### ISSUE TITLE
bug: 500 internal server error after refreshing page . 

### ISSUE THREAD

**Issue by umiecornxig** [apache/apisix#10001]
### Current Behavior

**I am new using Apache apisix** , whereas I'm encountered with a bug in Apisix.
I've installed and configured Apisix  on docker and it works fine  for me .
once I configured route I'm successfully using it on Browser (**Chrome,Edge**).

- **But after some time if I **Hard refresh** or reload page  I'm getting 500 internal server error and after few minutes it gets fixed itself.**

- **I've also configured SSL using Apisix dashbord and it works fine .**
- Also checked upstream it also works fine .

### Expected Behavior

It Should have worked fine even after refreshing page and not given 500 internal server Error.

### Error Logs

**[error] 50#50: 84150228 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/init.lua:332: attempt to index local 'matched_ssl' (a nil value)**
stack traceback:
coroutine 0:
        **/usr/local/apisix/apisix/init.lua: in function 'verify_https_client'
        /usr/local/apisix/apisix/init.lua:560: in function 'http_access_phase'**
        access_by_lua(nginx.conf:336):2: in main chunk, client: 192.168.100.157, server: _, request: "GET / HTTP/2.0", host: "mydomain.com:9443"
192.169.100.159 - - [10/Aug/2023:04:45:42 +0000] mydomain.com:9443 "GET / HTTP/2.0" 500 651 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36" - - -

### Steps to Reproduce

Run docker procedure provided on documentation 
Set up SSL using Apisix Dashboard .
Set Upstream using Apisix  Dashboard .
Configured rout with upstream and host .

### Environment

I'm using Docker on Centos 7.
And followed documentation provided by latest **version 3.4** on Apisix.

**Comment by Revolyssup** [comment]
This issue is same as these other two issues -
https://github.com/apache/apisix/issues/9610
https://github.com/apache/apisix/issues/9962

You can track the above issues. Rolling back to 3.3.0 had solved the problem. Also this was coming on specific browsers.

**Comment by umiecornxig** [comment]
Is rolling back from LTS to some other version is really long time Solution ?

**Comment by Revolyssup** [comment]
> Is rolling back from LTS to some other version is really long time Solution ?

No, that is why we are still tracking the problem in those other issues.
