### ISSUE TITLE
`_meta.error_response` not effective if configured on the auth plugin on consumer

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10002]
## Description

Testing with the `jwt-auth` plugin as [suggested in the doc](https://apisix.apache.org/docs/apisix/terminology/plugin/#custom-error-response). Result: `_meta.error_response` is not effective if configured on the `jwt-auth` plugin on consumer. It is effective if configured on route. For details, see the tests below.

This behaviour is unintuitive and unexpected since auth plugin details are typically configured on consumers.

**Would like to understand why this is the case and if it is the intended behaviour.**

### 1. Configure `_meta.error_response` on Consumer

Create a consumer: 

```bash
curl "http://127.0.0.1:9180/apisix/admin/consumers" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "username": "tom",
  "plugins": {
     "jwt-auth": {
        "key": "user-key",
        "_meta": {
          "error_response": {
                "message": "TESTING FOR ERROR RESPONSE"
           }
        }
     }
  }
}'
```

Create a route: 

```bash
curl "http://127.0.0.1:9180/apisix/admin/routes" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "id": "jwt-auth-route",
  "uri": "/ip",
  "plugins": {
    "jwt-auth": {}
},
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

Sending requests without JWT token, we see that the error message is not the one we customized:

```bash
curl "http://127.0.0.1:9080/ip"

{"message":"Missing JWT token in request"} 
```

```bash
curl http://127.0.0.1:9080/ip?jwt=123456

{"message":"JWT token invalid"}
```

### 2. Configure `_meta.error_response` on Route

Create a consumer: 

```bash
curl "http://127.0.0.1:9180/apisix/admin/consumers" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "username": "tom",
  "plugins": {
     "jwt-auth": {
        "key": "user-key"
     }
  }
}'
```

Create a route: 

```bash
curl "http://127.0.0.1:9180/apisix/admin/routes" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "id": "jwt-auth-route",
  "uri": "/ip",
  "plugins": {
    "jwt-auth": {
        "_meta": {
          "error_response": {
                "message": "TESTING FOR ERROR RESPONSE"
           }
        }
    }
},
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

Sending requests without JWT token, we see that the error message is now the one we customized:

```bash
curl "http://127.0.0.1:9080/ip"

{"message":"TESTING FOR ERROR RESPONSE"}
```

```bash
curl http://127.0.0.1:9080/ip?jwt=123456

{"message":"TESTING FOR ERROR RESPONSE"}
```

## Environment

APISIX 3.2.0

**Comment by yuluo-yx** [comment]
I will do it in next week, please assign to me!

**Comment by leslie-tsang** [comment]
> curl "http://127.0.0.1:9080/ip"

This test request does not trigger any consumer, that's why apisix echo the raw response.
Try to config the `_meta.error_reponse` in `Route` may meet your need, :)

**Comment by kayx23** [comment]
Confirmed with @leslie-tsang that it was the intended behaviour. 

Example scenario: return different fixed error msgs for JWT token verification failure by route, such as different IT Admin contact information for different route.
