### ISSUE TITLE
apisix Whether to support multiple ports

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10007]
### Description

Does apisix support multi-port access? At present, access can only be accessed through 9080 proxy access, I want to access through multiple ports, similar to nginx, nginx can configure multiple ports for access
![image](https://github.com/apache/apisix/assets/39228009/168ca3a4-d00d-41c4-8e99-ddd3d97c3b65)

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by diegozhu** [comment]
yes . it dose

```
apisix:
    node_listen:
      - port: 80
      - port: 8081

**Comment by Revolyssup** [comment]
@githubxubin `node_listen` can be both a single port number or an array as shown in above comment.

**Comment by githubxubin** [comment]
> @githubxubin `node_listen` can be both a single port number or an array as shown in above comment.

thank you for your reply,and how confifure multiple ports of https?  Looking forward your reply ~ tks

**Comment by githubxubin** [comment]
> thank you for your reply,and how confifure multiple ports of https? Looking forward your reply ~ tks

thank you for your reply,and how confifure multiple ports of https? Looking forward your reply ~ tks
