### ISSUE TITLE
docs: There is an error in the grpc-transcode.md

### ISSUE THREAD

**Issue by Brhetty** [apache/apisix#10006]
### Current State

https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/grpc-transcode.md

![lQLPJxse7iSp_XzNAQHNBSSwu0POqUfUMIEEypebo0AwAA_1316_257](https://github.com/apache/apisix/assets/60052175/7eafb3e1-4cc7-41c3-9bf3-8d99e362c9fc)

![lQLPJv9o3x9qfXzNAkPNBH-wM-OQTIUQxnoEypebqMAwAA_1151_579](https://github.com/apache/apisix/assets/60052175/3d5b6798-bfe1-453f-ab37-4ab7728a98ee)

### Desired State

fix

**Comment by shreemaan-abhishek** [comment]
Would you like to raise a PR? @Brhetty

**Comment by yuluo-yx** [comment]
@shreemaan-abhishek Please assign to me, I will try solve it.

**Comment by yuluo-yx** [comment]
@Brhetty Hello, can you explain the problem you encountered in detail, I didn't understand what you said

**Comment by yuluo-yx** [comment]
@shreemaan-abhishek Please also add the Waiting for Feedback tag🫡
