### ISSUE TITLE
I want to add a new plugin to Apisix without restarting Apisix

### ISSUE THREAD

**Issue by ww530220264** [apache/apisix#10018]
### Description

As shown in the question，here are my steps, but they have not taken effect：

1、Define extra_lua_path "/xx/?.lua" in apisix's config file ("/usr/local/apisix/conf/config.yaml")
2、Add new plugin's lua into the package of extra_lua_path ("/xx/new-plugin.lua")
3、Add "- new-plugin" to the plugins block of apisix's config file ("/usr/local/apisix/conf/config.yaml")
4、Sent a request to apisix through admin api (curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT)
5、But there is no new-plugin info in the json by a call to apisix （http://ip:port/v1/schema ) 

### Environment

- APISIX version (run `apisix version`):3.2.2
- Operating system (run `uname -a`): Linux apisix-test-322-5ff457b9b6-m4shw 5.4.236-1.el7.elrepo.x86_64 #1 SMP Mon Mar 13 21:36:53 EDT 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT

This method can only reload the code written in existing plugins but cannot load new plugins.

**Comment by ww530220264** [comment]
> > curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT
> 
> This method can only reload the code written in existing plugins but cannot add new plugins. And I don't think there is a way to add new plugins without restarting APISIX.

Thanks a lot~
