### ISSUE TITLE
Apache APISix - Kubernetes services discovery method configuration: 

### ISSUE THREAD

**Issue by Gokulk7** [apache/apisix#10019]
### Description

Image version: 3.4.0

 Kubernetes services discovery method configuration is required for our requirement. Any reference documents will be very help full.

 
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
apisix  apisix          2               2023-08-14 08:33:39.346215428 +0000 UTC deployed        apisix-2.1.0    3.4.0

### Environment-
- Deployment : Helm chart based deployment
- APISIX version (run `apisix version): 3.4.0
- Operating system (run `uname -a`): AWS EC2

**Comment by shreemaan-abhishek** [comment]
Is this what you are looking for: https://apisix.apache.org/docs/apisix/discovery/kubernetes/?
