### ISSUE TITLE
bug: some test case failed

### ISSUE THREAD

**Issue by anp510** [apache/apisix#10011]
### Current Behavior

When I use the steps on the official website and install apisix and test with source code, why can’t I pass some test cases?

### Expected Behavior

test case  pass

### Error Logs

<img width="1097" alt="image" src="https://github.com/apache/apisix/assets/142106157/f32561ae-a680-4007-8d09-f632bf69f980">

### Steps to Reproduce

1. Install apisix from source code
2. Install nginx::test
3. run test case  t/xrpc/pingpong.t

### Environment

- APISIX version (run `apisix version`):  3.4.0, branch of master
- Operating system (run `uname -a`):  centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):   nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by Revolyssup** [comment]
@anp510 can you share the relevant error logs from t/servroot when you run this test?

**Comment by shreemaan-abhishek** [comment]
@anp510, the xrpc tests will only pass after making some configurations:
https://github.com/shreemaan-abhishek/apisix/blob/c1dc1553c6b2dbae3d385d34a1c930e2e3c9126d/t/xrpc/pingpong.t#L33-L37

**Comment by anp510** [comment]
> @anp510 can you share the relevant error logs from t/servroot when you run this test?
The full text is too long, the final fragment is as follows：

2023/08/14 14:08:02 [info] 4115#4115: *21 [lua] config_etcd.lua:627: sync_data(): waitdir key: /apisix/consumers prev_index: 38509, context: ngx.timer
2023/08/14 14:08:02 [info] 4115#4115: *21 [lua] config_etcd.lua:628: sync_data(): res: {"headers":{"X-Etcd-Index":"38521"},"body":{"node":[{"createdIndex":38521,"key":"/apisix/consumers/","modifiedIndex":38521}]}}, err: nil, context: ngx.timer
2023/08/14 14:08:02 [info] 4114#4114: *53 [lua] config_etcd.lua:117: produce_res(): append res: {
  result = {
    events = { {
        kv = {
          create_revision = "38521",
          key = "/apisix/consumers/",
          mod_revision = "38521",
          version = "1"
        }
      },
      <metatable> = {}
    },
    header = {
      cluster_id = "14841639068965178418",
      member_id = "10276657743932975437",
      raft_term = "5",
      revision = "38521"
    }
  }
}, err: nil, context: ngx.timer
2023/08/14 14:08:02 [info] 4114#4114: *49 [lua] config_etcd.lua:406: http_waitdir(): http_waitdir: {
  result = {
    events = { {
        kv = {
          create_revision = "38521",
          key = "/apisix/consumers/",
          mod_revision = "38521",
          version = "1"
        }
      },
      <metatable> = {}
    },
    header = {
      cluster_id = "14841639068965178418",
      member_id = "10276657743932975437",
      raft_term = "5",
      revision = "38521"
    }
  }
}, context: ngx.timer
2023/08/14 14:08:02 [info] 4114#4114: *49 [lua] config_etcd.lua:627: sync_data(): waitdir key: /apisix/consumers prev_index: 38509, context: ngx.timer
2023/08/14 14:08:02 [info] 4114#4114: *49 [lua] config_etcd.lua:628: sync_data(): res: {"headers":{"X-Etcd-Index":"38521"},"body":{"node":[{"createdIndex":38521,"key":"/apisix/consumers/","modifiedIndex":38521}]}}, err: nil, context: ngx.timer
2023/08/14 14:08:02 [notice] 4113#4113: signal 15 (SIGTERM) received from 4050, exiting
2023/08/14 14:08:02 [notice] 4114#4114: exiting
2023/08/14 14:08:02 [notice] 4115#4115: exiting
2023/08/14 14:08:02 [notice] 4115#4115: cleanup wasm vm: wasmtime
2023/08/14 14:08:02 [notice] 4114#4114: cleanup wasm vm: wasmtime
2023/08/14 14:08:02 [notice] 4115#4115: exit
2023/08/14 14:08:02 [notice] 4114#4114: exit
2023/08/14 14:08:02 [notice] 4113#4113: signal 17 (SIGCHLD) received from 4115
2023/08/14 14:08:02 [notice] 4113#4113: privileged agent process 4115 exited with code 0
2023/08/14 14:08:02 [notice] 4113#4113: signal 29 (SIGIO) received
2023/08/14 14:08:02 [notice] 4113#4113: signal 17 (SIGCHLD) received from 4114
2023/08/14 14:08:02 [notice] 4113#4113: worker process 4114 exited with code 0
2023/08/14 14:08:02 [notice] 4113#4113: exit
2023/08/14 14:08:02 [notice] 4113#4113: cleanup wasm vm: wasmtime

**Comment by anp510** [comment]
2023/08/14 14:08:01 [warn] 4114#4114: *60 stream [lua] xrpc.lua:117: run_protocol(): run_protocol while prereading client data, client: 127.0.0.1, server: 0.0.0.0:1985
2023/08/14 14:08:01 [info] 4114#4114: *60 stream [lua] init.lua:86: from_downstream(): call pingpong's from_downstream while prereading client data, client: 127.0.0.1, server: 0.0.0.0:1985
2023/08/14 14:08:01 [info] 4114#4114: *60 stream [lua] init.lua:101: from_downstream(): send heartbeat while prereading client data, client: 127.0.0.1, server: 0.0.0.0:1985
2023/08/14 14:08:01 [info] 4114#4114: *60 stream [lua] init.lua:86: from_downstream(): call pingpong's from_downstream while prereading client data, client: 127.0.0.1, server: 0.0.0.0:1985
2023/08/14 14:08:02 [info] 4115#4115: *84 [lua] timers.lua:39: run timer[plugin#server-info], context: ngx.timer
2023/08/14 14:08:02 [error] 4114#4114: *27 lua tcp socket read timed out, client: 127.0.0.1, server: localhost, request: "POST /t HTTP/1.1", host: "localhost"
2023/08/14 14:08:02 [info] 4114#4114: *60 stream [lua] init.lua:1114: stream_log_phase(): enter stream_log_phase—————————————————————————— while prereading client data, client: 127.0.0.1, server: 0.0.0.0:1985
2023/08/14 14:08:02 [warn] 4114#4114: *27 using uninitialized "upstream_scheme" variable while logging request, client: 127.0.0.1, server: localhost, request: "POST /t HTTP/1.1", host: "localhost"
2023/08/14 14:08:02 [warn] 4114#4114: *27 using uninitialized "upstream_host" variable while logging request, client: 127.0.0.1, server: localhost, request: "POST /t HTTP/1.1", host: "localhost"
2023/08/14 14:08:02 [warn] 4114#4114: *27 using uninitialized "upstream_uri" variable while logging request, client: 127.0.0.1, server: localhost, request: "POST /t HTTP/1.1", host: "localhost"
