### ISSUE TITLE
help request: Use the curl test to create upstream and route through the API, and the dashboard can directly delete the upstream

### ISSUE THREAD

**Issue by god12311** [apache/apisix#10010]
### Description

Dear All:

  I use the curl test to create upstream and route through the API, and the dashboard can directly delete the upstream,There is a binding relationship between upstream and route, and the business domain name can be accessed normally.

`
curl https://xxx.net/apisix/admin/upstreams/1691811771 -H 'X-API-KEY: xxxxxxxx' -X PUT -d @upstream.json

###  cat upstream.json
{
      "type": "roundrobin",
      "name": "upstream-xxx",
      "desc": "upstream xxxx",
      "retries": 1,
      "timeout": {  
            "connect":15,
            "send":15,
            "read":15
        },
      "scheme": "http",
      "nodes": {
        "xxx.xxx.svc.cluster.local": 100
      }
    }

curl https://xxx.net/apisix/admin/upstreams/1691811772 -H 'X-API-KEY: xxxxxx' -X PUT -d @upstream-1.json
### cat upstream-1.json
{
      "type": "roundrobin",
      "name": "upstream-xxxx-1",
      "desc": "upstream xxxxx-1",
      "retries": 1,
      "timeout": {  
            "connect":15,
            "send":15,
            "read":15
        },
      "scheme": "http",
      "nodes": {
        "xxx-1.xxx.svc.cluster.local": 100
      }
    }

curl https://xxxx.net/apisix/admin/routes/1691811771 -H 'X-API-KEY: xxxxx' -X PUT -d @route.json

### cat route.json
{
      "methods": [],
      "status": 1,
      "name": "xxxx.test.net",
      "desc": "route xxxx",
      "host": "xxxx.test.net",
      "uri": "/*",
      "plugins": {
            "traffic-split": {
                "rules": [
                    {
                        "weighted_upstreams": [
                            {
                                "upstream_id": 1691811772
                            },
                            {
                                "weight": 0
                            },
                            {
                                "weight": 100
                            }
                        ]
                    }
                ]
            }
        },
            "upstream_id": 1691811771
        }

`

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Helm APISIX Chart: apisix-1.3.1
- Operating system (run `uname -a`): 4.19.84-300.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.9
- APISIX Dashboard version, if relevant: 3.0.0
- Helm APISIX Dashboard Chart: apisix-dashboard-0.8.1

**Comment by Revolyssup** [comment]
@god12311 Can you elaborate what exactly are you proposing or needing help on? Are you saying that the dashboard shouldn't be allowed to delete the upstream which is referenced in a route?

**Comment by god12311** [comment]
Hello, the problem I found is that when the upstream and route are created through the curl api, and there is a binding relationship, the dashboard can directly delete the upstream in use

**Comment by Revolyssup** [comment]
@god12311 Yes this is by design because they are independent resources. They are used together. APISIX doesn't maintain a dependency counter like thing to check if a resource can be deleted or not. This is a feature that maybe the dashboard can offer but it is no longer maintained.

**Comment by god12311** [comment]
The data will eventually fall into etcd. Is there any difference between Dashboard fetching data from etcd?

**Comment by Revolyssup** [comment]
@god12311 yes the data will fall into etcd but routes or upstreams can be deleted independently from etcd even if one references the other.

**Comment by god12311** [comment]
Both read and write data from etcd. I understand that there is also a binding relationship between them. No matter how the route and upstream are created, if there is binding, the upstream cannot be deleted directly, which is also basic security. It's a rule, but it's not the case in my test

**Comment by Revolyssup** [comment]
Currently you can delete an upstream even if it is bind to a route by design. I am labelling this as an enhancement request.

**Comment by god12311** [comment]
Is this a bug? Because if it is created through the dashboard, the upstream cannot be deleted if there is a binding relationship。

Only the upstream and route created through the api will be deleted even if there is a binding relationship。

**Comment by god12311** [comment]
I solve the problem, it is an id type problem, I can use a string

**Comment by Revolyssup** [comment]
> Is this a bug? Because if it is created through the dashboard, the upstream cannot be deleted if there is a binding relationship。
> 
> Only the upstream and route created through the api will be deleted even if there is a binding relationship。

That must be a dashboard functionality

**Comment by Revolyssup** [comment]
> I solve the problem, it is an id type problem, I can use a string

Then you can close the issue.

**Comment by god12311** [comment]
Thank you
