### ISSUE TITLE
I want to define a routing rule that url can be rewritten based on request parameters;

### ISSUE THREAD

**Issue by Hectorsong** [apache/apisix#10020]
### Description

The request url and parameter can be supposed as belows:
/tx/v3?serviceId=600000
/tx/v3?serviceId=600001
...
I want to rewrite url and parameter by one routing rule, and the request parameter can be extracted through regular expressions, in order to rewrite url as belows:
/tx/service/600000
/tx/service/600001
...
Does this APISIX feature already exist or will be implemented in the future?
Thanks a lot.

**Comment by shreemaan-abhishek** [comment]
@Hectorsong, is your query resolved? If yes, then you may close this issue.
