### ISSUE TITLE
Feat: Upgrade dependency version

### ISSUE THREAD

**Issue by yuluo-yx** [apache/apisix#10023]
### Description

Upgrade dependency version.

<html>
<body>

components|old version|upgrade|reason|new version|github repo| changelog
-- | -- | -- | -- | -- | -- | --
lua-resty-ctxdump | 0.1-0 | no |   |   |  
lua-resty-template | 2.0 | no |   |   |  
lua-resty-etcd | 1.10.4 | no |   |   |  
lua-resty-balancer | 0.04 | no |   |   |  
lua-resty-ngxvar | 0.5.2 | no |   |   |  
lua-resty-jit-uuid | 0.0.7 | no |   |   |  
lua-resty-healthcheck-api7 （Jump） | 3.0.0 | no |   |   |  
lua-resty-hmac-ffi | 0.05 | yes|  Recommended upgrade, few changes| 0.06-1 | https://github.com/jkeys089/lua-resty-hmac |  No changelog, specific commit submission behavior: https://github.com/jkeys089/lua-resty-hmac/compare/v0.05...0.06-1 <br>Major updates:<br>1. adding sha384 to ALGOS table <br>2. Fix CI issues in their projects.
lua-resty-cookie | 0.1.0 | TBD | TBD | 0.2.0-1 | https://github.com/utix/lua-resty-cookie | No changelog, specific commit submission behavior: https://github.com/utix/lua-resty-cookie/compare/v0.1.0...v0.2.0<br>Major updates:<br>1. feat: add None as a valid SameSite value https://github.com/utix/lua-resty-cookie/commit/a2cb7798133d891510bd37340390314644083da92.<br>2. Add a get_cookie_size function to retrieve cookie size <br>3. Add a get_cookie_size function to retrieve cookie size https://github.com/utix/lua-resty-cookie/commit/bfd38f3b45eb702f9f969f2983d846f83bb1b3f53. <br>4. Expose the bake function as get_cookie_string https://github.com/utix/lua-resty-cookie/commit/9ecca85a37f946575d40b12de9e6a1a39c128b68
lua-resty-session | 3.10 | yes | Updates are mostly bug fixes | 4.0.4-1 | https://github.com/bungle/lua-resty-session | changelog content：<br>1. V4.0.4 chore(utils): remove dependency for lua_pack, fix #158<br>2. V4.0.3 fix(*): redis authorization<br>3. V4.0.2 fix(*): hkdf is not approved by FIPS, use PBKDF2 instead on FIPS-mode <br>4.V4.0.1   Fixes:fix(session): clear_request cookie to check remember_meta correctly before using it   <br> Add：<br>1. feat(opm): add more dependencies in requires;<br>2. feat(opm): add right version number requirements<br>3. docs(readme): add remark on dependencies on installation section
opentracing-openresty | 0.1 | no| |   |   |  
lua-protobuf | 0.4.1 | yes| Updates are mostly bug fixes | 0.5.0-1 | https://github.com/starwing/lua-protobuf | No changelog, specific commit submission behavior: https://github.com/starwing/lua-protobuf/compare/0.4.1...0.5.0<br>Major updates:<br>1. bug fixes and feat
lua-resty-openidc | 1.7.5 | TBD | TBD | 1.7.6-3 | https://github.com/zmartzone/lua-resty-openidc |  No changelog, specific commit submission behavior: https://github.com/zmartzone/lua-resty-openidc/compare/v1.7.5...v1.7.6<br>Major updates:<br>1. support for response_mode form_post https://github.com/zmartzone/lua-resty-openidc/commit/789cf8ac48086b95c8522cb7b34bf63252341968 <br>2. make sure request is rejected for the correct reason  https://github.com/zmartzone/lua-resty-openidc/commit/3ba8fe14db0356426a043d37c3ba929f6f4c1995 <br>3. improve error message when bearer token header is malformed https://github.com/zmartzone/lua-resty-openidc/commit/a468d13283d62ef5e3d14f02404294f7777c053d <br>4. make tests independent of nginx config file buffer size https://github.com/zmartzone/lua-resty-openidc/commit/b723124bdd751bd9f5b58bd1dc5584c897aa2d38 <br>5. ……
luafilesystem | 1.7.0-2 | TBD | TBD | 1.8.0-1 | https://github.com/lunarmodules/luafilesystem |  No changelog, specific commit submission behavior: https://github.com/lunarmodules/luafilesystem/compare/v1_7_0_2...v1_8_0
nginx-lua-prometheus | 0.20221218 | TBD | TBD | 0.20230607-1 | https://github.com/knyar/nginx-lua-prometheus |  No changelog, specific commit submission behavior: https://github.com/knyar/nginx-lua-prometheus/compare/0.20221218...0.20230607<br>Major updates:<br>1. Add more details to the label count error message<br>2. Do not attempt to concatenate nil values<br>3. Explicitly check for nil label valuesknyar committed 988be4d
lua-resty-ipmatcher | 0.6.1 | no| |   |   |  
lua-resty-kafka | 0.20-0 | yes | Updates are mostly bug fixes | 0.22-0 | https://github.com/doujiang24/lua-resty-kafka |  No changelog, specific commit submission behavior: https://github.com/doujiang24/lua-resty-kafka/compare/v0.20...v0.22<br>Major updates:<br>1. fix: api_version not used while producing to kafka<br>2. feature: resty.kafka support SCRAM-SHA-256和SCRAM-SHA-512<br>3. fix: handle unknown errcode4.
lua-resty-logger-socket | 2.0.1-0 | no| |   |   |  
skywalking-nginx-lua | 0.6.0 |no ||   |   |  
base64 | 1.5-2 | yes | Minor changes | 1.5-3 | https://github.com/iskolbin/lbase64 | No changelog, specific commit submission behavior: https://github.com/iskolbin/lbase64/compare/v1.5.2...v1.5.3 <br>Major updates:<br>1. updated extract function for 5.4+
binaryheap | 0.4 | no ||  |   |  
resty-redis-cluster | 1.02-4 | TBD | TBD | 1.05-1 | https://github.com/steve0511/resty-redis-cluster |  No changelog, specific commit submission behavior: https://github.com/steve0511/resty-redis-cluster/compare/1.02...1.05 <br>Major updates:<br>1. Add refresh_slots method with lock to fetch slots to avoid cluster sl…<br>2. ngx.req.start_time is not available when using this client in the wor…<br>3. Ensure configured serv_list is available when fetching slots
lua-resty-expr | 1.3.2 | no ||   |   |  
graphql | 0.0.2 | no| |   |   |  
argparse | 0.7.1-1 | no||   |   |  
luasocket | 3.1.0-1 | no| |  |   |  
luasec | 0.9-1 | TBD | TBD | 1.3.1-1 | https://github.com/brunoos/luasec |  No changelog, specific commit submission behavior: https://github.com/brunoos/luasec/compare/v0.9...v1.3.1
lua-resty-consul | 0.3-2 | no||   |   |  
penlight | 1.13.1 | no||   |   |  
ext-plugin-proto | 0.6.0 | no| |  |   |  
casbin | 1.41.5 | yes | Updates are mostly bug fixes | 1.41.8-1 | https://github.com/casbin/lua-casbin | changelog content：<br>1. V1.41.6 bug fixes: rockspec url protocol (#146) (e9ebbac)<br>2. V1.41.7 bug fixes: Revert 146 fix protocol and fix rockspec (#147) (459278e), closes #146<br>3. V1.41.8 bug fixes: fix broken links (#151) (24bd8d6)
inspect | 3.1.1 | TBD | TBD | 3.1.3-0 | https://github.com/kikito/inspect.lua |  No changelog, specific commit submission behavior: https://github.com/kikito/inspect.lua/compare/v3.1.1...v3.1.3<br>Major updates:<br>1. ignore metatables with __metatable field set to non-nil non-table values<br>2. allow using inspect inside __tostring metamethods without errors<br>3. escape DEL character. fixes<br>4. (refactor) rewrite using Teal <br>5. (perf) introduce perf test harness and refactor
lualdap | 1.2.6-1 | TBD | TBD | 1.3.1-1 | https://github.com/lualdap/lualdap |  No changelog, specific commit submission behavior: https://github.com/lualdap/lualdap/compare/v1.2.6...v1.3.1<br>Major updates:<br>1. Add scope="subtree" to search example<br>2. src/lualdap.c: fix search with multiple attrs<br>3. refactor lualdap_open_simple by calling lualdap_open4. add lualdap_open5. refactor lualdap_open_simple by calling lualdap_bind_simple
lua-resty-rocketmq | 0.3.0-0 | yes | Minor changes | 0.4.1-0 | https://github.com/yuz10/lua-resty-rocketmq | changelog：<br>1. V0.3.1-0 Support rocketmq serial type <br> 2. V0.4.1-0 Compat rocketmq 4.9.4, which changes GET_ROUTEINFO_BY_TOPIC protocol to standard apache/rocketmq#4432
opentelemetry-lua | 0.2-3 | TBD | TBD | 0.2.4 | https://github.com/yangxikun/opentelemetry-lua | |No changelog, specific commit submission behavior: https://github.com/yangxikun/opentelemetry-lua/compare/v0.2.3...v0.2.4
net-url | 0.9-1 | no ||   |   |  
xml2lua | 1.5-2 | no ||   |   |  
nanoid | 0.1-1 | no | |  |   |  
lua-resty-mediador | 0.1.2-1 | no| |   |   |  
lua-resty-ldap | 0.2.2-0 | no ||   |   |  
lua-resty-t1k | 1.1.0 | no ||   |   |  
  |   | no ||   |   |  
lua-resty-radixtree | 2.8.2 | yes | Maintained by the api7 open source organization | 2.9.0-0 | https://github.com/api7/lua-resty-radixtree | api7 community maintenance
jsonschema | 0.9.8 | yes |Maintained by the api7 open source organization| 0.9.9-0 | https://github.com/api7/jsonschema | api7 community maintenance
api7-lua-resty-dns-client | 7.0.1 | no ||   | https://github.com/api7/lua-resty-dns-client/releases |  
api7-lua-resty-http | 0.2.0 | yes | Maintained by the api7 open source organization | 0.2.1 | https://github.com/api7/lua-resty-http/releases | api7 community maintenance
api7-lua-resty-jwt | 0.2.5 | no| |   | https://github.com/api7/lua-resty-jwt/releases |  
api7-lua-tinyyaml | 0.4.2 | yes| Maintained by the api7 open source organization | 0.4.3 | https://github.com/api7/lua-tinyyaml/releases | api7 community maintenance
api7-dkjson | 0.1.1 | no ||   | https://github.com/api7/test-toolkit |  

</body>
</html>

**Comment by yuluo-yx** [comment]
The current status of component updates is as follows (see the table above for details):
All components under the api7 organization are updated, and the status of the rest of the components is as follows
|name|status|
|--|--|
|lua-resty-hmac-ffi | yes |
|lua-resty-cookie | TBD |
| lua-resty-session | yes |
|lua-protobuf|yes|
|lua-resty-openidc|TBD|
|luafilesystem|TBD|
|nginx-lua-prometheus|TBD|
|lua-resty-kafka|yes|
|base64|yes|
|resty-redis-cluster|TBD|
|luasec|TBD|
|casbin|yes|
|inspect|TBD|
|lualdap|TBD|
|lua-resty-rocketmq|tes
|opentelemetry-lua|TBD|
| | |
|jsonschema | yes|
|lua-resty-radixtree|yes|
|api7-lua-resty-http|yes|
|api7-lua-tinyyaml|yes|

**Comment by Sn0rt** [comment]
lua-resty-hmac-ffi  (upgrade

lua-resty-cookie (upgrade

lua-resty-session (upgrade 

lua-protobuf (upgrade with single PR

lua-resty-openidc (upgrade

luafilesystem (no upgrade, bad effect for APISIX

nginx-lua-prometheus (upgrade with single PR

lua-resty-kafka (upgrade with single PR

resty-redis-cluster (upgrade with single PR

luasec (no upgrade

casbin (upgrade with single PR

inspect (no upgrade

All of the lib maintain by API7 need upgrade

**Comment by Sn0rt** [comment]
# notice
 
don't upgrade `lua-resty-session`, lua-resty-openidc  depends on lua-resty-session >= 2.8, <= 3.10
don't upgrade `luasec` 
don't upgrade `luafilesystem`
don't upgrade `inspect`
