### ISSUE TITLE
docs: Where can I find the LTS release versions?

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix#10022]
### Current State

I've found only this page 
`https://apisix.apache.org/downloads/`
where it is stated that 3.2.2 is an LTS version and 3.4.1 is the current release.

### Desired State

I should like to find a page where the LST releases are indicated with the relative release date.
Better If there will be the possibility to subscribe to be notified when a new LTS release is distribuited

**Comment by Revolyssup** [comment]
cc: @kayx23

**Comment by navendu-pottekkat** [comment]
@MirtoBusico Thanks for this suggestion. Meanwhile, you can try [watching this repository and add notifications](https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/managing-subscriptions-for-activity-on-github/viewing-your-subscriptions) only for releases. You can also [subscribe on Twitter](https://twitter.com/ApacheAPISIX) to get updates.

**Comment by MirtoBusico** [comment]
@navendu-pottekkat 
Thanks
