### ISSUE TITLE
feat: I hope that APISIX can support disabling access log writing for a specific route.

### ISSUE THREAD

**Issue by zsmlinux** [apache/apisix#10027]
### Description

Scenario: When a certain route has a huge amount of traffic and you do not want to record access logs, it is necessary to disable access log writing.

**Comment by yuluo-yx** [comment]
Good idea!

**Comment by kayx23** [comment]
Relevant issue: https://github.com/apache/apisix/issues/10407

**Comment by kayx23** [comment]
Relevant issue: https://github.com/apache/apisix/issues/10407

cc: @shreemaan-abhishek @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
Duplicated with https://github.com/apache/apisix/issues/10407
