### ISSUE TITLE
help request: use `serverless` plugin for different authentication approaches

### ISSUE THREAD

**Issue by lilililizheng** [apache/apisix#10036]
### Description

I would like to use the plugin Serverless for multiple authentication methods, for example, my upstream may be configured with ldap authentication servers or oidc etc., and I would like to be able to pass its authentication requests to different authentication servers directly based on the user's choice. Can you guys provide examples? Or is there a community of exchange?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lilililizheng** [comment]
The process I designed is that the user brings their authentication type (e.g. WeChat Authentication or Phone Authentication or Third Party Authentication), and the authentication is passed and a JWT token is generated and returned. Subsequent requests with the token will directly verify the token, but I do not know how to easily realize the choice of multiple authentication methods (after all, nowadays many apps can choose more than one login method)

**Comment by Sn0rt** [comment]
1. It is not recommended to use serverless plugin in production environment
2. It is not recommended for people without rich experience in openresty to use the serverless plugin
3. Simple authentication can be completed using the authentication plug-in.

https://apisix.apache.org/docs/apisix/plugins/jwt-auth/
https://apisix.apache.org/docs/apisix/plugins/openid-connect/

**Comment by Revolyssup** [comment]
@lilililizheng Do you need further assistance here?
