### ISSUE TITLE
docs: health-check Page Not Found

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10035]
### Current State

**Description of the current state/issue**:
404  Page Not Found

**Link to the page**:

 https://apisix.apache.org/zh/docs/apisix/admin-api/health-check.md/

**Screenshots (if relevant)**:

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by shreemaan-abhishek** [comment]
feel free to raise a PR.

**Comment by yuluo-yx** [comment]
@qyk1995 I didn't find the specific link address, can you take a screenshot to point out where it is

**Comment by yuluo-yx** [comment]
@shreemaan-abhishek Please assign to me, I will try solve it.

**Comment by yuluo-yx** [comment]
@yzeng25  I found that in the documentation of the apisix warehouse, his link address is correct, and when the clone apisix-website project, the link points to the wrong address

**Comment by yzeng25** [comment]
> @yzeng25 I found that in the documentation of the apisix warehouse, his link address is correct, and when the clone apisix-website project, the link points to the wrong address
> 
> ```
> `，其中 `arg_***` 是来自 URL 的请求参数，详细信息请参考 [NGINX 变量列表](http://nginx.org/en/docs/varindex.html)。 |                                                  |
> | checks         | 否                                             | health_checker | 配置健康检查的参数，详细信息请参考 [health-check](./tutorials/health-check.md)。 
> ```
> 
> Any Idea?


@yuluo-yx ,you meant `[health-check](./tutorials/health-check.md)` right?

**Comment by yuluo-yx** [comment]
> > @yzeng25 I found that in the documentation of the apisix warehouse, his link address is correct, and when the clone apisix-website project, the link points to the wrong address
> > ```
> > `，其中 `arg_***` 是来自 URL 的请求参数，详细信息请参考 [NGINX 变量列表](http://nginx.org/en/docs/varindex.html)。 |                                                  |
> > | checks         | 否                                             | health_checker | 配置健康检查的参数，详细信息请参考 [health-check](./tutorials/health-check.md)。 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any Idea?
> 
> @yuluo-yx ,you meant `[health-check](./tutorials/health-check.md)` right?

yes, Yes, you can refer to https://github.com/apache/apisix/tree/master/docs/zh/latest/tutorials,  This file does exist in this folder

**Comment by yuluo-yx** [comment]
@yzeng25 This is the content under the en language,
```
This is the content under the en language,
```
this link is reachable:
`https://apisix.apache.org/docs/apisix/tutorials/health-check/`

**Comment by yzeng25** [comment]
@yuluo-yx ,can you provide the link of the page that contains the dead link?

**Comment by yuluo-yx** [comment]
> @yuluo-yx，您能提供包含死链接的页面链接吗？

of cources, `https://apisix.apache.org/zh/docs/apisix/admin-api/health-check.md/`.

**Comment by yuluo-yx** [comment]
@yzeng25  of cources,
zh : `https://apisix.apache.org/zh/docs/apisix/admin-api/health-check.md/`.
en : `https://apisix.apache.org/docs/apisix/tutorials/health-check/`
The obvious difference between them is the path problem, but the path of apisix seems to be suitable, and the paths of zh and en are consistent

**Comment by yzeng25** [comment]
@yuluo-yx  You can raise a pull request with the following change in zh-cn doc:

`详细信息请参考 [health-check](./tutorials/health-check.md)`

**Comment by yuluo-yx** [comment]
> @yuluo-yx You can raise a pull request with the following change in zh-cn doc:
> 
> `详细信息请参考 [health-check](./tutorials/health-check.md)`

Sorry, I don't quite understand what you mean, the content of this document is just like this, no need to change.

**Comment by yzeng25** [comment]
@yuluo-yx  Change `./admin-api/health-check.md` to `./tutorials/health-check.md` will solve the problem.

**Comment by yzeng25** [comment]
@yuluo-yx , In zh-cn doc, the dead link problem occurs in this page: https://apisix.apache.org/zh/docs/apisix/admin-api/#upstream-body-request-methods

![image](https://github.com/apache/apisix/assets/36651058/0a8a1f18-8154-4a80-8882-77c669ea635a)

When digging into the link and doc revision history, the `health-check.md` file has been moved out of `admin-api` folder since https://github.com/apache/apisix/pull/8129, which was merged on Oct 25th, 2022.

On the other hand, the en-us doc is correct. So then you can raise a pull request to fix the problem in zh-cn doc. Open the `admin-api,md` file under zh-cn path, search for `./admin-api/health-check.md` and replace it with `./admin-api/health-check.md` should fix the problem.

To go a step forward, you can global search `./admin-api/health-check.md` and replace it with `./admin-api/health-check.md` in *all* files, so that you can fix the same problem occurs in all docs.

**Comment by yuluo-yx** [comment]
I can understand what you mean, but there is only one version of the latest folder under the apisix docs/zh folder.
In the latest version, the address of the zh docis the same as the address pointed to by the en doc.
you can see :  
- zh:  https://github.com/apache/apisix/blob/ac3992f55c5e2e93f685a4295149faa6eef48284/docs/zh/latest/admin-api.md?plain=1#L911
- https://github.com/apache/apisix/blob/ac3992f55c5e2e93f685a4295149faa6eef48284/docs/en/latest/admin-api.md?plain=1#L898C110-L898C148
they have the same address. 

```
docs
| -- turtorials
| -- | -- health-check.md
| -- admin-api.md (ref ./turtorials/health-check.md)
```
As shown above, I cannot modify the parent path of `admin-api.md`, I can only modify the reference file path in this `admin-api.md`

**Comment by yzeng25** [comment]
Oh ok, I see. Then we can come back and check when the next version is released. The changes in the `latest` folder should be able to actually show up in the web page along with the release of next version, @yuluo-yx .

**Comment by yuluo-yx** [comment]
> Oh ok, I see. Then we can come back and check when the next version is released. The changes in the `latest` folder should be able to actually show up in the web page along with the release of next version, @yuluo-yx .

ok, got it🫡
