### ISSUE TITLE
bug: does apisix support sse at now

### ISSUE THREAD

**Issue by LazyViper** [apache/apisix#10030]
### Current Behavior

Currently, we have found that apisix often interrupts sse's server push messages

### Steps to Reproduce

ESXI 6.7 running Kubernetes version 1.15.2 cluster, Centos7 host

### Environment

ESXI 6.7 running Kubernetes version 1.15.2 cluster, Centos7 host

**Comment by shreemaan-abhishek** [comment]
What is SSE?

**Comment by yuluo-yx** [comment]
> What is SSE?

Maybe he said this: SSE (Server-sent Events) is a lightweight alternative to WebSocket, using the HTTP protocol.

**Comment by LazyViper** [comment]
Yes, sse is a server-sent event. We found a disconnection during use, and the service message was interrupted before it was fully returned




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月19日(星期六) 凌晨0:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] bug: does pisix support sse at now (Issue #10030)





  
What is SSE?
  
Maybe he said this: SSE (Server-sent Events) is a lightweight alternative to WebSocket, using the HTTP protocol.

**Comment by shreemaan-abhishek** [comment]
Do you have any error logs to share?

**Comment by Revolyssup** [comment]
@LazyViper Please provide more information like your apisix configuration and your request/response. Access/Error logs if any?

**Comment by Revolyssup** [comment]
@LazyViper Can you provide some logs or configuration?

**Comment by Cairry** [comment]
I have the same problem, is there a solution to this problem?
When I pass through the apisix gateway, the sse request will be interrupted early, as follows

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/e7de29d8-f9e1-4adc-8777-f3c06d90f783" />

Without apisix gateway, everything works fine.

<img width="879" alt="Image" src="https://github.com/user-attachments/assets/d31c4097-5c15-4fb2-b643-2b5fc844a20e" />

**Comment by Baoyuantop** [comment]
@Cairry Can you provide some logs or configuration?

**Comment by a1156698162** [comment]
> I have the same problem, is there a solution to this problem? When I pass through the apisix gateway, the sse request will be interrupted early, as follows
> 
> <img alt="Image" width="871" src="https://private-user-images.githubusercontent.com/115769353/422157169-e7de29d8-f9e1-4adc-8777-f3c06d90f783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIwNDU5NDEsIm5iZiI6MTc1MjA0NTY0MSwicGF0aCI6Ii8xMTU3NjkzNTMvNDIyMTU3MTY5LWU3ZGUyOWQ4LWY5ZTEtNGFkYy04Nzc3LWYzYzA2ZDkwZjc4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcwOVQwNzIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMGQwZjFhNjYzZmZjMjgzZDA3OTBkZWM4Y2NmNjYwZGNhMDAwOGRmYjcyZGI0NzUxZmRhOWM3YmE1NTBjMTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2HgVlF2uOu7kquCf-ofWwvSwMH8AJ5vNcFjsN4eI-J4">
> Without apisix gateway, everything works fine.
> 
> <img alt="Image" width="879" src="https://private-user-images.githubusercontent.com/115769353/422159149-d31c4097-5c15-4fb2-b643-2b5fc844a20e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTIwNDU5NDEsIm5iZiI6MTc1MjA0NTY0MSwicGF0aCI6Ii8xMTU3NjkzNTMvNDIyMTU5MTQ5LWQzMWM0MDk3LTVjMTUtNGZiMi1iNjQzLTJiNWZjODQ0YTIwZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcwOVQwNzIwNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODk3MzJhMmE4MDU0NTA4NWZkMzRiOTg0Mzk2NDRiYzY3ZDE0ZTM5YTE3NWYzY2FkOTRmMjBlNDQ2ZmFhOGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cQQ1ziYg-_V-bh9PUUbjB4FM6TAzjMfPzs8gV_KZmTY">

@Cairry 你好，请问下你们是怎么解决这个问题的？

**Comment by Cairry** [comment]
@a1156698162 把相关的timeout配置久一点

**Comment by a1156698162** [comment]
@Cairry 好的，感谢

**Comment by a1156698162** [comment]
@Cairry 还有个问题想请教下，在sse场景apisix不需要额外配置(不用配置proxy_buffering)就支持流式输出。不过proxy_buffering默认是on的呀。这块原因您清楚吗？

**Comment by Cairry** [comment]
> [@Cairry](https://github.com/Cairry) 还有个问题想请教下，在sse场景apisix不需要额外配置(不用配置proxy_buffering)就支持流式输出。不过proxy_buffering默认是on的呀。这块原因您清楚吗？

依然选择默认配置就可以，另外buffer可以配置小一些。

**Comment by a1156698162** [comment]
> > [@Cairry](https://github.com/Cairry) 还有个问题想请教下，在sse场景apisix不需要额外配置(不用配置proxy_buffering)就支持流式输出。不过proxy_buffering默认是on的呀。这块原因您清楚吗？
> 
> 依然选择默认配置就可以，另外buffer可以配置大一些。

proxy_buffering 默认是on的。正常如果是on的话，流式响应不会立即返回，而是要等缓冲区满了一块返回。这个我用nginx试过。但是apisix却没有这个问题。不太清楚其中的原因。

**Comment by Cairry** [comment]
> > > [@Cairry](https://github.com/Cairry) 还有个问题想请教下，在sse场景apisix不需要额外配置(不用配置proxy_buffering)就支持流式输出。不过proxy_buffering默认是on的呀。这块原因您清楚吗？
> > 
> > 
> > 依然选择默认配置就可以，另外buffer可以配置大一些。
> 
> proxy_buffering 默认是on的。正常如果是on的话，流式响应不会立即返回，而是要等缓冲区满了一块返回。这个我用nginx试过。但是apisix却没有这个问题。不太清楚其中的原因。

我倒没验证过nginx，目前使用apisix也并没有出现延迟等问题。

**Comment by a1156698162** [comment]
> > > > [@Cairry](https://github.com/Cairry) 还有个问题想请教下，在sse场景apisix不需要额外配置(不用配置proxy_buffering)就支持流式输出。不过proxy_buffering默认是on的呀。这块原因您清楚吗？
> > > 
> > > 
> > > 依然选择默认配置就可以，另外buffer可以配置大一些。
> > 
> > 
> > proxy_buffering 默认是on的。正常如果是on的话，流式响应不会立即返回，而是要等缓冲区满了一块返回。这个我用nginx试过。但是apisix却没有这个问题。不太清楚其中的原因。
> 
> 我倒没验证过nginx，目前使用apisix也并没有出现延迟等问题。

是的，apisix没有延迟，就很神奇
