### ISSUE TITLE
https+ip enabled?

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10044]
### Description

Can I use https+ip for access to apisix? After I upload the certificate and enable https redirection, I find that I can only access through the domain name. Can I use the form of https://ip: port for access

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Did you find any error when you tried to acces using domain name?

**Comment by githubxubin** [comment]
> Did you find any error when you tried to acces using domain name?

Hello~~ the domain access is normal, now I want to ask whether the form of https+ip access is supported, can you understand my meaning

**Comment by shreemaan-abhishek** [comment]
My bad, I actually wanted to ask you:

Did you find any error when you tried to acces using ip:port? Please share the error here.

**Comment by githubxubin** [comment]
> My bad, I actually wanted to ask you:
> 
> Did you find any error when you tried to acces using ip:port? Please share the error here.

the error log is :

```
2023/08/18 03:01:11 [error] 45#45: *4100951 [lua] init.lua:172: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 192.168.88.66, server: 0.0.0.0:9443

```

**Comment by githubxubin** [comment]
> My bad, I actually wanted to ask you:
> 
> Did you find any error when you tried to acces using ip:port? Please share the error here.

Can you help with this?

**Comment by shreemaan-abhishek** [comment]
> After I upload the certificate and enable https redirection, I find that I can only access through the domain name.

@githubxubin, could you please provide me the detailed reproduction steps?

**Comment by githubxubin** [comment]
> eproduct

step 1:
Upload certificate by dashboard
step 2:
Access the corresponding route through https://ip+port


The steps are so simple

**Comment by shreemaan-abhishek** [comment]
I just realized, that the server (apisix) would require the hostname to match against the domain name (or Common Name 🤔) to which the CA issued the certificate. So if you access by IP+PORT, the server (apisix) does not have any way to perform matching with the common name given in the certificate.

**Comment by Revolyssup** [comment]
@githubxubin you can use the --resolve flag in curl to map this IP to a hostname for which you have configured the cert
