### ISSUE TITLE
docs: what is the syntax of {id} in apisix-admin api?

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix#10047]
### Current State

In the admin-api api chapter ( https://apisix.apache.org/docs/apisix/admin-api/ ) all the examples for defining SSL, Upstream and Route use an {id} 

In the Request methods it is indicated as {...}

In all examples this {id} is a numeric string

There is no explanation of the {id} syntax

### Desired State

Add the syntax rules for {id}:

1. is it numeric
2. is it a string

If it is a string:

1. what is the max length
2. what characters are allowed (letter, numbers, special as - _ . # @ )

**Comment by shreemaan-abhishek** [comment]
Following is the schema for {id}:

https://github.com/shreemaan-abhishek/apisix/blob/6e4347840727c54dd6b79a60e53afc1204938242/apisix/schema_def.lua#L30-L38

```lua
local id_schema = {
    anyOf = {
        {
            type = "string", minLength = 1, maxLength = 64,
            pattern = [[^[a-zA-Z0-9-_.]+$]]
        },
        {type = "integer", minimum = 1}
    }
}
```

**Comment by MirtoBusico** [comment]
Fantastic!
It is exactly what I needed!
