### ISSUE TITLE
help request: need Apisix configuration for a corresponding nginx location block

### ISSUE THREAD

**Issue by GreenRover** [apache/apisix#10055]
### Description

Is it possible to following nginx config:

```
        location ~ ^/concentrator/Halon2/xyz/det/(.*)$ {
            proxy_method POST;
            proxy_pass http://xyz-exporter:1920/endpoint?m.QueueDetails=EnterpriseDev-HalonOp2NP|$1;
            proxy_pass_request_body off;
            proxy_no_cache 1;
            proxy_cache_bypass 1;
            proxy_set_body scrapeURI=https%3A%2F%2Fconcenop2np-primary.xyz.com%3A32197&username=admin&password=xxxxxxx;
            proxy_set_header Content-Type "application/x-www-form-urlencoded";
        }
```

as apisix route in `apisix.yaml` (standlone mode)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
You can use the proxy-rewrite plugin to achieve this. Please refer - https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by GreenRover** [comment]
Is it possible to have _proxy_set_body_ with this module?

If yes, can you please provide me an example?

**Comment by Revolyssup** [comment]
@GreenRover You can use serverless plugin to modify the request body. https://apisix.apache.org/docs/apisix/plugins/serverless/

**Comment by Revolyssup** [comment]
@GreenRover Was your use case met?

**Comment by GreenRover** [comment]
I switched now back to plane nginx and let kubernetes handle the restarts
