### ISSUE TITLE
Unable to Access API Routes via HTTPS (Port 443) 

### ISSUE THREAD

**Issue by umiecornxig** [apache/apisix#10060]
### Description

Hello APIsix community,

I'm currently facing an issue with my APIsix setup where **I'm unable to access my API routes via HTTPS on port 443**. I've already taken the following steps:

**Uploaded an SSL certificate via the APIsix dashboard.**
**Running APIsix within Docker, mapping port 443 to the container.**
Configured routes to listen on both ports 443 and 9443.
Checked firewall settings and DNS configuration.
**Despite these efforts, I can successfully access the routes via example.com:9443/path, but I encounter an issue when attempting to access them via https://example.com/path.**

Setup Details:

APIsix Version: [3.3.0]

**Steps Taken:**
Uploaded SSL certificate via APIsix dashboard.
Ran Docker container with port mapping.
Verified firewall settings and DNS configuration.
Expected Behavior:
I expect to be able to access the API routes via HTTPS on port 443 (https://example.com/path).

**Additional Notes:**

Are there any known issues related to SSL configuration in APIsix?
Are there any specific logs I should be checking for more details?
Any help or guidance in resolving this issue would be greatly appreciated.

Thank you in advance for your assistance!

Best regards,
Umesh

### Environment

- APISIX version (run `3.3`):
-Running Using docker

**Comment by umiecornxig** [comment]
Earlier I was using Nginx and managed to listen on 443 , how can I achieve the same with Apisix to listen on 443.

**Comment by Revolyssup** [comment]
@umiecornxig What is the exact error that you get when accessing HTTPS? Also can you please share the error logs when you make request on 443?
