### ISSUE TITLE
help request: How to forward the parameter of   http://a.com/api/v1/admin/casbinPolicyList?sub=user  to http://b.com/api/v1/admin/casbinPolicyList?sub=use?

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10067]
### Description

How to forward the parameter of   http://a.com/api/v1/admin/casbinPolicyList?sub=user  to http://b.com/api/v1/admin/casbinPolicyList?sub=use?

I try  redirect  and proxy-rewrite  didn't work，How do I configure it？

![1692610828619](https://github.com/apache/apisix/assets/44867235/89e3e364-1a1f-4b8a-b6bc-7c7cebf859d1)

### Environment

- APISIX version (run `apisix version`): apache/apisix:3.2.0-debian
- Operating system (run `uname -a`): 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): docker.io/bitnami/etcd:3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@qyk1995 You can use redirect plugin with regex_uri to extract the parameters and then pass them onto a different URI

**Comment by Revolyssup** [comment]
@qyk1995 Refer to something like this https://github.com/apache/apisix/blob/1fd2613198e7640018ea5576d9935b828e25fb9f/t/plugin/redirect.t#L783

**Comment by qyk1995** [comment]
@Revolyssup  thank you answer, but   following   ?  value  no.   example   xxxxxx?sub=use



my config 

`  "plugins": {
    "redirect": {
      "regex_uri": [
        "/(.*)",
        "http://b.com/$request_uri"
      ],
      "ret_code": 301
    }
  },`
