### ISSUE TITLE
help request: Is Multiple plugin-runners Plugin Runner supported？

### ISSUE THREAD

**Issue by cod-soap** [apache/apisix#10064]
### Is Multiple plugin-runners Plugin Runner supported？

My team is a multi programming language environment and plan to do some work on apisix.
We want to develop Plugin Runners with different programming language,such as golang ,java ,python.
Look up the docs, I do not find a way to config multi Plugin Runner to run them in  debug mode or deployment mode.
This is my attempt to configure multiple steps:
1.debug mode:
```
ext-plugin:
  path_for_test: 
    - /tmp/runner.sock
    - /tmp/runner1.sock
```
2.deployment mode:
```
ext-plugin:
  # path_for_test: /tmp/runner.sock
  cmd:
    - ["/path/to/apisix-go-plugin-runner/go-runner", "run"]
    - ["/path/to/apisix-go-plugin-runner/go-runner1", "run"]
```

BUT,All attempts will result in apisix loading plugin errors when processing requests.

By reading the source code, It seems that multiple configurations are not supported:
![image](https://github.com/apache/apisix/assets/25627194/5ce6417c-92d7-4992-80fc-e63cd0cd142b)

###  So I want to confirm if Apisix official does not support configuring multiple ?

If developing multiple plugins, is the official recommended best practice to use the Lua language instead of Plugin Runner?

Sincerely hope for a reply,that means a lot to us!

### Environment

- APISIX version (run `apisix version`):   3.4 
- Operating system (run `uname -a`):Linux ubuntu 5.15.0-43-generic #46-Ubuntu SMP Tue Jul 12 10:30:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): run in docker

**Comment by Revolyssup** [comment]
Yes, `path_for_test` is a string, not an array. As given in the docs here[1], In the prod environment, path_for_test should not be used and the unix socket path will be generated dynamically. APISIX currently only runs one executable as a subprocess managed under it.
1. https://apisix.apache.org/docs/apisix/external-plugin/

**Comment by cod-soap** [comment]
> Yes, `path_for_test` is a string, not an array. As given in the docs here[1], In the prod environment, path_for_test should not be used and the unix socket path will be generated dynamically. APISIX currently only runs one executable as a subprocess managed under it.
> 
> 1. https://apisix.apache.org/docs/apisix/external-plugin/

Thank you very much for your answer.
