### ISSUE TITLE
help request:  Just getting started, got Header or Cookie Too large Error.

### ISSUE THREAD

**Issue by Alan-MQ** [apache/apisix#10078]
### Description

https://apisix.apache.org/docs/apisix/getting-started/configure-routes/

I did exactly what this documentation said
first I install this apisix like they said in the website
```sh
curl -sL https://run.api7.ai/apisix/quickstart | sh
```
and I test it
```sh
curl "http://127.0.0.1:9080" --head | grep Server
```
it goes like this 
<img width="1503" alt="image" src="https://github.com/apache/apisix/assets/109934126/ae6f931f-143c-4a18-923d-49aac6b73232">
And everything looks great even after I add this route like this 
```sh
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

but when I wan to access this new route /ip I got something like this
<img width="1495" alt="image" src="https://github.com/apache/apisix/assets/109934126/50df03bb-7d11-40aa-abbd-8fcd29ec50f6">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
You can try a few more times, the service of httpbin.org is not very stable, there may be errors.

**Comment by Revolyssup** [comment]
@Alan-MQ Are you still getting this error consistently?

**Comment by qihaiyan** [comment]
try adding this in config.yaml @Alan-MQ 
```
  http_configuration_snippet: |
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
```

**Comment by Alan-MQ** [comment]
> @Alan-MQ Are you still getting this error consistently?
yep, still getting this error, and I'm curious if I'm using `curl "http://127.0.0.1:9080" --head | grep Server` running everything in new container, and doing exactly as the website document said, then we should have a same enviroment right? why just me getting this? I'm on macbook if it helps~~

**Comment by Alan-MQ** [comment]
> http_configuration_snippet: |
>     proxy_buffer_size 128k;
>     proxy_buffers 4 256k;
>     proxy_busy_buffers_size 256k;

![image](https://github.com/apache/apisix/assets/109934126/1a5aff63-ca83-40e6-ab3d-1b6ecd7efda1)
still the same error after I modified the config.yaml and restart the container

**Comment by qihaiyan** [comment]
add 2 space before ```http_configuration_snippet``` @Alan-MQ 
> > http_configuration_snippet: |
> > proxy_buffer_size 128k;
> > proxy_buffers 4 256k;
> > proxy_busy_buffers_size 256k;
> 
> ![image](https://user-images.githubusercontent.com/109934126/263183205-1a5aff63-ca83-40e6-ab3d-1b6ecd7efda1.png) still the same error after I modified the config.yaml and restart the container

**Comment by Alan-MQ** [comment]
> add 2 space before `http_configuration_snippet` , and this snippet should be added before `deployment` @Alan-MQ
> 
> just like this:
> 
> ```
>                                                               # hooks. Only administrators should have
>   http_configuration_snippet: |
>     proxy_buffer_size 128k;
>     proxy_buffers 4 256k;
>     proxy_busy_buffers_size 256k;                                                              # write access to this file for security.
> 
> deployment:                    # Deployment configurations
>   role: traditional            # Set deployment mode: traditional, control_plane, or data_plane.
>   role_traditional:
>     config_provider: etcd      # Set the configuration center.
> ```

I got it , http_configuration_snippet should under the apisix  the same level with `control` right ? thank you for your help, but still the same error message.

**Comment by qihaiyan** [comment]
> > add 2 space before `http_configuration_snippet` , and this snippet should be added before `deployment` @Alan-MQ
> > just like this:
> > ```
> >                                                               # hooks. Only administrators should have
> >   http_configuration_snippet: |
> >     proxy_buffer_size 128k;
> >     proxy_buffers 4 256k;
> >     proxy_busy_buffers_size 256k;                                                              # write access to this file for security.
> > 
> > deployment:                    # Deployment configurations
> >   role: traditional            # Set deployment mode: traditional, control_plane, or data_plane.
> >   role_traditional:
> >     config_provider: etcd      # Set the configuration center.
> > ```
> 
> I got it , http_configuration_snippet should under the apisix the same level with `control` right ? thank you for your help, but still the same error message.

try add ```large_client_header_buffers 4 8k;``` in the ```http_configuration_snippet``` @Alan-MQ

**Comment by yidashi** [comment]
一样的问题，并没有解决

**Comment by rohitkrishna094** [comment]
Its still not working. Their own docs are not working on multiple VMs. Opened another issue [here](https://github.com/apache/apisix/issues/10078)
