### ISSUE TITLE
Eureka no valid upstream node

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#10071]
### Description

When I discovered using apisix's eureka service, I couldn't get the node on the registry

the error log:
```
2023/08/22 05:20:29 [error] 47#47: *477106 [lua] init.lua:540: http_access_phase(): failed to set upstream: no valid upstream node: nil, client: 192.168.88.66, server: _, request: "GET /eureka/home/ HTTP/1.1", host: "10.210.21.105:9080"

```
1.the route config:
```
{
    "id": "475035634029822659",
    "create_time": 1692672902,
    "update_time": 1692673262,
    "uri": "/eureka/*",
    "name": "Eureka",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": [
                "^/eureka(/|$)(.*)",
                "/$2"
            ]
        }
    },
    "upstream": {
        "retries": 1,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "discovery_type": "eureka",
        "discovery_args": {
            "group_name": "",
            "namespace_id": ""
        },
        "pass_host": "pass",
        "service_name": "EUREKA-CLIENT",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "labels": {
        "API_VERSION": "1.0"
    },
    "status": 1
}
```

2.the config.yaml :
```
discovery:
  eureka:
    host: # it's possible to define multiple eureka hosts addresses of the same eureka cluster.
      - "http://10.210.21.105:8761"
    prefix: "/eureka/"
```
3.and My eureka server  is normal:
![image](https://github.com/apache/apisix/assets/131146587/45589b92-76f9-4a93-83dd-084c88441efa)

4.the operate:
![image](https://github.com/apache/apisix/assets/131146587/bad58322-5d7d-440a-914a-7aab02009fa1)

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
This is a very generic APISIX error that occurs when APISIX is unable to find a valid upstream.

Most probably, eureka could not populate services into the upstream configuration. Or there were no valid discoverable services available.

**Comment by bin-53** [comment]
> This is a very generic APISIX error that occurs when APISIX is unable to find a valid upstream.
> 
> Most probably, eureka could not populate services into the upstream configuration. Or there were no valid discoverable services available.

I know apisix can't find upstream, but why can't it be found, eureka is normal, and the service node is registered normally. You can't say that the failure of apisix is the problem of the registration center. I wonder if you can help troubleshoot the problem. Instead of just translating the error message for me!!!
 tks

**Comment by bin-53** [comment]
> curl'ing /apisix/admin/services

How to check in apisix, can you send a complete command?

**Comment by Revolyssup** [comment]
`curl http://127.0.0.1:9180/apisix/admin/services \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

**Comment by bin-53** [comment]
> `curl http://127.0.0.1:9180/apisix/admin/services \ -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

Wonder why eureka is not registered in apisix?
```
[root@localhost apisix_log]# curl http://10.210.21.106:9080/apisix/admin/services  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
{"node":{"key":"\/apisix\/services","dir":true,"nodes":[]},"count":0,"action":"get"}
```

**Comment by bin-53** [comment]
> `curl http://127.0.0.1:9180/apisix/admin/services \ -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

here is eureka apps info :
```
<applications>
<versions__delta>1</versions__delta>
<apps__hashcode>UP_1_</apps__hashcode>
<application>
<name>EUREKA-CLIENT</name>
<instance>
<hostName>10.210.21.105</hostName>
<app>EUREKA-CLIENT</app>
<ipAddr>10.210.21.105</ipAddr>
<status>UP</status>
<overriddenstatus>UNKNOWN</overriddenstatus>
<port enabled="true">8883</port>
<securePort enabled="false">443</securePort>
<countryId>1</countryId>
<dataCenterInfo class="com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo">
<name>MyOwn</name>
</dataCenterInfo>
<leaseInfo>
<renewalIntervalInSecs>30</renewalIntervalInSecs>
<durationInSecs>90</durationInSecs>
<registrationTimestamp>1692673081218</registrationTimestamp>
<lastRenewalTimestamp>1692673081218</lastRenewalTimestamp>
<evictionTimestamp>0</evictionTimestamp>
<serviceUpTimestamp>1692340568680</serviceUpTimestamp>
</leaseInfo>
<metadata>
<management.port>8883</management.port>
</metadata>
<homePageUrl>http://10.210.21.105:8883/</homePageUrl>
<statusPageUrl>http://10.210.21.105:8883/actuator/info</statusPageUrl>
<healthCheckUrl>http://10.210.21.105:8883/actuator/health</healthCheckUrl>
<vipAddress>eureka-client</vipAddress>
<secureVipAddress>eureka-client</secureVipAddress>
<isCoordinatingDiscoveryServer>false</isCoordinatingDiscoveryServer>
<lastUpdatedTimestamp>1692673081219</lastUpdatedTimestamp>
<lastDirtyTimestamp>1692672689909</lastDirtyTimestamp>
<actionType>ADDED</actionType>
</instance>
</application>
</applications>
```

**Comment by Revolyssup** [comment]
@bin-53 What was the output of `curl http://localhost:9090/v1/discovery/eureka/dump`?
