### ISSUE TITLE
deleting plugin doesn't take effect

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#10084]
### Current Behavior

When I configured limit-count plugin on apisix route, it worked normally, but when I deleted this plugin on the route (limit-count), it did not take effect and still blocked my request, I think it is the cache problem of apisix, because when I restart apisix, it is not valid. Everything is normal

my route config now:
```
{
    "id": "475465871255405249",
    "create_time": 1692929343,
    "update_time": 1692933469,
    "uri": "/fuwu/*",
    "name": "group1",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "host": "yangcong.com.cn",
    "plugins": {
        "proxy-rewrite": {
            "scheme": "https"
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "192.168.96.177",
                "port": 19080,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
when my requert  /fuwu/1k.tx the error  log is:
```
2023/08/25 03:08:23 [warn] 49#49: *614877 [lua] plugin.lua:901: run_plugin(): limit-count exits with http status code 503, client: 192.168.88.66, server: _, request: "GET /fuwu/1k.txt?ces=1111 HTTP/1.1", host: "yangcong.com.cn:9080"
```
The current route does not have the limit-count plug-in, nor does the global plug-in

### Expected Behavior

It takes effect after the plugin is deleted and does not require a reboot. I wonder if apisix has a configuration to disable caching

### Error Logs

```
2023/08/25 03:08:23 [warn] 49#49: *614877 [lua] plugin.lua:901: run_plugin(): limit-count exits with http status code 503, client: 192.168.88.66, server: _, request: "GET /fuwu/1k.txt?ces=1111 HTTP/1.1", host: "yangcong.com.cn:9080"
```

### Steps to Reproduce

step 1  :
set route with limit-count:
```
{
    "id": "475465871255405249",
    "create_time": 1692929343,
    "update_time": 1692933794,
    "uri": "/fuwu/*",
    "name": "group1",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "host": "yangcong.com.cn",
    "plugins": {
        "limit-count": {
            "count": 2,
            "disable": false,
            "policy": "local",
            "time_window": 1
        },
        "proxy-rewrite": {
            "scheme": "https"
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "192.168.96.177",
                "port": 19080,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "discovery_args": {
            "group_name": "",
            "namespace_id": ""
        },
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
step 2:
access the route  it is normal

step 3:
delete route plugin limit-count

step 4:
access the same route again, This error occurred

```
2023/08/25 03:08:23 [warn] 49#49: *614877 [lua] plugin.lua:901: run_plugin(): limit-count exits with http status code 503, client: 192.168.88.66, server: _, request: "GET /fuwu/1k.txt?ces=1111 HTTP/1.1", host: "yangcong.com.cn:9080"
```

step 5:
restart the apisix, then it can work normally

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@bin-53 You can reload after deleting the plugin with 
`curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT`

**Comment by bin-53** [comment]
> @bin-53 You can reload after deleting the plugin with `curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT`

This is a bug. Do you have to reload manually? Doesn't apisix have any mechanism to deal with it I think it's a caching problem on the server side

**Comment by Revolyssup** [comment]
@bin-53 If you make any changes to plugin, you need to reload

**Comment by Revolyssup** [comment]
@bin-53 Just to confirm, when you said "delete" the plugin, you meant you removed it from that route, right?

**Comment by bin-53** [comment]
> @bin-53 Just to confirm, when you said "delete" the plugin, you meant you removed it from that route, right?

yes

**Comment by jiangfucheng** [comment]
Did you use `Dashboard` or `Admin API` to set/delete the route?

**Comment by bin-53** [comment]
> `Dashboard`

Dashboard

**Comment by Revolyssup** [comment]
> plugin limit-count

Yes I mistakenly said to reload. It shouldn't require a reload.

**Comment by shreemaan-abhishek** [comment]
It seems there is a problem on your setup like other routes being evaluated for the same uri or global plugins being evaluated. If this bug really existed, more users would have reported. I will close this issue for now.
