### ISSUE TITLE
help request: limt-count plugin with custom key to base the request limiting on

### ISSUE THREAD

**Issue by UPADHYA28** [apache/apisix#10087]
### Description

Hi,

I am trying to explore the capability of `limit-count` plugin. I was to enable the limit-count using the my own key rather than using default key as `remote_addr`

So i am trying something like this. 
![image](https://github.com/apache/apisix/assets/5251377/93a46cbf-d68c-450f-a9cd-ec86cacd7964)

And after configuring it i am trying something like this.

`while true; do curl http://myGWAddress:myNodePort/test -H 'mykey:helloWorld' -I; sleep 0.75s ; done`

But this doesn't seems to be working as expected. because if i use different key for another similar request when the limit exceeded for `helloWorld` key, the request is giving 503. 

Can anyone please tell me whether i have understood wrongly and what i am trying to achieve is it not possible?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Just to clarify your use case, you want to base the rate limiting on `mykey` Header? @UPADHYA28 
The key here by default corresponds to an nginx variable. Try to set the key `$http_mykey`.

**Comment by Revolyssup** [comment]
https://github.com/apache/apisix/issues/9830#issuecomment-1633935640

**Comment by UPADHYA28** [comment]
@Revolyssup Thank you for commenting. Yes i was to limit the count based on the my own keys instead of remote_addr. 
Ex: If i have configured my limit-count for 5 in 60 sec window.
Then request with `mykey:one` should able to reach the request and another equest coming in the same time with `mykey:two` should also be able to access my api for 5 min.. Hope i am able to put my thoughts correctly here!

**Comment by UPADHYA28** [comment]
@Revolyssup Whatever you suggested did not work...
![image](https://github.com/apache/apisix/assets/5251377/07c463ac-3aed-48db-9791-9735a74ddd21)

**Comment by UPADHYA28** [comment]
@Revolyssup Thank you for your help. I was able to fix as per your suggestion and working as expected.
