### ISSUE TITLE
help request: How do I configure elasticsearch-logger to support response.headers and request.headers

### ISSUE THREAD

**Issue by ihse1988** [apache/apisix#10089]
### Description
hi,
my elasticsearch-logger plugin has been added to the route while i want to add response.headers and request.headers to the log.
like this:
`curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/elasticsearch-logger \
-H 'X-API-KEY: xx' -X PUT -d '
{
    "log_format": {
       "@timestamp": "$time_iso8601",     
        "uri": "$uri",   
        "request":"$request",
        "request_method":"$request_method",
        "request_length":"$request_length",
        "request_time":"$request_time",
         "request_headers":"$request_headers",
        "response_headers":"$response_headers"
    }
}'`
but there's no request_headers in my log
when i delete it like this:
`curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/elasticsearch-logger \
-H 'X-API-KEY: xx' -X DELETE`
response.headers and request.headers in log,but i want custom field
what should I do

thanks a lot

### Environment

- APISIX version (run `apisix version`):
3.3.0

- Operating system (run `uname -a`):
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.21.4.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1s  1 Nov 2022

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
{"version":"3.3.0","boot_time":1693032074,"etcd_version":"3.5.0","id":"a426402f-691e-4b35-8b91-aa311a2744e2","hostname":"localhost.localdomain"}

- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ihse1988** [comment]
@Revolyssup All the headers，

**Comment by Revolyssup** [comment]
@ihse1988 These are nginx variables, so either you can -
1. use $http_NAME_OF_THE_HEADER to extract a specific header
2. Use serverless plugin and [register](https://github.com/apache/apisix/blob/704645f6114ce6f2a4fe79857a8049e693f3878c/apisix/core/ctx.lua#L341) custom variables  extracting requests and response headers which correspond to all headers.

**Comment by ihse1988** [comment]
@Revolyssup Thanks,i try it!
