### ISSUE TITLE
help request: Issue with APISIX Installation on RHEL 8.8 using RPM

### ISSUE THREAD

**Issue by deekayzain** [apache/apisix#10092]
### Description

We are facing issue with new installation of APISIX on RHEL 8.8 server using RPM. Kindly guide us with updated installation steps

[root@VLAPISX201 ~]# yum install apisix-2.13.1
Updating Subscription Management repositories.
Last metadata expiration check: 16:26:06 ago on Thu 24 Aug 2023 06:51:32 PM IST.
Error:
 Problem: package apisix-2.13.1-0.el8.x86_64 requires apisix-base >= 1.19.9.1.4, but none of the providers can be installed
  - package apisix-base-1.19.9.1.4-0.el7.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.19.9.1.6-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.0-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.1-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.2-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.3-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.4-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.5-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.6-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.7-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.8-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - package apisix-base-1.21.4.1.9-0.el8.x86_64 conflicts with openresty provided by openresty-1.15.8.2-2.el8.x86_64
  - problem with installed package openresty-1.21.4.2-1.el8.x86_64
  - ------------------------------------------------------

  - package apisix-base-1.21.4.1.9-0.el8.x86_64 conflicts with openresty provided by openresty-1.21.4.2-1.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages) 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by deekayzain** [comment]
Kindly help us in proper versioning APISIX with OpenResty with etcd and LuaRocks that is compatible with rhel 8.8 server.

Your help is greatly appreciated.

**Comment by Sn0rt** [comment]
Can you try the latest version?
2.13.1 It takes time to confirm the compatibility of redhat 8.8.

**Comment by deekayzain** [comment]
for latest we have run this command yum install apisix or we need to specify version as well. kindly confirm.

**Comment by deekayzain** [comment]
[root@VLAPISX201 ~]# yum install apisix-3.4.1
Updating Subscription Management repositories.

This system is registered with an entitlement server, but is not receiving updat                                                                             es. You can use subscription-manager to assign subscriptions.


*** WARNING ***
The subscription for following product(s) has expired:
  - Oracle Java (for RHEL Server)
  - Red Hat Ansible Engine
  - Red Hat Beta
  - Red Hat CodeReady Linux Builder for x86_64
  - Red Hat Developer Tools (for RHEL Server)
  - Red Hat Developer Tools Beta (for RHEL Server)
  - Red Hat Developer Toolset (for RHEL Server)
  - Red Hat Enterprise Linux Atomic Host
  - Red Hat Enterprise Linux Atomic Host Beta
  - Red Hat Enterprise Linux Server
  - Red Hat Enterprise Linux for x86_64
  - Red Hat Software Collections (for RHEL Server)
  - Red Hat Software Collections Beta (for RHEL Server)
  - dotNET on RHEL (for RHEL Server)
You no longer have access to the repositories that provide these products.  It i                                                                             s important that you apply an active subscription in order to resume access to s                                                                             ecurity and other critical updates. If you don't have other active subscriptions                                                                             , you can renew the expired subscription.
Last metadata expiration check: 1 day, 19:35:11 ago on Mon 28 Aug 2023 02:07:39                                                                              PM IST.
Package apisix-3.4.1-0.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@VLAPISX201 ~]# timed out waiting for input: auto-logout
[apachadmin@VLAPISX201 ~]$ timed out waiting for input: auto-logout
[sidbiadm_dharmendrakumar@VLAPISX201 ~]$ sudo su - apachadmin
Last login: Wed Aug 30 09:41:09 IST 2023 on pts/1
[apachadmin@VLAPISX201 ~]$ sudo su -
Last login: Wed Aug 30 09:41:15 IST 2023 on pts/2
[root@VLAPISX201 ~]# apisix init
ERROR: Please check the version of OpenResty and Lua, OpenResty 1.19+ + LuaJIT is required for Apache APISIX.
[root@VLAPISX201 ~]#

**Comment by Sn0rt** [comment]
> * problem with installed package openresty-1.21.4.2-1.el8.x86_64

It is difficult for me to make an accurate judgment based on the above logs. I guess it may be caused by APISIX-base not being installed correctly.
Can you email me?
I can make an appointment to help you try to solve the problem by sharing the desktop.

**Comment by deekayzain** [comment]
My email id is deekayzain@gmail.com  or share your email id to write you by email. Thanks

**Comment by yuluo-yx** [comment]
> My email id is [deekayzain@gmail.com](mailto:deekayzain@gmail.com) or share your email id to write you by email. Thanks

His email: [wangguohao.2009@gmail.com](mailto:wangguohao.2009@gmail.com)

**Comment by deekayzain** [comment]
Now I am able install apisix on RHEL but how to install and run apisix dashboard on RHEL 8.8? Please suggest something on this. Thanks a lot for your help.

**Comment by Sn0rt** [comment]
actually. the dashboard not need install on rhel. you can install the dashboard on other machine and connect to APISIX.

btw. the opensource apisix dashboard is out of maintain. we recommand use admin API to manage the apisix instance.

**Comment by deekayzain** [comment]
Any guidance/docs to use admin API to manage the apisix instance.

Any help/suggest on this. Thanks a lot.

**Comment by Sn0rt** [comment]
![image](https://github.com/apache/apisix/assets/2706161/27868739-069c-4566-94fd-3d3e0a061118)

for example https://apisix.apache.org/docs/apisix/plugins/batch-requests/

**Comment by deekayzain** [comment]
@Sn0rt 
[root@VLAPISX201 conf]# apisix init_etcd
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
all etcd nodes are unavailable

Please help. Thanks

**Comment by deekayzain** [comment]
While hitting below link from browser or postman getting 403 Forbidden exception.

http://172.30.1.110:9180/apisix/admin/services?api_key=edd1c9f034335f136f87ad84b625c8f1

Kindly suggest. Thanks a lot.

**Comment by Revolyssup** [comment]
@deekayzain You have to pass the API key in header `X-API-Key` and not as a query parameter.

**Comment by gish531985** [comment]
> Now I am able install apisix on RHEL but how to install and run apisix dashboard on RHEL 8.8? Please suggest something on this. Thanks a lot for your help.

How was the issue resolved? and what steps were followed to install apisix over RHEL. Please share the details
