### ISSUE TITLE
bug: dns resolution did not resume immediately after the dns server resume

### ISSUE THREAD

**Issue by wklken** [apache/apisix#10093]
### Current Behavior

In our production, when the dns server reload frequently.
The requests will be all fail, while the dns resolution not ok `failed to parse domain: test.com, error: failed to query the DNS server: dns client error: 101 empty record received`;

But when the dns server is stable, the dns resolution of apisix did not resume immediately, the requests got error `[lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node` for hours, until we do `apisix reload`, the dns turns ok.

And from the log, one apisix instance with 4 processes, 3 processes got the dns failed, 1 processes got no error all the requests are ok.

---

apisix/core/dns/client.lua

```lua
function _M.resolve(self, domain, selector)
    local client = self.client

    local answers, err = client.resolve(domain)
    if not answers then
        return nil, "failed to query the DNS server: " .. err
    end
```

how the `client.resolve` detect the dns server is ok? 

### Expected Behavior

dns resolution resume immediately

### Error Logs

when the dns server is reloading

```
[lua] upstream.lua:79: parse_domain_for_nodes(): dns resolver domain: test.com error: failed to query the DNS server: dns client error: 101 empty record received
[lua] resolver.lua:80: parse_domain(): failed to parse domain: test.com, error: failed to query the DNS server: dns client error: 101 empty record received
```

when the dns server is stable (no `dns` error logs, **why?**)

```
[lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node
```

so, it means when the dns server is stable, the `parse_domain` success, no error logs, but the `handle_upstream` still get `no valid upstream node`

and after `apisix reload`, no error logs

1. dns client parse success, but return empty new_nodes? (cache?)
2. dns client parse success and return new_nodes, but `set_upstream` fail? 

### Steps to Reproduce

For now, I cannot reproduce it, but it has occurred three times in our production.
Any clues or advice for making dns server reload frequently?

### Environment

- APISIX version (run `apisix version`): 3.2.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wklken** [comment]
two upstream:
1. route.upstream
2. route.service_id -> service.upstream

the first upstream did not resume immediately

https://github.com/apache/apisix/blob/77704832ec91117f5ca7171811ae5f0d3f1494fe/apisix/init.lua#L422-L445

and it seems the `parse_domain_in_route` did not know the dns server is resumed

https://github.com/apache/apisix/blob/77704832ec91117f5ca7171811ae5f0d3f1494fe/apisix/init.lua#L210-L239

**Comment by wklken** [comment]
I have reproduce @jiangfucheng 

just mock dns fail in lua

## apisix config:

1. start apisix with 4 processes
2. change then nginx error log level to `info`

## register route:

1. add a route `/get` with one upstream, one node like `httpbin.org`; the parsed data in log is `"nodes":[{"host":"54.175.87.239","priority":1,"domain":"httpbin.org","port":80,"weight":100,"upstream_host":"httpbin.org"}]`
2. change `apisix/utils/upstream.lua` to mock dns random error, note the `1693542089` is a `now() + 60`

```lua
local function parse_domain_for_nodes(nodes) 
    local new_nodes = core.table.new(#nodes, 0)
    for _, node in ipairs(nodes) do
        local host = node.host
        if not ipmatcher.parse_ipv4(host) and
                not ipmatcher.parse_ipv6(host) then

            if host == "httpbin.org" and ngx_now() <= 1693542089 then
                if random(1,10) % 2 == 0 then
                        core.log.error("101 empty records")
                        return new_nodes
                end
                -- return nil, "failed to query the DNS server: timeout11"
            end
            local ip, err = core.resolver.parse_domain(host)
            if ip then
                local new_node = core.table.clone(node)
                new_node.host = ip
                new_node.domain = host
                core.table.insert(new_nodes, new_node)
            end
```

3. `apisix reload`

## do requests

1. `wrk  -c2 -t2 -d60s http://{}/get`
2. and after the wrk finished, do `curl http://{}/get` for about 10 times, got 200 and 503

## the log

when 503, there got no `dns` logs before `no valid upstream node`


```
2023/09/01 04:24:20 [info] 140701#140701: *15533385 [lua] radixtree_uri_with_parameter.lua:53: match(): route match mode: radixtree_uri_with_parameter
2023/09/01 04:24:20 [info] 140701#140701: *15533385 [lua] init.lua:572: http_access_phase(): matched route: {"key":"/bk-gateway-apisix/routes/test.prod.2423","modifiedIndex":532500,"clean_handlers":"table: 0x7f7d645c64c8","has_domain":true,"value":{"create_time":1693309224,"methods":["GET"],"service_id":"test.prod.stage-12","update_time":1693539224,"timeout":{"send":150,"read":150,"connect":150},"labels":{"gateway.bk.tencent.com/gateway":"test","gateway.bk.tencent.com/stage":"prod"},"uris":["/api/test/prod/dns","/api/test/prod/dns/"],"status":1,"priority":0,"name":"test-prod-dns","id":"test.prod.2423","plugins":{"bk-proxy-rewrite":{"match_subpath":false,"subpath_param_name":":ext","method":"GET","use_real_request_uri_unsafe":false,"uri":"/get"},"bk-resource-context":{"bk_resource_auth":{"resource_perm_required":false,"skip_user_verification":false,"verified_app_required":false,"verified_user_required":false},"bk_resource_id":2423,"bk_resource_name":"dns","bk_resource_auth_obj":{"resource_perm_required":false,"skip_user_verification":false,"verified_app_required":false,"verified_user_required":false}}},"upstream":{"nodes":{},"hash_on":"vars","scheme":"http","parent":{"key":"/bk-gateway-apisix/routes/test.prod.2423","modifiedIndex":532500,"clean_handlers":{},"has_domain":true,"value":"table: 0x7f7d9706c708","update_count":0,"orig_modifiedIndex":532500,"createdIndex":532332},"type":"roundrobin","pass_host":"node","timeout":{"send":150,"read":150,"connect":150}}},"update_count":0,"orig_modifiedIndex":532500,"createdIndex":532332
2023/09/01 04:24:20 [info] 140701#140701: *15533385 [lua] plugin.lua:630: merge_service_route():   route conf: {"key":"/bk-gateway-apisix/routes/test.prod.2423","modifiedIndex":532500,"clean_handlers":"table: 0x7f7d645c64c8","has_domain":true,"value":{"create_time":1693309224,"methods":["GET"],"service_id":"test.prod.stage-12","update_time":1693539224,"timeout":{"send":150,"read":150,"connect":150},"labels":{"gateway.bk.tencent.com/gateway":"test","gateway.bk.tencent.com/stage":"prod"},"uris":["/api/test/prod/dns","/api/test/prod/dns/"],"status":1,"priority":0,"name":"test-prod-dns","id":"test.prod.2423","plugins":{"bk-proxy-rewrite":{"match_subpath":false,"subpath_param_name":":ext","method":"GET","use_real_request_uri_unsafe":false,"uri":"/get"},"bk-resource-context":{"bk_resource_auth":{"resource_perm_required":false,"skip_user_verification":false,"verified_app_required":false,"verified_user_required":false},"bk_resource_id":2423,"bk_resource_name":"dns","bk_resource_auth_obj":{"resource_perm_required":false,"skip_user_verification":false,"verified_app_required":false,"verified_user_required":false}}},"upstream":{"nodes":{},"hash_on":"vars","scheme":"http","parent":{"key":"/bk-gateway-apisix/routes/test.prod.2423","modifiedIndex":532500,"clean_handlers":{},"has_domain":true,"value":"table: 0x7f7d9706c708","update_count":0,"orig_modifiedIndex":532500,"createdIndex":532332},"type":"roundrobin","pass_host":"node","timeout":{"send":150,"read":150,"connect":150}}},"update_count":0,"orig_modifiedIndex":532500,"createdIndex":532332}
2023/09/01 04:24:21 [error] 140701#140701: *15534047 [lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node
```

**Comment by wklken** [comment]
`route.value.upstream.nodes` is empty, so the `new_nodes` is empty(no dns resolve)

<img width="862" alt="image" src="https://github.com/apache/apisix/assets/2002216/b883927c-f650-4e1d-847b-3019083c6293">

-----

so the `route.value.upsteram.nodes` may be set empty somewhere

**Comment by wklken** [comment]
it's the plugin `proxy-rewrite` cause the error. if remove the plugin, no error!

```
    "plugins": {
      "proxy-rewrite": {
        "method": "GET",
        "uri": "/get",
        "use_real_request_uri_unsafe": false
      }
    }
```

I will use apisix docker-compose to reproduce the problem.

**Comment by jiangfucheng** [comment]
@wklken  Hi, could you paste the APISIX configurations? It's hard to reproduce this bug if no detailed configurations.

**Comment by wklken** [comment]
@jiangfucheng I still trying to reproduce it in apisix docker-compose, not success yet. I will update the issue when success. (it only can be reproduced on our image build from `apache/apisix:3.2.1-centos`)

**Comment by wklken** [comment]
@jiangfucheng Finally, It been reproduced on the apisix docker-compose. It take a lot of time , add I add some scripts to help.

here is the steps, can you please help to investigate this? (this is the problem which stuck our version for production)

------

## Reproduce steps:

### 1. use the docker-compose

1. `git clone https://github.com/apache/apisix-docker.git`
2. `vim  apisix_conf/master/config.yaml`, change the `router` and `nginx_config.processes`
```yaml
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  router:
    http: radixtree_uri_with_parameter

nginx_config:
  worker_processes: 4
```
3. `vim docker-compose-master.yaml` change the `image` to 3.2.1-centos
```yaml
services:
  apisix:
    image: "apache/apisix:3.2.1-centos"
```
4. `docker-compose -p docker-apisix -f docker-compose-master.yaml up` start the apisix and etcd

### 2. enter the container, do some change to mock the dns failure

> all in the container

1. `docker exec -it dockerapisix_apisix_1 /bin/bash`
2. check the `conf/config.yaml` is right, 4 processes, and the `apisix version` is 3.2.1
3. `vi apisix/utils/upstream.lua`, add code to mock the dns failure, 50% will `101 empty records`

```lua
-- to line 22

local random = math.random

-- add before core.resolver.parse_domain(host)

local function parse_domain_for_nodes(nodes)
    local new_nodes = core.table.new(#nodes, 0)
    for _, node in ipairs(nodes) do
        local host = node.host
        if not ipmatcher.parse_ipv4(host) and
                not ipmatcher.parse_ipv6(host) then
            if host == "httpbin.org" and ngx_now() <= 1695089345 then
                if random(1,10) % 2 == 0 then
                        core.log.error("101 empty records")
                        return new_nodes
                end
            end
            local ip, err = core.resolver.parse_domain(host)
```
4. add a script `create.sh` to register the route and service, **check the API_KEY is right**
```bash
#!/bin/bash

API_KEY="edd1c9f034335f136f87ad84b625c8f1"
ROUTE_ID="dns_route"
SERVVICE_ID="dns_service"

curl http://127.0.0.1:9180/apisix/admin/services/${SERVVICE_ID} -H "X-API-KEY: ${API_KEY}" -X PUT -d '
{
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.org",
        "port": 80,
        "weight": 100,
        "priority": 1
      }
    ],
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "node"
  }
}'

curl http://127.0.0.1:9180/apisix/admin/routes/${ROUTE_ID} -H "X-API-KEY: ${API_KEY}" -X PUT -d '
{
  "uri": "/api/test/prod/dns22",
  "methods": [
    "GET"
  ],
  "plugins": {
    "proxy-rewrite": {
      "method": "GET",
      "uri": "/get"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.org",
        "port": 80,
        "weight": 100,
        "priority": 1
      }
    ],
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "node"
  },
  "service_id": "dns_service",
  "status": 1
}'
```
5. add script `update_lua.sh` to change the timestamp fast
```bash
#!/bin/bash

now=$(date "+%s")
echo "now is: ${now}"

A=$(date -d "+30 seconds" "+%s")
echo "will change the condition to <= ${A}"
sed -i -r "s/<= ([0-9]+) then/<= ${A} then/g"  apisix/utils/upstream.lua
echo $?
echo "change done"

apisix reload
```
6. do the register
```bash
bash -x create.sh
```
7. check the url is ok **not in the container**
```
curl -vv http://0.0.0.0:9080/api/test/prod/dns22
```

## 3. not in the container, add check script

> not in the container

1. install wrk
2. add script `start_and_check.sh` for benchmark then check 503
```bash
#!/bin/bash

date

url="http://0.0.0.0:9080/api/test/prod/dns22"

echo "start bench wrk"
wrk -c2 -t2 -d35s ${url}

date

echo "sleep 5 s"
sleep 5

echo "check the status code 10 times"

for ((i=1; i<=10; i++))
do
    status_code=$(curl --write-out %{http_code} --silent --output /dev/null $url)
    echo "status=$status_code"
    if [ "${status_code}" -eq "503" ]
    then
        echo "503 show"
        exit
    fi
done
```

## 4. reproduce

> open two window to run step 1/2 at the same time

1. in container, run 
```
$ ./update_lua.sh 
now is: 1695089267
will change the condition to <= 1695089297
0
change done
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua reload

WARNING: using fixed Admin API token has security risk.
Please modify "admin_key" in conf/config.yaml .


2023/09/19 02:07:47 [notice] 157#157: signal process started
```
2. out the container, run
```
$ bash start_and_check.sh

Tue Sep 19 10:08:36 CST 2023
start bench wrk
Running 35s test @ http://0.0.0.0:9080/api/test/prod/dns22
  2 threads and 2 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    15.22ms   80.61ms 823.04ms   95.99%
    Req/Sec     6.91k   807.96     7.77k    95.97%
  461582 requests in 35.00s, 202.93MB read
  Non-2xx or 3xx responses: 461575
Requests/sec:  13187.64
Transfer/sec:      5.80MB
Tue Sep 19 10:09:11 CST 2023
sleep 5 s
check the status code 10 times
status=503
503 show
```
3. if `503 show`, means it been reproduced! you can `curl -vv http://0.0.0.0:9080/api/test/prod/dns22` for few times to check
```
curl -vv http://0.0.0.0:9080/api/test/prod/dns22
* About to connect() to 0.0.0.0 port 9080 (#0)
*   Trying 0.0.0.0...
* Connected to 0.0.0.0 (0.0.0.0) port 9080 (#0)
> GET /api/test/prod/dns22 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 0.0.0.0:9080
> Accept: */*
> 
< HTTP/1.1 503 Service Temporarily Unavailable
< Date: Tue, 19 Sep 2023 02:21:58 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 269
< Connection: keep-alive
< Server: APISIX/3.2.1
< 
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>
* Connection #0 to host 0.0.0.0 left intact
```
5. if all `200`, do step 1/2 again(it took 50 seconds each time, and it not 100% show 503, but if you try about 10 times, high possibility showed).

**Comment by wklken** [comment]
More clues for detecting:
1. should be `route.upstream`, and the `route` should related to a `service` with `upstream` will cause the problem
    - route without upstream - ok
    - route with upstream, without service_id - ok
2. 4 workers, only part of them will return 503
3. if `apisix reload`, will all 200
4. the `503` only 1 log `2023/09/19 02:34:52 [error] 854#854: *112694 [lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node, client: 172.31.0.1, server: _, request: "GET /api/test/prod/dns22 HTTP/1.1", host: "0.0.0.0:9080"`; it did not call the `parse_domain`, maybe some cache?

**Comment by wklken** [comment]
I add some log,  the image is more clear

<img width="1867" alt="image" src="https://github.com/apache/apisix/assets/2002216/2b55197b-9b16-4f67-b105-9fdf59784e88">

**Comment by Revolyssup** [comment]
@jiangfucheng , in the log you can see that @wklken has added I think some error logs from his side `101 empty record` inside `parse_domain_for_nodes` function. 

@wklken Can you show the snippet of `parse_domain_for_nodes` function where this log is?

**Comment by Revolyssup** [comment]
@jiangfucheng `api_ctx.matched_route` is per request so even if it is set wrong, the subsequent request will set it again.

**Comment by Revolyssup** [comment]
@wklken Just to confirm, it only happens when the route has service id, right?

**Comment by wklken** [comment]
> @wklken Just to confirm, it only happens when the route has service id, right?

Yes, route has upstream and has service_id (the service have upstream too)

**Comment by jiangfucheng** [comment]
> @jiangfucheng `api_ctx.matched_route` is per request so even if it is set wrong, the subsequent request will set it again. In the next request, you can see that api_ctx.matched_route has empty nodes in upstream after it is populated by match() function. The whole issue boils down to, why the matched_route log has no nodes? This is calculated for each request from the etcd. I haven't been able to find the exact flow that can explain where exactly did this nodes={} from previous upstream resulted in api_ctx.matched_route's nodes when api_ctx is freshly calculated per request. And where exactly is the caching happening at that point while matching route.
> 
> The only caching culprit I see currently is this
> 
> https://github.com/apache/apisix/blob/57a7dcdac63a0bda55ddd41fc56a10c6144bfd51/apisix/http/router/radixtree_uri_with_parameter.lua#L38
> 
> But modification in _M.user_routes is only done directly by etcd.



You are right, it's my mistake, `api_ctx` will be created when a new request comes, it does not reuse it.

**Comment by jiangfucheng** [comment]
> @wklken I think parse_domain_for_nodes is called in subsequent request but there are no nodes to iterate over, so you don't get the log.

Agree with this opinion.

**Comment by Revolyssup** [comment]
@wklken Just one last request, can you add a log to log the route in the for loop here https://github.com/apache/apisix/blob/a98f1ca7a4b368a5270c5cae2a2a526f21ba409a/apisix/http/route.lua#L40 ? and show the output. I am trying to figure out at what point exactly did the route change.

**Comment by Revolyssup** [comment]
@wklken In the first request, did you get a log similar to `route items: `???

**Comment by wklken** [comment]
> @wklken In the first request, did you get a log similar to `route items: ` or `insert uri route: `???

My log level is `info` and there no `route items:` or `insert uri route:` where the first `empty nodes` present.

**Comment by Revolyssup** [comment]
@wklken Before empty nodes came, did you find this? What was the last time this log came?

**Comment by wklken** [comment]
```
2023/09/19 06:46:16 [info] 51339#51339: *5157502 [lua] route.lua:73: create_radixtree_uri_router(): insert uri route: {"id":"dns_route","service_id":"dns_service","create_time":1695037859,"uri":"/api/test/prod/dns22","status":1,"methods":["GET"],"update_time":1695037859,"upstream":{"type":"roundrobin","pass_host":"node","scheme":"http","nodes":[{"priority":1,"port":80,"host":"httpbin.org","weight":100}],"parent":{"has_domain":true,"createdIndex":543015,"value":{"id":"dns_route","service_id":"dns_service","create_time":1695037859,"uri":"/api/test/prod/dns22","status":1,"methods":"table: 0x7f66620fc778","update_time":1695037859,"upstream":"table: 0x7f6661b40ed0","priority":0,"plugins":"table: 0x7f666236e638"},"modifiedIndex":543015,"orig_modifiedIndex":543015,"key":"/bk-gateway-apisix/routes/dns_route","update_count":0,"clean_handlers":{}},"hash_on":"vars"},"priority":0,"plugins":{"proxy-rewrite":{"method":"GET","use_real_request_uri_unsafe":false,"uri":"/get"}}}\

..... a lot of other insert uri route

2023/09/19 06:46:17  empty nodes  
```

@Revolyssup  1 second before the empty nodes

**Comment by Revolyssup** [comment]
cc: @kingluo

**Comment by wklken** [comment]
https://github.com/apache/apisix/issues/10093#issuecomment-1725524437

> For the above two issues, I think we just fix the return value in `parse_domain_for_nodes` function enough.

@jiangfucheng we need your help to confirm if that fix would be right.

According to your answer above, can we just add a check before `return new_nodes` inf `local function parse_domain_for_nodes(nodes)`? 

```
local function parse_domain_for_nodes(nodes)
    .....

    if #new_nodes == 0 then
      return nil, "no valid nodes after dns resolver domain: " .. host
    end

    return new_nodes

```

**Comment by Revolyssup** [comment]
Closed by https://github.com/TencentBlueKing/blueking-apigateway-apisix/pull/52

**Comment by wklken** [comment]
@Revolyssup the issue should not be closed before the official repo fix the bug? and we still don't know the reason.

our own repo need to fix the production so we patched it

**Comment by Revolyssup** [comment]
@wklken Yep I understand. The patch still doesn't fix the original issue, its kind of a hack

**Comment by sheharyaar** [comment]
Hi @wklken , can you please recheck if this is fixed or not. I think this may have been related to #10722 .

**Comment by wklken** [comment]
@sheharyaar Unfortunately, the bug is not fixed by #10722 

Follow the reproduce steps here: https://github.com/apache/apisix/issues/10093#issuecomment-1724748805

1. reproduce, 503 show
2. patch the changes, apisix reload
3. reproduce, 503 show

**Comment by sheharyaar** [comment]
Ok, I will have a look

**Comment by Revolyssup** [comment]
@wklken I have retried the reproduction steps several times but still cannot reproduce the issue. I do not get 503 after the normal operation is resumed.

**Comment by Revolyssup** [comment]
@wklken I have followed your exact reproduction steps multiple times but I never got the error.

**Comment by wklken** [comment]
@Revolyssup did you follow those steps here? https://github.com/apache/apisix/issues/10093#issuecomment-1724748805

and the apisix version should be 3.2.1;

----

we just patch it https://github.com/TencentBlueKing/blueking-apigateway-apisix/blob/master/src/build/patches/002_upstream_parse_domain_for_nodes.patch and it's on our production for about 10 months, and it works.

**Comment by Revolyssup** [comment]
@wklken Just want to confirm the behaviour after this patch.
So before the patch when empty nodes were returned, you were intermittently getting 503 error with the requests.
But now when you errror out early, you still get 500 error for "no valid ip found". But the subsequent requests when the dns comes back up, no error is found. right?

Basically you have covered the case that nodes will never be set as empty.

**Comment by wklken** [comment]
https://github.com/apache/apisix/issues/10093#issue-1869257753

```
The requests will be all fail, while the dns resolution not ok failed to parse domain: test.com, error: failed to query the DNS server: dns client error: 101 empty record received;

But when the dns server is stable, the dns resolution of apisix did not resume immediately, the requests got error [lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node for hours, until we do apisix reload, the dns turns ok.
```

It’s always showing a 503 error even if the DNS is okay.
I think there may be some cache that makes APISIX unaware of the DNS resume.

**Comment by Revolyssup** [comment]
> [#10093 (comment)](https://github.com/apache/apisix/issues/10093#issue-1869257753)
> 
> ```
> The requests will be all fail, while the dns resolution not ok failed to parse domain: test.com, error: failed to query the DNS server: dns client error: 101 empty record received;
> 
> But when the dns server is stable, the dns resolution of apisix did not resume immediately, the requests got error [lua] init.lua:486: handle_upstream(): failed to set upstream: no valid upstream node for hours, until we do apisix reload, the dns turns ok.
> ```
> 
> It’s always showing a 503 error even if the DNS is okay. I think there may be some cache that makes APISIX unaware of the DNS resume.

@wklken I meant to ask the behavior in your patch. After your patch, you do not get the 503 after dns server resumes. Right?

**Comment by Revolyssup** [comment]
I haven't been able to reproduce but by the error and how your patch fixes the error and the logs above that you showed, here is the conclusion so far:

Somehow the nodes in the original saved configuration are set to empty. Since this goes away after a reload means the etcd still has correct value.  Since I cant reproduce, I am going through the code to find the root cause currently.

**Comment by Revolyssup** [comment]
cache issue is unlikely because api_ctx is created newly for each new request. So for next request, new api_ctx will be created and the matched route should contain the correct routes configuration with the nodes field.

**Comment by Revolyssup** [comment]
![Screenshot from 2024-07-03 16-59-17](https://github.com/apache/apisix/assets/43276904/1f837916-b325-46c5-a15d-df9499f2cb3e)
Tried multiple times, still getting no 503s

**Comment by Revolyssup** [comment]
@wklken Also one clarification in the reproduction steps.

You ask to run  wrk just after running update_lua,sh. If you do that then 503 are expected because for the first 30 seconds the custom added code will sometimes return 503, the code that is added for reproduction. But after 30 seconds there can be no issue as that code doesn't run. 
![Screenshot from 2024-07-03 17-03-37](https://github.com/apache/apisix/assets/43276904/cdc2c9a8-03c6-4bae-96e5-d82dbd3be01c)

**Comment by Revolyssup** [comment]
Since after trying multiple times, this cannot be reproduced. I am closing the issue. If anyone else is able to reproduce this bug again then please reopen with the exact steps you folllowed.
