### ISSUE TITLE
help request: The cas-auth plugin cannot enabled

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10105]
### Description

Symptom When cas-auth is enabled in the configuration file, an error message is displayed indicating that apisix is restarted.
![image](https://github.com/apache/apisix/assets/16013545/de4270d7-3f63-48c9-86bd-bd9bbcf62b16)

Here's what's in the configuration file:
![image](https://github.com/apache/apisix/assets/16013545/2523b905-ca0f-4dde-9d9f-685fbcf420f7)

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@lxz999 Can you share the nginx.conf file as well?

**Comment by lxz999** [comment]
I only cut the paragraph where the error was reported
![image](https://github.com/apache/apisix/assets/16013545/49820ddc-9211-4ba4-abbc-e66743ba58f2)

**Comment by Revolyssup** [comment]
@lxz999 I think you are missing `cas-auth` field in config-default.yaml inside `nginx_config.http.lua_shared_dict`. Look at last line
![Screenshot from 2023-08-29 17-14-28](https://github.com/apache/apisix/assets/43276904/c6922acd-d7ba-4ad7-9f31-a019ce863db9)

**Comment by lxz999** [comment]
According to your method, it's all right. Thank you
