### ISSUE TITLE
feat: support gzip encoded logs in logger

### ISSUE THREAD

**Issue by qiaofazhan** [apache/apisix#10106]
### Current Behavior

Loggers to support this:
1. Kafka logger
2. Rocketmq logger
3. HTTP logger

### Expected Behavior

kafka-logger correctly parses the response body according to the request header Accept-Encoding

### Steps to Reproduce

Open the plug-in kafka-logger in route
Call the route interface
View the kafka-logger uri server console and view the log message

### Environment

- APISIX version (run `2.15`):
- Operating system (CentOS Linux):

**Comment by qiaofazhan** [comment]
I found that http-logger and rocketmq-logger have the same issue by searching for ”garbled codes“ in the community issues.

**Comment by Revolyssup** [comment]
@qiaofazhan Refer to the discussion here - https://github.com/apache/apisix/issues/9961

**Comment by Revolyssup** [comment]
We dont support compressed responses for structured logging.

**Comment by shreemaan-abhishek** [comment]
same as #9697

**Comment by qiaofazhan** [comment]
您好，邮件已收到，尽快给您回复。
