### ISSUE TITLE
help request: The mqtt-proxy plug-in configuration file cannot be added after the configuration is enabled

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10117]
### Description

Content in the configuration file:
![image](https://github.com/apache/apisix/assets/16013545/5d409fb6-471d-4acb-903f-d4ae49494695)

![image](https://github.com/apache/apisix/assets/16013545/8488357c-889f-4d83-b9a2-49533420a178)
The way I execute the plugin is:
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d ' 
{
    "plugins": {
        "mqtt-proxy": {
            "protocol_name": "MQTT",
            "protocol_level": 4
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": [{
            "host": "127.0.0.1",
            "port": 1980,
            "weight": 1
        }]
    }
}'
I get the following error when adding mqtt-proxy plugin:
{
	"error_msg": "stream mode is disabled, can not add stream routes"
}

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
You can refer to the documentation and try again.  [mqtt-proxy-plugin](https://apisix.apache.org/docs/apisix/plugins/mqtt-proxy/)

**Comment by lxz999** [comment]
It is okay, thank you
