### ISSUE TITLE
how to configure Etcd to mysql?

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#10113]
### Description

Apisix uses etcd as storage by default. Can you change it to mysql to obtain other storage devices? If yes, are there related documents for reference?

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
AFAIK, currently apisix does not support switching to other data sources, and there is no relevant document reference. If you want to switch, you need to adapt it yourself.

https://apisix.apache.org/docs/apisix/FAQ/#why-does-apache-apisix-use-etcd-for-the-configuration-center

**Comment by Gallardot** [comment]
Please take a look [etcd-adapter](https://github.com/api7/etcd-adapter).  
[apisix-ingress-controller](https://github.com/apache/apisix-ingress-controller) also uses this component to replace the real ETCD server. 

Note: This is an experimental feature and may pose risks.

**Comment by FelipoAntonoff** [comment]
Support for traditional banks would be good, as it reduces dependence on etcd. Most projects already use a SQL database such as MariaDB or MySQL and sometimes do not need a cluster of machines. My case would be to use it in a large or dedicated Cloud, I prefer to keep everything in MariaDB. Another approach would be to not depend on any other system, like Krakend does, I think it saves its configuration to disk.
