### ISSUE TITLE
help request: Issue with yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm

### ISSUE THREAD

**Issue by deekayzain** [apache/apisix#10123]
### Description

[root@VLAPISX201 ~]# yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
Updating Subscription Management repositories.

This system is registered with an entitlement server, but is not receiving updates. You can use subscription-manager to assign subscriptions.

Errors during downloading metadata for repository 'release':
  - Curl error (6): Couldn't resolve host name for https://repos.apiseven.com/packages/centos/8/x86_64/repodata/repomd.xml [Could not resolve host: repos.apiseven.com]
Error: Failed to download metadata for repo 'release': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

For the above issue, Your help is greatly appreciated.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
It looks like you've asked a related [question](https://github.com/apache/apisix/issues/10092), are you using RHEL?

**Comment by Revolyssup** [comment]
@deekayzain This may have been a one time issue. Were you able to download it?
