### ISSUE TITLE
help request: What does apisix_latency mean?

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10129]
### Description

What does apisix_latency mean?

I  not understand   apisix_latency  mean?  

<img width="334" alt="企业微信截图_94bd1181-70c7-4920-aa05-173c0cf17ac3" src="https://github.com/apache/apisix/assets/44867235/934e2110-04da-467d-9901-92a3bb28b58d">

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):  3.10.0-1160.90.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):   docker.io/bitnami/etcd:3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant:   apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yuluo-yx** [comment]
I think you can understand that as a request for delay.

**Comment by yuluo-yx** [comment]
I think you can understand that as a request for delay.

**Comment by qyk1995** [comment]
@yuluo-yx    apisix_latency  is  2.098,  latency  is  3.000000, upstream_latency  is  3.  latency  = upstream_latency   + apisix_latency ?What is the relationship between them？

**Comment by kingluo** [comment]
@qyk1995 yes, latency = upstream_latency + apisix_latency.
And in your case, the latency is abnormal.
Where did you find the stats? access.log? Please show your access.log item resulting from your use case.

**Comment by kingluo** [comment]
@qyk1995 
apisix_latency == (request_time - upstream_response_time) == (downstream trafffic latency + nginx latency)

**Comment by qyk1995** [comment]
@yuluo-yx  thank you very much.
