### ISSUE TITLE
help request: Issue with apisix init after installing the Apisix 3.4.1 on RHEL 8.8 server

### ISSUE THREAD

**Issue by deekayzain** [apache/apisix#10139]
### Description

[root@VLAPISX201 local]# apisix init
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init
Warning! Current maximum number of open file descriptors [1024] is not greater than 1024, please increase user limits by execute 'ulimit -n <new user limits>' , otherwise the performance is low.
local DNS is empty

Kindly help us on this.
Help is greatly appreciated. Thanks

### Environment

- APISIX version (run `apisix version`): 3.4.1
- Operating system (run `uname -a`): Linux VLAPISX201 4.18.0-477.15.1.el8_8.x86_64 #1 SMP Fri Jun 2 08:27:19 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): curl: (7) Failed to connect to 127.0.0.1 port 9090: Connection refused
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): bash: luarocks: command not found...
Failed to search for file: Failed to download gpg key for repo 'release': Curl error (6): Couldn't resolve host name for https://repos.apiseven.com/KEYS [Could not resolve host: repos.apiseven.com]

**Comment by Revolyssup** [comment]
@deekayzain Is the file /etc/resolv.conf present on this machine and can you show its output?

**Comment by shreemaan-abhishek** [comment]
@deekayzain, I don't think this is a failure. What happens when you proceed and execute `apisix start`?

**Comment by deekayzain** [comment]
[root@VLAPISX201 conf]# apisix start
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua start
local DNS is empty
[root@VLAPISX201 conf]#

**Comment by shreemaan-abhishek** [comment]
@deekayzain, my bad, this is a failure. And this is probably because your `/etc/resolv.conf` is empty.

As revolyssup mentioned earlier, is the file /etc/resolv.conf present on this machine and can you show its output?

**Comment by deekayzain** [comment]
/etc/resolv.conf.  Yes its there and its contents are below:

# Generated by NetworkManager
#nameserver 8.8.8.8

**Comment by Revolyssup** [comment]
@deekayzain The nameserver is commented out. Can you uncomment it?

**Comment by deekayzain** [comment]
Thanks  Revolyssup. its working. but how to enable and use apisix dashboard ?

**Comment by deekayzain** [comment]
While creating route we are getting below error :
[root@VLAPISX201 ~]# curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
> {
>   "id": "getting-started-ip",
>   "uri": "/ip",
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     }
>   }
> }'
HTTP/1.1 401 Unauthorized
Date: Mon, 04 Sep 2023 10:29:46 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/3.4.1
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600

{"error_msg":"failed to check token"}

Kindly help/suggest.

**Comment by Revolyssup** [comment]
@deekayzain Please provide token in the API Key header like `-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

**Comment by deekayzain** [comment]
Can you please provide sample example for using API key header using curl. Thanks

**Comment by Revolyssup** [comment]
> Can you please provide sample example for using API key header using curl. Thanks

https://apisix.apache.org/docs/apisix/terminology/route/#example

**Comment by deekayzain** [comment]
How to access the apisix dashboard?  below are curls we have checked but its not there.

[root@VLAPISX201 conf]# curl -vv http://172.30.1.110:9000/dashboard/
*   Trying 172.30.1.110...
* TCP_NODELAY set
* connect to 172.30.1.110 port 9000 failed: Connection refused
* Failed to connect to 172.30.1.110 port 9000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 172.30.1.110 port 9000: Connection refused
[root@VLAPISX201 conf]# curl -vv http://172.30.1.110:9080/dashboard/
*   Trying 172.30.1.110...
* TCP_NODELAY set
* Connected to 172.30.1.110 (172.30.1.110) port 9080 (#0)
> GET /dashboard/ HTTP/1.1
> Host: 172.30.1.110:9080
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Tue, 05 Sep 2023 04:45:10 GMT
< Content-Type: text/plain; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Server: APISIX/3.4.1
<
{"error_msg":"404 Route Not Found"}
* Connection #0 to host 172.30.1.110 left intact
Any help/suggest something. Thanks.

**Comment by deekayzain** [comment]
@Revolyssup 
[root@VLAPISX201 conf]# apisix init_etcd
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
all etcd nodes are unavailable


Please help/suggestion on this.

**Comment by Revolyssup** [comment]
@deekayzain You need to have etcd running. Looks like you are using the defaut address localhost, so make sure etcd is started on the machine on port 2379.
You can use `etcd &` to start etcd

**Comment by deekayzain** [comment]
@shreemaan-abhishek 

 , request: "GET /apisix/admin/routes?api_key=newsupersecurekey HTTP/1.1", host: "127.0.0.1:9180"
2023/09/08 16:05:49 [warn] 24922#24922: *55140 [lua] init.lua:119: set_ctx_and_check_token(): failed to check token: wrong apikey, client: 127.0.0.1, server: , request: "GET /apisix/admin/routes?api_key=newsupersecurekey HTTP/1.1", host: "127.0.0.1:9180"

**Comment by Revolyssup** [comment]
@deekayzain Make sure to pass the api key in header and not query params.

**Comment by deekayzain** [comment]
> @deekayzain You need to have etcd running. Looks like you are using the defaut address localhost, so make sure etcd is started on the machine on port 2379. You can use `etcd &` to start etcd

@Revolyssup 
Kindly elaborate on the above as we are getting error after reboot of system.

[root@VLAPISX201 conf]# apisix init_etcd
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
all etcd nodes are unavailable

Please help/suggestion on this.

**Comment by Revolyssup** [comment]
@deekayzain You need to have etcd server running  on the specified etcd.host[], which in this case is  `http://127.0.0.1:2379/version`.

**Comment by monkeyDluffy6017** [comment]
considered resolved

**Comment by naina24** [comment]
> > @deekayzain You need to have etcd running. Looks like you are using the defaut address localhost, so make sure etcd is started on the machine on port 2379. You can use `etcd &` to start etcd
> 
> @Revolyssup Kindly elaborate on the above as we are getting error after reboot of system.
> 
> [root@VLAPISX201 conf]# apisix init_etcd /usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init_etcd Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1 Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2 request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused all etcd nodes are unavailable
> 
> Please help/suggestion on this.

I am also facing the same issue...I have etcd running on openshift.
