### ISSUE TITLE
help request: How to locate apisix memory footprint issues

### ISSUE THREAD

**Issue by zjclyz** [apache/apisix#10142]
### Description

Problem: I recently built a gateway with apisix, which is currently in the testing phase without much traffic (QPM is about 100/min), and noticed that the gateway's memory usage is exaggerated, as shown in the picture（Machine specification: 8c 16g）:
<img width="691" alt="image" src="https://github.com/apache/apisix/assets/22068835/3f3998e5-3f7d-4aee-b8f6-c0a35cbecd4f">
<img width="696" alt="image" src="https://github.com/apache/apisix/assets/22068835/7fbc7727-69dd-4be4-ad76-ac47b525d30e">
<img width="745" alt="image" src="https://github.com/apache/apisix/assets/22068835/8116c8a7-f316-4da2-82ac-0a0d9c918489">

Plugins: opentelemetry, gzip,uri-blocker,proxy-rewrite,response-rewrite,log-rotate,real-ip, and a few simple plugins I wrote based on business requirements

Claim: Have you encountered this situation where there is little traffic and the gateway's memory footprint goes up and down? apisix What is a more convenient way to perform memory diagnostics to determine this kind of memory problem?

### Environment

- APISIX version (run `apisix version`): 2.1.8
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): no
- APISIX Dashboard version, if relevant: no
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by Revolyssup** [comment]
cc: @kingluo You may have better insights here.

**Comment by kingluo** [comment]
@zjclyz  try to disable the Prometheus plugin.
And if the issue keeps still, try the master branch.

**Comment by monkeyDluffy6017** [comment]
@zjclyz any progress?

**Comment by zjclyz** [comment]
> @zjclyz any progress?

I didn't find out exactly why, but I rewrote a plugin I wrote and it worked unexpectedly I didn't understand why, does apisix have a simple enough means of locating memory leaks like golang's prof

**Comment by monkeyDluffy6017** [comment]
APISIX have Lua part and c part, the first step is to distinguish whether the problem is with c or lua, it's a bit complicated, so i think the easy way is to remove the code you added, it the problem still exists, seek the community for help
