### ISSUE TITLE
help request: APISIX-Base  build

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10148]
### Description

About the APISIX-Base document did not understand, there are a few questions for me:
1.What is the relationship between ApISIX-Base and APISIX？
2.Does ApISIx-base need to be deployed with apisix？
3.Does ApISIx-base and apisix version need to be the same?

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
1. Apisix-base is vanilla openresty+extra modules. Apisix can be used with both - vanilla openresty and apisix-base
2. No you can deploy apisix with plain openresty as well, but few functionality won't work. 
3. No they have different release cycles.

**Comment by lxz999** [comment]
@Revolyssup If I want to enable mTls between apisix and upstream, do I need to build an ApISIx-base environment and deploy it with apisix? Is there documentation for the build and deployment of apisix-base?

**Comment by shreemaan-abhishek** [comment]
These two documents will help you to install apisix-base:
https://apisix.apache.org/docs/apisix/building-apisix/
https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh

> If I want to enable mTls between apisix and upstream, do I need to build an ApISIx-base environment

yes.

**Comment by lxz999** [comment]
@shreemaan-abhishek TKS
