### ISSUE TITLE
help request:  dynamic certificates 这个怎么理解？

### ISSUE THREAD

**Issue by zhangyuthink** [apache/apisix#10144]
### Description

官网文档中，[Get APISIX](https://apisix.apache.org/zh/docs/apisix/getting-started/README/) 提到了 APISIX 提供“dynamic certificates” 等功能。这里的 dynamic certificates 是什么意思？动态证书吗？还是有别的理解？
谢谢。

### Environment

- APISIX version (run `3.4`)

**Comment by yuluo-yx** [comment]
yeay, You can check out the following articles for more information:
- https://apisix.apache.org/zh/docs/apisix/next/certificate/
- https://www.apiseven.com/blog/apisix-integrate-with-vault-to-store-certs

**Comment by zhangyuthink** [comment]
thanks
