### ISSUE TITLE
help request: issues using keycloak for openid connect configuration 

### ISSUE THREAD

**Issue by itsMarydan** [apache/apisix#10157]
### Description

I am having issues configuring keycloak as my open id connect provider. 

I keep getting this error  *599941 [lua] openid-connect.lua:319: phase_func(): OIDC introspection failed: response indicates failure, status=307, body=, client: 172.29.0.1, server: _, request: "GET /anything/test HTTP/1.1", host: "127.0.0.1:9080"

here is my configuration 

 curl http://127.0.0.1:9180/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '                      {                                                          "uri":"/anything/*",    "plugins": {              "openid-connect": {             "client_id": "demo",                                  
            "client_secret": "hZ7tKWlokurPPm40zYdxyTHaBxkLkT4F",
            "discovery": "https://fa8f-2600-1014-a015-f03c-7d33-7ad1-1d0b-310b.ngrok-free.app/realms/demo/.well-known/openid-configuration",
            "scope": "openid profile",
            "bearer_only": true,
            "realm": "demo",
            "redirect_uri": "http://127.0.0.1:9080/anything/callback",
            "logout_path": "/anything/logout"
        }
    },
  "upstream":{
    "type": "roundrobin",
    "nodes":{
      "httpbin.org:443":1
    }
  }
}'

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@itsMarydan Your discovery endpoint is redirecting somewhere else instead of giving discovery metadata. Make sure there are no redirection from discovery server.

**Comment by kayx23** [comment]
see if this helps https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-keycloak

**Comment by itsMarydan** [comment]
Hi I resolved my issue, For networking related concerns I was refernecing my keycloak server via ngrok  in my apisix spec but when retrieving my token from keycloak I was using localhost so the issuer did not match what apisix was expecting

**Comment by itsMarydan** [comment]
Issue is resolved!
