### ISSUE TITLE
help request: body-transformer plugin not found in apisix

### ISSUE THREAD

**Issue by vchah** [apache/apisix#10159]
### Description

I read this [article](https://www.apiseven.com/blog/apisix-soap-to-rest-plugin) mentioning that API Gateway supports the SOAP plugin, but I couldn't find the option to enable SOAP plugin in the dashboard(v3.4.0).

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@vchah This plugin is currently not available in the Open source version.

**Comment by vchah** [comment]
I attempted to use the body transformer plugin to achieve this functionality, but I couldn't find the body transformer plugin in the dashboard either. Do I need to modify the plugin schema in the source code and restart the project?

**Comment by Revolyssup** [comment]
@vchah Make sure you have this line in your config https://github.com/apache/apisix/blob/a82a2f3c439119ade45b4afffb5a251cd7bb65d2/conf/config-default.yaml#L472

**Comment by Revolyssup** [comment]
@vchah what is the output of `/apisix/admin/plugins/list`. Is `body-transformer` present?

**Comment by vchah** [comment]
My teammate deployed using [apisix-docker](https://github.com/apache/apisix-docker) v3.4.1, so is it possible that apisix-docker is missing the body-transformer plugin?

**Comment by vchah** [comment]
@Revolyssup 
My teammate deployed using [apisix-docker](https://github.com/apache/apisix-docker) v3.4.1. I didn't find the configuration for `body-transformer`, Could it be a apisix-docker issue?

**Comment by Revolyssup** [comment]
When deploying with docker, you will have a config.yaml mounted in the container using volumes. Can you check in that config.yaml? @vchah

**Comment by vchah** [comment]
@Revolyssup I follow the [documentation](https://apisix.apache.org/docs/apisix/installation-guide/#installing-apisix) for installation. And I don't modify config.yaml. So docker uses [dashboard_conf](https://github.com/apache/apisix-docker/blob/master/example/dashboard_conf/conf.yaml) and [apisix_conf](https://github.com/apache/apisix-docker/blob/master/example/apisix_conf/config.yaml)

**Comment by kayx23** [comment]
> My teammate deployed using [apisix-docker](https://github.com/apache/apisix-docker) v3.4.1. I didn't find the configuration for body-transformer, Could it be a apisix-docker issue?

@vchah not sure about the particular issue you had with dashboard but `body-transformer` should have be enabled by default. In your `config-default.yaml` you should see:

```yaml
 - body-transformer               # priority: 1080
```

If you didn't customize `config.yaml`, there's no reason why it's not enabled.

**Comment by Revolyssup** [comment]
@vchah Were you able to solve this?

**Comment by vchah** [comment]
> @vchah Were you able to solve this?

I still couldn't find 'body-transformer' in the dashboard, but I can add it through the API, so it's sufficient for now. I'll study it later.
