### ISSUE TITLE
help request: APISIX standalone mode with 40000 consumers loading exception

### ISSUE THREAD

**Issue by jeckaliu** [apache/apisix#10164]
### Description

I try to test apisix plugin jwt performance in a large  number of users, so i create 40000 users, but failed when load apisix.yaml
I use this create users:
`#! /bin/bash/python3
import os
import sys
import random

def create_consumer_to_yaml(user_counts):
    while (user_counts != 0):
        user_counts = user_counts - 1
        apisix_file.write("  - username: user%d\n" % user_counts)
        apisix_file.write("    plugins: \n")
        apisix_file.write("      jwt-auth: \n")
        apisix_file.write("        key: user%d\n" % user_counts)
        apisix_file.write("        secret: user%d\n" % user_counts)

if __name__=="__main__":
    user_str = input("input a number: ")
    user_counts = int(user_str)
    apisix_file = open("apisix.yaml", "w+")
    apisix_file.write("consumers: \n")
    
    create_consumer_to_yaml(user_counts)
    
    apisix_file.write("#END")
    apisix_file.close()`

BUT apisix error report :
2023/10/01 00:25:52 [warn] 21693#21693: *2815 [lua] config_yaml.lua:96: missing valid end flag in file /usr/local/apisix/conf/apisix.yaml, context: ngx.timer
2023/10/01 00:25:52 [warn] 21696#21696: *2813 [lua] config_yaml.lua:96: missing valid end flag in file /usr/local/apisix/conf/apisix.yaml, context: ngx.timer
2023/10/01 00:25:52 [warn] 21691#21691: *2814 [lua] config_yaml.lua:96: missing valid end flag in file /usr/local/apisix/conf/apisix.yaml, context: ngx.timer
2023/10/01 00:25:52 [warn] 21690#21690: *2818 [lua] config_yaml.lua:96: missing valid end flag in file /usr/local/apisix/conf/apisix.yaml, context: ngx.timer
2023/10/01 00:25:52 [warn] 21692#21692: *2826 [lua] config_yaml.lua:96: missing valid end flag in file /usr/local/apisix/conf/apisix.yaml, context: ngx.timer
I check apisix.yaml and '#END' still  in the end of file. 

I need help wondering if there are any limitations or configurations of APISIX with a large numbers  of users.

### Environment

- APISIX version (run `apisix version`):3.4.1
- Operating system (run `uname -a`):Linux ubuntu 4.15.0-142-generic #146~16.04.1-Ubuntu SMP Tue Apr 13 09:27:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:jwt
- LuaRocks version, for installation issues (run `luarocks --version`):luarocks 3.9.2

**Comment by Revolyssup** [comment]
in your code snippet, you have 
``` 
create_consumer_to_yaml(user_counts)
apisix_file.write("#END")
```

please change the order

```
apisix_file.write("#END")
create_consumer_to_yaml(user_counts)

```

**Comment by jeckaliu** [comment]
thanks anyway， too many consumers cause a very slow apisix loading，and errors。I‘m try to limit consumers under 15000 ， `apisix start `  cause  about 40 seconds and no warn logs.
