### ISSUE TITLE
help request: failed to find any SSL certificate by SNI: health check

### ISSUE THREAD

**Issue by cyrnicolase** [apache/apisix#10162]
### Description

I get a lot of error messages。

`*93212869 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: health check, context: ssl_certificate_by_lua*, client: 14.17.67.52, server: 0.0.0.0:443`

Everything is same except the client ip.

I'v added the configure 
```yaml
apisix:
    ssl:
      fallback_sni: {$my_domain}
```

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.21.4.1

**Comment by Revolyssup** [comment]
@cyrnicolase Have you configured the ssl certificate for your fallback sni?

**Comment by Revolyssup** [comment]
Its trying to find cert for sni named `health check`. Are you sure that should be your `$my_domain` ?

**Comment by cyrnicolase** [comment]
OK , thanks. Domain name is not resolved.

**Comment by cyrnicolase** [comment]
@Revolyssup Could you help me
