### ISSUE TITLE
url过长时会报错404 Route Not Found

### ISSUE THREAD

**Issue by caster-Q** [apache/apisix#10169]
### Description

直连上游访问没有问题，不会报错，url设置短一些访问也不会报错
代理的elasticsearch，当索引名特别多，url过长时会报错，是不是代码里面承载url的变量有长度限制？
修改了nginx参数  large_client_header_buffers 40 200k; 没有效果

### Environment

- APISIX version (run `apisix version`): 3.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4

**Comment by yuluo-yx** [comment]
Can you provide apisix runtime logs? This helps us analyze and solve problems.

**Comment by bingym** [comment]
https://apisix.apache.org/docs/apisix/admin-api/#quick-note-on-id-syntax
