### ISSUE TITLE
help request: AES-128-GCM encryption in plugin

### ISSUE THREAD

**Issue by amyrprv** [apache/apisix#10163]
### Description

I created a custom plugin and I want to encrypt one property of the request body. I figured out that it requires `lua-openssl ` package from Luarocks which is not present in the current rockspec dependency tree. Is there any way to perform AES-128-GCM encryption? I am running Apisix from the official docker image. 

```
local ffi         = require("ffi")
local openssl     = require("openssl")

local function encrypt(key, src)
    
    openssl.rand_load()
    local iv = openssl.random(12)

    local cipher = openssl.get_cipher("AES-128-GCM")
    local ctx = openssl.evp_encrypt_init(key, iv, cipher, true)

    local cipherText, tag = ctx:final(src)

    if #cipherText ~= #src + 16 then
        core.log.error("Invalid cipher text length")
    end

    local message = ffi.new("char[?]", 12 + #src + 16)
    ffi.copy(message, iv, 12)
    ffi.copy(message + 12, cipherText, #cipherText)

    return ffi.string(message, 12 + #src + 16)
end
```

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Linux c518c369b311 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@amyrprv You're writing in-tree custom plugin or using serverless plugin to embed your code?

**Comment by amyrprv** [comment]
@Revolyssup I am writing a custom plugin.

**Comment by jiangfucheng** [comment]
@amyrprv  Hi, Maybe https://github.com/openresty/lua-resty-string this library will be helpful to you.

**Comment by gujiwork** [comment]
I am using AES encryption for the returned response content, serverless-post-function   body_filter or rewrite, is there an example?

**Comment by amyrprv** [comment]
@gujiwork Hi, I used [lua-resty-string](https://github.com/openresty/lua-resty-string) and it worked fluently, and it has examples.

**Comment by gujiwork** [comment]
> @gujiwork Hi, I used [lua-resty-string](https://github.com/openresty/lua-resty-string) and it worked fluently, and it has examples.

Thank you for your reply, but I can't get response data using core.response.hold_body_chunk(ctx).
```
return function(conf, ctx)
    local core = require(\"apisix.core\");
    local aes = require 'resty.aes';
    local cjson = require(\"cjson\");
    local ngx_resp = require \"ngx.resp\";
    local cipher = aes:new('0123456789123456', nil, aes.cipher(128, 'ecb'));
    local body = core.response.hold_body_chunk(ctx)

    core.response.set_header(\"X-API-VERSION\", \"v1\");

    ngx.say(ngx.encode_base64(cipher:encrypt(body)))

end
```

**Comment by monkeyDluffy6017** [comment]
considered resolved
