### ISSUE TITLE
help request: forward_auth plug-in uses an external authentication service

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10170]
### Description

When the forward-auth plug-in uses an external authentication service, can it obtain the apisix custom variable from the external service? Such as route_id

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
APISIX does not support this feature.

**Comment by lxz999** [comment]
@jiangfucheng TKS
