### ISSUE TITLE
APIsix Whether port matching is supported?

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#10177]
### Description

Does the APIsix routing function support port matching? nginx is supported

I have advanced configuration in the route but the route returns

{

"error_msg": "404 Route Not Found"

}

route config:
```
{
    "id": "477538366955455167",
    "create_time": 1694164647,
    "update_time": 1694164647,
    "uri": "/*",
    "name": "port-matchtest",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "vars": [
        [
            "remote_port",
            "==",
            "9080"
        ]
    ],
    "upstream": {
        "nodes": [
            {
                "host": "10.210.21.106",
                "port": 8000,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
 curl http://10.210.21.106:9080/
{"error_msg":"404 Route Not Found"}
![image](https://github.com/apache/apisix/assets/131146587/3572e776-5b98-43f6-b6bc-f377fd14e4ff)

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by bin-53** [comment]
@Sn0rt

**Comment by Sn0rt** [comment]
ok. I will take a look and confirm again.

**Comment by bin-53** [comment]
> 

Is it normal?

**Comment by Sn0rt** [comment]
apisix not support dispatch the tattric by match the port
https://apisix.apache.org/zh/docs/apisix/admin-api/#route-request-body-parameters

**Comment by Sn0rt** [comment]
it looks support match the by  `nginx` build in var

https://apisix.apache.org/zh/docs/apisix/admin-api/#route-request-body-parameters

**Comment by bin-53** [comment]
> it looks support match the by `nginx` build in var
> 
> https://apisix.apache.org/zh/docs/apisix/admin-api/#route-request-body-parameters
Yes, thank you for your reply. I see the documentation is also supported, but you see my above test case, the return is 404, you can try it? I don't know if I have a configuration error or if apisix itself has a bug

**Comment by bin-53** [comment]
> it looks support match the by `nginx` build in var
> 
> https://apisix.apache.org/zh/docs/apisix/admin-api/#route-request-body-parameters

Hello. Any results?

**Comment by bin-53** [comment]
Hasn't that been dealt with？

**Comment by tokers** [comment]
The reason is that `remote_port` is the port for the TCP client, not a server port, and it's always picked by the kernel randomly. You can try to print the `remote_port` in log to see its values. I bet it won't be `9080`.

As per your question, I think you should use the `$server_port` variable (which is also a built-in Nginx variable).

**Comment by monkeyDluffy6017** [comment]
I agree with @tokers, considered resolved
