### ISSUE TITLE
help request: What is the default maximum size of apisix access.log and error.log file

### ISSUE THREAD

**Issue by darkSheep404** [apache/apisix#10174]
### Description

Dear apisix team

I want to know what the maximum size of apisix access.log and error.log is

Springboot's log files seem to can add some configuration that, when they reach a certain size such as 50MB, puts the previous logs in a zip named with a timestamp like `app_2023-19.log.gz`

Does Apisix have this feature, and if so, how big does a single access.log file grow to put the previous log file into a zip file

尊敬的apisix team
我希望知道 apisix access.log和 error.log的最大大小是多少
Springboot的日志文件 似乎可以通过一些配置,当达到一定大小如50MB时,将之前的日志放到一个用时间戳命名的压缩包内 
例如``app_2023-19.log.gz`
Apisix有这方面的特性吗,如果有的话 单个access.log文件在达到多大以后 会把之前的日志文件放进一个压缩包内呢

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi, APISIX also support this feature, more details in https://apisix.apache.org/docs/apisix/plugins/log-rotate/

**Comment by darkSheep404** [comment]
> Hi, APISIX also support this feature, more details in https://apisix.apache.org/docs/apisix/plugins/log-rotate/↳
好的
多谢多谢!
