### ISSUE TITLE
help request: routing to different upstreams per APISIX listening ports

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#10178]
### Description

我希望在APISIX配置多个端口，比如8080、9090
然后我配置多个upstream， 如：upstream1. upstream2

我希望请求8080，就走upstream1   请求9090，就走upstream2

不知道是否可行，就像nginx的多个server一样

**Comment by githubxubin** [comment]
I have the same problem

**Comment by tokers** [comment]
Use the `vars` expression in the Route. You can use the `$server_port` variable as a condition. So that the server port can be used to match Route, and in different routes, you can configure different upstreams.

**Comment by bin-53** [comment]
> server_port

yeh server_port is OK,But why not remote_port，It is a built-in variable in nginx.  Could you please look at this issue #10177

**Comment by tokers** [comment]
> > server_port
> 
> yeh server_port is OK,But why not remote_port，It is a built-in variable in nginx. Could you please look at this issue #10177

for a TCP connection, the port of the party who initializes the connection is always unpredictable, usually, it's selected by the kernel. So it's not easy to use `client_port` as the condition.

**Comment by monkeyDluffy6017** [comment]
considered resolved
