### ISSUE TITLE
feat: As a community maintainer, I want to add github action so that manager stale issue

### ISSUE THREAD

**Issue by yuluo-yx** [apache/apisix#10173]
## Background

There are a lot of issues in the apisix community now, and it is inevitable that some PRs have been put on hold for a long time because users did not reply or for other reasons, resulting in a large accumulation of issues.

## action

My approach is to add a github action to close the accumulated issues. 
The effect is like the spring-cloud-alibaba community: https://github.com/alibaba/spring-cloud-alibaba/issues/3373
As you can see, he will first comment in the issue, prompt the user, and close the issue if there is no reply

## expected

The expected effect is to reduce the number of community issues, help community maintainers better build the community, and promote community development.

**Comment by yuluo-yx** [comment]
If this github action is needed, assign it to me and I'll get it done.
@Sn0rt

**Comment by jiangfucheng** [comment]
Does this [action](https://github.com/apache/apisix/blob/master/.github/workflows/close-unresponded.yml) already do this feature?

**Comment by shreemaan-abhishek** [comment]
Yep, stale issue management is already in place.

**Comment by shreemaan-abhishek** [comment]
But the `days-before-issue-stale` value is too big. A lot of issues get accumulated really quickly and 350 days seems too big.

https://github.com/apache/apisix/blob/08474294a5d297e6aed0a1b99c8a01263524d950/.github/workflows/stale.yml#L24C37-L24C37

**Comment by yuluo-yx** [comment]
> 此[操作](https://github.com/apache/apisix/blob/master/.github/workflows/close-unresponded.yml)是否已实现此功能？

yeay

**Comment by yuluo-yx** [comment]
> But the `days-before-issue-stale` value is too big. A lot of issues get accumulated really quickly and 350 days seems too big.
> 
> https://github.com/apache/apisix/blob/08474294a5d297e6aed0a1b99c8a01263524d950/.github/workflows/stale.yml#L24C37-L24C37

I think it can be changed to 30 days, and 100 days is a bit long. 30 days is enough to judge the status of the issue.

**Comment by moonming** [comment]
In the Apache APISIX community, most contributors do not work full-time on APISIX, and they are not obligated to respond to issues and PRs.
Therefore, the basis for judging issues is whether it is a problem, not the response time of the contributor. If you think it is not a problem, you can close the issue immediately. Don't put the cart before the horse.

**Comment by yuluo-yx** [comment]
> 在 Apache APISIX 社区中，大多数贡献者并不是全职从事 APISIX 工作，他们没有义务响应问题和 PR。 因此，判断问题的依据是是否是问题，而不是贡献者的响应时间。如果您认为没有问题，可以立即关闭该问题。不要本末倒置。

done!
