### ISSUE TITLE
help request: ssl config with error！

### ISSUE THREAD

**Issue by whatbug** [apache/apisix#10185]
Why is the SSL certificate invalid after updating the latest version, regardless of whether it is updated through the admin API or through the panel, and an SSL error is reported with "ERR_SSL_PROTOCOL_ERROR"？k8s env. thanks.

**Comment by Revolyssup** [comment]
@whatbug Can you provide the apisix configuration?

**Comment by whatbug** [comment]
> @whatbug Can you provide the apisix configuration? And also provide some error logs.

<img width="439" alt="image" src="https://github.com/apache/apisix/assets/32671621/1550a01a-b6b1-4663-9815-55b23f48aa0c">

long long time ago it's work well, but updated.

**Comment by whatbug** [comment]
![image](https://github.com/apache/apisix/assets/32671621/80e78611-97a4-4274-bb94-4664a88e3dd3)
Already of a commercial nature！
