### ISSUE TITLE
setting the  limit-conn,limit-count does not work

### ISSUE THREAD

**Issue by DavidChild** [apache/apisix#10186]
### Current Behavior

Problem description:

My environment has deployed two load APISIX and ETCD storage

It has been running online for some time now. Recently, we need to configure a flow limiting instance in the routing layer. However, after the configuration is completed, the JEMETER concurrency pressure has passed, and every request from JEMETER has passed normally without returning an abnormal 503 state.

the limit_conn/ limit-count setting configuration is as follows:

![image](https://github.com/apache/apisix/assets/18735238/e6331ec2-9e51-4ed9-b1e2-88898dd6fad7)

JEMETER's routing debugging configuration for APISIX: 30 per second, executed 10 rounds.

### Expected Behavior

I hope that Jemeter  debugged to apisix    and then APISIX can limit current and fuse normally

### Error Logs
none

### Steps to Reproduce

RUN APISIX WITH DOCKER

### Environment

- APISIX VERSION 2.10.0
- dashboard_version: 2.9.0

**Comment by Kingraymone** [comment]
I have the same question too

**Comment by monkeyDluffy6017** [comment]
I don't know much about jemeter, but the limit count plugin can work only with one machine, if you have n machines, please set the limt to limit/n, or use the redis policy

**Comment by monkeyDluffy6017** [comment]
I will close this issue, feel free to reopen it
