### ISSUE TITLE
bug: apisix doesn't consider healthy etcd nodes

### ISSUE THREAD

**Issue by panditha** [apache/apisix#10191]
### Current Behavior

We have setup a APISIX gateway in K8S and configured with etcd cluster hosted externally outside of K8S cluster. We have come across a scenario where one of our 3 nodes is down abut etcd cluster is responsive using etcdctl command. However apisix gateway is failing with error "none of the configured etcd works well" and keeps trying to connect to only the node that is down and not trying to connect to other available 2 nodes. Due to this behaviour gateway is getting into "CrashLoopBackOff" finally making it impossible to restart the gateway. We have cross verified that we have provided all 3 etcd nodes in apisix config.

### Expected Behavior

APISIX gateway should consider available etcd nodes for communication.

### Steps to Reproduce

stop one of the etcd node and error should be reproducable.

### Environment

staging & production.

**Comment by Revolyssup** [comment]
@panditha Can you share some of the error logs? As well as a minimal example of your apisix configuration?

**Comment by monkeyDluffy6017** [comment]
I will close this pr due to long period of no reponse, feel free to reopen it
