### ISSUE TITLE
Bug: multi-domain ssl cert taking precedence over non multi-domain certificate 

### ISSUE THREAD

**Issue by xjzyy** [apache/apisix#10199]
### Current Behavior

apisix version：2.13.1

After configuring a pan-domain SSL certificate, subsequent updates to non-pan-domain SSL certificates after expiration will not take effect. When accessing the domain name page to update the certificate, the SSL of the pan-domain name will be recognized by default, causing the page to be inaccessible.

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Linux apisix-02 3.10.0-1160.62.1.el7.x86_64 #1 SMP Tue Apr 5 16:57:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 2.11.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@xjzyy Can you provide your apisix configuration?

**Comment by monkeyDluffy6017** [comment]
I will close this pr due to long period of no response, feel free to reopen it
