### ISSUE TITLE
bug: The port matching of the advanced match failed. Procedure

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10205]
### Current Behavior

I use apisix's advanced Match to get the port that matches the remote, and perform different routing based on the port, but when I set remote_port, it doesn't work, 404 is returned, and I was operating on dashboard
 this is my config:

I have advanced configuration in the route but the route returns
{

"error_msg": "404 Route Not Found"

}
1.route config:
```
{
    "id": "477538366955455167",
    "create_time": 1694164647,
    "update_time": 1694164647,
    "uri": "/*",
    "name": "port-matchtest",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "vars": [
        [
            "remote_port",
            "==",
            "9080"
        ]
    ],
    "upstream": {
        "nodes": [
            {
                "host": "10.210.21.106",
                "port": 8000,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
2.request route:
curl http://10.210.21.106:9080/
{"error_msg":"404 Route Not Found"}
![image](https://github.com/apache/apisix/assets/39228009/13b965dc-b771-4765-87c2-b9215b7bc627)

### Expected Behavior

Can be correctly matched through the remote port

### Error Logs

{"error_msg":"404 Route Not Found"}

### Steps to Reproduce

1.set the route
2.request route
See above for the specific configuration

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Remote port is unpredictable, although we know that we initiated the request to port 9080, the port that actually started the request is different. You can verify it like so:

```bash
curl http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/header",
    "plugins": {
        "response-rewrite": {
            "headers": {
                "set": {
                    "init-port": "$remote_port"
                }
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```

<img width="476" alt="image" src="https://github.com/apache/apisix/assets/61597896/78b946c7-62b5-4fc8-8389-4a686b09e3fa">
