### ISSUE TITLE
help request: getting 503 and 502 responses when sending a request to APISIX, after creating services and routes

### ISSUE THREAD

**Issue by deekayzain** [apache/apisix#10207]
### Current State

As I am new to Apache apisix. Documentation is missing some important things as I am facing like..

How to validate the Service and Routes example after creation under Service Link:
https://apisix.apache.org/docs/apisix/terminology/service/

After creating service and routes the steps for validating the said service is missing. 
Please provide the steps.

### Desired State

Examples should have proper justification for doing certain activity.

**Comment by kayx23** [comment]
@deekayzain check out this getting started tutorial series, which includes the verification steps for any route and resources configured: https://apisix.apache.org/docs/apisix/next/getting-started/README/

It should provide a better idea for how to verify your services.

**Comment by deekayzain** [comment]
> @deekayzain check out this getting started tutorial series, which includes the verification steps for any route and resources configured: https://apisix.apache.org/docs/apisix/next/getting-started/README/
> 
> It should provide a better idea for how to verify your services.

after creation of route, while validating using curl "http://127.0.0.1:9080/ip"   getting error as 503 Service Temporarily Unavailable

**Comment by kayx23** [comment]
How did you install APISIX? With the quickstart script provided in the tutorial?

**Comment by deekayzain** [comment]
I installed with rpm insatallation instructions provided in apisix site on
RHEL 8.8 server.
Is there any missing instructions on site?

Please let me know.

**Comment by kayx23** [comment]
The tutorial series should all work as expected if you install this way (recommended for beginners): https://apisix.apache.org/docs/apisix/next/getting-started/README/#get-apisix

As for the 503, please provide error log for more info.

**Comment by deekayzain** [comment]
> The tutorial series should all work as expected if you install this way (recommended for beginners): https://apisix.apache.org/docs/apisix/next/getting-started/README/#get-apisix
> 
[error.log](https://github.com/apache/apisix/files/12656293/error.log)

> As for the 503, please provide error log for more info.

Kindly find the error.log for your reference.

**Comment by kayx23** [comment]
I can't seem to find logs associated to your 503 error. Please find the associated logs to see if they help you localize the problem.

You're looking for something that looks like this, but for 503:

![image](https://github.com/apache/apisix/assets/39619599/346e4059-28db-47c1-8f26-32f0c1460698)

**Comment by deekayzain** [comment]
> I can't seem to find logs associated to your 503 error. Please find the associated logs to see if they help you localize the problem.
> 
> You're looking for something that looks like this, but for 503:
> 
> ![image](https://user-images.githubusercontent.com/39619599/268860690-346e4059-28db-47c1-8f26-32f0c1460698.png)

Actually we are not getting any log having 503 and 502- Bad Gateway error in error.log. But we getting these on Postman and server putty. What to do ? please help.

**Comment by kayx23** [comment]
Well this doesn't sound like an issue on the APISIX side then.

Sounds like you're SSH into a remote server with Putty client? So your APISIX is on a remote server and where is postman? Could this be a network issue

**Comment by deekayzain** [comment]
> Well this doesn't sound like an issue on the APISIX side then.
> 
> Sounds like you're SSH into a remote server with Putty client? So your APISIX is on a remote server and where is postman? Could this be a network issue

Yes, Apisix is on remote RHEL server and postman is on local window machine.

**Comment by kayx23** [comment]
Does your remote RHEL server firewall and other network security settings in your environment allow for ingress traffic from your local window machine?

**Comment by kayx23** [comment]
Closing this question for now as the errors are related to the user's specific network setup.

If there's anything on the APISIX side that could be addressed, you can reopen the issue.
