### ISSUE TITLE
bug: The etcdserver: invalid auth token appears after apisix is started

### ISSUE THREAD

**Issue by caihonghaoCYF** [apache/apisix#10203]
### Current Behavior

Our etcd is configured with auth permission authentication, and the user name and password are configured correctly, but the e**tcdserver: invalid auth token** appears when apisix is started. Strangely enough, the etcd token that I used to error with apisix was successfully called directly through the etcd v3 api

### Expected Behavior

Help deal with it as soon as possible

### Error Logs

[lua] init.lua:97: http_init(): failed to load the configuration: etcdserver: invalid auth token

### Steps to Reproduce

apisix start

### Environment

- APISIX version : 3.1.0
- Operating system: centos7
- OpenResty: 1.19.9.1
- etcd version: 3.4.0

**Comment by Revolyssup** [comment]
@caihonghaoCYF so you have the correct username and password set in etcd.user and etcd.password inside the apisix config right?

**Comment by monkeyDluffy6017** [comment]
@caihonghaoCYF have you solved the problem?

**Comment by lakewatcher** [comment]
etcdserver: invalid auth token  , also found on apisix 2.15.3 
![image](https://github.com/apache/apisix/assets/27823963/6ab51f9d-aec7-4b28-a7a1-fde5cc4ed1c0)

**Comment by Revolyssup** [comment]
@caihonghaoCYF Looks like the token expired. Anyways, a PR was merged to add retries and backported to etcd 3.5[1]. Can you please retry with etcd 3.5 version?
1. https://github.com/etcd-io/etcd/pull/13477

**Comment by smileby** [comment]
@Revolyssup  @monkeyDluffy6017  Hi, I also encountered this problem.
When I called ‘/apisix/admin/routes’ to create a route, an ‘invalid auth token’ error occurred.

The error log is as follows：
```shell
2023/12/12 09:33:41 [error] 5675#0: *371176679 [lua] resource.lua:168: failed to post route[/routes] to etcd: etcdserver: invalid auth token, client: 127.0.0.1, server: , request: "POST /apisix/admin/routes HTTP/1.1", host: "127.0.0.1:9180"
2024/01/15 19:14:45 [error] 5679#0: *735722611 [lua] resource.lua:168: failed to post route[/routes] to etcd: etcdserver: invalid auth token, client: 127.0.0.1, server: , request: "POST /apisix/admin/routes HTTP/1.1", host: "127.0.0.1:9180"
2024/01/26 18:02:06 [error] 5679#0: *851524365 [lua] resource.lua:168: failed to post route[/routes] to etcd: etcdserver: invalid auth token, client: 127.0.0.1, server: , request: "POST /apisix/admin/routes HTTP/1.1", host: "127.0.0.1:9180"
```
Apart from the above information, there is no more content

environmental information:
```shell
etcd version:  3.5.4     ==> Deploy 3 nodes
etcd is configured with permission authentication
APISIX version : 3.2.0   ==>  Deploy 1 node
```

I have verified that the supplementary call and retry can be successful. But frequent retries bother me. Is there a better way to solve it?

**Comment by smileby** [comment]
I saw #8862 also mentioned this issue

**Comment by lakewatcher** [comment]
Has it been fixed?
