### ISSUE TITLE
feat: As a user, I want to dynamic set proxy-buffering parameter, so fit the SSE situation 

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#10204]
### Description

proxy_buffering is :
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

<img width="703" alt="image" src="https://github.com/apache/apisix/assets/10181098/5b866d15-215b-47db-959e-88cc078a074e">

**Comment by jiangfucheng** [comment]
Could you please describe your issue in English? This will allow more people to offer you assistance.

**Comment by kayx23** [comment]
This was supported in enterprise version: https://docs.api7.ai/hub/proxy-buffering

afaik there's currently no plan to port this to open source. cc: @monkeyDluffy6017

**Comment by br41n10** [comment]
You can set in nginx configuration snippet, for example, add this in config.yaml

```
nginx_config:
  http_server_location_configuration_snippet: |
    proxy_buffering off;
```

run `apisix init` and you will see `proxy_buffering off;` in `conf/nginx.con`. 

Limitation: Works for all Routes. I'm not sure is it possible to do this in custom plugin, to enable on individual Route.

**Comment by a1156698162** [comment]
> You can set in nginx configuration snippet, for example, add this in config.yaml
> 
> ```
> nginx_config:
>   http_server_location_configuration_snippet: |
>     proxy_buffering off;
> ```
> 
> run `apisix init` and you will see `proxy_buffering off;` in `conf/nginx.con`.
> 
> Limitation: Works for all Routes. I'm not sure is it possible to do this in custom plugin, to enable on individual Route.

@br41n10 可是我验证下来，apisix不用额外配置就支持sse。我看了apisix运行时生成的nginx.conf。没有发现proxy_buffering这个配置。那按道理默认时on的呀。这块原因您清楚吗？
