### ISSUE TITLE
bug: Changes through admin API doesn't take effect until restarting APISIX

### ISSUE THREAD

**Issue by jerrychenhf** [apache/apisix#10208]
### Current Behavior

I use Admin API to create Routes, Services and Upstreams, for example:
Route:
 {
      "value": {
        "priority": 0,
        "create_time": 1694749955,
        "service_id": "node-exporter",
        "update_time": 1694752938,
        "uris": [
          "/node-exporter",
          "/node-exporter/*",
        ],
        "id": "node-exporter",
        "status": 1
      },
      "key": "/example-apisix/routes/node-exporter",
      "modifiedIndex": 130,
      "createdIndex": 39
    },
Service:
{
      "value": {
        "update_time": 1694751018,
        "id": "node-exporter",
        "create_time": 1694749955,
        "upstream_id": "node-exporter"
      },
      "key": "/example-apisix/services/node-exporter",
      "modifiedIndex": 98,
      "createdIndex": 38
    },
Upstream:
{
      "value": {
        "update_time": 1694750166,
        "nodes": {
          "172.19.0.9:9100": 1,
          "172.19.0.10:9100": 1,
          "172.19.0.11:9100": 1,
          "172.19.0.12:9100": 1,
          "172.19.0.13:9100": 1,
          "172.19.0.6:9100": 1,
          "172.19.0.7:9100": 1,
          "172.19.0.8:9100": 1
        },
        "create_time": 1694749955,
        "scheme": "http",
        "hash_on": "vars",
        "id": "node-exporter",
        "pass_host": "pass",
        "type": "roundrobin"
      },
      "key": "/example-apisix/upstreams/node-exporter",
      "modifiedIndex": 81,
      "createdIndex": 37
    },

Everything created fine and can be queried through the Admin API.
But when I use it through "curl http://172.19.0.10:9080/node-exporter", it returns "404 Route Not Found"

After I restarted APISIX, the route takes effect and can working by "curl http://172.19.0.10:9080/node-exporter".

Other problems: Once restarted, the route takes effect. And I then use Admin API to change the route paths, for example, change to:
"uris": [
          "/node-exporter"
        ],

The Admin API is successful and can query the change through the Admin API. But the change doesn't take effect and need a restart to take effect.
I found that use Control API to query the routes and it returns the original "uris" before the change. (the Admin API routes and Control API routes return different result)

### Expected Behavior

Admin API change should take effect immediately (or within a expected interval) without restart the APISIX.

### Steps to Reproduce

1. I have a deployment tool for services like APISIX, running in docker container.
2. Start the service: sudo apisix start -c ${APISIX_CONFIG_FILE}. The service started successfully. 
3. My program used Admin API to create Upstream, Service and Route automatically and the Admin API are all successfully and the entities can be queried correctly through Admin API.
4. Try use the API Gateway through curl http://172.19.0.10:9080/node-exporter but it showed Route not found error.

### Environment

- APISIX version (run `apisix version`): 3.4.1
- Operating system (run `uname -a`): Linux 5169200c8a54 5.15.0-1044-aws #49~20.04.1-Ubuntu SMP Mon Aug 21 17:09:32 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.9
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jerrychenhf** [comment]
The Config file with the above issue for more information:
apisix:
  node_listen:
  - ip: 127.0.0.1
    port: 9080
  - ip: 172.19.0.10
    port: 9080
deployment:
  admin:
    admin_key:
    - key: XXXXXXXXXXXXXXXXXXXXX
      name: admin
      role: admin
    admin_listen:
      ip: 127.0.0.1
      port: 9180
  etcd:
    host:
    - http://172.19.0.3:2379
    - http://172.19.0.5:2379
    - http://172.19.0.4:2379
    prefix: /example-apisix
  role: traditional
  role_traditional:
    config_provider: etcd


After the change using Admin API, execute "sudo apisix reload" will also make the change take effect. And the Control API routes will return the same result as Admin API routes.

**Comment by jerrychenhf** [comment]
I found what configuration caused this behavior/bug.
In my Config.yaml, I used etcd "prefix: /example-apisix" instead the default "prefix: /apisix".
When I changed the /example-apisix back to /apisix or any other things that doesn't contain a dash "-", for example "/bapisix". The change immediately available at the control API and taking effect without restart/reload. If there is a dash in the prefix, the change will not see in the control API until a reload.

Please confirm whether this is a bug in APISIX.

**Comment by jiangfucheng** [comment]
@jerrychenhf  Hi, it seems to duplicate with https://github.com/apache/apisix/issues/9951 , it has been fixed, please use the latest version to test it again.

**Comment by monkeyDluffy6017** [comment]
considered resolved
