### ISSUE TITLE
help request: tls question

### ISSUE THREAD

**Issue by anhuiyu** [apache/apisix#10212]
### Description

client use mbedtls2 can't connect to the server,is it  cipher?help

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@anhuiyu Can you provide some relevant error logs and apisix configuration(if relevant)?

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
