### ISSUE TITLE
help request: failed to find any SSL certificate by SNI: health check

### ISSUE THREAD

**Issue by cyrnicolase** [apache/apisix#10217]
### Description

I get a lot of error messages like this:

```
*150084832 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: health check, context: ssl_certificate_by_lua*, client: 163.181.67.158, server: 0.0.0.0:443
```

Everything is same except the client ip.
I'v added the configure

```yaml
apisix:
    ssl:
      fallback_sni: ll.haochang.tv
```

My web system works in order, but I'm keeping get the error messages. I don't know why and how to fix it.

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): centos7 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1

**Comment by Revolyssup** [comment]
Have you configured the ssl cert for this particular sni in apisix configuration? Can you show if you have the relevant SSL resource configured on `/apisix/admin/ssls` endpoint with proper SNI?

**Comment by cyrnicolase** [comment]
![image](https://github.com/apache/apisix/assets/2086960/d8f1a2cd-7290-4d58-961a-4038f85d4c34)

Yes, it is. I use wildcard ssl certificates, and you can visit https://ll.haochang.tv

**Comment by Revolyssup** [comment]
@cyrnicolase Which requests cause this error? Because here sni is set as `health check` by client? 
Do you get these errors when normally accessing with
`curl -H "Host: ll.haochang.tv" https://ll.haochang.tv/` ?

**Comment by cyrnicolase** [comment]
No，we don't set `health check`, I don't kown why . My apisix is deployed in aliyun with SLB.

When I curl this domain, no error occurs

**Comment by cyrnicolase** [comment]
@Revolyssup My server works well right now. The only question is that there are lots of errors messages which puzzles me.

`*154616972 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: health check, context: ssl_certificate_by_lua*, client: 163.181.79.183, server: 0.0.0.0:443`

**Comment by monkeyDluffy6017** [comment]
@cyrnicolase have you solved you problem?

**Comment by cyrnicolase** [comment]
Not yet

**Comment by monkeyDluffy6017** [comment]
@AlinsRan please help to check this

**Comment by cyrnicolase** [comment]
NO , I've given up
