### ISSUE TITLE
dashboard plugin market 404

### ISSUE THREAD

**Issue by chiliast123** [apache/apisix#10226]
### Description

I used helm to deploy the apisix 3.5, the apisix-dashboard is the 3.0 version, but the dashboard plugin market page prompts 404, is there something wrong with my configuration?

And here another question, I configured the route and upstream, using openssl command in pod effect, outside will not work, what's the reason? you can check the picture below:

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
duplicating #10227
