### ISSUE TITLE
health check counter success always being 0

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10230]
### Description

The health check count (fetched from Control API healthcheck endpoint) is always 0, even the requests are successfully sent to the upstream nodes. Why is that the case? Is this not the count of successful requests?

### Start APISIX and Upstream Services

Get APISIX [here](https://apisix.apache.org/docs/apisix/getting-started/README/#get-apisix).

Start two sample NGINX containers to be used as upstream services in the same Docker network as APISIX:

```shell
DOCKER_NETWORK=apisix-quickstart-net
docker run -d -p 8080:80 --network=${DOCKER_NETWORK} --name nginx1 nginx
docker run -d -p 8081:80 --network=${DOCKER_NETWORK} --name nginx2 nginx
```

### Configure Active Checks

```shell
curl "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "example-hc-route",
  "uri":"/",
  "upstream": {
    "type":"roundrobin",
    "nodes": {
      "nginx1:80": 1,
      "nginx2:80": 1
    },
    "checks": {
      "active": {
        "type": "http",
        "http_path": "/",
        "healthy": {
          "interval": 2,
          "successes": 1
        },
        "unhealthy": {
          "interval": 1,
          "timeouts": 3
        }
      }
    }
  }
}'
```

Send a request to Control API health check endpoint. It returns no health check info, as expected: 

```shell
curl "http://127.0.0.1:9090/v1/healthcheck"

[{"name":"/apisix/routes/example-hc-route","nodes":{},"type":"http"}]
```

Send 5 requests to the route:

```shell
seq 5 | xargs -I{} curl "http://127.0.0.1:9080/" -sL
```

You should receive 200 responses for all.

Now if you check the health check info using Control API:

```shell
curl "http://127.0.0.1:9090/v1/healthcheck"
```

You get `"success": 0` in counter. This `success` value doesn't seem to change:

```text
[
    {
        "name": "/apisix/routes/example-hc-route",
        "nodes": [
            {
                "counter": {
                    "timeout_failure": 0,
                    "http_failure": 0,
                    "success": 0,
                    "tcp_failure": 0
                },
                "port": 80,
                "ip": "172.25.0.4",
                "status": "healthy"
            },
            {
                "counter": {
                    "timeout_failure": 0,
                    "http_failure": 0,
                    "success": 0,
                    "tcp_failure": 0
                },
                "port": 80,
                "ip": "172.25.0.5",
                "status": "healthy"
            }
        ],
        "type": "http"
    }
]
```

### Environment

APISIX version: v3.5.0 in the published Debian image.

**Comment by kayx23** [comment]
The root cause has been localized by @kingluo : the issue stems from the nodes statuses always being initialized with a state of `healthy`. This was before any checks that take place.

So in the case of an active check, if all subsequent requests are successful, then the note status remains `healthy` and unchanged. As a result, the `success` counter remains `0`.

**Comment by luoluoyuyu** [comment]
hi @moonming @kayx23 , I want to try it, please assign this issue to me

**Comment by kayx23** [comment]
Hi, thanks for the analysis and the diagram.

> if the node node is always in health state, then the success will always be 0 unless the node node state is changed.

Yes, the same behaviour is also described [above](https://github.com/apache/apisix/issues/10230#issuecomment-1726812559), that the node status is initialized to be healthy and if the status never change, counter remains 0. I guess this is more of a design discussion that if this behaviour is acceptable. If it is, feel free to resolve.

**Comment by monkeyDluffy6017** [comment]
Maybe we could update the doc to clarify this? @luoluoyuyu

**Comment by vvvvvant** [comment]
I conducted a test where I added an unreachable node upstream of the active check. I found that the status of this node was also "health". I can guarantee that it is unreachable. Upon observing the forwarding logs of this route, I noticed that some traffic to this node would time out (504) before being forwarded to a normal node (200) @monkeyDluffy6017 @luoluoyuyu
