### ISSUE TITLE
http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol

### ISSUE THREAD

**Issue by chenghongxi** [apache/apisix#10234]
### Description

failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 111.26.161.235, server: 0.0.0.0:9443

### Environment

- APISIX version (run `apisix version`):3.5
- Operating system (run `uname -a`):centos7.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:2.15
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by chenghongxi** [comment]
证书通过dashboard上传，如下图：
<img width="1693" alt="证书" src="https://github.com/apache/apisix/assets/48846160/8c15b342-e61b-48ad-9de1-77783e9865bb">
apisix config.yml,如下图：
<img width="276" alt="yaml" src="https://github.com/apache/apisix/assets/48846160/d548aea8-7045-4eec-a01f-466b3d2a0037">

**Comment by chenghongxi** [comment]
route json如下：
{
  "uri": "/api/form/gateway/save/6688d9e0c1225a46f4838ee08dd7392c",
  "name": "test",
  "plugins": {
    "consumer-restriction": {
      "rejected_code": 403,
      "rejected_msg": "不允许访问",
      "type": "consumer_name",
      "whitelist": [
        "6688d9e0c1225a46f4838ee08dd7392c"
      ]
    },
    "cors": {
      "allow_credential": false,
      "allow_headers": "*",
      "allow_methods": "*",
      "allow_origins": "http://xxx.com",
      "allow_origins_by_regex": [
        "[\".*\\.jilinxiangyun.com\", \".*\\.gov.cn\", \".*://localhost$\",\".*://localhost:.*$\"]"
      ],
      "disable": false,
      "expose_headers": "*",
      "max_age": 5
    },
    "key-auth": {
      "header": "apikey",
      "hide_credentials": false,
      "query": "apikey"
    },
    "limit-count": {
      "allow_degradation": false,
      "count": 5,
      "key": "consumer_name",
      "key_type": "var",
      "policy": "local",
      "rejected_code": 503,
      "rejected_msg": "请求过多",
      "show_limit_quota_header": true,
      "time_window": 1
    },
    "proxy-rewrite": {
      "headers": {
        "add": {
          "skip": "true"
        }
      },
      "scheme": "https"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "10.247.233.143",
        "port": 30020,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}

**Comment by chenghongxi** [comment]
@huacnlee @jaysonsantos @justinmclean @naveensrinivasan

**Comment by chenghongxi** [comment]
help

**Comment by Revolyssup** [comment]
@chenghongxi Can you show the request that was sent which resulted in this error?

**Comment by SparkLee** [comment]
我今天遇到了同样的错误， 我是通过配置 `fallback_sni` 来解决的。
```
apisix
  ssl：
    fallback_sni: "${your sni}"
````

我遭遇这个错误的背景是这样的：

我们的 APP 由于遇到域名劫持的问题，所以使用了阿里云的 HttpDNS，但是因为 HttpDNS 直接使用 IP 而非域名的方式对 APISIX 服务器发起 HTTPS 请求，导致 APISIX 因为获取不到域名信息（SNI标识）而无法匹配相应的 SSL 证书，从而导致请求失败，并且在 APISIX 的 error 日志中记录如下错误：`http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol`。

解决这个问题的思路是：

既然客户端 APP 无法提供 SNI 标识，那就配置一个默认的 SNI，亦即配置一个默认的 SSL 证书即可，配置示例： `apisix.ssl.fallback_sni: "www.baidu.com"` 。

另外为了匹配 HTTPS + IP 的请求，在 APISIX Dashboard 后台配置的 APISIX 路由的 “域名” 需要是 IP，或者干脆留空，亦即匹配所有的请求域名与 IP。

最后，由于我们在 APISIX 后面还有一个 Nginx 的上游服务，由于 Nginx 服务也配置了多个 Server，每个 Server 配置为不同的域名，由于这种 HTTPS + IP 的请求方式，导致 APISIX 无法传递请求域名”给到上游 Nginx 服务，导致 Nginx 也无法区分到底应该用哪个 Server 来提供服务，所以此时还需要配置一个默认的 Nginx Server，比如：
```nginx.conf
server {
    listen 80 default_server;
}
```

参考资料：

1、官方文档：[启用 SSL 证书后，为什么无法通过 HTTPS + IP 访问对应的路由？](https://apisix.apache.org/zh/docs/apisix/FAQ/#%E5%90%AF%E7%94%A8-ssl-%E8%AF%81%E4%B9%A6%E5%90%8E%E4%B8%BA%E4%BB%80%E4%B9%88%E6%97%A0%E6%B3%95%E9%80%9A%E8%BF%87-https--ip-%E8%AE%BF%E9%97%AE%E5%AF%B9%E5%BA%94%E7%9A%84%E8%B7%AF%E7%94%B1)
2、官方 APISIX 配置文件示例：[fallback_sni](https://github.com/apache/apisix/blob/release/3.6/conf/config-default.yaml#L122)

**Comment by rastiehaiev** [comment]
I experienced this once. SNI check failed ~ 4 times out of 10. In my case there were errors in my etcd. Something like "Invalid cluster ID" or something. I restarted etcd and it started working. Don't know what happened to it but maybe it will help in a way.

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
