### ISSUE TITLE
help request: [lua] config_etcd.lua:395: sync_data(): waitdir [/apisix/services] err

### ISSUE THREAD

**Issue by sumeng001** [apache/apisix#10236]
### Description

I see problems with #9336 and #8493.
I'm having the same problem as #9336, but I'm using the http account password method to connect to etcd. here's my configuration
![image](https://github.com/apache/apisix/assets/28882514/4f857839-22ec-4d09-bb6a-797d0b34da30)

He is running for a while and has a problem with connection to etcd timing out, here is my error message
![image](https://github.com/apache/apisix/assets/28882514/ebb49f68-6aa8-4049-95d3-b0a7a053bea6)

I'm not sure if upgrading to 3.2.2 will fix this? Because I've only migrated some of my domains for my production and test environments.
I hope I can get help and experience from everyone.
I will also test myself if this issue still occurs with version 3.2.2

### Environment

- APISIX version (run `apisix version`):/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.2.0
- Operating system (run `uname -a`):Linux xxxxname 4.19.0-4.el7.ucloud.x86_64 #1 SMP Mon Dec 16 08:54:55 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.21.4.2
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"etcd_version":"3.5.0","version":"3.2.0"}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
cc: @kingluo

**Comment by kingluo** [comment]
@sumeng001 Please try the latest version. The bugfix is merged there.

**Comment by sumeng001** [comment]
> @sumeng001请尝试最新版本。错误修复已合并到那里。

extremely grateful
