### ISSUE TITLE
help request: slack invite

### ISSUE THREAD

**Issue by rauanmayemir** [apache/apisix#10231]
### Description

May I get an invite that could allow joining without apache.org email?

### Environment

*

**Comment by Jijingling** [comment]
same asking here thanks for someone help!

**Comment by juzhiyuan** [comment]
Hi @rauanmayemir and @Jijingling, please use this one: https://join.slack.com/t/the-asf/shared_invite/zt-233mgv879-d24QCEXACntQJmQtuKlNug

This will expire in 21 days.
