### ISSUE TITLE
help request: How do I configure LDAP with password?

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10235]
### Description

My  ldap config, but apisix ladp configuration  is  only base_dn  ldap_uri . 

How to apisix  configure according to my ldap？

![4080d9f1ccdccf6893aa55c7d8148df](https://github.com/apache/apisix/assets/44867235/8d9116f7-2f9f-4943-b0c5-9e4464373cc1)

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):3.10.0-1160.90.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.7
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by qyk1995** [comment]
@Revolyssup  How to write  ldap  config password  in   the apisix  ldap   plugins?

**Comment by qyk1995** [comment]
@Revolyssup   I see this is https://github.com/apache/apisix/blob/master/apisix/plugins/ldap-auth.lua, discover  Authorization  parameter. but  I  don't know how write Authorization  in apisix ldap plugins.

**Comment by Revolyssup** [comment]
@qyk1995 You can follow this guide and ask any specific doubt you may have as to what to fill in what attribute https://apisix.apache.org/docs/apisix/plugins/ldap-auth/
