### ISSUE TITLE
help request: updating apisix.yaml in a standalone mode deployed on k8s

### ISSUE THREAD

**Issue by ghost** [apache/apisix#10244]
### Description

so there are multiple ways I have thought of implementing this:
1. Since, apisix/config folder has multiple files, while not affecting the other files, one way is to mount configmap as subpath, but it would require a third party side car container to listen to any configmap update
2. https://github.com/apache/apisix-docker/blob/328fc9de1591d175af7a622eb474c03603e7ed6a/example/docker-compose-standalone.yml#L27
Saw this environment variable in an example docker compose file, if the same way the image is deployed in k8s, do you think mounting configmap as directory won't affect its functioning (for upstream servers, I only need to keep editing apisix.yaml through configmap), here the updates from the configmap would automatically reflect in the file and then apisix will pick up the updates

3. Any way if you can suggest? One I read was about creating symlink between two files in a container, can this work in k8s?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by exllamafan** [comment]
Also, could anyone share the updated slack link please?

**Comment by shreemaan-abhishek** [comment]
https://join.slack.com/t/the-asf/shared_invite/zt-23oo16n1x-v0ZoiIe4RGFhZmp80PNGKA

**Comment by Revolyssup** [comment]
@exllamafan Just to confirm few things, how did you deploy apisix on k8s? Did you use the official helm chart?

**Comment by Revolyssup** [comment]
@exllamafan What is the problem in modifying the `apisix.yaml` configmap which is deployed in standalone mode in k8s? You can change configuration by modifying that. That configmap is already mounted in apisix container.

**Comment by Revolyssup** [comment]
https://github.com/apache/apisix-helm-chart/blob/master/docs/en/latest/FAQ.md#how-to-install-apache-apisix-running-in-standalone-mode

**Comment by Revolyssup** [comment]
@exllamafan that environment variable is only for docker based installations and used in the startup script ,not in code.

**Comment by exllamafan** [comment]
> @exllamafan that environment variable is only for docker based installations and used in the startup script ,not in code.

can the same docker container be run in the pod? Because if not, configmap would have to be subpath mounted to apisix.yaml and in that case, no updates in the configmap will be propagated automatically

**Comment by monkeyDluffy6017** [comment]
ping @Revolyssup

**Comment by Revolyssup** [comment]
@ghost The method of installation for standalone was updated to use helm chart. Please take a look https://github.com/apache/apisix-helm-chart/blob/master/docs/en/latest/FAQ.md#how-to-install-apache-apisix-running-in-standalone-mode
And here, mountPath is used instead of subPath so you can use configmap with it.
Please reopen the issue if needed
