### ISSUE TITLE
feature: supports more upstream parameters in `upstream` object

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1024]
discuss in dev mail: https://lists.apache.org/thread.html/ec86410d90194d1f74adfecddd6f4693df5b8753d5adb8d8a3465cc6%40%3Cdev.apisix.apache.org%3E

|Name    |Optional|Description|
|-------         |-----|------|
|type            |required|`roundrobin` supports the weight of the load, `chash` consistency hash, pick one of them.|
|uri     |optional|The uri to be used in requests to the upstream server.|
|host    |optional|The host of the upstream server.|
|protocol|optional|The protocol used to communicate with the upstream. It can be one of `http` or `https`. Defaults to `http`.|
|port    |optional|The upstream server port. Defaults to 80.|
|connect_timeout|optional|The timeout in milliseconds for establishing a connection to the upstream server. Defaults to `60000`.|
|write_timeout|optional|The timeout in milliseconds between two successive write operations for transmitting a request to the upstream server. Defaults to `60000`.|
|read_timeout|optional|The timeout in milliseconds between two successive read operations for transmitting a request to the upstream server. Defaults to `60000`.|

**Comment by Miss-you** [comment]
Hi, I want to ask if this feature is currently under development or has been merged into the trunk branch,  "Extract the host from the proxy-rewrite plugin into the upstream object” .

In addition, the routes object also has a host configuration, but in some specific scenarios, there will be multiple domain names corresponding to this route or a group of routes. I think it is more appropriate for the host to be placed in the service object? Or is there any other better way to use routes?

**Comment by spacewander** [comment]
Part of them are implemented in different name.
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
