### ISSUE TITLE
bug: APISIX_STAND_ALONE environment doesn't work as expected

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#10249]
### Current Behavior

After following the document's guide to run Standalone mode, it's running successfully but I can't access the gateway, and the `config.yaml` looks incorrect.

### Steps to Reproduce

1. Follow https://hub.docker.com/r/apache/apisix README's "How to run APISIX in stand-alone mode" section
2. Run the following command successfully:

```sh
docker run -d --name apache-apisix \
  -p 9080:9080 \
  -e APISIX_STAND_ALONE=true \
  apache/apisix
```

<img width="1205" alt="image" src="https://github.com/apache/apisix/assets/2106987/15be1a33-88ac-495d-818c-6d24c23ab596">

3. Access endpoint failed

<img width="411" alt="image" src="https://github.com/apache/apisix/assets/2106987/2f48aa67-f5f9-49d6-a170-11a8b7f32370">

4. After injecting the container, I noticed that the `config.yaml` is using `etcd` as a configuration store.

<img width="743" alt="image" src="https://github.com/apache/apisix/assets/2106987/c901941c-0678-4f14-bfbb-75b51387306f">
<img width="1053" alt="image" src="https://github.com/apache/apisix/assets/2106987/4cee80cc-f501-4540-80db-3a4c7b98c3c9">

### Environment

- APISIX version (run `apisix version`): 3.5.0
- Operating system (run `uname -a`): Linux e6a1b0d71e58 4.4.302+ #64570 SMP Thu Jul 20 00:04:37 CST 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): N/A
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: N/A
- Plugin runner version, for issues related to plugin runners: N/A
- LuaRocks version, for installation issues (run `luarocks --version`): N/A

**Comment by juzhiyuan** [comment]
I just used `inspect` to check the container, I can confirm I'm using the correct env.

<img width="1210" alt="image" src="https://github.com/apache/apisix/assets/2106987/93c13352-a46d-457a-8333-65cd99dc80f1">

**Comment by jiangfucheng** [comment]
It's a bug of `apisix-docker`, I will fix it today.

**Comment by jiangfucheng** [comment]
@juzhiyuan  Hi, I try to reproduce this bug in my local environment. I found it will download `yq` when we run apisix docker, It will take a little time. The `config.yaml` will be correct after `docker-entrypoint.sh` running is completed. Maybe you need to test it again after `docker run` init success.



https://github.com/apache/apisix-docker/blob/328fc9de1591d175af7a622eb474c03603e7ed6a/debian/docker-entrypoint.sh#L37-L40

**Comment by kamly** [comment]
It may be related to this change https://github.com/apache/apisix-docker/pull/494

**Comment by Revolyssup** [comment]
Conclusion: 
As @jiangfucheng noted, the actual reason for this issue is that startup might take a little longer because `yq` tool is downloaded in the startup script. This is done at startup and not included in the image build to avoid adding tools like yq in the image when it's only needed for some specific thing at startup. 

If this issue persists for other users where startup time is large due to network issues then we can move the download of the utility inside the image build.

**Comment by juzhiyuan** [comment]
> If this issue persists for other users where startup time is large due to network issues then we can move the download of the utility inside the image build.

Thanks for pointing out the real reason.

For new users: They need to learn the logic behind installation. So I would suggest to keep improving this to make it ready after the container started.

**Comment by Revolyssup** [comment]
@juzhiyuan So should we close this issue? Or should the issue be changed to something like "improve startup time by removing download process in startup script" to keep track?

**Comment by monkeyDluffy6017** [comment]
@Revolyssup Can we download the `yq` tool in the dockfile?

**Comment by Revolyssup** [comment]
> @Revolyssup Can we download the `yq` tool in the dockfile?

Yes that is what I had done initially. But @soulbird had suggested that having an Open source tool in the image can be a security issue so I had moved it to startup script informing that this might increase startup time. What do you suggest?

**Comment by kamly** [comment]
how about ?

```shell
sed -i 's/\(role: \).*/\1data_plane/' config.yaml
sed -i 's/\(config_provider: \).*/\1yaml/' config.yaml
```

**Comment by monkeyDluffy6017** [comment]
@kamly LGTM, could you have a try?

**Comment by Revolyssup** [comment]
@kamly `yq` is used when config file is already present. What is the guarantee that `role` and `config_provider` fields are present. Maybe I am being overly cautious but yq will add those fields if they are not present and using yaml parsing tool is less hacky than using sed to parse and manipulate yaml. But if we are sure that there would be no edge cases and the yaml will always contain these fields then I guess we can go ahead using `sed`

// @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
@Revolyssup the `yq` and `sed` both need to find the `role` and `config_provider` fields, i don't see the difference

**Comment by Revolyssup** [comment]
if `role` and `config_provider` is not present in the file then sed won't add it. yq will add it.  @monkeyDluffy6017

**Comment by jiangfucheng** [comment]
> how about ?
> 
> ```shell
> sed -i 's/\(role: \).*/\1data_plane/' config.yaml
> sed -i 's/\(config_provider: \).*/\1yaml/' config.yaml
> ```

We need set the `role_data_plane.config_provider: etcd`, the `config_provider` is belong to `role_traditional`, just replace `config_provider: etcd` to `config_provider: yaml` is not enough.

**Comment by jiangfucheng** [comment]
I agree with @Revolyssup, just using string replacement may not meet the situation of subsequent config content changes, using `yq` is relatively more flexible.

**Comment by monkeyDluffy6017** [comment]
@jiangfucheng @Revolyssup We need to fix the problem, download the `yq` tool and use it which is not accceptable now, we don't need to think that far ahead, as the name of this configuration item `config_provider` and `role` can be changed too.

**Comment by Revolyssup** [comment]
@kamly Would you like to create a PR replacing usage of yq with sed?

**Comment by kamly** [comment]
yes, of course, wait, wait ~

**Comment by Revolyssup** [comment]
@kamly since this is an urgent issue, if you can't make a PR by today you can hand it over to me

**Comment by kamly** [comment]
I make a PR https://github.com/apache/apisix-docker/pull/508 , please have a look ~

**Comment by Revolyssup** [comment]
PR merged https://github.com/apache/apisix-docker/pull/508
