### ISSUE TITLE
bug: AUTH0 oidc integration for bearer_only=true requires introspection endpoint

### ISSUE THREAD

**Issue by Radu-Iuonac** [apache/apisix#10245]
### Current Behavior

Hi,
I am trying to integrate APISIX with Auth0 via openid-connect plugin following the steps described here:
https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-auth0
I have configured an API and Application in Auth0, I have configured a route via CURL to apisix admin endpoint and tested the bearer_only=false method which works as intended. (login in auth0, and redirect back to my service)

When I switch bearer_only=true and try to run CURL with authorization header obtained from Auth0_DOMAIN/oauth/token i get the following error. I have tried multiple configurations, I have searched the issues here on github trying to get some help but it just doesn't work.

<img width="830" alt="Screenshot 2023-09-21 at 15 49 52" src="https://github.com/apache/apisix/assets/20111005/ba21cf96-65bd-4d51-a902-c111395d3025">

From what I searched online AUTH0 does not provide an instrospection endpoint https://community.auth0.com/t/introspection-endpoint-for-opaque-tokens-or-more-flexible-rules-to-get-clear-jwt-access-token/63866

### Steps to Reproduce

1. Run APISIX docker image and configure AUTH0 openid-connect plugin
2. create a route using admin api
3. update route by setting bearer-only=true
4. obtain a token from /oauth/token
5. CURL service with -H "Authorization Bearer $ACCESS_TOKEN"

### Environment

- APISIX version (run `apisix version`): 3.5.0
- Operating system (run `uname -a`): docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Boburmirzo** [comment]
@Radu-Iuonac Thank you for explaining the steps to reproduce well!

This doc has been tested and updated recently, there might be a few issues. Please, add "use_jwks": true value to your route plugin.

Could you try with this configuration?

curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "auth-with-oidc",
  "uri":"/anything/*",
  "plugins": {
    "openid-connect": {
      "client_id": "'"$AUTH0_CLIENT_ID"'",
      "client_secret": "'"$AUTH0_CLIENT_SECRET"'",
      "discovery": "https://'"$AUTH0_DOMAIN"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "redirect_uri": "http://localhost:9080/anything/callback",
      "bearer_only": true,
      "use_jwks": true
    }
  },
  "upstream":{
    "type":"roundrobin",
    "nodes":{
      "httpbin.org:80":1
    }
  }
}'

**Comment by Radu-Iuonac** [comment]
@Boburmirzo No no, thank you my friend :).
It works like a charm. Thank you very much!

I think somebody needs to update the tutorial here https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-auth0.

Have a good day!

**Comment by Boburmirzo** [comment]
@Radu-Iuonac Yeah, we will update the tutorial accordingly.

We can close the GitHub issue now.
