### ISSUE TITLE
bug: Using custom ETCD cluster, https access error

### ISSUE THREAD

**Issue by 5279314** [apache/apisix#10242]
### Current Behavior

config etcd http tls enabled。
```
		  ssl:
		    enable: true
		    listen:
		      - port: 9443
		        enable_http2: true
		    ssl_trusted_certificate: /usr/local/apisix/ssl/ca.pem
		deployment:
		  role: traditional
		  role_traditional:
		    config_provider: etcd
		  etcd:
		    host:                          # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
		      - \"https://10.1.1.100:2379\"
		      - \"https://10.1.1.120:2379\"
		      - \"https://10.1.1.130:2379\"
		    prefix: \"/apisix\"    # configuration prefix in etcd
		    timeout: 30    # 30 seconds
		    tls:
		      cert: /etcd-ssl/tls.crt
		      key: /etcd-ssl/tls.key
```
curl 
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
> {            
>   "id": "getting-started-ip",
>   "uri": "/ip",
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     }
>   }
> }'
HTTP/1.1 503 Service Temporarily Unavailable
Date: Thu, 21 Sep 2023 04:41:05 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/3.5.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
X-API-VERSION: v3

{"error_msg":"invalid response code: 503"}
```
The container can access the ETCD cluster normally。
![image](https://github.com/apache/apisix/assets/27267683/c7c5b8e2-8428-4379-bf62-8d4eb7a9fdf1)

### Expected Behavior

```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
> {            
>   "id": "getting-started-ip",
>   "uri": "/ip",
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     }
>   }
> }'
OK
```

### Error Logs

pod logs
[logs-from-apisix-in-apisix-f98dcb7d7-rls6h.log](https://github.com/apache/apisix/files/12680285/logs-from-apisix-in-apisix-f98dcb7d7-rls6h.log)

### Steps to Reproduce

Kubernetes yaml
[apisix.txt](https://github.com/apache/apisix/files/12680301/apisix.txt)

etcd config
```
cat /opt/etcd/cfg/etcd.conf 
#[Member]
ETCD_NAME="etcd-2"
ETCD_DATA_DIR="/var/lib/etcd/default.etcd"
ETCD_LISTEN_PEER_URLS="https://10.1.1.130:2380"
ETCD_LISTEN_CLIENT_URLS="https://10.1.1.130:2379,http://127.0.0.1:2379"

#[Clustering]
ETCD_INITIAL_ADVERTISE_PEER_URLS="https://10.1.1.130:2380"
ETCD_ADVERTISE_CLIENT_URLS="https://10.1.1.130:2379,http://127.0.0.1:2379"
ETCD_INITIAL_CLUSTER="etcd-1=https://10.1.1.100:2380,etcd-2=https://10.1.1.130:2380,etcd-3=https://10.1.1.120:2380"
ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster"
ETCD_INITIAL_CLUSTER_STATE="new"
```

### Environment

- APISIX version (run `apisix version`): 3.5.0
- Operating system (run `uname -a`): Linux apisix-f98dcb7d7-vkcnm 3.10.0-1160.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty -V
nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"version":"3.5.0","etcd_version":"unknown","boot_time":1695270808,"hostname":"apisix-f98dcb7d7-vkcnm","id":"08a48b78-1a1f-460f-8f38-7b888d420316"}

**Comment by Revolyssup** [comment]
@5279314 Can you add `sni` field inside etcd.tls with the value for which cert was generated?

**Comment by 5279314** [comment]
Can version 3. x only be accessed through Sni? I can use it this way on 2.15.3

**Comment by 5279314** [comment]
> Can version 3. x only be accessed through Sni? I can use it this way on 2.15.3


Can version 3. x only be accessed through Sni? I can use it this way on 2.15.3

**Comment by Revolyssup** [comment]
@5279314 It's weird that you dont get an error in 2.15.3. If you have specified an IP in host without an SNI, you should be getting `certificate host mismatch` in version 2.15.3 as well.  
https://github.com/apache/apisix/blob/f832ea2502ce2696b0e7390a1572ab7000fef344/t/cli/test_etcd_mtls.sh#L151

**Comment by 5279314** [comment]
> @5279314 It's weird that you dont get an error in 2.15.3. If you have specified an IP in host without an SNI, you should be getting `certificate host mismatch` in version 2.15.3 as well.
> 
> https://github.com/apache/apisix/blob/f832ea2502ce2696b0e7390a1572ab7000fef344/t/cli/test_etcd_mtls.sh#L151

There were no errors when using this method in version 2.15.3, and I tested SNI in version 3.5.0 without any errors.

**Comment by Revolyssup** [comment]
@5279314 So just to confirm - You get no errors in 2.15.3 without passing SNI. And in 3.5.0, you get no error after passing SNI?

**Comment by shreemaan-abhishek** [comment]
ping @5279314

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
