### ISSUE TITLE
request help: How to publish grayscale

### ISSUE THREAD

**Issue by jiezaizone** [apache/apisix#1025]
### Issue description
https://github.com/apache/incubator-apisix/blob/master/FAQ_CN.md#%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87apisix%E6%94%AF%E6%8C%81ab%E6%B5%8B%E8%AF%95
![image](https://user-images.githubusercontent.com/28976666/71800263-8f8d9300-3092-11ea-9a87-46585fcba188.png)

I have read this document and understand that the same domain name is configured with two routes and then filtered according to vars?
In the practical application scenario, the grayscale list is configured to be stored in redis by other means. Through the user name of access to determine whether in the grayscale list, exists, access to grayscale.
According to the documentation, I should configure two routes to access the default environment system and the grayscale environment system, and choose the access path through vars. Here I need to connect redis, how should I configure it? Is there a demo?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
The APISIX used `etcd` to store all of the route data. 

Why do you have to use Redis?

**Comment by jiezaizone** [comment]
> The APISIX used `etcd` to store all of the route data.
> 
> Why do you have to use Redis?

I could use an etcd instead, so get the grayscale list and do the logic that says filter_func, right?

**Comment by membphis** [comment]
Yes, that is a good way in APISIX .

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
