### ISSUE TITLE
help request: Getting error 503 Service temporarily unavailable while Validating for Request-Validation plugin 

### ISSUE THREAD

**Issue by deekayzain** [apache/apisix#10253]
### Description

Getting error 503 Service temporarily unavailable while Validating for Request-Validation plugin 

Please help/suggest something.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, please feel free to reopen it
