### ISSUE TITLE
help request: about radixtree_uri_with_parameter

### ISSUE THREAD

**Issue by guankai** [apache/apisix#10257]
### Description

I used radixtree_uri_with_parameter to match parameters on the path, such as /path/:param. Currently, I want to use this param in the uri in proxy-rewrite. How should I handle it?

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`): debian
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wklken** [comment]
- "uri": "/api/httpbin/header/status/:codes"
- proxy-rewrite  "uri": "/status/${codes}"

the `proxy-rewrite` will call `core.utils.resolve_var`

**Comment by guankai** [comment]
> * "uri": "/api/httpbin/header/status/:codes"
> * proxy-rewrite  "uri": "/status/${codes}"
> 
> the `proxy-rewrite` will call `core.utils.resolve_var`

it is not works, the route config
<img width="494" alt="image" src="https://github.com/apache/apisix/assets/2645968/70a830f7-3700-4d7d-92c0-7521a2b4959d">
and the log as
<img width="769" alt="image" src="https://github.com/apache/apisix/assets/2645968/fa0dcfbe-a454-41ab-8ff6-9f2582257b59">

the apisix can not identify the ${param}

**Comment by wklken** [comment]
@guankai sorry for the wrong answer, the settings is our custom proxy-rewrite support `core.utils.resolve_var(conf.uri, ctx.curr_req_matched)` from the ctx.curr_req_matched;

**Comment by guankai** [comment]
> @guankai sorry for the wrong answer, the settings is our custom proxy-rewrite support `core.utils.resolve_var(conf.uri, ctx.curr_req_matched)` from the ctx.curr_req_matched;

I don’t quite understand what your answer means. Does it mean regular matching through regex_uri? Can you give an example of proxy-rewrite plug-in configuration? If it is configured through regex_uri, I have found a way to do this. Is there an example of configuring through uri?

**Comment by wklken** [comment]
You can find the example in the test case: 

https://github.com/apache/apisix/blob/ddac444421dd20b45a78a232f558d364b6fb3fdd/t/plugin/proxy-rewrite.t#L562-L590

**Comment by guankai** [comment]
> You can find the example in the test case:
> 
> https://github.com/apache/apisix/blob/ddac444421dd20b45a78a232f558d364b6fb3fdd/t/plugin/proxy-rewrite.t#L562-L590

got it,thanks

**Comment by guankai** [comment]
@wklken 
Are you considering using this configuration in later versions?
`"uri": "/api/httpbin/header/status/:codes"
proxy-rewrite "uri": "/status/${codes}"`

**Comment by wklken** [comment]
> @wklken Are you considering using this configuration in later versions? `"uri": "/api/httpbin/header/status/:codes" proxy-rewrite "uri": "/status/${codes}"`

we have already made a plugin to support that, it's more simpler and efficient, the original code is from `proxy-rewrite`; it's not compatible with the `core.utils.resolve_var` with `ngx.var`

https://github.com/TencentBlueKing/blueking-apigateway-apisix/blob/f3544e39ed6d93d17156b038733ee61cf21ded65/src/apisix/plugins/bk-proxy-rewrite.lua#L217-L234

**Comment by boekkooi-lengoo** [comment]
Another options is to patch https://github.com/apache/apisix/blob/3.7.0/apisix/core/ctx.lua#L238 and add with sometime like:
```LUA
elseif core_str.has_prefix(key, "uri_arg_") then
if t._ctx.curr_req_matched then\
    val = t._ctx.curr_req_matched[(sub_str(key, 9))]\
end
```

I just added the following to my dockerfile.
```
RUN sed -i \
    -e '238i \
    elseif core_str.has_prefix(key, "uri_arg_") then\
      if t._ctx.curr_req_matched then\
          val = t._ctx.curr_req_matched[(sub_str(key, 9))]\
      end' \
    /usr/local/apisix/apisix/core/ctx.lua
```

Now you can use `$uri_arg_codes` to access the var in `proxy-rewrite`.

**Comment by monkeyDluffy6017** [comment]
considered resolved
