### ISSUE TITLE
help request: why i send post request but the body i can`t get it?

### ISSUE THREAD

**Issue by jack01234** [apache/apisix#10259]
### Description

1、curl http://localhost:8090/test123   -X POST   -H "Content-Type: application/json"   --data-raw '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
2、the file log is: {"request":{"headers":{"host":"172.20.192.17:31684","content-type":"application/json","accept":"*/*","user-agent":"curl/7.74.0","content-length":"63"},"size":206,"method":"POST","querystring":{},"uri":"/test123","url":"http://172.20.192.17:9080/test123"},"upstream_latency":1,"apisix_latency":0.99985504150391,"client_ip":"172.20.192.17","route_id":"1","latency":1.9998550415039,"server":{"hostname":"apisix-6b7d85c97-4qhvx","version":"3.2.2"},"upstream":"172.20.192.198:8545","start_time":1695711591640,"service_id":"","response":{"headers":{"date":"Tue, 26 Sep 2023 06:59:51 GMT","connection":"close","server":"APISIX/3.2.2","content-length":"0"},"status":404,"size":128,"body":""}} 
the querystring is null but i appoint the --data-raw please tell how can i resolve this？thank you very much

### Environment

- APISIX version is 3.2.2
- etcd version is 3.1
- APISIX Dashboard version is 3.0

**Comment by Revolyssup** [comment]
@jack01234 Are you trying to include response body while using the file logger? Make sure to set `include_resp_body` as `true` https://apisix.apache.org/docs/apisix/plugins/file-logger/#attributes

**Comment by Revolyssup** [comment]
@jack01234 Did the above solution work for you?

**Comment by monkeyDluffy6017** [comment]
considered resolved
