### ISSUE TITLE
bug: wrong json schema configuration

### ISSUE THREAD

**Issue by wzy0618** [apache/apisix#10260]
### Current Behavior

apisix/schema_def.lua:414
                client_cert_id = {
                    ["not"] = {required = {"client_client", "client_key"}}
                }
"client_client" has never appeared

### Steps to Reproduce

apisix/schema_def.lua:414
                client_cert_id = {
                    ["not"] = {required = {"client_client", "client_key"}}
                }
maybe "client_client" here should be "client_cert"

### Environment

- APISIX version (run `apisix version`):2.15(The latest version also has the same issue)
- Operating system (run `uname -a`):Linux 4.14.105-1-tlinux3-0022 #1 SMP Wed Sep 29 11:01:45 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):3.8.0

**Comment by Revolyssup** [comment]
@wzy0618 Yes it looks like a typo. Will you create a fix for this?

**Comment by wzy0618** [comment]
> @wzy0618 Yes it looks like a typo. Will you create a fix for this?

Just created a PR. By the way, delete the redundant two lines of configuration above.
