### ISSUE TITLE
Proposal: Remove centos7-based APISIX image

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#10266]
### Description

Proposed to remove APISIX docker image release based on centos 7

Mainly based on the following reasons:

centos has been upstreamed and is no longer maintained.
The centos 7 official image in dockerhub can no longer pass the security scan of dockerhub, which is unacceptable in the eyes of an enterprise customer.
APISIX provides opportunities for the release of redhat ubi image: docker pull apache/apisix:3.5.0-redhat
But this does not mean to completely abandon centos7, it just wants to leave the security issues of the operating system to the users themselves.

APISIX will still provide rpm release based on centos7.
APISIx currently still provides compatibility testing for centos7, which is guaranteed by the CI of apache/APISIX.

copy from https://github.com/apache/apisix-docker/issues/507

**Comment by Sn0rt** [comment]
@shreemaan-abhishek if you are interesting in this feature , pls send a email to email list . 
this is a break change!

**Comment by shreemaan-abhishek** [comment]
@Sn0rt, I got it.

**Comment by shreemaan-abhishek** [comment]
fixed by https://github.com/apache/apisix-docker/pull/512
