### ISSUE TITLE
help request: Is the radix tree rebuilt every time any route is updated?

### ISSUE THREAD

**Issue by wklken** [apache/apisix#10268]
### Description

On my test environment, we have 4000 routes(about 50000 on production)

And, call `PUT /admin/routes/1`, there will get a high cpu usage, change the log level to `info`

```
2023/09/27 06:40:00 [info] 37#37: *2730924 [lua] route.lua:73: create_radixtree_uri_router(): insert uri route: {}

.....4000+ lines insert uri route:

2023/09/27 06:40:00 [info] 37#37: *2730924 [lua] route.lua:96: create_radixtree_uri_router(): route items: []

2023/09/27 06:40:00 [info] 37#37: *2730924 [lua] radixtree.lua:355: pre_insert_route(): path:

.....4000+ lines pre_insert_route
```

and call `PUT /admin/routes/1` again(nothing changed), will call `create_radixtree_uri_router` again and get a high cpu usage.

----

from the code

https://github.com/apache/apisix/blob/f81a386da046bc063d6e3b442cde4f5702783b6f/apisix/http/router/radixtree_uri_with_parameter.lua#L21-L41

it seems that if any route update, the cached radix tree will be rebuilt? 

----

use wrk to see the benchmark result

<img width="957" alt="image" src="https://github.com/apache/apisix/assets/2002216/2754f3e8-1194-45f4-a652-3cf118473e6b">

The latency is excessively high, which is unacceptable.

----

the high cup usage and high latency, will cause some plugins timeout, like `limit-count` redis cli new and eval script

so, I have some questions and look forward to your response. Thank you!

1. if any route update, the cached radix tree will been rebuilt? it seems rebuilt every 5 seconds? 
2. even the route has no changes on uri and priority? 
3. the rebuilding is full, not incremental?
4. we have more than 40,000 routes in production, any of which could be updated at any time. Do you have any advice on how to control the frequency of these updates? For example, should we do bulk updates within a short time, or should we spread the updates over a longer period?
5. is there any chance we could rebuild the tree in the background and then replace the currently used tree? (This mechanism was used in our older version of the Golang API gateway)

### Environment

- APISIX version (run `apisix version`): 3.2.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wklken** [comment]
I read the source codes and it seems the 5 seconds is the timeout of etcd http client

according the doc [watchdir](https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md#watchdir)

when new http cli, the timeout is nil

```
2023/09/28 02:22:06 [error] 113216#113216: *4615262 [lua] config_etcd.lua:164: http_waitdir(): the timeout is: nil, context: ngx.timer
```

so the default values is 5s

https://github.com/api7/lua-resty-etcd/blob/ba32ec2b8591af363e09c1493594fc2f28a63278/lib/resty/etcd.lua#L26-L33

------

so even we keep updating the routes, the etcd http cli will timeout every 5 seconds, and rebuild the tree.

**Comment by wklken** [comment]
After read the source code and do a benchmark, It seems we can't fix it by change the `timeout` or `timer`

keep calling `PUT /routes/1` to update the route, then
- if there are no requests coming, the radixtree is rebuilt every  10s
- if there are requests coming, the radixtree is rebuilt every 1s(or 0.5s)

the router will check the `conf_version` of routes, and the etcd_config will change it during watching the changes.

on the production, requests keep coming in continuously. so the performance is poor.

-------

maybe we can change the condition here, to only rebuild the tree with a duration checking? 

or maybe the best way is do it `background`, and replace the cached object!


https://github.com/apache/apisix/blob/2650551ff53afcc61dacfbe77ec26bf89a41d16d/apisix/http/router/radixtree_uri_with_parameter.lua#L25-L48


Could someone give some advice here?

**Comment by monkeyDluffy6017** [comment]
We already have a pr to improve this: https://github.com/apache/apisix/pull/9692
Would you like to contribute?

**Comment by wklken** [comment]
Currently we use a patch to fix the problem: https://github.com/TencentBlueKing/blueking-apigateway-apisix/blob/master/src/build/patches/004_radixtree_uri_with_parameter_rebuild_with_interval.patch

-----

will check after #9692 been merged
