### ISSUE TITLE
help request:  how to config apisix to connect to  the etcd cluster via https?  many thanks 

### ISSUE THREAD

**Issue by szhengli** [apache/apisix#10263]
### Description

as title said, how to config apisix to connect to  etcd cluster via https. 

  etcd:
    host:
      - "http://foo:2379"
how to config https. need a place to specify the client key & cert and the ca cert of the etcd server

### Environment

apache/apisix:3.4.1-centos

**Comment by wklken** [comment]
https://github.com/apache/apisix/blob/ddac444421dd20b45a78a232f558d364b6fb3fdd/conf/config-default.yaml#L660-L677

use `deployment.etcd.tls`

**Comment by Revolyssup** [comment]
@szhengli Feel free to close the issue if the above comment answers your question.

**Comment by szhengli** [comment]
> https://github.com/apache/apisix/blob/ddac444421dd20b45a78a232f558d364b6fb3fdd/conf/config-default.yaml#L660-L677
> 
> use `deployment.etcd.tls`

But, how to set the CA certificate for apisix to connect etcd cluster? 

the below are the parameters required to connect to the etcd cluster
--cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt  --cert /var/lib/rancher/rke2/server/tls/etcd/client.crt --key /var/lib/rancher/rke2/server/tls/etcd/client.key 

if add cacert after key , apisix will fail to start, and suggest to set  ssl_trusted_certificate ,   but if set it, it still fails to connect the etcd cluster

**Comment by szhengli** [comment]
> https://github.com/apache/apisix/blob/ddac444421dd20b45a78a232f558d364b6fb3fdd/conf/config-default.yaml#L660-L677
> 
> use `deployment.etcd.tls`

But, how to set the CA certificate for apisix to connect etcd cluster?

the below are the parameters required to connect to the etcd cluster
--cacert /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert /var/lib/rancher/rke2/server/tls/etcd/client.crt --key /var/lib/rancher/rke2/server/tls/etcd/client.key

if add cacert after key , apisix will fail to start, and suggest to set ssl_trusted_certificate , but if set it, it still fails to connect the etcd cluster.

**Comment by szhengli** [comment]
verify: true  .  need to be set to false, to disable to the authentication to server's certificate.

**Comment by szhengli** [comment]
fixed
