### ISSUE TITLE
help request:  problem with radixtree_uri_with_parameter

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10261]
### Description

Hello. I tried to use path parameters by adding _radixtree_uri_with_parameter_ into my config.yaml

```
apisix:
  router:
    http: radixtree_uri_with_parameter
```

I create my route like this:

```
curl "http://127.0.0.1:9180/apisix/admin/routes/4" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "my.example.com",
  "uri": "/api/service/:myId/transaction",
  "plugins": {
    "basic-auth": {
      "disable": false
    }
  },
  "upstream": {
    "type": "roundrobin",
	"scheme": "http",
    "nodes": {
      "my.example.com": 1
    }
  }
}'
```

But for some reason apisix just do nothing when I send request and after some time returns **504 Gateway Time-out**.

Any other routes without path parameters are working fine.

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Red Hat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@PlasticJonbenetDoll Can you share some relevant error logs?

**Comment by Revolyssup** [comment]
For similar configuration, I can confirm that this works for me. More information would be needed. Does the request reach upstream? If not and if 504 is given by APISIX then there has to be some error logs.

**Comment by PlasticJonbenetDoll** [comment]
Where can I see apisix logs?

**Comment by Revolyssup** [comment]
@PlasticJonbenetDoll look at your config.yaml and see the value of `nginx_config.error_log`

**Comment by PlasticJonbenetDoll** [comment]
After I reinstalled apisix the problem was solved.
