### ISSUE TITLE
help request: how can i customize my error page for status code like 400,500

### ISSUE THREAD

**Issue by darkSheep404** [apache/apisix#10271]
### Description

For example,how to change this error page~
![image](https://github.com/apache/apisix/assets/49020899/fa9f3079-d341-483b-9c24-13323faa9913)

And is there a way to configure the same error page for all errors ?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
You can use response rewrite plugin to override the response body with your custom HTML and use `vars` field to provide nginx variable expression to check for a particular status code `$status`. https://apisix.apache.org/docs/apisix/plugins/response-rewrite/

**Comment by qihaiyan** [comment]
Another way is to change error_handling.lua

**Comment by Revolyssup** [comment]
@darkSheep404 You can reopen the issue if you have further queries
