### ISSUE TITLE
help request: Apisix retrying upstream with retry count set to 0

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#10272]
### Description

Why is the retry count set to 0 in the backend upstream, and Apisix still tries 3 times for timeout requests (a total of 4 times, the situation is that the upstream is also an nginx, and the nginx timeout time is relatively short. It first returned 504, and then Apisix seems to have sent 3 more requests)

### Environment

- APISIX version (run `apisix version`):  2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@StretchV Can you paste the apisix configuration you're using?
