### ISSUE TITLE
help request: enable_websocket invalid configuration

### ISSUE THREAD

**Issue by olddriver4** [apache/apisix#10273]
### Description

* config: 
```
$ curl http://127.0.0.1:9180/apisix/admin/routes/f9f06934 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

{"value":{"host":"api-testnet.xxx.link","labels":{"managed-by":"apisix-ingress-controller"},"status":1,"update_time":1695812997,"name":"ing_app-spot_spot-defi_57c53bcd","id":"f9f06934","create_time":1695800048,"uri":"/spot-defi/ws/*","desc":"Created by apisix-ingress-controller, DO NOT modify it manually","upstream_id":"53d1b804","enable_websocket":true},"createdIndex":22004,"key":"/apisix/routes/f9f06934","modifiedIndex":22143}
```

* websocket access: 
```
$ wscat -c ws://api-testnet.xxx.link/spot-defi/ws/

error: Unexpected server response: 400
```

* backend error: 
`time="2023-09-27T10:37:22.442Z" level=info msg="upgrade err: websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header\n"`

I get the same error when opening and closing websocket. The websocket does not take effect. How should I solve it?

### Environment

- APISIX version (run `3.4.0`)
- K8S version (run `1.25.0`)

**Comment by olddriver4** [comment]
aws clb no suuport websocket !

**Comment by olddriver4** [comment]
Can you help me?

`NB： I use aws clb (http: 80 & https: 443) proxy apisix service`

**Comment by Revolyssup** [comment]
@olddriver4 Do you see this anywhere in the info logs `enabled websocket for route:`

**Comment by olddriver4** [comment]
<img width="1241" alt="image" src="https://github.com/apache/apisix/assets/28889568/133e5c4b-b5e3-4f3c-af6d-7c626b777564">

I'm sure there's no information

**Comment by olddriver4** [comment]
> @olddriver4 Do you see this anywhere in the info logs `enabled websocket for route:`

<img width="1215" alt="image" src="https://github.com/apache/apisix/assets/28889568/4ae70fd9-d7af-4bda-909e-3df6c7af52ee">

I'm sure there's no information

**Comment by Revolyssup** [comment]
@olddriver4 Just to make sure that the correct route is being matched, can you show the info log when you send the ws request. The log should contain something like: `matched route: `

**Comment by olddriver4** [comment]
> I'm sure there's no information

I'm sure there's no information, but apisix has access information, doesn't it mean that apisix has been mentioned?

**Comment by Revolyssup** [comment]
@olddriver4 Yes but these are just the access logs. Do you not see the error logs?

**Comment by olddriver4** [comment]
<img width="1208" alt="image" src="https://github.com/apache/apisix/assets/28889568/81ee564c-8fff-46fa-ac3d-52594e45d46a">

Is PROXY TCP4 reporting an error?

**Comment by olddriver4** [comment]
> <img alt="image" width="1208" src="https://user-images.githubusercontent.com/28889568/271246609-81ee564c-8fff-46fa-ac3d-52594e45d46a.png">
> Is PROXY TCP4 reporting an error?


Is there no one to help me?

**Comment by Revolyssup** [comment]
@olddriver4 Sorry for the late reply. I am looking into this issue now

**Comment by Revolyssup** [comment]
@olddriver4 Is there any other proxy or some service sitting between APISIX and upstream?

**Comment by olddriver4** [comment]
> @olddriver4APISIX 和上游之间是否有其他代理或某些服务？

No other agents, initial description has configuration information

**Comment by olddriver4** [comment]
Found the problem: This is a problem with aws clb. Switching to nlb will be normal. I want to ask the people at AWS  

done.
