### ISSUE TITLE
help request: how to add parameters to URI

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10286]
### Description

Hello. I create my route like this:
```
curl "http://127.0.0.1:9180/apisix/admin/routes/4" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "my.example.com",
  "uri": "/api/service/:myId/transaction",
  "plugins": {
    "basic-auth": {
      "disable": false
    }
  },
  "upstream": {
    "type": "roundrobin",
	"scheme": "http",
    "nodes": {
      "my.example.com": 1
    }
  }
}'
```
and it works fine. 
But how should I write my route if I want to add params to URI like this /api/service/:myId/transaction?code=asd
I tried to change route like "uri": "/api/service/:myId/transactio?code=:code", only to get {"error_msg":"404 Route Not Found"}.

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Red Hat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Make sure you change this field https://github.com/apache/apisix/blob/105993f40f34768cd0a86035d01393346fff3a94/conf/config-default.yaml#L71 to `radixtree_uri_with_parameter`

**Comment by PlasticJonbenetDoll** [comment]
Thanks. I did add http: radixtree_host_uri and also changed "uri": "/api/service/:myId/transaction*"
