### ISSUE TITLE
bug: http_requests_total should be counter not gauge

### ISSUE THREAD

**Issue by polaru** [apache/apisix#10289]
### Current Behavior

When querying the default endpoint for metrics `/apisix/prometheus/metrics` the `http_requests_total` is labeled as a gauge:
```
# HELP apisix_http_requests_total The total number of client requests since APISIX started
# TYPE apisix_http_requests_total gauge
```

I think this metric should be a counter because it doesn't go down, except when it gets reset to zero, which is in line with the definition from [Prometheus docs](https://prometheus.io/docs/concepts/metric_types/#counter).

### Expected Behavior

I believe `http_requests_total` should be labeled as `counter` and not `gauge`.

### Steps to Reproduce

Query the metrics endpoint of a running Apisix instance; in my case this was done by:
```
$ k exec -ti apisix-79957c947-blvbq -- curl -v http://127.0.0.1:9091/apisix/prometheus/metrics 2>&1 | grep http_requests_total 
# HELP apisix_http_requests_total The total number of client requests since APISIX started
# TYPE apisix_http_requests_total gauge
apisix_http_requests_total 11172
```

### Environment

- APISIX version (run `apisix version`): 3.5.0
- Operating system (run `uname -a`): not relevant
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): not relevant
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): not relevant
- APISIX Dashboard version, if relevant: not relevant
- Plugin runner version, for issues related to plugin runners: not relevant
- LuaRocks version, for installation issues (run `luarocks --version`): not relevant

**Comment by moonming** [comment]
@Revolyssup @shreemaan-abhishek please take a look

**Comment by shreemaan-abhishek** [comment]
@moonming I do not fully understand as I don't have experience with prometheus so I cannot confirm if this is correct.

**Comment by Revolyssup** [comment]
Closed with this reason: https://github.com/apache/apisix/pull/10290#issuecomment-1786467060
This change is not needed
