### ISSUE TITLE
feat: As a user, I want to make grpc-transcode work with radixtree_uri_with_parameter, so that I can define the route with path parameters

### ISSUE THREAD

**Issue by moecasts** [apache/apisix#10285]
### Description

feat: As a user, I want to make `grpc-transcode` work with `radixtree_uri_with_parameter`, so that I can define the route with path parameters, but not the query。

**Comment by Revolyssup** [comment]
@moecasts If you're proposing a feature request, can you elaborate with examples? 
You want to use the values of path parameters as input of the gRPC request instead of query parameters?

**Comment by moecasts** [comment]
> @moecasts If you're proposing a feature request, can you elaborate with examples? You want to use the values of path parameters as input of the gRPC request instead of query parameters?

e.g:
I have define a route like: `GET /hello/:name`。

and, I have a proto like:
```
syntax = "proto3";
package helloworld;
service Greeter {
    rpc SayHello (HelloRequest) returns (HelloReply) {}
}
message HelloRequest {
    string name = 1;
}
message HelloReply {
    string message = 1;
}
```

now, when I query the route: `/hello/tom`, the server should get the name: tom。

 maybe, grpc-transcode's configuration should add a field `args` like:
```
 `args`: {
    'name‘： ’arg_name'
  },
```

and: `arg_name` from the ngx build-in args.
