### ISSUE TITLE
feat: As a user, I want forward-auth plugin to allow HTTP PUT,PATCH and DELETE as request method

### ISSUE THREAD

**Issue by theroys** [apache/apisix#10284]
### Description

Right now APISIX forward-auth plugin only supports HTTP GET and POST , as per code below
request_method = {
            type = "string",
            default = "GET",
            enum = {"GET", "POST"},
            description = "the method for client to request the authorization service"
},
Both PUT and PATCH method is extensively used in REST APIs to update an existing resource. Similarly DELETE is also commonly used to delete an existing resource . I think adding them will add completeness forward-auth plugin.

**Comment by Revolyssup** [comment]
@theroys The Method here is for the HTTP request to the authorization service. `GET` and `POST` methods make sense for an authorization service. In what use case will a client need something like `PATCH` and `DELETE` on an authorization service?

**Comment by theroys** [comment]
@Revolyssup  , agree. It was a misunderstanding . We confused the Method as supported HTTP methods while using forward-auth  plugin.

**Comment by Revolyssup** [comment]
> @Revolyssup , agree. It was a misunderstanding . We confused the Method as supported HTTP methods while using forward-auth plugin.

I am closing the issue. Feel free to reopen. :)
