### ISSUE TITLE
help request: How do I configure multiple Nacos clusters?

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10299]
### Description

How do I configure multiple Nacos clusters?

### Environment

- APISIX version (run `apisix version`):3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@lxz999 You can provide multiple host addresses in the configuration in discovery.nacos.host[]. Any one is picked at random.

**Comment by lxz999** [comment]
@Revolyssup If I have two clusters: cluster A: https://a.com:8848,B cluster: https://b.com:8848, the **serviceA** service is registered with cluster A, and the **serviceB** service is registered with cluster B. If it is randomly selected, how can I ensure the correctness of the invocation?

**Comment by monkeyDluffy6017** [comment]
@lxz999 have you solved your problem?
