### ISSUE TITLE
help request: How to do SSL offloading or SSL termination in APISIX. 

### ISSUE THREAD

**Issue by appleconda** [apache/apisix#10300]
### Description

I have added SSL certificate and key in APISIX so it is used by the gateway to process encrypted requests. 
But What I want to do is that when the gateway receives the encrypted request it offloads SSL before sending the request to the backend service. 
Is there way to achieve this? 
As of right now If I setup my backend service in http and I send encrypted request to the gateway to be forwarded to the http backend service it gives 502 bad gateway error. 

APISX Version: 3.5.0
config.yaml of apisix
``` apisix:
  ssl:
    enable: true
    listen:
      - port: 8116

  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: 
        role: admin                 # admin: manage all configuration data

      - name: "viewer"
        key: 
        role: viewer

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/apisix"               # apisix configurations prefix
    timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091```

**Comment by Gallardot** [comment]
Please provide detailed information such as APISIX version, route configuration details, relevant logs, and steps to reproduce the issue to investigate the reported feature.  APISIX supports this feature and it is a fundamental capability of APISIX.
