### ISSUE TITLE
apisix openid-connect plugin FQDN 

### ISSUE THREAD

**Issue by chiliast123** [apache/apisix#10304]
### Current Behavior

Wasn't the FQDN issue fixed in version 2.15? Why do I still have to use FQDN in version 3.2.2 for the service connection to work.
![mmexport1696734458677](https://github.com/apache/apisix/assets/122135142/8d5c861c-2402-4e4f-b6b2-be8d5de8df30)

### Expected Behavior

don't want to use FQDN

### Steps to Reproduce

helm install apisix 3.2.2

### Environment

- APISIX version (run `apisix version`): 3.2.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5
- APISIX Dashboard version, if relevant:03.0
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@chiliast123 Which issue are you referring to? Can you elaborate?

**Comment by chiliast123** [comment]
Can you see the picture? Ourapiisix now is 3.2.2, apisix dashboard is 3.0. We created a route on dashboard using openid-connect, the domain names need to use https://xxx.xxx.xxx.xxx. instead of http://xxx.xxx.xxx.xxx

**Comment by Revolyssup** [comment]
@chiliast123 You can use http in version 3.2.2. Maybe it's issue from dashboard side. What is the error that you get if you use http instead of https with FQDN?

**Comment by chiliast123** [comment]
Which version of dashboard do you recommend? Or what should we do to not use FQDN? We can not use http.

**Comment by kayx23** [comment]
Can't tell from the conversation above what this has to do with FQDN. Sounds like you just don't want to use HTTPS and would like to use HTTP?

@Revolyssup is right that there's no requirement of HTTPS for these configurations. We have a [doc](https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-keycloak#enable-oidc-plugin) here for oidc connection with keycloak and it used just HTTP.

Not sure about the dashboard and would need to know what error you encounter when using HTTP.

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
