### ISSUE TITLE
help request: After upgrading to 3.2.2, call query plug-in metadata report 500 error

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10305]
### Description

After upgrading to 3.2.2, call query plug-in metadata report 500 error.

**2023/10/08 14:55:10 [error] 490#490: *883852 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/admin/utils.lua:109: attempt to index local 'conf' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/apisix/apisix/admin/utils.lua: in function 'decrypt_params'
        /usr/local/apisix/apisix/admin/init.lua:218: in function 'handler'
        /usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:723: in function 'dispatch'
        /usr/local/apisix/apisix/init.lua:885: in function 'http_admin'
        content_by_lua(nginx.conf:241):2: in main chunk, client: 127.0.0.1, server: , request: "GET /apisix/admin/plugin_metadata/csrf HTTP/1.1"**

### Environment

- APISIX version (run `apisix version`):3.2.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@lxz999 Can you provide the reproduce steps? What is the configuration you used while PUTing the plugin_metadata with key `csrf`?

**Comment by lxz999** [comment]
@Revolyssup curl -X GET http://127.0.0.1:9180/apisix/admin/plugin_metadata/csrf -H 'x-api-key:edd1c9f034335f136f87ad84b625c8f1'

**Comment by dyrnq** [comment]
mark
