### ISSUE TITLE
docs: SAML plugin

### ISSUE THREAD

**Issue by ventaubain** [apache/apisix#10311]
### Current State

In the list of all available plugins, I can't see a SAML authentication plugin listed (Plugins -> Authentication). Is it normal given that the SAML support has been cited in the 3.0 release note (https://apisix.apache.org/blog/2022/11/02/apache-apisix-v3-preview/).

We can found a SAML plugin here https://github.com/api7/apisix-saml-auth-plugin that seems official.

### Desired State

A SAML plugin section added to the documentation with a small get started / example.

**Comment by kayx23** [comment]
The SAML plugin code isn't currently in the APISIX code base, for reasons that I'm unaware of.

So this isn't a doc issue per se. I expect doc to be added along with the plugin code.

**Comment by monkeyDluffy6017** [comment]
considered resolved
