### ISSUE TITLE
help request: cannot restrict roles to access apisix routes with keycloak.

### ISSUE THREAD

**Issue by sy-yan** [apache/apisix#10319]
### Description

I want to allow user who has Designated keycloak role to access apisix-dashboard.
And I have read a blog
https://apisix.apache.org/blog/2023/01/02/accessing_apisix-dashboard_from_everywhere_with_keycloak_authentication/
as guide.
But it seems that the "openid-connect" just allow all keycloak users without restricting roles.
So I wonder if apisix has a way to resolve.

keycloak 15 might allow rolePolicy, but my keycloak server is in version 6.0.

### Environment

- APISIX version (run `apisix version`):3.2.0
- APISIX Dashboard version, if relevant:3.0.0-alpine

**Comment by kayx23** [comment]
This plugin offers more capabilities with authorization: https://apisix.apache.org/docs/apisix/plugins/authz-keycloak/

**Comment by sy-yan** [comment]
> This plugin offers more capabilities with authorization: https://apisix.apache.org/docs/apisix/plugins/authz-keycloak/

I had seen this plugin too. But I don't know how to configure. 
When user access my route , I want that only the user who has "admin" role could access. 
Could you provide an example for me ? Thanks a lot.

**Comment by monkeyDluffy6017** [comment]
@sy-yan have you solved your problem?

**Comment by kayx23** [comment]
@sy-yan see this user's setup: https://github.com/apache/apisix/issues/9609#issuecomment-1836527016

In the third document, you can find

![Screenshot at Dec 12 20-01-14](https://github.com/apache/apisix/assets/39619599/71d77cbe-5dd6-4cc3-84ed-c01434d5b0e0)

**Comment by kayx23** [comment]
> I want to allow user who has Designated keycloak role to access apisix-dashboard.
> keycloak 15 might allow rolePolicy, but my keycloak server is in version 6.0.
> When user access my route, I want that only the user who has "admin" role could access.

I'm using keycloak v18.x.x so it's hard to tell. Not an expert on this, just trying to help. Are you positive policy isn't supported? Could you show us your keycloak v6.0 interface?

**Comment by kayx23** [comment]
@sy-yan Hi - following up to see if this issue is still active? From my understanding, you would enable Authorization for the client and configure role and policy (for RBAC) to a resource.

I tested with keycloak v18 and used `authz-keycloak` plugin to protect an arbitrary upstream (only clients with role `admin` can access) and it was working as intended. Most of the configurations would be done on the keycloak side though.

Unfortunately cannot advise on keycloak 6.0

**Comment by kayx23** [comment]
>  it seems that the "openid-connect" just allow all keycloak users without restricting roles.

As for `openid-connect`, I played around but also wasn't able to make RBAC works. This might be of interest for you: https://github.com/zmartzone/lua-resty-openidc/issues/222

Alternatively, you could implement scope based access with `required_scope`: https://github.com/apache/apisix/pull/10493
