### ISSUE TITLE
data format compatibility issues

### ISSUE THREAD

**Issue by chiliast123** [apache/apisix#10324]
### Description

Will there be data format compatibility issues with routes and upstream created by yaml files when apisix is upgraded (from 2.13 to 3.2.2)?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
of course. The syntax of existing plug-ins is different between different versions. So you have to look at it case by case.

**Comment by oyiadin** [comment]
this document may be exactly what you need: https://apisix.apache.org/docs/apisix/upgrade-guide-from-2.15.x-to-3.0.0/

**Comment by chiliast123** [comment]
Will the rules created by Ingress Controller CRD have data format compatibility issues? Can I execute helm upgrade apiaix directly with no impact?
![mmexport1697384507154](https://github.com/apache/apisix/assets/122135142/2e2fc23b-555c-434f-b434-8ba68eb10cd7)
![Uploading mmexport1697384505173.jpg…]()

**Comment by chiliast123** [comment]
Will the rules created by Ingress Controller CRD have data format compatibility issues? Can I execute helm upgrade apisix directly with no impact?
![mmexport1697384507154](https://github.com/apache/apisix/assets/122135142/d1fc0571-7cad-470d-aa1b-483122a3e036)
![Uploading mmexport1697384505173.jpg…]()

**Comment by monkeyDluffy6017** [comment]
@chiliast123 I think no, please be more careful when you do an upgrade
