### ISSUE TITLE
 help request: route not found

### ISSUE THREAD

**Issue by xialp** [apache/apisix#10322]
### Description

Version 1.26 k8s cluster, helm chart installed apisix apache/apisix:3.5.0-debian version, dashbord configured routing, and forwarded, but an error was reported that the route could not be found. Other versions also failed, but switched to a lower version. K8s is OK

### Environment

- APISIX version (run `apisix version`):3.5.0
- Operating system (run `uname -a`):Linux iZbp1cc9n7coeb5wuu979qZ 4.19.91-27.1.al7.x86_64 #1 SMP Tue Feb 21 11:41:32 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant:apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@xialp Can you share the route configuration and reproduction steps?

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
