### ISSUE TITLE
bug: dashbord config not effect

### ISSUE THREAD

**Issue by qlql489** [apache/apisix#10327]
### Current Behavior

dashboard edit upstream port from 8081 to 80，query apisix admin api  /apisix/admin/routes it work,port  change to 80 
![image](https://github.com/apache/apisix/assets/10767590/781afcfd-06a9-4cab-94d7-cf656168053f)
,but when call the router, it used the old config , log show the port: "upstream_addr":"172.27.0.5:9081
after restart apisix, it correct: "upstream_addr":"172.27.0.5:80"  

### Steps to Reproduce

1、download  https://github.com/apache/apisix-docker 
2、edit example/docker-compose-arm64.yml the apisix version  apache/apisix:3.4.1-centos
3、docker-compose -p docker-apisix -f docker-compose-arm64.yml up -d
4、new router 
```
{
  "uri": "/demo",
  "name": "demo",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "upstream": {
    "nodes": [
      {
        "host": "web1",
        "port": 9081,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```
call the router return 502
then change port to 80
call the router return 502
restart apisix 
call the router  success

### Environment

- APISIX version (run `apisix version`):  3.2.2-centos and 3.4.1-centos
- Operating system (run `uname -a`):  docker image: apache/apisix:3.4.1-centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): docker rancher/coreos-etcd:v3.4.15-arm64
- APISIX Dashboard version, if relevant:  docker apache/apisix-dashboard:3.0.1-centos
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by beginnerWJC** [comment]
I've got the same problem.

**Comment by Sn0rt** [comment]
I sorry to tell you the apisix-dashboard not guarantee compatible with apache/apisix:3.4.1-centos

https://github.com/apache/apisix-dashboard

> The master version should be used with Apache APISIX master version.
> The latest released version is [3.0.0](https://apisix.apache.org/downloads/) and is compatible with [Apache APISIX 3.0.x](https://apisix.apache.org/downloads/).

**Comment by qlql489** [comment]
what apisix-dashboard  version  compatible with apache/apisix:3.4.1-centos or compatible with apache/apisix:3.2.2-centos

**Comment by Sn0rt** [comment]
No, the latest version of the dashboard is only compatible with 3.0.x. You can use the admin api to manage apisix.

Of course you are welcome to contribute to the dashboard

**Comment by beginnerWJC** [comment]
@Sn0rt this problem not problems with apisix-dashboard，i use apisix-3.5.0，not change apisix-dashboard‘s version，find this problem is slove
