### ISSUE TITLE
help request: How to allocate memory and cpu for apisix, and what is the minimum?

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10321]
### Description

How to allocate memory and cpu for apisix, and what is the minimum?

### Environment

- APISIX version (run `apisix version`):3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by oyiadin** [comment]
Sorry but I can't catch your point.

If you want to trigger a garbage collection to reduce memory usage, try this: https://apisix.apache.org/docs/apisix/control-api/#post-v1gc

If you want to "pre-allocate" the memory & cpu usage of APISIX, I don't think it's achievable via a simple way. Maybe you can run a benchmark or stress test to "warm up" APISIX ;-)

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
