### ISSUE TITLE
help request:   etcd watch error: key: /apisix/ssls err: rpc error: code = PermissionDenied desc = etcdserver: permission denied

### ISSUE THREAD

**Issue by dingdingkaifa** [apache/apisix#10333]
### Description

etcd: etcd watch error: key: /apisix/ssls err: rpc error: code = PermissionDenied desc = etcdserver: permission denied

![20231013173927](https://github.com/apache/apisix/assets/32190417/b067f5ed-412e-4e8a-8894-21868f49e8a9)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
please provide the steps for reproduction.

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
