### ISSUE TITLE
bug: Apisix is changing server name to ip address. This makes it unable to get certificate and make TLS/SSL handshake

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10335]
### Current Behavior

Apisix is changing server name to IP address. This makes it unable to get certificate and make TLS/SSL handshake.

### Expected Behavior

Apisix souldn't access upstream by IP.

### Error Logs

SSL_do_handshake() failed (SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:SSL alert number 40) while SSL handshaking to upstream, client: xx.xx.xx.xx, server: _, request: "PUT /func/generate HTTP/1.1", upstream: "https://xx.xxx.xxx.xx:443/func/generate", host: "xxx.com"

### Steps to Reproduce

Create simple route:
```
curl "http://127.0.0.1:9180/apisix/admin/routes/5" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["POST"],
  "uri": "/func/generate",
  "status": 1,
  "upstream": {
    "type": "roundrobin",
	"scheme": "https",
    "nodes": {
      "api.someserver.com:443": 1
    }
  }
}'
```
Now if we connect with api.server.com that have TLS/SSL bound to address we receive an error.
I guess this happens because according to logs Apisix is trying to connect by https://xx.xxx.xxx.xx:443/func/generate and not https://api.someserver.com:443/func/generate.

Also I checked that upstream server is supporting SNI by doing curl with -servername param. 

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Redhat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Try configuring these values:

<img width="857" alt="image" src="https://github.com/apache/apisix/assets/61597896/5dbe1fb3-bcf5-4cd0-bde6-d1fe88e5d6a1">

You can see in the example [here](https://docs.api7.ai/apisix/plugins/graphql-limit-count#apply-rate-limiting-by-remote-address) that https scheme works as expected.

**Comment by PlasticJonbenetDoll** [comment]
Are there are any examples that shows how to use tls.client_cert?

**Comment by PlasticJonbenetDoll** [comment]
I have found similar issue here - https://github.com/apache/apisix/issues/6296. But wasn't able to fix the problem with proxy_rewrite or pass_host. Any suggestions?

**Comment by PlasticJonbenetDoll** [comment]
@shreemaan-abhishek I also tried your suggestion to configure tls.client_cert and tls.client_key but it didn't help.

**Comment by PlasticJonbenetDoll** [comment]
Those configurations doesn't work either:
```
apisix
  ssl：
    fallback_sni: "${your sni}"
```

**Comment by shreemaan-abhishek** [comment]
> I also tried your suggestion to configure tls.client_cert and tls.client_key but it didn't help.

Was there a different error?

**Comment by PlasticJonbenetDoll** [comment]
I'm closing the issue because I believe the problem is in upstream. This upstream I think doesn't support SNI.
