### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix#10336]
### Description

I need help to join the slack channel.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
https://join.slack.com/t/the-asf/shared_invite/zt-23oo16n1x-v0ZoiIe4RGFhZmp80PNGKA
