### ISSUE TITLE
docs: upstream helthcheck when using consul kv

### ISSUE THREAD

**Issue by jonathan-dev** [apache/apisix#10345]
### Current State

In the docs i find the following statement (https://apisix.apache.org/docs/apisix/tutorials/health-check/):

> We won't start the health check when the upstream only has one node, as we will access it whether this unique node is healthy or not.

Since I am using consul kv for the node management i don't strictly have nodes. does the above statement also aply for the consul kv entries (that i need at least 2).

### Desired State

Clarification what happens when no nodes but consul kv is used

**Comment by shreemaan-abhishek** [comment]
APISIX healthcheck rules do not apply for consul.
