### ISSUE TITLE
help request: customize APISIX default 403 Forbidden error page

### ISSUE THREAD

**Issue by nphariharan** [apache/apisix#10343]
### Description

Hello,

 I am using APISIX standalone configuration 3.6.0. I am trying to remove the "Powered by APISIX." in APISIX default 403 Forbidden error page. However I m unable to remove it. Pl provide help here. 

Thanks in advance.
Hariharan.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
this might help you: https://github.com/apache/apisix/issues/7987#issuecomment-1363711257

**Comment by lvillis** [comment]
I have solved it, refer to https://github.com/apache/apisix/issues/7987#issuecomment-1787575511

**Comment by monkeyDluffy6017** [comment]
considered resolved
