### ISSUE TITLE
bug: Incorrect Trace ID in loki-logger 

### ISSUE THREAD

**Issue by monlor** [apache/apisix#10341]
### Current Behavior

When enabling the trace_id nginx variable and configuring the loki-logger plugin with `log_labels.trace_id: $opentelemetry_trace_id` to set trace_id as a label, it seems to mismatch and sometimes captures trace IDs from other requests. This results in an incorrect association of logs with the corresponding trace IDs.

### Error Logs

logs:
```
..."traceparent":"00-762e14ed7580ccdc0813230ecd461e8a-d006463016a0c407-01"...
```
labels:
```
...trace_id: 79d9b7444bd7bf4ec844c65bae30006a...
```

### Steps to Reproduce

1. Run APISIX via the helm.
2. Create a Route using the APISIXROUTE.
3. Configure the loki-logger plugin with log_labels.trace_id: $opentelemetry_trace_id.
4. Observe the trace IDs in the logs, noticing that some of them are mismatched. compare traceparrent and labels

### Environment

apisix helm chart 2.3.0
- APISIX version (run `apisix version`): 3.6 
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@monlor So you never get the log from loki logger for the request `traceparent":"00-762e14ed7580ccdc0813230ecd461e8a-d006463016a0c407-01"...` ??

**Comment by monlor** [comment]
I had got the log from loki. we can see that the `trace_id` of the log `traceparent":"00-762e14ed7580ccdc0813230ecd461e8a-d006463016a0c407-01"` is `762e14ed7580ccdc0813230ecd461e8a `. This does not correspond to my custom `trace_id` label, which comes from `$opentelemetry_trace_id`.

**Comment by monlor** [comment]
I suspect it got the wrong label from other request.

**Comment by Revolyssup** [comment]
> I had got the log from loki. we can see that the `trace_id` of the log `traceparent":"00-762e14ed7580ccdc0813230ecd461e8a-d006463016a0c407-01"` is `762e14ed7580ccdc0813230ecd461e8a `. This does not correspond to my custom `trace_id` label, which comes from `$opentelemetry_trace_id`.

Yes I understood that  but I doubted about the possibility of inermixing because the variable opentelemetry_trace_id is request scoped only and shared nowhere. I just wanted to confirm if you're sure that the loki logs corresponded to that request only. Because logs are sent in batches, I wanted to make sure that it wasn't a problem of order not being right. So you can confirm that the loki log for that request was never received and only the one with some other label value was received?

**Comment by monlor** [comment]
Not really, Refer to this article [opentelemetry plugins](https://apisix.apache.org/docs/apisix/plugins/opentelemetry/#variables), opentelemetry_trace_id can be set to nginx.var. Loki logger can be configured to use values from nginx.var as labels.

**Comment by monlor** [comment]
I searched the logs by content '762e14ed7580ccdc0813230ecd461e8a', I only recerived one log.
I searched the logs by trace_id labels, Maybe I got multiple logs.

**Comment by Revolyssup** [comment]
> Not really, Refer to this article [opentelemetry plugins](https://apisix.apache.org/docs/apisix/plugins/opentelemetry/#variables), opentelemetry_trace_id can be set to nginx.var. Loki logger can be configured to use values from nginx.var as labels.

Yes and ngx.var is request scoped

**Comment by Revolyssup** [comment]
> I searched the logs by content '762e14ed7580ccdc0813230ecd461e8a', I only recerived one log. I searched the logs by trace_id labels, Maybe I got multiple logs.

So you never get the Loki log with label 762e14ed7580ccdc0813230ecd461e8a?

**Comment by monlor** [comment]
> > I searched the logs by content '762e14ed7580ccdc0813230ecd461e8a', I only recerived one log. I searched the logs by trace_id labels, Maybe I got multiple logs.
> 
> So you never get the Loki log with label 762e14ed7580ccdc0813230ecd461e8a?

Yes. Right!

```
Sorry! I'm not good at English, I can read every word, but it's a little hard to understand when they're grouped together. hahaha
😂
```

**Comment by Revolyssup** [comment]
@monlor Can you provide your configuration? Config.yaml and plugin configuration. This seems to be the case of lost logs. T

**Comment by shreemaan-abhishek** [comment]
is there any error in the error logs? @monlor

**Comment by shreemaan-abhishek** [comment]
Since we could not repro this issue, I'll close this now due to lack of activity.

**Comment by magnus-h-65** [comment]
Since I just ran across the same issue: The loki logger is not adapted to be used as a global rule, which I tried at first. The reason is that the plugin reuses data based on the `conf` parameter, which is the same for all routes if defined as a global rule. That might be the cause of this bug.

**Comment by Baoyuantop** [comment]
Hi @magnus-h-65, are there stable steps to reproduce?

**Comment by magnus-h-65** [comment]
Hi @Baoyuantop, I haven't made any test for it, however what I have is an APISix instance with 8 workers, and I assume each worker will set up the plugin with the `conf` it gets when first called, and then reuse that `conf` (it evaluates parameters which are not changing between events first time so it can reuse them later). So I get 3 or 4 different "base `conf`'s" which are reused over and over, but with different dates for each event.
Maybe a bit tricky to reproduce since the requests are routed to different workers in a random way...?
