### ISSUE TITLE
docs: documents of apisix ingtess controller v1.7 is not updated, the latest docs from your website is still about v1.6.1

### ISSUE THREAD

**Issue by karl-chanel** [apache/apisix#10348]

**Comment by shreemaan-abhishek** [comment]
cc: @AlinsRan @tao12345666333

**Comment by AlinsRan** [comment]
I think it's because the branch name has changed.

apisix-website: https://github.com/apache/apisix-website/blob/master/doc/docusaurus.config.js#L11-L12.
apisix-ingress-controller：https://github.com/apache/apisix-ingress-controller/blob/master/.asf.yaml#L46-L51

**Comment by lingsamuel** [comment]
> I think it's because the branch name has changed.
> 
> apisix-website: https://github.com/apache/apisix-website/blob/master/doc/docusaurus.config.js#L11-L12. apisix-ingress-controller：https://github.com/apache/apisix-ingress-controller/blob/master/.asf.yaml#L46-L51

In git's model, branches and tags have little difference. The real problem seems to be the website script does not search fort he git-tag paths.
https://github.com/apache/apisix-website/blob/master/scripts/sync-docs.js#L74

**Comment by moonming** [comment]
already fixed
