### ISSUE TITLE
bug: Install Dependency Script: ./utils/install-dependencies.sh seems to be broken

### ISSUE THREAD

**Issue by jj701** [apache/apisix#10362]
### Current Behavior

I was trying to build APISIX from source. I was following the instructions here: https://apisix.apache.org/docs/apisix/building-apisix/

I am building on Centos 7

I get this error when executing the ./utils/install-dependencies.sh:

failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try.
https://repos.apiseven.com/packages/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden

### Steps to Reproduce

Check out the Github Repository.

./utils/install-dependencies.sh 

### Environment

- APISIX version '3.6.0'
- Operating system Linux 3.10.0-1127.10.1.el7.x86_64

**Comment by Revolyssup** [comment]
@jj701 This might be because the mirrors aren't available at this point. You can try later after some time.

**Comment by jj701** [comment]
This issue is been there from weeks. Unable to do Centos 7 installation of APISIX

**Comment by shreemaan-abhishek** [comment]
can you share more information on the operating system/machine/cloud vm you are using?

**Comment by monkeyDluffy6017** [comment]
@jj701 have you solved your problem?

**Comment by monkeyDluffy6017** [comment]
centos7 is not suggested, it will EOL soon
