### ISSUE TITLE
help request: custom rejected_msg is not displayed in the request-validation plugin

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10367]
### Description 

Hello everyone! I have a problem with the request-validation plugin. Custom rejected_msg cannot be displayed. I
used my message in rejected_msg, but the standard ones are displayed. I also tried to use rejected_code, but the standard - 400 is always used.

Example of my route
```shell
{
  "uri": "/api/*",
  "name": "test",
  "methods": [
    "POST"
  ],
  "plugins": {
    "request-validation": {
      "body_schema": {
        "additionalProperties": false,
        "properties": {
          "age": {
            "maximum": 2,
            "minimum": 1,
            "type": "integer"
          },
          "is_active": {
            "type": "boolean"
          },
          "lastname": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "rejected_code": 418,
        "rejected_msg": "JSON",
        "type": "object"
      }
    }
  },
  "upstream_id": "483350426926711488",
  "status": 1
}
```
    
 The message I get in the APISIX log when executing a request using the plugin I attached above:
    
    
![image](https://github.com/apache/apisix/assets/54456916/b7c92993-27fb-4404-99b4-d71648268eef)

    
I tested this example on earlier versions of APISIX, the result was the same. Is my plugin configured incorrectly or is it a bug?   

### Environment

- APISIX version 3.5.0-debian
- etcd version etcd:3.4.15
- APISIX Dashboard version 3.0.1-alpine

**Comment by kayx23** [comment]
The plugin should be working. Here's my test:

```shell
curl "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT -d '
{
    "uri": "/get",
    "plugins": {
        "request-validation": {
            "header_schema": {
                "type": "object",
                "required": ["Host"],
                "properties": {
                    "Host": {
                        "type": "string",
                        "enum": ["httpbin"]
                    }
                }
            },
            "rejected_code": 555,
            "rejected_msg": "Oh No 555 reject message! \n"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:80": 1
        }
    }
}'
```

![image](https://github.com/apache/apisix/assets/39619599/1dcef43d-f42a-4aad-a5f6-effaa19e3128)

**Comment by pavlenkodev** [comment]
> The plugin should be working. Here's my test:
> 
> ```shell
> curl "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT -d '
> {
>     "uri": "/get",
>     "plugins": {
>         "request-validation": {
>             "header_schema": {
>                 "type": "object",
>                 "required": ["Host"],
>                 "properties": {
>                     "Host": {
>                         "type": "string",
>                         "enum": ["httpbin"]
>                     }
>                 }
>             },
>             "rejected_code": 555,
>             "rejected_msg": "Oh No 555 reject message! \n"
>         }
>     },
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "httpbin.org:80": 1
>         }
>     }
> }'
> ```
> 
> ![image](https://user-images.githubusercontent.com/39619599/277079976-1dcef43d-f42a-4aad-a5f6-effaa19e3128.png)



I tried your example and it also worked. I assume that in conjunction with header_body rejected_msg works. I tried an example from the official documentation that used body_schema and rejected code and message don't work. https://apisix.apache.org/docs/apisix/plugins/request-validation/


{
  "uri": "/get",
  "plugins": {
    "request-validation": {
      "body_schema": {
        "type": "object",
        "required": ["required_payload"],
        "properties": {
          "required_payload": {"type": "string"},
          "boolean_payload": {"type": "boolean"}
        },
        "rejected_msg": "customize reject message"
      }
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "127.0.0.1:8080": 1
    }
  }
}

Have you tried the same thing? Did you manage to output rejected message or code?

**Comment by pavlenkodev** [comment]
I noticed my mistake, it was in the wrong location of rejected_msg and code. After looking carefully at the @kayx23 example, I finally noticed this.
Thanks!
