### ISSUE TITLE
help request: Is it possible to create route that wouldn't need Host

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10365]
### Description

Hello.
I'm trying to make some routes and everything works fine when I pass Host in requests. But when I don't add Host in Header, then I receive 404 Route not Found Error. 
```
curl "http://127.0.0.1:9180/apisix/admin/routes/2" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "api.smthing.com",
  "uri": "/api/v1/accounts",
  "upstream": {
    "type": "roundrobin",
	"scheme": "http",
    "nodes": {
      "api.smthing.com": 1
    }
  }
}'
```

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Red Har
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
you can use `pass_host: node`
