### ISSUE TITLE
help request: getting the request status in Serverless plugin

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10378]
### Description

Hello everyone I wanted to use the serverless plugin to get the status of the request and, depending on the status, redirect or close access. I tried to write a function in lua using ngx.status, ctx.var.status, ngx.upstream_status, but I get 0 or nil instead of the real status.

Here is an example of my function that I implemented based on https://api7.ai/blog/serverless-plugin-for-event-hooks

```
   function webhook(conf, ctx)
   
    local http = require("resty.http")
    local core = require("apisix.core")
    local status = ngx.status

    if status == 200 then
      -- Redirect or new request create
       
        local httpc = http.new()
        local res, err = httpc:request_uri("http://webhook.site/907b49fc-2982-4d4b-bdf0-6863bcbb5bdd", {
            method = "POST",
            headers = {
                ["Content-Type"] = "application/json"
            },
            body = core.request.get_body(),
        })
         if not res then
            core.log.error("Failed to send webhook: ", err)
            return 500, err
        end
    end

    return conf.status, conf.body
end 
```

How can I get the status to implement the function?
Maybe this is done in a different way and the serverless plugin is not suitable?

### Environment

- APISIX version 3.5.0-debian
- etcd version etcd:3.4.15
- APISIX Dashboard version 3.0.1-alpine

**Comment by shreemaan-abhishek** [comment]
Are you using the same configurations as mentioned in the blog?

**Comment by pavlenkodev** [comment]
> Are you using the same configurations as mentioned in the blog?

I am running apisix not exactly as shown in the blog. I have my own docker-compose.yml, which contains only apisix, apisix dashboard api, and etcd. In this case, the configuration files for all services are used from the example in the blog.

I also tried to reproduce the example from the blog using the modified function that I added above. But I was unable to get the actual request/response status

**Comment by shreemaan-abhishek** [comment]
could you please share the plugin configuration.

**Comment by shreemaan-abhishek** [comment]
you need to use the serverless-post-plugin in the `body-filter` phase.

**Comment by shreemaan-abhishek** [comment]
you need to use the serverless-post-plugin in the `body-filter` phase.

**Comment by pavlenkodev** [comment]
This is my route configuration now

```
{
  "uri": "/api/*",
  "name": "serverless",
  "methods": [
    "GET"
  ],
  "plugins": {
    "serverless-post-function": {
      "functions": [
        "\n                    return function(conf, ctx)\n                        -- Import neccessary libraries\n                        local http = require(\"resty.http\")\n                        local core = require(\"apisix.core\")\n\n                        -- Send the webhook notification only if the request method is POST, otherwise skip and send it to the upstream as usual\n                        if ngx.status == 200 then\n                            -- Send the webhook notification to the specified URL\n                            local httpc = http.new()\n                            local res, err = httpc:request_uri(\"http://webhook.site/907b49fc-2982-4d4b-bdf0-6863bcbb5bdd\", {\n                                method = \"POST\",\n                                headers = {\n                                    [\"Content-Type\"] = \"application/json\"\n                                },\n                                body = core.request.get_body(),\n                            })\n                            -- Check the response from the webhook\n                            if not res then\n                                core.log.error(\"Failed to send webhook: \", err)\n                                return 500, err\n                            end\n                        end\n\n                        -- Return the response from the upstream service\n                        return conf.status, conf.body\n                    end"
      ],
      "phase": "body_filter"
    }
  },
  "upstream_id": "484339402638623428",
  "status": 1
}
```

I tried to do as you said. I have an error
![image](https://github.com/apache/apisix/assets/54456916/78a5b434-905a-413f-a3b6-12a1cb43f8f3)


I checked on the apisix configuration as indicated in the blog and in my local, the result is the same. I also tried to get the status using not only ngx.status. I noticed such a feature, if you use 0 or null in the condition (if ngx.status ==) , no error occurs, and if you use 200, an error occurs. Apparently this is due to sending a request to the webhook site? Is it necessary to do it differently, or is the body_filter phase not suitable for this?

**Comment by pavlenkodev** [comment]
Hi @shreemaan-abhishek ! Could you tell me what I did wrong?)

**Comment by pavlenkodev** [comment]
I found a solution how to implement my function in a different way! At the body-filter phase, I did not succeed.  Anyway, thanks for the help!

**Comment by shreemaan-abhishek** [comment]
@pavlenkodev please share what worked for you I want to learn how you made it through.
