### ISSUE TITLE
bug: When the request body is too large, forward-auth returns 403

### ISSUE THREAD

**Issue by lplcc** [apache/apisix#10375]
### Current Behavior

When the request body is too large, forward-auth returns 403

### Expected Behavior

Hope to support the upload of more than 10M files

### Error Logs

send() failed (32: Broken pipe), client: 10.10.103.41, server: _, request: "POST /jljftest/v1/paas/service/meter HTTP/1.1", host: "172.70.2.82:9080"
[lua] forward-auth.lua:125: phase_func(): failed to process forward auth, err: broken pipe, client: 10.10.103.41, server: _, request: "POST /jljftest/v1/paas/service/meter HTTP/1.1", host: "172.70.2.82:9080"

### Steps to Reproduce

1,Configuring routes
2,add forward-auth plugin
3,Calls the gateway interface to upload a request containing a base64 string

### Environment

- APISIX version (run `[APISIX/3.6.0]`):
- Operating system (run `linux`):
- OpenResty / Nginx version (run `openresty/1.21.4.2` or `nginx -V`):
- etcd version, if relevant (run `3.5.0`):
- APISIX Dashboard version, run 3.0.1:
- Plugin runner version, for issues related to plugin runners: forward-auth 3.6.0
- LuaRocks version, for installation issues (run `3.8.0`):

**Comment by shreemaan-abhishek** [comment]
> When the request body is too large, forward-auth returns 403

Can you describe the use case? Why would an auth request carry a too large body?

**Comment by Revolyssup** [comment]
@lplcc Unlike Nginx, APISIX does not limit the body size by default.
what is the value of `client_max_body_size` in your apisix configuration. You can set it to 0(for infinite)

**Comment by lplcc** [comment]
> > When the request body is too large, forward-auth returns 403
> 
> Can you describe the use case? Why would an auth request carry a too large body?

Our API is going to upload an attachment, which is done through a base64 string

**Comment by monkeyDluffy6017** [comment]
Try to increase the [conf.keepalive](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L113) and the [conf.timeout](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L119)

**Comment by lplcc** [comment]
> Try to increase the [conf.keepalive](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L113) and the [conf.timeout](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L119)
![image](https://github.com/apache/apisix/assets/22811367/73c86720-0bad-4465-b1c8-744cda3beade)
https://github.com/ledgetech/lua-resty-http#get_client_body_reader
it can solve the problem,There may be a better solution, but I don't have any other options

**Comment by monkeyDluffy6017** [comment]
> Try to increase the [conf.keepalive](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L113) and the [conf.timeout](https://github.com/apache/apisix/blob/455804771124c15ff909e49ad8dfdd961f0e4a88/apisix/plugins/forward-auth.lua#L119)

Have you tried this?

**Comment by lplcc** [comment]
Yes, our production environment is already in use，You couldn't upload 10MB images before, but now you can

**Comment by monkeyDluffy6017** [comment]
If these configurations can solve your problem, why do you create a completely different PR?

**Comment by lplcc** [comment]
Because I don't know much about lua, am not sure if my solution is perfect, but want to fix the bug

**Comment by monkeyDluffy6017** [comment]
It's ok to increase the timeout, let's close this issue

**Comment by lplcc** [comment]
> It's ok to increase the timeout, let's close this issue

I have tried,but I failed

**Comment by lplcc** [comment]
> It's ok to increase the timeout, let's close this issue
Can you give a detailed solution, or how to configure it

**Comment by lplcc** [comment]
> It's ok to increase the timeout, let's close this issue

it can't work,I was wrong about your question last time.


> Yes, our production environment is already in use，You couldn't upload 10MB images before, but now you can
This is done by modifying the source code, not by increasing the timeout

**Comment by shreemaan-abhishek** [comment]
> Can you give a detailed solution, or how to configure it

You can configure these attributes in the plugin configuration.

<img width="825" alt="image" src="https://github.com/apache/apisix/assets/61597896/44829503-aea1-4326-a770-92ca2e0f3e5b">

**Comment by lplcc** [comment]
I have tried all these things, but none of them have solved the problem
`conf.keepalive_timeout = 60000 `
`conf.timeout = 60000 `
`conf.keepalive = true`

**Comment by shreemaan-abhishek** [comment]
could you please share your route configuration?

**Comment by shreemaan-abhishek** [comment]
@monkeyDluffy6017, the OP is right, this bug actually exists.

**Comment by monkeyDluffy6017** [comment]
@shreemaan-abhishek the related pr failed a lot of test cases, would you like to fix this?
