### ISSUE TITLE
help request: is it possible to return custom response if the wrong method was called?

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#10387]
### Description

So I have a question. Is it possible to return custom response if the wrong method was called? 
For example route's method was GET but client sent POST request.
Currently apisix returns Route not Found, but I want to make different resopnse based on used method.

### Environment

- APISIX version (run `apisix version`): 3.5
- Operating system (run `uname -a`): Red Hat
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
you can use the serverless plugin to do this setup.

**Comment by PlasticJonbenetDoll** [comment]
Thanks for reply. Can you show an example of how serverless plugin can do that?

**Comment by shreemaan-abhishek** [comment]
I'm sorry I misunderstood your query. This isn't supported yet, could you raise a PR for this? Let me know if you need any help.

**Comment by kayx23** [comment]
> For example route's method was GET but client sent POST request.
> Currently apisix returns Route not Found, but I want to make different resopnse based on used method.

You would just create a route to match POST and return an error message. Consider using the `response-rewrite` plugin.

IMHO this should not be a new feature. Because what happens if someone needs to match to different destinations for GET and POST methods?

**Comment by monkeyDluffy6017** [comment]
Not supported yet

**Comment by monkeyDluffy6017** [comment]
Maybe you could configure a router with the wrong method, and return custom response in the router

**Comment by monkeyDluffy6017** [comment]
I will close this issue, feel free to reopen it
