### ISSUE TITLE
help request: Does traffic-split support health check?

### ISSUE THREAD

**Issue by jensonfunfun** [apache/apisix#10385]
### Description

Looking at the code, I found that the traffic-split plug-in does not support health checks. Is there support or a support plan?

### Environment

1、apisix version：3.2

**Comment by shreemaan-abhishek** [comment]
Welcome to submit a PR.

**Comment by jensonfxc** [comment]
I processed it based on apisix3.2, how should I submit it?

**Comment by shreemaan-abhishek** [comment]
you can raise a PR to the master branch first so that it can be backported to 3.2.

**Comment by monkeyDluffy6017** [comment]
@jensonfxc any update?
