### ISSUE TITLE
help request: Can the limit-req plugin limit the request speed based on upstream_addr?

### ISSUE THREAD

**Issue by jensonfxc** [apache/apisix#10384]
### Description

Is there a plug-in that can limit the speed based on upstream_addr?
<img width="874" alt="image" src="https://github.com/apache/apisix/assets/45093275/8cb4b9a5-def9-4656-a535-2709f21df9cb">

### Environment

1、apisix version：3.2

**Comment by shreemaan-abhishek** [comment]
In theory, it should work. You can give a try.

**Comment by moonming** [comment]
First, this is impossible because the upstream address is not known when running the limit req plugin. Then, what problem do you want to solve?

**Comment by jensonfxc** [comment]
We wondered if we could control the QPS forwarded to the backend in nginx to ensure that sudden large traffic would not be affected by backend usage, but we found that the common implementation is to discard all traffic through circuit breakers.
