### ISSUE TITLE
help request: memory growing up

### ISSUE THREAD

**Issue by channer99** [apache/apisix#10392]
### Description

A tendency for memory to gradually increase was confirmed.
checking many issues related to memory(prometheus, ext-plugin, traffic-split, etc...), but i cannot determine the exact cause.

<img width="1127" alt="1_memory_trand" src="https://github.com/apache/apisix/assets/148939043/7d50b388-1f3e-4182-8cd8-44195f648145">

The plugin below is used as a global plugin.
- cors, opentelemetry, prometheus, request_id, response_rewrite

The following plugins were set for individual routes.
- elasticsearch-logger, ext-plugin-pre-req, limit-count or limit-req, traffic-split

also, traffic-split plugin config is used like [#10349](https://github.com/apache/apisix/issues/10349#issuecomment-1776521774)(weight : 1 , weight : 0) 

my config.yaml is
```
apisix:
  node_listen:
      - port: 80
  ssl:
    enable: false

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - all
    admin_listen:
        port: 9180
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
  etcd:
    host:
      - "http://127.0.0.1:2379"

nginx_config:  
  enable_cpu_affinity: |
      true;
  http_configuration_snippet: |
      client_body_buffer_size 10m;
      proxy_max_temp_file_size 0;
  http_server_configuration_snippet: |
      merge_slashes off;
      proxy_ignore_client_abort on;
      set $parameter "dev";
  http:
    lua_shared_dict:
      prometheus-metrics: 100m

plugin_attr:
  opentelemetry:
    trace_id_source: x-request-id
    resource:
      service.name: test_GW
    collector:
      address: 192.168.8.211:4318
      request_timeout: 3
      request_headers:
        foo: bar
    batch_span_processor:
      drop_on_queue_full: false
      max_queue_size: 6
      batch_timeout: 2
      inactive_timeout: 1
      max_export_batch_size: 2
  prometheus:
    export_uri: /apisix/metrics
    export_addr:
      port: 8088

ext-plugin:
  cmd: ['java', '-jar', '-Xmx1g', '-Xms1g', '/usr/local/apisix/test.jar', '--paramr=dev']
```

So I obtained a flamegraph through openresty xray. 
Can you check where the memory leak occurs?

![2_Lua-Land Memory Leak Flame Graphs](https://github.com/apache/apisix/assets/148939043/b5ffcb14-cdea-4ecf-894a-6488149c29eb)
![3_LuaJIT GC Object Allocation Flame Graph](https://github.com/apache/apisix/assets/148939043/57ef3eb6-fb5c-4dd3-914f-e93bc01b4ed5)
![4_LuaJIT GC Object Allocation Size Flame Graph](https://github.com/apache/apisix/assets/148939043/33a39f4f-0c95-4147-9c8d-11a2fb7e2912)
![5_LuaJIT String Objects Allocation Flame Graph](https://github.com/apache/apisix/assets/148939043/c9e8e051-ed79-462c-8491-ba0bad478c08)
![6_LuaJIT Table Objects Allocation Flame Graph](https://github.com/apache/apisix/assets/148939043/406c3be3-4854-483f-96b0-2a290444405b)
![7_Lua Memory Realloc Size Flamegraphs](https://github.com/apache/apisix/assets/148939043/eabc4e07-a5bd-4fcb-96e1-731a598e4386)
![8_GC Object Reference Flame Graph](https://github.com/apache/apisix/assets/148939043/446898eb-7515-44da-89f3-32e8bd984b4c)
<img width="582" alt="9_Application-Level Memory Usage Breakdown_10_25" src="https://github.com/apache/apisix/assets/148939043/f154bfdf-50b1-4477-b8ab-3ba073334ff7">
<img width="618" alt="10_Application-Level Memory Usage Breakdown_10_23 png" src="https://github.com/apache/apisix/assets/148939043/de1f0d15-baa6-499b-8274-8e30c240a1c5">

It cannot be used in the operating environment due to memory increase issues.
need another analyzer(openresty xray) to accurately identify this issues? Please advise.

### Environment

- APISIX version (run `apisix version`): 3.4.1
- Operating system (run `uname -a`): Linux 5.4.0-147-generic
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 3.0.1
- Plugin runner version, for issues related to plugin runners: java 0.4.0
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by shreemaan-abhishek** [comment]
cc: @Sn0rt

**Comment by Sn0rt** [comment]
Can you continue to observe? It is normal for the memory to grow when NGX is processing requests.

1. According to my understanding, OOM will occur at some point if the memory leak continues.
2. NGX has its own memory management mechanism. Use user mode to apply for a large amount of memory and NGX manages it by itself.

From the information in the picture, it is not possible to determine where the memory leak occurred.

**Comment by channer99** [comment]
> Can you continue to observe? It is normal for the memory to grow when NGX is processing requests.
> 
> 1. According to my understanding, OOM will occur at some point if the memory leak continues.
> 2. NGX has its own memory management mechanism. Use user mode to apply for a large amount of memory and NGX manages it by itself.
> 
> From the information in the picture, it is not possible to determine where the memory leak occurred.

@Sn0rt 
Depending on the amount of user calls, the memory increased and decreased, gradually moving upwards (I had already experienced oom). After that, I used openresty xray to check for memory leaks. I don't think there's any point in continuing to watch anymore.

**Comment by Sn0rt** [comment]
If OOM does occur, it is necessary to check it.

**Comment by t2krew** [comment]
How's it going? I'm having the same problem.

**Comment by Sn0rt** [comment]
I can't detect any abnormalities in your xray analysis.

Some users have also reported https://github.com/apache/apisix/issues/10349 memory leaks before.

Combining your information, I very much suspect that the problem was introduced in 3.4; combined with the changelog, I guess it is caused by the modification of etcd. Can you help me test it? (I tried to reproduce it on centos but failed. )

Use the 3.3 etcd file to replace the 3.5 one. Take a look at `wget https://raw.githubusercontent.com/apache/apisix/release/3.3/apisix/core/config_etcd.lua`

**Comment by monkeyDluffy6017** [comment]
@channer99 Could you send these flame graphs to my email: liuwei@api7.ai, it's not very clear on the website.

**Comment by channer99** [comment]
> @channer99 Could you send these flame graphs to my email [monkeydluffy6017@gmail.com](mailto:monkeydluffy6017@gmail.com), it's not very clear on the website.


It doesn't seem to be visible when you click and check it on the web.
I think you can check it faster if you download the image and run the .svg file in your local environment.
@monkeyDluffy6017 thx!

**Comment by monkeyDluffy6017** [comment]
I didn't find the problem from your graphs, the memory has only increased by 100MB,  i think this is normal.
If you think there are some problems, from your graph, we can see that the memory allocated by lua growed the most, it may be a memory fragmentation issue
![image](https://github.com/apache/apisix/assets/9354193/b8270866-d73b-4ad8-9819-ea7f0983f655)

**Comment by channer99** [comment]
What do you think about this issue?
https://github.com/apache/apisix/issues/8461#issue-1478340806

**Comment by monkeyDluffy6017** [comment]
How about remove the ext-plugin and do a test?

**Comment by monkeyDluffy6017** [comment]
@channer99 Do you have any progress on this?

**Comment by king4sun** [comment]
I also meet this recently. My apisix app is eating memory slowly day by day. what I get from the metric monitor is a growing straight line. So please tell me is there a tool can get details please and thanks a lot.
![20231207-174147](https://github.com/apache/apisix/assets/12710166/2b6a6914-8f09-43fa-bf97-981ec3834c6d)

**Comment by wklken** [comment]
@monkeyDluffy6017 

I also met this issue, after deployed online for 2 weeks, we reschedule the pods, then got the chart below. from 3.7G to 6G.

the apisix version is 3.2.1

<img width="1543" alt="image" src="https://github.com/apache/apisix/assets/2002216/69bf2a34-a426-44b5-9a1a-a8b4a2f83bfe">

**Comment by monkeyDluffy6017** [comment]
We have located this problem: https://github.com/apache/apisix/pull/10614, it will affect all versions between 3.4.0 and 3.7.0

**Comment by wklken** [comment]
also affect 3.2.2; but we use 3.2.1.
I have some suspicion that it is caused by the prometheus plugin, is there any tool to analysis this, while we don't have xray

**Comment by monkeyDluffy6017** [comment]
I didn't find the pr in the version 3.2.2
![image](https://github.com/apache/apisix/assets/9354193/23af6202-0bc1-47cd-a110-a12ec31b96f9)

**Comment by wklken** [comment]
here: https://github.com/apache/apisix/blob/release/3.2/CHANGELOG.md#bugfix

<img width="618" alt="image" src="https://github.com/apache/apisix/assets/2002216/f8a7e596-38d4-4948-a059-b00635264ed2">

I think it should be merged into a PATCH version. We upgraded from 3.2.1 and downgraded because the bug #9951

**Comment by monkeyDluffy6017** [comment]
I think you are right, it will affect 3.2.2

**Comment by wklken** [comment]
> [@monkeyDluffy6017](https://github.com/monkeyDluffy6017)
> 
> I also met this issue, after deployed online for 2 weeks, we reschedule the pods, then got the chart below. from 3.7G to 6G.
> 
> We have no ext-plugins.
> 
> the apisix version is 3.2.1
> 
> <img alt="image" width="1543" src="https://private-user-images.githubusercontent.com/2002216/289010109-69bf2a34-a426-44b5-9a1a-a8b4a2f83bfe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI4NjMzMjUsIm5iZiI6MTc2Mjg2MzAyNSwicGF0aCI6Ii8yMDAyMjE2LzI4OTAxMDEwOS02OWJmMmEzNC1hNDI2LTQ0YjUtOWExYS1hOGI0YTJmODNiZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMTFUMTIxMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMyYWJkMzgzNTNmZjUyZGQ3OTM3NDk4Y2NhY2Q4MjZkM2U2NmIyNWFiM2EyYWM1MjExMjgzNjZkY2U1YTMxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PPuyaeGjaH_9Z2iI-axi1-C5srpNnd7yJUo1l18XGY0">

For anyone who met the same problem

you can try:

```
echo "" > *_access.log 
```

and see the memory usage.


It turns out it's the access.log/error.log max_kept/max_size cause the problem.
(max_kept=7, max_size=1G) and there are 14G log files in the pod.(about 4G page cache)

**Comment by shihuncl** [comment]
> > [@monkeyDluffy6017](https://github.com/monkeyDluffy6017)
> > I also met this issue, after deployed online for 2 weeks, we reschedule the pods, then got the chart below. from 3.7G to 6G.
> > We have no ext-plugins.
> > the apisix version is 3.2.1
> > <img alt="image" width="1543" src="https://private-user-images.githubusercontent.com/2002216/289010109-69bf2a34-a426-44b5-9a1a-a8b4a2f83bfe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjI4NjMzMjUsIm5iZiI6MTc2Mjg2MzAyNSwicGF0aCI6Ii8yMDAyMjE2LzI4OTAxMDEwOS02OWJmMmEzNC1hNDI2LTQ0YjUtOWExYS1hOGI0YTJmODNiZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTExMTFUMTIxMDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMyYWJkMzgzNTNmZjUyZGQ3OTM3NDk4Y2NhY2Q4MjZkM2U2NmIyNWFiM2EyYWM1MjExMjgzNjZkY2U1YTMxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PPuyaeGjaH_9Z2iI-axi1-C5srpNnd7yJUo1l18XGY0">
> 
> For anyone who met the same problem
> 
> you can try:
> 
> ```
> echo "" > *_access.log 
> ```
> 
> and see the memory usage.
> 
> It turns out it's the access.log/error.log max_kept/max_size cause the problem. (max_kept=7, max_size=1G) and there are 14G log files in the pod.(about 4G page cache)

hello,I've encountered the same problem, and I've always solved it by restarting. How did you resolve it?
