### ISSUE TITLE
feat: As a user, I want to use docker secrets (files) as apikeys

### ISSUE THREAD

**Issue by jonathan-dev** [apache/apisix#10390]
### Description

I am using docker for deployment which has the docker secrets for the management of secrets.
The secrets are stored in a file like for example `/run/secrets/password`.
I want to be able to use docker secrets to mage the API keys which are set in the `config.yaml` file.
But I only have seen the option to reference environment variables in that file not files.
So would the recommended way to use the docker secrets be to have an additional script which reads the secrets files to environment variables or is there another maybe more elegant solution?

**Comment by monkeyDluffy6017** [comment]
Why don't you read the data from `/run/secrets/password` to env before starting APISIX
