### ISSUE TITLE
help request: websocket - upstream not support upgrade

### ISSUE THREAD

**Issue by hxhieu** [apache/apisix#10406]
### Description

Hi,

I am trying and learning `apisix` and it seems I would need some help to understand it.
So far I have setup an Upstream
```
{
  "nodes": [
    {
      "host": "my-svc.my-ns",
      "port": 9999,
      "weight": 1
    }
  ],
  "type": "roundrobin",
  "scheme": "http"
}
```
And a Route
```
{
  "uri": "/my-test",
  "methods": [
    "POST",
    "GET"
  ],
  "upstream_id": "484497030622741383", // Is the above Upstream
  "enable_websocket": true,
  "status": 1
}
```
HTTP is fine and the Route is working, but the issue is my upstream does not support websocket upgrade call i.e. if the gateway send `GET /my-test` to upstream for the upgrade, it will fail because my upstream does not allow `GET` method.

Also, if I Postman websocket directly to the upstream, then it works.

Did I miss something or is there a plugin that does the upgrade in between, before sending the actual websocket connection to my upstream?

Thanks!

### Environment

- APISIX version `/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version 3.6.0`
- Operating system `Linux apisix-7c94449b58-jgqhp 6.2.16-12-pve #1 SMP PREEMPT_DYNAMIC PMX 6.2.16-12 (2023-09-04T13:21Z) x86_64 GNU/Linux`
- OpenResty / Nginx version `nginx version: openresty/1.21.4.2`
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners: `Fresh no plugins`
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> it will fail because my upstream does not allow GET method.

Then don't use GET method. Doesn't that work? Am I missing something?

**Comment by hxhieu** [comment]
Thanks and it turns out to be my setup. I had a proxy in front if apisix as well. Its fine after I remove the proxy
