### ISSUE TITLE
Casbin: Error loading model and policy

### ISSUE THREAD

**Issue by satishviswanathan** [apache/apisix#10408]
### Description

**Casbin auth configuration**

![image](https://github.com/apache/apisix/assets/17437409/ae80545d-3d81-4f04-967a-744069e297aa)

**Error**
![image](https://github.com/apache/apisix/assets/17437409/c9f018c3-287f-4427-8d37-58ad9fab774a)

**Environment**
![image](https://github.com/apache/apisix/assets/17437409/73142d20-aae8-4f55-a819-d8798372cbe9)

### Environment

apisix version - 3.6.0
OS : wsl container
etcd version, 3.5.7
apisix-dashboard version, if have: 3.0.1

**Comment by shreemaan-abhishek** [comment]
Could you please share the plugin configuration here?

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek  thank you for your response. I'm still relatively and trying to figure out overall how it works.

I used the following curl command to create a route.

```
curl "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

Used the following to test the route.

` curl -i -X GET "http://127.0.0.1:9080/anything/foo?arg=10" -H "Host: example.com" `

**Following are the plugins in my config.yml file.**
To the existing plugin list I have added authz-casbin and authz-casdoor

 ```
plugins:                          # plugin list (sorted in alphabetical order)
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  # - dubbo-proxy
  - echo
  # - error-log-logger
  # - example-plugin
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  # - log-rotate
  # - node-status
  - openid-connect
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  # - skywalking
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - server-info
  - traffic-split
  - authz-casbin
  - authz-casdoor
```

Casbin model and policy used.


[policy.csv](https://github.com/apache/apisix/files/13242496/policy.csv)

model.conf (unable to upload this file so sharing the code here)

```
[request_definition]
r = sub, obj, act

[policy_definition]
p = sub, obj, act

[role_definition]
g = _, _

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = (g(r.sub, p.sub) || keyMatch(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)
```

The part I'm struggling to figure out is where to place the policy and model files so that apisix can load it

**Comment by shreemaan-abhishek** [comment]
I am not sure but you might have to upload the model.conf to the casbin service/docker container. In the route configuration that you shared, you aren't even using the plugin.

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek  the plugin I'm using is "authz-casbin".

_"I am not sure but you might have to upload the model.conf to the casbin service/docker container"_

can you provide some directions on how to do this ?

**Comment by shreemaan-abhishek** [comment]
> can you provide some directions on how to do this ?

You can refer casbin documentation, even I am not familiar with casbin.

**Comment by shreemaan-abhishek** [comment]
> @shreemaan-abhishek the plugin I'm using is "authz-casbin".

But you haven't configured that in the route. 
<img width="590" alt="image" src="https://github.com/apache/apisix/assets/61597896/4a4211fc-891a-453f-9bf5-9b710c7fc0c6">

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek  thank you for your responses.

_I believe this is a global configuration for all the routes which says apply this policy for all routes_ 

![image](https://github.com/apache/apisix/assets/17437409/78c97f72-6dd0-483d-873f-cb4687f15cf4)

_The highlighted path seems to be a relative path but not sure where that is meant to be._

![image](https://github.com/apache/apisix/assets/17437409/03a39697-7fa8-4082-b1fa-14a8694f4703)

_The following indicates an attempt to load the policies while invoking the route but couldn't resolve the path_

![image](https://github.com/apache/apisix/assets/17437409/a404bfd5-a2d4-46a1-93fc-edffbcffe9b8)

**Comment by shreemaan-abhishek** [comment]
@satishviswanathan, my bad I got confused with cas-auth plugin.

Could you try using absolute path for model and policy?

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek no worries.

I clone this repo and initialized the docker using docker-compose.yml under the example folder.


![image](https://github.com/apache/apisix/assets/17437409/c1067227-a91c-42cb-b0d6-b1d16f759dd4)

 I had also updated the dashboard config under the  path example\dashboard_conf
 
As of now I have the model and policy under the example folder and also tried dropping under the path example\dashboard_conf.


And then as you mentioned tried updating the relative path as follows.

![image](https://github.com/apache/apisix/assets/17437409/a4547c73-4534-4713-81d3-dbe14dcd2df3)


{
  "_meta": {
    "disable": false
  },
  "model_path": "./model.conf",
  "policy_path": "./policy.csv",
  "username": "APP-User-Id"
}
 
Seems like the way I'm setting the relative path is wrong. Any suggestions what that path would look like?

**Comment by shreemaan-abhishek** [comment]
try using absolute path

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek in the Plugin editor for casbin I have given the relative path. Do you see any issue with what I have given ?

**Comment by shreemaan-abhishek** [comment]
I am not sure what it the issue with your setup. If you use relative path, make sure the target file's location is correct relative to the dashboard's location. Btw, I am not much familiar with the dashboard project and where it would look for your `conf` files.

And why are you reluctant towards using absolute path??

**Comment by satishviswanathan** [comment]
I'm using the relative path as shown below but relative to which location was my question, is it relative to apisix or dashboard. I tried dropped the files in apisix as well as dashboard but it's not picking up.

"model_path": "./model.conf",
"policy_path": "./policy.csv",

**Comment by satishviswanathan** [comment]
@shreemaan-abhishek - That is relative path you were asking about right ? Just making sure that I got your question right.

**Comment by monkeyDluffy6017** [comment]
@satishviswanathan have you solved this problem?

**Comment by satishviswanathan** [comment]
@monkeyDluffy6017 - thank you for reaching out. No this is still an issue for me.

**Comment by satishviswanathan** [comment]
I got it working. Had to mount the folder which contains the policies in the docker compose file.

**Comment by monkeyDluffy6017** [comment]
considered resolved
