### ISSUE TITLE
help request: Using a proxy-rewrite plugin with similar routes

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10419]
### Description

Hello! I have 3 routes: 
`/api/*/test`
` /api/*/*/test
`
`/api/*`
` /api/*/*
`
These routes are tied to one upstream. I need to temporarily redirect to the same upstream, but to route `/api/mock/test`. At the same time, save requests via
 `/api/*/test`
` /api/*/*/test
`
`/api/*`
` /api/*/*
`
To do this, I use the proxy-rewrite plugin. When configuring it, I specify the URI and Method parameter.

During the implementation, I encountered such a problem. While proxy-rewrite plugins are not configured on routes, requests reach the correct endpoints. But when I configure the prixy-rewrite for each route, confusion begins. 

Example :
My request curl http://127.0.0.1:9080/api/5ad37ba4-d36b-4bfc-bdd9-d615739f0d3b/test reaches the endpoint intended for `/api/*/*` but should be directed to `/api/*/test`.  I tried to solve this problem and found such regularity . 

If the routes were created in this order:

` /api/*/*/test    route_id = 1
`
 `/api/*/test      route_id = 2`
 ` /api/*/*         route_id = 3
`
`/api/*           route_id = 4`

My queries reach the desired endpoints.

Please tell me how I can configure the plugin or my routes so that they lead to the specified endpoints?

### Environment

- APISIX version 3.5.0-debian
- etcd version etcd:3.4.15
- APISIX Dashboard version 3.0.1-alpine

**Comment by shreemaan-abhishek** [comment]
Don't you think that according to regex, the URI `/api/*` will match (supersede) all of these: `/api/*/*/test`, `/api/*/test`, `/api/*/*`.

So the route matching wouldn't work as intended at the first place.

**Comment by pavlenkodev** [comment]
> Вам не кажется, что согласно регулярному выражению URI `/api/*`будет соответствовать (заменять) все это: `/api/*/*/test`, `/api/*/test`, `/api/*/*`.
> 
> Таким образом, сопоставление маршрутов изначально не будет работать так, как предполагалось.

Yes, /api/* covers all other routes, but in my situation it is necessary to have a proxy-rewrite on each of the routes, because redirection occurs on `/api/mock/test/1`, `/api/mock/test/2` etc. Each route will have its own forwarding address. I forgot to mention this in the description, sorry.

I suppose I should use priorities, or create routes in a certain order
