### ISSUE TITLE
help request: Can anyone provide an apisix example for the strimzi kafka

### ISSUE THREAD

**Issue by yanmxa** [apache/apisix#10412]
### Description

Recently, I have considered using APISIX to control Kafka authentication and authorization management, and I saw APISIX. However, I can't easily find an example of integrating APISIX with Kafka. Can anyone provide an example of how to use it? Also, It would be better to enable the go plugin with the example!

Thanks!

Note: [strimzi kafka](https://github.com/strimzi/strimzi-kafka-operator)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
I haven't worked with kafka in the past but I see there are two related resources:

- https://apisix.apache.org/docs/apisix/pubsub/kafka/
- https://apisix.apache.org/docs/apisix/plugins/kafka-proxy/

**Comment by yanmxa** [comment]
Thanks @shreemaan-abhishek! 
After a few days of trying, I summarized a roadmap to proxy Kafka using the APISIX and also made a plugin for certificate validation for Kafka.

- Document: https://github.com/yanmxa/gateway-playground/blob/main/apisix-kafka-bridge.md

**Comment by shreemaan-abhishek** [comment]
would you like to contribute this as a blog to the apisix website?

cc: @pottekkat

**Comment by yanmxa** [comment]
Sure! I can refine it a little later. Currently this is just a process I recorded myself. You can make some comments based on it.

**Comment by pottekkat** [comment]
@yanmxa That sounds good. I will take a look tomorrow.

**Comment by pottekkat** [comment]
@yanmxa I had a chance to review it. You can convert it to a blog post and mention what you are trying to achieve and how you are doing it. Linking to a repo with the configuration/manifest files will also be good so that readers can easily reproduce it. You can open a PR in the apisix-website repo adding a new file here: https://github.com/apache/apisix-website/tree/master/blog/en/blog/2023

Please let me know if you need help. I can review your draft post and suggest edits.
