### ISSUE TITLE
help request: Installing some commands requires root privileges

### ISSUE THREAD

**Issue by liangpeihuahua** [apache/apisix#10424]
### Description

Installing some commands requires root privileges
![image](https://github.com/apache/apisix/assets/118984957/a90c1188-c653-40b3-8671-b305422df4f6)
Need to know the password for apisix to switch root

### Environment

APISIX version (run apisix version):$ apisix version
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version
3.2.0

Operating system (run uname -a):$ uname -r
5.4.241-150.347.amzn2.x86_64
$ uname -a
Linux apisix-6bb954b88d-4k2w9 5.4.241-150.347.amzn2.x86_64 https://github.com/apache/apisix/pull/1 SMP Mon Apr 24 23:27:26 UTC 2023 x86_64 GNU/Linux

OpenResty / Nginx version (run openresty -V or nginx -V):$ nginx -V
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1s 1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.7 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.XAafuZTCsa/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):

APISIX Dashboard version, if relevant:

Plugin runner version, for issues related to plugin runners:

LuaRocks version, for installation issues (run luarocks --version):

**Comment by Revolyssup** [comment]
@liangpeihuahua What are you trying to install? It looks like the "apisix" user has been configured with limited permissions.It doesn't look like it has anything to do with APISIX.

**Comment by liangpeihuahua** [comment]
Yes, this is the permission set for the apisix user, so I want to know the password for the apisix user to switch to the root user, because in old versions of apisix, such as version 2.5, the initial user is root

**Comment by Revolyssup** [comment]
@liangpeihuahua Which installation steps did you follow?

**Comment by liangpeihuahua** [comment]
a. 3.2 version（Upgraded version）
apk add procps
apt-get install procps
![image](https://github.com/apache/apisix/assets/118984957/0e84b621-6b8d-4492-8c76-302571124edb)

b. 2.5 version（old version）

![image](https://github.com/apache/apisix/assets/118984957/a9aa0ed6-fa17-40e4-98c9-b4f09c764e23)

**Comment by liangpeihuahua** [comment]
so I want to know the password for the apisix user to switch to the root user

**Comment by liangpeihuahua** [comment]
I deployed it using helm and deployed it in the k8s pod. The developer has already packaged the image, including the password of the root user. So I would like to ask if any students know what the password of the root packaged by the developer is. It cannot be changed directly on the server.

**Comment by Revolyssup** [comment]
@liangpeihuahua Inside the container there are limited permissions as the packages required are already installed https://github.com/apache/apisix-docker/blob/bf08d86aad95859e010a2cede7f5c697a3f71e2e/debian/Dockerfile#L54
Why do you need to install that package?

**Comment by liangpeihuahua** [comment]
Because I need to check the command through processes such as ps to see if my custom plug-in is running normally.

**Comment by shreemaan-abhishek** [comment]
There is also another docker image [debian-dev](https://github.com/apache/apisix-docker/tree/master/debian-dev), is there a flag in helm chart that enables usage of dev image?

**Comment by liangpeihuahua** [comment]
is allowed. But it is much more convenient for me to know the root user password.

**Comment by shreemaan-abhishek** [comment]
you cannot log in as a root user due to the way the docker image is created:

https://github.com/apache/apisix-docker/blob/bf08d86aad95859e010a2cede7f5c697a3f71e2e/debian/Dockerfile#L54C1-L56C48

**Comment by kayx23** [comment]
> Because I need to check the command through processes such as ps to see if my custom plug-in is running normally.

@liangpeihuahua try `docker top`, or build a custom image and include `RUN apt-get update && apt-get install procps`.
