### ISSUE TITLE
help request: Why did it happen  apisix_latency >  upstream_latency ？

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10423]
### Description

Why did it happen  apisix_latency >  upstream_latency ？

![1698731944680](https://github.com/apache/apisix/assets/44867235/5e55fa7f-2c42-455d-982c-65f0480d2727)

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@qyk1995 apisix_latency == (request_time - upstream_response_time) == (downstream trafffic latency + nginx latency)

**Comment by qyk1995** [comment]
@Revolyssup  I don't quite understand what you have to do with the question I asked?

**Comment by qyk1995** [comment]
downstream traffic latency   is  client  to apisix   latency ?

**Comment by Revolyssup** [comment]
> downstream traffic latency is client to apisix latency ?

yes

**Comment by qyk1995** [comment]
@Revolyssup  thank you. I  will check  problem  again.
