### ISSUE TITLE
Is the apisix support preStop hook? for graceful shutdown

### ISSUE THREAD

**Issue by wklken** [apache/apisix#10437]
### Description

The kong and nginx support preStop in lifecycle

https://github.com/Kong/charts/blob/d760a065d768c5465de1856671a11ee198d546eb/charts/kong/values.yaml#L842-L854

https://github.com/kubernetes/ingress-nginx/blob/main/deploy/static/provider/cloud/deploy.yaml#L447-L451

and set the `terminationGracePeriodSeconds` for rolling update in k8s

-----

I wonder is the apisix pod terminated by k8s is graceful? it's ok only to set `terminationGracePeriodSeconds`? 

if we really need a `preStop` script?

**Comment by wklken** [comment]
apisix has `quit` for graceful shutdown, so, should we use it in `preStop`, or just wait for the `TERM` signal?

**Comment by wklken** [comment]
For a graceful shutdown of apisix on k8s (zero downtime deployment):

- You should add the `readinessProbe` to inform k8s when apisix is ready. For example: https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L194 ;
- The default nginx_config of apisix is `worker_shutdown_timeout: 240s`. Therefore, the maximum timeout of your routes should be less than `240s`, unless you change this configuration;
- `terminationGracePeriodSeconds` should be equivalent (or bigger than) to the maximum timeout of your routes, such as `terminationGracePeriodSeconds: 300`.
- `apisix` should be the `pid=1` process in the container. Otherwise, it should be the last `hang` process of your bash script in the command. This implies that if apisix quits, the pid=1 script will also quit. This make the pod terminated immediately if the apisix being gracefully stopped, otherwise it will wait for `terminationGracePeriodSeconds`, the process of program rolling update takes a very long time;
- You should add a `preStop` command like `sleep 15 && apisix quit` (ensure that `terminationGracePeriodSeconds >= 15 + apisix quit duration`). The `sleep 15` allows k8s to have sufficient time to remove the endpoint of the pod, while `apisix quit` attempts to gracefully stop the apisix server;
- The rolling update strategy should set `maxUnavailable` to `0`. In other words, one pod becomes ready, then one pod is terminated. (The default for `maxSurge` is 25%, but you can modify it based on your resources, like the CPU/memory of your cluster or the load of etcd.)


Otherwise, the user will receive some `502` errors from the terminating pod!

btw: if you enable the `websocket`, you should use other plan, previous settings is not ok for `websocket`.

----

The apisix helm chart should include documentation on this topic.

Also, it may be beneficial for apisix to support `quit` arguments like `kong quit --wait 15 --timeout 240`, in order to simplify and clarify the `preStop` process.

----

**Comment by wklken** [comment]
rules: 
> route maximum timeout < worker_shutdown_timeout(default 240s) < terminationGracePeriodSeconds(default 30s, should be changed!!!)

> preStop(sleep 15 && apisix quit) + worker_shutdown_timeout < terminationGracePeriodSeconds

**Comment by shreemaan-abhishek** [comment]
> The apisix helm chart should include documentation on this topic.

Would you like to raise a PR?

**Comment by wklken** [comment]
I'm still testing the settings, it works but still not 100% sure about each configuration, like how the apisix handle signal `TERM`, is the `preStop` really required? Once all these issues are confirmed, I think I can make a pr for the docs.

**Comment by monkeyDluffy6017** [comment]
considered resolved
