### ISSUE TITLE
bug: "prefer_name" setting for prometheus is not working 

### ISSUE THREAD

**Issue by jzhao20230918** [apache/apisix#10435]
### Current Behavior

hello,

I have config set as:

plugin_attr:
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091
    prefer_name: true

![1698919394253](https://github.com/apache/apisix/assets/145320661/246b963b-e0f1-4a53-8462-ecab7a54d001)

the "service" and "route" field are still in the ID format. Did I miss anything?

Thanks a lot.

### Steps to Reproduce

1. set "prefer_name" to true
2. set up service and route
3. check prometheus metrics

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jzhao20230918** [comment]
![1698919595057](https://github.com/apache/apisix/assets/145320661/2666869a-5bcc-4e3a-a4cd-025ef58e3cb6)

**Comment by jzhao20230918** [comment]
version 3.6.0

**Comment by kayx23** [comment]
I believe you configured it in the wrong place. `prefer_name` should be configured on the APISIX resource (e.g. route, global rule) like this:

```shell
...
    "plugins": {
        "prometheus":{
             "prefer_name": "true"
        }
    },
...
```

And not in `config.yaml`.

**Comment by jzhao20230918** [comment]
working now, thank you.
