### ISSUE TITLE
help request: The apisix upstream address is the k8s servicename domain, and it will always be 504 after the pod is restarted.

### ISSUE THREAD

**Issue by god12311** [apache/apisix#10432]
### Description

APISIX is deployed in Kubernetes via Helm and acts as a proxy to access pod services within Kubernetes. All upstream addresses are specified as service (svc) name addresses.

Issue:
1. When pods restart or are updated, continuous access requests may result in 502 or 504 errors after the pod restarts. If the access is not interrupted, the errors will persist.

route config:
{
  "uri": "/*",
  "name": "a.xxx.com",
  "desc": "route xxxx",
  "host": "a.xxx.com",
  "plugins": {
    "prometheus": {
      "prefer_name": true
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "xxxx-test1-service.xxx.svc.cluster.local:8080": 1
    }
}

When the pod restarts or the entire publishing process is ongoing, use this command to continuously access.
for i in `seq 1 10000`;do sleep 0.1;curl -X GET -I http://a.xxx.com;done

After a normal rolling restart of the pod, requests will result in a 502 error. After a certain timeout, a 504 error will appear. If the continuous access command mentioned above is not stopped, the domain access will remain in a 502 or 504 state.

HTTP/1.1 502 Bad Gateway
Server: nginx
Date: Thu, 02 Nov 2023 02:04:12 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 229
Connection: keep-alive
X-APISIX-Upstream-Status: 502

HTTP/1.1 504 Gateway Time-out
Server: nginx
Date: Wed, 01 Nov 2023 11:18:37 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 239
Connection: keep-alive
X-APISIX-Upstream-Status: 504

### Environment

- APISIX version (run `apisix version`): 3.2.0  By helm  chartversion 1.3.1
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.9
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
can you try to check if this exists in latest version?

**Comment by iarno** [comment]
I also encountered the same problem, the apisix version is 2.15.0

**Comment by iarno** [comment]
> I also encountered the same problem, the apisix version is 2.15.0

The default connection pool used by routing. There will be some http 504 error codes after the pod is restarted.

**Comment by monkeyDluffy6017** [comment]
@Revolyssup please help to check

**Comment by Vacant2333** [comment]
@shreemaan-abhishek can u help me assign this issue to me, i will go take it

**Comment by Vacant2333** [comment]
how many node do u have? can u provide more infomation to reproduce this issue

**Comment by Vacant2333** [comment]
i cant reproduce this bug on my enviorment, i creat 3 nodes cluster by kind, and install APISIX 3.2.0, then install nginx for the upstream, when i restart the nginx deployment, the state code will always be `200`
![image](https://github.com/apache/apisix/assets/19872346/52ca297a-959c-45fb-a091-d5943ebbb431)

**Comment by Vacant2333** [comment]
@iarno hello, can u help me to reproduce this problem, i have try on APISIX 2.15.0, it works well

**Comment by iarno** [comment]
> @iarno你好，你能帮我重现这个问题吗？我已经尝试过 APISIX 2.15.0，效果很好

@Vacant2333 Stress testing is required. QPS is around 10k+. There will be a small amount of 504 when restarting the k8s upstream pod. The upstream address uses lvs ip, the lvs mode is DR, and the upstream connection pool uses the default value.

**Comment by Vacant2333** [comment]
I think in the case of reporter, there is no use of lvs, and there are a large number of 504s (through curl+sleep) when QPS is very low. @god12311  is that right?
