### ISSUE TITLE
help request: How to replace the apisix server image

### ISSUE THREAD

**Issue by yanmxa** [apache/apisix#10438]
### Description

I have rebuilt the apisix image with a customized plugin. And then I try to install the apisix gateway on Openshift by helm. But I haven't found a way to modify the image. Anyone know how to do that?
```bash
helm install apisix apisix/apisix \
  --set gateway.type=NodePort \
  --set etcd.podSecurityContext.enabled=false \
  --set etcd.containerSecurityContext.enabled=false \
  --set serviceAccount.name=apisix-sa
```
Is there a flag like `--set deployment.apisix.image=<new-image>`?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
This might be of help: https://apisix.apache.org/docs/ingress-controller/tutorials/using-custom-plugins/

**Comment by shreemaan-abhishek** [comment]
Please reopen if your issue hasn't been resolved.
