### ISSUE TITLE
help request: Can not disable plugin.（插件禁用功能无效）

### ISSUE THREAD

**Issue by caojianfei** [apache/apisix#10442]
### Description

I use docker to test apisix, the repo is https://github.com/apache/apisix-docker, and the branch  i used is release/apisix-2.15.3.
My route info is:
```
{
  "uri": "/get",
  "name": "httpbin",
  "methods": [
    "GET"
  ],
  "plugins": {
    "response-rewrite": {
      "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
      "disable": true
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.org",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "node",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```
You can see the config of plugin response-rewrite , the disable option is true, but `response-rewrite` is still in effect.The same thing happens with other plugins.

Why this happens? Is that a bug or some other reason?

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):  Linux 3896876634d0 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"hostname":"3896876634d0","id":"e80d7802-5553-45a1-9813-8a3bf443b7a6","boot_time":1699001562,"etcd_version":"3.4.0","version":"2.15.1"}
- APISIX Dashboard version, if relevant: 2.13
- Plugin runner version, for issues related to plugin runners: no 
- LuaRocks version, for installation issues (run `luarocks --version`): no

**Comment by shreemaan-abhishek** [comment]
There might be another route that uses this plugin that is coming into effect.

**Comment by kayx23** [comment]
It should be inside `_meta`:

```
    "response-rewrite": {
      "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
      "_meta": { "disable": true }
    }
```

See https://docs.api7.ai/apisix/reference/plugin-common-configurations#_metadisable
