### ISSUE TITLE
Is there a way know the updated staus of Service via Service Discovery

### ISSUE THREAD

**Issue by jzhao20230918** [apache/apisix#10448]
### Description

Hello,

I added a service by Consul using service name only. Is there a way I can know more info or the current status of the service, e.g. service instance address, service status (down/up), etc. 

Thanks, 

### Environment

- APISIX version (run `apisix version`): 3.6
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: latest
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
the service discovery modules doesn't export any such features.

**Comment by luoluoyuyu** [comment]
Hi, @jzhao20230918 
apisix does not expose service discovery information to the public, but you can use the consul cli to get service discovery information: https://developer.hashicorp.com/consul/commands?product_intent=consul

**Comment by shreemaan-abhishek** [comment]
please reopen if you have more questions thanks.
