### ISSUE TITLE
help request: apisix java run plugin must use jdk11 ？

### ISSUE THREAD

**Issue by ttpaigesheng** [apache/apisix#10459]
### Description

启动java runner plugin 时 报如下错误
Caused by: java.lang.UnsupportedClassVersionError: org/apache/apisix/plugin/runner/configuration/A6HandlerConfiguration has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
初步看是由于  jdk版本不一致导致的

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ttpaigesheng** [comment]
<dependencies>
        <dependency>
            <groupId>org.apache.apisix</groupId>
            <artifactId>apisix-runner-starter</artifactId>
            <version>0.4.0</version>
        </dependency>
    </dependencies>

**Comment by shreemaan-abhishek** [comment]
yes: https://github.com/apache/apisix-java-plugin-runner/blob/8afa49e541b774c8e53917aa6d1d83eea6492eef/pom.xml#L59
