### ISSUE TITLE
help request: apisix wants to support proxy_next_upstream error timeout http_404

### ISSUE THREAD

**Issue by yuqiquan** [apache/apisix#10457]
### Description

I want to use apisix to implement proxy_next_upstream error timeout http_404 nginx configuration, that is, when the upstream status code is 404, retry to the next upstream. How to achieve this. Any good ideas?

### Environment

- APISIX version (run `apisix version`): 2.15.0

**Comment by shreemaan-abhishek** [comment]
There is already a retry mechanism:
<img width="826" alt="image" src="https://github.com/apache/apisix/assets/61597896/eedcddc6-9301-49db-838b-a5854069d79b">

https://github.com/shreemaan-abhishek/apisix/blob/105993f40f34768cd0a86035d01393346fff3a94/apisix/balancer.lua#L167-L177

But it doesn't support fine grain control.

**Comment by yuqiquan** [comment]
是的  但是这个重试机制好像只有在上游机器故障挂掉或者是超时时候才会进行重试

当上游机器正常，不管返回的状态码是什么，即使是5XX，重试机制都不会被触发，我觉得业务上有很多的要求都是要满足   proxy_next_upstream 这一个命令的 

健康检查只有在访问以后，才会把异常状态码的上游剔除，无法满足这一个要求

**Comment by yuqiquan** [comment]
Hope ngx.balancer add new function to  proxy_next_upstream
