### ISSUE TITLE
bug:  My opinion on this open source project

### ISSUE THREAD

**Issue by whatbug** [apache/apisix#10452]
### Current Behavior

Before, it could still be used normally when there was no commercialization, but now it is still covered with the skin of Apache, which is not only shameful. Now there are hundreds of fucking issues that have not been handled yet. Take a look at the 33k stars of the Kong gateway, which is a gap. I estimate many people who followed this project were very optimistic at the beginning, but now they are going further and further against their original intention. Don't they feel ashamed?

### Steps to Reproduce

1. bug
2. bug
3. many bug on the way.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
I'm the PMC chair for Apache APISIX and I'm not ashamed of it.
APISIX is a community-maintained open source project, and you can't rely on the community to solve your problems. Remember, you are the one asking for help. You should be grateful if others help you, and don't complain if they don't help you.
You are the one who should be ashamed, speaking in public using bad language.
You are welcome to use any other open source project, it is your freedom. But you are not welcome in the APISIX community, please stay away from us.

**Comment by monkeyDluffy6017** [comment]
Everyone should be the owner of the opensource. Participate in it, contribute to it, not just ask for it
