### ISSUE TITLE
help request: cannot use traditional mode with apisix.yaml configuration

### ISSUE THREAD

**Issue by yazebochan** [apache/apisix#10468]
### Description

I have traditional mode exactly copied from your github examples. I mean apisix.yaml and config.yaml files. But i can't force apisix read or process apisix.yaml file -- there are no routes active from that file. But Rest API works well -- routes created succesfully. Please help me

### Environment

- APISIX version (run :`apisix version`): 3.6.0-debian
- Operating system (run `uname -a`): Docker-compose file version 3
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.15
- APISIX Dashboard version, if relevant:3.0.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
traditional mode won't read configurations from apisix.yaml. The Admin API is to be used

**Comment by yazebochan** [comment]
how can i use both of them in 1 docker instance?

**Comment by yazebochan** [comment]
how can i use both of them in 1 instance?

**Comment by yazebochan** [comment]
@shreemaan-abhishek how can i use both of them in 1 docker compose instance

**Comment by shreemaan-abhishek** [comment]
both of what? Both deployment modes? You can't do that.

Only one deployment mode can be used at once.

**Comment by yazebochan** [comment]
got it. Another question -- how can i use anchors whatever in your yaml files? Or maybe what copying mechanism do you use?

**Comment by kayx23** [comment]
What do you mean by anchors?
