### ISSUE TITLE
bug: After using the mocking plugin in the route, the ip-restriction plugin is not effective.

### ISSUE THREAD

**Issue by guankai** [apache/apisix#10466]
### Current Behavior

apisix version 3.2
After using the mocking plugin in the route, the ip-restriction plugin is not effective.

### Steps to Reproduce

1. create a route with admin api.
2. add ip-restriction plugin on this route , it is effective.
3. add mocking plugin on this route, the ip-restriction plugin will not effective.

### Environment

apisix version 3.2

**Comment by shreemaan-abhishek** [comment]
This is an expected behaviour, the mocking plugin executes before ip-restriction (as it has a higher priority) and then closes the request. However you can change the priority of the plugins execution order: https://docs.api7.ai/apisix/reference/plugin-common-configurations#_metapriority

**Comment by guankai** [comment]
> This is an expected behaviour, the mocking plugin executes before ip-restriction (as it has a higher priority) and then closes the request. However you can change the priority of the plugins execution order: https://docs.api7.ai/apisix/reference/plugin-common-configurations#_metapriority

got it ,thank you
