### ISSUE TITLE
help request: How can I configure different nginx parameters based on different routes or hosts？

### ISSUE THREAD

**Issue by oubeichen** [apache/apisix#10465]
### Description

How can I configure different nginx parameters based on different routes or hosts, such as [ssl_buffer_size](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_buffer_size) and [proxy_buffering](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering)? 
These parameters are originally located inside the server or location blocks in the nginx configuration. 

However, I noticed in the apisix documentation (https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md) that it only supports global configuration.

Based on the currently available plugins, there doesn't seem to be a way to modify these parameters. 
Manually modifying the generated nginx configuration file seems to be a workaround, but it becomes cumbersome since it gets overwritten by apisix every time.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
nginx configuration is generated and then loaded when apisix starts and hence cannot be changed. Or needs to be restarted after changing the configuration. Dyanamic modification of nginx conf seems troublesome.

> How can I configure different nginx parameters based on different routes or hosts, such as [ssl_buffer_size](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_buffer_size) and [proxy_buffering](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering)?

What is your use case?

**Comment by oubeichen** [comment]
> nginx configuration is generated and then loaded when apisix starts and hence cannot be changed. Or needs to be restarted after changing the configuration. Dyanamic modification of nginx conf seems troublesome.
> 
> > How can I configure different nginx parameters based on different routes or hosts, such as [ssl_buffer_size](https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_buffer_size) and [proxy_buffering](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering)?
> 
> What is your use case?

Our project is deployed on Kubernetes using apisix ingress controller. 
Most of the services are REST-based web services, so the default configuration and plugins provided by apisix are sufficient. 
However, for a few services that provide live streaming, video streaming, or large file transfer, we need to disable ngx_http_proxy or modify ssl_buffer_size. 
We found that Nginx ingress controller can modify specific nginx parameters through annotations. 
However, apisix only provides a method to configure plugins and cannot directly modify the corresponding nginx parameters. 
But we don't want to use Nginx ingress controller as it would be a step backwards, wouldn't it?

**Comment by shreemaan-abhishek** [comment]
I'm not sure if this is yet supported, but there is an apisix plugin, did you see if it fits your need? https://apisix.apache.org/docs/apisix/plugins/proxy-control/

**Comment by kayx23** [comment]
There is a plugin to update the `proxy_buffering` directive at runtime and on a resource scale, but it's an enterprise feature atm: https://docs.api7.ai/hub/proxy-buffering

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
