### ISSUE TITLE
help request: when I use apisix proxy grpc services, why apisix return http_200 to client whatever grpc server returned?

### ISSUE THREAD

**Issue by wangkpot** [apache/apisix#10462]
### Description

such as  grpc server return code.InvalidArgument(3)，apisix will return http_200 to client.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Could you please share how this scenario can be reproduced?

**Comment by monkeyDluffy6017** [comment]
I will close this issue due to long period of no response, feel free to reopen it
