### ISSUE TITLE
feat:  body-transformer enhancement

### ISSUE THREAD

**Issue by yongxiaodong** [apache/apisix#10472]
#### 1、Backend returns gzip not supported
When the backend returns gzip data,  the decoding will be garbled.  i want to fix it

#### 2、Data using x-ww-form-urlencoded format is not supported
When the client sends a request format of x-www-form-urlencoded, Unable to parse parameter

#### 3、Parameter parsing and conversion of get requests are not supported
When the client sends a get request, Unable to parse parameter

### target
I want to add these features which are not supported right now
1. Support backend to return gzip data
2. Support the use of x-www-form-urlencoded format
3. Support the use of get requests

**Comment by shreemaan-abhishek** [comment]
could you please provide reproduction steps?

**Comment by shreemaan-abhishek** [comment]
Please provide steps to confirm if these features are missing.

**Comment by yongxiaodong** [comment]
> Please provide steps to confirm if these features are missing.

### example:
#### 1、Add routing based on body-transformer plugin. Modify the token field in the request to newtoken and the res field in the return to newres
```

	curl http://127.0.0.1:9180/apisix/admin/routes/test_ws \
		-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
	{
		"methods": ["POST","GET"],
		"uri": "/ws",
		"plugins": {
			"body-transformer": {
				"request": {
					"template": "{\"newtoken\": {{ token }}}"
					},
				"response": {
					"template": "{\"newres\": {{ res }}}"
					}	
			}
		},
		"upstream": {
			"type": "roundrobin",
			"nodes": {
				"192.168.14.254:5000": 1
			}
		}
	}'

```

### verify
#### 1. When the request method is post and the body type is json, it works normally. The upstream received ` {'newtoken': 123}`
```
curl --location '192.168.235.128:9080/ws?token=123' \
--header 'Content-Type: application/json' \
--data '{
    "token": 123
}'
```
#### 2. When the request method is post and the body type is x-www-form-data, it works abnormally. The upstream cannot receive ` {'newtoken': 123}`
```
curl --location '192.168.235.128:9080/ws?token=123' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'token=333'
```
#### 3.When the request method is get, the operation is abnormal. The upstream cannot receive ` {'newtoken': 123}`
```
curl --location '192.168.235.128:9080/ws?token=123'
```
#### 4. If the data content-type returned by the upstream service is: gzip, the response body cannot be modified
