### ISSUE TITLE
help request: update upstream error when use apisix-seed and nacos as service discovery

### ISSUE THREAD

**Issue by Monstergogo** [apache/apisix#10479]
### Description

I used nacos and apisix-seed as service discovery,  when apisix-seed rewrite upstream info to etcd, an error occurred in apisix:

[error] 51#51: *251621 [lua] config_etcd.lua:843: failed to fetch data from etcd: failed to check item data of [/apisix/upstreams] err:additional properties forbidden, found _discovery_type,  etcd key: /apisix/upstreams, context: ngx.timer

additional properties like _discovery_type is necessary to apisix-seed, this error caused apisix-seed not work. 
by the way, error will not occur when use apisix 3.5.0 and below version.

### Environment

- APISIX version (run `apisix version`): 3.6.0--debian
- Operating system (run `uname -a`): Apple M1 Pro
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4
- APISIX Dashboard version, if relevant: 3.0.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
- APISIX-SEED version:  0.1.0

**Comment by shreemaan-abhishek** [comment]
I'm not sure if apisix-seed is mature yet.

**Comment by monkeyDluffy6017** [comment]
@Monstergogo have you solved your problem?

**Comment by Monstergogo** [comment]
> @Monstergogo have you solved your problem?

no, I abandoned apisix-seed

**Comment by Monstergogo** [comment]
> @Monstergogo have you solved your problem?

ah, I abandoned apisix-seed

**Comment by monkeyDluffy6017** [comment]
@Monstergogo It's because this commit: https://github.com/apache/apisix/commit/a98f1ca7a4b368a5270c5cae2a2a526f21ba409a, apisix will not allow properties that not in schema any more
