### ISSUE TITLE
bug: when set upstream.tries = 0, the tcp passive health check will become invalid.

### ISSUE THREAD

**Issue by wangkpot** [apache/apisix#10488]
### Current Behavior

when set upstream.tries = 0, the tcp passive health check will become invalid.

### Expected Behavior

when set upstream.tries = 0, the tcp passive health check will not become invalid.

### Steps to Reproduce

Firstly，set upstream.tries = 0；Secondly，configuring passive health checks for route. Then you will find tcp passive health check will become invalid.

### Environment

- APISIX version (run `apisix version`):1.19.3
- Operating system (run `uname -a`):1.19.3
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please provide reproduction steps with the route/upstream configurations that you used.

**Comment by wangkpot** [comment]
> Please provide reproduction steps with the route/upstream configurations that you used.

upstream：
`{
		"scheme": "http",
		"hash_on": "vars",
		"pass_host": "pass",
		"checks": {
			"active": {
				"type": "tcp",
				"timeout": 1,
				"healthy": {
					"interval": 5,
					"successes": 2
				},
				"unhealthy": {
					"interval": 3,
					"tcp_failures": 6
				}
			},
			"passive": {
				"healthy": {
					"successes": 2
				},
				"type": "tcp",
				"unhealthy": {
					"tcp_failures": 2,
					"timeouts": 1
				}
			}
		},
		"retries": 0,
		"nodes": [
			{
				"port": 1111,
				"priority": 0,
				"host": "xx.xx.xx.xxx",
				"weight": 99
			},
			{
				"port": 2222,
				"priority": 0,
				"host": "xx.xx.xx.xxx",
				"weight": 99
			}
		],
		"name": "upstream00",
		"timeout": {
			"connect": 6,
			"read": 6,
			"send": 6
		},
		"type": "roundrobin",
		"id": "upstream00"
	}`
route:
`{
		"methods": [
			"GET",
			"POST",
			"HEAD"
		],
		"hosts": [
			"common.test.com"
		],
		"name": "common",
		"timeout": {
			"send": 6,
			"connect": 6,
			"read": 6
		},
		"priority": 0,
		"status": 1,
		"upstream_id": "upstream00",
		"id": "common",
		"uris": [
			"/*"
		]
	}`

**Comment by shreemaan-abhishek** [comment]
what made you think that the passive healthcheck failed, I could see the nodes marked as healthy. Did you notice any error logs? Am I missing something?

**Comment by wangkpot** [comment]
> what made you think that the passive healthcheck failed, I could see the nodes marked as healthy. Did you notice any error logs? Am I missing something?

The nodes in uptream are  unhealthy, unhealthy nodes will not be removed by tcp passive health checks. You can verify it.

**Comment by shreemaan-abhishek** [comment]
I tried again, I could see them become unhealthy.

**Comment by wangkpot** [comment]
> I tried again, I could see them become unhealthy.
If those node  become unhealthy after 18 seconds，that is because active healthcheck.

**Comment by wangkpot** [comment]
> I tried again, I could see them become unhealthy.

If those node become unhealthy after 18 seconds，that is because active healthcheck.

**Comment by shreemaan-abhishek** [comment]
> If those node become unhealthy after 18 seconds，that is because active healthcheck.

What does that mean? And what's your APISIX version?

**Comment by wangkpot** [comment]
> > If those node become unhealthy after 18 seconds，that is because active healthcheck.
> 
> What does that mean? And what's your APISIX version?

You could see them become unhealthy because active healthcheck marked those nonde as unhealthy, rather than passive healthcheck. My apisix version is 2.13.2.

**Comment by shreemaan-abhishek** [comment]
2.13.2 is too old, 3.2 is LTS and 3.6 is latest. Could you check if the recent versions have this problem?

**Comment by wangkpot** [comment]
> 2.13.2 is too old, 3.2 is LTS and 3.6 is latest. Could you check if the recent versions have this problem?

I think the latest code still has this problem. You can look at this line of code : https://github.com/apache/apisix/blob/5b7b1de1feeb9f6b5a57c93b13617d7f6dfa68c8/apisix/balancer.lua#L232C29-L232C47 .
Only when upstream can retry, tcp_failure will be reported.

**Comment by monkeyDluffy6017** [comment]
@wangkpot have you solved your problem?
