### ISSUE TITLE
bug: when set upstream.tries = 0, the tcp health check will become invalid.

### ISSUE THREAD

**Issue by wangkpot** [apache/apisix#10486]
### Current Behavior

when set upstream.tries = 0, the tcp health check will become invalid.

### Expected Behavior

when set upstream.tries = 0, the tcp health check still valid.

### Steps to Reproduce

when set upstream.tries = 0, the tcp health check will become invalid.

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`):1.19.3
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Could you please provide reproduction steps?

**Comment by wangkpot** [comment]
> Could you please provide reproduction steps?

**Comment by wangkpot** [comment]
additional remarks：when set upstream.tries = 0, the tcp **passive** health check will become invalid.

**Comment by wangkpot** [comment]
> Could you please provide reproduction steps?

Firstly，set upstream.tries = 0；Secondly，configuring passive health checks for route. Then you will find  tcp passive health check will become invalid.
