### ISSUE TITLE
why oidc plugin creates 2 sessions?

### ISSUE THREAD

**Issue by karl-chanel** [apache/apisix#10481]
### Description

![屏幕截图 2023-11-12 014753](https://github.com/apache/apisix/assets/78248702/2e9d7f08-4840-49be-b15f-c27c13e3a78a)

### Environment

- APISIX version (run `apisix version`): 3.6
- Operating system (run `uname -a`): ubuntu 2022

**Comment by karl-chanel** [comment]
有大佬可以告诉我为什么oidc认证后会在cookie里放入两个session吗，这两个作用是什么呢？

**Comment by kayx23** [comment]
They are the same cookie but chunked due to size. APISIX uses lua-resty-openidc which uses lua-resty-session. See [this](https://github.com/bungle/lua-resty-session/issues/35).

**Comment by kayx23** [comment]
Closing as completed.
