### ISSUE TITLE
feat: As a user, I want to unify the keyring and key_encrypt_salt fields

### ISSUE THREAD

**Issue by monkeyDluffy6017** [apache/apisix#10484]
### Description

As we can see, the [keyring](https://github.com/apache/apisix/blob/d8bd34414239ed36942c19f435ac10ad0d5e57c0/conf/config-default.yaml#L133) and the [key_encrypt_salt](https://github.com/apache/apisix/blob/d8bd34414239ed36942c19f435ac10ad0d5e57c0/conf/config-default.yaml#L111) are used in the same way and with the same meaning, so i suggest that if we could unify the keyring and key_encrypt_salt fields?

**Comment by luoluoyuyu** [comment]
I want to try it, please assign this issue to me

**Comment by luoluoyuyu** [comment]
hi @monkeyDluffy6017 
I want to use key_encrypt_salt to configure encryption of ssl and plugin data, do we need to consider compatibility issues if the current user has configured key_encrypt_salt and keycring respectively and has done a version upgrade?

**Comment by monkeyDluffy6017** [comment]
1. Why not use `keyring` ?
2. no need to consider the compatbility, name your pr start with `change: `

**Comment by luoluoyuyu** [comment]
> 1. Why not use `keyring` ?
> 2. no need to consider the compatbility, name your pr start with `change: `

@monkeyDluffy6017 ，thanks for the suggestion, I found that there is more code to use keyring than key_encrypt_salt, using key_encrypt_salt the amount of code would be smaller.

**Comment by monkeyDluffy6017** [comment]
`key_encrypt_salt` is under the item `ssl` and not generic, `keyring` is better, and no need to consider the amount of code

**Comment by RitterHou** [comment]
I am trying to fix this issue, can you assign it to me? @monkeyDluffy6017
