### ISSUE TITLE
help request: Why does nginx.conf has root permissions by default?

### ISSUE THREAD

**Issue by GuyT2002** [apache/apisix#10480]
### Description

Trying to run apisix, I have all the required resources, however I get the following log from the apisix pod:
```
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init
WARNING: using fixed Admin API token has security risk.
Please modify "admin_key" in conf/config.yaml .
failed to update nginx.conf: failed to open file: /usr/local/apisix/conf/nginx.conf, error info:/usr/local/apisix/conf/nginx.conf: Permission denied
```
However, I can't seem to find why the file is created with only root permissions, and not sufficient permission for apisix service account? (which exists in my cluster).
I'm using openshift containers platform 4.12.
I've seen the issue refered [here](https://github.com/apache/apisix-ingress-controller/issues/305), However, I don't understand why adding `anyuid` is a necessity here.
I can't really understand lua (hence the help request) but It does not seem like something that must be, since the nginx does not listen in port 80.

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`): Linux apisix-client-1-68ddb78b56-jl788-debug-6stlf 4.18.0-372.73.1.el8_6.x86_64 #1 SMP Fri Sep 8 13:16:27 EDT 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2

Irrelevant:
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
how did you install apisix?

**Comment by GuyT2002** [comment]
Yes, I've installed it using APIsix, adding here installation command:
```
helm install apisix-client-1 ~/Documents/apisix-helm-chart/charts/apisix \
  --set gateway.type=LoadBalancer  \
  --set etcd.enabled=false \
  --set etcd.host="{http://apisix-central-etcd.apisix-client-1.svc.cluster.local:2379}" \
  --set etcd.prefix=/apisix-client-1 \
  --set ingress-controller.enabled=false \
  --namespace apisix-client-1 \
  --set apisix.admin.type=LoadBalancer \
  --set apisix.admin.credentials.admin=qwe123 \
  --set serviceAccount.create=false \
  --set serviceAccount.name=apisix-ingress-controller \
  --set apisix.nginx_config.user=root \
  --set apisix.ssl.enabled=true \
  --set apisix.resources.requests.cpu=500m \
  --set apisix.resources.requests.memory=2G \
  --set apisix.resources.limits.cpu=2000m \
  --set apisix.resources.limits.memory=2G \
  --set apisix.initContainer.resources.requests.cpu=250m \
  --set apisix.initContainer.resources.requests.memory=1G \
  --set apisix.initContainer.resources.limits.cpu=1000m \
  --set apisix.initContainer.resources.limits.memory=1G
```
The service account and etcd are created beforehand, are work.
Anything more I can provide?

**Comment by kayx23** [comment]
You would need to [add `anyuid` to the service account](https://docs.api7.ai/apisix/install/kubernetes/rosa/#create-a-openshift-project-and-service-account).

**Comment by monkeyDluffy6017** [comment]
considered resolved
