### ISSUE TITLE
help request: etcd 2379 is already in use by kubenetes,how can i change the etcd port using by apisix?

### ISSUE THREAD

**Issue by Tridu33** [apache/apisix#10491]
### Description

```
\apisix-docker\example>docker-compose -p docker-apisix up -d
Error response from daemon: driver failed programming external connectivity on endpoint docker-apisix-etcd-1 (a110aa358d21cd9134cec10082b8aa694a79909bcf813df847e7fe2020692971):
listen tcp4 0.0.0.0:2379: bind: address already in use
```

Can i use apisix with my kubenetes  running? There is a daemon "k8s_POD_etcd-docker-desktop_kube-system" using the port 2379 , and it conflicts.

How can i change the port of etcd for apiSix?

### Environment

- APISIX version (run `apisix version`):latest
- Operating system (run `uname -a`):Windows Docker Desktop 24.0.2
- using this file https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml following the guide in https://apisix.apache.org/zh/docs/apisix/installation-guide/

**Comment by kayx23** [comment]
Change this config: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L666

Add the config to config.yaml

**Comment by Tridu33** [comment]
nice, i change 
```
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2387" 
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2387"
    ports:
      - "2387:2387/tcp"
```
in `docker-compose.yaml` and 
```
      - "http://etcd:2387"          # multiple etcd address
```
in `./apisix_conf/config.yaml` it works.
