### ISSUE TITLE
help request: use oidc plugin without client secret

### ISSUE THREAD

**Issue by jonathan-dev** [apache/apisix#10498]
### Description

In the [documentation](https://apisix.apache.org/docs/apisix/plugins/openid-connect/) of the oidc plugin the `client_secret` is listed as required.

Whats the reason for it being required? shouldn't I be able to use the plugin without a client secret?

When I need at secret wouldn't I break the [rule](https://www.oauth.com/oauth2-servers/client-registration/client-id-secret/) of including that in a mobile/ web client because there is no other way around it?

I tried just leaving it blank but that didn't work for me...

### Environment

using docker image: `apache/apisix:3.6.0-debian`

**Comment by kayx23** [comment]
For token endpoint authentication:

> If token_endpoint_auth_method is set to "client_secret_basic", "client_secret_post", or "client_secret_jwt", authentication to Token endpoint is using client_id and client_secret

[source](https://github.com/zmartzone/lua-resty-openidc)

**Comment by shreemaan-abhishek** [comment]
I am not sure what you mean but AFAIK, but you do not need to include the `client_secret` in a mobile/web client, in fact the `client_secret` is provided by the OIDC provider which is then configured into the plugin. During the request, the client should carry a credential given by the OIDC provider (ex: a bearer token) which is then used to authenticate the request.

**Comment by jonathan-dev** [comment]
For a little bit more context:
I am setting up the OIDC provider myself (Keycloak). When setting up the Application I think I am required to set the access to confidential access (only then Keycloak generates a client_secret witch I need(?) to configure in the plugin).
Now when I try to simulate a client (with a curl command) I need to add the client secret to my curl command in order to retrieve my JWT which then can be verified by the OIDC plugin.

Shouldn't I be able to not use the client secret in the JWT retrieving request when I want to use that request in web client for example? (or am I and I haven't noticed?)

Maybe with this description you can help me to figure out where I am off or misunderstanding something.
Thanks

**Comment by kayx23** [comment]
To clarify, are you asking why you need to configure client secret with APISIX if your downstream web client is passing the client secret already?

**Comment by jonathan-dev** [comment]
Ok I think that I now understand what confused me. I assumed that the client (curl command) and the Apisix plugin need to use the same clinet_id which doesn't seem to be the case. Because of that I thought that the client would also need to know the client secret that need to be set for the Apisix (which is not recommended for web clients for example).
If that makes any sense to you please confirm or try to get me on the right track. Otherwise just close it since it seems to be more related to my misunderstanding than to this Github project.

**Comment by kayx23** [comment]
You would configure client secret with APISIX oidc plugin. The downstream clients to APSIX (web or not) don't need to have info of this client secret.

**Comment by kayx23** [comment]
Hope that helped. If there's anything else you may reopen.
