### ISSUE TITLE
help request: Automatically configure routes/services

### ISSUE THREAD

**Issue by destinyzju** [apache/apisix#10507]
### Description

请问有没有办法在服务容器起来之后，自动在apisix里完成路由/服务的配置，就像traefik + nomad里一样？
我知道可以配service discovery，但是apisix dashboard里并不能看到发现的服务，配服务的时候还要手工填写服务名完成配置。研究了下，apisix ingress controller似乎可以完成类似的事情，还有没有其他办法？
多谢！

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please use english to describe your problem. The translated version didn't make much sense to me.
