### ISSUE TITLE
help request: uri too long ,return code 414,how to modify max_uri_length

### ISSUE THREAD

**Issue by zhjdhx** [apache/apisix#10516]
### Description

my uri length is 4000
return 414 
i want to modify max_uri_length,but i don't know how to do this,please help me with some docs,thank you 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Try setting [large_client_header_buffers](https://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers)

**Comment by shreemaan-abhishek** [comment]
please reopen if you have more questions
