### ISSUE TITLE
help request: Key-auth in consumer with custom header or grouping routes

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10518]
### Description

At the moment, I get the `apiKey `value (which I would like to use in key-auth consumer) from the jwt token using the serverless-plugin which is used globally and register it as a variable. I have the proxy-rewrite plugin configured globally, it adds to each request the `apiKey` header required for key-auth from my consumer. Unfortunately or fortunately - it doesn't work. I use one of the jwt token parameters as the `apikey ` value. I would like not to send the `apiKey `as the request header every time, but to substitute it from a registered variable. 

My question may be strange, but I came up with such an implementation, maybe there are other options? Is it possible to implement my option at all?

If my implementation is not possible, is there any way to apply plugins to a group of routes? Not globally, but only for a part of the routes

### Environment

- APISIX version 3.5:
- etcd version 3.4.15
- APISIX Dashboard version 3.01

**Comment by kayx23** [comment]
To apply plugins for a group of routes: https://apisix.apache.org/docs/apisix/terminology/plugin-config/

**Comment by pavlenkodev** [comment]
Thank you for your help @kayx23! Plugins are really used for a group of routes. Is it possible to add 
```
"vars": [
    [
      "http_var",
      "==",
      "value"
    ]
  ] 
```
for a group of routes?

**Comment by Revolyssup** [comment]
@pavlenkodev Are you talking about using this in key-auth plugin? Can you provide the full plugin configuration which you're trying to use?

**Comment by pavlenkodev** [comment]
> @pavlenkodev Are you talking about using this in key-auth plugin? Can you provide the full plugin configuration which you're trying to use?

I'm using a basic configuration for consumer 
 and the route. It is presented here - https://api sys.apache.org/docs/apisix/terminology/consumer/

Following the example at the link https://api sys.apache.org/docs/apisix/terminology/consumer/#example , I am trying to configure the key-auth plugin using my own variable, which I register using serverless-pre-function globally

Here is an example from the documentation :

```
 curl http://127.0.0.1:9180/apisix/admin/consumers \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "jack",
    "plugins": {
        "key-auth": {
            "key": "auth-one"
        },
        "limit-count": {
            "count": 2,
            "time_window": 60,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    }
}'
```

And here is an example that I would like to implement. The request has a jwt token and I get a parameter from it in the globally configured serverless-pre-function plugin and register it in the $my_value variable.

I know what values will come in this variable. For example: 1, 2, 3.
To do this, I will configure key-auth as shown below

 ```
 curl http://127.0.0.1:9180/apisix/admin/consumers \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "jack",
    "plugins": {
        "key-auth": {
            "key": "1"  -- or 2 or 3
        },
        "limit-count": {
            "count": 2,
            "time_window": 60,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    }
}'
```
After such a configuration, I would like to add the `apiKey: 1 `header at every request using the proxy-rewrite globaly, so that key-auth accepts it and opens access for routes that are waiting for it.

This is my idea of using. I managed to configure the key-auth plugin, there are no problems with this. The problem is that I can't get consumer to accept my apiKey:1 header for authorization and allow me to make a request

Do you have any ideas how this can be done? Or is it impossible?

**Comment by kayx23** [comment]
Which phase does the serverless-pre-function hook to? Is it possible that the the logics defined there didn't get executed before jwt auth?

**Comment by pavlenkodev** [comment]
> Which phase does the serverless-pre-function hook to? Is it possible that the the logics defined there didn't get executed before jwt auth?

I am using the serverless-pre-function plugin in the rewrite phase. As far as I understand, this is the earliest execution. Wasn't that supposed to work?
Perhaps proxy-rewrite is triggered later than key-auth, but I have set a priority of 5000 for it

**Comment by kayx23** [comment]
Ok just trying to exclude possible cases. Your understanding of the priority sounds good to me. I'm not certain what the issue is with serverless function approach. Perhaps @shreemaan-abhishek or @Revolyssup could provide more ideas.

As for this question:

> Thank you for your help @kayx23! Plugins are really used for a group of routes. Is it possible to add
> 
> ```
> "vars": [
>     [
>       "http_var",
>       "==",
>       "value"
>     ]
>   ] 
> ```
> 
> for a group of routes?

What I can think of is use a plugin that has the `vars` attribute (perhaps traffic-split or workflow) and configure it on plugin config. See if that serves your purpose.

**Comment by shreemaan-abhishek** [comment]
@pavlenkodev your use case is valid and the setup you described should work. Can you share your configs?

**Comment by shreemaan-abhishek** [comment]
IIRC, you said that authentication fails with this setup. Can you confirm if the key you generate in the serverless plugin matches the key defined in the consumer config. And please also check if there are any error logs. Your setup seems fair to me.

**Comment by pavlenkodev** [comment]
I reconfigured everything again, found another plugin that could interfere with work and disabled it. Now everything works! 
Thank you so much for helping everyone🎉
