### ISSUE TITLE
help request: Why does the layer 4 proxy need to specify stream_proxy in the configuration file? Why can't I specify the port directly like nginx?

### ISSUE THREAD

**Issue by GuoFlight** [apache/apisix#10520]
### Description

I want to know the reason why I can't create 4 layer proxy directly using API.
Official documentation: https://apisix.apache.org/zh/docs/apisix/next/stream-proxy/
If not set, an error will be reported: {"error_msg":"stream mode is disabled, can not add stream routes"}

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0

**Comment by luoluoyuyu** [comment]
hi @GuoFlight ,specifically, you can see how nginx configuration, in fact, stream-proxy and nginx configuration is almost the same, but the route can be dynamically configured.[https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#example]()

**Comment by DokiDoki1103** [comment]
如果不想在配置文件中提前制定，能不能有什么方法可以动态的添加并且实时生效？

**Comment by luoluoyuyu** [comment]
> 如果不想在配置文件中提前制定，能不能有什么方法可以动态的添加并且实时生效？

APISIX doesn't seem to support this during runtime
