### ISSUE TITLE
docker部署apisix，使用prometheus组件时， 当docker重启时，prometheus的指标会被重置成从0开始

### ISSUE THREAD

**Issue by gxproject** [apache/apisix#10521]
### Current Behavior

apisix暴露的指标是存在内存中的，重启就丢失了吗？
如果是这样我有什么办法可以让他持久化吗？

### Expected Behavior

apisix 暴露的prometheus指标不会因为重启而重置

### Steps to Reproduce

使用docker部署apisix
`docker run --name apisix \
--privileged=true \
-v /config/apisix/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml \
-p 9100:9100 \
-p 9150:9200 \
-p 9080:9080 \
-p 9180:9180 \
-p 9091:9091 \
-p 9443:9443 \
--restart=always \
-d apache/apisix:3.3.0-centos`

打开 prometheus 插件，运行一段时间，让prometheus 收集数据以调用数量为例（例如到10），然后重启apisix，运行一下，查看指标的图，出现了调用数量指标重置（从0开始）的现象， 两个时间段的数据差值 出现了负数

![image](https://github.com/apache/apisix/assets/4375272/739d730c-df98-4920-92c8-6060a8b59394)

**Comment by luoluoyuyu** [comment]
hi @gxproject ,It's not apisix's job to store the metrics data, apisix just provides the metrics information, which is timed and grabbed by the prometheus.

**Comment by luoluoyuyu** [comment]
hi @gxproject ,general is saved in the prometheus directory under the data folder, you can use dockers persistence mechanism to achieve the preservation of metrics data, dockers persistence can be specific look at this [https://docs.docker.com/storage/]()
