### ISSUE TITLE
How to configure the conversion of all domain names with certificates from the default http to https?

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10527]
### Description

Currently, dozens of domain names are configured on apisix. Follow the method in the official documentation () to configure http to automatically jump to https. Each configuration is too complicated. Is there any similar global configuration that can make all configured domain names automatically jump from http to https?

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.4
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
I don't think that's possible but you can write a shell script to export all stored routes using etcd/admin api. You can take motivation from these threads:

https://the-asf.slack.com/archives/CUC5MN17A/p1692768631040169
https://the-asf.slack.com/archives/CUC5MN17A/p1689604461287849
