### ISSUE TITLE
no test case to cover the default `false` for websocket upstream

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1053]
no test case to cover the default `false`

_Originally posted by @moonming in https://github.com/apache/incubator-apisix/pull/1051_

**Comment by lilien1010** [comment]
already has test case in  t/node/upstream-websocket.t
TEST 6: disable websocket(id: 6)

**Comment by moonming** [comment]
@lilien1010 I means no `"enable_websocket"` instead of `enable_websocket = false`.

**Comment by spacewander** [comment]
The `enable_websocket` is no longer in upstream now.
