### ISSUE TITLE
bug:  The HTTP routing host field cannot match the port 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix#10531]
### Current Behavior

req
```json
{
  "id": "getting-started-ip",
  "uri": "/*",
  "host":"8.130.141.31:7070",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "10.43.242.12:7070": 1
    }
  }
}
```
resp
```json
{
    "value": {
        "priority": 0,
        "uri": "/*",
        "create_time": 1700623575,
        "update_time": 1700623788,
        "upstream": {
            "pass_host": "pass",
            "nodes": {
                "10.43.242.12:7070": 1
            },
            "type": "roundrobin",
            "scheme": "http",
            "hash_on": "vars"
        },
        "id": "getting-started-ip",
        "status": 1,
        "host": "8.130.141.31:7070"
    },
    "key": "/apisix/routes/getting-started-ip"
}
```
<img width="1466" alt="图片" src="https://github.com/apache/apisix/assets/62740231/31e34cd6-74d3-4a77-b6eb-3c27e00fe1ca">

**Comment by shreemaan-abhishek** [comment]
could you describe your problem in the issue description?

**Comment by DokiDoki1103** [comment]
The HTTP routing host field does not recognize the port

**Comment by shreemaan-abhishek** [comment]
I just tested it and I realise that the [radixtree](https://github.com/api7/lua-resty-radixtree) library doesn't support `ip:port` in host header for host based matching

**Comment by DokiDoki1103** [comment]
I think you can optimize it, thank you

**Comment by moonming** [comment]
> I think you can optimize it, thank you

@DokiDoki1103 Welcome to contribute PR to fix this

**Comment by theweakgod** [comment]
> > I think you can optimize it, thank you
> 
> @DokiDoki1103 Welcome to contribute PR to fix this

Would it be possible for me to try it out?

**Comment by shreemaan-abhishek** [comment]
If you want to take this up comment here: https://github.com/api7/lua-resty-radixtree/issues/138 I will assign it to you.

**Comment by theweakgod** [comment]
> If you want to take this up comment here: [api7/lua-resty-radixtree#138](https://github.com/api7/lua-resty-radixtree/issues/138) I will assign it to you.

[check this](https://github.com/api7/lua-resty-radixtree/issues/138#issuecomment-1828956608)
I think it has nothing to do with lua-resty-radixtree.

**Comment by haoyang1994** [comment]
@DokiDoki1103 Did you try to configure host=8.130.141.31 instead of host=8.130.141.31:7070? I don't think it's a good practice to add port matching in host because I feel it can lead to confusion and it's not necessary for most cases. If what you need is server port filter, a possible workaround way is like this:

  "uri": "/*",
  "host": "8.130.141.31",
  "vars": [
    [
      "server_port",
      "==",
      "7070"
    ]
  ]

**Comment by theweakgod** [comment]
> If you want to take this up comment here: [api7/lua-resty-radixtree#138](https://github.com/api7/lua-resty-radixtree/issues/138) I will assign it to you.

Ok, this does need to be modified in radixtree

**Comment by DokiDoki1103** [comment]
> server_port



> @DokiDoki1103 Did you try to configure host=8.130.141.31 instead of host=8.130.141.31:7070? I don't think it's a good practice to add port matching in host because I feel it can lead to confusion and it's not necessary for most cases. If what you need is server port filter, a possible workaround way is like this:
> 
> "uri": "/*", "host": "8.130.141.31", "vars": [ [ "server_port", "==", "7070" ] ]

 How should I configure it here when I need to use the ingress controller?

**Comment by DokiDoki1103** [comment]
like this?
```
    - name: rbd-app-ui
      match:
        exprs:
          - subject:
              scope: ScopeHeader
              name: server_port
            op: Equal
            value: 7070
        paths:
          - /*
      backends:
        - serviceName: rbd-app-ui
          servicePort: 7070
```

**Comment by theweakgod** [comment]
> @DokiDoki1103 Did you try to configure host=8.130.141.31 instead of host=8.130.141.31:7070? I don't think it's a good practice to add port matching in host because I feel it can lead to confusion and it's not necessary for most cases. If what you need is server port filter, a possible workaround way is like this:
> 
> "uri": "/*", "host": "8.130.141.31", "vars": [ [ "server_port", "==", "7070" ] ]

If the host contains port, then it will match the host, otherwise it will not match. I think this design will be more suitable for you.
you can check this pr [#139](https://github.com/api7/lua-resty-radixtree/pull/139)

**Comment by haoyang1994** [comment]
Sorry, I may not have expressed myself clearly. The port appearing in `http_host` and `vars.server_port` are sometimes not equivalent. Take the following curl command as an example. `http_host` is 10.70.2.23:9000, but `server_port` will be 8000. 
`curl "http://10.70.2.23:8000/api/test/1" -H 'host: 10.70.2.23:9000'`

This situation may occur especially when there is a load balancer before apisix. Intuitively, one may feel that the port in the routing configuration needs to match the host in the http request header. 
That's why I thought the port on the host in the routing configuration may be confusing. But anyway, it doesn't appear to be harmful, and whoever configures the port on the host should know what to expect.

**Comment by DokiDoki1103** [comment]
> Sorry, I may not have expressed myself clearly. The port appearing in `http_host` and `vars.server_port` are sometimes not equivalent. Take the following curl command as an example. `http_host` is 10.70.2.23:9000, but `server_port` will be 8000. `curl "http://10.70.2.23:8000/api/test/1" -H 'host: 10.70.2.23:9000'`
> 
> This situation may occur especially when there is a load balancer before apisix. Intuitively, one may feel that the port in the routing configuration needs to match the host in the http request header. That's why I thought the port on the host in the routing configuration may be confusing. But anyway, it doesn't appear to be harmful, and whoever configures the port on the host should know what to expect.

 If I want to access the HTTP service on a certain port, then your method is more effective, but if I want to match the port through Host, your method is not supported

**Comment by theweakgod** [comment]
> Sorry, I may not have expressed myself clearly. The port appearing in `http_host` and `vars.server_port` are sometimes not equivalent. Take the following curl command as an example. `http_host` is 10.70.2.23:9000, but `server_port` will be 8000. `curl "http://10.70.2.23:8000/api/test/1" -H 'host: 10.70.2.23:9000'`
> 
> This situation may occur especially when there is a load balancer before apisix. Intuitively, one may feel that the port in the routing configuration needs to match the host in the http request header. That's why I thought the port on the host in the routing configuration may be confusing. But anyway, it doesn't appear to be harmful, and whoever configures the port on the host should know what to expect.

Yes, thank you for your advice.I will take it

**Comment by theweakgod** [comment]
> Sorry, I may not have expressed myself clearly. The port appearing in `http_host` and `vars.server_port` are sometimes not equivalent. Take the following curl command as an example. `http_host` is 10.70.2.23:9000, but `server_port` will be 8000. `curl "http://10.70.2.23:8000/api/test/1" -H 'host: 10.70.2.23:9000'`
> 
> This situation may occur especially when there is a load balancer before apisix. Intuitively, one may feel that the port in the routing configuration needs to match the host in the http request header. That's why I thought the port on the host in the routing configuration may be confusing. But anyway, it doesn't appear to be harmful, and whoever configures the port on the host should know what to expect.

Hey, I've finished changing it. Thanks again for your advice

**Comment by haoyang1994** [comment]
Defining the host port in the route as server_port matching is actually a simpler method.

**Comment by shreemaan-abhishek** [comment]
@theweakgod I agree with you.
