### ISSUE TITLE
What does this document mean?

### ISSUE THREAD

**Issue by ShenFeng312** [apache/apisix#10553]
### Description

![image](https://github.com/apache/apisix/assets/49786112/1cb8776b-e3d7-4e3e-813d-c007bb0855ae)
Is the document saying that I installed apisix according to the official documentation, but it's not running on apisixBase? Do I need to build apisixBase myself？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ShenFeng312** [comment]
How can Apisix run on Apisix-base?

**Comment by shreemaan-abhishek** [comment]
> Is the document saying that I installed apisix according to the official documentation, but it's not running on apisixBase? Do I need to build apisixBase myself？

most installation methods use apisix-base by default. How do install apisix?

**Comment by luoluoyuyu** [comment]
hi @ShenFeng312  
You can refer to this:https://apisix.apache.org/docs/apisix/installation-guide/

**Comment by ShenFeng312** [comment]
> > Is the document saying that I installed apisix according to the official documentation, but it's not running on apisixBase? Do I need to build apisixBase myself？
> 
> most installation methods use apisix-base by default. How do install apisix?

thx!

**Comment by ShenFeng312** [comment]
> hi @ShenFeng312 You can refer to this:https://apisix.apache.org/docs/apisix/installation-guide/

thx!
