### ISSUE TITLE
bug: nginx relaod but worker does not exit

### ISSUE THREAD

**Issue by jensonfxc** [apache/apisix#10554]
### Current Behavior

root     18552     1  0 09:46 ?        00:00:00 nginx: master process /usr/local/openresty/bin/openresty -p /usr/local/apisix
www-data 18553 18552  0 09:46 ?        00:00:14 nginx: worker process is shutting down
www-data 18554 18552  0 09:46 ?        00:00:12 nginx: worker process is shutting down
www-data 61666 18552  2 18:15 ?        00:00:00 nginx: worker process
www-data 61667 18552  2 18:15 ?        00:00:00 nginx: worker process
root     61668 18552  1 18:15 ?        00:00:00 nginx: privileged agent process

### Steps to Reproduce

This problem has been fixed in apisix3.5, but the code has not been merged for LTS 3.2. Can it be officially merged into LTS3.2?
https://github.com/apache/apisix/pull/9909

### Environment

- APISIX version (run `apisix version`): 3.2

**Comment by theweakgod** [comment]
maybe you should know this pr.
[https://github.com/apache/apisix/pull/9909](url)
it had been fixed. :)

**Comment by jensonfxc** [comment]
Steps to Reproduce
This problem has been fixed in apisix3.5, but the code has not been merged for LTS 3.2. Can it be officially merged into LTS3.2?
https://github.com/apache/apisix/pull/9909

--------
I know this version has been fixed. will it be officially merged into lts3.2?

**Comment by shreemaan-abhishek** [comment]
you can raise a PR to backport this to [release/3.2](https://github.com/apache/apisix/tree/release/3.2) branch.

**Comment by monkeyDluffy6017** [comment]
@jensonfxc LTS3.2 doesn't have the problem you metioned, the problem was casued the commit: https://github.com/apache/apisix/commit/4377d05491ae2af228d40e3900362371363a8f46
And the commit was merge after LTS3.2

**Comment by jensonfxc** [comment]
It was confusing, I found that the problem was solved after I replaced it with #9909 code @monkeyDluffy6017

**Comment by theweakgod** [comment]
> It was confusing, I found that the problem was solved after I replaced it with #9909 code @monkeyDluffy6017

Did you use consul as serivice discovery？

**Comment by jensonfxc** [comment]
> > It was confusing, I found that the problem was solved after I replaced it with #9909 code @monkeyDluffy6017
> 
> Did you use consul as serivice discovery？

Our apisix service reads all data from etcd and does not use other service discovery types. Can you try to use the code modified in #9909 to see if the worker can exit normally after replacing it. I tested that it can exit normally.

**Comment by monkeyDluffy6017** [comment]
@jensonfxc The etcd related code is very different between lts3.2 and 3.5, so if you could apply the commit https://github.com/apache/apisix/pull/9909, please check your version

**Comment by jensonfxc** [comment]
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.2.2

**Comment by jensonfxc** [comment]
@monkeyDluffy6017The code that finally merged the problem was this [5d6bde2](https://github.com/apache/apisix/commit/5d6bde2e963567055a0c40a2a8088233a714ff0f) .I compared the lts3.2 config_etcd.lua code to fix the problem and modified it with the lts3.2 code.

**Comment by monkeyDluffy6017** [comment]
@jensonfxc I'm afraid you are right, the version 3.2.2 has imported the etcd related changes, so the [5d6bde2](https://github.com/apache/apisix/commit/5d6bde2e963567055a0c40a2a8088233a714ff0f) will fix this problem, and we will backport to the 3.2.2 very soon

**Comment by jensonfxc** [comment]
ok i will close this question

**Comment by Lewisyixin** [comment]
I met same issue in version 3.2.2... so is it really fixed in 3.2?
![Uploading image.png…]()

**Comment by Lewisyixin** [comment]
I met same issue in 3.2.2, so is it really fixed in 3.2?
![image](https://github.com/user-attachments/assets/728f237a-eab0-4384-8eda-07f79d149487)

**Comment by jensonfunfun** [comment]
I remember that I compared apisix 3.5 and merged some codes, and then there was no problem of being unable to exit.

**Comment by jensonfunfun** [comment]
@Lewisyixin 
I remember that I compared apisix 3.5 and merged some codes, and then there was no problem of being unable to exit.
