### ISSUE TITLE
docs: the clickhouse-logger's default password was wrong

### ISSUE THREAD

**Issue by Vacant2333** [apache/apisix#10568]
### Current State

if we do the request as follow:
https://apisix.apache.org/docs/apisix/next/plugins/clickhouse-logger/#example-usage
apisix will throw a **error**:
![image](https://github.com/apache/apisix/assets/19872346/761be3fd-15f9-4d5f-b3cc-52581ba86bac)
i have check the clickhouse's docs:
https://github.com/ClickHouse/ClickHouse/blob/master/docker/server/README.md#start-server-instance
the password should be null
![image](https://github.com/apache/apisix/assets/19872346/daaa4804-196e-40a9-8551-c93e6a1e4efd)

and we should create table like:
```
curl -X POST 'http://127.0.0.1:8123/' \
--data-binary 'CREATE TABLE default.test (host String, client_ip String, route_id String, service_id String, `@timestamp` String, PRIMARY KEY(`@timestamp`)) ENGINE = MergeTree()' --user default:
```
the guide's is not working

### Desired State

correct the example usage that i can  run it without problem

**Comment by shreemaan-abhishek** [comment]
please raise a PR with the fix.
