### ISSUE TITLE
help request:  apisix how to  avoid encountering  TcpExtListenOverflows and TcpExtListenDrops

### ISSUE THREAD

**Issue by waney316** [apache/apisix#10560]
### Description

version：apisix 2.10.2
os：centos7.9 3.10.0

Client requests routed through application 'a' to Apisix experience a delay of 10 seconds in Apisix's logging for the corresponding request. After eliminating other network and application issues, suspicion arises that there might be an issue at the gateway layer. there has been a continuous occurrence of TCP full and half queues. Upon inspection using `ss -ltn`, it was found that the default value for Apisix is 511. In the current version, which cannot be changed or upgraded, how can I set a higher value?
![image](https://github.com/apache/apisix/assets/23314093/d0816fc9-0194-4752-bfb0-af0ba2c9e4b5)
![image](https://github.com/apache/apisix/assets/23314093/6ea6681a-2fa1-4bbd-9612-f033fd9fec3c)

Apart from this, I would like to ask, is there an optimal upgrade plan for migrating from Apisix 2.10 to Apisix 3.5? Currently, the official upgrade plan is from version 2.15 to 3.x.

### Environment

- APISIX version (run `apisix version`): apisix 2.10.2
- Operating system (run `uname -a`):  centos7.9 3.10.0
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.19.3.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.10
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> Currently, the official upgrade plan is from version 2.15 to 3.x.
you can upgrade to 2.15 first and then upgrade to 3.x

**Comment by shreemaan-abhishek** [comment]
did you check if this issue exists on latest?

**Comment by shreemaan-abhishek** [comment]
@waney316 could you please provided steps to reproduce?

**Comment by shreemaan-abhishek** [comment]
closing due to lack of response.
