### ISSUE TITLE
feat: validate `apisix.yaml` before deployment for standalone mode

### ISSUE THREAD

**Issue by boekkooi-lengoo** [apache/apisix#10583]
### Description

As a user I want to validate my apisix.yaml before deploying changes.

Currently calling `apisix test` only validates the `config.yaml` but not the `apisix.yaml` when the `deployment.role_data_plane.config_provider` is set to `yaml`.

Would it be possible to extend `apisix test` or create another command to validate the `apisix.yaml` using the cli?

Thanks in advance for having a look at this.

Related to https://the-asf.slack.com/archives/CUC5MN17A/p1695458645370659

**Comment by shreemaan-abhishek** [comment]
would you like to raise a PR for this?

**Comment by shreemaan-abhishek** [comment]
your work direction LGTM

**Comment by monkeyDluffy6017** [comment]
hi @boekkooi-lengoo the code is a bit complicated, could you describe your thought in detail?
