### ISSUE TITLE
help request: Requirements of the ETCD cluster when using APISIX as Kubernetes Ingress

### ISSUE THREAD

**Issue by SalvaChiLlo** [apache/apisix#10581]
### Description

Hello, I am reviewing APISIX as an Ingress alternative for our Kubernetes solution. 

As I understood from the documentation, APISIX relies on an ETCD cluster for its operation. 
Here, some questions come to my mind:
1. Knowing that I can use an external ETCD cluster, is it a good idea to use the one Kubernetes already uses under the hood? This question is more about APISIX's requirements on the ETCD cluster, as ETCD can only group up to a few gigabytes. What is the amount of data I can expect APISIX to produce? Do you have some concrete numbers?
2. Who uses this ETCD, and how?

** I'll not provide any environment details as I'm just evaluating/trying to understand how APISIX works

**Comment by shreemaan-abhishek** [comment]
@juzhiyuan any insights here?

**Comment by SalvaChiLlo** [comment]
Do you have any documentation on how to run APISIX without ETCD? 

By just not providing an ETCD connection it should work?

**Comment by juzhiyuan** [comment]
> Do you have any documentation on how to run APISIX without ETCD?

APISIX supports `standalone` mode.

> As far as I understand, the ingress controller should use the Kubernetes definitions to make everything work, isn't it?

There has one project called `APISIX Ingress Controller`, after 1.7.0+, it supports running without ETCD anymore.

**Comment by shreemaan-abhishek** [comment]
I will close this issue now, feel free to reopen if you have more questions.

**Comment by SalvaChiLlo** [comment]
I have an extra question when using mTLS. From what I've seen, it gets configured for the whole domain(SNI).

```
'{
    "sni": "test.com",
    "cert": "<content of server.cer>",
    "key": "<content of server.key>",
    "client": {
        "ca": "<content of ca.cer>"
    }
}'
```

Is it possible to enable mTLS just in certain subpaths?

Let's say I have example.com, and I want:

- `https://example.com/public` -> to just have TLS
- `https://example.com/private` -> Authenticate via certificate (mTLS)

Is that possible? If so, how should that be configured?
