### ISSUE TITLE
log-rotate Plugin  support  custom log files or directories

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#10580]
### Description

The log-rotate Plugin is used to keep rotating access and error log files in the log directory at regular intervals. But  log-rotate  not  support  custom log files or directories.  For example: "logs/apisix.log"

**Comment by qyk1995** [comment]
I see, but  I want to compress this  file-logger generated logs.

**Comment by Vacant2333** [comment]
> I see, but I want to compress this file-logger generated logs. Beacause file-logger generated logs probably too big.

yes,i mean we may can add the `path` attribute for `log-rotate`

**Comment by shreemaan-abhishek** [comment]
I will consider this as resolved. @qyk1995 please reopen if you have more questions.
