### ISSUE TITLE
help request: how to use regex in request-validation plugin. It doesnt work

### ISSUE THREAD

**Issue by kuzds** [apache/apisix#10598]
### Description

Example doesn't work
```
{
    "body_schema": {
        "type": "object",
        "required": ["regex_payload"],
        "properties": {
            "regex_payload": {
                "type": "string",
                "minLength": 1,
                "maxLength": 32,
                "pattern": "[[^[a-zA-Z0-9_]+$]]"
            }
        }
    }
}
```

### Environment

- APISIX 3.6

**Comment by shreemaan-abhishek** [comment]
what do you mean by "example doesn't work" could you please share the request that you made to apisix that didn't work?

**Comment by kuzds** [comment]
This example from apisix documentation for request-validation plugin
Route couldn't be created due to unnecessary square brackets in "pattern" field.
Thanks
