### ISSUE TITLE
bug: /etc/ssl folder is not in 3.7.0-debian

### ISSUE THREAD

**Issue by zhuoyang** [apache/apisix#10593]
### Current Behavior

/etc/ssl/ folder is not in `3.7.0-debian` container

### Expected Behavior

/etc/ssl folder should be in the container 

### Steps to Reproduce

```
docker run -it --entrypoint /bin/bash apache/apisix:3.7.0-debian
$ ls /etc/ssl
```

### Environment

- APISIX version (run `apisix version`): 3.7.0
- Container: 3.7.0-debian

**Comment by luoluoyuyu** [comment]
Hi @zhuoyang 
Hopefully this will help you
https://apisix.apache.org/docs/docker/manual/

**Comment by zhuoyang** [comment]
I should also mention that 3.6.0-debian and 3.7.0-redhat does have the /etcd/ssl folder

**Comment by luoluoyuyu** [comment]
Hi @zhuoyang 
This docker environment is running in debian:bullseye-slim. This system doesn't have that directory, and I don't think it's an APISIX problem!
You can look at the APISIX dockerfile
https://github.com/apache/apisix-docker/blob/master/debian/Dockerfile#L18C6-L18C26

**Comment by luoluoyuyu** [comment]
Hi @juzhiyuan 
Yes, I tried to run in docker
```
docker run -it debian:bullseye-slim /bin/bash
```
It also fails to find the corresponding directory
![image](https://github.com/apache/apisix/assets/82068138/46549e3d-c809-404d-a79b-7a8602d99ca6)

**Comment by Revolyssup** [comment]
@zhuoyang ca-certificates package is no longer pre-packaged into the container image. You will have to manually install it will `apt install ca-certificates`

**Comment by juzhiyuan** [comment]
refer to https://github.com/apache/apisix-docker/pull/514
