### ISSUE TITLE
help request: error occurred after changing the version.

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix#10594]
### Description

After changing the version from 3.4 to 3.7, I made the same call, but an error occurred.
(3.4 200 return, 3.7 400 return)

In version 3.7, the error below occurs when the Content-Length value of the request is high.
`writev() failed (32: Broken pipe) while sending request to upstream`
Can you confirm the situation? We are now seeing code changes from 3.4 to 3.7

### Environment

- APISIX version (run `apisix version`): 3.7
- Operating system (run `uname -a`): ubuntu
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.3
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by luoluoyuyu** [comment]
Hi @Cheol-Soon-Choi 
Can you describe the process in more detail so that it can better help you?

**Comment by shreemaan-abhishek** [comment]
ping @Cheol-Soon-Choi

**Comment by monkeyDluffy6017** [comment]
@Cheol-Soon-Choi have you solved your problem?
