### ISSUE TITLE
feat: as a user I want to configure limit-count plugin with single value in redis_cluster_nodes property

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix#10596]
### Description

**Description**

Current implementation (https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/init.lua#L79) of schema in plugin _limit-count_ requires _redis_cluster_nodes_ to have a minimum length of 2, which seems too restrictive.

**Use case**

One can have the following example of setup:

1. Redis Cluster deployed in Kubernetes with 3 nodes (for example, 10.42.0.113:6379;10.42.0.114:6379;10.42.0.115:6379)
2. Redis Cluster nodes are accessible through [Kubernetes Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) (for example redis-headless-service

Kubernetes headless service is a Kubernetes service that does not assign an IP address to itself. Instead, it returns the IP addresses of the pods associated with it directly to the DNS system, allowing clients to connect to individual pods directly.

So, each time we request redis-headless service we get all 3 nodes ips back (not a single IP of a single node), and it is the task of Redis client to route to one of the nodes properly.

As a result, the following configuration should be valid:

```curl -i http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "redis_cluster_nodes": [
              "redis-headless-service:6379"
            ],
        }
    },
    "upstream": {}
}'
```

and equivalent to

```
curl -i http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "redis_cluster_nodes": [
              "10.42.0.113:6379",
              "10.42.0.114:6379",
              "10.42.0.115:6379"
            ],
        }
    },
    "upstream": {}
}'
```

**Proposal**

Update plugin schema validation to make _minLength=1_ for _limit-count_ plugin.

**Comment by shreemaan-abhishek** [comment]
> In case when redis is deployed in kubernetes in cluster mode access to this redis is implemented through headless service. In such a scenario single cluster node is enough to make it work.

I quite don't get you. If you need only one redis node, then use the plain redis policy. Wouldn't that work?

**Comment by ikatlinsky** [comment]
maybe it is a matter of naming, let me expand.

from my understanding there are 3 policies for the plugin:
- local - no redis is used
- redis - for cases when single redis master instance is used
- redis-cluster - for cases when we have a cluster with multiple master instances

So in my case i have 3 master instances running and all of them are accessible through single headless kubernetes service. Based on my understanding of policies i should use redis-cluster, not redis policy. That is because of the different types of redis clients created as a result.

Is my understanding correct?

**Comment by shreemaan-abhishek** [comment]
I think using redis should suffice for your use case.

**Comment by ikatlinsky** [comment]
thanks, will check this option and get back with the results

**Comment by ikatlinsky** [comment]
i made a small check and the results are that policy = redis is not applicable to a cluster, in 50% of cases i got an error from limit-count plugin

phase_func(): failed to limit count: MOVED 10722 10.42.0.117:6379, client: 10.42.0.105

so in our use case we need to stick to redis_cluster policy

**Comment by monkeyDluffy6017** [comment]
So the redis cluster could be formed with one node only? @ikatlinsky

**Comment by ikatlinsky** [comment]
> So the redis cluster could be formed with one node only? @ikatlinsky

Nope, let me try to explain. We have the following setup:

1. Redis Cluster deployed in Kubernetes with 3 nodes (for example, 10.42.0.113:6379;10.42.0.114:6379;10.42.0.115:6379)
2. Redis Cluster nodes are accessible through [Kubernetes Headless Service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services) (for example redis-headless-service)

Kubernetes headless service is a Kubernetes service that does not assign an IP address to itself. Instead, it returns the IP addresses of the pods associated with it directly to the DNS system, allowing clients to connect to individual pods directly.

So, each time we request redis-headless service we get all 3 nodes ips back (not a single IP of a single node), and it is the task of Redis client to route to one of the nodes properly.

Below two configurations are equivalent in the results.

With headless service:

```
curl -i http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "redis_cluster_nodes": [
              "redis-headless-service:6379"
            ],
        }
    },
    "upstream": {}
}'
```

With each node provided separately:

```
curl -i http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "redis_cluster_nodes": [
              "10.42.0.113:6379",
              "10.42.0.114:6379",
              "10.42.0.115:6379"
            ],
        }
    },
    "upstream": {}
}'
```

Hope that explains better the use case, @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
LGTM, pr is welcomed
