### ISSUE TITLE
feat: As a user i want to configure sensitive limit-count plugin properties using environment variables

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix#10597]
### Description

**Description**

[limit-count](https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/init.lua) plugin has several sensitive properties (contain passwords and username) or fields which should be the same for all instances of plugins in side apisix server, for example:

- redis_username
- redis_password
- redis_host
- redis_port
- redis_cluster_nodes
- redis_cluster_name

**Use case**

We have a single Redis cluster which should be used for all limit-count plugins we do not want to duplicate Redis-related settings and we do not want to include _redis_password_ directly in configuration scripts which create plugins inside routes.

**Proposal**

Make all string and string array properties support environment variables. 

If the property is an environment variable it should be prefixed with _env:_ or _$env:_. In other cases, properties will be treated as a plain value.

**Comment by ikatlinsky** [comment]
i can work on the PR for this feature

**Comment by shreemaan-abhishek** [comment]
including environment variables you can support the usage of secret resources: https://apisix.apache.org/docs/apisix/terminology/secret/
