### ISSUE TITLE
help request: OIDC requires two logins for proper authentication

### ISSUE THREAD

**Issue by luoluoyuyu** [apache/apisix#10605]
## configure
The configuration is as follows
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
 
  "uri":"/anything/*",
  "plugins": {
    "openid-connect": {
     "client_id": "'"$AUTH0_CLIENT_ID"'",
      "client_secret": "'"$AUTH0_CLIENT_SECRET"'",
      "discovery": "https://'"$AUTH0_DOMAIN"'/.well-known/openid-configuration",
      "scope": "openid profile",
      "logout_path": "/anything/logout",
      "redirect_uri": "http://localhost:9080/anything/callback"
    }
  },
  "upstream":{
    "type":"roundrobin",
    "nodes":{
      "httpbin.org:80":1
    }
  }
}'

```

## Process description
The steps of the operation follow the documentation: https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-auth0
### First time login
Redirects to http://localhost:9080/anything/callback after first successful login Returns 500，
![image](https://github.com/apache/apisix/assets/82068138/5ec05bb7-4bd8-4932-8e65-61f11e0fe70e)

### Second login
To access '127.0.0.1:9080/anything/test' again, I need to log in once more, and unfortunately, I don't get redirected to  /anything/callback    after a successful login.
![image](https://github.com/apache/apisix/assets/82068138/421e5904-4aa6-4f54-904b-0c5c65531b65)

## log：
```
 openidc.lua:1106: authenticate(): state from argument: 0dd075ce951900a6bdecbe123d8420e6 does not match state restored from session: nil,
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Related: https://github.com/apache/apisix/issues/9131

But for that doc, I didn't run into `state does not match state restored from session` last I ran it. Is this behaviour reproducible if you start with a clean APISIX instance?

**Comment by Vacant2333** [comment]
![image](https://github.com/apache/apisix/assets/19872346/412bf7d6-946a-478d-8ba2-b1f4a02ec068)
i can reproduce it on my apisix

**Comment by kayx23** [comment]
Ok noted. I'll find time to take a look soon.

**Comment by kayx23** [comment]
Ok I can reproduce the `no session state found` as well. It didn't error out in review when we rolled out this doc so this is new. I'll investigate.

Please note that the originally reported `... does not match state restored from session` is a different error. I have seen it before with other OP but not sure how to recreate for Auth0.

**Comment by kayx23** [comment]
@luoluoyuyu the doc has been updated. Please see if your issue still persists.

**Comment by luoluoyuyu** [comment]
@kayx23 
Thanks, problem solved!
