### ISSUE TITLE
help request: How to set header to introspection endpoint used within OIDC plugin?

### ISSUE THREAD

**Issue by zmaren** [apache/apisix#10601]
### Description

In other API gateway I used similar way to set header to my introspection endpoint that I used within OIDC plugin. In pre-function plugin I did set header using their code `gateway.service.request.set_header('header', 'value')`. However, with APISIX, I'm unable to replicate this. Even though I added `serverless-pre-function` plugin with phase set to `rewrite` or `access`, with `ngx.req.set_header` method, header was not set and forwarded to introspection endpoint.

### Environment

- APISIX version: 3.7
- Operating system: Linux apisix-dev-7b89dc65c5-54f8w 5.10.176-157.645.amzn2.x86_64 #1 SMP Tue Mar 28 17:49:06 UTC 2023 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2 / 
- Plugin runner version, for issues related to plugin runners: no sure what is this and how to get it
- LuaRocks version, for installation issues (run `luarocks --version`): no luarocks installed

**Comment by shreemaan-abhishek** [comment]
could you please share your route configuration?

**Comment by zmaren** [comment]
{
  "uri": "/stores/:store_uuid/uploads",
  "name": "STORES-store_uuid-uploads-post",
  "methods": [
    "POST"
  ],
  "plugins": {
    "openid-connect": {
      "access_token_in_authorization_header": true,
      "bearer_only": true,
      "client_id": "client_id",
      "client_secret": "client_secret",
      "discovery": "http://localhost:8001/.well-known/openid-configuration",
      "introspection_endpoint": "http://localhost:8001/api/introspection",
      "introspection_endpoint_auth_method": "client_secret_post",
      "logout_path": "/logout",
      "realm": "apisix",
      "scope": "openid",
      "set_access_token_header": true,
      "set_id_token_header": false,
      "set_refresh_token_header": false,
      "set_userinfo_header": false,
      "ssl_verify": false,
      "timeout": 3,
      "token_endpoint_auth_method": "client_secret_basic",
      "unauth_action": "auth",
      "use_pkce": false,
      "authorization_params": {
        "x-scopes",
        "x-store-uuid"
      }
    },
    "serverless-pre-function": {
      "functions": [
        "return function(conf, ctx) ngx.req.set_header('x-scopes', 'read_store') end"
      ],
      "phase": "log"
    }
  },
  "upstream_id": "stores-service",
  "status": 1
}

**Comment by shreemaan-abhishek** [comment]
I see. This is not supported. Would you like to take this up?

**Comment by zmaren** [comment]
I made a small change directly to openidc.lua plugin from https://github.com/zmartzone/lua-resty-openidc

![CleanShot 2023-12-06 at 15 25 34@2x](https://github.com/apache/apisix/assets/36674206/31a2a747-f775-46c6-bbdf-2fca4ad8876d)

Now for me it works. But for anyone else who wants this, maybe we can have some PR.

**Comment by kayx23** [comment]
Hi @zmaren , could you update the img please? 

![image](https://github.com/apache/apisix/assets/39619599/640d7795-c150-42f1-a992-20e1f1f544b7)
