### ISSUE TITLE
help request:    how set ingress apisix support `proxy_protocol on`

### ISSUE THREAD

**Issue by ccbutcc** [apache/apisix#10629]
### Description

 when i use apisix ingress , how cloud i  set ingress apisix support  `proxy_protocol on`   to get the clinet ip from 4 layer proxy,thanks 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
@Revolyssup please help to answer the question

**Comment by chaiBitch** [comment]
there is a Native Nginx front of apisix as 4 layer proxy, like as user ->Nginx 4 layer -> Apisix Ingress -> K8S . when i set the first native nginx proxy_protocol on to send the clinet_ip to apisix , i don't know how to set the apisix ingress also support the proxy_protocol on , and when i don't add anything on apisix ingress ,it would comes back 400 . i need the apisix ingress to get the real client ip from the first Native Nginx thanks

**Comment by Revolyssup** [comment]
@chaiBitch Can you share the error logs of APISIX when you get the error status code 400?

**Comment by Revolyssup** [comment]
@chaiBitch Please refer to this if you want to use APISIX as L4 proxy here https://apisix.apache.org/docs/apisix/stream-proxy/
You can set this field as true while installing apisix helm chart https://github.com/apache/apisix-helm-chart/blob/462df931a90ed3f5cfa48791e4b86ee2c4909d93/charts/apisix/values.yaml#L287

**Comment by monkeyDluffy6017** [comment]
@ccbutcc please check if @Revolyssup solves your problem

**Comment by ccbutcc** [comment]
This does not solve my problem. You may not understand what I mean. Please take a look at this, [(https://github.com/apache/apisix/issues/10626)]
