### ISSUE TITLE
bug:SNI exception when i upgrade apisix to 3.7 from 3.4

### ISSUE THREAD

**Issue by HankChenCH** [apache/apisix#10622]
### Current Behavior

访问https提示网站无法提供安全连接

### Error Logs

2023/12/09 10:06:23 [error] 12141#12141: *2 [lua] config_etcd.lua:520: load_full_data(): failed to check item data of [/apisix/ssls] err:additional properties forbidden, found validity_start ,val
2023/12/09 10:10:18 [error] 12141#12141: *9213 [lua] init.lua:213: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: manage.gzcots-test.cn, context: ssl_client_hello_by_lua*

### Steps to Reproduce

yum update apisix

### Environment

- APISIX version (run `apisix version`): 3.7.0
- Operating system (run `uname -a`):Linux lb3 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"boot_time":1702087583,"etcd_version":"3.4.0","hostname":"lb3","id":"ec46e0d1-ac03-45f6-aeb1-57880628f21c","version":"3.7.0"}
- APISIX Dashboard version, if relevant:3.0.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Vacant2333** [comment]
Can you provide the URL for HTTPS and use it in English (Current Behavior)

**Comment by HankChenCH** [comment]
> Can you provide the URL for HTTPS and use it in English (Current Behavior)

**Current Behavior**

https://www.gzcots-test.cn:11443/
ERR_SSL_PROTOCOL_ERROR

**Comment by HankChenCH** [comment]
When I downgraded back to version 3.4, everything went back to normal

**Comment by ch4dwick** [comment]
I confirm I have this issue as well. A lower environment created 6 months ago and copied the configs to a production k8s cluster has this error. The production cluster is 3.7.0 while the dev cluster is 3.4.0.

**Comment by ShuLian1984** [comment]
我也出现类似情况.由3.4升级到3.7出现的.现在已经修复了.

|软件|版本|
|:-|:-|
|`APISIX`|3.7.0|
|`ETCD`|3.5.0|
|`APISIX-Dashboard`|3.0.1 (commit_hash: 397c0cb)|

我的使用场景如下:

通过`apisix-dashboard`导入证书,配置4层转发将`sni`为`mqtt.abc.com`的请求转到后端.
访问时,出现报错:
```bash
2023/12/11 20:34:57 [error] 2041778#2041778: *186823 stream [lua] radixtree_sni.lua:177: match_and_set(): failed to find any SSL certificate by SNI: mqtt.abc.com, context: ssl_certificate_by_lua*, client: 10.10.19.55, server: 0.0.0.0:20000
```
修复措施: 通过api创建证书.

通过`apisix-dashboard 3.0.1`版本导入证书可以复现该异常.

通过`/apisix/admin/ssls`接口对比通过api和Dashboard导入的证书信息发现明显差异:
**通过api创建的证书key部分是加密的.而Dashboard是明文的.**

> 初步判断为`APISIX 3.7`和`APISIX Dashboard 3.0.1`存在版本兼容问题.

以上仅供各位参考,希望对大家有所帮助.

**Comment by shreemaan-abhishek** [comment]
I reckon this issue has been resolved now.

**Comment by Zeeeeta** [comment]
> 我也出现类似情况.由3.4升级到3.7出现的.现在已经修复了.
> 
> 软件	版本
> `APISIX`	3.7.0
> `ETCD`	3.5.0
> `APISIX-Dashboard`	3.0.1 (commit_hash: 397c0cb)
> 我的使用场景如下:
> 
> 通过`apisix-dashboard`导入证书,配置4层转发将`sni`为`mqtt.abc.com`的请求转到后端. 访问时,出现报错:
> 
> ```shell
> 2023/12/11 20:34:57 [error] 2041778#2041778: *186823 stream [lua] radixtree_sni.lua:177: match_and_set(): failed to find any SSL certificate by SNI: mqtt.abc.com, context: ssl_certificate_by_lua*, client: 10.10.19.55, server: 0.0.0.0:20000
> ```
> 
> 修复措施: 通过api创建证书.
> 
> 通过`apisix-dashboard 3.0.1`版本导入证书可以复现该异常.
> 
> 通过`/apisix/admin/ssls`接口对比通过api和Dashboard导入的证书信息发现明显差异: **通过api创建的证书key部分是加密的.而Dashboard是明文的.**
> 
> > 初步判断为`APISIX 3.7`和`APISIX Dashboard 3.0.1`存在版本兼容问题.
> 
> 以上仅供各位参考,希望对大家有所帮助.

Same issue to me, apisix 3.7 and dashboard 3.0.1

The key part added by dashboard is plain text and not work, need to use API to add cert.

Really wish the dashboard could be fixed.
