### ISSUE TITLE
help request: how to disable strictly validate the input of core resources

### ISSUE THREAD

**Issue by zxyao145** [apache/apisix#10634]
### Description

In #10233, strict restrictions have been placed on routes, streams, etc. Is it possible to disable this validation?

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`): debian:bullseye-slim
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by luoluoyuyu** [comment]
HI @zxyao145 
There is no external interface for schema validation, and I don't think it's necessary.

**Comment by zxyao145** [comment]
@luoluoyuyu Hi, I'm not sure if it's a version issue. We use `_discovery_type`, but the schema defines it as `discovery_type`, and what I see in the test code is also `_discovery_type`. For `_service_name` has the same issue

https://github.com/apache/apisix/blob/4db435ee38b425da6364ad41aa9c019046190d87/apisix/schema_def.lua#L463-L466


https://github.com/apache/apisix/blob/4db435ee38b425da6364ad41aa9c019046190d87/t/admin/upstream.t#L346-L347

**Comment by luoluoyuyu** [comment]
@zxyao145  It's because this test is checking to see if it's a strict check and needs to return 400 https://github.com/apache/apisix/blob/master/t/admin/upstream.t#L357-L359

**Comment by zxyao145** [comment]
@luoluoyuyu got it, thanks a lot.
