### ISSUE TITLE
help request: Authorization Header causing gateway timeout on WebSocket endpoint

### ISSUE THREAD

**Issue by Austin-Russell** [apache/apisix#10631]
### Description

When creating a route to a WebSocket endpoint I have configured the Authz-Keycloak plugin to validate the route. This plugin requires an Authorization header to be a part of the initial request to the endpoint. When I add the Authorization header to my WebSocket request I am getting a 502 bad gateway response. Without the plugin or Authorization header the endpoint works as expected. If I add the Authorization header without the plugin, I am also getting the 502 bad gateways. Directly hitting the WebSocket service with the header, not going through APISIX, there is no issue. Is there something specific, a configuration setting or something that needs to be added to allow for this header? 

Initial error was a 504 until timeout was set to 100sec and in about 15-20sec the 502 was returned

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): Linux apisix-5bc4759ff8-pwnfj 5.10.184-175.749.amzn2.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by luoluoyuyu** [comment]
Hi @Austin-Russell 
Can you provide error logs?

**Comment by Austin-Russell** [comment]
```
2023/12/12 17:50:14 [error] 47#47: *740472579 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /test-websocket/stream HTTP/1.1", upstream: "http://20.118.132.3:5040/", host: "127.0.0.1:35071"
127.0.0.1 - - [12/Dec/2023:17:50:14 +0000] 127.0.0.1:35071 "GET /test-websocket/stream HTTP/1.1" 502 229 10.167 "-" "-" 20.118.132.3:5040 502 10.167 "http://127.0.0.1:35071/"
```

Above is what is reported out by APISIX when the Authorization Header is added to my request.

**Comment by sheharyaar** [comment]
Hi @Austin-Russell , can you please show how are you adding the Authorization header, along with APISIX error logs ?

**Comment by sheharyaar** [comment]
I would like to look into this

**Comment by Austin-Russell** [comment]
@sheharyaar Please let me know if there is any additional information I can provide. the error logs for APISIX are above. the method in which I am adding the header is via Postman as part of my request.
![image](https://github.com/apache/apisix/assets/16482449/a41c6a68-3fc3-4a65-a665-c668a352ac31)

**Comment by sheharyaar** [comment]
It would be better if you can send the various routes and configs you used with apisix.

**Comment by Austin-Russell** [comment]
[apisix_route_and_upstream_config.txt](https://github.com/apache/apisix/files/13662813/apisix_route_and_upstream_config.txt)
This is the configuration for the route and upstream. there is a service layer that just points to the upstream.
the upstream IP is a service that returns a constant stream of data.

**Comment by sheharyaar** [comment]
@Austin-Russell , can you please provide the authz-keycloak config you used with apisix, you can just mask the credentials / secrets from the config. Your current route config doesn't have this plugin.

**Comment by Austin-Russell** [comment]
The issue occurs with and without the plugin enabled and seems to just matter if the Authorization header is added.

**Comment by sheharyaar** [comment]
Ok, got it. Will test and update.

**Comment by sheharyaar** [comment]
Can I know if you are deploying using Docker ? So here is my test setup. I tested by adding a sample echo websocket server and the apisix in the same network with different IPs.

I used the following request (adapted from your config) : 
```
curl --location --request PUT 'http://127.0.0.1:9180/apisix/admin/routes/1' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data '{
    "uri": "/test-websocket/stream",
    "name": "stream",
    "methods": [
        "GET"
    ],
    "plugins": {
        "proxy-rewrite": {
            "uri": "/"
        }
    },
    "labels": {
        "Test": "Stream"
    },
    "enable_websocket": true,
    "status": 1,
    "upstream": {
        "nodes": [
            {
                "host": "172.18.5.15",
                "port": 8080,
                "weight": 1
            }
        ],
        "timeout": {
            "connect": 100,
            "send": 100,
            "read": 100
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "name": "websocket-upstream",
        "desc": "upstream pointing to websocket.",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    }
}'
```

Even with the authorization header, the websocket works :
![image](https://github.com/apache/apisix/assets/34273345/89005cbd-b6e9-4fae-8ad2-72c16c83b53f)

**Comment by sheharyaar** [comment]
There seems some issue with your deployment, if you are deploying with docker, please make sure the ws endpoint can be reached from the `apisix` container/network

**Comment by Austin-Russell** [comment]
Looked into this some more to narrow down the issue. It looks like APISIX is truncating the Auth token header before sending causing the issue. Is there a way to prevent the truncation of the header data?

**Comment by sheharyaar** [comment]
If you are using Authz-keycloak plugin, it uses Authorization header for it's own authentication : https://github.com/apache/apisix/blob/master/apisix/plugins/authz-keycloak.lua#L516-L518

For using authentication on the websocket server with the same header, you can just append the token like this :
`Authorization: Bearer mF_9.B5f-4.1JqM, Basic YXNkZnNhZGZzYWRmOlZLdDVOMVhk`. 

Please update after trying this out.

**Comment by sheharyaar** [comment]
@Austin-Russell , did the solution work for you ? If yes, please close the issue.

**Comment by Austin-Russell** [comment]
Solved issue as bearer firewall MTU issue was discovered that resolved the issue. was not an API SIX issue.
