### ISSUE TITLE
help request: After setting SSL port 443 still times out

### ISSUE THREAD

**Issue by techcheckri** [apache/apisix#10638]
### Description

I set cert and key to the list of SSLs like this:

```
curl http://127.0.0.1:9180/apisix/admin/ssls/1 \
 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
 {
      "cert" : "'"$(cat /nproj/kubernetes/tls/001/MyCertificate.crt)"'",
      "key": "'"$(cat /nproj/kubernetes/tls/001/MyKey.key)"'",
      "snis": ["mydomain435345.net"]
 }'
```

I can see it in the dashboard.

A route to mydomain435345.net exists and so `curl -ikv http://mydomain435345.net` works

But when I go to mydomain435345.net via https like

`curl -ikv https://mydomain435345.net`

`connect to xx.xx.xx.xx port 443 failed: Die Wartezeit für die Verbindung ist abgelaufen`

I get a timeout.

What could be wrong?

### Environment

Running on Azure, so most is not relevant

- APISIX version (run `apisix version`): command not found.
- Operating system (run `uname -a`): Linux debian 6.1.0-13-amd64 

change: added doc of how to load plugin. apisix#1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): not found
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
No firewall?

**Comment by kayx23** [comment]
Another thing to check for is the port. By default, `9443` is used for TLS encrypted traffic. See [port reference](https://docs.api7.ai/apisix/networking/port-reference) and [relevant docs](https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-mtls-between-client-and-apisix).

**Comment by techcheckri** [comment]
The port reference you refer to does not concern my APISIX ingress, it concerns APISIX itself. So when I connect over port 80 via http I get normal response. For 9080 I get a timeout the same as 443 or 9443.

But I found out the problem. I forgot to set --set gateway.tls.enabled=true in my ingress helm installation as described in the documentation https://apisix.apache.org/docs/ingress-controller/deployments/azure/ .

Thank you very much for taking the time!

Please close the issue!
