### ISSUE TITLE
help request: java plugin  does not work

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/apisix#10649]
### Description

Dear,

I started  apisix(docker) on linux centos , but I tried to acess  java plugin, but got error as below:
{"error_msg":"unknown plugin [ext-plugin-pre-req]"}
**I tried  to fix this issue for  2 weeks, but failed, please help me!**

MacBook-Pro-7:bin mayun$ curl -i http://120.78.123.93:9180/apisix/admin/routes/1 -X PUT -d '

{
"uri": "/index.html",
"plugins": {
"ext-plugin-pre-req": {
"conf" : [
{"name": "DemoFilter", "value": "{"enable":"feature"}"}
]
}
},
"upstream": {
"type": "roundrobin",
"nodes": {
"127.0.0.1:1980": 1
}
}
}'
HTTP/1.1 400 Bad Request
Transfer-Encoding: chunked
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Connection: keep-alive
Content-Type: application/json
Date: Wed, 13 Dec 2023 10:38:25 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Server: APISIX/3.7.0
X-Api-Version: v3

{"error_msg":"unknown plugin [ext-plugin-pre-req]"}

main steps  as below
1.git clone https://github.com/apache/apisix-docker.git
2. change docker-compose.yml  as below
![image](https://github.com/apache/apisix/assets/22955377/cafa7800-af67-4d81-a3a0-ace4c1704f0f)
3.change  apisix_conf/config.yaml as below
![image](https://github.com/apache/apisix/assets/22955377/ddb29ea4-424f-40d9-9c95-5e7e8ab411b4)
4. start docker “ docker-compose -p docker-apisix up -d”
![image](https://github.com/apache/apisix/assets/22955377/4a295056-bfc3-461d-9cf1-91c6a8978a4c)
5.enable the plugin  ext-plugin-pre-req via dashboard
![image](https://github.com/apache/apisix/assets/22955377/eb29d511-fbe5-4a65-979f-0bceb323e674)

6. try to access the demoFIlter plugin
curl -i http://120.78.123.93:9180/apisix/admin/routes/1 -X PUT -d '

{
"uri": "/index.html",
"plugins": {
"ext-plugin-pre-req": {
"conf" : [
{"name": "DemoFilter", "value": "{"enable":"feature"}"}
]
}
},
"upstream": {
"type": "roundrobin",
"nodes": {
"127.0.0.1:1980": 1
}
}
}'

### Environment

APISIX 3.7.0
Operating system linux centos 7
used  docker compose to start the example from docker-apisix.

all docker container info as bellow
![image](https://github.com/apache/apisix/assets/22955377/c9240b78-e8a4-43d8-a15d-10cde41e1567)

**Comment by mayunSaicmotor** [comment]
<img width="1105" alt="image" src="https://github.com/apache/apisix/assets/22955377/eb38ed8e-5ff6-4a3f-9a00-3f855f4f604e">

**Comment by yijieshusheng-git** [comment]
非常感谢大佬
