### ISSUE TITLE
bug: High latency when using `limit-req` plugin

### ISSUE THREAD

**Issue by PScoriae** [apache/apisix#10641]
### Current Behavior

I have Go code that makes 1000 calls to my endpoint on apisix. The code can be modified to support different sleep intervals between each of the calls. I tested three scenarios:
- no sleep interval
- 10ms sleep
- 100ms sleep

For reference, the baseline latency between my machine and the K8s cluster is **~250ms**

| Number of Calls  | Sleep Interval   | Result   |  
|---|---|---|
| 1000  | 0ms  | Response times for all status codes gradually increases. In this case, into the 2-3 second range [code output](https://pastebin.com/CsKHuXrX)  |   
| 1000  |  10ms | 429 response times stay fairly consistent 200s gradually take longer and longer, into the 2-3 second range, followed by a bunch of 200s at the very end [code output](https://pastebin.com/qkyYQ1aY)   |   
| 1000  |  100ms |  Response times start high, but gradually go down to baseline Otherwise, performs as expected [code output](https://pastebin.com/JDBHnG84) |   

### Expected Behavior

Basically, no matter what I set the sleep interval to, I'm expecting the following behavior:
- 429s should return immediately i.e. the response times shouldn't climb that high (it's a rejection anyway)
- 200s should return immediately, except the ones within the range of limit < x < burst. Then, those can be delayed accordingly.

### Steps to Reproduce

1. Run APISIX on Kubernetes using the official Helm charts
2. Deploy a simple Go api that returns 200
3. Add routes and configure the plugins using the ApisixRoute CRD ([ApisixRoute manifest](https://pastebin.com/a4w7KV3w))
4. Run tests on the endpoint as detailed above ([Go code](https://pastebin.com/Paz9n8CF))

### Environment

- APISIX version (run `apisix version`): apache/apisix:3.6.0-debian
- Helm chart version: apisix-2.3.1
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
Performance benchmarking is a complex and error-prone task.
Not only do you need to ensure that the configuration of Apache APISIX is correct (the default configuration is correct), you also need to ensure that:
1. Correct stress testing scripts and tools, we recommend wrk or wrk2
2. An upstream service with sufficient performance, such as the local NGINX echo service
3. Correct configuration between Apache APISIX and upstream services, this is key. Long pooling, timeout configuration, etc.
If you can reproduce this high latency stably, you can add some logs to determine where the main time consuming is, which is helpful for locating possible problems.

**Comment by leowmjw** [comment]
@moonming The upstream is just a Go service that returns immediately (e.g. echo service).  Is point 3 relevant if the upstream is just an echo service?  If it is, please provide us some further guidance.

@PScoriae Maybe can add detailed log for start of request + end; then we can grep out from the the logs for those with anomaly.

BTW when the plugin is disabled; it returns the result with expected stable latency.

**Comment by moonming** [comment]
for `limit-req` plugin, please pay attention to the `nodelay` parameter when benchmark: https://docs.api7.ai/hub/limit-req
