### ISSUE TITLE
help request:  OIDC plugin failed to connect to google

### ISSUE THREAD

**Issue by luoluoyuyu** [apache/apisix#10642]
### Description

Unable to connect to google authentication service

``` 
curl -i "http://127.0.0.1:9180/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
 
  "uri":"/anything/*",
  "plugins": {
    "openid-connect": {
      "client_id": "942299072001-vhduu1uljmdhhbbp7g22m3qsmo246a75.apps.googleusercontent.com",
      "client_secret": "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",
      "discovery": "https://accounts.google.com/.well-known/openid-configuration",
      "scope": "openid email",
      "logout_path": "/anything/logout",
      "redirect_uri": "http://localhost:9080/anything/callback"
    }
  },
  "upstream":{
    "type":"roundrobin",
    "nodes":{
      "httpbin.org:80":1
    }
  }
}'
```

###  log
``` 
accessing discovery url (https://accounts.google.com/.well-known/openid-configuration) failed: timeout
```

However, https://accounts.google.com/.well-known/openid-configuration can be accessed correctly using a browser

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Can't reproduce. I used my google OAuth 2.0 credentials and everything works fine?

![image](https://github.com/apache/apisix/assets/39619599/ea797097-69ab-4986-b170-7b16b185d4ae)

![image](https://github.com/apache/apisix/assets/39619599/e2f8e758-a7bc-42d8-83d8-a085435a6ec8)

![image](https://github.com/apache/apisix/assets/39619599/3b1a9e8e-5479-4aeb-947f-d5129608f672)

How did you install APISIX?

**Comment by luoluoyuyu** [comment]
@kayx23 
Okay, thanks.
