### ISSUE TITLE
help request: mTLS on subpaths

### ISSUE THREAD

**Issue by SalvaChiLlo** [apache/apisix#10647]
### Description

When using mTLS, from what I've seen, it gets configured for the whole domain(SNI).

```json
{
    "sni": "test.com",
    "cert": "<content of server.cer>",
    "key": "<content of server.key>",
    "client": {
        "ca": "<content of ca.cer>"
    }
}
```

Is it possible to enable mTLS just in certain subpaths?

Let's say I have `example.com`, and I want:

- `https://example.com/public` -> to just have TLS
- `https://example.com/private` -> Authenticate via certificate (mTLS)
- `https://example.com/superprivate` -> Authenticate via certificate (mTLS) with another CA

Is that possible? If so, how should that be configured?

### Environment

** I'll not provide any environment details as I'm just evaluating/trying to understand how APISIX works to know if it fits my needs

**Comment by moonming** [comment]
@kayx23 please take a look, thx

**Comment by kayx23** [comment]
It's probably a no, the reasons being that:

* X.509 certs are valid for domains or sub-domains and have no business to do with paths.
* APISIX doesn't offer extra mechanisms (AFAIK?) to to help you implement this by path.

We have some [docs](https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-https-between-client-and-apisix) around the topic where you'll see the (m)TLS is independent of the specific path.

The only thing about mTLS by path/route is https://github.com/apache/apisix/pull/9322 ([docs](https://apisix.apache.org/docs/apisix/3.4/tutorials/client-to-apisix-mtls/#mtls-bypass-based-on-regular-expression-matching-against-uri)), where you can whitelist a path to BYPASS mTLS. But this is not what you want.

**Comment by SalvaChiLlo** [comment]
If the capacity to by pass mTLS in certain subpaths is possible wouldn't it
be possible to have a list of paths that you specifically want mTLS enabled?

**Comment by kayx23** [comment]
Calling in engineering @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
@AlinsRan PTAL

**Comment by monkeyDluffy6017** [comment]
@shreemaan-abhishek PTAL

**Comment by shreemaan-abhishek** [comment]
> be possible to have a list of paths that you specifically want mTLS enabled?

possible but not yet supported.

**Comment by shreemaan-abhishek** [comment]
would you like to contribute this?

**Comment by kayx23** [comment]
somewhat relevant issue: https://github.com/apache/apisix/issues/2992

**Comment by AlinsRan** [comment]
Maybe you can use `skip_mtls_uri_regex`,  it is used to filter non MTLS requests.
Pelease refer to: https://apisix.apache.org/docs/apisix/tutorials/client-to-apisix-mtls/#mtls-bypass-based-on-regular-expression-matching-against-uri

**Comment by monkeyDluffy6017** [comment]
> Maybe you can use `skip_mtls_uri_regex`, it is used to filter non mTLS requests. Pelease refer to: https://apisix.apache.org/docs/apisix/tutorials/client-to-apisix-mtls/#mtls-bypass-based-on-regular-expression-matching-against-uri

@SalvaChiLlo Can this solve your problem?
