### ISSUE TITLE
help request:  how to shutdown the unnecessary logs？

### ISSUE THREAD

**Issue by mayunSaicmotor** [apache/apisix#10661]
### Description

Dear，

I user apisix-docker  to setup test apisix on linux centos server. I found it write logs all the time.
I don't know why it writes these logs, I am sure we didn't access the service. Is there anyway to shutdown the unnecessary logs? thanks.
<img width="1498" alt="image" src="https://github.com/apache/apisix/assets/22955377/abd0179f-9c94-4fcb-ab81-707a16969f22">

I used the command " docker-compose -p docker-apisix up -d" to setup dockers as below:
<img width="1686" alt="image" src="https://github.com/apache/apisix/assets/22955377/f8bb7de0-80d3-4532-bde6-a335a38c3006">

### Environment

- APISIX version  3.7.0
- linux centos 7

**Comment by shreemaan-abhishek** [comment]
looks very strange where did you find these logs?

**Comment by mayunSaicmotor** [comment]
> looks very strange where did you find these logs?
I have known the root cause ， it requested  by the  LBS for health  check!,
