### ISSUE TITLE
help request: how to bind apisix openshift route with wip

### ISSUE THREAD

**Issue by ppkkddqq** [apache/apisix#10674]
### Description

I have deployed the apsix cloud native to openshift, 

Deploymentconfig:  apisix -> Service -> Route

Current we want to cross openshift clusters, thus we apply vip for each custer, and one wip (upper two vips has bind to this wip)

while what i nned to do is to crete a new route use the wip domain 
but i got issue could not resolve dns, do i need other conifg?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lakshya8066** [comment]
Hi @ppkkddqq can you provide error logs and route configurations you used?
