### ISSUE TITLE
docs: improve description of `name` for all logger plugins

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10689]
### Current State

Currently the description for `name` attributes in logging plugins are not entirely clear. See https://github.com/apache/apisix/pull/10650#pullrequestreview-1780855634

### Desired State

Update the `name` attribute description in the docs for all logger plugins to something like:

![image](https://github.com/apache/apisix/assets/39619599/90e964c3-8986-4f12-89cb-aca21cc87926)

**Comment by kayx23** [comment]
This issue also serves as a reference in case users get confused for what the attribute is for and attempts to remove the attribute from the doc.

**Comment by zzzk1** [comment]
hi, @kayx23 it looks good i want to try
