### ISSUE TITLE
feat: As a user, I want to to use the body-transformer plugin for other data formats without warnings

### ISSUE THREAD

**Issue by jesse-r-s-hines** [apache/apisix#10681]
### Description

The body-transformer plugin is a very flexible plugin to modify the body content of requests and responses, and we can already use the `body-transformer` plugin to manipulate arbitrary data formats with the lua templates. However, if you don't specify `input_format` and `Content-Type` isn't JSON or XML it will always log a warning about "no input format to parse request/response body".

Adding another format to the `input_format` enum, `none`, that explicitly tells `body-transformer` to not try to parse or validate the body content and silences this warning would be convenient.

**Comment by shreemaan-abhishek** [comment]
would you like to contribute this?

**Comment by jesse-r-s-hines** [comment]
Sorry for the late reply. I probably won't get time to work on this one myself.

**Comment by smileby** [comment]
@shreemaan-abhishek feel good,  I'd like to try it if needed  ☺

**Comment by jesse-r-s-hines** [comment]
Currently, if you do not specify `input_format` and there's no `Content-Type` header the plugin will skip trying to parse the response body. This allows arbitrary transformations as it doesn't try to parse the body but still runs the template which can access the original body with `_body`.

The only problem is it spams warnings about "no input format to parse request/response body". I'd like an explicit `"input_format": "none"` to just silence that warning.

In our case we also have an upstream service that sometimes returns incorrect `Content-Type` headers, so it would be nice if `"input_format": "none"` caused it to not try to parse the content regardless of `Content-Type` and let the template logic do whatever is necessary to convert to the correct format. Currently if you don't strip `Content-Type` with `response-rewrite` the plugin will abort before calling the template if it can't parse the original response.

So something like:

Original response:
```
Content-Type: application/json
Body:
not actually json
```

Config:
```json
"body-transformer": {
    "response": {
        "template": "{\"message\": \"{* string.gsub(_body, 'not ', '') *}\"}"
    }
}
```

Transformed response:
```
Content-Type: application/json
Body:
{"message": "actually json"}
```



Thanks!

**Comment by smileby** [comment]
@jesse-r-s-hines @shreemaan-abhishek 
Hi, I submitted a PR to solve this issue. Please help confirm the correctness.
