### ISSUE TITLE
help request: grpc server is java, when using grPC-transcode plugin error in the background

### ISSUE THREAD

**Issue by lxz999** [apache/apisix#10686]
### Description

grpc server is java, when using grPC-transcode plugin error in the background. The error is as follows:
Expected header TE: trailers, but null is received. This means some intermediate proxy may not support trailers

### Environment

- APISIX version (run `apisix version`):3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
can you confirm if your setup works correctly without apisix as the proxy?

**Comment by lxz999** [comment]
> can you confirm if your setup works correctly without apisix as the proxy?

Yes, it is accessible without using a proxy

**Comment by shreemaan-abhishek** [comment]
seems similar to #10573

**Comment by sheharyaar** [comment]
@lxz999 , can you please check if applying this PR fixes your issue : #10851

**Comment by sheharyaar** [comment]
This is not related to #10573 , here the call is pure HTTP/2 GRPC, but the referred issue deals with HTTP/1 GRPC-Web calls.
