### ISSUE TITLE
help request:  Changing errors when using vars

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10680]
### Description

When I use the vars route (Example)
```
"vars": [
[
"my-param",
"IN",
[
"32940bbd-593d-0d3b-3514-b10d925ed1b0"
]
    ]
 ]
```
then in case myparam !=  32940bbd-593d-0d3b-3514-b10d925ed1b0  I get a 404 Route Not Found

Can I somehow change this error to my own with a different error code?

### Environment

APISIX version 3.5:
etcd version 3.4.15
APISIX Dashboard version 3.01

**Comment by sheharyaar** [comment]
Hi, you can try checking out the `workflow` plugin : https://apisix.apache.org/docs/apisix/plugins/workflow/

**Comment by shreemaan-abhishek** [comment]
consider resolved.
