### ISSUE TITLE
bug: apisix doesn't work, 'resty.events.compat' not found

### ISSUE THREAD

**Issue by Vacant2333** [apache/apisix#10684]
### Current Behavior

i follow the source installation guild(checkout master), https://apisix.apache.org/docs/apisix/building-apisix/
then start the apisix, it will throw a error like `'resty.events.compat' not found:`

if i checkout to the branch before, it works fine, looks like https://github.com/apache/apisix/pull/10550 makes this

### Expected Behavior

start apisix success, and no errors

### Error Logs
```shell
2023/12/21 11:45:49 [info] 4409#48488: *9 [lua] init.lua:114: http_init_worker(): random test in [1, 10000]: 9291, context: init_worker_by_lua*
2023/12/21 11:45:49 [error] 4406#48485: init_worker_by_lua error: /Users/vacant/apisix/apisix/events.lua:68: module 'resty.events.compat' not found:
	no field package.preload['resty.events.compat']
	no file '/Users/vacant/apisix//deps/share/lua/5.1/resty/events/compat.lua'
	no file '/Users/vacant/apisix//deps/share/lua/5.1/resty/events/compat/init.lua'
	no file '/Users/vacant/apisix/resty/events/compat.lua'
	no file '/Users/vacant/apisix/resty/events/compat/init.lua'
	no file '/opt/homebrew/Cellar/openresty/1.21.4.2_1/site/lualib/resty/events/compat.ljbc'
```

### Steps to Reproduce

follow the source installation guild
https://apisix.apache.org/docs/apisix/building-apisix/
```shell
curl https://raw.githubusercontent.com/apache/apisix/master/utils/install-dependencies.sh -sL | bash -

git checkout master

apisix stop

make deps
sudo make install

apisix start

cat logs/error.log
```

### Environment

- APISIX version (run `apisix version`): 3.7.0
- Operating system (run `uname -a`): Darwin MasterNode.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:34 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8103 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.2
- LuaRocks version, for installation issues (run `luarocks --version`): 3.9.2

**Comment by shreemaan-abhishek** [comment]
for now please change the value of `events`:
https://github.com/apache/apisix/blob/0a85ba4a07fdd58ec01f8deaed568c833fd3717f/conf/config-default.yaml#L143

to `lua-resty-worker-events`. It will fix the issue.

**Comment by shreemaan-abhishek** [comment]
cc: @bzp2010

**Comment by Vacant2333** [comment]
> lua-resty-worker-events

yes, it works!

**Comment by Vacant2333** [comment]
> for now please change the value of `events`:
> 
> https://github.com/apache/apisix/blob/0a85ba4a07fdd58ec01f8deaed568c833fd3717f/conf/config-default.yaml#L143
> 
> to `lua-resty-worker-events`. It will fix the issue.

yes! it works

**Comment by Vacant2333** [comment]
i dont understand why the ci pass, if this work bad on mac only?

**Comment by shreemaan-abhishek** [comment]
> i dont understand why the ci pass, if this work bad on mac only?

not a problem with mac, this occured on linux as well... we are missing some steps.

**Comment by moonming** [comment]
@Vacant2333 please update the install docs.

**Comment by Vacant2333** [comment]
> @Vacant2333 please update the install docs.

did u mean raise a pr to update this line? 
![image](https://github.com/apache/apisix/assets/19872346/aad93b85-5973-4c9a-9be4-1ee8ed3e0cec)

**Comment by Sn0rt** [comment]
1. need new code to ensure the APISIX runwith APISIX-runtime
2. need doc to guide user how to install APISIX-runtime 
3. (option) for macos need `brew`
