### ISSUE TITLE
bug: `keycloak-authz` returns 503 for missing `client_secret` when `lazy_load_paths` is set to true

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10682]
### Current Behavior

If you set `lazy_load_paths` to true in `keycloak-authz` but not configure `client_secret`, you get 503 error:

![image](https://github.com/apache/apisix/assets/39619599/b37b11c8-54f3-4233-941d-0a75980a9c83)

### Expected Behavior

It is better to return a meaningful error message, such as:

![image](https://github.com/apache/apisix/assets/39619599/f5d9ceff-6190-4c7b-820e-d0a4e4dbe738)

### Steps to Reproduce

I have keycloak running at `192.168.1.83`.

Create a route:

```shell
$ curl http://127.0.0.1:9180/apisix/admin/routes/1 -X PUT -d '
{
    "uri": "/*",
    "plugins": {
        "authz-keycloak": {
            "lazy_load_paths": true,
            "discovery": "http://192.168.1.83:8080/realms/quickstart-realm/.well-known/openid-configuration",
            "client_id": "apisix-quickstart-client"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'
```

Send a request to the route:

```shell
$ curl "http://127.0.0.1:9080/anything" -H "Authorization: Bearer $ACCESS_TOKEN"
```

The access token was previously obtained from the token endpoint of keycloak.

### Environment

- APISIX version (run `apisix version`): 3.7.0

**Comment by kayx23** [comment]
After you add the correct `client_secret`, and send the request to the route with the correct token again, you get 500 error from APISIX:

![image](https://github.com/apache/apisix/assets/39619599/9b1558d5-6fec-4124-971f-8c5614c8b762)

because `resource_registration_endpoint` is neither explicitly configured nor presented in the discovery doc:

```text
2023/12/22 00:16:00 [warn] 49#49: *15931 [lua] plugin.lua:1153: run_plugin(): authz-keycloak exits with http status code 503, client: 172.24.0.1, server: _, request: "GET /anything/test HTTP/1.1", host: "127.0.0.1:9080"
2023/12/22 00:16:38 [error] 50#50: *17428 [lua] authz-keycloak.lua:505: authz_keycloak_resolve_resource(): Unable to determine registration endpoint., client: 172.24.0.1, server: _, request: "GET /anything/test HTTP/1.1", host: "127.0.0.1:9080"
2023/12/22 00:16:38 [error] 50#50: *17428 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/authz-keycloak.lua:580: attempt to get length of local 'permission' (a number value)
stack traceback:
coroutine 0:
172.24.0.1 - - [22/Dec/2023:00:16:38 +0000] 127.0.0.1:9080 "GET /anything/test HTTP/1.1" 500 249 0.129 "-" "curl/7.64.1" - - - "http://127.0.0.1:9080"
/usr/local/apisix/apisix/plugins/authz-keycloak.lua: in function 'evaluate_permissions'
/usr/local/apisix/apisix/plugins/authz-keycloak.lua:778: in function 'phase_func'
/usr/local/apisix/apisix/plugin.lua:1148: in function 'run_plugin'
/usr/local/apisix/apisix/init.lua:725: in function 'http_access_phase'
```

The 503 is expected: 

![image](https://github.com/apache/apisix/assets/39619599/716f95dc-9ba7-4c52-b0c4-45494b77c00e)

But the 500?

**Comment by hanqingwu** [comment]
i think need add return err,   in  line 571
![image](https://github.com/apache/apisix/assets/7521141/0164a0a2-e403-4d3e-9d71-09ac0ed7f159)

**Comment by kayx23** [comment]
@hanqingwu cool, would you like to submit a PR for this?

**Comment by hanqingwu** [comment]
ok,  i will do it .

**Comment by monkeyDluffy6017** [comment]
@kayx23 could you create another issue describing your second problem?

**Comment by kayx23** [comment]
@monkeyDluffy6017 away for Christmas, will do when I'm back online.

**Comment by kayx23** [comment]
created: https://github.com/apache/apisix/issues/10708
