### ISSUE TITLE
docs: invitation link for slack - expired

### ISSUE THREAD

**Issue by rumenvasilev** [apache/apisix#10687]
### Current State

The slack invite link needs to be renewed - https://apisix.apache.org/docs/general/join/

### Desired State

slack invite link works

**Comment by kayx23** [comment]
https://join.slack.com/t/the-asf/shared_invite/zt-27w9d4kkn-je1VanFQgw1BU2XqWXMtbQ

please use this link (valid for 9 days) and find `#apisix`
