### ISSUE TITLE
help request: a client request body is buffered to a temporary file 

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#10692]
### Description

There is a system requesting my interface. The request body is relatively large. SocketException: Connection reset appears, and then it is found that /usr/local/apisix/logs/error.log has a large number of a cli Ent request body is buffered to a temporary file log, how should I solve it? I tried to configure it.

```
nginx_config:
  http_server_configuration_snippet: |
    client_body_buffer_size 150m;
    client_max_body_size 150m;
```

It doesn't seem to work, and the client is still Connection reset.

### Environment

- APISIX version (run `apisix version`): 3.6.0
- Operating system (run `uname -a`): Linux localhost 3.10.0-1160.102.1.el7.x86_64 #1 SMP Tue Oct 17 15:42:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: nginx/1.20.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"hostname":"localhost","version":"3.6.0","id":"e88b19cd-f472-4ac9-8dd7-ff883b6d022b","boot_time":1703175766,"etcd_version":"3.5.0"}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by sheharyaar** [comment]
Hi @swtseaman, can you please share your routes, services and other apisix configs, the error logs and the _complete_ steps to reproduce the issue ?

**Comment by swtseaman** [comment]
My timeout configuration
```
"timeout": {
      "connect": 6,
      "send": 6,
      "read": 60
    },
```

I found that the caller basically threw the Connect reset exception after the request was initiated 6s.

**Comment by swtseaman** [comment]
Excuse me, do I need to change connect or send by myself?

**Comment by swtseaman** [comment]
My upstream processing data does exceed 6s.

**Comment by sheharyaar** [comment]
Yes, you can try changing the timeouts : https://apisix.apache.org/docs/ingress-controller/concepts/apisix_upstream/#retries-and-timeouts

**Comment by sheharyaar** [comment]
Sorry, the above config is for the ingress-controller, for requests refer to timeout under : https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters

**Comment by shreemaan-abhishek** [comment]
>  it is found that /usr/local/apisix/logs/error.log has a large number of a cli Ent request body is buffered to a temporary file log, how should I solve it? I tried to configure it.

this is the default behavior of nginx when dealing with large request bodies.

**Comment by swtseaman** [comment]
I tried to modify the timeout time, but there was no problem. I checked some information. The prompt was that the server returned the RST message, which may be related to keepalived. How does the service turn off the keepalive_pool function, or what kind of situation will lead to RST?

**Comment by kayx23** [comment]
Also see https://github.com/apache/apisix/issues/6741

**Comment by shreemaan-abhishek** [comment]
@swtseaman have you solved your problem now?

**Comment by shreemaan-abhishek** [comment]
I will close this due to lack of activity.
