### ISSUE TITLE
help request: change JSON request or response body 

### ISSUE THREAD

**Issue by amyrprv** [apache/apisix#10698]
### Description

Hello,
I am working on a use case where I need to manipulate JSON data in Apisix., I receive JSON requests, and certain properties with encoded keys need to be decrypted and processed using a custom function.
Here's a simplified example of the JSON structure:
```
{
  "credit_cards": [
    {"cvv2": {"encoded": "1233"}},
    {"pin": {"pass": {"encoded": "4323"}}},
    {"cvv": {"new": {"encoded": "3123"}}}
  ]
}
```

Is there a way that I can traverse in the JSON and change my desired property? Also, I can add the paths to the destination field in the plugin conf.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
use the core.json module to decode json to lua_table and then manipulate it then re-encode it to json.

**Comment by amyrprv** [comment]
@shreemaan-abhishek 

The JSON request body can vary significantly in structure. This variability necessitates a more dynamic approach to identifying and manipulating the specific fields (like encoded keys) across different JSON formats. I need a method that allows for such dynamic handling of varying JSON structures

**Comment by shreemaan-abhishek** [comment]
you are looking for modifying the request body or response body?

**Comment by shreemaan-abhishek** [comment]
@amyrprv I'm afraid apisix doesn't support such fine grain control over manipulation of req/resp.

**Comment by shreemaan-abhishek** [comment]
but you can use the serverless plugin to implement your own logic for manipulation. Please close this question if you have no further questions.

**Comment by amyrprv** [comment]
I used [lua-jsonpath](https://github.com/hy05190134/lua-jsonpath).
