### ISSUE TITLE
feat: set `Host` header with NGINX var in `proxy-rewrite` plugin

### ISSUE THREAD

**Issue by lingliy** [apache/apisix#10705]
### Description

Repeat step:
1. proxy-rewrite settting 
curl http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "host": "www.test.com",
    "plugins": {
        "proxy-rewrite": {
            "headers": {
               "set": {
                    "Host": "$host:9977"
                }
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}'

2. curl  www.test.com:9080
3. upstream service expects to receive the Host header www.test.com:9977, but what I actually received was www.test.com:9080

while there are upstream ways to set Host headers, none of these ways support variables.

**Comment by shreemaan-abhishek** [comment]
@sheharyaar can you see if you can reproduce this when you are free?

**Comment by sheharyaar** [comment]
Ok, sure I will have a look at it

**Comment by kayx23** [comment]
Could it be that `host` for `proxy-rewrite` need not to be in `set`? See https://docs.api7.ai/hub/proxy-rewrite#rewrite-host-header

**Comment by lingliy** [comment]
> Could it be that `host` for `proxy-rewrite` need not to be in `set`? See https://docs.api7.ai/hub/proxy-rewrite#rewrite-host-header

Thanks for your reply, but there are two problems: 
1. tnot support variables
2. headers.set in proxy-rewrite does not support host header setting. If so, it is recommended that the documentation clearly state that the host header is not supported by headers.set

**Comment by kayx23** [comment]
> ...there are two problems:
> 
> 1. host field, not support variables
> 2. headers.set in proxy-rewrite does not support host header setting. If so, it is recommended that the documentation clearly state that the host header is not supported by headers.set

1. @sheharyaar please help check.
2. I just tested and agree. I'll take care of the doc update.

**Comment by lingliy** [comment]
> > ...there are two problems:
> > 
> > 1. host field, not support variables
> > 2. headers.set in proxy-rewrite does not support host header setting. If so, it is recommended that the documentation clearly state that the host header is not supported by headers.set
> 
> 1. @sheharyaar please help check.  (UPDATE: indeed not supported, it'd be a feat)
> 2. I just tested and agree. I'll take care of the doc update.

Thank you. I'll close the issue
