### ISSUE TITLE
feat: As a user, I want to use the LDAP plugin to support connecting ldap server with password

### ISSUE THREAD

**Issue by FOWind** [apache/apisix#10706]
### Description

I check the PR history found that ldap plugin has suffer a lot .
https://github.com/apache/apisix/pull/9254  upgrade to 0.2.2
https://github.com/apache/apisix/pull/9936 & https://github.com/apache/apisix/issues/9891 downgrade to 0.1.0

On my scene, 0.1.0 doesn't support connecting to ldap server with a password. It's hard to imagine that connecting to ldap server without password in product environment.

I think it's necessary to upgrade to 0.2.2 .

**Comment by shreemaan-abhishek** [comment]
having rust dependencies in apisix was leading to some trouble... but I am unable to recall properly.
