### ISSUE TITLE
As a developer, I want to get a plugin using for every single api/url like api-breaker plugin, so that I ask for help

### ISSUE THREAD

**Issue by YYYY-MM-DD** [apache/apisix#10714]
### Description

Hi, Dear APISIX team,

   As a developer, I hope to get a plugin using for every single api/url like api-breaker plugin, so that I ask for help.
   I got a issue that we want to break off a single api when it is unhealthy.
   The api-breaker Plugin implements circuit breaker functionality to protect Upstream services.
   I found it is using for the whole upstream when the healthy-check is failed. 
   But I hope to get a plugin using for a single api when it is unhealthy.
   For example, I got a api in my upstream like /app/user/save.When this api return the 503 response code for 5 times, I hope Apisix catch the error code and take effect the plugin to break the next request, but for other apis, it won't be take effect.

   What I mean is to implement a plugin that like Hystrix or Sentinel for every single api. 
   Would you please be kind to share me if there already exists a plugin like this? Or any developement schedule for the new plugin like this?
   Looking forward to any suggestions from you.
   Thank you! 
   Have a nice day!

**Comment by YYYY-MM-DD** [comment]
What I mean is to implement a plugin that like Hystrix or Sentinel for every single api. Thank you!

**Comment by shreemaan-abhishek** [comment]
I don't think any such plugin exists, @lakshya8066 do you have any idea if such plugin exists?

**Comment by lakshya8066** [comment]
I have not come across such a plugin yet, but I am wondering if there is a way we can use the workflow plugin to achieve this...

**Comment by Vacant2333** [comment]
i think the [http-logger](https://apisix.apache.org/docs/apisix/next/plugins/http-logger/) and [error-logger](https://apisix.apache.org/docs/apisix/next/plugins/error-log-logger/) can help u , eg. forward the error log to your application(it will check if there is 5*`503` error, if this happen, do something like stop the route), It can achieve your goal, although I think it will be less efficient in terms of performance.

**Comment by shreemaan-abhishek** [comment]
@YYYY-MM-DD, do the above suggestions help you? If not, you may write your logic in lua and use it in the serverless plugin. I will close this issue for now.
