### ISSUE TITLE
help request: about the plugin of prometheus

### ISSUE THREAD

**Issue by HaoTien** [apache/apisix#10734]
### Description

I can't find the func’s entrance of prometheus‘s plugin.
I looked through all the code of v3.6.0 and can't find where to enter this function of log

![image](https://github.com/apache/apisix/assets/32786491/c8b2cede-a9e5-49fd-937a-d1f81c9e1f41)

maybe is it there？
![image](https://github.com/apache/apisix/assets/32786491/195a427e-7c6e-4194-9456-f956edb626a9)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by HaoTien** [comment]
If I only open the plugin  of prometheus,  and do not bind the plugin for any routes， is not only set prometheus to the global_rule can call this function of log?

**Comment by shreemaan-abhishek** [comment]
https://github.com/apache/apisix/blob/105993f40f34768cd0a86035d01393346fff3a94/apisix/plugins/prometheus/exporter.lua#L222 here

**Comment by shreemaan-abhishek** [comment]
> If I only open the plugin of prometheus, and do not bind the plugin for any routes， is not only set prometheus to the global_rule can call this function of log?

I don't understand you.

**Comment by kayx23** [comment]
What are you trying to achieve? Customizing the plugin?

The prometheus plugin (or any other plugin) can be enabled on a global scale (with global rules), or locally (with routes, services, plugin configs). The global plugins execute before the local ones.

**Comment by HaoTien** [comment]
> https://github.com/apache/apisix/blob/105993f40f34768cd0a86035d01393346fff3a94/apisix/plugins/prometheus/exporter.lua#L222
> 
> here

I can find func‘s implementation, but don't know where to invok it

**Comment by shreemaan-abhishek** [comment]
> I can find func‘s implementation, but don't know where to invok it

This `http_log` function is exported as a `log` function by `prometheus.lua`
https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/plugins/prometheus.lua#L37

Which is then executed by APISIX in the `log` phase of `openresty`.

https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/init.lua#L863
https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/cli/ngx_tpl.lua#L789C1-L792C14

**Comment by HaoTien** [comment]
> > I can find func‘s implementation, but don't know where to invok it
> 
> This `http_log` function is exported as a `log` function by `prometheus.lua`
> 
> https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/plugins/prometheus.lua#L37
> 
> Which is then executed by APISIX in the `log` phase of `openresty`.
> 
> https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/init.lua#L863
> 
> 
> https://github.com/apache/apisix/blob/3a48d17889cf1283e63a6e2b44ed33ab07dc4588/apisix/cli/ngx_tpl.lua#L789C1-L792C14

thx！ the func of http_log_phase() is exactly what I'm looking for.
