### ISSUE TITLE
help request: vars does not have time to rearrange the parameter and returns 404 the route was not found

### ISSUE THREAD

**Issue by pavlenkodev** [apache/apisix#10730]
### Description

I have a serverless-pre-function plugin(GLOBALY) configured that gets a parameter from the authorization token coming in the request and registers it as an apisix variable. Serverless-pre-function processes globally for each request that comes to apisix.

Vars with the built-in parameter are configured on the route. Vars checks my registered serverless-pre-function parameter for compliance. If the parameter does not match, we get 404 route not found and this is normal in such a situation. If the parameter matches, the request is processed by the route

Problem :  When Apisix does not receive requests for 3+ minutes, the first request returns 404 route not found even if all the input parameters of the request are correct. As if Apicis falls asleep for a while, and then does not have time to check for vars
If you make requests constantly for some time, everything works well and the problem does not manifest itself

This is my serverless-pre-function global rule plugin

```
curl -X PUT \
http://localhost:9180/apisix/admin/global_rules/1 \
-H 'Content-Type: application/json' \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
-d '{
          "plugins": {
    "serverless-pre-function": {
	 "_meta": {
              "priority": 30000
            },
      "functions": [
        "return function() local core = require(\"apisix.core\").ctx.register_var(\"sub\",function(ctx) local core = require(\"apisix.core\") local jwt = require(\"resty.jwt\") local sub_not_found = \"not found\" local access_token = core.request.header(ctx, \"Authorization\") local result_value; if not access_token then result_value = sub_not_found return result_value end local jwt_obj = jwt:load_jwt(access_token) result_value = tostring(jwt_obj.payload.sub) return result_value end ) end"
      ],
      "phase": "rewrite"
    }
  }
}'
```

This is my route
```
{
  "uri": "/*",
  "name": "test",
  "methods": [
    "GET"
  ],
  "vars": [
    [
      "sub",
      "IN",
      [
        "123435"
      ]
    ]
  ],
  "upstream_id": "my-upstream",
  "status": 1
}
```

What could be the problem? Maybe I need to disable sleep mode somewhere? I will be glad of your help

### Environment

APISIX version 3.5:
etcd version 3.4.15
APISIX Dashboard version 3.01

**Comment by Vacant2333** [comment]
can u format the plugin's function, its hard to read

**Comment by luoluoyuyu** [comment]
The returned functions are as follows
```
return function()
    local core = require("apisix.core")
    
    core.ctx.register_var("sub", function(ctx)
        local core = require("apisix.core")
        local jwt = require("resty.jwt")
        local sub_not_found = "not found"
        
        local access_token = core.request.header(ctx, "Authorization")
        local result_value
        
        if not access_token then
            result_value = sub_not_found
            return result_value
        end
        
        local jwt_obj = jwt:load_jwt(access_token)
        result_value = tostring(jwt_obj.payload.sub)
        
        return result_value
    end)
end
```

**Comment by pavlenkodev** [comment]
> Hi @Vacant2333 The returned functions are as follows.Its main purpose is to extract the "sub" claim from a JWT found in the "Authorization" header of an HTTP request. If the header is missing or the JWT is not present, it returns the default value "not found."
> 
> ```
> return function()
>     local core = require("apisix.core")
>     
>     core.ctx.register_var("sub", function(ctx)
>         local core = require("apisix.core")
>         local jwt = require("resty.jwt")
>         local sub_not_found = "not found"
>         
>         local access_token = core.request.header(ctx, "Authorization")
>         local result_value
>         
>         if not access_token then
>             result_value = sub_not_found
>             return result_value
>         end
>         
>         local jwt_obj = jwt:load_jwt(access_token)
>         result_value = tostring(jwt_obj.payload.sub)
>         
>         return result_value
>     end)
> end
> ```

Due to the different time zones, I couldn't answer right away. Thank you!

**Comment by Vacant2333** [comment]
> > Hi @Vacant2333 The returned functions are as follows.Its main purpose is to extract the "sub" claim from a JWT found in the "Authorization" header of an HTTP request. If the header is missing or the JWT is not present, it returns the default value "not found."
> > ```
> > return function()
> >     local core = require("apisix.core")
> >     
> >     core.ctx.register_var("sub", function(ctx)
> >         local core = require("apisix.core")
> >         local jwt = require("resty.jwt")
> >         local sub_not_found = "not found"
> >         
> >         local access_token = core.request.header(ctx, "Authorization")
> >         local result_value
> >         
> >         if not access_token then
> >             result_value = sub_not_found
> >             return result_value
> >         end
> >         
> >         local jwt_obj = jwt:load_jwt(access_token)
> >         result_value = tostring(jwt_obj.payload.sub)
> >         
> >         return result_value
> >     end)
> > end
> > ```
> 
> Due to the different time zones, I couldn't answer right away. Thank you!

hello, have u resoulve your problem now

**Comment by pavlenkodev** [comment]
> > > Hi @Vacant2333 The returned functions are as follows.Its main purpose is to extract the "sub" claim from a JWT found in the "Authorization" header of an HTTP request. If the header is missing or the JWT is not present, it returns the default value "not found."
> > > ```
> > > return function()
> > >     local core = require("apisix.core")
> > >     
> > >     core.ctx.register_var("sub", function(ctx)
> > >         local core = require("apisix.core")
> > >         local jwt = require("resty.jwt")
> > >         local sub_not_found = "not found"
> > >         
> > >         local access_token = core.request.header(ctx, "Authorization")
> > >         local result_value
> > >         
> > >         if not access_token then
> > >             result_value = sub_not_found
> > >             return result_value
> > >         end
> > >         
> > >         local jwt_obj = jwt:load_jwt(access_token)
> > >         result_value = tostring(jwt_obj.payload.sub)
> > >         
> > >         return result_value
> > >     end)
> > > end
> > > ```
> > 
> > 
> > Due to the different time zones, I couldn't answer right away. Thank you!
> 
> hello, have u resoulve your problem now

Hi! No, the problem has not been solved. It was marked as a bug and is now in the backlog. I have not found any other options for implementing such functionality

**Comment by shreemaan-abhishek** [comment]
@pavlenkodev could you also share the request (as a curl command) that causes this issue? 404 route not found error is usually by apisix itself when it fails to match a route. I'm sure that serverless plugin has nothing to do with it.

**Comment by pavlenkodev** [comment]
Hello!  I also think that the serverless-plugin has no problem. I suspect that the error occurs in vars[ ] when using built-in parameter.

Base example
```
curl "http://localhost:9080/my-route"  -H "Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NSIsIm5hbWUiOiJKb2huIERvZSIsImlhdCI6MTUxNjIzOTAyMn0.0flS6CW7wKowP05D5aTQTIAAc0GnNjwr7o5JEVgqwto"
```
This authorization token contains sub = 12345, which I specified in my test route. To generate a token, I use jwt.io website
Before the route can process the request, it is necessary that the built-in parameter with the name sub = 12345
I also specified "IN" in vars, since I use it myself and the bug is reproduced under such conditions. That is, when solving a problem, it is necessary to look at a case in which several parameters are expected in vars by "IN".

@shreemaan-abhishek Did I understand you correctly and will my answer help in any way? or have I not disclosed the topic enough?

**Comment by shreemaan-abhishek** [comment]
okay I get it now. The problem is in your custom serverless function and your understanding of the serverless function.

Route matching always happens before any plugins are executed. According to your route configuration, the very first time you try to access your route, it will look for the `sub` variable, which has not yet been registered because the serverless plugin hasn't yet been executed (it can only be executed post route matching).

I hope this resolves your problem.

**Comment by pavlenkodev** [comment]
At the moment, this makes my problem unsolvable, because I was counting on such functionality😒
As far as I understand, there is no way I can change the priorities of the route mapping? Is there an option in which I could avoid getting a 404 error using approximately the same logic that I described above?

**Comment by pavlenkodev** [comment]
@shreemaan-abhishek I just started experimenting and trying to get a 404 error by removing vars, serverless-function
And I did it, at some point (much less often) I get a 404 route not found and at the same time the plugins are initialized again in the apisix logs
![image](https://github.com/apache/apisix/assets/54456916/83b1b9e1-5075-4e2a-b730-9bc6ac14e306)

Even if the problem with vars and serverless is more or less clear, but what could be the problem of restarting plugins? I sent you a screenshot of the part, but after the restart starts, it goes on cyclically and doesn't stop for a while.

**Comment by shreemaan-abhishek** [comment]
> but what could be the problem of restarting plugins? I sent you a screenshot of the part, but after the restart starts, it goes on cyclically and doesn't stop for a while.

Please create another issue for this.

**Comment by shreemaan-abhishek** [comment]
APISIX reload could have triggered this but if these logs appear repeatedly this is an abnormal behaviour. Could you please look into this and create another issue? If that's okay, you can close this one thanks.

**Comment by pavlenkodev** [comment]
I think I got the answer to this problem, I'll try to find out what causes Apisix to reload. Thank you!

> APISIX reload could have triggered this but if these logs appear repeatedly this is an abnormal behaviour. Could you please look into this and create another issue? If that's okay, you can close this one thanks.
