### ISSUE TITLE
bug: cann't delete an upstream node for the route

### ISSUE THREAD

**Issue by learnt** [apache/apisix#10743]
### Current Behavior

i cann't delete an **existed** upstream node for the route?
curl http://127.0.0.1:9180/apisix/admin/routes/12345\
-H 'X-API-KEY: xxxxxx' -X PATCH -i -d '
{
    "upstream": {
        "nodes": {
            "10.46.12.11:8800": null
        }
    }
}'

HTTP/1.1 400 Bad Request
Date: Wed, 03 Jan 2024 02:05:58 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
X-API-VERSION: v3

{"error_msg":"invalid configuration: property \"upstream\" validation failed: property \"nodes\" validation failed: object matches none of the required"}

### Steps to Reproduce

see description above

### Environment

- APISIX version (run `apisix version`):3.6.0
- Operating system (run `uname -a`):Linux apisix0 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"hostname":"apisix0","id":"31f4aaa7-9005-42ea-b22b-6f2c3977ceea","etcd_version":"3.5.0","version":"3.6.0","boot_time":1700613252}

**Comment by hanqingwu** [comment]
why not delete route directly ?

**Comment by shreemaan-abhishek** [comment]
just edit the upstream config to remove the node that you don't want. Remember that atleast one node should be present in the config.

**Comment by shreemaan-abhishek** [comment]
please close this issue if I answered your question.

**Comment by learnt** [comment]
> why not delete route directly ?

i just need to delete one node, thanks for replying.

**Comment by hanqingwu** [comment]
ok, you can get advice from shreemaan-abhishek  by  remove the node and rewrite config

**Comment by learnt** [comment]
> just edit the upstream config to remove the node that you don't want. Remember that atleast one node should be present in the config.

a node is going to restart for update, so i delete add it again to avoid request handling when the node is not ready, do you have any good idea to achieve this?

**Comment by hanqingwu** [comment]
https://apisix.apache.org/docs/apisix/tutorials/health-check/
maybe help you @learnt
