### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by qingtianbuyu** [apache/apisix#10747]
### Description

麻烦问下这个插件在哪里：
https://www.apiseven.com/blog/apisix-soap-to-rest-plugin

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Vacant2333** [comment]
https://apisix.apache.org/zh/docs/apisix/next/plugins/body-transformer/ its looks like this plugin

**Comment by hanqingwu** [comment]
这里有说是企业版的插件

This is an Enterprise plugin, [contact us](https://api7.ai/contact) for more information.

https://api7.ai/blog/apisix-soap-to-rest-plugin

**Comment by kayx23** [comment]
Please see the following resources:

* `soap` (enterprise): https://docs.api7.ai/hub/soap
* `body-transformer` (oss): https://docs.api7.ai/hub/body-transformer#transform-between-json-and-xml-soap

**Comment by qingtianbuyu** [comment]
ok， thanks for all of you～
