### ISSUE TITLE
help request: How to config xds?

### ISSUE THREAD

**Issue by Mararesliu** [apache/apisix#10752]
### Description

I want use apisix mesh, how can i config xds on 3.7.0 version. Is there any detail guide? I adapted 3.7.0, finally get xds-cofig-version nil value.

### Environment

- APISIX version (run `apisix version`): 3.7.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 5.1

**Comment by shreemaan-abhishek** [comment]
you mean this? https://github.com/api7/Amesh

**Comment by Mararesliu** [comment]
Yes, this project apisix version is 2.15, i try to match 3.7 verison. And this project seem like no body maintains it. Is there any plan to make apisix mesh?

**Comment by Mararesliu** [comment]
And i see cofing_provider for xds, bu not doc found on website that how to use it.

**Comment by shreemaan-abhishek** [comment]
if you have questions about amesh please open issues in amesh repository, thanks.
