### ISSUE TITLE
help request:  How to manually intervene in upstream in consul mode

### ISSUE THREAD

**Issue by creaplus** [apache/apisix#10758]
### Description

I am developing a plug-in to switch different development environments through the different value of X-Ca-Stage in the header. If the value is equal to pre, I expect to forward the traffic to the pre-issued apisix cluster. Now I use the consul service and find that I cannot control this proxy to the environment I specified. How should I develop it in the plug-in?

Also, do we have a Chinese communication group?

### Environment

- APISIX version (run `apisix version`): 3.7
- Operating system (run `uname -a`): docker Linux dee16c4d1bc3 6.5.11-linuxkit  SMP PREEMPT Wed Dec  6 17:08:31 UTC 2023 aarch64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5
- APISIX Dashboard version, if relevant: 3.0
- Plugin runner version, for issues related to plugin runners:  custom plugins

**Comment by Vacant2333** [comment]
chinese communication group:(qq) 552030619

**Comment by shreemaan-abhishek** [comment]
so you want to route request to different upstream nodes based on the header value?

**Comment by shreemaan-abhishek** [comment]
> so you want to route request to different upstream nodes based on the header value?

if yes then you may use the serverless-plugin. I will close this issue for now due to lack of activity.
