### ISSUE TITLE
help request: I need to replace the URL in the 'location' header of an HTTP 302 response

### ISSUE THREAD

**Issue by xxoxx** [apache/apisix#10753]
### Description

I need to replace the URL in the 'location' header of an HTTP 302 response. Here is the response I'm getting:
```

curl https://blog.xxx.com.cn:19443/wp-admin/ -I
HTTP/2 302
content-type: text/html; charset=UTF-8
location: http://blog.xxx.com.cn:19080/wp-login.php
```

I need to change the URL in the 'location' header from http://blog.xxx.com.cn:19080 to https://blog.xxx.com.cn:19443. I tried using response-rewrite in the filters, but it seems it can only perform replacements in response.body and does not support response.header. How can I solve this problem?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
@xxoxx ,   Maybe you can try rewrite-plugin  like this ?

    "plugins": {
        "redirect": {
            "uri": "https://blog.xxx.com.cn:19443/",
            "ret_code": 302
        }
    },

**Comment by xxoxx** [comment]
@hanqingwu    I have tried the redirect plugin, but it might not quite fit my needs. The redirect plugin can transform specific URIs in a request into specified 301 or 302 redirects. However, my requirement is to replace an existing specified 301 or 302 redirect URL in the response with a different specified address.

**Comment by hanqingwu** [comment]
ok, i get it , maybe you can try this ?
```
    "response-rewrite": {
      "headers": {
        "set": {
          "Location": "https://blog.xxx.com.cn:19443/"
        }
      }
    }
```

**Comment by xxoxx** [comment]
@hanqingwu  The method you suggested might not be suitable for me, because when I request the URL https://blog.xxx.com.cn:19443/wp-admin/, if I have not yet passed the user login verification of the program, it will redirect to http://blog.xxx.com.cn:19080/wp-login.php with a 302 response. However, if I have already passed the user login verification, there won't be a 302 redirect. In the solution you provided, a 302 redirect would occur regardless of whether I am logged in or not, which is inconsistent with the program's own logic.

**Comment by hanqingwu** [comment]
in this condition, maybe you should try use vars to match condition 
for example status 403 or others ? 
``` 
     "uri": "https://blog.xxx.com.cn:19443/wp-admin/",
    "response-rewrite": {
      "headers": {
        "set": {
          "Location": "http://blog.xxx.com.cn:19080/wp-login.php"
        }
      },
      "vars":[
                [ "status","==",403 ]
            ]
    }
```
     
https://apisix.apache.org/docs/apisix/plugins/response-rewrite/
