### ISSUE TITLE
docs: invitation link for slack

### ISSUE THREAD

**Issue by 1473371932** [apache/apisix#10751]
### Current State

The slack invite link needs to be renewed - https://apisix.apache.org/docs/general/join/

### Desired State

slack invite link works

**Comment by kayx23** [comment]
This link is valid for 30 days from now: https://join.slack.com/t/the-asf/shared_invite/zt-2a8jmj7hc-feDQV3OpBraUCX4jrILLvA

**Comment by 1473371932** [comment]
> This link is valid for 30 days from now: https://join.slack.com/t/the-asf/shared_invite/zt-2a8jmj7hc-feDQV3OpBraUCX4jrILLvA

thank you

**Comment by jaskeerat789** [comment]
@kayx23 it has expired now, can you please share a fresh invite link. Thanks

**Comment by kayx23** [comment]
https://join.slack.com/t/the-asf/shared_invite/zt-2cvbln69z-P~cIEtIWgYVwD2TQStz5hw
