### ISSUE TITLE
help request: The dubbo proxy plugin is not displayed on the dashboard page

### ISSUE THREAD

**Issue by Python-IBM** [apache/apisix#10766]
### Description

1.Enable dubbo proxy in the apisix and apisix dashboard config files
2.The dubbo proxy plugin is not displayed on the dashboard page
![image](https://github.com/apache/apisix/assets/33851767/a101676a-3a22-44ec-808d-11795e2e8ec9)

### Environment

- APISIX version (run `apisix version`): 3.6.0-debian
- Operating system (run `uname -a`): linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.15
- APISIX Dashboard version, if relevant: 3.0.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by SilentEntity** [comment]
Please read: https://apisix.apache.org/docs/apisix/plugins/dubbo-proxy/
