### ISSUE TITLE
help request: 能否提供集成有 Tongsuo的docker镜像

### ISSUE THREAD

**Issue by hello-000** [apache/apisix#10767]
### Description

能否提供集成有 Tongsuo的docker镜像，自己编译太麻烦了，还不成功.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lakshya8066** [comment]
@hello-000 I am not sure if this feature can be taken up on priority right now.
You are welcome to submit a PR on this if you want

**Comment by Vacant2333** [comment]
@hello-000 hi, the `apisix-docker` repo was fixed now, u can build this image by yourself, i dont think this feat we should process it, @shreemaan-abhishek can u help check and i think we could close it now
