### ISSUE TITLE
help request: failed to match any SSL certificate by SNI 

### ISSUE THREAD

**Issue by 223311** [apache/apisix#10772]
### Description

Hi team,
I am running the apisix docker image on my local.
docker run -d --name apache-apisix -p 9080:9080 -p 9443:9443 -p 2379:2379 -e APISIX_STAND_ALONE=true apache/apisix

but when i hit the url like http://localhost:9080 -it shows {"error_msg":"404 Route Not Found"} which is expected.
when i tam trying to hit the url https://localhost:9443 it shows **error ssl protocol.**
i am trying from the latest chrome.
and in error log it shows:

2024/01/07 04:42:36 [error] 36#36: *6704 [lua] init.lua:213: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: localhost, context: ssl_client_hello_by_lua*, client: 172.18.0.1, server: 0.0.0.0:9443
2024/01/07 04:42:36 [error] 35#35: *6788 [lua] init.lua:213: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: localhost, , context: ssl_client_hello_by_lua*, client: 172.18.0.1, server: 0.0.0.0:9443
2024/01/07 04:42:36 [error] 34#34: *6831 [lua] init.lua:213: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: localhost, , context: ssl_client_hello_by_lua*, client: 172.18.0.1, server: 0.0.0.0:9443
2024/01/07 04:42:37 [error] 40#40: *6906 [lua] init.lua:213: http_ssl_client_hello_phase(): failed to match any SSL certificate by SNI: localhost, , context: ssl_client_hello_by_lua*, client: 172.18.0.1, server: 0.0.0.0:9443

could you please help here..
I am excepting.. it should serve selfsigned/dummy certificate and return the response. 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by SilentEntity** [comment]
Please read https://apisix.apache.org/docs/apisix/ssl-protocol/#ssl_protocols-configuration.  Not an issue.

**Comment by 223311** [comment]
@SilentEntity  - Thanks for getting back to me. The link you sent discusses the domain name, but I'm accessing the URL locally, and the Apisix pod is running on the same instance. I'm attempting to access it through Chrome.

**Comment by 223311** [comment]
Thanks,For the help .it got resolved by adding certificate to the apisix of localhost. Thank you so much..

**Comment by bfyxzls** [comment]
thanks

**Comment by sultra** [comment]
I have same problem, the same solutions；the problem occurs when ssl cert added with API-Dashboard, but it can be viewed with admin api, which is very strange

**Comment by SkyeYoung** [comment]
@sultra Hi, we have built a new dashboard in APISIX 3.13.0. The old version is no longer maintained. You can refer to:

1. [notice (release)](https://github.com/apache/apisix-dashboard/releases/tag/notice)
2. Apache APISIX Dashboard Roadmap & Scopes #2981
3. [apisix.apache.org/docs/apisix/next/getting-started/README#validate](https://apisix.apache.org/docs/apisix/next/getting-started/README/#validate)

Please try the new dashboard, and do not ask irrelevant questions under closed issues.
