### ISSUE TITLE
feat: Refactoring config update from etcd 

### ISSUE THREAD

**Issue by hankai17** [apache/apisix#10783]
### Description

![image](https://github.com/apache/apisix/assets/20820539/eb91b9d2-5ef2-42ce-9181-bf30c154c785)

**Comment by lakshya8066** [comment]
Hi @hankai17 thanks for opening the issue.
Could you please provide a short description as well?

**Comment by Vacant2333** [comment]
@hankai17 hi, can u provide some descripthion and the english diagram? after that, we can discuss this feat together!
