### ISSUE TITLE
bug: APISIX master is no longer compatible with openresty on macos

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#10784]
### Current Behavior

The current APISIX master is no longer adapted to openresty. Currently, script installation dependencies still automatically install dependencies on openresty, which is not as expected. Expect APISIX-runtime to be installed automatically.

### Expected Behavior

```diff
diff --git a/utils/install-dependencies.sh b/utils/install-dependencies.sh
index bdf54598..5efff972 100755
--- a/utils/install-dependencies.sh
+++ b/utils/install-dependencies.sh
@@ -84,7 +84,7 @@ function install_dependencies_with_apt() {
 # Install dependencies on mac osx
 function install_dependencies_on_mac_osx() {
     # install OpenResty, etcd and some compilation tools
-    brew install openresty/brew/openresty luarocks lua@5.1 wget curl git pcre openldap
+    brew install luarocks wget curl git pcre openldap
 }

 # Identify the different distributions and call the corresponding function
```

### Steps to Reproduce

make deps with macos

1. make deps

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lakshya8066** [comment]
Yes, I am facing the same issue

**Comment by lakshya8066** [comment]
I am facing the issues on mac

**Comment by Vacant2333** [comment]
i have this problem too, im going to find a way to resoulve that now ((

**Comment by Vacant2333** [comment]
I don't think we should consider that users build / deploy `APISIX` with source code on `MacOS`. Although it is very convenient to develop on `MacOS` at the beginning, it can only support basic development capabilities. When you need to use tools such as `Flame Diagram`, `gdb` and so on, you still need to switch to the Linux system. I am going to delete the content about `MacOS` in this `install-dependsices.sh` and update a best practice in the document `Develop APISIX on MacOS by Docker`.

**Comment by membphis** [comment]
>  I am going to delete the content about MacOS in this install-dependsices.sh and update a best practice in the document Develop APISIX on MacOS by Docker.

agree with this, vote +1
