### ISSUE TITLE
help request: How to configure through hybrid mode using Apisix

### ISSUE THREAD

**Issue by flylan** [apache/apisix#10786]
### Description

I have a question about apisix configuration，Is there a deployment method that allows some of the configuration of Apisix to be stored in YAML (such as domain name resolution configuration) and some configuration to be stored in ETCD (such as IP pool in IP blocking plugin)

From the perspective of operation and maintenance personnel, most configurations are not frequently changed. These configurations should be stored in yaml files, which make people more confident and convenient for version tracking in git. Moreover, yaml configurations can be like code, distinguishing different environments and following the devops process.

From the perspective of developers, some configurations need to be changed in real time, such as the IP pool in the IP blocking plugin. Programs can dynamically block certain abnormal IPs based on business conditions, such as crawler IPs or IPs with abnormal traffic.

I noticed that Apisix 3. x version provides the decoupled mode, which separates the data plane from the control plane. I'm not sure if this mode can solve my problem
https://apisix.apache.org/docs/apisix/deployment-modes/

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by flylan** [comment]
Based on my current usage, most of the API configurations are rarely changed, with only a very small number requiring API updates. However, I can only choose to store the configuration through ETCD and post all API configurations to the API interface in a curl manner through a bash script. I also write every configuration curl request into a bash script to enable version tracking of all configurations

**Comment by shreemaan-abhishek** [comment]
no this isn't supported yet.
