### ISSUE TITLE
Do we have plugin to limit the concurrent tcp connections?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#10789]
### Description

My apisix instance's cpu will high if it handle too many SSL connections, so i want to limit the concurrent ssl  connections, what's the best practice for it? Thanks in advance.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
https://apisix.apache.org/docs/apisix/plugins/limit-conn/

**Comment by Vacant2333** [comment]
@purekeeper i think your problem was resloved now, pls confirm that and close this issue

**Comment by shreemaan-abhishek** [comment]
I'll consider this as resolved.
