### ISSUE TITLE
help request: curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by samsu-lb** [apache/apisix#10791]
### Description

docker-compose 两个节点
我记得之前是可以的，增加成集群的方式后方式变了？

root@ip-10-10-10-37:/project/apisix-docker# curl -vvvvv -i "http://127.0.0.1:9180/apisix/admin/routes" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
*   Trying 127.0.0.1:9180...
* Connected to 127.0.0.1 (127.0.0.1) port 9180 (#0)
> PUT /apisix/admin/routes HTTP/1.1
> Host: 127.0.0.1:9180
> User-Agent: curl/7.81.0
> Accept: */*
> X-API-KEY: edd1c9f034335f136f87ad84b625c8f1
> Content-Length: 143
> Content-Type: application/x-www-form-urlencoded
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

### Environment

apisix image: apache/apisix:${APISIX_IMAGE_TAG:-3.7.0-debian}
Linux ip-10-10-10-37 6.2.0-1017-aws https://github.com/apache/apisix/pull/17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
nginx:1.19.0-alpine
curl http://127.0.0.1:9090/v1/server_info
404 page not found

**Comment by samsu-lb** [comment]
apisix image: apache/apisix:${APISIX_IMAGE_TAG:-3.7.0-debian}
Linux ip-10-10-10-37 6.2.0-1017-aws #17~22.04.1-Ubuntu SMP Fri Nov 17 21:07:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
nginx:1.19.0-alpine
curl http://127.0.0.1:9090/v1/server_info
404 page not found

**Comment by hanqingwu** [comment]
docker ps 看下 容器状态是否正常

**Comment by samsu-lb** [comment]
![image](https://github.com/apache/apisix/assets/151890784/f807fe27-5180-4e0f-8c7c-09497aad76e0)
shi是正常的，并且能够正常提供服务

**Comment by samsu-lb** [comment]
apisix:
  enable_admin: **false**  这个选贤关闭了，改成true可以了
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

**Comment by sheharyaar** [comment]
Hi @samsu-lb , can you please add your issue in English?

**Comment by hanqingwu** [comment]
@samsu-lb .  OK,  The problem have resolved ,  Please close issue.
