### ISSUE TITLE
bug: Attempt to get JWT token fail

### ISSUE THREAD

**Issue by valpa** [apache/apisix#1079]
### Issue description
Attempt to get JWT token fail when run command
curl -i -X GET http://localhost:9080/apisix/plugin/jwt/sign?key=1212121212
if there is only one consumer

### Environment
* apisix version (cmd: `apisix version`): 1.0
* OS: docker version from https://github.com/apache/incubator-apisix-docker.git

### Minimal test code / Steps to reproduce the issue
Ensure there is no consumer configured
Run following commands:
```

curl -i -X PUT http://localhost:9080/apisix/admin/consumers -d '{"username":"1212121212","plugins":{"jwt-auth":{	"key":"1212121212"}}}'
curl -i -X GET http://localhost:9080/apisix/plugin/jwt/sign?key=1212121212

curl -i -X PUT http://localhost:9080/apisix/admin/consumers -d '
{
    "username": "jack",
    "plugins": {
        "jwt-auth": {
            "key": "user-key",
            "secret": "my-secret-key"
        }
    }
}'
curl -i -X GET http://localhost:9080/apisix/plugin/jwt/sign?key=1212121212
```

### What's the actual result? (including assertion message & call stack if applicable)
The first curl GET command get 500 error
The second curl GET command get 200 OK

### What's the expected result?
The first curl GET command shall get 200 OK with a token

**Comment by membphis** [comment]
which APISIX version you are using? it works fine for commit https://github.com/apache/incubator-apisix/commit/5736a0327220ca1bbbb7fadc9a18cff33dfb7cbe.

![image](https://user-images.githubusercontent.com/6814606/72664866-be661a80-3a3d-11ea-98bf-22fc93ff5036.png)

**Comment by valpa** [comment]
I was using docker version from https://github.com/apache/incubator-apisix-docker.git

Rebuild today so I believe APISIX is the last update in master branch.

Just tested again, still fail

```
jerry@jerry:~/api_gateway/incubator-apisix-docker/example
$ curl -i -X PUT http://localhost:9080/apisix/admin/consumers -d '{"username":"1212121212","plugins":{"jwt-auth":{"key":"1212121212"}}}'
HTTP/1.1 201 Created
Date: Sun, 19 Jan 2020 08:28:28 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"node":{"value":{"username":"1212121212","plugins":{"jwt-auth":{"algorithm":"HS256","key":"1212121212","secret":"5078d51b-dadd-40de-abbe-9704f16dc8cf","exp":86400}}},"createdIndex":305,"key":"\/apisix\/consumers\/1212121212","modifiedIndex":305},"action":"set"}
jerry@jerry:~/api_gateway/incubator-apisix-docker/example
$ curl -i -X GET http://localhost:9080/apisix/plugin/jwt/sign?key=1212121212
HTTP/1.1 500 Internal Server Error
Date: Sun, 19 Jan 2020 08:28:28 GMT
Content-Type: text/html
Content-Length: 174
Connection: close
Server: APISIX web server

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by membphis** [comment]
please provide the related error log.

I cannot reproduce this problem. If you can provide a reproduction environment, please contact me.

**Comment by membphis** [comment]
old issue. @valpa if you still have a problem, please let me know. we can reopen it.
