### ISSUE TITLE
help request:    The RPM package for version 3.2 cannot be downloaded

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#10806]
### Download command 
  `
       yum install -y --downloadonly --downloaddir=./apisix apisix-3.2
  `
### result 
<img width="648" alt="image" src="https://github.com/apache/apisix/assets/10181098/09416d0d-2734-4523-b544-69cc432751c2">

### Refer to the documentation
<img width="1031" alt="image" src="https://github.com/apache/apisix/assets/10181098/e574358a-3dba-4413-ab4c-416cc1f77452">

**Comment by lakshya8066** [comment]
Hi, do you want to download the apisix 3.2.0 version?
If yes, you can explicitly mention `3.2.0` and it will work.

`sudo yum install -y --downloadonly --downloaddir=./apisix apisix-3.2.0`

**Comment by zzqCh** [comment]
> Hi, do you want to download the apisix 3.2.0 version? If yes, you can explicitly mention `3.2.0` and it will work.
> 
> `sudo yum install -y --downloadonly --downloaddir=./apisix apisix-3.2.0`

ok, thanks
