### ISSUE TITLE
feat: Add schema attribute definition for some log plug-ins

### ISSUE THREAD

**Issue by smileby** [apache/apisix#10803]
### Description

The PR submitted before was #10738, dealing with the problem of #9190 .

Some plug-in related attributes need to be improved, such as include_req_body, include_req_body_expr, include_resp_body, include_resp_body_expr

Current status：

The list of plugins with missing attributes is as follows： 

- skywalking-logger
- tcp-logger
- udp-logger
- syslog
- sls-logger
- elasticsearch-logger
- splunk-hec-logging
- google-cloud-logging

expect：

Supplement the above plug-ins. Temporarily skip the following two plug-ins:
- splunk-hec-logging
- google-cloud-logging

> They have a specific format and will not be adjusted for the time being.

**Comment by smileby** [comment]
@shreemaan-abhishek  @pottekkat  Do I need to extend this function?

**Comment by shreemaan-abhishek** [comment]
you can submit a PR if you wish to.

**Comment by smileby** [comment]
I will finish it if I have time, I am currently doing other work.
