### ISSUE TITLE
docs: add Chinese translation for `multi-auth` plugin doc

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10802]
### Current State

Feature added in this PR along with the English doc: https://github.com/apache/apisix/pull/10482

The doc is found here: https://apisix.apache.org/docs/apisix/next/plugins/multi-auth/

### Desired State

Should have Chinese doc as well.

**Comment by smileby** [comment]
@kayx23 i can do it

**Comment by kayx23** [comment]
Thanks ^_^
