### ISSUE TITLE
docs:  key-auth

### ISSUE THREAD

**Issue by trayliang** [apache/apisix#10818]
### Current State

1 、https://apisix.apache.org/zh/docs/apisix/plugins/key-auth/

To fetch the key from a different header than apikey, change the header in the configuration:

{
    "key-auth": {
        "header": "Authorization"
    }
}

### Desired State

     Customize the header specific detailed steps

**Comment by zll600** [comment]
@trayliang The specific meaning of each parameter has been explained in the [document](https://apisix.apache.org/zh/docs/apisix/plugins/key-auth/#%E5%B1%9E%E6%80%A7). Can you refer to the doc to temporarily solve your problem?

refer: 
![image](https://github.com/apache/apisix/assets/71714656/7e5e8431-722d-43ed-a1cc-9a05f5989e67)

**Comment by sheharyaar** [comment]
@trayliang, If you issue is solved, please close this.
