### ISSUE TITLE
Can the limit-req plugin be used for Redis/mysql/kafka?

### ISSUE THREAD

**Issue by find404** [apache/apisix#10821]
### Description

apisix Can only be used for APIs?I want to use Apisix for Redis/mysql/kafka，Is it possible?

**Comment by lakshya8066** [comment]
Hi @find404 did you mean something like this?

https://apisix.apache.org/docs/apisix/next/xrpc/redis/
https://apisix.apache.org/docs/apisix/next/pubsub/kafka/

**Comment by theweakgod** [comment]
Do you want to use redis to store limit req leaky bucket algorithm counts?
