### ISSUE TITLE
bug: `jwe-decrypt` plugin secret requires exactly 32 chars

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10825]
### Current State

The [plugin doc](https://apisix.apache.org/docs/apisix/next/plugins/jwe-decrypt/#encrypt-data-with-jwe) and the [schema in the source code](https://github.com/apache/apisix/blob/master/apisix/plugins/jwe-decrypt.lua#L50) both mention the secret **minimum length** is 32.

However, through testing I found the secret needs to be **exactly 32 chars**, no more no less.

With a 32 char long secret, the encryption works out well:

![image](https://github.com/apache/apisix/assets/39619599/3953dc31-cdee-4f3e-81aa-84cb1698046f)

With a secret longer than 32 char, you end up with 500 error:

![image](https://github.com/apache/apisix/assets/39619599/5127ed1b-d9d9-4128-a1e1-75210814a7f5)

Logs:

```text
2024/01/17 04:35:55 [error] 126#126: *28259 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/jwe-decrypt.lua:131: attempt to index local 'aes_default' (a nil value)
stack traceback:
coroutine 0:
/usr/local/apisix/apisix/plugins/jwe-decrypt.lua: in function 'jwe_encrypt'
/usr/local/apisix/apisix/plugins/jwe-decrypt.lua:231: in function 'handler'
/usr/local/apisix/apisix/api_router.lua:72: in function 'handler'
/usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:723: in function 'dispatch'
/usr/local/apisix/apisix/api_router.lua:111: in function 'match'
/usr/local/apisix/apisix/plugins/public-api.lua:47: in function 'phase_func'
/usr/local/apisix/apisix/plugin.lua:1154: in function 'run_plugin'
/usr/local/apisix/apisix/init.lua:721: in function 'http_access_phase'
access_by_lua(nginx.conf:315):2: in main chunk, client: 172.24.0.1, server: _, request: "GET /apisix/plugin/jwe/encrypt?key=jack-key&payload={"uid":10000,"uname":"test"} HTTP/1.1", host: "127.0.0.1:9080"
172.24.0.1 - - [17/Jan/2024:04:35:55 +0000] 127.0.0.1:9080 "GET /apisix/plugin/jwe/encrypt?key=jack-key&payload={\x22uid\x22:10000,\x22uname\x22:\x22test\x22} HTTP/1.1" 500 249 0.000 "-" "curl/7.64.1" - - - "http://127.0.0.1:9080"
```

### Expected State

* Confirm the requirement for secret length
* Update schema and doc (and maybe test) accordingly
* No 500 internal server error

**Comment by kayx23** [comment]
@fishioon Hi! Are you able to check what's going on with the documented example? It is not working as intended.

The feat PR was contributed by you a while back (https://github.com/apache/apisix/pull/10252) and though I also directly committed to the PR to update the docs a little bit (as asked), I checked my change and saw I didn't change the command.

**Comment by kayx23** [comment]
I have updated the description and this is a bug, not just a doc issue. cc: @Vacant2333 @fishioon

**Comment by lakshya8066** [comment]
@kayx23 I can look into it. Can you assign me this issue?

**Comment by hanqingwu** [comment]
From plugin jwe-decrypt.lua , It  use encode   A256GCM ,   so key must 256bit  aligned

**Comment by Vacant2333** [comment]
> From plugin jwe-decrypt.lua , It use encode A256GCM , so key must 256bit aligned

yeah u r right, i will create a pr to update the docs
