### ISSUE TITLE
help request: verfify jwt barrer token using JWK server

### ISSUE THREAD

**Issue by 223311** [apache/apisix#10831]
### Description

I am looking for a plugin which help me to verify the jwt token using jwk server. so basically we have the jwk server and the incoming request is containing barrer token(Authorization: Barrer <jwt toaken>) . now i am trying to validate the jwt token with jwk server before sending to the upstream server. 

Could you please help me with this.

### Environment

apisix -3.7

**Comment by 223311** [comment]
@shreemaan-abhishek - The JWT token is created by the JKW server. When a service includes the token in the request header, it must undergo validation against the JWK-provided URL to confirm whether the token was indeed generated by the JKW server before forwarding it to the upstream destination.

**Comment by shreemaan-abhishek** [comment]
APISIX doesn't yet support this.

**Comment by shreemaan-abhishek** [comment]
And this seems like a really custom use case, I don't think apisix should support this either. cc: @Revolyssup @sheharyaar.

**Comment by sheharyaar** [comment]
Yeah, @223311,  if you want this feature, please use ext-plugin and create your own plugin.

**Comment by shreemaan-abhishek** [comment]
If you face any difficulties while writing this plugin you may open a new ticket for it. I will close this issue for now.
