### ISSUE TITLE
How does apisix do what it says it does？

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10845]
### Description

We see in the gateway document that apisix has "can protect API from the attack of malicious attack media such as SQL injection, DDOS attack and XSS", may I ask how to prevent SQL injection, DDOS attack and XSS attack, and are there related plug-ins？
![image](https://github.com/apache/apisix/assets/39228009/ea72f1f6-86c6-4683-8637-d21c8a98218c)

### Environment

- APISIX version (run `apisix version`):3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
You can integrate with WAFs such as [Coraza](https://docs.api7.ai/apisix/how-to-guide/security/waf/integrate-with-coraza) and [Chaitin](https://apisix.apache.org/docs/apisix/next/plugins/chaitin-waf). APISIX provides plugin options for such integrations.

See [this example](https://docs.api7.ai/apisix/how-to-guide/security/waf/integrate-with-coraza#verify-1) that fences off a potential XSS attack.

**Comment by lakshya8066** [comment]
You can also use the [rate limiting plugin ](https://docs.api7.ai/apisix/getting-started/rate-limiting#:~:text=For%20example%2C%20you%20can%20configure,excessive%20requests%20from%20web%20crawlers.) to prevent potential DDOS attacks

**Comment by githubxubin** [comment]
> You can also use the [rate limiting plugin ](https://docs.api7.ai/apisix/getting-started/rate-limiting#:~:text=For%20example%2C%20you%20can%20configure,excessive%20requests%20from%20web%20crawlers.) to prevent potential DDOS attacks

What about SQL injection prevention capabilities? Are there related plugins available?

**Comment by zll600** [comment]
> > You can also use the [rate limiting plugin ](https://docs.api7.ai/apisix/getting-started/rate-limiting#:~:text=For%20example%2C%20you%20can%20configure,excessive%20requests%20from%20web%20crawlers.) to prevent potential DDOS attacks
> 
> What about SQL injection prevention capabilities? Are there related plugins available?

maybe you can try coraza. Coraza support the `SQL Injection` prevention capabilities
refer: https://github.com/corazawaf/coraza
> 🔥 Security - Coraza runs the [OWASP Core Rule Set (CRS)](https://coreruleset.org/) v4 to protect your web applications from a wide range of attacks, including the OWASP Top Ten, with a minimum of false alerts. CRS protects from many common attack categories including: SQL Injection (SQLi), Cross Site Scripting (XSS), PHP & Java Code Injection, HTTPoxy, Shellshock, Scripting/Scanner/Bot Detection & Metadata & Error Leakages. Note that older versions of the CRS are not compatible.

**Comment by lakshya8066** [comment]
@githubxubin Does this answer your queries?

**Comment by githubxubin** [comment]
> maybe you can try to integrate [Coraza](https://docs.api7.ai/apisix/how-to-guide/security/waf/integrate-with-coraza). Coraza support the `SQL Injection` prevention capabilities

According to your answer, I can understand that there is no ready-made SQL injection prevention plug-in for apisix at present, so we need to integrate it by ourselves, right？tks

**Comment by githubxubin** [comment]
> @githubxubin Does this answer your queries?

apisix cannot be configured：
 >. schema validate failed: schema not found, path: plugins.coraza-filter
![image](https://github.com/apache/apisix/assets/39228009/3d946f73-b9a0-4f66-ae41-d86269ad6d77)

my route config:
```
{
    "id": "496799691292279501",
    "create_time": 1705645291,
    "update_time": 1705646212,
    "uri": "/test/*",
    "name": "coraza测试",
    "groupId": "1",
    "openId": "",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "plugins": {
        "coraza-filter": {
            "conf": {
                "directives_map": {
                    "default": [
                        "SecDebugLogLevel 9",
                        "SecRuleEngine On",
                        "Include @crs-setup-conf",
                        "Include @owasp_crs/*.conf"
                    ]
                },
                "default_directives": "default"
            }
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "10.210.21.105",
                "port": 1001,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "discovery_args": {
            "group_name": "",
            "namespace_id": ""
        },
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```

**Comment by zll600** [comment]
@githubxubin Could you give us more information about your request and response?

**Comment by zll600** [comment]
> > @lakshya8066 Does this answer your queries?
> 
> ![image](https://private-user-images.githubusercontent.com/39228009/297995820-26044297-8c87-4790-b37c-56e18ee0f164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODQ2NjgsIm5iZiI6MTcwNTg4NDM2OCwicGF0aCI6Ii8zOTIyODAwOS8yOTc5OTU4MjAtMjYwNDQyOTctOGM4Ny00NzkwLWIzN2MtNTZlMThlZTBmMTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YTE4NjU4YmZlNjRkMWYxZjA4OWVjYjhkYTY1NzJhODE3NjQ3MmRiMmZiNDIzYzE2ZDhmYTQ2Njg4YjZiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvV_OiEUmEdxmPDD5h_uw4A_-aspuV6STTt6qO55GUs) Excuse me, how to configure the need to prevent SQL injection? Can you give me an example? This part of the configuration is not in the documentation

you can refer the offical readme. https://github.com/corazawaf/coraza-proxy-wasm/tree/main.
also you can try this:
```shell
"directives_map": {
          "default": [
            "SecDebugLogLevel 9",
            "SecRuleEngine On",
            "Include @crs-setup-conf",
            "Include @owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"
          ]
        },
        "default_directives": "default"
```

**Comment by kayx23** [comment]
> > > @lakshya8066 Does this answer your queries?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/39228009/297995820-26044297-8c87-4790-b37c-56e18ee0f164.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4ODQ2NjgsIm5iZiI6MTcwNTg4NDM2OCwicGF0aCI6Ii8zOTIyODAwOS8yOTc5OTU4MjAtMjYwNDQyOTctOGM4Ny00NzkwLWIzN2MtNTZlMThlZTBmMTY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDAwNDYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5YTE4NjU4YmZlNjRkMWYxZjA4OWVjYjhkYTY1NzJhODE3NjQ3MmRiMmZiNDIzYzE2ZDhmYTQ2Njg4YjZiNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AvV_OiEUmEdxmPDD5h_uw4A_-aspuV6STTt6qO55GUs) Excuse me, how to configure the need to prevent SQL injection? Can you give me an example? This part of the configuration is not in the documentation
> 
> you can refer the offical readme. https://github.com/corazawaf/coraza-proxy-wasm/tree/main. also you can try this:
> 
> ```shell
> "directives_map": {
>      "default": [
>      "SecDebugLogLevel 9",
>      "SecRuleEngine On",
>      "Include @crs-setup-conf",
>      "Include @owasp_crs/REQUEST-942-APPLICATION-ATTACK-SQLI.conf"
>      ]
>   },
> "default_directives": "default"
> ```

To clarify, you are "schema validate failed: schema not found, path: plugins.coraza-filter" from the above?

**Comment by githubxubin** [comment]
> To clarify, you are "schema validate failed: schema not found, path: plugins.coraza-filter" from the above?

Yes, how do we deal with it

**Comment by zll600** [comment]
> To clarify, you are "schema validate failed: schema not found, path: plugins.coraza-filter" from the above?
Sorry, I didn't encounter this problem during my own testing with the configuration I mentioned above.

**Comment by githubxubin** [comment]
> Sorry, I didn't encounter this problem during my own testing with the configuration I mentioned above.

Is my version of apisix not supported? My version of apisix is 3.2/realse?
Does this release support Coraza.？

**Comment by shreemaan-abhishek** [comment]
@githubxubin please follow this documentation as is: https://docs.api7.ai/apisix/how-to-guide/security/waf/integrate-with-coraza to setup coraza integration. If you still get errors, please file another issue. I will close this for now.

**Comment by trungtien** [comment]
curl --location --request PUT 'http://x.x.x.x:9180/apisix/admin/routes/' \
--header 'X-API-KEY: yyyyyyyyyyyyyyyyyyyy' \
--header 'Content-Type: application/json' \
--data-raw '{
  "id": "getting-started-waf",
  "uri": "/anything/*",
   "plugins": {
    "coraza-filter": {
      "conf": {
        "directives_map": {
          "default": [
            "SecDebugLogLevel 9",
            "SecRuleEngine On",
            "SecRule REQUEST_URI \"@beginsWith /anything\" \"id:101,phase:1,t:lowercase,deny\""
          ]
        },
        "default_directives": "default"
      }
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "a.b.c.d:80": 1
    }
  }
}'

error_msg": "failed to check the configuration of plugin coraza-filter err: property \"conf\" validation failed: wrong type: expected string, got table"
apisix version 3.2.2: LTS 
Coraza version: 0.4.0

**Comment by kayx23** [comment]
>  it is expected to be officially supported in version 3.6.0.

https://apisix.apache.org/blog/2023/09/08/APISIX-integrates-with-Coraza/#how-to-use-coraza-in-apisix

**Comment by trungtien** [comment]
> > it is expected to be officially supported in version 3.6.0.
> 
> https://apisix.apache.org/blog/2023/09/08/APISIX-integrates-with-Coraza/#how-to-use-coraza-in-apisix

I know that APISIX 3.6.0 supports Coraza, but upgrading it in a production environment can have a significant impact. Can I submit the 'conf' value as a string?
https://github.com/corazawaf/coraza-proxy-wasm/blob/main/wasmplugin/config_test.go

**Comment by trungtien** [comment]
curl --location --request PUT 'http://x.x.x.x:9180/apisix/admin/routes/' \
--header 'X-API-KEY: yyyyyyyyyyyyyyyyyyyy' \
--header 'Content-Type: application/json' \
--data-raw '{
  "id": "getting-started-waf",
  "uri": "/anything/*",
   "plugins": {
    "coraza-filter": {
      "conf": "{\n                \"directives_map\": {\n                    \"default\": [\n                        \"SecDebugLogLevel 9\",\n                        \"SecRuleEngine On\",\n                        \"Include @crs-setup-conf\",\n                        \"Include @owasp_crs/*.conf\"\n                    ]\n                },\n                \"default_directives\": \"default\"\n            }"
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "a.b.c.d:80": 1
    }
  }
}'

It's working now by converting the 'conf' variable from JSON to a string.
apisix version LTS: 3.2.2
Coraza wasm 0.4.0

error log:
Coraza: Access denied (phase 1). Inbound Anomaly Score Exceeded in phase 1 (Total Score: 16) [file "@owasp_crs/REQUEST-949-BLOCKING-EVALUATION.conf"] [line "11098"] [id "949111"]

@githubxubin  You need to export the schema.json file and then copy it to the APISIX dashboard to register Coraza.
