### ISSUE TITLE
bug: Getting Bad Request `Request Header Or Cookie Too Large` after the definition of route

### ISSUE THREAD

**Issue by dimapaikin** [apache/apisix#10849]
### Current Behavior

I'm running example/docker-compose.yml from https://github.com/apache/apisix-docker repo. Version 3.8.0-debian.
According to the getting started I created the route like following  
`curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'`

To validate the configuration I'm calling following API
`curl "http://127.0.0.1:9080/ip"`

The result is: 
```
<html>

<head>
	<title>400 Request Header Or Cookie Too Large</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<center>Request Header Or Cookie Too Large</center>
	<hr>
	<center>openresty</center>
	<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p>
</body>

</html>
```

### Expected Behavior

Get the response:
```
{
  "origin": "183.94.122.205"
}
```

### Error Logs

```
docker-apisix-apisix-1      | 172.23.0.1 - - [18/Jan/2024:12:25:59 +0000] 127.0.0.1:9080 "GET /ip HTTP/1.1" 400 707 0.010 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 44.197.233.190:80 400 0.010 "http://127.0.0.1:9080"
docker-apisix-apisix-1      | 172.23.0.1 - - [18/Jan/2024:12:25:59 +0000] 127.0.0.1:9080 "GET /ip HTTP/1.1" 400 707 0.050 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 52.206.94.89:80 400 0.050 "http://127.0.0.1:9080"
docker-apisix-apisix-1      | 172.23.0.1 - - [18/Jan/2024:12:25:59 +0000] 127.0.0.1:9080 "GET /ip HTTP/1.1" 400 707 0.108 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 52.206.94.89:80 400 0.108 "http://127.0.0.1:9080"
docker-apisix-apisix-1      | 172.23.0.1 - - [18/Jan/2024:12:25:59 +0000] 127.0.0.1:9080 "GET /ip HTTP/1.1" 400 707 0.127 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" 52.206.94.89:80 400 0.128 "http://127.0.0.1:9080"
```

### Steps to Reproduce

Run example/docker-compose.yml from https://github.com/apache/apisix-docker repo. Version 3.8.0-debian.

```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```

Call
```
curl "http://127.0.0.1:9080/ip"
```

The result will be: 
```
<html>

<head>
	<title>400 Request Header Or Cookie Too Large</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<center>Request Header Or Cookie Too Large</center>
	<hr>
	<center>openresty</center>
	<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p>
</body>

</html>
```

### Environment

- APISIX version (run `apisix version`):  3.8.0-debian
- Operating system (run `uname -a`): windows

**Comment by kayx23** [comment]
Same issue as https://github.com/apache/apisix/issues/10827

* Are you using WSL?
* Are you using VPN?
* Can you use a new and clean linux environment?

**Comment by flea1lt** [comment]
I reproduces this issue on my machine, and it appears that the problem lies in the route's `pass_host` configuration, which is set to `pass`. Change it to `node` resolves the issue.
```bash
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -H 'x-api-key: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "id": "getting-started-ip",
  "uri": "/ip",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    },
    "pass_host": "node"
  }
}'
```
I think [getting-started](https://apisix.apache.org/docs/apisix/getting-started/configure-routes/) need to be updated.

**Comment by dimapaikin** [comment]
Thanks, it solved the problem!

**Comment by kayx23** [comment]
> I reproduces this issue on my machine, and it appears that the problem lies in the route's `pass_host` configuration, which is set to `pass`. Change it to `node` resolves the issue.
> 
> ```shell
> curl -i "http://127.0.0.1:9180/apisix/admin/routes" -H 'x-api-key: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>   "id": "getting-started-ip",
>   "uri": "/ip",
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     },
>     "pass_host": "node"
>   }
> }'
> ```
> 
> I think [getting-started](https://apisix.apache.org/docs/apisix/getting-started/configure-routes/) need to be updated.

I still cannot reproduce either with my cloud VM:

![image](https://github.com/apache/apisix/assets/39619599/8f26b2e2-eaf4-4b49-888c-e89562b33f93)

 or locally on my Macbook:

![image](https://github.com/apache/apisix/assets/39619599/594024a9-4c57-4ed6-b5dd-046b6244dcb2)

therefore this will not lead to an immediate doc update until we understand more of what's going on.

@flea1lt if you can share what your environment was when reproducing this issue, that'd be great.

**Comment by flea1lt** [comment]
Recheck this issue and found that it's the proxy redirection loop leads to 400 errors in my situation.

Details:
1. Started [apisix-docker](https://github.com/apache/apisix-docker).
2. Set the route and request it only once.
3. Proxy redirects requests to apisix, causing hundreds of requests in one second.
4. 400 errors observed due to the redirection loop.

![image](https://github.com/apache/apisix/assets/131451843/9053b93e-e16a-42d8-b987-aca50436a8d1)

The `pass_host` works because the request proxy received has a host that is not 127.0.0.1:9080 but httpbin.org:80, and it proxies it correctly.

So, this is not a problem from apisix, but I do not know if others are facing the same situation causing the problem.
@kayx23

**Comment by kayx23** [comment]
> The pass_host works because the request proxy received has a host that is not 127.0.0.1:9080 but httpbin.org:80, and it proxies it correctly.

Great that the solution is able to help a few users but not sure if I understood this explanation. The former is the proxy address and the later is the upstream address.
