### ISSUE TITLE
help request: When I use proxy_mode: http&stream configuration, only stream port works, http port doesn't work

### ISSUE THREAD

**Issue by zhu327** [apache/apisix#10847]
### Description

confg.yaml

```yaml
apisix:
  proxy_mode: http&stream
  stream_proxy:
    tcp:
      - 9100
  node_listen:
    - ip: "[::]"
      port: 9080
    - ip: 0.0.0.0
      port: 9080
  enable_admin: false
  enable_ipv6: true
```

Expected to support both TCP and HTTP simultaneously, but viewing the port listener, found that only 9100 of stream_proxy is enabled, HTTP 9080 is not enabled

```shell
[root@bk-micro-gateway-844fc7f784-xcj2v conf]# netstat  -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:9100            0.0.0.0:*               LISTEN      64/nginx: master pr
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      -
tcp6       0      0 :::8081                 :::*                    LISTEN      -
```

Port 8081 is listened by a sidecar container

### Environment

- APISIX version (run `apisix version`):

/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
3.2.1

- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):

nginx version: openresty/1.21.4.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.8 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.cLFc1OlJDR/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):

yaml

- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

/usr/local/bin/luarocks 3.8.0
LuaRocks main command-line interface

**Comment by Vacant2333** [comment]
hello can u provide some logs here @zhu327

**Comment by zhu327** [comment]
```
[root@bk-micro-gateway-c5c5d6f85-8fqbq logs]# cat error.log
2024/01/18 10:06:18 [warn] 66#66: *2 stream [lua] plugin.lua:252: load_stream(): new plugins: {"mqtt-proxy":true,"syslog":true,"limit-conn":true,"ip-restriction":true}, context: init_worker_by_lua*
2024/01/18 10:06:18 [warn] 69#69: *3 stream [lua] plugin.lua:252: load_stream(): new plugins: {"mqtt-proxy":true,"syslog":true,"limit-conn":true,"ip-restriction":true}, context: init_worker_by_lua*
2024/01/18 10:06:18 [warn] 67#67: *1 stream [lua] plugin.lua:252: load_stream(): new plugins: {"mqtt-proxy":true,"syslog":true,"limit-conn":true,"ip-restriction":true}, context: init_worker_by_lua*
2024/01/18 10:06:18 [warn] 68#68: *4 stream [lua] plugin.lua:252: load_stream(): new plugins: {"mqtt-proxy":true,"syslog":true,"limit-conn":true,"ip-restriction":true}, context: init_worker_by_lua*
```

stdout does not contain any useful information, haven't found any related logs

@Vacant2333

**Comment by kayx23** [comment]
What happens if you remove this whole block and just use the default (`node_listen: 9080`)?

```
  node_listen:
    - ip: "[::]"
      port: 9080
    - ip: 0.0.0.0
      port: 9080
```

**Comment by zhu327** [comment]
https://apisix.apache.org/docs/apisix/3.2/stream-proxy/#how-to-enable-stream-proxy

3.2.1

```yaml
apisix:
  enable_admin: false
  stream_proxy: # TCP/UDP proxy
    only: false
    tcp: # TCP proxy address list
      - 9100
```
