### ISSUE TITLE
How does apisix integrate coraza-proxy-wasm？

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#10859]
### Description

Currently, I need to use apisix's sql injection and xss capabilities, I tried to integrate coraza-proxy-wasm, but failed, 
here is my operation and configuration！
referer link:https://docs.api7.ai/apisix/how-to-guide/security/waf/integrate-with-coraza 
step 1:
All configurations are configured according to the document
step 2:
I failed to add a route on the dashboard page.
```
{
    "uri": "/test/*",
    "name": "coraza测试",
    "groupId": "1",
    "openId": "",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "plugins": {
        "coraza-filter": {
            "conf": {
                "directives_map": {
                    "default": [
                        "SecDebugLogLevel 9",
                        "SecRuleEngine On",
                        "Include @crs-setup-conf",
                        "Include @owasp_crs/*.conf"
                    ]
                },
                "default_directives": "default"
            }
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "10.210.21.105",
                "port": 1001,
                "weight": 1
            }
        ],
        "retries": 0,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "discovery_args": {
            "group_name": "",
            "namespace_id": ""
        },
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
Save failed！
the error is:
![image](https://github.com/apache/apisix/assets/39228009/ecec07ac-2103-4528-b8b9-c65bb4033241)
Whether it is a version problem:
apisix version: 3.2/release
dashboard version:3.0

### Environment

- APISIX version (run `apisix version`):3.2 apisix
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by githubxubin** [comment]
@shreemaan-abhishek

**Comment by sheharyaar** [comment]
Did you setup the wasm and it's config in the yaml correctly?

**Comment by githubxubin** [comment]
> Did you setup the wasm and it's config in the yaml correctly?

Yes the configuration is correct, here is my config configuration, and wasm in the container

config:
```
wasm:
  plugins:
    - name: coraza-filter
      priority: 7999
      file: /usr/local/bin/coraza-proxy-wasm.wasm
```
Inside the apisix container：
<img width="515" alt="image" src="https://github.com/apache/apisix/assets/39228009/37d8df12-aa37-4c3b-aa86-c4c49e758cc1">

My version 3.2/release does support this feature？tks

**Comment by sheharyaar** [comment]
apisix is running in the same container, right ?

**Comment by kayx23** [comment]
> apisix version: 3.2

Might be the version. I don't recall coraza was available in 3.2. If you can afford to upgrade, try 3.6.

**Comment by githubxubin** [comment]
> > apisix version: 3.2
> 
> Might be the version. I don't recall coraza was available in 3.2. If you can afford to upgrade, try 3.6.

It costs too much to upgrade the version, could you please help confirm it？tks

**Comment by kayx23** [comment]
@githubxubin `>=3.6` confirmed.

**Comment by githubxubin** [comment]
> @githubxubin `>=3.6` confirmed.

okey!
