### ISSUE TITLE
help request: apisix LTS version

### ISSUE THREAD

**Issue by dream110fly** [apache/apisix#10870]
### Description

The new LTS version of apisix is 3.2.2, and release/3.8 was released, Is there any plan to release a new LTS version based on a new released version

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
there is no such plan for now

**Comment by kayx23** [comment]
Still at 3.2 as of today.
