### ISSUE TITLE
feat: As a user, I want the consul plug-in to call the serviceID of the health api for deduplication.

### ISSUE THREAD

**Issue by theweakgod** [apache/apisix#10882]
### Description

According to [member blake of consul](https://github.com/hashicorp/consul/issues/11438#issuecomment-1003459485), the best way to implement consul is to register it on each node, but apisix starts from the api: v1/health/checks/ takes serviceID to get the data of each node, so there will be duplicate data here, for example
``` json
[{"Node":"consul-01","CheckID":"service:192.168.11.2:8001","Name":"Service 'test' check","Status":"passing","Notes": "","Output":"TCP connect 192.168.11.2:8001: Success","ServiceID":"192.168.11.2:8001","ServiceName":"test","ServiceTags":[],"Type": "tcp","Interval":"5s","Timeout":"5s","ExposedPort":0,"Definition":{},"CreateIndex":12014,"ModifyIndex":12015},{"Node" :"consul-03","CheckID":"service:192.168.11.2:8001","Name":"Service 'test' check","Status":"passing","Notes":"","Output ":"TCP connect 192.168.11.2:8001: Success","ServiceID":"192.168.11.2:8001","ServiceName":"test","ServiceTags":[],"Type":"tcp"," Interval":"5s","Timeout":"5s","ExposedPort":0,"Definition":{},"CreateIndex":10366,"ModifyIndex":12020}]
```
If node A is registered but node B is not, then the serviceID obtained by apisix will not be balanced, and the weight of the serviceID will be offset, but the user does not know it.
So, I want to deduplicate serviceID

By the way, I want to add a scheduling based on the minimum IP load. I still use roundrobin, but when polling the upstream, the polling is based on the minimum IP schedule, because we currently encounter a scenario where one machine has multiple service, but at a certain point in time, many requests hit the machine at the same time, causing the CPU to skyrocket. We hope to design an optional plug-in parameter. If this parameter is selected, the IP will be sorted first, and then the port will be sorted.

**Comment by theweakgod** [comment]
I can handle this. What do u think of this design?
@shreemaan-abhishek @monkeyDluffy6017

**Comment by shreemaan-abhishek** [comment]
> then the serviceID obtained by apisix will not be balanced

what do you mean by this?

The consul deployment architecture suggested by the official documentation can still be followed when using with APISIX, isn't it? Then I don't understand why we would need this feature. Unless the user deploys/configures consul inappropriately.

**Comment by theweakgod** [comment]
> > 那么apisix获取到的serviceID将不平衡
> 
> 你这是什么意思？
> 
> 配合 APISIX 使用时，仍然可以遵循官方文档建议的 consul 部署架构，不是吗？然后我不明白为什么我们需要这个功能。除非用户部署/配置consul不当。

Consul will get duplicate serviceIDs. I don’t think it should get duplicate serviceIDs.

> > then the serviceID obtained by apisix will not be balanced
> 
> what do you mean by this?
> 
> The consul deployment architecture suggested by the official documentation can still be followed when using with APISIX, isn't it? Then I don't understand why we would need this feature. Unless the user deploys/configures consul inappropriately.

Consul will get duplicate serviceIDs. I don’t think it should get duplicate serviceIDs.

**Comment by theweakgod** [comment]
> > then the serviceID obtained by apisix will not be balanced
> 
> what do you mean by this?
> 
> The consul deployment architecture suggested by the official documentation can still be followed when using with APISIX, isn't it? Then I don't understand why we would need this feature. Unless the user deploys/configures consul inappropriately.

This problem occurs exactly according to the official configuration. The Service registration data of each node of consul will not be synchronized, which requires the service to be registered on each node. The Service registration data obtained by apisix from consul is that of each node of consul. The sum of Service registration data. There will be duplicate data.
Duplicate ServiceIDs may exist in a List in the following situations. For example, I have three services ABC and three Nodes: Nodes1, Nodes2, Nodes3
I have registered services on all three Nodes, but in the apisix service list it may be
[A, B, C, C, B, A, A, B, C], he may not be a good roundrobin because he has CC and AA

**Comment by shreemaan-abhishek** [comment]
Okay I understand now. You may work on this if you want to.
