### ISSUE TITLE
help request: How to support service discovery of multiple Nacos clusters at the same time

### ISSUE THREAD

**Issue by fmjghyfwq** [apache/apisix#10890]
### Description

How to support service discovery of multiple Nacos clusters at the same time，version 2.15

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): k8s 1.23
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by smileby** [comment]
Currently not supported

**Comment by kayx23** [comment]
duplicated: https://github.com/apache/apisix/issues/10799
