### ISSUE TITLE
docs: OpenAPI definition for Apisix Admin and Control APIs

### ISSUE THREAD

**Issue by karelhusa** [apache/apisix#10892]
### Current State

The Apisix documentation includes pretty good description of its APIs:

- Admin API: https://apisix.apache.org/docs/apisix/admin-api/
- Control API: https://apisix.apache.org/docs/apisix/control-api/

Though, there is **no link to the OpenAPI definition for these APIs**. I would appreciate having a link to JSON/YAML document containing OpenAPI definition on these pages. I could clearly see the API operations, their parameters, request/response data and also import it, e.g., to Postman.

### Desired State

I suggest to:
- **Expose OpenAPI definition** for Admin and Control API
- **Add the link to the API definition** to the documentation pages:
  - Admin API: https://apisix.apache.org/docs/apisix/admin-api/
  - Control API: https://apisix.apache.org/docs/apisix/control-api/

This will help working with both APIs and reduce risks of errors, knowing precise API definitions.

**Comment by shreemaan-abhishek** [comment]
https://docs.api7.ai/apisix/reference/control-api
https://docs.api7.ai/apisix/reference/admin-api

The website says admin api is in beta so there might be some discrepancies.

**Comment by karelhusa** [comment]
Thanks @shreemaan-abhishek ! Is it possible to place the API definitions or the links to Apisix docs?
