### ISSUE TITLE
bug: apisix 3.8.0-debian docker image doesn't support arm64 

### ISSUE THREAD

**Issue by graphenn** [apache/apisix#10906]
### Current Behavior

apisix 3.8.0-debian docker image doesn't support arm64, but 3.7.0-debian and before support

### Steps to Reproduce

NA

### Environment

NA

**Comment by kayx23** [comment]
The support was purposely removed, afaik. For the specifics, would have to wait for others to pitch in.

**Comment by graphenn** [comment]
okay.
