### ISSUE TITLE
help request: set Authorization header from cookie

### ISSUE THREAD

**Issue by poostwoud** [apache/apisix#10936]
### Description

Hi,

Is there a way to read a token from a cookie and set this as the Authorization header using the default plugins?

We are using the openid-connect plugin to verify access tokens. This works using the Authorization header. However there doesn't seems to be an option for reading from a cookie.

We've also looked at the proxy-rewrite plugin. This allows to set, add and remove headers. But there doesn't seem to be a way to read from a cookie.

Any thoughts?

Cheers!

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): Linux apisix-gateway-86d6dffb7d-sh9jv 6.1.0-17-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: ?
- Plugin runner version, for issues related to plugin runners: ?
- LuaRocks version, for installation issues (run `luarocks --version`): ?

**Comment by shreemaan-abhishek** [comment]
you can access cookies like so: `ngx.var.cookie_NAME` https://github.com/openresty/lua-nginx-module/issues/19#issuecomment-825373 

To set a cookie value to a header you can use the serverless plugin to set headers like so:
```shell
curl "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT \
  -H "X-API-KEY: ${ADMIN_API_KEY}" \
  -d '{
    "plugins": {
      "serverless-post-function": {
        "functions": [
          "return function (conf, ctx) local core = require(\"apisix.core\"); core.request.set_header(ctx, \"abc\", \"def\"); end"
        ]
      }
    },
    "upstream": {
      "nodes": {
        "httpbin.org:80": 1
      },
      "type": "roundrobin"
    },
    "uri": "/*"
  }'
```
