### ISSUE TITLE
help request: Need Help in exposing apisix gateway from my EKS Cluster

### ISSUE THREAD

**Issue by gundeep1995** [apache/apisix#10933]
### Description

Hello team. I have my EKS cluster running in a private subnet, and I've built up Apisix, ingres-controller, and dashboard. I generated certain routes, and they may be resolved and worked locally with the command below. 
 
**kubectl -n apisix exec -it $(kubectl get pods -n apisix -l app.kubernetes.io/name=apisix -o name) -- curl "http://127.0.0.1:9080/get" -H 'Host: httpbin.org'**

But how do I make it public for my users? I tried using the admin-gateway service Loadbalancer, but it isn't functioning. Could someone kindly assist? 

### Environment

- APISIX version (run `apisix version`):- 2.15.0
- Operating system (run `uname -a`): EKS Cluster
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): -3.4.0
- version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
this seems more like an issue with AWS instead of APISIX.
