### ISSUE TITLE
bug: Cannot serialise table: excessively sparse array force: true

### ISSUE THREAD

**Issue by lakewatcher** [apache/apisix#10964]
### Current Behavior

一直在报  Cannot serialise table: excessively sparse array force: true

2024/02/25 11:12:41 [warn] 9506#9506: *571233999 [lua] json.lua:94: failed to encode: Cannot serialise table: excessively sparse array force: true, client: 10.202.16.131, server: _, request: "POST  

上下信息如下：
![image](https://github.com/apache/apisix/assets/27823963/f5c7aaaf-095c-44b5-a382-a417e7370621)

### Error Logs

2024/02/25 11:12:41 [warn] 9506#9506: *571233999 [lua] json.lua:94: failed to encode: Cannot serialise table: excessively sparse array force: true

### Steps to Reproduce

1.配置路由，健康检查
2.运行

### Environment

- APISIX version (run `apisix version`): 2.15.3
- Operating system (run `uname -a`): Linux TLVM202017071 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"boot_time":1704193495,"etcd_version":"3.5.0","id":"0880b644-4f19-49e1-af77-1be7d3d7e196","version":"2.15.3","hostname":"TLVM202017071"}
- APISIX Dashboard version, if relevant: 2.15
- Plugin runner version, for issues related to plugin runners: OIDC 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by theweakgod** [comment]
> Or you can comment out this line of code. https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L196

Is this work for u?

**Comment by lakewatcher** [comment]
> > Or you can comment out this line of code. https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L196
> 
> Is this work for u?

-- core.log.info("ctx: ", core.json.delay_encode(ctx, true))

Thank you for your reply. It's great
