### ISSUE TITLE
help request: where can we find resty.apisix.{x} module

### ISSUE THREAD

**Issue by grootTwig** [apache/apisix#10991]
### Description

I'm studying the code of apisix, and i've noticed some required modules like resty.apisix.request, but i can't find these modules in apisix dir or using package.searchpath() by lua. Is there any suggestion for me?

### Environment

- APISIX version (run `apisix version`): v2.15
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by theweakgod** [comment]
[resty.apisix.request](https://github.com/api7/apisix-nginx-module/blob/main/lib/resty/apisix/request.lua)
This will help u. u will find some other x in this page.
:)

**Comment by grootTwig** [comment]
> [resty.apisix.request](https://github.com/api7/apisix-nginx-module/blob/main/lib/resty/apisix/request.lua) This will help u. u will find some other x in this page. :)

thanks

**Comment by theweakgod** [comment]
Have u solved ur problem?

**Comment by theweakgod** [comment]
So can we close this issue or is there anything else?
