### ISSUE TITLE
docs: change the `workflow` plugin category from General to Traffic Management 

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#10998]
### Current State

The plugin https://apisix.apache.org/docs/apisix/plugins/workflow is currently under `General`.

### Desired State

Seems more appropriate under `Traffic (Management)`. Opening this issue to discuss what everyone thinks.

**Comment by sunheyi6** [comment]
I think it's ok too

**Comment by smileby** [comment]
LGTM
