### ISSUE TITLE
docs: proxy-rewrite plugin http://iresty.com/test/home.html 404

### ISSUE THREAD

**Issue by sunheyi6** [apache/apisix#11004]
### Current State

in [doc](https://apisix.apache.org/zh/docs/apisix/plugins/proxy-rewrite/) ,http://iresty.com/test/home.html 404

### Desired State

The url should be accessible

**Comment by yzeng25** [comment]
@sunheyi6  Could you take a screenshot of the exact location of this 404 link?

**Comment by sunheyi6** [comment]
> @sunheyi6 Could you take a screenshot of the exact location of this 404 link?
https://github.com/apache/apisix/blob/f932fbe4a5a57974e5c2632ded0554acc1070089/docs/zh/latest/plugins/proxy-rewrite.md?plain=1#L55-L91

**Comment by sunheyi6** [comment]
>  @sunheyi6 Could you take a screenshot of the exact location of this 404 link?

https://github.com/apache/apisix/blob/f932fbe4a5a57974e5c2632ded0554acc1070089/docs/zh/latest/plugins/proxy-rewrite.md?plain=1#L55-L91

**Comment by yzeng25** [comment]
Not sure what is going on here, PTAL when you are available @kayx23 @shreemaan-abhishek , thank you.

**Comment by kayx23** [comment]
Most docs on apache/apisix have been using dummy upstream and host, or upstreams that are deployed in CI. The affected scope is pretty much every single plugin docs.

You could replace upstream/host to an actual host in your environment, open a PR to fix this, or check the new docs site where examples work end to end https://docs.api7.ai/hub/proxy-rewrite
