### ISSUE TITLE
help request: Are all these plugins enabled by default?

### ISSUE THREAD

**Issue by sunheyi6** [apache/apisix#11011]
### Description

https://github.com/apache/apisix/blob/b83a20b6ee9fe72cd8489bdbca04b963a8a796b4/conf/config-default.yaml#L439-L532

### Environment

- APISIX version (run `apisix version`): no
- Operating system (run `uname -a`):no
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): no
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): no
- APISIX Dashboard version, if relevant: no
- Plugin runner version, for issues related to plugin runners: no
- LuaRocks version, for installation issues (run `luarocks --version`): no

**Comment by kayx23** [comment]
Yes, except for the ones commented out.

Why? Any issue using them?

**Comment by sunheyi6** [comment]
It's just some confusion in my studies, thank you for your answers.
