### ISSUE TITLE
help request: 503 Service is temporarily unavailable

### ISSUE THREAD

**Issue by hubcomsix** [apache/apisix#11028]
### Current Behavior

Error 503 is reported in apisix: Service is temporarily unavailable

### Error Logs

Error 503 is reported in apisix: Service is temporarily unavailable

### Steps to Reproduce

no

### Environment

no

**Comment by shreemaan-abhishek** [comment]
please provide the steps to repro

**Comment by motongxue** [comment]
👋 Thank you for reporting this issue! To better assist you, we need more information. Please provide the following details:

APISIX Version: What version of APISIX are you using?
Error Logs: Please provide the error logs of APISIX (usually located at /usr/local/apisix/logs/error.log).
Configuration Details: Can you share the configuration details of the route, service, upstream, or plugin that is causing the 503 error?
Request Information: How did you make the request? What tool or command did you use? What are the request headers and body?
Environment Information: How is your APISIX deployed? Is it locally, Docker, Kubernetes, etc.? What operating system are you using?
Steps to Reproduce: Please describe the specific steps that trigger this error.
Providing this information will help us diagnose the problem and find a solution faster. Thank you! 🙏

**Comment by shreemaan-abhishek** [comment]
closed due to lack of reponse.
