### ISSUE TITLE
help request:  How to extend the label of Prometheus? I would like to add some custom metrics 

### ISSUE THREAD

**Issue by DokiDoki1103** [apache/apisix#11038]
### Description

 How to extend the label of Prometheus? I would like to add some custom metrics 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
https://docs.api7.ai/hub/prometheus#add-extra-labels-for-metrics

**Comment by shreemaan-abhishek** [comment]
Please reopen if you have more questions.
