### ISSUE TITLE
help request: Trouble resetting etcd environment after route updates and plugin usage in APISIX

### ISSUE THREAD

**Issue by stevenL-1047** [apache/apisix#11030]
### Description

I've encountered an issue while testing APISIX, involving adding and deleting routes and using various plugins.  I cannot remember the exact changes made to routes and plugins. As a result, I use APISIX abnormally.

I would like to know:
1. How can I reset my etcd environment to a default state without losing essential APISIX configurations?
2. Are there any specific APISIX settings or data that I should back up before resetting the etcd environment?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by motongxue** [comment]
👋 Hi there,

Please don't worry! If you're certain that the data in your ETCD instance is not needed, or if ETCD does not contain any configuration information outside of apisix, you can back up data and safely delete all the information in ETCD.

If you wish to only reset the information in ETCD, you can do the following:

First, stop the APISIX instance from running.
Then, execute the command `etcdctl del "/apisix" --prefix` in your etcd to remove the information related to APISIX.
Please don't worry, when you restart APISIX, it will automatically generate the necessary configurations in ETCD.

Remember, before proceeding with this operation, make sure that you have backed up any essential data that you might need later.

Hope this helps!

**Comment by stevenL-1047** [comment]
Thx! It helps me a lot!
