### ISSUE TITLE
xxx upstream prematurely closed connection while reading response header from upstream, client: x.x.x.x

### ISSUE THREAD

**Issue by smallemployees** [apache/apisix#11039]
### Description

xxx upstream prematurely closed connection while reading response header from upstream, client: x.x.x.x

**Comment by motongxue** [comment]
Hi, I need more information address your issue:
1. What is the configuration information you have set, including what is the upstream address?
2. Can you provide the error log of APISIX? It is usually located at `/usr/local/apisix/logs/error.log` (this may vary depending on your installation path). This will help us identify the cause of the problem.
3. Does your upstream service have any error logs? Is your upstream service allowing connections?

**Comment by shreemaan-abhishek** [comment]
Closed due to lack of response.
