### ISSUE TITLE
bug: Disable All Prometheus-related Features When Prometheus Plugin is Turned Off

### ISSUE THREAD

**Issue by motongxue** [apache/apisix#11046]
### Current Behavior

The Prometheus plugin is a crucial component for observability within Apache APISIX. However, I've encountered an issue where, even after the Prometheus plugin is disabled, all features related to Prometheus are not entirely shut down. This behavior could lead to unexpected performance impacts and data leakage.

Upon disabling the Prometheus plugin, certain Prometheus-related functionalities continue to operate, suggesting that not all components associated with the plugin are fully turned off.

### Expected Behavior

When the Prometheus plugin is disabled, all functionalities and metrics associated with Prometheus should be completely deactivated to ensure no unnecessary overhead or data exposure.

### Steps to Reproduce

1. Enable the Prometheus plugin in Apache APISIX.
2. Generate some traffic and observe Prometheus metrics being collected.
3. Disable the Prometheus plugin.
4. Observe that metrics or features associated with Prometheus are still active or being collected.

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): Linux 4f398f8410bc 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.25.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
To be fixed by #11047. Thanks for your report.
