### ISSUE TITLE
help request: the origin `meta_format` of kafka-logger can not support `include_resp_body`

### ISSUE THREAD

**Issue by zll600** [apache/apisix#11054]
### Description

The origin `meta_format` of kafka-logger just collect original HTTP request which do not support `include_resp_body`. I'd like to know if this is a known limitation or a bug.

from the doc of kafka-logger, it only says ` Setting to default collects the information in JSON format and origin collects the information with the original HTTP request. `
https://apisix.apache.org/docs/apisix/plugins/kafka-logger/#meta_format-example

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@zll600 I dont think its a bug. origin here is intended to only have "original request" whereas json contains the full_log with everything. include_resp_body populates ctx.resp_body which is intentionally being used in full_log which is inside json. Though the response can be added to the response with `meta_format` `origin` as well as a feature but I am not sure if that is a required feature. 
// @monkeyDluffy6017

**Comment by shreemaan-abhishek** [comment]
> Though the response can be added to the response with meta_format origin as well as a feature but I am not sure if that is a required feature.

If the user really needs the request body, they can use `meta_format = json`.

**Comment by shreemaan-abhishek** [comment]
I will close this issue for now, if we get more requests/attention for this request we may re open it later. 👍🏼
