### ISSUE TITLE
bug: get error when set proxy_mode to http&stream

### ISSUE THREAD

**Issue by TimXu0713** [apache/apisix#11056]
### Current Behavior

I install apisix 3.8.0 with helm command 
```shell
helm upgrade apisix apisix/apisix -n apisix --set "timezone=\"Asia/Shanghai\"" --set "service.stream.enabled=true" --set "apisix.enableIPv6=false" --set "apisix.prometheus.enabled=true" --set "apisix.admin.credentials.admin=xxxxxxx" --set "apisix.admin.credentials.admin=xxxxxx" --set "apisix.admin.allow.ipList[0]=0.0.0.0/24"
``` 
the apisix pod get error "/usr/local/openresty//luajit/bin/luajit: [string "context=... or {}..."]:428: attempt to index global 'stream_proxy' (a nil value)"

### Expected Behavior

I want use apisix with k8s,and want use "Stream Proxy" function

### Error Logs

2024-03-18T16:53:07.279841675+08:00 /usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init

2024-03-18T16:53:07.370291766+08:00 /usr/local/openresty//luajit/bin/luajit: [string "context=... or {}..."]:428: attempt to index global 'stream_proxy' (a nil value)

2024-03-18T16:53:07.370332058+08:00 stack traceback:

2024-03-18T16:53:07.370340416+08:00 	[string "context=... or {}..."]:428: in function 'conf_render'

2024-03-18T16:53:07.370346926+08:00 	/usr/local/apisix/apisix/cli/ops.lua:746: in function </usr/local/apisix/apisix/cli/ops.lua:156>

2024-03-18T16:53:07.370352541+08:00 	/usr/local/apisix/apisix/cli/ops.lua:996: in function 'execute'

2024-03-18T16:53:07.370358209+08:00 	./apisix/cli/apisix.lua:40: in main chunk

2024-03-18T16:53:07.370363818+08:00 	[C]: at 0x563be39f23d0

### Steps to Reproduce

1、helm install apisix apisix/apisix --set gateway.type=NodePort --namespace apisix
2、helm upgrade apisix apisix/apisix -n apisix --set "timezone=\"Asia/Shanghai\"" --set "service.stream.enabled=true" --set "apisix.enableIPv6=false" --set "apisix.prometheus.enabled=true" --set "apisix.admin.credentials.admin=xxxxxxx" --set "apisix.admin.credentials.admin=xxxxxx" --set "apisix.admin.allow.ipList[0]=0.0.0.0/24"
3、get error in apisix pod

### Environment

- APISIX version (run `apisix version`):3.8.0
- Operating system (run `uname -a`): helm install 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
can you try to check apisix config.yaml  ?

**Comment by zieen** [comment]
any progress ? @TimXu0713

**Comment by hanqingwu** [comment]
yes,I can reproduce . 
when upgrade apisix by  --set "service.stream.enabled=true" , then apisix config  "proxy_mode: http&stream"
but stream_proxy not config yet , so you can try to config stream_proxy in configmap  apisix  like this.
```
  proxy_mode: http&stream
  stream_proxy:                 # TCP/UDP L4 proxy
      only: true                  # Enable L4 proxy only without L7 proxy.
      tcp:
        - addr: 9100              # Set the TCP proxy listening ports.
          tls: true
        - addr: "127.0.0.1:9101"

```

**Comment by hanqingwu** [comment]
https://github.com/apache/apisix-helm-chart/tree/master/charts/apisix
![image](https://github.com/apache/apisix/assets/7521141/3e36bf59-910b-4339-ad50-c88756dabd5d)

**Comment by TimXu0713** [comment]
> yes,I can reproduce . when upgrade apisix by --set "service.stream.enabled=true" , then apisix config "proxy_mode: http&stream" but stream_proxy not config yet , so you can try to config stream_proxy in configmap apisix like this.
> 
> ```
>   proxy_mode: http&stream
>   stream_proxy:                 # TCP/UDP L4 proxy
>       only: true                  # Enable L4 proxy only without L7 proxy.
>       tcp:
>         - addr: 9100              # Set the TCP proxy listening ports.
>           tls: true
>         - addr: "127.0.0.1:9101"
> ```

thanks,i manually edit the config file as you said,the pod runs successfully.
