### ISSUE TITLE
help request: 504 Timeout for requests

### ISSUE THREAD

**Issue by dgpratikpatil** [apache/apisix#11065]
### Description

I have an upstream service with the following timeout values:
Connect Timeout: 180s
Send Timeout: 180s
Read Timeout: 180s
Idle Timeout: 180s

My request still gets a 504 at 60s.

I have not altered any default nginx configs and they are still at 60s as picked from the [default config file](https://github.com/apache/apisix/blob/master/conf/config-default.yaml).

Is my timeout occurring due to default nginx configs at 60s?

### Environment

- APISIX version : docker image version 3.8.0
- Operating system : ubuntu linux
- OpenResty / Nginx version: bundled with the docker image
- etcd version: 3.5.6
- APISIX Dashboard version: docker image version 3.0.0 alpine
- Plugin runner version: Not aware
- LuaRocks version, for installation issues: 3.5

**Comment by shreemaan-abhishek** [comment]
please share the steps to reproduce this issue.

**Comment by YdayangY** [comment]
@dgpratikpatil hi, do u resolved this issue? I have same problem.

**Comment by Baoyuantop** [comment]
> please share the steps to reproduce this issue.
> 
> > Is my timeout occurring due to default nginx configs at 60s?
> 
> It is difficult to answer this question simply from this observation.

Hi @YdayangY, please provide that data.

**Comment by dgpratikpatil** [comment]
@YdayangY Yes I had resolved this issue.

I don't remember the exact fix I had put out, I'll update here when I am able to recollect it.

**Comment by YdayangY** [comment]
> > please share the steps to reproduce this issue.
> > > Is my timeout occurring due to default nginx configs at 60s?
> > 
> > 
> > It is difficult to answer this question simply from this observation.
> 
> Hi [@YdayangY](https://github.com/YdayangY), please provide that data.

Okay, here's my data. But I think the problem is with Nginx, and I don't have permission to change the Nginx config

`{
  "timeout": {
    "connect": 6,
    "send": 500,
    "read": 500
  },
  "type": "roundrobin",
  "scheme": "http",
  "discovery_type": "nacos",
  "discovery_args": {
    "group_name": "dev",
    "namespace_id": "xxx"
  },
  "pass_host": "xxx",
  "name": "xxx",
  "service_name": "xxx",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 50
  }
}`

**Comment by Baoyuantop** [comment]
Hi @YdayangY, the connection timeout is set to 6 seconds.

**Comment by YdayangY** [comment]
> [@YdayangY](https://github.com/YdayangY) Yes I had resolved this issue.
> 
> I don't remember the exact fix I had put out, I'll update here when I am able to recollect it.



> Hi [@YdayangY](https://github.com/YdayangY), the connection timeout is set to 6 seconds.

Yeah, but can a connection timeout affect sending or reading data? I'm sure the connection only takes less than 6 seconds.

**Comment by Baoyuantop** [comment]
Are there any error logs in APISIX indicating a timeout error? Does it work if the timeout settings are changed to the default configuration? If there are steps that can be stably reproduced, it will be helpful for troubleshooting.

**Comment by YdayangY** [comment]
I changed the timeout setting from 6 seconds to 600, but now the timeout is only 60 seconds.

**Comment by Baoyuantop** [comment]
How did you change it? Please provide the configuration file.

**Comment by YdayangY** [comment]
> How did you change it? Please provide the configuration file.

Just like I said before, it's this one.

`{ "timeout": { "connect": 6, "send": 500, "read": 500 }, "type": "roundrobin", "scheme": "http", "discovery_type": "nacos", "discovery_args": { "group_name": "dev", "namespace_id": "xxx" }, "pass_host": "xxx", "name": "xxx", "service_name": "xxx", "keepalive_pool": { "idle_timeout": 60, "requests": 1000, "size": 50 } }`
