### ISSUE TITLE
docs: add docs for `http-dubbo` plugin

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#11067]
### Current State

Looks like it was decided in the feat PR to split out the doc task: https://github.com/apache/apisix/pull/10703#issuecomment-1910464832

That was two months ago and there doesn't seem to be any doc as of now.

### Desired State

Should have some docs.

**Comment by sunheyi6** [comment]
Is this plugin need to test using [tengine](https://github.com/alibaba/tengine/tree/master/modules/mod_dubbo#quick-start)? If so, there are some problems with the installation of tenginte. I have tried several methods, but none of them can be installed. I am unable to test what the final result is.

**Comment by kayx23** [comment]
I have no idea, but it's good to share here what you have tried/worked/not worked, so that other people picking this task up can reference.

**Comment by kayx23** [comment]
Hi @ShenFeng312 are you available some time to add some doc for http-dubbo plugin?

**Comment by ShenFeng312** [comment]
@kayx23 Sorry for the delay. I'll add the documentation as soon as possible.

**Comment by ShenFeng312** [comment]
> Is this plugin need to test using [tengine](https://github.com/alibaba/tengine/tree/master/modules/mod_dubbo#quick-start)? If so, there are some problems with the installation of tenginte. I have tried several methods, but none of them can be installed. I am unable to test what the final result is.


This plugin does not require Tengine.
