### ISSUE TITLE
bug(ci): ci failing due to incomplete docker image backup

### ISSUE THREAD

**Issue by shreemaan-abhishek** [apache/apisix#11068]
## Problem

The CI is failing because the docker image cache is faulty (the size is too small to be complete): 
![image](https://github.com/apache/apisix/assets/61597896/07297961-c2a5-4bfb-a0db-a04085dfdd31)

https://github.com/apache/apisix/actions/runs/8356719685/job/22875292483?pr=11060#step:11:14

I suspect this is because on one of the previous CI runs, the `cache write` process was interrupted due to excess disk usage. Here is one [example](https://github.com/apache/apisix/actions/runs/8354526962/job/22876155716#step:20:163):
![image](https://github.com/apache/apisix/assets/61597896/952537c6-85bf-4830-8708-a0d117e0109e)

## Solution

- leverage the script that [frees disk space](https://github.com/apache/apisix/blob/master/ci/free_disk_space.sh) to free some more space by removing unnecessary packages.
- write another script (run before saving docker images) that frees disk space by removing some more packages.
  - since we save docker images after setting up the CI environment and running tests, this script can be more fierce on removing big files/packages as it is safer to remove them now
- ensure a mechanism that would abort the `cache write` process if it encounters any error so that cache is not incomplete.

![image](https://github.com/apache/apisix/assets/61597896/5fc64423-f2d9-468e-bc53-ed07ceec0476)

**Comment by zll600** [comment]
I have encountered this problem. 
1.You have to delete invalid cache (usually a few hundred kbs)
2. Rerun the failed CI.

To completely fix this problem, you must ensure that the runner has enough disk space. I've tried freeing more disks by  https://github.com/jlumbroso/free-disk-space
