### ISSUE TITLE
help request: when occurs 414, why apisix not record error log

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#11064]
### Description

hello:
 when I use apisix to proxy request, a request has a long url, which size exceed 8k, which got a 414 code.
 I know why it returns 414, because as the following say. this scenario is as expected
![img_v3_0295_b9caf58c-cf82-42e6-a811-aa659b2303bg](https://github.com/apache/apisix/assets/48037235/fb79da65-1b76-4763-a501-72599d1b066d)

but I want to know why 414 occurs, apisix not record error log

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> but I want to know why 414 occurs, apisix not record error log

does nginx record error log when 414 occurs?

**Comment by jujiale** [comment]
> > but I want to know why 414 occurs, apisix not record error log
> 
> does nginx record error log when 414 occurs?

I test in openresty, openresty also don't record error log，I want to know what kind of scenario  ,  when client request get some abnormal httpcode，such as 414，that openresty/apisix don't record error log

**Comment by jujiale** [comment]
#https://github.com/openresty/openresty/issues/964 resolved
