### ISSUE TITLE
ip_restriction plugin is not whitelisting the individual ips

### ISSUE THREAD

**Issue by NellyNakhero** [apache/apisix#11088]
### Description

@kayx23 

for ip-restriction the expected behavior is when i whitelist my device ip, i should be able to have access. However at the moment, when i whitelist a devices network ip, they still dont have access? Any guidance?

This is an sample image of how i am getting my IP
![image](https://github.com/apache/apisix/assets/79999370/92cb5cbd-17e0-48ca-8c06-ea298eb3f0d8)

And this is a sample on how i am whitelisting
<img width="702" alt="Screenshot 2024-03-25 at 12 20 10" src="https://github.com/apache/apisix/assets/79999370/c09cb4c4-570c-4ecf-8dd2-e3e130c159d9">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
How and where are you deploying APISIX?

Try with your external IP?

**Comment by NellyNakhero** [comment]
The APISIX is deployed in a k8s cluster. Will that in essence affect the IP? @kayx23

**Comment by kayx23** [comment]
Try a logging plugin on APISIX and log the request IP?

**Comment by NellyNakhero** [comment]
@kayx23 When logging, the IP i am able to fetch is the cluster ip, which when whitelisted it removes the restrictions for everyone using my APIs, Is there a way that i can use device ip instead of cluster ip or any alternative to achieve such a behaviour?

**Comment by shreemaan-abhishek** [comment]
@NellyNakhero you might have to use the `real-ip` plugin to make your real client ip visible to APISIX. It seems, APISIX is treating some other entity (I am not much familiar with k8s deployments) between you and APISIX.

https://docs.api7.ai/hub/real-ip

**Comment by NellyNakhero** [comment]
Thank you so much for responding @shreemaan-abhishek. I have checked out `real-ip` documentation and i have one more question. It seems like with `real-ip` plugin when someone makes an API call to my APIS they to attach their users device real IP as a header for APISIX to either whitelist or blacklist a user. Is this deduction on mine accurate?

**Comment by shreemaan-abhishek** [comment]
> It seems like with real-ip plugin when someone makes an API call to my APIS they to attach their users device real IP as a header for APISIX to either whitelist or blacklist a user. Is this deduction on mine accurate?

I didn't get you.

**Comment by NellyNakhero** [comment]
Okay so

my goal: Restrict only users who i have whitelisted their ips to access my apis

The `real-ip` plugin, expects that the any API requests that the API user sends has to attach their IP in the headers. Attached is a screenshot that illustrates the same.

The Question: Does this mean that once i implement this, i have to ask all users using my API to be attaching their IPs as headers?

<img width="1142" alt="Screenshot 2024-03-30 at 19 16 41" src="https://github.com/apache/apisix/assets/79999370/1e6da013-e984-485d-bfcd-dbcd5cdf202e">

**Comment by shreemaan-abhishek** [comment]
@NellyNakhero the `x-forwarded-for` header is automatically added: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For.

However, if you choose to source the IP from some other header, you will have to make sure that header is passed by all clients. If the header is not passed, this plugin will yield no effect/change.

**Comment by shreemaan-abhishek** [comment]
Please close this issue if your query has been resolved.

**Comment by NellyNakhero** [comment]
Ideally most users wont add headers especially if they know they are not going to be allowed to access APIs. Maybe if possible the team can add this to feature requests. Although thanks for the guide! I'll close this.
