### ISSUE TITLE
bug: `content-type` request header has been rewritten

### ISSUE THREAD

**Issue by baicaiclouds** [apache/apisix#11085]
### Current Behavior

When customizing the API plugin with Java, the Content type response header is rewritten, and the proxy response header is application/JSON. The value of the context type returned through the custom plugin becomes text/plain; Charset=utf-8, how to solve this problem?

### Steps to Reproduce

1、Customize Java plugins
2、run
3、watch response
![image](https://github.com/apache/apisix/assets/48907451/b11a2940-d768-4629-9c43-234b80493bc9)
![Uploading image.png…]()

### Environment

- APISIX version 3.1.0

**Comment by SilentEntity** [comment]
Need more info on apisix configs, upstream and route. And if any global rules(if present).

**Comment by shreemaan-abhishek** [comment]
I agree with @SilentEntity, it's very likely that something is wrong in your code. You may want to give a try with a bare minimum java plugin and see if the error exists there.

Also, one of your screenshots didn't get uploaded correctly.
![image](https://github.com/apache/apisix/assets/61597896/270a743a-e6df-43e3-87eb-05c782d2e601)

**Comment by zhl11b** [comment]
I got same bug，is it repaired？

**Comment by baicaiclouds** [comment]
Set different routes according to the different content types of the API, and then rewrite the response header content type through the response plugin of Apisix
















At 2024-10-16 17:57:52, "zhenghongli" ***@***.***> wrote:

I got same bug，is it repaired？
