### ISSUE TITLE
Http check route to return default response

### ISSUE THREAD

**Issue by Hectorsong** [apache/apisix#11093]
### Description

My requests are forwarded from the hardware load balancer to APISIX, and I hope to add an http-check request path to monitor whether the status of APISIX is normal, http-check request path. The http-check request path return http status 200 and default response body "Http check ok". How can I configure it in APISIX Dashboard?

**Comment by bwangll** [comment]
moking plugin simulate it.

**Comment by Hectorsong** [comment]
Appreciate it.
