### ISSUE TITLE
docs: Is it enable here rather than disable about admin_key_required？

### ISSUE THREAD

**Issue by johnxiaohe** [apache/apisix#11091]
### Current State

filepath: https://github.com/apache/apisix/blob/master/apisix/cli/ops.lua
location: line196

### Desired State

please enable `admin_key_required` and set a secure admin key!

**Comment by sunheyi6** [comment]
By default, it is enabled, but you have the option to disable it if you prefer.

**Comment by shreemaan-abhishek** [comment]
I'll consider this resolved.

**Comment by johnxiaohe** [comment]
> By default, it is enabled, but you have the option to disable it if you prefer.

If it is disabled, do I still need to set admin_key?  I just think this warning is a bit strange
![image](https://github.com/apache/apisix/assets/37014780/23479389-1b26-4fa8-8ee7-ad96c83e9fc2)

**Comment by shreemaan-abhishek** [comment]
> If it is disabled, do I still need to set admin_key?

I don't think so.

>  I just think this warning is a bit strange

this is just a warning and not an error/failure :)

**Comment by shreemaan-abhishek** [comment]
Oops, now I understand what you were talking about.

**Comment by johnxiaohe** [comment]
> Oops, now I understand what you were talking about.

Haha, yes, so I was a little confused about admin_key_required after seeing the comments. But there should be something wrong with this log only.

**Comment by shreemaan-abhishek** [comment]
the warning message was incorrect, I have raised a PR to fix it.
