### ISSUE TITLE
help request: 请教如何配置可以进入我自己的server

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#11092]
### Description

我在配置文件中配置了：
http_configuration_snippet: |
server {
    listen 443 ssl http2;
    server_name 10.110.3.51;
    return 404
    }
重启apisix查看nginx.conf已经将该server写入，然后通过浏览器调用
https://10.110.3.51/发现无法进入我设置的server而是进了默认的server，从日志中也可以发现一直打印
init.lua:172: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 10.10.16.129, server: 0.0.0.0:443
我这里查了一点资料nginx应该会默认优先匹配server_name相同的，但是实际情况不是。所以想知道是我配置有问题还是apisix对nginx的底层逻辑做了修改。
谢谢。
  

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
hi could you please update the issue description in english?

**Comment by kayx23** [comment]
Is there any reason you want to use NGINX's way to configure? If not, please use APISIX native approach to configure the same.
