### ISSUE TITLE
Is it possible to get the matched route_id in a custom wasm plugin?

### ISSUE THREAD

**Issue by constlhq** [apache/apisix#11098]
### Description

I want to access the `route_id` of current matched route , but have no clue after reading the docs and the wasm plugin examples.

### Environment

- APISIX version (run `apisix version`): 3.8
- Operating system (run `uname -a`): 20.04.1-Ubuntu
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by sunheyi6** [comment]
It seems not possible to get route_id in the custom wasm plugin,but you can get the route_id  in admin api

**Comment by hanqingwu** [comment]
why does you need get route_id  from custom wasm plugin ?  what 's your purpose ?

**Comment by shreemaan-abhishek** [comment]
If you have access to the `ctx` variable, you can get it like so: `ctx.matched_route.value.id`. You can learn more here: https://blog.frankel.ch/rabbit-hole-apisix-plugin/. written by @nfrankel 👏🏼
