### ISSUE TITLE
bug: 编排模式配置的插件不生效，且路由列表不显示插件名

### ISSUE THREAD

**Issue by JacianZhu** [apache/apisix#11100]
### Current Behavior

使用编排模式配置插件：
创建Route后再插件配置中使用编排模式配置 jwt-auth插件，
提交后 路由列表中 插件列 不显示插件名。
请求创建的Route， jwt-auth插件未生效。
使用普通模式配置  jwt-auth插件，请求Route，返回 {"message":"Missing JWT token in request"}， jwt-auth插件生效

### Steps to Reproduce

使用编排模式配置插件：
创建Route后再插件配置中使用编排模式配置 jwt-auth插件，
提交后 路由列表中 插件列 不显示插件名。
请求创建的Route， jwt-auth插件未生效。
使用普通模式配置  jwt-auth插件，请求Route，返回 {"message":"Missing JWT token in request"}， jwt-auth插件生效

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
is this similar to #11101 ? Please use english.

**Comment by kayx23** [comment]
duplicate of #11101
