### ISSUE TITLE
help request: Connect to upstream through proxy server (http_proxy)

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#11102]
### Description

Hi, 
When Apisix is running behind a firewall the only way to access some external upstreams is through a http_proxy or something similar. But how do I make Apisix know about http_proxy?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
you mean the upstream is protected by a firewall?

**Comment by kayx23** [comment]
APISIX is a proxy by itself. Do you mean there is another layer of (http) proxy sitting in front of your upstream service?
