### ISSUE TITLE
Impact for Redis license change?

### ISSUE THREAD

**Issue by billmoling** [apache/apisix#11118]
### Description

Dear APISIX Developers,

With the recent announcement of Redis adopting dual Source-Available Licensing (RSALv2 and SSPLv1) from version 7.4 onwards, moving away from the BSD 3-Clause License, I'm reaching out to gather your perspectives on this significant change. Given APISIX's utilization of Redis, particularly for features like rate limiting, how do you foresee this licensing shift impacting the APISIX roadmap? Are there any anticipated adjustments or considerations in response to these changes? maybe support other cache system?

News here: https://redis.com/blog/redis-adopts-dual-source-available-licensing/

**Comment by shreemaan-abhishek** [comment]
cc: @moonming
