### ISSUE TITLE
feat: As a sysadmin, I want to install on RedHat9, so that I can use it

### ISSUE THREAD

**Issue by Et7f3** [apache/apisix#11119]
### Description

https://apisix.apache.org/docs/apisix/next/installation-guide/#installation-via-rpm-repository

It mention only CentOs 7 and 8. Can a rpm provide support for rhel9 ? or centos stream 9 ? RedHat offers 32 dev licences for free (if needed in CI).

**Comment by shreemaan-abhishek** [comment]
Building from source FTW!

**Comment by Et7f3** [comment]
After opening the issue I did that and encountered an issue with umi https://github.com/umijs/umi/issues/9335#issuecomment-2038467938 but I was able to use it. I don't know if I compiled successfully or I have forgotten something but plugins page crashed and another page (edit upstream/service IIRC) in dashboard.

I just wanted a quicker way to test.

**Comment by shreemaan-abhishek** [comment]
If this is an issue related to installation of apisix dashboard then you should open an issue here: https://github.com/apache/apisix-dashboard/

**Comment by Et7f3** [comment]
So I can install a rpm with apisix (without dashboard) on rhel9 ? I didn't find one.
