### ISSUE TITLE
help request: Proxy Cache Plugin -- How to set cache_ttl for disk strategy?

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#11120]
### Description

Hi,
I want to know is it possible to set time (60 minutes) for Apisix to return cached response if I use disk strategy?

### Environment

- APISIX version (run `apisix version`): 3.6
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
You would adjust the value in config.yaml. See https://docs.api7.ai/hub/proxy-cache/configuration#static-configurations
