### ISSUE TITLE
Request for New Invite Link to Apache Software Foundation Slack Workspace

### ISSUE THREAD

**Issue by fykaa** [apache/apisix#11125]
### Description

I attempted to join the Apache Software Foundation Slack workspace using the invite link provided [here](https://apisix.apache.org/docs/general/join/#join-the-slack-channel), but it appears to not work. It says to open an issue to get a new invite link so that we can join the workspace.

There possibly a need for changes in[ this website doc. ](https://github.com/apache/apisix-website/blob/master/website/docs/general/join.md)

### Environment

-

**Comment by shreemaan-abhishek** [comment]
Hi Faeka, please drop your email here so that I can invite you to Apache's slack workspace to join the #apisix channel.

> There possibly a need for changes in[ this website doc.](https://github.com/apache/apisix-website/blob/master/website/docs/general/join.md)

I guess not, ASF's guidelines recommends against usage of permanent invitation link/sharing invitation links in public.

**Comment by fykaa** [comment]
Got it! Thanks for the update. I believe I should mail [dev@apisix.apache.org](mailto:dev@apisix.apache.org) for the slack invite in that case.

**Comment by Karan3304** [comment]
Hi everyone,

My name is Karan Swami, and I’m excited to join this community! I have a strong interest in web development, particularly with JavaScript, React.js,typescript. but facing an issue in joining apache slack channel,i guess i need an invite link,can someone help

**Comment by Karan3304** [comment]
@fykaa yes I did mail mam,and I got the invite link,as a guest I joined slack channel,thank you mam 🙂
