### ISSUE TITLE
apache/apisix:3.8.0-redhat execution /usr/local/apisix-go-plugin-runner/go-runner: No such file or directory

### ISSUE THREAD

**Issue by insulaire** [apache/apisix#11131]
### golang build os info:
golang:1.20-alpine

GOOS="linux
GOARCH="amd64"

go build -buildmode=pie  -o=bin/go-runner ./cmd/go-runner/

### Dockerfile:

After the build is completed, there will be an exception **No such file or directory**.

```
FROM apache/apisix:3.8.0-redhat

COPY ./bin/go-runner /usr/local/apisix-go-plugin-runner/go-runner

CMD [ "/usr/local/apisix-go-plugin-runner/go-runner" ]
```

From **apache/apisix:2.12.1-alpine**, there will be no error

```
FROM apache/apisix:2.12.1-alpine

COPY ./bin/go-runner /usr/local/apisix-go-plugin-runner/go-runner

CMD [ "/usr/local/apisix-go-plugin-runner/go-runner" ]
```

why?
Thanks for the advice.

### Environment

- APISIX version (3.8):

**Comment by insulaire** [comment]
Why no have 3.8.0-alpine?

**Comment by insulaire** [comment]
@hanqingwu  The file exists.
![image](https://github.com/apache/apisix/assets/35367433/a1ad3bf1-3324-4c27-b827-8d3013225663)

**Comment by hanqingwu** [comment]
so no more  exception No such file or directory.  ?

**Comment by insulaire** [comment]
@hanqingwu  
![image](https://github.com/apache/apisix/assets/35367433/710e1504-a4ca-41db-b8b7-6d397aaeb03d)
no more.

**Comment by hanqingwu** [comment]
`ls`   check  it exist , but run it show No such file  .. ?

**Comment by insulaire** [comment]
http://www.manongjc.com/detail/54-kradejqhknkbpjb.html
