### ISSUE TITLE
help request: How to save nginx's  time_iso8601  field into clickhouse's datetime format?

### ISSUE THREAD

**Issue by qyk1995** [apache/apisix#11130]
### Description

ClickHouse server version 24.3.2.23 (official build).
I want to store the nginx  time_iso8601 field in clickhouse, and the field in clickhouse is datetime. How do I create a table?

I try to set the clickhouse field to a string, and nginx time_iso860 can store it successfully. But when the field in clickhouse is datetime, the data is empty. Why?

**clickhouse-logger  Configuration：**
  "_meta": {
    "disable": false
  },
  "database": "default",
  "disable": false,
  "endpoint_addrs": [
    "http://192.168.5.5:8123"
  ],
  "log_format": {
    "balancer_ip": "$balancer_ip",
    "balancer_port": "$balancer_port",
    "client_ip": "$remote_addr",
    "host": "$host",
    "request_time": "$request_time",
    "service_id": "$service_id",
    "status": "$status",
    "time": "$time_iso8601",
    "upstream_response_time": "$upstream_response_time",
    "uri": "$uri"
  },
  "logtable": "test",
  "password": "123456",
  "user": "default"
}

**clickhouse  SQL:**
CREATE TABLE default.test (
    host String,
    client_ip String,
    route_id String,
    service_id String,
    `time` DateTime,
    PRIMARY KEY (`time`)
) ENGINE = MergeTree()
ORDER BY (`time`);

**clickhouse-logger log:**
        batch-processor.lua:95: Batch Processor[clickhouse-logger] failed to process entries: server returned status code[404] host[192.168.5.5] port[8123] body[Code: 60. DB::Exception: Table default.test does not exist. (UNKNOWN_TABLE) (version 24.3.2.23 (official build))

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
what about  $msec/1000  ?
