### ISSUE TITLE
feat: As a user, I want get_headers no longer returns all http headers, but limited to the default 100.

### ISSUE THREAD

**Issue by ronething** [apache/apisix#11139]
### Description

Currently, apisix fetches request headers without limiting them, which could lead to security risks, and we could consider limiting them to the original default of 100.

I can file a PR to make this change.

ref: 
- https://github.com/apache/apisix/blob/c6b9f993136bdae4548cf3c7b60b7c8f0e7fa95e/apisix/core/request.lua#L52-L73
- https://github.com/openresty/lua-nginx-module#ngxreqget_headers

**Comment by starsz** [comment]
Good ! Assign to you

**Comment by starsz** [comment]
Note this is a breaking change, we need to add into the release and changelog.
