### ISSUE TITLE
help request: upstream reset when client rate limited

### ISSUE THREAD

**Issue by imtzw** [apache/apisix#11142]
### Description

when client has rate limit (such as 50k/s) , 
in apisix's connection with upstream appears zero window , 
then it turns out apisix reset tcp connection with upstream then ( not immediately , after a while) sends a FIN to client , 
even if client tries to keep alive.
it seems for me, modifying http.send_timeout in config.yaml will resolve this , 
(it seems that if upstream sends no ACK after windowfull for this timeout .
one thing confusing is, this send_timeout argument is said to be a timeout_config for connection with client) 
but im concerned about the reason and what is best method/practice? 

### Environment

- APISIX version (run `apisix version`):  /usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
2.10.1

- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.19.3.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> 2.10.1

The version is too old, please consider upgrading or check if the bug exists in newer versions. If possible please share the steps on how to reproduce this issue thanks>

**Comment by imtzw** [comment]
This seems not a bug. 
when a socket receives faster from nginx than it sends to client, it will not be ready for a while.
if nginx doesnot permit buffer body, it may for such a while recv nothing from upstream. thus upstream's sending is blocked for just such a while ( if the upstream sends healthily , its send-queue is fullfilled instantly)
