### ISSUE TITLE
help request: apisix pod cpu is full，but There's no obvious reason

### ISSUE THREAD

**Issue by yydance** [apache/apisix#11154]
### Description

apisix is deployed in k8s，and the resources is limited CPU 4, memory 8Gi. Some day，CPU is full. I checked the apisix log, the apisix metrics, and the requests acrossing apisix，I don't find the obvious reason. So how can I analyse the problem?

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): centos7.9 Linux pre-k8m1 4.14.141-2.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.12
- APISIX Dashboard version, if relevant: 3.0
- Plugin runner version, for issues related to plugin runners: prometheus,real-ip,request-id,cors..
- LuaRocks version, for installation issues (run `luarocks --version`):

The apisix is deployed in k8s using helm, k8s version is 1.25.5

**Comment by nitishfy** [comment]
Hi, could you provide the steps to reproduce this issue? Are you unsure why is the pod CPU going full?

**Comment by yydance** [comment]
I can't reproduce the issue. In my environment, there is no high concurrency. when it occurs, I have to delete the pod, and then it recovered.  Like go pprof, how can I analyse?

**Comment by hanqingwu** [comment]
Can you try to use prometheus  and  get some information  ?
https://apisix.apache.org/docs/apisix/plugins/prometheus/

**Comment by yydance** [comment]
@hanqingwu @nitishfy I find out the reason. When I enable prometheus plugin, then I use wrk to test, below 
```
# wrk -t8 -c500 -d60s -s ./get.lua http://10.252.228.254:61160/infra/health/ping
```
And the result:
```
Running 1m test @ http://10.252.228.254:61160/infra/health/ping
  8 threads and 500 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    14.33ms   29.20ms 197.79ms   87.44%
    Req/Sec    80.82     69.02   370.00     78.42%
  1123 requests in 1.00m, 355.40KB read
Requests/sec:     18.69
Transfer/sec:      5.92KB
```
Then apisix pod cpu is full even though I stop the requests.

Prometheus configuration:
```
  prometheus:
    enabled: true
    containerPort: 9091
    metricPrefix: "apisix_"
    path: "/apisix/prometheus/metrics"

```

**Comment by hanqingwu** [comment]
so  if you disable plugin prometheus, the pod cpu is normal . the cpu full is in the plugin prometheus or  k8s pull metrics from the pod ?

**Comment by yydance** [comment]
> so if you disable plugin prometheus, the pod cpu is normal . the cpu full is in the plugin prometheus or k8s pull metrics from the pod ?

@hanqingwu It looks like this，I will continue to test other scenes
