### ISSUE TITLE
Oidc Plugin with parameter  "bearer_only": true, always return 401 unauthorized

### ISSUE THREAD

**Issue by yahia20456** [apache/apisix#11165]
### Description

I'm using apache apisix dashboard to configure routes and i'm using oidc plugin to authorize the access and this is the example of the configuration 
{
  "_meta": {
    "disable": false
  },
  "bearer_only": true,
  "client_id": "apisixAuthorization",
  "client_secret": "RqAm2yvVzBOMyREDIlZFN1kQ3lb6pMwp",
  "discovery": "https://*********/realms/apache-apisix/.well-known/openid-configuration",
  "introspection_endpoint": "********/realms/apache-apisix/protocol/openid-connect/token/introspect",
  "introspection_endpoint_auth_method": "client_secret_basic",
  "realm": "apache-apisix",
  "redirect_uri": "https://www.keycloak.org/",
  "scope": "openid profile"
}
when i set   "bearer_only": false it works and but when i set "bearer_only": true  and pass the bearer token in the header i get always 401 
Please if there any other solutions or alternatives keep me updated

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
set `"use_jwks": true`

**Comment by yahia20456** [comment]
thanks @kayx23 it works
