### ISSUE TITLE
CLI: set default value when render `nginx.conf`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1117]
maybe we can use https://github.com/iresty/jsonschema

**Comment by moonming** [comment]
Can you show a example? not get your point.

**Comment by membphis** [comment]
The `conf/config.yaml` is a user configuration file. When the APISIX version is upgraded, the users would like to reuse the old `config.yaml` file.  At this time, some new configuration items should use the default 
 values.

We can use `jsonschema` to complete the valid check of parameter values and set the correct default values, without having to deal with a configuration item individually in the CLI.
