### ISSUE TITLE
bug: Stream Proxy expires after a period of time

### ISSUE THREAD

**Issue by guliuliu1** [apache/apisix#11178]
### Description

![apisix-tcp-stream](https://github.com/apache/apisix/assets/30524551/68171ff9-c222-4db4-9b25-6bb75234a76b)

The TCP dynamic proxy becomes inactive after a certain period of time.
```
curl --location --request PUT 'http://10.8.9.84:9180/apisix/admin/stream_routes/' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' \
--header 'Content-Type: application/json' \
--data '{
  "id": "stream-route-mysql",
  "server_addr": "10.8.9.84",
  "server_port": 9393,
  "upstream": {
    "nodes": {
      "10.8.9.63:8080": 1
    },
    "type": "roundrobin"
  }
}'
```

### Environment

Linux localhost.localdomain 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.9.2009 (Core)
apisix version:3.2.2-centos

**Comment by guliuliu1** [comment]
> 你能提供一些关于 APISIX 的日志吗？

10.8.9.11 [22/Apr/2024:02:23:56 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:23:55 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:23:56 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:23:55 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:01 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:01 -0400] TCP 500 0 0 0.000
127.0.0.1 [22/Apr/2024:02:24:01 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:01 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:09 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:11 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:09 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:10 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:11 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:31 -0400] TCP 500 0 0 0.000
10.8.9.11 [22/Apr/2024:02:24:42 -0400] TCP 200 488 295 20.163
10.8.9.11 [22/Apr/2024:02:24:51 -0400] TCP 200 835 696 20.111

**Comment by guliuliu1** [comment]
> can you provide some log about apisix ?


Sorry for the confusion earlier. I have gone back to reproduce the scenario again, and the attached files include logs and packet capture files. The packet capture files record the requests sent by the APISIX server to the backend business.
[apisix.zip](https://github.com/apache/apisix/files/15059810/apisix.zip)

**Comment by hanqingwu** [comment]
I can't find exception from access_stream.log . 
Can you provide apisix running log ?  Or Can you try  get  http://10.8.9.84:9180/apisix/admin/stream_routes  is right config when proxy return 500?

**Comment by guliuliu1** [comment]
curl --location 'http://10.8.9.84:9180/apisix/admin/stream_routes/' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' \
--data ''
{
&nbsp; &nbsp; "list": [
&nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "createdIndex": 85,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "value": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "server_addr": "10.8.9.84",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "upstream": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "nodes": {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "10.8.9.63:8080": 1
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "hash_on": "vars",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "type": "roundrobin",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "scheme": "http",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "pass_host": "pass"
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "server_port": 9393,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "id": "stream-route-mysql",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "update_time": 1713773748,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "create_time": 1713747005
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; },
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "modifiedIndex": 133,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; "key": "/apisix/stream_routes/stream-route-mysql"
&nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; ],
&nbsp; &nbsp; "total": 1
}


It can be obtained normally, and there are no other related logs.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月22日(星期一) 下午4:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [apache/apisix] help request: Stream Proxy expires after a period of time (Issue #11178)














 
我找不到access_stream.log的例外。
你能提供apisix运行日志吗？或者，当代理返回 500 时，您可以尝试获取 http://10.8.9.84:9180/apisix/admin/stream_routes 正确的配置吗？
 
-
 直接回复此电子邮件，在 GitHub 上查看或取消订阅。
您收到此消息是因为您修改了打开/关闭状态。Message ID: ***@***.***&gt;

**Comment by guliuliu1** [comment]
> I can't find exception from access_stream.log . Can you provide apisix running log ? Or Can you try get http://10.8.9.84:9180/apisix/admin/stream_routes is right config when proxy return 500?

It can be obtained normally, and there are no other related logs.
```
curl --location 'http://10.8.9.84:9180/apisix/admin/stream_routes/' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' \
--data ''
{
    "list": [
        {
            "createdIndex": 85,
            "value": {
                "server_addr": "10.8.9.84",
                "upstream": {
                    "nodes": {
                        "10.8.9.63:8080": 1
                    },
                    "hash_on": "vars",
                    "type": "roundrobin",
                    "scheme": "http",
                    "pass_host": "pass"
                },
                "server_port": 9393,
                "id": "stream-route-mysql",
                "update_time": 1713773748,
                "create_time": 1713747005
            },
            "modifiedIndex": 133,
            "key": "/apisix/stream_routes/stream-route-mysql"
        }
    ],
    "total": 1
}
```

**Comment by hanqingwu** [comment]
Can you upgrade  apisix  latest version to test it  ?

**Comment by guliuliu1** [comment]
> Can you upgrade apisix latest version to test it ?

I've tested the APISIX 3.9 version, and the results remain consistent. Additionally, when testing TCP stream to proxy TCP sessions, direct disconnection occurs.
