### ISSUE TITLE
docs: improve `aws-lambda` plugin doc 

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#11177]
### Current State

https://apisix.apache.org/docs/apisix/plugins/aws-lambda doc seems outdated.

### Desired State

* Correct field name: There is no `secret_key` field. The actual field name is `secretkey`.
* [IAM Authorization Schema](https://apisix.apache.org/docs/apisix/plugins/aws-lambda/#iam-authorization-schema) section should be merged with the section above for easier understanding (e.g. `authorization.iam.accesskey`)
* The introduction should mention this plugin implements [AWS Signature Version 4 signing](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-signing.html).
* `service` field should provide more info for what users can/should configure. For example, with lambda function, this field should be configured as `lambda`, otherwise one could run into error `{"message":"Credential should be scoped to correct service: 'lambda'. "}`
* Correct examples, such as the extra `,` at the end causing the route creation to error:
![image](https://github.com/apache/apisix/assets/39619599/f115d28f-a7be-4ec6-be90-8bc9a87ea6d2)

Potentially more info needs to be updated. Review against code and update doc.

**Comment by nitishfy** [comment]
I'd like to take this up!
