### ISSUE TITLE
Bug: Very Poor Service Apche APisix

### ISSUE THREAD

**Issue by Asakaigg** [apache/apisix#11208]
### Current Behavior

I have never seen the service like this.
I have followed the standard way but the module doesn't install at all
I couldn't know how can we use this service ???
 

### Expected Behavior

I have installed one houndred times but it doesn't install 
Very poor service 

### Error Logs

it needs to down 

### Steps to Reproduce

https://apisix.apache.org/docs/apisix/installation-guide/

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Which installation method did you use?

For a quick start please use 

> Refer to the [Getting Started](https://apisix.apache.org/docs/apisix/getting-started/README/) guide for a quick walk-through on running Apache APISIX.

**Comment by shreemaan-abhishek** [comment]
If you are seeking help for installing APISIX from source, please create a new issue with some beneficial information about the EXACT error that you are facing. Thanks.
