### ISSUE TITLE
feat: As a user, I want APISIX control-plane pod to read Kubernetes CRDs for Routes/Consumer/Upstream/etc. and not APISIX ingress-controller pod, so that I can use Kubernetes CRDs natively without deploying APISIX ingress controller.

### ISSUE THREAD

**Issue by rrmistry** [apache/apisix#11210]
### Description

Currently, the Kubernetes CRDs are read by the APISIX ingress controller pod and updated in the control plane. But if we rely on another service for ingress (e.g. Istio Ingress Gateway) and want to use APISIX only for API routing) and disable APISIX ingress-controller then we noticed that the Kubernetes CRD instances do not get registered in APISIX (confirmed via APISIX Dashboard).

Our current workaround is to run a Kubernetes Job pod that makes REST API calls to APISIX admin endpoint to make the necessary objects.

But it would be ideal if the APISIX control pod itself would read the CRD instances. Not the ingress controller.

This way, deleting the Kubernetes CRD instances would also clean up unused objects in APISIX.

**Comment by Revolyssup** [comment]
Apisix control plane pod cannot do that currently and in my knowledge I dont think this is something that APISIX will do in future which is talking natively through Kubernetes resources. Currently for using CRDs, ingress controller is the only recommended way. APISIX is platform agnostic and can be deployed anywhere. Then using APISIX ingress controller, it is make kubernetes native. It cannot directly spin up informers for the APISIX k8s resources supported by ingress controller.

**Comment by rrmistry** [comment]
Too bad but fair point. I am ok to close this issue.

_____

The problem being solved for is how to make APISIX work with some fixed predetermined configuration set (i.e. some collection of APISIX objects that are version-controlled and also applied at startup to fully initialize it)

As mentioned earlier, calling admin REST API endpoints on startup is an acceptable workaround but not ideal. It would be good if APISIX can allow creating routes/upstream/consumers/etc. via a config file provided at startup. So that it can be dynamically configured and ready to go without having to call API endpoints.

**Comment by shreemaan-abhishek** [comment]
@rrmistry you might wanna checkout the standalone mode: https://docs.api7.ai/apisix/production/deployment-modes#standalone-mode
