### ISSUE TITLE
help request: help request: help request: apisix 3.8.0 helm install request etcd Operation already in progress

### ISSUE THREAD

**Issue by wangchao732** [apache/apisix#11212]
### Description

https://github.com/apache/apisix-helm-chart/issues/723#issue-2148795044

When I change the domain name address in the apisix configuration file, etcd cluster ip is started successfully. 

![image](https://github.com/apache/apisix/assets/19440083/9f8c4616-4546-464d-b197-1fb4b8e94c1d)

![image](https://github.com/apache/apisix/assets/19440083/f451e02b-5fcc-4c52-8755-696736c00b50)

### Environment

k8s : v1.22.12

**Comment by shreemaan-abhishek** [comment]
please don't spam by creating duplicate issues.

**Comment by wangchao732** [comment]
> please don't spam by creating duplicate issues.

You're right, but the submission hasn't been responded to for a long time, just want help with the issue.
