### ISSUE TITLE
bug: apisix prometheus metrics port not running.

### ISSUE THREAD

**Issue by wangchao732** [apache/apisix#11235]
### Current Behavior

apisix heml on k8s

  plugins:                          # plugin list
    - promethues
  plugin_attr:
    prometheus:
      export_uri: /apisix/prometheus/metrics
      metric_prefix: apisix_
      enable_export_server: true
      export_addr:
        ip: 0.0.0.0
        port: 9099

### Error Logs

is null.

2024/05/07 09:25:09 [warn] 52#52: *1 [lua] plugin.lua:205: load(): new plugins: {"ua-restriction":true,"cors":true,"zipkin":true,"example-plugin":true,"proxy-control":true,"sls-logger":true,"csrf":true,"real-ip":true,"limit-req":true,"response-rewrite":true,"ext-plugin-post-resp":true,"http-logger":true,"skywalking-logger":true,"cas-auth":true,"server-info":true,"gzip":true,"wolf-rbac":true,"api-breaker":true,"inspect":true,"workflow":true,"echo":true,"key-auth":true,"forward-auth":true,"openwhisk":true,"limit-count":true,"aws-lambda":true,"loki-logger":true,"request-id":true,"proxy-mirror":true,"degraphql":true,"request-validation":true,"multi-auth":true,"grpc-transcode":true,"datadog":true,"loggly":true,"client-control":true,"opa":true,"ext-plugin-pre-req":true,"limit-conn":true,"proxy-rewrite":true,"kafka-logger":true,"serverless-post-function":true,"prometheus":true,"uri-blocker":true,"hmac-auth":true,"public-api":true,"fault-injection":true,"azure-functions":true,"splunk-hec-logging":true,"ldap-auth":true,"google-cloud-logging":true,"basic-auth":true,"mocking":true,"udp-logger":true,"ext-plugin-post-req":true,"clickhouse-logger":true,"jwt-auth":true,"rocketmq-logger":true,"file-logger":true,"serverless-pre-function":true,"tcp-logger":true,"authz-casdoor":true,"ai":true,"referer-restriction":true,"openfunction":true,"grpc-web":true,"chaitin-waf":true,"ip-restriction":true,"body-transformer":true,"consumer-restriction":true,"openid-connect":true,"proxy-cache":true,"jwe-decrypt":true,"traffic-split":true,"authz-keycloak":true,"kafka-proxy":true,"authz-casbin":true,"syslog":true,"elasticsearch-logger":true,"tencent-cloud-cls":true,"redirect":true}, context: init_worker_by_lua*

### Steps to Reproduce

 curl -i http://192.168.44.159:9099/apisix/prometheus/metrics
curl: (7) Failed connect to 192.168.44.159:9099; 拒绝连接

### Environment

- APISIX version  3.8.0
- Helm install on k8s
- 
![1715074645756](https://github.com/apache/apisix/assets/19440083/69ef11d5-3a71-4ea8-81c9-6ec34e2cbd7b)

**Comment by hanqingwu** [comment]
Can you to  direct access pod whether works  ?  ` curl  -i http://10.10.0.186:9099/apisix/prometheus/metrics`

**Comment by wangchao732** [comment]
> Can you to direct access pod whether works ?

Invalid，Because the port is not listening, it should be that the prometheus plugin does not start for some reason.

**Comment by wangchao732** [comment]
![image](https://github.com/apache/apisix/assets/19440083/af8265a6-1ad2-4305-8e9f-f2edebd2f3c3)

**Comment by wangchao732** [comment]
> Can you to direct access pod whether works ? ` curl -i http://10.10.0.186:9099/apisix/prometheus/metrics`

docker run apisix. 

![image](https://github.com/apache/apisix/assets/19440083/ac8e2672-5f79-4bec-a4b4-874d6e927edb)

![image](https://github.com/apache/apisix/assets/19440083/cd8b0f05-2b61-4df4-9e0f-184a8c79cf09)
![image](https://github.com/apache/apisix/assets/19440083/2aeb5681-8b55-4e43-bf0e-1bfade2f49fb)

**Comment by hanqingwu** [comment]
Can you check your firewall has closed ?

**Comment by wangchao732** [comment]
> r firewall has closed ?

Yes,This is basic common sense, and in addition, this is a stand-alone local operation.

**Comment by wangchao732** [comment]
> Can you check your firewall has closed ?

Apisix log error : reportServiceInstance(): Instance report fails, timeout, context: ngx.timer

**Comment by wangchao732** [comment]
> Can you check your firewall has closed ?

Oh, this my config issue. sorry!
