### ISSUE TITLE
help request: openid-connect plugin configuration cannot take effect

### ISSUE THREAD

**Issue by lrfdehao** [apache/apisix#11245]
### Description

I saw that there are many configurations in the openid-connect plugin, such as refresh_session_interval, but in fact no relevant implementation was found in the code. Is this currently only configuration but no implementation?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by flea1lt** [comment]
`refresh_session_interval ` is used by [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc).

**Comment by lrfdehao** [comment]
thx
