### ISSUE TITLE
bug: 404 Not Found

### ISSUE THREAD

**Issue by rahulracker7539** [apache/apisix#11257]
### Current Behavior

am getting "404 Not Found" while doing curl request. it was all working fine and all of sudden today it stopped working. I have tried many things but still couldn't manage to fix this issue

please help me to fix this issue

### Expected Behavior

response from curl request without any 404 not found

### Error Logs

[warn] 48#48: *39277 [lua] plugin.lua:1160: run_plugin(): public-api exits with http status code 404,
and while doing curl request getting below 

curl --location --request GET 'https://apisix-test.com/s' --header 'X-EES-AUTH-HASH: <>' --header 'X-EES-AUTH-CLIENT-ID: <>' --header 'X-AUTH-HASH:<>' --header 'X-AUTH-CLIENT-ID: <>' --header 'X-TRANSACTION-ID: <>' --header 'X-RETRY: 1' --header 'X-EES-OPERATOR: 1' --header 'X-EES-CALLER: POSTMAN' --header 'X-EES-CALLER-VERSION: 0' --header 'X-EES-MESSAGEID: <>' --header 'Content-Type: application/json'
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>

### Steps to Reproduce

I have used helm chart to deploy the apisix and ingress controller.
here is my configmap :-

apisix:    
  node_listen:    
    - 9080
  enable_heartbeat: true
  enable_admin: true
  enable_admin_cors: true
  enable_debug: false
  enable_dev_mode: false
  enable_reuseport: true
  enable_ipv6: true
  enable_http2: true
  enable_server_tokens: true

  proxy_cache:                         
    cache_ttl: 10s                     
    zones:                             
    - name: disk_cache_one             
      memory_size: 50m                 
      disk_size: 1G                    
      disk_path: "/tmp/disk_cache_one" 
      cache_levels: "1:2"              

  router:
    http: radixtree_host_uri  
    ssl: 'radixtree_sni'        

  proxy_mode: http
  stream_proxy:                 
    tcp:                        
      - 9100
    udp:                        
      - 9200
  dns_resolver_valid: 30
  resolver_timeout: 5

  ssl:
    enable: false
    listen:
      - port: 9443
        enable_http3: false
    ssl_protocols: "TLSv1.2 TLSv1.3"
    ssl_ciphers: "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA"

nginx_config:    
  http_server_configuration_snippet: |
    large_client_header_buffers 16 64k;
    proxy_buffering on;
    proxy_buffers 32 8k;
    proxy_buffer_size 4k;
  error_log: "/dev/stderr"
  error_log_level: "warn"
  worker_processes: "auto"
  enable_cpu_affinity: true
  worker_rlimit_nofile: 20480
  event:
    worker_connections: 10620
  http:
    enable_access_log: true
    access_log: "/dev/stdout"
    access_log_format: '$remote_addr - $remote_user [$time_local] $http_host \"$request\" $status $body_bytes_sent $request_time \"$http_referer\" \"$http_user_agent\" $upstream_addr $upstream_status $upstream_response_time \"$upstream_scheme://$upstream_host$upstream_uri\"'
    access_log_format_escape: default
    keepalive_timeout: "60s"
    client_header_timeout: 60s
    client_body_timeout: 60s
    send_timeout: 10s
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_from:
      - 127.0.0.1
      - 'unix:'

plugins:
  - node-status
  - public-api

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    allow_admin:
      - 127.0.0.1/24
      - 0.0.0.0/0
    admin_listen:
      ip: 0.0.0.0
      port: 9180
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin
      - name: "viewer"
        key: 4054f7cf07e344346cd3f287985e76a2
        role: viewer

  etcd:
    host:                         
      - "http://apisix-etcd.ingress-apisix.svc.cluster.local:2379"
    prefix: "/apisix"
    timeout: 30

### Environment

- APISIX version (run `apisix version`): 3.9.1
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.25.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: -> Image:  apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Please format better for an easier read

**Comment by rahulracker7539** [comment]
> Please format better for an easier read

done

**Comment by acronymor** [comment]
![image](https://github.com/apache/apisix/assets/24858758/433b3ffe-e098-49b8-a77e-38d9821f9185)

i meet the same question.

**Comment by acronymor** [comment]
@acronymor it's not the bug, I didn't notice that the two ports were different.

![image](https://github.com/apache/apisix/assets/24858758/fb75c14a-e04d-40ec-9518-381530a163bb)

---

I succeeded by following this tutorial.

https://apisix.apache.org/docs/apisix/getting-started/README/
