### ISSUE TITLE
bug:使用四层代理后，一直报错 [error] 53#53: *2206 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/stream/router/ip_port.lua:46: attempt to index field 'server_addr_matcher' (a nil value)

### ISSUE THREAD

**Issue by dilinliu1116** [apache/apisix#11259]
### Current Behavior

版本：3.8.0-debian
上游配置：
![image](https://github.com/apache/apisix/assets/155533899/1dbd4f72-c4cb-4ffc-b8ca-0723a3b1e515)
![image](https://github.com/apache/apisix/assets/155533899/6597be26-a652-4ed1-8e4f-57fd646fe476)
同样的配置下版本3.5.6-debian的一切正常可以访问。3.8.0-debian的就一直报这个错

### Error Logs

stack traceback:
coroutine 0:
        /usr/local/apisix/apisix/stream/router/ip_port.lua: in function 'match_addrs'
        /usr/local/apisix/apisix/stream/router/ip_port.lua:178: in function 'match'
        /usr/local/apisix/apisix/init.lua:1045: in function 'stream_preread_phase'
        preread_by_lua(nginx.conf:104):2: in main chunk while prereading client data, client: 192.168.10.130, server: 192.168.10.130:3000
2024/05/16 17:08:31 [error] 53#53: *2206 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/stream/router/ip_port.lua:46: attempt to index field 'server_addr_matcher' (a nil value)

### Steps to Reproduce

1.使用docker-compose运行apisix
2.进入配置文件改  proxy_mode: http&stream
                                 stream_proxy:                 # TCP/UDP L4 proxy
                                     tcp:
                                        - addr: 3000
  3.重启apisix容器
 4.使用curl将上游代理信息打进apisix 
5.访问http，报错  

### Environment

- APISIX version :3.8.0-debian
- docker部署

**Comment by hanqingwu** [comment]
我使用 3.8.0 的测试没有重现
