### ISSUE TITLE
问题：apisix开启chaitin-waf后，流量如何被管理?

### ISSUE THREAD

**Issue by Jinxin231** [apache/apisix#11254]
### Description

https://apisix.apache.org/zh/docs/apisix/plugins/chaitin-waf/

文档描述 流量将被转给长亭 WAF 
问题是，后续的流量是会回给apisix，继续按插件优先级处理,还是流量会被长亭 WAF 转发给相关的应用服务器？

谢谢解答

**Comment by hanqingwu** [comment]
可以看雷池的介绍
社区版雷池以反向代理方式接入，优先于网站服务器接收流量，对流量中的攻击行为进行检测和清洗，将清洗过后的流量转发给网站服务器。
https://waf-ce.chaitin.cn/docs/

**Comment by moonming** [comment]
Chaitin waf is a plug-in of Apache APISIX, and chaitin waf does not know the upstream address and load balancing strategy. Traffic will still be forwarded to the upstream service through Apache APISIX.
