### ISSUE TITLE
help request: Setting cookie based on a condition.

### ISSUE THREAD

**Issue by pavankumar-siripurapu** [apache/apisix#11279]
### Description

we have a requirement to use a plugin, where we need to route the traffic on percentage basis. I'll give an example for better understanding. 

we have an URL https://xyz.com/ca/fr/index.html where ca is country (canada) and fr is french language. Now the traffic needs to routed 10% to https://xyz.com/ca/en/index.html and the remaining 90% to https://xyz.com/ca/fr/index.html. And whenever we're routing the traffic to https://xyz.com/ca/en/index.html we need to set a cookie. So for next call, if the cookie is there, it should directly go to https://xyz.com/ca/en/index.html else it should go via a 10:90 traffic split. What is the best possible way to achieve this ??

### Environment

- APISIX version (run `apisix version`): 3.8.0
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by nfrankel** [comment]
Interesting question. I don't think it's that hard, let me prepare a demo repo.

**Comment by nfrankel** [comment]
And that's it:

https://github.com/ajavageek/fixed-route-apisix/blob/master/apisix.yml

I'm in the process of writing a blog post about it if you need more details.

**Comment by nfrankel** [comment]
Hey @pavankumar-siripurapu 

I wrote a full-fledged [blog post](https://blog.frankel.ch/fixed-routes-apisix/) about your issue. Enjoy!

**Comment by pavankumar-siripurapu** [comment]
Thank you so much for your explanation and demonstration. @nfrankel, we have already tried this technique. The only reason we were hit was because APISIX must set the cookie during the 10% traffic split.


To put it simply, when the first request arrives, we must perform a 10:90 traffic split, and for the 10% of traffic, APISIX has to set a cookie so that subsequent requests from that browser/user will travel the same upstream without requiring a traffic split. In brief, we want to achieve session affinity.

**Comment by nfrankel** [comment]
In general, the upstreams sets the cookie and APISIX uses it later.

https://blog.frankel.ch/sticky-sessions-apache-apisix/
