### ISSUE TITLE
help request: prometheus collection indicator interface timeout

### ISSUE THREAD

**Issue by smileby** [apache/apisix#11274]
### How should we optimize or solve the time-consuming problem of APISIX data interface?

> Except for the following log occasionally, there are no other abnormalities.

```
2024/05/20 21:15:27 [warn] 31025#0: *11889570993 [lua] conf_server.lua:181: report_failure(): report failure, endpoint: xxx.xxx.xxx.xxx:2579 count: 1 while connecting to upstream, client: unix:, server: , request: "POST /v3/lease/grant HTTP/1.1", upstream: "http://xxx.xxx.xxx.xxx:2579/v3/lease/grant", host: "127.0.0.1"
```

### Environment

- APISIX version (run `apisix version`):  3.2.0
- Operating system (run `uname -a`):  Linux localhost.localdomain 3.10.0-327.el7.x86_64  SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
what is your apisix pod  resource request & limit config ?  is it enough ?

**Comment by smileby** [comment]
I used the default configuration. The shared_dict size used by prometheus-metrics is 10M. I saw on the monitoring that the peak usage of prometheus-metrics has reached 30m+, and the lowest is 21m. I don’t know if it is caused by insufficient space. My APISIX monitoring appears. Lots of volatility

![image](https://github.com/apache/apisix/assets/30252480/8bb72e90-0700-40bb-ad96-6d1e7f8326a5)

**Comment by smileby** [comment]
> When the number of connections is 2000, this problem does not exist. Can it be solved by increasing the capacity of shared_dict?

![image](https://github.com/apache/apisix/assets/30252480/69b842ca-75a2-4fb1-b4e8-37b1681bef89)

**Comment by smileby** [comment]
> > When the number of connections is 2000, this problem does not exist. Can it be solved by increasing the capacity of shared_dict?
> 
> ![image](https://private-user-images.githubusercontent.com/30252480/334254781-69b842ca-75a2-4fb1-b4e8-37b1681bef89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NjU4NDgsIm5iZiI6MTcxNjg2NTU0OCwicGF0aCI6Ii8zMDI1MjQ4MC8zMzQyNTQ3ODEtNjliODQyY2EtNzVhMi00ZmIxLWI0ZTgtMzdiMTY4MWJlZjg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDAzMDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0MmE1NDMzMTQ5NjA2YzBkZjgzNjA4ZDNhN2JlZWU3ZTFjNjFiZjBkMzFhN2Y1NjdiNzNjODQ1Zjg3NDFmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.esE3PVirBn4a9CSdDH3KzKZU7Pe2raJfnUUBWLmo01o)

![image](https://github.com/apache/apisix/assets/30252480/03d71c45-8f3c-4fcf-8901-64a9ab2c4a0c)

**Comment by smileby** [comment]
The picture below is my question.  At this time, the /apisix/prometheus/metrics interface is very time-consuming.


![image](https://github.com/apache/apisix/assets/30252480/95f95550-8b0a-4e52-8c0e-f43c5b3d858d)

**Comment by hanqingwu** [comment]
can you try add some log to  check what process cost most time ?

**Comment by smileby** [comment]
> hen I used prometheus to collect apisix monitoring data, I found that the /apisix/prometheus/metrics data interface occasionally took a long time, causing grafana monitoring data to be unstable. what is the reaso

My guess is that the amount of data is too large, resulting in time-consuming data transmission. The question I am more concerned about is why the monitoring fluctuates. Is it because the shared_dict elimination policy is triggered, resulting in data loss? Do you have any better suggestions for monitoring fluctuations, or can I try to expand shared_dict?

**Comment by hanqingwu** [comment]
yes, you can  try to expand shared_dict 
or  check whether  metrics loss because of  timeout

**Comment by smileby** [comment]
> yes, you can try to expand shared_dict or check whether metrics loss because of timeout

thank you for your reply. 

I want to know about APISIX's shared_dict configuration of prometheus' default configuration is 10mb. However, when collecting monitoring data, it will be 2-3 times the default configuration.
