### ISSUE TITLE
bug: install-dependencies.sh misses libyaml-dev on ubuntu22 dev container

### ISSUE THREAD

**Issue by adam-huganir** [apache/apisix#11290]
### Current Behavior

luarocks throws an error that it cannot find the libyaml library

### Expected Behavior

installing on this distribution succeeds without issues

### Steps to Reproduce

- create devcontainer using default ubuntu 22 in vscode
- run `make deps`

### Environment

Linux 827a58e833ef 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by adam-huganir** [comment]
PR created https://github.com/apache/apisix/pull/11291

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/11291
