### ISSUE TITLE
help request: handle_upstream(): failed to set upstream: no valid upstream node: failed to query the DNS server

### ISSUE THREAD

**Issue by winnie1228** [apache/apisix#11300]
### Description

deploy way: docker-compose
apisix/conf/config.yaml:
discovery:
  dns:
    servers:
      - "10.1.192.80:8600"
Consul is also deployed via docker on the same machine as apisix
error log:
> 2024/05/29 02:39:40 [error] 111#111: *230117 [lua] init.lua:545: handle_upstream(): failed to set upstream: no valid upstream node: failed to query the DNS server: dns lookup pool exceeded retries (1): timeout, client: 10.1.243.170, server: _, request: "GET /dns/test HTTP/1.1", host: "10.1.192.80:9080"
10.1.243.170 - - [29/May/2024:02:39:40 +0000] 10.1.192.80:9080 "GET /dns/test HTTP/1.1" 503 671 60.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" - - - "http://10.1.192.80:9080/test"

### Environment

- APISIX version (run `apisix version`):3.8.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by winnie1228** [comment]
I just found that running consul directly on the host machine can discover services through apisix DNS. Is there anything special that needs to be paid attention to when deploying consul in docker?

**Comment by nfrankel** [comment]
>Is there anything special that needs to be paid attention to when deploying consul in docker?

I'm afraid you need to ask the question to the Consul project itself

**Comment by kayx23** [comment]
See if this doc helps: https://docs.api7.ai/apisix/how-to-guide/service-discovery/consul-integration

Both Apisix and consul are started in Docker in that doc.
