### ISSUE TITLE
add apisix version when API responses

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#1132]
### Issue description
We could add the apisix version when API responses, so that the API caller could have a proper action.

**Comment by agile6v** [comment]
Could you provide specific cases? Thanks.

**Comment by totemofwolf** [comment]
We alway choose hide those `sensitive headers` by hand. I think we can provide such capabilities but turn it off by default. ;-)

**Comment by juzhiyuan** [comment]
Related issue https://github.com/apache/incubator-apisix-dashboard/issues/139

@totemofwolf The APISIX version is not sensitive to clients in my opinion, the Dashboard should know whether it's compatible with current APISIX.

**Comment by juzhiyuan** [comment]
@moonming How about this feature?

**Comment by spacewander** [comment]
Now the version can be detected via the Server header. Solved.
