### ISSUE TITLE
apisix will retry the post method?

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#11359]
### Description

use the apisix default value,if the post request return 502,then apisix will retry the next upstream server and return 200,how to chang this?and why use settings?

### Environment

- APISIX version (run `apisix version`):2.15.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Do you mean you want APISIX to return 5xx instead of trying the next upstream node?

**Comment by kellyseeme** [comment]
> Do you mean you want APISIX to return 5xx instead of trying the next upstream node?

yes，which place i can cancle this settings？

**Comment by kellyseeme** [comment]
> I don't think this is possible (cc @shreemaan-abhishek ). Can you provide your use case and explain why you would like to implement this?

Post requests are not idempotent and retrying is risky.

**Comment by kellyseeme** [comment]
> I don't think this is possible (cc @shreemaan-abhishek ). Can you provide your use case and explain why you would like to implement this?

Which scenarios and request methods are retried by default? Can you list this?

**Comment by ShenFeng312** [comment]
I think this can help you .But you may  need edit nginx.conf after `apisix init` if config.yml not support this
https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream
