### ISSUE TITLE
help request: keeping redis connection alive

### ISSUE THREAD

**Issue by mayeter** [apache/apisix#11372]
### Description

Hello, I've been working on the limit-req plugin with redis and I realized apisix creates a new connection for every single request, so I think maybe I can alter this behaviour and if I can keep a single connection, it could perform faster after getting rid of three-way handshake. 

Maybe you tried it already and it is a bad idea but I really need to get higher numbers 🙏 

I've played a little in apisix/plugins/limit-req/limit-req-redis.lua 

```
function _M.new(plugin_name, conf, rate, burst)
    local red, err = redis.new(conf)
    if not red then
        return red, err
    end
    local self = {
        red = red,
        conf = conf,
        plugin_name = plugin_name,
        burst = burst * 1000,
        rate = rate * 1000,
    }

    return setmetatable(self, mt)
end


function _M.incoming(self, key, commit)
    local conf = self.conf
    local red = self.red
    if not red then
        return red, err
    end

    return util.incoming(self, red, key, commit)
end
```

So it creates a connection once and keeps it under "self". My problem here is that it somehow terminates this connection after first request and the rest throws this error:

`2024/06/25 18:29:23 [error] 242482#242482: *3933 [lua] limit-req.lua:171: phase_func(): failed to limit req: closed, client: x.x.x.x, server: _, request: "GET /test1/x HTTP/2.0", host: "xyz.com"`

I failed to find the trigger that closes connection. Could you guide me please? 

### Environment

- APISIX version (run `apisix version`): 3.9
- Operating system (run `uname -a`): Ubuntu 22.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hanqingwu** [comment]
![image](https://github.com/apache/apisix/assets/7521141/005a1cf0-de4a-4824-b12d-26962c69388a)
apisix/utils/redis.lua

**Comment by hanqingwu** [comment]
need add red:set_keepalive(...)

**Comment by mayeter** [comment]
Hello, thank you for support. I managed to get pooled my connections according to the documentation [here](https://github.com/openresty/lua-resty-redis?tab=readme-ov-file#set_keepalive) however it still closes the connection and puts it in pool, then expect me to recall red:connect() function before using it, so it does tcp handshake anyway. I guess its the way resty library is written, so we could close this issue if you don't have any suggestion for me 🙏

**Comment by hanqingwu** [comment]
like this test .
https://github.com/openresty/lua-resty-redis/issues/70
I think reuse connect is works,  use red:connect after red:set_keepalive
