### ISSUE TITLE
docs: Join the slack community in a non-Apache mailbox for even better help

### ISSUE THREAD

**Issue by SquirHong** [apache/apisix#11407]
### Current State

can only use your apache mailbox to enter slack

### Desired State

Any email will do, and like pulsar, the pulsar community can join slack through any email

**Comment by SquirHong** [comment]
<img width="510" alt="image" src="https://github.com/user-attachments/assets/ab6a89bf-9164-4f84-baad-5afae6fe2a39">

**Comment by kayx23** [comment]
> can only use your apache mailbox to enter slack

...or by invitation (using your email). There is also a general invitation link but the apache server invitation expires every 30 days. For now you can use this link to join: https://join.slack.com/t/the-asf/shared_invite/zt-2n1cpm80z-iCvAV~GVMGd0O7OUtNgqug

Hope this helps.
