### ISSUE TITLE
help request: limit-count plugin how to support etcd as the counters  storage

### ISSUE THREAD

**Issue by cnn911** [apache/apisix#11428]
### Description

Hi,we're using the limit-count plugin, our apisix deploy in 3 nodes, but we don't want limit-count plugin dependent redis,  we guess why not etcd to store the counters, now it is not supportive actually. so what should we do to support it?

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> why not etcd to store the counters

Etcd isn't the right db for this purpose.

**Comment by shreemaan-abhishek** [comment]
Please discuss your use case on the mailing list if you would like to support the development of this feature, thanks.

**Comment by Ajeetprajapati315** [comment]
- ![Strategy-and-Market-Outlook-May-2019.pdf](https://github.com/user-attachments/files/16469840/Strategy-and-Market-Outlook-May-2019.pdf)
