### ISSUE TITLE
help request: How to change read timeout?

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#11433]
### Description

Is it possible to configure read timout?
When I make a request to one service I receive an error:

`2024/07/24 17:31:12 [error] 1528887#1528887: *89915380 upstream prematurely closed connection while reading response header from upstream, client: 10.1x.xx.xx, server: _, request: "GET /v1/status/providers HTTP/1.1", upstream: "https://xx.xxx.xxx.xx:443/v1/status/providers", host: "xxxx:80"`

I have tried to add to config.yaml:

```
nginx_config:                     
  http:
    proxy_read_timeout: 300s
```
But it didn't work.

What should I do?

### Environment

- APISIX version (run `apisix version`):3.5
- Operating system (run `uname -a`):Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
similar issue: https://github.com/apache/apisix/issues/11399

**Comment by PlasticJonbenetDoll** [comment]
> similar issue: #11399

There is no answer

**Comment by kayx23** [comment]
Yep sorry I was grouping the issues.

Perhaps try the `timeout` configuration in upstreams:

```
"timeout": {
  "connect": 10,
  "send": 10,
  "read": 30
}
```

reference: https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-3
