### ISSUE TITLE
Feature: Open API specification for Admin API 

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1146]
### Issue description
Is there an Open API (Swagger) specification to admin API? If so it can be easily used to define and maintain APIs, generate [API docs](https://github.com/slatedocs/slate) and import in API testing tools like the postman.

**Comment by membphis** [comment]
We do not have it now. Any good suggestions?

**Comment by sshniro** [comment]
Okay, shall I start creating an Open API for Admin API? After the YAML file is generated, we can use:
1. [Redoc](https://github.com/Redocly/redoc) This is interactive, we can connect the demo sandbox API SIX environment for this.
2. [Slate](https://github.com/slatedocs/slate)

Both can be used to show example invocations and autogenerate code for multiple languages.

**Comment by membphis** [comment]
I'm not very good at this, we can listen to other people's opinions. 

Their licenses are friendly, it's very nice.

**Comment by moonming** [comment]
I tried both, I prefer the Reddoc. @sshniro What do you think?

**Comment by sshniro** [comment]
@moonming yea I agree, as Admin API has comparatively less APIs Redoc will be good. Slate will be ideal if there are a lot of high-level documents to be written (API Orchestration examples).

**Comment by moonming** [comment]
@sshniro do you want to add Redoc for Apache APISIX?

**Comment by sshniro** [comment]
Yes @moonming I would like to initially add the open API specs, but currently working with the HTTP logger. After that, I can start working on this issue.

**Comment by membphis** [comment]
@sshniro can we close this issue now?

**Comment by sshniro** [comment]
I did not have time to check on this feature, will try this after merging the docs with the website.

**Comment by spacewander** [comment]
Since we plan to use manager API to replace admin API, there is no need to investigate into the old one.
