### ISSUE TITLE
bug:  [lua] init.lua:551: handle_upstream(): failed to set upstream: discovery nacos is uninitialized,

### ISSUE THREAD

**Issue by luyi1994** [apache/apisix#11468]
### Current Behavior

  nacos:
    host:
      - "http://127.0.0.1:8848"
    prefix: "/nac件 bug:  [lua] init.lua:551: handle_upstream(): failed to set upstream: discovery nacos is uninitialized, 

### Expected Behavior

Can load correctly. nacos services are available

### Error Logs

eroor1: handle_upstream(): failed to set upstream: discovery nacos is uninitialized,

### Steps to Reproduce

docker runs apisix 
![image](https://github.com/user-attachments/assets/1f3feb14-fb2e-4f87-bfc6-876fa9db0c09)

### Environment

![image](https://github.com/user-attachments/assets/b891f6f5-04dd-4eeb-9d84-acfac07639a6)

**Comment by zhoujiexiong** [comment]
It seems that `dicovery/nacos` does not config correctly.

Please ref. the following doc and confirm.
https://apisix.apache.org/docs/apisix/3.6/discovery/nacos/


<img width="392" alt="image" src="https://github.com/user-attachments/assets/cc34e5c3-07a1-44ed-9334-44aaaa1ab896">

**Comment by zhoujiexiong** [comment]
#11528
