### ISSUE TITLE
docs:  forward_auth插件中文文档错误

### ISSUE THREAD

**Issue by Jazzylol** [apache/apisix#11461]
### Current State

https://apisix.apache.org/zh/docs/apisix/plugins/forward-auth/

![CleanShot 2024-08-01 at 18 29 31](https://github.com/user-attachments/assets/b9d81836-83ec-4cc2-aef2-9b9dc5735b23)

status_on_error  type   boolean 

### Desired State

status_on_error  的type应该是 integer， 英文文档是正确的

**Comment by moonming** [comment]
@Jazzylol good catch, welcome PR to fix it
