### ISSUE TITLE
help request: 请问dashboard 这个项目还在维护吗？

### ISSUE THREAD

**Issue by oxcz** [apache/apisix#11473]
### Description

看好久好像没有新的提交了，目前apisix已经3.90了，那边还停留在3.0
已经部分项目把这个移出出去了，但是又在某些地方宣传自己有一个完整的后台。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yzeng25** [comment]
Could you close this issue as you've open an issue with the same question in the dashboard repo [#2960](https://github.com/apache/apisix-dashboard/issues/2960)? This issue should go into the dashboard repo rather than here.
