### ISSUE TITLE
docs: wrong plugin name occurs in basic-auth doc

### ISSUE THREAD

**Issue by yzeng25** [apache/apisix#11479]
### Current State

The plugin name was modified to `jwt-auth` in #6824 by mistake.

- https://github.com/apache/apisix/commit/b2f3273b6accec8a1f163d16df246fe36cb8a907#diff-09d972764191214769f413a3a5266e04ea8dd93ad2e80176de0615452a929b14
- https://apisix.apache.org/docs/apisix/plugins/basic-auth/#delete-plugin

![image](https://github.com/user-attachments/assets/54d8894e-33f3-4433-a34b-52e0aa287dff)

### Desired State

Change `jwt-auth` to `basic-auth` should fix this issue easily.

https://github.com/apache/apisix/blob/e74674649fde29cc59ae70be1f8a6f2266b3ba40/docs/en/latest/plugins/basic-auth.md?plain=1#L139

**Comment by yzeng25** [comment]
[@yyd](https://github.com/yyd0) do you want to work on this?

**Comment by opencmit2** [comment]
@yzeng25 Please Assign it to me.
