### ISSUE TITLE
bug: Strings in luajit are infinitely bloated, even if they are not rereferenced in the lua vm

### ISSUE THREAD

**Issue by fairyqb** [apache/apisix#11519]
### Current Behavior

Minimal example code

resty example.lua

`
	local function get_memory_usage()  
	    local b = collectgarbage("count")  * 1024
	    return b  
	end  

	local my_table = {}  
	for i = 1, 10000000 do  
	    my_table[i] =  string.rep("A" , 256) .. i  

	end

	my_table = nil
	print("start gc:", "mem:",get_memory_usage())
	collectgarbage("collect") 
	print("end gc:", "mem:",get_memory_usage())
	print("sleep 10m")

	print("done")
	ngx.sleep(60*10*6)

`

Strings in luajit are infinitely bloated, even if they are not rereferenced in the lua vm. As a result, the memory resources of the nginx process RES are increasing to become larger and larger.

### Expected Behavior

why?

### Error Logs

none

### Steps to Reproduce

none

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
aspsix all version

**Comment by Revolyssup** [comment]
@fairyqb This is not an apisix related bug but rather limitations/issues related with luajit itself. I dont think this can be fixed at the APISIX end. // @shreemaan-abhishek

**Comment by fairyqb** [comment]
> @fairyqb This is not an apisix related bug but rather limitations/issues related with luajit itself. I dont think this can be fixed at the APISIX end. // @shreemaan-abhishek

Is this a bug in openresty/apisix, or a bug in luajit, and this issue is not solved? Worrying about applying APISIX to production?

**Comment by Revolyssup** [comment]
I think you can ask this query here https://github.com/openresty/openresty

**Comment by membphis** [comment]
you can research the Luajit gc, here is another example which can show more information than yours:

result:
```shell
case 1:
Memory usage after garbage collection: 4319.6220703125 KB
Memory usage after garbage collection: 1247.5986328125 KB
Memory usage after garbage collection: 479.5361328125 KB
Memory usage after garbage collection: 287.5361328125 KB
```

source code:
```lua
ngx.say("\ncase 1:")
local my_table = {}
for i = 1, 1000 * 1000 do  
    my_table[i] =  string.rep("A" , 256) .. i
end
my_table = nil

for i = 1, 100, 1 do
    collectgarbage("collect")

    local memory_usage = collectgarbage("count")
    print("Memory usage after garbage collection: " .. memory_usage .. " KB")

    if memory_usage < 300 then
        break
    end

    ngx.sleep(1)
end
