### ISSUE TITLE
help request: what is default route priority rule ?

### ISSUE THREAD

**Issue by darkSheep404** [apache/apisix#11527]
### Description
dear apisix team
for exmaple
i have two ruote cover same url
01. /api/user/*
02. /api/user/test

will
/api/user/test go to 01 or 02 ?
/api/user/test/new will go to 01 or 02?
Is there any documentation about this ?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by darkSheep404** [comment]
and if 
01./api/user/*
- host : test.com

02. /api/user/test


call /api/user/test via test.com will go to 01 or 02 ?

**Comment by wklken** [comment]
you can check the doc here:
https://apisix.apache.org/docs/apisix/router-radixtree/

**Comment by darkSheep404** [comment]
> and if 01
> 
> ```
> ./api/user/*
> - host : test.com
> ```
> 
> 02 . ` /api/user/test`
> 
> call /api/user/test via test.com will go to 01 or 02 ?

per test, will go to 01
no config on host will not limit request host
but seems mismatch route due to one less condition

**Comment by darkSheep404** [comment]
> you can check the doc here: https://apisix.apache.org/docs/apisix/router-radixtree/↳

many thanks, that's what i'm looking for
