### ISSUE TITLE
feat: Rcommend to add the curl to image apache/apisix:version

### ISSUE THREAD

**Issue by geekgao** [apache/apisix#11531]
### Description

 To better test or use Apisix's, it is recommended to add the curl directive to the Docker image:
 **apache/apisix:3.9.0-debian**

So, Users could use curl add routes to APISIX in container. Like document example, Example: https://apisix.apache.org/zh/blog/2023/09/08/apisix-integrates-with-coraza/#%E9%85%8D%E7%BD%AE--anything-%E8%B7%AF%E7%94%B1%E9%9B%86%E6%88%90-coraza-waf-%E8%A7%84%E5%88%99

btw. I found that there is curl command in image: apache/apisix-dashboard

**Comment by kayx23** [comment]
I vaguely remember it was purposely removed for security reasons. @shreemaan-abhishek @juzhiyuan remember anything?

**Comment by shreemaan-abhishek** [comment]
@kayx23 yes, you are right. @geekgao we cannot add it back to the image, plus, it's not a requirement of critical importance either.
