### ISSUE TITLE
help request: Add APISIX into Arm64 Eco-System query system.

### ISSUE THREAD

**Issue by eric-yq** [apache/apisix#11594]
### Description

Hello team, 

APISIX can support AWS Graviton instances(Arm64, AArch64), can you add APISIX into [https://www.arm.com/developer-hub/ecosystem-dashboard](https://www.arm.com/developer-hub/ecosystem-dashboard )?

So, all the people can find it is supported in Arm64 eco-system.

Thanks.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
yes APISIX can run on arm64 architecture.

**Comment by eric-yq** [comment]
> yes APISIX can run on arm64 architecture.

yes I know it, is someone can add this information into https://www.arm.com/developer-hub/ecosystem-dashboard?

Thanks.
