### ISSUE TITLE
Proposal: multiple certificates deployment for a single domain

### ISSUE THREAD

**Issue by tokers** [apache/apisix#1159]
## Background

As is known to all, ECC (Elliptic Curve Cryptography)  certificate has several advantages than RSA certificate, like smaller key size. The speed of SSL handshake on the server side will be better if we can use the ECC certificate.

Nevertheless, some browsers may not recognize the ECC certificate, so if someone migrated his/her certificate from RSA to ECC, compatibility broken might occur.

## Solution

Let's try to deploy multiple certificates for a single domain, depending on the cipher suites that client sent, apisix can select and send the most appropriate certificates.

Technically, OpenSSL's related APIs like `SSL_use_certificate`, `SSL_use_PrivateKey`, can be called duplicately for a single SSL session, the certificate selection will be done under the hood.

## References

* https://www.leaderssl.com/articles/345-what-is-ecc-and-why-you-should-use-it
* https://imququ.com/post/ecc-certificate.html

**Comment by moonming** [comment]
sounds great. We need also update `ssl_ciphers` in nginx.conf too.

@tokers welcome PR:)

**Comment by tokers** [comment]
@moonming  I will try. Since i'm not familiar the internal of APISIX, it may take a long while. Anyway, i will synchronize the progress here.

**Comment by moonming** [comment]
@tokers If you have any questions, feel free to discuss with us, looking forward for your PR

**Comment by membphis** [comment]
@tokers any news?

**Comment by tokers** [comment]
I'm so sorry that i almost forgot this thing... 😂, i will start to do it once i have enough time.

**Comment by spacewander** [comment]
Look like this can be closed now?

**Comment by tokers** [comment]
@spacewander Yeah, the corresponding PR was merged.
