### ISSUE TITLE
bug: Using auth with body transformer remove body

### ISSUE THREAD

**Issue by grencik** [apache/apisix#11609]
### Current Behavior

Referencing to #11608 I found out when I use key-auth plugin together with body-transformer it will empty (or erase or I dont know) body and then it will not fill variables in template in body-transformer. So when key-auth fails it crash and when it not fail it will send not filled template.

### Expected Behavior

Expected to protect route with plugin and then transform body.

### Steps to Reproduce

1. Create route with plugins key-auth and body-transformer
2. Make request without failing auth

### Environment

- APISIX version (run `apisix version`): 3.10.0

**Comment by shreemaan-abhishek** [comment]
please update your findings in #11608
