### ISSUE TITLE
help request: WebSocket Connections Persist with Old Upstream After Route Update and Do Not Disconnect When Route is Disabled

### ISSUE THREAD

**Issue by qingyanbaby** [apache/apisix#11619]
### Description

I am experiencing an issue while using APISIX as a proxy for WebSocket connections. After updating the route to use a different upstream server, existing WebSocket connections continue to connect to the old upstream server instead of the newly configured one. Additionally, when I disable the route, the existing WebSocket connections remain active and do not disconnect as expected.

### Environment

- APISIX version (run `apisix version`): 3.9.1
- Operating system (run `uname -a`):  Linux 4fdb606a4dfe 5.4.0-193-generic #213-Ubuntu SMP Fri Aug 2 19:14:16 UTC 2024 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.25.3.1

**Comment by shreemaan-abhishek** [comment]
please share the steps to repro.

**Comment by zhoujiexiong** [comment]
May be you should restart backend service or add extra interaction to tell frontend to reconnect after updating route.
