### ISSUE TITLE
help request: How to use multiple upstreams in single route?

### ISSUE THREAD

**Issue by PlasticJonbenetDoll** [apache/apisix#11624]
### Description

Hello.
I wonder is it possible to have multiple Upstreams in single Route? And select needed Upstream based on Header in request?

### Environment

- APISIX version (run `apisix version`): 3.6
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
You can use chash as the upstream "type" with `hash_on` headers. Is this what you were looking for?
https://docs.api7.ai/apisix/reference/admin-api#tag/Upstream/paths/~1apisix~1admin~1upstreams/post

**Comment by zhoujiexiong** [comment]
Or the "traffic-split" plugin for the `multiple upstreams in single route` scenario?

https://apisix.apache.org/docs/apisix/plugins/traffic-split/

**Comment by PlasticJonbenetDoll** [comment]
With 'traffic-split' plugin is it possible to select Upstream based on link?
For example if user access /foo/bar the go to Upstream 1, and if user access /my/home go to Upstream 2?

**Comment by PlasticJonbenetDoll** [comment]
I guess I could try to use serverless plugin
