### ISSUE TITLE
help request: proxy cache zone

### ISSUE THREAD

**Issue by konglua89** [apache/apisix#11698]
### Description

Hey folks
we are migrating from nginx to apisix ... we got about thousand domain names and in nginx we got cache zone directive for every domain and conf files,,, so every domain got split cache zone . but in apisix we must define multiple cache zone in config.yaml file and restart apisix service... is there a way to define cache zone in apisix apis? 
or  if  all of my domains have a single cache zone makes bad performance in my apisix server?
best regards

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
>  is there a way to define cache zone in apisix apis?

afaik defining cache zones at runtime is not supported
