### ISSUE TITLE
bug: The highest version can be install is 3.9.1 when install apisix via RPM repository,but the latest version is 3.11

### ISSUE THREAD

**Issue by hwddong** [apache/apisix#11699]
### Current Behavior

The highest version can be install is 3.9.1 when install apisix via RPM repository,but the latest version is 3.11

![Snipaste_2024-10-31_18-24-34](https://github.com/user-attachments/assets/12c1cb06-a0c3-406f-8c14-8c3faf50558d)

### Steps to Reproduce

1.yum --showduplicates list apisix

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
CentOS Linux 7 reached end-of-life (EOL) on June 30, 2024. Therefore, Apache APISIX does not support CentOS and RPM in the release package and GitHub CI.
