### ISSUE TITLE
help request: When attempting to access the JWT authentication sign endpoint exposed through the public API, a 404 Not Found error is returned.

### ISSUE THREAD

**Issue by Fsystem** [apache/apisix#11733]
### Description

When attempting to access the JWT authentication sign endpoint exposed through the public API, a 404 Not Found error is returned.and public-api is enabled both in apisix config.yaml and apisix-dashboard config.yaml
![4673E913-4528-4469-A07E-5FB1A5751F9C](https://github.com/user-attachments/assets/a2c4cff0-d6b8-4464-86db-078d354ccdb1)

### Environment

- APISIX version (run `apisix version`):apache/apisix:3.11.0-debian
- Operating system (run `uname -a`):Debian 6.1.69-1 (2023-12-30) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):bitnami/etcd:3.5.16 
- APISIX Dashboard version, if relevant:apache/apisix-dashboard:3.0.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mikyll** [comment]
That's because the JWT signing endpoint was **removed** in **APISIX v3.11.0**.

You can see that in [CHANGELOG#3.11.0](https://github.com/apache/apisix/blob/release/3.11/CHANGELOG.md#3110)

And in commits history, with [commit 1773655](https://github.com/apache/apisix/commit/1773655f0d39db5a49c7ab04ee4cf70f6b6e2368#diff-3f3ee89c49b5146c08f997085bb1649703063edde15dcee24312bd98288241efL427-L435)

**Comment by Fsystem** [comment]
> That's because the JWT signing endpoint was **removed** in **APISIX v3.11.0**.
> 
> You can read the change in [CHANGELOG#3.11.0](https://github.com/apache/apisix/blob/release/3.11/CHANGELOG.md#3110), and in commits history, with [commit 1773655](https://github.com/apache/apisix/commit/1773655f0d39db5a49c7ab04ee4cf70f6b6e2368#diff-3f3ee89c49b5146c08f997085bb1649703063edde15dcee24312bd98288241efL427-L435)

Thank you, I understand now. Are there other ways to obtain a JWT signature

**Comment by mikyll** [comment]
> Are there other ways to obtain a JWT signature

@Fsystem as of now, I don't think APISIX provide any _out-of-the-box_. However, you can always write a custom plugin, e.g. `jwt-sign`, and expose a public api the same way that `jwt-auth` did (you can copy the code from the commit I provided above).

Check the docs for further info: [APISIX Plugin Development | register public API](https://apisix.apache.org/docs/apisix/plugin-develop/#register-public-api)

**Comment by Fsystem** [comment]
@mikyll Thanks, I will give it a try.
