### ISSUE TITLE
bug: Performance on container is no good, just 5.6k QPS

### ISSUE THREAD

**Issue by Mararesliu** [apache/apisix#11843]
### Current Behavior

I run apisix on one pod with two container, limit 2 cpu,  benchmark from apisix performance just 5.6k QPS, but benchmark to upstream directly is ok(26k). The problem is upstream latency too high, I see on the dashbord metrics
![224CAB4B-0B6C-438b-B411-27C95268A6D3](https://github.com/user-attachments/assets/ee935956-8350-4fe7-903e-b69d71555c6a)
I use Envoy ,it can got more than 8k QPS.

### Expected Behavior

How can in increase upstream performance via apisix?

### Steps to Reproduce

1、RUN a pod with apisix and nginx demo.
2、setting root route to nginx 
3、benchmark to apisix like 
./wrk  -t600 -c5000 -d120s -H "Host: nginx" http://172.17.0.2:9080

### Environment

- APISIX version (run `apisix version`): 3.11
- Operating system (run `uname -a`): redhat 8.11
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
For API Gateway performance testing, please ensure that the upstream is not a performance bottleneck, otherwise the performance cannot be fully released. The ideal test scenario is that the CPU of the API Gateway data plane is 100% used, refer to https://docs.api7.ai/apisix/production/performance/performance-testing

**Comment by Mararesliu** [comment]
It's because of i enable jager plugin.
