### ISSUE TITLE
feature: Support for OAuth User Managed Access Protocol(UMA) for Authorization 

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1188]
### Issue description
Does APISIX support UMA protocol to allows access to resources/upstreams? I would like to use the UMA protocol for authorization with the RedHat Keycloack Identity server.

![image](https://user-images.githubusercontent.com/13045528/75759895-981ee480-5d36-11ea-88f9-50c0582c289b.png)

**Comment by chnliyong** [comment]
Hi @sshniro ,

As I'm a little bit familiar with **Keycloak**, I've read the Keycloak [uma document](https://www.keycloak.org/docs/latest/authorization_services/index.html#_service_user_managed_access) and [uma 2.0](https://docs.kantarainitiative.org/uma/wg/oauth-uma-federated-authz-2.0-09.html#abstract-flow-fig).

Currently I'm not very clear about what **APISIX** should do in this flow? Is below description right for your scenario?

1. we access the resource provided by *Resource Server* through *APISIX*, and the response from the *Resource Server* is `401 Unauthorized` with `as_uri` and `ticket`
2. *APISIX* redirect to *Keycloak* then let the user interact(Authenticate) with *Keycloak* to get `access_token`
3. *APISIX* use the `as_uri`, `ticket`, `access_token` got at previous 2 steps to request *Keycloak* to get the **uma ticket**.

If above is your scenario, how the *uma ticket* would stored? Do we store it in cookie? Do you have any suggestion? And if you know some similar products supporting this, let me know. Thanks!

**Comment by sshniro** [comment]
Yes @chnliyong the workflow is correct. I would like to mediate the token calls via the API Gateway itself. And yes saving it in a cookie would be easier. Unfortunately, I did not find the token mediation support in similar products.
