### ISSUE TITLE
feature: support multiple ports like stream listen in http and https listen port.

### ISSUE THREAD

**Issue by wwd5613** [apache/apisix#1195]

**Comment by membphis** [comment]
Very good advice

**Comment by moonming** [comment]
@wwd5613 welcome PR

**Comment by soulsoul** [comment]
@wwd5613  can u show some example？

**Comment by soulsoul** [comment]
that means:  you want apisix can support multiple ports to start.  now apisix just can start up on one port by the  config parameter "node_listen ".  just for the configuration in nginx
server {
     listen  9080  9081  9082；
     listen  9443  ssl  https2;
}
is it right ?
@wwd5613

**Comment by tzssangglass** [comment]
I want to solve this issues. This is my first time to participate in apisix.
Can I choose @membphis  as a mentor.
The deadline I gave is October 18.

**Comment by membphis** [comment]
@tzssangglass no problem. I have assigned this issue to you. If you have any questions, please feel free to talk to me.

**Comment by tzssangglass** [comment]
> @tzssangglass no problem. I have assigned this issue to you. If you have any questions, please feel free to talk to me.

ok

**Comment by tzssangglass** [comment]
now i modified config.yaml as follows
```
apisix:
  node_listen:
    - 9080
    - 9081
    - 9082
```

and modified the ngx_tpl related places, as follows
```
        {% for _, port in ipairs(node_listen) do %}
        listen {* port *} {% if enable_reuseport then %} reuseport {% end %};
        {% end %}
        ……
        {% for _, port in ipairs(node_listen) do %}
        listen [::]:{* port *} {% if enable_reuseport then %} reuseport {% end %};
        {% end %}
```

in this way config.yaml can be parsed as the following configuration in nginx.conf
```
        listen 9080 reuseport;
        listen 9081 reuseport;
        listen 9082 reuseport;
        ……
        listen [::]:9080 reuseport;
        listen [::]:9081 reuseport;
        listen [::]:9082 reuseport;
```


now my question is
- Is it compatible with the original configuration of node_listen and separated by commas
- Expansion 9080 and 9443 port

**Comment by membphis** [comment]
support multiple listening ports, there are three styles:

> style 1

```yaml
apisix:
  node_listen:
    - 9080
    - 9081
    - 9082
```

> style 2

```yaml
apisix:
  node_listen: 9080 9081 9082
```

> style 3

```yaml
apisix:
  node_listen: 9080, 9081, 9082
```

Which is the one you would like? 
I vote to `2` and `3`.

**Comment by tzssangglass** [comment]
I vote to `3`

- downward compatibility
- reduced ambiguity

**Comment by moonming** [comment]
Apache APISIX is now using style 1, I think it should be consistent, this is also a more common way in yaml

**Comment by tzssangglass** [comment]
> Apache APISIX is now using style 1, I think it should be consistent, this is also a more common way in yaml

In master branch，`node_listen` is not  using style 1，https://github.com/apache/apisix/blob/b8e4b8589d3b62a1c30fe726963a9dca7a6ff3f6/conf/config-default.yaml#L23

but `stream_proxy`  is using style 1，
https://github.com/apache/apisix/blob/b8e4b8589d3b62a1c30fe726963a9dca7a6ff3f6/conf/config-default.yaml#L90

so without considering backward compatibility，`node_listen` change to style 1 is the most suitable.

**Comment by tzssangglass** [comment]
Or take a more complicated method, compatible with the original configuration method. If you need to support multiple ports like stream listen in http and https listen port，modify config.yaml like style 1.

**Comment by membphis** [comment]
> Apache APISIX is now using style 1,

APISIX is using style 2 or 3 (only one port) currently.

**Comment by tzssangglass** [comment]
I think the compatibility design is reasonable, I plan to do this.
If the user want to support multiple listen, they need to modify config.yaml like style 1
