### ISSUE TITLE
question: why not merge parameters of the same type in route management

### ISSUE THREAD

**Issue by xiangxiren** [apache/apisix#1207]
in routing management,why not merge these same types of parameters into one.Isn't this more concise and clear?
![image](https://user-images.githubusercontent.com/12774053/75953311-0e187c80-5eec-11ea-8093-4963aabe1962.png)

Also, why store upstream configuration data in route data structure?
If the routing maintenance data contains upstream configuration data, why not add it to the upstream data, and then use upstream_id to associate?

**Comment by spacewander** [comment]
To maintain the backward compatibility.
