### ISSUE TITLE
bug: the health check report error

### ISSUE THREAD

**Issue by wanzhenhan** [apache/apisix#1208]
### Issue description
failed to run balancer_by_lua*: /usr/share/lua/5.1/apisix/lua/apisix/balancer.lua:259: attempt to concatenate field 'status_ver' (a nil value)
 the health check config:
curl http://127.0.0.1:9080/apisix/admin/routes/500 -X PUT -d '
{
    "uri": "/",
    "methods": ["GET","PUT","POST","PATCH"],
    "plugins": {
        
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "10.82.4.112:25003": 1,
            "10.82.4.112:25004": 1
        },
        "checks": {
            "active":{
                "http_path": "/",
                "host": "test.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                },
                "req_headers": ["User-Agent: curl/7.29.0"]
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [500],
                    "http_failures": 3,
                    "tcp_failures": 3
                }
            }
        }
    }
}'

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
when i exec  "curl http://xx.xx.xx.xx:443/",it report

**Comment by membphis** [comment]
do you still need any help?  @wanzhenhan 

if yes, please tell us which version you are using.
