### ISSUE TITLE
Helper message when starting APISIX

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1214]
Currently, the APISIX start does not give any helpful indication.

![image](https://user-images.githubusercontent.com/13045528/76139912-7767cf00-6055-11ea-987d-22b37def17f7.png)

It would be helpful if we can see a message like this if APISIX started successfully.

```
APISIX started successfully and the Admin API is listening on port xxxx
```

**Comment by agile6v** [comment]
Hi @sshniro

I agree with you. But Nginx does not provide any useful hints. So if we want to achieve this,  it may need to be encapsulated to parse Nginx configuration and then check the startup status.

Thanks.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
