### ISSUE TITLE
use GitHub Actions as CI for Apache APISIX

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1253]
GitHub Actions provides more concurrency and provides ease for excessive run time and queue
the length we have been experiencing with Travis CI so far.

We can make Apache APISIX able to run on GitHub Actions, but still kept the
Travis CI files around so that we could use both at the same time during
the transitional period.  Eventually, Travis CI support will be removed.

**Comment by liuhengloveyou** [comment]
Does it need to close now?
