### ISSUE TITLE
Support JWT scopes to allow or reject requests in OAuth2 plugin

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1272]
### Issue description
The JWT contains the scopes available for a user via the scope attribute. Scope represents the capabilities the token has such as `read` or `delete`. It would be good if we can define a required set of scopes and allow or reject the request based on the required scope.

**Comment by membphis** [comment]
can you provide an example?

**Comment by sshniro** [comment]
The following is the scenario I have in mind.

The getProducts endpoint should be accessible via a token which has the read scope.
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uri": "/getProducts",
  "plugins": {
    "proxy-rewrite": {
      "scheme": "https"
    },
    "openid-connect": {
      "client_id": "api_six_client_id",
      "client_secret": "client_secret_code",
      "discovery": "full_URL_of_the_discovery_endpoint",
      "required_scope": "read_scope",
}
  }
}'
```

And the deleteProducts endpoint should be accessible via the token with a deletescope.
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uri": "/deleteProducts",
  "plugins": {
    "proxy-rewrite": {
      "scheme": "https"
    },
    "openid-connect": {
      "client_id": "api_six_client_id",
      "client_secret": "client_secret_code",
      "discovery": "full_URL_of_the_discovery_endpoint",
      "required_scope": "delete_scope",
}
  }
}'
```
This is how the core OpenID Library is suggesting to handle this scenario.

![image](https://user-images.githubusercontent.com/13045528/76847997-3e90dc80-6843-11ea-9781-baf711176a79.png)
https://github.com/zmartzone/lua-resty-openidc#sample-configuration-for-oauth-20-jwt-token-validation

**Comment by membphis** [comment]
@moonming you can take a look

**Comment by sshniro** [comment]
@moonming any thoughts on this enhancement?

**Comment by moonming** [comment]
`required_scope` should be `scope`?
others look good to me.

**Comment by tamasorban** [comment]
@spacewander, I believe there's still a need for this ticket. The openid-connect plugin introduced a scope property for a different purpose. The scope property described in the ticket would allow us to accept/reject the request.

**Comment by csotiriou** [comment]
> @spacewander, I believe there's still a need for this ticket. The openid-connect plugin introduced a scope property for a different purpose. The scope property described in the ticket would allow us to accept/reject the request.

I second that. I believe that this is indeed a very useful addition, and should definitely be reconsidered.

**Comment by csotiriou** [comment]
I believe that this need is partially or completely fulfilled by this fix: https://github.com/apache/apisix/pull/10493

**Comment by kayx23** [comment]
> I believe that this need is partially or completely fulfilled by this fix: https://github.com/apache/apisix/pull/10493

cc: @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
considered resolved
