### ISSUE TITLE
feature:  support multiple SNI for `ssl` object

### ISSUE THREAD

**Issue by cctv86** [apache/apisix#1306]
### Issue description

 ssl每次添加SNI都要创建证书, 后期证书到期，修改麻烦， 是否能借鉴kong， SNI做成一个list?

**Comment by membphis** [comment]
please use English on the public channel.

Your suggestion is very good. Would you like to contribute PR this?

**Comment by cctv86** [comment]
support multiple SNI for `ssl` object

**Comment by spacewander** [comment]
Solved in https://github.com/apache/apisix/pull/1678
