### ISSUE TITLE
change: enable the `backlog` parameter to control the total number of concurrent connections

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1315]
## plugin `limit-count` with `redis`

https://github.com/apache/incubator-apisix/blob/master/lua/apisix/plugins/limit-count/limit-count-redis.lua#L50

## Reference doc

backlog if specified, this module will limit the total number of opened connections for this pool. No more connections than pool_size can be opened for this pool at any time. If the connection pool is full, subsequent connect operations will be queued into a queue equal to this option's value (the "backlog" queue). If the number of queued connect operations is equal to backlog, subsequent connect operations will fail and return nil plus the error string "too many waiting connect operations". The queued connect operations will be resumed once the number of connections in the pool is less than pool_size. The queued connect operation will abort once they have been queued for more than connect_timeout, controlled by settimeouts, and will return nil plus the error string "timeout". This option was first introduced in the v0.10.14 release.

https://github.com/openresty/lua-nginx-module#tcpsockconnect

**Comment by Akayeshmantha** [comment]
Hi @membphis since its tcp related would like to give it a try after kafka plugin hope its ok?

**Comment by membphis** [comment]
that is fine @Akayeshmantha

**Comment by gxthrj** [comment]
Great, let me do it

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by gxthrj** [comment]
Sorry about that I forgot this issue. I will re-create a PR .

**Comment by membphis** [comment]
The priority of this issue is low.
