### ISSUE TITLE
Is it possible to have a script to convert etcd data and apisix.yaml file to each other?

### ISSUE THREAD

**Issue by zhengyionline** [apache/apisix#1326]
### Issue description
1、当进行路由Routes相关问题查找时，使用etcd查询不容易发现问题。
2、当第一次将接口全部向apisix迁移，使用apisix.yaml能更快更新etcd内数据

1. When looking for problems related to Routes, it is not easy to find problems using etcd queries.
2. When migrating all interfaces to apisix for the first time, use apisix.yaml to update the data in etcd faster.

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: CentOS7

**Comment by aimpsmile** [comment]
like upstream_id、service_id that id of auto make  . use etcd backup to data.whether is solve

**Comment by moonming** [comment]
@zhengyionline Please use English in the public channel, thx

**Comment by membphis** [comment]
No such feature at present, welcome to contribute PR

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
