### ISSUE TITLE
request help: How to dump variable data for debugging

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1362]
### Issue description
I'm using MQTT plugin to proxy some data to a broker. Before sending the data to upstream I want to parse and implement some custom security workflows. Thus how can I print all the request data for debugging?

**Comment by membphis** [comment]
There are two ways:

1. Use `json`.encode, the easiest, but not very convenient when viewing
2. Convert the request data into a hex string and output it in a format similar to `tcpdump`

```
00000000  3f ee 8f 50 a0 2b ce d9  fd 5b 6d 15 08 b0 55 5a   ?..P.+.. .[m...UZ
00000010  aa 49 06 b4 e3 29 e4 af  90 56 8e e9 b7 2f 6a 36   .I...).. .V.../j6
00000020  b5 4c d7 4e 8b f5 26 01  b8 ef 03 dc 3f 45 4d 97   .L.N..&. ....?EM.
00000030  e8 5f a5 77 0f 69 cb e8  c9 f9 a3 e5               ._.w.i.. ....
```

**Comment by sshniro** [comment]
Thanks, I will try the tcpdump method. 
I guess this can be added to the doc as well for reference?

**Comment by membphis** [comment]
> I guess this can be added to the doc as well for reference?

I am not sure. Anyone else have comments?

**Comment by moonming** [comment]
> > I guess this can be added to the doc as well for reference?
> 
> I am not sure. Anyone else have comments?

I think it could be added to MQTT's documentation.
