### ISSUE TITLE
feature: add global name

### ISSUE THREAD

**Issue by qiujiayu** [apache/apisix#1379]
APISIX need add global name for log platform, zipkin, such as spring boot 'spring.application.name',

**Comment by qiujiayu** [comment]
https://github.com/apache/incubator-apisix/pull/1370

the service name of Zipkin cloud be like this `service_name = zipkin.service_name or core.name` will be better.

**Comment by qiujiayu** [comment]
https://github.com/apache/incubator-apisix/pull/1241

the skywalking plugin also need.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
