### ISSUE TITLE
request help: do you have plan to support let's encrypt?

### ISSUE THREAD

**Issue by marshalys** [apache/apisix#1399]
### Issue description
let's encrypt can auto renew cert, does apisix have some plan to support it ?

**Comment by membphis** [comment]
yes, that is a todo item. welcome PR

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by anjia0532** [comment]
https://github.com/auto-ssl/lua-resty-auto-ssl
