### ISSUE TITLE
request help: routes only ipv4 or ipv6  support

### ISSUE THREAD

**Issue by wwd5613** [apache/apisix#1409]
### Issue description

when I set a route like

```
{
  "host":"www.wafhttps.com",
  "upstream":{
        "nodes":{
                     "127.0.0.1:8080":1
                    },
        "type":"round-robin"
  },
  "vars":[["server_port","==","80"]],
  "uri":"*"
}
```

i can visit by ipv4 or ipv6

### Environment

* apisix version (cmd: `apisix version`):
1.1
* OS:
only alowed by ipv4 or ipv6

**Comment by membphis** [comment]
By default, both IPv4 and IPv6 are enabled.

Are you asking how to use only IPv4 or IPv6? If so, you can consider using filter_fun.

**Comment by wwd5613** [comment]
{"filter_func":"function(vars) return string.len(vars['binary_remote_addr']) == 16 end","vars"

**Comment by membphis** [comment]
You are right. You can close this issue.

**Comment by spacewander** [comment]
Solved.
