### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by leonardjin** [apache/apisix#1431]
![image](https://user-images.githubusercontent.com/21360614/78806032-c312ed00-79f4-11ea-8c6e-06d301ac340f.png)

prometheus  impact the performance too much 

is there space to optimize the plugins?

there is no prometheus route
![image](https://user-images.githubusercontent.com/21360614/78807234-5a2c7480-79f6-11ea-9dab-ae1d84e20dff.png)

there is a prometheus route and press the other route without prometheus 

![image](https://user-images.githubusercontent.com/21360614/78807359-87792280-79f6-11ea-8bf5-eacef1f4a1f6.png)

**Comment by membphis** [comment]
please prove more information, for example, your route rules. one more thing, please confirm you are using standard `prometheus` plugin of Apache APISIX.

I have tested the prometheus plugin before, and the performance drop after activation is about 15%.

If you want to get better performance, this library may be useful: https://github.com/Kong/lua-resty-counter .

**Comment by membphis** [comment]
@leonardjin please set a good title, I think you just need help.

**Comment by moonming** [comment]
The top of the flame diagram is garbled, is the full debug symbol not installed?

**Comment by moonming** [comment]
>  I guess you do not use standard prometheus plugin in APISIX, please confirms this.

Looking at the call stack of the flame graph, it appears that the plug-in for Apache APISIX is indeed being used

**Comment by moonming** [comment]
> please prove more information, for example, your route rules.
> 
> I have tested the prometheus plugin before, and the performance drop after activation is about 15%.
> I guess you do not use standard prometheus plugin in APISIX, please confirms this.
> 
> If you want to get better performance, this library may be useful: https://github.com/Kong/lua-resty-counter .

I don't think this will solve the problem. If the flame graph had been displayed more completely, we would have been able to find the bottleneck. We can't just shoot with our eyes closed.

**Comment by Miss-you** [comment]
dependencies = {
    "lua-resty-template = 1.9",
    "lua-resty-etcd = 0.9",
    "lua-resty-balancer = 0.02rc5",
    "lua-resty-ngxvar = 0.5",
    "lua-resty-jit-uuid = 0.0.7",
    "lua-resty-healthcheck-iresty = 2.0",
    "lua-resty-jwt = 0.2.0",
    "lua-resty-cookie = 0.1.0",
    "lua-resty-session = 2.24",
    "opentracing-openresty = 0.1",
    "lua-resty-radixtree = 1.8",
    "lua-protobuf = 0.3.1",
    "lua-resty-openidc = 1.7.2-1",
    "luafilesystem = 1.7.0-2",
    "lua-tinyyaml = 0.1",
    "lua-resty-prometheus = 1.0",
    "jsonschema = 0.8",
    "lua-resty-ipmatcher = 0.6",
    "lua-resty-kafka = 0.07",
}

**Comment by membphis** [comment]
how

**Comment by membphis** [comment]
@Miss-you @leonardjin any news? it seems that the `nginx-lua-prometheus` will release a new version soon, it has better performance.

https://github.com/knyar/nginx-lua-prometheus/commits/master

**Comment by membphis** [comment]
fixed with new version of `nginx-lua-prometheus`.
