### ISSUE TITLE
[HELP]: how to install APISIX without a network

### ISSUE THREAD

**Issue by vrc289** [apache/apisix#1438]
### Issue description
官方的指导对于有网络的情况比较好，但是对于某些无网络的情况下感觉不是很好，相比于OR， 在无网络的情况下安装好openssl pcre  zlib 等库后就可以正常源码安装不同，官方指导中的每一种方式都需要连接服务器，想请教一下大家如何才能正常的在无网络的情况下顺利安装APISIX

### Environment

* apisix version (cmd: `apisix version`):  1.1
* OS: redhat 7.2

**Comment by membphis** [comment]
you can install the APISIX by rpm package.

https://github.com/apache/incubator-apisix/blob/master/doc/how-to-build.md#installation-via-rpm-package-centos-7

**Comment by vrc289** [comment]
sudo yum install -y https://github.com/apache/incubator-apisix/releases/download/1.1/apisix-1.1-0.el7.noarch.rpm

when you execute the above instruction without a network,  you will miss about 20 lua package, and you can't run the apisix server successfully

**Comment by ShiningRush** [comment]
Run a container is a good choice, [here](https://hub.docker.com/r/apache/apisix) is image.

**Comment by membphis** [comment]
> when you execute the above instruction without a network, you will miss about 20 lua package, and you can't run the apisix server successfully

This package packages all the dependencies, you only need to install openresty and etcd. Then APISIX can work normally.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by yinyang323** [comment]
I have same questions.

**Comment by membphis** [comment]
RPM for centos.
docker for others
