### ISSUE TITLE
feature:  Multiple accounts can be configured for one consumer

### ISSUE THREAD

**Issue by stone4774** [apache/apisix#1450]
At present, when creating a consumer, if you use the basic auth authentication method to configure multiple basic auth accounts, only the last one will be kept, and you want to configure multiple accounts at the same time

Scenario: a consumer has multiple instances. If the account password of its basic auth is leaked, the account or password must be changed. In the process of changing, there will be a problem that the new or old account fails to authenticate for a short time

If multiple accounts can take effect at the same time, the above problems will not occur during account replacement

**Comment by moonming** [comment]
> Scenario: a consumer has multiple instances. If the account password of its basic auth is leaked, the account or password must be changed. In the process of changing, there will be a problem that the new or old account fails to authenticate for a short time

In the case of a password leak, old passwords shouldn't be allowed to be accessed, right?

**Comment by stone4774** [comment]
Yes, so the password needs to be changed. The problem is how to ensure that 403 will not be returned in this process; 
  
 I create a consumer for each service to control its access to other services, so I must ensure that the request of the service is stable during password change;

If a consumer can support multiple accounts at the same time, it means that I can configure a new account password for the service. After all instances of the service are switched, delete the old account password, so as to ensure the safe and smooth transition of the service

**Comment by membphis** [comment]
> In the process of changing, there will be a problem that the new or old account fails to authenticate for a short time

You can do this through a custom authentication plugin. Not all users need this feature.
It maybe wrong for some users.
