### ISSUE TITLE
feature:  Load balancing of weighted-upstream 

### ISSUE THREAD

**Issue by stone4774** [apache/apisix#1452]
Currently, it only supports the weight configuration of different nodes in an upstream; it is usually used to adapt to the differences in the capabilities of each node; what is needed now is that different versions of a service can carry out load balancing according to different weights;            

In the current architecture model, upstream can take the role of service version very well. We only need to support multiple weighted-upstreams

**Comment by moonming** [comment]
@stone4774 can you show a example? thx

**Comment by stone4774** [comment]
When a service publishes a new version, you can create a new upstream (similar to the cluster in envy) for the instance of the new version, configure it to the service, and specify the weight as follows:

curl http://127.0.0.1:9080/apisix/admin/services/200 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "weighted_upstreams": {
        "total_weight": 100,
        "upstream_ids":[
            {
                 "upstream_id":1,
                 "weight": 99
            },{
                 "upstream_id":2,
                 "weight": 1
            }
        ]
    }
}'

I think it's very important, but at present, apsix doesn't support it. Now if I want to use a small amount of traffic to verify the new version, I have to find some routes with small traffic to try, but these traffic is selective and can't cover all situations

We can refer to the implementation of envoy:
https://www.envoyproxy.io/docs/envoy/v1.14.0/configuration/http/http_conn_man/traffic_splitting

**Comment by moonming** [comment]
LGTM. This is an implementation of the AB test, no more routing level to set conditions.
@membphis what do you think?

**Comment by moonming** [comment]
@stone4774 welcome PR, thx

**Comment by membphis** [comment]
LGTM too, that is a good feature

**Comment by stone4774** [comment]
I have implemented this requirement by using plug-ins, but I think it is more reasonable to integrate directly internally; I will bring it up in a few days

**Comment by membphis** [comment]
that is cool, waiting for your PR ^_^

**Comment by membphis** [comment]
@stone4774 any news?

**Comment by spacewander** [comment]
Can be simulated with traffic-split plugin.
