### ISSUE TITLE
request help: Backlog parameter value tuning

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1456]
APISIX backlog is currently the default value(Usually 128), and it is prone to packet loss in the listen queue and semi-link queue in large concurrent scenarios. 

APISIX is based on nginx. The backlog value of nginx is determined by two system configurations and one configuration value in nginx.conf:
1. System parameters:
sysctl net.ipv4.tcp_max_syn_backlog
sysctl net.core.somaxconn
2. nginx.conf:
default_server backlog

How to check the backlog size of APISIX process?
Use the 'ss -lnt' command

**Comment by membphis** [comment]
> APISIX backlog is currently the default value(Usually 128),

http://nginx.org/en/docs/http/ngx_http_core_module.html#listen

“sets the backlog parameter in the listen() call that limits the maximum length for the queue of pending connections. By default, backlog is set to -1 on FreeBSD, DragonFly BSD, and macOS, and to 511 on other platforms.”

the default of `backlog` should be `511`.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
