### ISSUE TITLE
request help: Health Checks for Upstream

### ISSUE THREAD

**Issue by Joe123-ai** [apache/apisix#1480]
Added Health Checks for Upstream, such as two nodes in a load balancing environment failing, why wait until the request has timed out before requesting a normal node server

**Comment by moonming** [comment]
How to reproduce the problem?

**Comment by Joe123-ai** [comment]
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
         "nodes": {
            "127.0.0.1:9090": 1,
            "127.0.0.1:8080": 1
        },
        "type": "roundrobin",
        "retries": 1,
        "checks": {
            "active": {
                "http_path": "/status",
                "host": "foo.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 1
                },
                "req_headers": ["User-Agent: curl/7.29.0"]
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [404,500],
                    "http_failures": 1,
                    "tcp_failures": 1
                }
            }
        }
    }
}'

My goal is that when a node server fails, after checking, the request can quickly go to another node server to request data.How do I set it?

**Comment by membphis** [comment]
After setting the routing rules, healthcheck did not start working immediately.

The healthcheck check will work after the first request comes in.

Then you wait for some time and test again, you can find that it will filter the unhealthy nodes.

**Comment by Joe123-ai** [comment]
I'm just going to go through the documentation, but it doesn't actually filter out unhealthy nodes.What's going on here?

**Comment by membphis** [comment]
if you still have problem, pls provide more log information. we need to confirm it

**Comment by membphis** [comment]
@Joe123-ai old issue, if you still have a problem, please feel free to reopen this issue.
