### ISSUE TITLE
request help: APACHE APISIX access log format optimization

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1482]
### Issue description

Hi everyone
The current Apache APISIX's 'access.log' format is as follows:

```
9.35.159.205 - - [20/Apr/2020:16:46:39 +0800] service-61ge01ri-1251890925.szjr.apigw.tencentcs.com:9080 "GET /e H7.29.0"  - 0.000
```

Generally speaking, it contains less information. At present, the 'access.log' of our gateway usually has the following fields, more fields can more easily locate the problem:

```
[route_id:$route_id][service_id:$service_id][consumer_id:$consumer_id]
[upstream_id:$upstream_id][host:$host][/release/m1_vivo_formal_1][https]
[rsp_st:200][ups_st:200][cip:39.65.54.127][uip:9.18.52.5:7999][vip:111.231.179.251]
[rsp_len:570][req_len:422][req_t:0.039][ups_rsp_t:0.039][ups_conn_t:0.003]
[ups_head_t:0.039][err_msg:-][tcp_rtt:39000][162780][20/Apr/2020:18:41:14 +0800]
[req_id:cf7c3ed06065bfac123448c67745c019]
```

I want to ask, does Apache APISIX need this log optimization PR?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
mail list: https://lists.apache.org/thread.html/re119c27a28acbc0b06b0a89bf03c5d1ac4a75e39b6f04c970ae951f6%40%3Cdev.apisix.apache.org%3E

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
