### ISSUE TITLE
bug: limit-count plugin not working right.

### ISSUE THREAD

**Issue by mattu79** [apache/apisix#1483]
### Issue description
When I use limit-count plugin, I send 3 request in 3 seconds, the limit-remain should be 9999, 9998, 9997, but get the 9999,9999,9999.
![limit-count-bug](https://user-images.githubusercontent.com/16251655/79766526-abbff200-835a-11ea-8932-63e63e2b0e20.png)

And the access log only log one request.
<img width="1386" alt="only_one_reqeust" src="https://user-images.githubusercontent.com/16251655/79766932-37398300-835b-11ea-843a-d3f7b7aa51b2.png">

* apisix version 1.1 in master:
* OS: MacOS

**Comment by membphis** [comment]
please update your apisix version.

and please confirm only one APISIX service is running.
if you need any help, please leave a message.
