### ISSUE TITLE
request help: How to run loggers globally

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1492]
### Issue description
When making a logger globally available (http/tcp/udp) the plugins which use the batch processor creates log buffers for individual route ids:

```bash
local entry = log_util.get_full_log(ngx)
local log_buffer = buffers[entry.route_id]
```

So, even though I configure the plugin to run globally it's going to create log buffers per route. One option to resolve this by using a single log buffer entry, if the plugin is configured as a global plugin.

Thus how can I identify, whether a plugin is configured per route or globally; inside the `_M.log` phase?

```lua
function _M.log(conf)
  if global_plugin then
    local log_buffer = buffers['global_http_logger']
  end
end
```

**Comment by sshniro** [comment]
Hi @membphis, can I know, is there a way to identify if the plugin is running in a global context or not?

**Comment by membphis** [comment]
we dont have this `flag` now. if you need, we can add one.

**Comment by sshniro** [comment]
That would be great, I'll create an issue for this enhancement.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
