### ISSUE TITLE
request help: health-check

### ISSUE THREAD

**Issue by zhanghouwen** [apache/apisix#1495]
![图片](https://user-images.githubusercontent.com/51305974/80054262-500b8980-8551-11ea-8c82-64b3876bf9e1.png)
If I want to check multiple "http_path", how should I set it? Can you give me an example?
Thanks！

**Comment by moonming** [comment]
@zhanghouwen not support yet, `host` is tring format, please take a look:https://github.com/apache/incubator-apisix/blob/master/apisix/schema_def.lua#L81
welcome PR

**Comment by spacewander** [comment]
Consider solved as the author didn't reply.
