### ISSUE TITLE
request help: Admin API supports prometheus exporter interface

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1509]
### Issue description

Currently, the prometheus exporter interface is used as an APISIX global route. In this case, there are certain security risks:
1. No WAF protection first
2. The second global route represents that other people can pull the data to the exporter through guessing, there is a certain security risk

I propose that the admin API supports the prometheus exporter interface

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by Miss-you** [comment]
I hope to discuss the suitability and feasibility of this feature.
@moonming @membphis

**Comment by membphis** [comment]
@Miss-you How about adding default parameters to the plugin?

**Comment by spacewander** [comment]
Solved.
