### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/apisix#1510]
### Issue description
can we inject into the exiting phase of nginx

### Environment

* apisix version (cmd: `apisix version`): v1.1
* OS: centos

**Comment by ShiningRush** [comment]
Here is all phase of openresty, I think you can use  `Log Phase` as you mentioned "exiting phase".
![image](https://user-images.githubusercontent.com/24238012/80328031-a7bb3500-8870-11ea-8c6c-2cd1dd41c7f4.png)

If all of those phase can not help you, you can post a issue to [openresty](https://github.com/openresty/openresty) : )

**Comment by moonming** [comment]
Actually, OpenResty doesn't have the exit phase yet.

**Comment by moonming** [comment]
@ShiningRush @OnlyPiglet these is a PR for exit work phase: https://github.com/openresty/lua-nginx-module/pull/1682

**Comment by OnlyPiglet** [comment]
> @ShiningRush @OnlyPiglet these is a PR for exit work phase: [openresty/lua-nginx-module#1682](https://github.com/openresty/lua-nginx-module/pull/1682)

thanks I see

**Comment by membphis** [comment]
> can we inject into the exiting phase of nginx

What do you need to do in the exit phase?

**Comment by OnlyPiglet** [comment]
> > can we inject into the exiting phase of nginx
> 
> What do you need to do in the exit phase?
some other operations to react with other system when apisix is exit

**Comment by membphis** [comment]
here is a simple way to implement a fake `exit` phase,  you can make a try.

```lua
local delay = 60 * 10
local handler
handler = function (premature)
    if premature then
        -- add your code here, that is a fake `exit` phase
        return
    end
    
    ngx.sleep(delay)
    local ok, err = ngx.timer.at(delay, handler)
    if not ok then
        ngx.log(ngx.ERR, "failed to create the timer: ", err)
        return
    end
 end

local ok, err = ngx.timer.at(0, handler)
if not ok then
    return
end
```

**Comment by OnlyPiglet** [comment]
@membphis thanks a lot
