### ISSUE TITLE
request help: Does the Node of the Upstream supports the IPV6 addr?

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1515]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
IMO, it supports IPv6, but there is not test cases to cover. welcome PR for that.

**Comment by Miss-you** [comment]
Okay, I happened to also use Apache APISIX 1.2 to verify whether the upstream node supports ipv6

**Comment by spacewander** [comment]
There are tests to cover it now.
