### ISSUE TITLE
request help: Does apisix support password protected SSL certs?

### ISSUE THREAD

**Issue by dotSlashLu** [apache/apisix#1527]
### Issue description
Many of our domain certificates are password protected, is it possible to use them with apisix? Will this be supported in the future?

### Environment

* apisix version (cmd: `apisix version`): v1.2
* OS: CentOS 7

**Comment by moonming** [comment]
not support yet.
I think it's a good feature, do you have time to do this feature?

**Comment by dotSlashLu** [comment]
Yes, this feature is very important for many businesses. In a large number of companies most of certificates, especially wildcard certificates, are asked to be encrypted for security. 

I would like to do this but it seems to be a veeery huge amount of work. 

Firstly, `ngx.ssl` doesn't support this directly. 

And, the hardest part is, to do it securely, I think it's better not to store the password, rather the password should be asked every time when nginx boots, like how nginx handles this. To do things in that phase, I need to write an nginx module(I don't even know if a module can work at boot time...) or even patch nginx itself.

Ohh! Ok... Suddenly an idea came to me. I think we can just configure password protected certs into config.yaml and put them inside nginx's config file, then nginx will ask the password and decrypt them for us, all we need to do is to get the encrypted certs and use them. Still a module or patch will be needed, but at least we will not need to mess with the boot phase.

All of these are just some preliminary thoughts, maybe it's just impossible to implement. PLEASE don't expect too much. But I'll see to it if I have time. Any advice and guidance from the team are useful to me, thanks!

**Comment by moonming** [comment]
thanks @dotSlashLu

**Comment by membphis** [comment]
@dotSlashLu you can make a try with this way first

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by BohdanM-AVISPL** [comment]
Hello, @dotSlashLu, you closed it as completed. Was you able to come up with some solution?

**Comment by SebastienB-AVISPL** [comment]
Hello Team, @dotSlashLu, @membphis,

This feature is important for business, some companies won't accept to expose Apisix if certificate private key is not protected by a passphrase. We are running into that problem a few weeks before going to production with Apisix.
It it possible to re-open this issue ?

I made attempts to forcing the "ssl_password_file" field in the nginx.conf, but it does not work.
I suppose Apisix is trying to load the key defined in "ssls" section before the nginx.conf is generated/used (just a guess)
Apisix shows message "Enter PEM pass phrase:" in log and fails with error (values changed) :

**Enter PEM pass phrase:**
[error] 362#362: *1 [lua] **config_yaml.lua:218**: failed to check item data of [ssls] err:failed to parse key:  **PEM_read_bio_PrivateKey() failed** ,val: {"key":"-----BEGIN ENCRYPTED PRIVATE KEY-----\nMII[....]-----END ENCRYPTED PRIVATE KEY-----\n","id":"ssl1","status":1,"snis":["test.com"],
"type":"server","cert":"-----BEGIN CERTIFICATE-----[...]-----END CERTIFICATE-----\n"}, context: init_worker_by_lua*

**Comment by igor-borisoglebski** [comment]
APISIX uses openresty and not nginx. From what I could tell, openresty isn't supporting that use case directly. Perhaps it might be possible to load a passphrase protected certificate with this library: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/ssl.md

**Comment by sbrouet** [comment]
Hello,

This feature is still important to us.
We would really appreciate if some though could be given into it, maybe a rough estimate of implementation cost could be done, so it is clear whether this feature could be planned or not.

OpenSSL library documentation gives an example on how to use method `PEM_read_bio_PrivateKey` and read passphrase:
https://www.openssl.org/docs/man1.1.1/man3/PEM_read_bio_PrivateKey.html
See:
```
Write a private key (using PKCS#8 format) to a BIO using triple DES encryption, using the pass phrase "hello":
[...]
Skeleton pass phrase callback:
```

@igor-borisoglebski  : https://openresty.org/en/  OpenResty® is a full-fledged web platform that integrates our enhanced version of the [Nginx](https://openresty.org/en/nginx.html) core
First thing Apisix Docker entrypoint does is generating the nginx.conf file.

Thank you
