### ISSUE TITLE
[discuss] need a way to debug API (router rules)

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1533]
1. add a `DEBUG API` page
2. user can specify the request header, URI, arguments and body
3. click the `RUN API` button to debug the API
4. show the running step detail info about this API

here is an example of design:

![image](https://user-images.githubusercontent.com/6814606/81249851-43f3f180-9052-11ea-933e-6eca0cc9b0c2.png)

**Comment by moonming** [comment]
@membphis I think you should describe the requirements in detail, it's not appropriate to post a picture here

**Comment by membphis** [comment]
thx @moonming I have updated the picture.

**Comment by spacewander** [comment]
Is it still on the roadmap? As summer 2020 has been passed.

**Comment by moonming** [comment]
@juzhiyuan is dashoard debug feature support this?

**Comment by juzhiyuan** [comment]
Hi @membphis, we have supported the first three steps, as for `show the running step detail info about this API`, I need to consider this one with @liuxiran. We could close this issue now, let me create a new one at Dashboard to track.
