### ISSUE TITLE
Support JWT sub attribute for consumer detection

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1538]
### Issue description
In general, the [JWT sub](https://tools.ietf.org/html/rfc7519#section-4.1.2) contains the intended recipient or user of the token. Via using this attribute we can uniquely identify the user (email/uuid). 

If an enterprise is using OAuth for communication, then when we export the access logs, we need to decode the JWT token manually to identify the user. It would be nice if we can hint the Open ID connect plugin to identify the user, via using the JWT token. By this, we can effortlessly identify the user in log management platforms like Kibana.

```lua
local schema = {
    type = "object",
    properties = {
        client_id = {type = "string"},
        ssl_verify = {type = "boolean"}, -- default is false
        consumer_attribute = {type = "string", default = "sub"},
    }
}
```

```lua
function _M.access(conf, ctx)
-- decode token
-- if consumer_attribute present
ngx.ctx.consumer = jwttoken.sub
end
```

By setting this value, the [logutil](https://github.com/apache/incubator-apisix/blob/master/apisix/utils/log-util.lua) can successfully export the jwt consumer to the external log management platforms.

**Comment by moonming** [comment]
LGTM, welcome PR

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by tzssangglass** [comment]
@sshniro , I am interested in this enhancement and need more discussion. Does your proposal mean that Open ID connect is linked to the JWT plugin?
