### ISSUE TITLE
[discuss] need a way to support v3 protocol of etcd

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1542]
use a new component `etcd proxy` (maybe a process or a Nginx server).

`user -> etcd proxy -> admin API -> etcd v3`.

![image](https://user-images.githubusercontent.com/6814606/81135867-5f94c480-8f8c-11ea-9f86-7ce8ebe77de5.png)

**Comment by nic-chen** [comment]
proxy mode will make the system complicated. I prefer to provide a conversion interface in the resty-etcd library for now, which can convert the respond data of the v3 interface into the format of the v2 interface to achieve compatibility.

**Comment by moonming** [comment]
why not support etcd v3 directly?

**Comment by bingchengxiaobing117** [comment]
I have tried etcd v3 procotol, but I often run out of time in watchdir api. If you are interested, you can discuss it together, the detail see:
https://github.com/api7/lua-resty-etcd/issues/56

**Comment by membphis** [comment]
> why not support etcd v3 directly?

The Admin API and apisix core depend on the etcd v2 protocol.

If we support etcd v3 directly, it will be a big PR. But I love to support etcd v3 directly, v3 is future.

**Comment by Yiyiyimu** [comment]
Hi @nic-chen , I'm interested in this project for summer-2020. Do you have some guideline/evaluation tasks or suggestions to get familiar with this project?

**Comment by moonming** [comment]
@Yiyiyimu are you come from https://cwiki.apache.org/confluence/display/APISIX/Open+Source+Promotion+Plan+-+Summer+2020+Tasks?
I think you can start from how to use https://github.com/api7/lua-resty-etcd, and th different from etcd v2 and v3 protocol.

**Comment by moonming** [comment]
@nic-chen what do you think?

**Comment by moonming** [comment]
@Yiyiyimu IMO, I suggest you to use etcd v3 directly in Apache APISIX, not the etcd proxy mode.

**Comment by Yiyiyimu** [comment]
> @Yiyiyimu are you come from https://cwiki.apache.org/confluence/display/APISIX/Open+Source+Promotion+Plan+-+Summer+2020+Tasks?
> I think you can start from how to use https://github.com/api7/lua-resty-etcd, and th different from etcd v2 and v3 protocol.

Thank you @moonming for the quick reply! 

Yes I do come from the promotion plan. I'll give it a try on lua-resty-etcd these days.

**Comment by moonming** [comment]
great, please feel free ping me when you need any help.
I will add you to the candidate of this task.

Shuyang Wu <notifications@github.com> 于 2020年5月23日周六 上午12:31写道：

**Comment by nic-chen** [comment]
@Yiyiyimu

I suggest that you could install Apache APISIX using the master branch source code, 
and then configure and use it according to the documentation, 
so that you can understand how APISIX and etcd work, 
and then look at the source code to understand how [lua-resty-etcd](https://github.com/api7/lua-resty-etcd) v2 is used in APISIX.

If you do not have openresty development experience, you need to familiarize yourself with openresty first.

As @moonming said, we have discussed and reached an agreement to directly use v3 instead of v2 without data format compatibility.

please feel free to contact us when you need any help. Thanks.

**Comment by Yiyiyimu** [comment]
Thank you @nic-chen for your stepwise suggestions! BTW, which way do you recommend to contact the mentors and the community, email subscription, gitter or some other ways?

**Comment by moonming** [comment]
mailinglist is the best

Shuyang Wu <notifications@github.com> 于 2020年5月23日周六 下午3:04写道：

**Comment by moonming** [comment]
@Yiyiyimu we can discuss this issue in the dev mailing list: dev@apisix.apache.org, thx

**Comment by Yiyiyimu** [comment]
Sure thank you Ming!
I'll update my progress in these days.

________________________________
发件人: Wen Ming <notifications@github.com>
发送时间: 2020年5月30日星期六 10:38
收件人: apache/incubator-apisix
抄送: Shuyang Wu; Mention
主题: Re: [apache/incubator-apisix] [discuss] need a way to support v3 protocol of etcd (#1542)


@Yiyiyimu<https://github.com/Yiyiyimu> we can discuss this issue in the dev mailing list: dev@apisix.apache.org<mailto:dev@apisix.apache.org>, thx

―

**Comment by nic-chen** [comment]
hi @Yiyiyimu 

Is there any progress?

please feel free to contact us if you have any problem with this.
