### ISSUE TITLE
Support Groups for consumers 

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1548]
Currently, the auth plugins require individual consumer names. But in general organization have multiple consumers for an app and managed them via groups. By grouping the consumers we can easily set the groups to other routes/plugins and consumer restrictions.

**Comment by moonming** [comment]
Is this more appropriate to control on the dashboard?

**Comment by sshniro** [comment]
@moonming yes we can extend the support for configuring this in the dashboard as well. But I presume the core should have the functionality to create group consumers. Therefore, we can add users to blocked and allowed groups and use them in the authentication plugins.

If this is okay, then I would like to contribute to this feature.

**Comment by membphis** [comment]
I am very interested in this feature.

**Comment by wasabihu** [comment]
I also have similar ideas.

Consumer and group have many-to-many relationship.

example:
`
curl http://127.0.0.1:9080/apisix/admin/consumers/2  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "username": "jack4",
	"groups" : [
                "jack1", "wasabi"
            ],
    "plugins": {
        "key-auth": {
            "key": "auth-one4"
        }
    }
}'
`

**Comment by jp-gouin** [comment]
Hi,
Is this feature still in development or planned in a futur release ?

**Comment by sshniro** [comment]
I could not work on this feature. Please feel free to contribute.
