### ISSUE TITLE
bug: Apache APISIX concurrent connection statistics implementation method is wrong

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1549]
### Issue description

The current statistical method of the number of concurrent connections is to count +1 when there is a new http request and -1 when processing a request, but in fact a long connection often has multiple http requests and responses. The current APISIX statistics of the current connection is more appropriate to be called the QPS.

The number of concurrent connections is usually based on the nginx qos module

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment]
I don't think it's bug, and this isn't a QPS concept either.
please refer to https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/conn.md, maybe `request concurrency` is more clear.
