### ISSUE TITLE
feature: support new field `host` for Service object

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix#1573]
### Issue description
The service object adds a host field. When the route object does not have a host field, the service object can be inherited. 
When the host needs to be changed, only the service can be changed, and it is not necessary to modify all the route host fields.
Structurally, the service object is more like a server in nginx,  the route object is location.

**Comment by membphis** [comment]
@lilien1010 do you have time to implement this feature?

**Comment by spacewander** [comment]
There is no interest to add more features to the service object.

This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
