### ISSUE TITLE
bug: The return value of 'os.execute' in 'bin/apisix' is different in different APISIX Release. 

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1577]
### Issue description

The rpm package version of bin/apisix uses LUAJIT. On the other hand, luarocks or the source version of bin/apisix uses LUA.

In Lua 5.1, the return value of os.execute is 0 or non-zero; in LUAJIT or Lua 5.3 version, the return value of os.execute is true or nil.

For the rpm package version, `apisix reload` and other commands are unavailable due to the incompatibility of `os.execute` return value processing.

https://www.lua.org/manual/5.1/manual.html#pdf-os.execute
https://www.lua.org/manual/5.3/manual.html#pdf-os.execute

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by Miss-you** [comment]
I personally think that the `os.execute` processing compatible with different lua interpreters is just fine. It is not recommended to rewrite the `bin/apisix` script in other languages, which is a waste of time.

**Comment by membphis** [comment]
change to `luajit` may be a good way.

https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L1

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/bin/apisix#L912

Compatible mode, can support lua and luajit at the same time.
