### ISSUE TITLE
refactor SSL logic

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1578]
But this poses a risk that the SNI and expiration times are likely to be inconsistent with SSL certificates, and there is now no validation mechanism.
A better approach would be:
1. add checks for public and private keys
2. the sni and expiration time are automatically obtained from the certificate.

This PR can be a temporary implementation that will be refactored later. A new issue can be created.

_Originally posted by @moonming in https://github.com/apache/incubator-apisix/issues/1571#issuecomment-627166317_

**Comment by spacewander** [comment]
Solved by #3085
