### ISSUE TITLE
feature: support talking to etcd via TLS.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#158]

**Comment by membphis** [comment]
`etcd` 的 TLS 认证通常是双向的，但目前 cosocket 是不支持的，不过还好，目前有个 PR 是正在进行中。 

可以期待一下这个 PR：https://github.com/openresty/lua-nginx-module/pull/997

**Comment by moonming** [comment]
The TLS authentication is important for auth between end to end, not just for etcd.

**Comment by moonming** [comment]
based on this PR: https://github.com/openresty/lua-nginx-module/pull/1599, we can do more things about auth between end to end.

**Comment by Miss-you** [comment]
Hi, I believe that we don't need to support the TLS or the priority of this requirement is not high or even a pseudo-demand. TLS/HTTPS solved the risk of data being hijacked at WAN. APISIX usually access etcd via LAN, and messages in the LAN usually do not need to be considered for hijacking.
If we need to access etcd via the WAN, encryption methods such as TLS are necessary.

**Comment by phin1x** [comment]
Is there any progress on this issue? TLS communication and mTLS auth ist very important for etcd.
accessing the etcd via lan is no excuse. In enterprise environments or shared enviroments you have dozens of applications running in the same network. if one of those apps got hijacked, it can easy access your data.
for development purpose it is ok to run a insecure setup, in production end to end encryption and authentication is a basic requirement, no matter where etcd is running!

**Comment by membphis** [comment]
> Is there any progress on this issue?

the official `openresty` still not support the mTLS now. we have to wait

**Comment by moonming** [comment]
OpenResty already support mTLS.

Thanks,
Ming Wen
Twitter: _WenMing


YuanSheng Wang <notifications@github.com> 于2020年8月12日周三 下午11:42写道：

**Comment by membphis** [comment]
> OpenResty already support mTLS.

https://github.com/openresty/lua-resty-core/pull/278

We still need to wait more time.

**Comment by spacewander** [comment]
Solved by #2584 . Server side TLS verification is enough to use by now.
