### ISSUE TITLE
bug: Stand-alone mode init error ,so work error

### ISSUE THREAD

**Issue by andyindr** [apache/apisix#1584]
### Issue description
use Stand-alone mode
but init error

### Environment

* apisix version (cmd: `apisix version`):
* OS: centos7

apisix:1.2

### Minimal test code / Steps to reproduce the issue
config.yaml:
config_center: yaml 

apisix.yaml :
routes:
  -
    uri: /hello
    upstream:
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
#END

### What's the actual result? (including assertion message & call stack if applicable)

error.log

2020/05/13 11:18:55 [error] 8877#8877: *3 [lua] config_yaml.lua:169: failed to check item data of [routes] err:failed to create lock: dictionary not found ,val: {"uri":"\/hello","upstream":{"nodes":{"127.0.0.1:1980":1},"type":"roundrobin"}}, context: ngx.timer

### What's the expected result?

Stand-alone mode can work in 1.2

**Comment by andyindr** [comment]
use etcd is well done
but Stand-alone mode no work

**Comment by membphis** [comment]
what is your error message you got?

**Comment by andyindr** [comment]
the question has resolve

because the rpm package has bug
https://github.com/apache/incubator-apisix/releases/download/1.2/apisix-1.2-0.el7.noarch.rpm

**### after installed,  must delete path/deps/share/lua/5.1/apisix**

avoid plugins conflict........

**Comment by andyindr** [comment]
detail log:

2020/05/21 13:34:07 [error] 19580#19580: *1455 [lua] config_yaml.lua:169: failed to check item data of [routes] err:failed to create lock: dictionary not found ,val: {"uri":"\/hello","upstream":{"nodes":{"127.0.0.1:1980":1},"type":"roundrobin"}}, context: ngx.timer
2020/05/21 13:34:33 [error] 19580#19580: *1861 lua entry thread aborted: runtime error: .../deps/share/lua/5.1/apisix/http/router/radixtree_uri.lua:42: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'ipairs'
	.../deps/share/lua/5.1/apisix/http/router/radixtree_uri.lua:42: in function 'create_radixtree_router'
	.../deps/share/lua/5.1/apisix/http/router/radixtree_uri.lua:97: in function 'match'
	/usr/local/apisix//deps/share/lua/5.1/apisix/init.lua:285: in function 'fun_org'
	/usr/local/apisix//deps/share/lua/5.1/apisix/debug.lua:132: in function 'http_access_phase'
	access_by_lua(nginx.conf:167):2: in main chunk, client: 192.168.137.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.137.229:9080", referrer: "http://192.168.137.229:9080/hello"

**Comment by moonming** [comment]
> the question has resolve
> 
> because the rpm package has bug
> https://github.com/apache/incubator-apisix/releases/download/1.2/apisix-1.2-0.el7.noarch.rpm
> 
> **### after installed, must delete path/deps/share/lua/5.1/apisix**
> 
> avoid plugins conflict........

why we must delete `path/deps/share/lua/5.1/apisix`? if we do that, all deps are missing.

**Comment by membphis** [comment]
old issue. @andyindr if you still have this issue with the latest APISIX, feel free to reopen this issue
