### ISSUE TITLE
request help: A better way to support the Etcd Cluster and the two-way authentication with ETCD.

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1592]
### Issue description

Since the Openresty base library does not support the client to initiate https two-way authentication, some users have recently consulted how APISIX supports Etcd two-way authentication. I thought of a solution that can solve the https two-way authentication problem through etcd proxy.

In the mode of Etcd proxy, Etcd acts as a reverse proxy and forwards client requests to the Etcd cluster. Etcd proxy does not participate in the consistent replication of Etcd clusters.

We can complete two-way authentication with Etcd through Etcd proxy, or connect to Etcd cluster through Etcd proxy; Etcd proxy and APSIIX are deployed on the same node, APISIX interacts with local Etcd proxy, Etcd proxy only allows localhost address access

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by Akayeshmantha** [comment]
@Miss-you  this is a great approach.

**Comment by membphis** [comment]
We can write some doc about this feature. 
Anyone want to do this?

**Comment by spacewander** [comment]
APISIX now supports mTLS by itself.
