### ISSUE TITLE
request help: Better documentation for standalone mode configuration

### ISSUE THREAD

**Issue by wangyjx** [apache/apisix#1597]
### Issue description
The documentation for standalone mode is very few, it doesn't cover many scenarios, like host match, plugins, people can only make trials with lots of failures. It is time-consuming. Please complete the document for this.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
@apache/apisix-committers Anyone wants to do this?

**Comment by juzhiyuan** [comment]
Just waiting for this
