### ISSUE TITLE
bug: reload Occasional bug,create core dump file in /tmp/core_apisix

### ISSUE THREAD

**Issue by wwd5613** [apache/apisix#1603]
### Issue description
when i reload apisix by command 'make reload',  sometimes ,create a large number of dumpfile in /tmp/core_apisix.
but make stop & make run is errorless.

### Environment

* apisix version (cmd: `apisix version`): v1.2
* OS:centos7.4

### Minimal test code / Steps to reproduce the issue
1. make reload
### What's the actual result? (including assertion message & call stack if applicable)

![image](https://user-images.githubusercontent.com/2143396/82531887-c7ddcb80-9b72-11ea-8144-767dd4934d74.png)

**Comment by agile6v** [comment]
Hi @wwd5613 Please provide the stack of the core file. 

Thanks

**Comment by membphis** [comment]
@wwd5613 any news?

**Comment by membphis** [comment]
old issue, @wwd5613 if you still have this issue with latest APISIX, feel free to reopen this issue
