### ISSUE TITLE
bug: stand alone mode proxy-rewrite headers has bug

### ISSUE THREAD

**Issue by andyindr** [apache/apisix#1604]
### Issue description
under stand alone mode 
the proxy-rewrite headers has bug

https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/proxy-rewrite.lua
this plugin under stand alone , after set apisix.yaml
the check_schema function no use, only execute rewrite

so headers_arr not exist

the bug result is apisix.yaml content:

proxy-rewrite:
            headers_arr: ["X-Api-Version", "v1", "X-Api-Engine", "apisix", "X-Api-useless", "6666"]

only this format can used

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS: centos7

### Minimal test code / Steps to reproduce the issue
1.proxy-rewrite:
            headers: 
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

custom header not useful

### What's the expected result?

custom header can useful

**Comment by moonming** [comment]
@membphis  please take a look

**Comment by membphis** [comment]
@andyindr please provide a fully config of `conf/apisix.yaml`

we need it .

**Comment by membphis** [comment]
we need to check schema after we got the conf, here is an example:

 
```lua
if data_valid and self.item_schema then
    data_valid, err = check_schema(self.item_schema, item.value)
    if not data_valid then
        log.error("failed to check item data of [", self.key,
                    "] err:", err, " ,val: ", json.encode(item.value))
    end
end
```

Here is the code for config_etcd:
https://github.com/apache/incubator-apisix/blob/master/apisix/core/config_etcd.lua#L169

**Comment by membphis** [comment]
and we need to update this file: https://github.com/apache/incubator-apisix/blob/master/apisix/core/config_yaml.lua

@nic-chen do you have time to fix this bug?

**Comment by wrl96** [comment]
@membphis I have resolved this bug. pls assign it to me

**Comment by membphis** [comment]
@wrl96 please feel free to submit your PR, waiting for it ^_^

**Comment by spacewander** [comment]
Fixed by https://github.com/apache/apisix/pull/2856
