### ISSUE TITLE
plugin(prometheus): support to hot reload

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1610]
This is the current todo comments:

https://github.com/apache/incubator-apisix/pull/1607/files#diff-dc8151ecf7fc460e27a70fb1e00e7f55R53

The metrics can only be initialized in the init and init worker phases, and we need to let it support other phases.

**Comment by liuhengloveyou** [comment]
Does it need to close now?

**Comment by membphis** [comment]
yes
