### ISSUE TITLE
bug: the value of operationName in ExitSpan is nil in the plugin of skywalking

### ISSUE THREAD

**Issue by cyxinda** [apache/apisix#1614]
### Issue description
the value of operationName in ExitSpan is nil in the plugin of skywalking，that is because of the value of ctx.var.upstream_uri  in the line 54 of the file of apisix/plugins/skywalking/tracer.lua is nil.

### Environment

* apisix version (cmd: `apisix version`):the mix version of master and moonming/apisix
* OS: centos 7.5

### Minimal test code / Steps to reproduce the issue
1.There are some wrong with the ui of skywalking,as follow:
![image](https://user-images.githubusercontent.com/7237898/82865363-24692e00-9f59-11ea-97cc-9805c0e1d9b4.png)
2. I  analysis of  the messages from skywalking web server ,And find that the endpointname is nil.
![image](https://user-images.githubusercontent.com/7237898/82865580-a6f1ed80-9f59-11ea-8981-5aa990122124.png)
3.I log the message that is sended to skywalking server in the apisix.the operationName value is nil string.
![image](https://user-images.githubusercontent.com/7237898/82865791-2bdd0700-9f5a-11ea-9c76-2c4d7333743c.png)
And the code about that is  in the line 54 of the file of apisix/plugins/skywalking/tracer.lua.
![image](https://user-images.githubusercontent.com/7237898/82865967-9130f800-9f5a-11ea-9fc5-a1fd3f028004.png)

### What's the actual result? (including assertion message & call stack if applicable)
the value of ctx.var.upstream_uri  in the line 54 of the file of apisix/plugins/skywalking/tracer.lua is nil

**Comment by moonming** [comment]
good catch.
`upstram_uri` was set in https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L397, and will be rewrite if enable `proxy-rewrite` plugin:https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/proxy-rewrite.lua#L156.

so the line 54 of the file of apisix/plugins/skywalking/tracer.lua should be:
```ctx.var.upstream_uri or ctx.var.uri```

welcome PR to fix it.

**Comment by spacewander** [comment]
Now `ctx.var.uri` is used instead.
