### ISSUE TITLE
feature: support url check with regular expression matching and dynamic upstream selection

### ISSUE THREAD

**Issue by shengnoah** [apache/apisix#1617]
### Issue description
Support url check with regular expression matching.
If  url contains some specical characters and regular expression defined matching.
Set dynamic proxy upstream point to  HTTTP Server A.
If msimatch regular expression.
Set dynamic proxy upstream point to  HTTTP Server B.

### Example

URL: http://127.0.0.1/index.php?a=<script>
Regular expression: “\<(iframe|script|body|img|layer|div|meta|style|base|object|input)” 
Match result: Yes, found a match string:"<script"  and  set dynamic proxy upstream point to HTTP server B.
 
Upstream HTTP server A : accept user normal HTTP Service Requests.
Upstream HTTP server B : accept user illegal requests.
Syslog Server : open Syslog UDP listening port with logs data reception for the statistics.

### Flow process

![example](https://github.com/shengnoah/luaren/wiki/images/apisix_url_regular_matching.jpg)

**Comment by moonming** [comment]
@shengnoah I think Apache APISIX already support this, you can use https://github.com/api7/lua-resty-radixtree#operator-list to match uri with regex operator `~~`

**Comment by shengnoah** [comment]
Yeah , "operator-list" is OK.

I think i shoud edit issue title,
"support url check with regular expression matching  and  dynamic upstream selection"
According to regular expressions match result to select a upstream server by the definition of users.

> @shengnoah I think Apache APISIX already support this, you can use https://github.com/api7/lua-resty-radixtree#operator-list to match uri with regex operator `~~`

**Comment by membphis** [comment]
@shengnoah you can write an example of this plugin. What do you think?

```
{
    "uri_list": [
        "/foo/glay/*", "/foo/bar", "/foo/gloo/*"
    ],
    action: {
        reject_code: 200,
        delay: 10     # 1 sec
        body: xxxx
    }
}
```

**Comment by shengnoah** [comment]
{
    "uri_list:" [
        "/test?Username=laoli&DeviceId=XDS3EFG756767676DXCVXV234234"
    ],
    rules: {
        rule:  (?:laoli)&DeviceId=XDS3EFG756767676DXCVXV234234
    },
    action: {
        OK_proxy_pass:https://iresty.com/testcase_one
        NG_proxy_pass:https://apisix.com/testcase_one
    }
}

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/84781689-b5dc3500-b019-11ea-9072-0d2396f4331b.png)

**Comment by membphis** [comment]
step1:

```
{
    uri_rules: [
        "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
        "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
    ],
    rejected_code: 403
}
```

step2:

```
{
    uri_rules: [
        "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
        "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
    ],
    honey_pot: "https://apisix.com/testcase_one"
}
```

step3:

```
{
    uri_rules: [
        "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
        "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
    ],
    honey_pot: "https://apisix.com/testcase_one",
    syslog_server: "udp://xxxx:2380/"
}
```

**Comment by shengnoah** [comment]
> plugins:
> 
> 1. allow-list
> 2. block-list
> 
> we can implement the plugin by 3 steps:
> 
> step1: hit rules and set response code
> 
> ```
> {
>     uri_rules: [
>         "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
>         "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
>     ],
>     rejected_code: 403
> }
> ```
> 
> step2: hit rules and set specify upstream
> 
> ```
> {
>     uri_rules: [
>         "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
>         "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
>     ],
>     honey_pot: "https://apisix.com/testcase_one"
> }
> ```
> 
> step3: hit rules and write the log to specify `syslog` server
> 
> ```
> {
>     uri_rules: [
>         "(?:liuneng)&DeviceId=XDS3EFG756767676DXCVXV234234",
>         "(?:zhaosi)&DeviceId=CDF7EFG1212345687XCEVXV678976",
>     ],
>     honey_pot: "https://apisix.com/testcase_one",
>     syslog_server: "udp://xxxx:2380/"
> }
> ```

Maybe it's better to change the variable name. 

uri_rules -> filter-rules
Because not just filer URLs in future.

honey_pot -> honeypot
