### ISSUE TITLE
[DISCUSS] "config.yaml" supports annotation configuration

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1620]
### Issue description

The current nginx.conf configuration file for apache apisix is generated by `bin/apisix` from the `config.yaml` configuration file, so nginx.conf is best generated by the `bin/apisix` script rather than maintaining a copy itself.

However, the current `bin/apisix` support for generating `nginx.conf` is a generic configuration and does not support some custom or temporary configurations.

It is hoped that `config.yaml` will add an annotation field and that the configuration of this part will be generated directly to the specified location in `nginx.conf`.

Similar practice: in kubernetes-ingress, Ingress configuration has a comment field, where you can fill in large `nginx.conf` custom configurations directly in the comment field, instead of having to implement a piece of code for each field (because some configurations are customized, and it doesn't make sense to leave them to `bin/apisix` implementation, which is not general enough).

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@Miss-you can you show a example about annotation configuration?

**Comment by membphis** [comment]
@Miss-you any news?

**Comment by xxm404** [comment]
Maybe APISIX needs support to require the Nginx template file, the user can custom Nginx config by modifying the Nginx template file.

**Comment by membphis** [comment]
`bin/apisix` has contained a template already.

**Comment by xxm404** [comment]
> `bin/apisix` has contained a template already.

I mean, APISIX can make `nginx.template` file like `apisix.yaml` in APISIX home directory.

**Comment by membphis** [comment]
they were the same for users. 
I want to hide nginx.conf, the personality part should only be in the configuration file.
