### ISSUE TITLE
bug: the behavior of the code 'ngx.worker.id() == 0' in the the file of skywalking/client.lua would not be unpredictable 

### ISSUE THREAD

**Issue by cyxinda** [apache/apisix#1623]
@moonming 
### Issue description
the behavior of the code 'ngx.worker.id() == 0' in the the file of skywalking/client.lua would not be unpredictable becuase we can't predict when the worker process id ==0 will be executed.

### Environment

* apisix version (cmd: `apisix version`):the master version with the skywalking plugin.
* OS:centos7.5

### Minimal test code / Steps to reproduce the issue
1.the code location is as follow:
![image](https://user-images.githubusercontent.com/7237898/83133426-72c32c00-a115-11ea-967d-ec1aabd085af.png)

2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
The worker process that id ==0  did not execute for a long time after request,which results in the skywalking data not being sent in time.

### What's the expected result?
  I think this timer to send skywalking data should be added when the skywalking plugin is added.for example when schame is checked.
![image](https://user-images.githubusercontent.com/7237898/83133633-bddd3f00-a115-11ea-876a-046c8de5e9a7.png)
 The current position of the timer is as follows:
![image](https://user-images.githubusercontent.com/7237898/83134010-4d82ed80-a116-11ea-8d2b-88515b014713.png)

**Comment by lilien1010** [comment]
@cyxinda 
I think your mean `client.lua behavior would  be unpredictable`

but accordding doc like below
https://github.com/openresty/lua-nginx-module#ngxworkerid

worker.id is from 0 to N-1

**Comment by zhangjicun** [comment]
local endpoint = conf.endpoint
local tracing_buffer = ngx.shared['skywalking-tracing-buffer']
local service_id = tracing_buffer:get(endpoint .. '_service_id')

replace
if ngx.worker.id() == 0 and not heartbeat_timer then
to
if not service_id and not heartbeat_timer then

how about like this going to work?

**Comment by membphis** [comment]
@moonming please take a look at https://github.com/apache/incubator-apisix/issues/1623#issuecomment-652813171

**Comment by spacewander** [comment]
This issue is not longer valid since skywalking client is rewritten. And now the client works as suggested.

**Comment by cyxinda** [comment]
OK，thx

发自我的iPhone
