### ISSUE TITLE
safe: The vars in the route require illegal verification

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#1639]
Variables in `vars` need to be written in a certain format
e.g.
http_xxx > 1
arg_xxx == 2
cookie_xxx ~~ "hello.*"
If the variable is directly written as `xxx`, the rule does not take effect

**Comment by moonming** [comment]
I think we also need to check the prefix, only `http`, `arg`, `cookie` are allowed.

**Comment by spacewander** [comment]
The `vars` is so flexible that there is no way to limit it. For example, we have `graphql_operation` support which is pure implemented in Lua.
