### ISSUE TITLE
add support for Vault

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1652]

**Comment by membphis** [comment]
what do you mean `Vault`?

**Comment by moonming** [comment]
please google the key Word first

YuanSheng Wang <notifications@github.com> 于 2020年6月21日周日 下午4:38写道：

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/85220670-0966ce00-b3e0-11ea-9721-cb3cf3c24ad2.png)

I do not know who you want to support.

**Comment by moonming** [comment]
Vault is for store and manger private and security data, like ssl key,
password etc.

YuanSheng Wang <notifications@github.com> 于 2020年6月21日周日 下午4:57写道：

**Comment by membphis** [comment]
It seems like this project: https://github.com/hashicorp/vault

**Comment by sshniro** [comment]
@moonming  @membphis shall I attempt this task?

**Comment by moonming** [comment]
sure, absolutely.

Thanks,
Ming Wen
Twitter: _WenMing


Nirojan Selvanathan <notifications@github.com> 于2020年8月6日周四 下午4:49写道：

**Comment by sshniro** [comment]
It seems vault supports multiple authentication mechanisms (OIDC, Tokens, Username Password etc), is there a recommended approach for the default authentication mechanism?
https://www.vaultproject.io/docs/auth

**Comment by membphis** [comment]
I recommend starting with something simple, such as `Tokens`.

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/5745
