### ISSUE TITLE
add AK/SK auth plugin

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1653]

**Comment by Miss-you** [comment]
有文章或者文档介绍什么是AK/SK auth吗？

**Comment by juzhiyuan** [comment]
AccessKey and SecrectKey just like AWS IAM keys?

**Comment by moonming** [comment]
yes

Thanks,
Ming Wen
Twitter: _WenMing


琚致远 <notifications@github.com> 于2020年6月12日周五 下午4:42写道：

**Comment by moonming** [comment]
AKA HMAC:  https://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/HMACAuth.html

**Comment by ChelinTsien** [comment]
assign to me

**Comment by moonming** [comment]
> assign to me

nice

**Comment by ChelinTsien** [comment]
@membphis this is ak/sk auth ，implemented according to aws v4, just badly named.

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/2192
