### ISSUE TITLE
bug: The 'config.yaml' update issue when reuseport is enabled

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#1663]
### Issue description

We recently encountered a bug:
when reuseport is enabled by default, during the running of APISIX, modify `config.yaml` and start without stopping APISIX. This resulted in some workers still using the old config, some workers using the new config,
and the old workers could not be killed by `apisix stop`

I think we need to fix it by:

1. When running `apisix start`, Check if APISIX has been running. If is running, remind to use `apisix reload`

2. `apisix reload` needs to regenerate nginx.conf according to config.yaml and then reload

3. When running `apisix start` or `apisix reload` , check the nginx.conf syntax before truely run the command.

### Environment

* apisix version (cmd: `apisix version`):
1.3
* OS:
centos7

### Minimal test code / Steps to reproduce the issue
1. apisix start
2. change conf/config.yaml
3. apisix start

**Comment by nic-chen** [comment]
@qiukeren 
I found this issue quite suit you, you just fix a similar one. would you like to fix this one too ?  ^_^

**Comment by qiukeren** [comment]
棒 我看一下

stick. let me see see.
