### ISSUE TITLE
add test cases in `t/` for admin api https access 

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1666]
I think the test coverage of add test case in shell is too low, e.g. I don't know what happens if I open https but send an http request, and it not test that the host is incorrect, it's basically the same as not testing at all.
Maybe we can merge this PR first, but test cases must added later.

_Originally posted by @moonming in https://github.com/apache/incubator-apisix/pull/1648_

**Comment by spacewander** [comment]
Consider solved
