### ISSUE TITLE
bug: make stop can't kill multi apisix server

### ISSUE THREAD

**Issue by nerowangtc** [apache/apisix#1671]
### Issue description
If I use make run to start multiple apisix server, the process shows below:
[nero@VM_42_81_centos ~/incubator-apisix]$ ps -ef | grep apisix
nero     28293     1  0 10:35 ?        00:00:00 nginx: master process /usr/local/openresty/bin/openresty -p /home/nero/incubator-apisix/ -c /home/nero/incubator-apisix/conf/nginx.conf
nero     29053     1  0 10:40 ?        00:00:00 nginx: master process /usr/local/openresty/bin/openresty -p /home/nero/incubator-apisix/ -c /home/nero/incubator-apisix/conf/nginx.conf

Now if i use make stop to stop a apisxi server , it goes ok
[nero@VM_42_81_centos ~/incubator-apisix]$ make stop
/usr/local/openresty/bin/openresty -p $PWD/ -c $PWD/conf/nginx.conf -s stop
[nero@VM_42_81_centos ~/incubator-apisix]$ ps -ef | grep apisix
nero     28293     1  0 10:35 ?        00:00:00 nginx: master process /usr/local/openresty/bin/openresty -p /home/nero/incubator-apisix/ -c /home/nero/incubator-apisix/conf/nginx.conf
nero     29362 28108  0 10:42 pts/0    00:00:00 grep --color=auto apisix

But if is make stop again, it produce a error message
[nero@VM_42_81_centos ~/incubator-apisix]$ make stop
/usr/local/openresty/bin/openresty -p $PWD/ -c $PWD/conf/nginx.conf -s stop
nginx: [error] open() "/home/nero/incubator-apisix/logs/nginx.pid" failed (2: No such file or directory)
make: *** [stop] Error 1
[nero@VM_42_81_centos ~/incubator-apisix]$ ps -ef | grep apisix
nero     28293     1  0 10:35 ?        00:00:00 nginx: master process /usr/local/openresty/bin/openresty -p /home/nero/incubator-apisix/ -c /home/nero/incubator-apisix/conf/nginx.conf
nero     29421 28108  0 10:42 pts/0    00:00:00 grep --color=auto apisix

and the another apisix process remains
I think this is a bug if some one missuse this command
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1. make run
2. make run
3. make stop

**Comment by Miss-you** [comment]
Hi, the logic for 'make stop' is based on the 'nginx.pid' file. openresty processes, rather than stopping all openresty processes, so the 'make stop' stops only a group of openresty processes

**Comment by Miss-you** [comment]
On the other hand, I think the root cause of the problem is that multiple 'make run' or 'apisix start' will start multiple groups of apisix processes, I've created a new issue and I welcome the discussion.

**Comment by Miss-you** [comment]
I think the point we should be discussing is whether multiple 'apisix starts' should only start a set of apisix processes

**Comment by nerowangtc** [comment]
In my point of view, i think in the current stage of apisix, it is meaningless to start multiple apisix server with make run command, cuz only can access one at a time

**Comment by moonming** [comment]
@nerowangtc is this issue same as https://github.com/apache/incubator-apisix/issues/1663?

**Comment by nerowangtc** [comment]
@moonming It'looks like the same

**Comment by moonming** [comment]
@nerowangtc got it, it's a bug when enabled `reuseport`, welcome PR

**Comment by membphis** [comment]
only one APISIX instance can be started now.

![image](https://user-images.githubusercontent.com/6814606/85214501-45793f00-b39e-11ea-9c49-6d78b516a624.png)

**Comment by membphis** [comment]
fixed
