### ISSUE TITLE
perf: limit plugin may lead to big redis traffic?

### ISSUE THREAD

**Issue by qiukeren** [apache/apisix#1672]
### Issue description

when open limit-count plugin, one request converts to the following 3 redis commands:

```
"ttl" "plugin-limit-count127.0.0.1route78"
"ttl" "plugin-limit-count127.0.0.1route78"
"set" "plugin-limit-count127.0.0.1route78" "1" "EX" "2"
```

on big traffic conditions, it may enlarges redis traffic.

is there any to change this?

一个限流请求对应三个redis操作，当流量很大的时候可能导致redis访问超标。
有没有办法解决？
例如采用令牌桶之类的算法？

### Environment

* apisix version (cmd: `apisix version`):1.3
* OS: OSX

**Comment by moonming** [comment]
Have you encountered the problem of redis access timeout?
If yes, I think add a token bucket locally would be a better implementation

**Comment by spacewander** [comment]
Closed as lack of response.
