### ISSUE TITLE
bug: Apache APISIX upstream domain name resolution requires a timeout

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1673]
### Issue description
If the upstream is a domain type, the address resolution of the domain does not have a timeout.
If APISIX accesses the upstream after modifying the resolution address of the domain, it still uses the IP address that was resolved before. You have to restart APISIX or reload APISIX.

### Environment

* apisix version (cmd: `apisix version`):latest
* OS:tlinux2.2

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by moonming** [comment]
https://github.com/apache/incubator-apisix/blob/master/apisix/core/utils.lua#L76 do you means this function?

**Comment by membphis** [comment]
@Miss-you do you still have this issue? if not, we can close this issue
