### ISSUE TITLE
request help: Questions about suffix matching

### ISSUE THREAD

**Issue by guoweia** [apache/apisix#1677]
### Issue description
How to implement such a routing configuration.

location ~* \.(js|css|flash|media|jpg|png|gif|dll|cab|CAB|ico|vbs|json|txt)$ {
  ...
}

### Environment

* apisix version (cmd: `apisix version`):
* OS:centos 7.2

**Comment by membphis** [comment]
here is an example:

```
{
    "uri": "/*",
    "vars": [
        ["uri", "~~", "(...|ico|txt)$"]
    ]
}
```

**Comment by spacewander** [comment]
Consider solved.
