### ISSUE TITLE
Is etcd configuration support v3 api

### ISSUE THREAD

**Issue by harrybin815** [apache/apisix#1680]
### Issue description
Is etcd configuration support v3 api

### Environment

* apisix version: v0.9
* OS: Linux

**Comment by houshunwei** [comment]
I read about etcd:
site: https://github.com/apache/incubator-apisix/blob/2c17ca7facb71ed8d3974e3f5a50dff762795723/doc/install-dependencies-cn.md

Apache APISIX 目前只支持 v2 版本的 etcd，但是最新版的 etcd (从 3.4 起)已经默认关闭了 v2 版本的功能。所以你需要添加启动参数 --enable-v2=true 来开启 v2 的功能，��目前对 v3 etcd 的开发工作已经启动，不久后便可投入使用。

**Comment by membphis** [comment]
lua-resty-etcd already supports etcd v3, welcome PR.

**Comment by spacewander** [comment]
Solved.
