### ISSUE TITLE
request help: Does the protocol support custom transformations

### ISSUE THREAD

**Issue by guoziqin** [apache/apisix#1686]
### Issue description
Whether RPC over HTTP protocol is supported
### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS:centos7

**Comment by moonming** [comment]
please take a look at [mqtt plugin](https://github.com/apache/incubator-apisix/blob/master/apisix/stream/plugins/mqtt-proxy.lua), is it good for you?

**Comment by membphis** [comment]
@guoziqin it needs some work to support custom transformations. if you need any help, please let me know.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
