### ISSUE TITLE
request help: apisix supports running as root user

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#1693]
### Issue description

Currently apisix supports running with normal user privileges. if you run as root user, then the nginx worker will be the nobody user and will fail to read conf or lua scripts.
Would like to add configuration to config.yaml to support running apisix as root user
### Environment

* apisix version (cmd: `apisix version`): latest
* OS: linux

**Comment by moonming** [comment]
`sudo apisix start` is ok in my side.
do you means add `user root` in nginx.conf?

**Comment by Miss-you** [comment]
yes, pr is here https://github.com/apache/incubator-apisix/pull/1695

**Comment by xxm404** [comment]
Hi @Miss-you apisix default home directory is `/usr/local/apisix/`,need sudo permission to start,in production environment sudo permission is strict manage,maybe apisix need support run as normal user

**Comment by membphis** [comment]
That's dangerous, I don't think APISIX will officially add this feature.

**Comment by vivid-dev** [comment]
I also encountered the same error when I used root to install and run apisix.
To solve these you have to do these:
1.access apisix return 500.             --run export prefix=`pwd`  in apisix root path
2.access apisix return 403.             -- add user root; in apisix conf

**Comment by moonming** [comment]
run Apache APISIX's workers as root is too dangerous. Every app should only get the minimum permissions

**Comment by vivid-dev** [comment]
Maybe a mandatory restriction is needed.

**Comment by Miss-you** [comment]
> run Apache APISIX's workers as root is too dangerous. Every app should only get the minimum permissions

I also agree that running the nginx worker under root is a security risk.

The above problem requires root privileges, I'll try another solution here!

**Comment by Miss-you** [comment]
On the other hand, if apisix is running in an isolated environment such as a container (e.g. docker), I think the nginx worker can use root user rights.

**Comment by Miss-you** [comment]
I think we need an Apache APISIX security configuration specification.

**Comment by membphis** [comment]
> I think we need an Apache APISIX security configuration specification.

that is another question. I have created a new issue: https://github.com/apache/incubator-apisix/issues/1740

**Comment by spacewander** [comment]
Considered solved.
