### ISSUE TITLE
request help: Does route supports to match ':authority' header of grpc?

### ISSUE THREAD

**Issue by houshunwei** [apache/apisix#1698]
### Issue description

I designed different prefix paths for different upstreams of grpc:
/path1/helloworld.Greeter/SayHello  --> upstream1
/path2/helloworld.Greeter/SayHello  --> upstream2

but grpc-client does not support path prefix:
https://github.com/grpc/grpc/issues/14900
In above grpc issue,  they recommend to use ':authority' header.
Can you give me some hint to do this using apisix?

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS:centos, docker

**Comment by moonming** [comment]
@nic-chen please take a look

**Comment by nic-chen** [comment]
I think path prefix works well in APISIX.

BUT the entire path will be passed to the backend service, like `/path1/helloworld.Greeter/SayHello`, so the backend service can handle it.

Maybe we could use [proxy-rewrite](https://github.com/apache/incubator-apisix/blob/master/doc/plugins/proxy-rewrite.md) to pass the right path `/helloworld.Greeter/SayHello` to backend.

**Comment by spacewander** [comment]
Consider solved
