### ISSUE TITLE
request help: we need separate sd(service discovery) from balance phase

### ISSUE THREAD

**Issue by ShiningRush** [apache/apisix#1700]
Now the service discovery run in default balancer, this is not a good way,
If someone want implement a custom balancer, he also need to implement sd.

**Comment by Miss-you** [comment]
Good idea.
But which or which service discovery centers should we support?

**Comment by ShiningRush** [comment]
I think it is no matter what service discovery is, all we need is extracting the logic about it, and place it before default balancer's execution.

**Comment by moonming** [comment]
@membphis what do you think?

**Comment by membphis** [comment]
agree +1. we need a simple way to support this case

**Comment by ShiningRush** [comment]
Well, I will do it recently.

**Comment by spacewander** [comment]
Solved.
