### ISSUE TITLE
After the request is sent through the gateway and the background is redirected, the port of the request address disappears

### ISSUE THREAD

**Issue by zhanghouwen** [apache/apisix#1703]
version:1.2
Example:
http://127.0.0.1:9080/A becomes  http://127.0.0.1/B，The port is gone.
This is my route :
![图片](https://user-images.githubusercontent.com/51305974/84470018-ef790d00-acb4-11ea-99c6-756a780b56b1.png)

**Comment by membphis** [comment]
@zhanghouwen we need more information.
please provide more information about your route. you can get it by curl + Admin API

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
