### ISSUE TITLE
bug: Invalid JSON encoding when exporting logs with method body 

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1710]
### Issue description
If the method body contains JSON data, then while exporting via loggers it results in invalid encoding.

```shell
curl http://127.0.0.2:9080/get --data '{"sample_payload":"hello"}'
```

```json
{
"upstream":"52.54.214.244:443",
"body":"{\\"sample_payload\\":\\"hello\\"}","method":"POST"}, -- wrong encoding
}
```

### Fix
Encode the method body before appending to the log message.

**Comment by moonming** [comment]
thanks.
welcome PR.

**Comment by spacewander** [comment]
The problem can't be reproduced in the master now.
