### ISSUE TITLE
Rate limit API calls based on consumers

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1712]
### Issue description
Is it possible to perform rate limiting based on consumers/users, in order to implement monetization for the APIs?

Example:
```shell
{
    "username": "jack"
    "quotas": [
    	{
            "route_id": "1",
            "limit": 10,
            "window": "1 week"
        },
        {
            "route_id": "2",
            "limit": 150,
            "window": "1 week"
        }
}
```

**Comment by membphis** [comment]
The consumer object is allowed to bind the plug-in, and the configuration priority of this plug-in is the highest.

https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#consumer

**Comment by sshniro** [comment]
Thank you, If I understood correctly this can feature can be implemented via creating a consumer with a `limit plugin` and assign the consumer to a `route`.

I guess the doc can be reworded to easily identify such features.

**Comment by membphis** [comment]
You understand right

**Comment by houshunwei** [comment]
> The consumer object is allowed to bind the plug-in, and the configuration priority of this plug-in is the highest.
> 
> https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#consumer

when using limit-req in consumer，limit-req limits by consumer or only by limit-req's key(ip or others)?
for example:

"limit-req": {
            "rate": 1,
            "burst": 0,
            "rejected_code": 429,
           "key":"**consumer**"
        }

**Comment by membphis** [comment]
@houshunwei you can take a look at: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/limit-req.md#attributes
