### ISSUE TITLE
bug: healthcheck bug

### ISSUE THREAD

**Issue by wwd5613** [apache/apisix#1715]
### Issue description
when press test，error log appear occasionally.

![微信截图_20200615143830](https://user-images.githubusercontent.com/2143396/84625658-50535000-af16-11ea-843b-05aea2ca8da3.png)

### Environment

* apisix version (cmd: `apisix version`):1.2
* OS:centos7.4

**Comment by moonming** [comment]
Can you provide reproduction steps?

**Comment by moonming** [comment]
what about use the 1.3 or the master version?

**Comment by wwd5613** [comment]
step:

**Comment by wwd5613** [comment]
i have not test other versions.
step:
1、add route:
{"host":"www.test.com","filter_func":"function(vars) return string.len(vars['binary_remote_addr']) == 4  end","vars":[["server_port","==","80"]],"upstream":{"retries":3,"nodes":{"192.168.0.14:80":1},"hash_on":"vars","checks":{"active":{"unhealthy":{"http_failures":2,"tcp_failures":2,"interval":1,"timeouts":3},"timeout":1,"https_verify_certificate":true,"http_path":"\/healthcheck","healthy":{"interval":2,"successes":1},"req_headers":["User-Agent: curl\/7.29.0"],"type":"http","host":"healthcheck.com","concurrency":10}},"type":"roundrobin"},"priority":3,"uri":"*"}
2、modify www.test.com hosts to apisix server ip,press test with wrk for several times.
wrk -t 16 -c 400 -d 30 --latency http://www.test.com/test
then error log appeard sometimes.

**Comment by membphis** [comment]
please update your version first. I remember we have fixed such a bug.

**Comment by membphis** [comment]
@wwd5613 any news?

**Comment by membphis** [comment]
@wwd5613 old issue, please reopen this issue if you still have this issue with latest APISIX version
