### ISSUE TITLE
Add more test cases for OpenID connect plugin

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1718]
### Issue description
An openID connect compliant identity server has been set up in the build process. The previous unit tests were written to auth0 and it lacks certain tests such as remote introspection. Therefore, additional unit test cases can be written to have full coverage of the plugin.

https://github.com/apache/incubator-apisix/blob/cd98a2bec8bee2a2cea5b0bbbb892f25e7394cf0/.travis/linux_openresty_runner.sh#L42

**Comment by moonming** [comment]
Cool, that will be great.
