### ISSUE TITLE
request help: How radix_tree to find the back-end routing address information？

### ISSUE THREAD

**Issue by cwtree** [apache/apisix#1720]
### Issue description
apisix中的radix_tree我理解是通过字符串构建一个树，在树上查找某个字符串存不存在，比如通过host来路由，那就是通过所有网站的host来构建树，基于这个树能解决的就是判断这个host在不在这颗树上，那么如何根据host找到对应的路由地址信息的呢？是通过别的存储又查了一遍的这个路由地址信息吗？那为啥不直接用哈希表呢，O(1)查找，value即为地址信息，直接路由，哈希表大一点也不存在很大的冲突风险了。

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
Please use English in the public channel, thx

**Comment by moonming** [comment]
hash can't solve prefix and regular routes

**Comment by spacewander** [comment]
Consider solved.
