### ISSUE TITLE
bug: {"error_msg":"unknown plugin [skywalking]"}

### ISSUE THREAD

**Issue by guoziqin** [apache/apisix#1722]
### Environment

* apisix version (cmd: `apisix version`): v1.3
* OS:centos7

### Minimal test code / Steps to reproduce the issue
1. "plugins": {
    "skywalking": {
      "endpoint": "http://101.200.141.199:8080",
      "sample_ratio": 1,
      "service_name": "APISIX_SERVER"
    }
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
success

### What's the expected result?
{"error_msg":"unknown plugin [skywalking]"}

**Comment by guoziqin** [comment]
How do I add Skywalking plugin

**Comment by guoziqin** [comment]
![Uploading image.png…]()

**Comment by moonming** [comment]
1.3 version not including skywalking plugin, you can try master branch
