### ISSUE TITLE
optimize: reduce the connection between APISIX and etcd

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1733]
`worker-event` is useful for this case.

![image](https://user-images.githubusercontent.com/6814606/85035957-56675c00-b1b6-11ea-9163-c8ec8ae4b105.png)

**Comment by totemofwolf** [comment]
Thanks @membphis . Here I post the context for this issue: -)

![261592489581_ pic_hd](https://user-images.githubusercontent.com/1818214/85040372-4f8f1800-b1bb-11ea-979b-66ffc8559adb.jpg)

**Comment by moonming** [comment]
Do we really need this optimization? How much optimization does it bring to APISIX?

**Comment by spacewander** [comment]
Duplicate of #1546
