### ISSUE TITLE
request help:   stream_proxy    the parameters of the proxy 

### ISSUE THREAD

**Issue by EasonHe** [apache/apisix#1736]
### Issue description

I want to set the stream  parameters of the proxy  in server  
different server ports have different parameters 

such as            

```
        proxy_connect_timeout 3s;
        proxy_timeout 10s;
```

I checked the code on github ：

```
{% if stream_proxy then %}
stream {
    lua_package_path  "$prefix/deps/share/lua/5.1/?.lua;$prefix/deps/share/lua/5.1/?/init.lua;]=]
    server {
        {% for _, port in ipairs(stream_proxy.tcp or {}) do %}
        listen {*port*} {% if enable_reuseport then %} reuseport {% end %} {% if proxy_protocol and proxy_protocol.enable_tcp_pp then %} proxy_protocol {% end %};
```

I cannot set the relevant proxy parameters

### Environment

* apisix version (cmd: `apisix version`): v1.3
* OS: centos7

**Comment by membphis** [comment]
we should support this feature, welcome PR.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by liuning89757** [comment]
@spacewander stream_configuration_snippet is not for server level configuration, is there a plan for support this feature？
