### ISSUE TITLE
bug: Without directory /tmp/apisix_cores, the system will not work

### ISSUE THREAD

**Issue by FunnySunshine520** [apache/apisix#1738]
### Issue description
if directory /tmp/apisix_cores does not exist and use "make reload" to reload the system. Then this system is not working properly

### Environment
* OS

### Minimal test code / Steps to reproduce the issue
1. Delete catalog /tmp/apisix_cores
2. Execute command: make reload

### What's the actual result? (including assertion message & call stack if applicable)
the system is not working properly

**Comment by membphis** [comment]
it has been fixed. @FunnySunshine520 if you still have a problem, pls update your APISIX to lastest version
