### ISSUE TITLE
feature: need to record which matches the current request.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1749]
It is useful when we need to record the matching URI in the monitor. eg: `prometheus`.

here is the related PR in `radixtree`: https://github.com/api7/lua-resty-radixtree/pull/42

**Comment by membphis** [comment]
@nic-chen do you have time to continue this feature?

**Comment by membphis** [comment]
https://github.com/apache/incubator-apisix/pull/1748 had been merged, we can start this feature now.

**Comment by spacewander** [comment]
Consider solved
