### ISSUE TITLE
How can i proxy to a uwsgi service?

### ISSUE THREAD

**Issue by zheng11581** [apache/apisix#1756]
### Issue description
I want to replace our nginx by apisix.
1. I have a service manage by uwsgi.
root@iZ2ze551g2b9bmm02el80nZ:/deploy/apisix/logs# netstat -ntlp |grep 17001
tcp        0      0 0.0.0.0:17001           0.0.0.0:*               LISTEN      3375/uwsgi   

2. create a route
curl http://127.0.0.1:9080/apisix/admin/upstreams/3  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -i -X PUT -d '
{
    "id": "3",
    "type": "roundrobin",
    "nodes": {
        "127.0.0.1:17001": 1
    }
}'

curl -i http://127.0.0.1:9080/apisix/admin/routes/3 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "uris": ["/api/*"],
    "methods": ["GET", "POST"],
    "upstream_id": 3
}'

3.  curl http://127.0.0.1:9080/api/api_doc
get an 502 error

2020/06/22 22:32:21 [error] 26936#26936: *59817862 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /api/api_doc HTTP/1.1", upstream: "http://127.0.0.1:17001/api/api_doc", host: "127.0.0.1:9080"
2020/06/22 22:32:25 [error] 26936#26936: *59817862 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: , request: "GET /api/api_doc HTTP/1.1", upstream: "http://127.0.0.1:17001/api/api_doc", host: "127.0.0.1:9080"

### Environment

* apisix version (cmd: `apisix version`):  1.3
* OS: Ubuntu 16.04

**Comment by membphis** [comment]
the protocol `uwsgi` is different with HTTP. you can take an example as `grpc`.

apisix does not support `uwsgi` now. welcome PR ^_^
 
```nginx
 uwsgi_pass  127.0.0.1:9090;             
 uwsgi_param UWSGI_SCRIPT demosite.wsgi;  
 uwsgi_param UWSGI_CHDIR /demosite;     
```

**Comment by spacewander** [comment]
Can be solved by https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md
