### ISSUE TITLE
feature: support etcd v3

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1767]
related issues:

https://github.com/apache/incubator-apisix/issues?q=is%3Aissue+is%3Aopen+v3+

`lua-resty-etcd` already supports etcd v3, we can support it by this feature:

https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md

**Comment by shenal** [comment]
Current data access logic does not encapsulate the internal fields set by etcd. While we tackle the v3 upgrade we should have a separate data access layer which abstracts the internal etcd API requirements and act purely as a K/V layer

**Comment by shenal** [comment]
@membphis I would like to start work on this. If no one is planning to pick this up

**Comment by membphis** [comment]
that is great, I have assigned to you ^_^

**Comment by nic-chen** [comment]
@shenal  @membphis 
`support etcd v3` is a task of summer2020( #1542 ), I think @Yiyiyimu is working on it  already. You could give your advice to him, and help review when he submit pr  : )

@Yiyiyimu What is your progress now ? Maybe you could submit a draft pr So we could see your  progress.

**Comment by shenal** [comment]
@nic-chen  Perfect !! :) 

@Yiyiyimu Let me know how I can help

**Comment by Yiyiyimu** [comment]
Hi @shenal thank you for your help! I'll submit the draft pr these days and I'll let you know whenever a discussion is needed~

**Comment by spacewander** [comment]
Solved.
