### ISSUE TITLE
optimize: fetch the request method name with integer data type

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1774]
```
ngx_http_lua_ffi_req_get_method
```

https://github.com/openresty/lua-resty-core/blob/0cc3931a6a2a206c01fe995f98fff5bdf0d8ab57/lib/resty/core/request.lua#L64

it is better performance than `ngx.req.get_method()` .

**Comment by liuhengloveyou** [comment]
What is it now?

**Comment by membphis** [comment]
> What is it now?

your question makes me confused. 

In APISIX, we mainly use `ngx.req.get_method()` now.

But I think we can use `ngx_http_lua_ffi_req_get_method` which it is better performance.
