### ISSUE TITLE
 change: remove the plugin `heartbeat`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1776]
it is useless now, we can drop it

**Comment by mtx2d** [comment]
Hi @membphis, 

Could you say more on how heartbeat is not used?
I tried directly removing the `heartbeat.lua` file in PR#1845, but many CI test failed, so this task is more than simply delete the file. 

Could you point me to the correct direction?

**Comment by membphis** [comment]
you can check the output of CI, fix them one by one.

here is an example:

```
#   Failed test 'TEST 5: get plugin heartbeat schema - status code ok'
#   at /Users/runner/work/incubator-apisix/incubator-apisix/test-nginx/lib/Test/Nginx/Socket.pm line 948.
#          got: '400'
#     expected: '200'

#   Failed test 'TEST 5: get plugin heartbeat schema - response_body - response is expected (repeated req 0, req 0)'
#   at /Users/runner/work/incubator-apisix/incubator-apisix/test-nginx/lib/Test/Nginx/Socket.pm line 1589.
#          got: '{"error_msg":"failed to load plugin heartbeat"}
# '
#     expected: '{"additionalProperties":false,"type":"object"}
# '
# Looks like you failed 2 tests of 15.
t/admin/plugins.t ................ 
```

BTW, we need to remove this flag: https://github.com/apache/incubator-apisix/blob/master/conf/config.yaml#L19

https://github.com/apache/incubator-apisix/search?q=enable_heartbeat&unscoped_q=enable_heartbeat

**Comment by membphis** [comment]
fixed
