### ISSUE TITLE
consul serviece create route limit req report 502

### ISSUE THREAD

**Issue by colder219** [apache/apisix#1780]
error log

2020/06/30 14:27:20 [error] 30366#30366: *3160677 [lua] balancer.lua:304: load_balancer(): failed to pick server: missing upstream configuration while connecting to upstream, client: 172.20.30.94, server: , request: "GET /healthcheck HTTP/1.1", host: "172.20.20.7:9080"

**Comment by membphis** [comment]
please provide more information. eg: the version of apisix, your route, etc.
