### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#1790]
### Issue description
我在upstream中配置了两个node，使用的是轮训的策略，当其中一个node服务被我关掉后，并不会影响正常的调用，会将请求转发到正常的node。 那这样健康检查是用来干什么的？健康检查不是用来检查节点是否健康吗？

### Environment

* apisix version (cmd: `apisix version`):1.3
* OS:centos7

**Comment by membphis** [comment]
you need to enable the `healthcheck` for `upstream`.

https://github.com/apache/incubator-apisix/blob/master/doc/admin-api.md#upstream
