### ISSUE TITLE
change: enabled websocket  in route

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#1791]
I think websocket should be enabled in route, not upstream. This logic is clearer. On the other hand, if we support multiple upstream, we only need to configure it once in the route, otherwise we need to configure each upstream.

**Comment by FourierX9** [comment]
Hello, I am Weiqing and I want to work on this issue as my first issue. I am trying to understand the inside logic and I will work out a  development plan in a few days.

**Comment by membphis** [comment]
@FourierX9 any news?

**Comment by FourierX9** [comment]
Sorry for replying late. It is my first time to work on an OpenSource project, and I made a few mistakes in the last couple of weeks, but I think I am on the right track now. I read some materials about Lua last week and I have set up a Linux environment last weekend. Currently, I am trying to figure out how to work on this problem. Besides my daily job takes up lots of time but I spent lots of time on this project during weekend.

**Comment by membphis** [comment]
If you are just starting to learn Lua and open source projects, then this issue is not for you because it is more difficult.

I suggest you start your first step with some simpler issues.

**Comment by membphis** [comment]
@FourierX9 if you still want to work on this issue, please let us know.

**Comment by FourierX9** [comment]
I think it is okay to change to some simpler issues. Is there anything recommended?

**Comment by membphis** [comment]
@FourierX9 https://github.com/apache/apisix/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

you can choose issue from this list ^_^

**Comment by dabue** [comment]
I will update it ，if no one else applied it.
