### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by 18210212423** [apache/apisix#1802]
Can the service URL be obtained by the gateway itself instead of manually configuring

**Comment by membphis** [comment]
can you provide an example?

**Comment by houshunwei** [comment]
> Can the service URL be obtained by the gateway itself instead of manually configuring

The Answer is `No`.  It's a gateway, not istio(manage your east-west throughput)
But you can do that by your self:
1. detect service add/delete in your own way ;
2. apply change to Route/Service in apisix;

**Comment by XW512** [comment]
> can you provide an example?

If many microservices need to be registered to the gateway, it will be very troublesome to add them manually. Is it possible to register the services to zookeeper or other registration centers, and then the gateway will read the registered services. Now we want to register nearly hundreds of interfaces to the gateway

**Comment by moonming** [comment]
> > can you provide an example?
> 
> If many microservices need to be registered to the gateway, it will be very troublesome to add them manually. Is it possible to register the services to zookeeper or other registration centers, and then the gateway will read the registered services. Now we want to register nearly hundreds of interfaces to the gateway

agreed, Apache APISIX can works with external service discovery：In addition to the built-in etcd, it also supports Consul and Nacos DNS discovery mode, and Eureka
