### ISSUE TITLE
performance: spend more time on ssl handshake

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1804]
tools: siege

```shell
# cat siegerc
verbose = true
quiet = false
gmethod = GET
limit = 500
show-logfile = true
logging = true
protocol = HTTP/1.1
chunked = true
cache = false
connection = close
concurrent = 100
time =1M
url =https://test.me/test.json
delay = 1
expire-session =false 
internet = false
benchmark = true
accept-encoding = gzip
url-escaping = true
spinner = true
unique = true

# siege  -q -R ./siegerc
```

the response of `https://test.me/test.json`:

```json
{"test":
[{"level":"info","ts":"2020-06-12T14:41:57.133+0800","caller":"raft/raft.go:811","msg":"9957321eb5db8bba [logterm: 918, index: 319] sent MsgVote request to 60921c4b9b6be29d at term 921"},
{"level":"info","ts":"2020-06-12T14:41:57.133+0800","caller":"raft/raft.go:923","msg":"9957321eb5db8bba is starting a new election at term 921"},
{"level":"info","ts":"2020-06-12T14:41:57.133+0800","caller":"raft/raft.go:713","msg":"9957321eb5db8bba became candidate at term 922"},
{"level":"info","ts":"2020-06-12T14:41:57.133+0800","caller":"raft/raft.go:824","msg":"9957321eb5db8bba received MsgVoteResp from 9957321eb5db8bba at term 922"},
{"level":"info","ts":"2020-06-12T14:41:57.133+0800","caller":"raft/raft.go:811","msg":"9957321eb5db8bba [logterm: 918, index: 319] sent MsgVote request to 45f6f42f21825e6b at term 922"},
{"level":"info","ts":"2020-06-12T14:41:57.148+0800","caller":"raft/raft.go:811","msg":"9957321eb5db8bba [logterm: 918, index: 319] sent MsgVote request to 60921c4b9b6be29d at term 922"}]
}
```

flame graph:

![image](https://user-images.githubusercontent.com/6814606/86551615-2242b800-bf78-11ea-9d3a-2b8033c471c5.png)

**Comment by membphis** [comment]
I tested it on my local computer and reproduced the problem.

Here is the flame graph of `no-reuse-session`:
[perf-no-reuse-session.svg.zip](https://github.com/apache/incubator-apisix/files/4876949/perf-no-reuse-session.svg.zip)

Here is the flame graph of `reuse-session`:
[perf-reuse-session.svg.zip](https://github.com/apache/incubator-apisix/files/4876951/perf-reuse-session.svg.zip)

When we enabled `reuse-session`, QPS increased by 10 times.

**Comment by membphis** [comment]
We need to limit the speed of the SSL handshake and control it at a suitable frequency.

**Comment by moonming** [comment]
the steps to get flame graph by `perf`:
```
sudo perf record --call-graph dwarf -p `pid` 
```

```
sudo perf script -i perf.data &> perf.unfold
```

```
git clone https://github.com/brendangregg/FlameGraph.git
./FlameGraph/stackcollapse-perf.pl perf.unfold &> perf.folded
./FlameGraph/flamegraph.pl perf.folded > perf.svg
```

**Comment by spacewander** [comment]
As the TLS session ticket is enabled since TLS 1.1, is it worthwhile to implement server side session reuse mechanism for old clients? Maybe we can suspend it until someone requires (or pays) for it.

**Comment by UnderTreeTech** [comment]
Any updates? @membphis @moonming

**Comment by membphis** [comment]
1. Add speed limit method in the handshake phase, related issue: https://github.com/apache/incubator-apisix/issues/1858
2. The client support reuse session or ticket. the APISIX has supported to store/fetch the old session now. but for `ticket` session, APISIX does not support now, related issue: https://github.com/apache/incubator-apisix/issues/1859

welcome PR

**Comment by spacewander** [comment]
The issue is replaced by #1858 and #1859.
