### ISSUE TITLE
request help: apisix v1.4 can't enable prometheus plugin

### ISSUE THREAD

**Issue by TigerGxl** [apache/apisix#1806]
### Issue description
测试环境1.4版本,源码安装,启用redirect插件正常,带上prometheus时提示 **{"error_msg":"unknown plugin [prometheus]"}** 
我简化一下不必要的接口参数,只保留相关部分
生产环境1.3版本,运行良好,对比过1.3中的数据结构,基本一致,唯独1.4版本中 **"prometheus": {}**配置无法生效
`curl "http://127.0.0.1:9180/apisix/admin/routes/abc" -X PUT -d '
{
    "plugins": {
        "prometheus": {}
    },
    "upstream": {
        "nodes": {
            "1.2.3.4:8080": 100
        },
        "hash_on": "vars",
        "type": "roundrobin"
    },
    "hosts": [
        "demo.com"
    ],
    "uris": [
        "/*"
    ]
}'`

版本
![image](https://user-images.githubusercontent.com/32395903/86581226-68b50880-bfb2-11ea-8e88-582061d34e6c.png)
当正常启用其他插件如redirect时,正常
![image](https://user-images.githubusercontent.com/32395903/86580930-f6dcbf00-bfb1-11ea-91ef-15fc24ac2c66.png)
当正常启用prometheus时,异常
![image](https://user-images.githubusercontent.com/32395903/86580780-bf6e1280-bfb1-11ea-808b-970b70d14d5e.png)

### Environment

* apisix version (cmd: `apisix version`):1.4
* OS:centos-release-7-6.1810.2.el7.centos.x86_64

**Comment by membphis** [comment]
please update your library after you use a new APISIX. eg: `make deps`

**Comment by idbeta** [comment]
I think this issue can be closed now. @spacewander
