### ISSUE TITLE
request help: how to get request body and url parameters

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/apisix#1820]
In apisix core.request it only expose apis to get/set header, get remote ip.  I wanna develop a plugin to check request signature is valid or not, How to get request body and url parameters?

**Comment by membphis** [comment]
read request body, please take a look at this document: https://github.com/openresty/lua-nginx-module#ngxreqread_body

read URL parameters, you can take a look at this document: https://github.com/openresty/lua-nginx-module#ngxreqget_uri_args

**Comment by UnderTreeTech** [comment]
I think it's better to expose apis to get body and url parameters in core.request. Users can start to develop quickly based on apisix. @membphis

**Comment by membphis** [comment]
yes, that is better. welcome PR ^_^
