### ISSUE TITLE
request help: basic-auth

### ISSUE THREAD

**Issue by laopaz** [apache/apisix#1825]
apisix version:1.2
Basic auth cannot save when adding data
![image](https://user-images.githubusercontent.com/59036981/87113381-aeb6e880-c2a0-11ea-82dc-b3718f37bfab.png)
![image](https://user-images.githubusercontent.com/59036981/87113425-c7bf9980-c2a0-11ea-95eb-88dc3c4957ca.png)

Please help me

**Comment by membphis** [comment]
you can make a try with `admin API`

here is the doc: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/basic-auth.md

**Comment by houshunwei** [comment]
There are many un-synced features between dashboard  and admin-api. 
So I recommend that:
dashboard for view;
admin-api for add/update;

**Comment by juzhiyuan** [comment]
> There are many un-synced features between dashboard and admin-api.
> So I recommend that:
> dashboard for view;
> admin-api for add/update;

The screenshot is taken on the older dashboard, please have a try on the new dashboard(master branch with Docker);

**Comment by spacewander** [comment]
Consider solved.
