### ISSUE TITLE
request help: call external service

### ISSUE THREAD

**Issue by jackwoods** [apache/apisix#1841]
### Issue description
Let's say there is a 3rd party service: https://xxx/xxx
Our subsystems want to use this service, and go through apisix, so that:
* We can use apisix to generate access tokens for the requests as the 3rd party service requires (would be a customized plugin)
* We can make use of a lot of apisix functionalities.

What will be the best practice (solution)?

**Comment by sshniro** [comment]
@jackwoods if I'm not mistaken I assume you are trying to access a third party service via apisix and to also pass or generate a token and send to this third-party service?

**Comment by membphis** [comment]
> We can use apisix to generate access tokens for the requests as the 3rd party service requires (would be a customized plugin)

I prefer this way.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
