### ISSUE TITLE
request help: log phase occurs nil pointer error log.

### ISSUE THREAD

**Issue by panhow** [apache/apisix#1842]
like the picture shown
![image](https://user-images.githubusercontent.com/34205715/87427180-f9bf5b80-c612-11ea-9549-69893d5b649e.png)

```
2020/07/11 23:18:17 [error] 4573#0: *674259867 failed to run log_by_lua*: /usr/local/apisix/lua/apisix.lua:486: attempt to index local 'api_ctx' (a nil value)
stack traceback:
	/usr/local/apisix/lua/apisix.lua:486: in function 'http_log_phase'
	log_by_lua(apisix.conf:111):2: in main chunk while logging request, client: 11.1.1.9, server: , request: "POST /HNAP1/ HTTP/1.0", host: "dd:80"
```

* apisix version (cmd: `apisix version`): 1.3
* OS:  centos7

**Comment by moonming** [comment]
Can you provide reproduction steps?

**Comment by moonming** [comment]
there is no `/usr/local/apisix/lua/apisix.lua` in APISIX 1.3 version. 
please check the version again.

**Comment by membphis** [comment]
> Can you provide reproduction steps?

@panhow we need this to confirm the bug. but I think you can upgrade your APISIX is a better way.

**Comment by panhow** [comment]
> > Can you provide reproduction steps?
> 
> @panhow we need this to confirm the bug. but I think you can upgrade your APISIX is a better way.
I check my `init.lua` file, is version: `0.4`.
I can't reproduce this error.But the error log occurs once a day on test enviroment, 20 logs per 30 seconds on production enviroment.It doesn't affect to response so far.But we stil worried about it.

**Comment by panhow** [comment]
https://github.com/apache/incubator-apisix/blob/master/apisix/init.lua#L445
is it because it return nothing.

**Comment by membphis** [comment]
> but I think you can upgrade your APISIX is a better way.

please make a try with this.

**Comment by Miss-you** [comment]
I think you should upgrade the apache apisix .

**Comment by Miss-you** [comment]
If you are using luarocks to install, you can uninstall and reinstall.

**Comment by membphis** [comment]
old issue. @panhow if you still have this issue, feel free to reopen it
