### ISSUE TITLE
Support verify ssl option parameter in Keycloak Plugin

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1855]
When Keycloak is deployed in an HTTPs environment the Keycloak plugin fails to resolve SSL certs with the following error:

```
lua ssl certificate verify error: (20: unable to get local issuer certificate),
```
To resolve this problem either the Nginx should have the following configurations

```
lua_ssl_verify_depth 2;
lua_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.pem;
```

**OR**
configure SSL verify to `false` while making the HTTP call to Keycloak server

**Comment by membphis** [comment]
> add `lua_ssl_trusted_certificate` and `lua_ssl_verify_depth`

my vote +1

**Comment by sshniro** [comment]
Agreed, but for our scenario, both are deployed in the same domain (Keycloak and APISIX). Therefore, the extra verification felt like an additional step to our setup.
