### ISSUE TITLE
request help: What to do when the downstream protocol is http and the upstream service is tcp

### ISSUE THREAD

**Issue by adugeek** [apache/apisix#1856]
### Issue description

Hello:
    Our existing services are exposed externally using tcp.

     Now, we plan to migrate the system to k8s deployment,
    
     Considering that the tcp service is not convenient to expose outside the k8s cluster,

     So we need an http gateway to perform protocol conversion operations, and connected to the back-end tcp service

     We have made a demo based on openrestry + cosocket + ffi to do protocol conversion

     Here, please teachl me how to use apisix to done this work conveniently

### Environment

* apisix version (cmd: `apisix version`):
* OS: Linux

**Comment by membphis** [comment]
> We have made a demo based on openrestry + cosocket + ffi to do protocol conversion

this way is good. if you need a better performance, we need to hack openresty, we can implement a new `cosocket_ffi` method.

Of course, for the TCP protocol, multiplexing technology is usually used, which makes the implementation difficult.

**Comment by moonming** [comment]
> > We have made a demo based on openrestry + cosocket + ffi to do protocol conversion
> 
> this way is good. if you need a better performance, we need to hack openresty, we can implement a new `cosocket_ffi` method.
> 
> Of course, for the TCP protocol, multiplexing technology is usually used, which makes the implementation difficult.

@membphis I think you misunderstood the question. @adugeek want to know how to do this job with Apache APISIX, and he want to make it easier.

**Comment by moonming** [comment]
@adugeek you can refer to the tcp-logger plugin: https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/tcp-logger.lua, which is also downstream http and upstream tcp.

**Comment by adugeek** [comment]
> @adugeek you can refer to the tcp-logger plugin: https://github.com/apache/incubator-apisix/blob/master/apisix/plugins/tcp-logger.lua, which is also downstream http and upstream tcp.

Yes ,I just want to knwon this ! TKS , ^_^.
