### ISSUE TITLE
request help: [improve] how to update apisix  in product

### ISSUE THREAD

**Issue by freesky100** [apache/apisix#1857]
### Issue description
my enviroment current use 1.0 version ,and  i want to upgrade to 1.4.1version ,how i upgrade without affecting current runtime
system.
hope have a shell or managerment endpoint , implments one key to upgrade.
also want the installation to provide the same script
### Environment

* apisix version (cmd: `apisix version`):1.0.0
* OS: centos7

**Comment by membphis** [comment]
1. you need to read the changelog of the new version, eg: 1.1, 1.2, 1.3, 1.4
2. You need to determine which changes that are not downward compatible are of your own concern.
3. for centos7, we advise you to install with RPM package way, you can install the new version, then the APISIX has upgraded to the new version.
