### ISSUE TITLE
Make admin APISIX response return JSON instead of HTML content

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#1861]
While making Admin API calls the rejected response provides HTML content. Is this the preferred way? Or can this behavior modified to return proper JSON response?

<img width="491" alt="Screenshot 2020-07-17 at 08 16 46" src="https://user-images.githubusercontent.com/13045528/87755205-e2e15a80-c806-11ea-9494-364fe84de074.png">

**Comment by membphis** [comment]
Normal response (200), APISIX returns the response body in JSON format.

Abnormal response (not 200), I think it is more appropriate to use the HTTP default response body.

**Comment by spacewander** [comment]
Surpassed by #3316
