### ISSUE TITLE
bug: redirect question

### ISSUE THREAD

**Issue by Joe123-ai** [apache/apisix#1862]
apisix version:1.3

Send request address  is  'http://127.0.0.1:9080/test',
![图片](https://user-images.githubusercontent.com/63997680/87759011-2ad0a380-c840-11ea-91ca-8e5a5069b401.png)

The address changes after redirection :http://127.0.0.1/test1.

question:after redirect,the port disappear

**Comment by membphis** [comment]
please provide more information, eg:

your apisix version
your route informatin

**Comment by membphis** [comment]
@Joe123-ai if you still have a problem, please feel free to reopen this issue.
