### ISSUE TITLE
request help: do you have any plan to add waf feature?

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/apisix#1868]
### Issue description
Do you have any plan to add waf to defend attacks like XSS, SQL Injection, WebShell?

**Comment by shuaijinchao** [comment]
Hello, APISIX already supports the IP black and white list function, please see [IP Restriction Plugin](https://github.com/apache/incubator-apisix/blob/master/doc/plugins/ip-restriction.md)

**Comment by UnderTreeTech** [comment]
I mean support anti xss, sql  injection, webshell upload and etc but not only IP Restriction. @shuaijinchao WAF is more complicated than IP Restriction.

**Comment by membphis** [comment]
@UnderTreeTech welcome PR for them

we can support IP Restriction and URI blocker now.

**Comment by moonming** [comment]
@UnderTreeTech yes, Apache APISIX need WAF features. Maybe we can add module like modsecurity?

**Comment by yimingsir** [comment]
hope apisix integrated with modsecurity

**Comment by tokers** [comment]
> hope apisix integrated with modsecurity

PRs are welcome.

**Comment by lukasmrtvy** [comment]
Proly doable with go-runner and https://github.com/corazawaf/coraza

**Comment by tao12345666333** [comment]
> Trustwave is announcing the End-of-Life (EOL) of our support for ModSecurity effective July 1, 2024. We will then hand over the maintenance of ModSecurity code back to the open-source community. 

https://www.modsecurity.org/

Maybe this is not the best option?

**Comment by Sn0rt** [comment]
@UnderTreeTech  https://apisix.apache.org/blog/2023/09/08/APISIX-integrates-with-Coraza/ 

hi. have you try coraza wasm plugin by follow this guide ?

**Comment by moonming** [comment]
Apache APISIX already support:
