### ISSUE TITLE
doc: The `doc/admin-api.md#consumer` & `doc/zh-cn/admin-api.md#consumer` doc, the consumer 'id' meaning confused.   

### ISSUE THREAD

**Issue by EdisonLiang** [apache/apisix#1873]
### Issue description
The `doc/admin-api.md#consumer` & `doc/zh-cn/admin-api.md#consumer` doc, the consumer `id` meaning confused.   

`id` miss leading `name` to `index` number while fetching one consumer details. eg:
based on docs:
`curl http://127.0.0.1:9080/apisix/admin/consumers/{id}  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' `

but should be fix it for:
`curl http://127.0.0.1:9080/apisix/admin/consumers/{name}  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

**Comment by membphis** [comment]
welcome PR

**Comment by sober-wang** [comment]
How to create a new X-API-KEY ?
Would we always use the `edd1c9f034335f136f87ad84b625c8f1` ?
If my URI include usernaem and password . What should I write the HTTP Body?

**Comment by membphis** [comment]
@sober-wang if you want to ask a new question, please create a new issue.

I do not understand your question. maybe this link can help you: 

https://github.com/apache/apisix/blob/master/conf/config.yaml#L28

**Comment by sober-wang** [comment]
> @sober-wang if you want to ask a new question, please create a new issue.
> 
> I do not understand your question. maybe this link can help you:
> 
> https://github.com/apache/apisix/blob/master/conf/config.yaml#L28

I want know the admin and viewer key  how to build. I want to try replace the key. : )

-----------------------------------------------------------------------------------------
If my URI include usernaem and password . What should I do ?
For the question , I find a document  ,other friend's can open the URL: 
[Enable basic-ath plugin](https://github.com/apache/apisix/blob/master/doc/plugins/basic-auth.md)

**Comment by juzhiyuan** [comment]
> How to create a new X-API-KEY ?
> Would we always use the `edd1c9f034335f136f87ad84b625c8f1` ?
> If my URI include usernaem and password . What should I write the HTTP Body?

No, this fixed key is ONLY for showing how to use that request, please MODIFY it when you use it in PRODUCTION env.

https://github.com/apache/apisix/blob/master/conf/config.yaml#L28

**Comment by sober-wang** [comment]
> > How to create a new X-API-KEY ?
> > Would we always use the `edd1c9f034335f136f87ad84b625c8f1` ?
> > If my URI include usernaem and password . What should I write the HTTP Body?
> 
> No, this fixed key is ONLY for showing how to use that request, please MODIFY it when you use it in PRODUCTION env.
> 
> https://github.com/apache/apisix/blob/master/conf/config.yaml#L28

I understand it. next I try multiple length of string, if I used only one string or more length string , it always pass . it need limit user enter string of key , the key length not less than 6 byte for security on internet exposure area.

**Comment by juzhiyuan** [comment]
> > > How to create a new X-API-KEY ?
> > > Would we always use the `edd1c9f034335f136f87ad84b625c8f1` ?
> > > If my URI include usernaem and password . What should I write the HTTP Body?
> > 
> > 
> > No, this fixed key is ONLY for showing how to use that request, please MODIFY it when you use it in PRODUCTION env.
> > https://github.com/apache/apisix/blob/master/conf/config.yaml#L28
> 
> I understand it. next I try multiple length of string, if I used only one string or more length string , it always pass . it need limit user enter string of key , the key length not less than 6 byte for security on internet exposure area.

Could you please add these tips to the FAQ by sending a PR?

**Comment by membphis** [comment]
> the key length not less than 6 byte for security on internet exposure area.

welcome PR, add this limitation.

**Comment by spacewander** [comment]
Surpassed by #2656
