### ISSUE TITLE
request help: How to perform Authentication Code Grant Flow with OIDC using APISIX?

### ISSUE THREAD

**Issue by mtx2d** [apache/apisix#1876]
### Issue description
I want to use APISIX as the main API gateway to perform the OIDC flow for my mobile app. 
Do we have document showing such an similar to the follow?

In the meantime, at step `I`, I would like to talk to a Redis instance for user Sessions, is this possible?
![image](https://user-images.githubusercontent.com/64316805/88002969-c298f080-cad1-11ea-8aaf-47028808475c.png)

### Environment
* apisix version (cmd: `apisix version`): 1.4.1
* OS: Kubernetes
* OAuth IdP: Google

**Comment by membphis** [comment]
@moonming do you know this? I am not familiar for this issue.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
