### ISSUE TITLE
request help: add version in http response `server` header

### ISSUE THREAD

**Issue by moonming** [apache/apisix#1877]
Apache APISIX only return `server: APISIX`, we need to add version like `server: APISIX/1.4`

**Comment by moonming** [comment]
we can remove https://github.com/apache/incubator-apisix/blob/master/bin/apisix#L241, and use lua code to add http header

**Comment by swayamraina** [comment]
@moonming I have made the required changes however I am unable to run test-cases (new to writing tests inn perl/lua).
Can you please help to understand how to setup/run TCs

thanks

**Comment by swayamraina** [comment]
@membphis can you please help here?

**Comment by membphis** [comment]
you can submit your code first. then I will help you where is the problem. ^_^ @swayamraina

**Comment by membphis** [comment]
@swayamraina https://github.com/apache/apisix/issues/2064

would you like to fix this issue?

**Comment by swayamraina** [comment]
Yes, will fix this
