### ISSUE TITLE
request help: The port disappears after redirection

### ISSUE THREAD

**Issue by Joe123-ai** [apache/apisix#1880]
### Issue description
以下是routes配置：
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/nacos-provider/provider/*",
    "upstream": {
         "nodes": {
            "127.0.0.1:8099": 1
			},
        "type": "roundrobin"
     
    }
}'

我用java写了一个重定向的后台，代码如下：
 //test
    @RequestMapping("/test")
    public ModelAndView paramRedirect() {
        return new ModelAndView("redirect:/hello.do");
    }
我在浏览器发送请求 ：http://127.0.0.1:9080/nacos-provider/provider/test
然后经网关处理后，浏览器地址变为了：https://127.0.0.1/nacos-provider/provider/hello.do;
发现问题：java后台有重定向，经apisix网关处理后，http请求变成了https，端口也消失了

### Environment
apisix version:1.3

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@Joe123-ai what's the response header of the upstream java service? Apache APISIX will not change the upstream response.

**Comment by Joe123-ai** [comment]
这是返回的header:
Content-Type →application/json;charset=UTF-8
Transfer-Encoding →chunked
Date →Tue, 21 Jul 2020 06:35:28 GMT

**Comment by Joe123-ai** [comment]
需要我做什么处理吗

**Comment by moonming** [comment]
is there has `Location:` response header?

Thanks,
Ming Wen
Twitter: _WenMing


Joe123-ai <notifications@github.com> 于2020年7月21日周二 下午2:41写道：

**Comment by Joe123-ai** [comment]
我不太明白您的意思，您能说下需要我这边怎么测试下吗
