### ISSUE TITLE
Does the stream proxy support authentication plugins?

### ISSUE THREAD

**Issue by hzqij** [apache/apisix#1886]
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "127.0.0.1:1995": 1
        },
        "type": "roundrobin"
    }
}'

curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "plugins": {
        "mqtt-proxy": {
            "protocol_name": "MQTT",
            "protocol_level": 4,
            "upstream": {
                "ip": "127.0.0.1",
                "port": 1980
            }
        }
    }
}'

does the stream proxy support authentication plugins?

thanks.

**Comment by moonming** [comment]
No, all the auth plugins are wroking in L7, and stream proxy working in L4.
By the way, how to do auth for tcp or udp request? TCP-AO？
