### ISSUE TITLE
Linux jobs in Travis-CI

### ISSUE THREAD

**Issue by odidev** [apache/apisix#1887]
Hi Team,

I am interested in adding arm64 jobs to Travis-CI.
I found that the linux jobs have been removed from .travis.yml recently. May I please know why the change has been done? I am interested in this activity because aarch64 support is fabulously increasing in the projects, and Travis-CI would be a good platform to display aarch64 support. 

### Environment Details ###
OS : Linux
Arch : arm64

**Comment by moonming** [comment]
@odidev CI is migrating from travis to github actions, and only macos is still using travis CI.
I'm not sure if arm64 is supported in github actions, but if not, we can add a test for arm64 to travis CI.
Welcome PR

**Comment by odidev** [comment]
I have modified the Github actions to trigger jobs for arm64 but facing error "Unable to locate package openresty-debug". While looking into found that the OpenResty official APT repositories provide openresty-debug and OpenResty official pre-built binary is not supported for arm64.

Link- https://openresty.org/en/linux-packages.html

So I thought of building it from the source but it is taking approx 50-60 minutes to build for arm64.

Can you please suggest your views that if you agree on building it from source or has any other approach?

**Comment by moonming** [comment]
@odidev any update?

**Comment by odidev** [comment]
@moonming 
I am currently not looking into this activity as this project is moved to Github-actions.

**Comment by spacewander** [comment]
Can we close this as Travis CI is dying?

**Comment by membphis** [comment]
yes
