### ISSUE TITLE
bug: some site pages will be garbled

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix#1889]
### Issue description
Use APISIX master branch to do reverse generation, some site pages will be garbled

### Environment

* apisix version (cmd: `apisix version`): master branch 1.4.1
* OS: centos7

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by tiger333777** [comment]
chareset utf-8

**Comment by membphis** [comment]
welcome PR,  I think this is a common feature.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
