### ISSUE TITLE
request help: signature plugin

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/apisix#1900]
Hope apisix will add signature verify plugin

**Comment by moonming** [comment]
@UnderTreeTech can you show me a example? I am not sure what signature plugin?

**Comment by UnderTreeTech** [comment]
signature = md5(query_param+body+secret+timestamp+nonce)
In p2p, 2c scenario, we should verify peer request is valid or malicious. Signature is a common way to guarantee request trustable. @moonming

**Comment by moonming** [comment]
@UnderTreeTech Is it same as https://github.com/apache/incubator-apisix/issues/1653?

**Comment by UnderTreeTech** [comment]
Yep, but less complicated, maybe just md5 or sha1.

**Comment by moonming** [comment]
got it. @UnderTreeTech Do you have time to contribute to this plugin?

**Comment by UnderTreeTech** [comment]
OK，I'll try. @moonming

**Comment by moonming** [comment]
@UnderTreeTech why close this issue and pr?anything I can help?
