### ISSUE TITLE
request help: too many redis connections while using limit-count plugin

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/apisix#1911]
I benched limit-count plugin by 100K request, 1K concurrency and found that the redis connections is much more than pool size, there are many timewait , close wait connections, Is pool connection not reusable long connection? BTW, my pool size is 100 and keepalive timeout is 10 minutes. @membphis

**Comment by membphis** [comment]
please take a look at  the option `backlog` of `tcpsock:connect`: https://github.com/openresty/lua-nginx-module#tcpsockconnect

it maybe useful for you.

**Comment by UnderTreeTech** [comment]
Gotcha, I'll reply after test it.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
