### ISSUE TITLE
bug: syslog plugin log "invalid api_ctx cannot proceed with sys logger plugin"

### ISSUE THREAD

**Issue by ACanOfGas** [apache/apisix#1935]
### Issue description
syslog plugin log "invalid api_ctx cannot proceed with sys logger plugin"

### Environment

* apisix version (cmd: `apisix version`):1.4
* OS:8.2

### Minimal test code / Steps to reproduce the issue
1.api config syslog plugin
2.error log: "invalid api_ctx cannot proceed with sys logger plugin"

### What's the actual result? (including assertion message & call stack if applicable)
.error log: "invalid api_ctx cannot proceed with sys logger plugin"

### What's the expected result?
normal access

function send_syslog_data in ngx.timer context , and not get api_ctx

**Comment by membphis** [comment]
please show us what is the conf of plugin `sys logger`

**Comment by ACanOfGas** [comment]
> please show us what is the conf of plugin `sys logger`

"syslog":{
                                "host":"192.168.100.153",
                                "max_retry_times":3,
                                "tls":false,
                                "retry_interval":100,
                                "timeout":3,
                                "buffer_duration":60,
                                "port":514,
                                "batch_max_size":1000,
                                "sock_type":"TCP",
                                "flush_limit":4096,
                                "name":"sys logger",
                                "drop_limit":1048576,
                                "pool_size":5
                            }

**Comment by membphis** [comment]
> syslog plugin log "invalid api_ctx cannot proceed with sys logger plugin"

sorry for my delayed reply, we need a full error log of this error.

**Comment by membphis** [comment]
@ACanOfGas you can make a try with this PR: https://github.com/apache/apisix/pull/2002
