### ISSUE TITLE
request help: build-in etcd service discovery example

### ISSUE THREAD

**Issue by to2false** [apache/apisix#1952]
### Issue description
> works with external service discovery：In addition to the built-in etcd, it also supports Consul and Nacos DNS discovery mode, and Eureka

Is there an example of using build-in etcd service discovery?
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
Discovery service protocol: https://etcd.io/docs/v3.4.0/dev-internal/discovery_protocol/

**Comment by to2false** [comment]
> Discovery service protocol is only used in cluster bootstrap phase, and cannot be used for runtime reconfiguration or cluster monitoring.

I mean how to register service like [consul dns](https://gist.github.com/moonming/32aed4922ea428db1abfe2edfd730b3a) using with apisix.

I did not find an example in the doc.

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/29b15892b7aebf98f5724336276686496a15bfe4/doc/zh-cn/admin-api.md#route

you can take a look at this doc.

![image](https://user-images.githubusercontent.com/6814606/89368257-a752f580-d70d-11ea-9c01-90d88d708f09.png)

**Comment by to2false** [comment]
@membphis Thanks reply.

Implement like a discovery service through Admin APIs seems to need a store service-bound id, I will implement it in this way first.

Or is there an easier way to do?

**Comment by membphis** [comment]
> Or is there an easier way to do?

if you using etcd as a discovery way, that is the right way. 
it almost the same as https://etcd.io/docs/v3.4.0/dev-internal/discovery_protocol/ .
