### ISSUE TITLE
feature: accept ":" in id?

### ISSUE THREAD

**Issue by jackwoods** [apache/apisix#1955]
### Issue description
Is it possible that we can accept **":"** in id? 
Then we can use it for namespace delimiter.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Source code
```lua
local id_schema = {
    anyOf = {
        {
            type = "string", minLength = 1, maxLength = 64,
            pattern = [[^[a-zA-Z0-9-_]+$]]
        },
        {type = "integer", minimum = 1}
    }
}
```

**Comment by moonming** [comment]
LGTM
welcome PR to add this feature

**Comment by jackwoods** [comment]
https://github.com/apache/incubator-apisix/pull/1959
