### ISSUE TITLE
bug: return fail if failed to load SSL certificate by SNI

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1957]
https://github.com/apache/incubator-apisix/blob/master/apisix/init.lua#L162

only `warn` message is not enough.

**Comment by membphis** [comment]
@nic-chen do you have time to handle this bug?

**Comment by nic-chen** [comment]
@membphis  Ok, let me deal with this issue.

**Comment by membphis** [comment]
@nic-chen I will handle this bug
