### ISSUE TITLE
need test case: redirect plugin

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1962]
https://github.com/apache/incubator-apisix/pull/1958/files#diff-cdaf7c2893523e3e57d9b439cb5d2b23R133

**Comment by liuhengloveyou** [comment]
what is it ? need to close?

**Comment by membphis** [comment]
it has been fixed https://github.com/apache/apisix/commit/ce6dc643ddc92056deb035893df0831c049c042d
so we can close this issue
