### ISSUE TITLE
request help: When using the RS256 algorithm, how to set the PUBLIC KEY and RSA PRIVATE KEY of the jwt-auth plugin？

### ISSUE THREAD

**Issue by hzqij** [apache/apisix#1966]
### Issue description
When using the RS256 algorithm, how to set the PUBLIC KEY and RSA PRIVATE KEY of the jwt-auth plugin？
![image](https://user-images.githubusercontent.com/29828306/89103354-c28ae000-d443-11ea-9a88-4e173a41a2c1.png)

![image](https://user-images.githubusercontent.com/29828306/89103424-74c2a780-d444-11ea-8b7e-cbb5884fccaf.png)

### Environment

* apisix version (cmd: `apisix version`): 1.4.1
* OS: centos 7.2

**Comment by membphis** [comment]
please take a look at the Admin API doc. we focus on the new dashboard now.

https://github.com/apache/apisix/blob/master/doc/plugins/jwt-auth.md#attributes

**Comment by spacewander** [comment]
Solved by #2594
