### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#1972]
### Issue description
When I log in Kafka, the following error occurs:
![1](https://user-images.githubusercontent.com/29362652/89152923-81571500-d596-11ea-930b-f68ee1e84c5b.png)
When Lua gets the KAFka IP, it does not resolve it through /etc/hosts. Why? Is there a solution?
### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS:centos7

**Comment by membphis** [comment]
Nginx will never use /etc/hosts to resolve DNS.

Nginx parses the domain always by DNS server, please take a look at: http://nginx.org/en/docs/http/ngx_http_core_module.html#resolver.
