### ISSUE TITLE
request help: want use https and wss ,how should it be configured

### ISSUE THREAD

**Issue by qianglu1989** [apache/apisix#1973]
### Issue description
how should it be configured   https and wss 

1、now,i create upstream

![image](https://user-images.githubusercontent.com/8486184/89159056-8d949f80-d5a1-11ea-8be3-3d32a3269c8f.png)

2、router
![image](https://user-images.githubusercontent.com/8486184/89159120-a69d5080-d5a1-11ea-8aa6-f3e29117d235.png)

3、  https is ok，but how can iconfig wss, example wss port is 10800 (wss://gw-test.xxx.cn/ws) ,please help me ,3q

### Environment

* apisix version (cmd: `apisix version`): 1.4.0
* OS: linux

**Comment by membphis** [comment]
you need to set SSL certificate first. https://github.com/apache/apisix/blob/29b15892b7aebf98f5724336276686496a15bfe4/doc/zh-cn/admin-api.md#ssl

**Comment by qianglu1989** [comment]
> you need to set SSL certificate first. https://github.com/apache/apisix/blob/29b15892b7aebf98f5724336276686496a15bfe4/doc/zh-cn/admin-api.md#ssl

no,here i don't set it, because here is https -> nginx  ->  apisix. so how  configure it wss

**Comment by membphis** [comment]
I think you can use `wss` after you set the SSL certificate.

**Comment by qianglu1989** [comment]
> I think you can use `wss` after you set the SSL certificate.

已经设置了，前面还有个nginx, 我换个域名访问wss 使用都没问题。现在我想直接使用apisix 的域名来进行转发，应该怎么配置

**Comment by membphis** [comment]
> 现在我想直接使用apisix 的域名来进行转发，应该怎么配置

I do not know what do you need. Can you provide more detail?

**Comment by spacewander** [comment]
Closed as lack of response.
