### ISSUE TITLE
apisix latest version with skywalking  register failed

### ISSUE THREAD

**Issue by samunbest** [apache/apisix#1974]
apache/skywalking-oap-server:7.0.0-es7 
apisix version latest deploy by DOCKER

[lua] client.lua:118: register_service_instance(): skywalking service instance register failed, response code:500, context: ngx.timer, client: 180.167.84.154, server: 0.0.0.0:9080

**Comment by samunbest** [comment]
[lua] client.lua:118: register_service_instance(): skywalking service instance register failed, response code:500, context: ngx.timer, client: 127.0.0.1, server: 0.0.0.0:9900

**Comment by membphis** [comment]
@moonming please take a look

**Comment by 2465566** [comment]
any update?  this issue also occurred in Apisix 1.4 running in docker.

**Comment by samunbest** [comment]
> any update? this issue also occurred in Apisix 1.4 running in docker.
while i also have some troubles with apisix deploy in docker, it goes well when i install by rmp
