### ISSUE TITLE
bug: cors when the request is a preflight request we shouldn't set the Access-Control-Allow-Headers *

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/apisix#1983]
### Issue description
when the request is a preflight request we shouldn't set the Access-Control-Allow-Headers, if we set the Access-Control-Allow-Headers * we will get a error from google chrome.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### My way to solve this
```lua

local function set_allow_headers_options_method(conf,ctx)

    local allow_headers = conf.allow_headers

    if allow_headers == "*" or allow_headers == "**" then

        local headers = core.request.header(ctx,"Access-Control-Request-Headers")

        if headers then
            ngx.header["Access-Control-Allow-Headers"] = headers
        end

    end

end

        if ctx.var.request_method == "OPTIONS" then
            set_allow_headers_options_method(conf,ctx)
            return 200
        end

```

**Comment by membphis** [comment]
@ShiningRush please confirm if it is a bug

**Comment by ShiningRush** [comment]
What version are you using?

**Comment by OnlyPiglet** [comment]
@ShiningRush 
the cors plugin has returned all needing CORS headers,but if the allow_headers is * ,the current cors will set 
Access-Control-Request-Headers:* ，this will be failed when the request is a preflight request.

the currnet code of cors

```lua
local function set_cors_headers(conf, ctx)
    local allow_methods = conf.allow_methods
    if allow_methods == "**" then
        allow_methods = "GET,POST,PUT,DELETE,PATCH,HEAD,OPTIONS,CONNECT,TRACE"
    end

    core.response.set_header("Access-Control-Allow-Origin", ctx.cors_allow_origins)
    core.response.set_header("Access-Control-Allow-Methods", allow_methods)
    core.response.set_header("Access-Control-Allow-Headers", conf.allow_headers)
    core.response.set_header("Access-Control-Max-Age", conf.max_age)
    core.response.set_header("Access-Control-Expose-Headers", conf.expose_headers)
    if conf.allow_credential then
        core.response.set_header("Access-Control-Allow-Credentials", true)
    end
end

    if ctx.var.request_method == "OPTIONS" then
        return 200
    end
```
we should set the  Access-Control-Allow-Credentials *,this will cause a cors error,I am sorry I didn't has a capture of this error.
we should set the Access-Control-Allow-Credentials which are the same of the preflight request like this

```lua
local function set_allow_headers_options_method(conf,ctx)

    local allow_headers = conf.allow_headers

    if allow_headers == "*" or allow_headers == "**" then

        local headers = core.request.header(ctx,"Access-Control-Request-Headers")

        if headers then
            ngx.header["Access-Control-Allow-Headers"] = headers
        end

    end

end

```
```lua
        if ctx.var.request_method == "OPTIONS" then
            set_allow_headers_options_method(conf,ctx)
            return 200
        end
```

**Comment by ShiningRush** [comment]
Fine, I got it.
This not a bug, just a CORS specification, you can not set either `Access-Control-Allow-Origin`, `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, `Access-Control-Expose-Headers` to `*` when `Access-Control-Allow-Credentials` be `true`.
the cors plugin can use `**` in this situation at parameter of `allow_origins` and `allow_methods`, this is because plugins convert `**` to concrete values, such as "origin.com", "GET,POST" etc. But the plugin does not implement `**` for `allow_headers`, `expose_headers`, so you should configure concrete values instead of `*`.

**Comment by ShiningRush** [comment]
I will add some validations for plugin, and more some tips in doc.

**Comment by OnlyPiglet** [comment]
@ShiningRush 
ok,sometimes it's usually be set * or **  ,so it's better to add convert logic as allow_origins and allow_methods of allow_headers, expose_headers

**Comment by ShiningRush** [comment]
I am sorry to say it is hard to implement it for `allow_headers`, `expose_headers`, because the plugin does not know what header should be allowed.The request does not contain the info about both them.

**Comment by OnlyPiglet** [comment]
@ShiningRush when it's a preflight request it will contains Access-Control-Request-Headers this should be the allow_headers ,this is what I have done 

        if ctx.var.request_method == "OPTIONS" then
            set_allow_headers_options_method(conf,ctx)
            return 200
        end

**Comment by ShiningRush** [comment]
Yes, preflight request will contain `Access-Control-Request-Headers`, but normal request does not contain this header( 
if i remember correctly  ), so we can not reply `ACAH` in normal request, it will cause browser check failed.
Are your code work fine in chrome?

**Comment by OnlyPiglet** [comment]
yes because I will check if this is a preflight request

**Comment by spacewander** [comment]
According to the spec, it looks like that `Access-Control-Allow-Method` and `Access-Control-Allow-Headers` are only for preflight request.
https://fetch.spec.whatwg.org/#http-access-control-allow-methods
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers

So the only thing need to be restricted is `Access-Control-Expose-Headers`. For example, we can require `Access-Control-Expose-Headers` not to be `*` when `Access-Control-Allow-Credentials: true`.

**Comment by OnlyPiglet** [comment]
@spacewander 
Yes I agree with you totally,the Access-Control-Expose-Headers can't be * when Access-Control-Allow-Credentials: true is true.

**Comment by ShiningRush** [comment]
I have a try on chrom.It is seem like browser will just check `Access-Control-Allow-Origin` in normal request, so we could implement `**` for `allow_headers`, and add a validation that  forbidding use`*` in option  when `allow_credential`  is true.

**Comment by eminoda** [comment]
CORS Plugins: 
````
"cors": {
      "allow_credential": false,
      "allow_headers": "Content-Type,Fetch-Mode,accept", // fix IE CORS
      "allow_methods": "*",
      "allow_origins": "*",
      "disable": false,
      "expose_headers": "*",
      "max_age": 5
     #}
````
Http Methods Options preflight request received "access-control-allow-headers: *", allow_headers is not working.

**Comment by ShiningRush** [comment]
the plugin codes look fine, can you sure your plugin setting is as same as you posted?(you can call admin api to check it)
