### ISSUE TITLE
bug: plugins limit-conn  repeatedly leaving key

### ISSUE THREAD

**Issue by ACanOfGas** [apache/apisix#1986]
### Issue description

When configuring the limit-conn plugin for both global and route rules,  ctx.limit_conn,ctx.limit_conn_key, ctx.limit_conn_delay
will be override.  in log phase, Repeatedly releasing route key and global rule key not release

### Environment

* apisix version (cmd: `apisix version`):1.4
* OS:centos8.1

### Minimal test code / Steps to reproduce the issue

1. configure the limit-conn plugin for both global and route rules 
2. Access trigger upper global limmit conn bound
3. Follow-up requests are all denied

route-config

```
"plugins":{
    "anti-replay":{
        "validperiod":300,
        "enable":false
    },
    "proxy-rewrite":{
        "uri":"/enlink/api/client/conf/v2/qrList",
        "scheme":"https"
    },
    "limit-conn":{
        "conn":10,
        "rejected_code":510,
        "burst":10,
        "default_conn_delay":1,
        "key":"remote_addr"
    }
}
```

global-config

```
{
    "value":{
        "plugins":{
            "limit-conn":{
                "conn":50,
                "burst":2,
                "rejected_code":550,
                "key":"remote_addr",
                "default_conn_delay":1
            }
        },
        "id":"f82088a019d34f929e552d44a23555ff"
    },
    "createdIndex":204,
    "key":"/apisix/global_rules/f82088a019d34f929e552d44a23555ff",
    "modifiedIndex":204
}
```

### What's the actual result? (including assertion message & call stack if applicable)

Follow-up requests are all denied

### What's the expected result?

normal access

**Comment by membphis** [comment]
@ACanOfGas you can make a try with new PR: https://github.com/apache/apisix/pull/1994

I think it can work in normally now.
