### ISSUE TITLE
change: reenable `proxy-cache`, `proxy-mirror` by default in APISIX

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1987]
Talked with @moonming right now, will enable proxy-cache, proxy-mirror by default in APISIX.
For most users, it is easier to use API​​SIX.

Add a new document named What are the best practices for benchmarking APISIX?, tell the user how do benchmark for APISIX.

related discuss: https://github.com/apache/apisix/pull/1968#issuecomment-668535203

**Comment by membphis** [comment]
```diff
diff --git a/conf/config.yaml b/conf/config.yaml
index 869c26a8..f8673ada 100644
--- a/conf/config.yaml
+++ b/conf/config.yaml
@@ -175,8 +175,8 @@ plugins:                          # plugin list
   - authz-keycloak
   - uri-blocker
   - request-validation
-  # - proxy-cache
-  # - proxy-mirror
+  - proxy-cache
+  - proxy-mirror

 stream_plugins:
   - mqtt-proxy

**Comment by dabue** [comment]
I'll update it.
