### ISSUE TITLE
bug: custom plugin does not work

### ISSUE THREAD

**Issue by spjiang** [apache/apisix#1990]
### Issue description
自定义插件

### Environment
version：1.4.1
* apisix version (cmd: `apisix version`):
* OS: macos 10.14.4

### Minimal test code / Steps to reproduce the issue
1.
![image](https://user-images.githubusercontent.com/8924638/89295063-ff004b00-d692-11ea-91f3-45f21dfcf879.png)

2.
![image](https://user-images.githubusercontent.com/8924638/89295157-26571800-d693-11ea-991a-9d210db705a4.png)

3.
curl http://127.0.0.1:9080/apisix/admin/global_rules -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'                                            19:47:34  ☁  master ☀
{"node":{"nodes":[{"value":{"plugins":{"user-limit-count":{}}},"createdIndex":38,"key":"\/apisix\/global_rules\/1","modifiedIndex":38}],"modifiedIndex":13,"createdIndex":13,"key":"\/apisix\/global_rules","dir":true},"action":"get"}
![image](https://user-images.githubusercontent.com/8924638/89295197-37078e00-d693-11ea-8e32-b71614f2cad6.png)

全局插件没有生效

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/89319056-34686100-d6b2-11ea-92b9-535538f1441a.png)

this line is wrong. the return value means `code and body` for `access` phase.

`local code, body = phase_fun(plugins[i + 1], api_ctx)`: https://github.com/apache/apisix/blob/master/apisix/init.lua#L130

**Comment by membphis** [comment]
@spjiang close this issue. if you still have a problem, please feel free to reopen this issue.
