### ISSUE TITLE
remove all `incubator` in doc and source code

### ISSUE THREAD

**Issue by membphis** [apache/apisix#1999]
need to remove `incubator`, mainly is about the doc.

* https://github.com/apache/incubator-apisix
* /API_ASPIX/incubator-apisix/
* git://github.com/apache/incubator-apisix

**Comment by jie123108** [comment]
I want to fix it.

**Comment by jie123108** [comment]
@membphis 
In README.md and README_CN.md. 
`wget http://www.apache.org/dist/incubator/apisix/1.4/apache-apisix-1.4-incubating-src.tar.gz`
I tested this link and found it to be a 404. Removing `incubator` is also a 404. How to solve this problem?
`wget http://www.apache.org/dist/apisix/1.4/apache-apisix-1.4-src.tar.gz`

**Comment by membphis** [comment]
> http://www.apache.org/dist/incubator/apisix/1.4/apache-apisix-1.4-incubating-src.tar.gz

you can find the file in here: https://downloads.apache.org/apisix/

**Comment by jie123108** [comment]
Okay, thanks. I found it.
