### ISSUE TITLE
request help: Parameters in path don't work as expected

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#2008]
### Issue description
Parameters in path as described here https://github.com/api7/lua-resty-radixtree/issues/37 don't seem to work as expected.
For example I would expect request "/foo/1/bar" to be accepted by route with "uri": "/foo/:id/bar", and request "/foo/bar" rejected. It turns out both requests are matched by the route, like if the colon is functioning as the "*"

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: osx

**Comment by membphis** [comment]
I will make a test in `resty-radixtree` for this case.

**Comment by membphis** [comment]
I added a test case in `resty-radixtree`, it works fine with the case you provided.

https://github.com/api7/lua-resty-radixtree/pull/49

We will make a try in APISIX later.

**Comment by membphis** [comment]
we can update the `resty-radixtree` release new version
