### ISSUE TITLE
request help:  How are worker_processes configured

### ISSUE THREAD

**Issue by qianglu1989** [apache/apisix#2016]
### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: linux

how can configured  `worker_processes`
my config.yml
![image](https://user-images.githubusercontent.com/8486184/89600951-e14f0380-d895-11ea-9c16-5bd9ba958c63.png)

but worker_processes  is not working , in nginx.conf `worker_processes`  always  auto

pelase help me  3q

**Comment by spacewander** [comment]
Look like we could not customize worker number yet.
