### ISSUE TITLE
bug: limit-conn cache never update

### ISSUE THREAD

**Issue by JoeyLee0201** [apache/apisix#2019]
### Issue description
Hello, 

I have a consumer who use limit-conn plugin and set value of conn to 10,

But when I update the value of conn, like 20. It will still limit connection number to 10.

I find there is a cache mechanism in this plugin like:

![image](https://user-images.githubusercontent.com/12098805/89635146-22b4d280-d8d9-11ea-8e51-2414a50f655d.png)

How could I fix this problem?

Also, what's the structure of lim?

Could I get the value of conn in lim, thus I can compare like:

if lim.conn ~= conf.conn then
      ....

### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: docker image

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by JoeyLee0201** [comment]
In case code image doesn't, here is cache mechanism below:

local lim, err = core.lrucache.plugin_ctx(plugin_name, ctx,
                                              create_limit_obj, conf)

**Comment by JoeyLee0201** [comment]
I have solve this problem.
just " lim:set_conn(conf.conn)" to make sure the value of conn is the newest.

see doc about "resty.limit.conn" for more information:
https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/conn.md#set_conn

**Comment by membphis** [comment]
Do we need to update the source code of the plugin `limit-conn` ?

**Comment by JoeyLee0201** [comment]
Yes,  it's a bug  which should be treat seriously. And I don't think my way is the best one.
The cache will be update in lrucache.lua，if apisix find conf.version is not the same with obj version.
But, the version seems not be updated when changing consumer's plugins. 

So, I think a good way is to make sure conf.version will be update, thus when load cache, it will know context has been changed, then create a new limit object.

It's just my suggestion, actually I don't know much detail behind the program, maybe there exist another better way.

**Comment by membphis** [comment]
@JoeyLee0201 https://github.com/apache/apisix/pull/2028

I submitted a PR to fix this issue. Welcome to make a try.
