### ISSUE TITLE
feature: Request ID plugin to uniquely identify requests in APISIX

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#2022]
### Issue description
When a client requests an API error I want to find the relevant request in the access logs. Is there a way to provide unique id. for each request and append in the request header?

**Comment by membphis** [comment]
we can implement a plugin for this feature.

1. check if the request contains `X-Request-Id`
2. if not we'll generate a UUID as `request_id`
3. set to proxy_header and response header
4. write `request_id` to access log

**Comment by sshniro** [comment]
Thank you, I'll create a request-id plugin for this use case and send a PR, and I assume this plugin should have the highest priority number?

**Comment by membphis** [comment]
> and I assume this plugin should have the highest priority number?

yes, we need to implement it in this way.
