### ISSUE TITLE
bug: comparing etcd key's modifiedIndex as a number may cause an error when access to prometheus exporter api

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#2025]
### Issue description

When any upstream node uses domain name as host, modifiedIndex of the etcd key for upstream is modifed to string in the domain name resolution caching logic:
https://github.com/apache/apisix/blob/master/apisix/init.lua#L251

At this time, comparing the etcd key's modifiedIndex as a number will cause an error:
https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L181

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos 7

### Minimal test code / Steps to reproduce the issue
1.  use domain name as host for an upstream node.
2. resolve domain name to another IP
3. access prometheus exporter api

### What's the actual result? (including assertion message & call stack if applicable)
cause an error

### What's the expected result?
normal response

**Comment by membphis** [comment]
@nic-chen do you have time to fix this bug?

**Comment by nic-chen** [comment]
> @nic-chen do you have time to fix this bug?

sure
