### ISSUE TITLE
failed to fetch service configuration by id

### ISSUE THREAD

**Issue by lchoua** [apache/apisix#2041]
### Issue description
Hello everyone, I am using APISIX with it's docker version. I have already created an Upstream, a Service, a Route and a Consumer. 
I have running etcd in another container.
When I make a request to the Route, that I created, sometimes I get a 200 status code but other times I get a 404 status code because of the APISIX.The error that I found in the error.log file is:
```
2020/08/10 19:56:42 [error] 55#55: *3070154 [lua] init.lua:354: http_access_phase(): failed to fetch service configuration by id: -----, client: 10.0.0.35, server: , request: "GET /ping HTTP/1.1", host: "10.0.0.9:29080"
```
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: CentOS-7

**Comment by membphis** [comment]
please provide your conf, eg: the service with id `-----`

if possible, you can provide all of the your conf.

**Comment by lchoua** [comment]
The service configuration is:
```
"value": {
                    "upstream_id": "****",
                    "plugins": {
                        "limit-count": {
                            "time_window": 60,
                            "count": 1,
                            "rejected_code": 503,
                            "key": "remote_addr",
                            "policy": "local"
                        },
                        "key-auth": {}
                    },
"id": "-----"
},
```
and the upstream configuration is:
```
"value": {
                    "type": "roundrobin",
                    "nodes": {
                        "https://www.mymicroservice.com": 1
                    },
                    "hash_on": "vars",
                    "id": "****"
                },
```

**Comment by membphis** [comment]
Can you provide a real example of which we can reuse it directly?

we can set the real route and service into etcd and try to confirm where is the bug.

waiting for your conf.

**Comment by moonming** [comment]
@lchoua ping

**Comment by spacewander** [comment]
Closed as lack of response.
