### ISSUE TITLE
feat: We can add the hostname field to prometheus

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2042]
### Issue description
We can add the hostname field to prometheus

### Environment

* apisix version 1.5:
* OS:

By way of environment variables, We can get the host name through the environment variable `HOSTNAME` in k8s.

1. need to modify apisix script, add export `env HOSTNAME;` in https://github.com/apache/apisix/blob/master/bin/apisix;

2. get hostname from env in the plugin named prometheus (https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua);

**Comment by nic-chen** [comment]
we could get host from `vars`. but prometheus can store only numbers as value.

**Comment by gxthrj** [comment]
> we could get hostname from `vars`. but prometheus can store only numbers as value.

hi, @nic-chen 
I don’t quite understand what you said `prometheus can store only numbers as value`
But we can add a label named host for each metric, such as this
```lua
-- Take metrics.status as an example
...
metrics.status = prometheus:counter("http_status",
        "HTTP status codes per service in APISIX",
        {"code", "service", "node", "host"})
...
metrics.status:inc(1, vars.status, service_name, balancer_ip, host_name)
...

```

**Comment by nic-chen** [comment]
> > we could get hostname from `vars`. but prometheus can store only numbers as value.
> 
> hi, @nic-chen
> I don’t quite understand what you said `prometheus can store only numbers as value`
> But we can add a label named host for each metric, such as this
> 
> ```lua
> -- Take metrics.status as an example
> ...
> metrics.status = prometheus:counter("http_status",
>         "HTTP status codes per service in APISIX",
>         {"code", "service", "node", "host"})
> ...
> metrics.status:inc(1, vars.status, service_name, balancer_ip, host_name)
> ...
> ```

good idea

**Comment by Gerrard-YNWA** [comment]
> > we could get hostname from `vars`. but prometheus can store only numbers as value.
> 
> hi, @nic-chen
> I don’t quite understand what you said `prometheus can store only numbers as value`
> But we can add a label named host for each metric, such as this
> 
> ```lua
> -- Take metrics.status as an example
> ...
> metrics.status = prometheus:counter("http_status",
>         "HTTP status codes per service in APISIX",
>         {"code", "service", "node", "host"})
> ...
> metrics.status:inc(1, vars.status, service_name, balancer_ip, host_name)
> ...
> ```

Hello, any progress in this issue?  
We have a similar  for collecting different apisix instance's metrics in a separate grafana panel, like `apisix_nginx_http_current_connections`.
However, metrics from the `/apisix/prometheus/metrics` outputs without any label about instance infomation, which is quite inconvenient to find the data comes from which instance.
If `apisix` can add a label like `host_name` to every metrics, I think it will be helpful.

**Comment by tokers** [comment]
@nic-chen @gxthrj

**Comment by nic-chen** [comment]
@Gerrard-YNWA  we have supported hostname in metrics like 
`apisix_node_info{hostname="apisix-deployment-588bc684bb-zmz2q"} 1`

not  label for each metrics

**Comment by membphis** [comment]
it seems that we can close this issue, all right?

**Comment by Gerrard-YNWA** [comment]
@nic-chen Since no extra host label for each metric's output, is there a way we can merge the two separate metric like: `apisix_nginx_http_current_connections{state="active"} 100` and `apisix_node_info{hostname="apisix-deployment-588bc684bb-zmz2q"} 1` into one `apisix_nginx_http_current_connections{state="active", hostname="apisix-deployment-588bc684bb-zmz2q"} 100` via `promsql` ?
