### ISSUE TITLE
bug: Failed to query DNS server when proxying HTTPS upstream traffic

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#2044]
### Issue description
When proxying traffic to https based upstream, we are getting the following error. We are using the proxy rewrite plugin to create an HTTPs based traffic. Can we know why APISIX is checking for UDP based DNS resolver here?

```
2020/08/03 09:45:13 [error] 37#37: *14632 [lua] init.lua:167: parse_domain(): failed to parse domain for 
domain_name_removed.com, error:failed to query the DNS server: failed to receive reply from UDP server 
127.0.0.11:53: timeout, client: 172.21.0.1, server: , request: "GET /apis/sr HTTP/1.1", host: "localhost:9080"
```

**Comment by membphis** [comment]
in `balancer` phase, it only supports `IP` address, we have to parse the domain to IP in `access` or `rewrite` phase.

and we have to parse it on Lua land. the Nginx can not help us. here is the doc link: https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_current_peer

**Comment by membphis** [comment]
you need to set the right DNS resolver for APISIX [1]

[1] https://github.com/apache/apisix/blob/master/conf/config.yaml#L90

**Comment by sshniro** [comment]
Thanks for the detailed explanation.
