### ISSUE TITLE
request help: Dashboard can not change password

### ISSUE THREAD

**Issue by qianglu1989** [apache/apisix#2047]
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: linux
step
1、 clone github
2、init code
3、yarn run serve
App running at:
[0]   - Local:   http://localhost:8080/ 
[0]   - Network: http://172.17.13.109:8080/

when i want change password, is not working

![image](https://user-images.githubusercontent.com/8486184/89981584-adfde180-dca6-11ea-974b-59b0e2c5c959.png)

how can i set my  username and pwd

**Comment by juzhiyuan** [comment]
There has NO username & password for both the old & newer dashboard, and this PR is working on this.

https://github.com/apache/apisix-dashboard/pull/330
