### ISSUE TITLE
request help: unsupported subsystem: stream

### ISSUE THREAD

**Issue by wjh549628** [apache/apisix#2048]
### Issue description
1 conf/config.yaml   apisix.config_center use yaml
![image](https://user-images.githubusercontent.com/37922630/89990392-e73d4e00-dcb4-11ea-937c-b7dce7bf55e1.png)

2 conf/config.yaml   stream_proxy enable
![image](https://user-images.githubusercontent.com/37922630/89990604-32576100-dcb5-11ea-8459-ca6438d516db.png)

3 apisix.yaml
![image](https://user-images.githubusercontent.com/37922630/89990881-937f3480-dcb5-11ea-9dff-61ff94ea2170.png)

4 sudo make init & sudo make run
![image](https://user-images.githubusercontent.com/37922630/89990943-aa258b80-dcb5-11ea-9ca3-68a37c217c72.png)

### Environment

* apisix version (cmd: `apisix version`):v1.4
* OS:MACOS

**Comment by membphis** [comment]
welcome PR for supporting `stream` when enabled standalone model.
