### ISSUE TITLE
request help: How to set the timeout period for waiting for upstream response in apisix?

### ISSUE THREAD

**Issue by zhoujun24** [apache/apisix#2049]
### Issue description
After the client sends the request, the processing time of the back-end service exceeds 60s, causing Apisix to return 504

![image](https://user-images.githubusercontent.com/19777017/89993720-b9a6d380-dcb9-11ea-89d6-dea4494e0537.png)
![image](https://user-images.githubusercontent.com/19777017/89993956-08ed0400-dcba-11ea-862d-d22c27f0da8a.png)

### Environment

* apisix version (cmd: `apisix version`): 1.1
* OS: CentOS 7.4

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream

you can set the `timeout` for `upstream` object

**Comment by membphis** [comment]
> * apisix version (cmd: `apisix version`): 1.1

please upgrade your APISIX first.

**Comment by zhoujun24** [comment]
@membphis 
Thanks for your guidance, my problem is solved.
