### ISSUE TITLE
request help:  what is the recommended way to split access log in k8s pod? for example, split by day

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#2051]
### Issue description
what is the recommended way to split access log in k8s pod? for example, split by day

### Environment

* apisix version (cmd: `apisix version`):  1.5
* OS: deploy in k8s

**Comment by membphis** [comment]
> for example, split by day

Here is an example for `access` log, is right?

```
access.log
access-20200801-000000.log
access-20200802-000000.log
access-20200803-000000.log
```
