### ISSUE TITLE
request help:  1.5 make deps error

### ISSUE THREAD

**Issue by lijiapengsa** [apache/apisix#2052]
### Issue description
after make deps

![image](https://user-images.githubusercontent.com/7970836/90091592-66845d80-dd59-11ea-93ee-993e57557849.png)

then  make deps
[root@k8s-ops-apache-apisix-1.5]# make deps
luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
Using rockspec/apisix-master-0.rockspec... switching to 'build' mode
Stopping after installing dependencies for apisix master-0

### Environment
centos7
use https://github.com/apache/apisix/blob/master/doc/zh-cn/install-dependencies.md#centos-7 install  dependencies
* apisix version (cmd: `apisix version`): 1.5
* OS: CentOS Linux release 7.8.2003 (Core)

**Comment by membphis** [comment]
This means that you have successfully installed the dependencies of APISIX.

![image](https://user-images.githubusercontent.com/6814606/90236580-8600b080-de55-11ea-9191-c5f25e411fed.png)
