### ISSUE TITLE
request help: how to get post data of form-data、x-www-form-urlencoded、data-raw(json)

### ISSUE THREAD

**Issue by yfgcq** [apache/apisix#2053]
### Issue description
 how to get post data of form-data、x-www-form-urlencoded、data-raw(json)？
怎么获取这几种form-data、x-www-form-urlencoded、data-raw(json) post请求的post data ？

ngx.req.get_post_args()可以获取 x-www-form-urlencoded请求的post data
ngx.req.get_body_data()可以获取data-raw(json) ,必须指定ContentType:application/json,
但是有时postman 或者curl 请求时 没指定ContentType
    curl xxx POST -i -d ' {"AppKey": "a1", "id": 22234666}'
    apisix 判断逻辑： 
`
      if string.find(ngx.req.get_headers()["Content-Type"] or "","application/json", 1, true) then
        ngx.req.get_body_data()
      else
        ngx.req.get_post_args() --
       end
`
问题1:没指定application/json，但传递参数又是json格式,这种情况怎么判断解析数据？
问题2:form-data 不知道怎么获取？

### Environment

* apisix version (cmd: `apisix version`):1.4.1
* OS:linux

**Comment by jiezaizone** [comment]
发自我的华为手机-------- 原始邮件 --------发件人： yfgcq <notifications@github.com>日期： 2020年8月13日周四 下午2:21收件人： apache/apisix <apisix@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： [apache/apisix] request help: how to get post data of form-data、x-www-form-urlencoded、data-raw(json) (#2053)

Issue description

how to get post data of form-data、x-www-form-urlencoded、data-raw(json)？

怎么获取这几种form-data、x-www-form-urlencoded、data-raw(json) post请求的post data ？

ngx.req.get_post_args()可以获取 x-www-form-urlencoded请求的post data

ngx.req.get_body_data()可以获取data-raw(json) ,必须指定ContentType:application/json,

但是有时postman 或者curl 请求时 没指定ContentType

curl xxx POST -i -d ' {"AppKey": "a1", "id": 22234666}'

apisix 判断逻辑：

if string.find(ngx.req.get_headers()["Content-Type"] or "","application/json", 1, true) then ngx.req.get_body_data() else ngx.req.get_post_args() -- end

问题1:这种情况怎么办？

问题2:form-data 不知道怎么获取？

Environment

apisix version (cmd: apisix version):1.4.1OS:linux

**Comment by yfgcq** [comment]
???

**Comment by membphis** [comment]
1. read the request header
2. check the `Content-Type`
3. different type, use different way.

https://moonbingbing.gitbooks.io/openresty-best-practices/content/

this book may help you.

**Comment by jack01234** [comment]
我也遇到了这样的问题，你解决了吗
