### ISSUE TITLE
request help: How to limit the exposure of Prometheus monitoring data to the public network.

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix#2054]
### Issue description
怎么限制 prometheus 监控数据暴露到公网。url链接如下：
http://ip/apisix/prometheus/metrics

How to limit the exposure of Prometheus monitoring data to the public network. The URL link is as follows:
http://ip/apisix/prometheus/metrics

### Environment

* apisix version (cmd: `apisix version`): apisix 1.5
* OS:centos 7

**Comment by membphis** [comment]
You can update the plug-in `prometheus` to allow only some IPs, for example `127.0.0.1`.
