### ISSUE TITLE
request help: how apisix proxy to static files

### ISSUE THREAD

**Issue by TigerGxl** [apache/apisix#2055]
### Environment

* apisix version (cmd: `apisix version`): 1.5 (by luarocks)
* OS:Ubuntu 16.04.6

apisix is great to loads api service, now i want to proxy to static file like html without nginx.

this is my conf in etcd
![image](https://user-images.githubusercontent.com/32395903/90116590-47e98b00-dd88-11ea-95a8-56b6a5bc8970.png)

What I want to do is when i request "http://demo.apisix.com", apisix loads to "/home/demo80/index.html", run javascript in the html, and now , if i request "http://demo.apisix.com/v1", apisix loads to my backend  "172.16.43.216:5000" and return 404, it's not working,What should I do right?

**Comment by membphis** [comment]
you can use another Nginx server to provide the static files.

client -> apisix -> nginx(static file)
client -> apisix -> upstream

create two routes for this case, then it will work fine.
