### ISSUE TITLE
request help: rpm包方式安装apisix 1.5后，访问admin api 404.

### ISSUE THREAD

**Issue by tongorz** [apache/apisix#2057]
### Issue description
rpm包方式安装apisix 1.5后，访问admin api 404.

```
curl http://127.0.0.1:9080/apisix/admin
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
```

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS: CentOS 7

**Comment by membphis** [comment]
here is the quickstart: https://github.com/apache/apisix/blob/master/doc/getting-started.md

**Comment by moonming** [comment]
@tongorz 
Please use English in the public channel, thx
