### ISSUE TITLE
bug: Please delete old releases from mirroring system

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix#2059]
To reduce the load on the ASF mirrors, projects are required to delete old releases [1]
Please can you remove all non-current releases?
Thanks!

Remember to update any download pages to remove old releases (or point to the archive server) before removing the releases from https://dist.apache.org/repos/dist/release/apisix/...

Note: the download area seems to be a bit muddled.
There are two releases at top level:
https://dist.apache.org/repos/dist/release/apisix

There are also several releases a level deeper:
https://dist.apache.org/repos/dist/release/apisix/apisix/
This looks wrong.

[1] http://www.apache.org/dev/release.html#when-to-archive

**Comment by membphis** [comment]
Thank you very much for your reminder, we will update it as soon as possible.

**Comment by juzhiyuan** [comment]
- [ ] SVN
- [ ] Download Page

**Comment by sebbASF** [comment]
Deletion is very simple:
- update the download page to remove the old releases
- delete the releases from https://dist.apache.org/repos/dist/release/apisix/apisix/
 (you can probably delete the entire directory)

Remember that the mirrors give their services for free, so they should not have to store old releases unnecessarily.

**Comment by sebbASF** [comment]
Please tidy up the release area.

It's not fair on the volunteer mirrors to have to carry old releases.

**Comment by moonming** [comment]
@sebbASF we updated download page by https://github.com/apache/apisix-website/pull/93, and removed old releases from svn.
