### ISSUE TITLE
bug: got 500 response when PUT new upstream

### ISSUE THREAD

**Issue by lhtlp1997** [apache/apisix#2060]
### Issue description
Installed openResty，etcd and Compilation tool。Start apisix successfully。But I got a err when I did:
curl "http://127.0.0.1:9080/apisix/admin/upstreams/50" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "type": "roundrobin",
    "nodes": {
        "httpbin.org:443": 1
    }
}'

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Environment
cent os 7
* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
please check your error log, we need it to confirm this bug.

**Comment by lhtlp1997** [comment]
2020/08/14 19:24:03 [error] 12547#12547: *36 lua entry thread aborted: runtime error: /root/apache-apisix-1.5/apisix/init.lua:697: attempt to index upvalue 'router' (a nil value)
stack traceback:
coroutine 0:
	/root/apache-apisix-1.5/apisix/init.lua: in function 'http_admin'
	content_by_lua(nginx.conf:145):2: in main chunk, client: 127.0.0.1, server: , request: "PUT /apisix/admin/routes/1 HTTP/1.1", host: "127.0.0.1:9080"

**Comment by membphis** [comment]
BTW, please use English in the public channel ^_^

**Comment by lhtlp1997** [comment]
2020/08/14 19:26:10 [error] 12552#12552: *39 lua entry thread aborted: runtime error: /root/apache-apisix-1.5/apisix/init.lua:697: attempt to index upvalue 'router' (a nil value)
stack traceback:
coroutine 0:
	/root/apache-apisix-1.5/apisix/init.lua: in function 'http_admin'
	content_by_lua(nginx.conf:145):2: in main chunk, client: 127.0.0.1, server: , request: "PUT /apisix/admin/upstreams/50 HTTP/1.1", host: "127.0.0.1:9080"

**Comment by membphis** [comment]
Do not try to use apisix under the root user, it is not safe.
And some lua code may not be loaded normally due to missing permissions.
