### ISSUE TITLE
request help: 接口签名算法支持

### ISSUE THREAD

**Issue by longshang** [apache/apisix#2066]
请问APISIX怎么支持接口签名算法，例如微信签名算法：https://pay.weixin.qq.com/wiki/doc/api/external/declarecustom.php?chapter=4_5

**Comment by membphis** [comment]
you can follow the step in your link, it should work fine.

and I think you can take a look at those projects: https://github.com/search?q=resty+wechat

**Comment by moonming** [comment]
@longshang 
Please use English in the public channel, thx

**Comment by moonming** [comment]
@longshang please take a look at this PR: https://github.com/apache/apisix/pull/1960

**Comment by longshang** [comment]
> @longshang
> Please use English in the public channel, thx

OK，thx
