### ISSUE TITLE
request help: 获取 jwt-auth token 的接口如何保证安全性呢

### ISSUE THREAD

**Issue by ShynHan** [apache/apisix#2068]
### Issue description
![image](https://user-images.githubusercontent.com/12025422/90376864-ae80e880-e0a9-11ea-82d4-f12d0872e438.png)

这个获取 jwt-auth token 的接口只需要一个 key 参数，这个 key 参数又可以在 jwt-auth token 解码出来，
那岂不是任何人都可以通过这个接口随意生成 jwt-auth token

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
we should use HTTPS to protect this `key`.  it is a common way.

**Comment by moonming** [comment]
@ShynHan Please use English in the public channel, thx

**Comment by ShynHan** [comment]
@moonming Sorry, witch channel can be use Chinese?
