### ISSUE TITLE
bug: APISIX启动一直报错如下

### ISSUE THREAD

**Issue by longshang** [apache/apisix#2069]
### Issue description
[emerg] 1#1: invalid number of arguments in "worker_shutdown_timeout" directive in /usr/local/apisix/conf/nginx.conf:21

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS: centos

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
please update your `conf/config.yaml` to latest version.

**Comment by moonming** [comment]
@longshang 
Please use English in the public channel, thx
