### ISSUE TITLE
request help: What is hosts in route?

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#2071]
### Issue description
excuse me，What is hosts in route?
![image](https://user-images.githubusercontent.com/29362652/90474831-c5324880-e158-11ea-89f9-c2681c6bb014.png)
In the new version of Dashboard, this is required, but I'm not sure what this is for. Although it's explained in the ADMIN Api, it still makes me confused, right? Can you explain that again? thank you

### Environment

* apisix version (cmd: `apisix version`):1.4
* OS:centos7

**Comment by membphis** [comment]
1. please update your APISIX to latest version 1.5
2. the `域名` means the field which named `host`. it is the host of client request.

```
# curl http://127.0.0.1:9080/hello -H "host: foo.com"

in this case, the host is foo.com
```

https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

![image](https://user-images.githubusercontent.com/6814606/90494141-c2921c00-e175-11ea-9eb5-cc18b82809d8.png)
