### ISSUE TITLE
prometheus no memory when  high qps request help: 

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/apisix#2074]
### Issue description
when at a high qps scene, the promethues will report a error about the exporter
no memory allocted
table.contact(peometheus:merics_data())

### Environment

* apisix version (cmd: `apisix version`):
* OS: centos 7.7 64 位

it seem's the reason is the limit of luajit or lua itself,how can I solve this.thanks for helping

**Comment by membphis** [comment]
please provide a full error log.

**Comment by OnlyPiglet** [comment]
@membphis  I sorry I have destory the colud server, this is the only info about this error,the error link the file of promethues/exporter.lua  table.contact(peometheus:merics_data())
``` lua entry thread aborted: memory allocation error: not enough memory
```

**Comment by OnlyPiglet** [comment]
we cloudn't add the limit of lua or luajit right?

**Comment by OnlyPiglet** [comment]
there is a fire flame
<img width="923" alt="Snipaste_2020-08-18_21-39-38" src="https://user-images.githubusercontent.com/46953658/90519987-562a1380-e19b-11ea-8061-3a0990f2473e.png">
I am not sure if this will be helpful

**Comment by membphis** [comment]
Do you enabled Lua GC 64 model?
And what is the size of your memory?

**Comment by OnlyPiglet** [comment]
@membphis yes,that's what I am concerned the Lua GC 64 model .MyMemory is 16GB,The Cpu is 4 cores
