### ISSUE TITLE
request help: Is 'k8s_deployment_info' in upstream supported in latest few versions?

### ISSUE THREAD

**Issue by houshunwei** [apache/apisix#2075]
#### 1. I add a route with upstream like this:

```
curl http://10.234.59.13:8880/apisix/admin/routes/1101 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["POST", "GET"],
    "uri": "/test",
    "upstream": {
      "type": "roundrobin",
      "k8s_deployment_info": {
          "namespace": "my-domain",
          "deploy_name": "my-deploy",
          "backend_type": "pod",
          "port": 8001
      }
    }
}'
```
#### 2. Got `502 Bad Gateway` when request.
when i request `http://{docker-ip}:9080/test`, i got `502 Bad Gateway`.

detail logs in error.log:
```
2020/08/18 23:53:25 [error] 185#185: *31949449 [lua] balancer.lua:254: load_balancer(): failed to pick server: no valid upstream node while connecting to upstream, client: 10.233.64.1, server: , request: "GET /test HTTP/1.1"
```

#### 3. No source code for `k8s_deployment_info`
I have tried to find k8s_deployment_info related code. But k8s_deployment_info only exists in doc and schema_define.lua.

Question：Is 'k8s_deployment_info' in upstream supported in latest few versions?

### Environment

* apisix version (cmd: `apisix version`): APISIX 1.4
* OS: docker, centos7

**Comment by membphis** [comment]
k8s_deployment_info + ingress controller ，should work together.
the `ingress controller` will translate it to real upstream nodes.
