### ISSUE TITLE
bug: service discovery duplicate request service information in Eureka

### ISSUE THREAD

**Issue by frank0417** [apache/apisix#2076]
### Issue description

Service discovery duplicate request service information in Eureka

### Environment

* apisix version (cmd: `apisix version`):
* OS:linux centos

### Minimal test code / Steps to reproduce the issue
1.set enable_dev_mode:false
2.service discovery center:eureka

### What's the actual result? (including assertion message & call stack if applicable)

multiple workers execute repeat fetch_full_registry

### What's the expected result?
only one

**Comment by frank0417** [comment]
add ngx.worker.id()==0

**Comment by frank0417** [comment]
Each worker will pull the service information. If a worker pulls the service information, it needs to be shared by all workers. Otherwise, some workers will not be able to obtain the service information. If it is changed, the global cache is required

**Comment by spacewander** [comment]
Currently all the workers will fetch service info from Eureka.
