### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix#2080]
### Issue description
![image](https://user-images.githubusercontent.com/17898385/90602224-ffb8e580-e22b-11ea-90ca-b7b9957c1d94.png)
Request API to report 403.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by liubinqi2007** [comment]
![image](https://user-images.githubusercontent.com/17898385/90603478-f0d33280-e22d-11ea-8934-f4100dfd3b86.png)

**Comment by ShiningRush** [comment]
You need a token to access admin api, please have look at the section of "REST Admin API" in [homepage](https://github.com/apache/apisix),
Maybe we should append more detail about auth in the doc of admin api, such as how to send token in request, now here is nothing in [it](https://github.com/apache/apisix/blob/master/doc/admin-api.md). @moonming @membphis

**Comment by membphis** [comment]
please confirm if you set right value for `allow_admin `:

https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L58

**Comment by membphis** [comment]
> Maybe we should append more detail about auth in the doc of admin api, such as how to send token in request, now here is nothing in [it](https://github.com/apache/apisix/blob/master/doc/admin-api.md). @moonming @membphis

welcome to create a new issue, we need some doc about this case. add a topic in FAQ is fine too.
