### ISSUE TITLE
[BUG] there are some impacts when we migrate the content in `config.yaml` to `config-default.yaml`

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2081]
### Issue description
In the projects named [apisix-dashboard](https://github.com/apache/apisix-dashboard) and [apisix-docker](https://github.com/apache/apisix-docker), we get the content of config.yaml for keeping config.yaml same with the latest version of apisix.
now, we migrate the content in `config.yaml` to `config-default.yaml`,so the script need to be modified too.

### Environment

* apisix version : latest
* OS: Linux

**Comment by gxthrj** [comment]
like https://github.com/apache/apisix-dashboard/issues/381

**Comment by gxthrj** [comment]
and a PR for `apisix-dashboard`  in https://github.com/apache/apisix-dashboard/pull/383

**Comment by gxthrj** [comment]
a PR for `apisix-docker` in https://github.com/apache/apisix-docker/pull/72

**Comment by spacewander** [comment]
Solved.
