### ISSUE TITLE
request help: Update plugin's schema

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#2082]
### Issue description

The Apache APISIX Dashboard is using a module named [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/), which is used to build UI components according to JSONSchema, but due to some differences between Draft7 and other versions Apache APISIX is using, some components couldn't be rendered correctly, so in order to fix this issue, I propose to change some plugin's schema.

I will create issues to describe the changes for each plugin, this issue mainly focuses on tracking the total process.

### Environment

* apisix version (cmd: `apisix version`): All
* OS:

### Process
- [x] [prometheus](https://github.com/apache/apisix/issues/2084) & [node-status](https://github.com/apache/apisix/issues/2084)
- [x] [basic-auth](https://github.com/apache/apisix/issues/2083)
- [x] [ip-restriction](https://github.com/apache/apisix/issues/2085)
- [x] [limit-count](https://github.com/apache/apisix/issues/2086)
- [x] [fault-injection](https://github.com/apache/apisix/issues/2088)
- [x] [response-rewrite](https://github.com/apache/apisix/issues/2087)
- [ ] [kafka-log](https://github.com/apache/apisix-dashboard/issues/790#issuecomment-728803034)
- [x] jwt-auth

**Comment by juzhiyuan** [comment]
I will create issues to describe the changes for each plugin.

**Comment by liuxiran** [comment]
- [ ] consumer-restriction

**Comment by imjoey** [comment]
Added here for tracking #2432 .
- [ ] request-validation

**Comment by liuxiran** [comment]
Added for tracking #2441
- [ ] hmac-auth

**Comment by juzhiyuan** [comment]
- [ ] proxy-rewrite

![image](https://user-images.githubusercontent.com/2106987/96826430-ee779980-1465-11eb-8111-f347fda71cbf.png)

**Comment by liuxiran** [comment]
add for tracing jwt-auth: https://github.com/apache/apisix/issues/2288

**Comment by liuxiran** [comment]
> * [ ]  proxy-rewrite
> 


I have **a proposal** for this header's schema modification: @juzhiyuan 

- The schema provided by APISIX stays the same, because the type of parameter in header can only be defined when the user designs it

- dashboard(plugin component) Adapt the schema that the user needs. 
---

take `proxy-rewrite` as an example:

- the header schema returned by APISIX is:
```json
"headers": {
    "description": "new headers for request",
    "minProperties": 1,
    "type": "object"
}
```

- dashboard adapt the header schema to:
```json
{
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "key": {
                "type": "string"
	    },
	   "value": {
	       "type": "object",
               "oneOf": [{
                   "title": "value type is string",
                   "properties": {
                       "value": {
		           "type": "string"
			}
		    }
		},
		{
		    "title": "value type is number",
		    "properties": {
		        "value": {
			    "type": "number"
			}
		     }
		}]
           }
       }
   }
}
```

- the `proxy-rewrite` config page in dashboard looks like:
[default looks]
![2020-10-26 14-52-28屏幕截图](https://user-images.githubusercontent.com/2561857/97142100-fd7a8680-179a-11eb-8e68-48c2ae06f10c.png)
[define parameters looks]
![111111111111111](https://user-images.githubusercontent.com/2561857/97143182-26038000-179d-11eb-84ed-1d81609d7f96.jpg)

- the data posted to the APISIX:
```json
"proxy-rewrite": {
        ...configdata,
	"headers": {
	    "token": {
		"value": "345345-reertert"
	    }
	}
}
```

**Comment by juzhiyuan** [comment]
> > * [ ]   proxy-rewrite
> 
> I have **a proposal** for this header's schema modification: @juzhiyuan
> 
> * The schema provided by APISIX stays the same, because the type of parameter in header can only be defined when the user designs it
> * dashboard(plugin component) Adapt the schema that the user needs.
> 
> take `proxy-rewrite` as an example:
> 
> * the header schema returned by APISIX is:
> 
> ```json
> "headers": {
>     "description": "new headers for request",
>     "minProperties": 1,
>     "type": "object"
> }
> ```
> 
> * dashboard adapt the header schema to:
> 
> ```json
> {
>     "type": "array",
>     "items": {
>         "type": "object",
>         "properties": {
>             "key": {
>                 "type": "string"
> 	    },
> 	   "value": {
> 	       "type": "object",
>                "oneOf": [{
>                    "title": "value type is string",
>                    "properties": {
>                        "value": {
> 		           "type": "string"
> 			}
> 		    }
> 		},
> 		{
> 		    "title": "value type is number",
> 		    "properties": {
> 		        "value": {
> 			    "type": "number"
> 			}
> 		     }
> 		}]
>            }
>        }
>    }
> }
> ```
> 
> * the `proxy-rewrite` config page in dashboard looks like:
>   [default looks]
>   ![2020-10-26 14-52-28屏幕截图](https://user-images.githubusercontent.com/2561857/97142100-fd7a8680-179a-11eb-8e68-48c2ae06f10c.png)
>   [define parameters looks]
>   ![111111111111111](https://user-images.githubusercontent.com/2561857/97143182-26038000-179d-11eb-84ed-1d81609d7f96.jpg)
> * the data posted to the APISIX:
> 
> ```json
> "proxy-rewrite": {
>         ...configdata,
> 	"headers": {
> 	    "token": {
> 		"value": "345345-reertert"
> 	    }
> 	}
> }
> ```

it's ok for me, what's your opinion? cc @membphis

**Comment by liuxiran** [comment]
Sorry to related fix this issue by https://github.com/api7/dashboard-components/pull/143, which only fix: https://github.com/apache/apisix/issues/2082#issuecomment-714225553,  part of this issue,
reopen now

**Comment by liuxiran** [comment]
> Added here for tracking #2432 .
> 
> * [x]  request-validation

After the schema draft updated in APISIX, **request-validation** also needs to transform the schema at plugin componet, so that it can work properly in dashboard, just like proxy-rewrite do. @juzhiyuan 

- the schema turned by APISIX:
```json
{
	"anyOf": [{
		"properties": {
			"body_schema": {
				"type": "object"
			}
		},
		"required": ["body_schema"],
		"title": "Body schema"
	}, {
		"properties": {
			"header_schema": {
				"type": "object"
			}
		},
		"required": ["header_schema"],
		"title": "Header schema"
	}],
	"type": "object"
}
```
- dashboard needs to transform the schema to:
```json
{
    "type": "object",
    "properties": {
      "requestParams": {
        "title": "define request paramers",
        "type": "array",
        "items": {
          "type": "object",
          "anyOf": [{
              "title": "define body params",
              "properties": {
                "body_schema": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "valueType": {
                      "type": "string",
                      "enum": [
                        "string",
                        "array",
                        "integer",
                        "number",
                        "object",
                        "boolean"
                      ]
                    },
                    "required": {
                      "type": "boolean"
                    }
                  }
                }
              },
              "required": ["body_schema"],
              "miniItems": 1
            },
            {
              "title": "define header params",
              "properties": {
                "header_schema": {
                  "type": "object",
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "valueType": {
                      "type": "string",
                      "enum": [
                        "string",
                        "array",
                        "integer",
                        "number",
                        "object",
                        "boolean"
                      ]
                    },
                    "required": {
                      "type": "boolean"
                    }
                  }
                }
              }
            }
          ]
        }
      }
    }
  }
``` 

- the config page in dashboard looks like:



![2020-11-04 15-04-20屏幕截图](https://user-images.githubusercontent.com/2561857/98079645-1e379000-1eaf-11eb-8633-cd90e22c0f24.png)

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/issues/2082#issuecomment-721552396

Please take a look and have a try when you are free :)

cc @LiteSun

**Comment by LiteSun** [comment]
I try to transform `request-validation` schema as you provided, but it seems there is an error. @liuxiran 

![image](https://user-images.githubusercontent.com/31329157/98326057-46e49480-202b-11eb-996e-f235ee3e25bf.png)

**Comment by LiteSun** [comment]
Should I transform  `request-validation` request?

**Comment by juzhiyuan** [comment]
> Should I transform `request-validation` request?

What's the correct data format for this plugin? cc @liuxiran

**Comment by liuxiran** [comment]
> > Should I transform `request-validation` request?
> 
> What's the correct data format for this plugin? cc @liuxiran

yep, request and response transform are also needed, we should transform the data got from schema form  to:

```json
{
  "body_scheme"?: {
    "type": "object",
    "required": $key[], // the $key which required: true
    "properties": {
      [$key]: {
          "type": [$valueType],
          [$otherkey defined in dependencies]: [$value]
      }
    }
  },
  "header_schema"?:{
    the same with body_schema
   }
  }
```

and transform the data got from API to 
```json
{
   "requestParams": [
      {
         "body_schema": {
             "key": xxx,
             "valueType": "",
             ....
         }
      },
      {
         "header_schema":{}
      }
      ...
   ]
}
``` 

The reason is that fe need schema UI form to help user deine what the parameter verify schema  looks like.  pass a schema definition to api.

@juzhiyuan @LiteSun

**Comment by LiteSun** [comment]
> > > Should I transform `request-validation` request?
> > 
> > 
> > What's the correct data format for this plugin? cc @liuxiran
> 
> yep, request and response transform are also needed, we should transform the data got from schema form to:
> 
> ```json
> {
>   "body_scheme"?: {
>     "type": "object",
>     "required": $key[], // the $key which required: true
>     "properties": {
>       [$key]: {
>           "type": [$valueType],
>           [$otherkey defined in dependencies]: [$value]
>       }
>     }
>   },
>   "header_schema"?:{
>     the same with body_schema
>    }
>   }
> ```
> 
> and transform the data got from API to
> 
> ```json
> {
>    "requestParams": [
>       {
>          "body_schema": {
>              "key": xxx,
>              "valueType": "",
>              ....
>          }
>       },
>       {
>          "header_schema":{}
>       }
>       ...
>    ]
> }
> ```
> 
> The reason is that fe need schema UI form to help user deine what the parameter verify schema looks like. pass a schema definition to api.
> 
> @juzhiyuan @LiteSun

@liuxiran Tks! I still have a question that How to handle multiple body_schema header_schema cases? As showing below:
![image](https://user-images.githubusercontent.com/31329157/98342475-6b506900-204b-11eb-9a88-c771c7415e76.png)

**Comment by liuxiran** [comment]
> @liuxiran Tks! I still have a question that How to handle multiple body_schema header_schema cases? As showing below:

each body_schema in form data will be a sub attr of requestdata. body_schema. properties, the same to header_schema😊

**Comment by LiteSun** [comment]
Got it! Tks👍

**Comment by liuxiran** [comment]
After communicating with @LiteSun, there are three problems with the **request validation schema** design of the first edition:

1. dirty data: when change from body_schema to header_schema, useless `body_schema` will be generated, and it can not be tranform to UI. 
**try to update the transform schema to** the follow one
```json
{
    "type": "object",
    "properties": {
      "requestParams": {
        "title": "define request paramers",
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#/definitions/requestParams"
        },
        "minItems": 1
      }
    },
    "definitions": {
      "requestParams": {
        "type": "object",
        "properties": {
          "schema": {
            "type": "string",
            "enum": [
              "body_schema",
              "header_schema"
            ]
          },
          "key": {
            "type": "string"
          },
          "valueType": {
            "type": "string",
            "enum": [
              "string",
              "array",
              "integer",
              "number",
              "object",
              "boolean"
            ]
          },
          "required": {
            "type": "boolean"
          }
        },
        "dependencies": {
          "valueType": {
            "oneOf": [
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "string"
                    ]
                  },
                  "minLength": {
                    "type": "integer"
                  },
                  "maxLength": {
                    "type": "integer"
                  },
                  "pattern": {
                    "type": "string"
                  },
                  "enumValues": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  }
                },
                "required": ["valueType"]
              },
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "array"
                    ]
                  },
                  "minItems": {
                    "type": "integer"
                  },
                  "itemsType": {
                    "type": "string",
                    "enum": [
                      "string",
                      "array",
                      "integer",
                      "number",
                      "object",
                      "boolean"
                    ]
                  },
                  "uniqueItems": {
                    "type": "boolean"
                  }
                },
                "required": [
                  "valueType"
                ]
              },
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "integer"
                    ]
                  },
                  "minimum": {
                    "type": "integer"
                  },
                  "maximum": {
                    "type": "integer"
                  }
                },
                "required": [
                  "valueType"
                ]
              },
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "number"
                    ]
                  },
                  "minimum": {
                    "type": "number"
                  },
                  "maximum": {
                    "type": "number"
                  }
                },
                "required": [
                  "valueType"
                ]
              },
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "object"
                    ]
                  }
                },
                "required": [
                  "valueType"
                ]
              },
              {
                "properties": {
                  "valueType": {
                    "enum": [
                      "boolean"
                    ]
                  }
                },
                "required": [
                  "valueType"
                ]
              }
            ]
          }
        },
        "required": ["schema", "key", "valueType"]
      }
    }
  }
```
2. how to handle parameters with the same name in the same section? as  user may have inadvertently defined two parameters with the same name.  **I prefer to covers the former with the latest one**.
3. how to handle the order in which parameters are defined? as we have to transform the data before it posted to the API, it will  disrupt the order in which the parameters were originally defined. **I prefer to ignore the order,  because the order of parameters does not affect the result of calling the api**

**Comment by juzhiyuan** [comment]
[example plugin](https://github.com/apache/apisix/issues/2672)

**Comment by liuxiran** [comment]
> * [ ]  [example plugin](https://github.com/apache/apisix/issues/2672)

example plugin will be disabled with #2673

**Comment by LiteSun** [comment]
> After communicating with @LiteSun, there are three problems with the **request validation schema** design of the first edition:
> 
> 1. dirty data: when change from body_schema to header_schema, useless `body_schema` will be generated, and it can not be tranform to UI.
>    **try to update the transform schema to** the follow one
> 
> ```json
> {
>     "type": "object",
>     "properties": {
>       "requestParams": {
>         "title": "define request paramers",
>         "type": "array",
>         "items": {
>           "type": "object",
>           "$ref": "#/definitions/requestParams"
>         },
>         "minItems": 1
>       }
>     },
>     "definitions": {
>       "requestParams": {
>         "type": "object",
>         "properties": {
>           "schema": {
>             "type": "string",
>             "enum": [
>               "body_schema",
>               "header_schema"
>             ]
>           },
>           "key": {
>             "type": "string"
>           },
>           "valueType": {
>             "type": "string",
>             "enum": [
>               "string",
>               "array",
>               "integer",
>               "number",
>               "object",
>               "boolean"
>             ]
>           },
>           "required": {
>             "type": "boolean"
>           }
>         },
>         "dependencies": {
>           "valueType": {
>             "oneOf": [
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "string"
>                     ]
>                   },
>                   "minLength": {
>                     "type": "integer"
>                   },
>                   "maxLength": {
>                     "type": "integer"
>                   },
>                   "pattern": {
>                     "type": "string"
>                   },
>                   "enumValues": {
>                     "type": "array",
>                     "items": {
>                       "type": "string"
>                     }
>                   }
>                 },
>                 "required": ["valueType"]
>               },
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "array"
>                     ]
>                   },
>                   "minItems": {
>                     "type": "integer"
>                   },
>                   "itemsType": {
>                     "type": "string",
>                     "enum": [
>                       "string",
>                       "array",
>                       "integer",
>                       "number",
>                       "object",
>                       "boolean"
>                     ]
>                   },
>                   "uniqueItems": {
>                     "type": "boolean"
>                   }
>                 },
>                 "required": [
>                   "valueType"
>                 ]
>               },
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "integer"
>                     ]
>                   },
>                   "minimum": {
>                     "type": "integer"
>                   },
>                   "maximum": {
>                     "type": "integer"
>                   }
>                 },
>                 "required": [
>                   "valueType"
>                 ]
>               },
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "number"
>                     ]
>                   },
>                   "minimum": {
>                     "type": "number"
>                   },
>                   "maximum": {
>                     "type": "number"
>                   }
>                 },
>                 "required": [
>                   "valueType"
>                 ]
>               },
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "object"
>                     ]
>                   }
>                 },
>                 "required": [
>                   "valueType"
>                 ]
>               },
>               {
>                 "properties": {
>                   "valueType": {
>                     "enum": [
>                       "boolean"
>                     ]
>                   }
>                 },
>                 "required": [
>                   "valueType"
>                 ]
>               }
>             ]
>           }
>         },
>         "required": ["schema", "key", "valueType"]
>       }
>     }
>   }
> ```
> 
> 1. how to handle parameters with the same name in the same section? as  user may have inadvertently defined two parameters with the same name.  **I prefer to covers the former with the latest one**.
> 2. how to handle the order in which parameters are defined? as we have to transform the data before it posted to the API, it will  disrupt the order in which the parameters were originally defined. **I prefer to ignore the order,  because the order of parameters does not affect the result of calling the api**

1. I just test the latest transform schema you provided.it works well and dirty data has been successfully removed. For more info, please refer to https://github.com/api7/dashboard-components/pull/176
2&3.It is ok for me. What do you think? @juzhiyuan @membphis

**Comment by juzhiyuan** [comment]
Not sure, just waiting for others opinions.

**Comment by liuxiran** [comment]
- [ ] key-auth

**Comment by liuxiran** [comment]
- [ ] echo

**Comment by spacewander** [comment]
@juzhiyuan 
Have we finished this job?

**Comment by juzhiyuan** [comment]
Oh yes, done
