### ISSUE TITLE
bug:  kubenetes ingress install error

### ISSUE THREAD

**Issue by binbinjianjian** [apache/apisix#2093]
### Issue description
kubenetes ingress  install  error

### Environment
centos7    kubenetes    v1.14.0 and  v1.18.2

### pod error log
[root@k8s-cdh-master kubernetes]# kubectl logs apisix-gw-deployment-6b95457c8f-g8sxp
/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:684: bad argument #1 to 'sfind' (string expected, got nil)
stack traceback:
	[C]: in function 'sfind'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:684: in function 'parsedocuments'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:746: in function 'read_yaml_conf'
	/usr/bin/apisix:675: in function </usr/bin/apisix:668>
	/usr/bin/apisix:922: in main chunk
	[C]: at 0x00404c0

**Comment by juzhiyuan** [comment]
Please update your issue title, thanks!

**Comment by gxthrj** [comment]
@binbinjianjian It looks more like there is a problem with your configuration file, please show us your `config.yaml`

**Comment by spacewander** [comment]
Closed as lack of response.
