### ISSUE TITLE
update limit-* plugins doc: Apache APISIX already support all nginx variables as limit key

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2095]
@gy09535 Apache APISIX already support all nginx variables as limit key: http://nginx.org/en/docs/varindex.html, you just need to add it in the enum list of key: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-req.lua#L29.

_Originally posted by @moonming in https://github.com/apache/apisix/pull/2094#issuecomment-678111148_

**Comment by spacewander** [comment]
Already done.
