### ISSUE TITLE
bug: route use limit-count plugin, update again plugin config info not effective

### ISSUE THREAD

**Issue by wbaweto** [apache/apisix#2098]
### Issue description
route use limit-count plugin, update again plugin config info not effective

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS:  CentOS Linux release 7.6.1810 (Core)

### Minimal test code / Steps to reproduce the issue
1. route config type
route -> service -> upstream

```
{
    "uri": "/v1/test/get",
    "hosts": ["api-dev.test.com"],
    "priority": 10,
    "methods": ["GET", "POST", "OPTIONS", "HEAD"],
    "plugins": {
        "limit-count": {
            "count": 10,
            "time_window": 3,
            "rejected_code": 403,
            "key": "remote_addr"
        }
    },
    "service_id": "test"
}
```

2. update again plugin config info
modify imit-count.count from 10 to 20

```
{
    "uri": "/v1/test/get",
    "hosts": ["api-dev.test.com"],
    "priority": 10,
    "methods": ["GET", "POST", "OPTIONS", "HEAD"],
    "plugins": {
        "limit-count": {
            "count": 20,
            "time_window": 3,
            "rejected_code": 403,
            "key": "remote_addr"
        }
    },
    "service_id": "test"
}
```

### What's the actual result? (including assertion message & call stack if applicable)

1、initial config limit-count,  response head. expected result, is right
Apisix-Plugins: limit-count
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 9

2、update again limit-count info,  response head. unexpected result, is wrong
Apisix-Plugins: limit-count
X-RateLimit-Limit: 20
X-RateLimit-Remaining: 9

X-RateLimit-Remaining result is wrong, expected result: 19

### Reason positioning

1、apisix/plugins/limit-count.lua:
local lim, err = core.lrucache.plugin_ctx(plugin_name, ctx, create_limit_obj, conf)

2、apisix/core/lrucache.lua
function _M.plugin_ctx(plugin_name, api_ctx, create_obj_fun, ...)
    local key = api_ctx.conf_type .. "#" .. api_ctx.conf_id
    return _plugin(plugin_name, key, api_ctx.conf_version, create_obj_fun, ...)
end

api_ctx.conf_type value: service
api_ctx.conf_id value: test
api_ctx.conf_version -> service_id=test version ID

no matter how update route's limit-count info,  api_ctx.conf_type、api_ctx.conf_id、api_ctx.conf_version is unchanged, 
limit-count info always get the initial value

I think the root cause：
apisix/init.lua  http_access_phase function:
route.value.service_id is existed, the follow code:
       local changed
        route, changed = plugin.merge_service_route(service, route)
        api_ctx.matched_route = route
        if changed then
            api_ctx.conf_type = "route&service"
            api_ctx.conf_version = route.modifiedIndex .. "&"
                                   .. service.modifiedIndex
            api_ctx.conf_id = route.value.id .. "&"
                              .. service.value.id
        else
            api_ctx.conf_type = "service"
            api_ctx.conf_version = service.modifiedIndex
            api_ctx.conf_id = service.value.id
        end

variable: changed  is always nil，plugin.merge_service_route has problem

**Comment by gy09535** [comment]
> welcome PR to fix this issue

I think there has two problems, the 'changed' variable is always nil, Because when the 'route_config' is changed ,  it become a new key ,so the  'changed' variable  is always nil. Another problem is the 'route.modifiedIndex' is 'service.modifiedIndex', But the service is not changed, According to the code: https://github.com/apache/apisix/blob/master/apisix/plugin.lua#L297 .


I changed the cache key to 'route_conf.modifiedIndex .. service_conf.modifiedIndex'  , a new value will be used whatever  the route or service has changed ,and also change the  'new_conf.modifiedIndex'  property as 'route_conf.modifiedIndex' (actually the service 'modifiedIndex') .

According to this PR: https://github.com/apache/apisix/pull/2121
