### ISSUE TITLE
request help: move `conf/cert` to `t/cert`

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2110]
all of these files are ONLY for test cases.

**Comment by Yiyiyimu** [comment]
Do we also need to change the path in Makefile?
https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/Makefile#L124

**Comment by moonming** [comment]
> Do we also need to change the path in Makefile?
> 
> https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/Makefile#L124

we shoule remove this line :)

**Comment by Yiyiyimu** [comment]
> we shoule remove this line :)

Sure thx

**Comment by Yiyiyimu** [comment]
https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L301
https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L366

It seems there is need to configure ssl_certificate when start apisix

**Comment by moonming** [comment]
the default of https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L64 is empty, so I think we can also remove https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L366-L367.
@nic-chen  what do you think?

**Comment by nic-chen** [comment]
> the default of https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L64 is empty, so I think we can also remove
> 
> https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L366-L367
> 
> .
> @nic-chen what do you think?

sure, i think it's better empty default.

**Comment by Yiyiyimu** [comment]
> the default of https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L64 is empty, so I think we can also remove
> 
> https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L366-L367
> 
> .
> @nic-chen what do you think?

When the the default is set empty, apisix would chose to use cert&key in conf/cert

https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L289-L303

**Comment by Yiyiyimu** [comment]
Hi @moonming @nic-chen any suggestions?

**Comment by moonming** [comment]
@nic-chen please take a look, this PR bolcked 2.1 release.

**Comment by nic-chen** [comment]
@Yiyiyimu 

We could  throw an error when `https_admin` is `true`, but  `cert` and `key` are not configured.

**Comment by Yiyiyimu** [comment]
> We could throw an error when `https_admin` is `true`, but `cert` and `key` are not configured.

Sure thx

> > the default of https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L64 is empty, so I think we can also remove
> > https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/bin/apisix#L366-L367
> >
> 
> sure, i think it's better empty default.

@nic-chen Does that mean the default configuration would set SSL off?

**Comment by nic-chen** [comment]
Oh, `https_admin` is disable by default:
https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/conf/config-default.yaml#L61

but, `ssl` is enable by default:
https://github.com/apache/apisix/blob/1aefe915f1a01ff7d068cfe7013676bfece2d43e/conf/config-default.yaml#L101

I think we should set it off by default, because the cert and key is useless for users.

 we need to discuss this on the maillist.

**Comment by moonming** [comment]
Is there a relationship between these two configurations?

**Comment by Yiyiyimu** [comment]
> Is there a relationship between these two configurations?

Currently `ssl` would use certs in `conf/cert` by default, so we could not remove the certs but leave `ssl` on

**Comment by moonming** [comment]
> Currently `ssl` would use certs in `conf/cert` by default,

Where is the code? I will take a look

**Comment by moonming** [comment]
Got it. I think we can turn off `SSL` by default. @membphis what do you think?

**Comment by membphis** [comment]
agree to turn off `SSL` by default

**Comment by Yiyiyimu** [comment]
And there is another problem. I'm not sure the usage and difference between `apisix_admin_ssl.crt` and `apisix.crt`, but currently  `apisix_admin_ssl.crt` could be customized in 
https://github.com/apache/apisix/blob/0ff2ab824264c1e55fafa489143e4cd68d7cc7bf/apisix/cli/ngx_tpl.lua#L236-L247
but `apisix.crt` is hard-set to
https://github.com/apache/apisix/blob/0ff2ab824264c1e55fafa489143e4cd68d7cc7bf/apisix/cli/ngx_tpl.lua#L326-L327

Do we need to let users also customize `apisix.crt`

**Comment by nic-chen** [comment]
> And there is another problem. I'm not sure the usage and difference between `apisix_admin_ssl.crt` and `apisix.crt`, but currently `apisix_admin_ssl.crt` could be customized in
> https://github.com/apache/apisix/blob/0ff2ab824264c1e55fafa489143e4cd68d7cc7bf/apisix/cli/ngx_tpl.lua#L236-L247
> 
> 
> but `apisix.crt` is hard-set to
> https://github.com/apache/apisix/blob/0ff2ab824264c1e55fafa489143e4cd68d7cc7bf/apisix/cli/ngx_tpl.lua#L326-L327
> 
> Do we need to let users also customize `apisix.crt`

yes, we should.

**Comment by Yiyiyimu** [comment]
@nic-chen thanks! Another problem: in `ngx_tpl.lua`, three files could be customized, but if they are empty only two would get default values. Do we still need `ssl_client_certificate `? If yes, which one should we use for test?

**Comment by nic-chen** [comment]
@Yiyiyimu  `ssl_client_certificate` is only used for mTLS.
