### ISSUE TITLE
request help: How to modify lua_package_path and lua_package_cpath in nginx.conf ? 

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2114]
### Issue description

How to modify lua_package_path and lua_package_cpath in nginx.conf ? 
I have config lua_package_path and lua_package_cpath in config.yaml -> nginx_config -> http，but it is not work!

config.yaml
`
nginx_config:                     # config for render the template to genarate nginx.conf
http:
    lua_package_path: "$prefix/deps/share/lua/5.1/?.lua;$prefix/deps/share/lua/5.1/?/init.lua;$prefix/?.lua;$prefix/?/init.lua;;$prefix/?.lua;./?.lua;$prefix/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;
/usr/local/share/lua/5.1/?/init.lua;$prefix/openresty/luajit/share/lua/5.1/?.lua;$prefix/openresty/luajit/share/lua/5.1/?/init.lua;"
    lua_package_cpath: "$prefix/deps/lib64/lua/5.1/?.so;$prefix/deps/lib/lua/5.1/?.so;;./?.so;/usr/local/lib/lua/5.1/?.so;$prefix/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;"
`

### Environment

* apisix version (cmd: `apisix version`): apisix-1.5
* OS: CentOS Linux release 7.7.1908 (Core) 3.10.0-1062.18.1.el7.x86_64

**Comment by Firstsawyou** [comment]
You need to modify the "apisix" configuration file. The source code package is in the "apisix/bin/" directory, and the rpm installation method is in the "/usr/bin/" directory.
![image](https://user-images.githubusercontent.com/52862365/91026400-45f7b580-e62d-11ea-9c2f-bf80ac1d2639.png)

![image](https://user-images.githubusercontent.com/52862365/91026282-219bd900-e62d-11ea-8900-2fa363119acc.png)

**Comment by xyz2b** [comment]
awesome
thank you
