### ISSUE TITLE
request help: openid-connect JSON decode failed

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix#2118]
### Issue description
Using licensed plug-ins
<img width="881" alt="image" src="https://user-images.githubusercontent.com/17898385/91145888-b7e10500-e6e8-11ea-93a7-7caff09168d8.png">
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/17898385/91145902-bc0d2280-e6e8-11ea-8e4f-9a1219e31cb5.png">

我使用的openid-connect插件，现在报这种错
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
Can you provide reproduction steps?

**Comment by idbeta** [comment]
@liubinqi2007 Did you try version 2.0?
