### ISSUE TITLE
request help: Can use SSL certificate for ectd auth ?

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2123]
### Issue description
apisix's config.yml only have user/password for etcd auth
I not find SSL certificate configure for etcd auth

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos7.6

**Comment by membphis** [comment]
that is a todo feature. it needs to support mTLS but openresty does not support this feature now

**Comment by xyz2b** [comment]
Will apifix implement this function on its own?

**Comment by xyz2b** [comment]
Will apisix implement this function on its own?

**Comment by membphis** [comment]
need to patch openresty by yourself, it is not easy for most users.

**Comment by xyz2b** [comment]
ok, thank you.
