### ISSUE TITLE
request help: should apisix support dynamic configuration?

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2124]
### Issue description
Sometime we should get some configs such as authorization  service url, we can put this configs in apisix config or plugin config.
If we put this in  apisix config ,when we change config we should restart apisix, And if we put in plugin config, We should change all plugin configs.
Should we support a global  dynamic configuration which can be change on the admin api?

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:

**Comment by idbeta** [comment]
ping @spacewander

**Comment by spacewander** [comment]
> support a global dynamic configuration which can be change on the admin api

It depends on what configuration you want to change. There is some limit in Nginx.

**Comment by gy09535** [comment]
I will close this issue
