### ISSUE TITLE
request help: move etcd cluster in docker for CI

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2125]
The Apache APISIX node and etcd are deployed on the same machine in CI. 
But in actual user environment, these two are deployed separately. We need to deploy Apache APISIX nodes and etcd cluster separately in CI, so as to be closer to the real environment and to find more potential bugs

**Comment by EnableAsync** [comment]
I tried to deploy etcd with docker and found that the latest version of etcd did not pass all the test cases.
https://github.com/EnableAsync/apisix/actions/runs/247908169

Then I changed the version of etcd to `3.2` and found that `openresty` passes all test cases, but `tengine` has one test case that does not pass.
https://github.com/EnableAsync/apisix/runs/1096251043#step:7:133

I'd like to get your help.

**Comment by moonming** [comment]
@EnableAsync Apache APISIX only supports etcd v2 now, so the latest version of etcd not pass all test cases is expected.

@membphis please take a look at tengine failed test cases: https://github.com/EnableAsync/apisix/runs/1096251043#step:7:133

**Comment by moonming** [comment]
> Then I changed the version of etcd to `3.2` and found that `openresty` passes all test cases, but `tengine` has one test case that does not pass.
> https://github.com/EnableAsync/apisix/runs/1096251043#step:7:133

I think you can ingore this error, which is not introduced by your modification.
