### ISSUE TITLE
[DISCUSS]How do we control `host delivery`

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2126]
### Issue description

- Questions

We know that APISIX will pass the request host to upstream by default, and the host can be rewritten through the `proxy-rewrite` plugin, but in some scenarios, this makes it difficult for us to use.

- Suggestions

The processing of the host by the gateway is roughly divided into three situations:
1. Pass the host.
2. Do not pass host.
3. Rewrite host.

The first and second points are two very common situations. 
the last point is very special, we can realized by `proxy-rewrite` plugin.

Whether to transfer host is more like a mark, which acts on route or upstream, we need a switch to control it conveniently.

### Environment

* apisix version : 1.5

**Comment by juzhiyuan** [comment]
OK, please provide the API Design :D

**Comment by spacewander** [comment]
Consider solved
