### ISSUE TITLE
request help: Can support multi-server config?

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2128]
### Issue description
I want to configure multi-server in nginx config, because I want to listen multi port. Can support it ? 
Or I configure multi apisix instance?

Thanks!
### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos 7

**Comment by membphis** [comment]
please provide an example of nginx.conf, I can not sure what is you need

**Comment by xyz2b** [comment]
like...

http {
...
server {
    listen 80;
    server_name www.github.com;

    location / {
        ...
    }
}

server {
    listen 8080;
    server_name www.test.com;

     location / {
        ...
     }
}
}

two severs, but listen port is not same

**Comment by membphis** [comment]
we can listen to multiple ports eg: 80 and 8000.

```shell

# foo.com:80

{
    "uri": "/*",
    "host": "foo.com"
    "vars": ["server_port", "==", "80"],                
}

# bar.com:8000

{
    "uri": "/*",
    "host": "bar.com"
    "vars": ["server_port", "==", "8000"],                
}
```

**Comment by xyz2b** [comment]
I use apisix admin api to configure, but apisix not listen in 8080 to receive requests, only have 9080 and 9443. Something wrong? 
# curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/*",
    "hosts": ["www.foo.com"],
    "remote_addrs": ["10.107.97.24"],
    "methods": ["POST", "GET"],
    "vars": [
        ["server_port", "==", "8080"]
    ],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "172.16.144.119:8081": 1
        }
    }
}'

**Comment by membphis** [comment]
need to update `bin/apisix` first, welcome PR ^_^

**Comment by xyz2b** [comment]
OK, Thanks
