### ISSUE TITLE
bug: set route fail when  ETCD host is domain in K8S env

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix#2129]
### Issue description
 
recently I am try build a helm package for Kubesphere's built-in AppStore

but if I use internal dns for etcd, it will show an error like this 
```
{"error_msg":"apisix-mhkykh-etcd-0.apisix-mhkykh-etcd could not be resolved (3: Host not found)"}
```

and here is the configuration of config.yaml
```
etcd:
  host:
    - "http://apisix-mhkykh-etcd-0.apisix-mhkykh-etcd:2379"
  prefix: "/apisix" # apisix configurations prefix
  timeout: 3 # 3 seconds
```

it works fine inside the docker cli
```
curl http://apisix-mhkykh-etcd-0.apisix-mhkykh-etcd:2379/version
{"etcdserver":"3.3.12","etcdcluster":"3.3.0"}
```

```
cat /etc/resolv.conf
nameserver 169.254.25.10
search apisix-test-liling.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

also the the resolver inside the `nginx.conf` is using local nameserver
cat conf/nginx.conf
```
    resolver 169.254.25.10 valid=30;
    resolver_timeout 5;
 ....

    init_by_lua_block {
        require "resty.core"
        apisix = require("apisix")

        local dns_resolver = { "169.254.25.10", }
        local args = {
            dns_resolver = dns_resolver,
        }
        apisix.http_init(args)
    }
```

### Environment

* apisix version (cmd: `apisix version`): 1.5-alpine
* OS: K8S 

### Minimal test code / Steps to reproduce the issue
test code:
https://github.com/lilien1010/helm-charts/tree/add_apisix_and_etcd
cd src/main
`helm dependency update apisix`
 `helm package apisix`

### What's the expected result?
it should works fine when etcd is a internal domain

**Comment by lilien1010** [comment]
that's wired
I found the nameserver is not ok,
when I try
`nslookup apisix-mhkykh-etcd-0.apisix-mhkykh-etcd`
it shows
```
Server:         169.254.25.10
Address:        169.254.25.10:53

** server can't find apisix-mhkykh-etcd-0.apisix-mhkykh-etcd: NXDOMAIN

** server can't find apisix-mhkykh-etcd-0.apisix-mhkykh-etcd: NXDOMAIN

```

**Comment by lilien1010** [comment]
![image](https://user-images.githubusercontent.com/3814966/91535359-9b8dd400-e945-11ea-8442-f2c9b6ef346e.png)

**Comment by angus9487** [comment]
User the address like this:
etcd:
      host:                          
        - "http://{{ ServiceName }}.{{ Namespace}}.svc.cluster.local:2379"

eg.     http://apisix-etcd.apisix-test.svc.cluster.local:2379
