### ISSUE TITLE
request help: how to set user-define URI in self-define plugin

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix#2137]
### Issue description
如果我想再插件里改这个地址或者自己的插件也实现一个这样的地址，我应该怎么配置，我现在如果自定义uri提示我没有匹配对应的规则
![888CD391B27FD429FFD45D5105EB5B6F](https://user-images.githubusercontent.com/17898385/91708606-23791580-ebb4-11ea-86c5-6684d509b930.jpg)
<img width="510" alt="image" src="https://user-images.githubusercontent.com/17898385/91708617-25db6f80-ebb4-11ea-8c07-ec04b425370b.png">
![image](https://user-images.githubusercontent.com/17898385/91708625-28d66000-ebb4-11ea-9926-6f31f11e7ad2.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
you need to enable the new plugin first. and please use English on the public channel.

and if you still have a problem, you need to provide a mini case in which we can get the same error with them.
