### ISSUE TITLE
request help: What IDE to use for development? How to debug?

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#2140]
### Issue description

Hello, excuse me! What IDE to use for development? How to debug? What else do I need to do besides installing OpenResty locally? I am a Java development, just started this piece, I now clone the source code, using Vscode and Intellij idea to try to execute the code, but there are always various errors!
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: windows

**Comment by moonming** [comment]
I use vacode as the IDE, and print logs to debug, and there is no modern method to debug OpenResty programs.
What error did you encounter specifically?

**Comment by membphis** [comment]
> but there are always various errors!

we should use `ngx_lua`, it is different from standard Lua.

```
"luacheck.globals": [
        "--std", "ngx_lua",
        "--no-redefined",
        "--max-line-length", "100"
    ],
```

**Comment by membphis** [comment]
I think we can close this issue

**Comment by spacewander** [comment]
Consider solved.

**Comment by anjia0532** [comment]
Try a EmmyLua plugin with IDEA? Segmentfault's blog [使用idea调试lua代码-Openresty](https://segmentfault.com/a/1190000018430640)
