### ISSUE TITLE
request help:Custom plug-in (URL)

### ISSUE THREAD

**Issue by liubinqi2007** [apache/apisix#2141]
### Issue description
If I want to change this address in my plug-in or my own plug-in implements one, what should I configure? Now if the custom URI prompts me that I don't match the corresponding rule
![888CD391B27FD429FFD45D5105EB5B6F](https://user-images.githubusercontent.com/17898385/91826015-9a271900-ec6f-11ea-8029-60e3b2eee29f.jpg)
<img width="510" alt="image" src="https://user-images.githubusercontent.com/17898385/91826020-9dbaa000-ec6f-11ea-991f-ade28ef93216.png">
![image](https://user-images.githubusercontent.com/17898385/91826029-a14e2700-ec6f-11ea-9a03-3758234f7acf.png)
I need to implement a URL in my custom plug-in, as shown in Figure 1，. But when accessing the changed URL, the prompt does not have any matching rules

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
wrong name

![image](https://user-images.githubusercontent.com/6814606/91936626-d23b6400-ed22-11ea-8656-91bb5d2b73a4.png)

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus.lua#L48

that is an example, please take a look at this plugin.
