### ISSUE TITLE
optimization: cache the parsed certs and pkeys into LRU queues to reduce the parsing overheads

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2144]
We can parse the result of `ssl. parse_pem_cert` and `ssl. parse_pem_priv_key` into LRU cache queues, this should help to reduce the CPU utilizations of `ssl_certificate_by_lua*` phase.

**Comment by membphis** [comment]
yes, this way is better. welcome PR

**Comment by tokers** [comment]
Will implement this as soon as possible.

**Comment by tokers** [comment]
The related PR was merged, i'm closing this issue.
