### ISSUE TITLE
request help: add Chaos Testing for Apache APISIX

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2152]
### Issue description
The current test does not cover various abnormal conditions such as network, disk, cpu, etc.

**Comment by Yiyiyimu** [comment]
I'd like to work on this after finish etcd v3 upgrade. [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) seems to have quite an active community. I'd like to give it a try on it.

**Comment by moonming** [comment]
cool, look forward to it

Shuyang Wu <notifications@github.com> 于 2020年9月5日周六 下午12:41写道：

**Comment by zhouqiang-cl** [comment]
@Yiyiyimu @moonming Thank you for your interest in Chaos Mesh.
 I am [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) maintainer. If you have any questions, please feel free to ping us in #project-chaos-mesh channel in the [CNCF Slack](https://join.slack.com/t/cloud-native/shared_invite/zt-fyy3b8up-qHeDNVqbz1j8HDY6g1cY4w) workspace or directly create issues in [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) repo. 

If there is any feature that you want to have, you can also create an issue in Chaos Mesh repo. We will consider it in the next version of Chaos Mesh.

Thank you again

**Comment by Yiyiyimu** [comment]
Hi @zhouqiang-cl thank you for your support!

**Comment by idbeta** [comment]
@Yiyiyimu ,i am also interested in Chaos Testing for Apache APISIX，hope to do this with you

**Comment by moonming** [comment]
> I'd like to work on this after finish etcd v3 upgrade. [Chaos Mesh](https://github.com/chaos-mesh/chaos-mesh) seems to have quite an active community. I'd like to give it a try on it.

@Yiyiyimu do you have time to do this feature? And where should we start?

**Comment by Yiyiyimu** [comment]
Hi @moonming I just have basic knowledge of Chaos Mesh. Will update my progress soon.

**Comment by Yiyiyimu** [comment]
@idbeta Glad to cooperate with you! We could share our progress here and decide how to split the workload.

**Comment by spacewander** [comment]
Surpassed by https://github.com/apache/apisix/issues/2757
