### ISSUE TITLE
bug: failed test cases about parse yaml config

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2154]
https://github.com/apache/apisix/pull/2148/checks?check_run_id=1060755809#step:6:448
https://github.com/apache/apisix/pull/2148/checks?check_run_id=1060755809#step:6:465

**Comment by membphis** [comment]
it is not a bug. the test case is testing the invalid `config.yaml`.

https://github.com/apache/apisix/blob/master/t/core/config-default.t#L51

Please pay attention to the `must_die` label
