### ISSUE TITLE
bug: can not run apisix on ARM

### ISSUE THREAD

**Issue by DHB-liuhong** [apache/apisix#2156]
### Environment

* apisix version (cmd: `apisix version`): 1.4
* OS: arm linux 7.6

### Minimal test code / Steps to reproduce the issue
1. apisix start

### What's the actual result? (including assertion message & call stack if applicable)
root@node0002 conf]# apisix start
nginx: [error] init_by_lua error: /usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:76: /usr/local/apisix//deps/lib64/lua/5.1/librestyradixtree.so: cannot open shared object file: No such file or directory
stack traceback:
        [C]: in function 'load_shared_lib'
        /usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:76: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/admin/init.lua:19: in main chunk
        [C]: in function 'require'
        /usr/local/apisix/apisix/init.lua:22: in main chunk
        [C]: in function 'require'
        init_by_lua:3: in main chunk

2.  i find that，because ffi.load(fpath) is failed。
3. i use openresty's luajit to run a test ,is failed
[root@node0002 bin]# pwd
/usr/local/openresty/luajit/bin
[root@node0002 bin]# cat test.lua
local ffi = require("ffi")
local t="/usr/local/apisix/deps/lib64/lua/5.1/librestyradixtree.so"
--local f = io.open(t)
--if f ~= nil then
--    print("test")
--end
print("test11111")
local c = ffi.load(t)

print("test22222")
[root@node0002 bin]# ll
total 520
lrwxrwxrwx 1 root root     18 Sep  3 14:28 luajit -> luajit-2.1.0-beta3
-rwxr-xr-x 1 root root 527096 Sep  3 14:24 luajit-2.1.0-beta3
-rw-r--r-- 1 root root    226 Sep  3 14:01 test.lua
[root@node0002 bin]# ./luajit test.lua
test11111
./luajit: test.lua:8: /usr/local/apisix/deps/lib64/lua/5.1/librestyradixtree.so: cannot open shared object file: No such file or directory
stack traceback:
        [C]: in function 'load'
        test.lua:8: in main chunk
        [C]: at 0x00404bd0
4. i run this test on x86 , it is ok
5.[root@node0002 bin]# rpm -qa | grep openresty
openresty-zlib-1.2.11-3.el7.aarch64
openresty-openssl-1.1.0k-2.el7.aarch64
openresty-pcre-8.43-1.el7.aarch64
openresty-1.15.8.2-6.el7.aarch64

**Comment by DHB-liuhong** [comment]
i have solved it

**Comment by moonming** [comment]
@DHB-liuhong how to fix this issue? that will be good if you can share some details.

**Comment by DHB-liuhong** [comment]
@moonming .Apisix must be compiled on an ARM machine

**Comment by moonming** [comment]
@DHB-liuhong got it, thanks.

**Comment by ak476565** [comment]
@moonming Can you share your ARM64 image of Apisix on DockerHub? I'm having problems compiling. thank you
<img width="903" alt="截屏2021-06-04 21 45 55" src="https://user-images.githubusercontent.com/3871722/120811186-4ccd3480-c57e-11eb-9b32-289c0c0a2777.png">

**Comment by Yiyiyimu** [comment]
@ak476565 Have you retried installation, it seems the network problem. Or you could try https://luarocks.cn/ if keep failing
