### ISSUE TITLE
request help: apisix 1.3 upgrade apisix 1.5,admin api occur 403

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2157]
### Issue description
apisix 1.3 upgrade apisix 1.5,admin api occur 403
![@5TLD~5W%Y485ICMTLF7XJM](https://user-images.githubusercontent.com/68832358/92095341-1bb1af00-ee08-11ea-8f3c-904b2fa9defa.png)

### Environment
docker
* apisix version (cmd: `apisix version`): apisix 1.5
* OS:centOs

**Comment by y934317258** [comment]
![image](https://user-images.githubusercontent.com/68832358/92101575-e7da8780-ee0f-11ea-914e-12d1c246f488.png)
change api six version from 1.3 to 1.5 only

**Comment by y934317258** [comment]
After verification, 1.5 and above, when allow_admin is empty, all access is forbidden. Is this a bug？

**Comment by moonming** [comment]
@liuhengloveyou please take a look

**Comment by liuhengloveyou** [comment]
> @liuhengloveyou please take a look

OK

**Comment by spacewander** [comment]
Should be fixed by #1979
