### ISSUE TITLE
bug:prometheus plugin crash in ARM64 environment 

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2159]
### Issue description

[error] 11324#11324: *1 [lua] plugin.lua:66: load_plugin(): failed to load plugin [prometheus] err: bad light userdata pointer, context: init_worker_by_lua*

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos7.6

**Comment by imjoey** [comment]
> ### Issue description
> [error] 11324#11324: _1 [lua] plugin.lua:66: load_plugin(): failed to load plugin [prometheus] err: bad light userdata pointer, context: init_worker_by_lua_
> 
> ### Environment
> * apisix version (cmd: `apisix version`): 1.5
> * OS: centos7.6

Hi @idbeta, please refer to https://forum.openresty.us/d/6488-euleros-aarch64lua-bad-light-userdata-pointer , which indicates this had been fixed in https://github.com/LuaJIT/LuaJIT/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c , you could try to upgrade openresty to 1.19.3.1rc0 or use the latest LuaJit.

**Comment by idbeta** [comment]
> Hi @idbeta, please refer to https://forum.openresty.us/d/6488-euleros-aarch64lua-bad-light-userdata-pointer , which indicates this had been fixed in [LuaJIT/LuaJIT@e9af1ab](https://github.com/LuaJIT/LuaJIT/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c) , you could try to upgrade openresty to 1.19.3.1rc0 or use the latest LuaJit.

ok, thanks for reminding, I will try.

**Comment by spacewander** [comment]
Feel free to reopen it if the problem still exists.

**Comment by moonming** [comment]
> > Hi @idbeta, please refer to https://forum.openresty.us/d/6488-euleros-aarch64lua-bad-light-userdata-pointer , which indicates this had been fixed in [LuaJIT/LuaJIT@e9af1ab](https://github.com/LuaJIT/LuaJIT/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c) , you could try to upgrade openresty to 1.19.3.1rc0 or use the latest LuaJit.
> 
> 
> 
> ok, thanks for reminding, I will try.
> 
> 

Any response?

**Comment by idbeta** [comment]
> > ### Issue description
> > [error] 11324#11324: _1 [lua] plugin.lua:66: load_plugin(): failed to load plugin [prometheus] err: bad light userdata pointer, context: init_worker_by_lua_
> > ### Environment
> > 
> > * apisix version (cmd: `apisix version`): 1.5
> > * OS: centos7.6
> 
> Hi @idbeta, please refer to https://forum.openresty.us/d/6488-euleros-aarch64lua-bad-light-userdata-pointer , which indicates this had been fixed in [LuaJIT/LuaJIT@e9af1ab](https://github.com/LuaJIT/LuaJIT/commit/e9af1abec542e6f9851ff2368e7f196b6382a44c) , you could try to upgrade openresty to 1.19.3.1rc0 or use the latest LuaJit.

I verified it with openresty 1.19.3.1 today, there is no problem anymore.
