### ISSUE TITLE
request help: multi-tenancy/multi-workspace feature

### ISSUE THREAD

**Issue by masahills** [apache/apisix#2165]
### Issue description
Hi,
Do you have any plan to introduce multi-tenancy feature into APISIX?
The motivation for this feature is that we want to let multiple internal organizations/teams to manage only their own configurations without affecting others. A concept of this feature is called 'Workspace' in Kong Enterprise Edition.

**Comment by moonming** [comment]
There is no plan yet. Do you have a general plan for this?
 I am concern that this will increase the cost of user learning and use, not every user needs multi-tenancy.

**Comment by masahills** [comment]
We have hundreds of internal API endpoints which go through a cluster of API gateway servers. It is a typical micro-service architecture and each API is developed and owned by different engineering teams within an organization.

Managing all of those API configurations by a single devops team is not a realistic approach so we want each engineering team to manage their own API configurations with a proper account management (i.e. an internal IdP or Azule AD.)

Since APISIX can update all API configurations without server restarts, it is a perfect solution for API management for micro-service architecture systems. I think this is a common requirement for organizations that use an API gateway systems. Since those users who need an API gateway, they usually have to control a large number of APIs from various sources with different polices and requirements. Managing those with a single devops team becomes nightmare as the number of configurations grows.

I'm hoping that the feature is included in your roadmap sometime in the future.

**Comment by spacewander** [comment]
@moonming 
I remember we move this feature to Enterprise version?

**Comment by moonming** [comment]
yes.

Thanks,
Ming Wen
Twitter: _WenMing


罗泽轩 <notifications@github.com> 于2020年12月24日周四 上午10:40写道：

**Comment by prakharbirla-ng** [comment]
@moonming , apologies for using an old thread!

When you say enterprise version, do you mean [API7](https://api7.ai/) or something else? I couldn't find information about an APISIX enterprise version. Thanks

**Comment by moonming** [comment]
> [@moonming](https://github.com/moonming) , apologies for using an old thread!
> 
> When you say enterprise version, do you mean [API7](https://api7.ai/) or something else? I couldn't find information about an APISIX enterprise version. Thanks

@prakharbirla-ng please take a look https://docs.api7.ai/apisix/enterprise-feature/overview
