### ISSUE TITLE
feat: how use apisix send log to aliyun sls

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2169]
### Issue description
How apisix can send log to aliyun? I think ailiyun support syslog standard rfc5424( https://help.aliyun.com/document_detail/112903.html?spm=a2c4g.11186623.6.763.28801b47aqgVZq).

But the nginx support syslog standard rfc3164(http://nginx.org/en/docs/syslog.html).

And I can not find the log message format filed "STRUCTURED-DATA" in rfc3164(https://tools.ietf.org/html/rfc3164#section-4.1.1 ),But find it in rfc5424(https://tools.ietf.org/html/rfc5424?spm=a2c4g.11186623.2.17.5b0f1b47l82QJg).

So I am confused how should I use it in syslog plugin.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@membphis @gxthrj please take a look

**Comment by gy09535** [comment]
I have see the repository  of  https://github.com/cloudflare/lua-resty-logger-socket，It just implementation  socket log to send log to  syslog-ng(collector)  source.The syslog-ng has source and destination. I should publish "syslog-ng" for proxy for ali cloud  log service(sls). I think should I send log to sls without proxy.

**Comment by membphis** [comment]
I think we can send the log to aliyun sls is an easy way, and that is a stable way.

use `lua-resty-logger-socket` is a better way.

**Comment by membphis** [comment]
another way, set `syslog` server in `conf/config.yaml` is another good method

**Comment by gy09535** [comment]
> I think we can send the log to aliyun sls is an easy way, and that is a stable way.
> 
> use `lua-resty-logger-socket` is a better way.

Agree with you and I use cosocket implementation it, please review

**Comment by membphis** [comment]
welcome PR，then the community can share this feature. ^_^

**Comment by gy09535** [comment]
> welcome PR，then the community can share this feature. ^_^
I use cosocket  and processor to  send logs to sls , you can define different routes or services plugins to send logs to different log store which in sls. you can use sls  do anythings such as data analysis  monitor  and alarm soon. For us I finish the doc, users can reference sls logger doc to use it.
