### ISSUE TITLE
feature(core): implement `core.sleep`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2170]
Use a small time interval (such as 1s) to complete a relatively long sleep behavior, so that the worker process can be shut down gracefully.

Here is the fake code(we may):

```lua
function sleep(sec)
    if sec <= 1 then
        ngx_sleep(sec)
        return
    end

    while true do
        if sec > 1 then
            ngx_sleep(1)
        end

        if exiting() then
            return
        end

        sec = sec - 1
        if sec < 1 then
            ngx_sleep(sec)
            return
        end
    end
end
```

**Comment by tokers** [comment]
Maybe a readable name is also important to imply the difference, like `interrupted_sleep`

**Comment by dabue** [comment]
please assign it to me.

**Comment by dabue** [comment]
I will add a new function 'sleep' to  'core.utils', and replace all 'sleep = ngx.sleep' with 'sleep = core.utils.sleep'. Is that OK?

**Comment by dabue** [comment]
I 'll add a new function sleep to the file apisix/core.lua, and replace all filed ‘sleep = ngx.sleep’  with 'sleep = require("apisix.core.sleep")'. Is that OK?

**Comment by membphis** [comment]
it is fine, let us do it ^_^
