### ISSUE TITLE
bug: kafka-logger plugin comes with exception logs

### ISSUE THREAD

**Issue by GBXing** [apache/apisix#2175]
### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:Ubuntu
### Minimal test code / Steps to reproduce the issue
1. Add Kafka-logger to the route and access it

### What's the actual result? (including assertion message & call stack if applicable)
Normal functionality, but with exception logging
error.log:
 2020/09/07 14:39:03 [error] 502#502: *169385 [lua] batch-processor.lua:61: Batch Processor[kafka logger] failed to process entries: nil, context: ngx.timer, client: 172.29.64.1, server: 0.0.0.0:9080
2020/09/07 14:39:03 [error] 502#502: *169385 [lua] batch-processor.lua:68: Batch Processor[kafka logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 172.29.64.1, server: 0.0.0.0:9080

**Comment by moonming** [comment]
the default value of `max_retry_count` is 0, you can increase this value then try.
@sshniro Is it small to set `max_retry_count` default value to 0?

**Comment by GBXing** [comment]
@moonming  Setting max_retry_count to 2 still generates an exception log, and the log is sent three times

**Comment by GBXing** [comment]
@moonming 
Finding that the result is not returned in [(https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L91)] results in the failure of the BacthProcessor to obtain the result, thereby determining that the message delivery failed.

**Comment by sshniro** [comment]
@GBXing I assume the issue relies on the connectivity to the Kafka or a bug inside the logger. The batch processor is a standalone module that is used in other loggers and does not have an issue in batching and sending the requests.

@moonming yes for default we can set max_retry count to zero as well.

Please take a look at this PR as well: https://github.com/apache/apisix/pull/2222 , probably this might be the fix.

**Comment by spacewander** [comment]
@GBXing 
Since #2222 is merged, is your issue fixed now?

**Comment by spacewander** [comment]
Consider solved as the author didn't reply.
