### ISSUE TITLE
request help: How to configure timeout settings?

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2176]
### Issue description
How to configure timeout settings?
Such as: proxy_connect_timeout, proxy_send_timeout, proxy_read_timeout and so on.

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos 7.5

**Comment by ShiningRush** [comment]
There is currently no way to set these values. We can record this requirement and expose it in soon.
As a workaround, you can modify the configuration content in `bin/apisix` to set those values.

**Comment by xyz2b** [comment]
ok, thanks
