### ISSUE TITLE
Windows Platform how to run APisix, how to debug 

### ISSUE THREAD

**Issue by yuansh** [apache/apisix#2178]
### Issue description

Apisix project has been running in CENTOS7 environment, and now we need to develop custom plug-ins. We did not see the documents about the deployment and compilation of the project under Windows platform on the problems we encountered. Could you please provide the reference documents?I use the IDE (Visual Studio Code) and the platform (Windows) to run lua project operations from the IDE.
The error is as follows:
[error] .\apisix\core\log.lua:19: attempt to index a nil value (local 'ngx')

Is there a reference for developing plug-ins under Windows (dependent package installation)
### Environment

* apisix version (cmd: `apisix version`):1.5.1
* OS:windows 10

**Comment by moonming** [comment]
Apache APISIX has not been tested on windows system, so there may be problems. Going back to your error, it seems that OpenResty is not installed correctly

**Comment by yuansh** [comment]
Thanks a lot. I'll try some other operating systems

**Comment by moonming** [comment]
you are welcome.

**Comment by Dule-mart** [comment]
Hello

I read your last message about not testing Apache APISIX on windows yet, is this still the case to date for windows?

**Comment by tzssangglass** [comment]
yes, we do not yet offer support for windows perfect build APISIX.

**Comment by juzhiyuan** [comment]
How about using WSL? @Dule-mart you could try WSL

**Comment by chenyyyang** [comment]
Do you have any  tutorials about how to install apisix with WSL(ubuntu)?
@juzhiyuan  @tzssangglass 
Thank you

**Comment by juzhiyuan** [comment]
Hi @chenyyyang, I don't have a windows environment to try this case, but I find two other posts may help you:

1. https://lentimo.medium.com/installing-apache-apisix-on-windows-78068d3d378a
2. https://juejin.cn/post/7089413228987416584
