### ISSUE TITLE
request help: support geoip as judgment condition

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2180]
### Issue description
as discuss in https://lists.apache.org/thread.html/r947d414b42900ec8e73f0c7366513e80da74b33261effb664901da2d%40%3Cdev.apisix.apache.org%3E

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
Look like we already support it.
We can use `$geoip` and the `var` in route.
