### ISSUE TITLE
bug: error in the pod when deploying apisix-gw-config-cm.yaml in kubernetes

### ISSUE THREAD

**Issue by maxluo1992** [apache/apisix#2182]
### Issue description
根据本项目中kubernetes的部署步骤操作，在部署apisix-gw-config-cm.yaml发现pod内报错
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:701: failed to read `apisix` field from yaml file
stack traceback:
        [C]: in function 'error'
        /usr/bin/apisix:701: in function </usr/bin/apisix:668>
        /usr/bin/apisix:922: in main chunk
        [C]: at 0x00404c00

### Environment

* apisix version (cmd: `apisix version`):
* OS:
Centos7
二进制安装的K8S1.18.3
etcd是部署在K8S集群外的

**Comment by moonming** [comment]
@maxluo1992 Please use English in the public channel, thx
@gxthrj please take a look, thx

**Comment by maxluo1992** [comment]
OK




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wen Ming"<notifications@github.com&gt;; 
发送时间: 2020年9月8日(星期二) 中午12:04
收件人: "apache/apisix"<apisix@noreply.github.com&gt;; 
抄送: "Max Luo"<963679535@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [apache/apisix] request help:  (#2182)





 
@ maxluo1992请在公共频道上使用英语，thx 
 @gxthrj请看一下，thx
 
— 
您收到此邮件是因为有人提到您。
直接回复此电子邮件，在GitHub上查看，或取消订阅。

**Comment by nic-chen** [comment]
@maxluo1992  please take a look at your local `apisix-gw-config-cm.yaml`, what is the content in it ?

**Comment by maxluo1992** [comment]
This is config.yaml file content.
apiVersion: v1
data:
  config.yaml: |
kind: ConfigMap
metadata:
  name: apisix-gw-config.yaml
  namespace: default
dns_resolver:
  - 10.244.3.14

**Comment by maxluo1992** [comment]
This is config.yaml file content:
```yaml
apiVersion: v1
data:
  config.yaml: |
kind: ConfigMap
metadata:
  name: apisix-gw-config.yaml
  namespace: default
dns_resolver:
  10.244.3.14

**Comment by tokers** [comment]
@maxluo1992 
You should put the whole configuration file data into the `data` field of ConfigMap object, rather than add some fields like `dns_resolver` in ConfigMap own's spec.

**Comment by maxluo1992** [comment]
Ok, I will have a try and give you the feedback if possible.

**Comment by gxthrj** [comment]
> This is config.yaml file content:
> 
> ```yaml
> apiVersion: v1
> data:
>   config.yaml: |
> kind: ConfigMap
> metadata:
>   name: apisix-gw-config.yaml
>   namespace: default
> dns_resolver:
>   10.244.3.14
> ```

```yaml
apiVersion: v1
data:
  config.yaml: |
  dns_resolver:
    10.244.3.14
kind: ConfigMap
metadata:
  name: apisix-gw-config.yaml
  namespace: default

```
the `dns_resolver ` should be in `data` field

**Comment by gxthrj** [comment]
need to update the doc for deploying APISIX in k8s

**Comment by maxluo1992** [comment]
@gxthrj I found that APISIXl uses the http protocol to connect to etcd, but the etcd of the k8s cluster uses the mandatory https protocol, so it cannot connect.

**Comment by gxthrj** [comment]
@maxluo1992 We close this issue now .
And discussing [here](https://github.com/apache/apisix/issues/2814) about supporting `https` when connecting to etcd.
