### ISSUE TITLE
bug: Can't see the route created using api in dashboard

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix#2183]
### Issue description
使用curl api接口的方式创建了路由，然后在etcd中也能get到值，但是dashboard中却没有创建的路由

### Environment
centos 7

* apisix version (cmd: `apisix version`):
* OS: v1.5

### Minimal test code / Steps to reproduce the issue
1.  curl --location --request POST 'http://10.1.9.115:9080/apisix/admin/routes' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "uri": "/index.html",
    "hosts": ["paa.com", "*.maa.com"],
    "remote_addrs": ["127.0.0.0/8"],
    "methods": ["PUT", "GET"],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "172.17.0.1:80": 1
        }
    }
}'
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
{
    "node": {
        "value": {
            "priority": 0,
            "methods": [
                "PUT",
                "GET"
            ],
            "uri": "/index.html",
            "remote_addrs": [
                "127.0.0.0/8"
            ],
            "hosts": [
                "paa.com",
                "*.maa.com"
            ],
            "upstream": {
                "nodes": {
                    "172.17.0.1:80": 1
                },
                "hash_on": "vars",
                "type": "roundrobin"
            }
        },
        "createdIndex": 4399,
        "key": "/apisix/routes/00000000000000004399",
        "modifiedIndex": 4399
    },
    "action": "create"
}

### What's the expected result?
能在dashboard中能看到通过curl api接口的方式创建的路由条目

**Comment by moonming** [comment]
@chenyicai Please use English in the public channel, thx
for this issue, yes, this is the bug of dashboard, and we will fix by https://github.com/apache/apisix-dashboard/issues/434, we plan to remove mysql and only read/write from etcd.

**Comment by chenyicai** [comment]
ok,thank you very much, i will use English next time！

**Comment by moonming** [comment]
Thanks for your understanding
