### ISSUE TITLE
bug: limit-conn，After limiting concurrency for the first time, all subsequent requests are blocked

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2184]
### Issue description
limit-conn，After limiting concurrency for the first time, all subsequent requests are blocked
### Environment

* apisix version (cmd: `apisix version`):master
* OS:centOs

### Minimal test code / Steps to reproduce the issue
1.config
![image](https://user-images.githubusercontent.com/68832358/92451999-0e256c00-f1f0-11ea-80aa-30ba54f6af29.png)
2.first.it's true
![image](https://user-images.githubusercontent.com/68832358/92452064-25645980-f1f0-11ea-9f00-7ef649b156db.png)
3.then,error occur
![image](https://user-images.githubusercontent.com/68832358/92452131-39a85680-f1f0-11ea-8e67-b587bccfa78f.png)
### What's the actual result? (including assertion message & call stack if applicable)
After limiting concurrency for the first time, all subsequent requests are blocked

### What's the expected result?
like first

**Comment by moonming** [comment]
Can you provide reproduction steps using admin API? @y934317258  thx

**Comment by spacewander** [comment]
Closed as lack of response.
