### ISSUE TITLE
request help:  url_block.lua plugin: Is there any performance bottleneck if there are many block rules, say 1000000 url rules in production enviroment

### ISSUE THREAD

**Issue by fankeke** [apache/apisix#2188]
### Issue description
plugin： url_blocker.lua

```
local from = re_find(ctx.var.request_uri, conf.block_rules_concat, "jo")
```

Is there any performance bottleneck if there are many block rules, say 1000000 url rules  in production enviroment

Every request will be handled by block plugin.

**Comment by fankeke** [comment]
@membphis

**Comment by fankeke** [comment]
Every request will be handled by block plugin.

**Comment by membphis** [comment]
Improving performance mainly depends on the quality of the rules.

For runtime selection, if better performance is required, streaming matching such as hyperscan is needed.

**Comment by membphis** [comment]
you can take a look at this benchmark result: https://rust-leipzig.github.io/regex/2017/03/28/comparison-of-regex-engines/

**Comment by fankeke** [comment]
Improving performance mainly depends on the quality of the rules.

=======
thanks for reply

In our system, there are already 1+ million block urls， if every request should be match with each url urls， I'm afraid it won't work. :(

**Comment by tokers** [comment]
> Improving performance mainly depends on the quality of the rules.
> 
> =======
> thanks for reply
> 
> In our system, there are already 1+ million block urls， if every request should be match with each url urls， I'm afraid it won't work. :(

Then a good data structure (something like Trie Tree, or AC Automata?) might be used to optimize the match process, :).

**Comment by spacewander** [comment]
There is also a library to match plain text in parallel: https://github.com/cloudflare/lua-aho-corasick.

@fankeke 
Can we divide the 1+ million block urls into groups according to their hosts?

**Comment by fankeke** [comment]
Can we divide the 1+ million block urls into groups according to their hosts?

===========

@spacewander the whole 1+million urls only for one host(upstream)  :)

**Comment by moonming** [comment]
> Improving performance mainly depends on the quality of the rules.
> 
> For runtime selection, if better performance is required, streaming matching such as hyperscan is needed.

uri match is none business with streaming match

**Comment by moonming** [comment]
> Can we divide the 1+ million block urls into groups according to their hosts?
> 
> ===========
> 
> @spacewander the whole 1+million urls only for one host(upstream) :)

Can you give some examples?
On the other hand, why are there a million regex rules under the same host?

**Comment by spacewander** [comment]
Closed as lack of response.
