### ISSUE TITLE
request help: What is the current circuit breaker strategy and where is it introduced

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2190]
### Issue description
What is the current circuit breaker strategy and where is it introduced?
For example, if the threshold value is reached in the monitoring period, it will fuse. How long can it be recovered after fusing
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@y934317258 sorry for the late reply. 
This is configurable, please take a look at https://github.com/apache/apisix/blob/master/doc/health-check.md.

**Comment by spacewander** [comment]
Consider solved.
