### ISSUE TITLE
bug  zipkin Arguments

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#2191]
- parameters passed when using the function

https://github.com/apache/apisix/blob/3ece377d3ff920a3f46c0fa93312e5d7b276f63f/apisix/plugins/zipkin/codec.lua#L101-L103

- the actual parameters defined by the function
> https://github.com/iresty/opentracing-openresty/blob/master/opentracing/span_context.lua#L33-L37
```lua
-- Public constructor
local function new(trace_id, span_id, parent_id, baggage)
	if trace_id == nil then
		trace_id = generate_trace_id()
....
```

- error log

```text
apisix_1    | 2020/09/09 03:14:32 [error] 24#24: *61 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/zipkin/codec.lua:116: bad argument #1 to '(for generator)' (table expected, got boolean)
apisix_1    | stack traceback:
apisix_1    | coroutine 0:
apisix_1    |   [C]: in function '(for generator)'
apisix_1    |   /usr/local/apisix/apisix/plugins/zipkin/codec.lua:116: in function 'inject'
apisix_1    |   /usr/local/apisix/apisix/plugins/zipkin.lua:156: in function 'phase_fun'
apisix_1    |   /usr/local/apisix/apisix/init.lua:130: in function 'run_plugin'
apisix_1    |   /usr/local/apisix/apisix/init.lua:315: in function 'http_access_phase'
apisix_1    |   access_by_lua(nginx.conf:167):2: in main chunk, client: 172.16.215.41, server: , request: "POST /event/xxxx HTTP/1.1", host: "172.16.210.58:9080"
```

**Comment by dickens7** [comment]
when `x-b3-sampled` is 1, the BUG is triggered

**Comment by spacewander** [comment]
Look like the sample argument is removed since https://github.com/iresty/opentracing-openresty/pull/2/files. But the code in apisix didn't update for it.
CC @moonming

**Comment by moonming** [comment]
> Look like the sample argument is removed since https://github.com/iresty/opentracing-openresty/pull/2/files. But the code in apisix didn't update for it.
> CC @moonming

yes, you are right. 
@dickens7 welcome PR https://github.com/dickens7/apisix/commit/1b969cf3ad224dda6211219c686d01a59b3f7cca
