### ISSUE TITLE
feature(kafka-logger):  need to read the request body data if it was cached to local file

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2196]
https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L67

The file name is not enough.
we need to read the file content.

**Comment by swayamraina** [comment]
Hi @membphis 
I would like to pick this up. Can you describe what exactly is required here?

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L67

```lua
local body_file = ngx.req.get_body_file()
if body_file then
    -- we only readed the file name of request body, it is not enough.
    -- we need to read the file content by file name.
    log.request.body_file = body_file
end
```

for how to read file content by file name, you can take a look at this: https://stackoverflow.com/questions/11201262/how-to-read-data-from-a-file-in-lua

**Comment by membphis** [comment]
@swayamraina I have assigned this issue to you, many thx

**Comment by swayamraina** [comment]
@membphis  I got what exactly is required here and will raise a PR.
I had one question though, why would request body data get cached to a local file and be absent in the request body

**Comment by sshniro** [comment]
@membphis any idea how to create this scenario? Where the body is kept in a local file? Does it occur if the data is too big?

**Comment by membphis** [comment]
> Does it occur if the data is too big?

you are right. for more detail information, you can take a look at: https://github.com/openresty/lua-nginx-module#ngxreqread_body

I think that if the request body is big, we can only read the first 1 MB of the request body data.

**Comment by spacewander** [comment]
@membphis 
Is this feature still required?

**Comment by membphis** [comment]
> @membphis Is this feature still required?

yes, we need this feature.

**Comment by spacewander** [comment]
I don't think it is a good idea. As the disk operation is expensive and it only happens when the body is too large. Reading truncated body is not so helpful in the log.

**Comment by tzssangglass** [comment]
Would it be better to adjust the parameters to avoid the request being logged in the file?

**Comment by tokers** [comment]
> Would it be better to adjust the parameters to avoid the request being logged in the file?

There has a trade-off between the memory usage and the disk operations, but it should be decided by the user.

**Comment by membphis** [comment]
Hope to hear more users' voices.
