### ISSUE TITLE
request help: How to ensure the security of token without password

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2197]
### Issue description

How to ensure the security of token without password
![image](https://user-images.githubusercontent.com/68832358/92564885-76d21e80-f2ac-11ea-8a73-3cd1e0add842.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by y934317258** [comment]
I don't understand the meaning of this plug-in. In my opinion, it is extremely unsafe. Can you introduce its usage scenarios?

**Comment by y934317258** [comment]
@membphis

**Comment by membphis** [comment]
the client needs to know the valid `user-key` first, then the client can request the source he needs with token.

for more information about JWT token, you can take a look at: https://jwt.io/introduction/
