### ISSUE TITLE
request help:  How to deploy apisix 

### ISSUE THREAD

**Issue by liuximu** [apache/apisix#2198]
### Issue description
求官方确认一下：
 apache/apisix 包括两个职责，有两种部署方式：
1 被放到线上部署成API-Gateway集群，关闭api相关的接口，作为数据面
2 被放到内网部署成管理平台，开源被 apisix-dashboard 调用完成配置的变更

是这样子吗？谢谢

**Comment by moonming** [comment]
Please use English in the public channel, thx
Your understanding is right, DP and CP are communicate through etcd, here is the technical architecture of Apache APISIX: https://github.com/apache/apisix/blob/master/doc/images/apisix.png

**Comment by idbeta** [comment]
I think this issue can be closed, @spacewander
