### ISSUE TITLE
request help: The parameter meaning of JWT auth plug-in. What are the functions of parameter configuration in consumer and routing

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2199]
### Issue description
The parameter meaning of JWT auth plug-in. What are the functions of parameter configuration in consumer and routing
![image](https://user-images.githubusercontent.com/68832358/92565615-80a85180-f2ad-11ea-9719-cd601b9b56a8.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
@juzhiyuan please take a look. Is this a TODO?

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/issues/2082#issue-681772868

We have fixed a couple of plugins' schema, I will add this one to the TODO list.

**Comment by idbeta** [comment]
In the latest dashboard version, the plugin can be set up through codemirror, and there is also a link for the plugin setting document, and there are also prompt messages for the setting errors of the consumer and plugin, so I think this issue has been fixed. If there are better suggestions, I should it be a new issue. @juzhiyuan @spacewander

**Comment by juzhiyuan** [comment]
Hi, in Dashboard we will use Plug-in Editor to operate plug-in data for now. We may support form when it's ready.
