### ISSUE TITLE
request help: use core.log Output log, output to which file

### ISSUE THREAD

**Issue by y934317258** [apache/apisix#2201]
### Issue description
use core.log Output log, output to which file

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by linsir** [comment]
`logs/error.log`

**Comment by y934317258** [comment]
> `logs/error.log`
No matter what level of log, is it output to error.log ?

**Comment by linsir** [comment]
no, should change the `error_log_level`.<https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L112> @y934317258
