### ISSUE TITLE
feature: allow empty `service` object, it does not contain any `upstream` and `plugin`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2202]
Sometimes users create an empty service (managed through API).

When needed later, add specific attributes, such as plug-ins, upstream, etc.

just remove this limitation and add test case to check it.

https://github.com/apache/apisix/blob/master/apisix/schema_def.lua#L476-L481

**Comment by Firstsawyou** [comment]
Assigned to me.

**Comment by spacewander** [comment]
Solved.
