### ISSUE TITLE
bug: “prevNode” should not return after setting a route

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2204]
### Issue description
set twice route in the same uri，the second response should not include “preNode”
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
...
{"action":"set","node":{...},"**prevNode**":{...}}

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos7

**Comment by moonming** [comment]
yes, agreed, we can remove the `prevNode` section now. 
Welcome PR

**Comment by idbeta** [comment]
it was fixed in v2.0
