### ISSUE TITLE
request help: websocket proxy

### ISSUE THREAD

**Issue by MrJLuo** [apache/apisix#2207]
### Issue description
1.Use APISIX to proxy the websocket protocol. If you need to use the http protocol to forward to the upstream, can you only rewrite the header through the proxy-rewrite plugin?
2.By default, apisix forwards the same protocol directly to the upstream?

### Environment

* apisix version (cmd: `apisix version`):v1.5
* OS:linux centos 7.2

**Comment by membphis** [comment]
By default, apisix transparently transmits user parameters.

If you need to rewrite a client request (such as a scheme), you need to rewrite it through the proxy-rewrite plug-in.
