### ISSUE TITLE
Is Apache APISIX support strip_path in Kong?

### ISSUE THREAD

**Issue by mlick** [apache/apisix#2208]
### Issue description

![image](https://user-images.githubusercontent.com/8747500/92697047-5a51e700-f37d-11ea-9107-0b8687dd068e.png)
Similar to the configuration of nginx, if there is a root directory / behind, this /sugrec will not be appended to the address of baidu.com, if not, it will be appended automatically.
The default of kong is true, which means it will automatically strip the path on the route.
### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos 7.4

**Comment by moonming** [comment]
Is this configure? https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L83

**Comment by moonming** [comment]
Please use English in the public channel, thx

**Comment by mlick** [comment]
@moonming got it thanks!

**Comment by spacewander** [comment]
Consider solved.

**Comment by pengtaochang** [comment]
![image](https://user-images.githubusercontent.com/39374127/105465004-5770e680-5ccd-11eb-96fd-b31bfb102418.png)
I using proxy_rewrite plugin achieve the strip_path feature. Hope it's helpful.
