### ISSUE TITLE
can router support uri+params style

### ISSUE THREAD

**Issue by powermanlc** [apache/apisix#2213]
### Issue description
I have a question, normally router matched /a/b/c, 
can support **/aa/bb/cc?d=1&e=2** this http get method, params connect the uri.

### Environment

* apisix version (cmd: `apisix version`): 1.3
* OS:

**Comment by spacewander** [comment]
You can route via Nginx builtin variable: https://github.com/apache/apisix/blob/master/doc/router-radixtree.md#how-to-filter-route-by-nginx-builtin-variable

**Comment by powermanlc** [comment]
> You can route via Nginx builtin variable: https://github.com/apache/apisix/blob/master/doc/router-radixtree.md#how-to-filter-route-by-nginx-builtin-variable

thank you.
