### ISSUE TITLE
Used TscanCode scan the lua code,it report two code defects

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2215]
### Issue description
.../t/lib/test_admin.lua: Code line 223,undeclared Variable [core] is used.
../apisix/http/router/radixtree_sni.lua: Code line 187,[radixtree_router] is used after check at line 172

**Comment by spacewander** [comment]
Which version of apisix the TscanCode works on? The lines don't match the master branch of apisix.

**Comment by membphis** [comment]
> .../t/lib/test_admin.lua: Code line 223,undeclared Variable [core] is used.

https://github.com/apache/apisix/blob/master/t/lib/test_admin.lua#L222-L225

it should be defects, we need to fix it.

**Comment by idbeta** [comment]
@spacewander it's apisix 1.5 master branch
[.../apisix/http/router/radixtree_sni.lua:162]: (Critical) [radixtree_router] is used after check at line 147
[.../t/lib/test_admin.lua:223]: (Critical) Undeclared variable [core] is used.

**Comment by spacewander** [comment]
> [radixtree_router] is used after check at line 147

Look like it is a false positive.
