### ISSUE TITLE
How to get the parameters of the post request in the log plugins

### ISSUE THREAD

**Issue by zwwhub** [apache/apisix#2220]
It seems that the input parameters of the post request are not recorded in tcp-logger and http-logger

**Comment by zwwhub** [comment]
When I tried to modify the plugin source code to get the parameters through method ngx.req.get_post_args(), an error was reported: API disabled in the context of ngx.timer

**Comment by gy09535** [comment]
The nginx timer is out of request life cycle , you can get it in the  log event  of plugin, and  other way  the log plugin is already support get request body, you can just send an parameter  named "include_req_body". Maybe we should add it in the [doc](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/syslog.md).

**Comment by zwwhub** [comment]
i get it,thanks
