### ISSUE TITLE
CLI: Check the etcd version in CLI. The version must be 3.4 or greater.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2227]
comments:

https://github.com/apache/apisix/pull/2036#issuecomment-691957197

**Comment by tokers** [comment]
@membphis May i pick it up?

**Comment by moonming** [comment]
sure, assigned to you @tokers

**Comment by Yiyiyimu** [comment]
Sorry @tokers I just noticed you pick up this issue. I fixed it in the [new commit](https://github.com/apache/apisix/pull/2036/commits/58e8401a24ceed0313702903103ea4e608128021). But it would still be great if you could review it

**Comment by tokers** [comment]
I think it can be closed now since it was fixed in https://github.com/apache/apisix/pull/2233.

**Comment by tokers** [comment]
> Sorry @tokers I just noticed you pick up this issue. I fixed it in the [new commit](https://github.com/apache/apisix/pull/2036/files/d2e3d01eb9f17ff16fd40f14bf0c5d1017d047ce..0570fdb4e5ecb490f76ac0947bae8e034fed70c8). But it would still be great if you could review it~

:)

**Comment by Yiyiyimu** [comment]
> I think it can be closed now since it was fixed in #2233.

ping @membphis

**Comment by tokers** [comment]
ping @membphis @moonming

**Comment by moonming** [comment]
> ping @membphis @moonming

thanks for your remind
