### ISSUE TITLE
request help: "consumer" provides access to a collection of "service".

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2229]
### Issue description
Configure multiple "service" objects. I want to restrict the "service" on the "consumer". What should I do?
For example: "service" has: serv1, serv2 and serv3. In "consumer", only ser1 and serv2 are allowed to access, but serv3 is not allowed.

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:

**Comment by moonming** [comment]
This is what identity authentication needs to do, such as ACL, right?

**Comment by Firstsawyou** [comment]
> This is what identity authentication needs to do, such as ACL, right?

Yes.

**Comment by moonming** [comment]
the same as https://github.com/apache/apisix/issues/385

**Comment by Firstsawyou** [comment]
Assigned to me.

**Comment by moonming** [comment]
How do you plan to implement this feature?

**Comment by Firstsawyou** [comment]
> How do you plan to implement this feature?

It is planned to create a whitelisted plug-in through "service_id", which is bound to "consumer".

**Comment by Firstsawyou** [comment]
> the same as #385

Ok，let me take a look.

**Comment by moonming** [comment]
please take a look at kong's ACL plugin too:
https://docs.konghq.com/hub/kong-inc/acl/

Thanks,
Ming Wen
Twitter: _WenMing


Firstsawyou <notifications@github.com> 于2020年9月15日周二 下午1:29写道：
