### ISSUE TITLE
bug: etcd_version in ./bin/apisix is not defined

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2234]
### Issue description

The variable `etcd_version` in ./bin/apisix is not defined, comment see [here](https://github.com/apache/apisix/pull/2036/files#diff-62edadffc237f13dc28a694080d293a8R918).

**Comment by moonming** [comment]
good catch, welcome PR to fix

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/2233
