### ISSUE TITLE
bug(CLI): need to call `os.exit(false)`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2240]
Calls the ISO C function exit to terminate the CLI program.

for example:

https://github.com/apache/apisix/blob/master/bin/apisix#L77
https://github.com/apache/apisix/blob/master/bin/apisix#L902
https://github.com/apache/apisix/blob/master/bin/apisix#L908

**Comment by idbeta** [comment]
ping @membphis @spacewander This issue has been fixed in version 2.0, pls close it.
