### ISSUE TITLE
request help: apisix start error:init_by_lua error : no pcre jit support found

### ISSUE THREAD

**Issue by huzhewei** [apache/apisix#2248]
### Issue description
apisix start出现no pcre jit support found，但我本地已经安装了pcre和pcre-devel了
nginx:[error] init_by_lua error: .../init.lua:57: no pcre jit support found

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos6.9

**Comment by huzhewei** [comment]
我加了--with-pcre=../pcre-8.4.2后修复了此问题，但是抛出了新问题
nginx[error]: init_by_lua error: ../lualib/ngx/re.lua:47 : missing declaration for symbol hnx_http_lua_ffi_exec_regex''

**Comment by Yiyiyimu** [comment]
Hi @huzhewei I think I met same problem before. I suggest to follow instructions in [doc/install-dependencies](https://github.com/apache/apisix/blob/master/doc/install-dependencies.md#centos-7) to install openresty, where you could avoid apisix dependencies missing.

**Comment by huzhewei** [comment]
> Hi @huzhewei I think I met same problem before. I suggest to follow instructions in [doc/install-dependencies](https://github.com/apache/apisix/blob/master/doc/install-dependencies.md#centos-7) to install openresty, where you could avoid apisix dependencies missing.

There is no internet in my environment, so I installed openresty-1.15.8.2 through source code, and my pcre version is pcre-7.8-7.el6.x86_64 , pcre-devel version is  pcre-devel-7.8-7.el6.x86_64

**Comment by Yiyiyimu** [comment]
Maybe you could refer to https://github.com/openresty/lua-resty-core/issues/258.

There is some discussion about this problem.

**Comment by huzhewei** [comment]
> Maybe you could refer to [openresty/lua-resty-core#258](https://github.com/openresty/lua-resty-core/issues/258).
> 
> There is some discussion about this problem.

thanks so much! i helped me a lot!
best wishes!

@Yiyiyimu
