### ISSUE TITLE
request: add the dependency of lua-resty-hmac

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2256]
Now Apache APISIX does not declare the dependency on lua-resty-hmac, but implicitly installs it through [lua-resty-jwt](https://luarocks.org/modules/cdbattags/lua-resty-jwt). There are two problems with this approach:
1. Lua-resty-hmac cannot be updated in time
2. Implicit installation will cause confusion to users

Therefore, we should:
1. Update lua-resty-jwt to the latest version, and check whether other lua-resty-* is updated;
2. Add dependency on[ lua-resty-hmac](https://github.com/jkeys089/lua-resty-hmac) in the luarocks of Apache APISIX

**Comment by membphis** [comment]
https://github.com/jkeys089/lua-resty-hmac/pull/24

create a new PR to release version 1.0 .

**Comment by moonming** [comment]
@membphis any update?

**Comment by membphis** [comment]
https://luarocks.org/modules/jkeys089/lua-resty-hmac-ffi

we can fetch the `lua-resty-hmac` from here now.

I create a new issue: https://github.com/SkyLothar/lua-resty-jwt/issues/95

We can wait more time.
