### ISSUE TITLE
bug: failed to match any routes"

### ISSUE THREAD

**Issue by lifehacking** [apache/apisix#2258]
### Issue description

client curl  --->  route ---> upstream 

client curl return: failed to match any routes

route config： 

```json
{
    "node": {
        "createdIndex": 52, 
        "modifiedIndex": 52, 
        "key": "/apisix/routes/2", 
        "value": {
            "priority": 0, 
            "upstream_id": "1", 
            "hosts": [
                "www.test.com"
            ], 
            "uris": [
                "/"
            ], 
            "id": "2"
        }
    }, 
    "action": "get"
}
```

upstream config：

```json
{
    "node": {
        "createdIndex": 53, 
        "modifiedIndex": 53, 
        "key": "/apisix/upstreams/1", 
        "value": {
            "retries": 3, 
            "timeout": {
                "read": 30, 
                "connect": 30, 
                "send": 30
            }, 
            "nodes": {
                "192.168.1.6:8000": 1
            }, 
            "type": "roundrobin", 
            "id": "1", 
            "hash_on": "vars"
        }
    }, 
    "action": "get"
}
```

### Environment

* apisix version ：1.5
* OS: centos7.6

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

client returen: 

curl http://www.test.com/status/index.html
{"error_msg":"failed to match any routes"}

**Comment by Caelebs** [comment]
{
"error_msg": "failed to match any routes"
}

**Comment by moonming** [comment]
@membphis @nic-chen please take a look

**Comment by membphis** [comment]
@lifehacking @Caelebs  

![image](https://user-images.githubusercontent.com/6814606/94099851-816ce600-fe5e-11ea-96c0-e326fc80f697.png)

**Comment by moonming** [comment]
@membphis please use text instead of image, which is not friendly for search

**Comment by idbeta** [comment]
@lifehacking any update?
