### ISSUE TITLE
bug: problems in batch-requests doc

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2262]
### Issue description
1. Default timeout in [code](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) is set to 30000. but in [doc](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) it's 3000.
2. Currently user is told to disable batch-requests by removing `/conf/config.yaml`. Let's say we change it to `config-default.yaml`, but this file is not suggested to modify. How should we deal with this - customized deletion but not addition - situation?

**Comment by membphis** [comment]
if you wants to enalbe specified plugins,  you can set a new plugin list in file `conf/config.yaml`.

here is an example, it only enabled `limit-***` plugins.

```yaml
# in file: conf/config.yaml
plugins:                          # plugin list
  - limit-req
  - limit-count
  - limit-conn

**Comment by Yiyiyimu** [comment]
thx!

**Comment by membphis** [comment]
> 1. Default timeout in [code](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) is set to 30000. but in [doc](https://github.com/apache/apisix/blob/master/apisix/plugins/batch-requests.lua#L48) it's 3000.

update `doc` is better.

**Comment by Yiyiyimu** [comment]
> update `doc` is better.

Ok sure thx!
