### ISSUE TITLE
refactor bin/apisix

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2264]
As a part of APISIX ecosystem, the `bin/apisix` is also important, while current implementation is somewhat chaotic, and there are some bad smell in the code base.

So what's the plan for the evolution of `bin/apisix`, maybe we can refactor it if possible, for the cleaner code base and better structure.

**Comment by moonming** [comment]
agreed +1
do you have any idea about this?

**Comment by moonming** [comment]
@membphis please take a look

**Comment by tokers** [comment]
I think the first thing that we can do is splitting this monomeric file into multiple modules, each as a Lua file, which enhances the readability and keeps the code base clean.

The second one, might be devoting to optimize the interactivity? Such the output message, the fancy command options completion in bash/zsh.

**Comment by membphis** [comment]
agree +1 to refactor `bin/apisix`

the CLI is becoming more and more important.

**Comment by membphis** [comment]
> I think the first thing that we can do is splitting this monomeric file into multiple modules, each as a Lua file, which enhances the readability and keeps the code base clean.

we can implement this version first ^_^

**Comment by tokers** [comment]
@membphis Let me deal it :)

**Comment by tokers** [comment]
We have separated some parts of the monomeric `bin/apisix`:

* All auxiliary functions were moved to `apisix/cli/util.lua`;
* All environmental factors were moved to `apisix/cli/env.lua`;
* All operations about etcd were moved to `apisix/cli/etcd.lua`;
* All file I/O operations were moved to `apisix/cli/file.lua`;
* The template of nginx.conf was moved to `apisix/cli/ngx_tpl.lua`;

Next we're about to refactoring all sub commands to ops.lua.

**Comment by spacewander** [comment]
Solved.
