### ISSUE TITLE
First time use: Nginx.conf, manager-api and dashboard

### ISSUE THREAD

**Issue by MrLightSpeed0** [apache/apisix#2272]
### Issue description
I downloaded apisix yesterday and I have encountered a few issues during the build process. The version is apisix 1.5 (the latest one) for Ubuntu 18.04. 
#1. at the last step when I run ./bin/apisix start, I got an error message saying the address is not support by protocol. I looked it up and knowing that was related the ipv6 is not supported on, so I went to conf/nginx.conf file and commented out the following two lines: 
    listen [::]:9080 ... 
    listen [::]:9443 ...
however, after I ran the start command again, those two values got reverted back (i.e. un-commented) to what they were. it seems like the nginix.conf is regenerated every time when I run the apisix start. Could you please advise how this file is regenerated each time and what I should do to not include them? I did look at my system and ipv6 is indeed disabled and not supported.  

#2. I tried to build dashboard, go build needs to import following:
      "github.com/apisix/manager-api/conf"
      "github.com/apisix/manager-api/log"
      "github.com/apisix/manager-api/route"
However I kept getting the errors saying those cannot found. I even tried to do, say:  go get github.com/apisix/manager-api/conf, etc. they could not be found. I searched the github and unable to find them. Please advise on this.

#3, Since I could not move forward with #2, I tried to do docker for the dashboard. again it failed with timed-out for what it looked like that something to with GoProxy tried to dial tcp 119.28.201.50:443 I tried to see what the ip address seemed to be un-resolvable. I m from US and didnt think I needed GoProxy. so please advise on this as well.

Thank you!
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: Ubuntu 18.04

**Comment by Yiyiyimu** [comment]
Hi @MrLightSpeed0 I'm only familiar with apisix itself, so I could only answer the first question.

Yes nginx.conf would be regenerated each time you start apisix, and if you notice, there is waring on the top of nginx.conf says do not edit this file. The recommended way is to comment out the code in bin/apisix
https://github.com/apache/apisix/blob/6e0da454d1b5291e6ee22b9b05b254de056b63c5/bin/apisix#L360-L365

Hope it helps :)

**Comment by Yiyiyimu** [comment]
For the 3rd problem, you could directly remove goproxy
https://github.com/apache/apisix-dashboard/blob/ba185b9e109c945235e61eff3c63a7cabd56d50f/api/Dockerfile#L23-L24
these two lines

**Comment by spacewander** [comment]
For the first problem, you can also disable `enable_ipv6` in the config.yaml.

**Comment by spacewander** [comment]
For the remain problems, I create an issue in dashboard: https://github.com/apache/apisix-dashboard/issues/500, and we can move the discussion there.

**Comment by Yiyiyimu** [comment]
> For the first problem, you can also disable `enable_ipv6` in the config.yaml. There is no need to modify the template code directly.

Thx I missed this option

**Comment by MrLightSpeed0** [comment]
very nice. thank you so much. that worked well. I can now start apisix! I will follow up on the dashboard question in the other board. let me close this "issue" and I will open a new issue asking another question.
