### ISSUE TITLE
request help: let id of route or any other object in APISIX allows dot characters

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2274]
### Issue description

let id of route or any other object in APISIX allows dot characters

now we only allow [[^[a-zA-Z0-9-_]+$]] or Integer

### Environment

* apisix version : v1.5
* OS:

**Comment by spacewander** [comment]
@gxthrj 
What does 'any other object' mean?

**Comment by gxthrj** [comment]
> @gxthrj
> What does 'any other object' mean?

Other objects include upstream, service and consumer

**Comment by membphis** [comment]
that is a good suggestion, let us do it
