### ISSUE TITLE
feat: support to fetch `consumer_name`, `route_id` and `service_id` via `ctx.var`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2275]
here is the fake code:

```lua
local consumer_name = ctx.var.consumer_name
local route_id = ctx.var.route_id
local service_id = ctx.var.service_id
```

This makes it easier for the plugin code to get the values of these variables.

**Comment by membphis** [comment]
@Firstsawyou you can take a look at this issue.

https://github.com/apache/apisix/pull/2270/files#diff-dfbae0bb78c37ecbf8879c21157751ffR71, we can implement it in a simpler way.

**Comment by Firstsawyou** [comment]
assigned to me.
