### ISSUE TITLE
bug: http_logger missing parameter `keepalive`

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2276]
### Issue description

http_logger use `keepalive` but didn't set it in the schema

https://github.com/apache/apisix/blob/39ef6fb2eb944be5b4f6784573cd61a758ac3975/apisix/plugins/http-logger.lua#L27-L42

https://github.com/apache/apisix/blob/39ef6fb2eb944be5b4f6784573cd61a758ac3975/apisix/plugins/http-logger.lua#L114

**Comment by liuhengloveyou** [comment]
Which branch? I can't see those codes now.

**Comment by Yiyiyimu** [comment]
it got fixed in #2294. Thank you for your remind!
