### ISSUE TITLE
bug: is plugin `log-rotate` enabled as default

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2281]
### Issue description

In [config-default.yaml](https://github.com/apache/apisix/blob/84ce7ba781affbf93c136ea5d3e2e12460ebe4ed/conf/config-default.yaml), log-rotate is not enabled as default, but attributes of it is set:
https://github.com/apache/apisix/blob/84ce7ba781affbf93c136ea5d3e2e12460ebe4ed/conf/config-default.yaml#L199-L202

**Comment by moonming** [comment]
This seems to be designed this way, @membphis can you confirm it?

**Comment by spacewander** [comment]
The plugin attribute just shows how we can configure it.
