### ISSUE TITLE
enable a jwt-auth plugin without required field key

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix#2288]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

jwt-auth plugin can be configured successfully without any configuration，
but refer to the doc: https://github.com/apache/apisix/blob/master/doc/plugins/jwt-auth.md#attributes
field `key` is reqired, and a jwt-plugin without key could not be used as well.

So would it be better to set the key as reqired here?
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
@liuxiran This plugin is used in a dynamic case, when it works with Consumer, key is required. When it works with other cases, key is optional, so we use it as an optional field, but when you use it, please SET that key field for security reasons.

It's schema would be modified in the furetue according to @membphis's feedback :D
