### ISSUE TITLE
request help: stream proxy didn't work

### ISSUE THREAD

**Issue by huzhewei** [apache/apisix#2289]
### Issue description
I want to register tcp protocol services and proxy the port.
So I realized my discovery registry, and wanted to register a route to proxy the tcp service.

discovery.nodes:
{
  "tcp-service":{
     "host":"10.0.15.249",
     "port":"8000",
     "weight":10
  }  
}

Then I request stream_proxy api to register:
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "server_addr": "127.0.0.1",
    "server_port": 2000,
    "upstream": {
        "service_name": "tcp-service",
        "type": "roundrobin"
    }
}'

But I can't see the address mapping by using netstat -ant | grep 2000

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS:centos6.9

**Comment by huzhewei** [comment]
I have modified the config_yaml to allow stream proxy:
strea_proxy:
  tcp:
    - 9100
    - 9010

**Comment by huzhewei** [comment]
Should I modify  config_yaml and add tcp port:2000 before requesting stream_proxy api?
![image](https://user-images.githubusercontent.com/50432229/94094575-68f6ce80-fe52-11ea-9352-283fb8a82f83.png)

**Comment by huzhewei** [comment]
I have resolved it using my way.
But I think my method is not very standard,
I added "discovery.init_worker" into stream_init_worker to make nodes effective.
Someone give me a suggestion?

**Comment by huzhewei** [comment]
@Yiyiyimu Does Apisix support to proxy an unspecified number of tcp services without modifying config.yaml ？
stream_proxy:
  tcp:
    - 9100
    . .  .

**Comment by Yiyiyimu** [comment]
Sorry I'm not familiar with this part. 
ping @membphis

**Comment by huzhewei** [comment]
@Yiyiyimu  Thanks~
@membphis  Could you please give me a hand?

**Comment by spacewander** [comment]
Apisix doesn't support to proxy an unspecified number of TCP services without modifying config.yaml

**Comment by huzhewei** [comment]
thanks ~
I have got it.



***@***.***
 
From: 罗泽轩
Date: 2021-06-07 17:09
To: apache/apisix
CC: huzhewei; Author
Subject: Re: [apache/apisix] request help: stream proxy didn't work (#2289)
Apisix doesn't support to proxy an unspecified number of TCP services without modifying config.yaml
