### ISSUE TITLE
feature: Create RabbitMQ publisher plugin

### ISSUE THREAD

**Issue by djkevincr** [apache/apisix#2291]
This plugin works as a publisher which collects APISIX gateway logs and publish to external message broker, so that interested subscribers can fetch published logs from plugin. Architecture for the implementation is similar to other log publisher plugins. Eg:- Kafka Logger

**Comment by Yiyiyimu** [comment]
Hi @djkevincr is it that the outreachy 2020 application period has already ended on Sept 21st? It seems people could not register currently

**Comment by membphis** [comment]
https://github.com/wingify/lua-resty-rabbitmqstomp

this library seems good, it is `MIT` license.

**Comment by tashiya-menuri** [comment]
Hi All,

Thank you for accepting me as an Outreacy Intern. I am looking forward to work with you all. Can someone please assign the github issue for me. I am currently working on setting up development environment for Apache APISIX server. Can someone please suggest updated documentation [1] for this, to basically build the source and run? 

I have already completed a docker based local setup for RabbitMQ, started working on writing a simple client code from Lua. 

[1] https://github.com/apache/apisix/blob/master/doc/how-to-build.md#installation-via-source-release

Regards
Menuri

**Comment by tokers** [comment]
@tashiya-menuri Assigned to you :)

**Comment by spacewander** [comment]
Already done.

**Comment by Fabriceli** [comment]
RabbitMQ plugin has released? I can not find in https://github.com/apache/apisix/tree/master/apisix/plugins
