### ISSUE TITLE
错误：Failed to start after changing the configuration

### ISSUE THREAD

**Issue by zhangpjbo** [apache/apisix#2300]
### Issue description
Failed to start after changing the configuration

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos7.5

### Minimal test code / Steps to reproduce the issue
Configuration is as follows:
Change the config.yaml configuration
![1600925190](https://user-images.githubusercontent.com/43983137/94104477-baf71e80-fe69-11ea-95c0-fd6a2fd9119d.png)

Introduce a file in upstream.lua
![1600925451](https://user-images.githubusercontent.com/43983137/94104705-335ddf80-fe6a-11ea-8b7a-66ef6c94f29d.png)

### What's the actual result? (including assertion message & call stack if applicable)
error starting apisix times, as shown below:
![1600925544](https://user-images.githubusercontent.com/43983137/94104774-67d19b80-fe6a-11ea-905f-3a55fc2b4646.png)

**Comment by spacewander** [comment]
The `resty.template` doesn't work under stream subsystem, so you can not introduce it directly in upstream.lua.

**Comment by zhangpjbo** [comment]
How do I use this package in upstream.lua, mainly because it involves dynamically writing the configuration to the file.

**Comment by spacewander** [comment]
You may need to only load `resty.template` under http subsystem, for example:
```lua
local template
if ngx.config.subsystem == "http" then
    template = require "resty.template"
end
```

Here I will close the issue as it isn't relative with apisix anymore.
