### ISSUE TITLE
request help: Provide the ability to view plug-in types

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2308]
### Issue description
some auth plugins has a type named "auth", Identifies that this plugin is used for authentication

![image](https://user-images.githubusercontent.com/4413028/94166516-fa4f5a80-febd-11ea-8fcf-cd699a62ddde.png)

I need to know the type of plugin, so can make some judgments based on the type.

### Environment

* apisix version: 1.5
* OS:

**Comment by membphis** [comment]
that is a useful feature, we can let APISIX support this

**Comment by juzhiyuan** [comment]
Just for sure, this feature will not only take effects on Auth plugins but also for all plugins, right?

**Comment by membphis** [comment]
you are right ^_^ @juzhiyuan

**Comment by juzhiyuan** [comment]
any update? Does this support now?

**Comment by membphis** [comment]
We can support this feature in 2.2

**Comment by tzssangglass** [comment]
i can do this
