### ISSUE TITLE
request help: how to renew healthy-checke lrucache 

### ISSUE THREAD

**Issue by MrJLuo** [apache/apisix#2314]
### Issue description
I found that only when the worker is started for the first time (or after lrucache_checker times out), will the checker be created and the latest node information will be written to the cache; when the registry information changes, lrucache_checker cannot detect and update the cache, only reload or wait The cache will not be updated until the lrucache_checker cache expires.
How can we solve this problem?

### Environment
centos7.2

* apisix version (cmd: `apisix version`):apisix v1.5
* OS:linux

**Comment by membphis** [comment]
> when the registry information changes, lrucache_checker cannot detect and update the cache, 

if the registration information changes, the old lrucache_checker will be removed automatically. here is the source code line:

https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua#L196

if the old lrucache_checker was not removed automatically when the registration information changes, it should be a bug.
