### ISSUE TITLE
request help: Nginx integrated skywalking acquisition function, TPS decreased significantly

### ISSUE THREAD

**Issue by limm0554** [apache/apisix#2315]
Hello!
 Nginx integrates the collection function of skywalking, and it is found that TPS decreases significantly.
Excuse me, have you done relevant diagnosis there?
thank you

**Comment by liuhengloveyou** [comment]
Probably because the collection logic increases the request time.

**Comment by moonming** [comment]
we need to upgrade skywalking plugin to support sw 8.0, then to check the performance issue.

**Comment by membphis** [comment]
> Probably because the collection logic increases the request time. @liuhengloveyou 

We need to confirm what is causing the increase in request time.

**Comment by spacewander** [comment]
I think this issue is stale?

**Comment by membphis** [comment]
we can close this issue now.
