### ISSUE TITLE
request help: How to use circuit breaking service? Thanks

### ISSUE THREAD

**Issue by silveric10** [apache/apisix#2318]
### Issue description
It seems that you have already realized "Circuit-Breaker : Intelligent tracking of unhealthy upstream services."
but I can't find the plugin or code, can you tell me how to use this function? 
Thanks
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by liuhengloveyou** [comment]
seem to doesn't merge into the main line yet. It is not described in the documentation.

**Comment by membphis** [comment]
> It seems that you have already realized "Circuit-Breaker : Intelligent tracking of unhealthy upstream services."

you can enable the `health checker` in the upstream objects first. 
it'll remove the unhealthy upstream node if the status is unhealthy.
