### ISSUE TITLE
request help: start with k8s to report an error

### ISSUE THREAD

**Issue by limestone0o0** [apache/apisix#2319]
### Issue description
When I use the following command：

kubectl apply -f deployment.yaml

found error:
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:678: failed to read `nginx_config` field from yaml file
stack traceback:
	[C]: in function 'error'
	/usr/bin/apisix:678: in function </usr/bin/apisix:641>
	/usr/bin/apisix:858: in main chunk
	[C]: at 0x55ecc6b2b320

### Environment
k8s
* apisix version (cmd: `apisix version`): latest
* OS: ubuntu18

**Comment by nic-chen** [comment]
need steps to reproduce. and the `.yaml` file content. thanks.

**Comment by limestone0o0** [comment]
@nic-chen as documented, etCD has been added, and nothing else has changed.
https://github.com/apache/apisix/tree/master/kubernetes

**Comment by limestone0o0** [comment]
Follow the K8S document exactly, with the same content as in the document. @nic-chen ,thanks

**Comment by nic-chen** [comment]
@limestone0o0 
could you run 
```shell
kubectl get cm
```

and show us the result ? it looks like reading config.yaml failed.

**Comment by XXMY** [comment]
There is a default yaml file of configmap: https://github.com/apache/apisix/blob/master/conf/config-default.yaml

**Comment by nic-chen** [comment]
@XXMY Have you encountered the same problem?

**Comment by spacewander** [comment]
Closed as lack of response.
