### ISSUE TITLE
request help: install apisix without network

### ISSUE THREAD

**Issue by HuangDCat** [apache/apisix#2324]
### Issue description
Is everyone have any experience in installing apisix offline? I want to install apisix on a server that has no external network at all, but there is no description of this part in the current document. There may be many related dependencies. If you have relevant installation experience, could you provide a document for offline installation, thank you!

### Environment
dev

* apisix version (cmd: `apisix version`): 1.5
* OS: RedHat

**Comment by moorefu** [comment]
We do this like this.
Prepare a mirror environment of the off-line target environment, but the mirror environment is on-line. 
in the on-line environment execute the shell like this
```bash
#!/bin/sh
APISIX_VERSION=1.5
apisix_version="${APISIX_VERSION}"
yum install -y yum-plugin-downloadonly && \
yum install -y yum-utils && \
yum-config-manager --add-repo  https://openresty.org/package/centos/openresty.repo && \
yum install -y --downloadonly --downloaddir=./rpms/ etcd openresty curl git gcc libaio libpng-devel && \
yum install -y --downloadonly --downloaddir=./rpms/ https://github.com/apache/apisix/releases/download/$APISIX_VERSION/apisix-$APISIX_VERSION-0.el7.noarch.rpm
```
and the the copy the rpms dir to the target environment, execute some shell like this
```bash
#!/bin/sh

ls -l rpms|grep rpm|awk '{print "rpms/"$9}'|tr '\n' ' ' | yum localinstall -y --nogpgcheck
```
enjoy!
