### ISSUE TITLE
request help: No grpc-proxy plugin found

### ISSUE THREAD

**Issue by nature100** [apache/apisix#2328]
### Issue description
I can't find grpc-proxy on https://github.com/apache/apisix/tree/master/apisix/plugins, there are documents about it.

### Environment

- In the current master version source code

* apisix version (cmd: `apisix version`):latest
* OS: -

The plugin is not found in the docker version, so grpc plugin cannot be added in the management background.

**Comment by nature100** [comment]
@membphis I created a new issue
![image](https://user-images.githubusercontent.com/22267190/94341432-cc902000-003b-11eb-8c89-6266fb177a77.png)

**Comment by nic-chen** [comment]
grpc-proxy is not a plugin.entry is here:
https://github.com/apache/apisix/blob/master/bin/apisix#L518

**Comment by nature100** [comment]
If it is a grpc-web request, can it also be forwarded?

**Comment by nature100** [comment]
> grpc-proxy不是插件。条目在这里：[https](https://github.com/apache/apisix/blob/master/bin/apisix#L518) :
> [//github.com/apache/apisix/blob/master/bin/apisix#L518](https://github.com/apache/apisix/blob/master/bin/apisix#L518)

谢谢，我以为是一个单独的插件。https://github.com/apache/apisix/blob/master/doc/zh-cn/grpc-proxy.md

**Comment by nature100** [comment]
> grpc-proxy is not a plugin.entry is here:
> https://github.com/apache/apisix/blob/master/bin/apisix#L518

Thanks！！！

**Comment by nic-chen** [comment]
> If it is a grpc-web request, can it also be forwarded?

sure, you could have a try.

**Comment by nature100** [comment]
Okay, let me give feedback after testing.

**Comment by nature100** [comment]
After actual measurement, grpc-web data forwarding is completely normal. Great, thanks to the apisix committers, it's really easy to use!
![image](https://user-images.githubusercontent.com/22267190/94342247-5b07a000-0042-11eb-941c-5b393902e4f7.png)
