### ISSUE TITLE
request help: Apisix host configuration of route can not be '*' ?

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2330]
### Issue description
Apisix host configuration of route can not be '*' ?

![image](https://user-images.githubusercontent.com/48942966/94358181-bdf44800-00d1-11eb-8bd2-29866307ee1b.png)

I test radixtree can support '*' configuration of host. In the apisix soure code, I find host configuration restrictions. I want to understand why such a restriction in host.
`local host_def_pat = "^\\*?[0-9a-zA-Z-.]+$|^\\*$"`

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:Centos7.x

**Comment by moonming** [comment]
@membphis please take a look

**Comment by xyz2b** [comment]
Sorry. The last condition of this regular expression (^\\*$) is added by myself. The regular expression in the original code is `local host_def_pat = "^\\*?[0-9a-zA-Z-.]+$"`. So, I want to know why the host limit cannot be config '*'.

**Comment by xyz2b** [comment]
Sorry. The last condition of this regular expression `|^\\*$` is added by myself. The regular expression in the original code is local host_def_pat = "^\\*?[0-9a-zA-Z-.]+$". So, I want to know why the host limit cannot be config `*`.

**Comment by xyz2b** [comment]
Sorry. The last condition of this regular expression `|^\\*$` is added by myself. The regular expression in the original code is `local host_def_pat = "^\*?[0-9a-zA-Z-.]+$"`. So, I want to know why the host limit cannot be config `*`.

**Comment by membphis** [comment]
if you set `*` for field `host`, it means matching any host.

for this case, you do not need to set field `host`.

> So, I want to know why the host limit cannot be config *.

if you want to set  host to `*`, you do not need to set the field "host".

**Comment by xyz2b** [comment]
ok, thank you.
