### ISSUE TITLE
bug: why key is required in Upstream's request body?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#2335]
### Issue description
As the Admin API[1] says, the `key` is only valid when using the `chash` type, so why it's required in API's request body?

![image](https://user-images.githubusercontent.com/2106987/94393538-d7f36080-018d-11eb-8435-6364d5e6bb51.png)

[1] https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the expected result?

related issue https://github.com/apache/apisix-dashboard/issues/498

**Comment by nic-chen** [comment]
You can consider it as a conditional required

**Comment by juzhiyuan** [comment]
optional required? cc @membphis @moonming

**Comment by membphis** [comment]
we need to fix it doc
