### ISSUE TITLE
work process 都会执行脚本中的ngx_timer_every 调度吗

### ISSUE THREAD

**Issue by sixinyiyu** [apache/apisix#2359]
### Issue description
discovery 里的nacos.lua会在启动时拉取一下服务列表，我这里打印了下日志
![QQ图片20201006174034](https://user-images.githubusercontent.com/3435446/95185355-30b0a200-07fb-11eb-9a4f-f9cbca0e129d.png)
同时也显示 4个nginx工作线程，那这样的话，每次去更新服务列表跟服务实例的时候，会n个工作线程同时执行这个任务？
如何规避，让其中一个线程去执行就可以了？
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos

**Comment by sixinyiyu** [comment]
是否需要制定某个线程 0 == ngx.worker.id()  ？保证一个执行？

**Comment by sixinyiyu** [comment]
变量可见性

**Comment by membphis** [comment]
> 如何规避，让其中一个线程去执行就可以了

welcome PR for a better way ^_^

@sixinyiyu if possible, please use English in a public channel. 

We hope that more and more people from all over the world will join us for a better API gateway.
