### ISSUE TITLE
request help: i'm interesting in plugin orchestration, can you provide a video for use it? thank you

### ISSUE THREAD

**Issue by tristan-tsl** [apache/apisix#2360]
### Issue description
can you provide a video for use it?

### Environment

* apisix version (cmd: `apisix version`): no
* OS: no

**Comment by membphis** [comment]
gif link: https://static.apiseven.com/low-code-api-gateway-example-en-US.gif
mp4 link: https://static.apiseven.com/low-code-api-gateway-example-en-US.mp4

**Comment by tristan-tsl** [comment]
oh, yes, thank you
