### ISSUE TITLE
perf: use `table.isarray` which is can be JIT compiled

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2361]
We can use `table.isarray` to check whether the Lua table is a pure array-like table.

https://github.com/apache/apisix/blob/master/apisix/core/config_local.lua#L60

Here is the doc link:

doc link: https://github.com/openresty/luajit2#tableisarray

**Comment by tokers** [comment]
I have committed a PR to optimize it: https://github.com/apache/apisix/pull/2365 :).
