### ISSUE TITLE
bug: gRPC transcoding plugin how to support import  other proto file?

### ISSUE THREAD

**Issue by tanjiancheng** [apache/apisix#2366]
###
I use the `import google/api/annotations.proto` just for test 
```
curl http://127.0.0.1:9080/apisix/admin/proto/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "content" : "syntax = \"proto3\";
    package helloworld;
	import \"google/api/annotations.proto\";
    service Greeter {
        rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
    message HelloRequest {
        string name = 1;
    }
    message HelloReply {
        string message = 1;
    }"
}'
```
and then return the error like this:
```
2020/10/09 07:47:23 [error] 25#25: *168534 lua entry thread aborted: runtime error: /usr/local/apisix//deps/share/lua/5.1/protoc.lua:283: module load error: google/api/annotations.proto
        ./google/api/annotations.proto: No such file or directory
stack traceback:
coroutine 0:
        [C]: in function 'error'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:283: in function 'parsefile'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:447: in function 'top_parser'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:771: in function 'f'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:1028: in function 'do_compile'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:1032: in function 'compile'
        /usr/local/apisix//deps/share/lua/5.1/protoc.lua:1042: in function 'load'
        /usr/local/apisix/apisix/plugins/grpc-transcode/proto.lua:46: in function 'create_obj_fun'
        /usr/local/apisix/apisix/core/lrucache.lua:134: in function 'fetch'
        /usr/local/apisix/apisix/plugins/grpc-transcode.lua:117: in function 'phase_func'
        /usr/local/apisix/apisix/init.lua:138: in function 'run_plugin'
        /usr/local/apisix/apisix/init.lua:595: in function 'grpc_access_phase'
```
The actual use contains other more complex scenarios,how to support this?

### Environment

* apisix version:1.5
* OS: centos7

**Comment by membphis** [comment]
@nic-chen do you know how to resolve this issue?

**Comment by nic-chen** [comment]
we don't support import proto yet. you can add the dependent content directly to the proto

**Comment by tanjiancheng** [comment]
@nic-chen 
Do you means copy the import  content to the same file proto and use the apisix/admin/proto to put this merge proto content?

**Comment by nic-chen** [comment]
> @nic-chen 
> 
> Do you means copy the import  content to the same file proto and use the apisix/admin/proto to put this merge proto content?


Yes, it could be solved in this way. Proto import is quite troublesome to implement and would not be considered in the near future.

**Comment by tanjiancheng** [comment]
ok,thanks

**Comment by lizitao-sys** [comment]
> ok,thanks

Hello, have you solved this problem? How did it work?

**Comment by ntyrrell** [comment]
Would be keen to see this handled eventually - it doesn't seem sustainable to have to copy proto definitions instead of imports, especially if you have several imports, or the types being imported are complex or liable to change frequently.

**Comment by mehmetcuneyit** [comment]
> Would be keen to see this handled eventually - it doesn't seem sustainable to have to copy proto definitions instead of imports, especially if you have several imports, or the types being imported are complex or liable to change frequently.

Hi, check this out https://github.com/apache/apisix/discussions/6351 . It's been solved, for further instructions https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md
