### ISSUE TITLE
bug:Use zipkin plugin and  limit-req plugin  together, zipkin plugin can not work when is limit

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2377]
### Issue description
I use zipkin plugin and limit-req plugin together, When then service is being limit, I got this error log:
```
2020/10/10 17:03:12 [error] 48277#0: *6990 failed to run header_filter_by_lua*: ...nts/workspace/incubator-apisix/apisix/plugins/zipkin.lua:177: attempt to index field 'proxy_span' (a nil value)
stack traceback:
	...nts/workspace/incubator-apisix/apisix/plugins/zipkin.lua:177: in function 'phase_func'
	...ser/Documents/workspace/incubator-apisix/apisix/init.lua:150: in function 'run_plugin'
	...ser/Documents/workspace/incubator-apisix/apisix/init.lua:611: in function 'common_phase'
	...ser/Documents/workspace/incubator-apisix/apisix/init.lua:619: in function 'http_header_filter_phase'
```
Please confirm is this a bug?
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by gy09535** [comment]
I think  when API is limit ,their has no proxy and has no response body, somewhere remove this context, so the proxy span is nil, ref: https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua#L189 , I add some code to judge the "opentracing.proxy_span" and "opentracing.body_filter_span" is not null ,it can work. But I can not find the root cause, please help confirm

**Comment by moonming** [comment]
I think if APIhas been limited, because of the priority, apisix should not run the zipkin plugin

**Comment by gy09535** [comment]
> I think if API has been limited, because of the priority, apisix should not run the zipkin plugin

Thanks, I will confirm it.

**Comment by gy09535** [comment]
> I think if API has been limited, because of the priority, apisix should not run the zipkin plugin

I find if the plugin function return code and body, the response will be exit, the flowing lua script will not execute, so the zipkin access method is not execute, ref: https://github.com/apache/apisix/blob/master/apisix/init.lua#L142 .
Should we fix it in zipkin plugin, add some judge code  to make sure the span is exits?

**Comment by membphis** [comment]
if we need it, we can set a higher priority. https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua#L51

@moonming please confirm if that is a good way for `zipkin`. 

Maybe `skywalking` plugin also has this issue.

**Comment by gy09535** [comment]
> if we need it, we can set a higher priority. https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua#L51
> 
> @moonming please confirm if that is a good way for `zipkin`.
> 
> Maybe `skywalking` plugin also has this issue.

But if the plugin order support self define, the  priority may be not work?

**Comment by gy09535** [comment]
I have change the priority of zipkin plugin, I think maybe we have another problem , can not span the right time of access and rewrite, should we change some code out plugin?

**Comment by moonming** [comment]
> But if the plugin order support self define, the priority may be not work, please confirm.

@nic-chen please confirm this question, thx

**Comment by nic-chen** [comment]
> > if we need it, we can set a higher priority. https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua#L51
> 
> > 
> 
> > @moonming please confirm if that is a good way for `zipkin`.
> 
> > 
> 
> > Maybe `skywalking` plugin also has this issue.
> 
> 
> 
> But if the plugin order support self define, the  priority may be not work, please confirm.
> 
> ![image](https://user-images.githubusercontent.com/15153469/95974615-cd042580-0e47-11eb-94e0-7e83adcd8f45.png)
> 
> 

plugin orchestration has its own order, and the priority of plugin itself does not work in orchestration
