### ISSUE TITLE
bug: 2020/10/11 11:29:46 [error] 24#24: *18483 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer

### ISSUE THREAD

**Issue by luoqingming110** [apache/apisix#2388]
### Environment

* apisix version (cmd: `apisix version`):
* OS: k8s

### Minimal test code / Steps to reproduce the issue
1.2020/10/11 11:29:46 [error] 24#24: *18483 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer

### What's the actual result? (including assertion message & call stack if applicable)

2020/10/11 11:29:17 [error] 21#21: *16162 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:46 [error] 24#24: *18483 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:46 [error] 28#28: *18493 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:46 [error] 20#20: *20766 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:46 [error] 25#25: *20772 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:46 [error] 22#22: *20773 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:47 [error] 18#18: *20774 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:47 [error] 19#19: *20776 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:47 [error] 21#21: *20762 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer
2020/10/11 11:29:47 [error] 23#23: *20769 [lua] config_etcd.lua:433: failed to fetch data from etcd: /apisix/routes is not a dir,  etcd key: /apisix/routes, context: ngx.timer

### What's the expected result?
run ok

**Comment by spacewander** [comment]
Which version of `etcd` and `apisix` you are using?

**Comment by moonming** [comment]
The master version of apisix only support etcd v3 protocol

**Comment by idbeta** [comment]
If you are using APISIX 1.5 ( installed with "wget http://www.apache.org/dist/apisix/1.5/apache-apisix-1.5-src.tar.gz" ), 
you should start etcd like this: 
```shell
etcd -enable-v2 &
```

**Comment by spacewander** [comment]
Closed this issue as the author doesn't response anymore.
