### ISSUE TITLE
bug: return 400 response if the uri of route contains `//`.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2393]
### description

I tested the route with a very long uri, but it seems not work

> set route

curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{"uri": "/hellolaONJDqj0hSjILB6Hv5ofkbaw0GEGvkunSKdMgAidzZYkPRQPWtlWv8ddAikKYORlaVrFVdHszTTehpXRojFTeCDKnXwRXHtuqkoxkG4Syn/FUK/DlbkKuDoDyjPdHP4tXirdQMx4E8bZmrdFnqUFGp80K0iFjmuV5b12EZSjAAHNxcY5z8HVdalk9wzUSV67lDCd/fdaqtc1YioBcPI10xmXiSRn2uJEgQiroOWV6n75QBHFLsVcVGQjpOPxLmCwANnpEl0m1niA20grwA2fYKx1TlZtEgTJlDHv7xCkHj8C9ax7yzclBPpjtOtoBuahUd5bX6/4fao8XbiJMmmjA7tw8TtXoh3TzwfIXDOWHhcpDoTXZ35KZkyCVVAvuWnhsbBCRc5agavm/hxBNke8hOiDYC6CeJ81OIrr2gXfhQNtny0pIjI2T7602G5S7SdJqLAZyi1u2txKr7JveWoL4RIaJAHs67JL2JZS7DwLDNxhCnzhVPODSCfPd3ePaldrNRIXmegEhUss7iTYuTM0gqg4kgVcCtwl7W6ZBAixkaVEN4bLzaoCbW75/LpfQILuDjxwD2SFic6LHo5n9sa6eX5oLuXgwLR3GUjcuEowSTS40U4vwdmsoEO3h/4Ywyt7bu1njYqtBiKsxNtUJBSUhP3UX6sy8kRFrYP8BaOm0fmOpn2l5Y26cD8uh9WUAZb41hNXqn4jt12IiRpEi0Dy6WIUWRZGIfOSN6wWqkNm8Q/4lNmudsg45JsHLjNaV9BY1mHf/e0HexaXod9uoa7pKS2Kfms7k9HIS9SEuWgmEffQ4qEdEanTNvdX8XzF6g46Tue93bcAN5dSNBmoRs1AQlUfjSqgWRef3ap1PYsZNg7bkhRW/Itjb3hXIj9ofo9GJZ3Ps8OwoFXlSUsGFG0upUgxrb3VITLWIhSJWdAFNpLrNRB9DiSe0YqJuBqtug32AGiLFFHq7k5N3wG0ECJbRwwMddBZa83PojEbIvPRUL2k5fvkvmhor2CnNHfRJ8fFPL1RA5AjBzJbhL2SW5VeoXuqJ0guETBD0UbzenfbsVYWMX4ZgHub8f2OJqIslkJLnFKSWZOFtZ6n9p5njUE/emgWIbICFxHpljF3AbaKO10ldsQ2/exrlx2DjLD18U7wfK/eBiZQFwcNTSB8tHOLTpY035fny9eFH6YcnwmkB8ah9EhOPYqQU1hCNJZ4SYUO9uTLzGZntGT2A7QeWQuFpc6jE5o48P3OAjtIn8Z5Sv9uLe0GhIuOPGpHrnCrJfZJ4MvDCxpKMEE6pH54c17I9gstrMRuY1B2yERS38E6Ki9I5fQVyJPgmczc9XO7ml1svBTBfYy3vzK/ysUnLE2sMI6dQtplLo4KYX56Ts3LvLfDhyRSiZ75WsEQQ7HhSye2jrhG/rmG381Mg8H9bU5ZLN4gqFQGJOIWaq9zsMCeTOMw11MuGjViwqvaC/vQM97PpvAztWOHvC1I3daAsQY/mpIe8XKwPA8SAQ67qTeQaw1NNE4deWP6J9EZchiwZNEKNWTnw0MrAwcJvz6vLFKS3aUbQf3I39UoRl65kVnrEC3UksZBU/k0DMQCvurbWz9HVyxJKYLbvvd15SHgBPcAAOcozf8PD1KAGvTqmlG61p0On/fzXRce4TOryrhjkAyegHJWPplZX8opIMqjxrBO9s5c/KzQGkz50YqxJUaF/k/6FRVXKcoK9ygron1Q9JW/8G3h4KkkU/772rMGRXQ9d1/TXypK6wCWHAqvoWv8d6WyOyPbydcyuN0LGysWxs3NQVSK/5jOQ8xgI4htedPaRDj5TfygMf9CVz48o1BZnr1MZziPriHuDM2mnpqVV/Q9HbPmZUKkptn4C39G5qzx9//Yfg9FX2cI7ZLG8bMAW6/4b2ZJaUztMGgMDkxHYPkJ7OYe0aqH4aDQREPwjduYgSuMQTCal2Ki6DN5/p5ww2XKQJfl0Ic8K4NDldQalk2dpaikNP4NthB7yyV020b2dRvCC29AM1r87hMYf0J3V3SFQEwEp7F6opek8PEkExOMCq4XCnznXy0eGtU43m271aYNxqFH9f/DycSd4ktjUPeVNWxDH2/vi83fR71mDfN3CyR1Rt6d17qlvLtoxypqkmiOn0hn2AK0agRLtL8kmAZVFTxtOujUsIjBflxxhV9Fwoz222/2fUqXGrs/Ez5oToTGIlcRJhQQELguP1M7GxcQJPqYZlaIYRjwOfPm9POzRr4h20c68NEkMS30cYDj2cIVsoLexu63h45TdMO7BJo49voUHDBOkY7Uz66szWe5O4uMehIVwRWxYsE5CZRU2KmM72xYmCrTyYQokByFeK2DZ0SWaGlrigxcn9D3Y/l6uyz6crMZJzBDeC/YuPs0ngtJFnGivkiJlxlYDpOqFf97LJAZ/8ZCeF7eelcZqqe4GsAb0zXamr75f210B39ITxmS6AmRrcbcesZhNGoQL1pYS/gd04s3TTzgpiE3uqZxtQCgiGYyVPUgSuNnVLyU/mbciFhIXVhbaWFfzgE1zbdM6UB8mRqMIEytVQVYqlWCgzMDA1i5pCwWXxFBR1P7LU/rXiKzCwGZRN9k6mPvpHaB3GpKS06GnlGvgkaX0KttJBnNwhcz4SxqpryfqwBKDCQ5mpjRo5i3QPHRXbCDbCN7SzIxiz3PX1UlLwXq5KlzYAMDxGwSVvj1SEWRvuCsAmXziqz31QrsGfJynbtNd83HpXWa0shalvtvnsDDjbmrAcMimtHvjOV0j7qGLvGom/b0IhRDFK4A4uiw1ByZl6lIKbveFH4YPmbMFl/gwnpVTtiOTcrDVrWeNevy6yFNAU38XTCyZ7VFMMxOmVUv0jr9fsdyQ/TbjZFVKuTiCPBcMxaBMw/dHOdqsyXUzBBWBrt5hH9NLkld9jwJWEIHg3zOylAd4u1Vgeb3kcKAntueFH8/cvMJcT8WEqiv9TLtbcTrFITbEUMotviVqIOB5pAgRhUGr5J7pYpjHCZijYTKKEsL6VMo4", 
"upstream": {"nodes": {"127.0.0.1:9666": 1}, "type": "roundrobin"}}
'
HTTP/1.1 200 OK
... ...

> test

curl -i 'http://127.0.0.1:9080/hellolaONJDqj0hSjILB6Hv5ofkbaw0GEGvkunSKdMgAidzZYkPRQPWtlWv8ddAikKYORlaVrFVdHszTTehpXRojFTeCDKnXwRXHtuqkoxkG4Syn/FUK/DlbkKuDoDyjPdHP4tXirdQMx4E8bZmrdFnqUFGp80K0iFjmuV5b12EZSjAAHNxcY5z8HVdalk9wzUSV67lDCd/fdaqtc1YioBcPI10xmXiSRn2uJEgQiroOWV6n75QBHFLsVcVGQjpOPxLmCwANnpEl0m1niA20grwA2fYKx1TlZtEgTJlDHv7xCkHj8C9ax7yzclBPpjtOtoBuahUd5bX6/4fao8XbiJMmmjA7tw8TtXoh3TzwfIXDOWHhcpDoTXZ35KZkyCVVAvuWnhsbBCRc5agavm/hxBNke8hOiDYC6CeJ81OIrr2gXfhQNtny0pIjI2T7602G5S7SdJqLAZyi1u2txKr7JveWoL4RIaJAHs67JL2JZS7DwLDNxhCnzhVPODSCfPd3ePaldrNRIXmegEhUss7iTYuTM0gqg4kgVcCtwl7W6ZBAixkaVEN4bLzaoCbW75/LpfQILuDjxwD2SFic6LHo5n9sa6eX5oLuXgwLR3GUjcuEowSTS40U4vwdmsoEO3h/4Ywyt7bu1njYqtBiKsxNtUJBSUhP3UX6sy8kRFrYP8BaOm0fmOpn2l5Y26cD8uh9WUAZb41hNXqn4jt12IiRpEi0Dy6WIUWRZGIfOSN6wWqkNm8Q/4lNmudsg45JsHLjNaV9BY1mHf/e0HexaXod9uoa7pKS2Kfms7k9HIS9SEuWgmEffQ4qEdEanTNvdX8XzF6g46Tue93bcAN5dSNBmoRs1AQlUfjSqgWRef3ap1PYsZNg7bkhRW/Itjb3hXIj9ofo9GJZ3Ps8OwoFXlSUsGFG0upUgxrb3VITLWIhSJWdAFNpLrNRB9DiSe0YqJuBqtug32AGiLFFHq7k5N3wG0ECJbRwwMddBZa83PojEbIvPRUL2k5fvkvmhor2CnNHfRJ8fFPL1RA5AjBzJbhL2SW5VeoXuqJ0guETBD0UbzenfbsVYWMX4ZgHub8f2OJqIslkJLnFKSWZOFtZ6n9p5njUE/emgWIbICFxHpljF3AbaKO10ldsQ2/exrlx2DjLD18U7wfK/eBiZQFwcNTSB8tHOLTpY035fny9eFH6YcnwmkB8ah9EhOPYqQU1hCNJZ4SYUO9uTLzGZntGT2A7QeWQuFpc6jE5o48P3OAjtIn8Z5Sv9uLe0GhIuOPGpHrnCrJfZJ4MvDCxpKMEE6pH54c17I9gstrMRuY1B2yERS38E6Ki9I5fQVyJPgmczc9XO7ml1svBTBfYy3vzK/ysUnLE2sMI6dQtplLo4KYX56Ts3LvLfDhyRSiZ75WsEQQ7HhSye2jrhG/rmG381Mg8H9bU5ZLN4gqFQGJOIWaq9zsMCeTOMw11MuGjViwqvaC/vQM97PpvAztWOHvC1I3daAsQY/mpIe8XKwPA8SAQ67qTeQaw1NNE4deWP6J9EZchiwZNEKNWTnw0MrAwcJvz6vLFKS3aUbQf3I39UoRl65kVnrEC3UksZBU/k0DMQCvurbWz9HVyxJKYLbvvd15SHgBPcAAOcozf8PD1KAGvTqmlG61p0On/fzXRce4TOryrhjkAyegHJWPplZX8opIMqjxrBO9s5c/KzQGkz50YqxJUaF/k/6FRVXKcoK9ygron1Q9JW/8G3h4KkkU/772rMGRXQ9d1/TXypK6wCWHAqvoWv8d6WyOyPbydcyuN0LGysWxs3NQVSK/5jOQ8xgI4htedPaRDj5TfygMf9CVz48o1BZnr1MZziPriHuDM2mnpqVV/Q9HbPmZUKkptn4C39G5qzx9//Yfg9FX2cI7ZLG8bMAW6/4b2ZJaUztMGgMDkxHYPkJ7OYe0aqH4aDQREPwjduYgSuMQTCal2Ki6DN5/p5ww2XKQJfl0Ic8K4NDldQalk2dpaikNP4NthB7yyV020b2dRvCC29AM1r87hMYf0J3V3SFQEwEp7F6opek8PEkExOMCq4XCnznXy0eGtU43m271aYNxqFH9f/DycSd4ktjUPeVNWxDH2/vi83fR71mDfN3CyR1Rt6d17qlvLtoxypqkmiOn0hn2AK0agRLtL8kmAZVFTxtOujUsIjBflxxhV9Fwoz222/2fUqXGrs/Ez5oToTGIlcRJhQQELguP1M7GxcQJPqYZlaIYRjwOfPm9POzRr4h20c68NEkMS30cYDj2cIVsoLexu63h45TdMO7BJo49voUHDBOkY7Uz66szWe5O4uMehIVwRWxYsE5CZRU2KmM72xYmCrTyYQokByFeK2DZ0SWaGlrigxcn9D3Y/l6uyz6crMZJzBDeC/YuPs0ngtJFnGivkiJlxlYDpOqFf97LJAZ/8ZCeF7eelcZqqe4GsAb0zXamr75f210B39ITxmS6AmRrcbcesZhNGoQL1pYS/gd04s3TTzgpiE3uqZxtQCgiGYyVPUgSuNnVLyU/mbciFhIXVhbaWFfzgE1zbdM6UB8mRqMIEytVQVYqlWCgzMDA1i5pCwWXxFBR1P7LU/rXiKzCwGZRN9k6mPvpHaB3GpKS06GnlGvgkaX0KttJBnNwhcz4SxqpryfqwBKDCQ5mpjRo5i3QPHRXbCDbCN7SzIxiz3PX1UlLwXq5KlzYAMDxGwSVvj1SEWRvuCsAmXziqz31QrsGfJynbtNd83HpXWa0shalvtvnsDDjbmrAcMimtHvjOV0j7qGLvGom/b0IhRDFK4A4uiw1ByZl6lIKbveFH4YPmbMFl/gwnpVTtiOTcrDVrWeNevy6yFNAU38XTCyZ7VFMMxOmVUv0jr9fsdyQ/TbjZFVKuTiCPBcMxaBMw/dHOdqsyXUzBBWBrt5hH9NLkld9jwJWEIHg3zOylAd4u1Vgeb3kcKAntueFH8/cvMJcT8WEqiv9TLtbcTrFITbEUMotviVqIOB5pAgRhUGr5J7pYpjHCZijYTKKEsL6VMo4'
HTTP/1.1 404 Not Found
...

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by idbeta** [comment]
ping @membphis

**Comment by membphis** [comment]
the input URI is invalid. the admin API should return 400 for this case

![image](https://user-images.githubusercontent.com/6814606/95761451-ea69b000-0cde-11eb-9115-b5ebf75884c7.png)
