### ISSUE TITLE
bug: broken link of AWS deployment, due to repo deleted

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2399]
### Issue description
In https://github.com/apache/apisix/tree/master/doc#aws
> See [this guide](https://github.com/pahud/cdk-samples/blob/master/typescript/apisix/README.md) by [Pahud Hsieh](https://github.com/pahud) and learn how to provision the recommended architecture 100% in AWS CDK.

The guide provided by Pahud just got deleted, due to Pahud deprecated that repo. Could we place that guide in the `doc` folder?
I think @pahud is happy to help~

**Comment by pahud** [comment]
Yes, I will refresh the doc and open a PR for this repo today.

**Comment by moonming** [comment]
hello @pahud , any update?

**Comment by pahud** [comment]
> hello @pahud , any update?

Will open the PR in the next 1 or 2 days.

**Comment by pahud** [comment]
PR opened https://github.com/apache/apisix/pull/2567
