### ISSUE TITLE
can you consider the project roadmap?

### ISSUE THREAD

**Issue by li1234yun** [apache/apisix#2400]
1. I don't find the project roadmap, can you consider about it? 
2. By the way, I want to ask the release date of version 2.  ^_^

**Comment by juzhiyuan** [comment]
You could find the milestones here https://github.com/apache/apisix/milestones

**Comment by juzhiyuan** [comment]
Welcome to send a PR to have the milestones more clearer in the README file 🤔

**Comment by li1234yun** [comment]
I will add milestone link in README file later.
