### ISSUE TITLE
plugin(consumer-restriction): update the schema

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix#2402]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [ ] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?

I'm confused about the option select item in the consumer-restriction plugin
![image](https://user-images.githubusercontent.com/2561857/94222544-3adfc000-ff20-11ea-8c4e-b4448e045b34.png)
 what does it mean?

___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirement or improvement
- Please describe your requirements or improvement suggestions.

**Comment by juzhiyuan** [comment]
Just transferred the issue to the apisix repository, cc @membphis

**Comment by Jaycean** [comment]
assign to me
