### ISSUE TITLE
CLI: What if the user start apisix by sudo? Does the worker still have permission to write logs?

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2405]
> What if the user start apisix by sudo? Does the worker still have permission to write logs?

@dabue we need to confirm this case.

original commit: https://github.com/apache/apisix/pull/2374/files#r503639787

**Comment by membphis** [comment]
I make a test right now, it is fine.

```
rm -rf logs
sudo ./bin/apisix start
curl http://xxx:9080/hello # for testing
sudo ./bin/apisix stop
```

**Comment by dabue** [comment]
I got the same result.

**Comment by moonming** [comment]
What I really care about is whether the log can be written in

**Comment by membphis** [comment]
> curl http://xxx:9080/hello # for testing

**Comment by membphis** [comment]
close this issue first. if you still have question, please feel free to reopen it.
