### ISSUE TITLE
CI on OS X is broken

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#2412]
https://travis-ci.org/github/apache/apisix/builds/735271697
![image](https://user-images.githubusercontent.com/4161644/95931305-56d9d180-0dfb-11eb-8244-d7db4dae6f24.png)
@nic-chen

**Comment by nic-chen** [comment]
OK,  I will fix it later.

**Comment by nic-chen** [comment]
fixed

**Comment by moonming** [comment]
> fixed

Where is the fix PR? @nic-chen

**Comment by nic-chen** [comment]
@moonming 
It doesn't need a PR for this issue. just upload a darwin version release for `grpc_server_example`:

https://github.com/api7/grpc_server_example/releases/tag/20200901

**Comment by moonming** [comment]
@nic-chen got it. 
please add the close reason not just close issue.

**Comment by nic-chen** [comment]
> @nic-chen got it.
> please add the close reason not just close issue.

OK, thanks for tips.
