### ISSUE TITLE
request help: apisix use promethus plugin

### ISSUE THREAD

**Issue by brianzhangrong** [apache/apisix#2413]
### Issue description
![image](https://user-images.githubusercontent.com/39478871/95936586-84794780-0e08-11eb-976b-9446fcf9b1bb.png)
![image](https://user-images.githubusercontent.com/39478871/95936646-ad014180-0e08-11eb-8edb-f646dbf478c9.png)
access  localhost:9080/apisix/promethus/metrics report 
![image](https://user-images.githubusercontent.com/39478871/95936694-c609f280-0e08-11eb-8dd5-88b9baba3914.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
Duplicate: #2394?

**Comment by nic-chen** [comment]
there is a bug in 1.5 when using domain name for upstream nodes. 
we had fixed it in master branch.

**Comment by juzhiyuan** [comment]
> there is a bug in 1.5 when using domain name for upstream nodes.
> we had fixed it in master branch.

This bug was fixed in the master branch, right? then shall we close this issue?

**Comment by membphis** [comment]
I think we can close this issue. @brianzhangrong if you still have a problem, please feel free to reopen this issue
