### ISSUE TITLE
request help: radixtree_host_uri does not consider routing priority

### ISSUE THREAD

**Issue by haifeng9414** [apache/apisix#2423]
### Issue description
Why does radixtree_host_uri.lua not set the priority when creating a route:
```
local radixtree_route = {
        paths = route.value.uris or route.value.uri,
        methods = route.value.methods,
        remote_addrs = route.value.remote_addrs
                       or route.value.remote_addr,
        vars = route.value.vars,
        filter_fun = filter_fun,
        handler = function (api_ctx)
            api_ctx.matched_params = nil
            api_ctx.matched_route = route
        end
    }
```
Is this a bug?

* apisix version (cmd: `apisix version`): latest master(4f535e7401468c3f857cbf6a83ed6c3a0a9496db)

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

![image](https://user-images.githubusercontent.com/6814606/96162628-56e8e700-0f4b-11eb-94db-9754f89df89e.png)

**Comment by haifeng9414** [comment]
The priority of the route is not set in radixtree_host_uri.lua. Even if the route has a priority, the priority of the route is the default value.

**Comment by membphis** [comment]
@haifeng9414 many thx for your report. would you like to fix this issue?

**Comment by haifeng9414** [comment]
> @haifeng9414 many thx for your report. would you like to fix this issue?

Yes, I would
