### ISSUE TITLE
bug: zipkin plugin can not  work with  new config  when  plugin config is change

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2425]
### Issue description
When the zipkin  plugin endpoint is changed , zipkin always use old endpoint to report.
I think the issue  cause of this code :https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua#L111 , we should add the endpoint as the key.

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by gy09535** [comment]
please confirm

**Comment by membphis** [comment]
confirm that is a bug, welcome PR ^_^

**Comment by gy09535** [comment]
got it, thanks

**Comment by membphis** [comment]
@gy09535 would like to submit a PR to fix this bug? 

we can use a different key, then we can fix this issue.

**Comment by gy09535** [comment]
> @gy09535 would like to submit a PR to fix this bug?
> 
> we can use a different key, then we can fix this issue.

yeah, I will fix it.

**Comment by gy09535** [comment]
> @gy09535 would like to submit a PR to fix this bug?
> 
> we can use a different key, then we can fix this issue.

After check, I make a mistake , the "core.lrucache.plugin_ctx" use the config  version as the key, so when the config is changed ,the version is always change, so it can use new value. I will close this issue.
