### ISSUE TITLE
feature: add managed fields in jsonschema for resources, such as create_time and update_time

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#2433]
### Issue description
We are refactoring the dashboard `manager api`, to remove the dependency on MySQL. Previously, some managed fields were saved in mysql. After refactoring, we moved these fields to ETCD. I think APISIX's json schema should also support this part of the fields to avoid data being filtered out.

Here is the detail:

create_time and update_time for `route`,`upstream`,`service`,`consumer`,`ssl`
validity_start and validity_end for `ssl`

this four fields are all int type for Unix timestamp.

**Comment by nic-chen** [comment]
cc @moonming @membphis @ShiningRush

**Comment by membphis** [comment]
@nic-chen can you provide some examples? we need this for confirming.

**Comment by nic-chen** [comment]
@membphis 

example, add create_time and update_time for `service`

```

local timestamp_def = {
    type = "integer",
}

_M.service = {
    type = "object",
    properties = {
        id = id_schema,
        plugins = plugins_schema,
        upstream = upstream_schema,
        upstream_id = id_schema,
        name = {type = "string", maxLength = 50},
        desc = {type = "string", maxLength = 256},
        script = {type = "string", minLength = 10, maxLength = 102400},
        labels = {
            description = "key/value pairs to specify attributes",
            type = "object",
            patternProperties = {
                [".*"] = label_value_def
            },
            maxProperties = 16
        },
        create_time = timestamp_def,
        update_time = timestamp_def
    },
    additionalProperties = false,
}
```

**Comment by membphis** [comment]
@nic-chen do we need to add `create_time` and `update_time` for all object? eg: `service`, `route` and `consumer` etc.

**Comment by nic-chen** [comment]
> @nic-chen do we need to add `create_time` and `update_time` for all object? eg: `service`, `route` and `consumer` etc.

yes, i think so. if not, data will  be filter by :
https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua#L220-L226

**Comment by membphis** [comment]
agree to add the new field ^_^

**Comment by dabue** [comment]
+1， or add a field  version.



88786912@qq.com
 
From: YuanSheng Wang
Date: 2020-10-16 19:00
To: apache/apisix
CC: Subscribed
Subject: Re: [apache/apisix] feature: add managed fields in jsonschema for resources, such as create_time and update_time (#2433)
agree to add the new field ^_^

**Comment by membphis** [comment]
fixed alread
