### ISSUE TITLE
plugin(hmac-auth): update the schema

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix#2441]
Part of https://github.com/apache/apisix/issues/2082
### Current schema
```json
{
	"additionalProperties": false,
	"properties": {
		"disable": {
			"type": "boolean"
		}
	},
	"title": "work with route or service object",
	"type": "object"
}
```
the plugin page looks:
![2020-10-16 20-39-49屏幕截图](https://user-images.githubusercontent.com/2561857/96259158-c3b5bd00-0fef-11eb-8375-b631eecead37.png)

---

### Expected schema
according to the [doc](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/hmac-auth.md#%E5%B1%9E%E6%80%A7) and [test case](https://github.com/apache/apisix/blob/1afa8f77272e6099d2c54e4f703f6a70adb16f72/t/plugin/hmac-auth.t#L27)

```json
{
  "type": "object",
  "required": [
    "access_key",
    "secret_key"
  ],
  "properties": {
    "access_key": {
      "type": "string",
      "title": "Accesskey"
    },
    "secret_key": {
      "type": "string",
      "title": "Secretkey"
    },
    "algorithm": {
      "type": "string",
      "enum": [
        "hmac-sha1",
        "hmac-sha256",
        "hmac-sha512"
      ],
      "default": "hmac-sha256",
      "title": "Algorithm"
    },
    "clock_skew": {
      "type": "number",
      "title": "clockskew",
      "default": 0
    },
    "signed_headers": {
      "type": "array",
      "title": "A list of strings",
      "items": {
        "type": "string",
        "default": "bazinga"
      }
    }
  }
}
```
the form looks:

![2020-10-16 21-06-48屏幕截图](https://user-images.githubusercontent.com/2561857/96261849-8b17e280-0ff3-11eb-8243-de6d4fca3691.png)

```

**Comment by liuxiran** [comment]
`hmac-auth` define two schemas:

- one is : https://github.com/apache/apisix/blob/d1729c0af3bc416a88904568b4d2718c99a1982d/apisix/plugins/hmac-auth.lua#L40

- the other one is: https://github.com/apache/apisix/blob/d1729c0af3bc416a88904568b4d2718c99a1982d/apisix/plugins/hmac-auth.lua#L47

- and the schema returned to the caller is only:  https://github.com/apache/apisix/blob/d1729c0af3bc416a88904568b4d2718c99a1982d/apisix/plugins/hmac-auth.lua#L80

maybe this is the cause of the problem, and this case has already made part of the plugins unuseable in dashboard.

so is it possible to return differet schema depending on the different param or return all schemas that caller coulde Judge which one to use?

@juzhiyuan @moonming @membphis @spacewander

**Comment by juzhiyuan** [comment]
@membphis Please take a look

**Comment by spacewander** [comment]
I think we should pass the schema type to get the correct schema, since currently we already have three kinds of schema:
1. metadata
2. consumer
3. route/service

**Comment by membphis** [comment]
> * metadata
> * consumer

How about this API style?

```
/apisix/admin/schema/plugins/{plugin_name}/metadata
/apisix/admin/schema/plugins/{plugin_name}/consumer
```

**Comment by spacewander** [comment]
My suggestion is to put `metadata`/`consumer` into the arguments, if the argument is missing, choice the default plain `schema`.

**Comment by imjoey** [comment]
> My suggestion is to put `metadata`/`consumer` into the arguments, if the argument is missing, choice the default plain `schema`.

+1 . IMHO, query parameters would be more flexible.

**Comment by membphis** [comment]
> My suggestion is to put `metadata`/`consumer` into the arguments, if the argument is missing, choice the default plain `schema`.

this way is much better. agree +1

**Comment by liuxiran** [comment]
ok,  based on the results of the discussion above, I think this issue contains at least two modifications: 

- [ ] admin-api provides api like：
     * `/apisix/admin/schema/plugins/{plugin_name}` to get plugin schema
     * `/apisix/admin/schema/plugins/{plugin_name}?schema_type=consumer_schema` to get plugin consumer_schema

- [ ] dashboard calls the corresponding api to get the correct schema.

e.g:

1. consumer wants to config hmac-auth plugin, then call `/apisix/admin/schema/plugins/hmac-auth?schema_type=consumer_schema` to get the config schema

1. route wants to config hmac-auth plugin, then call `/apisix/admin/schema/plugins/hmac-auth` to get the config schema

my partner and I will take this issue :)

**Comment by juzhiyuan** [comment]
yep 😁

**Comment by membphis** [comment]
`/apisix/admin/schema/plugins/{plugin_name}?schema_type=consumer_schema`

to

`/apisix/admin/schema/plugins/{plugin_name}?schema_type=consumer`

simpler

**Comment by liuxiran** [comment]
> `/apisix/admin/schema/plugins/{plugin_name}?schema_type=consumer_schema`
> 
> to
> 
> `/apisix/admin/schema/plugins/{plugin_name}?schema_type=consumer`
> 
> simpler

got it~!

**Comment by Jaycean** [comment]
Assigne to me
