### ISSUE TITLE
[discuss](prometheus): Add consumer_id dimension in http metrics for prometheus plugin

### ISSUE THREAD

**Issue by imjoey** [apache/apisix#2445]
### Issue description

For now, there has no `consumer_id` dimension in http metrics, so we cannot get the data such as:

- HTTP status returned by each route accessed by each consumer
- HTTP request count sent from each consumer to each route

Let's take `apisix_http_status` for example, an additional label `consumer="joey"` is exported, as the following:

```
apisix_http_status{code="200",route="77f32992-4fe8-4888-9553-84d7e1240734",service="",consumer="joey",node="8.8.8.8"} 5487
```

Any feedback is welcome.

**Comment by membphis** [comment]
I think it is good. +1
