### ISSUE TITLE
chore: wrong log

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2449]
`random stream test in [1, 10000]` -> `stream/http subsystem, generate random value:`

https://github.com/apache/apisix/blob/master/apisix/init.lua#L86
https://github.com/apache/apisix/blob/master/apisix/init.lua#L777

**Comment by HelloBug0** [comment]
https://github.com/apache/apisix/blob/master/apisix/init.lua#L777
`core.log.info("random stream test in [1, 10000]: ", math.random(1, 1000000))`
change to:
`core.log.info("random stream test in [1, 10000]: ", math.random(1, 10000))`

https://github.com/apache/apisix/blob/master/apisix/init.lua#L777
`core.log.info("random test in [1, 10000]: ", math.random(1, 1000000))`
change to:
`core.log.info("random test in [1, 10000]: ", math.random(1, 10000))`
