### ISSUE TITLE
bug: limit-conn

### ISSUE THREAD

**Issue by LY-GO** [apache/apisix#2450]
### Issue description
I had test  the plugin of limit-conn.I found the question that the same ip only request the router by five times when conn is 5 and key is remote_addr, and i don't request the  router next time.Why so that?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
Plugin limit-conn Edit
 conn=5
rejected_code=503
 burst=0
 key=remote_addr
 default_conn_delay=0

### What's the actual result? (including assertion message & call stack if applicable)
same user only visit the router with the config 

### What's the expected result?
i hope that the plugin only limit concurrency,and different users also continue to request the router when user request the service after first .

**Comment by membphis** [comment]
> i hope that the plugin only limit concurrency,and different users also continue to request the router when user request the service after first .

What is the difference between different users? The client's IP address or other things? Please confirm this first.

and please provide a mini case which we can reproduce your bug.

**Comment by LY-GO** [comment]
> > i hope that the plugin only limit concurrency,and different users also continue to request the router when user request the service after first .
> 
> What is the difference between different users? The client's IP address or other things? Please confirm this first.
> 
> and please provide a mini case which we can reproduce your bug.

one questions:
you had said the request would been allowed when concurrence declines.When i test the plugin of limit-conn,even through i decline the conn,the request still is unsuccess. this is a bug ?

**Comment by membphis** [comment]
I think you should provide a complete case, we need to know more detailed step information.

Mainly two questions:

1. What is the route data?
2. What is your test method?

**Comment by LY-GO** [comment]
> I think you should provide a complete case, we need to know more detailed step information.
> 
> Mainly two questions:
> 
> 1. What is the route data?
> 2. What is your test method?
<img width="401" alt="router-data" src="https://user-images.githubusercontent.com/67543312/96394096-c254e200-11f3-11eb-9ce3-57545e0deeba.png">
<img width="491" alt="router-data2" src="https://user-images.githubusercontent.com/67543312/96394103-c680ff80-11f3-11eb-8dd8-1985ae637cbf.png">
<img width="235" alt="plugin" src="https://user-images.githubusercontent.com/67543312/96394105-c8e35980-11f3-11eb-8de1-6974ffa1360c.png">
2.i use the jmeter to test plugin

**Comment by membphis** [comment]
let me confirm it

**Comment by membphis** [comment]
that is a bug, fix it soon
