### ISSUE TITLE
discuss: How apisix records the request data sent to the upstream service

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2452]
### Issue description

In the use of `apisix`, we do not have a good tool to obtain the request data sent to the upstream service, which is very inconvenient for us to troubleshoot some abnormal problems, such as: I enabled a plug-in to process client requests, and whether the processed requests comply with Our expectations, this is not known. If `apisix` supports recording the request information sent to the upstream server, then we can easily know whether the request processed by the plugin serves the expected.

**Comment by membphis** [comment]
it is not easy to record the `upstream` request data :(

**Comment by Firstsawyou** [comment]
Yes, I am looking for a feasible way to solve.

**Comment by imjoey** [comment]
+1 for me.

**Comment by gxthrj** [comment]
How about logging requests in the phase `log` through the plug-in?

**Comment by Firstsawyou** [comment]
I think we can use the `serverless` plugin to execute some `lua` logic codes at the specified stage to try to achieve it.

**Comment by membphis** [comment]
> I think we can use the `serverless` plugin to execute some `lua` logic codes at the specified stage to try to achieve it.

can you show me an example? ^_^

**Comment by spacewander** [comment]
Consider solved
