### ISSUE TITLE
doc:  typo in getting-started.md and the example in plugins/syslog.md#how-to-enable  is  wrong.

### ISSUE THREAD

**Issue by dabue** [apache/apisix#2457]
### Issue description
Line 240:
curl -i -X GET http://127.0.0.1:9080/samplePrefix/get?param1=foo&param2=bar -H 'apikey: superSecretAPIKey'

should be replaced with 
curl -i -X GET "http://127.0.0.1:9080/samplePrefix/get?param1=foo&param2=bar" -H 'apikey: superSecretAPIKey'

### Environment

* apisix version (cmd: `apisix version`):
* OS: centos 7

**Comment by membphis** [comment]
can you provide the original doc link?

**Comment by dabue** [comment]
https://github.com/apache/apisix/blob/master/doc/getting-started.md#add-a-prefix-to-the-route    Line 240

and the example which in  https://github.com/apache/apisix/blob/master/doc/plugins/syslog.md#how-to-enable   is also wrong.

**Comment by membphis** [comment]
nice, welcome PR
