### ISSUE TITLE
request help: How to define a self-develop plugin?

### ISSUE THREAD

**Issue by yanshanlangren** [apache/apisix#2464]
### Issue description
I developed a sample LUA plugin.

Put the .lua file under directory of `/usr/local/apisix/apisix/plugins`

Add plug-in name under `plugins` in `/usr/local/apisix/conf/config.yaml`

Then I reload/restart apisix, and tried to create new plugin within a route, but got hint `{"error_msg":"unknown plugin [qingcloud-auth]"}`

What else do I need to do?

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: CentOS Linux release 7.8.2003 (Core)

**Comment by membphis** [comment]
here is the doc link: https://github.com/apache/apisix/blob/master/doc/plugin-develop.md

hope this can help you.

**Comment by juzhiyuan** [comment]
I will close this issue now, please follow the link above. Feel free to reopen this one.

**Comment by yanshanlangren** [comment]
> here is the doc link: https://github.com/apache/apisix/blob/master/doc/plugin-develop.md
> 
> hope this can help you.

What I've done is based on this guide, but error still occurs, Is there any further documentations?

**Comment by yanshanlangren** [comment]
> I will close this issue now, please follow the link above. Feel free to reopen this one.

Please reopen it, my problem is not resolved.

**Comment by ziyou434** [comment]
我也遇到这个问题。
我下载了 1.5版本，其中并没有conf/config-default.yaml,只有config.yaml,在里面添加了插件，但是出现了同样的错误。
然后我尝试自己创建一个了config-default.yaml，仍然出现{"error_msg":"invalid plugins configuration: unknown plugin [XXXX]"}

**Comment by spacewander** [comment]
Does your plugin pass the validation in:
https://github.com/apache/apisix/blob/68c4fd556c86b31d88d9c613e57c5395013a5c46/apisix/plugin.lua#L82

We need a minimal fake plugin from your side to reproduce the issue.

**Comment by spacewander** [comment]
Closed as lack of response.
