### ISSUE TITLE
apisix frequent http code 502

### ISSUE THREAD

**Issue by powermanlc** [apache/apisix#2466]
### Issue description

only access go service appear http 502
error.log : upstream prematurely closed connection while reading response header from upstream，
recv() failed (104: Connection reset by peer) while reading response header from upstream,

### Environment

* apisix version (cmd: `apisix version`): 
* OS:

**Comment by membphis** [comment]
you upstream node is unstable, you need to fix this first

**Comment by powermanlc** [comment]
> you upstream node is unstable, you need to fix this first

how can i to do

**Comment by membphis** [comment]
I can not reply to you the answer, you have to fix this question by yourself.

we only can help if the APISIX has issues.

**Comment by powermanlc** [comment]
> I can not reply to you the answer, you have to fix this question by yourself.
> 
> we only can help if the APISIX has issues.

ok thanks

**Comment by membphis** [comment]
close this issue first. please feel free to reopen this issue if you need help with this issue.
