### ISSUE TITLE
strengthen: The ulimit setting should be checked when APISIX starts，if user limits too small(like 1024),APISIX should prompt to modify, otherwise the performance is low

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2467]
### Issue description
The ulimit setting should be checked when APISIX starts，if user limits too small(like 1024), APISIX should prompt to modify, otherwise, the performance is low

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
I don't think this the job of Apache APISIX

**Comment by membphis** [comment]
> if user limits too small(like 1024), APISIX should prompt to modify, otherwise, the performance is low

We need this kind of prompt.

If CLI can find some environment setting problems before APISIX starting, the user will be reminded by a warning message and how to fix it.

It makes it easier for users to use APISIX quickly and correctly. 

For example, check the value of ʻulimit -n`.

**Comment by moonming** [comment]
got it
Thanks,
Ming Wen
Twitter: _WenMing


YuanSheng Wang <notifications@github.com> 于2020年10月21日周三 下午1:55写道：

**Comment by HelloBug0** [comment]
When I run apisix, I can see this notice in error.log
`2020/10/25 06:18:31 [notice] 255449#255449: getrlimit(RLIMIT_NOFILE): 999999:999999`
This log shows the current value and the max value of opening files. 

The user could check the logs and know the limits of systems.

**Comment by spacewander** [comment]
Already done.
