### ISSUE TITLE
bug: In the third step of editing routing in the new version of dashboard, the configuration item of proxy rewrite is missing in normal mode

### ISSUE THREAD

**Issue by nirvanareborn** [apache/apisix#2473]
### Issue description

In the third step of editing routing in the new version of dashboard, the configuration item of proxy rewrite is missing in normal mode
### Environment

* apisix version (cmd: `apisix version`):
* OS: 1.5

### Minimal test code / Steps to reproduce the issue
1.In the third step of editing routing in the new version of dashboard, the configuration item of proxy rewrite is missing in normal mode

**Comment by juzhiyuan** [comment]
duplicate as https://github.com/apache/apisix-dashboard/issues/565
