### ISSUE TITLE
request help: Add metering plug-in

### ISSUE THREAD

**Issue by longshang** [apache/apisix#2474]
### Issue description
Can you tell me how to add a plug-in with the number of interface calls for an application，THX!

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
Do you need a plugin that counts the number of API calls?

if yes, we can implement this feature by a new plugin.

1. time window.
2. Calculation of the number of API requests.

**Comment by longshang** [comment]
> Do you need a plugin that counts the number of API calls?
> 
> if yes, we can implement this feature by a new plugin.
> 
> 1. time window.
> 2. Calculation of the number of API requests.

YES，And API counts can support persistent database, which is convenient for business layer to read。THX！Soon there will be this new plugin。

**Comment by gy09535** [comment]
> Do you need a plugin that counts the number of API calls?
> 
> if yes, we can implement this feature by a new plugin.
> 
> 1. time window.
> 2. Calculation of the number of API requests.

Should we add it in metric and store it in prom?

**Comment by spacewander** [comment]
I vote adding a new option to add the feature in Prometheus's metric.
Even we provides a separate plugin to count the API calls, we still need a layer to aggregate them and analyze them. There is no need to reinvent part of Prometheus.
