### ISSUE TITLE
request help: add service_id as key to plugin limit-*

### ISSUE THREAD

**Issue by LY-GO** [apache/apisix#2477]
### Issue description
i want to add key for limit-plugin;it can accomplish limit according to service_id;If i want to implement the function,you can give some suggestion.Thanks!

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
1. you need to use a better title.
2. one issue for one thing: add `service_id` as key to plugin `limit-*`, do you mean this?

**Comment by LY-GO** [comment]
> 1. you need to use a better title.
> 2. one issue for one thing: add `service_id` as key to plugin `limit-*`, do you mean this?
Sorry,my English not better;one issue : add `service_id` as key to plugin `limit-*`,

**Comment by LY-GO** [comment]
Sorry,my English not better;one issue : add service_id as key to plugin limit-*,i mean that.

**Comment by LY-GO** [comment]
> 1. you need to use a better title.
> 2. one issue for one thing: add `service_id` as key to plugin `limit-*`, do you mean this?
now i set key in the following way,but service_id is nil.Why is that?
![service_id](https://user-images.githubusercontent.com/67543312/96859853-9ad07480-1494-11eb-839c-7f770df700f9.png)

![service-name](https://user-images.githubusercontent.com/67543312/96859413-0f56e380-1494-11eb-837e-eebc882ce441.png)

**Comment by membphis** [comment]
I think we can support `service_id` as key to plugin `limit-count` first.
so you can update the title of this issue. 

after we resolve this issue, you can create more issues for other limit-* plugins.

**Comment by membphis** [comment]
> 2\. now i set key in the following way,but service_id is nil.Why is that?

do you bind any service to route?

**Comment by LY-GO** [comment]
> > 2. now i set key in the following way,but service_id is nil.Why is that?
> 
> do you bind any service to route?

yes
![Uploading services.png…]()

**Comment by LY-GO** [comment]
> > 2. now i set key in the following way,but service_id is nil.Why is that?
> 
> do you bind any service to route?

yes
![services](https://user-images.githubusercontent.com/67543312/96976436-6d480180-154e-11eb-9eae-4e6133e9819f.png)

**Comment by LY-GO** [comment]
> > 2. now i set key in the following way,but service_id is nil.Why is that?
> 
> do you bind any service to route?

we can use core.var.service_id to acquire  value of service_id?

**Comment by membphis** [comment]
this old version dashboard, so it not support `service_id` as key.

**Comment by LY-GO** [comment]
> this old version dashboard, so it not support `service_id` as key.

new version supports service_id as key?my version is 1.5,Is there any other version

**Comment by membphis** [comment]
please make a try with the master branch ^_^

**Comment by juzhiyuan** [comment]
> > this old version dashboard, so it not support `service_id` as key.
> 
> new version supports service_id as key?my version is 1.5,Is there any other version

The new dashboard doesn't support the Service module currently.

tracking issue: https://github.com/apache/apisix-dashboard/issues/471

**Comment by LY-GO** [comment]
> please make a try with the master branch ^_^

i still use the master branch

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count.lua#L39

plugin `limit-count`, it has supported using `service_id` as key in master branch.

which plugin you want to support `service_id` ?

**Comment by LY-GO** [comment]
> please make a try with the master branch ^_^

I can require service_id from  Eureka?

**Comment by LY-GO** [comment]
> https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count.lua#L39
> 
> plugin `limit-count`, it has supported using `service_id` as key in master branch.
> 
> which plugin you want to support `service_id` ?

plugin of limit-conn and limit-req

**Comment by membphis** [comment]
welcome to submit PR to support `service_id` for `limit-conn` or `limit-req`.

they were should be the same as `limit-count`.

**Comment by LY-GO** [comment]
> welcome to submit PR to support `service_id` for `limit-conn` or `limit-req`.
> 
> they were should be the same as `limit-count`.

How ca i require service_id through Euerka?

**Comment by membphis** [comment]
> How can i require service_id through Euerka?

sorry I do not understand your question.
