### ISSUE TITLE
request help: the difference between limit-conn and limit-req

### ISSUE THREAD

**Issue by LY-GO** [apache/apisix#2483]
### Issue description
the difference between limit-conn and limit-req;the limit-conn is used to limit connection,but limit-req is used to limit request
<img width="953" alt="req and conn" src="https://user-images.githubusercontent.com/67543312/96680512-3df79000-13a8-11eb-9a05-17f549c3b24f.png">

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
limit-conn: Token Bucket
limit-req: Leaky Bucket

for more information, you can read the doc of the plugin, the attributes are very different.
