### ISSUE TITLE
request help: apifix support the etcd cluster of HTTPS？

### ISSUE THREAD

**Issue by kuaiwenwu** [apache/apisix#2489]
### Issue description
cn:
apisix 是否支持 https 的etcd集群呢？
我没有在配置文件中看到配置etcd证书的相关的参数。
请指教如何实现。
en:
Does apifix support the etcd cluster of HTTPS?
I don't see the parameters related to configuring the etcd Certificate in the configuration file.
Please tell me how to do it.

### Environment

* apisix version (apisix`1.5`):
* OS:centos7

**Comment by moonming** [comment]
not yet. Welcome to discuss how to do this

**Comment by tokers** [comment]
I think for now, only the simple TLS can be used in APISIX since the limitation of Cosocket, i.e. your etcd cluster must not enable the `--client-cert-auth` option.

**Comment by tokers** [comment]
@moonming Maybe we can support the simple TLS mode firstly.

**Comment by moonming** [comment]
> @moonming Maybe we can support the simple TLS mode firstly.

Cool, agree + 1

**Comment by kuaiwenwu** [comment]
Thank you very much for your reply. Next, I'll make some adjustments here. Thank you
