### ISSUE TITLE
discuss: In the request of the `hmac-auth` plugin, remove the request header related to the plugin

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2490]
### Issue description

In the process of using the hmac-auth plug-in, we do not want to send the http request header related to the plug-in to the upstream service. The reasons are as follows:
1. For security, please hide these headers.
2. Follow-up logic and upstream do not need these fields.

The http request headers related to the `hmac-auth` plugin are (the default plugin):

```
X-HMAC-SIGNATURE,
X-HMAC-ALGORITHM,
X-HMAC-SIGNED-HEADERS
```

These http request header names have default values in the plugin and can also be customized in the `conf/config.yaml` file.

**Comment by moonming** [comment]
Why delete these request headers?  Are there any protocol specifications?

**Comment by Firstsawyou** [comment]
> Why delete these request headers? Are there any protocol specifications?

These request headers are related to the `hmac-auth` plugin, and upstream does not need to care about their existence (except `access-key`).

**Comment by gxthrj** [comment]
There are the following considerations for deleting the hmac signature header:
1. To be safe, hide these headers
2. Follow-up logic and upstream do not need these fields

but access-key is useful，it can not be remove.

**Comment by moonming** [comment]
@Firstsawyou What are the http headers related to this plugin? Where is the unified definition and management?

**Comment by Firstsawyou** [comment]
> W

There are two ways to define request headers related to the `hmac-auth` plugin:
1. The signature information is separately placed in the request header
Related request headers are(plugin default):
```
X-HMAC-ACCESS-KEY,
X-HMAC-SIGNATURE,
X-HMAC-ALGORITHM,
X-HMAC-SIGNED-HEADERS,
Date
```
The `X-HMAC-SIGNED-HEADERS` is of the `array` type and can have multiple request headers.
These request header names have default values ​​in the plugin, and can also be customized in the `conf / config.yaml` file.

2. Put the signature information together in the Authorization field of the request header
Related request headers are:
```
Authorization,
X-HMAC-SIGNED-HEADERS
```

**Comment by Firstsawyou** [comment]
> @Firstsawyou What are the http headers related to this plugin? Where is the unified definition and management?

There are two ways to define request headers related to the `hmac-auth` plugin:
1. The signature information is separately placed in the request header
Related request headers are(plugin default):
```
X-HMAC-ACCESS-KEY,
X-HMAC-SIGNATURE,
X-HMAC-ALGORITHM,
X-HMAC-SIGNED-HEADERS,
Date
```
The `X-HMAC-SIGNED-HEADERS` is of the `array` type and can have multiple request headers.
These request header names have default values ​​in the plugin, and can also be customized in the `conf / config.yaml` file.

2. Put the signature information together in the Authorization field of the request header
Related request headers are:
```
Authorization,
X-HMAC-SIGNED-HEADERS
```

**Comment by gxthrj** [comment]
1. We often use the first way to do hmac verification, and the headers are displayed separately.
When the verification is successful, we keep the `X-HMAC-ACCESS-KEY`, and remove `X-HMAC-SIGNATURE` `X-HMAC-ALGORITHM` `X-HMAC-SIGNED-HEADERS`.

2. I'm not sure if the way of putting the signature information together in the Authorization field is standard usage. 
But in this way, We need to discuss how to deal with `Authorization`. 
I suggest to remove  header `Authorization` and add header `X-HMAC-ACCESS-KEY`.

**Comment by Firstsawyou** [comment]
I think after parsing `Authorization`, we can get the value of `access-key` and add ʻaccess-key` to the http request header. Then `Authorization` can be removed.

**Comment by gxthrj** [comment]
> I think after parsing `Authorization`, we can get the value of `access-key` and add ʻaccess-key`to the http request header. Then`Authorization` can be removed.

Or we do not support the way of putting the signature information together in the Authorization field.
I didn't find any benefits for this. 
 1.  Hidden the header organization order.
 2. There is no corresponding header name definition.
 3. `access-key` as the user flag should not be hidden in `Authorization`.

**Comment by membphis** [comment]
> X-HMAC-ACCESS-KEY,
> X-HMAC-SIGNATURE,
> X-HMAC-ALGORITHM,
> X-HMAC-SIGNED-HEADERS,
> Date

I think we can remove `X-HMAC-SIGNATURE`, `X-HMAC-ALGORITHM` and `X-HMAC-SIGNED-HEADERS`.

And we should keep `X-HMAC-ACCESS-KEY` and `Date`. what do you think? @gxthrj @Firstsawyou

**Comment by Firstsawyou** [comment]
> > X-HMAC-ACCESS-KEY,
> > X-HMAC-SIGNATURE,
> > X-HMAC-ALGORITHM,
> > X-HMAC-SIGNED-HEADERS,
> > Date
> 
> I think we can remove `X-HMAC-SIGNATURE`, `X-HMAC-ALGORITHM` and `X-HMAC-SIGNED-HEADERS`.
> 
> And we should keep `X-HMAC-ACCESS-KEY` and `Date`. what do you think? @gxthrj @Firstsawyou

Why do we need to keep the `date`, upstream should not need it. I don't understand here?

**Comment by Firstsawyou** [comment]
Do we need to add a switch option in `schema` to control the deletion of HTTP request headers?

**Comment by imjoey** [comment]
> > > X-HMAC-ACCESS-KEY,
> > > X-HMAC-SIGNATURE,
> > > X-HMAC-ALGORITHM,
> > > X-HMAC-SIGNED-HEADERS,
> > > Date
> > 
> > 
> > I think we can remove `X-HMAC-SIGNATURE`, `X-HMAC-ALGORITHM` and `X-HMAC-SIGNED-HEADERS`.
> > And we should keep `X-HMAC-ACCESS-KEY` and `Date`. what do you think? @gxthrj @Firstsawyou
> 
> Why do we need to keep the `date`, upstream should not need it. I don't understand here?

`Date` is a general and commonly used HTTP header, so we would better not remove it beforehand from the request sent to upstreams.

**Comment by membphis** [comment]
> @Firstsawyou `Date` is a general and commonly used HTTP header, so we would better not remove it beforehand from the request sent to upstreams.

agree with this. that is my reason too.

> And we should keep `X-HMAC-ACCESS-KEY` and `Date`. what do you think? @gxthrj @Firstsawyou

@gxthrj please help me to confirm if the upstream service need `X-HMAC-ACCESS-KEY`, I can not sure about this.

**Comment by Firstsawyou** [comment]
> > > > X-HMAC-ACCESS-KEY,
> > > > X-HMAC-SIGNATURE,
> > > > X-HMAC-ALGORITHM,
> > > > X-HMAC-SIGNED-HEADERS,
> > > > Date
> > > 
> > > 
> > > I think we can remove `X-HMAC-SIGNATURE`, `X-HMAC-ALGORITHM` and `X-HMAC-SIGNED-HEADERS`.
> > > And we should keep `X-HMAC-ACCESS-KEY` and `Date`. what do you think? @gxthrj @Firstsawyou
> > 
> > 
> > Why do we need to keep the `date`, upstream should not need it. I don't understand here?
> 
> @Firstsawyou `Date` is a general and commonly used HTTP header, so we would better not remove it beforehand from the request sent to upstreams.

Thank you for answering, I understand.

**Comment by membphis** [comment]
@Firstsawyou please update the description about this issue, it makes me confused.

what is the final result?

**Comment by Firstsawyou** [comment]
> @Firstsawyou please update the description about this issue, it makes me confused.

Thanks for your suggestion, the description has been updated.
