### ISSUE TITLE
bug: log system only print log of error,but log of info can't print

### ISSUE THREAD

**Issue by LY-GO** [apache/apisix#2494]
### Issue description

log system only print log of error,but log of info can't print
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
you need to set a lower log level:

https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L112
