### ISSUE TITLE
[DISCUSS]: The plugin hmac-auth remove the support the way of Authorization header

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2496]
### Issue description

I suggest removing support for Authorization header. 
the usage is [here](https://github.com/apache/apisix/blob/master/doc/plugins/hmac-auth.md#use-the-generated-signature-to-try-the-request)

I didn't find any benefits for this.

1. Hidden the header organization order.
2. There is no corresponding header name definition.
3. access-key as the user flag should not be hidden in Authorization.

**Comment by membphis** [comment]
duplicated: https://github.com/apache/apisix/issues/2490
