### ISSUE TITLE
request help: how can I get the log

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix#2500]
### Issue description
我在开发一个插件，模仿已有的插件代码使用了core.log.info()，但是我找不到日志打印，conf/logs下没有我想要的日志输出，求教
日志文件在哪
### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos 7

**Comment by membphis** [comment]
the default log level is `warn`: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L112

you need to change it.
