### ISSUE TITLE
whitelist and limit-conn plugin is conflict in same route

### ISSUE THREAD

**Issue by damage85** [apache/apisix#2503]
apisix server version: 1.4

1. add route "whitelist"，path is “/api/whitelist” and choose upstream
2. input IPV4 and my IP in ip restriction config page and then save
3. access the http api submitting by my IP
4. I expect that apisix will return the upstream result but it return an error page showing 500 internal server error
5. single whitelist rule is tested fine.

submit data:

```json
{
	"name": "whitelist",
	"route_group_id": "790a7a05-f67b-4bb6-a369-1379336d8416",
	"route_group_name": "数据接口",
	"status": true,
	"protocols": ["http", "websocket"],
	"paths": ["/service/whitelist/*"],
	"methods": ["GET"],
	"upstream_protocol": "http",
	"upstream_id": "bf9bdd26-5d4c-4268-a747-0c8af81eb355",
	"type": "roundrobin",
	"plugins": {
		"ip-restriction": {
			"whitelist": ["172.16.33.8"]
		},
		"limit-conn": {
			"burst": 0,
			"conn": 1,
			"default_conn_delay": 0,
			"key": "remote_addr",
			"rejected_code": 503
		}
	},
	"script": {},
	"uris": ["/service/whitelist/*"],
	"vars": [],
	"upstream_header": {},
	"upstream_path": {
		"to": "/emergency/temporary/host"
	}
}
```

[error.docx](https://github.com/apache/apisix/files/5427858/error.docx)

**Comment by spacewander** [comment]
> showing 500 internal server error

What did you see in the logs/error.log when the 500 happened?

**Comment by damage85** [comment]
> 2020/10/26 11:50:16 [error] 5443#5443: *25621116 lua entry thread aborted: runtime error: /usr/local/openresty/lualib/resty/limit/conn.lua:32: assertion failed!
stack traceback:
coroutine 0:
        [C]: in function 'assert'
        /usr/local/openresty/lualib/resty/limit/conn.lua:32: in function 'create_obj_fun'
        /usr/local/apisix/apisix/core/lrucache.lua:174: in function 'plugin_ctx'
        /usr/local/apisix/apisix/plugins/limit-conn.lua:64: in function 'phase_fun'
        /usr/local/apisix/apisix/init.lua:147: in function 'run_plugin'
        /usr/local/apisix/apisix/init.lua:385: in function 'http_access_phase'
        access_by_lua(nginx.conf:171):2: in main chunk, client: 172.16.33.4, server: , request: "GET //api/hjw/test1 HTTP/1.1", host: "172.16.27.51:18888"

**Comment by membphis** [comment]
the `default_conn_delay` should greater than `0`, eg: `0.1`.

this is a bug of version `1.5`, we have fixed this issue in master branch. 

please make a try with the latest version or `2.0` version.

**Comment by damage85** [comment]
> the `default_conn_delay` should greater than `0`, eg: `0.1`.
> 
> this is a bug of version `1.5` or `1.4`, we have fixed this issue in master branch.
> 
> please make a try with the latest version or `2.0` version.

It is the same result after I tried changing `default_conn_delay` from 0 to 0.1, conn =1 and burst = 1
