### ISSUE TITLE
[discuss] about localized require

### ISSUE THREAD

**Issue by RocFang** [apache/apisix#2506]
As we konw, In openresty we should localize require, and in apisix's lua scripts, the luacheck helps us do the checking.
But in some cases, like nginx.conf generated by template, there are global require, for example:

```
apisix = require("apisix")
```
Because they are in nginx.conf's xxx_by_lua_block, they can't be cecked by luacheck.

So, Is it nessesary to follow the lua code style in nginx.conf?

thanks.

**Comment by membphis** [comment]
I only found those:

https://github.com/apache/apisix/blob/master/bin/apisix#L283-L284

In `init_by_lua_block` phase, it not a hot path, so we do not need localize `require`.

**Comment by RocFang** [comment]
@membphis thanks. maybe i did not express it clearly. my question is not about localize require,like local  require = require,but the global variable apisix.
but of course  i agrew that it's not a problem. thabks.

**Comment by membphis** [comment]
for variable `apisix`, I think it is fine. 

It is the right way. 

Please feel free to reopen this issue if you still have questions about it.
