### ISSUE TITLE
request help:  route match with  customize the request header rules

### ISSUE THREAD

**Issue by sixinyiyu** [apache/apisix#2508]
### Issue description

request heders 
  a:     client_type  xxx_ios  
          client_version 2.0
  b:    client_type xxx_android
         client_version 2.1

different headers variable match different router with different priority

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos 7

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

please pay attention on the `vars` and `priority`, you need it

**Comment by sixinyiyu** [comment]
"vars": [ 
        ["http_origin", "==", "http://xxx.api.cn"]
    ]

it's work

**Comment by spacewander** [comment]
Consider solved.
