### ISSUE TITLE
[discuss]: use fault-injection plugin to implement mock function

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2511]
### Issue description

We can add new features to the fault-injection plugin for the following reasons:
Currently, the `fault-injection` plugin does not support custom conditions to implement the `mock` function. I think we can add the request header as a conditional judgment in the request (there may be a better way) to realize the mock function.
E.g:

```
"vars": [
     [ "http_mock01", "==", " api01" ],
     [ "http_mock02", "==", " api02" ]
]
```
When there are multiple conditions in `vars`, they have an `or` relationship.
If `vars` passes the verification, fault injection is performed on the request. Otherwise, no processing is done on the request. In order to maintain backward compatibility, the fault injection operation is still performed when the vars condition is not configured.

**Comment by membphis** [comment]
I think this feature is useful. Can we implement the `vars` in a common way? 

Then this feature can be reused in different plugins.

BTW, you wrote a typo, `httP_mock01` -> `http_mock01 `, is it right?

**Comment by Firstsawyou** [comment]
> I think this feature is useful. Can we implement the `vars` in a common way?
> 
> Then this feature can be reused in different plugins.
> 
> BTW, you made a typo, `httP_mock01` -> `http_mock01 `, is it right?

Thank you for your suggestion, I think it is achievable, I can try it.
