### ISSUE TITLE
Use APISIX_WORKER_PROCESSES instead of APIX_WORKER_PROCESSES?

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#2517]
The former one is more compatible with the name of this project.
CC @ShiningRush @membphis

**Comment by membphis** [comment]
agree +1

`APIX_WORKER_PROCESSES` is not easy to understand.

`APIX` is very different from `APISIX`.

**Comment by moonming** [comment]
> agree +1
> 
> 
> 
> `APIX_WORKER_PROCESSES` is not easy to understand.
> 
> 
> 
> `APIX` is very different from `APISIX`.

+1. We should always use APISIX

**Comment by ShiningRush** [comment]
The prefix generally does not exceed four letters, such as `kubernetes -> kube`, `prometheus -> prom`, `grafana-> gf`.

I think the prefix is ​​just a format, which doesn't have much meaning in itself. Whether it is `APIX` or `AX`, as long as the community defines it, the people who use it will always remember it.
But if everyone thinks ʻAPISIX` is more suitable, six letters are also acceptable, although I rarely see such a long prefix

**Comment by tokers** [comment]
agree + 1

We don't have to be limited by the number of letters, meanings first.

**Comment by Miss-you** [comment]
I don't think environmental variables `APISIX_WORKER_PROCESSES` are a good idea.
It makes sense to count the number of CPUs based on cgroup information.

but, APISIX_WORKER_PROCESSES is better than APIX_WORKER_PROCESSES
