### ISSUE TITLE
request help: [doc] need quick-start

### ISSUE THREAD

**Issue by zhangguanzhang** [apache/apisix#2530]
### Issue description
need qucik-start

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
welcome PR

**Comment by membphis** [comment]
here is the related doc: https://github.com/apache/apisix/tree/master#get-started

feel free to re-edit it for a better one.

**Comment by zhangguanzhang** [comment]
This part of the information is too little, a more complete entry process document is needed

**Comment by membphis** [comment]
welcome PR ^_^

**Comment by idbeta** [comment]
I think it would be better and helpful if you could provide more details about `qucik-start`, or PR like upper post.

**Comment by zhangguanzhang** [comment]
就是从简单的demo到入门，到常见的，到高级的一步步，而不是零散的doc介绍各个部分

**Comment by tokers** [comment]
> 就是从简单的demo到入门，到常见的，到高级的一步步，而不是零散的doc介绍各个部分

Well, I think some best practices articles/blogs are needed @membphis

**Comment by membphis** [comment]
agree, we need it. welcome PR ^_^

**Comment by spacewander** [comment]
Already done?

**Comment by membphis** [comment]
we can close this issue, added this doc
