### ISSUE TITLE
doc(plugins/hmac-auth): generate signature should be more detailed

### ISSUE THREAD

**Issue by fukiki** [apache/apisix#2531]
### Issue description
In  [hmac-auth.md](https://github.com/apache/apisix/blob/master/doc/plugins/hmac-auth.md) , about generate signature, there should be a more detailed introduction:

1、About `signature = HMAC-SHAx-HEX(secret_key, signing_string)` , list some examples for different language, would be better.
2、The parameter signature should be base64 encoded, for example: base64.b64encode(signature)
3、In headers，the value of "X-HMAC-SIGNED-HEADERS", should be splited by ";", such as: "x-hmac-header-a;x-hmac-header-b"

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos 7

**Comment by membphis** [comment]
welcome PR, LGTM
