### ISSUE TITLE
feat:   Apisix upstream domain resolver can not support "search  xxxx, options  xxxxx" in k8s environment

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2532]
### Issue description
for example  in k8s environment , we can use  service name as backend nodes, sometime  for core DNS query we can combine the service name  and "svc.cluster.local" as the domain, the  resolve config is 
```
nameserver 10.96.0.10
search svc.cluster.local cluster.local
options ndots:5
```
apisix just support "nameserver",ref code:  https://github.com/apache/apisix/blob/master/apisix/core/utils.lua#L75,so we must define the full domain "xxxx.svc.cluster.local", But  we can not us other suffix such as "cluster.local". Should we support the full dns resolve rule?
### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by membphis** [comment]
> Should we support the full dns resolve rule?

do you know how it works? I am not familiar with this.

**Comment by gy09535** [comment]
I know some from k8s core dns resolver, Now I read this page:https://linux.die.net/man/5/resolv.conf , full support is difficult, But support search and options can work in k8s cluster.

**Comment by membphis** [comment]
welcome PR for this feature.

if you need any help, please let us know.

**Comment by gy09535** [comment]
> welcome PR for this feature.
> 
> if you need any help, please let us know.

Sure, thanks.

**Comment by dickens7** [comment]
To solve this problem, you can refer to or use this library directly

https://github.com/Kong/lua-resty-dns-client

@gy09535

**Comment by gy09535** [comment]
> To solve this problem, you can refer to or use this library directly
> 
> https://github.com/Kong/lua-resty-dns-client
> 
> @gy09535

See it, It it great.

**Comment by ShaoZeMing** [comment]
> > 要解决此问题，您可以直接参考或使用此库
> > https://github.com/Kong/lua-resty-dns-client
> > @ gy09535
> 
> 看到它，太好了 💯

+1

**Comment by ShaoZeMing** [comment]
> > 要解决此问题，您可以直接参考或使用此库
> > https://github.com/Kong/lua-resty-dns-client
> > @ gy09535
> 
> 看到它，太好了 💯

hello 我们目前特别迫切需要这个功能，想知道这个功能开发情况如何了？

**Comment by gy09535** [comment]
> > > 要解决此问题，您可以直接参考或使用此库
> > > https://github.com/Kong/lua-resty-dns-client
> > > @ gy09535
> > 
> > 
> > 看到它，太好了 💯
> 
> hello 我们目前特别迫切需要这个功能，想知道这个功能开发情况如何了？

I will try to do it next week, if I have times.

**Comment by ShaoZeMing** [comment]
> > > > 要解决此问题，您可以直接参考或使用此库
> > > > https://github.com/Kong/lua-resty-dns-client
> > > > @ gy09535
> > > 
> > > 
> > > 看到它，太好了 💯
> > 
> > 
> > hello 我们目前特别迫切需要这个功能，想知道这个功能开发情况如何了？
> 
> I will try to do it next week, if I have times.

好的，非常感谢。

**Comment by membphis** [comment]
> I will try to do it next week, if I have times.

any news? @gy09535

**Comment by gy09535** [comment]
> > I will try to do it next week, if I have times.
> 
> any news? @gy09535

I am doing it in my company repository, when I finish it I will  copy it to apisix.
