### ISSUE TITLE
request help: how to find routes/upstreams in etcd?

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#2535]
### Issue description
Hi, we are create a route and a upstream using apisix api, but can't find it in etcd db.

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS:centos7

![image](https://user-images.githubusercontent.com/10362371/97296737-026b3300-188c-11eb-91f1-2be2378a88e8.png)

**Comment by gewei2000** [comment]
@membphis @moonming

**Comment by tokers** [comment]
@gewei2000 APISIX/1.5 uses the etcd v2 store, while you are using the v3 protocol to get data from v3 mvcc backend, which is separated with v2 store, try:

```
ETCDCTL_API=2 etcdctl ls /apisix
```

**Comment by gewei2000** [comment]
> @gewei2000 APISIX/1.5 uses the etcd v2 store, while you are using the v3 protocol to get data from v3 mvcc backend, which is separated with v2 store, try:
> 
> ```
> ETCDCTL_API=2 etcdctl ls /apisix
> ```

thks
