### ISSUE TITLE
request help: configure route to only execute plugins

### ISSUE THREAD

**Issue by thekingofworld** [apache/apisix#2542]
### Issue description
I want configure a route to only execute plugins: 
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -d '
{
    "plugins": {
        "cgi-proxy": {
        }
    },
    "uri": "/cgi-proxy"
}'
```
But an error occurred while requesting
![image](https://user-images.githubusercontent.com/8169665/97319518-effef280-18a7-11eb-961d-b7a8e2b290c4.png)
### Environment

Can anyone help? thx
* apisix version (cmd: `apisix version`): 
   2.0
* OS:
   mac

**Comment by lilien1010** [comment]
You need specific a upstream in the route, with a upstream or a upstream_id.

**Comment by thekingofworld** [comment]
![image](https://user-images.githubusercontent.com/8169665/97390355-90d8c680-1917-11eb-878b-ad7772ec8870.png)
It seems we don’t have to configure upstream.

**Comment by membphis** [comment]
what is the plugin `cgi-proxy`? do you set any upstream object in this plugin?

**Comment by Miss-you** [comment]
> cgi-proxy

cgi-proxy should be a custom plugin.
CGI is an internal Tencent term that uses apache httpd to provide http services which use CGI.

**Comment by Miss-you** [comment]
> ### Issue description
> I want configure a route to only execute plugins:
> 
> ```
> curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -d '
> {
>     "plugins": {
>         "cgi-proxy": {
>         }
>     },
>     "uri": "/cgi-proxy"
> }'
> ```
> 
> But an error occurred while requesting
> ![image](https://user-images.githubusercontent.com/8169665/97319518-effef280-18a7-11eb-961d-b7a8e2b290c4.png)
> 
> ### Environment
> Can anyone help? thx
> 
> * apisix version (cmd: `apisix version`):
>   2.0
> * OS:
>   mac

The route requires at least one plugin or upstream binding.
