### ISSUE TITLE
request help: Different routes have different access permission

### ISSUE THREAD

**Issue by lhtlp1997** [apache/apisix#2544]
### Issue description: Different routes have different access permission
I added a Key-Auth plugin to my new route. But I found that ***all the consumers that have key-auth can access to the route***.

What I want to do is that ***different routes have different access permission***. But According to the doc(https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/key-auth.md), I don't know how to do.

Are there any solutions?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
https://github.com/apache/apisix/blob/master/doc/plugins/consumer-restriction.md

I think you need this plugin. 

please feel free to reopen this issue if you still have a problem with this issue.
