### ISSUE TITLE
request help: how to serve static file with apisix

### ISSUE THREAD

**Issue by qiufeihai** [apache/apisix#2550]
### Issue description
how to serve static file with apisix

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: Centos

**Comment by membphis** [comment]
apisix is an API gateway. for static files, you can use another nginx upstream.

client -> apisix -> nginx upstream(static file)

**Comment by Miss-you** [comment]
client -> apisix -> server (hugo/gin/ and so on.)

https://github.com/gohugoio/hugo
https://github.com/gin-gonic/gin

client->CDN(such as Cloudfare)->API Gateway(Apache APISIX) -> your server (hugo/gin/httpd/nginx)

**Comment by belongwqz** [comment]
How to setup apisix to get the same effect in nginx as:
```
location /static_sub_path/ {
    alias /local_static_file_path/;
}
```

**Comment by q2dg** [comment]
It's shocking that in a Apache's project (as Apisix is), Apache's httpd server isn't mencioned for anything
