### ISSUE TITLE
apisix 2.X    支持etcd ssl配置吗，想共用k8s集群中的etcd

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#2551]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/pull/2548

**Comment by Yangzcy423911** [comment]
您好，没有找到关于TLS KEY的配置

**Comment by tokers** [comment]
@Yangzcy423911 Even after #2548 is merged, APISIX still cannot support the **mutual** TLS connection with etcd.

**Comment by tokers** [comment]
> 您好，没有找到关于TLS KEY的配置

I bet you mean the client cert, key and ca certificate?

**Comment by Yangzcy423911** [comment]
明白了，谢谢您！

**Comment by Miss-you** [comment]
I think you can use the etcd proxy localily.
[Apache APISIX -> etcd proxy(cert) ]--http mTLS-->[etcd]
