### ISSUE TITLE
[discuss]: support ctx.var to get service_name

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2563]
DISCUSS：

In some scenarios, only by `service_id` it is not possible to directly tell which service is. I think that if we can support `ctx.var` to get `service_name`, then it will be easier for us to know which `service` is currently through `service_name`.

For example: when using the `prometheus` plugin, we only get the `service_id` through the Prometheus dashboard, which is not easy to understand the service. When the `service_name` field is added, we can more easily understand who this service is.
But `service_name` is not a unique identifier. I am not sure if adding `ctx.var` to get `service_name` is a good idea.

Welcome to discuss.

**Comment by moonming** [comment]
You can get the service name through service id, why must it be obtained through `ctx.var`?

**Comment by Firstsawyou** [comment]
> You can get the service name through service id, why must it be obtained through `ctx.var`?

Very good, thank you for your suggestion, I will try it.

**Comment by Firstsawyou** [comment]
> You can get the service name through service id, why must it be obtained through `ctx.var`?

Thank you very much, I got it. ^_^
