### ISSUE TITLE
support include other nginx config in the apisix(lua file)

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#2565]
### Issue description
I can find that apisix use template to generate nginx.conf in the apisix(lua file),   we need to change this file  in following scenarios in my company
- Setting third nginx module param;
- Setting nginx params not supported in config.ymal
- Export other servers  and locations which third nginx module needed

What's about adding a new feature, for example,  support including other nginx conf file in the  apisix(lua file)
Thank you!

### Environment

* apisix version (master):

**Comment by nic-chen** [comment]
Could you show some example?

**Comment by nanamikon** [comment]
Sure！
For example
```
req_status_zone host "$server_name" 200M;
req_status_zone hostadr "$server_name:$upstream_addr" 200M;
req_status host hostadr;
req_status_lazy on;

server
{
    listen 45651;
    server_name _;
    access_log off;

    location /ysec_status {
        req_status_show;
        allow 127.0.0.1;
        deny all;
    }
}
```

**Comment by tzssangglass** [comment]
You mean like the nginx_http_include directive from kong?

```
nginx_http_include = /path/to/your/extend.conf
```

the `extend.conf` may be like 

```conf
lua_shared_dict custom_plugin_a_cache 8m;
lua_shared_dict custom_plugin_b_cache 8m;
```

then this configuration will appear in the `nginx.conf`

**Comment by spacewander** [comment]
I will vote for ingress-nginx's snippet feature: 
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet

This feature can be configured directly in the yaml file.

**Comment by nic-chen** [comment]
> I will vote for ingress-nginx's snippet feature: 
> 
> https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet
> 
> 
> 
> This feature can be configured directly in the yaml file.

agree +1

**Comment by tzssangglass** [comment]
I doubt this will solve the renaming configuration, e.g. I want to configure multiple `lua_shared_dict`

**Comment by spacewander** [comment]
@tzssangglass 
Configure `lua_shared_dict` is already supported: https://github.com/apache/apisix/blob/1fb000c92e9252c5872a83278cb44652ebdfe4d5/conf/config-default.yaml#L142

Why do you think this feature can't be supported via snippets?

**Comment by tzssangglass** [comment]
> @tzssangglass
> Configure `lua_shared_dict` is already supported:
> 
> https://github.com/apache/apisix/blob/1fb000c92e9252c5872a83278cb44652ebdfe4d5/conf/config-default.yaml#L142
> 
> Why do you think this feature can't be supported via snippets?

Good. I had misconceptions about snippets before. I'm not sure if all the configurations can be translated from `yaml` to the final `nginx.conf`, so I thought if the ability to load extend.conf could be provided, there could be a back up plan.

**Comment by nanamikon** [comment]
> I will vote for ingress-nginx's snippet feature:
> https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#configuration-snippet
> 
> This feature can be configured directly in the yaml file.

Good idea ， most of situation can be covered。

```
server
{
    listen 45651;
    server_name _;
    access_log off;

    location /ysec_status {
        req_status_show;
        allow 127.0.0.1;
        deny all;
    }
}
```
But I think this format of config is not suitable to write to ymal

**Comment by spacewander** [comment]
@nanamikon 
I think we can write them in a literal block, see `literal_block` in https://learnxinyminutes.com/docs/yaml/. We should take care about the indentation of Nginx configuration. But once the configuration is indented, it is suitable in the yaml file.
