### ISSUE TITLE
bug: uri-blocker's code and doc are confusing

### ISSUE THREAD

**Issue by RocFang** [apache/apisix#2568]
### Issue description

In uri-blocker's doc, we can get every block rule is a independent regular expression.
But in the code, we can find that every rule is concated into a single regular expression, so `^` and `$` may not work as expected.

I guess the concating operation instead of literate rule array is for performance consideration? But does it realy matters a lot, consider the extra copy of the array.
If it's by design, I think the doc may need some updates for the cenarios mentioned above. thanks. @membphis

**Comment by idbeta** [comment]
Can you write more details about regular expressions that go wrong? That would be very helpful

**Comment by RocFang** [comment]
@idbeta sorry, my mistake, ignore it:)
