### ISSUE TITLE
CI: line is too line

### ISSUE THREAD

**Issue by starsz** [apache/apisix#2569]
Hi, while I am reading the code, I found that some lines are too long (More than eighty characters).

As the [CODE_STYLE.md](https://github.com/apache/apisix/blob/master/CODE_STYLE.md#maximum-length-per-line) said.

> Each line cannot exceed 80 characters. If it exceeds, you need to wrap and align:

I recommend adding `--max-line-length 80` into luacheck, and fix all the lines exceed 80 characters.

**Comment by idbeta** [comment]
I agree that 80 characters are enough most of the time, but sometimes 80 characters seem a little bit short and make the code more awkward to read, just for python.

**Comment by tokers** [comment]
The specification of 80 characters forces programmer to design concise variable name, function name and literals, I don't think it makes the code more awkward to read (if so, community can refactor it :) ),  so i think we should obey the code style specification.

**Comment by spacewander** [comment]
@starsz 
Currently we already have the line length style check in `lj-releng`. The length we chose is 100.

**Comment by starsz** [comment]
Okay, I follow the decision of the community. Hmmm.

**Comment by membphis** [comment]
> The length we chose is 100.

I think `100` is fine.

https://github.com/apache/apisix/blob/master/.luacheckrc#L4

we checked it by `luacheck` too.
