### ISSUE TITLE
request help: support centos 7, centos 8 in CI

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2573]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by idbeta** [comment]
Github action runs-on only supports a few systems: [detail](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on)
I think it is possible to test on centos7&8 by creating docker container Github action.

**Comment by membphis** [comment]
Github action OS list:

![image](https://user-images.githubusercontent.com/6814606/97715086-ec17de00-1afc-11eb-9426-f5698d2ef70e.png)

**Comment by moonming** [comment]
@idbeta any update?

**Comment by moonming** [comment]
@idbeta this issue blocked 2.1 release

**Comment by idbeta** [comment]
I will start this thing as soon as possible.

**Comment by membphis** [comment]
@idbeta please confirm you finish this job in this week. if not, we change this `Milestone` to `2.2`

**Comment by idbeta** [comment]
Sorry, I think I can not finish it this week. @moonming @membphis

**Comment by membphis** [comment]
Okay, I got it. I have changed the milestone to the 2.2.

**Comment by idbeta** [comment]
Hello @gxthrj @nic-chen, I have two questions, need your help.  
1. I deployed Centos7 by using a docker container in the CI server, deployed APISIX in it, and executed all cases, some succeeded, like:
```
/admin/*.t
/config-center-yaml/*.t
/debug/*.t
/router/*.t
/script/*.t
/stream-node/*.t
/stream-plugin/*.t
/utils/*.t
```
but some cases failed for strange reasons. Do you know the reason? 
```
Cannot detect source of 't/certs/*.t'! at /usr/share/perl5/vendor_perl/TAP/Parser/IteratorFactory.pm line 263.
	TAP::Parser::IteratorFactory::detect_source('TAP::Parser::IteratorFactory=HASH(0x1559df0)', 'TAP::Parser::Source=HASH(0x144fec0)') called at /usr/share/perl5/vendor_perl/TAP/Parser/IteratorFactory.pm line 213
	TAP::Parser::IteratorFactory::make_iterator('TAP::Parser::IteratorFactory=HASH(0x1559df0)', 'TAP::Parser::Source=HASH(0x144fec0)') called at /usr/share/perl5/vendor_perl/TAP/Parser.pm line 469
	TAP::Parser::_initialize('TAP::Parser=HASH(0x154ecd0)', 'HASH(0x10e5638)') called at /usr/share/perl5/vendor_perl/TAP/Object.pm line 58
```
2. Because some plugins cases need to deploy docker containers (like zookeeper, kafka etc.), I don’t know how to combine Centos7 containers with these containers, can you give some advice?

here is my workflow file:
```
jobs:     
  test_apisix:
    name: test_apisix
    runs-on: ubuntu-latest
    container: docker.io/centos:7
    steps:
    - uses: actions/checkout@v2
 
    - name: intall deps
      run: |
        yum install -y wget tar gcc automake autoconf libtool make
        wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        rpm -ivh epel-release-latest-7.noarch.rpm
        yum install -y curl git luarocks lua-devel which
        wget https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz
        tar -xvf etcd-v3.4.13-linux-amd64.tar.gz && cd etcd-v3.4.13-linux-amd64 && cp -a etcd etcdctl /usr/bin/
        cd ..
        etcd &
        yum install -y yum-utils
        yum-config-manager --add-repo https://openresty.org/package/centos/openresty.repo
        yum install -y openresty-debug
        yum install -y openresty
        PATH=$PATH:/usr/local/openresty/luajit/bin:/usr/local/openresty/nginx/sbin:/usr/local/openresty/bin

    - name: run test
      run: |
        git clone https://github.com/apache/apisix.git
        cd apisix
        make deps

        export PERL5LIB=.:$PERL5LIB
        export OPENRESTY_PREFIX="/usr/local/openresty-debug"
        export PATH=$OPENRESTY_PREFIX/nginx/sbin:$OPENRESTY_PREFIX/luajit/bin:$OPENRESTY_PREFIX/bin:$PATH

        yum install -y cpanminus build-essential libncurses5-dev libreadline-dev libssl-dev perl
        cpanm --notest Test::Nginx IPC::Run > build.log 2>&1 || (cat build.log && exit 1)
        make test
```

**Comment by membphis** [comment]
> 1. I don’t know how to combine Centos7 containers with these containers

`--net=host`

**Comment by nic-chen** [comment]
> 2. Because some plugins cases need to deploy docker containers (like zookeeper, kafka etc.), I don’t know how to combine Centos7 containers with these containers, can you give some advice?

I think service is good for that:
https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers

**Comment by nic-chen** [comment]
> t/certs/*.t
t/certs/ has no test file at all.

**Comment by idbeta** [comment]
> > t/certs/*.t
> 
> t/certs/ has no test file at all.

Ok, I was cheated.
