### ISSUE TITLE
request help: new plugin feature

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#2574]
### Issue description
I want to develop a plugin, the plugin is to get the specified key (such as user id) from the cookie, then go to redis to read a json through this key, put it in the memory cache, let it automatically expire after 10 minute,  do we have this cache components?
@membphis @moonming

**Comment by membphis** [comment]
When you create `lru` object, you can enable the option `invalid_stale`.

https://github.com/apache/apisix/blob/9b63fd5710427820a9002920f8b48cb43bf06cd8/apisix/init.lua#L118

**Comment by gewei2000** [comment]
> When you create `lru` object, you can enable the option `invalid_stale`.
> 
> https://github.com/apache/apisix/blob/9b63fd5710427820a9002920f8b48cb43bf06cd8/apisix/init.lua#L118

thks
