### ISSUE TITLE
proposal: chaos test

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2577]
1. Background
      In the real world, various faults may occur anytime and anywhere, such as sudden disk write failure, or sudden network disconnection in the computer room, etc. In order to more easily verify APISIX's tolerance for various faults, we need to perform chaos testing.
2. Purpose
     Check whether APISIX can work normally in the case of various external faults.
3. Method
     Thanks to @Yiyiyimu for recommending a good testing tool that can simulate various system failures--[chaos-mesh](https://github.com/chaos-mesh/chaos-mesh), we can add a separate action to combine [chaos-mesh](https://github.com/chaos-mesh/chaos-mesh) to perform chaos testing on APISXI.

**Comment by moonming** [comment]
please send to mailinglist

**Comment by membphis** [comment]
for the important thing, we need to discuss it in the mailing list first. 

that is the apache way.

**Comment by moonming** [comment]
ping @idbeta

**Comment by spacewander** [comment]
Surpassed by https://github.com/apache/apisix/issues/2757
