### ISSUE TITLE
DISCUSS: should we distinguish the reload of plugin's metadata  from the reload of plugin's function?

### ISSUE THREAD

**Issue by dabue** [apache/apisix#2578]
### Issue description
APISIX plug-ins are hot-loaded, it's very convenient. But there are some tiny faults when we use timer in global plug-ins, just like log-rotate.

There will be more then one timer when we update the attributes of 'log-rotate' plug-in by reload.

You will find ‘pkg_loaded[pkg_name] = nil’  in Line 63 of apisix/plugin.lua,  the earlier timer created  will be out of control  when we reload the plug-in.

 Should we distinguish the reload of plugin's metadata  from the reload of plugin's function， provide a way to update the configuration only?

**Comment by membphis** [comment]
yes, we should fix this issue.

We implement a new API named `plugin.destroy`, is it fine?

Before reloading the plugin, we can try to call `plugin.destroy` to destroy the plugin instance.

**Comment by spacewander** [comment]
Since there is no way to cancel a timer, I think we need to use `timer.at` to create timer, and don't trigger a new timer when the conf_version is changed.

**Comment by spacewander** [comment]
Or maybe move the timer out of the plugin's `init` function, and only call when the plugin is loaded.

Anyway, if plugin's metadata is unsync with plugin's function, there will be many trouble. So I think it would be better if we can change them in the same time.

**Comment by dabue** [comment]
or we provide another way to reload plugin's metadata only?



88786912@qq.com
 
From: 罗泽轩
Date: 2020-10-31 13:17
To: apache/apisix
CC: dabue; Author
Subject: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
Or maybe move the timer out of the plugin's init function, and only call when the plugin is loaded.
Anyway, if plugin's metadata is unsync with plugin's function, there will be many trouble. So I think it would be better if we can change them in the same time.

**Comment by dabue** [comment]
or keep the revision of metadata in lua_shared_dict.  if need update metadata properties, using the ngx.timer.at replace the core.timer.new. like this   
```
 local delay = 5
 local meta_revision
 local first_load
 local handler
 handler = function (premature)
     if premature then
         return
     end
     if first_load  then
        local code, body = plugin_metadata.get(plugin_name)
        if code == 200 then
            meta_revision = body.header.revision
        else
            return
        end
        first_load = false
        ngx.shared.meta_revision:set(plugin_name, meta_revision)
     end
     
     if meta_revision ~= ngx.shared.meta_revision:get(plugin_name) then
        return
     end
     local ok, err = ngx.timer.at(delay, handler)
     if not ok then
         ngx.log(ngx.ERR, "failed to create the timer: ", err)
         return
     end

     -- do something in timer
 end

function _M.init()
    first_load = true
    local ok, err = ngx.timer.at(0, handler)
    if not ok then
        ngx.log(ngx.ERR, "failed to create the timer: ", err)
        return
    end
end

```



88786912@qq.com
 
From: dabue
Date: 2020-10-31 14:36
To: apache/apisix; apache/apisix
CC: Author
Subject: Re: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
or we provide another way to reload plugin's metadata only?



88786912@qq.com
 
From: 罗泽轩
Date: 2020-10-31 13:17
To: apache/apisix
CC: dabue; Author
Subject: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
Or maybe move the timer out of the plugin's init function, and only call when the plugin is loaded.
Anyway, if plugin's metadata is unsync with plugin's function, there will be many trouble. So I think it would be better if we can change them in the same time.

**Comment by dabue** [comment]
sorry, I made a conceptual mistake about the revision, we can use the md5 of metadata to replace it , just like:

```
 local delay = 5
 local meta_md5
 local first_load
 
 local handler

 handler = function (premature)
     if premature then
         return
     end
     if first_load  then
        local code, body = plugin_metadata.get(plugin_name)
        if code == 200 then
            meta_md5 = getMd5(core.json.encode(body.node.value))
        else
            return
        end
        first_load = false
        ngx.shared.meta_md5:set(plugin_name, meta_md5)
     end
     
     if meta_md5 ~= ngx.shared.meta_md5:get(plugin_name) then
        return
     end
     local ok, err = ngx.timer.at(delay, handler)
     if not ok then
         ngx.log(ngx.ERR, "failed to create the timer: ", err)
         return
     end

     -- do something in timer
 end

function _M.init()
    first_load = true
    local ok, err = ngx.timer.at(0, handler)
    if not ok then
        ngx.log(ngx.ERR, "failed to create the timer: ", err)
        return
    end
end
```



88786912@qq.com
 
From: dabue
Date: 2020-10-31 22:17
To: apache/apisix; apache/apisix
CC: Author
Subject: Re: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
or keep the revision of metadata in lua_shared_dict.  if need update metadata properties, using the ngx.timer.at replace the core.timer.new. like this   
```
 local delay = 5
 local meta_revision
 local first_load
 local handler
 handler = function (premature)
     if premature then
         return
     end
     if first_load  then
        local code, body = plugin_metadata.get(plugin_name)
        if code == 200 then
            meta_revision = body.header.revision
        else
            return
        end
        first_load = false
        ngx.shared.meta_revision:set(plugin_name, meta_revision)
     end
     
     if meta_revision ~= ngx.shared.meta_revision:get(plugin_name) then
        return
     end
     local ok, err = ngx.timer.at(delay, handler)
     if not ok then
         ngx.log(ngx.ERR, "failed to create the timer: ", err)
         return
     end

     -- do something in timer
 end

function _M.init()
    first_load = true
    local ok, err = ngx.timer.at(0, handler)
    if not ok then
        ngx.log(ngx.ERR, "failed to create the timer: ", err)
        return
    end
end

```



88786912@qq.com
 
From: dabue
Date: 2020-10-31 14:36
To: apache/apisix; apache/apisix
CC: Author
Subject: Re: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
or we provide another way to reload plugin's metadata only?



88786912@qq.com
 
From: 罗泽轩
Date: 2020-10-31 13:17
To: apache/apisix
CC: dabue; Author
Subject: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
Or maybe move the timer out of the plugin's init function, and only call when the plugin is loaded.
Anyway, if plugin's metadata is unsync with plugin's function, there will be many trouble. So I think it would be better if we can change them in the same time.

**Comment by dabue** [comment]
LGTM



88786912@qq.com
 
From: YuanSheng Wang
Date: 2020-10-30 22:11
To: apache/apisix
CC: dabue; Author
Subject: Re: [apache/apisix] DISCUSS: should we distinguish the reload of plugin's metadata from the reload of plugin's function? (#2578)
yes, we should fix this issue.
We implement a new API named plugin.destroy, is it fine?
Before reloading the plugin, we can try to call plugin.destroy to destroy the plugin instance.

**Comment by spacewander** [comment]
I though about this last weekend. We can fix it in two steps:
1. move `core.timer.new` out of `log-rotate` plugin, so it won't be affected when the plugin is reloaded.
2. since we already support set plugin's metadata via admin API, there is no need to configure them in the config.yaml, so can we get the configuration from etcd directly? It may introduce extra step in the deployment, since we won't configure the metadata directly via file. CC @nic-chen

**Comment by dabue** [comment]
@spacewander I have a few questions：
1.  we need a timer to start the handler for global events,  if move the core.timer.new, how to triger it?
2 . if  we add the  handler to  background timer, how to exit the timer created by the eariler version ?

I agreed with you that usage of core.timer.new  in plugins is  in conflict with the hot-reload characteristic， it should be moved.

**Comment by spacewander** [comment]
@dabue 
You can take a look at https://github.com/apache/apisix/pull/2596/files to see how we can achieve it.

**Comment by dabue** [comment]
@spacewander  LGTM,  that's cool !
