### ISSUE TITLE
test: check the plugin name for each plugin

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2579]
original comment: https://github.com/apache/apisix/pull/2576#issuecomment-719568210

**Comment by idbeta** [comment]
I scanned the plugins folder with python and found that `serverless.lua` looks like a plugin, but it is not defined `local plugin_name`

**Comment by moonming** [comment]
> I scanned the plugins folder with python and found that `serverless.lua` looks like a plugin, but it is not defined `local plugin_name`, and no name problem with other plugins.

We need add test cases in CI
