### ISSUE TITLE
apisix如何做灰度发布，使业务方不修改业务代码，可以快速完成灰度发布

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#2589]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
you can take a look at this doc: https://github.com/apache/apisix/blob/master/FAQ_CN.md#%E5%A6%82%E4%BD%95%E9%80%9A%E8%BF%87-apisix-%E6%94%AF%E6%8C%81%E7%81%B0%E5%BA%A6%E5%8F%91%E5%B8%83

there is another plugin `dynamic-upstream`, it may be useful for you:

https://github.com/api7/apisix-plugin-dynamic-upstream/blob/main/doc/zh-cn/plugins/dynamic-upstream.md

**Comment by Yangzcy423911** [comment]
谢谢您的回答，我们目前生产环境用的是1.5版本，应该如何与dynamic-upstream这个插件配合使用呢，这个插件的功能可以满足我们的需求

**Comment by membphis** [comment]
You need to use  APISIX `2.0` + dynamic-upstream. ^_^
