### ISSUE TITLE
request help: dynamic-upstream 插件如何与1.5版本的apisix融合及2.0版本融合，后期考虑将这个插件直接集成到apisix中吗

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#2603]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by idbeta** [comment]
It is best to be compatible with APISIX 1.5 and APISIX 2.0 at the same time.

**Comment by Firstsawyou** [comment]
Place the plugin in the `plugins/` directory of apisix and declare it in the plugin list section of the `config.yaml` or `config-default.yaml` file. Then the plug-in can take effect.
For me, you can change the title to English, which will be more perfect.

**Comment by Firstsawyou** [comment]
Regarding whether to add the plugin to apisix, we are still in further discussion.
