### ISSUE TITLE
request help: Is the custom plug-in written by nginx effective under apisix

### ISSUE THREAD

**Issue by lilihongjava** [apache/apisix#2611]
### Issue description
We're going to mix APISIX and nginx plug-ins.
Some complex functions are planned to be developed with nginx plug-in.
Simple functions are planned to be developed with APISIX plug-ins.
Because I found that apisix compiler is independent of  nginx .But  I saw readme is that "基于 Nginx 网络库和 etcd 实现".
If apisix only nginx network library is used, I doubt that my nginx plug-in won't work

Is the custom plug-in written by nginx effective under apix?

**Comment by spacewander** [comment]
You can expose Lua API from your Nginx plugins, so that your APISIX plugin can call them without reloading with Nginx configuration change.

**Comment by lilihongjava** [comment]
> You can expose Lua API from your Nginx plugins, so that your APISIX plugin can call them without reloading with Nginx configuration change.

So it can be mixed APISIX plugins and nginx plugins.
Well, I got it wrong that apisix only use nginx network library.

**Comment by spacewander** [comment]
Yes. APISIX can take the full advantage of Nginx's power.
