### ISSUE TITLE
bug: fail to fetch data from etcd

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2614]
APISIX version: `2.0`
etcd version: `3.4.3`

not enabled any auth for etcd instance.

error log:

```
config_etcd.lua:428: failed to fetch data from etcd: insufficient credentials code: 401, etcd key: /apisix/upstreams
```

but we can fetch data in this way:

```sh
etcdctl get --prefix apisix
```

**Comment by nic-chen** [comment]
please make sure auth enable successfully, if so , cli command should be：

```sh
$ etcdctl get --prefix /apisix --user root:5tHkHhYkjr6cQY
```


And make sure ETCD config for APISIX is correct,

**Comment by idbeta** [comment]
Check your APISIX configuration, whether the user and password of etcd is enabled.

**Comment by membphis** [comment]
the user is using Mac OS, so I think we can close this PR at first.

**Comment by membphis** [comment]
missing `make init` or `apisix init` step
