### ISSUE TITLE
request help: we need to support multi-nodes in upstream when pass_host ==  node

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2620]
### Issue description
In our current version, upstream can choose not to transparently transmit the host of the original request, 
but we also impose a restriction. When `pass_host == node`, upstream can only have one node.

We hope to get rid of this restriction. When upstream chooses not to transparently transmit the host (`pass_host == node`), each node transmits downwards according to its own host.

### Environment

* apisix version : 2.0
* OS:

**Comment by gxthrj** [comment]
the latest version of openresty (OpenResty 1.19.3.1 RC1) has support this feature: add the balancer.recreate_request function, which allows user to recreate request buffer in balancer phase. 
We can refer to this.

**Comment by spacewander** [comment]
So we only need to enable this feature for users who use OpenResty 1.19.3?

**Comment by gxthrj** [comment]
> So we only need to enable this feature for users who use OpenResty 1.19.3?

can we patch the old versions? 
Or make sure that the version of OpenResty that apisix depends on is adjusted to 1.19.3 in the future?

@membphis what do you think?

**Comment by gxthrj** [comment]
@spacewander @membphis Is there any progress on this?

**Comment by membphis** [comment]
> > So we only need to enable this feature for users who use OpenResty 1.19.3?
> 
> can we patch the old versions?
> Or make sure that the version of OpenResty that apisix depends on is adjusted to 1.19.3 in the future?
> 
> @membphis what do you think?

only support 1.19.3 is fine.

In the future, APISIX will mainly work with patched openresty to support mTLS and other new functions.
