### ISSUE TITLE
request help: do we still need `show-output` in bin/apisix

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#2624]
### Issue description
https://github.com/apache/apisix/blob/61cd91440bb8826d616e7a056428fe42ea64ebd0/bin/apisix#L573-L577

`show-output` seems used to debug init_etcd. And when implementing argparse for start apisix, it would be annoyed to deal with arguments from different sources like in #2101
https://github.com/apache/apisix/blob/2abb90efa7cc9a0bae98e688edf8fec13a7e57fd/bin/apisix

Could we remove `show-output`?

**Comment by spacewander** [comment]
I vote for removing and adding a new `--verbose` option after https://github.com/apache/apisix/pull/2101 is merged.

**Comment by Yiyiyimu** [comment]
> I vote for removing and adding a new `--verbose` option after #2101 is merged.

Sure I could take care this
