### ISSUE TITLE
apisix stand-alone mode

### ISSUE THREAD

**Issue by zlchanger** [apache/apisix#2635]
### Issue description
我突然看到config_center可以配置为yaml,请问哪有apisix.config的详细编写文档，我目前使用到的插件是jwt-auth

### Environment

* apisix version (cmd: `apisix version`): 1.2
* OS:

**Comment by tokers** [comment]
@zlchanger You can read the [config-default.yaml](https://github.com/apache/apisix/blob/master/conf/config-default.yaml), there are massive comments.

**Comment by zlchanger** [comment]
> @zlchanger You can read the [config-default.yaml](https://github.com/apache/apisix/blob/master/conf/config-default.yaml), there are massive comments. The yaml config example is here https://github.com/apache/apisix/blob/master/conf/apisix.yaml.

我想知道在apisix.yaml，jwt-auth这个插件怎么配置，比如，secret,key等值写在哪

**Comment by idbeta** [comment]
@zlchanger You can read https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/jwt-auth.md

**Comment by zlchanger** [comment]
> @zlchanger You can read https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/jwt-auth.md

OK

**Comment by idbeta** [comment]
@zlchanger Has the JWT issue you mentioned in this issue been resolved? Use the 2.0 version
