### ISSUE TITLE
feat(CLI): support to specify proxy timeout in config.yaml

### ISSUE THREAD

**Issue by ShiningRush** [apache/apisix#2637]
### Issue description
Default proxy timeout (read, send, connect etc.) is 60s, it is too long for some users.We should add this option for `config.yaml`, so they can config it in config file instead of modify `nginx_tpl.lua`.

**Comment by spacewander** [comment]
Now we set the timeout dynamically via https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#set_timeouts, see https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream
```
"timeout": {                # Set the timeout for connection, sending and receiving messages.
        "connect":15,
        "send":15,
        "read":15,
    },
```
