### ISSUE TITLE
request help: disable ssl_session_tickets by default

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#2638]
### Issue description

In a word, 'ssl_session_tickets' would make Perfect Forward Secrecy useless.

reference：
ingress-nginx：https://github.com/kubernetes/ingress-nginx/pull/6196
mozilla：https://github.com/mozilla/server-side-tls/issues/135

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
> Because proper rotation of session ticket encryption key is not implemented in nignx or Apache.

https://github.com/mozilla/server-side-tls/issues/135

Look like it would be better if we implement session ticket rotation? We need a modified version of [lua-ssl-nginx-module](https://github.com/openresty/lua-ssl-nginx-module) to get new ticket from etcd.

**Comment by Miss-you** [comment]
> > Because proper rotation of session ticket encryption key is not implemented in nignx or Apache.
> 
> [mozilla/server-side-tls#135](https://github.com/mozilla/server-side-tls/issues/135)
> 
> Look like it would be better if we implement session ticket rotation? We need a modified version of [lua-ssl-nginx-module](https://github.com/openresty/lua-ssl-nginx-module) to get new ticket from etcd.

Implementing session ticket rotation is a good idea, but not a high priority. I think we should first disable the 'ssl_session_tickets'. 

On the other hand, it might be better to use redis instead of etcd.

**Comment by membphis** [comment]
disable ssl_session_tickets by default
+1 ^_^
