### ISSUE TITLE
[DISCUSS] Only keep one Server header in HTTP response

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2640]
### Issue description

I found sometimes there are two `Server` headers in HTTP response:

![image](https://user-images.githubusercontent.com/10428333/98333741-620bd000-203c-11eb-9bda-fad906385153.png)

I think it's redundant, we only need `Server: APISIX/2.0`.

**Comment by Firstsawyou** [comment]
Agree, for me, it is better to keep only `Server: APISIX/2.0`.

**Comment by spacewander** [comment]
The adding header is only in the test scaffold.
https://github.com/apache/apisix/blob/3ab580fa7150736735c7dec67f6a3f4d2987b597/t/APISIX.pm#L392

@membphis 
Do you remember why you added it deliberately?

**Comment by membphis** [comment]
> Do you remember why you added it deliberately?

sorry I do not remember this :( if you think it is useless or wong, welcome to remove it.

> I found sometimes there are two `Server` headers in HTTP response:

I think the first one is generated by APISIX, and the second one is from the upstream server.

> I think it's redundant, we only need `Server: APISIX/2.0`.

agree, +1

**Comment by spacewander** [comment]
Solved.
