### ISSUE TITLE
request help: Use ngx.var.request_id as unique id for requests and response tracing, not jit-uuid.

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#2643]
### Issue description

Use `ngx.var.request_id` as unique id for req and resp tracing, not `jit-uuid`.

The distributed unique id generation algorithm is a classic problem. The current seed of jit-uuid is set by the lua code, while lua always use the same seed by default.

On the other hand, nginx/openresty has a default distributed id -- `ngx.var.request_id`. And after a year of experience, `ngx.var.request_id` itself has a very low collision rate (billions of requests per day) and has never had a request_id/trace_id collision on the same day.

I think it's better to use `ngx.var.request_id` rather than generate uuid by itself.

ref:
https://github.com/apache/skywalking/issues/5805

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
we mainly use `jit-uuid` when we need to generate Gateway ID in APISIX, it works in `init_lua` phase. 

I do not think we can use `ngx.var.request_id` in this phase.

**Comment by Miss-you** [comment]
> we mainly use `jit-uuid` when we need to generate Gateway ID in APISIX, it works in `init_lua` phase.
> 
> I do not think we can use `ngx.var.request_id` in this phase.

Why Apache APISIX need to generate a uuid in `init` stage? What problem needs to be solved?

If it is used for tracing, I think the lifecycle of a request will be in rewrite/access , etc. And `init` or `init_worker` phase don't need uuid.

**Comment by nic-chen** [comment]
> > we mainly use `jit-uuid` when we need to generate Gateway ID in APISIX, it works in `init_lua` phase.
> 
> > 
> 
> > I do not think we can use `ngx.var.request_id` in this phase.
> 
> 
> 
> Why Apache APISIX need to generate a uuid in `init` stage? What problem needs to be solved?
> 
> 
> 
> If it is used for tracing, I think the lifecycle of a request will be in rewrite/access , etc. And `init` or `init_worker` phase don't need uuid.

It's an ID for each APISIX instance, not for each request.

**Comment by Miss-you** [comment]
These are two different scenarios.
I think Apache APISIX itself should use jit-uuid to generate unique ID, but in the case of tracing requests and responses, it should use `ngx.var.request_id`.

> > > we mainly use `jit-uuid` when we need to generate Gateway ID in APISIX, it works in `init_lua` phase.
> > 
> > 
> > > 
> > 
> > 
> > > I do not think we can use `ngx.var.request_id` in this phase.
> > 
> > 
> > Why Apache APISIX need to generate a uuid in `init` stage? What problem needs to be solved?
> > If it is used for tracing, I think the lifecycle of a request will be in rewrite/access , etc. And `init` or `init_worker` phase don't need uuid.
> 
> It's an ID for each APISIX instance, not for each request.

**Comment by Miss-you** [comment]
we can simply use `api_ctx.var.request_id`

demo code:
```
ngx.log(ngx.ERR, "access request_id:"..tostring(api_ctx.var.request_id))
```

log:
``` 
2020/11/11 15:52:26 [error] 3915#4973481: *12690 [lua] init.lua:339: http_access_phase(): access request_id:191905e1e06f01b9f5c3e6c4f6ed94d2, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "localhost:9080"
```

![image](https://user-images.githubusercontent.com/3816205/98784615-59e5d300-2436-11eb-884e-5279c41b680a.png)

**Comment by membphis** [comment]
Which part of APISIX do you want to update?
