### ISSUE TITLE
bug: The download page link in the release page is invalid

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2647]
### Issue description
`download page` link to http://apisix.apache.org/downloads/  which is 404 now.

**Comment by membphis** [comment]
where did you get this link?

**Comment by idbeta** [comment]
> where did you get this link?

https://github.com/apache/apisix/releases/tag/2.0

**Comment by moonming** [comment]
will fix in https://github.com/apache/apisix-website/issues/81
