### ISSUE TITLE
doc: use username always, drop the `id` description

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2651]
![image](https://user-images.githubusercontent.com/6814606/98453978-1ff8a080-219a-11eb-8342-43a7dae5fdb1.png)

**Comment by juzhiyuan** [comment]
Not only this example, please check other examples in the Consumer part.

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/98454216-fd1bbb80-219c-11eb-85bd-53a213a97151.png)

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/98454434-571d8080-219f-11eb-888c-d21fb34df07b.png)

And this one.

**Comment by membphis** [comment]
> And this one.

I make a try right now, it works fine(it should throw an error, that is a bug)
I'll create a new issue about this bug.

**Comment by moonming** [comment]
I think we should remove id of consumer, only name is ok

**Comment by spacewander** [comment]
I think we can remove the '{username}' from URL, as the `username` is already given as body.

**Comment by juzhiyuan** [comment]
Agree!

**Comment by juzhiyuan** [comment]
Let it be more like a RESTful request
