### ISSUE TITLE
feat: there is no "createtime" when creating a consumer by adminAPI, which causes dashboard to display wrong "Update Time"

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2654]
### Issue description
There is no "createtime" when creating a consumer by adminAPI, which causes dashboard to display wrong "Update Time"

### Environment
* apisix version (cmd: `apisix version`):
* OS: apisix2.0 + dashboard 2.0

relate https://github.com/apache/apisix-dashboard/issues/718

**Comment by membphis** [comment]
there is the new field we need to support, please confirm they are Unix timestamp:

* create_time
* update_time

@nic-chen @ShiningRush

**Comment by nic-chen** [comment]
> there is the new field we need to support, please confirm they are Unix timestamp:
> 
> * create_time
> * update_time
> 
> @nic-chen @ShiningRush

yes, it is. and is in secode.

**Comment by spacewander** [comment]
We only have those fields:
https://github.com/apache/apisix/blob/a2fa3ff89d886020a317f7e7f024756296e9861d/t/admin/consumers.t#L328

What we need to do is adding them to the doc.
