### ISSUE TITLE
bug: the plug-in can't be reload if it's function changed only.

### ISSUE THREAD

**Issue by dabue** [apache/apisix#2655]
### Issue description
the plug-in can't be reload with the ' apisix/admin/plugins/reload' if it's function changed only.
because the code  https://github.com/apache/apisix/blob/master/apisix/plugin.lua#L111

### Environment

* apisix version (cmd: `apisix version`): the current master branch
* OS: centos 7

**Comment by membphis** [comment]
can you provide a mini step for this bug? then we can use it to reproduce this bug
