### ISSUE TITLE
bug: 用plugin-interceptors方法对/apisix/prometheus/metrics目录进行限制无效

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix#2658]
### Environment

* apisix version (cmd: `apisix version`):apisix 2.o
* OS:centos 7

用下面方法，对/apisix/prometheus/metrics 进行限制无效，烦请验证是否bug
https://github.com/apache/apisix/blob/master/doc/zh-cn/plugin-interceptors.md

**Comment by spacewander** [comment]
@tiger333777 
Please check the master branch. The interceptors didn't work for 2.0 (This version is not new enough).

**Comment by spacewander** [comment]
2.1 is released.  Feel free to reopen it if it could be reproduced in the master branch.

**Comment by ziyou434** [comment]
I found it still doesn't work in 2.1 version @spacewander

**Comment by spacewander** [comment]
You should provide an example to prove it is invalid. I tried myself, it works!
