### ISSUE TITLE
bug: There is some doubt about `xxx || true` in `apisix_cli_test.sh`

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#2660]
### Issue description

Is there a problem with the test case logic `xxx || true` here?

![image](https://user-images.githubusercontent.com/3816205/98472405-ea04fc00-222d-11eb-9818-6a89113ad009.png)

I printed a local printout of the count variable and the run result is not a number but a string, not as expected

The logic of this code is to expect the `grep` and `wc` commands to check if there is a corresponding configuration entry for `nginx.conf`.

![image](https://user-images.githubusercontent.com/3816205/98472409-ec675600-222d-11eb-8f55-610a9e853554.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by spacewander** [comment]
The first one you quote has `-c` after `grep`.
The second one misses the `-c` option.

**Comment by Miss-you** [comment]
> The first one you quote has `-c` after `grep`.
> The second one misses the `-c` option.

I got it. Thank u.
