### ISSUE TITLE
request help: plugin(hamc-auth) compatible with aliyun hmac-auth

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix#2661]
### Issue description
I think the hmac-auth plugin of apisix can be compatible with the hamc-auth of aliyun, Tencent cloud and other cloud manufacturers. In this way, some users who want to switch from the cloud manufacturer to apisix can directly replace it. My idea here is to modify the current hmac-auth or add a new plugin to support this function. I don't know whether the community has any plans for this function, if so I also intend to complete this function

**Comment by spacewander** [comment]
Can you show us the difference between ours and the hamc-auth of aliyun, Tencent cloud and other cloud manufacturers?
