### ISSUE TITLE
request help: Suggestions for storing dynamic rules in apifix

### ISSUE THREAD

**Issue by lilihongjava** [apache/apisix#2664]
### Issue description
Requirement: a request has an application ID and a developer ID. it is necessary to find out the private key(there is a management console that can be configured)  corresponding to the application and developer in a place to encrypt the request content. This data(private key) is dynamic and will change frequently. Now i need to select a key value library. At present, we plan to put redis or etcd. For redis,  it is a memory database, and it is also used for limit-req. The reason why etcd is put is that apifix comes with it. I understand that etcd has a watch mechanism, but I don't know whether apifix provides a function to get the latest data stored in etcd？ And whether in the apisix plugin  can get the latest data in real time in memory？
Or do you have any better suggestions for dynamic data storage? Thank you

**Comment by spacewander** [comment]
For how we get the latest data in etcd, you can take a look at https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua.

**Comment by lilihongjava** [comment]
Thank you for your prompt reply
Is there any reference example？

**Comment by spacewander** [comment]
How we use the `config_etcd` is the best example, which is workable and battle-tested.
