### ISSUE TITLE
chore: The maximum length of the name when creating a route is 100, but an error will still be prompted at the end

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2665]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX 2.0 + APISIX-dashboard 2.0

The maximum length of the name when creating a route is 100, but input a name of 100 length an error will still be prompted at the end.
![image](https://user-images.githubusercontent.com/7396835/98465619-19ebd980-2205-11eb-877b-84b5b930ef4d.png)

**Comment by gxthrj** [comment]
@spacewander @Firstsawyou do you have time to resolve，the max length of route name is 50 in APISIX by now, it seems to short. and we had better to  keep it the same as dashboard.

**Comment by membphis** [comment]
> It seems to fix the logic both in manager-api and APISIX,
> the name of route has max length 50 in APISIX

we should change the max length to  `100`, same as the dashboard.

**Comment by juzhiyuan** [comment]
Just wait, we should make a decision on this issue, what's the proper mac limit? If 100 is good to go, then we should update the backend. If 50 is enough, then let the frontend to update.

**Comment by membphis** [comment]
> If 100 is good to go, then we should update the backend.

I vote for this. `50` is small.
