### ISSUE TITLE
bug(proxy_mirror): The request header is not original in the request after mirror

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2668]
### Issue description

When using the `proxy_mirror` plugin, I first use the proxy_mirror plugin to mirror the source request, and then add the request header information to the source request. The expected mirroring request should be consistent with the source request, but the request header information in the mirrored request is changed.

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS:

Example:

This is my test case in `proxy_mirror.t` file：
1.Add 1986 port service, used to print mirroring request information in the log.

```
add_block_preprocessor(sub {
    my ($block) = @_;

    my $http_config = $block->http_config // <<_EOC_;

    server {
        listen 1986;
        server_tokens off;

        location / {
            content_by_lua_block {
                local core = require("apisix.core")

                core.log.info("upstream_http_version: ", ngx.req.http_version())

                local headers_tab = ngx.req.get_headers()
                local headers_key = {}
                for k in pairs(headers_tab) do
                    core.table.insert(headers_key, k)
                end
                core.table.sort(headers_key)

                for _, v in pairs(headers_key) do
                    core.log.info(v, ": ", headers_tab[v])
                end

                core.log.info("uri: ", ngx.var.uri)
                ngx.say("hello world")
            }
        }
    }
_EOC_

    $block->set_value("http_config", $http_config);
});
```

2.After mirroring the request, rewrite the request header through the `serverless-post-function` plugin(the priority of the `serverless-post-function` plugin is less than that of the `proxy-mirror` plugin).

```
=== TEST 1: Bind the `proxy-mirror` plugin, and modify the request header through the `serverless-post-function` plugin.
--- config
       location /t {
           access_by_lua_block {
               local t = require("lib.test_admin").test
               local code, body = t('/apisix/admin/routes/1',
                    ngx.HTTP_PUT,
                    [[{
                        "plugins": {
                            "proxy-mirror": {
                               "host": "http://127.0.0.1:1986"
                            },
                            "serverless-post-function": {
                                "phase": "rewrite",
                                "functions" : ["return function() 
                                                    ngx.req.set_header(\"api-key\",\"world\");
                                                    ngx.req.set_header(\"name\",\"james\");
                                                end"]
                            }
                        },
                        "upstream": {
                            "nodes": {
                                "127.0.0.1:1980": 1
                            },
                            "type": "roundrobin"
                        },
                        "uri": "/hello"
                   }]]
                   )

               if code >= 300 then
                   ngx.status = code
               end
               ngx.say(body)
           }          
        }
--- request
GET /t
--- error_code: 200
--- response_body
passed
--- no_error_log
[error]
```

3.Send a request to test the plugin, and view the request information after the mirroring request in the log.

```
=== TEST 2: api-key=hello changed to api-key=world, name=rose changed to name=james
--- 
--- request
GET /hello
--- error_code: 200
--- more_headers
api-key: hello
name: rose
--- response_body
hello world
--- error_log
api-key: hello
name: rose
```

4.The request header after `proxy_mirror` mirroring is not the source request header, but is rewritten by the `serverless-post-function` plugin.

<img width="547" alt="截屏2020-11-09 下午10 01 13" src="https://user-images.githubusercontent.com/52862365/98550902-a1a21880-22d7-11eb-8283-8b3c88a072f3.png">

The expected result is: `api-key: hello`, ` name: rose`

**Comment by spacewander** [comment]
Give a concrete example?

**Comment by Firstsawyou** [comment]
> Give a concrete example?

I will add later.

**Comment by spacewander** [comment]
It is because the headers of Nginx's subrequest is just a swallow copy of its parent request:
https://github.com/nginx/nginx/blob/a3b5ccd0566e618635303309dd8592aa4cfd7eaf/src/http/ngx_http_core_module.c#L2366

**Comment by spacewander** [comment]
We can adjust the header like this: https://github.com/openresty/lua-nginx-module/blob/7105adaa523adedec80f0aaa13388b88d08988f8/src/ngx_http_lua_subrequest.c#L1635

**Comment by membphis** [comment]
it seems we can not handle this case in APISIX(it depends on Nginx core)
