### ISSUE TITLE
request help: while etcd auth enable，apisix cannot get etcd settings after restart 

### ISSUE THREAD

**Issue by jxhecong** [apache/apisix#2670]
### Issue description
enable etcd auth, add right user and password in config.yaml, add a right routes, curl the service is OK
apisix restart, curl the service result 404
when remove user and password in config.yaml and disable etcd auth, the service is fine again

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: centos7.6

**Comment by spacewander** [comment]
Have you seen any error message after apisix restart?

**Comment by jxhecong** [comment]
just "signal process started" in error.log

**Comment by jxhecong** [comment]
someting strange:
etcd --user=***:*** get / --prefix
the command's just output /apisix/routes/1 which is configured
such as
"
/apisix/consumers/
init_dir
/apisix/global_rules/
init_dir
/apisix/node_status/
init_dir
/apisix/plugin_metadata/
init_dir
/apisix/plugins/
init_dir
/apisix/proto/
init_dir
..."
is not found

**Comment by jxhecong** [comment]
1. reproduce the failure.
1.1 etcd --user=: delete / --prefix
      etcd --user=: get / --prefix, to make sure nothing left
1.2 enable etcd auth, add right user and password in config.yaml, apisix start, add a right routes, curl the service is OK
      etcd --user=: get / --prefix, just output the /apisix/routes/ which is configured
1.3 apisix restart, curl the service result 404
      etcd --user=: get / --prefix, just output the /apisix/routes/ which is configured

2. to avoid the problem
2.1 disable etcd auth, apisix restart
      etcd get / --prefix, output all KVs that apisix configured
2.2 then enable etcd auth, it's OK to restart apisix

**Comment by nic-chen** [comment]
> someting strange:
> 
> etcd --user=***:*** get / --prefix
> 
> the command just output /apisix/routes/1 which is configured
> 
> such as
> 
> "
> 
> /apisix/consumers/
> 
> init_dir
> 
> /apisix/global_rules/
> 
> init_dir
> 
> /apisix/node_status/
> 
> init_dir
> 
> /apisix/plugin_metadata/
> 
> init_dir
> 
> /apisix/plugins/
> 
> init_dir
> 
> /apisix/proto/
> 
> init_dir
> 
> ..."
> 
> is not found

Thanks for feedback，that is why.
'init_etcd' doesn't support auth yet.

**Comment by jxhecong** [comment]
need to add a config option "token" in config.yaml for apisix.etcd, used by init_etcd to add "-H 'Authorization: ***'" in curl command

**Comment by jxhecong** [comment]
> need to add a config option "token" in config.yaml for apisix.etcd, used by init_etcd to add "-H 'Authorization: ***'" in curl command

etcd auth token change easy, it's not a good idea to set it in config.yaml.
this PR get token by request etcd server when apisix start
