### ISSUE TITLE
bug: click Settings` example-plugin` button, displays a 500 error.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2672]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
APISIX Dashboard 2.0
- What happened?
If possible, provide a way to reproduce the error.

When creating a route or consumer, click Settings` example-plugin` plug-in button, the interface displays a 500 error.
![image](https://user-images.githubusercontent.com/7396835/98340868-fed46a80-2048-11eb-9b82-fd8d32b5f1d2.png)

**Comment by spacewander** [comment]
Can we close it after https://github.com/apache/apisix/pull/2673?

**Comment by juzhiyuan** [comment]
Yep

**Comment by juzhiyuan** [comment]
We don't have a need to adjust this sample's schema.
