### ISSUE TITLE
request help: apisix can support verify client of ssl?

### ISSUE THREAD

**Issue by xyz2b** [apache/apisix#2674]
### Issue description
apisix can support verify client of ssl?
openresty is support verify client of ssl. The interface is as follows:
`ok, err = ssl.verify_client(ca_certs?, depth?)`

### Environment

* apisix version (cmd: `apisix version`): apisix 2.0
* OS:centos7.5

**Comment by membphis** [comment]
that is a new API in `1.19.3`, welcome PR to add this feature ^_^

**Comment by spacewander** [comment]
@xyz2b 
Before submitting any code, please show your design either in GitHub issue or mail list. We could not accept a nontrivial feature without discussion.

**Comment by spacewander** [comment]
Solved. See https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#ssl
Can be controlled via `client.ca` & `client.depth`.
