### ISSUE TITLE
compared with springcloud gateway ,the qps is lower

### ISSUE THREAD

**Issue by ShadowCharle** [apache/apisix#2683]
### Issue description
I built two services, a target service and a SpringCloud Gateway service.

I used WRK for stress tests on the same machine:

1. Invoke the target service directly using WRK
![test1](https://user-images.githubusercontent.com/58029929/98623569-0052ab00-2347-11eb-8b6e-7257ae21956f.png)
2. Configure the route of the target service in the SpringCloud Gateway service, and then use WRK to call the SpringCloud Gateway service
![test2](https://user-images.githubusercontent.com/58029929/98623608-13657b00-2347-11eb-9bb6-d80368e1863f.png)

3. Create the route of the target service in ApISIX, and then call ApISIX by WRK

![test3](https://user-images.githubusercontent.com/58029929/98623622-19f3f280-2347-11eb-8c07-88495a801ea7.png)

You can clearly see that the QPS of spring cloud gateway is higher than that of apifix! When I tested with the top command, I found that the CPU utilization rate of spring cloud gateway was higher than that of apifix. Is this the reason? Is there any way to increase the throughput of apifix?
### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos7.3

**Comment by tokers** [comment]
@ShadowCharle You have some non-2xx or 3xx requests in the benchmark test for SpringCloud gateway, have you ever investigated it?

**Comment by ShadowCharle** [comment]
yes,But that's rarely the case，I don't think that's the core issue

**Comment by idbeta** [comment]
I think you should Increase the stress so the CPU utilization rate of servers of the two APIgateways are full and then compare their QPS.
Have you modified the system settings? Like `ulimit -n`

**Comment by tokers** [comment]
@ShadowCharle What about the number of Nginx workers for APISIX and Java threads for SpringCloud?

**Comment by ShadowCharle** [comment]
i modified the system settings. ulimit -n=65535 and fs.file-max=3248559

**Comment by ShadowCharle** [comment]
cpu core:6      
SpringCloud is a Java service, and I haven't changed any configuration;

**Comment by tokers** [comment]
> cpu core:6
> SpringCloud is a Java service, and I haven't changed any configuration;

Then i think maybe the benchmark is unfair, we don't know the real OS threads there involves the computation.
