### ISSUE TITLE
bug: dashboard2.0 create route with key-auth plugin, there is a useless setting

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2686]
- Why do you submit this issue?
- [ ] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

![image](https://user-images.githubusercontent.com/7396835/98629039-f767d680-2352-11eb-98e3-307a2eb30936.png)

**Comment by Jaycean** [comment]
Please assigne to me. I will fix it. Tks.

**Comment by spacewander** [comment]
I already did it.
