### ISSUE TITLE
bug: CI is not stable

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#2688]
### Issue description

![image](https://user-images.githubusercontent.com/2106987/98641874-6bac7500-2367-11eb-93dd-27164e95aeb7.png)

In this [PR](https://github.com/apache/apisix/pull/2684),  I only update the markdown files, but the CI failed.

### Environment

* apisix version (cmd: `apisix version`): master branch

**Comment by spacewander** [comment]
https://samples.auth0.com/.well-known/openid-configuration
Can't be accessed sometimes.

**Comment by juzhiyuan** [comment]
Alright, let's keep this issue open and I will add a proper label for it.
