### ISSUE TITLE
request help: got malformed version message: "" from etcd

### ISSUE THREAD

**Issue by yankunsam** [apache/apisix#2692]
### Issue description
I install apisix in gateway namespace,not default. Should I add etcd or dns_resolver in config.yaml?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by tokers** [comment]
@yankunsam What's the etcd configuration in your config.yaml?

**Comment by yankunsam** [comment]
like this: 
etcd:
  host:
    - "http://etcd-cluster-client.gateway.svc.cluster.local:2379"

**Comment by Firstsawyou** [comment]
1. First check whether the etcd configuration in your `config.yaml` file is correct.
2. Check whether your etcd service can be used normally.
3. You can try to restart etcd service.

**Comment by nic-chen** [comment]
yes，need to add dns_resolver in config.yaml

**Comment by ziyou434** [comment]
> yes，need to add dns_resolver in config.yaml
 I want to instruct dns_reslover what kind of role does it play in the interaction between apisix and etcd, and why it is set up, please tell me

**Comment by membphis** [comment]
what is the apisix version?

**Comment by freebsdly** [comment]
when apisix starting , it use curl to check etcd version, maybe etcd server should enable api v2.

**Comment by freebsdly** [comment]
when apisix starting, it use curl to check etcd version, curl -s -m [timeout] http://ip:port/version , make sure the domain name can be resolved

**Comment by spacewander** [comment]
Consider solved
