### ISSUE TITLE
[DISCUSS] Should we add metric for log sender and zipkin ?

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2693]
### Issue description
Now  the log sender batch store the data in memory , we can not know how many logs or spans is send, so I think we can add some metric to monitor it. 

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by gy09535** [comment]
I do it in my private repository should apisix need it?

**Comment by spacewander** [comment]
Could you provide a design about it?

**Comment by spacewander** [comment]
I think we need to allow plugin to register their metrics. Like a `_M.collect` method and prometheus will call them when in need.

**Comment by gy09535** [comment]
> Could you provide a design about it?

When  prometheus exporter init , I add a gauge to metric with label : node，route_id, type。And I export two module function inc and set to change the gauge value. In "syslog plugin" log method  I  use this module method  inc it value, and  in batch process I reduce it value. And zipkin is also do that.

**Comment by gy09535** [comment]
> I think we need to allow plugin to register their metrics. Like a `_M.collect` method and prometheus will call them when in need.

We can add plugin init method  to register their own metric

**Comment by spacewander** [comment]
> We can add plugin init method to register their own metric,And provide api to change it value.

@gy09535 
Pull request is welcome!

**Comment by gy09535** [comment]
haha , I will do it.

**Comment by gy09535** [comment]
> > We can add plugin init method to register their own metric,And provide api to change it value.
> 
> @gy09535
> Pull request is welcome!

haha, I wil do it.

**Comment by gy09535** [comment]
> > We can add plugin init method to register their own metric,And provide api to change it value.
> 
> @gy09535
> Pull request is welcome!

Please assign to me.
