### ISSUE TITLE
chore: code format optimization of `t/lib/server.lua` file 

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2697]
### Issue description

In the `t/lib/server.lua` file, there is only one blank line between most `functions`, and we need two blank lines. 

<img width="559" alt="截屏2020-11-11 上午12 28 10" src="https://user-images.githubusercontent.com/52862365/98702016-df28a380-23b4-11eb-9622-8d1c519cda3d.png">

Example：

```
function  _M.XXX()
   XXX
end


function  _M.YYY()
  YYY
end
```

**Comment by tokers** [comment]
That's good to treat the test codes equally without discrimination. I think it can be checked by the lint tool too.
