### ISSUE TITLE
request help: plugins in global rules are prioritized over those in routes, regardless of priority

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#2711]
### Issue description
Plugins in global rules are prioritized over those in routes, regardless of priority.

Our use case: prometheus configured in global rules & a custom plugin that is configured per route. The custom plugin sets a variable in context during log phase: `ctx.custom_variable = value`, and we'd like to get that variable in metrics, by modifying exporter.lua. However since global rules are always ran first we can't achieve that.

One workaround I can think of is to move  the `ctx.custom_variable = value` to an earlier phase. But since that part of the logic is dedicated for logging & monitoring, I don't think that's the best practice. It's more intuitive if the global rules respect plugin priorities.

### Environment

* apisix version (cmd: `apisix version`): APISIX 2.0
* OS: mac/linux

**Comment by spacewander** [comment]
We can allow user to postpone the global rule, so that we can achieve this without breaking current behavior. For example:

```
global rule -> lcoal rule -> postponed global rule
```

**Comment by Gary-Airwallex** [comment]
TBH that still sounds counter intuitive to me. How about merging plugins from global rules with plugins from routes/services? We could mark global-rule plugins (e.g. with a prefix), so that a plugin is still ran twice if it's applied in both global_rule and route.

Also it'd be great if there are more documentations for the behavior of global rules: https://github.com/apache/apisix/blob/master/doc/architecture-design.md#Global-Rule and https://github.com/apache/apisix/blob/master/doc/admin-api.md

**Comment by spacewander** [comment]
@Gary-Airwallex 
Pull request is welcome!

**Comment by spacewander** [comment]
@Gary-Airwallex 
I have changed my mind and open a discussion there: https://lists.apache.org/thread.html/r99e93b5bbade9e34a18e87b674bd999fdbe875a505c46664b731d9ff%40%3Cdev.apisix.apache.org%3E
Let's go to the mail list.

**Comment by vicaya** [comment]
@spacewander, a global rule that can be postponed (postpone=true) sounds good! Is postponed global rule in the roadmap? It could really simplify some gnarly config.

**Comment by sampy2518** [comment]
I have a peculiar situation in my project where I am trying to replace my existing old Proxy code with APISIX. my current proxy backtrack the versions apis and services in a different way. for example. 
API Versions available : V1, V2, V3

Routes should be created in below format 
V1
	API1 
		Service1
		Service2 
	API2
		Service3
		Service4
	API3
		Service5

V2
	API2
		Service4
	API4 
		Service6
V3
	API2
		Service4
	API5 
		Service7

API routing, fallback and backtracking rules to follow 
case 1:  	
APP A : current Version used V2. All any API from the frontend will be called with V2

Invoke V2/API1/Service1/ will be redirected to V1/API1/Service1, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service1 in API1.

Invoke V2/API1/Service2/ will be redirected to V1/API1/Service2, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service2 in API1.

Invoke V2/API2/Service3/ will be redirected to V1/API2/Service3, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service3 in API2.

Invoke V2/API2/Service4/ will be redirected to V2/API2/Service4, As it is present in V2
 
Invoke V2/API3/Service5/ will be redirected to V1/API3/Service5, As it is not present in current version V2, so it will backtrack or fallback to previous version which is V1 and search for the Service5 in API3.

Invoke V2/API4/Service6/  will be redirected to V2/API4/Service6, As it is present in V2

case 2:  	
APP b : current Version used V3. All any API from the frontend will be called with V3

Invoke V3/API1/Service1/ will be redirected to V1/API1/Service1, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service1 in API1.

Invoke V3/API1/Service2/ will be redirected to V1/API1/Service2, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service2 in API1.

Invoke V3/API2/Service3/ will be redirected to V1/API2/Service3, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service3 in API2.

Invoke V3/API2/Service4/ will be redirected to V3/API2/Service4, As it is present in V3
 
Invoke V3/API3/Service5/ will be redirected to V1/API3/Service5, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V1 and search for the Service5 in API3.

Invoke V3/API4/Service6/ will be redirected to V2/API4/Service6, As it is not present in current version V3, so it will backtrack or fallback to previous version which is V2 and search for the Service6 in API4.

Invoke V3/API4/Service7/ will be redirected to V3/API5/Service7, As it is present in V3

I would like to ask how can i define a customer global plugin which is work when for any incoming request from client and rewrite the URL as per above rule.

**Comment by darkSheep404** [comment]
> We can allow user to postpone the global rule, so that we can achieve this without breaking current behavior. For example:
> 
> ```
> global rule -> lcoal rule -> postponed global rule
> ```

may i know this feature are available now ?
