### ISSUE TITLE
request help: How to turn off access log?

### ISSUE THREAD

**Issue by fregie** [apache/apisix#2713]
### Issue description
My apisix run in docker and It's may be dangerous if access.log keep logging.
I want to turn off the access log.

**Comment by idbeta** [comment]
I think turn the access log off is not a good idea.

**Comment by fregie** [comment]
I have written a plugin to upload access log to my log service,so I don't need nginx save a access.log in container.
I think it's ncecssary providing a switch of access log.

**Comment by spacewander** [comment]
@fregie 
Pull request is welcome!
