### ISSUE TITLE
bug: When accessing APISIX route, there are two servers in the response header.

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#2714]
### Issue description
When accessing APISIX route, there are two `Server` in the response header, one of which is upstream, can they used different key names?

```shell
$ curl  http://127.0.0.1:9080/test_core -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.0
Server: BaseHTTP/0.3 Python/2.7.13
Date: Thu, 12 Nov 2020 04:31:03 GMT

tested by python
```

### Environment

* apisix version (cmd: `apisix version`): master
* OS:

**Comment by spacewander** [comment]
We can remove the upstream one.

**Comment by Miss-you** [comment]
I think it's better to just leave `Server: APISIX/2.0` and override the other `server` header field!

demo：
```

$ curl  http://127.0.0.1:9080/test_core -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.0
Date: Thu, 12 Nov 2020 04:31:03 GMT

tested by python
```

**Comment by Miss-you** [comment]
here is the bug.

![image](https://user-images.githubusercontent.com/3816205/98934142-9986ea80-251c-11eb-994a-7f48654c66b2.png)

ref:
https://github.com/apache/apisix/blob/master/apisix/init.lua#L341
