### ISSUE TITLE
bug: apisix error logs

### ISSUE THREAD

**Issue by yankunsam** [apache/apisix#2716]
### Issue description

![image](https://user-images.githubusercontent.com/16130147/98901652-20bd6980-24ef-11eb-9e1f-0668e6728a36.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by ziyou434** [comment]
It seems that this problem has bothered many people，maybe you can see #2695 ，let‘s discuss together.

**Comment by krufyliu** [comment]
@yankunsam what's your etcd address? i meet the same problem.

if your etcd address has special character such as '-',  the problem occurs.

**Comment by spacewander** [comment]
Should be solved by https://github.com/api7/lua-resty-etcd/pull/92/files
