### ISSUE TITLE
request help: how do I get etcd data in a custom plugin

### ISSUE THREAD

**Issue by GBXing** [apache/apisix#2717]
### Issue description
I save some configuration data to the ETCD, hoping to load the configuration data into local memory when I start Apisix, and then get the configuration data when I develop my custom plugin by requiring ("apisix.xxx").get(). Is there an easy way to do this?
The way I've been able to do this so far is to add code to the http_init_worker() method of init.lua to load my configuration data when Apisix starts, but it may not be a good idea to change the source code

### Environment

* apisix version (cmd: `apisix version`): 1.5

**Comment by spacewander** [comment]
You can take a look at plugin-metadata API: https://github.com/apache/apisix/blob/master/doc/admin-api.md#plugin-metadata and its relative code.

**Comment by GBXing** [comment]
> You can take a look at plugin-metadata API: https://github.com/apache/apisix/blob/master/doc/admin-api.md#plugin-metadata and its relative code.

Sorry, I mean that I want to load configuration data from ETCD to local memory when Apisix is started, and then go to local memory to get data in custom plugin. Is there any way to do this without changing the source code

**Comment by GBXing** [comment]
@spacewander 
Now I refer to the code of the Consumer module and add a custom init_worker() method in the http_init_worker() of init.lua to load etCD data into local memory. Is there an easier way

**Comment by spacewander** [comment]
My original suggestion is that you can write your version of plugin_metadata. But your current way is fine too.
