### ISSUE TITLE
[DISCUSS] The error message "got malformed version message from etcd" is ambiguous

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2718]
When the etcd initialization fails, the output error message:

```
got malformed version message: "" from etcd
```

Which is ambiguous, i think the error details should be exposed. What do you think?

**Comment by Firstsawyou** [comment]
I agree with you. I have also encountered such a situation, this prompt message is not clear.

**Comment by nic-chen** [comment]
agree +1

**Comment by membphis** [comment]
agree +1

BTW, how can we get this error message? is it a bug?

**Comment by tokers** [comment]
> agree +1
> 
> BTW, how can we get this error message? is it a bug?

It's note a bug but a not so friendly hint when we cannot get the etcd version when the etcd cluster is abnormal, like cluster without leader and we are timed out, or even the cluster is totally offline.

**Comment by tokers** [comment]
@starsz Would you like to optimize this? Thanks!

**Comment by starsz** [comment]
> @starsz Would you like to optimize this? Thanks!

No problem. My pleasure!
