### ISSUE TITLE
request help: Apache APISIX support gzip

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#2720]
### Issue description
Gzip is a file format used for file compression and decompression. It is based on the Deflate algorithm that allows files to be made smaller in size which allows for faster network transfers. Gzip is commonly supported by web servers and modern browsers, meaning that servers can automatically compress files with Gzip before sending them, and browsers can uncompress files upon receiving them.

1. gzip is turned off by default

2. recommended nginx.conf demo: (if gzip is turned on)

```
    gzip on;
    gzip_min_length 1K;
    gzip_buffers 32 4K;
    gzip_http_version 1.0;
    gzip_comp_level 1;
    gzip_types application/atom+xml application/javascript application/x-javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/javascript text/plain text/x-component;
    gzip_vary on;

```

ref:
nginx-ingress: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/configmap.md

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by nic-chen** [comment]
nice

**Comment by membphis** [comment]
`gzip` should be off by default.

**Comment by jxhecong** [comment]
How to turn on gzip in apisix ?

**Comment by jxhecong** [comment]
I found that brotli is not work when i already compiled with google/ngx_brotli in openresty, and 'proxy_set_header Accept-Encoding ""' was setted by proxy-rewrite. The content was not encoded in gzip either.

**Comment by tzssangglass** [comment]
> I found that brotli is not work when i already compiled with google/ngx_brotli in openresty, and 'proxy_set_header Accept-Encoding ""' was setted by proxy-rewrite. The content was not encoded in gzip either.

supported, please try this compile script https://github.com/api7/apisix-build-tools/blob/792a61f3de2e23b124c92f34c975d1e6ce753498/build-apisix-openresty.sh#L80 to compile the `http_gzip_static_module` .

**Comment by jxhecong** [comment]
> > I found that brotli is not work when i already compiled with google/ngx_brotli in openresty, and 'proxy_set_header Accept-Encoding ""' was setted by proxy-rewrite. The content was not encoded in gzip either.
> 
> supported, please try this compile script https://github.com/api7/apisix-build-tools/blob/792a61f3de2e23b124c92f34c975d1e6ce753498/build-apisix-openresty.sh#L80 to compile the `http_gzip_static_module` .

I have already complied with --with-http_gzip_static_module, and '/usr/local/openresty/bin/openresty -V' can show it.

**Comment by tzssangglass** [comment]
here I give a minimalist configuration for apisix to start gzip.

step 1: turn on gzip, add configuration in `config.yaml`

```yaml
nginx_config:
  http_server_configuration_snippet: |
    gzip on;
``` 

step 2: request with gzip header


```shell
curl -H "Accept-Encoding: gzip" 127.0.0.1:9080/index.html -I 
```

step 3:

the response header is

```
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Date: Mon, 07 Jun 2021 06:12:56 GMT
Last-Modified: Wed, 02 Jun 2021 00:04:09 GMT
ETag: W/"60b6caf9-449"
Server: APISIX/2.6
Content-Encoding: gzip
```

**Comment by jxhecong** [comment]
Have you setted 'proxy_set_header Accept-Encoding ""' in apisix by proxy-rewrite plugin？To be sure content is not compressed in RS.

**Comment by tzssangglass** [comment]
> Have you setted 'proxy_set_header Accept-Encoding ""' in apisix by proxy-rewrite plugin？To be sure content is not compressed in RS.

no, isn't your problem to turn on gzip?

**Comment by jxhecong** [comment]
> > Have you setted 'proxy_set_header Accept-Encoding ""' in apisix by proxy-rewrite plugin？To be sure content is not compressed in RS.
> 
> no, isn't your problem to turn on gzip?

I have setted 'gzip on;' or 'brotli on;' in bin/apisix.  The problem is that when '{"plugins":{"proxy-rewrite":{"headers":{"Accept-Encoding":""}}}}' is configured, content will not be compressed by apisix.

**Comment by tokers** [comment]
> > > Have you setted 'proxy_set_header Accept-Encoding ""' in apisix by proxy-rewrite plugin？To be sure content is not compressed in RS.
> > 
> > 
> > no, isn't your problem to turn on gzip?
> 
> I have setted 'gzip on;' or 'brotli on;' in bin/apisix. The problem is that when '{"plugins":{"proxy-rewrite":{"headers":{"Accept-Encoding":""}}}}' is configured, content will not be compressed by apisix.

It seems that this plugin also change the request headers, not only for upstream.

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/4640
