### ISSUE TITLE
request help:  How to scale horizontally APISIX in Kubernetes sharing the same etcd database?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#2730]
original comment: https://github.com/apache/apisix/issues/2644#issuecomment-725587524

> Thank's for all the help that you gave me. I have another question to ask you, how is the best way to scale horizontally APISIX in Kubernetes sharing the same etcd database? Should I replicate etcd too?

**Comment by gxthrj** [comment]
In the production environment, it is recommended to deploy etcd in clusters. 

We can scale horizontally apisix according to the traffic level of the data plane. Etcd does not need to be expanded. Etcd belongs to the control plane and is not affected by the traffic on the data plane.

**Comment by juzhiyuan** [comment]
cc @NicolasBachs
