### ISSUE TITLE
Proposal: Support enable/disable route

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix#2737]
### Issue description

We could add enable/disable status to route so that it would support online / offline feature.

refer to:  https://github.com/apache/apisix-dashboard/issues/611#issuecomment-722256486

**Comment by membphis** [comment]
do we need to add a new field to `route` for this feature? @liuxiran

**Comment by liuxiran** [comment]
> do we need to add a new field to `route` for this feature? @liuxiran

We need a field to mark the status of the route:

- add a new field, that would be the most straightforward way

- add a specific property to the `labels`, that would be  a kind of extensibility way

We think both ways are okay, which one would you prefer @membphis ?

**Comment by moonming** [comment]
add a new field is good for me

**Comment by juzhiyuan** [comment]
I would prefer using standalone field, for labels are used to add description for target.

**Comment by liuxiran** [comment]
Ok, then we'll do this by adding a new field :) 

Since we are not much familiar with the logic of the route, we will try to sort out the existing logic and list the solution

**Comment by membphis** [comment]
> add a new field is good for me

+1

**Comment by liuxiran** [comment]
I have a question: how does apisix watch the changes of etcd and update the nginx config?  

my current implementation idea is that 

1. add a field `status` in route`s schema, like  https://github.com/apache/apisix/blob/d7593a0ac3f960ab23d5a71d98cf1666e21b207c/apisix/schema_def.lua#L621

1. write the route to etcd after it is created, and remove it from the nginx configuration when it is discovered that the status of the route is 0 (offline).

as for the second step I didn't find the relevant code , so do we have any reference codes or documentations?

Thanks and looking forward to your reply😊

cc @membphis @moonming @spacewander

**Comment by membphis** [comment]
I write an example, follow @liuxiran design: add new field `status`. I think this way is good.

```
{
    "uri": "/hello",    # uri
    "status": 0,        # integer value: 1 - online(default value), 0 - offline
    ... ...
}
```

**Comment by juzhiyuan** [comment]
If this is ok, kindly remove the `discuss` label and add `enhancement`.

**Comment by juzhiyuan** [comment]
> as for the second step I didn't find the relevant code , so do we have any reference codes or documentations?

Just to make sure, @membphis please take a look at here.

**Comment by liuxiran** [comment]
> > as for the second step I didn't find the relevant code , so do we have any reference codes or documentations?
> 
> Just to make sure, @membphis please take a look at here.

Yes, indeed, I haven't found the clue yet, how to let the route with `status=0` not take effect, I have not found reference codes

**Comment by membphis** [comment]
> Yes, indeed, I haven't found the clue yet, how to let the route with `status=0` not take effect, I have not found reference codes

welcome PR for this new feature. the APISIX does not support this feature now.

Does anyone want to handle this problem?

**Comment by liuxiran** [comment]
> > Yes, indeed, I haven't found the clue yet, how to let the route with `status=0` not take effect, I have not found reference codes
> 
> welcome PR for this new feature. the APISIX does not support this feature now.
> 
> Does anyone want to handle this problem?

OK，thanks a lot, then my teammate will try to handle it later.

**Comment by tzssangglass** [comment]
to let the route with status=0 not take effect, can only remove this route from the radetree？

**Comment by moonming** [comment]
ping @membphis

**Comment by membphis** [comment]
> to let the route with `status=0` not take effect, can only remove this route from the `radixtree`？

@tzssangglass @moonming 

for router `radixtree_uri`, we can add a new process here: 
https://github.com/apache/apisix/blob/master/apisix/http/router/radixtree_uri.lua#L42

```lua
    for _, route in ipairs(routes) do
        if type(route) == "table" then
            if route.status and route.status ~= 1 then   -- check the status
                goto CONTINUE
            end

            ... ...
            ::CONTINUE::
        end
    end
```

and we need to update the router `adixtree_host_uri` too, use the same way.

**Comment by tzssangglass** [comment]
get, let me study it.
