### ISSUE TITLE
doc(FAQ): "It is unreasonable to only enable passive checking" 

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2748]
original comment: https://github.com/apache/apisix/issues/2746#issuecomment-727175022

both need Chinese and English.

**Comment by tzssangglass** [comment]
assigned it to me

**Comment by tzssangglass** [comment]
need to explain how healthcheck works to complete this FAQ?

**Comment by membphis** [comment]
you can take a look at here:

original comment: #2746 (comment)

> need to explain how healthcheck works to complete this FAQ?

we do not need this job.

**Comment by tzssangglass** [comment]
get it

**Comment by spacewander** [comment]
Already done.
