### ISSUE TITLE
There are HTTP jump to HTTPS in API IX 2.0 back-end server code. How to configure it?

### ISSUE THREAD

**Issue by tiger333777** [apache/apisix#2755]
### Issue description
There are HTTP jump to HTTPS in API IX 2.0 back-end server code. How to configure it? When dasboard version 1.5, you can configure the back-end HTTPS back to the source. Now use 443 to return to the source back end, and it will always jump 301
### Environment

* apisix version (cmd: `apisix version`):  apisix 2.0 + dashboard 2.0 rc3
* OS: centos 7.6

**Comment by membphis** [comment]
@tiger333777 please use English in public channel
