### ISSUE TITLE
how to use vars in  routes?

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#2763]
### Issue description

**1. I add a new route:**
{
   "methods": [
        "POST"
    ],
    "uris": [
        "/test"
    ],
    "vars": [["arg_age","==","20"] ],
    "upstream": {
       
        "nodes": {
            "10.3.155.39:8080": 1
        },
        "type": "roundrobin"
    }
}

2. curl -i http://127.0.0.1:9080/api/index -X POST -d '{age:"20", arg_age:"20"}'

3. {"error_msg":"404 Route Not Found"}

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS:centos7.3

**Comment by spacewander** [comment]
The `arg_age` variable is for the query parameter in the URI (`?age=xxx`). 
http://nginx.org/en/docs/http/ngx_http_core_module.html#variables

To route according to the sent JSON body you should write your filter function: 
https://github.com/api7/lua-resty-radixtree/#new
