### ISSUE TITLE
request help: when upstream_type is chash, set_more_tries() make no sense.

### ISSUE THREAD

**Issue by zfs123** [apache/apisix#2770]
### Issue description
when upstream_type is chash, if last picked server does not work, apisix won't pick next server because of the unchanged chash_key, which make the function set_more_tries() to be meaningless.
is there any problem with this? how about using picker:next(last_id) to choose next server?

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: CentOS 7.4

**Comment by spacewander** [comment]
PR: #2676
