### ISSUE TITLE
request help: alwayls failed to fetch data from etcd

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#2775]
### Issue description

Etcd is installed on the physical machine. apisix is started in the docker. apisix start successfully and invoke apisix api to add data also successfully. However, after a while, there will be unlimited errors. Why is this?

![image](https://user-images.githubusercontent.com/10362371/99392895-6f1b9f80-2917-11eb-9cf6-08bd7a9457a0.png)

### Environment

* apisix version (cmd: `apisix version`): apache/apisix:2.0-centos
* OS: Centos
* etcd version: 3.4.3

**Comment by spacewander** [comment]
Should be solved by https://github.com/apache/apisix/pull/2687
