### ISSUE TITLE
request help: How to close X-Forwarded* and X-Real-IP in requests

### ISSUE THREAD

**Issue by Applenice** [apache/apisix#2777]
### Issue description
I don't want X-Forwarded* and X-Real-IP to appear in APISIX proxy rewrite requests, how do I configure it? I found no relevant information.

Is there a way to add, but not a way to close? I tried to configure proxy protocol in config.yaml, but it didn't work.
https://github.com/apache/apisix/pull/1113

### Environment

* apisix version (cmd: `apisix version`):
```
$ git branch -v
* master c1ac7d6 docs: add a English link of node-status.md (#2753)
```

**Comment by tokers** [comment]
@Applenice See https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md for details. Just some snippet reference:

>
> headers | object | optional |   |   | Forward to the new headers of the upstream, can set up multiple. If it exists, will rewrite the header, otherwise will add the header. You can set the corresponding value to an empty string to remove a header.
> -- | -- | -- | -- | -- | --

**Comment by tokers** [comment]
> @Applenice See https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md for details. Just some snippets reference:
> 
> > headers
> > object
> > optional
> >  
> >  
> > Forward to the new headers of the upstream, can set up multiple. If it exists, will rewrite the header, otherwise will add the header. You can set the corresponding value to an empty string to remove a header.

Sorry, these headers are set explicitly in the nginx.conf template, which always passed to upstream.

**Comment by tokers** [comment]
@Applenice Could you introduce your demands why these headers shouldn't be passed?

**Comment by tokers** [comment]
We may need to add some notes in document of plugin proxy-rewrite to state that several headers can not be overridden/deleted by proxy-rewrite plugin.

**Comment by starsz** [comment]
Hi, I think there is a temporary solution.

If your apisix version is earlier than or equal to 2.0, you can change your `/bin/apisix`, comment the line like this
```
#proxy_set_header   X-Forwarded-For      $var_x_forwarded_for;
#proxy_set_header   X-Forwarded-Proto    $var_x_forwarded_proto;
#proxy_set_header   X-Forwarded-Host     $var_x_forwarded_host;
#proxy_set_header   X-Forwarded-Port     $var_x_forwarded_port;
#proxy_set_header   X-Real-IP         $remote_addr;
```
and reload the apisix.

If your apisix is on the master branch, you should do the same things as above on `apisix/cli/ngx_tpl.lua`

**Comment by Applenice** [comment]
> @Applenice Could you introduce your demands why these headers shouldn't be passed?

I think it should be configurable, and not all upstream need or care about this information.

**Comment by Applenice** [comment]
> Hi, I think there is a temporary solution.
> 
> If your apisix version is earlier than or equal to 2.0, you can change your `/bin/apisix`, comment the line like this
> 
> ```
> #proxy_set_header   X-Forwarded-For      $var_x_forwarded_for;
> #proxy_set_header   X-Forwarded-Proto    $var_x_forwarded_proto;
> #proxy_set_header   X-Forwarded-Host     $var_x_forwarded_host;
> #proxy_set_header   X-Forwarded-Port     $var_x_forwarded_port;
> #proxy_set_header   X-Real-IP         $remote_addr;
> ```
> 
> and reload the apisix.
> 
> If your apisix is on the master branch, you should do the same things as above on `apisix/cli/ngx_tpl.lua`

Thank you for your response, I have tested this method as a temporary solution.
