### ISSUE TITLE
DISCUSS(kafka-logger):  the key field should be optional

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2778]
### Issue description

In the schema of the kafka-logger plugin, the key field is mandatory, as shown below:

```
......
    properties = {
        ......
        key = {type = "string"},
        ......
    },
    required = {"broker_list", "kafka_topic", "key"}
......
```

I think the key field should be optional, because when a message is sent to the Kafka service, the key can be specified or empty. So when the key is empty, it can be used normally.

The key should be optional in the schema：

```
......
    properties = {
        ......
        key = {type = "string"},
        ......
    },
    required = {"broker_list", "kafka_topic"}
......
```

**Comment by moonming** [comment]
please send discuss thread to mailinglist
