### ISSUE TITLE
plugin(prometheus): incorrect http status name

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2782]
![image](https://user-images.githubusercontent.com/6814606/99500783-ca03d400-29b5-11eb-8545-f541a9b9b7f8.png)

**Comment by membphis** [comment]
@idbeta do you have time to confirm if this is a bug, many thx

**Comment by idbeta** [comment]
> @idbeta do you have time to confirm if this is a bug, many thx

ok, I will check it when I am free.

**Comment by idbeta** [comment]
@membphis I reproduced this problem in the local environment.
Grafana v7.3.3 (2489dc4d3a)
prometheus-2.22.2.darwin

**Comment by membphis** [comment]
@idbeta many thx for your confirmation. We need to update the JSON file of grafana: https://github.com/apache/apisix/blob/master/doc/json/apisix-grafana-dashboard.json

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/3402?

**Comment by Yiyiyimu** [comment]
Solved confirmed
