### ISSUE TITLE
request help: Add docker image that contains apisix all dependencies

### ISSUE THREAD

**Issue by moonming** [apache/apisix#2783]
### Issue description

Users do not need to install any dependencies, such as OpenResty and etcd, and can directly experience Apache APISIX. Of course, it is not recommended to use in the production environment.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by gxthrj** [comment]
ok,   Related to https://github.com/apache/apisix-dashboard/issues/824

**Comment by gxthrj** [comment]
close this issue now , the issue had resolved in https://github.com/apache/apisix-docker/pull/99.
