### ISSUE TITLE
request help: prometheus metrics missing bandwith

### ISSUE THREAD

**Issue by to2false** [apache/apisix#2784]
### Issue description
How to get bandwith metrics?
### Environment

* apisix version (cmd: `apisix version`): 1.5/2.0
* OS: alpine(docker container)

**Comment by spacewander** [comment]
There is `apisix_bandwidth` in https://github.com/apache/apisix/blob/master/doc/plugins/prometheus.md

**Comment by to2false** [comment]
> Total Bandwidth (egress/ingress) flowing through apisix

So it only works under ingress?

**Comment by spacewander** [comment]
> 
> 
> > Total Bandwidth (egress/ingress) flowing through apisix
> 
> So it only works under ingress?

Both ingress and egress are supported.

**Comment by to2false** [comment]
Okay
