### ISSUE TITLE
request help:  in stream_proxy，Udp agent, forwarding to upstream, packet loss is serious

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#2787]
### Issue description
1. my config:
{
    "server_addr": "10.3.174.125",  
    "server_port": 9200,  
    "upstream": {
        "nodes": {
            "10.3.174.127:29090": 1,
            "10.3.174.126:29090": 1
        },
        "type": "roundrobin"
    }
}
2.I sent 6, lost 2, and forwarded 4 normally

3.error log:
![1221](https://user-images.githubusercontent.com/29362652/99527785-558e5c80-29d8-11eb-9f8a-377cbfccd6ac.jpg)

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS:centos7

**Comment by membphis** [comment]
you should check the network of upstream first, it shows `connection refused`.
