### ISSUE TITLE
perf: In function is_empty_yaml_line, 'string.find' plain mode is not recommended, and re.find is better.

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#2788]
### Issue description

```
local function is_empty_yaml_line(line)
    return line == '' or string.find(line, '^%s*$') or
           string.find(line, '^%s*#')
end
```

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by idbeta** [comment]
Is there test data to prove it is better?

**Comment by tokers** [comment]
Currently `bin/apisix` is interpreted by the Lua.
