### ISSUE TITLE
request help: Send a correct request but return “502 bad gateway”

### ISSUE THREAD

**Issue by 1746631764** [apache/apisix#2792]
### Issue description
When testing the limit count plug-in or other plug-ins
![image](https://user-images.githubusercontent.com/53963192/99628758-c0d83d00-2a71-11eb-9ba6-99f08a5d24ac.png)

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos 7

**Comment by nic-chen** [comment]
could you please provide detailed steps to reproduce and related error log and access log? thanks.

**Comment by 1746631764** [comment]
> could you please provide detailed steps to reproduce and related error log and access log? thanks.

Operate according to the document
error.log:
2020/11/19 15:28:07 [error] 3693#3693: *203078 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "http://39.97.63.215:80/index.html", host: "127.0.0.1:9080"

**Comment by nic-chen** [comment]
> > could you please provide detailed steps to reproduce and related error log and access log? thanks.
> 
> Operate according to the document
> error.log:
> 2020/11/19 15:28:07 [error] 3693#3693: *203078 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "http://39.97.63.215:80/index.html", host: "127.0.0.1:9080"

It tell that upstream: "http://39.97.63.215:80/index.html"  connect failed

**Comment by Firstsawyou** [comment]
> > could you please provide detailed steps to reproduce and related error log and access log? thanks.
> 
> Operate according to the document
> error.log:
> 2020/11/19 15:28:07 [error] 3693#3693: *203078 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "http://39.97.63.215:80/index.html", host: "127.0.0.1:9080"

@1746631764 
I think the upstream service you configured may be unavailable. When operating according to the document, you need to configure the available upstream service addresses.

**Comment by 1746631764** [comment]
> > > could you please provide detailed steps to reproduce and related error log and access log? thanks.
> > 
> > 
> > Operate according to the document
> > error.log:
> > 2020/11/19 15:28:07 [error] 3693#3693: *203078 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "http://39.97.63.215:80/index.html", host: "127.0.0.1:9080"
> 
> @1746631764
> I think the upstream service you configured may be unavailable. When operating according to the document, you need to configure the available upstream service addresses.

Yes, I've discovered the problem，thanks
