### ISSUE TITLE
request help: use self ca to connect etcd fail

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2794]
### Issue description
I use cfssl to generated the  etcd ca, I can connect it with etcdctl with flowing command
```
etcdctl --endpoints=https://127.0.0.1:2379  --key-file=/etc/etcd/etcd-ca/client-key.pem --cert-file=/etc/etcd/etcd-ca/client.pem  cluster-health
```
And I can use the curl command to connect it 
```
curl -k --cert /usr/local/certs/client.pem --key /usr/local/certs/client-key.pem -s -m 60 https://192.168.100.96:12379/version
```
But how can I do in apisix, I config etcd with  https and with no verify, after that I got this error 
```
 [error] 4533#0: *91 SSL_do_handshake() failed (SSL: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:SSL alert number 42), context: ngx.timer
``` 
I try to set this config "lua_ssl_trusted_certificate" (https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate) with root ca "ca.pem", but I also can not work. Is their some config for "client-key" and "client.pem" I can set?

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by tokers** [comment]
APISIX doesn't support mutual TLS with etcd.

**Comment by gy09535** [comment]
> APISIX doesn't support mutual TLS with etcd, but the single TLS mode was already supported.

See it , maybe it is a "openresty" issue, I check "openresty" can not support mutual TLS.

**Comment by starsz** [comment]
Hi, @gy09535. Because the socket in lua-nginx-module can't connect with mutual TLS, So APISIX doesn't support mutual TLS with etcd.
More Details: https://github.com/openresty/lua-nginx-module#tcpsockconnect
https://github.com/api7/lua-resty-etcd/blob/cd300fbad847f9a4297307dcb85b57c821d161d8/lib/resty/etcd/v3.lua#L493.

I think you may try etcd-proxy. ：）

**Comment by gy09535** [comment]
> Hi, @gy09535. Because the socket in lua-nginx-module can't connect with mutual TLS, So APISIX doesn't support mutual TLS with etcd.
> More Details: https://github.com/openresty/lua-nginx-module#tcpsockconnect
> https://github.com/api7/lua-resty-etcd/blob/cd300fbad847f9a4297307dcb85b57c821d161d8/lib/resty/etcd/v3.lua#L493.
> 
> I think you may try etcd-proxy. ：）

yeah，I am trying another way

**Comment by spacewander** [comment]
We  will close this issue since the mTLS needs to be supported in OpenResty.
