### ISSUE TITLE
request help:  Unable to view upstream health check results 

### ISSUE THREAD

**Issue by gzhsnail** [apache/apisix#2797]
### Issue description
 After the health check is completed through the interface settings, the upstream health check results cannot be viewed .

通过接口设置完成健康检查后，无法查看 upstream 健康检查结果，需要根据健康检查的结果触发告警机制等其他场景。

### Environment

* apisix version (cmd: `apisix version`): v2.0
* OS: centos 7

**Comment by spacewander** [comment]
Let's move the discussion to #2798.
