### ISSUE TITLE
[DISCUSS] provide a control interface to expose APISIX internal state

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#2798]
We can let APISIX listen a specific port and provide some APIs just like the current admin server.

Those APIs include:
* /healthcheck: show the status of healthcheck. See #2797.

**Comment by tokers** [comment]
Yep, i'm devoting to the /status api, i think the health check result is also required.

**Comment by spacewander** [comment]
@gzhsnail What kind of health check information you need?

**Comment by tokers** [comment]
This topic could be more semantic, not only health check result of upstream endpoints, but also dumping configurations and others.

**Comment by tokers** [comment]
This topic could be more semantic, not only health check result of upstream endpoints, but also dumping configurations and others.

**Comment by gzhsnail** [comment]
> 
> 
> @gzhsnail What kind of health check information you need?

 For the time being, only upstream is required to be active 。
暂时只需要 upstream 主动检查是否健康和被动检查是否健康。

**Comment by spacewander** [comment]
@gzhsnail 
There is not concept of "主动检查是否健康" and "被动检查是否健康".
There is only two state: "healthy" and "unhealthy". Both "active check" and "passive check" can change a node from "healthy" to "unhealthy", or reverse.

**Comment by spacewander** [comment]
So we can get the check & upstream's configuration, the healthy nodes (unhealthy nodes can be found via `nodes` - `healthy nodes`).
