### ISSUE TITLE
bug: In proxy UDP, roundrobin is unbalanced

### ISSUE THREAD

**Issue by zhuchengxing** [apache/apisix#2799]
### Issue description
When I used UDP proxy, I find roundrobin unbalanced.  Once the connection is established, it will always send a message to only one of the nodes!
### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS:centos7

### Minimal test code / Steps to reproduce the issue
1.  config stream_routes:
{
    "server_addr": "10.3.174.125",  
    "server_port": 9200,  
    "upstream": {
        "nodes": {
            "10.3.174.127:29090": 1,
            "10.3.174.126:29090": 1
        },
        "type": "roundrobin"
    }
}

2. test send message，I sent several pieces of data to ApisiX 9200 port with the **nc** command,commplete command: **nc -p 6336 -u 10.3.174.125 9200**
![q](https://user-images.githubusercontent.com/29362652/99751998-6812ae00-2b1e-11eb-9a53-a24809065212.jpg)

3.Apisix would forward the UDP message sent, but it was forwarded to only one node without load balancing effect, which made me very confused:
![2](https://user-images.githubusercontent.com/29362652/99752321-0e5eb380-2b1f-11eb-9933-a29c26e0a34c.jpg)
![3](https://user-images.githubusercontent.com/29362652/99752331-11f23a80-2b1f-11eb-9add-0e18d0f014d8.jpg)

### What's the actual result? (including assertion message & call stack if applicable)
You can see that the message is only forwarded to node 126！

### What's the expected result?
I expect to achieve responsible and balanced results.

**Comment by starsz** [comment]
Hi, @zhuchengxing, have you check the error log?

And you can try to send UDP package to node 127 directly. Like this 
```
nc -p 6336 -u 10.3.174.127 290290
```

Is that ok?

**Comment by idbeta** [comment]
@zhuchengxing any update? my environment ( master branch ) cannot reproduce the problem according to your steps,

**Comment by zhuchengxing** [comment]
> Hi, @zhuchengxing, have you check the error log?
> 
> And you can try to send UDP package to node 127 directly. Like this
> 
> ```
> nc -p 6336 -u 10.3.174.127 290290
> ```
> 
> Is that ok?

yes !   nc -p 6336 -u 10.3.174.127 29090

**Comment by zhuchengxing** [comment]
> @zhuchengxing any update? my environment ( master branch ) cannot reproduce the problem according to your steps,

!!!!!   I just tried it again, but it still doesn't load balance, is that because the master branch has changed? i used 2.0

**Comment by idbeta** [comment]
@zhuchengxing I reproduce your problem now, i am not familiar with this feature, cc @membphis

**Comment by zhuchengxing** [comment]
@idbeta  ok, thanks .

**Comment by membphis** [comment]
welcome to submit PR to fix this issue

**Comment by shuaijinchao** [comment]
I can’t reproduce this problem using `nc` and `client` in a local debug environment

---

![image](https://user-images.githubusercontent.com/8529452/139784354-3a49da98-9d48-419f-8e54-a30d2fc3b520.png)

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
