### ISSUE TITLE
test(CLI): only need to confirm part of result, returned list may change in the future.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2800]
original comment: https://github.com/apache/apisix/pull/2690/files#r527367999

**Comment by membphis** [comment]
@ jxhecong would like to this this issue?

**Comment by wfnuser** [comment]
I would like to have a try.😄

**Comment by membphis** [comment]
many thx, good luck. if you need any help, pls let us know

**Comment by wfnuser** [comment]
I'm going through the whole project background. I'm not so sure what 'init_kv=(' and 'apisix_cli_test.sh ' for, yet. Where can I figure it out quickly. Would you give me some clues, that will be a big help.

**Comment by membphis** [comment]
> I'm going through the whole project background. I'm not so sure what 'init_kv=(' and 'apisix_cli_test.sh ' for, yet. Where can I figure it out quickly. Would you give me some clues, that will be a big help.

@jxhecong need your help ^_^

**Comment by wfnuser** [comment]
I think what @membphis means in the original comment: https://github.com/apache/apisix/pull/2690/files#r527367999 is, that there might be more routes in $cmd_res, we should only check part of the key-value pairs are correct.
So I would like to use a hash map in shell supported by shell 4. Is that ok?

**Comment by membphis** [comment]
> So I would like to use a hash map in shell supported by shell 4. Is that ok?

I think a regular matching is enough and simpler.

**Comment by wfnuser** [comment]
> > So I would like to use a hash map in shell supported by shell 4. Is that ok?
> 
> I think a regular matching is enough and simpler.

Not so sure how to use regular matching here. 😂

**Comment by spacewander** [comment]
Solved.
