### ISSUE TITLE
[DISCUSS]: add vars matching rules to public methods

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2809]
### Issue description

We all know that apisix supports vars matching rules, similar to this: {var, operator, val}. But these rules are in the `apisix/deps/share/lua/5.1/resty/radixtree.lua` file, not in the public method. Therefore, we cannot reuse these rules. The `match` rule is a very useful feature. If we add the `match` rule to the `apisix/apisix/core` module, we can reuse these `match` rules.  I think it must be very interesting.

Examples of vars matching:

```
[ "arg_name", "==", "rose" ],
[ "http_appKey", "~~", "[a-z].+" ]
[ "server_port", ">=", "80" ]
```

Supported operators: `==, ~=, ~~, >, >=, <, <=, ip, ip_in`

### Operator list

| Operator  | Description           |         Example             |
|-----------|-----------------------|-----------------------------|
| ==        | equal                 | {"arg_name", "==", "json"}  |
| ~=        | not equal to          | {"arg_name", "~=", "json"}  |
| ~~        | Regular match         | {"arg_name", "~~", "[a-z]+"}|
| <         | Less than             | {"arg_age", "<", 24}        |
| <=        | Less than or equal to | {"arg_age", "<=", 24}       |
| >         | more than the         | {"arg_age", ">", 24}        |
| >=        | greater or equal to   | {"arg_age", ">=", 24}       |

what do you think? Welcome to discuss together.

**Comment by starsz** [comment]
Where can these matching rules be used？Can you give some examples?

**Comment by spacewander** [comment]
Maybe we can move the matching rules to a separate repo, so that we can also use this to satisfy https://github.com/api7/lua-resty-radixtree/issues/74

**Comment by moonming** [comment]
> Maybe we can move the matching rules to a separate repo, so that we can also use this to satisfy [api7/lua-resty-radixtree#74](https://github.com/api7/lua-resty-radixtree/issues/74)

agreed, router already support match rules.

**Comment by moonming** [comment]
> But these rules are in the apisix/deps/share/lua/5.1/resty/radixtree.lua file, not in the public method. 

@Firstsawyou I am not get your point.

**Comment by Firstsawyou** [comment]
> > But these rules are in the apisix/deps/share/lua/5.1/resty/radixtree.lua file, not in the public method.
> 
> @Firstsawyou I am not get your point.

What I mean is that we can't reuse the matching rules in radixtree.lua, because his definition is local.
The matching rule definition in radixtree.lua:

```lua
local compare_funcs = {
    ["=="] = function (l_v, r_v)
        if type(r_v) == "number" then
            l_v = tonumber(l_v)
            if not l_v then
                return false
            end
        end
        return l_v == r_v
    end,
    ["~="] = function (l_v, r_v)
        return l_v ~= r_v
    end,
    [">"] = function (l_v, r_v)
        l_v = tonumber(l_v)
        r_v = tonumber(r_v)
        if not l_v or not r_v then
            return false
        end
        return l_v > r_v
    end,
    ["<"] = function (l_v, r_v)
        l_v = tonumber(l_v)
        r_v = tonumber(r_v)
        if not l_v or not r_v then
            return false
        end
        return l_v < r_v
    end,
    ["~~"] = function (l_v, r_v)
        local from = re_find(l_v, r_v, "jo")
        if from then
            return true
        end
        return false
    end,
    ["IN"] = in_array,
    ["in"] = in_array,
}
```

**Comment by Firstsawyou** [comment]
> Hi, Where can these matching rules be used？Can you give some examples?

This is a related issue that needs to use these rules：
https://github.com/apache/apisix/issues/2511 
https://github.com/apache/apisix/issues/2303

**Comment by tzssangglass** [comment]
> Maybe we can move the matching rules to a separate repo, so that we can also use this to satisfy [api7/lua-resty-radixtree#74](https://github.com/api7/lua-resty-radixtree/issues/74)

agree +1

**Comment by spacewander** [comment]
Done
