### ISSUE TITLE
[DISCUSS]: allow user to specify APISIX id in config.yaml

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#2810]
Currently, the id of APISIX is generated UUID, which can't be controlled by the user. I think it would be good to allow user to specify a meaningful id to bind APISIX instance with their internal system.

**Comment by tokers** [comment]
It would be better to support vars.

**Comment by spacewander** [comment]
> 
> 
> It would be better to support vars.

I am confusing. `vars` is already supported: https://github.com/apache/apisix/pull/2743

**Comment by tokers** [comment]
> > It would be better to support vars.
> 
> I am confusing. `vars` is already supported: #2743

Sorry i forgot it.

**Comment by membphis** [comment]
I think that is a good feature

**Comment by tzssangglass** [comment]
Let me try.

**Comment by membphis** [comment]
I have assigned this job to you @tzssangglass 
good luck ^_^

**Comment by tzssangglass** [comment]
> I have assigned this job to you @tzssangglass
> good luck ^_^

ok

**Comment by tzssangglass** [comment]
my pleasure
