### ISSUE TITLE
bug: about wolf-rbac get token problem

### ISSUE THREAD

**Issue by 1731lin** [apache/apisix#2812]
### Issue description
[root@localhost example]# curl http://127.0.0.1:9080/apisix/plugin/wolf-rbac/login -i -H "Content-Type: application/json" -d '{"appid": "restful-demo", "username":"root", "password":"wolf-123456"}'
HTTP/1.1 500 Internal Server Error
Date: Sat, 21 Nov 2020 03:43:33 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"message":"request to wolf-server failed! connection refused"}

### Environment

* apisix version (cmd: `apisix version`):1.5
* OS:centos7

### Minimal test code / Steps to reproduce the issue
1.https://github.com/vinsonzou/apisix-plugin-rbac
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

I followed the github steps and I had this problem,{"message":"request to wolf-server failed! connection refused"}

### What's the expected result?
get token
{"rbac_token":"V1#restful#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzQ5LCJ1c2VybmFtZSI6InRlc3QiLCJtYW5hZ2VyIjoiIiwiYXBwaWQiOiJyZXN0ZnVsIiwiaWF0IjoxNTc4ODIzNzQ3LCJleHAiOjE1Nzk0Mjg1NDd9.4rGPHv9hWPZ4G0p2F82gQciY8WIE2qdYNvAT_22X_Co","user_info":{"nickname":"test","username":"test","id":"749"}}

**Comment by spacewander** [comment]
The error message is already clear. The wolf-server you configured via `server` field can be connected. (`request to wolf-server failed! connection refused`).
Please check your environment and your configuration.
