### ISSUE TITLE
DISCUSS: Should APISIX support `https` when connecting to etcd ?

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#2814]
### Issue description
Related to #2182 

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by starsz** [comment]
Hi, As far as I know, APISIX had support HTTPS already.

See more details: 
https://github.com/apache/apisix/blob/3c12b61207d3b3862b2d25060b85e606227b5a65/doc/install-dependencies.md#note

https://github.com/apache/apisix/blob/4d290172146ba6fea372a2e224f6a8947a8fce6c/conf/config-default.yaml#L153-L156

**Comment by moonming** [comment]
already support

**Comment by spacewander** [comment]
solved.
