### ISSUE TITLE
[DISCUSS]:  APISIX should check the ssl certificate in "apisix/admin/ssl" API

### ISSUE THREAD

**Issue by starsz** [apache/apisix#2816]
### Issue description
Hi, I think APISIX should check the SSL certificate in "apisix/admin/ssl" API.
If the SSL certificate is illegal, APISIX should give some prompt.

related： https://github.com/apache/apisix/issues/2791

**Comment by tokers** [comment]
@starsz PR's are welcome.

**Comment by moonming** [comment]
CP do this job now

**Comment by moonming** [comment]
I'm not sure if dp needs this check

**Comment by spacewander** [comment]
Since there are users using the admin API, I think it is needed.
