### ISSUE TITLE
[DISCUSS]: Use luasocket lib instead of `curl` in "bin/apisix" 

### ISSUE THREAD

**Issue by starsz** [apache/apisix#2818]
Hi, I advise using luasocket lib instead of `curl` in "bin/apisix".

Although, it's very convenient to get HTTP responses by using "io.open" and "curl". 
But, I think it's not an elegant way and has some limitations. Such as can't distinguish error info between `Connection refused` and empty response.

So I think we can use luasocket lib and create a common function in "cli/util.lua", so that we can deal with some HTTP request better in "bin/apisix".

releated: #2718

**Comment by spacewander** [comment]
Do you mean writing a new HTTP client based on luasocket? Since lua-resty-http can't be used without `ngx`.

**Comment by tokers** [comment]
What about just use luasocket?

**Comment by tokers** [comment]
> Do you mean writing a new HTTP client based on luasocket? Since lua-resty-http can't be used without `ngx`.

The luasocket lib already has a HTTP client implementation.

**Comment by starsz** [comment]
Hi, @spacewander @tokers, Yeah, luasocket had an HTTP client implementation already. 
See: http://w3.impa.br/~diego/software/luasocket/http.html
So, I want to use luasocket lib instead of curl in "bin/apisix".

**Comment by tokers** [comment]
But i'm not sure whether it's built in? Or users have to install it before they can use `bin/apisix`.

**Comment by starsz** [comment]
> But i'm not sure whether it's built in? Or users have to install it before they can use `bin/apisix`.

Users need to do `make deps` before they use `bin/apisix`. So I think it can be solved.

**Comment by tokers** [comment]
> > But i'm not sure whether it's built in? Or users have to install it before they can use `bin/apisix`.
> 
> Users need to do `make deps` before they use `bin/apisix`. So I think it can be solved.

OK, that's good.

**Comment by membphis** [comment]
We can make a try.

Need to pay attention to the use of different systems(ubuntu, centos and mac os), whether there are compatibility issues.

**Comment by moonming** [comment]
Can we specify the path of openresty to solve this problem?  So we can use lua-resty-http.

**Comment by membphis** [comment]
Do you mean to run the CLI in fake `openresty` ENV? Is it the same as the "resty" command?

**Comment by moonming** [comment]
yes

Thanks,
Ming Wen
Twitter: _WenMing


YuanSheng Wang <notifications@github.com> 于2020年11月23日周一 下午11:42写道：

**Comment by spacewander** [comment]
There are some limitation in `resty`, for instance, access environment variables.

**Comment by starsz** [comment]
Hi, @moonming, I think there is no need to use `lua-resty-http`.
In CLI, we don't care about non-blocking, and luasocket is also easy to use now.

What's your opinion about using `lua-resty-http`.
