### ISSUE TITLE
request help: how to apply bandwidth control in apisix?

### ISSUE THREAD

**Issue by wfgydbu** [apache/apisix#2820]
### Issue description
Does APISIX support bandwidth control right now?

Consider this scenario, Using APISIX as a gateway to handle all traffics, and expecting the gateway to limit the bandwidth (all traffics) to, say no more than 5G. because we have to keep some bandwidth for inner user, i.e. for managerment.

Is this possible? Do we have this feature or any solutions now?

Thanks.

### Environment

* apisix version (cmd: `apisix version`): any version > 1.2, preferably 2.0
* OS: Centos 7.6

**Comment by spacewander** [comment]
There is not such a feature. But you can write your plugin works on body_filter and do the limitation. There is not way to archive an ingress bandwidth control yet.
Personally speaking, I will suggest you to do this at the level of router instead of the API gateway.

**Comment by tokers** [comment]
@wfgydbu If the granularity of bandwidth limitation is the whole gateway instance, i think it's better to do it in a low level, just as @spacewander said.

If you want to do it per request level, now you can modify the `apisix/cli/ngx_tpl.lua` (the nginx.conf configuration template), add `limit_rate` directive to use the rate limiting feature of Nginx itself.

**Comment by wfgydbu** [comment]
Thanks for comments. 

Seems we need to re-discuss out plan here, thanks!

**Comment by wfgydbu** [comment]
> There is not such a feature. But you can write your plugin works on body_filter and do the egress limitation, then apply it to global rule. There is not way to archive an ingress bandwidth control yet.
> Personally speaking, I will suggest you to do this at the level of router instead of the API gateway.

Could you please explain a bit why we cannot limit egress traffic but not ingress traffic with apisix? Thanks a lot! @spacewander

**Comment by spacewander** [comment]
Because Nginx doesn't provide a mechanism to limit ingress traffic.

**Comment by wfgydbu** [comment]
Cool 😭，Thanks!
