### ISSUE TITLE
Implement status API

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2821]
We have already some disscussion about this topic: https://lists.apache.org/thread.html/re3097f7e88d636e8137231c36462c32773b2b4817d91f7997e91358f%40%3Cdev.apisix.apache.org%3E.

This thread is used to track the development progress about APISIX part.

The related issues:

* https://github.com/apache/apisix-dashboard/issues/849
* https://github.com/apache/apisix-dashboard/issues/850

**Comment by tokers** [comment]
Information should be exposed:

```json
{
    "id": "ddea4053-4ffd-4f09-b176-b8c5e919916b",
    "hostname": "localhost.local",
    "version": "2.0",
    "etcd_version": "3.5.0",
    "uptime": 3600,
    "node_listen": [9080, 9443, 9180]
}
```

@juzhiyuan @membphis @moonming @starsz What do you think? May be the node_listen could be more semantic like:

```json
node_listen: [
    {
         "port": 9080,
         "name": "http"
    },
    {
         "port": 9081,
         "name": "http"
    },
    {
         "port": 9180,
         "name": "admin"
    },
    {
         "port": 9443,
         "name": "https"
    },
    {
         "port": 9100,
         "name": "tcp"
    },
    {
         "port": 9101,
         "name": "udp"
    }
]
```

**Comment by moonming** [comment]
can we return `config.yaml`? and we can do this later.

**Comment by tokers** [comment]
> can we return `config.yaml`? and we can do this later.

You mean the whole config.yaml data after the vars resolving?

**Comment by starsz** [comment]
Hi, @tokers. Only `port` in node_listen maybe not enouth if `host` was set to listen.

**Comment by tokers** [comment]
> > can we return `config.yaml`? and we can do this later.
> 
> You mean the whole config.yaml data after the vars resolving?

@justinmclean Does the frontend page should be adjusted if we do so?

**Comment by tokers** [comment]
> Hi, @tokers. Only `port` in node_listen maybe not enough if `host` was set to listen.

That's true.

**Comment by juzhiyuan** [comment]
> > > can we return `config.yaml`? and we can do this later.
> > 
> > 
> > You mean the whole config.yaml data after the vars resolving?
> 
> @justinmclean Does the frontend page should be adjusted if we do so?

hmmm justinmclean may not know about this, we don't need to update the sketch for the frontend according to this proposal[1].

[1] https://github.com/apache/apisix-dashboard/issues/850#issuecomment-732010534

**Comment by tokers** [comment]
> can we return `config.yaml`? and we can do this later.

There are some secret data like `key_encrypt_salt` which are not suitable to be shown.

**Comment by juzhiyuan** [comment]
How about adding those secret data to an allowlist?

**Comment by tokers** [comment]
I think it will make the data plane complex, since we have to filter these secret data. I suggest just add some basic items firstly, and listen the feedback from Community.

**Comment by membphis** [comment]
We can implement a mini version first and add more fields later. ^_^

**Comment by tokers** [comment]
OK, let's just add the most basic fields now:

```json
{
    "id": "ddea4053-4ffd-4f09-b176-b8c5e919916b",
    "hostname": "localhost.local",
    "version": "2.0",
    "etcd_version": "3.5.0",
    "uptime": 3600,
    "last_report_at": 1606121591
}
```
