### ISSUE TITLE
request help: fault-injection abort.body  Using variables

### ISSUE THREAD

**Issue by GiftLee** [apache/apisix#2827]
### Issue description
abort.body    
{"status":"success","time":"$time_local"}

$time_local is nginx variables
or  Custom variable

ok     english is poor 
 
 i want this 

location ~ ^/get_json {
    default_type application/json;
    return 200 '{"status":"success","SERVER_TIME":"$current time"}';
}

### Environment

* apisix version 2.0:
* OS: Centos 7

**Comment by Firstsawyou** [comment]
This is a related issue: [https://github.com/apache/apisix/issues/2511 ](https://github.com/apache/apisix/issues/2511), I think supporting variables are very useful.

If the function of this related issue is realized, I think we can implement it.
[https://github.com/apache/apisix/issues/2809 ](https://github.com/apache/apisix/issues/2809)

**Comment by GiftLee** [comment]
i think enhance fault-injection ,add function 

like  this 
```

function _M.rewrite(conf, ctx)
    core.log.info("plugin rewrite phase, conf: ", core.json.delay_encode(conf))

    if conf.delay
       and conf.delay.duration ~= nil
       and sample_hit(conf.delay.percentage)
    then
        sleep(conf.delay.duration)
    end

    if conf.abort
       and conf.abort.http_status ~= nil
       and sample_hit(conf.abort.percentage)
    then
        -- core.log.debug("sss1 ", conf.abort.body)
        local body = string.gsub(conf.abort.body, "%$(.-)%$", function (func)  return loadstring(func)() end)
        -- core.log.debug("abortwwwu ", body)
        return conf.abort.http_status, body
    end
end
```
is good idea ?

**Comment by membphis** [comment]
waiting for more response
