### ISSUE TITLE
request help: helm chart comfigmap.yaml

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix#2839]
### Issue description
Recently because of work needs, I am writing a “APISIX" helm chart for company. (Company has helm repo. )
I ran into a problem when I wrote configmap.yaml. I am not sure which parameters to write in values.yaml. Because I only modified a small part of the parameters in my previous use, but obviously many parameters are meaningful.
This may require a department review, but other colleagues don’t know much about apisix.

I find helm chart has been add in 2.2 milestone, maybe you can give me some suggestions.

**Comment by moonming** [comment]
@gxthrj please take a look.
we already has repo of helm chart: https://github.com/apache/apisix-helm-chart

**Comment by ziyou434** [comment]
> @gxthrj please take a look.
> we already has repo of helm chart: https://github.com/apache/apisix-helm-chart

I used this in the dev environment before, and now I change it based on it.
But because of the version upgrade, config-default.yaml has changed a bit.
I remember this was written by a contributor, and I think the developers may have more insights.

**Comment by gxthrj** [comment]
Hi @ziyou434 
The `config-default.yaml` in Apache APISIX is the default config file, It contains the most complete configuration items, and no modification is required by default.

The most need to care about is `config.yaml` when deploying Apache APISIX .  The `config.yaml` is a subset of `config-default.yaml`, before running Apache APISIX, the two files will be merged, replacing `config-default.yaml` with the value in `config.yaml`.

In helm charts, it is the [configmap.yaml](https://github.com/apache/apisix-helm-chart/blob/master/chart/apisix/templates/configmap.yaml) and [values.yaml](https://github.com/apache/apisix-helm-chart/blob/master/chart/apisix/values.yaml), we define the configuration that needs to be changed in `values.yaml`. Please note that `array type` of configuration items must be replaced in full.

Apache APISIX will release 2.1 soon, we also need to update the [helm chart](https://github.com/apache/apisix-helm-chart), for release, I plan to start this work this week, and everyone is welcome to participate.

**Comment by ziyou434** [comment]
> @ ziyou434
> ，您好：`config-default.yaml`Apache APISIX中的是默认配置文件，它包含最完整的配置项目，默认情况下不需要修改。
> 
> 最需要关心的是`config.yaml`部署Apache APISIX时。本`config.yaml`的一个子集`config-default.yaml`，运行Apache APISIX之前，这两个文件将被合并，替换`config-default.yaml`与价值`config.yaml`。
> 
> 在头盔图表中，是[configmap.yaml](https://github.com/apache/apisix-helm-chart/blob/master/chart/apisix/templates/configmap.yaml)和[values.yaml](https://github.com/apache/apisix-helm-chart/blob/master/chart/apisix/values.yaml)，我们定义了需要更改的配置`values.yaml`。请注意，`array type`配置项目必须全部更换。
> 
> Apache APISIX即将发布2.1，我们还需要更新[头盔图表](https://github.com/apache/apisix-helm-chart)，要发布，我计划在本周开始这项工作，欢迎大家参加。

I hope you can share any good ideas or discoveries in the task, I appreciate it. 
My task deadline is next Wednesday. I don’t want it to be no different from the [old helm chart](https://github.com/apache/apisix-helm-chart), and then my work will lose its meaning.

**Comment by ziyou434** [comment]
I Communicate with leader again to clarify the requirements, and my purpose of developing it is to load custom plugins.
My job is to update the version, and then add the plugin.lua to the container by configmap.
Do you have other ways to load custom plugins？

**Comment by gxthrj** [comment]
In the new version of Apache APISIX 2.0 you can continue to use your previous configuration,APISIX can continue to work, because `config.yaml` will be merged with `config-default.yaml`.
Make sure that the plugin list in [values.yaml](https://github.com/apache/apisix-helm-chart/blob/master/chart/apisix/values.yaml) contains all the plugins you need.

**Comment by gxthrj** [comment]
> I Communicate with leader again to clarify the requirements, and my purpose of developing it is to load custom plugins.
> My job is to update the version, and then add the plugin.lua to the container by configmap.
> Do you have other ways to load custom plugins？

Please pay attention to the [change logs](https://github.com/apache/apisix/blob/master/CHANGELOG.md#200) when you are ready to upgrade Apache APISIX.
