### ISSUE TITLE
request help: Route vars regex match support case-insensitive

### ISSUE THREAD

**Issue by yangxikun** [apache/apisix#2841]
### Issue description

We want Route vars regex match support case-insensitive, such as match http_user_agent header value.

Is it possible add an `~*` operator to support case-insensitive? I can make a PR for this.

https://github.com/api7/lua-resty-radixtree/blob/99f4049ff3520e0f60bb64bb6f2f382947458890/lib/resty/radixtree.lua#L542

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS:

**Comment by yangxikun** [comment]
Also, we want `!~` operator to support not regex match. We are migrating from nginx.

**Comment by spacewander** [comment]
@yangxikun 
Let's add it to https://github.com/api7/lua-resty-expr.
BTW, we will have `not` operator support with https://github.com/api7/lua-resty-expr/pull/3
