### ISSUE TITLE
request help: resty/lock.lua sleep API disabled in the context of balancer_by_lua*

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/apisix#2842]
### Issue description

2020/11/25 10:14:54 [error] 91#91: *851285 connect() failed (111: Connection refused) while connecting to upstream, client: 172.3
0.42.212, server: , request: "GET /xxx?method=testxxxx HTTP/1.1", upstream: "http://****/test?method=testxxx
x", host: "gateway-lxrel.internetofcity.cn"
2020/11/25 11:07:57 [error] 88#88: *3602906 failed to run balancer_by_lua*: /usr/local/apisix//deps/share/lua/5.1/resty/lock.lua:
153: API disabled in the context of balancer_by_lua*
stack traceback:
        [C]: in function 'sleep'
        /usr/local/apisix//deps/share/lua/5.1/resty/lock.lua:153: in function 'lock'
        /usr/local/apisix//deps/share/lua/5.1/resty/healthcheck.lua:207: in function 'locking_target_list'
        /usr/local/apisix//deps/share/lua/5.1/resty/healthcheck.lua:268: in function 'add_target'
        /usr/local/apisix/lua/apisix/balancer.lua:86: in function 'create_obj_fun'
        /usr/local/apisix/lua/apisix/core/lrucache.lua:171: in function 'lrucache_checker'
        /usr/local/apisix/lua/apisix/balancer.lua:119: in function 'fetch_healthchecker'
        /usr/local/apisix/lua/apisix/balancer.lua:245: in function 'pick_server'
        /usr/local/apisix/lua/apisix/balancer.lua:315: in function 'load_balancer'
        /usr/local/apisix/lua/apisix.lua:645: in function 'http_balancer_phase'
        balancer_by_lua:2: in main chunk while connecting to upstream, client: *****, server: , request: "*******"

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by membphis** [comment]
what is the apisix version?

**Comment by OnlyPiglet** [comment]
> what is the apisix version?

apisix 1.1 but make some customized changes but the main logic is the same with apisix 1.1

**Comment by membphis** [comment]
pls make a  try with the latest version

your version is too old

**Comment by OnlyPiglet** [comment]
ok i see
