### ISSUE TITLE
doc: wrong link

### ISSUE THREAD

**Issue by membphis** [apache/apisix#2843]
### Issue description

the correct link should be: `#consumer-1`

https://github.com/apache/apisix/blob/master/doc/architecture-design.md#table-of-contents

![image](https://user-images.githubusercontent.com/6814606/100187405-fd4ce280-2f22-11eb-814f-666008f76e56.png)

**Comment by HelloBug0** [comment]
Yeah, it will jump to other wrong title Consumer now. And I have test it that it will work right and won't influence other headline if the link changes to #consumer-1. 
How do you know it will work well by changing to #consumer-1? I tried #consumer-2,  it doesn't work. And I stilll don't know the reason why it works well in this way even throug I search it. 
Feels AMAZING!

**Comment by membphis** [comment]
here is my way to get the right link:

![image](https://user-images.githubusercontent.com/6814606/100312468-600ab080-2fed-11eb-99ce-3a514f4990b7.png)

or we can fix this issue via this way:
![image](https://user-images.githubusercontent.com/6814606/100312565-a5c77900-2fed-11eb-8d6a-094f40ecaf6a.png)

**Comment by HelloBug0** [comment]
I see. 👍 👍 👍

**Comment by 96RadhikaJadhav** [comment]
@membphis  This issue has already been worked on or is it still open? If open, can I work on it?

**Comment by membphis** [comment]
@96RadhikaJadhav that is a todo job. welcome to fix this issue

**Comment by 96RadhikaJadhav** [comment]
@membphis  Could you please guide me the path to the file where this link can be changed?

**Comment by membphis** [comment]
> @membphis  Could you please guide me the path to the file where this link can be changed?

https://github.com/apache/apisix/blob/master/doc/architecture-design.md#table-of-contents

**Comment by 96RadhikaJadhav** [comment]
@membphis  I have created a PR. But I forgot to add '-' between consumer and 1. I just changed it to '#consumer1'. But I guess still the link is working fine. Could you please review my PR and let me know if any changes needs to be done.

**Comment by membphis** [comment]
> @membphis I have created a PR. But I forgot to add '-' between consumer and 1. I just changed it to '#consumer1'. But I guess still the link is working fine. Could you please review my PR and let me know if any changes needs to be done.

I have replied you, please take a look: https://github.com/apache/apisix/pull/2890#discussion_r532378209

**Comment by 96RadhikaJadhav** [comment]
@membphis I was facing issue to make changes in previous PR, so I created new one.
Please ignore previous one. Please review -> docs: corrected link in architecture-design and let me know if any changes required.

**Comment by membphis** [comment]
@96RadhikaJadhav new PR has been merged. many thx for your contribution
