### ISSUE TITLE
request help:  Ask for a complete openid-connect example

### ISSUE THREAD

**Issue by ShenAoScript** [apache/apisix#2845]
### Issue description
After the environment is ready, I can simply call the plug-in to get the address from my discovery endpoint, and then take the configuration as parameters to request the authentication server, and then pop up to the login window to open the redirection address after authentication...

### Environment

* apisix version 2.0
* OS: centos7 & win10

Ask for a complete or detailed example

Ask for an explanation of its various configurations

THX 4 your help

**Comment by membphis** [comment]
@moonming any suggestion?

**Comment by ShenAoScript** [comment]
You can find examples by perusing the documentation
