### ISSUE TITLE
[DISCUSS] Pagination for fully synchronization from etcd

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2853]
### Issue description

We use `etcdcli:readdir` when we need to load all config instances (like `Route`, `Upstream`) in one round trip, which generates a lot of network traffic, also, the loop to parse each config instances is long, which causes CPU times peak.

So pagination for the fully synchronization is required to reduce both peak of bandwidth and CPU times.

* https://github.com/etcd-io/etcd/issues/11001
* https://github.com/etcd-io/etcd/blob/master/api/etcdserverpb/rpc.proto#L426
* Original issue: https://github.com/apache/apisix/issues/2848.

**Comment by spacewander** [comment]
I think we should let user choose whether to enable pagination and the step size. If pagination is enable, the sync time will be longer, which may be bad for some cases.

**Comment by membphis** [comment]
Do we need to update the `lua-resty-etcd`?

**Comment by wfnuser** [comment]
> lua-resty-etcd

If we need, may I have a try on this issue. It seems not that hard.

**Comment by tokers** [comment]
> Do we need to update the `lua-resty-etcd`?

Yep, we shall.

**Comment by tokers** [comment]
> I think we should let user choose whether to enable pagination and the step size. If pagination is enable, the sync time will be longer, which may be bad for some cases.

We can reserve some advanced option settings in config.yaml, and put all these optimization-scope options there.

**Comment by tokers** [comment]
> > lua-resty-etcd
> 
> If we need, may I have a try on this issue. It seems not that hard.

PR's Welcome!

**Comment by wfnuser** [comment]
> > Do we need to update the `lua-resty-etcd`?
> 
> Yep, we shall.

So do we need to add a new API to read etcd by range?

**Comment by wfnuser** [comment]
Do you have slack channels. I might have a lot of questions.

**Comment by tokers** [comment]
> > > Do we need to update the `lua-resty-etcd`?
> > 
> > 
> > Yep, we shall.
> 
> So do we need to add a new API to read etcd by range?

I glanced the description of https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md#readdir and found there is no such a `start_key` to support our demand to get bulk keys in batched manner. I prefer to extend the `etcd:readdir` instead of adding new one, the new API would be so similar with `etcd:readdir`, it doesn't make so much sense.

**Comment by tokers** [comment]
> Do you have slack channels. I might have a lot of questions.

Yeah, also use this name `tokers`.

**Comment by wfnuser** [comment]
Hi, can some one assign this issue to me. Or It is often difficult to find this issue.😂

**Comment by tokers** [comment]
@wfnuser Assigned to you.

**Comment by wfnuser** [comment]
> > Do you have slack channels. I might have a lot of questions.
> 
> Yeah, also use this name `tokers`.

how can I find or join APISIX slack space?

**Comment by wfnuser** [comment]
> > > > Do we need to update the `lua-resty-etcd`?
> > > 
> > > 
> > > Yep, we shall.
> > 
> > 
> > So do we need to add a new API to read etcd by range?
> 
> I glanced the description of https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md#readdir and found there is no such a `start_key` to support our demand to get bulk keys in batched manner. I prefer to extend the `etcd:readdir` instead of adding new one, the new API would be so similar with `etcd:readdir`, it doesn't make so much sense.

So I will try add `start_key` or `offset` in `readdir` parameter `opts`.
Another question is, we should smooth the traffic in the `readdir` function, or we should write the code in where we call `readdir`? Then we might need to write it in many place where we call `readdir`.

I mean another way is we implement `readdir` with a parameter might called `rate`.
The rate will limit the keys we fetch from etcd each time to smooth the network traffic. We call `readdir` still return the whole bunch of keys, but hide the implementation details of fetch data in multiple round trip.

**Comment by tokers** [comment]
> > > > > Do we need to update the `lua-resty-etcd`?
> > > > 
> > > > 
> > > > Yep, we shall.
> > > 
> > > 
> > > So do we need to add a new API to read etcd by range?
> > 
> > 
> > I glanced the description of https://github.com/api7/lua-resty-etcd/blob/master/api_v3.md#readdir and found there is no such a `start_key` to support our demand to get bulk keys in batched manner. I prefer to extend the `etcd:readdir` instead of adding new one, the new API would be so similar with `etcd:readdir`, it doesn't make so much sense.
> 
> So I will try add `start_key` or `offset` in `readdir` parameter `opts`.
> Another question is, we should smooth the traffic in the `readdir` function, or we should write the code in where we call `readdir`? Then we might need to write it in many place where we call `readdir`.
> 
> I mean another way is we implement `readdir` with a parameter might called `rate`.
> The rate will limit the keys we fetch from etcd each time to smooth the network traffic. We call `readdir` still return the whole bunch of keys, but hide the implementation details of fetch data in multiple round trip.

Not only for the bandwidth, you know create a huge table is expensive, both due to the table grown and memory allocation. So if we still keep all items in a single table and give them to caller at one time, the CPU cycle overheads are still high (the iteration loop will be tight).

Actually an ideal way is passing in a callback to be called when we get new items from etcd, but that would conflict with the current `etcdcli:readdir`, so maybe we need to create another method like `etcdcli:walkdir`.

```lua
local ok, err = etcdcli:walkdir(func(item)
    -- do something here to process the item.
end, opts)
```

**Comment by wfnuser** [comment]
OK. I will try to add `start_key` in `etcdcli:readdir` parameter lists first. Create `etcdcli:walkdir` later in another PR.

**Comment by tokers** [comment]
@wfnuser Any new updates?

**Comment by wfnuser** [comment]
> @wfnuser Any new updates?

Sorry... On vocation these days. I'm still working on it.

**Comment by wfnuser** [comment]
I'm still working on it. It takes me some time to learn how Test::Nginx and etcd work and also get more familiar with lua. Don't be worry...

**Comment by wfnuser** [comment]
@tokers @membphis  After spending some learning costs, I have updated the readdir api to support start_key. Take a look?
And I will update the apisix code later.

**Comment by tokers** [comment]
> @tokers @membphis After spending some learning costs, I have updated the readdir api to support start_key. Take a look?
> And I will update the apisix code later.

Thanks for your hard work, we will review it.

**Comment by spacewander** [comment]
I just have a question: if we paginate the result, how can we ensure all key is reading?

For example,
We have key a, d, f in revision 1.
While reading [d, f], a new key b is inserted as revision 2. Then a new key g is inserted as revision 3.
After reading [f, g], the latest revision will be 3, so the b is lost.

Please correct me if I am wrong.

**Comment by wfnuser** [comment]
> I just have a question: if we paginate the result, how can we ensure all key is read?
> 
> For example,
> We have key a, d, f in revision 1.
> While reading [d, f], a new key b is inserted as revision 2. Then a new key g is inserted as revision 3.
> After reading [f, g], the latest revision will be 3, so the b is lost.
> 
> Please correct me if I am wrong.

I think it will be acceptable? It will be the same as we read before we insert the new key?

**Comment by spacewander** [comment]
Previously, we can use `watch` to catch up the change since the new key has higher revision. Like we read `[a, f]`, and get revision 1, then we watch with revision 1. If we can't read the data at once, there will be race.
