### ISSUE TITLE
chore(kafka-logger): remove semicolon ";" and add blank line 

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2860]
### Issue description

1.Delete the semicolon after this line of code:
[https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L26](https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L26)

2.Two blank lines are required before the line of `return _M`：
https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L185

**Comment by membphis** [comment]
welcome PR ^_^

**Comment by wfnuser** [comment]
This one seems easy too. I would like to have a try!

**Comment by membphis** [comment]
That's nice👍👍
