### ISSUE TITLE
request help: the key of the json in response_body is unordered

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#2862]
### Issue description
In a response body, if the body is in json format, the order of keys in json is unordered.
As a result, when executing test cases, many test cases that define the full response_body content or one that contains multiple keys fail to execute.
As follows
![QQ图片20201127092252](https://user-images.githubusercontent.com/30819887/100400645-348dd180-3092-11eb-86a1-a3a1c4ce8789.png)

### Environment

* apisix version (cmd: `apisix version`):master laster
* OS:centos7
* OpenResty:1.19.3.1-1.el7
* Test::Nginx:0.29

**Comment by tzssangglass** [comment]
It may be that the LuaJIT update in OpenResty:1.19.3.1 has caused the `jsonencode` results to change.
This problem is fixed in apisix with the
PR (no merge to master yet): https://github.com/apache/apisix/pull/2768

Temporary Fix: Reduce the version of OpenResty.

**Comment by spacewander** [comment]
#2768 can't be merged because there is a problem about the GitHub Action.
