### ISSUE TITLE
request help: Is there a plug-in that acts on the response phase？

### ISSUE THREAD

**Issue by 1746631764** [apache/apisix#2863]
### Issue description
I want to make a response message encryption plug-in，but I don't know if the plug-in can act on the response phase alone. Besides, is there such a response phase?Are there any relevant documents that can be used for reference？

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
You can take a look at https://github.com/apache/apisix/blob/master/apisix/plugins/response-rewrite.lua
