### ISSUE TITLE
feat: Load config with different environment 

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#2873]
### Issue description
We load config.yaml with static name ,but for different environment we can add different configuration, such as etcd  ip address, plugins . I think we can use "env" environment  to load different configuration. For example when the env is beta, we can add "beta-config.yaml" first and then load "config.yaml".

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
This should be done.
See https://github.com/apache/apisix/blob/master/doc/profile.md

**Comment by gy09535** [comment]
> This should be done.
> See https://github.com/apache/apisix/blob/master/doc/profile.md

Got it.
