### ISSUE TITLE
request help: use the disable property to disable plugin

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#2882]
### Issue description

Should we update plugins' docs to use the `disable` property instead of omitting the plugin's data to disable that plugin? This could prevent lost plugin's data when disabling it.

e.g https://github.com/apache/apisix/blob/master/doc/plugins/api-breaker.md#disable-plugin

### Environment

* apisix version (cmd: `apisix version`): No
* OS: No

**Comment by membphis** [comment]
We can add a new section about this way, add a reference to the doc of `plugin`.

**Comment by spacewander** [comment]
Isn't this behavior broken now? Add a disable field doesn't trigger the `destory` method of the plugin. And re-enable a plugin doesn't the `init` method.

**Comment by spacewander** [comment]
Better not mention this experimental feature in the doc.

**Comment by spacewander** [comment]
OK, I was misled right now. It is **disable a plugin for a route/service**, not **disable a plugin**. We should clarify it in the doc. The current doc mess `enable / disable a plugin for a route/service` with `enable / disable a plugin`, and many people are mislead.

**Comment by spacewander** [comment]
I think the plugins' doc need to be rewritten to show the difference. There is no need to show the `disable a plugin for a route/service` in every doc since they are similar.

**Comment by juzhiyuan** [comment]
This PR[1] would depend on this feature, related issue [2]

[1] https://github.com/apache/apisix-dashboard/pull/898
[2] https://github.com/apache/apisix-dashboard/issues/495

**Comment by spacewander** [comment]
Done.
