### ISSUE TITLE
request help: 配置 jwt-auth 插件 获取 token的时候报错

### ISSUE THREAD

**Issue by wenlincheng** [apache/apisix#2883]
### Environment

* apisix version (cmd: `apisix version`):2.0
* OS:MacOS

`
2020/11/28 06:48:51 [error] 42#42: *16841 lua entry thread aborted: runtime error: unknown reason
stack traceback:
coroutine 0:
	[C]: in function 'error'
	/usr/local/apisix//deps/share/lua/5.1/resty/jwt.lua:465: in function 'get_secret_str'
	/usr/local/apisix//deps/share/lua/5.1/resty/jwt.lua:493: in function 'sign'
	/usr/local/apisix/apisix/plugins/jwt-auth.lua:209: in function 'handler'
	/usr/local/apisix/apisix/api_router.lua:107: in function 'handler'
	/usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:730: in function 'dispatch'
	/usr/local/apisix/apisix/api_router.lua:133: in function 'match'
	/usr/local/apisix/apisix/init.lua:373: in function 'http_access_phase'
	access_by_lua(nginx.conf:174):2: in main chunk, client: 172.20.0.1, server: , request: "GET /apisix/plugin/jwt/sign?key=pikaman HTTP/1.1", host: "127.0.0.1:9080"

`

配置 jwt-auth 插件 获取 token的时候报这个错是什么原因呢 运行以下命令
curl http://127.0.0.1:9080/apisix/plugin/jwt/sign?key=pikaman -i

**Comment by tzssangglass** [comment]
Please describe the steps in detail, including configuring the consumer, configuring the jwt plugin, and attaching configuration parameters for easy reproduction.
In addition, please use English.

**Comment by idbeta** [comment]
@wenlincheng Can you provide more detailed steps?
