### ISSUE TITLE
[DISCUSS]:  requires a doc to display secondary endpoints in apisix

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#2889]
I found that some admin API provided by apisix are not found in any documentation, such as
`/apisix/admin/plugins/list`,  so do we need a doc to keep track of the admin API that is nowhere to put?

**Comment by moonming** [comment]
sure，welcome pr

**Comment by tzssangglass** [comment]
ok, i will.
#2308

**Comment by spacewander** [comment]
Done.
