### ISSUE TITLE
quickstart 403

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#2900]
i use quickstart https://github.com/apache/apisix/blob/master/doc/getting-started.md,but it return 403
i used docker (windows)
apisix version (cmd: apisix version):2.0

```
2020/11/30 12:08:16 [error] 52#52: *6 [lua] config_etcd.lua:448: failed to fetch data from etcd: /usr/local/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:149: attempt to concatenate local 'err' (a nil value)
stack traceback:
	/usr/local/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:149: in function 'new'
	/usr/local/apisix/apisix/core/config_etcd.lua:416: in function </usr/local/apisix/apisix/core/config_etcd.lua:414>
	[C]: in function 'xpcall'
	/usr/local/apisix/apisix/core/config_etcd.lua:414: in function </usr/local/apisix/apisix/core/config_etcd.lua:405>,  etcd key: /apisix/routes, context: ngx.timer
```

**Comment by cverdela** [comment]
curl -X GET \
  http://127.0.0.1:9080/apisix/admin/services/ \
  -H 'cache-control: no-cache' \
  -H 'postman-token: 7430832d-b372-4a9c-03f1-94cbbc9705e9' \
  -H 'x-api-key: edd1c9f034335f136f87ad84b625c8f1'

using postman

**Comment by spacewander** [comment]
Should be fixed by https://github.com/api7/lua-resty-etcd/pull/92/files.
You can wait for the ongoing v2.1 release and try again (or try the master branch).
