### ISSUE TITLE
bug: use openid-connect plugin  https error

### ISSUE THREAD

**Issue by lihansir** [apache/apisix#2908]
### Environment

* apisix version: 2.0
* OS: Centos7

### Minimal test code / Steps to reproduce the issue
1.use apisix-dashboard, create a route
2.enable openid-connect plugin, and fill in discovery、introspection_endpoint such as "https://xxxxx/oidc/.well-known/openid-configuration"、"https://xxxxx/oidc/token/introspection"
3.use postman to test the configured routing address

### What's the actual result? (including assertion message & call stack if applicable)
Http response status is 401,and the apisix log file has some error

   /usr/local/apisix/logs/error.log:
       2020/12/01 04:14:54 [error] 43#43: *573137 [lua] openidc.lua:502: call_token_endpoint(): accessing introspection endpoint (https://xxxxx/oidc/token/introspection) failed: 20: unable to get local issuer certificate, client: 10.10.10.10, server: , request: "GET / HTTP/1.1", host: "10.10.10.10:30794"
2020/12/01 04:14:54 [error] 43#43: *573137 [lua] openid-connect.lua:152: phase_func(): failed to introspect in openidc: accessing introspection endpoint (https://xxxxx/oidc/token/introspection) failed: 20: unable to get local issuer certificate, client: 10.10.10.10, server: , request: "GET / HTTP/1.1", host: "10.10.10.10:30794"

### What's the expected result?
I hope openid-connect plugin can support https

**Comment by spacewander** [comment]
The error message shows that APISIX doesn't trust the server's certificate.
What certificate used by https://xxxxx/oidc/token/introspection?

**Comment by lihansir** [comment]
If you have anything to offer, please feel free to contact

**Comment by lihansir** [comment]
![image](https://user-images.githubusercontent.com/44010674/100721701-9fc10600-33fa-11eb-8641-237a34245abf.png)

**Comment by lihansir** [comment]
![image](https://user-images.githubusercontent.com/44010674/100721771-be270180-33fa-11eb-91f5-7a3901e108d0.png)

**Comment by spacewander** [comment]
Interesting. Is the `https://xxxxx/oidc/token/introspection` can be accessed publicly? I guess your machine may miss the root CA or intermediate certificate for Let's Encrypt. But since this is an environment problem, I can not do anything.

**Comment by lihansir** [comment]
Can I ignore the verification of certificates? How to do it？

**Comment by lihansir** [comment]
I've done it myself

1、Install the necessary dependencies
        yum install ca-certificates
        update-ca-trust
2、Rename certificate
        cp /etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-lua.pem
3、Modify the configuration file of nginx, config path : /usr/local/apisix/conf/nginx.conf
        Add the following to the "http" tag：
        lua_ssl_trusted_certificate '/etc/ssl/certs/ca-lua.pem’;
4、openresty -p /usr/local/apisix -s reload

![image](https://user-images.githubusercontent.com/44010674/100756849-9e0e3700-3428-11eb-91ec-4dee251cb1b2.png)
