### ISSUE TITLE
request help: balancer阶段的插件在什么时候执行

### ISSUE THREAD

**Issue by comedown** [apache/apisix#2909]
### Issue description
我在example-plugin下面加了balancer方法，但是没有执行

function _M.balancer(conf, ctx)
    core.log.info("plugin balancer phase, conf: ", core.json.encode(conf))
    core.log.info(" ctx: ", core.json.encode(ctx, true))
end

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS: MacOS 10.15.7

**Comment by spacewander** [comment]
Balancer phase is not supported yet.
