### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#2915]
### Issue description
How do I make different routes use different Apikeys 
for example，tom can access route A ，john can  access route B
### Environment

* apisix version (cmd: `apisix version`):2.0
* OS:docker

**Comment by membphis** [comment]
you can take a look at this plugin: https://github.com/apache/apisix/blob/master/doc/plugins/consumer-restriction.md

**Comment by cverdela** [comment]
thanks
