### ISSUE TITLE
request help: how to validates the requests by user

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#2916]
### Issue description
how to validates the requests by user
for example, User A post URL with body 
`cpu_load_short,host=server01,USER=A value=0.64 1434055562000000006`
（influxdb tag）
body must with USER=A not B

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS:docker

**Comment by idbeta** [comment]
I do not understand your question very well, can you provide more detail? @cverdela

**Comment by cverdela** [comment]
for example,  User A post xxxURL with body
cpu_load_short,host=server01,USER=A value=0.64 1434055562000000006
IF User B post URL with body
cpu_load_short,host=server01,USER=A value=0.64 1434055562000000006
should be error

**Comment by nic-chen** [comment]
@cverdela maybe you could try plugin hmac-auth
