### ISSUE TITLE
request help: How to use OIDC plugin correctly

### ISSUE THREAD

**Issue by lihansir** [apache/apisix#2921]
### Issue description
I created a router, and use the oidc plugin
1、Currently, only bearer_only is true, I carry an Authorization bearer token  Header, which can be verified and accessed normally。
     But when the bearer_only is false, it always redirects to the page I set up, but can not be verified and accessed normally。

2、When a request didn't carry an Authorization bearer token  Header or the token is error
         when the bearer_only is true, it always redirects to 401 page, but can't  redirects to the page I set up。How can I do?

Or have more detailed documentation for me about oidc plugin
      
### Environment

* apisix version: 2.0
* OS: Centos7

**Comment by spacewander** [comment]
CC @moonming

**Comment by spacewander** [comment]
> 2、When a request didn't carry an Authorization bearer token Header or the token is error
when the bearer_only is true, it always redirects to 401 page, but can't redirects to the page I set up

Isn't this expected? Don't have a correct token, reject with 401.

> But when the bearer_only is false, it always redirects to the page I set up, but can not be verified and accessed normally

I am not quite understand what you mean. Could you provide more details so that we can reproduce it at our side?

**Comment by lihansir** [comment]
> 2、When a request didn't carry an Authorization bearer token Header or the token is error
> when the bearer_only is true, it always redirects to 401 page, but can't redirects to the page I set up

why didn't redirects to the page I set up
![image](https://user-images.githubusercontent.com/44010674/100831958-c8e8a180-34a1-11eb-9593-16a264048292.png)
