### ISSUE TITLE
bug: missing ssl cert for ssl

### ISSUE THREAD

**Issue by backnero** [apache/apisix#2923]
### Issue description
```
/usr/local/openresty/luajit/bin/luajit: /usr/bin/apisix:256: missing ssl cert for ssl
stack traceback:
[C]: in function 'error'
/usr/bin/apisix:256: in function </usr/bin/apisix:150>
/usr/bin/apisix:419: in main chunk
[C]: at 0x00404d60

```

No configuration has been modified. After re-pulling the 2.0 image deployment from 5 pm on December 1st, this error occurred and it failed to start

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS: dockerhub centos v2.0 apisix
rancher + K8s 
image : apache/apisix:2.0-centos

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by backnero** [comment]
![image](https://user-images.githubusercontent.com/21979871/100828604-78217a80-349a-11eb-9ec5-b9b965a7e4c6.png)
Browser access tips

**Comment by souzens** [comment]
i tried change ssl enable to "false" in config.yaml ，and apisix is no longer supported https access .

**Comment by idbeta** [comment]
@gxthrj look at this issue if you have time

**Comment by backnero** [comment]
> i tried change ssl enable to "false" in config.yaml ，and apisix is no longer supported https access .
> 
> look config-default.yaml ，add ssl config below
> # ssl_cert: /path/to/ssl_cert
> # ssl_cert_key: /path/to/ssl_cert_key

If it is set to false, does not support https refer to adminapi or all https requests? Because I set up multiple domain names and certificates through sni. If ssl is set in config, should there be multiple certificates or one certificate?

**Comment by backnero** [comment]
The same configuration, image. I have used it for nearly half a month. During the period, the application will be restarted regularly, and this error did not appear. This error began to appear after the afternoon of December 1st. I don't know why.

**Comment by backnero** [comment]
```
2020/12/02 07:20:29 [warn] 14#14: *10 [lua] init.lua:262: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer
2020/12/02 07:20:29 [error] 14#14: *10 [lua] init.lua:283: sync_local_conf_to_etcd(): failed to set plugins: connection refused, context: ngx.timer
2020/12/02 07:20:32 [error] 14#14: *234 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
2020/12/02 07:20:33 [error] 15#15: *363 [lua] exporter.lua:284: handler(): prometheus: plugin is not initialized, please make sure  'prometheus_metrics' shared dict is present in nginx template, client: 127.0.0.1, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "gateway.default.svc.cluster.local:9080"
2020/12/02 07:20:35 [error] 14#14: *495 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
2020/12/02 07:20:38 [error] 14#14: *742 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
2020/12/02 07:20:41 [error] 14#14: *991 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
2020/12/02 07:20:44 [error] 14#14: *1239 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
2020/12/02 07:20:47 [error] 14#14: *1486 [lua] client.lua:92: reportServiceInstance(): Instance report fails, connection refused, context: ngx.timer
```
Error in error.log

I use yaml as the configuration center

**Comment by backnero** [comment]
![image](https://user-images.githubusercontent.com/21979871/100841675-94311600-34b2-11eb-87bc-93efc876c39d.png)
V2.0 image is updated

**Comment by membphis** [comment]
@gxthrj do you have time to look at this issue?

**Comment by gxthrj** [comment]
I try to reproduce in 2.0-centos.

**Comment by gxthrj** [comment]
Oops, in k8s or in docker can not reproduce.
![image](https://user-images.githubusercontent.com/4413028/100866767-1d0c7980-34d4-11eb-9d19-57e836d7bc7d.png)

**Comment by backnero** [comment]
Can you roll back the last submitted docker image in v2.0

**Comment by backnero** [comment]
Does the 2.1 update affect the docker image in the hub? I see that the 2.1 version of the docker image is the same size as the 2.0 version of the docker image

![image](https://user-images.githubusercontent.com/21979871/100952202-09502a00-354b-11eb-8461-e171b0de7c54.png)

**Comment by Hcreak** [comment]
I may have found the reason. I specified the SSL certificate. Before that, I don’t need to specify it at startup.
