### ISSUE TITLE
optimization: string concatenation in sls-logger.lua

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2930]
### Issue description

The string concatenation in sls-logger.lua is inefficient, we should optimize it.

![image](https://user-images.githubusercontent.com/10428333/100850370-afa21e00-34be-11eb-86ee-85d029d8c234.png)

https://github.com/apache/apisix/blob/master/apisix/plugins/sls-logger.lua#L135

**Comment by gy09535** [comment]
Please give some performance testing to prove use string concatenation is not inefficient.

**Comment by membphis** [comment]
steps:

- use lua table to cache items
- call table.concat

**Comment by tokers** [comment]
> Please give some performance testing to prove use string concatenation is not inefficient, I have do the performance test for sls log ,can not find any inefficient issue.

This is a classical bad practice for string concatenation. Just see the following snippet to benchmark it.

```lua
local function concat_100000x_way1(s)
    local t = ""
    for i = 1, 50000 do
        t = t .. s
    end

    return t
end


local function concat_100000x_way2(s)
    local t = {}
    for i = 1, 50000 do
        t[i] = s
    end

    return table.concat(t)
end


local function bench(func, s)
    local s = os.time()
    func(s)
    print("cost time: ", os.time() - s)
end


bench(concat_100000x_way1, string.rep("haha", 50))
bench(concat_100000x_way2, string.rep("haha", 50))
```

**Comment by gy09535** [comment]
> > Please give some performance testing to prove use string concatenation is not inefficient, I have do the performance test for sls log ,can not find any inefficient issue.
> 
> This is a classical bad practice for string concatenation. Just see the following snippet to benchmark it.
> 
> ```lua
> local function concat_100000x_way1(s)
>     local t = ""
>     for i = 1, 50000 do
>         t = t .. s
>     end
> 
>     return t
> end
> 
> 
> local function concat_100000x_way2(s)
>     local t = {}
>     for i = 1, 50000 do
>         t[i] = s
>     end
> 
>     return table.concat(t)
> end
> 
> 
> local function bench(func, s)
>     local s = os.time()
>     func(s)
>     print("cost time: ", os.time() - s)
> end
> 
> 
> bench(concat_100000x_way1, string.rep("haha", 50))
> bench(concat_100000x_way2, string.rep("haha", 50))
> ```

got it

**Comment by gy09535** [comment]
Please assign to me, I will fix it.

**Comment by tokers** [comment]
@gy09535 Assigned to you. :)

**Comment by spacewander** [comment]
Done.
@gy09535 
Next time, please refer this issue with `close #xxx`
