### ISSUE TITLE
request help: Route vars regex match support `~*` and `not` operator

### ISSUE THREAD

**Issue by yangxikun** [apache/apisix#2933]
### Issue description

We are migrating from nginx, and need feature from https://github.com/api7/lua-resty-expr. When will APISIX use it.

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
I am working on it. Too busy to finish it in time.

**Comment by membphis** [comment]
welcome pr @yangxikun

**Comment by yangxikun** [comment]
OK, I can make a PR for this.
Is it right to change https://github.com/api7/lua-resty-radixtree/blob/99f4049ff3520e0f60bb64bb6f2f382947458890/lib/resty/radixtree.lua#L629 to use lua-resty-expr?

**Comment by spacewander** [comment]
Almost done now, see https://github.com/api7/lua-resty-radixtree/pull/78
We just need to update APISIX when the new release is out.

@yangxikun 
You can submit a PR in APISIX  to do this.

**Comment by yangxikun** [comment]
@spacewander Great! Which APISIX branch should I submit PR to?

**Comment by spacewander** [comment]
master branch. See https://github.com/apache/apisix/blob/master/rockspec/apisix-master-0.rockspec
