### ISSUE TITLE
request help: how to get "toolkit.json"?

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#2936]
### Issue description
when I try to write a test case, an error occurs.

```
/usr/local/apisix/t/lib/test_admin.lua:18: module 'toolkit.json' not found:" (req 0)
```

i don't know how to get the `toolkit.json` lib 
### Environment

* apisix version (cmd: `apisix version`): master/latest version
* OS:centos7
* OpenResty:1.17.8.2
* Test::Nginx:0.29

**Comment by Firstsawyou** [comment]
Clone the files in the following project to your local `t/` directory, it should solve the problem.
[https://github.com/api7/test-toolkit](https://github.com/api7/test-toolkit)

**Comment by moonming** [comment]
@Firstsawyou we need to update doc of test.
The root reason is openresty upgrade to 1.19, which not keep the json encode/decode order, so apisix have to do this job by ourself.

**Comment by membphis** [comment]
https://github.com/apache/apisix/pull/2934/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R191

@tzssangglass you can make a try with this PATCH ^_^

**Comment by Firstsawyou** [comment]
> @Firstsawyou we need to update doc of test.
> The root reason is openresty upgrade to 1.19, which not keep the json encode/decode order, so apisix have to do this job by ourself.

Ok i will update later.

**Comment by tzssangglass** [comment]
solved
