### ISSUE TITLE
bug: "unread data in buffer" when getting prometheus metrics

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#2938]
### Issue description
We have the prometheus plugin enabled in global rule and query the /apisix/promethues/metrics endpoint once per second. After upgrading to APISIX 2.0 from 1.5, occasionally we see ERROR logs like this: 
`[error] 36#36: *105103628 [lua] http.lua:951: request_uri(): unread data in buffer, client:, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1"`

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: linux

### Minimal test code / Steps to reproduce the issue
1. We weren't able to reproduce this issue. 

### What's the actual result? (including assertion message & call stack if applicable)
Errors, see above. Not sure if this has any impact on the prometheus metrics?

### What's the expected result?
No errors.

**Comment by spacewander** [comment]
Strange. We just tweak some metrics between 1.5 and 2.0, which should not affect the way to fetch the data. Need a packet capture file and corresponding error log to confirm it.

**Comment by spacewander** [comment]
Probably relative: https://github.com/ledgetech/lua-resty-http/pull/230

**Comment by nanamikon** [comment]
> @nanamikon
> Would you submit a PR to api7/lua-resty-http?

Ok
