### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix#2945]
### Issue description
There is a problem when using apixix2.0. My current structure is that the request goes to nginx first, and then nginx forwards the request to Java (IP: port) on the backend, so that the access interface can return code200. **But I use apisix to replace nginx**, configure the IP and port of the backend service upstream, and all interfaces return code 404. 
The information returned by the browser is similar to this. It seems to be returned by our interface, but it is normal for me to use nginx directly
**return message：**
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Thu Dec 03 14:55:56 CST 2020
There was an unexpected error (type=Not Found, status=404).
No message available

Please help me analyze the reason ，thank you
### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: centos 7

**Comment by tzssangglass** [comment]
please give a minimized example to reproduce this, includes nginx configuration, apisix configuration, and the java interface demo.

**Comment by chenyicai** [comment]
Thank you very much for your reply. My question has already used proxy_ rewrite plugin solved it
