### ISSUE TITLE
discuss: nginx Configuration Template Independence

### ISSUE THREAD

**Issue by onlonely** [apache/apisix#295]
我们知道当前nginx.conf的渲染模版是在bin/apisix文件里面写死的

这在实际使用的时候可能不太方便修改nginx配置,虽然说不建议修改..
但是实际使用过程中需求千变万化,非常有可能需要修改渲染模版..所以希望渲染的模版独立在一个地方.方便修改。

We know that the template of nginx.conf is currently hard code in the `bin/apisix` file.

This may not be very convenient to modify the nginx configuration in actual use, although it is not recommended to modify.

But the actual use of the process of changing demand, it is very likely to need to modify the template. So I hope that the rendering template in a separate place. Easy to modify.

**Comment by liuhengloveyou** [comment]
In fact you can modify it, if you know how.

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/2581
