### ISSUE TITLE
bug: Admin API concurrently created Router ID duplicate

### ISSUE THREAD

**Issue by AloneFire** [apache/apisix#2950]
### Issue description
Admin 接口并发创建 Router 得到的 ID 重复

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: linux

### Minimal test code / Steps to reproduce the issue
1. 
2.
3.

**Comment by idbeta** [comment]
@AloneFire Please describe your operation steps and tools in detail. but why do you want to create routes concurrently?

**Comment by AloneFire** [comment]
原因是我想通过apisix做一个权限网关，routes 配置 是从另一个系统批量同步过来的，同步过程使用了多线程，同步结束后发现数据不一致有几条数据创建返回的ID是重复的

**Comment by Hcreak** [comment]
> 原因是我想通过apisix做一个权限网关，routes 配置 是从另一个系统批量同步过来的，同步过程使用了多线程，同步结束后发现数据不一致有几条数据创建返回的ID是重复的

为什么不同步etcd的数据 或者使用同一个etcd集群呢

**Comment by oldthreefeng** [comment]
> 为什么不同步etcd的数据

@Hcreak  怎么同步, 感觉etcd同步的文档很少见.

**Comment by AloneFire** [comment]
> 为什么不同步etcd的数据 或者使用同一个etcd集群呢
是这样，数据源不是etcd ，同步解决方案呢当然也可以通过操作etcd或者直接就避免并发同步， 但是Admin 接口在并发状态下会出现问题我觉得这就是一个bug

**Comment by AloneFire** [comment]
我测试过老版本，etcd使用v2的接口是没有这个问题的

**Comment by idbeta** [comment]
This problem does exist if use `post` concurrently. 
If you use `put`, there is no problem specifying a different id.

**Comment by AloneFire** [comment]
yes,you're right

**Comment by AloneFire** [comment]
> This problem does exist if use `post` concurrently.
> If you use `put`, there is no problem specifying a different id each time.

yes,you're right

**Comment by oldthreefeng** [comment]
> 我测试过老版本，etcd使用v2的接口是没有这个问题的

能给出测试过程的脚本么. @AloneFire

**Comment by AloneFire** [comment]
@oldthreefeng 这个脚本不太好单独抽出来，就是同样的多线程批量插入，apisix 1.x 不会出现这个问题

**Comment by oldthreefeng** [comment]
> If you use put, there is no problem specifying a different id each time. 

do `put` ~ this is a lot helpful for me.

**Comment by membphis** [comment]
pls provide the steps which can reproduce this issue

**Comment by AloneFire** [comment]
> pls provide the steps which can reproduce this issue

只是简单的并发调用 Admin  POST接口

```python
from gevent import monkey
import gevent

monkey.patch_all()
from pprint import pprint
import requests

APIKEY = "****************************"
APISIX_HOST = "http://127.0.0.1"


def create_route():
    api = f"{APISIX_HOST}/apisix/admin/routes"
    resp = requests.post(api, json={
        "uri": "*",
        "upstream_id": "one upstream_id"
    }, headers={
        "X-API-KEY": APIKEY
    })
    return resp.json().get("node", {}).get("key")


if __name__ == '__main__':
    N = 10
    tasks = [gevent.spawn(create_route) for n in range(N)]
    gevent.joinall(tasks)
    keys = [t.value for t in tasks]
    pprint(keys)
    assert (set([t.value for t in tasks]).__len__() == N)
```

**Comment by membphis** [comment]
@AloneFire need more information:

1. how did you install the apisix? 
2. how did you start the apisix?
3. did you modify the apisix source code?
4. what is the content of file `conf/config.yaml`?

**Comment by membphis** [comment]
@spacewander I use this script reproduce this issue. It seems to be a bug of APISIX. please take a look at this issue

```py
$ cat test.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import grequests

#并发设置route
payloads = {}
for id in range(100):
    payload = {
                "uri": "/test_%s"%id,
                "upstream": {
                    "type": "roundrobin",
                    "nodes": {
                        "127.0.0.1:7000": 1
                    }
                }
    }
    payloads[id]=payload
unsent_request = []
header = {"X-API-KEY":"edd1c9f034335f136f87ad84b625c8f1"}
for id in payloads:
    print(id)
    unsent_request.append(grequests.post("http://127.0.0.1:9080/apisix/admin/routes/" ,json=payloads[id], headers = header))
    responses = grequests.map(unsent_request) # post创建路由不用指定id，否则报错{"error_msg":"wrong route id, do not need it"}
for response in responses:
    print(response.content)
    response.close()
```

Same UUID:

![image](https://user-images.githubusercontent.com/6814606/101469231-71ee3b00-397f-11eb-8208-7717a5525354.png)

**Comment by spacewander** [comment]
https://github.com/apache/apisix/blob/32c7df44cacc28d33abf5c1179b0fc8afa934036/apisix/core/etcd.lua#L277-L287

I think there is a race between read and set.
Maybe we should introduce a `/apisix/_gen_seq` as the id generator.

**Comment by membphis** [comment]
only etcd v3 have this issue, is right? @nic-chen @Yiyiyimu

**Comment by Yiyiyimu** [comment]
Yes the bug is imported in v3. The "manual suffix" in etcd v2 is added on the etcd side to make sure the duplication will not happen. I didn't consider concurrency at that time. 

Agree with @spacewander
