### ISSUE TITLE
request help:  migrate apisix data from 1.5 to 2.x 

### ISSUE THREAD

**Issue by souzens** [apache/apisix#2951]
### Issue description

In our develop environment, it is found that when the etcd data is relatively large, apisix will generate a large number of network requests when reloading the etcd data, (see https://github.com/apache/apisix/issues/2848 )which will currently lead to an increase in the CPU. At first I guessed that it might be because etcd was deployed in the container. I did a migration , move etcd to ECS, but the situation did not get better. Instead, when the route rules were updated, the request time of apisix would also increase.

In view of the above situation, I decided to upgrade the version of the develop environment apisix from 1.5 to 2.0 and re-tested. According to the suggestions given by the README, the data of etcd v2 needs to be migrated to etcd v3. In the actual operation, I found The data structure between 1.5 and 2.0 is different, which makes this test unable to continue.

Due to the removal of mysql, some fields of etcd do not exist under 1.5, missing fields such as name , create_time , update_time (this does not affect the use of dashboard and apisix)

The important thing is that the data structure of node under upstream has changed, as shown in pic
![image](https://user-images.githubusercontent.com/35559209/101001437-1811fd80-359a-11eb-97c3-00177f24ce6e.png)

Obviously, this migration requires data structure correction, so I terminated the migration plan.

I would like to ask for help to the apisix team if there is an official manual for upgrading apisix 1.5 to 2.0. There may be many individuals or companies with the same needs.

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos

**Comment by spacewander** [comment]
Both data structures of `upstream.nodes` are supported under APISIX 2.0.
