### ISSUE TITLE
ctx.var.upstream_addr may be separated by commas.

### ISSUE THREAD

**Issue by whl739** [apache/apisix#2954]
### Issue description
See code in `apisix/balancer/ewma.lua`:
```
local function _ewma_after_balance(ctx, before_retry)
    if before_retry then
        -- don't count tries which fail to complete
        return nil 
    end 

    local response_time = tonumber(ctx.var.upstream_response_time) or 0
    local connect_time = tonumber(ctx.var.upstream_connect_time) or 0
    local rtt = connect_time + response_time
    local upstream = ctx.var.upstream_addr

    if not upstream then
        return nil, "no upstream addr found"
    end 

    return get_or_update_ewma(upstream, rtt, true)
end
```

Both var `upstream_response_time` and `upstream_addr` may  be separated by commas,  it will cause unexpected result.
And if openresty is not patched with `lua-var-nginx-module`, these times are all 0.

**Comment by spacewander** [comment]
PR is welcome! The value is 0 because `tonumber("xxx")` is nil.

**Comment by whl739** [comment]
There's another issue here, ctx.var will cache the result, see case:
if upstream fails, balancer phase will enter multi times, a balancer algorithm may want to update upstream status(e.g. response time), but `ctx.var.upstream_xxx`'s value is the first one.

**Comment by spacewander** [comment]
I think there are two solution
1. use `ngx.var` instead
2. explicitly clear the cache before retrying

What about your opinion? @membphis

**Comment by membphis** [comment]
2th is better for me

**Comment by spacewander** [comment]
I look through the code and find that we don't use `ctx.var.upstream_xxx` in balancer phase. As there is nothing to purge, we can simply leave a comment.
