### ISSUE TITLE
bug: there is an error message when starting apisix 2.1

### ISSUE THREAD

**Issue by wfgydbu** [apache/apisix#2957]
### Issue description
A runtime error occurs when starting apisix at the first time. 

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS: Centos 7.6

### Minimal test code / Steps to reproduce the issue
1. Starting with a clean environment, run `make deps`, `make init`, and `make run`
2. Find an error message in `error.log` with log level `info`.

### What's the actual result? (including assertion message & call stack if applicable)
![image](https://user-images.githubusercontent.com/9432753/101110779-b2af2280-3614-11eb-8972-324178e458d7.png)

### What's the expected result?
Nothing

**Comment by wfgydbu** [comment]
I've tried to locate it by adding some `core.log.info(...)`

Find the root statement is at https://github.com/apache/apisix/blob/master/apisix/core/etcd.lua#L188

Trying to call `etcd_cli:set()` with key `/apisix/plugins` and value of plugins name list (mine is  `[{"name":"echo"}]`) and failed.

the current logic `if not res` cannot detect this failure, because the `error` field stays inside the `res` body.

**Comment by spacewander** [comment]
Look like your lua-resty-etcd library is too old. From the code I guess you are using version < v1.2, but the APISIX 2.1 requires v1.4.2.

You need to reinstall the dependency.

**Comment by wfgydbu** [comment]
Thanks! I'll take a look.

**Comment by wfgydbu** [comment]
Problem solved, thanks again.
