### ISSUE TITLE
bug: missing upstream configuration in Route or Service

### ISSUE THREAD

**Issue by jaredhuang** [apache/apisix#2960]
### Issue description
when i start the limit-req  plugin ,I set:  burst  1 ,key remote_addr  ,rate 1 ,rejected_code 503
I access my web site ,sometimes get 503 ,  sometimes get 500 ,
and i look the error.log ,i get 
`, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "passport.xxx.com"
2020/12/04 10:47:36 [error] 13542#13542: *185825 [lua] init.lua:527: http_access_phase(): failed to parse upstream: missing upstream configuration in Route or Service, client: 183.62.168.218, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "xxxx.com"
2020/12/04 10:47:38 [error] 13542#13542: *185825 [lua] init.lua:527: http_access_phase(): failed to parse upstream: missing upstream configuration in Route or Service, client: 183.62.168.218, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "xxxx.com"`

route:
`{
    "id": "331277816307910169",
    "create_time": 1606986565,
    "update_time": 1607050029,
    "uris": [
        "/*"
    ],
    "name": "passport-api",
    "methods": [
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "DELETE",
        "OPTIONS",
        "PATCH"
    ],
    "hosts": [
        "passport.xxx.com"
    ],
    "vars": [],
    "plugins": {
        "limit-req": {
            "burst": 2,
            "key": "remote_addr",
            "rate": 2,
            "rejected_code": 503
        }
    },
    "upstream_id": "331277767888864793"
}`

upstreams:
`{
    "id": "331277767888864793",
    "create_time": 1606986536,
    "update_time": 1606986536,
    "nodes": [
        {
            "host": "172.16.35.172",
            "port": 8087,
            "weight": 1
        }
    ],
    "timeout": {
        "connect": 6000,
        "read": 6000,
        "send": 6000
    },
    "type": "roundrobin",
    "name": "passport-api"
}`

### Environment

* apisix version (cmd: `apisix version`):
[root@tx-apisix-01 logs]# apisix  version
2.1
* OS:
[root@tx-apisix-01 logs]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
sometimes get 503 ,  sometimes get 500 ,

### What's the expected result?
get 503 status

**Comment by membphis** [comment]
pls provide the error log when you got 500 response

**Comment by jaredhuang** [comment]
> pls provide the error log when you got 500 response
@membphis ,
`, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "passport.xxx.com" 2020/12/04 10:47:36 [error] 13542#13542: *185825 [lua] init.lua:527: http_access_phase(): failed to parse upstream: missing upstream configuration in Route or Service, client: 183.62.168.218, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "xxxx.com" 2020/12/04 10:47:38 [error] 13542#13542: *185825 [lua] init.lua:527: http_access_phase(): failed to parse upstream: missing upstream configuration in Route or Service, client: 183.62.168.218, server: , request: "GET /api/screen/test/health HTTP/2.0", host: "xxxx.com"`

**Comment by tzssangglass** [comment]
verify that  the matched `router` or the `service` has config the `upstream`, I just do this mistake.

**Comment by moonming** [comment]
@membphis please take a look

**Comment by membphis** [comment]
@tzssangglass please add my QQ: 272995614 

I cannot reproduce your issue. We talk by IM for more detailed information.

**Comment by tzssangglass** [comment]
> @tzssangglass please add my QQ: 272995614
> 
> I cannot reproduce your issue. We talk by IM for more detailed information.

no need, I caused this exception due to my own error and solved it, it was a problem with my configuration parameters.Σ( ° △ °|||)︴

you need @jaredhuang
