### ISSUE TITLE
help~! 如何将 Kong已有业务平滑迁移至 apisix 解决方案？

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#2962]
社区朋友有解决方案。大家多提出来。

**Comment by membphis** [comment]
If you are interested in this topic, welcome to discuss this issue.

**Comment by shuaijinchao** [comment]
We are currently working on a project https://github.com/api7/kong-to-apisix

**Comment by membphis** [comment]
so we can close this issue now ^_^

many thx @shuaijinchao 's cool job
