### ISSUE TITLE
feature(https): support for creating new SSL objects using certificate files.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#297]

**Comment by liuhengloveyou** [comment]
What's this?

**Comment by membphis** [comment]
here is a usage:

```
curl -X POST  -F cert=@test.crt -F key=@test.key -F sni="test.com"  http://myapi.com/admin/ssl/1
```

it is easier to use for the user.

**Comment by spacewander** [comment]
Do we still need to support it in admin API?

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
