### ISSUE TITLE
[DISCUSS] rich command line options to enhance the bin/apisix

### ISSUE THREAD

**Issue by tokers** [apache/apisix#2972]
### Issue description

We have almost finished the first step for refactoring `bin/apisix` (only https://github.com/apache/apisix/pull/2929 is pending), and the next step we should do is introducing a well-designed command line parser (like https://github.com/mpeterv/argparse, which is used by luarocks), refining some necessary command line options, enhancing a higher flexibility.

**Comment by starsz** [comment]
I have the same idea.
I think bin/apisix may contain some options to get config.
How about this? 

`./bin/apisix upstream get u1`
`./bin/apisix consumer get c1`

**Comment by tokers** [comment]
> I have the same idea.
> I think bin/apisix may contain some options to get config.
> How about this?
> 
> `./bin/apisix upstream get u1`
> `./bin/apisix consumer get c1`

That should belong the sub command like config.

```
./bin/apisix config upstream u1
./bin/apisix config consumer c1
```

**Comment by moonming** [comment]
Do we need a new bin file for this tool?

**Comment by tokers** [comment]
> Do we need a new bin file for this tool? 

We'd better to use the current one and keep the backward compatibility.
