### ISSUE TITLE
upstream service parsed by CNAME raises exception

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#2973]
The upstream proxy service is exposed through CNAME, and the domain name is accelerated by Alibaba Cloud. After setting the domain name as upstream,  Apisix will resolve and cache the IP address for the domain name. This resulted in the upstream being unable to be properly proxied.

- [AlibabaCloud Dynamic Route for Content Delivery Network](https://help.aliyun.com/product/64812.html)

**Comment by membphis** [comment]
> Apisix will resolve and cache the IP address for the domain name

parse and cache in lrucache:

https://github.com/apache/apisix/blob/master/apisix/init.lua#L120-L122

and the cache time is 30 sec by default, you can specify a new value:

https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L101

**Comment by dickens7** [comment]
This does not really solve the problem, and it will affect all upstream services after changing `dns_resolver_valid` default value.

I am wondering if I can add a configuration for `dns_no_cache` to upstream to solve this kind of problem.

**Comment by membphis** [comment]
> I am wondering if I can add a configuration for `dns_no_cache` to upstream to solve this kind of problem.

Do you want to resolve the domain in every request? What is the reason for this way? 

As I know, if there is no cache, it will lead to poor performance.

**Comment by dickens7** [comment]
yes this will cause severe performance degration. And this requires further study of th accelearation service provided by different vendors.  just put this issue aside, and i will supplement this later

**Comment by spacewander** [comment]
Now we cache the record according to the TTL. Feel free to reopen it if the problem is still exist.
