### ISSUE TITLE
request help: how to get username of key-auth in my Lua script

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#2976]
### Issue description
how to get username of key-auth in my Lua script
i want Routing path = username
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by spacewander** [comment]
Take a look at https://github.com/apache/apisix/blob/c41aa8534a18f43ef0c3cd6780f106595f9f9b88/apisix/plugins/key-auth.lua#L91-L99

**Comment by spacewander** [comment]
Consider solved as the author didn't reply.
