### ISSUE TITLE
request help: Where can I find apisix-2.1-0.src.rpm ?

### ISSUE THREAD

**Issue by Fuchange** [apache/apisix#2979]
### Issue description

I wanted to build rpm package locally,  But I didn't find where can i get the apisix-2.1-0.src.rpm or .spec file .

Although I can write one myself, I hope it can keep up with the upstream.

If anyone can provide it, it will help a lot. Thanks!

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS:

**Comment by liuxiran** [comment]
cc @moonming @membphis @spacewander

**Comment by moonming** [comment]
here is the rpm file: https://github.com/apache/apisix/releases/tag/2.1
and the build tool is here: https://github.com/api7/build-tools

**Comment by Fuchange** [comment]
@moonming Thanks!
