### ISSUE TITLE
[DISSCUS]:  support `ctx.var` to get service_name and route_name

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#2982]
### Issue description

When using the http-logger plugin, I need to obtain the name value corresponding to the service (for example: `"service_name:$service_name"`). But it is currently not available.
Is it necessary for us to support `ctx.var` to get the value of `service_name`?
By the way, sometimes `route_name` is also obtained, but it is not currently supported.

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS:

**Comment by membphis** [comment]
I think this feature is useful, look nice for me

**Comment by Firstsawyou** [comment]
Assigned to me.
