### ISSUE TITLE
request help:  how does apisix update route table when I add new route on Dashboard UI?

### ISSUE THREAD

**Issue by oneslideicywater** [apache/apisix#2996]
### Issue description

Hello, I'm new to APISIX, what confuse me is that when I add a new route on Dashboard UI, I didn't see corresponding 
rules added in `nginx.conf`。

Given that I know Lua has runtime memory like java, so I guess does apisix receive callback by etcd update event,and store
the whole route table in Lua runtime memory。am I right? 

If that's true, I think community should make a blog post to illustrate the principle when admin updates routes in dashboard UI ,how apisix works to make it take effect under the hood.

**Comment by spacewander** [comment]
You can start reading the code from https://github.com/apache/apisix/blob/c7b198f969967f27c395aa2da8353174a091f246/apisix/http/router/radixtree_uri.lua#L90
