### ISSUE TITLE
get error where deploy ingress on k8s with etcd

### ISSUE THREAD

**Issue by FeynmanLoo** [apache/apisix#2998]
### Environment

* apisix version (cmd: `apisix version`): image: 'apache/apisix:latest'
* OS: centos & k8s 1.18

this is my config.yaml 

`  config.yaml: 
    etcd:
      host:
        - http://192.168.111.110:32789
    apisix:
      admin_key:
        -
          name: "admin"
          key: edd1c9f034335f136f87ad84b625c8f1
          role: admin`

get error when start the deployment of k8s:

`/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:641: failed to classify line:       http://192.168.111.110:32789
stack traceback:
	[C]: in function 'error'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:641: in function 'parsemap'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:504: in function 'parseseq'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:675: in function 'parsemap'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:685: in function 'parsemap'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:735: in function 'parsedocuments'
	/usr/local/apisix/deps/share/lua/5.1/tinyyaml.lua:760: in function 'parse'
	/usr/local/apisix/apisix/cli/file.lua:132: in function 'read_yaml_conf'
	/usr/bin/apisix:157: in function </usr/bin/apisix:150>
	/usr/bin/apisix:419: in main chunk
	[C]: at 0x00404d60`

**Comment by spacewander** [comment]
Use `- "http://192.168.111.110:32789"`. Note the address should be quoted to satisfy the yaml syntax.
