### ISSUE TITLE
doc: How to verify  that APISIX is properly forwarding requests to your service

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#300]

**Comment by shoulda** [comment]
when i post a service to the APISIX ,I don't know how to verify that  APISIX is properly forwarding requests to my service sucessfully.

**Comment by spacewander** [comment]
Just send a request which matches your configured rule?

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
