### ISSUE TITLE
request help: Requirements version

### ISSUE THREAD

**Issue by rinaldou** [apache/apisix#3004]
### Issue description
I want to build apisix on s390x (ibm mainframe). 
For this, i want to be sure of each requirement version to compile on redhat 8. 
etcd = v3.4.13
openresty = ?
luarocks = ?
lua-devel = ?

### Environment
s390x
* apisix version (cmd: `apisix version`): latest
* OS: redhat 8

**Comment by spacewander** [comment]
Use `5.1` for `lua-devel`. For the rest, use the latest version.
