### ISSUE TITLE
feat: enable the SSL feature in DP by default

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3005]
APISIX version: `2.1`

It not a good idea to disable the SSL feature by default, and it is not easy to enable this feature.
we should enable it by default.

Then we can use the placeholder certificate, and then APISIX can start normally. 

![image](https://user-images.githubusercontent.com/6814606/101640476-83ad0c80-3a6b-11eb-992f-741eef521ad1.png)

**Comment by membphis** [comment]
@Yiyiyimu do you have time handle this issue?

**Comment by Yiyiyimu** [comment]
Hi @membphis So do we use the original test certificate as the placeholder? If that is the case, I think we could directly revert the whole PR.

**Comment by membphis** [comment]
we can copy the test certificate file as the placeholder. and the file name should contain the keyword `placeholder`.

so we do not need to revert the whole PR.

**Comment by Yiyiyimu** [comment]
Got it thx! Do we still put the copied certificates in `conf/cert`?

**Comment by membphis** [comment]
> Got it thx! Do we still put the copied certificates in `conf/cert`?

confirm with this
