### ISSUE TITLE
request help: flamegraph

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix#3007]
### Issue description
I want to know how to show specific functions in the flamegraph，I use the perf, because systamp has some version problem with kernel.
perf record -F 99 -p 37 -g -- sleep 60
37 is my nginx_worker process's uid 
I find my flamegraph seems can't show the lua function.

![image](https://user-images.githubusercontent.com/42988300/101715805-0cad5d80-3ad7-11eb-8d60-ff9c35d4c97a.png)

My leader watched the video in bilibili organized by cloud native community ，he hope I can get the flamegraph like @membphis did. Can you give me some help. 

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by ziyou434** [comment]
About systemtap
```
stap-prep

...
package kernel-4.14.198-152.320.amzn2.x86_64 is not installed
package kernel-devel-4.14.198-152.320.amzn2.x86_64 is not installed
package kernel-debuginfo-4.14.198-152.320.amzn2.x86_64 is not installed

```
I can't get these rpm in the internet, so I can't use systemtap.

**Comment by membphis** [comment]
the systemtap need the `kernel` debuginfo

**Comment by ziyou434** [comment]
> the systemtap need the `kernel` debuginfo

But I can't search out those packages in any mirrors，it's the problem. 
And linux kernel version is decided by contianer, I don't known what I can do.

**Comment by spacewander** [comment]
Maybe you can contact AWS since the Amazon Linux 2 is their OS.
