### ISSUE TITLE
request help: About OIDC plugin

### ISSUE THREAD

**Issue by hyt05** [apache/apisix#3014]
### Issue description

Hello Team,
I was trying to implement the service to service call via plugin authentication.
I expect the plugin will use client_credential grant flow and get me a bearer token which I will use to call the required service. There should not be any user interaction in authentication process. It should be with client id & secret only.

Do you know if plugin supports this behaviour? If yes, can you please help me configure it?

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: Centos7.8

**Comment by spacewander** [comment]
I think you need the ongoing PR: https://github.com/apache/apisix/pull/2903 to satisfy your requirement.
