### ISSUE TITLE
feat: support to export the JSON schema of APISIX via `CLI`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3022]
discuss mail:
https://lists.apache.org/thread.html/rb1c19fe9b6e51ede3b5aead122e2bcd4de6249f42b971eabfb8a79ac%40%3Cdev.apisix.apache.org%3E

Because the dashboard project requires schema verification for plug-ins,
upstreams, etc., and the definition of the schema is written in the Lua
code of Apache APISIX. Therefore, we need a tool to generate a JSON schema
file based on the Lua code of Apache APISIX so that it can be used by the
Go and front-end code of the dashboard project.

If the developer want to sync the JSON schema, he/she should follow this step:

1. export JSON schema file: call `apisix export-jsonschema`, we will get the file `schema.json`
2. copy the file `schema.json` from apisix to the dashboard folder
3. start the dashboard

those steps are much safer. and the dashboard does not need any update.

**Comment by juzhiyuan** [comment]
This tip should be clearly described in Apache APISIX's Documentation, too.

**Comment by tzssangglass** [comment]
when APISIX is not running, can export the JSON schema?

**Comment by spacewander** [comment]
We can't load the plugin schema without loading `ngx.*` stuff. What about doing this in control API (https://github.com/apache/apisix/issues/2798)?

**Comment by tokers** [comment]
> We can't load the plugin schema without loading `ngx.*` stuff. What about doing this in control API (#2798)?

Agree, otherwise the code base of CLI has to be refactored.

**Comment by nic-chen** [comment]
@spacewander, here is an exported data example:

```json
{
    "main": {
        "consumer": {
            "additionalProperties": false,
            "properties": {
                ...
            },
            "required": ["username"],
            "type": "object"            
        },
        "global_rule": {
            ...
        },
        ...
    },
    "plugins": {
        "authz-keycloak": {
            "consumer_schema": {},
            "metadata_schema": {},
            "priority": 0,
            "schema": {},
            "type":{},
            "version": ""
        },
        ...
    }
}
```

I will use it to continue working on the Dashboard first. 

If there is any change, please let me know, thanks!
