### ISSUE TITLE
bug: some typo errors in the document

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#3024]
### Issue description

`https://github.com/apache/apisix/blob/master/doc/plugins/request-validation.md`
![image](https://user-images.githubusercontent.com/7396835/101973220-5a5dcd80-3c71-11eb-9452-b213e833aece.png)
`https://github.com/apache/apisix/blob/master/doc/plugins/http-logger.md`
![image](https://user-images.githubusercontent.com/7396835/101973256-ac065800-3c71-11eb-9516-4e385ce67e77.png)

**Comment by 96RadhikaJadhav** [comment]
@juzhiyuan @idbeta I have created a PR #3030. Please review it and let me know if any other changes required :) .
