### ISSUE TITLE
Can APISIX be used with The C module of Nginx?

### ISSUE THREAD

**Issue by ShenAoScript** [apache/apisix#3033]
### Issue description
If it needs to be used together with C module, what are the precautions?

### Environment

* apisix version (cmd: `apisix version`): 2.0+
* OS: linux

**Comment by spacewander** [comment]
Yes. See https://github.com/apache/apisix/issues/2611

**Comment by spacewander** [comment]
And you can inject custom Nginx configuration via https://github.com/apache/apisix/blob/0222db7bf31e022bd69cc28cdac3b41be09b875f/conf/config-default.yaml#L135

**Comment by ShenAoScript** [comment]
I want to start OpenResty by source code, in order to add custom C modules

**Comment by membphis** [comment]
https://github.com/apache/apisix/issues/2248

you can take a look at this issue @ShenAoScript

**Comment by ShenAoScript** [comment]
@membphis Thanks, it helped me a lot.
Finally, I have a small question. Our organization is using version 1.5 of APISIX as the final solution and may upgrade to 2.0. But none of these versions support custom Nginx configurations. In this case, is there any other way to fix the problem than by upgrading the version?
@spacewander

**Comment by spacewander** [comment]
I suggest you to upgrade the version unless you are good at hacking OpenResty application.

**Comment by ShenAoScript** [comment]
all right, thanks for the answer
