### ISSUE TITLE
request help: how to set cookie path in apisix

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3034]
### Issue description
how to set cookie path in apisix, such as nginx `proxy_cookie_path /demo/ /`

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS:centos7.5

**Comment by spacewander** [comment]
Add this directive to https://github.com/apache/apisix/blob/0222db7bf31e022bd69cc28cdac3b41be09b875f/conf/config-default.yaml#L141?

**Comment by gewei2000** [comment]
> Add this directive to
> 
> https://github.com/apache/apisix/blob/0222db7bf31e022bd69cc28cdac3b41be09b875f/conf/config-default.yaml#L141
> 
> ?

I've added many routes to apisix. I want to change each route cookie path and how to set directive

like this
```
location /demo1/{
         proxy_pass  http://1.1.1.1:8080/demo1/;
         proxy_cookie_path /demo1/ /;
}
location /demo2/{
         proxy_pass  http://1.1.1.1:8080/demo2/;
         proxy_cookie_path /demo2/ /;
}
```

**Comment by gewei2000** [comment]
@spacewander

**Comment by spacewander** [comment]
Maybe you can write a plugin to rewrite Set-Cookie response header.

**Comment by gewei2000** [comment]
> Maybe you can write a plugin to rewrite Set-Cookie response header.

3Q
