### ISSUE TITLE
I configured Apisix to boot on, but apisix needs to wait about one minute after server start successfully

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix#3038]
### Issue description
I configured Apisix to boot on,  but apisix needs to wait about one minute after server start successfully.

The ps message like this:
root       763     1  0 16:26 ?        00:00:00 /usr/local/openresty/luajit/bin/luajit /usr/bin/apisix start
root      1266   763  0 16:26 ?        00:00:00 openresty -p /usr/local/apisix -c /usr/local/apisix/conf/nginx.conf

About 1 minute ago the "/usr/local/openresty/luajit/bin/luajit /usr/bin/apisix start"  process disappear ,then everything is ok.
So how to resolve this problem? I hope start apisix immediately  when the server start.

### Environment
* apisix version (cmd: `apisix version`): v2.0
* OS: centos 7

### What's the expected result?
 I hope start apisix immediately  when the server start.
Thank you

**Comment by spacewander** [comment]
The `apisix start` is required to do some initialization. You could add more log inside to see which part consumes the most time.

**Comment by chenyicai** [comment]
this is the strace message 

**17:04:26.589701 select(6, [5], NULL, NULL, NULL) = 1 (in [5]) <112.756888>**
17:06:19.346871 close(5)                = 0 <0.000187>
17:06:19.347159 shmget(0x72, 1, IPC_CREAT|0444) = 0 <0.000087>
17:06:19.347312 shmat(0, 0, SHM_RDONLY) = 0x7fc0eeb65000 <0.000037>
17:06:19.347402 open("/dev/urandom", O_RDONLY) = 5 <0.000050>
17:06:19.347576 fstat(5, {st_mode=S_IFCHR|0666, st_rdev=makedev(1, 9), ...}) = 0 <0.000040>
17:06:19.347700 read(5, "SnN3\246\254\356\237%\376Y\364\221)\325:p\252\27\331d\212-\232\255\252\214\33\36\254\275v", 32) = 32 <0.000113>
17:06:19.347919 clock_gettime(CLOCK_REALTIME, {1608887179, 348031238}) = 0 <0.000110>
17:06:19.348224 open("/usr/local/apisix/conf/cert/apisix.crt", O_RDONLY) = 6 <0.001111>
17:06:19.349410 fstat(6, {st_mode=S_IFREG|0755, st_size=1667, ...}) = 0 <0.000066>
17:06:19.349594 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc0eeb64000 <0.000038>
17:06:19.349729 read(6, "-----BEGIN CERTIFICATE-----\nMIIE"..., 4096) = 1667 <0.020529>
17:06:19.370640 read(6, "", 4096)       = 0 <0.000057>
17:06:19.370815 close(6)                = 0 <0.000043>
17:06:19.370925 munmap(0x7fc0eeb64000, 4096) = 0 <0.000086>
17:06:19.371187 open("/usr/local/apisix/conf/cert/apisix.key", O_RDONLY) = 6 <0.000063>
17:06:19.371317 fstat(6, {st_mode=S_IFREG|0755, st_size=2459, ...}) = 0 <0.000058>
17:06:19.371427 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc0eeb64000 <0.000040>
17:06:19.371530 read(6, "-----BEGIN RSA PRIVATE KEY-----\n"..., 4096) = 2459 <0.003008>
17:06:19.374714 close(6)                = 0 <0.000071>
17:06:19.374879 munmap(0x7fc0eeb64000, 4096) = 0 <0.000054>
17:06:19.375553 brk(0)                  = 0x2499000 <0.000034>
17:06:19.375641 brk(0x24be000)          = 0x24be000 <0.000034>
17:06:19.376949 mmap(NULL, 131072, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc0eeb38000 <0.000040>
17:06:19.378787 stat("/etc/sysconfig/64bit_strstr_via_64bit_strstr_sse2_unaligned", 0x7fff89d911a0) = -1 ENOENT (No such file or directory) <0.000056>
17:06:19.379268 futex(0x7fc0ee9460d0, FUTEX_WAKE_PRIVATE, 2147483647) = 0 <0.000034>
17:06:19.379396 open("/usr/local/apisix//deps/share/lua/5.1/resty/core.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000056>
17:06:19.379524 open("/usr/local/apisix//deps/share/lua/5.1/resty/core/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000038>
17:06:19.379614 open("/usr/local/apisix/resty/core.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000031>
17:06:19.379688 open("/usr/local/apisix/resty/core/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000034>
17:06:19.379769 open("/usr/local/openresty/site/lualib/resty/core.ljbc", O_RDONLY) = -1 ENOENT (No such file or directory) <0.001287>
17:06:19.381119 open("/usr/local/openresty/site/lualib/resty/core/init.ljbc", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000056>
17:06:19.381243 open("/usr/local/openresty/lualib/resty/core.ljbc", O_RDONLY) = -1 ENOENT (No such file or directory) <0.001269>
17:06:19.382581 open("/usr/local/openresty/lualib/resty/core/init.ljbc", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000565>
17:06:19.383224 open("/usr/local/openresty/site/lualib/resty/core.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000032>
17:06:19.383320 open("/usr/local/openresty/site/lualib/resty/core/init.lua", O_RDONLY) = -1 ENOENT (No such file or directory) <0.000035>
17:06:19.383403 open("/usr/local/openresty/lualib/resty/core.lua", O_RDONLY) = 6 <0.000043>
17:06:19.383513 close(6)                = 0 <0.000032>
17:06:19.383593 open("/usr/local/openresty/lualib/resty/core.lua", O_RDONLY) = 6 <0.000033>
17:06:19.383690 fstat(6, {st_mode=S_IFREG|0644, st_size=616, ...}) = 0 <0.000032>
17:06:19.383774 mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fc0eeb64000 <0.000031>
17:06:19.383850 read(6, "-- Copyright (C) Yichun Zhang (a"..., 8192) = 616 <0.000668>
17:06:19.384571 read(6, "", 4096)       = 0 <0.000036>
17:06:19.384683 close(6)                = 0 <0.000029>

**Comment by membphis** [comment]
Can you provide a reproduction environment or reproduction steps? @chenyicai
