### ISSUE TITLE
request help: how to get cookie obj from response in apisix

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3046]
### Issue description
how to get cookie obj from response in apisix?

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS:centos7.5

**Comment by spacewander** [comment]
Take a look at https://github.com/cloudflare/lua-resty-cookie
and https://github.com/apache/apisix/blob/master/apisix/plugins/response-rewrite.lua

**Comment by gewei2000** [comment]
> Take a look at https://github.com/cloudflare/lua-resty-cookie
 this lib of method only can be parse request cookie, can not parse response cookie to obj, do we have internal method to parse response cookie to obj?

**Comment by spacewander** [comment]
Sorry, it is my mistake.
You can read `Set-Cookie` header directly. AFAIK, there is not internal wrapper for it.
