### ISSUE TITLE
what The meaning of priority？？

### ISSUE THREAD

**Issue by oldthreefeng** [apache/apisix#3052]
### Issue description

"priority": 10,

The meaning of priority？

The higher the number, the higher the priority? 

the same host with different urls .  one priority is 10 ; other is 20。

Which is processed first？  10 or 20 ？ 

### Environment

* apisix version (cmd: `apisix version`): 1.5
* OS: centos 7.9   3.10-1160

**Comment by spacewander** [comment]
The higher the number, the higher the priority

There is a bug in 1.5 which causes the priority doesn't take effect: https://github.com/apache/apisix/pull/2447

**Comment by oldthreefeng** [comment]
@spacewander  thx , this helps me a lot~
