### ISSUE TITLE
request help: prometheus port security problem

### ISSUE THREAD

**Issue by ziyou434** [apache/apisix#3056]
### Issue description
Now prometheus use 9080 port，It's not safe.
APISIX provide a IP Interceptors to ensure safety, but now it's Invalid. #2658 
Port isolation is actually a more reasonable approach, Is there a way to make it leak on other ports?

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS: linux

**Comment by spacewander** [comment]
You should provide an example to prove it is invalid. I tried myself, it works!

**Comment by ziyou434** [comment]
> You should provide an example to prove it is invalid. I tried myself, it works!

emm, example involve some sensitive information, maybe my operator have mistake.
Actually I want to known if  has a way to make it leak on other ports?

**Comment by spacewander** [comment]
No

**Comment by spacewander** [comment]
But we can add it to the TODO list. Maybe finish it in release 2.3?

**Comment by spacewander** [comment]
Currently, please read the doc and solve it with plugin interceptor: https://github.com/apache/apisix/blob/master/doc/plugin-interceptors.md
