### ISSUE TITLE
bug: missing copy the files in `conf/cert`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3057]
the APISIX enabled the SSL by default, PR: https://github.com/apache/apisix/commit/b7325f033ea721307c6b52beb52c85beaf710f28

so we need to copy the files in `conf/cert` too when installing.

We need to update the process:

https://github.com/apache/apisix/blob/a52b5e9b3b00da40705144c868cfe3a67de47b8d/Makefile#L124-L126

**Comment by membphis** [comment]
@Yiyiyimu would you like to fix this issue?

**Comment by Yiyiyimu** [comment]
My bad, missed this part. Thank you for point it out!

BTW, do we have some test to test if `make install` could work correctly and build apisix successfully, like does the test on the dashboard side would detect this problem?
