### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix#3058]
# Use openid-connect
`{"bearer_only":true,"client_id":"harbor","client_secret":"123456","discovery":"http://10.1.68.155:5556/dex/auth","introspection_endpoint_auth_method":"client_secret_basic","logout_path":"/logout","realm":"master","scope":"openid","ssl_verify":false,"timeout":3000}`
# I configured the header 
Authorization
# but error
500 Internal Server Error

**Comment by spacewander** [comment]
Show the backtrack in the error log, and your Authorization header's value?

**Comment by NetRainn** [comment]
error.log



Authorization is JWT token

Did I use UUID?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 中午1:23
收件人:&nbsp;"apache/apisix"<apisix@noreply.github.com&gt;;
抄送:&nbsp;"三年"<1084194568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/apisix] bug:  (#3058)





 
Show the backtrack in the error log, and your Authorization header's value?

**Comment by spacewander** [comment]
We can't see your error.log. Please reply via GitHub.

**Comment by spacewander** [comment]
Closed as lack of response.
