### ISSUE TITLE
doc: how to compile openresty by source code for apisix.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#306]
some guys need this:

```
./configure --with-http_stub_status_module --with-ipv6 --with-http_v2_module --with-http_realip_module
```

**Comment by moonming** [comment]
the best way to install openresty is from rpm, not the source code. we should declare in doc.
And one more thing, openresty has different compilation options in source packages and rpm, which can cause confusion: https://github.com/openresty/openresty-packaging/blob/master/rpm/SPECS/openresty.spec#L169

**Comment by imjoey** [comment]
Hi @membphis @moonming , this issue seems stable. While, in the next few weeks, we will work on building and delivering APISIX, as well as OpenResty, on openEuler, which is yet another open source operating system originated in China. So I guess the compiling docs may be useful in some circumstances. Of course after getting our work done, we will try to contribute ours compiling docs back to APISIX and openEuler communities. Please let me know if you guys have any interests in openEuler. Thanks.

**Comment by membphis** [comment]
> Please let me know if you guys have any interests in openEuler. Thanks.

yes, we are interests in openEuler. I think it is time to write a doc about how to install APISIX and OpenResty by source code.

**Comment by imjoey** [comment]
@membphis,  wow, that's great and would be very helpful. Thank you very
much. I think our team can take part in this job.

**Comment by moonming** [comment]
> > Please let me know if you guys have any interests in openEuler. Thanks.
> 
> yes, we are interests in openEuler. I think it is time to write a doc about how to install APISIX and OpenResty by source code.

Compiling these two software from source code has official documentation. What do we need to do?

**Comment by membphis** [comment]
> Compiling these two software from source code has official documentation. What do we need to do?

Compile and install the source code. If there is an official document, we can refer to the official document link.

Our goal is to write a list of steps to tell developers how to compile and install from source code step by step.

**Comment by moonming** [comment]
I don't think it's our job to tell user how to compile and install
openresty from source code.
And the doc of Apache APISIX is already has.

Thanks,
Ming Wen
Twitter: _WenMing


YuanSheng Wang <notifications@github.com> 于2020年11月18日周三 下午5:12写道：
