### ISSUE TITLE
Not obvious how to report issues

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix#3063]
I could not find any mention of *how* to report issues or submit PRs.
For someone familiar with how GitHub and the ASF work, it is not difficult to find the GH issue URL, but it is not obvious to those who are unfamiliar with GH.

There should be a top-level link pointing to the issue tracker.

**Comment by spacewander** [comment]
CC @moonming

**Comment by moonming** [comment]
Are there examples of other apache projects? This should be a general template

**Comment by spacewander** [comment]
Closed as lack of response.
