### ISSUE TITLE
[DISCUSS] Do we need to keep `k8s_deployment_info` in Upstream?

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#3068]
We originally hoped to save some k8s deployment information so that some third-party tools can maintain Upstream nodes based on this information. 

But at present, few people use it, and it is easy to cause misunderstanding. So I wonder if this part should be removed now.

What do you think?  Thanks.

**Comment by spacewander** [comment]
Look like removing it will be a break change?
https://github.com/apache/apisix/blob/f476d2c3dc68439406a9531fc8b4a2a2d50c1333/apisix/schema_def.lua#L386-L390

**Comment by spacewander** [comment]
This field isn't used by APISIX now. Is there anywhere using it?

**Comment by nic-chen** [comment]
> This field isn't used by APISIX now. Is there anywhere using it?

none in open source projects

**Comment by membphis** [comment]
agree to remove this field
