### ISSUE TITLE
request help: How to get the requested URI and request method in the lua code?

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix#3069]
### Issue description

How should I get the requested URI and request method in the code? For example, I can use `core.request.header(ctx, "Authorization") ` to get the value in the header, But I don't know how to get the requested uri and request method in lua code. 

uri          ->  /user/test
method -> GET 
```
10.10.20.10 - - [17/Dec/2020:21:03:55 +0800] 10.10.10.250:9080 "GET /user/test HTTP/1.1" 200 7452 0.003 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36" 10.10.16.248:32244 200 0.003
```

### Environment

* apisix version (cmd: `apisix version`): `apisix v2.1`
* OS: `CentOS Linux release 7.6.1810 (Core)`

**Comment by membphis** [comment]
you can use `ctx.var.***` to fetch the variable in Nginx, here is the index of variables:

http://nginx.org/en/docs/varindex.html

**Comment by Caelebs** [comment]
Thank you for your reply, I can already get the required parameters

```
    local req_method = ctx.var.request_method
    local req_uri    = ctx.var.request_uri
```
@membphis
