### ISSUE TITLE
request help: How to implement authentication of URL with business parameters？ |  如何实现url附带业务参数鉴权？

### ISSUE THREAD

**Issue by qwxingzhe** [apache/apisix#3080]
### Issue description
场景是，三方携带token访问报告页面，需要鉴权，每个用户有自己的 secret，比如token = report_id . time . md5(report_id . secret . time )，我们想在网关层面对此鉴权，但鉴权的逻辑是一个独立的微服务。

目前实现方案是使用 authz-keycloak 插件，将token_endpoint地址填为自己的鉴权服务地址，微服务中通过获取 Authorization 来鉴权。

但是这样存在一个问题，三方变更url参数后（报告id非自身的），使用之前合法的token依旧可以访问到服务。

能否在 authz-keycloak 中加入或获取url参数，或者有其他方案解决此问题吗？

### Environment

* apisix version (cmd: `apisix version`):2.0-alpine
* OS:centos 7

**Comment by spacewander** [comment]
I am not quite understand what you mean. It seems you want to pass something isn't relative to keycloak protocol in the authorization? If it is, my suggestion is to write your own plugin from authz-keycloak.

**Comment by qwxingzhe** [comment]
> authz-keycloak.

Yes, I can't get the URL parameters through authz-keycloak to meet my full authentication needs. If there is no better solution, I will consider rewriting the authz-keycloak plug-in

**Comment by spacewander** [comment]
Because your auth server is not keycloak, I think it would be better to write your own one based on the authz-keycloak plugin.

**Comment by qwxingzhe** [comment]
![image](https://user-images.githubusercontent.com/7071651/102777238-2601b400-43cb-11eb-8040-9e3370282eab.png)

That's what I want, and if not, I might need to implement it myself

**Comment by spacewander** [comment]
> 
> 
> Because your auth server is not keycloak, I think it would be better to write your own one based on the authz-keycloak plugin.
