### ISSUE TITLE
Question: How to auto upgrade SSL cert?

### ISSUE THREAD

**Issue by yuncai929** [apache/apisix#3083]
apisix使用ssl证书到期,自动延期后.apisix如何自动更新对应的证书

**Comment by juzhiyuan** [comment]
How about acme? I remember we have an issue with this, but I couldn't find it now 😂

**Comment by yuncai929** [comment]
> How about acme? I remember we have an issue with this, but I couldn't find it now 😂

Thank you ask for my question! I use letsencrypt

**Comment by LeungAlvin** [comment]
@yuncai929 请问现在解决了Apisix 证书自动更新/续期的问题了吗？
