### ISSUE TITLE
request help: Support load balance by least connections

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#3086]
### Issue description
Support new feature load balance by least connections.

**Comment by membphis** [comment]
do you mean `ewma`?

https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream

![image](https://user-images.githubusercontent.com/6814606/102990609-9f77de80-4552-11eb-9cab-f0fc9f53f13b.png)

**Comment by moonming** [comment]
not the same thing

**Comment by membphis** [comment]
I search it on google, got it. This is a very useful algorithm.
