### ISSUE TITLE
apisix 可以处理带有冒号的uri吗? 例如这种/v1/books:batchGetBooks

### ISSUE THREAD

**Issue by zhuliquan** [apache/apisix#3090]

**Comment by spacewander** [comment]
Supported.

**Comment by zhuliquan** [comment]
I don't think so, I find some errors
For example:
I set two routes like this:
##route1
{"uris":["/test/v1/files/*"],"name":"get_file1","desc":"get_file1","methods":["GET"],"vars":[],"plugins":{"proxy-rewrite":{"regex_uri":["^/test/v1/files/(.+)","/v1/files/$1"]}},"upstream_id":"333773215308464216"}
##route2
{"uris":["/test/v1/files:listReputationHistories"],"name":"list_reputation_history1","methods":["POST"],"vars":[],"plugins":{"proxy-rewrite":{"uri":"/v1/files:listReputationHistories"}},"upstream_id":"333773215308464216"}

But run command `curl "http://127.0.0.1:9080/test/v1/files:xxxdsadsadxxx" -XPOST -d {"uri":"xxx"}` , It also can return results.
APISIX sames to match '/test/v1/files:xxxdsadsadxxx' to '"/test/v1/files:listReputationHistories'.
