### ISSUE TITLE
request help: plugin openid-connect

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix#3091]
## Can you provide an example for openid-connect
There is too little information ， I didn't test it out
![image](https://user-images.githubusercontent.com/35440615/102771191-76bfdf80-43c0-11eb-8b36-976970a30b7c.png)

## error info
`2020/12/21 19:08:34 [error] 61075#61075: *39637703 connect() to [2401:b180:1:50::f]:80 failed (101: Network is unreachable), client: 10.4.7.66, server: , request: "GET /get/getSomething HTTP/1.1", host: "10.4.6.211:9080"

2020/12/21 19:08:34 [error] 61075#61075: *39637703 [lua] openidc.lua:581: openidc_discover(): accessing discovery url (http://oauth.aliyun.com/.well-known/openid-configuration) failed: network is unreachable, client: 10.4.7.66, server: , request: "GET /get/getSomething HTTP/1.1", host: "10.4.6.211:9080"

2020/12/21 19:08:34 [error] 61075#61075: *39637703 [lua] openid-connect.lua:163: phase_func(): failed to authenticate in openidc: accessing discovery url (http://oauth.aliyun.com/.well-known/openid-configuration) failed: network is unreachable, client: 10.4.7.66, server: , request: "GET /get/getSomething HTTP/1.1", host: "10.4.6.211:9080"
`

**Comment by membphis** [comment]
I think we need more doc for this plugin

**Comment by membphis** [comment]
> " openidc_discover(): accessing discovery url (http://oauth.aliyun.com/.well-known/openid-configuration) failed: network is unreachable"

wrong uri

**Comment by NetRainn** [comment]
不好意思，请问下 ，如果我在这里不配地址，那么在apisix中 open-connect插件会去请求我配置的http://10.1.68.155:5556/dex/.well-known/openid-configuration这个地址中的哪个地址吗?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月23日(星期三) 晚上7:14
收件人:&nbsp;"apache/apisix"<apisix@noreply.github.com&gt;;
抄送:&nbsp;"三年"<1084194568@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/apisix] request help: plugin openid-connect (#3091)





  
" openidc_discover(): accessing discovery url (http://oauth.aliyun.com/.well-known/openid-configuration) failed: network is unreachable"
  
wrong uri

**Comment by membphis** [comment]
@spacewander @moonming I am not familiar with the plugin and need your help

**Comment by spacewander** [comment]
> 
> 不好意思，请问下 ，如果我在这里不配地址，那么在apisix中 open-connect插件会去请求我配置的[http://10.1.68.155:5556/dex/.well-known/openid-configuration这个地址中的哪个地址吗](http://10.1.68.155:5556/dex/.well-known/openid-configuration%E8%BF%99%E4%B8%AA%E5%9C%B0%E5%9D%80%E4%B8%AD%E7%9A%84%E5%93%AA%E4%B8%AA%E5%9C%B0%E5%9D%80%E5%90%97)?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "apache/apisix" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月23日(星期三) 晚上7:14 收件人:&nbsp;"apache/apisix"<apisix@noreply.github.com&gt;; 抄送:&nbsp;"三年"<1084194568@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/apisix] request help: plugin openid-connect (#3091) " openidc_discover(): accessing discovery url (http://oauth.aliyun.com/.well-known/openid-configuration) failed: network is unreachable" wrong uri — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I can't understand what you mean.
