### ISSUE TITLE
Docs: need more details about version control

### ISSUE THREAD

**Issue by thekingofworld** [apache/apisix#3093]
> Version Control: Supports rollbacks of operations.

Is there a more detailed documentation about this feature?
thx for help.

**Comment by spacewander** [comment]
This is not a feature of APISIX, but a feature of etcd which store APISIX's configuration. Since etcd supports revision, you can get the old data and set it back, if it is not compacted. It is not as powerful as git, but is useful under some occasions.

**Comment by thekingofworld** [comment]
understand, thx.
