### ISSUE TITLE
apisix redis cluster distributed limit rate

### ISSUE THREAD

**Issue by cscfamily001** [apache/apisix#3099]
现有apisix插件限流功能都是针对route，现有插件还是自定义插件都没办法获取upstream中的主机ip，因为负载均衡阶段是否请求处理的最后一个阶段，处理请求的插件都在负载均衡之前，在负载均衡之后的阶段只有：处理返回头、返回body和日志。apisix现有插件除了limit-count之外的limit-req、limit-conn都不支持redis-cluster。

**Comment by spacewander** [comment]
> 现有apisix插件限流功能都是针对route，现有插件还是自定义插件都没办法获取upstream中的主机ip

Upstream level limitation is in service mesh scope. Currently we don't have plan to do it in the API gateway.

> apisix现有插件除了limit-count之外的limit-req、limit-conn都不支持redis-cluster

PR is welcome!
