### ISSUE TITLE
test: add TLS testcase in apisix

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#3103]
### Issue description
1. create route_1 with upstream_1
2. create route_2 with upstream_2
3. test client create TLS connection (certificate) with apisix
4. test client request route_1, should access the upstream_1
5. test client request route_2, should access the upstream_2

It should be tested in both openresty 1.19  and openresty 1.17

relate #3079

### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by moonming** [comment]
Can't understand this description

**Comment by moonming** [comment]
any update?
