### ISSUE TITLE
The consumer-restriction plugin using service_id type restriction does not take effect 

### ISSUE THREAD

**Issue by whioue** [apache/apisix#3106]
### Issue description
想要consumer来绑定服务或路由，所以使用consumer-restriction插件来实现，使用这个插件有两种限制类型，一种是使用consumer_name这个没问题，另一种是service_id使用时，发现文档上实例是key-auth认证，这个没问题，但我使用此插件限制basic-auth时发现无法限制成功

### Environment

* apisix version (cmd: `apisix version`):
* OS:

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

**Comment by spacewander** [comment]
Is it solved by https://github.com/apache/apisix/pull/2905? You can try it on the master branch.

**Comment by whioue** [comment]
> [＃2905](https://github.com/apache/apisix/pull/2905)解决了吗？您可以在master分支上尝试。

I tried it on version 2.0 and it seems that it has not been solved for the time being

**Comment by whioue** [comment]
> Is it solved by #2905? You can try it on the master branch.
@spacewander 
I tried it on version 2.0 and it seems that it has not been solved for the time being

**Comment by spacewander** [comment]
I can reproduce with 2.0, but can't reproduce with master branch. The fix is only on the master branch. Can you try the master branch directly? Remember to stop and restart APISIX entirely.

**Comment by whioue** [comment]
> I can reproduce with 2.0, but can't reproduce with master branch. The fix is only on the master branch. Can you try the master branch directly? Remember to stop and restart APISIX entirely.
@spacewander it's solved thank you
