### ISSUE TITLE
类似网关指定的路由或服务请求一个指定服务地址，根据地址定义的参数控制是否通过，并可以将部分参数传递下游？

### ISSUE THREAD

**Issue by ShaoZeMing** [apache/apisix#3115]
### Issue description
我想实现一个网关自定义鉴权的功能，很类似rbac的拓展，但我们并不是用的这套rbac进行认证的，我想请教一下，是否有拓展能个填写自定义的请求地址，可以根据目标服务返回状态判断是否通行，并且可以将访问的数据携带下游服务中。如下图示意：

![image](https://user-images.githubusercontent.com/19376576/103063831-70627b00-45ed-11eb-8d12-f72e79325b38.png)

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by tokers** [comment]
What you said is just like a Webhook feature. Now APISIX doesn't have it, PR's welcome!

**Comment by spacewander** [comment]
Take a look at https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua

**Comment by spacewander** [comment]
Of course, you can't use openid-connect directly as your auth server doesn't implement the OIDC protocol. But you can implement similar thing base on this plugin as your auth server works similar to OIDC protocol.

**Comment by gy09535** [comment]
> ### Issue description
> 我想实现一个网关自定义鉴权的功能，很类似rbac的拓展，但我们并不是用的这套rbac进行认证的，我想请教一下，是否有拓展能个填写自定义的请求地址，可以根据目标服务返回状态判断是否通行，并且可以将访问的数据携带下游服务中。如下图示意：
> 
> ![image](https://user-images.githubusercontent.com/19376576/103063831-70627b00-45ed-11eb-8d12-f72e79325b38.png)
> 
> ### Environment
> * apisix version (cmd: `apisix version`):
> * OS: (cmd: `uname -a`)
> * OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

I have do  the some similar feature,  you should add two plugins,  one is for  define the hook contract , and  when the hook api response, you can restore the message in context. another is the combine plugin which you can combine the message and the  request body with some rules, and then you can set the request to the upstream.

**Comment by spacewander** [comment]
> 
> 
> Take a look at https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua

I find a better one: https://github.com/apache/apisix/blob/master/apisix/plugins/authz-keycloak.lua

**Comment by ShaoZeMing** [comment]
> > ### Issue description
> > 我想实现一个网关自定义鉴权的功能，很类似rbac的拓展，但我们并不是用的这套rbac进行认证的，我想请教一下，是否有拓展能个填写自定义的请求地址，可以根据目标服务返回状态判断是否通行，并且可以将访问的数据携带下游服务中。如下图示意：
> > ![image](https://user-images.githubusercontent.com/19376576/103063831-70627b00-45ed-11eb-8d12-f72e79325b38.png)
> > ### Environment
> > 
> > * apisix version (cmd: `apisix version`):
> > * OS: (cmd: `uname -a`)
> > * OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
> 
> I have do the some similar feature, you should add two plugins, one is for define the hook contract , and when the hook api response, you can restore the message in context. another is the combine plugin which you can combine the message and the request body with some rules, and then you can set the request to the upstream.

谢谢提醒，想观摩观摩，你的开源吗？

**Comment by ShaoZeMing** [comment]
> > Take a look at https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua
> 
> I find a better one: https://github.com/apache/apisix/blob/master/apisix/plugins/authz-keycloak.lua

Thanks, let me see

**Comment by gy09535** [comment]
> > > ### Issue description
> > > 我想实现一个网关自定义鉴权的功能，很类似rbac的拓展，但我们并不是用的这套rbac进行认证的，我想请教一下，是否有拓展能个填写自定义的请求地址，可以根据目标服务返回状态判断是否通行，并且可以将访问的数据携带下游服务中。如下图示意：
> > > ![image](https://user-images.githubusercontent.com/19376576/103063831-70627b00-45ed-11eb-8d12-f72e79325b38.png)
> > > ### Environment
> > > 
> > > * apisix version (cmd: `apisix version`):
> > > * OS: (cmd: `uname -a`)
> > > * OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
> > 
> > 
> > I have do the some similar feature, you should add two plugins, one is for define the hook contract , and when the hook api response, you can restore the message in context. another is the combine plugin which you can combine the message and the request body with some rules, and then you can set the request to the upstream.
> 
> 谢谢提醒，想观摩观摩，你的开源吗？

sure, I should refactor it and the auth server can response JWT , the backend can resolve the JWT to get user info . I think it is a good way to change token to JWT, because of not want to export user info to client.
