### ISSUE TITLE
request help: To get route object and set headers

### ISSUE THREAD

**Issue by Ben0625** [apache/apisix#3116]
### Issue description
I want to get the self-defined parameter serve_name(which corresponds to Route one to one) printed in the 'access.log' by changing access_log_format ($http_serve_name). I want to set this parameter as an attribute in 'lables' of Route when setting a Route. The problem is, how can I get the corresponding Route object in the apisix original code after hitting a route and then set 'serve_name' of lables into the headers so that this attribute will be printed in the 'access.log'?

### Environment

* apisix version: 2.0
* OS: x86_64 GNU/Linux
* OpenResty / Nginx version: openresty/1.17.8.1

**Comment by spacewander** [comment]
Take a look at https://github.com/apache/apisix/commit/bdd00e1f55fd13cd3d2b12656ec1dc2d4e3f6e0b

**Comment by Ben0625** [comment]
> Take a look at [bdd00e1](https://github.com/apache/apisix/commit/bdd00e1f55fd13cd3d2b12656ec1dc2d4e3f6e0b)

Thanks a lot, I find the code in http_access_phase() of 'init.lua' very helpful. I just add one line to set attributes of matched route into headers.
