### ISSUE TITLE
The proxy-rewrite plugin does not support pass nginx's variable within header

### ISSUE THREAD

**Issue by yongboy** [apache/apisix#3117]
## Issue description

I want to pass the nginx's [Embedded Variables](http://nginx.org/en/docs/http/ngx_http_core_module.html#variables) for upstream applications, below is my proxy-rewrite plugin's config:

```json
{
    "headers": {
        "X-AUTH-UID": "$arg_uid"
    },
    "regex_uri": [
        "^/monitor/(.*)",
        "/$1"
    ]
}
```

The test url：

```
curl http://gw.dev/monitor/hello?uid=10001
```

The upstream application got the raw req info below: 

```
GET /hello?uid=10001 HTTP/1.1
Host: gw.dev
X-Real-IP: 172.19.0.1
X-Forwarded-For: 172.19.0.1
X-Forwarded-Proto: http
X-Forwarded-Host: gw.dev
X-Forwarded-Port: 9080
User-Agent: curl/7.64.1
Accept: */*
X-AUTH-UID: $arg_uid

......
```

## Environment

* apisix version : 1.5
* OS: MacOS
* OpenRestyx / Nginx version: nginx/1.17.3

**Comment by spacewander** [comment]
Only constant value is supported.

**Comment by Firstsawyou** [comment]
Assigned to me.

**Comment by BFergerson** [comment]
I believe I'm facing a similar issue. I am trying to use two plugins to create a sort of password-protected area in my application. I was hoping to use the basic-auth plugin for username/password functionality and proxy-rewrite to automatically add the username to the route. For example, rerouting requests to `host:3000` to `host:3000/{username}`.

Is that similar to this issue and would it be solved with work done on this issue?

**Comment by spacewander** [comment]
@BFergerson 
It is another thing since the username is not exposed to `ctx.var` yet. You might need to open a new issue for it.
