### ISSUE TITLE
bug: 下载大文件会断流

### ISSUE THREAD

**Issue by candicandi** [apache/apisix#3120]
### Issue description

apisix代理http下载大文件的时候会断流
### Environment

* apisix version (2.1):
* OS: (centos7.8)
* openresty/1.19.3.1

apisix下载超过500M的文件时会断流，表现为下载下载到约300-500m时流量突然为0

**Comment by tokers** [comment]
@candicandi Could you please provide a reproducible case?

**Comment by OnlyPiglet** [comment]
@candicandi  是不是你的nginx.conf 设置了 send_timeout 过短

**Comment by agile6v** [comment]
The size of the path specified by `proxy_temp_path` directive may be full. Please check the disk where the path is located. By default the path is ${NGINX_PREFIX} + proxy_temp/ . @candicandi

**Comment by membphis** [comment]
ping @candicandi

**Comment by spacewander** [comment]
<img width="723" alt="微信截图_20210105085208" src="https://user-images.githubusercontent.com/4161644/103594361-72a0cf80-4f33-11eb-8e67-b24a14199a77.png">
Solved.

**Comment by zsqcc** [comment]
> <img alt="微信截图_20210105085208" width="723" src="https://user-images.githubusercontent.com/4161644/103594361-72a0cf80-4f33-11eb-8e67-b24a14199a77.png">
> 
> Solved.

how to solve it?
