### ISSUE TITLE
request help: Route中vars不能使用IN操作符

### ISSUE THREAD

**Issue by momo8zero** [apache/apisix#3123]
### Issue description
Route中的vars无法使用"IN"操作符,我看lua-resty-expr文档中是支持的,但使用HTTP请求Admin API 提示格式错误
"=="仅能匹配一个值,有没有匹配多个值,其中一个符合条件即通过的条件?

### Environment

* apisix version (cmd: `apisix version`): v2.1
* OS: (cmd: `uname -a`) centos7.6
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
Could you show us how you send the request to admin API?

**Comment by momo8zero** [comment]
我尝试了这样的方式:
"vars": [
   ["http_token","IN",["1","2"]]
]
但是提示参数不符合规范,
我尝试这样:
"vars": [
   ["http_token","IN","1","2"]
]
保存会成功,但是实际上并没有应用

**Comment by spacewander** [comment]
"vars": [
["http_token","IN",["1","2"]]
]
is the correct way.

The validation has bug. I fix it in https://github.com/apache/apisix/pull/3124.

**Comment by momo8zero** [comment]
> "vars": [
> ["http_token","IN",["1","2"]]
> ]
> is the correct way.
> 
> The validation has bug. I fix it in #3124.

Thank you~~~~!!!
