### ISSUE TITLE
request help: do we support pinpoint?

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3126]
### Issue description
do we support pinpoint?

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: centos7
* OpenResty / Nginx version: 1.19.3.1

**Comment by spacewander** [comment]
We don't support pinpoint. It seems there is not an official / widely-used pinpoint client for OpenResty. Anyway, PR is welcome!

**Comment by gewei2000** [comment]
> We don't support pinpoint. It seems there is not an official / widely-used pinpoint client for OpenResty. Anyway, PR is welcome!

3Q
