### ISSUE TITLE
request help: can't set redis policy in 'limit-count'

### ISSUE THREAD

**Issue by zhuliquan** [apache/apisix#3128]
### Issue description
**error:**
{"error_msg":"failed to check the configuration of plugin limit-count err: failed to validate dependent schema for \"policy\": value should match only one schema, but matches none"}
**my limit-count setting:**
"limit-count": {
            "disable": false,
            "count": 1000,
            "time_window": 60,
            "rejected_code": 503,
            "key": "consumer_name",
            "policy": "redis",
            "redis_host": "XXXXXXXXX",
            "redis_port": "XXXXXX",
            "redis_password": "XXXXXXXX",
            "redis_timeout": 1001
        }

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
The `redis_port` should be integer.

**Comment by Firstsawyou** [comment]
The schema does not match, it seems that redis_port is not an `integer` causing the problem.
