### ISSUE TITLE
Combining basic-auth & proxy-rewrite

### ISSUE THREAD

**Issue by BFergerson** [apache/apisix#3133]
I am trying to use two plugins to create a sort of password-protected area in my application. I was hoping to use the basic-auth plugin for username/password functionality and proxy-rewrite to automatically add the username to the route. For example, dynamically rerouting requests to `host:3000` to `host:3000/{username}`.

Is this something that falls within the functionalities APISIX aims to cover? Is this something I can achieve with a custom plugin?

**Comment by tokers** [comment]
It seems we cannot modify uri based on request headers.

I think maybe we can expand the proxy-rewrite, PR's welcome!

**Comment by spacewander** [comment]
You may need to change proxy-rewrite like what we have done with fault-injection:
https://github.com/apache/apisix/blob/53777519b8261994f34dfd67fc07cc1b97ba2946/apisix/plugins/fault-injection.lua#L85
And use the `consumer_name` as variable name. See:
https://github.com/apache/apisix/blob/53777519b8261994f34dfd67fc07cc1b97ba2946/apisix/core/ctx.lua#L174-L175
