### ISSUE TITLE
bug:  why  does host proxy_write not  support such as ip+port 

### ISSUE THREAD

**Issue by jeesk** [apache/apisix#3136]
### Issue description
when I set  host of proxy_wiite, tell me Invalid plugin data
does not match the regex pattern ^[0-9a-zA-Z-.]+$.  

### Environment

* apisix version  2.1
* apisix dashboard version: 2.2
* OS:  centos 7.8 
* OpenResty openresty/1.19.3.1

### Minimal test code / Steps to reproduce the issue
1.
2.
3.

### What's the expected result?
<img width="895" alt="插件有问题" src="https://user-images.githubusercontent.com/27076817/103168454-54214100-486e-11eb-8f3b-bd8c8872e6ed.png">

**Comment by Firstsawyou** [comment]
Are you talking about the `proxy_rewrite` plugin?  See if the format of the `host` you set is incorrect, the `host` you set needs to meet the prompt regularity.
 For example: `192.168.12.34`.

**Comment by idbeta** [comment]
Now the `host` cannot contain port, but the document do not explain it, I think is a bug. @spacewander

**Comment by membphis** [comment]
ping @jeesk

**Comment by jeesk** [comment]
> Are you talking about the `proxy_rewrite` plugin? See if the format of the `host` you set is incorrect, the `host` you set needs to meet the prompt the regex pattern ^[0-9a-zA-Z-.]+$.
> For example: `192.168.12.34`.

yes

**Comment by membphis** [comment]
we should support this case. @jeesk would you like to submit a PR about this issue?
