### ISSUE TITLE
request help: apisix有类似kong中request transformer插件？

### ISSUE THREAD

**Issue by duliming** [apache/apisix#3148]
### Issue description
我想对下游客户请求的body和header做过滤，重写，目的是隐藏一部分参数，避免暴露给下游客户。看到kong有request Transformer的插件，apisix是否有这样的插件或者方法可以实现？

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`)：centOS 7
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) nginx/1.16.1 openresty/1.19.3.1

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/doc/plugins/response-rewrite.md#attributes

**Comment by duliming** [comment]
Are you sure that response-rewrite can solve my problem?

**Comment by duliming** [comment]
> See https://github.com/apache/apisix/blob/master/doc/plugins/response-rewrite.md#attributes

Are you sure that response-rewrite can solve my problem?
