### ISSUE TITLE
request help: ADD rewrite in apisix, and zipkin does not work

### ISSUE THREAD

**Issue by azura27** [apache/apisix#3155]
### Issue description
Hello,  I wanner to realize the "rewrite" directive in Nginx with plugin manner on APISIX.
But whther I set the priority of zipkin to higher or lower than that of rewrite(401), zipkin pending span does not generate.
Would you please give some advice on this, thanks a lot.

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS: (cmd: `uname -a`)3.10.0-693.21.1.el7.x86_64
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) 1.15.8.3

**Comment by azura27** [comment]
route A rewrite  to B, zipkin plugin add on B is OK, but on A could not work, Is this normal? How can I change zipkin to A to make it effect?

**Comment by spacewander** [comment]
I suggest you to use the plugin `proxy-rewrite` to change the URL. It is quite weird to use Nginx's rewrite with Lua code.

**Comment by azura27** [comment]
I learned this plugin for the last hour and test it, but I found it does not meet my demand, It just change the URI, but not redirect to the new upstream.
For example:
I set a route with uri /temp.htm(B); and the other is /dev/temp.htm(A); and I add proxy-rewrite like below:
method 1: "proxy-rewrite":{"uri":"/temp.htm"}
method 2:"proxy-rewrite":{"regex_uri":["\/dev\/(.*)$","\/$1"]}
both methods cannot get response from upstream of B;
Is this usage is right OR does this plugin support redirect of route?  
Looking forwardx your response, thans again~

**Comment by azura27** [comment]
I also see there is redirect plugin, but it does not support Nginx "rewrite" directive's "last" or "break" flag, Is that right?

**Comment by spacewander** [comment]
> For example:
> I set a route with uri /temp.htm(B); and the other is /dev/temp.htm(A); and I add proxy-rewrite like below:
> method 1: "proxy-rewrite":{"uri":"/temp.htm"}
> method 2:"proxy-rewrite":{"regex_uri":["/dev/(.*)$","/$1"]}
> both methods cannot get response from upstream of B;

Why not set the same upstream for route A & B?

**Comment by azura27** [comment]
I seems OK, maybe I consider too much.
Thanks a lot~
