### ISSUE TITLE
request help: StripPrefix and PrefixPath

### ISSUE THREAD

**Issue by 7error** [apache/apisix#3160]
### Issue description

**StripPrefix: remove prefixes of paths**
```bash
when StripPrefix=2
http://127.0.0.1/user-service/a/user/1  -----> http://127.0.0.1:8080/user/1

when StripPrefix=1
http://127.0.0.1/user-service/a/user/1  -----> http://127.0.0.1:8080/a/user/1

ref  https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-stripprefix-gatewayfilter-factory
```
**PrefixPath is reverse of StripPrefix**
```bash
when PrefixPath=/user
http://127.0.0.1/1  ----->   http://127.0.0.1:8080/user/1

ref https://cloud.spring.io/spring-cloud-gateway/reference/html/#the-prefixpath-gatewayfilter-factory

```

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
You can use proxy-rewrite's regex_uri:
https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md#attributes

**Comment by 7error** [comment]
tks,I found this `https://github.com/apache/apisix/blob/master/doc/getting-started.md#add-a-prefix-to-the-route`, It seems a little clear,I will try this.
