### ISSUE TITLE
request help: 如何使用nacos作为服务发现

### ISSUE THREAD

**Issue by luger1990** [apache/apisix#3162]
目前在技术调用apisix。请问如何使用nacos作为服务发现，直接读取nacos中的服务作为upstream。不用单个去配置后端ip。找了找文档没有看到。麻烦帮忙解答。多谢

**Comment by luger1990** [comment]
刚写完就查到了。。 https://github.com/apache/apisix/blob/1f52c70d841b790a0e4617a3daf53ea3f5b7cdd0/doc/zh-cn/discovery.md#upstream-%E9%85%8D%E7%BD%AE 我先自己研究研究

**Comment by tokers** [comment]
@luger1990 Feel free to ask any questions here :)

**Comment by luger1990** [comment]
> @luger1990 Feel free to ask any questions here :)

请问官网目前是没有实现 nacos 注册中心吗。 我看`/usr/local/apisix/apisix/discovery`没有发现`nacos.lua` 文件

**Comment by starsz** [comment]
Right. Maybe you can try to submit a PR for this.

**Comment by membphis** [comment]
I remembered @moonming write an article, mainly implement it by DNS way.

Here is another one I found by google:

https://www.jxhs.me/2020/11/30/apisix%E4%B8%8Econsul%E6%9C%8D%E5%8A%A1%E5%8F%91%E7%8E%B0%E7%9A%84%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8/
