### ISSUE TITLE
request help: docker build fail

### ISSUE THREAD

**Issue by UnderTreeTech** [apache/apisix#3163]
### Issue description
docker build all-in-one dashboard and get following errors:
`Error: Could not load rockspec file /tmp/luarocks_luarocks-rockspec-apisix-master-0-oKNioa/apisix-master-0.rockspec (Error loading file: [string "/tmp/luarocks_luarocks-rockspec-apisix-master..."]:7: unexpected symbol near '<')
`
How to fix it?

### Environment

* apisix version (cmd: `apisix version`): master
* OS: MacOS Catalina 10.15.7

**Comment by spacewander** [comment]
Duplicate: https://github.com/apache/apisix-docker/issues/88
