### ISSUE TITLE
request help: upstream.lua:57: set_upstream(): upstream node has been specified, cannot be set repeatedly

### ISSUE THREAD

**Issue by json7** [apache/apisix#3164]
### Issue description

Occasionally, an error "upstream node has been specified, can't be set repeatedly" is reported when a configured route is requested
### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`) linux 3.10.0-1127.8.2.el7.x86_64 centos 7
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) nginx version: openresty/1.19.3.1

**Comment by json7** [comment]
I have created two routes, and each route has its own back-end handler. However, I find that once the back-end handler of a route requests another route as an "httpclient", this problem begins to occur

**Comment by spacewander** [comment]
Is there runnable steps to reproduce this issue?

**Comment by json7** [comment]
> Is there runnable steps to reproduce this issue?

I have created two routes, and each route has its own back-end handler. However, I find that once the back-end handler of a route requests another route as an "httpclient", this problem begins to occur

**Comment by spacewander** [comment]
It seems that you have modified the APISIX? Currently APISIX only support using a remote address as the backend(upstream).

**Comment by json7** [comment]
> It seems that you have modified the APISIX? Currently APISIX only support using a remote address as the backend(upstream).

There was no change
example:
routeA:  back-end api (127.0.0.1:9001)
routeB:  back-end api (127.0.0.1:9002)

httpclient(chrome) -> routerA -> 127.0.0.1:9001 ->routerB->error
httpclient(chrome) ->routerB->127.0.0.1:9002  ->success

**Comment by spacewander** [comment]
Interesting. What is your route configuration?

**Comment by spacewander** [comment]
Is it the same as https://github.com/apache/apisix/issues/3079?

**Comment by json7** [comment]
> Is it the same as #3079?

It's not the same problem

**Comment by json7** [comment]
> Is it the same as #3079?

可以加我qq我给您提供复现环境  1210336990

**Comment by json7** [comment]
Yes, it's about the openresty version. I went back to 1.17 and it's normal

**Comment by mcdullbloom** [comment]
I also got the warning "upstream node has been specified, cannot be set repeatedly" and several 404 response as well(the qps is about 800) . I added some logs in set_by_route and udp-logger  and found that apisix forward the request to wrong backend upstream node. I susspect that the api_ctx is polluted but I have no idea why this happen.

PS：we do not use the plugin "traffic-split"

Environment
apisix version (cmd: apisix version): 2.4
OS: (cmd: uname -a) linux 3.10.0-693.el7.x86_64  CentOS Linux release 7.4.1708 (Core) 
OpenResty / Nginx version: (cmd: nginx -V or openresty -V) nginx version: openresty/1.19.3.1
