### ISSUE TITLE
bug: grpc-transcode plugin

### ISSUE THREAD

**Issue by cj2a7t** [apache/apisix#3166]
### Issue description
put /apisix/proto/1 
put /apisix/proto/2
put /apisix/proto/3

delete /apisix/proto/1
delete /apisix/proto/2

curl grpc api exception..

### Environment

* apisix version (cmd: `apache/apisix:2.1-alpine`):
* OS: (cmd: `docker`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

### Minimal test code / Steps to reproduce the issue
apisix started.
`
curl http://${ip}:${port}/apisix/admin/proto/1
{
    "content": "..."
}

curl http://${ip}:${port}/apisix/admin/proto/2
{
    "content": "..."
}

curl http://${ip}:${port}/apisix/admin/proto/3
{
    "content": "..."
}
`
delete 1 and 2 , grpc-transcode exception.

### What's the actual result? (including assertion message & call stack if applicable)
`
	"values": [false, false, false, {
		"key": "\/apisix\/proto\/3",
		"modifiedIndex": 125,
		"value": {
			"content": "syntax = \"proto3\";package site.coderjia.dream.cloud.grpc;message HelloRequest {string firstName = 1;string lastName = 2;}message HelloResponse {string greeting = 1;}service HelloService {rpc hello(HelloRequest) returns (HelloResponse);}",
			"id": "3"
		},
		"clean_handlers": {},
		"createdIndex": 125
	}],
`
![image](https://user-images.githubusercontent.com/70355872/103393168-5c25fd00-4b5c-11eb-88b3-4b37745dde12.png)
protos contains false
![image](https://user-images.githubusercontent.com/70355872/103393200-7d86e900-4b5c-11eb-8848-acc3d26641ef.png)

### What's the expected result?
when I deleted /apisix/proto/1 ,  false placeholders should not be used.

**Comment by spacewander** [comment]
@nic-chen

**Comment by nic-chen** [comment]
thanks for feedback, will fix soon.

**Comment by spacewander** [comment]
Maybe we can use https://github.com/apache/apisix/blob/65579fc45b97b450185e9e6e30aaa596f5bee68e/apisix/core/config_util.lua#L39 to solve the problem.

**Comment by cj2a7t** [comment]
> thanks for feedback, will fix soon.
thanks

**Comment by nic-chen** [comment]
> Maybe we can use
> 
> https://github.com/apache/apisix/blob/65579fc45b97b450185e9e6e30aaa596f5bee68e/apisix/core/config_util.lua#L39
> 
> to solve the problem.

Thanks for tips!
