### ISSUE TITLE
ci: need a better title

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3167]
here is the current list, it is not easy to read.

![image](https://user-images.githubusercontent.com/6814606/103393799-b07eac00-4b5f-11eb-9b43-5582af58bfc9.png)

**Comment by membphis** [comment]
here is the name of Dashboard CI which is better than APISIX:

![image](https://user-images.githubusercontent.com/6814606/103393821-d015d480-4b5f-11eb-83da-eccbfa698cfe.png)

**Comment by membphis** [comment]
discussed with @spacewander , change `build/build` to `test/e2e` should be enough. welcome PR

![image](https://user-images.githubusercontent.com/6814606/103394231-23892200-4b62-11eb-9aca-1d408704e8a4.png)

**Comment by spacewander** [comment]
No, this change requires to refactor CI files.

**Comment by membphis** [comment]
> No, this change requires to refactor CI files.

we do not need to refactor the CI files. just rename the file name and title as  https://github.com/apache/apisix/issues/3167#issuecomment-752837864
