### ISSUE TITLE
runtime error(ctx.lua):  bad argument #2 to 'setmetatable' (nil or table expected)

### ISSUE THREAD

**Issue by hauer9** [apache/apisix#3171]
### Issue description

I had the same error as issue #3079 while debugging my program, and then I fixed the bug with pr #3105, but this error happened.

![image](https://user-images.githubusercontent.com/38620097/103406321-45e86300-4b95-11eb-9490-c8eb5ca06a55.png)
![image](https://user-images.githubusercontent.com/38620097/103406336-51d42500-4b95-11eb-8c07-5493913ce9bd.png)

![image](https://user-images.githubusercontent.com/38620097/103406295-310bcf80-4b95-11eb-9e82-1ae769721914.png)

### Environment

* apisix version: 2.1
* OS: Linux
* Nginx version: openresty / 1.19.3.1

**Comment by spacewander** [comment]
Will you add a log in ctx.lua:83 to see what is passed to setmetatable?

**Comment by hauer9** [comment]
![image](https://user-images.githubusercontent.com/38620097/103498822-fea5ef00-4e80-11eb-9ed5-5e8b8a32008d.png)

**Comment by spacewander** [comment]
Can you confirm if this change: https://github.com/apache/apisix/pull/3182/files solve your problem?

**Comment by hauer9** [comment]
Yes, thx.

**Comment by Hcreak** [comment]
@spacewander 
I want to know will this bug be corrected in the next release?
I’m suffering from this problem now. L O L~

**Comment by spacewander** [comment]
We will get it merged once @membphis is back.
