### ISSUE TITLE
request help: prometheus not support filter by route

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3174]
### Issue description
I have imported the json file and configured prometheus plugin in each route.

This is `/apisix/prometheus/metrics` api result
![image](https://user-images.githubusercontent.com/10362371/103451384-93341400-4cfe-11eb-9436-fdc3ab47be70.png)

![image](https://user-images.githubusercontent.com/10362371/103451382-8e6f6000-4cfe-11eb-9810-974768c6e472.png)

### Environment
* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`) centos 
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`

**Comment by spacewander** [comment]
I can't understand what you mean by `group by route`.

**Comment by gewei2000** [comment]
> I can't understand what you mean by `group by route`.

You can understand it as filter by route.

**Comment by tokers** [comment]
@gewei2000 You mean add a label as "route" in some prometheus metrics?

**Comment by gewei2000** [comment]
> @gewei2000 You mean add a label named as "route" in some prometheus metrics?

I want to watch every route traffic in prometheus，but metrics api doesn't have route traffic data

**Comment by gewei2000** [comment]
@spacewander

**Comment by spacewander** [comment]
Metrics API does have route traffic data, see:
https://github.com/apache/apisix/blob/7c5df5d343ef79f9a292a8eb621fec72280d13ea/apisix/plugins/prometheus/exporter.lua#L159

If it doesn't work, add more log in prometheus/exporter.lua to see what happened.

**Comment by gewei2000** [comment]
@spacewander I have already visit route many times, but metrics api `/apisix/prometheus/metrics` can not receive any route data;

**Comment by Firstsawyou** [comment]
> @spacewander I have already visit route many times, but metrics api `/apisix/prometheus/metrics` can not receive any route data;

Hi, @gewei2000 
I tried it, and there is route data. You can try to send a successful http request first, and then request the `/apisix/prometheus/metrics` interface.

```shell
$ curl http://127.0.0.1:9080/apisix/prometheus/metrics
# HELP apisix_bandwidth Total bandwidth in bytes consumed per service in APISIX
# TYPE apisix_bandwidth counter
apisix_bandwidth{type="egress",route="1",service="",consumer="",node="111.13.149.108"} 248
apisix_bandwidth{type="egress",route="1",service="",consumer="",node="118.193.98.63"} 248
apisix_bandwidth{type="egress",route="1",service="",consumer="",node="127.0.0.1"} 1420
apisix_bandwidth{type="egress",route="1",service="",consumer="",node="220.181.38.148"} 710
apisix_bandwidth{type="ingress",route="1",service="",consumer="",node="111.13.149.108"} 83
apisix_bandwidth{type="ingress",route="1",service="",consumer="",node="118.193.98.63"} 83
apisix_bandwidth{type="ingress",route="1",service="",consumer="",node="127.0.0.1"} 332
apisix_bandwidth{type="ingress",route="1",service="",consumer="",node="220.181.38.148"} 166
# HELP apisix_etcd_modify_indexes Etcd modify index for APISIX keys
# TYPE apisix_etcd_modify_indexes gauge
apisix_etcd_modify_indexes{key="consumers"} 25508
apisix_etcd_modify_indexes{key="global_rules"} 25477
apisix_etcd_modify_indexes{key="max_modify_index"} 27905
apisix_etcd_modify_indexes{key="prev_index"} 27900
apisix_etcd_modify_indexes{key="protos"} 0
apisix_etcd_modify_indexes{key="routes"} 27905
apisix_etcd_modify_indexes{key="services"} 27794
apisix_etcd_modify_indexes{key="ssls"} 0
.......
```

**Comment by membphis** [comment]
you can enable the plugin `prometheus` in global rule.
