### ISSUE TITLE
apisix有时候请求不到流量

### ISSUE THREAD

**Issue by candicandi** [apache/apisix#3175]
### Environment

* apisix version (cmd: `apisix version`):2.1
* OS: (cmd: `uname -a`) centos7.8
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) 

用https://github.com/apache/apisix-dashboard实现如下配置
两个上游A.  B
两个路由X   Y
其中两个路由的域名一致，路径部分A: /*   B: /api/* 转发规格a->x,b->y,欲实现规则就是当请求的规则是api的时候转发到b，其他则转发到a，如www.example.com/api/auth则到b，www.example.com/auth则到a，现在出现少量应该到a的请求被转发到了b，同时请求a的时候有30%的机率不返回数据

**Comment by candicandi** [comment]
可联系我获取线上环境的数据

**Comment by spacewander** [comment]
What is your OpenResty version?

**Comment by spacewander** [comment]
I think you should turn the error log to info, and provide some error log and network capture file so that we can analyse them.

**Comment by spacewander** [comment]
> 其中两个路由的域名一致，路径部分A: /* B: /api/* 转发规格a->x,b->y

And you should provide the configuration written inside etcd, so that we know how you configure.

**Comment by membphis** [comment]
```shell
[root@48 apisix-2.1-fix]# openresty -V
nginx version: openresty/1.19.3.1
built by gcc 8.3.1 20191121 (Red Hat 8.3.1-5) (GCC)
built with OpenSSL 1.1.1h  22 Sep 2020 (running with OpenSSL 1.1.1i  8 Dec 2020)
TLS SNI support enabled
```

the APISIX has contained this patch:

https://github.com/apache/apisix/commit/5de99904467db5b71e8df4c1f22444eb9d4223b7

**Comment by spacewander** [comment]
<img width="723" alt="微信截图_20210105085208" src="https://user-images.githubusercontent.com/4161644/103594418-9c59f680-4f33-11eb-8f41-4f839e3272e1.png">
Solved.
