### ISSUE TITLE
bug: failed to parse upstream: missing upstream configuration in Route or Service

### ISSUE THREAD

**Issue by Gaoy-o** [apache/apisix#3180]
### Issue description

configuration in stand-alone mode：

routes:
  -
    uri: /hello
    plugins:
      echo:
        body: "body"
#END

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS: (cmd: `uname -a`) centos
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
The error message is clear. You don't have any upstream configuration in your route. Please read the doc: https://github.com/apache/apisix/blob/master/doc/stand-alone.md#how-to-config-rules

**Comment by Gaoy-o** [comment]
https://github.com/apache/apisix/blob/master/doc/admin-api.md

**Comment by Gaoy-o** [comment]
https://github.com/apache/apisix/blob/bb629bc7ebbf8b0d736de96a0b5d973a34e34fdd/apisix/schema_def.lua#L525

**Comment by Gaoy-o** [comment]
https://github.com/apache/apisix/blob/bb629bc7ebbf8b0d736de96a0b5d973a34e34fdd/apisix/schema_def.lua#L525

> The error message is clear. You don't have any upstream configuration in your route. Please read the doc: https://github.com/apache/apisix/blob/master/doc/stand-alone.md#how-to-config-rules

https://github.com/apache/apisix/blob/bb629bc7ebbf8b0d736de96a0b5d973a34e34fdd/apisix/schema_def.lua#L525

**Comment by spacewander** [comment]
There are some ways to set upstream dynamically, so there is not a check when validating the route configuration. But since you hit this error message, it is clear that you don't set an upstream at all.
