### ISSUE TITLE
doc: current doc is not clear, easy to confuse readers

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3189]
https://github.com/apache/apisix/blob/master/doc/admin-api.md#route

![image](https://user-images.githubusercontent.com/6814606/103601466-a6d0bc00-4f44-11eb-9b81-65bf4b7db1f7.png)

https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md#attributes

![image](https://user-images.githubusercontent.com/6814606/103601710-32e2e380-4f45-11eb-970e-37497b79b7f4.png)

**Comment by spacewander** [comment]
Consider solved
