### ISSUE TITLE
feat(CI): add WIP from the GitHub Marketplace

### ISSUE THREAD

**Issue by jbampton** [apache/apisix#3198]
https://github.com/marketplace/wip

WIP is free.

Allow authors of pull requests to set status to pending while still working on it.

By default, the WIP app sets a pull request status to pending if it finds one of the following terms in its title
- wip
- work in progress
- 🚧

**Comment by tokers** [comment]
That's cool, PR's welcome.

**Comment by spacewander** [comment]
The application is good.
But we don't have right to install third party application into Apache.
Currently we use Draft Pull request to represent "WIP" status.

**Comment by jbampton** [comment]
Hey @spacewander are you sure ?  I know this is the policy for GitHub Actions now with the ASF.

You already have the 3rd party app Semantic Pull Requests installed -> https://github.com/apps/semantic-pull-requests

WIP is a verified app by GitHub -> https://github.com/marketplace/wip

**Comment by spacewander** [comment]
<img width="828" alt="微信截图_20210106101107" src="https://user-images.githubusercontent.com/4161644/103720982-8fa6d280-5007-11eb-93a4-2fa4177d4a0c.png">

At least I don't have the right. Not sure if @membphis or @moonming has the right.

**Comment by moonming** [comment]
@spacewander we have the same right.
you can create a jira for apache infra team

**Comment by spacewander** [comment]
Err... It seems the semantic checker has already done the same thing. We can't merge a PR if its title begins with `WIP`. There is no need to add another 3rd party application.
