### ISSUE TITLE
upload the debug info to opentracing system at the same time

### ISSUE THREAD

**Issue by moonming** [apache/apisix#320]
https://github.com/iresty/apisix/commit/04129add2749fcac25fb5e2483a075dce3529209#diff-93f2cfdf5ab2bf2a97d21782ae768bf8R147 
the header should write to the tag of zipkin too.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
