### ISSUE TITLE
bug: server runs apisix also runs Nginx.  "apisix restart" command does not work

### ISSUE THREAD

**Issue by azura27** [apache/apisix#3202]
### Issue description
 server runs apisix in fold /home/apisix fold and runs Nginx in /usr/local/nginx/sbin fold would cause restart cmd failed
### Environment

* apisix version (cmd: `apisix version`): 2.0 (with changes from: https://github.com/apache/apisix/pull/2575/files)
* OS: (cmd: `uname -a`)   Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)   1.15.8.3

### Minimal test code / Steps to reproduce the issue

1. run nginx and apisix together
2. restart apisix
3.

### What's the actual result? (including assertion message & call stack if applicable)
"APISIX  is running ... " show in the screen and apisix stop running
### What's the expected result?
apisix restart   #3193

**Comment by spacewander** [comment]
> server runs apisix in fold /home/apisix fold and runs Nginx in /usr/local/nginx/sbin fold

How do you run like this?

**Comment by azura27** [comment]
run with different pot: apisix 9080 3443; Nginx : 80 16443 8080...
they are run on the same machine, no other relation

**Comment by azura27** [comment]
> How do you run like this? I think it will cause two different pwd and causes some problems like this one.
> 
> Is it possible to split them into two services?
 this is test environment, online would be splited

**Comment by spacewander** [comment]
You can check the path of `nginx.pid` as I suggested in #3193. Add more log during the restart may help.

**Comment by azura27** [comment]
OK, thanks a lot

**Comment by azura27** [comment]
In theory, restart is start after stop, the pid file is empty. But in my test the pid hasn't been clear before start. Maybe this is result from system performance.  Bud does this need to fix for differnent platform support?

**Comment by spacewander** [comment]
It's a known issue: https://github.com/apache/apisix/issues/2948

@azura27 
Could you submit a PR to fix it? Thanks!

https://github.com/apache/apisix/pull/2869/files already provides what you need - just solve the conflict and add a test inside https://github.com/apache/apisix/blob/master/.travis/apisix_cli_test/test_main.sh in it.

The test can be `echo $fake_pid > logs/nginx.pid` then `./bin/apisix start` blah blah.

**Comment by azura27** [comment]
PR pulled according the reference provided: https://github.com/apache/apisix/pull/3208
