### ISSUE TITLE
bug: 自定义nginx配置生成不正确

### ISSUE THREAD

**Issue by shenshaoye** [apache/apisix#3203]
版本：apisix-master
bug描述：
我们使用apisix时需要加载一个第三方模块，把第三方模块编译成so文件，使用load_module指令加载进来，但是load_module指令需要写在event配置块前面，目前apisix提供的修改config-default.yaml文件，main_configuration_snippet的解析是在event配置块后面，因此使用load_module指令时会有问题；
另外一个相似的include指令，有时需要include一个配置文件，在http块的末尾，但是现在http_configuration_snippet的解析位置在http块的server配置块的前面，可能会有问题；

上述问题需要修改下ngx_tpl.lua生成nginx.conf的部分

**Comment by spacewander** [comment]
For the second one, what about adding new "http_configuration_after_snippet" for some order-matter directives?

**Comment by shenshaoye** [comment]
我觉得对于http块的配置，可以多开放几个http_configuration_snippet，以适应在生成的http块中的不同位置来添加自定义配置

**Comment by shenshaoye** [comment]
好的，我尝试修改一下
