### ISSUE TITLE
bug: apisix stream_routes do not support ip-restriction

### ISSUE THREAD

**Issue by pc10201** [apache/apisix#3205]
apisix version 2.1
 
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "server_addr": "0.0.0.0",
>     "server_port": 2000,
>     "upstream": {
>         "nodes": {
>             "127.0.0.1:22": 1
>         },
>         "type": "roundrobin"
>     }
> ,
>     "plugins": {
>         "ip-restriction": {
>             "whitelist": [
>                 "127.0.0.1",
>                 "113.74.26.106/24"
>             ]
>         }
>     }
> }'
{"error_msg":"unknown plugin [ip-restriction]"}

**Comment by Firstsawyou** [comment]
In the 4 layer proxy, only `mqtt-proxy` is badly supported, and the `ip-restriction` plugin is not supported.
