### ISSUE TITLE
bug: blacklist does not work

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix#3209]
### Issue description
Configure plugin  ip-restriction in dashboard，blacklist does not work
I want to not allowed ip 192.168.1.1 access, so i config the ip in dashboard plugin ip-restriction blacklist ,config content like this:
{
  "blacklist": [
    "192.168.1.1"
  ]
}

But the IP can still access the website

### Environment

* apisix version (cmd: `apisix version`): v.2.1
* OS: (cmd: `uname -a`) Linux ali-qa-apisix-01 4.4.0-85-generic #108-Ubuntu SMP Mon Jul 3 17:23:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) openresty/1.19.3.1

**Comment by Firstsawyou** [comment]
Can you provide the configuration information of etcd? This makes it easier for us to troubleshoot problems.

**Comment by starsz** [comment]
Hi, @chenyicai I think you can check the error_log for more details.

**Comment by spacewander** [comment]
Closed as lack of response.
