### ISSUE TITLE
bug: Route has no auto-generated id

### ISSUE THREAD

**Issue by LLLLimbo** [apache/apisix#3210]
I create a route in this way
`curl --location --request POST 'http://192.168.2.102:9080/apisix/admin/routes' \
--header 'Content-Type: application/json' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--data-raw '{
    "uri": "/car/*",
    "upstream": {
        "service_name": "SEEINER-CAR",
        "type": "roundrobin",
        "discovery_type": "eureka"
    }
`
And then in admin-dashboard，its id seemes to be null，and I can not delete it due to the problem.
![image](https://user-images.githubusercontent.com/31607003/103857188-f81dae80-50f0-11eb-9807-c9dd8a2b969f.png)
![image](https://user-images.githubusercontent.com/31607003/103857255-1683aa00-50f1-11eb-9d27-626a49a0f91e.png)

**Comment by starsz** [comment]
Hi, @LLLLimbo. Have you checked the route data in etcd?

**Comment by LLLLimbo** [comment]
> Hi, @LLLLimbo. Have you checked the route data in etcd?
I checked in etcd just now , it seems  exists. But why?

` etcdctl get /apisix/routes/00000000000000544244
/apisix/routes/00000000000000544244
{"uri":"\/car\/*","create_time":1609999013,"priority":0,"upstream":{"service_name":"SEEINER-CAR","type":"roundrobin","pass_host":"pass","hash_on":"vars","discovery_type":"eureka"},"update_time":1609999013}
`
![image](https://user-images.githubusercontent.com/31607003/103858186-dde4d000-50f2-11eb-87e8-7cd622db6afa.png)

**Comment by Firstsawyou** [comment]
@LLLLimbo 
When creating a route in `POST` method, currently, the automatically generated id will not be added to the configuration information. You can try the `PUT` method to specify the route id.

If possible, we need to add the id automatically generated by POST to the configuration information.

**Comment by LLLLimbo** [comment]
> @LLLLimbo
> When creating a route in `POST` method, currently, the automatically generated id will not be added to the configuration information. You can try the `PUT` method to specify the route id.
> 
> If possible, we need to add the id automatically generated by POST to the configuration information.

Thanks, got it.
