### ISSUE TITLE
bug: version need update

### ISSUE THREAD

**Issue by starsz** [apache/apisix#3215]
### Issue description

Hi, I found the version in the master branch is still 2.1. I think it needs an update.

### Environment

* apisix version (cmd: `apisix version`): master branch 
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

### Minimal test code / Steps to reproduce the issue

https://github.com/apache/apisix/blob/2996416d603cd6b76b0b9dc9fede220edebebc13/apisix/core/version.lua#L18

### What's the expected result?

2.2 or master or git commit hash.

**Comment by spacewander** [comment]
The 2.2 isn't released yet. Just start the vote.
It is inevitable to use "wrong" VERSION if people use master branch directly in current branch management. But if they use master branch directly, who cares about the `VERSION`?

**Comment by starsz** [comment]
> The 2.2 isn't released yet. Just start the vote.
> It is inevitable to use "wrong" VERSION if people use master branch directly in current branch management. But if they use master branch directly, who cares about the `VERSION`?

Not very sure.Because the version will be contained in the response header. So It will cause misunderstanding if it was "wrong".

**Comment by spacewander** [comment]
@starsz 
We can do nothing if the people customize their APISIX but don't change the header.

**Comment by spacewander** [comment]
If they use the release version from Apache, the response header is correct.

**Comment by starsz** [comment]
@spacewander Got it.
