### ISSUE TITLE
request help: Using the latest master branch code, apisix cannot be started after make deps

### ISSUE THREAD

**Issue by Jaycean** [apache/apisix#3216]
### Issue description
Using the latest master branch code, apisix cannot be started after make deps
### Environment

* apisix version (cmd: `apisix version`): master
* OS: Linux localhost 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: nginx version: openresty/1.19.3.1
* Lua version: Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio

### Error log;
```
[root@localhost apisix]# ./bin/apisix start
lua: error loading module 'socket.core' from file '/root/github/apisix/deps/lib/lua/5.1/socket/core.so':
	/root/github/apisix/deps/lib/lua/5.1/socket/core.so: undefined symbol: lua_pcall
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	/root/github/apisix/deps/share/lua/5.1/socket.lua:12: in main chunk
	[C]: in function 'require'
	/root/github/apisix/deps/share/lua/5.1/socket/http.lua:10: in main chunk
	[C]: in function 'require'
	./apisix/cli/etcd.lua:22: in main chunk
	[C]: in function 'require'
	./apisix/cli/ops.lua:18: in main chunk
	[C]: in function 'require'
	./bin/apisix:34: in main chunk
	[C]: in ?
```

**Comment by liuxiran** [comment]
when I update the code to the lastest master branch, I had the same problem,  @spacewander @membphis @tokers pls take a look when you have time, thanks a lot~^_^

**Comment by spacewander** [comment]
Solved after talking with @liuxiran. It is because of Lua 5.3.5. Use LuaJIT or Lua 5.1 instead.
