### ISSUE TITLE
request help: Does apisix support long chain and short chain configuration in upstream configuration  ? 

### ISSUE THREAD

**Issue by zhangxiaohui123456** [apache/apisix#3223]
### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by zhangxiaohui123456** [comment]
Does apisix support  long connection or short connection in upstream configuration？，If support how to configur about timeout?

**Comment by Firstsawyou** [comment]
Hi, @zhangxiaohui123456 
Upstream supports configuring the timeout period, please see here:[https://github.com/apache/apisix/blame/master/doc/admin-api.md#L520 ](https://github.com/apache/apisix/blame/master/doc/admin-api.md#L520)
