### ISSUE TITLE
request help:  how to use apisix with zookeeper  service discovery

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3231]
### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
zookeeper service discovery is unsupported yet.
But you can add it. You can take the eureka support (https://github.com/apache/apisix/blob/master/apisix/discovery/eureka.lua) as an example. PR is welcome!

**Comment by youlianyiran** [comment]
hope support zookeeper service discovery for dubbo

**Comment by membphis** [comment]
> hope support zookeeper service discovery for dubbo

would like to contribute this feature? @youlianyiran

**Comment by youlianyiran** [comment]
> 

I am a java programmer. I am not familiar with the apisix and nginx,  just a probably understanding of them,  need a lot of time to be proficient in item

**Comment by youlianyiran** [comment]
> 

I am a java programmer. I am not familiar with the apisix and nginx, just a probably understanding of them, need a lot of time to be proficient in item

**Comment by youlianyiran** [comment]
> 

I am a java programmer. I am not familiar with the apisix and nginx, just a probably understanding of them, need a lot of time to be proficient in item

**Comment by spacewander** [comment]
Note that dubbo's zookeeper service discovery has some special dubbo relative logic.

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/6751
