### ISSUE TITLE
bug: http://apisix.apache.org/downloads/ broken links

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix#3233]
The page http://apisix.apache.org/downloads/ has several broken links:
0.1.0-rc2: all links

Also, the verification instructions look rather odd; it's not clear why there are so many * and \ chars

**Comment by Firstsawyou** [comment]
@spacewander  Please help look at this problem.

**Comment by moonming** [comment]
@gxthrj  please take a look

**Comment by gxthrj** [comment]
Sorry, I will modify the links
