### ISSUE TITLE
feature request: public ECR repo on AWS

### ISSUE THREAD

**Issue by pahud** [apache/apisix#3237]
### Issue description

AWS [announced](https://aws.amazon.com/tw/blogs/aws/amazon-ecr-public-a-new-public-container-registry/) Amazon ECR public in Dec. 2020 providing 50GB free storage each month for each AWS customer.  I believe it would be great to register a official ECR public on AWS, i.e. `public.ecr.aws/apisix` and push images from CI either manually or automatically.

If you are interested, I have a Github Action out-of-the-box

https://github.com/pahud/ecr-public-action/

And I have a mandarin walk-thru video on Youtube

https://youtu.be/wifX_Jb6zcw

If we prefer to trigger the image build/tag/push manually, simply set `workflow_dispatch` like this:

https://github.com/pahud/ecr-public-action/blob/578d422d320045456031d51e91ca32e621861cc5/.github/workflows/main.yml#L8

## ECR public pricing and quotas

All AWS customers will get **50 GB** of free storage each month, and if you exceed that limit, you will pay nominal charges. Check out the pricing page for details.

Anyone who pulls images anonymously will get **500 GB** of free data bandwidth each month, after which they can sign up or sign in to an AWS account to get more. Simply authenticating with an AWS account increases free data bandwidth up to **5 TB** each month when pulling images from the internet.

Finally, workloads running in AWS will get **unlimited** data bandwidth from any region when pulling publicly shared images from ECR Public. 
([source](https://aws.amazon.com/tw/blogs/aws/amazon-ecr-public-a-new-public-container-registry/))

**Comment by juzhiyuan** [comment]
Hi @spacewander, do we need to support the ECR repo as Pahud suggests? 😄

**Comment by spacewander** [comment]
It seems this issue hasn't been updated for a long time...
