### ISSUE TITLE
feat: enhance plugin category

### ISSUE THREAD

**Issue by LiteSun** [apache/apisix#3239]
# Feature request
Enhance plugin category

## Please describe your feature
![image](https://user-images.githubusercontent.com/31329157/104154588-3cc28600-5420-11eb-8b95-7c743dd25036.png)

Currently, many of the plugins returned by the interface are grouped into other, which makes it difficult for users to quickly locate a specific plugin, so we need a more detailed category.

cc @juzhiyuan @nic-chen

**Comment by nic-chen** [comment]
@spacewander  @membphis @juzhiyuan @LiteSun 
 
I tried to classify them, what do you think?

**auth**
basic-auth
hmac-auth
jwt-auth
key-auth

-- They are not related to consumers, but they also belong to the authentication category. How should we classify them?
authz-keycloak
openid-connect


**log**
error-log-logger
http-logger
kafka-logger
log-rotate
sls-logger
syslog
tcp-logger
udp-logger
wolf-rbac


**metric**
prometheus


**proxy**
dubbo-proxy
grpc-transcode
proxy-cache
proxy-mirror


**restriction**
consumer-rejection
cors
fault-injection
ip-restriction
referer-restriction
uri-blocker


**rewrite**
proxy-rewrite
redirect
response-rewrite


**trace**
skywalking
zipkin


**traffic**
api-breaker
limit-conn
limit-count
limit-req
traffic-split


**validation**
request-validation


**other**
batch-requests
node-status
request-id
server-info
serverless-post-function
serverless-pre-function

**Comment by spacewander** [comment]
I think we should define the category first.
What is the difference between `rewrite` and `traffic`?

**Comment by spacewander** [comment]
We already have defined the plugin category: https://github.com/apache/apisix/blob/master/docs/en/latest/README.md#plugins

**Comment by nic-chen** [comment]
> We already have defined the plugin category: https://github.com/apache/apisix/blob/master/docs/en/latest/README.md#plugins

oh, yes, thanks!
I will submit a PR to close this issue.

**Comment by spacewander** [comment]
Consider solved
