### ISSUE TITLE
bug:  `ngx.req.read_body` should be called in the if branch 

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#3243]
### Issue description
`ngx.req.read_body` should be called in the if branch. `read_body` here will partially increase the overall request latency and should not be called if not necessary. 

Next we need a local variable:
`local ngx_read_body = ngx.req.read_body`

ref:
https://github.com/apache/apisix/blob/master/apisix/plugins/wolf-rbac.lua#L330

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by membphis** [comment]
I do not think we need it: `function _M.get_body(max_size, ctx)`

https://github.com/apache/apisix/blob/master/apisix/core/request.lua#L153

we have a `max_size` parameter now.

**Comment by Miss-you** [comment]
The `ngx.req.get_post_args()` need `ngx.req.read_body`

ref:
https://github.com/openresty/lua-nginx-module#ngxreqget_post_args

**Comment by membphis** [comment]
> The `ngx.req.get_post_args()` need `ngx.req.read_body`
> 
> ref:
> https://github.com/openresty/lua-nginx-module#ngxreqget_post_args

yes, you are right. welcome PR to fix it

**Comment by Miss-you** [comment]
done
