### ISSUE TITLE
request help:  How the nginx configured Location smoothly migrates to apisix

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3244]
![image](https://user-images.githubusercontent.com/26598793/104188993-05220100-5455-11eb-84a3-04a7f8c627d0.png)

How to use the functions above the apisix proxy is as effective as the Nginx configuration and can be accessed normally

**Comment by Yangzcy423911** [comment]
At present, the front end is through the domain name matching path / , but / apisix / admin this kind of match should do, it is best to have some examples

**Comment by membphis** [comment]
@Yangzcy423911 you can provide the fake nginx configuration text directly, it easy to discuss.

**Comment by Yangzcy423911** [comment]
nginx config:
log_format  apigateway  '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" "$request_time" "$upstream_response_time"';
#access_log  logs/wechat.log  ;
#error_log  logs/wechaterror.log  info;
server {
        listen       81;
        server_name  192.168.1.100;
        root /opt/front/uat-gateway/html;
        access_log  logs/uat-apigateway.log apigateway;
      location ^~ / {
                 try_files $uri $uri/ /index.html;
        }
      location /apisix/admin {
                 proxy_pass http://192.168.1.100:1001/apisix/admin;
        }
}


Thanks I

**Comment by Yangzcy423911** [comment]
how to use apisix router about full router

**Comment by membphis** [comment]
@Yangzcy423911 you can put your original route rule, then we can help you to check where is wrong

**Comment by Yangzcy423911** [comment]
original route rule please visit  https://github.com/apache/apisix/issues/3252   detail
