### ISSUE TITLE
How to smoothly upgrade from 2.1 to 2.2? 2.1 is deployed with RPM

### ISSUE THREAD

**Issue by json7** [apache/apisix#3257]

**Comment by Firstsawyou** [comment]
In my opinion, two service environments are needed. As shown below:
After the new version is deployed, a small amount of traffic can be migrated to the new version to verify the stability of the new service.

![image](https://user-images.githubusercontent.com/52862365/104286769-7bc00c80-54f0-11eb-9a90-9c96dcb38a07.png)

After the new version is stable, all traffic can be migrated to the new version.

![image](https://user-images.githubusercontent.com/52862365/104286782-7f539380-54f0-11eb-9310-c217b76f92bd.png)
