### ISSUE TITLE
request help: how support cas?

### ISSUE THREAD

**Issue by roneywei** [apache/apisix#3260]
### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
how support cas

**Comment by spacewander** [comment]
What is `cas`？

**Comment by roneywei** [comment]
Central Authentication Service

**Comment by spacewander** [comment]
I am not familiar of cas. It seems it supports:
JWT: https://apereo.github.io/cas/6.3.x/installation/JWT-Authentication.html
OpenID-Connect: https://apereo.github.io/cas/6.3.x/protocol/OIDC-Protocol.html

Maybe we can integrate with it via plugins:
https://github.com/apache/apisix/blob/master/doc/plugins/jwt-auth.md
https://github.com/apache/apisix/blob/master/doc/plugins/openid-connect.md

**Comment by roneywei** [comment]
IdP ：Support  Auth0, okta, etc 

We are use cas !

Hope apisix support cas ！

**Comment by tq02ksu** [comment]
I have the same scenario in the company, I think it is a common requirement.

**Comment by spacewander** [comment]
The CAS seems to use standard protocols like JWT and OpenID-Connect

Maybe we can integrate with it via plugins:
https://github.com/apache/apisix/blob/master/doc/plugins/jwt-auth.md
https://github.com/apache/apisix/blob/master/doc/plugins/openid-connect.md
