### ISSUE TITLE
request help: support chash key splicing

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#3261]
### Issue description
Nginx support hash key splicing, just as follow
```
hash ${request_uri}${http_token}${http_sign}  consistent
```

I can't find how to replace it with chash in apisix，  and I think it’s an importance function in prd env

Thanks for helping

### Environment

* apisix version (2.1):
* OS: (ubuntu 16)
* OpenResty / Nginx version: (1.19`)

**Comment by Firstsawyou** [comment]
Take a look at this document: [https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream ](https://github.com/apache/apisix/blob/master/doc/admin-api.md#upstream)

**Comment by spacewander** [comment]
@nanamikon 
We can add a new `hash_on` type to support it.
There are already a helper function to eval Nginx variable:  https://github.com/apache/apisix/blob/3e19b06293463f52c8d26f0958542fc475ff0fcd/apisix/core/utils.lua#L268
You need to modify https://github.com/apache/apisix/blob/3e19b06293463f52c8d26f0958542fc475ff0fcd/apisix/balancer/chash.lua#L33-L41

PR is welcome!

**Comment by nanamikon** [comment]
@spacewander 
I am new to apisix,  and I test this function follow your tips using test-nginx。
I have following points to discuss

1. the key of hash_on can be defined as  “vars_combinations”,     refers to http://nginx.org/en/docs/stream/ngx_stream_upstream_module.html
```
The key can contain text, variables, and their combinations (1.11.2)
```

2. In upstreams.lua，  should I check the schema in this situation？  I think it is no need to do this， because it is an advance feature
```
local function get_chash_key_schema(hash_on)
    if not hash_on then
        return nil, "hash_on is nil"
    end

    if hash_on == "vars" then
        return core.schema.upstream_hash_vars_schema
    end

    if hash_on == "header" or hash_on == "cookie" then
        return core.schema.upstream_hash_header_schema
    end

    if hash_on == "consumer" then
        return nil, nil
    end
    return nil, "invalid hash_on type " .. hash_on
end
```
3.  If all vals are not exist， for example
```
$request_uri-$host
``` 
the hash on should be "-",  and will not use default chash_key "remote_addr"，  is it acceptable？
Refer to https://trac.nginx.org/nginx/ticket/765，  any plan to support map？

**Comment by spacewander** [comment]
1. good name!
2. we can simply check if it is string type:
```
local xxx_schema = {
    type = "string",
}
```
3. it is acceptable.

> any plan to support map

We can add `fallback_hash_on` feature in a separate PR.

**Comment by nanamikon** [comment]
Thanks for your reply,  I will submit pr today
