### ISSUE TITLE
request help:   without network install apisix

### ISSUE THREAD

**Issue by 18210212423** [apache/apisix#3262]
### Issue description
Luarocks needs network to install dependencies, such as Lua resty JWT. If I need to install in Linux without network, how can I install it

### Environment

* apisix version (cmd: `apisix version`): 2,2
* OS: (cmd: `uname -a`)  Linux
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) 1.19.3.1

**Comment by spacewander** [comment]
Install via the rpm: https://github.com/apache/apisix/releases
Or via docker (docker save/load)

**Comment by 18210212423** [comment]
I use rpm -ivh apisix-2.2-0.el7.rpm
but error:
error: Failed dependencies:
	openresty >= 1.15.8.1 is needed by apisix-2.2-0.noarch

Openresty has been installed in Linux
openresty -v
nginx version: openresty/1.19.3.1

Do I have any questions？

**Comment by spacewander** [comment]
The rpm package requires OpenResty installed via rpm too.

**Comment by 18210212423** [comment]
OK，thank you，I want to ask, where can I get the RPM of openresty，Do I need to make it myself？

**Comment by spacewander** [comment]
OpenResty provides official package for CentOS: http://openresty.org/en/linux-packages.html#centos
I am not familiar with yum, but if it can be installed via yum, I think it is possible to exact a rpm package from it.

**Comment by 18210212423** [comment]
I looked at the installation with RPM and found that there was still a lack of package. Luarocks installation module, offline installation, how to install

**Comment by spacewander** [comment]
> 
> 
> I looked at the installation with RPM and found that there was still a lack of package. Luarocks installation module, offline installation, how to install

Do you mean installing luarocks offline?

**Comment by 18210212423** [comment]
sorry，I didn't describe it clearly. Luarocks has been installed, but how should those modules such as lua-rest-jwt-0.2.0 be installed offline? Thank you

**Comment by 18210212423** [comment]
I use luarocks to make lua-resty-template-dev-1.rockspec, but the installed version seems to be wrong

**Comment by 18210212423** [comment]
I would like to ask how to remove the support of IPv6, because the system does not support IPv6

**Comment by 18210212423** [comment]
Finally, I packaged and copied the DEPS folder in apisix, which is installed on the Internet, to the Linux system without network, and found that the dependency can be read，but now the Linux system does not support IPv6，how to remove the support of IPv6？

**Comment by 18210212423** [comment]
i have find it，
apisix:
  node_listen: 9080                # APISIX listening port
  enable_admin: true
  enable_admin_cors: true          # Admin API support CORS response headers.
  enable_debug: false
  enable_dev_mode: false           # Sets nginx worker_processes to 1 if set to true
  enable_reuseport: true           # Enable nginx SO_REUSEPORT switch if set to true.
  enable_ipv6: true   # config false

**Comment by membphis** [comment]
@18210212423 pls feel free to reopen this issue if you still have problem

**Comment by 18210212423** [comment]
> @18210212423 pls feel free to reopen this issue if you still have problem

OK,Thank you very much for your reply
