### ISSUE TITLE
request help: stream proxy support dynamic configuration

### ISSUE THREAD

**Issue by belongwqz** [apache/apisix#3265]
### Issue description

根据 [https://github.com/apache/apisix/blob/master/doc/stream-proxy.md#how-to-enable-stream-proxy](https://github.com/apache/apisix/blob/master/doc/stream-proxy.md#how-to-enable-stream-proxy)说明，stream_proxy只能从配置文件进行，能否做成etcd里的动态配置，以便可以使用接口或者dashboard进行管理。

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by Firstsawyou** [comment]
The settings of stream route can be dynamically configured through etcd. The configuration file is to enable and configure the stream port.

**Comment by spacewander** [comment]
@belongwqz 
We can't do it as Nginx doesn't support listening new port on the fly.

**Comment by belongwqz** [comment]
可以考虑将配置文件（config.yaml）里的stream_proxy配置推送到etcd里，然后apisix-dashboard就可以从etcd获知哪些端口以及协议已经开启监听用于4层代理，然后基于此来进行更进一步的动态stream_route的配置。

**Comment by caibirdme** [comment]
@spacewander we don't need to support adding listening port dynamically but it'd be better to support config L4 proxy for existed port. People can add the tcp listen port and then restart, then on the dashboard, we could learn from the etcd which port can be used for l4 proxy, and only support configuration for those ports.
