### ISSUE TITLE
bug:  apisix 2.2 base Tengine trun on prometheus error

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3266]
### Environment

* apisix version (cmd: `apisix version`): 2.2
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
openresty -V
Tengine version: Tengine/2.3.2
nginx version: nginx/1.17.3
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
### Minimal test code / Steps to reproduce the issue

1.  in router config monitor
about router
{
    "node": {
        "value": {
            "update_time": 1610508245,
            "methods": [
                "GET",
                "HEAD",
                "POST",
                "PUT",
                "DELETE",
                "OPTIONS",
                "PATCH"
            ],
            "upstream": {
                "pass_host": "pass",
                "type": "roundrobin",
                "nodes": [
                    {
                        "host": "wx.test.com",
                        "port": 80,
                        "weight": 1
                    }
                ],
                "timeout": {
                    "connect": 6000,
                    "send": 6000,
                    "read": 6000
                }
            },
            "id": "337065930544645006",
            "hosts": [
                "wx.test.con"
            ],
            "name": "test123",
            "status": 1,
            "uris": [
                "/*"
            ],
            "plugins": {
                "prometheus": {
                    "disable": false
                },
                "redirect": {
                    "http_to_https": true
                },
                "request-id": {
                    "disable": false,
                    "include_in_response": true
                }
            },
            "create_time": 1610436550,
            "desc": "测试",
            "vars": {}
        },
        "key": "/uat-apisix/routes/337065930544645006"
    },
    "count": "1",
    "action": "get"
}
2.  apisix error log
2021/01/13 11:27:32 [error] 17251#17251: *13691570 lua entry thread aborted: runtime error: /usr/share/lua/5.1/apisix/core/etcd.lua:92: attempt to index field 'header' (a nil value)
stack traceback:
coroutine 0:
        /usr/share/lua/5.1/apisix/core/etcd.lua: in function 'get_format'
        /usr/share/lua/5.1/apisix/core/config_etcd.lua:75: in function 'getkey'
        /usr/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:310: in function 'handler'
        /usr/share/lua/5.1/apisix/api_router.lua:124: in function 'handler'
        /usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:713: in function 'dispatch'
        /usr/share/lua/5.1/apisix/api_router.lua:159: in function 'match'
        /usr/share/lua/5.1/apisix/init.lua:381: in function 'http_access_phase'
        access_by_lua(nginx.conf:251):2: in main chunk, client: 192.168.1.1, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "192.168.1.1"

etcd enable auth username and passowrd

apisix configfile:
etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://1.1.1.1:2379"
    - "http://2.2.2.2:2379"
    - "http://3.3.3.3:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. "https://127.0.0.1:2379".
  prefix: "/uat-apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds
  resync_delay: 5
  user: "root"                    # root username for etcd
  password: "123456"      # root password for etcd
  tls:
    verify: true   
plugin_attr:
  prometheus:
    export_uri: /apisix/prometheus/metrics

**Comment by spacewander** [comment]
Look like etcd returns an unexpected response to APISIX?
Need a network capture file to confirm it.
BTW, what's your etcd version?

**Comment by Yangzcy423911** [comment]
etcd detail
etcdctl version
etcdctl version: 3.4.14
API version: 3.4

**Comment by Firstsawyou** [comment]
We will check it.

**Comment by Yangzcy423911** [comment]
By the way , check it is OK?

**Comment by spacewander** [comment]
@Yangzcy423911 
> Need a network capture file to confirm it.

As I said, you should provide a network capture file to show what happened between APISIX and etcd when the problem occured.

**Comment by Yangzcy423911** [comment]
How can I provide this network file

If there is a problem with the connection between the gateway and etcd, the gateway service cannot be started normally, which is not logical

**Comment by spacewander** [comment]
> 
> 
> Look like etcd returns an unexpected response to APISIX?
> Need a network capture file to confirm it.
> BTW, what's your etcd version?

I already told you it is about the request/response problem, not about the connection.

There are plenty of resources about how to provide a network capture file on the Internet.

**Comment by Yangzcy423911** [comment]
use curl 
curl 192.168.1.1/apisix/prometheus/metrics -v
* About to connect() to 192.168.1.1 port 80 (#0)
*   Trying 192.168.1.1...
* Connected to 192.168.1.1 (192.168.1.1) port 80 (#0)
> GET /apisix/prometheus/metrics HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.1.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Date: Thu, 14 Jan 2021 01:51:10 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 603
< Connection: close
< Server: Tengine
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
 Sorry for the inconvenience.<br/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://192.168.1.1/apisix/prometheus/metrics</td>
</tr>
<tr>
<td>Server:</td>
<td>192-168-1-1</td>
</tr>
<tr>
<td>Date:</td>
<td>2021/01/14 09:51:10</td>
</tr>
</table>
<hr/>Powered by Tengine<hr><center>tengine</center>
</body>
</html>
* Closing connection 0

**Comment by Yangzcy423911** [comment]
![image](https://user-images.githubusercontent.com/26598793/104538962-bee8bf80-5657-11eb-8895-35be3b00f3b9.png)
![image](https://user-images.githubusercontent.com/26598793/104539022-cf993580-5657-11eb-878b-d44ca2d3a659.png)
![image](https://user-images.githubusercontent.com/26598793/104539076-de7fe800-5657-11eb-9f79-59a3faac337c.png)
![image](https://user-images.githubusercontent.com/26598793/104539124-eb044080-5657-11eb-8d5b-d9d008288ee7.png)

Thins is a   network capture you see!

**Comment by spacewander** [comment]
Please upload the original `.pcap` file.

**Comment by spacewander** [comment]
And you need to point out which captured request causes the error. There are too much requests in your capture file.

**Comment by Yangzcy423911** [comment]
I don't know much about the analysis gateway package. Because there is sensitive information (including intranet address), it's not convenient to upload it directly here. I went to my network colleague and asked him to analyze it. He said that the requests were normal and there was no problem with the package.

**Comment by Yangzcy423911** [comment]
===========================================================================================================================================
HTTP/Requests:
Topic / Item                Count         Average       Min Val       Max Val       Rate (ms)     Percent       Burst Rate    Burst Start  
-------------------------------------------------------------------------------------------------------------------------------------------
HTTP Requests by HTTP Host  49                                                      0.0026        100%          0.0300        12.857       
 192.168.1.1:2379          7                                                       0.0004        14.29%        0.0100        4.059        
  /version                  2                                                       0.0001        28.57%        0.0100        5.178        
  /v3/kv/range              4                                                       0.0002        57.14%        0.0100        8.020        
  /v3/auth/authenticate     1                                                       0.0001        14.29%        0.0100        4.059        
 192.168.1.1               8                                                       0.0004        16.33%        0.0200        19.158       
  /v3/watch                 8                                                       0.0004        100.00%       0.0200        19.158       
 192.168.1.2:2379          8                                                       0.0004        16.33%        0.0100        5.972        
  /version                  4                                                       0.0002        50.00%        0.0100        8.020        
  /v3/kv/range              3                                                       0.0002        37.50%        0.0100        5.972        
  /v3/auth/authenticate     1                                                       0.0001        12.50%        0.0100        17.475       
 192.168.1.2               8                                                       0.0004        16.33%        0.0100        3.608        
  /v3/watch                 8                                                       0.0004        100.00%       0.0100        3.608        
 192.168.1.3:2379          5                                                       0.0003        10.20%        0.0100        5.179        
  /version                  3                                                       0.0002        60.00%        0.0100        5.971        
  /v3/kv/range              2                                                       0.0001        40.00%        0.0100        5.179        
 192.168.1.3               13                                                      0.0007        26.53%        0.0200        17.528       
  /v3/watch                 13                                                      0.0007        100.00%       0.0200        17.528       

-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by Yangzcy423911** [comment]
![image](https://user-images.githubusercontent.com/26598793/104540916-759a6f00-565b-11eb-94ed-e6cd40358966.png)

This is about http request, you see

**Comment by spacewander** [comment]
I guess it is caused by some response which doesn't contain `header` field in its body.
You can take your investigation from:
https://github.com/api7/lua-resty-etcd/blob/f2abd8b99629c1c8b133aa25e6c7c20a255d0d4a/lib/resty/etcd/v3.lua#L90
You can search corresponding response or just dump them out.

The patch below may help you catch those response:
```diff
diff --git apisix/core/etcd.lua apisix/core/etcd.lua
index 07af2b06..a26b4958 100644
--- apisix/core/etcd.lua
+++ apisix/core/etcd.lua
@@ -89,6 +89,9 @@ function _M.get_format(res, real_key, is_dir)
         return nil, "insufficient credentials code: 401"
     end

+    if not res.body.header then
+        local cjson = require("cjson.safe"); ngx.log(ngx.ALERT, "", cjson.encode(res.body))
+    end
     res.headers["X-Etcd-Index"] = res.body.header.revision

     if not res.body.kvs then
```

**Comment by Yangzcy423911** [comment]
Do you want to recompile APISIX directly after modifying the code or just replace the corresponding file and restart the service

**Comment by spacewander** [comment]
Just replace the corresponding file and restart the service is enough.

**Comment by Yangzcy423911** [comment]
I will modifying  file /usr/share/lua/5.1/apisix/core/etcd.lua and  Add the code you provided above and restart the service. Won't adding this code affect the use of other modules

**Comment by Yangzcy423911** [comment]
Restart and re access the node. The error log is as follows

2021/01/14 15:11:25 [error] 25657#25657: *651 [lua] http.lua:951: request_uri(): unread data in buffer, client: 192.168.1.1, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "192.168.1.1"
2021/01/14 15:11:25 [alert] 25657#25657: *651 [lua] etcd.lua:93: get_format(): {"code":7,"error":"etcdserver: permission denied","message":"etcdserver: permission denied"}, client: 192.168.1.1, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "192.168.1.1"
2021/01/14 15:11:25 [error] 25657#25657: *651 lua entry thread aborted: runtime error: /usr/share/lua/5.1/apisix/core/etcd.lua:96: attempt to index field 'header' (a nil value)
stack traceback:
coroutine 0:
	/usr/share/lua/5.1/apisix/core/etcd.lua: in function 'get_format'
	/usr/share/lua/5.1/apisix/core/config_etcd.lua:75: in function 'getkey'
	/usr/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:310: in function 'handler'
	/usr/share/lua/5.1/apisix/api_router.lua:124: in function 'handler'
	/usr/local/apisix//deps/share/lua/5.1/resty/radixtree.lua:713: in function 'dispatch'
	/usr/share/lua/5.1/apisix/api_router.lua:159: in function 'match'
	/usr/share/lua/5.1/apisix/init.lua:381: in function 'http_access_phase'
	access_by_lua(nginx.conf:251):2: in main chunk, client: 192.168.1.1, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "192.168.1.1"

**Comment by Yangzcy423911** [comment]
about apisix with connected etcd config
etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://192.168.1.1:2379"
    - "http://192.168.1.2:2379"
    - "http://192.168.1.3:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. "https://127.0.0.1:2379".
  prefix: "/uat-apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds
  resync_delay: 5
  user: "uat"                    # root username for etcd
  password: "123456"      # root password for etcd
  tls:
    verify: true

**Comment by Yangzcy423911** [comment]
Call the interface / apimix / Prometheus / metrics to read the key information in etcd. I have modified the prefix. Normally, there is no permission problem

**Comment by Yangzcy423911** [comment]
After I use the etcd cluster's highest privilege configuration and restart the service, the calling interface returns normal data, which should be the problem of etcd cluster's privilege. I still want to understand that this interface accesses the keys in etcd

**Comment by Yangzcy423911** [comment]
Here are my suggestions

        local res, _ = config:getkey("/routes")
        if res and res.headers then
            clear_tab(key_values)
            -- global max
            key_values[1] = "x_etcd_index"
            metrics.etcd_modify_indexes:set(res.headers["X-Etcd-Index"], key_values)
        end
    end


  modifying code line local res, _ = config:getkey("/routes")   


One line of code in the above code, when obtaining this key, if you add the prefix of reading etcd configuration from the configuration file, and then splice this key, you can avoid the problem of inaccessible interface caused by permissions.

**Comment by Yangzcy423911** [comment]
Here's how I deal with it

etcdctl --endpoints='1.1.1.1:2379,2.2.2.2:2379,3.3.3.3:2379' --user root  role grant-permission uat-entry-read-write-prefix-apisix --prefix=true readwrite /routes
access interface 

curl 192.168.1.1:9080/apisix/prometheus/metrics
# HELP apisix_etcd_modify_indexes Etcd modify index for APISIX keys
# TYPE apisix_etcd_modify_indexes gauge
apisix_etcd_modify_indexes{key="consumers"} 0
apisix_etcd_modify_indexes{key="global_rules"} 0
apisix_etcd_modify_indexes{key="max_modify_index"} 208
apisix_etcd_modify_indexes{key="prev_index"} 227
apisix_etcd_modify_indexes{key="protos"} 0
apisix_etcd_modify_indexes{key="routes"} 208
apisix_etcd_modify_indexes{key="services"} 117
apisix_etcd_modify_indexes{key="ssls"} 186
apisix_etcd_modify_indexes{key="stream_routes"} 0
apisix_etcd_modify_indexes{key="upstreams"} 106
apisix_etcd_modify_indexes{key="x_etcd_index"} 228
# HELP apisix_etcd_reachable Config server etcd reachable from APISIX, 0 is unreachable
# TYPE apisix_etcd_reachable gauge
apisix_etcd_reachable 1
# HELP apisix_nginx_http_current_connections Number of HTTP connections
# TYPE apisix_nginx_http_current_connections gauge
apisix_nginx_http_current_connections{state="accepted"} 25108
apisix_nginx_http_current_connections{state="active"} 1
apisix_nginx_http_current_connections{state="handled"} 25108
apisix_nginx_http_current_connections{state="reading"} 18
apisix_nginx_http_current_connections{state="total"} 7
apisix_nginx_http_current_connections{state="waiting"} 1
apisix_nginx_http_current_connections{state="writing"} 0
# HELP apisix_nginx_metric_errors_total Number of nginx-lua-prometheus errors
# TYPE apisix_nginx_metric_errors_total counter
apisix_nginx_metric_errors_total 0
# HELP apisix_node_info Info of APISIX node
# TYPE apisix_node_info gauge
apisix_node_info{hostname="192-168-1-1"} 1

**Comment by spacewander** [comment]
> 
> 
> Here are my suggestions
> 
> ```
>     local res, _ = config:getkey("/routes")
>     if res and res.headers then
>         clear_tab(key_values)
>         -- global max
>         key_values[1] = "x_etcd_index"
>         metrics.etcd_modify_indexes:set(res.headers["X-Etcd-Index"], key_values)
>     end
> end
> ```
> 
> modifying code line local res, _ = config:getkey("/routes")
> 
> One line of code in the above code, when obtaining this key, if you add the prefix of reading etcd configuration from the configuration file, and then splice this key, you can avoid the problem of inaccessible interface caused by permissions.

I am not quite understand. Maybe you can submit a pull request so that we can discuss around it?
