### ISSUE TITLE
bug: failed to wait etcd dir

### ISSUE THREAD

**Issue by duanzhaoqian** [apache/apisix#3267]
### Issue description
运行一段时间出现，不确定原因，make reload就好了
![image](https://user-images.githubusercontent.com/8066935/104416388-aec8d580-55ae-11eb-9f0a-f565b1602171.png)

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS: (cmd: `uname -a`) Linux  3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
nginx version: openresty/1.19.3.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/apps/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1 --add-module=../iconv-nginx-module-0.14 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/apps/openresty/luajit/lib -Wl,-rpath,/usr/local/lib' --with-http_stub_status_module --with-http_sub_module --with-http_ssl_module --with-http_realip_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

### What's the expected result?
大量error.log

**Comment by Firstsawyou** [comment]
It is recommended to use the latest version, this problem may have been fixed in the latest version.

**Comment by spacewander** [comment]
We have fixed bugs of etcd since 2.0.
Since you are using OpenResty 1.19, which requires APISIX 2.2, I suggest you to upgrade to 2.2.

**Comment by duanzhaoqian** [comment]
谢谢，我升级下试试

**Comment by spacewander** [comment]
Feel free to reopen it if this bug can be reproduced with the 2.2.
