### ISSUE TITLE
How to do service discovery based on etcd or consul? The documents on our GitHub don't look very smoothrequest help: 

### ISSUE THREAD

**Issue by json7** [apache/apisix#3268]

**Comment by Firstsawyou** [comment]
@spacewander  Please help to see this problem.

**Comment by membphis** [comment]
for the `consul`, you can use the DNS way, you can take a look: https://apisix.dev/d/42-apache-apisix-101-consul

**Comment by json7** [comment]
> for the `consul`, you can use the DNS way, you can take a look: https://apisix.dev/d/42-apache-apisix-101-consul

thanks

**Comment by json7** [comment]
> for the `consul`, you can use the DNS way, you can take a look: https://apisix.dev/d/42-apache-apisix-101-consul

DNS based method is very limited, and our service ports are generally random, so we are more likely to do service discovery based on the namespace. Now our APIs IX doesn't support it?

**Comment by membphis** [comment]
> we are more likely to do service discovery based on the namespace. Now our APIs IX doesn't support it?

this is a todo feature, would you like to join us to implement this feature together? ^_^

**Comment by ElvinEfendi** [comment]
@membphis does the consul based routing respect weights set in the consul SVC record?

**Comment by membphis** [comment]
> @membphis does the consul based routing respect weights set in the consul SRV record?

need @moonming to confirm this detail. thx

**Comment by tokers** [comment]
> @membphis does the consul based routing respect weights set in the consul SRV record?

We don't have special process for SRV record, i think it's necessary in this case.

**Comment by favorinfo** [comment]
when using the current version (v2.7), you can just set the dns client opt in apisix/discovery/dns.lua (line 81),
change the origin order {"last", "A", "AAAA", "SRV", "CNAME"} to {"last", "SRV", "A", "AAAA", "CNAME"}
then the port will change to the random port.

**Comment by tokers** [comment]
> when using the current version (v2.7), you can just set the dns client opt in apisix/discovery/dns.lua (line 81),
> change the origin order {"last", "A", "AAAA", "SRV", "CNAME"} to {"last", "SRV", "A", "AAAA", "CNAME"}
> then the port will change to the random port.

@favorinfo Let's record this problem into another issue? It looks like this is another problem.

**Comment by spacewander** [comment]
Close to avoid being hijacked.
