### ISSUE TITLE
apisix连接外部tls etcd集群报错

### ISSUE THREAD

**Issue by dw-3** [apache/apisix#3270]
[root@dev-apisix ~]# apisix restart
nginx: [error] open() "/usr/local/apisix/logs/nginx.pid" failed (2: No such file or directory)
got malformed version message: "" from etcd

配置如下:
etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "https://10.10.100.71:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
    - "https://10.10.100.72:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
    - "https://10.10.100.73:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. "https://127.0.0.1:2379".
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds
  # resync_delay: 5               # when sync failed and a rest is needed, resync after the configured seconds plus 50% random jitter
  # user: root                    # root username for etcd
  # password: 5tHkHhYkjr6cQY      # root password for etcd
  tls:
    verify: true                  # whether to verify the etcd endpoint certificate when setup a TLS connection to etcd,
                                  # the default value is true, e.g. the certificate will be verified strictly.

**Comment by dw-3** [comment]
etcd 3.4.0

**Comment by dw-3** [comment]
apisix2.2

**Comment by Firstsawyou** [comment]
@membphis  @tokers  Please take a look.

**Comment by membphis** [comment]
https://github.com/apache/apisix/search?q=got+malformed+version+message&type=issues

@Firstsawyou @dw-3 you can search this question in the issue, then you'll find the reason.

**Comment by spacewander** [comment]
Same as https://github.com/apache/apisix/issues/3225
And see https://github.com/apache/apisix/issues/3283

**Comment by Firstsawyou** [comment]
> https://github.com/apache/apisix/search?q=got+malformed+version+message&type=issues
> 
> @Firstsawyou @dw-3 you can search this question in the issue, then you'll find the reason.

Ok.
