### ISSUE TITLE
bug: the plugin limit-req reached threshold response with error code 503 by Apache Benchmark

### ISSUE THREAD

**Issue by xujl930** [apache/apisix#3276]
### Issue description
I got some response of error code 503 from Apisix when benchmark with ab，however，i have set rate to 10k per second. I  run ab -n 100 -c 10, it returned out about a half  503 response. is there any wrong configuration caused the result?

### Environment

* apisix version (cmd: `apisix version`): docker image: apache/apisix:2.2-alpine
* apsix-dashboard: docker image: apache/apisix-dashboard:2.3
* OS: (cmd: `uname -a`): macOS Big Sur 11.1
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1

### Minimal test code / Steps to reproduce the issue

1. run apisix and apisix-dashboard,add a global limit req plugin with configuration
```
{
  "burst": 0,
  "disable": false,
  "key": "remote_addr",
  "rate": 100000,
  "rejected_code": 503
}
```
2. add a upstream server, a route point to the upstream server
3. use ab with command like 
```
ab -n 100 -c 10 http://127.0.0.1:9080/<your-route-url>
```

### What's the actual result? (including assertion message & call stack if applicable)
![image](https://user-images.githubusercontent.com/26455030/104537773-9233a880-5655-11eb-872b-5fb7c4f5fa30.png)
![image](https://user-images.githubusercontent.com/26455030/104537487-028dfa00-5655-11eb-9dd6-0b6f07df8d6f.png)

### What's the expected result?
it should return all response with 200 code

**Comment by Firstsawyou** [comment]
You can look at this document: [https://github.com/apache/apisix/blob/master/doc/plugins/limit-req.md ](https://github.com/apache/apisix/blob/master/doc/plugins/limit-req.md)

**Comment by membphis** [comment]
`ab` uses short connections by default, you need to use the `-k` parameter.

https://httpd.apache.org/docs/2.4/programs/ab.html:

`-k              Use HTTP KeepAlive feature`

**Comment by membphis** [comment]
and if you got 5xx response, you can check your error log first: `apisix/logs/error.log`, we can get more useful information

**Comment by xujl930** [comment]
> `ab` uses short connections by default, you need to use the `-k` parameter.
> 
> https://httpd.apache.org/docs/2.4/programs/ab.html:
> 
> `-k Use HTTP KeepAlive feature`

seems that doesn't work, still got many response of 503

**Comment by xujl930** [comment]
> and if you got 5xx response, you can check your error log first: `apisix/logs/error.log`, we can get more useful information

there is no info output in error.log, the limit-req plugin just return 503

**Comment by tokers** [comment]
Would you please use another benchmark tool like wrk or vegeta to test it?

**Comment by xujl930** [comment]
> Would you please use another benchmark tool like wrk or vegeta to test it?
```
Running 1s test @ http://127.0.0.1:9080/52-dev/sqleditor/test-jlxu
  10 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    63.42ms   70.05ms 244.26ms   88.48%
    Req/Sec   170.96     59.55   310.00     66.67%
  1680 requests in 1.11s, 643.48KB read
  Non-2xx or 3xx responses: 990
Requests/sec:   1520.20
Transfer/sec:    582.27KB
```

**Comment by tokers** [comment]
The limit-req uses the leaky bucket algorithm, which cares about the frequency of incoming requests, not the number of requests at the moment, if two requests come in closely, the latter requests might be rejected.

**Comment by tokers** [comment]
> The limit-req uses the leaky bucket algorithm, which cares about the frequency of incoming requests, not the number of requests at the moment, if two requests come in closely, the latter requests might be rejected.

**Comment by membphis** [comment]
@xujl930 feel free to reopen this issue if you still have any question
