### ISSUE TITLE
Support disable ssl verify for etcd connection

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#3283]
Currently when people want to connect etcd cluster via TLS, there is no way to disable SSL verify.

We need to solve it in two aspects:
1. allow disabling SSL verify in apisix/cli with luasocket
2. allow disabling SSL verify in lua-resty-etcd.

**Comment by spacewander** [comment]
This feature will solve https://github.com/apache/apisix/issues/3225

**Comment by spacewander** [comment]
@starsz

**Comment by starsz** [comment]
OK. Please assign it to me.

**Comment by tokers** [comment]
https://github.com/api7/lua-resty-etcd/blob/master/lib/resty/etcd/v3.lua#L113 @spacewander lua-resty-etcd already supports to verify SSL or not.

**Comment by spacewander** [comment]
But we don't pass the option to it.

**Comment by starsz** [comment]
Should lua-resty-etcd support blocking requests by using luasocket?
Then we can use lua-resty-etcd in apisix/cli.

**Comment by spacewander** [comment]
@starsz 
It would be great. We can do it in a separate PR.

**Comment by tokers** [comment]
> But we don't pass the option to it.

You mean APISIX or others?
https://github.com/apache/apisix/blob/master/apisix/core/config_etcd.lua#L502

**Comment by spacewander** [comment]
Sorry, it is my mistake...
