### ISSUE TITLE
bug: apisix/plugin.lua init_worker prometheus.exporter init  should happen before _M.load() 

### ISSUE THREAD

**Issue by yangxikun** [apache/apisix#3286]
### Issue description

Our custom plugins rely on `apisix.plugins.prometheus.exporter.get_prometheus()` return an initialized prometheus instance to create metrics. 

### Environment

* apisix version (cmd: `apisix version`): 2.2

### What's the actual result? (including assertion message & call stack if applicable)

When apisix start, custom plugins init first, and `apisix.plugins.prometheus.exporter.get_prometheus()` return nil, cause error `attempt to index a nil value`.

apisix/plugin.lua: 

```lua
function _M.init_worker()
    _M.load()

    -- some plugins need to be initialized in init* phases
    if ngx.config.subsystem == "http" then
        require("apisix.plugins.prometheus.exporter").init()
    end

    ......

end
```

**Comment by spacewander** [comment]
Do you mean moving `require("apisix.plugins.prometheus.exporter").init()` ahead of `_M.load()`?

**Comment by yangxikun** [comment]
@spacewander Yes.

**Comment by spacewander** [comment]
PR is welcome!
