### ISSUE TITLE
bug: Cors plugin

### ISSUE THREAD

**Issue by NetRainn** [apache/apisix#3288]
## Cors
![image](https://user-images.githubusercontent.com/35440615/104564015-5f090d80-5685-11eb-8b8e-8653645b3de0.png)
## Result
![image](https://user-images.githubusercontent.com/35440615/104564113-7e079f80-5685-11eb-9347-cb84de54dbf2.png)
allow_methods is GET but I use POST  It can also be successful

**Comment by Firstsawyou** [comment]
It is better to provide your etcd configuration information, which helps to troubleshoot problems.

**Comment by membphis** [comment]
@NetRainn do you still have this issue? If yes, please provide your HTTP response header information

**Comment by spacewander** [comment]
Consider solved
