### ISSUE TITLE
feat: add a pre-commit framework

### ISSUE THREAD

**Issue by jbampton** [apache/apisix#3289]
I have used both `pre-commit` and `overcommit`.    

From the `pre-commit` site -> "Git hook scripts are useful for identifying simple issues before submission to code review. We run our hooks on every commit to automatically point out issues in code such as missing semicolons, trailing whitespace, and debug statements. By pointing these issues out before code review, this allows a code reviewer to focus on the architecture of a change while not wasting time with trivial style nitpicks."

Apache Airflow uses a `pre-commit` framework and you can run linters and other checks based in any language to test code before you push to GitHub.  Basically it speeds up the developer feedback loop as in you know about issues before they hit the CI.

I added the Markdown linter to the Apache Airflow `pre-commit` framework and I have another open PR trying to add another check to sort make uniq there custom dictionary.

My view is that `pre-commit` is better but if you like Ruby then `overcommit` is for you.

https://pre-commit.com/
https://github.com/sds/overcommit
https://github.com/apache/airflow/blob/master/.pre-commit-config.yaml

There are a lot of different things you can check with Git hooks for example the next image is using `overcommit` on one of my personal projects:

<img width="861" alt="Screen Shot 2021-01-03 at 9 38 26 am" src="https://user-images.githubusercontent.com/418747/104562914-b367b980-5694-11eb-81aa-62929f854015.png">

There are also pre-written hooks for lots of language this image shows for Golang:

<img width="718" alt="Screen Shot 2020-11-15 at 12 20 10 pm" src="https://user-images.githubusercontent.com/418747/104563591-8e277b00-5695-11eb-9246-730d46aa033b.png">

**Comment by Firstsawyou** [comment]
For me, this is pretty good.

**Comment by membphis** [comment]
wow, I'll make a try with this way. many thx @jbampton

**Comment by kwanhur** [comment]
If `pre-commit` still has its attraction for `APISIX-*` repos, I can move on it. Please let me known.

I'm familiar with `pre-commit`.

**Comment by spacewander** [comment]
We don't need it yet.
