### ISSUE TITLE
request help: I need to get the upstream setting in current router rule when develop a new plugin.

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3294]
### Issue description
 I need to get the upstream setting in current router rule when develop a new plugin like batch_request.
### Environment
 I need to get the upstream setting in current router rule when develop a new plugin like batch_request.
* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by Firstsawyou** [comment]
It can be obtained through the upstream id bound on the route, please refer to here: [https://github.com/apache/apisix/blob/master/apisix/init.lua#L436-L444 ](https://github.com/apache/apisix/blob/master/apisix/init.lua#L436-L444)

**Comment by pengtaochang** [comment]
@Firstsawyou  Thankyou very much, again, I write plugin code  in function _M.access(conf, ctx),  could you pointer me how to get the route object or upstream_id ,  I'd appreciate it.

**Comment by Firstsawyou** [comment]
If your upstream is set on "route" then you can get the upstream through `ctx.matched_route` (upstream_id and service_id can also be obtained through `ctx.matched_route`). You can first view the data structure of "ctx.matched_route" through the log to determine to obtain the corresponding data.

Example:

```lua
core.log.warn("ctx.matched_route: ", core.json.encode(ctx.matched_route))
```

print log:
```
{"createdIndex":14,"modifiedIndex":6278,"has_domain":false,"clean_handlers":{},"value":{"plugins":{"traffic-split":{"rules":[{"weighted_upstreams":[{"upstream":{"hash_on":"vars","pass_host":"pass","type":"roundrobin","nodes":{"127.0.0.1:80":1},"name":"upstream_A"},"weight":1}],"match":[{"vars":[["http_release","==","new_release"]]}]}]}},"uris":["\/hello"],"create_time":1610288363,"status":1,"update_time":1610629287,"priority":0,"upstream":{"hash_on":"vars","type":"roundrobin","nodes":[{"weight":1,"host":"127.0.0.1","port":81}],"pass_host":"pass"},"id":"1"},"key":"\/apisix\/routes\/1"}
```

If your upstream is set to "service" or "upstream" then you need to get it through the corresponding id.

**Comment by pengtaochang** [comment]
Thank you very much, you solved my problem perfectly.
