### ISSUE TITLE
request help: I user apisix proxy a request which using for upload big file (5MB around) , the request raise Error：socket hang up

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3301]
### Issue description
 I user apisix proxy a request which using for upload big file (5MB around) , the request raise Error：socket hang up.

I had test my api server, upload and download api is working well.
### Environment

* apisix version (cmd: `apisix version`):2.0
* OS: (cmd: `uname -a`) ubantu
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) openresty/1.17.8.2

**Comment by Firstsawyou** [comment]
It may be that the file size of the proxy is limited. 
@spacewander  Please help to look at this problem when you have time.

**Comment by tokers** [comment]
Is there any error logs when the socket hang up?

Could you also provide a minimal reproducable case.

**Comment by pengtaochang** [comment]
Sorry, It don't work in Windows WSL but work well in VM server. Sincere thanks.
