### ISSUE TITLE
doc/zh-cn/how-to-build.md 

### ISSUE THREAD

**Issue by admin-xl-2048** [apache/apisix#3302]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

A clear and concise description of what you want and what your use case is.

**Comment by admin-xl-2048** [comment]
There is a small error under this file: CD apache-apisix-2.2 should be changed to CD apisix-2.2

**Comment by idbeta** [comment]
Welcome to pr @admin-xl-2048

**Comment by KafilatAdeleke** [comment]
I"ll fix this.

**Comment by spacewander** [comment]
Already fix in the master branch.
