### ISSUE TITLE
feat: use tool to format lua code automatically

### ISSUE THREAD

**Issue by hnlq715** [apache/apisix#3303]
As title, I can send a PR for this if you guys interested.

**Comment by spacewander** [comment]
This will be a nightmare for `git blame` and `git log -p`...

**Comment by hnlq715** [comment]
@spacewander 
I mean we can choose specific file to format code automatically, when necessary, not format all the existed code.

with makefile support
```
make format $filepath
```

**Comment by spacewander** [comment]
How to distinguish specific file with existed code? There is not a clear boundary for it.

**Comment by hnlq715** [comment]
When we changes a file, we usually do some style fix to the changed file when necessary, and I think this can also be done by a tool.
And auto format is a right way to improve code quality, just like Go? :-)

As for git blame or git log -p, we still remain the whole file changed history, when we need.

After all, this is just a develop tool to be used manually, it all depends on the developer how to use it.

**Comment by spacewander** [comment]
Unlike Go, there is not rule to keep the style consistent from the beginning.
Such a change will make `git blame` and `git log -p` quite hard, even if the whole change is still here.

> After all, this is just a develop tool to be used manually, it all depends on the developer how to use it.

I don't want a tool which might be misused.

**Comment by hnlq715** [comment]
> Unlike Go, there is not rule to keep the style consistent from the beginning.
> Such a change will make `git blame` and `git log -p` quite hard, even if the whole change is still here.
> 
> > After all, this is just a develop tool to be used manually, it all depends on the developer how to use it.
> 
> I don't want a tool which might be misused.

Alright, sad story...
