### ISSUE TITLE
traffic-split var中设置header不能有- 横线

### ISSUE THREAD

**Issue by dw-3** [apache/apisix#3306]
traffic-split 设置如下:

```json
{
  "disable": false,
  "rules": [
    {
      "match": [
        {
          "vars": [
            [
              "http_h-x-strategy-token-cmnet",
              "==",
              "CompanyNetwork"
            ]
          ]
        }
      ],
      "weighted_upstreams": [
        {
          "upstream": {
            "hash_on": "vars",
            "name": "upstream_A",
            "nodes": {
              "10.0.15.97:80": 10
            },
            "pass_host": "pass",
            "type": "roundrobin"
          },
          "weight": 1
        }
      ]
    }
  ]
}
```

apisix 2.2 etcd3.4.0

经测试 如果vars中含有- 横线,会导致校验header失败,请解决

**Comment by membphis** [comment]
@Firstsawyou you can check it

**Comment by membphis** [comment]
before we get the data from header with `vars`, we need to translate `http_h-x-strategy-token-cmnet` to `http_h_x_strategy_token_cmnet`

it should be a bug, we need to fix it.

**Comment by spacewander** [comment]
It is not a bug. There is not a Nginx variable call `http_h-x...`. Maybe we can reject this input in the validation.

**Comment by membphis** [comment]
> we need to translate http_h-x-strategy-token-cmnet to http_h_x_strategy_token_cmnet

https://github.com/apache/apisix/blob/master/apisix/core/ctx.lua#L160

Why did it not take effect?

**Comment by Firstsawyou** [comment]
> @Firstsawyou you can check it

Okay, let me check.

**Comment by spacewander** [comment]
Look like the `eval` target is `ngx.var` but not `ctx.var`:
https://github.com/apache/apisix/blob/bbbdf58d555ee89144b6923e751deabf7e0bbf15/apisix/plugins/traffic-split.lua#L294

**Comment by Firstsawyou** [comment]
> Look like the `eval` target is `ngx.var` but not `ctx.var`:
> https://github.com/apache/apisix/blob/bbbdf58d555ee89144b6923e751deabf7e0bbf15/apisix/plugins/traffic-split.lua#L294

I will submit a PR to fix this problem.
