### ISSUE TITLE
request help: How to count the total amount of URL

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#3309]
### Issue description
Does this apisix support the configuration of the same URL? For example, if the URLs of multiple systems are the same, how can I count the number of calls to each interface

**Comment by Firstsawyou** [comment]
To count the number of calls of each interface, please refer to the `apisix_http_status` indicator of the `prometheus` plugin.

Configure the same uri problem, you can look at this document: [https://github.com/api7/apache-apisix-best-practices/blob/main/getting_started/quick_start_route.md ](https://github.com/api7/apache-apisix-best-practices/blob/main/getting_started/quick_start_route.md)

**Comment by tokers** [comment]
@123libohan You mean calculate the number of access for each URL?

**Comment by 123libohan** [comment]
> To count the number of calls of each interface, please refer to the `apisix_http_status` indicator of the `prometheus` plugin.
> 
> Configure the same uri problem, you can look at this document: [https://github.com/api7/apache-apisix-best-practices/blob/main/getting_started/quick_start_route.md ](https://github.com/api7/apache-apisix-best-practices/blob/main/getting_started/quick_start_route.md)

Here we want to accurately count the calls of each interface. Through Prometheus, there may be the possibility of missing statistics

**Comment by 123libohan** [comment]
> @123libohan You mean calculate the number of access for each URL?

Yes, we want to count the number of calls to each interface, and know the number of successful requests, the number of failed requests, etc

**Comment by tokers** [comment]
@123libohan See the metric in the following link https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L101 to see whether the `http_status` can meet your demands.

**Comment by 123libohan** [comment]
> @123libohan See the metric in the following link https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L101 to see whether the `http_status` can meet your demands.
> 
> It has both of the http stautus code and matched uri labels.

Thank you for your answer, but our side is the business needs, need accurate statistics, not for statistical indicators

**Comment by tokers** [comment]
@123libohan I will suggest you to collect the logs by a couple of logger plugins.

**Comment by 123libohan** [comment]
> @123libohan I will suggest you to collect the logs by a couple of logger plugins.

I see what you mean. I have a scheme to count the call amount in the final return phase of the result. The call amount is stored locally, and then a timing task is set to synchronize the call amount to redis regularly. However, if apisix is restarted, the call amount may be lost

**Comment by 123libohan** [comment]
> @123libohan I will suggest you to collect the logs by a couple of logger plugins.

I see what you mean. I have a scheme to count the call amount in the final return phase of the result. The call amount is stored locally, and then a timing task is set to synchronize the call amount to redis regularly. However, if apimix is restarted, it may lead to the loss of call amount. Do you have a better scheme?

**Comment by tokers** [comment]
Your log data can be transported to external log suite like Kafka. I think it's better to process data use component like ELK, i am not an expert in this domain, you may try to search more best practices about this field.
