### ISSUE TITLE
bug: broken links on download page for 2.3

### ISSUE THREAD

**Issue by sebbASF** [apache/apisix#3315]
The download page [1] asc and sha512 links for version 2.3 are broken.

[1] https://apisix.apache.org/downloads/

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/104830133-cbb71e80-58b6-11eb-98ba-f58b8cac0b6f.png)

The backup site and SVN[1] works, I have no idea why that mirror is broken.

[1] https://dist.apache.org/repos/dist/release/apisix/dashboard/2.3/

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/104830161-15076e00-58b7-11eb-9d5f-c9e64d0d377b.png)

`asc` and `sha512` don't get synced 🤔 How to force it to sync?

**Comment by tokers** [comment]
That's really strange, if i remember correctly, i saw them in this directory 😂.

**Comment by juzhiyuan** [comment]
ya..

**Comment by sebbASF** [comment]
KEYS, sigs and hashes are deliberately excluded from mirrors.

As per instructions[1]

"All links to checksums, detached signatures and public keys for current releases must reference downloads.apache.org/ using https:// (TLS)"

i.e.

https://downloads.apache.org/apisix/KEYS
and
https://downloads.apache.org/apisix/xxx/yyy.sha512 etc

[1] https://infra.apache.org/release-distribution#download-links

**Comment by juzhiyuan** [comment]
thanks, I know what happened.
