### ISSUE TITLE
apisix2.2 traffic-split 支持header中添加-横线报错

### ISSUE THREAD

**Issue by dw-3** [apache/apisix#3323]
链接:
https://github.com/apache/apisix/pull/3310

经测试,替换traffic-split.lua以更新插件后重启apisix后,报错如下:

{"error_msg":"unknown plugin [traffic-split]"}

配置文件中已启用插件:

![image](https://user-images.githubusercontent.com/20983001/104881267-f4651400-599b-11eb-922d-f87d8572e8ad.png)

**Comment by Firstsawyou** [comment]
You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.

**Comment by dw-3** [comment]
> You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.

依然报错
[root@dev-apisix plugins]# ls -l traffic-split.lua 
-rwxrwxrwx. 1 1000 1000 182298 1月  18 14:26 traffic-split.lua
[root@dev-apisix plugins]# pwd
/usr/local/apisix-2.2/apisix/plugins

**Comment by Firstsawyou** [comment]
> > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> 
> 依然报错
> [root@dev-apisix plugins]# ls -l traffic-split.lua
> -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> [root@dev-apisix plugins]# pwd
> /usr/local/apisix-2.2/apisix/plugins

Please check if your local version is 2.2, and I will confirm this issue locally.

**Comment by dw-3** [comment]
> > > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> > 
> > 
> > 依然报错
> > [root@dev-apisix plugins]# ls -l traffic-split.lua
> > -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> > [root@dev-apisix plugins]# pwd
> > /usr/local/apisix-2.2/apisix/plugins
> 
> Please check if your local version is 2.2, and I will confirm this issue locally.


I confirm that the version is 2.2.

[root@dev-apisix apisix-2.2]# ./bin/apisix version
2.2

**Comment by Firstsawyou** [comment]
> > > > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> > > 
> > > 
> > > 依然报错
> > > [root@dev-apisix plugins]# ls -l traffic-split.lua
> > > -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> > > [root@dev-apisix plugins]# pwd
> > > /usr/local/apisix-2.2/apisix/plugins
> > 
> > 
> > Please check if your local version is 2.2, and I will confirm this issue locally.
> 
> I confirm that the version is 2.2.
> 
> [root@dev-apisix apisix-2.2]# ./bin/apisix version
> 2.2

After trying it, the plug-in can be loaded normally, but the latest traffic-split plugin will have an abnormal problem on the v2.2 version, that is, we cannot upgrade on the v2.2 version.

```shell
[error] 18607#18607: *54079 lua entry thread aborted: runtime error: /home/apisix/apisix/plugins/traffic-split.lua:253: missing argument parent
```

However, this abnormal problem has been resolved on the master branch.
Only the code of the master branch can use the latest traffic-split plugin (allow the request header to have a horizontal line: "—").

**Comment by dw-3** [comment]
Do you mean that I can't use the horizontal line in the header of this plugin in version 2.2? Do I need to wait until your major version is updated?

**Comment by dw-3** [comment]
> > > > > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> > > > 
> > > > 
> > > > 依然报错
> > > > [root@dev-apisix plugins]# ls -l traffic-split.lua
> > > > -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> > > > [root@dev-apisix plugins]# pwd
> > > > /usr/local/apisix-2.2/apisix/plugins
> > > 
> > > 
> > > Please check if your local version is 2.2, and I will confirm this issue locally.
> > 
> > 
> > I confirm that the version is 2.2.
> > [root@dev-apisix apisix-2.2]# ./bin/apisix version
> > 2.2
> 
> After trying it, the plug-in can be loaded normally, but the latest traffic-split plugin will have an abnormal problem on the v2.2 version, that is, we cannot upgrade on the v2.2 version.
> 
> ```shell
> [error] 18607#18607: *54079 lua entry thread aborted: runtime error: /home/apisix/apisix/plugins/traffic-split.lua:253: missing argument parent
> ```
> 
> However, this abnormal problem has been resolved on the master branch.
> Only the code of the master branch can use the latest traffic-split plugin (allow the request header to have a horizontal line: "—").

Do you mean that I can't use the horizontal line in the header of this plugin in version 2.2? Do I need to wait until your major version is updated?

**Comment by Firstsawyou** [comment]
> > > > > > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> > > > > 
> > > > > 
> > > > > 依然报错
> > > > > [root@dev-apisix plugins]# ls -l traffic-split.lua
> > > > > -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> > > > > [root@dev-apisix plugins]# pwd
> > > > > /usr/local/apisix-2.2/apisix/plugins
> > > > 
> > > > 
> > > > Please check if your local version is 2.2, and I will confirm this issue locally.
> > > 
> > > 
> > > I confirm that the version is 2.2.
> > > [root@dev-apisix apisix-2.2]# ./bin/apisix version
> > > 2.2
> > 
> > 
> > After trying it, the plug-in can be loaded normally, but the latest traffic-split plugin will have an abnormal problem on the v2.2 version, that is, we cannot upgrade on the v2.2 version.
> > ```shell
> > [error] 18607#18607: *54079 lua entry thread aborted: runtime error: /home/apisix/apisix/plugins/traffic-split.lua:253: missing argument parent
> > ```
> > 
> > 
> > However, this abnormal problem has been resolved on the master branch.
> > Only the code of the master branch can use the latest traffic-split plugin (allow the request header to have a horizontal line: "—").
> 
> Do you mean that I can't use the horizontal line in the header of this plugin in version 2.2? Do I need to wait until your major version is updated?

Yes.

**Comment by membphis** [comment]
@dw-3 I think we can close this issue now

**Comment by dw-3** [comment]
> @dw-3 I think we can close this issue now



> > > > > > > You need to make sure whether the traffic-split plugin exists in the `plugins/` directory. If it exists, you need to check whether the plugin has readable permission.
> > > > > > 
> > > > > > 
> > > > > > 依然报错
> > > > > > [root@dev-apisix plugins]# ls -l traffic-split.lua
> > > > > > -rwxrwxrwx. 1 1000 1000 182298 1月 18 14:26 traffic-split.lua
> > > > > > [root@dev-apisix plugins]# pwd
> > > > > > /usr/local/apisix-2.2/apisix/plugins
> > > > > 
> > > > > 
> > > > > Please check if your local version is 2.2, and I will confirm this issue locally.
> > > > 
> > > > 
> > > > I confirm that the version is 2.2.
> > > > [root@dev-apisix apisix-2.2]# ./bin/apisix version
> > > > 2.2
> > > 
> > > 
> > > After trying it, the plug-in can be loaded normally, but the latest traffic-split plugin will have an abnormal problem on the v2.2 version, that is, we cannot upgrade on the v2.2 version.
> > > ```shell
> > > [error] 18607#18607: *54079 lua entry thread aborted: runtime error: /home/apisix/apisix/plugins/traffic-split.lua:253: missing argument parent
> > > ```
> > > 
> > > 
> > > However, this abnormal problem has been resolved on the master branch.
> > > Only the code of the master branch can use the latest traffic-split plugin (allow the request header to have a horizontal line: "—").
> > 
> > 
> > Do you mean that I can't use the horizontal line in the header of this plugin in version 2.2? Do I need to wait until your major version is updated?
> 
> Yes.
You mean that the current version does not support, then how can I use the current version of other methods to achieve it

**Comment by Firstsawyou** [comment]
Hi, @dw-3 
If you want to use it in the v2.2 version, you need to modify this line of code in the traffic-split plugin as follows:

https://github.com/apache/apisix/blob/e8dcf3793ca40b30047406ac51a79a500356f67b/apisix/plugins/traffic-split.lua#L290

change into:

https://github.com/apache/apisix/blob/1b3e547c5b041693e5a336486e9bc9f160435e53/apisix/plugins/traffic-split.lua#L294

In this way, horizontal lines can be supported. You can give it a try.

**Comment by dw-3** [comment]
> Hi, @dw-3
> If you want to use it in the v2.2 version, you need to modify this line of code in the traffic-split plugin as follows:
> 
> https://github.com/apache/apisix/blob/e8dcf3793ca40b30047406ac51a79a500356f67b/apisix/plugins/traffic-split.lua#L290
> 
> change into:
> 
> https://github.com/apache/apisix/blob/1b3e547c5b041693e5a336486e9bc9f160435e53/apisix/plugins/traffic-split.lua#L294
> 
> In this way, horizontal lines can be supported. You can give it a try.
I tried it during the day and I will report an error :

{"error_msg":"unknown plugin [traffic-split]"}

**Comment by Firstsawyou** [comment]
> > Hi, @dw-3
> > If you want to use it in the v2.2 version, you need to modify this line of code in the traffic-split plugin as follows:
> > https://github.com/apache/apisix/blob/e8dcf3793ca40b30047406ac51a79a500356f67b/apisix/plugins/traffic-split.lua#L290
> > 
> > change into:
> > https://github.com/apache/apisix/blob/1b3e547c5b041693e5a336486e9bc9f160435e53/apisix/plugins/traffic-split.lua#L294
> > 
> > In this way, horizontal lines can be supported. You can give it a try.
> > I tried it during the day and I will report an error :
> 
> {"error_msg":"unknown plugin [traffic-split]"}

It is recommended that you check your environment so that the traffic-split plugin can execute normally. Then try to change it.

**Comment by dw-3** [comment]
> > > Hi, @dw-3
> > > If you want to use it in the v2.2 version, you need to modify this line of code in the traffic-split plugin as follows:
> > > https://github.com/apache/apisix/blob/e8dcf3793ca40b30047406ac51a79a500356f67b/apisix/plugins/traffic-split.lua#L290
> > > 
> > > change into:
> > > https://github.com/apache/apisix/blob/1b3e547c5b041693e5a336486e9bc9f160435e53/apisix/plugins/traffic-split.lua#L294
> > > 
> > > In this way, horizontal lines can be supported. You can give it a try.
> > > I tried it during the day and I will report an error :
> > 
> > 
> > {"error_msg":"unknown plugin [traffic-split]"}
> 
> It is recommended that you check your environment so that the traffic-split plugin can execute normally. Then try to change it.

Thank you very much, I have tried successfully, many of you, especially @Firstsawyou, we use this to achieve grayscale, I hope apisix will get better and better, and I will also promote apisix

**Comment by tokers** [comment]
Consider it had been solved.
