### ISSUE TITLE
bug: test case failed in t/admin/plugin-metadata.t

### ISSUE THREAD

**Issue by hnlq715** [apache/apisix#3333]
### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

https://github.com/apache/apisix/pull/3300/checks?check_run_id=1725227529

### Minimal test code / Steps to reproduce the issue

1. make test

### What's the actual result? (including assertion message & call stack if applicable)
```
t/admin/health-check.t .................... ok

#   Failed test 'TEST 10: hit prometheus route - status code ok'
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 935.
#          got: '200'
#     expected: '403'
# Looks like you failed 1 test of 50.
t/admin/plugin-metadata.t ................. 
Dubious, test returned 1 (wstat 256, 0x100)
```
### What's the expected result?
Pass test case always.

**Comment by spacewander** [comment]
Try to solve it in https://github.com/apache/apisix/pull/3329
I will keep running it repeatedly today, and will mark it ready if things go well.

**Comment by spacewander** [comment]
Consider solved
