### ISSUE TITLE
feat: support to specify the scheme(http/https) in upstream

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3336]
we can specify the schema by the plugin: https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md

This function is too common, I think we should support this option in the upstream object.

Here is an example:

```json
{
    "id": "1",                  # id
    "scheme": "http",               
    "nodes": {"host:80": 100},  # Upstream machine address list, the format is `Address + Port`
    "type":"roundrobin"
}
```

@lilien1010 @spacewander what do you think?

**Comment by membphis** [comment]
@shuaijinchao

**Comment by spacewander** [comment]
Maybe we can use `tls: true`, so https://github.com/apache/apisix/issues/3344 can be handled.

**Comment by lilien1010** [comment]
what if both scheme http and https need to be supported? scheme needs to be array?

**Comment by lilien1010** [comment]
vote for @spacewander  just `tls:ture` sound better

**Comment by membphis** [comment]
> `"scheme": "http",  ` or `"scheme": "https",  `

For users, it is easier to understand. Some users may not know what TLS is, so I think `https` is more common.

**Comment by lilien1010** [comment]
I'd rather call it `enable_https:ture` for easy understanding🌝.
in this plugin, the only options are https and http.
btw if scheme equals `https`, should we still allow http or not?

**Comment by tokers** [comment]
It's more flexible if the scheme is defined for each node.
