### ISSUE TITLE
request help: plugin.lua:90: load_plugin(): failed to load plugin [transformations] err: module 'apisix.stream.plugins.transformations' not found:

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3341]
### Issue description
the error:
2021/01/19 10:28:34 [error] 45#45: *166658 [lua] plugin.lua:90: load_plugin(): failed to load plugin [transformations] err: module 'apisix.stream.plugins.transformations' not found:
	no field package.preload['apisix.stream.plugins.transformations']
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/apisix/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/apisix/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/transformations.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/transformations/init.ljbc'
	no file '/usr/local/openresty/lualib/apisix/stream/plugins/transformations.ljbc'
	no file '/usr/local/openresty/lualib/apisix/stream/plugins/transformations/init.ljbc'
	no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/openresty/lualib/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/lualib/apisix/stream/plugins/transformations/init.lua'
	no file './apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/share/lua/5.1/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/share/lua/5.1/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/apisix/apisix/stream/plugins/transformations.lua'
	no file './apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/share/lua/5.1/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/share/lua/5.1/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/transformations.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/transformations/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/transformations.so'
	no file '/usr/local/openresty/lualib/apisix/stream/plugins/transformations.so'
	no file './apisix/stream/plugins/transformations.so'
	no file '/usr/local/lib/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './apisix/stream/plugins/transformations.so'
	no file '/usr/local/lib/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/stream/plugins/transformations.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/site/lualib/apisix.so'
	no file '/usr/local/openresty/lualib/apisix.so'
	no file './apisix.so'
	no file '/usr/local/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './apisix.so'
	no file '/usr/local/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
	no file '/usr/local/lib/lua/5.1/loadall.so', context: ngx.timer

### Environment
I copy my plugins( transformations.lua ) to /usr/local/apisix/apisix/plugins/ in docker images.
The Dockerfile:
FROM apache/apisix:2.2-centos
COPY plugins/transformations.lua /usr/local/apisix/apisix/plugins
RUN sed -i '/plugins/a\  - transformations' /usr/local/apisix/conf/config-default.yaml

I have the error when start a docker container.
* apisix version (cmd: `apisix version`): 2.2
* OS: (cmd: `uname -a`)ubantu
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)openresty/1.19.3.1

**Comment by spacewander** [comment]
> RUN sed -i '/plugins/a\ - transformations' /usr/local/apisix/conf/config-default.yaml

There is no transformations plugin in APISIX.

**Comment by pengtaochang** [comment]
I write the transformations plugin in local and copy to images through the Dockerfile

**Comment by spacewander** [comment]
There is a bug in your `RUN sed -i '/plugins/a\ - transformations' /usr/local/apisix/conf/config-default.yaml`.


```
@@ -255,6 +256,7 @@ plugins:                          # plugin list (sorted in alphabetical order)
   - traffic-split

 stream_plugins:
+ - transformations # <-- should not modify this line
   - mqtt-proxy
```

I suggest you to copy a config.yaml instead of modifying the exist one.

**Comment by ShaoZeMing** [comment]
目前我自定义插件使用2.12.1版本进行构建，发现也会报错。
