### ISSUE TITLE
bug: After installing version 2.2, access to dashboard generates 403

### ISSUE THREAD

**Issue by wallwind** [apache/apisix#3349]
### Environment

* apisix version (cmd: `apisix version`):   [root@VM_2_6_centos apisix]# apisix version
2.2
* OS: (cmd: `uname -a`)：Linux VM_2_6_centos 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
nginx version: openresty/1.19.3.1
### Minimal test code / Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1772992/105062393-87de3800-5ab5-11eb-9bc8-7aa129b62c77.png)

2.
3.

### What's the expected result?
http://ip:9080/apisix/dashboard

**Comment by Firstsawyou** [comment]
APISIX only allows access to the address of `127.0.0.0/24` by default, you need to allow your client address in the configuration file：[https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L61-L62 ](https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L61-L62)
for example: 

```
allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0 
```

APISIX and dashboard are separate, you need to install dashboard separately: [https://github.com/apache/apisix-dashboard ](https://github.com/apache/apisix-dashboard)

You can refer to related documents to learn more about how to use it.

**Comment by moonming** [comment]
Please use English in the public channel, thx
