### ISSUE TITLE
request help: do you want update skywalking plugin protocal from http1.1 to grpc ?

### ISSUE THREAD

**Issue by xingren23** [apache/apisix#3353]
### Issue description

之前实现skywalking-nginx-lua模块时 lua还不支持http协议，现在apisix已经支持的gRPC协议代理，是不是可以用gRPC协议取代HTTP1.1 协议来上报trace信息？

https://github.com/apache/skywalking/issues/1071

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
Proxy gRPC in C is different from communication via gRPC in Lua.

BTW, we are not the maintainer of skywalking. We don't own https://github.com/apache/skywalking-nginx-lua.
It would be better if you ask this question to them.

**Comment by xingren23** [comment]
> Proxy gRPC in C is different from communication via gRPC in Lua.
> 
> BTW, we are not the maintainer of skywalking. We don't own https://github.com/apache/skywalking-nginx-lua.
> It would be better if you ask this question to them.

Thanks
