### ISSUE TITLE
discuss: should prometheus plugin add route on apisix_http_latency measuremet?

### ISSUE THREAD

**Issue by wy92** [apache/apisix#3358]
https://github.com/apache/apisix/blob/319c3ebefd22cd2949b84d97d196fd2a80630d38/apisix/plugins/prometheus/exporter.lua#L105

**Comment by tokers** [comment]
@wy92 You mean add the per-route data.

**Comment by spacewander** [comment]
Closed as lack of response.

**Comment by Yiyiyimu** [comment]
fixed by #3993 
https://github.com/apache/apisix/blob/19dbe3456f29c7847b64da8e72136e548c131114/apisix/plugins/prometheus/exporter.lua#L146-L158
