### ISSUE TITLE
issue of traffic split vars

### ISSUE THREAD

**Issue by dw-3** [apache/apisix#3359]
curl http://127.0.0.1:80/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "traffic-split": {
            "rules": [
                {
                    "match": [
                        {
                            "vars": [
                                ["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]
                            ],
                            "vars": [
                                ["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]
                            ]
                        }
                    ],
                    "weighted_upstreams": [
                        {
                            "upstream": {
                                "name": "upstream_A",
                                "type": "roundrobin",
                                "nodes": {
                                    "127.0.0.1:1981":10
                                }
                            },
                            "weight": 3
                        },
                        {
                            "weight": 2
                        }
                    ]
                }
            ]
        }
    },
    "upstream": {
            "type": "roundrobin",
            "nodes": {
                "127.0.0.1:1980": 1
            }
    }
}'

etcd result:
{
    "update_time":1611131384,
    "upstream":{
        "type":"roundrobin",
        "hash_on":"vars",
        "nodes":{
            "127.0.0.1:1980":1
        },
        "pass_host":"pass"
    },
    "plugins":{
        "traffic-split":{
            "rules":[
                {
                    "match":[
                        {
                            "vars":[
                                [
                                    "cookie_h-x-strategy-token-cmnet",
                                    "==",
                                    "CompanyNetwork"
                                ]
                            ]
                        }
                    ],
                    "weighted_upstreams":[
                        {
                            "weight":3,
                            "upstream":{
                                "nodes":{
                                    "127.0.0.1:1981":10
                                },
                                "type":"roundrobin",
                                "hash_on":"vars",
                                "pass_host":"pass",
                                "name":"upstream_A"
                            }
                        },
                        {
                            "weight":2
                        }
                    ]
                }
            ]
        }
    },
    "create_time":1611130637,
    "priority":0,
    "id":"1",
    "uri":"/index.html",
    "status":1
}

vars http 不见了

**Comment by moonming** [comment]
@dw-3 
Please use English in the public channel, thx

**Comment by moonming** [comment]
and format your json for human read

**Comment by dw-3** [comment]
> and format your json for human read

I entered json, and it changed in github

**Comment by dw-3** [comment]
> > and format your json for human read
> 
> I entered json, and it changed in github

{
    "update_time":1611131384,
    "upstream":{
        "type":"roundrobin",
        "hash_on":"vars",
        "nodes":{
            "127.0.0.1:1980":1
        },
        "pass_host":"pass"
    },
    "plugins":{
        "traffic-split":{
            "rules":[
                {
                    "match":[
                        {
                            "vars":[
                                [
                                    "cookie_h-x-strategy-token-cmnet",
                                    "==",
                                    "CompanyNetwork"
                                ]
                            ]
                        }
                    ],
                    "weighted_upstreams":[
                        {
                            "weight":3,
                            "upstream":{
                                "nodes":{
                                    "127.0.0.1:1981":10
                                },
                                "type":"roundrobin",
                                "hash_on":"vars",
                                "pass_host":"pass",
                                "name":"upstream_A"
                            }
                        },
                        {
                            "weight":2
                        }
                    ]
                }
            ]
        }
    },
    "create_time":1611130637,
    "priority":0,
    "id":"1",
    "uri":"/index.html",
    "status":1
}

**Comment by Firstsawyou** [comment]
Hi, @dw-3 

You need to set the vars part like this:

```json
{
"uri": "/index.html",
"plugins": {
"traffic-split": {
"rules": [
{
"match": [
{
"vars": [["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
},
{
"vars": [["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
}
],
"weighted_upstreams": [
{
"upstream": {
"name": "upstream_A",
"type": "roundrobin",
"nodes": {
"127.0.0.1:1981":10
}
},
"weight": 3
},
{
"weight": 2
}
]
}
]
}
},
"upstream": {
"type": "roundrobin",
"nodes": {
"127.0.0.1:1980": 1
}
}
}
```
The format of many vars examples in the documentation is incorrect, I will fix it later.

**Comment by dw-3** [comment]
> Hi, @dw-3
> 
> You need to set the vars part like this:
> 
> ```json
> {
> "uri": "/index.html",
> "plugins": {
> "traffic-split": {
> "rules": [
> {
> "match": [
> {
> "vars": [["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> },
> {
> "vars": [["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> }
> ],
> "weighted_upstreams": [
> {
> "upstream": {
> "name": "upstream_A",
> "type": "roundrobin",
> "nodes": {
> "127.0.0.1:1981":10
> }
> },
> "weight": 3
> },
> {
> "weight": 2
> }
> ]
> }
> ]
> }
> },
> "upstream": {
> "type": "roundrobin",
> "nodes": {
> "127.0.0.1:1980": 1
> }
> }
> }
> ```
> 
> The format of many vars examples in the documentation is incorrect, I will fix it later.

Please let me know after the update, we are still waiting for the test, thank you

**Comment by Firstsawyou** [comment]
> > Hi, @dw-3
> > You need to set the vars part like this:
> > ```json
> > {
> > "uri": "/index.html",
> > "plugins": {
> > "traffic-split": {
> > "rules": [
> > {
> > "match": [
> > {
> > "vars": [["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> > },
> > {
> > "vars": [["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> > }
> > ],
> > "weighted_upstreams": [
> > {
> > "upstream": {
> > "name": "upstream_A",
> > "type": "roundrobin",
> > "nodes": {
> > "127.0.0.1:1981":10
> > }
> > },
> > "weight": 3
> > },
> > {
> > "weight": 2
> > }
> > ]
> > }
> > ]
> > }
> > },
> > "upstream": {
> > "type": "roundrobin",
> > "nodes": {
> > "127.0.0.1:1980": 1
> > }
> > }
> > }
> > ```
> > 
> > 
> > The format of many vars examples in the documentation is incorrect, I will fix it later.
> 
> Please let me know after the update, we are still waiting for the test, thank you

OK, I will notify you after the update.

**Comment by Firstsawyou** [comment]
> > Hi, @dw-3
> > You need to set the vars part like this:
> > ```json
> > {
> > "uri": "/index.html",
> > "plugins": {
> > "traffic-split": {
> > "rules": [
> > {
> > "match": [
> > {
> > "vars": [["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> > },
> > {
> > "vars": [["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> > }
> > ],
> > "weighted_upstreams": [
> > {
> > "upstream": {
> > "name": "upstream_A",
> > "type": "roundrobin",
> > "nodes": {
> > "127.0.0.1:1981":10
> > }
> > },
> > "weight": 3
> > },
> > {
> > "weight": 2
> > }
> > ]
> > }
> > ]
> > }
> > },
> > "upstream": {
> > "type": "roundrobin",
> > "nodes": {
> > "127.0.0.1:1980": 1
> > }
> > }
> > }
> > ```
> > 
> > 
> > The format of many vars examples in the documentation is incorrect, I will fix it later.
> 
> Please let me know after the update, we are still waiting for the test, thank you

Hi, @dw-3 
The docs has been updated: [https://github.com/apache/apisix/pull/3366 ](https://github.com/apache/apisix/pull/3366)

**Comment by dw-3** [comment]
> ```json
> {
> "uri": "/index.html",
> "plugins": {
> "traffic-split": {
> "rules": [
> {
> "match": [
> {
> "vars": [["http_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> },
> {
> "vars": [["cookie_h-x-strategy-token-cmnet","==","CompanyNetwork"]]
> }
> ],
> "weighted_upstreams": [
> {
> "upstream": {
> "name": "upstream_A",
> "type": "roundrobin",
> "nodes": {
> "127.0.0.1:1981":10
> }
> },
> "weight": 3
> },
> {
> "weight": 2
> }
> ]
> }
> ]
> }
> },
> "upstream": {
> "type": "roundrobin",
> "nodes": {
> "127.0.0.1:1980": 1
> }
> }
> }
> ```

I tried it, yes, thanks

**Comment by dw-3** [comment]
OK
