### ISSUE TITLE
discuss: should we support the etcd missing some special keys case

### ISSUE THREAD

**Issue by yongboy** [apache/apisix#3362]
Sometimes, we may not need some keys below existing in ETCD, or maybe deleted by some OPS.

| Key | Value    |
|-----|----------|
| /apisix/services | init_dir |
| /apisix/node_status | init_dir |
| /apisix/ssl | init_dir |
| /apisix/global_rules | init_dir |
| /apisix/stream_routes | init_dir |
| /apisix/proto | init_dir |
| /apisix/plugin_metadata | init_dir |
| ... | ... |

In that case, when the nginx's worker process got reload signal, which will not load all the data from ETCD failure.

En, should I to submit a PR to fix the BUG ?

PS:

The PR code below is working well with Apisix 2.2  in my online env now ~

The `apisix.core.config-etcd.lua` ori code:

```lua
            if not dir_res.nodes then
                dir_res.nodes = {}
            end
```

My way:

```lua
            if not dir_res.nodes then
                if dir_res.key then
                    dir_res.nodes = { clone_tab(dir_res) }
                else
                    dir_res.nodes = {}
                end
            end
```

**Comment by nic-chen** [comment]
I remember that if these keys (`/apisix/routes`, `/apisix/services`, etc.) do not exist, the ETCD watch will fail. 
@Yiyiyimu  please have a look.

**Comment by yongboy** [comment]
Here is the PR: #3372

**Comment by Yiyiyimu** [comment]
> I remember that if these keys (`/apisix/routes`, `/apisix/services`, etc.) do not exist, the ETCD watch will fail.
> @Yiyiyimu please have a look.

Yeah I remember the same. But lots of things got optimized after my attempt, and it would be great if we could get rid of them. I'll help to track the PR
