### ISSUE TITLE
request help: How to use apisix proxy apisix-dashboard

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3364]
### Issue description
I want to user apisix proxy the apisix dashboard, but don't know what need to do.
Thanks.
### Environment
apisix-dashboard 2.3
* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`)ubantu
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)openresty/1.19.3.1

**Comment by Firstsawyou** [comment]
APISIX and Dashboard are two independent projects, and there is no attempt to proxy Dashboard in the past.

**Comment by Miss-you** [comment]
1. apisix route should use the `radixtree_host_uri` mod.
2. create a route as follow:
```
host: dashboarddomain
uri:/
upstream:dashboard addr
```
3. then you can access the dashboard by url `dashboarddomain/xxx`

**Comment by pengtaochang** [comment]
thanks @Miss-you @Firstsawyou
