### ISSUE TITLE
bug: http service should not be started before etcd data is pulled

### ISSUE THREAD

**Issue by hizzd** [apache/apisix#3370]
### Issue description
that when accessing immediately after apisix is started, it will return:
```json
{"error_msg ": "404 Route Not Found"}
```
Is it because apisix did not pull the route data in etcd in time?
maybe the http service of apisix should be started after pulling etcd data.

### Environment

* apisix version: [docker] apache/apisix:2.2-alpine
* OS: [docker] apache/apisix:2.2-alpine
* OpenResty / Nginx version: [docker] apache/apisix:2.2-alpine
* etcd enabled auto-tls.
* apisix disable etcd.tls.verify.

**Comment by spacewander** [comment]
This is a known issue. We plan to start pulling etcd data in the `init_worker` phase. To achieve this, we need to implement two preconditions first:
1. add Chaos test so that we can cover such a big change
2. allow lua-resty-etcd to use luasocket.

Maybe we can do this in version `2.5`.
