### ISSUE TITLE
request help: The proxy-cache plugin overrides `Cache-Control` in upstream header.

### ISSUE THREAD

**Issue by myWsq** [apache/apisix#3373]
### Issue description

The proxy cache plugin overrides the Cache Control in the upstream header, even if the plugin is not used in the route.

https://github.com/apache/apisix/blob/e3601e6876e13a44fa8102fa19a41b4bc1a080e2/apisix/cli/ngx_tpl.lua#L511-L536

Disabling the plugin in `config.yml` solves this problem, but some routes need to enable the plugin. How should I preserve the Cache Control in the upstream header with the proxy cache plugin globally enabled?

### Environment

* apisix version: 2.2
* OS:  Linux 7cc563f53b08 4.19.121-linuxkit #1 SMP Tue Dec 1 17:50:32 UTC 2020 x86_64 Linux
* OpenResty / Nginx version:  nginx version: openresty/1.19.3.1

**Comment by spacewander** [comment]
```
             proxy_hide_header                   Cache-Control; 
             proxy_hide_header                   Expires; 
             add_header      Cache-Control       $upstream_hdr_cache_control; 
             add_header      Expires             $upstream_hdr_expires; 
             add_header      Apisix-Cache-Status $upstream_cache_status always; 
```

We can remove them from the Nginx conf, and implement them in https://github.com/apache/apisix/blob/aff1a907a3671bd6610b304a54ebef47022ca6cf/apisix/plugins/proxy-cache.lua#L251

PR is welcome!
