### ISSUE TITLE
Modify the 500 response code in the upstream.lua file to 503 response code

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3374]
### Issue description

The `500` response code should be changed to a `503` response code. Because this is a situation where upstream cannot work.
Code link: [https://github.com/apache/apisix/blob/master/apisix/upstream.lua#L125-L168 ](https://github.com/apache/apisix/blob/master/apisix/upstream.lua#L125-L168)

### Environment

* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)

**Comment by spacewander** [comment]
This will break the compatibility. Is there a strong reason to do the change?

**Comment by Firstsawyou** [comment]
> This will break the compatibility. Is there a strong reason to do the change?

The 500 response code represents a problem caused by an error in the program code. However, this is caused by no upstream available. Obviously, the 500 response code is not standardized, which makes people understand that there is a bug in the code program.

**Comment by spacewander** [comment]
OK, let's do it.
