### ISSUE TITLE
discuss: the discovery module need more features

### ISSUE THREAD

**Issue by yongboy** [apache/apisix#3375]
For the practice need, our consul key-value discovery module(eg: `apisix/discovery/consul_kv.lua`) need some features below:

1. export `service_version()` method
    - export for the `balancer.lua`, for avoiding got unregistered invalid nodes when handle request
    - return number, eg: `return 1`
2. export control api for debugging

Any ideas are welcome  :))

I will submit a PR later ~

**Comment by spacewander** [comment]
I am not quite understand what you need. But you can submit a PR first so we can discuss with the code.
