### ISSUE TITLE
request help: how do i know plugin Orchestration condition variables

### ISSUE THREAD

**Issue by jaredhuang** [apache/apisix#3383]
### Issue description
how do i know plugin Orchestration condition variables 。
In the video:
[https://static.apiseven.com/low-code-api-gateway-example-en-US.mp4](https://static.apiseven.com/low-code-api-gateway-example-en-US.mp4)  Condition is  code == 403 , the keyword "code" is a variables? how do i know variables list ? 

### Environment
* apisix version (cmd: `apisix version`):
2.1
* OS: (cmd: `uname -a`)
5.8.0-1.el7.elrepo.x86_64
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
openresty/1.19.3.1

**Comment by spacewander** [comment]
CC @juzhiyuan @nic-chen

**Comment by nic-chen** [comment]
In theory, you could use any variable that exists and can be accessed here. 

But we recommend using `code` which returned by the plugin phase functions.

**Comment by jaredhuang** [comment]
@nic-chen How to understand "the plugin phase functions" ，have  example?

**Comment by nic-chen** [comment]
@jaredhuang  
here is an example(rewrite phase function of `basic-suth`):
https://github.com/apache/apisix/blob/master/apisix/plugins/basic-auth.lua#L128-L169

and `code` is 401 :
```lua
return 401, { message = "Password is error" }
```

**Comment by jaredhuang** [comment]
@nic-chen  TKS
