### ISSUE TITLE
request help: unbalanced message in kafka partition using kafka-logger plugin

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#3384]
### Issue description
I used the `kafka-logger` plugin and saw in kafka's monitor that all messages are placed in the same partition by kafka.
I didn't set the `key` parameter of the `kafka-logger` plugin.
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`):centos
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)1.19.2

Doubtful places
The `kafka-logger` plugin creates a new producer instance to connect to kafka every time it pushes a message, which causes kafka to reallocate the partition each time, leading to the above phenomenon, please correct me.

**Comment by spacewander** [comment]
Maybe we can reuse producer via lrucache, like this: https://github.com/apache/apisix/blob/e5916cf541281e7fe756dd2e393bd6dcf702c220/apisix/plugins/limit-req.lua#L67?

**Comment by tzssangglass** [comment]
> Maybe we can reuse producer via lrucache, like this:
> 
> https://github.com/apache/apisix/blob/e5916cf541281e7fe756dd2e393bd6dcf702c220/apisix/plugins/limit-req.lua#L67
> 
> ?

yep, I think it's a great way.

**Comment by tokers** [comment]
> > Maybe we can reuse producer via lrucache, like this:
> 
> > 
> 
> > https://github.com/apache/apisix/blob/e5916cf541281e7fe756dd2e393bd6dcf702c220/apisix/plugins/limit-req.lua#L67
> 
> > 
> 
> > ?
> 
> 
> 
> yep, I think it's a great way.

Welcome pr!

**Comment by tzssangglass** [comment]
assigned me this
