### ISSUE TITLE
request help: does the proxy_cache plugin support static resource cache

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3390]
### Issue description
does the `proxy_cache` plugin support static resource cache,
such as nginx config `location ~* /service_a/(.*)\.(png|jpg|js|css)$`

### Environment

* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`)centos7.5

**Comment by Firstsawyou** [comment]
Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?

**Comment by gewei2000** [comment]
> Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?

let me try

**Comment by Firstsawyou** [comment]
> > Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?
> 
> let me try

You can refer to this document for configuration：[https://github.com/apache/apisix/blob/master/doc/customize-nginx-configuration.md ](https://github.com/apache/apisix/blob/master/doc/customize-nginx-configuration.md)

**Comment by membphis** [comment]
> Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?

this is not a best way in APISIX. we can use the Route + proxy cache plugin to implement this feature

**Comment by gewei2000** [comment]
> > Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?
> 
> this is not a best way in APISIX. we can use the Route + proxy cache plugin to implement this feature.
> 
> Route: match the request `/service_a/(.*)\.(png|jpg|js|css)$`
> Proxy-cache plugin: implement the proxy and cache file.

let me try this way

**Comment by gewei2000** [comment]
> > Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?
> 
> this is not a best way in APISIX. we can use the Route + proxy cache plugin to implement this feature.
> 
> Route: match the request `/service_a/(.*)\.(png|jpg|js|css)$`
> Proxy-cache plugin: implement the proxy and cache file.

can not match any route

route config
```
{
	"id": "1",
	"name": "static_cache",
	"plugins": {
		"proxy-cache": {
			"cache_zone": "disk_cache_one",
			"cache_key": ["$host", "$uri", "$is_args", "$args"],
			"cache_bypass": ["$arg_bypass"],
			"cache_method": ["GET"],
			"cache_http_status": [200],
			"hide_cache_headers": true,
			"no_cache": ["$arg_test"]
		}
	},
	"upstream_id": "1",
	"uris": ["/service_a/(.*)\\.(png|jpg|js|css)$"]
}
```

debug log
```
2021/01/22 13:52:53 [info] 39#39: *4987 [lua] init.lua:387: http_access_phase(): not find any matched route, client: 10.0.0.3, server: , request: "GET /service_a/111.png HTTP/1.1", host: "10.1.2.2:9081"
```

**Comment by Firstsawyou** [comment]
> not find any matched route,

Hi, @gewei2000  What is the `uri` you request for this route?

**Comment by Firstsawyou** [comment]
> > not find any matched route,
> 
> Hi, @gewei2000 What is the `uri` you request for this route?

Sorry, I saw it in the log information.

**Comment by Firstsawyou** [comment]
> > > Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?
> > 
> > 
> > this is not a best way in APISIX. we can use the Route + proxy cache plugin to implement this feature.
> > Route: match the request `/service_a/(.*)\.(png|jpg|js|css)$`
> > Proxy-cache plugin: implement the proxy and cache file.
> 
> can not match any route
> 
> route config
> 
> ```
> {
> 	"id": "1",
> 	"name": "static_cache",
> 	"plugins": {
> 		"proxy-cache": {
> 			"cache_zone": "disk_cache_one",
> 			"cache_key": ["$host", "$uri", "$is_args", "$args"],
> 			"cache_bypass": ["$arg_bypass"],
> 			"cache_method": ["GET"],
> 			"cache_http_status": [200],
> 			"hide_cache_headers": true,
> 			"no_cache": ["$arg_test"]
> 		}
> 	},
> 	"upstream_id": "1",
> 	"uris": ["/service_a/(.*)\\.(png|jpg|js|css)$"]
> }
> ```
> 
> debug log
> 
> ```
> 2021/01/22 13:52:53 [info] 39#39: *4987 [lua] init.lua:387: http_access_phase(): not find any matched route, client: 10.0.0.3, server: , request: "GET /service_a/111.png HTTP/1.1", host: "10.1.2.2:9081"
> ```

There is an extra `\` in this `/service_a/(.*)\\.(png|jpg|js|css)$` uris, which should look like this: `/service_a/(.*)\.(png|jpg|js|css)$`

**Comment by gewei2000** [comment]
> > > > Configure `location ~* /service_a/(.*)\.(png|jpg|js|css)$` in apisix, can it solve your problem?
> > > 
> > > 
> > > this is not a best way in APISIX. we can use the Route + proxy cache plugin to implement this feature.
> > > Route: match the request `/service_a/(.*)\.(png|jpg|js|css)$`
> > > Proxy-cache plugin: implement the proxy and cache file.
> > 
> > 
> > can not match any route
> > route config
> > ```
> > {
> > 	"id": "1",
> > 	"name": "static_cache",
> > 	"plugins": {
> > 		"proxy-cache": {
> > 			"cache_zone": "disk_cache_one",
> > 			"cache_key": ["$host", "$uri", "$is_args", "$args"],
> > 			"cache_bypass": ["$arg_bypass"],
> > 			"cache_method": ["GET"],
> > 			"cache_http_status": [200],
> > 			"hide_cache_headers": true,
> > 			"no_cache": ["$arg_test"]
> > 		}
> > 	},
> > 	"upstream_id": "1",
> > 	"uris": ["/service_a/(.*)\\.(png|jpg|js|css)$"]
> > }
> > ```
> > 
> > 
> > debug log
> > ```
> > 2021/01/22 13:52:53 [info] 39#39: *4987 [lua] init.lua:387: http_access_phase(): not find any matched route, client: 10.0.0.3, server: , request: "GET /service_a/111.png HTTP/1.1", host: "10.1.2.2:9081"
> > ```
> 
> There is an extra `\` in this `/service_a/(.*)\\.(png|jpg|js|css)$` uris, which should look like this: `/service_a/(.*)\.(png|jpg|js|css)$`

This is an escape character.
![image](https://user-images.githubusercontent.com/10362371/105472820-56dd4d80-5cd7-11eb-9219-56086d33da9e.png)

**Comment by gewei2000** [comment]
@membphis @Firstsawyou

**Comment by Firstsawyou** [comment]
> @membphis @Firstsawyou

Okay, let me check.

**Comment by Firstsawyou** [comment]
The way of `/service_a/(.*)\\.(png|jpg|js|css)$` is correct, but I found that regular configuration is not supported in `uris`.

**Comment by gewei2000** [comment]
> The way of `/service_a/(.*)\\.(png|jpg|js|css)$` is correct, but I found that regular configuration is not supported in `uris`.

bug?

**Comment by Firstsawyou** [comment]
> > The way of `/service_a/(.*)\\.(png|jpg|js|css)$` is correct, but I found that regular configuration is not supported in `uris`.
> 
> bug?

I don't think it's a bug, maybe we need to support it.

@membphis  Regular matching is not supported in `uri`, right?

**Comment by membphis** [comment]
@gewei2000 @Firstsawyou here is an example, please take a look at, I think it will help you:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/service_a/*",
    "vars": [["uri", "~~", "(.jpg|.html)$"]],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```

**Comment by membphis** [comment]
> I don't think it's a bug, maybe we need to support it.

I think we have supported this case, please take a look at comment: https://github.com/apache/apisix/issues/3390#issuecomment-766533343

**Comment by Firstsawyou** [comment]
> @gewei2000 @Firstsawyou here is an example, please take a look at, I think it will help you:
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
> {
>     "uri": "/service_a/*",
>     "vars": [["uri", "~~", "(.jpg|.html)$"]],
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "127.0.0.1:1980": 1
>         }
>     }
> }'
> ```

@membphis  Ok, I get it , thanks！

**Comment by gewei2000** [comment]
> @gewei2000 @Firstsawyou here is an example, please take a look at, I think it will help you:
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
> {
>     "uri": "/service_a/*",
>     "vars": [["uri", "~~", "(.jpg|.html)$"]],
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "127.0.0.1:1980": 1
>         }
>     }
> }'
> ```

thanks a lot
