### ISSUE TITLE
bug: timeout in upstream_schema can be set to zero, but in fact not workable.

### ISSUE THREAD

**Issue by wfgydbu** [apache/apisix#3392]
### Issue description
field "timeout" in upstream_schema can not be zero.

https://github.com/apache/apisix/blob/bf16615583c7645d51473f66fd5a970c9740afc4/apisix/schema_def.lua#L314

### Environment

* apisix version (cmd: `apisix version`):  2.2 
* OS: (cmd: `uname -a`) centos 7.6
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`) openresty/1.17.8.2

### Minimal test code / Steps to reproduce the issue

1. setup route: 
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "timeout": {
            "connect": 0,
            "send": 0,
            "read": 0
        },
        "nodes": {
            "127.0.0.1:8000": 10
        }
    }
}'
```
OK.

2. run `curl http://127.0.0.1:9080`, return 500
3.error.log
```
2021/01/22 09:52:16 [error] 3537781#3537781: *442240 failed to run balancer_by_lua*: /kvm-hyt/onest-balancer/apisix/balancer.lua:107: bad connect timeout
stack traceback:
	[C]: in function 'error'
	/usr/local/openresty/lualib/ngx/balancer.lua:175: in function 'set_timeouts'
	/kvm-hyt/onest-balancer/apisix/balancer.lua:107: in function 'pick_server'
	/kvm-hyt/onest-balancer/apisix/balancer.lua:194: in function 'load_balancer'
	/kvm-hyt/onest-balancer/apisix/init.lua:708: in function 'http_balancer_phase'
	balancer_by_lua:2: in main chunk while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", host: "127.0.0.1:9080"
```

### What's the actual result? (including assertion message & call stack if applicable)
Error in error.log, 

### What's the expected result?
timeouts actually cannot be zero

**Comment by spacewander** [comment]
We need to change `minimum` to `exclusiveMinimum`. Would you contribute a PR? Remember to add a test for it.

**Comment by wfgydbu** [comment]
I would love to, but I'm actually pretty new with the test part. I may need some help here.

If you are OK with the latter part and not in a rush to fix this, I will do it.

**Comment by spacewander** [comment]
You can add a case in t/admin/upstream2.t like this one:
https://github.com/apache/apisix/blob/d698220341776791f6e34568e0a17d52ab517919/t/admin/upstream.t#L323

**Comment by spacewander** [comment]
You can submit a draft PR and make it pass later.

**Comment by wfgydbu** [comment]
OK, I will to do it, ASAP. Feel free to assign it to me.
