### ISSUE TITLE
Update Dashboard's screenshot

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3397]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

I see there have some pages[1] which still include 1.0 Dashboard's screenshot.

[1] https://github.com/apache/apisix/blob/master/doc/plugins/zipkin.md
[1] need to find out

## Describe the solution you'd like

1. Remove those screenshots from documentation and folders;
2. Take the latest screenshots from here[1].

[1] https://github.com/apache/apisix-dashboard#demo

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Please assign this issue to me.

**Comment by starsz** [comment]
> Hi @juzhiyuan
> 
> Please assign this issue to me.

Sure. Much appreciated.

**Comment by juzhiyuan** [comment]
duplicate with https://github.com/apache/apisix/issues/3711#issuecomment-788550616

**Comment by juzhiyuan** [comment]
@stu01509 Hi, you could take a look at #3711
