### ISSUE TITLE
request help: no cors header return sometimes

### ISSUE THREAD

**Issue by rogerogers** [apache/apisix#3407]
### Environment

* apisix version: 2.2
* OS: Linux localhost.localdomain 5.9.13-200.fc33.x86_64 #1 SMP Tue Dec 8 15:42:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux fedora 33
* OpenResty / Nginx version: nginx version: openresty/1.19.3.1
built by gcc 10.2.1 20201016 (Red Hat 10.2.1-6) (GCC) 
built with OpenSSL 1.1.1h  22 Sep 2020 (running with OpenSSL 1.1.1i  8 Dec 2020)

### Minimal test code / Steps to reproduce the issue

1. wrong header
![image](https://user-images.githubusercontent.com/40619032/105658374-4f00f180-5f01-11eb-8f97-450456ef4282.png)

2. right header
![image](https://user-images.githubusercontent.com/40619032/105658476-7e176300-5f01-11eb-9a1f-0ad39ffb6408.png)

my cors config in a service group
`{
  "allow_credential": true,
  "allow_headers": "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Arg-Id",
  "allow_methods": "GET,POST,OPTIONS",
  "allow_origins": "http://m-local.guess.com,http://www-local.guess.com",
  "disable": false,
  "expose_headers": "Authorization"
}`

**Comment by spacewander** [comment]
I can't see the word in your images.
You need to provide reproducible steps in text.

**Comment by rogerogers** [comment]
> I can't see the word in your images.
> You need to provide reproducible steps in text.

It's just a browser request list, sometime no cors header return, but not always. like this
`HTTP/1.1 200 OK
Server: openresty
Date: Mon, 25 Jan 2021 05:32:58 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive`

**Comment by spacewander** [comment]
What you said is **not** a reproducible steps. I can't follow your word to create an environment to reproduce the issue, so I can't help you to solve the problem.

**Comment by spacewander** [comment]
For the "sometimes" problem, you should add more log in the cors plugin, to see what happened when the error occurs.
For example:
https://github.com/apache/apisix/blob/8904011fa8321358b7fb31f612cca887fa23ff28/apisix/plugins/cors.lua#L168
You should log down the `ctx.conf_type`, `ctx.conf_id` and returned `multiple_origin`.

**Comment by tokers** [comment]
@rogerogers Also, the configuration like Route, Upstream of APISIX should be provided here.

**Comment by rogerogers** [comment]
> @rogerogers Also, the configuration like Route, Upstream of APISIX should be provided here.

### Here is the metadata in etcd
* service {"id":"338649582328091268","create_time":1611380480,"update_time":1611544897,"name":"api-local","upstream_id":"338680447942791812","plugins":{"cors":{"allow_credential":true,"allow_headers":"DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization,Arg-Id","allow_methods":"GET,POST,OPTIONS","allow_origins":"http://m-local.guess.com,http://www-local.guess.com","disable":false,"expose_headers":"Authorization"}}}
* route {"id":"338680561356771972","create_time":1611398945,"update_time":1611543793,"uris":["/*"],"name":"api-local","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"hosts":["api-local.guess.com"],"vars":[],"service_id":"338649582328091268","upstream_id":"338680447942791812","status":1}

**Comment by rogerogers** [comment]
> For the "sometimes" problem, you should add more log in the cors plugin, to see what happened when the error occurs.
> For example:
> https://github.com/apache/apisix/blob/8904011fa8321358b7fb31f612cca887fa23ff28/apisix/plugins/cors.lua#L168
> 
> 
> You should log down the `ctx.conf_type`, `ctx.conf_id` and returned `multiple_origin`.

### code
* <pre>local multiple_origin, err = core.lrucache.plugin_ctx(lrucache, ctx, nil,
                                                create_multiple_origin_cache, conf)
  local json=require('cjson.safe')
  core.log.error(json.encode(multiple_origin))
</pre>

* <pre>local allow_methods = conf.allow_methods
  core.log.error(conf.allow_methods.. 'guess')
  if allow_methods == "**" then
      allow_methods = "GET,POST,PUT,DELETE,PATCH,HEAD,OPTIONS,CONNECT,TRACE"
  end
  core.response.set_header("Access-Control-Allow-Origin", ctx.cors_allow_origins)
  core.log.error(ctx.cors_allow_origins)
</pre>

### logs
* 2021/01/26 10:30:38 [error] 3816274#3816274: *1473 [lua] cors.lua:173: phase_func(): {"http:\/\/m-local.guess.com":true,"http:\/\/www-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/comments HTTP/1.0", upstream: "http://127.0.0.1:9505/products/comments", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:38 [error] 3816274#3816274: *1473 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/comments HTTP/1.0", upstream: "http://127.0.0.1:9505/products/comments", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:38 [error] 3816274#3816274: *1473 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/comments HTTP/1.0", upstream: "http://127.0.0.1:9505/products/comments", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:38 [error] 3816273#3816273: *1469 [lua] cors.lua:173: phase_func(): {"http:\/\/www-local.guess.com":true,"http:\/\/m-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:38 [error] 3816273#3816273: *1469 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:38 [error] 3816273#3816273: *1469 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:38 [error] 3816273#3816273: *1538 [lua] cors.lua:173: phase_func(): {"http:\/\/www-local.guess.com":true,"http:\/\/m-local.guess.com":true}, client: 127.0.0.1, server: , request: "OPTIONS /products/recommend HTTP/1.0", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:38 [error] 3816273#3816273: *1538 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess, client: 127.0.0.1, server: , request: "OPTIONS /products/recommend HTTP/1.0", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:38 [error] 3816273#3816273: *1538 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com, client: 127.0.0.1, server: , request: "OPTIONS /products/recommend HTTP/1.0", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:39 [error] 3816276#3816276: *1540 [lua] cors.lua:173: phase_func(): {"http:\/\/m-local.guess.com":true,"http:\/\/www-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:39 [error] 3816276#3816276: *1540 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:39 [error] 3816276#3816276: *1540 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"

* 2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:173: phase_func(): {"http:\/\/m-local.guess.com":true,"http:\/\/www-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:173: phase_func(): {"http:\/\/m-local.guess.com":true,"http:\/\/www-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail"
2021/01/26 10:30:42 [error] 3816275#3816275: *1750 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/v3/detail HTTP/1.0", upstream: "http://127.0.0.1:9505/products/v3/detail", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:43 [error] 3816275#3816275: *1805 [lua] cors.lua:173: phase_func(): {"http:\/\/m-local.guess.com":true,"http:\/\/www-local.guess.com":true} while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:43 [error] 3816275#3816275: *1805 [lua] cors.lua:131: set_cors_headers(): GET,POST,OPTIONSguess while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"
2021/01/26 10:30:43 [error] 3816275#3816275: *1805 [lua] cors.lua:137: set_cors_headers(): http://m-local.guess.com while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /products/recommend HTTP/1.0", upstream: "http://127.0.0.1:9505/products/recommend", host: "api-local.guess.com", referrer: "http://m-local.guess.com/detail/"

###Seems no log when situation occurred

**Comment by spacewander** [comment]
> Seems no log when situation occurred

So you mean when error occurs, the `header_filter` in cors plugin is not run?
Interesting, I have not seen this before. Maybe you can add more logs to find its execution path (or decrease the log level to info if permitted).

**Comment by jinyuxiaoqiang** [comment]
Have you solved this problem? I meet the same problem

**Comment by jinyuxiaoqiang** [comment]
> > Seems no log when situation occurred
> 
> So you mean when error occurs, the `header_filter` in cors plugin is not run? Interesting, I have not seen this before. Maybe you can add more logs to find its execution path (or decrease the log level to info if permitted).

I add log to the cors plugin, when the error occurred  _M.rewrite will run.  _M.header_filter and set headers not run @spacewander

**Comment by spacewander** [comment]
@jinyuxiaoqiang 
What's your APISIX version?
Is there a way to 100% reproduce it?

**Comment by jinyuxiaoqiang** [comment]
apisix version: 2.2
It reproduced rapidly yesterday,even I restart apisix service. At last I restart dashboard-2.3.0 and apisix service,it returns to normal. I will keep looking on it. Still there isn’t a way to 100% reproduce it.

**Comment by jinyuxiaoqiang** [comment]
I have reproduced this problem.After create global_plugin through dashboard, I delete this global_plugin.It remains something in etcd,then the problem will sometime occurred.

/global_rules/1
{"id":"1","plugins":{}}

**Comment by spacewander** [comment]
@bzp2010 
Has this issue been reported to dashboard before?
Maybe it is relative to https://github.com/apache/apisix/pull/4867

**Comment by jinyuxiaoqiang** [comment]
I can’t figure out how it leads to the problem. Can you give me some instructions?

**Comment by spacewander** [comment]
Can this be reproduced with APISIX 2.9 or higher?
