### ISSUE TITLE
bug: kubernetes/deployment.yaml not work on kind

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#3412]
### Issue description

When deploy apisix on k8s in minikube, it works fine. But on kind, when apply apisix deployment, error would come as:
```
Events:
  Type     Reason       Age                   From                         Message
  ----     ------       ----                  ----                         -------
  Warning  FailedMount  59m                   kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[localtime], unattached volumes=[localtime default-token-k4dr7 apisix-config-yaml-configmap]: timed out waiting for the condition
  Warning  FailedMount  47m (x2 over 50m)     kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[localtime], unattached volumes=[apisix-config-yaml-configmap localtime default-token-k4dr7]: timed out waiting for the condition
  Warning  FailedMount  4m43s (x19 over 63m)  kubelet, kind-control-plane  Unable to attach or mount volumes: unmounted volumes=[localtime], unattached volumes=[default-token-k4dr7 apisix-config-yaml-configmap localtime]: timed out waiting for the condition
  Warning  FailedMount  24s (x40 over 65m)    kubelet, kind-control-plane  MountVolume.SetUp failed for volume "localtime" : hostPath type check failed: /etc/localtime is not a file
```
So the error comes from the file existence check, which is
https://github.com/apache/apisix/blob/6331e5d05734f19f398b8dbae7f0470ce6069c98/kubernetes/deployment.yaml#L104-L111
although the file does exist. Try to replace the symbolic link with the actual file, but it still not work. If removed the file check, the error would be like: 
```
Error: failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/etc/localtime\\\" to rootfs \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/apisix-gw-deployment/rootfs\\\" at \\\"/run/containerd/io.containerd.runtime.v2.task/k8s.io/apisix-gw-deployment/rootfs/usr/share/zoneinfo/UTC\\\" caused \\\"not a directory\\\"\"": unknown
```

### Environment

* apisix version : master
* OS: WSL2, Ubuntu 18.04
* kind version: v0.8.1
* k8s version: v1.18.2

### Minimal test code / Steps to reproduce the issue

Following https://github.com/apache/apisix/blob/master/kubernetes/README.md

**Comment by Yiyiyimu** [comment]
Hi @spacewander! Do you know the reason for this?

**Comment by spacewander** [comment]
It seems there are some words after `caused \\\"not a directory\\\"\"": unknown`?
BTW, is `/etc/localtime` in the host readable?

**Comment by tokers** [comment]
@Yiyiyimu Kind is special, may be you should check wether the `/etc/localtime` exists in the container of kubelet.

**Comment by Yiyiyimu** [comment]
@spacewander Thanks for the reply! Yes it's weird it seems the error log got cut off but that's all that I could get from events.. And you are right, container kind does not have the file `/etc/localtime`...

**Comment by Yiyiyimu** [comment]
@tokers Thanks for the reply! You're right container `kind` in docker does not have the file `/etc/localtime`, and when I enter k8s node of kind, `/etc/localtime` is an empty directory but not a file (while in minikube it is).

**Comment by spacewander** [comment]
Consider solved

**Comment by Yiyiyimu** [comment]
@spacewander I wondered if it could be reproduced. If yes, maybe we need to add other setup steps for kind users, or recommend not to use it

**Comment by spacewander** [comment]
Is there someone uses kind in the prod?

**Comment by tokers** [comment]
> Is there someone uses kind in the prod?

I think most people use it in their development environment.

**Comment by spacewander** [comment]
So we don't need to support it.
