### ISSUE TITLE
bug: access阶段访问返回code,body，还会继续执行body_fileter

### ISSUE THREAD

**Issue by zhangpeix** [apache/apisix#3421]
### Environment

* apisix version :2.2
* OS: centos7
* OpenResty / Nginx version: 

我修改了echo插件,在调用access阶段，返回code和body,还会继续执行body_fileter

**Comment by spacewander** [comment]
Similar to https://github.com/apache/apisix/issues/2703.
Recommend to read through that issue and read the https://github.com/moonbingbing/openresty-best-practices/blob/master/ngx_lua/phase.md
