### ISSUE TITLE
bug: 插件的body_filter执行了两次

### ISSUE THREAD

**Issue by zhangpeix** [apache/apisix#3431]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`)  centeros7
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
* etcd version, if have: (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API)
* apisix-dashboard version, if have:

1.我修改了插件echo，在body_filter的入口打印了日志，在error.logs里面发现重复打印了两次，应该是重复调用了把
2.在access访问返回code 200但是还是没有终止整个请求

**Comment by spacewander** [comment]
> Nginx output filters may be called multiple times for a single request because response body may be delivered in chunks. Thus, the Lua code specified by in this directive may also run multiple times in the lifetime of a single HTTP request.

See the doc: https://github.com/openresty/lua-nginx-module#body_filter_by_lua

**Comment by tzssangglass** [comment]
You can refer to the code of the [grpc-transcode](https://github.com/apache/apisix/blob/master/apisix/plugins/grpc-transcode/response.lua) plugin for more information on how to get the full content of the response body.
