### ISSUE TITLE
docs: Some images are half-width and half-height,

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix#3435]
# Improve Docs
https://github.com/apache/apisix/blob/master/doc/zh-cn/architecture-design.md#plugin 

## Please describe which part of docs should be improved or typo fixed
Some images are half-width and half-height, Make the pictures uniform style, it will look better～

**Comment by Firstsawyou** [comment]
I think the current format is quite good. Because we need to set the size of the image according to different titles and scenes, if you use a unified style, it may not have the current effect.
Of course, if there is a way to make this image format look better. Welcome to "PR".
