### ISSUE TITLE
curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by ShaoZeMing** [apache/apisix#3437]
### Issue description
目前执行: 
curl http://127.0.0.1:80/apisix/plugin/jwt/sign?key=user-key -i  
或者 curl http://127.0.0.1:80

报错误  curl: (52) Empty reply from server

添加了全局cors 插件+zipkin 差距

没有添加任何本机/* 域名代理

     

### Environment

* apisix version 2.2 (docker-centos):
* OS: Linux xxxx-o1 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version: (nginx version: openresty/1.19.3.1)
* etcd version, if have:  3.4
* apisix-dashboard 2.3

**Comment by Firstsawyou** [comment]
Please provide your configuration information. This will help troubleshoot the problem.

**Comment by ShaoZeMing** [comment]
configuration：

docker pull apache/apisix:2.2-centos
mkdir -p  /data/apisix/
#配置文件：


docker run --restart=always -d --name apisix-server \
    --network apisix \
    -p 80:9080 \
    -p 443:9443 \
    -v /data/apisix/conf/config.yaml:/usr/local/apisix/conf/config.yaml  \
    -v /data/apisix/logs:/usr/local/apisix/logs  \
    apache/apisix:2.2-centos



etcd:
  host:
   - "http://etcd-server:2379"
#
# To configure via environment variables, you can use `${{VAR}}` syntax. For instance:
#
# etcd:
#     host:
#       - "http://${{ETCD_HOST}}:2379"
#
# And then run `export ETCD_HOST=$your_host` before `make init`.
#
# If the configured environment variable can't be found, an error will be thrown.
apisix:
  admin_key:
    -
      name: "admin"
      # yamllint disable rule:comments-indentation
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please
      # update it when you deploy to production environment
      # yamllint enable rule:comments-indentation
      role: admin


![image](https://blog.4d4k.com/wp-content/uploads/2021/01/Snipaste_2021-01-27_22-00-31.png)

![image](https://blog.4d4k.com/wp-content/uploads/2021/01/Snipaste_2021-01-27_22-03-41.png)

**Comment by Firstsawyou** [comment]
This is not caused by apisix, you should check the `curl` command for errors.

**Comment by ShaoZeMing** [comment]
> This is not caused by apisix, you should check the `curl` command for errors.

But the same happens when I use http request.

**Comment by ShaoZeMing** [comment]
apisix/logs/error.log

```

2021/01/28 05:52:18 [warn] 49#49: *1 [lua] plugin.lua:206: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/01/28 05:52:18 [warn] 50#50: *2 [lua] plugin.lua:206: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/01/28 05:52:18 [warn] 51#51: *3 [lua] plugin.lua:206: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/01/28 05:52:18 [warn] 52#52: *4 [lua] plugin.lua:206: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/01/28 05:52:18 [warn] 55#55: *5 [lua] plugin.lua:206: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/01/28 05:52:18 [warn] 49#49: *7 [lua] init.lua:288: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer
2021/01/28 05:52:50 [error] 51#51: *2271 failed to run header_filter_by_lua*: /usr/local/apisix/apisix/core/lrucache.lua:159: invalid value (nil) at index 1 in table for 'concat'
stack traceback:
        [C]: in function 'concat'
        /usr/local/apisix/apisix/core/lrucache.lua:159: in function 'plugin_ctx'
        /usr/local/apisix/apisix/plugins/cors.lua:168: in function 'phase_func'
        /usr/local/apisix/apisix/init.lua:164: in function 'run_plugin'
        /usr/local/apisix/apisix/init.lua:625: in function 'common_phase'
        /usr/local/apisix/apisix/init.lua:662: in function 'http_header_filter_phase'
        header_filter_by_lua:2: in main chunk, client: 192.168.0.139, server: , request: "GET / HTTP/1.1", host: "192.168.3.130"

```

**Comment by spacewander** [comment]
Fixed by https://github.com/apache/apisix/pull/3332?

**Comment by spacewander** [comment]
Consider solved
