### ISSUE TITLE
request help: confused about etcd compacted err in logs

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3438]
### Issue description
I checked the error.log and found logs like this:
`2021/01/27 21:29:03 [warn] 49#49: *859201 [lua] config_etcd.lua:311: sync_data(): waitdir [/apisix/proto] err: compacted, need to fully reload, context: ngx.timer`

It appears periodically. I don't know what the error is. Is it harmful? Do I need to do something to fix this?

### Environment

* apisix version (cmd: `apisix version`): 
2.1

* OS: (cmd: `uname -a`) 
Linux ti-gateway-workload-7d656465d4-2zdlk 3.10.107-1-tlinux2_kvm_guest-0052 #1 SMP Wed Jan 15 18:42:19 CST 2020 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
nginx version: openresty/1.19.3.1
built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

* etcd version, if have: (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API)

* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Don't be panic! It's a warning and just indicate APISIX will fully reload the configuration because current modification index is compacted and lost.
See https://github.com/apache/apisix/issues/2680

**Comment by Firstsawyou** [comment]
Try `apisix reload` ?

**Comment by spacewander** [comment]
There is nothing about `apisix reload`. I just submitted a PR to change this error message if this thing confuses you.
