### ISSUE TITLE
request help: stand-alone,config to use yaml file ,can't start up

### ISSUE THREAD

**Issue by ZanderMo** [apache/apisix#3441]
### Issue description
The config.yaml file codeing like this:
`
apisix:
  config_center: yaml
`
Than run to start  get info:
`
lua: /usr/apisix-2.2/deps/share/lua/5.1/tinyyaml.lua:624: found bad indenting in line:     -
stack traceback:
        [C]: in function 'error'
        /usr/apisix-2.2/deps/share/lua/5.1/tinyyaml.lua:624: in function 'parsemap'
        /usr/apisix-2.2/deps/share/lua/5.1/tinyyaml.lua:685: in function 'parsemap'
        /usr/apisix-2.2/deps/share/lua/5.1/tinyyaml.lua:735: in function 'parsedocuments'
        /usr/apisix-2.2/deps/share/lua/5.1/tinyyaml.lua:760: in function 'parse'
        ./apisix/cli/file.lua:196: in function 'read_yaml_conf'
        ./apisix/cli/ops.lua:133: in function 'init'
        ./apisix/cli/ops.lua:393: in function '?'
        ./apisix/cli/ops.lua:455: in function 'execute'
        ./bin/apisix:36: in main chunk
        [C]: ?
`
it not start up
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS: (cmd: `uname -a`) ubuntu 18
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
* etcd version, if have: (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API) none
* apisix-dashboard version, if have: none

**Comment by Firstsawyou** [comment]
From the error log, it may be that the `yaml` configuration file is indented incorrectly. You should check your `yaml` configuration file.

It is recommended to format the `config.yaml` configuration:
such as:
```
apisix:  
  config_center:yaml   
```

**Comment by ZanderMo** [comment]
THX，I try to fix this config.yaml,but it got another error log:  ERROR:  Admin API can only be used with etcd config_center.

**Comment by ZanderMo** [comment]
How do I turn off the Admin API option

**Comment by ZanderMo** [comment]
OK, resolved, to close the Admin API option:
  enable_admin: false

**Comment by Firstsawyou** [comment]
> THX，I try to fix this config.yaml,but it got another error log: ERROR: Admin API can only be used with etcd config_center.

After enabling the Stand-alone mode, the Admin API will no longer be allowed to use.
