### ISSUE TITLE
bug: when etcd down, apisix would keep printing error log

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#3444]
### Issue description
Currently when apisix is running, if etcd shuts down, apisix would keep print out `config_etcd.lua:530: failed to fetch data from etcd: connection refused`, and the speed is around 2 log per second per core. 

And it could be fixed after api7/lua-resty-etcd#111 (return error code when no healthy etcd available) got fixed.

Ref: #3404

**Comment by spacewander** [comment]
Consider solved
