### ISSUE TITLE
request help: How to limit the cost of apisix cluster environment

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#3445]
### Issue description
In the stand-alone mode, quota can be set by quota plug-in. However, in the cluster, how to ensure that the total amount of calls of each node is the total amount of quota. Although it can be processed by the redis cluster, the concurrency supported by the redis cluster is limited. If it is necessary to process a million level calls, how should it be set

**Comment by tokers** [comment]
@123libohan What's the quota you mentioned above? Is the limited QPS?

**Comment by 123libohan** [comment]
Yes, if it is in a cluster environment, it is impossible to guarantee the control of the total transfer amount

**Comment by 123libohan** [comment]
> @123libohan What's the quota you mentioned above? Is the limited QPS?

Yes, if it is in a cluster environment, it is impossible to guarantee the control of the total transfer amount

**Comment by membphis** [comment]
> Although it can be processed by the redis cluster, the concurrency supported by the redis cluster is limited. If it is necessary to process a million level calls, how should it be set

If you need a more powerful solution, please submit your requirements in detail.

**Comment by tokers** [comment]
@123libohan Does you cluster has a layer-4 LB in front of APISIX?

Since the rate limiting is in the single-instance scope, if the weight of each APISIX instance is same, you may configure the quota that divides the number of instances. But it's still hard for the scene that the weights are different.

**Comment by spacewander** [comment]
Consider solved
