### ISSUE TITLE
request help: I use plugin proxy-rewrite and serverless-pre-function,both of them cant rewrite x-forwarded-host,why?

### ISSUE THREAD

**Issue by ArminYang** [apache/apisix#3446]

**Comment by ArminYang** [comment]
can I write the apisix-conf to resolve it?

**Comment by ArminYang** [comment]
but they both can rewrite customized request header

**Comment by Firstsawyou** [comment]
This may be related to the proxy-rewrite plugin in the `rewrite` phase.

**Comment by Firstsawyou** [comment]
Try to use the `access` of `serverless-post-function`.

**Comment by ArminYang** [comment]
thank you,I find another way to solve it like rewrite the other header
