### ISSUE TITLE
why? I can only get the first query through the interface (/apimix/admin/routes or /apimix/admin/upstreams or /apimix/admin/services)

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#3452]
query through the interface (/apimix/admin/routes or /apimix/admin/upstreams or /apimix/admin/services)

e.g. :

# etcdctl get --prefix "/apisix/upstreams/"
/apisix/upstreams/100
{"desc":"test","create_time":1611827769,"retries":1,"pass_host":"pass","nodes":{"www.baidu.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611827980,"id":"100","type":"roundrobin"}
/apisix/upstreams/1611828392
{"desc":"test","create_time":1611828392,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828392,"id":"1611828392","type":"roundrobin"}
/apisix/upstreams/1611828444
{"desc":"test","create_time":1611828444,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828444,"id":"1611828444","type":"roundrobin"}
/apisix/upstreams/1611828871
{"desc":"test","create_time":1611828872,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828872,"id":"1611828871","type":"roundrobin"}
/apisix/upstreams/1611828873
{"desc":"test","create_time":1611828873,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828873,"id":"1611828873","type":"roundrobin"}
/apisix/upstreams/1611828875
{"desc":"test","create_time":1611828875,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828875,"id":"1611828875","type":"roundrobin"}
/apisix/upstreams/1611828878
{"desc":"test","create_time":1611828878,"retries":1,"pass_host":"pass","nodes":{"www.qq.com:80":1},"hash_on":"vars","name":"p-1","update_time":1611828878,"id":"1611828878","type":"roundrobin"}
/apisix/upstreams/1611829585
{"name":"p-1","id":"1611829585","create_time":1611829586,"retries":1,"pass_host":"pass","update_time":1611829586,"nodes":{"www.qq.com:80":1},"desc":"test","type":"roundrobin","hash_on":"vars"}
/apisix/upstreams/339352825173639868
{"id":"339352825173639868","create_time":1611799645,"update_time":1611799645,"nodes":[{"host":"10.6.1.124","port":80,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrob
in","pass_host":"pass","name":"test1"}
# etcdctl get --prefix "/apisix/routes/"
/apisix/routes/1
{"id":"1","create_time":1611571509,"priority":0,"uri":"\/*","name":"mb-t-1","status":1,"hosts":["a.test.com"],"update_time":1611717160,"upstream":{"pass_host":"pass","hash_on":"vars","type":"roundr
obin","nodes":{"10.6.1.128:8480":1}}}/apisix/routes/2
{"id":"2","create_time":1611571774,"priority":0,"uri":"\/t1\/","name":"mb-t-2","status":1,"hosts":["a.test.com"],"update_time":1611726484,"upstream":{"pass_host":"pass","hash_on":"vars","type":"rou
ndrobin","nodes":{"10.6.1.128:8480":1}}}/apisix/routes/3
{"id":"3","create_time":1611571790,"priority":0,"uri":"\/t2\/","name":"mb-t-3","status":1,"hosts":["a.test.com"],"update_time":1611726500,"upstream":{"pass_host":"pass","hash_on":"vars","type":"rou
ndrobin","nodes":{"10.6.1.128:8480":1}}}/apisix/routes/339352937312551612
{"id":"339352937312551612","create_time":1611799712,"update_time":1611799750,"uris":["/*"],"name":"test1","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"vars":[],"service_id":"33
9352970061677244","upstream_id":"339352825173639868","labels":{"test1":"test1"},"status":1}
-------------------------------------------------------------------------------------------------------------
# curl http://127.0.0.1:9080/apisix/admin/upstreams -H 'X-API-KEY: test123'
{"count":"9","node":{"value":{"create_time":1611827769,"retries":1,"pass_host":"pass","hash_on":"vars","update_time":1611827980,"nodes":{"www.baidu.com:80":1},"id":"100","type":"roundrobin","name":
"p-1","desc":"test"},"key":"\/apisix\/upstreams\/100"},"action":"get"}

# curl http://127.0.0.1:9080/apisix/admin/routes -H 'X-API-KEY: test123'
{"count":"4","node":{"value":{"create_time":1611571509,"status":1,"uri":"\/*","update_time":1611717160,"id":"1","priority":0,"upstream":{"nodes":{"10.6.1.128:8480":1},"pass_host":"pass","hash_on":"
vars","type":"roundrobin"},"hosts":["a.test.com"],"name":"mb-t-1"},"key":"\/apisix\/routes\/1"},"action":"get"}

How to solve this problem? Thks , everybody!

**Comment by Firstsawyou** [comment]
Have you changed the code of Apisix?

**Comment by Firstsawyou** [comment]
Based on the information provided, your problem cannot be determined. You should provide a complete usage example.

**Comment by idbeta** [comment]
this issue is too strange, you should provide your environment and steps,
```
* apisix version (cmd: `apisix version`):
* OS: (cmd: `uname -a`)
* OpenResty / Nginx version: (cmd: `nginx -V` or `openresty -V`)
* etcd version, if have: (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API)
* apisix-dashboard version, if have:
```

**Comment by moonming** [comment]
ping @Firstsawyou

**Comment by sandy420** [comment]
> 
> 
> Based on the information provided, your problem cannot be determined. You should provide a complete usage example.
e.g.:
curl http://127.0.0.1:9080/apisix/admin/upstreams -H 'X-API-KEY: test123'

{"count":"4","node":{"value":{"create_time":1611571509,"status":1,"uri":"/*","update_time":1611717160,"id":"1","priority":0,"upstream":{"nodes":{"10.6.1.128:8480":1},"pass_host":"pass","hash_on":"
vars","type":"roundrobin"},"hosts":["a.test.com"],"name":"mb-t-1"},"key":"/apisix/routes/1"},"action":"get"}

**Comment by Firstsawyou** [comment]
> > Based on the information provided, your problem cannot be determined. You should provide a complete usage example.
> > e.g.:
> > curl http://127.0.0.1:9080/apisix/admin/upstreams -H 'X-API-KEY: test123'
> 
> {"count":"4","node":{"value":{"create_time":1611571509,"status":1,"uri":"/*","update_time":1611717160,"id":"1","priority":0,"upstream":{"nodes":{"10.6.1.128:8480":1},"pass_host":"pass","hash_on":"
> vars","type":"roundrobin"},"hosts":["a.test.com"],"name":"mb-t-1"},"key":"/apisix/routes/1"},"action":"get"}

Hi, @sandy420   You need to provide the installation method, version information, and what modifications have been made. Because I have not reproduced it in the last few versions.
