### ISSUE TITLE
feat: precompile openresty binary to speed up CI progress

### ISSUE THREAD

**Issue by hnlq715** [apache/apisix#3458]
As title.

**Comment by hnlq715** [comment]
Before:
![image](https://user-images.githubusercontent.com/1734615/106268179-aedefb80-6265-11eb-9c72-084cca8fef46.png)

Now:
![image](https://user-images.githubusercontent.com/1734615/106268199-b900fa00-6265-11eb-952b-08f5bf50b49b.png)

**Comment by Firstsawyou** [comment]
pr is welcome.

**Comment by tokers** [comment]
@hnlq715 Is there anything i misunderstood?

Seems like the speed is slow now.

**Comment by hnlq715** [comment]
Yep, so we need to speed up CI progress. Now means the latest version in master branch.
I checked the history, and this change comes from the support for dubbo, which needs dubbo module.

So, maybe we could precompile binary with dubbo module to improve this.

**Comment by tokers** [comment]
> Yep, so we need to speed up CI progress. Now means the latest version in master branch.
> I checked the history, and this change comes from the support for dubbo, which needs dubbo module.
> 
> So, maybe we could precompile binary with dubbo module to improve this, or try the dynamic module way?

Have you get insight of where the extra time is costing on? Is the compilation step?

**Comment by hnlq715** [comment]
Yep, the compile step was added for dubbo module, which is not existed before.

**Comment by tokers** [comment]
@hnlq715 It takes one more minute to complete dubbo module compilation?

**Comment by hnlq715** [comment]
> @hnlq715 It takes one more minute to complete dubbo module compilation?

All nginx compile progress, which is added to support dubbo module.

**Comment by tokers** [comment]
Not sure whether this is worth, the test cases dominate most the time, maybe optimizing the test cases is better.
