### ISSUE TITLE
[DISCUSS] Should have a unified installation path

### ISSUE THREAD

**Issue by Fuchange** [apache/apisix#3463]
We have too many installation paths now.

Like the line 20 to 32 of /bin/apisix :

``` shell script
if [ -s './apisix/cli/apisix.lua' ]; then
    # install via source
    APISIX_LUA=./apisix/cli/apisix.lua
elif [ -s '/usr/share/lua/5.1/apisix/cli/apisix.lua' ]; then
    # install via luarock
    APISIX_LUA=/usr/share/lua/5.1/apisix/cli/apisix.lua
elif [ -s '/usr/local/apisix/deps/share/lua/5.1/apisix/cli/apisix.lua' ]; then
    # install via shell
    APISIX_LUA=/usr/local/apisix/deps/share/lua/5.1/apisix/cli/apisix.lua
else
    # install via official rpm or docker
    APISIX_LUA=/usr/local/apisix/apisix/cli/apisix.lua
fi
```
Skip of the first one, we have : 

-  `/usr/share/lua/5.1` : by `luarocks make` or `make install` (at CI)
-  `/usr/local/apisix/` : by rpm or docker
-  `/usr/local/apisix/deps/share/lua/5.1/` : by `./utils/install-apisix.sh install`

Same problem with the deps : 

- `/usr/share/lua/5.1` : by `luarocks install ` (at CI)
- `/usr/local/apisix/deps/share/lua/5.1/` : by rpm or docker
- `./` : by `make deps` (I cant even install deps to my system by `make`)

Should we integrate into `/usr/local/apisix/` or another path ?

**Comment by spacewander** [comment]
Better also start this discussion on the mail list.

**Comment by Fuchange** [comment]
> Better also start this discussion on the mail list.

:ok_hand:
