### ISSUE TITLE
bug: luasec 0.9-1 may  have caused the compilation to fail

### ISSUE THREAD

**Issue by Fuchange** [apache/apisix#3469]
### Issue description

On apisix-dashboard's [ci](https://github.com/apache/apisix-dashboard/runs/1804800876), 

```
apisix master-0 depends on luasec 0.9-1 (not installed)
Installing https://luarocks.org/luasec-0.9-1.src.rock

Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
  No file openssl/ssl.h in /include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
```
same as apisix [commit:5399a31b24](https://github.com/apache/apisix/runs/1803615860)

```
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
```

### Environment

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): push ci
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)

cant run `luarocks install `

### What's the expected result?

The confirmation can be passed

**Comment by spacewander** [comment]
Have you installed openresty-openssl-devel or openresty-openssl-dev? See https://github.com/apache/apisix/blob/master/doc/install-dependencies.md

**Comment by gxthrj** [comment]
Well, the dockerfile in [APISIX docker](https://github.com/apache/apisix-docker) need to be updated , too .
