### ISSUE TITLE
docs: update the error-log-logger plugin docs

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3473]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

1、In the `How to set the TCP server address` example, `curl http://127.0.0.1:9080//apisix/admin/plugin_metadata/error-log-logger` After the port number is `//`, we should change It is modified to `/`.

[https://github.com/apache/apisix/blob/master/doc/plugins/error-log-logger.md#how-to-set-the-tcp-server-address ](https://github.com/apache/apisix/blob/master/doc/plugins/error-log-logger.md#how-to-set-the-tcp-server-address)

[https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E6%8E%A5%E6%94%B6%E6%97%A5%E5%BF%97%E7%9A%84-tcp-%E6%9C%8D%E5%8A%A1%E5%99%A8 ](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E6%8E%A5%E6%94%B6%E6%97%A5%E5%BF%97%E7%9A%84-tcp-%E6%9C%8D%E5%8A%A1%E5%99%A8)

2、In Chinese documents, this link is invalid, and it needs to be linked to the correct location. 
[https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0 ](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0)

## Describe the solution you'd like

1、In the `How to set the TCP server address` example, `curl http://127.0.0.1:9080//apisix/admin/plugin_metadata/error-log-logger` After the port number is `//`, we should change It is modified to `/`.

2、The correct link should be:
[https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E6%8E%A5%E6%94%B6%E6%97%A5%E5%BF%97%E7%9A%84-tcp-%E6%9C%8D%E5%8A%A1%E5%99%A8 ](https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/error-log-logger.md#%E5%A6%82%E4%BD%95%E8%AE%BE%E7%BD%AE%E6%8E%A5%E6%94%B6%E6%97%A5%E5%BF%97%E7%9A%84-tcp-%E6%9C%8D%E5%8A%A1%E5%99%A8)

**Comment by jpcarroll** [comment]
Hi I would like to work on this issue!

**Comment by Firstsawyou** [comment]
> Hi I would like to work on this issue!

Hi, @jpcarroll  Very well, pr is welcome.
