### ISSUE TITLE
apisix variable assignment

### ISSUE THREAD

**Issue by mdh67899** [apache/apisix#3474]
### Issue description

    location = /info {
        proxy_pass http://192.168.1.10/index.html;
        set $appname "app1";
    }

我这边有个需求，nginx的location样例是这样写的，转发的时候会在location里设置一个appname变量，用来标记是转发给哪个后台应用的，log_format会将appname打印到日志里，请问在apisix里该怎么实现变量赋值的功能呢？谢谢

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by tokers** [comment]
@mdh67899 You can take a look at https://github.com/apache/apisix/blob/master/doc/plugins/http-logger.md.

Also, please use English in the public channel :)

**Comment by mdh67899** [comment]
https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/kafka-logger.md

**Comment by mdh67899** [comment]
Did kafka-logger support log_format  Metadata?

https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/kafka-logger.md

**Comment by Firstsawyou** [comment]
> Did kafka-logger support log_format Metadata?
> 
> https://github.com/apache/apisix/blob/master/doc/zh-cn/plugins/kafka-logger.md

The kafka-logger plugin does not support it, but the http-logger plugin can support it.
