### ISSUE TITLE
[Disscuss]: the prometheus plugin supports the host metric

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3475]
### Issue description

Currently, the Prometheus plugin does not support the host metric and cannot count visits based on the requested host.Therefore, I think the host metric can be added to support it.

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by tokers** [comment]
Why not use the `http_status` metric? it has the matched_host label and i think we can aggregate by this label.

**Comment by Firstsawyou** [comment]
> Why not use the `http_status` metric? it has the matched_host label and i think we can aggregate by this label.

I'm very sorry, I only read the documentation, not the code. Currently there is already matched_host, which can be achieved.

**Comment by Firstsawyou** [comment]
There is already a `matched_host` metric.

**Comment by moonming** [comment]
> > Why not use the `http_status` metric? it has the matched_host label and i think we can aggregate by this label.
> 
> 
> 
> I'm very sorry, I only read the documentation, not the code. Currently there is already matched_host, which can be achieved.

please update doc
