### ISSUE TITLE
authz-keycloak: support configurating token refresh/expire time

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#3479]
See https://github.com/apache/apisix/pull/3308#discussion_r563283583
@jenskeiner

**Comment by Belyenochi** [comment]
I want to fix this if no one else claims it.

**Comment by jenskeiner** [comment]
@Belyenochi I'd say go for it. I actually have a modified and improved version of this plugin that I have tested in a prod-like environment, but haven't gotten around to add these changes here so far. But will do my best to get that done as well soon. In the meantime, don't hesitate to fix/improve.
