### ISSUE TITLE
How to implement the header set in nginx in Apisix

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#3480]
e.g.:
This is my configuration in nginx,and How to implement the header set in nginx in Apisix:

location = / {
    more_set_input_headers "Host:qastatic.56qq.com";
	proxy_pass http://qastatic-56qq-com-lan/firestar/;
}

-------------------------------------------
The routing configuration information I queried in etcd:

#etcdctl get --prefix '/apisix/routes/1612229377'
/apisix/routes/1612229377
{"update_time":1612229377,"methods":["PUT","GET","POST"],"id":"1612229377","hosts":["qa-sh-hubble.ymm-inc.com","eadmin.qa-sh.56qq.com"],"remote_addrs":["10.0.0.0\/8","0.0.0.0\/0"],"priority":0,"sta
tus":1,"desc":"static路由测试svc1","create_time":1612229377,"uri":"\/*","name":"static路由测试svc1","enable_websocket":false,"service_id":"1612180320","**plugins":{"proxy-rewrite":{"uri":"\/firestar\/","headers":{"more_set_input_headers":"Host:qastatic.56qq.com"}}},**"upstream_id":"1612180237","vars":{}}
---------------------
Excuse me, what's  wrong with my routing configuration?

**Comment by spacewander** [comment]
Please read the doc: https://github.com/apache/apisix/blob/master/doc/plugins/proxy-rewrite.md, and its example of `headers`.

And you also need to read the doc of `more_set_input_headers` and `proxy_pass`. Before migrating Nginx configuration to APISIX, you should know how they work first.
