### ISSUE TITLE
support to use http/2 in non TLS scnario

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3485]
Currently APISIX only supports to use HTTP/2 protocol in TLS port. It could be better to support it also in non-TLS scnario.

**Comment by membphis** [comment]
Does anyone use HTTP2 in this way?

**Comment by tokers** [comment]
@membphis Not sure, but we may need to support plain gRPC proxy, and it's required to enable HTTP/2.

**Comment by membphis** [comment]
I I saw people discussing this need on the mailing list, and it seems that someone is really interested in this issue.

**Comment by spacewander** [comment]
Move to #3496
