### ISSUE TITLE
APISIX found that upstream reported 500 error through consul service

### ISSUE THREAD

**Issue by xyz101121** [apache/apisix#3486]
1.  apisix中的config.yaml已经配置dns_resolver
![image](https://user-images.githubusercontent.com/16227137/106560879-b868ac00-6562-11eb-8b7c-9d3371784d44.png)

2.route配置的upstream
![image](https://user-images.githubusercontent.com/16227137/106560982-e1893c80-6562-11eb-85ce-1c25e40eb15b.png)

3. consul解析没有问题
![image](https://user-images.githubusercontent.com/16227137/106561064-0087ce80-6563-11eb-8129-b0d4c6a5835c.png)

可是我访问的时候报500错误，当我把upstream直接替换成后端的ip地址，是没有问题的，-XPATCH -d '{"upstream":{"nodes":{"172.16.0.237":1}}}

**Comment by Firstsawyou** [comment]
It would be better to provide relevant error log information.

**Comment by xyz101121** [comment]
access.log没有500的请求，error.log在请求失败的时候没有错误，配置文件如下：

![image](https://user-images.githubusercontent.com/16227137/106572661-acd1b100-6573-11eb-9bda-41994dc93ee4.png)

**Comment by tokers** [comment]
It's weird, could you paste the generated nginx.conf? We need the `init_by_lua_block` section where the dns resolvers are passed in.

**Comment by xyz101121** [comment]
![image](https://user-images.githubusercontent.com/16227137/106607240-0bac2000-659e-11eb-8592-83b4871330f4.png)

**Comment by tokers** [comment]
@Firstsawyou We have X-Upstream series headers, could you also provide a request/response sample by the curl? We want to see the response headers.

**Comment by Firstsawyou** [comment]
@xyz101121   We have `X-APISIX-Upstream-Status` response header information, you should provide this information.
Similar to this:

```
curl http://127.0.0.1:9080/hello -i
HTTP/1.1 502 Bad Gateway
Date: Wed, 03 Feb 2021 01:35:00 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 154
Connection: keep-alive
Server: APISIX/2.2
X-APISIX-Upstream-Status: 502, 502, 502
......
```

**Comment by xyz101121** [comment]
Now，suddenly it is ok, I don't know why !

**Comment by xyz101121** [comment]
and now i find other question, Sometimes customize head for "env" is  ok, sometimes not，But this routing level is the highest
![image](https://user-images.githubusercontent.com/16227137/106722997-9abe4400-6641-11eb-80e2-5f38a0ea59f1.png)

![image](https://user-images.githubusercontent.com/16227137/106723240-dc4eef00-6641-11eb-9cb1-be688b4ac941.png)

**Comment by tokers** [comment]
> and now i find other question, Sometimes customize head for "env" is ok, sometimes not，But this routing level is the highest
> ![image](https://user-images.githubusercontent.com/16227137/106722997-9abe4400-6641-11eb-80e2-5f38a0ea59f1.png)
> 
> ![image](https://user-images.githubusercontent.com/16227137/106723240-dc4eef00-6641-11eb-9cb1-be688b4ac941.png)

Are you sure these requests were processed by APISIX? If so, the Server header should be `APISIX`.

**Comment by xyz101121** [comment]
Sure ,I customized the header server

**Comment by xyz101121** [comment]
![image](https://user-images.githubusercontent.com/16227137/106836605-72335a00-66d4-11eb-99bf-11fad628bec5.png)

**Comment by tokers** [comment]
> and now i find other question, Sometimes customize head for "env" is ok, sometimes not，But this routing level is the highest
> ![image](https://user-images.githubusercontent.com/16227137/106722997-9abe4400-6641-11eb-80e2-5f38a0ea59f1.png)
> 
> ![image](https://user-images.githubusercontent.com/16227137/106723240-dc4eef00-6641-11eb-9cb1-be688b4ac941.png)

Would you like to close this issue and open another one to describe the problem (provide your configuration, error logs), one thread for one issue, or others will be confused when they check this thread.

**Comment by membphis** [comment]
close this issue first.

@xyz101121 you can create a new issue with your question. feel free to reopen it if you think they are one bug.
