### ISSUE TITLE
request help:  run "sh run.sh 4" ,inform"nginx: [emerg] open() "/root/apisix/apisix-docker/benchmark/server/conf/nginx.conf" failed (2: No such file or directory)"

### ISSUE THREAD

**Issue by No-sleeping** [apache/apisix#3490]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by No-sleeping** [comment]
跑run.sh的时候时候，提示“找不到这个文件”，可是我看脚本里根本就没有用到这个文件啊

**Comment by Firstsawyou** [comment]
You can look at the test method here: [https://gist.github.com/membphis/137db97a4bf64d3653aa42f3e016bd01 ](https://gist.github.com/membphis/137db97a4bf64d3653aa42f3e016bd01)

**Comment by spacewander** [comment]
Closed as lack of response.
