### ISSUE TITLE
Prometheus collection and official collection document index data are missing

### ISSUE THREAD

**Issue by xyz101121** [apache/apisix#3492]
我根据文档进行信息采集，
https://github.com/apache/apisix/blob/master/doc/plugins/prometheus.md#available-metrics
可是实际采集指标对不上，缺少很多，实际采集如下:
![image](https://user-images.githubusercontent.com/16227137/106573312-6c266780-6574-11eb-9955-463b916441ee.png)

**Comment by Firstsawyou** [comment]
Have you ever initiated a request to upstream. If not, you need to have a request to upstream to trigger other metrics.

**Comment by Firstsawyou** [comment]
By the way, you can use a translation tool to translate Chinese into English.

**Comment by xyz101121** [comment]
I have many requests from prod env ,But other metrics are not finded

**Comment by Firstsawyou** [comment]
Please provide a minimum reproduction step for the problem. Mainly how your prometheus plugin is configured.

**Comment by Firstsawyou** [comment]
> I have many requests from prod env ,But other metrics are not finded

By the way, provide the version information of your apisix.

**Comment by xyz101121** [comment]
I configure info from link (https://github.com/apache/apisix/blob/master/doc/plugins/prometheus.md)
apisix is docker , image is apache/apisix:2.2-alpine

**Comment by tokers** [comment]
@xyz101121 Could you please provide the config.yaml of your APISIX?

**Comment by xyz101121** [comment]
this is my apisix config
![image](https://user-images.githubusercontent.com/16227137/106606881-9a6c6d00-659d-11eb-9ff4-a5e98384d924.png)

**Comment by spacewander** [comment]
How you configure the route? Have you enabled the promethues plugin on the route?

**Comment by xyz101121** [comment]
I see , I try change route, Please wait

**Comment by xyz101121** [comment]
Now it is ok ,Because I did not configure the promethus plugin on other routes, I only configured it on /hello ， Thanks for your help!
