### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by cwy57885142** [apache/apisix#3495]
### Issue description
mqtt-proxy插件，在文档描述内容较少，remote_addr参数未知

curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "plugins": {
        "mqtt-proxy": {
            "protocol_name": "MQTT",
            "protocol_level": 4,
            "upstream": {
                "ip": "127.0.0.1",
                "port": 1980
            }
        }
    }
}'

1.curl命令行中的remote_addr指的是路由地址还是mqtt server地址；

**Comment by Firstsawyou** [comment]
I think it is the remote address, that is, the address of the client to which you sent the request.

**Comment by cwy57885142** [comment]
thanks

**Comment by tokers** [comment]
Consider as solved.
