### ISSUE TITLE
feat: support grpc proxy with insecure mode

### ISSUE THREAD

**Issue by hnlq715** [apache/apisix#3496]
I checked the current implementation, for now apisix seems only support grpc proxy with ssl.

In my case, we want to try apisix to balance grpc traffic with insecure mode in intranet environment.

Is there any reason not to support grpc without ssl enabled? Looking forward to your reply :-)
```
        {% for _, port in ipairs(node_listen) do %}
        listen {* port *} {% if enable_reuseport then %} reuseport {% end %};
        {% end %}
        {% if ssl.enable then %}
        {% for _, port in ipairs(ssl.listen_port) do %}
        listen {* port *} ssl {% if ssl.enable_http2 then %} http2 {% end %} {% if enable_reuseport then %} reuseport {% end %};
        {% end %}
        {% end %}
```

**Comment by spacewander** [comment]
Maybe we can allow plaintext HTTP2?

**Comment by hnlq715** [comment]
> Maybe we can allow plaintext HTTP2?

That's it.

**Comment by nic-chen** [comment]
@hnlq715  PR is welcome.

**Comment by hnlq715** [comment]
@spacewander @nic-chen 
Seems like nginx do not support h2c and http1 on the same port without ssl...
So, maybe we need to add a new port for this?

nginx issue:
https://trac.nginx.org/nginx/ticket/816

without ssl:
```
https://github.com/nginx/nginx/blob/9e07862d6e9d37041a42bbfa34dd1f56ed547505/src/http/ngx_http_request.c#L324-L331
```

with ssl:
```
https://github.com/nginx/nginx/blob/9e07862d6e9d37041a42bbfa34dd1f56ed547505/src/http/ngx_http_request.c#L812-L831
```

**Comment by membphis** [comment]
> Seems like nginx do not support h2c and http1 on the same port without ssl...

confirm this ^_^

**Comment by tokers** [comment]
> > Seems like nginx do not support h2c and http1 on the same port without ssl...
> 
> confirm this ^_^

That's true, we cannot use same port for both http/1.1 and http2 if we don't use TLS/SSL.

**Comment by spacewander** [comment]
Maybe we can extend the array format of `node_listen`, allow providing http2 flag?
https://github.com/apache/apisix/blob/1e35cc00eb1df21ee2e826f010c7e1ea35de8ef0/conf/config-default.yaml#L23

**Comment by tokers** [comment]
> Maybe we can extend the array format of `node_listen`, allow providing http2 flag?

That's good.

**Comment by hnlq715** [comment]
> Maybe we can extend the array format of `node_listen`, allow providing http2 flag?
> 
> https://github.com/apache/apisix/blob/1e35cc00eb1df21ee2e826f010c7e1ea35de8ef0/conf/config-default.yaml#L23

It’s good if we do not need to consider compatibility

**Comment by spacewander** [comment]
We should support current way too.

**Comment by spacewander** [comment]
Solved.
