### ISSUE TITLE
Question: How to select dynamic upstream by url path or url parameter ?

### ISSUE THREAD

**Issue by tongorz** [apache/apisix#3503]
### Issue description
I'm trying to use apisix as a proxy of thoudsands of server's IPMI(or BMC) WEB interface。

URL should be something like this:
https://ipmi.somedomain.com/{{Server_IPMI_IP}}  or 
https://ipmi.somedomain.com?ip={{Server_IPMI_IP}}

Upstream should be something like this:
https://{{Server_IPMI_IP}}

Can apisix help to support the case described above？

Thank you!

**Comment by Firstsawyou** [comment]
You can take a look at this plugin, it should help you: [https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md ](https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md)

**Comment by Firstsawyou** [comment]
> You can take a look at this plugin, it should help you: [https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md ](https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md)

The traffic-slipt plugin can select dynamic upstream for the url parameter, but does not support the rewriting of the url parameter.

**Comment by tongorz** [comment]
> > You can take a look at this plugin, it should help you: [https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md ](https://github.com/apache/apisix/blob/master/doc/plugins/traffic-split.md)
> 
> The traffic-slipt plugin can select dynamic upstream for the url parameter, but does not support the rewriting of the url.

Thank you. :)
It looks like that the traffic-slipt plugin won't work in my case...

**Comment by tokers** [comment]
@tongorz Have you tried the proxy-rewrite plugin?

**Comment by tokers** [comment]
@tongorz It looks like you wanna proxy to the IP which specified in the parameter?

**Comment by tongorz** [comment]
> @tongorz It looks like you wanna proxy to the IP which specified in the parameter?

Yes. I want all traffic to IPMI WEB of Servers go through proxy server first.

**Comment by tokers** [comment]
@spacewander 

Seems we don't have  a way to achieve this.

**Comment by membphis** [comment]
You can refer to the traffic-split plugin and extend a new custom plugin.

If you need more specific help, you can contact us.

**Comment by spacewander** [comment]
Consider solved

**Comment by xuzhijvn** [comment]
this question has been solved?
