### ISSUE TITLE
Grpc proxy to support proxy rewrite (and other possible plugins)

### ISSUE THREAD

**Issue by JanLi-air** [apache/apisix#3506]
# Improve Docs

Currently GRPC access phase doesn't run plugins, so grpc proxy is a pure proxy. 
Problems some plugins might be required for some scenarios.
For example,
When the upstream is an ingress controller, we need to use proxy-rewrite to rewrite the host for the ingress route mapping. But the current grpc solution doesn't support such a feature.

## Please describe which part of docs should be improved or typo fixed

grpc-proxy.md needs to be changed.

## Describe the solution you'd like

I think we can provide grpc plugins, which might be a different set from the http plugins.

**Comment by spacewander** [comment]
Have you tried the master branch?

**Comment by spacewander** [comment]
Should have been done.
