### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by cwy57885142** [apache/apisix#3516]
关于插件authz-keycloak中的Bearer {JWT Token}如何生成问题

Create a route and enable the authz-keycloak plugin on the route:

```
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/get",
    "plugins": {
        "authz-keycloak": {
            "token_endpoint": "http://127.0.0.1:8090/auth/realms/{client_id}/protocol/openid-connect/token",
            "permissions": ["resource name#scope name"],
            "audience": "Client ID"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:8080": 1
        }
    }
}'
```

Test Plugin：
curl http://127.0.0.1:9080/get -H 'Authorization: Bearer {JWT Token}'

JWT Token如何生成？

**Comment by Firstsawyou** [comment]
The `jwt-auth` plugin has an example of generating `jwt token`, you can refer to it .

**Comment by cwy57885142** [comment]
> 该`jwt-auth`插件有一个生成示例`jwt token`，您可以参考它。

authz-keycloak插件需要与jwt-auth插件结合使用？

**Comment by Firstsawyou** [comment]
> > 该`jwt-auth`插件有一个生成示例`jwt token`，您可以参考它。
> 
> authz-keycloak插件需要与jwt-auth插件结合使用？

No, that is just an example of generating `JWT Token`. For the detailed usage of the `authz-keycloak` plugin, you can refer to its test case. [https://github.com/apache/apisix/blob/master/t/plugin/authz-keycloak.t ](https://github.com/apache/apisix/blob/master/t/plugin/authz-keycloak.t)

**Comment by cwy57885142** [comment]
> > > 该`jwt-auth`插件有一个生成示例`jwt token`，您可以参考它。
> > 
> > 
> > authz-keycloak插件需要与jwt-auth插件结合使用？
> 
> 不，那只是generate的一个例子`JWT Token`。有关该`authz-keycloak`插件的详细用法，可以参考其测试用例。https://github.com/apache/apisix/blob/master/t/plugin/authz-keycloak.t

参考测试用例执行，缺少 issuedFor，该值指的是什么？
{"error":"invalid_request","error_description":"You must provide the issuedFor"}

**Comment by Firstsawyou** [comment]
> 参考测试用例执行，缺少 issuedFor，该值指的是什么？
> {"error":"invalid_request","error_description":"You must provide the issuedFor"}

It looks like your request is abnormal and you need to provide your configuration example.

**Comment by cwy57885142** [comment]
> > 参考测试用例执行，缺少 issuedFor，该值指的是什么？
> > {"error":"invalid_request","error_description":"You must provide the issuedFor"}
> 
> It looks like your request is abnormal and you need to provide your configuration example.

请求:
curl http://admin.test.com/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/echo",
    "plugins": {
        "authz-keycloak": {
            "token_endpoint": "http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token",
			"policy_enforcement_mode": "PERMISSIVE",
            "audience": "test_client"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "172.20.11.32:18080": 1
        }
    }
}'

获取access_token:
curl --location --request POST 'http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'username=test_user' --data-urlencode 'password=123456' --data-urlencode 'client_id=test_client' --data-urlencode 'grant_type=password'

验证: curl http://admin.tydic.com/echo -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6SUxOWUMzaFp0LTI5emc2VVY2RWV6WGMxZEZyamxSLVIxNHJ2cHdsUmhBIn0.eyJleHAiOjIwNDQ2NjYwMDMsImlhdCI6MTYxMjY2NjAwMywianRpIjoiN2MxZDBhOWUtMzIxZC00YTYyLTk2NWQtZTNiNjg3ZTYzYThlIiwiaXNzIjoiaHR0cDovLzE3Mi4yMC4xMS4xODE6ODA5MC9hdXRoL3JlYWxtcy9Vbml2ZXJzaXR5IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImM2NTcyMzZhLWMxZTctNDNhMS05MjJmLWI2NDViZjZiNzhmOSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3RfY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImUxMDI0NzY3LTE0NjUtNDNjYi1hMWZhLTZlNDAzMjU1NTAxNyIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ0ZXN0X3JvbGUiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdF91c2VyIn0.vNv-KEQttVqQxAdkGi2huITSHXkMIkXhbiCd_1XlGvDbPGL26K1hkefAExtlcrwoOnXIoW9KCySo8etTaTrZ9Mz3X5FiNX64bIrPAFy5CspWodgnWS-Ck2gkUhUbSi6xJ7sR6TaI815WNQVl-x_newP4l8rAWNT6sSwBMPVc0LtKEk7m5Zhkcdy-KBSr_S2HKqCwJgw4Ll-XKh53sjOVJ6vaC1B2oxZf9n-DddV05z2Cw1d_X_fKoCb7EY5hKboXIUSYlW_MPc5FL4bEW0u-KYPb87OzAgZaWknN9yAlZMLetdQw7rGZJA3R1XBWedoTH6B8gIYmmCcc0EKsf0S0eQ'

结果:
{"error":"invalid_request","error_description":"You must provide the issuedFor"}

**Comment by cwy57885142** [comment]
> > 参考测试用例执行，缺少 issuedFor，该值指的是什么？
> > {"error":"invalid_request","error_description":"You must provide the issuedFor"}
> 
> It looks like your request is abnormal and you need to provide your configuration example.

例1:请求:
curl http://admin.test.com/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "plugins": {
        "authz-keycloak": {
            "token_endpoint": "http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token",
			"policy_enforcement_mode": "PERMISSIVE",
            "audience": "test_client"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "172.20.11.32:18080": 1
        }
    }
}'

获取access_token:
curl --location --request POST 'http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'username=test_user' --data-urlencode 'password=123456' --data-urlencode 'client_id=test_client' --data-urlencode 'grant_type=password'

验证: curl http://admin.test.com/echo -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6SUxOWUMzaFp0LTI5emc2VVY2RWV6WGMxZEZyamxSLVIxNHJ2cHdsUmhBIn0.eyJleHAiOjIwNDQ2NjYwMDMsImlhdCI6MTYxMjY2NjAwMywianRpIjoiN2MxZDBhOWUtMzIxZC00YTYyLTk2NWQtZTNiNjg3ZTYzYThlIiwiaXNzIjoiaHR0cDovLzE3Mi4yMC4xMS4xODE6ODA5MC9hdXRoL3JlYWxtcy9Vbml2ZXJzaXR5IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImM2NTcyMzZhLWMxZTctNDNhMS05MjJmLWI2NDViZjZiNzhmOSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3RfY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImUxMDI0NzY3LTE0NjUtNDNjYi1hMWZhLTZlNDAzMjU1NTAxNyIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ0ZXN0X3JvbGUiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdF91c2VyIn0.vNv-KEQttVqQxAdkGi2huITSHXkMIkXhbiCd_1XlGvDbPGL26K1hkefAExtlcrwoOnXIoW9KCySo8etTaTrZ9Mz3X5FiNX64bIrPAFy5CspWodgnWS-Ck2gkUhUbSi6xJ7sR6TaI815WNQVl-x_newP4l8rAWNT6sSwBMPVc0LtKEk7m5Zhkcdy-KBSr_S2HKqCwJgw4Ll-XKh53sjOVJ6vaC1B2oxZf9n-DddV05z2Cw1d_X_fKoCb7EY5hKboXIUSYlW_MPc5FL4bEW0u-KYPb87OzAgZaWknN9yAlZMLetdQw7rGZJA3R1XBWedoTH6B8gIYmmCcc0EKsf0S0eQ'

结果:
{"error":"invalid_request","error_description":"You must provide the issuedFor"}


例2:
curl http://admin.test.com/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/echo",
    "plugins": {
        "authz-keycloak": {
            "token_endpoint": "http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token",
			"policy_enforcement_mode": "PERMISSIVE",
            "audience": "test_client"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "172.20.11.32:18080": 1
        }
    }
}'

获取access_token:
curl --location --request POST 'http://172.20.11.181:8090/auth/realms/University/protocol/openid-connect/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'username=test_user' --data-urlencode 'password=123456' --data-urlencode 'client_id=test_client' --data-urlencode 'grant_type=password'

验证: curl http://admin.test.com/echo -H 'Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ6SUxOWUMzaFp0LTI5emc2VVY2RWV6WGMxZEZyamxSLVIxNHJ2cHdsUmhBIn0.eyJleHAiOjIwNDQ2NjYwMDMsImlhdCI6MTYxMjY2NjAwMywianRpIjoiN2MxZDBhOWUtMzIxZC00YTYyLTk2NWQtZTNiNjg3ZTYzYThlIiwiaXNzIjoiaHR0cDovLzE3Mi4yMC4xMS4xODE6ODA5MC9hdXRoL3JlYWxtcy9Vbml2ZXJzaXR5IiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImM2NTcyMzZhLWMxZTctNDNhMS05MjJmLWI2NDViZjZiNzhmOSIsInR5cCI6IkJlYXJlciIsImF6cCI6InRlc3RfY2xpZW50Iiwic2Vzc2lvbl9zdGF0ZSI6ImUxMDI0NzY3LTE0NjUtNDNjYi1hMWZhLTZlNDAzMjU1NTAxNyIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ0ZXN0X3JvbGUiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoicHJvZmlsZSBlbWFpbCIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicHJlZmVycmVkX3VzZXJuYW1lIjoidGVzdF91c2VyIn0.vNv-KEQttVqQxAdkGi2huITSHXkMIkXhbiCd_1XlGvDbPGL26K1hkefAExtlcrwoOnXIoW9KCySo8etTaTrZ9Mz3X5FiNX64bIrPAFy5CspWodgnWS-Ck2gkUhUbSi6xJ7sR6TaI815WNQVl-x_newP4l8rAWNT6sSwBMPVc0LtKEk7m5Zhkcdy-KBSr_S2HKqCwJgw4Ll-XKh53sjOVJ6vaC1B2oxZf9n-DddV05z2Cw1d_X_fKoCb7EY5hKboXIUSYlW_MPc5FL4bEW0u-KYPb87OzAgZaWknN9yAlZMLetdQw7rGZJA3R1XBWedoTH6B8gIYmmCcc0EKsf0S0eQ'

结果:
{"error":"invalid_request","error_description":"You must provide the issuedFor"}

**Comment by cwy57885142** [comment]
同样请求情况下也遇到过如下报错:
{"error":"invalid_request","error_description":"Client does not support permissions"}[

**Comment by cwy57885142** [comment]
![Uploading 9[Q90}Z_H}SA4REW@9}TW23.png…]()

**Comment by membphis** [comment]
ping @Firstsawyou

**Comment by Firstsawyou** [comment]
> 参考测试用例执行，缺少 issuedFor，该值指的是什么？
> {"error":"invalid_request","error_description":"You must provide the issuedFor"}

I'm very sorry, I did not reply to your message in time.
This error message is returned by `keycloack`, you can refer to the solution here: https://stackoverflow.com/questions/63566261/postman-keycloack-issuedfor

**Comment by spacewander** [comment]
Closed as lack of response from the author.
