### ISSUE TITLE
request help: vars_combinations can not work

### ISSUE THREAD

**Issue by zhangxiaohui123456** [apache/apisix#3518]
### Issue description
Upstream combination vars_combinations are selected for the upstream configuration this is my configuration :
 {
    "id" : "161190602766647283",
    "desc" : "prod-tour",
    "nodes" : {
      "172.18.234.22:8888" : 1,
      "172.18.234.22:7777" : 1
    },
    "type" : "chash",
    "hash_on" : "vars_combinations",
    "key" : "request_uri",
    "checks" : {
      "active" : {
        "http_path" : "/",
        "healthy" : {
          "interval" : 10
        },
        "unhealthy" : {
          "interval" : 10
        }
      }
    }
 start is ok,but when I access route go wrong,this is error info 
 2021/02/04 15:28:30 [error] 8611#8611: *46068 lua entry thread aborted: runtime error: /mios/ispthird/openresty/anhui-master-3.1.0//lua/nginx.lua:333: attempt to index local 'upstream' (a nil value)
stack traceback:
coroutine 0:
        /mios/ispthird/openresty/anhui-master-3.1.0//lua/nginx.lua: in function 'fun_org'
        ...pthird/openresty/anhui-master-3.1.0//lua/nginx/debug.lua:127: in function 'http_access_phase'
        access_by_lua(nginx.conf:147):2: in main chunk, client: 172.20.80.39, server: nginx, request: "GET /tour/test.html HTTP/1.1", host: "172.18.234.22:23111"

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:

```
$ curl http://127.0.0.1:9080/hello -i
HTTP/1.1 500 Internal Server Error
Date: Wed, 03 Feb 2021 01:35:00 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 154
Connection: keep-alive
Server: APISIX/2.2
X-APISIX-Upstream-Status: 500, 500
......
```

This helps us troubleshoot the issue.

**Comment by zhangxiaohui123456** [comment]
> These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> 
> ```
> $ curl http://127.0.0.1:9080/hello -i
> HTTP/1.1 500 Internal Server Error
> Date: Wed, 03 Feb 2021 01:35:00 GMT
> Content-Type: text/html; charset=utf-8
> Content-Length: 154
> Connection: keep-alive
> Server: APISIX/2.2
> X-APISIX-Upstream-Status: 500, 500
> ......
> ```
> 
> This helps us troubleshoot the issue.



> These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> 
> ```
> $ curl http://127.0.0.1:9080/hello -i
> HTTP/1.1 500 Internal Server Error
> Date: Wed, 03 Feb 2021 01:35:00 GMT
> Content-Type: text/html; charset=utf-8
> Content-Length: 154
> Connection: keep-alive
> Server: APISIX/2.2
> X-APISIX-Upstream-Status: 500, 500
> ......
> ```
> 
> This helps us troubleshoot the issue.
curl http://172.18.234.22:23111/tour/test.html -i  
log is :
HTTP/1.1 500 Internal Server Error
Date: Thu, 04 Feb 2021 07:51:51 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 1502
Connection: close
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000; includeSubdomains
Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0

**Comment by Firstsawyou** [comment]
> > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > ```
> > $ curl http://127.0.0.1:9080/hello -i
> > HTTP/1.1 500 Internal Server Error
> > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > Content-Type: text/html; charset=utf-8
> > Content-Length: 154
> > Connection: keep-alive
> > Server: APISIX/2.2
> > X-APISIX-Upstream-Status: 500, 500
> > ......
> > ```
> > 
> > 
> > This helps us troubleshoot the issue.
> 
> > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > ```
> > $ curl http://127.0.0.1:9080/hello -i
> > HTTP/1.1 500 Internal Server Error
> > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > Content-Type: text/html; charset=utf-8
> > Content-Length: 154
> > Connection: keep-alive
> > Server: APISIX/2.2
> > X-APISIX-Upstream-Status: 500, 500
> > ......
> > ```
> > 
> > 
> > This helps us troubleshoot the issue.
> > curl http://172.18.234.22:23111/tour/test.html -i
> > log is :
> > HTTP/1.1 500 Internal Server Error
> > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > Content-Type: text/html; charset=utf-8
> > Content-Length: 1502
> > Connection: close
> > X-XSS-Protection: 1; mode=block
> > X-Content-Type-Options: nosniff
> > Referrer-Policy: no-referrer-when-downgrade
> > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > Pragma: no-cache
> > Expires: 0

Why is there no response header information for `Server: APISIX/2.2`  ?

**Comment by zhangxiaohui123456** [comment]
> > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > ```
> > > $ curl http://127.0.0.1:9080/hello -i
> > > HTTP/1.1 500 Internal Server Error
> > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > Content-Type: text/html; charset=utf-8
> > > Content-Length: 154
> > > Connection: keep-alive
> > > Server: APISIX/2.2
> > > X-APISIX-Upstream-Status: 500, 500
> > > ......
> > > ```
> > > 
> > > 
> > > This helps us troubleshoot the issue.
> > 
> > 
> > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > ```
> > > $ curl http://127.0.0.1:9080/hello -i
> > > HTTP/1.1 500 Internal Server Error
> > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > Content-Type: text/html; charset=utf-8
> > > Content-Length: 154
> > > Connection: keep-alive
> > > Server: APISIX/2.2
> > > X-APISIX-Upstream-Status: 500, 500
> > > ......
> > > ```
> > > 
> > > 
> > > This helps us troubleshoot the issue.
> > > curl http://172.18.234.22:23111/tour/test.html -i
> > > log is :
> > > HTTP/1.1 500 Internal Server Error
> > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > Content-Type: text/html; charset=utf-8
> > > Content-Length: 1502
> > > Connection: close
> > > X-XSS-Protection: 1; mode=block
> > > X-Content-Type-Options: nosniff
> > > Referrer-Policy: no-referrer-when-downgrade
> > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > Pragma: no-cache
> > > Expires: 0
> 
> Why is there no response header information for `Server: APISIX/2.2` ?

I delete that part ,this is a success response log info:
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 231
Connection: keep-alive
Date: Thu, 04 Feb 2021 08:25:22 GMT
X-Frame-Options: sameorigin
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: no-referrer-when-downgrade
Strict-Transport-Security: max-age=31536000; includeSubdomains
Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
I don't think that will matter

**Comment by zhangxiaohui123456** [comment]
> > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > ```
> > > > $ curl http://127.0.0.1:9080/hello -i
> > > > HTTP/1.1 500 Internal Server Error
> > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > Content-Type: text/html; charset=utf-8
> > > > Content-Length: 154
> > > > Connection: keep-alive
> > > > Server: APISIX/2.2
> > > > X-APISIX-Upstream-Status: 500, 500
> > > > ......
> > > > ```
> > > > 
> > > > 
> > > > This helps us troubleshoot the issue.
> > > 
> > > 
> > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > ```
> > > > $ curl http://127.0.0.1:9080/hello -i
> > > > HTTP/1.1 500 Internal Server Error
> > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > Content-Type: text/html; charset=utf-8
> > > > Content-Length: 154
> > > > Connection: keep-alive
> > > > Server: APISIX/2.2
> > > > X-APISIX-Upstream-Status: 500, 500
> > > > ......
> > > > ```
> > > > 
> > > > 
> > > > This helps us troubleshoot the issue.
> > > > curl http://172.18.234.22:23111/tour/test.html -i
> > > > log is :
> > > > HTTP/1.1 500 Internal Server Error
> > > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > > Content-Type: text/html; charset=utf-8
> > > > Content-Length: 1502
> > > > Connection: close
> > > > X-XSS-Protection: 1; mode=block
> > > > X-Content-Type-Options: nosniff
> > > > Referrer-Policy: no-referrer-when-downgrade
> > > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > > Pragma: no-cache
> > > > Expires: 0
> > 
> > 
> > Why is there no response header information for `Server: APISIX/2.2` ?
> 
I set up  apisix-2.1  In my machine and I use configuration  
{"hash_on":"vars","enable_websocket":false,"timeout":{"connect":15,"send":15,"read":15},"type":"chash","hash_on" : "vars_combinations","key" : "$request_uri$remote_addr","retries":3,"desc":"photo-api","id":"photo-api-upstream","name":"photo-api","nodes":{"192.168.17.14:23095":8,"192.168.17.14:23096":8}} , error info is change :

**Comment by Firstsawyou** [comment]
You need to provide the installation method and version information of apisix. It is best to have a minimum reproduction step.

> > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > ```
> > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > HTTP/1.1 500 Internal Server Error
> > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > Content-Type: text/html; charset=utf-8
> > > > > Content-Length: 154
> > > > > Connection: keep-alive
> > > > > Server: APISIX/2.2
> > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > ......
> > > > > ```
> > > > > 
> > > > > 
> > > > > This helps us troubleshoot the issue.
> > > > 
> > > > 
> > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > ```
> > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > HTTP/1.1 500 Internal Server Error
> > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > Content-Type: text/html; charset=utf-8
> > > > > Content-Length: 154
> > > > > Connection: keep-alive
> > > > > Server: APISIX/2.2
> > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > ......
> > > > > ```
> > > > > 
> > > > > 
> > > > > This helps us troubleshoot the issue.
> > > > > curl http://172.18.234.22:23111/tour/test.html -i
> > > > > log is :
> > > > > HTTP/1.1 500 Internal Server Error
> > > > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > > > Content-Type: text/html; charset=utf-8
> > > > > Content-Length: 1502
> > > > > Connection: close
> > > > > X-XSS-Protection: 1; mode=block
> > > > > X-Content-Type-Options: nosniff
> > > > > Referrer-Policy: no-referrer-when-downgrade
> > > > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > > > Pragma: no-cache
> > > > > Expires: 0
> > > 
> > > 
> > > Why is there no response header information for `Server: APISIX/2.2` ?
> 
> I set up apisix-2.1 In my machine and I use configuration
> {"hash_on":"vars","enable_websocket":false,"timeout":{"connect":15,"send":15,"read":15},"type":"chash","hash_on" : "vars_combinations","key" : "$request_uri$remote_addr","retries":3,"desc":"photo-api","id":"photo-api-upstream","name":"photo-api","nodes":{"192.168.17.14:23095":8,"192.168.17.14:23096":8}} , error info is change :
> HTTP/1.1 500 Internal Server Error
> Date: Thu, 04 Feb 2021 08:44:16 GMT
> Content-Type: text/html; charset=utf-8
> Content-Length: 174
> Connection: close
> Server: APISIX/2.1
> 
> Please check this error again

What is your apisix version? Is it 2.1?

**Comment by zhangxiaohui123456** [comment]
> You need to provide the installation method and version information of apisix. It is best to have a minimum reproduction step.
> 
> > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > ```
> > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > Content-Type: text/html; charset=utf-8
> > > > > > Content-Length: 154
> > > > > > Connection: keep-alive
> > > > > > Server: APISIX/2.2
> > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > ......
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > This helps us troubleshoot the issue.
> > > > > 
> > > > > 
> > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > ```
> > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > Content-Type: text/html; charset=utf-8
> > > > > > Content-Length: 154
> > > > > > Connection: keep-alive
> > > > > > Server: APISIX/2.2
> > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > ......
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > This helps us troubleshoot the issue.
> > > > > > curl http://172.18.234.22:23111/tour/test.html -i
> > > > > > log is :
> > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > > > > Content-Type: text/html; charset=utf-8
> > > > > > Content-Length: 1502
> > > > > > Connection: close
> > > > > > X-XSS-Protection: 1; mode=block
> > > > > > X-Content-Type-Options: nosniff
> > > > > > Referrer-Policy: no-referrer-when-downgrade
> > > > > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > > > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > > > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > > > > Pragma: no-cache
> > > > > > Expires: 0
> > > > 
> > > > 
> > > > Why is there no response header information for `Server: APISIX/2.2` ?
> > 
> > 
> > I set up apisix-2.1 In my machine and I use configuration
> > {"hash_on":"vars","enable_websocket":false,"timeout":{"connect":15,"send":15,"read":15},"type":"chash","hash_on" : "vars_combinations","key" : "$request_uri$remote_addr","retries":3,"desc":"photo-api","id":"photo-api-upstream","name":"photo-api","nodes":{"192.168.17.14:23095":8,"192.168.17.14:23096":8}} , error info is change :
> > HTTP/1.1 500 Internal Server Error
> > Date: Thu, 04 Feb 2021 08:44:16 GMT
> > Content-Type: text/html; charset=utf-8
> > Content-Length: 174
> > Connection: close
> > Server: APISIX/2.1
> > Please check this error again
> 
> What is your apisix version? Is it 2.1?

yes ，what version can support the configuration ?

**Comment by Firstsawyou** [comment]
> > You need to provide the installation method and version information of apisix. It is best to have a minimum reproduction step.
> > > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > > ```
> > > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > Content-Length: 154
> > > > > > > Connection: keep-alive
> > > > > > > Server: APISIX/2.2
> > > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > > ......
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > This helps us troubleshoot the issue.
> > > > > > 
> > > > > > 
> > > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > > ```
> > > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > Content-Length: 154
> > > > > > > Connection: keep-alive
> > > > > > > Server: APISIX/2.2
> > > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > > ......
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > This helps us troubleshoot the issue.
> > > > > > > curl http://172.18.234.22:23111/tour/test.html -i
> > > > > > > log is :
> > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > Content-Length: 1502
> > > > > > > Connection: close
> > > > > > > X-XSS-Protection: 1; mode=block
> > > > > > > X-Content-Type-Options: nosniff
> > > > > > > Referrer-Policy: no-referrer-when-downgrade
> > > > > > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > > > > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > > > > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > > > > > Pragma: no-cache
> > > > > > > Expires: 0
> > > > > 
> > > > > 
> > > > > Why is there no response header information for `Server: APISIX/2.2` ?
> > > 
> > > 
> > > I set up apisix-2.1 In my machine and I use configuration
> > > {"hash_on":"vars","enable_websocket":false,"timeout":{"connect":15,"send":15,"read":15},"type":"chash","hash_on" : "vars_combinations","key" : "$request_uri$remote_addr","retries":3,"desc":"photo-api","id":"photo-api-upstream","name":"photo-api","nodes":{"192.168.17.14:23095":8,"192.168.17.14:23096":8}} , error info is change :
> > > HTTP/1.1 500 Internal Server Error
> > > Date: Thu, 04 Feb 2021 08:44:16 GMT
> > > Content-Type: text/html; charset=utf-8
> > > Content-Length: 174
> > > Connection: close
> > > Server: APISIX/2.1
> > > Please check this error again
> > 
> > 
> > What is your apisix version? Is it 2.1?
> 
> yes ，what version can support the configuration ?

Yes, you need to update to version 2.2, version 2.1 does not support it.

**Comment by zhangxiaohui123456** [comment]
> > > You need to provide the installation method and version information of apisix. It is best to have a minimum reproduction step.
> > > > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > > > ```
> > > > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > > Content-Length: 154
> > > > > > > > Connection: keep-alive
> > > > > > > > Server: APISIX/2.2
> > > > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > > > ......
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This helps us troubleshoot the issue.
> > > > > > > 
> > > > > > > 
> > > > > > > > These error logs look very strange, the file that reported the error does not belong to apisix. Can you provide the response header data of the wrong request, like this:
> > > > > > > > ```
> > > > > > > > $ curl http://127.0.0.1:9080/hello -i
> > > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > > Date: Wed, 03 Feb 2021 01:35:00 GMT
> > > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > > Content-Length: 154
> > > > > > > > Connection: keep-alive
> > > > > > > > Server: APISIX/2.2
> > > > > > > > X-APISIX-Upstream-Status: 500, 500
> > > > > > > > ......
> > > > > > > > ```
> > > > > > > > 
> > > > > > > > 
> > > > > > > > This helps us troubleshoot the issue.
> > > > > > > > curl http://172.18.234.22:23111/tour/test.html -i
> > > > > > > > log is :
> > > > > > > > HTTP/1.1 500 Internal Server Error
> > > > > > > > Date: Thu, 04 Feb 2021 07:51:51 GMT
> > > > > > > > Content-Type: text/html; charset=utf-8
> > > > > > > > Content-Length: 1502
> > > > > > > > Connection: close
> > > > > > > > X-XSS-Protection: 1; mode=block
> > > > > > > > X-Content-Type-Options: nosniff
> > > > > > > > Referrer-Policy: no-referrer-when-downgrade
> > > > > > > > Strict-Transport-Security: max-age=31536000; includeSubdomains
> > > > > > > > Content-Security-Policy: default-src * data: 'unsafe-eval' 'unsafe-inline'
> > > > > > > > Cache-Control: no-cache, no-store, max-age=0, must-revalidate
> > > > > > > > Pragma: no-cache
> > > > > > > > Expires: 0
> > > > > > 
> > > > > > 
> > > > > > Why is there no response header information for `Server: APISIX/2.2` ?
> > > > 
> > > > 
> > > > I set up apisix-2.1 In my machine and I use configuration
> > > > {"hash_on":"vars","enable_websocket":false,"timeout":{"connect":15,"send":15,"read":15},"type":"chash","hash_on" : "vars_combinations","key" : "$request_uri$remote_addr","retries":3,"desc":"photo-api","id":"photo-api-upstream","name":"photo-api","nodes":{"192.168.17.14:23095":8,"192.168.17.14:23096":8}} , error info is change :
> > > > HTTP/1.1 500 Internal Server Error
> > > > Date: Thu, 04 Feb 2021 08:44:16 GMT
> > > > Content-Type: text/html; charset=utf-8
> > > > Content-Length: 174
> > > > Connection: close
> > > > Server: APISIX/2.1
> > > > Please check this error again
> > > 
> > > 
> > > What is your apisix version? Is it 2.1?
> > 
> > 
> > yes ，what version can support the configuration ?
> 
> Yes, you need to update to version 2.2, version 2.1 does not support it.

ok， I have a try。 Thank you

**Comment by nanamikon** [comment]
Refer to https://github.com/apache/apisix/issues/3261 and https://github.com/apache/apisix/releases/tag/2.2
I think 2.2 does not support vars_combinations ,   master branch may be you choice
