### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by zhangxiaohui123456** [apache/apisix#3520]
### Issue description
When upstream selects type chash hash_on as cookie  . This is what happened : 
When a request to an upstream node returns a 404, it keeps sending requests to that upstream node without making a request to another node
### Environment

* apisix version (cmd: `apisix version`):2.1
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Fixed by https://github.com/apache/apisix/pull/2676

**Comment by Firstsawyou** [comment]
Please note that your request is 404 and did not reach the upstream node. If the upstream node is unavailable, it should return a status code of `5xx`. You need to make the request hit the unavailable upstream node of a valid route before you can select other available nodes.

**Comment by zhangxiaohui123456** [comment]
> Please note that your request is 404 and did not reach the upstream node. If the upstream node is unavailable, it should return a status code of `5xx`. You need to make the request hit the unavailable upstream node of a valid route before you can select other available nodes.

but if  I choose roundrobin as upstream type , When a request to an upstream node returns a 404,  the request is turn another node .The access.log will be printed   multiple upstream information like this :172.18.193.68:23095, 172.18.193.68:23096,

**Comment by spacewander** [comment]
This was a bug in chash and already has been fixed. See my previous reply.

**Comment by zhangxiaohui123456** [comment]
> 这是chash中的错误，并且已得到修复。请参阅我以前的回复。

thanks

**Comment by zhangxiaohui123456** [comment]
> This was a bug in chash and already has been fixed. See my previous reply.

I see  the  Fixed by #2676 ,but My apisix version is 1.x ,Is there a way to fix it?

**Comment by spacewander** [comment]
You can wait for the 2.3 release, or patch APISIX by yourself.
