### ISSUE TITLE
bug: apisix cant find upstream and return 500

### ISSUE THREAD

**Issue by cocoonYh** [apache/apisix#3524]
### Issue description

i run apisix with docker for mac, and running server on mac directly.
apisix:2.2-centos
apisix-dashboard:2.3
etcd:3.4.9

### Environment

* apisix version (cmd: `apisix version`): 2.2
* OS (cmd: `uname -a`): Linux a664481da340 4.19.121-linuxkit
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.3

### Minimal test code / Steps to reproduce the issue

`
{
    "methods": ["GET"],
    "uri": "/v1/oms/sub_user",
    "service_protocol": "grpc",
    "plugins": {
        "grpc-transcode": {
         "proto_id": "1",
         "service": "oms.SubUserService",
         "method": "ListSubUser"
        }
    },
    "upstream_id": "340370032628335311"
}
`

`
/apisix/upstreams/340370032628335311
{"id":"340370032628335311","create_time":1612405948,"update_time":1612491017,"nodes":[{"host":"docker.for.mac.host.internal","port":9001,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"pass","name":"sub-user"}
`

### What's the actual result? (including assertion message & call stack if applicable)
got 500 resp, and here is err log
`
2021/02/05 02:10:23 [error] 43#43: *2543893 failed to run balancer_by_lua*: /usr/local/apisix/apisix/balancer.lua:165: attempt to index local 'up_conf' (a nil value)
stack traceback:
	/usr/local/apisix/apisix/balancer.lua:165: in function 'pick_server'
	/usr/local/apisix/apisix/balancer.lua:272: in function 'load_balancer'
	/usr/local/apisix/apisix/init.lua:758: in function 'http_balancer_phase'
	balancer_by_lua:2: in main chunk while connecting to upstream, client: 172.18.0.1, server: , request: "GET /v1/oms/sub_user HTTP/1.1", host: "127.0.0.1:9080"
`

**Comment by Firstsawyou** [comment]
It is very similar to the problem here and may have been fixed: 
https://github.com/apache/apisix/issues/3342 
https://github.com/apache/apisix/issues/3339

Try to configure another host, will this problem still occur?

```
"nodes":[{"host":"docker.for.mac.host.internal","port":9001,"weight":1}]
```

**Comment by cocoonYh** [comment]
> It is very similar to the problem here and may have been fixed:
> #3342
> #3339
> 
> Try to configure another host, will this problem still occur?
> 
> ```
> "nodes":[{"host":"docker.for.mac.host.internal","port":9001,"weight":1}]
> ```

i

**Comment by membphis** [comment]
@cocoonYh you can make a try with the master branch

**Comment by spacewander** [comment]
Closed as lack of response.
