### ISSUE TITLE
request help: Can I drop requests from Prometheus in access.log? 

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3526]
### Issue description
I enable the Prometheus plugin and the `access.log` file is filled with requests from Prometheus.
```
{"remote_addr":"","time_local":"05/Feb/2021:11:11:10 +0800","http_host":"","request":"GET /apisix/prometheus/metrics HTTP/1.1", "status": 200,"body_bytes_sent": 304059,"request_time":"0.085", "http_referrer":"","http_user_agent":"Prometheus/2.10.0","upstream_addr":"", "upstream_status":"","upstream_response_time":"", "upstream_url":"http://10.199.4.69", "uin":"","ti_project_id": ,"ti_business_id": , "api_version":"","client_ip":"","event_type":"", "service":"","action":"","request_id":""}
```
Should I remove these request logs? If so, how to remove them? What is the best practice?

### Environment

* apisix version (cmd: `apisix version`):2.1
* OS (cmd: `uname -a`): Linux 4.14.105-19-0017 #1 SMP Wed Oct 28 12:13:16 CST 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
nginx version: openresty/1.19.3.1
built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
built with OpenSSL 1.1.1h  22 Sep 2020
TLS SNI support enabled
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Since Nginx doesn't support disabling access log on the fly, AFAIK there is no way to do that.
Previously I solved this problem at the collector side, like skipping special UA/path in the filebeat/fluentd.

**Comment by diaosj** [comment]
> Since Nginx doesn't support disabling access log on the fly, AFAIK there is no way to do that.
> Previously I solved this problem at the collector side, like skipping special UA/path in the filebeat/fluentd.

Got it. Thanks!
Currently, I deal with it in the same way. Drop these in the filebeat.
