### ISSUE TITLE
request help: Why ip-restriction return json instead of default 403 error page

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#3528]
### Issue description
ip-restriction will return json when the remote ip matches blacklist
```
{"message":"Your IP address is not allowed"}
```

I think default 403 error page will be better,  or supporting an option to change this behavior is ok

### Environment

* apisix version (cmd: `apisix version`): 2.2
* OS (cmd: `uname -a`): ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):   3.4.13
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
As an API gateway, we prefer to communicate via HTTP+JSON instead of plain HTML.

**Comment by Firstsawyou** [comment]
I think it is reasonable to return json. As a gateway, apisix does not need to care about these web pages, this is not what it should focus on. You can display related pages based on the response code returned.

**Comment by nanamikon** [comment]
Thanks for reply,   I get your point.    Mixing api with the backstage management  is common usage of gateway in my comany, so I have to provide an option of using 403 error page or  json (as user format)

I can't achieve it without changing code, refer to ip-restriction.lua.
```
    if block then
        return 403, { message = "Your IP address is not allowed" }
    end
```

**Comment by spacewander** [comment]
You can submit a PR to customize the returned body part.

**Comment by nanamikon** [comment]
Refer to apisix/core/response.lua,   resp_exit will be called when error occours,  I think it is a global handle for response exit, we can't use plugin extension here。  What about redirecting to a new uri to do the actual work ？

Add method 
```
function _M.register_exit_handle_uri(uri){
       handle_uri = uri
}
```

Modify apisix/core/response.lua
Add exec to redirect to error handle
```
    if handle_uri then
        ngx.exec(handle_uri, {code=xxx, body=yyy});
    else
        if idx > 0 then
          ngx_print(concat_tab(t, "", 1, idx))
        end
    
        if code then
            return ngx_exit(code)
        end   
    end

```


Add new config to change this behavior
```
apisix:
      exit_handle_uri:"/error_handle"
     
```

New uri for error handle，added by http_server_configuration_snippet 
```
    location = /error_handle {
      content_by_lua '
        local args = ngx.req.get_uri_args()
        ngx.print(args.body)
        return ngx.exit(args.code)
      ';
    }
```

**Comment by nanamikon** [comment]
Btw，  some issus about how to customize error response format as follow

1 Kong error response
https://github.com/Kong/kong/issues/3192

2 Upstream error response
https://github.com/Kong/kong/issues/972

I can't find an official solution in kong so far，and I think it is important to customize apisix error response without modifying code in prd env ，as apsix growing so fast

**Comment by spacewander** [comment]
I think we should open another issue to discuss "exit_handle_uri", as it is not a trivial feature and not only relative with ip-restriction.

**Comment by nanamikon** [comment]
ok
