### ISSUE TITLE
bug: make deps prompt error

### ISSUE THREAD

**Issue by idbeta** [apache/apisix#3529]
### Environment

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): ubuntu 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

after excute
```
curl https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh -sL | sudo bash -
```
`make deps` prompt error:
```
mkdir -p ~/.luarocks
luarocks config --local variables.OPENSSL_LIBDIR /usr/local/openresty/openssl/lib

Error: Cannot create file at /home/xxxx/.luarocks/config-5.1.lua
Makefile:58: recipe for target 'deps' failed
make: *** [deps] Error 1
```

**Comment by spacewander** [comment]
Why you need `sudo` to create directory under `/home/xxxx` if you are `xxxx`?

**Comment by idbeta** [comment]
> Why you need `sudo` to create directory under `/home/xxxx` if you are `xxxx`?

because `/home/xxxx/.luarocks/config-5.1.lua` was created after execute linux-install-luarocks.sh
and make deps will again
```
luarocks config --local variables.OPENSSL_LIBDIR $(addprefix $(OR_PREFIX), openssl/lib)
```
