### ISSUE TITLE
request help: How to implement custom balancer?

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#3533]
### Issue description
Rerfer to apisix/init.lua,   there is no phase named "balancer" , so what's the plan to support balancer in the feature?

By the way,  I also try to use Script, but it does not support balancer phase either.

### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.17
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
Is it this one? https://github.com/apache/apisix/blob/master/apisix/init.lua#L711

**Comment by tokers** [comment]
Yes, now we cannot implement custom balancer yet. Do you have some good idea to support it?

**Comment by spacewander** [comment]
Why do you think we can't implement custom balancer? Just add your one under `apisix/balancer`.
