### ISSUE TITLE
request help: Can APISIX use certificates to access etcd？

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3535]
### Issue description
Etcd has an issue before 3.4.14: https://github.com/etcd-io/etcd/pull/12264. 
We are asked to sign and use certificates to access etcd.
Does APISIX support this? 

### Environment

Not related to the environment.

* apisix version (cmd: `apisix version`): 
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Client side certificate is not supported yet. Maybe you can use etcd-proxy?

**Comment by diaosj** [comment]
> Client side certificate is not supported yet. Maybe you can use etcd-proxy?

Thanks. I will try it.
