### ISSUE TITLE
bug: failed to run balancer_by_lua*: /usr/local/share/lua/5.1/resty/healthcheck.lua:247: attempt to index field 'targets' (a nil value)

### ISSUE THREAD

**Issue by kuberxy** [apache/apisix#3537]
### Issue description
2021/02/05 14:24:48 [error] 17384#17384: *114551120 failed to run balancer_by_lua*: /usr/local/share/lua/5.1/resty/healthcheck.lua:247: attempt to index field 'targets' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/resty/healthcheck.lua:247: in function 'get_target'
	/usr/local/share/lua/5.1/resty/healthcheck.lua:424: in function 'get_target_status'
	/usr/local/share/lua/5.1/apisix/balancer.lua:68: in function 'fetch_health_nodes'
	/usr/local/share/lua/5.1/apisix/balancer.lua:149: in function 'create_obj_fun'
	/usr/local/share/lua/5.1/apisix/core/lrucache.lua:92: in function 'lrucache_server_picker'
	/usr/local/share/lua/5.1/apisix/balancer.lua:246: in function 'pick_server'
	/usr/local/share/lua/5.1/apisix/balancer.lua:276: in function 'load_balancer'
	/usr/local/share/lua/5.1/apisix/init.lua:748: in function 'http_balancer_phase'
	balancer_by_lua:2: in main chunk while connecting to upstream, client: 183.95.49.7, server: , request:

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): 4.15.0-111-generic Ubuntu 18.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.15.8.3

**Comment by kuberxy** [comment]
the same issues:
[The targets is nil when call the function get_target after add target](https://github.com/Kong/lua-resty-healthcheck/issues/43#issue-607171476)

**Comment by membphis** [comment]
Have you tried the latest version?  you are using `2.1` version

**Comment by kuberxy** [comment]
I did not use it.

**Comment by spacewander** [comment]
Should be fixed by https://github.com/apache/apisix/pull/3240

**Comment by panhow** [comment]
@spacewander hello , wonder why #3240 can fix this issue ?

**Comment by membphis** [comment]
the `healthcheck` will call `resty-lock`, and the `resty-lock` will call `ngx.sleep`, but `ngx.sleep` can not be called in `balancer` phase. 

so we move it to access phase which allow to call `ngx.sleep`.
