### ISSUE TITLE
Add global plugins, such as cors, zipkin, and find that the response header appears twice. I want to know if the global plugin is called repeatedly internally, will this affect performance? ?

### ISSUE THREAD

**Issue by ShaoZeMing** [apache/apisix#3541]
### Issue description
Add global plugins, such as cors, zipkin, and find that the response header appears twice. I want to know if the global plugin is called repeatedly internally, will this affect performance? ?

I added cors and zipkin plugins globally, but I found that the response header appeared twice, so I want to ask.

Thank you

#### Example

![image](https://user-images.githubusercontent.com/19376576/107133878-b79b9580-6927-11eb-8b5f-7063df2a9821.png)

### Environment

* apisix version : 2.2-master
* OS (cmd: `uname -a`): linux  centos
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4
* apisix-dashboard version, if have: 2.3-docker

**Comment by spacewander** [comment]
It is fine to call global plugin multiple times, as there is a phase filter:
https://github.com/apache/apisix/blob/e5cd46e38e09d1025817381a3bf0b85a4f02a528/apisix/init.lua#L573-L574

If the global plugin doesn't define a method for a specific phase, it won't be run.

cors / zipkin are needed to be run in multiple phases with different code. The same code won't be run twice.

**Comment by ShaoZeMing** [comment]
> It is fine to call global plugin multiple times, as there is a phase filter:
> https://github.com/apache/apisix/blob/e5cd46e38e09d1025817381a3bf0b85a4f02a528/apisix/init.lua#L573-L574
> 
> If the global plugin doesn't define a method for a specific phase, it won't be run.
> 
> cors / zipkin are needed to be run in multiple phases with different code. The same code won't be run twice.

Thank you
