### ISSUE TITLE
request help: Configuration of the routing and upstream through apisix proxy access, the original project access address 127.0.0.1 / token, apisix proxy to access the address http://192.168.153.136:9000/token (IP and port corresponding to the output directory conf. Yaml configuration of IP + port)

### ISSUE THREAD

**Issue by xuyancheng24** [apache/apisix#3545]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):Linux 192.168.153.135 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):{"up_time":261183,"hostname":"localhost.localdomain","id":"f9fd7a15-4547-4c5f-8582-e95e96a0d4ce","last_report_time":1612679866,"version":"2.2","boot_time":1612418713,"etcd_version":"3.4.0"}
* apisix-dashboard version, if have:2.3

**Comment by Firstsawyou** [comment]
```
 http://192.168.153.136:9000/token 
```
Is the 9000 port a dashboard port?

**Comment by Firstsawyou** [comment]
By the way, your problem description should be placed in the following `Issue description`.

**Comment by xuyancheng24** [comment]
dashboard is9000

**Comment by Firstsawyou** [comment]
You should use the port monitored by apisix to access. If it is still not available, please provide your etcd configuration data.

**Comment by xuyancheng24** [comment]
![route](https://user-images.githubusercontent.com/37585344/107139796-da926d80-6958-11eb-8f3d-6700e46536d9.jpg)
![upstream](https://user-images.githubusercontent.com/37585344/107139797-dc5c3100-6958-11eb-916f-dd2a6ff249aa.jpg)


Apisix 9080 is not available，this is my  etcd configuration data（upstream and route）.

**Comment by Firstsawyou** [comment]
You need to determine if the upstream node `127.0.0.1:900` is available.
It is better to provide route and upstream configuration in etcd, rather than the configuration displayed by the dashboard.

**Comment by xuyancheng24** [comment]
how to get route and upstream configuration in etcd

**Comment by Firstsawyou** [comment]
> how to get route and upstream configuration in etcd

get all routes:  `etcdctl get --prefix /apisix/routes`
get all upstreams: `etcdctl get --prefix /apisix/upstreams`

**Comment by xuyancheng24** [comment]
/apisix/routes/340306895233352835
{"id":"340306895233352835","create_time":1612368316,"update_time":1612684479,"uris":["/token"],"name":"test","vars":[],"upstream_id":"340306661996496003","status":1}
/apisix/upstreams/340306661996496003
{"id":"340306661996496003","create_time":1612368177,"update_time":1612661041,"nodes":[{"host":"127.0.0.1","port":8099,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"node","name":"test"}

**Comment by xuyancheng24** [comment]
/apisix/routes/340306895233352835
{"id":"340306895233352835","create_time":1612368316,"update_time":1612684479,"uris":["/token"],"name":"test","vars":[],"upstream_id":"340306661996496003","status":1}
/apisix/upstreams/340306661996496003
{"id":"340306661996496003","create_time":1612368177,"update_time":1612661041,"nodes":[{"host":"127.0.0.1","port":8099,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"node","name":"test"}

**Comment by Firstsawyou** [comment]
> /apisix/routes/340306895233352835
> {"id":"340306895233352835","create_time":1612368316,"update_time":1612684479,"uris":["/token"],"name":"test","vars":[],"upstream_id":"340306661996496003","status":1}
> /apisix/upstreams/340306661996496003
> {"id":"340306661996496003","create_time":1612368177,"update_time":1612661041,"nodes":[{"host":"127.0.0.1","port":8099,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"node","name":"test"}

The upstream address in your title is `127.0.0.1/token`, but in your configuration it is `127.0.0.1:8099/token`. It is possible that your upstream node address is incorrect.

**Comment by xuyancheng24** [comment]
How to modify the upstream

**Comment by Firstsawyou** [comment]
> How to modify the upstream

You can directly modify your upstream node configuration through the dashboard.
Try to modify it to your available upstream address:
<img width="617" alt="截屏2021-02-07 下午4 45 19" src="https://user-images.githubusercontent.com/52862365/107141454-c142ee80-6963-11eb-8a52-53b92fb29acd.png">

**Comment by membphis** [comment]
can we close this issue now? @xuyancheng24
