### ISSUE TITLE
request help: Docker service not support ipv6.

### ISSUE THREAD

**Issue by eavesmy** [apache/apisix#3548]
### Issue description
My docker service not support ipv6 but nginx.conf has ```[::]: 8090```.
When i start apisix-dockr then log output 
```nginx: [emerg] socket() [::]:9080 failed (97: Address family not supported by protocol)```.

Does apisix has argument to turn ipv6 down?

**Comment by eavesmy** [comment]
Just edit config.yaml and 
```
enable_ipv6: false
```
Thx.

**Comment by Firstsawyou** [comment]
> Just edit config.yaml and
> 
> ```
> enable_ipv6: false
> ```
> 
> Thx.

You can set the parameter `enable_ipv6: true` to false in the configuration file.
