### ISSUE TITLE
request help: only enables upstream passive health checker

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3549]
It seems Apache APISIX cannot only enable the passive health checker for now.

![image](https://user-images.githubusercontent.com/10428333/107140304-21ce2d80-695c-11eb-9ad0-5e7ccb6f229f.png)

While it might be useful to only enable passive health check in Kubernetes, and leverage the Kubelet's liveness and readiness probe as the active health checker.

**Comment by spacewander** [comment]
Why do you think the health checker is different from https://github.com/apache/apisix/issues/2748?
