### ISSUE TITLE
change to a different port for controling API

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3550]
`9090` has been used by `prometheus` by default.

https://github.com/apache/apisix/blob/95c01707bf888ac7971b9469208bf767ac9b994a/doc/control-api.md

**Comment by spacewander** [comment]
The port can be configured.

**Comment by membphis** [comment]
We should use another port as default value

**Comment by spacewander** [comment]
As prometheus is resource intensive, people won't deploy it near the gateway. Usually people will deploy it in a separate cluster.

And such a change will be a break change and make people to distrust our API backward compatibility promise.

**Comment by membphis** [comment]
For developers or trial users, it is common to deploy apisix + prometheus locally.

Port conflicts will occur at this time.

**Comment by spacewander** [comment]
It can be solved by changing the configuration. There is no need to break the backward compatibility for development decision.

**Comment by membphis** [comment]
@starsz please know this

**Comment by starsz** [comment]
> @starsz please know this

OK.I got it.
