### ISSUE TITLE
request help: Does APISIX cut off request body when it is too large?

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3552]
### Issue description
I wrote a plugin to deal with the incoming request, then forwarded it to upstream servers. The simplified logic is like this:
```lua
local req_body, _ = core.request.get_body()
...

local decoded, _ = core.json.decode(req_body)
...

req_body, _ = core.json.encode(decoded)
core.log.warn("RequestId: ", ctx.var.request_id, " ctx.var.http_x_tc_action: ", ctx.var.http_x_tc_action, " req_body: ", req_body)

-- set body
ngx.req.set_body_data(req_body)
```

When the request (HTTP, POST JSON) is about 20k，the upstream server can't decode received data. I checked the APISIX log and found these two lines:
```
2021/02/07 15:35:30 [warn] 48#48: *110236 a client request body is buffered to a temporary file /usr/local/apisix/client_body_temp/0000000007, client: 172.17.48.15, server: , request: "POST /gateway?cmd=SaveFlow HTTP/1.1", host: "121.4.203.92"
2021/02/07 15:35:30 [warn] 48#48: *110236 [lua] rewrite-ti.lua:152: phase_func(): RequestId: e00dd516-e59a-43c2-90b4-a94ae6b93d76 ctx.var.http_x_tc_action: SaveFlow req_body: {"RequestId":"e00dd516-e59a-43c2-90b4-a94ae6b93d76", <xxx, too long>
```

I know that the default `client_body_buffer_size` value is 16k. The request's size exceeds this limit. So the request is buffered to a temp file. When printed to log, the content is cut off. I wonder which step caused this unexpected behavior.

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
I write a plugin to check it:
```
function _M.access(conf, ctx)
    local req_body, err = core.request.get_body()
    if not req_body then
        return 503, {message = err}
    end
    local decoded, err = core.json.decode(req_body)
    if not decoded then
        return 503, {message = err}
    end
    ngx.log(ngx.WARN, "get key ", decoded.key)
    return 200, decoded.key
end
```

And request it with this:
```
#!/usr/bin/env python
# coding: utf-8
# sudo pip install requests
import requests

resp = requests.put("http://127.0.0.1:9080/test", json={
    "key": "key",
    "value": "12345" * (1024 * 1024)
})
print(resp.status_code)
print(resp.text)
```

Then I get the result successfully:
```
2021/02/08 09:19:23 [warn] 1416#1416: *1248 a client request body is buffered to a temporary file .../client_body_temp/0000000001, client: 127.0.0.1, server: , request: "PUT /test HTTP/1.1", host: "127.0.0.1:9080"
2021/02/08 09:19:23 [warn] 1416#1416: *1248 [lua] x.lua:55: phase_func(): get key key, client: 127.0.0.1, server: , request: "PUT /test HTTP/1.1", host: "127.0.0.1:9080"
```

The wrong is in somewhere else.

**Comment by diaosj** [comment]
> I write a plugin to check it:
> 
> ```
> function _M.access(conf, ctx)
>     local req_body, err = core.request.get_body()
>     if not req_body then
>         return 503, {message = err}
>     end
>     local decoded, err = core.json.decode(req_body)
>     if not decoded then
>         return 503, {message = err}
>     end
>     ngx.log(ngx.WARN, "get key ", decoded.key)
>     return 200, decoded.key
> end
> ```
> 
> And request it with this:
> 
> ```
> #!/usr/bin/env python
> # coding: utf-8
> # sudo pip install requests
> import requests
> 
> resp = requests.put("http://127.0.0.1:9080/test", json={
>     "key": "key",
>     "value": "12345" * (1024 * 1024)
> })
> print(resp.status_code)
> print(resp.text)
> ```
> 
> Then I get the result successfully:
> 
> ```
> 2021/02/08 09:19:23 [warn] 1416#1416: *1248 a client request body is buffered to a temporary file .../client_body_temp/0000000001, client: 127.0.0.1, server: , request: "PUT /test HTTP/1.1", host: "127.0.0.1:9080"
> 2021/02/08 09:19:23 [warn] 1416#1416: *1248 [lua] x.lua:55: phase_func(): get key key, client: 127.0.0.1, server: , request: "PUT /test HTTP/1.1", host: "127.0.0.1:9080"
> ```
> 
> The wrong is in somewhere else.

Thanks. I'm struggling with it. Confusing.

**Comment by spacewander** [comment]
Feel free to reopen it if it is our problem.
