### ISSUE TITLE
bug: apisix-2.0 JWT 获取token，认证失败

### ISSUE THREAD

**Issue by NUPT-Pig** [apache/apisix#3553]
### Issue description
apisix-2.0 开启JWT认证，获取token的接口不定期失败
![image](https://user-images.githubusercontent.com/13393439/107147269-04af5400-6988-11eb-9b2c-9ad92ab87949.png)

在token的有效范围内认证存在不定期不通过的情况
![image](https://user-images.githubusercontent.com/13393439/107147128-4f7c9c00-6987-11eb-98c8-21d4701ab0e8.png)
![image](https://user-images.githubusercontent.com/13393439/107147130-54415000-6987-11eb-8970-88c1efc6e4d2.png)
![image](https://user-images.githubusercontent.com/13393439/107147136-5dcab800-6987-11eb-9ff7-4b11c82139f3.png)

### Environment

* apisix version (cmd: `apisix version`):2.0
* OS (cmd: `uname -a`):k8s部署
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.14
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. curl http://apisix-gw-lb.default.svc.cluster.local:9080/apisix/plugin/jwt/sign?key=USER_NAME
2. 获取token后，发送任意的请求

**Comment by spacewander** [comment]
For OpenResty 1.19, you should use APISIX 2.2 and higher.
See https://github.com/apache/apisix/blob/master/CHANGELOG_CN.md#bugfix
