### ISSUE TITLE
bug: test case not stable: t/plugin/tcp-logger.t

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#3560]
### Issue description

Test failed in CI and rerun succeeds, but the error seems could not be reproduced on my side.
```
#   Failed test 'TEST 7: check plugin configuration updating - status code ok'
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 948.
#          got: '404'
#     expected: '200'

#   Failed test 'TEST 7: check plugin configuration updating - response_body - response is expected (repeated req 0, req 0)'
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 1589.
# @@ -1,2 +1 @@
# -passedopentracing
# +fail
# -passedopentracing

#   Failed test 'TEST 7: check plugin configuration updating - grep_error_log_out (req 0)'
#   at /home/runner/work/apisix/apisix/test-nginx/lib/Test/Nginx/Socket.pm line 1149.
# @@ -1,2 +0,0 @@
# -sending a batch logs to 127.0.0.1:5044
# -sending a batch logs to 127.0.0.1:5045
# Looks like you failed 3 tests of 21.
t/plugin/tcp-logger.t ...................... 
Dubious, test returned 3 (wstat 768, 0x300)
```

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/issues/3450

**Comment by Yiyiyimu** [comment]
Thanks @spacewander good to know that!

BTW, which aspect of chaos test do you think would be helpful to this issue

**Comment by spacewander** [comment]
It is obvious. And people have complained about it since last year. The problem is that we don't have enough resource to solve it early.

**Comment by Yiyiyimu** [comment]
> This is a known issue. We plan to start pulling etcd data in the `init_worker` phase. To achieve this, we need to implement two preconditions first:
> 
> 1. add Chaos test so that we can cover such a big change
> 2. allow lua-resty-etcd to use luasocket.
> 
> Maybe we can do this in version `2.5`.

I mean you talked about using chaos test to better cover the critical change, is there any specific test do you think would be of help?
