### ISSUE TITLE
request help: enable websocket 

### ISSUE THREAD

**Issue by cgc1983** [apache/apisix#3568]
### Issue description
create websocket route  but client cant not connect server

1.create a route
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/index.html",
    "hosts": ["foo.com", "*.bar.com"],
    "remote_addrs": ["127.0.0.0/8"],
    "methods": ["PUT", "GET"],
    "enable_websocket": true,
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}'

2. use this command line to get route info curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'  , the response body donot have eanbel_websocket flag

### Environment
apisix 2.1

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
I tested it and there is an eanbel_websocket field. You can check it again.

```
./bin/apisix version
2.1
```

```
$ curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
{"action":"get","header":{"revision":"114129","cluster_id":"14841639068965178418","raft_term":"9","member_id":"10276657743932975437"},"count":"1","node":{"createdIndex":112829,"modifiedIndex":114129,"value":{"priority":0,"uri":"\/index.html","enable_websocket":true,"create_time":1612693019,"methods":["PUT","GET"],"hosts":["foo.com","*.bar.com"],"id":"1","upstream":{"type":"roundrobin","pass_host":"pass","nodes":{"39.97.63.215:80":1},"hash_on":"vars"},"remote_addrs":["127.0.0.0\/8"],"update_time":1612857507},"key":"\/apisix\/routes\/1"}}
```

**Comment by Firstsawyou** [comment]
For an example of using eanbel_websocket, you can refer to the test case： https://github.com/apache/apisix/blob/master/t/node/upstream-websocket.t

**Comment by cgc1983** [comment]
i got it
if i edit the route in dashboard and save the route config, the enable_socket flag had lost
