### ISSUE TITLE
request help: Apisix agent access error 502, Dashboard configuration upstream IP information and the background log error IP information is inconsistent

### ISSUE THREAD

**Issue by xuyancheng24** [apache/apisix#3569]
### Environment

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):Linux 192.168.153.135 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* {"up_time":261183,"hostname":"localhost.localdomain","id":"f9fd7a15-4547-4c5f-8582-e95e96a0d4ce","last_report_time":1612679866,"version":"2.2","boot_time":1612418713,"etcd_version":"3.4.0"}
![9ZRD F`GTB ~8 6{`PRMV](https://user-images.githubusercontent.com/37585344/107340053-45c67600-6af8-11eb-8558-6b84514430a9.png)
[dashboard-conf.txt](https://github.com/apache/apisix/files/5950104/dashboard-conf.txt)
[apisix-config-default.txt](https://github.com/apache/apisix/files/5950105/apisix-config-default.txt)
[apisix-config.txt](https://github.com/apache/apisix/files/5950106/apisix-config.txt)

* apisix-dashboard version, if have:2.3

**Comment by xuyancheng24** [comment]
/apisix/consumers/
init_dir
/apisix/data_plane/server_info/f9fd7a15-4547-4c5f-8582-e95e96a0d4ce
{"id":"f9fd7a15-4547-4c5f-8582-e95e96a0d4ce","hostname":"localhost.localdomain","version":"2.2","boot_time":1612418713,"etcd_version":"3.4.0","up_time":439272,"last_report_time":1612857985}
/apisix/global_rules/
init_dir
/apisix/node_status/
init_dir
/apisix/plugin_metadata/
init_dir
/apisix/plugins
[{"name":"api-breaker"},{"name":"authz-keycloak"},{"name":"basic-auth"},{"name":"batch-requests"},{"name":"consumer-restriction"},{"name":"cors"},{"name":"echo"},{"name":"fault-injection"},{"name":"grpc-transcode"},{"name":"hmac-auth"},{"name":"http-logger"},{"name":"ip-restriction"},{"name":"jwt-auth"},{"name":"kafka-logger"},{"name":"key-auth"},{"name":"limit-conn"},{"name":"limit-count"},{"name":"limit-req"},{"name":"openid-connect"},{"name":"prometheus"},{"name":"proxy-cache"},{"name":"proxy-mirror"},{"name":"proxy-rewrite"},{"name":"redirect"},{"name":"referer-restriction"},{"name":"request-id"},{"name":"request-validation"},{"name":"response-rewrite"},{"name":"serverless-post-function"},{"name":"serverless-pre-function"},{"name":"sls-logger"},{"name":"syslog"},{"name":"tcp-logger"},{"name":"udp-logger"},{"name":"uri-blocker"},{"name":"wolf-rbac"},{"name":"zipkin"},{"name":"server-info"},{"name":"traffic-split"},{"name":"mqtt-proxy","stream":true}]
/apisix/plugins/
init_dir
/apisix/proto/
init_dir
/apisix/routes/
init_dir
/apisix/routes/340306895233352835
{"id":"340306895233352835","create_time":1612368316,"update_time":1612844248,"uris":["/token"],"name":"test","vars":[],"plugins":{"api-breaker":{"break_response_code":502,"disable":true,"healthy":{"http_statuses":[200],"successes":1},"unhealthy":{"failures":2,"http_statuses":[500,503]}},"ip-restriction":{"disable":true,"whitelist":["127.0.0.1","113.74.26.106/24"]},"referer-restriction":{"bypass_missing":false,"disable":true,"whitelist":["xx.com","*.xx.com"]},"request-validation":{"body_schema":{"properties":{"string_payload":{"maxLength":2,"minLength":1,"type":"string"}},"required":["string_payload"],"type":"object"},"disable":true}},"upstream_id":"340991270086247561","status":1}
/apisix/routes/341121850077611147
{"id":"341121850077611147","create_time":1612854066,"update_time":1612854304,"uris":["/token2"],"name":"test2","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"vars":[],"upstream_id":"341122161529848971","status":1}
/apisix/services/
init_dir
/apisix/ssl/
init_dir
/apisix/stream_routes/
init_dir
/apisix/upstreams/
init_dir
/apisix/upstreams/340991270086247561
{"id":"340991270086247561","create_time":1612776235,"update_time":1612844189,"nodes":[{"host":"172.22.70.41","port":8099,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"pass","name":"test","desc":"http://172.22.70.41:8099/token"}
/apisix/upstreams/341122161529848971
{"id":"341122161529848971","create_time":1612854252,"update_time":1612854266,"nodes":[{"host":"172.22.70.41","port":8098,"weight":1}],"timeout":{"connect":6000,"read":6000,"send":6000},"type":"roundrobin","pass_host":"pass","name":"test2","desc":"http://172.22.70.41:8098/"}

**Comment by Firstsawyou** [comment]
Hi, @xuyancheng24 
Please provide the error log information of dashboard and apisix. . Thank you.

**Comment by xuyancheng24** [comment]
2021/02/09 14:24:51 [error] 41268#41268: *33377211 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.153.1, server: , request: "GET /token HTTP/1.1", upstream: "http://172.22.70.54:8099/token", host: "192.168.153.140:9080"
2021/02/09 14:40:31 [error] 41266#41266: *33494752 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.153.1, server: , request: "GET /token HTTP/1.1", upstream: "http://172.22.70.54:8099/token", host: "192.168.153.140:9080"
2021/02/09 15:05:52 [error] 41265#41265: *33682137 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.153.1, server: , request: "GET /token HTTP/1.1", upstream: "http://172.22.70.54:8099/token", host: "192.168.153.140:9080"
2021/02/09 17:42:02 [error] 41268#41268: *34855742 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.153.1, server: , request: "GET /token HTTP/1.1", upstream: "http://172.22.70.54:8099/token", host: "192.168.153.140:9080"

**Comment by xuyancheng24** [comment]
2021-02-09T16:13:38.528+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T16:34:52.664+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T16:34:52.664+0800	WARN	store/store.go:142	data not found by key: 341121850077611147
2021-02-09T16:34:56.325+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T17:12:19.106+0800	WARN	filter/authentication.go:46	token validate failed: token is expired by 7m35s
2021-02-09T17:12:19.141+0800	WARN	filter/authentication.go:46	token validate failed: token is expired by 7m35s
2021-02-09T17:12:26.743+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T17:12:26.743+0800	WARN	store/store.go:142	data not found by key: 341121850077611147
2021-02-09T17:12:28.656+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T17:13:13.491+0800	WARN	store/store.go:142	data not found by key: 340306895233352835
2021-02-09T17:13:13.491+0800	WARN	store/store.go:142	data not found by key: 341121850077611147
2021-02-09T17:13:15.458+0800	WARN	store/store.go:142	data not found by key: 340306895233352835

**Comment by nic-chen** [comment]
@Firstsawyou 

It looks OK from these data. Can problems be reproduced with these configurations?

**Comment by Firstsawyou** [comment]
@nic-chen  @xuyancheng24   I tried and didn't find this problem (dashboard 2.3, apisix 2.2), I think it is probably because the version of dashboard and apisix are inconsistent. Because when I use `dashboard 2.3, apisix 2.1`, the configured route 404 problem occurs.

@xuyancheng24 Please confirm the version of your dashboard and apisix?

**Comment by Firstsawyou** [comment]
> * apisix version (cmd: `apisix version`):2.3

The 2.3 version of apisix has just been released. Are you using the 2.3 branch?

**Comment by xuyancheng24** [comment]
I used 2.2 Apisix

**Comment by Firstsawyou** [comment]
Hi, @xuyancheng24 
You need to pay attention to whether the version used matches. If there are still errors, you can try to use the `curl` tool to initiate a request to narrow down the location of the problem.
