### ISSUE TITLE
bug: fail to run make deps on MacOS with luarocks 3.5

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix#3575]
### Issue description

when run `make deps` on Mac with luarocks, it keep showing error  `No results matching query were found for Lua 5.4.` during install lua-resty-dns-client.

As we can see from https://github.com/Kong/lua-resty-dns-client/blob/master/lua-resty-dns-client-5.2.1-1.rockspec

`lua-resty-dns-client` requires `lua >= 5.1, < 5.4`, but by default luarocks 3.5 is using `/usr/local/opt/lua/bin/lua5.4`

which caused this issue

**Comment by lilien1010** [comment]
My way to make sure `make deps` run smoothly is open `/usr/local/bin/luarocks` and chang `/usr/local/opt/lua/bin/lua5.4` to `/usr/local/bin/lua` at the first line.

**Comment by lilien1010** [comment]
for long term solution, migth need to  `lua-resty-dns-client` allowed to install with lua 5.4.

**Comment by spacewander** [comment]
We recommend to install luarocks via source and bind it with luajit, see:
https://github.com/apache/apisix/blob/master/doc/install-dependencies.md#note

> we recommend installing LuaRocks via source code

A script has been provided to install luarocks automatically: https://github.com/apache/apisix/blob/master/utils/linux-install-luarocks.sh
And we have updated the installation instruction for Linux distributions.

Unfortunately, I don't have Mac. Maybe you can provide the script for Mac and update the instruction for Mac?

Thanks!

**Comment by membphis** [comment]
@lilien1010 do you still have this issue? if yes, please let us know

**Comment by lilien1010** [comment]
@membphis 
As I mentioned above, I mannuly change code of luarocks，which works fine for me, but it's not strongly recommend edit executable file.

I think still someone gona encounter with this if they install luarocks with homebrew which might install lua 5.4 automatically, that will caused an incompatible issue from lua-resty-dns-client.

**Comment by membphis** [comment]
@nic-chen would like to handle this issue?

**Comment by nic-chen** [comment]
> @nic-chen would like to handle this issue?

OK
