### ISSUE TITLE
feat(CI): transfer some testing to CircleCI to reduce the load on GitHub Actions

### ISSUE THREAD

**Issue by jbampton** [apache/apisix#3585]
GitHub Actions has usage limits for each repo and when running many builds from lots of concurrent pull requests it can be slow and even time out tests for some of the largest GitHub projects with lots of tests.

CircleCI is free for Open Source and we do already have some `Travis CI` files in the APISIX repo.
Adding another testing service can also expand the `testing matrix` or can add more tests and more varied tests as well.
Knowledge of CircleCI another testing framework or website can also add extra and valuable skills and experience to the existing APISIX team members and committers.

A lot of the more minor testing could be moved across to CircleCI using `green` certified `orbs`.  The existing GitHub Action testing for linting Markdown and YAML is quick to run, but the switch to using the GitHub Super Linter means that it runs a lot slower.  There are more checks with the GitHub Super Linter and it is just slower to run generally.  Also as time passes more and more tests are being added to GitHub Actions making each pull request slower to run.

We can add tests for Go with `vet`, `fmt`, `golint`, `revive` and more. We can move the spell checker script `misspell` and include it with the Go tests since it's written in Golang.  We can also add tests for `Markdownlint` and `yamllint`.  We can add a new test with `Shellcheck` which checks shell script. We can add some general-purpose tools to help analyze, debug, and optimize the CircleCI builds.  There are lots more `orbs` too.

All the links below that list the orbs are `green` certified: build-tools, go, python, shellcheck and node.

I am not sure what the policies of the ASF are for using CircleCI.

If this feature sounds valuable then I would like to do the work and add the pull request to fix this issue 👍 

refs #3045 
refs #3247 
refs #3250
refs #3581 

https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration
https://circleci.com/
https://circleci.com/orbs/
https://yamllint.readthedocs.io/en/stable/
https://www.npmjs.com/package/markdownlint-cli
https://github.com/koalaman/shellcheck
https://github.com/client9/misspell
https://blog.golang.org/gofmt
https://golang.org/cmd/vet/
https://revive.run/
https://pkg.go.dev/golang.org/x/lint/golint
https://circleci.com/developer/orbs/orb/circleci/build-tools
https://circleci.com/developer/orbs/orb/circleci/go
https://circleci.com/developer/orbs/orb/circleci/python
https://circleci.com/developer/orbs/orb/circleci/shellcheck
https://circleci.com/developer/orbs/orb/circleci/node

**Comment by spacewander** [comment]
> CircleCI is free for Open Source and we do already have some Travis CI files in the APISIX repo.

We have some Travis CI files because we used Travis CI before. Migrate Travis CI files to GitHub Action took us many efforts.

Maintain CI across multiple vendors is too complex. And CircleCI might become the next Travis CI.
