### ISSUE TITLE
docs: add Spanish translations

### ISSUE THREAD

**Issue by jbampton** [apache/apisix#3587]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

From a Google search `Spanish` is now the world's **4th most spoken language** in the world.

<img width="620" alt="Screen Shot 2021-02-12 at 6 23 19 am" src="https://user-images.githubusercontent.com/418747/107695225-05374a00-6cfc-11eb-81e0-ce577b8f55ae.png">

## Describe the solution you'd like

A translation process overtime where the Markdown documentation files are translated into Spanish. 

First doc to translate would be the `README` as `README_ES.md`.

I am offering to work on this doing most of the GitHub, Git, training and management work if needed.  I run a small team where I train people too and even have some friends that write in India and Asia.

I don't speak Spanish but I have three colleagues which I have worked with before that all speak and write Spanish and do translations. One also does **Portuguese** translations. All 3 are my friends and they all live in South America.  Only 2 are currently available to help but I am waiting to hear back from the 3rd person can take some time sometimes etc. Normally I get one person to do the English to Spanish translation and then another to check the work and it works well.

I also have contacts in India and four more in South America too.

One person has already forked the `APISIX` repo and created some translated text as a `test` of using and practising with GitHub.  I need to sometimes assist them with Git and GitHub best practices as most people are newish to GitHub and not coders but technical writers, translators, virtual assistants,  project managers, designers and graphic designers.

Timezones are a lot different between the four us since I'm in `Australia` and they are in `South America` so sometimes there can be additional delays when doing tasks etc.  

I look at translating the docs to Spanish as a slow but **very fruitful** process and having a third language is a **great feature** and **important marketing effort** for APISIX. Spanish is a global language.  Also I can help with some automated checking of English and Spanish translations using Google translate.

**Comment by jbampton** [comment]
Jorge -> @summerhill5 started on the Spanish translation.  This is really one of his first times trying to use GitHub by himself but I have helped a small amount.  Looks like he has done about half the `README.md` in Spanish.  

He was editing directly on the GitHub website as he is not sure about Git commands.  I did get him to download and install GitHub Desktop as well and tried to provide some instructions.  We will end up naming the file `README_ES.md` as `ES` is the code for Spain.  Jorge made a small mistake and renamed the English `README.md` instead of creating a new file.

When it comes time to merge the work I will get admin access on Jorge's APISIX fork and do the rebase, squash and fix ups etc.

https://github.com/summerhill5/apisix/blob/patch-1/README_Spanish.md

![translated](https://user-images.githubusercontent.com/418747/107885398-d01e3800-6f45-11eb-81aa-6da80baf4d37.jpg)

**Comment by spacewander** [comment]
@jbampton 
Thanks for your and your teammates' contributions!

@moonming 
As the discussion in https://lists.apache.org/thread.html/r0d5d3f55b709f4d019a1492b68dd631daa854ae5b31802557eb1e3e7%40%3Cdev.apisix.apache.org%3E and https://lists.apache.org/thread.html/r2c8e5372fbaa301433691c3e97b245e0ba8970c91c9486ec22cfc050%40%3Cdev.apisix.apache.org%3E,
should we provide a separate repo to hold the i18n files?

**Comment by spacewander** [comment]
Also CC @juzhiyuan @membphis

**Comment by juzhiyuan** [comment]
Ya, this main repo only maintains documentation in English, contributors would create repos like `apache-apisix-in-spanish` or something else.

**Comment by spacewander** [comment]
@juzhiyuan 
What's the roadmap for it?

**Comment by membphis** [comment]
ping @juzhiyuan

**Comment by juzhiyuan** [comment]
Today I just send a mail to our mailing list, I would prefer that we need to make sure the English docs are correct, reliable, up-to-date, and easy to learn first. For other languages, our community's contributors could help to maintain them.

**Comment by juzhiyuan** [comment]
So we could review and accept this PR.

**Comment by membphis** [comment]
> Today I just sent a mail to our mailing list, I would prefer that we need to make sure the English docs are correct, reliable, up-to-date, and easy to learn first. For other languages, our community's contributors could help to maintain them.

I think you can post the mail link here ^_^

**Comment by juzhiyuan** [comment]
sure, here it is.

https://lists.apache.org/thread.html/r0d5d3f55b709f4d019a1492b68dd631daa854ae5b31802557eb1e3e7%40%3Cdev.apisix.apache.org%3E

**Comment by jbampton** [comment]
@summerhill5 and I are going to work on translating `FAQ.md` next.

Will be doing this over the next week or so 👍

**Comment by jbampton** [comment]
Hello everyone. 

A very sad day has come and our dear friend Jorge @summerhill5 has died of COVID-19 in Venezuela.   

Jorge died in hospital and was sick for over 3 weeks.  The Crisis in Venezuela during the Bolivarian Revolution is an ongoing socioeconomic and political crisis that began in Venezuela on 2 June 2010 during the presidency of Hugo Chávez and has continued since.   I believe the hospital facilities in Venezuela are bad too.

Jorge translated the README and FAQ to Spanish and he was a really good worker and will be badly missed.

I have some other friends that translate to Spanish but I am not sure if they will help us or whether they can do complex technical translations but I will ask them.

**Comment by moonming** [comment]
@jbampton I am very sorry to hear that. 
R.I.P. @summerhill5

**Comment by membphis** [comment]
Thank Jorge Araica @summerhill5 very much.
Because of the open-source code, we have the opportunity to work together.

Thanks to everyone who loves technology and loves sharing for making this world a harmonious family.
