### ISSUE TITLE
bug(CI): markdown link check not failing when broken links found

### ISSUE THREAD

**Issue by jbampton** [apache/apisix#3592]
### Issue description

The GitHub Action for checking for broken links is not working or failing when broken links are found.

### Environment

npm -> https://www.npmjs.com/package/markdown-link-check

### Minimal test code / Steps to reproduce the issue

1. Install `markdown-link-check` with npm -> https://github.com/tcort/markdown-link-check
2. Run `markdown-link-check README.md`

### What's the actual result? (including assertion message & call stack if applicable)

```
[✖] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/clustering.md → Status: 404
```

### What's the expected result?

No broken links

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/pull/3197

Hi @jbampton, I see you modified the previous CI 🤔 Could we use the previous CI? and apply for the allow list from infra?

**Comment by jbampton** [comment]
Hey @juzhiyuan we can't use the orignal check since it was using a third-party GitHub Action which the ASF banned.

**Comment by juzhiyuan** [comment]
Ya, we have 2 solutions now:

1. Ask ASF Infra for help to allow that action;
2. Try to update the current action to throw warnings when broken links are found.

What do you think?

**Comment by jbampton** [comment]
Hey @juzhiyuan I am unsure of what is happening now since `Apache SkyWalking` uses a dead link checker with the same npm library as we do -> https://github.com/apache/skywalking/blob/master/.github/workflows/dead-link-checker.yaml

But their's seems to be running against all files instead of just modified files.

I think we should try to update the existing action or at least debug it since using third-party GitHub Actions is a security risk.

**Comment by juzhiyuan** [comment]
> But their's seems to be running against all files instead of just modified files.

Ya, maybe Skywalking has fixed all dead links first? then enable that checker for all files 🤔 

I still prefer just checking the modified files IMO.

**Comment by spacewander** [comment]
Now markdown-link-check is removed.
