### ISSUE TITLE
how to set the JWT content as header values?

### ISSUE THREAD

**Issue by henryfoster** [apache/apisix#3594]
### Issue description
Hi,
I need apisix to validate a JWT token in the request header that was issued by my own auth-service and set the content of the JWT token (like user_id) as header arguments. I've read through the JWT doc section, but I can't find how to set the JWT content as header values.
### Environment

* apisix version (cmd: `apisix version`): latest
* OS (cmd: `uname -a`): ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): latest
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
The JWT token is set as the request header, you can refer to here: https://github.com/apache/apisix/blob/master/doc/plugins/jwt-auth.md#try-request-with-token . Hope to help you.

**Comment by henryfoster** [comment]
I think you misunderstood me. I mean how can I set the **content** of the token after it was verified by apisix?
A JWT usually contains information about the user like the **userID** and **permissions** the user has.
After apisix verified that the token is valid I need to set this information as header values on the request **instead** of the JWT and forward it to the destination service.

So the request Header would contain:
 "userID": "023984u2034423",
 "roles": "ROLE_ADMIN" 
 for example.

**Comment by tokers** [comment]
@henryfoster Try the [serverless plugin](https://github.com/apache/apisix/blob/master/doc/plugins/serverless.md), you can fetch the Authorization header in it (like `ngx.req.get_headers`, `ngx.var.http_authorization`) but one thing should be noticed that you cannot get any JWT parsing artifacts generated by Apache APISIX so you may need to do the duplicate works, or you may try to get insight into the JWT code base in Apache APISIX to write concise codes.

**Comment by nic-chen** [comment]
Currently, plugin `jwt-auth` does not pass consumer info to the back-end service.
But it should be simple to implement such a feature, we could refer to: https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua#L317-L318

**Comment by benx203** [comment]
You can consider use this:
https://github.com/benx203/apisix/blob/jwt-auth-support-content/apisix/plugins/jwt-auth.lua

test:
payload is result of encodeURIComponent,eg:
payload:{"aaa":"11","bb":"222"},after encode is %7B%22aaa%22%3A%2211%22%2C%22bb%22%3A%22222%22%7D.

sign:
curl "http://127.0.0.1:9080/apisix/plugin/jwt/sign?key=user-key&payload=%7B%22aaa%22%3A%2211%22%2C%22bb%22%3A%22222%22%7D"

view info:
curl "http://127.0.0.1:9080/apisix/plugin/jwt/user-info?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhYWEiOiIxMSIsImtleSI6InVzZXIta2V5IiwiZXhwIjoxNjE4NTU4OTg2LCJiYiI6IjIyMiJ9.vwOMS2oeHU-H45rrwt1O2oPg8c7C8z9dDK0UzEhD3dk" -i

response:
{"user_info":{"bb":"222","key":"user-key","exp":1618558986,"aaa":"11"}}

**Comment by tzssangglass** [comment]
> How to pass consumer information to the back-end API?

see: https://github.com/apache/apisix/issues/4078#issuecomment-822231019

BTW, you can search or open a new issue, instead of commenting on unrelated issues in an issue that is already closed.

**Comment by ecoupal-believe** [comment]
Would it be possible to the same with openid connect ?
