### ISSUE TITLE
request help: What are the advantages of replacing curl with luasocket when connecting to etcd?

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3596]
### Issue description
I noticed that in v2.3, when connecting to etcd (such as auth and put requests), APISIX switches from curl to luasocket in the  `apisix/cli/etcd.lua` file. What are the advantages? Is this more efficient?

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/issues/2818
