### ISSUE TITLE
request help: How to config etcd with https

### ISSUE THREAD

**Issue by zackzhangkai** [apache/apisix#3599]
### Issue description

```
# etcd:
#     host:
#       - "http://127.0.0.1:2379"
#
# To configure via environment variables, you can use `${{VAR}}` syntax. For instance:
#
# etcd:
#     host:
#       - "http://${{ETCD_HOST}}:2379"
```

How to config etcd private key and cert, if my etcd use https?

**Comment by Firstsawyou** [comment]
You can look here:https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L193-L204
It should help you.

**Comment by zackzhangkai** [comment]
This is used password , not use cerfile. How can I config my cafile path , such as `/etc/ssl/etcd/ssl` ?

**Comment by zackzhangkai** [comment]
My confguration is as follows, but it doesn't work:

```bash
etcd:
  host:
    - "https://127.0.0.1:2379"
  tls:
    verify: true
    ssl_trusted_certificate: /etc/ssl/etcd/ssl/ # Specifies a file path with trusted CA certificates in the PEM format
...
```

**Comment by tokers** [comment]
@zackzhangkai Currently the mTLS is not support yet.

**Comment by tokers** [comment]
@zackzhangkai You may try to use etcd proxy.

**Comment by zackzhangkai** [comment]
Not the mTLS, just https, you can understand as single tls.

**Comment by tokers** [comment]
> Not the mTLS, just https, you can understand as single tls. 

Sorry, I misunderstood your mean since I saw the CA configuration.

What's the behavior of "not work"? Could you paste some error logs?

**Comment by zackzhangkai** [comment]
I have consult the codes, and  cannot find where to placeholder the certificates. The configuration `ssl_trusted_certificate` maybe not correct. I just test it, and it takes no effect.  I just want to know how to configure with https with certificate.

Apisix version is latest.

**Comment by tokers** [comment]
@zackzhangkai You don't need to configure certificates on APISIX side. Just use "https" scheme in `etcd.host` is enough.

**Comment by zackzhangkai** [comment]
configmap as follows:
```bash
data:
  config.yaml: |
    etcd:
      host:
        - "https://127.0.0.1:2379"
    apisix:
      admin_key:
        - name: "admin"
          # yamllint disable rule:comments-indentation
          key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
          # yamllint enable rule:comments-indentation
          role: admin
kind: ConfigMap
```
errors as follows:

```
k logs -f apisix-gw-deployment-57997cbbcd-q9j8n
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
request etcd endpoint 'https://127.0.0.1:2379/version' error, connection refused
```

**Comment by tokers** [comment]
@zackzhangkai How did you deploy APISIX and etcd cluster? Do they in the same pod? If not, you cannot access etcd from APISIX by `127.0,0.1`. You should, however, filling the correct IP address or domain like "{etcd-service-name}.{namespace}.svc.cluster.local".

**Comment by zackzhangkai** [comment]
```bash
# curl https://127.0.0.1:2379/version --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/admin-ssa3.pem   --key /etc/ssl/etcd/ssl/admin-ssa3-key.pem
{"etcdserver":"3.3.12","etcdcluster":"3.3.0"}
```

**Comment by zackzhangkai** [comment]
It's about the etcd pem and key, not the address.

**Comment by tokers** [comment]
> ```shell
> # curl https://127.0.0.1:2379/version --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/admin-ssa3.pem   --key /etc/ssl/etcd/ssl/admin-ssa3-key.pem
> {"etcdserver":"3.3.12","etcdcluster":"3.3.0"}
> ```

Since you mentioned that your etcd cluster doesn't enable the mTLS, why your curl call still carries the client cert, key and cacert?

**Comment by zackzhangkai** [comment]
configmap: 

```bash
data:
  config.yaml: |
    etcd:
      host:
        - "https://etcd.kube-system.svc.cluster.local:2379"
      tls:
        verify: true
    apisix:
      ssl:
        ssl_trusted_certificate: /etc/ssl/etcd/ssl/
```

deployment mount this volume:

```bash
        - mountPath: /etc/ssl/etcd/ssl
          name: etcd-certs-0
          readOnly: true
...
      volumes:
      - hostPath:
          path: /etc/ssl/etcd/ssl
          type: DirectoryOrCreate
        name: etcd-certs-0
```

Errors:

```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
request etcd endpoint 'https://etcd.kube-system.svc.cluster.local:2379/version' error, certificate verify failed
```

the certs have no problem.

```bash
[root@ssa3 ~]# curl https://127.0.0.1:2379/version --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/admin-ssa3.pem   --key /etc/ssl/etcd/ssl/admin-ssa3-key.pem
{"etcdserver":"3.3.12","etcdcluster":"3.3.0"}
```

**Comment by zackzhangkai** [comment]
> > ```shell
> > # curl https://127.0.0.1:2379/version --cacert /etc/ssl/etcd/ssl/ca.pem --cert /etc/ssl/etcd/ssl/admin-ssa3.pem   --key /etc/ssl/etcd/ssl/admin-ssa3-key.pem
> > {"etcdserver":"3.3.12","etcdcluster":"3.3.0"}
> > ```
> 
> Since you mentioned that your etcd cluster doesn't enable the mTLS, why your curl call still carries the client cert, key and cacert?

really, I got confused with the mTLS. It's my fault.  By the way, does it has a proposal to support mTLS?

**Comment by zackzhangkai** [comment]
Though I curl with certificate , it does not indicate the communication is mTLS. It's just because of my etcd has enabled tls. I think we get misunderstanding with mTLS.

**Comment by zackzhangkai** [comment]
Got it, Thank you. It is really mtls.

**Comment by tokers** [comment]
@zackzhangkai Unfortunately, APISIX is not capable to use mTLS now, it's in our TODO list.

**Comment by zackzhangkai** [comment]
Thanks a lot.

**Comment by dingwood** [comment]
hope the mtls function  coming soon .....
