### ISSUE TITLE
request help: About current limiting algorithm

### ISSUE THREAD

**Issue by ShenAoScript** [apache/apisix#3602]
### Issue description
About current limiting algorithm
### Environment
* apisix version (cmd: `apisix version`): 2.0+
* OS (cmd: `uname -a`):centos7

Now the plugin "limit-req" algorithm is
` if delay >= 0.001 then
        sleep(delay)
    end`

If I turn it into：
`    if delay >= 0.001 then
       do nothing
    end`

so, the leaky bucket becomes the token bucket ?

**Comment by spacewander** [comment]
No

**Comment by spacewander** [comment]
Please read the definition of these two algorithms:
https://en.wikipedia.org/wiki/Token_bucket
https://en.wikipedia.org/wiki/Leaky_bucket

**Comment by ShenAoScript** [comment]
ok,I've seen people say that on the Internet.and it's puzzles me.
thanks for your ans.
