### ISSUE TITLE
chore: remove 2.3 version of rpm and deb packages 

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3604]
Because the current rpm/deb package depends on `openresty-openssl` library, but `openresty 1.19.*` uses `openresty-openssl111` by default and the currently added dependencies may be wrong.

So I decided to delete the 2.3 version of the rpm and deb packages. After the problem is determined, repackage and upload.

Released link:
https://github.com/apache/apisix/releases/tag/2.3

related issue: https://github.com/apache/apisix/issues/3598

**Comment by membphis** [comment]
ping @spacewander @moonming @tokers @nic-chen

**Comment by tokers** [comment]
Agree +1

**Comment by nic-chen** [comment]
+1

**Comment by spacewander** [comment]
Done
