### ISSUE TITLE
discuss: `batch-processor` should not depend on plugin `prometheus`

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#3610]
### Issue description

[`batch-processor`](https://github.com/apache/apisix/blob/master/apisix/utils/batch-processor.lua#L155) as the underlying lib should not depend on the upper plugin.

```lua
    if not batch_metrics and prometheus.get_prometheus() and self.name
       and self.route_id and self.server_addr then
        batch_metrics = prometheus.get_prometheus():gauge("batch_process_entries",
                                                          "batch process remaining entries",
                                                          {"name", "route_id", "server_addr"})
    end
```
in [batch-processor.lua line 155](https://github.com/apache/apisix/blob/master/apisix/utils/batch-processor.lua#L155)

The code is hierarchical, basic core -> logic package -> plug-in code, must follow this reference logic

Lib `batch-process` can be referenced by any plugin

If plugin prometheus needs to reference `batch-process` in the future, but `batch-process` itself depends on prometheus, then there will be an loop reference here

And this also destroys the positioning of the plugin itself: pluggable

What's your opinion? Thanks.

**Comment by tokers** [comment]
@nic-chen Would you like to paste some code snippets?

**Comment by nic-chen** [comment]
> @nic-chen Would you like to paste some code snippets?

updated. thanks!

**Comment by tokers** [comment]
Got it, should refactor it.

**Comment by spacewander** [comment]
The batch processor depends on prometheus exporter, not the prometheus plugin.
