### ISSUE TITLE
bug: Error will be reported when apisix starts , if which is not installed

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#3611]
### Issue description
If which is not installed, the logic will be wrong and it does not match expectations.

### Environment

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): centos
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.13

### Minimal test code / Steps to reproduce the issue
After APISIX installed, use `apisix start`

get error

![image](https://user-images.githubusercontent.com/4413028/108513442-952d5300-72fd-11eb-8763-6cad434ad00a.png)

**Comment by tokers** [comment]
So we should detect whether the utility `which` exists in the system.

```shell
OR_BIN=$(which openresty || exit 1)
```
