### ISSUE TITLE
request help: logging upstream response data

### ISSUE THREAD

**Issue by Applenice** [apache/apisix#3612]
### Issue description
I have enabled the proxy rewrite plugin and it is currently working fine, but I want to log the responses returned by the upstream service for things like data validation, auditing and so on. I've done some research, but I'm still confused. For example:

https://serverfault.com/questions/361556/is-it-possible-to-log-the-response-data-in-nginx-access-log/598045

How to implement it in APISIX, thanks!

### Environment

* apisix version (cmd: `apisix version`): 2.3
* OS (cmd: `uname -a`): Linux tmp 5.4.0-65-generic #73~18.04.1-Ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): v3.4.13
* apisix-dashboard version, if have: 2.4

**Comment by spacewander** [comment]
It is not supported yet. You can write your own plugin or extend current xxx-logger plugins.

**Comment by Applenice** [comment]
> It is not supported yet. You can write your own plugin or extend current xxx-logger plugins.

Thanks for the reply, the first attempt to write the plugin failed.🙃 I'll go learn the code of xxx-logger.

**Comment by Applenice** [comment]
Also, is it considered to implement this plugin in APISIX in the future?

**Comment by tokers** [comment]
@Applenice Welcome to submit a proposal about this new feature :)

**Comment by Applenice** [comment]
> @Applenice Welcome to submit a proposal about this new feature :)

Thanks for the reply. I would like to save the upstream response data in the specified log file and then parse the log file. But there are several factors to consider, such as
- Upstream response data size, some of which may be very large
- High frequency of requests

**Comment by spacewander** [comment]
Already done.

**Comment by philippem** [comment]
> Already done.

how to use/enable?
