### ISSUE TITLE
feat: Add method filter on consummer-restriction plugin

### ISSUE THREAD

**Issue by jp-gouin** [apache/apisix#3635]
Hi,
I think it could be interesting to add a filter on the method in the consummer-restriction plugin;

With something like : 
```
"consumer-restriction": {
            "whitelist": [
                {
                    "jack1" : ["OPTIONS","GET","POST","DELETE","PATCH","*"]
                }
            ]
        }
```
This feature could be optional and fallback on the current processing.

**Comment by spacewander** [comment]
PR is welcome!

**Comment by jp-gouin** [comment]
Ok sure , i'll work on that
