### ISSUE TITLE
request help: How to modify HMAC_ The format of verification time

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3643]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

in auth authentication plug-in, such as the time format of CST

**Comment by Firstsawyou** [comment]
Judging from the hmac-auth code structure, it should be supported. You can try it with CST time format.

**Comment by Firstsawyou** [comment]
@nic-chen From the hmac-auth code structure, it should be possible to use the CST time format, right?

**Comment by Firstsawyou** [comment]
@nic-chen Please take a look, do you have any ideas?

**Comment by Yangzcy423911** [comment]
example: Tue Feb 23 18:22:17 CST 2021

**Comment by nic-chen** [comment]
@Yangzcy423911  
it doesn't support the format you mentioned. you could customize your time format in:
https://github.com/apache/apisix/blob/master/apisix/plugins/hmac-auth.lua#L295

**Comment by Yangzcy423911** [comment]
Turn on the time check, the request has been failed, the status code is 401

**Comment by Yangzcy423911** [comment]
clock_skew set to 300 ，How to understand the meaning of this field。
After the field is set, the gateway returns 401 all the time, and after closing time verification, the request succeeds. In this case, how to troubleshoot the problem

**Comment by Firstsawyou** [comment]
> clock_skew set to 300 ，How to understand the meaning of this field。
> After the field is set, the gateway returns 401 all the time, and after closing time verification, the request succeeds. In this case, how to troubleshoot the problem

`clock_skew` is the time offset, which means that according to your current request `Date` (GMT), your request is normal within the time of `Date` + 300 seconds, when it exceeds the time of `Date` + 300, your request will fail.

**Comment by Yangzcy423911** [comment]
When the on time offset, the request will always fail, the gateway test time, because the signature string contains time, the request time and the gateway time is not consistent, the resulting signature will be different, the request failure occurs

**Comment by nic-chen** [comment]
> When the on time offset, the request will always fail, the gateway test time, because the signature string contains time, the request time and the gateway time is not consistent, the resulting signature will be different, the request failure occurs

Two solutions:
1. turn it off
2. Keep time consistent

**Comment by Yangzcy423911** [comment]
OK, I Know
