### ISSUE TITLE
request help: potocol support plan

### ISSUE THREAD

**Issue by azura27** [apache/apisix#3646]
### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS (cmd: `uname -a`): 3.10.0-693.21.1.el7.x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.13
* apisix-dashboard version, if have:

Hello, I wanna know If QUIC support in the future feature support list? If in list, wanna discussion and help, Thanks a lot

**Comment by spacewander** [comment]
We need to wait the official OpenResty to support QUIC first.

**Comment by monkeyDluffy6017** [comment]
Please refer to https://github.com/apache/apisix/issues/9752
