### ISSUE TITLE
建议：是不是后续版本可以考虑把插件的优先级集成到统一的配置里去

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#3652]
因为插件一多，当需要新增一个自定义插件的时候需要挨个查看其他的插件文件中的priority以避免重复，体验不是很好

**Comment by StretchV** [comment]
https://github.com/apache/apisix-dashboard/blob/v2.4/docs/FAQ.md#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard

**Comment by moonming** [comment]
Maybe we can automatically generate a priority list of plugins
@Firstsawyou

**Comment by Firstsawyou** [comment]
> Maybe we can automatically generate a priority list of plugins
> @Firstsawyou

Yes, I will try it.
