### ISSUE TITLE
bug: example-plugin 把 control_api 改成api ，访问还是报路由找不到

### ISSUE THREAD

**Issue by mr3chen** [apache/apisix#3655]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. example-plugin 把 control_api 改成api ，访问还是报路由找不到
2.
3.

### What's the expected result?

curl -L -X GET 'http://127.0.0.1:9080/v1/plugin/example-plugin/hello' 不是返回404

**Comment by spacewander** [comment]
example-plugin is disabled by default:
https://github.com/apache/apisix/blob/728df41e1682da8d4cd615a613a938e275a4d085/conf/config-default.yaml#L232

And you use the wrong port for control-api.
https://github.com/apache/apisix/blob/728df41e1682da8d4cd615a613a938e275a4d085/conf/config-default.yaml#L129-L131

It should be 9090.
