### ISSUE TITLE
[discuss]: remove the `location /apisix/dashboard` API interface in the ngx_tpl.lua file

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3662]
### Issue description

Since APISIX and APISIX Dashboard are currently deployed independently of each other, the old `/apisix/dashboard` API interface is still retained in the ngx_tpl.lua file. I think it should be removed.
The reasons are as follows:

1. The `/apisix/dashboard` API interface is useless;
2. When users use the `rpm` package to install APISIX and APISIX Dashboard, there is a directory structure named `dashboard` in the directory structure of APISIX, which is easy for users to misunderstand that they need to use the `/apisix/dashboard` API interface to perform access.

![apisix-dashboard](https://user-images.githubusercontent.com/52862365/109036834-fb9ee080-7704-11eb-853d-1e1c77b382bd.png)

**Comment by spacewander** [comment]
@juzhiyuan 
What about your opinion?

**Comment by juzhiyuan** [comment]
It seems that this location is a historical issue, we could remove it IMO.

**Comment by moonming** [comment]
@Firstsawyou are you fix the rpm package issue？

**Comment by Firstsawyou** [comment]
> @Firstsawyou are you fix the rpm package issue？

No, rpm packages are normal.

**Comment by moonming** [comment]
Doesn't your issue say that there is a problem with the rpm package?

**Comment by Firstsawyou** [comment]
> Doesn't your issue say that there is a problem with the rpm package?

That is the problem of recording user feedback. I tested it later and found that there was no problem. The user's access method is wrong, and I haven't updated it in time.
