### ISSUE TITLE
request help: The performance of wolf RBAC plug-in is too weak. Is there a better plug-in for rbac

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#3670]
### Issue description
wolf-rbac is an authentication and authorization (rbac) plugin
I used it for rbac，but QPS down to 300/s
how to do for rbac without  losing performance
### Environment
* apisix version (cmd: `apisix version`): docker 2.0
* OS (cmd: `uname -a`): centos docker
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.17.8.2

**Comment by Firstsawyou** [comment]
You should provide relevant configuration information and related steps for testing QPS, so that others know what is causing it.

**Comment by cverdela** [comment]
wolf-server runs on server A.
apisix runs on server B with etcd.
all runs in docker.
apisix limit 1 cpu .
i use jmeter with 100 threads
QPS was 3000/s
when i use plugins wolf-rbac， QPS down to 300/s
only add plugins wolf-rbac in /apisix/admin/routes
All of other configurations are default

**Comment by membphis** [comment]
please update your title, make a more meaningful
