### ISSUE TITLE
doc: add `--server` of luarocks for China mainland users

### ISSUE THREAD

**Issue by moonming** [apache/apisix#3671]
# Improve Docs
https://github.com/apache/apisix/blob/master/FAQ.md#why-is-it-that-installing-apisix-dependencies-with-luarocks-causes-timeout-slow-or-unsuccessful-installation

```
luarocks install apisix --server https://luarocks.cn
```
## Please describe which part of docs should be improved or typo fixed

A clear and concise description of what you want and what your use case is.

**Comment by stu01509** [comment]
Hi @moonming 

I want to solve this issue, just only add the command below?
```sh
luarocks install apisix --server https://luarocks.cn
```

**Comment by moonming** [comment]
yes, you are right.

**Comment by stu01509** [comment]
Thanks, I would like to fix this issue.
