### ISSUE TITLE
When multiple plugins are configured in plugin_config, only one takes effect

### ISSUE THREAD

**Issue by nic-chen** [apache/apisix#3674]
When I use Admin API to configure `plugin_config`, it works fine with multiple plugins.

Here is the data in ETCD that configured by Admin API:
```
/apisix/plugin_configs/1
{"create_time":1614250686,"update_time":1614250686,"plugins":{"response-rewrite":{"headers":{"X-VERSION":"1.0"},"body_base64":false},"uri-blocker":{"rejected_code":403,"block_rules":["root.exe","root.m+"]}},"id":"1"}
```

However, this problem occurs when configure `plugin_config` by Manager API.

Here is the data in ETCD that configured by Manager API:
```
/apisix/plugin_configs/1
{"id":"1","create_time":1614250686,"update_time":1614250856,"plugins":{"response-rewrite":{"headers":{"X-VERSION":"1.0"}},"uri-blocker":{"block_rules":["root.exe","root.m+"]}}}
```

At first I thought it was because the Manager API did not automatically fill in the default value(`"rejected_code":403`), but I configured `uri-blocker` separately by Manager API, it worked normally.

```
/apisix/plugin_configs/1
{"id":"1","create_time":1614250686,"update_time":1614251379,"plugins":{"uri-blocker":{"block_rules":["root.exe","root.m+"]}}}
```

please have a look when you have time, thanks. @spacewander 

### Environment

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): macOS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: master

**Comment by spacewander** [comment]
I try it at my side and can't reproduce it. My etcd data:

```
$ etcdctl get /apisix/routes --prefix
/apisix/routes/
init_dir
/apisix/routes/1
{"update_time":1614305330,"plugin_config_id":1,"create_time":1614235098,"priority":0,"uri":"\/test\/*","id":"1","upstream":{"pass_host":"pass","nodes":{"127.0.0.1:23790":1},"scheme":"http","hash_on":"vars","type":"roundrobin"},"status":1}
$ etcdctl get /apisix/plugin_config --prefix
/apisix/plugin_configs/
init_dir
/apisix/plugin_configs/1
{"id":"1","create_time":1614250686,"update_time":1614250856,"plugins":{"response-rewrite":{"headers":{"X-VERSION":"1.0"}},"uri-blocker":{"block_rules":["root.exe","root.m+"]}}}
```

**Comment by spacewander** [comment]
Here is how I check it:
```
 ￥ curl http://127.0.0.1:9080/test/root.exe  -i
HTTP/1.1 403 Forbidden
Date: Fri, 26 Feb 2021 02:09:18 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 150
Connection: keep-alive
Server: APISIX/2.3
X-VERSION: 1.0

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by nic-chen** [comment]
> Here is how I check it:
> 
> ```
> 
>  ￥ curl http://127.0.0.1:9080/test/root.exe  -i
> 
> HTTP/1.1 403 Forbidden
> 
> Date: Fri, 26 Feb 2021 02:09:18 GMT
> 
> Content-Type: text/html; charset=utf-8
> 
> Content-Length: 150
> 
> Connection: keep-alive
> 
> Server: APISIX/2.3
> 
> X-VERSION: 1.0
> 
> 
> 
> <html>
> 
> <head><title>403 Forbidden</title></head>
> 
> <body>
> 
> <center><h1>403 Forbidden</h1></center>
> 
> <hr><center>openresty</center>
> 
> </body>
> 
> </html>
> 
> ```

Thanks, I will check it again.

**Comment by nic-chen** [comment]
@spacewander 
I rechecked it today and found that it was an incremental synchronization problem, not a problem of multiple plugins.

Sorry for misleading.

Please take a look at that pr when you have time, thanks.
