### ISSUE TITLE
bug: proxy-cache plugin has side-effect even if it's not configured in any route

### ISSUE THREAD

**Issue by JanLi-air** [apache/apisix#3677]
### Issue description
If proxy-cache is configured in plugin list, it will override Cache-Control and Expires headers from the upstream.
Problem is that even if proxy-cache is not configured in any route, those headers will still be overridden.
So we have a side effect for proxy-cache.

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS (cmd: `uname -a`): linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. Use the default configuration from apisix
2. Write Cache-Control and Expires headers in upstream
3. Check the response

### What's the actual result? (including assertion message & call stack if applicable)
Cache-Control and Expires headers disappeared

### What's the expected result?
If proxy-cache is not configured for a route, apisix should not rewrite Cache-Control and Expires headers.

**Comment by membphis** [comment]
it is not easy to fix this bug, I think it needs to change the Nginx core.

**Comment by membphis** [comment]
disable `proxy-cache` plugin is a simple way for most users

**Comment by JanLi-air** [comment]
Agree, but proxy-cache might be used in some scenarios. The fix might not be available to all users.

**Comment by spacewander** [comment]
Similar like https://github.com/apache/apisix/issues/3373?

**Comment by JanLi-air** [comment]
> Similar like #3373?

Yes, seems the same

**Comment by spacewander** [comment]
Will you submit a fix? I have already provided a solution in that issue.
