### ISSUE TITLE
request help: error_log has garbled

### ISSUE THREAD

**Issue by thekingofworld** [apache/apisix#3683]
### Issue description
1. error_log has garbled
2. using uninitialized "uuid" variable error
### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.17.8.1

![image](https://user-images.githubusercontent.com/8169665/109254340-ca213480-782c-11eb-89ee-9cc0d92c6642.png)

![image](https://user-images.githubusercontent.com/8169665/109254440-fc329680-782c-11eb-81ab-777e03688dfd.png)

any body can take a look?
thanks a lot.

**Comment by Firstsawyou** [comment]
It is not affected by the warning log, and `using uninitialized` has been fixed, please see here: https://github.com/apache/apisix/pull/3641/files

**Comment by thekingofworld** [comment]
there's another error, why error_log has garbled?

**Comment by Firstsawyou** [comment]
> there's another error, why error_log has garbled?

This is related to your request data.

**Comment by tokers** [comment]
@thekingofworld Seems like some binary protocol frames were sent to the HTTP port.
