### ISSUE TITLE
docs: the prometheus.md grammar improve

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3689]
# Improve Docs

the `prometheus.md` doc is hard to read. We need to improve the grammar of some of its sentence.

E.g:  https://github.com/apache/apisix/pull/3494#discussion_r583421215

**Comment by moonming** [comment]
any update? @Firstsawyou

**Comment by Firstsawyou** [comment]
> any update? @Firstsawyou

There is an update here： https://github.com/apache/apisix/pull/3494
