### ISSUE TITLE
Support for AzureAD/OIDC integration with APISIX

### ISSUE THREAD

**Issue by Bhanuji95** [apache/apisix#3690]
Hello team,

We are trying to integrate our APIs authentication with AzureAD/OIDC using apisix, can you please let us know how we can achieve this?

**Comment by tokers** [comment]
@Bhanuji95 Currently we don't implement it. Would you please to submit a PR to achieve this? Thanks!

**Comment by spacewander** [comment]
What is the difference between the AzureAD/OIDC and the OIDC we currently support? Is there official documentation for AzureAD/OIDC?

**Comment by Bhanuji95** [comment]
Hello @spacewander,

There is no difference between AzureAD and OIDC, also azuread uses oidc authentication mechanism. Let me try the oidc provided by apisix

**Comment by totemofwolf** [comment]
> Hello @spacewander,
> 
> There is no difference between AzureAD and OIDC, also azuread uses oidc authentication mechanism. Let me try the oidc provided by apisix. Thanks

Is this compatible with OpenLDAP?

**Comment by spacewander** [comment]
OpenLDAP is different as it runs LDAP protocol?

**Comment by endersonmenezes** [comment]
> Hello @spacewander,
> 
> There is no difference between AzureAD and OIDC, also azuread uses oidc authentication mechanism. Let me try the oidc provided by apisix. Thanks

Works for you? Because Azure AD doesn't have an introspection endpoint, what did you do to get around that?

**Comment by romainmeunier** [comment]
Any update regarding this ?
