### ISSUE TITLE
[discuss]: enable etcd health check

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#3692]
### Issue description
I saw this issue #3673 and this pr  #3676.
I think it's time to enable the etcd health check feature.
by the way, **etcd's `host` configuration, if it is in the form of `ip:port`, the health check takes effect,** if it is in the form of domain, the health check fails because etcd's node is hidden behind the domain and cannot be distinguished, so use the FQDN of etcd in k8s does not solve the issues #3673.

**Comment by tokers** [comment]
Yes, it just uses the FQDN since the underlying cosocket suite supports to resolve it according to the `resolver` directive in nginx.conf.

We may, resolving the FQDN (and cache it) by ourselves in the level of lua-resty-etcd.

**Comment by spacewander** [comment]
I think we need to resolve it in the APISIX side as lua-resty-etcd knows nothing about the resolver.

**Comment by tzssangglass** [comment]
> I think we need to resolve it in the APISIX side as lua-resty-etcd knows nothing about the resolver.

agree, etcd `host` is meant to be each node of etcd, not a cluster, and using a k8s domain is equivalent to configuring a unique etcd cluster address, which does not match the meaning of `host`, so perhaps we can add an attribute to support etcd cluster address configuration

**Comment by spacewander** [comment]
> using a k8s domain

For this case maybe we can resolve the domain each time before retry?

**Comment by tzssangglass** [comment]
> For this case maybe we can resolve the domain each time before retry?

Maybe we can do it, but I think we can also do without. My point is: if you configure the `domain`, then the component responsible for domain resolution should also provide the ability to health check, and it should always return the `ip` of a healthy instance under that domain.

I'm not sure if this is a correct point, just a perception.

**Comment by spacewander** [comment]
> the component responsible for domain resolution should also provide the ability to health check

I doubt if it is a good idea to combine the health check with domain resolution, as the health check methods are various and can't detect the healthy one immediately.

**Comment by tzssangglass** [comment]
> I doubt if it is a good idea to combine the health check with domain resolution, as the health check methods are various and can't detect the healthy one immediately.

yes, you are right
only when operating etcd do we know if the node is healthy or not

**Comment by Yiyiyimu** [comment]
Hi @tzssangglass are you still working on this 😀

**Comment by tzssangglass** [comment]
> Hi @tzssangglass are you still working on this 😀 I could take care of it if you do not got enough time

okay, I haven't had enough time lately, so leave it to you.

**Comment by spacewander** [comment]
Already done.
