### ISSUE TITLE
bug: k8s下建立的etcd服务地址，apisix无法解析

### ISSUE THREAD

**Issue by w7team** [apache/apisix#3702]
`bash-5.0# curl http://127.0.0.1:9090/v1/server_info`
{"id":"4ea26d5c-1df7-42aa-a7a1-731b15dd9e39","hostname":"apisix-server-7c5fddf5fc-cvjvr","boot_time":1614505444,"etcd_version":"unknown","up_time":154,"last_report_time":-1,"version":"2.3"}

`bash-5.0# curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`
{"error_msg":"etcd.etcd could not be resolved (2: Server failure)"}

`bash-5.0# curl -s http://etcd.etcd:2379/version`
{"etcdserver":"3.4.13","etcdcluster":"3.4.0"}

etcd的服务地址是`http://etcd.etcd:2379`，直接访问没问题，启动apisix也正常，就是使用的时候报解析错误

**Comment by tokers** [comment]
@w7team What's your APISIX version?

**Comment by spacewander** [comment]
It seems you add this domain via /etc/hosts? A regular k8s service address is like `xxxx.svc.cluster.local:2379`.

**Comment by spacewander** [comment]
Closed as lack of response.

**Comment by orange0cat** [comment]
I also had this problem and solved it by configuring etcd srv name like "xxx.ingress-apisix.svc.cluster.local:2379".
