### ISSUE TITLE
update User Wall picture in README

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3708]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, we have more than 40 users who are using Apache APISIX since the last update, it's time to update the User Wall picture in README, anyone would like to have a try on this good first issue?

[1] https://github.com/apache/apisix/blob/master/docs/en/latest/powered-by.md

## Describe the solution you'd like

1. Visit https://github.com/apache/apisix-website/blob/master/website/static/data/showcases.json#L1
2. Collect those users' logo files and combine them into one picture;
3. Update README.md file

**Comment by iamayushdas** [comment]
working on  it!

**Comment by juzhiyuan** [comment]
OK!

**Comment by juzhiyuan** [comment]
You could find their logos here https://apisix.apache.org/

![image](https://user-images.githubusercontent.com/2106987/109462667-d280a600-7a9e-11eb-8b10-f5f4c496c2c9.png)

**Comment by juzhiyuan** [comment]
Not sure if GitHub has some tools like Pictures Wall Auto generator 🤔

**Comment by iamayushdas** [comment]
done!

**Comment by iamayushdas** [comment]
> Not sure if GitHub has some tools like Pictures Wall Auto generator

i am also not aware of any
