### ISSUE TITLE
improve screenshots in docs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3711]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, I noticed that there have some screenshots from the v1 dashboard, does anyone would like to take some screenshots from the v2.x dashboard[2]?

[1] https://apisix.apache.org/docs/apisix/plugins/jwt-auth
[2] https://github.com/apache/apisix-dashboard

**Comment by iamayushdas** [comment]
i am not sure what to do in this actually? where to put the screenshots?
@juzhiyuan

**Comment by juzhiyuan** [comment]
like this: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/key-auth.md

![image](https://user-images.githubusercontent.com/2106987/109592240-e46b5300-7b49-11eb-9777-a4894e84ce5a.png)

This screenshot is out of date, we need to take some new screenshots from http://139.217.190.60/

**Comment by stu01509** [comment]
Hi @iamayushdas 

Are you working on this issue? If not I would like to solve it.

**Comment by iamayushdas** [comment]
> Hi @iamayushdas 
> 
> 
> 
> Are you working on this issue? If not I would like to solve it.

Yes i am

**Comment by iamayushdas** [comment]
http://139.217.190.60/ - link is not loading @juzhiyuan
