### ISSUE TITLE
allow using regex in the redirect plugin

### ISSUE THREAD

**Issue by pengtaochang** [apache/apisix#3722]
### Issue description
I can't find how to config apisix to support regular matching in uri. The nginx configuration is as follows:
```
location ~* /lib/([a-fA-F0-9]+)$ {
    return 301 https://example.com/lib/all/$1;
}
```

### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):ubantu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:2.3

**Comment by Firstsawyou** [comment]
You can use the combination of `uri` and `vars` of APISIX route to achieve regular matching of `uri`.

**Comment by pengtaochang** [comment]
I don’t understand what you mean, you can post a link to the document or some demo, thank you very much！

**Comment by Firstsawyou** [comment]
> I don’t understand what you mean, you can post a link to the document or some demo, thank you very much！

This is an example, you can refer to it:

```
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/lib/*",
    "vars": [
        ["uri","~*","/lib/([a-fA-F0-9]+)$"]
    ],
    "upstream": {
        "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin"
    }
}'
```
You can refer to here for the detailed usage of vars: https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#route

**Comment by pengtaochang** [comment]
I understand the method to match route through vars regular. I still need to know the regualr value so that I redirect to another uri.Could you gave some tips? thank you very much！

**Comment by Firstsawyou** [comment]
> I still need to know the regualr value so that I redirect to another uri.

Try to use it with the `regex_uri` of the `proxy-rewrite` plugin?

**Comment by pengtaochang** [comment]
I have used the proxy-rewrite plugin. It can redirect to right page in apisix and return right html file. But, the client Browser need to redirect to another path so that display correctly.  I have read the doc of response-rewrite, but I still can't find how to get regular value in uri.

**Comment by tokers** [comment]
> I have used the proxy-rewrite plugin. It can redirect to right page in apisix and return right html file. But, the client Browser need to redirect to another path so that display correctly. I have read the doc of response-rewrite, but I still can't find how to get regular value in uri.

That's not rewrite, that's redirect.

**Comment by pengtaochang** [comment]
Yes, that's redirect with uri matching  parameters. I also read the doc of redirect. It doesn't look like it's supported

**Comment by pengtaochang** [comment]
This is a common feature and hopefully can be supported later

**Comment by pengtaochang** [comment]
Now, I have to change the code of ngx_tpl.lua.

**Comment by nanamikon** [comment]
I have the same issue，  we need the redirect plugin to support regex，  maybe I can submit a pull request ， add a new param called regex_uri  for this issue

**Comment by Firstsawyou** [comment]
> I have the same issue， we need the redirect plugin to support regex， maybe I can submit a pull request ， add a new param called regex_uri for this issue

Nice, looking forward to your PR.

**Comment by nanamikon** [comment]
I have done it
