### ISSUE TITLE
[Discuss] standardize release guide & branch/tag relations

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#3726]
Currently in apisix/apisix-dashboard/apisix-ingress-controller, we have three different types of branch/tag naming format. Let's say for version 1.0:

| repo               | branch | tag   | notes                               |
| ------------------ | ------ | ----- | ----------------------------------- |
| apisix             | v1.0   | 1.0   | tags before 1.0 are in format `1.0` |
| dashboard          | v1.0   | v1.0  | branch and tag name is the same     |
| ingress-controller | v1.0.0 | 1.0.0 |                                     |

There are three main problems for releasing:

1. Since we don't maintain LTS version, we could directly remove all branches that have been released. 
When at release window, maintainers are suggested to use the format `release/1.0` to create release branch and trigger corresponding release Actions. The reason for using `release/1.0` is to avoid trigger release Actions in branch like `verbose` since we tell the release branch by its prefix.
2. Since all releases and related tools are based on tags, we have no choices but to keep the different format of tags in different repos, which the universal tools should adapt to. A suggestion is we should define a new tag format rule for future projects related to apisix, so we won't deal with more kinds of formats 🤣 
3. Currently in apisix, we kind of add tag/make release on random commit during the release. 
    - 2.3 tag on the last commit before merging some master commits in release PR. [tag](https://github.com/apache/apisix/commit/63f779aeae7a4cfdc3baa5c6dad955ef139719f8), [PR](https://github.com/apache/apisix/pull/3466)
    - 2.2 tag on the last commit of the release PR. [tag](https://github.com/apache/apisix/commit/e8dcf3793ca40b30047406ac51a79a500356f67b), [PR](https://github.com/apache/apisix/pull/3168)
    - 2.1 tag on the first (force-pushed) commit of the PR. [tag](https://github.com/apache/apisix/commit/c0f3f73842ca64b92c41c59352d3f9b7969ca738), [PR](https://github.com/apache/apisix/pull/2887)
    - 1.5 tag on the first commit of old release branch but not on release PR. [tag](https://github.com/apache/apisix/commit/6c5b52e93ea522009355643feb9d8c5a84e4baf4), [PR](https://github.com/apache/apisix/pull/1965)

    Some references:
    - Kong tag on the last commit in release PR, see [tag](https://github.com/kong/kong/tree/2.3.2)
    - Envoy tag on the release PR, see [tag](https://github.com/envoyproxy/envoy/tree/v1.17.0)
    - Skywalking tag on the last commit before new change for next version the release PR, see [tag](https://github.com/apache/skywalking/tree/v8.3.0)
    - Kubernetes tag directly on release branch, and retag for each minor version, see [tag](https://github.com/kubernetes/kubernetes/commits/release-1.20)

    I think it might be better if we tag the release PR commit, in another word we add tag right after the release PR got merged, so we won't miss any commits. If something is missing and we need another round of voting, we create another PR on the original branch. After the vote passed and new release got published, we then delete the release branch. 

TODO:

- [ ]  Change release guide on apisix website, so new release could follow the new pattern.
- [ ]  Delete branches. Change release guide so maintainers need to delete branch when the release got ended.

**Comment by juzhiyuan** [comment]
Hi @imjoey @membphis @pahud @tokers, we are reviewing the release process, please take a look at this issue when you have time :)

**Comment by tokers** [comment]
Personally, I prefer the `release/` branch, it has significant difference with tag, while `va.b.c` is more confused.

**Comment by tokers** [comment]
I think it's a clear way, agree it + 1.

**Comment by starsz** [comment]
```
Delete branches. Change release guide so maintainers need to delete branch when the release got ended.
```
Is it necessary？ Kong, Envoy, Kubernetes keep the branch and Skywalking delete it.

**Comment by Yiyiyimu** [comment]
> Is it necessary？ Kong, Envoy, Kubernetes keep the branch and Skywalking delete it.
The reason they keep the branches is they still maintain the branches, cherry-pick/backport the bugfix to the release branches. While we do not, like what skywalking does.  And I think the reason we choose this is kind of since the Apache release process is more strict 😬

**Comment by starsz** [comment]
> > Is it necessary？ Kong, Envoy, Kubernetes keep the branch and Skywalking delete it.
> 
> The reason they keep the branches is they still maintain the branches, cherry-pick/backport the bugfix to the release branches. While we do not, like what skywalking does. And I think the reason we choose this is kind of since the Apache release process is more strict 😬

Got it.Thank you for your explanation 😄.
Agree +1.

**Comment by imjoey** [comment]
@Yiyiyimu thank you very much for this awesome proposal.

Personally, I would prefer:

- `release/1.0` is better than current `1.0` as the release branch name
- agreed with @Yiyiyimu that tag the release on the release PR

Any feedback is welcome.

> The reason they keep the branches is they still maintain the branches, cherry-pick/backport the bugfix to the release branches. While we do not, like what skywalking does. And I think the reason we choose this is kind of since the Apache release process is more strict 😬

I also got confused before, thanks for the explanations. Thanks.

**Comment by juzhiyuan** [comment]
Hi, any conclusion here?

**Comment by Yiyiyimu** [comment]
> Hi, any conclusion here? 

Hi I think I could follow the proposal and try to update the release guide this weekend~

**Comment by juzhiyuan** [comment]
got it~

**Comment by juzhiyuan** [comment]
any update here?

cc @spacewander @imjoey @membphis @liuxiran to check this solution, thanks!

**Comment by membphis** [comment]
the new way is better than before. 
We can follow @Yiyiyimu 's suggestion +1

**Comment by Yiyiyimu** [comment]
Hi @spacewander any reason to close it ( besides I forgot to update 🤦

**Comment by spacewander** [comment]
We already did it.

**Comment by Yiyiyimu** [comment]
> We already did it.

I didn't get it, the release guide on website seems not changed

**Comment by spacewander** [comment]
What about opening an issue to apisix-website? At least the APISIX itself doesn't have this problem.

**Comment by Yiyiyimu** [comment]
Got it.
