### ISSUE TITLE
docs: invalid link to CHANGELOG

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3728]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, I just noticed there has a broken link to CHANGELOG.

## Describe the solution you'd like

1. visit https://github.com/apache/apisix/blob/master/docs/en/latest/config.json#L158
2. use the correct link `https://github.com/apache/apisix/blob/master/CHANGELOG.md`

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by juzhiyuan** [comment]
Hi, please resolve other issues first 😂

**Comment by sukhpreet-singh1** [comment]
can you please assign me this issue.

**Comment by juzhiyuan** [comment]
Hi @sukhpreet-singh1, this one is resolved by @stu01509 :) you could find more good first issue here 😊
