### ISSUE TITLE
docs: invalid link to CODE_STYLE #3728

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3729]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, I just noticed there has a broken link to CODE_STYLE.

## Describe the solution you'd like

1. visit https://github.com/apache/apisix/blob/master/docs/en/latest/config.json#L145
2. use the correct link https://github.com/apache/apisix/blob/master/CODE_STYLE.md

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by juzhiyuan** [comment]
Hi, please resolve other issues first 😂

**Comment by sukhpreet-singh1** [comment]
can you please assign me this?

**Comment by juzhiyuan** [comment]
Hi, this one is taken by others. You could resolve other issues :)

**Comment by sukhpreet-singh1** [comment]
Who had taken this?
