### ISSUE TITLE
docs: use markdown way to import images

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3730]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, when visiting https://apisix.apache.org/docs/apisix/architecture-design , I noticed that there have some broken images 🤔 After @qier222 's search, he found that that's due to in the original markdown file, it's using `<img src="xxx" />` to import images.

## Describe the solution you'd like

1.  visit https://github.com/apache/apisix/tree/master/docs/en/latest and find the related markdown files.
2. we need to use the `![description](src)` way to import pictures.

![image](https://user-images.githubusercontent.com/2106987/109628445-b7389800-7b7d-11eb-9459-8e58f4fec452.png)

![image](https://user-images.githubusercontent.com/2106987/109628458-bb64b580-7b7d-11eb-9a88-417dc3219b51.png)

**Comment by stu01509** [comment]
Please assign this issue to me.

**Comment by juzhiyuan** [comment]
ok!

**Comment by stu01509** [comment]
Hi @juzhiyuan 

I found these pictures have the width and height property, If we change to the markdown syntax their height and width will be change, so should I convert it?

**Comment by juzhiyuan** [comment]
It's ok to have no dimension IMO, I would recommend users visit them in doc site :)

What's your opinion @spacewander @imjoey

**Comment by imjoey** [comment]
> It's ok to have no dimension IMO, I would recommend users visit them in doc site :)
> 
> What's your opinion @spacewander @imjoey

@juzhiyuan +1 for no dimension. Probably we care more about the content than the style in markdown. 😄

**Comment by soulsoul** [comment]
maybe we should change the regex expression of replacement .  just repalce the url is OK.

**Comment by qier222** [comment]
> maybe we should change the regex expression of replacement . just repalce the url is OK.

Agree
