### ISSUE TITLE
bug: plugin ip-restriction cannot work on HTTPS

### ISSUE THREAD

**Issue by chenyicai** [apache/apisix#3732]
### Issue description
When i enabled plugin ip-restriction ,config blacklist
Visit http domain(eg:http://www.xxx.com) name response 
{"message":"Your IP address is not allowed"}

But when i visit https://www.xxx.com it works well , my ip is allowed

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): Linux ali_prod_apisix_srv01 4.4.0-201-generic #233-Ubuntu SMP Thu Jan 14 06:10:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  openresty/1.19.3.1

### What's the expected result?
when i visit https://www.xxx.com  , it response "{"message":"Your IP address is not allowed"}"

**Comment by Firstsawyou** [comment]
Do both `http://www.xxx.com` and `https://www.xxx.com` resolve to the same IP address?

**Comment by chenyicai** [comment]
yes !They resolve to the same IP address.

**Comment by chenyicai** [comment]
I only have one A record , the ssl certificate used in alibaba cloud slb

**Comment by tokers** [comment]
Could you give more details about your configuration and request/response context.

**Comment by membphis** [comment]
ping @chenyicai

**Comment by spacewander** [comment]
Closed as lack of response.
