### ISSUE TITLE
request help: error occured at start-up time of apisix(installed mode: compiling) 

### ISSUE THREAD

**Issue by libeio** [apache/apisix#3752]
### Issue description
error occured at start-up time of apisix(the apisix and its dependency, like openresty, openssl, zlib, installed by compiling) 

### Environment

* apisix version (v2.3):
* OS (kernel: 4.18.0-240.el8.x86_64   release: CentOS Linux release 8.3.2011):
* OpenResty / Nginx version (v19.3.1):
* etcd version, if have (etcd-v3.4.13-linux-amd64):
* lua(5.1.5)
* openssl(1.1.0l)
* zlib(1.2.11)
* pcre(8.44)
* luarocks(3.5.0)
* apisix-dashboard version, if have:

### Procdure - Install OpenResty

在配置时指定各依赖对应的源码文件，具体编译及安装方式为:
```sh
  ./configure --prefix=/usr/local/openresty --with-zlib=/usr/local/src/zlib-1.2.11 --with-pcre=/usr/local/src/pcre-8.44 --with-openssl=/usr/local/src/openssl-1.1.0l --with-http_stub_status_module --with-http_ssl_module --with-http_realip_module --with-http_v2_module
  gmake
  gmake install
```

### Procdure - Use etcd

这里使用官方编译好的二进制包。

### Procdure - Deploy apisix

链接命令:
```sh
    ln -s /usr/local/openresty/bin/openresty /usr/bin/openresty
    ln -s /usr/local/openresty/bin/resty /usr/bin/resty
```

在部署 `apisix` 时，会用到 `openssl` 和 `zlib`，`apisix` 要求将其放置到 `/usr/local/openresty/` 目录下。这里采用链接方式，链接路径分别为 `/usr/local/openresty/openssl` 和 `/usr/local/openresty/zlib` ，如下:
```sh
  ln -s /usr/local/openssl /usr/local/openresty/openssl
  ln -s /usr/local/zlib /usr/local/openresty/zlib
```

完成之后，`/usr/local/openresty` 的一级目录树结构如下:
```sh
  ├── bin
  ├── COPYRIGHT
  ├── luajit
  ├── lualib
  ├── nginx
  ├── openssl -> /usr/local/openssl
  ├── pod
  ├── resty.index
  ├── site
  └── zlib -> /usr/local/zlib
```

对 `apisix` 的部署。部署过程如下:
进入 `apisix` 的顶层目录中执行如下命令:
```sh
  make deps
```

另附: `/usr/local/openssl` 的一级目录树结构:
```sh
  ├── bin
  │   ├── c_rehash
  │   └── openssl
  ├── include
  │   └── openssl
  ├── lib
  │   ├── engines-1.1
  │   ├── libcrypto.a
  │   ├── libcrypto.so -> libcrypto.so.1.1
  │   ├── libcrypto.so.1.1
  │   ├── libssl.a
  │   ├── libssl.so -> libssl.so.1.1
  │   ├── libssl.so.1.1
  │   └── pkgconfig
  ├── share
  │   ├── doc
  │   └── man
  └── ssl
      ├── certs
      ├── misc
      ├── openssl.cnf
      ├── openssl.cnf.dist
      └── private
```

### Procdure - Start apisix
在一个 shell 会话中执行:
```sh
  ./etcd
```
在另一个 shell 会话中执行:
```sh
  ./bin/apisix start
```
报错:
```sh
  /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
  nginx: [error] init_by_lua error: /home/dev/apisix-2.3/apisix/init.lua:68: pcre jit stack allocation failed
  stack traceback:
          [C]: in function 'error'
          /usr/local/openresty/lualib/ngx/re.lua:311: in function 'opt'
          /home/dev/apisix-2.3/apisix/init.lua:68: in function 'http_init'
          init_by_lua:9: in main chunk
```

**Comment by spacewander** [comment]
The error message shows that it failed to mmap enough space for jit stack.

Does it happen each time? Does it happen in other machines?

**Comment by libeio** [comment]
### Procdure

> 
> 
> The error message shows that it failed to mmap enough space for jit stack.
> 
> Does it happen each time? Does it happen in other machines?

Apisix run in the machine CentOS 8.1 and this error occured every time。

**Comment by spacewander** [comment]
I just try it in the CentOS 8, with the official OpenResty rpm and https://github.com/apache/apisix/releases/download/2.3/apisix-2.3-0.x86_64.rpm, everything works as expected.

Maybe you can use gdb to set up a breakpoint at pcre_jit_stack_alloc to see what happened.

**Comment by libeio** [comment]
> 
> 
> The error message shows that it failed to mmap enough space for jit stack.
> 
> Does it happen each time? Does it happen in other machines?

I try same way in ubuntu 16.04 macheine, report the same error in the CentOS 8.1 I tested.

**Comment by libeio** [comment]
> 
> 
> I just try it in the CentOS 8, with the official OpenResty rpm and https://github.com/apache/apisix/releases/download/2.3/apisix-2.3-0.x86_64.rpm, everything works as expected.
> 
> Maybe you can use gdb to set up a breakpoint at pcre_jit_stack_alloc to see what happened.

I be poor at gdbing lua because rarely used this language.╮(╯▽╰)╭

**Comment by libeio** [comment]
the following content below is all the record about how I compiled and installed. You can try it in yr machine in the same way.

### downlinks
[lua5.1.5](http://www.lua.org/ftp/lua-5.1.5.tar.gz)
[luarocks](http://luarocks.github.io/luarocks/releases/luarocks-3.5.0.tar.gz)
[pcre](ftp://ftp.pcre.org/pub/pcre/pcre-8.44.tar.gz)
[zlib](http://zlib.net/zlib-1.2.11.tar.gz)
[openssl](https://github.com/openssl/openssl/archive/OpenSSL_1_1_0l.zip)
rename OpenSSL_1_1_0l to openssl-1.1.0l after unzip it

### Lua

Lua 当前常用版本有 5.1, 5.2, 5.3 三个，目前 `apisix` 使用 5.1 版本。

- 依赖包安装

  对于 redhat 系列:
  ```sh
    yum install readline-devel
  ```
  
  对于 debian 系列:
  ```sh
    apt-get install libreadline-dev
  ```

- 解压 tarball 进入顶层目录下
  ```sh
    tar -zxvf lua-5.1.5.tar.gz
    cd lua-5.1.5
  ```

- 编译、测试与安装
  ```sh
    make linux
    make test
    make install
  ```
  默认安装到 `/usr/local/bin/` 目录下。


### LuaRocks

[参考](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix)

`LuaRocks` 是 Lua 包管理工具，必须指定 Lua 安装路径进行安装(缺省会去 `/usr/local/bin` 目录下寻找)。

作为包管理工具，当然也可以使用 `yum` 或 `apt-get` 进行安装，但有些机器版本的源中并没有提供该安装包。

此外，在某些平台上，通过包管理工具安装 `LuaRocks` 会导致 Lua 被升级为 Lua 5.3，所以`apisix`官方也建议通过源代码的方式安装 `LuaRocks`。

所以这里以编译安装示例。

- 解压
  ```sh
    tar -zxvf luarocks-3.5.0.tar.gz 
    cd luarocks-3.5.0
  ```

- 配置、编译与安装
  ```sh
    ./configure --prefix=/usr/local/luarocks --with-lua-include=/usr/local/include
    make
    make install
  ```

- 链接到搜索路径
  ```sh
    ln -s /usr/local/luarocks/bin/luarocks /usr/bin
  ```


### OpenResty

`apisix` 依赖于 `OpenResty`，而 `OpenResty` 又依赖其他模块，不过很多模块在 `OpenResty` 包内均有内置，除了 `openssl`,`zlib` 和 `pcre`。

所以在安装 `OpenResty` 时，需要指定上述三个依赖包的位置。

方法一: `OpenResty` 的依赖可以通过 yum 包管理方式安装，参考[这里](60_openresty-openssl-devel.md)。

方法二: 这里采用编译安装，依赖包版本如下:

|  依赖包  |  版本  |
|:--------|:-------|
| openssl | 1.1.0l |
| zlib    | 1.2.11 |
| PCRE    | 8.44   |

采用编译安装时，不需要将 `openssl`,`zlib` 和 `PCRE` 各自独立编译完成之后再通过 `OpenResty` 指定依赖头文件或库文件路径。

`OpenResty` 采用了一种更为简单的编译方式，在配置时只需要指定各依赖对应的源码文件即可。具体编译安装方式如下:

```sh
  ./configure --prefix=/usr/local/openresty --with-zlib=/usr/local/src/zlib-1.2.11 --with-pcre=/usr/local/src/pcre-8.44 --with-openssl=/usr/local/src/openssl-1.1.0l --with-http_stub_status_module --with-http_ssl_module --with-http_realip_module --with-http_v2_module
  gmake
  gmake install
```
在 ubuntu 系统下会提示采用 `make` 和 `make install` 方式进行编译安装。


### etcd

[下载查找](https://github.com/etcd-io/etcd/releases/download/v3.4.13/etcd-v3.4.13-linux-amd64.tar.gz)

版本: v3.4.13

`etcd` 使用 golang 编写，为了避免编译不规范，这里直接使用编译好的二进制包。


### apisix

在部署 `apisix` 之前，还需要做两件事情，链接命令与放置 `openssl` 库文件。

1.链接命令
  ```sh
    ln -s /usr/local/openresty/bin/openresty /usr/bin/openresty
    ln -s /usr/local/openresty/bin/resty /usr/bin/resty
  ```

2.放置库文件

在部署 `apisix` 时，也会用到 `openssl` 和 `zlib`，与 `OpenResty` 不同，`apisix` 要求 `openssl` 和 `zlib` 编译成开发头文件和库的形式，链接路径分别为 `/usr/local/openresty/openssl` 和 `/usr/local/openresty/zlib` 。

这里将编译完成之后的 `/usr/local/openssl` 和 `/usr/local/zlib` 分别链接到对应路径下下:
```sh
  ln -s /usr/local/openssl /usr/local/openresty/openssl
  ln -s /usr/local/zlib /usr/local/openresty/zlib
```

附:[openssl和zlib编译安装](61_openssl_zlib_compiled.md)

附: `/usr/local/openssl` 的二级目录树结构为:
```sh
  ├── bin
  │   ├── c_rehash
  │   └── openssl
  ├── include
  │   └── openssl
  ├── lib
  │   ├── engines-1.1
  │   ├── libcrypto.a
  │   ├── libcrypto.so -> libcrypto.so.1.1
  │   ├── libcrypto.so.1.1
  │   ├── libssl.a
  │   ├── libssl.so -> libssl.so.1.1
  │   ├── libssl.so.1.1
  │   └── pkgconfig
  ├── share
  │   ├── doc
  │   └── man
  └── ssl
      ├── certs
      ├── misc
      ├── openssl.cnf
      ├── openssl.cnf.dist
      └── private
```

完成之后，`/usr/local/openresty` 的一级目录树结构如下:
```sh
  ├── bin
  ├── COPYRIGHT
  ├── luajit
  ├── lualib
  ├── nginx
  ├── openssl -> /usr/local/openssl
  ├── pod
  ├── resty.index
  ├── site
  └── zlib -> /usr/local/zlib
```

至此，就可以进行对 `apisix` 的部署了。部署过程如下:

进入 `apisix` 的顶层目录中执行如下命令:
```sh
  make deps
```

**Comment by spacewander** [comment]
My bad! I didn't notice the compile option. You need to add `--with-pcre-jit` for the `./configure`.

**Comment by libeio** [comment]
> 
> 
> My bad! I didn't notice the compile option. You need to add `--with-pcre-jit` for the `./configure`.

add option `--with-pcre-jit` when `./configure` the OpenResty?

**Comment by spacewander** [comment]
Yes.

**Comment by szqm123** [comment]
我也遇到类似问题，解决方法如下（不要单独安装pcre和Openssl_1_1_1-statble）：
首先下载到github上下载pcre和openssl_1_1_1-stable的源码包并解压到/usr/local，然后执行如下命令进行安装：
./configure --with-pcre=/usr/local/pcre-master --with-openssl=/usr/local/openssl-OpenSSL_1_1_1-stable --with-http_stub_status_module --with-http_ssl_module --with-http_realip_module --with-http_v2_module -with-pcre-jit
gmake
gmake install

**Comment by javsalgar** [comment]
Found same issue with Photon 3.0, which is using PCRE 8.44. Compiled in other distros like Centos 7, Ubuntu 18.04 or Debian 11 without issues.
