### ISSUE TITLE
feat: support the configuration of keepalive related parameters in config.yaml

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3760]
### Issue description

Currently we do not support the `upstream` custom configuration of `keepalive` related parameters in nginx.conf, because these parameters are fixed.

 E.g:.

```
upstream apisix_backend {
        server 0.0.0.1;
        balancer_by_lua_block {
            apisix.http_balancer_phase()
        }

        keepalive 320;
    }
```

I think the `keepalive` parameter should be a customizable configuration.

**Comment by tokers** [comment]
It may not support per upstream, but supports to customize in config.y'all.

**Comment by membphis** [comment]
We should support specifying more directive values: 

http://nginx.org/en/docs/http/ngx_http_upstream_module.html

![image](https://user-images.githubusercontent.com/6814606/110435951-9973b180-80ee-11eb-9923-908e2c2a8a18.png)

**Comment by Firstsawyou** [comment]
Assigned to me.
