### ISSUE TITLE
docs: fix powered-by link

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3767]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, I noticed that this `powered-by.md` is missing 🤔 for this file is under the root directory.

![image](https://user-images.githubusercontent.com/2106987/110125384-35a36d00-7dfe-11eb-9c1a-26d7e45426b8.png)

## Describe the solution you'd like

1. Visit https://github.com/apache/apisix/edit/master/README.md

![image](https://user-images.githubusercontent.com/2106987/110129027-67b6ce00-7e02-11eb-8363-333bdeeff88a.png)

2. Use `[Powered By](powered-by.md)` instead.

**Comment by stu01509** [comment]
I will fix it

**Comment by stu01509** [comment]
Hi @juzhiyuan 

Seems like this issue has been solved, we can close it.

**Comment by juzhiyuan** [comment]
Ya
