### ISSUE TITLE
support one-line installs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3771]
# Feature Request

## Please describe which part of docs should be improved or typo fixed

Hi, I noticed that the [GetEnvoy](https://www.getenvoy.io/) supports one-line installs by using the following commands:

```sh
$ curl -L https://getenvoy.io/cli | bash -s -- -b /usr/local/bin
$ getenvoy run standard:1.17.1 -- --version
```

It not only supports many platforms but also reduces users' time to dig out how to build this software.

From Apache APISIX's Get Started part[1], it doesn't support this way yet AFAIK, could anyone help to implement this feature?

[1] https://github.com/apache/apisix#get-started

**Comment by spacewander** [comment]
Already supported.
