### ISSUE TITLE
request help: how to config "location /m { alias /mnt/www/saas-h5/; index index.html; }"

### ISSUE THREAD

**Issue by robingong** [apache/apisix#3772]
### Issue description
我们想在apisix的配置文件里实现（参照原生ngin):
'''
http{
...
  server{
...
		location /m {
			alias /mnt/www/saas-h5/;
			index index.html;
		}
...
'''

那么，在config-default.yaml里，该怎么配置呢？

### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):ubuntu18
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md
You can add it into
```
# put this in config.yaml:
nginx_config:
  http_server_configuration_snippet：
  ...
```
