### ISSUE TITLE
plugin server-info will write data to etcd

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3775]
# Question

## Please describe which part of docs should be improved or typo fixed

Hi, the Apache APISIX implements the `server-info` plugin in #2926 #2821, and this plugin will set data to `etcd` here[1] 🤔 this will lead to conflicts with the original design: **DP will only READ data from etcd.**

![](https://github.com/apache/apisix/raw/master/docs/assets/images/apisix.png)

I'm not sure if we need to have some changes to this plugin 🤔 

[1] https://github.com/apache/apisix/pull/2926/files#diff-874bdf83da087cde5a431f91ce48ffc6bc042c5b3a64c6e21b1ca799b9261f66R137

**Comment by membphis** [comment]
DP is read-only to etcd data, making it easier to control security.
I suggest keeping it read-only for DP.

**Comment by tokers** [comment]
It's difficult to do ti without introducing any other components.

**Comment by membphis** [comment]
I think we should disable this feature by default, keep `read-only for DP`

**Comment by membphis** [comment]
@nic-chen Do you have any news about this issue?

**Comment by nic-chen** [comment]
> @nic-chen Do you have any news about this issue?

We're using keepalive instead of always updating, but it's still writing, not read-only: https://github.com/apache/apisix/pull/6202
