### ISSUE TITLE
request help:  plz ，i wanne konw why this result linear .can u offer more detail configuration parameter？

### ISSUE THREAD

**Issue by No-sleeping** [apache/apisix#3777]
### Issue description

想问下，这里是怎么能够达到线性得。
能提供下这里执行得wrk命令么，
请问下这这里压测得时用得是长连接还是短链接？

### Environment
![image](https://user-images.githubusercontent.com/29038574/110284905-6ca39980-801d-11eb-86a3-2e2915ee7578.png)

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Please read the English doc: https://github.com/apache/apisix/blob/master/docs/en/latest/benchmark.md. The Chinese doc is not up-to-date.

And it is not linear, see the x-axis.

**Comment by No-sleeping** [comment]
这中文文档和这英文文档 不是一样的么？

**Comment by spacewander** [comment]
https://github.com/apache/apisix/blob/master/docs/en/latest/benchmark.md
> And if you want to run the benchmark test in your machine, you should run another Nginx to listen 80 port

You can start reading from this.
