### ISSUE TITLE
bug: CROS

### ISSUE THREAD

**Issue by miaoyb** [apache/apisix#3778]
### Issue description
跨域插件bug，开启全局跨域之后再关闭全局跨域插件，跨域依然生效
### Environment

* apisix version (cmd: `apisix version`): v2.3
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. 开启全局跨域
2.前后端分离项目可以正常从前端跨域访问后端
3.关闭全局跨域，前端依然可以跨域访问后端。即使清空etcd再次建立新的route，依然可以成功

etcd info

plugins json
```json
[{"name":"api-breaker"},{"name":"authz-keycloak"},{"name":"basic-auth"},{"name":"batch-requests"},{"name":"consumer-restriction"},{"name":"cors"},{"name":"echo"},{"name":"fault-injection"},{"name":"grpc-transcode"},{"name":"hmac-auth"},{"name":"http-logger"},{"name":"ip-restriction"},{"name":"jwt-auth"},{"name":"kafka-logger"},{"name":"key-auth"},{"name":"limit-conn"},{"name":"limit-count"},{"name":"limit-req"},{"name":"openid-connect"},{"name":"prometheus"},{"name":"proxy-cache"},{"name":"proxy-mirror"},{"name":"proxy-rewrite"},{"name":"redirect"},{"name":"referer-restriction"},{"name":"request-id"},{"name":"request-validation"},{"name":"response-rewrite"},{"name":"serverless-post-function"},{"name":"serverless-pre-function"},{"name":"sls-logger"},{"name":"syslog"},{"name":"tcp-logger"},{"name":"udp-logger"},{"name":"uri-blocker"},{"name":"wolf-rbac"},{"name":"zipkin"},{"name":"server-info"},{"name":"traffic-split"},{"stream":true,"name":"mqtt-proxy"}]
```

route json
```json
{"create_time":1615188897,"status":1,"upstream_id":"abc-test","update_time":1615188897,"priority":0,"name":"abc-test","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"uris":["\/*"],"vars":{},"plugins":{"redirect":{"ret_code":302,"http_to_https":true}},"hosts":["abc-test.test.cn"]}
```

global rules json
```json
{"id":"1","create_time":1615193846,"update_time":1615193846,"plugins":{"request-id":{"disable":false}}}
```

**Comment by Firstsawyou** [comment]
You should provide reproducible use cases or related etcd configuration information.

**Comment by miaoyb** [comment]
> ### Issue description
> 跨域插件bug，开启全局跨域之后再关闭全局跨域插件，跨域依然生效
> 
> ### Environment
> * apisix version (cmd: `apisix version`): v2.3
> * OS (cmd: `uname -a`):
> * OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
> * etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
> * apisix-dashboard version, if have:
> 
> ### Minimal test code / Steps to reproduce the issue
> 1. 开启全局跨域
>    2.前后端分离项目可以正常从前端跨域访问后端
>    3.关闭全局跨域，前端依然可以跨域访问后端。即使清空etcd再次建立新的route，依然可以成功
> 
> etcd info
> 
> ```json
> [{"name":"api-breaker"},{"name":"authz-keycloak"},{"name":"basic-auth"},{"name":"batch-requests"},{"name":"consumer-restriction"},{"name":"cors"},{"name":"echo"},{"name":"fault-injection"},{"name":"grpc-transcode"},{"name":"hmac-auth"},{"name":"http-logger"},{"name":"ip-restriction"},{"name":"jwt-auth"},{"name":"kafka-logger"},{"name":"key-auth"},{"name":"limit-conn"},{"name":"limit-count"},{"name":"limit-req"},{"name":"openid-connect"},{"name":"prometheus"},{"name":"proxy-cache"},{"name":"proxy-mirror"},{"name":"proxy-rewrite"},{"name":"redirect"},{"name":"referer-restriction"},{"name":"request-id"},{"name":"request-validation"},{"name":"response-rewrite"},{"name":"serverless-post-function"},{"name":"serverless-pre-function"},{"name":"sls-logger"},{"name":"syslog"},{"name":"tcp-logger"},{"name":"udp-logger"},{"name":"uri-blocker"},{"name":"wolf-rbac"},{"name":"zipkin"},{"name":"server-info"},{"name":"traffic-split"},{"stream":true,"name":"mqtt-proxy"}]
> ```
> 
> ```json
> {"create_time":1615188897,"status":1,"upstream_id":"abc-test","update_time":1615188897,"priority":0,"name":"abc-test","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"uris":["\/*"],"vars":{},"plugins":{"redirect":{"ret_code":302,"http_to_https":true}},"hosts":["abc-test.test.cn"]}
> ```
> 
> ### What's the actual result? (including assertion message & call stack if applicable)
> ### What's the expected result?



> You should provide reproducible use cases or related etcd configuration information.

The etcd configuration has been added.

**Comment by moonming** [comment]
@Firstsawyou

**Comment by Firstsawyou** [comment]
> @Firstsawyou

I will reproduce it locally later.

**Comment by Firstsawyou** [comment]
I tried to enable the cors plugin globally, and the test seems to be normal.

You should provide detailed steps to reproduce the problem.

1. Enable the global cors plugin

```shell
$ curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>    "plugins": {
>         "cors": {
>             "allow_methods":"GET,POST"
>         }
>     }
> }'
{"node":{"value":{"id":"1","plugins":{"cors":{"max_age":5,"allow_methods":"GET,POST","expose_headers":"*","allow_headers":"*","allow_credential":false,"allow_origins":"*"}},"update_time":1615448097,"create_time":1615447419},"key":"\/apisix\/global_rules\/1"},"action":"set"}
```

2、Add  route

```shell
$ curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/hello",
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "127.0.0.1:1980": 1
>         }
>     }
> }'
{"node":{"value":{"update_time":1615448108,"uri":"\/hello","priority":0,"upstream":{"nodes":{"127.0.0.1:1980":1},"pass_host":"pass","type":"roundrobin","hash_on":"vars","scheme":"http"},"create_time":1615448108,"id":"1","status":1},"key":"\/apisix\/routes\/1"},"action":"set"}
```

3、Test the plugin (with a header related to `CORS` in the response headers)

```shell
$ curl http://127.0.0.1:9080/hello -v
* About to connect() to 127.0.0.1 port 9080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET /hello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Thu, 11 Mar 2021 07:35:37 GMT
< Server: APISIX/2.3
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: GET,POST
< Access-Control-Max-Age: 5
< Access-Control-Expose-Headers: *
< Access-Control-Allow-Headers: *
< 
hello 1980
```
4、Remove the global cors plugin

```shell
$ curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X DELETE
{"key":"\/apisix\/global_rules\/1","node":{},"deleted":"1","action":"delete"}
```

5、 Request the API again (there is no `CORS` related response headers)

```shell
$ curl http://127.0.0.1:9080/hello -v
* About to connect() to 127.0.0.1 port 9080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET /hello HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:9080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/octet-stream
< Transfer-Encoding: chunked
< Connection: keep-alive
< Date: Thu, 11 Mar 2021 07:36:16 GMT
< Server: APISIX/2.3
< 
hello 1980
```

**Comment by moonming** [comment]
@miaoyb 
Please use English in the public channel, thx

**Comment by spacewander** [comment]
Closed as lack of response.
