### ISSUE TITLE
bug: 404 or 500 when apisix reload

### ISSUE THREAD

**Issue by redynasc** [apache/apisix#3779]
### Issue description
the request reponse 404 or 500 when apisix reload
### Environment

* apisix version (cmd: `apisix version`):v1.5
* OS (cmd: `uname -a`):Linux d5-dui-10042016030hb 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.3.33
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.  keep the 50 qps stress test
2.  reload the apisix by command  'kill -HUP processid'

### What's the actual result? (including assertion message & call stack if applicable)
some request reponse 404 or 500,
the error log  like this:
"lua] init.lua:392: http_access_phase(): failed to find upstream by id: 00000000000000012085"

My analysis：
  first load the config of all routes and upsteams asynchronously in http_init_worker phase，
when the first http request up  come in，the routes and upstreams has not been loaded completely
### What's the expected result?
reponse 200

**Comment by Firstsawyou** [comment]
Your apisix version is relatively old, not sure whether it has been fixed, it is recommended to update to the latest version to try.

**Comment by spacewander** [comment]
Known issue: https://github.com/apache/apisix/issues/3370.
