### ISSUE TITLE
request help: SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#3783]
### Issue description

我有个upsream的scheme设置为http，然后这个路由也配置了SSL证书，用https直接访问能够正常返回，但是upsream的scheme设置为https（强制跳转https），访问一直报502 Bad Gateway

路由配置：
{
    "uri": "/test/*",
	"hosts": ["nutsta.cn"],
    "plugins": {
    },
    "upstream": {
        "service_name": "TEST-SERVICE",
        "type": "roundrobin",
        "discovery_type": "eureka",
	"scheme": "https"
    }
}

错误日志：
2021/03/08 21:16:09 [error] 65945#681239: *2862 SSL_do_handshake() failed (SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number), client: 127.0.0.1, server: , request: "GET /test/test HTTP/1.1", subrequest: "/proxy_mirror", host: "nutsta.cn:9080"

### Environment
本地

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`): Darwin MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
{
    "id": "f7444900-a7af-4b20-9f83-365947024ee8",
    "version": "2.4",
    "boot_time": 1615209248,
    "etcd_version": "3.4.0",
    "up_time": 572,
    "last_report_time": 1615209788,
    "hostname": "sMacBook-Pro.local"
}

* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
> SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

What's your upstream's TLS protocol version?

**Comment by kongjun01** [comment]
> > SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> 
> What's your upstream's TLS protocol version?

ssl_protocols TLSv1.2 TLSv1.3;

**Comment by kongjun01** [comment]
> > SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> 
> What's your upstream's TLS protocol version?

上游服务是tomcat，没有任何的ssl配置。可能不是上游的问题，因为upsream的scheme设置为http，用https访问正常。

**Comment by kongjun01** [comment]
> > SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number
> 
> What's your upstream's TLS protocol version?

TLSv1 TLSv1.1 TLSv1.2  ?

**Comment by spacewander** [comment]
Will you provide a network capture file including the handshake with the upstream?

**Comment by kongjun01** [comment]
问题解决了，强制跳转https用的是重定向，不是重写

**Comment by whioue** [comment]
> 问题解决了，强制跳转https用的是重定向，不是重写

请问是怎么解决的，我也遇到了这个问题

**Comment by whioue** [comment]
> Will you provide a network capture file including the handshake with the upstream?
我也遇到了这个问题，下面是我捕捉到的数据包，后端的nginx会返回400的错误，错误日志中的报错信息为：SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number。
![image](https://user-images.githubusercontent.com/47098518/184130045-efb4c9f9-b730-4e0d-ab1e-42ff68532f3d.png)
![image](https://user-images.githubusercontent.com/47098518/184130074-18cf0980-e3a3-4fe0-a433-fe2087f463d8.png)

**Comment by tzssangglass** [comment]
> 请问是怎么解决的，我也遇到了这个问题

use `redirect` plugin.

**Comment by whioue** [comment]
> > 请问是怎么解决的，我也遇到了这个问题
> 
> use `redirect` plugin.
我理解的重定向插件是客户端使用http访问apisix，会重定向为客户端使用https访问apisix，这与apisix与后端的ssl握手有关联吗？

**Comment by tzssangglass** [comment]
> 我理解的重定向插件是客户端使用http访问apisix，会重定向为客户端使用https访问apisix，这与apisix与后端的ssl握手有关联吗？

I mean, this problem was solved by this last user with the `redirect` plugin. If your question is different, please submit a new issue.
