### ISSUE TITLE
request help: api-breaker 

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3784]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): Tengine.2.3
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

What the gateway will do when the service resumes available beyond the maximum fuse duration configured by the gateway.

**Comment by tokers** [comment]
Currently the service has to wait until the `max_breaker_sec` time elapsed. See https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/api-breaker.md for more details.

**Comment by Yangzcy423911** [comment]
I've read this document. When the service is available, the maximum time of fusing is exceeded. How should the gateway recover the request and call to the upstream service
