### ISSUE TITLE
[discuss]: does the traffic-split plugin has a way to implement the original capabilities without corrupting the data?

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#3787]
### Issue description
prerequisite: the traffic-split plugin now controls the request proxy to a specific upstream by corrupting the upstream configuration in the route.

topic: is there a way to do the same thing without corrupting the upstream configuration in the route?

if there are problems with the prerequisite, please correct me

reference #3758

**Comment by moonming** [comment]
@Firstsawyou

**Comment by membphis** [comment]
ping @Firstsawyou

**Comment by Firstsawyou** [comment]
@tzssangglass  uses the method of `"when the route is configured with an upstream_id, the upstream_id is passed into the server_list"` to solve it.
Thank you very much @tzssangglass .

**Comment by Firstsawyou** [comment]
I think we can create a temporary variable to cache the upstream_id configured in the plug-in, and delete it after the end of use, so as to avoid the modification of `ctx.matched_route.value.upstream_id`. For example, create a temporary variable upstream_id_tmp: `ctx.matched_route.value.upstream_id_tmp`
