### ISSUE TITLE
request help: 用openssl生成证书和秘钥后，不能直接用，还要把私有CA证书cacert.pem文件内容，追加到/etc/pkis/certs/ca-bundle.crt，才能用https访问

### ISSUE THREAD

**Issue by xuyancheng24** [apache/apisix#3800]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
* apisix-dashboard version, if have:2.3

**Comment by xuyancheng24** [comment]
ssl证书，apisix ssl的这个属性能用吗？这个看注释应该是指定受信任的证书路径吧？怎么用？我这边希望不通过证书信息追加到/etc/pkis/certs/ca-bundle.crt方式才能访问https，用那个受信任的证书路径参数可以解决吗？

**Comment by xuyancheng24** [comment]
ssl证书，apisix ssl的这个属性能用吗？这个看注释应该是指定受信任的证书路径吧？怎么用？我这边希望不通过证书信息追加到/etc/pkis/certs/ca-bundle.crt方式才能访问https，用那个受信任的证书路径参数可以解决吗？
![Uploading 1.png…]()

**Comment by tokers** [comment]
@xuyancheng24 `ssl_trusted_certificate` is used to fill the Nginx directive `lua_ssl_trusted_certificate`, which is used by APISIX itself when it talks to external components (to verify these components).

You didn't say how you use the self-signed certificate, maybe as a server-side certificate? In such a case, this depends on your clients' to ignore the verification of the certificate. It has nothing to do with putting the CA cert to /etc/pkis/certs/ca-bundle.crt unless you access APISIX in the local host.

**Comment by xuyancheng24** [comment]
you mean if I don't access APISIX in the local host, and it as a server-side certificate,or Client access does not affect，I don't need the CA cert (/etc/pkis/certs/ca-bundle.crt)?

**Comment by tokers** [comment]
> you mean if I don't access APISIX in the local host, and it as a server-side certificate,or Client access does not affect，I don't need the CA cert (/etc/pkis/certs/ca-bundle.crt)?

I did'nt totally understand your mean. But if you want to use this self-signed certificate as a server side certificate, you should:

1. configure a SSL object with the cert and priv key, written to ETCD through APISIX admin API or manager API;
2. add the CA cert to the /etc/pki/certs/ca-bundle.crt or other similar files in your client machine/VM/container, or just ignore the certification verification in your client side;

**Comment by moonming** [comment]
@xuyancheng24 
Please use English in the public channel, thx
