### ISSUE TITLE
request help: support kubernetes as service discovery

### ISSUE THREAD

**Issue by Junnplus** [apache/apisix#3801]
### Issue description
RT.

**Comment by spacewander** [comment]
Use https://github.com/apache/apisix-ingress-controller instead?

**Comment by tokers** [comment]
@Junnplus Use Ingress Controller is a better way, or we have to communicate with API Server in APISIX core, which is complex and the ecosystem is lack.

**Comment by Junnplus** [comment]
I know Ingress Controller of APISIX, but it depends on the realization of crds, I want to synchronize services in the specified namespaces, but need to create an ApisixUpstream for each service in ingress controller.

**Comment by spacewander** [comment]
Maybe you can export them via DNS:
https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/dns.md
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/

**Comment by xianshun163** [comment]
when  use dns，  it is differ as the service discovery, the apisix  balancer.lua can  not get  the pod ip.

**Comment by zhixiongdu027** [comment]
#4880
Maybe You Can Try This PR
