### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by MrLibra** [apache/apisix#3803]
### Issue description
[root@geek_apisix_dev_bjh01 apisix]# make deps
luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
Using rockspec/apisix-master-0.rockspec... switching to 'build' mode
Stopping after installing dependencies for apisix master-0

[root@geek_apisix_dev_bjh01 apisix]# ./bin/apisix version
2.2
[root@geek_apisix_dev_bjh01 apisix]# ./bin/apisix start
lua: /workspace/apisix/deps/share/lua/5.1/tinyyaml.lua:728: parse error: apisix:
stack traceback:
	[C]: in function 'error'
	/workspace/apisix/deps/share/lua/5.1/tinyyaml.lua:728: in function 'parsedocuments'
	/workspace/apisix/deps/share/lua/5.1/tinyyaml.lua:760: in function 'parse'
	./apisix/cli/file.lua:196: in function 'read_yaml_conf'
	./apisix/cli/ops.lua:133: in function 'init'
	./apisix/cli/ops.lua:393: in function '?'
	./apisix/cli/ops.lua:455: in function 'execute'
	./bin/apisix:36: in main chunk
	[C]: ?
### Environment
* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):centos7.4
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:

**Comment by MrLibra** [comment]
Installing https://luarocks.org/luaxxhash-1.0.0-1.rockspec

Error: Failed installing dependency: https://luarocks.org/lua-resty-dns-client-5.2.0-1.src.rock - Failed installing dependency: https://luarocks.org/luaxxhash-1.0.0-1.rockspec - Unknown protocol git
make: *** [deps] 错误 1

**Comment by Firstsawyou** [comment]
Is there an error message when I run the `make deps` command?

**Comment by spacewander** [comment]
Closed as lack of response.
