### ISSUE TITLE
request help: type mismatch at offset 33, bytes expected for type string, got varint

### ISSUE THREAD

**Issue by riskgod** [apache/apisix#3818]
### Issue description
I add the plugin grpc-transcode to my APISIX，but get the err type mismatch at offset 33, bytes expected for type string, got varint

### Environment
Use docker to build my local APISIX https://github.com/apache/apisix-docker/tree/master/example
Here is the my local grpc source code https://github.com/ShisiJu/grpc-node
Here is the steps I use https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md
### Minimal test code / Steps to reproduce the issue

create the apisix's proto
```
curl http://127.0.0.1:9080/apisix/admin/proto/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "content" : "syntax = \"proto3\";
    package helloworld;
    service Greeter {
        rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
    message HelloRequest {
        string name = 1;
    }
    message HelloReply {
        string message = 1;
    }"
}'
```
setup the router 

```
curl http://127.0.0.1:9080/apisix/admin/routes/111 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/grpctest",
    "plugins": {
        "grpc-transcode": {
            "proto_id": "1",
            "service": "helloworld.Greeter",
            "method": "SayHello"
        }
    },
    "upstream": {
        "scheme": "grpc",
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:50051": 1
        }
    }
}'
```

1: open localhost:9000 
2: set my upstream to my grpc server 
3: set my router to my upstream 
4: curl -i http://127.0.0.1:9080/grpctest?name=world

### What's the actual result? (including assertion message & call stack if applicable)
```
failed to run body_filter_by_lua*: .../local/apisix/apisix/plugins/grpc-transcode/response.lua:58: type mismatch at offset 33, bytes expected for type string, got varint
```
### What's the expected result?
```shell
HTTP/1.1 200 OK
Date: Fri, 16 Aug 2019 11:55:36 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server
Proxy-Connection: keep-alive

{"message":"Hello world"}
```

**Comment by nic-chen** [comment]
@riskgod  how to run you grpc server ?

**Comment by riskgod** [comment]
> hi , @riskgod how to run you grpc server ?

```bash
# 进入目录
cd dynamic_codegen/
# 运行服务端代码
node greeter_server.js 
# 运行客户端代码
node greeter_client.js 
```

**Comment by nic-chen** [comment]
@riskgod 
I think it is caused by inconsistent proto:
https://github.com/ShisiJu/grpc-node/blob/master/protos/helloworld.proto#L31-L40

You could try to use the same proto as APISIX on the grpc server.

**Comment by riskgod** [comment]
> @riskgod
> I think it is caused by inconsistent proto:
> https://github.com/ShisiJu/grpc-node/blob/master/protos/helloworld.proto#L31-L40
> 
> You could try to use the same proto as APISIX on the grpc server.

after update the proto file the problem is not fixed

```
message HelloRequest {
  string name = 1 ;
}

// The response message containing the greetings
message HelloReply {
  string message = 1 ;
}
```

**Comment by nic-chen** [comment]
@riskgod  sorry, I'm busy these days, may try to reproduce on my side later.
