### ISSUE TITLE
bug: the duration recorded by the zipkin plugin does not match the phase

### ISSUE THREAD

**Issue by zfs123** [apache/apisix#3827]
### Issue description
The duration recorded by the zipkin plugin does not match the phase. May The plugin should be executed last, not first.

### Minimal test code / Steps to reproduce the issue
add ngx.sleep() at some other plugin's rewrite phase, the duration of access phase will be longer, instead of rewrite phase.

**Comment by spacewander** [comment]
This is a problem. However, if we put the zipkin plugin to the last, requests rejected by previous plugins won't be traced.

@moonming @membphis 
Maybe we can reassign the span into proxy/response/log? Those are doubtless.

**Comment by membphis** [comment]
I think we can move some code to `rewrite` phase, is it enough?

**Comment by zfs123** [comment]
>if we put the zipkin plugin to the last, requests rejected by previous plugins won't be traced.

Does this problem exist no matter whether we put this plugin on the first or the last?

**Comment by spacewander** [comment]
> 
> 
> > if we put the zipkin plugin to the last, requests rejected by previous plugins won't be traced.
> 
> Does this problem exist no matter whether we put this plugin on the first or the last?

Why does this problem exist if we run the plugin first?

**Comment by zfs123** [comment]
> > > if we put the zipkin plugin to the last, requests rejected by previous plugins won't be traced.
> > 
> > 
> > Does this problem exist no matter whether we put this plugin on the first or the last?
> 
> Why does this problem exist if we run the plugin first?

If we run the plugin first, we record the duration of the last phase at the beginning of the current phase. if the request was rejected in last phase, we can not record the duration.

**Comment by spacewander** [comment]
> 
> 
> > > > if we put the zipkin plugin to the last, requests rejected by previous plugins won't be traced.
> > > 
> > > 
> > > Does this problem exist no matter whether we put this plugin on the first or the last?
> > 
> > 
> > Why does this problem exist if we run the plugin first?
> 
> If we run the plugin first, we record the duration of the last phase at the beginning of the current phase. if the request was rejected in last phase, we can not record the duration.

I see. I thought "this problem" is "rejected by previous plugins won't be traced" so I mislead your reply.

Actually, we can't measure the time of phases correctly. Therefore I advise reassigning the span into proxy/response which is doubtless.

**Comment by zfs123** [comment]
> Actually, we can't measure the time of phases correctly. Therefore I advise reassigning the span into proxy/response which is doubtless.

Reassigning the span into proxy/response is a nice way. 

I have a idea that if we want to measure the time of phases, how about splitting the zipkin plugin into two plugins?

zipkin-proxy: from the request start to the request is tranfered to upstream(rewrite, access, balancer)
zipkin-response: from the header of the response is read to the start of log phase.(header_filter, body_filter)

In order not to include upstream response time, the zipkin-proxy plugin should have the lowest priority. 
In order to measure the time of header_filter phase, the zipkin-response plugin should have the highest priority. 

Can we measure the time of every phase correctly by this way?

**Comment by spacewander** [comment]
Yes, split zipkin into two plugins can measure the time correctly.
However, it will break the convention that we should handle all the things in one plugin. It will introduce more complexity to the dashboard and other relative projects.

As the time measure might be not so critical, I think we can sacrifice some part of it to prevent architecture change.

**Comment by zfs123** [comment]
Thanks a lot!
