### ISSUE TITLE
bug: link error after splite architecture design documents

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#3833]
### Issue description

After separating the architecture design document, other documents are not modified, resulting in link errors.

### Minimal test code / Steps to reproduce the issue

1. Open `https://apisix.apache.org/docs/apisix/admin-api`
2. Find `Router` Link

or

1. Open `https://github.com/apache/apisix/blob/master/docs/zh/latest/admin-api.md`
2. Find `Router` Link

### What's the actual result? (including assertion message & call stack if applicable)

Redirect to a page that does not exist. (Page Not Found)

### What's the expected result?

Show correct document content.

**Comment by bzp2010** [comment]
If it's not a special design, I will fix it. XD

**Comment by tokers** [comment]
@bzp2010 I think it's a bug, PR's welcome.

**Comment by bzp2010** [comment]
> @bzp2010 I think it's a bug, PR's welcome.

Yes, I have submitted a PR to fix it. #3834
