### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by whioue** [apache/apisix#3835]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.In version 2.0, I tried to call the hot load interface to update my modified plugin (update the plug-in code), but it didn't take effect, after restart server, the plugin  effect

**Comment by tokers** [comment]
@whioue Could you please provide more detailed steps to reproduce this problem? Also, please summary your problem in simple words to title this issue.
