### ISSUE TITLE
bug: Using admin/plugins/reload function, the plugin modification is not effective

### ISSUE THREAD

**Issue by whioue** [apache/apisix#3837]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.In version 2.0, After modifying the plugin, use the hot load function (admin / plugins / reload). The modification does not take effect. but if you restart server the plugin directly after modifying it, the modification will take effect. i don't know why, ask for help , thank you

**Comment by Firstsawyou** [comment]
>After modifying the plugin,

This mean: Modify the code of the plugin, or modify the configuration of the plugin?

**Comment by whioue** [comment]
> > 修改插件后，
> 
> 这意味着：修改插件的代码，还是修改插件的配置？
What is modifying plugin configuration？

**Comment by whioue** [comment]
> > After modifying the plugin,
> 
> This mean: Modify the code of the plugin, or modify the configuration of the plugin?
I want Modify the code of the plugin, what is modify the configuration of the plugin?

**Comment by Firstsawyou** [comment]
> what is modify the configuration of the plugin

Modify the configuration of the plugin to look like this: 

Change the field value of the limit-count plugin.

```shell
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "count": 2,
            "time_window": 60,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}'
```

**Comment by whioue** [comment]
> > what is modify the configuration of the plugin
> 
> Modify the configuration of the plugin to look like this:
> 
> Change the field value of the limit-count plugin.
> 
> ```shell
> curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/index.html",
>     "plugins": {
>         "limit-count": {
>             "count": 2,
>             "time_window": 60,
>             "rejected_code": 503,
>             "key": "remote_addr"
>         }
>     },
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "39.97.63.215:80": 1
>         }
>     }
> }'
> ```
This kind of configuration change can take effect without hot reload,right？I don't know how to change the plugin must be use /admin/plugins/reload
