### ISSUE TITLE
request help: Is it possible to close prometheus metrics request log

### ISSUE THREAD

**Issue by linxiaohui** [apache/apisix#3840]
### Issue description

I have enabled the prometheus plugin， and prometheus quest `/apisix/prometheus/metrics` every 15s. the request will show at apisix‘s access.log，is it possible to configure apisix  **not logging this request to access.log**
 
### Environment

* apisix version (cmd: `apisix version`):
 2.3
* OS (cmd: `uname -a`):
 Linux Ubuntu 20.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
 nginx version: openresty/1.19.3.1
built by gcc 9.3.0 (Alpine 9.3.0) 
built with OpenSSL 1.1.1i  8 Dec 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre --with-compat --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads --with-stream --with-stream_ssl_preread_module

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 
3.4.9 
* apisix-dashboard version, if have:

**Comment by tokers** [comment]
@linxiaohui See the `http.enable_access_log` in config-default.yaml, just set it to `false`.

**Comment by linxiaohui** [comment]
> @linxiaohui See the `http.enable_access_log` in config-default.yaml, just set it to `false`.

@tokers Thanks for your reply. I checked this, it seems that this config will disable the who access. log, whis I want is just the /apisix/prometheus/metrics won't show

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/issues/3526
