### ISSUE TITLE
request help: How to auto upgrade SSL certificate, such as using let's encrypt

### ISSUE THREAD

**Issue by JoeyGaojingxing** [apache/apisix#3841]
### Issue description

Just as the title, feel difficult with lua

**Comment by spacewander** [comment]
You can write a cron job that checks the certificates and upgrade them via admin/manager API. There is no need to do it in Lua.

**Comment by JoeyGaojingxing** [comment]
That's a good idea, thanks a lot~

**Comment by anjia0532** [comment]
https://github.com/auto-ssl/lua-resty-auto-ssl

**Comment by Yiyiyimu** [comment]
> https://github.com/auto-ssl/lua-resty-auto-ssl

Welcome PR!

**Comment by anjia0532** [comment]
[acme.sh#Using pre hook post hook renew hook reloadcmd](https://github.com/acmesh-official/acme.sh/wiki/Using-pre-hook-post-hook-renew-hook-reloadcmd)+[apisix admin api#SSL](https://apisix.apache.org/zh/docs/apisix/admin-api#ssl) works.

**Comment by Yiyiyimu** [comment]
@anjia0532 Do you mind add it to the docs

**Comment by anjia0532** [comment]
@Yiyiyimu Maybe next week

easy to do this.

1. gen ssl certificate by acme.sh
2. set renew hook script to update apisix ssl key and cert. `PUT /apisix/admin/ssl/{id}`

**Comment by anjia0532** [comment]
@Yiyiyimu https://github.com/apache/apisix/pull/4297

**Comment by 04116** [comment]
hi, how about renew on stand-alone mode?
