### ISSUE TITLE
Request help: Using upstream_route, all requests go to node 1. How to evenly distribute the requests to all nodes?

### ISSUE THREAD

**Issue by sailershen** [apache/apisix#3843]
# 环境
centos 7.9 x64，通过rpm安装的apisix-2.4-0.x86_64。
etcd版本为3.4.13，rpm安装，装好后没有修改任何配置，直接启动运行。

# 需求：
用apisix做负载均衡，把请求分配到后端172.16.10.241:6500 （1号节点）和 172.16.10.242:6500（2号节点）上，6500端口是业务系统定义的非web端口。

# apisix的配置文件
/usr/local/apisix/conf/config.yaml的内容：
```
etcd:
  host:
    - "http://127.0.0.1:2379"
apisix:
  admin_key:
    - name: "admin"
   key: edd1c9f034335f136f87ad84b625c8f2
     role: admin
  stream_proxy:
    tcp:
      - 6500
```

# 操作命令
```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1
        },
        "type": "roundrobin"
    }
}'
```
```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/2 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "upstream": {
        "nodes": {
            "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

# 查看stream_route：
`
curl http://127.0.0.1:9080/apisix/admin/stream_routes/ -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2'
`

# 输出
```
{
  "count":"3",
  "node":{
    "key":"\/apisix\/stream_routes",
    "nodes":[
      {
        "createdIndex":1595,
        "value":{
          "upstream":{
            "pass_host":"pass",
            "nodes":{"172.16.10.241:6500":1},
            "scheme":"http",
            "hash_on":"vars",
            "type":"roundrobin"
          },
          "id":"1"
        },
        "modifiedIndex":1595,
        "key":"\/apisix\/stream_routes\/1"
      },
      {
        "createdIndex":1596,
        "value":{
          "upstream":{
            "pass_host":"pass",
            "nodes":{"172.16.10.242:6500":1},
            "scheme":"http",
            "hash_on":"vars",
            "type":"roundrobin"
          },
          "id":"2"
        },
        "modifiedIndex":1596,
        "key":"\/apisix\/stream_routes\/2"
      }
    ],
    "dir":true
  },
  "action":"get"
}
```

在多台电脑上用telnet访问apisix服务器的6500端口，发现只有1号节点上有来自apisix服务器的网络连接，2号节点上一个也没有。
请问如何把对6500端口的访问平均分布到所有节点上？

**Comment by Firstsawyou** [comment]
let me check.

**Comment by sailershen** [comment]
> let me check.

Thanks

**Comment by Firstsawyou** [comment]
You can try to match the request through remote_addr, but the remote_addr option only supports a single IP configuration. Example:

```shell
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

**Comment by sailershen** [comment]
Thanks for help.

**Comment by tokers** [comment]
Why not put these two endpoints into one route?

```json
{
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1,
            "172.16.10.242:6500": 2
        },
        "type": "roundrobin"
    }
}
```

**Comment by moonming** [comment]
@sailershen 
Please use English in the public channel, thx

**Comment by sailershen** [comment]
Thx.
Now I try to use "remote_addr".
```
# node 1
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

```
# node 2
curl http://127.0.0.1:9080/apisix/admin/stream_routes/2 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

Show the stream_routes:
```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/ -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2'
```

Output:
`
{"count":"3","node":{"key":"\/apisix\/stream_routes","nodes":[{"createdIndex":8533,"value":{"remote_addr":"127.0.0.1","upstream":{"pass_host":"pass","nodes":{"172.16.10.241:6500":1},"scheme":"http","hash_on":"vars","type":"roundrobin"},"id":"1"},"modifiedIndex":8533,"key":"\/apisix\/stream_routes\/1"},{"createdIndex":8534,"value":{"remote_addr":"127.0.0.1","upstream":{"pass_host":"pass","nodes":{"172.16.10.242:6500":1},"scheme":"http","hash_on":"vars","type":"roundrobin"},"id":"2"},"modifiedIndex":8534,"key":"\/apisix\/stream_routes\/2"}],"dir":true},"action":"get"}
`

But when I telnet to node 1 or to

**Comment by Firstsawyou** [comment]
Hi, @sailershen  You try to configure two stream_routes together, like this:

> Why not put these two endpoints into one route?
> 
> ```json
>curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
> {
>     "upstream": {
>         "nodes": {
>             "172.16.10.241:6500": 1,
>             "172.16.10.242:6500": 1
>         },
>         "type": "roundrobin"
>     }
> }'
> ```

**Comment by sailershen** [comment]
Thx for help.


```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1,
            "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

or 

```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f2' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1,
            "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

it's still failed.
```
telnet 127.0.0.1 6500
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```

**Comment by Firstsawyou** [comment]
@spacewander  If you have time, please help look at this problem. In the proxy stream, can't we configure multiple upstream nodes? When I test that upsteam has multiple nodes, the following error message will appear:

1、 add stream route

```shell
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY:edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{   
    "upstream": {
        "nodes": {
            "172.16.10.241:6500": 1,
             "172.16.10.242:6500": 1
        },
        "type": "roundrobin"
    }
}'
```

2、 test request

```shell
$ telnet 127.0.0.1 6500
Trying 127.0.0.1...
Connected to 127.0.0.1.
Escape character is '^]'.
Connection closed by foreign host.
```

3、error.log  info

```
2021/03/22 14:34:14 [error] 20162#20162: *41200 failed to run balancer_by_lua*: /home/apisix-bug-report/apisix/balancer.lua:50: table index is nil
stack traceback:
        /home/apisix-bug-report/apisix/balancer.lua:50: in function 'transform_node'
        /home/apisix-bug-report/apisix/balancer.lua:64: in function 'fetch_health_nodes'
        /home/apisix-bug-report/apisix/balancer.lua:101: in function 'create_obj_fun'
        /home/apisix-bug-report/apisix/core/lrucache.lua:92: in function 'lrucache_server_picker'
        /home/apisix-bug-report/apisix/balancer.lua:189: in function 'pick_server'
        /home/apisix-bug-report/apisix/balancer.lua:221: in function 'load_balancer'
        /home/apisix-bug-report/apisix/init.lua:796: in function 'stream_balancer_phase'
        balancer_by_lua:2: in main chunk while connecting to upstream, client: 127.0.0.1, server: 0.0.0.0:6500, bytes from/to client:0/0, bytes from/to upstream:0/0
```

**Comment by membphis** [comment]
> @spacewander If you have time, please help look at this problem. In the proxy stream, can't we configure multiple upstream nodes? When I test that upsteam has multiple nodes, the following error message will appear:

it seems that you found one bug. ^_^

**Comment by Firstsawyou** [comment]
> it seems that you found one bug. ^_^

Got it, we need to fix it and add more test cases.

**Comment by spacewander** [comment]
I am already working on it.

**Comment by Firstsawyou** [comment]
Hi, @sailershen 
Thank you for your report, this problem has been fixed, you can follow this PR: https://github.com/apache/apisix/pull/3897

**Comment by Yullin** [comment]
> You can try to match the request through remote_addr, but the remote_addr option only supports a single IP configuration. Example:
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "remote_addr": "127.0.0.1",
>     "upstream": {
>         "nodes": {
>             "172.16.10.242:6500": 1
>         },
>         "type": "roundrobin"
>     }
> }'
> ```

So why not support multiple ip addresses or like "192.168.0.0/16"?
