### ISSUE TITLE
request help: How to know when apsix loading all config from etcd, and ready for request?

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#3844]
### Issue description
How to know when apsix loading all config from etcd, and ready for request?

For example ,  we need to auto scale apisix server，so we shoud know when apsix  ready， 

 user request can be sent to it

### Environment

* apisix version (2.3):
* OS (ubuntu 16):
* OpenResty / Nginx version (1.19.3):
* etcd version, if have (3.4):

**Comment by spacewander** [comment]
I think we don't need it after https://github.com/apache/apisix/pull/3799 is merged?

**Comment by nanamikon** [comment]
Nice PR,  it is fine to me.
