### ISSUE TITLE
request help: Include message body when performing HMAC authentication

### ISSUE THREAD

**Issue by rdouman** [apache/apisix#3846]
### Issue description
We have an upstream provider that is using HMAC authentication when calling our APISIX instance.  They are including only request body data when generating their HMAC and not using any headers or url paramteres.  Is is possible, using the HMAC plugin to validate the HMAC using the request body ? Also, is there a mechanism to exclude the request headers ?

### Environment

* apisix version (cmd: `apisix version`): 2.2
* OS (cmd: `uname -a`): apache/apisix:2.2-alpine
* etcd version: 3.4.14
* apisix-dashboard version, if have: 2.3

**Comment by Firstsawyou** [comment]
The hmac-auth plugin does not sign the body of the request. You can try to sign without using request headers or url parameters.

**Comment by rdouman** [comment]
Hi @Firstsawyou thanks for your response.  The message body is signed by our vendor in order to not only authenticate the message but also show that the message has not been altered.  I'm a still little unclear from the answer above about how to achieve my desired result.  Are you suggesting that omitting the **request headers** and **url parameters** would produce the required result (i.e. include the message body) ?

**Comment by Firstsawyou** [comment]
> Hi @Firstsawyou thanks for your response. The message body is signed by our vendor in order to not only authenticate the message but also show that the message has not been altered. I'm a still little unclear from the answer above about how to achieve my desired result. Are you suggesting that omitting the **request headers** and **url parameters** would produce the required result (i.e. include the message body) ?

The hmac-auth plugin does not sign the request body. If you want to include the signature of the request body, I think the plugin needs to be modified.
@nic-chen  What do you think?

**Comment by nic-chen** [comment]
Yes, it is not supported by default. 
I think we could add a custom header (the hash value of the body) to judge, instead of reading the body directly for comparison.

**Comment by tokers** [comment]
> Yes, it is not supported by default.
> I think we could add a custom header (the hash value of the body) to judge, instead of reading the body directly for comparison.

You may refer to the [Content-MD5 header](https://tools.ietf.org/html/rfc1864), it's analogous.
