### ISSUE TITLE
bug: roundrobin load balancing k8s short domain name and ip configuration at the same time will only choose one kind of polling

### ISSUE THREAD

**Issue by godsoul** [apache/apisix#3849]
### Environment

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`):Linux gateway-apisix-f46d89c6b-4gjst 3.10.0-1127.19.1.el7.x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* apisix-dashboard version, if have: 2.3

### Minimal test code / Steps to reproduce the issue

1.roundrobin 负载均衡k8s 短域名服务 ( xxx.svc.default.cluster.local) 和 ip (10.1.1.1) 只会选择一种轮询

### What's the actual result? (including assertion message & call stack if applicable)
当k8s 短域名服务 权重高的时候，流量只会进 k8s 短域名服务上，ip 不会有流量，当 k8s 短域名和 ip权重一样的时候，流量只会进 ip 服务
### What's the expected result?
本来应该按权重轮询

**Comment by tokers** [comment]
@godsoul A minimalist case is desired to let us reproduce your problem :).

**Comment by godsoul** [comment]
![image](https://user-images.githubusercontent.com/3104500/111562445-31e5f200-87d1-11eb-9d78-12468840705b.png)

**Comment by imjoey** [comment]
@godsoul this seems very weird. Are you using an APISIX instance as a normal Service, or as an ingress gateway? Could you please elaborate on the deployment architecture? We do need more details. Thanks.

**Comment by godsoul** [comment]
1. network flow path： Nginx ingress -> APISIX gateway -> api-gateway-srv 
2. Nginx is ingress, APISIX is gateway, The api-gateway-srv  is normal  micro service .

**Comment by moonming** [comment]
@godsoul 
Please use English in the public channel, thx
