### ISSUE TITLE
feature: ACL

### ISSUE THREAD

**Issue by sgnah** [apache/apisix#385]
ACL 功能，什么时候加入？

**Comment by chnliyong** [comment]
The `ACL` may be a broad subject.
The intuitive idea is ip whitelist and ip blacklist. We need to group the ip list and apply to specific routes. I have planned to write a `ip-whitelist` plugin，the plugin need config ip whitelist group，and may need extract a concept `IP Group`(represent by CIDR) such as `SSL`, `Upstream`

**Comment by spacewander** [comment]
The consumer mechanism works as ACL.
