### ISSUE TITLE
bug: cannot use https when creating route through web UI

### ISSUE THREAD

**Issue by JoeyGaojingxing** [apache/apisix#3852]
### Issue description

![image](https://user-images.githubusercontent.com/15071824/111511196-764d9f80-8789-11eb-8eb5-fb22866f37e9.png)
![image](https://user-images.githubusercontent.com/15071824/111511286-8bc2c980-8789-11eb-8e64-22999e5648ab.png)

### Environment

* apisix version (cmd: `apisix version`): 2.3
* OS (cmd: `uname -a`): Linux ecs-s2-large-2-linux-20190719115737 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx:1.18.0-alpine
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): No
* apisix-dashboard version, if have: 2.4

### Minimal test code / Steps to reproduce the issue

1. create a SSL certificate from browser
2. create an route an chose `Enable HTTPS`
3. click `Next` then throw the error

### What's the expected result?

It should go to the next step with out error

**Comment by tokers** [comment]
> click Next then throw the error

@JoeyGaojingxing Could you provide the error details?

**Comment by spacewander** [comment]
Moved to https://github.com/apache/apisix-dashboard/issues/1611
