### ISSUE TITLE
The available key types in limit-count plugin are not recorded in docs

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3855]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

The key type in limit-count plugin can be:

* `remote_addr`
* `server_addr`
* `http_x_real_ip`
* `http_x_forwarded_for`
* `consumer_name`
* `service_id`

But none of them were recorded.

## Describe the solution you'd like

Add a section to describe the available key types in the document of limit-count plugin.

**Comment by spacewander** [comment]
@tokers 
The key types are recorded in docs.
See http://apisix.apache.org/docs/apisix/plugins/limit-count

```
["remote_addr", "server_addr", "http_x_real_ip", "http_x_forwarded_for", "consumer_name", "service_id"]
```

**Comment by iamayushdas** [comment]
i think markdown file of limit-count plugin will be more helpful for user after this: #3866 i guess

**Comment by spacewander** [comment]
I don't like to repeat the same words multiple times.

**Comment by iamayushdas** [comment]
> I don't like to repeat the same words multiple times.

okay my bad

**Comment by spacewander** [comment]
Note that the website is generated from the markdown.
This is the markdown source: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/limit-count.md#attributes

**Comment by iamayushdas** [comment]
yeah got your point.

**Comment by spacewander** [comment]
Close this issue as we don't need it actually.
