### ISSUE TITLE
[discuss] Support exposing databases as web services

### ISSUE THREAD

**Issue by imjoey** [apache/apisix#3856]
### Issue description

When constructing data middle platform, uses may need expose their databases, e.g. relational/bigdata/nosql, as web services for API consumers.

For now, we firstly develop an application for databases access, and then set it as the upstream of APISIX routes. For example, we make use of [PostgREST/postgrest](https://github.com/PostgREST/postgrest) to serve RESTful APIs for Postgresql and make APISIX proxy the requests to the RESTful APIs provided by postgrest.

I was wondering that if APISIX could add support for auto-exposing the databases via uniform CRUD APIs. If possible, the only thing that users need to do is to fulfill the endpoint and credential of databases, and then the APIs are ready for data CRUD.

This feature is normally a build-in feature within ESBs, like Mule or WSO2. In contrast, APISIX is a lightweight API Gateway. So in regard of this feature, I'm very much looking forward to your insights.

Thanks very much.

**Comment by membphis** [comment]
For discussion of new features, I recommend moving to the mailing list for discussion. 

@imjoey

**Comment by imjoey** [comment]
> For discussion of new features, I recommend moving to the mailing list for discussion.
> 
> @imjoey

@membphis ok, thanks for the directions. I would turn to mailing list for further discussions.

**Comment by imjoey** [comment]
Close this for now, will reopen this if we are planning to add this feature. Thanks.
