### ISSUE TITLE
Optimize the Serverless plugin

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3857]
### Issue description

Currently the serverless plugin functions don't have args, when we want to access some per-request data in `api_ctx`, we have to use `ngx.ctx.api_ctx`, which is obscure for new users. So I think we can push the `api_ctx` table to all serverless functions. For instance, we can write a function like:

```json
"serverless-pre-function": {
            "phase": "rewrite",
            "functions" : ["return function(api_ctx) ngx.log(ngx.ERR, \"consumer name is \", api_ctx.consumer_name); end"]
}
```

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by iamayushdas** [comment]
can i have more help in this from you. i want to understand and solve this issue from myself. @tokers

**Comment by tokers** [comment]
@iamayushdas Sure, assigned to you.

**Comment by iamayushdas** [comment]
Could you elaborate me like in which file i have to make changes or something like that. Please

**Comment by tokers** [comment]
@iamayushdas The related files are

* https://github.com/apache/apisix/blob/master/apisix/plugins/serverless-pre-function.lua
* https://github.com/apache/apisix/blob/master/apisix/plugins/serverless-post-function.lua

See http://apisix.apache.org/docs/apisix/plugins/serverless for more details.

**Comment by spacewander** [comment]
Consider solved
