### ISSUE TITLE
request help: Error: Could not satisfy dependency lua-resty-hmac-ffi 0.05: No results matching query were found for Lua 5.3. make: *** [Makefile:67: deps] Error 1

### ISSUE THREAD

**Issue by JackLiMEM** [apache/apisix#3859]
### Issue description
Error: Could not satisfy dependency lua-resty-hmac-ffi 0.05: No results matching query were found for Lua 5.3.
make: *** [Makefile:67: deps] Error 1
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
You should provide your environmental information and installation steps.

**Comment by anyforever** [comment]
我也出现这个问题，Centos 8下编译。
开始装的lua 5.4，提示不行，退回了5.3，然后
$ cd apisix
$ make deps
时，出现此报错
`
Error: Could not satisfy dependency lua-resty-hmac-ffi 0.05: No results matching query were found for Lua 5.3.
make: *** [Makefile:67: deps] Error 1
`

我直接安装这个依赖，也是如此
[root@Centos apisix-2.4]# luarocks install lua-resty-hmac-ffi

Error: No results matching query were found for Lua 5.3.
To check if it is available for other Lua versions, use --check-lua-versions.

搜到了依赖项的页面，标的是lua 5.1
http://luarocks.org/modules/jkeys089/lua-resty-hmac-ffi

**Comment by Firstsawyou** [comment]
The installation of lua-resty-hmac-ffi depends on lua 5.1, try to install lua 5.1 .

**Comment by spacewander** [comment]
Only Lua 5.1 or LuaJIT is supported. See https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md

**Comment by szqm123** [comment]
1、重新编译luarocks，安装luarocks时选择luajit作为lua编译器，不要使用lua5.3或者5.4。
进入luarocks目录：
./configure  --with-lua=/usr/local/openresty/luajit  --lua-suffix=jit  --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
make&make install
2、进入apisix目录
make deps

**Comment by anyforever** [comment]
没想到apisix这么难装。。一堆依赖，各种报错。。上面的问题解决了，又出现新的。解决了一个又一个，解决了好几个了，懒得搞了，放弃了。
`
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl111/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [Makefile:79: deps] Error 1
`

**Comment by Firstsawyou** [comment]
> 没想到apisix这么难装。。一堆依赖，各种报错。。上面的问题解决了，又出现新的。解决了一个又一个，解决了好几个了，懒得搞了，放弃了。
> `Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL No file openssl/ssl.h in /usr/local/openresty/openssl111/include You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command. Example: luarocks install luasec OPENSSL_DIR=/usr/local make: *** [Makefile:79: deps] Error 1`

Refer to the document here, it should solve your problem: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#why-does-the-make-deps-command-fail-in-source-installation
