### ISSUE TITLE
bug: Upstream SNI should also be rewritten when the upstream host is rewritten

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3864]
### Issue description

Currently, when the upstream host is changed (by `proxy-rewrite plugin, or the Host rewrite policy in Upstream), the SNI passed to Upstream is not changed when the scheme is HTTPS. That might introduce some SSL handshaking problem, we may fix it.

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

**Comment by membphis** [comment]
How to fix it? Are there any guides?

**Comment by tokers** [comment]
> How to fix it? Are there any guides?

We should set the `proxy_ssl_name` directive with the `upstream_host` variable.

```nginx
proxy_ssl_name $upstream_host;
```

Currently, the value of `proxy_ssl_name` is `$host`, which won't be changed even if the host to upstream was rewritten.

**Comment by membphis** [comment]
I think this issue can be a `good first issue`, right?

**Comment by tokers** [comment]
Yep.
