### ISSUE TITLE
docs: add more example about how to use the router `radixtree-uri`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#3873]
for examples:

> eg:

1. different routes with the same values.
2. different routes with the same URI, eg: `/*`.
3. different routes with different URI, eg: `/test/*`, `/*`.

help the user to know how to use APISIX

**Comment by membphis** [comment]
related issue https://github.com/apache/apisix/issues/3865

**Comment by Firstsawyou** [comment]
Assigned to me.
