### ISSUE TITLE
request help: If the etcd cluster is down, is there any way for APISIX to start normally and get the configured data

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#3878]
### Issue description
If the etcd cluster is down, is there any way for APISIX to start normally and get the configured data.

**Comment by spacewander** [comment]
No. If people use etcd as the data source and it is down, there is no other way to get the configured data.

**Comment by aiyiyi121** [comment]
I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？

**Comment by aiyiyi121** [comment]
> No. If people use etcd as the data source and it is down, there is no other way to get the configured data.

I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？

**Comment by aiyiyi121** [comment]
> No. If people use etcd as the data source and it is down, there is no other way to get the configured data.

I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？
