### ISSUE TITLE
is it optional to enable TLS when installing APISIX on MacOS?

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3879]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, I noticed that when installing Apache APISIX in MacOS, it seems that it's required to enable TLS[1] 🤔 not as Debian does.

![image](https://user-images.githubusercontent.com/2106987/111958755-92a26100-8b28-11eb-8c34-5c90d923da23.png)

Just to make sure, is it optional or required?

[1] https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md#mac-osx

**Comment by spacewander** [comment]
IMHO, we can remove it. Enabling TLS will require extra configuration, and such a change in the dev environment is not so helpful.

**Comment by juzhiyuan** [comment]
agree +1

**Comment by tokers** [comment]
@juzhiyuan This issue could be a "good first issue".
