### ISSUE TITLE
request help: I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#3880]
### Issue description
I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？

**Comment by Firstsawyou** [comment]
> ### Issue description
> I see proxy_cache.disk_path: "/tmp/disk_cache_one" in the config.yaml, this is the path to store the cache data, but why I can't find anything in the /tmp/disk_cache_one path？

This is the path used by the proxy-cache plugin to store cached data. Only after you enable the proxy-cache plug-in can you see the existence of data. You can refer to it here: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md

**Comment by aiyiyi121** [comment]
> This is the path used by the proxy-cache plugin to store cached data. Only after you enable the proxy-cache plug-in can you see the existence of data. You can refer to it here: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md

Thx, I mistook this for the config of caching etcd data，so，where can I find sonmething abouting caching etcd data？

**Comment by tokers** [comment]
> > This is the path used by the proxy-cache plugin to store cached data. Only after you enable the proxy-cache plug-in can you see the existence of data. You can refer to it here: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md
> 
> Thx, I mistook this for the config of caching etcd data，so，where can I find sonmething abouting caching etcd data？

ETCD data caching is in memory, not in filesystem.

**Comment by aiyiyi121** [comment]
> ETCD data caching is in memory, not in filesystem.

What is the etcd data cache interval, or it's real-time watching?

**Comment by Firstsawyou** [comment]
> What is the etcd data cache interval, or it's real-time watching?

It is monitored in real time, you can refer to here:
https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-does-apisix-use-etcd-to-achieve-millisecond-level-configuration-synchronization

**Comment by aiyiyi121** [comment]
> It is monitored in real time, you can refer to here:
> https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-does-apisix-use-etcd-to-achieve-millisecond-level-configuration-synchronization

Thanks a lot.
