### ISSUE TITLE
add a proper link to README item

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3882]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

I noticed that there has one item without a proper link[1], anyone would like to fix it?

![image](https://user-images.githubusercontent.com/2106987/112072983-063a8180-8bae-11eb-84dc-da7664a65e10.png)

[1] https://github.com/apache/apisix/blob/master/README.md

**Comment by stu01509** [comment]
Let me fix it 🙂
