### ISSUE TITLE
request help: Modify the ctx.var.upstream_uri does not work in access phase when i use proxy-rewrite plugin

### ISSUE THREAD

**Issue by comedown** [apache/apisix#3885]
### Issue description
After proxy-rewrite plugin is executed, i add the following line of code to modify the request parameters, but it does not work.
api_ctx.var.upstream_uri = "/test/urlencoded"

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS (cmd: `uname -a`): MacOS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): V3

**Comment by spacewander** [comment]
We don't answer questions caused by modifying APISIX.
You need to debug your change by yourself.
