### ISSUE TITLE
bug: Execute "make deps" prompt "Could not find header file for OPENSSL"

### ISSUE THREAD

**Issue by Caelebs** [apache/apisix#3886]
### Issue description

When I compiled and installed apisix2.4, I executed `make deps` and prompted "Could not find header file for OPENSSL"
The complete error message is as follows
```
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [deps] 
```
I checked that openssl is installed, Including openresty-openssl111
```
[root@TEST3 /0322/23/apisix] -> rpm -qa | grep -i openresty
openresty-openssl111-devel-1.1.1i-1.el7.x86_64
openresty-zlib-1.2.11-3.el7.centos.x86_64
openresty-pcre-8.44-1.el7.x86_64
openresty-openssl111-1.1.1i-1.el7.x86_64
openresty-1.17.8.2-1.el7.x86_64
```
```
[root@TEST3 /0322/23/apisix] -> find / -name ssl.h
/root/.cache/node-gyp/12.16.1/include/node/openssl/ssl.h
/usr/local/openresty/openssl111/include/openssl/ssl.h
/opt/node-v12.16.1-linux-x64/include/node/openssl/ssl.
```
According to the error, I executed `luarocks install luasec OPENSSL_DIR=/usr/local`, and modified OPENSSL_DIR to `/usr/local/openresty/openssl111/`, this step can be successful, But subsequent execution of `make deps` will still prompt the same error, So what should I do now?

```
[root@TEST3 /0322/23/apisix] -> luarocks install luasec OPENSSL_DIR=/usr/local/openresty/openssl111/
Installing https://luarocks.org/luasec-1.0-1.src.rock...
Using https://luarocks.org/luasec-1.0-1.src.rock... switching to 'build' mode
gcc -O2 -fPIC -I/usr/include -c src/options.c -o src/options.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/config.c -o src/config.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/ec.c -o src/ec.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/x509.c -o src/x509.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/context.c -o src/context.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/ssl.c -o src/ssl.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/luasocket/buffer.c -o src/luasocket/buffer.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/luasocket/io.c -o src/luasocket/io.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/luasocket/timeout.c -o src/luasocket/timeout.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -O2 -fPIC -I/usr/include -c src/luasocket/usocket.c -o src/luasocket/usocket.o -DWITH_LUASOCKET -DLUASOCKET_DEBUG -I/usr/local/openresty/openssl111/include -Isrc/ -Isrc/luasocket
gcc -shared -o ssl.so -L/usr/lib64/lua src/options.o src/config.o src/ec.o src/x509.o src/context.o src/ssl.o src/luasocket/buffer.o src/luasocket/io.o src/luasocket/timeout.o src/luasocket/usocket.o -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/openssl111/lib: -lssl -lcrypto
Updating manifest for /usr/lib64/luarocks/rocks
luasec 1.0-1 is now built and installed in /usr (license: MIT)
```

### Environment
* apisix version (cmd: `apisix version`): `2.4`
* OS (cmd: `uname -a`): `CentOS Linux release 7.6.1810 (Core)`
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): `openresty/1.17.8.2`
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
Could you show us the output of `luarocks config variables`?

**Comment by Caelebs** [comment]
Sorry, I don't know the usage of this command. According to the -h prompt, I executed the following commands, I don't know if it's right
```
[root@TEST3 /0322/23/apisix] -> luarocks config --lua-ver
5.1
[root@TEST3 /0322/23/apisix] -> luarocks config --system-config
/etc/luarocks/config-5.1.lua
[root@TEST3 /0322/23/apisix] -> luarocks config --lua-incdir
/usr/include
[root@TEST3 /0322/23/apisix] -> luarocks config --lua-libdir
/usr/lib64/lua
[root@TEST3 /0322/23/apisix] -> luarocks config --rock-trees
/root/.luarocks	user
/usr	system
[root@TEST3 /0322/23/apisix] -> luarocks config --user-config
/root/.luarocks/config-5.1.lua

Error: file not found
```
@spacewander

**Comment by Caelebs** [comment]
Before that, according to the commands in the install-dependencies.md document, I installed `openresty-openssl111-devel`, But I just found out that the document says "If you are using OpenResty which is older than `1.17.8`, please installing `openresty-openss-devel` instead of `openresty-openssl111-devel`", but in the following example , The command given is to install `openresty-openssl111-devel`? Is the document description wrong?
But after I installed `openresty-openssl-devel`, executing `make deps` still prompted "Could not find header file for OPENSSL"
```
[root@TEST3 /0322/23/apisix] -> rpm -qa | grep openssl
openresty-openssl111-devel-1.1.1i-1.el7.x86_64
openssl-libs-1.0.2k-16.el7.x86_64
openresty-openssl111-1.1.1i-1.el7.x86_64
openresty-openssl-1.1.0l-2.el7.x86_64
openresty-openssl-devel-1.1.0l-2.el7.x86_64
openssl-1.0.2k-16.el7.x86_64
```

**Comment by spacewander** [comment]
> 
> 
> Sorry, I don't know the usage of this command. According to the -h prompt, I executed the following commands, I don't know if it's right
> 
> ```
> [root@TEST3 /0322/23/apisix] -> luarocks config --lua-ver
> 5.1
> [root@TEST3 /0322/23/apisix] -> luarocks config --system-config
> /etc/luarocks/config-5.1.lua
> [root@TEST3 /0322/23/apisix] -> luarocks config --lua-incdir
> /usr/include
> [root@TEST3 /0322/23/apisix] -> luarocks config --lua-libdir
> /usr/lib64/lua
> [root@TEST3 /0322/23/apisix] -> luarocks config --rock-trees
> /root/.luarocks	user
> /usr	system
> [root@TEST3 /0322/23/apisix] -> luarocks config --user-config
> /root/.luarocks/config-5.1.lua
> 
> Error: file not found
> ```
> 
> @spacewander

Run it like this:
```
 incubator-apisix (bdt) 0
 ￥ luarocks config variables
{
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
```

**Comment by Firstsawyou** [comment]
This seems to be caused by the lack of the openssl development kit of openresty. https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#why-does-the-make-deps-command-fail-in-source-installation

**Comment by Caelebs** [comment]
I run the command `luarocks config variables` directly, it will prompt error and did not get your output
```
[root@TEST3 /0322/23/apisix] -> luarocks config variables

Error: Please provide a flag for querying configuration values. See '/usr/bin/luarocks help config'.
```

I have compiled and installed apisix2.2 version before on this machine, These errors did not appear at the time. The document requires `openresty-openssl-devel` to be installed instead of ` openresty-openssl111-devel`, so I have uninstalled `openresty-openssl111-devel`, but the error still persists

```
[root@TEST3 /0322/23/apisix] -> rpm -qa | grep -i openssl
openssl-libs-1.0.2k-16.el7.x86_64
openresty-openssl111-1.1.1i-1.el7.x86_64
openresty-openssl-1.1.0l-2.el7.x86_64
openresty-openssl-devel-1.1.0l-2.el7.x86_64
openssl-1.0.2k-16.el7.x86_64
```

@spacewander @Firstsawyou

**Comment by spacewander** [comment]
> Error: Please provide a flag for querying configuration values. See '/usr/bin/luarocks help config'.

I guess you are using luarocks 2.x?
If it is, please upgrade it to 3.x. You can take advantage of this script: https://github.com/apache/apisix/blob/master/utils/linux-install-luarocks.sh

**Comment by Caelebs** [comment]
The current situation is that I reinstalled the openresty-openssl111-devel that I uninstalled before, executed the script you gave, and I checked that the variables set in it are normal
```
variables = {
   OPENSSL_INCDIR = "/usr/local/openresty/openssl111/include",
   OPENSSL_LIBDIR = "/usr/local/openresty/openssl111/lib"
}

```
But when I execute make deps, I don't quite understand what is wrong with the prompt message given.
```
[root@TEST3 /0322/23/apisix] -> make deps
mkdir -p ~/.luarocks
luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl111/lib
Wrote
	variables.OPENSSL_LIBDIR = "/usr/local/openresty/openssl111/lib"
to
	/root/.luarocks/config-5.1.lua
luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl111/include
Wrote
	variables.OPENSSL_INCDIR = "/usr/local/openresty/openssl111/include"
to
	/root/.luarocks/config-5.1.lua
luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local

apisix master-0 depends on lua-resty-ctxdump 0.1-0 (0.1-0 installed)
apisix master-0 depends on lua-resty-dns-client 5.2.0 (5.2.0-1 installed)
apisix master-0 depends on lua-resty-template 1.9 (1.9-1 installed)
apisix master-0 depends on lua-resty-etcd 1.4.3 (1.4.3-0 installed)
apisix master-0 depends on lua-resty-balancer 0.02rc5 (0.02rc5-0 installed)
apisix master-0 depends on lua-resty-ngxvar 0.5.2 (0.5.2-0 installed)
apisix master-0 depends on lua-resty-jit-uuid 0.0.7 (0.0.7-2 installed)
apisix master-0 depends on lua-resty-healthcheck-api7 2.2.0 (2.2.0-0 installed)
apisix master-0 depends on lua-resty-jwt 0.2.0 (0.2.0-0 installed)
apisix master-0 depends on lua-resty-hmac-ffi 0.05 (0.05-0 installed)
apisix master-0 depends on lua-resty-cookie 0.1.0 (0.1.0-1 installed)
apisix master-0 depends on lua-resty-session 2.24 (2.24-1 installed)
apisix master-0 depends on opentracing-openresty 0.1 (0.1-0 installed)
apisix master-0 depends on lua-resty-radixtree 2.7.0 (2.7.0-0 installed)
apisix master-0 depends on lua-protobuf 0.3.1 (0.3.1-0 installed)
apisix master-0 depends on lua-resty-openidc 1.7.2-1 (1.7.2-1 installed)
apisix master-0 depends on luafilesystem 1.7.0-2 (1.7.0-2 installed)
apisix master-0 depends on lua-tinyyaml 1.0 (1.0-0 installed)
apisix master-0 depends on nginx-lua-prometheus 0.20201218 (0.20201218-1 installed)
apisix master-0 depends on jsonschema 0.9.4 (0.9.4-0 installed)
apisix master-0 depends on lua-resty-ipmatcher 0.6 (0.6-0 installed)
apisix master-0 depends on lua-resty-kafka 0.07 (0.07-0 installed)
apisix master-0 depends on lua-resty-logger-socket 2.0-0 (2.0-0 installed)
apisix master-0 depends on skywalking-nginx-lua 0.4-1 (0.4-1 installed)
apisix master-0 depends on base64 1.5-2 (1.5-2 installed)
apisix master-0 depends on binaryheap 0.4 (0.4-1 installed)
apisix master-0 depends on dkjson 2.5-2 (2.5-2 installed)
apisix master-0 depends on resty-redis-cluster 1.02-4 (1.02-4 installed)
apisix master-0 depends on lua-resty-expr 1.2.0 (1.2.0-0 installed)
apisix master-0 depends on graphql 0.0.2 (0.0.2-1 installed)
apisix master-0 depends on argparse 0.7.1-1 (0.7.1-1 installed)
apisix master-0 depends on luasocket 3.0rc1-2 (3.0rc1-2 installed)
apisix master-0 depends on luasec 0.9-1 (0.9-1 installed)
apisix master-0 depends on lua-resty-consul 0.3-2 (0.3-2 installed)
apisix master-0 depends on penlight 1.9.2-1 (1.9.2-1 installed)
Stopping after installing dependencies for apisix master-0

[root@TEST3 /0322/23/apisix] ->
```

**Comment by Firstsawyou** [comment]
> But when I execute make deps, I don't quite understand what is wrong with the prompt message given.
> 
> ```
> [root@TEST3 /0322/23/apisix] -> make deps
> mkdir -p ~/.luarocks
> luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl111/lib
> Wrote
> 	variables.OPENSSL_LIBDIR = "/usr/local/openresty/openssl111/lib"
> to
> 	/root/.luarocks/config-5.1.lua
> luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl111/include
> Wrote
> 	variables.OPENSSL_INCDIR = "/usr/local/openresty/openssl111/include"
> to
> 	/root/.luarocks/config-5.1.lua
> luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local
> 
> apisix master-0 depends on lua-resty-ctxdump 0.1-0 (0.1-0 installed)
>........
> ```

According to the information you provided, the `make deps` command has been executed successfully.
The following messages are configuring your environment information and installing dependent packages.

**Comment by Caelebs** [comment]
Thanks for the reply, apisix is now able to start
@Firstsawyou @spacewander
