### ISSUE TITLE
request help: Can I set timeout for each route?

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3888]
### Issue description
Nginx has a series of timeout settings, such as `proxy_connect_timeout`、`proxy_read_timeout`. These settings are valid for all the connections. Can I set these params to a large value (say 3600s), and then control timeout (say 60s) for each route?

### Environment

* apisix version (cmd: `apisix version`): 2.3

**Comment by Firstsawyou** [comment]
You can refer to the setting of the `timeout` field in upstream:  https://github.com/apache/apisix/blob/2.4/docs/en/latest/admin-api.md#upstream

**Comment by diaosj** [comment]
Thanks. I'll try it.
