### ISSUE TITLE
request help: opentelemetry luajit SDK and intergration with APISIX

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix#3891]
[opentelemetry](https://opentelemetry.io/) as an observability framework for cloud-native software is ♨️.

API Gateway as a network centre handler, it's observability is critical, It will be helpful for APISIX's simplicity connect with open-telemetry.
 
[Golang SDK](https://github.com/open-telemetry/opentelemetry-go)

**Comment by spacewander** [comment]
Where is the opentelemetry luajit SDK?

**Comment by lilien1010** [comment]
Hi  @SomalianIvan  I think this cloud be your first feature to implement, while you own so much context on opentelemerey.

you can follow  https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/skywalking.md & https://github.com/apache/skywalking-nginx-lua

**Comment by lilien1010** [comment]
I  can also help you walk through this.

**Comment by SomalianIvan** [comment]
Hey folks I'll pick it up this Thursday

**Comment by tokers** [comment]
> Hey folks I'll pick it up this Thursday

👍, Assigned to you.

**Comment by tokers** [comment]
@SomalianIvan Any updates :)?

**Comment by yangxikun** [comment]
I am writing an opentelemetry-lua sdk, and will integrate with APISIX.

**Comment by xuminwlt** [comment]
focus the feature
