### ISSUE TITLE
docs: the FAQ document adds how to upgrade APISIX

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3892]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

At present, there is no relevant document to introduce "How to upgrade APISIX", but how to upgrade APISIX is a very common problem, we need to record it in the FAQ document.

**Comment by tokers** [comment]
What about adding a new document like `ops.md` or `admin.md` to describe it elaborately.

**Comment by Firstsawyou** [comment]
> What about adding a new document like `ops.md` or `admin.md` to describe it elaborately.

This is a good idea, I agree.
