### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by ZanderMo** [apache/apisix#3904]
### Environment

* apisix version (cmd: `apisix version`): v2.2
config_center: yaml 

apisix.yaml 配置 :
routes:
  - uri: /systemconf/admin/*
    upstream_id: 8014
    plugins:
      jwt-auth: {}
     consumer-restriction: {
            whitelist: [
                admin
            ]
        }  
consumers:
  - username: admin
    plugins:
      jwt-auth:
        key: admin
        secret: 123
  - username: app
    plugins:
      jwt-auth:
        key: app
        secret: 123

jwt的key无论用admin还是app都提示
{"message":"The consumer_name is forbidden."}

**Comment by spacewander** [comment]
Fixed by https://github.com/apache/apisix/pull/3394
