### ISSUE TITLE
request help:  upstream healthy check with http upstream server no access log

### ISSUE THREAD

**Issue by Yangzcy423911** [apache/apisix#3916]
### Environment

* apisix version (cmd: `apisix version`):2.2
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

upstream  info

{
    "node": {
        "value": {
            "update_time": 1616730666,
            "id": "340800355065398158",
            "name": "test",
            "checks": {
                "active": {
                    "host": "www.host.com",
                    "port": 80,
                    "http_path": "/api/actuator/health",
                    "healthy": {
                        "interval": 2,
                        "successes": 1
                    },
                    "unhealthy": {
                        "http_failures": 3,
                        "interval": 2
                    },
                    "timeout": 3
                }
            },
            "nodes": [
                {
                    "host": "192.168.1.100",
                    "port": 8080,
                    "weight": 0
                },
                {
                    "host": "192.168.1.200",
                    "port": 8080,
                    "weight": 1
                }
            ],
            "timeout": {
                "connect": 6000,
                "send": 6000,
                "read": 6000
            },
            "type": "roundrobin",
            "create_time": 1612662441,
            "desc": "test",
            "pass_host": "pass"
        },
        "key": "/apisix/upstreams/340800355065398158"
    },
    "count": "1",
    "action": "get"
}

use curl cmd

curl http://www.host.com:80/api/actuator/health
{"status":"UP"}

upstream  server log 
2021-03-26 13:06:12.310 INFO com.host.com.check -/actuator/health

**Comment by Firstsawyou** [comment]
According to your configuration, in the active detection, you set `"port": 80`, it will overwrite the `8080` port in your upstream node, is the port of the service you want to detect at the back-end is `80`?

**Comment by Yangzcy423911** [comment]
The port of upstream service is not 8080, but 8080. How to understand the host here

**Comment by Yangzcy423911** [comment]
What is the significance of health detection here? If it is detected periodically, upstream services should have corresponding logs

**Comment by Firstsawyou** [comment]
You can refer to the health check example here. If you can see the related health check log in the log, the upstream service will also have the related log.  https://github.com/apache/apisix/issues/3616#issuecomment-783179886

**Comment by Firstsawyou** [comment]
> How to understand the host here

The `host` in the active health check is the host that periodically initiates http requests to detect whether the upstream is healthy. For specific information, you can refer to here:  https://github.com/apache/apisix/blob/master/docs/en/latest/health-check.md

**Comment by Yangzcy423911** [comment]
If the host here uses the domain name method and then specifies the port, can it replace the address of the upstream node and the corresponding port for health status detection
