### ISSUE TITLE
request help: question about Prometheus memory consumption

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#3917]
### Issue description

I noticed this message in `logs/error.log`:
```
2021/03/26 14:37:26 [error] 38#38: *130656606 [lua] prometheus.lua:732: log_error(): Unexpected error adding a key: no memory while logging request
```

I guess the memory for Prometheus metrics has an upbound limit. What is that value? I may need to config more memory for APISIX.

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1

**Comment by spacewander** [comment]
https://github.com/apache/apisix/blob/83931ba0a5c95e04ec867a4ffd0821d426ca0d27/apisix/cli/ngx_tpl.lua#L131

I would appreciate it if you can make it configurable.

**Comment by diaosj** [comment]
> https://github.com/apache/apisix/blob/83931ba0a5c95e04ec867a4ffd0821d426ca0d27/apisix/cli/ngx_tpl.lua#L131
> 
> I would appreciate it if you can make it configurable.

Thanks! 
Looks like I can config it in `config-default.yaml`. I will try this.

**Comment by Applenice** [comment]
I was trying to solve this issue and when testing I found the problem:
https://github.com/apache/apisix/blob/e35ef6d54469a312b209bf60b194eca50938ebbe/apisix/cli/ngx_tpl.lua#L144
https://github.com/apache/apisix/blob/e35ef6d54469a312b209bf60b194eca50938ebbe/apisix/cli/ngx_tpl.lua#L145

It can be modified like this:
```
lua_shared_dict internal_status      {* http.lua_shared_dict.internal_status *};
```
But it seems to be because this format of `plugin-limit-req` does not conform to the lexical conventions of Lua names. An error is reported:
```
/usr/local/openresty/luajit/bin/luajit: [string "context=... or {}..."]:289: attempt to perform arithmetic on field 'plugin' (a nil value)
```
Can I change the lua_shared_dict variable that uses `-` to `_`? This way the relevant code needs to be modified.

**Comment by Yiyiyimu** [comment]
Hi @Applenice I think it would import no breaking changes so it's good to go~

**Comment by Applenice** [comment]
> Hi @Applenice I think it would import no breaking changes so it's good to go~

Okay, I'll fix it.😃

**Comment by tokers** [comment]
@Applenice Have you tried this:

```yaml
lua_shared_dict internal_status      {* http.lua_shared_dict["plugin-limit-req"] *};
```

**Comment by Applenice** [comment]
> @Applenice Have you tried this:
> 
> ```yaml
> lua_shared_dict internal_status      {* http.lua_shared_dict["plugin-limit-req"] *};
> ```

I just tested this way of writing and it does work. I learned.

So do I need to change the PR content? Would it be better to keep one style?😃 Personally, I think it's a bit strange to have two ways of handling the same feature because of different naming formats. Of course my idea may not be the best.

**Comment by spacewander** [comment]
What about configuring with the original dash style?

**Comment by Applenice** [comment]
> What about configuring with the original dash style?

Agree, so that it can be consistent with the naming of the plugin.😊

**Comment by suninuni** [comment]
When I set prometheus-metrics as 100m in configmap apisix, apisix throw an error about key conflicted.

```ynl
     http:
        lua_shared_dicts:              # add custom shared cache to nginx.conf
          prometheus-metrics: 100m 
```

```shell
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
WARNING: using fixed Admin API token has security risk.
Please modify "admin_key" in conf/config.yaml .
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2021/09/16 08:28:56 [emerg] 1#1: the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64
nginx: [emerg] the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64

```

**Comment by tzssangglass** [comment]
> When I set prometheus-metrics as 100m in configmap apisix, apisix throw an error about key conflicted.
> 
> Apisix version is 2.7
> 
> ```
>      http:
>         lua_shared_dicts:              # add custom shared cache to nginx.conf
>           prometheus-metrics: 100m 
> ```
> 
> ```shell
> /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
> WARNING: using fixed Admin API token has security risk.
> Please modify "admin_key" in conf/config.yaml .
> /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
> 2021/09/16 08:28:56 [emerg] 1#1: the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64
> nginx: [emerg] the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64
> ```

This has nothing to do with 100m, the error logs have clearly indicated this to you.

the shared dict `prometheus-metrics` has been already defined, see: https://github.com/apache/apisix/blob/d6c09fba6543c9fc28520ef7172596a01417222f/apisix/cli/ngx_tpl.lua#L171

so you can not define shared dict with the same name(`prometheus-metrics`) in a custom configuration.

**Comment by suninuni** [comment]
> > When I set prometheus-metrics as 100m in configmap apisix, apisix throw an error about key conflicted.
> > Apisix version is 2.7
> > ```
> >      http:
> >         lua_shared_dicts:              # add custom shared cache to nginx.conf
> >           prometheus-metrics: 100m 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```shell
> > /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
> > WARNING: using fixed Admin API token has security risk.
> > Please modify "admin_key" in conf/config.yaml .
> > /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
> > 2021/09/16 08:28:56 [emerg] 1#1: the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64
> > nginx: [emerg] the size 104857600 of shared memory zone "prometheus-metrics" conflicts with already declared size 10485760 in /usr/local/apisix/conf/nginx.conf:64
> > ```
> 
> This has nothing to do with 100m, the error logs have clearly indicated this to you.
> 
> the shared dict `prometheus-metrics` has been already defined, see:
> 
> https://github.com/apache/apisix/blob/d6c09fba6543c9fc28520ef7172596a01417222f/apisix/cli/ngx_tpl.lua#L171
> 
> so you can not define shared dict with the same name(`prometheus-metrics`) in a custom configuration.

I find this key (prometheus-metrics) in config-default.yml, and I want overwrite this value to 100m, so I add these configuration in configmap which will be volumed as config,yml.

https://github.com/apache/apisix/blob/e127cc7a43416673f4b0c77db1ecf09a191abcb8/conf/config-default.yaml#L212-L216

So if I want to overwrite this key (prometheus-metircs) to 100m, where should I modify?

**Comment by tzssangglass** [comment]
try

```
apisix:
  http:
    lua_shared_dict:
      prometheus-metrics: 10m
```

in `config.yaml`

**Comment by suninuni** [comment]
> try
> 
> ```
> apisix:
>   http:
>     lua_shared_dict:
>       prometheus-metrics: 10m
> ```
> 
> in `config.yaml`


I set this to 100m both in `apisix.http.lua_shared_dict.prometheus-metrics` AND `nginx_config.http.lua_shared_dict.prometheus-metrics`, but value in conf/nginx.conf is still be 10m.

![image](https://user-images.githubusercontent.com/7345529/133736903-9a8c420e-956f-4ae7-a1b0-dbd2ba1d7298.png)

**Comment by suninuni** [comment]
And another question is can this completely solve the problem? In my opinion, expanding this value can only alleviate this problem, not solve it. If the memory is full, shouldn't it release part of it? 

In my test, this error will continue to appear after the memory is full, and it seems that no request can continue to be recorded. And the memory of the apisix pod will continue to grow, even to 900m. Although I am not sure if it is caused by this problem, it seems that there is something wrong.

**Comment by tzssangglass** [comment]
> And another question is can this completely solve the problem? In my opinion, expanding this value can only alleviate this problem, not solve it. If the memory is full, shouldn't it release part of it?
> 
> In my test, this error will continue to appear after the memory is full, and it seems that no request can continue to be recorded. And the memory of the apisix pod will continue to grow, even to 900m. Although I am not sure if it is caused by this problem, it seems that there is something wrong.
> 
> ![image](https://user-images.githubusercontent.com/7345529/133738979-0b08f719-26f7-477c-a71b-727d83e41406.png)

pls submit another PR and show steps to reproduce
