### ISSUE TITLE
request help: timer enhancement

### ISSUE THREAD

**Issue by whl739** [apache/apisix#3923]
Currently, apisix provides a background timer for logger related plugins, whitch is not universal.

See this demand: a plugin may register a timer in `init` function, the timer will be recurring to pull data, and unregister it in `destroy` function, the phase functions may use these pulled data. But the current timer implemention is not possible to do that.

How can i do this, any suggestions?

**Comment by spacewander** [comment]
The timer is not logger only, we can use it in other plugins too. See:
https://github.com/apache/apisix/blob/c9df9fca652d14d32c8331820640ed9344c4529a/apisix/plugins/server-info.lua#L241

**Comment by whl739** [comment]
The background timer can not set a interval time, and the callback function have to check the time by itself, it's not easy to use.
It's implemention is that spawn registed timer threads, and wait them to finish, if one timer cost too much time, other timers will be affected.

**Comment by spacewander** [comment]
> The background timer can not set a interval time, and the callback function have to check the time by itself, it's not easy to use.

Yes, as OpenResty doesn't provide a cancel_timer API, we have to do the "cancel" job in the callback.

> if one timer cost too much time, other timers will be affected

Not exactly. The `core.timer` use `timer.every` API, so each group of timers' fire time is not affected by the last timer group. And each timer in the same group is run in a separate thread.

**Comment by whl739** [comment]
But also `core.timer` provides `self.running` to prevent callback function to run repeatly, timers are still affected.

**Comment by spacewander** [comment]
Yes, you are right.
We can add an option to override this behavior and use it in the background timer.
PR is welcome!

**Comment by whl739** [comment]
What about [lua-resty-timer](https://github.com/Kong/lua-resty-timer) from Kong?

**Comment by spacewander** [comment]
I don't think it does much better than ours.

**Comment by spacewander** [comment]
That library only uses `timer.at`, which may fail to run a timer when the memory or the number of connections is not enough. When it failed to start, there is not a second chance.

**Comment by tokers** [comment]
> Yes, you are right.
> We can add an option to override this behavior and use it in the background timer.
> PR is welcome!

This could be a better way, @whl739 Would you please submit a PR to help APISIX to optimize this? Thanks!
