### ISSUE TITLE
redirect plugins add curl test for `http_to_https`

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3931]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

The [document](http://apisix.apache.org/docs/apisix/plugins/redirect) about redirect plugin contains the configuration about using `http_to_https` in redirect plugin, but it doesn't add a curl test case to show the result.

![image](https://user-images.githubusercontent.com/10428333/112805052-afe6aa80-90a7-11eb-9b4e-c19d33c9a55c.png)

## Describe the solution you'd like

We should add a curl test case to show that a request is really redirected since the scheme is `HTTP`.

**Comment by kartikeysaran** [comment]
Hey ! Is this issue still unresolved ?

**Comment by tzssangglass** [comment]
> 嘿 ！这个问题还没有解决吗？

PR is welcome!

**Comment by leslie-tsang** [comment]
AFAIK, @kartikeysaran , not yet, would you have a try ?

**Comment by kartikeysaran** [comment]
Yeah sure

**Comment by tzssangglass** [comment]
hi @kartikeysaran, assigned you

**Comment by leslie-tsang** [comment]
@kartikeysaran Hi there, Are there any issues that are preventing you from moving forward?

Do let me know if any help in needed.

**Comment by mangoGoForward** [comment]
I tested it like this:

1. Create a route

```bash
$ curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "plugins": {
        "redirect": {
            "http_to_https": true
        }
    }
}'
```

2. Test.

```bash
$ curl http://127.0.0.1:9080/hello -i
HTTP/1.1 301 Moved Permanently
Date: Fri, 18 Feb 2022 07:48:32 GMT
Content-Type: text/html
Content-Length: 166
Connection: keep-alive
Location: https://127.0.0.1/hello
Server: APISIX/2.12.0

<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

How about add the second step to the [redirect document](http://apisix.apache.org/docs/apisix/plugins/redirect)? @tzssangglass @leslie-tsang

**Comment by leslie-tsang** [comment]
> I tested it like this:
> 
> 1. Create a route
> 
> ```shell
> $ curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/hello",
>     "plugins": {
>         "redirect": {
>             "http_to_https": true
>         }
>     }
> }'
> ```
> 
> 2. Test.
> 
> ```shell
> $ curl http://127.0.0.1:9080/hello -i
> HTTP/1.1 301 Moved Permanently
> Date: Fri, 18 Feb 2022 07:48:32 GMT
> Content-Type: text/html
> Content-Length: 166
> Connection: keep-alive
> Location: https://127.0.0.1/hello
> Server: APISIX/2.12.0
> 
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body>
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>openresty</center>
> </body>
> </html>
> ```
> 
> How about add the second step to the [redirect document](http://apisix.apache.org/docs/apisix/plugins/redirect)? @tzssangglass @leslie-tsang

LGTM, don't forget to reduce the unnecessary info in the output.

eg:
```bash
$ curl http://127.0.0.1:9080/hello -i
HTTP/1.1 301 Moved Permanently
...
Location: https://127.0.0.1/hello
...
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by mangoGoForward** [comment]
> LGTM, don't forget to reduce the unnecessary info in the output.
> 
> eg:
> 
> ```shell
> $ curl http://127.0.0.1:9080/hello -i
> HTTP/1.1 301 Moved Permanently
> ...
> Location: https://127.0.0.1/hello
> ...
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body>
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>openresty</center>
> </body>
> </html>
> ```

@soltysh are you working on this issue already? If not I'd like to tackle this issue :)
