### ISSUE TITLE
request help: Specify an upstream and remove it from all routes

### ISSUE THREAD

**Issue by hackeryutu** [apache/apisix#3935]
### Issue description
request help: Specify an upstream and remove it from all routes
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by tokers** [comment]
@hackeryutu You don't show your problems.

**Comment by Firstsawyou** [comment]
Hi, @hackeryutu 
According to the current description, we do not know what your problem is, you need to describe your problem clearly.
