### ISSUE TITLE
request help: How to proxy to a third-party website by developing a plug-in?

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#3942]
### Issue description
If inscribe.
for example:  when access `http://ip:port`，proxy to `https://github.com`：
  location / {
      proxy_pass  https://github.com;
      proxy_redirect     off;
      proxy_set_header   Host             $host;
      proxy_set_header   X-Real-IP        $remote_addr;
      proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
  }

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by moonming** [comment]
@kongjun01 
Please use English in the public channel, thx

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#upstream. You need to use the domain name as the `nodes`.
