### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by zwjzxh520** [apache/apisix#3944]
### 支持分布式部署吗？分布式部署的时候，限流插件，可以保证正确的工作吗？

查阅了一下源码，发现是用 resty.lrucache 做的缓存，这应该是本机缓存，那假如部署在三台机器，限流配置为每秒 1000 QPS， 会不会导致实际允许 3000 QPS 的流量了

**Comment by Firstsawyou** [comment]
Support cluster deployment. Please refer here: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-set-up-high-available-apache-apisix-clusters
Using the `limit-count` plugin, it can support the current limit of the Redis strategy. https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/limit-count.md#attributes

**Comment by zwjzxh520** [comment]
非常感谢！  limit-conn 和 limit-req 这两个插件还是不支持使用 redis 是吗？后续会有计划支持吗？

**Comment by Firstsawyou** [comment]
> limit-conn 和 limit-req 这两个插件还是不支持使用 redis 是吗？后续会有计划支持吗？

Yes, limit-conn and limit-req plugins do not yet support the use of redis strategies. There is currently no plan to support it. You can create an issue to discuss it.

**Comment by tokers** [comment]
@zwjzxh520 By the way, please use English on public channel, thanks for your cooperation.

**Comment by spacewander** [comment]
Consider solved
