### ISSUE TITLE
request help: How can I use geoip in route

### ISSUE THREAD

**Issue by a0925260369** [apache/apisix#3946]
### Issue description
I want visit different upstreams based on region.
Here is my cmd,  but it doesn't work.
What should I do 
```
curl http://127.0.0.1:9080/apisix/admin/routes/12 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "host": "127.0.0.1",
    "service_id": "1",
    "vars": [
      ["geoip", "==", "CN"]
    ]
}'
```
### Environment

* apisix version (cmd: `apisix version`):2.3 (helm install)
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1 (helm install)
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):(helm install)
* apisix-dashboard version, if have: (helm install)

**Comment by Firstsawyou** [comment]
The `vars` field here configures nginx variables, which does not support `geoip`.

**Comment by a0925260369** [comment]
@Firstsawyou 
From this issue #2180 , apisix can use ```$geoip``` and the ```var``` in route. 
So , I try to set ```geoip``` in ```vars```. This seems to be wrong
Can you tell me how to use ```geoip```?

**Comment by Firstsawyou** [comment]
> From this issue #2180 , apisix can use `$geoip` and the `var` in route.

You try to set `$geoip` in vars. I'm not sure if it can.

**Comment by moonming** [comment]
maybe we need to install ngx_http_geoip_module first?

**Comment by spacewander** [comment]
The `ngx_http_geoip_module` is not a builtin module.
You need to build it by yourself, see http://nginx.org/en/docs/http/ngx_http_geoip_module.html

**Comment by a0925260369** [comment]
> The `ngx_http_geoip_module` is not a builtin module.
> You need to build it by yourself, see http://nginx.org/en/docs/http/ngx_http_geoip_module.html

Thanks, I will try to install it.
After install, can I use $geoip and the var in route?
Like this cmd.
```
curl http://127.0.0.1:9080/apisix/admin/routes/12 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "host": "127.0.0.1",
    "service_id": "1",
    "vars": [
      ["geoip", "==", "CN"]
    ]
}'
```

**Comment by tokers** [comment]
@a0925260369 You may provide some geo files, or Nginx doesn't know any geo information anymore. After that, you can use any variables provided by geo_ip module in APISIX's route `vars`.

**Comment by a0925260369** [comment]
After I build openrestry with geo_ip2 module,  finally I cane use variables provided by geo_ip2 module in APISIX's route vars.
Thanks a lot.
