### ISSUE TITLE
The retry of etcd is missing after replacing curl with luasocket

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#3953]
Previously, there is retry mechanism when the bin/apisix tried to connect etcd cluster:
https://github.com/apache/apisix/blob/e8dcf3793ca40b30047406ac51a79a500356f67b/apisix/cli/etcd.lua#L203

After the curl code was rewritten with luasocket, this mechanism is missing.

In some situation, like a flaky netowork problem, or the health checker has not removed an unhealthy node from the DNS record yet, the retry can reduce the chance that APISIX fails to start.

CC @starsz

**Comment by starsz** [comment]
We do need it.

**Comment by yxudong** [comment]
Hi, I'd like work on this issue.
Please assign it to me.
