### ISSUE TITLE
Translate HTTP request to gRPC

### ISSUE THREAD

**Issue by cz-theng** [apache/apisix#3956]
the [grpc-transcode](https://github.com/apache/apisix/tree/master/apisix/plugins/grpc-transcode) plugin translate HTTP
request to grpc request with HTTP param like "?xxx=yyy". But this soluation make client to constract the URL params.

how about share .pb file with client. and client marshal pb request struct to a bin data , and send request with that data in HTTP's body. then APISix plugin like grpc-transcode need not constract pb request struct , just use HTTP's body as a marshaled pb request,the send requst to gRPC services.

**Comment by spacewander** [comment]
> how about share .pb file with client. and client marshal pb request struct to a bin data , and send request with that data in HTTP's body

This is what a client does when it starts a gRPC call over HTTP2.
