### ISSUE TITLE
proposal: Should apisix support host+path as route? 

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#3959]
### Issue description
Now apisix support hosts and  paths as route, such as this config:

```
a.com
b.com

/a
/b
```

But sometimes we have some business scenario should support host+path as route, such as:
 
```
a.com /a
b.com /b
``` 

I have see the apisix route match radix-tree code, If we implementation this, we should split the route, I think this change is  very big. I have a proposal, should we write a plugin to support it, and in the plugin we create a sub radix-tree which spilt the route as the sub routes. we can use the plugin to do the verification.Or their any other suggestions to implementation it?

### Environment
* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
This is already supported, you can refer to the description of `radixtree_host_uri` here: https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/router.md

**Comment by gy09535** [comment]
> This is already supported, you can refer to the description of `radixtree_host_uri` here: https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/router.md

I have see the 
  'radixtree_host_uri:https://github.com/apache/apisix/blob/master/apisix/http/router/radixtree_host_uri.lua#L79' , I think this can not support the  'host+path' case, because the hosts and paths in route is  two properties, for example :
```
hosts: a.com b.com
path: /a /b
```
their should be four combinations 
```
a.com /a
a.com /b
b.com /a
b.com /b
```
all this situation can hit the route, but I want the route config is 
```
a.com /a 
b.com /b 
```
this just two situation can hit the route, to implementation this situation we should change the route config such as 
```
host_paths:[{
host: a.com,path: /a}
{host:b.com,path:/b} ]
```
this is  not a compatible change.

**Comment by tokers** [comment]
> > This is already supported, you can refer to the description of `radixtree_host_uri` here: https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/router.md
> 
> I have see the
> 'radixtree_host_uri:https://github.com/apache/apisix/blob/master/apisix/http/router/radixtree_host_uri.lua#L79' , I think this can not support the 'host+path' case, because the hosts and paths in route is two properties, for example :
> 
> ```
> hosts: a.com b.com
> path: /a /b
> ```
> 
> their should be four combinations
> 
> ```
> a.com /a
> a.com /b
> b.com /a
> b.com /b
> ```
> 
> all this situation can hit the route, but I want the route config is
> 
> ```
> a.com /a 
> b.com /b 
> ```
> 
> this just two situation can hit the route, to implementation this situation we should change the route config such as
> 
> ```
> host_paths:[{
> host: a.com,path: /a}
> {host:b.com,path:/b} ]
> ```
> 
> this is not a compatible change.

What you want can be achieved by splitting this into two routes. The first route contains host `a.com` and uri `/a`, and
similarly, the second route has host `b.com` and uri `/b`.

**Comment by gy09535** [comment]
> > > This is already supported, you can refer to the description of `radixtree_host_uri` here: https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/router.md
> > 
> > 
> > I have see the
> > 'radixtree_host_uri:https://github.com/apache/apisix/blob/master/apisix/http/router/radixtree_host_uri.lua#L79' , I think this can not support the 'host+path' case, because the hosts and paths in route is two properties, for example :
> > ```
> > hosts: a.com b.com
> > path: /a /b
> > ```
> > 
> > 
> > their should be four combinations
> > ```
> > a.com /a
> > a.com /b
> > b.com /a
> > b.com /b
> > ```
> > 
> > 
> > all this situation can hit the route, but I want the route config is
> > ```
> > a.com /a 
> > b.com /b 
> > ```
> > 
> > 
> > this just two situation can hit the route, to implementation this situation we should change the route config such as
> > ```
> > host_paths:[{
> > host: a.com,path: /a}
> > {host:b.com,path:/b} ]
> > ```
> > 
> > 
> > this is not a compatible change.
> 
> What you want can be achieved by splitting this into two routes. The first route contains host `a.com` and uri `/a`, and
> similarly, the second route has host `b.com` and uri `/b`.

Yes, it can work,  but if you have too many paths, you should create more routes.
