### ISSUE TITLE
request help: how to add proxy_ignore_client_abort in apisix

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#3968]
### Issue description
how to add proxy_ignore_client_abort in apisix

### Environment

* apisix version (cmd: `apisix version`):2.4
* OS (cmd: `uname -a`):centos

**Comment by tokers** [comment]
@gewei2000 Try `http_server_configuration_snippet ` https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L157.
