### ISSUE TITLE
doc: update the Getting Started guide in Chinese

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3970]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi! We have just updated the Getting Started docs in English[1], now anyone would like to translate it to Chinese?

## Describe the solution you'd like

1. Visi the Getting Started docs[1] first, and read it to make sure you understand what it says;
2. Here is the original Markdown file in English[2];
3. Here is the Markdown file in Chinese[3], **we are going to update it**.

[1] https://apisix.apache.org/docs/apisix/getting-started/
[2] https://github.com/apache/apisix/edit/master/docs/en/latest/getting-started.md
[3] https://github.com/apache/apisix/edit/master/docs/zh/latest/getting-started.md

**Comment by gxlct008** [comment]
I want to give it a try, hoping to give apisix some help.

**Comment by juzhiyuan** [comment]
Thanks! Let me if you need help!

DeepL.com is our friend
