### ISSUE TITLE
docs: update the image of the old version of Dashboard in the prometheus plugin doc

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#3973]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

The Dashboard picture in the section [How to open the plugin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md#how-to-enable-it) in the prometheus.md document is the old version, we need to update the picture to the new version.

<img width="1202" alt="截屏2021-04-06 上午9 33 41" src="https://user-images.githubusercontent.com/52862365/113646366-46742680-96bb-11eb-93ba-dae2e524caaa.png">

## Describe the solution you'd like

We need to update the old version of the picture to the latest version.

**Comment by juzhiyuan** [comment]
Hi, your images are broken actually 😂

**Comment by Firstsawyou** [comment]
> Hi, your images are broken actually 😂

 😂 Yes, it has been updated.
