### ISSUE TITLE
Enhance the documentation of echo plugin

### ISSUE THREAD

**Issue by tokers** [apache/apisix#3974]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

![image](https://user-images.githubusercontent.com/10428333/113387894-c2baf100-93bf-11eb-8a94-933b2e482f80.png)

The descriptions for `auth_value` are obscure, it doesn't really explain what is `auth_value`, also, related usage about `auth_value` is missing.

A clear and concise description of what you want and what your use case is.

Add elaborate descriptions for `auth_value` and prepare more examples (for `auth_value`, `after_body`, `headers` and so on).

**Comment by spacewander** [comment]
I dig into the history, looks like we can remove this field.
It is used to demonstrate how to take advantage of the access phase.
