### ISSUE TITLE
request help:  Is there a plugin that can limit the tcp connection?

### ISSUE THREAD

**Issue by silveric10** [apache/apisix#3975]
### Issue description
I learned that Limit-req, Limit-count and Limit-concurrency are all used to limit the http request count, but is there a plugin that can limit the tcp connection? Thank you.

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by spacewander** [comment]
No
