### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by YeZiZhen** [apache/apisix#3978]
### Environment

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):Linux ubuntu 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
built by gcc 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
built with OpenSSL 1.1.1g  21 Apr 2020
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath=/usr/local/openresty/openssl/lib' --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):etcd Version: 3.4.13
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1.在apisix-2.3\apisix\plugins下添加新插件，保存，命名正确
2.执行curl http://127.0.0.1:9000/apisix/admin/plugins/reload -H 'X-API-KEY: westone' -X PUT返回done
3.执行curl http://127.0.0.1:9000/apisix/admin/plugins/list -H 'X-API-KEY: westone' -X GET后并没有新添加的插件，对已有的插件更改也没有产生变化
4.定义新的route使用新插件提示未知的插件

5.现在是必现，之前没有出现过这样的问题

**Comment by spacewander** [comment]
You need to declare your plugin in `config.yaml` first.

**Comment by Firstsawyou** [comment]
>定义新的route使用新插件提示未知的插件

Is your new plugin name configured in the plug-in list of the `config.yaml` configuration file?
By the way, it is better to use English in the community.

**Comment by spacewander** [comment]
Closed as lack of response.
