### ISSUE TITLE
In Stand-alone mode,  Is the apisix.yaml  configuration Descriptive Capability as strong as using  admin-api(etcd)?

### ISSUE THREAD

**Issue by xiewenhui** [apache/apisix#3979]
Stand-alone.md is so concise.

In Stand-alone mode,  Is the apisix.yaml  configuration Descriptive Capability as strong as using  admin-api(etcd)?
https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md

for example ，How to cfg   the parameters of the health check for Upstream in Stand-alone mode？

**Comment by Firstsawyou** [comment]
The yaml mode is as powerful as the etcd mode. For how to configure the health check, you can refer to here:
https://github.com/apache/apisix/blob/master/t/config-center-yaml/route-upstream.t
