### ISSUE TITLE
doc: added fields for Health Check

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#3984]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hi, when I visit the Apache APISIX's docs here[1], I noticed that some fields are missing, like `active.healthy.http_statuses`, as for other fields, need more search and compare with other API Gateways.

So anyone would like to add the `active.healthy.http_statuses` field back here[2]?

## Describe the solution you'd like

1. Visit this file[2];
2. Add `active.healthy.http_statuses` field back, its meaning is `An array of HTTP statuses to consider a success, indicating healthiness, when returned by a probe in active health checks. Defaults to [200, 302].`, this description is from Konga.
3. File your PR!

[1] https://apisix.apache.org/docs/apisix/health-check/
[2] https://github.com/apache/apisix/edit/master/docs/en/latest/health-check.md

**Comment by gxlct008** [comment]
I want to give some help.
