### ISSUE TITLE
request help: How to configure multi listen ports(http or https)

### ISSUE THREAD

**Issue by highkay** [apache/apisix#3985]
### Issue description

I could only find these configurations for port listening,  one for http and one for https. I need multi ports for http and https protocol.

### Environment

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`): all platform
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): all
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): all
* apisix-dashboard version, if have: 2.5

**Comment by tokers** [comment]
@highkay See http://apisix.apache.org/docs/apisix/FAQ/#how-to-make-apisix-listen-on-multiple-ports-when-handling-http-or-https-requests.

**Comment by highkay** [comment]
well ,I can config multi ports now. But I can't find any way to config the ports in route.

**Comment by highkay** [comment]
Alright, I find out somehow why I faced so much issues in using apisix, which is a product centerilize the usage in a ops team of an orgnization (maybe more cloud-native ). I just make apisix fitting a complete retail software, which require it could be run in a nothing is certain (for example, config a private domain ) enviroment. These cases are out-of-scope for apisix, am I right?

**Comment by spacewander** [comment]
Yes
