### ISSUE TITLE
bug: limit-count may prevent more requests by mistake that should access normally in High concurrency scenarios

### ISSUE THREAD

**Issue by ychdesign** [apache/apisix#3988]
### Issue description
{
  "count": 4000,
  "key": "server_addr",
  "policy": "redis-cluster",
  "redis_cluster_nodes": [],
  "rejected_code": 500,
  "time_window": 1
}

When the threshold not reached,a few requests are prevented by the limit-count plugin.
The founction incoming, ttl and incrby opreations are not atomic.
Maybe can use eval() to ensure it.

### Environment

* apisix version : 2.0
* OS (cmd: `uname -a`): Linux 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  openresty/1.19.3.1

### Minimal test code / Steps to reproduce the issue
压测即可复现

**Comment by spacewander** [comment]
Look like the bug is real. Why did you close your PR?

**Comment by ychdesign** [comment]
pr check failed，在改pr的信息



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月6日(星期二) 下午4:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] bug: limit-count may prevent more requests by mistake that should access normally in High concurrency scenarios (#3988)





 
Look like the bug is real. Why did you close your PR?

**Comment by spacewander** [comment]
You can open a draft PR.
<img width="706" alt="微信截图_20210406164246" src="https://user-images.githubusercontent.com/4161644/113683770-27938580-96f7-11eb-994e-9fb0b2eae727.png">

**Comment by ychdesign** [comment]
thanks. It resloved.

**Comment by zwjzxh520** [comment]
不知道为什么会将这几行代码去掉？
` local ok, err = red:set_keepalive(10000, 100)
    if not ok then
        return nil, err
    end`

**Comment by ychdesign** [comment]
> 不知道为什么会将这几行代码去掉？
> 
> ```lua
> local ok, err = red:set_keepalive(10000, 100)
> if not ok then
>     return nil, err
> end
> ```
> 
> @ychdesign

sorry. I ignored it by mistake. would you make a pr to solve that？
