### ISSUE TITLE
Error: It is forbidden to run APISIX in the /root directory.

### ISSUE THREAD

**Issue by anyforever** [apache/apisix#3998]
### Environment

* apisix version (cmd: `apisix version`):2.4.1
* OS (cmd: `uname -a`):CentOS 8
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

用root用户编绎安装的，在原下载目录启动，提示这个，然后把bin文件移动到/usr/local/apisix/bin目录，启动，依然报这个错误提示。。难道不能用root用户编译？为什么不自动选择给安装到/usr/local/apisix呢？或者可以编译的时候明确指定安装到哪里也可以。

**Comment by Firstsawyou** [comment]
Did you install apisix from source?
You can install apisix using the `rpm` package, so that it is installed in the `/usr/local/` directory by default

**Comment by anyforever** [comment]
Yes, install apisix from source. RPM package（only for CentOS 7）
but my OS is 8

**Comment by Firstsawyou** [comment]
> Yes, install apisix from source. RPM package（only for CentOS 7）
> but my OS is 8

Ok, the source installation method cannot be enabled in the `/root` directory, you need to try other directories to start apisix. You can also use docker to install apisix.

**Comment by moonming** [comment]
> > Yes, install apisix from source. RPM package（only for CentOS 7）
> 
> > but my OS is 8
> 
> 
> 
> Ok, the source installation method cannot be enabled in the `/root` directory, you need to try other directories to start apisix. You can also use docker to install apisix.

but you should tell why can not run in root dir.
and it is nothing with docker.

**Comment by anyforever** [comment]
@moonming 1.在root目录编译的时候没有任何提示，等到启动的时候才提示不能这样。。有点迟了吧
2.把root目录编译完的copy到/usr/local/apisix目录下启动，也是一样的提示。所以提问是不是编译的时候必须在非root目录操作，建议软件做成跟别的软件那种常规安装模式，例如：make install之后，给安装到/usr/local/apisix目录。或者在configure时可以手动指定安装目录较好

**Comment by Firstsawyou** [comment]
> @moonming 1.在root目录编译的时候没有任何提示，等到启动的时候才提示不能这样。。有点迟了吧
> 2.把root目录编译完的copy到/usr/local/apisix目录下启动，也是一样的提示。所以提问是不是编译的时候必须在非root目录操作，建议软件做成跟别的软件那种常规安装模式，例如：make install之后，给安装到/usr/local/apisix目录。或者在configure时可以手动指定安装目录较好

Because the `worker` process of APISIX is the authority of ordinary users of `nobody`. When APISIX is in the `/root` directory, ordinary users do not have the authority to access the /root directory. 
Therefore, this error message will be output. You need to copy the entire project of `APISIX` to another directory, so that the `worker` process of APISIX has the permission to read related files, instead of just copying `./bin/apisix` files.

**Comment by juzhiyuan** [comment]
1. Build Apache APISIX from source codes under the `/root` directory;
2. Run `apisix start`
3. Error occurred.

```sh
[root@VM-0-7-centos apisix]# apisix start
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
Error: It is forbidden to run APISIX in the /root directory.
```

Just label this issue as `doc`.
