### ISSUE TITLE
request help: gRPC gateway is not enabled in etcd cluster "which is required by Apache APISIX“

### ISSUE THREAD

**Issue by WinSuperStar** [apache/apisix#3999]
### Issue description
when I start apisix，get the message 
gRPC gateway is not enabled in etcd cluster "which is required by Apache APISIX"
### Environment

* apisix version (cmd: `apisix version`): 2.5 && 2.4
* OS (cmd: `uname -a`):Linux apisix 5.2.14-1.el7.elrepo.x86_64 #1 SMP Tue Sep 10 10:50:19 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
The etcd cluster needs to enable `gRPC gateway`, you can refer to here to enable it.  https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#why-there-are-a-lot-of-failed-to-fetch-data-from-etcd-failed-to-read-etcd-dir-etcd-key-xxxxxx-errors-in-errorlog

**Comment by WinSuperStar** [comment]
ok
