### ISSUE TITLE
request help: health check for gRPC upstream

### ISSUE THREAD

**Issue by moonming** [apache/apisix#4006]
### Issue description
The current health check of Apache APISIX is for http/https upstream. Can we add the check for gRPC upstream?
@nic-chen 

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by riskgod** [comment]
Now we check the health open a now http/https path /8080 in my gRPC services,  if we have gRPC check, it will be very helpful.

**Comment by nic-chen** [comment]
OK, I will try for it.
