### ISSUE TITLE
Improve: Plugin Traffic-split do not use '"server_port", ">", 0' for vars by default

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#4015]
### Issue description
If I use traffic-split without any vars, `server_port > 0 ` will be set. https://github.com/apache/apisix/blob/master/apisix/plugins/traffic-split.lua#L49
Although it does not affect the logic, it will affect the reading. and make the configuration look inconsistent.

### Environment

* apisix version (cmd: `apisix version`): 2.5

**Comment by Firstsawyou** [comment]
Yes, we can remove it,
