### ISSUE TITLE
request help:I need a demo for authz-keycloak

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#4032]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
You can refer to the documentation here: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-keycloak.md
The test cases of the authz-keycloak plugin may be helpful to you: https://github.com/apache/apisix/blob/master/t/plugin/authz-keycloak.t

**Comment by cverdela** [comment]
401 with error：{"error":"invalid_grant","error_description":"Invalid bearer token"} 
get auth/realms/apisix/.well-known/uma2-configuration
"grant_types_supported": [
        "authorization_code",
        "implicit",
        "refresh_token",
        "password",
        "client_credentials"
    ],
how to add grant_type ：urn:ietf:params:oauth:grant-type:uma-ticket

**Comment by cverdela** [comment]
@Firstsawyou

**Comment by Firstsawyou** [comment]
> 401 with error：{"error":"invalid_grant","error_description":"Invalid bearer token"}
> get auth/realms/apisix/.well-known/uma2-configuration
> "grant_types_supported": [
> "authorization_code",
> "implicit",
> "refresh_token",
> "password",
> "client_credentials"
> ],
> how to add grant_type ：urn:ietf:params:oauth:grant-type:uma-ticket

Did you check if the `access token` is valid?
Or provide your configuration information?
