### ISSUE TITLE
[discuss]: keep backward compatibility of apisix admin api or manager api

### ISSUE THREAD

**Issue by bfcx** [apache/apisix#4037]
When upgrading APISIX form v1.5 to v2.4, I find that the response body of admin api in APISIX2.4 are not keep compatibility with that in v1.5.

In APISIX 1.5, config restored by etcd v2,  response body returned by admin api both contains the field:
"modifiedIndex("mod_revision" in etcd v3)" and "prevNode("prev_kv" in etcd v3)".

BUT, in APISIX 2.4, response body of admin api and manager api are not contains these fields.

We've developed series of apis base on APISIX1.5 admin api which can perform batch operations of CURDs for apisix config, so, in our apis we used field "modifiedIndex" and "prevNode" for atomicity guarantee and failed rollback.

**DISCUSS**:
Wish to add these fields in response body of admin api and manager api in APISIX2.4, to keep compatibility with that in v1.5.

**Comment by gxthrj** [comment]
cc @nic-chen @spacewander

**Comment by spacewander** [comment]
Those fields are removed intentionally because we have plan to support non-etcd storage.

@bfcx 
Will you contribute the batch operation support to us so we can maintain the backward compatibility?

**Comment by nic-chen** [comment]
> Those fields are removed intentionally because we have plan to support non-etcd storage.

Yes, so we only return generic values, not the data unique to etcd.

**Comment by spacewander** [comment]
Closed as lack of response.
