### ISSUE TITLE
skywalking plugin attribute service_instance_name hard-coded

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#4040]
### Issue description

Whether its attribute “service_instance_name” can be obtained automatically instead of hard-coded in the configuration

**Comment by spacewander** [comment]
@gxthrj 
Could you help us to confirm it?

**Comment by gxthrj** [comment]
@dickens7 Do you mean set `service_instance_name ` with the real APISIX instance name? 

For example, In k8s set `service_instance_name` with APISIX pod name.

**Comment by dickens7** [comment]
> @dickens7 Do you mean set `service_instance_name ` with the real APISIX instance name? 
> 
> For example, In k8s set `service_instance_name` with APISIX pod name.

yes, it's necessary when there are many nodes.

**Comment by spacewander** [comment]
@dickens7 
PR is welcome!

**Comment by dickens7** [comment]
ok, assign it to me.
