### ISSUE TITLE
request help: grpc-transcode 是否支持 proto 文件组织

### ISSUE THREAD

**Issue by vincenthcui** [apache/apisix#4041]
### Issue description

grpc-transcode 插件支持 import proto 吗。工程实践中很难用一个 proto 定义所有服务，通常需要 improt 多个 Proto 完成定义，protobuf 官方也是这样推荐的

**Comment by nic-chen** [comment]
It is not currently supported. Because our proto is stored in ETCD instead of in a directory, the import relationship is not easy to handle.
btw, please use English in public channel.
