### ISSUE TITLE
request help: the radixtree.lua does not support dot character when using parameter in path

### ISSUE THREAD

**Issue by comedown** [apache/apisix#4046]
### Issue description
I added a routing rule which path is "/test/:project/:version/*action", it does not match the url "/test/1/7.5.11/multi/path".
Instead, the url "/test/1/2/multi/path" can.

Please take a look!

### Environment

* apisix version (cmd: `apisix version`): 2.0
* OS (cmd: `uname -a`): OSX
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
Can you provide a reproducible use case?

**Comment by Gerrard-YNWA** [comment]
https://github.com/api7/lua-resty-radixtree/blob/master/lib/resty/radixtree.lua#L463  
The pattern `[=[([\w\-_\%]+)]=]` for matching parameters in path failed.

**Comment by comedown** [comment]
> https://github.com/api7/lua-resty-radixtree/blob/master/lib/resty/radixtree.lua#L463
> The pattern `[=[([\w\-_\%]+)]=]` for matching parameters in path failed.

Thanks fro you answer,

**Comment by comedown** [comment]
> https://github.com/api7/lua-resty-radixtree/blob/master/lib/resty/radixtree.lua#L463
> The pattern `[=[([\w\-_\%]+)]=]` for matching parameters in path failed.

Thanks! It is helpful to me.

**Comment by comedown** [comment]
> Let me test it.

Thanks for you help! How about supporting the dot character in regular expression in lua-resty-radixtree libaray?

**Comment by spacewander** [comment]
@Gerrard-YNWA 
Will you contribute the fix you find?
