### ISSUE TITLE
request help:Questions about route matching

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#4049]
### Issue description

i have two routes：
1.
{
...
uri: ["/*.html"]
}
2.
{
...
uri:["/**"]
}

I want  to match the first route by `path = "/main.html" `，match the second route by `path="/test/1"`.

What should I do？

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by Firstsawyou** [comment]
For the first routing rule, you can try this:

```shell
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/*",
    "vars": [
        ["uri", "~~", "/.+\\.html$"]
    ],
    "upstream": {
            "type": "roundrobin",
            "nodes": {
                "127.0.0.1:1980": 1
            }
    }
}'
```

For the second routing rule, you can try this:

```shell
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/test/1",
    "upstream": {
            "type": "roundrobin",
            "nodes": {
                "127.0.0.1:1980": 1
            }
    }
}'
```

**Comment by kongjun01** [comment]
thanks

**Comment by kongjun01** [comment]
the second routing rule must `/*`，because it is back server. the front server(the first routing rule) is 
```
uris: ["/","/*.html"]

your example(the first routing rule) , paths that end in html can be matched , but not match `/`.

my requirement is for front and rear end separation , or maybe you have some other solution?

**Comment by kongjun01** [comment]
my front server route rule:
```
"uris": [
  "/*"
],
priority: 100, 
"vars": [
  [
    "uri",
    "~*",
    "/|/.+\\.html"
  ]
]
```

my back server route rule:
```
"uris": [
  "/*"
],
priority: 0
```

when i access `/test` , the match front route.  I don't think it works when there is an or regular expression.

**Comment by tokers** [comment]
@kongjun01 The Regex Pattern `/|/.+\\.html` absolutely can match the `/test`.

**Comment by kongjun01** [comment]
So the `var` match doesn't fulfill my requirement. whether `uris` can be support matched regular expression , or the end match?

**Comment by tokers** [comment]
> So the `var` match doesn't fulfill my requirement. whether `uris` can be support matched regular expression , or the end match? I think this kind of need is quite common.

This is another problem about how to write correct regex pattern. What about `"^/$|/.+\\.html"`

**Comment by kongjun01** [comment]
it is ok , thanks~
