### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix#4054]
### Environment

* apisix version (cmd: `apisix version`):  APISIX/2.3
* OS (cmd: `uname -a`): #60-Ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

Hi all,
I am new to APISIX.
I just trying to create a route to an API the is up and running on my local machine.
the details of the route are :
curl http://127.0.0.1:9080/apisix/admin/routes/2 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/testrouting",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "http://127.0.0.1:9090": 1
        }
    }
}'
this return that the route created successfully

when I am trying to access the route using this link:
 curl http://127.0.0.1:9080/testrouting
then this  appear 

![image](https://user-images.githubusercontent.com/79872781/114796098-5a411c00-9d90-11eb-803f-630a43a23ef3.png)

So could you please help me?

**Comment by Firstsawyou** [comment]
You need to configure the domain name or IP in the upstream nodes. Your route should be created like this:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/2 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
"uri": "/testrouting",
"upstream": {
"type": "roundrobin",
"nodes": {
"127.0.0.1:9090": 1
}
}
}'
```

**Comment by hozaifaaoud** [comment]
Thank you for your response,
I tried your solution and currently, I am facing this issue
![image](https://user-images.githubusercontent.com/79872781/114921608-0a636300-9e2b-11eb-8fc0-bf1bb522a3b2.png)
could you please help me?

**Comment by hozaifaaoud** [comment]
> The addresses in upstream nodes need to be configured with a domain name or IP. Your route should be created like this:
> 
> ```shell
> curl http://127.0.0.1:9080/apisix/admin/routes/2 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
> {
> "uri": "/testrouting",
> "upstream": {
> "type": "roundrobin",
> "nodes": {
> "127.0.0.1:9090": 1
> }
> }
> }'
> ```

**Comment by Firstsawyou** [comment]
You should provide detailed configuration information to facilitate troubleshooting.

**Comment by hozaifaaoud** [comment]
here is the configuration file :

apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds
------------
if there are any other configurations you need... please let me know.

**Comment by tokers** [comment]
> Thank you for your response,
> 
> I applied your solution.
> 
> And I tried calling the API using :
> 
> curl http://127.0.0.1:9080/testrouting
> 
> then  I faced this issue
> 
> ![image](https://user-images.githubusercontent.com/79872781/114926850-21a54f00-9e31-11eb-892b-77fa6dcaac5a.png)
> 
> could you please help me?
> 
> 

Have you ever tried to access the upstream endpoint directly? It seems like this 404 response is not generated by apisix.

**Comment by hozaifaaoud** [comment]
yes I tried accessing the service directly 
my test API is up and running in this port  9090
here is the request
curl  http://127.0.0.1:9090/
and here is the response 
![image](https://user-images.githubusercontent.com/79872781/114960899-42d56200-9e68-11eb-9907-43ebba2bff3c.png)

**Comment by Firstsawyou** [comment]
You try to access like this, is there any response data?

```shell
curl http://127.0.0.1:9090/testrouting
```

**Comment by hozaifaaoud** [comment]
calling this url
 curl http://127.0.0.1:9090/testrouting 
returns  my service response 
![image](https://user-images.githubusercontent.com/79872781/115029337-2cf68a00-9ec6-11eb-9a3f-190395f72071.png)

**Comment by Firstsawyou** [comment]
This issue is the same as https://github.com/apache/apisix/issues/4065 , and we will discuss it on https://github.com/apache/apisix/issues/4065.

**Comment by leslie-tsang** [comment]
Considered resolved due to lack of feedback. Feel free to reopen it if needed.

**Comment by medmo** [comment]
503 Service Temporarily Unavailable may be caused by proxies.
