### ISSUE TITLE
bug: setting an empty global rule stops route plugins from running?

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#4057]
### Issue description
See steps to reproduce.

### Environment

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): Ubuntu 18.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have:

### Minimal test code / Steps to reproduce the issue

1. Create a global rule with an empty map of plugins
```
local code, body = t('/apisix/admin/global_rules/1',
                 ngx.HTTP_PUT,
                 [[{
                    "plugins": {}
                }]]
                )
```
         
2. Create a route, enable prometheus
```
local code, body = t('/apisix/admin/routes/1',
                ngx.HTTP_PUT,
                [[{
                    "plugins": {
                        "prometheus": {}
                    },
                    "upstream": {
                        "nodes": {
                            "127.0.0.1:1980": 1
                        },
                        "type": "roundrobin"
                    },
                    "uri": "/hello"
                }]]
                )
```
3. Request `/hello`. 
4. Get prometheus metrics.

### What's the actual result? (including assertion message & call stack if applicable)
The `/hello` request is not counted by apisix_http_status. In fact, it never entered log phase of exporter.lua.
### What's the expected result?
Prometheus plugin should work as normal.

**Comment by Firstsawyou** [comment]
I tested it and reproduced it.

@spacewander  Should we need to fix it?
