### ISSUE TITLE
request help: add APISIX plugin component id for skywalking

### ISSUE THREAD

**Issue by moonming** [apache/apisix#4059]
### Issue description

related PR: https://github.com/apache/skywalking/pull/6757 

We need to make changes on the Apache APISIX side. We can refer to https://github.com/apache/skywalking-nginx-lua/pull/74

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:

**Comment by moonming** [comment]
we need to update https://github.com/apache/apisix/blob/master/apisix/plugins/skywalking.lua

**Comment by dmsolr** [comment]
Hi, could assign it to me. I would like to do it. :)
