### ISSUE TITLE
bug: the route which was create by dashboard is invalid

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4063]
### Issue description
Here has a problem, i configure the route /patient/patient/* as below , but it also said that 404 Route Not Found
curl -i -X GET http://ip:host/patient/patient/id -H "Host: httpbin.org" -H 'apikey: superSecretAPIKey'

It was amazing that there had no route of /get which i was update to/patient/patient/* can get the reseult..
curl -i -X GET http://ip:host/get -H "Host: httpbin.org" -H 'apikey: superSecretAPIKey'

there has only one etcd which was run by APISIX Helm Chart, i thought that `/get ` path was created by api (/admin/route)
but path `patient/patient/id` was created by dashboard, so i tired to create `patient/patient/id` by using api (/admin/route),
it's work! just 404 per another question

so why the path which was create by dashboard is invalid.

### Environment
* use APISIX Helm Chart

**Comment by Firstsawyou** [comment]
You should check whether there is route data created by Dashboard in etcd?

**Comment by tokers** [comment]
Could you see this route on dashboard ?

**Comment by Marco-Zheng** [comment]
> You should check whether there is route data created by Dashboard in etcd?



> Could you see this route on dashboard ?

Yes, i can see the route.

**Comment by Marco-Zheng** [comment]
> You should check whether there is route data created by Dashboard in etcd?

In order to make it clear , i delete all route and will try to reenact the bug
- Firstlly, i add a route by apisix admin api (not on dashboard) as below and it show on dashboard successfully.
![image](https://user-images.githubusercontent.com/52538259/114963392-3ae4e480-9e9f-11eb-83aa-c5354f546216.png)
![image](https://user-images.githubusercontent.com/52538259/114963234-d9bd1100-9e9e-11eb-9d3f-985453a631b4.png)
Then i send a request, the route was found(only one route) 
![image](https://user-images.githubusercontent.com/52538259/114963532-8f885f80-9e9f-11eb-928f-7f45cb26e863.png)

- Then i create a route on dashboard as below, only route path change 
![image](https://user-images.githubusercontent.com/52538259/114963740-f73eaa80-9e9f-11eb-84ee-144fd91340d5.png)
Here has two route as below
![image](https://user-images.githubusercontent.com/52538259/114963810-1c331d80-9ea0-11eb-9204-c94538d24196.png)
Then i send a request, as you can see, the route not found..
![image](https://user-images.githubusercontent.com/52538259/114963866-3bca4600-9ea0-11eb-9ce8-d766acd2bb59.png)

**Comment by Marco-Zheng** [comment]
> Could you see this route on dashboard ?

I have written down the detailed reproduction process on below comment

**Comment by Marco-Zheng** [comment]
> You should check whether there is route data created by Dashboard in etcd?

I also check the etcd, two route are all exsist 
![image](https://user-images.githubusercontent.com/52538259/114965161-a1b7cd00-9ea2-11eb-8472-bfd5e7e09dae.png)

**Comment by Marco-Zheng** [comment]
> You should check whether there is route data created by Dashboard in etcd?

Like this:
{"update_time":1618539226,"create_time":1618539226,"host":"httpbin.org","upstream_id":"51","uri":"\/patient\/patient\/*","status":1,"priority":0,"id":"10"}
/apisix/routes/350662478968914814
{"id":"350662478968914814","create_time":1618540724,"update_time":1618540724,"uris":["/member/member/*"],"name":"test","methods":["GET","HEAD","POST","PUT","DELETE","OPTIONS","PATCH"],"hosts":["httpbin.org"],"vars":[],"upstream_id":"51","status":1}

**Comment by spacewander** [comment]
It is a known issue. The dashboard in the helm chart is too old:
https://github.com/apache/apisix-helm-chart/blob/e26517c5302d3d839c2f483a211c60dd55d43c0d/charts/apisix-dashboard/values.yaml#L27

We will fix it once a new dashboard version is released (none of the releases of dashboard support APISIX 2.5 yet).

**Comment by Marco-Zheng** [comment]
> It is a known issue. The dashboard in the helm chart is too old:
> https://github.com/apache/apisix-helm-chart/blob/e26517c5302d3d839c2f483a211c60dd55d43c0d/charts/apisix-dashboard/values.yaml#L27
> 
> We will fix it once a new dashboard version is released (none of the releases of dashboard support APISIX 2.5 yet).

Ok, it main caused per `var:[]`
![image](https://user-images.githubusercontent.com/52538259/114969606-4ccc8480-9eab-11eb-91a9-c46dbc4c972f.png)

So, which version is ok at this time, or we need deploy apisix & apisix dashboard & apisix ingress controller & etcd in k8s without using apisix-helm-chart?

**Comment by spacewander** [comment]
You can use APISIX 2.4 + APISIX dashboard 2.5

@tokers 
What is the version requirement for the ingress controller?

**Comment by tokers** [comment]
> You can use APISIX 2.4 + APISIX dashboard 2.5
> 
> @tokers
> What is the version requirement for the ingress controller?

Just use apisix-ingress-controller `0.5.0` is OK.

**Comment by Marco-Zheng** [comment]
> > You can use APISIX 2.4 + APISIX dashboard 2.5
> > @tokers
> > What is the version requirement for the ingress controller?
> 
> Just use apisix-ingress-controller `0.5.0` is OK.

@tokers @spacewander Thanks a lot, i'll try to deploy your mentioned apisix version.

**Comment by Marco-Zheng** [comment]
> You can use APISIX 2.4 + APISIX dashboard 2.5
> 
> @tokers
> What is the version requirement for the ingress controller?

@tokers @spacewander @Firstsawyou The problem has bean solved, many thanks! i'll close the issue.
