### ISSUE TITLE
bug: Advanced route matching condition is invalid

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#4066]
### Issue description

When the uri of the two routes are the same, the upstream is inconsistent. One is to set the advanced routing "header route", and one is ordinary route. When the weights of the two routes are the same or the weight of the ordinary route is greater than that of the advanced route, the advanced route cannot be hit. 

### Environment

* apisix version (cmd: `apisix version`): 
 2.5 

* OS (cmd: `uname -a`):  
Ubuntu 20.04

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  
 openresty/1.19.3.1

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 
{"boot_time":1618294363,"etcd_version":"3.4.0","id":"79165099-6f97-4ab3-baf6-ac73f87b2d41","hostname":"apisix-778786b894-7krw9","last_report_time":1618537429,"version":"2.5","up_time":243104}

* apisix-dashboard version, if have: 
2.5

**Comment by Firstsawyou** [comment]
Different routes have the same uri, if you want to set advanced routing rules to match, then you need to set advanced routing rules for them at the same time. Here are some examples of routing rules, you can refer to: https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#4-different-routes-have-the-same-uri

**Comment by dickens7** [comment]
i see, thanks.
