### ISSUE TITLE
docs: remove leading `$` of each bash command

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#4076]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Currently in [`getting-started`](https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started.md), there would always be a `$` at the front of each command, which makes users hard to do three-click to directly copy the whole command and run without modification. They have to manually delete `$`. And it could be more annoying when on [website](http://apisix.incubator.apache.org/docs/apisix/getting-started) that users could directly use one-click copy button to do so. So it could be better if we remove all those dollar signs at the front of each command in docs.

And the same problem that happens in `how-to-build`/`install-dependencies` also could be fixed.

## Describe the solution you'd like

Remove them all~

**Comment by Serendipity96** [comment]
hi @Yiyiyimu , Can I work on this issue?

**Comment by tokers** [comment]
> hi @Yiyiyimu , Can I work on this issue?

Sure, assigned it to you.
