### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by izayoi-akira** [apache/apisix#4078]
### Issue description
关于jwt-auth，`/apisix/plugin/jwt/sign`可以获取token，并且访问成功
但是有个需求，是如何让apisix或者上游知道是哪个消费者访问的？

**Comment by izayoi-akira** [comment]
How can I get the consumer message which requeset the upstream by upstream or apisix

**Comment by Firstsawyou** [comment]
> 如何让apisix或者上游知道是哪个消费者访问的？

According to the existing configuration in the `consumer`, when you access authentication, it will be authenticated with the information configured in the consumer according to the token you use.

You can refer to the consumer-restriction plugin, through which you can do corresponding access restrictions.

**Comment by izayoi-akira** [comment]
Access Restrictions is not what I want, I want upstream to know witch consumer is accessing it.

for example:
There are two consumers: consumers1 and consumers2,they got token1 and token2 with `/apisix/plugin/jwt/sign`.
Then they both access the upstream api: `xxx.com/articel/add`,now xxx.com wants to know if it was consumers1 or consumers2 that access it

**Comment by izayoi-akira** [comment]
> > 如何让apisix或者上游知道是哪个消费者访问的？
> 
> According to the existing configuration in the `consumer`, when you access authentication, it will be authenticated with the information configured in the consumer according to the token you use.
> 
> You can refer to the consumer-restriction plugin, through which you can do corresponding access restrictions.

Access Restrictions is not what I want, I want upstream to know witch consumer is accessing it.

for example:
There are two consumers: consumers1 and consumers2,they got token1 and token2 with /apisix/plugin/jwt/sign.
Then they both access the upstream api: xxx.com/articel/add,now xxx.com wants to know if it was consumers1 or consumers2 that access it

**Comment by Firstsawyou** [comment]
> I want upstream to know witch consumer is accessing it.

You can try to use the proxy-rewrite plugin to add the consumer nam field to the request header and carry it upstream. like this:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/route01",
    "plugins": {
        "jwt-auth": {},
        "proxy-rewrite": {
            "headers": {
                "consumer-name": "$consumer_name"
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1981": 1
        }
    }
}'
```

**Comment by izayoi-akira** [comment]
> ```shell
> proxy-rewrite
> ```

 Thanks a lot !!!
