### ISSUE TITLE
bug: limit-count 中 count 值未生效

### ISSUE THREAD

**Issue by zwjzxh520** [apache/apisix#4080]
### Issue description
limit-count 中的 count 值未生效，压测时，常常能跑到设置值的3倍左右，比如，count 设置为 2000，发现能跑到 6000，local 与 redis 均有测试

插件中 redis 操作代码已经根据 #3988 调整

apisix 是跑在 k8s 中，一个 pod

插件配置 
```
{
  "count": 2000,
  "disable": false,
  "key": "remote_addr",
  "policy": "local",
  "time_window": 1
}
```

### Environment

* apisix version (cmd: `apisix version`):  2.4
* OS (cmd: `uname -a`): image: *apache/apisix:2.4-alpine*  uname -a : *Linux apisix-7bffcdb47d-hxz4l 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 Linux*
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  *nginx version: openresty/1.19.3.1*
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):   *3.4.0*
* apisix-dashboard version, if have:  commit: *afc3df96c0f7d86bfd20c579*

### Minimal test code / Steps to reproduce the issue

1.
2.
3.

### What's the actual result? (including assertion message & call stack if applicable)
![image](https://user-images.githubusercontent.com/2184202/115218221-e3fa3c00-a138-11eb-8913-2a0375b71c89.png)

截图中的 current rps 达到了 6000，而 current failures 才 200 多，预期是 4000

### What's the expected result?
QPS 超过 2000 后，正常请求在 2000，超过的均为 503

**Comment by Firstsawyou** [comment]
> {
>   "count": 2000,
>   "disable": false,
>   "key": "remote_addr",
>   "policy": "local",
>   "time_window": 1
> }

The value of the `time_window` field in the plug-in configuration is set to 1 second, you should try to set the `time_window` value larger. Because `time_window` represents the size of the time window (in seconds), the `count` will be reset after this time.

**Comment by zwjzxh520** [comment]
我的需求是每秒限制 2000 请求，难道这样配置不符合吗？
设置成 
time_window: 2
count: 4000
这样吗？

**Comment by Firstsawyou** [comment]
> 我的需求是每秒限制 2000 请求，难道这样配置不符合吗？
> 设置成
> time_window: 2
> count: 4000
> 这样吗？

This is reasonable. But time_window is set to 1 second, which is too short. It is not guaranteed that all requests will be completed within 1 second. When the request exceeds 1 second, the `count` value will be reset. The effect of the limit-count plug-in will be sent as it is now.
You can first set the value of `time_window` to a larger value, which makes it easier to test out the function of the limit-count plugin.

**Comment by zwjzxh520** [comment]
好的，明白您说的意思了

**Comment by zwjzxh520** [comment]
```
{
  "count": 60000,
  "disable": false,
  "key": "remote_addr",
  "policy": "redis",
  "redis_database": 20,
  "redis_host": "r-******.com",
  "redis_password": "",
  "redis_port": 6339,
  "redis_timeout": 500,
  "rejected_code": 503,
  "time_window": 60
}
```

![image](https://user-images.githubusercontent.com/2184202/115217989-aa293580-a138-11eb-8577-31daa6d3e433.png)

我们将 time_window 设置为了 60 s， 从压测结果中可以看出，控频是有波动的

上游接收到的请求数：

```
时间: 2021-04-19 17:08 QPS：199823
时间: 2021-04-19 17:07 QPS：166324
时间: 2021-04-19 17:06 QPS：150550
时间: 2021-04-19 17:05 QPS：114395 -- 开始压测
```
从 apisix 穿透到上游每分钟的请求数，远远大于我们设置的阈值 60000

**Comment by spacewander** [comment]
This problem is very relative to the actual environment, including how your load tester works, the network between your services, etc. As it is not easy to reproduce at our side correctly, you may need to add more logs to the limit-count plugin to see which side has missing count.

**Comment by zwjzxh520** [comment]
是的，这个也能理解你们的难处。

麻烦提供一些可以排查的方向，也是感激不尽

**Comment by spacewander** [comment]
Maybe you can log down the remaining there and compare it with the access log?
https://github.com/apache/apisix/blob/43b6e0d1504cab9fe41dd517a7d3770d57e21613/apisix/plugins/limit-count/limit-count-redis-cluster.lua#L97

**Comment by zwjzxh520** [comment]
感谢，找到原因了，是我们的统计有误
