### ISSUE TITLE
Failed installing dependencies

### ISSUE THREAD

**Issue by Ben0625** [apache/apisix#4084]
make deps
### Environment
* apisix version: 2.5
* OS: 3.10.0-693.el7.x86_64
* OpenResty version: openresty/1.17.8.2

>Installing https://luarocks.org/luasec-0.9-1.src.rock
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl111/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [deps] Error 1

The output of `luarocks config variables` :
> {
   AR = "ar",
   BUNZIP2 = "bunzip2",
   CC = "gcc",
   CFLAGS = "-O2 -fPIC",
   CHMOD = "chmod",
   CMAKE = "cmake",
   CP = "cp",
   CURL = "curl",
   CURLNOCERTFLAG = "-k",
   CVS = "cvs",
   FIND = "find",
   GIT = "git",
   GPG = "gpg",
   GUNZIP = "gunzip",
   HG = "hg",
   ICACLS = "icacls",
   LD = "gcc",
   LIBFLAG = "-shared",
   LIB_EXTENSION = "so",
   LS = "ls",
   LUA = "/usr/local/bin/luajit",
   LUALIB = "libluajit-5.1.a",
   LUA_BINDIR = "/usr/local/bin",
   LUA_DIR = "/usr/local",
   LUA_INCDIR = "/usr/local/include/luajit-2.1",
   LUA_LIBDIR = "/usr/local/lib",
   LUA_LIBDIR_FILE = "libluajit-5.1.a",
   MAKE = "make",
   MD5 = "md5",
   MD5SUM = "md5sum",
   MKDIR = "mkdir",
   MKTEMP = "mktemp",
   OBJ_EXTENSION = "o",
   OPENSSL = "openssl",
   OPENSSL_INCDIR = "/usr/local/openresty/openssl111/include",
   OPENSSL_LIBDIR = "/usr/local/openresty/openssl111/lib",
   PWD = "pwd",
   RANLIB = "ranlib",
   RM = "rm",
   RMDIR = "rmdir",
   ROCKS_TREE = "/usr/local/lib/luarocks/rocks-5.1",
   RSYNC = "rsync",
   RSYNCFLAGS = "--exclude=.git -Oavz",
   SCP = "scp",
   SCRIPTS_DIR = "/usr/local/bin",
   SEVENZ = "7z",
   SSCM = "sscm",
   SVN = "svn",
   TAR = "tar",
   TEST = "test",
   TOUCH = "touch",
   UNZIP = "unzip -n",
   WGET = "wget",
   WGETNOCERTFLAG = "--no-check-certificate",
   ZIP = "zip"

The output of `luarocks --version` :
/usr/local/bin/luarocks 3.4.0
LuaRocks main command-line interface

The output of `openssl version`:
OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by Firstsawyou** [comment]
Is the dependency of APISIX installed according to the documentation here? https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md

**Comment by spacewander** [comment]
Do you install openresty-openssl111-devel? What's the output of `ls -R /usr/local/openresty/openssl111/include`?

**Comment by Ben0625** [comment]
> Do you install openresty-openssl111-devel? What's the output of `ls -R /usr/local/openresty/openssl111/include`?

This is exactly the problem. 
For those that may have the same probelm: I failed to install by yum, then I fixed it through https://www.programmersought.com/article/44521860037/

Then I install openresty-openssl111-devel by yum. Then "make deps" success.
Big thanks.
