### ISSUE TITLE
feature: support to fetch balancer `ip`/`port` from `ctx.vars`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#4091]
we have stored the upstream ip/port in `ctx` object, here is the link: https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L204-L205

we should support to fetch from `ctx.vars`, here is the example:

```lua
local up_ip = ctx.vars["balancer_ip"]
local up_port = ctx.vars["balancer_port"]
```

Then we can use this value in plugins(eg: SkyWalking).

I think we can use the same way as "consumer_name", which is the code link:

https://github.com/apache/apisix/blob/master/apisix/core/ctx.lua#L176

**Comment by membphis** [comment]
@moonming welcome to take a look at this issue

and I think @Firstsawyou should familiar with this feature, welcome to make a try.

**Comment by Firstsawyou** [comment]
Assigned to me.
