### ISSUE TITLE
request help: How to configure apisix and dashboad  if etcd turns on certificate authentication

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4094]
### Environment

* apisix version (cmd: `apisix version`):2.3

**Comment by Firstsawyou** [comment]
In the APISIX configuration file, there is a default `etcd. tls.verify` as true. Is this okay?

https://github.com/apache/apisix/blob/964a92ee773264999eb67d0cd5539baf8961001b/conf/config-default.yaml#L200-L202

**Comment by Firstsawyou** [comment]
The configuration of etcd client certificate is not supported in APISIX 2.3. It is only supported in APISIX 2.5 This is the configuration information of etcd in 2.5

https://github.com/apache/apisix/blob/b17bb8fe728583dbb1f41bccc9c22fc8081ce5e0/conf/config-default.yaml#L204-L210


Dashboard's etcd client certificate configuration try to configure it here?
https://github.com/apache/apisix-dashboard/blob/v2.4/api/conf/conf.yaml#L31-L34

**Comment by StretchV** [comment]
ok thx you
