### ISSUE TITLE
request help: The http-logger plug-in encountered an unacceptable log information

### ISSUE THREAD

**Issue by zouyongsheng** [apache/apisix#4098]
**Issue description**
The http-logger plug-in is opened in route, and the demo program is configured to receive log information, save relevant information, and test. The demo program cannot receive the corresponding log information

 **Environment**
* apisix version (cmd: `apisix version`):2.5
* OS (cmd: `uname -a`): Linux 3.10.0-862.el7.x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
* apisix-dashboard version, if have:2.4

**Steps to reproduce the issue**
Configure a route, enable the HTTP logger plug-in, and configure the URI property of HTTP logger as http://127.0.0.1 : 5000/demo/logger, save access test, view demo program console output (I just export log information to console in the interface method of /demo/logger), but the result is unexpected / demo / logger has no output

![image](https://user-images.githubusercontent.com/22516879/115526402-914c8b80-a2c2-11eb-8312-9f77842f74da.png)

Ask for help, thank you!

**Comment by Firstsawyou** [comment]
Is there any output in your error.log?

**Comment by zouyongsheng** [comment]
> 您的error.log中是否有任何输出？
There is no error log information

**Comment by zouyongsheng** [comment]
Ask for help, thank you!

**Comment by Firstsawyou** [comment]
> (I just export log information to console in the interface method of /demo/logger)

My local test did not reproduce it. Maybe your log server receives logs abnormally.
You can receive the request body data of the http-logger plugin in the log server.

**Comment by zouyongsheng** [comment]
> > (I just export log information to console in the interface method of /demo/logger)
> 
> My local test did not reproduce it. Maybe your log server receives logs abnormally.
> You can receive the request body data of the http-logger plugin in the log server.

The problem has been solved, my port is disabled, thank you!

**Comment by tokers** [comment]
Consider it to be solved.

**Comment by 90yangkang** [comment]
Hello，my demo has received a request, but there is no log information.
![微信截图_20211124152204](https://user-images.githubusercontent.com/35477514/143193109-3dc63007-631b-4c31-9d46-76cad373cb22.png)

![微信截图_20211124152248](https://user-images.githubusercontent.com/35477514/143193117-240009dd-8e9e-441c-be87-f99d68381e67.png)

**Comment by tzssangglass** [comment]
> Hello，my demo has received a request, but there is no log information. ![微信截图_20211124152204](https://user-images.githubusercontent.com/35477514/143193109-3dc63007-631b-4c31-9d46-76cad373cb22.png)
> 
> ![微信截图_20211124152248](https://user-images.githubusercontent.com/35477514/143193117-240009dd-8e9e-441c-be87-f99d68381e67.png)

use java mock http server is not recommended. can you capture some network packets?
