### ISSUE TITLE
bug: 设置upstream healthcheck后会把原来的router 关联的upstream 覆盖

### ISSUE THREAD

**Issue by zuoshaoyi** [apache/apisix#4100]
没设置健康检查时router配置:
[root@docker2 ~]# ETCDCTL_API=2 etcdctl get  /apisix/routes/00000000000000000028
{"upstream_id":"00000000000000000014","uris":["\/index.html"],"plugins":{},"priority":0}

使用 https://github.com/apache/apisix/blob/master/docs/en/latest/health-check.md 设置健康检查，调用参数如下:
curl http://127.0.0.1:9080/apisix/admin/routes/00000000000000000028  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "upstream": {
         "nodes": {
            "192.168.113.101:8080": 1,
            "192.168.113.101:9090":1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "timeout": 5,
                "http_path": "/",
                "host": "foo.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                },
                "req_headers": ["User-Agent: curl/7.29.0"]
            },
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201],
                    "successes": 3
                },
                "unhealthy": {
                    "http_statuses": [500],
                    "http_failures": 3,
                    "tcp_failures": 3
                }
            }
        }
    }
}'

此时再次查看router 元数据信息:
[root@docker2 ~]# ETCDCTL_API=2 etcdctl get  /apisix/routes/00000000000000000028
{"upstream":{"type":"roundrobin","nodes":{"192.168.113.101:9090":1,"192.168.113.101:8080":1},"checks":{"active":{"unhealthy":{"http_failures":2,"tcp_failures":2,"timeouts":3,"interval":1,"http_statuses":[429,404,500,501,502,503,504,505]},"timeout":5,"req_headers":["User-Agent: curl\/7.29.0"],"type":"http","concurrency":10,"http_path":"\/","https_verify_certificate":true,"healthy":{"successes":1,"interval":2,"http_statuses":[200,302]},"host":"foo.com"},"passive":{"unhealthy":{"timeouts":7,"tcp_failures":3,"http_failures":3,"http_statuses":[500]},"healthy":{"successes":3,"http_statuses":[200,201]},"type":"http"}},"hash_on":"vars","retries":2},"priority":0,"uri":"\/index.html"}

发现原有的upstream 数据被覆盖。

再次在dashboard上修改router 配置，健康检查的配置也会被覆盖。

**Comment by tokers** [comment]
@zuoshaoyi 
It's an expected behavior as you use `PUT` method.

**Comment by zuoshaoyi** [comment]
还有其它方式能更新router upstream 健康检查配置不？

**Comment by zuoshaoyi** [comment]
而且，在dashboard上操作router 配置，健康检查的配置会被刷掉

**Comment by tokers** [comment]
@zuoshaoyi Please http://apisix.apache.org/docs/apisix/admin-api for details, also, please use English in public channel.

I'm not sure the HTTP method use by apisix-dashboard. @juzhiyuan Need your help.

**Comment by zuoshaoyi** [comment]
ok,thanks

**Comment by juzhiyuan** [comment]
Hi @zuoshaoyi, may I know what's your dashboard's version? You could see them on the server info page (On the left sidebar). 

BTW, days ago, we just fixed some issues on the Upstream module, which includes the Health Checker configuration, you could have a try on the latest codes, it's compatible with Apache APISIX 2.5.

**Comment by zuoshaoyi** [comment]
thanks~ my apisix version is 1.3,later i will try with apisix 2.5 .

**Comment by juzhiyuan** [comment]
🤣🤣 wow, maybe you could have a try on Apache APISIX 2.5 & Apache APISIX Dashboard 2.6 (will release tomorrow maybe)

**Comment by zuoshaoyi** [comment]
Sorry, I refer to this article to install Apisix. It seems that article is a bit old(https://www.jianshu.com/p/19607e0c7005)

**Comment by nic-chen** [comment]
had been released, welcome to have a try on Apache APISIX 2.5 & Apache APISIX Dashboard 2.6

**Comment by juzhiyuan** [comment]
consider closed, if it still happens in our latest release, let us know.
