### ISSUE TITLE
request help:  How can I add passive health check to discovery register

### ISSUE THREAD

**Issue by hwlzs** [apache/apisix#4101]
### Issue description

I am trying to write a new consul discovery register ,  i found if the ip lists are not updated from consul center ,  the apisix balance (type is roundrobin) can not automatically remove unhealthy ip by passive healthy check.
How can i conveniently realize this feature？ 

### Environment

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`): Linux centosT-ImgBcrs-8167 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.4

**Comment by spacewander** [comment]
Could you provide more details about how you configure the upstream and consul?
