### ISSUE TITLE
[discuss]：Hope apisix supports dynamic modification of nginx configuration

### ISSUE THREAD

**Issue by gaobo0202** [apache/apisix#4107]
We want to migrate the service from nginx to apisix, but the nginx configuration of the service is different. For example, many services have different configuration requirements for `client_max_body_size`, `client_body_buffer_size`, and `keepalive`. If apisix can support dynamic modification of nginx configuration, it will increase the flexibility of configuration and be more friendly to nginx users.

**Comment by spacewander** [comment]
This requires modifying Nginx itself.

We already have a project for it: https://github.com/api7/apisix-nginx-module.

As Nginx itself doesn't support dynamic configuration, it will be a very big project and cost months (or years) for us to do it.

I will close this issue as it is too general to answer. If you want to support some specific features, like setting `client_max_body_size` dynamically, you can open another issue.
