### ISSUE TITLE
chore: update architecture diagram

### ISSUE THREAD

**Issue by membphis** [apache/apisix#4112]
here is the new one:

![image](https://user-images.githubusercontent.com/6814606/115801835-49d41580-a410-11eb-8be3-30858fb52745.png)

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/115801882-61ab9980-a410-11eb-964d-9bf70ea4bc01.png)

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on this issue. Please assign me this.

**Comment by tokers** [comment]
@himanshu007-creator Assigned to you :).
