### ISSUE TITLE
request help: Is there a plan to Support SAP RFC protocol conversion？

### ISSUE THREAD

**Issue by winnetcn** [apache/apisix#4113]
### Issue description
 Is there a plan to Support SAP RFC protocol conversion？

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@winnetcn Hi,

Could you provide some literature to help us learn what is SAP RFC protocol.

**Comment by winnetcn** [comment]
Refer to this website：http://www.restcloud.cn/restcloud/mycms/sap.html and https://github.com/SAP/gorfc/blob/master/gorfc/gorfc.go
