### ISSUE TITLE
request help: 希望在openid-connect插件增加token有效期缓存机制

### ISSUE THREAD

**Issue by cranehovers** [apache/apisix#4120]
### Issue description
希望在openid-connect插件增加token缓存机制，每次和令牌服务器交互的时候，获取token的有效期，在token的有效期内，不再重复向令牌服务器请求，减少令牌服务器的压力，缩短每次请求的整体RTT

**Comment by Firstsawyou** [comment]
The openid-connect plugin does not seem to support it yet. This is a very useful feature.  @spacewander  What do you think?

**Comment by spacewander** [comment]
The library we used already supported it:
https://github.com/zmartzone/lua-resty-openidc/blob/4ff64540ece124a64f66c5f5c5ed6b2dd8a58483/lib/resty/openidc.lua#L1582
https://github.com/zmartzone/lua-resty-openidc/blob/4ff64540ece124a64f66c5f5c5ed6b2dd8a58483/lib/resty/openidc.lua#L1637

**Comment by Hey-Jobs** [comment]
这个过时机制是在插件里设置的？是否会存在和令牌服务器的token过期时间不一致的问题？

**Comment by spacewander** [comment]
The token cache feature is provided by lua-resty-openidc and is enabled by default.
If you are interested in it, please read lua-resty-openidc's doc and its source code.

**Comment by xujiesh0510** [comment]
我来补充下：

令牌服务器的 鉴权接口 返回结果：

 ```
public class UserTokenForGateway
    {
        [JsonPropertyName("access_token")]
        public string Access_Token { get; set; }
        
        public bool Active { get; set; }

        [JsonPropertyName("exp")]
        public long Exp { get; set; }
    }

```
其中 exp  值是当前 unix时间戳的秒数 + 期望缓存的秒数

另外在网关配置下：
![image](https://user-images.githubusercontent.com/10271679/116026426-544b1500-a685-11eb-8245-a09b1dbf1962.png)
