### ISSUE TITLE
request help: how to set up https？

### ISSUE THREAD

**Issue by water-gulugulu** [apache/apisix#4128]
### Environment

* apisix version (2.5):
* apisix-dashboard version (2.5)
设置https无法访问。
![image](https://user-images.githubusercontent.com/49268861/115988468-7775b600-a5ec-11eb-9eaa-0577527a56bd.png)
![image](https://user-images.githubusercontent.com/49268861/115988473-7e042d80-a5ec-11eb-92e4-d36bb0ac0697.png)

这两个不设置的话就没有问题是可以访问到的，但是设置了之后无法访问。证书也是正确的已上传

**Comment by tokers** [comment]
@water-gulugulu After you set up these two items, which behavior does APISIX show for you?

**Comment by Firstsawyou** [comment]
You should try to disable redirection.

**Comment by spacewander** [comment]
Closed as lack of response.
