### ISSUE TITLE
request help: oidc problem

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4129]
### Issue description
I configure oidc as below
![image](https://user-images.githubusercontent.com/52538259/115988603-14d0ea00-a5ed-11eb-8459-af06c593390e.png)
here is my introspection_endpoint method
![image](https://user-images.githubusercontent.com/52538259/115988633-37630300-a5ed-11eb-8d84-bf51c67bd5b2.png)
then i send request as below
![image](https://user-images.githubusercontent.com/52538259/115988673-5feafd00-a5ed-11eb-8a8a-27a944a1faee.png)
but it return back 401 Authorization Required

### Environment

* apisix version 2.4

**Comment by Firstsawyou** [comment]
This is caused by an invalid authorization header value. You should check this authorization header.
Looking at the test case, Authorization should be `"Bearer"+ "access_token"`.

https://github.com/apache/apisix/blob/8b4a36b0c233e9ceb750f3120bd5f4798ac199b8/t/plugin/openid-connect.t#L1408

**Comment by Marco-Zheng** [comment]
> This is caused by an invalid authorization header value. You should check this authorization header.
> Looking at the test case, Authorization should be `"Bearer"+ "access_token"`.
> 
> https://github.com/apache/apisix/blob/8b4a36b0c233e9ceb750f3120bd5f4798ac199b8/t/plugin/openid-connect.t#L1408

I use this one , but also doesn't work.
![image](https://user-images.githubusercontent.com/52538259/116042075-959cee00-a6a0-11eb-940b-b1541b5e3009.png)

**Comment by Marco-Zheng** [comment]
> This is caused by an invalid authorization header value. You should check this authorization header.
> Looking at the test case, Authorization should be `"Bearer"+ "access_token"`.
> 
> https://github.com/apache/apisix/blob/8b4a36b0c233e9ceb750f3120bd5f4798ac199b8/t/plugin/openid-connect.t#L1408

my service config like this
```
{
  "name": "dental-pratice-patient-web-dev",
  "desc": "患者dev服务",
  "upstream_id": "102",
  "plugins": {
    "cors": {
      "disable": false
    },
    "jwt-auth": {
      "disable": true
    },
    "limit-conn": {
      "burst": 0,
      "conn": 1,
      "default_conn_delay": 0.1,
      "disable": true,
      "key": "remote_addr",
      "rejected_code": 503
    },
    "limit-req": {
      "burst": 1,
      "disable": true,
      "key": "remote_addr",
      "rate": 3,
      "rejected_code": 503
    },
    "openid-connect": {
      "bearer_only": true,
      "client_id": "apisix",
      "client_secret": "client_secret_code",
      "disable": false,
      "discovery": "http://localhost:8888/oidc/token",
      "introspection_endpoint": "http://localhost:8888/oidc/auth",
      "introspection_endpoint_auth_method": "client_secret_basic",
      "realm": "master"
    },
    "request-id": {
      "disable": false,
      "include_in_response": true
    }
  }
}'
```

**Comment by Marco-Zheng** [comment]
> This is caused by an invalid authorization header value. You should check this authorization header.
> Looking at the test case, Authorization should be `"Bearer"+ "access_token"`.
> 
> https://github.com/apache/apisix/blob/8b4a36b0c233e9ceb750f3120bd5f4798ac199b8/t/plugin/openid-connect.t#L1408

I found the problem! `localhost:8888` is not allowed..
I would like to suggest that can accept  localhost mode.

**Comment by Marco-Zheng** [comment]
> This is caused by an invalid authorization header value. You should check this authorization header.
> Looking at the test case, Authorization should be `"Bearer"+ "access_token"`.
> 
> https://github.com/apache/apisix/blob/8b4a36b0c233e9ceb750f3120bd5f4798ac199b8/t/plugin/openid-connect.t#L1408

Here comes another problem, i set the redirect_uri, but i didn't receive it while i send a request to gateway
![image](https://user-images.githubusercontent.com/52538259/116055333-2d093d80-a6af-11eb-84ef-b438e6e562a1.png)
the error mesaage is 
![image](https://user-images.githubusercontent.com/52538259/116055476-51fdb080-a6af-11eb-937a-73a882d59eda.png)

**Comment by smlHao** [comment]
> ### Issue description
> I configure oidc as below
> ![image](https://user-images.githubusercontent.com/52538259/115988603-14d0ea00-a5ed-11eb-8459-af06c593390e.png)
> here is my introspection_endpoint method
> ![image](https://user-images.githubusercontent.com/52538259/115988633-37630300-a5ed-11eb-8d84-bf51c67bd5b2.png)
> then i send request as below
> ![image](https://user-images.githubusercontent.com/52538259/115988673-5feafd00-a5ed-11eb-8a8a-27a944a1faee.png)
> but it return back 401 Authorization Required
> 
> ### Environment
> * apisix version 2.4

hello    does the code of authserver can share with me ?
