### ISSUE TITLE
openid-connect.md  TOKEN缓存的功能

### ISSUE THREAD

**Issue by xujiesh0510** [apache/apisix#4130]
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/openid-connect.md 
这个页面能补下  token 缓存功能如何配置的文档么？ 这样就不必要每次都要请求令牌服务器了。
另外这个功能是 production-ready 么？

![image](https://user-images.githubusercontent.com/10271679/116018996-cfa4ca80-a675-11eb-93d5-367013f8f259.png)

**Comment by spacewander** [comment]
I added it to the original issue: https://github.com/apache/apisix/issues/4120#issuecomment-826455874

**Comment by xujiesh0510** [comment]
结果 见 https://github.com/apache/apisix/issues/4120
