### ISSUE TITLE
bug:  ./apisix/cli/etcd.lua:18: module 'base64' not found:

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4133]
### Issue description

When i start local apisix, here comes a problem  module 'base64' not found, the version for apisix is 2.4 

![image](https://user-images.githubusercontent.com/52538259/116025893-1c8f9d80-a684-11eb-82dc-d9f89c3c6a22.png)

### Environment

* apisix version (cmd: `apisix version`):2.4

**Comment by spacewander** [comment]
The base64 library is already declared in the rockspec: https://github.com/apache/apisix/blob/master/rockspec/apisix-2.4-0.rockspec

Please reference https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#2-install-apache-apisix and check if there is something wrong when installing APISIX.

**Comment by Marco-Zheng** [comment]
> The base64 library is already declared in the rockspec: https://github.com/apache/apisix/blob/master/rockspec/apisix-2.4-0.rockspec
> 
> Please reference https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#2-install-apache-apisix and check if there is something wrong when installing APISIX.

I install again and it works, thx a lot
