### ISSUE TITLE
request help: to disable(not ban) a consumer without changing router config?

### ISSUE THREAD

**Issue by hzbd** [apache/apisix#4135]
### Issue description
Without changing the router configuration, I just want to disable(not ban) a consumer. How to do it? 

```
// result like this.
$ curl -i -k -X GET "http://api.xxx.com/v1/index.html" -H 'apikey: 123-123-123'
HTTP/1.1 403 OK
Server: nginx/1.16.1
Date: Mon, 26 Apr 2021 13:38:14 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive

{"message":"The consumer_name has not been activated."}
```

PS：The [fault-injection](https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/fault-injection.md) plugin must act on the router to take effect.

### Environment

* apisix version: 2.4

**Comment by tokers** [comment]
Currently it doesn't support switch for consumer.

Could you please describe your scenario?

**Comment by hzbd** [comment]
![image](https://user-images.githubusercontent.com/3000843/116120942-ae35f400-a6f2-11eb-94fa-7f5fc2d103c1.png)

![image](https://user-images.githubusercontent.com/3000843/116120977-b7bf5c00-a6f2-11eb-9a35-b341f0b4ecd5.png)



In some cases, `user b(consumer 2)` 's access needs to be suspended, but it will be enabled again after a period of time. At the same time, when the `user b(consumer 2)` is suspended, the exception return code can be found in time.

**Comment by tokers** [comment]
@hzbd If you want to suspend the access of consumer `2` by some rate-limiting plugins, why not just go ahead as for now you can implement it already, we don't need to introduce another `enable/disable` status for consumers.

http://apisix.apache.org/docs/apisix/plugins/limit-count

**Comment by spacewander** [comment]
Closed as lack of response.
