### ISSUE TITLE
bug: apisix metrics sometimes slow requests get encountered

### ISSUE THREAD

**Issue by to2false** [apache/apisix#4137]
### Environment

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`): `Linux gateway 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): v3.4.13
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/21302817/116169636-c11ee780-a737-11eb-8089-d91ba6af6d6e.png) I can't reproduce it, it only happens occasionally now

additional, the server load is not high.

### What's the actual result? (including assertion message & call stack if applicable)
- metrics requested over 30s

### What's the expected result?
- metrics requested should be quick

**Comment by Firstsawyou** [comment]
> I can't reproduce it, it only happens occasionally now
> 
> additional, the server load is not high.

The metrics data is real-time, which may be related to the time interval when you call the `/apisix/prometheus/metrics` interface.

This is the log of my test calling the `/apisix/prometheus/metrics` interface:

```shell
127.0.0.1 - - [27/Apr/2021:13:52:45 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.001 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:46 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.002 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:47 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.003 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:47 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.002 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:46 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.003 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:48 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.002 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:48 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.002 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
127.0.0.1 - - [27/Apr/2021:13:52:49 +0800] 127.0.0.1:9080 "GET /apisix/prometheus/metrics HTTP/1.1" 200 8062 0.002 "-" "curl/7.29.0" - - - "http://127.0.0.1:9080"
```

**Comment by to2false** [comment]
The above metrics requests come from prometheus, the interval is 30s.
Not sure if it caused by machine resources.

An additional question, are the sources of the metrics all in memory? Or come from other places? Which places should I check?

**Comment by to2false** [comment]
I found the problem caused by sysctl net. nf_conntrack_max is too small, I increase the value of it, seems work well now.
