### ISSUE TITLE
bug: Inconsistent behavior of schema check for response-rewrite plugin between AdminAPI and ManagerAPI

### ISSUE THREAD

**Issue by imjoey** [apache/apisix#4150]
### Issue description

Regarding the `response-rewrite` plugin, the Admin API does additional checks for schema definition, such as checking whether the `body` is a valid base64 string if `body_base64` is set to `true`. While the Manager API only use `schema.json` for checking the type of properties. This would lead to incorrect data could be successfully submitted via the Dashboard, but errors occur when APISIX is trying to load them from etcd.

As said in https://github.com/openresty/lua-nginx-module/blob/master/t/013-base64.t, `ngx.decode_base64` will generates `500 Internal Server Error` for `nil` and `null` string for `""`.

### Environment

* apisix version (cmd: `apisix version`): 2.4 and master
* OS (cmd: `uname -a`): MacOS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.6

### Minimal test code / Steps to reproduce the issue

1. In the dashboard, create a route with `response-rewrite` plugin enabled;
2. Configure the `response-rewrite` plugin to only consist of the `body_base64` equals to `true`
```json
{
     "body_base64" : true,
}
```
3. Submit the  configurations

### What's the actual result? (including assertion message & call stack if applicable)

1. The route creation could be successfully submitted.
2. APISIX(v2.4) continuously generate the following logs:
```
2021/04/28 14:45:09 [error] 348311#348311: *30 [lua] config_etcd.lua:552: failed to fetch data from etcd: ...xiran/product/apisix/apisix/plugins/response-rewrite.lua:84: string argument only
stack traceback:
  [C]: in function 'error'
  /usr/local/openresty/lualib/resty/core/base64.lua:98: in function 'decode_base64'
  ...xiran/product/apisix/apisix/plugins/response-rewrite.lua:84: in function 'check_schema'
  /home/liuxiran/product/apisix/apisix/plugin.lua:572: in function 'plugin_checker'
  /home/liuxiran/product/apisix/apisix/http/route.lua:106: in function 'checker'
  /home/liuxiran/product/apisix/apisix/core/config_etcd.lua:357: in function 'sync_data'
  /home/liuxiran/product/apisix/apisix/core/config_etcd.lua:526: in function </home/liuxiran/product/apisix/apisix/core/config_etcd.lua:516>
  [C]: in function 'xpcall'
  /home/liuxiran/product/apisix/apisix/core/config_etcd.lua:516: in function </home/liuxiran/product/apisix/apisix/core/config_etcd.lua:507>,  etcd key: /apisix/routes, context: ngx.timer
```

### What's the expected result?

If we submit that configuration, the page should prompt with the error `invalid base64 content`, which is should be the same as what the APISIX AdminAPI returns.

**Comment by imjoey** [comment]
IMO, there are 2 ways to resolve this:
1. introduce the plugin-specified checking logics for each plugin into Manager API;
2. make Manager API to call Admin API for resource manipulations, as discussed in mailing thread http://mail-archives.apache.org/mod_mbox/apisix-dev/202103.mbox/%3cCAOqn2MFxPA-ZEbnsH8VQ2Hyc9hNP9McbzBFSMrcgbxwuHkD9oA@mail.gmail.com%3e;

Looking forward to what you think guys. Thanks.

**Comment by iamayushdas** [comment]
i guess the issue is resolved now, you can close the issue now

**Comment by tokers** [comment]
ping @imjoey

**Comment by imjoey** [comment]
> @imjoey i guess the issue is resolved now, you can close the issue now
> 
> 

@iamayushdas I'm afraid not yet. In ADMIN API, response-rewrite plug-in also checks if the input `body` is base64-decodable, while there is no such check in MANAGER API.

Current checks performed in MANAGER API is merely property validation, without any logical checks like ADMIN API. While, there is no such similar mechanism for additional plug-in checks in MANAGER API. Probably we would better to define the `checkSchema` method within each plug-in if it requires additional checks. Then we can exact the plugins from request data and check what we want to.

Please let me know what do you think. Thanks. @tokers @iamayushdas

**Comment by tokers** [comment]
@imjoey The second way is a long-term job, what about just fixing these problems one-by-one now?

**Comment by imjoey** [comment]
> @imjoey The second way is a long-term job, what about just fixing these problems one-by-one now?

@tokers OK, got this. I will close this issue for now and open other PRs if needed. Thanks for the guidance. 😄
