### ISSUE TITLE
bug: After installing the Apisix on ARM-based System,but it can't works properly.

### ISSUE THREAD

**Issue by Molio-tan** [apache/apisix#4157]
### Issue description
I'm sorry to ask,have you deploy the Apisix successfully on ARM-based hardware,and it works properly?No, I found the Apisix installed successfully but it cannot works properly.

### Environment

* apisix version (cmd: `apisix version`): v2.4 or v2.5
* OS (cmd: `uname -a`): Linux test123 4.19.90-17.5.ky10.aarch64 #1 SMP Fri Aug 7 13:35:33 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): v1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): v3.4.13
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): v3.6.0

### Minimal test code / Steps to reproduce the issue
I tried some method to install the Apisix,such as,`luarocks install apisix` that apisix v2.4 was installed successfully or succeed in using source code to install apisix v2.5. When I run apisix with `./bin/apisix start`,there are normal for the terminal but errors in `logs/error.log` like
[error.log](https://github.com/apache/apisix/files/6396102/error.log)

I use this [blog](https://zhuanlan.zhihu.com/p/84467919) to install apisix on 鲲鹏系统.

### What's the expected result?
I found the 'resty.worker.events' in direction` deps`
![image](https://user-images.githubusercontent.com/31587573/116501151-afc60e80-a8e2-11eb-91a6-06104ef072fa.png)
So what's wrong with it?
Thanks anyway.

**Comment by imjoey** [comment]
Hi @Molio-tan, the error logs indicate that perhaps you've installed the OpenResty and APISIX to the incorrect path. Could you please see if the path `/usr/local/apisix/` and `/usr/local/openresty` both exist? Thanks.

**Comment by tokers** [comment]
@Molio-tan How did you start APISIX? As your APISIX was installed under /root`, actually when you launch APISIX in such a path, APISIX will reject to start.

See https://github.com/apache/apisix/issues/3207 for more details.

**Comment by Firstsawyou** [comment]
Judging from the log information, there are many lua files that were not found. It is likely that the installation is abnormal. You should provide specific installation steps.
```
2021/04/28 19:20:32 [error] 86736#0: init_worker_by_lua error: /usr/local/share/lua/5.1/apisix/init.lua:95: module 'resty.worker.events' not found:
	no field package.preload['resty.worker.events']
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
	no file '/usr/local/apisix/resty/worker/events.lua'
```

**Comment by Molio-tan** [comment]
> indicate

Thanks for your reply. I use `luarocks install apisix` to install Apisix v2.4,  so it can be found on path `/usr/local/apisix`. And the OpenResty was built with source code on path `/usr/local/openresty` by manually.
So, maybe I am wrong to deal with it. But, before to use `luarocks install apisix` to install Apisix v2.4 , I tried to install Apisix with source code on path `/opt/...` and the same problem was still there.I don't understand what happened with the installed direction between the OpenResty and the Apisix.
Looking forward for your reply.

**Comment by Molio-tan** [comment]
> @Molio-tan How did you start APISIX? As your APISIX was installed under /root`, actually when you launch APISIX in such a path, APISIX will reject to start.
> 
> See #3207 for more details.

Thank you for your suggestion.  I installed the Apisix on path `/opt/...` . After reading the issue you remind, I find the error is the same. So is it not properly to install Apisix on path `/...`?

**Comment by Molio-tan** [comment]
> Judging from the log information, there are many lua files that were not found. It is likely that the installation is abnormal. You should provide specific installation steps.
> 
> ```
> 2021/04/28 19:20:32 [error] 86736#0: init_worker_by_lua error: /usr/local/share/lua/5.1/apisix/init.lua:95: module 'resty.worker.events' not found:
> 	no field package.preload['resty.worker.events']
> 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> 	no file '/usr/local/apisix/resty/worker/events.lua'
> ```

Yes certainly, I followed the [blog](https://zhuanlan.zhihu.com/p/84467919) to install the Apisix.

**Comment by tzssangglass** [comment]
@Molio-tan, hi,  from the error logs, it seems that some dependent lua packages were missing during the installation of apisix. Have you solved this problem?

**Comment by Molio-tan** [comment]
> @Molio-tan, hi, from the error logs, it seems that some dependent lua packages were missing during the installation of apisix. Have you solved this problem?

Yes, I do. I am sure it 's successful during the command execution of `make deps`, and I could find the file `events.lua` was in the path `/usr/local/share/lua/5.1/resty/worker/`.So I think the module 'resty.worker.events' was already installed.

**Comment by tzssangglass** [comment]
1. check that `events.lua` does not appear in the search path of the error log
2. check the `events.lua` file permissions

**Comment by Molio-tan** [comment]
> 1. check that `events.lua` does not appear in the search path of the error log
> 2. check the `events.lua` file permissions

Thank you for your rely.
I check the file`events.lua`esixts in the path below as the red box:
![image](https://user-images.githubusercontent.com/31587573/117289678-76bc0a00-ae9f-11eb-9dc4-db4d6ec1d8ac.png)


And the file permissions as follows
![image](https://user-images.githubusercontent.com/31587573/117289610-60ae4980-ae9f-11eb-8d48-9ac68c00b857.png)
I installed the apisix with the `root` user all the time.

**Comment by tokers** [comment]
@Molio-tan Which user are used for running APISIX?

**Comment by Molio-tan** [comment]
@tokers I ran the APISIX with the root user.

**Comment by tokers** [comment]
> @tokers I ran the APISIX with the root user.

So as the worker processes?

**Comment by Molio-tan** [comment]
@tokers Yes, during the installation and runing , I executed the command with root user.
Shall we use the efficient way to chat with each other, such as the Wechat? My wechat is Molio-tan, thanks.

**Comment by dmsolr** [comment]
@Molio-tan 
I met something like this a few days ago. But I am working non-ARM environment. Maybe there is a helping for you.

1. remove "./deps" directory.
2. following [this doc](https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md) and walking through again.
3. make deps

Free feel to ping me if it still cannot be resolved.

**Comment by Molio-tan** [comment]
@dmsolr Thank you for your solutions. I think there maybe some wrong during `make deps` too.So, I again to install APISIX by source code. Here are my steps:
1. get the source code by `git clone http://github.com/apache/apisix.git`;
2. execute `cd apisix; make deps`, since I have already install OpenResty and ETCD.

During the step 2, there is an error
![image](https://user-images.githubusercontent.com/31587573/117531345-a5a7bc80-b014-11eb-8796-e779140de686.png)
While the openssl exists Kylin v10, it's path is /opt/gmssl/. I use the example command to handle:
`luarocks config variables.OPENSSL_INCDIR /opt/gmssl/include`
`luarocks config variables.OPENSSL_LIBDIR /opt/gmssl/lib`
But it failed again. I check the script `Makefile` and delete the red box in the picture as follows:
![image](https://user-images.githubusercontent.com/31587573/117531544-7b0a3380-b015-11eb-85db-71f7ffa15a5e.png)
Luckly, it works so well until start APISIX. When `./bin/apisix start`
![image](https://user-images.githubusercontent.com/31587573/117532023-05539700-b018-11eb-82cc-9d87e68d79a8.png)
I check the openssl111 and it exists `/usr/local/openresty/openssl111`. This errors is different from the former, what happened?

**Comment by imjoey** [comment]
@Molio-tan Have you tried the similar solution provided by https://blog.csdn.net/nange_nice/article/details/82182635? Probably this may give you a quick fix.

Currently, only OpenSSL is well tested with openresty. The introduction of [GmSSL repository](https://github.com/guanzhi/GmSSL#about-gmssl) tells `Existing projects such as Apache web server can be easily ported to GmSSL with minor modification and a simple rebuild.`, so maybe there still needs some work to get along with openresty.

Since the uncommonly used GmSSL introduces too much complexity and uncertainty. Could you use OpenSSL first to check if it works? If everything goes well, I guess the only work is to make openresty successfully running on GmSSL.

Looking forward to your feedback. Thanks.

**Comment by Molio-tan** [comment]
> @Molio-tan Have you tried the similar solution provided by https://blog.csdn.net/nange_nice/article/details/82182635? Probably this may give you a quick fix.
> 
> Currently, only OpenSSL is well tested with openresty. The introduction of [GmSSL repository](https://github.com/guanzhi/GmSSL#about-gmssl) tells `Existing projects such as Apache web server can be easily ported to GmSSL with minor modification and a simple rebuild.`, so maybe there still needs some work to get along with openresty.
> 
> Since the uncommonly used GmSSL introduces too much complexity and uncertainty. Could you use OpenSSL first to check if it works? If everything goes well, I guess the only work is to make openresty successfully running on GmSSL.
> 
> Looking forward to your feedback. Thanks.

I felt SO SORRY that we came back at first on this issue.  The module 'resty.worker.events' not found.
Here are my steps:
1. install openssl111
```
tar -zf openssl-1.1.1h.tar.gz
cd openssl-1.1.1h/
./config --prefix=/usr/local/openssl111 --openssldir=/usr/local/openssl111
make && make install
```
2. install openresty
```
tar -xzf openresty-1.19.3.1.tar.gz
cd openresty-1.19.3.1/
./configure --prefix=/usr/local/openresty   --with-pcre-jit    --with-ipv6 --with-http_stub_status_module --without-http_gzip_module --with-http_realip_module  --with-http_v2_module
make && make install
ln -s /usr/local/openresty/bin/openresty /usr/bin/
```
3. set the path of 'OPENSSL_LIBDIR' and 'OPENSSL_INCDIR' by `luarocks`
```
luarocks config variables.OPENSSL_LIBDIR /usr/local/openssl111/lib
luarocks config variables.OPENSSL_INCDIR /usr/local/openssl111/include
```
4. start APISIX by `./bin/apisix start`

**Comment by Jaycean** [comment]
@Molio-tan 
 I used kylin V10 arm64 and encountered the same problem.
```
[C]: in function 'require'
	/usr/local/apisix/apisix/init.lua:95: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk
2021/05/14 10:33:35 [error] 111#111: init_worker_by_lua error: /usr/local/apisix/apisix/init.lua:95: module 'resty.worker.events' not found:
	no field package.preload['resty.worker.events']
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
	no file '/usr/local/apisix/resty/worker/events.lua'
	no file '/usr/local/apisix/resty/worker/events/init.lua'
	no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
	no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
	no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
	no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
	no file '/usr/local/openresty/lualib/resty/worker/events.lua'
	no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
	no file './resty/worker/events.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
	no file './resty/worker/events.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty/worker/events.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/resty/worker/events.so'
	no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
	no file '/usr/local/openresty/lualib/resty/worker/events.so'
	no file './resty/worker/events.so'
	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty/worker/events.so'
	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty.so'
	no file '/usr/local/apisix//deps/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/site/lualib/resty.so'
	no file '/usr/local/openresty/lualib/resty.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
```

Moreover, I tried to compile in the centos7 arm64 container, but when I created a route and tried to connect, the same error occurred. CentOS\ Alpine \kylin V10 could not, the same error

Is it possible that the path is wrong? I found that there are more "/" '/usr/local/apisix//'
```
no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
```

**Comment by Molio-tan** [comment]
> @Molio-tan
> I used kylin V10 arm64 and encountered the same problem.
> 
> ```
> [C]: in function 'require'
> 	/usr/local/apisix/apisix/init.lua:95: in function 'http_init_worker'
> 	init_worker_by_lua:2: in main chunk
> 2021/05/14 10:33:35 [error] 111#111: init_worker_by_lua error: /usr/local/apisix/apisix/init.lua:95: module 'resty.worker.events' not found:
> 	no field package.preload['resty.worker.events']
> 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> 	no file '/usr/local/apisix/resty/worker/events.lua'
> 	no file '/usr/local/apisix/resty/worker/events/init.lua'
> 	no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
> 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
> 	no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
> 	no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
> 	no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
> 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
> 	no file '/usr/local/openresty/lualib/resty/worker/events.lua'
> 	no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
> 	no file './resty/worker/events.lua'
> 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> 	no file './resty/worker/events.lua'
> 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
> 	no file '/usr/local/openresty/lualib/resty/worker/events.so'
> 	no file './resty/worker/events.so'
> 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file './resty/worker/events.so'
> 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty.so'
> 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty.so'
> 	no file '/usr/local/openresty/site/lualib/resty.so'
> 	no file '/usr/local/openresty/lualib/resty.so'
> 	no file './resty.so'
> 	no file '/usr/local/lib/lua/5.1/resty.so'
> 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> 	no file './resty.so'
> 	no file '/usr/local/lib/lua/5.1/resty.so'
> 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> 	no file '/usr/local/lib/lua/5.1/loadall.so'
> ```
> 
> Moreover, I tried to compile in the centos7 arm64 container, but when I created a route and tried to connect, the same error occurred. CentOS\ Alpine \kylin V10 could not, the same error
> 
> Is it possible that the path is wrong? I found that there are more "/" '/usr/local/apisix//'
> 
> ```
> no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> ```
> 
> cc @tokers @membphis @imjoey PTAL,
> I tried a lot of methods and encountered the same problem. Apisix(v2.4) can run, and dashboard(v2.5) can run and login.
> However, the created route cannot be accessed because apisix does not work properly.

@Jaycean I'm sorry for replying for you on time.By the way, have you solved the problem?
@imjoey Is there any good news for the problem?

**Comment by Jaycean** [comment]
> > @Molio-tan
> > I used kylin V10 arm64 and encountered the same problem.
> > ```
> > [C]: in function 'require'
> > 	/usr/local/apisix/apisix/init.lua:95: in function 'http_init_worker'
> > 	init_worker_by_lua:2: in main chunk
> > 2021/05/14 10:33:35 [error] 111#111: init_worker_by_lua error: /usr/local/apisix/apisix/init.lua:95: module 'resty.worker.events' not found:
> > 	no field package.preload['resty.worker.events']
> > 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/apisix/resty/worker/events.lua'
> > 	no file '/usr/local/apisix/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
> > 	no file './resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file './resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.so'
> > 	no file './resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file './resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty.so'
> > 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/site/lualib/resty.so'
> > 	no file '/usr/local/openresty/lualib/resty.so'
> > 	no file './resty.so'
> > 	no file '/usr/local/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file './resty.so'
> > 	no file '/usr/local/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Moreover, I tried to compile in the centos7 arm64 container, but when I created a route and tried to connect, the same error occurred. CentOS\ Alpine \kylin V10 could not, the same error
> > Is it possible that the path is wrong? I found that there are more "/" '/usr/local/apisix//'
> > ```
> > no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> > no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cc @tokers @membphis @imjoey PTAL,
> > I tried a lot of methods and encountered the same problem. Apisix(v2.4) can run, and dashboard(v2.5) can run and login.
> > However, the created route cannot be accessed because apisix does not work properly.
> 
> @Jaycean I'm sorry for replying for you on time.By the way, have you solved the problem?
> @imjoey Is there any good news for the problem?

It hasn't been solved yet.

**Comment by tzssangglass** [comment]
I installed apisix on macOS M1 (arm64) successfully, but I don't have a kylin V10 arm64 system to verify this.

**Comment by Yiyiyimu** [comment]
Successfully installed APISIX on AWS graviton2 (arm64) successfully but failed to find Kylin cloud server to test

**Comment by membphis** [comment]
@Molio-tan if you need more help, you can contact me by email: membphis@gmail.com

I think we need to log into your system environment and try to find out why.

**Comment by ysc972** [comment]
在国产环境下，启动apisix ，需要在nginx.conf文件中增加user root; 配置，才能正常启动。
In the domestic environment, to start apisix, you need to add user root in the nginx.conf file; apisix can be started normally.

**Comment by imjoey** [comment]
> > @Molio-tan
> > I used kylin V10 arm64 and encountered the same problem.
> > ```
> > [C]: in function 'require'
> > 	/usr/local/apisix/apisix/init.lua:95: in function 'http_init_worker'
> > 	init_worker_by_lua:2: in main chunk
> > 2021/05/14 10:33:35 [error] 111#111: init_worker_by_lua error: /usr/local/apisix/apisix/init.lua:95: module 'resty.worker.events' not found:
> > 	no field package.preload['resty.worker.events']
> > 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/apisix/resty/worker/events.lua'
> > 	no file '/usr/local/apisix/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
> > 	no file './resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file './resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
> > 	no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
> > 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
> > 	no file '/usr/local/openresty/lualib/resty/worker/events.so'
> > 	no file './resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file './resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file '/usr/local/apisix//deps/lib64/lua/5.1/resty.so'
> > 	no file '/usr/local/apisix//deps/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/site/lualib/resty.so'
> > 	no file '/usr/local/openresty/lualib/resty.so'
> > 	no file './resty.so'
> > 	no file '/usr/local/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > 	no file './resty.so'
> > 	no file '/usr/local/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
> > 	no file '/usr/local/lib/lua/5.1/loadall.so'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Moreover, I tried to compile in the centos7 arm64 container, but when I created a route and tried to connect, the same error occurred. CentOS\ Alpine \kylin V10 could not, the same error
> > Is it possible that the path is wrong? I found that there are more "/" '/usr/local/apisix//'
> > ```
> > no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events.lua'
> > no file '/usr/local/apisix//deps/share/lua/5.1/resty/worker/events/init.lua'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cc @tokers @membphis @imjoey PTAL,
> > I tried a lot of methods and encountered the same problem. Apisix(v2.4) can run, and dashboard(v2.5) can run and login.
> > However, the created route cannot be accessed because apisix does not work properly.
> 
> @Jaycean I'm sorry for replying for you on time.By the way, have you solved the problem?
> @imjoey Is there any good news for the problem?

@Molio-tan Hi, I just tried the apisix v2.6 in your environment, the error is gone and everything is so smooth. FYI, I installed the apisix v2.6 under `/opt/ALB-V1.0/apisix`.

**Comment by imjoey** [comment]
> 在国产环境下，启动apisix ，需要在nginx.conf文件中增加user root; 配置，才能正常启动。
> In the domestic environment, to start apisix, you need to add user root in the nginx.conf file; apisix can be started normally.

@ysc972 Hi, thanks for the feedback. Could you please provide the exact versions APISIX and OS which your solution can works on? Much appreciated.

**Comment by imjoey** [comment]
> 在国产环境下，启动apisix ，需要在nginx.conf文件中增加user root; 配置，才能正常启动。
> In the domestic environment, to start apisix, you need to add user root in the nginx.conf file; apisix can be started normally.

@ysc972  Thanks for your advice. It works with no error logs. @Molio-tan I just tried APISIX v2.6 and everything is smooth, please have a check in `/opt/ALB-V1.0/apisix`.

FYI, I made a change in `/usr/local/openresty/nginx/conf/nginx.conf` to use `user  root;` instead of `# user  nobody;`.

**Comment by ysc972** [comment]
> > 在国产环境下，启动apisix ，需要在nginx.conf文件中增加user root; 配置，才能正常启动。
> > In the domestic environment, to start apisix, you need to add user root in the nginx.conf file; apisix can be started normally.
> 
> @ysc972 Hi, thanks for the feedback. Could you please provide the exact versions APISIX and OS which your solution can works on? Much appreciated.

os : kylin v10 arm . APISIX : master

**Comment by Molio-tan** [comment]
> > 在国产环境下，启动apisix ，需要在nginx.conf文件中增加user root; 配置，才能正常启动。
> > In the domestic environment, to start apisix, you need to add user root in the nginx.conf file; apisix can be started normally.
> 
> @ysc972 Thanks for your advice. It works with no error logs. @Molio-tan I just tried APISIX v2.6 in you environment and everything is smooth, please have a check in `/opt/ALB-V1.0/apisix`.
> 
> FYI, I made a change in `/usr/local/openresty/nginx/conf/nginx.conf` to use `user root;` instead of `# user nobody;`.

@imjoey @ysc972 Thank you all,I can use apisix correctly.

**Comment by Yiyiyimu** [comment]
Hi @ysc972 do you mind add this configuration to apisix config so other users could easily run apisix on Chinese OS?

**Comment by ysc972** [comment]
> Hi @ysc972 do you mind add this configuration to apisix config so other users could easily run apisix on Chinese OS?

Hi @Yiyiyimu i have created a PR,so you can start reviewing.Thanks

**Comment by ak476565** [comment]
> > > 在国产环境下，启动apisix，需要在nginx.conf文件中增加用户root；配置，才能正常启动。
> > > 在国内环境中，开始apisix，您需要添加用户root在nginx.conf文件; apisix 可以正常启动。
> > 
> > 
> > @ysc972感谢您的建议。它没有错误日志。@Molio-tan我刚刚在你的环境中尝试了 APISIX v2.6，一切都很顺利，请检查一下`/opt/ALB-V1.0/apisix`。
> > 仅供参考，我进行了更改`/usr/local/openresty/nginx/conf/nginx.conf`以使用`user root;`而不是`# user nobody;`.
> 
> @imjoey @ysc972谢谢大家，我可以正确使用 apisix。

Hi,Can you share your ARM64 image of Apisix on DockerHub? I'm having problems compiling. thanks bro.
