### ISSUE TITLE
bug: public key decode failed

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4158]
### Issue description
![image](https://user-images.githubusercontent.com/52538259/116523878-4c030c00-a909-11eb-93c6-2c34308761a4.png)
i use the public key, but also show `OIDC introspection failed: jwt signature verification failed: Decode secret is not a valid cert/public key: ASN1 lib: nested asn1 error: wrong tag`
i try to decode it locally, and it was successed,the public key as below 
![image](https://user-images.githubusercontent.com/52538259/116524404-ec593080-a909-11eb-958a-f9130c9d3dd5.png)

```
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwOJ60pDd/d+M8NWOvn38zHWGNgFc0+6DsFLTYJiokVAAZHpDXjshkPzPsdew+4w/fkZeZzptU6JuOLbyGGNV6iJkFjQRlZVYF3twZAxEsgHnfC1irDS0s4yOdJAvqNUuivJ5VwquSNautXaIcwEK9DZUyF9iQxCiUxaSGiV/u7njW/oRSRuJ/wALdqNNw3ay6raUHV8zToJbgiLaWAwbDBXRtQsHEYsjVvLPuZZSvGb2G07rIFuqIZ/XYfuoAPDTiR0fwY6EgDK2QMoXJtplofkRLfb9dPQgxkLe08V84Iwzr+9yojRrrsdJssLp01SdcfLtGlCGHOopcKc5IxV/jwIDAQAB
```

**Comment by Firstsawyou** [comment]
What is the version of APISIX?

**Comment by Marco-Zheng** [comment]
> What is the version of APISIX?

It's 2.4

**Comment by Firstsawyou** [comment]
OK, I'll check later.

**Comment by Marco-Zheng** [comment]
> OK, I'll check later.

I found the problem, per tag was wrong, it must be `-----BEGIN PUBLIC KEY-----` not `-----BEGIN CERTIFICATE----`
you can have a try, if  it's a problem cause, i just give a little advice that the doc can be update to prevent such situation~
![image](https://user-images.githubusercontent.com/52538259/116527553-5fb07180-a90d-11eb-9e2c-f219b286c2b0.png)

**Comment by Firstsawyou** [comment]
> I found the problem, per tag was wrong, it must be `-----BEGIN PUBLIC KEY-----` not `-----BEGIN CERTIFICATE----`

Yes, welcome to fix it.

https://github.com/apache/apisix/blob/master/t/plugin/openid-connect.t#L892
