### ISSUE TITLE
bug: sls-logger 没有日志了

### ISSUE THREAD

**Issue by zwjzxh520** [apache/apisix#4161]
### Issue description
原来使用的是apisix 2.4，阿里云能正常接收到日志，升级到2.5之后，sls-logger 一直没有日志了
打开debug模式，发现没有了sls-logger的发送行为，在2.4的时候，打开debug后，能看到很多sls-logger的发送日志的。但是现在没有找到了

### Environment

* apisix version (cmd: `apisix version`):   2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):  3.4
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
I compared the code related to sls-logger in version 2.4 and 2.5, both are unchanged, please check if the sls-logger configuration is in effect first.

**Comment by Firstsawyou** [comment]
You should provide the relevant configuration information, and check the APISIX error.log to see if there is any available log information.

**Comment by zwjzxh520** [comment]
找到问题所在了。
以为 conf/config.yaml 的配置是与 conf/config-default.yaml 合并的，没想到是conf/config.yaml的配置覆盖config-default.yaml，修改了 config.yaml 的plugins属性，添加了些自定义的插件，结果只加载了这几个自定义插件，默认的插件全部未加载了。将config-default.yaml的plugins全部复制到config.yaml后就可以了。

另外，想请教 一下，怎么清除其他的 apisix 节点？
![image](https://user-images.githubusercontent.com/2184202/116710848-c9f80d80-aa04-11eb-9792-ec1f79dfc5c1.png)
这是我本地的环境，其实中有一个apisix节点是有效的，其他的都是无用的，想将无用的删除掉。

**Comment by tzssangglass** [comment]
@juzhiyuan pls take a look

**Comment by tokers** [comment]
> 找到问题所在了。
> 
> 以为 conf/config.yaml 的配置是与 conf/config-default.yaml 合并的，没想到是conf/config.yaml的配置覆盖config-default.yaml，修改了 config.yaml 的plugins属性，添加了些自定义的插件，结果只加载了这几个自定义插件，默认的插件全部未加载了。将config-default.yaml的plugins全部复制到config.yaml后就可以了。
> 
> 
> 
> 另外，想请教 一下，怎么清除其他的 apisix 节点？
> 
> ![image](https://user-images.githubusercontent.com/2184202/116710848-c9f80d80-aa04-11eb-9792-ec1f79dfc5c1.png)
> 
> 这是我本地的环境，其中只有一个apisix节点是有效的，其他的都是无用的，想将无用的删除掉。

It will be removed automatically after the key is expired.

**Comment by juzhiyuan** [comment]
fine, it seems that those 2 issues are resolved, feel free to reopen this one if needed.
