### ISSUE TITLE
New feature suggestion: support back pressure request (新功能建议:支持背压感知请求)

### ISSUE THREAD

**Issue by springrain** [apache/apisix#4169]
apisix接受到请求,背压感知上游的请求处理能力,根据上游的处理能力转发请求,如果上游消费能力跟不上,超过设置的时间,apisix就返回超时,断开请求连接.这样apisix主动背压处理了响应超时熔断等问题
-------
When apisix receives the request, the back pressure senses the upstream request processing capability, and forwards the request according to the upstream processing capability. If the upstream consumption capacity cannot keep up, and the set time is exceeded, apisix will return a timeout and disconnect the request connection. In this way, apisix will actively back pressure Deal with issues such as response timeout and fuse

**Comment by zwjzxh520** [comment]
+1

**Comment by tzssangglass** [comment]
mark

**Comment by spacewander** [comment]
Already done: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/api-breaker.md
