### ISSUE TITLE
bug: log-util print response header connection always close, is apisix use short connection to upstream ?

### ISSUE THREAD

**Issue by tangtangsara** [apache/apisix#4171]
### Issue description
log-util 打印出来的日志, 记录响应头中的 connection 一直是close
### Environment

* apisix version 2.5
* OS  mac os 11
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* luarocks version 5.1

### Minimal test code / Steps to reproduce the issue

1.
默认配置下 set $upstream_connection         '';
不传给upstream(tomcat 8.5.50)节点connection,
tomcat返回的头也不包含connection
记录的日志connection为close

请求抓包如下图
![image](https://user-images.githubusercontent.com/11268163/116720979-60313100-aa0f-11eb-8cf1-8f8807bd323b.png)

2.
强制配置 set $upstream_connection         'keep-alive';
传给upstream(tomcat 8.5.50)节点connection:"keep-alive",
tomcat返回的头包含keepalive 信息
Keep-Alive: timeout=60
Connection: keep-alive

但记录的日志connection仍然为close

请求抓包如下图
![image](https://user-images.githubusercontent.com/11268163/116720485-d5503680-aa0e-11eb-863d-9e5302232142.png)

3.
不确定apisix和upstream节点之间的通讯是否是keep-alive. 
如果一直是使用 connection:close短连接,是否会对性能有影响,是否会建立大量连接,出现大量 time_wait

**Comment by tzssangglass** [comment]
Hi, I reproduced your example and apisix does not actively modify the header connection.

my route
```json
{
    "update_time": 1619856904,
    "id": "1",
    "upstream": {
        "hash_on": "vars",
        "pass_host": "pass",
        "scheme": "http",
        "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin"
    },
    "uri": "/*",
    "create_time": 1619856904,
    "status": 1,
    "enable_websocket": true,
    "priority": 0
}
```

`127.0.0.1:1980` is a nginx server, the nginx.conf is https://github.com/apache/apisix/blob/master/benchmark/server/conf/nginx.conf

here is my request and response

```
GET
127.0.0.1:9080/hello
16:21:22.653
Pretty
Raw
Request Headers:
Connection:"keep-alive"
cache-control:"no-cache"
Postman-Token:"7d3d220d-e0d1-4958-89b4-5f3fa842f244"
User-Agent:"PostmanRuntime/7.6.0"
Accept:"*/*"
Host:"127.0.0.1:9080"
accept-encoding:"gzip, deflate"
Response Headers:
Content-Type:"text/plain; charset=utf-8"
Transfer-Encoding:"chunked"
Connection:"keep-alive"
Date:"Sat, 01 May 2021 08:21:22 GMT"
Server:"APISIX/2.5"
Response Body:Infinity
```

**Comment by tzssangglass** [comment]
You can check to see if tomcat is actively disabling keep-alive.

**Comment by Firstsawyou** [comment]
Your problem is that the response header of the APISIX proxy request has `connection:keep-alive`, but the log printed by `log-util` is `connection: close`, right?

By the way, the communication between `apisix` and `upstream` nodes is keepalive. Please see here: https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L247

**Comment by tangtangsara** [comment]
> Hi, I reproduced your example and apisix does not actively modify the header connection.
> 
> my route
> 
> ```json
> {
>     "update_time": 1619856904,
>     "id": "1",
>     "upstream": {
>         "hash_on": "vars",
>         "pass_host": "pass",
>         "scheme": "http",
>         "nodes": {
>             "127.0.0.1:1980": 1
>         },
>         "type": "roundrobin"
>     },
>     "uri": "/*",
>     "create_time": 1619856904,
>     "status": 1,
>     "enable_websocket": true,
>     "priority": 0
> }
> ```
> 
> `127.0.0.1:1980` is a nginx server, the nginx.conf is https://github.com/apache/apisix/blob/master/benchmark/server/conf/nginx.conf
> 
> here is my request and response
> 
> ```
> GET
> 127.0.0.1:9080/hello
> 16:21:22.653
> Pretty
> Raw
> Request Headers:
> Connection:"keep-alive"
> cache-control:"no-cache"
> Postman-Token:"7d3d220d-e0d1-4958-89b4-5f3fa842f244"
> User-Agent:"PostmanRuntime/7.6.0"
> Accept:"*/*"
> Host:"127.0.0.1:9080"
> accept-encoding:"gzip, deflate"
> Response Headers:
> Content-Type:"text/plain; charset=utf-8"
> Transfer-Encoding:"chunked"
> Connection:"keep-alive"
> Date:"Sat, 01 May 2021 08:21:22 GMT"
> Server:"APISIX/2.5"
> Response Body:Infinity
> ```
@tzssangglass 
您这个请求和响应是 postman (客户端 或浏览器) -> apisix之间的, 他们之间的响应我这里也是没问题的
我提交的问题是apisix -> upstream之间的,  

tomcat不会有什么问题, 因为之前通过nginx代理响应都是正常的.
而且我通过抓包,确认了 apisix 发送请求给tomcat时
 设置nginx配置 set $upstream_connection         '';   代表  无connection头, tomcat响应没有connection 头
 设置nginx配置 set $upstream_connection         'keep-alive';   代表强制启用 keep-alive, tomcat响应有connection:keepalive
这都是正确的 

@Firstsawyou 日志里面记录的响应头,一定是有问题的, 没有打印出正确的tomcat的响应头.
更重要的是, 因为这个问题引起了我的担心 , 担心 apisix和tomcat之间的连接,即便是tomcat响应了keepalive,但仍然如日志打印的connection:close一直使用短连接.
高并发的情况会大量创建连接

**Comment by tangtangsara** [comment]
> You can check to see if tomcat is actively disabling keep-alive.



> Your problem is that the response header of the APISIX proxy request has `connection:keep-alive`, but the log printed by `log-util` is `connection: close`, right?
> 
> By the way, the communication between `apisix` and `upstream` nodes is keepalive. Please see here: https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L247
检查过 已启用了
![image](https://user-images.githubusercontent.com/11268163/116786440-2d4f7180-aad1-11eb-8505-6d483dba49bc.png)

**Comment by tokers** [comment]
@tangtangsara Could you paste some logs which connection header is close in the content.

**Comment by tzssangglass** [comment]
@tangtangsara 
my request and response is client(postman) -> apisix-> upstream(nginx).

```
而且我通过抓包,确认了 apisix 发送请求给tomcat时
设置nginx配置 set $upstream_connection ''; 代表 无connection头, tomcat响应没有connection 头
设置nginx配置 set $upstream_connection 'keep-alive'; 代表强制启用 keep-alive, tomcat响应有connection:keepalive
这都是正确的
```
please post a screenshot of the packet capture

**Comment by tzssangglass** [comment]
@tangtangsara let me check it
···
设置nginx配置 set $upstream_connection ''; 代表 无connection头, tomcat响应没有connection 头
设置nginx配置 set $upstream_connection 'keep-alive'; 代表强制启用 keep-alive, tomcat响应有connection:keepalive
···

**Comment by tangtangsara** [comment]
> @tangtangsara
> my request and response is client(postman) -> apisix-> upstream(nginx).
> 
> ```
> 而且我通过抓包,确认了 apisix 发送请求给tomcat时
> 设置nginx配置 set $upstream_connection ''; 代表 无connection头, tomcat响应没有connection 头
> 设置nginx配置 set $upstream_connection 'keep-alive'; 代表强制启用 keep-alive, tomcat响应有connection:keepalive
> 这都是正确的
> ```
> 
> please post a screenshot of the packet capture

@tzssangglass 此issue的最上面, 那两张截屏就是tshark抓包的内容截屏.
分别为   set $upstream_connection ''    和 set $upstream_connection 'keep-alive'

**Comment by tzssangglass** [comment]
@tangtangsara 
How did you modify the variable `$upstream_connection`

**Comment by tangtangsara** [comment]
> @tangtangsara
> How did you modify the variable `$upstream_connection`?
> I mean did you modify this variable by modifying the file or using a plugin or something?

modify ngx_tpl.lua
![image](https://user-images.githubusercontent.com/11268163/116807760-7baf4f80-ab67-11eb-8508-cb9d96b0d12c.png)

**Comment by tzssangglass** [comment]
This modification is not recommended
Instead of modifying `ngx_tpl.lua`, what about just letting apisix do the proxy?

**Comment by spacewander** [comment]
@tangtangsara 

> 日志里面记录的响应头,一定是有问题的, 没有打印出正确的tomcat的响应头.

It is a known issue of OpenResty: https://github.com/openresty/lua-nginx-module/issues/1453#issuecomment-452944624
