### ISSUE TITLE
request help: I need tcp upstream connection result as a response to tcp client

### ISSUE THREAD

**Issue by zhangwenjian** [apache/apisix#4177]
### Issue description
I use apisix as my tcp protocol gateway, you can imagine that is a rdp gateway.
The tcp client will send final server ip address after connected with gateway, and the balancer_by_lua_block will call set_current_peer to set the assigned server ip address  as final backend. Then I need to response to the client that server is connected successfully or failed. But after set_current_peer returns, I don't known whether final backend server can be connected. How do to get the result and notify my client?

**Comment by spacewander** [comment]
This feature is not supported by Nginx's stream subsystem's proxy_pass.
But you can implement the proxy feature in Lua via `ngx.socket.tcp` and achieve it.

**Comment by zhangwenjian** [comment]
to spacewander: The solution based on ngx.socket.tcp is to overide the default implemention of upstream connection in nginx? Is there any open source code for reference?

**Comment by spacewander** [comment]
I have been heard some people did it before. Unfortunately, there is no open source code AFAIK.

**Comment by zhangwenjian** [comment]
Someone suggests to write a nginx c module to realize a own tcp protocol gateway. Actually, the core logic of my gateway is very simple, do I need to write a new full nginx stream module?

**Comment by spacewander** [comment]
The answer is yes.
