### ISSUE TITLE
request help: apisix config backup

### ISSUE THREAD

**Issue by li1234yun** [apache/apisix#4182]
### Issue description
When I use apisix in my dev environment, I want to import my dev environment config to production environment. Maybe you can think of the config backup and restore.

### Environment

* apisix version: 2.5
* OS (cmd: `uname -a`): Darwin
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.15
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Firstsawyou** [comment]
Can you use etcd data backup and recovery?

**Comment by li1234yun** [comment]
Thank you for providing the backup way! Maybe you can think of offical solution for config backup and restore to improve user experience and avoid other extra burden.

**Comment by spacewander** [comment]
Using etcd's mechanism to backup the configuration is the official solution.

**Comment by li1234yun** [comment]
OK, I see, Thank you! I will close the issus.
