### ISSUE TITLE
request help: how to resovle cjson decode empty array and emtpy object separately?

### ISSUE THREAD

**Issue by sniper-xx** [apache/apisix#4193]
### Issue description

The json data from the backend server, both have empty array and empty object. when decode the json data, it's only to controll cjson decode either to array or to object. but that leads to troubles. Is there any resolution to resolve this proplem?

**Comment by spacewander** [comment]
Could you provide an example?

`[]` will be decoded as an empty array, `{}` will be an empty object. It is not a problem.

**Comment by spacewander** [comment]
What about using `decode_array_with_array_mt`? https://github.com/openresty/lua-cjson#decode_array_with_array_mt
Can it solve your problem?

**Comment by sniper-xx** [comment]
```lua
local function wrap_result(conf, ctx)
    local result = {
        msg="ok",
        code= resp_code,
        elapsed = ngx.time()-elapsed,
        data = "__placeholder__",
        success=true
    }

    --如果完成后台数据读取,重新进行Json结果封装
    result['data'] = cjson_decode(data_buffer)
    ngx.arg[1] = cjson_encode(result)
    --local wrap_string = cjson_encode(result)
    --local ret_content = ngx.re.sub(wrap_string,'"__placeholder__"',data_buffer,'jo')
    --ngx.arg[1] = ret_content
    ngx.arg[2] = true
end
```

**Comment by sniper-xx** [comment]
The apisix use as a gateway. I want to wrap the result of backend service.  but the empty array and empty object both exists in the backend data. the problem is both empty object and empty array is encoded to either object or array.

**Comment by sniper-xx** [comment]
Is there any resolution to resovle this proplem?  I expected the empty array is decoded a array. the empty object is decoded a object.

**Comment by sniper-xx** [comment]
I try to replace the content string,but i don't known whether it affects performance?

**Comment by spacewander** [comment]
> 
> 
> What about using `decode_array_with_array_mt`? [openresty/lua-cjson#decode_array_with_array_mt](https://github.com/openresty/lua-cjson#decode_array_with_array_mt)
> Can it solve your problem?

It may solve your problem

**Comment by sniper-xx** [comment]
It's solved using decode_array_with_array_mt. thanks!
