### ISSUE TITLE
request help:  How to implement nginx rewirte funtcion (Internal redirection)

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#4198]
### Issue description
For example,  just as follow
nginx.conf
```
location / {
   rewrite ^(.*)$ /test/$1 break;
}

location /test {
...
}
```

When we visit localtion /,   nginx will internal redirect to localtion /test。I have refered to redirect plugin and proxy-rewrite plugin， none of them can implement this function。  So should  I build a new plugin to implement it？

### Environment

* apisix version (2.5):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
may close by #4152

**Comment by nanamikon** [comment]
> may close by #4152

Redirect plugin will return 302， let client to do the redirection，  but what I need is do it Internally，  for example， after rewriting， route matching should be executed again with new uri， so does the following process

**Comment by tzssangglass** [comment]
`ngx.exec` can do internal redirection, but to get this request re-routed I don't know of any good way to achieve this.
I'm wondering if there is any indirect way to accomplish this? For example, set up two routes, and the proxy-rewrite plugin on route A does a path rewrite and the rewritten path can be macth with route B,  forwards request to route B?

**Comment by spacewander** [comment]
Consider solved
