### ISSUE TITLE
request help: APISIX网关可以定制一个后台来方便用户的配置嘛

### ISSUE THREAD

**Issue by yxm-hs** [apache/apisix#4200]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Do you mean https://github.com/apache/apisix-dashboard?

**Comment by yxm-hs** [comment]
不是apisix-dashboard

**Comment by yxm-hs** [comment]
定制的这个后台能够简化授权流程，一些不是很懂计算机的用户可以通过简单的操作来授权或取消API的调用密钥

**Comment by spacewander** [comment]
We don't have plan to do it in the open source version.
