### ISSUE TITLE
request help: implement consul support

### ISSUE THREAD

**Issue by water1st** [apache/apisix#4207]
### Environment

* apisix version (cmd: `apisix version`):2.5
* OS (cmd: `uname -a`):Linux 7c30c8872c4e 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.5.
* apisix-dashboard docker image version: apache/apisix-dashboard:latest
* apisix docker image version: apache/apisix:latest

I hope apisix can load the upstream service nodes directly from consul not just key value,maybe i can write a script to implement consul support, but i don't know the how to start , and i don't know the script how to work, i need help,
I need a script tutorial, and a script example,or other discovery support implement better

**Comment by spacewander** [comment]
> load the upstream service nodes directly from consul not just key value

What does this mean? Could you give an example?

**Comment by water1st** [comment]
consul has two functions, namely, service discovery and configuration(key value stroage). Service discovery is service instance to register the endpoint in consul,consul will check the health and kick out the abnormal endpoint offline. Another function is configuration(key value storage). At present, the consul support in apisix document is key value storage. If key value storage is used to realize service discovery, it will lead to problems such as service exception and no way to automatically offline

**Comment by spacewander** [comment]
Maybe you can take a look at Consul's API: https://www.consul.io/api-docs/catalog#list-nodes-for-service

**Comment by water1st** [comment]
yes, i hope apisix consul support use this way, not just key value way, how can i implement that , maybe i need write some openrest script for implement,but i don't know how the openrest  work and i dont konw how the script work, can you offer some help?like offer some other discovery implement exmple.

**Comment by spacewander** [comment]
You can talk a look at https://github.com/apache/apisix/blob/master/apisix/discovery/consul_kv.lua
