### ISSUE TITLE
request help:APISIX 中hmac-auth插件他的认证级别只能到接口嘛

### ISSUE THREAD

**Issue by yxm-hs** [apache/apisix#4217]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by yxm-hs** [comment]
使用hmac-auth鉴权方式，只能一个接口对应一个密钥信息嘛

**Comment by Firstsawyou** [comment]
> 使用hmac-auth鉴权方式，只能一个接口对应一个密钥信息嘛

No, after the hmac-auth plugin is enabled on a route, it will match the hmac-auth plugin information configured on the consumer, and you can configure multiple hmac-auth plugins on the consumer.

**Comment by yxm-hs** [comment]
在一个consumer上开启并配置hmac-auth插件，route上开启hmac-auth插件，使用该consumer的信息及接口的信息生成密钥，这个密钥只能访问服务下用于生成密钥信息的接口，如果要访问其他接口，是不是他们都得去生成密钥，再访问。可以一个生成的密钥用于多个接口的调用嘛

**Comment by Firstsawyou** [comment]
According to the formula of the signature string, different API interfaces need to use different parameters such as `URI`. Therefore, one key cannot be used to call multiple interfaces. 
`signing_string = HTTP Method + \n + HTTP URI + \n + canonical_query_string + \n + access_key + \n + Date + \n + signed_headers_string`

**Comment by yxm-hs** [comment]
嗯呢，明白
