### ISSUE TITLE
request help: how to configure complex nginx route

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4223]
### Issue description
Our company has below complex nginx route, can we manual configure it in openresty nginx directly?
![image](https://user-images.githubusercontent.com/52538259/117908968-f583cd80-b30b-11eb-9e96-427230dcf773.png)

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-use-route-uri-for-regular-matching

**Comment by Marco-Zheng** [comment]
@spacewander Hi, i try this way to match the uri, but failed
![image](https://user-images.githubusercontent.com/52538259/118247502-d6d13280-b4d5-11eb-9c58-16cc2c9adbce.png)
then i try to

**Comment by spacewander** [comment]
The vars in route is different from the vars in traffic-split.

**Comment by Marco-Zheng** [comment]
> The vars in route is different from the vars in traffic-split.

Ok. thanks, i find another way to replace it
