### ISSUE TITLE
request help: how to manager so many api by group in apisix?

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4226]
### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@vincentwc You can leverate the labels feature, see http://apisix.apache.org/docs/dashboard/api/api for details.

**Comment by vincentwc** [comment]
> @vincentwc You can leverate the labels feature, see http://apisix.apache.org/docs/dashboard/api/api for details.

thinks for your reply, so there're any demo for labels use,  I send http request likew this,demo2 is my label-key
{{ip_addr}}:9080/apisix/admin/routes?label=demo,
 but the response is all routes which include no this lable's route  ,show as below:
`{
    "action": "get",
    "node": {
        "key": "/apisix/routes",
        "dir": true,
        "nodes": [
            {
                "modifiedIndex": 17329,
                "key": "/apisix/routes/82",
                "createdIndex": 16979,
                "value": {
                    "create_time": 1620785633,
                    "status": 1,
                    "name": "my-user-demo",
                    "upstream": {
                        "type": "roundrobin",
                        "pass_host": "pass",
                        "nodes": [
                            {
                                "host": "10.255.249.3",
                                "weight": 1,
                                "priority": 0,
                                "port": 8082
                            }
                        ],
                        "timeout": {
                            "read": 5,
                            "connect": 5,
                            "send": 5
                        },
                        "hash_on": "vars",
                        "scheme": "http"
                    },
                    "priority": 0,
                    "uris": [
                        "/user/hello"
                    ],
                    "plugins": {
                        "key-auth": {}
                    },
                    "methods": [
                        "GET"
                    ],
                    "id": "82",
                    "labels": {
                        "demo": "user",
                        "API_VERSION": "v1"
                    },
                    "update_time": 1620804633,
                    "desc": "my-user-demo-82"
                }
            },
            {
                "modifiedIndex": 17366,
                "key": "/apisix/routes/85",
                "createdIndex": 16989,
                "value": {
                    "id": "85",
                    "status": 1,
                    "name": "my-demo-product",
                    "upstream": {
                        "nodes": [
                            {
                                "weight": 1,
                                "host": "10.255.249.3",
                                "port": 8085
                            }
                        ],
                        "timeout": {
                            "read": 5,
                            "connect": 5,
                            "send": 5
                        },
                        "pass_host": "pass",
                        "type": "roundrobin"
                    },
                    "uris": [
                        "/product/hello"
                    ],
                    "desc": "my-product-demo-85",
                    "labels": {
                        "demo2": "product"
                    },
                    "update_time": 1620806525,
                    "create_time": 1620786071
                }
            }
        ]
    },
    "count": "3"
}`

**Comment by Firstsawyou** [comment]
You can use the labels filter function of [APISIX Dashboard](https://github.com/apache/apisix-dashboard) to manipulate labels.
<img width="1173" alt="截屏2021-05-12 下午5 54 24" src="https://user-images.githubusercontent.com/52862365/117955958-29321800-b34b-11eb-8c38-15179cfb47a3.png">

**Comment by vincentwc** [comment]
> You can use the labels filter function of [APISIX Dashboard](https://github.com/apache/apisix-dashboard) to manipulate labels.
> <img alt="截屏2021-05-12 下午5 54 24" width="1173" src="https://user-images.githubusercontent.com/52862365/117955958-29321800-b34b-11eb-8c38-15179cfb47a3.png">

thank you for your replay, but there are any plan to add the features at apisix not in dashboard since usually we can't use apisxi-dashborad in pro-env？ or，there are any suggestion about to implement theb route filter in apisix by ourselves
