### ISSUE TITLE
feat: append query string when using redirect with regex_uri

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#4229]
### Proposed changes
https://github.com/apache/apisix/pull/4152 supports redirect with regex, but 1. it does not append the query string from original request to the Location header, and 2. it does not encode url. I suggest fxing these as in proxy-rewrite. If everyone agrees on this I'll create a PR for the change. 

### Concerns
Proposed changes do change the behavior of current implementation, and it will cause problems if 
1. someone expects the query string to be removed, or
2. someone encodes url manually in plugin configuration, e.g. `"regex_uri": ["/abc(.*)", "/ab%20c$1"],`

**Comment by Firstsawyou** [comment]
I think this is a very good feature. For concerns, we can use a switch to decide whether to enable this feature. 
@spacewander  What do you think?

**Comment by spacewander** [comment]
Yes, we can add two options for them. We can create two PRs, each for a new feature.

**Comment by spacewander** [comment]
@Gary-Airwallex 
Will you submit a PR for the first part? Thanks!
