### ISSUE TITLE
request help: 怎么给不同的路由设置同一种类型的auth，但是名称不同？

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4230]
### Issue description
now，we have two route :routeA  and  routeB 
                         two key-auth: keyA  keyB
how to set routeA with keyA   and routeB with keyB?
有两个路由，两个key-auth吗，怎么让routeA与keyA绑定，routeB与keyB绑定

### Environment

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Firstsawyou** [comment]
You can achieve this through the consumer-restriction plugin, please refer to the documentation here: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md
