### ISSUE TITLE
request help: 怎么根据不同的用户创建不同权限

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4231]
### Environment、
对于授权管理这一块不是很了解，也看了官网的相关资料
https://apisix.apache.org/zh/docs/apisix/plugins/key-auth
但是好像没有关于不同用户的权限操作？
* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Firstsawyou** [comment]
You can configure different authentication plugins on `consumer`, and enable related authentication plugins in routing. If you want to implement different routes with different permissions, then you can refer to the use of the [consumer-restriction](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md) plugin.

**Comment by vincentwc** [comment]
> You can configure different authentication plugins on `consumer`, and enable related authentication plugins in routing. If you want to implement different routes with different permissions, then you can refer to the use of the [consumer-restriction](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md) plugin.

got it ,thanks
