### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by lgw79674057** [apache/apisix#4237]
mac 环境下，按照安装文档手册进行了
# 安装 OpenResty, etcd 和 编译工具
brew install openresty/brew/openresty luarocks lua@5.1 etcd curl git

# 开启 etcd server
brew services start etcd

# 为 etcd 服务启用 TLS
etcd --cert-file=/path/to/cert --key-file=/path/to/pkey --advertise-client-urls https://127.0.0.1:2379
然后进行
$ mkdir apisix-2.5
$ wget https://downloads.apache.org/apisix/2.5/apache-apisix-2.5-src.tgz
$ tar zxvf apache-apisix-2.5-src.tgz -C apisix-2.5

安装运行时依赖的 Lua 库：

$ make deps
检查 APISIX 的版本号：

$ ./bin/apisix version
启动 APISIX:

$ ./bin/apisix start

执行后就出现
./bin/apisix start
/usr/local/Cellar/openresty/1.19.3.1_1/luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [emerg] invalid port in resolver "fe80::96e9:eeff:fe67:db2d" in /Users/lgw/Downloads/apisixe-2.5/conf/nginx.conf:80
看端口9080也没启动起来，curl http://127.0.0.1:9080也不行，也不知道去哪里看日志

**Comment by Firstsawyou** [comment]
Have you modified the `config.yaml` configuration file?

**Comment by lgw79674057** [comment]
> Have you modified the `config.yaml` configuration file?

yes,but i have restore the `config.yaml` and it also didn't work

**Comment by lgw79674057** [comment]
> > Have you modified the `config.yaml` configuration file?
> 
> yes,but i have restore the `config.yaml` and it also didn't work
---config.ymal----

apisix:
  admin_key:
    - name: "admin"
      # yamllint disable rule:comments-indentation
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      # yamllint enable rule:comments-indentation
      role: admin

**Comment by spacewander** [comment]
What is in your `/etc/resolv.conf`?

**Comment by lgw79674057** [comment]
> What is in your `/etc/resolv.conf`?

#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
nameserver fe80::96e9:eeff:fe67:db2d
nameserver 192.168.8.1

**Comment by lgw79674057** [comment]
i have solve this issue, beacuse my mac has ipv6 at /etc/resolv.conf,so i had annotation it then it work

**Comment by spacewander** [comment]
Look like we don't support IPv6 nameserver yet.
You can work around it by configuring the `dns_resolver` field.
