### ISSUE TITLE
bug: self plugins doesn't effect under k8s env 

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4238]
### Issue description
我在本地(非k8s环境)安装了自己写的插件 是可以生效的
但是在k8s环境 做了一个apisix的镜像，配置了
![image](https://user-images.githubusercontent.com/52538259/118087869-c7c88280-b3f8-11eb-8a0d-7b9a64909359.png)

plugins目录下也有了
![image](https://user-images.githubusercontent.com/52538259/118087922-dfa00680-b3f8-11eb-82d1-568179c80661.png)
但是不知为何没有生效
![image](https://user-images.githubusercontent.com/52538259/118087955-ee86b900-b3f8-11eb-8447-9252ad13c9da.png)

### Environment

* apisix version (cmd: `apisix version`):2.4

**Comment by Firstsawyou** [comment]
Have you configured the plugin name in the plug-in list in the config.yaml file?

**Comment by Marco-Zheng** [comment]
> config.yaml

no.. i just configured in config-default.yaml, per apisix doc, config.yaml will rewrite and cover the config in config-default.yaml, so i didn't configure it
when i run the apisix locally, i didn't configure it but it can worked well

**Comment by Marco-Zheng** [comment]
> Have you configured the plugin name in the plugin list in the config.yaml file?

no.. i just configured in config-default.yaml, per apisix doc, config.yaml will rewrite and cover the config in config-default.yaml, so i didn't configure it
when i run the apisix locally, i didn't configure it but it can work well

**Comment by Firstsawyou** [comment]
It may be that there are other plugin lists in the config.yaml file, which overwrites the plug-in list in config-default.yaml.

**Comment by Firstsawyou** [comment]
Did you deploy APISIX through [apisix-helm-chart](https://github.com/apache/apisix-helm-chart) in ks8?

**Comment by Marco-Zheng** [comment]
> Did you deploy APISIX through [apisix-helm-chart](https://github.com/apache/apisix-helm-chart) in ks8?

Yeap, is there any problem with apisix-helm-chart ?

**Comment by Firstsawyou** [comment]
> > Did you deploy APISIX through [apisix-helm-chart](https://github.com/apache/apisix-helm-chart) in ks8?
> 
> Yeap, is there any problem with apisix-helm-chart ?

You can try adding your plug-in name in the plugin list here：https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L138-L177

**Comment by tokers** [comment]
@Marco-Zheng Currently we don't have an incremental way to configure custom plugins. You have to change the `value.yaml` in apisix charts.

**Comment by Marco-Zheng** [comment]
> > > Did you deploy APISIX through [apisix-helm-chart](https://github.com/apache/apisix-helm-chart) in ks8?
> > 
> > 
> > Yeap, is there any problem with apisix-helm-chart ?
> 
> You can try adding your plug-in name in the plugin list here：https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/values.yaml#L138-L177

Thanks a lot, i'll try it

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng Currently we don't have an incremental way to configure custom plugins. You have to change the `value.yaml` in apisix charts.

ok, thanks a lot~

**Comment by Marco-Zheng** [comment]
@tokers @Firstsawyou The problem has bean solved, thanks for your kindly help!
