### ISSUE TITLE
request help: How to explain the key of ‘no_cache’ in 'proxy-cache' of  plugin

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4239]
### Issue description
proxy-cache 插件中的no_cache项如何配置呢，这个值为什么是一个数组呢，数组中的值代表什么呢？数组中的值是被缓存的还是不被缓存的呢？说明文档如下：
![12312121212121](https://user-images.githubusercontent.com/31284380/118097858-cc476800-b405-11eb-89ae-e0e4068be310.png)

这句话的意思是只要数组是除了‘0’以外的值或空数组，这个插件就不启用缓存功能了是吗？
### Environment

* apisix version (cmd: `apisix version`):  2.3

**Comment by StretchV** [comment]
根据说明描述，我感觉这个‘no_cache’应该是bool值才对呀，为什么是个数组吗

**Comment by StretchV** [comment]
关于文档中的这个例子
![22222222222222](https://user-images.githubusercontent.com/31284380/118099583-04e84100-b408-11eb-96be-1f01b434b77c.jpg)
我想尝试理解一下，不知道是不是正确的
当请求  http：//XXXX/hello?test=XXXX 时，插件是不对这个请求做缓存的
当请求 http：//XXXX/hello时，由于参数test的值是‘’，所以对这个请求的值做缓存
这个理解正确吗

**Comment by StretchV** [comment]
如果我配置成
{
  "disable": false,
  "hide_cache_headers": false,
  "no_cache": [
    "XXXXX"
  ]
}
 是不是这个插件就永远不会起到缓存的目的呢

**Comment by tokers** [comment]
@StretchV This list allows you to configure some conditions so that APISIX won't cache some requests if the evolution of the condition is true.
