### ISSUE TITLE
request help: when add  jwt-auth plugin to a service/route，jwt token must contain "key" claim。

### ISSUE THREAD

**Issue by StephenYjw** [apache/apisix#4241]
### Issue description
添加 jwt 插件时，希望可以添加一个属性，指定 jwt payload 中的claim name，对应 consumer 中的 key。
比如 jwt payload 如下：
```
{
  "iss":"http://127.0.0.1",
  "client_id":"application1",
  "sub": "1234567890",
  "iat": 1516239022
}
```
## 添加 jwt 插件 ：
![image](https://user-images.githubusercontent.com/20896662/118103914-09632880-b40d-11eb-9589-619a68b99fd2.png)

## consumer 配置：
![image](https://user-images.githubusercontent.com/20896662/118103781-dfaa0180-b40c-11eb-8906-88a0404bb745.png)

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
PR is welcome!

**Comment by LiuYuHui** [comment]
Hi @spacewander, I want to help solve this issue, but I am not familar with apisix, could you provide some points about where to start?

**Comment by tzssangglass** [comment]
hi @LiuYuHui, you can start here https://apisix.apache.org/docs/general/contributor-guide/, have a good trip

**Comment by spacewander** [comment]
@LiuYuHui 
Read it: https://github.com/apache/apisix/blob/master/apisix/plugins/jwt-auth.lua

**Comment by spacewander** [comment]
@StephenYjw 
Could you confirm it?

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
