### ISSUE TITLE
request help: support ip in sni？

### ISSUE THREAD

**Issue by snowood-orz** [apache/apisix#4248]
### Issue description
When apisix was deployed in an Intranet environment, I could not add domain name resolution to the DNS server, so users could only access apisix over IP, and the protocol has to be https.

Can I access it through apisix? Or only to add a nginx in front of apisix?

### Environment

Deployed through the apisix-docker project 

* apisix version: apisix:2.4-alpine
* etcd version: etcd:3.4.9
* apisix-dashboard version: apisix-dashboard:2.5

**Comment by spacewander** [comment]
The RFC requires the SNI should not be an IP.
You can assign private domains to intranet IP in your DNS, and act yourself as a CA.
