### ISSUE TITLE
bug: nginx:/etcd/utils.lua:15: Bad http library. Should use api7-lua-resty-http instead

### ISSUE THREAD

**Issue by wwwworkhard** [apache/apisix#4249]
### Issue description
运行   ./bin/apisix start

报错： ./bin/apisix start
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [error] init_by_lua error: ...ocal/apisix-2.5//deps/share/lua/5.1/resty/etcd/utils.lua:15: Bad http library. Should use api7-lua-resty-http instead
stack traceback:
	[C]: in function 'error'
	...ocal/apisix-2.5//deps/share/lua/5.1/resty/etcd/utils.lua:15: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5//deps/share/lua/5.1/resty/etcd/v2.lua:10: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5//deps/share/lua/5.1/resty/etcd.lua:1: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5/apisix/core/etcd.lua:18: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5/apisix/core/config_etcd.lua:22: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5/apisix/core.lua:27: in main chunk
	[C]: in function 'require'
	/usr/local/apisix-2.5/apisix/init.lua:19: in main chunk
	[C]: in function 'require'
	init_by_lua:3: in main chunk

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

**Comment by Firstsawyou** [comment]
You should provide installation steps.
By the way, you need to give relevant environmental information.

**Comment by Firstsawyou** [comment]
This is a similar problem to yours, you can refer to it. https://github.com/apache/apisix/issues/4007

**Comment by wwwworkhard** [comment]
I have the same problem as you. It's not solved yet ,  i  have to try  another  one computer  make the "defps"

**Comment by wwwworkhard** [comment]
@Firstsawyou  how to solve this  problem . i   looked at the source code ,  "  if not http.tls_handshake then
    error("Bad http library. Should use api7-lua-resty-http instead")
end "

![image](https://user-images.githubusercontent.com/12581016/119499585-71185c80-bd99-11eb-98cc-4c9c36c84814.png)

**Comment by wwwworkhard** [comment]
my  server from aliyun  ,  Maybe i used safeSecurity enhancement mode .

**Comment by Firstsawyou** [comment]
> how to solve this problem

You should refer to this issue: https://github.com/apache/apisix/issues/4007 
It should solve your problem.
