### ISSUE TITLE
request help: there are any solution for install apisix cluster, it's better to supply detailed tutorial

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4250]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4

**Comment by Firstsawyou** [comment]
The data plane of Apache APISIX is stateless and can be scaled arbitrarily and flexibly. Directly deploy multiple APISIX nodes and connect them to the same set of etcd. You can also refer to the introduction here:
https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-set-up-high-available-apache-apisix-clusters

**Comment by vincentwc** [comment]
> The data plane of Apache APISIX is stateless and can be scaled arbitrarily and flexibly. Directly deploy multiple APISIX nodes and connect them to the same set of etcd. You can also refer to the introduction here:
> https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-set-up-high-available-apache-apisix-clusters

Got it.thanks

**Comment by Yiyiyimu** [comment]
Consider solved
