### ISSUE TITLE
bug: The proxy-rewrite plugin can't rewrite "X-Forwarded-Proto" header

### ISSUE THREAD

**Issue by jiayx** [apache/apisix#4252]
### Issue description

The proxy-rewrite plugin can't rewrite "X-Forwarded-Proto" header

### Environment

* apisix version 2.5 with docker
* docker image apache/apisix:2.5-centos
* etcd version 3.4
* apisix-dashboard 2.6

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. Start a http server as upstream, http server print the request header. [http server code](https://gist.github.com/mdonkers/63e115cc0c79b4f6b8b3a6b797e485c7)

2. Create a route with the "proxy-rewrite" plugin, upstream to the step 1 server, with the following plugin configuration
```json
{
  "proxy-rewrite": {
    "headers": {
      "X-Forwarded-Proto": "https"
    }
  }
}
```
3. Make a request with http, and check server's log

### What's the actual result?
X-Forwarded-Proto: http

### What's the expected result?
X-Forwarded-Proto: https

**Comment by tokers** [comment]
This is a known issue as these headers are added in nginx.conf.

**Comment by jiayx** [comment]
> This is a known issue as these headers are added in nginx.conf.
Thank you for your reply.
Is this a bug or a feature? Is there currently a way to customize the "X-Forwarded-Proto".

**Comment by spacewander** [comment]
The header is automatically set to the request's scheme.
In what situation we need to change it to a value different from the real one?

**Comment by jiayx** [comment]
The situation I encountered was this: there was a load balancer in front of apisix, and the load balancer was responsible for certificate offloading, but the load balancer did not pass the X-Forwarded-Proto header to apisix, and the services behind apisix relied on this header.

我遇到的情况是这样的：在 apisix 前面有一个负载均衡器，负载均衡器负责证书卸载，但是负载均衡器没有把 X-Forwarded-Proto 头传递给 apisix，apisix 后面的服务又依赖这个头。

**Comment by jiayx** [comment]
还有就是 proxy-rewrite plugin 没有明确表示无法重写 X-Forwarded-* 系列的头，预期就是可以重写
