### ISSUE TITLE
request help: introspection address somehow changed..

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4254]
### Issue description

I configure the discovery as below 
![image](https://user-images.githubusercontent.com/52538259/118250954-9673b380-b4d9-11eb-9513-b91320ac7b57.png)
the k8s analysis address is 172.20.253.6
![image](https://user-images.githubusercontent.com/52538259/118251192-d63a9b00-b4d9-11eb-9d96-dec514901bf7.png)
but when i sent a request to my server , somehow it show that introspection address is 172.20.7.236
![image](https://user-images.githubusercontent.com/52538259/118251217-db97e580-b4d9-11eb-851b-053f77433440.png)
i checked my introspection endpoint from auth server the ip is also 172.20.253.6 , the question is why the ip has changed..
![image](https://user-images.githubusercontent.com/52538259/118251502-40534000-b4da-11eb-81c3-c084e4daf767.png)

* apisix version (cmd: `apisix version`): 2.4
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Firstsawyou** [comment]
@gxthrj  Please take a look.

**Comment by gxthrj** [comment]
Actually, I don’t understand your question very well. There are three IPs（172.20.7.236，172.20.7.243， 172.20.253.6） in pics. Which ip do you think is wrong?

Anyway, Please show the clusterIP for service dev01 with the command like `kubectl get svc dev01 -n xxx`.

**Comment by tokers** [comment]
@Marco-Zheng By saying "I configure the discovery as below", what did you mean exactly?

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng By saying "I configure the discovery as below", what did you mean exactly?

@tokers @gxthrj Sorry, let me update the discovery info, i configure the discovery like this 
![image](https://user-images.githubusercontent.com/52538259/118425276-6efc3100-b6fb-11eb-9727-571b5363419b.png)
the  address is http://xxxxxxx.medcloud-dev1.svc.cluster.local:18080/oauth/discovery
then i check http://xxxxxxx.medcloud-dev1.svc.cluster.local's `cluster ip` in k8s is `172.20.253.6`

/oauth/discovery is one of api in auth-server, auth server will expose the api of introspection which can do token introspection, and i check the ip of introspection api is `172.20.253.6`, that's a correct address
![image](https://user-images.githubusercontent.com/52538259/118425599-1711fa00-b6fc-11eb-8f45-9eb24a553f2c.png)

But when i sent a request to my server, i print the introspection address, somehow it show that introspection address is `172.20.7.236` which is different with correct ip `172.20.253.6`, so i don't know how it works.
![image](https://user-images.githubusercontent.com/52538259/118425625-25601600-b6fc-11eb-94ba-4bfe921af2cc.png)

**Comment by tokers** [comment]
@Marco-Zheng Have you ever checked the DNS resolvers used by APISIX container?

**Comment by gxthrj** [comment]
I think the IP 172.20.7.243 is one of the IP of `dev01` pods.  Is it right?

**Comment by Marco-Zheng** [comment]
> 172.20.7.243

@gxthrj yes，`172.20.253.6` is cluster ip, `172.20.7.243` is node ip, but `172.20.7.236` is a strange ip address..

**Comment by Marco-Zheng** [comment]
> @Marco-Zheng Have you ever checked the DNS resolvers used by APISIX container?

Yeap, i didn't find any problem with DNS resolvers.

**Comment by tokers** [comment]
> > @Marco-Zheng By saying "I configure the discovery as below", what did you mean exactly?
> 
> @tokers @gxthrj Sorry, let me update the discovery info, i configure the discovery like this
> ![image](https://user-images.githubusercontent.com/52538259/118425276-6efc3100-b6fb-11eb-9727-571b5363419b.png)
> the address is http://xxxxxxx.medcloud-dev1.svc.cluster.local:18080/oauth/discovery
> then i check http://xxxxxxx.medcloud-dev1.svc.cluster.local's `cluster ip` in k8s is `172.20.253.6`
> 
> /oauth/discovery is one of api in auth-server, auth server will expose the api of introspection which can do token introspection, and i check the ip of introspection api is `172.20.253.6`, that's a correct address
> ![image](https://user-images.githubusercontent.com/52538259/118425599-1711fa00-b6fc-11eb-8f45-9eb24a553f2c.png)
> 
> But when i sent a request to my server, i print the introspection address, somehow it show that introspection address is `172.20.7.236` which is different with correct ip `172.20.253.6`, so i don't know how it works.
> ![image](https://user-images.githubusercontent.com/52538259/118425625-25601600-b6fc-11eb-94ba-4bfe921af2cc.png)

Still, be confusing.

1. `172.20.7.243` is the node IP, did you mean k8s worker node or the APISIX upstream node?
2. You said "But when I sent a request to my server", what is "my server"? Is the auth server or your backend?

**Comment by Marco-Zheng** [comment]
> > > @Marco-Zheng By saying "I configure the discovery as below", what did you mean exactly?
> > 
> > 
> > @tokers @gxthrj Sorry, let me update the discovery info, i configure the discovery like this
> > ![image](https://user-images.githubusercontent.com/52538259/118425276-6efc3100-b6fb-11eb-9727-571b5363419b.png)
> > the address is http://xxxxxxx.medcloud-dev1.svc.cluster.local:18080/oauth/discovery
> > then i check http://xxxxxxx.medcloud-dev1.svc.cluster.local's `cluster ip` in k8s is `172.20.253.6`
> > /oauth/discovery is one of api in auth-server, auth server will expose the api of introspection which can do token introspection, and i check the ip of introspection api is `172.20.253.6`, that's a correct address
> > ![image](https://user-images.githubusercontent.com/52538259/118425599-1711fa00-b6fc-11eb-8f45-9eb24a553f2c.png)
> > But when i sent a request to my server, i print the introspection address, somehow it show that introspection address is `172.20.7.236` which is different with correct ip `172.20.253.6`, so i don't know how it works.
> > ![image](https://user-images.githubusercontent.com/52538259/118425625-25601600-b6fc-11eb-94ba-4bfe921af2cc.png)
> 
> Still, be confusing.
> 
> 1. `172.20.7.243` is the node IP, did you mean k8s worker node or the APISIX upstream node?
> 2. You said "But when I sent a request to my server", what is "my server"? Is the auth server or your backend?

@tokers 
1、`172.20.7.243`is nodeIp for auth-server not APISIX upstream node
2、`my server` is  auth-server, I sent a request to my server because i'm no sure if the   introspection address which was exposed is correct address, the facts proved that the address was correct, but i don't know why apisix send introspection request to an unknown address `172.20.7.236`
![image](https://user-images.githubusercontent.com/52538259/118580315-4428e000-b7c2-11eb-936c-2a0566e41d9c.png)

**Comment by tokers** [comment]
@Marco-Zheng From the naming convention of auth-server, I believe it runs inside Kubernetes cluster, so I don't know why you use term`node ip` to describe it. What is the ClusterIP for the auth-server service?

**Comment by Marco-Zheng** [comment]
@tokers The cluster ip is 172.20.253.6, this problem seem to be resolved after restart the apisix, thanks for your kindly help
