### ISSUE TITLE
request help: How to block non-domain name (ip) access

### ISSUE THREAD

**Issue by qianjunakasumi** [apache/apisix#4255]
#### English translation

Hello, I am using APISIX to monitor HTTPS port as the traffic entrance of my application

Most of the traffic has been cleaned by CDN,
But there is still a small amount of traffic directly requesting my original IP address

This may bring hidden dangers to application security

I want to protect my application by banning IP address access

Can you tell me how to do it? Thank you for your work

`If the control does not print the log, it will be the perfect solution, I don’t want abnormal logs to appear in the file :)`

---

#### 中文原文

你好，我正在使用 APISIX 监听 HTTPS 端口作为我的应用程序的流量入口

绝大多数的流量经过了 CDN 的清洗，
但是仍有少部分的流量直接请求我的原始 IP 地址

这可能对应用安全带来隐患

我希望通过禁止 IP 地址访问来保护我的应用程序

你能告诉我怎么做吗？谢谢你的工作

`如果阻止并不打印日志，可能更加完美！我不希望看到非正常的请求写入日志，因为已经完全阻断！:)`

---

#### Additional Information 附加信息

I tried to search for keywords such as `ban ip` and `block ip` in the Issues list, but I did not get the correct results.
If you find it in the documentation or elsewhere, thank you for letting me know!

I also tried to inject Nginx configuration in `config.yaml`, but it shows conflicts during runtime and will be ignored.

我尝试在 Issues 列表中搜索 `ban ip` 、 `block ip` 等关键词，但没有得到正确结果，
如果您在文档或其他地方发现了它，谢谢你告诉我！

我还尝试在 `config.yaml` 中注入 Nginx 配置，但运行时它显示冲突，将被忽略。

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@qianjunakasumi Try [ip-restrction](http://apisix.apache.org/docs/apisix/plugins/ip-restriction).

**Comment by qianjunakasumi** [comment]
@tokers Thank you for your reply :), but it's not the expected...

When I request an undefined route, APISIX usually returns a 404 status code
BUT I want to directly **DENY**( 444 code ? ) rather than return status code when requesting IP
by this way could protects my application, which must be protected by CDN to reach the original server.

Thank you again for your reply.

---

@tokers 谢谢你的回复:)，但它不是预期的...

当我请求未定义的路由时，APISIX 通常会返回 404 状态码
但我希望请求 IP 时，直接阻断而不是返回状态码
这样可以保护我的应用程序必须经过CDN的保护才能到达源服务器

再次感谢你的回复

**Comment by qianjunakasumi** [comment]
Usually, I want to NOT print the access log when denied, because everything is invalid
通常，我希望在阻断时不打印访问日志，因为一切都是无效的

**Comment by qianjunakasumi** [comment]
alright, I drew a picture to make it easy to understand.

![image](https://user-images.githubusercontent.com/53565118/118356696-17e64700-b5a9-11eb-9381-1aef162a88cb.png)

The timeout of expected may be to return 444 etc., instead of 404, and I don't want it to record the request in log files

**Comment by tzssangglass** [comment]
If you want the fastest implementation, my idea is to add an nginx in front of apisix and let nginx do the work.

**Comment by qianjunakasumi** [comment]
@tzssangglass Thank you for your advice, it is really the fastest way! but I prefer APISIX to act as a traffic portal...instead of nginx

**Comment by tzssangglass** [comment]
alternatively you can use `radixtree_host_uri` for route matching, but this will still log the request. see https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/router.md

**Comment by qianjunakasumi** [comment]
Finally my solution is as follows:
Add nginx configuration to `http_server_configuration_snippet`

It looks like this:
```
nginx_config:
  http_server_configuration_snippet: |
    if ($host ~* MY_IP_HERE ) {
      return 418;
    }
```

And my problem was solved.

The fly in the ointment is that it cannot turn off access log printing...

---

@tokers @tzssangglass Thanks again for your help!

**Comment by qianjunakasumi** [comment]
追加：
得益于 apisix 的 nginx 配置注入，我们可以通过下列方法实现**不**记录**未成功**的请求

https://stackoverflow.com/questions/19011719/how-to-write-only-logs-with-200-status
