### ISSUE TITLE
discuss: Allow to set custom timeout for route when route belongs to service or upstream

### ISSUE THREAD

**Issue by xuchmao** [apache/apisix#4258]
### Issue description
Need to config custom timeout for route when route belongs to service or upstream. 
Sometimes we don't want to use timeout configured in service or upstream but use custom timeout instead.

### Environment
apisix version (cmd: apisix version): 2.3

**Comment by spacewander** [comment]
Wait for more votes to see if this FR is widely needed.

**Comment by tokers** [comment]
@xuchmao Indeed the Envoy xDS protoocl does this. But we still need some real scenarios to understand the necessary for this feature.

**Comment by tokers** [comment]
> @xuchmao Indeed the Envoy xDS protoocl does this. But we still need some real scenarios to understand the necessary for this feature.

Could you paste some case in real world?

**Comment by lujiajing1126** [comment]
> > @xuchmao Indeed the Envoy xDS protoocl does this. But we still need some real scenarios to understand the necessary for this feature.
> 
> Could you paste some cases in real world?

Obviously, uploading files should have longer timeout compared to a normal GET/POST

**Comment by FightingLiming** [comment]
When a service has multiple interfaces, the timeout period of each interface may be different.

**Comment by spacewander** [comment]
We can pass through the timeout via ctx:
https://github.com/apache/apisix/blob/0114c983eecee1a9a9a3f3c13c3b149f9fe7d89f/apisix/balancer.lua#L138-L140

PR is welcome!

**Comment by yxudong** [comment]
Hi, @spacewander I'd like work on this issue.
Please assign it to me.
But what extent should this feature be supported, like just precise match or should supprt regex match?

**Comment by spacewander** [comment]
> But what extent should this feature be supported, like just precise match or should supprt regex match?

I am confused. Doesn't we only need to add a timeout field as we have done with upstream?

**Comment by tokers** [comment]
> Hi, @spacewander I'd like work on this issue.
> Please assign it to me.
> But what extent should this feature be supported, like just precise match or should supprt regex match?

It seems that what you talked about is another thing? If so, we may create another issue to track, and in this thread, let's talk about custom timeout settings.

**Comment by yxudong** [comment]
Sorry, I misunderstood.
I'll work on this issue about custom timeout settings.

**Comment by tokers** [comment]
> Sorry, I misunderstood.
> I'll work on this issue about custom timeout settings.

Looking forward to your PR :)

**Comment by yxudong** [comment]
The issue can be closed. @tokers

**Comment by tokers** [comment]
> The issue can be closed. @tokers

Well done, thanks for your contribution!
