### ISSUE TITLE
docs: Improve the plugin name in the response-rewrite plugin docs

### ISSUE THREAD

**Issue by Firstsawyou** [apache/apisix#4259]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

In the response-rewrite plugin documentation, there are many ways to write `response rewrite`, for example:

<img width="834" alt="截屏2021-05-17 下午3 07 34" src="https://user-images.githubusercontent.com/52862365/118446139-dc22bd00-b721-11eb-82cd-c29f5fffaa74.png">

But in fact it should be `response-rewrite`. Therefore, we need to change the `response rewrite` in the Chinese and English documents to `response-rewrite`.

## Describe the solution you'd like

We need to change the `response rewrite` in the Chinese and English documents to `response-rewrite`.

**Comment by yxudong** [comment]
Hi , i would like to work on this issue. Please assign me this.

**Comment by Firstsawyou** [comment]
PR is welcome!
