### ISSUE TITLE
request help: apisix reload fialed, please help

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4267]
### apisix reload fialed,show as below:
`
[root@csf-2 apisix-2.5]# make reload

/usr/bin/openresty -p $PWD/  -c $PWD/conf/nginx.conf -s reload
nginx: [warn] low address bits of 10.101.42.163/24 are meaningless in /usr/local/vincent/apisix-2.5/conf/nginx.conf:190
nginx: [alert] kill(7120, 1) failed (3: No such process)
make: *** [reload] Error 1
`

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
* apisix-dashboard version, if have:2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by Firstsawyou** [comment]
How did you install APISIX? Have any changes been made to the configuration file of `config.yaml`?

**Comment by tokers** [comment]
@vincentwc It looks like your APISIX master process was killed by accidentally, so when you tried to execute make reload, the Nginx signal process get a dead master process pid.

**Comment by vincentwc** [comment]
> @vincentwc It looks like your APISIX master process was killed by accidentally, so when you tried to execute make reload, the Nginx signal process get a dead master process pid.

got it ,thanks
