### ISSUE TITLE
request help: I need to batch create route,How to do it?

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4272]
### I need to batch create route
Apisix supplied plugins -- batch-requests to do batch request, but i don't know whether it works to batch create route?
and i send by postman failed,response show as  `500 Internal Server Error`

My request params show :
`
{
    "headers": {
        "Content-Type": "application/json",
        "admin-jwt": "xxxx"
    },
    "pipeline": [
        {
            "body": {
                "desc": "my-user-demo-82",
                "labels": {
                    "demo_env": "user",
                    "user_env": "user"
                },
                "upstream": {
                    "nodes": {
                        "10.255.249.3:8082": 1
                    },
                    "type": "roundrobin"
                },
                "uri": "/user/hello"
            },
            "method": "PUT",
            "path": "/apisix/admin/routes/82"
        },
        {
            "body": {
                "desc": "my-product-demo-85",
                "labels": {
                    "demo_env": "prod",
                    "prod_env": "prod"
                },
                "upstream": {
                    "nodes": {
                        "10.255.249.3:8085": 1
                    },
                    "type": "roundrobin"
                },
                "uri": "/product/hello"
            },
            "method": "PUT",
            "path": "/product/hello"
        },
        {
            "body": {
                "desc": "my-product-demo-85",
                "labels": {
                    "demo_env": "prod",
                    "prod_env": "prod"
                },
                "upstream": {
                    "nodes": {
                        "10.255.249.3:8087": 1
                    },
                    "type": "roundrobin"
                },
                "uri": "/demo/hello"
            },
            "method": "PUT",
            "path": "/demo/hello"
        }
    ]
}
`
request uri is : /apisix/batch-requests

sorry the json is not format, it seem the github not support to pretty json

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by tokers** [comment]
> Request help without environment information will be ignored or closed.

@vincentwc Please add your environment information.

**Comment by vincentwc** [comment]
> > Request help without environment information will be ignored or closed.
> 
> @vincentwc Please add your environment information.

ok, i have add env info, hope your reply,thanks

**Comment by vincentwc** [comment]
> I think to create routes in batches, you can use shell scripts to write curl commands to call the admin api interface in batches. The `batch-requests` plugin is not recommended, and the `batch-requests` plugin does not yet support the creation of APISIX routes. Because the `body` of the `batch-requests` plugin batch request is a `string` type data.
okay, thanks
