### ISSUE TITLE
discuss: enrich the Available metrics of plugin prometheus

### ISSUE THREAD

**Issue by fukiki** [apache/apisix#4273]
### Issue description

About the plugin prometheus, in the original metric data of APISIX, the number of the available metrics is limited.

In some practical application scenarios, request_method and remote_addr are very useful monitoring metrics.

Is there a plan to enrich the [Available metrics](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md#available-metrics)，such as adding remote_addr, request_method in Status codes?
![pe](https://user-images.githubusercontent.com/59835099/118767304-2174f500-b8b0-11eb-92b2-d37192071c0c.png)

### Environment

apisix version (cmd: apisix version): 2.5

**Comment by fukiki** [comment]
> We can introduce a way to dynamically configure label with Nginx var?

If using the way to dynamically configure label with Nginx var:
1. This configure is only for Nginx default [variables](http://nginx.org/en/docs/varindex.htm).
The monitoring of some business response data requires further data processing, because it is not generic.
2. Configure the specific display item of Nginx var in Attributes of Plugin Prometheus.

**Comment by spacewander** [comment]
> This configure is only for Nginx default variables

It is enough. Keep it simple stupid.

> Attributes of Plugin Prometheus

Should be here: https://github.com/apache/apisix/blob/83436ee125d18dff9ffa3f3daeba69548a5c3243/conf/config-default.yaml#L298 as labels are global.

**Comment by fukiki** [comment]
@spacewander Thanks for your advice. I will try it.

**Comment by dmsolr** [comment]
I am interested in this. May I pick it up?
