### ISSUE TITLE
bug: `debug.yaml` not contains in apisix container in kubernetes

### ISSUE THREAD

**Issue by Yiyiyimu** [apache/apisix#4279]
### Issue description

Somehow `debug.yaml` is not contained in apisix container in kubernetes, while the same docker container has that file. As a result, when changing log level to `info`, the error log would be flushed by `debug.lua:44: read_debug_yaml(): failed to fetch /usr/local/apisix/conf/debug.yaml attributes: cannot obtain information from file '/usr/local/apisix/conf/debug.yaml': No such file or directory, context: ngx.timer`

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): lastest docker version / 2.5
* OS (cmd: `uname -a`): WSL2 x86_64 Ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.15
* Kubernetes version: 1.20.2

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. Add `error_log_level: "info"` to config.yaml
2. Deploy apisix in kubernetes, with the instruction in `./kubernetes`
3. `kubectl exec -it ${APISIX_CONTAINER} -- ls conf/` to find the missing `debug.yaml`
4. `kubectl exec -it ${APISIX_CONTAINER} -- tail logs/error.log` to get the flushing notice

**Comment by Yiyiyimu** [comment]
I still can't figure out why it happens. @gxthrj Could you have a look at it

**Comment by tokers** [comment]
The error was returned by the underlying `stat` call. It' strange, I will try to reproduce on my side later.

**Comment by gxthrj** [comment]
I am not very clear about this point, I will try to use it in local.
