### ISSUE TITLE
request help: How to implements different user|group could see different route|api info?

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4281]
### How to implements different user could see different route info?

such as : There are 400 Apis|Route and we have two group users,groupA and groupB

we need groupA can see and operate 100 Api|Route and  groupB could see and operate another 300 Api|Route，
GroupA and GroupB isolation ，There are any solution for it?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by spacewander** [comment]
Only the Enterprise version provides this role-based management. How we archive it is a business secret.
