### ISSUE TITLE
request help: how to set priority with my 3rd-party plugins?

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4284]
### how to set priority with my 3rd-party plugins?

There are any suggestion about  3rd-party plugins' priority setting ? 
第三方插件优先级设置有没有建议呢？apisix官方文档写的优先级越高，插件越先执行，不知道会不会存在第三方插件设置优先级范围不对导致官方提供的插件不能执行或者被拦截等其他情况出现，有没有一个推荐的第三方插件优先级范围？
i sent request and find some plugin's priority is negative?  it's means the plugin execute after get response?
优先级为负数是代表路由响应之后执行还是其他的场景？

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by spacewander** [comment]
> There are any suggestion about 3rd-party plugins' priority setting

You can use priority 1 ~ 100 for the plugin unless you want it to run before some builtin plugins.

The priority of all the plugins can be found here: https://github.com/apache/apisix/blob/916041d9ab21bbe47f7817869e9de77684a38fbd/t/debug/debug-mode.t#L47

> i sent request and find some plugin's priority is negative? it's means the plugin execute after get response?

The negative priority doesn't have a special meaning. It just represents that the priority is quite low.

**Comment by vincentwc** [comment]
> > There are any suggestion about 3rd-party plugins' priority setting
> 
> You can use priority 1 ~ 100 for the plugin unless you want it to run before some builtin plugins.
> 
> The priority of all the plugins can be found here:
> 
> https://github.com/apache/apisix/blob/916041d9ab21bbe47f7817869e9de77684a38fbd/t/debug/debug-mode.t#L47
> 
> > i sent request and find some plugin's priority is negative? it's means the plugin execute after get response?
> 
> The negative priority doesn't have a special meaning. It just represents that the priority is quite low.

Got it ,thanks
