### ISSUE TITLE
request help: 网关加入到app 时不时出现404

### ISSUE THREAD

**Issue by Hsuing** [apache/apisix#4287]
环境：centos7,apisix2.5, dashboard2.6

实现要求：
       访问 http://localhost:9080/uu/admin
       实际访问: http://localhost:9898/admin

实现方式：
	用apisix_dash_board 界面上正则表达

app访问时apisix日志现象404：
223.223.1.21 - - [21/May/2021:06:55:07 +0000] sixgw.xxx.com "POST /uu/api/Symbol/GetPrice HTTP/1.1" 404 0 0.001 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148" 127.0.0.1:8081 404 0.000 "http://sixgw.xxx.com/uu/api/Symbol/GetPrice"

app访问时apisix日志正常现象：
223.223.1.21 - - [21/May/2021:08:14:04 +0000] sixgw.xx.com "POST /uu/api/Symbol/GetPrice HTTP/1.1" 200 5687 0.013 "http://192.168.1.67:8848/main.html?pc=88" "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36" 127.0.0.1:8081 200 0.013 "http://sixgw.xx.com/api/Symbol/GetPrice"

apisix2.5 配置保持默认不变

dashboard2.6上配置：
路由和上游相关配置
链接：http://note.youdao.com/noteshare?id=791c8380c54e2395b5b6f23894b8b7a0

**Comment by tokers** [comment]
@Hsuing Could you reproduce this problem by tools like `curl`? We may need to capture the reason that causing this 404 and the source of 404 (apisix or backend).

**Comment by Firstsawyou** [comment]
Hi, @Hsuing 

You can refer to the use of the `regex_uri` field here (https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-rewrite.md#attributes). 
According to the information you provide, you can try to configure it like this:  
<img width="753" alt="截屏2021-05-21 下午6 09 01" src="https://user-images.githubusercontent.com/52862365/119121470-0c3ec880-ba60-11eb-98b9-e6cec2a8914e.png">

**Comment by Hsuing** [comment]
@Firstsawyou  两个都尝试了，还是这样

**Comment by Hsuing** [comment]
@tokers  通过curl 测试没有问题，到app 里面测试出现问题

**Comment by Firstsawyou** [comment]
> app访问时apisix日志现象404：
> 223.223.1.21 - - [21/May/2021:06:55:07 +0000] sixgw.xxx.com "POST /uu/api/Symbol/GetPrice HTTP/1.1" 404 0 0.001 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 14_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148" 127.0.0.1:8081 404 0.000 "http://sixgw.xxx.com/uu/api/Symbol/GetPrice"

The access request `uri` of this `app` does not seem to be rewritten as: `/api/Symbol/GetPrice`. You should provide the relevant configuration information in etcd to determine whether the configuration is correct.

**Comment by Hsuing** [comment]
etcd_route信息：
{"id":"355755448990696943","create_time":1621576371,"update_time":1621588626,"uris":["/uu/*"],"name":"uu","methods":["GET","POST","PUT","DELETE","PATCH","HEAD","OPTIONS","CONNECT","TRACE"],"plugins":{"proxy-rewrite":{"regex_uri":["^/uu/(.*)","/$1"]}},"upstream":{"nodes":[{"host":"127.0.0.1","port":8081,"weight":1}],"timeout":{"connect":6,"read":6,"send":6},"type":"roundrobin","scheme":"http","pass_host":"pass"},"labels":{"API_VERSION":"v1"},"status":1}

**Comment by Hsuing** [comment]
![image](https://user-images.githubusercontent.com/8718211/119288020-5c917280-bc7a-11eb-90d2-1f767e9f27bf.png)

**Comment by Firstsawyou** [comment]
> @Firstsawyou
> ![image](https://user-images.githubusercontent.com/8718211/119288020-5c917280-bc7a-11eb-90d2-1f767e9f27bf.png)

I did not reproduce the 404 problem locally. Do you have other similar route configurations?

**Comment by Firstsawyou** [comment]
> @tokers 通过curl 测试没有问题，到app 里面测试出现问题

It is normal to request through the `curl` tool. Maybe you need to check whether there are any differences between the app and curl request methods?

**Comment by Hsuing** [comment]
> > @tokers 通过curl 测试没有问题，到app 里面测试出现问题
> 
> It is normal to request through the `curl` tool. Maybe you need to check whether there are any differences between the app and curl request methods?


没有区别

**Comment by tzssangglass** [comment]
@Hsuing if the curl access is OK, we can assume the route is OK, so I think the problem is with the app.

is there a pattern to the app 404 exceptions? from the information listed above, no conclusions can be drawn.

**Comment by Hsuing** [comment]
> @Hsuing if the curl access is OK, we can assume the route is OK, so I think the problem is with the app.
> 
> is there a pattern to the app 404 exceptions? from the information listed above, no conclusions can be drawn.

在app 来回点击按钮，404 就会出现

**Comment by Firstsawyou** [comment]
> 在app 来回点击按钮，404 就会出现

You can capture the packet to check the difference between the normal and 404 requests when the app is accessed.

**Comment by a280238558** [comment]
![image](https://user-images.githubusercontent.com/19814473/119309639-26b3b480-bca1-11eb-9ccc-89f78044b5fd.png)
这是我配置的路由规则，偶尔出现路由匹配错误，我通过你proxy-rewrite插件日志输入如下
![image](https://user-images.githubusercontent.com/19814473/119309779-56fb5300-bca1-11eb-9012-a866e91b0d3e.png)
正常应该匹配成下面这个
![image](https://user-images.githubusercontent.com/19814473/119309812-67133280-bca1-11eb-9d85-f4d524674bca.png)

**Comment by Firstsawyou** [comment]
> 这是我配置的路由规则，偶尔出现路由匹配错误，我通过你proxy-rewrite插件日志输入如下
> ![image](https://user-images.githubusercontent.com/19814473/119309779-56fb5300-bca1-11eb-9012-a866e91b0d3e.png)
> 正常应该匹配成下面这个
> ![image](https://user-images.githubusercontent.com/19814473/119309812-67133280-bca1-11eb-9d85-f4d524674bca.png)

Judging from the screenshot information of the first log, the request was matched to other routes (`^/market/(.*)` ).
Can you provide a detailed recurring use case? For example, the request is reproduced through the `curl` tool.

**Comment by a280238558** [comment]
@Firstsawyou 不是100%出现，通过不断的执行，10次又一次会出现

**Comment by a280238558** [comment]
@Firstsawyou 
![image](https://user-images.githubusercontent.com/19814473/119323851-b8c3b900-bcb1-11eb-8fd1-f20462bc89d8.png)
这是输入的日志截图，看执行顺序，前面都正常，请看最后一次顺序有变化radixtree.lua执行完直接执行了proxy-rewrite
而不是init.lua

**Comment by Firstsawyou** [comment]
> 不是100%出现，通过不断的执行，10次又一次会出现

You should provide etcd configuration information.

**Comment by Firstsawyou** [comment]
> 这是输入的日志截图，看执行顺序，前面都正常，请看最后一次顺序有变化radixtree.lua执行完直接执行了proxy-rewrite
> 而不是init.lua

The order of the logs here does not explain the problem, because they are printed at the same time.

I did not reproduce this problem. This is my local test:

1. Create a route (The back-end service response data is: `proxy-rewrite plugin test`)

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{   
    "uri": "/test/get/proxy/rewrite",
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": ["^/test/(.*)","/$1"]          
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:8080": 1
        }
    }
}'
```

2.Test (Repeated execution many times, no 404 appeared):

```shell
for i in `seq 1 100`; do curl http://127.0.0.1:9080/test/get/proxy/rewrite; done

proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
proxy-rewrite plugin test
......
```

Maybe you should provide all the `route` configuration data bound to the proxy-rewrite plugin in etcd.

**Comment by Hsuing** [comment]
已解决，全局插件为空导致时不时出现404

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/4087
