### ISSUE TITLE
request help: custome plugin failed

### ISSUE THREAD

**Issue by vincentwc** [apache/apisix#4288]
###custome plugin failed
Step one: create plugin file show as below
apisix/custom_plugin/vincent-plugin.lua  
I just cope exampla-plugin.lua to vincent-plugin.lua  
Step two:
update makefile show as below
	$(INSTALL) -d $(INST_LUADIR)/apisix/custom_plugin
	$(INSTALL) apisix/custom_plugin/*.lua $(INST_LUADIR)/apisix/custom_plugin/
Step three:
update conf/config.yml
add   - vincent-plugin  config
Step four:
 make deps
 make reload
then ,send control api request to get all plugin info,but not vincent-plugin info 
there are anything wrong? hope your reply,thanks

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: 2.5
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by tokers** [comment]
@vincentwc You just copied the example-plugin.lua to vicent-plugin.lua, but you don't change the plugin name, right?

**Comment by vincentwc** [comment]
> @vincentwc You just copied the example-plugin.lua to vicent-plugin.lua, but you don't change the plugin name, right?

no, i have changed pluign name and config it at conf/congfig.yml

**Comment by tokers** [comment]
cc @Firstsawyou Please take a look.

**Comment by vincentwc** [comment]
> cc

**Comment by vincentwc** [comment]
> 



> cc @Firstsawyou Please take a look.

sorry,i  Misoperation and closed it ,but please help me to resolve it ,thanks

**Comment by Firstsawyou** [comment]
> > 
> 
> > cc @Firstsawyou Please take a look.
> 
> sorry,i Misoperation and closed it ,but please help me to resolve it ,thanks

Ok, I will reproduce it.

**Comment by vincentwc** [comment]
> > > 
> > 
> > 
> > > cc @Firstsawyou Please take a look.
> > 
> > 
> > sorry,i Misoperation and closed it ,but please help me to resolve it ,thanks
> 
> Ok, I will reproduce it.

thanks, it can be work when i set custom plugin in apisix/plugins file ,but it can't work when set it in my own file such as apisix/custom_plugin file and i have update makefile show this issue top,
then make deps, make run ,it can't work
当把插件放在plugins目录下时，可以生效，但是放到我自定义的目录下不能生效，已经在makefile里面添加了install项了，也在config.yml里面添加自定义插件了，make deps重新编译，然后make run 在cpntrol api里面还是查不到

**Comment by tzssangglass** [comment]
> > > > 
> > > 
> > > 
> > > > cc @Firstsawyou Please take a look.
> > > 
> > > 
> > > sorry,i Misoperation and closed it ,but please help me to resolve it ,thanks
> > 
> > 
> > Ok, I will reproduce it.
> 
> thanks, it can be work when i set custom plugin in apisix/plugins file ,but it can't work when set it in my own file such as apisix/custom_plugin file and i have update makefile show this issue top,
> then make deps, make run ,it can't work
> 当把插件放在plugins目录下时，可以生效，但是放到我自定义的目录custom下不能生效，已经在makefile里面添加了install项了，也在config.yml里面添加自定义插件了，make deps重新编译，也试过make install命令，然后make run 在control api里面还是查不到

apisix will look for the code file of the plugin from the fixed directory, maybe you also need to modify the code.

take a look at 
https://github.com/apache/apisix/blob/52cb59213de546052718f740eafddd47fa57e7f7/apisix/plugin.lua#L82-L84

**Comment by vincentwc** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > cc @Firstsawyou Please take a look.
> > > > 
> > > > 
> > > > sorry,i Misoperation and closed it ,but please help me to resolve it ,thanks
> > > 
> > > 
> > > Ok, I will reproduce it.
> > 
> > 
> > thanks, it can be work when i set custom plugin in apisix/plugins file ,but it can't work when set it in my own file such as apisix/custom_plugin file and i have update makefile show this issue top,
> > then make deps, make run ,it can't work
> > 当把插件放在plugins目录下时，可以生效，但是放到我自定义的目录custom下不能生效，已经在makefile里面添加了install项了，也在config.yml里面添加自定义插件了，make deps重新编译，也试过make install命令，然后make run 在control api里面还是查不到
> 
> apisix will look for the code file of the plugin from the fixed directory, maybe you also need to modify the code.
> 
> take a look at
> https://github.com/apache/apisix/blob/52cb59213de546052718f740eafddd47fa57e7f7/apisix/plugin.lua#L82-L84

thanks for your reply. you mean that i need update resource code to implement custom plugin file? currently, i'm not not very familiar with lua , Maybe i should learn lua first, but i hope could more convenient to use it,thanks
@Firstsawyou   Is he talking about this problem?  i need update plugin.lua code when i set custom plugin in my own file?

**Comment by tzssangglass** [comment]
> 当把插件放在plugins目录下时，可以生效，但是放到我自定义的目录custom下不能生效，已经在makefile里面添加了install项了，也在config.yml里面添加自定义插件了，m

so you can put custom plugins in the plugins directory for quick use

**Comment by Firstsawyou** [comment]
Not required. Because APISIX already supports loading plug-ins in third-party catalogs. I will follow the steps you provided to reproduce your problem. If I succeed, I will reply to you in this issue.

**Comment by vincentwc** [comment]
> Not required. Because APISIX already supports loading plugins in third-party catalogs. I will follow the steps you provided to reproduce your problem. If I succeed, I will reply to you in this issue.

I rechecked error.log and show as below:
failed to load plugin [vincent-plugin] err: module 'apisix.plugins.vincent-plugin' not found:
Looks like the custom directory is not loaded

**Comment by Firstsawyou** [comment]
> I rechecked error.log and show as below:
> failed to load plugin [vincent-plugin] err: module 'apisix.plugins.vincent-plugin' not found:
> Looks like the custom directory is not loaded

Sorry, my mistake. Currently, third-party plug-in directories are not supported. You need to put custom plug-ins in the plugins directory to take effect.


https://github.com/apache/apisix/blob/master/Makefile#L156 Here is the directory file structure used to build the luarocks way to install APISIX, but it is not a custom plugin directory.

**Comment by vincentwc** [comment]
> > I rechecked error.log and show as below:
> > failed to load plugin [vincent-plugin] err: module 'apisix.plugins.vincent-plugin' not found:
> > Looks like the custom directory is not loaded
> 
> Sorry, my mistake. Currently, third-party plug-in directories are not supported. You need to put custom plug-ins in the plugins directory to take effect.
> 
> https://github.com/apache/apisix/blob/master/Makefile#L156 Here is the directory file structure used to build the luarocks way to install APISIX, but it is not a custom plugin directory.

Got it ,thanks

**Comment by vincentwc** [comment]
> > > I rechecked error.log and show as below:
> > > failed to load plugin [vincent-plugin] err: module 'apisix.plugins.vincent-plugin' not found:
> > > Looks like the custom directory is not loaded
> > 
> > 
> > Sorry, my mistake. Currently, third-party plug-in directories are not supported. You need to put custom plug-ins in the plugins directory to take effect.
> > https://github.com/apache/apisix/blob/master/Makefile#L156 Here is the directory file structure used to build the luarocks way to install APISIX, but it is not a custom plugin directory.
> 
> Got it ,thanks
You mean that it's just useful to luarocks but not uesd for custom plugin directory?

**Comment by Firstsawyou** [comment]
> You mean that it's just useful to luarocks but not uesd for custom plugin directory?

Yes, the custom plugin code needs to be placed in the `/plugins` directory.

The directory structure of `$(INSTALL) -d $(INST_LUADIR)/apisix/custom_plugin` is used for luarocks to install APISIX, and the final plugin also needs to be placed in the `/plugins` directory.

**Comment by vincentwc** [comment]
> > You mean that it's just useful to luarocks but not uesd for custom plugin directory?
> 
> Yes, the custom plugin code needs to be placed in the `/plugins` directory.
> 
> The directory structure of `$(INSTALL) -d $(INST_LUADIR)/apisix/custom_plugin` is used for luarocks to install APISIX, and the final plugin also needs to be placed in the `/plugins` directory.

got it ,thanks, maybe  i can make son directory in plugins directory as my custom directory, i'll test it
