### ISSUE TITLE
rewrite  url、header before Authentications plugins execution

### ISSUE THREAD

**Issue by xujiesh0510** [apache/apisix#4289]
### Environment

Request help without environment information will be ignored or closed.

* apisix(docker)  version 2.4
* apisix-dashboard version 2.5

![image](https://user-images.githubusercontent.com/10271679/119128798-b1f63580-ba68-11eb-9bf9-c15ed6156558.png)

Proxy rewrite  plugin has lower priority than  Authentications plugins . 
My question is how to  rewrite header and url  before  Authentication plugins kick in .

**Comment by spacewander** [comment]
You need to write your own plugin.
