### ISSUE TITLE
bug: k8s下lua里无法解析使用etcd名称的访问地址

### ISSUE THREAD

**Issue by w7team** [apache/apisix#4299]
### Issue description
配置信息：
![image](https://user-images.githubusercontent.com/74588507/119343447-0dbef980-bcc9-11eb-86df-92a75e7b7f7e.png)

报错日志：
![image](https://user-images.githubusercontent.com/74588507/119343487-17486180-bcc9-11eb-9cbf-f3941bb5bec2.png)

服务器上ping的结果：
![image](https://user-images.githubusercontent.com/74588507/119343511-2202f680-bcc9-11eb-90b3-a382a82e7756.png)

### Environment
直接使用docker镜像测试的，apache/apisix:2.5-alpine，apache/apisix:dev均有这个问题

**Comment by tokers** [comment]
As per your error log, the DNS response code is "2: Server Failure", which means the DNS server cannot give us a response.

This is not related with APISIX itself, you should check whether your DNS service (kube-dns) works well.

**Comment by spacewander** [comment]
Closed as lack of response.
