### ISSUE TITLE
request help: charset config in ngx_tpl.lua

### ISSUE THREAD

**Issue by Yullin** [apache/apisix#4302]
### Issue description
一些情况下，Client端对于Charset的支持不完善，希望charset作为可配置项出现在config.yaml中。
另外在实际生产中还有对于log_format多种格式的需求，以及access_log多项配置（日志以syslog server=xxx的形式输出多份）
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Firstsawyou** [comment]
The current `chartset` setting is fixed in the [ngx_tpl.lua](https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L220) file, I think it is necessary to put it in config.yaml as a configurable option.

**Comment by Firstsawyou** [comment]
Assigned to me.
