### ISSUE TITLE
 transparent

### ISSUE THREAD

**Issue by rogerwangzy** [apache/apisix#4304]
apisix 基于nginx,是否支持 proxy_pass transparent ？

MQTT 协议的代理，由于并发连接数非常大，会出现  代理与 upstream 之间tcp连接数耗尽的问题（如果不支持透明代理的话）

**Comment by spacewander** [comment]
You can use `stream_configuration_snippet` to inject a new server to do it:
https://github.com/apache/apisix/blob/master/docs/zh/latest/customize-nginx-configuration.md

**Comment by rogerwangzy** [comment]
基于官方的nginx, tcp proxy_pass transparent  ，没有配置成功过。。。，haproxy也不行，想找一个能解决问题的代理，始终没找到。
