### ISSUE TITLE
bug: After enabling proxy-mirror, normal requests report 404

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#4312]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.5
* OS (cmd: `uname -a`):centos 7.3
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.14
* apisix-dashboard version, if have: 2.6
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.在配置路由时启用了proxy-mirror后,无法请求报404
路由配置的json如下:
{
"action": "get",
"node": {
"key": "/apisix/routes/356497226769367867",
"value": {
"upstream_id": "355766670582612795",
"id": "356497226769367867",
"methods": [
"GET",
"POST",
"PUT",
"DELETE",
"PATCH",
"HEAD",
"OPTIONS",
"CONNECT",
"TRACE"
],
"plugins": {
"proxy-rewrite": {
"host": "abc.test.com"
},
"proxy-mirror": {
"host": "http://10.10.1.1:8081"
}
},
"hosts": [
"test.test.com"
],
"status": 1,
"create_time": 1622018505,
"update_time": 1622020347,
"name": "carpool-operation",
"uris": [
"/test*"
]
}
},
"count": "1"
}

请求http://test.test.com/test  返回404
当禁用proxy-mirror时,请求http://test.test.com/test 返回正常

**Comment by Firstsawyou** [comment]
Okay, let me check.

**Comment by starsz** [comment]
Hi @sandy420 .What's the response body when enable the `proxy-mirror` plugin.

**Comment by sandy420** [comment]
The response returned by the mirror request is ignored.so,I don’t know what it is.

**Comment by tokers** [comment]
@sandy420 Is therey any error logs in your apisix when the 404 was triggered. Also, please pastes some contexts about the 404 requests.

**Comment by Firstsawyou** [comment]
@sandy420 
Local test did not show 404. You should check whether apisix has log information records, as @tokers  said, providing context information for 404 requests.

**Comment by spacewander** [comment]
Closed as lack of response.
