### ISSUE TITLE
request help: Set request var in header, but i don't get param from ctx.var

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4318]
### Issue description
I see that in the traffic-split of the official case of Apisix, ctx.var is the value from the request header, but when I put the parameter in the header when I requested it, I didn't get the value ?
![image](https://user-images.githubusercontent.com/52538259/119756074-91e5cc80-bed5-11eb-9136-5a4cd41bf1cf.png)
![image](https://user-images.githubusercontent.com/52538259/119756078-94482680-bed5-11eb-841b-acb2df6b1407.png)

### Environment
* apisix version (cmd: `apisix version`): 2.4

**Comment by tokers** [comment]
@Firstsawyou Please take a look when you have time.

**Comment by Firstsawyou** [comment]
The request header information will not be stored in ctx.var unless we store it in advance. The request header is obtained by using nginx's `$http_PARAMETER` method.

**Comment by tzssangglass** [comment]
like @Firstsawyou said, with `ctx.var` you can't just rely on dynamic debug to see what values are in it, there is even a portion of c data in this.

**Comment by starsz** [comment]
> The request header information will not be stored in ctx.var unless we store it in advance. The request header is obtained by using nginx's `$http_PARAMETER` method.

Not really true. Here we override the index function.
Hi @Marco-Zheng, you can refer to: 

https://github.com/apache/apisix/blob/9a40fd7cb497974f9d7bd75f128eed5dd238cdc6/apisix/core/ctx.lua#L136-L162

**Comment by spacewander** [comment]
Closed as lack of response.
