### ISSUE TITLE
request help: About Consul integration design question

### ISSUE THREAD

**Issue by SkyChenSky** [apache/apisix#4323]
I want to use consul to do discovery.
What makes me very curious is that use consul key/value without standard service discovery api and define a set of templates.
So I want to know the purpose of this design.

We look forward to your reply.
Thank you.

**Comment by spacewander** [comment]
The consul KV discovery is contributed by @yongboy 
Maybe his company uses consul KV instead of the service discovery api.

**Comment by yongboy** [comment]
If you have more than 1000 services to manage, and if you want to organize them by some logic order, choosing Key/Value form of service discovery would be a good idea.

Sorry for replying later :))

**Comment by coolincy** [comment]
kv can not check upstream's health, service can check , so why user kv?  If kv, I think redis is better.
