### ISSUE TITLE
Improve Docs: How APISIX uses non-Lua languages to write plug-ins

### ISSUE THREAD

**Issue by topzyh** [apache/apisix#4324]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

我看到 APISIX 2.6  支持使用其他语言编写自定义插件，能否补充一下相关文档、及文档发布时间？

## Describe the solution you'd like

我们准备使用 APISIX 接入公司用户认证和统一鉴权，但由于公司用户、系统众多，鉴权逻辑复杂，lua已经不能满足使用要求了，需要使用java开发；通过token和domain、uri 来鉴权

感谢 APISIX

**Comment by spacewander** [comment]
Let's watch the development of https://github.com/apache/apisix-java-plugin-runner!

**Comment by Engine-AI** [comment]
You can develop your own personalized authentication plug-in through lua, but it needs to be compatible with the dashboard

**Comment by topzyh** [comment]
> Let's watch the development of https://github.com/apache/apisix-java-plugin-runner!

有没有相关的使用文档呢，我没有找到 😭 （什么时候能补充一下 ）感谢~

**Comment by spacewander** [comment]
This project is almost finished but is not released yet. We will add the documentation before release.

**Comment by NMSAzulX** [comment]
请问有C#版本的吗?

**Comment by spacewander** [comment]
Currently we don't have plan to add C# support.

**Comment by belongwqz** [comment]
what about python?

**Comment by spacewander** [comment]
Currently we don't have plan to add Python support.
