### ISSUE TITLE
bug: set https certificate but doesn't work

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4343]
### Issue description
I set https certificate but doesn't work
![image](https://user-images.githubusercontent.com/52538259/120160604-0055c200-c229-11eb-9f5d-629bc86ee59f.png)
http://test-hello.laoganma.fun/ is ok but https://test-hello.laoganma.fun/ exist with timeout
![image](https://user-images.githubusercontent.com/52538259/120160417-cf758d00-c228-11eb-8c98-b4af44dccb92.png)

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.4

**Comment by spacewander** [comment]
Need to provide detailed configuration (etcd data, etc.), and the steps to reproduce it.

**Comment by Marco-Zheng** [comment]
@spacewander Hi, my etcd version is etcd-5.2.1, apisix version (cmd: apisix version): 2.4, apisix-dashboard version: 2.5

**Comment by spacewander** [comment]
Don't send us the screenshot. We can't copy your configuration from it. And you doesn't show the most important part: the SSL configuration.

**Comment by Marco-Zheng** [comment]
@spacewander 
Sorry, here is the route configuration
```
{
  "uris": [
    "/*"
  ],
  "name": "test-hello",
  "methods": [
    "GET",
    "HEAD",
    "POST",
    "PUT",
    "DELETE",
    "OPTIONS",
    "PATCH"
  ],
  "hosts": [
    "test-hello.laoganma.fun"
  ],
  "upstream_id": "357208006879871749",
  "status": 1
}
```
SNI is `*.laoganma.fun` `laoganma.fun` , the certificate is private so i can't paste it, is there any other  SSL configuration need to be added 
![image](https://user-images.githubusercontent.com/52538259/120186231-cfd05100-c245-11eb-9303-314cecf9185b.png)

**Comment by spacewander** [comment]
Could you also provide the packet capture file?

**Comment by starsz** [comment]
> no error was found, no request path was found after checking access.log

Can you try to use `curl` with --resolve option?

**Comment by tokers** [comment]
@Marco-Zheng Could you tell us the particular error message?

You may also use `openssl s_client` to check the TLS handshaking details like:

```sh
openssl s_client -connect {APISIX HTTPS Host}:{APISIX HTTPS PORT} -servername test-hello.laoganma.fun
```

**Comment by Marco-Zheng** [comment]
@spacewander @tokers @starsz Hi, i use command`openssl s_client -connect {APISIX HTTPS Host}:{APISIX HTTPS PORT} -servername test-hello.laoganma.fun
` locally, it show that `no peer certificate available`
![image](https://user-images.githubusercontent.com/52538259/120258007-e0bfa780-c2c3-11eb-937e-474a5e3d8a7d.png)

**Comment by tokers** [comment]
@Marco-Zheng It seems that APISIX doesn't return the correct cert for this connection, you may try to adjust the error_log level (for instance, `info` )and see some detailed error message.

**Comment by Marco-Zheng** [comment]
@tokers Ok, i'll have a try, my apisix deploy on k8s, there has node port 30017 map to apisix port 80, but ssl port for apisix is 443, may be we need expose it?

**Comment by tokers** [comment]
> @tokers Ok, i'll have a try, my apisix deploy on k8s, there has node port 30017 map to apisix port 80, but ssl port is 443, may be we need expose it?

How did you deploy your APISIX?

**Comment by Marco-Zheng** [comment]
> > @tokers Ok, i'll have a try, my apisix deploy on k8s, there has node port 30017 map to apisix port 80, but ssl port is 443, may be we need expose it?
> 
> How did you deploy your APISIX?

@tokers by using helm chart

**Comment by tokers** [comment]
> > > @tokers Ok, i'll have a try, my apisix deploy on k8s, there has node port 30017 map to apisix port 80, but ssl port is 443, may be we need expose it?
> > 
> > 
> > How did you deploy your APISIX?
> 
> @tokers by using helm chart

PR's welcome to optimize it.
