### ISSUE TITLE
request help:  如何使用 _M.check_schema 方法?

### ISSUE THREAD

**Issue by NMSAzulX** [apache/apisix#4350]
### Issue description

请问这个方法有非常详细的解释文档吗?
对下面的代码有些疑问:
1. cached_validator 方法的逻辑在哪里?  具体是用来做什么的? 是为了缓存验证结果吗?
2. validator 方法的逻辑在哪里? 这个是为了校验传入来的 JSON 实体与格式是否匹配?  

``` lua
local function get_validator(schema)
    local validator, err = cached_validator(schema, nil,
                                create_validator, schema)

    if not validator then
        return nil, err
    end

    return validator, nil
end

function _M.check(schema, json)
    local validator, err = get_validator(schema)

    if not validator then
        return false, err
    end

    return validator(json)
end
```
3. 这里我可以直接返回 ok 吗? 我们场景就是高度信任的, 不需要验证这些, 如果直接返回 ok 会影响其他插件吗?
``` lua
-- key-auth
function _M.check_schema(conf, schema_type)
    if schema_type == core.schema.TYPE_CONSUMER then
        return core.schema.check(consumer_schema, conf)
    else
        return core.schema.check(schema, conf)
    end
end
```
4. 配置格式验证后期会设计成只验证一次吗?比如只在注册插件的时候验证一次?

**Comment by spacewander** [comment]
> cached_validator 方法的逻辑在哪里? 具体是用来做什么的? 是为了缓存验证结果吗?

Function cached_validator is `create_validator` with the lrucache wrapper.

> validator 方法的逻辑在哪里? 

validator is generated by jsonschema

> 这个是为了校验传入来的 JSON 实体与格式是否匹配?

Yes

> 如果直接返回 ok 会影响其他插件吗?

No. Just affect the schema check of this plugin.

> 配置格式验证后期会设计成只验证一次吗?比如只在注册插件的时候验证一次?

We need to check the schema again each time the plugin configuration is changed.

**Comment by NMSAzulX** [comment]
好的,多谢!
