### ISSUE TITLE
request help: 如何将已写好的 xxx.lua 插件上传到正在运行的网关服务中去?

### ISSUE THREAD

**Issue by NMSAzulX** [apache/apisix#4354]
### Issue description

刚刚写好 .lua 插件,  运维家里就出事了,  现在登录不上服务器,  如何将 .lua 文件上传到正在运行的网关中去, 并启用??

**Comment by juzhiyuan** [comment]
Hi, AFAIK, you have to put the Plugin file under the APISIX project. Wait for others' confirmation.

**Comment by NMSAzulX** [comment]
@juzhiyuan  多谢....

**Comment by tokers** [comment]
@NMSAzulX Hmmm, that's unfortunate, but you can use the serverless plugins to write dynamic Lua codes.

**Comment by tokers** [comment]
> @NMSAzulX Hmmm, that's unfortunate, but you can use the serverless plugins to write dynamic Lua codes.

Hopefully it can help you.
