### ISSUE TITLE
bug: unable to pass Getting started, curl connections refused

### ISSUE THREAD

**Issue by laurentperez** [apache/apisix#4355]
### Issue description

following https://apisix.apache.org/docs/apisix/getting-started

it fails on first curl with connection refused

`curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

curl: (7) Failed to connect to 127.0.0.1 port 9080: Connexion refusée

curl http://127.0.0.1:9090/v1/server_info fails too, connection refused

docker ps
```
zsh 14286 %-git:(master(origin/master)|) dps
CONTAINER ID   IMAGE                         COMMAND                  CREATED         STATUS                          PORTS                  NAMES
3a92eec85681   apache/apisix:2.5-alpine      "sh -c '/usr/bin/api…"   9 minutes ago   Restarting (1) 15 seconds ago                          docker-apisix_apisix_1
7b98f516aa7c   bitnami/etcd:3.4.15           "/opt/bitnami/script…"   9 minutes ago   Restarting (1) 35 seconds ago                          docker-apisix_etcd_1
bfb29ea1c752   nginx:1.19.0-alpine           "/docker-entrypoint.…"   9 minutes ago   Up 9 minutes                    0.0.0.0:9082->80/tcp   docker-apisix_web2_1
381de7b223f6   apache/apisix-dashboard:2.6   "/usr/local/apisix-d…"   9 minutes ago   Restarting (2) 10 seconds ago                          docker-apisix_apisix-dashboard_1
d1ace60362c5   nginx:1.19.0-alpine           "/docker-entrypoint.…"   9 minutes ago   Up 9 minutes                    0.0.0.0:9081->80/tcp   docker-apisix_web1_1
```

using docker logs docker-apisix_apisix_1 there are etcd errors

```
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
request etcd endpoint 'http://etcd:2379/version' error, temporary failure in name resolution
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init

```

```
2021-06-01 14:44:37.926911 W | pkg/fileutil: check file permission: directory "/bitnami/etcd/data" exist, but the permission is "drwxrwxr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
2021-06-01 14:44:37.926943 C | etcdmain: cannot access data directory: open /bitnami/etcd/data/.touch: permission denied

```

### Environment

Bug report without environment information will be ignored or closed.

master clone of https://github.com/apache/apisix-docker.git

zsh 14288 %-git:(master(origin/master)|) uname -a
Linux ITK-P-202008-03 5.8.0-53-generic #60-Ubuntu SMP Thu May 6 07:46:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. follow https://apisix.apache.org/docs/apisix/getting-started
2. curl will fail
3.

**Comment by tzssangglass** [comment]
Similar to this https://github.com/apache/apisix-docker/issues/173, it is being resolved.
