### ISSUE TITLE
request help: route discovery

### ISSUE THREAD

**Issue by liujin1993** [apache/apisix#4356]
### 描述
我们使用nginx做的网关，后端有很多微服务。目前维护了近百个配置文件，每天要花费很多时间在配置路由上。

之前迁移了一部分服务到apisix，apisix对接eureka后，实现了upstream的自动发现，但是还是要手动配置路由。

所以想请教下，apisix有没有**路由发现**的功能，即：服务将自己的ip和route注册到eureka，apisix对接eureka自动生成upstream和route

可以参考traefik，也有点像xDS协议中的rDS
![image](https://user-images.githubusercontent.com/31949674/120361050-0092b200-c33c-11eb-8389-6ef07e54e8f9.png)

### description
We use nginx as gateway, and maintain hundreds of config files because of a large number of micro services.

Rencently we migrate some service from nginx to apisix. We use eureka as registry center, and apisix can generate upstreams  automatically. However, route can not be generated automatically, and we still need config route in dashboard.

I wonder if apisix has route discovery like traefik, thank you.

**Comment by tzssangglass** [comment]
Now it is not. I have a question, if apisix gets route from eureka, what route is configured on apisix?

**Comment by tylitianrui** [comment]
@spacewander  why not establish a new standard  of it

**Comment by spacewander** [comment]
@wanyuetian @tylitianrui @liujin1993 
We can extend https://github.com/api7/apisix-mesh-agentto support more discovery sources.
CC @tokers @lingsamuel

**Comment by tokers** [comment]
> @wanyuetian @tylitianrui @liujin1993
> We can extend https://github.com/api7/apisix-mesh-agent to support more discovery sources.
> CC @tokers @lingsamuel

Yep, actually @lingsamuel already works on this, see https://github.com/api7/apisix-mesh-agent/pull/64 for the details.
