### ISSUE TITLE
request help: create consumer

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix#4363]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): 60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): "3.4.0"
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0
 
I am trying to create consumer but from aremote machine using this command 
curl http://192.168.156.8:9080/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d ' {
	"username": "HozaBC",
	"plugins": {
	"key-auth": {
	"key": "1672UvWs3VavrT56iJVGdUa2DX2YPBQ5tVq9ptXnYcSa"
	},
	"ip-restriction": {
	"whitelist": "0.0.0.0/0"]		
	}	
	}
	}'
and I am facing this issue 

![image](https://user-images.githubusercontent.com/79872781/120544141-612df780-c3ed-11eb-9569-b3e20a874441.png)

=========
But it works fine when I replace the IP address "192.168.156.8" with "127.0.0.1"
could you please help me to fix this issue?

**Comment by Yiyiyimu** [comment]
Hi @hozaifaaoud Where are you deploying apisix, on both local and remote machines?

**Comment by hozaifaaoud** [comment]
it works now .... thanks for your quick support
