### ISSUE TITLE
request help: Set parameters in nginx.conf

### ISSUE THREAD

**Issue by Ben0625** [apache/apisix#4365]
We want to migrate the service from nginx to apisix, but some parameters need to be set. To be specific, in `nginx.conf` we have a fixed setting for `client_max_body_size 10m`, `client_body_buffer_size 10m`, `proxy_buffer_size 10m` and `proxy_buffers 8 10m`. For APISIX I only see `client_max_body_size` parameter in config-default.yaml, so I can change this parameter successfully. But when I try to set other parameters like this one, they all fail. How can I set these 3 other parameters in nginx.conf?

**Comment by spacewander** [comment]
You can do it with: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

**Comment by Ben0625** [comment]
My version is 2.0
Does it mean that I cannot customize Nginx configuration?...
