### ISSUE TITLE
request help: Why is it wrong when I modify the URI of the route

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4366]
### Issue description
<img width="1381" alt="QQ20210603-0" src="https://user-images.githubusercontent.com/31284380/120600774-bca6c680-c47b-11eb-8957-0325232eb6c3.png">

为什么我修改uris时apisix报错呢,修改其他的属性是没问题的

### Environment
2.3
Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.3
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by StretchV** [comment]
原来是这条路由原来存的是uri,...但是如果我想把这条路由的uri改成数组我该怎么请求修改操作呢

**Comment by Firstsawyou** [comment]
You can do this:
```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d '{
    "uri": null,
    "uris": ["/a","/b"]
}'
```

**Comment by Firstsawyou** [comment]
You can do this:
```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d '{
    "uri": null,
    "uris": ["/a","/b"]
}'
```

**Comment by spacewander** [comment]
Closed as lack of response.
