### ISSUE TITLE
check duplicate service to avoid duplicate creation

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4369]
# Improve Docs
When i using below command to add upstream, apisix can create duplicate upstream
```
curl "http://127.0.0.1:9080/apisix/admin/upstreams" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X POST -d '
{
  "nodes": [
    {
      "host": "127.0.0.1",
      "port": 8080,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6000,
    "read": 6000,
    "send": 6000
  },
  "type": "roundrobin",
  "pass_host": "pass",
  "name": "dental-practice-patient-web-dev"
}'
```
![image](https://user-images.githubusercontent.com/52538259/120616752-10211080-c48c-11eb-9729-9ca270a11bee.png)

## Please describe which part of docs should be improved or typo fixed
suggest that apisix can check duplicate service to avoid duplicate creation

## Describe the solution you'd like

avoid duplicate creation like upstream.. etc

**Comment by spacewander** [comment]
Use PUT method.

```
curl "http://127.0.0.1:9080/apisix/admin/upstreams/dental-practice-patient-web-dev" -X PUT
```
