### ISSUE TITLE
request help: Will limit-req support nodelay and rate in minute

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#4382]
### Issue description
Will limit-req support nodelay and rate in minute?
If not, I find nodelay can be implemented by adding condition, but resty.limit.req only support rate in second,   how can I implemnt rate in minute?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): ubuntu
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
> I find nodelay can be implemented by adding condition

PR is welcome!

> how can I implemnt rate in minute

Divide the rate by 60 is already enough?

**Comment by nanamikon** [comment]
In my company,  many users set 200 r/m on remote_address or even lower,    If i divided by 60,   1r/s or 2r/s will be reached easily, because modern browser support http2,  so  one user visit one nignx over 1r/s is very common.

Now,  we transfer this conf to apisix,  some of them reach limit and delay request online。

I think we use nodelay in nginx conf while apisix only support delay cause this happen，  maybe I can test it

```
The rate is specified in requests per second (r/s). If a rate of less than one request per second is desired, it is specified in request per minute (r/m). For example, half-request per second is 30r/m.
```

```
ctx->rate = rate * 1000 / scale;
```

Maybe multiply by 1000 is the key to solve the decimal point ？

**Comment by spacewander** [comment]
> In my company, many users set 200 r/m on remote_address or even lower, If it divided by 60, 1r/s or 2r/s will be reached easily,

It's how Nginx works too. Note that the r/m is the speed rate, it doesn't mean you can have 200 requests in a minute, it means you can't be faster than 200r/m. Drive a car in 36km/h is equal to 10m/s.

> because modern browser support http2, so one user visit one nignx over 1r/s is very common.

In this case we need a good burst and/or use delay.

> ctx->rate = rate * 1000 / scale;

`resty.limit.req` does the same thing, see https://github.com/openresty/lua-resty-limit-traffic/blob/56b9a35a69117ed0e8a2e3b9a0866c426403e1b9/lib/resty/limit/req.lua#L144

**Comment by nanamikon** [comment]
Thanks for reply，   after adding nodelay，  we solve the online problem

> resty.limit.req does the same thing, see https://github.com/openresty/lua-resty-limit-traffic/blob/56b9a35a69117ed0e8a2e3b9a0866c426403e1b9/lib/resty/limit/req.lua#L144

So mayby rate should be float, but I think it is not the key point

>In this case we need a good burst and/or use delay.

I want to submit a pr to add nodelay function,   a new param as follow
| Name | Type | Requirement | Default|
|--------|---------|-------------|---------|
|nodelay|boolean|optional|false|

Is it ok?

**Comment by spacewander** [comment]
LGTM
