### ISSUE TITLE
版本2.6，通过admin api无法识别discovery_args

### ISSUE THREAD

**Issue by shhnwangjian** [apache/apisix#4393]
版本2.6
场景：使用nacos discovery
通过admin api配置upstream无法识别discovery_args
upstream.lua 源码还没支持这块
返回信息如下：
{"error_msg":"invalid configuration: property \"upstream\" validation failed: additional properties forbidden, found discovery_args"}

**Comment by spacewander** [comment]
`discovery_args` is added after v2.6.
