### ISSUE TITLE
request help :aliyun dcdn + apisix may cause http_ssl_phase() failed to fetch ssl config: failed to find SNI. 

### ISSUE THREAD

**Issue by oldthreefeng** [apache/apisix#4394]
### Issue description
when use aliyun dcdn + apisix。 i found some error logs like . 

```
2021/06/09 00:18:23 [error] 46#46: *6197858 [lua] init.lua:149: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 120.27.74.159, server: 0.0.0.0:9443
```

at the same time. i have capture the packet on the ecs host. after do some reseacrh of it .but nothing can be found.  this really confused me. 
```
$ tcpdump -i eth0 -s 0 -w /var/tmp/1.cap
```

![image](https://user-images.githubusercontent.com/38313565/121227865-a30fdf80-c8be-11eb-9f18-a4f19ec17665.png)

just like @spacewander says https://github.com/apache/apisix/issues/3037#issuecomment-744276474

i am not sure there is a bug on aliyun dcdn when sni set but dont sent to apisix.  or apisix just have ignore the sni say hello (may http_ssl_phase can provide much more logs can debug the errors. just like host)
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):  `Linux k8s-node-110-228 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:2.6

officailly. is there any method i can disable http_ssl_phase check ?

**Comment by spacewander** [comment]
Maybe you can create a support case in aliyun dcdn.

**Comment by oldthreefeng** [comment]
1. use dcdn -> apisix.  aliyun dcdn when sni set . apisix occasionally reports errors like http_ssl_phase (may some where requested APISIX-443 port  via IP directly, not sure ). 
2. use dcdn -> apisix.  aliyun dcdn when sni not set. apisix 100% reports errors.
3. use dcdn -> waf -> apisix. aliyun dcdn when sni set or not . apisix 100% reports errors.  (casue waf did not support sni)

@spacewander
