### ISSUE TITLE
request help: There is no error log for synchronizing eureka, and no routing or service information is found through the dashboard

### ISSUE THREAD

**Issue by leshalv** [apache/apisix#4397]

**Comment by tokers** [comment]
@leshalv Please paste some contexts about your problem, like the APISIX version and OpenResty version you're using. Also, Eureka is used to do the service discovery, not route discovery, it shouldn't influence the existing of routes.

**Comment by moonming** [comment]
@leshalv 
Please use English in the public channel, thx

**Comment by leshalv** [comment]
apache/apisix:2.5-alpine
apache/apisix-dashboard:2.6.1

**Comment by leshalv** [comment]
服务现在还是没有信息，现在用的是2.7.0版本

**Comment by tokers** [comment]
> @leshalv Please paste some contexts about your problem, like the APISIX version and OpenResty version you're using. Also, Eureka is used to do the service discovery, not route discovery, so the problem that routes was not shown in Dashboard should be irrelevant with Eureka.

@leshalv You don't read what I said.

**Comment by tzssangglass** [comment]
@leshalv use `curl http://127.0.0.1:9090/v1/discovery/eureka/dump | jq` to dump the eureka. Is this solved now?
