### ISSUE TITLE
stand-alone support read from apisix.json

### ISSUE THREAD

**Issue by adugeek** [apache/apisix#4399]
As Title:
Only very few yaml generation  lib,
On the contrary, many json generation lib

**Comment by tzssangglass** [comment]
I think yaml is used more because it is positioned as a configuration file, especially in cloud-native scenarios.
by the way, is there a suitable lua-resty-* library for reading the json file?

**Comment by tokers** [comment]
> > I think yaml is used more because it is positioned as a configuration file, especially in cloud-native scenarios.
> 
> I agree this point.
> But, The problem is no suitable lib covery lua stuct to yaml.
> 
> > is there a suitable lua-resty-* library for reading the json file?
> 
> We don't need a library to read json files,
> What we need is a library that can convert between lua struct and json string. They are many.
> 
> But we don't have a library that can convert between lua struct and yaml string.

@adugeek Does lua-tinyyaml meet your demand?

**Comment by adugeek** [comment]
> Does lua-tinyyaml meet your demand?

tinyyaml  can decode yaml string , but cant't encode yaml string .

**Comment by tokers** [comment]
@adugeek What is the scenario that you'll face? Why we need to encode the configuration?
