### ISSUE TITLE
request help: Can the port be set for http_to_https in the redirect plugin?

### ISSUE THREAD

**Issue by ieayoio** [apache/apisix#4400]
### Issue description
Can the port be set for http_to_https in the redirect plugin?

The default https port of apisix is 9443, but after I set http_to_https to true, 
visiting "http://test.com:9080/service/"
will redirect to "https://test.com/service/",
my expected to jump to "https://test.com:9443/service/"

### Environment

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):`Linux xxxxx 4.19.90-2012.5.0.0054.oe1.x86_64 #1 SMP Tue Dec 22 15:58:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
```
nginx version: openresty/1.19.3.1
built by gcc 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)
built with OpenSSL 1.1.1h  22 Sep 2020 (running with OpenSSL 1.1.1k  25 Mar 2021)
```
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
```
{"hostname":"xxxxxx","boot_time":1623142227,"etcd_version":"3.4.0","up_time":93656,"last_report_time":1623235829,"id":"xxxxx","version":"2.6"}
```
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):`/usr/local/bin/luarocks 3.4.0`

**Comment by tokers** [comment]
@ieayoio Currently we can't, but PR's welcome to extend it.

**Comment by rockjing** [comment]
I have the same issue. So what's update ?

**Comment by membphis** [comment]
I reopened this issue, welcome PR from anyone

**Comment by tokers** [comment]
> I have the same issue. So what's update ?

Would you like to try it?

**Comment by kwanhur** [comment]
I'll try to solve it.
