### ISSUE TITLE
bug: ip-restriction blacklist is not work

### ISSUE THREAD

**Issue by wannianma** [apache/apisix#4402]
### Issue description

i want try use the blacklist to block ip 172.16.20.142, but it's not work.

my ip-restirction setting json below:

```
{"id":"5","create_time":1614164130,"update_time":1623316842,"uris":["/api/test/*"],"name":"route_test","hosts":["test.tf.wnx.fun"],"vars":[],"plugins":{"ip-restriction":{"blacklist":["172.16.20.142"],"disable":false},"proxy-rewrite":{"regex_uri":["^/district/get(.*)","/get$1"],"scheme":"http"}},"upstream_id":"347373286092442083","status":1}
```

access.log 
```
 - - [10/Jun/2021:17:22:17 +0800] "GET /api/test/index HTTP/1.1" 200 53 "-" "PostmanRuntime/7.28.0" "-" 0.121 0.065 "-" "-" "-" "-" "-" "-" - "http://internal.match.wyh.wonlap.cn"
 ```

reposne body
```
{
    "code": 200,
    "error": "",
    "data": {
        "tag": "A"
    }
}
```

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS:Linux T65 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have: 2.4
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):/usr/local/bin/luarocks 3.5.0

**Comment by tokers** [comment]
@wannianma The access.log you pasted cannot prove where you sent this request, you may try to add $remote_addr to access.log and see the remote_addr value from APISIX's point of view.

**Comment by wannianma** [comment]
I hava found the reason, i do not reset the plugins in the conf/config.ymal.
