### ISSUE TITLE
request help: apisix是否有类似于nginx proxy_next_upstream的请求重试机制

### ISSUE THREAD

**Issue by kuberxy** [apache/apisix#4403]
### Issue description
我们的系统出现了“消息发送多次”的问题。请问apisix是否会在一些情况下向后端节点发送多次请求？又或者我能否通过一些方法排除是apisix的问题

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
$ apisix version
2.2

* OS (cmd: `uname -a`):
$ uname -a
Linux hz-i-node2 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
$ openresty -V
nginx version: openresty/1.15.8.3
built by gcc 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
built with OpenSSL 1.1.0l  10 Sep 2019
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-threads --with-dtrace-probes --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_ssl_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --add-module=/home/cyadmin/downloads/openresty-1.15.8.3/bundle/ip2location-nginx --add-module=/home/cyadmin/downloads/openresty-1.15.8.3/bundle/nginx-sticky-module --with-stream --with-stream_ssl_preread_module

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
Stand-Alone. not use etcd

* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):
$ luarocks --version
/usr/bin/luarocks 2.4.2
LuaRocks main command-line interface

**Comment by tokers** [comment]
@kuberxy You can try to disable the retry, see http://apisix.apache.org/docs/apisix/admin-api#upstream for details.

**Comment by kuberxy** [comment]
@tokers  Thanks
