### ISSUE TITLE
request help: integration with Nats 

### ISSUE THREAD

**Issue by smiziara** [apache/apisix#4404]
### Issue description

I want to develop a plugin for Apisix, so i can forward http requests to Nats, wait for the response and then write the body and headers to the http response. 

The approach would be as following:
1) Apisix receives the http request, perform the authentication and validation (other plug-ins can be used) 
2) Then a payload representing this request is sent to Nats messaging, and await for the response. 
3) When the response is received, the payload will contains new headers and body, that will be used as the response for the client. 

My question is, whats the best approach to implement this? 
As a lua plugin? Or the Java plugin runner? 

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):  latest
* OS (cmd: `uname -a`): centos 7
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): latest
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Do you mean https://nats.io/?

If it provides HTTP API, we can integrate it via Lua. The keycloak plugin will be an example: https://github.com/apache/apisix/blob/master/apisix/plugins/authz-keycloak.lua

**Comment by smiziara** [comment]
> Do you mean https://nats.io/?
> 
> If it provides HTTP API, we can integrate it via Lua. The keycloak plugin will be an example: https://github.com/apache/apisix/blob/master/apisix/plugins/authz-keycloak.lua

Exactly. The ideia would be to use their socket communication, to achieve the best performance, avoiding bridges and any extra http calls. 
So I would need to keep a conection alive just like the Kafka plugin, but wait for the Rpc to respond the request. 
I dont wanna block anything on apisix pipeline.
What would be the best approach for me to follow? 

Thanks!

**Comment by smiziara** [comment]
@spacewander actually Nats now supports websocket too, but i would need to perform a transcoding just like the gRpc, because the incoming would be a http request. 
So its about the same, major difference is that i wouldn't need to import a nats client sdk.

**Comment by spacewander** [comment]
OpenResty's network operation is non-blocking. But there is no gRPC implementation in the Lua world.
