### ISSUE TITLE
request help: Multi-version control of configuration

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4408]
### Issue description
Does apisix support multi-version control of configuration? 
Assuming that we must have a problem with the configuration of a certain version, we want to quickly roll back to the configuration of a previous version instead of re-configuration

**Comment by spacewander** [comment]
You can get a previous revision of etcd's data and write it back to the etcd.

**Comment by zuiyangqingzhou** [comment]
I know what you mean. 
I mean, does apisix have a higher level of abstraction based on etcd for version control? Or is there any plan for this in the future?
Because it is currently not very convenient to rely entirely on etcd for visual version management of configuration

**Comment by spacewander** [comment]
No yet.

**Comment by tokers** [comment]
@zuiyangqingzhou It can be a feature of apisix-dashboard. If you will, welcome to submit a proposal to the mailing list dev@apisix.apache.org, let's have a discussion there.

**Comment by zuiyangqingzhou** [comment]
@tokers  Okay, I believe it's not just me who has such a demand. 
If this can become a new feature of dashboard, I believe that apisix will become more and more competitive in the market. 
In addition, is there a template when submit a proposal?

**Comment by tokers** [comment]
> @tokers Okay, I believe it's not just me who has such a demand.
> If this can become a new feature of dashboard, I believe that apisix will become more and more competitive in the market.
> In addition, is there a template when submit a proposal?

We don't have a solid template for submitting a proposal, just describing the background, the design, and the benefits that we can get if we implement it.
