### ISSUE TITLE
request help: how to config browser cache in apisix:2.6

### ISSUE THREAD

**Issue by gewei2000** [apache/apisix#4410]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):centos 7.5
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@gewei2000 You may try to add some headers like Cache-Control and Pragma.
