### ISSUE TITLE
request help: upstream timed out (110: Connection timed out) while reading response header from upstream

### ISSUE THREAD

**Issue by eavesmy** [apache/apisix#4411]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5

我们布置了两套服务，一套线上一套测试，都使用相同配置。
测试服务一直正常，线上服务却经常报错：
```
upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: _, request: "POST /auth/login HTTP/1.1",
```
apisix 配置中 keepalive 时间为 60s。
请问应该怎么处理这个问题？

**Comment by spacewander** [comment]
The error message shows the upstream doesn't respond in time. Need to investigate the upstream of the online environment.

**Comment by Stciflytek** [comment]
大家好。我也遇到。部署环境：docker、欧拉、x86； 接口响应时间大概是10s，那么一定会报此异常，路由中超时时间（3个参数）都设置为60s。 。接口响应时间很快的接口，都没有问题。上游服务正常。在window环境任何接口都没问题。
