### ISSUE TITLE
request help: How to set route uri matching to be case-insensitive

### ISSUE THREAD

**Issue by misterchen** [apache/apisix#4412]
### Issue description

Is there a way to set route uri matching to be case-insensitive?

Example :
URI maching : /sampleweb/*

Expect :
/sampleweb/    ->   success
/SampleWeb/   ->   success
/Sampleweb/    ->   success

Test :
```
curl http://127.0.0.1:9080/sampleweb/
-> success

curl http://127.0.0.1:9080/SampleWeb/
{"error_msg":"404 Route Not Found"}

curl http://127.0.0.1:9080/Sampleweb/
{"error_msg":"404 Route Not Found"}
```

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.15
* apisix-dashboard version, if have: 2.6

**Comment by spacewander** [comment]
You can write your own router, convert input uris to lowercase, like this one: https://github.com/apache/apisix/blob/master/apisix/http/router/radixtree_uri_with_parameter.lua

PR is welcome!

**Comment by misterchen** [comment]
Thank you for your response
I have no development experience with Lua
Currently, I will try other methods to solve it

Looking forward to your feature updates 👍

**Comment by spacewander** [comment]
Look like we already support it via regex match? For example:

```
{
  "uri": "/*",
  "vars": [
      ["uri", "~*", "^/sampleweb/"]
  ],
  "plugins": {
    "fault-injection": {
      "abort": {
        "http_status": 200,
        "body": "hello world"
      }
    } 
  },
  "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}
```

If we need to mix the case-insensitive match and case-sensitive match, the regex match can solve the problem.
