### ISSUE TITLE
bug: etcd cluster setting,one node down,cannot connect to other healthy one

### ISSUE THREAD

**Issue by azura27** [apache/apisix#4414]
### Issue description
config etcd with following setting:
etcd:
  host:           
    - "http://10.10.10.1:2379"  
    - "http://10.10.10.2:2379"
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.0
* OS (cmd: `uname -a`): 3.10.0-693.21.1.el7.x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.10
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. config etcd with two etcd host in same cluster
2. start apisix, we could see it connect to the first etcd host configed
3. stop first etcd, and apisix could not connect etcd with error: failed to fetch from etcd

### What's the actual result? (including assertion message & call stack if applicable)
apisix connect etcd failed
### What's the expected result?
apisix could connect other healthy etcd

**Comment by spacewander** [comment]
@Yiyiyimu 
Will https://github.com/apache/apisix/pull/4191 solve the problem?

**Comment by Yiyiyimu** [comment]
> Will #4191 solve the problem?
Yes. Would work on it today

**Comment by azura27** [comment]
Thank you, we will test later

**Comment by Yiyiyimu** [comment]
Sorry @azura27 I haven't finished #4191, need several more days on it

**Comment by azura27** [comment]
> Sorry @azura27 I haven't finished #4191, need several more days on it

OK, take your time, we have make it have high availability with VIP

**Comment by Yiyiyimu** [comment]
Close with #4191
