### ISSUE TITLE
request help: upload apisix latest version to luarocks 

### ISSUE THREAD

**Issue by xuchmao** [apache/apisix#4416]
### Issue description

The latest version of apisix in luarocks is [2.4](https://luarocks.org/modules/apisix/apisix) and it is behind the github. Need to upload the latest version 2.6 to luarocks.

### Environment

* luarocks 3.7.0

**Comment by Yiyiyimu** [comment]
Hi @xuchmao as you could find in #4170, we don't recommend installing apisix from luarocks anymore.
