### ISSUE TITLE
request help:  failed to set upstream: discovery nacos is uninitialized

### ISSUE THREAD

**Issue by YangHuiFor** [apache/apisix#4420]
### Issue description
本地使用的apisix 2.6版本， 项配置下使用nacos服务发现。 搜索了之前的Issue没发现有类似的问题

curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/v1/*",
    "upstream": {
        "service_name": "APISIX-NACOS",
        "type": "roundrobin",
        "discovery_type": "nacos"
    }
}'

请求无法通过，提示
2021/06/12 07:26:50 [error] 47#47: *213366 [lua] init.lua:470: http_access_phase(): failed to set upstream: discovery nacos is uninitialized, client: 172.20.0.1, server: _, request: "GET /v1/t HTTP/1.1", host: "127.0.0.1:9080"

### Environment
使用的Mac docker环境
![image](https://user-images.githubusercontent.com/4995476/121768961-98419d00-cb93-11eb-99c0-8a60e40a5c2d.png)

**Comment by Yiyiyimu** [comment]
Hi @YangHuiFor have you configured nacos in apisix config correctly? Could you show `config.yaml` and how you set up nacos

**Comment by YangHuiFor** [comment]
> Hi @YangHuiFor have you configured nacos in apisix config correctly? Could you show `config.yaml` and how you set up nacos
hi @Yiyiyimu 

this my `config.yaml`
![image](https://user-images.githubusercontent.com/4995476/121795610-e8c50300-cc44-11eb-8d28-189ba40aa7c5.png)

this my nacos
![image](https://user-images.githubusercontent.com/4995476/121795627-04c8a480-cc45-11eb-955e-352261afc28d.png)

**Comment by tokers** [comment]
@YangHuiFor It looks like the nacos client in APISIX was not initialized correctly, you may need to look through the error.log and found some clues about this (check out the reload/start/restart timing).

**Comment by YangHuiFor** [comment]
@tokers 
 error.log
2021/06/14 02:50:49 [error] 46#46: *2725467 [lua] init.lua:470: http_access_phase(): failed to set upstream: discovery nacos is uninitialized, client: 172.20.0.1, server: _, request: "GET /v1/t HTTP/1.1", host: "127.0.0.1:9080"

**Comment by tokers** [comment]
> @tokers
> error.log
> 2021/06/14 02:50:49 [error] 46#46: *2725467 [lua] init.lua:470: http_access_phase(): failed to set upstream: discovery nacos is uninitialized, client: 172.20.0.1, server: _, request: "GET /v1/t HTTP/1.1", host: "127.0.0.1:9080"

Well, I mean are there any log messages that can tell us the reason what the discovery nacos can not be initialized?

**Comment by spacewander** [comment]
Closed as lack of response.

**Comment by jxljf** [comment]
please execute 'make reload' after modify conf.yaml

**Comment by zemelLeong** [comment]
> > @tokers
> > error.log
> > 2021/06/14 02:50:49 [error] 46#46: *2725467 [lua] init.lua:470: http_access_phase(): failed to set upstream: discovery nacos is uninitialized, client: 172.20.0.1, server: _, request: "GET /v1/t HTTP/1.1", host: "127.0.0.1:9080"
> 
> Well, I mean are there any log messages that can tell us the reason what the discovery nacos can not be initialized?

I have same issue. I get this `error.log` when I execute command `docker-compose -p docker-apisix up -d` to start apisix.
![image](https://user-images.githubusercontent.com/26835087/134798918-0e8ada25-9ea0-45a9-99f8-9ec17b21999e.png)

**Comment by zemelLeong** [comment]
> > > @tokers
> > > error.log
> > > 2021/06/14 02:50:49 [error] 46#46: *2725467 [lua] init.lua:470: http_access_phase(): failed to set upstream: discovery nacos is uninitialized, client: 172.20.0.1, server: _, request: "GET /v1/t HTTP/1.1", host: "127.0.0.1:9080"
> > 
> > 
> > Well, I mean are there any log messages that can tell us the reason what the discovery nacos can not be initialized?
> 
> I have same issue. I get this `error.log` when I execute command `docker-compose -p docker-apisix up -d` to start apisix.
> ![image](https://user-images.githubusercontent.com/26835087/134798918-0e8ada25-9ea0-45a9-99f8-9ec17b21999e.png)

never mind. the discovery need in the root.
https://github.com/apache/apisix/blob/master/conf/config-default.yaml

**Comment by luyi1994** [comment]
I have the same problem  。。

**Comment by luyi1994** [comment]
[error] 50#50: *152 [lua] init.lua:548: handle_upstream(): failed to set upstream: discovery nacos is uninitialized

**Comment by zhoujiexiong** [comment]
#11528
