### ISSUE TITLE
request help: key auth plugin didn't support get key from querystring

### ISSUE THREAD

**Issue by forgaoqiang** [apache/apisix#4421]
### Issue description
I think it's a basic demand that the apikey should be check from HTTP header or HTTP Querystring, could you guys add that feature, It's very convenient to support both HTTP header and query string 

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@forgaoqiang PR's welcome to support it!

**Comment by forgaoqiang** [comment]
thanks for the feature
