### ISSUE TITLE
request help: Does APISIX support Redis Sentinel?

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#4422]
### Issue description

Does APISIX support Redis Sentinel? Do I need a special Lua package to use it?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`): Linux 3.10.0-1160.11.1.el7.x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.14

**Comment by spacewander** [comment]
The Redis client can talk with the sentinel. We can extend the current implementation to do it: https://redis.io/topics/sentinel#obtaining-the-address-of-the-current-master

**Comment by tzssangglass** [comment]
or you can use this library https://github.com/ledgetech/lua-resty-redis-connector
