### ISSUE TITLE
Does apisix support etcd service discovery

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4442]
I see in the readme file that it supports etcd as a service discovery, but I didn’t see the relevant documentation, and I didn’t find an example of how to use it.

**Comment by tzssangglass** [comment]
APISIX uses etcd as a CP implementation and is not the same concept as a microservice registry discovery center like Nacos or Eureka.

**Comment by zuiyangqingzhou** [comment]
But I saw the following paragraph in the readme file, which clearly stated that in addition to the built-in etcd, it also supports Nacos, etc.

![image](https://user-images.githubusercontent.com/17425270/122496585-99a11880-d01e-11eb-88df-c5dcf882c4d2.png)

If you don’t support it, does this sentence cause misunderstanding?

**Comment by tzssangglass** [comment]
> But I saw the following paragraph in the readme file, which clearly stated that in addition to the built-in etcd, it also supports Nacos, etc.
> 
> ![image](https://user-images.githubusercontent.com/17425270/122496585-99a11880-d01e-11eb-88df-c5dcf882c4d2.png)
> 
> If you don’t support it, does this sentence cause misunderstanding?

yes, I think there is a slight misunderstanding here. PR is welcome!

**Comment by spacewander** [comment]
APISIX indeed supports using etcd for service discovery.

There is no official service discovery API in etcd.
So the only one to use etcd is writing your own discovery framework.
It is also the way we do in APISIX.

When we put this configuration into etcd via Admin API or via something else:
```
/apisix/upstreams/myAPIProvider
...
/apisix/routes/1
..."upstream_id":"myAPIProvider"
```

We are already doing service discovery.
