### ISSUE TITLE
request help: 如何用http_logger插件？

### ISSUE THREAD

**Issue by 929404097** [apache/apisix#4446]
### Issue description
我使用了http_logger插件发送日志，日志是收到了，但没有携带任何信息，且error.log有报错

2021/06/18 16:45:30 [error] 1358#1358: *271527 [lua] batch-processor.lua:63: Batch Processor[http logger] failed to process entries: error while sending data to [192.168.3.45] port[7010] timeout, context: ngx.timer, client: 192.168.3.45, server: 0.0.0.0:9080
2021/06/18 16:45:30 [error] 1358#1358: *271527 [lua] batch-processor.lua:70: Batch Processor[http logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 192.168.3.45, server: 0.0.0.0:9080
### Environment
Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):centos7
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
according to the `error.log`, it was sent to the log collection service that timed out. please check the network and the timeout settings on the log collection service first.

**Comment by 929404097** [comment]
> according to the `error.log`, it was sent to the log collection service that timed out. please check the network and the timeout settings on the log collection service first.

我日志收集服务器是可以收到请求的，只不过没有任何其他参数带过来，只是一个空请求

**Comment by 90yangkang** [comment]
Is there a solution for this? @929404097
