### ISSUE TITLE
request help: http_logger

### ISSUE THREAD

**Issue by 929404097** [apache/apisix#4447]
### Issue description 
http_logger插件
http_logger插件，服务端要用什么参数名接收传过来的信息？请求是收到了，但是没看到request里携带有任何的信息

![插件](https://user-images.githubusercontent.com/32952450/122539557-4ea4f680-d05a-11eb-9af3-2414b6db163e.jpg)
![服务端](https://user-images.githubusercontent.com/32952450/122539590-56649b00-d05a-11eb-9e2d-9996530a0338.jpg)

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):win10
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
All log messages are encoded into the request body.

**Comment by spacewander** [comment]
Closed as lack of response.
