### ISSUE TITLE
request help:  how apisix remove route  prefix?

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#4452]
### Issue description
for example :
```
origin path is  /apisix/api/*
upstream path should be : /api/*
```
![image](https://user-images.githubusercontent.com/15153469/122705456-5a760000-d288-11eb-89b8-23d77ee4677c.png)

how can I use it?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):  2.5
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@gy09535 Please see http://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/ for details.

**Comment by tzssangglass** [comment]
or you can try this https://github.com/apache/apisix/issues/4140#issuecomment-827507578

**Comment by Yiyiyimu** [comment]
Since at least three users asked about this afaik, do we need to add "prefix-removing" as one of the route's arguments? 
[Kong supported this](https://docs.konghq.com/gateway-oss/2.4.x/admin-api/#request-body-3) which named `strip_path`

**Comment by spacewander** [comment]
Put "prefix-removing" in the route is confusing:
1. our route matching is quite complex, path match is only part of it
2. there will be too many places which can change the path of a route

**Comment by Yiyiyimu** [comment]
> Put "prefix-removing" in the route is confusing:
> 
> 1. our route matching is quite complex, path match is only part of it
> 2. there will be too many places which can change the path of a route

Got it. Thanks for the explanation! I didn't consider those aspects.
I'll add it to FAQ
