### ISSUE TITLE
request help: make run occur error: init_worker_by_lua error: /root/c4_working/onest-balancer/apisix/init.lua:89: module 'resty.worker.events' not found:

### ISSUE THREAD

**Issue by Qizhd** [apache/apisix#4454]
### Issue description
```
[root@qizhendong-dev1 onest-balancer]# make run
mkdir -p logs
/usr/bin/openresty -p $PWD/ -c $PWD/conf/nginx.conf
[root@qizhendong-dev1 onest-balancer]# cat logs/error.log

2021/06/21 16:21:04 [error] 16118#16118: init_worker_by_lua error: /root/c4_working/onest-balancer/apisix/init.lua:89: module 'resty.worker.events' not found:
        no field package.preload['resty.worker.events']
        no file '/root/c4_working/onest-balancer//deps/share/lua/5.1/resty/worker/events.lua'
        no file '/root/c4_working/onest-balancer//deps/share/lua/5.1/resty/worker/events/init.lua'
        no file '/root/c4_working/onest-balancer/resty/worker/events.lua'
        no file '/root/c4_working/onest-balancer/resty/worker/events/init.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/local/share/lua/5.3/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.3/resty/worker/events/init.lua'
        no file '/usr/local/lib/lua/5.3/resty/worker/events.lua'
        no file '/usr/local/lib/lua/5.3/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file './resty/worker/events/init.lua'
        no file '/root/c4_working/onest-balancer//deps/lib64/lua/5.1/resty/worker/events.so'
        no file '/root/c4_working/onest-balancer//deps/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
        no file '/usr/local/openresty/lualib/resty/worker/events.so'
        no file './resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/lib/lua/5.3/resty/worker/events.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './resty/worker/events.so'
        no file '/root/c4_working/onest-balancer//deps/lib64/lua/5.1/resty.so'
        no file '/root/c4_working/onest-balancer//deps/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/lib/lua/5.3/resty.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './resty.so'
stack traceback:
        [C]: in function 'require'
        /root/c4_working/onest-balancer/apisix/init.lua:89: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

```

### Environment

`centos 7.6`

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
 apisix 2.1

* OS (cmd: `uname -a`):
Linux qizhendong-dev1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
[root@qizhendong-dev1 onest-balancer]# openresty -V
nginx version: openresty/1.19.3.2
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Duplicate of #3207
