### ISSUE TITLE
request help:  How to use advanced debugging mode

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4457]
https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/debug-mode.md

I saw this document introduced that you can turn on the advanced debugging mode, So my debug.yaml file is like this：
```
hook_conf:
  enable: true                 # enable or disable this feature
  name: hook_phase              # the name of module and function list
  log_level: info               # log level
  is_print_input_args: true     # print the input arguments
  is_print_return_value: true   # print the return value

hook_phase:                     # module and function list, name: hook_phase
  apisix:                       # required module name
    - http_access_phase         # function name
    - http_header_filter_phase
    - http_body_filter_phase
    - http_log_phase

#END
```
Then I called some interfaces, including authentication plug-ins. I saw no changes in the logs, just like the advanced debugging mode was not turned on, only the warn log

Can you tell me what a complete process of using advanced debugging mode is like? What should I focus on?

**Comment by tokers** [comment]
@zuiyangqingzhou Make sure your logging level setting (`error_log_level`) is lower than the `log_level` setting in `debug.yaml`.

**Comment by zuiyangqingzhou** [comment]
> @zuiyangqingzhou Make sure your logging level setting (`error_log_level`) is lower than the `log_level` setting in `debug.yaml`.

Thank you, but I think it should be explained in the document, although it is only a small point

**Comment by tokers** [comment]
> > @zuiyangqingzhou Make sure your logging level setting (`error_log_level`) is lower than the `log_level` setting in `debug.yaml`.
> 
> Thank you, but I think it should be explained in the document, although it is only a small point

PR's welcome.
