### ISSUE TITLE
request help: upstream host added domain name will be converted to IPv4

### ISSUE THREAD

**Issue by yoyofx** [apache/apisix#4463]
### Issue description
upstream host 添加域名，会被转换成IP，是否能直接按域名解析

### Environment

Request help without environment information will be ignored or closed.

* apisix 2.6
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard 2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@yoyofx Please paste some details and a minimal reproducible case.

**Comment by yoyofx** [comment]
比如说，添加一个上游的host  是 域名 + 端口号， host1.gg.com , 80
设置路由 /hostgg/*  后， 访问 xx.xx.xx.xx:9080/hostgg  后 host1.gg.com 域名会被dns解析成IP( 10.0.2.11:80 ) 
但是我这边想要的结果是直接转发到这个域名，而不是dns解析成IP后再访问 。

**Comment by tokers** [comment]
I'm afraid I didn't understand what you mean, how did a service can be accessed if its domain cannot be resolved to IP addresses?

**Comment by tzssangglass** [comment]
or you could just say what you want? maybe you need the request to be forwarded upstream with some `host` parameters?

**Comment by yoyofx** [comment]
> or you could just say what you want? maybe you need the request to be forwarded upstream with some `host` parameters?

确实这时候应该用host解决，感谢
