### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by 1026197530** [apache/apisix#4465]
After the update to the new version, the configured global route /* cannot be forwarded to the node in the configured upsteam group. 404 is reported via the Apisix access interface

### Environment   APISIX-2.2   
                               etcd Version: 3.4.11   
                               openresty version: openresty/1.15.8.3
                              apisix-dashboard    2.3

**Comment by Yiyiyimu** [comment]
Hi @1026197530 do you migrate from 1.x to 2.2?

**Comment by 1026197530** [comment]
yeap! It appears that GRPC routing is not supported in Apisix 2.2

**Comment by Yiyiyimu** [comment]
It seems we [do support](https://github.com/apache/apisix/blob/v2.2/doc/admin-api.md#route) grpc in 2.2. Or have you tried newer version of apisix

**Comment by tokers** [comment]
@1026197530 What is your problem? Please give more and more details. Also, don't describe different problems in the same track, it confuses others.
