### ISSUE TITLE
bug: Can't get real Ip in service

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4470]
### Issue description
I have configured "X-Forwarded-For" in proxy-rewrite: "$proxy_add_x_forwarded_for"
In order to get the Real IP, per we used K8S, so the IP would be transferred to the clusterIP of K8S, but we could not get this value, and X-real-IP was always obtained from the clusterIP of K8S.
### Environment

* apisix version (cmd: `apisix version`): 2.6

### Minimal test code / Steps to reproduce the issue

1.add plugin in service 
```
 "plugins": {
    "proxy-rewrite": {
      "disable": false,
      "headers": {
        "ENV": "pre",
        "Host": "$host",
        "X-Forwarded-For": "$proxy_add_x_forwarded_for"
      },
      "regex_uri": [
        "/api/scrm/(.*)",
        "/common-rest/$1"
      ]
    }
  }
```
2.print the header for X-Forwarded-For
![A5EA809E0A555B8A87D2F8C11A946BE2](https://user-images.githubusercontent.com/52538259/123032062-ee2a0680-d417-11eb-989f-187b040a3b31.jpg)
the ip for 172.19... is k8s clusterip, 220.249.. is correct real ip, but X-Forwarded-For is null and X-Real-IP is 172.19.. which is not correct real ip, i also try to configure like this `"X-Real-IP": "$proxy_add_x_forwarded_for"`, 
I expect to get the result like this `220.249.., 172.19...`(got two ip),  actually i got only one ip `172.19...`
below is the log for apisix, show correct ip which i expect for
![8C0E104E2717BCA1CE25705CD069CC42](https://user-images.githubusercontent.com/52538259/123032458-9049ee80-d418-11eb-9672-20f08488523e.jpg)

3. so i guess the X-Real-IP/X-Forwarded-For was rewrite by apisix
i also checked the config-default.yaml, not sure if below configuration will influence the result, i try to add the ip 
172.19.0.0 in order to filter the incorrect k8s ip segment, but doesn't work
![image](https://user-images.githubusercontent.com/52538259/123032629-d606b700-d418-11eb-8dec-429d8d819273.png)

### What's the actual result? (including assertion message & call stack if applicable)
`172.19...`
### What's the expected result?
`220.249.., 172.19...`

**Comment by Marco-Zheng** [comment]
I also try configure like this 
![image](https://user-images.githubusercontent.com/52538259/123033445-5a0d6e80-d41a-11eb-9571-45ed2a1e19d9.png)
but X-Forwarded-For always null, no rewrite logic code in my business server..
![image](https://user-images.githubusercontent.com/52538259/123033526-78736a00-d41a-11eb-96cb-9f0bb372c238.png)

**Comment by spacewander** [comment]
If I understand it correctly,

`220.249..` is the client IP. `172.19...` is the APISIX(proxy) IP. So you want to put client IP in the X-Forwarded-For header.

But from your description, I think the client doesn't send its IP in the X-Forwarded-For (as X-Forwarded-For is null). So is there a way to get its IP?

**Comment by Marco-Zheng** [comment]
@spacewander 220.249.. is the real IP which the client requested, 
172.19... is not APISIX(proxy) IP, it's the k8s node ip(we have 9 k8s node, and my service `common-rest` in one of node, you can consider it as transfer agent ip), we need the ip from real client

but as you can see, i configure X-Forwarded-For, X-Real-IP in order to get result `220.249.., 172.19...`
but actually i get the result is 
X-Real-IP=`172.19...`
X-Forwarded-For=`null`

**Comment by spacewander** [comment]
There is some logic to generate "X-Forwarded-For": https://github.com/apache/apisix/blob/2707fda3eb7b23d995ac23ecf4a17000dd765855/apisix/cli/ngx_tpl.lua#L545-L546

So the change in proxy-rewrite doesn't take effect.

However, if the client sent its IP via "X-Forwarded-For", it should provide the expected result "220.249.., 172.19...".

**Comment by Marco-Zheng** [comment]
@spacewander thanks for your kindly reply, but i just review the code, if x_forward_for is null, the value of x_forward_for must be $remote_addr, why get the null value.
![image](https://user-images.githubusercontent.com/52538259/123077596-c43f0700-d44c-11eb-9f0b-0afc93501799.png)

**Comment by spacewander** [comment]
Interesting. I try it locally but can't reproduce it. Here is my route:
```
{
 "uri": "/xff",
 "plugins": {
    "proxy-rewrite": {
      "disable": false,
      "headers": {
        "ENV": "pre",
        "Host": "$host",
        "X-Forwarded-For": "$proxy_add_x_forwarded_for"
      },
      "regex_uri": [
        "/api/scrm/(.*)",
        "/common-rest/$1"
      ]
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
     "127.0.0.1:1980": 1
    }
  }
}
```

Here is how I try
```bash
 ￥ curl http://127.0.0.1:9080/xff -i
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Thu, 24 Jun 2021 01:55:52 GMT
Server: APISIX/2.6

uri: /xff
accept: */*
env: pre
host: 127.0.0.1:9080
user-agent: curl/7.68.0
x-forwarded-for: 127.0.0.1
x-forwarded-host: 127.0.0.1
x-forwarded-port: 9080
x-forwarded-proto: http
x-real-ip: 127.0.0.1

 ￥ curl http://127.0.0.1:9080/xff -i -H "X-Forwarded-For: 220.249.1.1"
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Date: Thu, 24 Jun 2021 01:56:35 GMT
Server: APISIX/2.6

uri: /xff
accept: */*
env: pre
host: 127.0.0.1:9080
user-agent: curl/7.68.0
x-forwarded-for: 220.249.1.1, 127.0.0.1
x-forwarded-host: 127.0.0.1
x-forwarded-port: 9080
x-forwarded-proto: http
x-real-ip: 127.0.0.1
```

The `x-forwarded-for` is never null.

Can you provide a packet capture file to see if x-forwarded-for is missing?

**Comment by Marco-Zheng** [comment]
@spacewander yes, no x-forwarded-for was found per request from Web, if rewrite plugin doesn't work, i'll try to defined another param then overwrite it by proxy rewrite plugin, it can work, thanks for your kindly help

**Comment by helloxubo** [comment]
> 
Hello,Have you solved it? I have the same problem.
