### ISSUE TITLE
request help: use environment properties to overwrite properties in configuration file

### ISSUE THREAD

**Issue by xuchmao** [apache/apisix#4475]
### Issue description
Need to support use environment properties to overwrite properties in configuration file, just like what it is Spring Framework.

For example, set ectd.prefix="/foo" as  environment arg,  ectd.prefix in config.yaml is "apisix", finally value of property  ectd.prefix is "foo" when apisix run.

By the way, priority of config-${APISIX_PROFILE}.yaml > config.yaml will be much better.

Thanks ! 

### Environment
* apisix 2.6

**Comment by tzssangglass** [comment]
reading environment variables in the configuration file is now supported, see https://github.com/apache/apisix/blob/75376e3162efa3d38ee113a8ee5e6d7435e7c392/conf/config.yaml#L24-L28.

and environment properties is now supported, see  https://github.com/apache/apisix/blob/master/docs/en/latest/profile.md

**Comment by xuchmao** [comment]
Thanks, I will try it.
