### ISSUE TITLE
ip直连,请求ssl证书失败,希APISIX支持

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#4482]
使用httpdns后,将域名转成了IP,使用IP直接连服务
这样请求服务的时候没办法拿到SSL证书,
比如,  test.abc.com  的dns解析是1.1.1.1 ,然后通过httpdns拿到域名的解析然后将转化成 https://1.1.1.1/test  (在请求头的header中传入"host":"test.abc.com")这样的能获取到ssl证书

![image](https://user-images.githubusercontent.com/10955441/123378284-1f910680-d5bf-11eb-8807-10cc86f1a7a2.png)

**Comment by spacewander** [comment]
You should pass the real host as SNI. Like this one:
`curl -k --resolve 'test.cn:9443:127.0.0.1' https://test.cn:9443/hello  -v`
