### ISSUE TITLE
bug: ip-restriction whitelist doesn't work

### ISSUE THREAD

**Issue by Marco-Zheng** [apache/apisix#4485]
### Issue description

I used IP -restriction whitelist but it did not work. Later I read the log and found that, because our apisix in k8s environment, the IP of the external network will be converted to the IP of K8S container after getting it

The extranet address of our company that I configured at present does not work. Is there any solution?

### Environment

* apisix version (cmd: `apisix version`):2.6

### Minimal test code / Steps to reproduce the issue
1. in k8s environment
2. configure outside web address as whitelist
3.send request

### What's the actual result? (including assertion message & call stack if applicable)
return 403
### What's the expected result?
access normally

**Comment by tokers** [comment]
This cannot be solved on apisix side, by the way, which CNI plugin is in use? solutions like Calico +ebpf might help you to get the real ip address to prevent the kubernetes ip masquerade.

Or, of the remote address can be set to x-forwarded-for.

**Comment by tzssangglass** [comment]
I was thinking that maybe `ip-restriction` could support an extension - to get the real ip from a user-defined location

**Comment by tokers** [comment]
@tzssangglass We alreay have some items to setting this in config-default.yaml.

**Comment by Marco-Zheng** [comment]
@tokers thx, i'll try to reset remote address as x-forwarded-for, and update the result later

**Comment by Marco-Zheng** [comment]
@tokers it's seems that proxy-rewrite plugin can not rewrite remote_addr to $proxy_add_x_forwarded_for
the log show remote_addr still k8s node ip

**Comment by tokers** [comment]
It depends on whether your client carries the X-Forwarded-For header.

**Comment by Marco-Zheng** [comment]
> It depends on whether your client carries the X-Forwarded-For header.

thx for your kindly help, i 'll try to use another method to resolve this problem
