### ISSUE TITLE
request help: There is no need to upgrade the core code at the same time when upgrading the plugin

### ISSUE THREAD

**Issue by xxm404** [apache/apisix#4487]
### Issue description
When I want to update some plugins, I found I must be updated the APISIX core code at the same time, Maybe the update of the plugin should be independent of the core code.

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.5
* OS (cmd: `uname -a`): ubuntu 18.04.1
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.17.8.2

**Comment by spacewander** [comment]
Upgrade plugin and core at the same time will make life easy, you can ensure they have the same version.
