### ISSUE TITLE
bug: 路径/*不包括/

### ISSUE THREAD

**Issue by w7team** [apache/apisix#4489]
说明里是：/* 代表所有路径
但实际设置的时候/*不包括/，还要设置/*和/两个值才行，这个属于bug不？
![image](https://user-images.githubusercontent.com/74588507/123511374-6e1fcd00-d6b3-11eb-95be-b81f22980a34.png)

**Comment by spacewander** [comment]
I try:
```
{
  "uri": "/*",
  "plugins": {
    "echo": {
      "body": "w"
    }
  },
  "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}
```

And I find it can match `/`.

Can you confirm the problem can be reproduced with the Admin API? What's your APISIX version?

**Comment by w7team** [comment]
我是2.6下测试的，确定会有这个问题

**Comment by spacewander** [comment]
Can't be reproduced with 2.6:

```
 $ curl http://127.0.0.1:9080/ -i
HTTP/1.1 502 Bad Gateway
Date: Mon, 28 Jun 2021 09:19:33 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.6
X-APISIX-Upstream-Status: 502
Custom-Header-Name: 4979675b-3ca8-424f-8fa2-2c96b96b229c

w
```

**Comment by tokers** [comment]
@w7team How did you create this route? Through dashboard or Admin API? you may try to paste the route here.

**Comment by spacewander** [comment]
Closed as lack of response.
