### ISSUE TITLE
Improve Docs: add "/apisix/admin/plugins/reload" into  admin-api.md

### ISSUE THREAD

**Issue by starsz** [apache/apisix#4495]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

Hello, I found that apisix support using "/apisix/admin/plugins/reload" API to reload plugins.
But we don't add description into admin-api.md

Referer: https://github.com/apache/apisix/blob/07bfe5b9c03ad361cb71541eb02fd661f1323213/apisix/admin/init.lua#L28

## Describe the solution you'd like

Add "/apisix/admin/plugins/reload" API into admin-api.md

**Comment by Patil2099** [comment]
I would love to pick this up.

**Comment by starsz** [comment]
> I would love to pick this up.

Pretty good. Assign it to you.

**Comment by param-thakker** [comment]
Hi @starsz , is this still open?

**Comment by Yiyiyimu** [comment]
Hi @param-thakker you could try to pick up some [other issues](https://github.com/apache/apisix/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22good+first+issue%22) which have no assignees

**Comment by starsz** [comment]
It's already supported yet.
Link:  https://apisix.apache.org/docs/apisix/plugins/#hot-reload
