### ISSUE TITLE
bug: cors cannot set config with credential true, allow_headers *

### ISSUE THREAD

**Issue by azura27** [apache/apisix#4496]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.0
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.13
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.  PUT CMD to admin API to set cors plugin open, config allow_credential true, allow_headers "*"
2.  Failed
3.

### What's the actual result? (including assertion message & call stack if applicable)
Failed to set with error messgae:  you can not set '*' for other option when 'allow_credential' is true
### What's the expected result?
set successfully, as the doc of "HTTP ACCESS CONTROL ALLOW" (https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS)

**Comment by tokers** [comment]
@azura27 This is by design, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials for detais.

**Comment by azura27** [comment]
> @azura27 This is by design, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials for detais.

This DOC only says "Access-Control-Allow-Origin" should not be “*”, not all other headers should not be "*". Am I got the right link:  "Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’"

**Comment by tokers** [comment]
> > @azura27 This is by design, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials for detais.
> 
> This DOC only says "Access-Control-Allow-Origin" should not be “_”, not all other headers should not be "_". Am I got the right link: "Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’"

Not sure about other headers. @ShiningRush What are the original design considerations about this?

**Comment by tokers** [comment]
> > @azura27 This is by design, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials for detais.
> 
> This DOC only says "Access-Control-Allow-Origin" should not be “_”, not all other headers should not be "_". Am I got the right link: "Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’"

Not sure about other headers. @ShiningRush What are the original design considerations about this?

**Comment by ShiningRush** [comment]
You can learn more detail about `Access-Control-Allow-Origin` in [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#directives) and [CORSNotSupportingCredentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

**Comment by azura27** [comment]
> You can learn more detail about `Access-Control-Allow-Origin` in [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#directives) and [CORSNotSupportingCredentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials)

NOT find the evidence either. In our product environment, this is not suitable, and in similar gateway server KONG, the headers config onliy limit origin. We've remove other headers' limitation in our own ENV.  If this is the design, then take this issue as an suggestion

**Comment by ShiningRush** [comment]
>For requests without credentials, the literal value "*" can be specified, as a wildcard; the value tells browsers to allow requesting  code from any origin to access the resource. **Attempting to use the wildcard with credentials will result in an error**.

I believe the information I posted has been described clearly enough, please read it carefully.

**Comment by azura27** [comment]
OK, got it. my focus is origin (the value tells browsers to allow requesting code from any **origin** to access the resource), and yours is this sentence "for requests without credentials, the literal value "*" can be specified, as a wildcard" .

**Comment by ShiningRush** [comment]
BTW: I compared the Chinese and English versions of  [Access-Control-Allow-Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin#directives), and found that the Chinese version did not mention wildcard related matters. Maybe you are viewing its Chinese version page?

**Comment by azura27** [comment]
OK, thanks a lot
