### ISSUE TITLE
Failed to start apisix on Kylin V10, ARM Architecture

### ISSUE THREAD

**Issue by Molio-tan** [apache/apisix#4497]
### Issue description
When I installed the Apisix, `make deps` seemed like no problem, but I execute the comman for start: `./bin/apisix start`, there is error:
![image](https://user-images.githubusercontent.com/31587573/123609530-4f941000-d832-11eb-902d-cadd789a5780.png)
Anyway, `./bin/apisix version` was executed with the same error.

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): Linux localhost.localdomain 4.19.90-17.ky10.aarch64 #1 SMP Sun Jun 28 14:27:40 CST 2020 aarch64 aarch64 aarch64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.5.0
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.3.1

### Installation
1. install openssl111
```
    wget https://www.openssl.org/source/openssl-1.1.1d.tar.gz
    tar -xzf openssl-1.1.1d.tar.gz 
    cd openssl-1.1.1d
    ./config
    make && make test && make install
```
2. install openresty
```
    tar -xzf openresty-1.19.3.1.tar.gz
    cd openresty-1.19.3.1
    ./configure --prefix=/usr/local/openresty --with-luajit --without-http_redis2_module --with-http_iconv_module --with-http_postgres_module  --with-openssl=$alb_install_dir/openssl-1.1.1d
    make && make install
```
3. install apisix
```
git clone https://github.com/apache/apisix.git
cd apisix
make deps
```
4. start apisix
```
./bin/apisix start
```

**Comment by tokers** [comment]
It seems that the `zlib` installation is broken. Could you paste the `ldd` output of the openresty command?

**Comment by Molio-tan** [comment]
> It seems that the `zlib` installation is broken. Could you paste the `ldd` output of the openresty command?

I don't figure out the `ldd` output of the openresty command.Could you show me what command to be executed?thx

**Comment by tokers** [comment]
> figure out

Just run "ldd \`which openresty\`". If your OpenResty binary is inside the PATH environment.

**Comment by Molio-tan** [comment]
> > figure out
> 
> Just run "ldd `which openresty`". If your OpenResty binary is inside the PATH environment.

![image](https://user-images.githubusercontent.com/31587573/123781489-e6320100-d906-11eb-854e-34a265a01793.png)

**Comment by tokers** [comment]
It seems that the OpenResty you used referring to the system zlib package, and it might missing the symbol `zErrror`. How did you install the OpenResty?

**Comment by Molio-tan** [comment]
> It seems that the OpenResty you used referring to the system zlib package, and it might missing the symbol `zErrror`. How did you install the OpenResty?

At the first you can see my process of [installing the OpenResty](https://github.com/apache/apisix/issues/4497#issue-931421993). I installed it with source code.By the way,  I can test OpenResty successfully with `openresty -p . -c nginx.conf`.
The `nginx.conf`:
```
user root;
worker_processes  1;
worker_rlimit_core 100m;
error_log logs/error.log;

events {
    worker_connections 1024;
}

http {
    server {
        listen 6666;
        location / {
            default_type text/html;
             content_by_lua '
                ngx.say("<p>Hello, World!</p>")
            ';
        }
    }
}

```

**Comment by Molio-tan** [comment]
Without any solutions,after many times of reinstall,it does work.
