### ISSUE TITLE
bug: nacos discovery not support base auth include `%` chars.

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix#4513]
### Issue description
e.g. discovery.nacos.host will be `"http://${username}:${password}@${host1}:${port1}"` ,if username or passowrd has `@` should be replace `%40` (ref https://stackoverflow.com/a/6718568) 

but apsix 2.7 regular expression is `[a-zA-Z0-9-_.:\@]`
https://github.com/apache/apisix/blob/174044e60cfbad6f8aa023200f3be145f5249ed1/apisix/discovery/nacos.lua#L45

will throw exception 
```
2021/07/01 09:27:09 [error] 54#54: init_worker_by_lua error: /usr/local/apisix/apisix/discovery/nacos.lua:312: invalid nacos configuration: property "host" validation failed: failed to validate item 1: failed to match pattern "^http(s)?:\\/\\/[a-zA-Z0-9-_.:\\@]+$" with "https://admin:%40123%40@nacos.xxx.xxx:443"
```

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.7-alpine
* OS (cmd: `uname -a`): ubuntu 16.04 LTS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

**Comment by spacewander** [comment]
Thanks for your report. 
PR is welcome!

**Comment by spacewander** [comment]
We can fix the regex.

**Comment by anjia0532** [comment]
@spacewander  thanks
