### ISSUE TITLE
bug: nacos fetch instance list got error

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix#4514]
### Issue description

`2021/07/01 10:28:30 [error] 44#44: *32565 [lua] nacos.lua:303: get_url:ns/instance/list?healthyOnly=true&serviceName= err:20: unable to get local issuer certificate, context: ngx.timer`

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): apisix:2.7-alpine
* OS (cmd: `uname -a`): ubuntu 16.04LTS
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

**Comment by anjia0532** [comment]
`curl https://nacos.xxxx/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=xxxx&namespaceId=xxx` is ok

**Comment by tokers** [comment]
How did you configure the `lua_ssl_trusted_certificates` item in `config.yaml`?

**Comment by anjia0532** [comment]
@tokers No,use website doc to config it, I don't know about this config properties more info.

![image](https://user-images.githubusercontent.com/15098916/124207690-a17db400-db18-11eb-9b38-6bf5ea131830.png)

OK,find it from openresty https://github.com/openresty/lua-nginx-module#lua_ssl_trusted_certificate and I'll try it.

**Comment by anjia0532** [comment]
Not work.

1. Use apache:apisix:2.7-alpine and use `find / -name *.pem` to got root PEM.
```yaml

nginx_config:
# ...
  http:
    lua_ssl_verify_depth: 2
    lua_ssl_trusted_certificate: /etc/ssl/certs/ca-cert-GlobalSign_Root_CA.pem
```
same error info again
`2021/07/02 01:51:23 [error] 44#44: *25319 [lua] nacos.lua:303: get_url:ns/instance/list?healthyOnly=true&serviceName= err:20: unable to get local issuer certificate, context: ngx.timer`

**Comment by spacewander** [comment]
What's your OpenSSL built with Nginx?
OpenSSL 1.0.x doesn't work with Let's Encrypt: https://community.letsencrypt.org/t/openssl-client-compatibility-changes-for-let-s-encrypt-certificates/143816

**Comment by anjia0532** [comment]
@spacewander [apache/apisix:2.7-alpine](https://hub.docker.com/layers/apache/apisix/2.7-alpine/images/sha256-b9bea90dac390021db097cf8fb1256aba59c4a0943a44fa0d891f317b2081567?context=explore)

**Comment by tokers** [comment]
@anjia0532 Please output the result of `openresty -V`.

**Comment by anjia0532** [comment]
用的就是官方的docker镜像 [apache/apisix:2.7-alpine](https://hub.docker.com/layers/apache/apisix/2.7-alpine/images/sha256-b9bea90dac390021db097cf8fb1256aba59c4a0943a44fa0d891f317b2081567?context=explore)
```
bash-5.1# openresty -V
nginx version: openresty/1.19.3.1
built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl/lib -Wl,-rpath,/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl/lib' --with-pcre --with-compat --with-file-aio --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_geoip_module=dynamic --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-ipv6 --with-mail --with-mail_ssl_module --with-md5-asm --with-pcre-jit --with-sha1-asm --with-stream --with-stream_ssl_module --with-threads --with-stream --with-stream_ssl_preread_module
```

**Comment by tokers** [comment]
Does the `/etc/ssl/certs/ca-cert-GlobalSign_Root_CA.pem` sign the Nacos server certificate directly? If not, does this file contain the intermediate CA certificate (as I saw the `Root` keyword in this cert file).

**Comment by anjia0532** [comment]
@tokers Nacos server certificate is generate by [https://letsencrypt.org/](https://letsencrypt.org/) .It's not a two-way certificate.
run with curl ( `curl https://nacos.xxxx/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=xxxx&namespaceId=xxx`) is ok .

> Nacos 服务器的证书是通过 [https://letsencrypt.org/](https://letsencrypt.org/) 生成的普通单向证书，不是双向证书。在apisix的容器里使用curl 访问是可以的 `curl https://nacos.xxxx/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=xxxx&namespaceId=xxx` . 根据 https://letsencrypt.org/certificates/ 所说的，letsencrypt的上一级签发是 ISRG_Root，我换成 `lua_ssl_trusted_certificate: "/etc/ssl/certs/ca-cert-ISRG_Root_X1.pem"` 也不行。
> 我现在将https降级成http，是可以同步了。

**Comment by tokers** [comment]
> @tokers Nacos server certificate is generate by https://letsencrypt.org/ .It's not a two-way certificate.
> run with curl ( `curl https://nacos.xxxx/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=xxxx&namespaceId=xxx`) is ok .
> 
> > Nacos 服务器的证书是通过 https://letsencrypt.org/ 生成的普通单向证书，不是双向证书。在apisix的容器里使用curl 访问是可以的 `curl https://nacos.xxxx/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=xxxx&namespaceId=xxx` . 根据 https://letsencrypt.org/certificates/ 所说的，letsencrypt的上一级签发是 ISRG_Root，我换成 `lua_ssl_trusted_certificate: "/etc/ssl/certs/ca-cert-ISRG_Root_X1.pem"` 也不行。
> > 我现在将https降级成http，是可以同步了。

I mean, what is the relationship between the Nacos server certificate and the `/etc/ssl/certs/ca-cert-GlobalSign_Root_CA.pem`?

**Comment by anjia0532** [comment]
我对这块不是很熟悉，上文中有解释，/etc/ssl/certs/ca-cert-GlobalSign_Root_CA.pem 是我随便选了一个根证书(find / -name *.pem)，发现不行后，又根据https://letsencrypt.org/certificates/  找了一个ISRG_Root的试了一下也不行，我不太清除为啥一个公共签署的还不被信任，（letsencrypt应该是一个很常见的方案，理论上不应该也不需要再单独配置一个信任证书）

您的意思是，需要我针对这个证书，单独用Openssl签一个信任证书给apisix? 感觉有点怪怪的，有参数可以忽略信任校验么(或许这个问题我应该去openresty社区提问？但是我不太确认是apisix的问题，还是apisix+alpine的问题，还是openresty的问题)？

**Comment by tokers** [comment]
@anjia0532 The `lua_ssl_trusted_certificate` should be configured to the CA cert which signing the Nacos server cert.

**Comment by anjia0532** [comment]
OK ,Fine. I surrender. nacos change to http protocol . works good. thanks .I'll close this.

**Comment by anjia0532** [comment]
Use `curl -v https://nacos.xxx.xxx` to get Key Point info `successfully set certificate verify locations: CAfile: /etc/ssl/certs/ca-certificates.crt`

Config lua_ssl_trusted_certificate  to /etc/ssl/certs/ca-certificates.crt and restart apisix
![image](https://user-images.githubusercontent.com/15098916/124235397-c1789c00-db47-11eb-9756-84144528d982.png)

same error again.
![image](https://user-images.githubusercontent.com/15098916/124235441-cfc6b800-db47-11eb-93b4-c376b70906e5.png)


```
curl -v https://nacos.xxx.xxx

*   Trying 192.168.32.204:443...
* Connected to nacos.xxx.xxx (192.168.32.204) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=xxx.xxx
*  start date: Jun 22 08:48:18 2021 GMT
*  expire date: Sep 20 08:48:17 2021 GMT
*  subjectAltName: host "nacos.xxx.xxx" matched cert's "*.xxx.xxx"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7f03d28aca90)
> GET / HTTP/2
> Host: nacos.xxx.xxx
> user-agent: curl/7.77.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< date: Fri, 02 Jul 2021 07:07:40 GMT
< content-type: text/html;charset=utf-8
< content-length: 431
< vary: Accept-Encoding
< content-language: en
< server: BWS/1.1
````

**Comment by spacewander** [comment]
@anjia0532 
Do you try curl inside the docker image?
Maybe we can do some packet capture and find the difference between the curl and the openresty?

**Comment by anjia0532** [comment]
@spacewander Yes. Run the curl command inside website docker image `apache/apisix:2.7-alpine`.

```
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
```

configure the conf/config.yaml

```yaml
nginx_config:
# ...
  http:
    lua_ssl_verify_depth: 2
    lua_ssl_trusted_certificate: "/etc/ssl/certs/ca-certificates.crt"
# ...
```
and restart apisix container

error again

`2021/07/02 01:51:23 [error] 44#44: *25319 [lua] nacos.lua:303: get_url:ns/instance/list?healthyOnly=true&serviceName= err:20: unable to get local issuer certificate, context: ngx.timer`

**Comment by spacewander** [comment]
Would you send us certificates (the nacos's and the trusted one) to reproduce this issue?

**Comment by anjia0532** [comment]
@spacewander send it to your email( spacewanderlzx@gmail.com )

**Comment by spacewander** [comment]
I reproduce the issue and solve it via configuration:
```
apisix:
  ssl:
    ssl_trusted_certificate: /etc/ssl/certs/ca-certificates.crt
```

**Comment by anjia0532** [comment]
@spacewander 谢谢，我看到config_default.yaml中有配置这个参数 

https://github.com/apache/apisix/blob/d4c7fbbe831bc12c50ba63f00757f0eee14eae15/conf/config-default.yaml#L117 

1. 有点疑惑，以为是openresty的配置，所以之前测试都放到了 `nginx_config` 下，是不是可以理解为，`nginx_config`都是nginx的配置项，openresty和apisix的都在`apisix`下？
2. 什么场景下需要设置 `ssl_trusted_certificate` ，反向代理https? https 双向认证？`serverless-*-function` 相关函数调用https服务时？

**Comment by spacewander** [comment]
1. this directive is between Nginx configuration and SSL relative stuff.
2. when you try to connect TLS services with cosocket

**Comment by anjia0532** [comment]
@spacewander OK ,thanks. I'll close this issues and supplemental documentation to explain this problem (`unable to get local issuer certificate`)
