### ISSUE TITLE
request help: skywalking无法修改endpoint_addr

### ISSUE THREAD

**Issue by CraxGrix** [apache/apisix#4517]
### Issue description

请问能否提供修改示例，每当我修改的时候都会提示Invalid plugin data。

<img width="1278" alt="WeChat750a91d6fc7fc9d8ca7cf410944673ca" src="https://user-images.githubusercontent.com/16173957/124124026-87a58800-daaa-11eb-9f3b-3a3ba75f1007.png">

### Environment

Request help without environment information will be ignored or closed.

* apisix version:2.7
* OS (cmd: `uname -a`):
* Linux aliyun-linux-4c-16g-01 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* nginx version: openresty/1.19.3.2
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled

* etcd version:{"id":"71f5a178-0fa5-4d24-ad133a771e119065","up_time":865,"version":"2.7","boot_time":1625141588,"etcd_version":"3.4.0","hostname":"aliyunlinux-4c-16g-01","last_report_time":1625142428}

* apisix-dashboard version, if have:  2.6
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):/usr/local/bin/luarocks 3.4.0

**Comment by CraxGrix** [comment]
这是config.yaml
<img width="852" alt="WeChat4b64428f70d4969af39d398bbb824eeb" src="https://user-images.githubusercontent.com/16173957/124124937-9e001380-daab-11eb-9e02-aca443261b57.png">

**Comment by spacewander** [comment]
endpoint_addr can only be set via static configuration file config.yaml.
