### ISSUE TITLE
Cors plug-in configuration allow_credential is true, need to pay attention to other configuration items cannot exist

### ISSUE THREAD

**Issue by cendawei** [apache/apisix#4522]
# Improve Docs

## cors配置文档

当allow_credential为true时

## 除allow_credential的其他配置项

注意不能为*，因为各配置项有默认值，字段值可显式设为空

**Comment by Yiyiyimu** [comment]
Hi @cendawei PR Welcome!

**Comment by tokers** [comment]
@cendawei 
 https://github.com/apache/apisix/blob/master/apisix/plugins/cors.lua#L134-L139
