### ISSUE TITLE
[DISCUSS] Make parts of API URL much simpler

### ISSUE THREAD

**Issue by KishaniKandasamy** [apache/apisix#4526]
# Improve Docs
Hi everyone, 
I'm currently working on [this project](https://summer.iscas.ac.cn/#/org/orgdetail/apacheapisix/proid210050255?lang=en) under the mentorship of @juzhiyuan .
Before making any changes, It would be great with your opinions.

## Please describe which part of docs should be improved or typo fixed
we could make the parts of API URL (in https://apisix.apache.org/docs/apisix/getting-started) in a simple view that can be easily understandable .

![Screenshot 2021-07-03 003026](https://user-images.githubusercontent.com/53715187/124364122-06422700-dc5d-11eb-81d2-588133b41832.jpg)

## Describe the solution you'd like
We could change the above description  into something  similar to  this.
![marketers-guide-to-apis-api-breakdown](https://user-images.githubusercontent.com/53715187/124364163-45707800-dc5d-11eb-8768-cd954df0acdf.png)
What do you think?

**Comment by KishaniKandasamy** [comment]
Hi everyone What about this?
![requesturl](https://user-images.githubusercontent.com/53715187/124796106-6c38f200-df6e-11eb-9338-1707559c0eb0.jpg)

**Comment by Yiyiyimu** [comment]
Hi @KishaniKandasamy sorry I failed to get which place should we change

**Comment by tzssangglass** [comment]
> Hi @KishaniKandasamy sorry I failed to get which place should we change

I think he meant to turn the text description of the url, such as protocl, host, etc., into the form of an image, more intuitive.

**Comment by tzssangglass** [comment]
> Hi everyone What about this?
> ![requesturl](https://user-images.githubusercontent.com/53715187/124796106-6c38f200-df6e-11eb-9338-1707559c0eb0.jpg)

the port part is missing from the image

**Comment by KishaniKandasamy** [comment]
> > Hi everyone What about this?
> > ![requesturl](https://user-images.githubusercontent.com/53715187/124796106-6c38f200-df6e-11eb-9338-1707559c0eb0.jpg)
> 
> the port part is missing from the image

Hi  @tzssangglass , Thanks for the feedback but I thought we could omit port number in URLs, As if it is not given  then the  User may know that By default, HTTP uses port 80🤔.What do you think?

**Comment by tzssangglass** [comment]
> Hi @tzssangglass , Thanks for the feedback but I thought we could omit port number in URLs, As if it is not given then the User may know that By default, HTTP uses port 80🤔.What do you think?
> ![url](https://user-images.githubusercontent.com/53715187/124855058-02e4cd80-dfc6-11eb-81ad-b1975f93f209.jpg)

I am afraid of ambiguity. I think adding the default port 80 to the image will remove the ambiguity.

**Comment by KishaniKandasamy** [comment]
Yesss then It would be better doing  so:)
