### ISSUE TITLE
request help:  about configuring grayscale release

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4527]
### Issue description
As we all know, apisix currently supports cluster deployment. 

Suppose we currently have 5 apisix instances. After updating a certain configuration, we only want to publish to a certain instance for verification, and then publish to the remaining 4 instances after the verification is passed. 

Is this feature apisix considered to support it?

**Comment by spacewander** [comment]
So you want to manage two different versions of APISIX with the same version of CP?

**Comment by zuiyangqingzhou** [comment]
Yes, it can be understood that, I want to have multiple versions of the configuration effective on different apisix instances in a certain period of time.

Because when we create a new configuration or modify a configuration, we always want to verify it with a small amount of traffic, instead of directly pushing it to the global traffic.

**Comment by tokers** [comment]
@zuiyangqingzhou There is a useful trick that can used to implement the configuration grayscale, Apache APISIX supports configuring a Route object with route match expressions (the `vars` field in Route), you may add an expression to specify the set of APISIX instances that will use the route.

```json
{
  "vars": [
    ["server_addr", "==", "172.17.13.3"]
  ]
}
```
