### ISSUE TITLE
request help: There are ambiguities in the understanding of several parameters of the health check

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4528]
### Issue description

first：
>
> https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L136
> 
> Regarding this timeout, I understand that it is the timeout period of the upstream health check. If the upstream does not respond after this time, it may be marked as a suspected unhealthy node

second:
>  
> https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L146-L167
>
> Regarding this code, what I understand is that there can be independent health check intervals for healthy upstream. If several consecutive cycles (depending on the number of successful configurations) are OK, it is considered a healthy node, otherwise it is considered to be a Unhealthy node

third:
>
> https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L172-L202
> I understand that the interval time here is to control the interval time for detecting unhealthy nodes, but there is a timeout parameter here. What is the difference between this timeout time and the timeout time of the first code snippet?

Is my understanding of the three code snippets correct? What is the difference between the timeout parameter in the first and third paragraphs?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
The `timeouts` under `unhealthy` is used to configure how many timeout events should occur so an endpoint can be set to unhealthy, not to configure the connection timeout.

**Comment by zuiyangqingzhou** [comment]
> The `timeouts` under `unhealthy` is used to configure how many times that timeout events should occur so an endpoint can be set to unhealthy, not to configure the connection timeout.

https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L184-L195

Okay, if timeouts represents the number of timeouts, how do you understand the number of failures of http_failures and tcp_failtures? I understand that if it times out, it shouldn’t be a failure?

**Comment by tokers** [comment]
> > The `timeouts` under `unhealthy` is used to configure how many times that timeout events should occur so an endpoint can be set to unhealthy, not to configure the connection timeout.
> 
> https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L184-L195
> 
> Okay, if timeouts represents the number of timeouts, how do you understand the number of failures of http_failures and tcp_failtures? I understand that if it times out, it shouldn’t be a failure?

timeouts, http_failures and tcp_faileres are three kinds of exceptions, all the settings here is used to indicate the number.

**Comment by zuiyangqingzhou** [comment]
> > > The `timeouts` under `unhealthy` is used to configure how many times that timeout events should occur so an endpoint can be set to unhealthy, not to configure the connection timeout.
> > 
> > 
> > https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L184-L195
> > 
> > Okay, if timeouts represents the number of timeouts, how do you understand the number of failures of http_failures and tcp_failtures? I understand that if it times out, it shouldn’t be a failure?
> 
> timeouts, http_failures and tcp_faileres are three kinds of exceptions, all the settings here is used to indicate the number.

I try to understand what you mean. Do you see right? 

That is to say, timeout and failure are in two dimensions. Whether it is a health check interface call timeout or a failed status code, we all think that this node is unhealthy

Is my understanding correct？

**Comment by tokers** [comment]
> > > > The `timeouts` under `unhealthy` is used to configure how many times that timeout events should occur so an endpoint can be set to unhealthy, not to configure the connection timeout.
> > > 
> > > 
> > > https://github.com/apache/apisix/blob/cb8e41d5f4037c332978dc21eff7a63e0ab48322/apisix/schema_def.lua#L184-L195
> > > 
> > > Okay, if timeouts represents the number of timeouts, how do you understand the number of failures of http_failures and tcp_failtures? I understand that if it times out, it shouldn’t be a failure?
> > 
> > 
> > timeouts, http_failures and tcp_faileres are three kinds of exceptions, all the settings here is used to indicate the number.
> 
> I try to understand what you mean. Do you see right?
> 
> That is to say, timeout and failure are in two dimensions. Whether it is a health check interface call timeout or a failed status code, we all think that this node is unhealthy
> 
> Is my understanding correct？

I think so.
