### ISSUE TITLE
apisix plugin write test cases

### ISSUE THREAD

**Issue by GrantZheng** [apache/apisix#4534]
你好，请问apisix plugin 如何编写测试用例，有没有好的最佳实践？

**Comment by Yiyiyimu** [comment]
Hi @GrantZheng you could refer to test cases of other plugins for now, since we haven't got best practise currently 🤣 But welcome contributing yours when you finish your tests.

**Comment by tzssangglass** [comment]
hope it helps you: https://github.com/iresty/programming-openresty-zh/tree/master/testing
