### ISSUE TITLE
request help: Is Plugin shared memory shared across cluster

### ISSUE THREAD

**Issue by sagivoulu** [apache/apisix#4543]
### Issue description
In many plugins I see the use of ```ngx.shared[]``` to store information (i.e. Circuit breaker counter, request limit counter etc...). Where does this information get stored? In the local memory of the api gateway? In the control plane etcd? 

I am asking because some plugin use cases (request limiting, circuit breaker, authentication session and more) require this data to be stored in a shared memory store (i.e. Redis / memcash / etcd), so a cluster of apisix instances can access it. 

B.T.W I know that some plugins have configuration options to specify a shared memory like redis, but I am not talking about these plugins.

**Comment by spacewander** [comment]
In the local memory of the api gateway.
See https://github.com/openresty/lua-nginx-module#ngxshareddict

**Comment by sagivoulu** [comment]
Thanks, that answers my question.
