### ISSUE TITLE
request help: what's the most recommended way to share variables between plugins in a single request

### ISSUE THREAD

**Issue by Huweicai** [apache/apisix#4545]
I have several plugins being miggrated from **Kong** to **APISIX**.
In Kong, plugins share variables use [kong.ctx.shared](https://docs.konghq.com/gateway-oss/2.4.x/pdk/kong.ctx/#kongctxshared) to work together.
I wonder what's the most recommended way to do it in APISIX?
Can I just attach these variables to ctx ? Like this:
```
function _M.access(conf, ctx)
    ctx.var1 = "xxxx"
    ctx.var2 = "xxxx"
    core.log.warn(ctx.var1)
    core.log.warn(ctx.var2)
end
```

**Comment by spacewander** [comment]
Yes. If you worry about name conflict, you can add your plugin name as the prefix.

**Comment by Huweicai** [comment]
> Yes. If you worry about name conflict, you can add your plugin name as the prefix.

Thanks.
