### ISSUE TITLE
bug: 404 route not found if URI contains %0A

### ISSUE THREAD

**Issue by gxthrj** [apache/apisix#4547]
### Issue description
If URI contains %0A, will cause route match failed.

### Environment

* apisix version (cmd: `apisix version`): 2.6

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. create a route
```
curl http://127.0.0.1:9080/apisix/admin/routes/31 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "*",
    "hosts": ["foo.com"],
    "methods": ["PUT", "GET"],
    "enable_websocket": true,
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'
```
2. have a try with normal request
```
curl -i http://127.0.0.1:9080/ip -H "Host:foo.com"
```
It will be success.

```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 45
Connection: keep-alive
Date: Tue, 06 Jul 2021 14:47:10 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/2.6

{
  "origin": "172.19.0.1, 114.220.17.103"
}
```
3. If URI contains %0A
```
curl -i http://127.0.0.1:9080/ip%0AVega -H "Host:foo.com"
```
will get 404
```
HTTP/1.1 404 Not Found
Date: Tue, 06 Jul 2021 14:35:51 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.6

{"error_msg":"404 Route Not Found"}
```

### What's the expected result?
Expect normal routing, and upstream returns 404
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

**Comment by tokers** [comment]
What is the exact behavior if you access the upstream directly with this URL?

**Comment by gxthrj** [comment]
> What is the exact behavior if you access the upstream directly with this URL?

It has been writen here.

![image](https://user-images.githubusercontent.com/4413028/124689692-8ab9d180-df0b-11eb-9908-866c99c5995f.png)

**Comment by tokers** [comment]
> > What is the exact behavior if you access the upstream directly with this URL?
> 
> It has been written here.
> 
> ![image](https://user-images.githubusercontent.com/4413028/124689692-8ab9d180-df0b-11eb-9908-866c99c5995f.png)

I mean, don't use APISIX as the proxy.

**Comment by spacewander** [comment]
Look like it is a bug in the route match library.

**Comment by gxthrj** [comment]
> > > What is the exact behavior if you access the upstream directly with this URL?
> > 
> > 
> > It has been written here.
> > ![image](https://user-images.githubusercontent.com/4413028/124689692-8ab9d180-df0b-11eb-9908-866c99c5995f.png)
> 
> I mean, don't use APISIX as the proxy.

Using Nginx, it will return from upstream. Because the location is '*'.

**Comment by gxthrj** [comment]
> Look like it is a bug in the route match library.

Yep

**Comment by JanLi-air** [comment]
Is there an easy fix for this? When can we expect a fix?

**Comment by membphis** [comment]
fixed: https://github.com/api7/lua-resty-radixtree/pull/99

**Comment by gxthrj** [comment]
Great~

**Comment by Yiyiyimu** [comment]
need to use new version before closing this issue. my bad
