### ISSUE TITLE
edit body request

### ISSUE THREAD

**Issue by HamsterBoi** [apache/apisix#4565]
hey, is there an option to edit the body request before moving it forward to the target host?

**Comment by Yiyiyimu** [comment]
Hi @HamsterBoi as far as I found in [proxy-rewrite](http://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/), it seems we haven't support rewriting body yet. 

PR's welcome!

**Comment by spacewander** [comment]
Can be implemented in a custom plugin.
