### ISSUE TITLE
request help: The upstream service configures the service name, but the service name corresponds to multiple nodes. Does the health check have any effect?

### ISSUE THREAD

**Issue by xuyancheng24** [apache/apisix#4568]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.7
* OS (cmd: `uname -a`):Linux 192.168.126.128 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.13
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.5.0

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

**Comment by spacewander** [comment]
This is a test for it: https://github.com/apache/apisix/blob/master/t/node/healthcheck-discovery.t

Please don't submit such a "bug report".
