### ISSUE TITLE
request help: traffic-split The plug-in does not support graying of parameters in the body at present. I hope it can support it

### ISSUE THREAD

**Issue by philzhangrui** [apache/apisix#4579]
#**## **traffic-split**   
The plug-in does not support graying of parameters in the body at present. I hope it can support it

**Comment by tokers** [comment]
@philzhangrui Support for body parsing is somewhat tricky, as we also need to consider the size of body, the format of body.

Do you have some good suggestions about this?

**Comment by spacewander** [comment]
What about writing a plugin run before the traffic-split, and parse the body, convert to the header which can be handled by traffic-split?

**Comment by philzhangrui** [comment]
this is good idea

**Comment by spacewander** [comment]
https://github.com/apache/apisix/blob/32f9d699a986864612963868d7d23408e3860550/apisix/core/ctx.lua#L54
