### ISSUE TITLE
request help: suggestions on improving the default_conn_delay of the limit-conn plugin

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4583]
### Issue description
The default_conn_delay of the limit-conn plug-in is used to control the delay of forwarding to upstreams when the connection exceeds a certain threshold, but after actual testing, it is found that this delay time is not strictly in accordance with the configured delay time.

https://github.com/openresty/lua-resty-limit-traffic/blob/master/lib/resty/limit/conn.lua#L98-L101

It is found in the source code of lua-resty-limit-traffic that there is a certain calculation logic for the delay time. If req_latency is nil, the delay time is strictly in accordance with the user-defined delay time

I think a control parameter should be added in apisix to let users decide whether the delay time should be strictly in accordance with the configured time

What do you think？

**Comment by spacewander** [comment]
PR is welcome!

**Comment by zuiyangqingzhou** [comment]
ok, i will make a try
