### ISSUE TITLE
request help: how use lua_shared_dict in t file

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#4588]
### Issue description
In unit test,i don't know how to use lua_shared_dict,and set value in it. Can you help me?

### Environment
OS:macOS
apisix:2.5

**Comment by spacewander** [comment]
Declare it in APISIX.pm and use it normally in the Lua code.

**Comment by shoulda** [comment]
> Declare it in APISIX.pm and use it normally in the Lua code.

ok ,thanks
