### ISSUE TITLE
bug: Grafana中没有数据

### ISSUE THREAD

**Issue by zhixiang0608** [apache/apisix#4590]
你好，我在Grafana中只有nginx和etcd的数据，没有bandwidth,http
我发现grafana里的`sum(rate(apisix_http_status{service=~"$service",route=~"$route",instance=~"$instance"}[1m])) by (service)`
在源数据中查询并没有返回
![image](https://user-images.githubusercontent.com/46064678/125375713-2049db00-e3bc-11eb-81ef-d9975d7b3a04.png)

**Comment by zhixiang0608** [comment]
version：2.7

**Comment by spacewander** [comment]
@Yiyiyimu 
Could you have a look when you have free time?

@zhixiang0608 
What's the output when you query the prometheus uri in APISIX directly? Does it have any data?

**Comment by zhixiang0608** [comment]
![image](https://user-images.githubusercontent.com/46064678/125376463-a0247500-e3bd-11eb-861f-769167a85cd3.png)
我的源数据中service="",consumer=""都是为空字符串

**Comment by zhixiang0608** [comment]
我发现这个sql在grafana中是有数据的
histogram_quantile(0.95, sum(rate(apisix_http_latency_bucket{type=~"apisix",service=~"$service",consumer=~"$consumer",node=~"$node"}[5m])) by (le))
我修改了rate里的间隔时间

**Comment by tokers** [comment]
@zhixiang0608 Have you ever enabled the Prometheus plugin?

**Comment by zhixiang0608** [comment]
我启用了

**Comment by starsz** [comment]
@zhixiang0608 Have you enabled the plugin in route or service or global_rule?

**Comment by zhixiang0608** [comment]
是的，我已经启用了
我把所有时间间隔都设置为2m后，都有数据返回了，谢谢各位~
