### ISSUE TITLE
request help: make init failed

### ISSUE THREAD

**Issue by yuhaizr** [apache/apisix#4594]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.7
* OS (cmd: `uname -a`): 2.6.32-754.24.3.el6.x86_64 
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):  3.0.4

执行完 make deps 之后 执行  make init 报以下错误，麻烦帮忙看看怎么解决？
./bin/apisix init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit: error loading module 'socket.core' from file '/usr/local/apisix-2.7/deps/lib/lua/5.1/socket/core.so':
        /usr/local/apisix-2.7/deps/lib/lua/5.1/socket/core.so: undefined symbol: lua_callk
stack traceback:
        [C]: at 0x00452e40
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/socket.lua:12: in main chunk
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/socket/http.lua:10: in main chunk
        [C]: in function 'require'
        ./apisix/cli/etcd.lua:23: in main chunk
        [C]: in function 'require'
        ./apisix/cli/ops.lua:18: in main chunk
        [C]: in function 'require'
        ./apisix/cli/apisix.lua:32: in main chunk
        [C]: at 0x00404c80
make: *** [init] 错误 1

**Comment by tokers** [comment]
It seems that `lua_callk` is an ABI introduced in Lua/5.3, how did you install the luasocket?

**Comment by yuhaizr** [comment]
> 
> 
> It seems that `lua_callk` is an ABI introduced in Lua/5.3, how did you install the luasocket?

luasocket 我这边没有去安装，我之前用的 make deps？然后我需要单独安装luasocket ？
还有就是一开始我用的lua是5.3 ，发现不行，我改成了5.1 也是不行

**Comment by tokers** [comment]
What about using the luajit carried by openresty?

**Comment by yuhaizr** [comment]
> 
> 
> What about using the luajit carried by openresty?

我现在用的就是 openresty 自带的 luajit

**Comment by tzssangglass** [comment]
> 还有就是一开始我用的lua是5.3 ，发现不行，我改成了5.1 也是不行

I think you need to clean up your environment and re-run `make deps`.

Maybe you ran `make deps` with Lua 5.3 and compiled `socket.so`, even if you switch to Lua 5.1, it will not recompile to generate `socket.so`.

**Comment by shuaijinchao** [comment]
You can try the following steps:
1. rm -rf /apisix-path/deps
2. Recompile and install luarocks and specify the `luajit` header file directory, for example: `./configure --with-lua-include=/openresty-path/luajit/include/luajit-2.1`
3. Enter the apisix directory and re-execute `make deps` to install dependencies

**Comment by yuhaizr** [comment]
> 
> 
> You can try the following steps:
> 
>     1. rm -rf /apisix-path/deps
> 
>     2. Recompile and install `luarocks` and specify the `luajit` header file directory, for example: `./configure --with-lua-include=/openresty-path/luajit/include/luajit-2.1`
> 
>     3. Enter the apisix directory and re-execute `make deps` to install dependencies

我安装你的方法做了之后，上面的问题解决了，然后又出现了新的问题：

./bin/apisix init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so':
        /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list
stack traceback:
        [C]: at 0x00452d70
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/ssl.lua:8: in main chunk
        [C]: in function 'require'
        /usr/local/apisix-2.7/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
        [C]: in function 'require'
        ./apisix/cli/etcd.lua:24: in main chunk
        [C]: in function 'require'
        ./apisix/cli/ops.lua:18: in main chunk
        [C]: in function 'require'
        ./apisix/cli/apisix.lua:32: in main chunk
        [C]: at 0x00404c80
make: *** [init] 错误 1

**Comment by tokers** [comment]
> > You can try the following steps:
> > ```
> > 1. rm -rf /apisix-path/deps
> > 
> > 2. Recompile and install `luarocks` and specify the `luajit` header file directory, for example: `./configure --with-lua-include=/openresty-path/luajit/include/luajit-2.1`
> > 
> > 3. Enter the apisix directory and re-execute `make deps` to install dependencies
> > ```
> 
> 我安装你的方法做了之后，上面的问题解决了，然后又出现了新的问题：
> 
> ./bin/apisix init
> /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
> /usr/local/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so':
> /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list
> stack traceback:
> [C]: at 0x00452d70
> [C]: in function 'require'
> /usr/local/apisix-2.7/deps/share/lua/5.1/ssl.lua:8: in main chunk
> [C]: in function 'require'
> /usr/local/apisix-2.7/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
> [C]: in function 'require'
> ./apisix/cli/etcd.lua:24: in main chunk
> [C]: in function 'require'
> ./apisix/cli/ops.lua:18: in main chunk
> [C]: in function 'require'
> ./apisix/cli/apisix.lua:32: in main chunk
> [C]: at 0x00404c80
> make: *** [init] 错误 1

What about removing the ./deps` directory and re-execute `make deps`?

**Comment by yuhaizr** [comment]
> 
> 
> > > You can try the following steps:
> > > ```
> > > 1. rm -rf /apisix-path/deps
> > > 
> > > 2. Recompile and install `luarocks` and specify the `luajit` header file directory, for example: `./configure --with-lua-include=/openresty-path/luajit/include/luajit-2.1`
> > > 
> > > 3. Enter the apisix directory and re-execute `make deps` to install dependencies
> > > ```
> > 
> > 
> > 我安装你的方法做了之后，上面的问题解决了，然后又出现了新的问题：
> > ./bin/apisix init
> > /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
> > /usr/local/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so':
> > /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list
> > stack traceback:
> > [C]: at 0x00452d70
> > [C]: in function 'require'
> > /usr/local/apisix-2.7/deps/share/lua/5.1/ssl.lua:8: in main chunk
> > [C]: in function 'require'
> > /usr/local/apisix-2.7/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
> > [C]: in function 'require'
> > ./apisix/cli/etcd.lua:24: in main chunk
> > [C]: in function 'require'
> > ./apisix/cli/ops.lua:18: in main chunk
> > [C]: in function 'require'
> > ./apisix/cli/apisix.lua:32: in main chunk
> > [C]: at 0x00404c80
> > make: *** [init] 错误 1
> 
> What about removing the ./deps`directory and re-execute`make deps`?

我就算在删除  deps 目录，之后安装出现这个问题

**Comment by spacewander** [comment]
What's the output of `nginx -V` and `ldd /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so`?

**Comment by yuhaizr** [comment]
> ldd /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so

我重新安装了 openrestry   使用  --with-openssl=/usr/local/openssl1.1.1k  之后可以了。
但是start 的时候遇到新的问题

./bin/apisix start
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
nginx: [error] init_by_lua error: /usr/local/apisix-2.7/apisix/init.lua:65: pcre jit stack allocation failed
stack traceback:
        [C]: in function 'error'
        /usr/local/openresty/lualib/ngx/re.lua:311: in function 'opt'
        /usr/local/apisix-2.7/apisix/init.lua:65: in function 'http_init'
        init_by_lua:9: in main chunk

**Comment by tokers** [comment]
> > ldd /usr/local/apisix-2.7/deps/lib/lua/5.1/ssl.so
> 
> 我重新安装了 openrestry 使用 --with-openssl=/usr/local/openssl1.1.1k 之后可以了。
> 但是start 的时候遇到新的问题
> 
> ./bin/apisix start
> /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
> nginx: [error] init_by_lua error: /usr/local/apisix-2.7/apisix/init.lua:65: pcre jit stack allocation failed
> stack traceback:
> [C]: in function 'error'
> /usr/local/openresty/lualib/ngx/re.lua:311: in function 'opt'
> /usr/local/apisix-2.7/apisix/init.lua:65: in function 'http_init'
> init_by_lua:9: in main chunk
> 
> 之后又重新安装了openrestry 使用了 --with-pcre-jit 之后就正常了。
> 我们可以在哪里看到需要的所有的依赖有哪些嘛？

Did you use the build script https://raw.githubusercontent.com/api7/apisix-build-tools/master/build-apisix-openresty.sh ?
