### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by hcolde** [apache/apisix#4601]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):Darwin coldes-MacBook-Air.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty:1.19.3.1-alpine-fat
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.9
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

I have 2 user information:

```json
[
    {
        "client_id":"a",
        "client_secret":"aaa"
    },
    {
        "client_id":"b",
        "client_secret":"bbb"
    }
]
```

how to add to openid-connetor?

I only know how to add one,like this:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri":"/get",
    "plugins":{
        "proxy-rewrite":{
            "scheme":"https"
        },
        "openid-connect":{
            "client_id":"a",
            "client_secret":"aaa",
            ...
        }
    },
    "upstream":{
        "type":"roundrobin",
        "nodes":{
            "httpbin.org:443":1
        }
    }
}'
```

**Comment by shuaijinchao** [comment]
@hcolde hello, `openid-connect` plugin currently does not support adding multiple user information to a plugin policy. Welcome to submit a PR for improvement.
