### ISSUE TITLE
request help: Problem forwarding

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#4609]
### Issue description

I have a domain name: aaa.com wants to proxy directly to bbb.com, by developing the plugin but aaa.com doesn t need to configure information about upstream。

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
You can configure an upstream with "bbb.com".
```
{
    "type": "roundrobin",
    "nodes": {
        "bbb.com:80": 1
    }
}

```

It's impossible to do that without upstream.

**Comment by kongjun01** [comment]
thanks, It is resolved. This is my code for the plugin.

```
function _M.rewrite(conf, ctx)

    local up_conf = {
        type = "roundrobin",
        nodes = {{ host = 'www.baidu.com', weight = 100 }},
        scheme = 'https',
        hash_on = "vars",
        timeout = {
            connect = 15,
            send = 15,
            read = 15
        }
    }

    local route_val = { uri = "/*", host = { 'hao.huhuas.cn' }, id = "reverse_baidu", upstream = up_conf }
    ctx.matched_route = { has_domain = true, value = route_val, modifiedIndex = 'reverse_baidu' }

end`
