### ISSUE TITLE
bug: response header  has duplicate

### ISSUE THREAD

**Issue by philzhangrui** [apache/apisix#4611]
### Issue description The header returned by response has duplicate

![微信图片_20210715194502](https://user-images.githubusercontent.com/7685507/125782813-9061b3bc-b465-4e85-b08f-e2a098add6e0.png)

**Comment by tzssangglass** [comment]
please give a minimum reproduction use case

**Comment by spacewander** [comment]
It is expected. We haven't deduplicated the Apisix-Plugins header yet. See https://github.com/apache/apisix/blob/6af1b69607bfb26bb6b61ec3b8307e2425e1f1c3/t/debug/debug-mode.t#L239

**Comment by spacewander** [comment]
We will refactor the debug feature in the upcoming versions. Things may change at that time.
