### ISSUE TITLE
 Is there any plan to support routing by judging whether the header exists?

### ISSUE THREAD

**Issue by jamesislebron** [apache/apisix#4614]
### Issue description
比如有同样两个host+path+method都一致的路由，想要通过header是否存在，来决定具体走到哪个路由上面，请问目前是否有相关方案支持？

**Comment by tzssangglass** [comment]
hi @jamesislebron , take a look at https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#how-to-filter-route-by-nginx-builtin-variable.

here is an simple example:
```
$ curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/index.html",
    "vars": [
        ["http_version", "==", "1.0.0"]
    ],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}'
```

This route will require the request header `version` equal `1.0.0`.

**Comment by jamesislebron** [comment]
> hi @jamesislebron , take a look at https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#how-to-filter-route-by-nginx-builtin-variable.
> 
> here is an simple example:
> 
> ```
> $ curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
> {
>     "uri": "/index.html",
>     "vars": [
>         ["http_version", "==", "1.0.0"]
>     ],
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "39.97.63.215:80": 1
>         }
>     }
> }'
> ```
> 
> This route will require the request header `version` equal `1.0.0`.

**Comment by jamesislebron** [comment]
@tzssangglass 首先感谢你这么快速的解答，但是我的问题和你给出的范例可能略有不同，让我完整的描述一下吧：
1、你提到的这个用法我是了解的，但我的需求不是通过header的value判断是否路由，而是想通过某个header是否存在来判断
2、翻看了一下文档和源码，目前似乎是没有["http_version", "exist"]这种写法的
3、然后看到这里通过nginx builtin var判断支持正则，尝试通过增加规则["http_version", "～=", "[z-aA-Z0-9]{1,}"]来曲线救国，理论上应该是没问题的，但是发现出现bug，当不传header version的时候，http_version的值是nil，理论上正则是过不了的，但是这里还是返回了1，这里应该是个bug：
![image](https://user-images.githubusercontent.com/20439714/126025247-5785ef51-0df2-4a1a-bc8a-b8e89240f57d.png)
4、所以回到了这个issue的问题，是否考虑支持判断header是否存在这一特性。

**Comment by tzssangglass** [comment]
I think what you mean is `has` operator, you can also take a look at : https://github.com/api7/lua-resty-expr#operator-list

simple example:

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "vars": [
        ["http_version", "in", ["1.0.0"]]
    ],
    "upstream": {
       "nodes": {
           "127.0.0.1:1980": 1
       },
       "type": "roundrobin"
    }
}'
```

this request will be caught by the route

```
curl -H 'version: 1.0.0' 127.0.0.1:9080/hello
```

this request will not be caught by the route

```
curl -H 'version: 1.0.1' 127.0.0.1:9080/hello
```

**Comment by jamesislebron** [comment]
并不是哈，我希望的效果是：
this request will be caught by the route
`curl -H 'version: 1.0.0' 127.0.0.1:9080/hello`
while this request will not be caught by the route
`curl  127.0.0.1:9080/hello`

**Comment by jamesislebron** [comment]
> @tzssangglass 首先感谢你这么快速的解答，但是我的问题和你给出的范例可能略有不同，让我完整的描述一下吧：
> 1、你提到的这个用法我是了解的，但我的需求不是通过header的value判断是否路由，而是想通过某个header是否存在来判断
> 2、翻看了一下文档和源码，目前似乎是没有["http_version", "exist"]这种写法的
> 3、然后看到这里通过nginx builtin var判断支持正则，尝试通过增加规则["http_version", "～=", "[z-aA-Z0-9]{1,}"]来曲线救国，理论上应该是没问题的，但是发现出现bug，当不传header version的时候，http_version的值是nil，理论上正则是过不了的，但是这里还是返回了1，这里应该是个bug：
> ![image](https://user-images.githubusercontent.com/20439714/126025247-5785ef51-0df2-4a1a-bc8a-b8e89240f57d.png)
> 4、所以回到了这个issue的问题，是否考虑支持判断header是否存在这一特性。

这里的第三点，我给出的信息有误，添加的规则应该是：

`["http_version", "~~", "[z-aA-Z0-9]{1,}"]`

**Comment by tokers** [comment]
@jamesislebron Try JSON `null`.
```
"vars": [
        ["http_version", "!", "equal", null]
    ]
```

**Comment by jamesislebron** [comment]
> @jamesislebron Try JSON `null`.
> 
> ```
> "vars": [
>         ["http_version", "!", "equal", null]
>     ]
> ```

@tokers It seems that apisix can not support `null` param, while the `"!", "equal"` oprator may should be `~=` ?

**Comment by tokers** [comment]
> > @jamesislebron Try JSON `null`.
> > ```
> > "vars": [
> >         ["http_version", "!", "equal", null]
> >     ]
> > ```
> 
> @tokers It seems that apisix can not support `null` param now.
> Meanwhile the `"!", "equal"` oprator may should be `~=` ? There is no op like `equal` in `https://github.com/api7/lua-resty-expr/blob/main/lib/resty/expr/v1.lua#L64-L139`.

Try look this one for details https://github.com/api7/lua-resty-expr.

**Comment by tzssangglass** [comment]
@jamesislebron Please update apisix to the latest version, `make deps` to introduce the latest dependencies, and test 

```
"vars": [
    ["http_version", "~~", "[z-aA-Z0-9]{1,}"]
 ]
```

**Comment by jamesislebron** [comment]
> @jamesislebron Please update apisix to the latest version, `make deps` to introduce the latest dependencies, and test
> 
> ```
> "vars": [
>     ["http_version", "~~", "[z-aA-Z0-9]{1,}"]
>  ]
> ```

I Have already test ok by this way.
But I it may be awesome to add a op like `exits` in https://github.com/api7/lua-resty-expr . 
Thanks a lot for your reply .
