### ISSUE TITLE
please consider provide binary distrobution on linux and  win platform 

### ISSUE THREAD

**Issue by yudar1024** [apache/apisix#4617]
like nginx or openresty , can you provide linux and win binary?

**Comment by spacewander** [comment]
We have rpm for it: https://github.com/apache/apisix/releases/tag/2.7

**Comment by yudar1024** [comment]
> 
> 
> We have rpm for it: https://github.com/apache/apisix/releases/tag/2.7

still not convenient, eg ubuntu and opensuse :), if it can distrobute like etcd, just a binary and pre-build, it is perfect. and i didn't find the dev guide. can you doc the dev env setup guide? i think that's very helpful.

**Comment by spacewander** [comment]
> still not convenient, eg ubuntu and opensuse

The package code is open source: https://github.com/api7/apisix-build-tools#example
We use fpm to build the package, so it is easy to create a deb one.
PR is welcome!

> i didn't find the dev guide. can you doc the dev env setup guide

Better to open a new issue for another question.

Do you mean building from source? You can refer to these docs:
https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md
https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-source-release-package

Or you can set up the dev env via mount the src code to a docker container.
