### ISSUE TITLE
bug: regex rules return true when value is `nil` and pattern is `[z-aA-Z0-9]{1,}` 

### ISSUE THREAD

**Issue by jamesislebron** [apache/apisix#4619]
### Issue description

regex rules return true when value is `nil` and pattern is `[z-aA-Z0-9]{1,}` 

### Environment

* apisix version (cmd: `apisix version`): 2.1
* OS (cmd: `uname -a`): centos 7
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  openresty/1.17.8.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): 2.3.0

### Minimal test code / Steps to reproduce the issue

1. I added a rules for a route like this: 

```
["http_version", "~~", "[z-aA-Z0-9]{1,}"]
```

2. I found that this request would  be caught by the route

```
curl 127.0.0.1:9080/hello
```

3. I tried to read source code and add log in it, found that there meybe a bug in `deps/share/lua/5.1/resty/expr/v1.lua` line 93 - 99 :
```
    ["~~"] = function (l_v, r_v)
        local from = re_find(l_v, r_v, "jo")
        core.log.warn("l_v: ", l_v, " r_v" ,r_v, "re_find res: ", from)
        if from then
            return true
        end
        return false
    end,
```
### What's the actual result? 
when I use the request without header version, the l_v's value is nil , the r_v‘s value is what I set: `[z-aA-Z0-9]{1,}`
the op is regex op `~~`, but ngx.re_find function return `true`, is this a bug ?
logs:
![image](https://user-images.githubusercontent.com/20439714/126034496-d5d5e7f7-a38a-4cc9-a913-54c629b1d8fd.png)

### What's the expected:
When I use the reqesut without the `version` header, the `compare_val` func should not return true, and it should not be caught by this route.

**Comment by tzssangglass** [comment]
Please update apisix version to 2.7
The code you pointed out has been fixed in the latest version
Please refer to 
https://github.com/api7/lua-resty-expr/blob/48925f4b9afa261d48317dc00834be1709d5dd83/lib/resty/expr/v1.lua#L115-L125

**Comment by jamesislebron** [comment]
> Please update apisix version to 2.7
> The code you pointed out has been fixed in the latest version
> Please refer to
> https://github.com/api7/lua-resty-expr/blob/48925f4b9afa261d48317dc00834be1709d5dd83/lib/resty/expr/v1.lua#L115-L125

 @tzssangglass 
 wow，已经看到，非常感谢🙏
