### ISSUE TITLE
request help: 请问当创建了一个grpc的路由，auth-key这种插件还可以用吗，apisix支持http2的头的读写吗

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4620]

**Comment by tokers** [comment]
@StretchV Sure, HTTP/2 was supported by APISIX.

**Comment by StretchV** [comment]
@tokers proxy-mirror这个插件我加到代理grpc的路由上,但是我没有在收集端获取到镜像流量,但是普通的路由是可以收集到的,请问proxy-mirror这个插件不支持grpc路由的镜像拷贝吗

**Comment by StretchV** [comment]
@tokers proxy-mirror这个插件我加到代理grpc的路由上,但是我没有在收集端获取到镜像流量,但是普通的路由是可以收集到的,请问proxy-mirror这个插件不支持grpc路由的镜像拷贝吗

**Comment by StretchV** [comment]
如果在grpc路由开启auth-key插件,客户端发送的时候是往metadata中加信息就可以了吗

**Comment by tokers** [comment]
> @tokers proxy-mirror这个插件我加到代理grpc的路由上,但是我没有在收集端获取到镜像流量,但是普通的路由是可以收集到的,请问proxy-mirror这个插件不支持grpc路由的镜像拷贝吗

Sorry for my carelessness, proxy-mirror currently cannot be used in route which upstream scheme is grpc.

**Comment by tokers** [comment]
> metadata



> 如果在grpc路由开启auth-key插件,客户端发送的时候是往metadata中加信息就可以了吗

Not sure which gRPC SDK you use, for grpc-go, you can use [SetHeader](https://pkg.go.dev/google.golang.org/grpc#SetHeader).

**Comment by StretchV** [comment]
@tokers 请问，这个函数貌似只能服务端调用吧，客户端调用的话会报 failed to fetch the stream from the context context.Background

**Comment by StretchV** [comment]
另外请问grpc的流量镜像目前apisix有实现的方法插件吗，如果没有的话之后是否会考虑制作呢

**Comment by tokers** [comment]
> @tokers 请问，这个函数貌似只能服务端调用吧，客户端调用的话会报 failed to fetch the stream from the context context.Background

There are some other similar methods, you may try to check out the corresponding documents.

**Comment by tokers** [comment]
@StretchV By the way, please use English in public channels.

**Comment by StretchV** [comment]
Excuse me,is there a plug-in for apisix to implement the traffic image of grpc? If not, will it be considered later?

**Comment by tzssangglass** [comment]
> Excuse me,is there a plug-in for apisix to implement the traffic image of grpc? If not, will it be considered later?

please submit another issue, example of title: feature: support for grpc traffic mirroring

**Comment by StretchV** [comment]
> > Excuse me,is there a plug-in for apisix to implement the traffic image of grpc? If not, will it be considered later?
> 
> please submit another issue, example of title: feature: support for grpc traffic mirroring

ok

**Comment by StretchV** [comment]
> @StretchV By the way, please use English in public channels.

I try to use the 'metadata.AppendToOutgoingContext' method on the client side,eg: "metadata.AppendToOutgoingContext(ctx,"apikey","auth-one")" and I can get the value in metadata through the metadata.FromIncomingContext method on the server side. However, after the "auth-key" plug-in is opened on this grpc route, I will still report a 401 error.I want to know how to do authentication through gateway on grpc route

**Comment by StretchV** [comment]
> > metadata
> 
> > 如果在grpc路由开启auth-key插件,客户端发送的时候是往metadata中加信息就可以了吗
> 
> Not sure which gRPC SDK you are using, for grpc-go, you can use [SetHeader](https://pkg.go.dev/google.golang.org/grpc#SetHeader).

I have never figured out how to use this method on the client side

**Comment by StretchV** [comment]
哦,问题解决了,是因为我的消费者是在apisix-dashboad中创建的,但是不知道为什么看着是有数据的但是没有生效,我通过adminapi重新生成了一个消费者后来重试就可以了,
