### ISSUE TITLE
bug: traffic-split plugin

### ISSUE THREAD

**Issue by htwdjqr** [apache/apisix#4623]
### Issue description
启用 traffic-split 做蓝绿发布时，无法正确的转发至规则匹配节点

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):Linux apisix 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):\/usr/local/bin/luarocks 3.4.0

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.配置 traffic-split 插件
{
  "disable": false,
  "rules": [
    {
      "match": [
        {
          "vars": [
            [
              "http_release",
              "==",
              "new_release"
            ]
          ]
        }
      ],
      "weighted_upstreams": [
        {
          "upstream": {
            "name": "upstream_A",
            "nodes": {
              "172.18.50.234:10002": 10
            },
            "type": "roundrobin"
          }
        }
      ]
    }
  ]
}
2.使用postman发起请求，并且设置请求头release=new_release，使其命中配置规则。

### What's the actual result? (including assertion message & call stack if applicable)
一部分请求会转发到172.18.50.234:10002节点中，另外一部分请求会转发到路由配置的上游节点中。

### What's the expected result?
命中规则的所有请求都会转发至172.18.50.234:10002节点中。

**Comment by spacewander** [comment]
Can't be reproduced on my side.

The route:
```
{
    "uri": "/hello",
    "plugins": {
        "traffic-split": {
            "disable": false,
            "rules": [
                {
                    "match": [
                        {
                            "vars": [
                                [
                                    "http_release",
                                    "==",
                                    "new_release"
                                ]
                            ]
                        }
                    ],
                    "weighted_upstreams": [
                        {
                            "upstream": {
                                "name": "upstream_A",
                                "nodes": {
                                    "127.0.0.1:1980": 10
                                },
                                "type": "roundrobin"
                            }
                        }
                    ]
                }
            ]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1979": 1
        }
    }
}
```

The wrk script:
```
wrk.headers["release"] = "new_release"
```

Set up Nginx to listen 1980 but not 1979.

Run curl & wrk:
```
 ￥ curl http://127.0.0.1:9080/hello
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
 incubator-apisix (pbp) 0
 ￥ curl http://127.0.0.1:9080/hello -H "release: new_release"
OK%
 incubator-apisix (pbp) 0
 ￥ wrk http://127.0.0.1:9080/hello -s ~/wrk/hdr.lua -d 60
Running 1m test @ http://127.0.0.1:9080/hello
  2 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.58ms  160.80us   6.11ms   79.31%
    Req/Sec     3.18k   128.69     3.47k    64.67%
  379688 requests in 1.00m, 58.64MB read
Requests/sec:   6328.03
Transfer/sec:      0.98MB
```

**Comment by htwdjqr** [comment]
现在测试更离谱，所有命中规则的请求都直接转发到路由配置的上游节点了，而不是规则命中的节点。

我的配置如下：

```json
{
  "disable": false,
  "rules": [
    {
      "match": [
        {
          "vars": [
            [
              "http_release",
              "==",
              "new_release"
            ]
          ]
        }
      ],
      "weighted_upstreams": [
        {
          "upstream": {
            "name": "upstream_A",
            "nodes": {
              "172.18.50.234:10002": 10
            },
            "type": "roundrobin"
          }
        }
      ]
    }
  ]
}
```

请求：curl http://127.0.0.1:9080/uc/demo -H "release: new_release"

这个问题有啥排查思路呢？

**Comment by htwdjqr** [comment]
找到traffic-split失效的原因了，是因为之前按照https://apisix.apache.org/docs/apisix/plugins/skywalking文档，在config.yaml文件中配置skywalking插件：
```yaml
plugins:
  - skywalking
```
我现在在config.yaml的plugins下面加上traffic-split，插件就生效了。

这个是因为我在config.yaml中配置了plugins，从而导致config-default.yaml中的所有plugins都被覆盖了吗？麻烦解答下疑惑吧

**Comment by tokers** [comment]
> 找到traffic-split失效的原因了，是因为之前按照[https://apisix.apache.org/docs/apisix/plugins/skywalking文档，在config.yaml文件中配置skywalking插件：](https://apisix.apache.org/docs/apisix/plugins/skywalking%E6%96%87%E6%A1%A3%EF%BC%8C%E5%9C%A8config.yaml%E6%96%87%E4%BB%B6%E4%B8%AD%E9%85%8D%E7%BD%AEskywalking%E6%8F%92%E4%BB%B6%EF%BC%9A)
> 
> ```yaml
> plugins:
>   - skywalking
> ```
> 
> 我现在在config.yaml的plugins下面加上traffic-split，插件就生效了。
> 
> 这个是因为我在config.yaml中配置了plugins，从而导致config-default.yaml中的所有plugins都被覆盖了吗？麻烦解答下疑惑吧

Yep, the same configuration item in `config.yaml` will override the same one in `config-default.yaml`.

**Comment by htwdjqr** [comment]
> > 找到traffic-split失效的原因了，是因为之前按照[https://apisix.apache.org/docs/apisix/plugins/skywalking文档，在config.yaml文件中配置skywalking插件：](https://apisix.apache.org/docs/apisix/plugins/skywalking%E6%96%87%E6%A1%A3%EF%BC%8C%E5%9C%A8config.yaml%E6%96%87%E4%BB%B6%E4%B8%AD%E9%85%8D%E7%BD%AEskywalking%E6%8F%92%E4%BB%B6%EF%BC%9A)
> > ```yaml
> > plugins:
> >   - skywalking
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我现在在config.yaml的plugins下面加上traffic-split，插件就生效了。
> > 这个是因为我在config.yaml中配置了plugins，从而导致config-default.yaml中的所有plugins都被覆盖了吗？麻烦解答下疑惑吧
> 
> Yep, the same configuration item in `config.yaml` will override the same one in `config-default.yaml`.
