### ISSUE TITLE
please doc dev env setup guide

### ISSUE THREAD

**Issue by yudar1024** [apache/apisix#4625]
# Improve Docs

Hi apisix team, I try to dev some function for test extend apisix, but I didn't find any dev env setup guide , this is not mean build with source . it means how to setup dev environment, like run lua test and debug the lua in realtime. can you consider to doc this content?

**Comment by spacewander** [comment]
There are some online resources about OpenResty:
Testing:
https://github.com/openresty/programming-openresty/blob/master/testing/introduction.adoc (English)
https://github.com/iresty/programming-openresty-zh (The Chinese translation)

Misc:
https://github.com/moonbingbing/openresty-best-practices (Chinese)
