### ISSUE TITLE
优化Apisix源码编译方式安装脚本

### ISSUE THREAD

**Issue by TravelEngineers** [apache/apisix#4630]
目前国内一般服务器都有较多网络限制，在未使用k8s或者docker的开发团队，Apisix的源码编译方式需要用脚本去不停的下载外部依赖。这样对于纯内网环境，Apisix在选型调研阶段就会被排除。
类似Nginx或者Openrestry，使用源码编译方式安装时，可以无需依赖外部网络。对于需要不停下载外部依赖的，基本上都直接考虑docker了，很少有人在能使用外部网络的情况下，再去用yum进行安装。

**Comment by spacewander** [comment]
We have provided rpm and docker installation: https://apisix.apache.org/zh/docs/apisix/how-to-build/#2-%E5%AE%89%E8%A3%85-apache-apisix.

Build from source is mostly only for the development.
