### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by ArmitageW** [apache/apisix#4631]
### Issue description
Can consumers be bound to a specified route? I created two JWT consumers, but I hope that the router can only use one of them, not both.
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by nic-chen** [comment]
@ArmitageW  maybe you could use plugin `consumer-restriction`: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md

**Comment by ArmitageW** [comment]
ths
