### ISSUE TITLE
bug: When the service kv does not exist, the fetch timer of consul_kv will fetch service data frantically, resulting in 100% CPU

### ISSUE THREAD

**Issue by forcemain** [apache/apisix#4632]
当服务kv不存在时consul_kv的fetch timer会疯狂获取服务数据导致CPU 100%

2021/07/20 07:11:55 [error] 42#42: *193170 [lua] consul_kv.lua:329: connect consul: http://10.242.154.205:8500/v1/kv/ by key: /kv/apisix-service-upstreams, got result: null, with error: timeout, context: ngx.timer

目测是因为_M.connect异常后直接再次跳转到:: ERR ::再次尝试_M.connect~ 死循环了

**Comment by spacewander** [comment]
What about using exponential backoff with retry instead of retrying immediately?
We can try after 1,4,16,64,256,256,... seconds.

**Comment by yongboy** [comment]
This is a bug now :))
I would submit a PR  later to fix it.

And, if you want to avoid the bug at the moment, you should insert some test data into `/apisix-service-upstreams` key space.

**Comment by forcemain** [comment]
@yongboy yeah, i see

**Comment by forcemain** [comment]
@sbritocorral yeah,  periodic increase  maybe better

**Comment by tokers** [comment]
Agree, currently, the next timer will be created at once.

**Comment by Zheaoli** [comment]
@yongboy Is there anything update?

**Comment by spacewander** [comment]
@Zheaoli 
I am working on it.
