### ISSUE TITLE
request help:上游服务中的目标节点设置为 k8s 的 servicename 时指定的负载均衡算法会失效吗？

### ISSUE THREAD

**Issue by edisonwd** [apache/apisix#4634]
### Issue description
![image](https://user-images.githubusercontent.com/25941671/126293333-1376b96b-24b4-4c02-855c-2d2b10789f30.png)

默认情况下 k8s 通过 servicename 找到后端对应的podip ,再轮询选择一个podip，这样的话在 apisix 中指定的负载均衡算法还会生效吗？
### Environment

* apisix version (cmd: `apisix version`): 2.6
* apisix-dashboard version, if have: 2.6

**Comment by tokers** [comment]
@edisonwd As you just configure the FQDN or Service ClusterIP, there is only one node in the APISIX Upstream, so any load balancing algorithms are meaningless here.

**Comment by edisonwd** [comment]
如果要使用这里的负载均衡算法，目标节点写 podip 吗？有很多 pod ，重新调度后 podip 会发生变化，这里应该怎么指定目标节点？

**Comment by edisonwd** [comment]
> @edisonwd As you just configure the FQDN or Service ClusterIP, there is only one node in the APISIX Upstream, so any load balancing algorithms are meaningless here.
如果要使用这里的负载均衡算法，目标节点写 podip 吗？有很多 pod ，重新调度后 podip 会发生变化，这里应该怎么指定目标节点？

**Comment by tokers** [comment]
> > @edisonwd As you just configure the FQDN or Service ClusterIP, there is only one node in the APISIX Upstream, so any load balancing algorithms are meaningless here.
> > 如果要使用这里的负载均衡算法，目标节点写 podip 吗？有很多 pod ，重新调度后 podip 会发生变化，这里应该怎么指定目标节点？

Welcome to use Apache APISIX Ingress Controller https://github.com/apache/apisix-ingress-controller. It's not easy to adjust the Kubernetes Service Discovery just by APISIX.

**Comment by edisonwd** [comment]
> > > @edisonwd As you just configure the FQDN or Service ClusterIP, there is only one node in the APISIX Upstream, so any load balancing algorithms are meaningless here.
> > > 如果要使用这里的负载均衡算法，目标节点写 podip 吗？有很多 pod ，重新调度后 podip 会发生变化，这里应该怎么指定目标节点？
> 
> Welcome to use Apache APISIX Ingress Controller https://github.com/apache/apisix-ingress-controller. It's not easy to adjust the Kubernetes Service Discovery just by APISIX.

如果配置ingress 的域名，它使用是 ingress 的负载均衡算法，这里的负载均衡依然不会生效吧。这里只有在配置多个目标节点的情况下才会使用这里的负载均衡算法对吧？

**Comment by tzssangglass** [comment]
> 这里只有在配置多个目标节点的情况下才会使用这里的负载均衡算法对吧？

yes.

**Comment by sandy420** [comment]
我配置了多少上游节点,现在upstream负载不均衡,有人知道是哪里的问题吗?这是每个节点的被分配的请求监控
![lALPDgQ9y7MgOv7Mus0CdA_628_186](https://user-images.githubusercontent.com/10955441/134310089-922805a0-5562-45b4-8162-b2eacfb94c15.png)
