### ISSUE TITLE
request help:  How to achieve traffic image in grpc routing

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4635]

**Comment by tokers** [comment]
@StretchV Could you explain the `traffic image` more elaborate?

**Comment by StretchV** [comment]
proxy-mirror this plugin

**Comment by tzssangglass** [comment]
You mean proxy-mirror supports the grpc protocol, right?

**Comment by StretchV** [comment]
> You mean proxy-mirror supports the grpc protocol, right?

yes,how to  do that?
