### ISSUE TITLE
bug: install apisix from source code

### ISSUE THREAD

**Issue by BlackGhostKing** [apache/apisix#4636]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):  2.7
* OS (cmd: `uname -a`): ubuntu16.04
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

root@ubuntu:/home/adin/bin/apisix/apisix-2.7# make deps
mkdir -p ~/.luarocks
luarocks config variables.OPENSSL_LIBDIR /usr/local/openresty/openssl/lib
Wrote
	variables.OPENSSL_LIBDIR = "/usr/local/openresty/openssl/lib"
to
	/root/.luarocks/config-5.1.lua
luarocks config variables.OPENSSL_INCDIR /usr/local/openresty/openssl/include
Wrote
	variables.OPENSSL_INCDIR = "/usr/local/openresty/openssl/include"
to
	/root/.luarocks/config-5.1.lua
luarocks install rockspec/apisix-master-0.rockspec --tree=deps --only-deps --local 
Missing dependencies for apisix master-0:
   luasec 0.9-1 (not installed)
   lua-resty-consul 0.3-2 (not installed)
   penlight 1.9.2-1 (not installed)
   ext-plugin-proto 0.1.1 (not installed)

apisix master-0 depends on lua-resty-ctxdump 0.1-0 (0.1-0 installed)
apisix master-0 depends on lua-resty-dns-client 5.2.0 (5.2.0-1 installed)
apisix master-0 depends on lua-resty-template 2.0 (2.0-1 installed)
apisix master-0 depends on lua-resty-etcd 1.5.0 (1.5.0-0 installed)
apisix master-0 depends on lua-resty-balancer 0.02rc5 (0.02rc5-0 installed)
apisix master-0 depends on lua-resty-ngxvar 0.5.2 (0.5.2-0 installed)
apisix master-0 depends on lua-resty-jit-uuid 0.0.7 (0.0.7-2 installed)
apisix master-0 depends on lua-resty-healthcheck-api7 2.2.0 (2.2.0-0 installed)
apisix master-0 depends on lua-resty-jwt 0.2.0 (0.2.0-0 installed)
apisix master-0 depends on lua-resty-hmac-ffi 0.05 (0.05-0 installed)
apisix master-0 depends on lua-resty-cookie 0.1.0 (0.1.0-1 installed)
apisix master-0 depends on lua-resty-session 2.24 (2.24-1 installed)
apisix master-0 depends on opentracing-openresty 0.1 (0.1-0 installed)
apisix master-0 depends on lua-resty-radixtree 2.8.0 (2.8.0-0 installed)
apisix master-0 depends on lua-protobuf 0.3.2 (0.3.2-0 installed)
apisix master-0 depends on lua-resty-openidc 1.7.2-1 (1.7.2-1 installed)
apisix master-0 depends on luafilesystem 1.7.0-2 (1.7.0-2 installed)
apisix master-0 depends on lua-tinyyaml 1.0 (1.0-0 installed)
apisix master-0 depends on nginx-lua-prometheus 0.20210206 (0.20210206-1 installed)
apisix master-0 depends on jsonschema 0.9.5 (0.9.5-0 installed)
apisix master-0 depends on lua-resty-ipmatcher 0.6 (0.6-0 installed)
apisix master-0 depends on lua-resty-kafka 0.07 (0.07-0 installed)
apisix master-0 depends on lua-resty-logger-socket 2.0-0 (2.0-0 installed)
apisix master-0 depends on skywalking-nginx-lua 0.4-1 (0.4-1 installed)
apisix master-0 depends on base64 1.5-2 (1.5-2 installed)
apisix master-0 depends on binaryheap 0.4 (0.4-1 installed)
apisix master-0 depends on dkjson 2.5-2 (2.5-2 installed)
apisix master-0 depends on resty-redis-cluster 1.02-4 (1.02-4 installed)
apisix master-0 depends on lua-resty-expr 1.3.0 (1.3.0-0 installed)
apisix master-0 depends on graphql 0.0.2 (0.0.2-1 installed)
apisix master-0 depends on argparse 0.7.1-1 (0.7.1-1 installed)
apisix master-0 depends on luasocket 3.0rc1-2 (3.0rc1-2 installed)
apisix master-0 depends on luasec 0.9-1 (not installed)
Installing https://luarocks.org/luasec-0.9-1.src.rock

Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
Makefile:80: recipe for target 'deps' failed
make: *** [deps] Error 1

**Comment by tokers** [comment]
@BlackGhostKing Try to use [this script](https://github.com/apache/apisix/blob/master/utils/linux-install-luarocks.sh) to re-install your luarocks command line tool.
