### ISSUE TITLE
wrong description in certificate.md

### ISSUE THREAD

**Issue by mytsing520** [apache/apisix#4639]
File:
apisix/docs/zh/latest/certificate.md

Wrong Description:
一个 SSL 证书的域名也可能包含泛域名，如*.test.com，它代表所有以test.com结尾的域名都可以使用该证书。 比如*.test.com，可以匹配 www.test.com、mail.test.com甚至a.b.test.com。

Modification Suggestion:
remove "甚至a.b.test.com".

**Comment by spacewander** [comment]
PR is welcome!

**Comment by RhnSharma** [comment]
I would like to take this one. Is it up for grabs?
