### ISSUE TITLE
request help:  lua redis problem

### ISSUE THREAD

**Issue by philzhangrui** [apache/apisix#4642]
### Issue description

I wrote a plug-in to imitate limit Conn, mainly to replace the shared memory with redis. I encountered some problems. 1. The connection problem of redis 2. Living without con, redis without link,
@membphis    

code
[file.zip](https://github.com/apache/apisix/files/6853488/file.zip)

Please give me some guidance

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@philzhangrui Please just paste the code instead of uploading a file, it's not friendly for mobile users.

**Comment by tzssangglass** [comment]
> 1. The connection problem of redis 2. Living without con, redis without link

you should describe these two issues in detail.
for example, what is the problem performance and what do you expect.

**Comment by philzhangrui** [comment]
> > 1. The connection problem of redis 2. Living without con, redis without link
> 
> you should describe these two issues in detail.
> for example, what is the problem performance and what do you expect.

Well, to imitate limit Conn, you need to execute the redis command twice. I want to know if you have similar examples. I can imitate them

**Comment by philzhangrui** [comment]
In the log phase, sockets are not allowed

**Comment by tokers** [comment]
> In the log phase, sockets are not allowed

Spawn a timer to do that in the log phase.
