### ISSUE TITLE
request help: can apisix be prioritized to upstream in the same area?

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4643]
### Issue description
We currently have three AZ, the three nodes of the Apisix cluster are deployed in these three AZ, and our upstream services are also deployed in these three AZ, and how can Apisix prioritize to the same AZ's upstream service?

**Comment by spacewander** [comment]
You can write your own balancer with AZ in the metadata: https://github.com/apache/apisix/pull/4605

**Comment by zuiyangqingzhou** [comment]
Does the load balancing algorithm EWMA can achieve the same effect?

**Comment by tzssangglass** [comment]
> Does the load balancing algorithm EWMA can achieve the same effect?

no.

**Comment by zuiyangqingzhou** [comment]
Can you explain why?

My needs is that the APISIX is prioritized to reach the low latency upstream,  apisix and upstream in the same AZ will have a lower delay than if they are not in the same AZ.

 The EWMA algorithm preferentially forwards the packets to the nodes with lower latency

Is there something wrong with my understanding？ @tzssangglass  @spacewander

**Comment by spacewander** [comment]
EWMA prefers but does not guarantee to choose the node with the lowest latency. There is some random stuff inside of it.

**Comment by zuiyangqingzhou** [comment]
I see. Thanks for your patience  @spacewander
