### ISSUE TITLE
request help: Excuse me, can we track the grpc traffic in Intranet by using apisix?

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#4644]

**Comment by tzssangglass** [comment]
what `in Intranet` mean, please describe the problem in detail, this question is too vague.

**Comment by StretchV** [comment]
就是追踪流量，因为内网都是通过grpc请求的，我不确定用apisix代理了所有内网的grpc服务端，有没有方法可以像sidecar那样做到流量打点然后追踪甚至拓扑出完整的流量图

**Comment by StretchV** [comment]
就是追踪流量，因为内网都是通过grpc请求的，我不确定用apisix代理了所有内网的grpc服务端，有没有方法可以像sidecar那样做到流量打点然后追踪甚至拓扑出完整的流量图

**Comment by tokers** [comment]
See the tracing-related plugins of APISIX, like SkyWalking and Zipkin.

**Comment by StretchV** [comment]
thankyou
