### ISSUE TITLE
Keycloak integration 

### ISSUE THREAD

**Issue by cgodefroy92** [apache/apisix#4645]
Hello, 
I re-open the case since it was closed because I believed I have found the solution.

The previous case is this one : https://github.com/apache/apisix/issues/4616

As a reminder, I would like to achieve the following architecture with APISIX and keycloak : 
![Capture d’écran 2021-07-20 à 17 17 30](https://user-images.githubusercontent.com/28594536/126538913-90725d5f-cd4f-4db4-bd6f-360eb1b9940b.png)

In fact the issue was not solved because forcing the Frontend URL in Keycloak to the kubernetes internal URL is a problem when we try to code a front-end. (The front-end url of the keycloak login page became http://10.0.0.11.181:8080 which is not a public url reachable from outside the kubernetes cluster)

The only solution is to use the public IP of keycloak in the iss field of the token and find a way to change the way APISIX and Keycloak talk together, in order to Keycloak accept the token whereas APISIX call the discovery end-point with the internal IP.

I have read some posts about the usage of keycloak behind a reverse proxy and it seems that we have to pass some headers to Keycloak (X-Forwarded-For and X-Forwarded-Proto):

https://stackoverflow.com/questions/47068266/keycloak-docker-behind-loadbalancer-with-https-fails

Regards
CG

**Comment by spacewander** [comment]
Look like it's a bug report of APISIX?

**Comment by cgodefroy92** [comment]
I am not sure, that's why i aks the question. Maybe the problem is well-known and we can configure something in APISIX to forward to keycloak the X-forwarded header...

**Comment by spacewander** [comment]
Do you mean adding these two headers to:
https://github.com/apache/apisix/blob/aa7ecfafd7fc036b555014418dedb7fd4be1815e/apisix/plugins/authz-keycloak.lua#L165

before sending requests to keycloak?
