### ISSUE TITLE
request help: 如何给网关绑定一个域名

### ISSUE THREAD

**Issue by monyuan** [apache/apisix#4647]
如何给网关绑定一个域名，未看到相关的文档。
用nginx反代到127.0.0.1:9080是否可行

**Comment by tokers** [comment]
It depends on your DNS management system to add some records for the APISIX cluster.

**Comment by monyuan** [comment]
@tokers 现在我已经将 a.com 域名解析到了安装apisix的服务器，apisix监听的是0.0.0.0:9080，我应该通过什么方法将其关联，谢谢！

**Comment by tokers** [comment]
@monyuan You don't give the context about your scenario, I don't know what is the meaning of "关联", I don't know which component will work together with APISIX. Please give elaborate information about your problem, thanks!

**Comment by monyuan** [comment]
@tokers 现在我已经安装了apisix，网关的地址为 ： 120.55.32.655:9080。  但是我不想使用IP访问这个网关，需要使用域名代替。

我已经将 a.com 解析到了此台服务器，如何 将 a.com 映射到  120.55.32.655:9080。

谢谢

**Comment by xshans** [comment]
直观的说，就是如何让apisix像nginx一样，可以一台服务器配置多个域名 ~~

**Comment by tzssangglass** [comment]
> 直观的说，就是如何让apisix像nginx一样，可以一台服务器配置多个域名 ~~

the `hosts` in route configure?
