### ISSUE TITLE
配置nacos 时提示 {"error_msg":"invalid configuration: property \"upstream\" validation failed: additional properties forbidden, found service_name"}

### ISSUE THREAD

**Issue by itw-hewb** [apache/apisix#4648]
使用的apisix 是 2.6的版本  碰到以下问题 如图
![image](https://user-images.githubusercontent.com/22789061/126582273-5f17b5de-586c-477b-8393-7882fa8e813d.png)

**Comment by spacewander** [comment]
The `Server` doesn't indicate it is APISIX 2.6.
Can you provide a plain text error report?

**Comment by itw-hewb** [comment]
> 在`Server`并不表示它是APISIX 2.6。
> 你能提供一个纯文本的错误报告吗？
这是我的版本apisix version
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
2.6
这是错误信息

curl http://127.0.0.1:9080/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X POST -i -d '
 {
     "uri": "/testNacos/*",
     "name": "testNacos",
     "upstream": {
         "service_name": "APISIX-NACOS",
         "type": "roundrobin",
         "discovery_type": "nacos"
    }
 }'
HTTP/1.1 400 Bad Request
Date: Thu, 22 Jul 2021 02:53:04 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Server: APISIX web server

{"error_msg":"invalid configuration: property \"upstream\" validation failed: additional properties forbidden, found service_name"}

**Comment by spacewander** [comment]
Please ensure you are using APISIX 2.6.
Here is my result:
```
 ￥ curl http://127.0.0.1:9080/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X POST -i -d '
{
"uri": "/testNacos/*",
"name": "testNacos",
"upstream": {
"service_name": "APISIX-NACOS",
"type": "roundrobin",
"discovery_type": "nacos"
}
}'
HTTP/1.1 201 Created
Server: openresty
Date: Thu, 22 Jul 2021 03:11:57 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600

{"node":{"key":"\/apisix\/routes\/00000000000000254369","value":{"status":1,"uri":"\/testNacos\/*","create_time":1626923517,"update_time":1626923517,"priority":0,"name":"testNacos","upstream":{"scheme":"http","type":"roundrobin","service_name":"APISIX-NACOS","discovery_type":"nacos","pass_host":"pass","hash_on":"vars"}}},"action":"create"}
```

The response header is quite different.

**Comment by itw-hewb** [comment]
> 请确保您使用的是 APISIX 2.6。
> 这是我的结果：
> 
> ```
>  ￥ curl http://127.0.0.1:9080/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X POST -i -d '
> {
> "uri": "/testNacos/*",
> "name": "testNacos",
> "upstream": {
> "service_name": "APISIX-NACOS",
> "type": "roundrobin",
> "discovery_type": "nacos"
> }
> }'
> HTTP/1.1 201 Created
> Server: openresty
> Date: Thu, 22 Jul 2021 03:11:57 GMT
> Content-Type: application/json
> Transfer-Encoding: chunked
> Connection: keep-alive
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: *
> Access-Control-Max-Age: 3600
> 
> {"node":{"key":"\/apisix\/routes\/00000000000000254369","value":{"status":1,"uri":"\/testNacos\/*","create_time":1626923517,"update_time":1626923517,"priority":0,"name":"testNacos","upstream":{"scheme":"http","type":"roundrobin","service_name":"APISIX-NACOS","discovery_type":"nacos","pass_host":"pass","hash_on":"vars"}}},"action":"create"}
> ```
> 
> 响应头是完全不同的。

因此我也很疑惑 是否与我最开始从2.5版本直接升级到2.6版本有关系?
