### ISSUE TITLE
doc: Comparison of APISIX vs other products in the market (Benchmark)

### ISSUE THREAD

**Issue by moonming** [apache/apisix#466]
like https://www.krakend.io/docs/benchmarks/api-gateway-benchmark/

**Comment by moonming** [comment]
@Miss-you  Can you write an article about the results of your test?  thx

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
