### ISSUE TITLE
question: Proxy static files with APISIX, how to configure routes

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#4672]
Proxy static files with Nginx, for example:

```nginx
location ~* .(js|css|flash|media|jpg|png|gif|ico|vbs|json|txt)$ {
...
}
```

In `nginx.conf`, this means matching requests with js, css, etc. as a suffix. This configuration can be converted into a route with regular matching for APISIX, for example:

```json
{
    "uri": "/*",
    "vars": [
        ["uri", "~~", ".(js|css|flash|media|jpg|png|gif|ico|vbs|json|txt)$"]
    ]
}
```

**Comment by xiangyu123** [comment]
and how to set the nginx root directive, to offer the static files from local directory ?
