### ISSUE TITLE
bug: It should return 400 when update consumer with mismatched username in path and body

### ISSUE THREAD

**Issue by liuxiran** [apache/apisix#4680]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.7
* OS (cmd: `uname -a`): Darwin Kernel Version 20.3.0
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
* apisix-dashboard version, if have: NAN
* luarocks version, if the issue is about installation (cmd: `luarocks --version`): NAN

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. I have a consumer, username is `user`
![image](https://user-images.githubusercontent.com/2561857/127104736-14b3db3a-e2a1-4a7d-8af3-650ebd46bb35.png)

2. when I update this consumer by admin-api used mismatched username in path  and body, update successfully

![image](https://user-images.githubusercontent.com/2561857/127104557-796367de-8b32-45c7-bb51-b08bd0ee2e19.png)

### What's the expected result?

IMO it should return HTTP code 400 when call admin-api to update consumer with mismatched username in path and body or user will get confused.

**Comment by spacewander** [comment]
Yes. We can add similar check like
https://github.com/apache/apisix/blob/20df78432dc9447c7a1c2f63c1cd53a1a641a3fa/apisix/admin/routes.lua#L46

PR is welcome!

**Comment by liuxiran** [comment]
> Yes. We can add similar check like
> https://github.com/apache/apisix/blob/20df78432dc9447c7a1c2f63c1cd53a1a641a3fa/apisix/admin/routes.lua#L46
> 
> PR is welcome!

Thanks a lot~

**Comment by okaybase** [comment]
[https://github.com/apache/apisix/pull/4756](url) @spacewander @liuxiran
