### ISSUE TITLE
request help: traffic-split 插件切量的比例什么情况下会不准确？波动有多大？

### ISSUE THREAD

**Issue by ryan4yin** [apache/apisix#4684]
### Issue description

traffic-split 插件中的这句话是什么意思？
```
注：由于加权循环算法（特别是在重置wrr状态时）的缺点，因此每个上游之间的比率可能不太准确。
```

是说 traffic-split 流量切分可能会波动？哪些情况会重置 wrr 状态？对切量有什么影响？

**Comment by tokers** [comment]
> ### Issue description
> traffic-split 插件中的这句话是什么意思？
> 
> ```
> 注：由于加权循环算法（特别是在重置wrr状态时）的缺点，因此每个上游之间的比率可能不太准确。
> ```
> 
> 是说 traffic-split 流量切分可能会波动？哪些情况会重置 wrr 状态？对切量有什么影响？

The WRR state will be reset if the configuration of traffic split was changed.
