### ISSUE TITLE
After using the skywalking plug-in, upstream services cannot be accessed

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix#4698]
curl上游服务之后返回curl: (52) Empty reply from server。
查看日志![46C965BDF9621054323F74BC53CCD04A](https://user-images.githubusercontent.com/31987918/127438962-3b56c66f-eaf1-4631-bb53-e3cf09bdb653.jpg)
请问是什么问题啊

**Comment by tzssangglass** [comment]
similar as #4571

**Comment by tzssangglass** [comment]
hi @lihuawei321, did you fix this?

**Comment by dmsolr** [comment]
It looks like #4571 said. Did you set a global rule for skywalking and bind skywalking plugin to the route/service at the same time? If so, it has been resolved by #4571.

**Comment by moonming** [comment]
@lihuawei321 
Please use English in the public channel, thx

**Comment by spacewander** [comment]
Closed as lack of response.
