### ISSUE TITLE
It is recommended that the log-rotate plugin add a log compression function

### ISSUE THREAD

**Issue by Areturn** [apache/apisix#4699]
![image](https://user-images.githubusercontent.com/25275823/127439932-4034034e-a402-486f-893d-67f748b3ace9.png)
访问大的话日志不压缩，会特别占用磁盘

![image](https://user-images.githubusercontent.com/25275823/127440065-d8856122-d0a0-4947-87ce-ed4f92fea88e.png)
未压缩日志是压缩后日志的10+倍大小，压缩还是很有必要的

**Comment by tzssangglass** [comment]
hi @Areturn, Would you be interested in submitting a PR to resolve?

**Comment by moonming** [comment]
@Areturn 
Please use English in the public channel, thx

**Comment by okaybase** [comment]
PR: https://github.com/apache/apisix/pull/4795
