### ISSUE TITLE
 [warn] 53#53: *8 [lua] plugin.lua:150: load(): new plugins

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#4700]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version :2.7:
* OS (cmd: `Linux   3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`):
* etcd version:3.4:

 My  config.yaml body:

apisix:       
  admin_key:
    -
      name: admin
      key: edd1c9dxe2s5f136f87ad84dxxxxx
      role: admin                

etcd:
  host:                           
    - "http://10.0.1.xx:2379"

When I deployed to K8S ,It show warn log:
 
2021/07/29 07:59:23 [warn] 53#53: *8 [lua] plugin.lua:150: load(): new plugins: {"batch-requests":true,"proxy-rewrite":true,"proxy-cache":true,"redirect":true,"http-logger":true,"proxy-mirror":true,"prometheus":true,"server-info":true,"limit-req":true,"client-control":true,"key-auth":true,"ext-plugin-pre-req":true,"jwt-auth":true,"traffic-split":true,"authz-keycloak":true,"grpc-transcode":true,"openid-connect":true,"syslog":true,"limit-conn":true,"uri-blocker":true,"response-rewrite":true,"udp-logger":true,"request-validation":true,"cors":true,"consumer-restriction":true,"ext-plugin-post-req":true,"serverless-post-function":true,"zipkin":true,"example-plugin":true,"serverless-pre-function":true,"tcp-logger":true,"request-id":true,"sls-logger":true,"echo":true,"referer-restriction":true,"kafka-logger":true,"basic-auth":true,"limit-count":true,"wolf-rbac":true,"fault-injection":true,"hmac-auth":true,"api-breaker":true,"ip-restriction":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 49#49: *5 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 48#48: *4 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 44#44: *2 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 50#50: *6 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 46#46: *1 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 43#43: *3 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 45#45: *9 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 47#47: *7 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*
2021/07/29 07:59:23 [warn] 53#53: *8 [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true}, context: init_worker_by_lua*

**Comment by spacewander** [comment]
The warn message is fine enough. We choice this log level so that the log message can be seen by default. It doesn't mean any harm, unlike the `error` one.
