### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by azura27** [apache/apisix#4717]
### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.0
* OS (cmd: `uname -a`): centos 7.4
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.17.8.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.5
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. set a route with cors open, OPTIONS method support
2.visit route with OPTIONS method, return response with no allow-control-allow-origin etc. headers
3.

### What's the actual result? (including assertion message & call stack if applicable)
response with no allow-control-allow-origin etc. headers
### What's the expected result?
response with allow-control-allow-origin etc. headers

For split backend and frontend environment OPTIONS method is used frequently, so return in rewrite stage is not suitable

**Comment by spacewander** [comment]
> set a route with cors open, OPTIONS method support

What's your configuration for this route?

**Comment by azura27** [comment]
"cors":{"allow_origins":"*","expose_headers":"*","allow_credential":false,"max_age":5,"allow_headers":"*","allow_methods":"GET,HEAD,PUT,PATCH,POST,OPTIONS"}

**Comment by tzssangglass** [comment]
I think it's expected behavior, and take a look at this: https://github.com/apache/apisix/issues/1100

source code for `cors` plugin handling OPTIONS method: https://github.com/apache/apisix/blob/9db2dd2399c3970df1e1b7fa0f8b7dcd92d26b1c/apisix/plugins/cors.lua#L227-L231

The OPTIONS method is a preflight request to check if CORS is supported, so the OPTIONS response header should not require the `allow-control-allow-origin` header.

**Comment by spacewander** [comment]
@azura27 


> 
> 
> "cors":{"allow_origins":"_","expose_headers":"_","allow_credential":false,"max_age":5,"allow_headers":"*","allow_methods":"GET,HEAD,PUT,PATCH,POST,OPTIONS"}

`""` is not a valid configuration, which will remove the allow-control-allow-origin header.
