### ISSUE TITLE
 plugin.lua:92: load_plugin(): failed to load plugin [limit-conn] err: module 'apisix.stream.plugins.limit-conn' not found:

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#4720]
Environment
Bug report without environment information will be ignored or closed.

apisix version :2.7:
OS (cmd: Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux):
etcd version:3.4:

My config.yaml body: 
 `apisix:       
  admin_key:
    -
      name: admin
      key: edd1c9dxe2s5f136f87ad84dd25s8f1
      role: admin                

etcd:
  host:                           
    - "http://10.0.1.6:2379"    

plugins:                           # plugin list (sorted by priority)
  - client-control                 # priority: 22000
  - ext-plugin-pre-req             # priority: 12000
  - zipkin                         # priority: 11011
  - request-id                     # priority: 11010
  - fault-injection                # priority: 11000
  - serverless-pre-function        # priority: 10000
  - batch-requests                 # priority: 4010
  - cors                           # priority: 4000
  - ip-restriction                 # priority: 3000
  - ua-restriction                 # priority: 2999
  - referer-restriction            # priority: 2990
  - uri-blocker                    # priority: 2900
  - request-validation             # priority: 2800
  - openid-connect                 # priority: 2599
  - wolf-rbac                      # priority: 2555
  - hmac-auth                      # priority: 2530
  - basic-auth                     # priority: 2520
  - jwt-auth                       # priority: 2510
  - key-auth                       # priority: 2500
  - consumer-restriction           # priority: 2400
  - authz-keycloak                 # priority: 2000
  - error-log-logger              # priority: 1091
  - proxy-mirror                   # priority: 1010
  - proxy-cache                    # priority: 1009
  - proxy-rewrite                  # priority: 1008
  - api-breaker                    # priority: 1005
  - limit-conn                     # priority: 1003
  - limit-count                    # priority: 1002
  - limit-req                      # priority: 1001
  - gzip                           # priority: 995
  - server-info                    # priority: 990
  - traffic-split                  # priority: 966
  - redirect                       # priority: 900
  - response-rewrite               # priority: 899 
  - grpc-transcode                 # priority: 506
  - prometheus                     # priority: 500
  - echo                           # priority: 412
  - http-logger                    # priority: 410
  - sls-logger                     # priority: 406
  - tcp-logger                     # priority: 405
  - kafka-logger                   # priority: 403
  - syslog                         # priority: 401
  - udp-logger                     # priority: 400
  - example-plugin                 # priority: 0
  - serverless-post-function       # priority: -2000
  - ext-plugin-post-req            # priority: -3000

stream_plugins: # sorted by priority
  - ip-restriction                 # priority: 3000
  - limit-conn                     # priority: 1003
  - mqtt-proxy                     # priority: 1000`

When I deployed to K8S ,It show err log:
 
`2021/07/30 06:45:12 [error] 52#52: *9 [lua] plugin.lua:92: load_plugin(): failed to load plugin [limit-conn] err: module 'apisix.stream.plugins.limit-conn' not found:
no field package.preload['apisix.stream.plugins.limit-conn']
no file '/usr/local/apisix//deps/share/lua/5.1/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/apisix//deps/share/lua/5.1/apisix/stream/plugins/limit-conn/init.lua'
no file '/usr/local/apisix/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/apisix/apisix/stream/plugins/limit-conn/init.lua'
no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/limit-conn.ljbc'
no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/limit-conn/init.ljbc'
no file '/usr/local/openresty/lualib/apisix/stream/plugins/limit-conn.ljbc'
no file '/usr/local/openresty/lualib/apisix/stream/plugins/limit-conn/init.ljbc'
no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/limit-conn/init.lua'
no file    ###'/usr/local/openresty/lualib/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/lualib/apisix/stream/plugins/limit-conn/init.lua'
no file './apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/share/lua/5.1/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/share/lua/5.1/apisix/stream/plugins/limit-conn/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/limit-conn/init.lua'
no file './apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/share/lua/5.1/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/share/lua/5.1/apisix/stream/plugins/limit-conn/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/limit-conn.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/stream/plugins/limit-conn/init.lua'
no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/stream/plugins/limit-conn.so'
no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/stream/plugins/limit-conn.so'
no file '/usr/local/openresty/site/lualib/apisix/stream/plugins/limit-conn.so'
no file '/usr/local/openresty/lualib/apisix/stream/plugins/limit-conn.so`

**Comment by tzssangglass** [comment]
The `limit-conn` plugin in stream mode is only available in APISIX version 2.8, you should upgrade your APISIX version to 2.8.
