### ISSUE TITLE
apisix 启动日志是什么意思？

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#4721]
Environment
Bug report without environment information will be ignored or closed.

apisix version :2.7:
OS (cmd: Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux):
etcd version:3.4:

部署apisix 到k8s上，查看日志，这两行是什么意思？到底 是启动成功呢？还是失败？ 还有怎样查apisix 运行状态？

![QQ截图20210730150330](https://user-images.githubusercontent.com/21329253/127614260-c64d9128-cd61-426a-b8b9-f108fd62c168.png)

**Comment by tzssangglass** [comment]
`init` means initialize the runtime environment, `init_etcd` means initialize the etcd connection and get configuration information.

If there are only these two log lines, then APISIX may fail to start.

You can access the APISIX proxy port to check if it works.

**Comment by moonming** [comment]
@yaobo-lab @tzssangglass 
Please use English in the public channel, thx
