### ISSUE TITLE
request help: can using apisix-openresty in production ?

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix#4724]
### Issue description
I using mtls to connect etcd, so i mush using `apisix-openresty`. Is apisix-openresty be fully testing, can i using apisix-openresty in production?

**Comment by spacewander** [comment]
Yes. See https://github.com/apache/apisix/blob/b967b8accabc06d3ffbda61630bce3faddb0cb10/ci/linux_openresty_runner.sh#L20
https://github.com/apache/apisix/blob/b967b8accabc06d3ffbda61630bce3faddb0cb10/utils/linux-install-openresty.sh#L27-L35
