### ISSUE TITLE
47#47: *152 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/upstreams] err: compacted, will read the configuration again via readdir, context: ngx.timer

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#4732]
apisix version :2.8:
OS (cmd: Linux 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux):
etcd version:3.4:

 My config.yaml body:

`apisix:
  enable_admin: true
  port_admin: 9180
  allow_admin:
    - 0.0.0.0/0
  https_admin: false
  admin_key:
    - name: "admin"
      key: edd1c9dxe2s5f136f87ad84dd25s8f1
      role: admin

  allow_admin:
   https_admin: false

nginx_config:
  error_log_level: warn

etcd:
  host:
    - "http://10.0.1.6:2379"`

When I deployed to K8S ,It show  many warn log: how to fix it？

`2021/08/02 01:26:15 [warn] 49#49: *45 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/upstreams] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:15 [warn] 45#45: *34 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/services] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:16 [warn] 48#48: *112 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/upstreams] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:16 [warn] 47#47: *138 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/plugin_metadata] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:16 [warn] 42#42: *71 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/routes] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:16 [warn] 42#42: *67 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/plugin_metadata] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:17 [warn] 48#48: *106 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/services] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:17 [warn] 52#52: *160 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/routes] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:18 [warn] 48#48: *102 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/ssl] err: compacted, will read the configuration again via readdir, context: ngx.timer
2021/08/02 01:26:19 [warn] 47#47: *152 [lua] config_etcd.lua:336: sync_data(): waitdir [/apisix/upstreams] err: compacted, will read the configuration again via readdir, context: ngx.timer`

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/3438
