### ISSUE TITLE
request help:  Does Apisix support multiple prefix route matching

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4742]
### Issue description
I have an upstream service and I want routes starting with /API and /public to match correctly and to be routed to the same upstream service. I want this to be implemented in a routing rule. So how do I configure it?

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Match with regex? https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-use-route-uri-for-regular-matching

**Comment by zuiyangqingzhou** [comment]
got it , thank you
