### ISSUE TITLE
k8s 环境apisix集成prometheus，apisix和prometheus的配置如何设置？request help: 

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix#4744]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tao12345666333** [comment]
You need to modify the configmap resource of Apache APISIX

```
plugin_attr:
  prometheus:
    export_addr:
      ip: 0.0.0.0
      port: 9092
```

and create a service to expose this port.

xref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md

**Comment by tao12345666333** [comment]
We can also add this function to Helm chart

https://github.com/apache/apisix-helm-chart

**Comment by wjmmjr** [comment]
已经解决了，我的处理方式：
1. prometheus-server的configmap增加job_name
`scrape_configs:
    - job_name: apisix-prom
      metrics_path: '/apisix/prometheus/metrics' #这是固定的路径，不能更改
      static_configs:
      - targets:
        - apisix-admin.apisix:9091`
  2. apisix-admin的svc增加port
  ` - name: apisix-prom
      port: 9091
    `
3. apisix的configmap增加插件的配置
  `plugin_attr:
      prometheus:
        export_addr:
          ip: "0.0.0.0"
          port: 9091`

**Comment by tao12345666333** [comment]
@tzssangglass @yzeng25 should we add this to the FAQ?

**Comment by tzssangglass** [comment]
> @tzssangglass @yzeng25 should we add this to the FAQ?

Is this a native deployment of APISIX in k8s? not APISIX Ingress Controller or APISIX Helm Charts

**Comment by tao12345666333** [comment]
yep. And APISIX helm chart doesn't support this configuration now.

**Comment by yzeng25** [comment]
> @tzssangglass @yzeng25 should we add this to the FAQ?

Only if it is frequently asked.

**Comment by webup** [comment]
> It has been solved. This is my way to deal with it:
> 
> 1. Add job to the configmap of prometheus-server
> 
> ```
> scrape_configs:
>     - job_name: apisix-prom
>       metrics_path: '/apisix/prometheus/metrics'   #This is a fixed path and cannot be changed
>       static_configs:
>       - targets:
>          - your-svc.your-namespace:9091
> ```
> 
> 1. Add port to SVC of apisix-admin
> 
> ```
> - name: apisix-prom
>   port: 9091
> ```
> 
> 1. Add the configuration of the apisix plugin_attr
> 
> ```
>   plugin_attr:
>       prometheus:
>            export_addr:
>               ip: "0.0.0.0"
>               port: 9091
> ```

This works, but seems the plugin configuration made in dashboard could not overwrite this `plugin_attr` content. :(
