### ISSUE TITLE
bug: apisix customized plugin doesn't effect

### ISSUE THREAD

**Issue by clojure8** [apache/apisix#4751]
### Issue description
Here comes a problem, i add a customized plugin(openid-connect-extra) under folder `./apisix/plugins`, it's docker images,
then i check the plugin actually in this folder as below image shown
![wecom-temp-c03669fb2fa90c3d2f74a3a3a0a7d74e](https://user-images.githubusercontent.com/44196210/128113362-bb80c7bd-b90b-4e57-bf2a-b92b016ff997.png)

but when i running apisix, the error logs shown that apisix.plugins.openid-connect-extra do not found within apisix module, could please give any advise about it.
<img width="1531" alt="wecom-temp-277e58a737396a8314d307219d6335dc" src="https://user-images.githubusercontent.com/44196210/128113371-0b68e52c-9906-40f3-9b1b-88d98c3490e4.png">

### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`): linux(ACK)

use apisix:2.6 image and copy my plugins into it

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1. add self plugin as below 
```
############创建Dockerfile文件
cat > Dockerfile << EOF
FROM apache/apisix:2.6-alpine
COPY apisix-2.6/apisix/plugins/openid-connect-extra.lua /usr/local/apisix/apisix/plugins
COPY apisix-2.6/apisix/plugins/openid-connect-redis.lua /usr/local/apisix/apisix/plugins
RUN  sed -i '/^plugins/a \  - openid-connect-extra'     /usr/local/apisix/conf/config-default.yaml
EOF
```
2.start apsix

### What's the actual result? (including assertion message & call stack if applicable)

<img width="1531" alt="wecom-temp-277e58a737396a8314d307219d6335dc" src="https://user-images.githubusercontent.com/44196210/128113371-0b68e52c-9906-40f3-9b1b-88d98c3490e4.png">

### What's the expected result?

run successfully and load my custimized plugin openid-connect-extra

**Comment by tokers** [comment]
It's weird as the backtrace showing there is no such a file: 
![image](https://user-images.githubusercontent.com/10428333/128123701-fdc03133-8989-4034-9572-f485a49571db.png)

**Comment by tokers** [comment]
Is it normal on the VM environment.

**Comment by tylitianrui** [comment]
is it  relative path ?
