### ISSUE TITLE
request help: 提示 Request Error Code: 2000001 The manager-api and apache apisix are mismatched.

### ISSUE THREAD

**Issue by luoyin63** [apache/apisix#4753]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.7
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Baoyuantop** [comment]
This might help you https://github.com/apache/apisix-dashboard/issues/1944#issuecomment-885051655
