### ISSUE TITLE
request help:  got `{"error_msg":"failed to match any routes"}` after setting a route

### ISSUE THREAD

**Issue by luoyin63** [apache/apisix#4754]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.7
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):
查看日志提示：2021-08-04T14:14:00.246+0800	WARN	store/store.go:148	data not found by key: 366625380058008792

**Comment by tokers** [comment]
@luoyin63 Please paste much information here.

1. The route you created
2. How did you send requests to APISIX (and show us the response).

**Comment by luoyin63** [comment]
I  send requests to APISIX APISIX Dashboard

**Comment by tokers** [comment]
> I send requests to APISIX APISIX Dashboard

Could you paste the elaborate route configuration and the request/response?

**Comment by membphis** [comment]
please change the title to English @luoyin63

**Comment by starsz** [comment]
It seems that the resources' key (366625380058008792) can't be found in etcd ?
