### ISSUE TITLE
request help: Can the type parameter of the consumer-restriction plug-in support route_ id

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#4755]
### Issue description
在Consumer中添加 consumer-restriction 插件，里面的 type 能否支持下route_id，这样我们就能基于 consumer 的纬度来限制能访问到的 route，现在的版本我看了下只支持 consumer_name 和 service_id，即只能在 route 纬度来限制 consumer 或者 只能在 consumer 纬度来限制能访问的 service。

需求场景：同一组service下可以有多个route，但是可能有部分route是不用鉴权的或者需要额外申请才给开通，如果能在consumer纬度支持一下 route_id，那样就能更精细化的赋权，且不用每个用户来申请权限都需要对route接口发起一个PATCH请求。

插件文档：https://apisix.apache.org/docs/apisix/plugins/consumer-restriction
具体参数：type
参数描述：According to different objects, corresponding restrictions, support consumer_name, service_id.

### Environment
基于官方最新docker镜像部署。
* apisix version (cmd: `apisix version`): 2.8
* OS (cmd: `uname -a`): centos7
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.2
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.3.4
* apisix-dashboard version, if have: 2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):  null

**Comment by spacewander** [comment]
PR is welcome!

**Comment by jagerzhang** [comment]
> PR is welcome!

Aready Commit, Plz review.

**Comment by membphis** [comment]
@jagerzhang please change the title to English
