### ISSUE TITLE
request help: 关于细粒度

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix#4762]
### Issue description
现在有个场景需要做到：不同接口对应不同的权限，那现在只能有多少个api就需要建很多个路由吗？

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):2.7.3
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4.0

**Comment by spacewander** [comment]
Yes

**Comment by zhangbing17** [comment]
> Yes

那意思是关于细粒度这块还没做到是吧

**Comment by tzssangglass** [comment]
We have just merged the [authz-casbin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-casbin.md) plugin, you can use casbin to check the permissions of different paths on the same route.

casbin link: https://github.com/casbin/casbin

**Comment by zhangbing17** [comment]
> We have just merged the [authz-casbin](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-casbin.md) plugin, you can use casbin to check the permissions of different paths on the same route.
> 
> casbin link: https://github.com/casbin/casbin

你说的这个我看咱们apisix现在是不支持的吧？

**Comment by membphis** [comment]
please change the title to English @zhangbing17

**Comment by starsz** [comment]
Maybe you can try to write some logic in the server-less plugin?
http://apisix.apache.org/docs/apisix/plugins/serverless

**Comment by tzssangglass** [comment]
> 你说的这个我看咱们apisix现在是不支持的吧？

It's not a question of support or not, there are many ways to achieve. Creating a lot of routes is one way to implement this, as is using casbin, and you can choose the implementation to suit your situation.
