### ISSUE TITLE
request help: 是否考虑给upstream的node增加ttl属性

### ISSUE THREAD

**Issue by ggxx** [apache/apisix#4764]
目前在admin API中看到route支持ttl，是否考虑在upstream的node中增加ttl属性？
这样通过upstream的node维护service provider地址，provider正常运行中可以定期更新自身node的ttl，当provider不可用时，该node的ttl到期后自动删除

**Comment by spacewander** [comment]
We can only set ttl to a key, but not a field inside the key.
