### ISSUE TITLE
request help: java如何集成apisix

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix#4768]
### Issue description
有个不明白。springboot项目怎么集成apisix呢，有没有demo？
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):2.7.3
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4.0

**Comment by tokers** [comment]
Try to learn https://github.com/apache/apisix-java-plugin-runner.

**Comment by zhangbing17** [comment]
> Try to learn https://github.com/apache/apisix-java-plugin-runner.

你的这是自定义插件吧，比如鉴权抽成一个服务
