### ISSUE TITLE
bug:  unable to authenticate using the wolf-rbac plugin

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix#4769]
### Environment
![image](https://user-images.githubusercontent.com/23377580/128491122-ab4d5a9b-82e9-4ed8-a806-901b33d6a0c7.png)

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.wolf首先创建用户
![image](https://user-images.githubusercontent.com/23377580/128491458-e18c0e14-65f0-432d-b723-0806936b85d8.png)

2.其次获取刚用户的key
![image](https://user-images.githubusercontent.com/23377580/128491649-4f874b96-5867-4a66-a851-134cd90bf1aa.png)

3.验证访问
![image](https://user-images.githubusercontent.com/23377580/128491599-4fddca9b-9e35-4808-9979-96d040a6ed87.png)

apisix和wolf部署在不同服务器

**Comment by tzssangglass** [comment]
This exception message is for the `consumer-restriction` plugin, see: https://github.com/apache/apisix/blob/baf843403461883c1334e63d15a6bb3622c31940/apisix/plugins/consumer-restriction.lua#L125

This error is not due to the wolf-rbac plugin.

**Comment by zhangbing17** [comment]
So what was the mistake that caused this? I think I configured everything right，
![image](https://user-images.githubusercontent.com/23377580/128651752-98db42fb-07ce-4ec3-9602-3ea215a10cbb.png)

**Comment by tzssangglass** [comment]
`consumer-restriction` is incorrectly configured, see :https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md

**Comment by zhangbing17** [comment]
Hey, big man, what is this question
![image](https://user-images.githubusercontent.com/23377580/128654433-38b279b6-a2d5-4f8a-83e9-9673e2008fef.png)

Here is my Wolf configuration，
![image](https://user-images.githubusercontent.com/23377580/128654490-09739e5a-dc70-45d9-974a-ed71b2a1d764.png)
![image](https://user-images.githubusercontent.com/23377580/128654502-c250c1cb-0c45-459a-ab47-de23ad37f43a.png)
![image](https://user-images.githubusercontent.com/23377580/128654571-2670365d-d3df-42ba-85af-a001adee7d6c.png)

**Comment by zhangbing17** [comment]
![image](https://user-images.githubusercontent.com/23377580/128690490-912a89c1-395f-4d39-ba39-fc2538d08e2a.png)
Is this route correct?Why does certification still not work

**Comment by tokers** [comment]
> Hey, big man, what is this question
> ![image](https://user-images.githubusercontent.com/23377580/128654433-38b279b6-a2d5-4f8a-83e9-9673e2008fef.png)
> 
> Here is my Wolf configuration，
> ![image](https://user-images.githubusercontent.com/23377580/128654490-09739e5a-dc70-45d9-974a-ed71b2a1d764.png)
> ![image](https://user-images.githubusercontent.com/23377580/128654502-c250c1cb-0c45-459a-ab47-de23ad37f43a.png)
> ![image](https://user-images.githubusercontent.com/23377580/128654571-2670365d-d3df-42ba-85af-a001adee7d6c.png)

Your request was passed to the backend service and you may try to check out its configuration.

**Comment by tzssangglass** [comment]
the error of `resource '\/' not exist`，I think this was returned by wolf. The request path you are using is `/`, check if this request path exists in wolf.

**Comment by zhangbing17** [comment]
> 的错误`resource '\/' not exist`，我认为这是由狼返回的。您使用的请求路径是`/`，请检查 wolf 中是否存在此请求路径。

It's changed to this, but
![image](https://user-images.githubusercontent.com/23377580/128793255-3ee72206-5581-4c01-9aaa-e79f480ddd3f.png)

![image](https://user-images.githubusercontent.com/23377580/128793211-913c394f-5b87-4aa8-8323-0d3895ca7a0b.png)
![image](https://user-images.githubusercontent.com/23377580/128793277-375102d0-8360-4f23-80ef-4ce5bab5939b.png)

**Comment by tzssangglass** [comment]
I think you have the wrong `consumer-restriction` configuration, see: https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/consumer-restriction.md#%E7%A4%BA%E4%BE%8B

And I suggest you consider the `consumer-restriction` and `wolf-rbac` plugins separately. We are now communicating in a confusing situation.
