### ISSUE TITLE
request help: when i run ip-restriction single test,always appears below errors

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#4770]
### Issue description
when i run ip-restriction single test,always appears below errors。
[error] 14511#329621: *2310 [lua] config_etcd.lua:600: failed to fetch data from etcd: closed,  etcd key: /apisix/upstreams, context: ngx.timer"
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `2.8`):
* OS (cmd: `MAC-OS`):

**Comment by Yiyiyimu** [comment]
Hi @shoulda could you show your etcd's status. As the error suggests, etcd seems unhealthy

**Comment by tokers** [comment]
> ### Issue description
> when i run ip-restriction single test,always appears below errors。
> [error] 14511#329621: *2310 [lua] config_etcd.lua:600: failed to fetch data from etcd: closed, etcd key: /apisix/upstreams, context: ngx.timer"
> 
> ### Environment
> Request help without environment information will be ignored or closed.
> 
> * apisix version (cmd: `2.8`):
> * OS (cmd: `MAC-OS`):

It's my understanding that this is a generic error and is not caused by this plugin, so we may focus on why this error occurres.

**Comment by shoulda** [comment]
> Hi @shoulda could you show your etcd's status and how you configure etcd in apisix.
> As the error suggests, etcd seems unhealthy

I use the config-defaul.yaml file, dont hava special config

**Comment by shoulda** [comment]
> > ### Issue description
> > when i run ip-restriction single test,always appears below errors。
> > [error] 14511#329621: *2310 [lua] config_etcd.lua:600: failed to fetch data from etcd: closed, etcd key: /apisix/upstreams, context: ngx.timer"
> > ### Environment
> > Request help without environment information will be ignored or closed.
> > 
> > * apisix version (cmd: `2.8`):
> > * OS (cmd: `MAC-OS`):
> 
> It's my understanding that this is a generic error and is not caused by this plugin, so we may focus on inspecting why this error occurres.

It's OK when i run the ip-restriction single test in apisix2.5

**Comment by tzssangglass** [comment]
> ip-restriction single test

what it is?

**Comment by shoulda** [comment]
> > ip-restriction single test
> 
> what it is?

就是跑ip-restriction插件的单测😄

**Comment by tzssangglass** [comment]
On the master branch, I execute `make deps` nstall the latest dependencies. 

Turn on etcd, and  use `prove -Itest-nginx/lib -r t/plugin/ip-restriction.t` to run test, it works well.

**Comment by shoulda** [comment]
I was run apisix2.8, does you run the test on the apisix 2.8 works well?

**Comment by tzssangglass** [comment]
yes, my etcd version is 3.4.13
