### ISSUE TITLE
request help:  failed to install dependencies by make deps

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#4772]
### Issue description
failed to install dependencies by make deps
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): master
* OS (cmd: `uname -a`): 5.12.8-200.fc33.aarch64
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
```
nginx version: openresty/1.19.3.2
built by gcc 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
……
```

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):
```
/usr/local/bin/luarocks 3.4.0
LuaRocks main command-line interface
```

after executing `make deps` with the latest code, the error is 

```
Missing dependencies for casbin 1.26.0-1:
   lrexlib-pcre >= 2.9.1 (not installed)
   luaposix >= 35.0 (not installed)

casbin 1.26.0-1 depends on lua >= 5.1 (5.1-1 provided by VM)
casbin 1.26.0-1 depends on lualogging >= 1.5.1 (1.5.1-1 installed)
casbin 1.26.0-1 depends on lrexlib-pcre >= 2.9.1 (not installed)
Installing https://luarocks.org/lrexlib-pcre-2.9.1-1.src.rock

Error: Failed installing dependency: https://luarocks.org/casbin-1.26.0-1.rockspec - Failed installing dependency: https://luarocks.org/lrexlib-pcre-2.9.1-1.src.rock - Could not find header file for PCRE
  No file pcre.h in /usr/local/include
  No file pcre.h in /usr/include
  No file pcre.h in /include
You may have to install PCRE in your system and/or pass PCRE_DIR or PCRE_INCDIR to the luarocks command.
Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local
make: *** [Makefile:88: deps] Error 1
```

What should I do to process the PCRE header?

**Comment by spacewander** [comment]
See the latest change of https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md

**Comment by tzssangglass** [comment]
add pcre-devel dependency ->  `yum -y pcre-devel`
