### ISSUE TITLE
bug: plugins:proxy_cache, GET ,apisix-cache-status return,but POST not.

### ISSUE THREAD

**Issue by zhangdadan** [apache/apisix#4776]
apisix:v2.8
plugins:proxy_cache
my conf: 
`
"plugins": {
    "proxy-cache": {
      "cache_method": [
        "POST",
        "GET"
      ],
      "disable": false,
      "hide_cache_headers": true
    }
  },
`
I print ngx.var find that GET `upstream_cache_status` has value,but POST not at file `/usr/local/apisix/apisix/plugins/proxy-cache.lua`

What's wrong?

**Comment by tokers** [comment]
@zhangdadan Thank for your report, it seems there is a bug in the `proxy-cache` plugin, the `cache_method` setting doesn't affect the underlying `proxy_cache_methods` directive.

**Comment by zhangdadan** [comment]
![image](https://user-images.githubusercontent.com/18242914/128651927-799eb107-b183-4214-a1eb-62992071bd8d.png)

I find `proxy_cache_methods`  is not dynamic at `/usr/local/apisix/conf/nginx.conf`,can it be configured?

**Comment by tokers** [comment]
> > @zhangdadan Thank for your report, it seems there is a bug in the `proxy-cache` plugin, the `cache_method` setting doesn't affect the underlying `proxy_cache_methods` directive.
> 
> ![image](https://user-images.githubusercontent.com/18242914/128651927-799eb107-b183-4214-a1eb-62992071bd8d.png)
> 
> I find `proxy_cache_methods` is not dynamic at `/usr/local/apisix/conf/nginx.conf`,can it be configured?

Currently it's not dynamic, and cannot be extended by the plugin configuration.

**Comment by zhangdadan** [comment]
> > > @zhangdadan Thank for your report, it seems there is a bug in the `proxy-cache` plugin, the `cache_method` setting doesn't affect the underlying `proxy_cache_methods` directive.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/18242914/128651927-799eb107-b183-4214-a1eb-62992071bd8d.png)
> > I find `proxy_cache_methods` is not dynamic at `/usr/local/apisix/conf/nginx.conf`,can it be configured?
> 
> Currently it's not dynamic, and cannot be extended by the plugin configuration.

But，I has configured by myself and add `POST` value on `proxy_cache_methods ` at  the `/usr/local/apisix/conf/nginx.conf`,then run `apisix restart`, but it's not useful.

**Comment by tzssangglass** [comment]
You can try the configuration here：https://github.com/apache/apisix/blob/6655a358890925ee82a23a74b4edecca4130bba0/apisix/cli/ngx_tpl.lua#L599

**Comment by zhangdadan** [comment]
> You can try the configuration here：
> 
> https://github.com/apache/apisix/blob/6655a358890925ee82a23a74b4edecca4130bba0/apisix/cli/ngx_tpl.lua#L599
Thanks,it' useful
