### ISSUE TITLE
When deserializing cjson, Int64 may have a precision problem. How to deal with it

### ISSUE THREAD

**Issue by zuodengchao** [apache/apisix#4777]
local core=require("apisix.core")
local nosign="{\"msg\":\"参数不正确\",\"code\":1234567890123456789,\"errmsg\":\"SIGN_INVALID\"}";
 local obj=core.json.decode(nosign)
 core.log.warn("core conf:",core.json.encode(obj))

输出：

2021/08/08 14:26:38 [warn] 43#43: *2876 [lua] zdc.lua:20: phase_func(): core conf:{"errmsg":"SIGN_INVALID","code":1.2345678901235e+18,"msg":"参数不正确"}, client: 127.0.0.1, server: _, request: "POST /api/system/feedback/list HTTP/1.1", host: "192.168.2.15:9080"

问题：
 对于json 中的code 可否完整输出

**Comment by membphis** [comment]
please change the title to English

**Comment by spacewander** [comment]
cjson treats number in JSON as number in Lua, which is a double value. The only way to work around it is to use string for the big number.
