### ISSUE TITLE
The rewrite-proxy plug-in will invalidate the methods（ngx.req.set_uri_args or ngx.req.set_body_data） in the custom plug-in

### ISSUE THREAD

**Issue by zuodengchao** [apache/apisix#4790]
我自定义了一个插件xxx 执行阶段是access ，中间处理的逻辑是在body或者是在query 中添加了一个参数userId,	ngx.req.set_uri_args(data)和ngx.req.set_body_data(data)，
当没有启动rewrite-proxy插件的时候，我自定的插件是可以的，启用之后发现set_uri_args和set_body_data 将会失效

**Comment by tokers** [comment]
Do you mean `proxy-rewrite` plugin?

Which plugin runs first? The `proxy-rewrite` or your own? Actually the args sent to upstream was stored in the Nginx variable `$upstream_uri`, and it will be changed by `proxy-rewrite` (but appending the original args), so if the `proxy-rewrite` runs first, your changes are not ineffective.

**Comment by zuodengchao** [comment]
proxy-rewrite runs in the rewrite phase, and my customized plugin runs in the access phase, so proxy rewrite must run first.That's strange
