### ISSUE TITLE
response-write support mutiply error code

### ISSUE THREAD

**Issue by aichibazhang** [apache/apisix#4792]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.6
* OS (cmd: `uname -a`): ubuntu

**Comment by tokers** [comment]
@aichibazhang Could you describe your demands in more elaborately?

**Comment by aichibazhang** [comment]
我的意思是,response-write 是否可以支持多个错误码的改写,array类型,比如这样的json
```
 "response-rewrite": [{
            "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
            "headers": {
                "X-Server-id": 3,
                "X-Server-status": "on",
                "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
            },
            "vars":[
                [ "status","==","200" ]
            ]},
  "body": "{\"code\":\"error\",\"message\":\"request limit\"}",
            "headers": {
                "X-Server-id": 3,
                "X-Server-status": "on",
                "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
            },
            "vars":[
                [ "status","==","502" ]
            ]},
        ]
```

**Comment by tokers** [comment]
> 我的意思是,response-write 是否可以支持多个错误码的改写,array类型,比如这样的json
> 
> ```
>  "response-rewrite": [{
>             "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
>             "headers": {
>                 "X-Server-id": 3,
>                 "X-Server-status": "on",
>                 "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
>             },
>             "vars":[
>                 [ "status","==","200" ]
>             ]},
>   "body": "{\"code\":\"error\",\"message\":\"request limit\"}",
>             "headers": {
>                 "X-Server-id": 3,
>                 "X-Server-status": "on",
>                 "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
>             },
>             "vars":[
>                 [ "status","==","502" ]
>             ]},
>         ]
> ```

Interesting, I think it's useful.

**Comment by tokers** [comment]
@aichibazhang Would you like to write a discussion mail to dev@apisix.apache.org? Let's discuss about the proposal.

**Comment by membphis** [comment]
@aichibazhang Please mainly use English, eg: the title
