### ISSUE TITLE
request help:  Requires: openresty >= 1.17.8.2

### ISSUE THREAD

**Issue by luoyin63** [apache/apisix#4798]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

![image](https://user-images.githubusercontent.com/35888258/128965320-7e0a6edd-9771-4210-8a21-d7096afa5b70.png)
版本正确，却提示这个

**Comment by spacewander** [comment]
You need to install OpenResty with yum if you need to install APISIX with yum.
