### ISSUE TITLE
Admin API中关于创建Route入参(vars)的描述有错误

### ISSUE THREAD

**Issue by sunhao-java** [apache/apisix#4800]
# 改进文档

url: https://apisix.apache.org/zh/docs/apisix/admin-api#route

![image](https://user-images.githubusercontent.com/2178487/128975486-d88ae095-8e6d-4f3f-8c75-725374849927.png)
在json中，方括号表示数组，而花括号表示对象。这里明显是想表述是数组嵌套数组的方式，但是用两个花括号在json里面是错误的书写方式。所以这里应该是方括号。

## 描述你想要的解决方案

这里的示例应该修改成如下：
```
[
    [
        "arg_name",
        "==",
        "json"
    ],
    [
        "arg_age",
        ">",
        18
    ]
]
```

**Comment by tong3jie** [comment]
类似的错误还有几个字段：hosts，remote_addrs，methods

**Comment by spacewander** [comment]
PR is welcome!
