### ISSUE TITLE
request help: 这跟nginx有啥区别嘛？？没太看懂，生产中能直接替换nginx嘛

### ISSUE THREAD

**Issue by xiaojifan** [apache/apisix#4801]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by membphis** [comment]
pls read the readme doc first, it can help you.
