### ISSUE TITLE
bug: Error: read ECONNRESET

### ISSUE THREAD

**Issue by zhangbing17** [apache/apisix#4802]
### Issue description
Curl is available on the server and other server requests, but the local postman request keeps getting Error: read 
![image](https://user-images.githubusercontent.com/23377580/128985770-ed68cca4-a815-4531-9233-041b3393265f.png)
![image](https://user-images.githubusercontent.com/23377580/128985800-fd6abf0e-3f90-459a-aa4c-949a2342c08d.png)

ECONNRESET### Environment

Bug report without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.8
* OS (cmd: `uname -a`):Linux slave1 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.2

* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
* apisix-dashboard version, if have:2.7
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
![image](https://user-images.githubusercontent.com/23377580/128985977-18486c92-0200-4d33-abd4-cd07a172dc5f.png)

2.
![image](https://user-images.githubusercontent.com/23377580/128986003-75fce842-4672-488c-bb07-258f13b7e30f.png)

**Comment by tzssangglass** [comment]
curl is ok means that both curl and apisix are working well.

I think the problem is postman.

**Comment by zhangbing17** [comment]
> curl is ok means that both curl and apisix are working well.
> 
> I think the problem is postman.

nonono.I deployed with helm and postman has access to the admin-API interface,you see
![image](https://user-images.githubusercontent.com/23377580/129017650-9194bec0-ee9c-46ca-982a-796fd5538eed.png)

**Comment by tokers** [comment]
@zhangbing17 What's the result of using `curl` on your local machine?

**Comment by tzssangglass** [comment]
> > curl is ok means that both curl and apisix are working well.
> > I think the problem is postman.
> 
> nonono.I deployed with helm and postman has access to the admin-API interface,you see
> ![image](https://user-images.githubusercontent.com/23377580/129017650-9194bec0-ee9c-46ca-982a-796fd5538eed.png)

at bug report, step 1 and 2 use same host and port(`10.10.10.197:9080`), and then what is `10.10.12.196:30003`? For the initial bug report, I think it was a postman problem.

I was confused by the cases you listed.

For the initial bug report, I suppose another possibility is that curl and postman are in the same network environment? If it's not, then it could also be a network problem.
