### ISSUE TITLE
bug: proxy-mirror plugin's upstream(minio backend) return 502 when put big file（Multipart upload）via s3cmd 

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#4803]
### Issue description
APISIX config
```
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "plugins": {
        "proxy-mirror": {
           "host": "http://10.139.15.11:9002"
        }
    },
    "upstream": {
        "nodes": {
            "10.139.15.11:9001": 1
        },
        "type": "roundrobin"
    },
    "uri": "/*"
}'
```

s3cmd config
```
host_base = 10.139.15.11:9080
host_bucket = 10.139.15.11:9080
bucket_location = us-east-1
use_https = False

access_key = minioadmin
secret_key = minioadmin
signature_v2 = True

```

The mirror upstream already return http 502 when put big size file. Get, crate bucket and put little file is ok.
```
0.139.15.11 - - [10/Aug/2021:20:15:47 +0800] 10.139.15.11:9080 "PUT /test2/100M?partNumber=1&uploadId=f2fc2100-3a6d-4bf0-94d6-31957a6bf0e8 HTTP/1.1" 502 0 0.009 "-" "-" 10.139.15.11:9002 502 0.007 - 0.010 "http://10.139.15.11:9080"
10.139.15.11 - - [10/Aug/2021:20:15:47 +0800] 10.139.15.11:9080 "PUT /test2/100M?partNumber=2&uploadId=f2fc2100-3a6d-4bf0-94d6-31957a6bf0e8 HTTP/1.1" 502 0 0.012 "-" "-" 10.139.15.11:9002 502 0.012 - 0.012 "http://10.139.15.11:9080"
10.139.15.11 - - [10/Aug/2021:20:15:47 +0800] 10.139.15.11:9080 "PUT /test2/100M?partNumber=3&uploadId=f2fc2100-3a6d-4bf0-94d6-31957a6bf0e8 HTTP/1.1" 502 0 0.008 "-" "-" 10.139.15.11:9002 502 0.008 - 0.008 "http://10.139.15.11:9080"
10.139.15.11 - - [10/Aug/2021:20:15:48 +0800] 10.139.15.11:9080 "PUT /test2/100M?partNumber=4&uploadId=f2fc2100-3a6d-4bf0-94d6-31957a6bf0e8 HTTP/1.1" 502 0 0.010 "-" "-" 10.139.15.11:9002 502 0.007 - 0.010 "http://10.139.15.11:9080"
```

### Environment

Bug report without environment information will be ignored or closed.

The same env with https://github.com/apache/apisix/issues/4794

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Minimal test code / Steps to reproduce the issue

Bug report without steps to reproduce will be ignored or closed.

1.
2.
3.

**Comment by zhendongcmss** [comment]
relation issue https://github.com/apache/apisix/issues/4803

**Comment by spacewander** [comment]
Unfortunately, I can't understand what you mean...
Could you provide a docker-compose environment so that we can reproduce it?
Not everyone knows s3cmd and minio.

**Comment by zhendongcmss** [comment]
> Unfortunately, I can't understand what you mean...
> Could you provide a docker-compose environment so that we can reproduce it?
> Not everyone knows s3cmd and minio.

**Comment by zhendongcmss** [comment]
> Unfortunately, I can't understand what you mean...
> Could you provide a docker-compose environment so that we can reproduce it?
> Not everyone knows s3cmd and minio.

This bug can be close. It is the MinIO upload big files policy. More details are that each upload ID is different with each ipstreams when mutil parts uploaded. The ID is generated by upstreams. So, that is the reason.
