### ISSUE TITLE
increase the open-policy-agent  plug-in support

### ISSUE THREAD

**Issue by yaobo-lab** [apache/apisix#4812]
### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):
* OS (cmd: `uname -a`):
* OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
* apisix-dashboard version, if have:
* luarocks version, if the issue is about installation (cmd: `luarocks --version`):

apisix can increase the openpolicyagent plug-in support?
https://github.com/open-policy-agent/opa

**Comment by spacewander** [comment]
Already done.
