### ISSUE TITLE
request help: Custom authentication logic and response #4823 

### ISSUE THREAD

**Issue by zou8944** [apache/apisix#4823]
### Issue description

你好，两个问题，请帮忙解答我应该如何使用。

1. 我需要的场景类似[key-auth](https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/key-auth.md)，但是我还需要在插件获取到自定义key时去调用自定的验证服务进行验证。即，key是变化的，而不是不变的。类似nginx的auth.url功能。
2. 验证key后，需要根据验证结果返回自定义的响应body，类似下面。而不是apisix自定义的响应消息体。

```json
{
  "code": "TokenOutOfDate",
  "msg": "token已过期",
  "data": null
}
```

**Comment by tzssangglass** [comment]
Please use English on public channel.



> 1. 但是我还需要在插件获取到自定义key时去调用自定的验证服务进行验证。

you can use `"resty.http"` to do this, Reference: https://github.com/apache/apisix/blob/master/apisix/plugins/wolf-rbac.lua

> 2. 需要根据验证结果返回自定义的响应body

use `core.response.exit()`

**Comment by zou8944** [comment]
ok, thanks. I will try it later

**Comment by zou8944** [comment]
wait, you mean than I need us `"resty.http"` to custom my authentication logic ? Is there any existing plugin that I can use to do it ?

**Comment by tzssangglass** [comment]
> you mean than I need use `"resty.http"` to custom authentication logic

yes, you said to verify with a custom verification service.

> Is there any existing plugin that I can use to do it

I don't know which plugin is suitable for your scenario, you can look at the documentation and code and pick the right one yourself.

**Comment by zou8944** [comment]
ok, thanks, I will continue exploring.
