### ISSUE TITLE
request help: prometheus data is not refreshed in real time

### ISSUE THREAD

**Issue by zhixiang0608** [apache/apisix#4827]
apisix_http_status code出现500，修复线上问题后，http://127.0.0.1:9091/apisix/prometheus/metrics中返回的数据，500依然存在

**Comment by moonming** [comment]
Can you provide reproduction steps and your version of APISIX? thanks

**Comment by zhixiang0608** [comment]
apisix version:2.6

**Comment by zhixiang0608** [comment]
http://127.0.0.1:9091/apisix/prometheus/metrics 中的数据在我执行，apisix reload 后是最新的了，指标数据不是实时更新的

**Comment by tokers** [comment]
@zhixiang0608 Metrics about status code are counters, please refer to https://prometheus.io/docs/concepts/metric_types/ for more details.

**Comment by zhixiang0608** [comment]
我认为是原数据的问题，不是Prometheus的问题

**Comment by tzssangglass** [comment]
> 我认为是原数据的问题

you mean that the 500 status code is returned by upstream?

**Comment by zhixiang0608** [comment]
修复upstream 返回500状态码后，http://127.0.0.1:9091/apisix/prometheus/metrics 里依然存在有500的状态码

**Comment by zhixiang0608** [comment]
![P @Q_G%O)MUX{}0}%W37I 1](https://user-images.githubusercontent.com/46064678/129693521-c44594bd-b77c-4adc-bafa-2b57715fee04.png)
这里可以设置推送间隔吗

**Comment by tzssangglass** [comment]
The push interval is configured by the prometheus server.

BTW, please use English on public channel.

**Comment by tokers** [comment]
> 我认为是原数据的问题，不是Prometheus的问题

Requests with `500` code occurred and were recorded by the apisix Prometheus exporter, I didn't capture what your mean about the problem of the original data.
