### ISSUE TITLE
correct the path of ngx_tpl.lua in the docs

### ISSUE THREAD

**Issue by ependi-buzz** [apache/apisix#4828]
# Improve Docs

## Please describe which part of docs should be improved or typo fixed

apisix/docs/zh/latest/customize-nginx-configuration.md

```
APISIX 会通过 apisix/ngx_tpl.lua 这个模板和 conf/config-default.yaml 加 conf/config.yaml 的配置生成 Nginx 配置文件。
```
模板的实际路径是：apisix/apisix/cli/ngx_tpl.lua

**Comment by spacewander** [comment]
PR is welcome!
