### ISSUE TITLE
request help: kafka-logger batch-processor error

### ISSUE THREAD

**Issue by wugd1986** [apache/apisix#4829]
求助！！！使用kafka-logger发送日志，重复发送多次相同的日志，具体错误如下：

### Issue description
error.log:
2021/08/11 14:39:03 [error] 44#44: *37913 [lua] batch-processor.lua:63: Batch Processor[kafka logger] failed to process entries: failed send data to kafka topic: , context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:9080
2021/08/11 14:39:03 [error] 44#44: *37913 [lua] batch-processor.lua:68: Batch Processor[kafka logger] exceeded the max_retry_count[1] dropping the entries, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:9080

### Environment

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`):2.6
* OS (cmd: `uname -a`):centos 7.6
* etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):2.3

#####adding
max_retry_count use default config.
how can I get the reason?

**Comment by tzssangglass** [comment]
> failed to process entries: failed send data to kafka topic

This means that the topic you configured on the kafka-logger plugin does not exist on kafka, you can manually produce a message to this topic on kafka to verify.
