### ISSUE TITLE
request help: dcdn + apisix , need custom rewrite the error respone feature.

### ISSUE THREAD

**Issue by oldthreefeng** [apache/apisix#4834]
### Issue description

ref: https://github.com/apache/apisix/issues/4394

### Environment

for apisix. is there any way to rewrite the error response (an error like phase ssl certs not matches error) to upstream ?

when phase ssl error .  return an error respone to upstream. but this can ignore for us. 

on Dcdn. we hava many rules for alert..  one is 50X response .   if an error meet ssl phase error. then apisix return an 502 to dcdn. this is not what we want to alert . just warning or others ..

so anyone can helps me out ? 

Request help without environment information will be ignored or closed.

* apisix version (cmd: `apisix version`): 2.8
* OS (cmd: `uname -a`):  centos-7.9 .

**Comment by tokers** [comment]
It's not easy to implement, so hack might be introduced for Nginx core.
