### ISSUE TITLE
How can i encrypt the response body?

### ISSUE THREAD

**Issue by lcssos** [apache/apisix#4837]
### Issue description

How can i encrypt the response body?

### Environment

- apisix version (cmd: `apisix version`):2.8
- OS (cmd: `uname -a`):Linux 6c1306f13813 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.7.0

**Comment by tzssangglass** [comment]
1. Refer to https://github.com/apache/apisix/blob/a671909576ae98f697df8f225124c0b09989cdb6/apisix/plugins/grpc-transcode/response.lua#L32-L42 to learn how to get a response.

2. Implement your own encrypt logic

3. Refer to https://github.com/apache/apisix/blob/22ee20c480332ffdb43a1b2e8f4114ea81619d32/apisix/plugins/response-rewrite.lua#L124-L139 to learn how to rewrite the response

**Comment by spacewander** [comment]
Consider solved
