### ISSUE TITLE
request help: How about replace ngx.balancer ? 

### ISSUE THREAD

**Issue by chzhuo** [apache/apisix#4846]
### Issue description

There are many limitations in `ngx.balancer` :
1. Can't set `proxy_next_upstream` dynamically and  individually. 
2. Can't get tcp error in log_phase， so can't  enable passive tcp check in log_phase

I wanna adding this feature to apisix, but `ngx.balancer` baffle me.

### Environment

- apisix version (cmd: `apisix version`): 2.8
- OS (cmd: `uname -a`): Linux  5.4.94-1.el7.elrepo.x86_64 centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by spacewander** [comment]
You can extend it via adding new code to https://github.com/api7/apisix-nginx-module/tree/main/patch

**Comment by spacewander** [comment]
Looks like those two things can be done in Lua land so there is no need to patch. What about your opinion? Replace `ngx.balancer`, of course, is unacceptable.

**Comment by spacewander** [comment]
> Can't get tcp error in log_phase， so can't enable passive tcp check in log_phase

OK, seems there is no way to distinguish tcp error from the HTTP error in the log phase. But we already count all the tcp errors as HTTP error in the log phase, count them separately is confusing (The number will be mismatched with the one in the access log). So current way is good enough to me.

**Comment by chzhuo** [comment]
I come from apisix-ingress-controller. we have many pod ips, I wanna checking this ips is exists, so i can't using active checker, i use only tcp passive checker. if http return 502 in log phase that is confusing to distinguish tcp error

**Comment by tokers** [comment]
> I come from apisix-ingress-controller. we have many pod ips, I wanna checking this ips is exists, so i can't using active checker, i use only tcp passive checker. if http return 502 in log phase that is confusing to distinguish tcp error

It's inevitable to modify the Nginx core to expose the real cause.
