### ISSUE TITLE
bug: kafka-logger plugin  not worked after update host 

### ISSUE THREAD

**Issue by johnyq** [apache/apisix#4847]
### Issue description

I created apisix router by rest admin api and used kafka-logger plugin  to save http request logs.
I found  that I had made a mistake,  kafka host was incorrect,  so  update it.
But  the new host configuration does not be loaded  by apisix  , I checked logs and found some erros  about  kafka broker .
Erverything was  OK after  restarting  the apisisx server .

### Environment

- apisix version (cmd: `apisix version`): 2.8
- OS (cmd: `uname -a`): linux (k8s environment , the image from dockerhub)
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1. create route and used kafka-logger plugin, set kafka  host  is "xxxxxx"(incorrect).
2. update host is "xxxx"(correct).
3. update operation succeeded .

### Actual result

 http request logs does not be sent to kafka

### Error log

checked apissix logs and  found   some error logs like " kafka broker not found " ,

### Expected result

sent logs to kafka after updating kafka host

**Comment by tokers** [comment]
Any related error logs?

**Comment by tzssangglass** [comment]
Maybe it can be solved by this PR: https://github.com/apache/apisix/pull/4876

**Comment by spacewander** [comment]
Closed as lack of response.
Consider solved
