### ISSUE TITLE
request help: Node unhealth but shown health in controll api.

### ISSUE THREAD

**Issue by eavesmy** [apache/apisix#4862]
### Issue description

It's my upstream config:
`
{"id":"user","create_time":1629286241,"update_time":1629444473,"nodes":[{"host":"10.33.83.36","port":10244,"weight":100},{"host":"10.33.83.36","port":10243,"weight":100},{"host":"10.33.83.36","port":10240,"weight":100}],"retries":1,"timeout":{"connect":6,"read":6,"send":6},"type":"roundrobin","checks":{"active":{"concurrency":10,"healthy":{"http_statuses":[200,302],"interval":1,"successes":2},"host":"test.xxxx.com","http_path":"/user/healthCheck","port":80,"req_headers":["User-Agent: curl/7.29.0"],"timeout":1,"type":"http","unhealthy":{"http_failures":3,"http_statuses":[429,404,500,501,502,503,504,505],"interval":1,"tcp_Failures":2,"timeouts":3}},"passive":{"healthy":{"http_statuses":[200],"successes":3},"type":"http","unhealthy":{"http_failures":2,"http_statuses":[502,503,504,404,500],"tcp_failures":3,"timeouts":7}}},"scheme":"http","pass_host":"pass","name":"user"}
`
I have 3 nodes on this upstream. I kill two of theme then i call `/user/healthCheck`. Now controll api show result:
`
[{"name":"upstream#\/apisix\/upstreams\/user","src_type":"upstreams","nodes":[{"priority":0,"weight":100,"host":"10.33.83.36","port":10244},{"priority":0,"weight":100,"host":"10.33.83.36","port":10243},{"priority":0,"weight":100,"host":"10.33.83.36","port":10240}],"src_id":"user","healthy_nodes":[{"priority":0,"weight":100,"host":"10.33.83.36","port":10244},{"priority":0,"weight":100,"host":"10.33.83.36","port":10243},{"priority":0,"weight":100,"host":"10.33.83.36","port":10240}]}]
`.

I wanner know how can i get unhealth nodes.

### Environment

- apisix version (cmd: `apisix version`): 2.7
- OS (cmd: `uname -a`): Linux 10-33-83-36 4.19.0-9.el7.ucloud.x86_64 #1 SMP Mon Sep 28 10:29:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by tzssangglass** [comment]
> I wanner know how can i get unhealth nodes.

here:https://github.com/apache/apisix/blob/master/docs/en/latest/control-api.md#get-v1healthcheck

The following two conditions will change the upstream node status from healthy to unhealthy:
1. active health check detects node unavailability;
2. Passive health check proxy requests to upstream nodes and finds nodes unavailable;



> call `/user/healthCheck`

Is this the address of the active health check probe? You should access apisix and let apisix to proxy the request to this upstream so that health check will work.

You can also adjust the log level and check the `error.log`.

**Comment by eavesmy** [comment]
Thx. It's a logic mistake.
