### ISSUE TITLE
request help: how do you guys enable the Wiki tab in github

### ISSUE THREAD

**Issue by taojintianxia** [apache/apisix#4866]
### Issue description

 hi , apisix team.

  I'm a contributor from another Apache project  [ShardingSphere](https://github.com/apache/shardingsphere).as we could see, in apisix repository, the Wiki tab is enabled, before I tried to enable the Wiki in .asf.yaml for shardingsphere, but at the same day, I got an email from Apache infra, after I google the error, I found you guys got the [same issue](http://mail-archives.apache.org/mod_mbox/apisix-notifications/202108.mbox/%3C162933792448.26145.326156899500989531.asfpy@gitbox.apache.org%3E) ^_^

would you please share the experience how do you enable the Wiki tab in an Apache project in github ? ^_^

### Environment

not related to a tech issue

**Comment by juzhiyuan** [comment]
see https://github.com/apache/hbase/blob/master/.asf.yaml#L30

**Comment by taojintianxia** [comment]
thank you
