### ISSUE TITLE
request help: apisix-gateway / apisix-admin / apisix-dashboard

### ISSUE THREAD

**Issue by siaron** [apache/apisix#4871]
### Issue description

k8s 中部署apisix与apisix-ingress-controller 我理解了下.
- client 通过 apisix-gateway(9080) 根据匹配规则路由到不同的pod中
- apisix-ingress-controller 监听k8s api 通过apisix-admin(9180)写到apisix中
- apisix-dashboard 怎么和apisix通信的,直接写etcd吗?

### Environment

- apisix version (cmd: `laste`):
- OS (cmd: `mac`):
- apisix-dashboard version, if have: laste

**Comment by tokers** [comment]
@siaron 

> apisix-dashboard 怎么和apisix通信的,直接写etcd吗?

Right. Here is the architecture:

![image](https://user-images.githubusercontent.com/10428333/130436038-884bb6ce-eba2-402e-a2e3-8a76722d1b21.png)

**Comment by siaron** [comment]
有一个问题请教下.
 我们现在web静态页面是一个挂载了nginx的pod. 然后如果访问需要在apisix/ingress再转发到这个pod上.
问题:
  有没有一个方法直接在apisix上挂载一个静态资源路径可以直接配置下路径就可以访问. 这种方式支持吗?

**Comment by siaron** [comment]
> 有一个问题请教下.
> 我们现在web静态页面是一个挂载了nginx的pod. 然后如果访问需要在apisix/ingress再转发到这个pod上.
> 问题:
> 有没有一个方法直接在apisix上挂载一个静态资源路径可以直接配置下路径就可以访问. 这种方式支持吗?
