### ISSUE TITLE
request help: where is resty.apisix.response file?

### ISSUE THREAD

**Issue by XuZhaoPro** [apache/apisix#4873]
### Issue description

I find that there is gzip.lua plugin in master and that is what i need. But in the gzip.lua file, require resty.apisix.response , where   is the resty/apisix/response.lua file？

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
See
https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#step-6-build-openresty-for-apache-apisix
https://github.com/api7/apisix-nginx-module/blob/main/lib/resty/apisix/response.lua
