### ISSUE TITLE
apisix 2.8的全局规则对TCP/UDP Proxy不适用

### ISSUE THREAD

**Issue by pc10201** [apache/apisix#4879]
### Issue description

apisix 2.8的全局规则对TCP/UDP Proxy不适用

### Environment

- apisix version (cmd: `apisix version`):2.8
- OS (cmd: `uname -a`): CentOS 7 4.19.12-1.el7.elrepo.x86_64 #1 SMP Fri Dec 21 11:06:36 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 2.5
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

略

### Actual result

略

### Error log

略

**Comment by spacewander** [comment]
Look like we need a stream_global_rule, like stream_routes to routes.

**Comment by tokers** [comment]
> stream_global_rule

+1.
