### ISSUE TITLE
request help: Apisix proxy static resource ?

### ISSUE THREAD

**Issue by siaron** [apache/apisix#4889]
### Issue description

访问静态资源的问题.
我们现在的web静态页面是一个包含nginx的pod. 然后如果访问静态页面需要在apisix/ingress再转发到这个pod上.

问题:
有没有一个方法直接在apisix上挂载一个静态资源路径可以直接配置下路径就可以访问. 这种方式支持吗?

### Environment

- apisix version (cmd: `laste`):
- OS (cmd: `mac`):
- OpenResty / Nginx version (cmd: `laste` or `laste`):

**Comment by spacewander** [comment]
You can inject a Nginx configuration: https://apisix.apache.org/docs/apisix/customize-nginx-configuration
