### ISSUE TITLE
request help: mqtt-proxy

### ISSUE THREAD

**Issue by siaron** [apache/apisix#4891]
### Issue description

```
kubectl exec -it -n default apisix-66cc75967c-drjzl -- curl http://127.0.0.1:9180/apisix/admin/stream_routes/3 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "remote_addr": "0.0.0.0/24",
>     "plugins": {
>         "mqtt-proxy": {
>             "protocol_name": "MQTT",
>             "protocol_level": 4,
>             "upstream": {
>                 "nodes": {
>                     "10.1.1.107:1883": 1,
>                     "10.1.1.106:1883": 1,
>                     "10.1.1.105:1883": 1
>                 },
>                 "type": "roundrobin"
>             }
>         }
>     }
> }'
Defaulted container "apisix" out of: apisix, wait-etcd (init)
{"error_msg":"failed to check the configuration of stream plugin [mqtt-proxy]: property \"upstream\" validation failed: value should match only one schema, but matches none"}
```
- 只能支持设置一个mqtt 代理吗?
```
"upstream": {
      "host": "127.0.0.1",
      "port": 1980
  }
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@siaron See http://apisix.apache.org/docs/apisix/plugins/mqtt-proxy/ for details. PR's welcome to extend it.

**Comment by siaron** [comment]
> @siaron See http://apisix.apache.org/docs/apisix/plugins/mqtt-proxy/ for details. PR's welcome to extend it.

我现在有两个基于tcp的应用. 
一个是netty写的.
一个mqtt broker. 
我能用两个不同的apisix端口代理这两个应用吗?  
   ...
    router:
        http: 'radixtree_uri'
        ssl: 'radixtree_sni'
    stream_proxy:                 # TCP/UDP proxy
      tcp:                        # TCP proxy port list
        - 9100
        - 9200
    dns_resolver:
    ...
怎么9100 和netty的绑定. 9200和mqtt broker绑定. netty 和mqtt broker 是多节点. 负载均衡访问.

**Comment by tokers** [comment]
> > @siaron See http://apisix.apache.org/docs/apisix/plugins/mqtt-proxy/ for details. PR's welcome to extend it.
> 
> 我现在有两个基于tcp的应用.
> 一个是netty写的.
> 一个mqtt broker.
> 我能用两个不同的apisix端口代理这两个应用吗?
> ...
> router:
> http: 'radixtree_uri'
> ssl: 'radixtree_sni'
> stream_proxy: # TCP/UDP proxy
> tcp: # TCP proxy port list
> - 9100
> - 9200
> dns_resolver:
> ...
> 怎么9100 和netty的绑定. 9200和mqtt broker绑定. netty 和mqtt broker 是多节点. 负载均衡访问.

See http://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-9, you can use `server_port` as one of the route match conditions.

**Comment by spacewander** [comment]
Consider solved
