### ISSUE TITLE
docs: https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/global-rule.md

### ISSUE THREAD

**Issue by Hxhong** [apache/apisix#4895]
### Improved or typo fixed.

![image](https://user-images.githubusercontent.com/42258295/130762616-19ee95a8-ad91-47b7-bab1-e5087a8a4687.png)
![image](https://user-images.githubusercontent.com/42258295/130762632-5aa97fc6-2de6-4a20-a8b7-eefffa1d885d.png)
Global rule doc may mistakenly define the scope of plugin.

### Solution

Please correct global rule doc.

**Comment by zaunist** [comment]
Hi, community. I update the `global-rule` description, please take a look here https://github.com/apache/apisix/pull/5739
