### ISSUE TITLE
request help: the problem with the response-rewrite plugin

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#4905]
### Issue description

As we all know, due to openResty, body_filter_by_lua* may be called multiple times in a single request, but response-rewrite plugin will Interrupt request on the body_filter_by_lua*  first by called, The subsequent process will not be requested.  the code is as follows

https://github.com/apache/apisix/blob/master/apisix/plugins/response-rewrite.lua#L137

 I think it will be better to merge the result of calling body_filter_by_lua* for many times and finally replace it with the configured body, what do you think? @spacewander 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
if you modify the response body in `body_filter_by_lua`, it means that you don't care what the upstream return, so why we need to wait for the upstream response? Can you give a convincing scenario?
