### ISSUE TITLE
bug: 创建一个使用jwt插件的consumer后，马上去创建jwt会报未找到consumer的404错误

### ISSUE THREAD

**Issue by liumoji** [apache/apisix#4911]
### Issue description

创建一个使用jwt插件的consumer后，马上去创建jwt会报未找到consumer的404错误
![image](https://user-images.githubusercontent.com/49864384/131088824-48a4f2ab-2298-430e-8b95-a2157b6648e1.png)

因为apisix对应逻辑日志打印的覆盖度不足，因此在源代码上做了相关打印消息，如图
![image](https://user-images.githubusercontent.com/49864384/131089996-4918fb17-2633-4a1c-8320-8c1afef115d4.png)
增加了错误码的区分，原来都是404，不太好定位

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.先创建一个使用jwt插件的consumer
2.申请其对应的jwt
3.有概率会报无法获取consumer

### Actual result

![image](https://user-images.githubusercontent.com/49864384/131088919-55e88a06-3960-4588-923a-b6b286c605f3.png)

创建consumer成功后，申请jwt报无法找到对应的consumer

### Error log

![Uploading image.png…]()

### Expected result

创建consumer成功后马上可以申请对应的jwt

**Comment by tokers** [comment]
How long is the time window between the consumer was created and you try to apply a JWT token?

**Comment by liumoji** [comment]
我的操作流程大概是这样的：
1.创建一个使用JWT插件的consumer；
2.收到创建成功响应后，马上用这个consumer 的key 去申请一个JWT，这个时候就会概率性的发生找不到consumer key的报错
间隔时间就是收到创建consumer成功后马上请求的，估计几毫秒吧

**Comment by tokers** [comment]
> 我的操作流程大概是这样的：
> 1.创建一个使用JWT插件的consumer；
> 2.收到创建成功响应后，马上用这个consumer 的key 去申请一个JWT，这个时候就会概率性的发生找不到consumer key的报错
> 间隔时间就是收到创建consumer成功后马上请求的，估计几毫秒吧

You should wait for a while as APISIX instances have to wait for the configuration to be propagated from ETCD.

**Comment by liumoji** [comment]
![image](https://user-images.githubusercontent.com/49864384/131273756-395bcb2c-3c02-46d1-9653-affb1c3e2762.png)
通过看源码在这块创建好consumer，存到etcd中，然后在请求jwt的api，在这块报错的，说找不到consumers_key
![image](https://user-images.githubusercontent.com/49864384/131273954-9c331834-161f-42f4-8dbb-a0507ecc3b5e.png)

**Comment by liumoji** [comment]
曾经设置了500毫秒的延迟请求，就是创建consumer后延时500毫秒，还是会概率的报这个错，提高到1秒浮现的概率会小一点，能不能做下类似的优化，就是等etcd返回了，在返回成功这样，因为在实际应用中，比如一个客户端注册逻辑，需要为其创建consumer，然后分配一个jwt来鉴权访问，如果中间流程延时过久，会造成不太好的用户体验，以上是在使用过程中的遇到的一点点现象，感谢你们的解答

**Comment by tokers** [comment]
> 曾经设置了500毫秒的延迟请求，就是创建consumer后延时500毫秒，还是会概率的报这个错，提高到1秒浮现的概率会小一点，能不能做下类似的优化，就是等etcd返回了，在返回成功这样，因为在实际应用中，比如一个客户端注册逻辑，需要为其创建consumer，然后分配一个jwt来鉴权访问，如果中间流程延时过久，会造成不太好的用户体验，以上是在使用过程中的遇到的一点点现象，感谢你们的解答

Currently, the waiting mechanism is not supported yet. You may use the HTTP long poll to mimic it.

**Comment by liumoji** [comment]
感谢支持

**Comment by mamalianggf** [comment]
Is it polling this interface?
![image](https://user-images.githubusercontent.com/48015924/140692609-e368f609-fa7b-4fa6-a91e-a665bbf1fb97.png)

**Comment by mamalianggf** [comment]
> > 曾经设置了500毫秒的延迟请求，就是创建consumer后延时500毫秒，还是会概率的报这个错，提高到1秒浮现的概率会小一点，能不能做下类似的优化，就是等etcd返回了，在返回成功这样，因为在实际应用中，比如一个客户端注册逻辑，需要为其创建consumer，然后分配一个jwt来鉴权访问，如果中间流程延时过久，会造成不太好的用户体验，以上是在使用过程中的遇到的一点点现象，感谢你们的解答
> 
> Currently, the waiting mechanism is not supported yet. You may use the HTTP long poll to mimic it.

Is it polling this interface?
![image](https://user-images.githubusercontent.com/48015924/140692921-c8c20718-7bb4-457b-992b-86ab4e310130.png)
