### ISSUE TITLE
bug: api-breaker is not getting expected/configured  response status

### ISSUE THREAD

**Issue by pawarJayesh8511** [apache/apisix#4924]
### Issue description

I have configured the following route, wherein 
1. if the upstream  is down i.e it either returns 500 or 502 or 503 then APISIX should return status  as 507. But, it is not happening like that.
2. if the upstream is not down, but, it throws the error with 500 status then also, it should give the same status code as 507.
But, in both above cases, it is not working as expected.

Route:

{
            "key":"\/apisix\/routes\/370045865856862098",
            "createdIndex":1731,
            "modifiedIndex":1738,
            "value":{
               "id":"370045865856862098",
               "upstream_id":"369094337344046994",
               "update_time":1630094440,
               "name":"apibreaker",
               "status":1,
               "uris":[
                  "\/api\/breaker"
               ],
               "create_time":1630094123,
               "methods":[
                  "GET",
                  "POST",
                  "PUT",
                  "DELETE",
                  "PATCH",
                  "HEAD",
                  "OPTIONS",
                  "CONNECT",
                  "TRACE"
               ],
               "plugins":{
                  "api-breaker":{
                     "disable":false,
                     "max_breaker_sec":5,
                     "unhealthy":{
                        "http_statuses":[
                           503,
                           500,
                           502
                        ],
                        "failures":3
                     },
                     "healthy":{
                        "successes":3,
                        "http_statuses":[
                           200
                        ]
                     },
                     "break_response_code":507
                  }
               }
            }
         }

Response from upstream:

curl -X GET -i  http://xxx.xxx.xx.1:9282/api/breaker

Output
HTTP/1.1 500 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 29 Aug 2021 15:27:02 GMT
Connection: close

{"timestamp":"2021-08-29T15:27:02.474+0000","status":500,"error":"Internal Server Error","message":"something went wrong","path":"/api/breaker"}

Response from APISIX gateway:
 
curl -X GET -i  http://127.0.0.1:9080/api/breaker
Output
HTTP/1.1 500 
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Date: Sun, 29 Aug 2021 15:33:21 GMT
Server: APISIX/2.8
X-APISIX-Upstream-Status: 500

{"timestamp":"2021-08-29T15:33:21.121+0000","status":500,"error":"Internal Server Error","message":"something went wrong","path":"/api/breaker"}

Response is not giving 507 status code.

### Environment

- apisix version (cmd: apisix version): 2.8

- OS (cmd: uname -a): Linux my-machine 5.11.0-27-generic

- conf: removed user resty and add server header. #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- OpenResty / Nginx version (cmd: nginx -V or openresty -V): nginx version: openresty/1.19.9.1

- etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API): 3.4.0

- apisix-dashboard version, if have: 2.7

- luarocks version, if the issue is about installation (cmd: luarocks --version): 3.4.0

### Steps to reproduce

I followed the steps in the https://apisix.apache.org/docs/apisix/plugins/api-breaker 
and, the route is:
{
            "key":"\/apisix\/routes\/370045865856862098",
            "createdIndex":1731,
            "modifiedIndex":1738,
            "value":{
               "id":"370045865856862098",
               "upstream_id":"369094337344046994",
               "update_time":1630094440,
               "name":"apibreaker",
               "status":1,
               "uris":[
                  "\/api\/breaker"
               ],
               "create_time":1630094123,
               "methods":[
                  "GET",
                  "POST",
                  "PUT",
                  "DELETE",
                  "PATCH",
                  "HEAD",
                  "OPTIONS",
                  "CONNECT",
                  "TRACE"
               ],
               "plugins":{
                  "api-breaker":{
                     "disable":false,
                     "max_breaker_sec":5,
                     "unhealthy":{
                        "http_statuses":[
                           503,
                           500,
                           502
                        ],
                        "failures":3
                     },
                     "healthy":{
                        "successes":3,
                        "http_statuses":[
                           200
                        ]
                     },
                     "break_response_code":507
                  }
               }
            }
         }

### Actual result

Response from upstream:

curl -X GET -i  http://xxx.xxx.xx.1:9282/api/breaker

Output
HTTP/1.1 500 
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sun, 29 Aug 2021 15:27:02 GMT
Connection: close

{"timestamp":"2021-08-29T15:27:02.474+0000","status":500,"error":"Internal Server Error","message":"something went wrong","path":"/api/breaker"}

Response from APISIX gateway:
 
curl -X GET -i  http://127.0.0.1:9080/api/breaker
Output
HTTP/1.1 500 
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Date: Sun, 29 Aug 2021 15:33:21 GMT
Server: APISIX/2.8
X-APISIX-Upstream-Status: 500

{"timestamp":"2021-08-29T15:33:21.121+0000","status":500,"error":"Internal Server Error","message":"something went wrong","path":"/api/breaker"}

Response is not giving 507 status code.

### Error log

2021/08/29 20:44:58 [error] 6062#6062: *212114 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/breaker HTTP/1.1", upstream: "http://xxx.xxx.xx.1:9282/api/breaker", host: "127.0.0.1:9080"
2021/08/29 20:47:40 [error] 6061#6061: *220460 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/breaker HTTP/1.1", upstream: "http://xxx.xxx.xx.1:9282/api/breaker", host: "127.0.0.1:9080"
2021/08/29 20:50:49 [error] 6062#6062: *230180 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/breaker HTTP/1.1", upstream: "http://xxx.xxx.xxx.1:9282/api/breaker", host: "127.0.0.1:9080"

### Expected result

Response from APISIX gateway:
 
curl -X GET -i  http://127.0.0.1:9080/api/breaker
Output
HTTP/1.1 507 
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Date: Sun, 29 Aug 2021 15:33:21 GMT
Server: APISIX/2.8
X-APISIX-Upstream-Status: 507

{"timestamp":"2021-08-29T15:33:21.121+0000","status":500,"error":"Internal Server Error","message":"something went wrong","path":"/api/breaker"}

Response is should give 507 status code.

**Comment by tokers** [comment]
How many times did you send requests to APISIX? As per your configuration, the threshold of the `api-breaker` plugin is `3`.

**Comment by pawarJayesh8511** [comment]
Thanks for responding. Now, after 3 retries, it worked but I not sure about successful case.
It always giving me successful response irrespective of number of retries for success status.
Need to understand the working of it and let me know how to reproduce this usecase of successful.

Note: I followed this from the document https://apisix.apache.org/docs/apisix/plugins/api-breaker 

"In an unhealthy state, when a request is forwarded to an upstream service and the status code in the healthy.http_statuses configuration is returned (e.g., 200) that healthy.successes is reached (e.g., three times), and the upstream service is considered healthy again."

**Comment by tokers** [comment]
How did you test for the successful cases?

**Comment by pawarJayesh8511** [comment]
@tokers : 
Step1 : Unhealthy test : It gave me 500 error
Step 2:  Then, upstream is running. 
Step 3:  I tried with curl as follows:
 
curl -X GET -i http://127.0.0.1:9080/api/breaker

This endpoint is for breaker plugin testing

Thus, in short, even if upstream is up and running, it should not get this response for 3 times. But, it giving the output very first time, I make the upstream running.

**Comment by tokers** [comment]
> @tokers :
> Step1 : Unhealthy test : It gave me 500 error
> Step 2: Then, upstream is running.
> Step 3: I tried with curl as follows:
> 
> curl -X GET -i http://127.0.0.1:9080/api/breaker
> 
> This endpoint is for breaker plugin testing
> 
> Thus, in short, even if upstream is up and running, it should not get this response for 3 times. But, it giving the output very first time, I make the upstream running.

Not sure whether I understood your meanings but how many times you sent requests in step 1? we should make sure the upstream was marked as unhealthy before we tried to test the heal.

**Comment by pawarJayesh8511** [comment]
@tokers : In step 1, I tried 4 to 5  times failure, it gave me 507, which I had configured in the above route.
And, then in I have made upstream running, I again hit the curl, so it gave me  this response.

curl -X GET -i http://127.0.0.1:9080/api/breaker

This endpoint is for breaker plugin testing
