### ISSUE TITLE
request help: Integration of eureka as discovery registry fail

### ISSUE THREAD

**Issue by mangoGoForward** [apache/apisix#4929]
### Issue description

When start APISIX, I got some error logs
`
2021/08/30 10:33:22 [error] 6232#3458399: *14278 [lua] eureka.lua:197: invalid response body: ��Sێ�0��G��򴔠
��EKQ�
M큸8vd;l���qBv�jժUϜ9�9s�� ϕ��юM��	�߻�@�MY��E�\ʍ@
n׻xW'�r6���4d!��>.�f���y��dsX
�hY�)��4��amM�E��q~U��
J���τ���Qԥ'L@�}᪛��ИV
�z�_ݭ��(��-6w��6�E
��[{[ ;����9���{P�BrSho�0s�f<�Q{�K�7���+p��d�F�W�gDI�G�F1:��C�|rM�n4�/�t�6�5>�Z�)�7ȩ[������&�x�����2Cj����M�����ͤ7���cM�4�ތF����$��n�R����xBd�!u%�8ATx���Q
+j�Zd�/�!s�h��)�k^���p��UO�ϧ��MU-��b��)���#(��S���Ky(%�Sml��@����&��s����+���C"N/7$:�ƾ���9I��5��-_`���|4���竗\�A�Y�,v�F��ĵk�\ err: Expected value but found invalid token at character 1, context: ngx.timer
`

eureka server start on tomcat, I set tomcat conf.server.xml character encoding to "UTF-8"
```
<Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               redirectPort="8443" URIEncoding="UTF-8" />
```

 I got correct response via curl or use chrome to visit "http://localhost:8080/eureka/v2/apps"
```
 $ curl --compressed  -i -X GET "http://localhost:8080/eureka/v2/apps" -H "Accept: application/json"
HTTP/1.1 200 
Content-Encoding: gzip
Vary: Accept-Encoding
Content-Type: application/json
Content-Length: 554
Date: Mon, 30 Aug 2021 06:15:18 GMT

{"applications":{"versions__delta":"1","apps__hashcode":"UP_1_","application":[{"name":"EUREKA","instance":[{"instanceId":"niyaoaidaodeMacBook-Pro.local","hostName":"niyaoaidaodeMacBook-Pro.local","app":"EUREKA","ipAddr":"127.0.0.1","status":"UP","overriddenStatus":"UNKNOWN","port":{"$":8080,"@enabled":"true"},"securePort":{"$":443,"@enabled":"false"},"countryId":1,"dataCenterInfo":{"@class":"com.netflix.appinfo.InstanceInfo$DefaultDataCenterInfo","name":"MyOwn"},"leaseInfo":{"renewalIntervalInSecs":30,"durationInSecs":90,"registrationTimestamp":1630303157467,"lastRenewalTimestamp":1630304120244,"evictionTimestamp":0,"serviceUpTimestamp":1630303156998},"metadata":{"@class":"java.util.Collections$EmptyMap"},"appGroupName":"UNKNOWN","homePageUrl":"http://niyaoaidaodeMacBook-Pro.local:8080/","statusPageUrl":"http://niyaoaidaodeMacBook-Pro.local:8080/Status","healthCheckUrl":"http://niyaoaidaodeMacBook-Pro.local:8080/healthcheck","vipAddress":"eureka.mydomain.net","isCoordinatingDiscoveryServer":"true","lastUpdatedTimestamp":"1630303157467","lastDirtyTimestamp":"1630303156955","actionType":"ADDED"}]}]}}
```

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):Darwin niyaoaidaodeMacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May 8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):{"version":"2.9","last_report_time":1630291416,"boot_time":1630291297,"etcd_version":"3.5.0","up_time":153,"hostname":"niyaoaidaodeMacBook-Pro.local","id":"f13398f9-bed6-44f1-9ad4-50c9d73401bb"}
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):usr/local/bin/luarocks 3.7.0

**Comment by tzssangglass** [comment]
see https://github.com/Netflix/eureka/wiki/Eureka-REST-operations

I think it may be that eureka is returning data in application/xml format. however, apisix explicitly uses https://github.com/apache/apisix/blob/f8eac5e725edd7323ee7b1f7be05b3fbc080fe70/apisix/discovery/eureka.lua#L104 

as header.

**Comment by tokers** [comment]
It seems that Eureka returned compressed data? While APISIX cannot unzip it.

**Comment by mangoGoForward** [comment]
> It seems that Eureka returned compressed data? While APISIX cannot unzip it.

I try to use lua-zlib to unzip response, but can not decode also

**Comment by tokers** [comment]
> > It seems that Eureka returned compressed data? While APISIX cannot unzip it.
> 
> I try to use lua-zlib to unzip response, but can not decode also

Any errors thrown?

**Comment by mangoGoForward** [comment]
> see https://github.com/Netflix/eureka/wiki/Eureka-REST-operations
> 
> I think it may be that eureka is returning data in application/xml format. however, apisix explicitly uses
> 
> https://github.com/apache/apisix/blob/f8eac5e725edd7323ee7b1f7be05b3fbc080fe70/apisix/discovery/eureka.lua#L104
> 
> as header.

I do not know whether The "Accept" header in eureka.lua does it work

**Comment by mangoGoForward** [comment]
> > > It seems that Eureka returned compressed data? While APISIX cannot unzip it.
> > 
> > 
> > I try to use lua-zlib to unzip response, but can not decode also
> 
> Any errors thrown?

```
local res_body = res.body
local unzip_data = zlib.inflate(res_body)
```
the type of unzip_data is userdata

**Comment by tokers** [comment]
> > > > It seems that Eureka returned compressed data? While APISIX cannot unzip it.
> 
> > > 
> 
> > > 
> 
> > > I try to use lua-zlib to unzip response, but can not decode also
> 
> > 
> 
> > Any errors thrown?
> 
> 
> 
> ```
> 
> local res_body = res.body
> 
> local unzip_data = zlib.inflate(res_body)
> 
> ```
> 
> the type of unzip_data is userdata


Any error logs？ information from these two lines is less.

**Comment by mangoGoForward** [comment]
> > the type of unzip_data is userdata
> 
> Any error logs？ information from these two lines is less.

When I use zlib.inflate to unzip the response, it return a userdata type, so it thrown bad argument when use json decode
```
local data, err = core.json.decode(unzip_data)
if not data then
    log.error("invalid response body: ", type(unzip_data), " err: ", err)
    return
end
```
I don't known how to process the data, can you help me? There is a problem when process the Eureka's returned data

**Comment by tokers** [comment]
> > > the type of unzip_data is userdata
> > 
> > 
> > Any error logs？ information from these two lines is less.
> 
> When I use zlib.inflate to unzip the response, it return a userdata type, so it thrown bad argument when use json decode
> 
> ```
> local data, err = core.json.decode(unzip_data)
> if not data then
>     log.error("invalid response body: ", type(unzip_data), " err: ", err)
>     return
> end
> ```
> 
> The error log:
> `2021/08/31 09:29:35 [error] 12663#3713017: *80 [lua] eureka.lua:197: invalid response body err: bad argument #1 to '?' (string expected, got userdata), context: ngx.timer`
> I don't known how to process the data, can you help me? There is a problem when process the Eureka's returned data

See https://github.com/brimworks/lua-zlib/blob/master/README#L92 for details about how to use the lua zlib.

And, welcome to submit a PR to help APISIX to handle the compressed data from Eureka :)

**Comment by mangoGoForward** [comment]
> See https://github.com/brimworks/lua-zlib/blob/master/README#L92 for details about how to use the lua zlib.
> 
> And, welcome to submit a PR to help APISIX to handle the compressed data from Eureka :)

I submit a PR to handle the compressed data from Eureka, can you help me to review this code #4956
