### ISSUE TITLE
request help: How to install Apache APISIX 2.9 on Mac M1

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#4945]
### Issue description

Hi, when I try to install Apache APISIX 2.9 on Mac (M1) accoding to those links[1][2], it failed due to reasons below:

```sh
lualogging 1.5.2-1 depends on luasocket (3.0rc1-2 installed)
lualogging 1.5.2-1 is now installed in /Users/juzhiyuan/workspace/apisix-2.9/apache-apisix-2.9-src/deps (license: MIT/X11)

casbin 1.26.0-1 depends on lrexlib-pcre >= 2.9.1 (not installed)
Installing https://luarocks.org/lrexlib-pcre-2.9.1-1.src.rock

Error: Failed installing dependency: https://luarocks.org/casbin-1.26.0-1.rockspec - Failed installing dependency: https://luarocks.org/lrexlib-pcre-2.9.1-1.src.rock - Could not find header file for PCRE
  No file pcre.h in /usr/local/include
  No file pcre.h in /usr/include
  No file pcre.h in /include
You may have to install PCRE in your system and/or pass PCRE_DIR or PCRE_INCDIR to the luarocks command.
Example: luarocks install lrexlib-pcre PCRE_DIR=/usr/local
make: *** [deps] Error 1
```

When I try to install `pcre-devrel`, it shows

```
brew install pcre-devel

Warning: No available formula or cask with the name "pcre-devel".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

[1] https://apisix.apache.org/docs/apisix/how-to-build/#installation-via-source-release-package
[2] https://github.com/apache/apisix/issues/4772

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): Darwin bogon 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): None
- apisix-dashboard version, if have: None
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): /opt/homebrew/bin/luarocks 3.7.0

**Comment by spacewander** [comment]
Have you tried `brew install pcre`?
See https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md#mac-osx

**Comment by hsluoyz** [comment]
@rushitote

**Comment by juzhiyuan** [comment]
Yes, I have followed the instructions https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md#mac-osx

**Comment by juzhiyuan** [comment]
Yes, I have followed the instructions https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md#mac-osx

**Comment by iSuperCoder** [comment]
Why don't you  use Docker? Try it, very simple!

**Comment by juzhiyuan** [comment]
I'd like to build it from Source, and make some changes. 😄

**Comment by tzssangglass** [comment]
after `brew install pcre`, I do something ad below

1. find the `pcre` install dir, on Mac M1, usually in `/opt/homebrew/Cellar/pcre/8.45/`
2. modify the `~/.luarocks/config-5.1.lua` as 

```
lua_interpreter = "luajit"
variables = {
   OPENSSL_INCDIR = "/opt/homebrew/opt/openresty-openssl111/include",
   OPENSSL_LIBDIR = "/opt/homebrew/opt/openresty-openssl111/lib",
   PCRE_DIR = "/opt/homebrew/Cellar/pcre/8.45",
   PCRE_INCDIR = "/opt/homebrew/Cellar/pcre/8.45/include"
}
```

**Comment by spacewander** [comment]
Could we add this to:
https://github.com/apache/apisix/blob/b7c1b5e8ce91323b14f80db8bdb4b63ca37bd6ef/Makefile#L38

Note: need a way to check pcre version instead of hardcoded 8.45

**Comment by tzssangglass** [comment]
relate to this commit: https://github.com/tzssangglass/apisix-build-tools/commit/a725224c604e7971c9e5b4e2326f20f90904347c

**Comment by Chever-John** [comment]
I just solved the problem.
The first thing you need to know is that `brew`'s location in M1 Macos has been changed and is currently in `/opt/homebrew/cellar/`. 
So you should configure your files like this:
```
cheverjohn@Johns-MacBook-Pro apisix % cat ~/.luarocks/config-5.1.lua
variables = {
   LDAP_DIR = "/opt/homebrew/cellar/openldap/2.6.1",
   LDAP_INCDIR = "/opt/homebrew/cellar/openldap/2.6.1/include",
   OPENSSL_INCDIR = "/opt/homebrew/opt/openresty-openssl111/include",
   OPENSSL_LIBDIR = "/opt/homebrew/opt/openresty-openssl111/lib",
   PCRE_DIR = "/opt/homebrew/cellar/pcre/8.45",
   PCRE_INCDIR = "/opt/homebrew/cellar/pcre/8.45/include"
}
```

Then it works!

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.

**Comment by tzssangglass** [comment]
> have the same problem on centos 7

Please refer here: https://github.com/apache/apisix/issues/4945#issuecomment-909850338

**Comment by Chever-John** [comment]
@butterfly1924 Also you can refer to this [link](https://apisix.apache.org/docs/apisix/how-to-build/#:~:text=The%20following%20is%20the%20solution%20of%20macOS%2C%20which%20is%20similar%20to%20that%20of%20other%20operating%20systems%3A)
