### ISSUE TITLE
request help: Mac安装部署报错，Error: Lua interpreter not found at /opt/lua@5.1

### ISSUE THREAD

**Issue by winnetcn** [apache/apisix#4958]
### Issue description

Claire@viplink apigw % make deps

mkdir -p ~/.luarocks
luarocks --lua-dir=/opt/lua@5.1 config --local variables.OPENSSL_LIBDIR /usr/local/Cellar/openresty/1.19.9.1_2/openssl/lib

Error: Lua interpreter not found at /opt/lua@5.1

You may want to specify a different Lua version with --lua-version

make: *** [deps] Error 1
Claire@viplink apigw %

Claire@viplink apigw % lua -v
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio

![image](https://user-images.githubusercontent.com/24367948/131629901-bbebc91b-8b4f-4116-a227-16b510ce3242.png)

### Environment

- apisix version (cmd: `apisix version`): 2.6
- OS (cmd: `uname -a`): Darwin viplink.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
- luarocks --version
/usr/local/bin/luarocks 3.7.0
LuaRocks main command-line interface

**Comment by mangoGoForward** [comment]
where your lua installed, It shows Lua interpreter not found at /opt/lua@5.1. if use homebrew installed, HOMEBREW_PREFIX is /usr/local

**Comment by winnetcn** [comment]
> where your lua installed, It shows Lua interpreter not found at /opt/lua@5.1. if use homebrew installed, HOMEBREW_PREFIX is /usr/local

感谢回复，apisix为什么默认把lua放在/opt下？

**Comment by tzssangglass** [comment]
> > where your lua installed, It shows Lua interpreter not found at /opt/lua@5.1. if use homebrew installed, HOMEBREW_PREFIX is /usr/local
> 
> 感谢回复，apisix为什么默认把lua放在/opt下？

for Mac M1, the default `HOMEBREW_PREFIX` has changed to `/opt/homebrew`, see: https://github.com/Homebrew/install/pull/373/files#diff-043df5bdbf6639d7a77e1d44c5226fd7371e5259a1e4df3a0dd5d64c30dca44fR21-R24

**Comment by tzssangglass** [comment]
> 感谢回复，apisix为什么默认把lua放在/opt下？

APISIX does not put it under `/opt` by default, maybe your HOMEBREW_PREFIX is not set. see https://github.com/apache/apisix/blob/b7c1b5e8ce91323b14f80db8bdb4b63ca37bd6ef/Makefile#L41

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
