### ISSUE TITLE
request help: healthcheck plugin can support  passive checks alone ?

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix#4959]
### Issue description

healthcheck plugin can support  passive checks alone?  like nginx upstream processing method. After exceeding the set failure threshold(max_fails), the node is removed, **after a period of time, try again**.

relate issue: https://github.com/apache/apisix-ingress-controller/issues/632

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
> After exceeding the set failure threshold(max_fails), the node is removed, **after a period of time, try again**.

I think active health checks can do this

**Comment by Donghui0** [comment]
> > After exceeding the set failure threshold(max_fails), the node is removed, **after a period of time, try again**.
> 
> I think active health checks can do this

When there are many endpoint nodes, such as between 300 and 500. And when the number of k8s services is relatively large, active check will have higher CPU consumption.

**Comment by tzssangglass** [comment]
not supported yet.

but I think it's a very useful feature, my initial ideas are as below:

1. only passive health checks are enabled by default
2. passive health check finds that the upstream node has failed and marks the node as unhealthy
3. enable active health checks to probe unhealthy nodes
4. once an unhealthy node is found to be recovered by active health checks, mark the node as healthy and stop active health checks on this node

can you send an email to discuss this at dev@apisix.apache.org ?
