### ISSUE TITLE
docs: Improved hmac-auth plugin signature string generation instructions

### ISSUE THREAD

**Issue by caixiaomao** [apache/apisix#4962]
### Improved or typo fixed.

When a signature string is generated, an empty string must be wrapped, even if there is no signature information. Otherwise, authentication fails. This needs to be addressed when generating the signature string

### Solution

Add the corresponding description to the sample document that generates the sample signature string

**Comment by tzssangglass** [comment]
hi @caixiaomao , Can you paste the link or picture to the error?

**Comment by caixiaomao** [comment]
It's not a bug, it's documentation that needs fixing。
In the **Signature string splicing example**
The `signing_string` generated according to the `signature generation formula` is:

```plain
"GET
/index.html
age=36&name=james
user-key
Tue, 19 Jan 2021 11:33:20 GMT
User-Agent:curl/7.29.0
x-custom-a:test
"
```

If there is no date or canonical_query_string, The string that needs to be encrypted should look like this, and the documentation should complement this

```plain
"GET
/index.html

user-key

User-Agent:curl/7.29.0
x-custom-a:test
"
```
