### ISSUE TITLE
request help: how to config a default Site certificate

### ISSUE THREAD

**Issue by mamalianggf** [apache/apisix#4968]
### Issue description

I want to config a default Site certificate that ignore domain etc to all router.then i can visit route via https.I can't find a Configuration items that can achieve my goal.Hope your help,thanks

### Environment

- apisix version:2.9
- OS:ubuntu1804
- OpenResty / Nginx version : openresty/1.19.3.1
- etcd version:3.4.15

**Comment by tokers** [comment]
Currently, it's not possible to configure a default TLS certificate as APISIX always tried to match the SNI from a client with the ones in SSL objects.

However, if the Host/SNI of all your clients have the same suffix, you may prepare a corresponding wildcard certificate.

**Comment by mamalianggf** [comment]
ok,thanks
