### ISSUE TITLE
Why doesn't apisix have the function of Vhost?

### ISSUE THREAD

**Issue by xshans** [apache/apisix#4973]
# Feature request

Why doesn't apisix have the function of Vhost?

**Comment by RocFang** [comment]
apisix's router supply a more dynamic method than nginx's vhost.
but if you insist on configuring some static vhosts, just add the config to the config template, just like a regular nginx configuration.

**Comment by xshans** [comment]
can help me?
configure the 9000 port routing of apisix as apisix.xx.com to visit
401 Authorization Required
