### ISSUE TITLE
docs: need to update the doc about `discovery_type` of `upstream`

### ISSUE THREAD

**Issue by membphis** [apache/apisix#4981]
### Improved or typo fixed.

![image](https://user-images.githubusercontent.com/6814606/132088887-b19f4085-9371-4f49-983f-f622c49fabc4.png)

it shows we only support `eureka`.

### Solution

we have supported:

![image](https://user-images.githubusercontent.com/6814606/132088922-ca5cddfb-59e2-42be-bbac-8c2eda222863.png)

**Comment by AleenaSA** [comment]
Hi, you could assign this to me!

**Comment by RAMESSESII2** [comment]
Hope this is what you meant @membphis.

**Comment by RAMESSESII2** [comment]
![tmep](https://user-images.githubusercontent.com/54385449/132127431-65a9a1bd-354e-46c9-8425-cbb068437219.png)

**Comment by satyaarthchhabra** [comment]
Hi @RAMESSESII2 are you still working on this issue

**Comment by RAMESSESII2** [comment]
> Hi @RAMESSESII2 are you still working on this issue

nope, not assigned, go ahead.

**Comment by spacewander** [comment]
Look like we don't need it actually?
This `eureka` is under the example column. It is just an example, doesn't mean we only support eureka.
