### ISSUE TITLE
feat: add cache verification tool for APISIX

### ISSUE THREAD

**Issue by RedemptionC** [apache/apisix#4994]
### Issue description

Hi,community,I plan to add a cache verification tool for APISIX
Also,this is a subtask of [an open summer 2021 project](https://summer.iscas.ac.cn/#/org/prodetail/210050252?lang=en)
> there are 2 part in this projct,the other one is for the dashboard,I have submitted a [PR](https://github.com/apache/apisix-dashboard/pull/2065) for that
the dashboard part is  almost finished,and it will be nice of you to give a code review or advice so I can make it ready to be merged ASAP

what the tool does is to verify that config items in APISIX cache are the same as those in ETCD
as @nic-chen says,it will be useful for debugging

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):ubuntu 20.04 LTS
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.13
- apisix-dashboard version, if have: 2.7.1
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4.0

**Comment by RedemptionC** [comment]
@nic-chen 
as the project detail suggests,we need to add a command line tool for APISIX
is it that we need to make something like `make cache-verify`?

**Comment by spacewander** [comment]
Since you want to get the state from a live APISIX process, you may need to add some APIs to expose synced data via https://github.com/apache/apisix/blob/master/docs/en/latest/control-api.md#get-v1healthcheck

**Comment by nic-chen** [comment]
@RedemptionC 

As @spacewander said, you could expose data through the Control API.

Btw, you should do some research, and rewrite a proposal, then others could give you advice.

**Comment by RedemptionC** [comment]
@spacewander 
thank you
BTW,I wonder why there isn't a Chinese version of control-api.md?
will a Chinese version be accepted by the community?(via PR)If yes,I'd like to give a try

**Comment by RedemptionC** [comment]
@nic-chen 
thanks 
I'll do that
