### ISSUE TITLE
help: jwt-auth 是否由主动销毁已生成 token的功能？

### ISSUE THREAD

**Issue by fmcodeing** [apache/apisix#4999]
### Issue description

jwt-auth 是否由主动销毁已生成 token的功能？

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

jwt-auth 是否由主动销毁已生成 token的功能？

### Actual result

jwt-auth 是否由主动销毁已生成 token的功能？

### Error log

jwt-auth 是否由主动销毁已生成 token的功能？

**Comment by tzssangglass** [comment]
`jwt` is stateless, as specified by the protocol itself.
