### ISSUE TITLE
docs: move 'start etcd server' from install-dependency.md to how-to-build.md

### ISSUE THREAD

**Issue by RedemptionC** [apache/apisix#5007]
### Improved or typo fixed.

IMO,we need to start etcd everytime we run APISIX,not only after we install dependencies
so these lines should be in [how-to-build.md](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md) rather than [install-dependency.md](https://github.com/apache/apisix/blob/master/docs/en/latest/install-dependencies.md) 
```
# start etcd server
nohup etcd &
```

### Solution

move 'start etcd server' from install-dependency.md to how-to-build.md

**Comment by spacewander** [comment]
No. The etcd is dependency, not part of APISIX.
