### ISSUE TITLE
plugin-interceptors does not work

### ISSUE THREAD

**Issue by wjmmjr** [apache/apisix#5015]
### Issue description

根据apisix文档设置plugin-interceptors不生效
文档链接：https://www.bookstack.cn/read/apisix-2.7-zh/plugin-interceptors.md#eidwhu
**错误如下：**
开启ip-restriction全局插件情况下：
![cd8d01eac27d1f8b799c6a602d0ff63](https://user-images.githubusercontent.com/18857921/132473902-395e9324-227f-48f0-803d-b9376f94ddaa.png)
不开启ip-restriction全局插件情况下：
![image](https://user-images.githubusercontent.com/18857921/132474127-6fb9b789-1086-4ae1-9ce4-0371a4ea283d.png)
当前地址没问题，是可用的：
![44374807bb9c9489a0d0cb662a643a7](https://user-images.githubusercontent.com/18857921/132474284-1cd8bfee-7e3c-4f56-a435-563a4a69f879.png)
那如何修改能解决问题？

### Environment

Environment：K8S，apisix-2.7
![image](https://user-images.githubusercontent.com/18857921/132474562-fd4d4c93-c3fb-4c2c-8c3d-61586751762d.png)

**Comment by Zheaoli** [comment]
Would you mind to tell us with version of APISIX you use?

**Comment by tzssangglass** [comment]
the CIDR in whitelist check the IP of client, not the IP of APISIX, so your example is invalid.

if you deploy APISIX in k8s, I think the client ip that APISIX sees is the ip of the k8s gateway?

similar as https://github.com/apache/apisix/issues/4485, https://github.com/apache/apisix/issues/4767

**Comment by tokers** [comment]
> the CIDR in whitelist check the IP of client, not the IP of APISIX, so your example is invalid.
> 
> if you deploy APISIX in k8s, I think the client ip that APISIX sees is the ip of the k8s gateway?
> 
> similar as #4485, #4767

It depends on where the k8s cluster deploying and where the user sending the request.

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
