### ISSUE TITLE
request help: Apisix version 1.5 frequently appeared ssl-related error messages

### ISSUE THREAD

**Issue by kuaiwenwu** [apache/apisix#5024]
### Since using apisix 1.5, the following error messages often appear in the error log:

```
2021/09/09 14:25:05 [warn] 9985#9985: *4436800 [lua] init.lua:162: http_ssl_phase(): failed to fetch ssl config: failed to fetch SSL certificate: not found, context: ssl_certificate_by_lua *, client: 118.178.15.105, server: 0.0.0.0:443
2021/09/09 14:25:06 [warn] 9985#9985: *4436851 [lua] init.lua:162: http_ssl_phase(): failed to fetch ssl config: failed to fetch SSL certificate: not found, context: ssl_certificate_by_lua *, client: 118.178.15.96, server: 0.0.0.0:443
2021/09/09 14:25:06 [warn] 9988#9988: *4436900 [lua] init.lua:162: http_ssl_phase(): failed to fetch ssl config: failed to fetch SSL certificate: not found, context: ssl_certificate_by_lua *, client: 118.178.15.96, server: 0.0.0.0:443
2021/09/09 14:25:07 [warn] 9986#9986: *4436954 [lua] init.lua:162: http_ssl_phase(): failed to fetch ssl config: failed to fetch SSL certificate: not found, context: ssl_certificate_by_lua *, client: 120.27.173.11, server: 0.0.0.0:443
2021/09/09 14:25:07 [warn] 9985#9985: *4436960 [lua] init.lua:162: http_ssl_phase(): failed to fetch ssl config: failed to fetch SSL certificate: not found, context: ssl_certificate_by_lua *, client: 120.27.173.8, server: 0.0.0.0:443
```
### And the following error message:
```
2021/09/09 14:25:11 [warn] 9986#9986: *4437170 [lua] radixtree_sni.lua:166: match_and_set(): failed to find any SSL certificate by SNI: iop-inner.xxx.com, context : ssl_certificate_by_lua*, client: 10.20.2.12, server: 0.0.0.0:443
2021/09/09 14:25:11 [warn] 9985#9985: *4437194 [lua] radixtree_sni.lua:166: match_and_set(): failed to find any SSL certificate by SNI: iop-inner.xxx.com, context : ssl_certificate_by_lua*, client: 10.20.2.12, server: 0.0.0.0:443
2021/09/09 14:25:12 [warn] 9986#9986: *4437218 [lua] radixtree_sni.lua:166: match_and_set(): failed to find any SSL certificate by SNI: iop-inner.xxx.com, context : ssl_certificate_by_lua*, client: 10.20.2.12, server: 0.0.0.0:443
2021/09/09 14:25:12 [warn] 9985#9985: *4437242 [lua] radixtree_sni.lua:166: match_and_set(): failed to find any SSL certificate by SNI: iop-inner.xxx.com, context : ssl_certificate_by_lua*, client: 10.20.2.12, server: 0.0.0.0:443
```
### I don’t know if it has something to do with the configuration in config.yaml?

I don’t know if it has something to do with the configuration in config.yaml? 
![image](https://user-images.githubusercontent.com/24381401/132638096-ca00faaa-25ca-413a-934b-bd2117c04600.png)

### Environment

- apisix version (cmd: `apisix version`): 1.5
- OS (cmd: `uname -a`):Linux  3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.17.8.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.3

**Comment by tzssangglass** [comment]
Is this a sure thing? Has some case of find SSL certificate by SNI success？

**Comment by tzssangglass** [comment]
Can you capture network packets about these error?

**Comment by tzssangglass** [comment]
Can you provide steps for stable reproduction?

**Comment by kuaiwenwu** [comment]
> Is this a sure thing? Has some case of find SSL certificate by SNI success？
### I did not understand what you mean. The ssl certificate you are talking about here is the certificate I put in the /usr/local/apisix/cert/ directory? 
![image](https://user-images.githubusercontent.com/24381401/132784774-667881ed-7c6b-4bf7-85cf-c4bf03818b47.png)
### The certificate below is a general certificate *.xxx.com, I modified it to the default certificate name and placed it under the cert directory.
![image](https://user-images.githubusercontent.com/24381401/132784798-4c64863b-60f5-4f7e-ac3a-94e0ba2557d3.png)

**Comment by tzssangglass** [comment]
> provide steps for stable reproduction

pls provide steps for stable reproduction, or you can take a look at https://github.com/apache/apisix/blob/master/docs/zh/latest/certificate.md

**Comment by kuaiwenwu** [comment]
> > provide steps for stable reproduction
> 
> pls provide steps for stable reproduction, or you can take a look at https://github.com/apache/apisix/blob/master/docs/zh/latest/certificate.md

Great, let me take a look. Thank you.
