### ISSUE TITLE
request help:  I want to add the result data of the request response to the access log

### ISSUE THREAD

**Issue by ly-hash** [apache/apisix#5037]
### Issue description

I want to add the result data of the request response to the access log. Now it seems that only status is supported. What should I do? In addition, I want to return the response result of JSON. For the HTML returned now, the response code is also specified, such as 404，500. The return part of the code can be customized，thank you

### Environment

- apisix version (cmd: `apisix version`):  2.9
- OS (cmd: `uname -a`): centOS7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
You may have to collect the response body by concatenating them in the body_filter phase, you may serialize them into a Nginx variable and print it in the access log, since you need another Nginx variable, you may have to modify the `apisix/cli/ngx_tpl.lua` to add it (as currently, APISIX doesn't support to configure custom Nginx variables in config.yaml).

**Comment by tzssangglass** [comment]
It seems that there are some about this feature.

For the response body, it can be logged in the log files, also in plugins such as kafka-logger, and pushed to the log server.

**Comment by ly-hash** [comment]
@toker,thank you very much
If I need to customize the result of the returned response, for example, instead of returning 404 or 500 information, it is a JSON structure, how should I modify it

**Comment by ly-hash** [comment]
@tokers,thank you very much
If I need to customize the result of the returned response, for example, instead of returning 404 or 500 information, it is a JSON structure, how should I modify it

**Comment by ly-hash** [comment]
@tzssangglass，I think you're right. It may be more convenient for users to make it into a plug-in

**Comment by tzssangglass** [comment]
I find it difficult to log the response body in the log file(access.log, error.log), which involves the `log_format` directive.

But allowing it in a logging plugin like kafka-logger is possible.

**Comment by aikin-vip** [comment]
need this feature too!!!

**Comment by zcstack** [comment]
建议开发者在现有的logger插件内支持响应body！

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/5550
