### ISSUE TITLE
Permission deniedbug: 

### ISSUE THREAD

**Issue by cielswift** [apache/apisix#5042]
### Issue description

#将 Apache APISIX 的 Docker 镜像下载到本地
git clone https://github.com/apache/apisix-docker.git
# 将当前的目录切换到 apisix-docker/example 路径下
cd apisix-docker/example
# 运行 docker-compose 命令，安装 Apache APISIX
docker-compose -p docker-apisix up -d

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

#将 Apache APISIX 的 Docker 镜像下载到本地
git clone https://github.com/apache/apisix-docker.git
# 将当前的目录切换到 apisix-docker/example 路径下
cd apisix-docker/example
# 运行 docker-compose 命令，安装 Apache APISIX
docker-compose -p docker-apisix up -d

### Actual result

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: failed to open file: /usr/local/apisix/conf/config.yaml, error info:/usr/local/apisix/conf/config.yaml: Permission denie

### Error log

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
failed to read local yaml config of apisix: failed to open file: /usr/local/apisix/conf/config.yaml, error info:/usr/local/apisix/conf/config.yaml: Permission denie

**Comment by tokers** [comment]
@cielswift Could you show the permission of the `example/apisix_conf/config.yaml`?

**Comment by leslie-tsang** [comment]
@cielswift Please follow cmd below and paste output as comment.
```bash
# fetch OS
uname -a

# fetch user info
id

# fetch dockerd info (docker launch user may cause permission issue)
ps aux | grep dockerd

# fetch config.yaml permission (run in `apisix-docker/example`)
ls -l example/apisix_conf/config.yaml
```

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.

**Comment by cielswift** [comment]
@leslie-tsang  
![image](https://user-images.githubusercontent.com/42295829/133953676-1222aeab-a279-496d-a139-cae289ad89b3.png)

**Comment by cielswift** [comment]
![image](https://user-images.githubusercontent.com/42295829/133953785-b987804e-01aa-4f62-bf44-0746e40d0fbb.png)
![image](https://user-images.githubusercontent.com/42295829/133954022-1792d08e-93a3-4773-8c81-47357108a31d.png)
not open
