### ISSUE TITLE
bug: Health check cause Connection reset by peer

### ISSUE THREAD

**Issue by javalover123** [apache/apisix#5048]
### Issue description

Health check cause Connection reset by peer.

![网页捕获_13-9-2021_121732_dev skorpro com](https://user-images.githubusercontent.com/9191388/133024030-77f1a7c7-7a6b-40d4-82f5-0cc549cde5cf.jpeg)

### Environment

- apisix version (cmd: `apisix version`):2.6
- OS (cmd: `uname -a`):Linux d7e3aced1f6b 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
- apisix-dashboard version, if have:2.7
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.7.0

### Steps to reproduce

1. Config health check
2. check backend(Java) node's log

### Actual result

Backend java Log contains Connection reset by peer

### Error log

Connection reset by peer

**Comment by tzssangglass** [comment]
> Backend java Log contains Connection reset by peer

what it is?

Can you provide steps that can be replicated?

**Comment by javalover123** [comment]
> > Backend java Log contains Connection reset by peer
> 
> what it is?
> 
> Can you provide steps that can be replicated?

I provide a screenshot, health check config is show all infomations. 
Backend java application is a normal http service based on spring boot.

**Comment by tzssangglass** [comment]
> I provide a screenshot in the issue description, showed all information about health check config.

I can't get any valid information from the screenshot.
