### ISSUE TITLE
request help: how to set my plugin path in unittest

### ISSUE THREAD

**Issue by besich** [apache/apisix#5053]
### Issue description

how to set my plugin path in unittest
in running apisix, it could be setup the `extra_lua_path` and `extra_lua_cpath` in `conf/config.yaml`,
but in unittest, how to set it?
```
add_block_preprocessor(sub{
    my ($block) = @_;
    my $user_yaml_config = $block->user_yaml_config // <<_EOC_;
apisix:
  extra_lua_path: "/xxxxxx/apisix/?.lua"
_EOC_

    $block->set_value("yaml_config", $user_yaml_config);
});
```
it also not found the  lua script.
 

### Environment

none

**Comment by dmsolr** [comment]
It does not support yet. You can try to modify lua_package_path in APISIX.pm

**Comment by leslie-tsang** [comment]
Hi, you can modify it in `t/APISIX.pm`, more detail can be find in [openresty unit test](https://openresty.gitbooks.io/programming-openresty/content/testing/test-modes.html)
https://github.com/apache/apisix/blob/cd97d827abf6791611ce355b12555531dbd7b53d/t/APISIX.pm#L231-L234
