### ISSUE TITLE
docs: developer guide?

### ISSUE THREAD

**Issue by RedemptionC** [apache/apisix#5056]
### Improved or typo fixed.

Hi,community

I've searched this repo and the official site
found these two related post:
[CONTRIBUTING](https://github.com/apache/apisix/blob/3ccc5b8b825c56b7b9a3bf56d3aed5879be1b3a6/CONTRIBUTING.md),this post covers some general guidance on contributing
and another post which only covers  how to submit a pull request(I couldn't find that post now)

I'm curious that whether this is enough for a developer to get started
I read a [post](https://opensource.com/life/16/3/contributor-guidelines-template-and-tips) on open source documentations,it suggests that the docs should include some info about the technical stack,the prerequisite to get started,and something about code structure or the overall design,like what the [dolphinscheduler](https://dolphinscheduler.apache.org/en-us/development/architecture-design.html) did

I'm curious how did you get started contributing code to this project 

And maybe it's due to that I don't fully scan the repo and the official website,what I did is just searching the keywords(like development,developer guide,only to get results on other projects of APISIX,like dashboard or plugin) and looking at the overall structure

if that's the case,correct me and close this issue,thanks a lot.
 

### Solution

-

**Comment by nic-chen** [comment]
please see https://github.com/apache/apisix/tree/master/docs/en/latest/architecture-design @RedemptionC

**Comment by RedemptionC** [comment]
> please see https://github.com/apache/apisix/tree/master/docs/en/latest/architecture-design @RedemptionC

thank you, but that doesn't seem to be what I'm locking for.

**Comment by spacewander** [comment]
To get involved, a better way is reading code & play with it.
You can start your journey from apisix/cli/ngx_tpl.lua and apisix/init.lua
