### ISSUE TITLE
request help: mqtt-proxy dosen't work

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5057]
### Issue description

我使用mqtt-plugin测试连接不了。

apisix已经监听9100端口.

bash-5.1# netstat -atp |grep 9100
tcp        0      0 0.0.0.0:9100            0.0.0.0:*               LISTEN      1/apisix -g daemon
tcp        0      0 0.0.0.0:9100            0.0.0.0:*               LISTEN      1/apisix -g daemon
tcp        0      0 0.0.0.0:9100            0.0.0.0:*               LISTEN      1/apisix -g daemon
...

添加路由：
```java
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "192.168.20.20",
    "plugins": {
        "mqtt-proxy": {
            "protocol_name": "MQTT",
            "protocol_level": 4,
            "upstream": {
                "host": "192.168.20.20",
                "port": 1883
            }
        }
    }
}'
```
测试连接失败

![image](https://user-images.githubusercontent.com/3895272/133200760-1c3cd155-76ef-4a53-ae7b-69d673e2a38d.png)

apiisx配置：

```java
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false
  enable_control: true
  stream_proxy:
    only: false
    tcp:
      - 9100
```

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
any logs about this in `error.log` or `access.log`?

**Comment by qq54903099** [comment]
> any logs about this in `error.log` or `access.log`?

尝试连接的时候没有日志：

启动的时候：

2021/09/14 05:42:25 [warn] 44#44: *3 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 43#43: *2 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 42#42: *1 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 45#45: *4 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 52#52: *10 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 48#48: *7 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 47#47: *6 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 50#50: *8 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 49#49: *12 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 53#53: *11 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 46#46: *5 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 51#51: *9 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 56#56: *13 [lua] plugin.lua:150: load(): new plugins: {"proxy-rewrite":true,"proxy-mirror":true,"client-control":true,"key-auth":true,"kafka-logger":true,"server-info":true,"echo":true,"request-id":true,"serverless-post-function":true,"redirect":true,"basic-auth":true,"limit-count":true,"batch-requests":true,"openid-connect":true,"uri-blocker":true,"consumer-restriction":true,"ext-plugin-pre-req":true,"fault-injection":true,"proxy-cache":true,"example-plugin":true,"udp-logger":true,"jwt-auth":true,"hmac-auth":true,"wolf-rbac":true,"ip-restriction":true,"request-validation":true,"tcp-logger":true,"api-breaker":true,"sls-logger":true,"ua-restriction":true,"referer-restriction":true,"limit-conn":true,"traffic-split":true,"limit-req":true,"grpc-transcode":true,"response-rewrite":true,"prometheus":true,"cors":true,"serverless-pre-function":true,"zipkin":true,"authz-keycloak":true,"authz-casbin":true,"gzip":true,"ext-plugin-post-req":true,"syslog":true,"http-logger":true,"real-ip":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 45#45: *4 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 47#47: *6 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 43#43: *2 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 48#48: *7 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 42#42: *1 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 50#50: *8 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 52#52: *10 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 44#44: *3 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 49#49: *12 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 53#53: *11 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 46#46: *5 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 51#51: *9 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 47#47: *14 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 52#52: *16 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 50#50: *19 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 43#43: *20 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 48#48: *17 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 44#44: *21 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 46#46: *22 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 42#42: *18 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 49#49: *23 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 53#53: *24 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 56#56: *13 [lua] plugin.lua:192: load_stream(): new plugins: {"limit-conn":true,"ip-restriction":true,"mqtt-proxy":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 45#45: *15 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 51#51: *50 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2021/09/14 05:42:25 [warn] 56#56: *391 stream [lua] plugin.lua:192: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*

**Comment by tokers** [comment]
The stream route asks the remote addr is 192.168.20.20, are you sure this is the ip that apisix seen?

**Comment by tzssangglass** [comment]
I notice that the `remote_addr` and `upstream.host` both are `192.168.20.20`, and the APISIX ip is `192.168.20.20`?

maybe your `remote_addr` is wrong?

**Comment by qq54903099** [comment]
> I notice that the `remote_addr` and `upstream.host` both are `192.168.20.20`, and the APISIX ip is `192.168.20.20`?
> 
> maybe your `remote_addr` is wrong?

I use same machine.  my local computer

**Comment by tzssangglass** [comment]
try change `"192.168.20.20"` to `"127.0.0.1"`

**Comment by qq54903099** [comment]
> try change `"192.168.20.20"` to `"127.0.0.1"`
like this?

```java
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
   
    "upstream": {
        "nodes": {
            "127.0.0.1:1995": 1
        },
        "type": "roundrobin"
    }
}'
```

but i install apisix use docker.  upstream use 127.0.0.1 can't connect.

**Comment by tzssangglass** [comment]
If you use a client to push MQTT messages to APISIX, the client IP that APISIX sees in docker is the `remote_addr`.

**Comment by qq54903099** [comment]
> If you use a client to push MQTT messages to APISIX, what is the client IP that APISIX sees in docker?use this IP as `remote_addr`.

我用了本地安装的方式，是ok了。
