### ISSUE TITLE
request help: Error when start the Python-plugin-runner

### ISSUE THREAD

**Issue by Molio-tan** [apache/apisix#5059]
### Issue description

When I installed the apisix-python-plugin-runner, I tried to use prod-mode to start it with `conf/config.yaml` as bellow.
![image](https://user-images.githubusercontent.com/31587573/133221364-c74a9bf3-c436-4986-890d-bd85befd6e01.png)
As all prepared, I restarted the apisix and I found an error in `logs/error.log`
![image](https://user-images.githubusercontent.com/31587573/133221671-fc734722-fb96-45d4-9512-c87abd292978.png)
So, I checked it out in terminal. But it didn't work.
![image](https://user-images.githubusercontent.com/31587573/133222097-2e573873-d540-4716-b87d-0e96363ef105.png)

where should I export the `LC_ALL` and `LANG`?

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): Linux molio-apusic 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.13
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
When started by `prod-mode`, the `python runner` as a child process of Nginx will have a separate process space, so the settings in the terminal cannot be read.

**Comment by shuaijinchao** [comment]
You can temporarily adjust it here:

https://github.com/apache/apisix/blob/b72404f643f37b10eb164056d784c33a97251c46/apisix/plugins/ext-plugin/init.lua#L639-L640

Next, I will fix it. In addition, Python Runner 0.1.0 version needs to use `APISIX 2.7` version, `APISIX 2.8` and `APISIX 2.9` versions are not compatible with `Python Runner 0.1.0` due to private protocol adjustments.

**Comment by Molio-tan** [comment]
> You can temporarily adjust it here:
> 
> https://github.com/apache/apisix/blob/b72404f643f37b10eb164056d784c33a97251c46/apisix/plugins/ext-plugin/init.lua#L639-L640
> 
> Next, I will fix it. In addition, Python Runner 0.1.0 version needs to use `APISIX 2.7` version, `APISIX 2.8` and `APISIX 2.9` versions are not compatible with `Python Runner 0.1.0` due to private protocol adjustments.
> 
> Please see document:
> https://github.com/apache/apisix-python-plugin-runner/blob/6c10aa1429a23c0b316121b348af8df65df1495e/docs/en/latest/getting-started.md

Oh, I'm sorry that i didn't notice the compatibility between apisix and the runner.
By your suggestion, I add two line as bellow and it work correctly. Thank you.
![image](https://user-images.githubusercontent.com/31587573/133361052-511f4260-1bcd-41df-89aa-55eb51f3cf49.png)
