### ISSUE TITLE
How to modify /usr/local/apisix/conf/nginx.conf

### ISSUE THREAD

**Issue by xiongyunhua-star** [apache/apisix#5063]
### Issue description

I want to insert a header （k : v）in nginx.conf of APISIX

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by xiongyunhua-star** [comment]
But the file is read-only

**Comment by tzssangglass** [comment]
take a look at:https://github.com/apache/apisix/blob/master/docs/zh/latest/customize-nginx-configuration.md
