### ISSUE TITLE
bug: 通过rpm升级apisix时会覆盖/usr/local/apisix/conf/config.yaml

### ISSUE THREAD

**Issue by pc10201** [apache/apisix#5066]
### Issue description

通过rpm升级apisix时会覆盖/usr/local/apisix/conf/config.yaml
之前修改的配置文件都会丢失

### Environment

无

### Steps to reproduce

无

### Actual result

无

### Error log

无

**Comment by imjoey** [comment]
@pc10201 Hi, could you please provide the steps to reproduce this error? As far as I know, `rpm -U` will automatically well handle this situation by computing the md5 value of the configurations with the same name. We need more details, thanks.

**Comment by spacewander** [comment]
Solved in https://github.com/api7/apisix-build-tools/pull/95

**Comment by imjoey** [comment]
@pc10201 Now you can use the latest code in https://github.com/api7/apisix-build-tools for building a new RPM. Thanks.
