### ISSUE TITLE
request help: jwt-auth plugin failed to sign jwt HTTP/1.1 500 Internal Server Error

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5067]
### Issue description

jwt-auth插件配置
![image](https://user-images.githubusercontent.com/26192378/133414176-5c618216-612c-4bf2-b95b-fa425e137040.png)
![image](https://user-images.githubusercontent.com/26192378/133414247-db08bcfd-13d2-4b9b-bf11-d684231b873b.png)
![image](https://user-images.githubusercontent.com/26192378/133414287-47327c1c-9203-40d2-a79f-c5f194dd4efa.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

按文案配置公钥密钥

### Actual result

获取token服务报错

### Error log

![image](https://user-images.githubusercontent.com/26192378/133414422-828d765e-3281-4b78-8b02-01b4eb49f489.png)

**Comment by shuaijinchao** [comment]
Is there an error message when setting the plug-in information? You can check whether the parameter settings are complete through AdminAPI.

**Comment by 18300618319** [comment]
可以加一下微信吗



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 晚上6:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] jwt-auth插件failed to sign jwt HTTP/1.1 500 Internal Server Error (#5067)






设置插件信息时有错误提示吗？可以通过 Adm in API 检查参数设置是否完成。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by 18300618319** [comment]
这应该是没报错吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 晚上6:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] jwt-auth插件failed to sign jwt HTTP/1.1 500 Internal Server Error (#5067)





 
Is there an error message when setting the plug-in information? You can check whether the parameter settings are complete through AdminAPI.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 18300618319** [comment]
@shuaijinchao 在吗

**Comment by shuaijinchao** [comment]
> @shuaijinchao 在吗

you WeChat ID ?

**Comment by 18300618319** [comment]
LB86248864




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 晚上6:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] jwt-auth插件failed to sign jwt HTTP/1.1 500 Internal Server Error (#5067)






@shuaijinchao在吗

你微信号？

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by shuaijinchao** [comment]
```bash
curl http://127.0.0.1:9080/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
  "username": "kerouac",
  "plugins": {
    "jwt-auth": {
      "algorithm": "RS256",
      "base64_secret": false,
      "exp": 86400,
      "key": "user-key",
      "public_key": "-----BEGIN PUBLIC KEY-----\n...\n-----END PUBLIC KEY-----",
      "private_key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n"
    }
  }
}'
```

---

The public key and private key settings are reversed.
