### ISSUE TITLE
request help: How to ignore the access log of a certain route?

### ISSUE THREAD

**Issue by bingoku** [apache/apisix#5071]
### Issue description

如题

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
Do not record log?

**Comment by spacewander** [comment]
Currently the only way is to solve in the collector side, see https://github.com/apache/apisix/issues/3526

**Comment by bingoku** [comment]
> Do not record log?

yes

**Comment by shuaijinchao** [comment]
> > Do not record log?
> 
> yes

It is currently not possible to ignore the nginx access log directly, please refer to @spacewander reply.
