### ISSUE TITLE
bug:  In radixtree_host_uri mode, the prometheus plugin cannot obtain the correct matched_uri value.

### ISSUE THREAD

**Issue by Donghui0** [apache/apisix#5077]
### Issue description

In radixtree_host_uri mode.   api_ctx.curr_req_matched._path was eventually replaced by  `host_rev`

example:
      request:  http://123.com/x1         api_ctx.curr_req_matched._path  replaced by  `moc.321`

### Environment

- apisix version (cmd: `apisix version`): v2.9
- OS (cmd: `uname -a`): centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.1

### Steps to reproduce

1: adjustment mode, change to `radixtree_host_uri`
2: request  apisix route
3: query apisx:9091/apisx/promethues/metrics.

### Actual result

host reverse.  
example:
      request:  http://123.com/x1         api_ctx.curr_req_matched._path  replaced by  `moc.321`

### Error log

none

### Expected result

api_ctx.curr_req_matched._path  replaced by  `matched_ops.uri`

**Comment by spacewander** [comment]
Need to reset curr_req_matched._path after matched.
Would you provide a fix?
