### ISSUE TITLE
bug: lua-protobuf v 0.3.3 cache manager exit by signal 11

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#5079]
### Issue description

I ran `make deps` based on `apisix-master-0.rockspec` from the master branch, then I found that the cache manager kept exit abnormally

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`): 

```
Linux localhost.localdomain 5.12.8-200.fc33.aarch64 SMP Sat May 29 17:54:05 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 

```
nginx version: openresty/1.19.3.2
built by gcc 10.3.1 20210422 (Red Hat 10.3.1-1) (GCC) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_OPENRESTY_VER=0.0.0 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.hoRe9VZG7j/openresty-1.19.3.2/../mod_dubbo --add-module=/tmp/tmp.hoRe9VZG7j/openresty-1.19.3.2/../ngx_multi_upstream_module --add-module=/tmp/tmp.hoRe9VZG7j/openresty-1.19.3.2/../apisix-nginx-module --add-module=/tmp/tmp.hoRe9VZG7j/openresty-1.19.3.2/../lua-var-nginx-module --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
```

- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):

```
{"last_report_time":1631812585,"hostname":"localhost.localdomain","id":"e5cdf2f6-ad1c-4789-a19a-dc61b6741270","version":"2.9","boot_time":1631812585,"etcd_version":"3.4.0","up_time":2}
```

- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
  - luarocks version, if the issue is about installation (cmd: `luarocks --version`):

```
/usr/local/bin/luarocks 3.4.0
LuaRocks main command-line interface
```

### Steps to reproduce

1. based on `apisix-master-0.rockspec` from the master branch, and `./bin/apisix start`, see `logs/error.log`, has `[alert] 7948#7948: cache manager process 7953 exited on signal 11 (core dumped)`
2. change `"lua-protobuf = 0.3.3"` to `"lua-protobuf = 0.3.2"` in `apisix-master-0.rockspec`, and `./bin/apisix start`, see `logs/error.log`, no `[alert] 7948#7948: cache manager process 7953 exited on signal 11 (core dumped)`

### Actual result

 no `[alert] 7948#7948: cache manager process 7953 exited on signal 11 (core dumped)` in `logs/error.log` when `"lua-protobuf = 0.3.3"`

### Error log

2021/09/17 01:12:31 [alert] 7948#7948: cache manager process 7953 exited on signal 11 (core dumped)

**Comment by tzssangglass** [comment]
@yuhongyu879

**Comment by spacewander** [comment]
Could you provide the core dump file of cache manager? Can it be reproduced 100%?

**Comment by tzssangglass** [comment]
I tried core dump, but the dumped file was empty. In my environment, it can be reproduced 100%, I have verified this at least 3 times.

**Comment by spacewander** [comment]
Interesting, can't reproduce at my side.
