### ISSUE TITLE
bug: Active check is turned on, but Health check status no data 

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5082]
### Issue description

We configured active checking, but no data output where curl  `127.1:9090/v1/healthcheck`
![image](https://user-images.githubusercontent.com/9711651/133710624-37977107-ab1a-4f99-8d0e-78f143b356cb.png)

![image](https://user-images.githubusercontent.com/9711651/133710765-9c4bdf57-4d17-4ac5-9c5f-ceafe313dc40.png)

There is no relevant error output from the K8S console, Plz take a look.

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): centos-docker
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.x
- apisix-dashboard version, if have: 2.8

### Steps to reproduce

1. add upstream
```
PUT /apisix/admin/upstreams/demo_test
{
  "nodes": [
    {
      "host": "127.0.0.1",
      "port": 9090,
      "weight": 100
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 60,
    "read": 60
  },
  "type": "roundrobin",
  "checks": {
    "active": {
      "concurrency": 10,
      "healthy": {
        "http_statuses": [
          200,
          302,
          404,
          403,
          405,
          401
        ],
        "interval": 2,
        "successes": 2
      },
      "http_path": "/",
      "port": 9090,
      "timeout": 2,
      "type": "http",
      "unhealthy": {
        "http_failures": 3,
        "http_statuses": [
          429,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "interval": 1,
        "tcp_Failures": 2,
        "tcp_failures": 2,
        "timeouts": 2
      }
    },
    "passive": {
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 3
      },
      "type": "http",
      "unhealthy": {
        "http_failures": 2,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 2,
        "timeouts": 3
      }
    }
  },
  "hash_on": "vars",
  "scheme": "http",
  "pass_host": "pass",
  "name": "demo_test"
}
```
2. curl -X GET 127.1:9090/v1/healthcheck

### Actual result

GET 127.1:9090/v1/healthcheck
```
{}
```

### Error log

nothing

### Expected result

GET 127.1:9090/v1/healthcheck
```
[
    {
        "healthy_nodes": [
            {
                "host": "127.0.0.1",
                "port": 9090,
                "priority": 0,
                "weight": 100
            }
        ],
        "name": "upstream#/apisix/upstreams/demo_test",
        "nodes": [
            {
                "host": "127.0.0.1",
                "port": 9090,
                "priority": 0,
                "weight": 100
            }
        ],
        "src_id": "demo_test",
        "src_type": "upstreams"
    }
]
```

**Comment by tokers** [comment]
Trigger of health checker is lazy, so you should send some requests before you check the health check data.

**Comment by jagerzhang** [comment]
> Trigger of health checker is lazy, so you should send some requests before you check the health check data.

i see...

**Comment by jagerzhang** [comment]
I have another question. When a new request activates the health check, how long will the route revoke the health check if there is no new request?

**Comment by tzssangglass** [comment]
> how long will the route revoke the health check if there is no new request

I don't understand this. Do you mean the expiry time of the health check data in the shared dict?

**Comment by tokers** [comment]
> @tokers I have another question. When a new request activates the health check, how long will the route revoke the health check if there is no new request? Is there any guidance document for this?

The active health check will send probes to the endpoints (for both the healthy set and the unhealthy set) periodically. So status will be updated in time.

**Comment by jagerzhang** [comment]
> > how long will the route revoke the health check if there is no new request
> 
> I don't understand this. Do you mean the expiry time of the health check data in the shared dict?

I mean, will it become lazy again after activation? 
Is there any guidance document about this feature?

**Comment by tokers** [comment]
> > > how long will the route revoke the health check if there is no new request
> > 
> > 
> > I don't understand this. Do you mean the expiry time of the health check data in the shared dict?
> 
> I mean, will it become lazy again after activation?
> Is there any guidance document about this feature?

It won't. You can see https://kong.github.io/lua-resty-healthcheck/topics/readme.md.html for more details.

**Comment by jagerzhang** [comment]
> > > > how long will the route revoke the health check if there is no new request
> > > 
> > > 
> > > I don't understand this. Do you mean the expiry time of the health check data in the shared dict?
> > 
> > 
> > I mean, will it become lazy again after activation?
> > Is there any guidance document about this feature?
> 
> It won't. You can see https://kong.github.io/lua-resty-healthcheck/topics/readme.md.html for more details.

ok, tks
