### ISSUE TITLE
memory leak when enable prometheus as global

### ISSUE THREAD

**Issue by suninuni** [apache/apisix#5092]
### Issue description

When the prometheus global plugin is enabled, the memory of apisix continues to grow abnormally.

### Environment

- apisix version (cmd: `apisix version`): 2.7

### Steps to reproduce

- deploy httpbin service in k8s ([step in apisix-inrgess-controller](https://apisix.apache.org/docs/ingress-controller/practices/proxy-the-httpbin-service))
- enable prometheus as global rule and set perfer_name as true (lua_shared_dict.prometheus-metrics is 10m)
- mock http request throw ab with high concurrency `ab -n 2000000 -c 2000 http://xxxxx`

### Actual result

- memory keep growing
    
    ![image](https://user-images.githubusercontent.com/7345529/133870299-cd0b5c4e-84f8-49a7-9b5b-51e4c2830c79.png)

### Error log

- `*45077733 [lua] prometheus.lua:860: log_error(): Unexpected error adding a key: no memory while logging request,`

### Expected result

- The memory should not continue to grow. 
- Prometheus should release a part of the memory allocated to it after it is used up to avoid continuous errors.

**Comment by suninuni** [comment]
releated https://github.com/apache/apisix/issues/3917#issuecomment-921736339

@tzssangglass FYI

**Comment by suninuni** [comment]
![image](https://user-images.githubusercontent.com/7345529/133880899-a365a1b5-18c5-4fbb-991e-52b4f7a2cfd5.png)

It's keep growing, FYI.

**Comment by spacewander** [comment]
First of all, we need to check if the error log is caused by the memory used by Prometheus is unbound or just because the default size is too small.

The configuration of lua shdict is not available until 2.8, so you may need to modify the ngx_tpl.lua: https://github.com/apache/apisix/pull/4524

If the Prometheus memory usage grows without limit, it will consume all the memory configurated. Otherwise, the memory usage stops growing in a level.

We also need to compare the Prometheus metrics before/after the http request. Prometheus client is a well-known memory consumer. How many metrics/labels are there in the Prometheus metrics?

You can also use X-Ray to diagnose the memory issue: https://openresty.com.cn/cn/xray/. Note that I am not the developer of X-Ray (it is a commercial product developed by others).

**Comment by suninuni** [comment]
> The configuration of lua shdict is not available until 2.8, so you may need to modify the ngx_tpl.lua

We are now deploying apisix in the test environment, so I will upgrade apisix to 2.9 and retest in next week.

> How many metrics/labels are there in the Prometheus metrics?

I counted the number of metrics rows in two pods with different memory consumption. Is this magnitude acceptable? 

memory 763m: 18869

![image](https://user-images.githubusercontent.com/7345529/133884758-25fa6b95-e1f4-4a8e-8446-0558a5634c77.png)

memory 596m: 17924

![image](https://user-images.githubusercontent.com/7345529/133884828-cb421254-17e3-4b75-a797-ffd3ad348955.png)

**Comment by tzssangglass** [comment]
IMO, this is not normal, but it still depends on the size of the lua share dict assigned to prometheus in your runtime nginx.conf, and the number of concurrent requests. I suggest that you try with X-Ray that @spacewander mentioned.

**Comment by membphis** [comment]
@suninuni the latest version of APISIX is 2.11 now, can you make a try with APISIX `2.11`? We can not sure if we have fixed this issue.

If you still have this problem, please let us know.

**Comment by suninuni** [comment]
> @suninuni the latest version of APISIX is 2.11 now, can you make a try with APISIX `2.11`? We can not sure if we have fixed this issue.
> 
> If you still have this problem, please let us know.

The same error log as before.

```
2021/12/30 02:36:43 [error] 50#50: *20414229 [lua] prometheus.lua:860: log_error(): Unexpected error adding a key: no memory while logging request
```

And now I try to set `lua_shared_dict.prometheus-metrics` as 100m, FYI.

**Comment by suninuni** [comment]
> And now I try to set lua_shared_dict.prometheus-metrics as 100m

It seems that the memory does not increase after it has increased to a certain value, and I have not found `no memory while logging request` log any more.

![image](https://user-images.githubusercontent.com/7345529/147726207-35518df3-c680-4cfd-98f7-4645dea92e5f.png)

So it seems that this problem no longer exists with APISIX `2.11`, I will continue to observe. Thanks for your support!

**Comment by tokers** [comment]
> Unexpected error adding a key

So the memory increasing is normal and the no memory issue is just because the pre-defined lua shared dict too small?

**Comment by suninuni** [comment]
> > Unexpected error adding a key
> 
> So the memory increasing is normal and the no memory issue is just because the pre-defined lua shared dict too small?

After a period of stability, memory increased until oom...

![image](https://user-images.githubusercontent.com/7345529/147990245-99e8bac9-5640-4451-aca7-ce5203f4f0f1.png)

**Comment by suninuni** [comment]
@tokers @membphis FYI

**Comment by membphis** [comment]
> So it seems that this problem no longer exists with APISIX `2.11`, I will continue to observe. Thanks for your support!

do you update your apisix to `2.11`?

**Comment by suninuni** [comment]
> > So it seems that this problem no longer exists with APISIX `2.11`, I will continue to observe. Thanks for your support!
> 
> do you update your apisix to `2.11`?

yes

**Comment by suninuni** [comment]
Finally, I solved this problem by removing the node label (balance_ip) for the metrics in [exporter.lua](https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L168).

The root cause is that the key saved in the shared dict contains all labels, such as ` idx=__ngx_prom__key_35279, key=http_status{code="499",route="xxxx",matched_uri="/*",matched_host="xxxxx ",service="",consumer="",node="10.32.47.129"}`. In a k8s cluster, or in a k8s cluster that the deployments are frequently deployed, the information of nodes is always changing, resulting in dict always growing.

Maybe we can change the node label as extra_labels and let the user decide if this label is needed.

**Comment by tokers** [comment]
> Finally, I solved this problem by removing the node label (balance_ip) for the metrics in [exporter.lua](https://github.com/apache/apisix/blob/master/apisix/plugins/prometheus/exporter.lua#L168).
> 
> The root cause is that the key saved in the shared dict contains all labels, such as ` idx=__ngx_prom__key_35279, key=http_status{code="499",route="xxxx",matched_uri="/*",matched_host="xxxxx ",service="",consumer="",node="10.32.47.129"}`. In a k8s cluster, or in a k8s cluster that the deployments are frequently updated, the information of nodes is always changing, resulting in dict always growing.
> 
> Maybe we can change the node label as extra_labels and let the user decide if this label is needed.

Indeed, that's a question when users deploy Apache APISIX on Kubernetes.

**Comment by va3093** [comment]
@suninuni How did you remove the `node` label. Are you using a custom build of apisix?

**Comment by va3093** [comment]
I fixed this by adding the following `module_hook`
```lua
local apisix = require("apisix")

local old_http_init = apisix.http_init
apisix.http_init = function (...)
    ngx.log(ngx.EMERG, "Module hooks loaded")
    old_http_init(...)
end

local exporter = require("apisix.plugins.prometheus.exporter")
local old_http_log = exporter.http_log
exporter.http_log = function (conf, ctx)
    ctx.balancer_ip = "_overwritten_"
    old_http_log(conf, ctx)
end
```
I put that in a config map and loaded it into the apisix config using the following config in my helmchart values.yml file.


```yaml
  luaModuleHook:
    enabled: true
    luaPath: "/usr/local/apisix/apisix/module_hooks/?.lua"
    hookPoint: "module_hook"
    configMapRef:
      name: "apisix-module-hooks"
      mounts:
        - key: "module_hook.lua"
          path: "/usr/local/apisix/apisix/module_hooks/module_hook.lua"
```

**Comment by jinjianming** [comment]
I observed that it was actually Apisix_ HTTP_ Latency_ There are too many bucket indicators that are constantly increasing, causing memory to continue to rise
![image](https://github.com/apache/apisix/assets/57084209/ecdfcce7-66db-4d70-a9a0-cc23365e79cd)
Apisix_ HTTP_ Status is not particularly abundant
![image](https://github.com/apache/apisix/assets/57084209/b4b794dc-8b81-4be1-9bba-757bcb8b7dbe)

Apisix_ Nginx_ Metric_ Errors_ There are many errors in the total indicator, and the log reports errors
```
content:2023/07/06 15:41:08 [error] 48#48: *972511102 [lua] init.lua:187: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 109.237.98.226, server: 0.0.0.0:9443
```
![image](https://github.com/apache/apisix/assets/57084209/79d9298a-77ee-44db-962c-a5769449d6f0)
How should I optimize and solve this problem
