### ISSUE TITLE
bug: rejected_msg not working in limit-count plugin

### ISSUE THREAD

**Issue by tinpad** [apache/apisix#5107]
### Issue description

I am using below request to setup limit-count as global rule.

curl http://127.0.0.1:9080/apisix/admin/global_rules/111 -H 'X-API-KEY: xxxxxxxxxxxxxxxxxxxx' -X PUT -d '
{
    "plugins": {
        "limit-count": {
            "time_window": 60,
            "policy": "local",
            "count": 10,
            "key": "remote_addr",
            "rejected_code": 429,
            "rejected_msg" : "{\"message\":\"Request Limit Exceeded\"}"
        }
    }
}'
When I hit the below route and the count exceeds the count 10 - 

http://127.0.0.1:9080/order/list?pageSize=10

I am getting 429 but not getting the response in json format as mentioned in the above route.
I am getting following html content -

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Environment

- apisix version (cmd: `apisix version`): 2.8
- OS (cmd: `uname -a`): 20.04.1-Ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
- apisix-dashboard version, if have: NA
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

### Steps to reproduce

as mentioned above, if we exceed the request count more than 10

### Actual result

<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Error log

2021/09/21 13:57:03 [warn] 2926#2926: *85612 [lua] plugin.lua:658: run_plugin(): limit-count exits with http status code 429, client: 127.0.0.1, server: _, request: "GET /order/list?pageSize=10 HTTP/1.1", host: "127.0.0.1:9080"

### Expected result

{"message":"Request Limit Exceeded"}

**Comment by tokers** [comment]
@tinpad Have you ever tried to check out the route object by using the GET API?

**Comment by tinpad** [comment]
@tokers I am getting below json with get api

{
  "node": {
    "dir": true,
    "nodes": [
      {
        "createdIndex": 1989,
        "key": "/apisix/global_rules/111",
        "modifiedIndex": 3019,
        "value": {
          "plugins": {
            "limit-count": {
              "key": "remote_addr",
              "rejected_code": 429,
              "redis_database": 0,
              "policy": "local",
              "time_window": 60,
              "rejected_msg": "{\"message\":\"Request Limit Exceeded\"}",
              "count": 10
            },
            "uri-blocker": {
              "block_rules": [
                "script.bat",
                "script.sh",
                "script.exe"
              ],
              "rejected_code": 403
            },
            "http-logger": {
              "retry_delay": 1,
              "timeout": 3,
              "uri": "http://192.168.1.2:8060/logger/log",
              "auth_header": "",
              "buffer_duration": 60,
              "batch_max_size": 1000,
              "include_req_body": false,
              "inactive_timeout": 5,
              "max_retry_count": 0,
              "name": "http logger",
              "concat_method": "json"
            },
            "basic-auth": {},
            "prometheus": {
              "prefer_name": false
            }
          },
          "id": "111",
          "update_time": 1632221711,
          "create_time": 1631798886
        }
      }
    ],
    "key": "/apisix/global_rules"
  },
  "count": "3",
  "action": "get"
}

**Comment by spacewander** [comment]
The rejected_msg is added in 2.9: https://github.com/apache/apisix/pull/4808/
So APISIX 2.8 doesn't support it.
