### ISSUE TITLE
conmuser does not support editing

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5114]
### Issue description

conmuser不支持修改编辑

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
conmuser不支持修改编辑

### Steps to reproduce

conmuser不支持修改编辑

### Actual result

conmuser不支持修改编辑

### Error log

conmuser不支持修改编辑

**Comment by 18300618319** [comment]
消费者只有新增没有编辑功能，功能缺失


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 下午5:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] conmuser does not support editing (#5114)





 
provide reproduction steps
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tzssangglass** [comment]
> 消费者只有新增没有编辑功能，功能缺失

see: https://github.com/apache/apisix/blob/master/docs/zh/latest/admin-api.md#consumer

**Comment by tzssangglass** [comment]
> 消费者只有新增没有编辑功能，功能缺失

You can use PUT to update an existing key.

**Comment by 18300618319** [comment]
不能更新名字，应该可以通过id更新名字




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] conmuser does not support editing (#5114)





  
消费者只有新增没有编辑功能，功能缺失
  
You can use PUT to update an existing key.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spacewander** [comment]
There is no name in Consumer. For Consumer, the username is id.

**Comment by 18300618319** [comment]
需要加一下名称




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 晚上6:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] conmuser does not support editing (#5114)





 
There is no name in Consumer. For Consumer, the username is id.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spacewander** [comment]
Why? There is already a username.

**Comment by 18300618319** [comment]
需要有id




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月22日(星期三) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] conmuser does not support editing (#5114)






为什么已经有用户名了。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by spacewander** [comment]
The username is already acted as id.

**Comment by 18300618319** [comment]
需要区分开


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月22日(星期三) 晚上6:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] conmuser does not support editing (#5114)





 
The username is already acted as id.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by spacewander** [comment]
We used to have a separate id and username, and it caused confusion.
So we only keep the username and remove the id.
See
https://github.com/apache/apisix-dashboard/issues/718#issuecomment-723512066
https://github.com/apache/apisix/issues/2651
https://github.com/apache/apisix/pull/2679
