### ISSUE TITLE
request help: APISIX can export current configratures to apisix.yaml

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#5119]
### Issue description

(1) when upgrade from etcd v2 to v3, due to compatibility issues, v2 cannot be directly upgraded to v3. The configuration file can be used as an intermediate transition.
(2) It is converient for duplicate one config to another
(3) K8S and other softwares have exporting config function

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
One of our enthusiastic users writes a tool to do it, see https://github.com/apache/apisix/issues/5957

> fetch admin api convert to file
