### ISSUE TITLE
消费者可以添加上name和id吗

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5123]
### Issue description

消费者可以添加上name和id吗

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
消费者可以添加上name和id吗

**Comment by spacewander** [comment]
We used to do this. But it is not a good idea and we don't want to revert back to the old implementation. See https://github.com/apache/apisix/issues/5114#issuecomment-924802517
