### ISSUE TITLE
bug: apisix 2.9 didn't support skywalking 8.7.0

### ISSUE THREAD

**Issue by macaty** [apache/apisix#5133]
### Issue description

apisix 2.9 启用skywalking插件，发送到skywalking 8.7.0版本的，skywalking无法解析，ui里面显示空白。
降级skywalking 8.3版本就可以了正常了。

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`):Linux 240D135 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
- apisix-dashboard version, if have: 2.8
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1、安装apisix 2.9
2、启用apisix的skywalking插件
    plugins:
      - skywalking   
    plugin_attr:
      skywalking:   
        service_name: APISIX
        service_instance_name: $hostname
        endpoint_addr: http://192.168.xxx0:12800
3、dashboard启用全局配置
{
  "disable": false,
  "sample_ratio": 1
}

### Actual result

4、安装skywalking 8.7.0 oap和ui
查看数据，空白显示

5、安装安装skywalking 8.3.0 oap和ui
查看数据，正常

### Error log

无错误log

### Expected result

无错误日志

**Comment by macaty** [comment]
![Uploading 微信图片_20210923134348.jpg…]()

**Comment by macaty** [comment]
![QQ图片20210924184622](https://user-images.githubusercontent.com/16797633/134662527-360e8534-954d-4de0-80ee-7af9289de5d8.png)

**Comment by macaty** [comment]
![QQ图片20210924184622](https://user-images.githubusercontent.com/16797633/134662707-fc3fcc62-43bb-402a-bb4a-d941530968b8.png)
8.3 working good

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/skywalking.md#run-skywalking-example, the example used here is skywalking 8.3, and I don't think this is a bug.

I don't know what changes between skywalking 8.7 and 8.3, maybe we should update https://github.com/apache/skywalking-nginx-lua to support skywalking 8.7.

@spacewander @membphis what's your options?

**Comment by macaty** [comment]
thx

**Comment by spacewander** [comment]
Does https://github.com/apache/apisix/pull/5139 solve the problem?

**Comment by macaty** [comment]
Can you build a docker image for me to test?

**Comment by tzssangglass** [comment]
> Can you build a docker image for me to test?

do it yourself, you can refer to: https://github.com/apache/apisix-docker/blob/master/centos/Dockerfile

**Comment by dmsolr** [comment]
> ![QQ图片20210924184622](https://user-images.githubusercontent.com/16797633/134662527-360e8534-954d-4de0-80ee-7af9289de5d8.png)
> 8.7.0 show nothing

Seem like it collected the tracing segment. You could try to pick up the proper time zone and time range, and then click `reload` at the right top.
