### ISSUE TITLE
bug: radixtree_host_uri match pattern causes the prometheus metrics information to be incorrect

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#5134]
### Issue description

When I set the route matching pattern to radixtree_host_uri, I can see that the matched_uri in the matched_host in the metrics becomes a matched_host, and the order is exactly the opposite of host, and the matched_host is empty， as follows
```
apisix_http_status{code="101",route="test_master_route",matched_uri="moc.retsam.2ipa",matched_host="",service="",consumer="",node="xxxx"} 2
apisix_http_status{code="101",route="test_master_route",matched_uri="moc.retsam.2ipa",matched_host="",service="",consumer="",node="xxx"} 4
apisix_http_status{code="101",route="test_master_route",matched_uri="moc.retsam.2ipa",matched_host="",service="",consumer="",node="xxx"} 3
```

But my real matched_uri is **/hello**, and matched_host is **api2.master.com**

### Environment

- apisix version (cmd: `apisix version`):  2.9
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1. the route matching pattern is configured as radixtree_host_uri
2. check out metrics： curl http://127.0.0.1:9091/apisix/prometheus/metrics

### Actual result

matched_uri and matched_host do not match expectations，The expected results are as follows

matched_uri: /hello
matched_host: api2.master.com

### Error log

none

**Comment by tzssangglass** [comment]
can be fixed by: https://github.com/apache/apisix/pull/5124

**Comment by zuiyangqingzhou** [comment]
well done
