### ISSUE TITLE
request help:  How do I start multiple instances

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#5143]
### Issue description

Assuming I have two different profiles in the conf directory: config-a.yaml and conffig-b.yaml. 

How do I start  different instances by specifying different profiles?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/blob/master/docs/en/latest/profile.md

**Comment by zuiyangqingzhou** [comment]
Thank you very much
