### ISSUE TITLE
request help: use name instead of id in grafana dashboard

### ISSUE THREAD

**Issue by starsz** [apache/apisix#5149]
### Issue description

Hi, I found that now we use the service id and route id in the grafana dashboard.
Which is not friendly to read. So I recommend we can use name instead of id in the grafana dashboard.

Now:
![image](https://user-images.githubusercontent.com/25628854/135027767-62309cd3-589a-48de-baf7-2a39d6c9d55f.png)
![image](https://user-images.githubusercontent.com/25628854/135027792-b6038228-d697-49ef-b861-dec9343a8f7a.png)

### Environment

- apisix version (cmd: `apisix version`): 2.6 
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
The default label of prometheus is id but not name.

**Comment by starsz** [comment]
Yes.I think we can use the name as the label of Prometheus if the name exists?

**Comment by lifehacking** [comment]
@starsz  how solved label name view？
