### ISSUE TITLE
docs: When will APisix have RSA, AES encryption, or national secret plugins?

### ISSUE THREAD

**Issue by xuyancheng24** [apache/apisix#5162]
### Issue description

docs: When will APisix have RSA, AES encryption, or national secret plugins?

### Environment

- apisix version (cmd: `apisix version`):2.10
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
What feature are you expected in those plugins? Could you provide a detailed purposal?

**Comment by tzssangglass** [comment]
relate: https://github.com/apache/apisix/issues/953

**Comment by tzssangglass** [comment]
According to the 953 description, openssl 1.1.1 supports national secret, I'm not sure.

**Comment by xuyancheng24** [comment]
I want to provide encryption and decryption of the request body parameter
