### ISSUE TITLE
bug: plugin wolf-rbac  /apisix/plugin/wolf-rbac/login  resturn header is text/plain ,  cors error

### ISSUE THREAD

**Issue by laokan** [apache/apisix#5165]
### Issue description

1. the pluginx  wolf-rbac  's  login url /apisix/plugin/wolf-rbac/login return the json but header give  the content-type is text/plain,  when the browsr crossdomain post then show the cors error, please change the plugin login post give the Content-type  to application/json 

2. The wolf-rabc 's login uri /apisix/plugin/wolf-rbac/login will lose the cors plugin add the Header

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

post /apisix/plugin/wolf-rbac/login  show the response header

### Actual result

text/plain

### Error log

the browser given the cors error

**Comment by spacewander** [comment]
My bad! It is not about providing cors to wolf-rbac login. We just need to fix the login handler with `core.response.set_header("Content-Type", "application/json")`

**Comment by laokan** [comment]
after at /usr/local/apisix/apisix/plugins/wolf-rabc.lua  add core.response.set_header("Content-Type", "application/json" 
the response give the right header but The browser given the CORS error

**Comment by laokan** [comment]
diff The work and not work I found
not work：
`HTTP/1.1 200 OK
Date: Fri, 08 Oct 2021 05:16:50 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.5`
work:
`HTTP/1.1 200 OK
Date: Fri, 08 Oct 2021 05:19:04 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.5
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: *
Access-Control-Max-Age: 5
Access-Control-Expose-Headers: *
Access-Control-Allow-Headers: *`

when rabc-plugin register route ‘apisix/plugin/wolf-rbac/login’ then the Globalroute of cors plugin lose efficacy

**Comment by zhendongcmss** [comment]
> yes, add cors interceptors ，the cors ‘s conf should use the route cors plugin config

Hi @laokan sorry , I don't get your idea. Can you give more details. I want to fix this issue.

**Comment by spacewander** [comment]
Already done with public-api plugin.
