### ISSUE TITLE
bug: Failed to compile openresty

### ISSUE THREAD

**Issue by shengjianzhou** [apache/apisix#5166]
### Issue description

Failed to compile openresty when I use this script file downloaded from  https://raw.githubusercontent.com/api7/apisix-build-tools/master/build-apisix-openresty.sh ，this link  is in the page https://apisix.apache.org/docs/apisix/how-to-build
![微信截图_20211001145422](https://user-images.githubusercontent.com/11906480/135578219-b0577521-8f61-47ee-95a3-5eccf355b273.png)
/

### Environment

- apisix version (cmd: `apisix version`):
`2.9`
- OS (cmd: `uname -a`):
`-Linux CentOS7 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
`1.19.3.2`
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
`3.5.0`
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.sh build-apisix-openresty.sh
`...
objs/addon/src/ngx_http_apisix_module.o: In function `ngx_http_apisix_x509_copy':
/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/../apisix-nginx-module/src/ngx_http_apisix_module.c:96: undefined reference to `X509_up_ref'
objs/addon/src/ngx_http_apisix_module.o: In function `ngx_http_apisix_upstream_set_cert_and_key':
/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/../apisix-nginx-module/src/ngx_http_apisix_module.c:187: undefined reference to `EVP_PKEY_up_ref'
collect2: error: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/nginx-1.19.3'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/nginx-1.19.3'
make: *** [all] Error 2

...`

### Actual result

Failed to compile openresty

### Error log

objs/addon/src/ngx_stream_lua_initworkerby.o \
objs/addon/src/ngx_stream_lua_socket_tcp.o \
objs/addon/src/ngx_stream_lua_socket_udp.o \
objs/addon/src/ngx_stream_lua_args.o \
objs/addon/src/ngx_stream_lua_ssl.o \
objs/addon/src/ngx_stream_lua_balancer.o \
objs/addon/src/ngx_stream_lua_logby.o \
objs/addon/src/ngx_stream_lua_prereadby.o \
objs/addon/src/ngx_stream_lua_semaphore.o \
objs/addon/src/ngx_stream_lua_ssl_certby.o \
objs/addon/src/ngx_stream_lua_log_ringbuf.o \
objs/addon/src/ngx_stream_lua_input_filters.o \
objs/addon/mod_dubbo/ngx_dubbo_util.o \
objs/addon/utils/objects.o \
objs/addon/utils/utils.o \
objs/addon/hessian2/hessian2_ext.o \
objs/addon/hessian2/hessian2_input.o \
objs/addon/hessian2/hessian2_output.o \
objs/addon/mod_dubbo/ngx_dubbo.o \
objs/addon/mod_dubbo/ngx_http_dubbo_module.o \
objs/addon/ngx_multi_upstream_module/ngx_http_multi_upstream_module.o \
objs/addon/ngx_multi_upstream_module/ngx_multi_upstream_module.o \
objs/addon/ngx_multi_upstream_module/ngx_stream_multi_upstream_module.o \
objs/addon/src/ngx_http_apisix_module.o \
objs/addon/src/ngx_http_lua_var_module.o \
objs/ngx_modules.o \
-L/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/lib -L/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,--require-defined=pcre_version -Wl,-E -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -L/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/luajit-root/usr/local/openresty/luajit/lib -lluajit-5.1 -lm -ldl -lstdc++ -lpcre -lssl -lcrypto -ldl -lpthread -lz \
-Wl,-E
objs/addon/src/ngx_http_apisix_module.o: In function `ngx_http_apisix_x509_copy':
/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/../apisix-nginx-module/src/ngx_http_apisix_module.c:96: undefined reference to `X509_up_ref'
objs/addon/src/ngx_http_apisix_module.o: In function `ngx_http_apisix_upstream_set_cert_and_key':
/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/../apisix-nginx-module/src/ngx_http_apisix_module.c:187: undefined reference to `EVP_PKEY_up_ref'
collect2: error: ld returned 1 exit status
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory `/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/nginx-1.19.3'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/tmp/tmp.V5w436RFjl/openresty-1.19.3.2/build/nginx-1.19.3'
make: *** [all] Error 2

### Expected result

 configured, compile, installed openresty successfully

**Comment by spacewander** [comment]
OpenSSL 1.1.1 is need.
Please build apisix-openresty within the given dockerfile in that project instead of just running the build script.

**Comment by spacewander** [comment]
@guoqqqi 
Look like the doc website https://apisix.apache.org/docs/apisix/how-to-build/ doesn't show the latest doc? An old version of 2.9 is shown instead.

**Comment by guoqqqi** [comment]
OK, let me check it out

**Comment by imjoey** [comment]
> > OpenSSL 1.1.1 is need. Please build apisix-openresty within the given dockerfile in that project instead of just running part of the build script.
> 
> I installed the following packages ，but still get the same error yum install -y curl git gcc openresty-openssl111-devel unzip pcre pcre-devel openssl openssl-devel
> 
> BTW: Because I want to install apisix in virtal machine and bare metal server , not in docker environment Thinks

@shengjianzhou 

Hi, please clone the code https://github.com/api7/apisix-build-tools and use the following command to generate the apisix-base-1.0.0-0.el7.x86_64.rpm, which represents your customized openresty package.

```
$ make package type=rpm app=apisix-base version=1.0.0 image_base=centos image_tag=7`
ls output/
apisix-base-1.0.0-0.el7.x86_64.rpm
```

If you want to customize your openresty, please make your own changes on https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh. 

This only make use of the docker environment for compiling, the generated artifact is rpm, right for VM installation.

**Comment by tzssangglass** [comment]
same as: https://github.com/apache/apisix/issues/4912

**Comment by lwtju** [comment]
you can  down the package openssl-1.1.1m and configure --with-openssl=../openssl-1.1.1m
