### ISSUE TITLE
request help: How to get ETCD data in plugins?

### ISSUE THREAD

**Issue by yocaning** [apache/apisix#5168]
### Issue description

how to get etcd value in plugins

this is my code

```
authorizations_etcd, error = core.config.new("/authorizations", {
        automatic = true,
        item_schema = app_scheme
    })
    core.log.warn("key: " .. authorizations_etcd.key)
    if not authorizations_etcd then
        core.log.error("failed to create etcd instance for fetching authorizations: " .. error)
        return
    end
    local etcd_token ,err=authorizations_etcd:get("yocantest")
    for i =1 ,#etcd_token  do
        core.log.warn("etcd_token: " .. etcd_token[i])
    end
    if not err then
        core.log.warn(err)
    end
```

the etcd has value ,but i cant get 

> 

### Environment

- apisix version (cmd: `apisix version`):2.2
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by yocaning** [comment]
ok ,i find that why i cant get ,because the etcd data dont change ,so the table dont update after i restart my apisix.
by the way ,what should i do if i want the cache `authorizations_etcd` update after restart apisix 。

**Comment by yocaning** [comment]
new request help：
what should i do if i want the cache `authorizations_etcd` update after restart apisix 。or what i want is load the etcd data before restart apisix

**Comment by tokers** [comment]
> ok ,i find that why i cant get ,because the etcd data dont change ,so the table dont update after i restart my apisix. by the way ,what should i do if i want the cache `authorizations_etcd` update after restart apisix 。

Apache APISIX always fetch the full data from ETCD as it just starts. And now, the default behavior is that APISIX will load them in the init phase (before any requests can be handled).

**Comment by yocaning** [comment]
> > ok ,i find that why i cant get ,because the etcd data dont change ,so the table dont update after i restart my apisix. by the way ,what should i do if i want the cache `authorizations_etcd` update after restart apisix 。
> 
> Apache APISIX always fetch the full data from ETCD as it just starts. And now, the default behavior is that APISIX will load them in the init phase (before any requests can be handled).

yes，see my code，init phase code
function _M.init()：
 authorizations_etcd, error = core.config.new("/authorizations", {
        automatic = true,
        item_schema = app_scheme
    })
    if not authorizations_etcd then
        core.log.error("failed to create etcd instance for fetching authorizations: " .. error)
        return
    end
end 
but when i restart apisix ,the etcd dont hava data until i change the key ,my etcd is ok ,and have data ,the apisix restart dont have
