### ISSUE TITLE
源码本地开发

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5187]
### Issue description

通过源码运行起来，本地改完代码保存后就可以直接看到效果，这种开发方式apisix可以是实现吗
像前端项目就可以改完代码直接看到效果

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
You need to reload/restart the apisix instance.
