### ISSUE TITLE
request help: CI script `install-ext-services-via-docker.sh` optimization of avoid building local image

### ISSUE THREAD

**Issue by leslie-tsang** [apache/apisix#5188]
### Issue description

I found code below will build a local container image `nacos-test-service:1.0-SNAPSHOT`, it may be better to use an apisix official docker image to replace it.
https://github.com/apache/apisix/blob/03a1c760845e7666d924b4f817a42e8e4c0c7e0b/ci/install-ext-services-via-docker.sh#L57-L58

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Can you submit a PR to replace the script, so that we can know if it can work or not?

**Comment by leslie-tsang** [comment]
> Can you submit a PR to replace the script, so that we can know if it can work or not?

Working on it.
