### ISSUE TITLE
Why plugin list disappear after adding a new plugin?

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5198]
### Issue description

按照文档开完插件后，插件列表里没是怎么回事

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@18300618319 Could you paste more details, I didn't understand the problem clearly. Is that mean you enabled a plugin but it's not effective? Or it means you create your own plugin and try to integrate it?

**Comment by 18300618319** [comment]
![image](https://user-images.githubusercontent.com/26192378/136876370-d78812af-c403-4a5e-b980-ffae691c21ae.png)

**Comment by tokers** [comment]
@18300618319 The merge strategy of `plugins` overrides instead of merging, so you should reserve other plugins, then add your own.

**Comment by 18300618319** [comment]
2021/10/11 19:26:07 [error] 9533#9533: *3798416 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 16s, context: ngx.timer

**Comment by 18300618319** [comment]
![image](https://user-images.githubusercontent.com/26192378/136876582-b0654568-f75a-4555-8b00-2210b1703b16.png)

**Comment by 18300618319** [comment]
这原来都保留着呢

**Comment by shuaijinchao** [comment]
You can check whether the ETCD status is normal through the client. Are there any other problems?
