### ISSUE TITLE
how to config error_page like nginx?

### ISSUE THREAD

**Issue by zhangweidongyyl** [apache/apisix#5199]
### Issue description

In nginx we can config error_page like this:
 
`

        location /test_error_page {
              proxy_pass http://localhost:39084;
              error_page 404 500 503 502 = @errorPage;
        }

        location @errorPage {
           proxy_pass http://localhost:39082/err.html;
        }
`
but how can we config in apisix? I can not find any article 

### Environment

- apisix version (cmd: `apisix version`):2.6
- OS (cmd: `uname -a`):linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
I think it would be better to implement this function through a plug-in. You can get the response code in the header_filter phase and make the next action.

**Comment by nimohunter** [comment]
> > see: https://github.com/apache/apisix/blob/master/docs/zh/latest/customize-nginx-configuration.md, if this is not satisfied, you need to modify
> > https://github.com/apache/apisix/blob/3bc3ef8a74e3c47eda443ca9c8ea1fccfd309596/apisix/cli/ngx_tpl.lua#L269
> 
> I see this，but I need customized error_page for each location ,and the error_page is not the real errpage .so it can not Solve my problem

Is it worth developing a new plugin here? If needed, we can write a new plugin for it.  error handle plugin ?  just redirect to error page according from the response status?
