### ISSUE TITLE
request help: whether to support ngx_http_auth_request_module ?

### ISSUE THREAD

**Issue by guxingke** [apache/apisix#5210]
### Issue description

is have some way to use ngx_http_auth_request_module?
found nothings about ngx_http_auth_request_moudle after check all of the documents.

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
Why not use the authentication method provided by APISIX? [Basic Auth](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/basic-auth.md) or [Remote Auth](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/openid-connect.md).

**Comment by guxingke** [comment]
some historical reasons

---
in my case , it provide a cookie-base sso solution.

**Comment by tzssangglass** [comment]
if you want to compile this module into the openresty that apisix used, you can take a look at:https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh

**Comment by tokers** [comment]
> > @guxingke Use [Customize Nginx Configuration](http://apisix.apache.org/docs/apisix/customize-nginx-configuration/) to enable it.
> 
> i see apisix main logic config in one server block, if i want some hosts with auth and anothers not , how to do it ? and use customize nginx configuration it loss the biggest feature of dynamic configuration by admin api.

That's right, but I think it can be a temporary work around before we have a plugin implementation for it.

> if i want some hosts with auth and anothers not , how to do it ?

It would be tough if we only rely on the static Nginx configuration.

**Comment by zuiyangqingzhou** [comment]
@guxingke   I have done something similar, I also had a requirement that relied on the ngx_http_auth_request_module module, and finally solved it by developing a custom plugin in apisix, essentially the ngx_http_auth_request_module also intercepts the request and then does the corresponding permission authentication, which can be solved by custom plugin is completely solvable

**Comment by guxingke** [comment]
> @guxingke I have done something similar, I also had a requirement that relied on the ngx_http_auth_request_module module, and finally solved it by developing a custom plugin in apisix, essentially the ngx_http_auth_request_module also intercepts the request and then does the corresponding permission authentication, which can be solved by custom plugin is completely solvable

okay, i will try , thanks to all.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
