### ISSUE TITLE
request help: serverless plugin

### ISSUE THREAD

**Issue by panghu-00** [apache/apisix#5213]
### Issue description

serverless插件支持为多个phase添加逻辑吗，例如serverless-pre-function，想在header_filter和body_filter阶段都实现自定义的functions

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
The design that is limited by APISIX plug-in structure is currently not supported. The hash array used in the current plugin structure is not in the form of index array, so the plug-in name under each route cannot be repeated.
