### ISSUE TITLE
request help: support `make uninstall`

### ISSUE THREAD

**Issue by rapiz1** [apache/apisix#5225]
### Issue description

What about support `make uninstall` as a reverse of `make install`?
I assume this requires a little refactor in the Makefile and can be a useful improvement.

### Environment

- apisix version (cmd: `apisix version`): commit 2b23907

**Comment by spacewander** [comment]
@kwanhur 
Would you like to solve this problem?

**Comment by kwanhur** [comment]
> @kwanhur Would you like to solve this problem?

yep, I'll work on it.
