### ISSUE TITLE
bug: INST_CONFDIR is missing in Makefile

### ISSUE THREAD

**Issue by rapiz1** [apache/apisix#5228]
### Issue description

https://github.com/apache/apisix/blob/2b239077432a8af1812c5f95fc5f01b748abaabf/Makefile#L328
Here `INST_CONFDIR` is never defined in the Makefile. So if https://github.com/apache/apisix#get-started is followed, `README.md` will be installed to `/README.md`, which is completely not expected.

### Environment

- apisix version (cmd: `apisix version`): https://github.com/apache/apisix/commit/2b239077432a8af1812c5f95fc5f01b748abaabf

### Steps to reproduce

1. Follow https://github.com/apache/apisix#get-started

### Actual result

```
# make install
...
install apisix/stream/router/*.lua /usr/share/lua/5.1/apisix/stream/router/
install -d /usr/share/lua/5.1/apisix/utils
install apisix/utils/*.lua /usr/share/lua/5.1/apisix/utils/
install README.md /README.md
install bin/apisix /usr/bin/apisix
install -d /usr/share/lua/5.1/apisix/plugins/slslog
install apisix/plugins/slslog/*.lua /usr/share/lua/5.1/apisix/plugins/slslog/
```

### Error log

```
install bin/apisix /usr/bin/apisix
```
is not expected

### Expected result

Install to some config directory of APISIX?
Or drop the README.md completely off the installation.

**Comment by leslie-tsang** [comment]
Indeed, install `README.md` to `/README.md` is unexpected behavior.
VAR `INST_CONFDIR` was defined by rockspec during `luarocks install`, maybe we should define `INST_CONFDIR` in Makefile to avoid this. 
> Ref to #5140 
We can separate makefile target as well.
