### ISSUE TITLE
bug: http request to upstream, roundrobin is imbalance when multi nginx worker process

### ISSUE THREAD

**Issue by wbaweto** [apache/apisix#5246]
### Issue description

nginx worker process num: 16
upstream nodes num: 10
balance type: roundrobin
roundrobin is imbalance

### Environment

- apisix version : 2.10.0
- OS: Linux  3.10.0-1127.10.1.el7.x86_64
- OpenResty version: openresty/1.17.8.2

### Steps to reproduce

1.upstream config:
`{
  "nodes": [
    {
      "host": "10.0.9.148",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.158",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.126",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.127",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.130",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.131",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.133",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.128",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.134",
      "port": 80,
      "weight": 100
    },
    {
      "host": "10.0.9.138",
      "port": 80,
      "weight": 50
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "test api",
  "desc": "test api upstreams",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}`

upstream nodes:  9 node's weight is 100,  1 node's weight is 50.
**node 10.0.9.138 weight is 50**

### Actual result

http request num: ab -n 100 -c 10

1、lua-resty-balancer version: 0.02rc5, nginx worker process num: 16
rounrobin upstream node request count:
10.0.9.130:80:17
10.0.9.128:80:11
10.0.9.131:80:12
10.0.9.148:80:15
10.0.9.126:80:3
10.0.9.158:80:6
10.0.9.133:80:15
10.0.9.127:80:5
10.0.9.134:80:16

**result is unbalance, but is wrong。 weight:50(10.0.9.138) is not requested**

4、lua-resty-balancer version: 0.02rc5, nginx worker process num: 1
rounrobin upstream node request count:
10.0.9.130:80:11
10.0.9.128:80:10
10.0.9.131:80:11
10.0.9.148:80:11
10.0.9.126:80:10
10.0.9.158:80:10
10.0.9.133:80:11
10.0.9.138:80:5
10.0.9.127:80:10
10.0.9.134:80:11
**result is balance, weight is effect, is right**

3、lua-resty-balancer version: 0.04, nginx worker process num: 16
rounrobin upstream node request count:
10.0.9.130:80:10
10.0.9.128:80:11
10.0.9.131:80:12
10.0.9.148:80:13
10.0.9.126:80:12
10.0.9.158:80:8
10.0.9.133:80:12
10.0.9.127:80:11
10.0.9.134:80:11

**result is relatively balance, but is wrong。 weight:50(10.0.9.138) is not requested**

4、lua-resty-balancer version: 0.04, nginx worker process num: 1
rounrobin upstream node request count:
10.0.9.130:80:11
10.0.9.128:80:10
10.0.9.131:80:10
10.0.9.148:80:11
10.0.9.158:80:10
10.0.9.133:80:10
10.0.9.126:80:11
10.0.9.138:80:5
10.0.9.127:80:11
10.0.9.134:80:11

**result is balance, weight is effect, is right**

### Error log

experiment result: 
1、where lua-resty-balancer version is 0.02rc5，upstream nodes and nginx worker process num is more, balancer upstream result is very unbalance
2、nginx worker process is multi, weight roundrobin is wrong

### Expected result

rounrobin upstream node request count:
10.0.9.130:80:11
10.0.9.128:80:10
10.0.9.131:80:10
10.0.9.148:80:11
10.0.9.158:80:10
10.0.9.133:80:10
10.0.9.126:80:11
10.0.9.138:80:5
10.0.9.127:80:11
10.0.9.134:80:11

**result is balance, weight is effect, is right**

**Comment by tzssangglass** [comment]
@spacewander I think roundrobin works on a single worker, right?

**Comment by wbaweto** [comment]
> @spacewander I think roundrobin works on a single worker, right?

You can think so.

**Comment by HelloBug0** [comment]
If you want roundrobin works in all workers, may be you can try [this](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#zone) @wbaweto

**Comment by kwanhur** [comment]
Note it: the mentioned `RR` algorithm should be `WRR`  or `SWRR`, [Smooth Weighted Round-Robin](https://github.com/phusion/nginx/commit/27e94984486058d73157038f7950a0a36ecc6e35).

**Comment by tzssangglass** [comment]
> Note it: the mentioned `RR` algorithm should be `WRR` or `SWRR`, [Smooth Weighted Round-Robin](https://github.com/phusion/nginx/commit/27e94984486058d73157038f7950a0a36ecc6e35).

it's WRR, the `weight` has already been mentioned above.

**Comment by membphis** [comment]
hi @wbaweto 

The weight calculation of rr is done in a single worker process.

If you want to compute between multiple workers, performance will decrease.

If you still have problems, you can reopen this issue.
