### ISSUE TITLE
Proposal: support the upstream TLS settings for the stream subsystem

### ISSUE THREAD

**Issue by tokers** [apache/apisix#5247]
### Issue description

I noticed that the stream subsystem doesn't support the TLS settings for the upstream, also the upstream object itself already supports it.

We may also support it, but the `proxy_ssl` directive in stream subsystem doesn't support the variable substitution. We may resort to the apisix-nginx-module.

What's your idea?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
> Kong uses a patch to disable proxy_ssl if the upstream is not TLS, and set `proxy_ssl on` by default. IMHO, it would be better to set `proxy_ssl off` by default, and turn it on if the upstream is not TLS, which is more straightforward.

Exactly.

**Comment by Canonical10** [comment]
✅

**Comment by Canonical10** [comment]
✅
