### ISSUE TITLE
request help: schema validate failed: labels: Must have at most 16 properties

### ISSUE THREAD

**Issue by StretchV** [apache/apisix#5251]
### Issue description

when i create more 16 labels,there is a tips:schema validate failed: labels: Must have at most 16 properties,how can i set more than 16 labels?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Maybe we can increase length of the labels? CC @imjoey @liuxiran
