### ISSUE TITLE
apisix needs to support more powerful limit-req

### ISSUE THREAD

**Issue by zenglongfeng** [apache/apisix#5254]
### Issue description

I think the apisix limit-req plugin needs to support combined conditions to limit the request frequency and support whitelisting; just like the tengine limit-req module, it supports multiple conditional restrictions, such as: http_x_forward & http_user_agent are used to limit the request frequency and support white names.
This is the module documentation of tengine limit-req
https://tengine.taobao.org/document_cn/http_limit_req_cn.html

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by jagerzhang** [comment]
感觉和我之前提的需求有点类似：https://github.com/apache/apisix/issues/4760 更精细化的限速条件。
