### ISSUE TITLE
request help: domain name plus port access

### ISSUE THREAD

**Issue by Rehtt** [apache/apisix#5260]
### Issue description

Can domain plus port access?
eg:
`test1.com:1234  ->  1.1.1.1:1234`

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Yes
