### ISSUE TITLE
can apisix be configured with multiple etcd host?

### ISSUE THREAD

**Issue by zgLiuBing** [apache/apisix#5289]
### Improved or typo fixed.

![Uploading ff6543a31d9ab40f61693edc1fb3e29.jpg…]()
apisix可以配置多个etcd吗

### Solution

![ff6543a31d9ab40f61693edc1fb3e29](https://user-images.githubusercontent.com/26192378/138068693-ac636c27-9d52-4d10-a8a4-345466aabe99.jpg)
apisix可以配置多个etcd吗

**Comment by tzssangglass** [comment]
Consider solved. Feel free to reopen it if need.
