### ISSUE TITLE
Is etcd multi-copy?

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5290]
### Issue description

apisix中的etcd是多副本的吗

### Environment

apisix中的etcd是多副本的吗
怎么保证高可用和数据不丢失

**Comment by tzssangglass** [comment]
> 怎么保证高可用和数据不丢失

refer to:https://github.com/apache/apisix/blob/master/docs/zh/latest/FAQ.md#%E5%A6%82%E4%BD%95%E5%88%9B%E5%BB%BA%E9%AB%98%E5%8F%AF%E7%94%A8%E7%9A%84-apache-apisix-%E9%9B%86%E7%BE%A4

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
