### ISSUE TITLE
how to support multiple nodes balance on MQTT proxy?

### ISSUE THREAD

**Issue by siaron** [apache/apisix#5304]
### Issue description

mqtt 代理如何配置可以支持多节点负载均衡?

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`): macos
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
Currently, only one endpoint can be configured in the MQTT plugin, a feasible work around plan is add another indirect L4 proxy (we can just use the apisix itself), and let the MQTT proxy to the L4 proxy, configure an Upstream with multiple nodes in L4 proxy.

Of course, PR's welcome to extend the MQTT plugin.

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/5666
