### ISSUE TITLE
request help: APISIX Proxy-mirror plugin support custom path

### ISSUE THREAD

**Issue by sunnycjd** [apache/apisix#5305]
### Issue description

Currently I has test the proxy-mirror plugin in apisix, but I find that the feature of this plugin is different from the ngx_http_mirror_module in nginx. The mirror moudle of nginx can add the uri behind the host in "proxy_pass" directive, for example 
```
location / {
mirror /mirror;
proxy_pass http://backend;
}

location = /mirror {
internal;
proxy_pass http://test_backend$request_uri;
}
```
But when I test the proxy-mirror plugin in apisix dashboard, it prompts a message that the blank cannot be filled with URI. 
![image](https://user-images.githubusercontent.com/35248300/138317932-35e36ef5-2444-4876-84b6-b40a8432fa1d.png)

Will the proxy-mirror plugin be optimized to support the URI?

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):3.10.0-1160.42.2.el7.x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by sunnycjd** [comment]
> The path of the mirror request is always the path of the original request currently. Do you mean you want a custom path? Like mirroring "/a" to host "x.x.x.x"'s "/b" path?

Yes, that‘s what I means.

**Comment by zaunist** [comment]
If we need custom path, why not use `proxy-rewrite` plugin ? So I think there is no need to introduce this feature in the plugin.
