### ISSUE TITLE
request help: kafka logger supports logging response body

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#5344]
### Issue description

Same with https://github.com/apache/apisix/issues/5343 but for response body. Response body can be fetched by core.response.hold_body_chunk.

### Environment

- apisix version (cmd: `apisix version`): 2.10.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by qq54903099** [comment]
I just want to know when can support this issue

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/pull/5501

**Comment by qq54903099** [comment]
> see: #5501

但是我看这个issue里描述的内容不是requestBody么？好像没有responseBody

**Comment by tzssangglass** [comment]
> > see: #5501
> 
> 但是我看这个issue里描述的内容不是requestBody么？好像没有responseBody

my mistake. wait for someone to take this.

**Comment by dmsolr** [comment]
May I pick this one up?
