### ISSUE TITLE
request help: how to hide or change response server info

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#5353]
### Issue description

how hide or change response server info
![image](https://user-images.githubusercontent.com/3895272/139186432-40d146ac-e679-4ff6-8d02-7fede3b2f43d.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by mkyc** [comment]
out of curiosity @tzssangglass why `can not ignore Server header`?

**Comment by SkyeYoung** [comment]
@mkyc No one has raised a similar question before. If you think this is an issue, you can create one.

The feature comes from: https://github.com/apache/apisix/pull/2639

**Comment by mkyc** [comment]
I just got questions from security team why do we even publish that header at all. #2639 mentions dangers but if bad actor knows it's ApiSix it still helps them, they just have [more CVEs](https://www.cvedetails.com/version-list/45/87329/1/Apache-Apisix.html) to check.

**Comment by SkyeYoung** [comment]
@mkyc Hi, please don't raise new questions in an issue that has already been closed.  Currently, APISIX's approach is actually the same as NGINX's `server_tokens off;`.

I think your idea is a new requirement and can be raised as an issue.
