### ISSUE TITLE
request help: I have a url with # how can i config forward

### ISSUE THREAD

**Issue by jaredhuang** [apache/apisix#5356]
### Issue description

Dear all:
my backend have a Url : http://172.20.151.99:10003/#/login?redirect=%2F%23%2F
I set Upstream like this : 
![image](https://user-images.githubusercontent.com/5996364/139210088-d660e0d8-5319-48ce-be94-a3057f18c3e6.png)
Set route like this:
![image](https://user-images.githubusercontent.com/5996364/139210225-586f2314-5f89-4611-8613-25b9757fbd50.png)
but it can't work .  but I set in nginx like this : 
![image](https://user-images.githubusercontent.com/5996364/139210920-a0400cae-14d9-4742-9eda-b358bce07d06.png)
Nginx can forward .
how do i solve this problem .  

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`): CentOS Linux release 7.8.2003 (Core)
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 2.10.0
- apisix-dashboard version, if have: apisix-dashboard-2.9.0-0.el7.x86_64.rpm
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
> > > but nginx can work . Other solutions ？
> > 
> > 
> > Could you provide a curl cmd to reproduce it ?
> 
> This is screenshot is nginx gw: ![image](https://user-images.githubusercontent.com/5996364/139392048-b1f4fe3d-6335-424e-9a3b-f9caebb53378.png)
> 
> This is apisix gw: ![image](https://user-images.githubusercontent.com/5996364/139392211-a6b861a6-2d25-436d-9d4f-0396bc6aa51f.png)

Obviously, the curl utility also filtered the URL components after the `#` symbol, so the proxy failure is not caused by the `#` symbol, could you show the route details configured to APISIX?

**Comment by jaredhuang** [comment]
@tokers 
![image](https://user-images.githubusercontent.com/5996364/139615179-a720d0ca-c38d-43d9-b706-34f79f44b5e5.png)
![image](https://user-images.githubusercontent.com/5996364/139615275-13d8fdb8-6ce2-4569-973c-aa48cd8030ce.png)

**Comment by tokers** [comment]
It seems that the Route details are quite correct, could you check out the connection status between APISIX and the ETCD cluster?

**Comment by jaredhuang** [comment]
> It seems that the Route details are quite correct, could you check out the connection status between APISIX and the ETCD cluster?

![image](https://user-images.githubusercontent.com/5996364/139651891-1b50c2b3-8179-431d-9d07-a04b6d698c2e.png)

**Comment by tokers** [comment]
> > It seems that the Route details are quite correct, could you check out the connection status between APISIX and the ETCD cluster?
> 
> ![image](https://user-images.githubusercontent.com/5996364/139651891-1b50c2b3-8179-431d-9d07-a04b6d698c2e.png)

I mean the connection status from APISIX's perspective. Have you ever seen any error log entries in `error.log`?

**Comment by jaredhuang** [comment]
> I mean the connection status from APISIX's perspective. Have you ever seen any error log entries in `error.log`?
error.log no any output , and "I mean the connection status from APISIX's perspective" the command is ?

**Comment by jaredhuang** [comment]
i config route in apisix-2.1-0.noarch ,it can work ,and forward it is ok ,why ?

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/issues/7169#issuecomment-1141582991

> i config route in apisix-2.1-0.noarch ,it can work ,and forward it is ok ,why ?

because #5458 has been released since v2.11, this PR fixes the insecure URI encoding.
