### ISSUE TITLE
request help: Could Apache APISIX process traffic control with tcp/ip protocol?

### ISSUE THREAD

**Issue by yunfhu** [apache/apisix#5357]
Is apisix able process traffic control with tcp/ip protocol?

**Comment by yunfhu** [comment]
> > Is apisix able process traffic control with tcp/ip protocol?
> 
> Yes, you can use the `limit-conn` plugin in the stream sub-system, see https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua.
> 
> However, it's not feasible to limit the bandwidth through APISIX stream plugins, you may have to write your own.

we have tried use the limit-conn plugin to control tcp/ip traffic, it seems not work

**Comment by yunfhu** [comment]
> > Is apisix able process traffic control with tcp/ip protocol?
> 
> Yes, you can use the `limit-conn` plugin in the stream sub-system, see https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua.
> 
> However, it's not feasible to limit the bandwidth through APISIX stream plugins, you may have to write your own.

Any other traffic control plugin for tcp/ip traffic?

**Comment by tokers** [comment]
> > > Is apisix able process traffic control with tcp/ip protocol?
> > 
> > 
> > Yes, you can use the `limit-conn` plugin in the stream sub-system, see https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua.
> > However, it's not feasible to limit the bandwidth through APISIX stream plugins, you may have to write your own.
> 
> thanks, the limit-conn plugin works well for tcp/ip,any other traffic control plugin for tcp/ip traffic?

If I remember correctly, currently, we can just use this.

**Comment by yunfhu** [comment]
> > > > Is apisix able process traffic control with tcp/ip protocol?
> > > 
> > > 
> > > Yes, you can use the `limit-conn` plugin in the stream sub-system, see https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua.
> > > However, it's not feasible to limit the bandwidth through APISIX stream plugins, you may have to write your own.
> > 
> > 
> > thanks, the limit-conn plugin works well for tcp/ip,any other traffic control plugin for tcp/ip traffic?
> 
> If I remember correctly, currently, we can just use this.

Ok,really appreciate

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
