### ISSUE TITLE
request help: hmac-auth why not support timestamp?

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5362]
### Issue description

hamc-auth Date why not support timestamp ?

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
