### ISSUE TITLE
request help: 如何配置nacos作为服务发现

### ISSUE THREAD

**Issue by jaiminZhang** [apache/apisix#5366]
### Issue description

请教问题
环境简述 使用apisix作为k8s的网关
上游服务希望通过nacos作为注册服务发现，请问如何配置nacos的地址？
如果需要再配置文件配置，服务重新拉取会不会丢失？

**Comment by jaiminZhang** [comment]
多谢大佬

**Comment by juzhiyuan** [comment]
@jaiminZhang We have a better render website, see https://apisix.apache.org/docs/apisix/discovery/nacos
