### ISSUE TITLE
request help: In the registration information of apisix to etcd, the ip and port information of the apisix service is not included. How can this be configured and obtained?

### ISSUE THREAD

**Issue by chendingxing** [apache/apisix#5368]
### Issue description

apisix往etcd注册信息里面，没有包含apisix服务的ip和端口信息，这个可以如何配置获取吗request help: 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by chendingxing** [comment]
> Do you mean the IP and port information of the APISIX node machine? This information is currently not stored in ETCD.

yes,how can i get the IP and port information of the APISIX node machine by other way

**Comment by tokers** [comment]
> yes,how can i get the IP and port information of the APISIX node machine by other way

Maybe you can extend the server-info plugin of APISIX, so that it can save it to ETCD.

**Comment by shuaijinchao** [comment]
@chendingxing I think @tokers  answer is a good way.
