### ISSUE TITLE
docs: add guide to add and run tests locally 

### ISSUE THREAD

**Issue by rapiz1** [apache/apisix#5369]
### Improved or typo fixed.

I've added tests locally but failed to validate my tests. Surprisingly, I found that there's no doc about how to add and run tests. A simple search in the source leads me to `make test`. However, that doesn't work on my machine.

### Solution

It's better if there were docs about how to add and run tests properly, like, in `CONTRIBUTING.md`

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
