### ISSUE TITLE
request help: health check doesn't work

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5379]
### Issue description

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/health-check.md
`{
  "uri": "/index.html",
  "name": "sdfdsf",
  "plugins": {
    "limit-count": {
      "allow_degradation": false,
      "count": 2,
      "key": "remote_addr",
      "policy": "local",
      "rejected_code": 503,
      "show_limit_quota_header": true,
      "time_window": 60
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "127.0.0.1",
        "port": 1970,
        "weight": 1
      },
      {
        "host": "127.0.0.1",
        "port": 1980,
        "weight": 1
      }
    ],
    "retries": 2,
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "checks": {
      "active": {
        "concurrency": 10,
        "healthy": {
          "http_statuses": [
            200,
            302
          ],
          "interval": 2,
          "successes": 1
        },
        "host": "foo.com",
        "http_path": "/status",
        "port": 80,
        "req_headers": [
          "User-Agent: curl/7.29.0"
        ],
        "timeout": 5,
        "type": "http",
        "unhealthy": {
          "http_failures": 2,
          "http_statuses": [
            429,
            404,
            500,
            501,
            502,
            503,
            504,
            505
          ],
          "interval": 1,
          "tcp_Failures": 2,
          "timeouts": 3
        }
      },
      "passive": {
        "healthy": {
          "http_statuses": [
            200,
            201
          ],
          "successes": 3
        },
        "type": "http",
        "unhealthy": {
          "http_failures": 3,
          "http_statuses": [
            500
          ],
          "tcp_failures": 3,
          "timeouts": 7
        }
      }
    },
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}`

`curl localhost:9090/v1/healthcheck`
返回为空

![image](https://user-images.githubusercontent.com/3895272/139528493-fe82af9e-d6d8-446d-9112-2fd63b666ed2.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
The health check is lazy loaded, you need to let the apisix proxy request to upstream, and then the health check will be available.
