### ISSUE TITLE
request help: path parameter in the route

### ISSUE THREAD

**Issue by hozaifaaoud** [apache/apisix#5389]
### Issue description

I need to put the id as a path parameter in the route... How can I apply this using apisix dashboard?
Here is an example
http://127.0.0.1:9080/v1/users/{id}
I tried this
http://127.0.0.1:9080/v1/users/*
but it returns
{"status":400,"message":"#/id: expected type: Integer, found: String"}

### Environment

- apisix version (cmd: `apisix version`): 2.5
- OS (cmd: `uname -a`): linux ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):  3.4.13
- apisix-dashboard version, if have: 2.6
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

**Comment by tokers** [comment]
@hozaifaaoud The pronoun `it` is ambiguous, do you mean the apisix-dashboard returns `{"status":400,"message":"#/id: expected type: Integer, found: String"}`? Could you give some details about the route editing page?
