### ISSUE TITLE
request help: How to enable logging for the four-layer proxy stream route? 

### ISSUE THREAD

**Issue by feeops** [apache/apisix#5400]
### Issue description

七层的http日志是存储在acccess.log中的

四层代理stream route如何启用日志并自定义日志路径呢？

传统的openresty是可以实现的

### Environment

最新版

**Comment by spacewander** [comment]
We haven't supported it yet. PR is welcome!

**Comment by feeops** [comment]
> We haven't supported it yet. PR is welcome!

结合tcp-logger插件能实现吗？

**Comment by spacewander** [comment]
No

**Comment by spacewander** [comment]
You can add access log configuration in https://github.com/apache/apisix/blob/042ce5c1a6a4e040d6d6924f2d86e5534b730134/conf/config-default.yaml#L176 and render in the template. See https://nginx.org/en/docs/stream/ngx_stream_log_module.html

**Comment by feeops** [comment]
> You can add access log configuration in
> 
> https://github.com/apache/apisix/blob/042ce5c1a6a4e040d6d6924f2d86e5534b730134/conf/config-default.yaml#L176
> 
> and render in the template. See https://nginx.org/en/docs/stream/ngx_stream_log_module.html

这个不起作用，可以在config.yaml中添加
```
nginx_config:
  stream_configuration_snippet: |
    log_format basic '$remote_addr [$time_local] $protocol $status $bytes_sent $bytes_received  $session_time $upstream_addr $upstream_bytes_sent $upstream_bytes_received $upstream_connect_time';
    access_log logs/access_stream.log basic;
```
