### ISSUE TITLE
request help: could proxy_mirror copy traffic to nginx-ingress-controller on L4?

### ISSUE THREAD

**Issue by fish2018** [apache/apisix#5404]
### Issue description

![avatar](https://raw.githubusercontent.com/fish2018/files/master/imgs/proxy_mirror_issue.png)

我要跨云复制流量，从左边的阿里云复制流量到右边的腾讯云
proxy_mirror插件是否支持复制流量直接四层转发到nginx-ingress-controller?
proxy_mirror是否支持配置多个host？

**Comment by tokers** [comment]
Currently, the proxy_mirror plugin also works on the layer 7.

**Comment by fish2018** [comment]
> Currently, the proxy_mirror plugin also works on the layer 7.
nginx原生是支持四层转发的，需要重新编译nginx时指定--with-stream，现在proxy_mirror插件不支持四层转发，可以解决吗

**Comment by tzssangglass** [comment]
> nginx原生是支持四层转发的，需要重新编译nginx时指定--with-stream，现在proxy_mirror插件不支持四层转发，可以解决吗

Have you used nginx to implement a proxy mirror for streams?  I didn't find some about this on the nginx docs site.
