### ISSUE TITLE
request help: migrate Kong to APISIX

### ISSUE THREAD

**Issue by kehuili** [apache/apisix#5406]
### Issue description

Hi, I was trying to use kong-to-apisix to migrate Kong to APISIX, and I followed detail guide.

At first I got some pattern errors in log, so I just deleted consumers to make it work.
![image](https://user-images.githubusercontent.com/35578392/139868527-de6ed307-c358-429d-acc3-199bc9e7c1aa.png)

However, this time it still didn't work. I did got some warns but there were no errors in log.
![image](https://user-images.githubusercontent.com/35578392/139868608-1d063903-c8f6-4573-a488-b18586addcbb.png)

I would like to know if there are some ways to debug. Thank you.

By the way I also raised a same [issue](https://github.com/api7/kong-to-apisix/issues/35) at kong-to-apisix.

### Environment

- apisix version (cmd: `apisix version`): 2.6
- OS (cmd: `uname -a`): Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
The warn message here does not mean there is an error, the native apisix will also have these warn messages when start

**Comment by shuaijinchao** [comment]
Communicate in https://github.com/api7/kong-to-apisix/issues/35

**Comment by shuaijinchao** [comment]
Move to https://github.com/api7/kong-to-apisix/issues/35 for discussion, close this issue, and open it again if necessary.
