### ISSUE TITLE
bug: enable dubbo proxy ,start apisix occur error

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5410]
### Issue description

when i enable dubbo proxy ,start apisix occur error.

like this 
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua start
nginx: [emerg] unknown directive "multi" in /usr/local/apisix/conf/nginx.conf:148

![image](https://user-images.githubusercontent.com/3895272/140018475-4798b6f7-de2d-499b-b79d-38aee37fb0e3.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`): x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
Please refer to the documentation requirements: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/dubbo-proxy.md#requirement

Check if Tengine's mod_dubbo module is compiled in Openresty.

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
