### ISSUE TITLE
request help: cannot receive traffic after using proxy_mirror plugin

### ISSUE THREAD

**Issue by fish2018** [apache/apisix#5412]
### Issue description

配置：
```
{
  "uri": "/*",
  "host": "demo01.app.com",
  "plugins": {
    "proxy-mirror": {
      "host": "http://demo02.app.com",
      "sample_ratio": 1
    }
  },
  "upstream": {
    "nodes": {
      "172.19.77.23": 1
    },
    "type": "roundrobin"
  }
}
```
现象：

- demo02.app.com直接解析到k8s外的app的ip:port是正常的
- demo02.app.com解析到nginx-ingress-controller，这时候k8s容器中的app日志看不到流量进来,
浏览器访问demo02.app.com是正常的，apisix容器内ping/curl demo02.app.com也正常

这有可能是什么原因？

**Comment by tokers** [comment]
Could you try to send requests to `demo02.app.com` by curl or wget utility, only `ping` is not enough to troubleshoot.

**Comment by fish2018** [comment]
> Could you try to send requests to `demo02.app.com` by curl or wget utility, only `ping` is not enough to troubleshoot.

在apisix容器内curl demo02.app.com正常

**Comment by tokers** [comment]
> > Could you try to send requests to `demo02.app.com` by curl or wget utility, only `ping` is not enough to troubleshoot.
> 
> 在apisix容器内curl demo02.app.com正常

Any error log entries in Apache APISIX?

**Comment by shuaijinchao** [comment]
Are there error logs when using APISIX proxy-mirror plugin to forward traffic?

**Comment by fish2018** [comment]
> > > Could you try to send requests to `demo02.app.com` by curl or wget utility, only `ping` is not enough to troubleshoot.
> > 
> > 
> > 在apisix容器内curl demo02.app.com正常
> 
> Any error log entries in Apache APISIX?
apisix日志里没有报错

**Comment by fish2018** [comment]
> Are there error logs when using APISIX proxy-mirror plugin to forward traffic?

apisix日志里没有报错。这个情况看起来像是复制的流量在nginx-ingress-controller就没进去

**Comment by shuaijinchao** [comment]
> > Are there error logs when using APISIX proxy-mirror plugin to forward traffic?
> 
> apisix日志里没有报错。这个情况看起来像是复制的流量在nginx-ingress-controller就没进去

Does the ingress controller have log records? If not, you can observe it by capturing the packet.

**Comment by fish2018** [comment]
> > > Are there error logs when using APISIX proxy-mirror plugin to forward traffic?
> > 
> > 
> > apisix日志里没有报错。这个情况看起来像是复制的流量在nginx-ingress-controller就没进去
> 
> Does the ingress controller have log records? If not, you can observe it by capturing the packet.
```
"plugins": {
    "proxy-mirror": {
      "host": "http://demo02.app.com",
      "sample_ratio": 1
    }
  }
```
这个host不能是Ingress域名？
我把nginx-ingress-controller换成了apisix-ingress-controller结果一样: demo02.app.com域名单独访问正常，proxy_mirror复制流量不过去

**Comment by tokers** [comment]
From the above diagram, the `demo02.app.com` should point to the APISIX in k8s 02 instead Ingress.

**Comment by fish2018** [comment]
现在可以了，host要指定为客户端最初请求的域名demo01.app.com

**Comment by tzssangglass** [comment]
considered solved, feel free to reopen it.
