### ISSUE TITLE
bug: auto-generated apisix id is likely to be duplicated in containerized environments

### ISSUE THREAD

**Issue by tokers** [apache/apisix#5417]
### Issue description

Currently, Apache APISIX will generate an id while initializing if the user doesn't specify one, and it relies on the [lua-resty-jit-uuid](https://github.com/thibaultcha/lua-resty-jit-uuid) library but without an explicit seed.

https://github.com/apache/apisix/blob/4dafab5afa3293b3d72007517246e01da385f8ef/apisix/core/id.lua#L76-L78

While the jit-uuid library creates the seed by the process id and the time in ngx_lua context.

https://github.com/thibaultcha/lua-resty-jit-uuid/blob/82538049040ae85ff880b79886f21d8593140c7d/lib/resty/jit-uuid.lua#L53-L54

However, in a containerized environment, the process id (the master process) might be the same, i.e. the No. 1 process, also, if users try to deploy Apache APISIX clusters on Kubernetes through the `Deployment` resource, the time might be the same for several Pods, since `ngx.time` doesn't have enough precisions (only at milliseconds level). so the generated apisix id might be duplicated, and if the id is critical, this may cause some fatal problems in the business scenarios.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

N/A

### Actual result

N/A

### Error log

N/A

**Comment by spacewander** [comment]
Maybe we can suffix some rand bytes from https://github.com/thibaultcha/lua-resty-jit-uuid/issues/19#issuecomment-521076462

**Comment by tokers** [comment]
> Maybe we can suffix some rand bytes from [thibaultcha/lua-resty-jit-uuid#19 (comment)](https://github.com/thibaultcha/lua-resty-jit-uuid/issues/19#issuecomment-521076462)

Good idea.

**Comment by spacewander** [comment]
@leslie-tsang 
Would you like to have a try? Thanks!

**Comment by leslie-tsang** [comment]
> @leslie-tsang Would you like to have a try? Thanks!

Sure.

**Comment by leslie-tsang** [comment]
After reading the [lua-resty-jit-uuid's issue](https://github.com/thibaultcha/lua-resty-jit-uuid/issues/19#issuecomment-521076462), there are three solution for this issue:
1. use `resty.random` to generate `UUID`, it depend on OpenSSL `RAND_bytes `
2. use `tostring(table or str)` to get a random seed, Ref to [lua-nginx-module issue #1457](https://github.com/openresty/lua-nginx-module/issues/1457) and [apisix PR #5414](https://github.com/apache/apisix/pull/5414/files#diff-95a2018f002f15f5fb0714075b5ef27a1db113c186bfe20ae705f6023080b38fR214)
3. patch `_G.math.randomseed` like [kong](https://github.com/Kong/kong/blob/fb7a68d497c1104779d650014ba6521bf129f726/kong/globalpatches.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L241-L342) does

@spacewander @tokers What do you guys think ?

**Comment by spacewander** [comment]
I vote for the kong way.

**Comment by tzssangglass** [comment]
vote the kong way too

**Comment by tokers** [comment]
Vote for Kong, it's on a higher level.

**Comment by aseaday** [comment]
Considering a more stable production purpose use, how about we did our best in the k8s environment or something else?
[Project Hipsor](http://www.irisa.fr/caps/projects/hipsor/)

**Comment by membphis** [comment]
how about this way? 

https://github.com/kubernetes/ingress-nginx/blob/30809c066cd027079cbb32dccc8a101d6fbffdcb/rootfs/etc/nginx/lua/lua_ingress.lua#L44

**Comment by aseaday** [comment]
> how about this way?
> 
> https://github.com/kubernetes/ingress-nginx/blob/30809c066cd027079cbb32dccc8a101d6fbffdcb/rootfs/etc/nginx/lua/lua_ingress.lua#L44

It seems like the same as Kong one?

**Comment by membphis** [comment]
After a careful look at the two implementations, the core is the same.

Let's do it.

**Comment by aseaday** [comment]
> After a careful look at the two implementations, the core is the same.
> 
> Let's do it.

I want to fix this bug as an first step to contribute to apisix. As an newbie, I had one question:
1. Need we to patch the math.randomseed or just fix the id problem?

**Comment by membphis** [comment]
Which one is the best, then use which one.

**Comment by membphis** [comment]
I prefer patch `math.randomseed` way

**Comment by aseaday** [comment]
> I prefer patch `math.randomseed` way

If we patch the math.randomsee globally as the [kong](https://github.com/Kong/kong/blob/fb7a68d497c1104779d650014ba6521bf129f726/kong/globalpatches.lua?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L241-L342) way, we need to add a module as the global patch. Is it a good choice to put the module in the core?

**Comment by aseaday** [comment]
Or add randomsed in apisix/patch.lua

**Comment by membphis** [comment]
> Or add randomsed in apisix/patch.lua

I prefer this way. what is your opinion? @spacewander
