### ISSUE TITLE
can use ip:port access ?

### ISSUE THREAD

**Issue by Rehtt** [apache/apisix#5418]
### Issue description

apisix in 192.168.1.2 
eg:
```
192.168.1.2:1234 -> 192.168.1.5:8080
192.168.1.2:2345 -> 192.168.1.6:8090
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
pls describe it more clearly, I can't get it.

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.

**Comment by juzn01** [comment]
i have apisix 3.0 and i want enable control api public to "0.0.0.0" in config.yaml file but it don't work:
enable_control: true
control:
    ip: "127.0.0.1"
    port: 9090
  
curl http://127.0.0.1:9090/v1/healthcheck >> OK
curl http://apisix-ip:9090/v1/healthcheck   >> not OK
Please help me! Thanks!

**Comment by tzssangglass** [comment]
> Please help me! Thanks!

pls open new issue to report your problem.

**Comment by juzn01** [comment]
> > Please help me! Thanks!
> 
> pls open new issue to report your problem.

thank you , i open new issues:
https://github.com/apache/apisix/issues/8484
