### ISSUE TITLE
request help: How to write the rewrite rule

### ISSUE THREAD

**Issue by Caibreeze0908** [apache/apisix#5428]
### Issue description

server {
    listen       80;
    server_name  www.test123.com;
    location ~ ^/$|^/test1/check.do$ {
        if ($http_user_agent ~ Android|iPhone|iPad|UCWEB|MicroMessenger|MQQBrowser|Windows\ Phone) {
            rewrite ^/(.*)$ https://h5.test.com.cn/h5test/index.html#/testdo permanent;
        }

        rewrite ^/(.*) https://test.abc.com/$1 permanent;

        access_log off;
    }
}
How to configure in apifix？

### Environment

- apisix version (cmd: `apisix version`):2.4
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.3
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by bzp2010** [comment]
@Caibreeze0908 You should use the `proxy-rewrite` plugin.

just like this:
```json
{
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "^/(.*)",
        "/test/$1"
      ]
    }
  }
}
```

**Comment by Caibreeze0908** [comment]
This is a different domain name, and it's not proxy_ rewrite plug

**Comment by Caibreeze0908** [comment]
> @Caibreeze0908 You should use the `proxy-rewrite` plugin. Refer to this [document](https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite).
> 
> just like this:
> 
> ```json
> {
>   "plugins": {
>     "proxy-rewrite": {
>       "regex_uri": [
>         "^/(.*)",
>         "/test/$1"
>       ]
>     }
>   }
> }
> ```

This is a different domain name, and it's not proxy_ rewrite plug

**Comment by bzp2010** [comment]
> > @Caibreeze0908 You should use the `proxy-rewrite` plugin. Refer to this [document](https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite).
> > just like this:
> > ```json
> > {
> >   "plugins": {
> >     "proxy-rewrite": {
> >       "regex_uri": [
> >         "^/(.*)",
> >         "/test/$1"
> >       ]
> >     }
> >   }
> > }
> > ```
> 
> This is a different domain name, and it's not proxy_ rewrite plug

@Caibreeze0908 That's the `redirect` plugin, used in a similar way. [document](https://apisix.apache.org/docs/apisix/plugins/redirect)

**Comment by chyoong** [comment]
Hi, has this problem been solved yet? similar https://github.com/apache/apisix/issues/8094
