### ISSUE TITLE
bug: apisix/admin/init.lua:161,if curl -d 'false',return error

### ISSUE THREAD

**Issue by HaoTien** [apache/apisix#5430]
### Issue description

use the cmd: curl http://localhost:9180/apisix/admin/routes/1/enable_websocket -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d 'false'
to modified attribute /admin/routes/1/enable_websocket；
return 500，
init.lua:162: handler(): invalid request body: false err: nil, client: 127.0.0.1, server: , request: "PATCH /apisix/admin/routes/1/enable_websocket HTTP/1.1", host: "localhost:9180"

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):Linux apisix 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): 3.4.0

### Steps to reproduce

1.# create one route
$ curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/index.html",
    "hosts": ["foo.com", "*.bar.com"],
    "remote_addrs": ["127.0.0.0/8"],
    "methods": ["PUT", "GET"],
    "enable_websocket": true,
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "39.97.63.215:80": 1
        }
    }
}'
2.modified the attribute
curl http://localhost:9180/apisix/admin/routes/1/enable_websocket -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d 'false'
3.return 500
500 Internal Server Error

### Actual result

<!DOCTYPE html>
<html>
<head>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
<title>500 Internal Server Error</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>An error occurred.</h1>
<p>You can report issue to <a href="https://github.com/apache/apisix/issues">APISIX</a></p>
<p><em>Faithfully yours, <a href="https://apisix.apache.org/">APISIX</a>.</em></p>
</body>
</html>

### Error log

init.lua:162: handler(): invalid request body: false err: nil, client: 127.0.0.1, server: , request: "PATCH /apisix/admin/routes/1/enable_websocket HTTP/1.1", host: "localhost:9180"

### Expected result

PATCH return  201 Created
the value(true) of key("enable_websocket") is modified  to false

**Comment by tzssangglass** [comment]
what's your APISIX version? pls provide env info?

**Comment by HaoTien** [comment]
> what's your APISIX version? pls provide env info

I have provided env info.
