### ISSUE TITLE
docs: https://apisix.apache.org/docs/apisix/plugins/hmac-auth/#generate-signature-examples

### ISSUE THREAD

**Issue by Jon-Gaara** [apache/apisix#5431]
### Improved or typo fixed.

我用  签名生成示例中的示例入参，然后采用HMAC SHA256算出来base64编码后的是hXBSc9GNjMz8CuhR/+IcrgVl058er1D7/VYtzBQg9Q8=
与实例出参不符合
![1636111928(1)](https://user-images.githubusercontent.com/7116647/140504271-c0af2e36-5ba9-447c-bb42-b15c4fe786fc.png)
![1636111817(1)](https://user-images.githubusercontent.com/7116647/140504072-9cf1aa72-dced-4c35-ae36-04e7b5ecbffd.png)

### Solution

应该将secret 从this is secret key  改为 the shared secret key here

**Comment by tzssangglass** [comment]
yes, you are right. would like to submit a PR ti fix this?

**Comment by Jon-Gaara** [comment]
Yes, please.
