### ISSUE TITLE
how to change prometheus plugins listen ip to 0.0.0.0

### ISSUE THREAD

**Issue by eno16777736** [apache/apisix#5437]
### Issue description

my config.yaml like this:
...
plugin_attr:
  prometheus:
    export_addr:
      ip: 0.0.0.0 
      port: 9091
....
bug it still 127.0.0.1:9091 
![image](https://user-images.githubusercontent.com/37285753/140602795-0076e641-912f-4955-b8c2-087646d27396.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`): alpine
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 6.2
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@eno16777736 Make sure the configuration indent is correct, I think configure the IP to `0.0.0.0` is no problem.

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
