### ISSUE TITLE
request help: hmac-auth plguin missing H-MAC-ALGORITHM response 

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5464]
### Issue description

hmac-auth plguin missing H-MAC-ALGORITHM response  is error

I think when missing H-MAC-ALOGRITHM can response other message

![image](https://user-images.githubusercontent.com/3895272/140899678-0a2491aa-7151-45da-a1d3-9dc6e7694cf0.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
we should check the X-HMAC headers
