### ISSUE TITLE
request help: apisix whith 6000 interface ,repsonse is slow

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5468]
### Issue description

log like this:
`[
    {
        "requestSize": 267,
        "currentTime": "1636514297.346",
        "route_id": "380815765558788857",
        "status": "200",
        "upstreamStatus": "200",
        "upstreamResponseTime": 0.47,
        "clientIp": "100.127.197.70",
        "responseSize": 772,
        "host": "47.96.254.82",
        "requestTime": 1.488,
        "uri": "/getTest",
        "upstreamResponseLength": "480",
        "method": "GET",
        "schema": "http"
    }
]`

requestTime=1.488s ,upstreamResponseTime=0.47s

most route config like this.

![image](https://user-images.githubusercontent.com/3895272/141045495-e3d07256-bb88-46bc-b869-ec230ef25f27.png)

config detail like this.
![image](https://user-images.githubusercontent.com/3895272/141045529-a2bb9c9f-a14b-4b55-a818-938e780c115f.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
What is the apisix of 6000 interface? Can't understand the relationship between title and picture information. Can you describe it in detail? In addition, can this problem be reproduced?

**Comment by juzhiyuan** [comment]
> What is the apisix of 6000 interface?

From the screenshot and this PR's description, I think it mean there have 6000 Routes.

**Comment by shuaijinchao** [comment]
> > What is the apisix of 6000 interface?
> 
> From the screenshot and this PR's description, I think this PR means there have 6000 Routes.

APISIX routes are stored based on a tree structure. In theory, the number of routes will not affect the response time.

**Comment by qq54903099** [comment]
> What is the apisix of 6000 interface? Can't understand the relationship between title and picture information. Can you describe it in detail? In addition, can this problem be reproduced?

6000+ routes

**Comment by shuaijinchao** [comment]
> > What is the apisix of 6000 interface? Can't understand the relationship between title and picture information. Can you describe it in detail? In addition, can this problem be reproduced?
> 
> 6000+ routes

Is this problem 100% reproducible? Are all routes affected?

**Comment by tzssangglass** [comment]
If there is only one route, is the response normal?

**Comment by qq54903099** [comment]
let me try .
I will try other route

**Comment by juzhiyuan** [comment]
@qq54903099 Hi, may I know if you issue gets resolved?

**Comment by qq54903099** [comment]
> @qq54903099 Hi, may I know if your issue gets resolved?

我觉得应该是上游接口问题。换成其他接口，是ok的。

**Comment by juzhiyuan** [comment]
ok
