### ISSUE TITLE
docs: apisix/docs/en/latest/how-to-build.md

### ISSUE THREAD

**Issue by carsonzhan** [apache/apisix#5472]
### Improved or typo fixed.

The installation tutorial is too complex and not very friendly to newcomers.
improve：I hope to add a novice video to introduce the installation and deployment process of Apache APISIX.

### Solution

I hope to add a novice video to introduce the installation and deployment process of Apache APISIX.

**Comment by spacewander** [comment]
The how-to-build doc needs to be optimized. Actually, if you install APISIX via docker, it is just one line: `docker pull apache/apisix` plus installing etcd. Most of the content is building APISIX from the source, which is only helpful for the developer.

CC @juzhiyuan

**Comment by juzhiyuan** [comment]
@carsonzhan Hi, may I know if you install Apache APISIX successfully now? If yes, could you please list all the contents you hesitate? then we could try to improve them. If no, you could reply which step you're pending, then let us help you.

**Comment by lishaoshu1240** [comment]
yep， i alse found the  tutorial  is not  friendly for newcomer. 

i have understand the Route function. but i dont kown the difference between  the "Route" and "Upstream".  My understanding was that “Route” function  include "Upstream", beacuse when we config our route by "http://xx:9080/apisix/admin/routes/2", the body have the upstream informations.

In the installion tutorial it alse have the "Upstream" tab, the tutorial dont tell us how to
associate them  if you split the two function.

tutorial directroy, as follow:
Description
Route
Service
Consumer
Upstream
SSL
Global Rule
Plugin Config
Plugin Metadata
Plugin
Stream Route

**Comment by tzssangglass** [comment]
this is another issue, pls open new issue or dicsussion to talk about it.BTW, route and upstream related by `upstream_id` on route config.

**Comment by tokers** [comment]
> i have understand the Route function. but i dont kown the difference between the "Route" and "Upstream". My understanding was that “Route” function include "Upstream", beacuse when we config our route by "http://xx:9080/apisix/admin/routes/2", the body have the upstream informations.

Maybe the tutorial should have some hyperlinks for these core concepts.

**Comment by kwanhur** [comment]
Tutorial videos had been posted, like email [Getting started with Apache APISIX @YouTube](https://www.mail-archive.com/dev@apisix.apache.org/msg04513.html).

**Comment by juzhiyuan** [comment]
> Tutorial videos had been posted, like email [Getting started with Apache APISIX @YouTube](https://www.mail-archive.com/dev@apisix.apache.org/msg04513.html).

cc @Boburmirzo @navendu-pottekkat @avinal @hf400159
