### ISSUE TITLE
request help: Is there a tutorial on how to develop apisix plug-in multilanguage support？

### ISSUE THREAD

**Issue by zhaozhenghai** [apache/apisix#5473]
### Issue description

Can I develop apisix plug-ins in  some other interpreted language  ？Where can I find related instruction or tutorials，and Whether there are relevant guide to introduce its principle so that I can use other interpreted language to develop plug-ins ? 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
I found this: https://apisix.apache.org/zh/blog/2021/06/21/use-Java-to-write-Apache-APISIX-plugins/

**Comment by zhaozhenghai** [comment]
> I found this: https://apisix.apache.org/zh/blog/2021/06/21/use-Java-to-write-Apache-APISIX-plugins/

Thank you so much for sharing, it is very useful for me。

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
