### ISSUE TITLE
request help: Support forward-auth

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#5475]
### Issue description

We are using traefik and want to migrate to apisix, but traefik has a forward-auth plugin, which is a plugin that supports external authentication services, how does apisix support external authentication services?
![image](https://user-images.githubusercontent.com/92301646/141090382-3a42b0c0-99a6-40e3-8bf4-50c008c0a93b.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Can you provide more details about the forward-auth plugin and how do you use it?

**Comment by tzssangglass** [comment]
This auth model looks like `openid-connect` or `ladp-auth`,

`openid-connect`: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/openid-connect.md

`ladp-auth`: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/ldap-auth.md

**Comment by GhangZh** [comment]
That is, I want to use our own authentication service. In apisix, I want to set the domain name of the service through the annotation: "ingress.kubernetes.io/auth-url":http://xxxxxx, and hand it over to this service to get the authentication result. After the verification, it will continue, but it will not pass. Just stop
