### ISSUE TITLE
docker install  api-gateway faild.

### ISSUE THREAD

**Issue by lishaoshu1240** [apache/apisix#5484]
### Issue description

hi, 
     I install api-ageway through the installation handbook(link: https://apisix.apache.org/zh/docs/docker/manual)。
but i met some error, when i install  by the command:

[root@localhost data]# docker run --name test-api-gateway \
>  -v `pwd`/example/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml \
>  -v `pwd`/example/apisix_log:/usr/local/apisix/logs  \
>  -p 9080:9080 \
>  -p 9091:9091  \
>  -p 9443:9443 \
>  --network apisix \
>  --ip 172.18.5.11 \
>  -d apache/apisix

**here is error:**

/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely".
[root@localhost data]#

### Environment

[root@localhost data]# uname -a
Linux localhost.localdomain 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

docker run --name test-api-gateway \
>  -v `pwd`/example/apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml \
>  -v `pwd`/example/apisix_log:/usr/local/apisix/logs  \
>  -p 9080:9080 \
>  -p 9091:9091  \
>  -p 9443:9443 \
>  --network apisix \
>  --ip 172.18.5.11 \
>  -d apache/apisix

### Actual result

a95b5fde7e41ea0e18319c6ebbb2f43fa6134bce28a8720c4f4b082007b7be38
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely".
[root@localhost data]#

### Error log

a95b5fde7e41ea0e18319c6ebbb2f43fa6134bce28a8720c4f4b082007b7be38
/usr/bin/docker-current: Error response from daemon: oci runtime error: container_linux.go:235: starting container process caused "container init exited prematurely".
[root@localhost data]#

**Comment by tokers** [comment]
The error was mostly caused by the mount file or directory doesn't exist, make sure the `pwd/example/apisix_conf/config.yaml` and `pwd/example/apisix_log` existing.

**Comment by lishaoshu1240** [comment]
@tokers  I have checke the directory exist.
