### ISSUE TITLE
docs: APISIX supports multi-language architecture diagram

### ISSUE THREAD

**Issue by membphis** [apache/apisix#5502]
### Improved or typo fixed.

Not yet. Added to the documentation, such as chapters on multi-language and WASM.

### Solution

![image](https://user-images.githubusercontent.com/6814606/141671374-10e46b19-3831-4187-8ead-4eea5e72bac5.png)

**Comment by juzhiyuan** [comment]
@membphis Hi, could you describe this issue in detail? 😄

**Comment by membphis** [comment]
In our previous document, there is no architecture diagram for multi-language support. So I drew a picture to help you understand how APISIX supports multi-language, and to better understand how APISIX supports multi-language architecture.

### APISIX supports multiple languages in two ways: `RPC` and `WASM`

The `WASM` or WebAssembly way, is more modern. We look at the left part, APISIX can load and run WASM bytecode, so other languages only need to write the code according to the SDK, and then compile it into a WASM bytecode file and put it in the APISIX folder. APISIX has supported Golang SDK and Rust SDK, more language SDKs will be supported in the future. 

The RPC way, is a tradition way. We look at the right part, developers can choose the language according to their needs. After being started in an independent process, it exchanges data with APISIX through local RPC communication. Till this moment, APISIX has supported Java，Golang, Python and Node.js.

**Comment by juzhiyuan** [comment]
Much clearly!

**Comment by membphis** [comment]
I think we can put it into https://github.com/apache/apisix#features

Is there anybody want to do this?

**Comment by membphis** [comment]
Many thanks. Waiting for your PR
@bisakhmondal
