### ISSUE TITLE
response  very slow  when i start to test the Route function of APISIX

### ISSUE THREAD

**Issue by lishaoshu1240** [apache/apisix#5513]
### Issue description

I installed apisix by docker-compose in my Ali-cloud.  and i found the response is very slow(from 0.01-12s) when i test the route transe function.
![image](https://user-images.githubusercontent.com/10431594/141735133-0144931f-0d70-4813-9323-b03c3a43fad9.png)
![Uploading image.png…]()

### Environment

[root@izwz9j39cr29fz8ecg6ea4z ~]# docker exec -it docker-apisix_apisix_1  apisix version
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.10.0

[root@izwz9j39cr29fz8ecg6ea4z ~]# uname -a
Linux izwz9j39cr29fz8ecg6ea4z 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

[root@izwz9j39cr29fz8ecg6ea4z ~]# docker exec -it docker-apisix_apisix_1  openresty -v
nginx version: openresty/1.19.3.1

**Comment by lishaoshu1240** [comment]
ping  the domain web.zaitugongda.com  will got  47.107.229.161

![image](https://user-images.githubusercontent.com/10431594/141736167-b13a9ef5-f5c0-44c2-ab13-b934224c0fdc.png)

**Comment by tokers** [comment]
What's the route/upstreams details? And, it seems that `web.zaitugongda.com` is not on your infrastructure, you may also assess the networking impacts.

**Comment by lishaoshu1240** [comment]
{
  "methods": ["GET"],
  "host": "web.zaitugongda.com",
  "uri": "/ab*",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "47.107.229.161:9082": 1,
      "47.107.229.161:9081": 1
    }
  }
}

**Comment by tzssangglass** [comment]
what you marked is `$upstream_response_time`,  keeps time spent on receiving the response from the upstream server. 
I think you also need to check how long it takes for the upstream service to process the request. Another way to test this is that you can make the request not go through apisix, what is the latency?
