### ISSUE TITLE
error] 20920#20920: *692819 peer closed connection in SSL handshake while SSL handshaking to upstream,

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#5524]
### Issue description

在配置一个443反向代理的时候报这个错误
用HAPROXY，可以用check ssl verify none
这个来解决

### Environment

- apisix version (cmd: `apisix version`):/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
2.10.1

- OS (cmd: `uname -a`):Linux openresty-1 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.9.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 

- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

error] 20920#20920: *692819 peer closed connection in SSL handshake while SSL handshaking to upstream,

### Actual result

error] 20920#20920: *692819 peer closed connection in SSL handshake while SSL handshaking to upstream,

### Error log

error] 20920#20920: *692819 peer closed connection in SSL handshake while SSL handshaking to upstream,

**Comment by tokers** [comment]
Do you mean the downstream SSL or upstream SSL?

**Comment by lifeblood** [comment]
> upstream SSL

**Comment by lifeblood** [comment]
done

**Comment by tokers** [comment]
> done

Could you paste your solutions here :)
