### ISSUE TITLE
request help: The domain name in the matching condition, can add the main domain name wildcard

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#5527]
### Issue description

匹配条件 里的域名，可以加主域名wildcard吗
比如：

test.*

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by moonming** [comment]
@lifeblood 
Please use English in the public channel, thx

**Comment by shuaijinchao** [comment]
No, please refer to the `host` verification rules.

https://github.com/apache/apisix/blob/0ba89d5c0f9dc2863329a8fa6552c380453627cf/apisix/schema_def.lua#L40

**Comment by lifeblood** [comment]
> host_def_pat

what's setup?

**Comment by tzssangglass** [comment]
`test.*` can not work, `*.test` is ok. the anser above is clear.

**Comment by lifeblood** [comment]
done
