### ISSUE TITLE
bug: kafka-logger send thread crash

### ISSUE THREAD

**Issue by icecode** [apache/apisix#5528]
### Issue description

kafka-logger send thread crash

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): Linux developer-apisix 3.10.0-1160.36.2.el7.x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 2.9
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

run

### Actual result

No data sent Kafka

### Error log

![image](https://user-images.githubusercontent.com/1329634/141936767-3e71b61b-0ce9-410f-af13-de72dbccc036.png)

**Comment by shuaijinchao** [comment]
Please provide reproduction steps and related configuration.

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
