### ISSUE TITLE
request help: both apisix and dashboard would select the unhealth node in the etcd cluster to connect, wouldn't skip unhealth node

### ISSUE THREAD

**Issue by 18300618319** [apache/apisix#5532]
### Issue description

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

### Environment

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

### Steps to reproduce

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

### Actual result

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

### Error log

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

### Expected result

apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉
![Uploading c12528b84634374b9ebc6f0ed53086b.jpg…]()

**Comment by 18300618319** [comment]
![微信图片_20211116141724](https://user-images.githubusercontent.com/26192378/141951988-4a89bf8c-83e1-4a45-811a-7f91cfd73b87.jpg)

> 

>

**Comment by shuaijinchao** [comment]
The picture does not seem to be uploaded successfully. You can adjust the log level to `info` and filter the `healthcheck` to check whether the removal of unhealthy nodes is triggered.

**Comment by 18300618319** [comment]
已经在评论里上传图片了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 下午4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉 (Issue #5532)






图片好像没有上传成功，你可以把日志级别调整为信息并筛选出健康检查检查是否触发不健康节点的移除。

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by 18300618319** [comment]
测试过了，不会把不健康的节点自动去掉




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉 (Issue #5532)





 
The picture does not seem to be uploaded successfully. You can adjust the log level to info and filter the healthcheck to check whether the removal of unhealthy nodes is triggered.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 18300618319** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉 (Issue #5532)





 
The picture does not seem to be uploaded successfully. You can adjust the log level to info and filter the healthcheck to check whether the removal of unhealthy nodes is triggered.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by shuaijinchao** [comment]
> 测试过了，不会把不健康的节点自动去掉

Please provide snippets of APISIX related logs.

**Comment by 18300618319** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月16日(星期二) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉 (Issue #5532)





  
测试过了，不会把不健康的节点自动去掉
  
Please provide snippets of APISIX related logs.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tokers** [comment]
Please provide:

1. The version of your APISIX and Dashboard;
2. The Configuration of your APISIX (config.yaml);

**Comment by 18300618319** [comment]
apisix 2.10.0
dashboard 2.9.0




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年11月16日(星期二) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] apisix和dashboard都有这个问题，etcd集群一个节点挂掉还是会一直请求这个坏的节点，不会健康检查把坏的节点去掉 (Issue #5532)






请提供：

您的 API SIX 和仪表板的版本；

配置您的 API SIX （ config . yaml ）；

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.
