### ISSUE TITLE
systemctl enable apisix is not avialiable

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#5533]
### Issue description

systemctl enable apisix is not avialiable

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

systemctl enable apisix is not avialiable

### Actual result

systemctl enable apisix is not avialiable

### Error log

systemctl enable apisix is not avialiable

**Comment by tzssangglass** [comment]
show the  installation steps

**Comment by lifeblood** [comment]
sudo yum install -y https://github.com/apache/apisix/releases/download/2.10.1/apisix-2.10.1-0.el7.x86_64.rpm

**Comment by lifeblood** [comment]
● apisix.service - apisix
   Loaded: loaded (/usr/lib/systemd/system/apisix.service; static; vendor preset: disabled)
   Active: active (running) since 二 2021-11-16 14:53:00 CST; 6h ago
 Main PID: 25250 (openresty)
   CGroup: /system.slice/apisix.service
           ├─25250 nginx: master process openresty -p /usr/local/apisix -c /usr/local/apisix/conf/nginx.conf
           ├─25251 nginx: worker process
           ├─25252 nginx: worker process
           ├─25253 nginx: worker process
           ├─25254 nginx: worker process
           ├─25255 nginx: worker process
           ├─25256 nginx: worker process
           ├─25257 nginx: worker process
           ├─25258 nginx: worker process
           ├─25259 nginx: cache manager process
           └─25261 nginx: privileged agent process

11月 16 16:37:26 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:38:57 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:38:57 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:38:57 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:44:02 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:44:02 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:44:02 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:45:25 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:45:25 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service
11月 16 16:45:25 openresty-1 systemd[1]: Dependency Conflicts=apisix.service dropped from unit apisix.service

**Comment by tzssangglass** [comment]
have you written `apisix.service` or `openresty.service` yourself? Or do you install openresty before?

in fact, this rpm would prvode  `apisix.service` and `openresty.service`, see: https://github.com/api7/apisix-build-tools/tree/master/usr/lib/systemd/system

**Comment by lifeblood** [comment]
systemctl list-unit-files
apisix.service                                  static
can not change enabled

**Comment by tzssangglass** [comment]
see:https://github.com/api7/apisix-build-tools/blob/fdde4aea67c565f8bbcbbc627a6690766caf377d/usr/lib/systemd/system/apisix.service#L3

```
Conflicts=apisix.service
```

maybe your apisix.service is running?

**Comment by lifeblood** [comment]
[root@openresty-2 ~]# cat /usr/lib/systemd/system/apisix.service
[Unit]
Description=apisix
Conflicts=apisix.service
After=network-online.target

[Service]
Type=forking
WorkingDirectory=/usr/local/apisix
ExecStart=/usr/bin/apisix start
ExecStop=/usr/bin/apisix stop
ExecReload=/usr/bin/apisix reload

**Comment by tzssangglass** [comment]
> [root@openresty-2 ~]# cat /usr/lib/systemd/system/apisix.service [Unit] Description=apisix Conflicts=apisix.service After=network-online.target
> 
> [Service] Type=forking WorkingDirectory=/usr/local/apisix ExecStart=/usr/bin/apisix start ExecStop=/usr/bin/apisix stop ExecReload=/usr/bin/apisix reload

I mean apisix is running?

**Comment by lifeblood** [comment]
> > [root@openresty-2 ~]# cat /usr/lib/systemd/system/apisix.service [Unit] Description=apisix Conflicts=apisix.service After=network-online.target
> > [Service] Type=forking WorkingDirectory=/usr/local/apisix ExecStart=/usr/bin/apisix start ExecStop=/usr/bin/apisix stop ExecReload=/usr/bin/apisix reload
> 
> I mean apisix is running?

running

**Comment by tzssangglass** [comment]
I think you need to close apisix and then systenctl enable.

**Comment by lifeblood** [comment]
> I think you need to close apisix and then systenctl enable.

tried, not available

**Comment by tzssangglass** [comment]
I don't have a centos7 environment right now to reproduce your problem 😓

**Comment by tokers** [comment]
@lifeblood Please use `journalctl` to check out the logs.

**Comment by dyrnq** [comment]
@lifeblood It does not appear to cause a startup failure，just go to run `systemctl start apisix` start apisix or `systemctl stop apisix`  stop apisix

**Comment by kwanhur** [comment]
I'm sure `systemctl enable apisix` works well on Centos7 with `apisix-2.12.0-0.el7.x86_64`.

**Comment by kwanhur** [comment]
> @lifeblood It does not appear to cause a startup failure，just go to run `systemctl start apisix` start apisix or `systemctl stop apisix` stop apisix

Automatically startup apisix when host is arise on restarting, it's a recovery policy.
