### ISSUE TITLE
request help: How to get custom Java plugins to run before HMAC certified plugins?

### ISSUE THREAD

**Issue by iSuperCoder** [apache/apisix#5534]
### Issue description

在ext-plugin-pre-req中配置了一个java插件，实际执行时发现先于hmac-auth插件运行。如何让ext-plugin-pre-req中的插件首先执行？

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.0
- apisix-dashboard version, if have: 2.9.0
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): 0.1.0
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
Please use English in the public channel, thx.

the order of plugins exec is defined by priority in plugin's code, see: https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin-pre-req.lua#L24 and https://github.com/apache/apisix/blob/2c12b3695302f580a1498333aaafb68da26a3096/conf/config-default.yaml#L302-L358

the higher the priority number, the earlier the order of execution.



> 实际执行时发现先于hmac-auth插件运行。如何让ext-plugin-pre-req中的插件首先执行？

contradictory？

**Comment by tzssangglass** [comment]
AFAIK, `ext-plugin-pre-req` is run before `hmac-auth`.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
