### ISSUE TITLE
Route and Upstream's concepts are mixed and not clear

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#5535]
yep， i alse found the  tutorial  is not  friendly for newcomer. 

i have understand the Route function. but i dont kown the difference between  the "Route" and "Upstream".  My understanding was that “Route” function  include "Upstream", beacuse when we config our route by "http://xx:9080/apisix/admin/routes/2", the body have the upstream informations.

In the installion tutorial it alse have the "Upstream" tab, the tutorial dont tell us how to
associate them  if you split the two function.

tutorial directroy, as follow:
Description
Route
Service
Consumer
Upstream
SSL
Global Rule
Plugin Config
Plugin Metadata
Plugin
Stream Route

_Originally posted by @lishaoshu1240 in https://github.com/apache/apisix/issues/5472#issuecomment-969828265_

**Comment by juzhiyuan** [comment]
Hi @lishaoshu1240, thanks for your comment about Apache APISIX's docs. Yes, some concepts are mixed together and will confuse not only you but also me in the beginning.

First, let me explain this issue to you. Upstream and Route are two different entities in Apache APISIX, and the Route entity has 2 properties called `upstream` and `upstream_id`:
- `Route.upstream`: You could pass a complete Upstream Entity's data to it;
- `Route.upstream_id`: You could first create an Upstream Entity, and then use `Route.upstream_id` to **reference** it, so you don't need to create duplicated `Route.upstream` over and over again.

Second, for now, Apache APISIX's documentation is not good and friendly as other products indeed, it mainly meets this case now: How to use Apache APISIX and What APIs it has? I and you and other users would focus on if it could be better for a long time, but I would like to know how to implement this destination? In my own opinion, it needs all of us including contributors and users to give feedbacks on how to improve those documentations like you, like this Issue does :) 

Third, welcome all kinds of contributions to Apache APISIX's codes, docs, and communities, etc.

**Comment by lishaoshu1240** [comment]
👍
