### ISSUE TITLE
request help:  Found "Lua code block missing the closing long bracket" when running ci test

### ISSUE THREAD

**Issue by nanamikon** [apache/apisix#5541]
### Issue description

Hi
     I try to run ci test in my own ubuntu image,   I found this message as follow
``` 
t/plugin/traffic-split2.t .. nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
nginx: [emerg] Lua code block missing the closing long bracket "]=]" in /data/app/huya-proxy-nginx-ci/t/servroot/conf/nginx.conf:193
```

And I found it relate to this issue https://github.com/openresty/lua-nginx-module/issues/1622
Should I modify this test file ?  But this test case pass in my mac.  
Is there any tips for me to fix it , thanks

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):ubuntu 16
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.5

**Comment by spacewander** [comment]
The behavior depends on the OpenResty version and the platform.
You can rewrite the test with Lua table instead of long literal string.
