### ISSUE TITLE
bug: cannot install Apache APISIX by RPM

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#5549]
### Issue description

Hi, I try to install Apache APISIX according to https://apisix.apache.org/docs/apisix/how-to-build#installation-via-rpm-repositorycentos-7. When I run `sudo yum install apisix`, error occurred.

![image](https://user-images.githubusercontent.com/2106987/142417695-9e13c128-3c9a-4e37-bd13-2edd096a0947.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10.1
- OS (cmd: `uname -a`): CentOS
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): None
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): None
- apisix-dashboard version, if have: None
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): None
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): None

### Steps to reproduce

1. Visit https://apisix.apache.org/docs/apisix/how-to-build#installation-via-rpm-repositorycentos-7
2. Run `sudo yum install apisix`
3. Error occurred

### Actual result

See picture above please

### Error log

```
已加载插件：fastestmirror, langpacks
Loading mirror speeds from cached hostfile
正在解决依赖关系
--> 正在检查事务
---> 软件包 apisix.x86_64.0.2.10.1-0.el7 将被 安装
--> 解决依赖关系完成

依赖关系解决

======================================================================================================================================================
 Package                           架构                              版本                                    源                                  大小
======================================================================================================================================================
正在安装:
 apisix                            x86_64                            2.10.1-0.el7                            release                            1.9 M

事务概要
======================================================================================================================================================
安装  1 软件包

总下载量：1.9 M
安装大小：8.3 M
Is this ok [y/d/N]: y
Downloading packages:
apisix-2.10.1-0.el7.x86_64.rpm FAILED                                          ===================================  ] 1.7 MB/s | 1.8 MB  00:00:00 ETA
https://repos.apiseven.com/packages/centos/7/x86_64/apisix-2.10.1-0.el7.x86_64.rpm: [Errno -1] 软件包与预期下载的不符。建议：运行 yum --enablerepo=release clean metadata
正在尝试其它镜像。


Error downloading packages:
  apisix-2.10.1-0.el7.x86_64: [Errno 256] No more mirrors to try.
```

**Comment by imjoey** [comment]
@juzhiyuan thanks for reporting. There's something wrong with the repo metadata. The problem has been fixed and please retry.

**Comment by juzhiyuan** [comment]
It works! How do we prevent from this happening again?
