### ISSUE TITLE
request help: support advanced matching based on POST JSON Body

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5551]
### Issue description

类似issue：https://github.com/apache/apisix/issues/5399
希望可以在路由高级参数匹配中支持下POST Body里面的参数匹配。目前我们是通过写serverless-pre来实现的，代码如下：
```
function(vars)
    local core = require ('apisix.core')
    local body, err = core.request.get_body()
    if not body then
        return false
    end
  
    local data, err = core.json.decode(body)
    if not data then
        return false
    end
  
    -- 当匹配 body 里面 foo 字段等于 bar 的时候，路由生效
    if data['foo'] == 'bar' then
        return true
    end
  
    return false
  end
```

希望可以直接支持下这个特性~~

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#how-to-filter-route-by-post-form-attributes.

**Comment by jagerzhang** [comment]
> See https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#how-to-filter-route-by-post-form-attributes.

上一个issue里面讨论了下，好像这个特性不支持 application/json 里面的内容匹配，看代码写的是Content-Type = application/x-www-form-urlencoded

**Comment by shuaijinchao** [comment]
In addition to `application/x-www-form-urlencoded` and `application/json`, the commonly used Content-Type of POST also includes `multipart/form-data` and user-defined data formats. It is not a standardized format, so it is not recommended to use Body as a matching hit condition.
