### ISSUE TITLE
docs:  dont found the usage of etcd in discovery.md 

### ISSUE THREAD

**Issue by lishaoshu1240** [apache/apisix#5573]
### Improved or typo fixed.

hi,  i want to use etcd for discovery tools, but i dont found  it in the discovery.md 

### Solution

plesase add etcd relevant description.

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/4713

**Comment by lishaoshu1240** [comment]
> see: #4713

@tzssangglass , thanks reply so quikly,  you misunderstand what i say.  

var LINKS = "https://github.com/apache/apisix/blob/master/docs/en/latest/discovery.md#supported-discovery-registries"

the LINKS have  the usage of Eureka/Consul/Nacos, but dont have the etcd usage.
i want use etcd discovery to get my upstream addr in the apisix.  you can understand  what i want to do if you see this configure:

{
  "methods": ["GET"],
  "uris": ["/api/order*","/api/calu*"],
  "plugins": {
	"jwt-auth": {}
  },
  "upstream": {
     "service_name": "order",
    "type": "roundrobin",
    "discovery_type": "etcd"
  }
}

I have micro-services register the  addr to my topic “order”

[root@localhost ~]# etcdctl get "order/" --prefix
order/192.168.0.73:9999
{"Name":"order","IP":"192.168.0.73:9999"}

**Comment by tzssangglass** [comment]
> the LINKS have the usage of Eureka/Consul/Nacos, but dont have the etcd usage.

yes, see: see: https://github.com/apache/apisix/issues/4442#issuecomment-863746666, you need to register `order` as upstream of APISIX, like:

```
/apisix/upstreams/order
……
```

**Comment by lishaoshu1240** [comment]
> > the LINKS have the usage of Eureka/Consul/Nacos, but dont have the etcd usage.
> 
> yes, see: [#4442 (comment)](https://github.com/apache/apisix/issues/4442#issuecomment-863746666), you need to register `order` as upstream of APISIX, like:
> 
> ```
> /apisix/upstreams/order
> ……
> ```

It's also faild if I use this method,  please help me check logs:

![image](https://user-images.githubusercontent.com/10431594/143027297-20a27a4f-f3df-43da-8016-bf8ec10b318c.png)
![image](https://user-images.githubusercontent.com/10431594/143027321-82fd3a6d-b639-4f61-9a83-3f45c2deacc6.png)
![image](https://user-images.githubusercontent.com/10431594/143027341-1a4d337c-92fb-452d-8e56-0a26024e240b.png)
![image](https://user-images.githubusercontent.com/10431594/143027359-6ece9a80-0d8b-48e2-9e07-7a5f960b1d85.png)

**Comment by tzssangglass** [comment]
use words rather than pictures.

1. we don't have discovery_type is etcd
2. take a look at:https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#upstream, you need to register `order` as an upstream, check the config of `order`.

**Comment by lishaoshu1240** [comment]
> use words rather than pictures.
> 
> 1. we don't have discovery_type is etcd
> 2. take a look at:https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#upstream, you need to register `order` as an upstream, check the config of `order`.

I register order as upstream of APISIX， here is my config:

http://192.168.0.73:9080/apisix/admin/upstreams/order
{
	"service_name": "order",
    "type": "roundrobin",
    "discovery_type": "etcd"
  }

ps:  the keywords "discovery_type",  how to fill if i want use etcd as discovery and registory

where i can get the  examples of etcd as discovery.
if i use Eureka as discovery, i can follow this link:https://github.com/apache/apisix/blob/master/docs/en/latest/discovery.md

**Comment by tzssangglass** [comment]
> the keywords "discovery_type", how to fill if i want use etcd as discovery and registory

no need to set `discovery_type ` if you register order as upstream of APISIX.

**Comment by lishaoshu1240** [comment]
> > the keywords "discovery_type", how to fill if i want use etcd as discovery and registory
> 
> no need to set `discovery_type ` if you register order as upstream of APISIX.

can you help me write the configure?

if i do not set the discovery_type, it faild :
![image](https://user-images.githubusercontent.com/10431594/143189137-79cec408-8db8-4ecc-a1f8-5ebdc2cc6c97.png)

**Comment by tzssangglass** [comment]
read: https://github.com/apache/apisix/blob/master/docs/zh/latest/admin-api.md#body-%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0-3 first

**Comment by lishaoshu1240** [comment]
> read: https://github.com/apache/apisix/blob/master/docs/zh/latest/admin-api.md#body-%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0-3 first

hi，兄弟，这个文档我看了好多遍了，我完全理解admin-api.md 中upstream的意思。但是现在我光看这个文档还是不能明白内置的etcd 怎么用的。

我的order微服务已经注册到apisix 配套的的etcd里面了，现在就是想通过openresty 去服务发现这个order微服务。
所以我现在通过下面步骤来实现：
step1、通过http://192.168.0.73:9080/apisix/admin/upstreams/order 新增一个upstream。
{
"service_name": "order",
"type": "roundrobin",
"discovery_type": "etcd"
}
**现在问题点就在这，我不知道这个新增的upstream怎么写，你上文说不需要discovery_type，如果不需要的话，那么这个body参数怎么写？（只留下service_name 和type,去提交的话，会报错）。**

step2、通过http://192.168.0.73:9080/apisix/admin/routes/1 来添加上面的upstream。这一步没问题。
{
  "methods": ["GET"],
  "uris": ["/api/order*","/api/calu*"],
  "plugins": {
	"jwt-auth": {}
  },
  "upstream_id":"order"
}


通过上面两个步骤后，我的理解就是当有order微服务接口过来的时候，apsix能够正常转发到我的order后端地址。但是现在明显卡在第一步。

**Comment by juzhiyuan** [comment]
Hi @bzp2010, could you please take a look? 😄

**Comment by juzhiyuan** [comment]
Just have a discussion with @bzp2010, we don't support ETCD as Service Discovery yet 🤔 @leslie-tsang could you please have a confirmation? 😄

**Comment by leslie-tsang** [comment]
> Just have a discussion with @bzp2010, we don't support ETCD as Service Discovery yet 🤔 @leslie-tsang could you please have a confirmation? 😄

AFAIK, APISIX don't support `etcd` as `Service Discovery` yet.  🤔

**Comment by spacewander** [comment]
We support etcd as the source of discovery in a different way.
