### ISSUE TITLE
request help:  consumer 怎么能绑定 upstream

### ISSUE THREAD

**Issue by giwms** [apache/apisix#5574]
### Issue description

通过header的某个入参，访问不同的上游服务，但是consumer 不支持绑定upstream

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Use http://apisix.apache.org/docs/apisix/plugins/traffic-split instead.
