### ISSUE TITLE
request help: how to implement rollbacks of operations noticed in ops friendly

### ISSUE THREAD

**Issue by wangxiaochuang** [apache/apisix#5576]
### Issue description

I want to know how to rollback my wrong operations

### Environment

- apisix version: 2.10.1
- OS: centos7
- OpenResty / Nginx version: openresty/1.19.9.1
- etcd version: v3.5
- apisix-dashboard version, if have: 2.9.0
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
Do you mean your operations on the APISIX Dashboard?

**Comment by wangxiaochuang** [comment]
dashboard and apisix's admin api
