### ISSUE TITLE
request help: a forward plugin for api gw

### ISSUE THREAD

**Issue by endison1986** [apache/apisix#5579]
### Issue description

I write a plugin to forward request to other real route by an unitive url.

I write `ngx.req.set_uri("/...", true);` in _M.write function, but get error message `API disabled in the context of access_by_lua*`. It means I cannot set `jump?` to `true` in access phase, but I also cannot do this in _M.set, because  _M.set is blocked, I must do http request before rewrite uri.

```lua
function _M.rewrite(conf, ctx)
// rpc by http
ngx.req.set_uri("/...", true);
end
```

how can I do in this case.

### Environment

- apisix version (cmd: `apisix version`): 2.8

- OS (cmd: `uname -a`): `Linux apisix-server-7bf4dd654f-729fq 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.2

- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): {"id":"aac46492-9c9b-4dea-97c8-db491937d5ef","boot_time":1636444986,"etcd_version":"3.4.0","up_time":1203196,"last_report_time":1637648165,"version":"2.8","hostname":"apisix-server-7bf4dd654f-729fq"}

- apisix-dashboard version, if have:

- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):

- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
Perhaps you can refer to the implementation of the `proxy-rewrite` plugin. The request context of apisix is private. If you need to rewrite the forwarded URI in the execute phase, you can use `ctx.var.upstream_uri = xxxx`

**Comment by tokers** [comment]
@endison1986 As per the API description:

> The jump argument can only be set to true in rewrite_by_lua.

And the rewrite hook actually run on access phase.

**Comment by endison1986** [comment]
> Perhaps you can refer to the implementation of the `proxy-rewrite` plugin. The request context of apisix is private. If you need to rewrite the forwarded URI in the execute phase, you can use `ctx.var.upstream_uri = xxxx`

thx reply, I also notice `proxy-rewrite` plugin，and try to set up and apply it.
I create a route and set upstream `127.0.0.1:8080` that is not real, and set up `proxy-rewrite`, but I get an error message, `connect() failed (111: Connection refused) while connecting to upstream`
Maybe, I don't understand where should the plugin be used, I will try it again, 3q.

**Comment by endison1986** [comment]
> @endison1986 As per the API description:
> 
> > The jump argument can only be set to true in rewrite_by_lua.
> 
> And the rewrite hook actually run on access phase.

My understanding from openresty document is `ngx.req.set_uri(uri, jump?)` is rewrite uri, and jump only can set true in rewrite phase, but I always thought that `_M.rewrite` is in rewrite phase, until the developers of openresty told me that's not the case.
https://github.com/openresty/openresty/issues/787
