### ISSUE TITLE
request help: How to record interface(restful api) request log and return log？

### ISSUE THREAD

**Issue by 90yangkang** [apache/apisix#5585]
### Issue description

For example, when a request arrives at apifix, you can record the time of the request, URL parameters, body parameters, return time and return data of the request.

### Environment

- apisix version: 2.10
- OS : docker OS
- OpenResty / Nginx version:1.19.0-alpine
- etcd version, if have : 3.4.15
- apisix-dashboard version:2.9.0

**Comment by tokers** [comment]
@bzp2010 PTAL, thanks!

**Comment by tzssangglass** [comment]
`kafka-logger` can do this?

**Comment by 90yangkang** [comment]
> `kafka-logger` can do this

No Kafuka server   @tzssangglass

**Comment by tzssangglass** [comment]
you can use some other logger plugin, such as `http-looger`, `tcp-logger` or write plugin to do this. APISIX can record what you have said and you will need to make your own choices depending on the situation.

**Comment by 90yangkang** [comment]
> you can use some other logger plugin, such as `http-looger`, `tcp-logger` or write plugin to do this. APISIX can record what you have said and you will need to make your own choices depending on the situation.

http-logger and tcp-logger record the request info, don't record the return info.

**Comment by tzssangglass** [comment]
some existing PRs are refining these features, e.g. https://github.com/apache/apisix/pull/5550

http-logger and tcp-logger support record response can refer to this, if you are interested, PR is welcome!

**Comment by 90yangkang** [comment]
> some existing PRs are refining these features, e.g. #5550
> 
> http-logger and tcp-logger support record response can refer to this, if you are interested, PR is welcome!

![微信截图_20211124192659](https://user-images.githubusercontent.com/35477514/143229988-9bbc04b7-2a09-4e3e-9b05-b80e697e4f7d.png)


![微信截图_20211124152248](https://user-images.githubusercontent.com/35477514/143230017-337ca3ec-deb1-4253-b159-e3ed8926fe93.png)


use http-logger, Failed to get log_ format。

**Comment by tzssangglass** [comment]
not relevant to this issue, see: https://github.com/apache/apisix/issues/4098#issuecomment-977762062

**Comment by 90yangkang** [comment]
> not relevant to this issue, see: [#4098 (comment)](https://github.com/apache/apisix/issues/4098#issuecomment-977762062)

Ok，thanks~
