### ISSUE TITLE
request help: lua-resty-healthcheck support configuration of a minimum number of reserved nodes？

### ISSUE THREAD

**Issue by yyangh1** [apache/apisix#5587]
### Issue description

lua-resty-healthcheck的主动检查如果不能配置最少保留节点数，在出现检查地址出错或者检查接口不通等原因的时候，会把所有节点全部下线，出现灾难性的问题

### Environment

- apisix version (cmd: `apisix version`):2.8
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.9
- apisix-dashboard version, if have:2.7
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
BTW, the current health check can't bring all the nodes down. See https://github.com/apache/apisix/blob/59497deb8f3d7df2a9bd877d367f62108aea078f/apisix/balancer.lua#L86

**Comment by spacewander** [comment]
When there is something wrong with the health check, the original nodes will serve as used.
