### ISSUE TITLE
request help: cannot configure ssl_ceipher for a single domain

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#5590]
### Issue description

Now I need to enter a separate ceipher configuration for a second-level domain name, and then,Cannot configure ssl_ceipher for a single domain name,please help me!tks!
@tzssangglass 

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):centos 7.3
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
This relies on the underlying Nginx and OpenResty to provide such APIs, we may need more detailed design.
