### ISSUE TITLE
request help: delete etcd key after starting apisix, then error: no healthy etcd endpoint available

### ISSUE THREAD

**Issue by ImCHT** [apache/apisix#5597]
### Issue description

Apisix doesn't cache  etcd private key in memory? After I delete etcd key file after starting apisix, it can not connect to the etcd. For security reasons, I need to delete the etcd private key file.
This is my apisix config about etcd:
![image](https://user-images.githubusercontent.com/18203548/143161125-a6760dc9-be47-4a7a-9ee4-52e17a3637bb.png)
This is the apisix error log:
![image](https://user-images.githubusercontent.com/18203548/143161182-c780607f-b823-4b1c-9978-64e71d82629b.png)

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):eulerosv2r9.x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- 
![image](https://user-images.githubusercontent.com/18203548/143161432-c357d63b-283a-4ae2-83e0-8a45fffefc6f.png)
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- 
![image](https://user-images.githubusercontent.com/18203548/143161488-b55f3bb2-d9a2-4b24-882f-d0e82a90e7b4.png)

- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
if you don't delete etcd key file, would it work well?

AFAIK, we can not delete etcd key file. in extreme cases, worker would exit abnormally after APISIX is running, and then fork a new worker process, which will fail if etcd key file does not exist. data in memory is not permanent.

**Comment by ImCHT** [comment]
Yes, it works well. And after I regenerate the etcd key file, apisix can resume the communication with etcd.
![image-20211122105536589](https://user-images.githubusercontent.com/18203548/143241330-baebe14e-e100-406b-a48f-79056cb856ea.png)
Ok, I know. I may use  one-way authentication and iptables to implement two-way authentication.

**Comment by ImCHT** [comment]
Yes, it works well. And after I regenerate the etcd key file, apisix can resume the communication with etcd.
image-20211122105536589
Ok, I know. I may use one-way authentication and iptables to implement two-way authentication.
Thanks!
