### ISSUE TITLE
request help: proxy_mirror enable then apisix given error log

### ISSUE THREAD

**Issue by dongqisilent** [apache/apisix#5599]
### Issue description

when enable proxy_mirror  plugin， wo got many this exception. the error means upstream is available?

_CONTENT__:2021/11/23 16:32:50 [error] 1433#1433: *1205604631 upstream timed out (110: Connection timed out) while sending to client, client: xxx.xxx.xxx.xxx, server: _, request: "GET /api/xxxx?limit=20&offset=0 HTTP/1.1", subrequest: "/proxy_mirror", upstream: "http://xxx.xxx.xxx.xxx:8080/api/youzan/shop/list?limit=20&offset=0", host: "xxx.xxx.xxx.xxx", referrer: "https://xxx.xxx.xxx.xxx/customer_info"

### Environment

- apisix version (cmd: `apisix version`): 2.8
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
> the error means upstream is available

no, the error means upstream is unavailable

**Comment by tzssangglass** [comment]
you need to check the network problems first.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
