### ISSUE TITLE
bug: The latency of request is not stable as expected

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5604]
### Issue description

最近我们开始将生产环境的业务迁移到APISIX，迁移后有业务反馈延迟增大，实测了下，延迟确实存在无规律抖动现象，在我们的生产环境中，接入APISIX的业务正常延时是16ms左右，但是抖动的时候延迟会超过200ms，最高到了800ms，之前和zuul网关对比测试的一个截图：
![wecom-temp-cab7877337fa434e1ca1912ef7fea83f](https://user-images.githubusercontent.com/9711651/143397872-f6ef008a-f06c-4e2e-ba36-01f612008ff1.png)

这个问题对于延迟比较敏感的业务会受到影响。我不知道该如何定位。为了排除是我们生产环境网络或者APISIX配置的问题，我这边基于官方的example也测试了下，发现在本地网络环境下也存在抖动，正常应该是0ms，但是抖动的时候会达到10ms以上，不太符合APISIX 0.2ms延迟的预期。

具体测试用例和初步结果我已经上传到了github：https://github.com/jagerzhang/apisix-latency-test

辛苦APISIX研发专家帮忙看看这个是APISIX本身的问题还是其他什么因素影响的？ 

### Environment

- apisix version (cmd: `apisix version`): centos-2.10.2

### Steps to reproduce

复现用例和测试预览已整理上传，详见：https://github.com/jagerzhang/apisix-latency-test

**Comment by shuaijinchao** [comment]
Have you tried to observe and analyze by capturing packets?

**Comment by jagerzhang** [comment]
> Have you tried to observe and analyze by capturing packets?

@shuaijinchao 刚抓包分析了下，找到其中耗时14ms的请求看了下详情，APISIX到Nginx之间耗时之后0.04ms，APISIX却耗时14ms：
![image](https://user-images.githubusercontent.com/9711651/143397270-e5b81dcb-eb91-4652-bc59-9ce1ee5da26b.png)

完整抓包文件：
[start_test.cap.zip](https://github.com/apache/apisix/files/7600967/start_test.cap.zip)

**Comment by shuaijinchao** [comment]
![image](https://user-images.githubusercontent.com/8529452/143408346-66a66278-0265-446f-b1ff-809de3566b68.png)
![image](https://user-images.githubusercontent.com/8529452/143408849-f132fec1-4cf6-4111-89cc-ec250bc2a38b.png)

From the data packet analysis, the time is indeed consumed on APISIX, we will try to reproduce it later. cc @tzssangglass

**Comment by sandy420** [comment]
> APISIX

@jagerzhang @tzssangglass   me too,I mentioned issue before

**Comment by jagerzhang** [comment]
> > APISIX
> 
> @jagerzhang @tzssangglass me too,I mentioned issue before #5500

Well, let's focus together

**Comment by jagerzhang** [comment]
it's Solved when the prometheus plugin was disabled.

**Comment by xianshun163** [comment]
@jagerzhang Have you solved this problem? I found that the official code has been merged, about the prometheus  plugin deps

**Comment by jagerzhang** [comment]
> @jagerzhang Have you solved this problem? I found that the official code has been merged, about the prometheus plugin deps

yes, solved, need to wait the next release：https://github.com/apache/apisix/pull/6315

**Comment by jagerzhang** [comment]
@spacewander this case already exist in LTS 2.13.0 
![image](https://user-images.githubusercontent.com/9711651/163148221-368188f4-5c49-49eb-b899-1527666fb313.png)
