### ISSUE TITLE
bug: error when using the zipkin plugin

### ISSUE THREAD

**Issue by zqm233** [apache/apisix#5609]
### Issue description

When i using the zipkin plugin, there are some error logs

UPDATE:
I test the zipkin plugin in my mac. Result as follow.

![image](https://user-images.githubusercontent.com/15966865/143429639-240f8fd3-b376-4991-abca-8988cb031c1f.png)

![image](https://user-images.githubusercontent.com/15966865/143429685-0c8e520f-b236-4eeb-ae60-a2b7d01d1b33.png)

### Environment

- apisix version: Apisix 2.9
- OS : macos 

### Steps to reproduce
1. Apisix open the zipkin plugin, set an upstream and a route
2. use ab to test the route. $  ab -r -c 500 -n 10000  http://localhost:9080/a
3. Then the apisix log shows the error 

Use ab to test 
 open the zipkin plugin, the error shows

### Actual result

unkown

**Comment by shuaijinchao** [comment]
please provide your environment, configuration information and steps to reproduce.

**Comment by zqm233** [comment]
> please provide your environment, configuration information and steps to reproduce.

I test the zipkin in my personal mac now.

1. Apisix open the zipkin plugin, set an upstream and a route. A go service as the upastrem.
2. use ab to test the url  $ ab -r -c 500 -n 10000 http://localhost:9080/a
3. Then the apisix log shows the error
![image](https://user-images.githubusercontent.com/15966865/143432790-32241826-a9e5-46c5-97d5-efead2d9cc86.png)

**Comment by tzssangglass** [comment]
> 1. Apisix open the zipkin plugin, set an upstream and a route. A go service as the upastrem.

show the config of route, upstream

**Comment by shuaijinchao** [comment]
I cannot reproduce the problem following the steps you provided

---

![image](https://user-images.githubusercontent.com/8529452/143515179-2b84155a-ffa4-4438-a2b0-96f706eea688.png)
![image](https://user-images.githubusercontent.com/8529452/143515200-2b55ffbf-82a2-407a-b716-d1511962ddb3.png)
![image](https://user-images.githubusercontent.com/8529452/143515258-07528160-80ce-4f26-8ab5-fee3ec96ca9d.png)
![image](https://user-images.githubusercontent.com/8529452/143515488-b7191a98-75b2-4bae-845f-6c97ef33a2a7.png)

**Comment by zqm233** [comment]
> I cannot reproduce the problem following the steps you provided
> 
> ![image](https://user-images.githubusercontent.com/8529452/143515179-2b84155a-ffa4-4438-a2b0-96f706eea688.png) ![image](https://user-images.githubusercontent.com/8529452/143515200-2b55ffbf-82a2-407a-b716-d1511962ddb3.png) ![image](https://user-images.githubusercontent.com/8529452/143515258-07528160-80ce-4f26-8ab5-fee3ec96ca9d.png) ![image](https://user-images.githubusercontent.com/8529452/143515488-b7191a98-75b2-4bae-845f-6c97ef33a2a7.png)

The error does not show the first test. Just try the test several times in a minute.

**Comment by zqm233** [comment]
> > 1. Apisix open the zipkin plugin, set an upstream and a route. A go service as the upastrem.
> 
> show the config of route, upstream

As the photo.
![image](https://user-images.githubusercontent.com/15966865/143517005-52c39346-09c7-4767-abe4-141da53c3929.png)

![image](https://user-images.githubusercontent.com/15966865/143517042-87a1b6b6-0ba4-4012-bb85-b4d44fe95afa.png)

![image](https://user-images.githubusercontent.com/15966865/143517079-e5a95a12-3686-4edd-b52b-edec40fff7f6.png)

**Comment by tzssangglass** [comment]
I can't reproduce it either

1. start zipkin

`docker run -d -p 9411:9411 openzipkin/zipkin`

2. route config

```json
{
    "plugins": {
        "zipkin": {
            "endpoint": "http://127.0.0.1:9411/api/v2/spans",
            "sample_ratio": 1,
            "service_name": "APISIX-IN-SG"
        }
    },
    "upstream": {
       "nodes": {
           "127.0.0.1:1980": 1
       },
       "type": "roundrobin"
    },
    "uri": "/*"
}
```

3. wrk2

`wrk2 -t4 -c10 -d30s -R1000 --latency http://127.0.0.1:9080/get`

no errors in logs/error.log

**Comment by zqm233** [comment]
> I can't reproduce it either
> 
> 1. start zipkin
> 
> `docker run -d -p 9411:9411 openzipkin/zipkin`
> 
> 2. route config
> 
> ```json
> {
>     "plugins": {
>         "zipkin": {
>             "endpoint": "http://127.0.0.1:9411/api/v2/spans",
>             "sample_ratio": 1,
>             "service_name": "APISIX-IN-SG"
>         }
>     },
>     "upstream": {
>        "nodes": {
>            "127.0.0.1:1980": 1
>        },
>        "type": "roundrobin"
>     },
>     "uri": "/*"
> }
> ```
> 
> 3. wrk2
> 
> `wrk2 -t4 -c10 -d30s -R1000 --latency http://127.0.0.1:9080/get`
> 
> no errors in logs/error.log

What version of the APISIX do you use? Maybe i should the latest version?

**Comment by tzssangglass** [comment]
I know,  you put the zipkin plugin on the global rule?

**Comment by zqm233** [comment]
> I know, you put the zipkin plugin on the global rule.

yes

**Comment by shuaijinchao** [comment]
The problem cannot be reproduced after several retries. Have you checked whether the zipkin service is normal when there is a problem?

**Comment by zqm233** [comment]
> The problem cannot be reproduced after several retries. Have you checked whether the zipkin service is normal when there is a problem?

![image](https://user-images.githubusercontent.com/15966865/143518132-170efcad-316a-4898-ae98-913551750a2f.png)

When the error shows, the Zipkin is ok.

**Comment by tzssangglass** [comment]
my APISIX version is 2.10.2, and we have some bugfix maybe releated to this: https://github.com/apache/apisix/pull/5256 https://github.com/apache/apisix/pull/5295

can you use the master branch or 2.10.2 to test?

**Comment by zqm233** [comment]
> my APISIX version is 2.10.2, and we have some bugfix maybe releated to this: #5256 #5295
> 
> can you use the master branch or 2.10.2 to test?

Ok. I'll try it.

**Comment by zqm233** [comment]
> my APISIX version is 2.10.2, and we have some bugfix maybe releated to this: #5256 #5295
> 
> can you use the master branch or 2.10.2 to test?

The god damn error also shows in 2.10.2. The error didn't show until the 3rd time test. 


![image](https://user-images.githubusercontent.com/15966865/143524228-ea40ad2f-11be-4fe8-b32a-ba3bf3178d58.png)

![image](https://user-images.githubusercontent.com/15966865/143524280-c16adcb3-1afe-4c4f-9a9e-4d12baa51c6d.png)

**Comment by zqm233** [comment]
> my APISIX version is 2.10.2, and we have some bugfix maybe releated to this: #5256 #5295
> 
> can you use the master branch or 2.10.2 to test?

I change to Linux hardware to test it. It's ok. So I guess the error is related to some upstream timeout or something.

**Comment by tzssangglass** [comment]
considered resolved.
