### ISSUE TITLE
request help: How does APISIX make high availability

### ISSUE THREAD

**Issue by XW512** [apache/apisix#5612]
### Issue description

In order to achieve high availability of LVS in apifix, my idea is to forward a layer of nginx to each node of apifix,Do you have a better plan to achieve it

### Environment

- apisix version (cmd: `apisix version`): 2.10
- OS (cmd: `uname -a`): centOS7

**Comment by shuaijinchao** [comment]
Can you describe the design details in more detail? As far as I know, the high availability of LVS is based on keepalive. I did not understand their relationship from your description. Usually LVS will be deployed on the upper layer of API Gateway as a 4-layer load balancer.

**Comment by XW512** [comment]
> Can you describe the design details in more detail? As far as I know, the high availability of LVS is based on keepalive. I did not understand their relationship from your description. Usually LVS will be deployed on the upper layer of API Gateway as a 4-layer load balancer.
My idea is if you need to do a layer of nginx forwarding in the middle of high availability

**Comment by XW512** [comment]
> Can you describe the design details in more detail? As far as I know, the high availability of LVS is based on keepalive. I did not understand their relationship from your description. Usually LVS will be deployed on the upper layer of API Gateway as a 4-layer load balancer.

My idea is if you need to do a layer of nginx forwarding in the middle of high availability

**Comment by tokers** [comment]
> > Can you describe the design details in more detail? As far as I know, the high availability of LVS is based on keepalive. I did not understand their relationship from your description. Usually LVS will be deployed on the upper layer of API Gateway as a 4-layer load balancer.
> 
> My idea is if you need to do a layer of nginx forwarding in the middle of high availability

You don't have to. You may just add a specific Route on APISIX and let the LVS servers probe it so that it can be a heartbeat ping.

**Comment by XW512** [comment]
> > > Can you describe the design details in more detail? As far as I know, the high availability of LVS is based on keepalive. I did not understand their relationship from your description. Usually LVS will be deployed on the upper layer of API Gateway as a 4-layer load balancer.
> > 
> > 
> > My idea is if you need to do a layer of nginx forwarding in the middle of high availability
> 
> You don't have to. You may just add a specific Route on APISIX and let the LVS servers probe it so that it can be a heartbeat ping.

OK, thank you very much

**Comment by XW512** [comment]
Thank you for your reply.
