### ISSUE TITLE
request help: how to construct this kind of route

### ISSUE THREAD

**Issue by jianhaiqing** [apache/apisix#5613]
### Issue description

i want proxy what the client request, nginx conf look like, how can i compose apisix route as follows, 
```
location / {
    proxy_pass "$scheme://$host";
}
```
by the way, i would use plugin to insert header for each request, and user would set ip and domain into hosts file before issue a request. 

Many thanks in advance.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
APISIX's nginx configuration file is automatically generated based on `conf/config.yaml`, I think you can refer to the following two documents to deploy routing and rewrite request related information

https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#route
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-rewrite.md
