### ISSUE TITLE
docs(dubbo-proxy)  the path of example  is wrong

### ISSUE THREAD

**Issue by timxim** [apache/apisix#5617]
### Improved or typo fixed.

这里有个例子，在指定的路由中启用 dubbo-proxy 插件:
curl http://127.0.0.1:9080/apisix/admin/**upstream**/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "nodes": {
        "127.0.0.1:20880": 1
    },
    "type": "roundrobin"
}'

### Solution

curl http://127.0.0.1:9080/apisix/admin/upstreams/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "nodes": {
        "127.0.0.1:20880": 1
    },
    "type": "roundrobin"
}'

**Comment by spacewander** [comment]
PR is welcome!

**Comment by soham4abc** [comment]
Can I work on this issue?
