### ISSUE TITLE
bug: attempt to concatenate field 'shm_name' (a nil value)

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix#5626]
### Issue description

When I use master branch to exec
`make deps`
`make run`
An error occurred.
But when I checkout tag  2.10.2
the error not exists

Is this code forget to pass the right parameters?
![image](https://user-images.githubusercontent.com/31196226/143618191-a1285d30-f167-42d4-b59f-1bb404d46fec.png)
![image](https://user-images.githubusercontent.com/31196226/143618209-e118a081-2e83-4dc3-8efd-f576bb5bda86.png)

### Environment

- apisix version (cmd: `apisix version`):master branch
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

make run

### Actual result

nginx: [error] init_by_lua error: ...b/apisix//deps/share/lua/5.1/resty/etcd/health_check.lua:75: attempt to concatenate field 'shm_name' (a nil value)
stack traceback:
        ...b/apisix//deps/share/lua/5.1/resty/etcd/health_check.lua:75: in function 'init'
        ...ngye/Develop/Projects/Github/apisix/apisix/core/etcd.lua:61: in function 'new'
        ...velop/Projects/Github/apisix/apisix/core/config_etcd.lua:510: in function 'get_etcd'
        ...velop/Projects/Github/apisix/apisix/core/config_etcd.lua:785: in function 'init'
        ...s/changye/Develop/Projects/Github/apisix/apisix/init.lua:84: in function 'http_init'
        init_by_lua:9: in main chunk

### Error log

nginx: [error] init_by_lua error: ...b/apisix//deps/share/lua/5.1/resty/etcd/health_check.lua:75: attempt to concatenate field 'shm_name' (a nil value)
stack traceback:
        ...b/apisix//deps/share/lua/5.1/resty/etcd/health_check.lua:75: in function 'init'
        ...ngye/Develop/Projects/Github/apisix/apisix/core/etcd.lua:61: in function 'new'
        ...velop/Projects/Github/apisix/apisix/core/config_etcd.lua:510: in function 'get_etcd'
        ...velop/Projects/Github/apisix/apisix/core/config_etcd.lua:785: in function 'init'
        ...s/changye/Develop/Projects/Github/apisix/apisix/init.lua:84: in function 'http_init'
        init_by_lua:9: in main chunk

**Comment by spacewander** [comment]
@shuaijinchao 
Please take a look.

**Comment by shuaijinchao** [comment]
@kevinw66 based on your description
1. switch to the master branch (commit ID: 8f0b066c)
2. make deps
3. make run

I cannot reproduce this problem, can you provide more detailed steps to reproduce it?

![image](https://user-images.githubusercontent.com/8529452/143853001-4f3effd9-e65a-4af0-90e8-64f57fccc15a.png)

**Comment by kevinw66** [comment]
Environment
apisix version:master branch
OS:Darwin wuzhiguodeMacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
OpenResty / Nginx version:nginx version: openresty/1.19.9.1
etcd version:3.5.0
luarocks version, if the issue is about installation:3.8.0

**Comment by kevinw66** [comment]
![image](https://user-images.githubusercontent.com/31196226/143975036-fbb6a5fe-23a5-4dee-80f0-208857ceeb0f.png)

**Comment by kevinw66** [comment]
but this can work correctly on branch release/2.11, I'm confused

**Comment by kevinw66** [comment]
After I re-run make deps, the lua-resty-etcd version is upgrade from 1.5.4 to 1.6.0 and this problem disappear.
