### ISSUE TITLE
docs: add APISIX software architecture diagram

### ISSUE THREAD

**Issue by membphis** [apache/apisix#5630]
### Improved or typo fixed.

add new diagram before https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/apisix.md#plugin-loading-process

### Solution

<img width="575" alt="APISIX Software Architecture" src="https://user-images.githubusercontent.com/6814606/143735308-c95af8ea-6dae-4aa6-8c35-77d6c60404c0.png">

**Comment by membphis** [comment]
clearer version

<img width="1155" alt="WX20211128-163519@2x" src="https://user-images.githubusercontent.com/6814606/143735451-13d6fd62-6793-480c-bf53-fa832864e0d3.png">

**Comment by tokers** [comment]
> clearer version
> 
> 
> 
> <img width="1155" alt="WX20211128-163519@2x" src="https://user-images.githubusercontent.com/6814606/143735451-13d6fd62-6793-480c-bf53-fa832864e0d3.png">
> 
> 

Terms like service is captial while client is all in uppercase, I think it's better to keep them consistent.

**Comment by membphis** [comment]
![image](https://user-images.githubusercontent.com/6814606/144421101-b4851bba-310d-44fc-8b14-2489dce31c63.png)

**Comment by soham4abc** [comment]
I am willing to work on this issue. If possible pls assign!

**Comment by membphis** [comment]
we need to update the Chinese doc too: https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/apisix.md

the title should be `软件架构`.

**Comment by membphis** [comment]
ping @soham4abc would you like to try this? https://github.com/apache/apisix/issues/5630#issuecomment-986499739

**Comment by soham4abc** [comment]
> we need to update the Chinese doc too: https://github.com/apache/apisix/blob/master/docs/zh/latest/architecture-design/apisix.md
> 
> the title should be `软件架构`.

This much I will be able to do so. Please do assign me!

**Comment by membphis** [comment]
> This much I will be able to do so. Please do assign me!

done, good luck

**Comment by soham4abc** [comment]
I have issued the PR Please do have a look @membphis @leslie-tsang
