### ISSUE TITLE
How to use Grafana to monitor the number of requests in a time period?

### ISSUE THREAD

**Issue by jianmaikj** [apache/apisix#5631]
### Issue description

Need accurate count

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
There is a metric `apisix_http_status`, you can get the accumulated value if you ignore the `code` label.

* http://apisix.apache.org/docs/apisix/plugins/prometheus/
