### ISSUE TITLE
bug: enable skywalking plugin , the route rewrite is not affected

### ISSUE THREAD

**Issue by dongyudan** [apache/apisix#5633]
### Issue description

**1、route instance properties**
{
  "uri": "/sk2/hello",
  "name": "test skywalking",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "host": "192.168.42.104",
  "plugins": {
    "proxy-rewrite": {
      "uri": "/hello"
    },
    "skywalking": {
      "disable": false,
      "sample_ratio": 1
    }
  },
  "upstream_id": "382869453731268977",
  "status": 1
}

**2、apisix config** 
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
plugins:
    - skywalking
plugin_attr:
  skywalking:
    service_name: Dane
    service_instance_name: "Dane Instance Name"
    endpoint_addr: http://127.0.0.1:12800
    report_interval: 10

### Environment

- apisix version (cmd: `apisix version`):2.10.2
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:2.9
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

![image](https://user-images.githubusercontent.com/11826929/143817162-392b49fc-066b-4d54-8172-de6ef05caecb.png)
add new route, config static rewrite url "/hello"
1、Open “skywalking”  plugin in the dashboard
2、Test route  url  http://192.168.42.104:9080/sky/hello
3、Return the  error message " There was an unexpected error (type=Not Found, status=404)"，
4、Debug up-stream service，found request url  is not rewrite still  is "/sky/hello"
5、Disable “skywalking‘’ plugin  in the dashboard
6、Retest route  url  http://192.168.42.104:9080/sky/hello
7、Return the right data

### Actual result

Route url the same as up stream service node url ，rewrite never happened

### Error log

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Nov 29 11:27:26 CST 2021
There was an unexpected error (type=Not Found, status=404).
No message available

### Expected result

url  is rewrite to "/hello",return the right message .

**Comment by shuaijinchao** [comment]
Have you checked whether the skywalking service is normal? According to the error message you provided, this is more like an exception thrown by a spring framework?

**Comment by tzssangglass** [comment]
the 404 code is returned by upstream, pls confirm that this address is available upstream.

**Comment by dongyudan** [comment]
> Have you checked whether the skywalking service is normal? According to the error message you provided, this is more like an exception thrown by a spring framework?

spring boot service is normal，enable skywalking plugin,the proxy-rewrite plugin is not valid. disable skywalking plugin,the proxy-rewrite plugin work normally

**Comment by dongyudan** [comment]
>The upstream available

**Comment by tzssangglass** [comment]
@dongyudan consider it solved, feel free to reopen this.
