### ISSUE TITLE
request help: support get the key from function in limit-* plugins

### ISSUE THREAD

**Issue by starsz** [apache/apisix#5634]
### Issue description

Hi, 
Now, I see we had support `var`, `var_combination` in apisix limit-* plugins yet.
I think we can support a type like `function` so that we can write some logic as a function in the key.
Then we can get the key from the function.

### Environment

- apisix version (cmd: `apisix version`): 2.10.2
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
What about allowing user to register their var in https://github.com/apache/apisix/blob/8f0b066c86257ad6af19f9b3b7e209ece95d17c9/apisix/core/ctx.lua#L147?

**Comment by starsz** [comment]
> What about allowing user to register their var in
> 
> https://github.com/apache/apisix/blob/8f0b066c86257ad6af19f9b3b7e209ece95d17c9/apisix/core/ctx.lua#L147
> 
> ?

I think support function would be more flexible. 
We can write the function like this: 
```
function generate_key(ctx)
  if ctx.var.http_x_consumer == "a" then
       return "a"
  end

  return "default"
end
```

Then we can limit the specific request with a special header.

**Comment by spacewander** [comment]
We can register the variable with a custom function, like:
```
core.ctx.register_var("my_consumer", function (...)
end)
```

**Comment by starsz** [comment]
> We can register the variable with a custom function, like:
> 
> ```
> core.ctx.register_var("my_consumer", function (...)
> end)
> ```

Oh, that's good.
