### ISSUE TITLE
request help: body_filter how to send request in apisix

### ISSUE THREAD

**Issue by zhangweidongyyl** [apache/apisix#5643]
### Issue description

i want send request in body_filter,based on last request returned Status to send different req

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
we can use a 0 delay  `ngx.timer.at`, see: https://github.com/openresty/lua-nginx-module#ngxtimerat

**Comment by zhangweidongyyl** [comment]
> we can use a 0 delay `ngx.timer.at`, see: https://github.com/openresty/lua-nginx-module#ngxtimerat

This doesn't seem to solve my problem
i use 

> ngx.header[conf.headers_arr[i]] = val 

 in header_filter.
i use 

> ngx.redirect(host) 

in body_filter
I don't know if it can solve this problem, but it can't bring headers 。

**Comment by tzssangglass** [comment]
I cannot got what you want to do.

BTW, ngx.redirect is unavailable in `body_filter_by_lua`, see: https://github.com/openresty/lua-nginx-module#ngxredirect

**Comment by zhangweidongyyl** [comment]
> I cannot got what you want to do.
> 
> BTW, ngx.redirect is unavailable in `body_filter_by_lua`, see: https://github.com/openresty/lua-nginx-module#ngxredirect

ngx.req.set_uri  it seem can  solve my problem

**Comment by tzssangglass** [comment]
As I've already said, if you want to send the request in the body_filter phase, you can use ngx.timer to do so,see: https://moonbingbing.gitbooks.io/openresty-best-practices/content/ngx_lua/timer.html

**Comment by tzssangglass** [comment]
> based on last request returned Status to send different req

you can last request returned Status get by `get_last_failure`, see:https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/balancer.md#get_last_failure

**Comment by zhangweidongyyl** [comment]
> As I've already said, if you want to send the request in the body_filter phase, you can use ngx.timer to do so,see: https://moonbingbing.gitbooks.io/openresty-best-practices/content/ngx_lua/timer.html

yes i slove this problem like this 

>      function _M.body_filter(conf, ctx) 
           local function push_data(premature, uri, args, status)
               -- push the data uri, args, and status to the remote
               -- via ngx.socket.tcp or ngx.socket.udp
               -- (one may want to buffer the data in Lua a bit to
               -- save I/O operations)
           end
           local ok, err = ngx.timer.at(0, push_data,
                                        ngx.var.uri, ngx.var.args, ngx.header.status)
           if not ok then
               ngx.log(ngx.ERR, "failed to create timer: ", err)
               return
           end
         end
 

but my ngx.socket.tcp() always return 400 Bad Request ,how can i slove this problem

**Comment by zhangweidongyyl** [comment]
> As I've already said, if you want to send the request in the body_filter phase, you can use ngx.timer to do so,see: https://moonbingbing.gitbooks.io/openresty-best-practices/content/ngx_lua/timer.html

yes it can slove my problem ,i write like this 

`function _M.body_filter(conf, ctx) 
          local function push_data(premature, uri, args, status)
             -- push the data uri, args, and status to the remote
             -- via ngx.socket.tcp or ngx.socket.udp
             -- (one may want to buffer the data in Lua a bit to
             -- save I/O operations)
         end
         local ok, err = ngx.timer.at(0, push_data,
                                      ngx.var.uri, ngx.var.args, ngx.header.status)
         if not ok then
             ngx.log(ngx.ERR, "failed to create timer: ", err)
             return
         end

end`

but my ngx.socket.tcp() always return 400 Bad Request,how can i reslove this problem

**Comment by zhangweidongyyl** [comment]
i use tcp.socket.connect always return 

use https://github.com/openresty/lua-nginx-module#tcpsockconnect example
failed to connect to google: www.google.com could not be resolved (10060: Operation timed out)

**Comment by tzssangglass** [comment]
> but my ngx.socket.tcp() always return 400 Bad Request,how can i reslove this problem

This is a matter of the request method or request parameters. It has to do with your own service.

> failed to connect to google: [www.google.com](http://www.google.com) could not be resolved (10060: Operation timed out)

This is where your local network environment is unable to resolve the domain name and you can use another domain name that can resolve.

**Comment by tzssangglass** [comment]
I will turn this issue into a discussion, which has nothing to do with the project.
