### ISSUE TITLE
docs: remove the APISIX RPM package installation

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#5647]
### Improved or typo fixed.

The current documentation provides a way to install APISIX directly using RPM on CentOS7, but the current APISIX has switched its dependency to apisix-base version without providing its RPM installation method, which will cause the installation to fail.

![}7Y8{KOAPW6S2QJL2GRL5X4](https://user-images.githubusercontent.com/8078418/144004655-0c4881ea-ccc8-4a76-a384-4ef51779168e.png)

### Solution

Add a command for install apisix-base‘s RPM. 

```shell
sudo yum install -y https://repos.apiseven.com/packages/centos/7/x86_64/apisix-base-1.19.3.2.2-0.el7.x86_64.rpm
```

**Comment by spacewander** [comment]
We should no longer require users to install rpm directly as we already have a yum repo. The yum repo will resolve all the dependencies.

Let's remove https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-packagecentos-7 instead.

**Comment by bzp2010** [comment]
Yes, I agree with this too. But after that our yum repository will be placed in the CDN service provided by ASF?

**Comment by spacewander** [comment]
No. The CDN service provides the source, not the rpm package.

**Comment by leslie-tsang** [comment]
I would like take it. @spacewander
