### ISSUE TITLE
limit-count plugin does not work in redis mode?

### ISSUE THREAD

**Issue by jianmaikj** [apache/apisix#5648]
### Issue description

When the policy is redis, this error occurs: `limit-count.lua:187: phase_func(): failed to limit count: connection refused`,
Tested that redis is normally connectable

### Environment

- apisix version (cmd: `apisix version`):2.10
- OS (cmd: `uname -a`):Centos 7.6
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
Please provide more details about this, also, please provide the way you test the redis.

**Comment by ybbtuubj** [comment]
同样的问题,也是2.10版本,我的redis版本是6.2.6 用的127,0,0.1 6379 redis和apisix都在本地 用redis-cli本地测试redis没有问题

**Comment by tokers** [comment]
What's the route looks like?

**Comment by ybbtuubj** [comment]
我自己写的自定义插件，用的limit-count-redis.lua里面的代码，几乎一模一样复制过来的
![image](https://user-images.githubusercontent.com/20395808/144021211-223090a2-1287-47d3-a85e-c0606da89c36.png)
上图是代码，然后错误里面显示
![image](https://user-images.githubusercontent.com/20395808/144021520-d00eb1a1-60a4-4fdd-8eb5-8ecd90f03e21.png)

**Comment by jianmaikj** [comment]
upstream:
![image](https://user-images.githubusercontent.com/75167751/144030118-531ea169-f89e-4cdb-83ce-d58970ca89d9.png)
route:
![image](https://user-images.githubusercontent.com/75167751/144030313-abadc590-f7e8-48de-83bb-4736297f59e5.png)

When the policy is local or limit-count is not enabled, everything is ok.

**Comment by tzssangglass** [comment]
from the error log, it is clear that this is a network connection problem.

> Tested that redis is normally connectable

How did you tested it was normal?

Can you capture network packets?

**Comment by ybbtuubj** [comment]
嗯，我那个问题早上测了下是我自己的问题，我用容器创建的redis，是容器网络配置的问题。

**Comment by spacewander** [comment]
Consider solved?

**Comment by spacewander** [comment]
Sorry. The people who said the problem is solved isn't the author of this issue.

**Comment by jianmaikj** [comment]
> Sorry. The people who said the problem is solved isn't the author of this issue.

Redis is installed on the host, and the host client can connect and use normally.
![image](https://user-images.githubusercontent.com/75167751/144393000-12c4506b-57f1-40db-a983-5d01e282dd2c.png)
In addition, redis is used in other containers in the host, which is normal.
I have tried ip as 127.0.0.1 and 172.18.0.1 but they all doesn’t work, I don’t understand why

**Comment by tokers** [comment]
> > Sorry. The people who said the problem is solved isn't the author of this issue.
> 
> Redis is installed on the host, and the host client can connect and use normally. ![image](https://user-images.githubusercontent.com/75167751/144393000-12c4506b-57f1-40db-a983-5d01e282dd2c.png) In addition, redis is used in other containers in the host, which is normal. Tested that the Kong gateway enabled rate-limit plug-in is also normal (redis mode). I have tried ip as 127.0.0.1 and 172.18.0.1 but they all doesn’t work, I don’t understand why

Where did you deploy APISIX? Host or container?

**Comment by jianmaikj** [comment]
> > > Sorry. The people who said the problem is solved isn't the author of this issue.
> > 
> > 
> > Redis is installed on the host, and the host client can connect and use normally. ![image](https://user-images.githubusercontent.com/75167751/144393000-12c4506b-57f1-40db-a983-5d01e282dd2c.png) In addition, redis is used in other containers in the host, which is normal. Tested that the Kong gateway enabled rate-limit plug-in is also normal (redis mode). I have tried ip as 127.0.0.1 and 172.18.0.1 but they all doesn’t work, I don’t understand why
> 
> Where did you deploy APISIX? Host or container?
Deploy with container，and after I changed to host mode, it works normally. Is there a way to bridge mode?

**Comment by tzssangglass** [comment]
> 用容器部署，我改成host模式后就正常了

So it seems that this is not a problem with the plugin, but with access to the host network within the container.

> 有没有桥接模式的方法？

I'm not too familiar.

**Comment by tokers** [comment]
> > > > Sorry. The people who said the problem is solved isn't the author of this issue.
> > > 
> > > 
> > > Redis is installed on the host, and the host client can connect and use normally. ![image](https://user-images.githubusercontent.com/75167751/144393000-12c4506b-57f1-40db-a983-5d01e282dd2c.png) In addition, redis is used in other containers in the host, which is normal. Tested that the Kong gateway enabled rate-limit plug-in is also normal (redis mode). I have tried ip as 127.0.0.1 and 172.18.0.1 but they all doesn’t work, I don’t understand why
> > 
> > 
> > Where did you deploy APISIX? Host or container?
> > Deploy with container，and after I changed to host mode, it works normally. Is there a way to bridge mode?

You can also run the redis in container with the same container network.

**Comment by fatihbm** [comment]
> Hi There is the same issue own setup. We try the Redis cluster, but It has unsuccessful connection errors. I think the root cause is related to [lua-resty-redis-cluster](https://github.com/api7/lua-resty-redis-cluster), but I couldn't find any evidence. I opened another issue where you can find some more details about it. [steve0511/resty-redis-cluster#98](https://github.com/steve0511/resty-redis-cluster/issues/98)

By the way, our Redis cluster is setup on a virtual machine. I don't use the container. Also, Redis client can connect to any Redis nodes from any apisix node.
```
root@apisix3:/apisix-2.12.1# redis-cli -h 192.168.55.50 -p 7000 ping
PONG

**Comment by tzssangglass** [comment]
> Hi There is the same issue own setup. We try the Redis cluster, but It has unsuccessful connection errors. I think the root cause is related to [lua-resty-redis-cluster](https://github.com/api7/lua-resty-redis-cluster), but I couldn't find any evidence. I opened another issue where you can find some more details about it. [steve0511/resty-redis-cluster#98](https://github.com/steve0511/resty-redis-cluster/issues/98)

can you submit an new issue to trace this problem?

**Comment by fatihbm** [comment]
> 

I'm having a similar problem. I don't understand the purpose of why I should open a new issue. If this is still necessary, I will of course open it.

**Comment by tzssangglass** [comment]
> I'm having a similar problem. I don't understand the purpose of why I should open a new issue

1. you did not provide steps to reproduce the problem, even if it was similar.
2. you provide an error log in another project.
3. opening a new issue helps us to focus on solving your issue, which we do when it is necessary to merge issues.
