### ISSUE TITLE
request help: unable to collect logs when log-rotate plugin is enabled

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix#5658]
### Issue description

当我开启log-rotate插件后，发起请求后access.log没有日志，关掉log-rotate就有了。

### Environment

- apisix version (cmd: `apisix version`): 2.10.2
- OS (cmd: `uname -a`): centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.5
- apisix-dashboard version, if have: 2.9
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by saintak** [comment]
同样也遇到类似的问题，而且切割日志处理也有问题。

**Comment by shuaijinchao** [comment]
hi, @lihuawei321 @saintak , can you provide the steps to reproduce it? According to the document configuration, I did not reproduce the problem.

![image](https://user-images.githubusercontent.com/8529452/144348736-cc7d61a2-abec-4aa2-9212-0bab27551308.png)

![image](https://user-images.githubusercontent.com/8529452/144348960-7322bc37-5a6a-47f0-9889-fca6aa2cb522.png)

**Comment by saintak** [comment]
> hi, @lihuawei321 @saintak , can you provide the steps to reproduce it? According to the document configuration, I did not reproduce the problem.

我是设置成120秒切割一次，很明显能看出来最后一次切割会影响本次和前一次的文件。参见我提的issue #5663

**Comment by jiangkaiyuan98** [comment]
我是将enable_compression设置为true后，会出现access.log没有日志的现象
![image](https://user-images.githubusercontent.com/49426666/144355443-955ab22d-0d9a-4215-9dc8-e5a31837c7a3.png)
将enable_compression改为false后就正常了
![image](https://user-images.githubusercontent.com/49426666/144355687-959f239d-ccc9-4cd6-9948-beb823233545.png)

**Comment by shuaijinchao** [comment]
@saintak the https://github.com/apache/apisix/issues/5663 question, have you tried to check the file size several times without compression?

![image](https://user-images.githubusercontent.com/8529452/144373536-ec596820-7803-414d-bbc2-ca1321fadb92.png)

**Comment by shuaijinchao** [comment]
@lihuawei321  @saintak @jiangkaiyuan98  Thanks feedback. Reopen and compression will cause log record exceptions. We will fix this problem in the latest version.

**Comment by saintak** [comment]
> @saintak the #5663 question, have you tried to check the file size several times without compression and check the integrity of the file content?
> 
> ![image](https://user-images.githubusercontent.com/8529452/144373536-ec596820-7803-414d-bbc2-ca1321fadb92.png)

没有尝试，我们需要启用压缩，所以没有测试不压缩的情况。

**Comment by saintak** [comment]
> @lihuawei321 @saintak @jiangkaiyuan98 Thanks feedback. Reopen and compression will cause log record exceptions. We will fix this problem in the latest version.

能否加个feature，把tar czvf 改成gzip，后者更方便后续分析。在只有一个文件需要处理的时候打成一个tar包问题多多：
less tar.gz 我们会看到如下内容：

-rw-r--r-- nobody/root     203 2021-12-02 15:35 2021-12-02_15-34-00__error.log
2021-12-02_15-34-00__error.log.tar.gz (END)
zcat tar.gz 是这样的：
zcat 2021-12-02_15-34-00__error.log.tar.gz
2021-12-02_15-34-00__error.log0000644000014300000000000000031314152073437014142 0ustar  nobodyroot2021/12/02 15:34:55 [warn] 4012#4012: *2507624 [lua] log-rotate.lua:138: rotate_file(): remove uncompressed log file: /usr/local/apisix/logs/2021-12-02_15-34-00__access.log ret: true, context: ngx.timer
这样对后续统计分析和查看都是很不利的，相反使用gzip之后：
less 2021-12-02_15-34-00__error.log.gz可以直接显示log内容（而不是文件信息）
zcat 2021-12-02_15-34-00__error.log.gz
2021/12/02 15:36:00 [warn] 4012#4012: *2510131 [lua] log-rotate.lua:138: rotate_file(): remove uncompressed log file: /usr/local/apisix/logs/2021-12-02_15-34-00__access.log ret: true, context: ngx.timer
而且gzip无论是压缩还是解压会默认删除源文件。无需你们再清理原来的文件了。很方便

**Comment by shuaijinchao** [comment]
> > @lihuawei321 @saintak @jiangkaiyuan98 Thanks feedback. Reopen and compression will cause log record exceptions. We will fix this problem in the latest version.
> 
> 能否加个feature，把tar czvf 改成gzip，后者更方便后续分析。在只有一个文件需要处理的时候打成一个tar包问题多多

Good idea, maybe can consider supporting two compression modes. But the essential reason for this problem is the execution sequence of "compression" and "reopening". Are you interested in fix this problem?

**Comment by saintak** [comment]
先解决bug吧，

> > > @lihuawei321 @saintak @jiangkaiyuan98 Thanks feedback. Reopen and compression will cause log record exceptions. We will fix this problem in the latest version.
> > 
> > 
> > 能否加个feature，把tar czvf 改成gzip，后者更方便后续分析。在只有一个文件需要处理的时候打成一个tar包问题多多
> 
> Good idea, maybe can consider supporting two compression modes. But the essential reason for this problem is the execution sequence of `compression` and `reopen`. Are you interested in fix this problem?



> > > @lihuawei321 @saintak @jiangkaiyuan98 Thanks feedback. Reopen and compression will cause log record exceptions. We will fix this problem in the latest version.
> > 
> > 
> > 能否加个feature，把tar czvf 改成gzip，后者更方便后续分析。在只有一个文件需要处理的时候打成一个tar包问题多多
> 
> Good idea, maybe can consider supporting two compression modes. But the essential reason for this problem is the execution sequence of `compression` and `reopen`. Are you interested in fix this problem?

先解决bug吧，我不太懂lua，改不了。
使用gzip的logrotate等你们修复bug之后我可以在原来的基础上改写一个新的插件。

**Comment by lihuawei321** [comment]
> 



> 将enable_compression设置为true后，会出现access.log没有日志的现象

我现在也是这样，请问你解决了吗？

**Comment by stubbornTanzhe** [comment]
```
2022/06/30 07:00:00 [error] 48#48: *12614439 [lua] log-rotate.lua:206: compression_file(): remove uncompressed log file: /usr/local/apisix/logs//2022-06-30_07-00-00__access.log fail, err:/usr/local/apisix/logs//2022-06-30_07-00-00__access.log: No such file or directory  res:nil, context: ngx.timer
```
why is there a extra slash?

**Comment by stubbornTanzhe** [comment]
ping @shuaijinchao

**Comment by soulbird** [comment]
> ```
> 2022/06/30 07:00:00 [error] 48#48: *12614439 [lua] log-rotate.lua:206: compression_file(): remove uncompressed log file: /usr/local/apisix/logs//2022-06-30_07-00-00__access.log fail, err:/usr/local/apisix/logs//2022-06-30_07-00-00__access.log: No such file or directory  res:nil, context: ngx.timer
> ```
> 
> why is there a extra slash? /usr/local/apisix/logs//2022-06-30_07-00-00__access.log
> 
> ```
> plugin_attr:                                                                                             
>   log-rotate:                                                                                            
>     interval: 3600    # rotate interval (unit: second)                                                    
>     max_kept: 168     # max number of log files will be kept                                             
>     enable_compression: true    # enable log file compression(gzip) or not, default false
> ```
> 
> version:2.14.1
> 
> btw,change compression to false then log back to normal

Can you provide more information? I can't reproduce it with your configuration

**Comment by tzssangglass** [comment]
> why is there a extra slash?

pls submit an new issue to report this.

**Comment by stubbornTanzhe** [comment]
> version:2.14.1
> 
> btw,change compression to false then log back to normal

I'll keep watching, less infomation this time. next occur i'll submit new issue with full info

**Comment by lihuawei321** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/31987918/196138684-4533743f-85bd-49af-8e71-8e9a6b30d19f.png">
我开启日志压缩后，原有的access.log还会存在，这样压缩感觉没有意义，这个是什么问题？

**Comment by tzssangglass** [comment]
> 我开启日志压缩后，原有的access.log还会存在，这样压缩感觉没有意义，这个是什么问题？

you can config `max_kept` to adjust how long to keep the log, ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/log-rotate.md#attributes

**Comment by lihuawei321** [comment]
> 

我知道，问题是同一时间的既有压缩后的日志，又有原由的access.log。正常应该只有压缩的。

**Comment by tzssangglass** [comment]
> 我知道，问题是同一时间的既有压缩后的日志，又有原由的access.log。正常应该只有压缩的。

I looked at the code and the original log should be deleted after the compression is complete, apparently, this is a failure, is there a log related to this in the error log? like: `remove uncompressed log file:`
