### ISSUE TITLE
request help: serverless plugin question

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#5662]
### Issue description

I see the documentation inside the last can use serverless plugin to do external authentication, but this code how to configure into serverless plugin it can give an example?
![image](https://user-images.githubusercontent.com/92301646/144208600-b442fdcb-162b-472f-88ed-5402ae401192.png)
I escaped through json compression and put it in the functions field is not possible, it seems that as the documentation says can only write functions, but how to put this code in it.
```bash
"plugins": {
    "serverless-pre-function": {
      "disable": false,
      "functions": [
        "localhttp=require('resty.http')localhttpc=http.new()localres,err=httpc:request_uri('http://www.baidu.com',{keepalive_timeout=2000,headers={[\"Content-Type\"]=\"application/json\",}})ifnotresorres.statusthencore.response.exit(403)returnifres.status==302thencore.response.exit(302)end"
      ]
    }
  },
```
![image](https://user-images.githubusercontent.com/92301646/144210856-64f528ed-ef55-4301-95ad-5cbe62585a61.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.2
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
The custom function should be wrapped with `return function(conf, ctx)  ... end` in the code block. See https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/serverless.md#how-to-enable

```
curl -i http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "serverless-pre-function": {
            "phase": "rewrite",
            "functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
        },
        "serverless-post-function": {
            "phase": "rewrite",
            "functions" : ["return function(conf, ctx) ngx.log(ngx.ERR, \"match uri \", ctx.curr_req_matched and ctx.curr_req_matched._path); end"]
			# ^-- wrap the function
        },
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```

And remember to keep the whitespace, so it can be a valid Lua code.

I suggest using a script to generate the JSON instead of editing it manually.

**Comment by GhangZh** [comment]
Yes, I see that the documentation says that you can only put functions, and I have tested this demo and it is fine. [how-to-use-apisix-auth](https://www.apiseven.com/zh/blog/how-to-use-apisix-auth) This article says it's possible so I'm asking how this is supported
> The custom function should be wrapped with `return function(conf, ctx) ... end` in the code block. See https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/serverless.md#how-to-enable
> 
> ```
> curl -i http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/index.html",
>     "plugins": {
>         "serverless-pre-function": {
>             "phase": "rewrite",
>             "functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
>         },
>         "serverless-post-function": {
>             "phase": "rewrite",
>             "functions" : ["return function(conf, ctx) ngx.log(ngx.ERR, \"match uri \", ctx.curr_req_matched and ctx.curr_req_matched._path); end"]
> 			# ^-- wrap the function
>         },
>     },
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "127.0.0.1:1980": 1
>         }
>     }
> }'
> ```
> 
> And remember to keep the whitespace, so it can be a valid Lua code.
> 
> I suggest using a script to generate the JSON instead of editing it manually.

**Comment by starsz** [comment]
> 

Hello, @GhangZh 

Sorry for the late reply. This article takes an example of how to use serverless plugins to do authentication.
As @spacewander suggested, you should put the logic in the function.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
