### ISSUE TITLE
docs: ldap-auth plugin's doc is missing Consumer parameters

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#5668]
### Improved or typo fixed.

According to `ldap-auth` plugin's implementation[1], our docs are missing parameters when configuring Consumer.

See https://apisix.apache.org/docs/apisix/plugins/ldap-auth/

### Solution

Add the description of Consumer parameters.

[1] https://github.com/apache/apisix/blob/master/apisix/plugins/ldap-auth.lua#L40-L47

**Comment by zaunist** [comment]
Hi, @juzhiyuan. I just open a pull request to add consumer parameter, https://github.com/apache/apisix/pull/5736. Please take a look..
