### ISSUE TITLE
docs: skywalking-logger plugin doc is using an incorrect configuration demo

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#5671]
### Improved or typo fixed.

Please see https://apisix.apache.org/docs/apisix/plugins/skywalking-logger

![image](https://user-images.githubusercontent.com/2106987/144371319-6b66d78a-9900-4244-b1bd-f4837a4faf2c.png)

### Solution

🤔 There should be `skywalking-logger` with proper configurations, right?

https://github.com/apache/apisix/blob/master/apisix/plugins/skywalking-logger.lua

**Comment by spacewander** [comment]
Solved in the master branch.
