### ISSUE TITLE
bug: modify SSL Port not working in 2.10.1

### ISSUE THREAD

**Issue by chanjet1213** [apache/apisix#5672]
### Issue description

直接修改config.yaml文件或者修改config-default.yaml中9443端口为443后不生效，需要同时修改config.yaml和config-default.yaml中的9443端口。

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):centos7.8

### Steps to reproduce

1.修改config.yaml中ssl 9443端口为443，重启apisix，运行端口仍为9443
2.修改config-default.yaml中ssl 9443端口为443.重启apisix，运行端口为443

### Actual result

无

### Error log

无

**Comment by tzssangglass** [comment]
can you show the `conf/nginx.conf` after you only do the step 1.
