### ISSUE TITLE
request help: 

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix#5679]
### Issue description

make lint cannot use in macos.

I installed luarocks and lua via brew
but after I install luacheck and run `make lint`
an error occurred `ERROR: lj-releng ONLY supports LuaJIT 2.1!`

### Environment

macos

**Comment by tzssangglass** [comment]
```shell
$ luajit -v
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2020 Mike Pall. https://luajit.org/
$ which luajit
/usr/local/Cellar/openresty-debug/luajit/bin/luajit
```

What is your output？

**Comment by kevinw66** [comment]
> 

Thanks, I forgot to set env variable
