### ISSUE TITLE
Can using APISIX as an Object Storage Gateway？

### ISSUE THREAD

**Issue by cws1981** [apache/apisix#5680]
### Issue description

As titled

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Yes. See https://www.163.com/dy/article/GKVLC7RU0511D3QS.html
