### ISSUE TITLE
How to pass custom context in different phases of plugin execution?

### ISSUE THREAD

**Issue by solo-xwz** [apache/apisix#5694]
### Issue description

Such as access and log phases

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
You can use the ctx argument.
https://github.com/apache/apisix/blob/master/apisix/plugins/zipkin.lua is a good example.
