### ISSUE TITLE
request help: go-plugin-runner error after starting in debug mode

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#5708]
### Issue description

There has  an error after starting in debug mode。When I setting like this，it didn’t find  /tmp/runner.sock,And there is no content either.My custom plugin name is forward-auth
```bash
phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-46.sock: no such file or directory
```
![image](https://user-images.githubusercontent.com/92301646/144560426-10b9998d-d8d8-424d-8177-4ba3e7815780.png)
![image](https://user-images.githubusercontent.com/92301646/144560520-4c54b2bd-b102-4f97-b0fb-2fb0d4a1c397.png)
![image](https://user-images.githubusercontent.com/92301646/144560734-e1679bcd-0c8d-4636-9ec8-81777ced0b80.png)
![image](https://user-images.githubusercontent.com/92301646/144560832-6a39be12-7e63-43eb-bd0a-02b3a7d11517.png)
![image](https://user-images.githubusercontent.com/92301646/144783842-2c4455f1-74ed-4997-b073-44db8d2b79e6.png)

### Environment

- apisix version (cmd: `apisix version`):2.10
- OS (cmd: `uname -a`):linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):apisix-go-plugin-runner version latest--go1.16.9
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Is it relative to https://github.com/apache/apisix/discussions/5628#discussioncomment-1713241?

**Comment by GhangZh** [comment]
> Is it relative to [#5628 (reply in thread)](https://github.com/apache/apisix/discussions/5628#discussioncomment-1713241)?

Different, his sock is not found, my issue is not to find the sock, and my /tmp/runner.sock is automatically generated

**Comment by spacewander** [comment]
Can't reproduce on my side. My configuration is:
```
ext-plugin:
  path_for_test: /tmp/runner.sock
 #cmd: ["/home/lzx/git/apisix-go-plugin-runner/go-runner", "run", "-m", "prod"]

```

I got the expected error: "phase_func(): failed to connect to the unix socket unix:/tmp/runner.sock".

Maybe you can add more log to https://github.com/apache/apisix/blob/a4b6931390c302724675f9026078d479c6295119/apisix/plugins/ext-plugin/helper.lua#L32

**Comment by GhangZh** [comment]
> 

Thanks for the help, it was a problem with the environment variables that didn't get this configuration

**Comment by kingmouse-yx** [comment]
Bro, I also met the general problem, can you tell me how to solve it?

**Comment by jinghuaz** [comment]
[crit] 51#51: *132869 connect() to unix:/usr/local/apisix/conf/apisix-47.sock failed (13: Permission denied),
 [error] 51#51: *132869 [lua] init.lua:689: phase_func(): failed to connect to the unix socket unix:/usr/local/apisix/conf/apisix-47.sock: permission denied, 
[warn] 51#51: *132869 [lua] plugin.lua:722: run_plugin(): ext-plugin-pre-req exits with http status code 503,

**Comment by juzhiyuan** [comment]
> Bro, I also met the general problem, can you tell me how to solve it?

Hi, please create a new issue and attach the detailed reproduction steps, so we could help you :)

**Comment by GhangZh** [comment]
> Bro, I also met the general problem, can you tell me how to solve it?

Check that apisix config.yaml is correctly configured, the main reason for this error is that your configuration file does not read the configuration for listening here . You can look at this code apisix/apisix/plugins/ext-plugin/helper.lua
