### ISSUE TITLE
return 504

### ISSUE THREAD

**Issue by fish2018** [apache/apisix#5709]
### Issue description

域名app01.demo.com解析到apisix
apisix在slave01节点
现在从slave01上curl app01.demo.com会报504
腾讯云售后技术说可能是网络回环，谁遇到过这个问题吗？

![avatar](https://raw.githubusercontent.com/fish2018/files/master/imgs/apisix_issue01.png)

### Environment

腾讯云

**Comment by leslie-tsang** [comment]
@juzhiyuan Plz assign it to me.

**Comment by leslie-tsang** [comment]
I afraid this can't be slove by Apache APISIX, Ref from the following information found

 1. https://github.com/kubernetes/kubernetes/issues/79783
 2. https://cloud.tencent.com/document/product/457/61737
 3. https://help.aliyun.com/document_detail/171437.html

**Comment by moonming** [comment]
@fish2018 
Please use English in the public channel, thx

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if need.
