### ISSUE TITLE
request help: Can the jwt plugin support custom authentication parameter names?

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#5710]
### Issue description

目前jwt plguin 参数名称是写死的，能不能跟hmac一样，通过配置修改参数名称。

$ curl http://127.0.0.1:9080/index.html?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJ1c2VyLWtleSIsImV4cCI6MTU2NDA1MDgxMX0.Us8zh_4VjJXF-TmR5f8cif8mBU7SuefPlpxhH0jbPVI -i
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 13175

将jwt修改为其他参数。

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
PR is welcome!

**Comment by shaobo322** [comment]
`jwt-plugin` can be configued to different levels, `consumer` and `router`, which level do you want to configure?

**Comment by qq54903099** [comment]
> 

just like hmac-plugin；global rules

**Comment by liangliang4ward** [comment]
@spacewander hi, I wan't to know why this PR: https://github.com/apache/apisix/pull/5738 closed. It's something wrong?
if not other question, I can create pr to solve this issue;

**Comment by spacewander** [comment]
I pointed out that #5738 doesn't handle the param configuration correctly (it is configured in consumer but used as it is from route), then the author closed it (without creating a new one).

You can give it a try but in a new way.

**Comment by liangliang4ward** [comment]
> You can give it a try but in a new way.

ok。 pls assign me

**Comment by liangliang4ward** [comment]
> I pointed out that #5738 doesn't handle the param configuration correctly (it is configured in consumer but used as it is from route), then the author closed it (without creating a new one).
> 
> You can give it a try but in a new way.

I think this configuration can be configured in a config.yaml like hmac-auth. Or like key-auth config to route.
I prefer to configure to config.yaml, or go one step further and still support configuration to route with priority route> config.yaml
