### ISSUE TITLE
bug: apisix.service cannot be started automatically, and ulimit is not set

### ISSUE THREAD

**Issue by saintak** [apache/apisix#5711]
### Issue description

apisix.service这个文件配置的不对，可以参照我的版本设置：
说明：conflict这个配置没啥用处，不必保留
没有[install]，服务就是static的，没法设置为开机启动
systemd启动的服务的ulimit不能继承系统的ulimit，所以需要单独设置
配置restart可以在服务挂断之后尝试拉起

[Unit]
Description=apisix
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
Restart=on-failure
WorkingDirectory=/usr/local/apisix
ExecStart=/usr/bin/apisix start
ExecStop=/usr/bin/apisix stop
ExecReload=/usr/bin/apisix reload
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
通过yum安装的centos7上的apisix,自带的apisix.service编写是有问题的。

### Steps to reproduce

1.systemctl start apisix.service 尝试启动
2.systemctl status apisix.service
发现报错
`Warning! Current maximum number of open file descriptors [1024] is not greater than 1024, please increase user limits by execute 'ulimit -n <new user limits>' , otherwise ...rformance is low.`
并且发现服务是static,无法通过systemctl enable设置为开机自动启动 apisix.service:
● apisix.service - apisix
   Loaded: loaded (/usr/lib/systemd/system/apisix.service; static; vendor preset: disabled)
   Active: active (running) since Mon 2021-12-06 15:17:18 CST; 11min ago

### Actual result

无法设置开机自动启动
limit设置不正确

### Error log

Warning! Current maximum number of open file descriptors [1024] is not greater than 1024, please increase user limits by execute 'ulimit -n <new user limits>' , otherwise ...rformance is low.

### Expected result

[Unit]
Description=apisix
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
Restart=on-failure
WorkingDirectory=/usr/local/apisix
ExecStart=/usr/bin/apisix start
ExecStop=/usr/bin/apisix stop
ExecReload=/usr/bin/apisix reload
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target

**Comment by leslie-tsang** [comment]
PR is welcome, would you take it a try ?

**Comment by saintak** [comment]
> PR is welcome, would you take it a try ?

翻看了半天没在代码库找到apisix.service的位置，所以我应该提到哪个位置呢？

**Comment by leslie-tsang** [comment]
> > PR is welcome, would you take it a try ?
> 
> 翻看了半天没在代码库找到apisix.service的位置，所以我应该提到哪个位置呢？

Hello there, right [here](https://github.com/api7/apisix-build-tools/blob/master/usr/lib/systemd/system/apisix.service)

**Comment by saintak** [comment]
> > > PR is welcome, would you take it a try ?
> > 
> > 
> > 翻看了半天没在代码库找到apisix.service的位置，所以我应该提到哪个位置呢？
> 
> Hello there, right [here](https://github.com/api7/apisix-build-tools/blob/master/usr/lib/systemd/system/apisix.service)

好的，已经提了pr

**Comment by moonming** [comment]
@saintak 
Please use English in the public channel, thx

**Comment by spacewander** [comment]
Solved by https://github.com/api7/apisix-build-tools/pull/143
Thanks for @saintak
