### ISSUE TITLE
bug: when I use the kafka-logger plugin, failed to fetch the time in kafka

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix#5719]
### Issue description

我写入kafka的日志格式是：
[{"client_ip":"192.168.35.122","host":"192.168.9.234","@timestamp":"2021-12-07T10:41:12+08:00","route_id":"363894265081758809"}]
但是kafka显示的没有时间戳
![image](https://user-images.githubusercontent.com/31987918/144979540-a72a98be-423a-4a70-a736-093f5c610647.png)

### Environment

- apisix version (cmd: `apisix version`): 2.10
- OS (cmd: `uname -a`): centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have: 2.9
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi, could you please provide more steps so I could reproduce it?

**Comment by tzssangglass** [comment]
pls describe it more clearly. From the information you have provided, I do not know what is `failed to fetch the time in kafka`

**Comment by bfyxzls** [comment]
I also have the same issue, the created service config is:
```
"log_format": {
    "@timestamp": "$time_iso8601",
    "accessPage": "$http_accessPage",
    "accessSource": "$http_accessSource",
    "api": "$request_uri",
    "appVersion": "$http_appVersion"
  }
```

![Image](https://github.com/user-attachments/assets/6a11a51a-7da1-4428-907c-0d854f69e2a5)
