### ISSUE TITLE
request help: module 'toolkit.json' not found when use test-nginx for unit test

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#5729]
### Issue description

![image](https://user-images.githubusercontent.com/5835937/145031554-91ed0c6e-f69d-4d9f-a290-5dcaeab8bee1.png)

test-nginx project is clone like this

root/ is project root
- root/test-nginx
- roor/apisix
 test-nginx test is fine.

but cd to apisix and run is fail
```
prove -I. -I../test-nginx/inc -I../test-nginx/lib -r t/script
```

Then copy the https://github.com/api7/test-toolkit to root/apisix/t/toolkit
https://github.com/apache/apisix/issues/2936

The problem is still there.

In addition, there are some problems in the documentation of the development environment of the whole apifix. Although I have handled them, it still took me two days.

Hope this is the last question. - -!

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`): macos
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 1.19.3.2
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
1.  it is not recommended that apisix be placed in the `root` directory;
2. basically my directory structure is similar to yours. Looking at the search path in the error output, it doesn't search for a path under `/root/apisix` at all.

**Comment by xuminwlt** [comment]
> 1. it is not recommended that apisix be placed in the `root` directory;
> 2. basically my directory structure is similar to yours. Looking at the search path in the error output, it doesn't search for a path under `/root/apisix` at all.

root is my example path, the true path is my account path
~/github/apisix

The error message should be that I found the file under APIs / T / Toolkit, but the preload failed. I don't know why. Maybe I need to find the answer.
Maybe I can be a contribute for these question.

**Comment by xuminwlt** [comment]
Problem solved，clone to the t/  path is right，i have copied it to /t/lib, /t/lib  is wrong.
