### ISSUE TITLE
request help: sometimes connection refused while using service ip to connect the upstream

### ISSUE THREAD

**Issue by sekfung** [apache/apisix#5733]
### Issue description

**error log**
```log
[error] 48#48: *2240177 connect() failed (111: Connection refused) while connecting to upstream

[lua] balancer.lua:327: run(): failed to pick server: failed to find valid upstream server, all upstream servers tried while connecting to upstream

```

It can work sometimes, I try to increase times of retry for the route, but it can't solve this problem at all.

### Environment

- apisix version (cmd: `apisix version`): 2.10.1
- OS (cmd: `uname -a`): Linux apisix-6df8748bf6-v5hnb 4.14.105-19-0022
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): etcd Version: 3.4.16
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi @leslie-tsang, could you give some ideas on how to debug this issue?

**Comment by sekfung** [comment]
BTW，it deploy on k8s cluster

**Comment by leslie-tsang** [comment]
> Hi @leslie-tsang, could you give some ideas on how to debug this issue?

Yes for sure.


> ### Issue description
> **error log**
> 
> ```
> [error] 48#48: *2240177 connect() failed (111: Connection refused) while connecting to upstream
> 
> [lua] balancer.lua:327: run(): failed to pick server: failed to find valid upstream server, all upstream servers tried while connecting to upstream
> ```
> 
> It can work sometimes, I try to increase times of retry for the route, but it can't solve this problem at all.

Could you exec `curl` with `-v` to verify the network between apisix and upstream is working as expected ?
e.g.
```shell
curl -v http://upstream:port/uri
```

**Comment by sekfung** [comment]
@leslie-tsang 

**Success**
```log
curl -v http://10.1.56.0:20810/pay/unifiedorder

*   Trying 10.1.56.0:20810...
* Connected to 10.1.56.0 (10.1.56.0) port 20810 (#0)
> GET /pay/unifiedorder HTTP/1.1
> Host: 10.1.56.0:20810
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 405 
< Vary: Origin
< Vary: Access-Control-Request-Method
< Vary: Access-Control-Request-Headers
< Allow: POST
< Content-Type: application/json
< Transfer-Encoding: chunked
< Date: Wed, 08 Dec 2021 08:08:57 GMT
< 
* Connection #0 to host 10.1.56.0 left intact
```

**Failed**
```log
curl -v http://10.1.56.0:20810/pay/unifiedorder

*   Trying 10.1.56.0:20810...
* connect to 10.1.56.0 port 20810 failed: Connection refused
* Failed to connect to 10.1.56.0 port 20810 after 2 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 10.1.56.0 port 20810 after 2 ms: Connection refused
```
