### ISSUE TITLE
docs: how to traffic service percentage 

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix#5737]
### Improved or typo fixed.

How do I verify the correctness of the plugins

### Solution

I want to be able to use traffic-split similar plug-ins to control the percentage of service traffic

**Comment by Horus-K** [comment]
We have a very large user base，I need control plugings(response-rewrite.body) change

**Comment by tzssangglass** [comment]
> How do I verify the correctness of the plugins

We have test cases to cover the functionality of the plugin.

But you still need to verify it in your environment. You can verify this against the plugin's functional documentation.

> I need control plugings(response-rewrite.body) change

I don't know what you mean.

**Comment by Horus-K** [comment]
I need to be able to achieve service percentage, similar to upstream percentage

**Comment by Horus-K** [comment]
route binds multiple service

**Comment by tzssangglass** [comment]
> I need to be able to achieve service percentage, similar to upstream percentage

show a detailed case to describe the scene.

> route binds multiple service

we have already support this, pls read docs first.

**Comment by Horus-K** [comment]
> show a detailed case to describe the scene.

**Comment by Horus-K** [comment]
> show a detailed case to describe the scene.
![image](https://user-images.githubusercontent.com/48319268/145330261-be067eaf-87fa-4cdb-9dc4-ab52c548d1e2.png)
This route will return two results  XXX or GGG

**Comment by Horus-K** [comment]
> we have already support this, pls read docs first.

**Comment by Horus-K** [comment]
> we have already support this, pls read docs first.
I only see that route can be bound to one serviceid or pluginid

**Comment by tzssangglass** [comment]
> This route will return two results XXX or GGG

This is not supported. This would break some of the abstractions of APISIX.

I think you can get around this in other ways, such as setting up multiple routes. Or modify the response-rewrite plugin yourself.
