### ISSUE TITLE
bug: apisix reload Cannot clear uninitialized plug-ins

### ISSUE THREAD

**Issue by Jon-Gaara** [apache/apisix#5749]
### Issue description

如果我自定义了一个lua脚本，但是脚本里没有定义schema，会导致插件load不成功，这时候，我给这个插件再重新加上schema，然后执行apisix reload，这个插件还是会加载不成功，并且报之前的错误，这是因为plugin.lua再unload_plugin的时候，只是unload已经加载成功的plugin，导致没有被加载成功的plugin，用require加载的时候，还是加载之前错误的那个脚本

### Environment

- apisix version (cmd: `apisix version`):
- 2.10.0
- OS (cmd: `uname -a`):
- Linux sz-jon-yu 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- nginx version: openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.编写一个lua脚本，但是不设置schema
2.把lua脚本放到apisix/plugins目录下
3.执行curl http://127.0.0.1:9080/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT
4.查看日志，会出现报错信息
5.修改lua脚本，加上schema，重新执行reload
6.查看日志发现还是会出现之前的错误

### Actual result

查看日志发现还是会出现之前的错误

### Error log

   2021/12/09 10:34:29 [error] 2961467#0: *27804 [lua] plugin.lua:109: load_plugin(): invalid plugin [gw-api] schema field, context: ngx.timer
   2021/12/09 10:34:29 [error] 2961476#0: *27805 [lua] plugin.lua:109: load_plugin(): invalid plugin [gw-api] schema field, context: ngx.timer

### Expected result

期待执行reload，能把之前未初始化的插件，能够重新reload，不然就需要重启apisix才能重新加载

**Comment by tzssangglass** [comment]
plugin reload assumes the plugin is valid by default (at least it functions properly)

I'm not sure what good this change would do.

**Comment by Jon-Gaara** [comment]
1.目前我们在开发测试的时候，由于我一个同事新开发一个插件，但是这个插件不需要参数，所以就没加schema，出现了以上的情况
2.还有一种情况，如果我之前的插件是正常运行的，但是由于我把插件的version删掉或者schema删掉，然后reload，这时候肯定是加载不成功的，然后我把version和schema再修改回来，然后reload，结果我一个正常运行的插件，就不能运行。
 3.当然这些情况一般只会发生在开发阶段的一些不规范的操作才能产生，但是我觉得因为在apisix的热加载文档有所体现，
因为根据apisix的文档，不管新增、修改、还是删除插件，都不需要重启服务，但是我发现在某些情况并不会热加载

**Comment by tzssangglass** [comment]
> 不管新增、修改、还是删除插件，都不需要重启服务

The prerequisite is that the plugin code works properly. I don't think there's much need to make compatibility for code that doesn't work properly, it's just useless.

**Comment by Jon-Gaara** [comment]
ok,i know
