### ISSUE TITLE
request help: unfriendly notice message return when forgetting enable Authentication plugin on route / service configuration

### ISSUE THREAD

**Issue by Fatpa** [apache/apisix#5751]
### Issue description

After I created the consumer and enable it on the consumer-restriction of the route configuration, I try to visit it but got the misunderstanding return message, `{"message": "Missing authentication or identity verification."}`. It makes me confused that what happened? Invalid signature or others? 

In my opinion, may the return message should be more clearly, like `"Missing authentication or identity verification, please check your route / service configuration and maybe you forget to enable some plugins"`.

Or we maybe don't need to enable the same plugin again in the route / service configuration, I think both are working.

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`): 3.10.0-1160.6.1.el7.x86_64

**Comment by tokers** [comment]
Basically, the message returned is for the caller side, and let the caller to check out the route/service configuration is not so proper IMHO.

But we still can enrich the message, at lease we can tell the caller that certain types of credentials should be taken when send a request.

**Comment by Fatpa** [comment]
Can show the warning in the apisix error log?

**Comment by tokers** [comment]
> Can show the warning in the apisix error log?

These types of logs should print with the `info` or `notice` level.
