### ISSUE TITLE
request help: OpenWhisk plugin does not support modifying the response

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#5756]
## Description
The current `openwhisk` plugin will take the response from Apache OpenWhisk and return it directly without parsing. This request may contain complex data that rewrites the status code, response headers, and response body. We need to parse it and change the APISIX response.

The complex data like this:
```text
{
  "statusCode": 401,
  "headers": {
    "addition-header": "a-header"
  },
  "body": "xxx" | {"xxx":"xxx"}
}
```
We need to determine if the OpenWhisk response contains them, and if they are present, write them to the APISIX response.

**Comment by bardolphshampine** [comment]
This is a great proposal, I wish to give it a try.

**Comment by xetraforest-fenghan** [comment]
This is a great proposal, I wish to give it a try
