### ISSUE TITLE
Bug: about code style

### ISSUE THREAD

**Issue by CppCXY** [apache/apisix#5760]
### Issue description

I looked at the code style specification for the project, but I found that almost every file in the lua code in the project did not comply with the code style specification.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1. clone project
2. check lua code

### Actual result

It's ugly

### Error log

no

### Expected result

beautiful

**Comment by spacewander** [comment]
Having a code style is good, but is not necessary. A strange style doesn't prevent LuaJIT to become a fantasy project. We don't want to waste time arguing the code style.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix/blob/master/CODE_STYLE.md We have a CODE_STYLE file here 😄

**Comment by CppCXY** [comment]
> https://github.com/apache/apisix/blob/master/CODE_STYLE.md We have a CODE_STYLE file here 😄

I know, but I'm sure you didn't follow your code style

**Comment by CppCXY** [comment]
> The code of APISIX follows the https://github.com/apache/apisix/blob/master/CODE_STYLE.md specification. What do you think is the problem? Please give an example.

https://github.com/apache/apisix/blob/5ae38f81f25fc58a040e30d12ba8fef33bb56f60/apisix/wasm.lua#L42 do not keep 2 line
https://github.com/apache/apisix/blob/c178435d7ada4eeb713d9a1688fb5f54f971abdf/apisix/debug.lua#L104 why do end block no indent
https://github.com/apache/apisix/blob/c178435d7ada4eeb713d9a1688fb5f54f971abdf/apisix/stream/plugins/limit-conn.lua#L26 not only one space after ','

https://github.com/apache/apisix/blob/c178435d7ada4eeb713d9a1688fb5f54f971abdf/apisix/http/router/radixtree_uri_with_parameter.lua#L28 strange indent

...
