### ISSUE TITLE
bug: nacos.lua make some duplicate instance 

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix#5767]
### Issue description

1、deploy a  service  to register to the nacos
2、config some rule  and service and upstreams  at the apisix
3、make a test   
4、add some  log  at the balancer.lua, and  print the  upstream  nodes
5、 from the log  , that  is  3 instance  in the apisix,  but  that is  one  in the nacos.

I  read the  code  nacos.lua   ,and  find the reason:  it will get the same service  the  follow code,
local function get_nacos_services()
    local services = {}
    -- here we use lazy load to work around circle dependency
    local get_upstreams = require('apisix.upstream').upstreams
    local get_routes = require('apisix.router').http_routes
    local get_services = require('apisix.http.service').services
    local values = get_upstreams()
    iter_and_add_service(services, values)
    values = get_routes()
    iter_and_add_service(services, values)
    values = get_services()
    iter_and_add_service(services, values)
    return services
end

---------------------
and  I  try to fix it  like this, in the  local function fetch_full_registry(premature)  :
local infos = get_nacos_services()
    if #infos == 0 then
        applications = up_apps
        return
    end
    table.sort(infos,function(a,b)
        return a.namespace_id .. a.group_name .. a.service_name > b.namespace_id .. b.group_name .. b.service_name
    end)
    local last_service_info
    for _, service_info in ipairs(infos) do
        if compareService(last_service_info,service_info) then
            goto CONTINUE
        end
        last_service_info = service_info
        local data, err
        local namespace_id = service_info.namespace_id

----------------------
It  that   another  better way to fix it?  Thank you who can  fix it  in the github,     and I   can   get the code  next time。

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

use  the  nacos as the discovery .
and  add some code to print the upstream nodes  at the balancer.lua

### Actual result

the  instance is the same as the nacos

### Error log

no  error log

**Comment by tzssangglass** [comment]
> from the log , that is 3 instance in the apisix, but that is one in the nacos.

I don't really understand this. how did you determine that there were three instances? AFAIK, it is possible that the logs are output by different workers.

pls provide some more information.

**Comment by xianshun163** [comment]
I write a log  at  the  upstream.lua  at  250  line:
    246         local new_nodes, err = dis.nodes(up_conf.service_name, up_conf.discovery_args)
    247         if not new_nodes then
    248             return HTTP_CODE_UPSTREAM_UNAVAILABLE, "no valid upstream node: " .. (err or "nil")
    249         end
  >>  250         core.log.warn("upstream.lua return nodes:",core.json.delay_encode(new_nodes,true))    ---  here is the log I add 
    251         local same = upstream_util.compare_upstream_node(up_conf, new_nodes)
    252         if not same then

and  when I make  a call  , the log will tell me  that is  two  node ,they are all like each other.   here is the log: 

2021/12/16 10:46:54 [warn] 24648#24648: *39459760 [lua] upstream.lua:250: set_upstream(): upstream.lua return nodes:[{"weight":1,"host":"172.16.11.13","port":8086},{"weight":1,"host":"172.16.11.13","port":8086}], client: 127.0.0.1, server: _, request: "GET /demo1026-13/index HTTP/1.1", host: "local.xsapp.org"

------- here is my route config:
{
  "uri": "/demo1026-13/*",
  "name": "测试nacos-13",
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "^/demo1026-13/(.*)",
        "/${1}"
      ]
    }
  },
  "upstream": {
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "discovery_type": "nacos",
    "pass_host": "pass",
    "service_name": "demo1026"
  },
  "status": 1
}

---- here is my call 
curl -i -X GET  http://127.0.0.1:9080/demo1026-13/index     -H "api-key-auth: key-of-sam"

I have config only route  and upstream, so,   that is tow duplicates. 
If I config a service too, that will be  three duplicates.

**Comment by xianshun163** [comment]
> > from the log , that is 3 instance in the apisix, but that is one in the nacos.
> 
> I don't really understand this. how did you determine that there were three instances? AFAIK, it is possible that the logs are output by different workers.
> 
> pls provide some more information.

It is like the message  above .

**Comment by tzssangglass** [comment]
do the following request to your nacos and what do you get

```
curl -X GET '127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=true&serviceName= demo1026'
```

**Comment by xianshun163** [comment]
> ```
> curl -X GET '127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=demo1026'
> ```

[root@k8s_test1 ~]# curl -X GET '127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=demo1026'
{"name":"DEFAULT_GROUP@@demo1026","groupName":"DEFAULT_GROUP","clusters":"","cacheMillis":10000,"hosts":[{"instanceId":"172.16.11.13#8086#DEFAULT#DEFAULT_GROUP@@demo1026","ip":"172.16.11.13","port":8086,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@demo1026","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}],"lastRefTime":1640069415699,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true}

**Comment by tzssangglass** [comment]
ok, I will check soon.

**Comment by tzssangglass** [comment]
As I had difficulty setting up a nacos environment to simulate this test (which took me a long time), I opted to hack my way through it.

here's how I hack

```diff
diff --git a/apisix/discovery/nacos/init.lua b/apisix/discovery/nacos/init.lua
index d163b395..8e1f71da 100644
--- a/apisix/discovery/nacos/init.lua
+++ b/apisix/discovery/nacos/init.lua
@@ -104,7 +104,10 @@ end
 
 
 local function get_url(request_uri, path)
-    return request(request_uri, path, nil, 'GET', nil)
+    local json = [[{"name":"DEFAULT_GROUP@@demo1026","groupName":"DEFAULT_GROUP","clusters":"","cacheMillis":10000,"hosts":[{"instanceId":"172.16.11.13#8086#DEFAULT#DEFAULT_GROUP@@demo1026","ip":"127.0.0.1","port":8080,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@demo1026","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}],"lastRefTime":1640069415699,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true}]]
+    local data = core.json.decode(json)
+    return data
+    --return request(request_uri, path, nil, 'GET', nil)
 end
 
 
diff --git a/apisix/upstream.lua b/apisix/upstream.lua
index 4e23fbff..992b218c 100644
--- a/apisix/upstream.lua
+++ b/apisix/upstream.lua
@@ -248,6 +248,7 @@ function _M.set_by_route(route, api_ctx)
             return HTTP_CODE_UPSTREAM_UNAVAILABLE, "no valid upstream node: " .. (err or "nil")
         end
 
+        core.log.warn("upstream.lua return nodes:",core.json.delay_encode(new_nodes,true))
         local same = upstream_util.compare_upstream_node(up_conf, new_nodes)
         if not same then
             local pass, err = core.schema.check(core.schema.discovery_nodes, new_nodes)
diff --git a/t/toolkit b/t/toolkit
index 94f471d3..ab2471cc 160000
--- a/t/toolkit
+++ b/t/toolkit
@@ -1 +1 @@
-Subproject commit 94f471d3a9045667bc1f1784a21f89315cd64f7e
+Subproject commit ab2471cc9cbeec6fe605120160eeb9dd17ddda2c
```

the error.log as

```
2021/12/22 14:43:12 [warn] 51278#8892400: *18 [lua] upstream.lua:251: set_upstream(): upstream.lua return nodes:[{"weight":1,"port":8080,"host":"127.0.0.1"}], client: 127.0.0.1, server: localhost, request: "GET /hello HTTP/1.1", host: "localhost"
```

my test case is 

```
use t::APISIX 'no_plan';

repeat_each(1);
log_level('info');
no_root_location();
no_shuffle();
workers(4);

our $yaml_config = <<_EOC_;
apisix:
  node_listen: 1984
  config_center: yaml
  enable_admin: false
discovery:
  nacos:
      host:
        - "http://127.0.0.1:8848"
      prefix: "/nacos/v1/"
      fetch_interval: 1
      weight: 1
      timeout:
        connect: 2000
        send: 2000
        read: 5000

_EOC_

our $yaml_auth_config = <<_EOC_;
apisix:
  node_listen: 1984
  config_center: yaml
  enable_admin: false
discovery:
  nacos:
      host:
        - "http://nacos:nacos\@127.0.0.1:8848"
      prefix: "/nacos/v1/"
      fetch_interval: 1
      weight: 1
      timeout:
        connect: 2000
        send: 2000
        read: 5000

_EOC_

run_tests();

__DATA__

=== TEST 1: get APISIX-NACOS info from NACOS - no auth
--- yaml_config eval: $::yaml_config
--- apisix_yaml
routes:
  -
    uri: /hello
    upstream:
      service_name: demo1026
      discovery_type: nacos
      type: roundrobin
#END
--- pipelined_requests eval
[
    "GET /hello",
    "GET /hello",
]
--- response_body_like eval
[
    qr/server [1-2]/,
    qr/server [1-2]/,
]
--- no_error_log
[error, error]
```

**Comment by tzssangglass** [comment]
Is there any way you can provide a reproducible environment? About nacos.

**Comment by xianshun163** [comment]
about deploy the nacos: 
1、I get  tar package from :https://github.com/alibaba/nacos/releases/tag/2.0.1
2、untar the  package  and  goto the  bin dir， and  run ： sh startup.sh -m standalone
3、The url is  ： http://IP:8848/nacos  

about a service the register to the nacos  as  a  provider, we can get a example from here:
https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example
https://github.com/alibaba/spring-cloud-alibaba/wiki/Nacos-discovery

**Comment by tzssangglass** [comment]
can you try with nacos 1.4.x , recently we found that the nacos 2.x version is not supported enough.

releated to: https://github.com/apache/apisix/pull/5894

**Comment by xianshun163** [comment]
can you tell me what is the problem with the nacos 2.x，except what I said above 。 
May be  I  have to try to fix  it， because  I have use the nacos 2.x  in the product,    In other respects  nacos 1.X is not stable enough。

**Comment by tzssangglass** [comment]
You can see the problem by looking at the PR above.

**Comment by xianshun163** [comment]
I have find   the relate nacos problem #5815 ,  and  it is using  spring cloud  grpc port .     I use the http port,

**Comment by tzssangglass** [comment]
I followed your way and could not reproduce.

Here are the steps I took to reproduce it

#### step 1

start Nacos 2.0.1 as satndalone(get from https://github.com/alibaba/nacos/releases/tag/2.0.1)

#### step 2

start [service provider](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-discovery-example/nacos-spring-cloud-provider-example) and register service to Nacos.

and test get service from Nacos

```shell
curl -X GET '127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=true&serviceName=service-provider'
{"name":"DEFAULT_GROUP@@service-provider","groupName":"DEFAULT_GROUP","clusters":"","cacheMillis":10000,"hosts":[{"instanceId":"192.168.2.43#8070#DEFAULT#DEFAULT_GROUP@@service-provider","ip":"192.168.2.43","port":8070,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@service-provider","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}],"lastRefTime":1640330295589,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true}
```

#### step 3

my route config is

```json
{
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "hash_on": "vars",
        "scheme": "http",
        "discovery_type": "nacos",
        "pass_host": "pass",
        "service_name": "service-provider"
    },
    "status": 1
}
```

my config.yaml is 

```yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
discovery:
  nacos:
    host:
      - "http://127.0.0.1:8848"
```

#### step 4


```diff
diff --git a/apisix/discovery/nacos/init.lua b/apisix/discovery/nacos/init.lua
index d163b395..9624349d 100644
--- a/apisix/discovery/nacos/init.lua
+++ b/apisix/discovery/nacos/init.lua
@@ -225,6 +225,7 @@ local function get_nacos_services()
     iter_and_add_service(services, values)
     values = get_services()
     iter_and_add_service(services, values)
+    ngx.log(ngx.WARN, "services : ", require("lualib.inspect")(services))
     return services
 end
 
diff --git a/apisix/upstream.lua b/apisix/upstream.lua
index 4e23fbff..47f83e1b 100644
--- a/apisix/upstream.lua
+++ b/apisix/upstream.lua
@@ -244,6 +244,7 @@ function _M.set_by_route(route, api_ctx)
         end
 
         local new_nodes, err = dis.nodes(up_conf.service_name, up_conf.discovery_args)
+        ngx.log(ngx.WARN, "new_nodes : ", require("lualib.inspect")(new_nodes))
         if not new_nodes then
             return HTTP_CODE_UPSTREAM_UNAVAILABLE, "no valid upstream node: " .. (err or "nil")
         end
diff --git a/conf/config.yaml b/conf/config.yaml
index 421ac091..8e5d7764 100644
--- a/conf/config.yaml
+++ b/conf/config.yaml
@@ -45,3 +45,7 @@ apisix:
     - name: admin
       key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
       role: admin
+discovery:
+  nacos:
+    host:
+      - "http://127.0.0.1:8848"
```


and my error.log is

```
2021/12/24 15:14:29 [warn] 20348#10949645: *19 [lua] init.lua:228: get_nacos_services(): services : { {
    group_name = "DEFAULT_GROUP",
    namespace_id = "public",
    service_name = "service-provider"
  } }, context: ngx.timer
2021/12/24 15:14:29 [warn] 20359#10949656: *13 [lua] plugin.lua:222: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: init_worker_by_lua*
2021/12/24 15:14:29 [warn] 20350#10949647: *2 [lua] plugin.lua:222: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: init_worker_by_lua*
2021/12/24 15:14:29 [warn] 20351#10949648: *4 [lua] plugin.lua:222: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: init_worker_by_lua*
2021/12/24 15:14:30 [warn] 20348#10949645: *637 [lua] upstream.lua:247: set_upstream(): new_nodes : { {
    host = "192.168.2.43",
    port = 8070,
    weight = 1
  } }, client: 127.0.0.1, server: _, request: "GET /echo/hello HTTP/1.1", host: "127.0.0.1:9080"
```

I didn't reproduce the bug you mentioned, is there any difference between our previous steps?

Note: I used https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-discovery-example/nacos-spring-cloud-provider-example as java service to register to Nacos.

**Comment by xianshun163** [comment]
yes, you  only config a  route,   you can config a upstream  ,and a services,  use the discovery type of nacos.

**Comment by tzssangglass** [comment]
> yes, you only config a route, you can config a upstream ,and a services, use the discovery type of nacos.

show your configuration of route, service and upstream.

and I used the discovery type of nacos. see step 3.

**Comment by xianshun163** [comment]
the upstream config like this :
{
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "discovery_type": "nacos",
  "pass_host": "pass",
  "name": "arch.test.nacos",
  "service_name": "demo1026",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}

and the  service config like this:
{
  "name": "arch.test.nacos",
  "upstream": {
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "discovery_type": "nacos",
    "pass_host": "pass",
    "service_name": "demo1026",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  }
}

**Comment by tzssangglass** [comment]
After  checked, I found that this is a bug. 

As I mentioned above, add the service configuration as follows

```
{
    "name": "arch.test.nacos",
    "upstream": {
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "discovery_type": "nacos",
        "pass_host": "pass",
        "service_name": "service-provider",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    }
}
```


add  the upstream configuration as follows

```
{
    "timeout": {
        "connect": 6,
        "send": 6,
        "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "discovery_type": "nacos",
    "pass_host": "pass",
    "name": "arch.test.nacos",
    "service_name": "service-provider",
    "keepalive_pool": {
        "idle_timeout": 60,
        "requests": 1000,
        "size": 320
    }
}
```

We should note that the service itself does not have a `service_name` attribute.

my error.log is 


```
2021/12/28 18:10:29 [warn] 695#14133352: *20589 [lua] upstream.lua:251: set_upstream(): new_nodes : { {
    host = "192.168.2.43",
    port = 8070,
    weight = 1
  }, {
    host = "192.168.2.43",
    port = 8070,
    weight = 1
  }, {
    host = "192.168.2.43",
    port = 8070,
    weight = 1
  } }, client: 127.0.0.1, server: _, request: "GET /echo/hello HTTP/1.1", host: "127.0.0.1:9080"
```

**Comment by tzssangglass** [comment]
hi @xianshun163 would you like to submit a PR to fix it?

**Comment by xianshun163** [comment]
> 



> hi @xianshun163 would you like to submit a PR to fix it?

OK, I will  do  it. If you have any official guidelines, can you send them to me? I haven't submitted them in GitHub. Or I'll find it myself.

**Comment by tzssangglass** [comment]
here: https://apisix.apache.org/docs/general/contributor-guide/

If you have questions, you can call me in this issue.

**Comment by juzhiyuan** [comment]
@xianshun163 kindly let us know if you encounter problems when submitting PRs.

**Comment by xianshun163** [comment]
ok,  I will try it soon. thanks

**Comment by xianshun163** [comment]
@tzssangglass , @juzhiyuan   hi, I have found that, some one have commit some code about nacos, into the master branch: 
init.lua feat(nacos): support grpc java (#5894)12 days ago
schema.lua   feat(discovery): check schema before starting (#5629)

in the branch release/2.11.0  ,only have one code file :  nacos.lua

I want to confirm ,  if I  base  the master branch  to  submmit the code?

**Comment by juzhiyuan** [comment]
AFAIK, you need to check if this issue still occurred in the master branch, if yes, you need to push codes to the master branch, and cherry-pick code to the LTS branch. cc @tzssangglass

**Comment by tzssangglass** [comment]
> AFAIK, you need to check if this issue still occurred in the master branch, if yes, you need to push codes to the master branch, and cherry-pick code to the LTS branch. cc @tzssangglass

yes. let's start by committing the code to the master branch.

**Comment by xianshun163** [comment]
@tzssangglass @juzhiyuan  ,Dear friends, I have submit a pr, as the above link.But  it  seems have some problem, do you know  what have I to do next?

**Comment by juzhiyuan** [comment]
Hi @xianshun163, that's because it's your first PR for this repo. Once you have at least 1 PR gets merged, the further PR will no longer need approve :)

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/6282
