### ISSUE TITLE
request help:  stream-proxy as mysql proxy not work

### ISSUE THREAD

**Issue by yunfhu** [apache/apisix#5775]
### Issue description

I checked the route config, found auto filled the schema with "http",is that lead to the proxy not work?

#### apisix config.yaml

> apisix:
>   node_listen: 9080              # APISIX listening port
>   enable_control: true
>   stream_proxy: # TCP/UDP proxy
>     only: false
>     tcp: # TCP proxy address list
>       - 9100
>       # - "127.0.0.1:9100"
>     # udp: # UDP proxy address list
>     #   - 9200
>     #   # - "127.0.0.1:9211"
####  stream_routes information
> curl http://127.0.0.1:30080/apisix/admin/stream_routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X GET  | python -mjson.tool
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   399    0   399    0     0  57000      0 --:--:-- --:--:-- --:--:-- 57000
> {
>     "action": "get",
>     "count": 1,
>     "node": {
>         "dir": true,
>         "key": "/apisix/stream_routes",
>         "nodes": [
>             {
>                 "createdIndex": 21164,
>                 "key": "/apisix/stream_routes/1",
>                 "modifiedIndex": 21164,
>                 "value": {
>                     "create_time": 1639291584,
>                     "id": "1",
>                     "server_addr": "10.1.2.177",
>                     "server_port": 9100,
>                     "update_time": 1639291584,
>                     "upstream": {
>                         "hash_on": "vars",
>                         "nodes": {
>                             "10.1.2.171:3306": 1
>                         },
>                         "pass_host": "pass",
>                         "scheme": "http",
>                         "type": "roundrobin"
>                     }
>                 }
>             }
>         ]
>     }
> }

**Comment by yunfhu** [comment]
inside the apisix pod,I use the telnet command to check the stream proxy route, it shows ok

```
@MacBook-Pro APISIX % kubectl exec -it apisix-557f5f646f-r69z9 sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
sh-4.2# telnet localhost 9100
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
J
5.7.36@1->t-::kmLEXU'7Lmysql_native_passwordConne
```
but when I use the nodeport to test proxy function, the connection was closed

```
@MacBook-Pro ~ % telnet localhost 30100
Trying ::1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```
and here is the service information:

```
NAMESPACE     NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                          AGE
default       apisix       NodePort    10.111.193.248   <none>        9080:30080/TCP,9100:30100/TCP    39m
```

**Comment by spacewander** [comment]
@bisakhmondal 
Could you check if MySQL can be proxied via APISIX? Thanks!

**Comment by yunfhu** [comment]
> @bisakhmondal
> Could you check if MySQL can be proxied via APISIX? Thanks!
pls read previous comments which described very clearly

**Comment by bisakhmondal** [comment]
Hi @yunfhu, thanks for the detailed analysis
 
> login apisix pod with kubectl exec command,I use the telnet command to check the stream proxy route, it shows able route to mysql host
> 
> ```
> @MacBook-Pro APISIX % kubectl exec -it apisix-557f5f646f-r69z9 sh
> kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
> sh-4.2# telnet localhost 9100
> Trying 127.0.0.1...
> Connected to localhost.
> Escape character is '^]'.
> J
> 5.7.36@1->t-::kmLEXU'7Lmysql_native_password
> ```

Yes, I also have tested locally, there is no issue from the APISIX side while proxying the request to the MySQL server with the correct route configuration. 

> but when I logout the pod and tried to request with the node port, the connection was closed
> 
> ```
> @MacBook-Pro ~ % telnet localhost 30100
> Trying ::1...
> Connected to localhost.
> Escape character is '^]'.
> Connection closed by foreign host.
> ```

Got your point. 
>"value": {
"create_time": 1639291584,
"id": "1",
"server_addr": "10.1.2.177",
"server_port": 9100,
"update_time": 1639291584,
"upstream": {
"hash_on": "vars",
"nodes": {
"10.1.2.171:3306": 1
},
"pass_host": "pass",
"scheme": "http",
"type": "roundrobin"
}

Just curious why do you have `server_addr` filter enabled for port `10.1.2.177` while from the kubectl I can see your APISIX server is running on `10.1.2.186`. (see [here](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_server_addr))

Could you please check if you can access the mysql through the k8s nodeport for this stream route config: 
```json
{
    "upstream": {
        "nodes": {
            "10.1.2.171:3306": 1
        },
        "type": "roundrobin"
    }
}
```
assuming you can access the mysql at `10.1.2.171:3306`. Thanks.

**Comment by yunfhu** [comment]
@bisakhmondal thanks for your advice, the access works now

**Comment by bisakhmondal** [comment]
@yunfhu Glad, it worked. You can also take a look at the documentation added at #5783
Have a nice day!
