### ISSUE TITLE
request help: hmac-auth how to resist replay attacks

### ISSUE THREAD

**Issue by qq54903099** [apache/apisix#5784]
### Issue description

how to use hmac-auth plugin to resist replay attacks.

### Environment

- apisix version (cmd: `apisix version`): 2.10.2
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@qq54903099 Could you give more details?

**Comment by qq54903099** [comment]
> @qq54903099 Could you give more details?

https://www.jianshu.com/p/ee2b88364664

like parameter nonce

**Comment by spacewander** [comment]
@bisakhmondal 
Yes, you are right. 👍

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
