### ISSUE TITLE
request help: add offline installation for `how-to-build.md`

### ISSUE THREAD

**Issue by leslie-tsang** [apache/apisix#5785]
### Issue description

Currently, the installation docs of Apache APISIX doesn't mention the offline installation scenarios, which is common in the enterprise.

## Solution
add a offline installation demo in [how-to-build.md](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md)
```shell
## download APISIX offline RPM packages via YUM to `./apisix` folder
mkdir -p apisix
yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
yum clean all && yum makecache
yum install -y --downloadonly --downloaddir=./apisix apisix
```
> copy `./apisix` folder to target host
```shell
## install APISIX via RPM
yum install ./apisix/*.rpm
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by 123liubao** [comment]
I want to work on this, please assign it to me.

**Comment by tokers** [comment]
> I want to work on this, please assign it to me.

@123liubao Assigned.
