### ISSUE TITLE
request help: Custom plugin reload but unknown plugin

### ISSUE THREAD

**Issue by zjzwjcbj** [apache/apisix#5791]
### Issue description

I add a custom plugin and reload.But find unknown plugin.(Installed by Helm)
![image](https://user-images.githubusercontent.com/26433840/145916733-5a0725d9-2441-4c7f-af9a-bc72aea168c5.png)

![image](https://user-images.githubusercontent.com/26433840/145916806-87c50d3a-3d30-412a-8706-bd8efed4cc61.png)

![image](https://user-images.githubusercontent.com/26433840/145916857-a92cd052-06a0-43d0-893f-d890ad2fc042.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4.16
- apisix-dashboard version, if have:2.9.0
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
looks like it has something to do with your plugin code

**Comment by zjzwjcbj** [comment]
> looks like it has something to do with your plugin code
an example
![image](https://user-images.githubusercontent.com/26433840/145923767-a73d0f63-4bfb-4f38-9c29-e524a39c2e53.png)

**Comment by Baoyuantop** [comment]
It looks like your plugin is not loaded correctly by APISIX, you can get some information in the `error.log` of APISIX.

**Comment by zjzwjcbj** [comment]
> It looks like your plugin is not loaded correctly by APISIX, you can get some information in the `error.log` of APISIX.

but no error log and I found cannot add 'server-info' plugin
![image](https://user-images.githubusercontent.com/26433840/145927611-bb8fd38a-042d-4315-94bb-6a3bd659a3f3.png)

**Comment by tzssangglass** [comment]
`apisix/plugins` dir should has the plugin file, and plugin file name should same as `plugin_name`. 

> but no error log and I found cannot add 'server-info' plugin

can you use PUT method to try?

**Comment by zjzwjcbj** [comment]
> `apisix/plugins` dir should has the plugin file, and plugin file name should same as `plugin_name`.
> 
> > but no error log and I found cannot add 'server-info' plugin
> 
> can you use PUT method to try?

same
![image](https://user-images.githubusercontent.com/26433840/145940062-33e605f7-6f05-4ad9-b512-552d3260b156.png)

**Comment by zjzwjcbj** [comment]
when I reload 

> > `apisix/plugins` dir should has the plugin file, and plugin file name should same as `plugin_name`.
> > > but no error log and I found cannot add 'server-info' plugin
> > 
> > 
> > can you use PUT method to try?
> 
> same ![image](https://user-images.githubusercontent.com/26433840/145940062-33e605f7-6f05-4ad9-b512-552d3260b156.png)

![image](https://user-images.githubusercontent.com/26433840/145940607-dec3c571-7f05-4e0c-b5ff-7b6349e29338.png)

and in config-default.yaml
![image](https://user-images.githubusercontent.com/26433840/145940773-131fb04f-5e88-41d0-a265-6c6ed50ce026.png)

**when I reload, the log:**

2021/12/14 05:46:08 [warn] 163#163: *9181384 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, client: 127.0.0.1, server: , request: "PUT /apisix/admin/plugins/reload HTTP/1.1", host: "127.0.0.1:9180"
2021/12/14 05:46:08 [warn] 167#167: *9181386 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 169#169: *9181387 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 163#163: *9181384 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, client: 127.0.0.1, server: , request: "PUT /apisix/admin/plugins/reload HTTP/1.1", host: "127.0.0.1:9180"
2021/12/14 05:46:08 [warn] 169#169: *9181387 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 167#167: *9181386 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 165#165: *9181385 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 166#166: *9181391 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 165#165: *9181385 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 166#166: *9181391 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 171#171: *9181398 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 168#168: *9181404 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 171#171: *9181398 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 168#168: *9181404 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 164#164: *9181419 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 164#164: *9181419 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 162#162: *9181433 [lua] plugin.lua:151: load(): new plugins: {"ip-restriction":true,"batch-requests":true,"authz-keycloak":true,"limit-req":true,"fault-injection":true,"prometheus":true,"uri-blocker":true,"jwt-auth":true,"key-auth":true,"tcp-logger":true,"sls-logger":true,"request-validation":true,"basic-auth":true,"node-status":true,"http-logger":true,"gzip":true,"ua-restriction":true,"udp-logger":true,"referer-restriction":true,"traffic-split":true,"kafka-logger":true,"real-ip":true,"authz-casbin":true,"limit-count":true,"openid-connect":true,"cors":true,"zipkin":true,"wolf-rbac":true,"proxy-rewrite":true,"echo":true,"proxy-cache":true,"syslog":true,"serverless-pre-function":true,"hmac-auth":true,"grpc-transcode":true,"consumer-restriction":true,"api-breaker":true,"redirect":true,"proxy-mirror":true,"limit-conn":true,"response-rewrite":true,"request-id":true,"serverless-post-function":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 162#162: *9181433 [lua] plugin.lua:192: load_stream(): new plugins: {"ip-restriction":true,"mqtt-proxy":true,"limit-conn":true}, context: ngx.timer
2021/12/14 05:46:08 [warn] 162#162: *9181433 [lua] init.lua:359: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer
127.0.0.1 - - [14/Dec/2021:05:46:08 +0000] 127.0.0.1:9180 "PUT /apisix/admin/plugins/reload HTTP/1.1" 200 14 0.000 "-" "curl/7.79.1" -- - "http://127.0.0.1:9180"

**Comment by tzssangglass** [comment]
can you show the `third-party` plugin' code as text, let me check it.

**Comment by zjzwjcbj** [comment]
> can you show the `third-party` plugin' code as text, let me check it.

local core = require("apisix.core")
local plugin_name = "third-plugin"
local schema = {
    type = "object",
    properties = {
        content = {
            type = "string" }
    }
}

local _M = {
    version = 0.2,
    priority = 5000,
    name = plugin_name,
    schema = schema,
}

function _M.access(conf, ctx)
    core.log.warn("test--------")
    core.log.warn(conf.content)
end

return _M

**Comment by zjzwjcbj** [comment]
> can you show the `third-party` plugin' code as text, let me check it.



> > can you show the `third-party` plugin' code as text, let me check it.
> 
> local core = require("apisix.core") local plugin_name = "third-plugin" local schema = { type = "object", properties = { content = { type = "string" } } }
> 
> local _M = { version = 0.2, priority = 5000, name = plugin_name, schema = schema, }
> 
> function _M.access(conf, ctx) core.log.warn("test--------") core.log.warn(conf.content) end
> 
> return _M



> can you show the `third-party` plugin' code as text, let me check it.

The code should be ok.I changed the 'key-auth.lua' plugin with this code and it worked.
![image](https://user-images.githubusercontent.com/26433840/146105733-e5656ea3-ba2b-4330-96ea-08f4ab81fbd2.png)

**Comment by tzssangglass** [comment]
I cannot reproduce it.

```
$ ls apisix/plugins/third-plugin.lua
apisix/plugins/third-plugin.lua
```

here is my log, you can see that plugin is in used.
```
2021/12/15 09:27:40 [warn] 88794#3201972: *35259 [lua] third-plugin.lua:19: phase_func(): test--------, client: 127.0.0.1, server: _, request: "GET /get HTTP/1.1", host: "127.0.0.1:9080"
2021/12/15 09:27:40 [warn] 88794#3201972: *35259 [lua] third-plugin.lua:20: phase_func(): nil, client: 127.0.0.1, server: _, request: "GET /get HTTP/1.1", host: "127.0.0.1:9080"
```

**Comment by tzssangglass** [comment]
You can check if the plugin file exists in the `apisix/plugins/` directory and the permissions of the file.

**Comment by zjzwjcbj** [comment]
And  I change the

> You can check if the plugin file exists in the `apisix/plugins/` directory and the permissions of the file.
Seem no difference 
![image](https://user-images.githubusercontent.com/26433840/146106683-a55c76fa-d00b-4dd2-9e74-b20a51b15c88.png)

**Comment by zjzwjcbj** [comment]
> You can check if the plugin file exists in the `apisix/plugins/` directory and the permissions of the file.

Can it be the version problem
![image](https://user-images.githubusercontent.com/26433840/146106823-797c209e-7413-4992-a726-aebbbf83b134.png)

**Comment by zjzwjcbj** [comment]
> > You can check if the plugin file exists in the `apisix/plugins/` directory and the permissions of the file.
> 
> Can it be the version problem？ ![image](https://user-images.githubusercontent.com/26433840/146106823-797c209e-7413-4992-a726-aebbbf83b134.png)

I  change the config-default.yaml  and the config.yaml is not changed.  Is it right?
![image](https://user-images.githubusercontent.com/26433840/146107651-0160b750-964b-49b7-a789-3a30d23361a5.png)

**Comment by tzssangglass** [comment]
my version is 2.10.2, I don't think it's a version problem.

**Comment by tzssangglass** [comment]
> I change the config-default.yaml and the config.yaml is not changed. Is it right?

no, we should not change `config-default.yaml`.

**Comment by zjzwjcbj** [comment]
I use /apisix/admin/plugins/third-plugin   can find
![image](https://user-images.githubusercontent.com/26433840/146108252-03cf97df-2e78-468a-8721-6776a24b022a.png)

**Comment by tzssangglass** [comment]
I'm not familiar with k8s deployments. @tokers do you have any idea?

**Comment by tokers** [comment]
> I'm not familiar with k8s deployments. @tokers do you have any idea?

It's not related to the version, make sure whether the confit.yaml is mounted to the pod and contains such plugin.

**Comment by zjzwjcbj** [comment]
> > I'm not familiar with k8s deployments. @tokers do you have any idea?
> 
> It's not related to the version, make sure whether the confit.yaml is mounted to the pod and contains such plugin.

The config.yaml not contains this plugin and the config.yaml cannot change.
![image](https://user-images.githubusercontent.com/26433840/146175233-70596006-eb5e-49ea-b0c2-4541e3114b09.png)

**Comment by tokers** [comment]
> > > I'm not familiar with k8s deployments. @tokers do you have any idea?
> 
> > 
> 
> > It's not related to the version, make sure whether the confit.yaml is mounted to the pod and contains such plugin.
> 
> 
> 
> The config.yaml not contain this plugin and the config.yaml cannot change. (Even if  I change the config-dafault.yaml)
> 
> ![image](https://user-images.githubusercontent.com/26433840/146175233-70596006-eb5e-49ea-b0c2-4541e3114b09.png)
> 
> 

try to check out the apisix-helm-chart repo and mount this 3rd plugin, instead of changing it by yourself.

**Comment by zjzwjcbj** [comment]
> > > > I'm not familiar with k8s deployments. @tokers do you have any idea?
> > 
> > 
> > > 
> > 
> > 
> > > It's not related to the version, make sure whether the confit.yaml is mounted to the pod and contains such plugin.
> > 
> > 
> > The config.yaml not contain this plugin and the config.yaml cannot change. (Even if  I change the config-dafault.yaml)
> > ![image](https://user-images.githubusercontent.com/26433840/146175233-70596006-eb5e-49ea-b0c2-4541e3114b09.png)
> 
> try to check out the apisix-helm-chart repo and mount this 3rd plugin, instead of changing it by yourself.

I can't understand. Can you elaborate more?

**Comment by tokers** [comment]
See https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/README.md, and you check focus on the configurations about `apisix.customPlugins`.

**Comment by zjzwjcbj** [comment]
> See https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/README.md, and you check focus on the configurations about `apisix.customPlugins`.

Like this ?
helm install apisix apisix/apisix  --set gateway.type=NodePort --set admin.allow.ipList="{0.0.0.0/0}" --set apisix.customPlugins.enabled=true --set apisix.customPlugins.luaPath="/opt/apisix/custom_plugin/third-plugin.lua" --set apisix.customPlugins.plugins.name="third-plugin" -n apisix

**Comment by zjzwjcbj** [comment]
> See https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/README.md, and you check focus on the configurations about `apisix.customPlugins`.

Can I use like this? Add parameters on helm install.
helm install apisix apisix/apisix   --set apisix.customPlugins.enabled=true --set apisix.customPlugins.luaPath="/opt/apisix/custom_plugin/?.lua"

**Comment by zjzwjcbj** [comment]
> See https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/README.md, and you check focus on the configurations about `apisix.customPlugins`.

I add the plugin in plugins in values.yaml  It worked.Thanks a lot

**Comment by tzssangglass** [comment]
consideras solved, feel free to reope if you have problem about this.
