### ISSUE TITLE
request help: Apisix proxy static resource ? (针对#4889 问题的讨论)

### ISSUE THREAD

**Issue by guoweia** [apache/apisix#5792]
### Issue description

之前有一个issue被关掉了（#4889 ），无法继续讨论。
有两种方式实现这个需求，但是都不完美：
1.在nginx中增加配置，就是上一个issue提到的https://apisix.apache.org/docs/apisix/customize-nginx-configuration，这样的缺点是放弃了apisix对静态资源的管控，比如灰度发布场景，就无法实现；
2.增加一个nginx承接静态资源情况，这种方式的缺点是需要增加部署，增加网络消耗和静态资源服务器；
如果技术上可行，希望apisix能够原生支持静态资源的处理，解决上面两个方案的不足。

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi @guoweia,

> 之前有一个issue被关掉了（#4889 ），无法继续讨论。

This issue is closed by its author, maybe the author thought https://github.com/apache/apisix/issues/4889#issuecomment-905161689 has resolved the issue?

AFAIK, Apache APISIX is more focused on Microservices management, not sure if it's suitable to support more powerful Static Files 🤔 

Let's seek help from @leslie-tsang @tzssangglass 😄

**Comment by guoweia** [comment]
> Hi @guoweia,
> 
> > 之前有一个issue被关掉了（#4889 ），无法继续讨论。
> 
> This issue is closed by its author, maybe the author thought [#4889 (comment)](https://github.com/apache/apisix/issues/4889#issuecomment-905161689) has resolved the issue?
> 
> AFAIK, Apache APISIX is more focused on Microservices management, not sure if it's suitable to support more powerful Static Files 🤔
> 
> Let's seek help from @leslie-tsang @tzssangglass 😄

I discussed this scenario a long time ago. I found that it is mentioned every week in the QQ group. From the perspective of the market, it is recommended to consider it.

**Comment by juzhiyuan** [comment]
>  I found that it is mentioned every week in the QQ group. From the perspective of the market, it is recommended to consider it.

Get it, will wait for more thoughts from community.

**Comment by juzhiyuan** [comment]
BTW, we will have an online meeting tomorrow, see https://github.com/apache/apisix/discussions/5786 for more information. Welcome to join in.
