### ISSUE TITLE
Feature request : install_dependencies support install etcd separately

### ISSUE THREAD

**Issue by zaunist** [apache/apisix#5795]
### Issue description

Sometimes, we just need install etcd, ref [here](https://github.com/apache/apisix/pull/5718#discussion_r768255311). But install_dependencies.sh not support this feature, it will install all dependencies of APISIX. Should we support install etcd separately in install_dependencies.sh ? 

example:
```
bash install_dependencies.sh etcd
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
LGTM
