### ISSUE TITLE
request help: what is the meaning of  allowlist in ua-restriction?  

### ISSUE THREAD

**Issue by shoulda** [apache/apisix#5797]
### Issue description

request's user-agent  not in allowlist   also can suceess? is it right?

=== TEST 14: hit route and user-agent not in allowlist
--- request
GET /hello
--- more_headers
User-Agent:foo/bar
--- error_code: 200
--- response_body
hello world

**Comment by leslie-tsang** [comment]
I'm afraid the answer is yes, `ua-restriction` [test case 14](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/t/plugin/ua-restriction.t#L300-L307) work as expected, Ref to [ua-restriction code block](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/apisix/plugins/ua-restriction.lua#L94-L121)

**Comment by shoulda** [comment]
OK，according to the ua-restriction match_user_agent code block,it is ok; i am confuse of the meaning of allowlist, the function of allowlist just filters denylist?

**Comment by leslie-tsang** [comment]
Admittedly, the way `ua-restriction' works a bit counter-intuitive to human intuition.
> After reading the code of `ua-restriction`, there are some scenarios where this feature is really needed.

Image a scenario that you need to make sure only the target client can access the API in a LAN like `192.168.1.0/24`
Then you can add a CIDR to denylist, such as `192.168.1.0/24`, and `192.168.1.100` to the allow list.

**Comment by shoulda** [comment]
ok,thanks

**Comment by leslie-tsang** [comment]
@juzhiyuan @shoulda Consider solved. Feel free to reopen it if need.

**Comment by juzhiyuan** [comment]
ok
