### ISSUE TITLE
bug: the presence of plugin information is overwritten when generating the schema.json file

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#5798]
### Issue description

When adding a custom plugin or modifying the schema of the plugin, the schema file is generated through the `127.0.0.1:9090/v1/schema` interface, but it is found that the http plugin and stream plugin information are overwritten by each other

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.  add `test_mode = {type = "boolean",default = false,}` to the schema configuration file of the plugin limit-conn
2. curl 127.0.0.1:9090/v1/schema > schema.json
3. It can be found that the configuration does not exist in the schema.json file

### Actual result

code: https://github.com/apache/apisix/blob/master/apisix/plugin.lua#L582-L599
![image](https://user-images.githubusercontent.com/17425270/145956706-d3f02ac9-3f16-463b-8732-ffdee72531ae.png)
![image](https://user-images.githubusercontent.com/17425270/145956755-b68386c4-fc93-45c4-b34f-9e30d002a83c.png)

### Error log

none

**Comment by spacewander** [comment]
> add test_mode = {type = "boolean",default = false,} to the schema configuration file of the plugin limit-conn

There are two limit-conn plugins:
https://github.com/apache/apisix/blob/master/apisix/plugins/limit-conn.lua
https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua

Which plugin do you add the field to?

**Comment by zuiyangqingzhou** [comment]
> > add test_mode = {type = "boolean",default = false,} to the schema configuration file of the plugin limit-conn
> 
> There are two limit-conn plugins: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-conn.lua https://github.com/apache/apisix/blob/master/apisix/stream/plugins/limit-conn.lua
> 
> Which plugin do you add the field to?

this one: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-conn.lua

export via `127.0.0.1:9090/v1/schema` will be overwritten by stream limit-conn

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/4947
