### ISSUE TITLE
request help: install issue

### ISSUE THREAD

**Issue by laughingyear** [apache/apisix#5799]
### Issue description

![image](https://user-images.githubusercontent.com/86775317/145970037-1efe8ac0-9789-41e4-a837-27a87fea7b7d.png)
真的可以用吗

### Environment
apisix version
lua ./apisix/cli/apisix.lua version
lua: error loading module 'ssl.core' from file '/root/apisix-2.11.0/deps/lib/lua/5.1/ssl.so':
/root/apisix-2.11.0/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list

uname -a
Linux VM-166-181-centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

openresty -V
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC)
built with OpenSSL 1.0.2k-fips 26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module

luarocks --version
lua: /usr/bin/luarocks:4: module 'luarocks.cfg' not found:
no field package.preload['luarocks.cfg']
no file './luarocks/cfg.lua'
no file '/usr/local/share/lua/5.1/luarocks/cfg.lua'
no file '/usr/local/share/lua/5.1/luarocks/cfg/init.lua'
no file '/usr/local/lib/lua/5.1/luarocks/cfg.lua'
no file '/usr/local/lib/lua/5.1/luarocks/cfg/init.lua'
no file './luarocks/cfg.so'
no file '/usr/local/lib/lua/5.1/luarocks/cfg.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './luarocks.so'
no file '/usr/local/lib/lua/5.1/luarocks.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
[C]: in function 'require'
/usr/bin/luarocks:4: in main chunk
[C]: ?

**Comment by tokers** [comment]
@bournefeng You can paste your problems here so that we can know how to help you.

**Comment by bournefeng** [comment]
> 

apisix version
lua ./apisix/cli/apisix.lua version
lua: error loading module 'ssl.core' from file '/root/apisix-2.11.0/deps/lib/lua/5.1/ssl.so':
        /root/apisix-2.11.0/deps/lib/lua/5.1/ssl.so: undefined symbol: SSL_CTX_set1_curves_list

uname -a 
Linux VM-166-181-centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux


openresty -V
nginx version: openresty/1.15.8.1
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.1rc1 --add-module=../echo-nginx-module-0.61 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.15 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.15 --add-module=../rds-csv-nginx-module-0.09 --add-module=../ngx_stream_lua-0.0.7 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_ssl_module


luarocks --version
lua: /usr/bin/luarocks:4: module 'luarocks.cfg' not found:
        no field package.preload['luarocks.cfg']
        no file './luarocks/cfg.lua'
        no file '/usr/local/share/lua/5.1/luarocks/cfg.lua'
        no file '/usr/local/share/lua/5.1/luarocks/cfg/init.lua'
        no file '/usr/local/lib/lua/5.1/luarocks/cfg.lua'
        no file '/usr/local/lib/lua/5.1/luarocks/cfg/init.lua'
        no file './luarocks/cfg.so'
        no file '/usr/local/lib/lua/5.1/luarocks/cfg.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './luarocks.so'
        no file '/usr/local/lib/lua/5.1/luarocks.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/bin/luarocks:4: in main chunk
        [C]: ?

**Comment by leslie-tsang** [comment]
Hello there, can you fill in the "Environment" section in the description ?

**Comment by bournefeng** [comment]
> Hi, @bournefeng . How do you install apisix ? Can you install dependencies before install apisix ? Here is the docs for guide install dependencies https://apisix.apache.org/docs/apisix/install-dependencies.

 curl https://raw.githubusercontent.com/apache/apisix/master/utils/install-dependencies.sh -sL | bash -
+ main
++ uname -s
++ tr '[:upper:]' '[:lower:]'
+ OS_NAME=linux
+ [[ linux == \l\i\n\u\x ]]
+ multi_distro_installation
+ grep -Eqi CentOS /etc/issue
+ grep -Eq CentOS /etc/centos-release /etc/os-release /etc/redhat-release /etc/system-release /etc/tlinux-release
+ install_dependencies_with_yum centos
+ sudo yum install yum-utils
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors-tlinux.tencentyun.com
 * epel: mirrors.tencent.com
 * extras: mirrors-tlinux.tencentyun.com
 * tlinux: mirrors-tlinux.tencentyun.com
 * updates: mirrors-tlinux.tencentyun.com
Package yum-utils-1.1.31-52.tl2.noarch already installed and latest version
Nothing to do
+ local 'common_dep=curl git gcc openresty-openssl111-devel unzip pcre pcre-devel openldap-devel'
+ '[' centos == centos ']'
+ sudo yum-config-manager --add-repo https://repos.apiseven.com/packages/centos/apache-apisix.repo
Loaded plugins: fastestmirror
adding repo from: https://repos.apiseven.com/packages/centos/apache-apisix.repo
grabbing file https://repos.apiseven.com/packages/centos/apache-apisix.repo to /etc/yum.repos.d/apache-apisix.repo
repo saved to /etc/yum.repos.d/apache-apisix.repo
+ sudo yum install -y apisix-base curl git gcc openresty-openssl111-devel unzip pcre pcre-devel openldap-devel
Loaded plugins: fastestmirror
https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



 One of the configured repositories failed (Apache APISIX Repository for CentOS),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=release ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable release
        or
            subscription-manager repos --disable=release

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=release.skip_if_unavailable=true

failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try.
https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

looks like repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml wrong

**Comment by laughingyear** [comment]
openresty -v
nginx version: openresty/1.15.8.1

luarocks --version
/usr/bin/luarocks 3.5.0

now I run:
apisix init

**Comment by juzhiyuan** [comment]
Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.

**Comment by tzssangglass** [comment]
same as https://github.com/apache/apisix/issues/4594

try with https://github.com/apache/apisix/issues/4594#issuecomment-879225419

**Comment by laughingyear** [comment]
> same as #4594
> 
> try with [#4594 (comment)](https://github.com/apache/apisix/issues/4594#issuecomment-879225419)

i try as follow:
"
You can try the following steps:

rm -rf /apisix-path/deps
Recompile and install luarocks and specify the luajit header file directory, for example: ./configure --with-lua-include=/openresty-path/luajit/include/luajit-2.1
Enter the apisix directory and re-execute make deps to install dependencies
"

when i rerun "make deps"
it shows:
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [deps] Error 1


should I reinstall openssl?

**Comment by juzhiyuan** [comment]
No idea what happened 🤣🤣 need @shuaijinchao's help.

**Comment by zaunist** [comment]
> > Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.
> 
> i follow this,it shows
> 
> failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try. https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

Hi, @laughingyear . Did you compile the kernel yourself? The version `2.2` looks like a customised kernel. If you use customised kernel, this guide may not be for you.

**Comment by laughingyear** [comment]
> > > Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.
> > 
> > 
> > i follow this,it shows
> > failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try. https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
> 
> Hi, @laughingyear . Did you compile the kernel yourself? The version `2.2` looks like a customised kernel. If you use customised kernel, this guide may not be suiteable for you.

is there some way i can install？

**Comment by zaunist** [comment]
> 

If you use customised kernel, you need install dependencies by your self. There is a shell script to install dependencies, you could refer [here](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/utils/install-dependencies.sh#L46)

**Comment by zaunist** [comment]
> > > > Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.
> > > 
> > > 
> > > i follow this,it shows
> > > failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try. https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
> > 
> > 
> > Hi, @laughingyear . Did you compile the kernel yourself? The version `2.2` looks like a customised kernel. If you use customised kernel, this guide may not be suiteable for you.
> 
> is there some way i can install？

If you use customised kernel, you need install dependencies by your self. There is a shell script to install dependencies, you could refer [here](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/utils/install-dependencies.sh#L46)

**Comment by laughingyear** [comment]
> > > > > Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.
> > > > 
> > > > 
> > > > i follow this,it shows
> > > > failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try. https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
> > > 
> > > 
> > > Hi, @laughingyear . Did you compile the kernel yourself? The version `2.2` looks like a customised kernel. If you use customised kernel, this guide may not be suiteable for you.
> > 
> > 
> > is there some way i can install？
> 
> If you use customised kernel, you need install dependencies by your self. There is a shell script to install dependencies, you could refer [here](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/utils/install-dependencies.sh#L46)

I change the apache-apisix.repo

chage baseurl from
baseurl=https://repos.apiseven.com/packages/centos/$releasever/$basearch

to 
baseurl=https://repos.apiseven.com/packages/centos/7/$basearch

then i reinstall apisix:
yum install apisix

it shows:

Error: Package: apisix-base-1.19.9.1.0-0.el7.x86_64 (release)
           Requires: openresty-openssl111 >= 1.1.1h-1
Error: Package: apisix-base-1.19.9.1.0-0.el7.x86_64 (release)
           Requires: openresty-zlib >= 1.2.11-3
Error: Package: apisix-base-1.19.9.1.0-0.el7.x86_64 (release)
           Requires: openresty-pcre >= 8.44-1

**Comment by laughingyear** [comment]
> > > > > Please follow this doc https://apisix.apache.org/docs/apisix/how-to-build to install Apache APISIX, thanks.
> > > > 
> > > > 
> > > > i follow this,it shows
> > > > failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try. https://repos.apiseven.com/packages/centos/2.2/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
> > > 
> > > 
> > > Hi, @laughingyear . Did you compile the kernel yourself? The version `2.2` looks like a customised kernel. If you use customised kernel, this guide may not be suiteable for you.
> > 
> > 
> > is there some way i can install？
> 
> If you use customised kernel, you need install dependencies by your self. There is a shell script to install dependencies, you could refer [here](https://github.com/apache/apisix/blob/936d9ac72b722b308a0a0dce01e0784a135d0cef/utils/install-dependencies.sh#L46)

i reinstall openresty

Installed:
  openresty.x86_64 0:1.19.9.1-1.el7                                                                                                                                                                                                   

Dependency Installed:
  openresty-openssl111.x86_64 0:1.1.1l-1.el7                                    openresty-pcre.x86_64 0:8.44-1.el7                                    openresty-zlib.x86_64 0:1.2.11-3.el7.centos                  

then i reinstall apisix
it shows:

Error: apisix-base conflicts with openresty-1.19.9.1-1.el7.x86_64
 You could try using --skip-broken to work around the problem
** Found 185 pre-existing rpmdb problem(s), 'yum check' output follows:

apisix-base conflicts with openresty-1.19.9.1-1.el7.x86_64

**Comment by leslie-tsang** [comment]
Hello there, @laughingyear , please try [this](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-offline-packagecentos-7). 
Do let me know if you need any help with it.

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.
