### ISSUE TITLE
request help: Data import problem

### ISSUE THREAD

**Issue by sunyu-2020** [apache/apisix#5813]
### Issue description

How to import apisix.yaml into etcd cluster

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
You mean start APISIX via `standalone mode` and then migrate the configuration in `apisix.yaml` to etcd cluster ?

**Comment by sunyu-2020** [comment]
Yes, is there a solution that has been implemented

**Comment by shuaijinchao** [comment]
Currently there is no support for importing standalone mode data into etcd.
