### ISSUE TITLE
bug: using nacos for service discovery, no support for spring cloud programs?

### ISSUE THREAD

**Issue by vcqr** [apache/apisix#5815]
### Issue description

[error] 47#47: *117481 upstream prematurely closed connection while reading response header from upstream

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

使用spring cloud grpc程序注册到nacos中，port在meta data中gRPC_port=xxxx

### Actual result

502 Bad Gateway
openresty

### Error log

[error] 47#47: *117481 upstream prematurely closed connection while reading response header from upstream, client: 172.18.0.1

**Comment by tzssangglass** [comment]
pls use English in public channel.

> upstream prematurely closed connection while reading response header from upstream,

I think it's a problem with your upstream service

**Comment by vcqr** [comment]
There will be two ports in the spring cloud program registration nacos, one is the port of the http service, the other is the port of grpc, but the port of grpc is registered in the metadata, the problem is that Apisix is not compatible to read the port in the metadata

**Comment by tzssangglass** [comment]
> but the port of grpc is registered in the metadata,

can we specify that the registered http port in the metadata?

**Comment by vcqr** [comment]
> 

No， The default method is used when registering

**Comment by tzssangglass** [comment]
you can go to the nacos community and ask if there is a configuration for this

**Comment by vcqr** [comment]
It is okay to call between spring cloud and use nacos to do service discovery, but apisix is not compatible

**Comment by tzssangglass** [comment]
APISIX now supports Nacos 1.x and the CI is based on Nacos 1.4.1, are you using Nacos 2.x?

**Comment by vcqr** [comment]
2.x   yes

**Comment by tzssangglass** [comment]
we need to support nacos 2.x, @vcqr would like to submit a PR to fix this?

**Comment by vcqr** [comment]
> we need to support nacos 2.x, @vcqr would like to submit a PR to fix this?

@tzssangglass ok

**Comment by xianshun163** [comment]
I am trying to use nacos too, and I use spring cloud http way.
ApiSix  cat use the port of the http service,    have  you find some problem with the http service?
