### ISSUE TITLE
request help: mac m1 make install  error cannot mkdir /usr/share/lua

### ISSUE THREAD

**Issue by zjzwjcbj** [apache/apisix#5817]
### Issue description

macos Big Sur. M1 .When make install ,shows cannot mkdir /usr/share/lua .  I have closed SIP .How can I do?

<img width="532" alt="截屏2021-12-15 上午9 55 51的副本" src="https://user-images.githubusercontent.com/26433840/146130503-52afa4e6-c005-4c24-9864-d84b33955929.png">

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
Strange, it this directory mounted separately?

**Comment by zjzwjcbj** [comment]
> Strange, is this directory mounted separately?
This directory cannot mount.  Even if I edit /etc/synthetic.conf

**Comment by xuminwlt** [comment]
It is not the problem of M1, but also the permissions of MAC system to system path.see "macos sip".

**Comment by zaunist** [comment]
Hi, @zjzwjcbj . It's recommend to develop on Linux.

**Comment by tzssangglass** [comment]
Recommended for development on x86 systems, dependency support on M1 is not complete.

**Comment by tzssangglass** [comment]
@zjzwjcbj  we can close this?

**Comment by zjzwjcbj** [comment]
> @zjzwjcbj we can close this?

Ok,thanks.
