### ISSUE TITLE
init_worker_by_lua error: ./apisix/plugins/prometheus/exporter.lua:17: module 'prometheus' not found:

### ISSUE THREAD

**Issue by 532810439** [apache/apisix#5827]
### Issue description

get  apisix-release-2.7.zip    from  https://github.com/apache/apisix/releases   

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

make deps   ->success
apisix init     ->success
apisix start   ->success

### Actual result

module 'prometheus' not found:

### Error log

[error] 120522#0: init_worker_by_lua error: ./apisix/plugins/prometheus/exporter.lua:17: module 'prometheus' not found:
	no field package.preload['prometheus']
	no file '/home/cicv/apisix-release-2.7//deps/share/lua/5.1/prometheus.lua'
	no file '/home/cicv/apisix-release-2.7//deps/share/lua/5.1/prometheus/init.lua'
	no file '/home/cicv/apisix-release-2.7/prometheus.lua'
	no file '/home/cicv/apisix-release-2.7/prometheus/init.lua'
	no file '/usr/local/openresty/site/lualib/prometheus.ljbc'
	no file '/usr/local/openresty/site/lualib/prometheus/init.ljbc'
	no file '/usr/local/openresty/lualib/prometheus.ljbc'
	no file '/usr/local/openresty/lualib/prometheus/init.ljbc'
	no file '/usr/local/openresty/site/lualib/prometheus.lua'
	no file '/usr/local/openresty/site/lualib/prometheus/init.lua'
	no file '/usr/local/openresty/lualib/prometheus.lua'
	no file '/usr/local/openresty/lualib/prometheus/init.lua'
	no file './prometheus.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/prometheus.lua'
	no file '/usr/local/share/lua/5.1/prometheus.lua'
	no file '/usr/local/share/lua/5.1/prometheus/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/prometheus.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/prometheus/init.lua'
	no file './prometheus.lua'
	no file '/usr/share/lua/5.1/prometheus.lua'
	no file '/usr/share/lua/5.1/prometheus/init.lua'
	no file '/usr/lib64/lua/5.1/prometheus.lua'
	no file '/usr/lib64/lua/5.1/prometheus/init.lua'
	no file '/home/cicv/apisix-release-2.7//deps/lib64/lua/5.1/prometheus.so'
	no file '/home/cicv/apisix-release-2.7//deps/lib/lua/5.1/prometheus.so'
	no file '/usr/local/openresty/site/lualib/prometheus.so'
	no file '/usr/local/openresty/lualib/prometheus.so'
	no file './prometheus.so'
	no file '/usr/local/lib/lua/5.1/prometheus.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/prometheus.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './prometheus.so'
	no file '/usr/lib64/lua/5.1/prometheus.so'
	no file '/usr/lib64/lua/5.1/

**Comment by spacewander** [comment]
The zip is not the official release. Please read https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md to know how to install.

**Comment by 532810439** [comment]
now，I don't want to use OpenSSL。

wget  https://downloads.apache.org/apisix/2.7/apache-apisix-2.7-src.tgz

Report the same error  


[error] 120522#0: init_worker_by_lua error: ./apisix/plugins/prometheus/exporter.lua:17: module 'prometheus' not found:
no field package.preload['prometheus']
no file '/home/cicv/apisix-release-2.7//deps/share/lua/5.1/prometheus.lua'
no file '/home/cicv/apisix-release-2.7//deps/share/lua/5.1/prometheus/init.lua'
no file '/home/cicv/apisix-release-2.7/prometheus.lua'
no file '/home/cicv/apisix-release-2.7/prometheus/init.lua'
no file '/usr/local/openresty/site/lualib/prometheus.ljbc'
no file '/usr/local/openresty/site/lualib/prometheus/init.ljbc'
no file '/usr/local/openresty/lualib/prometheus.ljbc'
no file '/usr/local/openresty/lualib/prometheus/init.ljbc'
no file '/usr/local/openresty/site/lualib/prometheus.lua'
no file '/usr/local/openresty/site/lualib/prometheus/init.lua'
no file '/usr/local/openresty/lualib/prometheus.lua'
no file '/usr/local/openresty/lualib/prometheus/init.lua'
no file './prometheus.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/prometheus.lua'
no file '/usr/local/share/lua/5.1/prometheus.lua'
no file '/usr/local/share/lua/5.1/prometheus/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/prometheus.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/prometheus/init.lua'
no file './prometheus.lua'
no file '/usr/share/lua/5.1/prometheus.lua'
no file '/usr/share/lua/5.1/prometheus/init.lua'
no file '/usr/lib64/lua/5.1/prometheus.lua'
no file '/usr/lib64/lua/5.1/prometheus/init.lua'
no file '/home/cicv/apisix-release-2.7//deps/lib64/lua/5.1/prometheus.so'
no file '/home/cicv/apisix-release-2.7//deps/lib/lua/5.1/prometheus.so'
no file '/usr/local/openresty/site/lualib/prometheus.so'
no file '/usr/local/openresty/lualib/prometheus.so'
no file './prometheus.so'
no file '/usr/local/lib/lua/5.1/prometheus.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/prometheus.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './prometheus.so'
no file '/usr/lib64/lua/5.1/prometheus.so'
no file '/usr/lib64/lua/5.1/

**Comment by tzssangglass** [comment]
zip file is source code of APISIX, as @spacewander said, you need to build APISIX form source code.
