### ISSUE TITLE
request: Expect monitoring metrics to add monitoring of nginx shared memory usage

### ISSUE THREAD

**Issue by chanjet1213** [apache/apisix#5837]
### Issue description

期待监控指标添加对nginx共享内存使用情况的监控

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
It seems to be quite difficult, and if you use the ngx.shared.DICT API to monitor it, it will lose performance.

refer to: https://github.com/openresty/lua-nginx-module#ngxshareddictcapacity

**Comment by kwanhur** [comment]
Is it like [ngx_slab_stats](https://github.com/alibaba/tengine/tree/master/modules/ngx_slab_stat)? Which supports shared memory allocated from lua-nginx-module.

**Comment by tokers** [comment]
> I changed my mind and I think it's a meaningful enhancemen.
> 
> Perhaps we can first monitor the nginx.shared.DICT that is used by APISIX, and next we allow users to monitor a custom nginx.shared.DICT (or read the used nginx.shared.DICT directly from the configuration file).
> 
> cc @spacewander

@tzssangglass Could you share your proposal?

**Comment by tzssangglass** [comment]
we can use `ngx.shared.DICT.capacity` and `ngx.shared.DICT.free_space` to monitor a `ngx.shared.DICT`?

**Comment by tokers** [comment]
> > @tzssangglass Could you share your proposal?
> 
> we can use `ngx.shared.DICT.capacity` and `ngx.shared.DICT.free_space` to monitor a `ngx.shared.DICT`?

OK so we may get a curve about the shared dict, in the diagram we can see the shared dict memory usage.

**Comment by ccxhwmy** [comment]
> > @tzssangglass Could you share your proposal?
> 
> we can use `ngx.shared.DICT.capacity` and `ngx.shared.DICT.free_space` to monitor a `ngx.shared.DICT`?
I found that nginx adopts a way of pre-allocating memory for shared DICT, the smallext granularity is page, ranther than each allocation per use. The value of `ngx.shared.DICT.capacity` is accurate, but `ngx.shared.DICT.free_space` is the value left after the acquired pre-allocated memory, so there is a certain inconsistency in fine-grained `ngx.shared.DICT.free_space` accurate.

**Comment by tzssangglass** [comment]
> I found that nginx adopts a way of pre-allocating memory for shared DICT, the smallest granularity is page, ranther than allocat per use. The value of `ngx.shared.DICT.capacity` is accurate, but `ngx.shared.DICT.free_space` is the value left after the acquired pre-allocated memory, so there is a certain inconsistency in fine-grained `ngx.shared.DICT.free_space` accurate.

Is there some docs or code that explain this? This is useful info.

**Comment by ccxhwmy** [comment]
> > I found that nginx adopts a way of pre-allocating memory for shared DICT, the smallest granularity is page, ranther than allocat per use. The value of `ngx.shared.DICT.capacity` is accurate, but `ngx.shared.DICT.free_space` is the value left after the acquired pre-allocated memory, so there is a certain inconsistency in fine-grained `ngx.shared.DICT.free_space` accurate.
> 
> Is there some docs or code that explain this? This is useful info.

I checked the C code of `ngx.shared.DICT`, the ffi call function of `free_space` is `ngx_http_lua_ffi_shdict_free_space`, and the caluculation method is `bytes = ctx->shpool->pfree * ngx_pagesize;`. The ffi calling process of `set` is `ngx_http_lua_ffi_shdict_store->ngx_slab_alloc_locked->ngx_slab_alloc_pages`, it will judge whether the memory previously malloc is enough, if it is enough, it will not malloc memory. `pfree` will only be modified when entering `ngx_slab_alloc_pages` to malloc memory.

**Comment by tzssangglass** [comment]
Hi @ccxhwmy , would you like to work on this?

**Comment by ccxhwmy** [comment]
> Hi @ccxhwmy , would you like to work on this?

Can you tell me which plugin I can modify to get information of `ngx.shared.DICT` regularly and report it?

**Comment by tzssangglass** [comment]
> Can you tell me which plugin I can modify to get information of `ngx.shared.DICT` regularly and report it? prometheus?

yes, prometheus.
