### ISSUE TITLE
bug: When will GM SSL be supported

### ISSUE THREAD

**Issue by 532810439** [apache/apisix#5844]
### Issue description

GM/T 0024-2014 SSL VPN specification

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
2.11

### Steps to reproduce

GM SSL be supported

### Actual result

==

### Error log

==

**Comment by tokers** [comment]
I'm not so familiar with the GM SSL, could you give us the white paper, or the specification link, and some implementations?

**Comment by 532810439** [comment]
http://www.gb688.cn/bzgk/gb/newGbInfo?hcno=778097598DA2761E94A5FF3F77BD66DA

**Comment by spacewander** [comment]
Let's move to https://github.com/apache/apisix/issues/953
