### ISSUE TITLE
request help:  proxy_pass cannot use https

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix#5847]
### Issue description

![image](https://user-images.githubusercontent.com/48319268/146496223-e54e935b-82c2-4a5d-afc7-fdebc6f472d2.png)
nginx returen 502 
![image](https://user-images.githubusercontent.com/48319268/146496892-5aaac49a-9919-45df-a527-2e8906d8ab8a.png)
route use force https 
![image](https://user-images.githubusercontent.com/48319268/146496958-f804133d-fae4-4ccd-a8d5-f35345cad8b9.png)

apisix log:
2021/12/17 14:00:15 [error] 51#51: *7848975 [lua] init.lua:157: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: xxxxxx, server: 0.0.0.0:9443

### Environment

- apisix version 2.10.2:
- OS centos7.9:
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, 3.4.0
- apisix-dashboard version, 2.9

**Comment by Horus-K** [comment]
If proxy_pass uses http, then the route cannot be enabled to force https, otherwise there will be too many 301 redirects

**Comment by Horus-K** [comment]
I used ingress-nginx to start force https, return code 308, proxy_pass can use https
On apisix, I used https forwarding and set ret_code 308. In the end, proxy_pass still redirected too many 301 and was not accessible

**Comment by Horus-K** [comment]
i see this https://github.com/apache/apisix/issues/2257 but ret_code still not work 
![image](https://user-images.githubusercontent.com/48319268/146503014-7d7c15f9-b70b-4f81-9b89-bb419d6d6cca.png)
![image](https://user-images.githubusercontent.com/48319268/146503021-71ad7aa0-bd5d-4cd7-bafb-32dd5ca1ede3.png)

**Comment by tokers** [comment]
Please describe your architecture elaborately.

**Comment by Horus-K** [comment]
> Please describe your architecture elaborately.

We have 5 nginx online servers, we need to use proxy_pass to gray some traffic to apisix

**Comment by Horus-K** [comment]
> Please describe your architecture elaborately.

And I need to know how to use proxy_pass https

**Comment by Horus-K** [comment]
location / {
        index index.html;
        proxy_pass https://xxxxxxx.com;

        proxy_set_header Host $proxy_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_session_reuse off;
        proxy_ssl_server_name on;
        proxy_ssl_name $proxy_host;
        proxy_ssl_protocols TLSv1.2;
    }  that's it

**Comment by Horus-K** [comment]
bushi
