### ISSUE TITLE
request help: how to install in ubuntu

### ISSUE THREAD

**Issue by Carson-T** [apache/apisix#5851]
### Issue description

I can not find any course about how to install APISIX on ubuntu, please help me

### Environment

ubuntu20.04.3

**Comment by zaunist** [comment]
Hi, @Carson-T , we have a [repository](https://github.com/api7/apisix-build-tools) to packaging apisix for ubuntu, you can refer to package apisix on your machine.

**Comment by Carson-T** [comment]
thank you!!

**Comment by Carson-T** [comment]
> Hi, @Carson-T , we have a [repository](https://github.com/api7/apisix-build-tools) to packaging apisix for ubuntu, you can refer to package apisix on your machine.

thank you!!!

**Comment by tzssangglass** [comment]
consider as solved, feel free to reopen this if you need.

**Comment by chenyyyang** [comment]
make package type=deb app=apisix version=2.2 checkout=2.2
ls output/
apisix_2.2-0~ubuntu20.04_amd64.deb

 
Hi. @zaunist  @tzssangglass  @Carson-T 
I am not sure about the steps of installation at Ubuntu.
Step 1. clone teh https://github.com/api7/apisix-build-tools

Step2.
make package type=deb app=apisix version=2.2 checkout=2.2
ls output/
apisix_2.2-0~ubuntu20.04_amd64.deb

Step3.
use command "make run "to start apisix.

Do you mind sharing more information of detail Steps  or the logistics of apisix-build-tools

**Comment by juzhiyuan** [comment]
Hi @chenyyyang,

> use command "make run "to start apisix.

The `make run` command is used for Development mode AFAIK. It should be `make deps && make install && apisix start` instead according to https://apisix.apache.org/docs/apisix/next/building-apisix

As for your question: you could also refer to the link above to install on Ubuntu (I have tried on Ubuntu 18 & 20) 😄 

Cc @bzp2010 to confirm if it's recommended.

**Comment by tzssangglass** [comment]
> apisix_2.2-0~ubuntu20.04_amd64.deb

after build deb, we can intsall APISIX from local deb?
