### ISSUE TITLE
bug:  unambiguous fully-qualified domain name(FQDN),  i.e. ended in a dot. 

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#5855]
### Issue description

need to upgrade lua-resty-dns-client >=5.2.2

- https://github.com/Kong/lua-resty-dns-client#522-11-mar-2021

### Environment

- apisix version (cmd: `apisix version`): master

### Steps to reproduce

There is no

### Actual result

There is no

### Error log

There is no

**Comment by dickens7** [comment]
Domain names ended in a dot can solve this problem  #4874

**Comment by spacewander** [comment]
Thanks for the report. Could you submit a PR for this?

**Comment by leslie-tsang** [comment]
Hello there, @dickens7 Would you submit a PR to fix it ?
Here is an [example](https://github.com/apache/apisix/pull/5971)
