### ISSUE TITLE
docs: team page broken

### ISSUE THREAD

**Issue by tisonkun** [apache/apisix#5860]
### Improved or typo fixed.

![image](https://user-images.githubusercontent.com/18818196/146727616-698a9390-bd39-4d0c-b8dd-f58b5a7150ee.png)

https://apisix.apache.org/team/

### Solution

not yet

**Comment by spacewander** [comment]
We are handling it. CC @juzhiyuan

**Comment by juzhiyuan** [comment]
Hi, this issue is because jsDelivr's CDN Provider in China has something wrong 🤣 And they're trying to fix it, I will wait for some hours and will fix it by using original resources links. For more information, please see 
 https://lists.apache.org/thread/br03lmd3n73lbc6n0lzcmqjbvy960wvf

**Comment by juzhiyuan** [comment]
Note: This issue only affects users in China. 🙃

**Comment by juzhiyuan** [comment]
Hi, according to https://status.jsdelivr.com/ all servers are available now, consider resolved.
