### ISSUE TITLE
request help: split the full CI into two parts (running t/plugin and the other) 

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#5861]
### Issue description

Sometimes the full CI "linux_openresty" https://github.com/apache/apisix/blob/4423509680a0c2103ce23b30a0da71735ef73e8f/.github/workflows/build.yml#L27
takes 50 minutes to complete.

Let's split it into multiple parts so the max single job time can be reduced.

We can pass an environment variable as the test file range in https://github.com/apache/apisix/blob/4423509680a0c2103ce23b30a0da71735ef73e8f/ci/linux_openresty_common_runner.sh#L86

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by kwanhur** [comment]
solution example:
```shell
    # enable plugin test case or not
    plugin := $ENV_PROVE_PLUGIN
    # if on then all the cases into /tmp/test.t, otherwise exclude directory t/plugin/
    if [[ "$plugin" == "off" ]]; then
      find t/**/*.t ! -wholename '*/plugin/*' -type f | tee /tmp/test.t > /dev/null
    else
      find t/**/*.t -wholename '*/plugin/*' -type f | tee /tmp/test.t > /dev/null
    fi
    # read case from "STDIN", tests in file /tmp/test.t
    FLUSH_ETCD=1 prove -Itest-nginx/lib -I./ -r - < /tmp/test.t | tee /tmp/test.result
```

enable plugin test case or not with environment variable `ENV_PROVE_PLUGIN`, default `on`.
disable it with `export ENV_PROVE_PLUGIN=off`.

**Comment by kwanhur** [comment]
> solution example:
> 
> ```shell
>     # enable plugin test case or not
>     plugin := $ENV_PROVE_PLUGIN
>     # if on then all the cases into /tmp/test.t, otherwise exclude directory t/plugin/
>     if [[ "$plugin" == "off" ]]; then
>       find t/**/*.t ! -wholename '*/plugin/*' -type f | tee /tmp/test.t > /dev/null
>     else
>       find t/**/*.t -wholename '*/plugin/*' -type f | tee /tmp/test.t > /dev/null
>     fi
>     # read case from "STDIN", tests in file /tmp/test.t
>     FLUSH_ETCD=1 prove -Itest-nginx/lib -I./ -r - < /tmp/test.t | tee /tmp/test.result
> ```
> 
> enable plugin test case or not with environment variable `ENV_PROVE_PLUGIN`, default `on`. disable it with `export ENV_PROVE_PLUGIN=off`.

ignore the specified dir name could be better:

1. env variable `ENV_PROVE_IGNORE_DIR`
2. `find t/**/*.t ! -wholename '*/$ENV_PROVE_IGNORE_DIR/*' -type f | tee /tmp/test.t > /dev/null`

**Comment by tokers** [comment]
@kwanhur Does read test cases from the stdin cause the troubleshooting harder? Such as the case location.

**Comment by kwanhur** [comment]
> @kwanhur Does read test cases from the stdin cause the troubleshooting harder? Such as the case location.

I don't think so. 

On this way, It's equal to read a list of tests in a file, like [test.t](https://gist.github.com/kwanhur/6c67a9d1ffb5fd4e9f3184127367a69a), instead of default test directory `t/*.t`.

**Comment by tokers** [comment]
> > @kwanhur Does read test cases from the stdin cause the troubleshooting harder? Such as the case location.
> 
> I don't think so.
> 
> On this way, It's equal to read a list of tests in a file, like [test.t](https://gist.github.com/kwanhur/6c67a9d1ffb5fd4e9f3184127367a69a), instead of default test directory `t/*.t`.

Yes, you're right, just ignore it.

**Comment by spacewander** [comment]
@tokers @kwanhur 
Ignore the particular tests **only** doesn't solve the problem. When should we run the ignore tests?

**Comment by spacewander** [comment]
@tzssangglass 
Would you please handle this issue?

**Comment by kwanhur** [comment]
> @tokers @kwanhur Ignore the particular tests **only** doesn't solve the problem. When should we run the ignore tests?

at the beginning, I think we can split workflow `CI` into different parts, then each part uses different env variable to run different test cases.
