### ISSUE TITLE
docs: Can the Docs show a complete example of log_format？

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5868]
### Improved or typo fixed.

APISIX有很多日志插件，且支持自定义日志格式，但是文档里面对于自定义日志格式的描述过于简单，加大了自定义日志格式的难度，在搜索引擎搜索相关文档也基本没有log_format的相关说明。

另外，文档里面我看到展示了APISIX可以支持的变量：
![image](https://user-images.githubusercontent.com/9711651/146856319-23bffaf5-9332-4372-a4ea-8c973613007e.png)
感觉应该不止这些，比如 upstream_latency 、apisix_latency 这些阶段耗时字段没找到，有没有地方可以看到所有APISIX支持的可以用于定义log_format的变量呢？

### Solution

总结一下：
1. 建议Docs里面可以展示下默认的log_format，即不配置自定义log_format时输出的日志的格式模板，我们可以快速基于这个模板来自定义log_format，可以简化上手门槛；
2. 除了可以在 http://nginx.org/en/docs/varindex.html 查看所有Nginx支持的变量，希望也展示下APISIX能支持的所有日志变量；
3. 如果可以的话，建议再展示一些常用的log_format的最佳实践。

**Comment by spacewander** [comment]
"upstream_latency 、apisix_latency" those fields are hand-writing. They are not set via variable.

In fact, `log_format` can only support a subset of the data. The default log data can't be represented via log_format.

**Comment by membphis** [comment]
> 总结一下：
> 
> 1. 建议Docs里面可以展示下默认的log_format，即不配置自定义log_format时输出的日志的格式模板，我们可以快速基于这个模板来自定义log_format，可以简化上手门槛；
> 2. 除了可以在 http://nginx.org/en/docs/varindex.html 查看所有Nginx支持的变量，希望也展示下APISIX能支持的所有日志变量；
> 3. 如果可以的话，建议再展示一些常用的log_format的最佳实践。

welcome PR, make the doc better

**Comment by juzhiyuan** [comment]
Hi @jagerzhang, here has one PR that describes all Apache APISIX supporting variables, see https://github.com/apache/apisix/pull/5997/files

As for the default `log_format` configuration, we could find them here https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L90-L95 and https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L33-L40

Could you help to improve the Docs to make it more clear?

**Comment by jagerzhang** [comment]
> Hi @jagerzhang, here has one PR that describes all Apache APISIX supporting variables, see https://github.com/apache/apisix/pull/5997/files
> 
> As for the default `log_format` configuration, we could find them here https://github.com/apache/apisix/blob/master/apisix/plugins/kafka-logger.lua#L90-L95 and https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L33-L40
> 
> Could you help to improve the Docs to make it more clear?

谢谢回复，已经看到你们的PR了，辛苦。

其实在不设置log_format元数据的时候，默认的日志格式应该是这样的：https://github.com/apache/apisix/blob/aff5d825aaea12eab312e65e82d060ab9be9b06f/apisix/utils/log-util.lua#L99-L124

所以，我觉得文档中的log_format的例子可以将上述默认日志格式作为展示，比如：
```
{
    "url": "$scheme://$host:$server_port$request_uri",
    "uri": "$request_uri",
    "method": "$request_method",
    "headers": "这里是一个集合，可能不太好获取",
    "querystring": "$query_string",
    "size": "$request_length",
    "response": {
        "status": "$status",
        "headers": "这里是一个集合，可能不太好获取",
        "size": "$bytes_sent"
    },
    "server": {
        "hostname": "$hostname",
        "version": "$nginx_version"
    },
    "upstream": "$upstream_addr",
    "service_id": "$service_id",
    "route_id": "$route_id",
    "consumer": "$consumer",
    "client_ip": "$client_ip",
    "start_time": "$start_time",
    "latency": "$latency"
}
```
注：可能有些是一个函数，不知道该怎么改成变量，我大概意思就是log_format在不设置的时候的默认日志格式，可以做成一个例子，用户在定义log_format的时候只需要参考这个趋向于完整的例子去改，这样上手门槛就降低了非常多了，而且日志也是更全面的。
