### ISSUE TITLE
docs: add enable commands to the control API in the plugin development documentation

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix#5870]
### Improved or typo fixed.

Hi, community, 
When I develop a plugin based on the [plugin development documentation](https://apisix.apache.org/docs/apisix/plugin-develop/#register-control-api), in the case of the control API, there is no relevant command in the documentation. I am still using port 9080 to test the control API, but I keep getting 404 errors.

Then I found out in the [control API documentation](https://apisix.apache.org/docs/apisix/control-api) that it was listening on port 9090 and I knew I should test it with 9090. But I had never thought of it as a port problem before.

### Solution

We can write a test command in the plugin development documentation under the control API, like
```
curl -i http://127.0.0.1:9090/v1/plugin/example-plugin/hello
```
and add a tip to remind the user that the control API is listening on port 9090
![image](https://user-images.githubusercontent.com/72343596/146860044-95bcb868-18dd-4173-9244-a74e553c50f7.png)

**Comment by guoqqqi** [comment]
I will complete it if needed 😄

**Comment by spacewander** [comment]
Yes, we can do it. Note that we need to explain the port of control-api is configurable.
