### ISSUE TITLE
request help: Plugin mount

### ISSUE THREAD

**Issue by Ilqjx** [apache/apisix#5877]
### Issue description

Why are there so many stages when mounting a custom plugin instead of a simple request/response?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
These custom plugins contain not only plugins written in other languages which reply on the plugin-runner, but also some plugins written in Lua, for the latter, simple request/response is not feasible.

**Comment by Ilqjx** [comment]
For simple request/response is not feasible, I don’t quite understand, can you give me an example, thank you.

**Comment by tokers** [comment]
> For simple request/response is not feasible, I don’t quite understand, can you give me an example, thank you.

Please read the https://apisix.apache.org/docs/apisix/architecture-design/plugin to understand the plugin architecture.

**Comment by Ilqjx** [comment]
Does that mean that most of the plugins use simple request/response to solve the problem, but for some plugins, such as permission control plugins, they need to be inserted at the specified stage.

**Comment by Ilqjx** [comment]
Why a simple request/response is not feasible for plugins written in Lua?

**Comment by tokers** [comment]
> Why a simple request/response is not feasible for plugins written in Lua?

Sorry I'm confused by your descriptions of this issue, so you want to let APISIX communicate with an external plugin written in Lua through simple request/response?

That's a feasible idea but now we don't support such a "lua plugin runner".

**Comment by Ilqjx** [comment]
Ok thanks for your reply.
