### ISSUE TITLE
request help: how to add nodes in upstreams

### ISSUE THREAD

**Issue by hushaojun-0801** [apache/apisix#5878]
### Issue description

i use doc example but return 400 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by hushaojun-0801** [comment]
curl http://127.0.0.1:80/apisix/admin/upstreams/100 -H'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d '
> {
>     "nodes": {
>         "39.97.63.216:80": 1
>     }
> }'
HTTP/1.1 400 Bad Request
Date: Wed, 22 Dec 2021 02:10:01 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: *
Access-Control-Max-Age: 3600
Server: APISIX web server

{"error_msg":"invalid configuration: property \"type\" is required"}

**Comment by hushaojun-0801** [comment]
reset all upstreams after add type ，i  just want add a node

**Comment by shuaijinchao** [comment]
I cannot reproduce the problem with the example in the documentation

---
![image](https://user-images.githubusercontent.com/8529452/147043520-eddc9a60-2d72-43bb-ae41-60c89c1927b5.png)

**Comment by tokers** [comment]
@hushaojun-0801 The error log is self-documented, you should add the `type` field.

**Comment by hushaojun-0801** [comment]
srroy，i use  1.2 version  not 2.11，i will update now
