### ISSUE TITLE
docs: Mention four features that can be added later

### ISSUE THREAD

**Issue by aa57255621** [apache/apisix#5879]
### Improved or typo fixed.

Our company wants to use Apisix. Based on my recent use and the last Apisix weekly meeting, I'd like to address some needs to improve the Apisix experience,

1、hope the apisix-dashboard  supports configuration ofthe apisix custom plugin.
2、hope the apisix-dashboard supports configuration and modification of schema.json.
3、hope the Apisix-Dashboard Orchestration mode to be more powerful.
4、Hopefully the Serverless config plugin can provide more detailed documentation, or more examples, Novices  can  get started serverless config faster, not always look at the source code 

### Solution

Hope the above functions can be supported soon

**Comment by shuaijinchao** [comment]
cc @juzhiyuan

**Comment by juzhiyuan** [comment]
Hi @aa57255621, glad to hear from you! I'm personally preparing the Dashboard V3 proposal, will post it to the community once I'm ready, but you could have a look and comment on it :) see https://docs.qq.com/doc/DTkdBcG5IT3V6VER3

Also, we have the Meeting today, welcome to join! see https://docs.qq.com/doc/DTkdBcG5IT3V6VER3

https://github.com/apache/apisix/discussions/5873

**Comment by lijing-21** [comment]
Hi @aa57255621 , thank you for your contribution to the Apache APISIX!

We'd like to send you the special Contributor T-shirt[1], you could fill this form[2]~

[1] https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#contributor-t-shirt
[2] https://forms.gle/ycKcJNsjnqajMYzu7
