### ISSUE TITLE
feat: support to use path parameter with plugin's control api

### ISSUE THREAD

**Issue by The-White-Lion** [apache/apisix#5882]
### Issue description

Now,  when configure `radixtree_uri_with_parameter` in `config.yaml`, it only work on Route.
If you want use path parameter with control api, you must change source code.
Could you provide an optional way to configure it without change source code just like `radixtree_uri_with_parameter.lua`

### Environment

- all version

**Comment by spacewander** [comment]
It's possible to switch the router used for control-api, just like
https://github.com/apache/apisix/blob/a1024075103ca4107b04db3f1258b860f9c823cd/apisix/http/route.lua#L96

PR is welcome!

**Comment by The-White-Lion** [comment]
> It's possible to switch the router used for control-api, just like
> 
> https://github.com/apache/apisix/blob/a1024075103ca4107b04db3f1258b860f9c823cd/apisix/http/route.lua#L96
> 
> PR is welcome!

I submit a PR for this issue,  you can check this in #5934
