### ISSUE TITLE
request help: How to forward the received tcp data to multiple tcp backends at the same time (similar to broadcasting, not load balancing)

### ISSUE THREAD

**Issue by zhouyu0914k** [apache/apisix#5893]
### Issue description

只需要转发，不需要处理后端响应。http可以通过 proxy-mirror 实现，tcp的动态代理可以用stream_routes实现，但是不知道如何实现将收到的数据同时转发给多个后端

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`): Linux dev81 5.14.14-1.el7.elrepo.x86_64 #1 SMP Tue Oct 19 07:39:36 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.13
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
You can write a plugin for it. In this plugin, you can use `ngx.req.socket()` to read the data of client, and forward to multiple backend via `ngx.socket.tcp`. See https://github.com/openresty/stream-lua-nginx-module

**Comment by zhouyu0914k** [comment]
你好，我尝试过在openresty里使用lua脚本实现该功能，遇到了很多问题，我们apisix有交流群吗，我去群里问问

**Comment by juzhiyuan** [comment]
> 你好，我尝试过在openresty里使用lua脚本实现该功能，遇到了很多问题，我们apisix有交流群吗，我去群里问问

Hi @zhouyu0914k, we have an unofficial Apache APISIX WeChat group, add my WeChat **JuShaoyao** and I could invite you, but we still recommend using **GitHub issue and Mailing list** as DISCUSSION channel :)

**Comment by zhouyu0914k** [comment]
I tried to realize it using lua script, but got some trouble. 

The nginx.conf is:
  stream {
    lua_code_cache off;
    server {
        listen 10075;
        content_by_lua_file /usr/local/openresty/test.lua;
    }
  }

The test.lua is:
  while (true)
  do
    ngx.say("Hellow lua!!!")
    os.execute("sleep " .. 5)
  end

I found the script is executed on only the first connection and not on subsequent connection. How i can make certain the process mechanism?

**Comment by juzhiyuan** [comment]
Hi @leslie-tsang, @zhouyu0914k wants to know why this Lua Script is run only when the first connection is established, do you have some hints for him so he could learn why this happen? and how to run that Script when every connection is established?

**Comment by leslie-tsang** [comment]
Hello there, @zhouyu0914k Ref to [lua-resty-websocket](https://github.com/openresty/lua-resty-websocket) should help.

**Comment by zhouyu0914k** [comment]
@leslie-tsang I've seen [lua-resty-websocket](https://github.com/openresty/lua-resty-websocket), but I still don't know how to do. The biggest problem is that I don't know the execution mechanism of the script. Can you provide some relevant documents?

**Comment by zhouyu0914k** [comment]
I have implemented some functions through the following code：
```
         local sock = assert(ngx.req.socket(true))
         local dest_sock = ngx.socket.tcp()
         local ok, err = dest_sock:connect("10.1.129.81", 9999)
         if not ok then
             ngx.say("failed to connect to dest: ", err)
             return
         end
         dest_sock:settimeout(10000)  -- one second timeout
         while(true)
         do
           :: loop_begin :: local data, err = sock:receiveany(10 * 1024)
           if err then 
              if err ~= "timeout" then
                  ngx.say("encounter error: ", err)
                  return
              else
                  goto loop_begin
              end
           end
           if data then
             dest_sock:send(data)
           end
         end
```
But when I specify multiple TCP backend through upstream and get them by ngx.upstream the following error are encountered:
```
2021/12/28 14:06:43 [error] 89789#89789: *1 lua entry thread aborted: runtime error: content_by_lua(nginx.conf:88):2: module 'ngx.upstream' not found:
	no field package.preload['ngx.upstream']
	no file '/usr/local/openresty/site/lualib/ngx/upstream.ljbc'
	no file '/usr/local/openresty/site/lualib/ngx/upstream/init.ljbc'
	no file '/usr/local/openresty/lualib/ngx/upstream.ljbc'
	no file '/usr/local/openresty/lualib/ngx/upstream/init.ljbc'
	no file '/usr/local/openresty/site/lualib/ngx/upstream.lua'
	no file '/usr/local/openresty/site/lualib/ngx/upstream/init.lua'
	no file '/usr/local/openresty/lualib/ngx/upstream.lua'
	no file '/usr/local/openresty/lualib/ngx/upstream/init.lua'
	no file './ngx/upstream.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/ngx/upstream.lua'
	no file '/usr/local/share/lua/5.1/ngx/upstream.lua'
	no file '/usr/local/share/lua/5.1/ngx/upstream/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/upstream.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/ngx/upstream/init.lua'
	no file '/usr/local/openresty/site/lualib/ngx/upstream.so'
	no file '/usr/local/openresty/lualib/ngx/upstream.so'
	no file './ngx/upstream.so'
	no file '/usr/local/lib/lua/5.1/ngx/upstream.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx/upstream.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/openresty/site/lualib/ngx.so'
	no file '/usr/local/openresty/lualib/ngx.so'
	no file './ngx.so'
	no file '/usr/local/lib/lua/5.1/ngx.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/ngx.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(nginx.conf:88):2: in main chunk, client: 10.1.129.82, server: 0.0.0.0:10075
```
The same code can be executed normally in the `http - > server` block. How can I get the content of upstream in the `stream - > server` block. The code is:
```
local upstream = require "ngx.upstream"
         local get_servers = upstream.get_servers
         local srvs, err = get_servers("gateway")
         if not srvs then
             ngx.say("failed to get servers in upstream ", u)
         else
             for _, srv in ipairs(srvs) do
                 local first = true
                 for k, v in pairs(srv) do
                     if first then
                         first = false
                         ngx.print("    ")
                     else
                         ngx.print(", ")
                     end
                     if type(v) == "table" then
                         ngx.print(k, " = {", concat(v, ", "), "}")
                     else
                         ngx.print(k, " = ", v)
                     end
                 end
                 ngx.print("\n")
             end
         end

```
