### ISSUE TITLE
request help: How to add ext-plugin in config.yaml ,since apisix installed  by helm 

### ISSUE THREAD

**Issue by zjzwjcbj** [apache/apisix#5901]
### Issue description

I installed apisix by helm .How can I add ext-plugin  in config.yaml. like:
![image](https://user-images.githubusercontent.com/26433840/147234745-8934fc99-fec3-4ac5-b36c-22cfd23a5602.png)

### Environment

apisix version (cmd: apisix version):2.10.0
OS (cmd: uname -a):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 change: added doc of how to load plugin. #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux
OpenResty / Nginx version (cmd: nginx -V or openresty -V):openresty/1.19.3.1
etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API):3.4.16
apisix-dashboard version, if have:2.9.0
the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
luarocks version, if the issue is about installation (cmd: luarocks --version):

**Comment by tokers** [comment]
> ### Issue description
> I installed apisix by helm .How can I add ext-plugin in config.yaml. like: ![image](https://user-images.githubusercontent.com/26433840/147234745-8934fc99-fec3-4ac5-b36c-22cfd23a5602.png)
> 
> ### Environment
> apisix version (cmd: apisix version):2.10.0 OS (cmd: uname -a):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 change: added doc of how to load plugin. #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux OpenResty / Nginx version (cmd: nginx -V or openresty -V):openresty/1.19.3.1 etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API):3.4.16 apisix-dashboard version, if have:2.9.0 the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): luarocks version, if the issue is about installation (cmd: luarocks --version):

Hi!

See https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L321 for details.

I think it can be added to the FAQ, would you like to submit a PR to add it? Thanks!

**Comment by zjzwjcbj** [comment]
> > ### Issue description
> > I installed apisix by helm .How can I add ext-plugin in config.yaml. like: ![image](https://user-images.githubusercontent.com/26433840/147234745-8934fc99-fec3-4ac5-b36c-22cfd23a5602.png)
> > ### Environment
> > apisix version (cmd: apisix version):2.10.0 OS (cmd: uname -a):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 change: added doc of how to load plugin. #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux OpenResty / Nginx version (cmd: nginx -V or openresty -V):openresty/1.19.3.1 etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API):3.4.16 apisix-dashboard version, if have:2.9.0 the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): luarocks version, if the issue is about installation (cmd: luarocks --version):
> 
> Hi!
> 
> See https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L321 for details.
> 
> I think it can be added to the FAQ, would you like to submit a PR to add it? Thanks!

I mean I don't change the source code. Can I  change the configmap.yaml and values.yaml  which in chart to run the ext plugin

**Comment by zjzwjcbj** [comment]
How to install java plugin when apisix installed by helm. Seem the apisix pod has no java environment.

**Comment by tokers** [comment]
> How to install java plugin when apisix installed by helm. Seem the apisix pod has no java environment.

Oops. If I am correct, our helm chart doesn't expose the `ext-plugin` field, we may enhance the helm chart.

> How to install java plugin when apisix installed by helm. Seem the apisix pod has no java environment.

You can build a new container with Java environments based on Apache APISIX Images.

**Comment by zjzwjcbj** [comment]
> > How to install java plugin when apisix installed by helm. Seem the apisix pod has no java environment.
> 
> Oops. If I am correct, our helm chart doesn't expose the `ext-plugin` field, we may enhance the helm chart.
> 
> > How to install java plugin when apisix installed by helm. Seem the apisix pod has no java environment.
> 
> You can build a new container with Java environments based on Apache APISIX Images.

Ok,thanks。

**Comment by juzhiyuan** [comment]
> Oops. If I am correct, our helm chart doesn't expose the ext-plugin field, we may enhance the helm chart.

Hi @tokers, do we need to set this as Good first issue?
