### ISSUE TITLE
Proposal: include performance test and flamegraphs in CI

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#5902]
### Background

We have published performance test data for APISIX in the early days, but with the rapid iteration of APISIX, it has been a long time since we have updated it. 

Now we need a way to keep an eye on the current performance of APISIX more easily.

### Solution

Adding performance test and flamegraphs to the CI can help us keep track of APISIX performance in real time and identify potential performance issues and memory problems.

**Comment by tokers** [comment]
That's good, do you mean sampling APISIX when the test cases run?

**Comment by tzssangglass** [comment]
I want to generate flamegraphs during performance testing.

**Comment by tokers** [comment]
> I want to generate flamegraphs during performance testing.

As far I as know, APISIX will be started before a case and be shutdown after a case, so actually it's not running continuously.

**Comment by tzssangglass** [comment]
Yes, so the flamegraphs is not generated when the test case is run. We need to add a performance test step, and generate flamegraphs during performance testing.

**Comment by tokers** [comment]
> Yes, so the flamegraphs is not generated when the test case is run. We need to add a performance test step, and generate flamegraphs during performance testing.

Got it.

**Comment by spacewander** [comment]
Already done.
