### ISSUE TITLE
request help: can the log-plugins supports to logging upstream_latency and apisix_latency?

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5910]
### Issue description

现在所有日志插件就只能上报 latency 字段，能否将后端耗时和APISIX本身的耗时也分开记录下，方便运营分析？

### Environment

APISIX version: 2.11.0

**Comment by tokers** [comment]
You can customize the `log_format`field in plugin metadata according to your needs.

**Comment by shoulda** [comment]
> ### Issue description
> 现在所有日志插件就只能上报 latency 字段，能否将后端耗时和APISIX本身的耗时也分开记录下，方便运营分析？
> 
> ### Environment
> APISIX version: 2.11.0

请教一个问题，我们这边准备用prometheus来上报日志的，但是如何数据类型是counter，是否会有溢出现象或者受限于lua_shared_dict prometheus-metrics  的大小，你们这边又遇到这个问题吗？

**Comment by jagerzhang** [comment]
> You can customize the `log_format`field in plugin metadata according to your needs.

用log_format好像要把所有的字段都填写上才行吧？ 并不是追加的逻辑。

**Comment by jagerzhang** [comment]
> > You can customize the `log_format`field in plugin metadata according to your needs.
> 
> 试了下没生效，配置如下：
> 
> ```
> {
>   "batch_max_size": 1,
>   "broker_list": {
>     "X.X.X.X": 9092
>   },
>   "disable": false,
>   "include_req_body": true,
>   "include_resp_body": true,
>   "kafka_topic": "xxxxx",
>   "log_format": {
>     "apisix_latency": "$apisix_latency",
>     "upstream_latency": "$upstream_latency"
>   },
>   "max_retry_count": 3
> }
> ```
> 
> 求指引~


仔细看了下好像是要 PUT 到 plugin_metadata里面，那这里有个问题，我并不知道默认的log_format是怎么写的，如果我直接改成 
```
{
"log_format": {
    "apisix_latency": "$apisix_latency",
    "upstream_latency": "$upstream_latency"
  }
}
```
那其他字段是不是都没了？只剩下这2个字段？希望可以提供一个默认的log_format，然后我们追加下这2个字段.....

**Comment by jagerzhang** [comment]
> > > You can customize the `log_format`field in plugin metadata according to your needs.
> > 
> > 
> > 试了下没生效，配置如下：
> > ```
> > {
> >   "batch_max_size": 1,
> >   "broker_list": {
> >     "X.X.X.X": 9092
> >   },
> >   "disable": false,
> >   "include_req_body": true,
> >   "include_resp_body": true,
> >   "kafka_topic": "xxxxx",
> >   "log_format": {
> >     "apisix_latency": "$apisix_latency",
> >     "upstream_latency": "$upstream_latency"
> >   },
> >   "max_retry_count": 3
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 求指引~
> 
> 仔细看了下好像是要 PUT 到 plugin_metadata里面，那这里有个问题，我并不知道默认的log_format是怎么写的，如果我直接改成
> 
> ```
> {
> "log_format": {
>     "apisix_latency": "$apisix_latency",
>     "upstream_latency": "$upstream_latency"
>   }
> }
> ```
> 
> 那其他字段是不是都没了？只剩下这2个字段？希望可以提供一个默认的log_format，然后我们追加下这2个字段.....

用log_format应该就没法记录request_body了吧？

**Comment by tokers** [comment]
Actually, this [method](https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L76) will be run if the log_format is absent.

**Comment by juzhiyuan** [comment]
Hi @jagerzhang, AFAIK, you could follow this step to configure kafka-logger plugin:

1. (optional) `PUT /plugin_metedata` to use your custom `log_format` configuration for that plugin;
2. `PUT /routes` with `kafka-logger` configuration.

plugin_metedata is more like a General configuration, and it will work for all `kafka-logger` plugin.

**Comment by jagerzhang** [comment]
> Hi @jagerzhang, AFAIK, you could follow this step to configure kafka-logger plugin:
> 
> 1. (optional) `PUT /plugin_metedata` to use your custom `log_format` configuration for that plugin;
> 2. `PUT /routes` with `kafka-logger` configuration.
> 
> plugin_metedata is more like a General configuration, and it will work for all `kafka-logger` plugin.

感谢回复，这个方法我知道了哈，但是有另外一个疑问，因为如果按照这个方法来定义log_format，那么日志格式就完全按照定义的log_format来生成了，这里是一个覆盖模式，希望支持下增量模式，即我定义的字段只是append到默认的日志里面而不是直接覆盖。

比如 log_format 我定义为 `{"upstream_latency": $upstream_latency}`，那么最终日志格式希望是在默认日志的基础上，**增加**这个字段。

不知道我这样描述清楚了么？

**Comment by juzhiyuan** [comment]
Yes, it's clearly now :) (Just like PATCH and PUT methods 😄)

I found the default configuration here, see https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L35-L38

As for if we could support "PATCH" log_format, need @tzssangglass's confirmation.

**Comment by jagerzhang** [comment]
> Yes, it's clearly now :) (Just like PATCH and PUT methods 😄)
> 
> I found the default configuration here, see https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua#L35-L38
> 
> As for if we could support "PATCH" log_format, need @tzssangglass's confirmation.

Fantastic, looking forward to support.

**Comment by tzssangglass** [comment]
Not sure, haven't tried (I think in log_format as an attribute is the smallest unit of the PATCH operation. It should not be possible to continue the PATCH in the value of log_format.)

**Comment by jagerzhang** [comment]
激活下，已知可以将这2个变量添加到默认日志：https://github.com/apache/apisix/discussions/6010
