### ISSUE TITLE
request help: apisix how to use the service discovery with built-in etcd

### ISSUE THREAD

**Issue by xiaokunliu** [apache/apisix#5918]
### Issue description

now i have one requirement is that i want to use etcd to dicovery my upstream service, how to enable it

### Environment

for help: 
apisix how to use the service discovery with built-in etcd, now i have one requirement is that i want to use etcd to dicovery my upstream service, how to enable it

**Comment by tzssangglass** [comment]
same as https://github.com/apache/apisix/issues/5573

I will close it as it is a repeat issue.
