### ISSUE TITLE
request help: Infinitly "request": "HEAD / HTTP/1.0" Log

### ISSUE THREAD

**Issue by ameryhan** [apache/apisix#5922]
### Issue description

![image](https://user-images.githubusercontent.com/2375525/147344138-d687d594-db95-4207-8779-db94121a316d.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
pls give the reproduction steps
