### ISSUE TITLE
request help: How can I automatic extend token expiry with jwt auth on apisix ?

### ISSUE THREAD

**Issue by zhangxingdeppon** [apache/apisix#5930]
### Issue description

Hi, team, I'm a little confused about jwt auth, how can I automatic extend token expiry with jwt auth on apisix?  I have seen the office documents, but not fund any relevant content, could you give me some ideas? it's very important for me, thank you very much.

### Environment

- apisix version (cmd: `apisix version`): 2.10
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi @zhangxingdeppon, just to make sure, do you need the Token generated by Apache APISIX will automatically expand its Expiration time? 

According to https://jwt.io/, JSON Web Token is stateless and needs to be generated once it's expired. AFAIK, you may need to implement your logic with `access_token` & `refresh_token` to issue a new Token, see https://stackoverflow.com/questions/53946250/how-to-extend-the-expire-time-in-a-normal-access-token

What do you think, @leslie-tsang ?

**Comment by leslie-tsang** [comment]
> Hi @zhangxingdeppon, just to make sure, do you need the Token generated by Apache APISIX will automatically expand its Expiration time?
> 
> According to https://jwt.io/, JSON Web Token is stateless and needs to be generated once it's expired. AFAIK, you may need to implement your logic with `access_token` & `refresh_token` to issue a new Token, see https://stackoverflow.com/questions/53946250/how-to-extend-the-expire-time-in-a-normal-access-token
> 
> What do you think, @leslie-tsang ?

IMO, we **shouldn't change** the expiration time without permission[1][2], it defeats the **purpose** of the Token and makes it less reliable. It is best to refresh the token before it has expired.

[1] https://jwt.io/introduction/
[2] https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.4

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if need.

**Comment by zhangxingdeppon** [comment]
@leslie-tsang excellent, according to your advice, we decide to use external plugin to extend token expiry,  thanks very much,

**Comment by juzhiyuan** [comment]
Hi @zhangxingdeppon, glad to see you have other solutions 🥰 If needed, you could submit a PR to update the JWT plugin's doc, maybe others will also have the same question.
