### ISSUE TITLE
request help: gzip is not working on CentOS7

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#5931]
The gzip plugin is opened in the plug-in. The default configuration has not taken effect.

If an error is found, the prompt needs core log. error("need to build APISIX-OpenResty to support setting gzip")

Then I found it https://github.com/api7/apisix-nginx-module/tree/main/lib/resty/ Put it in the directory

An error is reported after restart. Normal after disabling the plug-in.

https://apisix.apache.org/docs/apisix/how-to-build

I installed CentOS 7 according to the above address

It mainly depends on good performance and convenient configuration. Just want to configure a gzip.

I haven't done much with servers, mainly java development. So I can't change anything.

After reading Lua's introduction, you can find what you need.
***I just want to use it, the functions of all plug-ins***

_Originally posted by @xlgo in https://github.com/apache/apisix/discussions/4919#discussioncomment-1868935_

**Comment by juzhiyuan** [comment]
cc @xlgo, just created an issue from your comment.

**Comment by xlgo** [comment]
这是要干啥？

**Comment by juzhiyuan** [comment]
Just created an issue to track your issue https://github.com/apache/apisix/discussions/4919#discussioncomment-1868935

**Comment by spacewander** [comment]
Answered in https://github.com/apache/apisix/discussions/4919#discussioncomment-1871921.
