### ISSUE TITLE
request help: why upstream.healthcheck_parent is route?

### ISSUE THREAD

**Issue by panhow** [apache/apisix#5935]
### Issue description

why upstream.healthcheck_parent is route?

checker:run will run after the object changed, but when i update a upstream, checker:clear(),checker:stop() are on route, route did not change, then the checker still checks the old upstream nodes?

### Environment

- apisix version (cmd: `apisix version`): 2.10
- OS (cmd: `uname -a`): Ubuntu 20.04 LTS 5.4.10 kernal
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Only when the upstream is a part of a route, the `upstream.healthcheck_parent` will be route.
In this case, changing the nodes is equal to changing the route.

If the upstream doesn't belong to a route, its parent will be itself. See https://github.com/apache/apisix/blob/db5813ff9ac2e77960af6c6ac3072eccee2057c7/apisix/upstream.lua#L501
https://github.com/apache/apisix/blob/db5813ff9ac2e77960af6c6ac3072eccee2057c7/apisix/upstream.lua#L447

**Comment by panhow** [comment]
thx, i thought this issue had already fixed,did not notice other changes
https://github.com/apache/apisix/pull/2747
