### ISSUE TITLE
request help: lose port if set Redirect  is enable on https

### ISSUE THREAD

**Issue by xlgo** [apache/apisix#5936]
### Issue description

redirect.lua   line 156

没有端口，如果不是默认的443 端口，就会出现问题
 修改 为   uri = "https://$host:9443$request_uri"       可以正常使用

### Environment

应该是那个版本都这样的问题吧。

### Steps to reproduce

无

### Actual result

无

### Error log

无

**Comment by leslie-tsang** [comment]
Hello there, AFAIK, you can define port in `$host` like `example.com:9443`

**Comment by leslie-tsang** [comment]
@xlgo Hello there, any update for this issue ?

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if need.
