### ISSUE TITLE
request help: I cant  conversion nginxconf to apisix 

### ISSUE THREAD

**Issue by hushaojun-0801** [apache/apisix#5937]
### Issue description

    map $host $province {
        ~^(anhuilogin)\.(baidu.com)$        "anhui";
		~^(beijinglogin)\.(baidu.com)$        "beijing";
    }    
    location ~* ^/(?<website>(A|B)) {
    proxy_pass http://prod.$province.$website;
    }
upstream prod.anhui.A {	
    server anhui-A;
}
upstream prod.anhui.B {	
    server anhui-B;
}
upstream prod.beijing.A {	
    server beijing-A;
}
upstream prod.beijing.B {	
    server beijing-B;
}

### Environment

- apisix version (cmd: `apisix version`): 2.7
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
You can match different conditions and distribute to different upstreams through the `vars` configuration in Route.

https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md#route

**Comment by hushaojun-0801** [comment]
ok,I will try it
