### ISSUE TITLE
docs: How to understand the internal working mechanism of apisix in depth

### ISSUE THREAD

**Issue by alex8224** [apache/apisix#5938]
### Improved or typo fixed.

In addition to looking at the source code directly, what other ways are there to detail the principles and workflow of apisix, including the parameters and callback functions that need to be used when writing the plug-in
The comments in the current code are still on the low side, and the development documentation is a bit lacking in depth, so there is still a high threshold for mastering apisix.

### Solution

Write advanced documentation, detailed documentation of principles, processes and interfaces

**Comment by shuaijinchao** [comment]
Please refer to the documentation in the directory `https://github.com/apache/apisix/tree/master/docs/en/latest/architecture-design`.

**Comment by alex8224** [comment]
@shuaijinchao Tks
This document has too little detail to be used as a development document

**Comment by tzssangglass** [comment]
Yes, we have discussed the need for plugin development documentation, but no one has contributed yet, and I will do this if I have time.

refer to: https://github.com/apache/apisix/discussions/5421

**Comment by alex8224** [comment]
@tzssangglass 
Thank you for your work

**Comment by juzhiyuan** [comment]
Maybe we could keep this issue open to tracking this improvement? @alex8224

**Comment by leslie-tsang** [comment]
Update: [mail list thread](https://lists.apache.org/thread/41zc5186lhg56okm8z5qxdo9rkt7f9t4), @alex8224
