### ISSUE TITLE
request help: How to build APISIX-OpenResty when I have deploy apisix  by the source code way

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix#5942]
### Issue description

 I have deploy apisix  by the source code way?

and  then  I  use the plugin  gzip, and that is a error like this :

2021/12/28 10:09:42 [error] 16285#16285: *7356922 [lua] gzip.lua:105: phase_func(): need to build APISIX-OpenResty to support setting gzip while reading response header from upstream

who can tell me  how to build the  APISIX-OpenResty? 
thanks!

### Environment

- apisix version (cmd: `apisix version`):2.11.0
- OS (cmd: `uname -a`):centos 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
Hello there, Answered in [#4919 (reply in thread)](https://github.com/apache/apisix/discussions/4919#discussioncomment-1871921).

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if need.

**Comment by juzhiyuan** [comment]
ok, I'm going to close.
