### ISSUE TITLE
request help: deploy apisix failed on K8s

### ISSUE THREAD

**Issue by hesh222** [apache/apisix#5946]
### Issue description

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2021/12/28 09:30:35 [emerg] 1#1: socket() [::]:9080 failed (97: Address family not supported by protocol)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
you can try: https://github.com/apache/apisix-helm-chart

and from the error.log, it seems that listen to ipv6 failed.

pls provide version, configuration, and reproduction steps.

**Comment by leslie-tsang** [comment]
Hello there, change `enable_ipv6: true` to `enable_ipv6: false` may help.

**Comment by hesh222** [comment]
感谢，修改enable_ipv6  为false 解决了此类问题
