### ISSUE TITLE
bug: /v1/healthcheck Sometimes no data is returned

### ISSUE THREAD

**Issue by gaobo0202** [apache/apisix#5953]
### Issue description

we use the / V1 / healthcheck interface of apisix to monitor alarms online, and false alarms will occur. The reason is that the /v1/healthcheck interface sometimes returns no data.
![飞书20211229-142059](https://user-images.githubusercontent.com/14210651/147633092-38fdb637-9b8d-41c2-83a4-65420bef0537.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.0
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

**Upstream configuration**
`{
  "nodes": [
    {
      "host": "10.2.1.183",
      "port": 8089,
      "weight": 10
    },
    {
      "host": "10.2.1.184",
      "port": 8089,
      "weight": 10
    }
  ],
  "timeout": {
    "connect": 3,
    "read": 60,
    "send": 30
  },
  "type": "roundrobin",
  "checks": {
    "active": {
      "concurrency": 10,
      "healthy": {
        "http_statuses": [
          200,
          302
        ],
        "interval": 1,
        "successes": 2
      },
      "http_path": "/health",
      "https_verify_certificate": true,
      "port": 8089,
      "timeout": 1,
      "type": "http",
      "unhealthy": {
        "http_failures": 5,
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "interval": 1,
        "tcp_failures": 2,
        "timeouts": 3
      }
    },
    "passive": {
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 5
      },
      "type": "http",
      "unhealthy": {
        "http_failures": 2,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 2,
        "timeouts": 7
      }
    }
  },
  "hash_on": "vars",
  "scheme": "http",
  "pass_host": "pass",
  "name": "cmdb-web"
}`

**Route configuration**
`{
  "cT": 0,
  "clusterId": 1,
  "createBy": 0,
  "desc": "",
  "enableWebsocket": false,
  "host": "cmdb-web.stage.sprucetec.com",
  "id": 1055,
  "methods": "[\"GET\",\"POST\",\"PUT\",\"DELETE\",\"PATCH\",\"HEAD\",\"OPTIONS\",\"CONNECT\",\"TRACE\"]",
  "name": "cmdb-web-spurcetec",
  "plugins": "{\"proxy-rewrite\":{\"disable\":false,\"host\":\"cmdb-web.stage.sprucetec.com\"},\"client-control\":{\"disable\":false,\"max_body_size\":10485760}}",
  "priority": 0,
  "status": 1,
  "uT": 1640696538832,
  "updateBy": 2,
  "updateTime": 1640696538832,
  "upstreamId": 1,
  "uris": "[\"/*\"]",
  "vars": "null"
}`

### Actual result

No result

### Error log

No Error log

**Comment by juzhiyuan** [comment]
hi @leslie-tsang could you please have a look?

**Comment by leslie-tsang** [comment]
@juzhiyuan Plz assign it to me.

**Comment by juzhiyuan** [comment]
Thanks!

**Comment by jagerzhang** [comment]
Reasonable design
https://github.com/apache/apisix/issues/5082
https://github.com/apache/apisix/issues/5379
https://github.com/apache/apisix/issues/5154

**Comment by tylitianrui** [comment]
it occur to me.  i  sorry  i  do  not  catch this design. 
The api  `/v1/healthcheck` is provided to get the health status  . After  sending  some requests , No data   is return   ,and only 
 sometimes  data  does .  how to handle when no data happens ?
<img width="1352" alt="截屏2022-01-05 下午1 06 46" src="https://user-images.githubusercontent.com/31768692/148163452-97012927-caba-4c3c-b397-7cc28e420f62.png">

**Comment by leslie-tsang** [comment]
> it occur to me. i sorry i do not catch this design. The api `/v1/healthcheck` is provided to get the health status . After sending some requests , No data is return ,and only sometimes data does . how to handle when no data happens ? <img alt="截屏2022-01-05 下午1 06 46" width="1352" src="https://user-images.githubusercontent.com/31768692/148163452-97012927-caba-4c3c-b397-7cc28e420f62.png">

Hello there, can you provide the steps to reproduce the issue ?

**Comment by whioue** [comment]
> > 它发生在我身上。抱歉，我没看懂这个设计。提供api`/v1/healthcheck`来获取健康状态。发送一些请求后，没有数据返回，只有有时数据才会返回。没有数据发生时如何处理？<img alt="截屏2022-01-05 下午1 06 46" width="1352" src="https://user-images.githubusercontent.com/31768692/148163452-97012927-caba-4c3c-b397-7cc28e420f62.png">
> 
> 您好，您能提供重现问题的步骤吗？

我也遇到了这种情况，有时不同的终端查询，有的终端能查到数据，有的终端查不到数据。我猜测的是会不会多个worker运行时这种情况会明显一些？只是猜测，但确实发生以上我说的这种情况，没有特别的复现方法，就按一般配置即可。

**Comment by whioue** [comment]
> @juzhiyuan 请分配给我。

我也遇到这种情况，有时不同的终端运行到这种情况查询，有的终端能查到数据，有的终端查不到数据。估计，但会发生以上我说的这种情况确实，没有特别的复现方法，就一般按配置启用。

**Comment by whioue** [comment]
> > 它发生在我身上。抱歉，我没看懂这个设计。提供api`/v1/healthcheck`来获取健康状态。发送一些请求后，没有数据返回，只有有时数据才会返回。没有数据发生时如何处理？<img alt="截屏2022-01-05 下午1 06 46" width="1352" src="https://user-images.githubusercontent.com/31768692/148163452-97012927-caba-4c3c-b397-7cc28e420f62.png">
> 
> 您好，您能提供重现问题的步骤吗？

我也遇到这种情况，有时不同的终端进行查询，有的终端能查到数据，有的终端查不到数据。我猜测的是apisix在多worker运行情况会复现概率大一些，只是猜测，但确实会发生以上我说的这种情况，没有特别的复现方法，就一般按配置启用。
