### ISSUE TITLE
usercase: golang toolkit-sync eureka/nacos instance info to apisix

### ISSUE THREAD

**Issue by anjia0532** [apache/apisix#5957]
### Improved or typo fixed.

my repo https://github.com/anjia0532/discovery-syncer

### Solution

my repo https://github.com/anjia0532/discovery-syncer

**Comment by anjia0532** [comment]
Different of [apisix discovery](https://apisix.apache.org/docs/apisix/discovery/nacos)/与官方[apisix discovery](https://apisix.apache.org/docs/apisix/discovery/nacos) 注册中心同步插件不同的几个点

1. support multiple nacos/eureka cluster/支持多个nacos/eureka集群
2. support [kong](https://konghq.com/install/#kong-community)/支持同步到[kong](https://konghq.com/install/#kong-community)
3. remove the instance from discovery(use cicd pipeline)/配合cicd(也可以不用)可以支持主动从注册中心将实例摘除
4. support [hot-reload config](https://github.com/anjia0532/discovery-syncer#api%E6%8E%A5%E5%8F%A3)/支持[热重载配置](https://github.com/anjia0532/discovery-syncer#api%E6%8E%A5%E5%8F%A3)(貌似apisix也支持)

[Inadequacy/不足之处](https://github.com/anjia0532/discovery-syncer#api%E6%8E%A5%E5%8F%A3):

1. 目前的同步任务是串行的，如果待同步的量比较大，或者同步时间窗口设置的特别小的情况下，会导致挤压

2. 不支持自定义同步插件，不利于自行扩展

3. 同步机制目前是基于定时轮询，效率比较低，有待优化，比如增加缓存开关，上游注册中心与缓存比对没有差异的情况下，不去拉取/变更下游网关的upstream信息，或者看看注册中心支不支持变动主动通知机制等。

**Comment by tzssangglass** [comment]
This is a huge change, have you sent a proposal to the mailing list before?

**Comment by anjia0532** [comment]
> This is a huge change, have you sent a proposal to the mailing list before?

No,its not change,this is a toolkit.
