### ISSUE TITLE
request help: How to modify apisix response using custom plugins

### ISSUE THREAD

**Issue by baoqian-zhang** [apache/apisix#5967]
### Issue description

遇到的问题：我想要写一个go插件将apisix转发给业务服务后的响应改写（逻辑是：进行i18n国际化，还需要连接redis）； 但是apisix提供拓展的ext-plugin*插件是在access或者rewrite阶段执行的， 并没有在filter_body阶段执行， 这里我需要怎么做？

### Environment

- apisix version (cmd: `apisix version`): 2.9
- OS (cmd: `uname -a`): cent7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by zhangbaoqian** [comment]
我修改了ext-plugin*插件的代码， 让他在filter_body阶段执行， 但是会报连接错误， 好像是openresty机制不让在filter_body建立连接

**Comment by tokers** [comment]
Yes, the `body_filter` phase is not yieldable.

**Comment by zhangbaoqian** [comment]
body_filter阶段应该是不能创建同步连接， 如果创建异步连接又不能满足我的需求

**Comment by tzssangglass** [comment]
AFAIK, it is not yet supported.
