### ISSUE TITLE
Hope to add support for setting the custom host header to be used for upstream's artive checks!

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#5969]
### Issue description

I used the domain name in the node of my upstreams.During the health check, apisix converted the domain to ip, and did not bring the host to the backend, which resulted in unrecognition, the health check failed, and the traffic failed to be distributed as expected.

![image](https://user-images.githubusercontent.com/10955441/147753829-6c838d5a-11aa-41be-ab39-b790d32d80fa.png)
![image](https://user-images.githubusercontent.com/10955441/147753946-d3050be1-054e-4a87-bffd-028a46e956af.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):centos 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):3.4
- apisix-dashboard version, if have:no
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):no
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):3.4

**Comment by tzssangglass** [comment]
@sandy420  You can hint that the health check endpoint only accepts domain access, not ip access.

**Comment by sandy420** [comment]
> @sandy420 You can hint that the health check endpoint only accepts domain access, not ip access.

how do it ? @tzssangglass

**Comment by tzssangglass** [comment]
> > @sandy420 You can hint that the health check endpoint only accepts domain access, not ip access.
> 
> how do it ? @tzssangglass

What I mean is that you could have indicated in the issue that your upstream service only accepts domain name access, thus raising the issue.

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/5175?

**Comment by tzssangglass** [comment]
@sandy420 pls check this.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
