### ISSUE TITLE
is Apache APISIX supports mTLS?

### ISSUE THREAD

**Issue by XuZhaoPro** [apache/apisix#5973]
### Issue description

有个场景，需要服务器对客户端也做认证，目前APISIX是否支持？

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
yes, and you need to use apisix-base.

**Comment by juzhiyuan** [comment]
Hi @XuZhaoPro, we have a documentation site here https://apisix.apache.org/docs/apisix/mtls/#mtls-between-apisix-and-upstream

**Comment by XuZhaoPro** [comment]
My problem is that apisix certify a client which send request ，it means only some special clients can visit apisix. Not apisix certify upstremas.

**Comment by juzhiyuan** [comment]
> My problem is that apisix certify a client which send request ... Not apisix certify upstremas ... And I found that apisix supports client.ca in ssl(admin api document), is that what I need?

I think so 🤔 cc @tzssangglass

**Comment by tzssangglass** [comment]
apisix supports 
1. [mTLS between client and apisix](https://github.com/apache/apisix/blob/master/docs/en/latest/certificate.md
); 
2. [mTLS between apisix and upstream](https://github.com/apache/apisix/blob/master/docs/en/latest/mtls.md#mtls-between-apisix-and-upstream)
3. mTLS for admin api;
4. mTLS between apisix and etcd;
