### ISSUE TITLE
request help: remove unused utils script

### ISSUE THREAD

**Issue by leslie-tsang** [apache/apisix#5976]
### Issue description

Currently, some utility scripts no longer fit the master branch and we should remove them to make sure no one gets confused.

## Solution
> remove unused utils script

* ~~[utils/check-version.sh](https://github.com/apache/apisix/blob/master/utils/check-version.sh) - no longer been used.~~ (used in[https://apisix.apache.org/docs/general/release-guide](https://apisix.apache.org/docs/general/release-guide#make-source-code-package-and-upload-to-apache-svn))
* [utils/gen-install-folder.sh](https://github.com/apache/apisix/blob/master/utils/gen-install-folder.sh) - no longer been used, don't work as expect as well.
* [utils/install_yaml_conf.sh](https://github.com/apache/apisix/blob/master/utils/install_yaml_conf.sh) - no longer been used, [Makefile](https://github.com/apache/apisix/blob/master/Makefile) don't refer to it any more.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
Good. Can we cc the authors of these scripts?

**Comment by leslie-tsang** [comment]
cc @membphis @nic-chen

**Comment by membphis** [comment]
> utils/check-version.sh - no longer been used.

it is useful. 

![image](https://user-images.githubusercontent.com/6814606/147820310-5334fb44-ab5b-4fa7-9cf9-6af9dd226983.png)


> utils/gen-install-folder.sh - no longer been used, don't work as expect as well.
> utils/install_yaml_conf.sh - no longer been used, Makefile don't refer to it any more.

I do not know.

**Comment by leslie-tsang** [comment]
> 

I see. Thanks @membphis

**Comment by zaunist** [comment]
Hi, community. I'm glad to contribute this issue. I want to confirm that `utils/gen-install-folder.sh` and `utils/install_yaml_conf.sh` been removed exactly ?

**Comment by membphis** [comment]
I think the answer is YES. @zaunist welcome to make a try ^_^
