### ISSUE TITLE
request help: routed again after cutting off the path

### ISSUE THREAD

**Issue by yourgracee** [apache/apisix#5981]
### Issue description

我按照官网文档FAQ中的方法剪除路径：
![image](https://user-images.githubusercontent.com/18047268/147808855-b845ce25-0fb6-454b-8dbf-d4285fa573e6.png)
但是我还有一条路由规则是针对/bar的，因此再次被路由到不正确的服务，请问如何配置？

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
please provide specific cases and steps to reproduce.

**Comment by yourgracee** [comment]
1.配置一条/foo/bar 改写为 /foo的路由正则改写，绑定后端A服务
2.配置一条为/foo的路径重定向到其他服务，绑定后端B服务
3.访问/foo/bar
4.本应该跳转到A服务，结果跳转到B服务

**Comment by yourgracee** [comment]
> please provide specific cases and steps to reproduce.
1.配置一条/foo/bar 改写为 /foo的路由正则改写，绑定后端A服务
2.配置一条为/foo的路径重定向到其他路径，绑定后端B服务
3.访问/foo/bar
4.本应该跳转到A服务，结果跳转到B服务

**Comment by shuaijinchao** [comment]
according to your description, I cannot reproduce this problem.

---

![image](https://user-images.githubusercontent.com/8529452/147813018-119c2931-9a62-4521-ad8c-0537e9ce1d94.png)

**Comment by yourgracee** [comment]
> according to your description, I cannot reproduce this problem.
> 
> ![image](https://user-images.githubusercontent.com/8529452/147813018-119c2931-9a62-4521-ad8c-0537e9ce1d94.png)

第二步配置不是正则改写，而是重定向
{
  "uri": "/bar",
  "name": "api-redirector",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "redirect": {
      "ret_code": 301,
      "uri": "/bar/"
    }
  },
  "status": 1
}

**Comment by shuaijinchao** [comment]
Please reproduce the problem 100% locally and submit all test configurations.

---

![image](https://user-images.githubusercontent.com/8529452/148043810-7bedaff8-ba97-421c-b430-b5f7bf265f96.png)
