### ISSUE TITLE
request help: Configure https upstream, keep reporting error 401

### ISSUE THREAD

**Issue by tiyorn** [apache/apisix#5983]
### Issue description

上游配置为https，一直报401，怀疑跟ssl有关系。请问APISIX转发https请求至上游的时候，是否会受到SSL certificate verification的干扰，有没有开关可以关闭SSL certificates verify

### Environment

- apisix version (cmd: `apisix version`):2.9
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
proxy https request need enable `ssl.ssl_trusted_certificate`, but the response 401 should not be the reason for https

**Comment by tokers** [comment]
You can use the same way to access your upstream directly, without the intervention of APISIX.

**Comment by tiyorn** [comment]
> You can use the same way to access your upstream directly, without the intervention of APISIX.

I have tried it and it is ok, but not after going through the apisix, only 401 is prompted in access.log.

**Comment by zaunist** [comment]
Hi, @tiyorn. Have you set the upstream schema ? If you want to forward https request, you need set the upstream schema to `https`. Ref  https://apisix.apache.org/zh/docs/apisix/admin-api#body-%E8%AF%B7%E6%B1%82%E5%8F%82%E6%95%B0-3
![image](https://user-images.githubusercontent.com/38528079/147822156-42a125ce-f1ff-42c6-83d4-d6f341da5c3e.png)

**Comment by tiyorn** [comment]
End the problem, this is caused by the interception of the upstream business layer, and has nothing to do with apisix. Thank you everyone.

**Comment by juzhiyuan** [comment]
ok, considered resolved :)
