### ISSUE TITLE
request help: Where Can I Find More APISIX Variables ?

### ISSUE THREAD

**Issue by artemus717** [apache/apisix#5990]
### Issue description

I want to define my own log format. But I can't find enough APISIX Variables. I only find this:https://apisix.apache.org/docs/apisix/plugins/kafka-logger

Where Can I Find More APISIX Variables ?

### Environment

- apisix version (cmd: `apisix version`): 2.11.0

Using Official Docker Image.

**Comment by tokers** [comment]
There are a lot of variables from Nginx itself, I think the [Variable Index Doc](http://nginx.org/en/docs/varindex.html) is a good place.

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/147912974-24724011-4f29-4f8a-9e24-8f56caf50a76.png)

Hi @artemus717, here has the hyperlink to Nginx vars, may I know if it's hidden too deep to notice this?

**Comment by spacewander** [comment]
@artemus717 
Listed in https://github.com/apache/apisix/pull/5997/files

**Comment by artemus717** [comment]
> Variable Index Doc

Thanks a lot . I konw I can use nginx variables . But I want to konw is there any  other APISIX Variables . For example  i want to put route path to log file , i can only find requset uri . In my opinion , route path should be an APISIX Variable .
