### ISSUE TITLE
request help: How to maintain TCP long links using APISIX

### ISSUE THREAD

**Issue by BoyK** [apache/apisix#5991]
### Issue description

Business links are as follows：

      Client <-----tcp long link----> APISIX <-------> Services

How can I achieve it ?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by zaunist** [comment]
cc @tzssangglass

**Comment by tokers** [comment]
@BoyK Hi, maybe you can learn the stream proxy functionality, see https://apisix.apache.org/docs/apisix/stream-proxy/ for details.

**Comment by BoyK** [comment]
> @BoyK Hi, maybe you can learn the stream proxy functionality, see https://apisix.apache.org/docs/apisix/stream-proxy/ for details.

tks
