### ISSUE TITLE
request help: logger plugins supports report custom labels of route

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#5998]
### Issue description
如图，为了方便管理，我们这边会给每个路由自定义系统和应用的标签。希望各日志插件能将这个标签也记录一下，方便在日志分析时和业务做快捷的对应。
![image](https://user-images.githubusercontent.com/9711651/147999207-8ac9cddc-d4e1-464a-aff9-1a563c47ec97.png)

目前在用 kafka-logger ，望优先支持~~感谢。

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`): docker-centos

**Comment by tzssangglass** [comment]
useful

**Comment by spacewander** [comment]
Solved by https://github.com/apache/apisix/pull/5941

**Comment by tzssangglass** [comment]
#5941 just privode `register_var` function, not implemented in the logger plugin code?

**Comment by jagerzhang** [comment]
> #5941 just privode `register_var` function, not implemented in the logger plugin code?

确实没有在日志插件中实现，我参考这个写法自己试了下，发现`ctx.matched_route.value`里面并没有labels相关内容，代码如下：
```
    local route = ctx.matched_route and ctx.matched_route.value
    core.log.info("route.value: ", core.json.delay_encode(route))  # 这里输出我看了下，里面是没有路由自定义标签的。
    if route and route.labels then
        entry.route = {}
        entry.route.labels = route.labels
    end
```

**Comment by spacewander** [comment]
I demonstrate how to use it in https://github.com/apache/apisix/pull/6163

**Comment by jagerzhang** [comment]
> I demonstrate how to use it in #6163

嗯，当我改造kafka-logger的时候，发现了一个bug，已提issue: https://github.com/apache/apisix/issues/6169
