### ISSUE TITLE
request help: the cors plugin does not force the use of expose_headers

### ISSUE THREAD

**Issue by fish2018** [apache/apisix#6003]
### Issue description

cors插件会开启expose_headers参数，
`expose_headers: "*" `  会触发ios12的bug。
或者就要列出所有的headers，有很多自定义的headers时就会变得很麻烦

### Environment

---

**Comment by spacewander** [comment]
Could you provide more details so we can assess the severity?
Normally we prefer to follow the standard, even some clients don't.

Maybe a few months later, the majority of iOS 12 users will accept a patch and upgrade their software.

If this is critical to you, you can fork and modify cors plugin, and add a workaround by yourself.
