### ISSUE TITLE
Proposal: support Forward Auth authenticate plugin

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#6007]
## Background

Forward Auth cleverly moves the authentication and authorization logic to a dedicated external service, where the gateway forwards the user's request to the authentication service and blocks the original request and replaces the result when the authentication service responds with a non-20x state. In this way, we can achieve a custom error return or user redirection to the authentication page if the authentication fails.

### Configure schema

Name | Type | Requirement | Default | Description
-- | -- | -- | -- | --
host | string | required |   | Auth service host (eg. https://localhost:8999)
ssl_verify | boolean | optional | true | Whether to verify the certificate
request_headers | array | optional | [] | Request headers allowed to be forwarded
response_headers | array | optional | [] | Response headers allowed to be returned

### Implementation

Through the plugin, part of the requested information is forwarded to the authentication service during the access phase, which will transmit the following information by way of a request header.

Method | Schema | Domain | Path | Source IP
-- | -- | -- | -- | --
X-Forwarded-Method | X-Forwarded-Proto | X-Forwarded-Host | X-Forwarded-Uri | X-Forwarded-For

At the same time, the request headers will be forwarded according to the list of request headers set in the `request_headers` in the configuration, if not set, all request headers will be forwarded. After the authentication service response, if the response code is 20x, the request will be forwarded upstream normally, otherwise the response of the authentication service will be forwarded to the client, and the response headers will be filtered using `response_headers`.

## Other
What are your ideas?

**Comment by tokers** [comment]
1. Does the `X-Forwarded-Uri` header contains the query string?
2. I think a field like allowed_status_code should return, so that we can distinguish the situation that it's indeed forbidden or just caused by other reasons (so that we may apply the degradation).

**Comment by bzp2010** [comment]
Hi, @tokers.

1. It should instead contain the query string, should I add an extra key for that?
`X-Forwarded-Uri: /headers?test=test`

2. As an authentication service, it needs to return a default rejection response and write to the log in case of its failure. I don't have a good solution for this part yet to distinguish between normal rejection and service degradation, so I hope you will give me more suggestions.

**Comment by tokers** [comment]
> Hi, @tokers.
> 
> 1. It should instead contain the query string, should I add an extra key for that?
>    `X-Forwarded-Uri: /headers?test=test`
> 2. As an authentication service, it needs to return a default rejection response and write to the log in case of its failure. I don't have a good solution for this part yet to distinguish between normal rejection and service degradation, so I hope you will give me more suggestions.

1. I think it's good enough, we don't have to add another field;
2. We may don't have to do this in the first MVP version but we should consider such a demand, what about adding the filed `reject_codes`, and when this field is missing, by default all non-2xx status codes will be treated as rejection. Let's also see other guys' idea :)

**Comment by spacewander** [comment]
After reading https://doc.traefik.io/traefik/middlewares/http/forwardauth/, it seems the authResponseHeaders in that plugin is different from the one in the proposal.

> The authResponseHeaders option is the list of headers to copy from the authentication server response and set on forwarded request, replacing any existing conflicting headers.

Those headers are used to set on forwarded request.

To make thing clear, maybe we can use `upstream_headers` and `client_headers`, like this one in Envoy:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-authorizationresponse

Another question, what if the request already has `X-Forwarded-XX` header?

**Comment by tzssangglass** [comment]
> Another question, what if the request already has `X-Forwarded-XX` header?

I think the ideal way to do this is to have the plugin act on a specific route that only matches requests that require Forward Auth.

However this design goes against the existing plugin design ......

**Comment by bzp2010** [comment]
> To make thing clear, maybe we can use upstream_headers and client_headers, like this one in Envoy:
https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/ext_authz/v3/ext_authz.proto#extensions-filters-http-ext-authz-v3-authorizationresponse

I think this is a clear way to do it, but it can be confusing to users when configuring and I need to highlight these configurations in the documentation.

> Another question, what if the request already has X-Forwarded-XX header?

According to the scheme used in traefik, which is designed with the `trustForwardHeader` configuration, it will trust the header passed in by the client, do we need to do this? If not, these headers passed in by the client will be discarded by default.

**Comment by spacewander** [comment]
> but it can be confusing to users when configuring and I need to highlight these configurations in the documentation

To me, the Envoy way is more clear. Could you explain the "confusing"?

> do we need to do this

We can skip it in the first version.
