### ISSUE TITLE
request help:  add real-ip plugin failed， logs get error

### ISSUE THREAD

**Issue by ccwall3** [apache/apisix#6009]
### Issue description

![image](https://user-images.githubusercontent.com/7711718/148146596-96100265-7dbd-4cbf-ba8e-12a91d946499.png)

2022/01/04 18:05:17 [error] 24003#24003: *79260034 [lua] real-ip.lua:103: phase_func(): need to build APISIX-OpenResty to support setting real ip, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/query HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"
2022/01/04 18:05:17 [warn] 24003#24003: *79260034 [lua] plugin.lua:658: run_plugin(): real-ip exits with http status code 501, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/query HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"
2022/01/04 18:05:17 [error] 24003#24003: *79260035 [lua] real-ip.lua:103: phase_func(): need to build APISIX-OpenResty to support setting real ip, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/queryUser HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"

apisix already exist, logs tell need to build apisix-openresy, idont  know  how  to  repair it 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by zaunist** [comment]
Hi, @ccwall3. Could you please provide your apisix version、dashboard version and operation system version?

**Comment by leslie-tsang** [comment]
Hello there, Plz take a look of [#4919 (reply in thread)](https://github.com/apache/apisix/discussions/4919#discussioncomment-1871921).

**Comment by ccwall3** [comment]
> 
apisix  version	2.9
dashboard_version  2.8
centos 7.9


</div></div></div><div class="ant-card" style="box-sizing: border-box; margin: 0px; padding: 0px; color: rgba(0, 0, 0, 0.85); font-size: 14px; font-variant: tabular-nums; line-height: 1.5715; list-style: none; font-feature-settings: &quot;tnum&quot;, &quot;tnum&quot;; position: relative; background: rgb(255, 255, 255); border-radius: 2px; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, &quot;Helvetica Neue&quot;, Arial, &quot;Noto Sans&quot;, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="ant-card-head" style="box-sizing: border-box; min-height: 48px; margin-bottom: -1px; padding: 0px 24px; color: rgba(0, 0, 0, 0.85); font-weight: 500; font-size: 16px; background: transparent; border-bottom: 1px solid rgb(240, 240, 240); border-radius: 2px 2px 0px 0px;"><div class="ant-card-head-wrapper" style="box-sizing: border-box; display: flex; align-items: center;"><br class="Apple-interchange-newline">
</body>
</html>


> Hi, @ccwall3. Could you please provide your apisix version、dashboard version and operation system version?

**Comment by ccwall3** [comment]
>


> > 
> 
> apisix version 2.9 dashboard_version 2.8 centos 7.9
> 
>  is that means  the answer is  using the apisix-nginx-module?(https://github.com/api7/apisix-nginx-module)
> > Hi, @ccwall3. Could you please provide your apisix version、dashboard version and operation system version?

**Comment by ccwall3** [comment]
> Hello there, Plz take a look of [#4919 (reply in thread)](https://github.com/apache/apisix/discussions/4919#discussioncomment-1871921).

error.log:2022/01/06 19:18:24 [warn] 8872#8872: *45690 [lua] real-ip.lua:121: phase_func(): missing real address, client: 10.8.171.254, server: _, request: "GET /backend-auth/login HTTP/1.1", host: "devapi.meomeopet.com"

**Comment by tzssangglass** [comment]
> missing real address

This means that there is no `X-Forwarded-For` in your request headers.

**Comment by leslie-tsang** [comment]
> 2022/01/04 18:05:17 [error] 24003#24003: *79260034 [lua] real-ip.lua:103: phase_func(): need to build APISIX-OpenResty to support setting real ip, client: 10.8.171.254, server: _, request: "POST /backend-auth/dept/query HTTP/1.1", host: "devapi.meomeopet.com", referrer: "http://localhost:8000/auth/department"

This require APISIX-OpenResty to support this feature. More detail refer to [how-to-build](https://apisix.apache.org/docs/apisix/how-to-build/#step-6-build-openresty-for-apache-apisix)

> error.log:2022/01/06 19:18:24 [warn] 8872#8872: *45690 [lua] real-ip.lua:121: phase_func(): missing real address, client: 10.8.171.254, server: _, request: "GET /backend-auth/login HTTP/1.1", host: "devapi.x.com"

This mean that `real-ip` plugin can't find the HTTP header `X-Forwarded-For` in the request.

Can you show a curl-formatted request to reproduce the issue ?

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.
