### ISSUE TITLE
request help: routing matching rule of radixtree

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#6019]
### Issue description

I have the following list of paths：
1. /api/a/math/a
2. /api/math/a
3. /api/math-aaa

the path rule I configured is `/*/math*`,  but not work

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
As the radixtree uses prefix match, it can't handle the case that both head and tail are wildcards.
You can match it with regex: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-use-route-uri-for-regular-matching
