### ISSUE TITLE
bug: in Orchestration, OpenID-Connect Plug-in Properties Timeout does not set, there will be an error

### ISSUE THREAD

**Issue by mrzxy** [apache/apisix#6021]
### Issue description

```json
// plugins setting
{
  "bearer_only": true,
  "client_id": "gw",
  "client_secret": "0a1c2496-bf4f-47ee-83e4-db1b5839cad9",
  "disable": false,
  "discovery": "http://192.168.102.12:8080/auth/realms/test/.well-known/openid-configuration",
  "realm": "test"
}
```

View source code according to error prompts:
![image](https://user-images.githubusercontent.com/11501927/148174809-aef6b0d9-0ec2-403e-87bc-1d770939660a.png)

timeout is required?

### Environment

- apisix version: v2.11.0
- OS: Linux apisix-5547d6477b-tqmg8 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 Linux
- OpenResty / Nginx version ): openresty/1.19.3.2

### Steps to reproduce

1. create router
![image](https://user-images.githubusercontent.com/11501927/148320190-951ec7c9-fafa-4e54-b717-d8b5f74305ea.png)
2. set upstream 
![image](https://user-images.githubusercontent.com/11501927/148320207-b84c731c-2587-4f6e-8507-0f8a449260aa.png)
3. set openid-connect plugins 
![image](https://user-images.githubusercontent.com/11501927/148320238-d04cd94c-b81f-4561-be7d-cbfdf6ad00da.png)

```json
// plugins setting
{
  "bearer_only": true,
  "client_id": "gw",
  "client_secret": "0a1c2496-bf4f-47ee-83e4-db1b5839cad9",
  "disable": false,
  "discovery": "http://192.168.102.12:8080/auth/realms/test/.well-known/openid-configuration",
  "realm": "test"
}
```

### Actual result

![image](https://user-images.githubusercontent.com/11501927/148178356-e0e33e3d-8574-4798-8fd6-182c1e5a6a60.png)

### Error log

![image](https://user-images.githubusercontent.com/11501927/148174750-9fd12aa2-6364-4a63-ba8d-21c9e1656d5e.png)

**Comment by tzssangglass** [comment]
`conf.timeout` has default value, see: https://github.com/apache/apisix/blob/3f66fab63ecffa7bf4d5bdb02ce8a688a4285709/apisix/plugins/openid-connect.lua#L41-L46

can you add a log like this:

```diff
diff --git a/apisix/plugins/openid-connect.lua b/apisix/plugins/openid-connect.lua
index 1c8d78c1..085581c8 100644
--- a/apisix/plugins/openid-connect.lua
+++ b/apisix/plugins/openid-connect.lua
@@ -240,6 +240,7 @@ function _M.rewrite(plugin_conf, ctx)
 
     -- Previously, we multiply conf.timeout before storing it in etcd.
     -- If the timeout is too large, we should not multiply it again.
+    ngx.log(ngx.WARN, "conf : ", require("inspect")(conf))
     if not (conf.timeout >= 1000 and conf.timeout % 1000 == 0) then
         conf.timeout = conf.timeout * 1000
     end
diff --git a/t/toolkit b/t/toolkit
index ab2471cc..94f471d3 160000
--- a/t/toolkit
+++ b/t/toolkit
@@ -1 +1 @@
-Subproject commit ab2471cc9cbeec6fe605120160eeb9dd17ddda2c
+Subproject commit 94f471d3a9045667bc1f1784a21f89315cd64f7e
```

And you need to provide more complete reproduction of the steps

**Comment by mrzxy** [comment]
> `conf.timeout` has default value, see:
> 
> https://github.com/apache/apisix/blob/3f66fab63ecffa7bf4d5bdb02ce8a688a4285709/apisix/plugins/openid-connect.lua#L41-L46
> 
> can you add a log like this:
> 
> ```diff
> diff --git a/apisix/plugins/openid-connect.lua b/apisix/plugins/openid-connect.lua
> index 1c8d78c1..085581c8 100644
> --- a/apisix/plugins/openid-connect.lua
> +++ b/apisix/plugins/openid-connect.lua
> @@ -240,6 +240,7 @@ function _M.rewrite(plugin_conf, ctx)
>  
>      -- Previously, we multiply conf.timeout before storing it in etcd.
>      -- If the timeout is too large, we should not multiply it again.
> +    ngx.log(ngx.WARN, "conf : ", require("inspect")(conf))
>      if not (conf.timeout >= 1000 and conf.timeout % 1000 == 0) then
>          conf.timeout = conf.timeout * 1000
>      end
> ```
> 
> And you need to provide more complete reproduction of the steps

I can't debug, because I am not familiar with Lua, but I perfect the process of recovery.
