### ISSUE TITLE
bug: build openresty fail

### ISSUE THREAD

**Issue by gaobo0202** [apache/apisix#6028]
### Issue description

I build the openresty used the sh file like this https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base-debug-centos7.sh and https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh.
I saw that other issues mentioned such problems, so I upgraded the OpenSSL version and tried 1.1.1, 1.1.1m and 1.1.1i. The problem remained the same.
![image](https://user-images.githubusercontent.com/14210651/148224497-93272c6d-c1da-4ca2-8849-e6333f9c316f.png)

### Environment

- apisix version (cmd: `apisix version`):2.10.1.1
- OS (cmd: `uname -a`):centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

sh build-apisix-base-debug-centos7.sh

### Actual result

compilation failed

### Error log

-L/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/luajit-root/usr/local/openresty-debug/luajit/lib -L/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/luajit-root/usr/local/openresty-debug/luajit/lib -Wl,-rpath,/usr/local/openresty-debug/luajit/lib -Wl,-rpath,/usr/local/openresty-debug/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty-debug/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty-debug/openssl111/lib -Wl,--require-defined=pcre_version -Wl,-E -Wl,-E -ldl -lpthread -lpthread -lcrypt -L/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/luajit-root/usr/local/openresty-debug/luajit/lib -lluajit-5.1 -lm -ldl -L/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/luajit-root/usr/local/openresty-debug/luajit/lib -lluajit-5.1 -lm -ldl -lstdc++ -lpcre -lssl -lcrypto -ldl -lpthread -lz \
-Wl,-E
objs/addon/src/ngx_http_apisix_module.o：在函数‘ngx_http_apisix_x509_copy’中：
/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/../apisix-nginx-module/src/ngx_http_apisix_module.c:95：对‘X509_up_ref’未定义的引用
objs/addon/src/ngx_http_apisix_module.o：在函数‘ngx_http_apisix_upstream_set_cert_and_key’中：
/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/../apisix-nginx-module/src/ngx_http_apisix_module.c:186：对‘EVP_PKEY_up_ref’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [objs/nginx] 错误 1
make[2]: 离开目录“/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/nginx-1.19.9”
make[1]: *** [build] 错误 2
make[1]: 离开目录“/tmp/tmp.kG7BAbXESf/openresty-1.19.9.1/build/nginx-1.19.9”
make: *** [all] 错误 2

**Comment by tzssangglass** [comment]
same as #4912

**Comment by tzssangglass** [comment]
> so I upgraded the OpenSSL version and tried

just from the phenomena, it seems that you have updated it in the wrong way.

**Comment by tzssangglass** [comment]
and take a look at:https://github.com/apache/apisix/issues/5166#issuecomment-966902008

**Comment by gaobo0202** [comment]
> and take a look at:[#5166 (comment)](https://github.com/apache/apisix/issues/5166#issuecomment-966902008)

I have tried to use apifix build tools to produce the compilation environment, but the following error is reported. The execution command is 'make package type=rpm app=apisix-base version=1.0.0 image_base=centos image_tag=7'

![111](https://user-images.githubusercontent.com/14210651/148321140-b6c4e3dc-c6d1-4e51-82a3-0713351c018f.png)

**Comment by spacewander** [comment]
Closed as duplicated
