### ISSUE TITLE
discuss: It is not inappropriate using “apisix”  type for prometheus metrics（count first bytes from client）

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#6029]
### Issue description

Because the `apisix_latency` include read contents from client, not ONLY apisix process time. It is very confused on the  dashbord and got resault that apisix lead  to high latency.
https://github.com/apache/apisix/blob/aff5d825aaea12eab312e65e82d060ab9be9b06f/apisix/utils/log-util.lua#L189
https://github.com/apache/apisix/blob/aff5d825aaea12eab312e65e82d060ab9be9b06f/apisix/plugins/prometheus/exporter.lua#L164

![image](https://user-images.githubusercontent.com/88528414/148322377-1f97f484-0e66-4f98-a022-0eb4ef17f59b.png)

### Environment

- apisix version (cmd: `apisix version`): master branch
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

I suggest use "apisix-and-client" type.

### Actual result

nil

### Error log

nil

**Comment by spacewander** [comment]
Yes, people often found that the APISIX latency is high caused by slow clients. But changing the type will be a break change.

What about adding a note in the doc: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md?

**Comment by zhendongcmss** [comment]
@spacewander Add notes on doc is easy. But it doesn't dispel confused. See the Grafana dashboard persion is different with seening the document.

**Comment by tzssangglass** [comment]
I prefer break change to make the metrics clearer, but of course, we need the mailing list to discuss that.

**Comment by xianshun163** [comment]
@zhendongcmss @tzssangglass 

Because the `apisix_latency` include read contents from client, not ONLY apisix process time.
do you  mean read contents from client cost a  lot of time?   Why does it take so much time in  read data.


> ### Issue description
> Because the `apisix_latency` include read contents from client, not ONLY apisix process time. It is very confused on the dashbord and got resault that apisix lead to high latency.
> 
> https://github.com/apache/apisix/blob/aff5d825aaea12eab312e65e82d060ab9be9b06f/apisix/utils/log-util.lua#L189
> 
> 
> https://github.com/apache/apisix/blob/aff5d825aaea12eab312e65e82d060ab9be9b06f/apisix/plugins/prometheus/exporter.lua#L164
> 
> ![image](https://user-images.githubusercontent.com/88528414/148322377-1f97f484-0e66-4f98-a022-0eb4ef17f59b.png)
> 
> ### Environment
> * apisix version (cmd: `apisix version`): master branch
> * OS (cmd: `uname -a`):
> * OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
> * etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
> * apisix-dashboard version, if have:
> * the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
> * luarocks version, if the issue is about installation (cmd: `luarocks --version`):
> 
> ### Steps to reproduce
> I suggest use "apisix-and-client" type.
> 
> ### Actual result
> nil
> 
> ### Error log
> nil
> 
> ### Expected result
> _No response_

**Comment by tzssangglass** [comment]
> do you mean read contents from client cost a lot of time? Why does it take so much time in read data.

For example, in file upload scenario, it takes a long time to read the data from the client

**Comment by xianshun163** [comment]
Yes, I found that although QPS is not high, but  there is file transfer
