### ISSUE TITLE
request help: when use skywalking,found error

### ISSUE THREAD

**Issue by zjzwjcbj** [apache/apisix#6042]
### Issue description
The skywalking version is 6.6.0
when i add skywalking endpoint  xxx:12800  ,found error : client.lua:114: reportServiceInstance(): Instance report fails, response code 405, context: ngx.timer

when add endpoint   xxx:11800,found :client.lua:109: reportServiceInstance(): Instance report fails, closed, context: ngx.timer.

### Environment

- apisix version (cmd: apisix version):2.10.0
- OS (cmd: uname -a):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux
- OpenResty / Nginx version (cmd: nginx -V or openresty -V):openresty/1.19.3.1
- etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API):3.4.16
- apisix-dashboard version, if have:2.9.0
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: luarocks --version):

**Comment by tzssangglass** [comment]
According to this: https://github.com/apache/skywalking-nginx-lua#download, maybe 6.x is too old.

cc @dmsolr
