### ISSUE TITLE
request help: APISIX-2.11 RPM installation error

### ISSUE THREAD

**Issue by XW512** [apache/apisix#6043]
### Issue description

When I installed APISIX-2.11 with RPM, the following error occurred
error: Failed dependencies:
        apisix-base >= 1.19.3.2.2 is needed by apisix-2.11.0-0.el7.x86_64

but,It can be installed normally with APISIX-2.10
Do I lack any bags？

### Environment

- apisix version (cmd: `apisix version`):  2.11
- OS (cmd: `uname -a`):  centOS7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
1. additional installation steps.
2. have you installed apisix-base?

**Comment by XW512** [comment]
> 1. additional installation steps.
> 2. have you installed apisix-base?

It is install_dependencies under util sh?but,If I don't have a network, is there a problem,Why doesn't the 2.10 version need this

**Comment by tzssangglass** [comment]
here: https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-repositorycentos-7

we can install apisix and apisix-base easily by this repo.

> Why doesn't the 2.10 version need this

2.10 version is also need this.

You need a full description of

1. how to install apisix-base
2. how to install apisix v2.10.0

**Comment by XW512** [comment]
> 

OK，I'll take a look at it again

>

**Comment by XW512** [comment]
> 

OK，I'll take a look at it again

**Comment by leslie-tsang** [comment]
Hello there, please try [this](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-offline-packagecentos-7). 
Do let me know if you need any help with it.

**Comment by leslie-tsang** [comment]
Hello there, @XW512, Any updates on the progress?

**Comment by XW512** [comment]
> Hello there, @XW512, Any updates on the progress?
I restore the system and try to install rpm

**Comment by XW512** [comment]
> Hello there, @XW512, Any updates on the progress?

I installed OpenSSL, Lua, lualocks and openresty，openresty version is 1.19.9.1，but，Installation with RPM is still not possible
The error message is still the same

[root@VM-20-7-centos app]# rpm -ivh apisix-2.11.0-0.el7.x86_64.rpm 
error: Failed dependencies:
	apisix-base >= 1.19.3.2.2 is needed by apisix-2.11.0-0.el7.x86_64
[root@VM-20-7-centos app]# 
Looking at this error message, I wonder if the minimum version of openresty is 1.19.3.2.2

[root@VM-20-7-centos app]# openresty -version
nginx version: openresty/1.19.9.1

**Comment by XW512** [comment]
> Hello there, @XW512, Any updates on the progress?

After I reinstalled the system, I had no problem installing 2.10.2 using rpm, but I reported a lack of dependency using 2.11.0

[root@VM-20-7-centos app]# rpm -ivh openresty-pcre-8.44-1.el7.x86_64.rpm 
warning: openresty-pcre-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:openresty-pcre-8.44-1.el7        ################################# [100%]
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# rpm -ivh openresty-pcre-devel-8.44-1.el7.x86_64.rpm 
warning: openresty-pcre-devel-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:openresty-pcre-devel-8.44-1.el7  ################################# [100%]
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# rpm -ivh openresty-openssl111-1.1.1i-1.el7.x86_64.rpm 
warning: openresty-openssl111-1.1.1i-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:openresty-openssl111-1.1.1i-1.el7################################# [100%]
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# rpm -ivh openresty-1.19.9.1-1.el7.x86_64.rpm 
warning: openresty-1.19.9.1-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:openresty-1.19.9.1-1.el7         ################################# [100%]
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# whereis openresty
openresty: /usr/bin/openresty /usr/local/openresty /usr/local/openresty/bin/openresty
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# 
[root@VM-20-7-centos app]# rpm -ivh apisix-2.10.2-0.el7.x86_64.rpm 
Preparing...                          ################################# [100%]
Updating / installing...
   1:apisix-2.10.2-0.el7              ################################# [100%]
[root@VM-20-7-centos app]# rpm -ivh apisix-2.11.0-0.el7.x86_64.rpm 
error: Failed dependencies:
	apisix-base >= 1.19.3.2.2 is needed by apisix-2.11.0-0.el7.x86_64
[root@VM-20-7-centos app]# whereis apisix
apisix: /usr/bin/apisix /usr/local/apisix
[root@VM-20-7-centos app]# 
I wonder if there are any restrictions in version 2.11.0

**Comment by leslie-tsang** [comment]
> > Hello there, @XW512, Any updates on the progress?
> 
> After I reinstalled the system, I had no problem installing 2.10.2 using rpm, but I reported a lack of dependency using 2.11.0
> 
> [root@VM-20-7-centos app]# rpm -ivh openresty-pcre-8.44-1.el7.x86_64.rpm warning: openresty-pcre-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-pcre-8.44-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-pcre-devel-8.44-1.el7.x86_64.rpm warning: openresty-pcre-devel-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-pcre-devel-8.44-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-openssl111-1.1.1i-1.el7.x86_64.rpm warning: openresty-openssl111-1.1.1i-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-openssl111-1.1.1i-1.el7################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-1.19.9.1-1.el7.x86_64.rpm warning: openresty-1.19.9.1-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-1.19.9.1-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# whereis openresty openresty: /usr/bin/openresty /usr/local/openresty /usr/local/openresty/bin/openresty [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh apisix-2.10.2-0.el7.x86_64.rpm Preparing... ################################# [100%] Updating / installing... 1:apisix-2.10.2-0.el7 ################################# [100%] [root@VM-20-7-centos app]# rpm -ivh apisix-2.11.0-0.el7.x86_64.rpm error: Failed dependencies: apisix-base >= 1.19.3.2.2 is needed by apisix-2.11.0-0.el7.x86_64 [root@VM-20-7-centos app]# whereis apisix apisix: /usr/bin/apisix /usr/local/apisix [root@VM-20-7-centos app]# I wonder if there are any restrictions in version 2.11.0

Try `yum` instead of `rpm`, install `*.rpm` to resolve the dependencies. please try [this](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-offline-packagecentos-7).

**Comment by XW512** [comment]
> > > Hello there, @XW512, Any updates on the progress?
> > 
> > 
> > After I reinstalled the system, I had no problem installing 2.10.2 using rpm, but I reported a lack of dependency using 2.11.0
> > [root@VM-20-7-centos app]# rpm -ivh openresty-pcre-8.44-1.el7.x86_64.rpm warning: openresty-pcre-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-pcre-8.44-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-pcre-devel-8.44-1.el7.x86_64.rpm warning: openresty-pcre-devel-8.44-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-pcre-devel-8.44-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-openssl111-1.1.1i-1.el7.x86_64.rpm warning: openresty-openssl111-1.1.1i-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-openssl111-1.1.1i-1.el7################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh openresty-1.19.9.1-1.el7.x86_64.rpm warning: openresty-1.19.9.1-1.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID d5edeb74: NOKEY Preparing... ################################# [100%] Updating / installing... 1:openresty-1.19.9.1-1.el7 ################################# [100%] [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# whereis openresty openresty: /usr/bin/openresty /usr/local/openresty /usr/local/openresty/bin/openresty [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# [root@VM-20-7-centos app]# rpm -ivh apisix-2.10.2-0.el7.x86_64.rpm Preparing... ################################# [100%] Updating / installing... 1:apisix-2.10.2-0.el7 ################################# [100%] [root@VM-20-7-centos app]# rpm -ivh apisix-2.11.0-0.el7.x86_64.rpm error: Failed dependencies: apisix-base >= 1.19.3.2.2 is needed by apisix-2.11.0-0.el7.x86_64 [root@VM-20-7-centos app]# whereis apisix apisix: /usr/bin/apisix /usr/local/apisix [root@VM-20-7-centos app]# I wonder if there are any restrictions in version 2.11.0
> 
> Try `yum` instead of `rpm`, install `*.rpm` to resolve the dependencies. please try [this](https://github.com/apache/apisix/blob/master/docs/en/latest/how-to-build.md#installation-via-rpm-offline-packagecentos-7).

According to the link you sent, I have successfully started apifix, but I have a problem. For example, if there is no network to install apifix, can I directly install those RPMs

[root@VM-20-7-centos app]# cd apisix/
[root@VM-20-7-centos apisix]# 
[root@VM-20-7-centos apisix]# 
[root@VM-20-7-centos apisix]# 
[root@VM-20-7-centos apisix]# 
[root@VM-20-7-centos apisix]# 
[root@VM-20-7-centos apisix]# ll -a
total 39780
drwxr-xr-x 2 root root     4096 Jan  9 20:42 .
drwxr-xr-x 5 root root     4096 Jan  9 20:49 ..
-rw-r--r-- 1 root root  2047030 Dec 14 19:35 apisix-2.11.0-0.el7.x86_64.rpm
-rw-r--r-- 1 root root 36801590 Dec 14 19:35 apisix-base-1.19.9.1.0-0.el7.x86_64.rpm
-rw-r--r-- 1 root root  1624460 Sep  8 04:37 openresty-openssl111-1.1.1l-1.el7.x86_64.rpm
-rw-r--r-- 1 root root   167960 Mar 20  2020 openresty-pcre-8.44-1.el7.x86_64.rpm
-rw-r--r-- 1 root root    55004 Jul 15  2017 openresty-zlib-1.2.11-3.el7.centos.x86_64.rpm

**Comment by leslie-tsang** [comment]
> According to the link you sent, I have successfully started apifix, but I have a problem. For example, if there is no network to install apifix, can I directly install those RPMs

Sure, the link intended to solve the offline installation scenarios.

**Comment by XW512** [comment]
> > According to the link you sent, I have successfully started apifix, but I have a problem. For example, if there is no network to install apifix, can I directly install those RPMs
> 
> Sure, the link intended to solve the offline installation scenarios.

Thank you very much for your answer

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.
