### ISSUE TITLE
How to get path variable

### ISSUE THREAD

**Issue by bnyte** [apache/apisix#6046]
### Issue description

I want to configure my parameters in path, how should I configure him? I have configured it now but `apisix` gives me `404 responses` 

> i am sure that this 404 is not responded to by my backend service

below is the recurrence

- routing config

![](https://user-images.githubusercontent.com/75556346/148527130-56eb34d6-2eed-4630-8c8f-fc204acd8fdc.png)

- apisix 404 response

![image](https://user-images.githubusercontent.com/75556346/148527024-7f96d2b6-0dc6-462b-9035-7405770e4fa9.png)

### Environment

all are the latest version, and run in the latest version of docker

**Comment by bnyte** [comment]
# supplement

I have been successful once, but the value obtained by my back-end service is `:token`

**Comment by tzssangglass** [comment]
refer to: https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match

**Comment by bnyte** [comment]
> 参考：[https](https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match) : [//github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match](https://github.com/apache/apisix/blob/master/docs/en/latest/router-radixtree.md#5-parameter-match)

In my opinion, my configuration may be consistent with the link you provided. My question may be how to rewrite the uri through regularization. Maybe apisix supports adding uri prefix uniformly?

**Comment by bnyte** [comment]
![image](https://user-images.githubusercontent.com/75556346/148633054-293708fd-7551-4611-9545-8b963843fe4d.png)

if value = `:token` my service can get this request... apisix does not have dynamic routing... I want to get the way how to configure routing correctly

**Comment by tokers** [comment]
@bnyte What's your need? Could you describe it more concisely and exactly?

**Comment by bnyte** [comment]
@tokers The browser requests `/v1/user/login/:username` but the request obtained by the backend service is `/sso/v1/user/login/bnytezz` now request `/v1/user/login/bnytezz` my service cant get this request but i can get `/v1/user/login/:username`

**Comment by tzssangglass** [comment]
> `master`/docs/en/latest/router-radixtree.md#5-parameter-match

did you set 

```yaml
apisix:
    router:
        http: 'radixtree_uri_with_parameter'
```

**Comment by bnyte** [comment]
> 

This configuration does the trick, thanks for your help, I'll close it now
