### ISSUE TITLE
request help: How to get Route ID in ext-plugin-pre-req

### ISSUE THREAD

**Issue by leyuuu** [apache/apisix#6048]
### Issue description

![image](https://user-images.githubusercontent.com/50611440/148559922-45a1c0ca-148d-4e4e-8aa7-ba9a88f20876.png)

Does this mean that the `route id` can only be accessed by the built-in plugin with `ctx`?<sup>[Example](https://github.com/apache/apisix/blob/ef04e067c8044b98b261fd51149d9e8503b84d8a/apisix/utils/log-util.lua#L83)</sup>

Thanks in advance

### Environment

- apisix version 2.10.2

**Comment by tzssangglass** [comment]
No support yet. What is the purpose of getting the route id in the plugin runner?

**Comment by leyuuu** [comment]
Thanks for your answer.
In my secondary development project, I want to use java-plugin-runner to do some authorization based on `route id`.

**Comment by membphis** [comment]
@leyuuu I think this is a meaningful feature, if you need it, we can discuss how to implement it.

pls feel free to reopen this issue if you need.

**Comment by tzssangglass** [comment]
+1

**Comment by leyuuu** [comment]
I found the solution in this document <https://github.com/apache/apisix/blob/master/docs/en/latest/apisix-variable.md>

All I need to do is add a [`requiredVars`](https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#the-functions-must-be-implemented-of-filter-execution).

Sorry for the confusion.

**Comment by tzssangglass** [comment]
> /docs/en/latest/apisix-variable.md 中

If you are successful in practice, you can submit a document PR to improve it.
