### ISSUE TITLE
request help: Source code installation APISIX error

### ISSUE THREAD

**Issue by XW512** [apache/apisix#6050]
### Issue description

I installed openresty using the source code installation, and the command to execute the coding is

./configure --with-http_ssl_module --with-openssl=/usr/local/openssl

the openssl I have upgraded to 1.1.1 m

lua version 5.1.5

luarocks version 3.8.0

When I compile APISIX，It has the following error

apisix master-0 depends on argparse 0.7.1-1 (0.7.1-1 installed)
apisix master-0 depends on luasocket 3.0rc1-2 (3.0rc1-2 installed)
apisix master-0 depends on luasec 0.9-1 (not installed)
Installing https://luarocks.org/luasec-0.9-1.src.rock

Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/openresty/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [deps] Error 1

But my system has installed OpenSSL

openssl version

OpenSSL 1.1.1m  14 Dec 2021

How should I deal with this problem？

### Environment

- apisix version (cmd: `apisix version`):  2.11.0
- OS (cmd: `uname -a`):  centOS7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
Hello there, have you extracted the OpenSSL header files to `/usr/local/openresty/openssl/include` ?

**Comment by XW512** [comment]
> Hello there, have you extracted the OpenSSL header files to `/usr/local/openresty/openssl/include` ?

What can I do extracted the OpenSSL header files to `/usr/local/openresty/openssl/include` ?

**Comment by leslie-tsang** [comment]
try this
```bash
rm -rf /usr/local/openresty/openssl
ln -s /usr/local/openssl /usr/local/openresty/openssl
```

**Comment by XW512** [comment]
> 



> try this
> 
> ```shell
> rm -rf /usr/local/openresty/openssl
> ln -s /usr/local/openssl /usr/local/openresty/openssl
> ```

thank you，I'll try it

**Comment by XW512** [comment]
This problem occurred when I initialized APISIX

[root@VM-20-7-centos apisix-2.11.0]# apisix init
which: no openresty in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/java/jdk1.8.0_221/bin:/root/bin:/usr/local/openresty/nginx/sbin:/root/bin)
lua ./apisix/cli/apisix.lua init
can not find openresty

Do we need to set openresty self startup？

**Comment by leslie-tsang** [comment]
plz add OpenResty to `$PATH`

**Comment by XW512** [comment]
> plz add OpenResty to `$PATH`

thank you

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.

**Comment by tzssangglass** [comment]
If you solve the problem, can you raise a discussion or PR to the FAQ document how it was solved?
