### ISSUE TITLE
request help: How to debug plugin lua files

### ISSUE THREAD

**Issue by encanto-oss** [apache/apisix#6067]
### Issue description

I am using Jetbrains IDEA with EmmyLua, where is the reference for debugging?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
Hello there, Try [this](https://juejin.cn/post/6951650129044570125) out.

**Comment by shuaijinchao** [comment]
you can refer to:
https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/debug-mode.md

I usually use the log for debuggin.

**Comment by lijing-21** [comment]
Hi @encanto-oss, thank you for your contribution!

Here is the Contributor T-shirt form[1], if you're interested, kindly take a look :)

[1] https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#contributor-t-shirt
