### ISSUE TITLE
request help: building failed on Mac(2.11 ldap.h)

### ISSUE THREAD

**Issue by siaron** [apache/apisix#6068]
### Issue description

Installing https://luarocks.org/lualdap-1.2.6-1.src.rock

Error: Failed installing dependency: https://luarocks.org/lualdap-1.2.6-1.src.rock - Could not find header file for LDAP
  No file ldap.h in /usr/include
  No file ldap.h in /include
You may have to install LDAP in your system and/or pass LDAP_DIR or LDAP_INCDIR to the luarocks command.
Example: luarocks install lualdap LDAP_DIR=/usr/local
make: *** [deps] Error 1

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi @siaron, please provide the information:

1. Which documentation you're following to build? (Please paste the link here);
2. What are your steps to install it? so we could try to reproduce.

**Comment by juzhiyuan** [comment]
I noticed the same error like https://github.com/apache/apisix/pull/3894#issuecomment-937479073 please have a check

**Comment by siaron** [comment]
1. macbook 编译apisix 执行 `LUAROCKS_SERVER=https://luarocks.cn make deps`
```
Error: Failed installing dependency: https://luarocks.org/lualdap-1.2.6-1.src.rock - Could not find header file for LDAP
  No file ldap.h in /usr/local/include
  No file ldap.h in /usr/include
  No file ldap.h in /include
You may have to install LDAP in your system and/or pass LDAP_DIR or LDAP_INCDIR to the luarocks command.
Example: luarocks install lualdap LDAP_DIR=/usr/local
make: *** [deps] Error 1
```
2. 已经安装`brew install openldap`

**Comment by siaron** [comment]
> 2\. brew install openldap

有没有mac的解决方式

**Comment by tokers** [comment]
@siaron The `LDAP_DIR` can be specified to the LuaRocks config file, see https://github-wiki-see.page/m/luarocks/luarocks/wiki/Config-file-format#Variables for details.

**Comment by tzssangglass** [comment]
my `~/.luarocks/config-5.1.lua` is like

```
variables = {
   LDAP_DIR = "/usr/local/opt/openldap",
   LDAP_INCDIR = "/usr/local/opt/openldap/include",
   OPENSSL_INCDIR = "/usr/local/opt/openresty-openssl111/include",
   OPENSSL_LIBDIR = "/usr/local/opt/openresty-openssl111/lib",
   PCRE_DIR = "/usr/local/Cellar/pcre/8.45",
   PCRE_INCDIR = "/usr/local/Cellar/pcre/8.45/include"
}
```

**Comment by tzssangglass** [comment]
In fact, if you don't understand the build process, it is not recommended to develop on mac, there will be many incompatibilities and you will need to maintain it yourself.

**Comment by leslie-tsang** [comment]
Hello there, it's not recommended to develop on unfamiliar operating systems.
Introducing multiple unknowns at the same time, it's going to be a long day to figure out if something is wrong or not.

> 编译安装时可以指定LDAP_DIR=xxx吗?

Sure, `LDAP_DIR` defined by LuaRocks config file, more detail in [luarocks wiki](https://github.com/luarocks/luarocks/wiki/Config-file-format)

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.

**Comment by kwanhur** [comment]
I got this trouble too, `brew info openldap` show installed dir `/usr/local/opt/openldap`, setted `LDAP_DIR` then `make deps` successfully.

So, suggest to post this prerequisite.

**Comment by juzhiyuan** [comment]
> I got this trouble too, `brew info openldap` show installed dir `/usr/local/opt/openldap`, setted `LDAP_DIR` then `make deps` successfully.
> 
> So, suggest to post this prerequisite.

Hi @kwanhur, Would you like to improve the docs?

**Comment by kwanhur** [comment]
> > I got this trouble too, `brew info openldap` show installed dir `/usr/local/opt/openldap`, setted `LDAP_DIR` then `make deps` successfully.
> > So, suggest to post this prerequisite.
> 
> Hi @kwanhur, Would you like to improve the docs?

yep, #6227

**Comment by Chever-John** [comment]
Is this a MAC specific problem?
I'm curious, how did you install the openLDAP? @tzssangglass
Guess that:
```
brew install openldap
&
luarocks config variables.LDAP_DIR /usr/local/Cellar/openldap/2.5.6
```


> my `~/.luarocks/config-5.1.lua` is like
> 
> ```
> variables = {
>    LDAP_DIR = "/usr/local/opt/openldap",
>    LDAP_INCDIR = "/usr/local/opt/openldap/include",
>    OPENSSL_INCDIR = "/usr/local/opt/openresty-openssl111/include",
>    OPENSSL_LIBDIR = "/usr/local/opt/openresty-openssl111/lib",
>    PCRE_DIR = "/usr/local/Cellar/pcre/8.45",
>    PCRE_INCDIR = "/usr/local/Cellar/pcre/8.45/include"
> }
> ```

**Comment by tzssangglass** [comment]
> I'm curious, how did you install the openLDAP? @tzssangglass

yes.

> Is this a MAC specific problem?

Yes, this is only required on MAC.

**Comment by Chever-John** [comment]
> > I'm curious, how did you install the openLDAP? @tzssangglass
> 
> yes.
> 
> > Is this a MAC specific problem?
> 
> Yes, this is only required on MAC.

Thinks, this news is of great use to me.

**Comment by gogogo1024** [comment]
may be possibly has the same problem 
`
Lua 5.4.4
macOS 12.4
`
` brew install openldap`
 openldap version is 2.6.2, so lualdap version  is apisix's dependencies  lualdap version 1.2.6-1 needs to find header file for LDAP, but always No file ldap.h in /usr/local/Cellar/openldap/2.5.6/include , in  /usr/local/Cellar/openldap/2.6.2/include I find the ldap.h .
