### ISSUE TITLE
docs: add demonstration of log config of "nginx_config" ?

### ISSUE THREAD

**Issue by kerneltravel** [apache/apisix#6072]
### Improved or typo fixed.

accroding to doc  https://github.com/apache/apisix/blob/master/docs/zh/latest/customize-nginx-configuration.md , I firstly put 
“nginx_config” inside scope “apisix” of file config/config.yaml ,which many people will do-also but found not work probably in the resulting config/nginx.conf . 

the second (hard) work is the json format log as log-format “main” 
the third (hard) work is to tune the indent require by above doc, meaning, 4 space instead of 3space or 2space ,the later two-format space format will make apisix fail to restart.

so here I'd share my fine-tuned demonstration of nginx_config.  for somebody who need an example of this subject.

### Solution

append this content in file config/config.yaml ,starting from NEW-LINE !!
```
nginx_config:
  http:
    error_log_level: "info"
    enable_access_log: true
    access_log: logs/access.log
    access_log_format: '{"@timestamp":"$time_iso8601","host":"$hostname","server_ip":"$server_addr","client_ip":"$remote_addr","xff":"$http_x_forwarded_for","domain":"$host","url":"$uri","referer":"$http_referer","args":"$args","upstreamtime":"$upstream_response_time","responsetime":"$request_time","request_method":"$request_method","status":"$status","size":"$body_bytes_sent","request_body":"$request_body","request_length":"$request_length","protocol":"$server_protocol","upstreamhost":"$upstream_addr","file_dir":"$uri","http_user_agent":"$http_user_agent"}'
    access_log_format_escape: json
  http_configuration_snippet: |
    log_format  my-custom-logs-format
    '{"@timestamp":"$time_iso8601",'
    '"host":"$hostname",'
    '"server_ip":"$server_addr",'
    '"client_ip":"$remote_addr",'
    '"xff":"$http_x_forwarded_for",'
    '"domain":"$host",'
    '"url":"$uri",'
    '"referer":"$http_referer",'
    '"args":"$args",'
    '"upstreamtime":"$upstream_response_time",'
    '"responsetime":"$request_time",'
    '"request_method":"$request_method",'
    '"status":"$status",'
    '"size":"$body_bytes_sent",'
    '"request_body":"$request_body",'
    '"request_length":"$request_length",'
    '"protocol":"$server_protocol",'
    '"upstreamhost":"$upstream_addr",'
    '"file_dir":"$uri",'
    '"http_user_agent":"$http_user_agent"'
    '}';
```

the `my-custom-logs-format`  is custom log format for nginx server {} as site log fomat.

**Comment by leslie-tsang** [comment]
Hello there, Thanks for your sharing !
Would you like to submit a PR to improve the documentation ?

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.
