### ISSUE TITLE
bug: build failed because dependencies relying on deprecated git protocol

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#6073]
### Issue description

Fail to install dependencies because one of them is using protocol (git://) deprecated by github. See https://github.blog/2021-09-01-improving-git-protocol-security-github and https://luarocks.org/luaxxhash-1.0.0-1.rockspec

### Environment

- apisix version (cmd: `apisix version`): 2.6
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

Build from source with luarocks (`make deps`).

### Actual result

Build failed when cloning luaxxhash.

### Error log

```
lua-resty-dns-client 5.2.0-1 depends on lua-resty-timer ~> 1 (not installed)
Installing https://luarocks.org/lua-resty-timer-1.1.0-1.src.rock
lua-resty-timer 1.1.0-1 is now installed in /apisix/deps (license: Apache 2.0)
lua-resty-dns-client 5.2.0-1 depends on binaryheap >= 0.4 (not installed)
Installing https://luarocks.org/binaryheap-0.4-1.src.rock
binaryheap 0.4-1 depends on lua >= 5.1 (5.1-1 provided by VM)
binaryheap 0.4-1 is now installed in /apisix/deps (license: MIT/X11)
lua-resty-dns-client 5.2.0-1 depends on luaxxhash >= 1.0 (not installed)
Installing https://luarocks.org/luaxxhash-1.0.0-1.rockspec
Cloning into 'luaxxhash'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Error: Failed installing dependency: https://luarocks.org/lua-resty-dns-client-5.2.0-1.src.rock - Failed installing dependency: https://luarocks.org/luaxxhash-1.0.0-1.rockspec - Failed cloning git repository.
make: *** [Makefile:83: deps] Error 1
```

### Expected result

Build succeeds.

**Comment by leslie-tsang** [comment]
Hello there, it's recommended to use the LTS version instead of the `2.6` version.
The fixes have been merged into the master branch and LTS branch via PR #5825

**Comment by Gary-Airwallex** [comment]
Thanks @leslie-tsang ! As I'm using luarocks bundled into a base image this is what I used to fix the issue: https://github.com/apache/apisix-docker/pull/268/files
