### ISSUE TITLE
bug: The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by tylitianrui** [apache/apisix#6074]
### Issue description

` The unauthenticated git protocol on port 9418 is no longer supported  `   when installing  `lua-resty-dns-client`.  package `lua-resty-dns-client` depends on  ` luaxxhash >= 1.0 (not installed)`

detail:
```
Missing dependencies for lua-resty-dns-client 5.2.0-1:
   luaxxhash >= 1.0 (not installed)

lua-resty-dns-client 5.2.0-1 depends on lua >= 5.1, < 5.4 (5.1-1 provided by VM)
lua-resty-dns-client 5.2.0-1 depends on penlight ~> 1 (1.12.0-1 installed)
lua-resty-dns-client 5.2.0-1 depends on lrandom (20180729-1 installed)
lua-resty-dns-client 5.2.0-1 depends on lua-resty-timer ~> 1 (1.1.0-1 installed)
lua-resty-dns-client 5.2.0-1 depends on binaryheap >= 0.4 (0.4-1 installed)
lua-resty-dns-client 5.2.0-1 depends on luaxxhash >= 1.0 (not installed)
Installing https://luarocks.org/luaxxhash-1.0.0-1.rockspec
cloning 'luaxxhash'...
fatal: remote error：
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed installing dependency: https://luarocks.org/lua-resty-dns-client-5.2.0-1.src.rock - Failed installing dependency: https://luarocks.org/luaxxhash-1.0.0-1.rockspec - Failed cloning git repository.

```  

 I am unable to change git:// to https://  in  [uaxxhash-1.0.0-1.rockspec](https://luarocks.org/luaxxhash-1.0.0-1.rockspec)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.3.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

make deps

### Actual result

installing  dependencies  fails

### Error log

Installing https://luarocks.org/lua-resty-dns-client-5.2.0-1.src.rock
Missing dependencies for lua-resty-dns-client 5.2.0-1:
   luaxxhash >= 1.0 (not installed)

lua-resty-dns-client 5.2.0-1 depends on lua >= 5.1, < 5.4 (5.1-1 provided by VM)
lua-resty-dns-client 5.2.0-1 depends on penlight ~> 1 (1.12.0-1 installed)
lua-resty-dns-client 5.2.0-1 depends on lrandom (20180729-1 installed)
lua-resty-dns-client 5.2.0-1 depends on lua-resty-timer ~> 1 (1.1.0-1 installed)
lua-resty-dns-client 5.2.0-1 depends on binaryheap >= 0.4 (0.4-1 installed)
lua-resty-dns-client 5.2.0-1 depends on luaxxhash >= 1.0 (not installed)
Installing https://luarocks.org/luaxxhash-1.0.0-1.rockspec
cloning 'luaxxhash'...
fatal: remote error：
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

Error: Failed installing dependency: https://luarocks.org/lua-resty-dns-client-5.2.0-1.src.rock - Failed installing dependency: https://luarocks.org/luaxxhash-1.0.0-1.rockspec - Failed cloning git repository.

**Comment by leslie-tsang** [comment]
Hello there, plz check #6073 out.

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.
