### ISSUE TITLE
request help: ci faied due to lack of memory

### ISSUE THREAD

**Issue by zhixiongdu027** [apache/apisix#6076]
### Issue description

#4880 

In this Pr, 
I added some code to set up a k8s cluster.  [common.sh](https://github.com/apache/apisix/pull/4880/files#diff-67362488684645b13d1314d9d45bdfd21fed3599970720bccd584a079971dff9)

but it looks like it fails with no clear error message.

someone can  help! 
  TKS ~_~

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
@tao12345666333 @leslie-tsang PLAT

**Comment by tao12345666333** [comment]
FYI

https://github.com/apache/apisix-ingress-controller/blob/de522437bd3db3dc3e8d8f33c92f322de67531b8/.github/workflows/e2e-test-ci.yml#L74-L90

**Comment by zhixiongdu027** [comment]
@tao12345666333 @tzssangglass 
Hi: 
Sorry, I set a wrong issues title. 

I don't actually want to know how the script or job to build a k8s cluster is defined.

What I want to know is why this CI fails, and there is no prompt message.
[ubuntu-18.04, linux_openresty](https://github.com/apache/apisix/runs/4770829694?check_suite_focus=true)
[(ubuntu-18.04, linux_openresty_1_17)](https://github.com/apache/apisix/runs/4770829694?check_suite_focus=true)


In fact, using kind to create a k8s cluster has been successful.
[(ubuntu-18.04, linux_openresty_1_17)](https://github.com/apache/apisix/runs/4770829694?check_suite_focus=true)

and using minikube to create a k8s cluster has been failed .
[chaos-test](https://github.com/apache/apisix/runs/4770830967?check_suite_focus=true)

**Comment by leslie-tsang** [comment]
> and using minikube to create a k8s cluster has been failed . [chaos-test](https://github.com/apache/apisix/runs/4770830967?check_suite_focus=true)

Hello there, [chaos test](https://github.com/apache/apisix/runs/4770830967?check_suite_focus=true) failed due to dependencies relying on deprecated git protocol, plz check #6073 out.

> In fact, using kind to create a k8s cluster has been successful. [(ubuntu-18.04, linux_openresty_1_17)](https://github.com/apache/apisix/runs/4770829694?check_suite_focus=true)

I suspect there is not enough memory to launch both basic CI env and k8s service. more detail in [#5200](https://github.com/apache/apisix/pull/5200#discussion_r727852007)

**Comment by zhixiongdu027** [comment]
> I suspect there is not enough memory to launch both basic CI env and k8s service. more detail in #5200

if so, What can I do .
Creating a new cluster is a necessary condition for test k8s discovery module .

**Comment by tokers** [comment]
> > I suspect there is not enough memory to launch both basic CI env and k8s service. more detail in #5200
> 
> if so, What can I do . Creating a new cluster is a necessary condition for test k8s discovery module .

Try to run your test suites in a separated github action workflow, so that you don't have to launch a couple of components which are not related to your cases.

**Comment by zhixiongdu027** [comment]
All the test cases in kubernets.t pass, but the final result still fails

The limited hints suggest this is the cause of the runtime environment running out of memory, and there's nothing I can do about it

You can see it here #4880

**Comment by zhixiongdu027** [comment]
I got your point.
Maybe it can work ，but wiil be always failed in  other ci

**Comment by leslie-tsang** [comment]
> Maybe it can work ，but wiil be always failed in other ci

* [build (ubuntu-18.04, linux_openresty)](https://github.com/apache/apisix/runs/4790512640?check_suite_focus=true) Failure may be due to lack of memory
* [run ci on centos7](https://github.com/apache/apisix/runs/4790512541?check_suite_focus=true) Ditto
* [ci-eclint](https://github.com/apache/apisix/runs/4790512078?check_suite_focus=true) 
   ```bash
   docs/zh/latest/discovery/kubernetes.md
    41:43 ❌ unexpected trailing whitespace
                                            (EditorConfig trim_trailing_whitespace https://goo.gl/oo8iVb)
    47:14 ❌ unexpected trailing whitespace
                                            (EditorConfig trim_trailing_whitespace https://goo.gl/oo8iVb)
    50:80 ❌ unexpected trailing whitespace
                                            (EditorConfig trim_trailing_whitespace https://goo.gl/oo8iVb)
   ```
* [Markdown](https://github.com/apache/apisix/runs/4790512152?check_suite_focus=true)

    ```bash
    docs/zh/latest/discovery/kubernetes.md:41:43 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 6]
    docs/zh/latest/discovery/kubernetes.md:47:14 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
    docs/zh/latest/discovery/kubernetes.md:50:80 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
    docs/zh/latest/discovery/kubernetes.md:85:1 MD037/no-space-in-emphasis Spaces inside emphasis markers [Context: "> _"]
    docs/zh/latest/discovery/kubernetes.md:92 MD028/no-blanks-blockquote Blank line inside blockquote
    docs/zh/latest/discovery/kubernetes.md:94 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: ">  + mTLS"]
    docs/zh/latest/discovery/kubernetes.md:98 MD032/blanks-around-lists Lists should be surrounded by blank lines [Context: "> 所以只实现了 token 的方式, 这也意味着不支持 k..."]
    docs/zh/latest/discovery/kubernetes.md:101 MD028/no-blanks-blockquote Blank line inside blockquote
    docs/zh/latest/discovery/kubernetes.md:104 MD035/hr-style Horizontal rule style [Expected: -------; Actual: ------]
    docs/zh/latest/discovery/kubernetes.md:106 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
    ```

> Try to run your test suites in a separated github action workflow, so that you don't have to launch a couple of components which are not related to your cases.

It should work. 🤣

**Comment by zhixiongdu027** [comment]
@leslie-tsang 
I mean even if I can create a new ci just for testing kubernetes.t
But kubernetes.t will still run in centos-ci , build-ci and will eventually fail

**Comment by zhixiongdu027** [comment]
maybe  we can split  test cases into two or more ci  ?
