### ISSUE TITLE
hmac-auth plugins，java hmac-sha256 signature check fail

### ISSUE THREAD

**Issue by kennethToyuan** [apache/apisix#6080]
### Issue description

 public static String HMACSHA256(String data, String key) throws Exception {
        Mac sha256_HMAC = Mac.getInstance("HmacSHA256");
        SecretKeySpec secret_key = new SecretKeySpec(key.getBytes("UTF-8"), "HmacSHA256");
        sha256_HMAC.init(secret_key);
        byte[] array = sha256_HMAC.doFinal(data.getBytes("UTF-8"));
        StringBuilder sb = new StringBuilder();
        for (byte item : array) {
            sb.append(Integer.toHexString((item & 0xFF) | 0x100).substring(1, 3));
        }
        return sb.toString().toUpperCase();
    }

String message=HMACSHA256("GET\n/index.html\nage=36&name=james\nuser-key\nTue, 19 Jan 2021 11:33:20 GMT\nUser-Agent:curl/7.29.0\nx-custom-a:test\n","my-secret-key")

 String base64encodedString = java.util.Base64.getEncoder().encodeToString(message.getBytes("utf-8"));
 
System.out.println(base64encodedString ); 

out：
RDIwQTBCOTdBMERDQzBGNzAwODg4OTNERDY5QTIyRTcwRDYxODg2RTlFOTA4QzhERTg2QTlDOTZDRTE3QkFGMA==

official generated：
8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=

Incorrect length and value does not match,why??

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by qq54903099** [comment]
you can use this code:
`

import javafx.util.Pair;
import lombok.extern.slf4j.Slf4j;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import javax.xml.bind.DatatypeConverter;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.net.URL;
import java.net.URLEncoder;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
public class HmacAuthUtil {

    /**
     * 构造请求 header
     * @param urlStr 请求url，全路径格式，比如：https://xx.xx.xx.cn/api/p/v1/user.get
     * @param requestMethod 请求方法,大写格式，如：GET, POST
     * @param accessKey 
     * @param secretKey 
     * @return
     */
    public static Map<String, String> generateHeader(String urlStr,String requestMethod, String accessKey, String secretKey) {
        log.info("params,urlStr={},requestMethod={},accessKey={},secretKey={}",urlStr,requestMethod,accessKey,secretKey);
        Map<String, String> header = new HashMap<>();
        try {
            DateFormat dateFormat = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.US);
            dateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
            String date = dateFormat.format(new Date());
            URL url = new URL(urlStr);
            URI uri = new URI(url.getProtocol(), url.getHost(), url.getPath(), url.getQuery(), null);

            String canonicalQueryString = getCanonicalQueryString(uri.getQuery());

            String message = requestMethod.toUpperCase() + "\n" + uri.getPath() + "\n" + canonicalQueryString + "\n"  + accessKey + "\n" + date + "\n";

            Mac hasher = Mac.getInstance("HmacSHA256");
            hasher.init(new SecretKeySpec(secretKey.getBytes(), "HmacSHA256"));

            byte[] hash = hasher.doFinal(message.getBytes());

            // to lowercase hexits
            DatatypeConverter.printHexBinary(hash);

            // to base64
            String sign = DatatypeConverter.printBase64Binary(hash);
            header.put("X-HMAC-SIGNATURE", sign);
            header.put("X-HMAC-ALGORITHM", "hmac-sha256");
            header.put("X-HMAC-ACCESS-KEY", accessKey);
            header.put("Date", date);
        } catch (Exception e) {
            log.error("generate error",e);
            throw new RuntimeException("generate header error");
        }
        log.info("header info,{}",header);
        return header;
    }

    private static String getCanonicalQueryString(String query) {
        if (query == null || query.trim().length() == 0) {
            return "";
        }
        List<Pair<String, String>> queryParamList = new ArrayList<>();
        String[] params = query.split("&");
        for (String param : params) {
            int eqIndex = param.indexOf("=");
            String key = param.substring(0, eqIndex);
            String value = param.substring(eqIndex+1);
            Pair<String, String> pair = new Pair<String, String>(key,value);
            queryParamList.add(pair);
        }

        List<Pair<String, String>> sortedParamList = queryParamList.stream().sorted(Comparator.comparing(param -> param.getKey() + "=" + Optional.ofNullable(param.getValue()).orElse(""))).collect(Collectors.toList());
        List<Pair<String, String>> encodeParamList = new ArrayList<>();
        sortedParamList.stream().forEach(param -> {
            try {
                String key = URLEncoder.encode(param.getKey(), "utf-8");
                String value = URLEncoder.encode(Optional.ofNullable(param.getValue()).orElse(""), "utf-8")
                        .replaceAll("\\%2B","%20")
                        .replaceAll("\\+","%20")
                        .replaceAll("\\%21","!")
                        .replaceAll("\\%27","'")
                        .replaceAll("\\%28","(")
                        .replaceAll("\\%29",")")
                        .replaceAll("\\%7E","~")
                        .replaceAll("\\%25","%")
                        ;
                encodeParamList.add(new Pair<>(key, value));
            } catch (UnsupportedEncodingException e) {
                throw new RuntimeException("encoding error");
            }
        });
        StringBuilder queryParamString = new StringBuilder(64);
        for (Pair<String, String> encodeParam : encodeParamList) {
            queryParamString.append(encodeParam.getKey()).append("=").append(Optional.ofNullable(encodeParam.getValue()).orElse(""));
            queryParamString.append("&");
        }

        return queryParamString.substring(0, queryParamString.length() - 1);
    }
}`

**Comment by kennethToyuan** [comment]
> 你可以使用这个代码： `import javafx.util.Pair; 导入 lmport javafx.util.Pair； 导入 lombok.extern.slf4j.Slf4j；
> 
> 导入 javax.crypto.Mac； 导入 javax.crypto.spec.SecretKeySpec； 导入 javax.xml.bind.DatatypeConverter； 导入 java.io.UnsupportedEncodingException； 导入 java.net.URI； 导入 java.net.URL； 导入 java.net.URLEncoder； 导入 java.text.DateFormat； 导入 java.text.SimpleDateFormat； 导入java.util.*；ombok.extern.slf4j.Slf4j；
> 
> 导入 javax.crypto.Mac； 导入 javax.crypto.spec.SecretKeySpec； 导入 javax.xml.bind.DatatypeConverter； 导入 java.io.UnsupportedEncodingException； 导入 java.net.URI； 导入 java.net.URL； 导入 java.net.URLEncoder； 导入 java.text.DateFormat； 导入 java.text.SimpleDateFormat； 导入 java.util.*； 导入 java.util.stream.Collectors；
> 
> @slf4j 公共类 HmacAuthUtil {
> 
> ```
> /**
>  * 构造请求 header
>  * @param urlStr 请求url，全路径格式，比如：https://xx.xx.xx.cn/api/p/v1/user.get
>  * @param requestMethod 请求方法,大写格式，如：GET, POST
>  * @param accessKey 
>  * @param secretKey 
>  * @return
>  */
> public static Map<String, String> generateHeader(String urlStr,String requestMethod, String accessKey, String secretKey) {
>     log.info("params,urlStr={},requestMethod={},accessKey={},secretKey={}",urlStr,requestMethod,accessKey,secretKey);
>     Map<String, String> header = new HashMap<>();
>     try {
>         DateFormat dateFormat = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.US);
>         dateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));
>         String date = dateFormat.format(new Date());
>         URL url = new URL(urlStr);
>         URI uri = new URI(url.getProtocol(), url.getHost(), url.getPath(), url.getQuery(), null);
> 
>         String canonicalQueryString = getCanonicalQueryString(uri.getQuery());
> 
>         String message = requestMethod.toUpperCase() + "\n" + uri.getPath() + "\n" + canonicalQueryString + "\n"  + accessKey + "\n" + date + "\n";
> 
>         Mac hasher = Mac.getInstance("HmacSHA256");
>         hasher.init(new SecretKeySpec(secretKey.getBytes(), "HmacSHA256"));
> 
>         byte[] hash = hasher.doFinal(message.getBytes());
> 
>         // to lowercase hexits
>         DatatypeConverter.printHexBinary(hash);
> 
>         // to base64
>         String sign = DatatypeConverter.printBase64Binary(hash);
>         header.put("X-HMAC-SIGNATURE", sign);
>         header.put("X-HMAC-ALGORITHM", "hmac-sha256");
>         header.put("X-HMAC-ACCESS-KEY", accessKey);
>         header.put("Date", date);
>     } catch (Exception e) {
>         log.error("generate error",e);
>         throw new RuntimeException("generate header error");
>     }
>     log.info("header info,{}",header);
>     return header;
> }
> 
> private static String getCanonicalQueryString(String query) {
>     if (query == null || query.trim().length() == 0) {
>         return "";
>     }
>     List<Pair<String, String>> queryParamList = new ArrayList<>();
>     String[] params = query.split("&");
>     for (String param : params) {
>         int eqIndex = param.indexOf("=");
>         String key = param.substring(0, eqIndex);
>         String value = param.substring(eqIndex+1);
>         Pair<String, String> pair = new Pair<String, String>(key,value);
>         queryParamList.add(pair);
>     }
> 
>     List<Pair<String, String>> sortedParamList = queryParamList.stream().sorted(Comparator.comparing(param -> param.getKey() + "=" + Optional.ofNullable(param.getValue()).orElse(""))).collect(Collectors.toList());
>     List<Pair<String, String>> encodeParamList = new ArrayList<>();
>     sortedParamList.stream().forEach(param -> {
>         try {
>             String key = URLEncoder.encode(param.getKey(), "utf-8");
>             String value = URLEncoder.encode(Optional.ofNullable(param.getValue()).orElse(""), "utf-8")
>                     .replaceAll("\\%2B","%20")
>                     .replaceAll("\\+","%20")
>                     .replaceAll("\\%21","!")
>                     .replaceAll("\\%27","'")
>                     .replaceAll("\\%28","(")
>                     .replaceAll("\\%29",")")
>                     .replaceAll("\\%7E","~")
>                     .replaceAll("\\%25","%")
>                     ;
>             encodeParamList.add(new Pair<>(key, value));
>         } catch (UnsupportedEncodingException e) {
>             throw new RuntimeException("encoding error");
>         }
>     });
>     StringBuilder queryParamString = new StringBuilder(64);
>     for (Pair<String, String> encodeParam : encodeParamList) {
>         queryParamString.append(encodeParam.getKey()).append("=").append(Optional.ofNullable(encodeParam.getValue()).orElse(""));
>         queryParamString.append("&");
>     }
> 
>     return queryParamString.substring(0, queryParamString.length() - 1);
> }
> ```
> 
> }`

The result I want to return:
{
    "data": null,
    "code": -1,
    "msg": "Invalid digest"
}

actual return result:
{"message":"Invalid digest"}

Is there a way to handle it?

**Comment by qq54903099** [comment]
I thought you can use response-rewrite  plugin to rewrite response body.

but response-rewrite,only return one message...

"response-rewrite": {
      "body": "{code:-1,message:\"invalid\"}",
      "disable": false,
      "vars": [
        [
          "status",
          "==",
          401
        ]
      ]
    }

**Comment by kennethToyuan** [comment]
@qq54903099   nice !  good！
