### ISSUE TITLE
request help: macos arm docker-compose.yaml add apisix-dashboard

### ISSUE THREAD

**Issue by tx991020** [apache/apisix#6086]
### Issue description

macos arm docker-compose.yaml add apisix-dashboard

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
Can you desc your issue more clear ? I can't get the point. Thanks.
Need to add `apisix-dashboard` support for [docker-compose-arm64.yml](https://github.com/apache/apisix-docker/blob/master/example/docker-compose-arm64.yml) ?

**Comment by tx991020** [comment]
yes
