### ISSUE TITLE
docs: CONTRIBUTING.md need install luajit guide

### ISSUE THREAD

**Issue by zaunist** [apache/apisix#6093]
### Improved or typo fixed.

I have run `install_dependencies.sh` and `make deps`, but it seems not install luajit? When I follow the `CONTRIBUTING.md` to install `luacheck` and execute the `make lint`, I got a error:
```
▶ make lint
[ info ] lint -> [ Start ]
./utils/check-lua-code-style.sh
+ luacheck -q apisix t/lib
Total: 0 warnings / 0 errors in 186 files
+ find apisix -name *.lua ! -wholename apisix/cli/ngx_tpl.lua -exec ./utils/lj-releng {} +
+ cat /tmp/check.log
sh: 1: luajit: not found
ERROR: lj-releng ONLY supports LuaJIT 2.1!
+ exit 1
make: *** [Makefile:180: lint] Error 1
```
And then, I execute `sudo apt install luajit`, it work success. So can we add install luajit guide to `CONTRIBUTING.md`?

There are no instructions for installing luajit in the current documentation.

```
## Check code style and test case style

* code style
    * Please take a look at [APISIX Lua Coding Style Guide](CODE_STYLE.md).
    * Use tool to check your code statically by command: `make lint`.

```shell
        # install `luacheck` first before run it
        $ luarocks install luacheck
        # check source code
        $ make lint
        ./utils/check-lua-code-style.sh
        + luacheck -q apisix t/lib
        Total: 0 warnings / 0 errors in 146 files
        + find apisix -name *.lua ! -wholename apisix/cli/ngx_tpl.lua -exec ./utils/lj-releng {} +
        + grep -E ERROR.*.lua: /tmp/check.log
        + true
        + [ -s /tmp/error.log ]
        ./utils/check-test-code-style.sh
        + find t -name '*.t' -exec grep -E '\-\-\-\s+(SKIP|ONLY|LAST|FIRST)$' '{}' +
        + true
        + '[' -s /tmp/error.log ']'
        + find t -name '*.t' -exec ./utils/reindex '{}' +
        + grep done. /tmp/check.log
        + true
        + '[' -s /tmp/error.log ']'

      The `lj-releng` and `reindex` will be downloaded automatically by `make lint` if not exists.

```

### Solution

There is two solutions.
1. Add instructions for installing luajit in `CONTRIBUTING.md`.
2. Install luajit in the `install_dependencies.sh`script.

**Comment by zaunist** [comment]
> Hello there, `luajit` is usually embedded with OpenResty, so there is no need to install `luajit` separately Maybe we should add OpenResty's `luajit` to the `$PATH` to solve it ?

Seems like yes, I do have openresty installed, but cannot execute luajit command.

**Comment by tzssangglass** [comment]
We can add some hints by adding the following configuration to `~/.bash_profile` or `~/.zshrc` and so on


```
# openresty
export OPENRESTY_PREFIX="/usr/local/openresty"
export PATH=$OPENRESTY_PREFIX/nginx/sbin:$OPENRESTY_PREFIX/bin:$OPENRESTY_PREFIX/luajit/bin:$PATH
```

**Comment by zaunist** [comment]
> We can add some hints by adding the following configuration to `~/.bash_profile` or `~/.zshrc` and so on
> 
> ```
> # openresty
> export OPENRESTY_PREFIX="/usr/local/openresty"
> export PATH=$OPENRESTY_PREFIX/nginx/sbin:$OPENRESTY_PREFIX/bin:$OPENRESTY_PREFIX/luajit/bin:$PATH
> ```

Agree, so if need to update the docs, let me to do this work.

**Comment by tzssangglass** [comment]
I'm not sure where it would be appropriate to add it, in fact, it would fall under something related to plugin development environment setup.

**Comment by zaunist** [comment]
This problem should be caused by my environment, so close it.
