### ISSUE TITLE
request help: how to modify the default port of nginx,

### ISSUE THREAD

**Issue by tiyorn** [apache/apisix#6094]
### Issue description

The following error is reported when starting apisix:
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)

while the apisix configuration file does not seem to have this configuration item

### Environment

- apisix version (cmd: `apisix version`):2.11
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider solved. Feel free to reopen it if needed.

**Comment by amrellafy** [comment]
Which listen port need to be changed? 

We have the following settings and unfortunately it's not working:

```yaml
nginx_config:
  http_configuration_snippet: |
    server
    {
        listen 45651;
    }
```

**Comment by juzhiyuan** [comment]
Hi @amrellafy, does this doc work for you? https://apisix.apache.org/docs/apisix/customize-nginx-configuration/

**Comment by amrellafy** [comment]
@juzhiyuan  yes, and we still get the following error

 nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address already in use)

**Comment by juzhiyuan** [comment]
> nginx: [emerg] bind() to 127.0.0.1:9090 failed (98: Address already in use)

Hi, as the error shows: the 9090 port in use, could you please check which process is using it? also cc @bzp2010

**Comment by mariofdezzz** [comment]
Hello @juzhiyuan 

I'm working with @amrellafy. We have just discovered that apisix takes [port 9090](https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L158) by default for the [Control API](https://apisix.apache.org/docs/apisix/control-api/). In our case, we are deploying Apisix into **IBM Code Engine**, which doesn't allow ssh or a similar approach. We guess this ([Port 9090 Conflicts error on AIX](https://www.ibm.com/docs/en/itcam-app-diagnostic/7.1.0.2?topic=server-port-9090-conflicts-error-aix)) might be the reason why we can't take port 9090 on IBM Cloud.

Anyways, we have **disabled** *Control API*. Although, *Control API* used port can be changed.

```sh
  enable_control: false
  #control:
  #  ip: 127.0.0.1
  #  port: 9090
  disable_sync_configuration_during_start: false  # safe exit. Remove this once the feature is stable
```
