### ISSUE TITLE
request help: The performance of java-plugin is so bad

### ISSUE THREAD

**Issue by zjzwjcbj** [apache/apisix#6096]
### Issue description

I writed an auth plugin for both lua plugin and java plugin.Then I stress test.
I found that the throughput of the lua plugin is about 6-8 times that of the java plugin.
The performance of java plugin is so bad. Is that right?

 apisix-java-plugin-runner:0.1.0

### Environment

- apisix version (cmd: apisix version):2.10.0
- OS (cmd: uname -a):Linux apisix-7679f65569-j2gp9 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 Linux
- OpenResty / Nginx version (cmd: nginx -V or openresty -V):openresty/1.19.3.1
- etcd version, if have (cmd: run curl http://127.0.0.1:9090/v1/server_info to get the info from server-info API):3.4.16
- apisix-dashboard version, if have:2.9.0
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: luarocks --version):

**Comment by leslie-tsang** [comment]
Hello there, [apisix-java-plugin-runner](https://github.com/apache/apisix-java-plugin-runner) is voting for version `0.2.0`
Can you try `0.2.0` ?

also cc @tzssangglass

**Comment by zjzwjcbj** [comment]
0.2.0 will help improve performance ?

**Comment by zjzwjcbj** [comment]
> 

0.2.0 will help improve performance ?

**Comment by tzssangglass** [comment]
0.2.0 changes the communication framework from reactor-netty to netty, but no performance improvement is guaranteed. In fact, java runner is not provided for high performance scenarios.

According to my previous tests, the performance of the java runner is about 1/3 that of APISIX, but if you have complex operations in the java runner, the performance will be even lower.

**Comment by zjzwjcbj** [comment]
Ok,thanks
