### ISSUE TITLE
request help: apple M1  make install not permission to /usr/share

### ISSUE THREAD

**Issue by 1247691206** [apache/apisix#6099]
### Issue description

make install

install -d /usr/share/lua/5.1/apisix
install: mkdir /usr/share/lua: Read-only file system
make: *** [install] Error 71

csrutil disable  also tried ,still failed ....

### Environment

- apisix version (cmd: `apisix version`):/opt/homebrew/Cellar/openresty/1.19.9.1_2/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.11.0
- OS (cmd: `uname -a`):Darwin XXX-MB1 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.9.1
built by clang 13.0.0 (clang-1300.0.29.30)
built with OpenSSL 1.1.1l  24 Aug 2021
TLS SNI support enabled
configure arguments: --prefix=/opt/homebrew/Cellar/openresty/1.19.9.1_2/nginx --with-cc-opt='-O2 -I/opt/homebrew/include -I/opt/homebrew/opt/pcre/include -I/opt/homebrew/opt/openresty-openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.20 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.10 --with-ld-opt='-Wl,-rpath,/opt/homebrew/Cellar/openresty/1.19.9.1_2/luajit/lib -L/opt/homebrew/lib -L/opt/homebrew/opt/pcre/lib -L/opt/homebrew/opt/openresty-openssl111/lib' --pid-path=/opt/homebrew/var/run/openresty.pid --lock-path=/opt/homebrew/var/run/openresty.lock --conf-path=/opt/homebrew/etc/openresty/nginx.conf --http-log-path=/opt/homebrew/var/log/nginx/access.log --error-log-path=/opt/homebrew/var/log/nginx/error.log --with-pcre-jit --with-ipv6 --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_geoip_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-stream --with-http_ssl_module
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):/opt/homebrew/bin/luarocks 3.7.0

**Comment by tzssangglass** [comment]
No promises that APISIX will work perfectly on M1.

**Comment by tzssangglass** [comment]
BTW, you no need to `make install` on M1? If you are a developer, you can download the source code.

**Comment by 1247691206** [comment]
> BTW, you no need to `make install` on M1? If you are a developer, you can download the source code.

yes , I download source code  make deps  success but make install failed. I want to develop plugin

**Comment by tokers** [comment]
This type of "permission" problem is caused by the settings of your system, try to google it with some candidate answers with the key words :"macos m1 readonly file system".

**Comment by tzssangglass** [comment]
> yes , I download source code make deps success but make install failed. I want to develop plugin

then you don't need to `make install`? I didn't run `make install` when I developed on M1.

**Comment by 1247691206** [comment]
> > yes , I download source code make deps success but make install failed. I want to develop plugin
> 
> then you don't need to `make install`? I didn't run `make install` when I developed on M1.

ok  thanks , I tried run on docker

**Comment by juzhiyuan** [comment]
Here has one article about how to develop Apache APISIX on M1 by @guoqqqi, see https://github.com/apache/apisix-website/pull/837

**Comment by thor533** [comment]
@1247691206 
Dear, how did you deal with it? I also met the same problem. Could you give me some advice？ tks
