### ISSUE TITLE
request help: add test case

### ISSUE THREAD

**Issue by biubiue** [apache/apisix#6109]
### Issue description

In this pr
[#6107](https://github.com/apache/apisix/pull/6107)

I find  one bug  and commit PR.
But I can't write unit tests, I'm developing in a window environment.
someone can help!
TKS _

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by biubiue** [comment]
> At my first glance, there is no way to go into
> 
> https://github.com/apache/apisix/blob/2a67374af0b515b667e2d02f8744ac8dd9dad30f/apisix/ssl/router/radixtree_sni.lua#L108
> 
> The function is called in
> 
> https://github.com/apache/apisix/blob/2a67374af0b515b667e2d02f8744ac8dd9dad30f/apisix/ssl/router/radixtree_sni.lua#L120
> 
> To get an error because of the bad private key, we need to have a bad private key. However, we already do validation in
> 
> https://github.com/apache/apisix/blob/2a67374af0b515b667e2d02f8744ac8dd9dad30f/apisix/ssl.lua#L195
> 
> So it is not possible to have a bad private key.
> 
> @biubiue Could you share how do you discover this bug?
> 
> Anyway, the variable name is definitely wrong.

Just found out when reading the source code

**Comment by spacewander** [comment]
I see. You have a keen eye like an eagle :)
I will close it as there is no way to go into this branch yet.
