### ISSUE TITLE
docs:  No docs for Vault

### ISSUE THREAD

**Issue by moonming** [apache/apisix#6118]
### Improved or typo fixed.

https://github.com/apache/apisix/blob/0d4f65a9ae06430388af609ca0dcad386225d616/apisix/core/vault.lua

### Solution

not doc for how to use vault with Apache APISIX

**Comment by juzhiyuan** [comment]
@bisakhmondal added How to integrate jwt-auth with Vault by https://github.com/apache/apisix/pull/5745

see https://apisix.apache.org/docs/apisix/next/plugins/jwt-auth#enable-jwt-auth-with-vault-compatibility

**Comment by kerneltravel** [comment]
> @bisakhmondal added How to integrate jwt-auth with Vault by #5745
> 
> see https://apisix.apache.org/docs/apisix/next/plugins/jwt-auth#enable-jwt-auth-with-vault-compatibility

docs/en/latest/plugins/jwt-auth.md has been updated , so later the docs/zh/latest/plugins/jwt-auth.md docs need to be updated too.

**Comment by moonming** [comment]
we can add to the README.md

**Comment by juzhiyuan** [comment]
Get it, cc @guoqqqi to translate the Chinese part, and cc @bisakhmondal help to put it in README so more developers could notice this :)
