### ISSUE TITLE
feature : adding description field for property of plugin schema

### ISSUE THREAD

**Issue by wangyjx** [apache/apisix#612]
I think it is good to add a description field for property of plugin configuration schema and then the description can be displayed in the plugin configuration popup window.

**Comment by moonming** [comment]
sure, APISIX supports description field, for example:  https://github.com/iresty/apisix/blob/master/lua/apisix/schema_def.lua#L206
welcome description for plugin schema

**Comment by wangyjx** [comment]
Didn't see, thanks

**Comment by moonming** [comment]
@wangyjx PR is welcomed for description of plugin schema.

**Comment by wangyjx** [comment]
this might be an document issue. 😆

**Comment by moonming** [comment]
I don't think so, we should add the desc in the code base for dashboard.

**Comment by moonming** [comment]
and document is the same important as code.

**Comment by spacewander** [comment]
Already done in many plugins.
