### ISSUE TITLE
request help: There have many error logs 

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix#6123]
### Issue description

apisix的错误日志暴增：
![image](https://user-images.githubusercontent.com/31987918/149700637-9770149d-4c1d-4551-9d90-1f1a1c3b9674.png)

![image](https://user-images.githubusercontent.com/31987918/149700698-57f109db-c96d-436e-9af5-b1d3717c77f5.png)

全部是最样的报错

### Environment

- apisix version (cmd: `apisix version`): 2.8
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@lihuawei321 Did you enable the `skywalking` plugin?

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/2931

 and it is better to show text rather than images.

**Comment by leslie-tsang** [comment]
Hello there, `skywalking` plugin is disabled by default in [APISIX v2.8](https://github.com/apache/apisix/tree/release/2.8), It seems you had enable it by mistake.
Please refer to the [skywalking docs](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/skywalking.md#disable-plugin) to disable it.

**Comment by leslie-tsang** [comment]
@juzhiyuan Consider resolved due to lack of feedback. Feel free to reopen it if needed.
