### ISSUE TITLE
enhancement: the ip-restriction can not work if we use mutil-level angent

### ISSUE THREAD

**Issue by hiqrf** [apache/apisix#6125]
### Issue description

the ip-restriction can not work if we use mutil-level angent,because it useses ctx.var.remote_addr,this can olny fetch the ip adress of     upper level like lsb

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1、use a SLB in front of apisix
2、enable ip-restriction plugin
3、the SLB  olny fetch the slb's ip ,so it can not work correctly
4、may be we can use ctx.var.http_x_forwarded_for instead

### Actual result

the  ip-restriction plugin can work even if we use mutil-level angent,

### Error log

no error log provide

**Comment by tokers** [comment]
I updated the title from `bug` to `enhancement`, it's not a bug.

**Comment by hiqrf** [comment]
we can solve this problem with the real ip plugin
