### ISSUE TITLE
feature : support running dev environment on Windows 

### ISSUE THREAD

**Issue by wangyjx** [apache/apisix#613]
Because there are still large portion of developers who are using Windows and Openresty can run on Windows,  who not make apisix  at least the dev environment running on windows.

**Comment by moonming** [comment]
All of the components used by APISIX can run on windows. But we not test on windows platform yet.
Welcome try and feedback here.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
