### ISSUE TITLE
request help: custom mismatching route response

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix#6131]
### Issue description

now:

apisix/init.lua:388
```
return core.response.exit(404,
                    {error_msg = "404 Route Not Found"})
```

expect configable mismatching route response. incudes status code, header, body.

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
> incudes status code, header, body

Could you provide more details for your use case?

**Comment by spacewander** [comment]
Look like it is already solved by a match-anything route `/*` plus fault-injection plugin?

**Comment by zlhgo** [comment]
不好意思，英语不好。
就是如果APP请求了一个不存在的路由，返回的数据可能解析不了会导致APP崩溃，但是APP已经发布了。

**Comment by tzssangglass** [comment]
> 就是如果APP请求了一个不存在的路由，返回的数据可能解析不了会导致APP崩溃，测试可能没有测试到，但是APP已经发布了。

waht @spacewander means that you can set up a `/*` route to underwrite and match all requests that cannot be matched, and configure the `fault-injection` plugin on this route to  define your response.

just try.

**Comment by zlhgo** [comment]
谢谢，应该是没问题的。不过还是希望能考虑下是否支持自定义配置，因为这样会更简单一些。 :-)
