### ISSUE TITLE
request help: property "hosts" validation failed: failed to validate item

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#6142]
### Issue description

my route host is engine*.cacazhu.com ,Can support begin xxx*.xxxx.com?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`): 2.10.3
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
AFAIK, **not support yet**, you can design a custom plugin to achieve this.

**Comment by kongjun01** [comment]
oh , no, but, thank you anyway.

**Comment by kongjun01** [comment]
I modified the radixtree_ host_ uri.lua source code,  when insert host_ In routes, the original logic is to reverse the host. I add a property in route. when it is turned on, the last host is in reverse order, for example, host is test*.baidu.com, it will become moc.udiab.test*.

**Comment by leslie-tsang** [comment]
Hello there, seems we have a [solution](https://github.com/api7/lua-resty-radixtree/issues/112) here.

**Comment by leslie-tsang** [comment]
@juzhiyuan Considered solved. Feel free to reopen it if needed.
