### ISSUE TITLE
request help: How to modify the time zone in the error message

### ISSUE THREAD

**Issue by whioue** [apache/apisix#6148]
### Issue description

当我创建了一个jwt认证，设置了token的超时时间，通过api获取到token后，超过超时时间后使用此token会得到报错信息如下：
![image](https://user-images.githubusercontent.com/47098518/150080588-0bfb3367-c645-47bb-aac2-336ae953630d.png)
应该如何修改时区，将GMT修改成CST？

### Environment

- apisix version (cmd: `apisix version`):V2.8
- OS (cmd: `uname -a`):Centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
How did you sign the JWT token? The `exp` is numeric UNIX timestamp.

**Comment by leslie-tsang** [comment]
Hello there, I afraid it can't be done in APISIX, the error message generated in [resty.jwt](
https://github.com/SkyLothar/lua-resty-jwt/blob/master/lib/resty/jwt-validators.lua#L355)
The date in GMT format generated in [ngx.http_time](https://github.com/openresty/lua-nginx-module#ngxhttp_time)
