### ISSUE TITLE
request help: How to match both path param and prefix?

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix#6154]
### Issue description

I try to match the two urls like below
`/users/${userId}/orders`
`/users/${userId}/orders/${orderId}`

And I'm using radixtree_uri_with_parameter to match url
but when I set path to `/users/:user/orders*`, the `/users/${userId}/orders/${orderId}` didn't match
when I set path to `/users/:user/orders/*`, the `/users/${userId}/orders` didn't match

What should I do so I can use one rule to match the two url?

BTW, I cannot remove `orders` in path, because I may have another url like `/users/${userId}/goods` to route to another service.
### Environment

- apisix version (cmd: `apisix version`): 2.10.2
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
Path prefix matching and path parameter matching cannot be enabled at the same time.
