### ISSUE TITLE
bug: Makefile error in master branch

### ISSUE THREAD

**Issue by crazyMonkey1995** [apache/apisix#6157]
### Issue description

I found that apisix did make code adjustments to the discovery module:
![image](https://user-images.githubusercontent.com/21658981/150293464-86cf030a-8619-4445-ad71-97e22f01568c.png)
But the make file:
![image](https://user-images.githubusercontent.com/21658981/150293646-a7c98029-9044-46c1-a32c-2b1f0e1e2fde.png)
So the folders under discovery will not be copied in.

### Environment

-

### Steps to reproduce

build apisix with apisix-build-tools

### Actual result

missing discovery module

### Error log

-

### Expected result

-

**Comment by crazyMonkey1995** [comment]
By the way the branch I used is master

**Comment by leslie-tsang** [comment]
Thanks for reporting. I will check it.
