### ISSUE TITLE
request help:  can apisix suport downstream connection manage and Bidirectional streaming gRPC feature?

### ISSUE THREAD

**Issue by projectindex** [apache/apisix#6170]
### Issue description

1. downstream connection management
client -->apisix -->service
in sometime, client application heartbeat message lost, or need discard connection, or other reason,
can apisix actively force close TCP connection?

2.  Bidirectional streaming gRPC support
my service have Bidirectional streaming gRPC, which to push some message to client.

client only one http2 connection to apisix,and apisix deliver different request to backend service,
some service is unary call, 
but push service is bidi stream grpc,
I need the apisix hold the upstream connection， so that push message to the client

![image](https://user-images.githubusercontent.com/4802288/150335526-b6a85cad-1fa9-4e83-b42f-c5ee009a6808.png)

can this possible?

### Environment

- apisix version (cmd: `apisix version`):
-  2.11

- OS (cmd: `uname -a`):
centos 7

- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
lastest 

- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
 lastest 

- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
> 1. can apisix actively force close TCP connection?

Closing the connection should be something done by the client or upstream, and the gateway actively closing the connection is usually in a timeout situation.
