### ISSUE TITLE
Proposal: refactor server-info plugin

### ISSUE THREAD

**Issue by zaunist** [apache/apisix#6176]
## Background
The current server-info plug-in adds a revision every time the status is updated, and some users set a relatively short reporting time, which may result in millions or even tens of millions of data in etcd after a long run, resulting in a slow connection and high cpu usage.

## Purpose
Modify the current server-info plugin so that it does not write a piece of data to etcd every time the system state is refreshed. When the apisix node is alive, the server-info information will always be there and will not be updated with revisions; only when the apisix node system information changes will there be a put operation. (e.g., hostname changes)

### Configura Schema
| Name    | Type | default |Description |
|:---------:|:------:|:-------:|:-------------:|
| report_ttl | integer | 36 |the live time for server info in etcd (unit: second, maximum: 86400, minimum: 3) |

## implement

Etcd has a keepalive command that can refresh the TTL of the key without generating new revisions. We can use keepalive to refresh the node information to avoid writing a lot of useless information.
1. get the server-info data, if it does not exist, initialize the server-info information
2. bind the lease to the key "server-info"
3. call keepalive to refresh the TTL to ensure the node is alive

## Server-info Flowchart
![image](https://user-images.githubusercontent.com/38528079/150462633-07108377-3c34-47fc-b5c5-91fb2412a434.png)

## Other

What are your ideas?

**Comment by tokers** [comment]
After the implementation, we may also make a benchmark to assess the optimization level.

**Comment by zaunist** [comment]
> 

Sure, I will do this work.
