### ISSUE TITLE
request help: Why proxy-rewrite.host must be configured when starting the proxy-rewrite plugin, otherwise it will be forwarded directly to 127.0.0.1 by default, even if upstream.nodes is configured?

### ISSUE THREAD

**Issue by tiyorn** [apache/apisix#6185]
### Issue description

The configuration is as follows：
```
{
  "uri": "/blog/*",
  "name": "test_blog",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/blog/(.*)",
        "/$1"
      ],
      "scheme": "http"
    }
  },
  "plugin_config_id": "common_plugin",
  "upstream": {
    "nodes": [
      {
        "host": "10.132.16.70",
        "port": 80,
        "weight": 1
      }
    ],
    "retries": 3,
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    },
    "retry_timeout": 3
  },
  "status": 1
}
```

And the access.log show: 
`127.0.0.1:9080 "GET /blog/index.php HTTP/1.1" 301 0 0.172 "-" "PostmanRuntime/7.26.3" 10.132.16.70:80 301 0.168 "http://127.0.0.1:9080/index.php"`

When proxy-rewrite.host is configured as 10.132.16.70, it is normal. At this time, the log is：
`127.0.0.1:9080 "GET /blog/index.php HTTP/1.1" 301 0 0.179 "-" "PostmanRuntime/7.26.3" 10.132.16.70:80 301 0.176 "http://10.132.16.70/index.php"`

I don't understand why proxy-rewrite.host must be configured, otherwise it won't work properly.

### Environment

- apisix version (cmd: `apisix version`):2.11
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by starsz** [comment]
Hi, @tiyorn 
> proxy-rewrite.host must be configured

No, It's not necessary. It defines the Host head that sends to the upstream.
You can refer to the doc: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite

> otherwise it will be forwarded directly to 127.0.0.1 by default

I think the request is sent to the upstream `10.132.16.70`, and uses the `Host` head of `127.0.0.1:9098`, so the log will be that.

**Comment by leslie-tsang** [comment]
> I don't understand why proxy-rewrite.host must be configured, otherwise it won't work properly.

Hello there, `proxy-rewrite.host` is an optional configuration, which mean the request will be send to the `upstream` with the request header `Host: <proxy-rewrite.host>`, `proxy-rewrite` plugin work as expected.

> When proxy-rewrite.host is configured as 10.132.16.70, it is normal. At this time, the log is：
> 
> 127.0.0.1:9080 "GET /blog/index.php HTTP/1.1" 301 0 0.179 "-" "PostmanRuntime/7.26.3" 10.132.16.70:80 301 0.176 "http://10.132.16.70/index.php"

The config work as you expected due to `upstream.nodes.host` has been set to `10.132.16.70:80`, It is not due to the `proxy-rewrite.host` configuration taking effect.

@juzhiyuan Consider solved. Feel free to reopen it if needed.
