### ISSUE TITLE
bug: Error collecting logs with jaeger-collector-agent 9411

### ISSUE THREAD

**Issue by myoss** [apache/apisix#6189]
### Issue description

enable zipkin plugin, collecting logs with jaeger-collector-agent, request route failed

### Environment

- apisix version (cmd: `apisix version`): 2.11.0-alpine
- OS (cmd: `uname -a`): k8s pod
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.16
- apisix-dashboard version, if have: 2.10.1-alpine
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1. enable zipkin in global plugin 
    ```
      {
            "endpoint": "http://jaeger-collector-test.examle.com:9411/api/v2/spans",
            "sample_ratio": 1,
            "service_name": "APISIX-IN-SG",
            "server_addr": "192.168.3.50"
        }
    ```
2. create a route
3. request route failed

### Actual result

request route success

### Error log

```
2022/01/24 08:11:12 [error] 46#46: *54652654 failed to run log_by_lua*: /usr/local/apisix/apisix/plugins/zipkin.lua:273: attempt to index field 'response_span' (a nil value)
stack traceback:
        /usr/local/apisix/apisix/plugins/zipkin.lua:273: in function 'phase_func'
        /usr/local/apisix/apisix/plugin.lua:743: in function 'run_plugin'
        /usr/local/apisix/apisix/plugin.lua:776: in function 'run_global_rules'
        /usr/local/apisix/apisix/init.lua:335: in function 'common_phase'
        /usr/local/apisix/apisix/init.lua:708: in function 'http_log_phase'
        log_by_lua(nginx.conf:350):2: in main chunk while logging request, client: 172.20.211.54, server: _, request: "PUT /apisix/admin/global_rules/1 HTTP/1.0", upstream: "http://10.2.167.113:80/apisix/admin/global_rules/1", host: "dashboard-test.example.com", referrer: "https://dashboard-test.example.com/plugin/list"
```

**Comment by tzssangglass** [comment]
ref to: https://github.com/apache/apisix/issues/2151#issuecomment-706060672

This will help you?

**Comment by tokers** [comment]
@myoss What does the route object look like? Could you paste some elaborated details?

**Comment by myoss** [comment]
```
{
  "uri": "/**",
  "name": "apisix_ingress_dashboard",
  "host": "apisix-dashboard. examle.com",
  "upstream_id": "1",
  "status": 1
}
```

**Comment by spacewander** [comment]
@myoss 
Could you provide the way that you configure & run the jaeger-collector-agent so we can reproduce it?
