### ISSUE TITLE
request help: How to proxy to a third-party website by custom a global plug-in？

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#6190]
### Issue description

my route :

```
{
    "uri": "/*",
    "host":"test.test.com",
    "upstream":
    {
        "type": "roundrobin",
        "scheme": "https",
        "pass_host": "rewrite",
        "upstream_host":"www.baidu.com",
        "nodes":
        {
            "112.80.248.76:443": 1
        }
    }
}
```

I expect when i visit test.test.com agent to www.baidu.com, but it is return 404.

### Environment

- apisix version (cmd: `apisix version`): 2.10.3
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by kongjun01** [comment]
I expect to customize the route through the global plug-in, because the route information cannot be created through the apisix api. However, when the route does not match, it directly returns '404 route not found'.

**Comment by kongjun01** [comment]
Whether or not execute the plug-in before match runs?

**Comment by tzssangglass** [comment]
`404 route not found`

This means that your request is not caught by any route, which I think might have something to do with your `host` settings.

> Whether or not execute the plug-in before match runs?

global route run before route match.

**Comment by kongjun01** [comment]
My etcd doesn't have this route information.

![image](https://user-images.githubusercontent.com/5688653/150789678-67e035e9-5648-4fb4-80a7-17982818598c.png)

in apisix 2.10.3 version, global route run after route match.

**Comment by tzssangglass** [comment]
> My etcd doesn't have this route information.

If this is business logic you wrote yourself, won't discuss it.


> in apisix 2.10.3 version, global route run after route match.

Thank you for pointing that out, indeed.

ref to: https://github.com/apache/apisix/blob/d9be046028db5850a752f3b872fe21a6bc376e66/apisix/init.lua#L388-L396

**Comment by tzssangglass** [comment]
So I'm afraid you can't inject route when running the global plugin.

**Comment by kongjun01** [comment]
OK, I see what you mean.

**Comment by tzssangglass** [comment]
> I see what you mean.
> 
> or maybe:
> 
> ```
> local route = api_ctx.matched_route
> if not route then
>     -- run global rule
>     plugin.run_global_rules(api_ctx, router.global_rules, nil)
> 
>     route = api_ctx.matched_route
>     if not route then
>         core.log.info("not find any matched route")
>         return core.response.exit(404,
>                 {error_msg = "404 Route Not Found"})
>     end
> end
> ```
> 
> the global plugin can set route.

If you need to do this, you can fork it and modify it later.

**Comment by tzssangglass** [comment]
It seems that this issue is not related to the project, I will close it, feel free to reopen it if you need.
