### ISSUE TITLE
bug: socket hang up

### ISSUE THREAD

**Issue by kennethToyuan** [apache/apisix#6194]
### Issue description

add  response-rewrite   plugin, postman  submitapi error>>>>> socket hang up

### Environment

- apisix version (cmd: `apisix version`): 2.10.2
- OS (cmd: `uname -a`): Linux 9beceabc408a 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1.Route add hmac-auth
2.Route add ext-plugin-pre-req
3.Route add response-rewrite
{
  "body": "{\"code\":-102,\"message\":\"fail!\"}",
  "disable": false,
  "vars": [
    [
      "status",
      "~=",
      200
    ]
  ]
}

There is a probability of appearing after configuration, and it will be restored after repeated configuration and saving.

### Actual result

socket hang up

### Error log

2022/01/25 06:12:17 [error] 44#44: *1994 failed to run header_filter_by_lua*: /usr/local/apisix/apisix/plugins/response-rewrite.lua:73: attempt to call method 'eval' (a nil value)
stack traceback:
	/usr/local/apisix/apisix/plugins/response-rewrite.lua:73: in function 'vars_matched'
	/usr/local/apisix/apisix/plugins/response-rewrite.lua:142: in function 'phase_func'
	/usr/local/apisix/apisix/plugin.lua:701: in function 'common_phase'
	/usr/local/apisix/apisix/init.lua:615: in function 'http_header_filter_phase'
	header_filter_by_lua:2: in main chunk while sending to client, client: 192.168.47.1, server: _, request: "GET

### Expected result

{"code":-102,"message":"fail!"}

**Comment by tzssangglass** [comment]
give the full reproducible steps using curl.

BTW, 

```
{
"body": "{"code":-102,"message":"fail!"}",
"disable": false,
"vars": [
[
"status",
"~=",
200
]
]
}
```

is incorrect format.

**Comment by kennethToyuan** [comment]
@tzssangglass   Please tell me what is wrong?

**Comment by leslie-tsang** [comment]
> give the full reproducible steps using curl.
> 
> BTW,
> 
> ```
> {
> "body": "{"code":-102,"message":"fail!"}",
> "disable": false,
> "vars": [
> [
> "status",
> "~=",
> 200
> ]
> ]
> }
> ```
> 
> is incorrect format.

Hello there, @kennethToyuan , Invalid JSON formatting.

**Comment by kennethToyuan** [comment]
yes i found
