### ISSUE TITLE
request help: why proxy_rewrite dones't work well

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6209]
### Issue description

I do the demo follow https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite 
 step1 : curl add route and plugin 
step2:     curl -X GET http://127.0.0.1:9080/test/index.html,
but i get 502  and the request log is not same with you said ,I think it does not rewite the host to "http://iresty.com/test/home.html   .Anybody tell me why ?
![image](https://user-images.githubusercontent.com/15372524/151111800-b9d43848-7362-46f9-b745-c43ac829afdf.png)

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by leslie-tsang** [comment]
Hello there, It just a demo, which mean that you need to change the `upstream` and `host` to make it work.

**Comment by purekeeper** [comment]
@leslie-tsang    Please look the demo again, I think it not relate with the upstream, I think any request with uri /test/index.html will be forward to http://iresty.com/test/home/html,  because the proxy-rewrite plugin rewrite the request right ?

**Comment by leslie-tsang** [comment]
> @leslie-tsang Please look the demo again, I think it not relate with the upstream, I think any request with uri /test/index.html will be forward to http://iresty.com/test/home/html, because the proxy-rewrite plugin rewrite the request right ?

I afraid the answer is no. 
The request will be send to `http://127.0.0.1:80/test/index.html` with the request header `host: iresty.com`
> The `502` error occur as there is no service listen to `127.0.0.1:80`

You can try the following `CMD` to test if it achieves your goal
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/test/index.html",
    "plugins": {
        "proxy-rewrite": {
            "uri": "/test/home.html",
            "scheme": "http",
            "host": "iresty.com",
            "headers": {
                "X-Api-Version": "v1",
                "X-Api-Engine": "apisix",
                "X-Api-useless": ""
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "iresty.com:80": 1
        }
    }
}'
```

**Comment by purekeeper** [comment]
okay，thanks all.
