### ISSUE TITLE
bug: Setting head-name in "request-id" plugin has no effect

### ISSUE THREAD

**Issue by 1657486787** [apache/apisix#6220]
### Issue description

Setting head-name in "request-id" plugin has no effect

### Environment

- apisix version (cmd: `apisix version`):2.12
- OS (cmd: `uname -a`):Linux wx-2 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce

1.set the header_name in "request-id" plugin, pg:
{
  "disable": false,
  "request-id": {
    "header_name": "mk-id",
    "include_in_response": true
  }
}

2.However, the result is still “X-Request-Id”

### Actual result

"X-Request-Id: 7103a3f5-ff55-4549-925f-65a7ea9a5418"

### Error log

nothing

### Expected result

the head-name is  mk-id

**Comment by bisakhmondal** [comment]
Hi @1657486787, could you please share your apisix route configuration? I was not able to reproduce the bug that you are stating. I have checked it with the header_name you passed, it works as expected.

config
```bash
curl http://127.0.0.1:9080/apisix/admin/routes/5 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/test",
    "plugins": {
        "request-id": {
            "header_name": "mk-id",
            "include_in_response": true
        }
    },
    "upstream": {
       "type": "roundrobin",
        "scheme": "https",
        "nodes": {
            "google.com:443": 1
        }
    }
}'
```

```shell
curl localhost:9080/test -I      
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Content-Length: 1565
Connection: keep-alive
Referrer-Policy: no-referrer
Date: Fri, 28 Jan 2022 07:40:32 GMT
Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
Server: APISIX/2.12.0
mk-id: e235cc2f-af36-4f3c-ab4c-3896d39fbe88

```

Thank you.

**Comment by 1657486787** [comment]
> 

My configuration information is as follows：

**Comment by bisakhmondal** [comment]
Hey @1657486787,  I just looked into the configuration, you are having multilevel nesting in `request-id` plugin. and you are putting all the configuration inside the second level request-id. It doesn't make any sense.
> "request-id": {
"disable": false, // delete it
"request-id": {  // request-id inside request-id won't be decoded
"header_name": "mk-id",
"include_in_response": true
}
},

Replace it with:
```shell
"request-id": {
    "header_name": "mk-id",
    "include_in_response": true
}
```

Also, why are you putting the `disable:false` inside all the plugin configurations. It doesn't make any sense. Whenever confused, always consider the documentation [see https://apisix.apache.org/docs/apisix/plugins/request-id/ for request id].

**Comment by 1657486787** [comment]
> Hey @1657486787, I just looked into the configuration, you are having multilevel nesting in `request-id` plugin. and you are putting all the configuration inside the second level request-id. It doesn't make any sense.
> 
> > "request-id": {
> > ~"disable": false,~ // delete it
> > ~"request-id": {~ // request-id inside request-id won't be decoded
> > "header_name": "mk-id",
> > "include_in_response": true
> > ~}~
> > },
> 
> Replace it with:
> 
> ```shell
> "request-id": {
>     "header_name": "mk-id",
>     "include_in_response": true
> }
> ```
> 
> Also, why are you putting the `disable:false` inside all the plugin configurations. It doesn't make any sense. Whenever confused, always consider the documentation [see https://apisix.apache.org/docs/apisix/plugins/request-id/ for request id].



> Hey @1657486787, I just looked into the configuration, you are having multilevel nesting in `request-id` plugin. and you are putting all the configuration inside the second level request-id. It doesn't make any sense.
> 
> > "request-id": {
> > ~"disable": false,~ // delete it
> > ~"request-id": {~ // request-id inside request-id won't be decoded
> > "header_name": "mk-id",
> > "include_in_response": true
> > ~}~
> > },
> 
> Replace it with:
> 
> ```shell
> "request-id": {
>     "header_name": "mk-id",
>     "include_in_response": true
> }
> ```
> 
> Also, why are you putting the `disable:false` inside all the plugin configurations. It doesn't make any sense. Whenever confused, always consider the documentation [see https://apisix.apache.org/docs/apisix/plugins/request-id/ for request id].

thank you so much！
