### ISSUE TITLE
request help: failed to connect to the unix socket unix:/tmp/runner.sock: connection refused

### ISSUE THREAD

**Issue by 1657486787** [apache/apisix#6231]
### Issue description

the running result is "503 Service Temporarily Unavailable".  view  apisix_log/error.log  exceptions:

2022/01/29 02:10:19 [error] 45#45: *14847 [lua] init.lua:689: phase_func(): failed to connect to the unix socket unix:/tmp/runner.sock: connection refused, client: 192.168.20.230, server: _, request: "GET /       dw2/test HTTP/1.1", host: "192.168.1.101:9080"
2022/01/29 02:10:19 [warn] 45#45: *14847 [lua] plugin.lua:722: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 192.168.20.230, server: _, request: "GET /dw2/test HTTP/1.1", host: "       192.168.1.101:9080"

### Environment

- apisix version (cmd: `apisix version`): 2.12
- OS (cmd: `uname -a`): Linux wx-2 3.10.0-1160.el7.x86_64
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
You need to give the reproduction steps.

BTW, `connection refused`  means that no plugin runner is listening at this address.

**Comment by tokers** [comment]
Also, please provide the running environment of Apache APISIX.

**Comment by 1657486787** [comment]
> BTW

Actually, I have the plugin running. After testing, it is found that there is a problem with /tmp/runner.sock under /tmp, but it is normal to put it under other paths. do not know why
