### ISSUE TITLE
docs: the experimental description should be removed from `nacos` zh docs

### ISSUE THREAD

**Issue by leslie-tsang** [apache/apisix#6249]
### Improved or typo fixed.

The experimental description in [nacos zh docs](https://github.com/apache/apisix/blob/c0a19871f1456f7520302da9a3ace97ba45c91c8/docs/zh/latest/discovery/nacos.md?plain=1#L26) should be removed,
the english documents have been processed refer to #6240, now let's sync the change to the zh one.

### Solution

We can just remove the experimental description line.

**Comment by zaunist** [comment]
Hi, community, I'm glad to do this.
