### ISSUE TITLE
request help: Could it be interesting to implement cookie/session management in APISIX? 

### ISSUE THREAD

**Issue by WeiWANG0118** [apache/apisix#6268]
### Issue description

Hello apisix team,

Lately, I'm trying to integrate APISIX in my project(Angular + Node) as an API gateway. And I noticed I'm losing my cookie/session. I'm new to apisix, so I was thinking I had a bad configuration. But after doing some research and asking for help on your slack channel, I was told that apisix doesn’t support the management of cookie/sessions currently.  

So I'm thinking maybe it is an interesting feature that we, the developers can implement in apisix.  And if you are interested, I'm happy to communicate more details about my problem.    

I hope my opinion could be useful for you. And please let me know if I submit this issue with the correct template. 

### Environment

- apisix version: 2.12.0

**Comment by tzssangglass** [comment]
releated to

https://github.com/apache/apisix/issues/881

I'm not sure if this is what you need: https://github.com/apache/apisix/blob/master/t/node/chash-hashon.t#L401-L487

**Comment by tokers** [comment]
@WeiWANG0118 By saying "cookie/session management", could you describe it in more detail?
