### ISSUE TITLE
bug: failed to install via RPM Repository(CentOS 7)

### ISSUE THREAD

**Issue by scott-wong** [apache/apisix#6273]
### Issue description

follow the official doc, failed to install via RPM Repository(CentOS 7).
https://apisix.apache.org/docs/apisix/how-to-build/

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`): Linux eu-server 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.9.1
built by gcc 10.2.1 20200804 (Red Hat 10.2.1-2) (GCC) 
built with OpenSSL 1.1.1k  25 Mar 2021
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

`yum-config-manager --add-repo https://repos.apiseven.com/packages/centos/apache-apisix.repo`
`yum info -y apisix`

### Actual result

failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try.
https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### Error log

(base) [root@eu-server yum.repos.d]# yum info -y apisix
已加载插件：fastestmirror, langpacks, ulninfo
Loading mirror speeds from cached hostfile
https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
正在尝试其它镜像。
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

 One of the configured repositories failed (Apache APISIX Repository for CentOS),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=release ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable release
        or
            subscription-manager repos --disable=release

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=release.skip_if_unavailable=true

failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try.
https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

**Comment by leslie-tsang** [comment]
Seems you are using a `Red Hat Enterprise Linux 7`.
Some variables, such as `$releasever`, have different values in `Red Hat Enterprise Linux 7` and `CentOS7`, which resulting in this issue.
| var | CentOS7 | Red Hat Enterprise Linux 7 |
|:--: | :----: | :----: |
|$releasever| 7 | 7Server |

## Solution
To fix it, replace `$releasever` with `7` in `/etc/yum.repos.d/apache-apisix.repo` as shown below
```ini
[release]
name=Apache APISIX Repository for CentOS
baseurl=https://repos.apiseven.com/packages/centos/7/$basearch
skip_if_unavailable=False
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://repos.apiseven.com/KEYS
enabled=1
enabled_metadata=1
```

**Comment by scott-wong** [comment]
Got it,thx.
