### ISSUE TITLE
request help: client frequent SocketException: read time out

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#6285]
### Issue description

Through packet capturing, it is found that apisix dose not send the `server hello`. 

Using wireshark, shows as below:

![image](https://user-images.githubusercontent.com/5688653/153364335-7f37f20f-ae6d-4ef6-ac44-db3ee0daa651.png)

About than 10 times a minute. 

Do you know under what circumstances this problem can happen?

### Environment

- apisix version (cmd: `apisix version`): 2.10.3
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@kongjun01 From the screenshot we can know the TCP connection was reset after the Client Hello. You may send some requests to APISIX (mimicking the clients' behaviors), and look through the error.log or the response details to see the actual problem.

**Comment by kongjun01** [comment]
It's caused by that problem.

https://github.com/apache/apisix/issues/5755
