### ISSUE TITLE
request help:  apisix add port 9443 when receive 302 redirect

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6286]
### Issue description

Browser send https://a/b/c  to nlb(443) and nlb forward to apisix(9443) ,then apisix forward to backed service  testSerivce, testservice return 302 to a new url.   but the browser show the new url with port 9443 ,which result in failure, anybody know the reason ?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by souzens** [comment]
Try to disable
#proxy_set_header   X-Forwarded-Port
