### ISSUE TITLE
request help:  Miss metrics when call /apisix/prometheus/metrics

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6293]
### Issue description

Hi there, I enable  prometheus plugin ,and call the api  /apisix/prometheus/metrics  just get data like pic show, miss data http_status/http_latency/bandwidth... ,anybody known the reason ?
<img width="754" alt="image" src="https://user-images.githubusercontent.com/15372524/153527024-e661cbaa-7d58-40cb-a243-b48fa7ca1f65.png">

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@purekeeper By saying enable prometheus plugin, how did you do it? Could you provide your steps?

**Comment by nic-6443** [comment]
@purekeeper  One thing to note, there must be at least one http request sent to
APISIX, in order to generate `http_status/http_latency/bandwidth` metrics, I wonder if you have launched a request to the corresponding route after enabling the prometheus plugin? Of course, if it's a global rule, any request to any route can trigger the generation of metrics.

**Comment by purekeeper** [comment]
@nic-6443 @tokers     apisix deploy as a docker service, I enable the prometheus plugin and set params   

  prometheus:
    export_uri: /apisix/prometheus/metrics
    enable_export_server: true
    export_addr:
      ip: 0.0.0.0
      port: 9091

and  then call   /apisix/prometheus/metrics  get the result  which miss http_status/http_latency/bandwidth... metrics,
by the way,  we have launched many request.

**Comment by tokers** [comment]
> @nic-6443 @tokers apisix deploy as a docker service, I enable the prometheus plugin and set params
> 
> prometheus: export_uri: /apisix/prometheus/metrics enable_export_server: true export_addr: ip: 0.0.0.0 port: 9091
> 
> and then call /apisix/prometheus/metrics get the result which miss http_status/http_latency/bandwidth... metrics, by the way, we have launched many request.

Actually, you should create a global rule to enable the prometheus plugin.

**Comment by nic-6443** [comment]
@purekeeper Enable Prometheus plugin in global rules like this:
```
curl http://127.0.0.1:9180/apisix/admin/global_rules/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -i -X PUT -d '
{
    "plugins": {
      "prometheus": {
        "disable": false
      }
    }
}'
```

**Comment by purekeeper** [comment]
Thanks everyone, resolved.

**Comment by SmallWhitePG** [comment]
@purekeeper how to resolve
