### ISSUE TITLE
request help: Does route support regular expression ？

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6294]
### Issue description

I have a nginx location config like :

location ~ "^/newservice/dos/api2/v2/documents/([^/]{16,})/" {
  todo something
}

So how do i rewrite it by apisix's router ?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-use-route-uri-for-regular-matching
