### ISSUE TITLE
bug: global_rules的返回内容与其他接口不一致

### ISSUE THREAD

**Issue by c591762009** [apache/apisix#6297]
### Issue description

用get方法调用/apisix/admin/global_rules时，nodes节点内容为空，但count返回为1.其余接口正常。
![image](https://user-images.githubusercontent.com/32794876/153564213-faa2f871-bd21-4b9d-9956-134a42bb47e8.png)
[root@i-JrNh3EuzwM-7 ~]# curl http://127.0.0.1:9080/apisix/admin/global_rules -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
{"action":"get","count":"1","node":{"key":"\/apisix\/global_rules","dir":true,"nodes":{}}}
[root@i-JrNh3EuzwM-7 ~]# curl http://127.0.0.1:9080/apisix/admin/consumers  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
{"action":"get","count":0,"node":{"key":"\/apisix\/consumers","dir":true,"nodes":{}}}

### Environment

- apisix version (cmd: `apisix version`):all
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

直接调用接口就行
curl http://127.0.0.1:9080/apisix/admin/global_rules -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

### Actual result

{"action":"get","count":"1","node":{"key":"\/apisix\/global_rules","dir":true,"nodes":{}}}

### Error log

--

### Expected result

{"action":"get","count":"0","node":{"key":"\/apisix\/global_rules","dir":true,"nodes":{}}}

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/6155
