### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by Phoebus888** [apache/apisix#6298]
### Issue description

apiVersion: apisix.apache.org/v2beta1
kind: ApisixRoute
metadata:
  name: httpserver-route
  namespace: test
spec:
  http:
  - name: rule1
    match:
      hosts:
      - local.httpbin.org
      paths:
      - /*
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        regex_uri: ["^/test(/|$)(.*)", "/$2"]
    - name: jwt
      enable: true
    - name: limit-req
      enable: true
      config:
        rate: 1
        burst: 2
        rejected_code: 503
        key_type: "var"
        key: "remote_addr"
    - name: cors
      enable: true
    backends:
       - serviceName: nginx
         servicePort: 80

limit-req Plugin doesn't work

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

1

### Actual result

![image](https://user-images.githubusercontent.com/45359605/153565131-6c19b727-14fd-4b2e-9717-8dc2658533c5.png)

web只看到了proxy-rewrite插件生效  limit-req没有生效

### Error log

1

**Comment by Chever-John** [comment]
Can you tell me how you turned on the plugin?

something like error_log:)
