### ISSUE TITLE
bug: some mistakes in prometheus plugin

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix#6301]
### Issue description

The APISIX prometheus plugin uses the `/nginx_status` endpoint provided by nginx to get some internal metrics, which return the data like
```
Active connections: 291
server accepts handled requests
 16630948 16630948 31070465
Reading: 6 Writing: 179 Waiting: 106
```
According to the [nginx documentation](https://nginx.org/libxslt/en/docs/http/ngx_http_stub_status_module.html):
> The following status information is provided:
> 
> Active connections
> The current number of active client connections including Waiting connections.
> accepts
> The total number of accepted client connections.
> handled
> The total number of handled connections. Generally, the parameter value is the same as accepts unless some resource limits have been reached (for example, the worker_connections limit).
> requests
> The total number of client requests.
> Reading
> The current number of connections where nginx is reading the request header.
> Writing
> The current number of connections where nginx is writing the response back to the client.
> Waiting
> The current number of idle client connections waiting for a request.

The third number in the third line is `The total number of client requests`, but APISIX now puts this metric in `nginx_http_current_connections{label="total"}`, which is obviously wrong. 
https://github.com/apache/apisix/blob/0920d1d21fba36947b4ce13438040874c5d37610/apisix/plugins/prometheus/exporter.lua#L86-L88
https://github.com/apache/apisix/blob/0920d1d21fba36947b4ce13438040874c5d37610/apisix/plugins/prometheus/exporter.lua#L174-L206

Also the three metrics in the third line are all cumulative, should we use the counter type instead of the guage for those metrics? Which is more in line with the prometheus definition of metric types.

So I want to introduce two new metric: 
1. `nginx_http_requests_total`(counter type)
2. `nginx_http_connections_total`(counter type) with a `type` label, which has two values: `accepts`, `handled`

If there are no problems, I can complete the fix.
### Environment

- apisix version (cmd: `apisix version`): 2.10.1

### Steps to reproduce

Just enable prometheus plugin.

### Actual result

/

### Error log

/

**Comment by nic-6443** [comment]
> Yes, it is good.
> 
> > nginx_http_requests_total
> 
> Do you mean `apisix_http_requests_total`?

I think it's OK to use `apisix` as a prefix, but the previous metric used `nginx` as a prefix, do you think it needs to be changed together?
https://github.com/apache/apisix/blob/0920d1d21fba36947b4ce13438040874c5d37610/apisix/plugins/prometheus/exporter.lua#L86-L88

**Comment by nic-6443** [comment]
I think `nginx_http_requests_total` or `http_requests_total` is fine, because we will add an `apisix` prefix by default (the user can customize this prefix configuration in the plugin configuration), so there is no need to repeat it.
https://github.com/apache/apisix/blob/0920d1d21fba36947b4ce13438040874c5d37610/apisix/plugins/prometheus/exporter.lua#L79-L85
@spacewander What do you think?

**Comment by spacewander** [comment]
I will vote for `http_requests_total`.

**Comment by nic-6443** [comment]
> I will vote for `http_requests_total`.

Got it. As discussed above, I will be introducing two new metrics:
1. `http_requests_total`(counter type)
2. `nginx_http_connections_total`(counter type) with a `type` label, which has two values: `accepts`, `handled`

Also, the `state` label in the old `nginx_http_current_connections` metric will only have four values: `active`/ `reading`/ `writing`/ `waiting` and the `accepted`/ `handled`/ `total` will be removed. 
                          
I will submit this PR as soon as possible.

**Comment by nic-6443** [comment]
I found that I couldn't use the `counter` type when coding, because the metrics are directly obtain from nginx, there is no accumulation process, and the Prometheus counter type has no `set` method, it can only accumulate the count.
For this reason, I just introduced a new metric `http_requests_total`, which is of type guage.

**Comment by tokers** [comment]
> I found that I couldn't use the `counter` type when coding, because the metrics are directly obtain from nginx, there is no accumulation process, and the Prometheus counter type has no `set` method, it can only accumulate the count. For this reason, I just introduced a new metric `http_requests_total`, which is of type guage.

Can we just record the value and next time after we get the new value, let's accumulate the counter with the increments.

**Comment by nic-6443** [comment]
> > I found that I couldn't use the `counter` type when coding, because the metrics are directly obtain from nginx, there is no accumulation process, and the Prometheus counter type has no `set` method, it can only accumulate the count. For this reason, I just introduced a new metric `http_requests_total`, which is of type guage.
> 
> Can we just record the value and next time after we get the new value, let's accumulate the counter with the increments.

I feel that this is complicated and unnecessary, because metric type is only as a hint, and does not affect the subsequent data storage and processing, even if we use the `guage` type, can still use functions such as `rate` to handle, like the metric of the counter type.
