### ISSUE TITLE
MTLS error

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6303]
### Issue description

We have a very large  pem file which greater than 65535   ,then apisix occur error 

validation failed: property \\\"ca\\\" validation failed: string too long, expected at most 65536, got 126932\"}

what should do for this ?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by starsz** [comment]
Hi @purekeeper 
You can try to increase the max length limit in the schema.
Which is defined in the certificate_scheme 
Refer: https://github.com/apache/apisix/blob/50d6465fd7b6288f517fd5c408a3171ace7882dd/apisix/schema_def.lua#L380-L382

**Comment by tokers** [comment]
It seems that `64k` is too short for certificates and CA certificates?

**Comment by purekeeper** [comment]
Thanks everyone, resolved by  increase the max length limit in the schema .
