### ISSUE TITLE
request help: repeatedly download luarocks archive tar file

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6307]
### Issue description

execute `utils/linux-install-luarocks.sh` twice, got two tar files `v3.8.0.tar.gz` `v3.8.0.tar.gz.1`

reexecute it cause no `unzip` on my vm, build log:

```bash
Lua version detected: 5.1
Lua interpreter found: /usr/local/openresty/luajit/bin/luajit
lua.h found: /usr/local/openresty/luajit/include/luajit-2.1/lua.h
Could not find 'unzip'.
Make sure it is installed and available in your PATH.

configure failed.

+ exit 1
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
> ```shell
> Could not find 'unzip'.
> ```

You don't have the `unzip` command on your system?

**Comment by kwanhur** [comment]
> > ```shell
> > Could not find 'unzip'.
> > ```
> 
> You don't have the `unzip` command on your system?

yes, I installed it manually and redo `./utils/linux-install-luarocks.sh`

advise to check archive file `v3.8.0.tar.gz` exist or not and validate it, if unvalidated, remove it and download again.

**Comment by tzssangglass** [comment]
> advise to check archive file `v3.8.0.tar.gz` exist or not and validate it, if unvalidated, remove it and download again.

SGTM

**Comment by kwanhur** [comment]
Remove it after untar seems be better from https://github.com/apache/apisix/pull/6306#discussion_r806425026

Check target archive file checksum and then decide download or not, this maybe more complicated.
