### ISSUE TITLE
request help: in apisix, how to use rbac with keycloak?

### ISSUE THREAD

**Issue by hellobiek** [apache/apisix#6309]
### Issue description

I had watch the url：https://apisix.apache.org/zh/blog/2021/12/10/integrate-keycloak-auth-in-apisix/

Now, I know how to authoity using apisix，now I also want to use apisix authorization for me.

Could you help me to how to using role config in keycloak for apisix.

### Environment

- apisix version (cmd: `apisix version`): 2.7.12
- OS (cmd: `uname -a`): 18.04.1-Ubuntu
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):  using helm install 
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):  using helm install 
- apisix-dashboard version, if have: using helm install 
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): using helm install

**Comment by tzssangglass** [comment]
Please describe the specific problem, or you can see : https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-keycloak.md first

**Comment by hellobiek** [comment]
fixed

**Comment by hellobiek** [comment]
你好，我参考下面这篇博客，使用authz-keycloak来进行RBAC的权限管理： 
https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/authz-keycloak.md
现在每次访问，都需要输入token，但是我想使用，弹窗让用户输入用户名和密码的方式完成认证。
请问，这样的化，需要怎么做呢？我本地的配置如下：
`{
  "audience": "Client ID",
  "disable": false,
  "permissions": [
    "Png Resource#image:view"
  ],
  "token_endpoint": "http://10.20.0.213:31477/auth/realms/apisix_test_realm/protocol/openid-connect/token"
}`

请问，这样的条件下，该如何修改配置。

**Comment by tzssangglass** [comment]
The pop-up window needs to be similar to this code below:
https://github.com/apache/apisix/blob/749094bb55421f5b715af18e376c373603bf5d62/apisix/plugins/basic-auth.lua#L147-L150

authz-keycloak plugin not support yet.

**Comment by hellobiek** [comment]
can support this？

**Comment by tzssangglass** [comment]
1. I am not sure if this works well with key-clock.
2. why should support it? Can you show a detailed scenario, or a similar case?

**Comment by hellobiek** [comment]
my scenario: In Chome, If someone visist a url which needs to be protected.
