### ISSUE TITLE
stream_proxy report error

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6333]
### Issue description

Hi ， I enable stream_proxy and listen addr set to 5061, but api6 report error :

**nginx: [emerg] host not found in "map[addr:5061" of the "listen" directive in /usr/local/apisix/conf/nginx.conf:74**

I think it not need host for "listen" directive,but why it need host ?

when i set a host listen 0.0.0.0:5061,  and it report error 

**nginx: [emerg] invalid port in "map[addr:0.0.0.0:5061" of the "listen" directive in /usr/local/apisix/conf/nginx.conf:74**

So what should i do for it ?

### Environment

- apisix version (cmd: `apisix version`):  latest version
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by dantegarden** [comment]
I have the same problem, and the stream proxy function cannot be used.
apisix version is  2.12.1.:q
when I used helm to install  apisix-ingress-controller ，I got this in configmap named apisix:
`stream_proxy:  
    only: false
    tcp: 
    - map[addr:127.0.0.1:13101]`

It looks like the configmap generated from the helm configuration isn't right

**Comment by tzssangglass** [comment]
> stream_proxy:  
>     only: false
>     tcp: 
>     - map[addr:127.0.0.1:13101]

It looks like the wrong format, and again, you need to give the reproduction steps.
