### ISSUE TITLE
request help: forward-auth plugin cann't support request body

### ISSUE THREAD

**Issue by jinghuaz** [apache/apisix#6344]
### Issue description

feat: As a User, I want to use forward-auth plugin but the plugin cann't support request body sent to authorization server to  authentication form request body so that can you plan to do it?

**Comment by starsz** [comment]
Hi @jinghuaz.
Just want to know what's the body should be took when request to the auth server.

**Comment by jinghuaz** [comment]
Hi starsz, In some POST requests, the body will pass in the tenant ID, because our authentication service needs to get the tenant ID.

**Comment by spacewander** [comment]
I think we can add an option to it? 
PR is welcome!

**Comment by jinghuaz** [comment]
nice, only sent header may be not enough，sometimes we need sent body information to auth server with POST method. wait for your message.

**Comment by jwrookie** [comment]
can assigned  to me ?

**Comment by tokers** [comment]
@jwrookie Assigned to you.

**Comment by jinghuaz** [comment]
@jwrookie have any process please remeber update here, thanks...

**Comment by jwrookie** [comment]
> 


> @jwrookie have any process please remeber update here, thanks...

ok
