### ISSUE TITLE
bug: forward-auth configure error when use dashboard operation

### ISSUE THREAD

**Issue by jinghuaz** [apache/apisix#6347]
### Issue description

![image](https://user-images.githubusercontent.com/9525903/154390202-c95e8856-5489-4c0e-bf1b-ebe6ee40daff.png)
forward-auth plugin can not find in the dashboard router config. can use api created then copy it on dashboard.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):
apisix latest

### Steps to reproduce

forward-auth plugin can not find in the dashboard router config. can use api created then copy it on dashboard.

### Actual result

errCode 10000，not found schema

### Error log

errCode 10000，not found schema

**Comment by leslie-tsang** [comment]
Hello there, Please your environment in the description.
> errCode 10000，not found schema

It seems that apisix-dashboard hasn't updated the `forward-auth` schema yet.

**Comment by jinghuaz** [comment]
curl 127.0.0.1:9090/v1/schema > schema.json -->>404 page not found

**Comment by jinghuaz** [comment]
![image](https://user-images.githubusercontent.com/9525903/154393039-0295b3a9-55b4-4dd9-b99a-e79554b6dc3c.png)

**Comment by leslie-tsang** [comment]
AFAIK, Although currently `apisix-dashboard` version `2.10.1` doesn’t support `forward-auth` schema, you can import APISIX version `2.12.1` schema yourself. more detail in [apisix-dashborad docs](https://apisix.apache.org/docs/dashboard/FAQ#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard)

**Comment by jinghuaz** [comment]
I have read this [apisix-dashborad docs](https://apisix.apache.org/docs/dashboard/FAQ#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard), but response 404 page  not found is returned. Confirm that it is 9090 / V1 / schema??

**Comment by leslie-tsang** [comment]
> I have read this [apisix-dashborad docs](https://apisix.apache.org/docs/dashboard/FAQ#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard), but response 404 page not found is returned. Confirm that it is 9090 / V1 / schema??

Oh, I see. In docker deployment mode, you should use `9092` instead of `9090`.

**Comment by jinghuaz** [comment]
Nice!!!Replace schem.json is normal, I will close this issue, thanks!
