### ISSUE TITLE
request help: X-APISIX-Upstream-Status why only 5xx

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#6348]
### Issue description

Why is the return header `x-apisix-upstream-status` only 5xx? why not include all upstream status?

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by starsz** [comment]
Hi @liangliang4ward.
> Added X-APISIX-Upstream-Status header to distinguish 5xx errors from upstream or APISIX itself.
https://github.com/apache/apisix/blob/master/CHANGELOG.md#core-11

As the changelog says, it's used to distinguish 5xx errors from upstream or APISIX itself.

The code is here:
https://github.com/apache/apisix/blob/f37fc0eb77abbf7fdf98ea40ce706d75e5582a4b/apisix/init.lua#L591-L609

The original PR is here:
https://github.com/apache/apisix/pull/2817

**Comment by liangliang4ward** [comment]
> 

yes I know that;

but sometimes 4xx is easily confused with apisix return;

**Comment by spacewander** [comment]
Let's move the discussion to https://github.com/apache/apisix/issues/3963.
