### ISSUE TITLE
request help: Does API6 support upstream backup directive ?

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6350]
### Issue description

Does API6 support upstream backup directive

upstream {
server aa.xx.xx.com;
server bb.xx.com backup;
}

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
We can use `priority` in the `nodes`:

> Each node can be configured with a priority. A node with low priority will only be used when all the nodes with higher priority are unavailable or tried.
> As the default priority is 0, we can configure nodes with negative priority as the backup.

https://apisix.apache.org/docs/apisix/admin-api#request-body-parameters-3

**Comment by shidaxi** [comment]
Hi @spacewander , how to config priority in stand-alone mode?
