### ISSUE TITLE
request help:  Can't build image - apisix-docker/all-in-one-dashboard

### ISSUE THREAD

**Issue by WeiWANG0118** [apache/apisix#6353]
### Issue description

Hello, 

I can't build the image apisix-docker/all-in-one-dashboard/Dockerfile. 

Here are the logs: 
```
#37 628.4 
#37 628.4 Why you should do it regularly:
#37 628.4 https://github.com/browserslist/browserslist#browsers-data-updating
#37 1037.7 error Command failed with signal "SIGKILL".
#37 1037.7 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c if [ "$ENABLE_PROXY" = "true" ] ; then yarn config set registry https://registry.npmmirror.com/ ; fi     && yarn install     && yarn build]: exit code: 1
make: *** [build-dashboard] Error 1
```

### Environment
I add the command to build image in Makefile. 
```
- .PHONY: build-dashboard
build-dashboard:
	@$(call func_echo_status, "$@ -> [ Start ]")
	$(ENV_DOCKER) build -t $(APISIX_DASHBOARD_IMAGE_NAME):$(APISIX_DASHBOARD_VERSION) -f ./all-in-one/apisix-dashboard/Dockerfile .
	@$(call func_echo_success_status, "$@ -> [ Done ]")
```

**Comment by tokers** [comment]
> #37 1037.7 error Command failed with signal "SIGKILL".

It's terminated by the Kill signal.

**Comment by WeiWANG0118** [comment]
> > #37 1037.7 error Command failed with signal "SIGKILL".
> 
> It's terminated by the Kill signal.

**Comment by WeiWANG0118** [comment]
Yes, but why did it happen? And how to resolve it?

**Comment by tokers** [comment]
> Yes, but why did it happen? And how to resolve it?

Cannot get the result without any other information. Is it reproduced every time you running it?

**Comment by WeiWANG0118** [comment]
> > Yes, but why did it happen? And how to resolve it?
> 
> Cannot get the result without any other information. Is it reproduced every time you running it?

Yes. Everytime, so I can't build the image all-in-one/dashboard. I don't know if it just happens to me or what. It's depressing.

**Comment by leslie-tsang** [comment]
Actually, you don't have to do so.

`build-dashboard` deprecated via [apisix-docker PR 259](https://github.com/apache/apisix-docker/pull/259)

`make build-dashboard-centos` or `make build-dashboard-alpine` can be used instead.

**Comment by WeiWANG0118** [comment]
> Actually, you don't have to do so.
> 
> `build-dashboard` deprecated via [apisix-docker PR 259](https://github.com/apache/apisix-docker/pull/259)
> 
> `make build-dashboard-centos` or `make build-dashboard-alpine` can be used instead.

It's really hard for new comers to deploy their own apisix service.

**Comment by leslie-tsang** [comment]
> It's really hard for new comers to deploy their own apisix service.

It's not recommended for newbie to build their own apisix images. 

Make your life easier by using docker-compose. more detail in [quickstart-via-docker-compose](https://github.com/apache/apisix-docker#quickstart-via-docker-compose)
