### ISSUE TITLE
bug: proxy is not working to some website

### ISSUE THREAD

**Issue by RexHuang** [apache/apisix#6355]
### Issue description

use dashboard to create a proxy to kubernetes.io is not working, while the same setting can proxy to github.com.
see the setings as below:
{
  "uri": "*",
  "name": "kubernetes.io",
  "vars": [
    [
      "http_msisdn",
      "==",
      "13900000002"
    ]
  ],
  "plugins": {
    "ext-plugin-pre-req": {
      "disable": true,
      "name": "FooFilter",
      "value": "bar"
    },
    "prometheus": {
      "disable": false
    },
    "proxy-rewrite": {
      "host": "kubernetes.io",
      "scheme": "https"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "kubernetes.io",
        "port": 443,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "https",
    "pass_host": "node",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}

### Environment

- apisix version (cmd: `apisix version`): 2.6
- OS (cmd: `uname -a`): Linux node1 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): unknown
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0
- apisix-dashboard version, if have: 2.10.1
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner): unknown
- luarocks version, if the issue is about installation (cmd: `luarocks --version`): unknown

### Steps to reproduce

1. use dashboard to create the proxy as the export settings (change host name which you want to proxy).
2. use browser to access xxxx:9080, with ModHeader, set request header "msisdn=13900000002"
3. it can proxy to github.com, but can not proxy to kubernetes.io

### Actual result

proxy to github.com it can goes to github.com,
proxy to kubernetes.io, it seems the rule is not been used.

### Error log

no error log

### Expected result

should be able to proxy to kubernetes.io

**Comment by tzssangglass** [comment]
Proxy to kubernetes.io What is the response you get?

AFAIK, some websites refuse to be accessed by proxy servers.

**Comment by jwrookie** [comment]
I tried it according to your configuration, and it works fine

apisix version: `2.12.0`

please give more detailed response info, and i think it is caused by network problems

**Comment by RexHuang** [comment]
> I tried it according to your configuration, and it works fine
> 
> apisix version: `2.12.0`
> 
> please give more detailed response info, and i think it is caused by network problems

after upgrade to 2.12.0, it works fine. Thanks~
