### ISSUE TITLE
feat: Could modify the max array length of labels to the entry value in the configuration yaml

### ISSUE THREAD

**Issue by TkClark** [apache/apisix#6356]
### Issue description

Now. The maximum array length of labels in schema_def.lua is 16.
![image](https://user-images.githubusercontent.com/10162966/154447787-7de7385b-c50c-41d8-9ec4-10171ee45649.png)

Could the max array length be modified to the entry value in the configuration yaml

**Comment by mangoGoForward** [comment]
I'd like to tackle this issue, seems we can remove this line to remove restriction for the max array length.

https://github.com/apache/apisix/blob/f7b50f28bae7ca6ed373fe7c1ea07e658a6bee3f/apisix/schema_def.lua#L97

**Comment by TkClark** [comment]
yep，we just want this modified by official team. Than we can use the docker image. hahaha~

**Comment by mangoGoForward** [comment]
> yep，we just want this modified by official team. Than we can use the docker image. hahaha~

Maybe you can commit a PR to help official team to solve, and you can get an image what you wanted also.
