### ISSUE TITLE
feat: (openid-connect plugin) As a User, I want to return back to redirect_uri after logout completed so that I can continue browsing the application (a ui app for instance)

### ISSUE THREAD

**Issue by mongudu** [apache/apisix#6362]
### Issue description

As far as I see, the plugin  (openid-connect) has capability to logout user. But I am not sure about that the plugin is capable to return back to a url after the logout? (for instance https://127.0.0.1/shopping/car)

cc @starsz

**Comment by starsz** [comment]
Good feature! I think we can support it.

**Comment by moonming** [comment]
@starsz do you have a plan to do this? thx

**Comment by starsz** [comment]
> @starsz do you have a plan to do this? thx

Yes. I will submit a PR to do it this week.

**Comment by starsz** [comment]
@mongudu Supported.
