### ISSUE TITLE
feat: As a User, I want to have the port in the Host header when `pass_host = node` and the port is not standard

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#6366]
### Issue description

feat: As a User, I want to have the port in the Host header when `pass_host = node` and the port is not standard, so that we can solve the problem in https://github.com/apache/apisix/issues/6296 in a better way when:

1. the port in the Host header is checked
2. multiple nodes which have different host name

**Comment by wilson-1024** [comment]
can we modify the host in (apisix/apisix/balancer.lua lines 333-340)?
```java
        if pass_host == "node" and balancer.recreate_request then
            local host = server.domain or server.host
            if host ~= ctx.var.upstream_host then
                -- retried node has a different host
                ctx.var.upstream_host = host
                header_changed = true
            end
        end

**Comment by spacewander** [comment]
Yes, and note that this part is retry.
You should also modify:
https://github.com/apache/apisix/blob/9b0460fb68e26d3fc1e8eac6659794598ce859ac/apisix/init.lua#L263-L265

And the standard port map can be found in https://github.com/apache/apisix/blob/9b0460fb68e26d3fc1e8eac6659794598ce859ac/apisix/upstream.lua#L170. (You might need to refactor it)

**Comment by wilson-1024** [comment]
ok.Thank you for your guidance

**Comment by spacewander** [comment]
@wilson-1024 
Would you like to work for it?

**Comment by wilson-1024** [comment]
@spacewander Yes.I want to try to implement this function
