### ISSUE TITLE
docs: need to update https://apisix.apache.org/zh/docs/apisix/plugin-develop/

### ISSUE THREAD

**Issue by shenzhuangzhi1** [apache/apisix#6369]
### Improved or typo fixed.

https://apisix.apache.org/zh/docs/apisix/plugin-develop/ should be update.

### Solution

I'll update it. Update Chinese documents to be consistent with English documents.

**Comment by zaunist** [comment]
Thanks for your contribution.

**Comment by lijing-21** [comment]
Hi @shenzhuangzhi1 , thank you for your contribution!

Here is the Contributor T-shirt form[1], if you're interested, kindly take a look :)

[1] https://github.com/apache/apisix/blob/master/CONTRIBUTING.md#contributor-t-shirt
