### ISSUE TITLE
feature: supported cluster limit-req with redis server.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#638]
take a look: take an example: https://github.com/iresty/apisix/pull/624

**Comment by membphis** [comment]
supported: https://github.com/apache/incubator-apisix/blob/master/doc/plugins/limit-count.md#attributes

**Comment by liuhengloveyou** [comment]
Is it the same requirement as the limit-count?

**Comment by membphis** [comment]
> Is it the same requirement as the limit-count?

yes, almost the same.
