### ISSUE TITLE
docs: Discrepancies in "Getting Started" and "How to build Apache APISIX" pages 

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix#6380]
### Improved or typo fixed.

The "[Getting Started](https://apisix.apache.org/docs/apisix/getting-started)" page walks the user through an installation of APISIX using Docker. It is however mentioned [here](https://github.com/apache/apisix-docker#readme) that these Docker images are not official ASF images and users should always build from source.

There isn't a link to other installation methods in the "Getting Started" page.

There isn't an "Installation" page but instead "[How to build Apache APISIX](https://apisix.apache.org/docs/apisix/how-to-build)" which might be misleading as readers might think that it would be a guide to build the source for say, development purposes.

### Solution

Proposal:

1. Change "Getting Started" to "Quick Start" and make the intent clear that it is a guide to quickly run APISIX and test/play-around with it.
2. Add more internal links to the new "Quick Start" guide pointing people to other installation methods and end-to-end guides (future).
3. Change "How to build Apache APISIX" to "Installation" and provide a comprehensive guide on installing APISIX via different methods.
4. Other suggestions?

**Comment by navendu-pottekkat** [comment]
I can open up a PR after we discuss these proposed changes.

**Comment by jwrookie** [comment]
LGTM, but change `Getting Started` and  `How to build Apache APISIX`  titile maybe not significant.

welcome to discuss.

**Comment by navendu-pottekkat** [comment]
My intention with this change was to direct users to other installation methods as well in the "Getting Started" guide. Now that I think about it, the title could remain unchanged and we can interlink each of the two pages.

Do you think there is a specific reason why "How to build Apache APISIX" should not be changed to installation?

**Comment by jwrookie** [comment]
According to the guide, it describes different ways to install and also how to build a custom `apisix`, so I think the existing title might be better, don't you?

**Comment by kwanhur** [comment]
Definitely point out potential users with the two pages, then discuss how to express precisely could be better.

`getting-started` for the viewers how to have a try.

 `how-to-build` seems for those users who want to build and install with different ways, it supports building guides and installation guides.

**Comment by navendu-pottekkat** [comment]
I will draft a PR and we can discuss further changes there. It would be best to have something tangible to work with.
