### ISSUE TITLE
request help: Mutual TLS with client san validation

### ISSUE THREAD

**Issue by lijian-sw** [apache/apisix#6393]
### Issue description

Hi,

I have seen and tested Apisix can successfully do client authentication based on client SSL certificates.

But what I miss in this client certificate authentication is the SAN validation.
So in other words, how to ensure Apisix validates the client ip with the value specified in the client certificate (SAN or CN).

For what I have tested this validation does not take place, which results in a client certificate which still can be shared and used by multiple clients, are there any options within Apisix to ensure such validation can take place?

Am I overlooking something here?

### Environment

- apisix version (cmd: `apisix version`): 2.11.0
- OS (cmd: `uname -a`): Linux 3.10.0
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API): 3.4.0

**Comment by tzssangglass** [comment]
AFAIK, we don't support san verification yet. But I have implemented a similar function, code like

```
local ssl = require("ssl")
local san = ssl.loadcertificate(raw_cert):extensions()
```

by this way, we can get san, but it seems that this function is blocking.

**Comment by tokers** [comment]
> AFAIK, we don't support san verification yet. But I have implemented a similar function, code like
> 
> ```
> local ssl = require("ssl")
> local san = ssl.loadcertificate(raw_cert):extensions()
> ```
> 
> by this way, we can get san, but it seems that this function is blocking.

The fetching result can be cached with the LRU.
