### ISSUE TITLE
bug:  systemd will cause process stop when apisix is started by command

### ISSUE THREAD

**Issue by Lewisyixin** [apache/apisix#6401]
### Issue description

When apisix was started by the command 'apisix start', then using systemd to start apisix will cause the process to shut down. 
This may not be a bug exactily. But if in a production environment, one engineer starts process whth the former method, and another engineer uses systemd to execute the startup again, it may cause bad effects.

![image](https://user-images.githubusercontent.com/17898688/154947729-9e570faf-e875-4c80-b595-ab0b579d6e78.png)

One way to avoid this problem is adding 'RemainAfterExit=yes' in apisix.service.

### Environment

- apisix version (cmd: `apisix version`):2.12.1
- OS (cmd: `uname -a`): Linux apisix 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 13:29:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):nginx version: openresty/1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):etcd-v3.5.1
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

apisix start
systemctl status apisix
systemctl stop apisix
systemctl status apisix

### Actual result

Porcess shutdown

### Error log

no need

### Expected result

systemctl start apisix  will not cause process shutdown

**Comment by kwanhur** [comment]
It results in the cross operations between manually and systemd.

If operates only by manually or systemd, the result will not come out.

**Comment by Lewisyixin** [comment]
> It results in the cross operations between manually and systemd.
> 
> If operates only by manually or systemd, the result will not come out.

Right , but we just made mistakes in our QA env.  One engineer started by commond, the other used 'systemctl status' and thought the process was not started then  used 'systemd start' and finally found process was stoped. 
So if  'RemainAfterExit=yes' can be adding in apisix.service if it doesn't cause ohter errors?

**Comment by spacewander** [comment]
Is RemainAfterExit suitable for a proxy? I don't think so after reading https://stackoverflow.com/questions/38072849/when-should-the-option-remainafterexit-needs-to-be-set-true-when-creating-new-sy.

The same behavior happens if the engineer starts Nginx with `nginx -p . start` and stops it with systemctl.
