### ISSUE TITLE
request help: how to run test case at my machine

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#6408]
### Issue description

I execut cmd like this:
```shell
prove -I. -I../test-nginx/inc -I../test-nginx/lib -r t/node/upstream-status-all.t
```
error log like this:
```shell
#   Failed test 'TEST 1: set route(id: 1) and available upstream and enable_all_upstream_status: true - status code ok'
#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 948.
#          got: '500'
#     expected: '200'
```

how to run apisix instance at test and url like /hello

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`): centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by Chever-John** [comment]
Can you provide us with more info?
And executing `uname -a` will not return `linux`.

**Comment by liangliang4ward** [comment]
> Can you provide more info?
> 
> > run apisix instance at test
> > What this means is, are you having problems running APISIX test cases?
> 
> And executing `uname -a` will not return `linux`.

I use windows os and wsl run Centos7

**Comment by Chever-John** [comment]
Can you provide more information so that we can reproduce the problem? 
For example, you can provide your test files and the procedures for executing commands

**Comment by liangliang4ward** [comment]
test case :
https://github.com/liangliang4ward/apisix/blob/feature/resp-all-upstream-status/t/node/upstream-status-all.t

exe cmd : 
```shell
prove -I. -I../test-nginx/inc -I../test-nginx/lib -r t/node/upstream-status-all.t
```

**Comment by shenzhuangzhi1** [comment]
Maybe a dosc is needed about how to run test. 👍

**Comment by spacewander** [comment]
You can refer to https://github.com/apache/apisix/blob/master/docs/en/latest/internal/testing-framework.md

**Comment by liangliang4ward** [comment]
> You can refer to https://github.com/apache/apisix/blob/master/docs/en/latest/internal/testing-framework.md

I know that..

but when test case like `add route` occur error; I don't know how to do ..

```shell
#   Failed test 'TEST 1: set route(id: 1) and available upstream and show_upstream_status_in_response_header: true - status code ok'
#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 948.
#          got: '500'
#     expected: '200'

#   Failed test 'TEST 1: set route(id: 1) and available upstream and show_upstream_status_in_response_header: true - response_body - response is expected (repeated req 0, req 0)'
#   at /usr/local/share/perl5/Test/Nginx/Socket.pm line 1589.
#          got: '<!DOCTYPE html>
# <html>
# <head>
# <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
# <meta content="utf-8" http-equiv="encoding">
# <title>500 Internal Server Error</title>
# <style>
#     body {
#         width: 35em;
#         margin: 0 auto;
#         font-family: Tahoma, Verdana, Arial, sans-serif;
#     }
# </style>
# </head>
# <body>
# <h1>An error occurred.</h1>
# <p>You can report issue to <a href="https://github.com/apache/apisix/issues">APISIX</a></p>
# <p><em>Faithfully yours, <a href="https://apisix.apache.org/">APISIX</a>.</em></p>
# </body>
# </html>
# '
#     expected: 'passed
# '
```

**Comment by liangliang4ward** [comment]
need to do this.
https://github.com/api7/test-toolkit

**Comment by Chever-John** [comment]
> need to do this. https://github.com/api7/test-toolkit

Morning!
It's nice to see that you can work things out on your own.

**Comment by liangliang4ward** [comment]
when log "nginx: [emerg] unknown directive "lua_package_path" in /opt/workspace/apisix/t/servroot/conf/nginx.conf:30"

ref: https://github.com/apache/apisix/issues/1232

**Comment by leslie-tsang** [comment]
> when log "nginx: [emerg] unknown directive "lua_package_path" in /opt/workspace/apisix/t/servroot/conf/nginx.conf:30"
> 
> ref: #1232

It seems you are not using OpenResty.

BTW, Please open a new issue to track it.

**Comment by liangliang4ward** [comment]
> > when log "nginx: [emerg] unknown directive "lua_package_path" in /opt/workspace/apisix/t/servroot/conf/nginx.conf:30"
> > ref: #1232
> 
> It seems you are not using OpenResty.
> 
> BTW, Please open a new issue to track it.

I just record it.
