### ISSUE TITLE
feat: As a User, I want to use SM3 so that a plugin of sm3-auth is necessary

### ISSUE THREAD

**Issue by shenzhuangzhi1** [apache/apisix#6409]
### Issue description

`SM3` is a cryptographic hash function standard adopted by the government of the people's Republic of China and issued by the state cryptographic administration. Relevant standard is `GM/T 0004-2012`

**Comment by spacewander** [comment]
Could you explain why we need to use a cryptographic hash function with authentication? There is no md5-auth plugin.

**Comment by shenzhuangzhi1** [comment]
> Could you explain why we need to use a cryptographic hash function with authentication? There is no md5-auth plugin.

`hmac-auth` has three kind of algorithms: `hmac-sha1`, `hmac-sha256`, `hmac-sha512`. I think that `sm3` is saftier than others

**Comment by spacewander** [comment]
OK, so it will be the hmac-sm3. I will keep this issue open to see if it's worth doing.

**Comment by shenzhuangzhi1** [comment]
> OK, so it will be the hmac-sm3. I will keep this issue open to see if it's worth doing.
ohh, its excited, thanks

**Comment by fanchangjifen** [comment]
Sm secret key is involved in our business, may I ask whether there is an access plan

**Comment by spacewander** [comment]
@fanchangjifen 
Would you like to contribute?

**Comment by Hxhong** [comment]
SM algorithm has been widely used in China. The security of Sm3 algorithm is higher than MD5 algorithm and SHA-1 algorithm, and the security of SM4 algorithm is higher than 3DES algorithm. The demand for SM3 encryption will be increasing.

**Comment by fanchangjifen** [comment]
> @fanchangjifen Would you like to contribute?

Our team is engaged in the development of digital government business, which may be different from Internet business scenarios. So we wanted to figure out how we could offer hMAC-SM3 or standalone plug-ins. Note that the SM3 plugin has a lot of dependencies and we need to provide simplified technical support

**Comment by soulbird** [comment]
> 

You can refer to the [hmac-auth](https://github.com/apache/apisix/blob/master/apisix/plugins/hmac-auth.lua) plugin, and the sm3 algorithm may directly refer to https://github.com/toruneko/lua-resty-crypto/blob/master/lib/resty/digest/sm3.lua

**Comment by soulbird** [comment]
> > @fanchangjifen Would you like to contribute?
> 
> Our team is engaged in the development of digital government business, which may be different from Internet business scenarios. So we wanted to figure out how we could offer hMAC-SM3 or standalone plug-ins. Note that the SM3 plugin has a lot of dependencies and we need to provide simplified technical support

You can refer to the [hmac-auth](https://github.com/apache/apisix/blob/master/apisix/plugins/hmac-auth.lua) plugin, and the sm3 algorithm may directly refer to https://github.com/toruneko/lua-resty-crypto/blob/master/lib/resty/digest/sm3.lua

**Comment by shenzhuangzhi1** [comment]
> > > @fanchangjifen Would you like to contribute?
> > 
> > 
> > Our team is engaged in the development of digital government business, which may be different from Internet business scenarios. So we wanted to figure out how we could offer hMAC-SM3 or standalone plug-ins. Note that the SM3 plugin has a lot of dependencies and we need to provide simplified technical support
> 
> You can refer to the [hmac-auth](https://github.com/apache/apisix/blob/master/apisix/plugins/hmac-auth.lua) plugin, and the sm3 algorithm may directly refer to https://github.com/toruneko/lua-resty-crypto/blob/master/lib/resty/digest/sm3.lua

We done,thank you so much!
