### ISSUE TITLE
request help: mTLS Between APISIX and Upstream

### ISSUE THREAD

**Issue by whioue** [apache/apisix#6410]
### Issue description

1. I would like to ask mTLS Between APISIX and Upstream. If so, why is it that only the client certificate and key are configured when configuring the upstream, and the mTLS Between APISIX and Upstream can be completed without configuring the CA certificate？
2. 我通过抓包进行分析，发现客户端与apisix之间进行了一个完整且正常的双向认证，apisix与服务端之间也是进行一个完整的双向认证，但是apisix作为客户端与服务端进行双向认证是未校验服务端的证书，请问一下这样做的原因是什么？

### Environment

- apisix version (cmd: `apisix version`):v2.8
- OS (cmd: `uname -a`): linux centos7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by whioue** [comment]
我通过抓包进行分析，发现客户端与apisix之间进行了一个完整且正常的双向认证，apisix与服务端之间也是进行一个完整的双向认证，但是apisix作为客户端与服务端进行双向认证是未校验服务端的证书，请问一下这样做的原因是什么？

**Comment by tzssangglass** [comment]
we can set [proxy_ssl_trusted_certificate](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_ssl_trusted_certificate) by using [customize-nginx-configuration](https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md), and would you like to submitting a PR improvement documen?

we need improve here: https://github.com/apache/apisix/blob/master/docs/en/latest/mtls.md#mtls-between-apisix-and-upstream

**Comment by tzssangglass** [comment]
and we can do some optimization, if set `ssl_trusted_certificate` in `config.yaml`, let the template set automatically `proxy_ssl_trusted_certificate` same as `ssl_trusted_certificate` in `nginx.conf`.

**Comment by whioue** [comment]
> 并且我们可以做一些优化，如果设置`ssl_trusted_certificate`在 中`config.yaml`，让模板自动设置和在中`proxy_ssl_trusted_certificate`一样。`ssl_trusted_certificate``nginx.conf`
如您上述所属，只能在.yaml文件中固定死需要设置的ca证书，我的理解有误吗？如果是的话，是不是不太灵活呢？为什么没有在upstream中设置client_ca字段用来验证服务端的证书？后续有这方面的优化吗？

**Comment by tzssangglass** [comment]
> 如您上述所属，只能在.yaml文件中固定死需要设置的ca证书

yes

> 为什么没有在upstream中设置client_ca字段用来验证服务端的证书？后续有这方面的优化吗？

Given the reality that different upstream certificates may be issued by different CAs, making `ssl_trusted_certificate` dynamic is an optimization worth thinking about.

**Comment by tzssangglass** [comment]
> 后续有这方面的优化吗？

Do you have any suggestions?
