### ISSUE TITLE
bug: lj_str_new high CPU usague when performance testing with about 10k http request body

### ISSUE THREAD

**Issue by lizj3624** [apache/apisix#6412]
### Issue description

 lj_str_new high CPU usague when performance testing with about 10k http request body，I  think it's ngx_lua promble, [ngx_lua issue](https://github.com/openresty/lua-nginx-module/issues/2015)，apisix tested similar case and encountered similar problems?

lj_str_new high cpu usague when access_by_lua of ngx_lua
![ME1645502052074](https://user-images.githubusercontent.com/1217777/155062693-decb2939-5ec4-42c1-a102-f7b4189ea871.jpg)

### Environment

- OS (cmd: `uname -a`): Centos6
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): OpenResty-1.15.8
- CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
- worker num: 15
- http request 8k ~10k，10w qps

### Steps to reproduce

1. performance testing with about 10k http request body
2. access_by_lua enabled

### Actual result

lj_str_new high CPU usague 

### Error log

lj_str_new high CPU usague

**Comment by tzssangglass** [comment]
ok, are you comfortable generating a flamegraph of your test case?

you can ref: https://github.com/apache/apisix/blob/master/.github/workflows/performance.yml

**Comment by lizj3624** [comment]
I guress it's ngx_lua bug，i closed the issue in apisix， [ngx_lua issue](https://github.com/openresty/lua-nginx-module/issues/2015)
