### ISSUE TITLE
Consolidate issue/PR labels across all APISIX repos

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix#6413]
### Proposal

Apache APISIX has different repos housing different sub-projects and the project website. Each of these repos use labels that are not centralised to the project and does not have parity.

Moreover, the labels used are not comprehensive and semantic and does very little to convey information to contributors and project maintainers alike.

This is a proposal to create issue/PR labels that can be used across all APISIX repos that is clear, comprehensive and could be used for automatic labelling.

The labels proposed here—or a subset of it—could be used across all APISIX repos.

These proposed labels are an initial draft and it would be helpful if seasoned contributors and maintainers could help in identifying more labels or suggest any changes.

The proposal is documented in this doc: [Apache APISIX - Labels for Issues and PRs](https://docs.google.com/document/d/1eN59H3rojJRC1ey9CSANU4slF38idZCw_7nvm4NGwyc/edit?usp=sharing)

Please let me know if there is a community drive where we can host this file so that everyone can edit it.

**Comment by gxthrj** [comment]
Cool~
Looks good and detailed.

**Comment by tzssangglass** [comment]
great idea, and I left a comment on that docs.

**Comment by juzhiyuan** [comment]
> Please let me know if there is a community drive where we can host this file so that everyone can edit it.

Actually no, we use mailing list or GitHub issue to track and discuss.

**Comment by juzhiyuan** [comment]
I'm not sure if we really need those many labels 😅 because those labels are enough for me, let's wait for other maintainers ideas.

**Comment by shuaijinchao** [comment]
cool, using `labels` can indeed describe `issues/pr` more clearly. unfortunately, currently projects under Apache cannot use `bot` to manage these tags, which will result in a lot of labor costs to maintain these `labels`.

**Comment by navendu-pottekkat** [comment]
Also, most of these labels would be directly applied from the issue forms. So there is less manual work.

**Comment by shuaijinchao** [comment]
> @shuaijinchao Okay. Then we can reduce the number of labels to only those that are required and can be maintained easily. This is also to @juzhiyuan 's point.

Great.

**Comment by juzhiyuan** [comment]
Hi, I understand you intend to help better open-source users find target issues and help maintainers better maintain the community by a set of labels. Those current labels already meet my needs, and I would prefer to hear more from active maintainers in this repo. 🤗 

cc @shuaijinchao @spacewander @membphis @leslie-tsang

**Comment by navendu-pottekkat** [comment]
Yes. Suggestions would be good. If adding more labels makes it difficult to maintain, then we shouldn't probably do it but if it helps create a contributor funnel or make it easy to triage issues and help maintainers, we could do it.

If no change is needed, we can just rewrite the labels to be more neat and consistent. For example "wait for reproduce: Can't be reproduced at my side" could be changed to "cannot reproduce: Issue cannot be reproduced.".

**Comment by leslie-tsang** [comment]
> Those current labels already meet my needs

Agree.

> If no change is needed, we can just rewrite the labels to be more neat and consistent

One vote for this solution for now, need more detail of how to make it work.

**Comment by spacewander** [comment]
> If no change is needed, we can just rewrite the labels to be more neat and consistent. 

Is there a standard to determine `more neat and consistent`?

**Comment by navendu-pottekkat** [comment]
> > If no change is needed, we can just rewrite the labels to be more neat and consistent.
> 
> Is there a standard to determine `more neat and consistent`?

😅  Not really. It would just be a line so making it short and grammatically correct should be enough.

**Comment by membphis** [comment]
> I'm not sure if we really need those many labels 😅 because those labels are enough for me, let's wait for other maintainers ideas.

I have same issue. Too many labels would be more complicated for me and community.

**Comment by juzhiyuan** [comment]
> I have same issue.

Hi @membphis, do you mean "questions/concern" rather than "issue", right?

**Comment by membphis** [comment]
> Hi @membphis, do you mean "questions/concern" rather than "issue", right?

you are right. I means `questions` .
