### ISSUE TITLE
docs: change to English version

### ISSUE THREAD

**Issue by membphis** [apache/apisix#6414]
### Improved or typo fixed.

https://github.com/apache/apisix/pull/6215/files#r803272780

it is Chinese.

### Solution

We need to translate Chinese to English

**Comment by spacewander** [comment]
There is already an English one?
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md
Do you mean fixing the table in it?

**Comment by mangoGoForward** [comment]
[As the discussion said](https://github.com/apache/apisix/pull/6215#discussion_r808727629). the content of table header is Chinese in En doc, and I'd like to tackle this issue.
