### ISSUE TITLE
bug: One of the three PODs of etcd, has been reporting an error and restarting.

### ISSUE THREAD

**Issue by elricli** [apache/apisix#6419]
### Issue description

Screenshot:
![image](https://user-images.githubusercontent.com/11224565/155100421-ddc1a8e5-21f4-498f-b9a0-99208e1142f4.png)

### Environment

- apisix version (cmd: `apisix version`): 2.12.0-alpine
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): nginx version: openresty/1.19.9.1
- etcd version: 3.4.16-debian-10-r14

### Steps to reproduce

Unable to give the reproduce step.

### Actual result

Etcd pod alway restart.

### Error log

error log:
```
 etcd 09:13:06.78 
 etcd 09:13:06.78 Welcome to the Bitnami etcd container
 etcd 09:13:06.78 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-etcd
 etcd 09:13:06.78 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-etcd/issues
 etcd 09:13:06.78 
 etcd 09:13:06.78 INFO  ==> ** Starting etcd setup **
 etcd 09:13:06.80 INFO  ==> Validating settings in ETCD_* env vars..
 etcd 09:13:06.80 WARN  ==> You set the environment variable ALLOW_NONE_AUTHENTICATION=yes. For safety reasons, do not use this flag in a production environment.
 etcd 09:13:06.81 INFO  ==> Initializing etcd
 etcd 09:13:06.82 INFO  ==> Detected data from previous deployments
 etcd 09:13:17.22 INFO  ==> Updating member in existing cluster
 {"level":"warn","ts":"2022-02-22T09:13:22.669Z","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-871aa038-c241-4a50-94bf-cf3c9a264fe7/172-16-192-125.apisix-etcd.ingress-apisix.svc.cluster.local:2379","attempt":0,"error":"rpc error: code = NotFound desc = etcdserver: member not found"}
 Error: etcdserver: member not found
```

**Comment by jwrookie** [comment]
Try removing it from an existing cluster and then rejoining

**Comment by tzssangglass** [comment]
Is this an ETCD related issue and not an APISIX issue?

**Comment by drrrMikado** [comment]
> Is this an ETCD related issue and not an APISIX issue?

Maybe. [etcd-io/etcd/issues/13196.](https://github.com/etcd-io/etcd/issues/13724)

**Comment by zhangyihong** [comment]
I have the same problem. How to fix it?

apisix:  apache/apisix:2.13.1-alpine
etcd: bitnami/etcd:3.4.18-debian-10-r14

**Comment by tokers** [comment]
I think it's better to ask for advice from the ETCD community.
