### ISSUE TITLE
request help:  I need two backend

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6420]
### Issue description

I want have two  upstream , if  one return error, it colud fallback  to the other upstream,

For example :

client request http://aa.bb.com/test   default backend is proxy_pass to   **http://10.100.22.11**,  if it return error  or healthcheck error , the request should fallback to **https://cc.dd.com**,   note that the first is http ,the second is https,
so what should i do for it?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by starsz** [comment]
Hi @purekeeper.
You can set `https://cc.dd.com/` with negative priority.

> As the default priority is 0, we can configure nodes with negative priority as the backup.
Refer to the doc: https://apisix.apache.org/docs/apisix/admin-api

**Comment by Chever-John** [comment]
If I understand you correctly, I think [this](https://apisix.apache.org/docs/apisix/admin-api/#:~:text=https%20is%20valid.-,Note%3A,-Each%20node%20can) is what you mean.
Just to validate my idea.
Thinks!

**Comment by purekeeper** [comment]
@Chever-John @starsz    Thanks for reply, please note the default backend is http  protocal   , falback to https protocal,  as my understand the node priority have to keep  same protocal ,right ?   Thants means we can't write like

 "nodes": [
            {"host": "**http**://127.0.0.1", "port": 1980, "weight": 2000},
            {"host": "**https**://10.100.22.33", "port": 1981, "weight": 1, "priority": -1}
        ],

right  ?

**Comment by tokers** [comment]
Yeah, currently the `scheme` is on the upstream level.

**Comment by starsz** [comment]
> @Chever-John @starsz Thanks for reply, please note the default backend is http protocal , falback to https protocal, as my understand the node priority have to keep same protocal ,right ? Thants means we can't write like
> 
> "nodes": [ {"host": "**http**://127.0.0.1", "port": 1980, "weight": 2000}, {"host": "**https**://10.100.22.33", "port": 1981, "weight": 1, "priority": -1} ],
> 
> right ?

Yes.As @tokers said.
