### ISSUE TITLE
docs: For L7 proxy -> For L4 proxy

### ISSUE THREAD

**Issue by AlexAi27** [apache/apisix#6421]
### Improved or typo fixed.

https://github.com/apache/apisix/blob/master/docs/en/latest/admin-api.md?plain=1#L557

### Solution

For L7 proxy -> For L4 proxy

**Comment by starsz** [comment]
Good capture! Can you submit a PR to fix it?

**Comment by liangliang4ward** [comment]
> Good capture! Can you submit a PR to fix it?

let me fix it?
