### ISSUE TITLE
request help: After writing data to different KFK clusters in the custom plugin, kafka-logger does not work properly

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#6422]
### Issue description

When a custom plugin is added to apisix, resty.kafka.producer is referenced in the plugin to record a specific log, which causes kafka-logger to fail to work properly. From the log information, it is found that the same topic used by both plugins, but The custom plugin and kafka-logger are configured with different topic names, whether only one producer can exist in the plugin or resty.

@tzssangglass @membphis @spacewander @moonming 

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):centos 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19.9.1
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by membphis** [comment]
pls make a try with the latest version `2.12.1`

**Comment by tzssangglass** [comment]
If you need to regenerate the kafka producer, change the `cluster_name`.

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/kafka-logger.md

**Comment by sandy420** [comment]
> If you need to regenerate the kafka producer, change the `cluster_name`.
> 
> ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/kafka-logger.md

ok,tks
