### ISSUE TITLE
bug: No spaces are allowed in the configuration file

### ISSUE THREAD

**Issue by ccwall3** [apache/apisix#6425]
### Issue description

<img width="644" alt="057f5c3c4a39e3d3dc5eccd5a72cfae" src="https://user-images.githubusercontent.com/7711718/155259003-f751781d-3fed-4076-a5a5-8fea1ea2e317.png">
启动报错
failed to read local yaml config of apisix: failed to merge, path[plugin_attr->log-rotate->enable_compression] expect: boolean, but got: string

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

pass

### Actual result

pass

### Error log

pass

**Comment by zaunist** [comment]
Hi, @ccwall3. Could you check if there are any spaces after `false`, and if there are, you need to remove them.

**Comment by tokers** [comment]
@ccwall3 Could you explain the meaning of the red rectangles in your screenshoot?

**Comment by tzssangglass** [comment]
On the left side of the image, the `plugin_attr` on `log-rotate` is misconfigured.

> 启动报错 failed to read local yaml config of apisix: failed to merge, path[plugin_attr->log-rotate->enable_compression] expect: boolean, but got: string

You can try delete this line and rewrite it

**Comment by spacewander** [comment]
Closed as lack of response. Feel free to reopen it if need.
