### ISSUE TITLE
request help: log-rotate -- "send USER1 signal to master process [88584] for reopening log file"

### ISSUE THREAD

**Issue by sandy420** [apache/apisix#6427]
### Issue description

![image](https://user-images.githubusercontent.com/10955441/155297794-5e5ebd40-ffd7-4481-967c-4e8ba0946aeb.png)

What is the reason for the above picture

### Environment

- apisix version (cmd: `apisix version`):2.10.1
- OS (cmd: `uname -a`):centos 7
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):1.19
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
Do not worry, it is normal, you can read `Rotating Log-files` on http://nginx.org/en/docs/control.html

**Comment by shuaijinchao** [comment]
thx~ @tzssangglass  , @sandy420  my opinion is the same as @tzssangglass.

**Comment by sandy420** [comment]
thx
