### ISSUE TITLE
request help: authz-keycloak 

### ISSUE THREAD

**Issue by hellobiek** [apache/apisix#6431]
### Issue description

本人的配置如下：
`    "authz-keycloak": {
      "client_id": "apisix",
      "client_secret": "XXXXXXXXXXXXXXXXXXXXXX",
      "disable": false,
      "discovery": "http://10.20.0.213:31477/auth/realms/apisix_test_realm/.well-known/openid-configuration",
      "permissions": [
        "Png Resource#image:view"
      ]
    }`

但是在使用时报错，错误日志如下：

2022/02/24 01:17:16 [error] 44#44: *27382192 [lua] authz-keycloak.lua:694: phase_func(): failed to fetch JWT token: authorization header not available, client: 10.20.0.213, server: _, request: "GET /image/png HTTP/1.1", host: "10.20.0.213:32268"

### Environment

- apisix version (cmd: `apisix version`): 
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/issues/4616

You need to provide the complete reproduction steps.
