### ISSUE TITLE
request help: allow_origins and allow_origins_by_regex in cors plugin

### ISSUE THREAD

**Issue by Gary-Airwallex** [apache/apisix#6439]
### Issue description

The `allow_origins_by_regex` option is used when no origin in `allow_origins` matches with request origin. What if I'd like to use allow_origins_by_regex only? Do I have to specify the string `null` for `allow_origins`? Would it be possible to make allow_origins optional (removing `default = "*"`)?

### Environment

- apisix version (cmd: `apisix version`): master
- OS (cmd: `uname -a`): 
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
if you just want to use `allow_origins_by_regex`, no `allow_origins `, you can follow this case:
https://github.com/apache/apisix/blob/d5d1c8a49074c0238001286f0059a6a5b5a014ed/t/plugin/cors.t#L763-L844

**Comment by Gary-Airwallex** [comment]
Hi @tzssangglass in that example, the request origin is first matched with "http://sub.domain.com,http://sub2.domain.com"? It'll fail of course and then being matched against allow_origins_by_regex, but is it possible to omit the first step?

**Comment by tzssangglass** [comment]
> Hi @tzssangglass in that example, the request origin is first matched with "http://sub.domain.com,http://sub2.domain.com"? It'll fail of course and then being matched against allow_origins_by_regex, but is it possible to omit the first step?

You can try it.

**Comment by ochuko3d** [comment]
@tzssangglass Please we are getting this error **Referrer Policy: strict-origin-when-cross-origin** the referrer is **http://localhost:9001/**. below is my config

 "methods": [
    "POST"
  ],
  "host": "dev.api.assetstack.co",
  "plugins": {
    "cors": {
      "allow_credential": true,
      "allow_headers": "*",
      "allow_methods": "**",
      "allow_origins": "http://localhost:9001",
      "disable": false,
      "expose_headers": "*",
      "max_age": 600
    }
  },

**Comment by ochuko3d** [comment]
Hope your day is going great, I am getting this cors error with the following config

 "methods": [
    "POST"
  ],
 "host": “dev.api.*.c********o",
  "plugins": {
    "cors": {
      "allow_credential": true,
      "allow_headers": "*",
      "allow_methods": "**",
      "allow_origins": "http://localhost:9001",
      "disable": false,
      "expose_headers": "*",
      "max_age": 600
    }
  },

Referrer Policy: strict-origin-when-cross-origin
Referer: http://localhost:9001/

**Comment by tzssangglass** [comment]
@ochuko3d  I think this error is the behavior of the browser handling CORS? ref: https://developer.chrome.com/blog/referrer-policy-new-chrome-default/

**Comment by tokers** [comment]
@Gary-Airwallex `allow_origins` is not a required field.

**Comment by ochuko3d** [comment]
thanks @tokers @tzssangglass, please could a service mesh - istio- in the kubernetes cluster be causing this 
![image](https://user-images.githubusercontent.com/28976224/185074816-a27076c8-8b90-4f79-856c-2c7d5e09fe3f.png)

**Comment by ochuko3d** [comment]
Thanks. it has been resolved. Th config worked fine, the method wasn't communicated
