### ISSUE TITLE
How use "google.protobuf.Any"?

### ISSUE THREAD

**Issue by doudouliyougangbeng** [apache/apisix#6441]
### Issue description

curl http://127.0.0.1:8081/apisix/admin/proto/1 -H 'X-API-KEY: XXX' -X PUT -d '
{
     "content" : "syntax = \"proto3\";
     import "google/protobuf/any.proto";
...
}
{"error_msg":"invalid content: \/usr\/local\/tapisix\/\/deps\/share\/lua\/5.1\/protoc.lua:335: attempt to index field 'node' (a nil value)"}
{"error_msg":"invalid content: \/usr\/local\/tapisix\/\/deps\/share\/lua\/5.1\/protoc.lua:915: filename for loaded:88:3: unknown type 'google.protobuf.Any'"}

How to solve this problem？
       

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@doudouliyougangbeng See https://github.com/apache/apisix/blob/03324ee6f9940020a129f18c11c337e6bd40660f/docs/en/latest/plugins/grpc-transcode.md#add-a-proto.

**Comment by xuchmao** [comment]
1. Rewrite plugin grpc-transcode
2. Store google protobuf files locally 
3. Use protoc.loadfile to compile proto

![本地存储](https://user-images.githubusercontent.com/14901669/155665935-a1269fc9-1780-4109-a3b4-880e8e7d02bb.png)

![文件编译](https://user-images.githubusercontent.com/14901669/155666014-bb32f941-726d-45d5-8d63-f4b6c707480a.png)

**Comment by spacewander** [comment]
There is no need to rewrite grpc-transcode. We support loading a compiled `.pb` file.
See "First of all, let's create a .pb file from .proto files:" and the content below in https://github.com/apache/apisix/blob/03324ee6f9940020a129f18c11c337e6bd40660f/docs/en/latest/plugins/grpc-transcode.md#add-a-proto

**Comment by spacewander** [comment]
Note that this feature is just added this month. It is not in any release yet. We will release 2.13 in March with this feature included.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
