### ISSUE TITLE
request help: upstream how to do failover

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#6443]
### Issue description

I have this requirement, currently there are three upstream nodes, A, B, C, where node A and node B provide services normally, node C only do backup, only node A and node B have problems, node C will receive requests

How should I achieve this based on the current situation？

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
See https://apisix.apache.org/docs/apisix/next/architecture-design/upstream/, you can refer to the node priority.

**Comment by zuiyangqingzhou** [comment]
> See https://apisix.apache.org/docs/apisix/next/architecture-design/upstream/, you can refer to the node priority.

This should not meet my requirement, my requirement is that under normal circumstances the request will only hit node A and node B. Only if both node A and node B are down, the request will go to node C.

**Comment by nic-6443** [comment]
> > See https://apisix.apache.org/docs/apisix/next/architecture-design/upstream/, you can refer to the node priority.
> 
> This should not meet my requirement, my requirement is that under normal circumstances the request will only hit node A and node B. Only if both node A and node B are down, the request will auto go to node C.

Please read the upstream documentation carefully, this function can be achieved by node priority and active healthy check, there is a very clear demonstration case in the documentation, similar to the following：
```shell
curl --location --request PUT 'http://apisix-admin:9180/apisix/admin/routes/failover' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "host": "failover",
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "nodes": [
            {"host": "172.30.45.124", "port": 80, "weight": 1},
            {"host": "172.30.45.125", "port": 80, "weight": 1},
            {"host": "172.30.45.126", "port": 80, "weight": 1, "priority": -1}
        ],
        "checks": {
            "active": {
                "http_path": "/status/200",
                "healthy": {
                    "interval": 1,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 1
                }
            }
        }
    },
    "name": "failover"
}'
```

**Comment by zuiyangqingzhou** [comment]
> > > See https://apisix.apache.org/docs/apisix/next/architecture-design/upstream/, you can refer to the node priority.
> > 
> > 
> > This should not meet my requirement, my requirement is that under normal circumstances the request will only hit node A and node B. Only if both node A and node B are down, the request will auto go to node C.
> 
> Please read the upstream documentation carefully, this function can be achieved by node priority and active healthy check, there is a very clear demonstration case in the documentation, similar to the following：
> 
> ```shell
> curl --location --request PUT 'http://apisix-admin:9180/apisix/admin/routes/failover' \
> --header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "host": "failover",
>     "uri": "/*",
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": [
>             {"host": "172.30.45.124", "port": 80, "weight": 1},
>             {"host": "172.30.45.125", "port": 80, "weight": 1},
>             {"host": "172.30.45.126", "port": 80, "weight": 1, "priority": -1}
>         ],
>         "checks": {
>             "active": {
>                 "http_path": "/status/200",
>                 "healthy": {
>                     "interval": 1,
>                     "successes": 1
>                 },
>                 "unhealthy": {
>                     "interval": 1,
>                     "http_failures": 1
>                 }
>             }
>         }
>     },
>     "name": "failover"
> }'
> ```

Thanks for your patience

**Comment by nic-6443** [comment]
> the `priority ` can not be update in dashboard ui，is some wrong ? @nic-6443
The dashboard does not yet support configuring priority fields,  welcome to submit PR, thank you!
