### ISSUE TITLE
feat: As a User, I want to using one etcd cluster sharing by all the apisix clusters

### ISSUE THREAD

**Issue by jacobslei** [apache/apisix#6457]
### Issue description

 On the basis of current  apisix achitecture, one etcd cluster just can  be used for one apisix cluster for storing gateway configurations.  It seems like to have a little waste for etcd cluster resources. Is there any plans for supporting one etcd cluster using by many  apisix clusters ?

**Comment by jwrookie** [comment]
As far as I know, there are no plans for this, but it seems to be uncomplicated to implement. We give each `apisix` node a unique ID and use this ID for resource isolation. This needs to be discussed and fully validated by the community
