### ISSUE TITLE
feat: How to  discovering different upstream  nodes  from different registry center in one apisix cluster   

### ISSUE THREAD

**Issue by jacobslei** [apache/apisix#6458]
### Issue description

In our bussiness scene, we need to using api gateway to switch different environment for the first layer to enter the backend microservices cluster. So we need to implement that feature:
1.  discovering backend services using different eureka service in one apisix cluster
2. The backend services  instances which are discoveried from eureka service can be filter by key-value  meta configuration

**Comment by tokers** [comment]
It seems that both the needs are not feasible with using the current apisix.

**Comment by jacobslei** [comment]
> It seems that both the needs are not feasible with using the current apisix.

Thank you for your reply.  Do you know any plannings for supporting this feature?  And  if there is no planning for it, is there any  else solutions ?

**Comment by spacewander** [comment]
We can do it in https://github.com/api7/apisix-seed/?
