### ISSUE TITLE
APISIX's V3 (2022) Roadmap

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#6473]
### Issue description

We are going to release a new major version (V3) in 2022.
As a major version, we will remove deprecated fields, bring break
changes, and most importantly, add great features.

We are going to make APISIX easier to adopt:
1. redesign documentation
2. refactor the backend of Dashboard. Now, this backend will talk with
Admin API instead of etcd.
3. refactor the API definition in Admin API, so that it can match the
backend of Dashboard.
4. support different backend as the source of configuration instead of
etcd.
5. move some features to CP side.
6. smarter way to diagnose runtime issues. Probably a builtin plugin?
7. Connect to etcd via gRPC and reduce the number of etcd connection
8. declarative configuration like what we have done in apisix-ingress (a better implementation of standalone mode or Admin API can sync
configuration in file to etcd)

We are going to make APISIX connect to more ecosystems:
1. integrate with more Open Source projects
2. integrate with cloud vendors
3. integrate with OpenAPI spec and other API spec definitions
4. write plugin without Lua, in the traditional way (Plugin Runner) or
the modern way (Wasm)
5. native gRPC support as a client, so we can connect to further places

We are going to make APISIX proxy everything:
1. xRPC: an L4 proxy framework to provide wire-level observability of
databases & message queue & RPC.
And more L4 observability: Prometheus & logger in the L4 level.
2. support XDS so APISIX can be used as the DP of istio

**Comment by moonming** [comment]
looking forward to service mesh of Apache APISIX

**Comment by lizj3624** [comment]
4. support different backend，support consul，mysql？

**Comment by moonming** [comment]
> 4. support different backend，support consul，mysql？

yes

**Comment by kwanhur** [comment]
2. backend will talk with Admin API, `apisix-adminctl` or `apisixctl` will come into the plan together?

**Comment by wang-yeliang** [comment]
Look forward to Service Mesh.

罗泽轩 ***@***.***> 于2022年3月1日周二 09:44写道：

**Comment by kwanhur** [comment]
> > 2. backend will talk with Admin API, `apisix-adminctl` or `apisixctl` will come into the plan together?
> 
> The full sentence is
> 
> > 2. refactor the backend of Dashboard. Now, this backend will talk with
> >    Admin API instead of etcd.
> 
> `this backend` means the Dashboard's backend.

[apisix-dashboard#1884](https://github.com/apache/apisix-dashboard/issues/1884) discussion mentioned that uniformed data model for Dashboard's backend and command line's backend. So take some care of the both backends.

**Comment by spacewander** [comment]
> apisix 2.11 是否能够无缝切换到3版本？

There will be many break changes so we can't do it.

**Comment by spacewander** [comment]
> > > 2. backend will talk with Admin API, `apisix-adminctl` or `apisixctl` will come into the plan together?
> > 
> > 
> > The full sentence is
> > > 2. refactor the backend of Dashboard. Now, this backend will talk with
> > >    Admin API instead of etcd.
> > 
> > 
> > `this backend` means the Dashboard's backend.
> 
> [apisix-dashboard#1884](https://github.com/apache/apisix-dashboard/issues/1884) discussion mentioned that uniformed data model for Dashboard's backend and command line's backend. So take some care of the both backends.

This purpose is marked as stale.

**Comment by spacewander** [comment]
Let's freeze this issue.

**Comment by wolgod** [comment]
2.15 is the last big version of 2.x this year?

**Comment by spacewander** [comment]
2.15 will be the biggest minor version of 2.x.

**Comment by Nobilta** [comment]
if apisix v3 can support multi cluster of k8s'discovery?

**Comment by spacewander** [comment]
> if apisix v3 can support multi cluster of k8s'discovery?

It's not in the roadmap.

**Comment by Nobilta** [comment]
> > if apisix v3 can support multi cluster of k8s'discovery?
> 
> It's not in the roadmap.

fine,when we can use apisix v3?do you have any shecdule?

**Comment by tokers** [comment]
> > > if apisix v3 can support multi cluster of k8s'discovery?
> 
> > 
> 
> > It's not in the roadmap.
> 
> 
> 
> fine,when we can use apisix v3 and what's the shecdule?the connection to etcd with gRPC is necessary.

The first rc version should be available at the end of this month.
