### ISSUE TITLE
request help: Can I send HTTPS requests to apisix via IP

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#6479]
### Issue description

Because our firewall can only use IP to check HTTPS security. How can I send HTTPS requests to apisix via IP?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@aiyiyi121 FYI:

```
curl https://{APISIX IP}:{APISIX HTTPS PORT}/path/to/your/api
```

If the requests failed since the TLS issues, check out curl manual and find some options.

**Comment by aiyiyi121** [comment]
> @aiyiyi121 FYI:
> 
> ```
> curl https://{APISIX IP}:{APISIX HTTPS PORT}/path/to/your/api
> ```
> 
> If the requests failed since the TLS issues, check out curl manual and find some options.

It will fail using the `config-default.yaml`, and report errors "failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol".
But I have found the solution by reading the source code，and change the config.yaml-apisix-ssl-fallback_sni, it can set the default SNI when the client doesn't send SNI during handshake.
