### ISSUE TITLE
request help: {"error_msg":"unknown plugin [ext-plugin-pre-req]"}

### ISSUE THREAD

**Issue by stray-dog** [apache/apisix#6481]
### Issue description

https://apisix.apache.org/zh/docs/apisix/plugins/ext-plugin-pre-req

curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri":"/get",
    "plugins":{
        "ext-plugin-pre-req":{
            "conf":[
                {
                    "name":"myPluginName",
                    "value":"{\"key1\":\"feature\"}"
                }
            ]
        }
    },
    "upstream":{
        "nodes":{
            "httpbin.org:80":1
        },
        "type":"roundrobin"
    }
}'

### Environment

- apisix version : 2.12.1
- OS (cmd: ``): Linux
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tzssangglass** [comment]
have you enable `ext-plugin-pre-req` in your `config.yaml`?

**Comment by stray-dog** [comment]
Oh！I see it. Think you.
