### ISSUE TITLE
feat: route matching variables support case insensitivity

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix#6486]
### Issue description

![image](https://user-images.githubusercontent.com/48319268/156312536-ed59b5c3-9a3f-4f01-be54-ac158dc79656.png)
if ($arg_appid = "1"){
        set XXXX;
}
nginx中对于判断arg变量本身不区分大小写   但apisix区分大小写，是否可以支持变量本身大小写

**Comment by shuaijinchao** [comment]
confirm, I think it's a good proposition. @Horus-K

**Comment by Belyenochi** [comment]
> confirmed, I think it's a good proposition. @Horus-K

@shuaijinchao Does the question want apisix to support case insensitivity,if so can it be assigned to me.

**Comment by shuaijinchao** [comment]
thx~ @Belyenochi, yes, I think it should be done. I would like to know first if @Horus-K , as the person who found this issue, is willing to fix it?

**Comment by Horus-K** [comment]
@shuaijinchao Sorry, didn't have time to fix it

**Comment by shuaijinchao** [comment]
> @shuaijinchao Sorry, didn't have time to fix it

OK @Belyenochi  do you want to do this PR? once confirmed, I can assign it to you.

**Comment by Belyenochi** [comment]
> > @shuaijinchao Sorry, didn't have time to fix it
> 
> OK @Belyenochi do you want to do this PR? once confirmed, I can assign it to you.

h1 @shuaijinchao, pls assign it to me!

**Comment by spacewander** [comment]
@Belyenochi @shuaijinchao 
I am afraid arg_xxx should be case-sensitive. 

See https://stackoverflow.com/a/24700171.

> So the query part of the URI as defined by the spec for the HTTP scheme is case-sensitive. 

It is a limitation of Nginx that it handles all the variables in case-insensitive way. In fact, OpenResty's `get_uri_args` handles it correctly:

```
 server {
        listen 9981;
        location / {
            content_by_lua_block {
                local cjson = require("cjson")
                ngx.say(cjson.encode(ngx.req.get_uri_args()))
            }
        }
    }
```

with `curl '127.0.0.1:9981?a=2&A=1'`, it gets `{"A":"1","a":"2"}`.

It would be good if we can follow the standard and get rid of Nginx's weird behavior.

**Comment by Horus-K** [comment]
Is it possible to make case sensitivity an option？

**Comment by spacewander** [comment]
No. We don't have place to put the option in the expression. And such option disobeys the HTTP standard. Also it makes the user can't distinguish the correct argument from the wrong one. For example, we may match `useRid` as user id while the upstream treats `userID` as the real user ID, which may bring additional security risk.

**Comment by Horus-K** [comment]
#6513 A new problem has appeared, please help @spacewander
