### ISSUE TITLE
request help: what does `ctx.upstream_healthcheck_parent` do?

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#6488]
### Issue description

here: https://github.com/apache/apisix/blob/eb0bf87b3865b4192991f963594bc24b54d9aff9/apisix/upstream.lua#L78

It looks like storing this in the ctx isn't used now.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by spacewander** [comment]
It was used in 748e3375 before.
We can safely remove it now.
