### ISSUE TITLE
request help: github ci jobs run failed frequently

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6501]
### Issue description

From [Actions](https://github.com/apache/apisix/actions) logs, partial jobs run failed too often.

PR's checking easily not pass.

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
What specific problem are you having? This description is too broad, and if the new code does not affect other historical functions, it generally does not fail.

**Comment by kwanhur** [comment]
New pr gets trouble in check failure, even just modify `docs` `code lint config`, not modify any code. Like https://github.com/apache/apisix/pull/6428 's workflow, `code lint` jobs work fine, but others work failed. Rerun job needs trigger by admin or new commit.

PR owner and reviewer both worry about check result.

**Comment by spacewander** [comment]
GitHub Action is unstable yesterday.
