### ISSUE TITLE
doc: convert plugin's docs into mandoc

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6510]
Another viewpoint, will these plugins' docs can be converted into mandoc in the future?
If can, we can retrieve plugin's help by `man apisix-plugin-xxx` after installed apisix.

_Originally posted by @kwanhur in https://github.com/apache/apisix/issues/6477#issuecomment-1057821326_

**Comment by spacewander** [comment]
Maintaining online doc is enough.
