### ISSUE TITLE
request help: Using apisix proxy grpc service performance is low

### ISSUE THREAD

**Issue by lihuawei321** [apache/apisix#6511]
### Issue description

使用apisix代理grpc服务，发现性能较低。发现一个现象：压测POD,对应的端口只有几个TCP链接；但是通过apisix压测试，POD里的有上千条TCP连接。是不是apisix没有复用tcp链接。以下是测试结果：
![image](https://user-images.githubusercontent.com/31987918/156717935-be36476c-62a3-455c-9484-3e1305636d00.png)
有没有可能和k8s的dns请求有关系？
是否有可以优化的地方。

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
Can you provide more information? Such as the CNI you use.

**Comment by shuaijinchao** [comment]
apisix will enable keepalive by default, https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L366-L368

**Comment by shuaijinchao** [comment]
Is the proxy method through APISIX gRPC to gRPC? Or HTTP(s) to gRPC?

**Comment by moonming** [comment]
@nic-chen do you have any ideas?

**Comment by nic-chen** [comment]
Hi, @lihuawei321 

Please provide your APISIX version, your route/upstream configuration, and your test method, thanks!

**Comment by lihuawei321** [comment]
apsix version:  2.10

**Comment by lihuawei321** [comment]
apiversion : 2.10

**Comment by lihuawei321** [comment]
apiversion : 2.10  ingress: 1.3. cni :calico  http to grpc。使用的是grpc压测工具ghz测试。route
`{
  "uris": [
    "/helloworld"
  ],
  "name": "ingress_demo.helloworld.com_/helloworld",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "host": "demo.helloworld.com",
  "upstream_id": "6f746999",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  },
  "status": 1
}`
upstream `{
  "nodes": [
    {
      "host": "192.168.49.201",
      "port": 8085,
      "weight": 100
    }
  ],
  "type": "roundrobin",
  "hash_on": "vars",
  "scheme": "http",
  "pass_host": "pass",
  "name": "pdc-mcs_pdc-mcs-helloworld_8085",
  "desc": "Created by apisix-ingress-controller, DO NOT modify it manually",
  "labels": {
    "managed-by": "apisix-ingress-controller"
  }
}`

**Comment by tao12345666333** [comment]
Please provide more details, including your test application, calico specific network mode, overlay or underlay, etc.  It would be very helpful if a network topology could be provided.
