### ISSUE TITLE
bug: log-rotate can not rotate logs strictly hourly(or minutely)

### ISSUE THREAD

**Issue by snowdusk** [apache/apisix#6517]
### Issue description
e.g. 
Apisix start time is 15:29:23, log-rotate interval is 3600(1 hour)
Next rotate time is 16:29:23, next next rotate time is 17:29:23

I want next rotate time is 16:00:00, next next rotate time is 17:00:00

The current implement: 
```
    if not rotate_time then
        -- first init rotate time
        rotate_time = now_time + interval
        core.log.info("first init rotate time is: ", rotate_time)
        return
    end
```

This is my change.
```
    if not rotate_time then
        -- first init rotate time
        rotate_time = now_time + interval - (now_time % interval)
        core.log.info("first init rotate time is: ", rotate_time)
        return
    end
```

**Comment by shuaijinchao** [comment]
What problem does this solve? Also I don't think this is a bug

**Comment by membphis** [comment]
@snowdusk I think you are right. It seems https://github.com/apache/apisix/commit/139c3972898f1e45c6d5b1f40143c504116b3486 break this feature

**Comment by membphis** [comment]
> @snowdusk I think you are right. It seems [139c397](https://github.com/apache/apisix/commit/139c3972898f1e45c6d5b1f40143c504116b3486) break this feature

need @shuaijinchao's help

**Comment by soulbird** [comment]
Strictly hourly rotation of logs is better

**Comment by shuaijinchao** [comment]
I don't understand what problem can be solved this way? @membphis

**Comment by snowdusk** [comment]
@shuaijinchao OK. I will create a PR
