### ISSUE TITLE
request help:  Please give some advice about tars discovery

### ISSUE THREAD

**Issue by zhixiongdu027** [apache/apisix#6518]
### Issue description

Hi, All:

I'm planning to implement a tars proxy and it's almost done.

Now, I might need some advice from community members:

tars proxy requires a tars service discovery module but probably only the tars proxy plugin will use it. so we have two options:

 1: put the code into apisix/discovery/tars.lua
 2: put the code into apisix/plugins/tars-transcode/discovery.lua

I think you should understand the meaning of the two options , and please leave your comments
If you had a better way please also point it out

Many TKS !

You can get tars details from https://github.com/TarsCloud/TarsDocs

@tokers @membphis 

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by shuaijinchao** [comment]
I think the second way would be better. My knowledge of TARS is limited, but as far as I can tell
Its main application scenario is not service registration and discovery, so it can be placed in the plugin directory as part of the plugin.

It's just a personal opinion, we can listen to more people's suggestions.

**Comment by zhixiongdu027** [comment]
Sorry, after consideration, I decide to use option 1 ,

Because there may be some services in the tars that need to use the http protocol.
If these service also require proxies, we have to use option 1.
