### ISSUE TITLE
bug: nacos discovery config valid error when using $ in password symbol in config.yaml

### ISSUE THREAD

**Issue by Fengxq2014** [apache/apisix#6522]
### Issue description

When using $ in nacos password in config.yaml following the document from [https://apisix.apache.org/docs/apisix/discovery/nacos](https://github.com/apache/apisix/issues/url).
At starting time the nacos report error

### Environment

- apisix version (cmd: `apisix version`): 2.12.1
- OS (cmd: `uname -a`): linux

### Steps to reproduce

1. Config following yaml fragment in config.yaml
```
discovery:
  nacos:
    host:
      - "http://nacos:NOK1&(&*!#3$@127.0.0.1:8848"
```
2. Start apisix

### Actual result

apisix start report error

### Error log

[lua] init.lua:124: get_token_param(): nacos login fail:nacos NOK1&(&*!#3$%24 desc:status = 403, context: ngx.timer
[lua] init.lua:249: get_token_param error:status = 403, context: ngx.timer

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/6261? Will be in the 2.13.0 release.

**Comment by leslie-tsang** [comment]
Please assign it to me. :)

**Comment by leslie-tsang** [comment]
> Fixed in https://github.com/apache/apisix/pull/6261? Will be in the 2.13.0 release.

The schema check rules do not match character `$`, I will fix it.

**Comment by leslie-tsang** [comment]
@Fengxq2014 Could you please check the PR #6567 , if the test case can cover your scenario.

**Comment by Fengxq2014** [comment]
@lhack-jpeg Yes, thanks for your work
