### ISSUE TITLE
docs: change VIIO to VIVO in README

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#6524]
### Improved or typo fixed.

![image](https://user-images.githubusercontent.com/2106987/156975520-5ee18471-a8de-47a4-a80f-82240cebf2ed.png)

### Solution

Change it to VIVO.

**Comment by spacewander** [comment]
CC @bin-ya

**Comment by leslie-tsang** [comment]
There is another typo [here](https://github.com/apache/apisix/blob/cd97d827abf6791611ce355b12555531dbd7b53d/docs/zh/latest/plugins/server-info.md?plain=1#L44), let's do it in one PR :)
