### ISSUE TITLE
docs: update powered-by.md

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#6525]
### Improved or typo fixed.

After the https://github.com/apache/apisix/pull/6027/files merged, the https://github.com/apache/apisix/issues/487 has added some new user cases by community users.

For example: 

https://github.com/apache/apisix/issues/487#issuecomment-1038794485 

https://github.com/apache/apisix/issues/487#issuecomment-993453584

### Solution

We need to update these user cases to powered-by.md, ref to: https://github.com/apache/apisix/pull/6027/files

**Comment by liangliang4ward** [comment]
let me do this.
