### ISSUE TITLE
docs: improve Chinese copywriting

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6528]
### Improved or typo fixed.

Copywriting in `docs/zh/latest` have different formats:
  - some writings have one space before/after English words but some have no.
  - some punctuations used in halfwidth form but some in fullwidth. [what's differences between fullwidth and halfwidth](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms)

### Solution

* Add copywriting guidelines, include rules[1]

> reference: [chinese-copywriting-guidelines](https://sparanoid.com/note/chinese-copywriting-guidelines/)

* Add [lint tool](https://sparanoid.com/note/chinese-copywriting-guidelines/#tools) in code-lint workflow

[1]
[Spacing](https://sparanoid.com/note/chinese-copywriting-guidelines/#spacing)
  - [Place one space before/after English words](https://sparanoid.com/note/chinese-copywriting-guidelines/#place-one-space-beforeafter-english-words)
  - [Place one space before/after numbers](https://sparanoid.com/note/chinese-copywriting-guidelines/#place-one-space-beforeafter-numbers)
  - [Place one space between numbers and units](https://sparanoid.com/note/chinese-copywriting-guidelines/#place-one-space-between-numbers-and-units)
  - [No additional spaces before/after punctuation in fullwidth form](https://sparanoid.com/note/chinese-copywriting-guidelines/#no-additional-spaces-beforeafter-punctuation-in-fullwidth-form)
  - [text-spacing to the rescue?](https://sparanoid.com/note/chinese-copywriting-guidelines/#text-spacing-to-the-rescue)

[Punctuation](https://sparanoid.com/note/chinese-copywriting-guidelines/#punctuation)
  - [Avoid duplicate punctuation](https://sparanoid.com/note/chinese-copywriting-guidelines/#avoid-duplicate-punctuation)

[Fullwidth and halfwidth](https://sparanoid.com/note/chinese-copywriting-guidelines/#fullwidth-and-halfwidth)
  - [Use punctuation in fullwidth form](https://sparanoid.com/note/chinese-copywriting-guidelines/#use-punctuation-in-fullwidth-form)
  - [Use numbers in halfwidth form](https://sparanoid.com/note/chinese-copywriting-guidelines/#use-numbers-in-halfwidth-form)
  - [Use punctuation in halfwidth form for English sentences](https://sparanoid.com/note/chinese-copywriting-guidelines/#use-punctuation-in-halfwidth-form-for-english-sentences)

**Comment by tzssangglass** [comment]
LGTM, let's check with the tool.

**Comment by tzssangglass** [comment]
would you like to do it?

**Comment by tzssangglass** [comment]
@juzhiyuan PLAT

**Comment by juzhiyuan** [comment]
Hi @kwanhur, thanks for your suggestion! I support using a unified writing guideline, after reading https://sparanoid.com/note/chinese-copywriting-guidelines/ it looks good to me 🙌

1. We could use Lint tools to format styles first;
2. Support Lint CI to do formats automatically or just checker;
3. Update (more correctly is `rewrite`) Chinese Contents according to that guideline.

**Comment by kwanhur** [comment]
> would you like to do it?

Yep, I'll take part in the improving jobs.

**Comment by kwanhur** [comment]
Lint tool I recommend [autocorrect](https://github.com/huacnlee/autocorrect), it's binary supports to lint and fix, would be easily integrated into ci workflow. Autocorrect usage:

```bash
autocorrect --help
AutoCorrect 1.5.6
Jason Lee <huacnlee@gmail.com
A linter and formatter for help you improve copywriting, to correct spaces, punctuations between CJK (Chinese, Japanese,
Korean).

USAGE:
    autocorrect [FLAGS] [OPTIONS] <file>...

FLAGS:
        --debug      Print debug message.
        --type       Directly use set file type
        --fix        Automatically fix problems and rewrite file.
    -h, --help       Prints help information
        --lint       Lint and output problems.
    -V, --version    Prints version information
```

**Comment by juzhiyuan** [comment]
LGTM, and please note:

```
We only allow Actions that are official "Made by GitHub" or local to the Apache org on GitHub, to address a potential security vulnerability. This is an incident-related policy change. We are researching the situation, and the policy may evolve based on what we learn.
```

```
NEVER use 3rd-party actions directly in your worfklows - use the "submodule" pattern. Example PR [Tobiasz Kędzierski](https://cwiki.apache.org/confluence/display/~tobked)  [opened in SuperSet](https://github.com/apache/superset/pull/12709) showing how this could be done. Also ASF INFRA allow-listed some of the popular Actions out there, including my "cancel workflow" action, but I there is no public list of those available. The nice things about submodules is that they do not bring action code to your repo. They link to commit hashes of the Actions, and that integrates well with the GitHub review process so that committers have better chance to review the changes before they are merged. By using submodules, you are automatically following the GitHub recommendations for [hardening of security for 3rd-party actions](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions).
```

also, check those 3 articles:

1. https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/
2. https://infra.apache.org/github-actions-secrets.html 
3. https://cwiki.apache.org/confluence/display/BUILDS/GitHub+Actions+status#GitHubActionsstatus-Thereasonfortheissue

**Comment by kwanhur** [comment]
Thx for the tips. I think we can treat autocorrect integration as [staticcheck](https://github.com/apache/apisix/blob/master/.github/workflows/code-lint.yml#L39-L45) in code-lint job.

**Comment by navendu-pottekkat** [comment]
We should probably create a style guide for APISIX. We can start with documentation so that it can remain consistent. For the English docs, we could have something similar to https://developers.google.com/style/highlights where we outline how everything should be and add details specific to the project.

**Comment by kwanhur** [comment]
> We should probably create a style guide for APISIX. We can start with documentation so that it can remain consistent. For the English docs, we could have something similar to https://developers.google.com/style/highlights where we outline how everything should be and add details specific to the project.

LGTM. Docs writers will benefit from the document style guide.
