### ISSUE TITLE
request help: How add customized http header via apisix?

### ISSUE THREAD

**Issue by lizj3624** [apache/apisix#6535]
### Issue description

I want to add customized http request header from apisix to upstream in some routes，how i can do?

for example:  i want to add `X-My-Header: MyName`，i known nginx's cmd，add `proxy_set_header X-My-Header MyName`
in  server block

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by soulbird** [comment]
You can use proxy-rewrite plugin, like:
```
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/test/index.html",
    "plugins": {
        "proxy-rewrite": {
            "uri": "/test/home.html",
            "scheme": "http",
            "host": "iresty.com",
            "headers": {
                "X-My-Header": "MyName"
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}'
```
You can check the documentation for more details. https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/proxy-rewrite.md

**Comment by lizj3624** [comment]
Thank you very much! I try

**Comment by juzhiyuan** [comment]
I'm going to close this issue 🤗 If you have other questions, please let us know.
