### ISSUE TITLE
chore: As a Developer, I want to uniform code specification and style

### ISSUE THREAD

**Issue by zaunist** [apache/apisix#6541]
### Issue description

ref this comment https://github.com/apache/apisix/pull/6509#discussion_r820630797

when we write a code block like this:

```
return res, nil
```

The `, nil` is nonsense here, and the lua code style requires simplicity. So we should have to check our repository, remove the redundant `, nil` and unify the code style.

You could refer to this document: https://github.com/apache/apisix/blob/master/CODE_STYLE.md

Or do other people have any other comments?

**Comment by spacewander** [comment]
Please don't waste time doing this without any linter.
