### ISSUE TITLE
attempt to concatenate field 'algorithm' (a nil value)

### ISSUE THREAD

**Issue by kennethToyuan** [apache/apisix#6548]
### Issue description

2022/02/24 19:25:16 [error] 45#45: *90430744 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/hmac-auth.lua:301: attempt to concatenate field 'algorithm' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/plugins/hmac-auth.lua: in function 'validate'
	/usr/local/apisix/apisix/plugins/hmac-auth.lua:438: in function 'phase_func'
	/usr/local/apisix/apisix/plugin.lua:676: in function 'run_plugin'
	/usr/local/apisix/apisix/init.lua:447: in function 'http_access_phase'
	access_by_lua(nginx.conf:261):2: in main chunk, client: 192.168.47.1, server: _, request: "POST /jr-paas/mail/send HTTP/1.1", host: "192.168.47.128:9080"
2022/02/24 19:25:18 [error] 46#46: *90430823 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/hmac-auth.lua:301: attempt to concatenate field 'algorithm' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/plugins/hmac-auth.lua: in function 'validate'
	/usr/local/apisix/apisix/plugins/hmac-auth.lua:438: in function 'phase_func'
	/usr/local/apisix/apisix/plugin.lua:676: in function 'run_plugin'
	/usr/local/apisix/apisix/init.lua:447: in function 'http_access_phase'
	access_by_lua(nginx.conf:261):2: in main chunk, client: 192.168.47.1, server: _, request: "POST /jr-paas/mail/send HTTP/1.1", host: "192.168.47.128:9080"

consumer  config:
![image](https://user-images.githubusercontent.com/13416357/157215775-adb50fdf-b440-4a33-be1c-294d7dbf4960.png)

**Comment by soulbird** [comment]
Looking at

**Comment by soulbird** [comment]
> ### Issue description
> 2022/02/24 19:25:16 [error] 45#45: *90430744 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/hmac-auth.lua:301: attempt to concatenate field 'algorithm' (a nil value) stack traceback: coroutine 0: /usr/local/apisix/apisix/plugins/hmac-auth.lua: in function 'validate' /usr/local/apisix/apisix/plugins/hmac-auth.lua:438: in function 'phase_func' /usr/local/apisix/apisix/plugin.lua:676: in function 'run_plugin' /usr/local/apisix/apisix/init.lua:447: in function 'http_access_phase' access_by_lua(nginx.conf:261):2: in main chunk, client: 192.168.47.1, server: _, request: "POST /jr-paas/mail/send HTTP/1.1", host: "192.168.47.128:9080" 2022/02/24 19:25:18 [error] 46#46: *90430823 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/hmac-auth.lua:301: attempt to concatenate field 'algorithm' (a nil value) stack traceback: coroutine 0: /usr/local/apisix/apisix/plugins/hmac-auth.lua: in function 'validate' /usr/local/apisix/apisix/plugins/hmac-auth.lua:438: in function 'phase_func' /usr/local/apisix/apisix/plugin.lua:676: in function 'run_plugin' /usr/local/apisix/apisix/init.lua:447: in function 'http_access_phase' access_by_lua(nginx.conf:261):2: in main chunk, client: 192.168.47.1, server: _, request: "POST /jr-paas/mail/send HTTP/1.1", host: "192.168.47.128:9080"
> 
> consumer config: ![image](https://user-images.githubusercontent.com/13416357/157215775-adb50fdf-b440-4a33-be1c-294d7dbf4960.png)

Can you provide the version number of Apache APISIX and APISIX-dashboard?

**Comment by soulbird** [comment]
It's related issue #5464. We have fixed this issue in #5464. Please use version 2.10 and later

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
