### ISSUE TITLE
docs: Move keyword definition to `Concepts` section and improve

### ISSUE THREAD

**Issue by avinal** [apache/apisix#6549]
### Improved or typo fixed.

Currently, the APISIX keywords are inside the Architecture section and it makes it harder to look for them because most of the time users tend to ignore the architecture. 
- https://apisix.apache.org/docs/apisix/architecture-design/
- Architecture design should only contain things related to it.
- It is hard to understand the configuration without these keywords

### Solution

Moving the keywords to a new section named `Concepts` with following pages. This section can later also accommodate more keywords and terms related to APISIX.
## Concepts
- [x] Route
- [x] Plugin
- [x] Script
- [x] Service
- [x] Consumer
- [x] Upstream
- [x] Global Rule

**Comment by avinal** [comment]
Hey @juzhiyuan, please assign this issue to me and add it to the project board as well. Thanks :)

**Comment by tokers** [comment]
Definitely agree with that, we need the key concepts page used to explain their meanings, and link here in other places.
