### ISSUE TITLE
request help: how does the consumer work？

### ISSUE THREAD

**Issue by soulbird** [apache/apisix#6557]
### Issue description

s described in the documentation
creates a consumer object：
```shell
curl http://127.0.0.1:9080/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "jack",
    "plugins": {
        "key-auth": {
            "key": "auth-one"
        }
    }
}'
```

creates a route or service object
```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/index.html",
    "id": 1,
    "plugins": {
        "key-auth": {}
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```
From the created parameters, I didn't find any related parameters between consumer and route. 
The processing of the request in my understanding is:

1、recvive a request
2、match router
3、find related consumer obj
4、load plugins

Is that so？ And how does the consumer work？Each consumer object does not have a unique representation, how is step three done?

### Environment

- apisix version (cmd: `apisix version`): 
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by liangliang4ward** [comment]
need consumer-restriction plugin

**Comment by tokers** [comment]
@soulbird APISIX find consumers according to some plugins written in the Route (like auth plugins).

**Comment by tzssangglass** [comment]
> 1、recvive a request
> 2、match router
> 3、find related consumer obj
> 4、load plugins

you can track the consumer's processing from this PR: https://github.com/apache/apisix/pull/6502#discussion_r819432139

**Comment by soulbird** [comment]
> > 1、recvive a request
> > 2、match router
> > 3、find related consumer obj
> > 4、load plugins
> 
> you can track the consumer's processing from this PR: [#6502 (comment)](https://github.com/apache/apisix/pull/6502#discussion_r819432139)

Think you, I will take a look
