### ISSUE TITLE
docs: remove the `make install` in how to build Apache APISIX doc

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix#6559]
### Improved or typo fixed.

![image](https://user-images.githubusercontent.com/72343596/157397028-8544fe89-c70c-4991-a6c1-5314e9373b38.png)

Since `make install` is not an installation dependency and may cause some misunderstanding to the user, we should add some extra comments to it or remove `make install`

### Solution

remove the `make install` or add some extra notes such as: `Install the apisix (only for luarocks)`

Any better suggestions?

**Comment by juzhiyuan** [comment]
Could you please describe the `reason` why we need to remove this? and what misunderstanding?

**Comment by hf400159** [comment]
I think we should add some extra comments to it, because someone needs it.

**Comment by tzssangglass** [comment]
The original discussion is here: https://github.com/apache/apisix/pull/5136#discussion_r716058656

Maybe we still need to remove the `make install`  cc @spacewander

**Comment by moonming** [comment]
Is `make install` a misleading name? How about change to `make luarocks-init`?
In fact, Apache APISIX does not need to install after downloading the source code, it can be run directly

**Comment by guoqqqi** [comment]
> How about changing to `make luarocks-init`?
> Apache APISIX does not need to install after downloading the source code, it can be run directly after `make deps`.

+1 If changing the command would be tricky, We can start by adding some comments to it.

**Comment by spacewander** [comment]
Yes. Since the `make install` is designed by luarocks, would be better to create a new name.

**Comment by bin-ya** [comment]
Remove  make install or change the comment to Install the apisix (only for luarocks)?

**Comment by tzssangglass** [comment]
I think it would be better to remove `make install` (in that context).
