### ISSUE TITLE
bug: Error when build with apisix-build-tools

### ISSUE THREAD

**Issue by crazyMonkey1995** [apache/apisix#6560]
### Issue description

When build with apisix-build-tools, erro occur:

```
+ mkdir -p /tmp/build/output/apisix/usr/bin/
+ cd /apisix
+ sed -i 's/url.*/url = ".\/apisix",/' rockspec/apisix-master-0.rockspec
+ sed -i 's/branch.*//' rockspec/apisix-master-0.rockspec
+ luarocks make ./rockspec/apisix-master-0.rockspec --tree=/tmp/build/output/apisix/usr/local/apisix/deps --local

Error: Could not load rockspec file /apisix/./rockspec/apisix-master-0.rockspec (Error loading file: [string "/apisix/./rockspec/apisix-master-0.rockspec"]:77: '}' expected (to close '{' at line 33) near '.')
The command '/bin/sh -c /install-common.sh install_apisix     && /determine-dist.sh' returned a non-zero code: 1
make: *** [build-apisix-rpm] Error 1
```

I debug it and found that the reason is:  sed -i 's/url.*/url = ".\/apisix",/' rockspec/apisix-master-0.rockspec  
It change the dependencies unexpectedly:

![image](https://user-images.githubusercontent.com/21658981/157402634-6716c445-c6a1-4c3e-842c-577388d2a55f.png)

### Environment

- apisix version (cmd: `apisix version`): latest(master)
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

### Steps to reproduce

build with apisix-build-tools

### Actual result

error occur

### Error log

+ mkdir -p /tmp/build/output/apisix/usr/bin/
+ cd /apisix
+ sed -i 's/url.*/url = ".\/apisix",/' rockspec/apisix-master-0.rockspec
+ sed -i 's/branch.*//' rockspec/apisix-master-0.rockspec
+ luarocks make ./rockspec/apisix-master-0.rockspec --tree=/tmp/build/output/apisix/usr/local/apisix/deps --local

Error: Could not load rockspec file /apisix/./rockspec/apisix-master-0.rockspec (Error loading file: [string "/apisix/./rockspec/apisix-master-0.rockspec"]:77: '}' expected (to close '{' at line 33) near '.')
The command '/bin/sh -c /install-common.sh install_apisix     && /determine-dist.sh' returned a non-zero code: 1
make: *** [build-apisix-rpm] Error 1

### Expected result

build success

**Comment by crazyMonkey1995** [comment]
May be it is bug of apisix-build-tools?

**Comment by leslie-tsang** [comment]
Same as https://github.com/api7/apisix-build-tools/issues/165, there is a [PR](https://github.com/api7/apisix-build-tools/pull/166) working on it

**Comment by leslie-tsang** [comment]
Would you like to do a PR review to move it forward ? :)

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if need.
