### ISSUE TITLE
request help: prometheus metrics for nginx connections

### ISSUE THREAD

**Issue by dgff07** [apache/apisix#6569]
### Issue description

We activated the Prometheus plugin and when we saw the metrics about the Nginx connections, the total connections shows a strange value:
```
# HELP apisix_nginx_http_current_connections Number of HTTP connections
# TYPE apisix_nginx_http_current_connections gauge
apisix_nginx_http_current_connections{state="accepted"} 16997
apisix_nginx_http_current_connections{state="active"} 3
apisix_nginx_http_current_connections{state="handled"} 16997
apisix_nginx_http_current_connections{state="reading"} 0
apisix_nginx_http_current_connections{state="total"} 5108 «««««««««««« is this value correct?
apisix_nginx_http_current_connections{state="waiting"} 2
apisix_nginx_http_current_connections{state="writing"} 1
```
**Is the value of `apisix_nginx_http_current_connections{state="total"}` correct? This because it has a lower value than the others**
I tried to check the documentation, but I didn't find so much information about the metrics exposed.

Thank you for checking this

### Environment

- apisix version (cmd: `apisix version`): 2.12.0
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): openresty/1.19.9.1

**Comment by spacewander** [comment]
Is it solved by:
https://github.com/apache/apisix/issues/6301
https://github.com/apache/apisix/commit/84eced65a9097d4d93037aacb4d215d48d9923b1
