### ISSUE TITLE
request help: can proxy-rewrite rewrite URI from request parameters?

### ISSUE THREAD

**Issue by gracekk** [apache/apisix#6571]
### Issue description

Can proxy-rewrite or some plugin can rewrite uri from request parameter?
e.g.  
original request like https://abc.com/getuser?id=123
and I want query upstream uri like  https://abc.com/123/getuser
Any ideas？thx

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by nfrankel** [comment]
Indeed. You can use the `regex_uri` configuration parameter. In your case, its value would be something like this:

```
["https:\/\/abc\.com\/(.*)\?id=(.*)", "https://abc.com/getuser/$2/$1"]
```

**Comment by syzygyyy** [comment]
Thanks for reply, it's also applies to change the parameter key?
For example I want to change getuser interface to getdetail.

**Comment by nfrankel** [comment]
@syzygyyy I'm not sure I understand the question. However, you can transform anything you'd like as the plugin uses [regular expressions](https://en.wikipedia.org/wiki/Regular_expression).

Hint: I'm not an expert, hence I usually try them [online](https://regex101.com/).
