### ISSUE TITLE
feat: Redesign the architecture of the plugin system

### ISSUE THREAD

**Issue by nfrankel** [apache/apisix#6580]
## Current situation

At the moment, you add a plugin in the request flow by referencing with its name and setting the configuration. The plugin is effectively a **singleton**. 

This approach has some downsides:

* You can use a plugin only once in the request flow. Users cannot add the same plugin multiple times with different configurations.
* For maintainers, it means that they need to duplicate code and reference it with different names and priorities. For example, the [ext-plugin-pre-req](https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin-pre-req.lua) and the [ext-plugin-post-req](https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin-post-req.lua) do the same - run arbitrary Lua code.
* Users cannot change the priority of a plugin, it's hard-coded (see #6504)
* Plugin developers need to handle every possible configuration case (see #6197)

## Proposal

In Object-Oriented speak, make `Plugin` a class and introduce `PluginInstance` "objects" (or something similarly named):

* `Plugin` defines the code
* `PluginInstance` references the `Plugin` and associates it with a priority and a configuration

Decoupling the code from the configuration/priority would bring much more freedom for users.

**Comment by liangliang4ward** [comment]
yes! Some time I want use a plugin to config diffent properties.
just like https://github.com/apache/apisix/issues/6527

**Comment by tokers** [comment]
@nfrankel Could you give a configuration snippet about how to configuring plugins when using the new arch?

Also, we need to evaluate the cost for the re-design, such as how to refactor plugins so that plugin codes are reentrant.

**Comment by nfrankel** [comment]
@tokers Would something like that be possible?

```bash
curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '{
  "plugins": [
    "plugin": {
      "id": "ext-plugin-req",
      "priority": 500,
      "conf": [{
        "name": "ext-plugin-A",
        "value": "{\"enable\":\"feature\"}"}
      ]},
    },
    "plugin": {
      "id": "ext-plugin-req",
      "priority": -500,
      "conf": [{
        "name": "ext-plugin-B",
        "value": "{\"disable\":\"feature\"}"}
      ]},
    }
  ]
}'
```

**Comment by tokers** [comment]
> 

Got it.

But since we use the array to orchestrate plugins, I think we can remove the priority field.

**Comment by nfrankel** [comment]
>But since we use the array to orchestrate plugins, I think we can remove the priority field.

I don't think so. AFAIK, plugins can be set on different levels (`Route` or `Service`). Hence, you need a way to merge their orders: you need to be explicit about it.

**Comment by tokers** [comment]
> > But since we use the array to orchestrate plugins, I think we can remove the priority field.
> 
> I don't think so. AFAIK, plugins can be set on different levels (`Route` or `Service`). Hence, you need a way to merge their orders - be explicit about it. Does it make sense or am I wrong?

IMHO that's confusing, the intuitive order is Route > Service, if we let users decide the order, it's error-prone.

**Comment by nfrankel** [comment]
Imagine the user has defined a Service with plugin A and priority 5. Now, they define a route with plugin B and C.

How would you compute the order based on the array?

**Comment by tokers** [comment]
> Imagine the user has defined a Service with plugin A and priority 5. Now, they define a route with plugin B and C.
> 
> How would you compute the order based on the array?

That's tricky. We may think about another way to allow a plugin can be run multiple times but still use the object to store their config. I'm wondering if there are some circumstances that people want to run the same plugin in a single route but not continuously (e.g. run plugin A, plugin B, plugin A).

**Comment by tokers** [comment]
> > Imagine the user has defined a Service with plugin A and priority 5. Now, they define a route with plugin B and C.
> > How would you compute the order based on the array?
> 
> That's tricky. We may think about another way to allow a plugin can be run multiple times but still use the object to store their config. I'm wondering if there are some circumstances that people want to run the same plugin in a single route but not continuously (e.g. run plugin A, plugin B, plugin A).

If not, what about the following way:

```json
{
    "uri": "/api/*",
    "host": "foo.com",
   "plugins": {
       "limit-count": [
          {
             "time_window": 60,
             "count": 10,
             "key": "remote_addr"
          },
          {
             "time_window": 1,
             "count": 5,
             "key": "route_id"
          }
       ] 
    }
}

```

**Comment by liangliang4ward** [comment]
> > > Imagine the user has defined a Service with plugin A and priority 5. Now, they define a route with plugin B and C.
> > > How would you compute the order based on the array?
> > 
> > 
> > That's tricky. We may think about another way to allow a plugin can be run multiple times but still use the object to store their config. I'm wondering if there are some circumstances that people want to run the same plugin in a single route but not continuously (e.g. run plugin A, plugin B, plugin A).
> 
> If not, what about the following way:
> 
> ```json
> {
>     "uri": "/api/*",
>     "host": "foo.com",
>    "plugins": {
>        "limit-count": [
>           {
>              "time_window": 60,
>              "count": 10,
>              "key": "remote_addr"
>           },
>           {
>              "time_window": 1,
>              "count": 5,
>              "key": "route_id"
>           }
>        ] 
>     }
> }
> ```

It's that support something a little more flexible? For example, when hamc-auth supports `or` mode, multiple configurations?

**Comment by tzssangglass** [comment]
> hamc-auth supports multiple configurations and uses the `or` mode

I think it's not that hmac-auth itself supports `or`, but that the plugin orchestration system supports `or` for the same plugin.

**Comment by liangliang4ward** [comment]
> I think it's not that hmac-auth itself supports `or`, but that the plugin orchestration system supports `or` for the same plugin.

yes. but may be not the same plugin. perhaps the same type.

**Comment by membphis** [comment]
hi @nfrankel , I updated your example, which is simpler. I think it looks good now.

```shell
$ curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '[
    {
        "id": "ext-plugin-req",
        "priority": 500,
        "conf": [
            {
                "name": "ext-plugin-A",
                "value": "{\"enable\":\"feature\"}"
            }
        ],
    },
    {
        "id": "ext-plugin-req",
        "priority": -500,
        "conf": [
            {
                "name": "ext-plugin-B",
                "value": "{\"disable\":\"feature\"}"
            }
        ]
    }
]'
```

**Comment by nfrankel** [comment]
@membphis LGTM 🙂

**Comment by tokers** [comment]
> hi @nfrankel , I create a new example follow your way. I think it looks good now.
> 
> ```shell
> $ curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '{
>     "desc": "blah",
>     "plugins": [
>         {
>             "id": "limit-count",
>             "priority": 500,
>             "conf": [
>                 {
>                     "time_window": 60,
>                     "count": 10,
>                     "key": "remote_addr"
>                 },
>                 {
>                     "time_window": 1,
>                     "count": 5,
>                     "key": "route_id"
>                 }
>             ]
>         },
>         {
>             "id": "ip-restriction",
>             "priority": 200,
>             "conf": [
>                 {
>                     "whitelist": [
>                         "127.0.0.1",
>                         "113.74.26.106/24"
>                     ]
>                 }
>             ]
>         }
>     ]
> }'
> ```

I still think it'll confuse users, an array has an order attribute, but indeed we don't run the plugin as per their order in the array.

**Comment by nfrankel** [comment]
@tokers That's a legitimate concern. What about:

```bash
$ curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '{
    "desc": "blah",
    "plugins": {
        "limit-count": {
            "priority": 500,
            "conf": [
                {
                    "time_window": 60,
                    "count": 10,
                    "key": "remote_addr"
                },
                {
                    "time_window": 1,
                    "count": 5,
                    "key": "route_id"
                }
            ]
        },
        "ip-restriction": {
            "priority": 200,
            "conf": [
                {
                    "whitelist": [
                        "127.0.0.1",
                        "113.74.26.106/24"
                    ]
                }
            ]
        }
    }
}'
```

**Comment by tokers** [comment]
> @tokers That's a legitimate concern. What about:
> 
> ```shell
> $ curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '{
>     "desc": "blah",
>     "plugins": {
>         "limit-count": {
>             "priority": 500,
>             "conf": [
>                 {
>                     "time_window": 60,
>                     "count": 10,
>                     "key": "remote_addr"
>                 },
>                 {
>                     "time_window": 1,
>                     "count": 5,
>                     "key": "route_id"
>                 }
>             ]
>         },
>         "ip-restriction": {
>             "priority": 200,
>             "conf": [
>                 {
>                     "whitelist": [
>                         "127.0.0.1",
>                         "113.74.26.106/24"
>                     ]
>                 }
>             ]
>         }
>     }
> }'
> ```

Looks better than the original one, but still has the `priority` field, which means users can define the plugin running order by themselves?

**Comment by spacewander** [comment]
> @tokers That's a legitimate concern. What about:
> 
> ```shell
> $ curl -i https://my.host/apisix/admin/plugin_configs/1  -H 'X-API-KEY: abc' -X PUT -d '{
>     "desc": "blah",
>     "plugins": {
>         "limit-count": {
>             "priority": 500,
>             "conf": [
>                 {
>                     "time_window": 60,
>                     "count": 10,
>                     "key": "remote_addr"
>                 },
>                 {
>                     "time_window": 1,
>                     "count": 5,
>                     "key": "route_id"
>                 }
>             ]
>         },
>         "ip-restriction": {
>             "priority": 200,
>             "conf": [
>                 {
>                     "whitelist": [
>                         "127.0.0.1",
>                         "113.74.26.106/24"
>                     ]
>                 }
>             ]
>         }
>     }
> }'
> ```

From a developer's aspect, it is hard to distinguish this from the current arch, as "priority" / "conf" can be a valid field.

What about using a new field instead of "plugins" for the route conf?

**Comment by tokers** [comment]
> What about using a new field instead of "plugins" for the route conf?

Do you have any suggestion?

**Comment by nfrankel** [comment]
Let's take a step back. At the moment, we are not discussing what is the best developer experience but how not to make it too similar to the existing approach. That's another problem, and we can tackle it in another thread using API versioning, for which there are several solutions (_e.g._, path, header, query parameter).

**Comment by tokers** [comment]
I still cannot capture the meaning for using a "priority" field.

**Comment by spacewander** [comment]
I take a closer look at this proposal.
Currently, APISIX is route-based proxy (every configuration is bound to the route). This proposal will require changing APISIX to a plugin-based proxy (every configuration is organized as a plugin configuration), which needs to rewrite APISIX totally, so IMHO I can't accept such a proposal. 

What about a smaller change, like adding a priority field in the route's plugin? Like:
```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/index.html",
    "plugins": {
        "limit-conn": {
            "_meta": {"priority":1200}
            "conn": 1,
            "burst": 0,
            "default_conn_delay": 0.1,
            "rejected_code": 503,
            "key_type": "var",
            "key": "http_a"
        },
        "ip-restriction": {
              "_meta": {"priority":200}
              "whitelist": [
                    "127.0.0.1",
                     "113.74.26.106/24"
               ]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```

**Comment by membphis** [comment]
I think this is acceptable.

**Comment by nfrankel** [comment]
Why the extra verbosity?

`"_meta": {"priority":1200}` vs. `"priority": 1200`

**Comment by tokers** [comment]
@nfrankel `_meta` means metadata for a plugin, encapsulating the priority into it is useful for distinguishing it from the plugin configuration, and if we want to introduce more fields, we can also put them into `_meta`.
