### ISSUE TITLE
request help: upstreams use localhost

### ISSUE THREAD

**Issue by VineFiner** [apache/apisix#6593]
### Issue description

I deploy using docs, but it always fails. return 503
` https://apisix.apache.org/docs/apisix/getting-started/`
I just changed

```
curl "http://127.0.0.1:9080/apisix/admin/upstreams/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "127.0.0.1:9081": 1
  }
}'
```

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@VineFiner In which step that you got the `503` code? Is the process for creating the Upstream object or sending the real traffic?

**Comment by VineFiner** [comment]
> @VineFiner In which step that you got the `503` code? Is the process for creating the Upstream object or sending the real traffic?

I know the problem, it's a docker network problem.
There is no problem installing using RPM.

**Comment by tokers** [comment]
@VineFiner So consider this issue is solved?

**Comment by VineFiner** [comment]
> @VineFiner So consider this issue is solved?

Yes, I'm running fine with docker0 ip 172.17.0.1 .
For the docker-compose example there is web1 service, can you add a case where web1 runs locally.
