### ISSUE TITLE
request help: How get response info by lua plugin?

### ISSUE THREAD

**Issue by navysummer** [apache/apisix#6597]
### Issue description

 How get response info by lua plugin?

### Environment

- apisix version (cmd: `apisix version`):
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by soulbird** [comment]
You can get response header in `header_filter` phase via `ngx.header`. and get response body in `header_filter` phase.
Inside the Apache APISIX project, you can refer to https://github.com/apache/apisix/blob/master/apisix/core/response.lua
