### ISSUE TITLE
request help: real_ip_recursive for real-ip plugin

### ISSUE THREAD

**Issue by crazyMonkey1995** [apache/apisix#6602]
### Issue description

I found that there was once a PR about real_ip_recursive: https://github.com/apache/apisix/pull/4332
But it seems that the real-ip plugin does not have recursive related configuration items. In fact, I looked at the real-ip code and it seems that there is no related implementation. Is there any other way to achieve it? The current scenario is to configure it in the global plugin. real-ip for dynamic modification, looking forward to reply, thanks!

### Environment

- apisix version (cmd: `apisix version`): latest
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by tokers** [comment]
@crazyMonkey1995 I think it can be implemented in the real-ip plugin.

**Comment by crazyMonkey1995** [comment]
> 

Am I missing something? But the logic here is just to return the last IP of XFF
![image](https://user-images.githubusercontent.com/21658981/158164111-a2d0b0d2-6bf6-484b-a4e6-c251ae71be61.png)

**Comment by tokers** [comment]
> > 
> 
> Am I missing something? But the logic here is just to return the last IP of XFF ![image](https://user-images.githubusercontent.com/21658981/158164111-a2d0b0d2-6bf6-484b-a4e6-c251ae71be61.png) @tokers

No, the current implementation of `real-ip` plugin is not totally same to the Nginx real-ip module. We may support the `real_ip_header` and `real_ip_recursive` settings.

**Comment by crazyMonkey1995** [comment]
> > > 
> > 
> > 
> > Am I missing something? But the logic here is just to return the last IP of XFF ![image](https://user-images.githubusercontent.com/21658981/158164111-a2d0b0d2-6bf6-484b-a4e6-c251ae71be61.png) @tokers
> 
> No, the current implementation of `real-ip` plugin is not totally same to the Nginx real-ip module. We may support the `real_ip_header` and `real_ip_recursive` settings.

Ok, I misunderstood.

**Comment by tokers** [comment]
@crazyMonkey1995 Would you like to try it?

**Comment by crazyMonkey1995** [comment]
> @crazyMonkey1995 Would you like to try it?

Okay, but maybe not so soon.

**Comment by tokers** [comment]
> > @crazyMonkey1995 Would you like to try it?
> 
> Okay, but maybe not so soon.

Thanks!
