### ISSUE TITLE
request help: add semicolon check in `make lint`

### ISSUE THREAD

**Issue by shuaijinchao** [apache/apisix#6604]
### Issue description

Check for `;` at the end of lua code and add the check to make lint.

### Solution:
```bash
grep --include="*.lua" -R -Ev '^$|^[--]*.*[^;]$' apisix
```
This method cannot identify and filter nginx templates and FFI C code, so it cannot be directly applied to CI.

**Comment by tokers** [comment]
> ### Issue description
> Check for `;` at the end of lua code and add the check to make lint.

@shuaijinchao I think more details can be supplemented so that it can be a good first issue.

**Comment by membphis** [comment]
I think @shuaijinchao can write your solution first, although he may not be perfect. But it is also useful for others.

**Comment by shuaijinchao** [comment]
> I think @shuaijinchao can write your solution first, although he may not be perfect. But it is also useful for others.

Updated to topic

**Comment by membphis** [comment]
We need a better way, `grep --include="*.lua" -R -Ev '^$|^[--]*.*[^;]$' apisix` is not suitable for us.

<img width="1607" alt="image" src="https://user-images.githubusercontent.com/6814606/158780783-67d58ce9-bf87-4f4b-962f-7af7d7bd0ccd.png">

**Comment by shuaijinchao** [comment]
> We need a better way, `grep --include="*.lua" -R -Ev '^$|^[--]*.*[^;]$' apisix` is not suitable for us.
> 
Yes, this way is not suitable to put into CI.

**Comment by kwanhur** [comment]
I'm not sure, but hope some ideas could inspire by [lualint](https://github.com/philips/lualint/blob/master/lualint).
