### ISSUE TITLE
request help: ipv6 client preferentially proxy to ipv6 upstreams and ipv4 preferentially  proxy to ipv4 upstream

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#6608]
### Issue description

 ipv6 client preferentially proxy to ipv6 upstreams and ipv4 preferentially  proxy to ipv4 upstream

### Environment

- apisix version (cmd: `apisix version`): 2.10.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `curl http://127.0.0.1:9090/v1/server_info` to get the info from server-info API):
- apisix-dashboard version, if have:
- the plugin runner version, if the issue is about a plugin runner (cmd: depended on the kind of runner):
- luarocks version, if the issue is about installation (cmd: `luarocks --version`):

**Comment by zhendongcmss** [comment]
> It's not supported.
> 
> I am curious why this feature is wanted? The client to APISIX and APISIX to upstream are two connections and can use different network stack.

I know that. 

If set the upstreams with ipv4 and ipv6, apisix proxy request to ipv4 or ipv6. 
we hope that the failure of IPv6 switch will not affect the switch of IPv4.

**Comment by spacewander** [comment]
If the IPv6 upstreams are unreliable, you can use IPv4 upstreams by retry / backup.
The IPv4 upstream can be used to serve the IPv6 clients.
