### ISSUE TITLE
[PROPOSAL] Refactor the plugin code organization

### ISSUE THREAD

**Issue by besich** [apache/apisix#6612]
### Description

# PROPOSAL
Refactor the plugin code organization, make the plugin independent from APISIX, and maintain the plugin independently.

# BACKGROUND
The current APISIX compilation method is a full installation, which is very unfriendly to developers and users who install through source code.
Because many plugins depend on third-party libraries, the complicated environment is complex, but most of the time, these plugins are not needed.

# Technical
Current: plugins are mixed under **/apisix/plugins/*.lua**
Suggestion: migrate to **/plugins/*plugin*/**, *plugin* represents different plugins. One plugin is a One directory.

Under each plugin directory, there is an independent **/plugins/*plugin*/package.json** file, which has description information, which stores related to the independent plugin data.

## for example:
* startup code. eg. in **“/plugins/example-plugin/package.json”**, it has **“main”:”index.lua”**. 
* compile the plugin dependency library.
* compile the plugin dependency environment variable.
* unit tests about the plugin 
* multi-language

# BENEFIT
* The plugin can be compiled optionally. When compiling the APISIX, obtain which plugin enabled from the configuration file, and then compile after dynamically generating rockspec.
* Development-friendly. During unit testing, you can only test the enabled plugin.
* Maintenance-friendly. Because the core of APISIX should be relatively stable, the addition of the plugin will be dynamic and frequent.
* Make technical preparations for a marketplace.

**Comment by spacewander** [comment]
This way is overcomplex. I will vote -1 for it.

**Comment by spacewander** [comment]
> The plugin can be compiled optionally

The dependencies of the plugin are very hard to handle. Also, there are a lot of trouble to handle the dependencies between APISIX and plugins.

**Comment by spacewander** [comment]
> Because the core of APISIX should be relatively stable, the addition of the plugin will be dynamic and frequent.

Only people who are not familiar with APISIX will think this way is easier to maintain. As the opinion from the maintainer of APISIX, such way will make APISIX harder to maintain.

**Comment by spacewander** [comment]
Two simple questions:
1. what if a plugin depends on the apisix-base? How can we manage the dependencies with different plugins which require different apisix-base?
2. how to deal with the ecosystem of APISIX, like dashboard, ingress controller, and more?

Only people who are not familiar with APISIX will think this way is easier to maintain. In fact, it makes the situation more complex.
