### ISSUE TITLE
help request: kubernetes configuration is no longer maintained

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#6624]
### Description

https://github.com/apache/apisix/tree/master/kubernetes is no longer maintained. Currently, we already use helm charts to support installing APISIX in k8s. These files are only used by chaos test and should be moved to t/chaos.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by 123liubao** [comment]
Hello, @spacewander  , I want to work on this, please assign it to me.
