### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by wiew521** [apache/apisix#6635]
### Description

There is a problem installing on Tencent cloud server，Is the yum source of apifix inaccessible on Tencent cloud?

![image](https://user-images.githubusercontent.com/65159312/158729619-a5bb2d9a-0f96-47aa-835a-3b14ced703eb.png)

![image](https://user-images.githubusercontent.com/65159312/158729680-f18a830c-7dd1-4c5d-b7ab-9833a3c75b9c.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Centos 8 is not supported yet. Let's move the discussion to https://github.com/apache/apisix/issues/6462

**Comment by wiew521** [comment]
> Centos 8 is not supported yet. Let's move the discussion to #6462

tku，i just found out why.
