### ISSUE TITLE
help request: use k8s nginx ingress to map gateway port 9080

### ISSUE THREAD

**Issue by miahwk** [apache/apisix#6640]
### Description

- I used k8s nginx ingress to map the apisix gateway host,just like apisix-gateway.abc.com.curl the router,it displays 404 not found.But used the F5 device, it is working.
- I dont known whether setup something of ingress or nginx ingress controller.
- By the way,I used nodePort.It is fine.
- So who can give me some suggestion?

### Environment

- APISIX version (2.21):
- Operating system (k8s):

**Comment by tzssangglass** [comment]
cc @tao12345666333 @tokers PTAL

and @miahwk you need to provide reproducible steps and configuration information.

**Comment by tokers** [comment]
How did you send the requests? How did you map the APISIX gateway on Ingress Nginx?

**Comment by tao12345666333** [comment]
Can you show me your Ingress configuration?
