### ISSUE TITLE
docs: Develop writing specification and template for APISIX Chinese Documentation.

### ISSUE THREAD

**Issue by guitu168** [apache/apisix#6651]
### Current State

Because the articles of Apache APISIX are contributed by different people, the current format of document is not uniform, the style of writing is not uniform, the terms are not unified, and the structure is not unified.
中文描述：由于 Apache APISIX 的文章是由不同的人贡献的，因此当前文档存格式不统一、写作风格不统一、用词不统一、架构不统一等问题。

### Desired State

I want to develop a Apache APISIX Chinese document writing standard for the reference and moderator of document contributors. At the end of March, I will show the first draft. If you have more ideas, please let me know.
It mainly includes document writing specification and document writing template.
1. Document writing specification: including the correct writing method of common words, code format, name examples, usage rules of mark pairs, glossary, etc.
2. Document writing template: including principle documents, operation documents, etc.

The following is the completed part, please check:
Personal pronouns, IP addresses and domain names, punctuation, operators, sentences, tables, pictures, word spacing, lists, notes, links, marker pairs, code segments, links, prohibited words, terms, etc.

中文描述：
因此，我想制定一份 Apache APISIX 中文文档写作标准，以供文档贡献者参考和审核者审查。3月底，我会展示初稿。如果你有更多的想法，请告诉我。
规范内容主要包括文档写作规范和文档写作模板。
1. 文档写作规范：包括常用词的正确写法，代码格式，名称示例，标记对使用规则，术语表等内容。
2. 文档写作模板：包括原理类文档， 操作类文档等内容。
以下是已完成部分，请查看：
人称代词、 IP 地址和域名、标点符号、运算符、句子、表格、图片、字间距、列表、Note、链接、标记对、代码段、链接、违禁词、术语等。

**Comment by juzhiyuan** [comment]
Hi @hf400159, glad to see this issue! I would suggest you could work with @navendu-pottekkat together to propose a Style Guide, and then you could present one for Chinese. @navendu-pottekkat is on the ASF Slack channel.

**Comment by navendu-pottekkat** [comment]
@juzhiyuan @hf400159 Here is my suggestion. I will open up an issue and draft a style guide next week and we can collaborate.

https://github.com/apache/apisix/issues/6528#issuecomment-1064011458

**Comment by juzhiyuan** [comment]
Thanks, also cc @kwanhur

**Comment by hf400159** [comment]
@navendu-pottekkat Thank you for your suggestion, I hoped we can cooperate happily, It's a pleasure doing business with you If possible, I will create a style guide for APISIX Chinese documentation.

**Comment by navendu-pottekkat** [comment]
@hf400159 Awesome! There would be some overlaps in the style guide like how to include code snippets, and how to comment on code snippets etc.

**Comment by hf400159** [comment]
@navendu-pottekkat ok, I'll be discussing with you next week via Slack.

**Comment by liangliang4ward** [comment]
at chinese doc parmaters table head, Requirement some docs translate to "必选项", some docs translate to "可选项” and some translate to "是否必须". we should unify.

like :

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/file-logger.md?plain=1#L30

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/google-cloud-logging.md?plain=1#L35

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/traffic-split.md?plain=1#L32

**Comment by juzhiyuan** [comment]
I would prefer to use: 必填：是/否 -> Required: Yes, No

**Comment by liangliang4ward** [comment]
> I would prefer to use: 必填：是/否 -> Required: Yes, No

agree

**Comment by hf400159** [comment]
Yes, that was part of my plan. we will unify the plugin document style.

**Comment by navendu-pottekkat** [comment]
@guitu168 Are you still interested in working on this issue?

**Comment by ro4i7** [comment]
@navendu-pottekkat , i can solve this one, but i will take use of google translate. What you say?
