### ISSUE TITLE
help request: I want to add plublic IP of resolved domain to match rule of route，how i can do?

### ISSUE THREAD

**Issue by lizj3624** [apache/apisix#6658]
### Description

I only allow traffic of matching domain and resolved IP to enter，when apisix is deployed as a north-south traffic gateway to a cluster with many public IP。I think that  add plublic IP of resolved domain to match rule of route，how i can do?

for example:
cluster pulibic ip: 1.1.1.1，2.2.2.2，3.3.3.3
domain: test.my.com，resolved public ip(vip): 1.1.1.1
I only allow traffic of matching domain(test.my.com) and resolved IP(1.1.1.1) to enter，how i can do?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@lizj3624 Always check out the docs firstly :) https://apisix.apache.org/docs/apisix/next/admin-api/#route

**Comment by lizj3624** [comment]
> @lizj3624 Always check out the docs firstly :) https://apisix.apache.org/docs/apisix/next/admin-api/#route

please give an example，thank you very much

**Comment by nic-6443** [comment]
> > @lizj3624 Always check out the docs firstly :) https://apisix.apache.org/docs/apisix/next/admin-api/#route
> 
> please give an example，thank you very much

You can use `vars` matcher with `server_addr` variable from nginx to archive your demand. Like below:
```
{
    "host": "test.my.com",
    "uri": "/*",
    "upstream": {...},
    "vars": [["server_addr", "==", "1.1.1.1"]],
    "name": "test.my.com"
}
```

**Comment by lizj3624** [comment]
Ok，thank you very much.
