### ISSUE TITLE
help request: apisix deployed on k8s issue

### ISSUE THREAD

**Issue by xiaokunliu** [apache/apisix#6660]
### Description

now then i have a question as follow:
i use opneresty and apisix deployed on k8s, on request uri 
apisix/hello : client -> nlb -> apisix -> nginx
nginx/hello: client -> nlb ->  openresty -> nginx

pod config is the same: 4c8g for apisix and openresty

apisix and openresty use config is the same as follow:
use epoll;
worker_processes 4;
worker_connections  32768;

upstream config is the same as follow:
openresty config:
upstream nginx_backend {
        server nginx.test1.svc.cluster.local:80;
        keepalive 320; 
        keepalive_timeout  500s;
        keepalive_requests 1000000;
    }

apisix have config it at the dasborad upstream config as the same with openresty upstream config as follow:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/12118125/158988478-4d25c3a4-4400-4800-aeb0-a44b4e472b1e.png">

now i have a benmarch report, the apisix throught is less than openresty

apisix benmarch report:
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/12118125/158986212-96157bb6-480a-4697-98f5-060c1d8468e9.png">

nginx benmarch report:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/12118125/158986357-3d83ae22-7bb4-4e77-8b4f-28b874f24d73.png">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by xiaokunliu** [comment]
how to keep apisix have the expected throghtout as the officical benmarch result

**Comment by tokers** [comment]
> and have a question, have the apisix enabled tcp_nopush and tcp_nodelay and epoll config ?

@xiaokunliu As for this question, you can check out the rendering nginx.conf. If they are not set, default values are applied.

**Comment by tokers** [comment]
> how to keep apisix have the expected throghtout as the officical benmarch result

APISIX is based on OpenResty, it has more code paths than OpenResty, so more overheads are reasonable.
