### ISSUE TITLE
docs: unify chinese doc table head

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#6669]
### Current State

at chinese doc parmaters table head, `Requirement` some docs  translate to "必选项", some docs translate to "可选项” and some translate to "是否必须". we should unify.

like :

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/file-logger.md?plain=1#L30

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/google-cloud-logging.md?plain=1#L35

https://github.com/apache/apisix/blob/a47dab7eecd90998499eae10b477ce7fd8175c28/docs/zh/latest/plugins/traffic-split.md?plain=1#L32

### Desired State

unify translate.

**Comment by spacewander** [comment]
Related: https://github.com/apache/apisix/issues/6669

**Comment by liangliang4ward** [comment]
> Related: #6669

what's that mean?  relate this issue?

**Comment by liangliang4ward** [comment]
> Would you like to move this discussion to #6669?

this issue code is  6669

**Comment by spacewander** [comment]
Sorry, it should be https://github.com/apache/apisix/issues/6651
