### ISSUE TITLE
feat: Redis backend support for cache_strategy in proxy-cache plugin.

### ISSUE THREAD

**Issue by fatihbm** [apache/apisix#6676]
### Description

Hi,
I have wondered, is there any particular reason why the proxy-cache plugin doesn't have redis backend support for cache_strategy?
If it had been this support, it could provide distributed cache support and give the object's validity more accurately without node dependency.

Currently, the validity of the content to be cached is determined only when a request is made to the relevant apisix node independent of other nodes. 
Therefore, each node is responsible for its own cache time. So that causes problems when caching highly variable objects under high traffic. For example, one user can have an older version, and another can have a newer version even if they requested it at the same time.

**Comment by jagerzhang** [comment]
agree

**Comment by tzssangglass** [comment]
When adding redis as a cache, do we need to force the cached data to be fetched from redis? In that case, there will be a performance loss.


> Therefore, each node is responsible for its own cache time. So that causes problems when caching highly variable objects under high traffic. For example, one user can have an older version, and another can have a newer version even if they requested it at the same time.

This problem does exist, but is it not a very serious problem for proxy cache scenarios?
I think that proxy caching allows cached data and upstream response data to be inconsistent within the cache time, which is something that will be considered at the beginning of the proxy cache design.

Anyway, using redis as the cache implementation for proxy cache provides more options.

**Comment by fatihbm** [comment]
I understand your performance concern. I have extended this plugin with Redis backend support. Now, it first attempts to find out in a shared dictionary. If the cached object is found it'll be returned from here (HIT), if not found, it'll attempt fetching from Redis. This stage has two situations (HIT) or (MISS). If the status is MISS, the object is stored in both Redis and the shared dictionary. The shared dictionary is used to reduce performance loss. it will only use the cache for 10 seconds.
here we are only waiting an extra 10 seconds for the PURGE operation. Because PURGE operation just works on Redis.

We have high traffic and run more than ten nodes in each data center. This development will be valuable to us.

**Comment by tokers** [comment]
@fatihbm A multi-layer cache is a good, would you like to submit a proposal to the mailing list, and let's talk about it.

**Comment by tzssangglass** [comment]
I think we can consider it and let's discuss it on the mailing list first.

**Comment by nfrankel** [comment]
IMHO, it doesn't make sense to have a custom Redis (or whatever storage) integration for each plugin. We need to create a new abstraction, _i.e._, `Storage` that can be shared across all plugins that need a storage capability.

I created such a proposal for the [Google Summer of Code](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2022+Ideas+list#GSoC2022Ideaslist-ApacheAPISIXIntroduceaStorageabstraction). If we don't have any student interested, I'd be inclined we do it ourselves.

**Comment by nfrankel** [comment]
@tzssangglass Then we should introduce this abstraction ourselves

**Comment by tzssangglass** [comment]
> @tzssangglass Then we should introduce this abstraction ourselves

Do we need to wrap redis operations in APISIX to provide a unified pdk for the plugin?

**Comment by spacewander** [comment]
Using redis to cache upstream response is different from using it as configuration storage.

**Comment by nfrankel** [comment]
@spacewander A cache is a superset of a simple CRUD storage. Let's provide a caching storage abstraction and let's implement it via multiple concretions, _i.e._, in-memory, Redis, etc.

**Comment by fatihbm** [comment]
I understand from all this that there is a better solution proposal, but its implementation needs a costly development.  So until this is done, what is your thinking about the current Redis solution? Doing this just for this plugin can be a quick win?

**Comment by nfrankel** [comment]
@fatihbm Yes, it can be a quick win. And the next time we are faced with the same problem, we can also have a quick win. And then every time, we can favor short-term gains over long-term ones. Then, it will make the move to the Storage abstraction even more expensive as we will have to migrate all existing plugins to the new architecture. Hence, we will never do it.

The sooner we introduce the Storage abstraction, the better it is.

**Comment by middt** [comment]
Is there any progress regarding this issue?
We also need such a plugin; if there is no plan, we plan to develop it ourselves with Go.
