### ISSUE TITLE
feat: the limit-count plugin, if the server with the slot that needs to be used is unreachable it should be able to use other servers in the cluster.

### ISSUE THREAD

**Issue by fatihbm** [apache/apisix#6677]
### Description

issue #6530 
if the server with the slot that needs to be used is unreachable, the plugin doesn't search for a new slot on other servers in the cluster. Therefore, the router, service, etc. using that slot will be interrupted.

To avoid this, the plugin must be able to use new slots from other servers in the cluster.

**Comment by tzssangglass** [comment]
Should we update the `lua-resty-redis-cluster`?

**Comment by fatihbm** [comment]
> 

most likely yes. but I'm still not 100% sure.

**Comment by tzssangglass** [comment]
form https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/limit-count-redis-cluster.lua, there is very little code related to handling redis clusters.

**Comment by fatihbm** [comment]
I don't think the problem is here.  because the slot selection is done in `lua-resty-redis-cluster`.  I will review this code when I get the chance.
