### ISSUE TITLE
help request: how to record 2K+ logs?

### ISSUE THREAD

**Issue by navysummer** [apache/apisix#6680]
### Description

ngx.log and  core.log.info  can only record 2K logs，and those exceeding 2K cannot be recorded

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
This is the definition of nginx in https://github.com/nginx/nginx/blob/master/src/core/ngx_log.h#L76.
Apache APISIX does not support modifying this value yet.
You can consider splitting the log in the business logic so that it can be fully displayed
