### ISSUE TITLE
Whether lists in 'apisix admin-API' support pagination, such as routing lists

### ISSUE THREAD

**Issue by rampagecong** [apache/apisix#6681]
### Description

Whether lists in 'apisix admin-API' support pagination, such as routing lists.

### Environment

- APISIX version (run `apisix version`):2.12
- Operating system (run `uname -a`):Linux localdev 3.10.0-1160.49.1.el7.x86_64 #1 SMP Tue Nov 30 15:51:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):v3.5.0
- APISIX Dashboard version, if relevant:v2.10.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):v3.8.0

**Comment by jwrookie** [comment]
You can use [apisix-dashboard](https://github.com/apache/apisix-dashboard)

**Comment by rampagecong** [comment]
> You can use [apisix-dashboard](https://github.com/apache/apisix-dashboard)

Good idea,But I would like to use the power of admin-API for my own management platform

**Comment by jwrookie** [comment]
`etcd` not support offset, you may need to cache a copy of the data yourself, just like [apisix-dashboard](https://github.com/apache/apisix-dashboard)

**Comment by rampagecong** [comment]
> `etcd` not support offset, you may need to cache a copy of the data yourself, just like [apisix-dashboard](https://github.com/apache/apisix-dashboard)

OK,Thank you.
