### ISSUE TITLE
feat: add new admin api to query plugin info of a route or service

### ISSUE THREAD

**Issue by rpei2022** [apache/apisix#6685]
### Description

As a new user, I am trying to use apisix in our product, I want to get the plugins of one route or service, and do not care about other info of the route and service. Could we consider to add such new APIs?

**Comment by shuaijinchao** [comment]
I think AdminAPI will suffice, we can listen to other people's suggestions.

**Comment by juzhiyuan** [comment]
>  I want to get the plugins of one route or service, and do not care about other info of the route and service.

Hi, just to make sure, do you want one API like `/routes/{ID}/plugins` and it will return only `plugin` configuration?

I'd like to know more about your scenarios 😄
