### ISSUE TITLE
feat: Hope consul_kv supports the configuration of consul access controls.

### ISSUE THREAD

**Issue by gzhsnail** [apache/apisix#6692]
### Description

Hope consul_kv supports the configuration of consul access controls.
 The version I use is v2.13.

Official document of consul: 
          https://www.consul.io/docs/security/acl

**Comment by tokers** [comment]
Fair enough, access control is common.

**Comment by tzssangglass** [comment]
Can you add docs link about consul access control?

**Comment by jujiale** [comment]
I also find Apisix consul_kv is not have config for ACL，If consul open ACL，Could it be said that apisix has not access to consul???

**Comment by tzssangglass** [comment]
> If consul open ACL，Could it be said that apisix has not access to consul???

I have no try, if you're interested, give it a try and let's see what happens.
