### ISSUE TITLE
help request: apisix在解析域名时失败，出现循环

### ISSUE THREAD

**Issue by zhantanfeng** [apache/apisix#6700]
### Description

在双栈k8s集群中，利用apisix进行流量转发，出现解析域名失败的情况，具体日志如下：
![image](https://user-images.githubusercontent.com/47771083/159825830-b2d78f2b-c90f-48d4-8260-41f31cfa4ae0.png)
但是在ping这个域名时，已经解析出了这个地址
![image](https://user-images.githubusercontent.com/47771083/159826009-aa080b9f-2d71-4d08-8fb8-bf7d43bfc5c9.png)
在apisix的配置文件中也已经开启了ipv6
![image](https://user-images.githubusercontent.com/47771083/159826148-0096fdbb-d07b-4073-9813-e68d5e49d52b.png)
apisix版本为：2.5
k8s版本为1.21.5
etcd版本为：3.4.9
请问改如何解决呢？
[tcpdump.zip](https://github.com/apache/apisix/files/8360300/tcpdump.zip)

### Environment

- APISIX version (run `apisix version`):2.5
- Operating system (run `uname -a`):Linux dev-node11 4.19.25-200.1.el7.bclinux.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.19.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.9
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Can it be reproduced with the APISIX 2.12?
Would you like to provide a packet capture file when APISIX failed to resolve the address and the one for ping?

**Comment by zhantanfeng** [comment]
> 
I will try with APISIX 2.12, but I tried with 2.13, it can not run.

**Comment by spacewander** [comment]
> > 
> 
> I will try with APISIX 2.12, but I tried with 2.13, it can not run.

If 2.13 has the same problem, 2.12 also suffers from it. Let me see the packet capture file.

**Comment by zhantanfeng** [comment]
> > > 
> > 
> > 
> > I will try with APISIX 2.12, but I tried with 2.13, it can not run.
> 
> If 2.13 has the same problem, 2.12 also suffers from it. Let me see the packet capture file.

I got the packet capture file, what info do you want to see? it has lots of info.

**Comment by zhantanfeng** [comment]
> > > 
> > 
> > 
> > I will try with APISIX 2.12, but I tried with 2.13, it can not run.
> 
> If 2.13 has the same problem, 2.12 also suffers from it. Let me see the packet capture file.
![Uploading image.png…]()
here is the packet capture file screenshot.

**Comment by spacewander** [comment]
You can attach the pcap file in this issue.

**Comment by zhantanfeng** [comment]
> You can attach the pcap file in this issue.

I have uploaded the pcap file.

**Comment by spacewander** [comment]
I have just read the pcap file.
Look like the server queried 114.114.114.114 / 1.1.1.1 / 223.5.5.5 and got "No such name".

Could you provide a successful case's pcap with ping?

**Comment by zhantanfeng** [comment]
> I have just read the pcap file. Look like the server queried 114.114.114.114 / 1.1.1.1 / 223.5.5.5 and got "No such name".
> 
> Could you provide a successful case's pcap with ping?

It's a successful case, but not same environment with the error case.
[tcpdump.zip](https://github.com/apache/apisix/files/8361046/tcpdump.zip)

**Comment by zhantanfeng** [comment]
> I have just read the pcap file. Look like the server queried 114.114.114.114 / 1.1.1.1 / 223.5.5.5 and got "No such name".
> 
> Could you provide a successful case's pcap with ping?

![image](https://user-images.githubusercontent.com/47771083/160390140-f6eb9f45-9e07-46b0-8a60-3c0a8a4689cf.png)
It looks like it can parse this domain.

**Comment by tokers** [comment]
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/10428333/160515340-ed3e5dd4-5849-4eba-b897-5058b2854ef9.png">

It seems that the domain name has a duplicated ".svc.cluster.local" suffix.

**Comment by zhantanfeng** [comment]
> <img alt="image" width="1177" src="https://user-images.githubusercontent.com/10428333/160515340-ed3e5dd4-5849-4eba-b897-5058b2854ef9.png">
> 
> It seems that the domain name has a duplicated ".svc.cluster.local" suffix.

But it is successful, and I think it maybe has bussiness with the kube-dns svc address, do apisix support ipv6？

**Comment by spacewander** [comment]
Does manually configuring the nameserver in https://github.com/apache/apisix/blob/542569091d4b6a40b9d560c4fe76077ee9dba087/conf/config-default.yaml#L120 can solve the problem?

**Comment by zhantanfeng** [comment]
> Does manually configuring the nameserver in
> 
> https://github.com/apache/apisix/blob/542569091d4b6a40b9d560c4fe76077ee9dba087/conf/config-default.yaml#L120
> 
> can solve the problem?

You mean config dns_resolver with "8.8.8.8" or others? it can not solve the problem, I have tried it. Now it uses zhe cluster DNS server, but failed too.

**Comment by spacewander** [comment]
dns_resolver with "fd11:..."

**Comment by zhantanfeng** [comment]
> dns_resolver with "fd11:..."
If I configure this directly, there will be an error. Apifix can't run.

**Comment by spacewander** [comment]
What error?

**Comment by spacewander** [comment]
Don't forget to wrap the address with `""`, as there is a `:` in IPv6 address and will be recoginized as map if `""` is not given.

**Comment by zhantanfeng** [comment]
> 



> Don't forget to wrap the address with `""`, as there is a `:` in IPv6 address and will be recoginized as map if `""` is not given.

Here is the config file，but is failed too.
![image](https://user-images.githubusercontent.com/47771083/160533810-c86e0133-a7df-4f77-af11-57c43b072132.png)

**Comment by tokers** [comment]
@zhantanfeng You just configure the IPv6, but missing the port.

**Comment by zhantanfeng** [comment]
@spacewander @tokers Thank you very much! You solved the problem!
