### ISSUE TITLE
feat: As a user, when use basic-auth if password or username is error I don't want tell truth message

### ISSUE THREAD

**Issue by liangliang4ward** [apache/apisix#6703]
### Description

https://github.com/apache/apisix/blob/2149ab12bcb279574f4a68154c13087baa5477cf/apisix/plugins/basic-auth.lua#L169-L178

maybe we should tell them "usename or password is error"

**Comment by spacewander** [comment]
LGTM

**Comment by membphis** [comment]
If other authentication plugins have similar issues, we should fix them together.

**Comment by liangliang4ward** [comment]
I want fix them .
