### ISSUE TITLE
help request: the "Extract branch name" step is unnecessary in some workflow

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#6706]
### Description

https://github.com/apache/apisix/blob/2149ab12bcb279574f4a68154c13087baa5477cf/.github/workflows/kubernetes-ci.yml#L42
https://github.com/apache/apisix/blob/2149ab12bcb279574f4a68154c13087baa5477cf/.github/workflows/tars-ci.yml#L42

The output of this step is not used later.

@zhixiongdu027
Would you like to deal with them?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zhixiongdu027** [comment]
I will do it
