### ISSUE TITLE
help request:  Add a header if exist not overwrite

### ISSUE THREAD

**Issue by purekeeper** [apache/apisix#6710]
### Description

How can i add a header if not exist ,don't overwite if exist. Which plugin should used, proxy-rewite is not suitable,beacause it will overwrite if exist

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Maybe, we can add a configuration to determine if headers needs to be rewritten

**Comment by tokers** [comment]
@purekeeper Currently, you may support this by the serverless plugin: https://apisix.apache.org/docs/apisix/plugins/serverless.

**Comment by kwanhur** [comment]
- If the header was on request, `proxy-rewrite` plugin is a better choice.
- If it's on response, `response-rewrite` plugin is a better choice.

But both them have no support .

Support to set header if nonexistent, they'll easier to reach intention than `serverless` plugin.

**Comment by tzssangglass** [comment]
Another compromise is to use the `vars` on the route to distinguish between routes with a specified header and those without one, and to handle them separately.

IMO, don't override if it exists: this will cause to check the all headers, which is inefficient.

**Comment by PGDream** [comment]
suggest request add、remove、replace header plugin.

**Comment by soulbird** [comment]
solved in #8336
