### ISSUE TITLE
bug:  error heartbeat www.iresty.com

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#6714]
### Current Behavior

Why apisix send heartbeat to www.iresty.com ? I don't find any `www.iresty.com` string on lua code. Does it compile on binary ？

![image](https://user-images.githubusercontent.com/88528414/160038157-480d4605-c2b0-4ff6-b0ee-4c03a211c241.png)

### Steps to Reproduce

Doesn't config DNS.

### Environment

- APISIX version (run `apisix version`): 2.7
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Strange. There is no heartbeat.lua in APISIX.

**Comment by moonming** [comment]
we can remove all iresty.com now.

**Comment by moonming** [comment]
there is no heartbeat in Apache APISIX

**Comment by zhendongcmss** [comment]
> Strange. There is no heartbeat.lua in APISIX.

I am confused too.

**Comment by zhendongcmss** [comment]
2.10.1 have this issue too.

**Comment by zhendongcmss** [comment]
It send heartbeat to www.irest.com every hour from the timestamp.

**Comment by zhendongcmss** [comment]
It is occasional， no fixed time.

**Comment by tzssangglass** [comment]
Maybe you used some third-party plugins, most likely this one: https://github.com/UnderTreeTech/api-gateway/blob/master/apisix/plugins/heartbeat.lua#L117

**Comment by zhendongcmss** [comment]
NO, we don't use it. There are no `heartbeat.lua` on our code .

**Comment by zhendongcmss** [comment]
![image](https://user-images.githubusercontent.com/88528414/160093275-c7926569-5731-4d34-a8f8-5c2f6972244e.png)

**Comment by zhendongcmss** [comment]
![image](https://user-images.githubusercontent.com/88528414/160093669-bc8c1d63-5d87-4fdc-857a-8ff7c4eb491b.png)

**Comment by zhendongcmss** [comment]
This is the question, we don't add any 3rd plugins.

**Comment by tokers** [comment]
> ![image](https://user-images.githubusercontent.com/88528414/160093669-bc8c1d63-5d87-4fdc-857a-8ff7c4eb491b.png)

Not only the APISIX home directory but also libraries where Lua dependencies storing, you may also search the keyword "heartbeat" to see if there are some references in you code.
