### ISSUE TITLE
docs: sync Chinese version FAQ docs

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix#6720]
### Current State

#6695 updated English FAQ docs, We need to update the Chinese version.

### Desired State

Update the Chinese version `FAQ` docs

**Comment by hanzhenfang** [comment]
@guoqqqi 
I think i can complete it well.

**Comment by guoqqqi** [comment]
@hanzhenfang  Looking forward to your PR~ Thanks

**Comment by Ajay-singh1** [comment]
@guoqqqi Can we close this issue now as it has been fixed?
