### ISSUE TITLE
help request: 内存持续增涨OOM

### ISSUE THREAD

**Issue by pguokun** [apache/apisix#6725]
## 环境
服务器配置：阿里云(8核 32G)
操作系统：CentOS 7.9

## 问题现象：内存持续涨
![image](https://user-images.githubusercontent.com/15042141/160220515-2f6f890a-160d-4909-b5df-a38faf07d5a7.png)

## apisix自定义配置
http_configuration_snippet配置：
    client_header_buffer_size 4k;
    client_body_buffer_size  512k;
    large_client_header_buffers 4 32k;
    sendfile on;
    tcp_nopush     on;
    tcp_nodelay on;
    proxy_connect_timeout    300;
    proxy_read_timeout       300;
    proxy_send_timeout       300;
    proxy_buffer_size        32k;
    proxy_buffers            4 16k;
    proxy_busy_buffers_size 32k;
    proxy_temp_file_write_size 32k;
其他配置都是开源版本默认

## 插件使用
kafka-logger
prometheus
zipkin

### Steps to Reproduce

1、阿里云-容器服务 ACK helm安装
2、apisix日志推送到kafka

### Environment

- APISIX version (run `apisix version`): 2.12.1
- Operating system (run `uname -a`): Linux apisix-6d7cd4c778-28jgx 3.10.0-1160.15.2.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 无
- APISIX Dashboard version, if relevant: 2.10.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kwanhur** [comment]
If ok, suggest you disable all the plugins to eliminate their effects. Then enable plugin one by one.

**Comment by tzssangglass** [comment]
Is the memory performance of instance `29zhg` normal? Is there any difference?

**Comment by tokers** [comment]
@pguokun What about other metrics like QPS, CPU?

**Comment by jagerzhang** [comment]
@pguokun 我在腾讯云TKE（K8S）也发现有这个问题，内存增长趋于线性，我们这边用的插件如下：

全局插件：
- request-id
- resonset-rewrite
- kafka-logger

路由插件：
- proxy-rewrite （5%）
- consumer-restriction （70%）
- hmac（70%）
- limit-count (70%)

![image](https://user-images.githubusercontent.com/9711651/160310159-bb340827-cbf4-47b6-9097-d7f8530d2aa4.png)
![image](https://user-images.githubusercontent.com/9711651/160310128-72dd4e65-a495-4e5a-825a-9b0d584b1971.png)

不太清楚这里面有没有GC机制，如果有GC，GC的触发条件是不是内存占用到一定程度时才触发？而运行在容器里面，程序看到的内存其实是宿主机的内存，而非容器limit内存，会导致永远不可能触发GC呢？目前Python3.7及以下版本就有这个问题，看到的是宿主机的资源，导致GC不会被主动执行。

以上，仅供参考哈~

**Comment by spacewander** [comment]
LuaJIT manages the GC total count in the GCState.total field, so it won't depend on the host's memory info.

**Comment by jagerzhang** [comment]
> LuaJIT manages the GC total count in the GCState.total field, so it won't depend on the host's memory info.

got it.

**Comment by GhangZh** [comment]
I have the same problem, deployed on k8s with apisix pod 64G memory setting. 2GB traffic scenario on pressure test is OOM when uploading large files. but no OOM problem with traefik with 8G memory setting。

**Comment by tokers** [comment]
Memory allocated by `client_boy_buffer_size` is not managed by LuaJIT. It will be recycled after the request finalizing.

**Comment by spacewander** [comment]
> client_body_buffer_size 10240m

This buffer is preallocated per request. If you want to reduce disk io, you can configure to avoid request buffering via https://apisix.apache.org/docs/apisix/plugins/proxy-control

**Comment by tincopper** [comment]
我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。
在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。

![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)

解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。

**Comment by jagerzhang** [comment]
> 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> 
> ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> 
> 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。

我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。

**Comment by chenglin321** [comment]
> > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> 
> 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。

这个问题，有解决吗？

**Comment by tokers** [comment]
> > > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> > 
> > 
> > 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。
> 
> 这个问题，有解决吗？

This may be due to the in-memory logs save.

**Comment by chenglin321** [comment]
> > > > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > > > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > > > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> > > 
> > > 
> > > 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。
> > 
> > 
> > 这个问题，有解决吗？
> 
> This may be due to the in-memory logs save.

谢谢，这个有对应诊断分析的工具，我先自己诊断下？

**Comment by tincopper** [comment]
> > > > > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > > > > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > > > > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> > > > 
> > > > 
> > > > 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。
> > > 
> > > 
> > > 这个问题，有解决吗？
> > 
> > 
> > This may be due to the in-memory logs save.
> 
目前发现kafka-logger这个插件在我们环境中总是会断连，而且不会重连，导致一些日志积压在内存当中。感觉像是从lru当中获取的producer已经是断连了，想要添加重连逻辑的，但是没有发现有检测连接是否正常的api。现在处理是把从lru获取client对象改成直接从新获取producer，但是之前buffer的日志会发送失败。

**Comment by chenglin321** [comment]
> > > > > > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > > > > > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > > > > > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> > > > > 
> > > > > 
> > > > > 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。
> > > > 
> > > > 
> > > > 这个问题，有解决吗？
> > > 
> > > 
> > > This may be due to the in-memory logs save.
> 
> 目前发现kafka-logger这个插件在我们环境中总是会断连，而且不会重连，导致一些日志积压在内存当中。感觉像是从lru当中获取的producer已经是断连了，想要添加重连逻辑的，但是没有发现有检测连接是否正常的api。现在处理是把从lru获取client对象改成直接从新获取producer，但是之前buffer的日志会发送失败。

好的,谢谢。那我们还不一样。我这边是写一个自定义java插件,java插件的内存占用还好，openresty的内存不断增长，线上每两天realod下apisix。 -  -

**Comment by kqkdChen** [comment]
Did you finally find the cause and solution?

**Comment by removecode** [comment]
> > > > > > 我们也发现了这个问题，之前以为是代码的问题，但是发现nginx进程实际占用的内存是非常小的，后面排查是因为写日志文件accesss.log/error.log过大，然后导致page cache会很大，因为k8s的内存统计是包括rss + buffer/cache的。 在执行执行echo "" > access.log之后发现内存是直线下降的。不知道这个问题是不是也是这个原因导致的。
> > > > > > ![image-20220713173355369](https://user-images.githubusercontent.com/16191759/178891461-1a503df2-d62b-44bf-8160-a084f10660e8.png)
> > > > > > 解决办法：目前是通过log-rotate插件进行日志的滚动切割定期删除历史文件。
> > > > > 
> > > > > 
> > > > > 我们这边没有开文件日志，用的kafka-logger插件，也有泄漏问题。
> > > > 
> > > > 
> > > > 这个问题，有解决吗？
> > > 
> > > 
> > > This may be due to the in-memory logs save.
> 
> 目前发现kafka-logger这个插件在我们环境中总是会断连，而且不会重连，导致一些日志积压在内存当中。感觉像是从lru当中获取的producer已经是断连了，想要添加重连逻辑的，但是没有发现有检测连接是否正常的api。现在处理是把从lru获取client对象改成直接从新获取producer，但是之前buffer的日志会发送失败。

请问这个后来怎么解决的，我也发现了同样的问题。
