### ISSUE TITLE
bug: Can not access opentelemetry header in ext-plugin-pre-req plugin

### ISSUE THREAD

**Issue by Goxiaoy** [apache/apisix#6728]
### Current Behavior

opentelemetry  propagation header will be inject here by `carrier_new`

https://github.com/apache/apisix/blob/38663991c189c3c0d00ab48bcc9664142fabb170/apisix/plugins/opentelemetry.lua#L304-L305

which call
https://github.com/yangxikun/opentelemetry-lua/blob/3f8e88aa31046d1fd4e8b1a51af9b5f2044514ca/lib/opentelemetry/trace/propagation/carrier.lua#L14-L16

```lua
function _M.set(self, name, val)
    ngx.req.set_header(name, val)
end
```

This header seems not be able to access during the later `ext-plugin-pre-req` golang plugin Filter
I want to do some RPC calls in the go plugin with tracing, so I need to access this header

### Expected Behavior

opentelemetry conext should be propagated to the next plugin

### Steps to Reproduce

1. Run APISIX with docker image
2. Configure plugins `opentelemetry` and `ext-plugin-pre-req` on
3. Access opentelemetry tace header in golang plugin
```
trace := r.Header().Get("traceparent")
```
4. trace is empty

### Environment

- APISIX version (2.13.0):
- Operating system (centos`):
- Plugin runner version, for issues related to plugin runners: dee7fa0167af0ed8cdcd87d4321a43b194f2a7ed

**Comment by spacewander** [comment]
Interesting. It is expected has been fixed in https://github.com/apache/apisix/commit/210575cc08e8296083332caa17e259f83ef3beca. I will try to reproduce it tomorrow.
