### ISSUE TITLE
docs: Update plugin documentation

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix#6734]
### Current State

The plugin docs are inconsistent.

### Desired State

The plugin docs should be made consistent to enhance readability and make it easy to navigate.

It should also follow the documentation style guide: https://github.com/apache/apisix-website/pull/974

**Comment by navendu-pottekkat** [comment]
I will open PRs for each section to fix this soon.

**Comment by juzhiyuan** [comment]
Just added to Project https://github.com/orgs/apache/projects/35

**Comment by navendu-pottekkat** [comment]
Boom!

**Comment by tzssangglass** [comment]
nice
