### ISSUE TITLE
grpc-transcode+eureka, return 502

### ISSUE THREAD

**Issue by tq0426w** [apache/apisix#6740]
### Description

use grpc-transcode, give ip:port, can proxy grpc protocol by http protocol.

But when i use eureka as registry, i get 502 response.

apisix error.log:

2022/03/29 10:59:58 [error] 26592#26592: *58183 upstream prematurely closed connection while reading response header from upstream, client: 223.104.41.240, server: _, request: "GET /grpctest?name=mqtt HTTP/1.1", upstream: "grpc://172.17.77.181:58080", host: "121.43.113.62:9080"

i'm not sure whether apisix can get right grpc port, because  the port 58080 in "grpc://172.17.77.181:58080" is http protocol port.

how could i config to use grpc-transcode+eureka?

### Environment

- APISIX version (2.13.0):
- Operating system (Linux HOST099ECS 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux):
- OpenResty / Nginx version (nginx version: openresty/1.19.9.1):

**Comment by soulbird** [comment]
Please provide more information so that we can reproduce it, e.g： routes and upstream or any other...

**Comment by tzssangglass** [comment]
> upstream prematurely closed connection while reading response header from upstream

this is usually a problem with upstream connections.

> i'm not sure whether apisix can get right grpc port, because the port 58080 in "grpc://172.17.77.181:58080" is http protocol port.

It is likely that your upstream service is registered in eureka with the http port, so APISIX got the http port.

You can refer to this issue: https://github.com/apache/apisix/issues/5815 and this fix：https://github.com/apache/apisix/pull/5894, I think it's a similar problem.

**Comment by shuaijinchao** [comment]
You can try to use the grpc client to simulate the current request to verify that the current upstream is valid.

**Comment by tq0426w** [comment]
i modify discovery/eureka/init.lua code.

i find init.lua get port from eureka by "port" or "securePort" field.
but when a gRPC server register on eureka, its gRPC port in metadata.gRPC_port.

so i add it.

now my grpc-transcode+eureka can work.

**Comment by tzssangglass** [comment]
> i modify discovery/eureka/init.lua code.
> 
> i find init.lua get port from eureka by "port" or "securePort" field. but when a gRPC server register on eureka, its gRPC port in metadata.gRPC_port.
> 
> so i add it.
> 
> now my grpc-transcode+eureka can work.

Welcome to contribute PR
