### ISSUE TITLE
help request: How to Customize the Plugin Directory

### ISSUE THREAD

**Issue by kingmouse-yx** [apache/apisix#6743]
### Description

I have some plugins that I developed myself. Can I customize the directory to store them？

### Environment

- APISIX version (run `apisix version`): 2.12.1
- Operating system (run `uname -a`):  Darwin kingmouse.lan 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan 5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant: 2.10.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
You can load your code through this configuration：https://github.com/apache/apisix/blob/6cd7b8d024/conf/config-default.yaml#L52

**Comment by kingmouse-yx** [comment]
@soulbird 
I added the extra_lua_path configuration to the apisix configuration file
```
  extra_lua_path: "/usr/local/apisix/third/UcEtcdCore.lua"
```
But this error is reported when the service starts.

Actually what I want to say is,
Can the plugins I develop not be placed in the directory `/usr/local/apisix/apisix/plugins`.
For example, the directory `/tmp/myPlugins`.

**Comment by soulbird** [comment]
reference：https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md

**Comment by tokers** [comment]
> @soulbird @kingmouse-yx I met with the the same issue, I added my directory in extra_lua_path in the config.yaml and added my plugin into the plugins list in config.yaml, why I get the follwing error when restart the apisix? 2022/05/17 08:26:35 [error] 31#31: *2 [lua] plugin.lua:110: load_plugin(): failed to load plugin [plugin-test] err: module 'apisix.plugins.plugin-test' not found: no field package.preload['apisix.plugins.plugin-test'] no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/plugin-test.lua' no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/plugin-test/init.lua' no file '/usr/local/apisix/apisix/plugins/plugin-test.lua' no file '/usr/local/apisix/apisix/plugins/plugin-test/init.lua' no file '/usr/local/openresty/site/lualib/apisix/plugins/plugin-test.ljbc' no file '/usr/local/openresty/site/lualib/apisix/plugins/plugin-test/init.ljbc' no file '/usr/local/openresty/lualib/apisix/plugins/plugin-test.ljbc' no file '/usr/local/openresty/lualib/apisix/plugins/plugin-test/init.ljbc' no file '/usr/local/openresty/site/lualib/apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/site/lualib/apisix/plugins/plugin-test/init.lua' no file '/usr/local/openresty/lualib/apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/lualib/apisix/plugins/plugin-test/init.lua' no file './apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/plugin-test.lua' no file '/usr/local/share/lua/5.1/apisix/plugins/plugin-test.lua' no file '/usr/local/share/lua/5.1/apisix/plugins/plugin-test/init.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/plugin-test/init.lua' no file './apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/plugin-test.lua' no file '/usr/local/share/lua/5.1/apisix/plugins/plugin-test.lua' no file '/usr/local/share/lua/5.1/apisix/plugins/plugin-test/init.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/plugin-test.lua' no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/plugin-test/init.lua' no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/openresty/site/lualib/apisix/plugins/plugin-test.so' no file '/usr/local/openresty/lualib/apisix/plugins/plugin-test.so' no file './apisix/plugins/plugin-test.so' no file '/usr/local/lib/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/lib/lua/5.1/loadall.so' no file './apisix/plugins/plugin-test.so' no file '/usr/local/lib/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/plugin-test.so' no file '/usr/local/lib/lua/5.1/loadall.so' no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix.so' no file '/usr/local/apisix//deps/lib/lua/5.1/apisix.so' no file '/usr/local/openresty/site/lualib/apisix.so' no file '/usr/local/openresty/lualib/apisix.so' no file './apisix.so' no file '/usr/local/lib/lua/5.1/apisix.so' no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so' no file '/usr/local/lib/lua/5.1/loadall.so' no file './apisix.so' no file '/usr/local/lib/lua/5.1/apisix.so'

What's your `extra_lua_path`?

**Comment by rpei2022** [comment]
@tokers  extra_lua_path: "/opt/apisix/third/?.lua"

**Comment by soulbird** [comment]
> https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md

It seems that `extra_lua_path ` does not take effect.  Could you show info about `config.yaml `?

**Comment by rpei2022** [comment]
@soulbird 
apisix:
  node_listen: 9080             # APISIX listening port
  enable_heartbeat: true
  enable_admin: true
  enable_admin_cors: true
  enable_debug: false

  enable_dev_mode: false                       # Sets nginx worker_processes to 1 if set to true
  enable_reuseport: true                       # Enable nginx SO_REUSEPORT switch if set to true.
  enable_ipv6: false 			       # Enable nginx IPv6 resolver
  extra_lua_path: "/opt/apisix/third/?.lua"

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
    - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  port_admin: 9180
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092
nginx_config:
  error_log_level: "warn"

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://etcd:2379"     # multiple etcd address
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

plugin_attr:
  prometheus:
    export_uri: /apigateway/prometheus/metrics
    metric_prefix: apigateway_
    enable_export_server: true
    export_addr:
      ip: "0.0.0.0"
      port: 9091
plugins:                          # plugin list
  - api-breaker
  - authz-keycloak
                                  # receive http request with proxy protocol
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - echo
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - ua-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  - node-status
  - openid-connect
  - authz-casbin
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - traffic-split
  - gzip
  - real-ip
  - example-plugin
stream_plugins:
  - mqtt-proxy
  - ip-restriction
  - limit-conn

**Comment by rpei2022** [comment]
@soulbird @tokers  It seems that there is a bug, the /usr/local/apisix/apisix/cli/ops.lua fails to write extra_lua_path into the nginx.conf

**Comment by rpei2022** [comment]
@tokers @tzssangglass  

**The following is part of the content of docker-compose.yml, I put custom plugin files in ./plugins directory, and mount it to the directory /opt/third/apisix/plugins int the container.**
services:
  apisix:
    image: apache/apisix:2.13.1
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      **- ./plugins:/opt/third/apisix/plugins**
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_conf/nginx.conf:/usr/local/apisix/conf/nginx.conf:rw
The following is part of the content of conf/nginx.conf, after I manually added the /opt/third/?.lua in the front of the lua_package_path, my custom plugins could be loaded successfully, otherwise, my custom plugin could not be loaded.
http {
    # put extra_lua_path in front of the builtin path
    # so user can override the source code
    lua_package_path  "**/opt/third/?.lua**;$prefix/deps/share/lua/5.1/?.lua;$prefix/deps/share/lua/5.1/?/init.lua;/usr/local/apisix/?.lua;/usr/local/apisix/?/init.lua;;./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua;";
    lua_package_cpath "$prefix/deps/lib64/lua/5.1/?.so;$prefix/deps/lib/lua/5.1/?.so;;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/openresty/luajit/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so;";

**Comment by Chever-John** [comment]
@LancCJ Hi, can you offer the `logs/error.logs`?

**Comment by LancCJ** [comment]
> @LancCJ Hi, can you offer the `logs/error.logs`?

i see error.log,found path is not right.then i add 'apisix/plugins' now it works.https://files.slack.com/files-pri/T4S1WH2J3-F03GA115VST/image.png

**Comment by Chever-John** [comment]
@LancCJ Happy for you

however, I want to know what makes your first fail? a misleading article, or something else?

**Comment by LancCJ** [comment]
> 

I didn't pay attention to the example.the custom plug-in path is ignored if the hint is not too obvious

<img width="858" alt="image" src="https://user-images.githubusercontent.com/2968042/170024221-e41b2fff-6814-492e-beea-1b4d24870141.png">

**Comment by tokers** [comment]
Right, I think the directory hierarchy is ignore-prone, we can add a Docusuarus admonition (e.g., a tip) to highlight it.

**Comment by Chever-John** [comment]
@LancCJ It seems to be the case, and this piece does seem a bit confusing. Would you be willing to improve this section please? Just need to have the ability to write markdown documents~

**Comment by Chever-John** [comment]
@LancCJ Proud of you~
Looking forward to your PR!
