### ISSUE TITLE
docs:  apisix call etcd Architecture and mutual flow

### ISSUE THREAD

**Issue by PGDream** [apache/apisix#6744]
### Current State

temporary no doc

### Desired State

1. `APISIX` call etcd Architecture
2. `APISIX` call etcd mutual flow
3. `APISIX` boot Architecture image

**Comment by zhendongcmss** [comment]
where do those docs will place ?

**Comment by juzhiyuan** [comment]
👋 @PGDream, please provide details information. 

You can use Chinese to describe this question in detail and use https://fanyi.baidu.com/ to translate.
