### ISSUE TITLE
help request: how to handle with plugins global configuration?

### ISSUE THREAD

**Issue by gy09535** [apache/apisix#6753]
### User Case
- For some plugins such as authorization kinds of plugins, We just has one identity server address, So we can not config it in pre route with same address. Should we have the global place to set the config and change it flexibly? What is the best practices?

### Environment

- APISIX version (run `apisix version`): 2.5
- Operating system (run `uname -a`): alpine
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by liangliang4ward** [comment]
you can ref docs: https://apisix.apache.org/zh/docs/apisix/architecture-design/global-rule

**Comment by gy09535** [comment]
> you can ref docs: https://apisix.apache.org/zh/docs/apisix/architecture-design/global-rule

thanks
