### ISSUE TITLE
help request: An exception occurred when limit_count was used to control traffic limiting on multiple nodes. 

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#6760]
### Description

We want to individually control the maximum number of times each consumer calls the Router per minute.Currently, we use limit-count and key-auth to limit , and the policy is redis-cluster:
 `"key": "consumer_name",
 "policy": "redis-cluster",
  "scope": "route_id"`

Our Apisix has two nodes, and when the two nodes are requested separately, we find that each node generates a limit_count key in Redis, causing each node to perform traffic limiting separately instead of two nodes sharing a configuration, as shown below:

plugin-limit-count-by-client8bb09e5e110845f39a000391668e3e80route_idroute&service&consumer281088&216326&3

plugin-limit-count-by-client8bb09e5e110845f39a000391668e3e80route_idroute&service&consumer281088&216326&1

When the key is concatenated with the last part '&consumer', we found the consumer of the two nodes is  different, one is '&3' and another is '&1' ,but we use the same consumer request through key-auth.Why is the concatenation of '&consumer' different, and how can you control the two nodes to share a limit_count configuration instead of generating two keys.

### Environment

- APISIX version (2.11.0):
- OpenResty / Nginx version (1.19.9.1):
- etcd version, if relevant (3.4.0):
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Chever-John** [comment]
I noticed that there is a bug fix for the "limit-count" plugin in 2.12 and newer versions, check if it is a version issue?
