### ISSUE TITLE
docs: failed to install APISIX according to the documentation

### ISSUE THREAD

**Issue by cheverjonathan** [apache/apisix#6762]
### Current State

I followed the "[installation via source release package](https://apisix.apache.org/docs/apisix/next/how-to-build#installation-via-source-release-package)" method in the "[how to build.md](https://apisix.apache.org/docs/apisix/next/how-to-build)" documentation to install APSIX, but it failed in the end.

I finally managed to install APISIX according to this [document](https://apisix.apache.org/docs/apisix/install-dependencies).

So I would suggest adding an "[Install dependencies](https://apisix.apache.org/docs/apisix/2.10/how-to-build#step-1-install-dependencies)" section to the latest how-to-build [documentation](https://apisix.apache.org/docs/apisix/how-to-build). Just like in this [link](https://apisix.apache.org/docs/apisix/2.10/how-to-build#step-1-install-dependencies). 

Otherwise, if I follow the latest how-to-build documentation (meaning if I want to install APISIX according to the "installation via source release package" method), I will still fail.

### Desired State

It will work if I want to install APISIX according to the "installation via source release package" [method](https://apisix.apache.org/docs/apisix/how-to-build#installation-via-source-release-package).

**Comment by tokers** [comment]
@cheverjonathan What are the specific failures that you met? I found we already have the dependencies installation steps in the [installation via source release package](https://apisix.apache.org/docs/apisix/next/how-to-build#installation-via-source-release-package).

**Comment by cheverjonathan** [comment]
Sorry, I didn't find this part when I had the problem.
I will close this issue.
