### ISSUE TITLE
docs: update how-to-build.md etcd version to 3.5.2

### ISSUE THREAD

**Issue by tiankonglan** [apache/apisix#6767]
### Current State

Step 2: Install etcd
ETCD_VERSION='3.4.13'

### Desired State

ETCD_VERSION='3.5.2'

when our team upgrade apisix2.7  to apisix2.10 on the product environment, we use etcd3.5.0. after run serveral days, we found the etcd  has panic,  the error message is "failed to unmarshal mvccpb.KeyValue",   the bug report issue: https://github.com/etcd-io/etcd/issues/12845, fix pr: https://github.com/etcd-io/etcd/pull/13505, the method is upgrade the etcd to 3.5.2; then we upgrade ectd to 3.5.2, from now have twenty days;  so I consider  ETCD_VERSION to 3.5.2 is suitable. I have commit a pull request for this issue.

**Comment by leslie-tsang** [comment]
Hello there, there is a [PR](https://github.com/apache/apisix/pull/6755) have take care about this issue. :)

> so I consider ETCD_VERSION to 3.5.2 is suitable

Please refer to [6755#issuecomment-1082810057](https://github.com/apache/apisix/pull/6755#issuecomment-1082810057)

> > This release is no longer recommended for production. Please use v3.4 minor until v3.5.3 is released. Read more in https://github.com/etcd-io/etcd/tree/main/CHANGELOG.
> 
> See https://github.com/etcd-io/etcd/releases/tag/v3.5.2 for details.

**Comment by tiankonglan** [comment]
get it.    thanks,  let us know the ectd 3.5.2 is not the  stable version.
