### ISSUE TITLE
configuration feature

### ISSUE THREAD

**Issue by ysk229** [apache/apisix#6777]
### Description

hello
Is there any plan to have a backup configuration feature similar to konga, and if so, how long is the plan to have it? Thanks!

**Comment by tzssangglass** [comment]
The data of APISIX all stored in etcd, and you can read [the doc of etcd](https://etcd.io/docs/v3.3/op-guide/recovery/) for details of snapshotting and recovery.

I will close this issue as it is a known issue and has no value.

ref: #978
