### ISSUE TITLE
bug:  failed to find upstream by id:

### ISSUE THREAD

**Issue by tirelibirefe** [apache/apisix#6781]
### Current Behavior

Hello,
Here my route and upstream configs. If I didn't configure them wrong, the route cannot find upstream.

Regards

### Expected Behavior

I expect the route finds the upstream.

### Error Logs

![image](https://user-images.githubusercontent.com/45227339/161264163-ae58d81b-7840-43b7-8fc1-975addce5b8e.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/45227339/161263034-5c47cbd3-a417-4141-9acc-80fc3df8740e.png)
![image](https://user-images.githubusercontent.com/45227339/161263325-c033c876-52dd-4896-98ff-b4f922037777.png)
![image](https://user-images.githubusercontent.com/45227339/161263977-cf273379-6362-47ba-aa38-151f75f33cc1.png)

### Environment

- APISIX version (run `apisix version`):  Cannot find, the latest one, I  installed yesterday.
- Operating system (run `uname -a`): EKS Kubernetes 1.21 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): probably last one, I installed yesterday.
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): probably last one, I installed yesterday.
- APISIX Dashboard version, if relevant: 2.10 (it's shown there)
- Plugin runner version, for issues related to plugin runners: no idea, cannot see, probably last one, I installed yesterday.
- LuaRocks version, for installation issues (run `luarocks --version`): no idea, cannot see, probably last one, I installed yesterday.

**Comment by tzssangglass** [comment]
1. For error logs, please provide text rather than images
2. you need text to describe the reproduction steps, it's hard for me to guess what you want to say from the pictures, pictures are best as supporting statements.
3. it is easy to check the version, let's check the APISIX version first.

**Comment by tirelibirefe** [comment]
Hello @tzssangglass Sorry for images, I guessed it's clear. I defined the problem [here](https://github.com/apache/apisix/discussions/6782 )
My apisix version is 2.13
I think my description is enough to reproduce, if it's not, pls let me know; I can provide further details.

Thanks & Regards

**Comment by tzssangglass** [comment]
> I defined the problem [here](https://github.com/apache/apisix/discussions/6782)

discussion and this issue was the same problem? If so, let's choose to track this problem in the issue.
