### ISSUE TITLE
bug: openid-connect plugin doesn't redirect after logout

### ISSUE THREAD

**Issue by mehmetcuneyit** [apache/apisix#6791]
### Current Behavior

I would like to integrate APISIX gateway with [auth0](https://auth0.com) using [openid-connect](https://apisix.apache.org/docs/apisix/plugins/openid-connect/) plugin.
After a request is sent to `/logout`, the session is invalidated on the server side and `session=` field in the cookie set to empty on the client side. In addition to that a request needs be sent to auth0's logout endpoint ( see [here](https://auth0.com/docs/authenticate/login/logout/log-users-out-of-auth0) ). So, `post_logout_redirect_uri` field is configured in the plugin to make logout request to the auth0 endpoint, but it doesn't redirect. 

### Expected Behavior

When `post_logout_redirect_uri` is configured in openid-connect plugin, it should redirect user to the given URI after a request sent to the `/logout` endpoint on the gateway. 

### Error Logs

No errors printed to `/usr/local/apisix/logs/error.log`

### Steps to Reproduce

1. Run APISIX via [the Docker deployment](https://github.com/apache/apisix-docker)
```
cd example
docker-compose -p docker-apisix up -d
```

2. Create a Route in the dashboard
3. Enable/Configure openid-connect plugin (Scope: global). 
```
{
  "access_token_in_authorization_header": true,
  "bearer_only": false,
  "client_id": "{client_id}",
  "client_secret": "{client_secret}",
  "disable": false,
  "discovery": "https://{domain}.us.auth0.com/.well-known/openid-configuration",
  "introspection_endpoint_auth_method": "client_secret_post",  
  "realm": "master",
  "redirect_uri": "http://127.0.0.1:9080/",
  "scope": "openid profile",
  "post_logout_redirect_uri": "https://{domain}.us.auth0.com/v2/logout?client_id={client_id}&returnTo=http://127.0.0.1:9080/app",
}
```
4. Authenticate user by going to any defined route on the gateway ( e.g. `/protected` ). It will redirect user to the auth0 login page .
5. Go to `/logout`, no redirection happens.

![Screenshot from 2022-04-04 12-41-29](https://user-images.githubusercontent.com/39027858/161528057-af914a5f-1953-4f97-8455-d4d7c5596800.jpg)

### Environment

- APISIX version (run `apisix version`): **2.13.0**
- Operating system (run `uname -a`): the apisix docker image
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): the apisix docker image
- APISIX Dashboard version, if relevant: **2.10.1**
- Plugin runner version, for issues related to plugin runners: -
- LuaRocks version, for installation issues (run `luarocks --version`): -

**Comment by spacewander** [comment]
@starsz
Could you take a look? Thanks!

**Comment by starsz** [comment]
> @starsz Could you take a look? Thanks!

Looks strange, let me have a check.

**Comment by starsz** [comment]
Hi @mehmetcuneyit.
Thanks for the report, I found the reason.
1. Keycloak openid-configuration will provide an `end_session_endpoint` but Auth0 wouldn't.

Keycloak: 
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/25628854/161886814-72b03edf-2ccd-4c4b-a79a-6459c8d9a343.png">

Auth0 wouldn't provide ·end_session_endpoint`.I think we need to fix it to support the Auth0.

**Comment by mehmetcuneyit** [comment]
Thanks @starsz . auth0 is not the only one that doesn't provide `end_session_endpoint` as it is not required according to [openid specs](https://openid.net/specs/openid-connect-session-1_0.html) .  Also, Google OAuth2 doesn't provide it ( see [Google Oauth2 OpenId Discovery](https://accounts.google.com/.well-known/openid-configuration) ) . 

As a general solution, it would be good to introduce `discovery_metadata` field in the plugin. The plugin merges the discovery endpoints with configured endpoints inside `discovery_metadata` field before saving it to the cache. Simply, `discovery_metadata` option 
- allows to override endpoints defined in the discovery 
- allows to add new endpoints.
e.g.
```
{
...
  "discovery": "https://{domain}.us.auth0.com/.well-known/openid-configuration",
  "discovery_metadata": {
        "end_session_endpoint": "https://{domain}.us.auth0.com/v2/logout?client_id={client_id}&returnTo=http://127.0.0.1:9080/app"
  }
...
}
```

**Comment by starsz** [comment]
> Thanks @starsz . auth0 is not the only one that doesn't provide `end_session_endpoint` as it is not required according to [openid specs](https://openid.net/specs/openid-connect-session-1_0.html) . Also, Google OAuth2 doesn't provide it ( see [Google Oauth2 OpenId Discovery](https://accounts.google.com/.well-known/openid-configuration) ) .
> 
> As a general solution, it would be good to introduce `discovery_metadata` field in the plugin. The plugin merges the discovery endpoints with configured endpoints inside `discovery_metadata` field before saving it to the cache. Simply, `discovery_metadata` option
> 
> * allows to override endpoints defined in the discovery
> * allows to add new endpoints.
>   e.g.
> 
> ```
> {
> ...
>   "discovery": "https://{domain}.us.auth0.com/.well-known/openid-configuration",
>   "discovery_metadata": {
>         "end_session_endpoint": "https://{domain}.us.auth0.com/v2/logout?client_id={client_id}&returnTo=http://127.0.0.1:9080/app"
>   }
> ...
> }
> ```

Cool. That's a nice idea.

**Comment by ecoupal-believe** [comment]
I have the same problem with Cognito: it does not provide end_session_endpoint. Is there news on this ticket ?

**Comment by starsz** [comment]
> I have the same problem with Cognito: it does not provide end_session_endpoint. Is there news on this ticket?

It doesn't support "discovery_metadata" yet.
@ecoupal-believe Do you want to implement this feature?

**Comment by Revolyssup** [comment]
Last tracked - https://github.com/apache/apisix/pull/9949

**Comment by kayx23** [comment]
There was a new doc about integrating APISIX gateway with auth0 using openid-connect plugin: https://docs.api7.ai/apisix/how-to-guide/authentication/set-up-sso-with-auth0

Please see if anything's helpful

**Comment by mehmetcuneyit** [comment]
@starsz  @ecoupal-believe @Revolyssup I was wondering if the team has eta for this or any concerns with the solution ?

**Comment by luoluoyuyu** [comment]
hi @mehmetcuneyit 
For providing user logout it is necessary to provide `end_session_enpoint`, you can refer to this standard https://openid.net/specs/openid-connect-rpinitiated-1_0.html#OPMetadata

**Comment by luoluoyuyu** [comment]
hi @Revolyssup @ecoupal-believe @Sn0rt @mehmetcuneyit 
PR(#8941) is adding the ability to customize the logout uri without finding the service definition `end_session_enpoint`, this is done using the `redirect_after_logout_uri` configuration. In the OpenID connect standard documentation, I didn't find any description of redirect_after_logout_uri, which is actually defined in https://github.com/zmartzone/lua-resty-openidc. I don't think using this configuration will solve the problem, but the core of the problem is still in the `redirect_after_logout_uri` configuration, which is defined in https://github.com/zmartzone/lua-resty-openidc. The core of the solution is `end_session_enpoint`, such as providing `end_session_enpoint` configuration in the discovery service provided by Google openID. Even if you use `redirect_after_logout_uri`, it won't logout correctly, it just redirects to `redirect_after_logout_uri`.

As you can see in the code, if `redirect_after_logout_uri` exists then `redirect_after_logout_uri` is used. but they redirect with the same parameters.
```lua
    local uri
    if opts.redirect_after_logout_uri then
      uri = opts.redirect_after_logout_uri
    else
      uri = opts.discovery.end_session_endpoint
    end
    local params = {}
    if (opts.redirect_after_logout_with_id_token_hint or not opts.redirect_after_logout_uri) and session_token then
      params["id_token_hint"] = session_token
    end
    if opts.post_logout_redirect_uri then
      params["post_logout_redirect_uri"] = opts.post_logout_redirect_uri
    end
    return ngx.redirect(openidc_combine_uri(uri, params))
```

**Comment by luoluoyuyu** [comment]
Instead of exposing the `redirect_after_logout_uri` configuration to the user, I think we should determine if the openID service supports `end_session_enpoint`, and if not, use redirect_after_logout_uri for the logout redirect.

**Comment by luoluoyuyu** [comment]
Hi @mehmetcuneyit @Sn0rt  @monkeyDluffy6017 
The solution to the problem is to use redirect_after_logout_uri for redirection after logout if there is no end_session_endpoint in the discovery metadata, but note that since redirect_after_logout_uri is not defined in the schema, it can only be configured in the rewrite phase. If you set the value of redirect_after_logout_uri in the check_schema phase, you will get an error when restarting apisix.
