### ISSUE TITLE
help request: upstream node has been specified, cannot be set repeatedly and 404 caused by farword to wrong backend

### ISSUE THREAD

**Issue by mcdullbloom** [apache/apisix#6799]
### Description

I also got the warning "upstream node has been specified, cannot be set repeatedly" and several 404 response as well(the qps is about 800) . I added some logs in set_by_route and udp-logger and found that apisix forward the request to wrong backend upstream node. I susspect that the api_ctx is polluted but I have no idea why this happen.

PS：we do not use the plugin "traffic-split"

### Environment

apisix version (cmd: apisix version): 2.4
OS: (cmd: uname -a) linux 3.10.0-693.el7.x86_64 CentOS Linux release 7.4.1708 (Core)
OpenResty / Nginx version: (cmd: nginx -V or openresty -V) nginx version: openresty/1.19.3.1

**Comment by tokers** [comment]
@mcdullbloom Could you provide more details? Especially for the steps. Thanks!

**Comment by mcdullbloom** [comment]
We just request apisix normally. After I print the log, I find the upstream id in `api_ctx.matched_route.upstream_id` is not the same with `api_ctx.upstream_conf.upstream_id` . ( The qps is 100K for the apisix server, most of the request is ok with 200.We get 1 or 2  `404 `  every 10 minutes for a single domain name. So strange it is！)
```
function _M.http_access_phase()
    local ngx_ctx = ngx.ctx
    -- always fetch table from the table pool, we don't need a reused api_ctx
    local api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
    if api_ctx.upstream_conf ~= nil then
        api_ctx.upstream_conf = nil
    end
```
After I  set the  `api_ctx.upstream_conf` to nil，we get the same upstream_id now. But the upstream doesn't have the node and it is in other upstream.

**Comment by soulbird** [comment]
I will take a look

**Comment by spacewander** [comment]
@mcdullbloom 
Is it possible to reproduce the problem with the latest 2.13 release?
The 2.4 is released for more than 1 year and we have applied many bugfixes after it.

**Comment by mcdullbloom** [comment]
> @mcdullbloom Is it possible to reproduce the problem with the latest 2.13 release? The 2.4 is released for more than 1 year and we have applied many bugfixes after it.

@spacewander we can't change from 2.4 to 2.13 immediately for it's our production env.

By the way，shouldn't the `api_ctx` be nil at the beginning of the `http_access_phase` ? `core.tablepool.fetch` may use a exsit table
```
function _M.http_access_phase()
    local ngx_ctx = ngx.ctx
    -- always fetch table from the table pool, we don't need a reused api_ctx
    local api_ctx = core.tablepool.fetch("api_ctx", 0, 32)
```

**Comment by spacewander** [comment]
You can try to reproduce it with 2.13 under a non-production env.

**Comment by spacewander** [comment]
Tablepool will clear the table during release, see https://github.com/openresty/lua-tablepool#release.

I am too busy to discuss the detail if it can only be reproduced with a version released over a year.

**Comment by mcdullbloom** [comment]
thank you all.
