### ISSUE TITLE
feat: As a user, I want to let a Route to be bound to severial Services, so that a single Route could be able to serve different hosts bounded to different services

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#6805]
### Description

for example, i have 2 services with different hosts,like serviceA->hostA and serviceB->hostB
my routerA could be bound to serviceA and serviceB at the same time. the two services may have different plugins dicieded by which host was used.

**Comment by fatihbm** [comment]
If I look at our case, that wouldn't be a very good idea for us. 
That is, in this case, it would be necessary to define nearly three hundred services under a route. 
Even with the priority or the services we reserve according to the rules, this number will be tons.  
In the past, we have experienced these problems a lot with well-known commercial box products.  
Instead of changing the route, maybe an optional upper layer can be created and abstracted.
We loved the current radix tree design I hope you like it too :)

**Comment by tokers** [comment]
> 
Description
for example, i have 2 services with different hosts,like serviceA->hostA and serviceB->hostB
my routerA could be bound to serviceA and serviceB at the same time. the two services may have different plugins dicieded by which host was used.

In terms of this point, why not just create two routes?

**Comment by qihaiyan** [comment]
> 

because the two routes have same attributes like url, name, desc ... etc

**Comment by tzssangglass** [comment]
> the two services may have different plugins dicieded by which host was used.

I think what you really need is to select the set of plugins based on hosts. In this case, two routes are neede.

> because the two routes have same attributes like url, name, desc ... etc

These are not reasons to merge routes. Routing means: distinguishing requests based on different conditions and performing differentiated processing. In your scenario, hosts being different is a strong reason to need more than two routes.

**Comment by qihaiyan** [comment]
![image](https://user-images.githubusercontent.com/5896784/165033186-126b0623-eaf1-45b7-b578-025684bddfa4.png)


as the above diagram , if i have 20 routes, like you said, i have to create the 20 routes duplicatly, event if they could reuse the configuration in the service(with same plugins) they belong to.
if the 20 routes could belong to different service, i just need to create 2 different service, rather than another 20 routes.

refer to the document: [Service](https://apisix.apache.org/docs/apisix/architecture-design/service )
`As shown, different Routes could be bound to the same Service. This reduces redundancy as these bounded Routes will have the same [Upstream](https://apisix.apache.org/docs/apisix/architecture-design/upstream) and [Plugin](https://apisix.apache.org/docs/apisix/architecture-design/plugin) configurations.` @tzssangglass

**Comment by tzssangglass** [comment]
> i have to create the 20 routes duplicatly, event if they could reuse the configuration in the service(with same plugins) they belong to.

for this, you can use plugin-config to reuse the same plugin config, see : https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/plugin-config.md

> if the 20 routes could belong to different service, i just need to create 2 different service, rather than another 20 routes.

As I said above, binding the same plugin configuration to different services is not a reason to have route bind multiple services, it's putting the cart before the horse. service is an abstraction of route.

**Comment by tokers** [comment]
Bind a route to multiple services might cause side effects such as the plugin conflicts (the priority problem), I'm afraid it will make the design chaotic.

**Comment by qihaiyan** [comment]
Seems it's not a suitable design, i'll close the issue.
