### ISSUE TITLE
docs: picture with Chinese in English Documentation

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#6809]
### Current State

1. Visit https://apisix.apache.org/docs/apisix/external-plugin in the English version.
2. The architecture diagram is in Chinese.
3. Note: The website will redirect to the Chinese version if you use Chinese as the browser's default language. Please click on Top-Right Language Switcher to change the language.

![image](https://user-images.githubusercontent.com/2106987/162400499-123fe117-2bdb-4b84-b29b-ec78431b07da.png)

### Desired State

The architecture diagram should be in English, too.

**Comment by juzhiyuan** [comment]
Just found that the latest unreleased from the master branch is using the English version.

https://apisix.apache.org/docs/apisix/next/external-plugin

**Comment by juzhiyuan** [comment]
It is V2.13's Documentation site https://apisix.apache.org/docs/apisix/external-plugin/. Also, it's the default documentation for visitors when they read the `apache/apisix` project docs.

Because people will read the Chinese doc until we release 2.14 in the future, I would prefer to invite contributors to fix this issue for v2.13. 

But the confusing point is that we have to update the `release/2.13` branch if we fix this issue. Then do we need to release a new version by following the ASF's policy?

**Comment by wu-sheng** [comment]
Why do you have to run a release for a doc page? The commit ID is an option to avoid tag.

**Comment by juzhiyuan** [comment]
Hi, it is due to the Apache APISIX Website's building logic. Currently, the Apache APISIX Website will do those things:

1. Run a script to clone projects' repo in CI;
2. Read markdown files by switching each repo's branch;
3. Generate web pages for each branch.
4. Use Cron to run CI daily.

I noticed Apache SkyWalking is using commit id https://github.com/apache/skywalking-website/blob/master/data/docs.yml#L36. We could update the website's configuration files when we needed to build docs. Also, cc @SkyeYoung @bzp2010 

Back to this issue, what confused me is if we update the `release/2.13` branch, do we need to have an official release by voting?

**Comment by wu-sheng** [comment]
> Back to this issue, what confused me is if we update the release/2.13 branch, do we need to have an official release by voting?

It is just a branch. How APISIX community wants to manage it, or what is branch creation rule, that is PMC decision only. Only a new tag is concerned from the foundation perspective.

**Comment by SkyeYoung** [comment]
@juzhiyuan One question I've been thinking about is why not have the latest release branch be the default branch for the current document?
However, this creates a problem. When an APISIX version is released, the documentation work that was on master needs to be moved to the branch of the latest release. And the documentation work for the next release should be done on the master branch.

**Comment by spacewander** [comment]
> It is V2.13's Documentation site [apisix.apache.org/docs/apisix/external-plugin](https://apisix.apache.org/docs/apisix/external-plugin/). Also, it's the default documentation for visitors when they read the `apache/apisix` project docs.
> 
> Because people will read the English doc with Chinese content until we release 2.14 in the future, I would prefer to invite contributors to fix this issue for v2.13. But the confusing point is that we have to update the `release/2.13` branch if we fix this issue. Then do we need to release a new version by following the ASF's policy? cc @spacewander @wu-sheng

You can simply backport it. We have done this before: https://github.com/apache/apisix/pull/4671

**Comment by Ajay-singh1** [comment]
I can't see any Chinese text!

**Comment by SkyeYoung** [comment]
@Ajay-singh1 Hi, you can help the community improve this document 😸

**Comment by kayx23** [comment]
![image](https://github.com/apache/apisix/assets/39619599/e98a3e3b-9466-48ca-8ac1-ed5c6b918b77)

Seems to be addressed. Both docs used the English version now 😂
