### ISSUE TITLE
Proposal: Questions about the completion details of the Apache APISIX Introduce a Storage abstraction project

### ISSUE THREAD

**Issue by isHuangXin** [apache/apisix#6823]
### Description
Hello, I am a student major in computer science in Huazhong University of Science and Technology (华中科技大学). I want to apply for this project in GSOC 2022, but there are still many questions confusing me, hope to get completion details of this project.

**Background:**
1. Some plugins require storing data. For example, [limit-count](https://apisix.apache.org/docs/apisix/plugins/limit-count/) needs to keep track of originators of requests to limit how many requests the same client can send.

2. The plugin provides several data stores: local, Redis single node, and Redis cluster.

3. Now, other plugins that need to store data would also need to provide such configuration. Moreover, what if users want to store the data in MongoDB, Hazelcast, or in a plain SQL database?

Tasks:
- Introduce a Storage abstraction, on the same level as Upstream
- Create Storage concretions for local, Redis single node, and Redis cluster
- Migrate the limit-count plugin to use this abstraction
- If time allows, create a new plugin that uses this abstraction
- It time allows, create a new Storage implementation

**Questions:**

1. Introduce a Storage abstraction, on the same level as Upstream
     Which plugin is this abstract storage for? And what information is stored?

2.  Introduce a Storage abstraction, on the same level as Upstream that means 
     Abstract the limit-count-redis.lua and limit-count-redis-cluster.lua that the limit-count plugin has completed, and let limit-count inherit an abstract method that stores local, redis single, and redis cluster at the same time?

3. About background 3 Now, other plugins that need to store data would also need to provide such configuration. Moreover, what if users want to store the data in MongoDB, Hazelcast, or in a plain SQL database?
    Do I need to implement an abstract storage class for users to store data in MongoDB, Hazelcast, or in a plain SQL database?

**Comment by tokers** [comment]
@isHuangXin The case you mentioned is very vertical (rate-limiting), so we don't support other storage solutions since the performance and overheads. Note we need more real cases to decide if we really should do the things you proposed.

**Comment by moonming** [comment]
Apache APISIX does need an abstract storage layer, but the redis used in limit-rate is not a suitable example.
We can consider abstracting etcd as a storage layer, in fact, some people in the community already do this. Replace etcd with redis or mysql, etc.

**Comment by yangzhen0512** [comment]
> 

Is there any example link? Thanks.
