### ISSUE TITLE
help request:regex pattern  router

### ISSUE THREAD

**Issue by wjkhappy14** [apache/apisix#6828]
### Description

i want to use regex expression  ^[A-Z0-9]([-!#$%&'.*+/=?^`{}|~\w])*(?<=[A-Z0-9])$       match  some urls  ,  not rewrite the  url 

how to   ? i  can not get any help 
like nginx :

location  ~ ^/(.+)\.3gp\.zip$
{
#######
}

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@wjkhappy14 Please see https://github.com/api7/lua-resty-expr and the `vars` field in [Route](https://apisix.apache.org/docs/apisix/architecture-design/route/).

**Comment by wjkhappy14** [comment]
thks

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this.
