### ISSUE TITLE
bug: k8s service discovery error: not found environment variable KUBERNETES_SERVICE_HOST

### ISSUE THREAD

**Issue by spinachomes** [apache/apisix#6830]
### Current Behavior

k8s discovery can't get KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT from ENV

but in pod I can echo KUBERNETES_SERVICE_HOST var.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/24352696/162905835-7592cf38-cab2-4895-b1ec-a8a0dec9ccf2.png">

### Error Logs

2022/04/12 07:22:00 [error] 48#48: init_worker_by_lua error: /usr/local/apisix/apisix/discovery/kubernetes/init.lua:342: not found environment variable KUBERNETES_SERVICE_HOST
stack traceback:
        [C]: in function 'error'
        /usr/local/apisix/apisix/discovery/kubernetes/init.lua:342: in function 'init_worker'
        /usr/local/apisix/apisix/discovery/init.lua:35: in function 'init_worker'
        /usr/local/apisix/apisix/init.lua:109: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

### Steps to Reproduce

1.install apisix use helm [apisix-helm-chart](https://github.com/apache/apisix-helm-chart/blob/master/docs/en/latest/apisix.md)
2.add discovery:kubernetes: { } in apisix configmap
3.k logs -f po

### Environment

- APISIX version (run `apisix version`):2.13.0
- Operating system (run `uname -a`):Linux hecs-x-large-4-linux-20200603165605 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
> @spinachomes By default, APISIX doesn't recognize extra environment variables, please add this env to https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L172.

By the way, if this way helps you to resolve the problem, could you also help to optimize the doc of kubernetes discovery?

**Comment by spacewander** [comment]
We can inject the env variable when k8s service discovery is enabled?
https://github.com/apache/apisix/blob/b2184d85e12b8d56382e80099d189b454dd33e56/apisix/cli/ops.lua#L640

**Comment by zhixiongdu027** [comment]
> We can inject the env variable when k8s service discovery is enabled?
> https://github.com/apache/apisix/blob/b2184d85e12b8d56382e80099d189b454dd33e56/apisix/cli/ops.lua#L640


maybe i can get it done this weekend

**Comment by spinachomes** [comment]
> optimize

I will try

**Comment by spinachomes** [comment]
> > @spinachomes By default, APISIX doesn't recognize extra environment variables, please add this env to https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L172.
> 
> By the way, if this way helps you to resolve the problem, could you also help to optimize the doc of kubernetes discovery?

thanks, I will try

**Comment by zhixiongdu027** [comment]
> > We can inject the env variable when k8s service discovery is enabled?
> > https://github.com/apache/apisix/blob/b2184d85e12b8d56382e80099d189b454dd33e56/apisix/cli/ops.lua#L640
> 
> maybe i can get it done this weekend

Sorry, I received a temporary assignment from my boss and I need to take up weekend time.
So this work may be delayed for a few days, maybe you can cancel the assign first

@spacewander
