### ISSUE TITLE
docs: modify the Chinese version docs.

### ISSUE THREAD

**Issue by hf400159** [apache/apisix#6833]
### Current State

@navendu-pottekkat Navendu-pottekkat has reconstructed the English version of the docs, so the Chinese version of the docs also needs to be reconstructed. Document versions should be consistent and not significantly different to avoid confusion to users.
[6824](https://github.com/apache/apisix/pull/6824)
[6775](https://github.com/apache/apisix/pull/6775)
[6763](https://github.com/apache/apisix/pull/6763)

### Desired State

Reconstruct the Chinese version of the document.

**Comment by guoqqqi** [comment]
Hi, @Si-ege @hanzhenfang @juxianzheng Do you have time to help complete these questions?

**Comment by hf400159** [comment]
[6763](https://github.com/apache/apisix/pull/6763) done.
