### ISSUE TITLE
feat: Suggest that access-control-allow-origin in response header showing just as configured

### ISSUE THREAD

**Issue by Yullin** [apache/apisix#6835]
### Description

Sorry for my poor english.
In CORS plugin, Configured as follow:
{
  "cors": {
    "max_age": 5,
    "allow_methods": "GET,POST",
    "allow_credential": false,
    "allow_origins": "http://a.test.com,http://b.test.com,http://c.test.com",
    "allow_headers": "*",
    "expose_headers": "*"
  }
}
It's ok when client access apisix directly, but there will be a problem when CDN cache is in front of apisix.
Response header is cached by CDN, It will be blocked when you switch to b.test.com from a.test.com

**Comment by spacewander** [comment]
You should configure the domain name as the cache key in CDN, so the response from a.test.com won't be used with b.test.com
