### ISSUE TITLE
help request: apisix gateway supports intranet access to all interfaces, and Internet HTTPS access to specified interfaces

### ISSUE THREAD

**Issue by XW512** [apache/apisix#6840]
### Description

Now we want to use the apisik gateway to support the intranet to access all interfaces, and the Internet HTTPS to access the specified interfaces. I see the configuration file config default Yaml can support HTTPS port access, but such access should be able to access all interfaces. If you want to limit it, how to deal with it? I want to add an nginx in front to limit URL access

### Environment

- APISIX version (run `apisix version`): 2.13.0
- Operating system (run `uname -a`): centOS7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1

**Comment by kwanhur** [comment]
You can specify `ip` `port` to partial interfaces while expose HTTPS, the same way to HTTP.

https://github.com/apache/apisix/blob/153f385f3516237aa6427127e014cbd850136980/conf/config-default.yaml#L132-L133

**Comment by tzssangglass** [comment]
You can create separate routes for http and https. In the route created for https, you can use the host and vars attributes to match specific https requests.

```
curl -i http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "host": "foo.com",
    "vars": [
        [
            "scheme",
            "==",
            "https"
        ]
    ]
}'
```

**Comment by XW512** [comment]
> You can create separate routes for http and https. In the route created for https, you can use the `host` and `vars` attributes to match specific https requests.
> 
> ```shell
> $ curl -i http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/hello",
>     "host": "foo.com",
>     "vars": [
>         [
>             "scheme",
>             "==",
>             "https"
>         ]
>     ]
> }'
> ```
> 
> This way, you can control the interfaces open under https.

OK,thank you very much,I will try it

**Comment by XW512** [comment]
> You can create separate routes for http and https. In the route created for https, you can use the `host` and `vars` attributes to match specific https requests.
> 
> ```shell
> $ curl -i http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/hello",
>     "host": "foo.com",
>     "vars": [
>         [
>             "scheme",
>             "==",
>             "https"
>         ]
>     ]
> }'
> ```
> 
> This way, you can control the interfaces open under https.

OK,I will try it

**Comment by XW512** [comment]
> You can specify `ip` `port` to partial interfaces while expose HTTPS, the same way to HTTP.
> 
> https://github.com/apache/apisix/blob/153f385f3516237aa6427127e014cbd850136980/conf/config-default.yaml#L132-L133

OK,thank you,I will see it and try it

**Comment by XW512** [comment]
> 
I tried your configuration, but I found that URLs without this configuration can also be accessed by HTTPS
