### ISSUE TITLE
zipkin  UDP protocol

### ISSUE THREAD

**Issue by ysk229** [apache/apisix#6841]
### Description

Hello!
See the control surface has zipkin plug-in, is it support UDP protocol, is it jaeger.thrift, port 6831 3832 respectively?

**Comment by kwanhur** [comment]
Is question that zipkin plugin support jaeger collector on port 6831 and codec thrift on port 3832 or not?

zipkin plugin usage see [here](https://apisix.apache.org/docs/apisix/plugins/zipkin).

**Comment by tzssangglass** [comment]
I did a quick review of the code and now zipkin uses the http : https://github.com/apache/apisix/blob/2518b18a7ba87e4e42204bb01924c0c8f79d7527/apisix/plugins/zipkin/reporter.lua#L116-L137
