### ISSUE TITLE
help request: collect APISIX community newbie contributor onboarding guide

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#6843]
## Backgroud

Many seeders in the APISIX community are interested in learning how to contribute to the project but are unfamiliar with GitHub workflow and APISIX project. The Apache APISIX developer community will grow stronger if a clear growth roadmap is provided.

On 4.13 we held an online community meeting to discuss the experiences of newbie contributor.

## What to do?

We hope to use the power of the community to accomplish some of the following issues:

- How to search info in GitHub
- How to play with GitHub Action (fork and CI)
- How to work with GitHub workflow
- A playground for APISIX (online or localized) 
- How to use test framework with GitHub Action CI

Here are some simple sample answers:

- Before using GitHub
	- Learn some Git directives, like clone, fetch, commit, push, pull, rebase
	- Learn how to collaborate on projects with GitHub, read GitHub flow

- Before playing with APISIX 
	- Read books about Lua, OpenResty, and even perl 

## How to participate?

If you are interested in the questions mentioned above, or if you have some experience, then you can write your answers to some of the questions under this issue.

## What this issue will eventually become?

We hope this issue will eventually result in a newbie onboarding document. This is a long and iterative process.

### Environment

no

**Comment by EmilyKeer** [comment]
Hi, there is a setup guide for the series of Apache APISIX student contributor workshops: https://tfzcfxawmk.feishu.cn/docs/doccnqwcWedkGoQ7pQARLL7JVXf
It contains some info you mentioned already: Git / Github workflow, how to install Apache APISIX, etc.
So for the "newbie onboarding document":
- We can use some parts from this setup guide;
- As someone managing the logistics for the contributor workshops, I am more than happy to help with the newbie onboarding document creation process. The students in the workshops can provide feedback too.

**Comment by kwanhur** [comment]
> How to work with GitHub workflow

- Here's good tutorial [Github Actions](https://docs.github.com/en/actions)
- Play them within own repo step by step

> How to use test framework with GitHub Action CI

1. Take some time to read the book [Programming OpenResty](https://openresty.gitbooks.io/programming-openresty/content/) again and again
2. Have a look at APISIX [test cases](https://github.com/apache/apisix/tree/master/t)

**Comment by juzhiyuan** [comment]
Glad to know this thread! We have a page to show all Good first issues, see https://apisix.apache.org/contribute/

also cc @Boburmirzo

**Comment by kwanhur** [comment]
To a beginner, make some docs enhancement like building guides, translation and fixing typo etc. I think it'll be a better way to make some contributions.

**Comment by tzssangglass** [comment]
If we had a page to organize some links related to APISIX, such as the Nginx official site, OpenResty related content.
But I doubt anyone would really be interested, because from my experience, if I want to find certain information, I search for it myself and don't rely on a big, comprehensive wiki that someone else has put together.
