### ISSUE TITLE
help request: plugin's control api return 404 when invoked

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#6844]
### Description

hello, I get confused when I use APISIX2.11。
first，we have servral apisix cluster,but just some of occurs the follow exception
let me describe it.
1.use two apisix（such as apisixA and apisixB） consist of a cluster,they are use same prefix in etcd，such as "/sit/apisix"

2.start apisixA and apisixB，then invoke plugin's contolAPI,such as  http://172.xx.xx.01:9090/v1/plugin/example-plugin/hello,when I first invoke in apisixA,it returns "world", then I invoke it in apisixB, reutrns 404

3. I find when I restart apisixA and apisixB, the first I invoked is always ok(such as apisixA)，the second I invoked is always 404(such as apisixB)，also when I again restart apisixA and apisixB，the first I invoked is always ok(such as apisixB)，the second I invoked is always 404(such as apisixA)

4. when I add log in apisix/control/router.lua fuction _M.match(uri)，I find "return router:dispatch(uri, match_opts)" the 
param "match_opts" in apisixB(unhealth) does not have plugin's control api information(such as server-info's api)，the health apisixA has have plugin's control api information

5.  when I add log in apisix/plugin.lua "function _M.load(config)" I find the health apisixA's param config is nil，but unhealth apisixB's param is {"createdIndex":8664,"key":"\/sit\/apisix\/plugins\/","modifiedIndex":83836}

I am confused of such thing, hope get some help in here , thanks

### Environment

- APISIX version (run `apisix version`):2.11
- Operating system (run `uname -a`):Linux 3.10.0-1160.36.2.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jujiale** [comment]
hello,
I find some change in apisix2.12 in apisix/plugin.lua it's function load(config) has some change in following
"ignore changes of /apisix/plugins/ (https://github.com/apache/apisix/pull/5558)"
commit is "https://github.com/apache/apisix/commit/30c902895b41327907fb007b1ee5e97e6079b6ba"

I follow the above change in apisix2.11 , the error seems resolved, I tried it ,seems ok, but I don't konw why

**Comment by jujiale** [comment]
I don't konw why this thing could occurs，because we have several of clusters, but only some of clusters has such thing

**Comment by tzssangglass** [comment]
> I follow the above change in apisix2.11 , the error seems resolved, I tried it ,seems ok, but I don't konw why

can you try with `2.13.0` version?

**Comment by jujiale** [comment]
> > I follow the above change in apisix2.11 , the error seems resolved, I tried it ,seems ok, but I don't konw why
> 
> this is supposed to be a known error, can you try with `2.13.0` version?

@tzssangglass thank you very mush for reply, I have tried it , 2.13.0 is ok. but I want to konw why this situation occured，because we have several of clusters, but just some of them has such situation.

**Comment by tzssangglass** [comment]
> @tzssangglass thank you very mush for reply, I have tried it , 2.13.0 is ok. but I want to konw why this situation occured，because we have several of clusters, but just some of them has such situation.

Each APISIX initializes the `/apisix/plugins/` directory in etcd during the initialization phase, and this behavior is sensed by the running APISIX instances, which then handle errors.

**Comment by jujiale** [comment]
> > @tzssangglass thank you very mush for reply, I have tried it , 2.13.0 is ok. but I want to konw why this situation occured，because we have several of clusters, but just some of them has such situation.
> 
> Each APISIX initializes the `/apisix/plugins/` directory in etcd during the initialization phase, and this behavior is sensed by the running APISIX instances, which then handle errors.

thanks very much
