### ISSUE TITLE
help request: etcd OOM due to frequent deployments

### ISSUE THREAD

**Issue by suninuni** [apache/apisix#6845]
### Description

The load of apisix-etcd deployed in the K8s cluster has been increasing, is this normal?

By rebuilding the etcd cluster, the memory dropped to 200Mi without any change for K8s cluster.

This phenomenon occurs in several of my frequently deployed clusters.

![image](https://user-images.githubusercontent.com/7345529/163396153-e5bb948d-55bf-4a03-9851-e9b6700f44b6.png)

![image](https://user-images.githubusercontent.com/7345529/163395541-063532f0-1cc2-4298-8070-10de45c72076.png)

### Environment

- APISIX version (run `apisix version`): 2.11
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX ingress version: 1.4.0

**Comment by tokers** [comment]
> due to frequent deployments

How to understand this?

By the way, could you also check if you enable the server-info plugin?

**Comment by suninuni** [comment]
> > due to frequent deployments
> 
> How to understand this?

It means half of the upstreams (the specific numbers maybe 15 and each upstream have 2 pod) will be updated every 30 minutes.

> By the way, could you also check if you enable the server-info plugin?

Sorry, it's not being enabled  before.

```
{"last_report_time":1649989004,"id":"67158603-3d3c-412b-896e-3da3cfe7763b","version":"2.11.0","hostname":"192-168-116-247","boot_time":1649989004,"etcd_version":"3.4.0","up_time":41}
```

**Comment by suninuni** [comment]
The reason is that I found etcd oom, so I increased the memory for it, but it kept restoring from backup when it started. So, I can only rebuild etcd cluster.

So I guess that there are a lot of outdated information in etcd that have not been deleted. I haven't had time to find the relevant documentation on the data structures stored in etcd, is there anything I can query to confirm this?

**Comment by suninuni** [comment]
> So I guess that there are a lot of outdated information in etcd that have not been deleted. I haven't had time to find the relevant documentation on the data structures stored in etcd, is there anything I can query to confirm this?

I can't found dirty data in etcd, but the memory usage is normal?

![image](https://user-images.githubusercontent.com/7345529/163564808-fd46336d-e460-4c09-940f-bf6c07b79d23.png)

![image](https://user-images.githubusercontent.com/7345529/163564966-437c459d-65ca-444b-a49b-5fbee2214593.png)

**Comment by tokers** [comment]
@suninuni ETCD supports MVCC, so each `PUT` operation will make it generate a new version for the key-value pair, you may enable the auto compaction.

**Comment by suninuni** [comment]
> @suninuni ETCD supports MVCC, so each `PUT` operation will make it generate a new version for the key-value pair, you may enable the auto compaction.

Thanks, enable compaction solved my problem.
