### ISSUE TITLE
help request:  How should I set some properties of nginx in apisix

### ISSUE THREAD

**Issue by XW512** [apache/apisix#6852]
### Description

Now I use the APIs IX gateway in production and occasionally report recv() failed (104: connection reset by peer) while reading response header. After querying the data, it is found that the following default attributes in Apis IX may be relatively small
client_ body_ buffer_ size 512k;
client_ header_ buffer_ size 512k;
proxy_ buffers 4 64k;
proxy_ busy_ buffers_ size 64k;

How should I set these properties? In apifix, I see config - default Only client in yaml_ max_ body_ Size attribute, how should I set the above attributes? Thank you

### Environment

- APISIX version (run `apisix version`):  2.13.0
- Operating system (run `uname -a`): centOS7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

**Comment by XW512** [comment]
> see: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

OK,thank you,wo will try it

**Comment by XW512** [comment]
> see: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

When I was in config.yaml is configured as follows,

nginx_config:
    http_configuration_snippet: |
        client_body_buffer_size 100m;
        client_header_buffer_size 100m;
        proxy_buffers 4 10m;
        proxy_busy_buffers_size 10m;

I found that apisik can start, but in the generated nginx It is found that the configuration is not aligned in conf. how should this be aligned

    # http configuration snippet starts
    client_body_buffer_size 100m;
client_header_buffer_size 100m;
proxy_buffers 4 10m;
proxy_busy_buffers_size 10m;

    # http configuration snippet ends

**Comment by tzssangglass** [comment]
> 发现apisik可以启动，但是在生成的nginx中发现conf中没有对齐配置。这应该如何对齐

maybe you need to change : https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua

but I don't think that's a problem.

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this if you need.

**Comment by hyt05** [comment]
> > 发现apisik可以启动，但是在生成的nginx中发现conf中没有对齐配置。这应该如何对齐
> 
> maybe you need to change : https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua
> 
> but I don't think that's a problem.

I also encountered the phenomenon of misalignment, it does not affect the actual effect is it?
