### ISSUE TITLE
help request: Is it possible to apply the same plugins to multiple routes with different upstream?

### ISSUE THREAD

**Issue by MirtoBusico** [apache/apisix#6865]
### Description

Hi all,
I need to apply the same plugins to different routes that have different upstreams.

My use case:
Using openid-connect and authz-keycloak on these routes:
https://www.m01.net/frontend (single page application calling api1, api2 and api3) with upstream **frontendapp**
https://www.m01.net/api1 with upstream **api1server**
https://www.m01.net/api2 with upstream **api2server**
https://www.m01.net/api3 with upstream **api3server**

For now everything works if I define the two plugins for every route

I cannot use global plugins because I have some routes that have not to be authenticated/authorized

Is it possible to have the same plugins for different routes with different upstream?

Note: I'm using Apisix 2.13

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
I think what you need is: https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/plugin-config.md

**Comment by MirtoBusico** [comment]
Seems exactly what I need.

I'll try and report here

Thanks

**Comment by tzssangglass** [comment]
hi @MirtoBusico , pls see: https://github.com/apache/apisix-dashboard/issues/1904

**Comment by MirtoBusico** [comment]
Thanks a lot
This solves my question
