### ISSUE TITLE
APISIX 是否支持使用 etcd 作为服务注册和发现中心

### ISSUE THREAD

**Issue by shuqingzai** [apache/apisix#6866]
### Description

请问下，在 [discovery](https://apisix.apache.org/zh/docs/apisix/discovery) 好像没有看到 ETCD 的使用说明，是不支持吗？？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/4442#issuecomment-863746666 and https://github.com/apache/apisix/issues/4713
same as:#4442, so close this issue.
