### ISSUE TITLE
help request: override global rule for someone route

### ISSUE THREAD

**Issue by lefreet** [apache/apisix#6878]
### Description

1. i wan to add ip-restriction for  40 routes,  with some whitelist ips config. so i config the global rule for all of them.
2. after a time, i have the 41th route, it do not need ip-restriction

i try:
1. set the ip-restriction for the 41th route, attempt override global rule,  invalid.  with the doc say `Consumer > Route > Service` , but `Global`   :(
2. set the [Plugin Config](https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/plugin-config.md), but i should reconfig the plugin template for old 40 routes,  and do not config for the 41th route. the plugin config will merge route plugin and it is not intuitive

so , is some way to override the global rule(ip-restriction) only for my 41th route ?

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`): x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> so , is some way to override the global rule(ip-restriction) only for my 41th route ?

no way. global rule does effect for all requests.

**Comment by kwanhur** [comment]
Enn, it's a good feature for plugin's mechanism taking effects on selected routes, not only gobal.

**Comment by kwanhur** [comment]
> It makes the concept vague, difficult to maintain, and is a lazy approach.

Could you explain `it makes the concept vague` more details?

**Comment by kwanhur** [comment]
From plugin market in dashboard, it has only one option `global` for plugin's scope.

As users under the above scenario, if the candidate routes can be options for plugins' scope, it'll be more convenient to take the target. But also it'll be a huge and hard job behind this options.
