### ISSUE TITLE
bug: Some random api calls are taking 20 seconds to return from apisix

### ISSUE THREAD

**Issue by ignaciostellino** [apache/apisix#6890]
### Current Behavior

We are seeing some random calls that are pending for 20 seconds before the answer return. We have apisix as a gateway in the middle.
After restarting apisix seem to be fixed, need to know the root cause

### Steps to Reproduce

Run Apisix
Create routes
Some random apicalls take 20 seconds to response

### Environment

APISIX Version: 2.9-alpine

**Comment by tokers** [comment]
@ignaciostellino Could you describe the case in a more detailed way, we need at least the following information to help you:

1. What do the APIs look like?
2. How do you send API requests?
3. Have you ever tested the backend directly?
4. How do you deploy Apache APISIX?

**Comment by tzssangglass** [comment]
You've provided almost no useful information ......

BTW, did you use `prometheus` plugin?

**Comment by ignaciostellino** [comment]
> @ignaciostellino Could you describe the case in a more detailed way, we need at least the following information to help you:
> 
> 1. What do the APIs look like?
> 2. How do you send API requests?
> 3. Have you ever tested the backend directly?
> 4. How do you deploy Apache APISIX?

1. looks like /backend/apisix/backend/cap/api/v1/version
2. from the front end to apix six to the service
3. before having apisix in the middle we do not expirience this delay
4. With a docker image

We don't use prometheus plugin

**Comment by tokers** [comment]
> > @ignaciostellino Could you describe the case in a more detailed way, we need at least the following information to help you:
> > 
> > 1. What do the APIs look like?
> > 2. How do you send API requests?
> > 3. Have you ever tested the backend directly?
> > 4. How do you deploy Apache APISIX?
> 
> 1. looks like /backend/apisix/backend/cap/api/v1/version
> 2. from the front end to apix six to the service
> 3. before having apisix in the middle we do not expirience this delay
> 4. With a docker image
> 
> We don't use prometheus plugin

We need the elaborate route structure (without sensitive data) and the steps to reproduce this problem.

**Comment by ignaciostellino** [comment]
> > > @ignaciostellino Could you describe the case in a more detailed way, we need at least the following information to help you:
> > > 
> > > 1. What do the APIs look like?
> > > 2. How do you send API requests?
> > > 3. Have you ever tested the backend directly?
> > > 4. How do you deploy Apache APISIX?
> > 
> > 
> > 
> > 1. looks like /backend/apisix/backend/cap/api/v1/version
> > 2. from the front end to apix six to the service
> > 3. before having apisix in the middle we do not expirience this delay
> > 4. With a docker image
> > 
> > We don't use prometheus plugin
> 
> We need the elaborate route structure (without sensitive data) and the steps to reproduce this problem.

We have the following scenario:
APISIX is configured with OpenID-Connect plugin to authenticate API-requests by connecting to Keycloak’s open-id connect discovery & token introspection endpoints.
![image](https://user-images.githubusercontent.com/4086736/164722930-f87c60fe-98c4-4dd9-85a8-8b762034d888.png)

I hope this helps to understand our use of case

**Comment by tzssangglass** [comment]
> I hope this helps to understand our use of case

The architecture diagram is useful, but the reproduction steps need to be provided so that I can reproduce your problem locally in my area.

**Comment by tzssangglass** [comment]
You can refer to the author of this issue #6834, he provides great reproduction steps, I followed his reproduction steps to locate the problem very accurately and quickly.
