### ISSUE TITLE
feat: optimize uri-Blocker plugin

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#6900]
### Description

The current uri-blocker plugin interception for uri is based on the variable $request_uri, but $request_uri contains both path and parameters, I think it is more appropriate to intercept based on the variable $uri

**Comment by tokers** [comment]
Another idea, why not extend the URL match mode in this plugin?

**Comment by zuiyangqingzhou** [comment]
I thought about it later and you are right, thank you
