### ISSUE TITLE
docs: Optimize the table structure in plugin documentation.

### ISSUE THREAD

**Issue by hf400159** [apache/apisix#6912]
### Current State

In fact, in each plug-in of APISIX, there is a property table, such as the following figure. But this has a problem, for example, the `Default` and `Valid values` columns are mostly empty. So I suggest adding the contents of the `Default` and `Valid values` columns to the `Description`. This makes the table structure clearer. If there are many blank rows in the table, it is of no value to the user.

Before changing:
| Name         | type                                         | Required  | Default | Valid values | Description                                            |
| ------------ | -------------------------------- | ----------- | -------- | ------------- | ----------------------------------------   |
| proto_id     | string/integer                          | True          |              |                     | id of the proto content.                  |
| service       | string                                       | True          |               |                    | Name of the gRPC service.                   |
| method     | string                                       | True          |               |                     | Method name of the gRPC service.      |
| deadline    | number                                   | False         |     0         |                    | Deadline for the gRPC service in ms.    |
| pb_option | array[string(pb_option_def)]   | False         |                |                    | protobuf options.                                  |

After changing:
| Name         | Type                                         | Required  |   Description                                                                           |
| ------------ | -------------------------------- | ----------- |  --------------------------------------------------------------   |
| proto_id     | string/integer                          | True          |  id of the proto content                                                         |
| service       | string                                       | True          |  Name of the gRPC service.                                                    |
| method     | string                                       | True          | Method name of the gRPC service.                                        |
| deadline    | number                                   | False         |   Deadline for the gRPC service in ms. **Default value: 0.**   |
| pb_option | array[string(pb_option_def)]   | False         |   protobuf options.                                                                  |

![image](https://user-images.githubusercontent.com/97138894/164709574-56a56c56-2b47-4d80-80c7-64e2be520615.png)
![image](https://user-images.githubusercontent.com/97138894/164709628-cf507078-8659-4aeb-8143-a21961bfea1d.png)
![image](https://user-images.githubusercontent.com/97138894/164709680-0eb85c5e-1b62-4597-bb32-6539c6e2863d.png)

### Desired State

Optimize the table structure in plugin documentation.

**Comment by spacewander** [comment]
Isn't this change make the default value hard to find?

**Comment by juzhiyuan** [comment]
I would prefer keeping this column because it's much more straightforward :)
