### ISSUE TITLE
docs:  The link in 'how-to-reload-your-own-plugin' section of the FAQ page is invalid

### ISSUE THREAD

**Issue by qlql489** [apache/apisix#6920]
### Current State

the link in https://apisix.apache.org/docs/apisix/FAQ#how-to-reload-your-own-plugin is invalid
![](http://image.nianlun.tech/2022/04/24/3fdb6da7dd0e752fd09db8a6f6701ff7.png)

click the link show

![](http://image.nianlun.tech/2022/04/24/c3fdc390c231bc51141b2cfe1967d89a.png)
error link url is https://apisix.apache.org/docs/apisix/plugins.md, already invalid In the language state of Chinese, 

### Desired State

Fix the link to correct address

**Comment by Chever-John** [comment]
Would you like to solve this problem?
