### ISSUE TITLE
feat: As a user, I want to let api-breaker plugin return default response body

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#6923]
### Description

refer to the document [api-breaker](https://apisix.apache.org/docs/apisix/plugins/api-breaker)
when upstream is in the unhealthy state, the api-breaker returns unhealthy.http_statuses only, without a response body.
In order to be more compatible to the client, return a default response body is useful.

**Comment by tokers** [comment]
Sound good, which value do you think is reasonable for the default response body?

**Comment by qihaiyan** [comment]
> Sound good, which value do you think is reasonable for the default response body?

Different api may return different default value. Users should specify the default value with admin api, and the plugin api could add a new param like unhealthy.http_response_body

**Comment by tokers** [comment]
> > Sound good, which value do you think is reasonable for the default response body?
> 
> Different api may return different default value. Users should specify the default value with admin api, and the plugin api could add a new param like unhealthy.http_response_body

I think a field like `break_response_body` can be added.

**Comment by qihaiyan** [comment]
> > > Sound good, which value do you think is reasonable for the default response body?
> > 
> > 
> > Different api may return different default value. Users should specify the default value with admin api, and the plugin api could add a new param like unhealthy.http_response_body
> 
> I think a field like `break_response_body` can be added.

I could make a pr for this, if you don't mind. @tokers

**Comment by tokers** [comment]
> > > > Sound good, which value do you think is reasonable for the default response body?
> > > 
> > > 
> > > Different api may return different default value. Users should specify the default value with admin api, and the plugin api could add a new param like unhealthy.http_response_body
> > 
> > 
> > I think a field like `break_response_body` can be added.
> 
> I could make a pr for this, if you don't mind. @tokers

Sure, assigned to you.
