### ISSUE TITLE
request help: does APISIX support Server-sent events protocol?

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#6938]
### Discussed in https://github.com/apache/apisix/discussions/6930

<div type='discussions-op-text'>

<sup>Originally posted by **lrodriguez14** April 26, 2022</sup>
Does Apache Apisix support SSE(Server Sent Events)?</div>

**Comment by marziman** [comment]
Hello team,

we also need SSE and the EventSource implementation. We dont want to move away from all our APISIX knowhow and solutions where we use it, just for lack of SSE (EventSource).
I am wondering: As PISIX is based on NGINX, is it possible to reuse/install a NGINX plugin like this: https://github.com/wandenberg/nginx-push-stream-module
or just adding some configuration to NGINX to support it?

Or is developing a plugin in Java the right path? Would be great to get some help on this.

Thanks!
BR Mehmet

**Comment by juzhiyuan** [comment]
Hi @markt-asf, according to this comment[1], Apache APISIX doesn't support SSE so far.

> I am wondering: As APISIX is based on NGINX, is it possible to reuse/install a NGINX plugin like this: https://github.com/wandenberg/nginx-push-stream-module

For this one, let's wait for @spacewander's confirmation 🤗

We also have a Slack channel[2] under the Apache Software Foundation. There have 450+ members, and you are welcome to join in.

[1] https://github.com/apache/apisix/discussions/6930#discussioncomment-2642832
[2] https://apisix.apache.org/docs/general/join/
