### ISSUE TITLE
request help:  proxy-rewrite cannot modify X-Forwarded-Port

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix#6945]
### Current Behavior

clb(80 port)-> apisix(9080 port) --> pod
![image](https://user-images.githubusercontent.com/48319268/165440701-290ae881-1feb-4700-8fba-72cb6b9ded71.png)
![image](https://user-images.githubusercontent.com/48319268/165440809-a43fad1e-29bd-4a3e-9273-3f45a23eee9f.png)

### Expected Behavior

X-Forwarded-Port: 777
X-Forwarded-Port111: 77788

### Steps to Reproduce

apiVersion: apisix.apache.org/v2beta3
kind: ApisixRoute
metadata:
  name: whoami
  namespace: apisix
spec:
  http:
  - backends:
    - resolveGranularity: service
      serviceName: whoami
      servicePort: 80
      weight: 100
    match:
      paths:
      - /*
    plugins:
    - name: proxy-rewrite
      enable: true
      config:
        headers:
          X-Forwarded-Port: 777
          X-Forwarded-Port111: 77788
    name: rule11

### Environment

- APISIX version (run `apisix version`): 1.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Horus-K** [comment]
This made me have to modify the apisix listening port to 80 443

**Comment by tzssangglass** [comment]
This is a known issue and not a bug.

You can continue working on this PR: #5367, or take a temporary solution like this: https://github.com/apache/apisix/issues/5080#issuecomment-921499970
