### ISSUE TITLE
help request: how to build access_key secret_key relationships with customers on hmac-auth plugin?

### ISSUE THREAD

**Issue by jxw1989** [apache/apisix#6950]
### Description

How to build access_key secret_key relationships with customers
For example, if there is an interface called by two companies A and B at the same time, the access_key of company A and company B have different access_key needs, how to deal with it at this time

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@jxw1989 You mean the hmac-auth plugin?

**Comment by tzssangglass** [comment]
@jxw1989 pls describe your problem in detail, including background, current situation, expected goals, etc.

**Comment by jxw1989** [comment]
> @jxw1989 You mean the hmac-auth plugin?

yes

**Comment by tokers** [comment]
See https://apisix.apache.org/docs/apisix/plugins/hmac-auth/ for the details.

`access_key` should be maintained by yourselves.

**Comment by jxw1989** [comment]
> @jxw1989 You mean the hmac-auth plugin?



> See https://apisix.apache.org/docs/apisix/plugins/hmac-auth/ for the details.
> 
> `access_key` should be maintained by yourselves.

The current access_key and secret_key of hmac-auth need to be configured in the consumer in advance, and then the access_key and secret_key are issued to the interface caller, my problem is how to achieve the interface caller to apply for access_key and secret_key on its own

**Comment by qihaiyan** [comment]
> > @jxw1989 You mean the hmac-auth plugin?
> 
> > See https://apisix.apache.org/docs/apisix/plugins/hmac-auth/ for the details.
> > `access_key` should be maintained by yourselves.
> 
> The current access_key and secret_key of hmac-auth need to be configured in the consumer in advance, and then the access_key and secret_key are issued to the interface caller, my problem is how to achieve the interface caller to apply for access_key and secret_key on its own

The AccessKey management is the role of IAM system, like what cloud company does like AWS or aliyun.
https://aws.amazon.com/cn/premiumsupport/knowledge-center/iam-authentication-api-gateway/
