### ISSUE TITLE
help request: Why does apisix not have lua-resty-openssl?

### ISSUE THREAD

**Issue by Jon-Gaara** [apache/apisix#6962]
### Description

目前想通过apisix往kafka里面推送日志，但是由于公司的kafka必须通过SASL_SSL+SCRAM-SHA-512的方式才能连接，因此apisix自带的kafka-logger不支持，所以就想自定义开发插件，但是发现目前lua-resty-kafka也不支持这种形式的连接，并且apisix最新版本里面也不包含 lua-resty-openssl，因为我想问下：
   1.apisix是出于什么原因，没有包含lua-resty-openssl？
   2.apisix的kafka-logger是否能支持SASL_SSL+SCRAM-SHA-512这种模式连接kafka？

### Environment

- APISIX version (run `apisix version`): 2.10.0
- Operating system (run `uname -a`): Linux  5.10.16.3-microsoft-standard-WSL2
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): luarocks --version

**Comment by tzssangglass** [comment]
> 1.apisix是出于什么原因，没有包含lua-resty-openssl？

Install a new dependency because it is needed, and don't contain a new dependency because it is no required.

> 2.apisix的kafka-logger是否能支持SASL_SSL+SCRAM-SHA-512这种模式连接kafka？

@bzp2010, do you know this detail?

**Comment by tzssangglass** [comment]
> 1.apisix是出于什么原因，没有包含lua-resty-openssl？

Install a new dependency because it is needed, and don't contain a new dependency because it is no required.

> 2.apisix的kafka-logger是否能支持SASL_SSL+SCRAM-SHA-512这种模式连接kafka？

@bzp2010, do you know this detail?

**Comment by xgenvn** [comment]
@Jon-Gaara I think it would be easier to develop a logger middleware instead a new plugin, as a workaround. And perhaps use the `http-logger` plugin to push the logs. SSL configuration seems too lots of work in general.

**Comment by Jon-Gaara** [comment]
We rewrite resty.kafka to support scram-sha-512

**Comment by kwanhur** [comment]
> 1.apisix是出于什么原因，没有包含lua-resty-openssl？

if install apisix manually, you can find `lua-resty-openssl` indirectly pulling.
```shell
sudo luarocks install https://raw.githubusercontent.com/apache/incubator-apisix/master/rockspec/apisix-master-0.rockspec
luarocks show apisix
```

```plaintext
	lua-resty-ngxvar (using 0.5.2-0)
	lua-resty-openidc (using 1.7.2-1)
	lua-resty-openssl (using 0.8.8-1)
	lua-resty-radixtree (using 2.8.2-0)
	lua-resty-rocketmq (using 0.3.0-0)
```

**Comment by Jon-Gaara** [comment]
> > 1.apisix是出于什么原因，没有包含lua-resty-openssl？
> 
> if install apisix manually, you can find `lua-resty-openssl` indirectly pulling.
> 
> ```shell
> sudo luarocks install https://raw.githubusercontent.com/apache/incubator-apisix/master/rockspec/apisix-master-0.rockspec
> luarocks show apisix
> ```
> 
> ```
> 	lua-resty-ngxvar (using 0.5.2-0)
> 	lua-resty-openidc (using 1.7.2-1)
> 	lua-resty-openssl (using 0.8.8-1)
> 	lua-resty-radixtree (using 2.8.2-0)
> 	lua-resty-rocketmq (using 0.3.0-0)
> ```
I installed apisix manually, apisix-master-0.rockspec not included lua-resty-openssl

**Comment by kwanhur** [comment]
You can find it in `LUA_PATH` of `luarocks path`.
