### ISSUE TITLE
help request: lsof command not found while launching

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#6977]
### Description

Launch `apisix` failed via `systemctl start apisix`, I got the logs like

```shell
May 03 15:00:00 lvs systemd[1]: Starting apisix...
May 03 15:00:00 lvs apisix[13574]: /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
May 03 15:00:01 lvs apisix[13574]: sh: lsof: command not found
May 03 15:00:01 lvs apisix[13574]: nginx.pid exists but there's no corresponding process with pid         3876        , the file will be overwritten
May 03 15:00:02 lvs systemd[1]: Started apisix.
```

1. `lsof: command not found` `lsof` tool not existed in minimal centos 7 environment. Better to check `/proc/pid` directory exist or not via [lfs. attributes](https://keplerproject.github.io/luafilesystem/manual.html#reference). https://github.com/apache/apisix/blob/cc88a8db0ba64e1cb351e389ca5ec64c516073d6/rockspec/apisix-2.13.1-0.rockspec#L51
2. It should `return` while checking pid failed, log `nginx.pid exists but there's no corresponding process with pid` shouldn't output.
https://github.com/apache/apisix/blob/cc88a8db0ba64e1cb351e389ca5ec64c516073d6/apisix/cli/ops.lua#L723-L738

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Linux lvs 3.10.0-327.4.5.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@kwanhur Thanks for the feedback! I think it's good to remove the dependency to `lsof`.

**Comment by tokers** [comment]
> If known running on macOS, two solutions retrieve process information to check APISIX running or not:
> 
> 1. try to send a healthy signal via [luaposix](https://luaposix.github.io/luaposix/modules/posix.signal.html).
> 2. fetch via [proc_pidinfo](https://opensource.apple.com/source/xnu/xnu-4570.41.2/bsd/kern/proc_info.c.auto.html), require some hack jobs.

What about using the first option? We cannot unify the way we check if APISIX is running without the `lsof`, then why not using a straightforward and easy way.

**Comment by tzssangglass** [comment]
If the first option solves the problem (compatibility with different platforms), I support the first.

**Comment by kwanhur** [comment]
The first one, recommend `0` NONE signal which supported both on Linux and MacOS, I check the result as below

```shell
# Linux(Centos7)
[root@lvs ~]# kill -s 0 14291; echo $?
0
[root@lvs ~]# kill -s 0 14295; echo $?
-bash: kill: (14295) - No such process
1

# Macos
➜  ~ kill -0 18237; echo $?
0
➜  ~ kill -0 18236; echo $?
kill: kill 18236 failed: no such process
1
```

**Comment by tzssangglass** [comment]
> The first one, recommend `0` NONE signal which supported both on Linux and MacOS, I check the result as below

I don't really understand the difference, can you expand on it?

**Comment by kwanhur** [comment]
Solution 1 `try to send a healthy signal via luaposix`, so we can choose the signal name `NONE` and its number `0` as the healthy signal, this one both supported on Linux and MacOS, so it will be a uniform signal via luaposix.

**Comment by tzssangglass** [comment]
> Solution 1 `try to send a healthy signal via luaposix`, so we can choose the signal name `NONE` and its number `0` as the healthy signal, this one both supported on Linux and MacOS, so it will be a uniform signal via luaposix.

get
