### ISSUE TITLE
help request: How to test whether apisix is connected to consul kv

### ISSUE THREAD

**Issue by 107295472** [apache/apisix#6987]
### Description

All my requests are 503, and it is easy to write the target host to death. 503 with consul kv

### Environment

- APISIX version (run `apisix version`):2.12.1
- Operating system (run `uname -a`):centos 7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.0
- APISIX Dashboard version, if relevant:2.10.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Take a look at the errorlog?

**Comment by 107295472** [comment]
where is the errorlog

**Comment by 107295472** [comment]
`<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>`

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/167053118-1d82ce63-edc6-49b5-88c2-906fe80cd640.png)

**Comment by 107295472** [comment]
![image](https://user-images.githubusercontent.com/6436116/167053165-f786f489-c93f-49ff-aefc-30c6c7a8c059.png)

**Comment by 107295472** [comment]
> Take a look at the errorlog?

do you need nginx-upsync-module?

**Comment by 107295472** [comment]
fetch nodes failed by http://127.0.0.1:8500/v1/kv/upstreams/webpages, return default service, client: 192.168.10.161, server: _, request: "POST /accountservice/accountusecase/AccountLogin HTTP/1.1", host: "192.168.10.21:9080"
