### ISSUE TITLE
request help:How to write the Apisix log to ES?

### ISSUE THREAD

**Issue by helloxubo** [apache/apisix#6990]
### Issue description

Hello，I need to write the apisix access log and error log to ES. How to using http-logger plugin?

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
- your Kubernetes cluster version (output of kubectl version):
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a):

**Comment by tao12345666333** [comment]
http-logger: https://apisix.apache.org/docs/apisix/plugins/http-logger

I remember there was a discussion about APISIX writing logs to ES. 
Any plans? @tzssangglass
