### ISSUE TITLE
help request: auth plugin header question

### ISSUE THREAD

**Issue by stubbornTanzhe** [apache/apisix#6994]
### Description

I've see key-auth and jwt-auth，my point is why not auth plugin add sth which authorized?
such as consumer config->username 
in my scene,upstream usually wanna sth authorized result, such as username,which corresponding a consumer obj section
so i've been curious about the auth plugin original design idea

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> which corresponding a consumer obj section so i've been curious about the auth plugin original design idea

consumer is a concept in APISIX that is not passed upstream in the original design (the concept is out of scope)

you can pass `consumer_name` to the upstream in this way: https://github.com/apache/apisix/issues/4078#issuecomment-822231019

I now think it would be a useful feature to let users choose whether to pass consumer-related information upstream, and I've seen a similar claim at least three times in different issues.

What about the opinions of others?

**Comment by tokers** [comment]
> 

I think in this case what users really need is not the consumer information but the specific auth information (username of the basic-auth)?

**Comment by stubbornTanzhe** [comment]
thanks a lot.

yes,upstream really need is the auth info,maybe the authed user-info such as username or role sth.

[https://github.com/apache/apisix/issues/4078#issuecomment-822231019](url) 
i solve the problem with writing a custom plugin,sth like 
`core.request.set_header(ctx, "X-App-ID", consumer.username)` 

maybe we can give more best practice, such as <$consumer_name> usage, which i found only as "Nginx variables". 
I've no idea about the connection between the obj in apisix and the "Nginx variables"
@tzssangglass @tokers

**Comment by tzssangglass** [comment]
> I've no idea about the corresponding relationship between the obj in apisix and the "Nginx variables"

see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md#register-custom-variable

**Comment by stubbornTanzhe** [comment]
problem solved,close
