### ISSUE TITLE
feat: As a user, I want to  see `grpc-status-details-bin` in response body in case an error, so that I avoid parsing header to read error response

### ISSUE THREAD

**Issue by mehmetcuneyit** [apache/apisix#6996]
### Description

 I'm using `grpc-transcode` plugin to manage gRPC<=> HTTP, It would be great to convert `grpc-status-details-bin`  in header to HTTP response body  in case an error from the upstream. 
 
![Screenshot from 2022-05-07 15-31-05](https://user-images.githubusercontent.com/39027858/167256606-8855f255-5d6d-4c23-9a50-69d0b2f9b68a.png)

Decoded `grpc-status-details-bin` : 
![Screenshot from 2022-05-07 15-30-55](https://user-images.githubusercontent.com/39027858/167256611-80ae50df-221f-4448-aa6b-f21c946253f9.png)

Corresponding error model, see https://cloud.google.com/apis/design/errors for more : 

```
package google.rpc;

// The `Status` type defines a logical error model that is suitable for
// different programming environments, including REST APIs and RPC APIs.
message Status {
  // A simple error code that can be easily handled by the client. The
  // actual error code is defined by `google.rpc.Code`.
  int32 code = 1;

  // A developer-facing human-readable error message in English. It should
  // both explain the error and offer an actionable resolution to it.
  string message = 2;

  // Additional error information that the client code can use to handle
  // the error, such as retry info or a help link.
  repeated google.protobuf.Any details = 3;
}
```
Here are my concerns, quoting from https://www.grpc.io/docs/guides/error/

 - Library implementations of the extended error model may not be consistent across languages in terms of requirements for and expectations of the error details payload
- Existing proxies, loggers, and other standard HTTP request processors don’t have visibility into the error details and thus wouldn’t be able to leverage them for monitoring or other purposes
- Additional error detail in the trailers interferes with head-of-line blocking, and will decrease HTTP/2 header compression efficiency due to more frequent cache misses
- Larger error detail payloads may run into protocol limits (like max headers size), effectively losing the original error

Resources:
- Just to give you an idea , [similar problem for envoy in the past](https://github.com/envoyproxy/envoy/issues/3383)

**Comment by membphis** [comment]
@nic-chen What do you think of this feature?

**Comment by tzssangglass** [comment]
LGTM.

we can make it more consistent with HTTP semantics.

**Comment by nic-chen** [comment]
> LGTM.
> 
> we can make it more consistent with HTTP semantics.

+1

**Comment by membphis** [comment]
@nic-chen can you write a design about this new feature?

**Comment by mehmetcuneyit** [comment]
Thank you team for the quick attention :+1: 
Updated couple of details, I think `grpc-status-details-bin` is better choice  since `grpc-message`  it's already included

**Comment by nic-chen** [comment]
> Thank you team for the quick attention 👍 Updated couple of details, I think `grpc-status-details-bin` is better choice since `grpc-message` is already included

Thanks for the suggestion.

**Comment by vyvyan2010** [comment]
let me handle this

**Comment by vyvyan2010** [comment]
Do we need to decode `grpc-status-details-bin` ?

**Comment by tokers** [comment]
I think so. gRPC should be converted to HTTP, similarly, protobuf should be converted to JSON.

**Comment by tokers** [comment]
> @tokers do we have an example about how to decode `grpc-status-details-bin` via proto? 

Nope, we may need a closer look about the encoding rule of it.

**Comment by vyvyan2010** [comment]
`grpc-status-details-bin` is encoded with marshalling followed by base64

**Comment by tzssangglass** [comment]
> I have no idea how to upload proto file, and decode it with lua.

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md#enabling-the-plugin

we can use admin API, like:

```
curl http://127.0.0.1:9080/apisix/admin/proto/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "content" : "syntax = \"proto3\";
    package helloworld;
    service Greeter {
        rpc SayHello (HelloRequest) returns (HelloReply) {}
    }
    message HelloRequest {
        string name = 1;
    }
    message HelloReply {
        string message = 1;
    }"
}'
```

**Comment by vyvyan2010** [comment]
@tokers @tzssangglass do you agree with this plan ?

**Comment by tzssangglass** [comment]
> @tokers @tzssangglass do you agree with this plan ?

I'm not familiar with gRPC, cc @spacewander @bzp2010

**Comment by spacewander** [comment]
> `grpc-status-details-bin` is encoded with marshalling followed by base64, we need the proto to unmarshall. I have no idea how to upload proto file, and decode it with lua.
> 
> Here is my test code
> 
> ```
> message ErrorDetail {
>     int64 code = 1;
>     string message = 2;
>     string type = 3;
> }
> 
> // GetErrResp implements helloworld.GreeterServer
> func (s *server) GetErrResp(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
>     st := status.New(codes.Unavailable, "Out of service")
>     st, err := st.WithDetails(&pb.ErrorDetail{
>         Code:             1,
>         Message:       "The server is out of service",
> 	Type:  	       "service",
>     })
> 
>     if err != nil {
> 	panic(fmt.Sprintf("Unexpected error attaching metadata: %v", err))
>     }
> 
>     return nil, st.Err()
> }
> 
> === TEST 3: hit route
> --- request
> GET /grpctest?name=world
> --- response_headers
> grpc-status: 14
> grpc-message: Out of service
> grpc-status-details-bin: CA4SDk91dCBvZiBzZXJ2aWNlGlcKKnR5cGUuZ29vZ2xlYXBpcy5jb20vaGVsbG93b3JsZC5FcnJvckRldGFpbBIpCAESHFRoZSBzZXJ2ZXIgaXMgb3V0IG9mIHNlcnZpY2UaB3NlcnZpY2U
> --- no_error_log
> [error]
> --- error_code: 503
> ```

Put it under https://github.com/apache/apisix/tree/master/apisix/include/apisix/model

**Comment by spacewander** [comment]
> I'm going to add 2 configuration items
> 
>     1. `cpy_err_details_to_body`:  if true, copy `grpc-status-details-bin` to response body, the one in response header won't be deleted
>        {
>        "error": {
>        grpc-status-details-bin: "CA4SDk91dCBvZiBzZXJ2aWNlGlcKKnR5cGUuZ29vZ2xlYXBpcy5jb20vaGVsbG93b3JsZC5FcnJvckRldGFpbBIpCAESHFRoZSBzZXJ2ZXIgaXMgb3V0IG9mIHNlcnZpY2UaB3NlcnZpY2U"
>        }
>        }
> 
>     2. `err_details_proto_name`: if configured, decode `grpc-status-details-bin` to the following format:
>        {
>        "error": {
>        "code": 401,
>        "message": "Request had invalid credentials.",
>        "details": [{"type":"service","code":1,"message":"The server is out of service"}]
>        }
>        }

I would suggest using only one argument, directly decoding the header as a body.
`show_error_details_in_body` (bool):  if configured, decode `grpc-status-details-bin` in the body.

Store raw data in the body is not so helpful.

**Comment by vyvyan2010** [comment]
> 
```
        local encoded_data = "CA4SDk91dCBvZiBzZXJ2aWNlGlcKKnR5cGUuZ29vZ2xlYXBpcy5jb20vaGVsbG93b3JsZC5FcnJvckRldGFpbBIpCAESHFRoZSBzZXJ2ZXIgaXMgb3V0IG9mIHNlcnZpY2UaB3NlcnZpY2U"
        local decoded_data = ngx_decode_base64(encoded_data)
        local data = pb.decode("ErrorStatus", decoded_data)
        data = data.details[1].value
        local data = pb.decode("ErrorDetail", data)
```
Need to specify the proto name to decode `grpc-status-details-bin`, so  the `proto name` configuration item is needed

**Comment by spacewander** [comment]
> `proto name`

There is no `proto name` in your example?

**Comment by vyvyan2010** [comment]
```
message ErrorDetail {
    int64 code = 1;
    string message = 2;
    string type = 3;
}

local data = pb.decode("ErrorDetail", data)
```
message type ?

**Comment by spacewander** [comment]
The proto definition is in https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto.

See https://github.com/grpc/grpc-go/blob/ca62c6b92c334f52c7e48b7cbf624f3b877fb092/internal/transport/http_util.go#L317

**Comment by spacewander** [comment]
Do you mean:
```
                    "plugins": {
                        "grpc-transcode": {
                            "proto_id": "1",
                            "service": "helloworld.Greeter",
                            "method": "SayMultipleHello",
                            "show_status_in_body": true,
                            "status_detail_type": "helloworld.HelloReply"
                       }
                    }
```

Use the `show_status_in_body` to control the conversion, and the `status_detail_type` to control the type of the Detail

**Comment by vyvyan2010** [comment]
`show_status_in_body`, optional, when enabled, will show decoded `grpc-status-details-bin` in response body
`status_detail_type`, optional, the message type of  the `grpc-status-details-bin`'s `details` part, if not given, the `details` part will not be decoded.
Is it ok ?

**Comment by spacewander** [comment]
Yes

**Comment by vyvyan2010** [comment]
@spacewander  Have you ever  encountered this problem? I reinstalled my system and failed on test cases. 
```
prove -Itest-nginx/lib -I./ -r t/plugin/grpc-transcode.t
t/plugin/grpc-transcode.t .. 1/? curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
curl: (52) Empty reply from server
```

**Comment by spacewander** [comment]
> prove -Itest-nginx/lib -I./ -r t/plugin/grpc-transcode.t

I tried it again but everything works fine for me.
Do you use the master branch test-nginx?
https://github.com/apache/apisix/blob/f0a8355739db474dae5a150c7d195e0a4a5dbfa9/ci/linux_openresty_common_runner.sh#L41

**Comment by vyvyan2010** [comment]
@spacewander  i have found the problem today,  Forgetting that a proxy has been configured
```
curl -v -sS -H 'Host: Test-Nginx' 'http://127.0.0.1:1984/ver'
* Uses proxy env variable http_proxy == 'http://192.168.3.11:7890'
*   Trying 192.168.3.11:7890...
* Connected to 192.168.3.11 (192.168.3.11) port 7890 (#0)
```

**Comment by vyvyan2010** [comment]
@nic-chen why do we set `Trailer` response header here?
https://github.com/apache/apisix/blob/master/apisix/plugins/grpc-transcode.lua#L155
the `Trailer` response header is used to indicate the additional fields at the end of chunked
![image](https://user-images.githubusercontent.com/9354193/182778920-71c03b36-f1b0-4b08-aa8b-47f629553580.png)
But "grpc-status" and "grpc-message" are not involved in chunk

**Comment by nic-chen** [comment]
hi @vyvyan2010  we could set the Trailer only to the last chunk when response chunking.

**Comment by vyvyan2010** [comment]
@nic-chen "grpc-status" and "grpc-message" are not in the chunk, they are in the response header, so no need to set `ngx.header["Trailer"] = {"grpc-status", "grpc-message"}`

**Comment by nic-chen** [comment]
> 

OK, welcome to fix it, thanks!
