### ISSUE TITLE
bug: when using apisixroute to expose the service, it will often redirect to port 9080 or 9443 of the apisix-gateway container

### ISSUE THREAD

**Issue by jackk01** [apache/apisix#7003]
### Current Behavior
When using apisixroute to expose services, you will often be redirected to port 9080 or 9443 of the apisix-gateway container.
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/62927162/167243486-02c971f7-b541-4520-bdf4-c9a6ad247c09.png">

### Steps to Reproduce

helm install

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jackk01** [comment]
helm chart info:
apiVersion: v2
appVersion: 2.13.1

**Comment by tzssangglass** [comment]
I think this is a known issue that APISIX and Jenkins work unhealthy and we are fixing it.

ref: https://github.com/apache/apisix/issues/4942

**Comment by jackk01** [comment]
> I think this is a known issue that APISIX and Jenkins work unhealthy and we are fixing it.
> 
> ref: #4942

@tzssangglass @tao12345666333 Upgrade to APISIX v2.14.1, The problem still exists!!!

**Comment by tzssangglass** [comment]
> > I think this is a known issue that APISIX and Jenkins work unhealthy and we are fixing it.
> > ref: #4942
> 
> @tzssangglass @tao12345666333 Upgrade to APISIX v2.14.1, The problem still exists!!!

pls determine if your question is the same as #4942.

**Comment by adriano-brito-ts** [comment]
Also facing this issue, using APISIX with Keycloak + OpenID plugin. Setting redirect plugin with "http_to_https: true" it returns "domain:9443/uri", it should return 443 instead.

Kubernetes 1.26.1
Metallb 0.13.9
APISIX Gateway 3.3.0
APISIX Ingress Controller 1.6.1

Any clue when this isue will be fixed?

Thanks!

**Comment by Nainterceptor** [comment]
Same issue here using apisix ingress controller and keycloak, after few days of trying to find a workaround (like setting up proxy protocol...), we are finally using haproxy for keycloak 🤷‍♂️

**Comment by Revolyssup** [comment]
@Nainterceptor This issue should be fixed for ingress controller with this solution. https://github.com/apache/apisix/issues/4942#issuecomment-1379569298

**Comment by Revolyssup** [comment]
This issue should be fixed for ingress controller with this solution. https://github.com/apache/apisix/issues/4942#issuecomment-1379569298
Please reopen if needed
