### ISSUE TITLE
feat: As a user, I want to make SSL session reusable by id across instances

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#7005]
### Description

As known, build a new SSL connection takes two round time trips between client and server under TLS1.2 or lower.

So, to reduce the connection building cost, especially in a big cluster of APISIX, hope that reuse the SSL session across different instances. 

For example, clientA built a SSL connection with APISIX instanceA, next time clientA reach APISIX instanceB, if the SSL session can be reused, so clientA and instanceB have no need to build a new SSL connection.

**Comment by spacewander** [comment]
We need to modify Nginx to rotate SSL tickets so it is safe to reuse the session. See https://github.com/apache/apisix/issues/2638

**Comment by kwanhur** [comment]
Emm, both ticket and ID can improve SSL session reuse. Here about reusing SSL session by id, just like Apache TrafficServer [SSL Session Reuse Plugin](https://docs.trafficserver.apache.org/en/9.0.x/admin-guide/plugins/ssl_session_reuse.en.html) support it with Redis.

**Comment by spacewander** [comment]
It is possible to use session ID with OpenResty, like the https://github.com/openresty/lua-nginx-module#ssl_session_fetch_by_lua_block. But as the session ticket is the modern way (TLS 1.3 only uses session tickets to resume a session), I don't want to add session ID reuse across instances feature in APISIX.

**Comment by kwanhur** [comment]
Now APISIX support reuse SSL session cache locally by default.

https://github.com/apache/apisix/blob/1b5c1900da517bb7d34d4b221aace7242345e78a/apisix/cli/ngx_tpl.lua#L557-L561

**Comment by spacewander** [comment]
Yes. But investing more resources in an outdated solution is not acceptable.

**Comment by kwanhur** [comment]
Noop, it's not an outdated solution, it's an effective solution for TLS1.2 and below. 
Although TLS1.3 supports by [a big amount of browsers](https://caniuse.com/?search=TLS1.3), but TLS1.2 still will be present along with TLS1.3 for decades.

And now enable TLS1.2 by default, unless it has a plan to EOS(end of service) it recently.

https://github.com/apache/apisix/blob/ab7a7675d2a1abb1f0299a8fd44e5f80435c2158/conf/config-default.yaml#L145

**Comment by spacewander** [comment]
Why not invest in SSL session ticket directly which is both supported in TLS 1.3 and TLS 1.2?

It is very bad to invest in a outdated solution!!!

**Comment by spacewander** [comment]
Considered unacceptable,
