### ISSUE TITLE
help request: The gateway is forwarding websockets to upstream and I find this latency particularly high, does anyone know the configuration that should be optimized there?

### ISSUE THREAD

**Issue by washCutBlow** [apache/apisix#7018]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/26592450/167617630-ec443d64-96e1-43bd-a51b-deb721d5e614.png">

**Comment by tzssangglass** [comment]
It is difficult to see any problems from a picture, you need to give the full reproduction of the steps.

**Comment by tzssangglass** [comment]
> what is the mean the latency here ?

upstream_latency: time consumed by upstream services to process requests

But I'm not sure if this metric is meaningful in the context of the websocket protocol.

**Comment by tokers** [comment]
> > what is the mean the latency here ?
> 
> upstream_latency: time consumed by upstream services to process requests
> 
> But I'm not sure if this metric is meaningful in the context of the websocket protocol.

+1. WebSocket connection is long-live, the latency doesn't represent anything at all.
