### ISSUE TITLE
help request: How to make it possible for some source ip to access only some open apis

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#7019]
### Description

How to make it possible for some source ip to access only some open api's and disable access to the rest of the api's in the cluster via apisix.
![image](https://user-images.githubusercontent.com/92301646/167623932-9c02008c-40a9-4d03-9045-d7018277a219.png)

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.11
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by GhangZh** [comment]
> The ip-restriction Plugin allows you to restrict access to a Service or a Route by either whitelisting or blacklisting IP addresses. Look: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/ip-restriction.md

I've seen this but to meet my needs I need to blacklist the banned api's, the cost is too high as whitelist ones are in the minority

**Comment by tzssangglass** [comment]
> I've seen this but to meet my requirements I need to blacklist the banned api's which is too costly as there are only a few whiteliste api

If you want to do that: allow only certain specifics IP's to access certain specific APIs, there is currently no plugin that fully satisfies this functionality. 
In fact, I think this scenario is more like fine-grained access control.

**Comment by GhangZh** [comment]
> If you want to do that: allow only certain specifics IP's to access certain specific APIs, there is currently no plugin that fully satisfies this functionality. In fact, I think this scenario is more like fine-grained access control.

Yes, it is actually fine-grained access control. do you have any idea

**Comment by tokers** [comment]
> > I've seen this but to meet my requirements I need to blacklist the banned api's which is too costly as there are only a few whiteliste api
> 
> If you want to do that: allow only certain specifics IP's to access certain specific APIs, there is currently no plugin that fully satisfies this functionality. In fact, I think this scenario is more like fine-grained access control.

So what's the relationship between your APIs and the APISIX Routes? 1:1 or N:1?

If it's 1:1, how about put the `ip-restriction` plugin on these specific Routes.

**Comment by GhangZh** [comment]
> So what's the relationship between your APIs and the APISIX Routes? 1:1 or N:1?
> 
> If it's 1:1, how about put the `ip-restriction` plugin on these specific Routes.
N:1

**Comment by tzssangglass** [comment]
> N:1

The current plugins in APISIX do not yet express this relationship. I didn't think of any good way to do it. I guess you could try the suggestions above.

**Comment by tokers** [comment]
> > So what's the relationship between your APIs and the APISIX Routes? 1:1 or N:1?
> > If it's 1:1, how about put the `ip-restriction` plugin on these specific Routes.
> > N:1

Then you have to do some development jobs to adjust your model.

**Comment by kwanhur** [comment]
Dev it with [ext-plugin](https://apisix.apache.org/docs/apisix/external-plugin/) or [serverless](https://apisix.apache.org/docs/apisix/plugins/serverless).
