### ISSUE TITLE
help request: Does apisix support stream replay

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#7020]
### Description

I want to do stream replay at apisix , can someone offer some ideas?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
I don't remember APISIX having the ability to replay? I see that there are tools specifically designed to do replay.

**Comment by moonming** [comment]
@zuiyangqingzhou can you give an example for stream replay?

**Comment by zuiyangqingzhou** [comment]
> @zuiyangqingzhou can you give an example for stream replay?

At present, we use apisix as the traffic entrance for the entire business, we want to be able to record all or specified requests in real time, and when the online business fails, we can play back the real requests based on these offline files.

We learned that something like tcpcopy and goreplay can do something similar, but we wondered how we could do it in apisix

**Comment by zuiyangqingzhou** [comment]
> @zuiyangqingzhou can you give an example for stream replay?

At present, we use apisix as the traffic entrance for the entire business, we want to be able to record all or specified requests in real time, and when the online business fails, we can play back the real requests based on these offline files.

We learned that something like tcpcopy and goreplay can do something similar, but we wondered how we could do it in apisix       @moonming

**Comment by moonming** [comment]
@zuiyangqingzhou thanks for your explanation :) 
Apache APISIX itself does not provide such a feature. Apache APISIX has a mirror plug-in, but it does not do traffic replay.
I suggest you use external tool like tcpcopy
