### ISSUE TITLE
ci: unstable, random failures

### ISSUE THREAD

**Issue by membphis** [apache/apisix#7037]
### Current Behavior

<img width="906" alt="image" src="https://user-images.githubusercontent.com/6814606/168120331-2115e536-1528-4f52-9d2a-4a879276232d.png">

https://github.com/apache/apisix/runs/6407618978?check_suite_focus=true

### Expected Behavior

find the reason, it maybe a bug of code or test case

### Steps to Reproduce

https://github.com/apache/apisix/runs/6407618978?check_suite_focus=true

### Environment

master branch

**Comment by kwanhur** [comment]
It's more dependency on GitHub Actions and the organization related resource limitation.
