### ISSUE TITLE
help request: some error log when i use skywalking plugin

### ISSUE THREAD

**Issue by tcwloy** [apache/apisix#7039]
### Description

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/12730602/168206534-af16b34b-50a9-4e3d-b1f3-d10d903e7786.png">

After the skywalking plug-in is enabled, many errors appear in the log. The IP and port of the collector are open. I need help to analyze it

<img width="479" alt="image" src="https://user-images.githubusercontent.com/12730602/168207252-b326982d-218d-4cff-bcb5-8e83a8a5d80e.png">

### Environment

- APISIX version (run `apisix version`):2.12.1
- Operating system (run `uname -a`):Linux app-syn-server-06 3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):2.12.1
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners: skywalking
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
From the log, it was skywalking collector that closed the connection. I think you should check if your skywalking collector is working and make sure you have configured the correct endpoint_addr.

**Comment by tcwloy** [comment]
i resolved this problem. Because it is carelessly set as grpc port, you should use HTTP port
