### ISSUE TITLE
bug: /usr/local/apisix/apisix/cli/apisix.lua:31: module 'apisix.cli.env' not found

### ISSUE THREAD

**Issue by Hxhong** [apache/apisix#7044]
### Current Behavior

I run docker image with /bin/bash, but when apisix process is running and I restart the container, the second time i enter the container and start apisix, it failed...

### Expected Behavior

If I restart the container which is run with /bin/bash, the processes in container should be killed.

### Error Logs

The second time I enter the container, these are operations and errors：
1. start apisix: `apisix start`, but it failed, the error: 
`
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
APISIX is running...
`

2. restart apisix: apisix restart, but it failed, the error: 
`
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua restart
/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/apisix/cli/apisix.lua:31: module 'apisix.cli.env' not found:
	no field package.preload['apisix.cli.env']
	no file '/usr/local/apisix/deps/share/lua/5.1/apisix/cli/env.lua'
	no file './apisix/cli/env.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/cli/env.lua'
	no file '/usr/local/share/lua/5.1/apisix/cli/env.lua'
	no file '/usr/local/share/lua/5.1/apisix/cli/env/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env/init.lua'
	no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/apisix/deps/lib/lua/5.1/apisix/cli/env.so'
	no file './apisix/cli/env.so'
	no file '/usr/local/lib/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix.so'
	no file '/usr/local/apisix/deps/lib/lua/5.1/apisix.so'
	no file './apisix.so'
	no file '/usr/local/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/apisix/apisix/cli/apisix.lua:31: in main chunk
	[C]: at 0xaaaacc708690
`

### Steps to Reproduce

1. pull image: `docker pull apache/apisix:2.10.4-alpine`
2. start a container: `docker run -d -it -p 9080:9080 --name=apisix apache/apisix:2.10.4-alpine /bin/bash`
3. enter container: `docker exec -it apisix /bin/bash`
4. modify config.yaml
5. start apisix: `apisix start`, and I can access 'localhost:9080'
6. exit container: `exit`
7. restart container: `docker stop apisix`, `docker start apisix`
8. enter container: `docker exec -it apisix /bin/bash`
9. start apisix: `apisix start`, but it failed, the error: 
`
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
APISIX is running...`
10. restart apisix: apisix restart, but it failed, the error: 
`
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua restart
/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/apisix/cli/apisix.lua:31: module 'apisix.cli.env' not found:
	no field package.preload['apisix.cli.env']
	no file '/usr/local/apisix/deps/share/lua/5.1/apisix/cli/env.lua'
	no file './apisix/cli/env.lua'
	no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/cli/env.lua'
	no file '/usr/local/share/lua/5.1/apisix/cli/env.lua'
	no file '/usr/local/share/lua/5.1/apisix/cli/env/init.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env.lua'
	no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env/init.lua'
	no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/apisix/deps/lib/lua/5.1/apisix/cli/env.so'
	no file './apisix/cli/env.so'
	no file '/usr/local/lib/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/cli/env.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix.so'
	no file '/usr/local/apisix/deps/lib/lua/5.1/apisix.so'
	no file './apisix.so'
	no file '/usr/local/lib/lua/5.1/apisix.so'
	no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/apisix/apisix/cli/apisix.lua:31: in main chunk
	[C]: at 0xaaaacc708690
`

### Environment

- APISIX version (run `apisix version`): 2.10.4-alpine
- Operating system (run `uname -a`): macos Monterey 12.3.1
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.13
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
We cannot stop the APISIX process manually from within docker. You should control the container in the same way as docker.
I won't track this down for now, because the premise is wrong.
