### ISSUE TITLE
feat: As a user, I want to add support for Knative

### ISSUE THREAD

**Issue by hanf2x** [apache/apisix#7051]
### Description

Knative is a very commonly used serveless framework. 
![Competitors](https://cdn.thenewstack.io/media/2020/03/ba0c56f3-serverless2.png)

**Comment by bzp2010** [comment]
Hi, @encanto-oss, if you are interested in this, welcome to PR.

**Comment by encanto-oss** [comment]
Is there anybody else interested in this?

**Comment by RileySeaburg** [comment]
I am interested in this.

**Comment by tzssangglass** [comment]
> I am interested in this.

PR is welcome!

**Comment by vvavepacket** [comment]
I want this feature!

**Comment by tzssangglass** [comment]
> I want this feature!

have fun

**Comment by PasanBhanu** [comment]
I'm working on a plugin to support knative routing in the apisix through kourier (knative routing layer) 

If anyone landing here trying to figure-out how to change the host header dynamically, this might help you. 

[https://github.com/PasanBhanu/apisix-knative-kourier-routing-plugin](https://github.com/PasanBhanu/apisix-knative-kourier-routing-plugin)
