### ISSUE TITLE
help request: is there any way to get the upstream error in the plugin?

### ISSUE THREAD

**Issue by mygrsun** [apache/apisix#7056]
### Description

i want to get the upstream timeout error  in the plugin.beacuse i want to sent a json resonse to caller when the upstream is timeout.for example :
{"Response":{"RequestId":"123","Error":{"Message":"upstream timeout"}}}

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
It looks like you can only get a 502 status code in Apache APISIX. Maybe you can use [get_logs](https://github.com/openresty/lua-resty-core/blob/master/lib/ngx/errlog.md#get_logs) function to extract relevant information from the error log to determine `reset` or `timeout`, etc. I have not tested it, not sure if it is feasible.

**Comment by tzssangglass** [comment]
you can use this plugin: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/response-rewrite.md

the config maybe:

```json
{
                    "plugins": {
                        "response-rewrite": {
                            "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
                            "status_code": 502,
                            "vars": [
                                ["status","==",502]
                            ]
                        }
                    },
                    "upstream": {
                        "nodes": {
                            "127.0.0.1:1980": 1
                        },
                        "type": "roundrobin"
                    },
                    "uri": "/hello"
                }
```

just an example, please read the plugin document.

**Comment by mygrsun** [comment]
> you can use this plugin: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/response-rewrite.md
> 
> the config maybe:
> 
> ```json
> {
>                     "plugins": {
>                         "response-rewrite": {
>                             "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
>                             "status_code": 502,
>                             "vars": [
>                                 ["status","==",502]
>                             ]
>                         }
>                     },
>                     "upstream": {
>                         "nodes": {
>                             "127.0.0.1:1980": 1
>                         },
>                         "type": "roundrobin"
>                     },
>                     "uri": "/hello"
>                 }
> ```
> 
> just an example, please read the plugin document.

thank you
