### ISSUE TITLE
Is there any plugin can support saml2 auth ?

### ISSUE THREAD

**Issue by artemus717** [apache/apisix#7061]
### Description

I want to use saml2 protocal as an auth method. Thanks!

**Comment by starsz** [comment]
> Is there any plugin can support saml2 auth

I think we don't support it now.

**Comment by artemus717** [comment]
Is there some plan about this?

**Comment by starsz** [comment]
> Is there some plan about this?

As far as I know, there isn't.
If you are interested in, welcome to create PR on this excellent feature.
