### ISSUE TITLE
help request: grpc-transcode plugin can't proxy the grpc service

### ISSUE THREAD

**Issue by washCutBlow** [apache/apisix#7066]
### Description

报如下错误
^@^@2022/05/17 12:42:47 [error] 47#47: *1523366 [lua] util.lua:38: find_method(): compiled proto service not found, client: 172.22.0.1, server: _, request: "GET /grpcts HTTP/1.1", host: "meeting.cn"

我的配置
{
  "uri": "/grpcts",
  "name": "grpc-router-meeting",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "host": "meeting.cn",
  "plugins": {
    "grpc-transcode": {
      "disable": false,
      "method": "SayHello",
      "proto_id": "meeting.server",
      "service": "meeting.Greeter"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "172.31.19.238",
        "port": 45167,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "grpc",
    "pass_host": "pass"
  },
  "status": 1
}

<img width="639" alt="image" src="https://user-images.githubusercontent.com/26592450/168813560-a65bd30d-88ab-4705-adef-db872b3e0422.png">
有人能指点一下吗

**Comment by tzssangglass** [comment]
Unable to reproduce, the test case I used

```
BEGIN {
    if ($ENV{TEST_NGINX_CHECK_LEAK}) {
        $SkipReason = "unavailable for the hup tests";

    } else {
        $ENV{TEST_NGINX_USE_HUP} = 1;
        undef $ENV{TEST_NGINX_USE_STAP};
    }
}

use t::APISIX 'no_plan';

repeat_each(1);
no_long_string();
no_shuffle();
no_root_location();
log_level('debug');

run_tests;

__DATA__

=== TEST 1: set proto(id: 1)
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local etcd = require("apisix.core.etcd")
            local code, body = t('/apisix/admin/proto/1',
                 ngx.HTTP_PUT,
                 [[{
                    "content" : "syntax = \"proto3\";
                      package helloworld;
                      service Greeter {
                          rpc SayHello (HelloRequest) returns (HelloReply) {}
                      }
                      message HelloRequest {
                          string name = 1;
                      }
                      message HelloReply {
                          string message = 1;
                         }"
                   }]]
                )

            if code >= 300 then
                ngx.status = code
            end
            ngx.say(body)

            local res = assert(etcd.get('/proto/1'))
            local create_time = res.body.node.value.create_time
            assert(create_time ~= nil, "create_time is nil")
            local update_time = res.body.node.value.update_time
            assert(update_time ~= nil, "update_time is nil")

        }
    }
--- request
GET /t
--- response_body
passed
--- no_error_log
[error]



=== TEST 4: set routes(id: 1)
--- config
    location /t {
        content_by_lua_block {
            local t = require("lib.test_admin").test
            local code, body = t('/apisix/admin/routes/1',
                ngx.HTTP_PUT,
                [[{
                    "methods": ["GET", "POST"],
                    "uri": "/grpctest",
                    "plugins": {
                        "grpc-transcode": {
                            "proto_id": "1",
                            "service": "helloworld.Greeter",
                            "method": "SayHello"
                        }
                    },
                    "upstream": {
                        "scheme": "grpc",
                        "type": "roundrobin",
                        "nodes": {
                            "127.0.0.1:50051": 1
                        }
                    }
                }]]
            )

            if code >= 300 then
                ngx.status = code
            end
            ngx.say(body)
        }
    }
--- request
GET /t
--- response_body
passed
--- no_error_log
[error]



=== TEST 5: hit route
--- request
GET /grpctest?name=world
--- response_body eval
qr/\{"message":"Hello world"\}/
--- no_error_log
[error]
```

and using `t/grpc_server_example` under the APISIX repository as the grpc upstream, start the command as follows:

```
cd t/grpc_server_example

CGO_ENABLED=0 go build
./grpc_server_example \
    -grpc-address :50051 -grpcs-address :50052 -grpcs-mtls-address :50053 \
    -crt ../certs/apisix.crt -key ../certs/apisix.key -ca ../certs/mtls_ca.crt \
    > grpc_server_example.log 2>&1 || (cat grpc_server_example.log && exit 1)&

cd ../../
```

For example, I don't know what the `meeting` and `watch` folders are.

**Comment by washCutBlow** [comment]
我使用的是一个go micro v2启动的一个服务，是跟micro v2不兼容吗？您可以试一下，任何一个go micro v2框架的grpc服务

我使用micro call 都可以本地访问，但是接入网关就会报错

**Comment by washCutBlow** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/26592450/168944460-2a4b1b4f-17db-42e2-b1f7-8a9d569c6101.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/26592450/168944630-3880b116-afd4-42b9-855f-5172483244db.png">
我把服务名称改成了watch 忽略这个名字

**Comment by tzssangglass** [comment]
@bzp2010 @soulbird can you help this? I am not familiar with go.

**Comment by soulbird** [comment]
> @bzp2010 @soulbird can you help this? I am not familiar with go.

I will take a look

**Comment by tokers** [comment]
> compiled proto service not found

I don't think it's related to the go framework as it's an internal error in APISIX. It doesn't find the method.
