### ISSUE TITLE
help request: Can apisix route uri path by some target http header value?

### ISSUE THREAD

**Issue by jthann** [apache/apisix#7071]
### Description

We are using APISIX as gateway, in some scenarios，we need to route access uri or denied by client http request header value, for example：some access key value as http header，Currently in APISIX Route Object，there is filter_func mechanism to support extending filter logic， but the filter_func param is vars，we cannot get http header value from vars param.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> we cannot get http header value from vars param.

This is supported.

see: https://github.com/apache/apisix/discussions/6749#discussioncomment-2460105
