### ISSUE TITLE
As a user, I want to support multiple NGINX servers with different listening IP and port number

### ISSUE THREAD

**Issue by ochinchina** [apache/apisix#7077]
### Description

In the TELCOM area, The gateway host will join multiple LANs. Diffrent LAN will have different IP segment. So the Gateway host will have multiple IPs.

A NGINX Gateway needs to setup multiple http/tcp/udp servers. Each server will listen on its own IP and port number. Following is an example of a typical NGINX configuration in TELCOM area:

```NGINX
http {
...
  server {
      listen  10.0.0.1:8090;
      ....
  }

  server {
     listen 192.168.0.10:80;
     ....
    location /hello {
        proxy_pass http://hello-service;
    }

    location /foo {
       proxy_pass http://foo-service;
    }
  }
  ...
}
```

Is it possible for APISIX to expose NGINX server concept to user? and provide some APIs to operate the NGINX server. All the route, service... APIs can include an optional server-id in its request body to indicate the request is on a specific NGINX server.

And also is it possible to provide APIs to set NGINX parameter for the server and route...?

**Comment by soulbird** [comment]
You can add custom nginx configuration, refer here: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

**Comment by spacewander** [comment]
APISIX already supports using different listening IP & port?
https://github.com/apache/apisix/blob/260529a981e61ffa5db7c0750cfeb5a9b453c839/conf/config-default.yaml#L28

Or do you mean using different routes according to the IP & port?

**Comment by spacewander** [comment]
Maybe we can introduce an entry_id in the route. We can assign a unique entry_id to each IP&port, and only routes with the same entry_id will be used to match the traffic from an IP&port if an entry_id is assigned to it.

**Comment by ochinchina** [comment]
> 
I'd like the dynamic listening IP & port adding to the NGINX with APISIX API instead of pre-configure it in the config.yaml file. The route and services and upstream operations should be made under a specific NGINX server.
