### ISSUE TITLE
help request: CORS does not work on OPTIONS

### ISSUE THREAD

**Issue by endison1986** [apache/apisix#7082]
### Description

When I configured the advanced matching condition `env=dev` on Route and added the CORS plugin. Then I send a request through axios with the request header `env:dev`, then the browser initiates a preflight request `OPTIONS`, and I get a 404 return.

当我在Route上配置了高级匹配条件`env=dev`，并且添加了CORS插件后。然后我通过axios发送请求，并携带请求头`env:dev`，这时浏览器发起了一个预检请求`OPTIONS`，而我得到了一个404的返回。

![1652942235(1)](https://user-images.githubusercontent.com/7878324/169226393-998d98e7-c040-472a-b424-0b55006076ef.png)

### Environment

- APISIX version (run `apisix version`):2.12.1
- Operating system (run `uname -a`):Linux apisix-server-cd8564555-2njxg 3.10.0-514.26.2.el7.x86_64 # 1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by endison1986** [comment]
My understanding is that OPTIONS shouldn't apply advanced match conditions? But if the advanced matching conditions do not take effect, the same context cannot distinguish between routes.
我的理解是OPTIONS不应该应用高级匹配条件？但如果高级匹配条件不生效，相同的上下文就又无法区分路由了。

**Comment by spacewander** [comment]
Let's add OPTIONS to the route's methods when adding the CORS plugin.

> OPTIONS shouldn't apply advanced match conditions

We can't do it by default. Because if CORS plugin is not set,  there is no way to handle OPTIONS requests in APISIX. And it doesn't work well in the case that requests in different methods will be routed to different routes.

**Comment by endison1986** [comment]
`OPTIONS` is already in Route, but OPTIONS request without env responds with 404 due to adding advanced match condition `env=dev`.
I use HTTP request headers to distinguish different environments in the same context, but if OPTIONS cannot carry custom request headers, then I have to be careful with advanced match conditions?
Because this will cause APISIX to not be able to correctly distinguish the request target`OPTIONS`已经在Route中，但是由于添加了高级匹配条件`env=dev`导致没有env的OPTIONS请求响应了404.
我使用HTTP请求头在相同的上下文下区分不同的环境，但如果OPTIONS无法携带自定义请求头，那我不得不谨慎使用高级匹配条件？
因为这样将导致APISIX无法正确的分辨请求目标
------------------------------------------------------------------------------------------
I have an idea, I use APISIX+NACOS to discover services in my microservice environment, dev is actually the namespace in NACOS, the current namespace is fixed, if namesapce can pass the env in the HTTP request header as a parameter, Then I don't need to match different routes through env, so the number of routes is also reduced, and there is no need to configure a route for a namespace separately.
我有一个想法，我使用APISIX+NACOS在我的微服务环境中发现服务，dev实际上是NACOS中的namespace，目前的namespace是固定的，如果namesapce可以通过HTTP请求头中的env作为参数的话，那我就不需要通过env来匹配不同的路由了，这样路由的数量也变少了，不需要单独为一个namespace配置一个路由了
For example, configure like this:
比如象这样配置：
```json
{
  "timeout": {
    "connect": 30,
    "send": 30,
    "read": 30
  },
  "type": "roundrobin",
  "scheme": "http",
  "discovery_type": "nacos",
  "discovery_args": {
    "group_name": "DEFAULT_GROUP",
    "namespace_id": "${headers.env}"
  },
  "pass_host": "pass",
  "name": "user",
  "service_name": "user",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}
```

**Comment by spacewander** [comment]
> OPTIONS is already in Route, but OPTIONS request without env responds with 404 due to adding advanced match condition env=dev.

You can use `OR` syntax to include OPTIONS request without header: https://github.com/api7/lua-resty-expr#synopsis

> I have an idea, I use APISIX+NACOS to discover services in my microservice environment, dev is actually the namespace in NACOS, the current namespace is fixed, if namesapce can pass the env in the HTTP request header as a parameter, Then I don't need to match different routes through env, so the number of routes is also reduced, and there is no need to configure a route for a namespace separately.

It seems you can use the traffic-split plugin to select upstream dynamically instead of putting them to different routes.

**Comment by endison1986** [comment]
`OR` syntax may not meet my needs, because I have three environments, namely dev\test\prod, which are distinguished by the HTTP request header env

> `OR`可能无法满足我的需求，因为我有三个环境，分别是dev\test\prod，通过HTTP请求头env来区分

Thanks for your reply, I will try to implement dynamic selection of upstream using plugin `traffic-split`

> 谢谢你的答复，我将尝试使用插件`traffic-split`实现动态选择上游
