### ISSUE TITLE
help request: please check the version of OpenResty and lua, OpenResty 1.19 + LuaJIT or OpenResty before 1.19 + Lua 5.1 is required for Apache APISIX

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix#7098]
### Description

When I install APISIX via Source Release package according to this [link](https://apisix.apache.org/docs/apisix/how-to-build/).

I occurred to this issues: `please check the version of OpenResty and lua, OpenResty 1.19 + LuaJIT or OpenResty before 1.19 + Lua 5.1 is required for Apache APISIX`

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/43690894/169650923-6c038c87-000f-4ee0-9053-4dcf7ee36d9a.png">

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`): x86
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Chever-John** [comment]
This is solved by this PR: https://github.com/apache/apisix/pull/7067

we just changed APISIX's version to the latest.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.
