### ISSUE TITLE
help request: AWS ALB can't connect to apisix service node during traffic spikes

### ISSUE THREAD

**Issue by washCutBlow** [apache/apisix#7105]
### Description

我的apisix网关服务架构图如下：

AWS 全局加速器---->AWS ALB------>6台APISIX服务节点（部署在AWS的 4核8
G实例上）------>upstream节点。

但是每天在流量高峰时间点，会出现WS ALB无法连接到后端的apisix节点的目标连接数错误。请问应该如何调优呢？

<img width="818" alt="image" src="https://user-images.githubusercontent.com/26592450/169780950-38b3502d-3829-4229-a08f-b6e2ca5367f4.png">

我的AWS ALB的超时时间配置是100s。apisix的连接池超时时间是200s 连接池大小是1000. 并且nginx的连接数也配置的很大。

请问这是哪里的配置还需要优化吗？

我的apisix网关上配置了很多服务，服务的连接超时 几乎都很大，

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> 会出现WS ALB无法连接到后端的apisix节点的目标连接数错误

any error logs about this?

Although you described some of it, I still can't get the point. I can help you with a clear problem, but I can't solve things like optimization.
