### ISSUE TITLE
help request: Why is websocket not pushed in real time?

### ISSUE THREAD

**Issue by UpwardGrowth** [apache/apisix#7114]
### Description

Why is the websocket I configured not real-time, the one I configured with openresty is real-time, the websocket configured by apisix always pushes a batch of data after a period of time, note: the websocket I configured is to push data every second

My Apache APISIX is installed via Docker Compose

My format is like this:
{
  "uri": "/stream/*",
  "name": "stream_test",
  "priority": 5,
  "host": "www.website.com",
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "^/stream/*",
        "/$1"
      ]
    }
  },
  "upstream_id": "408937968976265927",
  "enable_websocket": true,
  "status": 1
}

### Environment

- APISIX version (run `apisix version`): 2.13.1-alpine
- Operating system (run `uname -a`): Linux aliyun-server 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.15
- APISIX Dashboard version, if relevant: 2.10.1-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by akalittle** [comment]
I'm facing the same problem while using the apisix with `proxy-rewrite` plugin.

**Comment by tzssangglass** [comment]
> I'm facing the same problem while using the apisix with `proxy-rewrite` plugin.

can you give a minimal reproduction of the use case?

**Comment by akalittle** [comment]
Sorry. It's my own problem. It works fine.
