### ISSUE TITLE
help request: stream_proxy seems not work

### ISSUE THREAD

**Issue by jamesislebron** [apache/apisix#7123]
### Description

 **apisix verison: 2.11
 config.yaml:**

<img width="953" alt="image" src="https://user-images.githubusercontent.com/20439714/170175612-b860a693-68ad-4e6e-8b64-956f5056b8f5.png">

**well,when I proxy 9100 to a http service like this:**

<img width="489" alt="image" src="https://user-images.githubusercontent.com/20439714/170175739-8afa6c73-5885-41c5-82d9-d5fc930e10ac.png">
<img width="689" alt="image" src="https://user-images.githubusercontent.com/20439714/170175758-abb4e466-2936-41b6-a9cc-4b8e723371f0.png">

**it works:**

<img width="544" alt="image" src="https://user-images.githubusercontent.com/20439714/170176062-873c443f-210a-43d0-8e5a-920d991e77ba.png">

**But when I proxy 9100 to a ssh service,it seems doesn't work:**

<img width="326" alt="image" src="https://user-images.githubusercontent.com/20439714/170176364-eb25a8e2-6bb8-496b-9634-53ca2f5b08b8.png">

<img width="799" alt="image" src="https://user-images.githubusercontent.com/20439714/170176338-fbdf61ba-56b9-4f9d-8a96-caee3494c41a.png">

### Environment

- APISIX version (2.11):
- Operating system (centos 7):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
Can you use nginx or openresty to verify that the proxy telnet is available?

From the logs you gave, it looks like the connection was established, but was closed for other reasons.

**Comment by jamesislebron** [comment]
> 

Em...

Well I try to change to another tcp upstream service without setting update and It works.

Maybe there is another error in my first failure example.

Thanks a lot !

**Comment by Chever-John** [comment]
@jamesislebron Hello, if you can, can you please tell me your configuration command? I don't think this is a detailed description(official doc).
