### ISSUE TITLE
bug: apisix2.9 one upstream node fail  all request return 502 

### ISSUE THREAD

**Issue by heming79** [apache/apisix#7125]
### Current Behavior

[root@yz-mbg-018203 ~]# curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80          
* About to connect() to proxy 192.168.7.204 port 80 (#0)
*   Trying 192.168.7.204...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.7.204 (192.168.7.204) port 80 (#0)
> GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: service-bmlt.wanzhuanmohe.cn
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 502 Bad Gateway
< Date: Wed, 25 May 2022 04:37:09 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 154
< Connection: keep-alive
< Server: APISIX/2.9
< X-APISIX-Upstream-Status: 502 : 
< 
{ [data not shown]
100   154  100   154    0     0  15837      0 --:--:-- --:--:-- --:--:-- 17111
* Connection #0 to host 192.168.7.204 left intact

去掉问题节点 马上就恢复200状态 
[root@yz-mbg-018203 ~]# curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80 
* About to connect() to proxy 192.168.7.204 port 80 (#0)
*   Trying 192.168.7.204...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 192.168.7.204 (192.168.7.204) port 80 (#0)
> GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1
> User-Agent: curl/7.29.0
> Host: service-bmlt.wanzhuanmohe.cn
> Accept: */*
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 
< Content-Type: application/json;charset=utf-8
< Content-Length: 42
< Connection: keep-alive
< Date: Wed, 25 May 2022 04:41:19 GMT
< Server: APISIX/2.9
< 
{ [data not shown]
100    42  100    42    0     0   8552      0 --:--:-- --:--:-- --:--:-- 10500

### Expected Behavior

只要有一个可用的upstream node ，就应该 返回200 状态 。 
nginx就可以 proxy_next_upstream  http_404 http_500 http_502 http_503 http_504 error timeout invalid_header;.
应该参考 nginx的 /nstatus  方便运维快速查看、监控所有upstream后端node的 健康状态 。  
另外如果 discovery 能支持etcd 要是能像traefik那样 获取k8s service关联的pod地址:端口号 就完美了 。
![Uploading image.png…]()

### Error Logs

我上午起过两个apisix 出现etcd 连接600多个导致 etcd 不可用的情况 。
/usr/local/apisix/logs # tail -f error.log 
2022/05/25 02:27:30 [error] 63#63: *304 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer
2022/05/25 02:27:30 [error] 57#57: *239 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer
2022/05/25 02:27:31 [error] 50#50: *49 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer
2022/05/25 02:27:31 [error] 44#44: *77 [lua] config_etcd.lua:563: no healthy etcd endpoint available, next retry after 4s, context: ngx.timer
不知道什么原因 日志一直在切割归档，而不是整点才切割归档。 
-rw-r--r--    1 root     root         334 May 25 04:00 2022-05-25_03-00-00__error.log.tar.gz
-rw-r--r--    1 root     root         124 May 25 04:39 2022-05-25_04-00-00__access.log.tar.gz
-rw-r--r--    1 root     root         261 May 25 04:39 2022-05-25_04-00-00__error.log.tar.gz
-rw-r--r--    1 nobody   root           0 May 25 04:39 access.log
-rw-r--r--    1 nobody   root           0 May 25 04:39 error.log
-rw-r--r--    1 root     root           2 May 25 02:42 nginx.pid

### Steps to Reproduce

1、run apisix docker ， dashboard docker 
2、create  upstream  
{
  "nodes": [
    {
      "host": "192.168.6.51",
      "port": 20730,
      "weight": 1
    },
    {
      "host": "192.168.6.54",
      "port": 20730,
      "weight": 1
    },
    {
      "host": "192.168.6.54",
      "port": 20731,
      "weight": 1
    },
    {
      "host": "192.168.6.93",
      "port": 20730,
      "weight": 1
    },
    {
      "host": "192.168.6.93",
      "port": 20731,
      "weight": 1
    }
  ],
  "retries": 4,
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "checks": {
    "active": {
      "concurrency": 10,
      "healthy": {
        "http_statuses": [
          200,
          302
        ],
        "interval": 1,
        "successes": 2
      },
      "http_path": "/",
      "port": 80,
      "timeout": 1,
      "type": "http",
      "unhealthy": {
        "http_failures": 5,
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "interval": 1,
        "tcp_Failures": 2,
        "timeouts": 3
      }
    },
    "passive": {
      "healthy": {
        "http_statuses": [
          200,
          201,
          202,
          203,
          204,
          205,
          206,
          207,
          208,
          226,
          300,
          301,
          302,
          303,
          304,
          305,
          306,
          307,
          308
        ],
        "successes": 5
      },
      "type": "http",
      "unhealthy": {
        "http_failures": 2,
        "http_statuses": [
          429,
          500,
          503
        ],
        "tcp_failures": 2,
        "timeouts": 7
      }
    }
  },
  "scheme": "http",
  "pass_host": "pass",
  "name": "service-bmlt\t",
  "desc": "cbd 百亩良田游戏api接口",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  },
  "retry_timeout": 2
}
3、create route  
{
  "uri": "/*",
  "name": "service-bmlt.wanzhuanmohe.cn",
  "methods": [
    "GET",
    "POST"
  ],
  "host": "service-bmlt.wanzhuanmohe.cn",
  "upstream_id": "409123196135021008",
  "status": 1
}
4、curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80   OK
5、通过dashboard 新增一个不可达的node 到upstream里 
    {
      "host": "192.168.6.91",
      "port": 20731,
      "weight": 1
    },
6、curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80   502 

### Environment

- APISIX version (run `apisix version`):2.9
- Operating system (run `uname -a`):centos7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.19.3.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15 
- APISIX Dashboard version, if relevant:2.8.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):3.7.0

**Comment by membphis** [comment]
> 1、run apisix docker ， dashboard docker
> 2、create upstream
> 3、create route
> 4、curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80 OK
> 5、add upstream node （no availabe ）
> 6、curl -voax service-bmlt.wanzhuanmohe.cn -x 192.168.7.204:80 502

can you provide the detail information about `2`, `3`, `5`? many thx

**Comment by gxthrj** [comment]
I tried with APISIX 2.9 and etcd 3.5 and found no such problem.
Use `httpbin.org` as upstream.

```
# curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/ip",
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "httpbin.org": 1
>         }
>     }
> }'
```

and then I add `127.0.0.1:80` which is not exist.

```
# curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/ip",
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "httpbin.org": 1,
>             "127.0.0.1:80": 1
>         }
>     }
> }'
```

The result is OK.

```
# curl http://127.0.0.1:9080/ip
{
  "origin": "10.100.0.1"
}
```

**Comment by gxthrj** [comment]
I hope you can provide the error log, when APISIX returns 502.

**Comment by heming79** [comment]
升级到 2.13.1之后 好很多了 。 偶尔还是会出现 502 不尝试next upstream的情况 。  
![image](https://user-images.githubusercontent.com/14069019/170232142-5386b94e-f8c4-4397-89bd-efa8443a3fa1.png)

**Comment by soulbird** [comment]
I noticed that you actually have two problems here:
1. Unhealthy nodes are not removed
2. From the log, it seems that there is no retry after the upstream returns 502

Regarding the first question, because you have configured checks.active.port to 80, healthcheck will use this port first when performing health checks.
If your upstream does not have port 80, this will cause apisix to determine that all your upstream services are unhealthy, and then use the default nodes (all configured nodes) for back-to-origin
It looks like apisix didn't kick out any unhealthy nodes.
If you look at the error_log, you should see something like this: `all upstream nodes is unhealthy, use default`.
So you should remove the `port:80` configuration. In addition, it is best to add 502 status code to the `checks.unhealthy.http_statuses` configuration

The second problem seems to be unexpectedly exiting in the process of retrying. I noticed that you configured `retry_timeout: 2`, if the network fluctuates and the first node is connected for more than 2s, then the next node will not have a chance to be retried.
Refer to this code: https://github.com/apache/apisix/blob/master/apisix/balancer.lua#L346-L350. If you can provide me with an errorlog, I will be able to confirm if this is the case.

**Comment by moonming** [comment]
> If your upstream does not have port 80, this will cause apisix to determine that all your upstream services are unhealthy, and then use the default nodes (all configured nodes) for back-to-origin
> It looks like apisix didn't kick out any unhealthy nodes.

In short, is this a bug in Apache APISIX?

**Comment by soulbird** [comment]
> > If your upstream does not have port 80, this will cause apisix to determine that all your upstream services are unhealthy, and then use the default nodes (all configured nodes) for back-to-origin
> > It looks like apisix didn't kick out any unhealthy nodes.
> 
> In short, is this a bug in Apache APISIX?

I thinke it's not. But if the dashboard forces  `port` to be configured, that's a problem, I'll reconfirm this.

**Comment by moonming** [comment]
> > > If your upstream does not have port 80, this will cause apisix to determine that all your upstream services are unhealthy, and then use the default nodes (all configured nodes) for back-to-origin
> > > It looks like apisix didn't kick out any unhealthy nodes.
> > 
> > 
> > In short, is this a bug in Apache APISIX?
> 
> I think it's not. But if the dashboard forces `port` to be configured, that's a problem, I'll reconfirm this.

I am confused. In any case, one upstream failure cannot affect other upstreams.

**Comment by heming79** [comment]
sometime still have 502 :
192.168.7.203 - - [26/May/2022:01:52:51 +0000] service-bmlt.wanzhuanmohe.cn "GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1" 502 154 0.002 "-" "curl/7.29.0" 192.168.6.91:20730 :  502 :  0.001 :  "http://service-bmlt.wanzhuanmohe.cn"

[root@yz-mbg-018204 logs]# tail -n 200 2022-05-26_02-00-00__error.log |grep "pick server"
2022/05/26 01:52:48 [error] 63#63: *21976125 [lua] balancer.lua:327: run(): failed to pick server: failed to find valid upstream server, all upstream servers tried while connecting to upstream, client: 192.168.7.203, server: _, request: "GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1", upstream: "http://192.168.6.91:20730/", host: "service-bmlt.wanzhuanmohe.cn"
2022/05/26 01:52:50 [error] 51#51: *21976772 [lua] balancer.lua:327: run(): failed to pick server: failed to find valid upstream server, all upstream servers tried while connecting to upstream, client: 192.168.7.203, server: _, request: "GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1", upstream: "http://192.168.6.91:20730/", host: "service-bmlt.wanzhuanmohe.cn"
2022/05/26 01:52:51 [error] 46#46: *21976925 [lua] balancer.lua:327: run(): failed to pick server: failed to find valid upstream server, all upstream servers tried while connecting to upstream, client: 192.168.7.203, server: _, request: "GET HTTP://service-bmlt.wanzhuanmohe.cn/ HTTP/1.1", upstream: "http://192.168.6.91:20730/", host: "service-bmlt.wanzhuanmohe.cn"

**Comment by heming79** [comment]
可能还是因为老版本dashboard 导致后端检测用了默认port:80 ， 当时其他节点都不可用只有192.168.6.91:20730 主动检测可用 ，实际被动检测502 ，所以就没有尝试别的节点 （主动检测异常的节点此时是不允许尝试的 ，/v1/healthycheck 目前不稳定所以我看不到后端健康检测实际情况 无法做出明确判断）。 应该不是bug

**Comment by mojerro** [comment]
我也遇到了这个问题，是线上环境，突然出现好几个接口502了，都是不常用的或者新建的接口。而且刚开始都是好的，直接访问端口也是畅通的。

现在我看access log和error log都很正常，返回502的接口好像没有单独的日志
@heming79 大佬方便到时候远程看看吗

**Comment by tzssangglass** [comment]
> 现在我看access log和error log都很正常，返回502的接口好像没有单独的日志
> @heming79 大佬方便到时候远程看看吗

Can you reproduce it?

**Comment by mojerro** [comment]
> > 现在我看access log和error log都很正常，返回502的接口好像没有单独的日志
> > @heming79 大佬方便到时候远程看看吗
> 
> Can you reproduce it?

yes, it still return 502 on my server now

**Comment by mojerro** [comment]
@heming79 老哥，你开启http2了吗，我这边这两天研究了一下，还重新部署了一遍，发现开启http2之后，所有1.1的请求都直接502且无error log

**Comment by tzssangglass** [comment]
Can you provide the reproduction steps? So that I can reproduce it locally.

**Comment by mojerro** [comment]
> Can you provide the reproduction steps? So that I can reproduce it locally.

@tzssangglass sorry for the late reply. Here are the steps.

1. enable `enable_http2: true` in `node_listen`
2. start the apisix
3. all requests with h1.1 will return 502 directly. You can deploy [penpot](https://help.penpot.app/technical-guide/getting-started/) and access it through apisix which will get this error.

**Comment by tzssangglass** [comment]
> @tzssangglass sorry for the late reply. Here are the steps.
> 
> 1. enable `enable_http2: true` in `node_listen`
> 2. start the apisix
> 3. all requests with h1.1 will return 502 directly. You can deploy [penpot](https://help.penpot.app/technical-guide/getting-started/) and access it through apisix which will get this error.

I cannot be reproduced.

my step:

`config.yaml`:

```
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
  node_listen:
    - port: 9080
      enable_http2: true
```

route config:

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/get",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:80": 1
        }
    }
}'
```


test:

```
curl http://127.0.0.1:9080/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1",
    "User-Agent": "curl/7.79.1",
    "X-Amzn-Trace-Id": "Rxxxxxx",
    "X-Forwarded-Host": "127.0.0.1"
  },
  "origin": "xxxxxx",
  "url": "http://127.0.0.1/get"
}
```

**Comment by mojerro** [comment]
@tzssangglass I reproduce it again, if I enable http2, then it returns 502 with no error log as blow.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/15071824/196078796-0efa41ee-6aa3-45f3-b790-d7c462919ca4.png">
<img width="421" alt="image" src="https://user-images.githubusercontent.com/15071824/196078950-dfb3df78-01b3-4817-a92a-15c7c0489c95.png">

If I close it and recreate the docker container, it runs well.

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/15071824/196079080-8407e7ef-2845-4f0f-8a3c-89b8b8bf663a.png">

**Comment by mojerro** [comment]
for common errors with cannot access upstream services, apisix usually return like this
<img width="340" alt="image" src="https://user-images.githubusercontent.com/15071824/196080300-7e0611f8-72a3-4b52-88e3-766674146124.png">

**Comment by tzssangglass** [comment]
> I reproduce it again, if I enable http2, then it returns 502 with no error log as blow.
> If I close it and recreate the docker container, it runs well.

It looks like you're deploying with docker, I'm wondering how you turned http2 on or off? Modify the config file and rebuild the APISIX docker?

> And I find one more thing, even with http2 = false, web can also use h2 proto

This is just a web page that shows that it uses the http2 protocol, it does not mean that APISIX actually handles the http2 protocol. In general, we focus on the `/usr/loca/apisix/conf/nginx.conf`.

if you enable http2 in `config.yaml` like:

```yaml
apisix:
  node_listen:
    - port: 9080
      enable_http2: true
```

 the `/usr/loca/apisix/conf/nginx.conf` mabe have `http2` like:

```nginx
    server {
        listen 0.0.0.0:9080 default_server http2 reuseport;

```

**Comment by mojerro** [comment]
> It looks like you're deploying with docker, I'm wondering how you turned http2 on or off? Modify the config file and rebuild the APISIX docker?

My command shows below, and my env file is in `./config/apisix_config.yml`

```sh
# start apisix
docker compose -p apisix up -d

# down apisix
docker compose -p apisix down
```

Thanks for your explanation.

**Comment by mojerro** [comment]
here is the `docker-compose.yml`
```yml
  apisix:
    image: apache/apisix:2.15.0-alpine
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./config/apisix_conf.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ##network_mode: host
    ports:
      - "80:80/tcp"
      - "39091:9091/tcp"
      - "443:443/tcp"
      - "39180:9180/tcp"
```

**Comment by tzssangglass** [comment]
after you enable http2 in `./config/apisix_conf.yaml`, can you show the `/usr/loca/apisix/conf/nginx.conf` in docker, like:

```
    server {
        listen 0.0.0.0:9080 
```

and if 502 appears, what are the error logs?

**Comment by mojerro** [comment]
@tzssangglass if 502 appears, there is nothing in `error.logs` and docker logs.

`/usr/loca/apisix/conf/nginx.conf`

```conf
    server {
        listen 0.0.0.0:9080 default_server http2 reuseport;
        listen 0.0.0.0:9443 ssl default_server http2 reuseport;

        server_name _;

        ssl_certificate      cert/ssl_PLACE_HOLDER.crt;
        ssl_certificate_key  cert/ssl_PLACE_HOLDER.key;
        ssl_session_cache    shared:SSL:20m;
        ssl_session_timeout 10m;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_prefer_server_ciphers on;
        ssl_session_tickets off;


        # http server configuration snippet starts
        
        # http server configuration snippet ends

        location = /apisix/nginx_status {
            allow 127.0.0.0/24;
            deny all;
            access_log off;
            stub_status;
        }


        ssl_certificate_by_lua_block {
            apisix.http_ssl_phase()
        }

        proxy_ssl_name $upstream_host;
        proxy_ssl_server_name on;

        location / {
            set $upstream_mirror_uri         '';
            set $upstream_upgrade            '';
            set $upstream_connection         '';

            set $upstream_scheme             'http';
            set $upstream_host               $http_host;
            set $upstream_uri                '';
            set $ctx_ref                     '';
            set $from_error_page             '';


            # http server location configuration snippet starts
            
            # http server location configuration snippet ends


            access_by_lua_block {
                apisix.http_access_phase()
            }

            proxy_http_version 1.1;
            proxy_set_header   Host              $upstream_host;
            proxy_set_header   Upgrade           $upstream_upgrade;
            proxy_set_header   Connection        $upstream_connection;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_pass_header  Date;

            ### the following x-forwarded-* headers is to send to upstream server

            set $var_x_forwarded_for        $remote_addr;
            set $var_x_forwarded_proto      $scheme;
            set $var_x_forwarded_host       $host;
            set $var_x_forwarded_port       $server_port;

            if ($http_x_forwarded_for != "") {
                set $var_x_forwarded_for "${http_x_forwarded_for}, ${realip_remote_addr}";
            }
            if ($http_x_forwarded_host != "") {
                set $var_x_forwarded_host $http_x_forwarded_host;
            }
            if ($http_x_forwarded_port != "") {
                set $var_x_forwarded_port $http_x_forwarded_port;
            }

            proxy_set_header   X-Forwarded-For      $var_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto    $var_x_forwarded_proto;
            proxy_set_header   X-Forwarded-Host     $var_x_forwarded_host;
            proxy_set_header   X-Forwarded-Port     $var_x_forwarded_port;

            ###  the following configuration is to cache response content from upstream server

            set $upstream_cache_zone            off;
            set $upstream_cache_key             '';
            set $upstream_cache_bypass          '';
            set $upstream_no_cache              '';

            proxy_cache                         $upstream_cache_zone;
            proxy_cache_valid                   any 10s;
            proxy_cache_min_uses                1;
            proxy_cache_methods                 GET HEAD POST;
            proxy_cache_lock_timeout            5s;
            proxy_cache_use_stale               off;
            proxy_cache_key                     $upstream_cache_key;
            proxy_no_cache                      $upstream_no_cache;
            proxy_cache_bypass                  $upstream_cache_bypass;


            proxy_pass      $upstream_scheme://apisix_backend$upstream_uri;

            mirror          /proxy_mirror;

            header_filter_by_lua_block {
                apisix.http_header_filter_phase()
            }

            body_filter_by_lua_block {
                apisix.http_body_filter_phase()
            }

            log_by_lua_block {
                apisix.http_log_phase()
            }
        }
```

**Comment by mojerro** [comment]
you can visit http://design.ux.mojerro.wang/ and have a look at 502 page

**Comment by tzssangglass** [comment]
> you can visit [http://design.ux.mojerro.wang](http://design.ux.mojerro.wang/) and have a look at 502 page

my route

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/hello",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "design.ux.mojerro.wang:80": 1
        }
    }
}'
```

and test

```
curl --http2-prior-knowledge "http://127.0.0.1:9080/hello" -vso /dev/null

*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /hello]
* h2h3 [:scheme: http]
* h2h3 [:authority: 127.0.0.1:9080]
* h2h3 [user-agent: curl/7.84.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x2092f10)
> GET /hello HTTP/2
> Host: 127.0.0.1:9080
> user-agent: curl/7.84.0
> accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 000
< date: Tue, 18 Oct 2022 05:10:47 GMT
< server: APISIX/2.99.0
<
{ [57 bytes data]
* Connection #0 to host 127.0.0.1 left intact
```

I think this means that APISIX has successfully proxied the http2 request

**Comment by mojerro** [comment]
@tzssangglass I think there may some difference between web browser and pure http request? you can see that the browser return 502 when it request as http1.1 
![](https://user-images.githubusercontent.com/15071824/196078796-0efa41ee-6aa3-45f3-b790-d7c462919ca4.png)

**Comment by tzssangglass** [comment]
> think there may some difference between web browser and pure http request? you can see that the browser return 502 when it request as http1.1

I don't have a better idea, you can grab the network packet sent by the browser

**Comment by mojerro** [comment]
> > think there may some difference between web browser and pure http request? you can see that the browser return 502 when it request as http1.1
> 
> I don't have a better idea, you can grab the network packet sent by the browser

OK, I will have a try.

Anyway, thanks for your reply~
