### ISSUE TITLE
docs: stream_proxy docs test case is 404 (version: 2.11)

### ISSUE THREAD

**Issue by jamesislebron** [apache/apisix#7126]
### Current State

stream_proxy docs test case is 404 (version: 2.11)

URL: https://625a9090d04b9a6953165811--2-11-old-docs-apache-apisix.netlify.app/t/stream-node/sanity.t

![image](https://user-images.githubusercontent.com/20439714/170196264-2d03bb62-ec90-493d-b391-b4cecccab2f0.png)

![image](https://user-images.githubusercontent.com/20439714/170196298-77920be5-efaa-4dc2-b536-88bb6a3ed784.png)

### Desired State

give some case or nothing

**Comment by SkyeYoung** [comment]
> Hi @SkyeYoung, could you please have a check?

@juzhiyuan This file should not exist, it indexes the test files in this repository.

**Comment by SkyeYoung** [comment]
@jamesislebron Hi, if you want to check it, pls click https://github.com/apache/apisix/blob/release/2.11/t/stream-node/sanity.t

**Comment by juzhiyuan** [comment]
Hi @jamesislebron @SkyeYoung, this issue has been fixed in the latest docs, refer to https://apisix.apache.org/docs/apisix/stream-proxy/
