### ISSUE TITLE
sls-logger plugin support custom log format like the other logger

### ISSUE THREAD

**Issue by jinghuaz** [apache/apisix#7129]
### Description

sls-logger plugins Can the request header field not be uploaded? for example:cookie，authorization...

**Comment by jinghuaz** [comment]
![image](https://user-images.githubusercontent.com/9525903/170249679-4823997e-314e-4524-926b-aa0a1f7f2e8b.png)

**Comment by tokers** [comment]
> Maybe we can make `sls-logger` support `log_format`?

That' a good idea.

**Comment by jinghuaz** [comment]
Hi,remember to notify or update the status of any updates.
