### ISSUE TITLE
docs: response-rewrite plugin support for regular expressions

### ISSUE THREAD

**Issue by NMichas** [apache/apisix#7130]
### Current State

`response-rewrite` plugin supports regular expressions, however the current doc page (https://apisix.apache.org/docs/apisix/plugins/response-rewrite) does not reflect that.

### Desired State

Provide additional documentation/examples, showing the use of regular expressions. It would be beneficial if examples also showcase how multiple replacements for the same request can be performed, i.e.
<a href="/'>  -> <a href="/some-other-path'>
<img src="/a.png'> -> <img src="/some-other-path-a.png'>

**Comment by spacewander** [comment]
PR is welcome!
