### ISSUE TITLE
feat: Add a hook or snippet for `exit_worker`

### ISSUE THREAD

**Issue by HashidaTKS** [apache/apisix#7131]
### Description

Hope to add a hook or snippet for `exit_worker`.

Currently, the `exit_worker` hook is not executed even if writing such a function in plugins.

```
function _M.exit_worker()
  core.log.info("exit_worker")
end
```

Also, `config.yaml` seems to have no snippet to change a content of the `exit_worker_by_lua*` directive created by `ngx_tpl.lua`.

https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L429

I think only a few users do something in the `exit_worker` directive, but I think it is useful for the users.

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/blob/6063f334098a93e10d603c156ea7d9a217e95f62/apisix/init.lua#L153-L155

Implemented, but not open to plugin development architecture.

> I think only a few users do something in the exit_worker directive, but I think it is useful for the users.

I think it's OK. Let's hear what others think.

**Comment by spacewander** [comment]
@HashidaTKS 
Could you provide some use cases of using exit_worker in a plugin?

**Comment by HashidaTKS** [comment]
>  Could you provide some use cases of using exit_worker in a plugin?

For example, starting a new daemon / background process to support the processing of a worker_process in the `init_worker` phase, and stopping it in the `exit_worker` phase.
Although, I feel like this is not a good usage...

**Comment by tzssangglass** [comment]
> For example, starting a new daemon / background process to support the processing of a worker process in the `init_worker` phase, and stopping it in the `exit_worker` phase.

This does not require the use of `exit_worker`, there is a `destroy` phase in the plugin development architecture for unloading plugins.

https://github.com/apache/apisix/blob/ef9ba91a601d400ef4d43e0dd3378f1d98c3b7d9/apisix/plugins/example-plugin.lua#L71-L73

In my experience, `exit_worker` is mainly used to clean up resources.

**Comment by HashidaTKS** [comment]
> This does not require the use of exit_worker, there is a destroy phase in the plugin development architecture for unloading plugins.

I didn't know that, thanks!

Since the `destroy` phase exists, I feel like it's okay without the `exit_worker` phase in a plugin.

**Comment by tzssangglass** [comment]
considered as solved, feel free to reopen this if you need.
