### ISSUE TITLE
help request: too many etcd connection to the apisix, does this normal?

### ISSUE THREAD

**Issue by washCutBlow** [apache/apisix#7132]
### Description

<img width="963" alt="image" src="https://user-images.githubusercontent.com/26592450/170387087-d2675900-6c58-4f7e-bd9d-c18cd32a6a31.png">

in my system, there are six apisix node, and a etcd cluster which include 3 node.  i found that the connection count is too more does this normal? 

i think this may be cause a question that ,when the traffic is large, may aws alb can't connect to my apisix node

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
How many worker processes in an APISIX node?

**Comment by tzssangglass** [comment]
etcd connections = apisix instances number * worker process number of each apisix instance * 13

**Comment by kwanhur** [comment]
> etcd connections = apisix instances number * worker process number of each apisix instance * 13

Take me the curious, where's the `13` from? Any document describes about it? @tzssangglass

**Comment by tokers** [comment]
> > etcd connections = apisix instances number * worker process number of each apisix instance * 13
> 
> Take me the curious, where's the `13` from? Any document describes about it? @tzssangglass

`13` resources (route, upstream, ...)

**Comment by kwanhur** [comment]
Thanks very much for @tokers .

From etcd, I found resources should be include

1. `/apisix/consumers/`
2. `/apisix/gen_id`
3. `/apisix/global_rules/`
4. `/apisix/plugin_configs/`
5. `/apisix/plugin_metadata/`
6. `/apisix/plugins/`
7. `/apisix/proto/`
8. `/apisix/routes/`
9. `/apisix/services/`
10. `/apisix/ssl/`
11. `/apisix/stream_routes/`
12. `/apisix/upstreams/`

**Comment by tzssangglass** [comment]
and `server-info` plugin would use `/apisix/data_plane/` by default
