### ISSUE TITLE
help request: upgrade to 2.14.0 after the route matching error, adjust the priority also did not solve, back to 2.13.1 on the normal

### ISSUE THREAD

**Issue by bingoku** [apache/apisix#7136]
### Description

 升级到 2.14.0 后路由匹配错乱，调整优先级也无解，回退到 2.13.1就正常了

不知道如何查询这个问题，求解。
 

### Environment

apisix version：apache/apisix:2.14.0-centos

**Comment by tzssangglass** [comment]
Your description does not provide valid information and I need detailed reproduction steps to be able to reproduce this issue locally.

**Comment by bingoku** [comment]
> 

<img width="702" alt="image" src="https://user-images.githubusercontent.com/4134788/170431990-f0c78e0d-e192-4ba4-ae76-73707363d45e.png">

其实我没做什么调整，这个图就是现在的路由规划。升级到2.14就乱了。回退到 2.13 是正常的，你说的复现步骤，恐怕不知道怎么给你们展示了。

**Comment by lemonrains** [comment]
I'm also get the similar error after upgrade to 2.14.0, and get normal if I downgrade the version to 2.13.1.

I got the error of the route which enabled  plugin openid-connect(base on keycloak) . And it  always redirect to uri  `/auth`.
Such as xxxx.xx.com/auth

**Comment by tzssangglass** [comment]
> 其实我没做什么调整，这个图就是现在的路由规划。升级到2.14就乱了

Is this image your own dashborad? I'd like to know what you mean by chaos

**Comment by tzssangglass** [comment]
> I got the error of the route which enabled plugin openid-connect(base on keycloak) . And it always redirect to uri `/auth`.
> Such as xxxx.xx.com/auth

Your problem is not related to this issue, please submit a new issue and give the steps to reproduce it.

**Comment by tokers** [comment]
Also, some descriptions about the disorder of route matching are desired, so that we can know a request that should hit route A hits route B.

**Comment by lemonrains** [comment]
> > I got the error of the route which enabled plugin openid-connect(base on keycloak) . And it always redirect to uri `/auth`.
> > Such as xxxx.xx.com/auth
> 
> Your problem is not related to this issue, please submit a new issue and give the steps to reproduce it.

Thank you for your reply. Finally I config response-rewrite plugin in order to redirect to `/`. Maybe it's my mistake, I'll check it later if it's relate to the new version.

**Comment by bingoku** [comment]
> 

你看上图我的规划路由 A 本来应该访问到 B，但是会访问到了 C D E 感觉像是 host 没匹配到。
我尝试过 指定service 的 host、router 的host，以及他们的优先级都没有解决 2.14 中的错乱。

经过上述操作后，我回滚2.13.1后就恢复正常了。

**Comment by tokers** [comment]
> > 
> 
> 你看上图我的规划路由 A 本来应该访问到 B，但是会访问到了 C D E 感觉像是 host 没匹配到。 我尝试过 指定service 的 host、router 的host，以及他们的优先级都没有解决 2.14 中的错乱。
> 
> 经过上述操作后，我回滚2.13.1后就恢复正常了。

This is useless for troubleshooting. Could you show some configs for us so that we can reproduce it?

**Comment by bingoku** [comment]
> > > 
> > 
> > 
> > 你看上图我的规划路由 A 本来应该访问到 B，但是会访问到了 C D E 感觉像是 host 没匹配到。 我尝试过 指定service 的 host、router 的host，以及他们的优先级都没有解决 2.14 中的错乱。
> > 经过上述操作后，我回滚2.13.1后就恢复正常了。
> 
> This is useless for troubleshooting. Could you show some configs for us so that we can reproduce it?

如何提供更多信息？有其它沟通方式吗？微信什么，我这边是 100% 可与复现。

**Comment by badx** [comment]
I'm also get the similar error after upgrade to 2.14.1, and get normal if I downgrade the version to 2.13.1.
I checked the config by etcd and it looks like the config is correct.
I deleted all the configuration and added a new route, the problem still exists
I suspect the problem is caused by the upgrade.

**Comment by tokers** [comment]
@spacewander @tzssangglass Do you have any idea about this?

**Comment by tzssangglass** [comment]
> @spacewander @tzssangglass Do you have any idea about this?

I've gathered similar information from other channels, but there is no reproducible demo, and I've noticed one detail: one of the steps is to migrate etcd data.

**Comment by Fatpa** [comment]
We also get the similar error after upgrading to 2.14.1 from 2.11. 
According to the error logs, I found that some of the queries is mismatched the route when high concurrency simulation (about 600 qps), and got 302 / 400 / 404, etc status code.
At the same time, we make some tests in different versions, 2.13.1 works well but not 2.13.2.

We don't migrate etcd data but just enable etcd tls.

**Comment by tzssangglass** [comment]
Hi @Fatpa , can you provide a complete reproducible step-by-step? This is important for us to solve this problem.

**Comment by Fatpa** [comment]
> 

Would you like to talk on slack or WeChat? Our production environment is a bit complex, and I can't show much here.

**Comment by tzssangglass** [comment]
ok, I will check this issue and #7449 together.

**Comment by tzssangglass** [comment]
from: https://github.com/apache/apisix/issues/7449#issuecomment-1186745379

Can you give the content and header of the response when a 302 / 400 / 404 status code appears?

**Comment by tzssangglass** [comment]
> * downgrade the version back to 2.13.2, still getting same 302 / 400 / 404 status code

and the error logs related to it

**Comment by iori0758** [comment]
the route matching wrong did happen on my server,Maybe caused by etcd's connection is too many,now i changed etcd version to 3.4.20, it is normal so far
https://github.com/etcd-io/etcd/issues/14185
https://github.com/etcd-io/etcd/pull/14081
but 404 status still appear sometime,it just happed on high concurrency situation

apisix:2.14.1
etcd:3.4.20

路由错乱我前几天也碰到过，之前排查原因估计是etcd连接数超过250，导致curl带tls证书请求缓慢，所以我更换了etcd版本到3.4.20，目前1个星期了为止还没有复现
但目前还是会碰到偶见404，在高并发的场景有一些js和html会出现404，apisix显示请求到后台了，但后台nginx没有打印该请求日志，貌似请求到别的地方了
然后还有一个场景是变更apisix-dashboard的时候，偶尔会出现请求403

**Comment by tzssangglass** [comment]
> 路由错乱我前几天也碰到过，之前排查原因估计是etcd连接数超过250，导致curl带tls证书请求缓慢，所以我更换了etcd版本到3.4.20，目前1个星期了为止还没有复现
> 但目前还是会碰到偶见404，在高并发的场景有一些js和html会出现404，apisix显示请求到后台了，但后台nginx没有打印该请求日志，貌似请求到别的地方了
> 然后还有一个场景是变更apisix-dashboard的时候，偶尔会出现请求403

There is nothing we can do about the phenomenon but there is no stable recurrence of the steps.

**Comment by enuoCM** [comment]
> 3.4.2

Hi, 你配置的上游服务是不是有http，也有https？

**Comment by tzssangglass** [comment]
> Hi, 你配置的上游服务是不是有http，也有https？我们使用2.14.1这个版本，如果上游有http和https的话，就100%重现路由乱匹配的问题。

maybe fixed by #7466
