### ISSUE TITLE
bug: real-ip plugin get wrong ip when using X-Forwarded-For

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix#7137]
### Current Behavior

According to the current logic in real-ip plugin.
When I set source to http_x_forwarded_for. It will get last ip on the `X-Forwarded-For` header list.
But after search for some document, the first ip in the list is client ip, others maybe the proxy ip.

When I enable both real_ip plugin and set route rule to chash(or others like limit-req), it will always hashed by proxy ip, I think this is wrong behavior.
And there are more problem when using Aliyun SLB, Apisix will always get SLB's ip, which is managed by a pool and always different.

I don't know if this is a bug or I use it wrong.

### Steps to Reproduce

。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
This behavior is the same as Nginx's default behavior.

Could you turn `recursive` to true?
See https://apisix.apache.org/docs/apisix/next/plugins/real-ip

**Comment by kevinw66** [comment]
> This behavior is the same as Nginx's default behavior.
> 
> Could you turn `recursive` to true? See https://apisix.apache.org/docs/apisix/next/plugins/real-ip

It's not problem of `trusted_addresses`.

**Comment by spacewander** [comment]
It seems that you don't get my point.
You just need to configure `recursive` and `trusted_addresses`, which is equal to Nginx's `real_ip_recursive` and `set_real_ip_from`. Please refer to the relative documents.

**Comment by spacewander** [comment]
Note that the `recursive ` feature is in the master branch, so you need to backport it yourself or wait for the upcoming 2.14.1 release.

**Comment by spacewander** [comment]
> It will get last ip on the X-Forwarded-For header list.

This behavior is equal to Nginx's default behavior.

See https://nginx.org/en/docs/http/ngx_http_realip_module.html：
> If recursive search is disabled, the original client address that matches one of the trusted addresses is replaced by the last address sent in the request header field defined by the [real_ip_header](https://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_header) directive.
