### ISSUE TITLE
help request: how to make the redirect plugin get the redirect address from the return value

### ISSUE THREAD

**Issue by bukexiusi** [apache/apisix#7138]
### Description

需要从返回值中获取重定向地址，如何做？

**Comment by tzssangglass** [comment]
Then I think this requirement does not involve to redirect plugin.

The redirect plugin works in the `rewrite` phase.

If you need to retrieve some data from the results returned by the upstream, then the plugin should work in the `body_filter` phase.

You can write your own plugins to implement it.
