### ISSUE TITLE
feat: can apisix support proxy and eliminate the authentication when backend using digest auth?

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#7140]
### Description

我们正在在推动业务迁移到APISIX网关，且希望业务统一使用HMAC鉴权方式。目前遇到了一个困难，有部分业务的后端应用自带鉴权，且使用的是digest auth鉴权方式，因此我们无法通过APISIX的proxy-rewrite插件简单植入authentication头部来屏蔽后端鉴权。

这种情况下，业务就无法在不关闭后端鉴权的前提下平滑迁移到HMAC鉴权方式，只能维持原有的digest鉴权。

不知道APISIX能否支持下，出一个能屏蔽后端 digest 鉴权方式的插件，即：APISIX 往后端请求时，需要先digest鉴权。

可能这个需求比较小众，我先在这里提一下，看看有没有相同需求的朋友。

在github上也找了个类似的lua脚本：https://github.com/pacopink/resty-digest-auth/blob/master/lua/digest_access.lua

**Comment by tzssangglass** [comment]
hmac-auth support check `digest `, see:

https://github.com/apache/apisix/blob/ef9ba91a601d400ef4d43e0dd3378f1d98c3b7d9/apisix/plugins/hmac-auth.lua#L356-L372

**Comment by jagerzhang** [comment]
> hmac-auth support check `digest `, see:
> 
> https://github.com/apache/apisix/blob/ef9ba91a601d400ef4d43e0dd3378f1d98c3b7d9/apisix/plugins/hmac-auth.lua#L356-L372

好像说的不是一个场景~

**Comment by spacewander** [comment]
A question: what's the user info used in digest auth?

**Comment by jagerzhang** [comment]
> What's the user info used in digest auth? And is there any standard for the digest auth?

可以看看这几篇文章：
https://en.wikipedia.org/wiki/Digest_access_authentication
https://www.cnblogs.com/xiaoxiaotank/p/11078571.html
https://www.cnblogs.com/xiaoxiaotank/p/11079024.html

digest auth 可以理解为 Basic Auth的一个升级版，主要是解决Basic Auth鉴权使用静态头部认证带来的安全问题。在Basic Auth方式下，APISIX只需要往后端注入一个Basic Base64静态头部就能完成认证：
比如：
![image](https://user-images.githubusercontent.com/9711651/170456795-020e982b-2e56-4337-9804-56c48d503201.png)

但是Digest则无法在网关这里静态完成，需要写一个往后端服务的认证逻辑才行实现。

**Comment by spacewander** [comment]
LGTM. Would you like to contribute to this plugin and write a detailed proposal?

**Comment by spacewander** [comment]
Two suggestions about this:
1. better to avoid `auth` in the name of this plugin so it won't be misunderstood as a client authentication plugin.
2. maybe we can reserve some places in this plugin to support more authentication methods in the future.

**Comment by jagerzhang** [comment]
> Two suggestions about this:
> 
> 1. better to avoid `auth` in the name of this plugin so it won't be misunderstood as a client authentication plugin.
> 2. maybe we can reserve some places in this plugin to support more authentication methods in the future.

或许可以叫做  upstream-auth，用于和上游鉴权的一个插件，可以支持多种认证方式，比如Basic Auth、Key Auth、Digest Auth等

**Comment by spacewander** [comment]
To me, `upstream-auth` looks similar to `jwt-auth`. What about `proxy-credential`?
