### ISSUE TITLE
help request: apisixConsumer wolf-rbac plugin config for multiple appIds

### ISSUE THREAD

**Issue by rjiang-ptm** [apache/apisix#7147]
### Description

In the apisixConsumer config for wolf-rbac, the appId field can only be specified for one appid, or a list of appid? The use case is: usually for a given consumer/user, there could be multiple apps (appIds) associated with that user.

Here is the typical consumer config for wolf-rbac:

{
  "username":"wolf_rbac",
  "plugins":{
    "wolf-rbac":{
      "server":"http://127.0.0.1:12180",
      "appid":"restful"
    }
  },
  "desc":"wolf-rbac"
}'
Notice the appid is just one string.

Does the apisixConsumer wolf-rbac config can support multiple appid for a given consumer/user? If so, how to specify it - in what format, can you show some examples? If not, what do you suggest to support the above user case?

### Environment

- APISIX version (run `apisix version`): 2.10.0+
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Currently, it's impossible to do this. Would you like to share some scenarios about it?

**Comment by rjiang-ptm** [comment]
The scenario is very typical - basically one user/consumer can access multiple apps (appIds), each app may have its own url/endpoint/auth defined in wolf.
