### ISSUE TITLE
feat: As a user, I want to add `apisix test` to `apisix help`, so that people could know this command quickly

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7148]
### Description

See the discussion in https://github.com/apache/apisix/issues/3230#issuecomment-1139180735

@apit 
Pull request is welcome!

**Comment by kwanhur** [comment]
[WeOpen Star]I would like to help.

Please assign it to me.

**Comment by spacewander** [comment]
I think about it again. Maybe @apit has the priority to get this work? As he/she pointed it out first.
