### ISSUE TITLE
help request: can not load image of the plugin response-rewrite important tips for `ngx.exit`

### ISSUE THREAD

**Issue by kwanhur** [apache/apisix#7149]
### Description

[response-rewrite](https://apisix.apache.org/docs/apisix/plugins/response-rewrite/) important tips image for `nginx.exit` load failed. 

Note:
* My PC couldn't connect to [image server](https://cdn.jsdelivr.net/gh/Miss-you/img/picgo/20201113010623.png).
![sendpix0](https://user-images.githubusercontent.com/1792134/170624804-c8630266-e21c-4691-ab4e-3a9ae7bb6eeb.jpg)

https://github.com/apache/apisix/blob/aefffe914f9f3ec187d3db6688c02d22785cf400/docs/en/latest/plugins/response-rewrite.md?plain=1#L129

Suggest turn it into Markdown Table.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/170849580-aa296d3d-b43a-404a-8c88-720afb2b7c08.png)

Hi, @kwanhur, this is because jsDelivr is effected by GFW, I just uploaded this image to GitHub's Image Server, could you please file a PR to update it?

**Comment by juzhiyuan** [comment]
One day if we have a sponsored CDN server, we could even scan all static files and `https://user-images.githubusercontent.com` files and then upload them to CDN.

**Comment by kwanhur** [comment]
I'll post a PR to update it, but will we still post it with an image file? How about plaintext table?

**Comment by kwanhur** [comment]
How about plaintext table instead of image for `ngx.exit`? 

What's your opinion? @hf400159 @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
Both table and image on a different CDN sound like good ideas. I think @juzhiyuan is suggesting to use the image hosted on GitHub CDN. So, it should just be swapping the link.

**Comment by juzhiyuan** [comment]
> One day if we have a sponsored CDN server, we could even scan all static files and `https://user-images.githubusercontent.com` files and then upload them to CDN.

Yes.
