### ISSUE TITLE
help request: No slack channel in ASF foundation slack workspace

### ISSUE THREAD

**Issue by andrewgkew** [apache/apisix#7152]
### Description

Hi

I have followed your docs here: https://apisix.apache.org/docs/general/join/ but when in the ASF workspace and browse for channels there is no apisix channel? Can someone help?

Thanks

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
![image](https://user-images.githubusercontent.com/26448043/170681099-536fc2dd-c7e6-4079-93ac-9665c7ce0b28.png)
You need to search for apisix in "Browse Channels"

**Comment by moonming** [comment]
Click on the three dots after the "Channels"

**Comment by andrewgkew** [comment]
Thanks @moonming - this is the right workspace right?

<img width="304" alt="image" src="https://user-images.githubusercontent.com/2614141/170691814-bfeb3d5e-8740-44c8-9266-0a46c00ed480.png">

For some reason I can only find the skywalking channel and no others?

**Comment by andrewgkew** [comment]
Could you maybe look for myself in the workspace and see if I am limited to access? I tried to DM you but cant find you in there either?

**Comment by andrewgkew** [comment]
@wu-sheng is helping me with this now, seems that I have a guest account which is why I can not find any other channels.

**Comment by andrewgkew** [comment]
I now have access to the apisix channel.
