### ISSUE TITLE
bug: upgrading openresty to 1.21.4.1 causes startup failures

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#7155]
### Current Behavior

lua ./apisix/cli/apisix.lua start
apisix[20631]: lua: error loading module 'ssl.core' from file '/usr/local/apisix/
apisix[20631]: /usr/local/apisix/deps/lib/lua/5.1/ssl.so: undefined symbol: 
apisix[20631]: stack traceback:
apisix[20631]: [C]: ?
apisix[20631]: [C]: in function 'require'
apisix[20631]: /usr/local/apisix/deps/share/lua/5.1/ssl.lua:8: in main chunk
apisix[20631]: [C]: in function 'require'
apisix[20631]: /usr/local/apisix/deps/share/lua/5.1/ssl/https.lua:10: in main 
apisix[20631]: [C]: in function 'require'
apisix[20631]: ./apisix/cli/etcd.lua:24: in main chunk
apisix[20631]: [C]: in function 'require'
apisix[20631]: ./apisix/cli/ops.lua:18: in main chunk
apisix[20631]: [C]: in function 'require'
apisix[20631]: ./apisix/cli/apisix.lua:32: in main chunk

### Expected Behavior

start the normal

### Steps to Reproduce

./bin/apisix start

### Environment

- APISIX version (run `apisix version`): 2.10.5
- Operating system (run `uname -a`):  5.10.102-99.473.amzn2.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/7067.
