### ISSUE TITLE
bug: hook_conf must be present in debug.yaml, otherwise it will throw an exception

### ISSUE THREAD

**Issue by amrellafy** [apache/apisix#7159]
### Current Behavior

if hook_config is not present, the following exception will be thrown

`apisix attempt to index local 'hook_conf' (a nil value)`

https://github.com/apache/apisix/blob/aefffe914f9f3ec187d3db6688c02d22785cf400/apisix/debug.lua#L171 should include a check.

### Expected Behavior

not throwing an error if hook_conf is not present.

### Steps to Reproduce

1. create a debug.yaml
2. do not incude hook_conf

### Environment

- APISIX version 2.14.1
- on Docker

**Comment by spacewander** [comment]
The hook_conf is present by default:
https://github.com/apache/apisix/blob/1c33ab28f6d0aa5b0b7265185a1725bd3794dbc7/conf/debug.yaml#L22

Are there some user cases people need to remove the default  hook_conf?

**Comment by amrellafy** [comment]
per the documentation, hook_conf is only required in advanced debugging.

**Comment by tzssangglass** [comment]
> per the documentation, hook_conf is only required in advanced debugging.

`hook_conf` is part of the `debug.yaml` structure. Just because it is needed for advanced debugging does not mean that it can be removed if advanced debugging is not enabled.

But we could be clearer on this point in the documentation?

**Comment by spacewander** [comment]
Or we can add validation to https://github.com/apache/apisix/blob/master/apisix/debug.lua,  with jsonschema like https://github.com/apache/apisix/blob/master/apisix/cli/schema.lua.

**Comment by amrellafy** [comment]
> > per the documentation, hook_conf is only required in advanced debugging.
> 
> `hook_conf` is part of the `debug.yaml` structure. Just because it is needed for advanced debugging does not mean that it can be removed if advanced debugging is not enabled.
> 
> But we could be clearer on this point in the documentation?

For sure, maybe make it clearer. Thanks!

**Comment by amrellafy** [comment]
Sure, if you get access to push.

**Comment by spacewander** [comment]
> Sure, if you get access to push.

PR is welcome!
