### ISSUE TITLE
help request: etcd connection refused. Retryin..

### ISSUE THREAD

**Issue by isDerek** [apache/apisix#7162]
### Description

when i start the apisix service, wait a moment, the etcd will report the errors.
1. "[lua] v3.lua:647: request_chunk(): http://[ip]:32002: connection refused. Retrying, context: ngx.timer"
2. " [lua] health_check.lua:90: report_failure(): update endpoint: http://xxxx:32002 to unhealthy, context: ngx.timer"
3. [lua] v3.lua:647: request_chunk(): has no healthy etcd endpoint available. Retrying, context: ngx.timer
4. [lua] config_etcd.lua:567: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer

why the connection will be refused?

i check the etcd log , no error log was reported. i think the etcd client something wrong? 

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Linux apisix-6548b54c4d-g2blx 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):/usr/local/bin/luarocks 3.8.0

**Comment by isDerek** [comment]
the apisix so many worker process, is normal?  number is 36.

**Comment by isDerek** [comment]
i check the etcd connect in apisix node. it's so many. the etcd connection won't be released?

**Comment by isDerek** [comment]
we use nodeport type for etcd it's error, the etcd in the other k8s(vm). but when we use clusterIp for etcd. the etcd in the current k8s, it's ok.

**Comment by isDerek** [comment]
why the nodeport type for etcd can't run normal?

**Comment by tokers** [comment]
@isDerek Have you ever tried to connect ETCD by `etcdctl`?

**Comment by isDerek** [comment]
> @isDerek Have you ever tried to connect ETCD by `etcdctl`?

i enter the apisix node, and put the etcd data ,it' will be ok.  but the apisix logs notify many reconnected errors.

**Comment by isDerek** [comment]
the apisix k8s has many apisix pod. it will be error in svc load?

**Comment by tokers** [comment]
> the apisix k8s has many apisix pod. it will be error in svc load?

It's tough to judge. So you configure the ETCD service cluster IP to APISIX?

**Comment by isDerek** [comment]
> > the apisix k8s has many apisix pod. it will be error in svc load?
> 
> It's tough to judge. So you configure the ETCD service cluster IP to APISIX?

yes.

**Comment by isDerek** [comment]
one question: different apisix service can connect the same etcd ?

**Comment by tzssangglass** [comment]
It looks like this is due to APISIX not being able to access etcd properly according to the etcd endpoint you configured.

You can enter the APISIX pod and access etcd according to the etcd endpoint you configured to check the network.

**Comment by tokers** [comment]
> It looks like this is due to APISIX not being able to access etcd properly according to the etcd endpoint you configured.
> 
> You can enter the APISIX pod and access etcd according to the etcd endpoint you configured to check the network.

@isDerek You can use the ephemeral pod if APISIX pods cannot start normally.
