### ISSUE TITLE
bug: route matching host error

### ISSUE THREAD

**Issue by Horus-K** [apache/apisix#7163]
### Current Behavior

![image](https://user-images.githubusercontent.com/48319268/170910682-2d5e8b8a-94cb-43cb-bde6-60c2132dba23.png)
![image](https://user-images.githubusercontent.com/48319268/170910630-77dddcd5-c84a-4aa1-95ad-62e1031bd304.png)

I use the exact domain name to access xxxx.xxxx.xxxx.com and the route matched is id:1047。 If I adjust the id: 1314 priority to 10, the route id: 1314 will take effect

### Expected Behavior

The route should match to 1414

### Error Logs

NO

### Steps to Reproduce

只有精确路由id比通配路由id小，精确匹配才会生效，否则都会走到通配路由中。或者将精确匹配路由优先级调整为比通配路由大才行

### Environment

- APISIX version (run `apisix version`): 1.13.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Any routes which match more than path are considered equal and should be distinguished by priority. Otherwise the order to match depends on the actual implementation.

**Comment by Horus-K** [comment]
I understand
