### ISSUE TITLE
help request:  Alternatives to Semantic Pull Requests

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#7164]
### Description

Currently we are using [Semantic Pull Requests](https://github.com/zeke/semantic-pull-requests ) to check in PR but the project is no longer maintained. we need some alternatives.

e.g.

* https://github.com/amannn/action-semantic-pull-request 

If anyone is interested in this, please submit a PR to complete this replacement

**Comment by tokers** [comment]
May use git submodule to do this.

**Comment by tao12345666333** [comment]
> May use git submodule to do this.

Right!

**Comment by ccxhwmy** [comment]
> ### Description
> Currently we are using [Semantic Pull Requests](https://github.com/zeke/semantic-pull-requests) to check in PR but the project is no longer maintained. we need some alternatives.
> 
> e.g.
> 
> * https://github.com/amannn/action-semantic-pull-request
> 
> If anyone is interested in this, please submit a PR to complete this replacement

What does `check in PR` mean?

**Comment by ccxhwmy** [comment]
> > May use git submodule to do this.
> 
> Right!

I can understand the need to replace `semantic-pull-request` with `action-semantic-pull-request`, but why use `git submodule`?

**Comment by tao12345666333** [comment]
@ccxhwmy ref: https://infra.apache.org/github-actions-secrets.html

**Comment by kwanhur** [comment]
Personally, Github Workflow job better than submodule, just like [Lint](https://github.com/apache/apisix/blob/master/.github/workflows/lint.yml)

**Comment by ccxhwmy** [comment]
> @ccxhwmy submodle is more suitable.

I found that doing `git clone` in the github workflows still works, Would you tell me why `git submodule` is more suitable? I want to learn more about it.

**Comment by ccxhwmy** [comment]
I found that [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) does not support the characteristic "allowRevertCommit" which [semantic-pull-request](https://github.com/zeke/semantic-pull-requests) support, is there some mistake in my understanding?

**Comment by spacewander** [comment]
https://github.com/amannn/action-semantic-pull-request/issues/192
I see you have opened an issue for it.
If the action doesn't support it, we can omit it for now.

**Comment by ccxhwmy** [comment]
> [amannn/action-semantic-pull-request#192](https://github.com/amannn/action-semantic-pull-request/issues/192) I see you have opened an issue for it. If the action doesn't support it, we can omit it for now.

ok~
