### ISSUE TITLE
help request: How to configure the front-end interface proxy to request special symbols for linking at the same time?

### ISSUE THREAD

**Issue by LancCJ** [apache/apisix#7169]
### Description

hi,guys.i have a problem.the situation is i want to proxy the front-end interface(page),and my page url is `https://dispatch.testdolphin.com/dispatch-ms/#/conference/single_url?ipc_live=1&gbids=32050700001320000174`,so i configure it like this below:
<img width="657" alt="image" src="https://user-images.githubusercontent.com/2968042/171073251-ccf8d81f-b1ef-4053-aa10-7ad28e0e1cd2.png">
after that i try to visit and i found a problem 
<img width="950" alt="image" src="https://user-images.githubusercontent.com/2968042/171073386-6868f321-3ba2-4c44-8d9b-b2cfce1a7cff.png">

,# symbol escaped，and the log like this

`127.0.0.1 - - [31/May/2022:08:54:01 +0800] 127.0.0.1:9080 "GET /ronghetongxin/spbf?apikey=f3db72c3-9d47-4548-95a2-a75bc5b19d78&ipc_live=1&gbids=32050700001320000174 HTTP/1.1" 404 150 0.003 "-" "PostmanRuntime/7.29.0" - - - "http://dispatch.testdolphin.com/dispatch-ms/%23/conference/single_url?apikey=f3db72c3-9d47-4548-95a2-a75bc5b19d78&ipc_live=1&gbids=32050700001320000174"
`
Has anyone configured the interface?

### Environment

- APISIX version (run `apisix version`):2.14
- Operating system (run `uname -a`):Darwin LancCJdeMacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
built by clang 13.1.6 (clang-1316.0.21.2.5)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"etcd_version":"3.5.0","version":"2.14.0","hostname":"LancCJdeMacBook-Pro.local","id":"d213ef57-0178-49a7-ba5a-03d7d06e01a9","boot_time":1653956953}
- APISIX Dashboard version, if relevant:2.13
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):/usr/local/bin/luarocks 3.9.0
LuaRocks main command-line interface

**Comment by tokers** [comment]
It looks like your upstream server sent `404`? The response body you gave doesn't like a result from Apache APISIX.

**Comment by LancCJ** [comment]
@tokers yes ,you are right,because the symbol orignal is '# 'but now is '%23',so 404,i want to know how to keep symbol '#'

**Comment by tokers** [comment]
> @tokers yes ,you are right,because the symbol orignal is '# 'but now is '%23',so 404,i want to know how to keep symbol '#'

`#` is just an anchor and will be ignored by Apache APISIX? Not sure if escaping it can solve your problem.

**Comment by tzssangglass** [comment]
Similar to this issue: https://github.com/apache/apisix/issues/5654

Reason: https://github.com/apache/apisix/issues/5654#issuecomment-986250154

Solution 1: https://github.com/apache/apisix/issues/5654#issuecomment-1082523526

Solution 2: https://github.com/apache/apisix/issues/5654#issuecomment-1123198180

Perhaps we should add this point to the documentation.

**Comment by LancCJ** [comment]
> 

ok, tks

**Comment by LancCJ** [comment]
i change the route config json like this below
<img width="691" alt="image" src="https://user-images.githubusercontent.com/2968042/171076881-b768d6fb-e362-442b-9b80-9b618ba2229b.png">
it is ok now 
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/2968042/171076911-1b6aac04-266f-4157-a4ac-57bb045427dc.png">

**Comment by LancCJ** [comment]
change route config json like above setting can fix my peoblem
