### ISSUE TITLE
request help: use https

### ISSUE THREAD

**Issue by VineFiner** [apache/apisix#7172]
### Issue description

If I set `--set gateway.tls.enabled=true.`
And turn on redirect to https in the dashboard. will redirect to port `9443`.
If it is not set, the https URL cannot be opened.

### Environment

- your apisix-ingress-controller version (output of apisix-ingress-controller version --long):2.13
- your Kubernetes cluster version (output of kubectl version):v1.23.6+k3s1
- if you run apisix-ingress-controller in Bare-metal environment, also show your OS version (uname -a): Ubuntu20.04

**Comment by VineFiner** [comment]
Any progress?

**Comment by tao12345666333** [comment]
You can view the progress of those two issues or comment on them

**Comment by kwanhur** [comment]
Maybe plugin [redirect](https://apisix.apache.org/docs/apisix/plugins/redirect) with `http_to_https` can help you.

**Comment by spacewander** [comment]
Solved in https://github.com/apache/apisix/pull/7065

**Comment by VineFiner** [comment]
> Maybe plugin [redirect](https://apisix.apache.org/docs/apisix/plugins/redirect) with `http_to_https` can help you.

HTTP/1.1 301 Moved Permanently
...
Location: https://127.0.0.1:9443/hello
...

I want to use port 443

**Comment by VineFiner** [comment]
> 也许插件[重定向](https://apisix.apache.org/docs/apisix/plugins/redirect)可以帮助`http_to_https`你。

this doesn't work
