### ISSUE TITLE
help request: high vsz usage when downloading file(500M)

### ISSUE THREAD

**Issue by kevinw66** [apache/apisix#7173]
### Description

When downloading file through rest api, I see the worker process vsz use about 35G, normal it only needs 200M, see picture as below
![image](https://user-images.githubusercontent.com/31196226/171125384-66025b13-9718-4bf3-b3cc-ec95f8e08701.png)

Then the system kill this nginx worker, and the download was terminated.
`java.io.IOException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 522,876,046; received: 171,835,236)`

### Environment

- APISIX version (run `apisix version`):2.10.2
- Operating system (run `uname -a`): Apisix 2.10.2 Docker

**Comment by kevinw66** [comment]
> What's the RSS value of this worker? VSZ is the total mapped memory account.
> 
> BTW, What's the configuration of APISIX, and how did you configure APISIX (Routes, Upstreams, and so on)?

Hi, this is RSS and VSZ value of this worker, it's no much different
![image](https://user-images.githubusercontent.com/31196226/171314886-e88b9a4e-633a-40f8-8793-a625a38aa36a.png)

here is my route configuration
```json
{
  "uris": [
    "/api/*",
  ],
  "name": "route-name",
  "priority": 1,
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/api/(.*)",
        "/$1"
      ]
    },
    "cors": {
      "allow_credential": false,
      "allow_headers": "*",
      "allow_methods": "*",
      "allow_origins": "*",
      "disable": false,
      "expose_headers": "*",
      "max_age": 5
    },
  },
  "upstream": {
    "nodes": [
      {
        "host": "upstream-host",
        "port": 8080,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 600,
      "send": 600,
      "read": 600
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "node",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

**Comment by kevinw66** [comment]
> What's the RSS value of this worker? VSZ is the total mapped memory account.
> 
> BTW, What's the configuration of APISIX, and how did you configure APISIX (Routes, Upstreams, and so on)?

Hi, this is the problem of my custom plugin.
Can I ask what tools can I use to find out which exactly code cause this memory leak?

**Comment by tzssangglass** [comment]
> > What's the RSS value of this worker? VSZ is the total mapped memory account.
> > BTW, What's the configuration of APISIX, and how did you configure APISIX (Routes, Upstreams, and so on)?
> 
> Hi, this is the problem of my custom plugin. Can I ask what tools can I use to find out which exactly lua code cause this memory leak?

We can use the flamgraph to find memory leaks.

see: https://github.com/openresty/stapxx#sample-bt-leaks

**Comment by kevinw66** [comment]
> > > What's the RSS value of this worker? VSZ is the total mapped memory account.
> > > BTW, What's the configuration of APISIX, and how did you configure APISIX (Routes, Upstreams, and so on)?
> > 
> > 
> > Hi, this is the problem of my custom plugin. Can I ask what tools can I use to find out which exactly lua code cause this memory leak?
> 
> We can use the flamgraph to find memory leaks.
> 
> see: https://github.com/openresty/stapxx#sample-bt-leaks

Thanks
