### ISSUE TITLE
help request: about eureka when apisix reload

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#7178]
### Description

when apisix the reload, the eureka data is not ready (fetch_full_registry is not over), and there are many 502. Is there any solution.

### Environment

- APISIX version (run `apisix version`):2.10.5
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
I think discovery mode has this problem if it's a large amount of data.

We should allow users to specify that they have to wait for the fetch data to finish before providing the service, then APISIX will be interrupted during reload.

**Comment by soulbird** [comment]
> One solution is to let APISIX fetch all data from eureka in the `init_worker` phase. Just like the way we load data from ETCD.

Looks like that's what it's doing now.

**Comment by tzssangglass** [comment]
> Looks like that's what it's doing now.

For eureka, it's not.

**Comment by kongjun01** [comment]
> I think discovery mode has this problem if it's a large amount of data.
> 
> We should allow users to specify that they have to wait for the fetch data to finish before providing the service, then APISIX will be interrupted during reload.

I considered that before.Our most front-end is Ali Cloud SLB, with a heartbeat mechanism.When the release is released, [-s quit], wait for SLB to think that APISIX has been offline, but there is a waiting time for heartbeat detection, during which SLB will still have traffic forward

**Comment by kongjun01** [comment]
> One solution is to let APISIX fetch all data from eureka in the `init_worker` phase. Just like the way we load data from ETCD.

The etcd is also asynchronous with the ngx_timer_at function, so how does it guarantee that the apisix provides the service after the data is fully loaded with the etcd?

**Comment by tokers** [comment]
> > One solution is to let APISIX fetch all data from eureka in the `init_worker` phase. Just like the way we load data from ETCD.
> 
> The etcd is also asynchronous with the ngx_timer_at function, so how does it guarantee that the apisix provides the service after the data is fully loaded with the etcd?

See https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L159. That's the default behavior.

**Comment by soulbird** [comment]
> > One solution is to let APISIX fetch all data from eureka in the `init_worker` phase. Just like the way we load data from ETCD.
> 
> The etcd is also asynchronous with the ngx_timer_at function, so how does it guarantee that the apisix provides the service after the data is fully loaded with the etcd?

We used luasocket instead of cosocket to [load etcd configuration when apisix starts](https://github.com/apache/apisix/pull/3799) in `init_worker` phase

**Comment by kongjun01** [comment]
> > > One solution is to let APISIX fetch all data from eureka in the `init_worker` phase. Just like the way we load data from ETCD.
> > 
> > 
> > The etcd is also asynchronous with the ngx_timer_at function, so how does it guarantee that the apisix provides the service after the data is fully loaded with the etcd?
> 
> We used luasocket instead of cosocket to [load etcd configuration when apisix starts](https://github.com/apache/apisix/pull/3799) in `init_worker` phase

perfect.
