### ISSUE TITLE
help request: The port of the Management API cannot be started after streaming is enabled

### ISSUE THREAD

**Issue by wulinghui** [apache/apisix#7180]
### Description

![image](https://user-images.githubusercontent.com/36905201/171364823-55a5e99d-1a33-4b35-b058-927f319fe386.png)
`port 9080: Connection refused`
![image](https://user-images.githubusercontent.com/36905201/171365035-489bda28-90bf-48c1-b93f-137b661a5948.png)
>  stream  LISTEN  9100、9101 is runing . 9000 port can log in  ，  9080  Didn't get up
- config.yaml
![image](https://user-images.githubusercontent.com/36905201/171365441-860706de-204c-4a79-b850-0bb218c39a7e.png)

### Environment

- APISIX version (run `2.10.0`): 2.10.0
- Operating system (run `uname -a`):  Linux VM-0-34-ubuntu 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
built with OpenSSL 1.1.1k  25 Mar 2021 (running with OpenSSL 1.1.1l  24 Aug 2021)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  curl: (7) Failed to connect to 127.0.0.1 port 9090: Connection refused
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):  /usr/local/bin/luarocks 3.4.0

**Comment by wulinghui** [comment]
![image](https://user-images.githubusercontent.com/36905201/171366087-6aa1d2b1-57f2-4694-a8cd-352c1d1fd0a3.png)
![image](https://user-images.githubusercontent.com/36905201/171366222-d255c037-e345-4161-b2ac-cf43b2fccc33.png)


Note for the newly added configuration, port 9080 is up

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/5867.
Consider solved. Feel free to reopen it if needed.

**Comment by wulinghui** [comment]
`only: false`    is  ok
