### ISSUE TITLE
help request:  Does apisix support pkcs11?

### ISSUE THREAD

**Issue by mayoatte** [apache/apisix#7181]
### Description

Hello,

Does apisix support or can it be made to support pkcs11? We have a hard requirement to terminate ssl with an hsm stored key via this protocol. 

If this support is possible, can you please point me to any docs?

Thanks

### Environment

-

**Comment by soulbird** [comment]
This seems to be an issue with openssl. APISIX is built with openresty-openssl, which doesn't seem to include the pkcs#11 standard. Therefore, you may need to build APISIX from source, adjust the configuration file when compiling openssl, add support for pkcs#11; then use the `use_engine` directive in APISIX to set your preferred openssl engine. This is just a suggestion, not necessarily works. In general your main focus should be on how openssl supports pkcs#11 not APISIX.

**Comment by mayoatte** [comment]
Thanks @soulbird , that gives me something to look into.
