### ISSUE TITLE
bug: Independent external APIs cannot be automatically discovered by linking APIs servers

### ISSUE THREAD

**Issue by liangyawang** [apache/apisix#7185]

**Comment by spacewander** [comment]
Could you add a log 
```
    local cjson = require("cjson.safe"); ngx.log(ngx.EMERG, "AA", cjson.encode(apiserver))
```
in https://github.com/apache/apisix/blob/4562875348fdaab3cb05e6df8aecf0604fa6e157/apisix/discovery/kubernetes/informer_factory.lua#L48?

**Comment by liangyawang** [comment]
您好 请问您会讲中文吗 如果会的话 我向您提问一下 这行代码加在lua文件的什么位置？
还有个问题，当我把配置中的token_file改位token时它不再出现报错 但是我也不能确定它是否获取到了对应的endpoints

> 2022年6月2日 下午5:45，罗泽轩 ***@***.***> 写道：
> 
> local cjson = require("cjson.safe"); ngx.log(ngx.EMERG, "AA", cjson.encode(apiserver))

**Comment by tzssangglass** [comment]
> 您好 请问您会讲中文吗 如果会的话 我向您提问一下 这行代码加在lua文件的什么位置？

In the line above this line of code: https://github.com/apache/apisix/blob/4562875348fdaab3cb05e6df8aecf0604fa6e157/apisix/discovery/kubernetes/informer_factory.lua#L48

The new code was added to print what `apiserver ` is.

**Comment by liangyawang** [comment]
请回复一下这个问题

> 2022年6月3日 下午7:35，梁亚旺 ***@***.***> 写道：
> 
> 我尝试通过api创建一个路由 因为dashboard还没办法创建 命令如下
> <粘贴的图形-1.tiff>
> 
> 但是 当我尝试通过apisix访问域名时 发现apisix报错如下
> 2022/06/03 19:25:53 [error] 3135#3135: *10445111 [lua] init.lua:517: http_access_phase(): failed to set upstream: no valid upstream node: nil, client: 100.100.100.100, server: _, request: "GET /actuator/health HTTP/1.1", host: "teacher-test.xxxx.cn <http://teacher-test.xxxx.cn/>”
> 
> 官网中没有对kubernetes的自动发现做详细的描述 所以此刻 我不清楚问题出在了哪里 
> 上图中 service_name字段 yace是我k8s中的namespace teacher-app是我的endpoints名称 
>> 2022年6月2日 下午5:45，罗泽轩 ***@***.*** ***@***.***>> 写道：
>> 
>> local cjson = require("cjson.safe"); ngx.log(ngx.EMERG, "AA", cjson.encode(apiserver))
>

**Comment by tzssangglass** [comment]
> 2022/06/03 19:25:53 [error] 3135#3135: *10445111 [lua] init.lua:517: http_access_phase(): failed to set upstream: no valid upstream node: nil, client: 100.100.100.100, server: _, request: "GET /actuator/health HTTP/1.1", host: "teacher-test.xxxx.cn”

This log indicates that APISIX was unable to query valid IP from kubernates based on `service_name`. From the information you provided it is hard to tell where the problem is.

> 官网中没有对kubernetes的自动发现做详细的描述 所以此刻 我不清楚问题出在了哪里

I didn't find an article describing this in detail either.

You can choose to read the source code to understand it.

Or you can try the suggestion above to add log output and let's locate the problem together.

**Comment by liangyawang** [comment]
请问一下是否能够提供一个通过api创建自动发现类型为kubernetes的路由的例子

> 2022年6月4日 下午6:29，梁亚旺 ***@***.***> 写道：
> 
> Dear team member
> Do you have any examples about the configuration of automatic discovery by APIs through kubernetes and the creation of routes with kubernetes as the type of automatic discovery through APIs? If yes, please send me examples for other types of automatic discovery in the official website, except kubernetes. I think I may have used them incorrectly, so please give me two examples to try. Thank you very much

**Comment by tzssangglass** [comment]
> 请问一下是否能够提供一个通过api创建自动发现类型为kubernetes的路由的例子
> […](#)
> 2022年6月4日 下午6:29，梁亚旺 ***@***.***> 写道： Dear team member Do you have any examples about the configuration of automatic discovery by APIs through kubernetes and the creation of routes with kubernetes as the type of automatic discovery through APIs? If yes, please send me examples for other types of automatic discovery in the official website, except kubernetes. I think I may have used them incorrectly, so please give me two examples to try. Thank you very much

hi @zhixiongdu027 , can you provide some examples?

**Comment by juzhiyuan** [comment]
Updated: https://the-asf.slack.com/archives/CUC5MN17A/p1654503566448579?thread_ts=1654480287.905789&cid=CUC5MN17A

**Comment by zhixiongdu027** [comment]
抱歉抱歉，我现在才看到此信息。
我将在今晚尝试复现和修复此问题，

根据报错信息显示，我初步怀疑跟
apiserver 的初始化有关。

**Comment by zhixiongdu027** [comment]
I'm sorry, I've done several scene simulations locally and can't reproduce the situation in the picture.

Maybe the problem is related to the cluster configuration,

Is it convenient for me to communicate quickly through Im (wechat ,qq, mail) to solve this problem?
You can send your qq,wechart to my mail (root@libssl.com)
@liangyawang
