### ISSUE TITLE
help request: grpc-transcode not work

### ISSUE THREAD

**Issue by younglifestyle** [apache/apisix#7186]
### Description

apisix dashboard: , apisix：2.14.1 

Start with [apisix-docker](https://github.com/apache/apisix-docker), add [grpc_server_example](https://github.com/api7/grpc_server_example), follow the documentation [grpc-transcode.md](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/grpc-transcode.md), the interface cannot be accessed

```text
curl -i http://127.0.0.1:9080/grpctest?name=world
HTTP/1.1 503 Service Temporarily Unavailable
Date: Thu, 02 Jun 2022 10:22:17 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 194
Connection: keep-alive
Server: APISIX/2.14.1

<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

### Environment

- APISIX version (run `apisix version`): 2.14.1 
- Operating system (run `uname -a`): docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 19.0.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4.15
- APISIX Dashboard version, if relevant: 2.11

**Comment by jwrookie** [comment]
According to your description, I tested it and the result is ok.
```
example git:(master) curl -i http://127.0.0.1:9080/grpctest\?name\=world
HTTP/1.1 200 OK
Date: Fri, 03 Jun 2022 15:17:13 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.14.1
Trailer: grpc-status
Trailer: grpc-message

{"message":"Hello world"}
```

You need to provide more detailed information for find the problem. 

BTW In a test environment, you can delete the local `docker volume of etcd` and try again,

**Comment by younglifestyle** [comment]
proto file :
![image](https://user-images.githubusercontent.com/19261307/172337448-3bf644d3-120e-44c2-8c16-91508ff5cedc.png)

create route:
```
curl http://127.0.0.1:9080/apisix/admin/routes/111 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/grpctest",
    "plugins": {
        "grpc-transcode": {
            "proto_id": "1",
            "service": "helloworld.Greeter",
            "method": "SayHello"
        }
    },
    "upstream": {
        "scheme": "grpc",
        "type": "roundrobin",
        "nodes": {
            "10.2.33.4:50051": 1
        }
    }
}'
```
above is my configuration

**Comment by jwrookie** [comment]
Hi, access to container of APISIX and `telnet 10.2.43.4 50051`, The reason for 502 may be that the backend service is not started or the network is abnormal.

**Comment by younglifestyle** [comment]
> Hi, access to container of APISIX and `telnet 10.2.43.4 50051`, The reason for 502 may be that the backend service is not started or the network is abnormal.

APISIX can create etcd keys, it should be normal. 
GRPC service I can access with BloomRPC，which is also normal

**Comment by younglifestyle** [comment]
> Hi, access to container of APISIX and `telnet 10.2.43.4 50051`, The reason for 502 may be that the backend service is not started or the network is abnormal.

I tested the other API helloworld.Greeter SayHello，[grpc_server_example](https://github.com/api7/grpc_server_example)， test ok
```
curl -i http://127.0.0.1:9080/grpctest2?name=world
HTTP/1.1 200 OK                    
Date: Wed, 08 Jun 2022 08:51:01 GMT
Content-Type: application/json     
Transfer-Encoding: chunked         
Connection: keep-alive             
Server: APISIX/2.14.1              
Trailer: grpc-status               
Trailer: grpc-message 
```

**Comment by tzssangglass** [comment]
So we can close this? This should be a problem in the way gRPC is used. @younglifestyle

**Comment by younglifestyle** [comment]
> So we can close this? This should be a problem in the way gRPC is used. @younglifestyle

The interface of multiple proto files cannot be accessed. Can this verify the content of the document? In the document description, the interface of multiple proto files is not verified.

**Comment by tzssangglass** [comment]
> The interface of multiple proto files cannot be accessed. Can this verify the content of the document? In the document description, the interface of multiple proto files is not verified.

we should use different `proto` objects?

**Comment by younglifestyle** [comment]
> > The interface of multiple proto files cannot be accessed. Can this verify the content of the document? In the document description, the interface of multiple proto files is not verified.
> 
> we should use different `proto` objects?

I have used it. When I use the helloworld.TestImport.Run interface, it is the bound proto.pb. When I use the helloworld.Greeter SayHello interface, the bound proto is helloworld.proto

**Comment by tzssangglass** [comment]
what you need is: https://github.com/apache/apisix/blob/975038ea70dc47e0613c42b3eabb8dcc730216a4/t/plugin/grpc-transcode2.t#L236-L295?

**Comment by younglifestyle** [comment]
> what you need is:
> 
> https://github.com/apache/apisix/blob/975038ea70dc47e0613c42b3eabb8dcc730216a4/t/plugin/grpc-transcode2.t#L236-L295
> 
> ?

yes i did that and it didn't work

**Comment by tzssangglass** [comment]
> yes i did that and it didn't work

Then I can't reproduce it, because I will also follow the test cases to verify it.

You can verify the difference between the process the test case runs and the process you run.
