### ISSUE TITLE
help request: admin API access exception

### ISSUE THREAD

**Issue by LancCJ** [apache/apisix#7192]
### Description

hi guys,Today, I installed the latest version of apifix branch release/2.14 on a new centos7 x64 machine.After everything is deployed according to the document, try to access the URL  `http://my_ip:9080/apisix/admin/services/` according to the document.However, the following error occurred
<img width="832" alt="iShot_2022-06-04_08 35 08" src="https://user-images.githubusercontent.com/2968042/171969626-b192ee72-bb43-4773-a13b-c3d669f85a8f.png">

I'll check error Log file. The detailed error information is found as follows
<img width="1364" alt="image" src="https://user-images.githubusercontent.com/2968042/171969615-a7e8be11-05d4-4337-83b7-997da8a041de.png">

I also checked the source code for this error. The corresponding line is as follows

<img width="1199" alt="image" src="https://user-images.githubusercontent.com/2968042/171969655-0786d8c4-c8f0-456e-9edd-13958452b906.png">

I don't know what caused it. Who knows,Now thanks

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):Linux  Fri Apr 8 15:42:29 CST 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.19.9.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.13
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):/usr/local/bin/luarocks 3.8.0
LuaRocks main command-line interface

**Comment by tzssangglass** [comment]
I couldn't reproduce it, here are the steps I tried to reproduce it.

1. The version I use: https://github.com/apache/apisix/commits/release/2.14

2. Start APISIX and access

```shell
curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

{"count":0,"node":{"key":"\/apisix\/services","dir":true,"nodes":[]},"action":"get"}
```

**Comment by LancCJ** [comment]
Let me describe my error mode installation process.First, I clone the address code directly https://github.com/apache/apisix.Then switch to release/2.14.I follow the document https://apisix.apache.org/zh/docs/apisix/2.13/how-to-build#%E9%80%9A%E8%BF%87%E6%BA%90%E7%A0%81%E5%8C%85%E5%AE%89%E8%A3%85  Then an error occurred.

Later, according to @juzhiyuan  `s  opinion,so  i change APISIX_VERSION='2.14.1' reinstall,now it is ok.

**Comment by LancCJ** [comment]
change APISIX_VERSION='2.14.1' reinstall,now it is ok.
