### ISSUE TITLE
feat: apisix discovery for kubernetes support multi service_name

### ISSUE THREAD

**Issue by foxchenlei** [apache/apisix#7202]
### Description

Description
apisix：2.13.1

apisix discovery for kubernetes support multi service_names

```
curl http://127.0.0.1:80/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f8sdfcx7ad84b625c8f1sdfagw32' -X PUT -i -d '
{
    "uri": "/*",                                                         # location path
    "name": "test-test-app-for-kubernetes",     #Name a free reason
    "priority": 100,
    "host": "test.xxxx.cn",                    #Fill in according to your own domain name
    "methods": ["PUT", "GET", "POST", "DELETE", "PATCH", "HEAD", "OPTIONS","CONNECT", "TRACE"],
    "upstream": {
        "timeout": {
          "connect": 6,
          "send": 6,
          "read": 6
        },
        "service_name": "test/test-app:tcp8080;default/app:http",  #Configuration format： namespace/deploy_name:port_name
        "type": "roundrobin",
        "discovery_type": "kubernetes"                   #type use kubernetes
    }
}'

```

Environment
APISIX version (run apisix version): 2.13.1
Operating system (run uname -a): docker
OpenResty / Nginx version (run openresty -V or nginx -V): 19.0.1
etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info): 3.4.15
APISIX Dashboard version, if relevant: 2.13

**Comment by tokers** [comment]
@foxchenlei Could you share with us some scenarios that you might meet?

**Comment by foxchenlei** [comment]
1、My kubernetes network plugin is not stable, So i have to use  host network of pods. There are many service names , they provide same application with different ports.   
2、To avoid http status like  504,502 ..., I can add/delete svc on apisix when pods are  rolling update.

**Comment by tzssangglass** [comment]
If I understand correctly, you deploy many of the same services to deal with network instability (bless at least one of them is a stable service).

IMO, Then this is equivalent to ensuring high availability of the service at the design level instead of relying on k8s, which is not good design and seems redundant.

It may be possible to support multiple service_names, but it's a bit awkward in this scenario.

**Comment by foxchenlei** [comment]
ok,I hope it can be realized. thanks

**Comment by zhixiongdu027** [comment]
> 1、My kubernetes network plugin is not stable, So i have to use host network of pods. There are many service names , they provide same application with different ports.
> 2、To avoid http status like 504,502 ..., I can add/delete svc on apisix when pods are rolling update.

I think this problem should be solved by routing forwarding instead of "support multiple service_names"

**Comment by zhixiongdu027** [comment]
I don't think this is a "multi service name" problem, but a "multi upstream" problem.

**Comment by tokers** [comment]
The use case is not so general IMHO. It's just like a hack way to support multiple service names.

**Comment by jagerzhang** [comment]
你这个场景，还不如应用将主机IP和端口注册到eureka这种注册中心，然后对接APISIX即可，和微服务服务发现差不多的套路。

**Comment by foxchenlei** [comment]
新项目会这么做，老项目无人维护，用注册中心还要修改代码。其实 别的ingress都支持多个svc,例如traefik。而且线上已经这么跑了。这边了解apisix，想平滑迁移，才这么提问

**Comment by foxchenlei** [comment]
感谢回复，我了解下sidecar看看

**Comment by jagerzhang** [comment]
> 感谢回复，我了解下sidecar看看。能方便说下你们生产环境用的哪个sidecar吗

自己写的哈，基于Python或者Golang都可以，功能就是将应用的端口等信息注册到注册中心
