### ISSUE TITLE
feat: As a user, I want to see a more straightforward response when the client certificate is missing

### ISSUE THREAD

**Issue by tokers** [apache/apisix#7214]
### Description

The current response that Apache APISIX returns when the client doesn't provide its certificate (but APISIX requires it) is:

```
HTTP/2 400
date: Thu, 09 Jun 2022 02:29:01 GMT
content-type: text/html; charset=utf-8
content-length: 154
server: APISIX/2.13.1

<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

The response body doesn't show the fundamental reason. Maybe we can change it to: "missing client certificate".

**Comment by spacewander** [comment]
The latest version of APISIX will reject this client during handshake, so there won't be any HTML response but a `certificate verify failed` error in the error log.
https://github.com/apache/apisix/blob/1b0c182ea007acccaabda3c13d7f4102da3944d9/t/node/client-mtls.t#L306
