### ISSUE TITLE
When APISIX_PROFILE is used, no empty judgment is performed, resulting in an unsightly display format of the configuration file name

### ISSUE THREAD

**Issue by sunhao-java** [apache/apisix#7216]
### Description

1. When I am using APISIX_PROFILE, if a value is assigned, it will be displayed as follows
```
    a. config-dp.yaml
    b. config-cp.yaml
    c. ...[others]
```

2. However, when I don't do the assignment, I expect to be `config.yaml`, but I actually get `config-.yaml`.
3. It works fine, but the file names look ugly. As someone with code cleanliness, it's hard to accept it.

**Comment by sunhao-java** [comment]
Assigned to me, I can do it. @gxthrj

**Comment by tzssangglass** [comment]
I have a question, why we need to set `APISIX_PROFILE` to empty string, we can `unset APISIX_PROFILE` to unset the environment variable.

**Comment by sunhao-java** [comment]
We customized the dockerfile of apisix.
```
ENV \
    # The role of the apisix cluster. If dp and cp are not distinguished, the environment variable can be omitted or empty.
    APISIX_PROFILE="" \
```

The advantage of this is that when using the docker image, docker will remind the user which environment variables need to be set.

As mentioned above, when you do not need to distinguish between dp cp, you do not need to set this environment variable, that is, the default value of the environment variable is used, that is, an empty string.

That's why setting APISIX PROFILE to empty string appears.

**Comment by tzssangglass** [comment]
> The advantage of this is that when using the docker image, docker will remind the user which environment variables need to be set.

useful

**Comment by sunhao-java** [comment]
Thanks for your recognition. 😄

**Comment by sunhao-java** [comment]
> > The advantage of this is that when using the docker image, docker will remind the user which environment variables need to be set.
> 
> useful

Thanks for your recognition. 😄
