### ISSUE TITLE
help request: is there rpm which can be installed on arm ?

### ISSUE THREAD

**Issue by mygrsun** [apache/apisix#7227]
### Description

is there rpm which can be installed on arm

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Do you mean arm32 or arm64?

**Comment by mygrsun** [comment]
i want the arm64

**Comment by mygrsun** [comment]
> Do you mean arm32 or arm64?

i want the arm64

**Comment by spacewander** [comment]
CC @soulbird

**Comment by soulbird** [comment]
This is already in my plan.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.

**Comment by stubbornTanzhe** [comment]
i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo

**Comment by soulbird** [comment]
> i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo @spacewander

Now, you can install apisix under centos arm64:
```shell
yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
yum install -y apisix
```

**Comment by Liu-Junlin** [comment]
> > i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo @spacewander
> 
> Now, you can install apisix under centos arm64:
> 
> ```shell
> yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> yum install -y apisix
> ```

Very nice.
But Can I download the rpm file by a direct url ? Because my server in Production could not connect to internet ....
@soulbird

**Comment by soulbird** [comment]
> > > i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo @spacewander
> > 
> > 
> > Now, you can install apisix under centos arm64:
> > ```shell
> > yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> > yum install -y apisix
> > ```
> 
> Very nice. But Can I download the rpm file by a direct url ? Because my server in Production could not connect to internet .... @soulbird

Of course you can, but please remember to download the dependencies at the same time
````
https://repos.apiseven.com/packages/centos/7/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
https://repos.apiseven.com/packages/centos/8/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
````

**Comment by Liu-Junlin** [comment]
> > > > i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo @spacewander
> > > 
> > > 
> > > Now, you can install apisix under centos arm64:
> > > ```shell
> > > yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> > > yum install -y apisix
> > > ```
> > 
> > 
> > Very nice. But Can I download the rpm file by a direct url ? Because my server in Production could not connect to internet .... @soulbird
> 
> Of course you can, but please remember to download the dependencies at the same time
> 
> ```
> https://repos.apiseven.com/packages/centos/7/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
> https://repos.apiseven.com/packages/centos/8/aarch64/apisix-$APISIX_VERSION-0.el8.aarch64.rpm
> ```

Thanks very much.

**Comment by stubbornTanzhe** [comment]
> > i can build by build-tool,but it's better if you can provide centos arm64 rpm in api7 repo @spacewander
> 
> Now, you can install apisix under centos arm64:
> 
> ```shell
> yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> yum install -y apisix
> ```

3ks so much

**Comment by xinqing123** [comment]
> > > > 我可以通过构建工具构建，但如果你能在 api7 repo 中提供 centos arm64 rpm 就更好了@spacewander
> > > 
> > > 
> > > 现在，你可以在centos arm64下安装apisix了：
> > > ```shell
> > > yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> > > yum install -y apisix
> > > ```
> > 
> > 
> > 很不错。但是我可以通过直接 url 下载 rpm 文件吗？因为我的生产服务器无法连接到互联网....@soulbird
> 
> 当然可以，但是请记得同时下载依赖
> 
> ```
> https://repos.apiseven.com/packages/centos/7/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
> https://repos.apiseven.com/packages/centos/8/aarch64/apisix-$APISIX_VERSION-0.el8.aarch64.rpm
> ```

为什么这个连接我下不下来rpm

**Comment by xinqing123** [comment]
> > > > > 我可以通过构建工具构建，但如果你能在 api7 repo 中提供 centos arm64 rpm 就更好了@spacewander
> > > > 
> > > > 
> > > > 现在，你可以在centos arm64下安装apisix了：
> > > > ```shell
> > > > yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> > > > yum install -y apisix
> > > > ```
> > > 
> > > 
> > > 很不错。但是我可以通过直接 url 下载 rpm 文件吗？因为我的生产服务器无法连接到互联网....@soulbird
> > 
> > 
> > 当然可以，但是请记得同时下载依赖
> > ```
> > https://repos.apiseven.com/packages/centos/7/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
> > https://repos.apiseven.com/packages/centos/8/aarch64/apisix-$APISIX_VERSION-0.el8.aarch64.rpm
> > ```
> 
> 非常感谢。

能问一下，这些依赖包有aarch64的嘛，我没找到openresty的aarch64 的rpm

**Comment by xinqing123** [comment]
> > > > > 我可以通过构建工具构建，但如果你能在 api7 repo 中提供 centos arm64 rpm 就更好了@spacewander
> > > > 
> > > > 
> > > > 现在，你可以在centos arm64下安装apisix了：
> > > > ```shell
> > > > yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
> > > > yum install -y apisix
> > > > ```
> > > 
> > > 
> > > 很不错。但是我可以通过直接 url 下载 rpm 文件吗？因为我的生产服务器无法连接到互联网....@soulbird
> > 
> > 
> > 当然可以，但是请记得同时下载依赖
> > ```
> > https://repos.apiseven.com/packages/centos/7/aarch64/apisix-$APISIX_VERSION-0.el7.aarch64.rpm
> > https://repos.apiseven.com/packages/centos/8/aarch64/apisix-$APISIX_VERSION-0.el8.aarch64.rpm
> > ```
> 
> 非常感谢。

能问一下，这些依赖包有aarch64的嘛，我没找到openresty的aarch64 的rpm

**Comment by soulbird** [comment]
see: https://openresty.org/cn/linux-packages.html
