### ISSUE TITLE
help request: get Grpc transcode from url path

### ISSUE THREAD

**Issue by tomisargiottob** [apache/apisix#7233]
### Description

I am trying to make a request with the format /resource1/:id/resource2 and i have a backend with grpc that expects this id as parameter. I have been trying different combinations between grpc transcode and rewrite-proxy but haven't found a way to make it possible. Is there anything i can do to achieve this? 

When i made a direct grpc transcode, like the example, worked fine, apisix internally calls grpc://localhos:9800 and makes the call to my grpc server. If i try to make any kind of rewriting to the uri before grpc transcode this rewrite is appended to this internal call. As i said before, if a call /resource1/1234/resource2 and there is a uri substitution like this resource1/(.*)/resource2 > ?id=$1, the internal call is made like grpc://localhos:9800?id=1234 and does not work.

Do you have any suggestions for me to try?

### Environment

- APISIX version: 2.14.1-alpine
- Operating system: alpine from docker
- etcd version: 3.4.9
- APISIX Dashboard version, if relevant: 2.13-alpine
- services working with docker

**Comment by tzssangglass** [comment]
it looks unavailable, see: https://github.com/apache/apisix/blob/45816272a80d6d2045259d32acdabbec4039ed1e/apisix/plugins/grpc-transcode/request.lua#L60
