### ISSUE TITLE
performance : upgrading the luajit the CPU increased by 20% ，QPS performance drop 

### ISSUE THREAD

**Issue by fairyqb** [apache/apisix#7242]
### Current Behavior

client:
ab -n10000000 -c100 -k http://www.abc.com/

server:
aspsix apisix-2.10.0-0
luajit2-2.1-20220411
Linux  3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

upgrading the luajit version to luajit2-2.1-20220411 , the CPU increased by 20%, QPS and response time did not change（compared to the old luajit version）

@spacewander @membphis 

### Steps to Reproduce

as above 

### Environment

as above

**Comment by soulbird** [comment]
Did you upgrade the version of luajit separately? I suggest you better use the official openresty version that matches luajit

**Comment by fairyqb** [comment]
> Did you upgrade the version of luajit separately? I suggest you better use the official openresty version that matches luajit

After the upgrade of luajie, it is running normally, but the performance is degraded. I am worried that there will be more problems after upgrading openresty

**Comment by spacewander** [comment]
> compared to the old luajit version

Which version do you mean `the old luajit`?

**Comment by fairyqb** [comment]
luajit in apisix-2.10.0-0

**Comment by fairyqb** [comment]
@spacewander @membphis @moonming @tzssangglass @Firstsawyou

Is there a better idea?

**Comment by fairyqb** [comment]
up

**Comment by tokers** [comment]
@fairyqb In order to reproduce it, we need some details about the Route, Upstream and other settings you configured.

**Comment by membphis** [comment]
@fairyqb you need to provide more information about how to reproduce the problem step by step

this is very important for us if you want to get our help
