### ISSUE TITLE
help request: subpar performance of apisix in kubernetes

### ISSUE THREAD

**Issue by lzxuan** [apache/apisix#7244]
### Description

Following [this Slack thread](https://the-asf.slack.com/archives/CUC5MN17A/p1653900217440819), where I benchmarked APISIX running on a single-node K3s of version `v1.22.10+k3s1` atop `Ubuntu 20.04` VM with `8-core Intel Xeon Processor (Skylake, IBRS)` CPU and `8192MB` memory, the QPS obtained was way below than what was stated in [the official benchmark page](https://apisix.apache.org/docs/apisix/benchmark/#benchmark-test-for-reverse-proxy-enabled-2-plugins). The benchmark result was obtained using `wrk -d 60 --latency` (following [the official benchmark page](https://apisix.apache.org/docs/apisix/benchmark/#benchmark-test-for-reverse-proxy-enabled-2-plugins)):

OpenResty upstream with 1KB response:

| Number of CPU Core | 1        |
|--------------------|:--------:|
| Average Latency    | 178.18us |
| Average Req/Sec    | 30.70k   |

With APISIX (without any plugin enabled):

| Number of CPU Core | 1      | 2        | 4        |
|--------------------|:------:|:--------:|:--------:|
| Average Latency    | 0.94ms | 559.90us | 391.50us |
| Average Req/Sec    | 5.49k  | 9.36k    | 14.62k   |

With APISIX (with only prometheus plugin enabled):

| Number of CPU Core | 1      | 2        | 4        |
|--------------------|:------:|:--------:|:--------:|
| Average Latency    | 1.19ms | 678.52us | 460.13us |
| Average Req/Sec    | 4.29k  | 7.74k    | 12.58k   |

However, I was later being pointed out that the wrk command should be `wrk -d 5 -c 16` (following [the official benchmark script](https://github.com/apache/apisix/blob/master/benchmark/run.sh)). I then reran my benchmark on n1-highcpu-8 (8 vCPUs, 7.2 GB memory) on Google Cloud, with APISIX still running in a K3s cluster. The benchmark result of APISIX with `worker_processes` set to 1 and 2 respectively:

```
$ wrk -d 5 -c 16 http://up.test.com:30080
Running 5s test @ http://up.test.com:30080
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.72ms    1.05ms  32.26ms   99.08%
    Req/Sec     4.79k   497.22     5.71k    70.00%
  47637 requests in 5.00s, 8.72MB read
Requests/sec:   9524.89
Transfer/sec:      1.74MB
```

```
$ wrk -d 5 -c 16 http://up.test.com:30080
Running 5s test @ http://up.test.com:30080
  2 threads and 16 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     0.98ms  448.50us   7.67ms   67.33%
    Req/Sec     8.18k     1.07k   13.57k    73.27%
  82200 requests in 5.10s, 15.05MB read
Requests/sec:  16116.71
Transfer/sec:      2.95MB
```

The QPS did increase but it is highly suspected to be solely due to the change of the wrk command to using more connections, as I obtained similar figures when running the second wrk command on the first Ubuntu VM. Nonetheless, the new QPS obtained is still way below the 15k QPS stated in [the official benchmark page](https://apisix.apache.org/docs/apisix/benchmark/#benchmark-test-for-reverse-proxy-enabled-2-plugins). I wonder is there any way to tune and improve the performance of APISIX in Kubernetes. Thanks!

**Steps to Reproduce:**
1. Create `n1-highcpu-8` compute instance and SSH to it.
2. Install K3s with `curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION='v1.22.10+k3s1' sh -`.
3. Install Helm with `curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash`.
4. Git clone and helm install [apisix](https://github.com/lzxuan/apisix-prometheus-helm-chart).
5. Kubectl apply [upstream](https://gist.github.com/lzxuan/f7dbc9e9a7c30ed273463e1011b77e99).
6. `sudo echo '127.0.0.1 up.test.com' >> /etc/hosts`.
7. Add APISIX route to upstream with host set to `up.test.com`.
8. Install wrk and `wrk -d 5 -c 16 http://up.test.com:30080`.

### Environment

- ASISIX Helm chart version: `0.10.0`
- APISIX version: `2.14.1`
- Operating system: `Linux instance-1 5.13.0-1031-gcp #37~20.04.1-Ubuntu SMP Thu Jun 9 13:25:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- OpenResty version: `1.19.9.1`
- K3s version: `v1.22.10+k3s1`

**Comment by fairyqb** [comment]
@spacewander @membphis @moonming @tzssangglass @Firstsawyou

**Comment by moonming** [comment]
First of all, every major version of Apache APISIX is released, and there will be regressions in performance tests, and there will be no such performance degradation. Therefore, this data is caused by the inappropriate method of your performance test.
Then, during the stress test, check whether the CPU is fully loaded, whether there is an error log, whether there is a problem with the network settings(maybe K3s), etc.
At the same time, you can use perf, flame graph, etc. to find performance problems.

**Comment by lzxuan** [comment]
@moonming Thanks for your reply! First off, I belief the performance of APISIX is not degraded for every release and the result at the official benchmark page holds true. I would be very grateful if you could detail a little more on the inappropriate method of my performance test and perhaps what can be amended.
To add more details, the involved CPU cores were fully loaded during the test, no error log could be found, and the K3s was installed as-is via https://get.k3s.io so it was using the default network settings (I have updated the Steps to Reproduce, thanks for pointing out!). Anything that I can tune in order to obtain more performance?
FYI, I have tried various ways to generate the flame graph, including stapxx, systemtap, perf and BPF Compiler Collection, however I could not get the symbols resolved, since it was running in K3s. Would deeply appreciate if you could enlighten me!!
Thanks again.

**Comment by tzssangglass** [comment]
First of all, the official test benchmark is based on cloud servers, while your test is based on virtualization (k8s or k3s).

As a rule of thumb, performance testing in virtualized containers requires tuning of virtualization platform or container parameters (which I am not very familiar with).

BTW, we will be discussing performance testing related topics in our community meetings, ref: https://github.com/apache/apisix/discussions/7241

**Comment by lzxuan** [comment]
@tzssangglass I see, thanks a bunch!
