### ISSUE TITLE
request help: skywalking-logger and error-log-logger plugin service_instance_name set $hostname invalid

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#7251]
### Current Behavior

skywalking-logger and error-log-logger plugins set service_instance_name to `$hostname` and report to skywalking

instance is represented as `"$hostname"`string

![image](https://user-images.githubusercontent.com/41516298/173565702-ae0dd183-0482-41a1-af13-6c7bd2242188.png)

### Expected Behavior

Expect service instances to be a string of $hostname instead of "$hostname" after reporting to Skywalking

![image](https://user-images.githubusercontent.com/41516298/173566195-41a69254-58a8-4ddb-96d2-f05f50b1de6e.png)

### Error Logs

no error logs

### Steps to Reproduce

We can refer to the skywalking plugin processing method

https://github.com/apache/apisix/blob/45816272a80d6d2045259d32acdabbec4039ed1e/apisix/plugins/skywalking.lua#L130-L132

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Linux apisix-844457679-8242t 5.10.102.1-microsoft-standard-WSL2+ #1 SMP Mon Jun 13 04:56:19 UTC 2022 x86_64 Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
It was originally designed that way, but I think it's a good idea.

@dickens7 PR is welcome!

**Comment by dickens7** [comment]
assign me
