### ISSUE TITLE
help request: Questions about code of CORS plugin

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#7255]
### Description

```
if conf.allow_headers == "**" then
    core.response.set_header("Access-Control-Allow-Headers",
        core.request.header(ctx, "Access-Control-Request-Headers"))
else
    core.response.set_header("Access-Control-Allow-Headers", conf.allow_headers)
end
```

I'm confused，why set the response header `Access-Control-Allow-Headers` as `Access-Control-Request-Headers` when ’allow_headers‘  is ‘**’. If the value of `Access-Control-Request-Headers` is null, the value of `Access-Control-Allow-Headers` will be null too, and then leads to problems

### Environment

- APISIX version (run `apisix version`): 2.10
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> the value of `Access-Control-Allow-Headers` will be null too, and then leads to problems

Please give examples

**Comment by aiyiyi121** [comment]
> > the value of `Access-Control-Allow-Headers` will be null too, and then leads to problems
> 
> Please give examples

When the upstream server has added the cors response header, but there is no `Access-Control-Request-Headers`，apisix wiil set `Access-Control-Allow-Headers` to null

**Comment by jwrookie** [comment]
Why do you need to set cors headers by upstream services when the cors plugin is already in use ?

**Comment by aiyiyi121** [comment]
> Why do you need to set cors headers by upstream services when the cors plugin is already in use ?

The upstream server has added the cors headers, we can't modify the upstream easily because it's very old. 
I meet up  a problem, apisix will lost the cors header when I use `http` to request the `https` upstream server, so I attempt to add cors by apisix. but I find `Access-Control-Allow-Headers` will be set to null.

**Comment by jwrookie** [comment]
I don't understand what you mean, can setting `allow_headers` solve your problem?

**Comment by tzssangglass** [comment]
> The upstream server has added the cors headers, we can't modify the upstream easily because it's very old.

In this case I suggest you modify the plugin yourself to meet your needs.

**Comment by aiyiyi121** [comment]
> > The upstream server has added the cors headers, we can't modify the upstream easily because it's very old.
> 
> In this case I suggest you modify the plugin yourself to meet your needs.

ok, thanks. I have soloved the problem by http to https plugin. I am still confused about the code of cors plugin as described above， but that doesn't matter.
