### ISSUE TITLE
bug:  read header may cause an abnormally high CPU

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#7258]
### Current Behavior

currently, apisix gets the "X-Forwarded-Proto" header when calling the set_upstream_headers function,

https://github.com/apache/apisix/blob/master/apisix/init.lua#L228-L239

but it reads all the headers first, which may cause the CPU to rise abnormally if the number of headers is very large and the size is large

https://github.com/apache/apisix/blob/master/apisix/core/request.lua#L45-L66

<img width="1888" alt="image" src="https://user-images.githubusercontent.com/17425270/173836187-b2680e9f-9d34-45af-865e-7f03ca585790.png">

### Steps to Reproduce

none

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
It will just get the whole headers one time as we don't change the headers. Then the headers table will be cached in memory.

**Comment by zuiyangqingzhou** [comment]
I konw what you mean,  I mean whether it is necessary to get all the headers on some critical path, especially if the number of heads is large.

**Comment by soulbird** [comment]
> I konw what you mean, I mean whether it is necessary to get all the headers on some critical path, especially if the number of heads is large.

It seems that there isn't necessary to call it here, what about changing it to this?

`local hdr = api_ctx.var.http_x_forwarded_proto`

**Comment by tzssangglass** [comment]
> It seems that there isn't necessary to call it here, what about changing it to this?

It's a question of balance.

case 1: If the request gets only one header here in APISIX, then it is fastest to get it directly.

case 2: If the request gets other headers in other plugins or features of APISIX then caching the headers is better.
Because `ctx.var.http_x_forwarded_proto` reads variables directly from C land to Lua land, which is slower than fetching from the cache.

**Comment by soulbird** [comment]
We can cache headers on non-critical code paths, such as calling `core.request.get_header` in the plugin. Here, I think it is enough to get only one of the request headers we need.

**Comment by tzssangglass** [comment]
> `core.request.get_header` in the plugin. Here, I think it is enough to get only one of the request headers we need.

fair enough
