### ISSUE TITLE
feat: As a user, I want to add header rewriting to traffict_split plugin, so that it simplifies the setting of multiple lanes

### ISSUE THREAD

**Issue by hexiaofeng** [apache/apisix#7260]
### Description

As a user, I want to add header rewriting to traffict_split plugin, so that it simplifies the setting of multiple lanes。

{
    "uri": "/index.html",
    "plugins": {
        "traffic-split": {
            "rules": [
                {
                    "weighted_upstreams": [
                        {
                            "upstream": {
                                "name": "upstream_A",
                                "type": "roundrobin",
                                "nodes": {
                                    "127.0.0.1:1981":10
                                },
                                "timeout": {
                                    "connect": 15,
                                    "send": 15,
                                    "read": 15
                                }
                            },
                           "headers":{
                               "X-lane": "A"
                            },
                            "weight": 1
                        },
                        {
                            "headers":{
                               "X-lane": "B"
                            },
                            "weight": 1
                        }
                    ]
                }
            ]
        }
    },
    "upstream": {
            "type": "roundrobin",
            "nodes": {
                "127.0.0.1:1980": 1
            }
    }
}'

**Comment by tokers** [comment]
@hexiaofeng What's the use case about the change?

**Comment by hexiaofeng** [comment]
用于多泳道和全链路灰度场景，流量带上泳道标签，调用对应泳道的后端服务，后端微服务采用全链路跟踪技术透传泳道标签，持续调用泳道内的分组实例。

**Comment by tokers** [comment]
> 用于多泳道和全链路灰度场景，流量带上泳道标签，调用对应泳道的后端服务，后端微服务采用全链路跟踪技术透传泳道标签，持续调用泳道内的分组实例。

Fair enough, @spacewander What's your opinion?

**Comment by spacewander** [comment]
LGTM. Although I would like to add upstream-level plugins (proxy-rewrite per upstream).

**Comment by spacewander** [comment]
Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.

**Comment by tokers** [comment]
> Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.

Sounds good.

**Comment by tzssangglass** [comment]
> Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.

LGTM

**Comment by hexiaofeng** [comment]
> Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.

我期望也能在traffic-split增加。当跨k8s集群流量分发的时候，apisix会部署一份在k8s集群外，另外每个k8s集群的ingress复用是同一份，upstream这个时候无法区分泳道。

**Comment by tzssangglass** [comment]
So let's just add it directly to `traffic-split` first?

**Comment by tokers** [comment]
> So let's just add it directly to `traffic-split` first?

Even we do it on this plugin, we still need to consider the code reusability, so that we can migrate to the new way easily.

**Comment by spacewander** [comment]
> > Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.
> 
> 我期望也能在traffic-split增加。当跨k8s集群流量分发的时候，apisix会部署一份在k8s集群外，另外每个k8s集群的ingress复用是同一份，upstream这个时候无法区分泳道。

@hexiaofeng 
Will you give it a try?

**Comment by hexiaofeng** [comment]
> > > Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.
> > 
> > 
> > 我期望也能在traffic-split增加。当跨k8s集群流量分发的时候，apisix会部署一份在k8s集群外，另外每个k8s集群的ingress复用是同一份，upstream这个时候无法区分泳道。
> 
> @hexiaofeng Will you give it a try?

We have used this architecture

**Comment by god12311** [comment]
> > Or put the headers field to the upstream object, so we can use it in a more general way, not just traffic-split.
> 
> 我期望也能在traffic-split增加。当跨k8s集群流量分发的时候，apisix会部署一份在k8s集群外，另外每个k8s集群的ingress复用是同一份，upstream这个时候无法区分泳道。

你好，想请教下你们这个问题你们是怎么解决的？
