### ISSUE TITLE
bug: http method rewrite not works in proxy-rewrite plugin

### ISSUE THREAD

**Issue by mojerro** [apache/apisix#7261]
### Current Behavior

![image](https://user-images.githubusercontent.com/15071824/174016296-40024eeb-53b1-404a-ace2-18beac38f54d.png)

As the settings above, the route still uses `POST` method instead of `GET` method to the upstream

![image](https://user-images.githubusercontent.com/15071824/174017019-8565af4e-6f6b-4ef7-bcb1-fa5e6905770c.png)

### Expected Behavior

any routes matches the rule will change to `GET` method

### Error Logs

no error

### Steps to Reproduce

as above

### Environment

- APISIX version (run `apisix version`): 2.12.0 using docker image `apache/apisix:2.12.0-alpine`
- Operating system (run `uname -a`): `Linux 11111 4.15.0-163-generic #171-Ubuntu SMP Fri Nov 5 11:55:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by mojerro** [comment]
@soulbird dashboard version is 2.10.1

@tokers I think I know what I did, and I test the route by using the postman which works well. And 404 is from my backend docker  container, so it's true that the request reach the endpoint.

**Comment by mojerro** [comment]
I also check the json store in apisix using admin API, everything looks well just like the document shows

**Comment by tokers** [comment]
> @mojerro Your URI path is not correct, it should be `/server/specs/graphql/*`. I guess the `404` is returned by APISIX since it doesn't know which route should be used for this request.

Ignore it.

**Comment by mojerro** [comment]
Can you reproduce this problem or some extra information I need to provide

**Comment by tokers** [comment]
@mojerro I just checked the changelog, this problem was fixed since `2.13.0`, see https://github.com/apache/apisix/blob/master/CHANGELOG.md#2130.

**Comment by soulbird** [comment]
Fixed in https://github.com/apache/apisix/pull/6300. Please upgrade apisix and dashboard.

**Comment by tzssangglass** [comment]
considered as solved, feel free to reopen if you need.

**Comment by mojerro** [comment]
thanks a lot~
