### ISSUE TITLE
bug: document page 404 not found

### ISSUE THREAD

**Issue by jagerzhang** [apache/apisix#7263]
### Current Behavior

这个页面404了：
https://apisix.apache.org/zh/docs/terminology/plugin#%E7%83%AD%E5%8A%A0%E8%BD%BD

看代码是有这个文件的：
https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/plugin.md
https://github.com/apache/apisix/blob/master/docs/zh/latest/terminology/plugin.md

### Steps to Reproduce

null

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by SylviaBABY** [comment]
@jagerzhang Thanks for your reminder^^
We are locating the issue and will handle it later

**Comment by SylviaBABY** [comment]
@jagerzhang is this link appears in the FAQ document?

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/39793568/174275962-c3aae833-5713-489d-ae19-56191664ab83.png">

**Comment by juzhiyuan** [comment]
Hi, I just had a check: the correct link should be `/zh/docs/apisix/terminology/plugin` instead of `/zh/docs/terminology/apisix`, it misses the `/apisix` part. May I know which play you found this URL?

**Comment by jagerzhang** [comment]
> @jagerzhang is this link appears in the FAQ document?
> 
> <img alt="image" width="1023" src="https://user-images.githubusercontent.com/39793568/174275962-c3aae833-5713-489d-ae19-56191664ab83.png">

嗯，没记错的话应该是这里点过去的。

抱歉，忘记给Referer页面了。

**Comment by SylviaBABY** [comment]
> > @jagerzhang is this link appears in the FAQ document?
> > <img alt="image" width="1023" src="https://github.com/assets/39793568/c3aae833-5713-489d-ae19-56191664ab83">
> 
> 嗯，没记错的话应该是这里点过去的。
> 
> 抱歉，忘记给Referer页面了。

没事的，我们测试的时候也是找的这个入口。但是只有我这边在前几次点开该处时会出现你提到的「404」现象，其他同学点开这里都是正常的；之后我把浏览器关闭再重新打开 QA 页面然后点击该处链接后，发现页面呈现是正常的（尝试更换浏览器也是显示正常）

不知道你现在打开这里的超链接还是显示 404 吗？

**Comment by jagerzhang** [comment]
> > > @jagerzhang is this link appears in the FAQ document?
> > > <img alt="image" width="1023" src="https://github.com/assets/39793568/c3aae833-5713-489d-ae19-56191664ab83">
> > 
> > 
> > 嗯，没记错的话应该是这里点过去的。
> > 抱歉，忘记给Referer页面了。
> 
> 没事的，我们测试的时候也是找的这个入口。但是只有我这边在前几次点开该处时会出现你提到的「404」现象，其他同学点开这里都是正常的；之后我把浏览器关闭再重新打开 QA 页面然后点击该处链接后，发现页面呈现是正常的（尝试更换浏览器也是显示正常）
> 
> 不知道你现在打开这里的超链接还是显示 404 吗？

刷新浏览器缓存之后已经好了，我看到超链接已经换成 https://apisix.apache.org/zh/docs/apisix/terminology/plugin#%E7%83%AD%E5%8A%A0%E8%BD%BD，这个是正确的~

**Comment by juzhiyuan** [comment]
Great! Then I will close this issue :)
