### ISSUE TITLE
help request: prometheus error, `no memory while logging request`

### ISSUE THREAD

**Issue by kongjun01** [apache/apisix#7264]
### Description

The nginx configuration is set to the `lua_shared_dict prometheus-metrics 200m`, and after running for about 1 month, the prometheus plugin reports an error: `Unexpected error adding a key: no memory while logging request`. When the prometheus data is consumed, will the corresponding memory data be cleared?

### Environment

- APISIX version (run `apisix version`):2.10.5
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
The shared memory used to store Prometheus metrics is pre-allocated and the size is fixed, so when you have more and more routes, the number of metrics will be tremendous. You may need to calculate a proper size to store the metrics.

**Comment by kongjun01** [comment]
ok
