### ISSUE TITLE
feat: some question about kafka-logger

### ISSUE THREAD

**Issue by mikawudi** [apache/apisix#7267]
### Description

about kafka-logger plugin
1) in kafka, “key” will decide message route to what partition
but in kafka-logger plugin, key params only is a const str......
i think if key param can support exp for get value from variable, it will be more useful!

2) the second question is about message format of kafka-logger
when i use batch_max_size = 1, the message send to kafka is a json object
but when batch_max_size > 1, the message is a json array
```lua
if batch_max_size == 1 then
    data = entries[1]
    if type(data) ~= "string" then
        data, err = core.json.encode(data) -- encode as single {}
    end
else
    data, err = core.json.encode(entries) -- encode as array [{}]
end
```
as a kafka consumer.....befor i parse message and consume it, i need know apisix how to config batch_max_size? i think it not unreasonable

3) lua-resty-kafka have ringbuffer and sendbuffer....in kafka-logger plugin i think the “batch_max_size > 1” is not need to exist?

**Comment by spacewander** [comment]
> in kafka, “key” will decide message route to what partition
but in kafka-logger plugin, key params only is a const str......
i think if key param can support exp for get value from variable, it will be more useful!

PR is welcome!

> the second question is about message format of kafka-logger

It is a historical legacy.

> lua-resty-kafka have ringbuffer and sendbuffer....in kafka-logger plugin i think the “batch_max_size > 1” is not need to exist?

They are buffers in different places.

**Comment by mikawudi** [comment]
ok, will try to impl first item~
