### ISSUE TITLE
limit-count 全局限流功能

### ISSUE THREAD

**Issue by JunpengLi2017** [apache/apisix#7272]
### Description

如图，我配置了在route上配置redis全局限流，apisix节点为三个
![image](https://user-images.githubusercontent.com/34274920/174226218-12a5869a-a7a3-4a7c-baa7-410ed8325ff0.png)
但是最后全局限流没有生效，仍然是apisix单节点限流。且查看redis上的key数量和apisix节点数量相同，所以想问下是什么情况，是我这边还漏了什么配置步骤吗？
![image](https://user-images.githubusercontent.com/34274920/174226545-d60035cf-0615-4a52-9e87-1b54e2268d00.png)

### Environment

- APISIX version (2.10):

**Comment by tokers** [comment]
Looks like the limit key is not the same, are you sure the three apisix nodes connect to the cluster?

**Comment by JunpengLi2017** [comment]
> Looks like the limit key is not the same, are you sure the three apisix nodes connect to the cluster?

yes, three apisix nodes connet the same redis ,but not redis cluster。

**Comment by tokers** [comment]
> 

Sorry, I mean does these three nodes connect to the ETCD cluster normally?

**Comment by JunpengLi2017** [comment]
> > 
> 
> Sorry, I mean does these three nodes connect to the ETCD cluster normally?

how to check  ? if I add  apisix node,the redis add the same count.

**Comment by tokers** [comment]
> > > 
> > 
> > 
> > Sorry, I mean does these three nodes connect to the ETCD cluster normally?
> 
> how to check ? if I add apisix node,the redis add the same count.

Could you just check the error log file for each APISIX nodes? You can filter the log entries on the `error` level.

**Comment by tzssangglass** [comment]
any error logs about it?

**Comment by xuminwlt** [comment]
Look at the redis key，It's concat with 3 part, and the last is number 4/6/7，what the mean of the last one.
