### ISSUE TITLE
help request: Why can't I find authz-casdoor plugin?

### ISSUE THREAD

**Issue by saltwang** [apache/apisix#7279]
### Description

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/21987254/174550569-fb9eb6bb-9a1a-4efa-8257-12772e363097.png">

In the apisix container, I can find authz-casdoor.lua:
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/21987254/174551041-93502d4b-720b-4c2d-85be-bb84b91717df.png">

In config-default.yaml:
![image](https://user-images.githubusercontent.com/21987254/174552614-c4c6fc20-43d3-4453-a7c7-2fc4323f41a2.png)

### Environment

- APISIX version (run `apisix version`): 2.14.1
  apache/apisix                                                 2.14.1-alpine    382ae3df093d   3 weeks ago     148MB
- Operating system (run `uname -a`): use docker-compose to set up: https://apisix.apache.org/zh/docs/apisix/how-to-build
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by tokers** [comment]
The APISIX Dashboard `2.13.0` doesn't contain this plugin. cc @bzp2010

**Comment by saltwang** [comment]
> The APISIX Dashboard `2.13.0` doesn't contain this plugin. cc @bzp2010

OK，thank you！

BTW, which version will contain the plugin?

**Comment by tzssangglass** [comment]
> BTW, which version will contain the plugin?

2.14.1

**Comment by airclear** [comment]
@tzssangglass 

env  same as @saltwang ,   

I use curl to config the route  casdoor plugin ,  result like this:

`{"code":10000,"message":"schema validate failed: schema not found, path: plugins.authz-casdoor","data":null,"request_id":"b6be9eda-bd71-453f-a178-6462ed32b5f7"}`


curl: 

```
curl "http://apisix.xxxx.com:32380/apisix/admin/routes/3a8b12cf"  -H 'Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc2ODQ4NjIsImlhdCI6MTY1NzY4MTI2Miwic3ViIjoiYWRtaW4ifQ.34vkMLKyjVjUQ5eC0Y9kCqEv98BvkmbXE6gw5-3Dkvk' -X PUT -d '
{
  "uri": "/anything/*",
  "name": "casdoor-httpbin",
  "methods": ["GET"],
  "host": "httpbin.xxxx.com",
  "plugins": {
    "authz-casdoor": {
        "endpoint_addr":"http://10.200.180.82:7001",
        "callback_url":"http://httpbin.xxxx.com:32380/anything/callback",
        "client_id":"223c6180503181a2da92",
        "client_secret":"b9add612d0142bfa3f9bd62cf0013e9cfbdd82ff"
    }
  },
  "upstream_id": "5ce57b8e",
  "status": 1
}'
```
