### ISSUE TITLE
help request: deploy Dapr with APISIX

### ISSUE THREAD

**Issue by michaelh1355** [apache/apisix#7283]
### Description

I need to study deploy Dapr (host mode) + APISIX on my local. there any relevant document reference？ 

thanks!

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
See #7274 , These two are the same issue.

**Comment by moonming** [comment]
https://apisix.apache.org/blog/2021/11/17/dapr-with-apisix/ please take a look

**Comment by moonming** [comment]
and here is the Chinese version https://apisix.apache.org/zh/blog/2021/11/17/dapr-with-apisix/

**Comment by michaelh1355** [comment]
thank you  @moonming

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this if needed.
