### ISSUE TITLE
help request: apisix java pligin run response.setStatusCode(401) invalid ,No actual interception

### ISSUE THREAD

**Issue by object777** [apache/apisix#7299]
### Description

@Component
public class FooFilter implements PluginFilter {

    private final Logger logger = LoggerFactory.getLogger(FooFilter.class);

    @Override
    public String name() {
        return "FooFilter";
    }

    @Override
    public void filter(HttpRequest request, HttpResponse response, PluginFilterChain chain) {
        response.setStatusCode(401);
        chain.filter(request, response);
  }
@Override
    public List<String> requiredVars() {
        List<String> vars = new ArrayList<>();
        vars.add("remote_addr");
        vars.add("server_port");
        return vars;
    }

    @Override
    public Boolean requiredBody() {
        return true;
    }
}

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by object777** [comment]
HTTP/1.1 200 OK
Content-Length: 12
Connection: keep-alive
Content-Type: text/plain; charset=utf-8
Date: Wed, 22 Jun 2022 02:25:25 GMT
Keep-Alive: timeout=4
Proxy-Connection: keep-alive
Server: APISIX/2.12.1

**Comment by Xusq513** [comment]
@object777 what is the answer for this question ？I also have the problem.
