### ISSUE TITLE
help request:  Does stream proxy support access log in 2.10.x ?

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#7300]
### Description

It seem doesn't support access.log
```
  stream_proxy:                  # TCP/UDP proxy
   only: false                   # use stream proxy only, don't enable HTTP stuff
   tcp:                         # TCP proxy port list
     - addr: 9100
       tls: false
     - addr: "127.0.0.1:9101"
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
The feature is first added in 2.12: https://github.com/apache/apisix/commit/71c256be81d95d56ea38f9874699801cbbad6a2e

**Comment by tzssangglass** [comment]
feel free to add documentation to introduce this feature

**Comment by Chever-John** [comment]
@tzssangglass I am adding more info to improve it.
