### ISSUE TITLE
help request: Mac M1  make run error 

### ISSUE THREAD

**Issue by Louis2014** [apache/apisix#7313]
### Description

2022/06/23 14:39:24 [error] 6267#135075: init_worker_by_lua error: ...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: NYI: cannot call this C function (yet)
stack traceback:
	[C]: in function 'ngx_lua_ffi_shdict_get'
	...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: in function 'get'
	...space/apisix//deps/share/lua/5.1/resty/worker/events.lua:119: in function 'get_event_id'
	...space/apisix//deps/share/lua/5.1/resty/worker/events.lua:610: in function 'configure'
	...rs/louis/Documents/idea_workspace/apisix/apisix/init.lua:112: in function 'http_init_worker'
	init_worker_by_lua:2: in main chunk

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
See https://github.com/openresty/lua-nginx-module/pull/2037

You can wait for the next release of OpenResty or build it yourselves.

**Comment by Louis2014** [comment]
thanks

**Comment by tzssangglass** [comment]
> > See [openresty/lua-nginx-module#2037](https://github.com/openresty/lua-nginx-module/pull/2037)
> > You can wait for the next release of OpenResty or build it yourselves.
> 
> How to build the latest of lua-nginx-module and install into my OpenResty Environment?

You can see how to compile OpenResty here: https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base-debug-centos7.sh

**Comment by Louis2014** [comment]
> https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base-debug-centos7.sh

Thanks

**Comment by lujiajing1126** [comment]
Just a comment. I also suffered from this issue recently. I finally work out by applying the following two patches,

 - https://github.com/openresty/lua-resty-core/commit/da705fcaaf85f351fa87480816b4f41a65fc4bd5.patch
 - https://github.com/openresty/lua-nginx-module/commit/653d6a36f46b077cb902d7ba40824c299cf9bbf4.patch

Download the latest `openresty-1.21.4.1.tar.gz` tarball and these two patches. Then run `git apply` in the corresponding modules' directories. Follow the build steps from Homebrew Formula https://github.com/openresty/homebrew-brew/blob/HEAD/Formula/openresty.rb

Thanks to @zhuizhuhaomeng
