### ISSUE TITLE
bug: prometheus插件无法监听0.0.0.0

### ISSUE THREAD

**Issue by chenjinxuan** [apache/apisix#7321]
### Current Behavior

我想要将prometheus端口通过svc暴露出去，于是在apisix的conf.yaml里设置
      plugin_attr:
        prometheus:
           export_addr:
              ip: "0.0.0.0"
              port: 9091
然后重启pod，但是在其他pod访问这个pod的ip:9091 报curl: (7) Failed to connect to 10.10.27.89 port 9091: Connection refused
并且，我进去apisix的pod里
1 用pod ip 0.10.27.89:9091 不通
2 用127.0.0.1:9091 能通
3 用pod ip 0.10.27.89:9080 能通

### Expected Behavior

在pod内部和通过svc都能访问到prometheus暴露的9091端口

### Steps to Reproduce

配置
      plugin_attr:
        prometheus:
           export_addr:
              ip: "0.0.0.0"
              port: 9091

开启prometheus全局插件

### Environment

- APISIX version (run `apisix version`): 2.13.0
- Operating system (run `uname -a`): 容器
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by chenjinxuan** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/25172225/175481627-ab1768fb-3640-4a31-8bd4-2040b8193f05.png">

**Comment by tzssangglass** [comment]
0901 mapped out of the container?

**Comment by chenjinxuan** [comment]
> 

<img width="274" alt="image" src="https://user-images.githubusercontent.com/25172225/175502281-4a3ca4a9-c3b4-4493-ad89-e89553445eb5.png">

**Comment by tokers** [comment]
@chenjinxuan The port statement doesn't affect if the port can be accessed from the outside of container. We use the same way to export the prometheus endpoint and it can be accessed successfully.

**Comment by chenjinxuan** [comment]
> @chenjinxuan The port statement doesn't affect if the port can be accessed from the outside of container. We use the same way to export the prometheus endpoint and it can be accessed successfully.

但是我这边就是没有生效，非常奇怪，有什么需要注意的点么

**Comment by chenjinxuan** [comment]
上面的配置是正确的，是我搞错了，在配置文件里配置了两份plugin_attr
