### ISSUE TITLE
feat: As a user, I want to have a backup upstream in route

### ISSUE THREAD

**Issue by worldwonderer** [apache/apisix#7335]
### Description

As a user, I want to have a backup upstream like(backup_upstream_id) in route, so that when first choice upstream returns error i can use the backup one. It is different from retrying nodes in upstream.

**Comment by tokers** [comment]
@worldwonderer Try to use the node priority feature? https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-3

FYI:

> Each node can be configured with a priority. A node with low priority will only be used when all the nodes with higher priority have been tried or are unavailable.
> 
> As the default priority is 0, nodes with negative priority can be configured as a backup.
