### ISSUE TITLE
docs: Add descriptions for "APISIX Architecture" docs

### ISSUE THREAD

**Issue by pottekkat** [apache/apisix#7336]
### Current State

The [APISIX Architecture](https://apisix.apache.org/docs/apisix/next/architecture-design/apisix) page only has diagrams without any explanations or descriptions.

### Desired State

Add a description to the diagrams so that the reader can understand the architecture and how everything works.

**Comment by FavourDaniel** [comment]
@navendu-pottekkat Can I be assigned to this issue?

**Comment by navendu-pottekkat** [comment]
@FavourDaniel You can share a draft of what this would look like and I will assign this to you.
