### ISSUE TITLE
uri-blocker works on consumers

### ISSUE THREAD

**Issue by caster-Q** [apache/apisix#7343]
测试了一下，目前貌似uri-blocker仅支持配置在route上，配置在consumer上是无效的。
请问能否像limit-req插件那样，让uri-blocker可以作用在consumer层面，已达到不同的consumers可以访问不同URL的限制

**Comment by tokers** [comment]
@caster-Q It looks like you can use the consumer-constriction plugin.

**Comment by caster-Q** [comment]
consumer-constriction 只能控制哪些consumer能不能访问route，不能控制具体哪些url；
我的问题是uri-blocker能否向limit-req插件一样作用于某个consumer上，而不是只能作用在route上

**Comment by caster-Q** [comment]
@tokers

**Comment by tokers** [comment]
Currently nope.

**Comment by tzssangglass** [comment]
> 目前貌似uri-blocker仅支持配置在route上，配置在consumer上是无效的

What version are you using?
After this PR #6502 is merged, it should fix the problem.

**Comment by caster-Q** [comment]
> 

thanks

**Comment by caster-Q** [comment]
> > 目前貌似uri-blocker仅支持配置在route上，配置在consumer上是无效的
> 
> What version are you using? After this PR #6502 is merged, it should fix the problem.

uri-blocker is not auth  type，it not fix
