### ISSUE TITLE
help request: when will the v1.13.2 docker image push to the docker hub?

### ISSUE THREAD

**Issue by xianshun163** [apache/apisix#7345]
### Description

help request: when will the v1.13.2 docker image push to the docker hub?

### Environment

- APISIX version (run `apisix version`):v1.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@tzssangglass

**Comment by tzssangglass** [comment]
you mean 2.13.2? maybe within 48 hours

**Comment by xianshun163** [comment]
o, yes,   v2.13.2

**Comment by tzssangglass** [comment]
already available: https://hub.docker.com/r/apache/apisix/tags?page=1&name=2.13.2
