### ISSUE TITLE
bug:apisix2.14.1使用rpm离线安装时报错

### ISSUE THREAD

**Issue by zfxz** [apache/apisix#7346]
### Current Behavior

apisix2.14.1使用rpm离线安装时apisix-base报错，安装后执行apisix相关命令报错

### Steps to Reproduce

![dc2a7e20492c470ce9e080d95e8def5](https://user-images.githubusercontent.com/108332888/176150789-e304dfa7-a3b8-4b74-ab57-261be7da40ff.jpg)

### Environment

- APISIX 2.14.1(run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
There was some problem with the rpm repository last night, but it is now fixed and you can retry it once in its entirety.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.
