### ISSUE TITLE
request help: mac M1 can not start apisix via './bin/apisix start'

### ISSUE THREAD

**Issue by chenyyyang** [apache/apisix#7350]
### Description

➜  apache-apisix-2.14.1-src ./bin/apisix start 
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start
'http_stub_status_module' module is missing in your openresty, please check it out. Without this module, there will be fewer monitoring indicators.
nginx: [emerg] unknown directive "real_ip_header" in /Users/xxx/Desktop/IdeaProjects/apisix/apache-apisix-2.14.1-src/conf/nginx.conf:122

➜  apache-apisix-2.14.1-src openresty -v
nginx version: openresty/1.21.4.1

### Environment

<img width="229" alt="image" src="https://user-images.githubusercontent.com/22273370/176377239-f8316a9f-e34d-4ed7-a5a5-6d91668367ad.png">

**Comment by tokers** [comment]
@chenyyyang How did you install APISIX?

**Comment by tzssangglass** [comment]
1. You need to give the complete process of building APISIX and apisix-base, from the error report it seems that `http_stub_status_module` is missing when building apisix-base.
2. Environmental information needs to be text, not a picture of the operating system.

**Comment by chenyyyang** [comment]
Thank you @tzssangglass  @tokers 
I have solved the following issue.
But indicate new problems when i tried to develop Java Plugins.
![Screenshot2022_06_29_192350](https://user-images.githubusercontent.com/22273370/176428917-a47d6e11-e393-44f1-81a2-dde7d0d412a7.jpg)

I think the cause of the problem may be from Netty . I tried to upgrade the version of Netty and netty-transport-native-kqueue,but not work...
refer to : https://github.com/netty/netty/issues/12024#issuecomment-1169849069
Many thanks ~~

**Comment by chenyyyang** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/22273370/176430002-18e101ff-6fd5-40e7-9a4a-e545f6646cda.png">

**Comment by spacewander** [comment]
Close as @tzssangglass has replied in https://github.com/apache/apisix-java-plugin-runner/issues/156
