### ISSUE TITLE
docs: explain the rule of plugin config precedence

### ISSUE THREAD

**Issue by tokers** [apache/apisix#7361]
### Current State

Currently, we can configure plugins on Route, Service, Global Rule, and Consumer. But the precedence between them are not shown in the documents.

Say I configure the `limit-count` plugin on the Consumer and Route.

* Consumer

```json
{
    "plugins": {
        "limit-count": {
            "key": "abc",
            "count": 10
        }
    }
}
```

* Route

```json
{
    "plugins": {
        "limit-count": {
            "key": "abc",
            "count": 20
        }
    }
}
```

Which config for `limit-count` will be used? And what if I have another `limit-count` on the Service and the Service is referenced by the Route?

### Desired State

As a user, I hope there has a document to explain these stuffs.

**Comment by spacewander** [comment]
We can move https://github.com/apache/apisix/discussions/7179#discussioncomment-2903411 to the doc?

**Comment by tokers** [comment]
@spacewander That'd be good, I just look through the diagram, it's clear.
