### ISSUE TITLE
help request: real-ip plugin can't support for grpc proxy

### ISSUE THREAD

**Issue by caozhi6655** [apache/apisix#7363]
### Description

I use apisix for the grpc proxy，and i need to set custom header like X-Real-IP for the grpc header like：
`grpc_set_header X-Real-IP ($remote_addr | OtherParam)`，but I found it can't support for this。
And in the ngx_tpl.lua there is no `proxy_set_header   X-Real-IP         $remote_addr;`

I think apisix now give the grpc proxy support very poor，and I think apisix can't give a config for grpc like：
`
apisix:
    grpc: xxxx
`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
APISIX passes the client IP through `X-Forwarded-For` header, does it solve your problem?

**Comment by bzp2010** [comment]
@tokers

**Comment by bzp2010** [comment]
@tokers 

![image](https://user-images.githubusercontent.com/8078418/176803248-8aca7f3a-8be5-4e6a-9e85-f649d8ee2cf6.png)

I noticed that we use the `@grpc_pass` location to handle the grpc proxy where we don't set as many `XF` series request headers as we do for the http proxy.

**Comment by tokers** [comment]
@bzp2010 That's a moment to change the way we set X-Forwarded-* headers, I think we need an unified way to do that. No matter which protocols the users use.

**Comment by spacewander** [comment]
Since grpc is based on HTTP2, could we solve it with `ngx.req.set_header`?

**Comment by caozhi6655** [comment]
> Since grpc is based on HTTP2, could we solve it with `ngx.req.set_header`?
year，lua can do anything，but i think it becomes a dynamic configuration same good and it is what apisix does。

**Comment by tokers** [comment]
> > Since grpc is based on HTTP2, could we solve it with `ngx.req.set_header`?
> > year，lua can do anything，but i think it becomes a dynamic configuration same good and it is what apisix does。And as a common developer，he needn't to modify the source code。

What we talked is the default behaviors. Of course we need to expose the chance for users via the proxy-rewrite plugin.

**Comment by soulbird** [comment]
Yes I tested it, `ngx.req_set_header` is ok. So we can implement X-Real-IP settings through the` proxy-rewrite` plugin. Like:
```json
{
    "methods": ["POST", "GET"],
    "uri": "/helloworld.Greeter/Echo",
    "plugins": {
        "proxy-rewrite": {
            "headers": {
                "X-Real-IP": "$remote_addr"
            }
        }
    },
    "upstream": {
        "scheme": "grpc",
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:50051": 1
        }
    }
}
```
However, as @tokers  said, maybe we [should move some header setting related logic(https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L702-L725) to lua to get better compatibility.

**Comment by caozhi6655** [comment]
> Yes I tested it, `ngx.req_set_header` is ok. So we can implement X-Real-IP settings through the` proxy-rewrite` plugin. Like:
> 
> ```json
> {
>     "methods": ["POST", "GET"],
>     "uri": "/helloworld.Greeter/Echo",
>     "plugins": {
>         "proxy-rewrite": {
>             "headers": {
>                 "X-Real-IP": "$remote_addr"
>             }
>         }
>     },
>     "upstream": {
>         "scheme": "grpc",
>         "type": "roundrobin",
>         "nodes": {
>             "127.0.0.1:50051": 1
>         }
>     }
> }
> ```
> 
> However, as @tokers said, maybe we should move some [header setting related logic](https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L702-L725) to lua to get better compatibility.

I understand，thanks very much!

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.

**Comment by caozhi6655** [comment]
> Consider solved. Feel free to reopen it if needed.
But the real-ip plugin still can't support for grpc。It can solve the problem in another way，and i think designing a unified way to solve more protocols like grpc、http2 and so on is a better way like @tokens said。I hope it can be implement quickly。
