### ISSUE TITLE
docs: support API Reference for better experience 

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7368]
### Current State

Hi, @navendu-pottekkat, we're using a single Markdown file to contain all APIs here[1], as you can see it's not efficient to read and use.

![image](https://user-images.githubusercontent.com/2106987/176857811-42fa1683-190f-4779-b2c3-09756ec22e25.png)

[1] https://apisix.apache.org/docs/apisix/next/admin-api

### Desired State

How about using API References like redocusaurus[1] or docusaurus-openapi[2]?

![image](https://user-images.githubusercontent.com/2106987/176858400-989a6486-b37f-413a-b8a3-66657cd11efa.png)
![image](https://user-images.githubusercontent.com/2106987/176858425-19e888ec-fcd5-4a5c-bb9e-b2db64d19519.png)

[1] https://redocusaurus.vercel.app/examples/custom-page/
[2] https://docusaurus-openapi.tryingpan.dev/petstore/add-a-new-pet-to-the-store

**Comment by navendu-pottekkat** [comment]
@juzhiyuan Will look into this.

**Comment by navendu-pottekkat** [comment]
@juzhiyuan These are great if we are complying with OpenAPI specs. We can use the Plugin you shared above to automatically generate docs. It might take some configuration to fit it into our theme.

cc @SkyeYoung for input and suggestions.

**Comment by SkyeYoung** [comment]
Do we have these files? 
https://redocusaurus.vercel.app/docs/getting-started/Installation
<img width="400" alt="image" src="https://user-images.githubusercontent.com/48400568/177097205-813559c4-9f24-4790-9473-49735356f794.png">
https://github.com/PaloAltoNetworks/docusaurus-openapi-docs#configuring-docusaurusconfigjs-plugin-and-theme-usage
<img width="400" alt="image" src="https://user-images.githubusercontent.com/48400568/177097592-cb363266-9485-4078-9886-31329532093a.png">

**Comment by navendu-pottekkat** [comment]
Maybe @bzp2010 can give some idea on our current OpenAPI support. Last I checked, he mentioned that it is not perfect.

**Comment by SkyeYoung** [comment]
cc @guoqqqi

**Comment by bzp2010** [comment]
In fact the Admin API does not have an OpenAPI description yet, we need to push this thing first.🤔

**Comment by kayx23** [comment]
related issue https://github.com/apache/apisix/issues/9276

**Comment by navendu-pottekkat** [comment]
Maybe we need a new label in GitHub to suggest this would not be fixed until a dependency is fixed. In this case, we would need OpenAPI support first.

**Comment by kayx23** [comment]
Can this be closed now that we have https://docs.api7.ai/apisix/reference/admin-api?

Or just leave this open for the apache/apisix docs?

**Comment by pottekkat** [comment]
Yeah, +1 to closing this.
