### ISSUE TITLE
docs: optimize debug mode yaml comments

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#7369]
### Current State

the comments debug mode yaml: https://github.com/apache/apisix/blob/master/conf/debug.yaml is not easy to understand, we can optimization according to the corresponding documentation :https://github.com/apache/apisix/blob/master/docs/en/latest/architecture-design/debug-mode.md

### Desired State

 can get a basic idea of how to use it based on the comments in yaml

**Comment by juzhiyuan** [comment]
Hi @tzssangglass, 

1. I would recommend one Chrome extension Grammarly 😄 It could detect text and fix grammar issues, see 

![image](https://user-images.githubusercontent.com/2106987/177043820-6a316d30-49f4-4b13-a7b3-ec09d8f7b5d6.png)

2. To make sure: would you like to update the YAML file for this issue? The most direct way is to link the doc to this file 🤔 but if you could provide more information, @navendu-pottekkat or I could help update this file.

**Comment by tzssangglass** [comment]
> 1. I would recommend one Chrome extension Grammarly 😄 It could detect text and fix grammar issues, see

thanks, I install this extension just now.

> 2\. would you like to update the YAML file for this issue? The most direct way is to link the doc to this file

this YAML: https://github.com/apache/apisix/blob/master/conf/debug.yaml need to be updated.

> 2\. but if you could provide more information (as I don't get your point here)

for example, we can updated: https://github.com/apache/apisix/blob/919ac16d4bbb0350b5efc3b5515206dc69acd427/conf/debug.yaml?rgh-link-date=2022-07-01T09%3A04%3A15Z#L20

to more clearer

**Comment by navendu-pottekkat** [comment]
This would be good. @avinal is also working on improving inline documentation like this. PS: I'm currently working on a proposal that would update all the docs in the "Architecture Design" section. So, the "Debug Mode" page will have some changes.

**Comment by navendu-pottekkat** [comment]
@kayx23 Would you be able to check and take this up?

**Comment by kayx23** [comment]
@navendu-pottekkat I can take a look once I'm onto the debug and troubleshooting doc. Just not there yet.

**Comment by navendu-pottekkat** [comment]
Yes sure. Since you are working on these, it would be consistent if you pick these up as well.
