### ISSUE TITLE
docs: add description for Development environment

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7373]
### Current State

Hey 👋 I clone this repo to my dev server, but I get confused by mixing the `make install` and `make run` commands.

1. Our document doesn't mention the `make run` command: this command could start an apisix server without `apisix cli`; we could also use `make quit` or `make stop` to terminate the server.
2. Sometimes, I will forget to use `make run` but use `make install` and `apisix start` instead, then I will use commands mixed 😂 and have to try different ways to figure out why my configuration doesn't work.

@bzp2010 Could you please give more tips or notes?

### Desired State

How about having a guide like `the recommended ways to develop apisix`? or adding some tips on https://apisix.apache.org/docs/apisix/next/building-apisix? cc @navendu-pottekkat

**Comment by navendu-pottekkat** [comment]
If you follow the documentation (https://apisix.apache.org/docs/apisix/next/building-apisix) you should have `apisix` installed and `apisix init` and `apisix start` should work.

In the Makefile, `make run` will just call the `apisix` binary. So, both `make run` and `apisix run` are the same command. If `apisix start` doesn't work, then it is likely that the binary is not in the path.

So, I think we do not need to change anything here. This whole documentation is the recommended way to develop APISIX. We should only highlight the recommended way in our documentation. There should only be one way we recommend others.

**Comment by juzhiyuan** [comment]
> This whole documentation is the recommended way to develop APISIX.

I agree with this, but @bzp2010 recommended me to use `make run` on Development instead :)

**Comment by navendu-pottekkat** [comment]
@juzhiyuan It might be because the makefile sets the correct path to the APISIX binary.

**Comment by spacewander** [comment]
From my point of view, I would suggest using `./bin/apisix start` directly. The makefile is just a thin wrapper of `apisix` (not a good wrapper as its targets are not 100% equal to the action in `./bin/apisix`.)
