### ISSUE TITLE
bug: "make reload" doesn't regenerate /logs/nginx.conf

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7376]
### Current Behavior

When executing the `make reload` command, it doesn't regenerate the `/logs/nginx.conf` file, we have to use `make quit && make run` to generate the new one.

### Expected Behavior

This command should regenerate the new nginx.conf file.

### Steps to Reproduce

1. Use `make run` to run `apisix` in development mode.
2. Update `config.yaml` file.
3. Use `make reload` to reload the instance.
4. `/logs/nginx.conf` doesn't update as expected.

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): Linux VM-255-10-centos 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: N/A
- Plugin runner version, for issues related to plugin runners: N/A
- LuaRocks version, for installation issues (run `luarocks --version`): N/A

**Comment by tokers** [comment]
Fair enough. Agree +1.

**Comment by spacewander** [comment]
The `make reload` doesn't do the same as `apisix reload`. I just submitted a PR to fix it.
