### ISSUE TITLE
help request: How to decode the request body recorded by `http logger` when content encoding is gzip

### ISSUE THREAD

**Issue by jinnyu** [apache/apisix#7389]
### Description

I use `http-logger` to record the request log, 
and some upstream returns the content in gzip format(`Content-Encoding`).
After passing through `http-logger`, the content is garbled, and I try to decode it with Java runner, prompting that it is not in gzip format,

So how can I decode correctly?
Thank you!~

`http-logger` config (`log-format` not set)
```
{
  "concat_method": "new_line",
  "disable": false,
  "include_req_body": true,
  "include_resp_body": true,
  "uri": "http://log-server.com/logger/apisix"
}
```

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): offical docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
maybe we can use `https://github.com/hamishforbes/lua-ffi-zlib` to decode?

**Comment by jinnyu** [comment]
OK, thank you! I will try it.

**Comment by tokers** [comment]
Maybe it can be extended to all the loggers supporting response body?

**Comment by tzssangglass** [comment]
> Maybe it can be extended to all the loggers supporting response body?

looks good
