### ISSUE TITLE
feat: As a user, I want to run `apisix init` in directory other than /usr/local/apisix

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#7390]
### Description

when running `apisix init` in other directorys, we'll get an error:

`~ # pwd
/root`

`~ # apisix init
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit: /usr/local/apisix/apisix/cli/apisix.lua:31: module 'apisix.cli.env' not found:
        no field package.preload['apisix.cli.env']
        no file '/usr/local/apisix/deps/share/lua/5.1/apisix/cli/env.lua'
        no file './apisix/cli/env.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/cli/env.lua'
        no file '/usr/local/share/lua/5.1/apisix/cli/env.lua'
        no file '/usr/local/share/lua/5.1/apisix/cli/env/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/cli/env/init.lua'
        no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix/cli/env.so'
        no file '/usr/local/apisix/deps/lib/lua/5.1/apisix/cli/env.so'
        no file './apisix/cli/env.so'
        no file '/usr/local/lib/lua/5.1/apisix/cli/env.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/cli/env.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/usr/local/apisix/deps/lib64/lua/5.1/apisix.so'
        no file '/usr/local/apisix/deps/lib/lua/5.1/apisix.so'
        no file './apisix.so'
        no file '/usr/local/lib/lua/5.1/apisix.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /usr/local/apisix/apisix/cli/apisix.lua:31: in main chunk
        [C]: at 0x5625459b7460`

**Comment by tzssangglass** [comment]
Do you mean the scenario where APISIX is installed via rpm?

**Comment by qihaiyan** [comment]
> Do you mean the scenario where APISIX is installed via rpm?

For me the scenario is building my own docker image based on apisix's official image, and change the WORKDIR to another directory.

**Comment by tokers** [comment]
I think this is a meaningful issue so I just added the "good first issue" label.

**Comment by qihaiyan** [comment]
I can fix it @tokers

**Comment by ccxhwmy** [comment]
> > Do you mean the scenario where APISIX is installed via rpm?
> 
> For me the scenario is building my own docker image based on apisix's official image, and change the WORKDIR to another directory.

Would you tell me about detailed steps, I can't understand the process, I want to learn more about it.

**Comment by qihaiyan** [comment]
> > > Do you mean the scenario where APISIX is installed via rpm?
> > 
> > 
> > For me the scenario is building my own docker image based on apisix's official image, and change the WORKDIR to another directory.
> 
> Would you tell me about detailed steps, I can't understand the process, I want to learn more about it.

1. run the official docker by `docker run -it <imagename>`
2. cd /root
3. run `apisix init`
