### ISSUE TITLE
unknown directive "apisix_mirror_on_demand" in  nginx.conf:149

### ISSUE THREAD

**Issue by Louis2014** [apache/apisix#7393]
### Description

I want to make run ,but throw "unknown directive "apisix_mirror_on_demand" in  nginx.conf:149"

### Environment

- APISIX version (run `apisix version`): release/2.14
- Operating system (run `uname -a`): Darwin Kernel Version 21.5.0 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.19.3.2
built by clang 13.1.6 (clang-1316.0.21.2.5)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/opt/homebrew/Cellar/openresty/nginx --with-debug --with-cc-opt='-DNGX_LUA_USE_ASSERT -DNGX_LUA_ABORT_AT_PANIC -O2 -DAPISIX_OPENRESTY_VER=0.0.0 -DNGX_LUA_ABORT_AT_PANIC -I/opt/homebrew/Cellar/zlib/1.2.12/include -I/opt/homebrew/Cellar/pcre/8.45/include -I/opt/homebrew/Cellar/openresty-openssl111/1.1.1n_1/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/opt/homebrew/Cellar/openresty/luajit/lib -L/opt/homebrew/Cellar/zlib/1.2.12/lib -L/opt/homebrew/Cellar/pcre/8.45/lib -L/opt/homebrew/Cellar/openresty-openssl111/1.1.1n_1/lib -Wl,-rpath,/opt/homebrew/Cellar/zlib/1.2.12/lib:/opt/homebrew/Cellar/pcre/8.45/lib:/opt/homebrew/Cellar/openresty-openssl111/1.1.1n_1/lib' --add-module=/Users/louis/Downloads/tmp/openresty-1.19.3.2/../mod_dubbo --add-module=/Users/louis/Downloads/tmp/openresty-1.19.3.2/../ngx_multi_upstream_module --add-module=/Users/louis/Downloads/tmp/openresty-1.19.3.2/../apisix-nginx-module --add-module=/Users/louis/Downloads/tmp/openresty-1.19.3.2/../lua-var-nginx-module --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): etcd Version: 3.5.4
- LuaRocks version, for installation issues (run `luarocks --version`): 3.9.0

**Comment by tokers** [comment]
@Louis2014 How did you install APISIX?

**Comment by Louis2014** [comment]
> @Louis2014 How did you install APISIX?
I installed by source code in my local environment
step1: make deps
step2: make init
The above two steps has no error, make run throw error: "unknown directive "apisix_mirror_on_demand" in nginx.conf:149".
I wander what "apisix_mirror_on_demand"  means?

**Comment by Louis2014** [comment]
@tokers

**Comment by spacewander** [comment]
From the command line you pasted, the APISIX-Base you use is not built correctly. Please use https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh to build the APISIX-Base.

Run `./build-apisix-base.sh`.

**Comment by spacewander** [comment]
Just notice you are using Mac. So you may need to modify this script to handle some dependency  (openssl and others) path problems.

Anyway, the latest release of APISIX-Base is based on OpenResty 1.21.4. We don't maintain APISIX-Base based on OpenResty 1.19.3.2, which is too old.

**Comment by Louis2014** [comment]
> 
Thanks, I'll use OpenResty 1.21.4 and build the APISIX-Base.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.

**Comment by Louis2014** [comment]
> Consider solved. Feel free to reopen it if needed.

Thanks，I've solved it by modifying the script.
