### ISSUE TITLE
bug: enable both `http_to_https` and `append_query_string` of the redirect plugin will cause the query string to be repeated twice

### ISSUE THREAD

**Issue by nic-6443** [apache/apisix#7394]
### Current Behavior

```
curl --location --request PUT 'http://apisix-admin:9180/apisix/admin/routes/redirect' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "host": "redirect",
    "uri": "/*",
    "upstream": {
        "type": "roundrobin",
        "nodes": [
            {
                "host": "httpbin",
                "port": 80,
                "weight": 1
            }
        ]
    },
    "plugins": {
        "redirect": {
            "http_to_https": true,
            "append_query_string": true
        }
    },
    "name": "redirect"
}'
```

```
❯ curl --noproxy '*' http://apisix-gateway/ip\?hello\=world -H "Host: redirect" -v
*   Trying 10.98.108.144:80...
* TCP_NODELAY set
* Connected to apisix-gateway (10.98.108.144) port 80 (#0)
> GET /ip?hello=world HTTP/1.1
> Host: redirect
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Date: Wed, 06 Jul 2022 08:21:16 GMT
< Content-Type: text/html
< Content-Length: 166
< Connection: keep-alive
< Location: https://redirect/ip?hello=world&hello=world
< Server: APISIX/2.13.1
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>openresty</center>
</body>
</html>
* Connection #0 to host apisix-gateway left intact

```

### Expected Behavior

Tell the user in the documentation not to use both `http_to_https` and `append_query_string` options, or that apisix automatically handles not repeating the query string when both options are configured at the same time

### Steps to Reproduce

/

### Environment

- APISIX version (run `apisix version`): 2.13.1

**Comment by levy001** [comment]
I will fix this problem

**Comment by vyvyan2010** [comment]
I tested and found that if I use `http_to_https`, the `location` field in the response header will take `query_string` with it, is this expected?  if so, is it just a matter of updating the documentation and telling the user about this behavior?

**Comment by vyvyan2010** [comment]
If changing the behavior of http_to_https now will affect existing users, I suggest it's best to just update the documentation

**Comment by vyvyan2010** [comment]
@tokers

**Comment by tokers** [comment]
> If changing the behavior of http_to_https now will affect existing users, I suggest it's best to just update the documentation
> 
> 

It's not changing the behavior, it's a bug and we need to fix it.

**Comment by vyvyan2010** [comment]
With  `http_to_https `,  no `query_string` in the location field, right?

**Comment by vyvyan2010** [comment]
before:  no `query_ string`

**Comment by vyvyan2010** [comment]
for `http_to_https`,
before:  with query_string in the location field
after:  without query string in the location field
for the uses who are using the command, they will be affected, right?

**Comment by vyvyan2010** [comment]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/9354193/177937140-65966787-72f5-4b81-a4db-b06505a73647.png">
And from the doc, It was designed that way on purpose ？

**Comment by vyvyan2010** [comment]
Please evaluate and if you feel there is no impact on the user，i will fix this.  @tokers

**Comment by vyvyan2010** [comment]
can we add a new directive `http_to_https_without_query_string` ?

**Comment by tokers** [comment]
@vyvyan2010 I think you may misunderstand the issue. When we enable `http_to_https` and enable `append_query_string`, the query string will be appended **twice**.

**Comment by vyvyan2010** [comment]
@tokers it's very clear, but my point is that when only enable `http_to_https`，the query string is appended already，is it expected?

**Comment by tokers** [comment]
> @tokers it's very clear, but my point is that when only enable `http_to_https`，the query string is appended already，is it expected?

I think so, this field is only used to change the scheme.

**Comment by vyvyan2010** [comment]
so can we just update the doc, tell the user that the `http_to_https` will append the query string, and do not need `append_query_string`

**Comment by tokers** [comment]
> so can we just update the doc, tell the user that the `http_to_https` will append the query string, and do not need `append_query_string`

A better way will be to make them exclusive. So that users won't configure them simultaneously.

**Comment by vyvyan2010** [comment]
ok, i will update the doc and make them exclusive

**Comment by tokers** [comment]
@vyvyan2010 I'm sorry but looks like @levy001 already works on this issue.

**Comment by vyvyan2010** [comment]
that is my another id

**Comment by kwanhur** [comment]
Check it whether need to concat new uri, make a check when enable `append_query_string` under `http_to_https`, better to keep compatibility with `uri` mode.

https://github.com/apache/apisix/blob/44561b56cf5318fe054a31f490ccfec5d372d363/apisix/plugins/redirect.lua#L216

**Comment by tokers** [comment]
> Check it whether need to concat new uri, make a check when enable `append_query_string` under `http_to_https`, better to keep compatibility with `uri` mode.
> 
> https://github.com/apache/apisix/blob/44561b56cf5318fe054a31f490ccfec5d372d363/apisix/plugins/redirect.lua#L216

Sorry, what do you mean?
