### ISSUE TITLE
help request: 内网多个mqtt服务器，怎么做到按需转发

### ISSUE THREAD

**Issue by Wauux** [apache/apisix#7395]
### Description

apisix作为网关，内网有多个mqtt服务器，如何做到按需转发
配置文件里，stream_proxy 可以配置多个端口，但是怎么才能做到端口关联？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Route based on TLS SNI is feasible.

**Comment by Wauux** [comment]
> Route based on TLS SNI is feasible.

如果不基于tls 只能配一条mqtt的路由？

**Comment by spacewander** [comment]
> stream_proxy 可以配置多个端口，但是怎么才能做到端口关联？

You can match with `server_port`
https://github.com/apache/apisix/blob/master/docs/en/latest/stream-proxy.md#more-route-match-options

**Comment by Wauux** [comment]
谢谢，配置成功了， mqtt-proxy插件里没做介绍 .. 可以把链接贴进去

**Comment by juzhiyuan** [comment]
Hi @Wauux, could you please submit a PR to update the document?  https://github.com/apache/apisix/edit/master/docs/en/latest/plugins/mqtt-proxy.md
