### ISSUE TITLE
help request: consumer accesses the specified router

### ISSUE THREAD

**Issue by zhongpengrui** [apache/apisix#7399]
### Description

请问有A和B两个consumer，R1和R2两个router，如何让A只访问R1，B只访问R2，即多个consumer访问指定的router

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):Linux bogon 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
I think this is a missing feature, currently we can only limit the accessible consumers for the routes.

**Comment by qihaiyan** [comment]
the `consumer-restriction` plugin maybe works.

**Comment by zhongpengrui** [comment]
Thanks,this is what i want.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apache/apisix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月7日(星期四) 上午9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apache/apisix] help request: (Issue #7399)





 
the consumer-restriction plugin maybe works.

**Comment by zhongpengrui** [comment]
thanks for getting back to me




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2022年7月7日(星期四) 上午9:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/apisix] help request: (Issue #7399)





 
I think this is a missing feature, currently we can only limit the accessible consumers for the routes.

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this if needed.
