### ISSUE TITLE
Proposal: support openfunction serverless framework plugin

### ISSUE THREAD

**Issue by jackkkkklee** [apache/apisix#7404]
### Description

Hi, community!
I'd like to propose a discussion about supporting openfunction serverless framework

## 1. Background：
OpenFunction is a cloud-native open source FaaS (Function as a Service) platform aiming to let you focus on your business logic without having to maintain the underlying runtime environment and infrastructure.

### 1.1 OpenFunction features include:

1. Cloud agnostic and decoupled with cloud providers' BaaS
2. Pluggable architecture that allows multiple function runtimes
3. Support both sync and async functions
4. Unique async functions support that can consume events directly from event sources
5. Support generating OCI-Compliant container images directly from function source code.
6. Flexible autoscaling between 0 and N
7. Advanced async function autoscaling based on event sources' specific metrics
8. Simplified BaaS integration for both sync and async functions by introducing Dapr
9. Advanced function ingress & traffic management powered by K8s Gateway API (In Progress)
10. Flexible and easy-to-use events management framework

### 2.1     Objectives
Supports using functions in OpenFunction as routing "upstream" via plugins to enable access to Faas functions.

### 2.2   name

The plugin is named openfunction, and the priority is -1902, ranking after openwhisk

### 2.3   Test Environment

Prepare the kubernetes environment, download OFN, the CLI of openfunction and execute the following command

   “ofn install --all”

Then run openfunction samples according to the official documentation.

### 2.4   Authentication

At present, openfunction provides two function entries, one is advanced function ingress & Traffic Management powered by k8s gateway API (in progress) which has many authentication methods vary from different implementations. The other is the default gateway kourier(https://github.com/knative-sandbox/net-kourier)  that supports external auth.

Therefore, I think basic auth can be a default authentication method for most of k8s gateways.

 
### 2.5   parameters

1. function_Uri
2. ssl_verify 
3. service_token   Description: By using basic auth , the token format is 'xx:xx'.Since openfunction does not require authentication, it is optional.
4. timeout  
5. keepalive 
6. keepalive_timeout 
7. keepalive_pool 

### 2.6   example

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "plugins": {
        "openfunction": {
            "function_uri": "http://localhost:30585/default/function-sample/world",
            "service_token": “foo:foo123”
        }
    },
    "uri": "/gohello"
}'
```

```
POST http://localhost:30585/default/function-sample/world
Authentication: Basic xxxxx
{"payload":"Hello, world!"}
```

I would like to hear everyone's comments. Thanks!

**Comment by jackkkkklee** [comment]
Sure！

Name | Type | Requirement | Default | Valid Values | Description
-- | -- | -- | -- | -- | --
function_uri | String | Required |   |   |  
ssl_verify | Boolean | Optional | True |   |  
service_token | String | Optional |   |   | Basic Auth token required format “xxx:xxx”
timeout | Integer | Optional | 60000ms | [1, 60000]ms |  
keepalive | Boolean | Optional | True |   |  
keepalive_timeout | Integer | Optional | 60000ms | [1000,...] |  
keepalive_pool | Integer | Optional | 5 | [1,...] |  


Example：
```
"openfunction": {
      "function_uri": "http://localhost:30834/default/function-sample/world",
      "keepalive": true,
      "keepalive_pool": 5,
      "keepalive_timeout": 60000,
      "service_token": "foo:foo123",
      "ssl_verify": true,
      "timeout": 60000
    }
```

**Comment by tokers** [comment]
@jackkkkklee LGTM

**Comment by tzssangglass** [comment]
> Supports using functions in OpenFunction as routing "upstream" via plugins to enable access to Faas functions.

So the function to be executed is directly in the body?

Can you give the configuration of the route and the simulated request.

**Comment by tokers** [comment]
> > Supports using functions in OpenFunction as routing "upstream" via plugins to enable access to Faas functions.
> 
> So the function to be executed is directly in the body?
> 
> Can you give the configuration of the route and the simulated request.

I don't think so, the function is specified through the `function_uri`, and request characteristics are used as the parameters of the function.

**Comment by tzssangglass** [comment]
> I don't think so, the function is specified through the `function_uri`, and request characteristics are used as the parameters of the function.

Almost got it.

**Comment by jackkkkklee** [comment]
Set route
```
{
    "plugins": {
        "openfunction": {
            "function_uri": "http://localhost:30585/default/function-sample-go",
            "service_token": “foo:foo123”
        }
    },
    "uri": "/gohello"
}'
```

simulated request:
```
POST https://<address of apisix>/gohello
{"name":"openfunction"}
```

And it will request the function_uri which is "http://localhost:30585/default/function-sample" with request characteristics.

response body

```
hello,openfunction
```

> > Supports using functions in OpenFunction as routing "upstream" via plugins to enable access to Faas functions.
> 
> So the function to be executed is directly in the body?
> 
> Can you give the configuration of the route and the simulated request.

**Comment by spacewander** [comment]
Done
