### ISSUE TITLE
use var.uri repace var.request_uri in default log format is a good idea?

### ISSUE THREAD

**Issue by mikawudi** [apache/apisix#7408]
### Description

in nginx request_uri have queryparams, uri only contain request path without queryparams
in log-util.lua file
request.uri use the var.request_uri
request.querystring use the ngx.req.get_uri_args()
are their functional overlap?

and when i consumer http log into es, and want to aggregation with path, but the loginfo from get_full_log() return dose not contain var.request_uri
why not use var.uri replace var.request_uri in request.uri field?

<img width="2186" alt="WeChat1bff430f7be44cb2bb2b0b79d7c96d5c" src="https://user-images.githubusercontent.com/8215006/177720210-c0eb66d9-816e-4b47-8b89-2432499c52b8.png">

**Comment by tokers** [comment]
@mikawudi Try to customize the log format, and use `$request_uri` there.
