### ISSUE TITLE
help request: clickhouse-logger，table only have route_id but no service_id has error log。

### ISSUE THREAD

**Issue by caozhi6655** [apache/apisix#7415]
### Description

my clickhouse table 
`CREATE TABLE apisix_inner.request_local  ON CLUSTER default 
(
    `host` String,
    `client_ip` String,
    `route_id` String,
    `@timestamp` String,
    `router_name` String,
    `uri` String,
    `request_time` Float64,
    `status` Int32,
    `uid` Int64,
    `did` String,
    `trace_id` String,
    `time_num` Float64
)
ENGINE = MergeTree
PRIMARY KEY `@timestamp``

apiasix log format
`"log_format":
    {
        "host": "$host",
        "client_ip": "$remote_addr",
        "uri": "$uri",
        "request_time": "$request_time",
        "router_name": "$route_name",
        "status": "$status",
        "did": "$http_did",
        "trace_id": "$http_trace_id",
        "@timestamp": "$time_iso8601",
        "time_num": "$msec",
        "uid": "$http_uid"
    }`

and then taking a error：。。。。body[Code: 117, e.displayText() = DB::Exception: Unknown field found while parsing JSONEachRow format: service_id: (at row 1)

then i add the service_id field，it becomes ok！
Please have a look，is it a bug？

### Environment

- APISIX version (run `apisix version`):2.13.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
A service_id is always injected because of historical legacy problem:
https://github.com/apache/apisix/blob/e51ddf19c120a289225319d4f8479c7a2f468f35/apisix/utils/log-util.lua#L69

**Comment by tzssangglass** [comment]
looks like we need to update:https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md#metadata?

**Comment by caozhi6655** [comment]
> looks like we need to update:https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md#metadata?

i think so。I did the config refer to the doc，and it only has the route_id not conclude the service_id

**Comment by caozhi6655** [comment]
> would you like to submit a PR to fix this?

OK!
