### ISSUE TITLE
help request:  bug: When I use APISIX, all routes often fail to 404

### ISSUE THREAD

**Issue by 2294648043** [apache/apisix#7416]
### Description

APISIX v2.14.1, deployed through a docker image, often does nothing and all routes 404
Execute apisix reload operation in docker container to return to normal

But doing curl http://127.0.0.1:9180/apisix/admin/plugins/reload -X PUT operation is useless
even if it has been successful

What is the difference between reload on the outside and reload on the inside?
Why does v2.13.1 not have this problem？

Is this a bug in v2.14.1？

### Environment

- APISIX 2.14.1:
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@2294648043 Did you check out the error log?

**Comment by 2294648043** [comment]
> Hi @2294648043, could you please provide the details and steps so I can try to reproduce them?
> 
> Usually, if APISIX returns 404, the requests don't match any rule you configured, but according to your description, we'd better reproduce them first.

Under version 2.14.1, there are no clear reproduction steps for the time being. Under the same request address, it was still available a few minutes ago, no operation, all interfaces are 404

apisix config:
`apisix:
  node_listen: 9080              # APISIX listening port
  port_admin: 9180            # use a separate port
  enable_ipv6: false

  allow_admin:                  # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
  #  - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.
    - Intranet address/0

  admin_key:
    - name: "admin"
      key: 4y6c4z9j9z8a6n9h9x3c7t9r1g7i9o5n
      role: admin                 # admin: manage all configuration data
                                  # viewer: only can view configuration data
    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a2
      role: viewer
  
  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "etcd address"     #
  prefix: "/apisix"               # apisix configurations prefix
  timeout: 30                     # 30 seconds

nginx_config: 
  error_log: "logs/error.log"
  error_log_level: "warn"
  worker_processes: auto
  enable_cpu_affinity: true
  worker_rlimit_nofile: 20480
  worker_shutdown_timeout: 240s
  event:
    work_connections: 1000000
  http:
    enable_access_log: true
    access_log: "logs/access.log"
    access_log_format_escape: json
    access_log_format: '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr", "x_forward_for": "$proxy_add_x_forwarded_for", "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time, "status": $status, "vhost": "$host", "request_proto": "$server_protocol", "path": "$uri", "request_query": "$args", "request_length": $request_length, "duration": $request_time,"method": "$request_method", "http_referrer": "$http_referer", "http_user_agent": "$http_user_agent", "upstream_addr": "$upstream_addr", "upstream_response_time": "$upstream_response_time", "upstream_status": "$upstream_status", "upstream_scheme": "$upstream_scheme", "upstream_host": "$upstream_host", "upstream_uri": "$upstream_uri", "http_host": "$http_host", "request": "$request", "time_local": "$time_local", "body_bytes_sent": "$body_bytes_sent"}'
    keepalive_time: 60s
    client_header_timeout: 60s
    client_body_timeout: 60s
    client_max_body_size: 0
    send_timeout: 10s
    underscores_in_headers: "on"
    real_ip_header: "X-Real-IP"
    real_ip_from:                  # http://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from
      - 127.0.0.1
      - 'unix:'
    proxy_ssl_server_name: true
    upstream:
      keepalive: 320
      keepalive_requests: 1000
      keepalive_timeout: 60s

plugin_attr:
  log-rotate:
        interval: 43200    # rotate interval (unit: second)
        max_kept: 6     # max number of log files will be kept
        enable_compression: false    # enable log file compression(gzip) or not, default false
  prometheus:
    export_addr:
      ip: "0.0.0.0"
      port: 9091

plugins:
  - api-breaker
  - authz-casbin
  - authz-casdoor
  - authz-keycloak
  - aws-lambda
  - azure-functions
  - basic-auth
  - batch-requests
  - clickhouse-logger
  - client-control
  - consumer-restriction
  - cors
  - csrf
  - datadog
  - dubbo-proxy
  - echo
  - error-log-logger
  - example-plugin
  - ext-plugin-post-req
  - ext-plugin-post-resp
  - ext-plugin-pre-req
  - fault-injection
  - file-logger
  - forward-auth
  - google-cloud-logging
  - grpc-transcode
  - grpc-web
  - gzip
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - kafka-proxy
  - key-auth
  - ldap-auth
  - limit-conn
  - limit-count
  - limit-req
  - log-rotate
  - loggly
  - mocking
  - node-status
  - opa
  - openid-connect
  - opentelemetry
  - openwhisk
  - prometheus
  - proxy-control
  - proxy-mirror
  - proxy-rewrite
  - public-api
  - real-ip
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - rocketmq-logger
  - server-info
  - serverless-post-function
  - serverless-pre-function
  - skywalking-logger
  - skywalking
  - sls-logger
  - splunk-hec-logging
  - syslog
  - tcp-logger
  - traffic-split
  - ua-restriction
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - jwt-for-1ren`

**Comment by 2294648043** [comment]
> @2294648043 Did you check out the error log?

grafana 404 logs:
{"time": "2022-07-11T01:42:56+00:00", "remote_addr": "", "x_forward_for": "124.78.168.66", "remote_user": "", "bytes_sent": 223, "request_time": 0.002, "status": 404, "vhost": "pay.1rendata.com", "request_proto": "HTTP/1.1", "path": "/grafana/api/live/ws", "request_query": "", "request_length": 583, "duration": 0.002,"method": "GET", "http_referrer": "", "http_user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36", "upstream_addr": "172.16.5.189:3000", "upstream_response_time": "0.002", "upstream_status": "404", "upstream_scheme": "http", "upstream_host": "pay.1rendata.com", "upstream_uri": "", "http_host": "pay.1rendata.com", "request": "GET /grafana/api/live/ws HTTP/1.1", "time_local": "11/Jul/2022:01:42:56 +0000", "body_bytes_sent": "19"}
{"time": "2022-07-11T01:43:09+00:00", "remote_addr": "", "x_forward_for": "124.78.168.66", "remote_user": "", "bytes_sent": 38475, "request_time": 0.014, "status": 200, "vhost": "pay.1rendata.com", "request_proto": "HTTP/2.0", "path": "/grafana/", "request_query": "", "request_length": 523, "duration": 0.014,"method": "GET", "http_referrer": "", "http_user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36", "upstream_addr": "172.16.5.189:3000", "upstream_response_time": "0.014", "upstream_status": "200", "upstream_scheme": "http", "upstream_host": "pay.1rendata.com", "upstream_uri": "", "http_host": "pay.1rendata.com", "request": "GET /grafana/ HTTP/2.0", "time_local": "11/Jul/2022:01:43:09 +0000", "body_bytes_sent": "38140"}

it will be fine after a while，did nothing

**Comment by juzhiyuan** [comment]
> Under version 2.14.1, there are no clear reproduction steps for the time being. Under the same request address, it was still available a few minutes ago, no operation, all interfaces are 404

🤔 Don't worry, just **list all steps you did**, and I would like to reproduce this case.

**Comment by tzssangglass** [comment]
Does the upstream service have `/grafana/api/live/ws` API?

404 looks like returned by upstream.

**Comment by 2294648043** [comment]
> Does the upstream service have `/grafana/api/live/ws` API?
> 
> 404 looks like returned by upstream.

It exists
All upstream have，but none of the requests get

**Comment by 2294648043** [comment]
> Does the upstream service have `/grafana/api/live/ws` API?
> 
> 404 looks like returned by upstream.

For a while it works, for a while it doesn't
did nothing

**Comment by 2294648043** [comment]
Sometimes, clearing your browser's cache is enough
or after a few minutes

**Comment by 2294648043** [comment]
![微信图片_20220711112033](https://user-images.githubusercontent.com/42125589/178182505-70a0154d-556b-4eae-8071-f7400a77490b.png)
For example this swagger-ui.html  request

**Comment by tzssangglass** [comment]
> There are apisix logs generated, but the access status is 404, it seems that the route does not exist, and a total of 20 routes are all 404.

can you show logs about this in `access.log`?

**Comment by tzssangglass** [comment]
> But doing curl http://127.0.0.1:9180/apisix/admin/plugins/reload -X PUT operation is useless
> even if it has been successful

I noticed you have the custom plugin `jwt-for-1ren` does it return 404 in some cases?

**Comment by tzssangglass** [comment]
And you need to give the complete reproduction of the steps, such as how to build the upstream, and what is the routing configuration?

**Comment by 2294648043** [comment]
> 并且需要给出完整的步骤复现，比如upstream怎么搭建，路由配置是什么？

apisix is ​​deployed via docker-compose
Configuration in docker-compose：
`apisix:
    image: apache/apisix:2.14.1-alpine
    restart: always
    container_name: apisix
    volumes:
      - /data/apisix/logs:/usr/local/apisix/logs
      - /data/apisix/config/config.yaml:/usr/local/apisix/conf/config.yaml
      - /data/apisix/plugins:/usr/local/apisix/apisix/plugins
    ports:
      - "80:9080/tcp"
      - "9091:9091/tcp"
      - "443:9443/tcp"
      - "9092:9092/tcp"
      - "9180:9180/tcp"
    networks:
      - apisix`

Services are accessed through intranet ip + port
Example：
` {
  "upstream": {
    "nodes": [
      {
        "host": "172.16.5.187",
        "port": 20006,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  }
}`

**Comment by 2294648043** [comment]
> > 有apix日志，生成状态是404，但是好像访问路由不存在，一共20条路由都是404。
> 
> 您可以在其中显示有关此的日志`access.log`吗？

Above I have the log of reply access.log，The log in access.log is also 404

**Comment by 2294648043** [comment]
> > But doing curl http://127.0.0.1:9180/apisix/admin/plugins/reload -X PUT operation is useless
> > even if it has been successful
> 
> I noticed you have the custom plugin `jwt-for-1ren` does it return 404 in some cases?
This plugin configures the consumer but doesn't use it
I delete the consumer and the problem persists

**Comment by 2294648043** [comment]
> 
curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: token' -X PUT
apisix reload
What is the difference between reload on the outside and reload on the inside?

**Comment by tzssangglass** [comment]
> Above I have the log of reply access.log，The log in access.log is also 404

can you show some logs about this?

**Comment by tzssangglass** [comment]
> Services are accessed through intranet ip + port

I mean what is the upstream service and how should I start this service in my local machine?

**Comment by tzssangglass** [comment]
> What is the difference between reload on the outside and reload on the inside?

via `curl http://127.0.0.1:9180/apisix/admin/plugins/reload`, APISIX would not stop.

**Comment by 1renwuruiming** [comment]
> > Above I have the log of reply access.log，The log in access.log is also 404
> 
> can you show some logs about this?

从日志中读取到http 状态码是404，是通过service配置的路由，仅有1个node，实际后端服务未收到转发的请求

**Comment by tokers** [comment]
Where are the route rules? How did you create them?

**Comment by 1renwuruiming** [comment]
![image](https://user-images.githubusercontent.com/36869664/178386074-4aa7a189-83c1-4a42-98a0-48b5a5a0389a.png)

**Comment by 1renwuruiming** [comment]
@tokers

**Comment by 1renwuruiming** [comment]
1. 创建service
2. 绑定路由到service
3. 访问请求时会出现请求无法被转发的情况，需要重新reload，reload之后可以维持一段时间，之后又会丢失路由

**Comment by juzhiyuan** [comment]
@1renwuruiming @2294648043 Thanks for your description, but I can't figure out what happened here 🤔 How about scheduling an online meeting? You can book a slot here[1]. We could improve the document if this error is because of usage. 😉

[1] https://calendly.com/zhiyuanju/45min

**Comment by 1renwuruiming** [comment]
@juzhiyuan Thank you for your invitation. Let's have a meeting at 2:30 p.m

**Comment by 1renwuruiming** [comment]
@juzhiyuan Thank you for your invitation. Let's have a meeting at 2:30 p.m

**Comment by 1renwuruiming** [comment]
@juzhiyuan  I'm sorry that my English is not good. Can I use Chinese for the meeting

**Comment by tzssangglass** [comment]
> @1renwuruiming @2294648043 Thanks for your description, but I can't figure out what happened here 🤔 How about scheduling an online meeting? You can book a slot here[1]. We could improve the document if this error is because of usage. 😉

I will participate

**Comment by 1renwuruiming** [comment]
![image](https://user-images.githubusercontent.com/36869664/178416472-9be187ec-e898-4b4b-b1a3-710ef9a5cf2c.png)


> > @1renwuruiming @2294648043 Thanks for your description, but I can't figure out what happened here 🤔 How about scheduling an online meeting? You can book a slot here[1]. We could improve the document if this error is because of usage. 😉
> 
> I will participate

It's my pleasure.

**Comment by 1renwuruiming** [comment]
> > @1renwuruiming @2294648043 Thanks for your description, but I can't figure out what happened here 🤔 How about scheduling an online meeting? You can book a slot here[1]. We could improve the document if this error is because of usage. 😉
> 
> I will participate

It's my pleasure.

**Comment by 1renwuruiming** [comment]
![image](https://user-images.githubusercontent.com/36869664/178416737-aee88bb6-96fa-4513-814d-1d6bb84435c4.png)
这里有一个例子，没有修改路由的情况下，同一个请求，只是参数不同就出现了404的情况，希望这个可作为一个参照来定位一下问题

**Comment by juzhiyuan** [comment]
Thanks to @bzp2010 @tzssangglass, after checking with @1renwuruiming @2294648043, we found that this error is from `Upstream Server,` as the `404` response body content is "404 page not found", but APISIX will only return a JSON with "404 Route Not Found".
