### ISSUE TITLE
help request: the value returned by the gateway and the original interface is different

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#7436]
### Description

At present, the value returned by the gateway and the original interface is different. 

Calling the original interface returns the following value：
HttpStatus:'401 Unauthorized'
response:{
    "timestamp": "2022-07-11 19:32:04",
    "status": 401,
    "error": "Unauthorized",
    "path": "/map/api/*/*"
}

Through the apisix gateway ,the response is '404 page not found',and the HttpStatus is '404 Not Found'

Why does apisix return a HttpStatus of '404 Not Found'. How can we set the gateway to pass through the  original interface information as '401 Unauthorized'?

### Environment

- APISIX version (2.13.0):

**Comment by XW512** [comment]
I have the same problem

**Comment by soulbird** [comment]
Need more information to reproduce your problem. such as routing, backend services

**Comment by 123libohan** [comment]
> Need more information to reproduce your problem. such as routing, backend services. Please give steps to reproduce.

Our interface URL is this：http://orion-a.sit.xxx.com/map/api/bbb/queryCCC
Normal return value is：
{
"timestamp": "2022-07-11 19:32:04",
"status": 401,
"error": "Unauthorized",
"path": "/map/api//"
}
The normal HttpStatus is '401 Unauthorized'

We use apisix to perform gateway forwarding,by configuring  routes,services and upstreams plugins.

The gateway does not pass through the original value,the HttpStatus change to  is '404 Not Found'
Is it because the gateway cannot parse HttpStatus   '401 Unauthorized'?

**Comment by tzssangglass** [comment]
> "path": "/map/api//"

It looks like the second `/` in `//` is escaped, can you change the path of the upstream service from `/map/api//` to `/map/api/` and try again?

**Comment by 123libohan** [comment]
> > "path": "/map/api//"
> 
> It looks like the second `/` in `//` is escaped, can you change the path of the upstream service from `/map/api//` to `/map/api/` and try again?

Thanks,but that's not the reason. I omitted the patch,actually it is "/map/api/bbb/queryCCC"

**Comment by tzssangglass** [comment]
> 404 Not Found

Can we get the path of the request as it passes through the APISIX proxy and arrives upstream?

**Comment by tzssangglass** [comment]
> response:{
> "timestamp": "2022-07-11 19:32:04",
> "status": 401,
> "error": "Unauthorized",
> "path": "/map/api/_/_"
> }

It looks like this is a Spring Boot project, and when the 401 appears, I remember it would redirect to login page in internal.

You need to provide the full reproduction steps so that I can reproduce this problem locally.

**Comment by 123libohan** [comment]
> 

This is the case. Our back-end will judge whether we have permission to access this URL in the form of a token. However, when we conduct load balancing through APISIX, we find that the result returned by APISIX is not the result returned by our back-end. It becomes 404 page not found, while our back-end returns a 401 status code.

**Comment by 123libohan** [comment]
> > response:{
> > "timestamp": "2022-07-11 19:32:04",
> > "status": 401,
> > "error": "Unauthorized",
> > "path": "/map/api/_/_"
> > }
> 
> It looks like this is a Spring Boot project, and when the 401 appears, I remember it would redirect to login page in internal.
> 
> You need to provide the full reproduction steps so that I can reproduce this problem locally.

This is the case. Our back-end will judge whether we have permission to access this URL in the form of a token. However, when we conduct load balancing through APISIX, we find that the result returned by APISIX is not the result returned by our back-end. It becomes 404 page not found, while our back-end returns a 401 status code.

**Comment by tzssangglass** [comment]
> Can we get the path of the request as it passes through the APISIX proxy and arrives upstream?

so pls answer this question, and provide the full reproduction steps.
