### ISSUE TITLE
bug: the problem of data precision loss when grpc transcode has Uint64 type in request data

### ISSUE THREAD

**Issue by moecasts** [apache/apisix#7438]
## Request
```sh
$ curl -i http://127.0.0.1:9080/v1/users/\?id\=1234567890123456123
HTTP/1.1 404 Not Found
Date: Mon, 11 Jul 2022 16:26:29 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
grpc-status: 5
grpc-message: user not found
grpc-status-details-bin: CAUSDnVzZXIgbm90IGZvdW5kGjwKKHR5cGUuZ29vZ2xlYXBpcy5jb20vZ29vZ2xlLnJwYy5FcnJvckluZm8SEAoOVVNFUl9OT1RfRk9VTkQ
Server: APISIX/2.14.1
Trailer: grpc-status
Trailer: grpc-message
```

## Get
```
SELECT * FROM "users" WHERE id = 1234567890123456000 AND "users"."deleted_at" IS NULL ORDER BY "users"."id" LIMIT 1
```

### Expected Behavior

data precision should not loss

### Steps to Reproduce

1. Run APISIX via the Docker image.
2. Create a Route using grpc-transcode with uint64 proto
3. Curl the route

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): docker image: apache/apisix:2.14.1-alpine
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant:  docker image: apache/apisix-dashboard:2.13-alpine
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by tokers** [comment]
@moecasts Could you give the reproduce steps? Also, the [proto options](https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/#options-for-pb_option) might be useful for you.

**Comment by spacewander** [comment]
LuaJIT doesn't have good int64 support.

**Comment by moecasts** [comment]
> @moecasts你能给出重现步骤吗？此外，[proto 选项](https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/#options-for-pb_option)可能对您有用。

`pb_option` 没用，重现的话，随便创建一个带 `uint64` 的请求，即可复现

**Comment by moecasts** [comment]
> LuaJIT doesn't have good int64 support.

So, is I only can use http  proxy if using `uint64`?

**Comment by spacewander** [comment]
https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/#options-for-pb_option
The `int64_as_string` option can be used to encode int64 as `#123...` and the client needs to convert it from string to real int64. Not a perfect solution but a workaround.
