### ISSUE TITLE
docs: OpenTelemetry's document is out of date

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7439]
### Current State

1. Visit this plugin's document[1][2].
2. Check `additional_attributes[0]` field: It's `required` according to the document.
3. Check this plugin's schema[3]. This field needs at least `1` item.
4. Visit this plugin's document[1][2], and check `How-to-enable` section[4], this sample doesn't contain `additional_attributes` field.

[1] `master` branch: https://apisix.apache.org/docs/apisix/next/plugins/opentelemetry
[2] `2.14` version: https://apisix.apache.org/docs/apisix/plugins/opentelemetry
[3] https://github.com/apache/apisix/blob/master/apisix/plugins/opentelemetry.lua#L166-L171
[4] https://apisix.apache.org/docs/apisix/plugins/opentelemetry/#how-to-enable

### Desired State

I'm unsure which one is correct: the `attributes` part or `How to enable`?

Also, please help check the whole document's content. Not sure if there have other misleading or wrong contents.

### Other

1. PR: https://github.com/apache/apisix/pull/6119
2. Guide: https://opentelemetry.io/blog/2022/apisix/

**Comment by juzhiyuan** [comment]
Also, I suggest adding a link to it to the documentation, like https://opentelemetry.io/blog/2022/apisix/

**Comment by hf400159** [comment]
The documentation should say that if `additional_attributes` is enabled then `additional_attributes[0]` needs to be set. We can change the `additional_attributes[0]` attribute description.
