### ISSUE TITLE
feat: As a user, I want to pass APISIX configuration parameters by setting environment variables.

### ISSUE THREAD

**Issue by guitu168** [apache/apisix#7440]
### Description

1. When using Docker to start APISIX, I found that APISIX cannot change the configuration parameters of APISIX by setting environment variables, so I have to create a configuration file to start APISIX, which is not user-friendly. please refer: https://github.com/apache/apisix-docker#solution-2
2. This is a poor experience for users who want to quickly experience the functions of APISIX.
3. When using docker-compose to start, you also need to use Git to download the files of the relevant warehouse, but not all countries can access Git very smoothly.
4. When other gateways are used, they can set parameters by passing in environment variables.

**Comment by soulbird** [comment]
I'm investigating this feature.

**Comment by hf400159** [comment]
> I'm investigating this feature.

great!  look forward to this feature.
