### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by jayliang701** [apache/apisix#7442]
### Description

Apisix is a great gateway solution. Thanks for your work. 

I found all the request headers become lowercase even though I use serverless-pre-function plugin to set a header with uppercase. 
<pre><code>core.request.set_header(ctx, 'CONTEXT_ENTITY', app);
// 'context_entity' will be passed to routes</code></pre>
What is the purpose of doing this? And could I keep my custom header with its original case? 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
According to the [RFC](https://datatracker.ietf.org/doc/html/rfc2616#section-4.2), HTTP header fields are case-insensitive. I think you may need to adjust your backend service to be more RFC-compliant.

**Comment by jayliang701** [comment]
> 

all right. that makes sense. 
Thank you.
