### ISSUE TITLE
help request: Apisix startup error

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#7452]
### Description

An error occurred while installing and starting APISIX (2.14.1):

2022/07/13 17:01:03 [error] 120770#0: init_worker_by_lua error: /app/apisix-2.14.1/apisix/init.lua:111: module 'resty.worker.events' not found:
        no field package.preload['resty.worker.events']
        no file '/app/apisix-2.14.1//deps/share/lua/5.1/resty/worker/events.lua'
        no file '/app/apisix-2.14.1//deps/share/lua/5.1/resty/worker/events/init.lua'
        no file '/app/apisix-2.14.1/resty/worker/events.lua'
        no file '/app/apisix-2.14.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events.ljbc'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.ljbc'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/site/lualib/resty/worker/events/init.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events.lua'
        no file '/usr/local/openresty/lualib/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
        no file './resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/share/lua/5.1/resty/worker/events/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/resty/worker/events/init.lua'
        no file '/app/apisix-2.14.1//deps/lib64/lua/5.1/resty/worker/events.so'
        no file '/app/apisix-2.14.1//deps/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/site/lualib/resty/worker/events.so'
        no file '/usr/local/openresty/lualib/resty/worker/events.so'
        no file './resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty/worker/events.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file '/app/apisix-2.14.1//deps/lib64/lua/5.1/resty.so'
        no file '/app/apisix-2.14.1//deps/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/site/lualib/resty.so'
        no file '/usr/local/openresty/lualib/resty.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /app/apisix-2.14.1/apisix/init.lua:111: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

Help to see what is the cause and how to solve it , thans!

### Environment

- APISIX version (2.14.1):
- OpenResty  version (1.19.9.1):

**Comment by kwanhur** [comment]
How to install APISIX-2.14.1?

If just fetch the source tarball, you need to `make deps`.

**Comment by soulbird** [comment]
Look [here](https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-do-i-fix-the-error-module-restyworkerevents-not-found-in-apache-apisix)

**Comment by tzssangglass** [comment]
> 'resty.worker.events' not found:

In my experience, you installed and started APISIX in the `/root/` directory, you need to install APISIX in a non-root directory.

same as #3207

**Comment by 123libohan** [comment]
> > 'resty.worker.events' not found:
> 
> In my experience, you installed and started APISIX in the `/root/` directory, you need to install APISIX in a non-root directory.
> 
> same as #3207

thanks , our problem has been solved by this way
