### ISSUE TITLE
clickhouse-logger can't support datetime or date field in clickhouse

### ISSUE THREAD

**Issue by caozhi6655** [apache/apisix#7454]
### Description

I use clickhouse to instore access logs of apisix，and i need to delete history data example three month before。I want use TTL feature of clickhouse to delete data auto，and the TTL field must be datetime or date，and the datetime or date format is 'yyyy-MM-dd hh:mm:ss'。In apisix there is no varible this format，so the data can't be writen。

I think the clickhouse-logger plugin log-format can't support more，could you give a way to solve this？

**Comment by tzssangglass** [comment]
the default `timestamp` used in clickhouse-logger is `time_iso8601`, which looks like `2022-01-17T10:03:10+08:00`, you can  update the metadata of clickhouse-logger to specify the format of the `timestamp`, see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md#metadata

such as changing `$time_iso8601` to `$time_local`, which looks like `2022/07/11 18:52:41`.

**Comment by caozhi6655** [comment]
> the default `timestamp` used in clickhouse-logger is `time_iso8601`, which looks like `2022-01-17T10:03:10+08:00`, you can update the metadata of clickhouse-logger to specify the format of the `timestamp`, see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md#metadata
> 
> such as changing `$time_iso8601` to `$time_local`, which looks like `2022/07/11 18:52:41`.

I tried $time_local，it didn't work

**Comment by caozhi6655** [comment]
> the default `timestamp` used in clickhouse-logger is `time_iso8601`, which looks like `2022-01-17T10:03:10+08:00`, you can update the metadata of clickhouse-logger to specify the format of the `timestamp`, see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/clickhouse-logger.md#metadata
> 
> such as changing `$time_iso8601` to `$time_local`, which looks like `2022/07/11 18:52:41`.

I tried $time_local，it didn't work because the time format is not match；- can't be /。

**Comment by tzssangglass** [comment]
> It must match strictly i think，and there is no other varible's format is like `2000-01-01 12:00:00`

Then you can modify the format of the regular extraction. AFAIK, the common time format used by Nginx is `$time_iso8601`or `$time_local`.

**Comment by caozhi6655** [comment]
> 

I didn't catch your answer，can you please  give me a more information or operation steps？

**Comment by tzssangglass** [comment]
> I didn't catch your answer，can you please give me a more information or operation steps？

We can add the following code to `clickhouse-logger` to register a custom variable:

```lua
core.ctx.register_var("fmt_localtime", function(ctx)
    return ngx.localtime()
end)
```

Then use this variable in the metadata:

```
curl http://127.0.0.1:9080/apisix/admin/plugin_metadata/clickhouse-logger -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "log_format": {
        "host": "$host",
        "@timestamp": "$fmt_localtime",
        "client_ip": "$remote_addr"
    }
}'
```

**Comment by caozhi6655** [comment]
> > I didn't catch your answer，can you please give me a more information or operation steps？
> 
> We can add the following code to `clickhouse-logger` to register a custom variable:
> 
> ```lua
> core.ctx.register_var("fmt_localtime", function(ctx)
>     return ngx.localtime()
> end)
> ```
> 
> Then use this variable in the metadata:
> 
> ```
> curl http://127.0.0.1:9080/apisix/admin/plugin_metadata/clickhouse-logger -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "log_format": {
>         "host": "$host",
>         "@timestamp": "$fmt_localtime",
>         "client_ip": "$remote_addr"
>     }
> }'
> ```

So，this needs to update the clickhouse-logger plugins's code，right？

**Comment by tzssangglass** [comment]
> So，this needs to update the clickhouse-logger plugins's code，right？

yes

**Comment by tzssangglass** [comment]
hi @zhendongcmss, what's your option?

clickhouse use the format like `2000-01-01 12:00:00` as the default time format? If so, would it be more convenient for the clickhouse plugin to push the logs in this time format?
