### ISSUE TITLE
help request: How can one route support two Ou

### ISSUE THREAD

**Issue by hushaojun-0801** [apache/apisix#7462]
### Description

ou=Users,dc=test,dc=com
ou=A,ou=Users,dc=test,dc=com
How can one route support two Ou like this

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
What is OU? Looks like this is a business feature?

**Comment by hushaojun-0801** [comment]
apisix doc is  "base_dn": "ou=users,dc=example,dc=org", 
cn is user，ou is OrganizationUnit，i just use ldap one OrganizationUnit in one route，cant two OrganizationUnit in one route

**Comment by tzssangglass** [comment]
Not supported now, `ou` defined on the router and find consumer based on it, can't define two `ou` on the router.

**Comment by hushaojun-0801** [comment]
ok tks
