### ISSUE TITLE
help request: how to publish a http/https website, like Nginx/Apache?

### ISSUE THREAD

**Issue by michaelh1355** [apache/apisix#7464]
### Description

 can APISIX setup to publish a http/https websit, like Nginx/Apache? 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Sure.

**Comment by michaelh1355** [comment]
Hi Alex,

thank you for your reply quickly.  my APISIX and NGINX is running in the same server. as NGINX is running with our website and I am searching how to replace it with APISIX.
could you please advise any documents to me about on how to deploy a website by APISIX?

thanks!




***@***.***
 
From: Alex Zhang
Date: 2022-07-14 18:39
To: apache/apisix
CC: michaelh1355; Author
Subject: Re: [apache/apisix] help request: can APISIX setup to publish a http/https websit, like Nginx/Apache? (Issue #7464)
Sure.

**Comment by tzssangglass** [comment]
we can start by: https://apisix.apache.org/docs/apisix/getting-started/

BTW: APISIX is an API Gateway and it is not recommended to use it with proxy static resources (although it can do)

**Comment by juzhiyuan** [comment]
This question has been asked many times 😄 I will add this to our documentation. For now, the quickest way is `injecting Nginx snippet to APISIX`. Please read https://apisix.apache.org/docs/apisix/customize-nginx-configuration

**related issues**
1. https://github.com/apache/apisix/issues/3390
2. https://github.com/apache/apisix/discussions/6472
3. https://github.com/apache/apisix/issues/4889
4. https://www.mail-archive.com/dev@apisix.apache.org/msg01181.html
