### ISSUE TITLE
bug: log-rotate切割丢失文件

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#7468]
### Current Behavior

测试环境中开启log-rotate插件，配置如下：
plugin_attr:
  log-rotate:
    interval: 21600    # rotate interval (unit: second)
    max_kept: 20     # max number of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false
观察几天后发现丢失了一份文件，如下：
![11111](https://user-images.githubusercontent.com/75060224/179135111-3844eb36-ddb1-4881-b6b2-d9974d5155ed.png)
猜测是否与实例重启有关，查看重启时间为15点19分，但丢失的文件应该是14点的，再查看其他机器实例，如下：
![image](https://user-images.githubusercontent.com/75060224/179135280-a9747dfc-4875-4e73-abf5-a17578c06761.png)
同样是15点19分重启过的但是没有丢失文件。
该问题是在交流群中有人反馈出现丢失文件问题后，我在自己的测试环境持续测试中发现的

### Steps to Reproduce

1.启动apisix实例并开启log-rotate插件，每6小时切割生成一份日志文件，最多保存20份
2.启动测试程序，每分钟执行一定的调用，观察access.log文件可以正确记录日志
3.持续观察每日切割的文件

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0

**Comment by tzssangglass** [comment]
It is strange, if there is a problem with the log-rotate plugin,  all instances should lose log files.

**Comment by tzssangglass** [comment]
Is there a timed task on the instance that will clean up log files larger than xx size?

**Comment by wodingyang** [comment]
这是在自己测试用服务器上测试的，所以并没有文件大小限制与清理。
补充下：
为了测试该问题用了三台一样环境的服务器并且严格控制了流量，每个实例一分钟平均接收3个请求，所以每个access文件大小基本在130320字节，而根据7月11日20点生成的文件大小判断是丢失了数据的，具体查看 2022-07-11_20-00-00__access.log文件我发现
![image](https://user-images.githubusercontent.com/75060224/179153409-a7edee30-e7c7-4432-b3c8-a0408e9f2470.png)
确实丢失了一个半小时的日志数据

**Comment by wodingyang** [comment]
再补充一下，另两台机器上的实例也在15点19分做了重启，但是并没有丢失数据。为了测试日志问题这3台机器也没有其他应用进程

**Comment by wodingyang** [comment]
我具体查看了下日志，可能是我这边停了一段时间测试程序，没有生成14的日志问题我再跟踪下

**Comment by wodingyang** [comment]
![image](https://user-images.githubusercontent.com/75060224/179155880-22b4c47d-e654-4e69-b80d-a890161001fe.png)
对比了一下3台测试机器，确实从13点45-15点20压测程序可能停了没有日志，但是另外两台机器会生成14点的日志文件并将8-14点的数据写入14点的文件，这台出问题的机器却将8-20点的数据一起写入了20点的文件中，请教下这个会跟什么有关系

**Comment by tzssangglass** [comment]
It seems to be reproducible on this machine, and you can summarize the configuration on this machine into reproducible steps so that I can reproduce it locally to me.
