### ISSUE TITLE
How to config load balance in apisix.yaml in standalone mode

### ISSUE THREAD

**Issue by wyaow** [apache/apisix#7469]
### Description

routes:
    -
        uri: /hello
        service_id: 1
services:
    -
        id: 1
        upstream_id: 2
upstreams:
    -
        id: 2
        nodes:
            "127.0.0.1:1980": 1
        type: roundrobin
#END

how could i config another upstream to same router.

### Environment

- APISIX version (run `apisix version`):
- 2.11.0
- Operating system (run `uname -a`):
- ubuntu
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- {"last_report_time":-1,"version":"2.11.0","id":"73a51270-e056-4cf0-93e6-437ad922a23b","hostname":"host-weiyao","boot_time":1657854122,"etcd_version":"unknown","up_time":590}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
You mean you want to control the target upstream for requests matched the same route? If so, try to use the traffic-split plugin.

**Comment by wyaow** [comment]
it's ok . tks.
----------------------------
upstreams:
  -
    id: 1
    nodes:
      "127.0.0.1:12345": 1
      "127.0.0.1:12346": 1
