### ISSUE TITLE
feat: APISIX jwt-auth plugin should support ES256 digital algorithm

### ISSUE THREAD

**Issue by jthann** [apache/apisix#7472]
### Description

Currently APISIX [jwt-auth](https://github.com/apache/apisix/blob/master/apisix/plugins/jwt-auth.lua) plugin only support digital signature based on HS(HMAC) and RS(RSA). But in our system we mostly use ES256 based on ECDSA and which has very shorter key length than RSA at the same security level and well supported in Golang and Java(through 3rd lib). But if using APISIX Golang plugin, which has performance effect and have some [bugs](https://github.com/apache/apisix-go-plugin-runner/issues/74). So I think APISIX should support ES256 in APISIX lua plugin.

**Comment by tzssangglass** [comment]
I think we can support it, `lua-resty-jwt` has support `ES256`,see: https://github.com/cdbattags/lua-resty-jwt/pull/34

PR is welcome!

**Comment by qihaiyan** [comment]
I can fix it. @tzssangglass

**Comment by tzssangglass** [comment]
> I can fix it. @tzssangglass

OK, assigned to you, have fun!

**Comment by chenyyyang** [comment]
I found my **apisix version :2.11.0, meanwhile resty.jwt _VERSION: 0.2.0**
DOES NOT have the above feature. In the other word, not support ES256 yet.

**How can I upgrade the dependence "resty.jwt" ?** or the only way is to upgrade apisix?
Our apisix in running in PROD environment. It costs too much to upgrade the apisix cluster.
Thus, Is there any solutions to this?
@tzssangglass  @spacewander  @qihaiyan

**Comment by tzssangglass** [comment]
> Is there any solutions to this?

You can fork and maintain your own branch, and backport this PR on your own branch.

**Comment by chenyyyang** [comment]
Hi @tzssangglass . Thanks for reply.
I have read the file changes in PR https://github.com/apache/apisix/pull/7627/files.
But I did not find any changes on apisix-xxx-0.rockspec file. 
**It seems apisix team have upgrade the version of "lua-resty-jwt = 0.2.0" to  "api7-lua-resty-jwt = 0.2.4"...Right?
What i concerned is how to upgrade  module "resty.jwt".** 
Since  my apisix version :2.11.0, meanwhile resty.jwt _VERSION: 0.2.0 NOT have the function related to ES256.
**Can I upgrade the "lua-resty-jwt = 0.2.0" to  "api7-lua-resty-jwt = 0.2.4" in my apisix-2.11.0-0.rockspec file?**

**Comment by tzssangglass** [comment]
> 我可以在我的 apisix-2.11.0-0.rockspec 文件中将“lua-resty-jwt = 0.2.0”升级为“api7-lua-resty-jwt = 0.2.4”吗？

Just changing the version number will not upgrade the JWT lib version, you need to `make deps` to install the new version. If you downloaded the image via rpm/deb/docker etc., I forget if there is a Makefile, if not, you can't `make deps` either.

There are also some very hacky ways, such as manually replacing the corresponding code files, which I don't recommend.

BTW: We do not ensure the compatibility of this hack.

**Comment by chenyyyang** [comment]
Is that you in user support channel on QQ ?
Hah...I got it .
Will do change the dependency "lua-resty-jwt = 0.2.0" to "api7-lua-resty-jwt = 0.2.4" .
