### ISSUE TITLE
How can i proxy novnc by apisix?

### ISSUE THREAD

**Issue by xwc1125** [apache/apisix#7481]
### Description

the novnc is base on [websockify](https://github.com/novnc/websockify). websockify is websocket to tcp.
so it is not the standard websocket, how can i proxy the novnc?

### Environment

- APISIX version (run `apisix version`): 2.14.1-alpine
- APISIX Dashboard version, if relevant: 2.13-alpine

**Comment by spacewander** [comment]
CC @kingluo

**Comment by kingluo** [comment]
@xwc1125 What do you want to proxy?
websockify could run in stand-alone mode. And it implements the standard websocket protocol, which is also supported by APISIX. 

That is, there are two choices to place APISIX:
novnc ---(1)---> websockify ----(2)----> vncserver

1) if you put APISIX here, it proxy the websocket http connection between novnc and websockify.
For example, you could use below admin API to define a route:
```
curl "http://127.0.0.1:9080/apisix/admin/routes/3" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "enable_websocket": true,
  "host": "localhost",
  "uri": "/ws/test",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "localhost:8765": 1
    }
  }
}'
```

Here `localhost:8765` is the address of websockify.

2) tcp proxy
In this case, the APISIX only proxy the tcp connection between websockify and vncserver.
You could use below admin API to define a stream route:

```
curl http://127.0.0.1:9080/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "remote_addr": "127.0.0.1",
    "upstream": {
        "nodes": {
            "127.0.0.1:65432": 1
        },
        "type": "roundrobin"
    }
}'
```

Here `127.0.0.1:65432` is the address of your vncserver.

**Comment by xwc1125** [comment]
Thanks very much!
The first method is particularly effective.
Thanks again!

------------
By the way, the second methos may be is wrong.
The result is `{"error_msg":"stream mode is disabled, can not add stream routes"}`

**Comment by kingluo** [comment]
@xwc1125 Yes, you should configure the stream listen address in `config.yaml`:

For example:
```
apisix:
  stream_proxy: # TCP/UDP proxy
    tcp: # TCP proxy address list
      - "127.0.0.1:50000"
```

**Comment by xwc1125** [comment]
ok!
Thank you very much!
