### ISSUE TITLE
Remove deprecated configuration in the V3

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7482]
### Description

Let's remove the deprecated configuration in the APISIX v3, including:

- [ ] health_check_retry option https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/cli/etcd.lua#L201
- [ ] lua_shared_dicts https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/cli/ops.lua#L654-L655
- [ ] `audience` in authz-keycloak https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/plugins/authz-keycloak.lua#L123-L129
- [ ] `upstream` in mqtt-proxy https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/stream/plugins/mqtt-proxy.lua#L36
- [ ] `scheme` in proxy-rewrite https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/plugins/proxy-rewrite.lua#L71
- [ ] various apisix.real_ip_xxx options https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/cli/ngx_tpl.lua#L380
- [ ] some configurations in syslog https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/plugins/syslog.lua#L62
- [ ] some configurations in error-log-logger https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/plugins/error-log-logger.lua#L69-L74
- [ ] drop support of service_protocol https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/schema_def.lua#L613
- [ ] move the `disable` to `_meta` https://github.com/apache/apisix/blob/2385768cc004ee6ac9f6d50167d2eb671669f3c0/apisix/plugin.lua#L160

---

- [ ] remove old configuration items like port_admin from the configuration file 
- [ ] remove the expression to determine whether to run the plugin or not inside some plugins (like fault-injection) since https://github.com/apache/apisix/pull/7453 is merged.

**Comment by bzp2010** [comment]
Maybe we can remove old configuration items like `port_admin` from the configuration file as well? 🤔

**Comment by spacewander** [comment]
> Maybe we can remove old configuration items like `port_admin` from the configuration file as well? 🤔

LGTM

**Comment by spacewander** [comment]
We can also remove the expression to determine whether to run the plugin or not inside some plugins (like fault-injection) since https://github.com/apache/apisix/pull/7453 is merged.

**Comment by spacewander** [comment]
@tzssangglass 
Let's submit PRs to remove them when you have free time.
Don't forget to submit PR per task so we can record them in the changelog.
