### ISSUE TITLE
help request: discovery dns failed to create a resolver: failed to set peer name: consul1:8600

### ISSUE THREAD

**Issue by zdfhub** [apache/apisix#7484]
### Description

deploy way: docker-compose
apisix_conf/config.yaml: 
`discovery:
  dns:
    servers:
      - "consul1:8600"`
 
![image](https://user-images.githubusercontent.com/20886657/179497091-20a23988-59df-42c3-8046-c87ff81726c4.png)

consul deploy by docker-compose and the same docker network with apisix。
error log：
`init.lua:517: http_access_phase(): failed to set upstream: no valid upstream node: failed to query the DNS server: dns lookup pool exceeded retries (1): failed to create a resolver: failed to set peer name: consul1:8600 could not be resolved (2: Server failure)`
![image](https://user-images.githubusercontent.com/20886657/179496830-82510eb5-a115-4c8d-b9dc-7a7f9d7803d8.png)

exec into apisix container ：
<img width="652" alt="微信截图_20220718184758" src="https://user-images.githubusercontent.com/20886657/179496726-8fe0e7e1-9c2c-47ac-8886-f0d15b4b5a06.png">

### Environment

- APISIX version (run `apisix version`): apache/apisix:2.14.1-centos
- Operating system (run `uname -a`): docker 20.10.15
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):   bitnami/etcd:3.4.9
- APISIX Dashboard version, if relevant:  apache/apisix-dashboard:2.13-centos
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
here we need to use ip as dns servers, not `consul1`.

**Comment by zdfhub** [comment]
need to use real ip as dns servers

**Comment by xuerbujia** [comment]
Hello, I'm using the IP of the consul container instead of consul1, but I have the same problem as you. Did you solve it?
