### ISSUE TITLE
feat: As a user, I want to logger suppert traceId format, so that logger and trace will be linked.

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#7485]
### Description

Example:
trace_id=xxx

**Comment by tzssangglass** [comment]
Some observability plugins support trace_id, I'm not sure which loggers you're talking about specifically.

**Comment by xuminwlt** [comment]
Apisix accessLog and kafka-logger are in my opend plugins.

**Comment by tzssangglass** [comment]
We can specify log_format to record the trace_id.

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/kafka-logger.md#metadata

here is example:
```
"log_format": { "host": "$host", "client_ip": "$remote_addr", "uri": "$uri", "request_time": "$request_time", "router_name": "$route_name", "status": "$status", "did": "$http_did", "trace_id": "$http_trace_id", "@timestamp": "$time_iso8601", "time_num": "$msec", "uid": "$http_uid" }
```

**Comment by xuminwlt** [comment]
Thanks. I will check it.
