### ISSUE TITLE
Whether consumer-restriction can be matched with a re or prefix

### ISSUE THREAD

**Issue by MorganArthur** [apache/apisix#7488]
### Description

In the use of consumer-restriction, we need to configure a large number of whitelists in the route. Currently, more than 400 whitelists need to be configured. Therefore, I would like to consult whether consumer-restriction can be whitelisted in the form of re or prefix matching.

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
What about introducing the consumer group concept?

**Comment by tokers** [comment]
So that we can only need to configure the group in the plugin.

**Comment by MorganArthur** [comment]
That's a good idea

**Comment by tzssangglass** [comment]
I have a question, what is this scene? How did you bind the consumer in APISIX to the concept of what entity in your scenario.

**Comment by MorganArthur** [comment]
Our system provides an interface service externally. Applications registered on our platform can access the interface provided by us according to the authentication information of the application. We hope to respond to the flow limiting control for each application.

**Comment by MorganArthur** [comment]
Maybe my description is not exact, but the actual usage is that we only have two kinds of interfaces for users of our system to use, and we want to set different traffic limiting rules for different users. The interface has been provided and used for a long time. Now we want to add a gateway to add some interface restrictions. My understanding is that if we want to create a route through RE to impose restrictions, we will have to change the exposed interface, but we don't want to change the interface provided

**Comment by tokers** [comment]
> I don't think using `consumer_group seems` to solve the problem of having to configure a lot of whitelists. Since you thought of using regulars, why not create routes with regulars and do restrictions based on those routes?

What are `regulars`? 🤔

**Comment by tokers** [comment]
> Maybe my description is not exact, but the actual usage is that we only have two kinds of interfaces for users of our system to use, and we want to set different traffic limiting rules for different users. The interface has been provided and used for a long time. Now we want to add a gateway to add some interface restrictions. My understanding is that if we want to create a route through RE to impose restrictions, we will have to change the exposed interface, but we don't want to change the interface provided

I'm sorry but what is 'RE`?

**Comment by tzssangglass** [comment]
> Maybe my description is not exact, but the actual usage is that we only have two kinds of interfaces for users of our system to use, and we want to set different traffic limiting rules for different users. The interface has been provided and used for a long time. Now we want to add a gateway to add some interface restrictions. My understanding is that if we want to create a route through RE to impose restrictions, we will have to change the exposed interface, but we don't want to change the interface provided

After thinking about it for a while, I realized that `consumer_group` is a viable solution. Because here we are looking for a group of consumers.

**Comment by tzssangglass** [comment]
> > Maybe my description is not exact, but the actual usage is that we only have two kinds of interfaces for users of our system to use, and we want to set different traffic limiting rules for different users. The interface has been provided and used for a long time. Now we want to add a gateway to add some interface restrictions. My understanding is that if we want to create a route through RE to impose restrictions, we will have to change the exposed interface, but we don't want to change the interface provided
> 
> I'm sorry but what is 'RE`?

sorry, ignore it, I had misunderstood it before.
