### ISSUE TITLE
help request: How to build a new docker image with new version without running errors.

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#7492]
### Description

We need k8s discovery feature, and i saw a MR `inject k8s env to discovery ` [https://github.com/apache/apisix/pull/6869](6869) is in master branch and not release in 1.14.1, so i use apisix's dev image `apache/apisix:dev` is work well. but when i build it in apisix-docker/alpine-dev with default base-image `api7/apisix-base:1.19.9.1.6`, always show some error log like this,

```
usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2022/07/18 19:44:56 [emerg] 1#1: unknown directive "lua" in /usr/local/apisix/conf/nginx.conf:31
nginx: [emerg] unknown directive "lua" in /usr/local/apisix/conf/nginx.conf:31
```

some issue like that:
https://github.com/apache/apisix-docker/issues/333

How we can build the master branch code image, is there something info like api7/apisix-base image version update?
openresty in repo apisix-docker: api7/apisix-base:1.19.9.1.6
openresty in docker-hub apache/apisix:dev: openresty -v
nginx version: openresty/1.21.4.1

### Environment

- APISIX version (run `apisix version`): master branch 1.14.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by xuminwlt** [comment]
works fine in https://github.com/apache/apisix-docker/blob/master/debian-dev/Dockerfile, but alpin-dev not well

**Comment by tzssangglass** [comment]
try with: https://hub.docker.com/r/api7/apisix-base/tags?page=1&name=dev

**Comment by tzssangglass** [comment]
> alpine-dev

alpine-dev is no longer supported, debian-dev will be supported.
