### ISSUE TITLE
help request: how to ban cache?

### ISSUE THREAD

**Issue by 1renwuruiming** [apache/apisix#7495]
### Description

如何对指定的路由禁用缓存

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
what does` ban cache` means?  The route would cache what?

**Comment by 1renwuruiming** [comment]
我部署了一个vue项目，通过apisix代理到nginx来访问，nginx层面已禁用缓存，通过apisix访问时发现页面的数据未进行更新，实际接口已调用过，并且数据正常返回了

**Comment by tzssangglass** [comment]
> nginx层面已禁用缓存

You can comb through the disabled cache operations done on Nginx and implement the corresponding configuration on APISIX.

**Comment by 1renwuruiming** [comment]
nginx使用了no-cache配置来禁用缓存，那么在apisix上如何对路由层面实现这样的操作呢

**Comment by tzssangglass** [comment]
> nginx使用了no-cache配置来禁用缓存，那么在apisix上如何对路由层面实现这样的操作呢

we can use `proxy-cache` plugin: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md
