### ISSUE TITLE
docs: `default_weight` field is missing from `config-default.yaml` and document

### ISSUE THREAD

**Issue by tokers** [apache/apisix#7501]
### Current State

The Kubernetes Service Discovery module supports a field `default_weight` as the weight for Apache APISIX upstream nodes, but it misses from both the `config-default.yaml` and the document https://apisix.apache.org/docs/apisix/next/discovery/kubernetes/.

### Desired State

We need to add explanation for this field.

**Comment by spacewander** [comment]
Done
