### ISSUE TITLE
help request: 两个lua插件问题请教

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#7503]
### Description

1、在apisix的config.yaml中开启log-rotate插件会导致路由全部返回404，配置如图
![image](https://user-images.githubusercontent.com/75060224/179923001-153a91c2-edd8-4af7-a62b-6b1105b7e061.png)
只有在config-default.yaml中开启该插件才可以正常转发，其他插件是否这样没有试过。
2、开发自定义插件，路径与配置方式如图：
![UCO4 3R21_B4~MND2AYN04K](https://user-images.githubusercontent.com/75060224/179923321-8dca6f58-7990-4108-92ea-0071fb7c95c0.png)
apisix实例虽然启动但不知道如何使用自己写的插件，通过curl 127.0.0.1:9090/v1/schema > schema.json查看该文件也并没有自定义插件的定义信息。搜索资料发现加载方式都是将自己开发的应用放在apisix/apisix/plugins目录再修改config-default.yaml文件加入自定义插件。不知道在2.13.2级以上版本后是否建议这样加载自定义插件，官方文档中指定的extra_lua_path或extra_lua_cpath路径如何加载并使用第三方插件请详细说明下，现在个人感觉是个bug或者并没有起到该配置原先想提供的功能(不会只是为了覆盖同路径同名插件吧)

### Environment

- APISIX version (run `apisix version`):2.13.2
- Operating system (run `uname -a`):3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.21.4.0
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5
- APISIX Dashboard version, if relevant:2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> 1、在apisix的config.yaml中开启log-rotate插件会导致路由全部返回404，配置如图
> ![image](https://user-images.githubusercontent.com/75060224/179923001-153a91c2-edd8-4af7-a62b-6b1105b7e061.png)
> 只有在config-default.yaml中开启该插件才可以正常转发，其他插件是否这样没有试过。

1. Your configuration in `config.yaml` is wrong.

```
#plugins:
  - log-rotate
```

You've commented out `plugins`


2. Do not modify `config-default.yaml`, any changes should be made in `config.yaml`. The configuration of the same name in `config.yaml` will overwrite `config-default.yaml`.

3. It is better to use text rather than images.

**Comment by tzssangglass** [comment]
> apisix实例虽然启动但不知道如何使用自己写的插件，通过curl 127.0.0.1:9090/v1/schema > schema.json查看该文件也并没有自定义插件的定义信息。搜索资料发现加载方式都是将自己开发的应用放在apisix/apisix/plugins目录再修改config-default.yaml文件加入自定义插件。

see: https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md#where-to-put-your-plugins

Here are the answers you need.

**Comment by wodingyang** [comment]
第一个问题是我截图时忘了删第一行的注释，并不是没有问题，为了验证我又测试了一遍，在config.yaml里面注释两行代码时，可以正确返回，如下：
![image](https://user-images.githubusercontent.com/75060224/180137169-01bb6e78-3ce4-45de-84ae-d9c8fa454207.png)

放开注释，重启，
![image](https://user-images.githubusercontent.com/75060224/180137403-2e56867d-dc0f-401d-8a4c-0c10fb8bb783.png)
![image](https://user-images.githubusercontent.com/75060224/180137429-c473acb1-e4f6-456a-9654-c02b1f3b6a31.png)

**Comment by wodingyang** [comment]
第二个问题您所发链接，阅读下来跟https://apisix.apache.org/zh/docs/apisix/plugin-develop/这篇文档应该是一样的，并不能解答我的疑惑。我的疑惑是写好自己的插件配置到extra_lua_path路径下后，没有办法证明我的插件已经加载进来，通过curl 127.0.0.1:9090/v1/schema > schema.json查看并没有加入新的插件，通过dashboard配置新的插件，也会报找不到对应的schema信息的错误。所以写好自己的插件后，怎么真正使用起来呢？

**Comment by tzssangglass** [comment]
> 放开注释，重启，

Can you give me the full configuration of config.yaml after commenting out these two lines? And did you modify config-dedault.yaml during the whole test.

And instead of posting images directly, use text and command lines to show the verification process.

**Comment by tzssangglass** [comment]
> 127.0.0.1:9090/v1/schema > schema.json查看并没有加入新的插件，通过dashboard配置新的插件，也会报找不到对应的schema信息的错误。所以写好自己的插件后，怎么真正使用起来呢？

Did you fill in the name of your plugin in the `plugins` in `config.yaml`?

like:

```yaml
apisix:
  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f1 # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin

plugins: # copied from config-default.yaml
  ...
  - your-plugin
```

**Comment by wodingyang** [comment]
config.yaml配置如下：
`
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
  #extra_lua_path: "/home/apisix/?.lua"

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://192.168.68.114:2379"
    - "http://192.168.68.115:2379"
    - "http://192.168.68.116:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. https://127.0.0.1:2379.
  prefix: /test                 # apisix configurations prefix

ext-plugin:
        cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugins/plugin-runner-0.0.1.jar']

plugins:
  - log-rotate

plugin_attr:
  log-rotate:
    interval: 7200    # rotate interval (unit: second)
    max_kept: 24     # max number of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false
  redirect:
    https_port: 9443
`
1.将config-default.yaml中被注释的log-rotate配置放开
2.启动apisix，调用一个请求，返回200
3.将config-default.yaml中log-rotate配置注释(或者说是还原)
4.在config.yaml中配置log-rotate插件
5.重启apisix，调用同一个请求，返回404

**Comment by wodingyang** [comment]
问题而已解决，感谢！
不过再次验证了我的问题一，在config.yaml中配置plugins插件信息导致我的路由全部返回404，只能在config-default.yaml中添加

**Comment by tzssangglass** [comment]
> 1.将config-default.yaml中被注释的log-rotate配置放开
> 2.启动apisix，调用一个请求，返回200
> 3.将config-default.yaml中log-rotate配置注释(或者说是还原)
> 4.在config.yaml中配置log-rotate插件
> 5.重启apisix，调用同一个请求，返回404

> 不过再次验证了我的问题一，在config.yaml中配置plugins插件信息导致我的路由全部返回404，只能在config-default.yaml中添加

First of all, this is the wrong operation. As I said before, we should not modify `config-default.yaml`.

I actually tried your steps 4 and 5 and found no exceptions.

config.yaml like:

```yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin
plugins:
  - log-rotate
```



add route:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uri":"/get",
  "upstream":{
      "type":"roundrobin",
      "nodes":{
          "httpbin.org:80":1
      }
  }
}'
```

test:

```
curl http://127.0.0.1:9080get -i
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 300
Connection: keep-alive
Date: Fri, 22 Jul 2022 02:54:30 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/2.14.1

{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1",
    "User-Agent": "curl/7.29.0",
    "X-Amzn-Trace-Id": "Root=1-62da1166-1aa07ef50dab5c5a7be980d2",
    "X-Forwarded-Host": "127.0.0.1"
  },
  "origin": "127.0.0.1, xxxx",
  "url": "http://127.0.0.1/get"
}
```
