### ISSUE TITLE
bug: does apisix cannot suport ipv6 upstream host

### ISSUE THREAD

**Issue by lijianfeng1993** [apache/apisix#7508]
### Current Behavior

when update upstreams by apisix restapi，it returnd error when i used ipv6 address as host value.such as:
![image](https://user-images.githubusercontent.com/17739680/180110458-1b32c22c-671c-48fe-9c95-1241cda994b8.png)

if i used ipv4 address， it will be success. 

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/17739680/180110521-b2c45665-cf8b-4fd9-8c1c-f8c8020ca551.png)

### Environment

docker image apisix version:  apisix:2.10.0-alpine

deployed in ipv6 kubernetes env ,and apisix-ingress-controller watched endpoint with ipv6 address， so it used ipv6 address as host value to send requst to apisix

**Comment by tzssangglass** [comment]
fixed by#6908, you need to use APISIX version >=2.14.1.

**Comment by tzssangglass** [comment]
Close it, because it is a clear and already solved problem.

Feel free to reopen this if you needed.

**Comment by lijianfeng1993** [comment]
@tzssangglass  ok, thanks
