### ISSUE TITLE
bug: Apisix-gateway always has the problem of being unable to receive traffic, so that the request cannot be responded to. It can be recovered briefly after deleting the POD of APISIX.

### ISSUE THREAD

**Issue by jackk01** [apache/apisix#7509]
### Current Behavior

The web page from the APISIX gateway cannot be accessed

### Error Logs

2022/07/20 17:17:57 [error] 58#58: *2441139 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/20 17:17:57 [warn] 58#58: *2441139 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/20 18:25:22 [error] 58#58: *2923720 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/20 18:25:22 [warn] 58#58: *2923720 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/20 19:10:49 [warn] 58#58: *3248094 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/20 19:11:19 [warn] 58#58: *3248094 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/20 20:16:28 [error] 58#58: *3724941 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/20 20:16:28 [warn] 58#58: *3724941 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/20 21:25:50 [warn] 58#58: *4221620 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/20 21:49:51 [warn] 58#58: *4394490 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/20 23:17:32 [error] 58#58: *5029613 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/20 23:17:32 [warn] 58#58: *5029613 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 00:02:31 [error] 58#58: *5353807 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 00:02:31 [warn] 58#58: *5353807 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 00:47:29 [error] 58#58: *5678106 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 00:47:29 [warn] 58#58: *5678106 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 00:47:59 [warn] 58#58: *5678106 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/21 01:32:38 [error] 58#58: *6002516 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 01:32:38 [warn] 58#58: *6002516 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 03:48:09 [warn] 58#58: *6973366 [lua] v3.lua:151: _request_uri(): http://apisix-etcd.apisix.svc.cluster.local:2379: timeout. Retrying, context: ngx.timer
2022/07/21 04:32:11 [error] 58#58: *7294083 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 04:32:11 [warn] 58#58: *7294083 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 04:32:18 [error] 58#58: *7294083 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 04:32:18 [warn] 58#58: *7294083 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer
2022/07/21 04:54:45 [error] 58#58: *7456038 [lua] http.lua:955: request_uri(): unread data in buffer, context: ngx.timer
2022/07/21 04:54:45 [warn] 58#58: *7456038 [lua] v3.lua:151: _request_uri(): invalid response code: 503. Retrying, context: ngx.timer

### Steps to Reproduce

no

### Environment

- APISIX version 2.13.2

**Comment by tzssangglass** [comment]
It looks like the problem is caused by connecting the ETCD deployed in k8s. You need to provide steps to reproduce this, as well as how ETCD and APISIX are deployed, configured, etc., otherwise, we cannot reproduce the issue.
