### ISSUE TITLE
help request: request unauthorized

### ISSUE THREAD

**Issue by 1renwuruiming** [apache/apisix#7511]
### Description

当我使用curl进行admin接口调用时返回{"code":4107,"message":"request unauthorized"}，确认过参数中的X-API-KEY和配置文件中一致

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> 当我使用curl进行admin接口调用时返回{"code":4107,"message":"request unauthorized"}，确认过参数中的X-API-KEY和配置文件中一致

It appears that this response is returned upstream and is not related to APISIX.

**Comment by 1renwuruiming** [comment]
> > 当我使用curl进行admin接口调用时返回{"code":4107,"message":"request unauthorized"}，确认过参数中的X-API-KEY和配置文件中一致
> 
> It appears that this response is returned upstream and is not related to APISIX.

![image](https://user-images.githubusercontent.com/36869664/180366359-7fc5f7da-d9ea-4237-9d62-1e3e104e2196.png)
如图所示，调用admin的接口失败，是什么原因呢

**Comment by tzssangglass** [comment]
> 如图所示，调用admin的接口失败，是什么原因呢

I don't think you are calling the admin API, but the port is port 80 and you can see which local service is listening on port 80.

APISIX doesn't have anything related to `4107`.

And you can add `-d` to curl command, see the response header.

**Comment by 1renwuruiming** [comment]
通过docker的端口映射，我将9080端口映射到了宿主机的80端口

**Comment by 1renwuruiming** [comment]
![image](https://user-images.githubusercontent.com/36869664/180375752-9961181a-f89b-4f6a-add9-aae6c42c08ef.png)

**Comment by 1renwuruiming** [comment]
![image](https://user-images.githubusercontent.com/36869664/180412929-30534017-e60e-4708-bc87-1325eb85b7af.png)

**Comment by tzssangglass** [comment]
Then please give the reproduction steps.

How to start this container and what is the route configuration.


And, as a reminder, it is better to use text rather than screenshots, as your screenshots already expose the modified X-API-KEY.
