### ISSUE TITLE
feat: As a user, I want to add simple custom auth plugin,  like: X-Token or X-Tenant-Token or custom key name

### ISSUE THREAD

**Issue by dongjiang1989** [apache/apisix#7515]
### Description

We encountered a problem: In SaaS services, multiple tenants need to be identified by an identifier to communicate with tenants. jwt-auth + X-Tenant-Token can  identify enterprise users.

so we want to add  simple custom auth plugin with name token-auth. 

when this plugin validation fails. return http status code 401. 
When the plugin is verified successfully, upsteam forward to tenants address ip.

**Comment by tzssangglass** [comment]
You can take a look at this plugin: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/forward-auth.md
