### ISSUE TITLE
bug: 在config.yaml的plugins下开启插件导致路由失效

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#7522]
### Current Behavior

在测试log-rotate插件时发现，config-default.yaml中将该插件注释了，所以在config.yaml中配置
plugins:
  - log-rotate 打开该插件
 重启apisixi后发现原先配置可用的路由全部失效。
为了验证该问题，将本地apisix、openresty全部删除，只保留etcd以及已经配置好的参数，重新安装apisix2.13.2版本，问题依旧。
该问题已经发现一段时间，在这段时间使用与观察后，个人猜测在config.yaml中配置plugins打开指定插件是有问题的，只是大多数插件默认就是打开的所以忽视了该问题

### Steps to Reproduce

1.在干净的环境中安装2.13.2版本的apisix
2.执行初始化操作，配置config.yaml，配置如下：
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
  #extra_lua_path: "/home/apisix/plugin/?.lua"

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://192.168.68.114:2379"
    - "http://192.168.68.115:2379"
    - "http://192.168.68.116:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. https://127.0.0.1:2379.
  prefix: /test                 # apisix configurations prefix

#ext-plugin:
#        cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugins/plugin-runner-0.0.1.jar']

#plugins:
# - log-rotate

plugin_attr:
  log-rotate:
    interval: 7200    # rotate interval (unit: second)
    max_kept: 24     # max number of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false
3.启动apisix，通过工具访问路由，返回200
4.停止apisix，修改config.yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin
  #extra_lua_path: "/home/apisix/plugin/?.lua"

etcd:
  host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
    - "http://192.168.68.114:2379"
    - "http://192.168.68.115:2379"
    - "http://192.168.68.116:2379"     # multiple etcd address, if your etcd cluster enables TLS, please use https scheme,
                                  # e.g. https://127.0.0.1:2379.
  prefix: /test                 # apisix configurations prefix

#ext-plugin:
#        cmd: ['java', '-jar', '-Xmx4g', '-Xms4g', '/usr/local/apisix/custom_plugins/plugin-runner-0.0.1.jar']

plugins:
  - log-rotate

plugin_attr:
  log-rotate:
    interval: 7200    # rotate interval (unit: second)
    max_kept: 24     # max number of log files will be kept
    enable_compression: false    # enable log file compression(gzip) or not, default false
5.重新启动apisix，通过工具访问路由，返回404
![2222](https://user-images.githubusercontent.com/75060224/180381126-5810938b-6971-4822-a429-2d698b68fcca.gif)

### Environment

- APISIX version (run `apisix version`):2.13.2
- Operating system (run `uname -a`):3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.21.4.0
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5

**Comment by tzssangglass** [comment]
I can't reproduce your error on 2.13.2.

My reproduction steps.

1. route

```
curl http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uri":"/index*",
  "upstream":{
      "type":"roundrobin",
      "nodes":{
          "127.0.0.1:80":1
      }
  }
}'
```

upstream is an openresty server

2. config.yaml

```yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

plugins:
  - log-rotate

plugin_attr:
  log-rotate:
    interval: 7200
    max_kept: 24
    enable_compression: false
```

3. test

```shell

$ apisix stop

$ apisix start

$ curl localhost:9080/index.html -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 1097
Connection: keep-alive
Date: Fri, 22 Jul 2022 13:42:02 GMT
Last-Modified: Tue, 21 Jun 2022 06:43:30 GMT
ETag: "62b16892-449"
Accept-Ranges: bytes
Server: APISIX/2.13.2
```

4. comment plugins

```yaml
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

#plugins:
# - log-rotate

plugin_attr:
  log-rotate:
    interval: 7200
    max_kept: 24
    enable_compression: false
```

5. test again

```shell

$ apisix stop

$ apisix start

$ curl localhost:9080/index.html -i
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 1097
Connection: keep-alive
Date: Fri, 22 Jul 2022 13:42:02 GMT
Last-Modified: Tue, 21 Jun 2022 06:43:30 GMT
ETag: "62b16892-449"
Accept-Ranges: bytes
Server: APISIX/2.13.2
```

step 2~5, I tried repeatedly several times and could not reproduce it.

**Comment by tzssangglass** [comment]
After checking your actions, I found that after modifying config.yaml, APISIX was not restarted

**Comment by tzssangglass** [comment]
And according to: https://github.com/apache/apisix/issues/7503#issuecomment-1191059708

I am not sure if this 404 is returned by APISIX. You can use the curl command to show the process of returning a 404. The response body of APISIX when it returns a 404 is as follows

```
{"error_msg":"404 Route Not Found"}
```

**Comment by wodingyang** [comment]
按以上配置确实返回200，查看我的路由配置，使用了proxy-rewrite对路由进行了改写，具体配置如下：
{
  "uri": "/javatest/*",
  "name": "测试",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/javatest/*",
        "/"
      ]
    }
  },
  "upstream_id": "415336969531294748",
  "labels": {
    "API_VERSION": "v1.0"
  },
  "status": 1
}
，关闭log-rotate插件，返回200，日志信息：
10.10.16.129 - - [27/Jul/2022:11:35:53 +0800] 192.168.68.114:9080 "GET /javatest/firstwork/ HTTP/1.1" 200 63 0.009 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71" 10.110.3.50:8888 200 0.009 "http://192.168.68.114:9080/firstwork/"
，在config.yaml打开log-rotate插件，返回404，日志信息：
10.10.16.129 - - [27/Jul/2022:11:36:54 +0800] 192.168.68.114:9080 "GET /javatest/firstwork/ HTTP/1.1" 404 727 0.011 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71" 10.110.3.51:8888 404 0.011 "http://192.168.68.114:9080"

![image](https://user-images.githubusercontent.com/75060224/181155534-27e830cd-c7ab-44d2-9951-8c63f58f2671.png)
对比faxi发现在打开log-rotate插件后，proxy-rewrite插件重写时丢失了uri

**Comment by ZhangShangyu** [comment]
i may encounter the same problem,  apisix 2.13.2
when i enable the plugin in config.yaml,  such as node-status or log-rorate, then the metrics url return 503
(even just add plugins key in the yaml, enable nothing)

the route config in apisix.yaml:
<img width="347" alt="image" src="https://user-images.githubusercontent.com/15957047/181154355-3bb4aef2-f1df-4aca-be07-3d02d7074437.png">

before add plugins key in config.yaml:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/15957047/181155124-10e6eb66-a41d-4e92-923d-3b71fcc69c28.png">

after and the plugins key in config.yaml:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/15957047/181155408-6b68a8e5-9d83-4534-8258-39e73feb6dfb.png">
<img width="538" alt="image" src="https://user-images.githubusercontent.com/15957047/181154474-68156d98-d4fe-4cc6-a84e-338c84606417.png">
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/15957047/181155538-66613f1a-8498-4d32-b13f-a5d2baf2fb45.png">

**Comment by ZhangShangyu** [comment]
oh, i found the reason.
if you specific the plugins key in the config.yaml,  it will override all value in the config-default.yaml.
so if config log-rotate only,  the other plugins will not active,  should specific other plugins explicitly in the config.yaml
@wodingyang 

is this a feature or bug? @tzssangglass

**Comment by tzssangglass** [comment]
> if you specific the plugins key in the config.yaml, it will override all value in the config-default.yaml.

it's default behavior.

**Comment by tzssangglass** [comment]
> 按以上配置确实返回200，查看我的路由配置，使用了proxy-rewrite对路由进行了改写，具体配置如下： { "uri": "/javatest/_", "name": "测试", "methods": [ "GET", "POST" ], "plugins": { "proxy-rewrite": { "regex_uri": [ "/javatest/_", "/" ] } }, "upstream_id": "415336969531294748", "labels": { "API_VERSION": "v1.0" }, "status": 1 } ，关闭log-rotate插件，返回200，日志信息： 10.10.16.129 - - [27/Jul/2022:11:35:53 +0800] 192.168.68.114:9080 "GET /javatest/firstwork/ HTTP/1.1" 200 63 0.009 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71" 10.110.3.50:8888 200 0.009 "[http://192.168.68.114:9080/firstwork](http://192.168.68.114:9080/firstwork/)" ，在config.yaml打开log-rotate插件，返回404，日志信息： 10.10.16.129 - - [27/Jul/2022:11:36:54 +0800] 192.168.68.114:9080 "GET /javatest/firstwork/ HTTP/1.1" 404 727 0.011 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71" 10.110.3.51:8888 404 0.011 "http://192.168.68.114:9080"
> 
> ![image](https://user-images.githubusercontent.com/75060224/181155534-27e830cd-c7ab-44d2-9951-8c63f58f2671.png) 对比faxi发现在打开log-rotate插件后，proxy-rewrite插件重写时丢失了uri

`uri`  in route is `/javatest/`, it wouldn't match the requests which path is `/javatest/firstwork/`.

So the routing configuration you listed is not actually associated with the request. You can set the log level to info to see which route matches exactly from the error log.

**Comment by wodingyang** [comment]
I copied all the plugin configurations to config.yaml and turned on what I needed, which did solve the problem, I don't know when the official will fix this problem. thanks for your plan @ZhangShangyu

**Comment by ZhangShangyu** [comment]
> I copied all the plugin configurations to config.yaml and turned on what I needed, which did solve the problem, I don't know when the official will fix this problem. thanks for your plan @ZhangShangyu
😄

**Comment by ZhangShangyu** [comment]
> > if you specific the plugins key in the config.yaml, it will override all value in the config-default.yaml.
> 
> it's default behavior.

it seems not the best practice.  since the other key in the config.yaml are override the only option, not all options under the key.
for example, apisix.node_listen just override the apisix.node_listen, the other option under apisix is still define in the config-default.yaml. but the plugins key does not behavior likes this,  which is very confused to users

**Comment by tzssangglass** [comment]
> for example, apisix.node_listen just override the apisix.node_listen, the other option under apisix is still define in the config-default.yaml. but the plugins key does not behavior likes this, which is very confused to users

The reason for not doing this is that users need to be given the option to disable certain plugins without modifying config-default.yaml, so that they can specify the full list of plugins in config.yaml.

This issue has been discussed for a long time.

**Comment by wodingyang** [comment]
The problem now is that only opening one plug-in in config.yaml will cause problems with other plug-ins. There are two solutions. One is to modify config-default.yaml (although it is not recommended by the official, but there is no better way), and the other is to put all the The plugins are copied to config.yaml and modified according to actual needs.

We want to know what to do in this situation, or if the official thinks this is a bug and will be fixed

**Comment by ZhangShangyu** [comment]
> > for example, apisix.node_listen just override the apisix.node_listen, the other option under apisix is still define in the config-default.yaml. but the plugins key does not behavior likes this, which is very confused to users
> 
> The reason for not doing this is that users need to be given the option to disable some plugins without modifying `config-default.yaml`, so that they can specify the full list of plugins in `config.yaml`.
> 
> This issue has been discussed before.

got it,  but the docs may can be improved to clear this point,  when i flow the doc add the plugins.log-rotate, everything goes wrong
https://apisix.apache.org/docs/apisix/plugins/log-rotate/

**Comment by tzssangglass** [comment]
> put all the The plugins are copied to config.yaml and modified according to actual needs.

This is the recommended way.

**Comment by tzssangglass** [comment]
@wodingyang @ZhangShangyu 

Let's go back to the 404 issue.

> `uri` in route is `/javatest/`, it wouldn't match the requests which path is `/javatest/firstwork/`.
> 
> So the routing configuration you listed is not actually associated with the request. You can set the log level to info to see which route matches exactly from the error log.

@wodingyang You need to pay attention to my queries here.

So far, I have not reproduced your problem, so please help me reproduce the problem by combining the reproduction steps I gave above. Otherwise we cannot move forward to solve the problem.

**Comment by wodingyang** [comment]
step1: configure routing
{
  "uri": "/javatest/*",
  "name": "测试",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/javatest/*",
        "/"
      ]
    }
  },
  "upstream_id": "415336969531294748",
  "labels": {
    "API_VERSION": "v1.0"
  },
  "status": 1
}

step2: Only one plugin is enabled in config.yaml, I enable log-rotate
![image](https://user-images.githubusercontent.com/75060224/181678561-7c1eda98-25b3-45e4-974e-6fa1d55260c9.png)

step3:send request:http://192.168.68.114:9080/javatest/firstwork/
Expected result, return 200
Actual result, returns 404

**Comment by tzssangglass** [comment]
> step3:send request:[http://192.168.68.114:9080/javatest/firstwork](http://192.168.68.114:9080/javatest/firstwork/)
> Expected result, return 200
> Actual result, returns 404

I think you should read my reply above carefully, ref: https://github.com/apache/apisix/issues/7522#issuecomment-1196427796

the route with uri `/javatest/` wouldn't match `http://192.168.68.114:9080/javatest/firstwork/`.

**Comment by wodingyang** [comment]
{
  "uri": "/javatest/*",
  "name": "测试环境三JAVA实例路由",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "DemoFilter",
          "value": ""
        }
      ],
      "disable": false
    },
    "proxy-rewrite": {
      "regex_uri": [
        "/javatest/*",
        "/"
      ]
    }
  },
  "upstream_id": "415336969531294748",
  "labels": {
    "API_VERSION": "v1.0"
  },
  "status": 1
}

**Comment by wodingyang** [comment]
First of all this is a bug in github，What I copied is
![image](https://user-images.githubusercontent.com/75060224/181689991-f00c7951-42d3-4a3d-91bc-425ac3efaa86.png)
After clicking on commont, it shows
![image](https://user-images.githubusercontent.com/75060224/181690067-188fe582-9672-4890-8c12-a459b8ee22c4.png)
So don't worry about routing configuration issues anymore.
Secondly, some people have already responded to the same problem above, and some people have proposed solutions.
We found that in config.yaml, other configurations such as apisix, nginx_conf, you only need to configure the configuration you need to override the configuration in config-default.conf.
However, if only one plugin is enabled in plugins, it will cause other plugins to fail, which is the key to the problem.

**Comment by tzssangglass** [comment]
> However, if only one plugin is enabled in plugins, it will cause other plugins to fail, which is the key to the problem.

As stated above, this is the default behavior and I have explained why this is done.

Now my question is: in your environment where enabling the `log-rotate` plugin in `config.yaml` causes all requests to return 404(No route found)?

If so, give the minimum steps to reproduce it.

Like this: https://github.com/apache/apisix/issues/7522#issuecomment-1192591289

**Comment by tzssangglass** [comment]
OK, I already know why. When you change plugins in `config.yaml` and just turn on `log-rotate`, it will cause `proxy-rewrite` to disable. You need to enable `proxy-rewrite` too.

This is expected behavior.

Feel free to reopen this if you needed.
