### ISSUE TITLE
feat: As a user, I want to authenticate clients by client_id and client_secret headers

### ISSUE THREAD

**Issue by soulbird** [apache/apisix#7530]
### Description

We would like to authenticate clients by client_id and client_secret headers. But one key-auth plugin offers just one header to use. I tried to connect 2 key-auth plugins in plugin orchestration section but that didn't work

**Comment by tokers** [comment]
Cannot capture the background, could you describe it deliberately?

**Comment by soulbird** [comment]
> Cannot capture the background, could you describe it deliberately?

In the `key-auth` plugin, if the `header` configuration is specified, currently only `key` can be obtained from a single `header`, such as `client_id` or `client_secret`. But in some cases, my `key` may exist in multiple headers, and I need to configure multiple possible headers to ensure that I can get the `key`.

**Comment by soulbird** [comment]
We can set header or query as an array, for example:
````json
"key-auth": {
     "header": ["client_id", "client_secret"]
}
````
The plugin will then try to read the credential from a header or query string parameter which with the same name configured in `header` or `query` array.
cc @tokers @spacewander

**Comment by tokers** [comment]
@soulbird API keys are bound on APISIX consumers, so will the key-auth plugin contain multiple API keys for the same consumer? Or an API request will map with a few consumers?

**Comment by soulbird** [comment]
> ```json
> client_secret
> ```

The key-auth plugin will only contain one API key for a certain consumer. It's just that we will try to get the API key from different request headers or query parameters, such as when client_id does not exist, try to get the API key from client_secret.

**Comment by soulbird** [comment]
> @soulbird API keys are bound on APISIX consumers, so will the key-auth plugin contain multiple API keys for the same consumer? Or an API request will map with a few consumers?

The key-auth plugin will only contain one API key for a certain consumer. It's just that we will try to get the API key from different request headers or query parameters, such as when client_id does not exist, try to get the API key from client_secret

**Comment by soulbird** [comment]
It's my understanding that the key-auth plugin still contains only one key, but the value of the key can be a combination of client_id and client_secret in the request header. The current value of key comes from `header` or `query` , maybe we can add a `var_combination` configuration to support the combination of multiple variables into a key.

**Comment by tokers** [comment]
> It's my understanding that the key-auth plugin still contains only one key, but the value of the key can be a combination of client_id and client_secret in the request header. The current value of key comes from `header` or `query` , maybe we can add a `var_combination` configuration to support the combination of multiple variables into a key.


That would be complicated IMHO, I'm not sure if this is reasonable. Since such a rule asks the user to construct a key as per the combination rule.

**Comment by soulbird** [comment]
> > It's my understanding that the key-auth plugin still contains only one key, but the value of the key can be a combination of client_id and client_secret in the request header. The current value of key comes from `header` or `query` , maybe we can add a `var_combination` configuration to support the combination of multiple variables into a key.
> 
> That would be complicated IMHO, I'm not sure if this is reasonable. Since such a rule asks the user to construct a key as per the combination rule.

Sounds reasonable, let's see if more people are interested in this feature.
