### ISSUE TITLE
help request:  authz-casdoor got a error authz-casdoor.lua:104: phase_func(): no session found

### ISSUE THREAD

**Issue by qianshengzj** [apache/apisix#7539]
### Description

route config

```
{
  "uri": "/casdoor/*",
  "name": "casdoor",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "authz-casdoor": {
      "callback_url": "https://api.xxx.online/casdoor/callback",
      "client_id": "xxxx",
      "client_secret": "aaaaa",
      "disable": false,
      "endpoint_addr": "https://casdoor.xxx.online"
    }
  },
  "upstream_id": "418107428857447256",
  "status": 1
}
```

when i visit this path , it can redirect to  casdoor , after login and redirect to apisix callback, apisix got error
![image](https://user-images.githubusercontent.com/21097532/181003655-a861fca5-da7e-4c09-8dab-500b3d6f6438.png)

### Environment

- APISIX version (run `apisix version`):  apache/apisix:2.13.2-centos
- Operating system (run `uname -a`):  Linux apisix-546dd76f89-25w4w 5.4.205-1.el7.elrepo.x86_64 #1 SMP Tue Jul 12 09:20:25 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners: authz-casdoor
- LuaRocks version, for installation issues (run `luarocks --version`): no cmd

**Comment by tzssangglass** [comment]
This is not a problem, for the role of callback_url, refer to: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/authz-casdoor.md

**Comment by qianshengzj** [comment]
I had add ```callback_url ``` to casdoor app config,  got a error log  
```[error] 47#47: *9518646 [lua] authz-casdoor.lua:132: phase_func(): 20: unable to get local issuer certificate, client: 10.64.89.157, server: _, request: "GET /casdoor/callback?code=3c3f18894b67439babf8&state=516600999 HTTP/1.1",```

**Comment by tzssangglass** [comment]
> I had add `callback_url ` to casdoor app config, got a error log `[error] 47#47: *9518646 [lua] authz-casdoor.lua:132: phase_func(): 20: unable to get local issuer certificate, client: 10.64.89.157, server: _, request: "GET /casdoor/callback?code=3c3f18894b67439babf8&state=516600999 HTTP/1.1",`

ref: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md

**Comment by qianshengzj** [comment]
> > I had add `callback_url ` to casdoor app config, got a error log `[error] 47#47: *9518646 [lua] authz-casdoor.lua:132: phase_func(): 20: unable to get local issuer certificate, client: 10.64.89.157, server: _, request: "GET /casdoor/callback?code=3c3f18894b67439babf8&state=516600999 HTTP/1.1",`
> 
> ref: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md

thanks @tzssangglass 

after add config
```
apisix:
  ssl:
  	ssl_trusted_certificate: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
```
It's worked out very well

**Comment by XXMY** [comment]
If the docker image was not build based centos, like Debian or Ubuntu, How can I find the trusted crt file？
