### ISSUE TITLE
About the prometheus plugin, the metric data makes the route id as the identifier of the route

### ISSUE THREAD

**Issue by believe1499** [apache/apisix#7541]
### Description

About the prometheus plugin, the metric data makes the route id as the identifier of the route, it is not convenient to find out which route it is from the route id in grafana dashboard. How can we get the route id and route mapping relation convenient?

**Comment by believe1499** [comment]
![image](https://user-images.githubusercontent.com/4081251/181147434-603deacf-3761-4be0-bd7f-479bfa8d7ab6.png)
Only the route id, it is confused about the route info.

**Comment by soulbird** [comment]
You can use `prefer_name `, look at https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md#description.

**Comment by believe1499** [comment]
Got, thanks！
