### ISSUE TITLE
Whether to consider supporting nginx's regular route matching

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#7542]
### Description

There are many regex-based routing rule configurations in my project, as follows：
location ~*  ^/co_(.*)/product_([0-9a-zA-Z-]+)_([a-z]+).html {
         if ( $uaType = "mobile") {
               proxy_pass http://xxx;
           }
          proxy_pass http://yyy;
     } 

I can't replace the original rules with libradixtree based rules.
Is there any plan to provide regular-based routing matching rules, or provide related plug-ins?

**Comment by Hazel6869** [comment]
See https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-to-use-route-uri-for-regular-matching

**Comment by Hazel6869** [comment]
see https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-do-i-use-regular-expressions-regex-for-matching-uri-in-a-route

**Comment by wodingyang** [comment]
thanks for your reply But I still have a question：how to configure？
I looked at the dashboard's routing configuration - advanced configuration features，I found that only the following situations are supported, as shown in the figure：
![image](https://user-images.githubusercontent.com/75060224/181164003-e76f199b-70b7-495f-9207-f41a38d3bb8c.png)
So how to choose the uri in vars, or can only be added manually by viewing the routing page (and is there a detailed document)
![image](https://user-images.githubusercontent.com/75060224/181164178-179fe9bf-0a83-4584-806a-756605f53a47.png)

**Comment by tokers** [comment]
@wodingyang Try the "内置参数"?
