### ISSUE TITLE
feat: As a user, I want to provide configuration or plugins to support different routes to print logs in other formats in non-access.log

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#7546]
### Description

In my project, different log files and log formats are specified in different servers。

server {
    #core
    listen 80;
    listen 443 ssl http2;
    server_name www.test.com;

    #log
    access_log logs/test.access.log test;
    error_log  logs/test.error.log info;

    #core-location
    location  / {
        proxy_pass http://test;
    }
}

Is there any plan to support this situation? The output file and output format can be specified in the routing configuration to support the migration of old projects

**Comment by tzssangglass** [comment]
In fact, you can deploy multiple sets of APISIX to achieve this, setting different log formats and output locations.

IMO, it doesn't make sense to control the log format and output location at the routing level.
