### ISSUE TITLE
bug:  apisix admin all etcd nodes are unavailable on k8s

### ISSUE THREAD

**Issue by wangchao732** [apache/apisix#7547]
### Current Behavior

helm install apisix apisix/apisix --version 0.8.4 --set gateway.type=NodePort --set ingress-controller.enabled=true --set admin.allow.ipList="{0.0.0.0/0}"   --namespace ingress-apisix

### Error Logs

 /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init

 

 WARNING: using fixed Admin API token has security risk.
 Please modify "admin_key" in conf/config.yaml .

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd

 Warning! Request etcd endpoint 'http://apisix-etcd.ingress-apisix.svc.cluster.local:2379/version' error, connection refused, retry time=1
 request etcd endpoint 'http://apisix-etcd.ingress-apisix.svc.cluster.local:2379/version' error, connection refused

 all etcd nodes are unavailable

 Warning! Request etcd endpoint 'http://apisix-etcd.ingress-apisix.svc.cluster.local:2379/version' error, connection refused, retry time=2

### Steps to Reproduce

helm install apisix apisix/apisix --version 0.8.4 --set gateway.type=NodePort --set ingress-controller.enabled=true --set admin.allow.ipList="{0.0.0.0/0}"   --namespace ingress-apisix

### Environment

helm install apisix apisix/apisix --version 0.8.4 --set gateway.type=NodePort --set ingress-controller.enabled=true --set admin.allow.ipList="{0.0.0.0/0}"   --namespace ingress-apisix

**Comment by wangchao732** [comment]
![3cbee8f1a46fe03fc9fe5ce43a93d0f](https://user-images.githubusercontent.com/19440083/181194682-54a037ef-8327-4945-ae80-b83d50d20ea5.png)

**Comment by tzssangglass** [comment]
The error message is obvious enough, you need to check the network problem between APISIX and ETCD.

**Comment by wangchao732** [comment]
> The error message is obvious enough, you need to check the network problem between APISIX and ETCD.

At first I thought so too, but it turned out unexpectedly.
![1658970022688](https://user-images.githubusercontent.com/19440083/181398161-c48a2aec-1f8f-4e5b-80b7-69241e9d4541.png)

it seems to be a DNS problem ,why?

![f4655bfb7f550d5d054e14adbf28819](https://user-images.githubusercontent.com/19440083/181398305-cb88fe2d-49ea-44de-b309-7d8d8adfbcd3.png)


![0e06585c388e79282ec0ea72ed030bd](https://user-images.githubusercontent.com/19440083/181398294-ad1d7a01-e570-4584-8c38-ed6cae7ebab8.png)

**Comment by tokers** [comment]
What's the running status of your etcd cluster?

Also, you deployed etcd in namespace ingress-apisix. But the last screenshot you gave shows the namespace is apisix. That's a blind area for us.

**Comment by wangchao732** [comment]
> 



> you deployed etcd in namespace ingress-apisix. But the last screenshot you gave shows the namespace is apisix. That's a blind area for us.
ingress-apisix previous test

**Comment by wangchao732** [comment]
> What's the running status of your etcd cluster?
> 
> Also, you deployed etcd in namespace ingress-apisix. But the last screenshot you gave shows the namespace is apisix. That's a blind area for us.

yes, etcd running status cluster.

**Comment by tzssangglass** [comment]
Maybe you need to configure the FQDN of etcd.

**Comment by wangchao732** [comment]
> Maybe you need to configure the FQDN of etcd.

This does not seem to be an fqdn problem. k8s requests access through servername.namespace.svc.cluster.domain, which should not be a problem in theory.

**Comment by tokers** [comment]
The problem is related to your Kubernetes network settings and it's irrelevant to Apache APISIX.

**Comment by tokers** [comment]
> The problem is related to your Kubernetes network settings and it's irrelevant to Apache APISIX.

You may also check out the ETCD service definition and see your CoreDNS settings.

**Comment by wangchao732** [comment]
> > The problem is related to your Kubernetes network settings and it's irrelevant to Apache APISIX.
> 
> You may also check out the ETCD service definition and see your CoreDNS settings.

Yes, thank you for your reply, the problem I encountered is very strange, CoreDNS is running normally and other services are ok, but this problem occurs in this one, it feels incredible.

**Comment by tzssangglass** [comment]
> but this problem occurs in this one, it feels incredible.

This is a problem within your environment that we cannot help with.

**Comment by wangchao732** [comment]
I am also very puzzled, and finally solved the problem by modifying the full k8s dns address of apisix etcd. As shown below:




***@***.***
 
From: tzssangglass
Date: 2022-08-02 18:47
To: apache/apisix
CC: wangchao732; Author
Subject: Re: [apache/apisix] bug: apisix admin all etcd nodes are unavailable on k8s (Issue #7547)
but this problem occurs in this one, it feels incredible.
This is a problem within your environment that we cannot help with.

**Comment by tzssangglass** [comment]
Consider it solved. Feel free to reopen this if you needed.
