### ISSUE TITLE
Can response-rewrite support different httpStatus corresponding to different body

### ISSUE THREAD

**Issue by ipanocloud** [apache/apisix#7548]
### Description

`curl http://127.0.0.1:9080/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/test/index.html",
    "plugins": {
        "response-rewrite": {
            "body": "{\"code\":\"ok\",\"message\":\"new json body\"}",
            "headers": {
                "X-Server-id": 3,
                "X-Server-status": "on",
                "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
            },
            "vars":[
                [ "status","==",200 ]
            ]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}'`
比如：这里status=404 对应一个body 而 status=503 对应另外一个body
即不同的httpStatus对应不同的body

**Comment by tokers** [comment]
Looks like you want the custom error page feature?

**Comment by ipanocloud** [comment]
> 

want to return different response packets based on different httpstatus

**Comment by tzssangglass** [comment]
Let's see if there are more similar needs

**Comment by ipanocloud** [comment]
> Let's see if there are more similar needs

This need is real in the business

**Comment by ipanocloud** [comment]
> Looks like you want the custom error page feature?

want to return different response packets based on different httpstatus

**Comment by moonming** [comment]
welcome PR to implement this @ipanocloud

**Comment by stubbornTanzhe** [comment]
maybe base different body,not just status

**Comment by kwanhur** [comment]
> > 
> 
> want to return different response packets based on different httpstatus

it's similar to Nginx [error_page](http://nginx.org/en/docs/http/ngx_http_core_module.html#error_page) directive, which returns a different response body based on the response status code.
