### ISSUE TITLE
help request: LUA Plugin or Openid-Connect-Cookie support

### ISSUE THREAD

**Issue by spamokm** [apache/apisix#7551]
### Description

Hello,

I have a JWT token stored in cookie called JWT. It is present at a request to a route, which is protected by an openid-connect plugin.
The plugin only accepts a jwt in the authorization header, so my requests are failing. (If I call them manually iwth an authorization header they are completed successfully)

SO I can request a change for the openId plugin or I create a clone of it (calling it openid-connect-cookie) and add it to my apisix instance.

But here I am struggling as well, how do I add a custom lua plugin with a helm chart. I didn't get it hot to use the config map.
Is there a "how to" available or can someone guide me?
Apisix is installed via Helm to a kubernetes cluster

Which approach is the preferred one own plugin or creating a feature request?

Thank you
Oliver

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): 18.04.1-Ubuntu
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
We may extend the oidc plugin in terms of the token position. Just like other auth plugins.

**Comment by tzssangglass** [comment]
> We may extend the oidc plugin in terms of the token position. Just like other auth plugins.

yes, in fact, `lua-resty-openid` lib support to get JWT from cookie.

**Comment by spamokm** [comment]
Great news, should I raise a feature request for the openId-Connect plugin?
