### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by TridentZZ** [apache/apisix#7556]
### Description

请问apisix是否有去除请求头中Server的配置？或者能通过什么方式把Server字段隐藏起来？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/blob/95519bc0ab3497bdb5f9fe4baac050b252a10168/conf/config-default.yaml#L48

make `enable_server_tokens ` to false

**Comment by tzssangglass** [comment]
Close this issue, because it is a very basic and clear question. Feel free to reopen this if you need.

**Comment by TridentZZ** [comment]
> ref:
> 
> https://github.com/apache/apisix/blob/95519bc0ab3497bdb5f9fe4baac050b252a10168/conf/config-default.yaml#L48
> 
> make `enable_server_tokens ` to false

加了之后只是隐藏了版本号，我希望能把整个字段隐藏掉 Server：nginx。

**Comment by tzssangglass** [comment]
not support
