### ISSUE TITLE
help request: Nginx variable in log-format, Which module will used?

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#7557]
### Description

[Nginx 内置变量](http://nginx.org/en/docs/varindex.html)

like this
[$msec](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_msec) (ngx_http_core_module)
[$msec](http://nginx.org/en/docs/http/ngx_http_log_module.html#var_msec) (ngx_http_log_module)
[$msec](http://nginx.org/en/docs/stream/ngx_stream_core_module.html#var_msec) (ngx_stream_core_module)

[$request_time](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_request_time) (ngx_http_core_module)
[$request_time](http://nginx.org/en/docs/http/ngx_http_log_module.html#var_request_time) (ngx_http_log_module)

and the desc are different

$msec in core_module
current time in seconds with the milliseconds resolution (1.3.9, 1.2.6)

$msec in log_module
time in seconds with a milliseconds resolution at the time of the log write

what does the mean in apisix when i use `$msec`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
The one in `xxx_log_module` will be used in the Nginx's `access.log`, otherwise the one in `xxx_core_module` will be used.

**Comment by xuminwlt** [comment]
Thanks.
