### ISSUE TITLE
proxy-rewrite plugin not support multi regex_uri

### ISSUE THREAD

**Issue by ipanocloud** [apache/apisix#7558]
### Description

`
"proxy-rewrite": {
      "regex_uri": [
        "(^/message/message-center-mqtt-client/(.*)|^/message/internal/message-center-mqtt-client/(.*))",
        "/$1"
      ]
    }
`
see this case

**Comment by ipanocloud** [comment]
```json
{
    "proxy-rewrite":{
        "regex_uri":[
            "^(/message/message-center-mqtt-client/|/message/internal/message-center-mqtt-client/)(.*)",
            "/$1"
        ]
    }
}
```

**Comment by Hazel6869** [comment]
see https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by tokers** [comment]
@ipanocloud May I know the use case or pain point that you're facing? Currently, it's indeed that only one `regex_uri` is supported .

**Comment by Hazel6869** [comment]
I think we need to make two improvements: first, the size of the regex_uri  array  is marked as two on the document. later, we are doing functional optimization, multiple regex_uri supported .   cc @kingluo what do you think about this.

**Comment by spacewander** [comment]
@Hazel6869 
Could you provide some reasons (use cases or the other) to make these two improvements?
And what do you want to see after the improvements?

**Comment by Hazel6869** [comment]
@spacewander  I think the first one is the optimization of the document, the status is easy to misunderstand (ab ---> ababab), the second,  multiple regex_uri supported needs to be evaluated.

**Comment by tzssangglass** [comment]
Let's start by understanding what problems are solved by supporting multiple `regex_uri`. cc @ipanocloud

**Comment by Mar1usSo** [comment]
Hello,
We are facing the same problem while migrating Gateway from Nginx to apisix.
Cause we have lots of Rewrite rule

**Comment by tokers** [comment]
@Hazel6869 Please take a look when you have time.
