### ISSUE TITLE
bug: 域名匹配优先级导致问题

### ISSUE THREAD

**Issue by rogeecn** [apache/apisix#7562]
### Current Behavior

现在有两个路由
1. 配置域名 `a.com` 路由为 `/*`， 配置 priority 为 9999
2. 不配置域名 路由为 `/v2/*`， 默认priority 为 0

问题复现
1. 当运行 `curl http://a.com/v2/x.html` 时会匹配路由2的upstream。
2. 配置 1 路由添加 `/v2/*` 正常命中路由1请求规则上游

### Expected Behavior

访问 1 中匹配的上游,如未匹配域名请求返回404

### Steps to Reproduce

现在有两个路由
1. 配置域名 `a.com` 路由为 `/*`， 配置 priority 为 9999
2. 不配置域名 路由为 `/v2/*`， 默认priority 为 0

问题复现
1. 当运行 `curl http://a.com/v2/x.html` 时会匹配路由2的upstream。
2. 配置 1 路由添加 `/v2/*` 正常命中路由1请求规则上游

### Environment

docker pull apache/apisix:2.14.1-alpine

**Comment by tokers** [comment]
@rogeecn See https://apisix.apache.org/docs/apisix/terminology/router/, use `radixtree_host_uri`.

**Comment by rogeecn** [comment]
> 

ok,my bad ,thanks

**Comment by jagerzhang** [comment]
> @rogeecn See https://apisix.apache.org/docs/apisix/terminology/router/, use `radixtree_host_uri`.

@tokers Hello tokers, please take a look. In the radixtree_host_uri mode, the mechanism does not behave as expected.
https://github.com/apache/apisix/issues/11421
