### ISSUE TITLE
help request: why limit-count with group are not allowed to change the count

### ISSUE THREAD

**Issue by suninuni** [apache/apisix#7564]
### Description

https://github.com/apache/apisix/blob/dbd78df8f11d3aeb9c189ff6d88212d918788736/apisix/plugins/limit-count.lua#L168-L179

- Why is it not allowed to modify the configuration of the same group here? 
- If I use uniq group name when update the same route,  this will have a lot of unused limit obj in luacache?
- If I want to use the same group name, how can I re-create the limit object in luacache.

### Environment

- APISIX version (run `apisix version`): 2.13.2

**Comment by suninuni** [comment]
@spacewander please take a look.

**Comment by spacewander** [comment]
> Why is it not allowed to modify the configuration of the same group here?

Different routes in the same group should have the same configuration. Otherwise, the limit-count will work incorrectly.

> If I use uniq group name when update the same route, this will have a lot of unused limit obj in luacache

The unused obj will be removed from the lrucache eventually, as the cache is LRU.

> If I want to use the same group name, how can I re-create the limit object in luacache.

By creating a group. You can consider it as dividing the group into two, one is the new one, and the other is the original one.

**Comment by suninuni** [comment]
> By creating a group. You can consider it as dividing the group into two, one is the new one, and the other is the original one.

Ok, i'll try to convince myself to accept that, thanks a lot

**Comment by jinxin231** [comment]
> 
> > If I want to use the same group name, how can I re-create the limit object in luacache.
> 
> By creating a group. You can consider it as dividing the group into two, one is the new one, and the other is the original one.

Could you please explain this in detail? The problem we are currently facing is very similar; I need to update the limit-count associated with the group. The approach taken is to first delete it and then create it again, but it has not taken effect and requires restart pods .

If the old name is **groupname1**, should the newly created group's name also be **groupname1**? Does the old group need to be deleted? Thank you very much. 
@spacewander @suninuni
