### ISSUE TITLE
help request: how to redirect https to http?

### ISSUE THREAD

**Issue by forcemeter** [apache/apisix#7566]
### Description

i want redirect https request to http. (dog)

is there any functional or  redirect plugin's like http_to_https?

我想将https请求重定向到http，现在是否支持，或者有没有插件类似于http_to_https。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@botsphp You cannot implement this need via `redirect` plugin, but you can support it by using the `serverless-function` plugin. See https://apisix.apache.org/docs/apisix/plugins/serverless/ for more details.

**Comment by kwanhur** [comment]
hey @botsphp, could you explain what's the scenario and what's your expectation? Describe in more detail by `cURL`, pls.

Maybe I can work on it when I get your intention.
