### ISSUE TITLE
help request:  whether apisix supports changing `:authority` in the grpc protocol

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#7573]
### Description

The requested link looks like this: GRPC -> apisix -> istio

At present, I need to change `:authority` in apisix layer and forward it to istio,  istio does different work according to different `:authority`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Change the pseudo `:authority`  should be same to change the host header. Try to use `proxy-rewrite` plugin.

**Comment by tokers** [comment]
Or just using the `upstream_host` field in Upstream object.

**Comment by zuiyangqingzhou** [comment]
> Change the pseudo `:authority` should be same to change the host header. Try to use `proxy-rewrite` plugin.

proxy-rewrite plugin does not work，the following is the OpenResty documentation

<img width="973" alt="image" src="https://user-images.githubusercontent.com/17425270/182117023-2779a020-8b33-4dfc-b00b-98964d5e8baa.png">

**Comment by zuiyangqingzhou** [comment]
> Or just using the `upstream_host` field in Upstream object.

This should only change the `host`, not the `:authority` ?

**Comment by tokers** [comment]
> > Or just using the `upstream_host` field in Upstream object.
> 
> This should only change the `host`, not the `:authority` ?

`: authority` should be identical with `host`, just try `host`.
