### ISSUE TITLE
feat: support Discovery Center - PolarisMesh

### ISSUE THREAD

**Issue by Maple-mxf** [apache/apisix#7574]
### Description

polarismesh是腾讯开源的注册中心，里面包含了对于grpc框架的sdk支持，使得grpc拥有了微服务的治理能力。
apisix拥有grpc-transcode协议转换能力，配合polarismesh注册中心，能够为grpc开使用者带来巨大好处

**Comment by tokers** [comment]
@Maple-mxf Could you provide more materials about polarismesh? Such as its documentation, API reference.

**Comment by Maple-mxf** [comment]
polarismesh website：https://polarismesh.cn/
polarismesh github repo：https://github.com/polarismesh/polaris

**Comment by pemako** [comment]
@tokers  the feat has been closed without any description, can this feature be supported? I really hope that this feat can be supported. Thank you very much. Looking forward to your reply.

**Comment by huzhiqiang** [comment]
![Image](https://github.com/user-attachments/assets/bb9773e8-7efb-44f5-a66b-6d2cee304525)
我看已经吹出去了
