### ISSUE TITLE
feat:ext-plugin-post-resp  plugin need get original response body information

### ISSUE THREAD

**Issue by dargoner** [apache/apisix#7575]
### Description

Add Java runner postfilter to "ext-plugin-post-resp". We need to get the original response information (response header and response body), and perform field interception, unified formatting, encryption or signature processing. At present, it seems that there is no way to get this response body information (response header can be obtained). Do you have any plan?

The implementation logic of the Lua version of "rewrite response plugin" is now too simple to consider complex response information processing. Can you add a remote call or custom logic to process the response and then return?

**Comment by spacewander** [comment]
Maybe we can add a response body type in the ExtraInfo:
https://github.com/api7/ext-plugin-proto/blob/5d14fd1baaaf85d102ca877d64e79d1af85b233c/ext-plugin.fbs#L128
like https://github.com/apache/apisix/blob/7945e6d98b4f03576af92c2255b52e367952d5f7/apisix/plugins/ext-plugin/init.lua#L297

and pass the body there:
https://github.com/apache/apisix/blob/7945e6d98b4f03576af92c2255b52e367952d5f7/apisix/plugins/ext-plugin-post-resp.lua#L146

**Comment by soulbird** [comment]
LGTM

**Comment by dargoner** [comment]
This is a good idea. I hope to add it as soon as possible

**Comment by tzssangglass** [comment]
LGTM
