### ISSUE TITLE
docs: add Prerequisite steps in the Prometheus plugin documentation 

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#7579]
### Background

The Slack user reported that after installing the `apache/apisix` project, only the prometheus functionality doesn't work as expected.

After checking, the main reason is **this documentation[2] doesn't mention we should also install another project - the `Prometheus.`**

Another improvement is Prometheus's default port is 9090, and APISIX's Control API[3] also uses the `9090` port. This will lead to unexpected cases happened.

[1] https://the-asf.slack.com/archives/CUC5MN17A/p1659251120138759
[2] https://apisix.apache.org/docs/apisix/plugins/prometheus/
[3] https://apisix.apache.org/docs/apisix/control-api/

### Desired State

In the Prometheus plugin's documentation:

1. Add the Prerequisite/Note section to tell users: that APISIX and Prometheus are two different components, and we must install both when using this plugin. P.S We could use Docker with an All-in-one solution[1] instead for a quick start.
2. Highlight: Prometheus's default port (9090) is the same as APISIX's Control API, be careful when using Control API and Prometheus.

In the Control API documentation:

1. How about adding a NOTE section that mentions there will have conflict when using Prometheus together?

cc @bzp2010 to have a confirmation 🙏

[1] https://github.com/apache/apisix-docker
[2] https://apisix.apache.org/docs/apisix/control-api/

**Comment by spacewander** [comment]
> How about adding a NOTE section that mentions there will have conflict when using Prometheus together

I am confused in what case do people need to deploy Prometheus with the gateway in the same machine? It is pretty strange in production env.

**Comment by spacewander** [comment]
In my opinion, when we doc the port used by the Control API, we already show that if the other services also use the same port in the same network namespace, they can't work together. So there is no need to doc the conflict with the Prometheus's default port, which will make things more complex.

**Comment by tzssangglass** [comment]
IMO, I don't think there is a need to resolve the 9090 port conflict issue. Users need to choose the right port for their environment and configure it in config.yaml. Even if the control API is made to avoid 9090, it may conflict with the default port of other services. This is a difference in the user's environment.
