### ISSUE TITLE
protobin 解析失败

### ISSUE THREAD

**Issue by CreatedFromZhang** [apache/apisix#7580]
### Description

从后台proto列表使用protobin格式添加
![image](https://user-images.githubusercontent.com/42968363/182070699-4cea0814-ed0e-49b7-b827-62943523c32e.png)
启动服务,请求网关后返回501 ，查看日志发现
![image](https://user-images.githubusercontent.com/42968363/182070743-9366b180-6ce8-4a9a-b98e-e596bf67afbc.png)
判断解析protobin失败，不知道是什么原因导致的

### Environment

- APISIX version (`2.9`):
- Operating system (`Linux de839d9be7b2 5.4.154-1.el7.elrepo.x86_64 #1 SMP Fri Oct 15 13:02:21 EDT 2021 x86_64 Linux`):
- OpenResty / Nginx version (`nginx version: openresty/1.19.3.1`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:2.13-centos
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): /usr/local/openresty/luajit/bin/luarocks 3.7.0

**Comment by spacewander** [comment]
2.9 doesn't support protobin, please upgrade to 2.13.0 or higher.
