### ISSUE TITLE
bug: Incompatible redirect plugin parameters after upgrade to 2.15

### ISSUE THREAD

**Issue by crazyMonkey1995** [apache/apisix#7583]
### Current Behavior

redirect plugin parameters incompatible

### Error Logs

failed to check the configuration of plugin redirect err: value should match only one schema, but matches none

### Steps to Reproduce

1、create route in version 2.14
2、upgrade version to 2.15
3、route init error

Here is the bug:
The old version will have an append_ query_ string parameter, which is false by default. After upgrading, http_ to_ https and append_ query_ string parameters cannot coexist, even if The value of append_ query_string is false, which means that the old version created the plugin and append_ query_ string is false, the parameter verification also fails. This compatibility is not very reasonable.

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
See #7394 and #7433

**Comment by crazyMonkey1995** [comment]
> See #7394 and #7433


Actually, I know this bug has been fixed, but what I mean is that the compatibility may not be very good, imagine: I used this plugin in an old version, http_to_https is set to true, append_query_string is set to false, this should be no problem , but after the upgrade, I need to reconfigure the parameters of the plugin (remove the append_query_string parameter), and the logic of parameter verification is changed to judge that these two parameters cannot be true at the same time instead of coexisting, isn't it better?

**Comment by crazyMonkey1995** [comment]
By th way, the append_query_string parameter of the old version has a default value of false, which means that whether I submit this parameter or not, this parameter will be generated in etcd, and an error will occur after upgrading to the new version!

**Comment by tzssangglass** [comment]
@crazyMonkey1995, thank you for your feedback.

in 2.14.1, if we config `redirect` plugin like:

```
"plugins": {
    "redirect": {
        "http_to_https": true
    }
}
```

it will be stored in etcd as:

```
"plugins":{
    "redirect":{
        "http_to_https":true,
        "encode_uri":false,
        "append_query_string":false,
        "ret_code":302
    }
},
```

if we upgrade APISIX to 2.15.0, would get error like:

```
config_etcd.lua:243: load_full_data(): failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin redirect err: value should match only one schema, but matches none ,val: {\"host\":\"foo.com\",\"plugins\":{\"redirect\":{\"http_to_https\":true,\"encode_uri\":false,\"append_query_string\":false,\"ret_code\":302}},\"status\":1,\"uri\":\"\/hello\",\"id\":\"1\",\"priority\":0,\"create_time\":1659345713,\"update_time\":1659345713}, context: init_worker_by_lua*" (req 0)
# 2022/08/01 17:22:29 [info] 6059\#6059: *2 [lua] plugin.lua:746: check_single_plugin_schema(): check plugin schema, name: redirect, configurations: {"append_query_string":false,"ret_code":302,"http_to_https":true,"encode_uri":false}, context: init_worker_by_lua*
```

**Comment by spacewander** [comment]
I think the fix is incorrect.
```
"redirect": {
            "http_to_https": true,
            "append_query_string": true
        }
```
should be rejected.

But
```
 "redirect":{
        "http_to_https":true,
        "append_query_string":false
    }
```
should be OK.

**Comment by Yullin** [comment]
When I upgrade apisix from 2.13.1 to 2.15.3, I got the same issue:
```
2023/03/17 10:55:23 [error] 52#52: *1 [lua] config_etcd.lua:243: load_full_data(): failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin redirect err: value should match only one schema, but matches none ,val: {"uri":"\/*","plugins_check":"other","host":"foo.com","labels":{"env":"xxxxx"},"status":1,"upstream":{"name":"nodes","scheme":"https","pass_host":"pass","nodes":{"192.168.1.180:443":1,"192.168.1.237:443":1},"type":"roundrobin","hash_on":"vars"},"priority":1,"enable_websocket":false,"create_time":1677062316,"id":"00000000000001029445","update_time":1677119638,"remote_addrs":["192.168.0.0\/16"],"plugins":{"redirect":{"append_query_string":false,"ret_code":302,"http_to_https":true,"encode_uri":false}},"methods":["GET","POST","PUT","DELETE","OPTIONS"]}, context: init_worker_by_lua*
```
