### ISSUE TITLE
help request: health check with UDP proxy

### ISSUE THREAD

**Issue by liuning89757** [apache/apisix#7591]
### Description

Apisix support UDP proxy but seems cannot support UDP health check, according to https://apisix.apache.org/docs/apisix/health-check/  .  I test it with  DNS service, when stop DNS service on one backend apisix can not recognize the change. The [lua-resty-healthcheck] document also has nothing about UDP. 
Suggestions are greatly appreciated.

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`): centos7.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19

**Comment by Hazel6869** [comment]
@liuning89757  hello,  health check currently only supports the http protocol

**Comment by liuning89757** [comment]
So looks like use Apisix as UDP proxy for production is not a good idea.
