### ISSUE TITLE
help request: The number of connections keep increase with out any requests

### ISSUE THREAD

**Issue by jerrytaotz** [apache/apisix#7597]
### Description

Hi All,
We use helm chart to deploy APISIX in K8S pods, and find this phenomenon:
1. The number of connections keeps increase, most of them are waiting connections, but during this time, we do not create  any connections.
2.  It looks like the APISIX process restart frequently.

<img width="1420" alt="WeChatcaa11a8f00713cffb7616a0100134185" src="https://user-images.githubusercontent.com/15017733/182372143-fad937d7-50eb-45ea-93b2-28e715b717ac.png">
<img width="1417" alt="WeChatfd38e6e5d472137a7217261e91ce3e5d" src="https://user-images.githubusercontent.com/15017733/182372433-6f90392d-a057-4b1d-9f52-246845319596.png">

I have no idea on it, does any one have met this problem before?
 

### Environment

- APISIX version (run `apisix version`): 1.14.1
- Operating system (run `uname -a`): Linux

**Comment by tzssangglass** [comment]
It's strange, is an external health check probe probing this service?

**Comment by tzssangglass** [comment]
> 1. we do not create  any connections.

The request may not be coming from you, but from places you are ignoring.

**Comment by tokers** [comment]
Let's check out how the value is calculated. These connection numbers gotten from apisix are counters which increases since apisix starts.

**Comment by soulbird** [comment]
Prometheus will periodically call the `/apisix/prometheus/metrics` interface to obtain monitoring data. This also leads to an increase in the number of connections.

**Comment by jerrytaotz** [comment]
> > 1. we do not create  any connections.
> 
> The request may not be coming from you, but from places you are ignoring.

I'm pretty sure it doesn't have any consumers due to it is new environment and haven't deliver to customers yet, APISIX dashboard should be the only service who might make request to apisix

**Comment by jerrytaotz** [comment]
> Let's check out how the value is calculated. These connection numbers gotten from apisix are counters which increases since apisix starts.

The metrics expression is like:
`sum(apisix_nginx_http_current_connections{state=~"active|reading|writing|waiting", instance=~"$instance", kubernetes_namespace=~"$namespace"}) by (state)`
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/15017733/182512024-11e2bf9b-a54a-45e3-846a-b5cae020be3d.png">

**Comment by tzssangglass** [comment]
> APISIX dashboard should be the only service who might make request to apisix

APISIX dashboard will not access the APISIX Admin API, right? cc @bzp2010 

You can look at the `access.log`, the request information will be logged here.

**Comment by xuminwlt** [comment]
It is indeed a strange curve, it may be that the nginx worker has insufficient memory to cause the process to restart, etcd-rechable has restart behavior, and the connection is not released.

**Comment by tzssangglass** [comment]
> etcd-rechable has restart behavior, and the connection is not released.

yes, this problem exists in the previous version, you need to upgrade to the latest version. ref: https://github.com/api7/lua-resty-etcd/pull/165

**Comment by xuminwlt** [comment]
Thanks, we will check it.
