### ISSUE TITLE
help request: error.log report ping error per minute

### ISSUE THREAD

**Issue by EthanKk** [apache/apisix#7600]
### Description

error.log report this error per minute：
[error] 47#47: *114167693 [lua] client.lua:155: ping(): Agent ping fails, closed, context: ngx.timer

where is it come from？

### Environment

- APISIX version (run `apisix version`):2.14.1
-run in docker：apache/apisix:2.14.1-centos

**Comment by soulbird** [comment]
It looks like it comes from the skywalking-logger plugin. From the log, there is a problem with the network between your skywalking service and APISIX

**Comment by EthanKk** [comment]
ok,

> It looks like it comes from the skywalking-logger or skywalking plugin. From the log, there is a problem with the network between your skywalking service and APISIX

**Comment by EthanKk** [comment]
> It looks like it comes from the skywalking-logger or skywalking plugin. From the log, there is a problem with the network between your skywalking service and APISIX

I don't use skywalking-logger and the network between skywalking and apisix is ok.Is there anything else I can check?
