### ISSUE TITLE
help request: Does get request support search queries?

### ISSUE THREAD

**Issue by Gooooodman** [apache/apisix#7601]
### Description

1、支持搜索 uri , host 等等
看文档只有ttl
![image](https://user-images.githubusercontent.com/13062160/182501849-7ccb0b7e-2cb6-45f0-b593-e6ed1899208d.png)
2、支持 page ,size 查询

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
This is part of the V3 functionality, which is implemented in this PR: #7585. Let's wait for it to appear in the next release.

**Comment by Gooooodman** [comment]
@tzssangglass  thank you . 期待V3.  预计什么时候上线呢？

**Comment by tzssangglass** [comment]
> @tzssangglass thank you . 期待V3. 预计什么时候上线呢？

According to the release rules, it will be in this month or next month.
