### ISSUE TITLE
help request: proxy-rewrite plugin bind to consumer not run after auth

### ISSUE THREAD

**Issue by nemoii** [apache/apisix#7611]
### Description

here is the use case:
I have multiple consumers, each of them has a custom header (e.g. x-aa-app-consumer) represent for username. So I bind a proxy-rewrite to each consumer to rewrite custom headers into a unified header (e.g. x-myapp-uid). This is convenient for upstream to handle requests from different consumer.
However it doesn't work like I expected, headers are not rewrite, they are passed to upstream with no change.
As the document(https://apisix.apache.org/docs/apisix/terminology/consumer/) says, "The configurations like Plugins and Upstream bound to the Consumer are then executed.", was it misconfigured or kind of bug occurs?
Thanks for help!

### Environment

- APISIX version (run `apisix version`): 2.10.0
- Operating system (run `uname -a`): in k8s(image apisix:2.10.0-alpine)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): in k8s(image apisix:2.10.0-alpine)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): in k8s(image etcd:3.5.4-debian-11-r14)
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): in k8s(image apisix:2.10.0-alpine)

**Comment by spacewander** [comment]
Solved in https://github.com/apache/apisix/pull/6502

**Comment by spacewander** [comment]
Feel free to reopen it if the problem can be reproduced with 2.15.0.

**Comment by nemoii** [comment]
> Feel free to reopen it if the problem can be reproduced with 2.15.0.

2.15.0 has unsolved bug #7276 , cant upgrade to it, could you create a new release to include the commits that solve it?

**Comment by spacewander** [comment]
We will release 2.13.3 which contains the commits.

**Comment by extimo** [comment]
> We will release 2.13.3 which contains the commits.

OK，looking forward to see that

**Comment by extimo** [comment]
> 

When will 2.13.3 be released ? We need this fix desperately, thanks for reply!
@spacewander
