### ISSUE TITLE
request help: APISIX gateway GRPC transcode returning static token

### ISSUE THREAD

**Issue by tzssangglass** [apache/apisix#7628]
### Discussed in https://github.com/apache/apisix/discussions/7616

<div type='discussions-op-text'>

<sup>Originally posted by **ochuko3d** August  5, 2022</sup>
Hi guys,

I would really love help resolving an issue around  grpc transcode returning static tokens. My proto file has a an import embedded. import proto and was able to upload it to apisix admin,  and doing a trial run i keep getting an empty static token. 

APISIX log report 200 to the server but its not responding properly
</div>

**Comment by tzssangglass** [comment]
can you provide the .pb file? @ochuko3d

**Comment by ochuko3d** [comment]
Find below


�
google/protobuf/any.protogoogle.protobuf"6
Any
type_url (	RtypeUrl
value (RvalueBv
com.google.protobufBAnyProtoPZ,google.golang.org/protobuf/types/known/anypb�GPB�Google.Protobuf.WellKnownTypesbproto3
�
google/protobuf/empty.protogoogle.protobuf"
EmptyB}
com.google.protobufB
EmptyProtoPZ.google.golang.org/protobuf/types/known/emptypb��GPB�Google.Protobuf.WellKnownTypesbproto3
�
proto/account.protoaccountgoogle/protobuf/any.protogoogle/protobuf/empty.proto"L
GenericOperationResponse
status (Rstatus
message (	Rmessage"
CreateUserRequest
	firstName (	R	firstName
lastName (	RlastName
email (	Remail
password (	Rpassword"�
UserProfile 
nationality (	Rnationality.
countryOfResidence (	RcountryOfResidence
city (	Rcity
address (	Raddress
zipCode (RzipCode 
phoneNumber (	RphoneNumber 
linkedinUrl (	RlinkedinUrl

profession (	R
profession
company	 (	Rcompany
industry
 (	Rindustry"
annualIncome (	RannualIncomeT
modeOfInvestment (2(.account.USER_PROFILE_MODE_OF_INVESTMENTRmodeOfInvestment@
hasPreviousAfricaInvestment
 (RhasPreviousAfricaInvestment6
hasSyndicateExperience (RhasSyndicateExperienceD
attendedPastFutureAfricaEvent (RattendedPastFutureAfricaEvent9
futureAfricaEventName (	HRfutureAfricaEventName�B
_futureAfricaEventName"}
CreateUserResponse
status (Rstatus,
errors (2.google.protobuf.AnyRerrors!
user (2
.account.UserRuser"�
User
id (	Rid
	firstName (	R	firstName
lastName (	RlastName
email (	Remail
	createdAt (	R	createdAt"@
LoginRequest
email (	Remail
password (	Rpassword"H

LoginResponse
token (	Rtoken!
user (2
.account.UserRuser"/
CreateTransactionPinRequest
pin (Rpin"4
InitiatePasswordResetRequest
email (	Remail"`
ResetPasswordRequest
email (	Remail
otp (Rotp 
newPassword (	RnewPassword"Q
ResetPinRequest
otp (Rotp,
newTransactionPin (RnewTransactionPin*<
USER_PROFILE_MODE_OF_INVESTMENT

INDIVIDUAL	
GROUP2�
AccountServiceA
Signup.account.CreateUserRequest.account.CreateUserResponse6
Login.account.LoginRequest.account.LoginResponse0
GetUser.google.protobuf.Empty
.account.User?
CreateUserProfile.account.UserProfile.account.UserProfile?
UpdateUserProfile.account.UserProfile.account.UserProfile:

GetProfile.google.protobuf.Empty.account.UserProfileT
	CreatePin$.account.CreateTransactionPinRequest!.account.GenericOperationResponseM
InitiatePinReset.google.protobuf.Empty!.account.GenericOperationResponseG
ResetPin.account.ResetPinRequest!.account.GenericOperationResponsea
InitiatePasswordReset%.account.InitiatePasswordResetRequest!.account.GenericOperationResponseQ

ResetPassword.account.ResetPasswordRequest!.account.GenericOperationResponsebproto3

**Comment by tzssangglass** [comment]
ping @ochuko3d is this problem solved? and the pb file you posted is unreadable, you can upload it as a file and give the configuration and steps and I will try to reproduce it.
