### ISSUE TITLE
help request: Is there a way to constrain the key used for key-authing of a route to a specific one?

### ISSUE THREAD

**Issue by lee-x-zh** [apache/apisix#7635]
### Description

We use key-auth plugin to authenticate requests. we planed different keys(consumers) for different routes for access control usage. While we found with a arbitrary predefined key,  one can access all routes.
So, Is there any way to leverage consumers' keys to do access control  via key-auth plugin?

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
what you need is: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/consumer-restriction.md

and we discussion about consumer group on: https://github.com/apache/apisix/issues/7488

**Comment by lee-x-zh** [comment]
Indeed! That's the very solution to my problems. Thanks.
