### ISSUE TITLE
help request:about 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#7650]
### Description

i set upstream discovery kubernetes type , but it not work.when i access a path(i had set route), i got a error code like this:503 Service Temporarily Unavailable.
and the error log like this:
`[error] 17748#17748: *849588 [lua] init.lua:540: http_access_phase(): failed to set upstream: no valid upstream node: nil, client: 192.168.92.100, server: _, request: "GET /apisix/index.html HTTP/1.1", host: "192.168.92.101:9080"
`
i change the source code to confirm if the ip had added and i got the log like this:
`on_modified(): #######10.245.2.21 80 50, context: ngx.timer`
its mean that the correct ip has be added because this is the pod ip in kubernetes.
and if i set the upstream in nodes mod,it also works(use pod ip directly)
this's the upstream set 
```
{
  "uri": "/apisix/*",
  "name": "",
  "upstream": {
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "discovery_type": "kubernetes",
    "pass_host": "pass",
    "service_name": "nginx-service"
  },
  "status": 1
}
```
so i want to know how i should do to fix it

### Environment

- APISIX version 2.15

**Comment by tokers** [comment]
@Nobilta Please read the document carefully: https://apisix.apache.org/docs/apisix/discovery/kubernetes/#interface

**Comment by Nobilta** [comment]
> @Nobilta Please read the document carefully: https://apisix.apache.org/docs/apisix/discovery/kubernetes/#interface
i have reed this document carefully,i just want to use service discovery registry for kubernetes,if i make a wrong upstream setting?

**Comment by Nobilta** [comment]
> @Nobilta Please read the document carefully: https://apisix.apache.org/docs/apisix/discovery/kubernetes/#interface

i have reed this document carefully,i just want to use service discovery registry for kubernetes,if i make a wrong upstream setting?

**Comment by tzssangglass** [comment]
> "discovery_type": "kubernetes",

This is the wrong usage, you should read the documentation carefully.

we specify the discovery type in `config.yaml` in the following way:

```yaml
discovery:
  kubernetes:
```

**Comment by Nobilta** [comment]
- to slove this problem i change the upstream's service_name like `"service_name": "default/nginx-service:nginx-port"` ,and it works.

**Comment by robertluoxu** [comment]
i hava new question
