### ISSUE TITLE
help request: init.lua:349: store_token(): ext-plugin:set valid items forcibly overwritten

### ISSUE THREAD

**Issue by ZhangShangyu** [apache/apisix#7651]
### Description

got many warning in apisix error log, this is the msg:

2022/08/11 14:36:00 [warn] 58#58: *71699987 [lua] init.lua:349: store_token(): ext-plugin:set valid items forcibly overwritten

what is the log indicate? can any master to explain this?

### Environment

- APISIX version 2.13-0

**Comment by Hazel6869** [comment]
@ZhangShangyu Hi, the variable shdict is shared memory which name is "ext-plugin", the log indicate  that "forcible: a boolean value to indicate whether other valid items have been removed forcibly when out of storage in the shared memory zone."  may be you can change the value of "ext-plugin" in config-default.yaml.

**Comment by ZhangShangyu** [comment]
> 

thanks your explanation. 
so this log just a tips, not related to a performance or business issue?

**Comment by tzssangglass** [comment]
> so this log just a tips, not related to a performance or business issue?

we would better to do as `change the value of "ext-plugin" in config-default.yaml.`, we can make the shared dict size of `ext-plugin` in `config-default.yaml` to be large. Or you can submit an PR to do this.

**Comment by ZhangShangyu** [comment]
> > so this log just a tips, not related to a performance or business issue?
> 
> we would better to do as `change the value of "ext-plugin" in config-default.yaml.`, we can make the shared dict size of `ext-plugin` in `config-default.yaml` to be large. Or you can submit an PR to do this.

1m maybe small,  how about change to 10m like most other config value in lua_shared_dict?

**Comment by tzssangglass** [comment]
> 1m maybe small, how about change to 10m like most other config value in lua_shared_dict? @tzssangglass

you can set it to 10M by yourself.
