### ISSUE TITLE
docs: Dead link

### ISSUE THREAD

**Issue by stillfox-lee** [apache/apisix#7660]
### Current State

https://github.com/apache/apisix/blob/5bdcd4412025877b15ea71510be13ebfca52d220/docs/zh/latest/stream-proxy.md?plain=1#L74

[test case] link 404.

### Desired State

Link to the right test case URL.

**Comment by stillfox-lee** [comment]
https://github.com/apache/apisix/blob/5bdcd4412025877b15ea71510be13ebfca52d220/docs/en/latest/stream-proxy.md?plain=1#L76
I found English version doc link to the right place.

**Comment by Hazel6869** [comment]
@stillfox-lee  Hi, thanks for your suggestion, we will fix it soon 😊

**Comment by stillfox-lee** [comment]
Maybe add a markdown linter to check dead link in CI?

**Comment by Hazel6869** [comment]
@stillfox-lee  thanks for your suggestion 👍,  @tzssangglass can follow 😊

**Comment by tzssangglass** [comment]
> Maybe add a markdown linter to check dead link in CI?

we check markdown in this CI workflow:https://github.com/apache/apisix/blob/master/.github/workflows/doc-lint.yml

if we can add markdown linter in this workflow, PR is welcome!
