### ISSUE TITLE
bug: [Plugin] OpenID-Connect had an issue or not supported when using "use_jwks=true" and use "discovery" as the JWKS endpoint

### ISSUE THREAD

**Issue by sangnguyen7** [apache/apisix#7661]
### Current Behavior

Get 401 Response when introspecting a JWK token: 

WWW-Authenticate="Bearer realm="apisix", error="invalid_token", error_description="opts.discovery.jwks_uri is not present or not a string"

I have checked the openid-connect plugin code, it's using "resty.openidc" which supports "discovery" as an object that has a property "jwks_uri". However, the current openid-conect plugin required "discovery" as a String.

### Expected Behavior

Should make "discovery" as an object, instead of String, so that we can config as "discovery.jwks_uri" 

### Steps to Reproduce

1. Setup a route ("/verify") to an upstream with an openid-connect plugin setting as follow:
```
{
  "uri": "/verify",
"plugins": {
    "openid-connect": {
      "client_id": "",
      "client_secret": "",
      "disable": false,
      "discovery.jwks_uri": "http://host:port/.well-known/jwks.json",
      "use_jwks": true
    }
  },
"upstream":{
    "type": "roundrobin",
    "nodes":{
      "httpbin.org:443":1
    }
  }
}'
```
2. Make a call
```
curl -i -X GET http://127.0.0.1:9080/verify -H "Host: httpbin.org" -H "Authorization: Bearer {JWT_TOKEN}"
```

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): Kubernetes
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@sangnguyen7  Hi,  you can try  use "discovery"  to replace  "discovery.jwks_uri".   The response returned by the value of "discovery" needs to contain "jwks_uri",   you can see https://openid.net/specs/openid-connect-discovery-1_0.html.

**Comment by sangnguyen7** [comment]
@Hazel6869 Thanks for your comment. Sorry, I did not know that I had entered incorrectly in the Step To Reproduce above. It should be like this: 
```
{
  "uri": "/verify",
"plugins": {
    "openid-connect": {
      "client_id": "",
      "client_secret": "",
      "disable": false,
      "discovery": "http://host:port/.well-known/jwks.json",
      "use_jwks": true
    }
  },
"upstream":{
    "type": "roundrobin",
    "nodes":{
      "httpbin.org:443":1
    }
  }
}'
```

Yes, I did use "discovery" for my JWKS endpoint and I got the error in this issue. 

"pts.discovery.jwks_uri is not present or not a string"

**Comment by sangnguyen7** [comment]
Here is the link to the code snippet that checks the jwks_uri in the "resty.openidc" package.

https://github.com/zmartzone/lua-resty-openidc/blob/b07330120ffe54dd3fbeac247726b76d0f9dc793/lib/resty/openidc.lua#L893

```
   jwks, err = openidc_jwks(opts.discovery.jwks_uri, force, opts.ssl_verify, opts.keepalive, opts.timeout, opts.jwk_expires_in, opts.proxy_opts,
```

As above, it requires the "discovery" as an object which contains "jwks_uri"

**Comment by Hazel6869** [comment]
@sangnguyen7 Hi, you can set "discovery" like "https://samples.auth0.com/.well-known/openid-configuration"

**Comment by tokers** [comment]
The error reason says:

> WWW-Authenticate="Bearer realm="apisix", error="invalid_token", error_description="opts.discovery.jwks_uri is not present or not a string"

Have you ever checked the discovery configuration? Especially for the `jwks_uri`?
