### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by ftlynx** [apache/apisix#7697]
### Description

请问下 apisix的upstream node设置成域名。如a.test.com， 此时a.test.com解析出来的IP是1.1.1.1。 如果在某个时候，a.test.com 的解析被改成了2.2.2.2， apisix能感知到dns解析的变化吗？

关于upstream 的处理逻辑大概是什么样呢？是下面三个情况还是其它的逻辑呢？
1. 添加upstream的时候解析一下域名对应的ip，一直固定成这个IP
2. 每次请求upstream的时候解析一下这个域名
3. 每次请求upstream的时候解析且apisix还维护了一个dns缓存

目前我测试出来的结果是，我把a.test.com的dns解析从 1.1.1.1修改成2.2.2.2后，访问apisix的时候，upstream的地址1.1.1.1, 2.2.2.2 都存在,是否是缓存导致的呢？我已经在机器上面dig a.test.com出来的IP是2.2.2.2了。

### Environment

- APISIX version (run `apisix version`):  
- Operating system (run `uname -a`):  
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

使用的是docker image  为 apache/apisix:2.15.0-centos

**Comment by tokers** [comment]
> 请问下 apisix的upstream node设置成域名。如a.test.com， 此时a.test.com解析出来的IP是1.1.1.1。 如果在某个时候，a.test.com 的解析被改成了2.2.2.2， apisix能感知到dns解析的变化吗？

Yes it can.

We have a DNS cache for the domain. You should also check out your DNS resolution TTL.
