### ISSUE TITLE
help request: apisix-seed multi upstream node

### ISSUE THREAD

**Issue by EthanKk** [apache/apisix#7710]
### Description

With a service name，has multi upsteam node.How to regiest these node ip address in zookeeper。
One node format is ” create /zookeeper/APISIX-ZK '{"host":"127.0.0.1:1980","weight":100}'“，what is the format when one service name with multi upstream node

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
form: https://github.com/api7/apisix-seed/issues/53, it is not support yet. 

and pls discuss this issue in `apisix-seed` project, close this.
