### ISSUE TITLE
help request: Can apisix limit the request for a single api by source ip?

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#7718]
### Description

Can apisix limit the request for a single api by source ip, how should I do it?

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@GhangZh Hi, you can see   https://apisix.apache.org/zh/docs/apisix/plugins/ip-restriction/
