### ISSUE TITLE
feat: As a user, I want to log-rotate plugin support max_size

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#7724]
### Description

The log-rotate can only split file by interval, i want to split log file by max_size.

**Comment by tzssangglass** [comment]
I've been thinking about it for a while and it seems a bit of a problem? Do we have to start a timer to monitor the size of log files?

**Comment by qihaiyan** [comment]
> I've been thinking about it for a while and it seems a bit of a problem? Do we have to start a timer to monitor the size of log files?

Seams so, the unix system has a logrotate utility depending on cron, something as a timer.

**Comment by tzssangglass** [comment]
> Seams so, the unix system has a logrotate utility depending on cron, something as a timer.

we can use `ngx.timer.every()`

**Comment by qihaiyan** [comment]
I can have a try to fix it. @tzssangglass

**Comment by tzssangglass** [comment]
@qihaiyan assigned you, have fun.

**Comment by emperorente** [comment]
@qihaiyan any plan for this?  I have the same requirement.

**Comment by qihaiyan** [comment]
> @qihaiyan any plan for this? I have the same requirement.

It's about to be finished in this month. @emperorente

**Comment by emperorente** [comment]
Sounds Great, I await your update!
