### ISSUE TITLE
help request: HTTPS not working 

### ISSUE THREAD

**Issue by ochuko3d** [apache/apisix#7726]
### Description

- APISIX version (run `apisix version`): APISIX Ingress controller on EKS
- Operating system (run `uname -a`): Kubernetes
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`): how do i get this 

Hi Guys ,

So i am trying to configure https on my ingress using AWS certificate  manager. Below is the config

`
gateway:
  #type: NodePort
  # If you want to keep the client source IP, you can set this to Local.
   #ref: https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: nlb 
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http 
     service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*" 
     service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:1xxxxx:xxxx-xxxxx" 
     service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  externalIPs: []
  http:
    enabled: true
    servicePort: 80
    containerPort: 9080
  tls:
    enabled: true
    servicePort: 443
    containerPort: 9443
    existingCASecret: ""
    certCAFilename: ""
    http2:
      enabled: true
  stream:  # L4 proxy (TCP/UDP)
    enabled: false
    only: false
    tcp: []
    udp: []
  ingress:
    enabled: true
    annotations: 
      # kubernetes.io/ingress.class: nginx
      #  kubernetes.io/tls-acme: "true"
    hosts:
      - host: apisix.local
        paths: 
          - /*
    tls: []
  #  - secretName: apisix-tls
  #    hosts:
  #      - chart-example.local`

Everything ran smoothly and i got a happy helming. on checking the ec2-loadbalancer dashboard on AWS, i saw the newly created nlb and the certifcate attached to it.

![image](https://user-images.githubusercontent.com/28976224/185175806-75164d97-9b34-4c53-b0e8-e8760828b418.png)

1. I got this error when i tried using the redirect function
![image](https://user-images.githubusercontent.com/28976224/185174157-e37d5a30-ab88-44a8-8843-c48b58199c97.png)

2. I got this error at the browser, which shows the https icon, but i cannot proceed.
![image](https://user-images.githubusercontent.com/28976224/185175437-f1326bb1-91c1-4a63-9fee-dfcb3b21702a.png)

Am i to make any further modification?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
The error message is self-explained. You sent a plain HTTP request to an HTTPS port.  Try to use HTTPS scheme.

**Comment by ochuko3d** [comment]
Exactly, i changed the scheme to https, and was still getting the above. The Padlock still shows but stops there. I appreciate your prompt response, but do you have a template for SSL already enabled with AWS certificate on EKS.

**Comment by tokers** [comment]
> but do you have a template for SSL already enabled with AWS certificate on EKS

Sorry I cannot understand the meaning, but https://apisix.apache.org/blog/2021/10/22/cert-manager-in-ingress/ may help you.

**Comment by tzssangglass** [comment]
> Exactly, i changed the scheme to https, and was still getting the above. The Padlock still shows but stops there. I appreciate your prompt response, but do you have a template for SSL already enabled with AWS certificate on EKS.

Can you provide a complete reproduction of the use case?

What is the `Location` returned by the redirect plugin that you can capture?
