### ISSUE TITLE
feat: support of ocsp stapling

### ISSUE THREAD

**Issue by ryan4yin** [apache/apisix#7729]
### Description

I found there is no arguments/API about ocsp stapling in APISIX. and the following code indicates ocsp stapling is not supported yet:

https://github.com/apache/apisix/blob/b85ebd4e1cc1a41f7799f6458d421d56169e5e05/apisix/patch.lua#L269

Is there any plans to implement this feature?

**Comment by tokers** [comment]
Currently, not. Do you have any idea about it?

**Comment by ryan4yin** [comment]
@tokers Currently not, just curious about it~
