### ISSUE TITLE
help request: how to implement this Nginx configuration in apisix

### ISSUE THREAD

**Issue by believe1499** [apache/apisix#7735]
### Description

在apisix中如何实现这段Nginx的配置
location ~ ^/apisix/test/(.)? {
if ($request_method = 'OPTIONS') {
add_header 'Access-Control-Allow-Origin' '' always;
add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Max-Age' 1728000;
add_header 'Content-Type' 'text/plain charset=UTF-8';
add_header 'Content-Length' 0;
return 204;
}
if ($request_method = 'GET') {
add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
}

    if ($request_method = 'POST') {
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
    }

    proxy_pass    http://192.168.1.125:8080/$1;
    proxy_http_version 1.1;
    proxy_set_header Connection "upgrade";
    proxy_pass_header  Authorization;
    proxy_set_header Authorization $http_authorization;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Via "apisix.test.cn";
    proxy_redirect      off;
}
1、如何实现以上的if语句判断，根据不同的method需要添加不同的header（通过创建多个不同的路由规则？）
2、如何设置proxy_set_header（通过proxy-rewrite插件？）
3、如何设置proxy_pass_header

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> 如何实现以上的if语句判断，根据不同的method需要添加不同的header（通过创建多个不同的路由规则？）

yes, for example

add route route:

```shell
curl http://127.0.0.1:9080/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/get",
    "plugins": {
        "proxy-rewrite": {
            "headers": {
                "X-Api-Version": "v1",
                "X-Api-Engine": "apisix",
                "X-Api-useless": ""
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org:80": 1
        }
    }
}'
```

test:

```
curl http://127.0.0.1:9080/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1",
    "User-Agent": "curl/7.84.0",
    "X-Amzn-Trace-Id": "Root=1-62fe205b-636fcc8774d92f5936fc6bd5",
    "X-Api-Engine": "apisix",
    "X-Api-Version": "v1",
    "X-Forwarded-Host": "127.0.0.1"
  },
  "origin": "127.0.0.1, xxxxxx",
  "url": "http://127.0.0.1/get"
}
```



> 如何设置proxy_set_header（通过proxy-rewrite插件？）
> 如何设置proxy_pass_header
ref: https://github.com/apache/apisix/blob/master/docs/en/latest/customize-nginx-configuration.md

**Comment by kellyseeme** [comment]
@believe1499  hello,你实现了你发的配置了么？咋实现的。
`if ($request_method = 'OPTIONS') {
add_header 'Access-Control-Allow-Origin' '' always;
add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Max-Age' 1728000;
add_header 'Content-Type' 'text/plain charset=UTF-8';
add_header 'Content-Length' 0;
return 204;
}`
