### ISSUE TITLE
help request: how to implement writing subdomain into haeder header in apisix (implemented with nginx)

### ISSUE THREAD

**Issue by guaosi** [apache/apisix#7739]
### Description

nginx中的配置实现：
```
server {
    listen 80;
    server_name ~^(?<subdomain>.+)\.partner\.com$;
    root /docker/www;
    access_log /docker/log/nginx/$server_name.access.log  main;  
    # 转发
    location /api/v1 {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Subdomain $subdomain;
        proxy_pass http://backend;
    }
}
```
没想出来在apisix中应该怎么配置才能实现获取到动态的子域名然后填写进header中(业务需要),希望可以不吝赐教

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
See https://apisix.apache.org/docs/apisix/plugins/serverless/, write piece of code to do that, or just injecting the same Nginx configuration to Apache APISIX (see https://apisix.apache.org/docs/apisix/customize-nginx-configuration/).
