### ISSUE TITLE
feat: config time of log-rotate plugin work

### ISSUE THREAD

**Issue by mikawudi** [apache/apisix#7743]
### Description

log-rotate work on 
first:
    rotate_time = now_time + interval - (now_time % interval)
update:
     rotate_time = rotate_time + interval
when i set interval = 86400 and compression = true, i wan't the log-rotate rename and compression access and error log every day, but  now_time is timestamp of second.....server timezone in +08:00, so it work at 08:00 am every day.....
can i add an config field to offset the work time? because 08:00 is busy time......compression big access log file in busy time is not a good idea
<img width="723" alt="E8005A50-7B76-4454-A8C0-486174F53A65" src="https://user-images.githubusercontent.com/8215006/185557443-4e721264-9c94-4cfd-a24b-4aefab47419f.png">

**Comment by kingluo** [comment]
@mikawudi @spacewander Is it a good idea to do the log rotate based on cron-like expr? 
```
# run five minutes after midnight, every day
5 0 * * *
```

**Comment by spacewander** [comment]
> @mikawudi @spacewander Is it a good idea to do the log rotate based on cron-like expr?
> 
> ```
> # run five minutes after midnight, every day
> 5 0 * * *
> ```

LGTM

**Comment by mikawudi** [comment]
> @mikawudi @spacewander Is it a good idea to do the log rotate based on cron-like expr?
> 
> ```
> # run five minutes after midnight, every day
> 5 0 * * *
> ```

@kingluo i think it's a good idea
