### ISSUE TITLE
help request: The latency of request is not stable as expected

### ISSUE THREAD

**Issue by xjhuiw** [apache/apisix#7745]
### Description

I already  set the prometheus plugin was disabled  according to  steps  (https://github.com/apache/apisix/issues/5604)
But t here is still  appear  repreat phenomenon that  the latency of request is not stable as expected 

The request will be triggered from time to time after the request enters apisix, and the request will be sent to the back end with a delay of 3-4s

my  Environment for : 
- APISIX version (run `apisix version`): 2.6 
- Operating system (run `uname -a`): centos7 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.3.1

### Environment

- APISIX version (run `apisix version`): 2.6 
- Operating system (run `uname -a`): centos7 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.3.1

**Comment by tzssangglass** [comment]
can you use [openresty-xray](https://openresty.com/en/xray/) or [SystemTap](https://moonbingbing.gitbooks.io/openresty-best-practices/content/flame_graph/install.html) to generate a flamegarph ? Note that I am not the developer of X-Ray (it is a commercial product developed by others). 

For me, the following problems prevent me to provide help:

1. version 2.6 is too old
2. I don't have your environment to reproduce the problem
