### ISSUE TITLE
help request: hmac Authorization 如何拼接？

### ISSUE THREAD

**Issue by cnn007** [apache/apisix#7756]
### Description

https://apisix.apache.org/zh/docs/apisix/plugins/hmac-auth/

参考： 签名可以放到请求头 Authorization 字段中：
`
curl http://127.0.0.1:9080/index.html \
-H 'Authorization: hmac-auth-v1# + ACCESS_KEY + # + base64_encode(SIGNATURE) + # + ALGORITHM + # + DATE + # + SIGNED_HEADERS' -i
`
问题:
参考的就是这个链接，
1、Authorization 格式是什么，
2、'# + ' 真实字串中需要吗，有空格吗？
3、SIGNED_HEADERS 是怎么拼接的，只需要拼接名称，值不需要拼接是吗。

下面是我的一个请求示例（看下格式是否正确）：
`
curl -i "http://127.0.0.1:9080/index.html?name=james&age=36" \
-H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'
`

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
> 1、Authorization 格式是什么，

The signature without a prefix like Bearer

@tzssangglass We need a more clear doc for HMAC. The current version is not friendly to developers (even for me, it's not easy to understand).

**Comment by tzssangglass** [comment]
> 下面是我的一个请求示例（看下格式是否正确）：
> `curl -i "http://127.0.0.1:9080/index.html?name=james&age=36" \ -H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'`

It looks correct, and here is the correct format that I got from running the test cases:

```
"hmac-auth-v1#my-access-key#DjnaOTdYIQsMOlr/2vY45WZjeaUnhiWLylfRvPL95N8=#hmac-sha256#Mon, 22 Aug 2022 09:50:16 GMT#x-custom-header-a;x-custom-header-b"
```

**Comment by tzssangglass** [comment]
> We need a more clear doc for HMAC. The current version is not friendly to developers (even for me, it's not easy to understand).

I think it is because this algorithm is complex and if we want the documentation to be easy to read, we need the help of the documentation team. cc @juzhiyuan @SylviaBABY

I've looked at the documentation and have no better ideas. Maybe adding more pictures to show the algorithm process would be easier to read.

**Comment by SylviaBABY** [comment]
> > We need a more clear doc for HMAC. The current version is not friendly to developers (even for me, it's not easy to understand).
> 
> I think it is because this algorithm is complex, and if we want the documentation to be easy to read, we need the help of the documentation team. cc @juzhiyuan @SylviaBABY
> 
> I've looked at the documentation and have no better ideas. Maybe adding more pictures to show the algorithm process would be easier to read.

OK, I need more details about this improvement, so feel free to talk with me recently @tzssangglass. I will leave comments on this issue with more information as soon as the direction of revision is precise^^

**Comment by cnn007** [comment]
> > 下面是我的一个请求示例（看下格式是否正确）：
> > `curl -i "http://127.0.0.1:9080/index.html?name=james&age=36" \ -H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'`
> 
> It looks correct, and here is the correct format that I got from running the test cases:
> 
> ```
> "hmac-auth-v1#my-access-key#DjnaOTdYIQsMOlr/2vY45WZjeaUnhiWLylfRvPL95N8=#hmac-sha256#Mon, 22 Aug 2022 09:50:16 GMT#x-custom-header-a;x-custom-header-b"
> ```

without  'Authorization' ?  whcih one ? A or B.

`
A:
-H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'

B:
-H 'hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'
`
![image](https://user-images.githubusercontent.com/13449400/186114279-f36d1997-f0b7-465f-9747-d65b3b96d1de.png)

**Comment by tzssangglass** [comment]
> A:
> -H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'

need `x-custom-header-a`, ref: https://github.com/apache/apisix/blob/1aeb3a6517458bce94988e0d6e05a210fb70cfa2/t/plugin/hmac-auth.t#L624-L684

**Comment by cnn007** [comment]
> > A:
> > -H 'Authorization: hmac-auth-v1#user-key#8XV1GB7Tq23OJcoz6wjqTs4ZLxr9DiLoY4PxzScWGYg=#hmac-sha256#Tue, 19 Jan 2021 11:33:20 GMT#User-Agent;x-custom-a'
> 
> need `x-custom-header-a`, ref:
> 
> https://github.com/apache/apisix/blob/1aeb3a6517458bce94988e0d6e05a210fb70cfa2/t/plugin/hmac-auth.t#L624-L684

thank. The header needs to add 
-H "x-custom-a: test" \
-H "User-Agent: curl/7.29.0"
