### ISSUE TITLE
help request: apisix logs are messed up

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#7758]
### Description

![image](https://user-images.githubusercontent.com/92301646/185881084-b1af55b1-5dcb-4254-8f2a-baf86cbf1ea1.png)

We have customized the apisix log format, but recently there have been a large number of requests with faulty logs

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.19
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Please provide your custom log format.

**Comment by GhangZh** [comment]
> 

![image](https://user-images.githubusercontent.com/92301646/185882813-9e708521-5c7e-434e-9c41-bc89abb8227a.png)

**Comment by GhangZh** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/92301646/185882813-9e708521-5c7e-434e-9c41-bc89abb8227a.png)

**Comment by tzssangglass** [comment]
use text instead of images to show logs and confiurations.

**Comment by GhangZh** [comment]
> 

```bash
    nginx_config:                     # config for render the template to genarate nginx.conf
      error_log: "/dev/stderr"
      error_log_level: "warn"         # warn,error
      worker_rlimit_nofile: 60000     # the number of files a worker process can open, should be larger than worker_connections
      event:
        worker_connections: 60000

      http:
        enable_access_log: true
        access_log: "/dev/stdout"
        access_log_format: "{\"@timestamp\": \"$time_iso8601\", \"remote_addr\": \"$remote_addr\", \"costime\": $request_time, \"realtime\": \"$upstream_response_time\", \"status\": $status, \"x_forwarded\": \"$http_x_forwarded_for\", \"vhost\": \"$host\", \"server_addr\":\"$server_addr\", \"referer\": \"$http_referer\", \"method\": \"$request_method\", \"url\": \"$uri\", \"args\": \"$args\", \"request_url\":\"$request_uri\", \"upstream_name\":\"$upstream_name\", \"upstr_addr\": \"$upstream_addr\",\"bytes\": $bytes_sent, \"body_bytes\":$body_bytes_sent, \"http_agent\": \"$http_user_agent\"}"
        access_log_format_escape: json
```

**Comment by kwanhur** [comment]
it seems to say some access logs missing `vhost` content.

A mini demo to reproduce will be better.
