### ISSUE TITLE
feat: As a user, I want to see APISIX Heroes list, so that our community members work is recognized and mentioned

### ISSUE THREAD

**Issue by Boburmirzo** [apache/apisix#7765]
### Description

It would be nice to have a new webpage for the Apache APISIX Heroes list where we can mention our active contributors' name on the website and promote them. The page will be similar to:

 https://hazelcast.com/dev-community/heroes/
OR
https://linkerd.io/community/heroes/

**Comment by nfrankel** [comment]
Just pasting what I wrote earlier to keep a trace:

>my experience is that a hero programme is not only about a web page with lists of people
>(well, it's what i did because i had not time, but there were no benefits)
>we should regularly engage with the heroes to keep them motivated
>and it's time consuming

**Comment by tokers** [comment]
@Boburmirzo All contributors will be there or just the active parts?

Indeed, I'm not sure whether this is compliant with Apache, we don't say we are the core contributors, all contributors are equal.

**Comment by kwanhur** [comment]
A hero list for what? What can people get from the list as a contributor, a viewer, or an observer?
