### ISSUE TITLE
help request: about file-logger, why use get_last_reopen_ms to check file's opened-time? 

### ISSUE THREAD

**Issue by zfs123** [apache/apisix#7767]
### Description

Lrucache is worker exclusive, when worker is dead, cache and fd in cache will release. 
so why check the last_reopen_ms, does it mean the file may be reopened before get fd from cache ?  Under what situations will the file be reopened ?

Thanks.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
When using APISIX with apisix-base (which is the default if APISIX is installed from official rpm or docker), the file in file-logger will be reopened once Nginx receives the SIGUSR1 signal. The behavior is the same as Nginx's reopen log file feature.

**Comment by zfs123** [comment]
Thx.
