### ISSUE TITLE
是否可以用apisix作为k8s集群内部的服务的api-gateway

### ISSUE THREAD

**Issue by andyzheung** [apache/apisix#7769]
### Description

由于k8s集群内部的服务之间也会相互调用，但是希望能够统一将限流、鉴权等做到一起，因此希望所有集群内部的后端服务互访也通过一个gateway进行。
但是看了apisix的gateway只支持nodeport和lb模式，不知道是否能够支持我说的这种需求。
集群内服务互访不走coredns域名，都走到api-gateway，然后再转到后端。
![image](https://user-images.githubusercontent.com/22912347/186063638-c1d28b4b-d491-475b-b076-d937ce2f9b8f.png)

### Environment

1、k8s环境。

**Comment by tzssangglass** [comment]
You mean using APISIX to proxy east-west traffic?

cc @tokers @tao12345666333

**Comment by tzssangglass** [comment]
I think this would help for you: https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/kubernetes.md

**Comment by tao12345666333** [comment]
sure, its a basic function

**Comment by andyzheung** [comment]
> APISIX to proxy east-west traffic?

是的，希望用gateway解决集群内部的东西向流量，不用绕到外部。

**Comment by andyzheung** [comment]
> I think this would help for you: https://github.com/apache/apisix/blob/master/docs/en/latest/discovery/kubernetes.md

看了这篇文章，但并不理解如何配置k8s集群内部的微服务如何通过apisix来作为网关。

**Comment by tzssangglass** [comment]
> 看了这篇文章，但并不理解如何配置k8s集群内部的微服务如何通过apisix来作为网关。

We can't solve a problem as big as you not understanding something in an issue. You can come to us with a specific problem and ask for help.

**Comment by tokers** [comment]
> 

Yes, this doc shows how you can configure the Kubernetes service discovery on APISIX. As for how other components can call APISIX, it varies and depends on your topology and business needs.
