### ISSUE TITLE
help request: is it  possible to set up a google account auth 

### ISSUE THREAD

**Issue by akalittle** [apache/apisix#7770]
### Description

We have some dashboards and monitoring systems and the systems need a username & password to log in.
But we want to log in to all the systems by google account.
Is it possible to use a `forward-auth` plugin or some others?

### Environment

apache/apisix:2.15.0-alpine
apache/apisix-ingress-controller:1.4.1
docker.io/bitnami/etcd:3.5.4-debian-11-r14

Kubernetes cluster version:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-gke.2200

**Comment by tzssangglass** [comment]
What do you need? A demo about APISIX using auth plugins works well with google account?

**Comment by akalittle** [comment]
> What do you need? A demo about APISIX using auth plugins works well with google account?

Yep.A demo works fine with google account.

**Comment by tzssangglass** [comment]
I think you can try it first. we have no completed demo at this time.

**Comment by tokers** [comment]
@akalittle Is the OpenID Connect plugin available for you?

**Comment by akalittle** [comment]
> @akalittle Is the OpenID Connect plugin available for you?

Thanks. I will try this plugin.
