### ISSUE TITLE
bug: the request time is smaller than upsteam count delay

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#7772]
### Current Behavior

![image](https://user-images.githubusercontent.com/88528414/186149848-6f61e47e-aca7-4dfa-8f17-e0452773666e.png)

### Error Logs

access_log_format: "$remote_addr $toa_remote_addr - $remote_user [$fmt_ms_time_local] $http_host \"$request\" $status $body_bytes_sent $content_length $request_time \"$http_referer\" \"$http_user_agent\" $http_x_request_id $http_x_amz_target $upstream_addr $upstream_status $upstream_connect_time $upstream_header_time $upstream_response_time"

### Steps to Reproduce

1 TODO

### Environment

- APISIX version (run `apisix version`): 2.7 
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
pls use the latest master branch to test, I remember that we have fix some bugs about this.

**Comment by zhendongcmss** [comment]
> pls use the latest master branch to test, I remember that we have fix some bugs about this.

Do you know that where is the PR we fix it. 
This bug is sporadic and difficult to reproduce.

**Comment by tzssangglass** [comment]
Unfortunately, I don't know.
