### ISSUE TITLE
bug: Reposne_write plugin will delete the server-side cookies

### ISSUE THREAD

**Issue by JohnQI8888** [apache/apisix#7776]
### Current Behavior

Reposne_write plugin will delete the server-side cookies

### Steps to Reproduce

1. Run apisix
2. setup a route looks like this:
"value": {
                    "host": "aaa.xxx.com",
                    "plugins": {
                        "prometheus": {},
                        "response-rewrite": {
                            "headers": {
                                "Set-Cookie": "tagged=23333; Expires=Wed, 11 Sep 2030 08:00:00 GMT"
                            }
                        } 
                    },
                    "uris": [
                        "/*"
                    ],
                    "filter_func": "function(vars)\n    return true\nend",
                    "upstream_id": "127",
                    "name": "-master_r_2022-08-17_3-DEFAULT",
                    "priority": 0,
                    "id": "345"
                },
3.  the backend server setup another cookie
4.  check the response, you will find the server-side cookies were deleted.

### Environment

- APISIX version (run `apisix version`):1.5
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Known issue. We will fix it via https://lists.apache.org/thread/bxl0sn1qb5fchvnynz7b8sst9r07cyqm.

**Comment by spacewander** [comment]
Known issue. We will fix it via https://lists.apache.org/thread/bxl0sn1qb5fchvnynz7b8sst9r07cyqm.
