### ISSUE TITLE
help request: should i choose apisix discovery or apisix ingress cotroller?

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#7777]
### Description

i want to use the  Service Discovery of kubernetes，but i have two choose apisix discovery and apisix ingress controller.
what‘s their difference?And which one should i choose?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
It's up to you. Kubernetes service discovery just implements the service discovery, it cannot do things like Certificates management via Kubernetes secrets (in the case of Ingress Controller, it's feasible). Also, it depends on the way you want to manage APISIX, i.e. REST API / Web Console vs Declarative Configurations.
