### ISSUE TITLE
feat: As a user, I want to support service discovery in the stream subsystem

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7779]
### Description

As a user, I want to support service discovery in the stream subsystem, so that we can use it to get L4 upstream dynamically.

There is already an unfinished closed PR to add this feature: https://github.com/apache/apisix/pull/4488.
However, this PR is closed last year and the code has been changed a lot since that. So we can borrow some code from that PR but can't continue based on it.

**Comment by spacewander** [comment]
@zhixiongdu027
Would you like to have a try?

**Comment by zhixiongdu027** [comment]
I'm interested in doing this, but my todo list is temporarily full ~@_@~

**Comment by spacewander** [comment]
@zhixiongdu027 
Thanks for your reply.

**Comment by ronething** [comment]
i will try this, please assign to me.
