### ISSUE TITLE
bug: cors plugin  option request random use more seconds time

### ISSUE THREAD

**Issue by laokan** [apache/apisix#7781]
### Current Behavior

![image](https://user-images.githubusercontent.com/471843/186399261-1edbe48b-45b5-4677-8f25-ecc49cb686c5.png)
the cors pulugin option request!
sometime cost 6 second

### Steps to Reproduce

1. request the backend service with the cors plugin ,  some times the OPTION request use a high time

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
Do any access log and error log about this delay OPTION request?

How did you determine that the delay occurred in APISIX and not upstream?
