### ISSUE TITLE
can we use luajit string.buffer Serialization in apisix now

### ISSUE THREAD

**Issue by zhixiongdu027** [apache/apisix#7784]
### Description

In the openresty release notes, we can see that string.buffer is enabled.
Maybe we can use string.buffer's serialization function instead of json serialization/deserialization

![image](https://user-images.githubusercontent.com/4032302/186443606-28220b65-833d-451e-a83c-ad49adb508be.png)

More details on string.buffer can be found here:
[string.buffer](https://luapower.com/files/luapower/csrc/luajit/src/doc/ext_buffer.html)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@zhixiongdu027 Use `string.buffer` to mimic the JSON marshalling operation?

**Comment by spacewander** [comment]
`string.buffer` can be used internally. Maybe we can discover some use cases inside APISIX.

**Comment by zhixiongdu027** [comment]
@spacewander That's Great !
