### ISSUE TITLE
feat: As a user, I want to just verify the format of the resource configuration without writing to etcd

### ISSUE THREAD

**Issue by soulbird** [apache/apisix#7790]
### Description

WHY:
As a user, I want to just verify the format of the resource configuration without writing to etcd, so that I can write the configuration directly to etcd and be guaranteed to be available.

HOW:
The Admin API can provide a dry-run mode: only verifying whether the resource configuration format is correct, not writing etcd.
Whether dry-run mode is enabled can be determined by adding a request parameter to the existing API

**Comment by shreemaan-abhishek** [comment]
Fixed by #10065
