### ISSUE TITLE
help request: How to modify the default priority of a plugin

### ISSUE THREAD

**Issue by kense-lab** [apache/apisix#7793]
### Description

`鉴权插件` 的默认优先级是高于 `限流插件` 的，这样鉴权服务就是吃不到限流buff了
如何做到先走 `限流插件` 再走 `鉴权插件`，插件的默认优先级可以修改吗?
不太想升级2.15版本

### Environment

- APISIX version (run `apisix version`): 2.14.0

**Comment by Hazel6869** [comment]
@kense-lab  Hi,  you need 2.15.0 😊.   https://apisix.apache.org/zh/blog/2022/07/29/release-apache-apisix-2.15/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6%E4%BC%98%E5%85%88%E7%BA%A7

**Comment by kense-lab** [comment]
@Hazel6869

**Comment by tokers** [comment]
> @Hazel6869 Is there any other way besides upgrading to 2.15?

You may have to apply the patch to your version.

**Comment by Hazel6869** [comment]
@kense-lab  Hi,  If you only care about the priority of the plugin and don't consider routing, you can do it by modifying the code.   https://github.com/apache/apisix/blob/3c0757477a8c4e24910bb998d06e1d13ec283738/apisix/plugins/limit-conn.lua#L47

**Comment by kense-lab** [comment]
Got, thanks!
