### ISSUE TITLE
bug: the b3 header data should be consistently sent downstream in zipkin plugin

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix#7795]
### Current Behavior

Enabel zipkin plugin.

Set `sample_ratio` to not equal to 1, for example, 0.1. APISIX will not send B3 header data downstream when a request does not require sampling.

### Expected Behavior

Enabel zipkin plugin.

Set `sample_ratio` to not equal to 1, for example, 0.1. Even when a request does not require sampling, Apisix sends B3 header data downstream.

### Steps to Reproduce

ref: https://apisix.apache.org/docs/apisix/plugins/zipkin/

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Gallardot** [comment]
ref: https://github.com/openzipkin/b3-propagation#sampling-state

```
Sampling is a mechanism to reduce the volume of data that ends up in the tracing system. 
In B3, sampling applies consistently per-trace: once the sampling decision is made, the same value should be consistently sent downstream. 
```

Even if the data is not sampled, the logic of the relevant phase should still be executed. But the final span data is not sent to the zipkin server.

**Comment by Gallardot** [comment]
[opentelemetry plugin](https://apisix.apache.org/docs/apisix/plugins/opentelemetry/) has the same problem.

**Comment by spacewander** [comment]
If I am correct, do you mean:
When there is a b3 header sent by the client, we should sample it regardless of the APISIX's configuration?
If so, why should not we report the span?

**Comment by Gallardot** [comment]
> If I am correct, do you mean: When there is a b3 header sent by the client, we should sample it regardless of the APISIX's configuration? If so, why should not we report the span? As the behavior of "sample" is to report the span to the zipkin server.

Thanks @spacewander 
I mean if the http request is to be sampled, then we have to report span data to the zipkin Server. There's no problem with that. 
However, we should send `B3 header` data to `upstream` regardless of whether the http request needs to be sampled or not.

**Comment by spacewander** [comment]
I got your point.
Here we delete b3 header in https://github.com/apache/apisix/blob/cffa4b69f9080707d100fbe856f251054cc8cba4/apisix/plugins/zipkin.lua#L130 because at that time not every upstream supports the b3 header so I choose to convert it to the old format `x-b3-xxx` headers.
Obviously, we didn't set the `x-b3-xxxid` headers like what we have done in https://github.com/apache/apisix/blob/cffa4b69f9080707d100fbe856f251054cc8cba4/apisix/plugins/zipkin/codec.lua#L96, when the sample is disabled.

**Comment by xuminwlt** [comment]
The same question when use opentelemetry plugin.

**Comment by spacewander** [comment]
> The same question when use opentelemetry plugin.

Please create a separate issue for another plugin, thanks!

**Comment by Gallardot** [comment]
@spacewander 

If the tracing data is not sampled and traceids are null, I think we need to create our own traceids and send it to upstream. I create a pr #8099
