### ISSUE TITLE
feat: As a user, I want to let proxy-mirror plugin resolve the host, so that the DNS resolver in APISIX can be used.

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7796]
### Description

The proxy-mirror doesn't support brighter DNS resolution, as its feature is currently based on Nginx's directive, which uses Nginx's own DNS resolution.

As Nginx's own DNS resolution doesn't support modern DNS features, this brings some inconvenience, especially under k8s.

To solve the problem, we need to resolve the host ourselves, and pass the result to the Nginx variable `upstream_mirror_uri`.
https://github.com/apache/apisix/blob/3c0757477a8c4e24910bb998d06e1d13ec283738/apisix/plugins/proxy-mirror.lua#L63-L65

We can use the method below to resolve the host:
https://github.com/apache/apisix/blob/3c0757477a8c4e24910bb998d06e1d13ec283738/apisix/core/resolver.lua#L44

**Comment by Strangevy** [comment]
Hello, just call “_m.parse_domain“ parsing "conf.host"?

**Comment by spacewander** [comment]
> Hello, just call “_M.parse_domain“ parsing "conf.host"?

Before that, we need to exact the real host from the "conf.host".

**Comment by Strangevy** [comment]
> > Hello, just call “_M.parse_domain“ parsing "conf.host"?
> 
> Before that, we need to exact the real host from the "conf.host".

Can you assign it to me? I think I can try it.

**Comment by tzssangglass** [comment]
hi @Strangevy assigned you, have fun.
