### ISSUE TITLE
bug: apisix 2.15.0 startup failed, when etcd prefix is a multi-level path

### ISSUE THREAD

**Issue by kense-lab** [apache/apisix#7801]
### Current Behavior

apisix startup failed

apisix version: `2.15.0`
config: `etcd.prefix: /cbp/apisix`

error: `failed to validate config: property "etcd" validation failed: property "prefix" validation failed: failed to match pattern "^/[^/]+$" with "/cbp/apisix"`

### Error Logs

failed to validate config: property "etcd" validation failed: property "prefix" validation failed: failed to match pattern "^/[^/]+$" with "/cbp/apisix"

### Steps to Reproduce

1. edit config.yml
    ```yaml
    etcd
      prefix: "/cbp/apisix"
    ```

2. run: `apisix start`

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by spacewander** [comment]
Fixed in https://github.com/apache/apisix/pull/7675
