### ISSUE TITLE
bug: Improper logic of only in stream proxy configuration

### ISSUE THREAD

**Issue by gtbio** [apache/apisix#7802]
### Current Behavior

when our config file(/usr/local/apisix/conf/config.yaml) setting like this:
```
apisix:
  node_listen:                      # This style support multiple ports
    - 9080
    - 9081
  enable_admin: false
  ...
  stream_proxy:                  # TCP/UDP proxy
    only: true                   # use stream proxy only, don't enable HTTP stuff
    tcp:                         # TCP proxy port list
      - addr: 8080
      - addr: 8081
  ...
```
the ports 8080, 8081 listed behind "node_listen" will not listen, because I set stream_proxy.only = true.

stream proxy does not configure its own on and off, but through the only field to control the http subsystem on and off, which may be inappropriate, I think they should have separate for their own switch to control, rather than through the other configuration parameters to determine their own state.

### Expected Behavior

we expect config like this:
```
apisix:
  http_proxy:
    - 9080 
    - 9081
  admin_listen:                # use a separate port
    ip: 127.0.0.1              # Specific IP, if not set, the default value is `0.0.0.0`.
    port: 9180
    enable_admin_cors: true
  ...
  stream_proxy:                  # TCP/UDP proxy
    tcp:                         # TCP proxy port list
      - addr: 8080
      - addr: 8081
  ...
```
just delete `apisix.stream_proxy.only` attribute and use `http_proxy.enbale` and `stream_proxy.enable` to set http and stream subsystem enable, and maybe we can replace `node_listen`

### Steps to Reproduce

None

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`): Linux host1 3.10.0-1127.19.1.el7.x86_64 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant: -
- Plugin runner version, for issues related to plugin runners: - 
- LuaRocks version, for installation issues (run `luarocks --version`): -

**Comment by spacewander** [comment]
Maybe we can do it in APISIX 4.0?
At that time, stream proxy may be widely used enough so we can introduce a breaking change and move it to the same level of HTTP proxy configuration.
