### ISSUE TITLE
bug: proxy-rewrite in consumer not working

### ISSUE THREAD

**Issue by extimo** [apache/apisix#7809]
### Current Behavior

proxy-rewrite in consumer not working

### Expected Behavior

headers rewrite as configured in consumer

### Steps to Reproduce

1.create a consumer with jwt-auth and proxy-rewrite(rewrite headers)
2.create a route(with uri rewrite)
3.send request to that route

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
Please provide full details of the reproduction steps.
