### ISSUE TITLE
help request: Does grpc-transcode plugin supports authenticated grpc service?

### ISSUE THREAD

**Issue by drriguz** [apache/apisix#7814]
### Description

Authentication should be configured for production gRPC services, see https://grpc.io/docs/guides/auth/.

When token based authentication is enabled for the grpc backend, how should I specify it in APISIX?
I could not found any documentation about that, is it supported?

```
"upstream": {
        "scheme": "grpc",
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:50051": 1
        }
    }
```

### Environment

Latest APISIX

**Comment by tokers** [comment]
If the token can be specified directly, try to use `proxy-rewrite` plugin, set it there.
