### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by feeops** [apache/apisix#7819]
### Current Behavior

parse_domain dns query error

### Expected Behavior

no error

### Error Logs

stream [lua] upstream.lua:79: parse_domain_for_nodes(): dns resolver domain: rm-xxxxxxxx.mysql.ap-southeast-7.rds.aliyuncs.com error: failed to query the DNS server: dns client error: 101 empty record received while prereading client data

### Steps to Reproduce

apisix v2.13,v2.14,v2.15

### Environment

在apisix使用四层tcp反代，2.10上没有问题
v2.13,v2.14,v2.15 均有问题

**Comment by monkeyDluffy6017** [comment]
Could you provide full details of the reproduction steps, about route's config, the consumer's config, and how to send a request to test?

**Comment by monkeyDluffy6017** [comment]
Is it the same problem with https://github.com/apache/apisix/issues/7733 ?

**Comment by feeops** [comment]
> Is it the same problem with #7733 ?

Yes.It is.

**Comment by tzssangglass** [comment]
trace in #7733
