### ISSUE TITLE
help request: prometheus Unexpected error adding a key

### ISSUE THREAD

**Issue by GhangZh** [apache/apisix#7824]
### Description

```bash
2022/08/31 10:53:48 [error] 93#93: *4602458732 [lua] prometheus.lua:872: log_error(): Unexpected error adding a key: no memory while logging request
```
What else can I do if I don't want to restart apisix when this error occurs?

### Environment

- APISIX version (run `apisix version`):2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wolgod** [comment]
你需要在你的config.yaml 中修改lua dict的大小
```
nginx_config:
  http:
    lua_shared_dict:
      prometheus-metrics: 200m
```
