### ISSUE TITLE
help request: no healthy etcd endpoint available

### ISSUE THREAD

**Issue by xmasye** [apache/apisix#7828]
### Description

After Apisix was upgraded to 2.15.0, I encountered a few errors, about once or twice a day. Probably related to Prometheus monitoring. Yes, I have Prometheus enabled

I use K8S, Apisix and ETCD are on the same network and are functioning normally with no other network related errors reported

`44#44: *34515967 [lua] exporter.lua:404: handler(): prometheus: failed to reach config server while processing metrics endpoint: has no healthy etcd endpoint available, client: 10.0.112.23, server: , request: "GET /apisix/prometheus/metrics HTTP/1.1", host: "10.0.80.20:9091"`
`44#44: *34544120 [lua] config_etcd.lua:568: no healthy etcd endpoint available, next retry after 2s, context: ngx.timer`

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux apisix-85f4998c66-kg6cs 5.4.119-1-tlinux4-0009-public-eks #1 SMP Wed Aug 3 18:18:38 CST 2022 x86_64 Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):     nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4.18-debian-10-r14
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):   3.8.0

**Comment by tzssangglass** [comment]
It looks like the ETCD is not responding, do you have the ETCD auto-compression feature turned on?

**Comment by xmasye** [comment]
> It looks like the ETCD is not responding, do you have the ETCD auto-compression feature turned on?
@tzssangglass 
I installed APISIX via Helm, 
The default configuration is used for deployment. I think the default configuration is turned on

auto-compaction-mode: periodic
auto-compaction-retention: "1"

thanks

**Comment by tzssangglass** [comment]
As a rule of thumb, this is an exception to the etcd response. I don't have a good solution. Need to keep an eye on the etcd logs and running status.

**Comment by tzssangglass** [comment]
As a rule of thumb, this is an exception to the etcd response. I don't have a good solution. Need to keep an eye on the etcd logs and running status.

**Comment by xmasye** [comment]
@tzssangglass 
Thank you for your help. I will keep looking at the ETCD
