### ISSUE TITLE
docs: installation-guide.md and getting-started.md are hard to read

### ISSUE THREAD

**Issue by william302** [apache/apisix#7831]
### Current State

 In the documentation's [get-started](https://github.com/apache/apisix#get-started ) part, links of [install documentation](https://github.com/apache/apisix/blob/master/docs/en/latest/installation-guide.md) and [Getting Started](https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started.md) are hard to read(guess due to the JSX part in MD file is not properly rendered)

### Desired State

Change link to APISIX Documentation site. 
 https://apisix.apache.org/docs/apisix/installation-guide/ and https://apisix.apache.org/docs/apisix/getting-started/

**Comment by hf400159** [comment]
@william302  Would you like to submit a PR to change it?

**Comment by monkeyDluffy6017** [comment]
I have updated the doc.
