### ISSUE TITLE
request help: url contains Chinese, will decode utf8 encoded url into hexadecimal format of \x

### ISSUE THREAD

**Issue by biubiue** [apache/apisix#7838]
### Current Behavior

raw url: https://xxx.com/a/中文.html
url will encode this: https://xxx.com/a/%E4%B8%AD%E6%96%87.html
fact in apisix:  https://xxx.com/a/\xE4\xB8\xAD\xE6\x96\x87.html

### Steps to Reproduce

raw url: https://xxx.com/a/中文.html
url will encode this: https://xxx.com/a/%E4%B8%AD%E6%96%87.html
fact in apisix:  https://xxx.com/a/\xE4\xB8\xAD\xE6\x96\x87.html

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
```
curl "http://127.0.0.1:9080/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "[example.com](http://example.com/)",
  "uri": "/中文/*",
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "[httpbin.org:80](http://httpbin.org/)": 1
    }
  }
}'

curl -i -X GET "http://127.0.0.1:9080/中文/foo?arg=10" -H "Host: [example.com](http://example.com/)
curl -i -X GET "http://127.0.0.1:9080/%E4%B8%AD%E6%96%87/foo?arg=10" -H "Host: [example.com](http://example.com/)"
```
I test with the above test case, and both successfully match the route.
Could you tell me how i reproduce the problem?

**Comment by monkeyDluffy6017** [comment]
https://github.com/apache/apisix/pull/7401

**Comment by monkeyDluffy6017** [comment]
request APISIX
```
curl -i -X GET "http://127.0.0.1:9080/%25E4%25B8%25AD%25E6%2596%2587/foo?arg=10"
HTTP/1.1 200 OK
Content-Type: application/octet-stream
Transfer-Encoding: chunked
Connection: keep-alive
Date: Fri, 09 Sep 2022 08:37:46 GMT
Server: APISIX/2.15.0   
```
upstream nginx log:
```
==> logs/access.log <==
127.0.0.1 - - [09/Sep/2022:16:37:46 +0800] "GET /%25E4%25B8%25AD%25E6%2596%2587/foo?arg=10 HTTP/1.1" 200 35 "-" "curl/7.58.0"
```

APISIX will not change your URL,  it just forward your URL if you don't use any plugin.

So where is the problem?

Many web server, like nginx, it will decode the url-encoded URL before match the route.

So I guess you could encoded your URL twice like the example above.

**Comment by shreemaan-abhishek** [comment]
@biubiue any updates? If not, please close this issue. Thanks.
