### ISSUE TITLE
The internal authentication plug-in of the gateway wants to provide the interface call of the registry  。help request: 

### ISSUE THREAD

**Issue by dengfenghong** [apache/apisix#7846]
### Description

The internal authentication plug-in of the gateway wants to provide the interface call of the registry（网关内部鉴权插件，想提供注册中心实现接口调用）

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
same as: #7845

You can describe it clearly in #7845. No one can understand the meaning of what you are trying to say right now.

**Comment by dengfenghong** [comment]
重写JWT插件后，JWT的token生成、检查用的是自写的接口，如果要从插件中调用这个自写的接口，需要把接口配置到路由列表中，但是这样会导致自写的接口暴露给外网。我们想采用JWT插件消费nacos、zookeeper等注册中心提供的接口。但是目前没有发现插件对接注册中心调用服务的案例

**Comment by dengfenghong** [comment]
> 

重写JWT插件后，JWT的token生成、检查用的是自写的接口，如果要从插件中调用这个自写的接口，需要把接口配置到路由列表中，但是这样会导致自写的接口暴露给外网。我们想采用JWT插件消费nacos、zookeeper等注册中心提供的接口。但是目前没有发现插件对接注册中心调用服务的案例
