### ISSUE TITLE
docs: add more detail to `file-logger` to distinguish `access.log` 

### ISSUE THREAD

**Issue by guoqqqi** [apache/apisix#7847]
### Current State

There will be many users who are unaware of the circumstances in which they can use the file logger and sometimes feel that it does the same thing as `access.log`. We should add a more detailed description for `file-logger`.

### Desired State

Add some introductions to file-logger:

---

Role of file-logger and usage scenarios (differentiating access.log).

1. `file-logger` can count request and response data for individual routes locally, which is useful for debugging.
2. `file-logger` can get APISIX variables that access.log can't.
3. `file-logger` is hot-loaded, so we can change its configuration at any time with immediate effect.
4. `file-logger` saves every data in JSON format.
5. The user can modify the functions executed by the `file-logger` during the log phase to collect the information they want to collect.

**Comment by hf400159** [comment]
please assign me.
