### ISSUE TITLE
wasm share data

### ISSUE THREAD

**Issue by karboom** [apache/apisix#7849]
### Description

I want write a cache plugin with go&wasm，can each `httpContext` share variable in `pluginContext` ?

### Environment

APISIX version (2.15.0):
Operating system (docker):
OpenResty / Nginx version (openresty/1.21.4.1):

**Comment by spacewander** [comment]
Yes. See the "parent" in https://github.com/apache/apisix/blob/47187faccd96d02773fb1c71980c8ca0ea838d6a/t/wasm/response-rewrite/main.go#L79
