### ISSUE TITLE
feat: plugins need to call the registry center

### ISSUE THREAD

**Issue by dengfenghong** [apache/apisix#7851]
### Description

重写JWT插件后，JWT的token生成、检查用的是自写的接口，如果要从插件中调用这个自写的接口，需要把接口配置到路由列表中，但是这样会导致自写的接口暴露给外网。我们想采用JWT插件消费nacos、zookeeper等注册中心提供的接口。但是目前没有发现插件对接注册中心调用服务的案例

**Comment by tokers** [comment]
> 但是这样会导致自写的接口暴露给外网

@dengfenghong What about adding some security plugins when you public the API? e.g. ip-restriction, authentication plugins.

**Comment by dengfenghong** [comment]
> > 但是这样会导致自写的接口暴露给外网
> 
> @dengfenghong What about adding some security plugins when you public the API? e.g. ip-restriction, authentication plugins.
yes，we used ip-restriction, authentication plugins。but, the requst-real-ip can to modify in internet。plugins used registry center for decoupling and the inter api shoul'd show to internet

**Comment by tokers** [comment]
Try to use the Real IP Replacement in real-ip plugin?
