### ISSUE TITLE
Feature: Support full test in MacOS by using Azure Pipeline

### ISSUE THREAD

**Issue by Zheaoli** [apache/apisix#786]
In the Travis, MacOS can't support some test circumstances such as some special dependency. 

Maybe the APISIX can add some CI platform such as Azure Pipelines to support full test in MacOS

Here's an example: https://dev.azure.com/Python/cpython/_build/results?buildId=53399

**Comment by membphis** [comment]
Is it free for open source projects?

**Comment by Zheaoli** [comment]
@membphis yes it's free for non-commercial usage.

I can take care of this issue.

**Comment by membphis** [comment]
you can make a try ^_^

**Comment by moonming** [comment]
we using GtiHub Actions for MacOS CI
