### ISSUE TITLE
help request: 404 page not found

### ISSUE THREAD

**Issue by caiquanyue** [apache/apisix#7870]
### Description

404 page not found
docker-compost 安装 的2.15版本，apisix_conf/config.yaml 里配置eureka后，用 curl http://127.0.0.1:9090/v1/discovery/eureka/dump 检查，提示404
discovery:
  eureka:
    host:
      - "http://192.168.1.132:8761"
    prefix: "/eureka/"

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
Can you check the control API port?
