### ISSUE TITLE
help request: apisix start -c doesnt work

### ISSUE THREAD

**Issue by ynsdl** [apache/apisix#7875]
### Description

I am trying to start apisix with conf file but it returns no such file or directory even if file exists

```
[n@01 apisix-2.15.0]$ bin/apisix start -c conf/config.yaml
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start -c conf/config.yaml
failed to link customized config, error: No such file or directory
```

```
[n@01 apisix-2.15.0]$ bin/apisix start -c /home/n/apisix-2.15.0/conf/config.yaml
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start -c /home/n/apisix-2.15.0/conf/config.yaml
failed to link customized config, error: No such file or directory
```

conf/config.yaml file exist

```
[n@01 apisix-2.15.0]$ cd conf/
[n@01 conf]$ pwd
/home/n/apisix-2.15.0/conf
[n@01 conf]$ ll
-rw-rw-r--. 1    36 Sep  7 07:02 apisix.uid
-rw-r--r--. 1    906 Jul 24 12:30 apisix.yaml
drwxr-xr-x. 2    62 Jul 24 12:30 cert
-rw-r--r--. 1  30081 Jul 24 12:30 config-default.yaml
-rw-r--r--. 1   2044 Sep  7 07:14 config.yaml
-rw-r--r--. 1   1535 Jul 24 12:30 debug.yaml
-rw-r--r--. 1   5290 Jul 24 12:30 mime.types
-rw-rw-r--. 1  11863 Sep  7 07:31 nginx.conf
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
pls change your custom config file name to some another names, not `config.yaml`.

if using a custom config yaml file,  APISIX would create a hard link to your custom config yaml file as `config.yaml` .

**Comment by ynsdl** [comment]
I got it. Thanks you.
