### ISSUE TITLE
Luarocks install: we can not direct users to use unreleased source code.

### ISSUE THREAD

**Issue by membphis** [apache/apisix#788]
> Justin: This is not allowed as you are directing users to unreleased source code, they can only be directed to released versions of APISIX that have been voted on my the projects PPMC.

**Comment by membphis** [comment]
the line of source code: https://github.com/apache/incubator-apisix/blob/master/Makefile#L124

**Comment by spacewander** [comment]
Solved?

**Comment by membphis** [comment]
thx your remind
