### ISSUE TITLE
docs: where can I know the default log format for each logger

### ISSUE THREAD

**Issue by tokers** [apache/apisix#7883]
### Current State

I don't know the default log format for each logger (except the Kafka logger) in APISIX website.

### Desired State

I hope the default log format can be written in the document.

**Comment by monkeyDluffy6017** [comment]
Maybe i can provide a doc about the log format, how many logger does apisxi have?

**Comment by hf400159** [comment]
> Maybe i can provide a doc about the log format, how many logger does apisix have?
There are currently 16 loggers in APISIX. please refer 
https://apisix.apache.org/docs/apisix/plugins/http-logger/
