### ISSUE TITLE
feat: Allows the payload in the jwt token to be added to the upstream request body

### ISSUE THREAD

**Issue by foliet** [apache/apisix#7885]
### Description

Why can the jwt token only carry the payload when it is generated, but cannot put the payload in the request body to the upstream service when it is parsed?
If I want to pass the jwt token to the upstream service for parsing, what is the meaning of this plugin?
I hope that the key that will be added to the request body in the jwt payload can be set in the jwt plugin configuration of the router.

**Comment by foliet** [comment]
I hope the authentication can be stateless without having to store another user information in etcd

**Comment by tzssangglass** [comment]
> but cannot put the payload in the request body to the upstream service when it is parsed?

 jwt-auth just validates jwt and doesn't require modifying the request body. Or this will break the original request and is not standard behavior.

> If I want to pass the jwt token to the upstream service for parsing, what is the meaning of this plugin?

jwt would pass to upstream. I suggest you read the documentation first: https://apisix.apache.org/docs/apisix/plugins/jwt-auth/

> I hope that the key that will be added to the request body in the jwt payload can be set in the jwt plugin configuration of the router.

From a personal point of view, I don't like this feature, it goes beyond the boundaries of authentication.
