### ISSUE TITLE
help request: should we move the reload api from Admin API to Control API

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#7886]
### Description

 Currently, we have an API that reloads the plugin in the Admin API: https://apisix.apache.org/docs/apisix/terminology/plugin/#hot-reload. After years of usage, we find this design has some issues:
1. its logic is complex
2. it requires every node has the same plugin and static configuration.
3. its usage is limited

As the reload API is mainly used for dev or debug purposes, moving this API into the control API would be more appreciated. What about your ideas?

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Agree +1 from me.

It's my understanding that plugin reload is a "foreign" operation in Admin API. It doesn't like other operations which focus on specific objects. The plugin reload is an ops operation and should only be executed by the ops developer.

**Comment by tzssangglass** [comment]
agree +1 for me

**Comment by hf400159** [comment]
agree +1
