### ISSUE TITLE
feat: kafka-logger not supports ssl

### ISSUE THREAD

**Issue by MagicalBomb** [apache/apisix#7888]
### Description

I found there is no place to configure kafka-support use ssl.

In addition, the log kafka-logger output is not very clear, when connect to kafka using ssl:
here are logs kafka-logger prints
```
2022/09/09 09:05:23 [error] 56#56: *23270 [lua] client.lua:150: _fetch_metadata(): all brokers failed in fetch topic metadata, context: ngx.timer, client: 10.42.1.14, server: 0.0.0.0:80
2022/09/09 09:05:23 [error] 56#56: *23270 [lua] client.lua:150: _fetch_metadata(): all brokers failed in fetch topic metadata, context: ngx.timer, client: 10.42.1.14, server: 0.0.0.0:80
2022/09/09 09:05:23 [error] 56#56: *23270 [lua] producer.lua:272: buffered messages send to kafka err: not found topic, retryable: true, topic: dataapi.apisix.log, partition_id: -1, length: 1, context: ngx.timer, client: 10.42.1.14, server: 0.0.0.0:80
```
It's hard to determine what happens

So please make kafka-logger supports ssl and make log more clearer

**Comment by tokers** [comment]
PR's welcome to support the SSL feature!

**Comment by Hazel6869** [comment]
@MagicalBomb  Hi,  kafka-logger does not support ssl currently , we can optimize it

**Comment by hf400159** [comment]
Welcome to submit PR.

**Comment by tzssangglass** [comment]
> I commit one PR, contains this, but test case is not pass….

pls point the PR to resolve this issue

**Comment by Hazel6869** [comment]
> I commit one PR, contains this, but test case is not pass….

is this pr https://github.com/apache/apisix/pull/7782/files ?

**Comment by spacewander** [comment]
Done
