### ISSUE TITLE
bug: writev() failed (32: Broken pipe)  while sending request to upstream

### ISSUE THREAD

**Issue by mhh12121** [apache/apisix#7892]
### Current Behavior

I tried to upload files to backend service through apisix;
But during the uploading step, I met 
```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
```
responsed from apisix;

### Expected Behavior

This 502 error disappears forever!

### Error Logs

only one error among the whole uploadings;

```
2022/09/08 10:29:07 [error] 58#58: *73334436 writev() failed (32: Broken pipe) while sending request to upstream, client: 10.23.4.251, server: _, request: "POST /storage/v2/upload_file HTTP/1.1", upstream: "http://100.81.255.198:8000/storage/v2/upload_file", host: "10.23.4.251:31684"
```

### Steps to Reproduce

1. It sometimes occurs 
2. I'm uploading large files ( single one >1GB) and small files (around 1MB) simultaneously

### Environment

- k8s: v1.20.15
- APISIX version (run `apisix version`):  v2.13.1-alpine
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): I don't know
- APISIX Ingress controller: 1.4.1

**Comment by mhh12121** [comment]
The errors show ` writev() failed (32: Broken pipe) while sending request to upstream`.
Then I tried to increase the upstream service's keepalived timeout > 60s (apisix default 60s keepalived)
and everything goes well now;

**Comment by hf400159** [comment]
https://apisix.apache.org/docs/apisix/plugins/client-control/

**Comment by tzssangglass** [comment]
Considered as solved, feel free to reopen this if you need.
