### ISSUE TITLE
new plugin: data-validator

### ISSUE THREAD

**Issue by membphis** [apache/apisix#790]
Apache APISIX currently has a very high-performance jsonschema implementation that can be used to validate request parameters or request bodies.

When the verification succeeds or fails, the response specifies the response code to the requesting client.

Here is a mini case:

```lua
data_valitator = {
    var = "args_name",
    schema = {
        type = "string",
        minLength = 1,
        maxLength = 32,
        pattern = [[^[\w]+$]]
    },
    fail_code = 400,
}

data_valitator = {
    var = "args_name",
    schema = {
        type = "string",
        minLength = 1,
        maxLength = 32,
        pattern = [[^[\w]+$]]
    },
    succ_code = 200
}
```

**Comment by moonming** [comment]
Is it support json schema v4 or v5?

**Comment by moonming** [comment]
```
    succ_code = 200
```
I think we don't need `succ_code`

**Comment by membphis** [comment]
> Is it support json schema v4 or v5?

support draft4, draft6 and draft7.

**Comment by membphis** [comment]
related PR: https://github.com/apache/incubator-apisix/pull/1709
