### ISSUE TITLE
bug: opentelemetry sampler=alwaysOff with no traceId to logger

### ISSUE THREAD

**Issue by xuminwlt** [apache/apisix#7903]
### Current Behavior

sample on, the plugin is create a traceId or get parent traceid.
when sampler is off, the plugin skip and no traceId is create or transparent receive.

"log_format": { "host": "$host", "client_ip": "$remote_addr", "uri": "$uri", "request_time": "$request_time", "router_name": "$route_name", "status": "$status", "did": "$http_did", "trace_id": "$http_trace_id", "@timestamp": "$time_iso8601", "time_num": "$msec", "uid": "$http_uid" }

issue:
the same question to zipkin is fixed:https://github.com/apache/apisix/issues/7795

and the issue is here.
https://github.com/apache/apisix/issues/7485

### Expected Behavior

sample off, traceId is need.

### Steps to Reproduce

1. Open the plugin opentelemetry
2. set sample = alywaysOff
3. no traceId in htt_trace_id

### Environment

- APISIX version (run `apisix version`): 1.4.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
>Steps to Reproduce
Open the plugin opentelemetry
set sample = alywaysOff
no traceId in htt_trace_id


`htt_trace_id` should be `http_trace_id？

**Comment by tzssangglass** [comment]
> * Open the plugin opentelemetry
> * set sample = alywaysOff
> * no traceId in htt_trace_id

Please describe in more detail, including configuration and steps, and what to expect. For maintainers who are not familiar with this issue, it will take some time to understand the context.

**Comment by xuminwlt** [comment]
we get the result now, close it.
no trace_id in header, we need to custom it.
trace with no sampler create a new spanId.
