### ISSUE TITLE
request help: kafka-logger customizes log_format, the combination of multiple variables cannot be displayed

### ISSUE THREAD

**Issue by wushiwei008** [apache/apisix#7904]
### Current Behavior

    "log_format": {
     "url": "$scheme://$http_host$request_uri"， 
    "scheme": "$scheme",
    "http_host": "$http_host",
    "uri": "$request_uri", 
    "httpversion": "$server_protocol", 
    "upstream_response_time": "$upstream_response_time"
    }

如上自定义日志格式，“url”这行，多个变量组合的情况下，无法显示日志。

### Steps to Reproduce

apisix2.13

### Environment

apisix2.13

**Comment by tokers** [comment]
So what's the result?

**Comment by tokers** [comment]
What's the definition of "无法显示日志"?

**Comment by hf400159** [comment]
What format do you expect the log to be in? What format is it in now?

**Comment by tzssangglass** [comment]
> "url": "$scheme://$http_host$request_uri"，

I don't remember `log_format` supporting multiple variable combinations, where did you see that?

**Comment by shreemaan-abhishek** [comment]
@wushiwei008 do you have any further questions?
