### ISSUE TITLE
help request: config.yaml configuration not work

### ISSUE THREAD

**Issue by yuqiquan** [apache/apisix#7905]
### Description

我原先使用的是2.13.2版本 升到2.15.0 后在config.yaml中配置，apisix的部分没有效果，必须在config-default.yaml中进行配置

比如
![image](https://user-images.githubusercontent.com/44921350/189854936-ec925716-2a84-462d-979b-d3c776677ac6.png)

启动后发现压根无效
![image](https://user-images.githubusercontent.com/44921350/189855260-b0e87ab1-8e90-4def-8263-7cb6b5230b95.png)

在报错的路径中压根找不到/home/apisix/plugins/ 目录

而且我配置了control
![image](https://user-images.githubusercontent.com/44921350/189855569-b5648865-bbe0-4f3e-9f06-98d4abd66904.png)

在lua中使用
![image](https://user-images.githubusercontent.com/44921350/189855766-7cd6218c-1211-450d-8670-231c6719bc4b.png)

它报错为nil
![image](https://user-images.githubusercontent.com/44921350/189855985-db0abeb5-e21f-4721-85a6-2158ca6cfce1.png)

由此可见我的config.yaml文件中有关apisix的配置失效了  但是我的另一台升完级后 这样配置是正常的

为什么！！！

### Environment

- APISIX version (2.15.0):

**Comment by tzssangglass** [comment]
> 由此可见我的config.yaml文件中有关apisix的配置失效了 但是我的另一台升完级后 这样配置是正常的

You can look for the differences between the two server configurations. If I understand correctly, since it is normal for the other server to do the same operation, the problem may be the difference between the two.

**Comment by yuqiquan** [comment]
我自定义了一个info-report插件，文件放在/tmp/apisix/plugins/目录下
![image](https://user-images.githubusercontent.com/44921350/189892686-0f6da7b8-7b96-49f6-93a1-8fa547ba72c0.png)
 对config.yaml进行配置
![image](https://user-images.githubusercontent.com/44921350/189892826-c1522b01-fe46-4656-9c50-1bdb724008e9.png)

启动出现错误
![image](https://user-images.githubusercontent.com/44921350/189892909-351e15bb-ea24-41e3-985f-7c14352d02f4.png)


但是如果配置到config-default文件中就成功启动，不知道为什么

**Comment by tzssangglass** [comment]
try with

```yaml
apisix:
    extra_lua_path: "/tmp/apisix/plugins/?.lua"
```

in `config.yaml`

You can locate the problem by searching the path.

**Comment by shreemaan-abhishek** [comment]
@yuqiquan any updates?
