### ISSUE TITLE
How to get the response of the upstream and send it to an external service for transformation

### ISSUE THREAD

**Issue by vaibhavsw** [apache/apisix#7916]
### Description

How do I capture the response body, headers, and status codes from the response of Upstream, send it to an external service for transformation and processing, and then send the response back from the transformation service to the client?

In this direct response of the upstream is not sent to the client, rather the response from the upstream is modified by an external service, and then the response of modification is then sent to the client

### Environment

- APISIX version (run apisix version): 2.15
- Operating system (run uname -a): MacOS
- OpenResty / Nginx version (run openresty -V or nginx -V): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info): 3.4.15
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run luarocks --version): 3.8.0

**Comment by vaibhavsw** [comment]
@soulbird I didn't get what I do right now to get it working. Any workaround you think can give this flow?

**Comment by vaibhavsw** [comment]
@tzssangglass There are no examples as this a custom requirement where we do not want to expose the JSON sent from the client, rather modify them depending on some rules and then send that as a response.

**Comment by tzssangglass** [comment]
> There are no examples as this a custom requirement where we do not want to expose the JSON sent from the client, rather modify them depending on some rules and then send that as a response.

And why let transformation service return response to the client directly? When this request is proxied from the client to the upstream by APISIX, the response will also be proxied form upstream to client by APISIX.
