### ISSUE TITLE
bug: P99 latency is too high

### ISSUE THREAD

**Issue by ryan4yin** [apache/apisix#7919]
### Current Behavior

APISIX's P99 latency is too high, while the upstream latency is very low.

![apisix-p99-too-high](https://user-images.githubusercontent.com/22363274/190134825-be2e83ae-9a43-4727-b2ba-13732f056dc2.jpg)

related issues:
- <https://github.com/apache/apisix/issues/5604>

### Expected Behavior

APISIX's P99 latency should not be so high.

### Error Logs

the cpu flame graph I captured using `openresty-xray` shows the `exporter`/`prometheus` plugin consumed too much times in the request lifetime:

![job-4400902444-Lua-Land-CPU-Flame-Graph](https://user-images.githubusercontent.com/22363274/190141228-cb21e627-a4b7-424d-a56e-0b789de5a651.svg)

### Steps to Reproduce

first, create an upstream using the following config:

```json
{
    "id": "xxx-extractor",
    "desc": "xxx-extractor",
    "scheme": "http",
    "type":"roundrobin",
    "nodes": [
        { "host": "172.22.33.44", "port": 8106, "weight": 0, "priority": 0},
        { "host": "172.22.33.45", "port": 8106, "weight": 0, "priority": 0},
        { "host": "172.22.33.46", "port": 8106, "weight": 0, "priority": 0},
        { "host": "172.22.33.47", "port": 8106, "weight": 0, "priority": 0},
        { "host": "172.22.33.48", "port": 8106, "weight": 0, "priority": 0}
    ],
    "retries": 0,
    "timeout": {
        "connect":15,
        "send":15,
        "read":15
    },
    "checks": {
        "active": {
            "timeout": 3,
            "http_path": "/",
            "host": "xxx.xxx",
            "healthy": {
                "interval": 3,
                "successes": 3
            },
            "unhealthy": {
                "interval": 3,
                "http_failures": 3
            },
            "req_headers": ["User-Agent: curl/7.29.0"]
        },
        "passive": {
            "healthy": {
                "http_statuses": [200, 201],
                "successes": 3
            },
            "unhealthy": {
                "http_statuses": [500, 502, 503, 504],
                "http_failures": 3,
                "tcp_failures": 3
            }
        }
    }
}
```

then create a route with the following config:

```yaml
{
  "id": "xxx-ingress",
  "uri": "/*",
  "hosts": [
    "xxx.xxx"
  ],
  "methods": [
    "PUT",
    "GET",
    "POST",
    "HEAD"
  ],
  "plugins": {
    "prometheus": {},
    "proxy-mirror": {
      "host": "http://my-app.test.com"
    }
  },
  "upstream_id": "xxx-extractor"
}
```

and then given about 30 QPS to the APISIX instance, high P99 latency problem will occurs.

### Environment

running in Kubernetes, using helm chart `apisix/apisix` with version `0.11.0`.

- APISIX version (run `apisix version`): `docker.io/apache/apisix:2.15.0-alpine`
- Operating system (run `uname -a`): `Linux apisix-edge-765f88c49f-8tslz 5.4.190-107.353.amzn2.x86_64 #1 SMP Wed Apr 27 21:16:35 UTC 2022 x86_64 Linux`
- etcd version: `docker.io/bitnami/etcd:3.5.4-debian-11-r22`
- grafana dashbaord I use: <https://grafana.com/grafana/dashboards/11719-apache-apisix/>

**Comment by tokers** [comment]
@tzssangglass If I remember correctly, you submitted a PR to the api7-prometheus lib and try to optimize the performance?

**Comment by tzssangglass** [comment]
1. The sample is so small that you can reproduce the sample.
2. Is there a prometheus exporter that visits http://127.0.0.1:9091/apisix/prometheus/metrics to get the metrics when the flame chart is sampled?
3. From the latency monitoring, APISIX causes high latency, you can remove the `proxy-mirror` plugin and keep only `prometheus` plugin, and test again?

**Comment by ryan4yin** [comment]
> 1. The sample is so small that you can reproduce the sample.
> 2. Is there a prometheus exporter that visits http://127.0.0.1:9091/apisix/prometheus/metrics to get the metrics when the flame chart is sampled?
> 3. From the latency monitoring, APISIX causes high latency, you can remove the `proxy-mirror` plugin and keep only `prometheus` plugin, and test again?

1. I'm trying to reproduce this in a test environment
2. I tried several times to sample a cpu flame chart, I post some of them below.
3. I disabled the `proxy-mirror` plugin, but it's helpless, the P99 latency is still high.

the flame chart smapled 16mins ago, all the cpu flame chart seems the same:

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/22363274/190312062-959f5803-fad7-4a67-9425-51c8394ad381.png">

but the lua exectution flame chart shows some new info:

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/22363274/190312183-5aac1efe-bbc1-48c9-9277-d2de631fda87.png">

**Comment by tzssangglass** [comment]
> 3\. I disabled the `proxy-mirror` plugin, but it's helpless, the P99 latency is still high.

Can you show the grafana monitoring after removing the `proxy-mirror` plugin? I am interested in the average latency of about 5s. This is not normal.

Are there some error logs? It looks like you captured the exception stack.

The phenomena and conclusions about `prometheus` plugins causing P99 long-tail requests are known. ref: #5755
Note: This phenomenon usually occurs when the number of indicators exceeds 10,000.
Based on previous experience, the latency of long-tail requests is nearly a hundred times higher than the average latency(with an average delay of a few tens of milliseconds and a few seconds for long-tail requests.). 
But your garfana monitoring shows: long-tail requests are about four times more likely to be delayed than the average. This makes me feel strange(with an average latency of 5 seconds and 20 seconds for long-tail requests).

As a comparison test, you can remove the proimetheus plugin and test again to see if the average 5s latency and the P99 latency appear.

**Comment by ryan4yin** [comment]
after removing the `proxy-mirror` plugin:
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/22363274/190321213-45ad8480-6160-4366-a157-3b519c3fd06d.png">

**Comment by ryan4yin** [comment]
even though I disable all the plugins, the latency is still high...
<img width="710" alt="image" src="https://user-images.githubusercontent.com/22363274/190323283-4123eb3a-c3f0-4496-a047-f1e18b1c3acd.png">

**Comment by ryan4yin** [comment]
and I noticed(before I disable the prometheus plugin), there are many requests with 408 and 499 status code with QPS up to about 0.5:

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/22363274/190323545-e12e1c47-60d1-4977-bd32-fb639438e70a.png">

**Comment by ryan4yin** [comment]
> but the lua exectution flame chart shows some new info:
> 
> <img alt="image" width="1496" src="https://user-images.githubusercontent.com/22363274/190312183-5aac1efe-bbc1-48c9-9277-d2de631fda87.png">

is this flame chart shows some problem? the openresty-xray captured some Lua Error Message: 

>bad argument #1 to '?' (string expected, got nil)

**Comment by ryan4yin** [comment]
the phenomena is so weird, really confusing...

the latest statistics generated by  openresty-xray:

<img width="897" alt="image" src="https://user-images.githubusercontent.com/22363274/190324954-9ab6277a-9984-49ec-8c44-9ea46aec524d.png">
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/22363274/190325064-eeaef43d-7052-4783-bf9a-876424192c62.png">

**Comment by ryan4yin** [comment]
@tzssangglass does the APISIX latency contains the whole request lifetime? it it possible that the client's network are too bad, which caused high P99 latency?

my network architecture: 

```
[android client at Brazil] => [AWS Network LoadBalancer] => [APISIX Gateway Container running in AWS EKS] => [Upstream Server]
```

**Comment by tzssangglass** [comment]
> even though I disable all the plugins, the latency is still high...

This means that the latency is not related to the prometheus plugin, but to APISIX and upstream.
What is your upstream? You can have the request go from client to upstream without going through the APISIX proxy and see the latency distribution.

**Comment by tzssangglass** [comment]
> does the APISIX latency contains the whole request lifetime?

APISIX latency = whole request latency - upstream latency, indicates the time APISIX took to process the request.

**Comment by ryan4yin** [comment]
> This means that the latency is not related to the prometheus plugin, but to APISIX and upstream.

thanks for reply, but the upstream latency record by the prometheus plugin & openresty is very slow, should this indicates that the upstream server works fine?

the upstream server is sevaral sensorsdata's data-extractor server running in the same AWS VPC as APISIX, I'll do a local test to see the latency distribution of those upstream servers.

**Comment by ryan4yin** [comment]
> And based on these logs, I think the possible reasons are:
> 
>     1. The network between client and APISIX is poor, APISIX cannot read the client's headers or bodies properly;
> 
>     2. The client request body is very large and the APISIX read timeout(based on the analysis of available information, this is closer to the truth);
> 
> 
> Can you trace the high latency associated with the large client request body?

thanks very much! now the problem is clear, it's not a problem of APISIX Gateway.

I'll talk with our android team about this problem, and close this issue later.
