### ISSUE TITLE
help request: openid-connect didnt redirect to the auth page

### ISSUE THREAD

**Issue by akalittle** [apache/apisix#7929]
### Description

I want to use the openid-connect plugin to integrate the etcdkeeper webpage with google account auth.
When I set the plugin like below, it still leads to the etcdkeeper page. 
How could I  change the config to make it possible to redirect to the google auth page and redirect back to my service.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/38489160/190582720-35e2f67d-bb76-41b3-bfb7-66d718f3b46a.png">

### Environment

Environment
apache/apisix:2.15.0-alpine
apache/apisix-ingress-controller:1.4.1
quay.io/coreos/etcd:v3.5.4
docker.io/bitnami/etcd:3.5.4-debian-11-r14

Kubernetes cluster version:
Client Version: v1.24.0
Kustomize Version: v4.5.4
Server Version: v1.21.12-gke.2200

**Comment by akalittle** [comment]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/38489160/190581958-5146d2b3-b114-4c4c-aa45-6014af1cc524.png">

The application home link is `api.xxx.xx` which is apisix domain

<img width="449" alt="image" src="https://user-images.githubusercontent.com/38489160/190582063-cafb927e-ac5b-44c2-81e8-d647a5dc60d6.png">

and the redirect url is `apisixdomain/google/callback`

**Comment by tokers** [comment]
> When I set the plugin like below, it still leads to the etcdkeeper page.

What is etcdkeeper page? What's the relationship between it and the route?

By the way, your route cannot capture other API requests except which URI is `/` exactly. The route should use prefix match and the OIDC redirect uri should also be matched this route.

**Comment by akalittle** [comment]
<img width="487" alt="image" src="https://user-images.githubusercontent.com/38489160/190604033-b30fb3f7-c527-4446-b158-37de4adb2596.png">
It's just the service of etcdkeeper. You can just ignore that.
And the `/` path is ok to visit.

So should I set the redirect URI  in google OAuth setting to  ${domain} ,  not ${domain}/google/callback ?

**Comment by akalittle** [comment]
Sorry for the issue.
I just commented out the `openid-connect` plugin in the config file.
It's my fault.
