### ISSUE TITLE
bug: apisix sls-logger不能正常向阿里云sls传输数据

### ISSUE THREAD

**Issue by jiahui1988** [apache/apisix#7950]
### Current Behavior

bug: apisix sls-logger不能正常向阿里云sls传输数据（apisix没报错，阿里云sls在指定的时间内没收到数据），已经测试过

### Expected Behavior

阿里云侧排查发现是，签名不匹配

### Steps to Reproduce

1： 使用的是docker 版本安装的apisix
2： 版本是：15最新版本

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
pls provider 

1. configuration information
2. reproduction steps
3. error log

**Comment by Raymond0331** [comment]
First of all your ACK/ASK cluster have to set sls.
Second, add an ENV to your deployment, like the below:
           - name: aliyun_logs_your_project_app_name
              value: stdout
After that, pls trigger access , about 15 minutes later go to sls your will found a logstore which one  is named by your env

**Comment by tzssangglass** [comment]
Unfortunately, I don't have an Ali cloud cluster. Can you provide some key information, logs, packet capture data, etc., so that I can analyze it.

**Comment by jiahui1988** [comment]
本地已经修复。
