### ISSUE TITLE
help request: if i wan't support multi cluster of k8s'discovery,what can i do?

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#7951]
### Description

if i wan't support multi cluster of k8s'discovery,what can i do? Does the community have some ideas for implementation? I don't see any plans to support the v3 version ?

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
fixed by: https://github.com/apache/apisix/pull/7895

it would released in next version.

**Comment by wolgod** [comment]
thanks
