### ISSUE TITLE
feat: trace in  ext-plugin-pre-req can't connect to zipkin's (built-in plugin) trace

### ISSUE THREAD

**Issue by wzbwzt** [apache/apisix#7953]
### Description

Apisix中配置plugin runner,并将执行插件安装在ext-plugin-pre-req，当在runner 插件中添加trace时，无法关联apisix的内置zipkin 插件，根据其执行阶段和执行权重，建议将zipkin.lua中的access阶段的send headers to upstream 放入到rewrite阶段中；

function _M.rewrite(plugin_conf, ctx)
		....
		local request_span = ctx.opentracing.request_span
		    if conf.span_version == ZIPKIN_SPAN_VER_1 then
		        ctx.opentracing.rewrite_span = request_span:start_child_span("apisix.rewrite",
		            start_timestamp)
		
		        ctx.REWRITE_END_TIME = tracer:time()
		        ctx.opentracing.rewrite_span:finish(ctx.REWRITE_END_TIME)
		    else
		        ctx.opentracing.proxy_span = request_span:start_child_span("apisix.proxy",
		            start_timestamp)
		
		        -- send headers to upstream
		        local outgoing_headers = {}
		        tracer:inject(ctx.opentracing.proxy_span, "http_headers", outgoing_headers)
		        for k, v in pairs(outgoing_headers) do
		            core.request.set_header(ctx, k, v)
		        end
		    end
		end

**Comment by tzssangglass** [comment]
> Apisix中配置plugin runner,并将执行插件安装在ext-plugin-pre-req，当在runner 插件中添加trace时

I don't understand what these steps are, can you expand on them?

**Comment by spacewander** [comment]
What about switching to ext-plugin-post-req, as the header injection is done after ext-plugin-pre-req?

**Comment by wzbwzt** [comment]
> What about switching to ext-plugin-post-req, as the header injection is done after ext-plugin-pre-req?

yes, however we want plugin runner executed before most of the APISIX built-in plugins, ext-plugin-pre-req execute in access phase and has a very low priority.  if we change zipkin header injection from access phase to rewrite phase,will there be any other impact? has a litter worry about 😟

**Comment by spacewander** [comment]
You can use both, see https://github.com/apache/apisix/blob/efd5d1ec21cd1a756eaba345fe2357e54a2b721a/t/plugin/ext-plugin/sanity.t#L84.

ext-plugin-pre-req and ext-plugin-post-req can have different configurations.
