### ISSUE TITLE
help request: how to proxy_pass url  such as  "baidu.com" ？

### ISSUE THREAD

**Issue by chenyongzhi001** [apache/apisix#7956]
### Description

 server_name  www.a.com
    location /api/ {
            proxy_pass https://www.b.com/;
        }
how to config that in apisix-dashboard ？
use response-rewrite or proxy-rewrite ?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by chenyongzhi001** [comment]
and how to config upstream ?   just 127.0.0.1: 80 or what ?

**Comment by hf400159** [comment]
> and how to config upstream ? just 127.0.0.1: 80 or what ?

I didn't understand. You can configure upstream to any accessible address. please refer to [getting-start](https://apisix.apache.org/docs/apisix/next/getting-started/#create-a-route).

**Comment by tzssangglass** [comment]
As a reminder, do not use baidu.com as a test upstream, they will have some policies to restrict proxy access.

**Comment by shreemaan-abhishek** [comment]
@chenyongzhi001 you can use proxy-rewrite to achieve this, please reopen the issue if you have more questions.
