### ISSUE TITLE
help request: support ipv6 on the control plane

### ISSUE THREAD

**Issue by stubbornTanzhe** [apache/apisix#7972]
### Description

```
    admin_listen:                 # use a separate port
      ip: 0.0.0.0                 # Specific IP, if not set, the default value is `0.0.0.0`.
      port: 9180                  # Specific port, which must be different from node_listen's port.
```

```
netstat -antup| grep 9180
tcp  0.0.0.0:9180    listen
```

how can i change config to listen ipv6 address for the control plane?

### Environment

- APISIX version (run `apisix version`): 2.13.3
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
you can modify the allow_admin field in conf/config.yaml to specify a list of IPs that are allowed to call the Admin API. 

ref: https://github.com/apache/apisix/blob/release/2.13/conf/config-default.yaml#L74-L76

**Comment by stubbornTanzhe** [comment]
> you can modify the allow_admin field in conf/config.yaml to specify a list of IPs that are allowed to call the Admin API.
> 
> ref: https://github.com/apache/apisix/blob/release/2.13/conf/config-default.yaml#L74-L76

I change that,but seems that it's only listen 127.0.0.1 and tcpv4
```
bash-5.1# curl http://[::1]:9180/apisix/admin/consumers -H "X-API-KEY: 84b625edd1c95f136f87adc8f1f03433"
curl: (7) Failed to connect to ::1 port 9180 after 0 ms: Connection refused
```

**Comment by tzssangglass** [comment]
> I change that,but seems that it's only listen 127.0.0.1 and tcpv4

`127.0.0.1` in ipv6 is `::ffff:7f00:1`, my config:

```
apisix:
  admin_key:
    - name: admin
      key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
      role: admin

allow_admin:
  - ::ffff:7f00:1
```

### test

#### add route

```
curl -X PUT 'http://127.0.0.1:9080/apisix/admin/routes/1' \
    -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
    -d '{
    "uri": "/*",
    "upstream": {
        "nodes": {
            "httpbin.org:80": 1
        },
        "type": "roundrobin"
    }
}'
```

#### hot route

```
curl http://127.0.0.1:9080/get
{
  "args": {},
  "headers": {
    "Accept": "*/*",
    "Host": "127.0.0.1",
    "User-Agent": "curl/7.84.0",
    "X-Amzn-Trace-Id": "xxx",
    "X-Forwarded-Host": "127.0.0.1"
  },
......
}
```

success on APISIX v2.13

**Comment by stubbornTanzhe** [comment]
> allow_admin:
>   - ::ffff:7f00:1

maybe i am not describe it clear~

**Comment by stubbornTanzhe** [comment]
> > I change that,but seems that it's only listen 127.0.0.1 and tcpv4
> 
> `127.0.0.1` in ipv6 is `::ffff:7f00:1`, my config:
> 
> ```
> apisix:
>   admin_key:
>     - name: admin
>       key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
>       role: admin
> 
> allow_admin:
>   - ::ffff:7f00:1
> ```
> 
> ### test
> #### add route
> ```
> curl -X PUT 'http://127.0.0.1:9080/apisix/admin/routes/1' \
>     -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
>     -d '{
>     "uri": "/*",
>     "upstream": {
>         "nodes": {
>             "httpbin.org:80": 1
>         },
>         "type": "roundrobin"
>     }
> }'
> ```
> 
> #### hot route
> ```
> curl http://127.0.0.1:9080/get
> {
>   "args": {},
>   "headers": {
>     "Accept": "*/*",
>     "Host": "127.0.0.1",
>     "User-Agent": "curl/7.84.0",
>     "X-Amzn-Trace-Id": "xxx",
>     "X-Forwarded-Host": "127.0.0.1"
>   },
> ......
> }
> ```
> 
> success on APISIX v2.13

maybe i am not describe it clear~


i mean when in ipv6 env, the apisix pod's ip is ipv6 address, but admin address is ipv4
the admin CURD api is ok when curl to 127.0.0.1, but it seems that it use ipv4 tcp stream in the tcp layer~

**Comment by stubbornTanzhe** [comment]
when i set `enable_ipv6: true` , only effect `resolver xxxx valid=30 ipv6=on;`

**Comment by tzssangglass** [comment]
> i check the version and it seems that the nginx builded without ipv6 module.

yes, you can compile `apisix-base` based on the (script](https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh) yourself by adding `--with-ipv6`.

> so when `ipv6=on`, apisix can get ipv6 address and route by ipv6 or ipv4 address randomly?

if you want to use ipv6 only, after compiling apisix-base with `--with-ipv6`, you can use `ipv6only `, ref: https://ma.ttias.be/enable-ipv6-connectivity-for-nginx/

**Comment by tzssangglass** [comment]
> so when `ipv6=on`, apisix can get ipv6 address and route by ipv6 or ipv4 address randomly?

Do you want to always resolve upstream domains to ipv6 addresses?

**Comment by stubbornTanzhe** [comment]
> if you want to use ipv6 only, after compiling apisix-base with `--with-ipv6`, you can use `ipv6only=on`, ref: https://ma.ttias.be/enable-ipv6-connectivity-for-nginx/

for our case, we wanna test the only ipv6 all stack , include apisix,  for the [issue](http://www.gov.cn/zhengce/2017-11/26/content_5242389.htm)
not just ipv6 address in the upstream, but also connet to etcd with ipv6 layer、change business config with ipv6 layer~
no ipv4 network packets in the k8s cluster~

**Comment by tzssangglass** [comment]
> but also connet to etcd with ipv6 layer

AFAIK, connect to etcd with ipv6 address maybe work fail, ref: https://github.com/apache/apisix/issues/7100, however, you can choose to disable the health check function of etcd.

The others I think are achievable.
