### ISSUE TITLE
help request: whether apisix  can be supported communication between grpc_client and grpc_server?

### ISSUE THREAD

**Issue by gitcome** [apache/apisix#7973]
### Description

my call chain like this:
```
                                                           1.[RequestFilter return] --?--> GrpcClient (report closed the stream without sending trailers)
GrpcClient --grpc--> Apisix ----> Go-plugin-runner(ext-plugin-post-req)  
                                                           2.[RequestFilter continue] ----> GrpcServer(upstream) ----> Apisix ----> GrpcClient(ok)

```

in Go-plugin-runner, func RequestFilter like this:
```
func (p *Say) RequestFilter(conf interface{}, w http.ResponseWriter, r pkgHTTP.Request) {
	w.Header().Set("Content-Type", r.Header().Get("Content-Type"))
	num := rand.Int()
	if num%2 == 1 {
		w.WriteHeader(http.StatusOK)
		w.Header().Set("mykey", "test")
		w.Header().Set("Grpc-Status", "0")
		w.Header().Set("Grpc-Message", "ok")
		w.Header().Set("Grpc-Status-Details-Bin", "")
		return   // here retrun to GrpcClient, above chain 1, client report "server closed the stream without sending trailers"
	}
        return // here continue to upstream GrpcServer, then return to GrpcClient,  above chain 2, ok
}
```

grpc-transcode not suitable for our scene。Please have a look and give me help， thanks a lot!

### Environment

os: win10
apisix: apache/apisix:2.15.0-alpine (use apisix-docker\example\docker-compose.yml docker-compose up)
plugin-runner: apache/apisix-go-plugin-runner v0.4.0

**Comment by tzssangglass** [comment]
Apisix ----> Go-plugin-runner will not use gRPC protocol, so such a call is not possible.

**Comment by gitcome** [comment]
> Apisix ----> Go-plugin-runner will not use gRPC protocol, so such a call is not possible.

Go-plugin-runner will not use gRPC protocol, but GrpcClient use gRPC protocol call, Go-plugin-runner can receive req and enter function RequestFilter。if in RequestFilter set http status ok, GrpcClient can receive, but report.

conclusion: apisix can not support communication between grpc_client and grpc_server?

**Comment by tzssangglass** [comment]
> apisix can not support communication between grpc_client and grpc_server?

APISIX can use the grpc-web plugin to convert requests from the gRPC Web Client to the gRPC server. The call relationship is gRPC Web Client -> APISIX -> gRPC server.

> Go-plugin-runner will not use gRPC protocol, but GrpcClient use gRPC protocol call, Go-plugin-runner can receive req and enter function RequestFilter。if in RequestFilter set http status ok, GrpcClient can receive, but report.

I suggest that you discuss go-plugin-runner separately from the APISIX proxy gRPC.

**Comment by gitcome** [comment]
> > apisix can not support communication between grpc_client and grpc_server?
> 
> APISIX can use the grpc-web plugin to convert requests from the gRPC Web Client to the gRPC server. The call relationship is gRPC Web Client -> APISIX -> gRPC server.
> 
> > Go-plugin-runner will not use gRPC protocol, but GrpcClient use gRPC protocol call, Go-plugin-runner can receive req and enter function RequestFilter。if in RequestFilter set http status ok, GrpcClient can receive, but report.
> 
> I suggest that you discuss go-plugin-runner separately from the APISIX proxy gRPC.

Are there Apisix discussion groups？It's not clear here

**Comment by gitcome** [comment]
> > apisix can not support communication between grpc_client and grpc_server?
> 
> APISIX can use the grpc-web plugin to convert requests from the gRPC Web Client to the gRPC server. The call relationship is gRPC Web Client -> APISIX -> gRPC server.
> 
> > Go-plugin-runner will not use gRPC protocol, but GrpcClient use gRPC protocol call, Go-plugin-runner can receive req and enter function RequestFilter。if in RequestFilter set http status ok, GrpcClient can receive, but report.
> 
> I suggest that you discuss go-plugin-runner separately from the APISIX proxy gRPC.

@tzssangglass  I can't tell which is causing the error. Please take a look and give a help.

**Comment by tzssangglass** [comment]
> 有 APIsix 讨论组吗？这里不清楚

https://github.com/apache/apisix/tree/master/docs/zh/latest#%E7%A4%BE%E5%8C%BA

> @tzssangglass 我不知道是哪个导致了错误。请看一下并提供帮助。

You need to describe your problem clearly so I can help you.

I need:

1. complete reproduction of the steps, including details
2. detailed configuration information

**Comment by gitcome** [comment]
> 

十分抱歉，英文不太好。我重新用中文描述一下，因为线上使用Apisix出了问题急着解决，麻烦帮忙看一下。
调用链是这样的 
```
grpc客户端 <-> Apisix <->  过滤器apisix-go-plugin-runner <-> grpc服务端
```

- 搭建grpc客户端和grpc服务端

1.  grpc协议文件 https://github.com/grpc/grpc/blob/master/examples/protos/route_guide.proto  protoc生成go grpc文件
2.  grpc服务端代码
```
func start(ctx context.Context) {
	lis, err := net.Listen("tcp", fmt.Sprintf(":%d", 8301))
	if err != nil {
		logs.Error("net.Listen error: ", err)
		return
	}
	var options []grpc.ServerOption
	grpcServer := grpc.NewServer(options...)
	defer grpcServer.GracefulStop()
	svr := &TestSvc{}
	routeguide.RegisterRouteGuideServer(grpcServer, svr)
	go grpcServer.Serve(lis)
	<-ctx.Done()
}

type TestSvc struct {
	routeguide.UnimplementedRouteGuideServer
}

func (s *TestSvc) GetFeature(ctx context.Context, req *routeguide.Point) (*routeguide.Feature, error) {
	rsp := &routeguide.Feature{}
	rsp.Name = "tmp"
	rsp.Location = &routeguide.Point{Latitude: 1, Longitude: 2}
	return rsp, nil
}
```
3.  grpc客户端代码
```
func start(ctx context.Context) {
	conn, err := grpc.Dial("192.168.56.19:9080", grpc.WithTransportCredentials(insecure.NewCredentials()))
	if nil != err {
		return
	}
	defer conn.Close()
	client := routeguide.NewRouteGuideClient(conn)
	var header metadata.MD
	var trailer metadata.MD
	req := routeguide.Point{Latitude: 99, Longitude: 88}
	rsp, err := cli.GetFeature(ctx, &req, grpc.Header(&header), grpc.Trailer(&trailer))
	if err != nil {
		logs.Error(err)   // 如果在apisix-go-plugin-runner直接返回，这里报closed the stream without sending trailers
		return
	}
	logs.Info("rsp:", rsp.String())
	logs.Info("header:", header)
	logs.Info("trailer:", trailer)
}
```

- 搭建Apisix

1.  git clone https://github.com/apache/apisix-go-plugin-runner.git
2.  vim apisix-go-plugin-runner-master/cmd/go-runner/plugins/say.go
```
// 修改请求过滤处理函数如下，逻辑很简单，随机一个数
// 是奇数的话，设置http200和一些header后返回，该请求直接返回客户端，客户端收到后报错closed the stream without sending trailers
// 是偶数的话，RequestFilter直接return，该请求会到上游grpc server处理后返回到客户端，处理正常
func (p *Say) RequestFilter(conf interface{}, w http.ResponseWriter, r pkgHTTP.Request) {
	w.Header().Set("Content-Type", r.Header().Get("Content-Type"))
	num:=rand.Int31n(100)
	if num%2 == 1 {
		w.WriteHeader(http.StatusOK)
		w.Header().Set("Grpc-Status", "0")
		w.Header().Set("Grpc-Message", "0")
		w.Header().Set("Grpc-Status-Details-Bin", "")
		w.Header().Set("rspHeader", "value")
		return  // 这里请求返回给客户端 报错  #标记#
	}
        // 这里请求会到上游grpc server 正常
}
```
3.  vim apisix-go-plugin-runner-master/ci/apisix/config.yaml
添加http2监听端口
```
    - port: 9080
      enable_http2: true
```
添加ext-plugin插件
```
ext-plugin:
  cmd: ["/usr/local/apisix/go-runner", "run"]
```
4.  docker build -f Dockerfile -t apisixtest:v1 --progress=plain --no-cache .
5.  docker run -p 9079:9079/tcp -p 9080:9080/tcp -p 9091:9091/tcp -p 9443:9443/tcp -p 9092:9092/tcp -v D:\apisix-go-plugin-runner-master\log:/usr/local/apisix/logs --name=apisixtest1 apisixtest:v1    运行api
6. 打开 http://localhost:9000/routes/list,配置上游服务和路由，并添加ext-plugin-post-req插件
```
// 上游服务
{
  "nodes": [
    {
      "host": "192.168.56.19",
      "port": 8301,
      "weight": 1
    }
  ],
  "type": "roundrobin",
  "scheme": "grpc",
}

// 路由
{
  "uri": "/routeguide.RouteGuide/GetFeature",
  "name": "testa1",
  "methods": [
    "POST"
  ],
  "plugins": {
    "ext-plugin-post-req": {
      "conf": [
        {
          "name": "say",
          "value": "{\"body\":\"123\"}"
        }
      ],
      "disable": false
    }
  },
  "upstream_id": "425744995673178819",
  "status": 1
}
```
7.  使用上面的grpc client调用Apisix，发现如果代码来到上面#标记#处，接口返回报错closed the stream without sending trailers。如果请求过了apisix-go-plugin-runner并来到grpc server，则接口返回正常。


apisix-go-plugin-runner的代码也看了，找不出什么原因。猜想是go-plugin过滤请求返回给apisix后，apisix没有将回包grpc协议封装好就返回给客户端了。上面问题查了一周了，实在找不到解决方法，@tzssangglass @bzp2010 @soulbird 恳请帮忙一下，十分感谢！

**Comment by tzssangglass** [comment]
cc @spacewander

**Comment by spacewander** [comment]
> server closed the stream without sending trailers

AFAIK, OpenResty doesn't have an API to set the trailer. So there is no way to generate gRPC output in APISIX...

**Comment by gitcome** [comment]
> > server closed the stream without sending trailers
> 
> AFAIK, OpenResty doesn't have an API to set the trailer. So there is no way to generate gRPC output in APISIX...

@spacewander but why grpcClient can receive trailer when the request go through ext-plugin-post-req and return by upstream grpcserver?   It's confusing if the output is sometimes grpc and sometimes http.

**Comment by spacewander** [comment]
OpenResty can't modify the trailer but it can pass the trailer. So it works fine util you need to generate a gRPC response without going through the upstream.

**Comment by jujiale** [comment]
@spacewander 
Hello， I want to know if OpenResty have API for send grpc request. because we need to develop a plugin. the plugin offered a route which proxy http1.1 requset and its upstream also http service. but we need invoke other grpc service in the plugin to judge if the request have auth to visit the upstream service.

**Comment by spacewander** [comment]
You can give [grpc-client-nginx-module](https://github.com/api7/grpc-client-nginx-module) a try.
See https://github.com/apache/apisix/blob/master/apisix/core/grpc.lua

**Comment by jujiale** [comment]
> You can give [grpc-client-nginx-module](https://github.com/api7/grpc-client-nginx-module) a try. See https://github.com/apache/apisix/blob/master/apisix/core/grpc.lua

I will have a try. thanks a lot.
