### ISSUE TITLE
bug: when skywalking-logger service_instance_name set to $hostname not work

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#7977]
### Current Behavior

As mentiond in documentation https://apisix.apache.org/docs/apisix/plugins/skywalking-logger/, when `service_instance_name` set to `$hostname`, the plugin will use APISIX hostname to instance name, but it not work now.

### Expected Behavior

When setting `service_instance_name` to `$hostname`, APISIX must correctly send the hostname as the instance name to skywalking.

### Steps to Reproduce

1. Code in skywalking tracer plugin: https://github.com/apache/apisix/blob/master/apisix/plugins/skywalking.lua#L130-L132
2. There is no such code in `skywalking-logger`.

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`): not required
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): not required
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): not required
- APISIX Dashboard version, if relevant: not required
- Plugin runner version, for issues related to plugin runners: not required
- LuaRocks version, for installation issues (run `luarocks --version`): not required

**Comment by tzssangglass** [comment]
Will you fix it?

**Comment by bzp2010** [comment]
@tzssangglass I don't have time to deal with it for now, only to report the problems collected.

**Comment by spacewander** [comment]
Look like this PR is not merged into master...
https://github.com/apache/apisix/pull/7252
