### ISSUE TITLE
help request: proxy-rewrite plugin does not support grpc header rewrite?

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#7978]
### Description

hello
  I want to use proxy-rewrite to rewrite grpc header "host", then proxy it to gprc service in upstream. but I find that proxy-rewrit does not support

the config is below:
`

    {
      "uri": "/helloworld.Greeter/SayHello",
      "name": "grpc-grpc",
      "methods": [
        "POST",
        "GET"
      ],
      "plugins": {
        "proxy-rewrite": {
          "headers": {
            "host": "111.222.333.444"
          },
          "host": "111.222.333.444"
        }
      },
      "upstream": {
        "nodes": [
          {
            "host": "172.25.xxx.xxx",
            "port": 50051,
            "weight": 1
          }
        ],
        "timeout": {
          "connect": 6,
          "send": 6,
          "read": 6
        },
        "type": "roundrobin",
        "scheme": "grpc",
        "pass_host": "pass",
        "keepalive_pool": {
          "idle_timeout": 60,
          "requests": 1000,
          "size": 320
        }
      },
      "status": 1
    }

`

### Environment

- APISIX version (run `apisix version`):2.12.0
- Operating system (run `uname -a`):Linux  3.10.0-957.21.3.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
fixed by: https://github.com/apache/apisix/pull/7939

**Comment by jujiale** [comment]
> fixed by: #7939

@tzssangglass Thanks very much
