### ISSUE TITLE
help request: Install with Docker

### ISSUE THREAD

**Issue by Zh3Wang** [apache/apisix#7985]
### Description

according to the getting started

request:
`curl "http://127.0.0.1:9080/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

response:
`<html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>%`

Darwin wangzhedeMacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8110 x86_64

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
what is the version of images?

**Comment by noobHuKai** [comment]
apisix 404 response format is json，may be other program listen 9080，and apisix don't start

**Comment by Zh3Wang** [comment]
> apisix 404 response format is json，may be other program listen 9080，and apisix don't start

you are right !!!  thanks

**Comment by tzssangglass** [comment]
Considered resolved, feel free to reopen it if you needed.
