### ISSUE TITLE
help request: customize the return description and error page

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#7987]
### Description

when apisix return 5xx http code, I want customize the return description and error page.  It include two sides.

1. The short description of the error code. For example `HTTP/1.1 503 Service Temporarily Unavailable`, I want modify it to `HTTP/1.1 503 Service Unavailable`.    I grep `Service Temporarily Unavailable` not found but fount it on nginx.  https://github.com/nginx/nginx/blob/master/src/http/ngx_http_header_filter_module.c#L120
2. The default error html page. I want return XML format string not html. For example :
 ```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
```
to 
```
<?xml version="1.0" encoding="UTF-8" ?>
<error>502</error>
```

I found the error pages were defined on openresty and nginx.

https://github.com/openresty/openresty/blob/master/patches/nginx-1.11.2-builtin_error_page_footer.patch#L10

Is it possible to just modify the source code of apisix above two points?

### Environment

- APISIX version (run `apisix version`): 2.10.1
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.19.3.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.14
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@zhendongcmss You may try to use the `error_page` directive. See https://apisix.apache.org/docs/apisix/customize-nginx-configuration/ to learn how to inject this directive to APISIX.

**Comment by monkeyDluffy6017** [comment]
For 1, OpenRest doesn't provide a api to change the HTTP status reason now, but i found a stale pr: https://github.com/openresty/lua-nginx-module/pull/870, it could resolve your problem, but it is blocked by `need test cases`, i will push this pr.

For 2,  please follow what @tokers suggested, and if you want to handle with the upstream status code, please add directive `proxy_intercept_errors`.

**Comment by boekkooi-lengoo** [comment]
Hey all, 
So I hit the same issue where a 401 was returned by the `openid` plugin and it shows the nginx/openresty [error page](https://github.com/api7/apisix-nginx-module/blob/main/patch/1.21.4/nginx-error_page_contains_apisix.patch).

To be it feels very inconsistent that some plugins return error like `{"error_msg": "...."}` and then at other moment you need to deal with nginx error pages. 

Any how in my case I used the following code to match the error message up.

```YAML
  configurationSnippet:
    # Based on
    # - https://blog.adriaan.io/one-nginx-error-page-to-rule-them-all.html
    # - https://gist.github.com/lextoumbourou/d6221deb818da4f342ea
    httpStart: |
      more_clear_headers Server;
      
      map $status $status_text {
        400 'Bad Request';
        401 'Unauthorized';
        402 'Payment Required';
        403 'Forbidden';
        404 'Not Found';
        405 'Method Not Allowed';
        406 'Not Acceptable';
        407 'Proxy Authentication Required';
        408 'Request Timeout';
        409 'Conflict';
        410 'Gone';
        411 'Length Required';
        412 'Precondition Failed';
        413 'Payload Too Large';
        414 'URI Too Long';
        415 'Unsupported Media Type';
        416 'Range Not Satisfiable';
        417 'Expectation Failed';
        418 'I\'m a teapot';
        421 'Misdirected Request';
        422 'Unprocessable Entity';
        423 'Locked';
        424 'Failed Dependency';
        425 'Too Early';
        426 'Upgrade Required';
        428 'Precondition Required';
        429 'Too Many Requests';
        431 'Request Header Fields Too Large';
        451 'Unavailable For Legal Reasons';
        500 'Internal Server Error';
        501 'Not Implemented';
        502 'Bad Gateway';
        503 'Service Unavailable';
        504 'Gateway Timeout';
        505 'HTTP Version Not Supported';
        506 'Variant Also Negotiates';
        507 'Insufficient Storage';
        508 'Loop Detected';
        510 'Not Extended';
        511 'Network Authentication Required';
        default 'Something is wrong';
      }
      map $http_accept $extension {
        default html;
        ~*application/json json;
      }
    httpSrv: |
      error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 @error_$extension;

      location @error_json {
        types { } default_type "application/json; charset=utf-8";
        echo '{"error_msg": "$status_text"}';
      }
      location @error_html {
        types { } default_type "text/html; charset=utf-8";
        echo '<html><head><title>$status $status_text</title></head><body><center><h1>$status $status_text</h1></center></html>';
      }
```

**Comment by laizuan** [comment]
@boekkooi-lengoo 

hi I didn't find the 'configurationSnippet' configuration in 'default-config.yaml', could you please tell me how you configured it? thank you

**Comment by boekkooi-lengoo** [comment]
Hey @laizuan,

I think that was the name on the help chart in any case httpStart is the one defined under https://github.com/apache/apisix/blob/809ba09b26ddd62e0efa612f85e90d1aa938ce02/conf/config-default.yaml#L176

**Comment by pshettyk** [comment]
Super.  It worked.  Thanks very much. I had to put contents of "httpSrv" in "http_server_configuration_snippet" and "httpStart" in "http_configuration_snippet" section of config.xml.

**Comment by nphariharan** [comment]
Thanks for the help. The below is the working config.yaml. (tested in APISIX 3.6.0 - Standalone mode). Some body wants this feature, they can quickly take this working configuration. You can customize below code as per your needs.

nginx_config:
  http_configuration_snippet: |
    more_clear_headers Server;
    map $status $status_text {
      400 'Bad Request';
      401 'Unauthorized';
      402 'Payment Required';
      403 'Forbidden';
      404 'Not Found';
      405 'Method Not Allowed';
      406 'Not Acceptable';
      407 'Proxy Authentication Required';
      408 'Request Timeout';
      409 'Conflict';
      410 'Gone';
      411 'Length Required';
      412 'Precondition Failed';
      413 'Payload Too Large';
      414 'URI Too Long';
      415 'Unsupported Media Type';
      416 'Range Not Satisfiable';
      417 'Expectation Failed';
      418 'I\'m a teapot';
      421 'Misdirected Request';
      422 'Unprocessable Entity';
      423 'Locked';
      424 'Failed Dependency';
      425 'Too Early';
      426 'Upgrade Required';
      428 'Precondition Required';
      429 'Too Many Requests';
      431 'Request Header Fields Too Large';
      451 'Unavailable For Legal Reasons';
      500 'Internal Server Error';
      501 'Not Implemented';
      502 'Bad Gateway';
      503 'Service Unavailable';
      504 'Gateway Timeout';
      505 'HTTP Version Not Supported';
      506 'Variant Also Negotiates';
      507 'Insufficient Storage';
      508 'Loop Detected';
      510 'Not Extended';
      511 'Network Authentication Required';
      default 'Something is wrong';
    }
    map $http_accept $extension {
      default html;
      ~*application/json json;
    }

  http_server_configuration_snippet: |
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 @error_$extension;

    location @error_json {
      types { } default_type "application/json; charset=utf-8";
      echo '{"error_msg": "$status_text"}';
    }
    location @error_html {
      types { } default_type "text/html; charset=utf-8";
      echo '<html><head><title>$status $status_text</title></head><body><center><h1>$status $status_text</h1></center></html>';
    }

**Comment by lvillis** [comment]
Thanks @boekkooi-lengoo @nphariharan

Apisix v3.x requires the following configuration to take effect.

```yaml
apisix:
  # .....
nginx_config:
  http_configuration_snippet: |
    more_clear_headers Server;
    
    map $status $status_text {
    400 'Bad Request';
    401 'Unauthorized';
    402 'Payment Required';
    403 'Forbidden';
    404 'Not Found';
    405 'Method Not Allowed';
    406 'Not Acceptable';
    407 'Proxy Authentication Required';
    408 'Request Timeout';
    409 'Conflict';
    410 'Gone';
    411 'Length Required';
    412 'Precondition Failed';
    413 'Payload Too Large';
    414 'URI Too Long';
    415 'Unsupported Media Type';
    416 'Range Not Satisfiable';
    417 'Expectation Failed';
    418 'I\'m a teapot';
    421 'Misdirected Request';
    422 'Unprocessable Entity';
    423 'Locked';
    424 'Failed Dependency';
    425 'Too Early';
    426 'Upgrade Required';
    428 'Precondition Required';
    429 'Too Many Requests';
    431 'Request Header Fields Too Large';
    451 'Unavailable For Legal Reasons';
    500 'Internal Server Error';
    501 'Not Implemented';
    502 'Bad Gateway';
    503 'Service Unavailable';
    504 'Gateway Timeout';
    505 'HTTP Version Not Supported';
    506 'Variant Also Negotiates';
    507 'Insufficient Storage';
    508 'Loop Detected';
    510 'Not Extended';
    511 'Network Authentication Required';
    default 'Something is wrong';
    }
    map $http_accept $extension {
    default html;
    ~*application/json json;
    }
  http_server_configuration_snippet: |
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 @error_$extension;

      location @error_json {
        types { } default_type "application/json; charset=utf-8";
        echo '{"error_msg": "$status_text"}';
      }
      location @error_html {
        types { } default_type "text/html; charset=utf-8";
        echo '<html><head><title>$status $status_text</title></head><body><center><h1>$status $status_text</h1></center></html>';
      }
```

**Comment by monkeyDluffy6017** [comment]
considered resolved

**Comment by JoonaHa** [comment]
Hi @lvillis @boekkooi-lengoo 
Does setup this still work for you? I tried with Apisix 3.9 and 3.8
I tried by passing the values using the Helm chart's `configurationSnippet.httpStart` and `configurationSnippet.httpSrv`
Also tried by modifying config.yaml directly and in both cases container included the correct fields in file `/usr/local/apisix/conf/nginx.conf`
Still no luck.

**Comment by boekkooi-lengoo** [comment]
Hey @JoonaHa 

I just did an update from 3.8.0 to 3.9.0 and this trick still work like a charm for me.
Maybe there is some error in the logs or you forgot to add the header `Accept: application/json` while testing?

Cheers,
Warnar

**Comment by JoonaHa** [comment]
Thanks @boekkooi-lengoo I got it to work. I had misconfigured plugin which caused an error to return from lua instead of nginx.

**Comment by maksyche** [comment]
In case anyone faces the same error:`empty URI in redirect to named location "@error_html" while reading client request line`.

I needed only json response, so the solution for me was not to use named locations and specify the page name.

Overall config looks like this:
```
nginx_config:
  http_configuration_snippet: |
    more_clear_headers Server;
    
    map $status $status_text {
    400 'Bad Request';
    401 'Unauthorized';
    402 'Payment Required';
    403 'Forbidden';
    404 'Not Found';
    405 'Method Not Allowed';
    406 'Not Acceptable';
    407 'Proxy Authentication Required';
    408 'Request Timeout';
    409 'Conflict';
    410 'Gone';
    411 'Length Required';
    412 'Precondition Failed';
    413 'Payload Too Large';
    414 'URI Too Long';
    415 'Unsupported Media Type';
    416 'Range Not Satisfiable';
    417 'Expectation Failed';
    418 'I\'m a teapot';
    421 'Misdirected Request';
    422 'Unprocessable Entity';
    423 'Locked';
    424 'Failed Dependency';
    425 'Too Early';
    426 'Upgrade Required';
    428 'Precondition Required';
    429 'Too Many Requests';
    431 'Request Header Fields Too Large';
    451 'Unavailable For Legal Reasons';
    500 'Internal Server Error';
    501 'Not Implemented';
    502 'Bad Gateway';
    503 'Service Unavailable';
    504 'Gateway Timeout';
    505 'HTTP Version Not Supported';
    506 'Variant Also Negotiates';
    507 'Insufficient Storage';
    508 'Loop Detected';
    510 'Not Extended';
    511 'Network Authentication Required';
    default 'Something is wrong';
    }
  http_server_configuration_snippet: |
    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 426 428 429 431 451 500 501 502 503 504 505 506 507 508 510 511 /my_error_page;

    location /my_error_page {
      types { } default_type "application/json; charset=utf-8";
      echo '{"error_msg": "$status_text"}';
    }
```

**Comment by mikyll** [comment]
In case anyone needs it, I'm leaving here the full list of status code messages (plus "I'm a teapot"), according to [iana.org](https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml):

```conf
nginx_config:
  http_configuration_snippet: |
    # ...

    map $status $status_text {
    100 "Continue";
    101 "Switching Protocols";
    102 "Processing";
    103 "Early Hints";

    200 "OK";
    201 "Created";
    202 "Accepted";
    203 "Non-Authoritative Information";
    204 "No Content";
    205 "Reset Content";
    206 "Partial Content";
    207 "Multi-Status";
    208 "Already Reported";
    226 "IM Used";

    300 "Multiple Choices";
    301 "Moved Permanently";
    302 "Found";
    303 "See Other";
    304 "Not Modified";
    305 "Use Proxy";
    307 "Temporary Redirect";
    308 "Permanent Redirect";

    400 "Bad Request";
    401 "Unauthorized";
    402 "Payment Required";
    403 "Forbidden";
    404 "Not Found";
    405 "Method Not Allowed";
    406 "Not Acceptable";
    407 "Proxy Authentication Required";
    408 "Request Timeout";
    409 "Conflict";
    410 "Gone";
    411 "Length Required";
    412 "Precondition Failed";
    413 "Content Too Large";
    414 "URI Too Long";
    415 "Unsupported Media Type";
    416 "Range Not Satisfiable";
    417 "Expectation Failed";
    418 "I'm a teapot";
    421 "Misdirected Request";
    422 "Unprocessable Content";
    423 "Locked";
    424 "Failed Dependency";
    425 "Too Early";
    426 "Upgrade Required";
    428 "Precondition Required";
    429 "Too Many Requests";
    431 "Request Header Fields Too Large";
    451 "Unavailable For Legal Reasons";

    500 "Internal Server Error";
    501 "Not Implemented";
    502 "Bad Gateway";
    503 "Service Unavailable";
    504 "Gateway Timeout";
    505 "HTTP Version Not Supported";
    506 "Variant Also Negotiates";
    507 "Insufficient Storage";
    508 "Loop Detected";
    510 "Not Extended";
    511 "Network Authentication Required";

    default "Something is wrong";
    }

    # ...
```
