### ISSUE TITLE
help request: SSL private key encryption?

### ISSUE THREAD

**Issue by C2022021** [apache/apisix#7989]
### Description

I found `ssl` section in config-default.yaml has a `key_encrypt_salt` attribute, and comment of it said:
\#  If not set, will save origin ssl key into etcd.
\#  If set this, must be a string of length 16. And it will encrypt ssl key with AES-128-CBC
\#  !!! So do not change it after saving your ssl, it can't decrypt the ssl keys have be saved if you change !!

But, After I setting certificate and key through APISIX Dashboard, I still can get origin ssl key from etcd by command `etcdctl get --prefix "/apisix/ssl"` instead of encrypt string.
I am confused that is the key encryption function has not imlpement for apisix version 2.13.3 on RHEL ? Or anything I had setting wrong in my config file?

### Environment

- APISIX version (run `apisix version`): 2.13.3
- Operating system (run `uname -a`): RHEL 8.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.13
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
cc @bzp2010 . I'm not sure if this feature is implemented by Dashboard.

**Comment by monkeyDluffy6017** [comment]
The upload cert apis in apisix-dashboard and apisix are different, the one in apisix will encrypt ssl key, and apisix-dashboard will not. you could upload ssl certs with `utils/create-ssl.py`, like `./create-ssl.py t.crt t.key test.com`, we would unify apisix-dashboard and apisix later.

**Comment by C2022021** [comment]
Thanks for your reply!!
