### ISSUE TITLE
request help: migrate etcd configuration data from V2 into V3

### ISSUE THREAD

**Issue by lilien1010** [apache/apisix#799]
for the later version apisix, I think we need have some tool for user to migrate configuration data into higher version ETCD.

https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/v2-migration.md

**Comment by moonming** [comment]
why need tools for that? Is https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/v2-migration.md not good enough?

**Comment by membphis** [comment]
Add some documentation to make it available for the moment.

**Comment by spacewander** [comment]
Solved.
