### ISSUE TITLE
feat: Add Slow Start Support for Applications.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#7992]
### Description

> Slow start is very useful for applications that depend on cache and need a warm-up period before being able to respond to requests with optimal performance.
>With the slow start mode, targets warm up before accepting their fair share of requests based on a ramp-up period that you specify.

I think we need a slow start mode that allows you to add new targets without overwhelming them with a flood of requests. 
Most of the use cases I see are JVM based applications

* AWS has supported this model a few years ago
https://aws.amazon.com/about-aws/whats-new/2018/05/application-load-balancer-announces-slow-start-support/?nc1=h_ls

* Envoy also have one https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/load_balancing/slow_start

**Comment by tokers** [comment]
Technically, how to recognize a new instance in apisix upstream is difficult.

**Comment by tokers** [comment]
Technically, how to recognize a new instance in apisix upstream is difficult.

**Comment by tzssangglass** [comment]
It looks like we need to develop a new LB algorithm that supports slow start?

**Comment by tao12345666333** [comment]
I have discussed with some people before whether it is possible to add an Event mechanism to APISIX. cc @membphis 
In this way, users can subscribe to these events and perform some additional operations.

Corresponding to this, if it is not easy to implement in APISIX, maybe it is possible to subscribe to these events through an external system and then complete it through the Admin API?

**Comment by tokers** [comment]
> I have discussed with some people before whether it is possible to add an Event mechanism to APISIX. cc @membphis In this way, users can subscribe to these events and perform some additional operations.
> 
> Corresponding to this, if it is not easy to implement in APISIX, maybe it is possible to subscribe to these events through an external system and then complete it through the Admin API?

I think this feature can be done but it also needs help from the control plane. e.g., we may add the "node metadata" and let the control plane records the adding / updating timestamp for this node. In the meanwhile, implement the custom balancer in APISIX and use the timestamp.

**Comment by xuminwlt** [comment]
LGTM, we do it in LB weight config,  level up to 10  20  30, but sometimes weight is difficult to calculate.

**Comment by spacewander** [comment]
> Corresponding to this, if it is not easy to implement in APISIX, maybe it is possible to subscribe to these events through an external system and then complete it through the Admin API?

I didn't say it is not easy to implement. I said, "there is not a mechanism to recognize the new node", just means there is not such a mechanism for now.

We should add the node level timestamp to the node discovered by the DP side, so a pure CP side solution may have some limitations.

**Comment by spacewander** [comment]
A possible solution may contain two parts:
1. add timestamp when a node is created
2. add a callback when syncing upstream from CP, which will merge the timestamps of the old upstream to the new one.
