### ISSUE TITLE
feat: As a user, I want to 用网关的jwt做sso , so that 需要jwt校验失败可以返回更多的信息

### ISSUE THREAD

**Issue by wulinghui** [apache/apisix#7993]
### Description

现在如果jwt插件失败。 `{"message":"failed to verify jwt"}` 只有这个信息。

我希望里面包含当时放到的url也放到消息返回体中。

我还希望可以jwt失败之后可以有自定义的业务处理逻辑，如重定向到登录页面，进行下放jwt。

**Comment by tokers** [comment]
Currently, it's not feasible. You may use the plugin metadata to inject a custom error response but it cannot inject the URL right now.

See https://apisix.apache.org/docs/apisix/terminology/plugin/#plugin-common-configuration.

**Comment by wulinghui** [comment]
如果我自定义插件的形式是否可以。做重定向的支持呢？

**Comment by tzssangglass** [comment]
> 如果我自定义插件的形式是否可以。做重定向的支持呢？

Yes, your own code can of course be implemented as you want.

**Comment by wulinghui** [comment]
谢谢，我按上面的教程，实现了，特来感谢。
