### ISSUE TITLE
help request: Is there a plugin to change the upstream node during the load balancing phase?

### ISSUE THREAD

**Issue by siaron** [apache/apisix#7996]
### Description

-  a plugin to change the upstream node during the load balancing phase?

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
the balancer phase  is not open to plugins

**Comment by kingluo** [comment]
@siaron At balancing phase, all you could do is to choose an upstream, but the upstream list could not be changed. If you need to change the upstream accurately, maybe you should use traffic-split plugin.

**Comment by siaron** [comment]
The traffic-split looks a bit complicated. I put the upstream node into the http header through the `java plugin`. A custom plugin implemented it.

**Comment by tokers** [comment]
It looks like a dynamic upstream plugin which allows users to specify the nodes from an API request.

**Comment by tzssangglass** [comment]
> @kingluo The traffic-split looks a bit complicated. I put the upstream node into the http header through the `java plugin`. A custom plugin implemented it.

Are you saying that the java plugin runner is used to write the upstream ip in the header and pass it to APISIX, which uses a custom lua plugin to read the ip and set the upstream?

**Comment by siaron** [comment]
@tzssangglass yes.

**Comment by tzssangglass** [comment]
It is also a viable way.

**Comment by shreemaan-abhishek** [comment]
@siaron, would you like to propose this feature?
