### ISSUE TITLE
bug: apisix When only the active health check configuration is modified through the interface, the passive health check is also turned on through dashbord

### ISSUE THREAD

**Issue by jiahui1988** [apache/apisix#8000]
### Current Behavior

1）： 通过接口添加一个被动健康检查
curl http://127.0.0.1:9080/apisix/admin/routes/101 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "count": 2,
            "time_window": 60,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    },
    "upstream": {
         "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "http_path": "/status",
                "host": "foo.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                }
            }
        }
    }
}'
2）：通过dashboard查看该配置，发现被健康检查也被打开了（且通过响应的数据看，响应数据确实携带了被动健康检查等相关字段）。

### Expected Behavior

此时的被动健康检查自带应该是关闭状态。且响应数据不应该携带被动健康检查字段

### Error Logs

无日志输出。

### Steps to Reproduce

1）： 通过接口添加一个被动健康检查
curl http://127.0.0.1:9080/apisix/admin/routes/101 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "limit-count": {
            "count": 2,
            "time_window": 60,
            "rejected_code": 503,
            "key": "remote_addr"
        }
    },
    "upstream": {
         "nodes": {
            "127.0.0.1:1980": 1
        },
        "type": "roundrobin",
        "retries": 2,
        "checks": {
            "active": {
                "http_path": "/status",
                "host": "foo.com",
                "healthy": {
                    "interval": 2,
                    "successes": 1
                },
                "unhealthy": {
                    "interval": 1,
                    "http_failures": 2
                }
            }
        }
    }
}'
2）：通过dashboard查看该配置，发现被健康检查也被打开了（且通过响应的数据看，响应数据确实携带了被动健康检查等相关字段）。

### Environment

- APISIX version：通过docker安装的2.15（自带dashboard）

**Comment by hf400159** [comment]
fixed!  please refer to: https://github.com/apache/apisix/pull/7850
