### ISSUE TITLE
bug: apisix can't be started through docker in mac

### ISSUE THREAD

**Issue by jiahui1988** [apache/apisix#8002]
### Current Behavior

git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example

docker-compose -p docker-apisix up -d   后发现apisix一直在重启中。

### Error Logs

docker logs -f --tail  100 $<container_id>发现：
all etcd nodes are unavailable
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused

### Steps to Reproduce

git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example

docker-compose -p docker-apisix up -d

### Environment

- APISIX version : 最新版本

**Comment by jiahui1988** [comment]
etcd已经成功启动了，apisix报错。

**Comment by tzssangglass** [comment]
The etcd container is working?

**Comment by tokers** [comment]
It's strange, why the etcd address would be 127.0.0.1?

**Comment by soulbird** [comment]
Last night we released a docker image of the latest version of APISIX, some configurations haven't been synced yet, I'll fix it right away.

**Comment by shreemaan-abhishek** [comment]
Can this be closed now?
