### ISSUE TITLE
help request: This topic describes WebSocket configuration

### ISSUE THREAD

**Issue by Caibreeze0908** [apache/apisix#8012]
### Description

Configuration on nginx:
location ^~ /test/  {
    proxy_pass			https://RSIP:443;
    proxy_http_version  1.1;
    proxy_set_header    Host $host;
    proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header    Upgrade $http_upgrade;
    proxy_set_header    Connection "upgrade";
}
Notice:    that proxy_pass is followed by HTTPS
How do I configure it on Apisix?
When I changed my upstream scheme to HTTPS and enabled Websocket, I found that %3A in the URI was decoded to “:” 

### Environment

- APISIX version (run `apisix version`):2.13.1
- Operating system (run `uname -a`):x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):openresty/1.19.3.1
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:No plug-in is used
- LuaRocks version, for installation issues (run `luarocks --version`):2.3.0

**Comment by tzssangglass** [comment]
> How do I configure it on Apisix? When I changed my upstream scheme to HTTPS and enabled Websocket, I found that %3A in the URI was decoded to “:”

It looks like you've configured route on APISIX, can you share? `%3A` -> `.` pls describe the problem in detail.

**Comment by shreemaan-abhishek** [comment]
ping @Caibreeze0908
