### ISSUE TITLE
help request:  路由中的路径如何配置正则匹配

### ISSUE THREAD

**Issue by wulinghui** [apache/apisix#8013]
### Description

我看介绍是说: 
> HTTP 请求路径，如 /foo/index.html，支持请求路径前缀 /foo/*。/* 代表所有路径

我想配置只代理css或者js结尾的内容。配置如下：
  `~.*\.(css|js)?$`

这段配置再nginx中是好使的，但是再apisix中为啥不行？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
see: https://github.com/apache/apisix/issues/4672
