### ISSUE TITLE
help request: error：apisix-base conflicts with openresty-1.21.4.1-1.el7.x86_64

### ISSUE THREAD

**Issue by bluewaystar** [apache/apisix#8015]
### Description

When installing apisix through yum, sudo yum installs apisix. The error is as follows:

error:apisix-base conflicts with openresty-1.21.4.1-1.el7.x86_ sixty-four。

How to resolve this conflic，please.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Only one of openresty and apisix-base can be installed, you can uninstall openresty, apisix-base can completely replace openresty.

**Comment by bluewaystar** [comment]
> Only one of openresty and apisix-base can be installed, you can uninstall openresty, apisix-base can completely replace openresty.

thanks.have solved it.
