### ISSUE TITLE
help request: Customize the plug-in image

### ISSUE THREAD

**Issue by tong12580** [apache/apisix#8016]
### Description

How to give a custom plugin a custom image? 【dashboard】

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
Please describe your question clearly.
