### ISSUE TITLE
help request: Why does routing not work? path=/test/*

### ISSUE THREAD

**Issue by bluewaystar** [apache/apisix#8020]
### Description

APISIX Dashboard

Create route, **path=/test/***, error is reported as follows:
![image](https://user-images.githubusercontent.com/87225085/192955087-d4cf204c-b094-4c25-9b84-2ab016640454.png)

http://127.0.0.1:9080/test/callway
{
"status": 404,
"error": "Not Found",
"message": "",
"path": "/test/callway"
}
**please,Why does routing not work?**
-----------
Modify Path, **path=/***, executed successfully

http://127.0.0.1:9080/callway
![image](https://user-images.githubusercontent.com/87225085/192955184-afc76be5-e4bc-409c-a21f-a7968a8693d9.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> http://127.0.0.1:9080/test/callway
> {
> "status": 404,
> "error": "Not Found",
> "message": "",
> "path": "/test/callway"
> }

This response appears to be a 404 returned upstream, not from APISIX.

You can access the upstream directly with this path.

**Comment by bluewaystar** [comment]
> Please supply the environment information, thanks!

apisix version：2.99.0

nginx version: openresty/1.21.4.1

thanks.

**Comment by bluewaystar** [comment]
> http://127.0.0.1:9080/test/callway

access http://192.168.10.100:8866/callway is success

My intention is that the client accesses the gateway through Apisix http://127.0.0.1:**9080/test** And then actually proxy to the upstream http://192.168.10.**100:8866/callway**

**Comment by bluewaystar** [comment]
> > http://127.0.0.1:9080/test/callway
> > {
> > "status": 404,
> > "error": "Not Found",
> > "message": "",
> > "path": "/test/callway"
> > }
> 
> This response appears to be a 404 returned upstream, not from APISIX.
> 
> You can access the upstream directly with this path.

Individual access http://192.168.10.100:8866/callway No problem，it is Ok.

but My intention is that the client accesses the gateway through Apisix http://127.0.0.1:**9080/test** And then actually proxy to the upstream [http://192.168.10.**100:8866/callway](http://192.168.10.%2A%2A100:8866/callway)**

**Comment by tzssangglass** [comment]
> but My intention is that the client accesses the gateway through Apisix http://127.0.0.1:**9080/test** And then actually proxy to the upstream [http://192.168.10.**100:8866/callway](http://192.168.10.%2A%2A100:8866/callway)**

try with `proxy-rewrite` plugin, ref: https://github.com/apache/apisix/blob/master/docs/en/latest/FAQ.md#how-do-i-strip-a-prefix-from-a-path-before-forwarding-to-upstream-in-apache-apisix
