### ISSUE TITLE
bug: set endpoint into discovery DICT failed, no memory when use kubernetes discovery

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#8021]
### Current Behavior

2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:38:57 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:46:13 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:53:25 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer

### Expected Behavior

no error

### Error Logs

2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:37:43 [error] 64#64: *253 [lua] init.lua:111: on_added(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:38:57 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:46:13 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
2022/09/29 15:53:25 [error] 64#64: *253 [lua] init.lua:111: on_modified(): set endpoint into discovery DICT failed, no memory, context: ngx.timer
sh-4.2# uname -a

### Steps to Reproduce

apisix2.15 use k8s service discovery

### Environment

- APISIX version (run `apisix version`): apisix2.15
- Operating system (run `uname -a`): 4.14.105-19-0023.1
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@wolgod What's the size of the shared dict for the Kubernetes service discovery module. Could you just paste the APISIX `config-default.yaml` and `config.yaml`.

**Comment by wolgod** [comment]
> @wolgod What's the size of the shared dict for the Kubernetes service discovery module. Could you just paste the APISIX `config-default.yaml` and `config.yaml`.


when i set values like this in config.yaml, The error disappeared
config.yaml
```
      kubernetes: 20m
```

**Comment by zhixiongdu027** [comment]
> > @wolgod What's the size of the shared dict for the Kubernetes service discovery module. Could you just paste the APISIX `config-default.yaml` and `config.yaml`.
> 
> 
> when i set values like this in config.yaml, The error disappeared
> config.yaml
> ```
>       kubernetes: 20m
> ```
> 

I think this cluster must have a lot of services deployed

**Comment by wolgod** [comment]
> 
in apisix 2.15 ,shared_size  can use? i don't find  the config  [https://apisix.apache.org/zh/docs/apisix/2.15/discovery/kubernetes/](url)

**Comment by zhixiongdu027** [comment]
Sorry for my mistake.
Supported from 3.0.0-beta

**Comment by tokers** [comment]
@wolgod In APISIX 2.15, the shared dict size for Kubernetes service discovery is fixed, unless you modify the `apisix/cli/ngx_tpl.lua`.
