### ISSUE TITLE
bug: 全局插件开启了一个插件A，路由配置关闭了插件A。插件A仍然生效

### ISSUE THREAD

**Issue by kidd1985** [apache/apisix#8023]
### Current Behavior

apisix版本：2.15
dashboard版本:2.13
问题如上。

### Expected Behavior

期望结果是 相同插件 ，路由配置覆盖全局插件配置。

### Steps to Reproduce

1，全局配置开启插件A
"A-token-auth": {
      "disable": false
    
    }

2，路由配置，关闭插件A
"A-token-auth": {
      "disable": true
    
    }

### Environment

apisix版本：2.15
dashboard版本:2.13

**Comment by bzp2010** [comment]
This is normal and is supposed to work that way. Once turned on, the global plugin (i.e. Global Rule) will run no matter what, even if you turn it off on the route.
The global rule has nothing to do with routing plugins (which also contain Services and Consumers), they are decoupled. The global rule will definitely run once it is turned on, it is usually used to enforce global restrictions and security measures.

**Comment by tzssangglass** [comment]
It's not a problem, it's designed that way.

**Comment by kidd1985** [comment]
如果要把这个作为扩展功能呢，考虑支持么？是有这种需求。
 如果我自己做，需要怎么做？

**Comment by tzssangglass** [comment]
> 如果要把这个作为扩展功能呢，考虑支持么？是有这种需求。
> 如果我自己做，需要怎么做？

There are two ways.
1 Don't set global rule 
2 Do it on control plane: when you delete plugin A on the route, you also delete plugin A on the global rule at the same time.

APISIX does not have a plan to support this requirement.
