### ISSUE TITLE
bug: lua-resty-etcd version error

### ISSUE THREAD

**Issue by butterflyAce** [apache/apisix#8025]
### Current Behavior

when make deps on version:2.99.0，lua-resty-etcd need version 1.9.0,but was not found.it shoud be 1.9.0-0

### Expected Behavior

when make deps on version:2.99.0，lua-resty-etcd need version 1.9.0,but was not found.it shoud be 1.9.0-0

### Error Logs

No results matching query were found for Lua 5.1. make: *** [deps] 错误 1

### Steps to Reproduce

1.make deps

### Environment

- APISIX version (run `apisix version`): 2.99.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
I didn't reproduce this error.

**Comment by tzssangglass** [comment]
> when make deps on version:2.99.0，lua-resty-etcd need version 1.9.0,but was not found.it shoud be 1.9.0-0

This is not an error. As a rule of thumb, this is a network error in your environment connecting to luarocks.

try with `make deps ENV_LUAROCKS_SERVER=https://luarocks.cn`
