### ISSUE TITLE
apisix already supports dubbo3, can it support mainstream microservice frameworks written in c++, go, rust, etc.?

### ISSUE THREAD

**Issue by sunbiaozj** [apache/apisix#8026]
### Description

apisix已支持dubbo3的无缝对接，后面能支持c++、go、rust等写的主流微服务框架吗？
例如c++写的tars等主流微服务框架
        go写的rpcx、CloudWeGo等主流微服务框架
        rust写的 Volo等主流微服务框架

**Comment by soulbird** [comment]
APISIX already supports tars, others are not currently planned, but PR is welcome.

**Comment by galaxy-sea** [comment]
@sunbiaozj 
hello, 我开发了一个Spring Cloud APISIX, 你可以尝试一下使用Spring Cloud开发微服务

仓库地址: [https://github.com/galaxy-sea/spring-cloud-apisix](https://github.com/galaxy-sea/spring-cloud-apisix)
