### ISSUE TITLE
help request: Prometheus `http_requests_total ` metrics type  shouldn't be `gauge`

### ISSUE THREAD

**Issue by pg-yang** [apache/apisix#8028]
### Description

https://github.com/apache/apisix/blob/30378f5a64eb41446831b54b6c8ec042e004e098/apisix/plugins/prometheus/exporter.lua#L138-L139

Hello , I activated prometheus plugin for metrics , and found  the type of  `http_requests_total` is `gauge` . I think `counter` should be more appropriate . Right ? 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
for why: https://github.com/apache/apisix/issues/6301#issuecomment-1040030416

**Comment by pg-yang** [comment]
Thanks
