### ISSUE TITLE
request help: Does the APISIX need to write the configuration to the local disk?

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#803]
### Issue description
Does the APISIX need to write the configuration to the local disk?

The APISIX currently can run without the configuration center, etcd.

But its routes configuration just is stored in the memory. If APISIX runs without etcd or could not connect the etcd (still possible), meanwhile, APISIX has been restarted because of some critical BUG. APISIX will restart with no route configuration which will cause the network failure.

On the other hand, other API-Gateway, such as tyk or zuul, will write the configuration to the local disk when it exit.

### Environment

* apisix version (cmd: `apisix version`): 0.9 or higher
* OS: linux

**Comment by membphis** [comment]
Currently OpenResty has no worker exit phase, we can use the timer to synchronize the latest memory configuration data to the local disk file.

By the way, local files are better in YAML format, and YAML is more readable than JSON format.

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
