### ISSUE TITLE
benchmark is not deasired,how can i do change the config?

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8031]
### Description

in the k8s enviroment i use the wrk to benchmark,this is the result

cpu 请求 | cpu限制 | mem请求 | mem限制 | worker数量 | 后端个数 | 后端和apisix是否在一台机器 | QPS | tp50 | tp75 | tp90 | tp99
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
200m | 4 | 200Mi | 500Mi | 8 | 1 | 否 | 10594 | 0.87ms | 0.99ms | 1.36ms | 10.13ms
200m | 4 | 200Mi | 500Mi | 8 | 2 | 否 | 13558 | 640.00us | 798.00us | 1.17ms | 10.14ms
200m | 4 | 200Mi | 500Mi | 8 | 3 | 否 | 13817 | 634.00us | 781.00us | 1.10ms | 9.37ms
200m | 4 | 200Mi | 500Mi | 8 | 4 | 否 | 14660 | 595.00us | 721.00us | 1.04ms | 20.27ms

the result is not the same of desire

### Environment

- APISIX version (run `apisix version`): 2.14.1
- Operating system (run `uname -a`):TencentOS Server 2.4
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.2
- APISIX Dashboard version, if relevant:no install
- Plugin runner version, for issues related to plugin runners: prometheus
- LuaRocks version, for installation issues (run `luarocks --version`):3.8.0

**Comment by tzssangglass** [comment]
1. disable 'proxy-cache' amd `proxy-mirror` plugin
2. grow upstream service performance, don't let upstream services become bottlenecks
3. test `wrk --> upstream` as a control group, understand the impact of network latency and upstream performance in `wrk -> APISIX -> upstream`
