### ISSUE TITLE
help request: public-api http method?

### ISSUE THREAD

**Issue by C2022021** [apache/apisix#8032]
### Description

When I setting jwt-auth plugin, I need to expose "/apisix/plugin/jwt/sign" endpoint through public-api plugin. But not I only can call this endpoint by HTTP GET method even if I setting method rewrite for the route. Is that possible to change the http method of system defined public-api?

### Environment

- APISIX version (run `apisix version`): 2.13.3
- Operating system (run `uname -a`): RHEL 8.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.13
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
GET /apisix/plugin/jwt/sign is defined in the source code and does not provide a way to modify it, you can modify the source code yourself.

https://github.com/apache/apisix/blob/a45db5a70af14cdb694f65ce8fc115e1d5910024/apisix/plugins/jwt-auth.lua#L453-L461
