### ISSUE TITLE
help request: How does the admin api rewrite the request？

### ISSUE THREAD

**Issue by ascendlin** [apache/apisix#8033]
### Description

/apisix/admin/routes/{id}?ttl=0

How does the admin api rewrite the request？Similar to change request in dashboard

### Environment

- APISIX version (2.15.0):
- Operating system (Linux 192-168-16-6 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux):
- OpenResty / Nginx version (nginx version: openresty/1.21.4.1)

**Comment by tzssangglass** [comment]
The admin API is fixed, can you give an example of what is the rewrite admin api ?

**Comment by hf400159** [comment]
https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/  
![image](https://user-images.githubusercontent.com/97138894/194735483-05850845-6fcb-4169-bf95-f95faa2fd556.png)

**Comment by ascendlin** [comment]
> Do you want to use `Request Override`? ![image](https://user-images.githubusercontent.com/97138894/194735483-05850845-6fcb-4169-bf95-f95faa2fd556.png) please refer to: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

yes,thank you
