### ISSUE TITLE
How to install offline？

### ISSUE THREAD

**Issue by think4code** [apache/apisix#8034]
### Description

请问rpm和源码编译方式能不能完全离线安装？
刚按照官网说明rpm方式出错了。
源码安装方式需要先在线安装依赖，也不能离线安装。
最好能提供源码方式的完全离线安装教程，谢谢。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> 最好能提供源码方式的完全离线安装教程，谢谢。

It is not possible to install the source code by offline, the two are in conflict.

**Comment by tokers** [comment]
@zhangyuthink If you want, try to build from the source and package all the related dependencies together. You may have to write some custom scripts to make the process smooth. If possible, just download and export the APISIX docker image, which already contains the whole thing you need.

By the way, which kind of problem did you occur when you use RPM to install APISIX?

**Comment by zhangyuthink** [comment]
> 

按照官网的rpm离线安装教程操作，没有自动下载openresty-openssl111-1.1.1n-1.el7.x86_64.rpm，后来手动下载该rpm，成功了

**Comment by tokers** [comment]
cc @tzssangglass @spacewander So currently, apisix-base relies on openresty-openssl111-1.1.1n-1.el7.x86_64.rpm?

**Comment by soulbird** [comment]
Yes. apisix-base depends on openresty-openssl111-1.1.1n-1. I just tried to install apisix under centos 7 and everything works fine. I executed the command:
````
yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
yum install apisix
````

**Comment by hf400159** [comment]
Is the network normal? I can download it.

**Comment by spacewander** [comment]
https://github.com/api7/apisix-build-tools/blob/695c1ee5c84131efa796faa048829c7d9f63c585/package-apisix-base.sh#L37
openresty-openssl111 is already listed as the dependency of apisix-base.
