### ISSUE TITLE
help request: jwt-auth encryption key auto generate?

### ISSUE THREAD

**Issue by C2022021** [apache/apisix#8035]
### Description

In the documentation, it says that secret is not a required attribute of jwt-auth plugin. But now I face a problem, If setup a customer enable jwt-auth without setting secret, when request route I will get "error message: failed to verify jwt.", and if setup a customer enable jwt-auth with setting secret, then everything will be alright.

### Environment

- APISIX version (run apisix version): 2.13.3
- Operating system (run uname -a): RHEL 8.6
- OpenResty / Nginx version (run openresty -V or nginx -V):
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info): 3.4.13
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run luarocks --version):

**Comment by tokers** [comment]
@C2022021 Use secret means you choose the symmetric algorithm to sign/verify the JWT token. You can also use the asymmetric way (with RSA public & private keys). So that's why the secret field is not mandatory.

**Comment by washcroft** [comment]
@C2022021 I encountered something similar when using the /apisix/plugin/jwt/sign route.

Every **instance** of the plugin will use a random secret wherever it is not specified, so a random secret on the individual consumer and then a different random secret on the **/apisix/plugin/jwt/sign** route/service. This meant JWTs being signed for that consumer were always invalid, until the secrets matched.

**Comment by spacewander** [comment]
> Every instance of the plugin will use a random secret when secret is not specified in the config instance

https://github.com/apache/apisix/blob/9a08932417e16c51bcd9ed395a4947c339176527/apisix/plugins/jwt-auth.lua#L170

The secret is expected to be generated in the Admin API (before writing to etcd), and then each instance will sync the generated secret from etcd.

Could you provide a minimal reproducible example so we can verify it?

**Comment by washcroft** [comment]
> The secret is expected to be generated in the Admin API (before writing to etcd), and then each instance will sync the generated secret from etcd.

I mean every instance of the plugin, within the same apisix instance.

i.e.
- the plugin instance enabled on the consumer
- the plugin instance enabled on the route or service

...both will generate their own different random secrets

**Comment by tzssangglass** [comment]
> * the plugin instance enabled on the consumer

The secret of each jwt-auth plugin instance (if you use the symmetric algorithm to sign/verify the JWT token) is isolated by the consumer. This means that each consumer will have a different secret, and that is how it is designed.

**Comment by washcroft** [comment]
Ignore me, this appears to be working as expected/described now - not sure what was going on in the past.

**Comment by shreemaan-abhishek** [comment]
ping @C2022021
