### ISSUE TITLE
feat: As a user, I want to route uris should not be case-sensitive, so that /Api/V1/Table/Categories", "/api/V1/Table/categories",  "/Api/V1/table/categories"  this url does not match all of the paths

### ISSUE THREAD

**Issue by BTDevelop** [apache/apisix#8037]
### Description

"/Api/V1/Table/Categories",
"/api/V1/Table/categories", 
"/Api/V1/table/categories",
"/Api/v1/table/Categories" internal api is also case-insensitive but apisix is case-sensitive and these paths don't work.

configuration:
{
  "uris": [
    "/Api/v1/Table/Categories"
  ],
  "name": "Table.Categories",
  "methods": [
    "GET"
  ],
  "upstream_id": 1,
  "status": 1
}

"/Api/v1/Table/Categories"
"/Api/v1/Table/categories" this working?

**Comment by tokers** [comment]
@BTDevelop Currently, it doesn't work.

**Comment by spacewander** [comment]
See https://github.com/apache/apisix/issues/4412
