### ISSUE TITLE
stream_proxy tcp代理需要支持配置ssl_protocols、ssl_ciphers，默认的配置在android4.4上无法连接上

### ISSUE THREAD

**Issue by calebzhao** [apache/apisix#8041]
### Description

目前apisix好像不支持配置文件stream_proxy节点中配置ssl_protocols、ssl_ciphers，希望提供类似ssl节点可以配置ssl_protocols、ssl_ciphers

**Comment by tokers** [comment]
> 默认的配置在android4.4上无法连接上

Please provide some details about it.

**Comment by soulbird** [comment]
> ### Description
> 目前apisix好像不支持配置文件stream_proxy节点中配置ssl_protocols、ssl_ciphers，希望提供类似ssl节点可以配置ssl_protocols、ssl_ciphers

Currently you can add custom Nginx configuration in `stream_configuration_snippet` configuration item. Under the `stream_proxy` configuration item, the configuration of `ssl_protocols` is not yet supported.

But PR is welcome, you can refer to these two pieces of code:
https://github.com/apache/apisix/blob/master/apisix/cli/ops.lua#L487-L503
https://github.com/apache/apisix/blob/master/apisix/cli/ngx_tpl.lua#L185-L192

**Comment by Qiuqiu0505** [comment]
stream_proxy tcp代理转发时，请问可以通过哪种方式使得上游服务受到的源ip 保持不变？

**Comment by tokers** [comment]
> stream_proxy tcp代理转发时，请问可以通过哪种方式使得上游服务受到的源ip 保持不变？
> 
> 我配置的规则如下：
> 
> curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: ef403f335dce4906a2962b8f015a6d2d' -X PUT -d '
> 
> {
> 
>     "server_port":80,
> 
>      "scheme":"http",
> 
>     "upstream": {
> 
>         "nodes": {
> 
>             "上游服务ip:80": 1
> 
>         },
> 
>         "type": "roundrobin",
> 
>         "pass_host": "pass"
> 
>     }
> 
> }'
> 
> 
> 
> 但上游服务收到的proxy_add_x_forwarded_for始终为apisix 所在服务器ip。麻烦帮忙解答下，谢谢。
> 
> 

This issue is not relevant to your question. Please delete it and open another issue to describe your question.
