### ISSUE TITLE
feat: As a user, I want to support sasl_config in kafka-logger plugin, so that we can send logs to brokers that enable authentication

### ISSUE THREAD

**Issue by starsz** [apache/apisix#8046]
### Description

Hello,

Now I found "lua-resty-kafka" lib had supported set `sasl_config` in the client.
docs: https://github.com/doujiang24/lua-resty-kafka#new

So I want to support set `sasl_config` in kafka-logger plugin, then we can send logs to brokers that enable authentication.
Like: 

```
{
    "kafka-logger":{
        "brokers":[
            {
                "host":"127.0.0.1",
                "port":9092,
                "sasl_config":{
                    "mechanism":"PLAIN",
                    "user":"USERNAME",
                    "password":"PASSWORD"
                }
            }
        ],
        "kafka_topic":"test2",
        "key":"key1",
        "batch_max_size":1,
        "name":"kafka logger"
    }
}
```

**Comment by hf400159** [comment]
great work!

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/pull/7782

**Comment by starsz** [comment]
> Would you be willing to work with this developer on this #7782 if you wish?

OK. I can create PR based on this PR.
