### ISSUE TITLE
feat: As a user, I want to using apisix's standalone mode in k8s, but currently apisix.yaml does not support hot updates in k8s.

### ISSUE THREAD

**Issue by oil-oil** [apache/apisix#8048]
## Problems encountered

When using the volumeMount subPath method for single file mounting in k8s, the files inside the container cannot be hot updated, resulting in the `apisix.yaml` configuration is being updated in configmap and the files inside the container not being updated in parallel. If I need to synchronize the configuration, I have to destroy the pod and restart it.

## Solution

It may be necessary to provide a configurable environment variable that can specify the directory where `apisix.yaml` is generated, and mount this specified directory directly on configMap to achieve hot updates, and APISIX will go to the specified directory to read the configuration if the user has configured the environment variable when reading the configuration.

**Comment by spacewander** [comment]
The hot updates of configmap is not realtime. If I am correct, this time interval will be a few minutes. Packaging an agent in the container may be a better solution.

**Comment by starsz** [comment]
> It may be necessary to provide a configurable environment variable that can specify the directory where apisix.yaml is generated, and mount this specified directory directly on configMap to achieve hot updates, and APISIX will go to the specified directory to read the configuration if the user has configured the environment variable when reading the configuration.

I think it's a good idea. Maybe the environment variable can be called `APISIX_PROFILE_PATH`.
Now we can use an environment variable called [APISIX_PROFILE](https://apisix.apache.org/docs/apisix/profile/). It can deal with the situation of using different config files by the environment variable.

**Comment by wolgod** [comment]
Now I soft-link the config.yaml in a directory to the default path, so that the hot update can be achieved by mounting the config.yaml in the directory through the configmap

```
RUN mkdir -p /usr/local/apisix/conf/config \
&& mv /usr/local/apisix/conf/config.yaml  /usr/local/apisix/conf/config/config.yaml \
&& ln -s /usr/local/apisix/conf/config/config.yaml   /usr/local/apisix/conf/config.yaml \
```
