### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by loveyang2012** [apache/apisix#8049]
### Description

前辈们，咨询个问题，nginx 可以实现根据url转发请求到不同的后端，apisix怎么实现呢？
比如这样
![image](https://user-images.githubusercontent.com/24237714/194736928-f1239244-cf6d-4c49-bf9b-00c27090d34d.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
You can create a route. https://apisix.apache.org/docs/apisix/terminology/route/
