### ISSUE TITLE
bug: http_to_https

### ISSUE THREAD

**Issue by myp0627** [apache/apisix#8054]
### Current Behavior

eg: 
config.yaml：
apisix:
  ssl:
    listen_port: 
            - 443
            - 9443
router:
  "plugins": {
    "redirect": {
      "http_to_https": true
    }
  }

### Expected Behavior

http:xxx.xxx.com will convert to https:xxx.xxx.com

### Error Logs

2022/10/09 15:54:20 [error] 126329#126329: *790 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/redirect.lua:197: attempt to compare number with table
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/plugins/redirect.lua: in function 'phase_func'
	/usr/local/apisix/apisix/plugin.lua:897: in function 'run_plugin'
	/usr/local/apisix/apisix/init.lua:435: in function 'http_access_phase'

### Steps to Reproduce

/usr/local/apisix/apisix/plugins/redirect.lua :197：
if ret_port == nil or ret_port == 443 or ret_port <= 0 or ret_port > 65535  then

ret_port will is table 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
There doesn't have a field which name is listen_port. Please see the confit-default.yaml as the reference.

**Comment by tokers** [comment]
There doesn't have a field which name is listen_port. Please see the confit-default.yaml as the reference.

**Comment by tzssangglass** [comment]
pls try with

```
   apisix:
     ssl:
       enable: true
       listen:
         - port: 443
         - port: 9443
```

**Comment by myp0627** [comment]
> 没有名称为listen_port 的字段。请参阅 confit-default.yaml 作为参考。

![image](https://user-images.githubusercontent.com/20380172/194793517-06d267ec-7d89-40ad-99a7-20e0e28d2069.png)
thanks for the tip

**Comment by kellyseeme** [comment]
maybe the source docs is wrong：
[apisix docs](https://apisix.apache.org/zh/docs/apisix/2.15/FAQ/#%E5%9C%A8%E5%A4%84%E7%90%86-http-%E6%88%96-https-%E8%AF%B7%E6%B1%82%E6%97%B6%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-apache-apisix-%E6%9D%A5%E7%9B%91%E5%90%AC%E5%A4%9A%E4%B8%AA%E7%AB%AF%E5%8F%A3)
  ssl:
    listen_port:
      - 9443
      - 9444
      - 9445

**Comment by tzssangglass** [comment]
> maybe the source docs is wrong：
> [apisix docs](https://apisix.apache.org/zh/docs/apisix/2.15/FAQ/#%E5%9C%A8%E5%A4%84%E7%90%86-http-%E6%88%96-https-%E8%AF%B7%E6%B1%82%E6%97%B6%E6%88%91%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE-apache-apisix-%E6%9D%A5%E7%9B%91%E5%90%AC%E5%A4%9A%E4%B8%AA%E7%AB%AF%E5%8F%A3)
> ssl:
> listen_port:
> - 9443
> - 9444
> - 9445

The connection document you posted is v2.15, and listen_port was completely removed after the 2.15 release.
