### ISSUE TITLE
help request: how to set the backlog parameter

### ISSUE THREAD

**Issue by Drery** [apache/apisix#8055]
### Description

I want to know how to set the nginx backlog parameter.
Nginx is set in the `listen` statement: `listen  80  backlog=1024`.
But apisix can only set listen port such as:`node_listen: 80`.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
PR is welcome to supporting it.

**Comment by tokers** [comment]
PR is welcome to support it.

**Comment by monkeyDluffy6017** [comment]
What @tokers suggested is that if you could submit a pr to put `backlog` into `config-default.yaml`.
But if you just want to add `backlog` for yourself, you could try to modify the template file `apisix/cli/ngx_tpl.lua`.

**Comment by Drery** [comment]
Thanks, I'll give it a try, and in the meantime I'd like to ask if there are any other configurations that can cause connections to pile up。

**Comment by monkeyDluffy6017** [comment]
What do you mean by `connections pile up`, could you show an example?

**Comment by Drery** [comment]
The problem is that when a client accesses the backend API through our gateway, the error code 499 is often reported.  The cause is that the client times out for 10s. If no response is received for 10s, the client is disconnected. However, the weirdest thing is that the client sends the request at 10:00:00. After viewing the logs of the gateway and backend service, the request is received at 10:00:10, which is 10 seconds later. Because the access is from the Intranet, network problems can be eliminated. So I want to ask, what might be the cause of this situation?

问题是这样的，有客户端通过我们网关访问后端接口时，经常报499错误码。原因是客户端设置了10s超时，超过10s未收到响应断开了。但是诡异的地方在于，客户端是10:00:00分发起的请求，而查看网关及后端接口的日志发现，收到请求的时间是在10:00:10，也就是10s以后，因为都是内网访问，基本可以排除网络问题，因此就怀疑请求是在网关这里被堆积了。所以想问下，这种情况可能会是什么原因导致的？

**Comment by tzssangglass** [comment]
> 客户端是10:00:00分发起的请求，而查看网关及后端接口的日志发现，收到请求的时间是在10:00:10

Is the client time strictly consistent with the server time?

**Comment by Drery** [comment]
It's completely consistent.
And The request_time field in the nginx log is 0.

**Comment by tzssangglass** [comment]
> And The request_time field in the nginx log is 0.

`request_time` is only the time for nginx to process the request, and does not include the transmission time for the network to send data to the client, if the network condition is poor.

> 因此就怀疑请求是在网关这里被堆积了。所以想问下，这种情况可能会是什么原因导致的？

You need to verify if the request is stacked first. You can grab network packets to see how long it takes to establish the link, Nginx's handshake queue.

**Comment by panhow** [comment]
You can check the metric `node_netstat_TcpExt_ListenOverflows`,if `node-exporter` was installed, to find out do you need to increase the listen backlog.
