### ISSUE TITLE
help request:  why cors processing in header_filter phase?

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#8066]
### Description

Why is the main logic processing of cors in the header_filter phase?  Why can't you just do it in the rewrite phase? If so, there is no need to proxy the request to upstream.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
> If so, there is no need to proxy the request to upstream.

Why? Where is the HTTP response from?

**Comment by zuiyangqingzhou** [comment]
> > If so, there is no need to proxy the request to upstream.
> 
> Why? Where is the HTTP response from?

I understand that cors processing does not require an upstream response, 
or I may have misunderstood, you can correct me

**Comment by monkeyDluffy6017** [comment]
@zuiyangqingzhou What you said is right, and i checked the code, find that the `option` request will break the `rewrite phase`, it won't access the upstream.
https://github.com/apache/apisix/blob/c25e1123d90b9b9926de002b9a472740f1bbbbb0/apisix/plugins/cors.lua#L293

**Comment by kingluo** [comment]
@zuiyangqingzhou cors plugin is used to set response header, so it's natural to use in header filter phase.

**Comment by zuiyangqingzhou** [comment]
OK，got it , thank you all
