### ISSUE TITLE
feat: As a user, I want to Forward Proxy https with apisix

### ISSUE THREAD

**Issue by OnlyPiglet** [apache/apisix#8076]
### Description

if apisix can support forward proxy for https on 7 layer, the request like this

inner net server   http <-    -> http  apisix gateway   https <- -> https internet server

like this nginx module https://github.com/chobits/ngx_http_proxy_connect_module

**Comment by OnlyPiglet** [comment]
has find a plugin proxy_rewrite and upstream_schema can change the protocol schema, thanks a lot

**Comment by spacewander** [comment]
> has find a plugin proxy_rewrite and upstream_schema can change the protocol schema, thanks a lot

Consider solved. Feel free to reopen it if needed.

**Comment by spacewander** [comment]
We can use an external domain in the upstream. It doesn't work like a forward proxy with HTTP CONNECT, but can solve the problem described in the issue.
