### ISSUE TITLE
help request: I want to display my custom plugin on the dashboard. What should I do?

### ISSUE THREAD

**Issue by wulinghui** [apache/apisix#8077]
### Description

我写了一个插件。功能都ok啦。我想要再
`http://xxxx:9000/plugin/market` 的页面上展示我自定义的页面改怎么添加数据？  
同时我看接口返回里面没有对应的icon图标，这是用过name对应的吗？

![image](https://user-images.githubusercontent.com/36905201/195246351-eb34f257-5cbc-4da2-a4ce-355acf2f423b.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@wulinghui  Hi, you can see https://apisix.apache.org/zh/docs/dashboard/FAQ/ ,rule 4 may help you.

**Comment by wulinghui** [comment]
感谢您的回复，我看并操作。 
但是在第3步 查看  [资料](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory)
报404，我看该项目其他的资料也没有找到有用的信息。 
能告诉我最新的文档地址吗?

**Comment by Hazel6869** [comment]
> 感谢您的回复，我看并操作。 但是在第3步 查看 [(https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory)](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory) 报404，我看该项目其他的资料也没有找到有用的信息。 能告诉我最新的文档地址吗?

Wait a minute, i'll get back to you.

**Comment by Hazel6869** [comment]
> 感谢您的回复，我看并操作。 但是在第3步 查看 [(https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory)](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory) 报404，我看该项目其他的资料也没有找到有用的信息。 能告诉我最新的文档地址吗?

you can get the file deleted from this link https://github.com/apache/apisix-dashboard/pull/2183/files#diff-c860e93522cea33f5403823259559216006356caf830a8abe88e2f9b9a42193f

**Comment by Hazel6869** [comment]
> 感谢您的回复，我看并操作。 但是在第3步 查看 [(https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory)](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory) 报404，我看该项目其他的资料也没有找到有用的信息。 能告诉我最新的文档地址吗?

In order to solve your problem, you can log in to your docker and go to the "/usr/local/apisix-dashboard" directory,  which is your working directory.

**Comment by Hazel6869** [comment]
> 感谢您的回复，我看并操作。 但是在第3步 查看 [(https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory)](https://github.com/apache/apisix-dashboard/blob/master/docs/en/latest/deploy.md#working-directory) 报404，我看该项目其他的资料也没有找到有用的信息。 能告诉我最新的文档地址吗?

I will fix the link.

**Comment by wulinghui** [comment]
![image](https://user-images.githubusercontent.com/36905201/195492893-95f89ac8-6e5c-4da1-8258-27285aa44151.png)
谢谢您的回复，我看到并且解决啦。
但是新的问题是里面的icon图标如何自定义呢？

**Comment by Hazel6869** [comment]
> ![image](https://user-images.githubusercontent.com/36905201/195492893-95f89ac8-6e5c-4da1-8258-27285aa44151.png) 谢谢您的回复，我看到并且解决啦。 但是新的问题是里面的icon图标如何自定义呢？

you can 
reference  https://github.com/apache/apisix-dashboard/blob/master/web/src/components/Plugin/data.tsx#L21

**Comment by wulinghui** [comment]
ok，谢谢您的回复。
