### ISSUE TITLE
help request: About Batch Request Always got 404 error

### ISSUE THREAD

**Issue by Winniepoom** [apache/apisix#8078]
### Description

Hello I'm Very newbie into API Gateway. So my main goal are sending 1 request /command in to multiple services. I heard batch request might be my solution . I follow this [docs   ](https://apisix.apache.org/docs/apisix/plugins/batch-requests/) and always got 404 error any idea ?
Thank You.

My Environment on Docker OS ubuntu 20.04
- apisix dashbord 2.13
- apisix 2.15
- etcd 3.4.15
- nginx 1.19.0

Step to reproduce  

```
 curl http://mylocalip:9080/apisix/admin/routes/br -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/apisix/batch-requests",
    "plugins": {
        "public-api": {}
    }
}'
```

```
curl --location --request POST 'http://mylocalip:9080/apisix/batch-requests' \
--header 'Content-Type: application/json' \
--data '{
    "headers": {
        "Content-Type": "application/json",
        "admin-jwt":"xxxx"
    },
    "timeout": 500,
    "pipeline": [
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test"
        },
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test2"
        }
    ]
},
```

my respond
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@Winniepoom  Hi, you need to config the plugin like this first, do you do it?

**Comment by Winniepoom** [comment]
Ohh I'm not Config that yet.  Let me try that a moment.

> @Winniepoom Hi, you need to config the plugin like this first, do you do it?
> 
> curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/batch-requests -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d ' { "max_body_size": 4194304 }'

Ohh I'm not Config that yet.  Let me try that a moment.

**Comment by Winniepoom** [comment]
Too bad. Still got error 404 .
But when I try to config route in my dashboard it throw an waring like this

**Comment by Hazel6869** [comment]
> > @Winniepoom Hi, you need to config the plugin like this first, do you do it?
> > curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/batch-requests -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d ' { "max_body_size": 4194304 }'
> 
> Ohh I'm not Config that yet. Let me try that a moment.

if you have added the batch-requests  in the  config.yaml ?

**Comment by Hazel6869** [comment]
> added and still got an error. ![image](https://user-images.githubusercontent.com/107398226/195297229-6038f854-505f-448c-ab3d-7568a0b0c04d.png)

If you just added it, you need to restart apisix

**Comment by Hazel6869** [comment]
> Below is the result of my execution, you can see

➜  apisix-docker git:(master) ✗ curl http://127.0.0.1:9080/apisix/admin/routes/br \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/batch-requests",
    "plugins": {
        "public-api": {
            "uri": "/apisix/batch-requests"
        }
    }
}'
{"action":"set","node":{"value":{"update_time":1665565821,"create_time":1665562773,"uri":"\/batch-requests","priority":0,"status":1,"id":"br","plugins":{"public-api":{"uri":"\/apisix\/batch-requests"}}},"key":"\/apisix\/routes\/br"}}
➜  apisix-docker git:(master) ✗ curl --location --request POST 'http://127.0.0.1:9080/apisix/batch-requests' \
--header 'Content-Type: application/json' \
--data '{
    "headers": {
        "Content-Type": "application/json",
        "admin-jwt":"xxxx"
    },
    "timeout": 500,
    "pipeline": [
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test"
        },
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test2"
        }
    ]
}'
[{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:10:34 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404},{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:10:34 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404}]
➜  apisix-docker git:(master) ✗ curl --location --request POST 'http://127.0.0.1:9080/apisix/batch-requests' \
--header 'Content-Type: application/json' \
--data '{
    "headers": {
        "Content-Type": "application/json",
        "admin-jwt":"xxxx"
    },
    "timeout": 500,
    "pipeline": [
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test"
        },
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test2"
        }
    ]
}'
[{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:10:45 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404},{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:10:45 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404}]
➜  apisix-docker git:(master) ✗

**Comment by Winniepoom** [comment]
When I try to reproduce like you I got another error "404 Route Nit Found"
![image](https://user-images.githubusercontent.com/107398226/195305575-31289d33-d8e5-48f1-82f7-85e0fa9be1a4.png)

> root@apisix:/home/apisix# curl http://192.168.32.158:9080/apisix/admin/routes/br -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> > {
> >     "uri": "/batch-requests",
> >     "plugins": {
> >         "public-api": {
> >             "uri": "/apisix/batch-requests"
> >         }
> >     }
> > }'
> {"node":{"key":"\/apisix\/routes\/br","value":{"plugins":{"public-api":{"uri":"\/apisix\/batch-requests"}},"update_time":1665566648,"id":"br","uri":"\/batch-requests","priority":0,"status":1,"create_time":1665566648}},"action":"set"}
> root@apisix:/home/apisix# curl --location --request POST 'http://192.168.32.158:9080/apisix/batch-requests' \
> > --header 'Content-Type: application/json' \
> > --data '{
> >     "headers": {
> >         "Content-Type": "application/json",
> >         "admin-jwt":"xxxx"
> >     },
> >     "timeout": 500,
> >     "pipeline": [
> >         {
> >             "method": "POST",
> >             "path": "/community.GiftSrv/GetGifts",
> >             "body": "test"
> >         },
> >         {
> >             "method": "POST",
> >             "path": "/community.GiftSrv/GetGifts",
> >             "body": "test2"
> >         }
> >     ]
> > }'
> {"error_msg":"404 Route Not Found"}
> root@apisix:/home/apisix#

**Comment by Hazel6869** [comment]
> > @Winniepoom  Below is the result of my execution, you can see
> 
> ```
> ➜  apisix-docker git:(master) ✗ curl http://127.0.0.1:9080/apisix/admin/routes/1 \
> -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "uri": "/apisix/batch-requests",
>     "plugins": {
>         "public-api": {}
>     }
> }'
> {"action":"set","node":{"value":{"update_time":1665568096,"create_time":1665568096,"uri":"\/apisix\/batch-requests","priority":0,"status":1,"id":"1","plugins":{"public-api":{}}},"key":"\/apisix\/routes\/1"}}
> ➜  apisix-docker git:(master) ✗
> ➜  apisix-docker git:(master) ✗
> ➜  apisix-docker git:(master) ✗ curl --location --request POST 'http://127.0.0.1:9080/apisix/batch-requests' \
> --header 'Content-Type: application/json' \
> --data '{
>     "headers": {
>         "Content-Type": "application/json",
>         "admin-jwt":"xxxx"
>     },
>     "timeout": 500,
>     "pipeline": [
>         {
>             "method": "POST",
>             "path": "/community.GiftSrv/GetGifts",
>             "body": "test"
>         },
>         {
>             "method": "POST",
>             "path": "/community.GiftSrv/GetGifts",
>             "body": "test2"
>         }
>     ]
> }'
> [{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:48:50 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404},{"headers":{"Connection":"keep-alive","Content-Type":"text\/plain; charset=utf-8","Server":"APISIX\/2.15.0","Transfer-Encoding":"chunked","Date":"Wed, 12 Oct 2022 09:48:50 GMT"},"reason":"Not Found","body":"{\"error_msg\":\"404 Route Not Found\"}\n","status":404}]
> ➜  apisix-docker git:(master) ✗
> ```

@Winniepoom  sorry,  there is a problem with the code in my previous post, you can try again according to what I wrote

**Comment by Winniepoom** [comment]
```
root@apisix:/home/apisix/apisix-docker/example# curl http://192.168.32.158:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/apisix/batch-requests",
    "plugins": {
        "public-api": {}
    }
}'

{"action":"set","node":{"value":{"uri":"\/apisix\/batch-requests","priority":0,"plugins":{"public-api":{}},"update_time":1665568453,"id":"1","create_time":1665568361,"status":1},"key":"\/apisix\/routes\/1"}}


root@apisix:/home/apisix/apisix-docker/example# curl --location --request POST 'http://192.168.32.158:9080/apisix/batch-requests' --header 'Content-Type: application/json' --data '{
    "headers": {
        "Content-Type": "application/json",
        "admin-jwt":"xxxx"
    },
    "timeout": 500,
    "pipeline": [
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test"
        },
        {
            "method": "POST",
            "path": "/community.GiftSrv/GetGifts",
            "body": "test2"
        }
    ]
}'


<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
</body>
</html>
root@apisix:/home/apisix/apisix-docker/example#
```

Sorry But still don't work for me .

**Comment by Hazel6869** [comment]
> 

when i delete the batch-request  from my config, I reproduced your error.  I found the log error in my  log file.  So you can look at your log
![gcOqVNodOI](https://user-images.githubusercontent.com/30279880/195314841-411cd224-9e22-4923-b4da-638e5b512b6b.jpg)
![048AJXbeBm](https://user-images.githubusercontent.com/30279880/195314882-886b155c-86c8-4184-8f85-0881694ade5e.jpg)

**Comment by Winniepoom** [comment]
Here are my error log .
![image](https://user-images.githubusercontent.com/107398226/195317921-51595d43-0713-453f-8f5e-832e5c8f551e.png)

**Comment by Hazel6869** [comment]
> Here are my error log . ![image](https://user-images.githubusercontent.com/107398226/195317921-51595d43-0713-453f-8f5e-832e5c8f551e.png)

Can you give me the complete log file?

**Comment by Hazel6869** [comment]
> Here are my error log . ![image](https://user-images.githubusercontent.com/107398226/195317921-51595d43-0713-453f-8f5e-832e5c8f551e.png)
When I delete the batch-request from my config, I reproduced your error. I find the same error content with you  in my log file,  can you find the content "failed to load plugin .." ?

![image](https://user-images.githubusercontent.com/30279880/195477347-435bd9aa-5c9d-4485-9f2f-693c2e61cd60.png)

**Comment by tokers** [comment]
> /apisix/batch-requests

Are you sure the batch-requests plugin is enabled?

**Comment by Winniepoom** [comment]
Sorry for a newbie question but where are my conf/config.yaml ? I can't find my "conf" directory.

**Comment by Hazel6869** [comment]
> 

apisix/apisix-docker/example/apisix_conf/config.yaml

**Comment by Hazel6869** [comment]
> apisix/apisix-docker/example/apisix_conf/config.yaml



> Sorry for a newbie question but where are my conf/config.yaml ? I can't find my "conf" directory.



> Sorry for a newbie question but where are my conf/config.yaml ? I can't find my "conf" directory.

apisix/apisix-docker/example/apisix_conf/config.yaml

**Comment by Winniepoom** [comment]
Thank a lot guys

**Comment by hf400159** [comment]
https://apisix.apache.org/docs/apisix/plugins/batch-requests/#enabling-the-plugin  @Winniepoom  By the way, have you seen this title? From the results, you did not notice the title. Can you help optimize this document?
