### ISSUE TITLE
docs: Recommended to provide some examples of best practices, especially plugins

### ISSUE THREAD

**Issue by think4code** [apache/apisix#8080]
### Description

apisix功能强大，插件丰富。对于初次使用者来说，学习怎样配置需要很大的精力。
针对常见的使用场景，希望能够提供一些最佳实践，帮助初学者尽快落地使用。

**Comment by Hazel6869** [comment]
> 

Hi, does the official documentation not meet your needs?

**Comment by zhangyuthink** [comment]
> > 
> 
> @zhangyuthink Hi, does the official documentation not meet your needs?

官方文档中未找到我想要的，可以考虑增加如下内容。
最佳实践：
1、限制某消费者只允许调用部分路由
a)配置消费者，开启base_auth插件
b)配置上游、服务
c)配置路由，开启base_auth插件、consumer-restriction插件

**Comment by Hazel6869** [comment]
> 

ok, we will notice it.  @tzssangglass @SylviaBABY please pay attention.

**Comment by SylviaBABY** [comment]
> > > 
> > 
> > 
> > @zhangyuthink Hi, does the official documentation not meet your needs?
> 
> 官方文档中未找到我想要的，可以考虑增加如下内容。 最佳实践： 1、限制某消费者只允许调用部分路由 a)配置消费者，开启base_auth插件 b)配置上游、服务 c)配置路由，开启base_auth插件、consumer-restriction插件

Hi @zhangyuthink, Thanks for the comments. I think there are these related best practices in the community at present, but because of energy problems, they have not appeared in the official documents temporarily.

We will gradually improve the official documentation in the future, and thank you for your comments on the use of APISIXX. Similarly, we look forward to your contributions to these issues, giving some best practice scenarios from a user perspective^^

**Comment by hf400159** [comment]
APISIX test cases also include many examples. You can also check https://github.com/apache/apisix/blob/master/t/

**Comment by zhangyuthink** [comment]
> > > > 
> > > 
> > > 
> > > @zhangyuthink Hi, does the official documentation not meet your needs?
> > 
> > 
> > 官方文档中未找到我想要的，可以考虑增加如下内容。 最佳实践： 1、限制某消费者只允许调用部分路由 a)配置消费者，开启base_auth插件 b)配置上游、服务 c)配置路由，开启base_auth插件、consumer-restriction插件
> 
> Hi @zhangyuthink, thanks for the comments. I think there are these related best practices in the community at present, but because of energy problems, they have not appeared in the official documents temporarily.
> 
> We will gradually improve the official documentation in the future, and thank you for your comments on using APISIX. Similarly, we look forward to your contributions to these issues, giving some best practice scenarios from a user perspective^^

If I want to provide some best practices, what should I do?

**Comment by SylviaBABY** [comment]
> > > > > 
> > > > 
> > > > 
> > > > @zhangyuthink Hi, does the official documentation not meet your needs?
> > > 
> > > 
> > > 官方文档中未找到我想要的，可以考虑增加如下内容。 最佳实践： 1、限制某消费者只允许调用部分路由 a)配置消费者，开启base_auth插件 b)配置上游、服务 c)配置路由，开启base_auth插件、consumer-restriction插件
> > 
> > 
> > Hi @zhangyuthink, thanks for the comments. I think there are these related best practices in the community at present, but because of energy problems, they have not appeared in the official documents temporarily.
> > We will gradually improve the official documentation in the future, and thank you for your comments on using APISIX. Similarly, we look forward to your contributions to these issues, giving some best practice scenarios from a user perspective^^
> 
> If I want to provide some best practices, what should I do?

That's Great! You can add the details of the best practice scenarios you are involved into the corresponding plugin introduction document. The file path is shown below.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/39793568/195740472-3cad18aa-d03b-4eb1-aade-da99418c9c59.png">

And you can add such ##Best Practice title at the end of the document and put your contents
