### ISSUE TITLE
help request:  access static file by custom nginx.conf but error

### ISSUE THREAD

**Issue by wallishuang** [apache/apisix#8081]
### Description

Hi 
I folllow the doc [https://apisix.apache.org/docs/apisix/2.15/customize-nginx-configuration/]  to access static resource but occur error as following. and I try the other way like proxy cache [ https://github.com/apache/apisix/issues/3390]. it occurs the same error. It's make me confused, please help.

<html>

<head>
	<title>400 Request Header Or Cookie Too Large</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<center>Request Header Or Cookie Too Large</center>
	<hr>
	<center>openresty</center>
</body>

</html>

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): docker ,
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):Linux apisix-cb97c8cc7-cj2s5 5.4.0-125-generic #141~18.04.1-Ubuntu SMP Thu Aug 11 20:15:56 UTC 2022 x86_64 Linux
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): docker.io/bitnami/etcd:3.5.4-debian-11-r14
- APISIX Dashboard version, if relevant:  apache/apisix-dashboard:2.13-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Please provide details about how you configure the proxy-cache plugin and how you send a request which got such a status code.

**Comment by tzssangglass** [comment]
try to add the `large_client_header_buffers 4 16k;` directive to the `http_server_location_configuration_snippet` by custom nginx.conf, ref: http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers

**Comment by elkh510** [comment]
hi
try with this
no luck 
https://github.com/apache/apisix/issues/8081#issuecomment-1276959203
