### ISSUE TITLE
bug: http://test.com:443 is not supported

### ISSUE THREAD

**Issue by wbkys** [apache/apisix#8082]
### Current Behavior

400 Bad Request
The plain HTTP request was sent to HTTPS port
openresty

而且还爆了一个原生的错误出来 openresty 关键词 本该不会显示

### Steps to Reproduce

访问 http://test.com:443 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by OnlyPiglet** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/46953658/195475832-eb346179-c2ee-43b8-9b9f-e7fa840679af.png">
the error info show you have send a http request to https,you may should change the protocol to https like **https://test.com:443**
