### ISSUE TITLE
Using Redis as a pub/sub system for APISIX gateway

### ISSUE THREAD

**Issue by sangvhh** [apache/apisix#8083]
### Description

In the document, the part of pub/sub system only have Apache Kafka but not have Redis. Can I request the configuration for Redis pub/sub.

**Comment by Hazel6869** [comment]
> 
Can you give more information about your question?  such as, the document link？

**Comment by Hazel6869** [comment]
> @Hazel6869 You can refer to this document link for more information. https://apisix.apache.org/docs/apisix/pubsub/kafka/

Yes, we currently do not support redis for pub/sub.

**Comment by sangvhh** [comment]
I hope you and your team will build module redis pub/sub for apisix in the future. Besides, can you give me documents about publish/subscribe message to Kafka as pub/sub system. For example: API document, ...

>> @Hazel6869 You can refer to this document link for more information. https://apisix.apache.org/docs/apisix/pubsub/kafka/
> 
> Yes, we currently do not support redis for pub/sub.

**Comment by sangvhh** [comment]
2022/10/13 13:57:57 [error] 117697#117697: *73208646 [lua] kafka.lua:58: http_access_phase(): failed to initialize pubsub 
 module, err: bad "upgrade" request header: nil, client: 127.0.0.1, server: _, request: "GET /kafka HTTP/1.1", host: "127.0.0.1"
When I curl API  **curl -X GET http://127.0.0.1/kafka**, I receive these logs. Can you help me solve it?

**Comment by Hazel6869** [comment]
> > 2022/10/13 13:57:57 [error] 117697#117697: *73208646 [lua] kafka.lua:58: http_access_phase(): failed to initialize pubsub
> > module, err: bad "upgrade" request header: nil, client: 127.0.0.1, server: _, request: "GET /kafka HTTP/1.1", host: "127.0.0.1"
> 
> When I curl API **curl -X GET http://127.0.0.1/kafka**, I receive these logs. Can you help me solve it?

you need  to do these two steps first.

**Comment by sangvhh** [comment]
> you need to do these two steps first.
> 
> First, create an instance of the pubsub module, which is provided in the core package. Then, an instance of the Apache Kafka client is created and omitted code here.
> 
> Next, add the command registered in the protocol definition above to the pubsub instance, which will provide a callback function that provides the parameters parsed from the communication protocol, in which the developer needs to call the kafka client to get the data and return it to the pubsub module as the function return value.
How to create an instance of the pubsub module? I found related function in file **pubsub.lua**. Can I do it by APIs calling or source code editing?

**Comment by Hazel6869** [comment]
> > you need to do these two steps first.
> > First, create an instance of the pubsub module, which is provided in the core package. Then, an instance of the Apache Kafka client is created and omitted code here.
> > Next, add the command registered in the protocol definition above to the pubsub instance, which will provide a callback function that provides the parameters parsed from the communication protocol, in which the developer needs to call the kafka client to get the data and return it to the pubsub module as the function return value.
> 
> How to create an instance of the pubsub module? I found related function in file **pubsub.lua**. Can I do it by APIs calling or source code editing?

sorry, there is no such way as an api.
