### ISSUE TITLE
feat: opentelemetry plugin can set http status code to span tag by default

### ISSUE THREAD

**Issue by ZhangShangyu** [apache/apisix#8084]
### Description

the opentelemetry plugin now set http status code to span tag only when upstream response status is greater equals than 500.
<img width="737" alt="image" src="https://user-images.githubusercontent.com/15957047/195556460-620ea171-2adf-436a-a8d9-8ea94bdd936e.png">

can set http status code to span tag by default instead of only when upstream greater equals than 500?
to solve these cases:
* can filter trace by http code tag conveniently
* some plugin like limit-count will not have stream response status, if rate limit return 503, then also can show the 503 tag in span

**Comment by tokers** [comment]
Or this can be a flag?

**Comment by ZhangShangyu** [comment]
i try to add status in additional_attributes config, but there is an error happened

apisix.yaml:
```
opentelemetry:
    sampler:
      name: always_on
    additional_attributes:
      - route_id
      - status
```

apisix error log:
```
2022/10/13 08:02:47 [error] 133#133: *402129 lua entry thread aborted: runtime error: ...deps/share/lua/5.1/opentelemetry/trace/exporter/otlp.lua:67: bad argument #2 to 'encode' (string expected for field 'string_value', got number)
stack traceback:
coroutine 0:
	[C]: in function 'encode'
	...deps/share/lua/5.1/opentelemetry/trace/exporter/otlp.lua:67: in function 'export_spans'
	...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:18: in function 'process_batches'
	...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:46: in function <...are/lua/5.1/opentelemetry/trace/batch_span_processor.lua:29>, context: ngx.timer, client: 172.17.0.1, server: 0.0.0.0:24221
```

apisix version: 2.13.2

**Comment by spacewander** [comment]
> 2022/10/13 08:02:47 [error] 133#133: *402129 lua entry thread aborted: runtime error: ...deps/share/lua/5.1/opentelemetry/trace/exporter/otlp.lua:67: bad argument #2 to 'encode' (string expected for field 'string_value', got number)

We need to ensure the value has string type.

@soulbird 
Would you give it a try?

**Comment by soulbird** [comment]
`status` is of type number, not string.
In addition, the variables in the `additional_attributes` configuration are parsed during the `rewrite phase`, so configuring "status" here will not get the result you want, because APISIX has not received a response yet.

**Comment by ZhangShangyu** [comment]
thanks

**Comment by soulbird** [comment]
Not yet. Maybe we can make some adjustments to support adding some response-related attributes to spans. cc @bzp2010
