### ISSUE TITLE
http_ssl_phase(): failed to fetch ssl config: failed to find SNI: 

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#8086]
### Current Behavior

5649#5649: *1508782 [lua] init.lua:178: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 64.62.197.223, server: 0.0.0.0:443

### Steps to Reproduce

http_ssl_phase(): failed to fetch ssl config: failed to find SNI: 

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Please provide steps to reproduce

**Comment by lifeblood** [comment]
![image](https://user-images.githubusercontent.com/3621748/195634832-f30d4190-26df-4974-a10a-05ccf8af0305.png)

**Comment by tzssangglass** [comment]
Usually this is because the certificate corresponding to the Conmmon Name cannot be found based on the SNI passed by the client. 

You need to provide the packet capture data for the client request so that I can see what SNI the client is actually sending.

**Comment by zhendongcmss** [comment]
Configurate a default SNI in config-default.yaml

**Comment by hellojph** [comment]
I have the same problem;
I use images (**apache/apisix:2.15.0-centos** and **apache/apisix:2.15.0-alpine**) to deploy in K8S.
log:
2022/10/18 02:46:29 [error] 50#50: *51009508 [lua] init.lua:172: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 10.11.0.126, server: 0.0.0.0:9443

**Comment by tzssangglass** [comment]
Can you provide APISIX with the network packet data to accept this request? Because you are deployed in k8s, we want to make sure that

1. APISIX received the SNI from the client (to confirm that k8s' network facilities forwarded the SNI)
2. what is the SNI received by APISIX? Is there an SSL object configured for the corresponding SNI.
