### ISSUE TITLE
bug: Invalid filter with response-rewrite in apache/apisix:2.99.0-debian

### ISSUE THREAD

**Issue by chyoong** [apache/apisix#8087]
### Current Behavior

Hi, I would also like to use nginx sub_filter in apisix, but it still doesn't work when I use it in apache/apisix:2.99.0-debian，and I see an identical issue and have been merged，there https://github.com/apache/apisix/issues/5451

### Expected Behavior

Before content:
```html
<head>
    <title>test</title>
    <meta charset="utf-8">
</head>
```

ideally, use the content after `filter`:
```html
<head>
    <title>test</title>
    <meta charset="utf-8">
    <script>console.log(1)</script>
</head>
```

However, it does not take effect

### Steps to Reproduce

1. Use docker-compose deployment
2. In the `plugin/market` path, enable the `response-rewrite` plugin
3. configuration parameters are as follows
```json
{
  "disable": false,
  "filters": [
    {
      "regex": "</head>",
      "replace": "<script>console.log(1)</script></head>",
      "scope": "global"
    }
  ],
  "headers": {
    "set": {
      "x-powered-by": "",
      "x-server-balancer_addr": "$balancer_ip:$balancer_port"
    }
  },
  "vars": [
    [
      "status",
      "==",
      200
    ],
    [
      "content-type",
      "==",
      "text/html; charset=utf-8"
    ]
  ]
}
```

### Environment

- APISIX version (run `apisix version`): apache/apisix:2.99.0-debian
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:2.13-alpine

**Comment by soulbird** [comment]
same as #7852

**Comment by mscb402** [comment]
Please read document https://apisix.apache.org/docs/apisix/terminology/plugin/#plugin-common-configuration 
Currently apisix only support request parameters, so your configuration is not right. You should remove condition on vars
```
"vars": [
    [
      "status",
      "==",
      200
    ],
    [
      "content-type",
      "==",
      "text/html; charset=utf-8"
    ]
  ]
```
to 
```
"var": []
```

**Comment by soulbird** [comment]
```
<head>
    <title>test</title>
    <meta charset="utf-8">
</head>
```
Can you give a full upstream response? Contains response headers and a response body.

**Comment by soulbird** [comment]
> t request parameters,

The response-rewrite plugin has already received the response when executing the `vars` expression, so it can contain some variables in the response, you can check this test case: https://github.com/apache/apisix/blob/master/ t/plugin/response-rewrite2.t#L236

**Comment by soulbird** [comment]
> Please read document https://apisix.apache.org/docs/apisix/terminology/plugin/#plugin-common-configuration Currently apisix only support request parameters, so your configuration is not right. You should remove condition on vars
> 
> ```
> "vars": [
>     [
>       "status",
>       "==",
>       200
>     ],
>     [
>       "content-type",
>       "==",
>       "text/html; charset=utf-8"
>     ]
>   ]
> ```
> 
> to
> 
> ```
> "var": []
> ```

The response-rewrite plugin has already received the response when executing the `vars` expression, so it can contain some variables in the response, you can check this test case: https://github.com/apache/apisix/blob/master/ t/plugin/response-rewrite2.t#L236
