### ISSUE TITLE
help request: when i use wss to connect socket.io ,i get error

### ISSUE THREAD

**Issue by jackyzhao001** [apache/apisix#8093]
### Description

hi friends:
 when i use wss to connect socket.io ,i get error,  "xhr poll error".

[upstream]:
![2e650555-1041-4841-9297-ce6de8b22bd3](https://user-images.githubusercontent.com/12294408/195874515-885e03a3-8992-4e67-a36c-21fcf57208c4.jpeg)

[router]:
![ccf7d063-640a-4223-9f09-28ded70340c6](https://user-images.githubusercontent.com/12294408/195874592-93014eb0-79ad-4394-84dc-c3391151079d.jpeg)

i use "ws" to connect ,it is ok !.
![92800c64-d6a3-4016-91dd-391905bed20a](https://user-images.githubusercontent.com/12294408/195875023-099aee92-d57b-40d6-94ba-7bdb333cd4cc.jpeg)

i use "wss" to connect, it is error !
![fa938fa3-67d6-43df-aed0-20291fb14059](https://user-images.githubusercontent.com/12294408/195875110-0a3f7a3d-d882-4e4c-9faf-0cf304ac6560.jpeg)

I don't know how to solve it, please  give some advice ,thanks

### Environment

- APISIX version (run `apisix version`):   2.14.1
- Operating system (run `uname -a`): ubuntu 20.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jackyzhao001** [comment]
[router]
![ccf7d063-640a-4223-9f09-28ded70340c6](https://user-images.githubusercontent.com/12294408/195876813-3823e551-3cb9-4e6c-8be1-fe53a1593fc5.jpeg)

**Comment by tzssangglass** [comment]
read my demo of wss: https://github.com/apache/apisix/issues/5103#issuecomment-926456343

**Comment by jackyzhao001** [comment]
> read my demo of wss: [#5103 (comment)](https://github.com/apache/apisix/issues/5103#issuecomment-926456343)

hi,thanks your help.  i used your way to  test websocket. that's okay ,It works fine.but ,my server is socket.io not webscoket. the socket.io server doesn't work that your way. I don't know why.

**Comment by jackyzhao001** [comment]
> read my demo of wss: [#5103 (comment)](https://github.com/apache/apisix/issues/5103#issuecomment-926456343)

![image](https://user-images.githubusercontent.com/12294408/196613850-9d4156c7-c706-4ffb-bac4-ebe3eb4b8934.png)
based on your example, websocket is okay, but socket.io is not okay.

**Comment by tzssangglass** [comment]
> based on your example, websocket is okay, but socket.io is not okay.

can you provider a demo of a server that builds by socket.io, you can put the demo in your repository and provide instructions on how to build and start the server so I can try it locally?

**Comment by tzssangglass** [comment]
And I need to make sure that the client can successfully request the server(build by socket.io) via wss without going through the APISIX proxy?

**Comment by jackyzhao001** [comment]
> And I need to make sure that the client can successfully request the server(build by socket.io) via wss without going through the APISIX proxy?

hi, the current work flow looks like this: 1) i can use client to request the server(build by socket.io)  via ws without going through the APISIX proxy,  2) i can not to request the server(build by socket.io) via wss . by default , the socket.io server not supported wss, it need config nginx to  support it  , but  i hope the APISIX config upstream to support it ,   I wish use APISIX 
Upstream  instead of nginx

**Comment by tzssangglass** [comment]
I know why you get 502. 

because in my demo, client --> APISIX was `wss` protocol, and APISIX to upstream was`wss` protocol too.

in your scenes, you need client --> APISIX use  `wss` protocol, and APISIX to upstream use was `ws` protocol.

if I make upstream `listen 1983;`, not `listen 1983 ssl`, I would get 502.

so you can config route like:

```
curl --location --request PUT 'http://127.0.0.1:9180/apisix/admin/routes/1' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "upstream": {
        "scheme": "http",
        "nodes": {
            "127.0.0.1:1983": 1
        },
        "type": "roundrobin"
    },
    "enable_websocket": true,
    "uri": "/websocket_handshake"
}'
```

use `"scheme": "http"` to make APISIX connect upstream without SSL, because you say that socket.io only can accept `ws`.

**Comment by jackyzhao001** [comment]
>  For this websocket example  , i try to config  useing  ["scheme": "http"]    ,  either ws or wss , It works fine
![image](https://user-images.githubusercontent.com/12294408/196852077-6da8872e-2609-42c4-9ef2-fbd0ac6e1462.png)
![image](https://user-images.githubusercontent.com/12294408/196852196-07fd8355-3e61-4383-989f-7164450fef77.png)
![image](https://user-images.githubusercontent.com/12294408/196852329-35ccd4d8-66c2-48a4-a588-defffb3d8e6c.png)

**Comment by jackyzhao001** [comment]
> I know why you get 502.
> 
> because in my demo, client --> APISIX was `wss` protocol, and APISIX to upstream was`wss` protocol too.
> 
> in your scenes, you need client --> APISIX use `wss` protocol, and APISIX to upstream use was `ws` protocol.
> 
> if I make upstream `listen 1983;`, not `listen 1983 ssl`, I would get 502.
> 
> so you can config route like:
> 
> ```
> curl --location --request PUT 'http://127.0.0.1:9180/apisix/admin/routes/1' \
> --header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "upstream": {
>         "scheme": "http",
>         "nodes": {
>             "127.0.0.1:1983": 1
>         },
>         "type": "roundrobin"
>     },
>     "enable_websocket": true,
>     "uri": "/websocket_handshake"
> }'
> ```
> 
> use `"scheme": "http"` to make APISIX connect upstream without SSL, because you say that socket.io only can accept `ws`.

but  for  socket.io server .it  can't work .   
upstream:[
{
  "nodes": [
    {
      "host": "172.21.32.15",
      "port": 7002,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "messenger-websocket",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}]

router:[
{
  "uri": "/*",
  "name": "messenger",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream_id": "430416363467571906",
  "labels": {
    "API_VERSION": "v1"
  },
  "enable_websocket": true,
  "status": 1
}
]

![image](https://user-images.githubusercontent.com/12294408/196853216-eb6f7757-a742-46aa-b0de-524936d28f86.png)
![image](https://user-images.githubusercontent.com/12294408/196853280-a2040f25-5713-4274-b671-1efb023e406e.png)

**Comment by jackyzhao001** [comment]
i direct connect  socket.io server  , it is ok . 
![image](https://user-images.githubusercontent.com/12294408/196853469-1953b6dd-12ff-4dab-a978-e8f2d1266784.png)

**Comment by tzssangglass** [comment]
> For this websocket example , i try to config useing ["scheme": "http"] , either ws or wss , It works fine

if your upstream is `listen 1983;` and use `["scheme": "http"]` 

- use` wss` means: client --> (wss) --> APISIX --> (ws) --> upstream(`listen 1983;`)
- use` ws` means: client --> (ws) --> APISIX --> (ws) --> upstream(`listen 1983;`)

**Comment by tzssangglass** [comment]
> but for socket.io server .it can't work .

I don't have any more ideas either, I don't know what special differences there are in socket.io. If you want me to continue investigating, you need to provide the socket.io server demo.

**Comment by jackyzhao001** [comment]
> > but for socket.io server .it can't work .
> 
> I don't have any more ideas either, I don't know what special differences there are in socket.io. If you want me to continue investigating, you need to provide the socket.io server demo.

ok, socket.io server demo -> https://gitee.com/jackyzhao001/test-socketio

i test this demo .it is ok. please try it.

**Comment by jackyzhao001** [comment]
> 
![image](https://user-images.githubusercontent.com/12294408/196912928-e50d0995-9369-45a8-9a70-cb437f0b135a.png)

**Comment by tzssangglass** [comment]
I investigated a bit and found some differences by grabbing the packets without looking deeper.

I saw this: https://socket.io/docs/v4/#what-socketio-is-not

**Comment by jackyzhao001** [comment]
> I investigated a bit and found some differences by grabbing the packets without looking deeper.
> 
> I saw this: https://socket.io/docs/v4/#what-socketio-is-not

thank you, they are not the same. so apisix doesn't support socket.io yet ?

**Comment by tzssangglass** [comment]
> thank you, they are not the same. so apisix doesn't support socket.io yet ?

I don't know how to support it now

**Comment by tokers** [comment]
@jackyzhao001 Is it possible for you to capture some WebSocket frame packets? So that we can analyze this problem further.

**Comment by tzssangglass** [comment]
> @jackyzhao001 Is it possible for you to capture some WebSocket frame packets? So that we can analyze this problem further.

I caught the package, we can look at it together when we have time.

**Comment by tzssangglass** [comment]
[sio-cap.zip](https://github.com/apache/apisix/files/9837861/sio-cap.zip)

sio-raw.cap is socket.io client connect socker.io server directly
sio-apisix is socket.io client connect socker.io server proxy by APISIX

**Comment by jackyzhao001** [comment]
@tzssangglass   hi， Is there a plan to fix this bug ？
