### ISSUE TITLE
help request: How to realize centralized identity authentication

### ISSUE THREAD

**Issue by think4code** [apache/apisix#8096]
### Description

我有一个需求，我想用apisix实现集中身份认证，用一个接口实现登录并保存客户信息，然后返回token给客户端，客户端可以携带token访问其他业务接口，apisix可根据token获取客户信息并追加到请求体或者请求头之中。

我看了官网有关“身份认证”的博客，没找到想要的答案。

这样要怎么实现呢？或者有其他能实现类似功能的方案吗？谢谢。

**Comment by tokers** [comment]
Can you try this https://apisix.apache.org/docs/apisix/plugins/forward-auth/?

**Comment by zhangyuthink** [comment]
> Can you try this https://apisix.apache.org/docs/apisix/plugins/forward-auth/?

如果用这个插件，每次访问接口都需要到“一个专门的外部服务中”去认证。能不能一次认证，然后将认证结果保存到apisix，后续别的接口可直接调用之前的认证结果

**Comment by hardme** [comment]
jwt？
