### ISSUE TITLE
help request:  What should I pay attention to when the open source OpenResty is converted to APISIX-OpenResty

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#8097]
### Description

At present, we are using the open source version of openresty/1.19.9.1, but some apisix plugins can only work in Apisix-OpenResty. 

I would like to ask what should be paid attention to when converting from the open source version of openresty to Apisix-OpenResty,  Or do you have any relevant experience to draw on.

Thank you very much.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
The APISIX-Base is designed to be API-compatible with the OpenResty which has the same version prefix. So the latest APISIX-Base should work as OpenResty 1.21.3. AFAIK, there is no limitation forcing users to switch to vanilla OpenResty.

You can consider it an upgrade of OpenResty.

**Comment by zuiyangqingzhou** [comment]
> AFAIK, there is no limitation forcing users to switch to vanilla OpenResty.

some plugins force the use of APISIX-Base, for example

https://github.com/apache/apisix/blob/master/apisix/plugins/gzip.lua#L103-L107

**Comment by zuiyangqingzhou** [comment]
> You can consider it an upgrade of OpenResty.

To double check,  the same version of open source OpenResty is fully compatible with APISIX-Base OpenResty, but APISIX-Base OpenResty has some enhancements

**Comment by spacewander** [comment]
One more thing - make sure your APISIX-Base version matches the APISIX version. The current dependency rule is:
https://github.com/api7/apisix-build-tools/blob/695c1ee5c84131efa796faa048829c7d9f63c585/package-apisix.sh#L28-L31

It would not be a problem if we install APISIX from the package manager as it is solved when packaging APISIX.
But for installing via source, we lack a tool to solve this dependency problem.

Maybe we can hardcode a dependency rule in `cli/ops.lua` for each version of APISIX.
