### ISSUE TITLE
bug:  apisix，500 error

### ISSUE THREAD

**Issue by jiahui1988** [apache/apisix#8100]
### Current Behavior

apisix版本：3.0.0-beta

背景： 开始开启了openidc 插件，然后关闭插件后，就开始报错。（报错日志显示openidc问题，但是此时插件实际上是全部关闭状态。而且配置中只存在此一条路由配置）
配置截图：
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/75962736/196117182-27faad35-3074-47e5-b69f-7b343cdd050a.png">

<img width="1347" alt="image" src="https://user-images.githubusercontent.com/75962736/196117717-a55767e9-554e-48a7-a755-5a29cee3ebd4.png">
访问情况：
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/75962736/196117832-17debdb3-efd0-42fd-b788-571a8d0853d7.png">

### Error Logs

2022/10/17 07:43:21 [error] 47#47: *7178173 [lua] openidc.lua:1475: authenticate(): request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 07:43:21 [error] 47#47: *7178173 [lua] openid-connect.lua:315: phase_func(): OIDC authentication failed: request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 07:43:21 [warn] 47#47: *7178173 [lua] plugin.lua:923: run_plugin(): openid-connect exits with http status code 500, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 07:43:21 [alert] 47#47: *7178174 ignoring stale global SSL error (SSL: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt), context: ngx.timer, client: 172.23.0.1, server: 0.0.0.0:9080

### Steps to Reproduce

1：配置路由
2： 开启openidc插件
3： 访问链接测试通过
4： 此时关闭openidc插件功能
5： 访问测试链接，失败（报错）

### Environment

apisix版本：3.0.0-beta
使用插件：openidc

**Comment by jiahui1988** [comment]
测试apisix最近的几个版本中军存在该问题。

**Comment by jiahui1988** [comment]
如果卸载apisix，在重新安装apisix，并配置openidc插件，第一次访问还是正常的。

**Comment by jiahui1988** [comment]
日志内容为：

2022/10/17 08:05:11 [error] 48#48: *51955 [lua] openidc.lua:1092: authenticate(): unhandled request to the redirect_uri: /anything/foo, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:11 [error] 48#48: *51955 [lua] openid-connect.lua:315: phase_func(): OIDC authentication failed: unhandled request to the redirect_uri: /anything/foo, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:11 [warn] 48#48: *51955 [lua] plugin.lua:923: run_plugin(): openid-connect exits with http status code 500, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [error] 50#50: *52561 [lua] openidc.lua:1475: authenticate(): request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [error] 50#50: *52561 [lua] openid-connect.lua:315: phase_func(): OIDC authentication failed: request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [warn] 50#50: *52561 [lua] plugin.lua:923: run_plugin(): openid-connect exits with http status code 500, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/75962736/196122782-019bea0c-e408-4437-a49b-a5a8cbbbd001.png">

**Comment by tzssangglass** [comment]
> 3： 访问链接测试通过
> 4： 此时关闭openidc插件功能
> 5： 访问测试链接，失败（报错）

Please describe these steps in more detail.
1. After opening the openid plugin, the corresponding route config in etcd
2. The corresponding route config in etcd after closing the openid plugin
3. how to test and what is the curl command used

**Comment by jiahui1988** [comment]
> 
3: 使用浏览器访问链接：http://example.authing.com:9080/anything/foo,此时出现配置了open-connect插件的身份认证登录界面。
4:  在改路由中关闭open-connect插件
5： 浏览器访问http://example.authing.com:9080/anything/foo。此时报错。报错内容为:

2022/10/17 08:05:11 [error] 48#48: *51955 [lua] openidc.lua:1092: authenticate(): unhandled request to the redirect_uri: /anything/foo, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:11 [error] 48#48: *51955 [lua] openid-connect.lua:315: phase_func(): OIDC authentication failed: unhandled request to the redirect_uri: /anything/foo, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:11 [warn] 48#48: *51955 [lua] plugin.lua:923: run_plugin(): openid-connect exits with http status code 500, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [error] 50#50: *52561 [lua] openidc.lua:1475: authenticate(): request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [error] 50#50: *52561 [lua] openid-connect.lua:315: phase_func(): OIDC authentication failed: request to the redirect_uri path but there's no session state found, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"
2022/10/17 08:05:21 [warn] 50#50: *52561 [lua] plugin.lua:923: run_plugin(): openid-connect exits with http status code 500, client: 172.23.0.1, server: _, request: "GET /anything/foo HTTP/1.1", host: "example.authing.com:9080"

**Comment by tzssangglass** [comment]
You still haven't provided the required information

**Comment by tzssangglass** [comment]
> * after enable the openid plugin, the corresponding route config in etcd
> * the corresponding route config in etcd after disable the openid plugin

what this?

**Comment by jiahui1988** [comment]
> * etcd

但是。1： 我关闭了对应的openid组件，为什么从日志中看，组件还在工作，
             2:  最重要的问题是，关闭组件后，再在前端访问，就报错了（见上文截图）。

**Comment by tzssangglass** [comment]
> 我关闭了对应的openid组件，为什么从日志中看，组件还在工作，

Check all routes to see if any other routes are bound to the openid plugin and if the request hits this route

**Comment by tzssangglass** [comment]
> 开始开启了openidc 插件，然后关闭插件后，就开始报错。（报错日志显示openidc问题，但是此时插件实际上是全部关闭状态。而且配置中只存在此一条路由配置）

> 但是。1： 我关闭了对应的openid组件，为什么从日志中看，组件还在工作，
> 2: 最重要的问题是，关闭组件后，再在前端访问，就报错了（见上文截图）。


1. make sure that all configurations contain only one route?
2. provode the data for this route in etcd.
