### ISSUE TITLE
help request: Is it possible t have "include_req_body"  for google-cloud-logging ?

### ISSUE THREAD

**Issue by Arztz** [apache/apisix#8101]
### Description

Is it possible to have "include_req_body"  for google-cloud-logging?

path apisix/plugins/google-cloud-logging.lua  function get_logger_entry

Is it possble to add requestBody = entry.request.body to the code use "include_req_body" condition?

Should  I post in Issue: Feature Request ?

I use issue help in case of you have another  solution.

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux apisix-5b6bbfff88-xwq9q 5.4.144+ #1 SMP Wed Nov 3 09:56:10 PDT 2021 x86_64 Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13-alpine

**Comment by hf400159** [comment]
PR's welcome!
