### ISSUE TITLE
request help: support tars/taf/trpc with tengine's or nginx's module

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#812]
### Issue description

tars, taf and trpc is the transport protocol of Tencent. 

### Environment

* apisix version (cmd: `apisix version`): 1.0 or higher
* OS: tlinux 2.2/ centos

**Comment by moonming** [comment]
welcome PR

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
