### ISSUE TITLE
feat: As a user, I want to hide credentials for jwt-auth plugin, so that we wouldn't get  jwt token at upstream

### ISSUE THREAD

**Issue by starsz** [apache/apisix#8122]
### Description

Hello, I found that now those auth plugins had support "hide_credentials" 

|  plugin   | field   | url |
|  ----  | ----  | ---- | 
| key-auth  | hide_credentials |  https://apisix.apache.org/docs/apisix/next/plugins/key-auth/ |
| basic-auth  | hide-credentials | https://apisix.apache.org/docs/apisix/next/plugins/basic-auth/ |
| hmac-auth | keep_headers | https://apisix.apache.org/docs/apisix/next/plugins/hmac-auth/ |

But `jwt-auth` plugin doesn't support hiding credentials so we will get the credentials at upstream. It may cause some security problems. I think we should support it.

**Comment by starsz** [comment]
@pixeldin Do you want to try this?

**Comment by opencmit1** [comment]
What is the current version
APISIX 2.13.0 and all previous versions，The jwt auth plug-in has the security problem of disclosing the user's secret key, because the error information returned from the dependency library lua rest jwt contains sensitive information

**Comment by pixeldin** [comment]
> 

Ok, I am trying to cover it.

**Comment by starsz** [comment]
> APISIX 2.13.0 and all previous versions

Hi, @opencmit1.What I mean is that Apache APISIX will take the credentials to upstream.
Do you mean that APISIX will return the sensitive information to the client?

**Comment by opencmit1** [comment]
Relevant content can be viewed
https://segmentfault.com/a/1190000041741551
