### ISSUE TITLE
feat: As a user, I want to be able to set custom function in proxy-rewrite plugin, so that I can implement custom handling of parameters in URL path in rewrite phase.

### ISSUE THREAD

**Issue by kordino** [apache/apisix#8127]
### Description

feat: As a user, I want to be able to set custom function in proxy-rewrite plugin, so that I can implement custom handling of parameters in URL path in rewrite phase.

an example:
`curl -XPUT 'http://127.0.0.1:9080/apisix/admin/routes/1' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data-raw '{
    "uri": "/service/user/:userId",
    "name": "test",
    "plugins": {
        **"proxy-rewrite"**: {
            **"phase": "rewrite"**,
            "functions" : ["return function(conf, ctx) require(\"apisix.core\").response.exit(200, require(\"apisix.core\").json.encode(ctx.curr_req_matched, true)) end"]
        }
    }
}'`

**Comment by tzssangglass** [comment]
So why don't you just use the serverless plugin?

**Comment by kordino** [comment]
I have used the serverless per function but I don't know how to use it to rewrite the URI. Can you provide some help on how to rewrite:
 /service/object/:objectId (route or mask)  to this /service/action/object/:objectId (backend service)
and 
 /service/object/:objectId/something (route or mask)  to this /service/action/object/:objectId/something (backend service)

**Comment by tzssangglass** [comment]
> /service/object/:objectId (route or mask) to this /service/action/object/:objectId (backend service)

this can be done with `proxy-rewrite` plugin, config like:

```json
{
    "upstream":{
        "nodes":{
            "127.0.0.1:1980":1
        },
        "type":"roundrobin"
    },
    "plugins":{
        "proxy-rewrite":{
            "regex_uri":[
                "^/service/(.*)",
                "/service/action/$1"
            ]
        }
    },
    "uri":"/service/*"
}
```

**Comment by kordino** [comment]
Hi, Can I do the above in route? I am asking because I can not see proxy-rewrite in available plugins for route. I tried the above in the service but it didn't work unfortunately.
