### ISSUE TITLE
help request: about add a route  then all requst  return 404 error

### ISSUE THREAD

**Issue by vavikast** [apache/apisix#8132]
### Description

Hello I'm Very newbie into API Gateway.  I  install apisix and apisix controller  in kubernetes,  but I use apisix controller only 
 install  dashbord,  mostly I  use apisix + consul。now  my apisix is ok until   add a rule ,the rule local_proxy other domain,like that.
 location /scrm-organization-api {
        proxy_pass http://xxx,yyyy.com;
      }
then you can use the local_proxy,but after a minutes . all request will return 404.  include the dashboard,apisix-admin.
but the apisix logs  only print  404, I can't get  userful log .
the apisix  can't use, but  it look like ok, and the  alway print the log.

this is ok : 
![企业微信截图_16662501419613](https://user-images.githubusercontent.com/30380259/196881428-d9bb6e96-30dd-4709-b5ca-fde3b7f76650.png)
when add a rule : 
![image](https://user-images.githubusercontent.com/30380259/196881805-3f3fd49c-347a-4e46-9260-7a7a44463be2.png)
![image](https://user-images.githubusercontent.com/30380259/196881885-88598d72-d58e-4479-841f-09202e305025.png)

after a minutes 
all reuqest will 404. 
![企业微信截图_16662483851071](https://user-images.githubusercontent.com/30380259/196882036-6b893ee6-187c-4086-bd0d-d0653abad69e.png)
![image](https://user-images.githubusercontent.com/30380259/196883812-d8d8f037-8fa6-48a6-bc1a-ffcae251975f.png)
![image](https://user-images.githubusercontent.com/30380259/196884080-3efcb025-1600-49b7-af49-5eda4c7eb710.png)

### Environment

- APISIX version (run `apisix version`):  2.14.1
- Operating system (run `uname -a`): ID=alpine VERSION_ID=3.14.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4.18
- APISIX Dashboard version, if relevant: 2.13.0 
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0
- Hem info: NAME        NAMESPACE     	REVISION	UPDATED                                	STATUS  	CHART                 	APP VERSION
apisix          	ingress-apisix	1       	2022-06-27 12:05:12.308797023 +0800 CST	deployed	apisix-0.10.0         	2.14.1

**Comment by tzssangglass** [comment]
From your logs and accordingly, the 404 is returned upstream, not from APISIX.

**Comment by vavikast** [comment]
when I add the rule , all request will return 404, not only the proxy domain,  it's mean the apisix can't handle any request  just return 404.  I can get response from the upstream direct connection。 
I find  apisix memory  increase，so i suspect  apisix endless loop。
what should i do next

**Comment by tzssangglass** [comment]
I observed that you added several routes with uri `/*`. You can adjust the logging level in apisix and restart again, and see if the route hit by the 404 request is the expected route.

> when I add the rule , all request will return 404,

Are you saying that the admin API will also 404?

If possible, please provide minimal replication use cases.

I need to know.

1. what was the route in etcd before the 404

2. what routing configuration was added and then APISIX suddenly returned all 404

3. what is the test request

4. the APISIX configuration file

so I can reproduce it in my local.

**Comment by vavikast** [comment]
I deploy anoth one, but i can't reproduce it.
so can you remote control my computer,  or  you send your email to me ,you direct use the apisix .

**Comment by vavikast** [comment]
Thanks for tzssangglass, The key to solve problem  is the fix : https://github.com/apache/apisix/pull/7466, I upgrade the apisix to 15.0, It's fine .
