### ISSUE TITLE
help request: restart apisix, then route 404

### ISSUE THREAD

**Issue by liu871009243** [apache/apisix#8134]
### Description

before restarting apisix，routes run normally.
after restarting apisix, all routes 404.
but i can see the routes in dashboard, and the route configurations are correct. 
when i open the route in dashboard, and save it, the route get right

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Linux fs-ops-vm-apisix2 5.4.204-1.el7.elrepo.x86_64 #1 SMP Tue Jul 5 16:32:13 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.19.9.1built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2)(GCC) built with OpenSSL 1.1.1n  15 Mar 2022TLS SNI support enabled configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.19.9.1.6 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.20 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.10 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../mod_dubbo --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../ngx_multi_upstream_module --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../apisix-nginx-module --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../apisix-nginx-module/src/stream --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../wasm-nginx-module --add-module=/tmp/tmp.itsGpY3Nfs/openresty-1.19.9.1/../lua-var-nginx-module --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):etcd-v3.4.13-linux-amd64
- APISIX Dashboard version, if relevant:2.11.0

**Comment by tokers** [comment]
Did you see any error logs in APISIX `error.log` file? Especially for log entries in the `error` level.

**Comment by liu871009243** [comment]
when restart apisix, error.log outputs:
`  2022/10/20 17:22:40 [warn] 28536#28536: *224 [lua] jwt-laqu.lua:18: jwt-laqu, ngx_time:1666257760, context: ngx.timer
  2022/10/20 17:22:40 [warn] 28531#28531: *223 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
  2022/10/20 17:22:40 [warn] 28536#28536: *224 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
  2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] jwt-laqu.lua:18: jwt-laqu, ngx_time:1666257760, context: ngx.timer
  2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
  2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] init.lua:297: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer`

when i access the route, no log new in the error.log. 
and when i open the route in dashboard, and save it, the route get right. and when i access it, log get right

**Comment by panpingyuan** [comment]
I also encountered this problem, temporarily found that the load configration in init stage is {}.
apisix 2.13.0  openresty 1.19.1.1

**Comment by panpingyuan** [comment]
I also encountered this problem, temporarily found that the load configration in init stage is {}.
apisix 2.13.0 openresty 1.19.1.1  etcd 3.5.x

**Comment by tokers** [comment]
> when restart apisix, error.log outputs:
> 
> ```
> 2022/10/20 17:22:40 [warn] 28536#28536: *224 [lua] jwt-laqu.lua:18: jwt-laqu, ngx_time:1666257760, context: ngx.timer
> 2022/10/20 17:22:40 [warn] 28531#28531: *223 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
> 2022/10/20 17:22:40 [warn] 28536#28536: *224 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
> 2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] jwt-laqu.lua:18: jwt-laqu, ngx_time:1666257760, context: ngx.timer
> 2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] plugin.lua:223: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
> 2022/10/20 17:22:40 [warn] 28530#28530: *225 [lua] init.lua:297: sync_local_conf_to_etcd(): sync local conf to etcd, context: ngx.timer
> ```
> 
> when i access the route, no log new in the error.log. and when i open the route in dashboard, and save it, the route get right. and when i access it, log get right

Nothing is suspicious.

**Comment by tokers** [comment]
> 

Init stage? Did you enable the option: `disable_sync_configuration_during_start`?

**Comment by liu871009243** [comment]
our `disable_sync_configuration_during_start` option is false.

For additional, we deployed an etcd cluster, and enable basic auth.
And we deployed two apisix: apisix1 and apisix2  with LB.
restart apisix1, apisix1 route 404, but apisix2 run normally. restart apisix2, then apisix2 route 404.
we open the route in dashboard, and save it, both apisix1 and apisix2 run normally.

**Comment by tzssangglass** [comment]
> For additional, we deployed an etcd cluster, and enable basic auth.
> And we deployed two apisix: apisix1 and apisix2 with LB.
> restart apisix1, apisix1 route 404, but apisix2 run normally. restart apisix2, then apisix2 route 404.
> we open the route in dashboard, and save it, both apisix1 and apisix2 run normally.

it has been fixed by #5558, and released in APISIX v2.12.0, pls upgrade your APISIX's version.

**Comment by tzssangglass** [comment]
> I also encountered this problem, temporarily found that the load configration in init stage is {}.
> apisix 2.13.0 openresty 1.19.1.1 etcd 3.5.x

If you are using version 2.13, then it should be something else, please open a new issue and describe your problem in detail.

**Comment by liu871009243** [comment]
> it has been fixed by https://github.com/apache/apisix/pull/5558, and released in APISIX v2.12.0, pls upgrade your APISIX's version.
we are using version 2.13.1，if downgrading APISIX to v2.12.0，I fear of creating new problems. 
Is there any other solution? 
before deploying the apisix cluster, we have deployed stand-alone apisix and etcd without basic auth in a virtual machine. 
it is running normally, even if restart apisix.

**Comment by tzssangglass** [comment]
> we are using version 2.13.1，if downgrading APISIX to v2.12.0，I fear of creating new problems.
> Is there any other solution?

this fix was contained in 2.13.1, so don't need to downgrade. I think your question is different from this issue.

**Comment by liu871009243** [comment]
After deploying Apisix cluster, we imported routes, upstreams and consumers from old stand-alone apisix.
We wrote a python script, using apisix admin api to do it: get the resources from old apisix, and put them to new apisix cluster.
Whether it will make difference.

**Comment by tzssangglass** [comment]
> We wrote a python script, using apisix admin api to do it: get the resources from old apisix, and put them to new apisix cluster.
> Whether it will make difference.

There is no problem with the process, the admin API will verify the data format, but the process does not guarantee that the old and new data are the same?

**Comment by liu871009243** [comment]
> There is no problem with the process, the admin API will verify the data format, but the process does not guarantee that the old and new data are the same?

Are there any suggestions?
1. Using Apisix admin api
2. Exporting the data from old ETCD, and importing them to new ETCD cluster
3. To do...

**Comment by tzssangglass** [comment]
> 2\. Exporting the data from old ETCD, and importing them to new ETCD cluster

ETCD itself has the ability to migrate data

**Comment by forever765** [comment]
@tzssangglass yes, we tested both methods separately:
1. Using Apisix admin api. We will clear the new etcd cluster data, export the data using the apisix admin api, and import into the new apisix instance.
2. Exporting the data from old etcd using snapshot method, restore etcd snapshot data to new etcd cluster

**Comment by liu871009243** [comment]
@tzssangglass @tokers Thanks for technical support for a few days. Case wanting to promote the use of ApiSix in the team, we depolyed a new Apisix cluster, and synchronous data from the old stand-alone one. Then some problems encountered.

We exported the data from old ETCD, and imported them to new ETCD cluster, then the problems no longer encounter.

Now I get an idea: ETCD will callback Apisix when the data change. ETCD is the publisher, and Apisix is the subscriber. Looking forward to giving correction, convenient follow-up problem positioning.

-----------------------------------------------------------------------------
The following is our operation process.
Background: 
A stard-alone Apisix (old Apisix) and a local ETCD (old ETCD) in a virtual machine. It runs normally for days.
Tow new Apisix (Apisix1 and Apisix2) with LB, and a new ETCD cluster (new ETCD).
We want to use new Apisix and ETCD insteading of old one.

Step:
1. Eported the data from old ETCD, and imported them to new ETCD. Then modified old Apisix's ETCD config to new ETCD. But old Apisix started failed with some openresty error.
2. Step 1 let us guess that we can't import data to ETCD without using Apisix. Then we using Apisix admin api to import data. However, this issue appeared.
3. The comment: `the admin API will verify the data format, but the process does not guarantee that the old and new data are the same?` We retry to import data to new ETCD. Apisix1 and Apisix2 run normally even if restarting them.

Guess:
In Step 1, old Apisix started failed, because old Apisix don't konw new ETCD's data changes. Then the data doesn't match.
In Step 3, importing data in the same way as Step 1, but the new Apisix is running with the new ETCD all the time. So new Apisix knows the data changes.

**Comment by tzssangglass** [comment]
> 1. Exported the data from old ETCD, and imported them to new ETCD. Then modified old Apisix's ETCD config to new ETCD. But old Apisix started failed with some openresty error.

what error?

**Comment by tzssangglass** [comment]
> In Step 1, old Apisix started failed, because old Apisix don't konw new ETCD's data changes. Then the data doesn't match.

APISIX itself is stateless, so there is no comparison between old data and new data.

**Comment by liu871009243** [comment]
> what error?

@tzssangglass 
![企业微信截图_16665798671707](https://user-images.githubusercontent.com/48212724/197439792-afc551a3-4614-4634-87cf-4420e8486ab8.png)

**Comment by tzssangglass** [comment]
It looks like a core dump has occurred, which is a new problem.

**Comment by liu871009243** [comment]
@tzssangglass Thanks for technical support.
And I hava another question:
I found many files named "core.xxx" in the "/usr/local/apisix" folder.  They appeare when I restart apisix.
![image](https://user-images.githubusercontent.com/48212724/197924940-ac3f4e25-4b54-46b7-bb13-8183078eaac6.png)
And the "core.xxx" files are binary files. 
Can I delete the "core.xxx" files? 
Can I make them no logger appeare?

**Comment by tzssangglass** [comment]
> And I hava another question:
> I found many files named "core.xxx" in the "/usr/local/apisix" folder. They appeare when I restart apisix.

This is the coredump file that keeps the reason for the abnormal exit of the process, and you need to analyze this file with gdb to view the stack information and find the reason for the abnormal exit of the process.
