### ISSUE TITLE
help request: If I use Keycloak as my identity server,what is the different between authz-keycloak and openid-connect?

### ISSUE THREAD

**Issue by tcgdy0201** [apache/apisix#8136]
### Description

Hi Sir/Madam:

May I have you some minutes to help me with the question below.

I have deployed keycloak as my identity server, besides I also used 'openid-connect' plugin to add authentication for my apis. It works.

Today, I find another plugin as 'authz-keycloak' which seems similar as 'openid-connection'. So i get confused.

So I rasied this issue, what is the difference between these two plugins (`authz-keycloak` and `openid-connect`) and what is the scenario for those.

Thank you for your kind help in advance.

Best regards

### Environment

not relevant

**Comment by mscb402** [comment]
OpenID Connect is an authentication protocol based on the OAuth 2.0. Many authentication providers implement this protocol. You can use this plugin to connect with them. Like Keycloak, Ory Hydra, Okta, Auth0, etc
And the authz-keycloak plugin is only for Keycloak.

**Comment by tcgdy0201** [comment]
> 

thanks a lot！

**Comment by jnystad** [comment]
authz-keycloak seems to use Keycloak as an authorization provider (protecting resources represented in the Keycloak configuration), not just an identity provider. If you only want to use Keycloak as an IdP, openid-connect plugin should be sufficient (and simpler).

See the Keycloak documentation for authorization services: https://www.keycloak.org/docs/latest/authorization_services/index.html
