### ISSUE TITLE
help request: Is it supported quic/http2/websocket?

### ISSUE THREAD

**Issue by liyebing** [apache/apisix#8137]
### Description

Is apisix supported quic/http2/websocket?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
support http2 and websocket, don't support quic, read more: #6403

**Comment by monkeyDluffy6017** [comment]
Please refer to https://github.com/apache/apisix/issues/9752
