### ISSUE TITLE
request help: missing real address

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#8140]
### Current Behavior

2022/10/21 13:43:28 [warn] 7883#7883: *11042335 [lua] real-ip.lua:147: phase_func(): missing real address

### Expected Behavior

2022/10/21 13:43:28 [warn] 7883#7883: *11042335 [lua] real-ip.lua:147: phase_func(): missing real address

### Error Logs

2022/10/21 13:43:28 [warn] 7883#7883: *11042335 [lua] real-ip.lua:147: phase_func(): missing real address

### Steps to Reproduce

2022/10/21 13:43:28 [warn] 7883#7883: *11042335 [lua] real-ip.lua:147: phase_func(): missing real address

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`):Linux  6.0.1-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 10 10:32:48 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.2 -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/stream --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/meta --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../wasm-nginx-module-0.6.3 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../grpc-client-nginx-module-v0.2.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
provide reproduction steps, plugin configuration information

**Comment by tokers** [comment]
Are you sure your requests take the correct IP information (e.g., in a header)?

**Comment by shreemaan-abhishek** [comment]
ping @lifeblood
