### ISSUE TITLE
if apisix can support etcd cluster or multy etcd address roundrobin?

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#8142]
### Description

In Apisix 2.9,i find some code about multy etcd address roundrobin in resty.etcd file,but it can't be used.When i update to 2.15,i can't find this module.I try to config multy etcd address,but apisix will always to watch first health etcd,though these ips belong to one cluster of etcd.I hope my etcd cluster can have balance work load,how i can write my apisix's config yaml ? or what should i do to reach this aim?

### Environment

- APISIX version (run `apisix version`):2.9/2.15

**Comment by tzssangglass** [comment]
> but apisix will always to watch first health etcd

it has been fixed: https://github.com/api7/lua-resty-etcd/pull/170

**Comment by Nobilta** [comment]
> > but apisix will always to watch first health etcd
> 
> it has been fixed: [api7/lua-resty-etcd#170](https://github.com/api7/lua-resty-etcd/pull/170)

thank you so much,so can i use the feature in 3.0?

**Comment by tzssangglass** [comment]
> thank you so much,so can i use this feature in apisix3.0?

yes, and I remember v2.13.3 has backported this feature, use `lua-resty-etcd` 1.8.3, which contains this.

**Comment by Nobilta** [comment]
> > thank you so much,so can i use this feature in apisix3.0?
> 
> yes, and I remember v2.13.3 has backported this feature, use `lua-resty-etcd` 1.8.3, which contains this.
