### ISSUE TITLE
bug: skywalking-logger配置文件配置不生效apache/apisix:2.14.1-alpine

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/apisix#8143]
### Current Behavior

在apisix配置文件中开启这个参数后,没有上报日志
skywalking-logger: # 配置skywalking的相关信息
    service_name: "apisix::apisix"    # 前边是组名,后边是应用名
    service_instance_name: $hostname  # 取hostname作为实例名
    endpoint_addr: http://skywalking-oap.skywalking:12800  #skywalking的http地址

还需要在页面的插件这么配置就不上报
{
  "disable": false,
  "endpoint_addr": "http://skywalking-oap.skywalking:12800",
}
还要加 service_name: "apisix::apisix" 才能上报

在页面如下配置后,$hostname获取不到值

{
  "disable": false,
  "endpoint_addr": "http://skywalking-oap.skywalking:12800",
  "service_instance_name": "$hostname",
  "service_name": "apisix::apisix"
}

### Steps to Reproduce

按照上述进行重现

### Environment

版本apache/apisix:2.14.1-alpine

**Comment by hf400159** [comment]
Please refer to: https://apisix.apache.org/zh/docs/apisix/plugins/skywalking-logger/   `skywalking-logger` and  `skywalking` are different plugins.
