### ISSUE TITLE
Whether to support keeping the source IP consistent when forwarding using stream_proxy

### ISSUE THREAD

**Issue by chenjinfeng0505** [apache/apisix#8147]
### Description

1. 使用apisix进行请求转发，规则如下。
 curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: ef403f335dce4906a2962b8f015a6d2d' -X PUT -d '
{
    "server_port":80,
     "scheme":"http",
    "upstream": {
        "nodes": {
            "上游服务ip:80": 1
        },
        "type": "roundrobin",
        "pass_host": "pass"
    }
}'

请求端服务器ip: 27.223.99.188
apisix 服务器ip:  10.50.28.231

请求时， 上游服务收到的地址如下：
![image](https://user-images.githubusercontent.com/110583072/197337874-88c6636d-71e6-4f50-9900-28ebf9f8b0ae.png)

请问有什么方法能保证上游服务收到的地址为请求端服务器ip 吗？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Try the Nginx `proxy_bind` directive.
