### ISSUE TITLE
help request: how to use 'expires' and 'etag' in apisix?

### ISSUE THREAD

**Issue by niruntao** [apache/apisix#8152]
### Description

I have a piece of nginx code as below:

location ~*\.(jpg|jpeg|gif|png|bmp|svgicon|ico|ttf|eot|woff|woff2|txt)$ {
    expires 30d;
    add_header 'Cache-Control' 'max-age=2592000';
    add_header 'Cache-Control' 'must-revalidate, private';
    add_header  Last-Modified $date_gmt;
    etag on;
    proxy_pass http://test_proxy;
}

I want to migrate it to apisix, but I can't find any plugins that support 'expires' and 'etag'. Among them, I implemented add_header with the plugin 'response-rewrite'.

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): CentOS Linux release 7.9.2009 (Core)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx/1.17.3

**Comment by tzssangglass** [comment]
try with [proxy-cache](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md) plugin.

**Comment by hf400159** [comment]
https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md  might solve your problem.

**Comment by niruntao** [comment]
> try with [proxy-cache](https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-cache.md) plugin.

The proxy-cache plugin caches the file on disk, and I see expires is a configuration for the client-side cache. In addition, if you run apisix in k8s cluster, you have to do the corresponding persistence. If you use proxy-cache, is the change too big?

**Comment by tzssangglass** [comment]
> I see expires is a configuration for the client-side cache

where did you saw this?

**Comment by niruntao** [comment]
> > I see expires is a configuration for the client-side cache
> 
> where did you saw this?

I checked 'expires' on the official website of the nginx, but there is no description of how it implements the cache. Later, I checked the information on the Internet, and a blog post said that it is a client-side cache.

https://nginx.org/en/docs/http/ngx_http_headers_module.html#expires

http://t.zoukankan.com/Jackie-Chen-p-10640802.html

**Comment by tzssangglass** [comment]
> I checked 'expires' on the official website of the nginx, but there is no description of how it implements the cache. Later, I checked the information on the Internet, and a blog post said that it is a client-side cache.

You can use the response-rewrite plugin if you want to maintain the same functionality in APISIX with the Nginx configuration pasted above.

**Comment by niruntao** [comment]
> You can use the response-rewrite plugin if you want to maintain the same functionality in APISIX with the Nginx configuration pasted above.

Okay, I'll try again.

**Comment by shreemaan-abhishek** [comment]
@niruntao any updates? If not, please close the issue. Thanks.

P.S: proxy_cache now support memory based caching as well.
