### ISSUE TITLE
help request: https cert got ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by jeffreys-cat** [apache/apisix#8153]
### Description

I upload ssl cert on apisix dashboard, which is a wildcard SNI, my domain is `a.goose.com`, http://a.goose.com is OK, but https://a.goose.com not work,

![image](https://user-images.githubusercontent.com/11832969/197448004-d5da376a-8382-414f-8392-64c2c55ff523.png)

![image](https://user-images.githubusercontent.com/11832969/197447559-d18a29ee-2c3d-4252-be7a-b0c42978fef6.png)

![image](https://user-images.githubusercontent.com/11832969/197447591-8e673d1a-e775-4c93-9a64-3ecd4263bee4.png)

![image](https://user-images.githubusercontent.com/11832969/197447784-c7d61175-2930-4b92-bbe8-f9b48ffcb2e2.png)

![image](https://user-images.githubusercontent.com/11832969/197451258-db61bd18-3c09-4f48-b3e2-9e6850de5d20.png)

### Environment

- APISIX version (run `apisix version`): 2.99.0
- Operating system (run `uname -a`): centos 8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
> I upload ssl cert on apisix dashboard, which is a wildcard SNI, my domain is `a.goose.com`, http://a.goose.com is OK, but [a.goose.com](https://a.goose.com) not work,

what the common name of your cert? how to send request?

**Comment by tokers** [comment]
From the screenshot, the SNI is not related to the certificate common name & SAN.

**Comment by kingluo** [comment]
Configure from admin API, the issue is sloved.
https://the-asf.slack.com/archives/CUC5MN17A/p1666602805748959?thread_ts=1666585508.885599&cid=CUC5MN17A
Please close this issue.

**Comment by jeffreys-cat** [comment]
> From the screenshot, the SNI is not related to the certificate common name & SAN.

Yep, uploaded  certificate by dashboard not working

**Comment by jeffreys-cat** [comment]
> Configure from admin API, the issue is sloved. https://the-asf.slack.com/archives/CUC5MN17A/p1666602805748959?thread_ts=1666585508.885599&cid=CUC5MN17A Please close this issue.

Thanks you very much!
