### ISSUE TITLE
help request: http_ssl_phase(): failed to fetch ssl config: failed to find SNI

### ISSUE THREAD

**Issue by wangfeng22** [apache/apisix#8155]
### Description

I have set SSL certification, but sometimes the gateway still occurs this error.

```
2022/10/24 12:41:05 [error] 30233#30233: *1237045 [lua] init.lua:163: http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol. If you need to report an issue, provide a packet capture file of the TLS handshake., context: ssl_certificate_by_lua*, client: 10.36.216.12, server: 0.0.0.0:443
```

I use Wireshark to capture some packets as follow.

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/42538040/197465464-b8a68996-967a-4c64-bcb3-c31fe8e6caab.png">

client hello

<img width="928" alt="image" src="https://user-images.githubusercontent.com/42538040/197464999-4cf4fb1e-60b3-471a-bf49-bfdca65049b5.png">

server

<img width="810" alt="image" src="https://user-images.githubusercontent.com/42538040/197465206-a770e383-85f9-40a2-a2ae-bb84ed433c88.png">

### Environment

- APISIX version (run `apisix version`): 2.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
It looks like your client doesn't send Server Name Indication extension?
