### ISSUE TITLE
bug: upstream chash (hash on header) didn't work

### ISSUE THREAD

**Issue by dumontxbb** [apache/apisix#8156]
### This is my upstream's config
`{
  "nodes": [
    {
      "host": "httpbin.org",
      "port": 80,
      "weight": 1
    },
    {
      "host": "kennethreitz.org",
      "port": 80,
      "weight": 1
    }
  ],
  "retries": 0,
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "chash",
  "hash_on": "header",
  "key": "companyId",
  "scheme": "http",
  "pass_host": "pass",
  "name": "session_sticky_test_upstream",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }`

### This is my route's config
`{
  "uri": "/odata/v2/internal/sebTest1",
  "name": "session_sticky_test_route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream_id": "429113214085628608",
  "status": 1
}`

### my test url:
`curl --location --request GET 'localhost:9080/odata/v2/internal/sebTest1' \
--header 'companyId: test1'`

### **the reached upstream sometimes was node1, sometimes was node2 ,**
<img width="916" alt="Screen Shot 2022-10-24 at 15 13 16" src="https://user-images.githubusercontent.com/112160231/197468370-b6db846f-2255-4138-b150-dbb241c65831.png">

### Expected Behavior

the reached upstream should  always is node1 or node2 

### Steps to Reproduce

1. create upstream
2. create route
3. test url

### Environment

- APISIX version (run `apisix version`): 2.99.0
- Operating system (run `uname -a`): Linux bc0d17179e74 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 aarch64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.2 -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../apisix-nginx-module-1.10.0 --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/stream --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/meta --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../wasm-nginx-module-0.6.3 --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.r770utqAFx/openresty-1.21.4.1/../grpc-client-nginx-module-v0.2.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
root@bc0d17179e74:/usr/local/apisix/conf#
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
`"type": "chash", "hash_on": "header", "key": "companyId"`
It can be seen from this that the hash key you specified is `companyId` in the request header, but your actual request does not carry this request header.

**Comment by dumontxbb** [comment]
> `"type": "chash", "hash_on": "header", "key": "companyId"` It can be seen from this that the hash key you specified is `companyId` in the request header, but your actual request does not carry this request header.

sorry,i typed the wrong key~still the
<img width="1150" alt="Screen Shot 2022-10-25 at 09 13 40" src="https://user-images.githubusercontent.com/112160231/197659712-e1fdb34c-8559-4b8a-b9f3-a82dfa7262e1.png">
 same

**Comment by tokers** [comment]
Do you see any related error log?

**Comment by dumontxbb** [comment]
nope,There's nothing   in the /usr/local/apisix/logs/error.log

**Comment by tzssangglass** [comment]
The same scene cannot be reproduced.
Do you have some other routes with the same configuration in etcd?

**Comment by dumontxbb** [comment]
nope, there is only one route with the upstream {
  "nodes": [
    {
      "host": "httpbin.org",
      "port": 80,
      "weight": 1
    },
    {
      "host": "kennethreitz.org",
      "port": 80,
      "weight": 1
    }
  ],
  "retries": 0,
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "chash",
  "hash_on": "header",
  "key": "companyId",
  "scheme": "http",
  "pass_host": "pass",
  "name": "session_sticky_test_upstream",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}

**Comment by tzssangglass** [comment]
Can you provide a reproduction environment?

**Comment by tzssangglass** [comment]
> well I'll ask for your help when I deploy to a public IP

well

**Comment by shreemaan-abhishek** [comment]
@dumontxbb any updates? If not, please close the issue.
