### ISSUE TITLE
stream_routes Whether blue green switching is supported

### ISSUE THREAD

**Issue by XW512** [apache/apisix#8160]
### Description

At present, we want to use apisix for tcp forwarding, but we need to switch between blue and green, and how to configure it to support it

### Environment

- APISIX version (run `apisix version`): 2.13.0
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Which characteristic of the traffic can you use as the judgement of the traffic splitting?

**Comment by XW512** [comment]
> Which characteristic of the traffic can you use as the judgement of the traffic splitting?

What I want to distinguish is based on the port number. For example, 9101 is a formal port and 9102 is a gray-scale port. When switching to gray-scale, point the port of 9101 to the gray-scale upstream. In this way, the port of 9102 becomes a gray-scale service. I don't know whether it can support it

**Comment by tzssangglass** [comment]
Currently not supported, there is no such plugin for the stream subsystem.

**Comment by tokers** [comment]
You may need to create two `stream_routes` and operate (maybe by another program, or by yourself) them when you need to do the canary release.

**Comment by XW512** [comment]
> You may need to create two `stream_routes` and operate (maybe by another program, or by yourself) them when you need to do the canary release.

thank you, i will try it

**Comment by XW512** [comment]
> Currently not supported, there is no such plugin for the stream subsystem.

OK, I'll take a look
