### ISSUE TITLE
help request: include KeyCloak user id as Consumer for Prometheus

### ISSUE THREAD

**Issue by mathieuronvelmove** [apache/apisix#8161]
### Description

Used plugins:
* prometheus
* openid-connect
* authz-keycloak

Standalone mode is used.

Prometheus is providing metrics of called endpoints.
For example: 
```
apisix_http_status{code="302",route="routes#2",matched_uri="/my-path",matched_host="",service="",consumer="",node="xxx.xxx.xxx.xxx"} 6
```

However, the consumer field is empty despite users have been authenticated through KeyCloak.
Is there a way to match KeyCloak users as Apisix consumers? If yes, could you describe the way to achieve this?

I read this discussion which shows we can have consumers in Prometheus metrics but I don't know how to achieve this with openid-connect.
https://github.com/apache/apisix/discussions/7332

### Environment

- APISIX version (run `apisix version`): 2.15.0 (Docker apache/apisix:2.15.0-alpine)
- Operating system (run `uname -a`): Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): standalone mode
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
The consumer concept is designed for authentication ways handled by apisix while openid connect is not one of them and consumer is not appropriate for it.
