### ISSUE TITLE
feat: As a user, I want to add type for every plugin, so that we can get the type info of every plugin in the schema

### ISSUE THREAD

**Issue by starsz** [apache/apisix#8164]
### Description

Hello, I find that we have a type field in the plugin.

```
local _M = {
    version = 0.1,
    priority = 2500,
    type = 'auth',
    name = plugin_name,
    schema = schema,
    consumer_schema = consumer_schema,
}

```
refer: https://github.com/apache/apisix/blob/master/apisix/plugins/key-auth.lua#L57.

But only the auth plugin uses the type. For example: 
The file-logger plugin doesn't have.
refer: https://github.com/apache/apisix/blob/master/apisix/plugins/file-logger.lua#L47-L53.

So I really recommend that we can add the type filed to every plugin.
We can have "auth", "security", "serverless", "transformation" e.g.

**Comment by spacewander** [comment]
The `auth` type is used here: https://github.com/apache/apisix/blob/e2d0f0b16bb157412684a38b129d12acb4628d39/apisix/consumer.lua#L46. (BTW, the `auth` is a bad name to me. It would be better to be named as `consumer`. We keep this name just because we don't have a chance to rename it.) 

The `auth` type is also used in the dashboard to make sure a plugin can be bound with the consumer.

So what is the use case for `"security"` and the other types, and how to classify them?

**Comment by starsz** [comment]
> So what is the use case for "security" and the other types, and how to classify them?

IMO, I think we can follow the docs of APISIX, https://apisix.apache.org/docs/apisix/installation-guide/
<img width="276" alt="image" src="https://user-images.githubusercontent.com/25628854/197705116-38ff7072-ea3c-4350-850b-dbc822e432d9.png">


The type also can be used in the dashboard, for example 
<img width="2248" alt="image" src="https://user-images.githubusercontent.com/25628854/197706260-8702aa1f-12d0-4805-b52e-e29473312d60.png">
The front-end can use the type field to list and filter the plugin.


> how to classify them

We can define the plugin type list as constant in the APISIX core first.

**Comment by pixeldin** [comment]
@starsz, I would love to try it out, can you assign it to me?

**Comment by pixeldin** [comment]
> "the auth is a bad name to me. It would be better to be named as consumer."

What about my thought is:
1. Stay and keep the `type` field in the original plugin, as reserved for logical judgment for the consumer, we can rename the type value of "auth" to "consumer" or whatever appropriate context.
2. Add a `category` field to the existing plugin or new plugin in the future, which indicate the category, and the optional value is like [General/Authentication/Security/Serverless, etc...].

This is what i plan to do, it's suitable?

**Comment by tokers** [comment]
> > "the auth is a bad name to me. It would be better to be named as consumer."
> 
> What about my thought is:
> 
> 1. Stay and keep the `type` field in the original plugin, as reserved for logical judgment for the consumer, we can rename the type value of "auth" to "consumer" or whatever appropriate context.
> 2. Add a `category` field to the existing plugin or new plugin in the future, which indicate the category, and the optional value is like [General/Authentication/Security/Serverless, etc...].
> 
> This is what i plan to do, it's suitable?

I like "category".

**Comment by tzssangglass** [comment]
IMO, I think it would be good to keep one of `type` or `category`.

**Comment by pixeldin** [comment]
# Usage of type 

This two places mentions the `type` field:
https://github.com/apache/apisix/blob/2f4a4dba2c0cbc426ae99133c2546112ea71dba8/apisix/consumer.lua#L46
https://github.com/apache/apisix/blob/2f4a4dba2c0cbc426ae99133c2546112ea71dba8/apisix/admin/consumers.lua#L55

# Docs about plugin category
From the docs, most plugin in the '**Authentication**' category will initialization with `type = 'auth'` in code, like [ basic-auth / jwt-auth / hmac-auth / wolf-rbac etc... ]  
https://github.com/apache/apisix/blob/2f4a4dba2c0cbc426ae99133c2546112ea71dba8/apisix/plugins/basic-auth.lua#L56

But I found **not all** plugins in the '**Authentication**' category will specify `type = 'auth'`, such as this:
https://apisix.apache.org/zh/docs/apisix/plugins/authz-casbin/

So I think the origin usage about the `type` is not `category` means, right?

**Comment by tzssangglass** [comment]
> So I think the origin usage about the `type` is not `category` means, right?

yes, `type` is not used to show the properties of the plugin

**Comment by pixeldin** [comment]
So I think maybe we can keep the `type` for old logic, add `category` to classify plugins.

**Comment by starsz** [comment]
> So I think maybe we can keep the `type` for old logic, add `category` to classify plugins.

Agree +1.

**Comment by shreemaan-abhishek** [comment]
@pixeldin any updates?

**Comment by smileby** [comment]
@shreemaan-abhishek  Hi, Hello, do you feel there is still a need for support in this matter?

**Comment by shreemaan-abhishek** [comment]
This looks like a good to have feature.

**Comment by smileby** [comment]
hi @shreemaan-abhishek i want to try

**Comment by shreemaan-abhishek** [comment]
assigned to you

**Comment by smileby** [comment]
@shreemaan-abhishek  I referred to #8362  and completed the PR quickly. If you have time, please check if there is any problem. Thank you.

**Comment by starsz** [comment]
Hello @smileby.Thanks for your contribution.After deep thinking of this, we don't need this feature now. The reason is that it will increase maintenance costs. So I will close this issue, and I am sorry for that.
