### ISSUE TITLE
bug: proxy-rewrite and proxy-mirror do not work together

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#8167]
### Current Behavior

The route configuration (omitted some irrelevant content):
```
{
    "uri": "/v1/hello/*",
    "plugins": {
        "proxy-mirror": {
            "sample_ratio": 1,
            "host": "http://mirror.api:8082"
        },
        "proxy-rewrite": {
            "regex_uri": [
                "/v1/(.*)",
                "/$1"
            ],
            "_meta": {
                "priority": 2000
            }
        }
    }
}
```

The client uses this URI to request:
```
GET /v1/hello
```

Requests to the upstream will be rewritten as:
```
GET /hello
```

But the request to the mirror address is still:
```
GET /v1/hello
```

**So the URI rewritten in `proxy-rewrite` does not actually take effect for `proxy-mirror`. (I have overridden the proxy-rewrite priority via `_meta.priority` and it will be executed first)**

### Expected Behavior

The modified URI in `proxy-rewrite` will take effect for `proxy-mirror`.

### Steps to Reproduce

1. Create a route by referring to the route configuration in the current behavior.
2. Request API
3. Check mirror service log

Explanation of reasons:
`proxy-rewrite` gets the URI from `ctx.var.uri`, writes it to the `upstream_uri` variable, and subsequently uses that variable instead of the original `uri` when forwarding upstream. `proxy-mirror` does not take this into account and uses the original `uri` variable directly. I think it should behave in such a way that the `uri` is used first and the `upstream_uri` is used when the value does not match the `upstream_uri`. If necessary we also need to modify the `proxy-rewrite` priority so that it takes precedence over `proxy-mirror`.

### Environment

- APISIX version (run `apisix version`): 2.15.0

**Comment by spacewander** [comment]
LGTM. As it is a break change, we need to discuss it in the mail list too.

**Comment by nfrankel** [comment]
>If necessary we also need to modify the proxy-rewrite priority so that it takes precedence over proxy-mirror

That part is handled by the `_meta_priority` attribute so it shouldn't be part of this issue IMHO

**Comment by tokers** [comment]
If we don't change the built-in priority, then let's update the docs to show the way to let them work together.

**Comment by hf400159** [comment]
I think we can provide an example in the documentation.

**Comment by bzp2010** [comment]
I've started a mailing list discussion for this, and you can reply to it. https://lists.apache.org/thread/8y3kxrwxl9yh9f049660kbc1ob8vhqkk

**Comment by nfrankel** [comment]
There's no reaction on the Mailing List. Can we proceed please?
