### ISSUE TITLE
bug: misclassification and misled of documents building-apisix

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#8168]
### Current Behavior

The documentation describes the "installation" of APISIX using the "source tarball". It is assigned in the "Development" section, but obviously, it is used for installation, not development. The user will comply by installing APISIX to `/usr/local/apisix` instead of building up a usable development environment where there is no Makefile, test cases, etc.

### Expected Behavior

We should use git clone instead of the source package for development environments.

### Steps to Reproduce

1. Open https://apisix.apache.org/docs/apisix/building-apisix/
2. Read documentation.
3. Be misled.

### Environment

- APISIX version (run `apisix version`): 3.0.0-beta and previous versions.

**Comment by tokers** [comment]
cc @mscb402 Would you like to do this?

**Comment by mscb402** [comment]
> cc @mscb402 Would you like to do this?

please assign to me
