### ISSUE TITLE
help request: curl 9180 port got Connection reset by peer

### ISSUE THREAD

**Issue by jeffreys-cat** [apache/apisix#8171]
### Description

I stop the containers and restart them because I do some changes to the config, and then the 9180 port seems not to work, I search for the issues but not found useful information.

![image](https://user-images.githubusercontent.com/11832969/197736922-7aae9d58-805c-4a57-8883-13866fb47050.png)

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
hi, Can you provide more information?

**Comment by tokers** [comment]
It looks like you suffer a network problem, could you try to access the `9180` inside the container?

**Comment by jeffreys-cat** [comment]
![image](https://user-images.githubusercontent.com/11832969/197748124-69046d6b-a8ff-447a-a2dc-4ca4bd2faa76.png)


> hi, Can you provide more information?

I post my docker-compose.yml config, export the 9180 port

**Comment by jeffreys-cat** [comment]
> 

![image](https://user-images.githubusercontent.com/11832969/197748614-15d47fb7-b21f-465a-8a9f-83e30f0217f0.png)

**Comment by jeffreys-cat** [comment]
I closed the issue because it caused by the version, Here is the dialog

**Comment by Hxhong** [comment]
> 

hello, I met the same problem. And the slack dialog can't open. Could you please show me the dialog here?
