### ISSUE TITLE
bug: file-logger plugin seems mix different row to  one

### ISSUE THREAD

**Issue by Lewisyixin** [apache/apisix#8172]
### Current Behavior

It seems file-logger plugin generate a mixed content in one row
I blocked some important data(Just to json values.)
![image](https://user-images.githubusercontent.com/17898688/197743687-3ebd3057-2488-4937-9047-3a3cb29f9dff.png)

{"timestamp":"2022-10-25T09:45:09+08:00","service_id":"service_id","body_bytes_sent":"0","upstream_response_time":0.001,"http_host":"http_host","http_cookie":"cookie_ignore","route_id":"cng00000000000798","remote_addr":"1.1.1.1","upstream_status":"304","status":304,"http_user_agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","request":"GET /apiv1/a.js HTTP/1.1","http_referer":"ht{"timestamp":"2022-10-25T09:45:09+08:00","service_id":"service_id","body_bytes_sent":"0","upstream_response_time":0.001,"http_host":"domain","http_cookie":"cookie_ignore","route_id":"cng00000000000798","remote_addr":"1.1.1.1","upstream_status":"304","status":304,"http_user_agent":"Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","request":"GET /api/a.js HTTP/1.1","http_referer":"tps://baidu.com//aaa","server_port":"443","upstream_addr":"1.1.1.1:3333","request_time":0,"http_x_forwarded_for":" "}
https://baidu.com/aaaa.js","server_port":"443","upstream_addr":"2.2.2.2:8080","request_time":0,"http_x_forwarded_for":" "}

### Expected Behavior

Only one line of log will be generated by per request

### Steps to Reproduce

It's occasional

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux apisix-01 5.4.190-1.el7.elrepo.x86_64 #1 SMP Tue Apr 19 11:42:30 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  3.4.18
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Duplicated to https://github.com/apache/apisix/issues/7839?

**Comment by tzssangglass** [comment]
> Oh yes, sry. And should I close this issue?

yes, consider it solved, feel free to reopen if you needed.
