### ISSUE TITLE
APISIX Dashboard should support APISIX v3 Admin API

### ISSUE THREAD

**Issue by Chever-John** [apache/apisix#8173]
### Current State

I found a mistake when I want to try the SSL Url according to the [documentation](https://apisix.apache.org/docs/apisix/admin-api/#ssl).

Then it shows me the 404 code.

After searching the code of APISIX-Dashboard, I must point out that **there is a typo error**.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/43690894/197749115-7ed6e005-8c8a-4978-8390-7ad08f01d5f6.png">

<img width="529" alt="image" src="https://user-images.githubusercontent.com/43690894/197748307-90e2b176-e76f-4249-ae70-cf191f6c036a.png">

### Desired State

Change the route from "/apisix/admin/ssls/{id}" to "/apisix/admin/ssl/{id}".

**Comment by hf400159** [comment]
please refer to https://github.com/apache/apisix/commit/ccc43ea329edcc60f950307d91c7440c58bfcb3f#diff-314aba53159447d362970019b540277cb61f1de163f4a28f25a1c71ebba0f7a6

**Comment by Chever-John** [comment]
@hf400159 Thanks!

It looks like that `APISIX V3` will change the URL from "/ssl" to "/ssls".

Maybe you can give an attention on the current doc if possible.

Thanks again!!!!!

**Comment by Ajay-singh1** [comment]
@Chever-John You can close this issue now.
