### ISSUE TITLE
Websocket proxy returns 502 (Bad Gateway)

### ISSUE THREAD

**Issue by Msiavashi** [apache/apisix#8175]
### Description

I'm running a sample echo websocket server on my localhost. I added a websocket enabled route ("/")  from dashboard with the rest of the configs as default. Then sat the upstream's Host to my "localhost" and port to "8080" (my web socket port) and leave the rest as default.

I access the websocket server directly using `wscat` and it works fine. However, when I try to access it using APISIX on address `ws://localhost:9080/` it returns 502 bad gateway.

BTW I'm running the echo websocket server as a Docker container connected to the apisix network.

Here is the route:

```json

{
  "uri": "/",
  "name": "websocket test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream": {
    "nodes": [
      {
        "host": "127.0.0.1",
        "port": 8080,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "enable_websocket": true,
  "status": 1
}

```

### Environment

APISIX version: 2.99.0 Docker
Operating system: Ubuntu 20.04

**Comment by tokers** [comment]
> BTW I'm running the echo websocket server as a Docker container connected to the apisix network.

So apisix and your websocket server are in different containers?

In such a case, apisix cannot access the websocket server through 127.0.0.1. Try websocket container's IP.
