### ISSUE TITLE
bug: ssl handshake failed

### ISSUE THREAD

**Issue by luofanyuguai** [apache/apisix#8183]
### Current Behavior

 Call  url 'https://{domain}' but get ssl error 

### Expected Behavior

Got a normal http server response

### Error Logs

2022/10/26 08:28:11 [error] 53#53: *99045 [lua] radixtree_sni.lua:146: match_and_set(): failed to find any SSL certificate by SNI: xx.example.com, context: ssl_certificate_by_lua*, client: 172.21.43.126, server: 0.0.0.0:9443

### Steps to Reproduce

1. Uploaded cert and key through by apisis-dashboard
2. Add a /etc/hosts domain record with target to Apisix server IP
3. Curl a url with 'https' scheme
4. Failed to call 

### Environment

Start docker compose by using example in https://github.com/apache/apisix-docker/example

**Comment by luofanyuguai** [comment]
In Apisix the ssl config path on etcd is  ` ssl_certificates, err = core.config.new("/ssls", `
But I found that In Apisix-dashboard the path was `HubKeySsl          HubKey = "ssl"`

**Comment by tokers** [comment]
@bzp2010 is it due to the compability between apisix 3.0 and dashboard?

**Comment by hf400159** [comment]
Dashboard is still using the 2.x version of the API

**Comment by luofanyuguai** [comment]
the image is  apache/apisix:2.99.0-debian
