### ISSUE TITLE
help request: How doest APISIX enable http2?

### ISSUE THREAD

**Issue by jeffreys-cat** [apache/apisix#8185]
### Description

I don't find any docs, And the below config seems no docs either. Both configs are invalid.
![image](https://user-images.githubusercontent.com/11832969/198183291-d2c71138-075e-4ba8-ab3f-4807f92dedc3.png)
![image](https://user-images.githubusercontent.com/11832969/198184621-e1cdbed7-b81d-4631-9ba8-505e09cfbca9.png)

### Environment

- APISIX version (run `apisix version`):2.99
- Operating system (run `uname -a`): centos 8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@jeffreys-cat  Hi, APISIX has removed this configuration in version 3.0,  you can see  https://github.com/apache/apisix/blob/e523132f35fe2eb7e1d06990d037f18f89c9dcba/conf/config-default.yaml#L103

**Comment by jeffreys-cat** [comment]
@Hazel6869 Got it, I write a redundant symbol
