### ISSUE TITLE
help request:  upstream rejected request with error 2 while reading response header from upstream

### ISSUE THREAD

**Issue by YangChaorix** [apache/apisix#8186]
### Description

when send the request such as :

`curl 127.0.0.1:9080/grpc/getAccount2`

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

error been found 

error:
upstream rejected request with error 2 while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /grpc/getAccount HTTP/1.1", upstream: "grpc://127.0.0.1:5200", host: "127.0.0.1:9080"

**nodejs or java grpc server config transcode  ok**
**only dotnet  grpc server config  transcode fail**

why?

config:

```
{
  "uri": "/grpc/getAccount2",
  "name": "grpc转换(3)",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "grpc-transcode": {
      "method": "GetAccount",
      "proto_id": "account2",
      "service": "MD.BasicService.AccountService"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "127.0.0.1",
        "port": 5200,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "scheme": "grpc"
  },
  "status": 1
}
```

the protobuf

```
syntax = "proto3";

package MD.BasicService;


service AccountService {

// 根据帐号获取账户信息(Email/Mobile 包含密码)
rpc GetAccount (GetAccountRequest) returns (GetAccountResponse) {
}

// 根据帐号获取账户信息
rpc GetAccounts (GetAccountsRequest) returns (GetAccountsResponse) {
}

// 根据accountId 获取信息
rpc GetAccountByAccountId (GetByAccountIdRequest) returns (GetAccountResponse) {
}

// 根据accountId 获取信息
rpc GetAccountByAutoId (GetAccountByAutoIdRequest) returns (GetAccountResponse) {
}

//根据更新时间获取account
rpc GetAccountIdsByUpdateTime(GetAccountIdsByTimeRequest) returns (GetAccountIdsByTimeResponse){
}

// 添加账户
rpc AddAccount (AddAccountRequest) returns (StringResponse) {
}

// 修改账号更新时间
rpc EditAccountUpdateTime (GetByAccountIdRequest) returns (BoolResponse) {
}

// 修改手机号为空
rpc EditMobilePhoneToNull (EditAccountToNullRequest) returns (BoolResponse) {
}

// 修改邮箱为空
rpc EditEmailToNull (EditAccountToNullRequest) returns (BoolResponse) {
}

// 修改手机帐号
rpc EditAccountMobilePhone (EditAccountMobilePhoneRequest) returns (BoolResponse) {
}

// 修改邮箱帐号
rpc EditAccountEmail (EditAccountEmailRequest) returns (BoolResponse) {
}

// 修改帐号密码
rpc EditAccountPasswordByAccountId (EditAccountPasswordByAccountIdRequest) returns (BoolResponse) {
}

// 根据邮箱修改密码
rpc EditAccountPasswordByEmail (EditAccountPasswordByEmailRequest) returns (BoolResponse) {
}

// 根据手机号码修改密码
rpc EditAccountPasswordByMobilePhone (EditAccountPasswordByMobilePhoneRequest) returns (BoolResponse) {
}


}


message EditAccountPasswordByMobilePhoneRequest {

// 请求id
string request_id = 1;

// 手机号码
string mobile_phone = 2;

// 新密码
string new_password = 3;
}

message EditAccountPasswordByEmailRequest {
// 请求id
string request_id = 1;

// 邮箱
string email = 2;

// 新密码
string new_password = 3;
}

message EditAccountPasswordByAccountIdRequest {

// 请求id
string request_id = 1;

// 账号id
string account_id = 2;

// 旧密码（已加密）
string old_password = 3;

// 新密码（已加密）
string new_password = 4;
}

message EditAccountEmailRequest {

// 请求id
string request_id = 1;

// 账号id
string account_id = 2;

// 邮件
string email = 3;
}

message EditAccountMobilePhoneRequest {

// 请求id
string request_id = 1;

// 账号id
string account_id = 2;

// 手机号
string mobile_phone = 3;
}

message EditAccountToNullRequest {

// 请求id
string request_id = 1;

// 账号id
string account_id = 2;

// 密码
string password = 3;
}

message GetAccountRequest {

// 请求id
string request_id = 1;

// 用户邮件或手机号码
string account = 2;

// 状态（1：正常，2：注销 3：未激活)
int32 status = 3;
}

message GetAccountResponse {

int32 code = 1;

string message = 2;

Account data = 3;

}

message Account {
int32 auto_id = 1;
// 账号id
string account_id = 2;
// 手机号
string mobile_phone = 3;
// 邮件
string email = 4;
// 密码
string password = 5;
// 状态（1：正常，2：注销 3：未激活)
int32 status = 6;
// 更新时间
int64 update_time = 7;
// 创建时间
int64 create_time = 8;
}

message GetAccountsRequest {
// 请求id
string request_id = 1;

// 手机号码或邮件
repeated string accounts = 2;
}

message GetAccountsResponse {
int32 code = 1;
string message = 2;
repeated Account data = 3;
}

message GetAccountByAutoIdRequest {

// 请求id
string request_id = 1;

// 账号autoid
int32 auto_id = 2;
}
message GetAccountIdsByTimeRequest{
// 请求id
string request_id = 1;
// 账号id
repeated string account_Ids=2;
//更新时间
int64 update_time=3;
}

message  GetAccountIdsByTimeResponse{
int32 code = 1;
string message = 2;
repeated string data = 3;
}


message AddAccountRequest {

// 请求id
string request_id = 1;

// 账号
string account = 2;

// 密码
string password = 3;

// 状态（1：正常，2：注销 3：未激活)
int32 status = 4;

// 姓名
string fullname = 5;

// 公司
string company_name = 6;

// 职位
string profession = 7;
}

//---- this is common request

// 根据单个网络Id请求
message GetByProjectIdRequest {

    // 请求模块id
    string request_id = 1;

    // 网络Id
    string project_id = 2;
}

// 根据多个网络Id请求
message GetByProjectIdsRequest {

    // 请求模块id
    string request_id = 1;

    // 网络Id
    repeated string project_ids = 2;

}

// 根据单个账号Id请求
message GetByAccountIdRequest {
    // 请求模块id
    string request_id = 1;

    // 账号Id
    string account_id = 2;
}

message  GetDepartmentIdsRequest{
    // 请求模块id
    string request_id = 1;

    // 账号Id
    string account_id = 2;

// 是否 仅正常网络(否则 为所有网络）
bool onlyNormalProject = 5;
}

message  GetDepartmentIdRequest{
    // 请求模块id
    string request_id = 1;

// 网络Id
string project_id = 3;

    // 账号Id
    string account_id = 5;
}

// 根据多个账号Id请求
message GetByAccountIdsRequest {
    // 请求模块id
    string request_id = 1;

    // 账号Id
    repeated string account_ids = 2;
}


//---- this is common response


// 布尔返回类型
message BoolResponse {

    // 状态码
    int32 code = 1;

    // 错误信息
    string message = 2;

    // 返回值
    bool data = 3;
}

// 字符串返回值
message StringResponse {

    // 状态码
    int32 code = 1;

    // 错误信息
    string message = 2;

    // 返回值
    string data = 3;
}

//整型返回值
message Int32Response {

    // 状态码
    int32 code = 1;

    // 错误信息
    string message = 2;

    // 返回值
    int32 data = 3;
}

//长整型返回值
message Int64Response {

    // 状态码
    int32 code = 1;

    // 错误信息
    string message = 2;

    // 返回值
    int32 data = 3;
}

```

but grpcurl  test is ok

```
./grpcurl -plaintext -import-path ./protos  -proto account2.proto  \
> -d '{"account":"test1"}' 127.0.0.1:5200 MD.BasicService.AccountService.GetAccount
{
  "code": 1,
  "message": "成功",
  "data": {
    
  }
}
```

who can help me ?

**Comment by Hazel6869** [comment]
@YangChaorix  Hi, there are error detail?

**Comment by YangChaorix** [comment]
> @YangChaorix Hi, there are error detail?

**Comment by YangChaorix** [comment]
> @YangChaorix Hi, there are error detail?

detail? there have only apisix error.log..

**Comment by YangChaorix** [comment]
@Hazel6869 you need other error detail？  can you guide me? thanks

**Comment by tokers** [comment]
1. What's the protobuf file that you uploaded?
2. How did you send request via APISIX?

**Comment by YangChaorix** [comment]
@tokers  I have perfected  the question，please have a look， thanks

**Comment by Hazel6869** [comment]
@YangChaorix Hi,  I don't see your input parameter  "account: test1" in  the request withAPISIX.

**Comment by YangChaorix** [comment]
@tokers   the input parameter "account: test1" is not required, even if I add parameters, the result is still the same;
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/24434787/198453041-9aa31c8a-4ea0-42ff-931a-f9d4675e4193.png">

so, how i can debug the upstream error response and see it in the log;  thanks a lot!!

**Comment by Hazel6869** [comment]
> @tokers the input parameter "account: test1" is not required, even if I add parameters, the result is still the same; <img alt="image" width="1063" src="https://user-images.githubusercontent.com/24434787/198453041-9aa31c8a-4ea0-42ff-931a-f9d4675e4193.png">
> 
> so, how i can debug the upstream error response and see it in the log; thanks a lot!!

Before enabling the Plugin, you have to add the content of your .proto or .pb files to APISIX. Do you do it ?

**Comment by YangChaorix** [comment]
> 

yes， i do it, .proto or .pb files i had tried both
<img width="635" alt="image" src="https://user-images.githubusercontent.com/24434787/198465207-dab437bc-331b-4701-a94a-417f8e9edfc6.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/24434787/198465361-08975aed-9d73-462c-a42e-4fa42b6bdf4e.png">

**Comment by YangChaorix** [comment]
> > @tokers the input parameter "account: test1" is not required, even if I add parameters, the result is still the same; <img alt="image" width="1063" src="https://user-images.githubusercontent.com/24434787/198453041-9aa31c8a-4ea0-42ff-931a-f9d4675e4193.png">
> > so, how i can debug the upstream error response and see it in the log; thanks a lot!!
> 
> @YangChaorix Before enabling the Plugin, you have to add the content of your .proto or .pb files to APISIX. Do you do it ?

@Hazel6869

**Comment by Hazel6869** [comment]
@YangChaorix  Error 2 is an UNKNOWN error, this one has no more details...  😅

**Comment by YangChaorix** [comment]
> @YangChaorix Error 2 is an UNKNOWN error, this one has no more details... 😅

What a head-scratcher！ i lost all my hair🤔

**Comment by Hazel6869** [comment]
> What a head-scratcher

why do you need dotnet grpc, may be  it's a language compatibility issue.  i also do experiment.

**Comment by YangChaorix** [comment]
> > What a head-scratcher
> 
> why do you need dotnet grpc, may be it's a language compatibility issue. i also do experiment.

we use different grpc server node，java，go，dotnet provide interface server，use apisix to transcode to http.

so you know ；which languages can not compatible ？such as dotnet..

**Comment by Hazel6869** [comment]
> > > What a head-scratcher
> > 
> > 
> > why do you need dotnet grpc, may be it's a language compatibility issue. i also do experiment.
> 
> we use different grpc server node，java，go，dotnet provide interface server，use apisix to transcode to http.
> 
> so you know ；which languages can not compatible ？such as dotnet..

@spacewander do you know this case?

**Comment by spacewander** [comment]
> nodejs or java grpc server config transcode ok
only dotnet grpc server config transcode fail

I am afraid I know nothing about dotnet. Maybe the gRPC server implementation in dotnet is a bit different from those in nodejs/Java.

**Comment by YangChaorix** [comment]
> > nodejs or java grpc server config transcode ok
> > only dotnet grpc server config transcode fail
> 
> I am afraid I know nothing about dotnet. Maybe the gRPC server implementation in dotnet is a bit different from those in nodejs/Java.

thanks a lot !!   I'll try again

**Comment by zhongzhiqiang** [comment]
you can set `grpc_set_header   Te trailers;` in your ngx_tpl.lua

**Comment by YangChaorix** [comment]
> you can set `grpc_set_header Te trailers;` in your ngx_tpl.lua

please tell me how to set.

set here ?

<img width="728" alt="image" src="https://user-images.githubusercontent.com/24434787/198951819-d7f6efcf-dc08-43f9-b16b-64cb7c8bc4b4.png">

**Comment by YangChaorix** [comment]
> you can set `grpc_set_header Te trailers;` in your ngx_tpl.lua

The problem has been solved, thanks a lot！！
