### ISSUE TITLE
help request: when limit-count uses redis for full speed limit, changing the count value cannot take effect immediately

### ISSUE THREAD

**Issue by 1024-zzw** [apache/apisix#8190]
### Description

第一种：limit-count直接使用redis作为全局限速使用
1、这是我的limit-count配置：
count: 10
time_window: 60
key_type: var
key: remote_addr
rejected_code: 539
policy: redis
group: remote_addr
allow_degradation: true
show_limit_quota_header: true
redis_host: xxxxxx.redis.rds.aliyuncs.com
redis_port: 6379
redis_password: xxxxxx
redis_database: 40
redis_timeout: 1000
2、当我修改count=1500，从响应头仍然反馈是10的限速
count: 1500
time_window: 60
key_type: var
key: remote_addr
rejected_code: 539
policy: redis
group: remote_addr
allow_degradation: true
show_limit_quota_header: true
redis_host: xxxxxx.redis.rds.aliyuncs.com
redis_port: 6379
redis_password: xxxxxx
redis_database: 40
redis_timeout: 1000
第二种：先使用local，后使用redis作为全局限速使用，再改为local，发现local的限速即使配置了，也没有
呈现出限速的效果
第三种：直接使用local，这是没有问题的

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux apisix-76fcff66bd-qsznl 5.17.4-1.el7.elrepo.x86_64 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"etcdserver":"3.4.18","etcdcluster":"3.4.0"}
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
Please provide a specific reproduction process.

**Comment by monkeyDluffy6017** [comment]
@1024-zzw Is it possible that the command `set count=1500` was no successfully? Could you use curl command and check the response

**Comment by monkeyDluffy6017** [comment]
I notice that you use `group` in your config: `group: remote_addr`, when use `group` in the route, you couldn't not modify the `limit count` plugin any more, because there are other routes may share the same plugin. 
try to modify the `count` and `group` together.

**Comment by 1024-zzw** [comment]
When we use redis to integrate into this limit-count plugin, every time we adjust the parameters, we need to restart the pod of apisix to make it take effect

**Comment by monkeyDluffy6017** [comment]
Nothing about other plugins, once use `group` in `limit-count` plugin, you cannot modify the configuration any more.

**Comment by 1024-zzw** [comment]
2022/10/28 17:14:28 [error] 44#44: *79732 [lua] limit-count.lua:172: check_schema(): previous limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"disable":false,"show_limit_quota_header":true,"time_window":10,"count":1000,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 44#44: *79732 [lua] limit-count.lua:174: check_schema(): current limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"show_limit_quota_header":true,"time_window":10,"count":111,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 44#44: *79732 [lua] config_etcd.lua:574: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin limit-count err: group conf mismatched,  etcd key: /apisix/routes, context: ngx.timer
2022/10/28 17:14:28 [error] 46#46: *79728 [lua] limit-count.lua:172: check_schema(): previous limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"disable":false,"show_limit_quota_header":true,"time_window":10,"count":1000,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 46#46: *79728 [lua] limit-count.lua:174: check_schema(): current limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"show_limit_quota_header":true,"time_window":10,"count":111,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 46#46: *79728 [lua] config_etcd.lua:574: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin limit-count err: group conf mismatched,  etcd key: /apisix/routes, context: ngx.timer
2022/10/28 17:14:28 [error] 43#43: *79720 [lua] limit-count.lua:172: check_schema(): previous limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"disable":false,"show_limit_quota_header":true,"time_window":10,"count":1000,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 43#43: *79720 [lua] limit-count.lua:174: check_schema(): current limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"show_limit_quota_header":true,"time_window":10,"count":111,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 43#43: *79720 [lua] config_etcd.lua:574: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin limit-count err: group conf mismatched,  etcd key: /apisix/routes, context: ngx.timer
2022/10/28 17:14:28 [error] 49#49: *79648 [lua] limit-count.lua:172: check_schema(): previous limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"disable":false,"show_limit_quota_header":true,"time_window":10,"count":1000,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 49#49: *79648 [lua] limit-count.lua:174: check_schema(): current limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"show_limit_quota_header":true,"time_window":10,"count":111,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 49#49: *79648 [lua] config_etcd.lua:574: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin limit-count err: group conf mismatched,  etcd key: /apisix/routes, context: ngx.timer
2022/10/28 17:14:28 [error] 45#45: *79760 [lua] limit-count.lua:172: check_schema(): previous limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"disable":false,"show_limit_quota_header":true,"time_window":10,"count":1000,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 45#45: *79760 [lua] limit-count.lua:174: check_schema(): current limit-conn group remote_addr conf: {"redis_password":"xxxxxxx","rejected_code":539,"redis_port":6379,"show_limit_quota_header":true,"time_window":10,"count":111,"redis_timeout":1000,"group":"remote_addr","allow_degradation":true,"key_type":"var","policy":"redis","key":"remote_addr","redis_database":40,"redis_host":"r-bp1965rcv5ifxnhhbp.redis.rds.aliyuncs.com"}, context: ngx.timer
2022/10/28 17:14:28 [error] 45#45: *79760 [lua] config_etcd.lua:574: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plugin limit-count err: group conf mismatched,  etcd key: /apisix/routes, context: ngx.timer

**Comment by tokers** [comment]
> Nothing about other plugins, once use `group` in `limit-count` plugin, you cannot modify the configuration any more. **try to modify the `count` and the `group` together.**

@monkeyDluffy6017 Can we optimize the Admin API to warn the users or just reject the change request?

**Comment by monkeyDluffy6017** [comment]
@tokers The request is rejected already, remember to check the return value
```
{"error_msg":"failed to check the configuration of plugin limit-count err: group conf mismatched"}
```

**Comment by monkeyDluffy6017** [comment]
<img width="842" alt="image" src="https://user-images.githubusercontent.com/9354193/198918736-76c7ab88-8a9e-4490-b75d-47522853b730.png">
@1024-zzw From your error log, we found that the `group` is the same, but the `count` is different, so you need modify `group` and `count` at the same time

**Comment by tokers** [comment]
> @tokers The request is rejected already, remember to check the return value
> 
> ```
> {"error_msg":"failed to check the configuration of plugin limit-count err: group conf mismatched"}
> ```

Frankly this error message is still confusing? Why "group conf mismatched" is the hurdle to update my config? A straightforward error message will be better.

**Comment by tzssangglass** [comment]
> A straightforward error message will be better.

if user wants to update the config of limit-count plugin, we can tell user that `modify the count and the group together`

**Comment by airstring** [comment]
> modify `group` and `count` at the same time

After i modify `group` and `count` at the same time, will I have to  change all the routes to use the new group ?

**Comment by airstring** [comment]
@monkeyDluffy6017  After i modify group and count at the same time, will I have to change all the routes to use the new group ?

**Comment by shreemaan-abhishek** [comment]
This information has been discussed in #10102 and a PR was also raised #10103
