### ISSUE TITLE
help request:  Questions about global plugins and plugins on the route

### ISSUE THREAD

**Issue by zuiyangqingzhou** [apache/apisix#8193]
### Description

I've enabled a global plugin, such as limit-count, which returns 403 in the access phase when a certain threshold is reached, and I've enabled the response_rewrite plugin on route X.

I find that the header_filter phase of the response_rewrite plugin does not execute when I keep requesting route X that is restricted to return 403.

Is it normal ?

### Environment

- APISIX version (run `apisix version`):  2.10.5
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
It doesn't look normal, do you have a reproducible test case?

**Comment by zuiyangqingzhou** [comment]
> I checked the code, and the route-level plugin is loaded after the global rules are executed, which means that if you `exit(403)` in the global plugin, the route-level plugin will not be loaded. There are no plugins available in APISIX when `header_filter` is executed.

I confirm that you mean,  if `exit(403)` in the global plugin,  the route-level plugin will not be execute？ @soulbird

**Comment by tzssangglass** [comment]
> I confirm that you mean, if `exit(403)` in the global plugin, the route-level plugin will not be execute？ @soulbird

yes

**Comment by shreemaan-abhishek** [comment]
closing as fixed by #9815
