### ISSUE TITLE
bug: proxy-rewrite X-Forwarded-For doesn't work.

### ISSUE THREAD

**Issue by wangfeng22** [apache/apisix#8195]
### Current Behavior

I have set proxy-rewrite X-Forwarded-For header, but It's still invaild.

### Steps to Reproduce

1. Create a route with the X-Forwarded-For of headers rewrited.
2. Send a request through this route, and watch the back-end.

### Environment

- APISIX version (run `apisix version`): 2.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@wangfeng22  Hi, can you give me your  related curl?

**Comment by wangfeng22** [comment]
> @wangfeng22 Hi, can you give me your related curl, I'll check it out for you.
1. Create a random route, set proxy-rewrite X-Forwarded-For header, and watch the back-end.
```
curl --location --request GET 'http://test.test/api' \
--header 'X-Forwarded-For: 1.1.1.1'
```

**Comment by Hazel6869** [comment]
@wangfeng22  Can you give me the curl for configure proxy-rewrite plugin

**Comment by wangfeng22** [comment]
> @wangfeng22 Can you give me the curl for configure proxy-rewrite plugin
```
{
  "uri": "/*",
  "name": "开发机测试路由",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "host": "test.test",
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "X-Forwarded-For": "AAAA"
      }
    }
  },
  "upstream_id": "431751431687504807",
  "status": 1
}
```

**Comment by Hazel6869** [comment]
@wangfeng22 Hold on, let me give you an example.

**Comment by monkeyDluffy6017** [comment]
Would you like to submit a pr to fix this problem? @wangfeng22

**Comment by wangfeng22** [comment]
> @wangfeng22 I found 'X-Forwarded-For' has been configured in the file nginx.conf, so you can't change it. 😅 ![image](https://user-images.githubusercontent.com/30279880/198499987-19a1e2bb-252d-4069-945a-99d1e31dc9a2.png)

But you can change X-Forwarded-Proto, X-Forwarded-Host..., is that true?

**Comment by wangfeng22** [comment]
@monkeyDluffy6017 yes, I will try to figure it out this weekend.

**Comment by wangfeng22** [comment]
> @monkeyDluffy6017 yes, I will try to figure it out this weekend.

@monkeyDluffy6017 I think I don't know how to fix it.

**Comment by Hazel6869** [comment]
> > @wangfeng22 I found 'X-Forwarded-For' has been configured in the file nginx.conf, so you can't change it. 😅 ![image](https://user-images.githubusercontent.com/30279880/198499987-19a1e2bb-252d-4069-945a-99d1e31dc9a2.png)
> 
> But you can change X-Forwarded-Proto, X-Forwarded-Host..., is that true?

I also can't, this is not allowed.

**Comment by zuiyangqingzhou** [comment]
> @monkeyDluffy6017 yes, I will try to figure it out this weekend.

you can try this: https://github.com/apache/apisix/discussions/5091

**Comment by zuiyangqingzhou** [comment]
> @monkeyDluffy6017 yes, I will try to figure it out this weekend.

@wangfeng22   you can try this: https://github.com/apache/apisix/discussions/5091

**Comment by monkeyDluffy6017** [comment]
@wangfeng22 Try to fix like this: https://github.com/apache/apisix/pull/4260
