### ISSUE TITLE
help request: How dest APISIX set multi response-rewrite plugin

### ISSUE THREAD

**Issue by jeffreys-cat** [apache/apisix#8199]
### Description

How dest APISIX set multi response-rewrite plugin?
If Accept-Language match en then rewrites to en.goose.com, otherwise match cn rewrites to cn.goose.com.

My config is invalid, they will be merged. How can i config this rule?

![image](https://user-images.githubusercontent.com/11832969/198517943-ad5d531a-a622-4e2b-be0b-045b7a6bdb4a.png)
I

### Environment

- APISIX version (run `apisix version`):2.99
- Operating system (run `uname -a`):centos 8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@jeffreys-cat Hi, why do you need two?

**Comment by jeffreys-cat** [comment]
> @jeffreys-cat Hi, why do you need two?

Because I want to route to a different domains by browser language, which are en.goose.com and cn.goose.com

**Comment by Hazel6869** [comment]
> > @jeffreys-cat Hi, why do you need two?
> 
> Because I want to route to different domains by browser language, en.goose.com and cn.goose.com. If the Accept-Language is en, the route to en.goose.com, otherwise to cn.goose.com.

if you only have two cases,  you can one use response-rewrite, one use  default. 😄

**Comment by jeffreys-cat** [comment]
> > > @jeffreys-cat Hi, why do you need two?
> > 
> > 
> > Because I want to route to different domains by browser language, en.goose.com and cn.goose.com. If the Accept-Language is en, the route to en.goose.com, otherwise to cn.goose.com.
> 
> if you only have two cases, you can one use response-rewrite, one use default. 😄

Can you give me an example? How to set the default?

**Comment by Hazel6869** [comment]
@jeffreys-cat Hi you can use proxy-rewrite to configure different uri.
![image](https://user-images.githubusercontent.com/30279880/198537435-330d0a26-3b97-4523-9e63-3a579e07b5a2.png)

**Comment by Hazel6869** [comment]
> > > > @jeffreys-cat Hi, why do you need two?
> > > 
> > > 
> > > Because I want to route to different domains by browser language, en.goose.com and cn.goose.com. If the Accept-Language is en, the route to en.goose.com, otherwise to cn.goose.com.
> > 
> > 
> > if you only have two cases, you can one use response-rewrite, one use default. 😄
> 
> Can you give me an example? How to set the default?

the meaning of default is your server （the status with not APISIX plugin）

**Comment by jeffreys-cat** [comment]
> 

Thank you, I tried, but not working, I can't set https://en.goose.com as uri's value, I need the whole address redirected to the new domain. eg. I visit www.goose.com, I want to redirect to en.goose.com.

**Comment by tokers** [comment]
> > @jeffreys-cat Hi, why do you need two?
> 
> Because I want to route to different domains by browser language, en.goose.com and cn.goose.com. If the Accept-Language is en, the route to en.goose.com, otherwise to cn.goose.com.

Try to split your original route to two, with the help of the route `vars` field (fine-grained route control).

**Comment by Hazel6869** [comment]
> 

@jeffreys-cat yes, you need two routes.

**Comment by Hazel6869** [comment]
@jeffreys-cat  I give you an example  more detailed  `➜  example git:(master) ✗ curl http://127.0.0.1:9080/apisix/admin/routes/1  \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/test/index.html",
    "vars": [
    [
      "arg_http_accept_language",
      "==",
      "en"
    ]
  ],
    "plugins": {
        "proxy-rewrite": {
            "uri": "/get?$args",
            "scheme": "http",
            "host": "iresty.com",
            "headers": {
                "Location": "https://cn.goose.com"
            }
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'
{"action":"set","node":{"key":"\/apisix\/routes\/1","value":{"methods":["GET"],"plugins":{"proxy-rewrite":{"uri":"\/get?$args","scheme":"http","headers":{"Location":"https:\/\/cn.goose.com"},"use_real_request_uri_unsafe":false,"host":"iresty.com"}},"id":"1","upstream":{"scheme":"http","hash_on":"vars","nodes":{"httpbin.org":1},"type":"roundrobin","pass_host":"pass"},"uri":"\/test\/index.html","priority":0,"status":1,"update_time":1667181078,"vars":[["arg_http_accept_language","==","en"]],"create_time":1665568096}}}
➜  example git:(master) ✗  curl -X GET 'http://127.0.0.1:9080/test/index.html?http_accept_language=en' -v
Note: Unnecessary use of -X or --request, GET is already inferred.
* Uses proxy env variable http_proxy == 'http://127.0.0.1:7890'
*   Trying 127.0.0.1:7890...
* Connected to (nil) (127.0.0.1) port 7890 (#0)
> GET http://127.0.0.1:9080/test/index.html?http_accept_language=en HTTP/1.1
> Host: 127.0.0.1:9080
> User-Agent: curl/7.81.0
> Accept: */*
> Proxy-Connection: Keep-Alive
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Length: 485
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Connection: keep-alive
< Content-Type: application/json
< Date: Mon, 31 Oct 2022 01:51:38 GMT
< Keep-Alive: timeout=4
< Proxy-Connection: keep-alive
< Server: APISIX/2.15.0
<
{
  "args": {
    "http_accept_language": [
      "en",
      "en"
    ]
  },
  "headers": {
    "Accept": "*/*",
    "Accept-Encoding": "gzip",
    "Host": "iresty.com",
    "Location": "https://cn.goose.com",
    "User-Agent": "curl/7.81.0",
    "X-Amzn-Trace-Id": "Root=1-635f2a2a-272df4c93b26d19c2d973b4f",
    "X-Forwarded-Host": "127.0.0.1"
  },
  "origin": "172.19.0.1, 61.241.66.251",
  "url": "http://127.0.0.1/get?http_accept_language=en&http_accept_language=en"
}
* Connection #0 to host (nil) left intact
➜  example git:(master) ✗`

**Comment by jeffreys-cat** [comment]
@Hazel6869 It works, Thank you very much! APISIX community has great support for user👍
