### ISSUE TITLE
help request: http_ssl_phase(): failed to fetch ssl config

### ISSUE THREAD

**Issue by Msiavashi** [apache/apisix#8207]
### Description

I have deployed the APISIX gateway on GKE using the following command: 

`helm install apisix apisix/apisix --set gateway.type=LoadBalancer --set ingress-controller.enabled=true --namespace ingress-apisix --set ingress-controller.config.apisix.serviceNamespace=ingress-apisix --set gateway.tls.enabled=true`

I also set our Cloudflare SSL/TLS via the SSL tab in apisix-dashboard and it works fine.

However, when I try proxying requests to some HTTPS upstream it returns 502 Bad Gateway and the following error is logged in GCP:

`http_ssl_phase(): failed to fetch ssl config: failed to find SNI: please check if the client requests via IP or uses an outdated protocol`

The thing is that it works perfectly with some HTTPS upstreams, like this website (https://timeapi.io/swagger/index.html) but it fails with other HTTPS upstream! 

### Environment

- APISIX version (run `apisix version`): 2.99
- Operating system (run `uname -a`): GKE

**Comment by tokers** [comment]
Do these upstreams enable the mTLS?

**Comment by tokers** [comment]
@Msiavashi Configurations like Route and Upstream must be provided, or it's tough to troubleshoot.

**Comment by Msiavashi** [comment]
@tokers Here is the config that raises the error.

```json
{
  "uri": "/*",
  "name": "authnapi",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream": {
    "nodes": [
      {
        "host": "authnapi.idmelon.com",
        "port": 443,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "https",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}

```

**Comment by mscb402** [comment]
Mabe you should change `pass_host` to `rewrite`

> @tokers Here is the config that raises the error.
> 
> ```json
> {
>   "uri": "/*",
>   "name": "authnapi",
>   "methods": [
>     "GET",
>     "POST",
>     "PUT",
>     "DELETE",
>     "PATCH",
>     "HEAD",
>     "OPTIONS",
>     "CONNECT",
>     "TRACE"
>   ],
>   "upstream": {
>     "nodes": [
>       {
>         "host": "authnapi.idmelon.com",
>         "port": 443,
>         "weight": 1
>       }
>     ],
>     "timeout": {
>       "connect": 6,
>       "send": 6,
>       "read": 6
>     },
>     "type": "roundrobin",
>     "scheme": "https",
>     "pass_host": "pass",
>     "keepalive_pool": {
>       "idle_timeout": 60,
>       "requests": 1000,
>       "size": 320
>     }
>   },
>   "status": 1
> }
> ```

Hello. This look like an SNI error. Maybe it's because it passes the client's host to the Upstream, Please change ` "pass_host": "pass",` to ` "pass_host": "rewrite",`. And try again.

**Comment by tokers** [comment]
What are the common name and SAN list in your certificate, also, what's the SNI in the TLS handshake?

**Comment by Msiavashi** [comment]
> > @tokers Here is the config that raises the error.
> > ```json
> > {
> >   "uri": "/*",
> >   "name": "authnapi",
> >   "methods": [
> >     "GET",
> >     "POST",
> >     "PUT",
> >     "DELETE",
> >     "PATCH",
> >     "HEAD",
> >     "OPTIONS",
> >     "CONNECT",
> >     "TRACE"
> >   ],
> >   "upstream": {
> >     "nodes": [
> >       {
> >         "host": "authnapi.idmelon.com",
> >         "port": 443,
> >         "weight": 1
> >       }
> >     ],
> >     "timeout": {
> >       "connect": 6,
> >       "send": 6,
> >       "read": 6
> >     },
> >     "type": "roundrobin",
> >     "scheme": "https",
> >     "pass_host": "pass",
> >     "keepalive_pool": {
> >       "idle_timeout": 60,
> >       "requests": 1000,
> >       "size": 320
> >     }
> >   },
> >   "status": 1
> > }
> > ```
> 
> Hello. This look like an SNI error. Maybe it's because it passes the client's host to the Upstream, Please change ` "pass_host": "pass",` to ` "pass_host": "rewrite",`. And try again.

Hello. This worked. Thanks for the solution.

I see a custom hostname is gonna be deprecated soon. Do you think this is a good idea to stick with this solution?
![image](https://user-images.githubusercontent.com/13716075/199014801-c838d35b-b64d-48a1-979b-e89aaf5cb338.png)

**Comment by juzhiyuan** [comment]
Hi @Msiavashi 👋 Do you have any updates on this issue?

**Comment by Msiavashi** [comment]
@juzhiyuan  Unfortunately no. I used the DNS proxy of cloud lab with the "pass_host": "rewrite" to get it working.
