### ISSUE TITLE
Python custom plugin problem after apisix 2.14 switches to 3.0

### ISSUE THREAD

**Issue by coolmingwu** [apache/apisix#8211]
### Current Behavior

切换到3.0后，执行apisix restart后服务终端，只是换了个源镜像，更换后的镜像为2.99-centos，其他操作无变化，2.14版本可以正常使用，但是2.99不可以
![image](https://user-images.githubusercontent.com/93962343/198951225-861e17f0-c8ce-4002-a2b7-995a218bcacf.png)

### Error Logs

dockerfile :

ADD apisix-python-plugin-runner /apisix-python-plugin-runner
COPY config/test_config.yaml /usr/local/apisix/conf/config.yaml
COPY run.sh /run.sh
ENV APISIX_LISTEN_ADDRESS=unix:/tmp/runner.sock
RUN python3 setup.py install --force
WORKDIR /apisix-python-plugin-runner
EXPOSE 9080 9091 9443 9092
CMD bash /run.sh

run.sh :
/usr/bin/apisix restart
tail -f /dev/null 

### Steps to Reproduce

apache/apisi:2.99.0-centos 

### Environment

- APISIX version (run `apisix version`):2.14
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
you mean execute `/usr/bin/apisix restart` in docker failed?
