### ISSUE TITLE
help request: golang client or sdk to integrate apisix

### ISSUE THREAD

**Issue by ArenaSu** [apache/apisix#8221]
### Description

Is there apisix golang client or sdk to use ? I can not find it yet.

### Environment

- APISIX version (run `apisix version`): helm install latest version
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): k8s 1.23.7 env
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by opencmit1** [comment]
The user-defined plug-ins of golang
https://github.com/apache/apisix-go-plugin-runner

**Comment by ArenaSu** [comment]
> The user-defined plug-ins of golang https://github.com/apache/apisix-go-plugin-runner

It looks like apisix plugin tools. What i want is a golang SDK or client  to communicate with apisix admin API.

**Comment by hf400159** [comment]
Why use a client or SDK?  Can you give a specific scenario?

**Comment by ArenaSu** [comment]
> Why use a client or SDK? Can you give a specific scenario?

API gateway service is a component of PaaS platform. And we have multi k8s clusters as each cluster may have one or more API Gateway instances. PaaS manage API gateway configs via APIs by using golang client or sdks.

**Comment by tzssangglass** [comment]
> It looks like apisix plugin tools. What i want is a golang SDK or client to communicate with apisix admin API. I want to call apisix apis to manage routers, upstreams and services in my golang application.

We don't have such an SDK yet.

**Comment by ArenaSu** [comment]
> We don't have such an SDK yet, we plan to support export OpenAPI by `APISIX-Dashboard` and generate SDKs for go with the help of OpenAPI tools, like: https://github.com/OpenAPITools/openapi-generator

Looking forward to the feature and the generated SDKs is what i need.
