### ISSUE TITLE
when apisix can use grpc client to connect etcd cluster?

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#8229]
### Description

![image](https://user-images.githubusercontent.com/59631965/199399076-1912d9ee-f569-4e2b-b500-63e1fa85c55b.png)
i saw that apisix will use native grpc client to connect etcd cluster to reduce connections,but i don't find this feature in 3.0's change logs.so i want to know when and which version apisix can support this feature?thank every contributers so much!

### Environment

apisix :3.0

**Comment by Hazel6869** [comment]
@Nobilta  Are you find in this file? https://github.com/apache/apisix/blob/release/3.0/CHANGELOG.md

**Comment by Nobilta** [comment]
> @Nobilta Are you find in this file? https://github.com/apache/apisix/blob/release/3.0/CHANGELOG.md

i don't find this future,so i want to know when we can use this future

**Comment by Hazel6869** [comment]
> 

maybe the ChangeLOG don't  have the detail,  but you can use this feature.

**Comment by Nobilta** [comment]
> > 
> 
> @Nobilta maybe the ChangeLOG don't have the detail, but you can use this feature.

thank you so much,if i should change some config to make this feature become effective?beacuse in doc i don't find module about this feature

**Comment by tzssangglass** [comment]
> thank you so much,if i should change some config to make this feature become effective?beacuse in doc i don't find module about this feature

This is handled in lua-resty-etcd, ref: https://github.com/api7/lua-resty-etcd/commits/master

**Comment by Nobilta** [comment]
> > thank you so much,if i should change some config to make this feature become effective?beacuse in doc i don't find module about this feature
> 
> This is handled in lua-resty-etcd, ref: https://github.com/api7/lua-resty-etcd/commits/master

but i don't find i how i can use grpc instead of post to watch etcd😂and i can see many post requests named v3/watch to ask my etcd in apisix v3.0

**Comment by tzssangglass** [comment]
> but i don't find i how i can use grpc instead of post to watch etcd😂and i can see many post requests named v3/watch to ask my etcd,my apisix version is v3.0


This will not change until a new version of lua-resty-etcd is released and APISIX adopts the new version. 3.0 is not the end but the beginning of these new features. If the new version 3.0 carries a lot of unproven features, I think it will be a disaster.

so wait some more time, let change happen.

**Comment by Nobilta** [comment]
> 



> > but i don't find i how i can use grpc instead of post to watch etcd😂and i can see many post requests named v3/watch to ask my etcd,my apisix version is v3.0
> 
> This will not change until a new version of lua-resty-etcd is released and APISIX adopts the new version. 3.0 is not the end but the beginning of these new features. If the new version 3.0 carries a lot of unproven features, I think it will be a disaster.
> 
> so wait some more ti
