### ISSUE TITLE
help request:  is apisix support nginx  proxy_hide_header parameter? 

### ISSUE THREAD

**Issue by overstarry** [apache/apisix#8230]
### Description

 is apisix support nginx  proxy_hide_header parameter? 

### Environment

 is apisix support nginx  proxy_hide_header parameter? 
I want to hide the Content-Disposition，
nginx conf:
```
proxy_hide_header Content-Disposition
```

**Comment by tokers** [comment]
Try the proxy-rewrite plugin.

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/199513855-87c8914d-a9ef-49a1-83c5-1923ec360ff4.png)
of no avail

**Comment by overstarry** [comment]
@tokers

**Comment by mscb402** [comment]
> ![image](https://user-images.githubusercontent.com/23260162/199513855-87c8914d-a9ef-49a1-83c5-1923ec360ff4.png) of no avail

Is Content-Disposition header exist in response? If so, please use response-rewrite plugin.

```
"response-rewrite": {
            "headers": {
                "set": {
                    "Content-Disposition": inline,
                }
            }
}
```

**Comment by overstarry** [comment]
@mscb402 Tried and failed

**Comment by tokers** [comment]
> @tokers

Sorry, I just misunderstood your meaning, you can try the response rewrite plugin just like @mscb402 said.

**Comment by mscb402** [comment]
> @mscb402 Tried and failed

Can you share more detail

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/199695348-e406dd76-7e32-475f-9176-2b3dac772af6.png)

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/199699452-a8340d40-d465-435a-9ff9-7da2f0043d33.png)

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/199699644-01dd9e35-41e1-4c5b-94d2-73c0ca4ea13b.png)

**Comment by overstarry** [comment]
@mscb402

**Comment by overstarry** [comment]
remove Tried and failed

**Comment by tokers** [comment]
@overstarry Did you some error log entries in APISIX `error.log`?

**Comment by overstarry** [comment]
no

**Comment by mscb402** [comment]
Please share the router config and more log detail

**Comment by mscb402** [comment]
And apisix version

**Comment by overstarry** [comment]
`{
  "uri": "/*",
  "name": "xx",
  "host": "xxx",
  "plugins": {
    "proxy-rewrite": {
      "host": "xxx",
      "regex_uri": [
        "/(.*)$",
        "/xx/${1}"
      ]
    },
    "response-rewrite": {
      "disable": false,
      "headers": {
        "remove": [
          "Content-Disposition"
        ]
      },
      "vars": [
        [
          "status",
          "==",
          200
        ]
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "xxx",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}`

**Comment by overstarry** [comment]
![image](https://user-images.githubusercontent.com/23260162/199871974-75ce216e-2a01-4338-b75e-9d07ba720dad.png)

**Comment by overstarry** [comment]
1xxx - - [03/Nov/2022:10:34:36 +0000] xxx "GET /index.html HTTP/1.1" 200 5556 0.003 "-" "curl/7.75.0" 47.253.30.231:80 200 0.003 "xxx"

**Comment by mscb402** [comment]
Look like you are using version 2.13. This version does not support Remove/Add/Set Header. https://apisix.apache.org/docs/apisix/2.13/plugins/response-rewrite/
Please use this config:

```
"response-rewrite": {
            "headers": {
                    "Content-Disposition": "inline"
            }
}
```

or
```
"response-rewrite": {
            "headers": {
                    "Content-Disposition": ""
            }
}
```

Please try again

**Comment by overstarry** [comment]
{
  "uri": "/*",
  "name": "xx",
  "host": "xixi.xx",
  "plugins": {
    "proxy-rewrite": {
      "host": "xx.com",
      "regex_uri": [
        "/(.*)$",
        "/xx/${1}"
      ]
    },
    "response-rewrite": {
      "disable": false,
      "headers": {
        "Content-Disposition": "inline"
      },
      "vars": [
        [
          "status",
          "==",
          200
        ]
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "xx",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}

**Comment by overstarry** [comment]
ok，thanks
