### ISSUE TITLE
Version 3.0.0 Workflow plug-in feature asks：Can I set multiple groups of time_window for the same case when setting limit-count

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#8234]
### Description

As a user ,When I used the Version 3.0.0-beta apixis feature  Workflow  to set the limit-count plugin , can I set multiple groups of time_window for the same case when setting actions as limit-count?
Examples on the website looks like  :

 "workflow":{
            "rules":[
                {
                    "case":[
                        ["uri", "==", "/hello/v2/appid"]
                    ],
                    "actions":[
                        [
                            "limit-count",
                            {
                                "count":2,
                                "time_window":60,
                                "rejected_code":429
                            }
                        ]
                    ]
                }
            ]
        }

If I want to set the limit-count of /hello/v2/appid in minutes, hours and days at the same time, how do I set the time_window ?Does Workflow support this function?  If APISIX is not supported, can this requirement be met

**Comment by spacewander** [comment]
Currently, only one time_window can be used in the limit-count action.
To support multiple time_window, we can either add this support in limit-count plugin first, or extend the workflow plugin to remove the TODO: https://github.com/apache/apisix/blob/eef518f170ba0cc19d1efd4df49ee2a49280eaac/apisix/plugins/workflow.lua#L150
