### ISSUE TITLE
bug: 3.0版本使用Python插件apisix-8.sock文件权限问题

### ISSUE THREAD

**Issue by coolmingwu** [apache/apisix#8236]
### Current Behavior

3.0用了python插件后，生成的/apisix-python-plugin-runner/conf下的apisix-8.sock 这个文件总是没有w权限，必须手动赋予，2,14的版本没有这个问题

### Steps to Reproduce

docker-images版本：3.0.0-centos

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
docker-images版本：3.0.0-centos

**Comment by mscb402** [comment]
Can you give more details?
