### ISSUE TITLE
help request: upstream.nodes.host set domain invalid

### ISSUE THREAD

**Issue by wenxiHome** [apache/apisix#8237]
### Description

local up_conf = {
        type = "roundrobin",
        pass_host = "rewrite",
        upstream_host = "geo.datav.aliyun.com",
        scheme = "http",
        nodes = {
            { host = "geo.datav.aliyun.com", port = 80, weight = 1 }
        }
    }
    upstream.set(ctx, up_conf.type .. "#route_" .. matched_route.value.id,
            ctx.conf_version, up_conf)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
Can you provide more info? Steps to reproduce and Route's configuration.

**Comment by wenxiHome** [comment]
upstream config
![image](https://user-images.githubusercontent.com/41821549/199654475-379cd005-6aae-4f67-945e-e837dfa62cf0.png)
![image](https://user-images.githubusercontent.com/41821549/199654637-7c767237-10d2-4d03-a1e7-f67ae3e83dc3.png)

How can I configure the proxy

**Comment by mscb402** [comment]
Please share more detail about your problem

**Comment by mscb402** [comment]
> upstream config ![image](https://user-images.githubusercontent.com/41821549/199654475-379cd005-6aae-4f67-945e-e837dfa62cf0.png) ![image](https://user-images.githubusercontent.com/41821549/199654637-7c767237-10d2-4d03-a1e7-f67ae3e83dc3.png)
> 
> How can I configure the proxy

In this case, I think ‘Host请求头’ should be config to 'geo.datav.aliyun.com'.
