### ISSUE TITLE
feat: Support adding header in proxy-rewrite plugin

### ISSUE THREAD

**Issue by AlinsRan** [apache/apisix#8239]
### Description

Currently, proxy-rewrite plugin only supports set / delete headers. The limitation makes some operations impossible. This feature is required to implement [Gateway API HTTPHeaderFilter](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.HTTPHeaderFilter).

* Similar to #7794 

## Expect
```json
{
    "proxy-rewrite": {
        "headers": {
            "add": {
                "X-Server-id": 3,
                "X-Server-status": "on",
                "X-Server-balancer_addr": "$balancer_ip:$balancer_port"
            }
        }
    }
}
```
## Actual
```json
{
    "proxy-rewrite": {
        "headers": {
            "X-Api-Version": "v1",
            "X-Api-Engine": "apisix",
            "X-Api-useless": ""
        }
    }
}
```

**Comment by mscb402** [comment]
please assign to me

**Comment by AlinsRan** [comment]
@spacewander cc

**Comment by tzssangglass** [comment]
`proxy-rewrite` plugin support to add headers, read: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-rewrite.md#attributes

**Comment by AlinsRan** [comment]
> `proxy-rewrite` plugin support to add headers, read: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/proxy-rewrite.md#attributes

If the header exists, it will be overwritten.
for example:
1. current: `Cache-Control: max-age`
2.  add plugin
```json
{
    "proxy-rewrite": {
        "headers": {
            "add": {
                "Cache-Control": "must-revalidate",
            }
        }
    }
}
```
3. result: `Cache-Control: max-age, must-revalidate`

**Comment by tokers** [comment]
I think the design of this part should be consistent with response-rewrite.

**Comment by tokers** [comment]
cc @mscb402

**Comment by GitTest16** [comment]
Does this add plugin add value multiple time ? I am experiencing that header value get added two time
