### ISSUE TITLE
help request: apisix_nginx_http_current_connections中wait的值存在疑问

### ISSUE THREAD

**Issue by c591762009** [apache/apisix#8243]
### Description

存在一个问题，在使用prometheus插件时，我会发现apisix_nginx_http_current_connections这个指标，中state为waiting和active的值有时候一样多。这是为啥？因为本身该服务未对外使用，调用量会随之上升。如果是apisix与prometheus交互我可以理解总量的上升。但是等待量与活动量几乎要持平了，这是为何
![3ba4eda094501d5aeaf2eb7941ab805](https://user-images.githubusercontent.com/32794876/199904730-4f4dd05b-935d-426e-9cae-d65ecfc5fbf6.png)
![image](https://user-images.githubusercontent.com/32794876/199904821-5407c88b-7206-4e72-a595-433b23e2f5c3.png)

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
First of all, these calues are accumulated since apisix starts. An established connection will experience these stages. So equal values are desired.

Waiting is larger than active only if your apisix cannot handle connections in time.

**Comment by c591762009** [comment]
我是否可以理解为，当我的连接与apisix产生交互时，比如有10个连接，那么active就有10个，但是我实际上6个是在wait但是只有4个是在真实的write

**Comment by tokers** [comment]
> 我是否可以理解为，当我的连接与apisix产生交互时，比如有10个连接，那么active就有10个，但是我实际上6个是在wait但是只有4个是在真实的write

No. I just said the difference.

**Comment by c591762009** [comment]
> > 我是否可以理解为，当我的连接与apisix产生交互时，比如有10个连接，那么active就有10个，但是我实际上6个是在wait但是只有4个是在真实的write
> 
> No. I just said the difference.

那我还是没太明白，这些wait，write和active的关系是什么？

**Comment by tzssangglass** [comment]
> 那我还是没太明白，这些wait，write和active的关系是什么？

This data comes from Nginx's stub_status module, read more: http://nginx.org/en/docs/http/ngx_http_stub_status_module.html

```
Active connections
The current number of active client connections including Waiting connections.
Writing
The current number of connections where nginx is writing the response back to the client.
Waiting
The current number of idle client connections waiting for a request.
```
If you enabled keep-alive, `Waiting` is equal to `Active` - (reading+writing), this value depends on keepalive-timeout. 

In APISIX, keep-alive is enable by default.
