### ISSUE TITLE
docs: https://github.com/apache/apisix/blob/master/docs/zh/latest/plugins/hmac-auth.md 签名生成公式过程详解的6. wrong

### ISSUE THREAD

**Issue by yhfgithub** [apache/apisix#8244]
### Current State

hi,guys,You wrote wrong, there should be no \n after signed_headers_string.

6. `signed_headers_string` 用来制定参与到签名的 headers，在上面示例中包括 `User-Agent: curl/7.29.0` 和 `x-custom-a: test`。

根据 HTTP Method + \n + HTTP URI + \n + canonical_query_string + \n + access_key + \n + Date + \n + signed_headers_string **+ `\n`**，得到完整的 `signing_string` 为：

### Desired State

6. `signed_headers_string` 用来制定参与到签名的 headers，在上面示例中包括 `User-Agent: curl/7.29.0` 和 `x-custom-a: test`。

根据 HTTP Method + \n + HTTP URI + \n + canonical_query_string + \n + access_key + \n + Date + \n + signed_headers_string ，得到完整的 `signing_string` 为：

**Comment by tokers** [comment]
See apisix/plugins/hmac-auth.lua#287, the linebreak do exist.
