### ISSUE TITLE
help request: {"error_msg":"unknown plugin [jwt-auth]"}

### ISSUE THREAD

**Issue by WeiXue9** [apache/apisix#8246]
### Description

I creat route with jwt-auth plugin,but I got error_msg:unknown plugin [jwt-auth].
I see closed issues,I checked my  conf.yaml  and conf_default.yaml in apisix_conf ，I enabled plugins.
And my apisix dashboard can create route with jwt-auth plugin.
I cannot do anything,So I need help.

my  plugins config  in  conf.yaml:
![image](https://user-images.githubusercontent.com/90121655/199928426-4e6268fa-fa16-4fc4-bf05-94d1e0f6d0b0.png)

### Environment

- APISIX version (run `apisix version`): 2.15.0-alpine
- Operating system (run `uname -a`): centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15
- APISIX Dashboard version, if relevant:2.13-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by oyiadin** [comment]
Are you using `jwt-auth` in a stream route? APISIX does not share the same enabled-plugin list between http routes (which lies within the `plugins` part, the part you've published) and stream routes (which lies within the `stream_plugins: # sorted by priority
` part).

If it's sure that the route is a http one, maybe you can execute `etcdctl get /apisix/plugins` to ensure that the configs are correctly synchronized.

**Comment by shreemaan-abhishek** [comment]
@WeiXue9, do you have any further questions/updates? If not, please close the issue. Thanks.
