### ISSUE TITLE
help request: Does apisix support openshift?

### ISSUE THREAD

**Issue by hyang523Goa** [apache/apisix#8248]
### Description

We tried to install apisix to openshift using docker compose. We first use Kompose to convert docker-compse.yml to openshift yaml files and use oc to apply those yaml files to oepnshift. But we have some iusses with config files and permsision issues. We wonder if you have any doucmentation, guide or help to install it on oopeshift? We only found the docker Installation guide and it was ok to install on local docker but we don't know how to address openshift issues. We used newest verison from https://github.com/apache/apisix-docker.git and https://github.com/apache/apisix

Haoran Yang
Governament of Alberta
haoran.yang@gov.ab.ca

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
![oepsnift](https://user-images.githubusercontent.com/100244428/200071939-53a6c1c0-da1b-446f-bc5c-7fc9c16bb15f.png)

**Comment by tokers** [comment]
It's important to see how you mount the/use/local/apisix/conf/. Files and directories kept same permissions, owner and group with the original file.

Then, check which user you used to start apisix, and see if this user has sufficient permissions to open the files and directories.

**Comment by tao12345666333** [comment]
you can try to use Helm to deploy APISIX  https://github.com/apache/apisix-helm-chart

**Comment by hyang523Goa** [comment]
We did try helm installation and it didn't work either. The pod complains that the StatefulSet apisix-etcd is not up and the some end point cannot be resolved like $(MY_POD_NAME).apisix-etcd-headless.sa-si-snc-dev.svc.cluster.local:2379, apisix-etcd.sa-si-snc-dev.svc.cluster.local:2379, $(MY_POD_NAME).apisix-etcd-headless.sa-si-snc-dev.svc.cluster.local:2380, pisix-etcd-0.apisix-etcd-headless.sa-si-snc-dev.svc.cluster.local:2380, apisix-etcd-1.apisix-etcd-headless.sa-si-snc-dev.svc.cluster.local:2380 etc

We tried to create several routes to for those end points but they do not work.

**Comment by tao12345666333** [comment]
APISIX Helm chart uses `bitnami/etcd` chart https://github.com/bitnami/charts/tree/main/bitnami/etcd

maybe you can refer to https://github.com/bitnami/charts/issues/12215


Or you can deploy your own etcd cluster for APISIX use.

https://github.com/apache/apisix-helm-chart/blob/def952bfbd57b5895b8571e4bd10b220e5e9fe95/charts/apisix/values.yaml#L427-L456
