### ISSUE TITLE
feat: Can serverless plugin stops the request and make an immediate response?

### ISSUE THREAD

**Issue by oyiadin** [apache/apisix#8249]
### Description

Here is what I want to achieve: 

If something very simple, but needs some extra calculation (e.g. imagine some simple mathematics with cookies), fulfilled, stops the request (don't send to upstream) and response with a message immediately.

The `serverless` plugin would be the very suitable one for me to handle the condition that I need, but I need a way to intercept the request and make response. For example, we can utilize the return value of serverless's passed-in `functions`, if any one of the functions do return something not nil, then pass it up util here https://github.com/apache/apisix/blob/48b84311067ae1b863cfcda23d079a262ff4a8ee/apisix/plugin.lua#L957-L971

**Comment by tokers** [comment]
@oyiadin Yes, you can, I write the way here directly because I found it's not recorded. cc @tzssangglass 

You can just return two values in your codes.

```lua
return {code}, {body}
```

**Comment by oyiadin** [comment]
oops, sorry, I've forgot that my local branch is still at release/2.11.
I've seen that it's already supported in the latest branch, so no more question for me, thx for your comments!

**Comment by oyiadin** [comment]
maybe we can update the docs of serverless for this feature
