### ISSUE TITLE
send request to another upstram 

### ISSUE THREAD

**Issue by azizkhani** [apache/apisix#8250]
### Current Behavior

I have two upstream and two route  like this 
some of API in upstream like another for example both of then have /api/otp

I have two route like this 

route 1 =   /app1/api/otp ---> route to  ---> /api/otp  in upstream 1
route 2=   /app2/api/otp ---> route to ----> /api/otp in upstream 2

```
{
  "uri": "/app/api/otp",
  "name": "app-otp",
  "methods": [
    "POST"
  ],
  "plugins": {
    "proxy-rewrite": {
      "uri": "/api/otp"
    }
  },
  "upstream_id": "422891900672934422",
  "status": 1
}

```

```
{
  "uri": "/app2/api/otp",
  "name": "app2-otp",
  "methods": [
    "POST"
  ],
  "plugins": {
    "proxy-rewrite": {
      "uri": "/api/otp"
    }
  },
  "upstream_id": "422891900672934433",
  "status": 1
}

```

but when client app call route 1 request send to upstream 2  

### Steps to Reproduce

1.Run apisix with docker
2.define two up stream with different ip 
3. define two route and then call api 
4. request to route 1 send to upstream 2 some times

### Environment

- APISIX version 2.14.1
- Operating system ubuntu , docker
- etcd version, 3.4.0
- APISIX Dashboard version, 2.13.0

**Comment by hf400159** [comment]
Hi, I didn't reproduce your problem in 2.14.1. Can you provide more information?

**Comment by tokers** [comment]
@azizkhani Could you also provide the APISIX config.yaml?

**Comment by azizkhani** [comment]
![image](https://user-images.githubusercontent.com/35541507/200178885-d1118550-5dca-482c-b724-a0837994dea6.png)

**Comment by tangkaijun** [comment]
我也遇到同样的问题，

**Comment by tangkaijun** [comment]
我也遇到同样的问题：
实际的结果是
route 1(/app1/api/test) ---> service1(使用了插件proxy-rewrite) ---> upstream 1
route 2(/app2/api/test) ---> service2(使用了插件proxy-rewrite) ---> upstream 1
期望结果是：
route 1(/app1/api/test) ---> service1(使用了插件proxy-rewrite) ---> upstream1
route 2(/app2/api/test) ---> service2(使用了插件proxy-rewrite) ---> upstream2

**Comment by tangkaijun** [comment]
我使用的版本是apisix 3.0.0

**Comment by tzssangglass** [comment]
> but when client app call route 1 request send to upstream 2

How did you verify this? I noticed that the configuration of the "proxy-rewrite" plugin is the same.

**Comment by azizkhani** [comment]
> Hi, I didn't reproduce your problem in 2.14.1. You may need to check the upstream's IP. Can you provide more information?

did you know how solve this problem ? 
My app lunched in production and i got this bug and i can not rollback using apisix

**Comment by tokers** [comment]
> > Hi, I didn't reproduce your problem in 2.14.1. You may need to check the upstream's IP. Can you provide more information?
> 
> 
> 
> did you know how solve this problem ? 
> 
> My app lunched in production and i got this bug and i can not rollback using apisix

Are you using both the http and https protocols as the scheme to communicate with upstreams?

If so, try the 2.15.0 version.

**Comment by azizkhani** [comment]
> > > Hi, I didn't reproduce your problem in 2.14.1. You may need to check the upstream's IP. Can you provide more information?
> > 
> > 
> > did you know how solve this problem ?
> > My app lunched in production and i got this bug and i can not rollback using apisix
> 
> Are you using both the http and https protocols as the scheme to communicate with upstreams?
> 
> If so, try the 2.15.0 version.

I am suing just http protocol

**Comment by tzssangglass** [comment]
> 路由信息：
> route1: /*
> route2: /*

@tangkaijun for your case, two routes with the same uri will result in unresolved behavior.

**Comment by tzssangglass** [comment]
> > but when client app call route 1 request send to upstream 2
> 
> How did you verify this? I noticed that the configuration of the "proxy-rewrite" plugin is the same.

I'm still concerned about how you verified it, because your configuration confuses me.
