### ISSUE TITLE
feat: I hope the unix domain socket could be as the upstream node.

### ISSUE THREAD

**Issue by zhangw** [apache/apisix#8258]
### Description

Why does apisix not support unix domain socket be as the upstream that be already supported in native nginx?
In k8s architecture, a dedicated upstream server would running in the sider car container and it is useful if apisix could connect with the upstream server via unix domain socket.

**Comment by zhangw** [comment]
now I find a workaround like this: 
        
        location @grpc_error_pass {
            grpc_set_header   Content-Type application/grpc;
            grpc_socket_keepalive on;
            grpc_pass  unix:/tmp/foo.sock;
        }

        location @grpc_pass {

            access_by_lua_block {
                -- in some conditional
                ngx.exec("@grpc_error_pass")
            }
        }

**Comment by tokers** [comment]
> In k8s architecture, a dedicated upstream server would running in the sider car container and it is useful if apisix could connect with the upstream server via unix domain socket.

Are you using APISIX to handle east-west traffic?

**Comment by zhangw** [comment]
> > In k8s architecture, a dedicated upstream server would running in the sider car container and it is useful if apisix could connect with the upstream server via unix domain socket.
> 
> Are you using APISIX to handle east-west traffic?

Due to the apisix 2.x not support the fully grpc protocol, in some cases, we trying to let apisix directly return the grpc error code and abort the current stream processing, this behavior cause the downstream (aws nlb) not make sense what happend on http2 connection. We introduced a real grpc server which listening on the unix domain socket that help apisix to implement the correct grpc error handler. This grpc server running on a sidecar container which using the shared  volume as unix domain fd that connected by apisix worker process running on another container.

**Comment by tokers** [comment]
> > > In k8s architecture, a dedicated upstream server would running in the sider car container and it is useful if apisix could connect with the upstream server via unix domain socket.
> > 
> > 
> > Are you using APISIX to handle east-west traffic?
> 
> Due to the apisix 2.x not support the fully grpc protocol, in some cases, we trying to let apisix directly return the grpc error code and abort the current stream processing, this behavior cause the downstream (aws nlb) not make sense what happend on http2 connection. We introduced a real grpc server which listening on the unix domain socket that help apisix to implement the correct grpc error handler. This grpc server running on a sidecar container which using the shared volume as unix domain fd that connected by apisix worker process running on another container.

OK, could you also try the `127.0.0.1`? As these containers in the same pod are share the network namespace.

I think this may help you to solve the problem of lack UNIX domain socket.

**Comment by zhangw** [comment]
Thanks for your suggestion, considering the unix domain socket which can achieve more throughput than linux loopback, so we finally use the workaround mentioned above to solve this.

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this if you needed.
