### ISSUE TITLE
help request: dubbo direct forwarding

### ISSUE THREAD

**Issue by wxbty** [apache/apisix#8264]
### Description

Whether apisix supports direct forwarding of dubbo traffic, the existing dubbo-proxy implements http traffic to dubbo service. The scenario is to get through different network dubbo cluster access

**Comment by tokers** [comment]
Try the stream route? See https://apisix.apache.org/docs/apisix/admin-api/#stream-route.

If you need some fine-grained traffic control for Dubbo, you may have to do some development with the help of xRPC: https://apisix.apache.org/docs/apisix/xrpc/

**Comment by wxbty** [comment]
looks great， thx  @tokers
