### ISSUE TITLE
/usr/local/luawork/apisix/bin/apisix start /usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua start /usr/local/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/usr/local/luawork/apisix/deps/lib/lua/5.1/ssl.so':         /usr/local/luawork/apisix/deps/lib/lua/5.1/ssl.so: undefined symbol: EVP_PKEY_get_bits

### ISSUE THREAD

**Issue by hadoop835** [apache/apisix#8266]
### Description

![1667820329137](https://user-images.githubusercontent.com/8055054/200297980-342f434e-3308-4b1c-bd33-96646c7ebde1.png)

**Comment by tokers** [comment]
Please provide more details and do not just paste screenshot.

1. How did you install apisix?
2. What's the apisix version?

**Comment by hadoop835** [comment]
How did you install apisix?
Local installation, 
1、install lua & luarocks
2、install openresty
3、execute make deps & make run
What's the apisix version?
1、git clone  master

**Comment by monkeyDluffy6017** [comment]
Maybe you could try to run apisix follow this file: https://github.com/apache/apisix/blob/master/ci/centos7-ci.sh
