### ISSUE TITLE
help request: kafka-logger 3.0 Validation issues.

### ISSUE THREAD

**Issue by rampagecong** [apache/apisix#8267]
### Description

Plugin kafka-logger config:
{
    "brokers": [
        {
            "host": "dev-log-kafka.nhdc.cn",
            "port": 7101,
            "sasl_config": {
                "user": "qa-safety",
                "password": "GJWjjOqL1ef1LL3XdrK2"
            }
        },
        {
            "host": "dev-log-kafka.nhdc.cn",
            "port": 7102,
            "sasl_config": {
                "user": "qa-safety",
                "password": "GJWjjOqL1ef1LL3XdrK2"
            }
        },
        {
            "host": "dev-log-kafka.nhdc.cn",
            "port": 7103,
            "sasl_config": {
                "user": "qa-safety",
                "password": "GJWjjOqL1ef1LL3XdrK2"
            }
        }
    ],
    "disable": false,
    "kafka_topic": "apisixlog",
	"broker_list":{
		"test":7101
	}
}

Kafka access is "SASL_PLAINTEXT".
"mechanism":"PLAIN" = "mechanism":"SASL_PLAINTEXT" ????

2022/11/07 18:44:01 [error] 52#52: *277247 [lua] init.lua:533: http_access_phase(): failed to fetch service configuration by id: 432886819009332162, client: 172.32.218.128, server: _, request: "GET /safety-admin-api/risk/access/list?ID=&op_user=&op_start_time=&op_end_time=&page=1&page_size=10 HTTP/1.1", host: "10.159.5.70", referrer: "http://10.159.5.70/safety-admin-view/?org_code=12320000E80232435Q"

What is the reason for the error message above?

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`):linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:2.13
- Plugin runner version, for issues related to plugin runners: kafka-logger
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
I think this is due to the imcompatibility between dashboard 2.13 and apisix 3.0

**Comment by rampagecong** [comment]
> I think this is due to the imcompatibility between dashboard 2.13 and apisix 3.0

There are compatibility issues, but I think they are caused by kafka validation issues.

**Comment by rampagecong** [comment]
@shuaijinchao Hello, please help me to look at this problem.

**Comment by rampagecong** [comment]
The problem has been solved.
Need:
curl 127.0.0.1:9090/v1/schema > schema.json
Dashboard fold `dashboard/conf/schema.json` is replaced by schema.json then refer to the  kafka-logger documentation.

Thinks.
