### ISSUE TITLE
how to set route for nginx  return directive

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8269]
### Description

in my nginx.conf,i want to put this config to apisix config,
nginx.conf:
`location /test {
         add_header 'Access-Control-Allow-Origin' "*";
         add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
         add_header 'Access-Control-Allow-Headers' '*';
         if ($request_method = 'OPTIONS') {
             return 208;
         }`

in apisix,how to set this for one route.tks.

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Try the cors plugin and fault-injection plugin ( it allows you to return custom message when some rules matched).

**Comment by kellyseeme** [comment]
tks for reply .
