### ISSUE TITLE
help request: pb.decode()发生“runtime error table overflow”异常

### ISSUE THREAD

**Issue by doudouliyougangbeng** [apache/apisix#8273]
### Description

<img width="588" alt="image" src="https://user-images.githubusercontent.com/25500491/200473608-6738e3a5-be56-4ace-96b2-c58073dd1378.png">

### Environment

- APISIX version (run `apisix version`):2.10.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@doudouliyougangbeng Hi, what did you do, can you give me more information?

**Comment by monkeyDluffy6017** [comment]
Does your  pb file contain a recursive definition?

**Comment by shreemaan-abhishek** [comment]
@doudouliyougangbeng, do you have any further questions/updates? If not, please close the issue. Thanks.
