### ISSUE TITLE
help request:  The route occasionally returns a 404 page not found

### ISSUE THREAD

**Issue by wangfeng22** [apache/apisix#8280]
### Description

I have configured several routes, and everything going well. But when I added a new route, sometimes this route returned 404 page not found. That's really abnormal.In fact, the  back-end  didn't handle the 404 requests. 
I have restarted apisix, but this problem still exists. Only the domain name added later has this problem.

ps: The Route support http and https. The Upstream is configured like http://`domain`

### Environment

- APISIX version (run `apisix version`): 2.13.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Could you provide a minimal reproduction use case with detailed steps？

**Comment by tzssangglass** [comment]
maybe fix by: #7466 and release in v2.15.0

**Comment by wangfeng22** [comment]
> maybe fix by: #7466 and release in v2.15.0

I have studied this issue for many days, and I find it difficult to understand the explanation of this problem. Why can't I restart Apisix to solve this problem.

**Comment by wangfeng22** [comment]
> Could you provide a minimal reproduction use case with detailed steps？

1. add several routes like routerA, routerB, routerC, and so on. The router support HTTP and HTTPS. The upstream is configured like http://`domain`.
2. add routerD. Then a strange thing happened, routerD occasionally returns `404 page not found`. In fact, the upstream of routerD don't handle the 404 requests.

I don't know what returns `404 page not found`. routerA, routerB and routerC are working well.  I have restarted apisix, but this problem still exists.

**Comment by wangfeng22** [comment]
> maybe fix by: #7466 and release in v2.15.0

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/42538040/200737195-0e8c486a-2aaa-46cb-be51-00e96444eff0.png">
 
The 404 response is returned right now, and it doesn't get a response from upstream. You can see it from No number.

**Comment by wangfeng22** [comment]
@tokers Could you help me see?  Looking forward to your reply.

**Comment by tzssangglass** [comment]
> The 404 response is returned right now, and it doesn't get a response from upstream. You can see it from No number.

Are you saying that this problem still exists in 2.15.0? Or are you insisting on reproducing and working on this issue on 2.13.2?

**Comment by wangfeng22** [comment]
> 

I insist on reproducing and working on this issue on 2.13.2. I really want to know why this happened. This problem can be reproduced in the case of pressure measurement. It is difficult to understand the explanation of this problem in this issue #7466
