### ISSUE TITLE
bug: hold_body_chunk() chinese garbled

### ISSUE THREAD

**Issue by JerryZhangGD** [apache/apisix#8284]
### Current Behavior

 i called the method: hold_body_chunk()   (response.lua)  for a response body string  then lead to a Chinese garbled situation

### Steps to Reproduce

1. turn on the clickhouse-logger plugin
2. try to get the response body

### Environment

- APISIX version (run `apisix version`):2.15

**Comment by Hazel6869** [comment]
@JerryZhangGD Hi can you give me more plugin configuration information?
