### ISSUE TITLE
help request: how to rewrite upstream response 

### ISSUE THREAD

**Issue by yunduansing** [apache/apisix#8285]
### Description

1.upstream body may response:
`{
   "data": [],
  "total": 100
}
`
http status code: 200

**then I want to rewrite it like :** 
`{
   "data":{ "data": [],"total": 100} ,
   "errcode": 0
}
`
http status code: 200

2.upstream body may response:
`
"Internal error."
`
http status code: 500

**then I want to rewrite it like :** 
`{
   "msg": "Internal error.",
   "errcode": 500,
   "data": null
}
`
http status code: 200

I want to know how to do it when I use the default response-rewrite plugin

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@yunduansing Hi，you can use responese-rewrite plugin, refer to https://apisix.apache.org/zh/docs/apisix/plugins/response-rewrite/

**Comment by yunduansing** [comment]
> @yunduansing Hi，you can use responese-rewrite plugin, refer to https://apisix.apache.org/zh/docs/apisix/plugins/response-rewrite/ I can give you an example.

nice! please give me ur example ths.

**Comment by Hazel6869** [comment]
@yunduansing you can use this function 
![image](https://user-images.githubusercontent.com/30279880/200774203-ef69d13f-c749-4c5f-b82c-0afe62d72c96.png)
