### ISSUE TITLE
docs: mention the default log format for each logger plugin

### ISSUE THREAD

**Issue by tokers** [apache/apisix#8297]
### Current State

**Description of the current state/issue**:

Currently, only the Kafka Logger doc has the description for the default log format. But others don't have the section. This is not a good experience for our users.

**Link to the page**:

https://apisix.apache.org/docs/apisix/plugins/kafka-logger/

**Screenshots (if relevant)**:

-

### Desired State

**Description of the change you are proposing**:

For each logger plugin, people can know the default log format.

### Would you like to fix this issue?

No. Please assign another contributor

**Comment by bzp2010** [comment]
Hi, @tokers @navendu-pottekkat 

Since the APISIX documentation is managed by the APISIX project repository itself, I moved this issue to the APISIX repository.

**Comment by yujinchoi-94** [comment]
I'm trying to use `http-logger` plugin and I had to find [this](https://github.com/apache/apisix/blob/e021266129eff537ea6b59cca0061385663d3a69/apisix/utils/log-util.lua#L133-L159) to see which values are included in the log  by default and which fields are available for `log_format` field.
If there are related documents, it would be helpful. 😀

**Comment by kayx23** [comment]
Just stumbled upon this issue. I raised a similar one which was fixed in https://github.com/apache/apisix/pull/9516

That said, it seems the "default log format" in this issue is talking about [this](https://apisix.apache.org/docs/apisix/plugins/kafka-logger/#meta_format-example) instead? Can someone help confirm

cc: @pottekkat @monkeyDluffy6017 @bzp2010

**Comment by kayx23** [comment]
Alternatively, the default log format could be introduced with examples, e.g.:

* https://docs.api7.ai/hub/kafka-logger#log-in-different-meta-log-formats
* https://docs.api7.ai/hub/rocketmq-logger#log-in-different-meta-log-formats

**Comment by smileby** [comment]
I can try it @kayx23
