### ISSUE TITLE
help request: Request method 'GET' not supported

### ISSUE THREAD

**Issue by yanziyu0721730** [apache/apisix#8299]
### Description

当我使用post请求的时候 Request method 'GET' not supported  报这个错，我应该怎么定位问题？

### Environment

- APISIX version (run `apisix version`):3.0

**Comment by Hazel6869** [comment]
@yanziyu0721730 Hi can you give me more information,  such as your curl. 🤔

**Comment by tzssangglass** [comment]
> 当我使用post请求的时候 Request method 'GET' not supported 报这个错，我应该怎么定位问题？

Are you sure this is not an error returned upstream?

**Comment by shreemaan-abhishek** [comment]
@yanziyu0721730, do you have any further questions/updates? If not, please close the issue. Thanks.
