### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by fzp11** [apache/apisix#8308]
### Current Behavior

https http1.1 环境下，Content-Type: text/event-stream，即 sse的时候，直接pending直接超时
![image](https://user-images.githubusercontent.com/45675963/201099785-e7594e1d-4f82-41df-8bf6-e21bd84163f5.png)
http2.0 的时候可以

### Steps to Reproduce

chrom 浏览器后面禁用 --disable-http2
![image](https://user-images.githubusercontent.com/45675963/201100006-14bffa6d-c4e9-4840-8a40-62532c279adb.png)
然后需要用 EventSourcePolyfill.prototype = Object.create(EventTarget.prototype); 等 去调用

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kingluo** [comment]
Maybe these links are helpful:
https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx
https://apisix.apache.org/zh/docs/apisix/customize-nginx-configuration/

**Comment by fzp11** [comment]
感谢 已解决

**Comment by randsoy** [comment]
怎么解决的呢？

**Comment by kingluo** [comment]
> 怎么解决的呢？

Please refer to this link:
https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx

Configuring nginx could solve this issue.
