### ISSUE TITLE
help request: Why `ctx.var.host` is different from `ctx.var.http_host`?

### ISSUE THREAD

**Issue by diaosj** [apache/apisix#8310]
### Description

I use `Host` header in the coming request to generate API signature (something like `Authorization: xxx`).
I find that the `ctx.var.host` doesn't contain `port`.
Take `Host: 127.0.0.1:80` as an example.
`ctx.var.host` is `127.0.0.1`, while `ctx.var.http_host` is `127.0.0.1:80`.

It seems that `ctx.var.host` is used in `route.lua`, `radixtree_host_uri.lua`. I wonder whether `port` should be in host or not.

### Environment

- APISIX version (run `apisix version`): 2.7
- Operating system (run `uname -a`): Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.3.2

**Comment by spacewander** [comment]
The `ctx.var.host` will access the $host variable.

> $host
    in this order of precedence: host name from the request line, or host name from the “Host” request header field, or the server name matching a request

http://nginx.org/en/docs/http/ngx_http_core_module.html#var_host

It is documented that $host only contains the "host name" from the “Host” request header field.

While `ctx.var.http_host` is equal to the “Host” request header.

**Comment by diaosj** [comment]
Ah, the name doesn't contain port. Thanks!
