### ISSUE TITLE
help request: As a user, I use kubernetes service discovery ,same apisix instance ，It took a long time to get the changed ip

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#8313]
### Description

As a user, I use kubernetes service discovery ,same apisix instance It took a long time to get the changed ip，5 nodes of apisix, two of them get the correct ip after 10 minutes, how should I troubleshoot where this problem is

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Could you share the configurations of the Kubernetes service discovery module and, any error logs?

**Comment by zhixiongdu027** [comment]
In order to confirm whether it is the failure of the kubernetes cluster or the failure of discovery.
We set the log level to debug and we can see a lot of "on_events_modified" logs.
Also execute "kubect get endpoints -o yaml --watch" in the terminal
 
After getting some output, you can know whether the fault belongs to the cluster or discovery by comparing the time when the same event appears in the log and the time in the terminal.

**Comment by wolgod** [comment]
> Could you share the configurations of the Kubernetes service discovery module and, any error logs?
this not error log, The current phenomenon can be viewed through ss  -antp. Only when the connection is reconnected can the latest endpoints be obtained

```
kubernetes:
    service:
      # apiserver schema, options [http, https]
      schema: https
      # apiserver host, options [ipv4, ipv6, domain, environment variable]
      host: xxx.com
      # apiserver port, options [port number, environment variable]
      port: "6443"  #default ${KUBERNETES_SERVICE_PORT}
    client:
      token: |-
        Xxxx
    namespace_selector:
      match:
        - default
        - ^ns-[a-z0-9]+$

**Comment by zhixiongdu027** [comment]
sorry i didn't get your point

> > Could you share the configurations of the Kubernetes service discovery module and, any error logs?
> 
> this not error log, The current phenomenon can be viewed through ss -antp. Only when the connection is reconnected can the latest endpoints be obtained
> 
> ```
> kubernetes:
>     service:
>       # apiserver schema, options [http, https]
>       schema: https
>       # apiserver host, options [ipv4, ipv6, domain, environment variable]
>       host: xxx.com
>       # apiserver port, options [port number, environment variable]
>       port: "6443"  #default ${KUBERNETES_SERVICE_PORT}
>     client:
>       token: |-
>         Xxxx
>     namespace_selector:
>       match:
>         - default
>         - ^ns-[a-z0-9]+$
> ```

Sorry,  I didn't get your point

**Comment by wolgod** [comment]
> > this not error log, The current phenomenon can be viewed through ss -antp. Only when the connection is reconnected can the latest endpoints be obtained
> > ```
> > kubernetes:
> >     service:
> >       # apiserver schema, options [http, https]
> >       schema: https
> >       # apiserver host, options [ipv4, ipv6, domain, environment variable]
> >       host: xxx.com
> >       # apiserver port, options [port number, environment variable]
> >       port: "6443"  #default ${KUBERNETES_SERVICE_PORT}
> >     client:
> >       token: |-
> >         Xxxx
> >     namespace_selector:
> >       match:
> >         - default
> >         - ^ns-[a-z0-9]+$
> > ```
> 
> Sorry, I didn't get your point

I mean, the current connection to Apiserver does not receive any watch events. It can only be restored after a new connection to Apiserver is established. The front of Apiserver is lvs

**Comment by zhixiongdu027** [comment]
Can you try the if command and see if you can observe events?

```shell
kubectl get  --raw="https://{lvs}/api/v1/endpoints?limit=500&watch=true"
```

**Comment by wolgod** [comment]
我在debug日志里进行查询

在报502的节点看到 监听到事件的节点上 日志如下：

<img width="957" alt="image" src="https://user-images.githubusercontent.com/4132442/201587933-7e9661c9-8b38-4fd8-a386-226f46b5ebc8.png">


在正常的节点上可以看到日志 events事件的获取

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/4132442/201587867-200dd230-f38f-451c-8974-0a5fd5918d82.png">

**Comment by zhixiongdu027** [comment]
Based on the available information, 
I guess the problem may be related to the lvs timeout configuration

Maybe you can read this [document](https://ieevee.com/tech/2017/08/15/lvs-persistence.html)

**Comment by wolgod** [comment]
> document
14:08 502的节点重新发生了relist，如果lvs 超时了 客户端的连接是不是应该断掉，为啥还是一直保持呢？过了很久才relist？

2022/11/14 14:08:27 [info] 485#485: *2088226552 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?limit=120, context:

**Comment by zhixiongdu027** [comment]
> 如果lvs 超时了 客户端的连接是不是应该断掉，

I'm not sure how lvs handles timeouts,
According to general logic, maybe the client will not know that the link is disconnected until the client sends the data again.

**Comment by wolgod** [comment]
> > 如果lvs 超时了 客户端的连接是不是应该断掉，
> 
> I'm not sure how lvs handles timeouts, According to general logic, maybe the client will not know that the link is disconnected until the client sends the data again.



2022/11/14 14:52:30 [debug] 485#485: *2089958734 [lua] init.lua:59: on_added(): {"subsets":[{"addresses”:…….}
2022/11/14 14:52:30 [info] 485#485: *2089958734 [lua] informer_factory.lua:218: watch(): --raw=/api/v1/endpoints?resourceVersion=474194133&watch=true&allowWatchBookmarks=true&timeoutSeconds=2226, context: ngx.timer

自从14:52:30 进行watch 之后,直到15:32 重新list才能获取到最新数据，为什么会重新watch，我没找到相关的日志打印，
timeoutSeconds=2226 这个是apiserver的超时时间吧，大约37分钟，因为apiserver超时了，所以apisix 重新relist了?

2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?limit=120, context: ngx.timer
2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NDc0MjYxMzA1LCJzdGFydCI6Im5zLTIyNTYvZGF0YS10cmFuc2Zlci1wcm9kLWRhdGEtdHJhbnNmZXJcdTAwMDAifQ&limit=120, context: ngx.timer
2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NDc0MjYxMzA1LCJzdGFydCI6Im5zLTIyNzcveWNoYi1ndy1wYnMtYWlcdTAwMDAifQ&limit=120, context: ngx.timer
2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NDc0MjYxMzA1LCJzdGFydCI6Im5zLTIzMTIvZ3dzcy1tcS1jb25zdW1lci1hcHAtb25saW5lXHUwMDAwIn0&limit=120, context: ngx.timer
2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:59: list(): --raw=/api/v1/endpoints?continue=eyJ2IjoibWV0YS5rOHMuaW8vdjEiLCJydiI6NDc0MjYxMzA1LCJzdGFydCI6Im5zLTI0MjQvYXJrLXJlZ2lzdHJ5LXByb2RcdTAwMDAifQ&limit=120, context: ngx.timer
2022/11/14 15:32:16 [info] 485#485: *2091522897 [lua] informer_factory.lua:218: watch(): --raw=/api/v1/endpoints?resourceVersion=474261305&watch=true&allowWatchBookmarks=true&timeoutSeconds=1908, context: ngx.timer

**Comment by zhixiongdu027** [comment]
> Can you try the following command and see if you can observe events?
> 
> ```shell
> kubectl get  --raw="https://{lvs}/api/v1/endpoints?limit=500&watch=true"
> ```
> 

@wolgod 
Have you tried this command on the faulty node, can you observe the events ?

**Comment by wolgod** [comment]
> > Can you try the following command and see if you can observe events?
> > ```shell
> > kubectl get  --raw="https://{lvs}/api/v1/endpoints?limit=500&watch=true"
> > ```
> 
> @wolgod Have you tried this command on the faulty node, can you observe the events ?

i deploy the apisix in k8s pod ,when after i execute  apisix reload,now the 502 disappear

**Comment by zhixiongdu027** [comment]
> 自从14:52:30 进行watch 之后,直到15:32 重新list才能获取到最新数据，然后重新watch，中间没有收到events，
> timeoutSeconds=2226 这个是apiserver的超时时间吧，大约37分钟，因为apiserver超时了，所以15:32 apisix 重新relist了,
> 然后relist之后，重新watch，从日志上看 watch 没有成功，因为新的变更没有监听到

15:32:16 - 14:52:30 = 39m+14s  =  2346s = 2226s+120s

The timeout of discover relist is brought by httpc:set_timeouts(watch_seconds+120), 
not the normal apiserver disconnection.


https://github.com/apache/apisix/blob/288708cbe0098fd3f62fadd725490804d5d0a3db/apisix/discovery/kubernetes/informer_factory.lua#L198-L206

This information also confirms that it is indeed the failure caused by the lvs timeout configuration

**Comment by zhixiongdu027** [comment]
15:32:16 - 14:52:30 = 39m+46s = 2386s = 2226s+120s +40s

https://github.com/apache/apisix/blob/288708cbe0098fd3f62fadd725490804d5d0a3db/apisix/discovery/kubernetes/informer_factory.lua#L199-L206

https://github.com/apache/apisix/blob/288708cbe0098fd3f62fadd725490804d5d0a3db/apisix/discovery/kubernetes/init.lua#L320-L332

Combined with code analysis, 
We should be able to conclude that the one that terminates watch is
httpc.settimeouts , not apiserver chunked end

This information indicates that discovery cannot receive the data responded by apiserver, and also confirms that the cause of the problem is the lvs timeout configuration


perhaps you can find printed log by 
https://github.com/apache/apisix/blob/288708cbe0098fd3f62fadd725490804d5d0a3db/apisix/discovery/kubernetes/init.lua#L322-L323

**Comment by wolgod** [comment]
thanks ,but when relist happen,i don’t find log like this， i think it didn't take this branch

```core.log.error("list_watch failed, kind: ", handle.kind, 
         ", reason: ", "RuntimeException", ", message : ", status)
```

**Comment by zhixiongdu027** [comment]
> thanks ,but when relist happen,i don’t find log like this， i think it didn't take this branch
> 
> ```
>          ", reason: ", "RuntimeException", ", message : ", status)
> ```

It doesn't matter much, you should check the lvs config first

**Comment by wolgod** [comment]
thanks , now i try directly connect apiserver ，

**Comment by tokers** [comment]
> thanks , now i try directly connect apiserver ，

What's the result :)?

**Comment by crazyMonkey1995** [comment]
Same problem as I encountered. At that time, I finally checked because the proxy before the apiserver(4 layer LB) timed out, but it did not send a reset packet back. At this time, apisix (as the client) did not know that the connection had been disconnected. Should be the same problem
https://github.com/apache/apisix/issues/8311#issuecomment-1313222553

**Comment by wolgod** [comment]
> > thanks , now i try directly connect apiserver ，
> 
> What's the result :)?
 i  directly connect apiserver ，the problem disappeared ,now i try set lvs  timeout configuration greater than 1800+999+120, now The problem has not occurred yet,I don't know whether the problem has been solved or whether the probability of occurrence is very low. It is difficult to reproduce
