### ISSUE TITLE
help request: SSL not work: failed to parse key: PEM_read_bio_PrivateKey() failed

### ISSUE THREAD

**Issue by StormYudi** [apache/apisix#8316]
### Description

One of my SSL certificates can't be uploaded through APISIX API, but it works if I upload the certificate from APISIX-Dashboard, which is weird.

APISIX API: 
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/19419186/201533384-541a404e-86ea-4700-a265-5a3bf8757c04.png">

APISIX-Dashboard: 
<img width="1830" alt="image" src="https://user-images.githubusercontent.com/19419186/201533418-536aa574-2a89-45fc-afc8-cc604b84150c.png">

I've checked the content of the fields `cert` and `key`, the one in APISIX-API is as same as the one in APISIX-Dashboard.
Any reason for that situation? Please help, thanks!

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): `Linux [HIDE] 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: 2.13
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Information is not enough to track this issue. Could you make sure that the format of the private key you use in APISIX Admin API is right?

**Comment by StormYudi** [comment]
It seems that is not an APISIX-specific problem, it looks like the key has some problem, but I and not sure what the problem is.

I load the key into OpenResty, and it shows me:

`PEM_read_bio_PrivateKey() failed (SSL: error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag error:0D07803A:asn1 encoding routines:ASN1_ITEM_EX_D2I:nested asn1 error:Type=X509_ALGOR error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:Field=pkeyalg, Type=PKCS8_PRIV_KEY_INFO error:0907B00D:PEM routines:PEM_READ_BIO_PRIVATEKEY:ASN1 lib)`

**Comment by tzssangglass** [comment]
Carefully ensure there are no spaces or blanks within your certificate file, by selecting the entire text and looking for blank spaces on a text only editor.

**Comment by StormYudi** [comment]
> Carefully ensure there are no spaces or blanks within your certificate file, by selecting the entire text and looking for blank spaces on a text only editor.

Thanks for the help, he modified the SSL key... so the problem was resolved.
