### ISSUE TITLE
help request: http://etcd:2379: failed to parse domain

### ISSUE THREAD

**Issue by ZChengjin** [apache/apisix#8318]
### I installed apisix using the following steps：
1. git clone https://github.com/apache/apisix-docker.git
2. cd apisix-docker/example
3. docker-compose -p docker-apisix up -d
### I used the dashboard to create upstream, service, route, everything works fine. But the errlog of apisix will report the following error, although it does not affect my use at present, but I want to know why this is
_2022/11/14 02:29:15 [error] 50#50: *5772262 [lua] config_etcd.lua:570: failed to fetch data from etcd: http://etcd:2379: Service Unavailable,  etcd key: /apisix/consumers, context: ngx.timer
2022/11/14 02:29:15 [error] 47#47: *5768570 [lua] config_etcd.lua:570: failed to fetch data from etcd: http://etcd:2379: Service Unavailable,  etcd key: /apisix/global_rules, context: ngx.timer
2022/11/14 02:29:15 [error] 47#47: *5771065 [lua] config_etcd.lua:570: failed to fetch data from etcd: http://etcd:2379: Service Unavailable,  etcd key: /apisix/plugin_metadata, context: 
2022/11/14 02:59:45 [warn] 47#47: *38913 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2022/11/14 02:59:50 [warn] 47#47: *38905 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer_

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):Linux eee3e01b5631 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1;built by gcc 10.2.1 20210110 (Debian 10.2.1-6);built with OpenSSL 1.1.1n  15 Mar 2022
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:apache/apisix-dashboard:2.13-alpine
- Plugin runner version, for issues related to plugin runners:apisix-go-plugin-runner(master)
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
here `etcd` in `http://etcd:2379/` is the service name in docker-compose.yaml, ref: https://github.com/apache/apisix-docker/blob/master/example/docker-compose.yml#L49

Usually this should be resolvable. I tried it locally and it did not reproduce.

**Comment by mscb402** [comment]
Can you share your `docker ps` output.  Is etcd is start correct?

**Comment by ZChengjin** [comment]
> Can you share your `docker ps` output. Is etcd is start correct?

![image](https://user-images.githubusercontent.com/44678208/203496790-6d3c94cf-b99e-4961-ac6b-6495ca8738f0.png)
my etcd is started correctly

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/issues/8382#issuecomment-1324737855

**Comment by shreemaan-abhishek** [comment]
@ZChengjin, Do you have any further questions/updates? If not, please close the issue. Thanks.
