### ISSUE TITLE
help request: There was a problem with the installation process

### ISSUE THREAD

**Issue by daodol** [apache/apisix#8321]
### Description

I installed version 2.15 of apisix on centos and then uninstalled it again. I encountered an error while reinstalling version 2.13.1, and in the current situation, I reinstall version 2.15 and the software does not execute correctly
error message：
[root@worker164-host-name apisix]# yum install apisix-2.13.1
已加载插件：fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.bupt.edu.cn
 * epel: mirrors.bfsu.edu.cn
 * extras: mirrors.bfsu.edu.cn
 * updates: mirrors.bupt.edu.cn
正在解决依赖关系
--> 正在检查事务
---> 软件包 apisix.x86_64.0.2.13.1-0.el7 将被 安装
--> 正在处理依赖关系 apisix-base >= 1.19.9.1.4，它被软件包 apisix-2.13.1-0.el7.x86_64 需要
--> 正在检查事务
---> 软件包 apisix-base.x86_64.0.1.21.4.1.3-0.el7 将被 安装
--> 处理 apisix-base-1.21.4.1.3-0.el7.x86_64 与 openresty 的冲突
--> 正在使用新的信息重新解决依赖关系
--> 正在检查事务
---> 软件包 openresty.x86_64.0.1.19.3.2-1.el7 将被 升级
---> 软件包 openresty.x86_64.0.1.21.4.1-1.el7 将被 更新
--> 处理 apisix-base-1.21.4.1.3-0.el7.x86_64 与 openresty 的冲突
--> 解决依赖关系完成
错误：apisix-base conflicts with openresty-1.21.4.1-1.el7.x86_64
 您可以尝试添加 --skip-broken 选项来解决该问题
** 发现 4 个已存在的 RPM 数据库问题， 'yum check' 输出如下：
icedtea-web-1.7.1-1.el7.x86_64 有缺少的需求 java-1.8.0-openjdk
jline-1.0-8.el7.noarch 有缺少的需求 java >= ('0', '1.5', None)
1:libreoffice-core-5.3.6.1-21.el7.x86_64 有缺少的需求 java-headless >= ('1', '1.6', None)
1:libreoffice-ure-5.3.6.1-21.el7.x86_64 有缺少的需求 libjvm.so()(64bit)
[root@worker164-host-name apisix]# client_loop: send disconnect: Connection reset

### Environment

- APISIX version (2.15,2.13.1):
- Operating system (centos7):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Did you also install OpenResty in your local?

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/blob/master/docs/zh/latest/installation-guide.md#%E9%80%9A%E8%BF%87-rpm-%E4%BB%93%E5%BA%93%E5%AE%89%E8%A3%85

**Comment by shreemaan-abhishek** [comment]
ping @daodol
