### ISSUE TITLE
help request:    l  used the plugins  file-logger   ,but it doesnt work

### ISSUE THREAD

**Issue by yanziyu0721730** [apache/apisix#8323]
### Description

![image](https://user-images.githubusercontent.com/32325931/201808206-5ab32b2a-bb5a-4cbf-9596-bbe85aa75709.png)

### Environment

![image](https://user-images.githubusercontent.com/32325931/201808146-27f8398f-bdad-42eb-9526-c7082238b59a.png)

**Comment by yanziyu0721730** [comment]
l used docker to install apisix  but  can not find the log  in my linux  ,can you help me

**Comment by hf400159** [comment]
Can you see logs inside the container?

**Comment by yanziyu0721730** [comment]
thank you  ！l found it in  path  /home/apisix/apisix-docker/example/apisix_log  ,but  l hava another question  dose it  can  record the response context

**Comment by hf400159** [comment]
> thank you ！l found it in path /home/apisix/apisix-docker/example/apisix_log ,but l hava another question dose it can record the response context

https://apisix.apache.org/zh/docs/apisix/plugins/file-logger/

**Comment by hf400159** [comment]
Same as https://github.com/apache/apisix/issues/8331

**Comment by shreemaan-abhishek** [comment]
>  dose it can record the response context

What do you mean by response context?
