### ISSUE TITLE
bug: can't find ext-plugin-post-resp

### ISSUE THREAD

**Issue by yunduansing** [apache/apisix#8324]
### Current Behavior

I need enable ext-plugin-post-resp ,but can't find it 

### Steps to Reproduce

Install from the official docker image：apache/apisix:latest

### Environment

- APISIX version (run `apisix version`): v3.0.0
- Operating system (run `uname -a`): aliyun k8s
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.1
- APISIX Dashboard version, if relevant: latest
- Plugin runner version, for issues related to plugin runners: go-runner
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by hf400159** [comment]
ref: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L473
This plugin is enabled by default in `config-default.yaml`, if you enable plugins in config.yaml, please add this plugin'name to `config.yaml` as well.

**Comment by yunduansing** [comment]
> ref: https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L473 This plugin is enabled by default in `config-default.yaml`, if you enable plugins in `config.yaml`, please add this plugin'name to `config.yaml` as well.


I add ext-plugin-post-resp to `config.yaml`
```
plugins:  
  - ext-plugin-post-resp   
```

but the console log print：

no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/apisix/apisix/plugins/ext-plugin-post-resp.lua'
no file './apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp.so'
no file './apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix.so'
no file '/usr/local/apisix//deps/lib/lua/5.1/apisix.so'
no file '/usr/local/openresty/site/lualib/apisix.so'
no file '/usr/local/openresty/lualib/apisix.so'
no file './apisix.so'
no file '/usr/local/lib/lua/5.1/apisix.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './apisix.so'
no file '/usr/local/lib/lua/5.1/apisix.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix.so'
no file '/usr/local/lib/lua/5.1/loadall.so', context: init_worker_by_lua*
2022/11/15 11:24:32 [warn] 46#46: *4 [lua] plugin.lua:222: load_stream(): new plugins: {"mqtt-proxy":true,"ip-restriction":true,"limit-conn":true}, context: init_worker_by_lua*
2022/11/15 11:24:32 [warn] 54#54: *9 [lua] plugin.lua:172: load(): new plugins: {"ext-plugin-post-resp":true}, context: init_worker_by_lua*
2022/11/15 11:24:32 [error] 54#54: *9 [lua] plugin.lua:109: load_plugin(): failed to load plugin [ext-plugin-post-resp] err: module 'apisix.plugins.ext-plugin-post-resp' not found:
no field package.preload['apisix.plugins.ext-plugin-post-resp']
no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/apisix//deps/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/apisix/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/apisix/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp.ljbc'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp/init.ljbc'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp.ljbc'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp/init.ljbc'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp/init.lua'
no file './apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/apisix/apisix/plugins/ext-plugin-post-resp.lua'
no file './apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/luajit-2.1.0-beta3/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp.lua'
no file '/usr/local/openresty/luajit/share/lua/5.1/apisix/plugins/ext-plugin-post-resp/init.lua'
no file '/usr/local/apisix//deps/lib64/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/apisix//deps/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/site/lualib/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/lualib/apisix/plugins/ext-plugin-post-resp.so'
no file './apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/openresty/luajit/lib/lua/5.1/apisix/plugins/ext-plugin-post-resp.so'
no file '/usr/local/lib/lua/5.1/loadall.so'

**Comment by hf400159** [comment]
Please confirm your apisix version with `apisix version` command, the plugin was released in version 2.15. apisix version

**Comment by yunduansing** [comment]
> Please confirm your apisix version with `apisix version` command, the plugin was released in version 2.15 apisix version

Its aliyun fault,but now we use docker hub image encountered : /docker-entrypoint.sh: line 25: /usr/local/apisix/conf/config.yaml: Read-only file system

**Comment by tzssangglass** [comment]
> Its aliyun fault,but now we use docker hub image encountered : /docker-entrypoint.sh: line 25: /usr/local/apisix/conf/config.yaml: Read-only file system

I don't know what you've done to cause this, you can override `/usr/local/apisix/conf/config.yaml` by mounting config.yaml outside the container

**Comment by tzssangglass** [comment]
> /usr/local/apisix/conf/config.yaml: Read-only file system

same as #8328?
