### ISSUE TITLE
help request: kubernetes service discovery,upstream maybe have risk of loss?

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#8325]
### Description

If kubernetes service discovery is used, my apisix is deploy in pod ,will upstream be lost if apiserver fails to connect？

Will the content of shared memory be reset when apisix reload? According to the code, it should not. But if the pod is restarted, the data will be lost. Is there an etcd that is more secure

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zhixiongdu027** [comment]
> But if the pod is restarted, the data will be lost. Is there an etcd that is more secure
 
Shared memory will be freed unless you enable pod.spec.HostIPC
