### ISSUE TITLE
feat: As a user, I want apisix can provide a query interface to expose its initialization state.

### ISSUE THREAD

**Issue by zhixiongdu027** [apache/apisix#8330]
### Description

Users may want apisix to start providing external services after completing initialization.
Maybe apisix can provide a query interface to expose its own initialization state. （Including plugins, discovery)

**Comment by tokers** [comment]
@zhixiongdu027 Do you mean an inventory about the loading state for plugins, core module, discovery?

**Comment by tzssangglass** [comment]
what is the initialization state?

**Comment by zhixiongdu027** [comment]
apisix is stateless, all data (routing information, node information) is obtained from the outside during initialization.

Before obtaining complete initialization data, apisix may have wrong results when it provides services to the outside world.

Therefore, it is necessary for apisix to provide a flag to indicate that it has been fully initialized. (Get all routes, node information, and plugins are loaded)

Like Readiness and Startup Probes of kubernetes

**Comment by tokers** [comment]
Make sense. Only one concern, if we don't enable the configuration synchronization when APISIX is initing, the synchronization happens in different workers. In such a case, there is no such unified state. This stuff should be considered if we really need to develop this feature.

**Comment by tzssangglass** [comment]
One more question: How do we determine the success of the initialization? Send a signal after something like the normal end of fetching external resources?

**Comment by shreemaan-abhishek** [comment]
ping @zhixiongdu027
