### ISSUE TITLE
help request: I have a question,i used file-logger,18/5000  I want to record that response actually returns the data.

### ISSUE THREAD

**Issue by huangsiting** [apache/apisix#8331]
### Description

Here's what I keep a log of
![image](https://user-images.githubusercontent.com/33561834/201855107-903aa290-3f92-4ccc-9e73-c809bae8b3ec.png)

but I want to record the response returned by the real request address ，like this

![image](https://user-images.githubusercontent.com/33561834/201855481-6ff41f68-b90e-48bf-8aec-a0ab176296cd.png)

### Environment

![image](https://user-images.githubusercontent.com/33561834/201855818-d59241f3-ea31-4dea-847e-192c65011540.png)

**Comment by yanziyu0721730** [comment]
> 

SO ，Do you have any plans to improve this feature

**Comment by spacewander** [comment]
> not support yet, cc @spacewander may be a good first issue?

https://github.com/apache/apisix/blob/2f4a4dba2c0cbc426ae99133c2546112ea71dba8/apisix/plugins/http-logger.lua#L39
Maybe we can add a feature to record response body like the http-logger.

PR is welcome!

**Comment by pixeldin** [comment]
Hi @spacewander, I would love to know more and try it out, can you assign it to me?
