### ISSUE TITLE
etcd value is not same as the dashboard

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8340]
### Description

`bash-5.1# curl http://127.0.0.1:9080/apisix/admin/routes/6  -H 'X-API-KEY: edd1cf034335f136f87ad84b625c8f1' -X PUT -d '
{
    "desc": "",
    "name": "asdfsa",
    "plugins": {
        "ip-restriction": {
            "message": "You Ip adress is not allowd",
            "whitelist": [
                "127.0.0.1/24"
            ]
        }
    },
    "status": 1,
    "upstream_id": "421394408617804478",
    "uris": [
        "www.baidu.com"
    ]
}'
{"action":"set","node":{"value":{"update_time":1668590772,"priority":0,"plugins":{"ip-restriction":{"whitelist":["127.0.0.1\/24"],"message":"You Ip adress is not allowd"}},"desc":"","status":1,"id":"6","create_time":1668590237,"name":"asdfsa","upstream_id":"421394408617804478","uris":["www.baidu.com"]},"key":"\/test\/routes\/6"}}`
when i use the admin api to set values of route,in the etcd Escape characters are automatically added，but in dashboard it's not add.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/535200/202143627-36f3eff0-7273-4c8a-a394-403698eb9011.png">

Q1 :if the etcd value have the escape characters Will it affect  apisix？
Q2: if the etcd value have else value not in plugin attributes,will it affect apisix?
<img width="466" alt="image" src="https://user-images.githubusercontent.com/535200/202144689-a9db1400-e955-42dd-9aab-3224a7b8d9e0.png">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
The backslash doesn't matter.

**Comment by tokers** [comment]
> Q2: if the etcd value have else value not in plugin attributes,will it affect apisix?


No.
