### ISSUE TITLE
docs: update the architecture diagram to reflect the changes in APISIX 3.0 

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#8344]
### Current State

APISIX 3.0 has introduced lots of changes in the architecture of APISIX's DP and CP. For example, now the DP will connect to the CP directly instead of connecting the etcd.

### Desired State

We should update the architecture diagram to reflect the latest situation in APISIX 3.0

**Comment by membphis** [comment]
first version:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/6814606/204464065-c76012fc-47be-433f-a321-9e297113a3a7.png">

**Comment by membphis** [comment]
version second:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/6814606/204469580-7a340db2-43db-478a-9b91-5d85302ee3fa.png">

**Comment by Zerozero-123** [comment]
version 1
![1](https://user-images.githubusercontent.com/95060888/205477254-de73a45a-f659-401e-b7cc-02e53a346582.png)

version 2
![2](https://user-images.githubusercontent.com/95060888/205477286-93bf6389-5981-47b3-b53f-49df29464bd1.png)

version 3
![3](https://user-images.githubusercontent.com/95060888/205477278-6b942ff5-fce5-4eb1-b678-3f5cc54e084e.png)

version 4
![4](https://user-images.githubusercontent.com/95060888/205477298-7a28a797-5a32-4159-8b7f-ecae68f90153.png)

version 5
![5](https://user-images.githubusercontent.com/95060888/205477334-7dbbe257-a3dd-4f88-826b-6fd43e40787f.png)

**Comment by membphis** [comment]
> version 5

I love this version

**Comment by tokers** [comment]
I'm more inclined to version 1. The background color for 3, 4, 5 are too bright for me.

**Comment by Zerozero-123** [comment]
version 6
![version 6](https://user-images.githubusercontent.com/95060888/205611139-12d9529d-eb9d-48a9-a06e-a2d105c179b5.png)

**Comment by Zerozero-123** [comment]
version 7
<img width="1440" alt="version 7" src="https://user-images.githubusercontent.com/95060888/207204436-4cc45fc5-3498-4af0-b4fe-2b2c79063683.png">
version 8
<img width="1440" alt="version 8" src="https://user-images.githubusercontent.com/95060888/207204643-518cf4a3-7a66-410a-b285-5031af2abeb3.png">

**Comment by SkyeYoung** [comment]
Version 6 and 7 are the best until now. 

I prefer version 7. But it still can be improved. 

@Zerozero-123 I have some suggestions below.

![image](https://user-images.githubusercontent.com/48400568/208804133-3ae48d7e-c23c-4831-a2d2-6221d76111ca.png)

**Comment by membphis** [comment]
> I prefer version 7

vote +1 ^_^

**Comment by navendu-pottekkat** [comment]
@membphis What tool are we using to create diagrams? It would be great if we could all use a single tool to create diagrams and use it across all APISIX docs and blog posts we write. What do you think?

**Comment by membphis** [comment]
I mainly use omnigraffle , @Zerozero-123 use different tool, we do not use same tool now

**Comment by Neilblaze** [comment]
@spacewander @membphis can you assign me please if this is up for grabs?

> Please do correct me if I'm wrong, but if [this](https://apisix.apache.org/docs/apisix/architecture-design/apisix) is the architecture page for APISIX, then I noticed that the updates are yet to be reflected for both `v3.1` & `v3.0`.

**Comment by FavourDaniel** [comment]
@spacewander @juzhiyuan @membphis I was about making contribution to the open issue #7336 focused on adding descriptions for the APISIX Architecture diagram on the website. I'm a bit confused on which of the architecture diagram should be focused on. The existing diagram on the website or this new architecture diagram proposed here? Also while going through the videos on the YouTube channel, Bobur made reference to this one while explaining too. Do I take out the existing one, replace with this new one focusing on the data plane and control plane then provide description of the architecture or just provide description for the existing architecture? I already reached out to Navendu and he said to ask it here as well.
