### ISSUE TITLE
bug: apisix 3.0 v3_adapter.filter(data) causes some API response body empty when disabling v3 admin API

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix#8346]
### Current Behavior

https://github.com/apache/apisix/blob/2f4a4dba2c0cbc426ae99133c2546112ea71dba8/apisix/admin/v3_adapter.lua#L180

Perhaps should be `return body` ?

### Steps to Reproduce

curl http://127.0.0.1:9180/apisix/admin/routes -H "X-API-KEY: ******" -i

### Environment

- APISIX version (run `apisix version`): 3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Good catch! Would you like to submit a PR to fix it? Let's add tests in https://github.com/apache/apisix/blob/master/t/admin/api.t to verify the behavior.
