### ISSUE TITLE
bug: apisix同时开启skywalking插件和proxy_rewrite插件时，proxy_rewrite和skywalking-loggine不生效。

### ISSUE THREAD

**Issue by Dignn** [apache/apisix#8348]
### Current Behavior

![image](https://user-images.githubusercontent.com/59277130/202408384-9c73924c-652c-443c-9ba6-c63d4a144755.png)
This is the current proxy_ Rewrite configuration

![image](https://user-images.githubusercontent.com/59277130/202408914-dcea227e-8c8a-4525-b15a-8c5502ee4bb8.png)
This is Skywalking's tracking

I think there is no problem with my rewrite configuration. When I do not enable the skywalking plug-in in config.yaml, it can be forwarded normally.

Is there a solution? Help me

### Steps to Reproduce

。

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Dignn** [comment]
Could it be that the skywalking plug-in failed to execute, causing the subsequent plug-ins to fail to execute? My skywalking plug-in version is 8.6.0-es7.

**Comment by tzssangglass** [comment]
> When I do not enable the skywalking plug-in in config.yaml, it can be forwarded normally.

so if you enable the skywalking plugin, what does it look like to have abnormal forwarding? Gives the request and response, and the associated error log.

> Could it be that the skywalking plug-in failed to execute, causing the subsequent plug-ins to fail to execute? My skywalking plug-in version is 8.6.0-es7.

If this is the case, there will be associated logs in error.log.

**Comment by caiquanyue** [comment]
I have the same problem and there is no associated logs in error.log

**Comment by Dignn** [comment]
I found some problems with my configuration. Sorry.
