### ISSUE TITLE
bug: when using the proxy-mirror plugin, some domain resolution fails in Kubernetes.

### ISSUE THREAD

**Issue by AlinsRan** [apache/apisix#8351]
## Describe

In k8s, the proxy-mirror does not support resolving the following domains: 

* service.namespace
* service.namespace.svc

The same problem as #7796, as far as I know, this problem does not exist in APISIX 3.0。
Whether to consider fixing this problem in version APISIX 2.15.x？

### Error Logs

![8a94c1a9-8d01-4dda-b50e-ae48a230016d](https://user-images.githubusercontent.com/79972061/202406293-b18972b5-79d3-408f-94e2-773c0512ec93.jpeg)

### Environment

- APISIX version (run `apisix version`): 2.15.x

**Comment by spacewander** [comment]
We can backport https://github.com/apache/apisix/pull/7861 to 2.15

**Comment by tao12345666333** [comment]
Thanks!

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.
