### ISSUE TITLE
Directly support dubbo protocol proxy forwarding

### ISSUE THREAD

**Issue by wxbty** [apache/apisix#8352]
### Description

Direct tcp dynamic proxy cannot meet the needs, because it needs to parse the content and do some permission verification and other requirements

**Comment by hf400159** [comment]
https://apisix.apache.org/docs/apisix/plugins/dubbo-proxy/  Does the dubbo-proxy plugin not meet your needs?

**Comment by wxbty** [comment]
> https://apisix.apache.org/docs/apisix/plugins/dubbo-proxy/ Does the dubbo-proxy plugin not meet your needs?
This is http to dubbo, I hope dubbo to dubbo, it is the protocol implementation of xrpc

**Comment by tzssangglass** [comment]
> This is http to dubbo, I hope dubbo to dubbo, it is the protocol implementation of xrpc

In what scenario will it be used?

**Comment by wxbty** [comment]
> > This is http to dubbo, I hope dubbo to dubbo, it is the protocol implementation of xrpc
> 
> In what scenario will it be used?

We are working on a dubbo gateway and need to support mutual access between different network clusters. 
One solution is that dubbo filter sends http requests to apisix, and then transfers to dubbo, but we hope to use the more efficient dubbo protocol to transmit, so as to avoid transfer protocol

**Comment by wxbty** [comment]
For internal calls within the organization, the number of clients and the call path are fixed, and there is no need to use the http protocol

**Comment by tzssangglass** [comment]
not support yet, In fact, this feature relies on the support of the module: [ngx_http_dubbo_module](https://github.com/alibaba/tengine/blob/master/docs/modules/ngx_http_dubbo_module.md).

**Comment by wxbty** [comment]
@tzssangglass  #8246  is mentioned here that it can be extended on xrpc. I hope to mention a pr to implement dubbo's xrpc, can I do this?

**Comment by tzssangglass** [comment]
> @tzssangglass [](https://github.com/apache/apisix/issues/8246) 这里提到[#8246是可以在xrpc上扩展的。](https://github.com/apache/apisix/issues/8246)希望提个pr实现dubbo的xrpc，可以吗？

PR is welcome( #8246 nothing to do with this

**Comment by wxbty** [comment]
> > @tzssangglass  这里提到[#8246是可以在xrpc上扩展的。](https://github.com/apache/apisix/issues/8246)希望提个pr实现dubbo的xrpc，可以吗？
> 
> PR is welcome( #8246 nothing to do with this

updated， #8264
