### ISSUE TITLE
Change the default HTTP router from radixtree_uri to radixtree_host_uri

### ISSUE THREAD

**Issue by tokers** [apache/apisix#8354]
### Description

Hi, community, 

We talked about changing the default HTTP router from `radixtree_uri` to `radixtree_host_uri` in the [mailing list]
(https://lists.apache.org/thread/6kkrdk2bkxmccwho3lk5jz5lrsvbsxgt).

I'll show the content here again:

> Let me just explain the differences between them. The radixtree_uri 
router matches API requests with the existing route tree by URI path, 
While the radixtree_host_uri matches the HTTP host and then matches 
the URI path. 
>
> So when Apache APISIX uses radixtree_uri as the default HTTP router, 
there is a confusing scenario (even we can say it's a bug): Let's say 
we have two routes, the first one requires the host matches 
*.[example.com](http://example.com/), and the URI path is /anything, And the second one needs 
the host matches [foo.example.com](http://foo.example.com/) exactly, and the URI path is also 
/anything. In such a case, if we send an API request, we may hit the 
first route, which is counterintuitive. 
>
> We also have a lot of voices from the community that users have been 
in trouble since they think Apache APISIX will consider the HTTP host 
match by default. However, it's not the case. So I'm here to propose 
changing the default HTTP router to radixtree_host_uri. 
>
> I know this is a broken change, so we may have to do this in 3.x 
releases and may not back it port to the 2.15 LTS version. 
>
> By the way, the radixtree_uri may have better performance than 
radixtree_host_uri, so if we really change the default HTTP router, we 
also need to give users a hint that: if they want better performance 
or you are making a stress test, you may change the HTTP router back 
to the radixtree_uri.

I think to implement the change, we need to close the tasks below:

- [ ] Coding for changing the default URI, making all the test cases passed
- [ ] Write docs for claiming the broken change
- [ ] Write docs for giving users a hint about the performance difference between `radixtree_host_uri` and `radixtree_uri`, give them some advice about the performance tuning

**Comment by XFarooqi** [comment]
Hi @tokers 
I am wokring on the issue.

As per the investigation, it is found that the possible changes will be in [_M.http_init_worker()](https://github.com/apache/apisix/blob/b822423b9a1f0f42537462356697d128c4fa897d/apisix/router.lua#:~:text=local%20router_http_name%20%3D%20%22radixtree_uri%22)

Can you please guide me in testing stuff, as I am finding it difficult to understand the test cases?
Where do I have to update the doc for the changes?

**Comment by tokers** [comment]
> Hi @tokers I am wokring on the issue.
> 
> As per the investigation, it is found that the possible changes will be in [_M.http_init_worker()](https://github.com/apache/apisix/blob/b822423b9a1f0f42537462356697d128c4fa897d/apisix/router.lua#:~:text=local%20router_http_name%20%3D%20%22radixtree_uri%22)
> 
> Can you please guide me in testing stuff, as I am finding it difficult to understand the test cases? Where do I have to update the doc for the changes?

@XFarooqi Actually, just change the default value for the setting "http.router" in config-default.yaml, and run all the test cases, fix the failed ones.

**Comment by tokers** [comment]
As for the doc, write some hints in https://apisix.apache.org/docs/apisix/terminology/router/.
