### ISSUE TITLE
/opt/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/opt/apisix-2.15.1/deps/lib/lua/5.1/ssl.so'

### ISSUE THREAD

**Issue by lianglinhuan** [apache/apisix#8361]
### Current Behavior

 apisix init

### Expected Behavior

/opt/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init

### Error Logs

/opt/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/opt/openresty/luajit/bin/luajit: error loading module 'ssl.core' from file '/opt/apisix-2.15.1/deps/lib/lua/5.1/ssl.so':
        /opt/apisix-2.15.1/deps/lib/lua/5.1/ssl.so: undefined symbol: OPENSSL_sk_num
stack traceback:
        [C]: at 0x00454bd0
        [C]: in function 'require'
        /opt/apisix-2.15.1/deps/share/lua/5.1/ssl.lua:8: in main chunk
        [C]: in function 'require'
        /opt/apisix-2.15.1/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
        [C]: in function 'require'
        ./apisix/cli/etcd.lua:24: in main chunk
        [C]: in function 'require'
        ./apisix/cli/ops.lua:18: in main chunk
        [C]: in function 'require'
        ./apisix/cli/apisix.lua:38: in main chunk
        [C]: at 0x004056f0

### Steps to Reproduce

1.使用源码安装apisix2.15.1版本后
2.计划执行apisix init初始化集群
3.执行命令出现以上的错误

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
apisix：2.15.1
openresty：2.14.1
etcd:3.5.4
LuaRocks:3.8.0
Lua:5.4.3

**Comment by lianglinhuan** [comment]
会不会是openssl的版本问题，我现在安装的版本是OpenSSL_1_1_1o

**Comment by tzssangglass** [comment]
> 会不会是openssl的版本问题，我现在安装的版本是OpenSSL_1_1_1o

do you have `${APISIX install dir}/deps/lib/lua/5.1/ssl.so`?

**Comment by pioneer-hash** [comment]
> > 会不会是openssl的版本问题，我现在安装的版本是OpenSSL_1_1_1o
> 
> do you have `${APISIX install dir}/deps/lib/lua/5.1/ssl.so`?

我安装apisix：2.13.3 也有这个问题，这个ssl.so 文件在${APISIX install dir}/deps/lib/lua/5.1/ssl.so 也是存在的

**Comment by tzssangglass** [comment]
> 会不会是openssl的版本问题，我现在安装的版本是OpenSSL_1_1_1o

maybe,  normally we install openresty-openssl111 from the rpm/dep repository of openresty and use it when compiling apisix-base.

my version `OpenSSL 1.1.1s`

**Comment by tokers** [comment]
What are the installation steps? Did you already install the old apisix version?

**Comment by tokers** [comment]
> What are the installation steps? Did you already install the old apisix version?

If so, did you reinstall openresty? Or just use the existing one.

**Comment by lianglinhuan** [comment]
> > What are the installation steps? Did you already install the old apisix version?
> 
> If so, did you reinstall openresty? Or just use the existing one.

是的，我已经安装了旧版的apisix 2.15.0版本，openssl使用的是openssl 1.1.1o的版本，没有重装新的openssl。但是我之前是尝试过，安装openresty使用的是openssl 1.1.1s版本，系统使用的是openssl 1.1.1o，来安装apisix 2.15.1，还是会出现之前的那个问题。

**Comment by tzssangglass** [comment]
what output of `ldd ${APISIX install dir}/deps/lib/lua/5.1/ssl.so`?
