### ISSUE TITLE
bug: when using nacos discoverytype , return HTTP 500 and variable applications is nil

### ISSUE THREAD

**Issue by panpingyuan** [apache/apisix#8363]
### Current Behavior

when using nacos discoverytype , return HTTP 500 and variable applications is nil

### Expected Behavior

When using nacos to pressure test apisix2.13.0, error HTTP 500 is reported and variable applications is nil

### Error Logs

 
![15fe386acfbc41ff2551a8d37e7c4fa](https://user-images.githubusercontent.com/35962517/202885637-5e2a780f-0d6f-42af-b5ae-a643e437f53e.jpg)

### Steps to Reproduce

When using nacos to pressure test apisix2.13.0,

### Environment

- APISIX version (run `apisix version`):2.13.0
- Operating system (run `uname -a`): 4.19.90-23.26.v2101.ky10.aarch64 (kylin V10)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant:2.10.1

**Comment by mscb402** [comment]
Can you share your config?

**Comment by tzssangglass** [comment]
1. don't use pictures, use text
2. provide complete reproduction steps

**Comment by panpingyuan** [comment]
In the k8s environment, use the default Settings。There is no error when worker_processes is set to 4 instead of auto

**Comment by mscb402** [comment]
Perhaps you can send out your apisix configuration and nacos config

**Comment by mscb402** [comment]
Any thing can help us to solve this issues

**Comment by panpingyuan** [comment]
Thanks, docker environment worker_processes are caused by using auto
