### ISSUE TITLE
bug: 导入自建证书后，通过接口查看为空！

### ISSUE THREAD

**Issue by jiahui1988** [apache/apisix#8365]
### Current Behavior

1: 导入证书：
<img width="1670" alt="image" src="https://user-images.githubusercontent.com/75962736/202963756-1bb07e5c-6e5f-414e-8a1a-eb5039343773.png">

<img width="1613" alt="image" src="https://user-images.githubusercontent.com/75962736/202963437-544f3e4f-086a-46f7-aa2f-9f7008277377.png">

2：查看证书：
     curl "http://127.0.0.1:9180/apisix/admin/ssls" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

      {"list":[],"total":0}

### Steps to Reproduce

随便生成一个整数，导入后就是这个效果

### Environment

apisix：3.0

**Comment by jiahui1988** [comment]
1: etcd中查询存在证书
 
<img width="656" alt="image" src="https://user-images.githubusercontent.com/75962736/202965195-89e3e625-3357-4cb5-8cc6-dd2bf01c56b9.png">

2： 通过接口查询, 提示不存在key
curl "http://127.0.0.1:9180/apisix/admin/ssls/423343078246449861" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

{"message":"Key not found"}

**Comment by mscb402** [comment]
Look like it write to ETCD not correctly. Can you see the certificate after refreshing this webpage?

**Comment by jiahui1988** [comment]
> Can you see the certificate after refreshing this webpage

刷新网页也是一样的。

**Comment by jiahui1988** [comment]
> > Can you see the certificate after refreshing this webpage
> 
> 刷新网页也是一样的。

 1： 刷新网页

**Comment by jiahui1988** [comment]
<img width="1623" alt="image" src="https://user-images.githubusercontent.com/75962736/202967658-bcee2647-bc6c-4392-b8e2-a2d750427edf.png">
2：点击配置

**Comment by jiahui1988** [comment]
> 

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/75962736/202967755-eeac43c2-f2e4-45f2-a4c4-5918884f9ed6.png">

**Comment by jiahui1988** [comment]
> Look like it write to ETCD not correctly. Can you see the certificate after refreshing this webpage? It shouldn't be listed in the webpage If not written successfully.

但是从前端console调试上看，是有相应的

**Comment by jiahui1988** [comment]
> Look like it write to ETCD not correctly. Can you see the certificate after refreshing this webpage? It shouldn't be listed in the webpage If not written successfully.

但是从前端console调试上看，是有响应的

**Comment by jiahui1988** [comment]
> Look like it write to ETCD not correctly. Can you see the certificate after refreshing this webpage? It shouldn't be listed in the webpage If not written successfully.

dan但从前端console调试看是有响应的。
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/75962736/202968213-bb814ace-c7bb-4801-b699-0eb5f6fdb02b.png">
那为啥调用这个接口，显示Key不存在呢？     curl "http://127.0.0.1:9180/apisix/admin/ssls/423343078246449861" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

{"message":"Key not found"}

**Comment by mscb402** [comment]
Sorry, I misunderstood. Look like writing to etcd is correct. But API access is wrong. Can you try access 
` curl "http://127.0.0.1:9180/apisix/admin/ssl/423343078246449861" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

**Comment by jiahui1988** [comment]
> curl "http://127.0.0.1:9180/apisix/admin/ssl/423343078246449861" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/75962736/202969175-6026e004-c594-4b4a-8188-84ed96677ba1.png">

**Comment by mscb402** [comment]
Emm, this is so weird. Please waiting. Let me try it

**Comment by mscb402** [comment]
I think I know what happens. The apisix-dashboard currently does not support apisix 3.0.
apisix 3.0 current change `/apisix/admin/ssl/{id}` to `/apisix/admin/ssls/{id}`. But the old version apisix-dashboard still upload the certificate to `/apisix/admin/ssl/`. So you can get a certificate from etcd but can't get one from APIs

**Comment by jiahui1988** [comment]
>

**Comment by jiahui1988** [comment]
> I think I know what happens. The apisix-dashboard currently does not support apisix 3.0. apisix 3.0 current change `/apisix/admin/ssl/{id}` to `/apisix/admin/ssls/{id}`. But the old version apisix-dashboard still upload the certificate to `/apisix/admin/ssl/`. So you can get a certificate from etcd but can't get one from APIs现在通过调用api /apisix/admin/ssls/{id}是不行的。

**Comment by jiahui1988** [comment]
> I think I know what happens. The apisix-dashboard currently does not support apisix 3.0. apisix 3.0 current change `/apisix/admin/ssl/{id}` to `/apisix/admin/ssls/{id}`. But the old version apisix-dashboard still upload the certificate to `/apisix/admin/ssl/`. So you can get a certificate from etcd but can't get one from APIs

不通过apisix-dashboard调用。而通过apisix的接口调用 /apisix/admin/ssls/{id}，现在看也是拿不到数据的。

**Comment by mscb402** [comment]
Using `/apisix/admin/ssls` to create a certificate isn't work? Now you can only create a certificate from API and get it from API.

**Comment by mscb402** [comment]
Please try again. Using API to create a cert: https://apisix.apache.org/docs/apisix/admin-api/#ssl

**Comment by jiahui1988** [comment]
> Please try again. Using API to create a cert: https://apisix.apache.org/docs/apisix/admin-api/#ssl
如果用这个api，响应中 没有"snis" ，"validity_start" "validity_end"等字段？

**Comment by mscb402** [comment]
SNIS exists in the response struct. But `validity_start` and `validity_end` these two fields do not, These two fields are coming from apisix-dashboard.

**Comment by mscb402** [comment]
> SNIS exists in the response struct. But `validity_start` and `validity_end` these two fields do not, These two fields are coming from apisix-dashboard.

But you should set the SNIs manually when creating a certificate.

**Comment by jiahui1988** [comment]
> > SNIS exists in the response struct. But `validity_start` and `validity_end` these two fields do not, These two fields are coming from apisix-dashboard.
> 
> But you should set the SNIs manually when creating a certificate.

原生的证书格式是：
<img width="641" alt="image" src="https://user-images.githubusercontent.com/75962736/202993020-3b150631-21b8-4bad-b470-5d2b564acd99.png">
类似这种多行的，貌似报错，需要将多行用\n来填充成一行？

**Comment by mscb402** [comment]
是的

**Comment by jiahui1988** [comment]
> yes

貌似。利用API不能上传证书文件。

**Comment by mscb402** [comment]
You should copy the certificate file and replace the new line with `\n`, then post it to API
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/11229089/202994448-94366cfa-9234-49d2-8b47-ac3ba5c09f0e.png">

**Comment by gudieaofei** [comment]
When apisix-dashboard will support apisix 3?

**Comment by mscb402** [comment]
It might take a little more time
