### ISSUE TITLE
request help: proxy grpc requests without retries

### ISSUE THREAD

**Issue by xionghanhan** [apache/apisix#8373]
### Current Behavior

请求到超时服务的节点，到达超时时间后，直接返回504，没有转发到另一个节点。

### Expected Behavior

请求到超时服务的节点，到达超时时间后，请求转发到另一个服务节点。

### Steps to Reproduce

1.使用docker部署的apisix。
2.docker部署两个grpc服务
3.apisix-dashboard配置如下图
![image](https://user-images.githubusercontent.com/79395110/203244537-32899cb5-b336-4de8-8e43-cd1ddb651b97.png)

### Environment

apache/apisix:2.12.0-alpine

**Comment by mscb402** [comment]
Maybe health check is what you need. https://apisix.apache.org/zh/docs/apisix/tutorials/health-check/

**Comment by xionghanhan** [comment]
我试了http服务，同样的配置，超时是可以转发到另一个节点的。grpc服务就不行。

**Comment by xionghanhan** [comment]
健康检查，grpc服务只能使用tcp类型吗，这个无法探查出服务超时吧。

**Comment by tzssangglass** [comment]
Maybe we need to support `grpc_next_upstream`, and `grpc_next_upstream_timeout` ref: 
 http://nginx.org/en/docs/http/ngx_http_grpc_module.html#grpc_next_upstream_timeout

**Comment by tokers** [comment]
The retry feature is not supported yet for grpc @xionghanhan .

**Comment by xionghanhan** [comment]
好的，感谢解答疑惑，希望可以越做越好，支持一下哈。
