### ISSUE TITLE
feat:  As a user, I use kubernetes service discovery ,i wan’t to get the endpoints from the apisix

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#8375]
### Description

I use kubernetes service discovery ,i wan’t to get the endpoints from the apisix，Now apisix get the endpoints from apiserver are stored in the dict, there is no interface to find out, if there is a problem, there is no way to get the ips in apisix, hope to provide an interface to get the ip list in the dict

**Comment by tzssangglass** [comment]
> there is no interface to find out,

try with: https://github.com/apache/apisix/blob/master/docs/en/latest/discovery.md#embedded-control-api-for-debugging

**Comment by shreemaan-abhishek** [comment]
any updates @wolgod?
