### ISSUE TITLE
help request: dubbo-proxy plugin does not take effect

### ISSUE THREAD

**Issue by wxbty** [apache/apisix#8382]
### Description

1、Start apisix with docker：
git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example
docker-compose -p docker-apisix up -d

2、add dubbo-proxy plugin
vim example/dashboard_conf/conf.yaml  
remove # in front of dubbo-proxy

plugins:                          # plugin list (sorted in alphabetical order)
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  - dubbo-proxy  
  - echo
  

3、 reload
curl http://127.0.0.1:9180/apisix/admin/plugins/reload -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT

4、create route，refer to 
https://apisix.apache.org/zh/blog/2022/01/13/how-to-proxy-dubbo-in-apache-apisix/#%E5%85%A5%E9%97%A8%E7%AF%87%E5%AE%89%E8%A3%85%E4%BD%BF%E7%94%A8

curl http://127.0.0.1:9180/apisix/admin/upstreams/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "nodes": {
        "127.0.0.1:20880": 1
    },
    "type": "roundrobin"
}'
curl http://127.0.0.1:9180/apisix/admin/routes/1  -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "host": "127.0.0.1",    #There is a problem in the document，missing a comma here
    "uris": [
        "/demo"
    ],
    "plugins": {
        "dubbo-proxy": {
            "service_name": "org.apache.dubbo.springboot.demo.DemoService",
            "service_version": "0.0.0",
            "method": "sayHello"
        }
    },
    "upstream_id": 1
}'
Here returns the error：
{"error_msg":"unknown plugin [dubbo-proxy]"}

There are some warnings in the log，like #8318 ：
2022/11/23 07:43:11 [warn] 47#47: *17222 [lua] init.lua:309: sync_local_conf_to_etcd(): sync local conf to etcd, client: 172.18.0.1, server: , request: "PUT /apisix/admin/plugins/reload HTTP/1.1", host: "127.0.0.1:9180"
2022/11/23 07:43:11 [warn] 51#51: *17224 [lua] plugin.lua:250: load_stream(): new plugins: {"ip-restriction":true,"syslog":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
2022/11/23 07:43:11 [warn] 48#48: *17223 [lua] plugin.lua:250: load_stream(): new plugins: {"ip-restriction":true,"syslog":true,"limit-conn":true,"mqtt-proxy":true}, context: ngx.timer
2022/11/23 07:43:17 [warn] 47#47: *47 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2022/11/23 07:43:17 [warn] 47#47: *46 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2022/11/23 07:43:17 [warn] 47#47: *40 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer

### Environment

- APISIX version (run `apisix version`):  3.0.0
- Operating system (run `uname -a`):  mac m1
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1;built by gcc 10.2.1 20210110 (Debian 10.2.1-6);built with OpenSSL 1.1.1n 15 Mar 2022
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wxbty** [comment]
Tried restarting docker, still not working

**Comment by Hazel6869** [comment]
@wxbty Hi, these plugins can have effect? 
![image](https://user-images.githubusercontent.com/30279880/203499329-caf4b1a9-1621-40c7-a622-9c6da1a09e82.png)

**Comment by Hazel6869** [comment]
> Tried restarting docker, still not working

how do you restart? can you give me your command?

**Comment by wxbty** [comment]
This is there after installation, I have not tried  @Hazel6869

**Comment by Hazel6869** [comment]
@wxbty  If you are sure to restart, maybe you can refer to this issue  https://github.com/apache/apisix/issues/8376

**Comment by wxbty** [comment]
![image](https://user-images.githubusercontent.com/38374721/203500557-7318d129-9341-4ead-ab04-cf79a2eaadb7.png)

**Comment by Hazel6869** [comment]
> ![image](https://user-images.githubusercontent.com/38374721/203500557-7318d129-9341-4ead-ab04-cf79a2eaadb7.png)

you can do like this `docker-compose -p docker-apisix restart`

**Comment by wxbty** [comment]
I have seen this issue, but the docker installation directory does not use the default file, so I can't modify it
![image](https://user-images.githubusercontent.com/38374721/203501018-5416673a-e11a-4fd0-a0d0-7f463b8965fa.png)
Then the docs describe that config.yaml will override config-default.yaml, but that's not happening

**Comment by wxbty** [comment]
> > ![image](https://user-images.githubusercontent.com/38374721/203500557-7318d129-9341-4ead-ab04-cf79a2eaadb7.png)
> 
> you can do like this `docker-compose -p docker-apisix restart`

not in effect， @Hazel6869 
![image](https://user-images.githubusercontent.com/38374721/203501808-c1090547-a296-4ddf-b1a7-c1fac6fab1bf.png)

**Comment by wxbty** [comment]
It seems that the reason for not being able to access etcd, and not getting the latest plugin.
![image](https://user-images.githubusercontent.com/38374721/203504094-436a6d11-057c-484c-b19f-e0d2b5b854f6.png)

**Comment by wxbty** [comment]
![image](https://user-images.githubusercontent.com/38374721/203505304-85d7cf1f-ac4e-4699-bd88-ae0078a987c3.png)
It can be seen that the loaded plugin list does not contains dubbo, and there is no other more information

**Comment by wxbty** [comment]
Maybe it's an etcd folder permission problem ，etcd  docker log：
2022-11-23 08:33:16.776013 I | embed: initial advertise peer URLs = http://localhost:2380
2022-11-23 08:33:16.776185 I | embed: initial cluster =
2022-11-23 08:33:16.783323 W | pkg/fileutil: check file permission: directory "/etcd-data" exist, but the permission is "drwxr-xr-x". The recommended permission is "-rwx------" to prevent possible unprivileged access to the data.
2022-11-23 08:33:16.858998 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 86
raft2022/11/23 08:33:16 INFO: 8e9e05c52164694d switched to configuration voters=()
raft2022/11/23 08:33:16 INFO: 8e9e05c52164694d became follower at term 4
raft2022/11/23 08:33:16 INFO: newRaft 8e9e05c52164694d [peers: [], term: 4, commit: 86, applied: 0, lastindex: 86, lastterm: 4]
2022-11-23 08:33:16.885387 W | auth: simple token is not cryptographically signed
2022-11-23 08:33:16.892295 I | etcdserver: starting server... [version: 3.4.15, cluster version: to_be_decided]
2022-11-23 08:33:16.894044 I | embed: listening for peers on 127.0.0.1:2380
raft2022/11/23 08:33:16 INFO: 8e9e05c52164694d switched to configuration voters=(10276657743932975437)
2022-11-23 08:33:16.894578 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2022-11-23 08:33:16.894872 N | etcdserver/membership: set the initial cluster version to 3.4
2022-11-23 08:33:16.894898 I | etcdserver/api: enabled capabilities for version 3.4
2022-11-23 08:33:16.895175 W | etcdserver: failed to apply request "header:<ID:7587866785361419287 > lease_revoke:<id:694d84a333a1813c>" with response "size:28" took (72.667µs) to execute, err is lease not found
raft2022/11/23 08:33:18 INFO: 8e9e05c52164694d is starting a new election at term 4
raft2022/11/23 08:33:18 INFO: 8e9e05c52164694d became candidate at term 5
