### ISSUE TITLE
bug: external-plugin-post-resp plugin converts content-type from upstream response

### ISSUE THREAD

**Issue by seowjin1060** [apache/apisix#8388]
### Current Behavior

Bug : external-plugin-post-resp converts reponse  content types to plain/text

- Json response if request sended  directly to test api server 
![image](https://user-images.githubusercontent.com/26168539/203705459-fccb90a2-4c55-4715-9e0b-0a4810c101d8.png)

- Encoded to plain/text if request sended via apisix upstream 
![image](https://user-images.githubusercontent.com/26168539/203719724-5ccb86d3-e63c-4922-85de-1c1762966039.png)

### Steps to Reproduce

Testing with local apisix & test api server env  (apisix  3.0.0 on 9080 port , test api server with 8000 port )

- Enable ext-plugin-post-resp plugin (APISIX version > 2.99)
- no support in apisix dashboard(2.13) so needed to be add by admin api 
curl http://localhost:9180/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '{"plugins":{"ext-plugin-post-resp": {"allow_degradation":true,"conf":[{"value":"", "name":"PostResponseFilter"}],"disable":false}}}'

Plugin Configuration
```
{
  "allow_degradation": false,
  "conf":[
    {
       "name": "PostResponseFilter",
       "value": ""
    }
  ],
  "disable": false
}

```

- Json response if request sended  directly to test api server 
![image](https://user-images.githubusercontent.com/26168539/203705459-fccb90a2-4c55-4715-9e0b-0a4810c101d8.png)

- Encoded to plain/text if request sended via apisix upstream 
![image](https://user-images.githubusercontent.com/26168539/203719724-5ccb86d3-e63c-4922-85de-1c1762966039.png)

Cause many type of api servers handled by apisix, some of them don't handle http response with json automatically,

I expecting apisix not to convert response types to text/plain.

Any approach or opinion will be appreciated to fix this problems 

### Expected Behavior

Content type must be consist after handled by apisix upstream.

### Error Logs

This seems to logical problem with apisix core, so no error logs included

### Environment

- APISIX version (run `apisix version`): 2.99
- Operating system (run `uname -a`): RHEL 8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners: java 17
- LuaRocks version, for installation issues (run `luarocks --version`):  5.4.4

**Comment by mscb402** [comment]
Because there's a 302 status response. Maybe you can try accessing using HTTPS.
`curl -v -H "Accept: application/json" https://localhost:9443/mlc`

**Comment by mscb402** [comment]
Or disable HTTPS on your apisix route

**Comment by seowjin1060** [comment]
> Or disable HTTPS on your apisix route

Thank you for reply, there are some difference between sample and production environment. So 302 was appeared.

I updated example to production which 302 status was not appeared but content type was converted to text/plain.

And, Here's Route configuration tends to keep http method for each request.
![image](https://user-images.githubusercontent.com/26168539/203706245-7688f694-7cdd-4538-af37-9ee3582e715e.png)

**Comment by mscb402** [comment]
In your case, this is HTTP 500 status. Please try to test the HTTP 200 status upstream. Is 200 status still have this problem?

**Comment by seowjin1060** [comment]
Yes, that status code is from upstream target, not from apisix. 
So upstream responses with 200 code may affected with this issue, cause upstream response seems to be encoded with text/html via apisix.

Here's sample request to test server with 200 response code
![image](https://user-images.githubusercontent.com/26168539/203720212-54eaf10a-44d9-4ce5-8151-ee8020f642f5.png)

**Comment by mscb402** [comment]
Sorry, I try this on my local, but I can't make this happen again on my local. Please share your config. It depends on how you 
upstream response.

**Comment by WangSZ** [comment]
I have a similar problem that plugin-post-resp plugin changed upstream headers such as "Content-Type ,Access-Control-Allow-Origin,Access-Control-Allow-Credentials". The upstream is http://[httpbin.org](http://httpbin.org/)/


![image](https://user-images.githubusercontent.com/1385039/206895291-6d17af93-b928-4667-b8ab-016a9a74c474.png)

**Comment by soulbird** [comment]
Looks like a bug, the ext-plugin-post-resp plugin ignores the upstream content-type response header. refer: https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin/init.lua#L804-L809

**Comment by yunduansing** [comment]
I met the problem too
![image](https://user-images.githubusercontent.com/11469334/206971531-3422d471-b5ca-4f8b-84e5-a733ad0e8650.png)

**Comment by ZChengjin** [comment]
I also encountered this problem, is there a solution now?

**Comment by soulbird** [comment]
> I also encountered this problem, is there a solution now?

We can try to remove https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin/init.lua#L79

**Comment by yunduansing** [comment]
> I also encountered this problem, is there a solution now?

You can try enable the official "response-rewrite" plugin and config headers.set: Content-Type can solve this problem:
`"headers": {
    "set": {
      "Content-Type": "application/json; charset=utf-8"
    }
  }`

![image](https://user-images.githubusercontent.com/11469334/209898551-64d0bc93-f94c-472f-90c6-463a61a11fb2.png)

**Comment by seowjin1060** [comment]
> > I also encountered this problem, is there a solution now?
> 
> We can try to remove https://github.com/apache/apisix/blob/master/apisix/plugins/ext-plugin/init.lua#L79

HI there, how about deleting content-encoding also? 
Seems that causing charset fixed to utf-8.
Checked working normally if content-type / charset deleted from excluded header.

And I'll look into case if we are using post-response runner to use response from plugin. Because deleting excluded header will need to be writing requested header on runner response (postresponsefilter).

**Comment by soulbird** [comment]
In fact, I don't think we should restrict any modification of response headers, after all the response-rewrite plugin does not have any restrictions.  cc @spacewander

**Comment by spacewander** [comment]
> In fact, I don't think we should restrict any modification of response headers, after all the response-rewrite plugin does not have any restrictions. cc @spacewander

LGTM

**Comment by edisonX-sudo** [comment]
> I also encountered this problem, is there a solution now?

could be solved in this way
```go
...
func (ri *ResponseI18n2) ResponseFilter(conf interface{}, w pkgHTTP.Response) {
	respHeader := w.Header()
	contentType := respHeader.Get("Content-Type")
	respHeader.Set("X-Content-Type", contentType)
        ...
}
...
```
```apisix config
...
 "response-rewrite": {
      "_meta": {
        "disable": false
      },
      "headers": {
        "set": {
          "Content-Type": "$sent_http_x_content_type"
        }
      }
    }
...
```
