### ISSUE TITLE
how can i get cluster node number?

### ISSUE THREAD

**Issue by CuttleFishMan** [apache/apisix#8395]
### Description

hey guy,
I want to get the number of nodes which is in the cluster,how can i do that?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@CuttleFishMan Hi, can  you give me more information, I don't understand you 😣

**Comment by tzssangglass** [comment]
> I want to get the number of nodes which is in the cluster,how can i do that?

enable the server-info plugin, and each apisix instance will report its own node id to etcd by server-info plugin.
