### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by Drewolf** [apache/apisix#8399]
### Description

**背景：**
    我通过apisix-dashboard创建了一条路由，后端配置的是k8s集群中的SVC，目前想在 apisix-dashboard 上通过全局跨域插件，配置接口允许部分 origin 跨域访问。

**问题：**
    使用插件默认配置，allow_origins 配置为 * ，可正常允许跨域。但是想通过配置allow_origins_by_regex，使用正则表达式数组来匹配允许跨域访问的 Origin，则跨域配置不生效。

 **具体配置细节：**
 allow_origins 配置为 * ，可正常允许跨域
![image](https://user-images.githubusercontent.com/30138193/203886113-1fff97b4-faef-4265-8425-3cbd1fd3ef21.png)

![image](https://user-images.githubusercontent.com/30138193/203887127-33d1fb6f-419a-41ed-b1a4-9e2cff8ce13d.png)

配置allow_origins_by_regex，使用正则表达式数组来匹配允许跨域访问的 Origin，则跨域配置不生效
![image](https://user-images.githubusercontent.com/30138193/203887311-935c0e00-21b6-4f7f-9778-72c31525c088.png)

![image](https://user-images.githubusercontent.com/30138193/203887568-6ec6037b-3511-40eb-9dca-658e90b6dacd.png)

### Environment

- APISIX version (run `apisix version`):
2.15.0-alpine
- Operating system (run `uname -a`):
helm 部署
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
3.5.4-debian-11-r14
- APISIX Dashboard version, if relevant:
2.13-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
I think config should be 
```json
{
"allow_origins":"*",
"allow_methods":"*",
"allow_headers":"*",
"expose_headers":"*",
"max_age":5,
"allow_credential":false,
"allow_origins_by_regex":[".*\.test.com"]
}
```

**Comment by Drewolf** [comment]
还是有问题
![image](https://user-images.githubusercontent.com/30138193/203890190-d9c37f85-551c-4c62-b085-721d6db178bb.png)

![image](https://user-images.githubusercontent.com/30138193/203890252-c329e232-c245-40f9-b700-5e22a8ba8ede.png)

**Comment by Drewolf** [comment]
> I think config should be
> 
> ```json
> {
>   "allow_origins": "*",
>   "allow_methods": "*",
>   "allow_headers": "*",
>   "expose_headers": "*",
>   "max_age": 5,
>   "allow_credential": false,
>   "allow_origins_by_regex": [".*\\.test.com"]
> }
> ```

thanks, There's still a problem

**Comment by mscb402** [comment]
Please wait let me try it

**Comment by mscb402** [comment]
I try it on my local env. I know what happened. This is because cors plugin will match 'allow_origins' first, if 'allow_origins' not match then it will try match it with regex using 'allow_origins_by_regex'.

So, right config is
```json
 {
      "allow_credential": false,
      "allow_headers": "*",
      "allow_methods": "*",
      "allow_origins": "http://example.com",
      "allow_origins_by_regex": [
        ".*\\.test\\.com",
        "test\\.com"
      ],
      "expose_headers": "*",
      "max_age": 5
    }
```

or 
```json
 {
      "allow_credential": false,
      "allow_headers": "*",
      "allow_methods": "*",
      "allow_origins": "http://test.com",
      "allow_origins_by_regex": [],
      "expose_headers": "*",
      "max_age": 5
    }
```

**Comment by mscb402** [comment]
Then try it from curl

will return cors header
```
➜  curl  http://127.0.0.1:9080/status/200 -H 'host: cb.com' -H 'Origin: test.com' -v 
*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET /status/200 HTTP/1.1
> Host: cb.com
> User-Agent: curl/7.84.0
> Accept: */*
> Origin: test.com
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Date: Fri, 25 Nov 2022 03:28:37 GMT
< Access-Control-Allow-Origin: test.com
< Access-Control-Allow-Credentials: true
< Server: APISIX/3.0.0
< Vary: Origin
< Access-Control-Allow-Methods: *
< Access-Control-Max-Age: 5
< Access-Control-Expose-Headers: *
< Access-Control-Allow-Headers: *
< 
* Connection #0 to host 127.0.0.1 left intact
```


no cors header return
```
➜   curl  http://127.0.0.1:9080/status/200 -H 'host: cb.com'  -v                        
*   Trying 127.0.0.1:9080...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET /status/200 HTTP/1.1
> Host: cb.com
> User-Agent: curl/7.84.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Date: Fri, 25 Nov 2022 03:29:17 GMT
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Server: APISIX/3.0.0
< 
* Connection #0 to host 127.0.0.1 left intact
```

**Comment by Drewolf** [comment]
> I try it on my local env. I know what happened. This is because the cors plugin will match `allow_origins` first, if `allow_origins` does not match then it will try to match it with regex using `allow_origins_by_regex`.
> 
> Therefore when `allow_origins` set as `*`, any URL will matched, so that `allow_origins_by_regex` will not match again.
> 
> So, the right config is below. You can change `http://example.com` to any URL you are NOT using like `http://baidu.com` or `http://xxx.com`. Just make `allow_origins` not match.
> 
> ```json
>  {
>       "allow_credential": false,
>       "allow_headers": "*",
>       "allow_methods": "*",
>       "allow_origins": "http://example.com",
>       "allow_origins_by_regex": [
>         ".*\\.test\\.com",
>         "test\\.com"
>       ],
>       "expose_headers": "*",
>       "max_age": 5
>     }
> ```
> 
> or
> 
> ```json
>  {
>       "allow_credential": false,
>       "allow_headers": "*",
>       "allow_methods": "*",
>       "allow_origins": "http://test.com",
>       "allow_origins_by_regex": [],
>       "expose_headers": "*",
>       "max_age": 5
>     }
> ```

这样是正常的吗？response中没有任何跨域相关的 header
![image](https://user-images.githubusercontent.com/30138193/203904144-0cf8e68a-a193-42af-b607-ca426e3560f0.png)


![image](https://user-images.githubusercontent.com/30138193/203904053-36bcc765-abf0-4ae1-a11f-87cbc00b5e40.png)

**Comment by mscb402** [comment]
But this isn't what you want? Only match `Origin: test.com` exist cors header, others do not. Please be clear about what you want

**Comment by mscb402** [comment]
Be attention set `-H 'Origin: test.com'` on your curl If you are missing

**Comment by Drewolf** [comment]
> Contributor
> ### ** [mscb402](/mscb402) ** commented [Nov 25, 2022](#issuecomment-1327024256) •

我的CORS配置如下，其中有一条 ".*\\.ceshi.xgimi.com:8080"。目的是想配置允许 *.ceshi.xgimi.com:8080 跨域访问。但是响应头中没有任何跨域header
```
{
  "allow_origins": "http://example.com",
  "allow_methods": "*",
  "allow_headers": "*",
  "expose_headers": "*",
  "max_age": 5,
  "allow_credential": false,
  "allow_origins_by_regex": [".*\\.qa.xgimi.com", ".*\\.ceshi.xgimi.com:8080"]
}
```
![image](https://user-images.githubusercontent.com/30138193/203905628-7a49f66f-71e8-4add-aa6d-6809ff981e27.png)

**Comment by mscb402** [comment]
![image](https://user-images.githubusercontent.com/11229089/203906195-60021e4b-99cb-4836-8b46-827c07377cc9.png)
In your case, your curl does not set `origin` header to your request. At Mac and Linux we can using `-H 'Origin: test.com'` to set origin header but Windows may have different behavior. So, please fix that, you should send the request correctly.

**Comment by Drewolf** [comment]
> ![image](https://user-images.githubusercontent.com/11229089/203906195-60021e4b-99cb-4836-8b46-827c07377cc9.png) In your case, your curl does not set `origin` header to your request. At Mac and Linux we can using `-H 'Origin: test.com'` to set origin header but Windows may have different behavior. So, please fix that, you should send the request correctly.

确实是我的windows curl指令返回有问题，在linux上验证正常。

**Comment by Drewolf** [comment]
> I try it on my local env. I know what happened. This is because the cors plugin will match `allow_origins` first, if `allow_origins` does not match then it will try to match it with regex using `allow_origins_by_regex`.
> 
> Therefore when `allow_origins` set as `*`, any URL will matched, so that `allow_origins_by_regex` will not match again.
> 
> So, the right config is below. You can change `http://example.com` to any URL you are NOT using like `http://baidu.com` or `http://xxx.com`. Just make `allow_origins` not match.
> 
> ```json
>  {
>       "allow_credential": false,
>       "allow_headers": "*",
>       "allow_methods": "*",
>       "allow_origins": "http://example.com",
>       "allow_origins_by_regex": [
>         ".*\\.test\\.com",
>         "test\\.com"
>       ],
>       "expose_headers": "*",
>       "max_age": 5
>     }
> ```
> 
> or
> 
> ```json
>  {
>       "allow_credential": false,
>       "allow_headers": "*",
>       "allow_methods": "*",
>       "allow_origins": "http://test.com",
>       "allow_origins_by_regex": [],
>       "expose_headers": "*",
>       "max_age": 5
>     }
> ```

谢谢，确实是这个原因，问题已经解决了。

另外，apisix-dashboard 上的帮助说明有问题，容易误导用户。可以修改一下
![image](https://user-images.githubusercontent.com/30138193/203917924-3d0cae96-e9bc-4459-8707-7915c923bc4a.png)

**Comment by mscb402** [comment]
> > I try it on my local env. I know what happened. This is because the cors plugin will match `allow_origins` first, if `allow_origins` does not match then it will try to match it with regex using `allow_origins_by_regex`.
> > Therefore when `allow_origins` set as `*`, any URL will matched, so that `allow_origins_by_regex` will not match again.
> > So, the right config is below. You can change `http://example.com` to any URL you are NOT using like `http://baidu.com` or `http://xxx.com`. Just make `allow_origins` not match.
> > ```json
> >  {
> >       "allow_credential": false,
> >       "allow_headers": "*",
> >       "allow_methods": "*",
> >       "allow_origins": "http://example.com",
> >       "allow_origins_by_regex": [
> >         ".*\\.test\\.com",
> >         "test\\.com"
> >       ],
> >       "expose_headers": "*",
> >       "max_age": 5
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or
> > ```json
> >  {
> >       "allow_credential": false,
> >       "allow_headers": "*",
> >       "allow_methods": "*",
> >       "allow_origins": "http://test.com",
> >       "allow_origins_by_regex": [],
> >       "expose_headers": "*",
> >       "max_age": 5
> >     }
> > ```
> 
> 谢谢，确实是这个原因，问题已经解决了。
> 
> 另外，apisix-dashboard 上的帮助说明有问题，容易误导用户。可以修改一下 ![image](https://user-images.githubusercontent.com/30138193/203917924-3d0cae96-e9bc-4459-8707-7915c923bc4a.png)

Ok, I'm opening a new issue for this. Thanks for your support for Apisix
