### ISSUE TITLE
help request: how to redirect HTTP to HTTPs?

### ISSUE THREAD

**Issue by Drewolf** [apache/apisix#8405]
### Description

你好，我通过apisix-dashboard配置重定向，想实现 http 强制 跳转 https。发现跳转过后的https地址和我实际浏览器请求的地址不一致，如何配置才能不改变我的请求地址。
![image](https://user-images.githubusercontent.com/30138193/203936516-acd8589e-024c-477d-b8c6-9064726c59ee.png)

![image](https://user-images.githubusercontent.com/30138193/203936721-77e6183a-52b4-4102-aae7-6268b0d0498f.png)

我请求的地址是 http://nginx.qa.xgimi.com/neo/voice/1.html 
强制跳转过后的地址是 https://nginx.qa.xgimi.com:9443/neo/voice/1.html

### Environment

- APISIX version (run `apisix version`): 2.15.0-alpine
- Operating system (run `uname -a`): helm 部署
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4-debian-11-r14
- APISIX Dashboard version, if relevant: 2.13-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@Drewolf https://nginx.qa.xgimi.com:9443/neo/voice/1.html is your target address?

**Comment by tokers** [comment]
@Drewolf Your Layer-4 proxy should take the `X-Forwarded-Port`, or APISIX will use the server port that accepts the request.

**Comment by Drewolf** [comment]
> @Drewolf Your Layer-4 proxy should take the `X-Forwarded-Port`, or APISIX will use the server port that accepts the request.

X-Forwarded-Port 不是7层负载均衡(LB)才能配置的吗？我用的华为云，在负载均衡上没找到配置这个的地方

**Comment by juzhiyuan** [comment]
> 我请求的地址是 http://nginx.qa.xgimi.com/neo/voice/1.html
> 强制跳转过后的地址是 https://nginx.qa.xgimi.com:9443/neo/voice/1.html

Hi @Drewolf, to confirm: your question is, "why the URL ends with `9443`"? 

9443 is used by APISIX as the default HTTPS Listening Port, maybe that's the reason?

**Comment by Drewolf** [comment]
> 

 我猜测也是这个原因，9443是APISIX的https端口。但是我应该怎么配置，才能达到我的预期呢？
http://nginx.qa.xgimi.com/neo/voice/1.html 强制跳转到 https://nginx.qa.xgimi.com/neo/voice/1.html， 而不是https://nginx.qa.xgimi.com:9443/neo/voice/1.html

**Comment by Drewolf** [comment]
> 

请问应该如何配置，才能达到我的预期效果呢？

**Comment by Drewolf** [comment]
> > 我请求的地址是 http://nginx.qa.xgimi.com/neo/voice/1.html
> > 强制跳转过后的地址是 https://nginx.qa.xgimi.com:9443/neo/voice/1.html
> 
> Hi @Drewolf, to confirm: your question is, "why the URL ends with `9443`"?
> 
> 9443 is used by APISIX as the default HTTPS Listening Port, maybe that's the reason?

请问应该如何配置i，才能达到我的预期效果呢？

**Comment by tokers** [comment]
I think the redirect plugin cannot handle this scenario right now, there is a hack way for this: adding the serverless plugin, handling the Location header in the header_filter phase by yourself.

**Comment by Drewolf** [comment]
> phase

官网这部分写的比较简略，能否发一下具体的配置示例？谢谢

**Comment by tokers** [comment]
@Drewolf Sorry, APISIX already support configuring a port for this case:

> When enabling http_to_https, the ports in the redirect URL will pick a value in the following order (in descending order of priority)
Read plugin_attr.redirect.https_port from the configuration file (conf/config.yaml).
If apisix.ssl is enabled, read apisix.ssl.listen and select a port randomly from it.
Use 443 as the default https port.

See https://apisix.apache.org/docs/apisix/plugins/redirect/

**Comment by Drewolf** [comment]
> @Drewolf Sorry, APISIX already support configuring a port for this case:
> 
> > When enabling http_to_https, the ports in the redirect URL will pick a value in the following order (in descending order of priority)
> > Read plugin_attr.redirect.https_port from the configuration file (conf/config.yaml).
> > If apisix.ssl is enabled, read apisix.ssl.listen and select a port randomly from it.
> > Use 443 as the default https port.
> 
> See https://apisix.apache.org/docs/apisix/plugins/redirect/

我大概明白您的意思了，但是我在 apisix-dashboard 上没找到配置 https_port 的地方，请问在哪里配置呢？
![image](https://user-images.githubusercontent.com/30138193/204173856-5d16526e-adf8-4997-a636-af6acec2d3b4.png)

**Comment by tokers** [comment]
@Drewolf The `plugin_attrs` should be configured on the APISIX side. See https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L494.

**Comment by Drewolf** [comment]
> @Drewolf The `plugin_attrs` should be configured on the APISIX side. See https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L494.

谢谢，我通过修改chart中的ssl端口解决了我的问题。
![企业微信截图_16696096219465](https://user-images.githubusercontent.com/30138193/204514259-1821317b-90ce-4e92-8f5c-a7630f8b2edf.png)
