### ISSUE TITLE
help request: Add Jwt-Plugin Return 400 Request Header Or Cookie Too Large

### ISSUE THREAD

**Issue by huanghuanghui** [apache/apisix#8406]
### Description

I use [[apisix-docker](https://github.com/apache/apisix-docker)](https://github.com/apache/apisix-docker)  docker-compose run apisix server,when i try to add  `jwt-auth `,use this introduction  [[apisix-2.4-zh-plugins-jwt-auth](https://www.bookstack.cn/read/apisix-2.4-zh/plugins-jwt-auth.md)](https://www.bookstack.cn/read/apisix-2.4-zh/plugins-jwt-auth.md). I curl this request `/apisix/plugin/jwt/sign` to get Authorization Key,Apisix response
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/32832946/203944935-2f9e5a9c-3934-489f-8141-a7061875f3dc.png">

- this is my consumer configuraion:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32832946/203945343-8a2f98da-d13b-498c-98b2-cb9e2de05b6c.png">

- my route configuration:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/32832946/203945550-bbb5768e-bdb5-400a-b24e-d42578770f86.png">

### Environment

- APISIX version (run `apisix version`):
<img width="906" alt="image" src="https://user-images.githubusercontent.com/32832946/203945781-b42a4ef4-405c-4775-9fd7-cdcf090a08f8.png">

- Operating system (run `uname -a`):
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/32832946/203945841-f4b9cc48-155f-488c-be28-825084aa630d.png">

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/32832946/203946098-4c3c7c7f-33e9-45a7-bfe4-936ca8f26d1f.png">

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
<img width="623" alt="image" src="https://user-images.githubusercontent.com/32832946/203946386-acd434a4-6372-4a44-815d-7a69aba686ab.png">

- APISIX Dashboard version, if relevant:
apache/apisix-dashboard:2.13-alpine
- Plugin runner version, for issues related to plugin runners:

- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
It looks like that your dashboard(2.13) does not match your apisix(3.0.0) , use api instead of dashboard like https://www.bookstack.cn/read/apisix-2.4-zh/plugins-jwt-auth.md

**Comment by NextStation** [comment]
I got the same issue with the jwt-plugin, even though send the request "http://localhost:9080/apisix/plugin/jwt/sign?key=user-key  in the container, the response is "400 Request Header Or Cookie Too Large" , check the access log , 1000 times of token-generate requests are sent in a second, such as
`172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.150 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.150 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.200 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.200 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.239 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.239 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.343 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.343 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.350 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.349 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.389 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.388 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.429 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.429 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.457 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.458 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.474 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.473 "http://172.19.0.63:9080"
172.19.0.1 - - [07/Dec/2022:02:19:45 +0000] 172.19.0.63:9080 "GET /get_token?key=3irGA4et HTTP/1.1" 400 230 0.484 "-" "curl/7.29.0" 2.2.3.6:9080 400 0.484 "http://172.19.0.63:9080"`

**Comment by tzssangglass** [comment]
> 400 Request Header Or Cookie Too Large

try with: https://github.com/apache/apisix/issues/8081#issuecomment-1276959203

**Comment by NextStation** [comment]
这个问题”400 Request Header Or Cookie Too Large“ 总是会出现再搭建apisix集群的时候。
通过docker-compose拉起2个apisix实例+3个etcd实例，请求jwt token（curl http://127.0.0.1:9080/apisix/plugin/jwt/sign?key=user-key -i）就会报这个400错误。

很明显，仅获取token，抓包并没发现过大的header。
查apisix的access日志，发起curl 指令的时候，每次apisix自动产生了682条请求，很神奇，难以理解。

如果用同样的容器镜像配置拉起单个apisix+etcd+dashboard的时候， token 就可以正常获取。

请问是否有标准的apisix集群 docker-compose.yml文件参考呢

**Comment by monkeyDluffy6017** [comment]
considered resolved
