### ISSUE TITLE
help request: how to get token with casdoor plugin?

### ISSUE THREAD

**Issue by Laniakearr** [apache/apisix#8408]
### Description

Hi,
I am trying to use the Casdoor plugin for CAS purposes, and it works well.
However, in a real application, I want my back-end application to know the client information by receiving tokens.
From what I observe, only a cookies session is sent from the plugin.
May I know if it is possible to send tokens as well?
If so, how to do so?

![a7277b54-b7b7-40dd-b5d7-84e6584b2c3c](https://user-images.githubusercontent.com/73451979/204103720-6f69dc1f-41d6-442c-b97f-b7627505bbb7.png)

### Environment

- APISIX version (run `apisix version`): 2.99.0-debian
- Docker: 20.10.20, build 9fdeb9c
- Plugin runner version, for issues related to plugin runners: casdoor:latest (V1.167.0)

**Comment by Laniakearr** [comment]
Route config:
`{
  "uri": "/anything/*",
  "name": "",
  "methods": [
    "GET"
  ],
  "plugins": {
    "authz-casdoor": {
      "callback_url": "http://<my localhost>:9080/anything/a",
      "client_id": "xxx",
      "client_secret": "xxx",
      "endpoint_addr": "http://1<my localhost>:8000"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.org",
        "port": 80,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "pass_host": "pass"
  },
  "status": 1
}`

**Comment by mscb402** [comment]
I read the code from Casdoor plugin. Look like it only saves access_token to the session. And not provide any method to get it. So maybe this plugin does not support what you want. But you can use openid-connect plugin instead. Casdoor also using OAuth protocol. https://apisix.apache.org/docs/apisix/plugins/openid-connect/

**Comment by monkeyDluffy6017** [comment]
Casdoor has official documentation supporting the apisix integration.
https://casdoor.org/docs/integration/lua/apisix

**Comment by mscb402** [comment]
> https://casdoor.org/docs/integration/lua/apisix

There is openid-connect plugin config from Casdoor

```json
{
    "openid-connect": {
      "client_id": "Client ID",
      "client_secret": "Client secret",
      "discovery": "http://CASDOOR_HOSTNAME/.well-known/openid-configuration",
      "introspection_endpoint_auth_method": "client_secret_basic",
      "logout_path": "/logout",
      "realm": "master",
      "redirect_uri": "http://APISIX_HOSTNAME/REDIRECTWHATYOUWANT",
      "bearer_only": false,
      "set_id_token_header": false,
      "access_token_in_authorization_header": true,
      "set_access_token_header": true,
      "set_userinfo_header": false,
      "realm": "master"
    }
  }
```

**Comment by Laniakearr** [comment]
@monkeyDluffy6017 @mscb402 Thank you very much for your help!
I will try to use the openid-connect plugin, and I will close this issue once it works. :)

**Comment by Laniakearr** [comment]
For those who want to obtain Token as well, remember to set "set_id_token_header" to be true.
`{
    "openid-connect": {
      "client_id": "Client ID",
      "client_secret": "Client secret",
      "discovery": "http://CASDOOR_HOSTNAME/.well-known/openid-configuration",
      "introspection_endpoint_auth_method": "client_secret_basic",
      "logout_path": "/logout",
      "realm": "master",
      "redirect_uri": "http://APISIX_HOSTNAME/REDIRECTWHATYOUWANT",
      "bearer_only": false,
      **"set_id_token_header": true,**
      "access_token_in_authorization_header": true,
      "set_access_token_header": true,
      **"set_userinfo_header": true,**
      "realm": "master"
    }
  }`
Problem solved. Thanks for help :)

**Comment by Laniakearr** [comment]
Another question, are we able to modify the name and the content length of the "X-Access-Token" parameter?

**Comment by monkeyDluffy6017** [comment]
The `X-Access-Token` is returned by the `casdoor`, so why you change the length of `X-Access-Token`.

**Comment by mscb402** [comment]
> Another question, are we able to modify the name and the content length of the "X-Access-Token" parameter?

Nope, You can't change `X-Access-Token` this header to another

**Comment by mscb402** [comment]
Only two options `Authorization` or `X-Access-Token`

**Comment by mscb402** [comment]
If you set `access_token_in_authorization_header=true` token will save in the `Authorization` like `Authorization: Bearer xxxxx`. If you set `access_token_in_authorization_header=false` token will save in the `X-Access-Token` like `X-Access-Token: xxxx`

**Comment by Laniakearr** [comment]
Problem solved thank you!
