### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by maqile** [apache/apisix#8410]
### Description

请教下，apisix 的 k8s 服务发现，跟 apisix ingress 有啥区别

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@maqile Hi  may be you can see https://www.apiseven.com/blog/apisix-ingress-details 🤔

**Comment by maqile** [comment]
两者功能是不是重复

**Comment by Hazel6869** [comment]
> 两者功能是不是重复

The difference is that the way of APISIX ingress is: routing and so on are defined by the way of k8s resource yaml
