### ISSUE TITLE
feat: As a user I want to use limit-count plugin with redis-cluster that support tls/ssl.

### ISSUE THREAD

**Issue by harmseru** [apache/apisix#8413]
### Description

- Apisix limit-count should support redis with tls/ssl setup.

- Here is a thread in [apisix Apache Software Foundation slack](https://the-asf.slack.com/archives/CUC5MN17A/p1669619956867579) which details the flaws/missing features.

**Comment by tao12345666333** [comment]
We can add an option for passing these configurations.
https://github.com/openresty/lua-resty-redis#connect

WDYT? @spacewander

**Comment by tao12345666333** [comment]
```
    local config = {
        ...
        dict_name = "plugin-limit-count-redis-cluster-slot-lock",
        connect_opts = {
         	ssl = true,
                ssl_verify = true,
      ...
      }
   }
```
It can be like above.

thanks @monkeyDluffy6017

**Comment by harmseru** [comment]
Also please enable the ability to disable ssl verification if possible.

**Comment by ronething** [comment]
hi, i will try this, pls assign to me.

**Comment by tao12345666333** [comment]
Thanks @ronething for making it happen.
#8558 has been merged.  It will be introduced in the next version @harmseru
