### ISSUE TITLE
bug: kafka-logger.lua校验与前端不匹配

### ISSUE THREAD

**Issue by lihanghang404** [apache/apisix#8417]
### Current Behavior

kafka-logger插件前端校验必须输入broker_list属性，
![image](https://user-images.githubusercontent.com/91579571/204427709-d0bae6c4-7b87-4bc1-8c5b-d02318d889bd.png)
后端lua脚本校验brokers与broker_list只能同时存在一个
oneOf = {
        { required = {"broker_list", "kafka_topic"},},
        { required = {"brokers", "kafka_topic"},},
    }

### Expected Behavior

去掉前端broker_list的正则校验。因为仅brokers可以输入sasl_config安全验证相关配置。应该尽快弃用broker_list属性。

### Error Logs

 failed to process entries: failed to send data to Kafka topic: not found topic, brokers: {"10.206.67.198":9092}, context: ngx.timer, client: 10.206.65.132, server: 0.0.0.0:9080

### Steps to Reproduce

1. run apisix via the Docker images
2. create a router in dashboard
3. configuring the kafka-logger plugin in dashboard
4. configuring both of 'broker_list' and 'brokers'
5. logger error commit 'should only match 1 scheme'
6. configuring only the 'brokers'
7. commit 'should have required property 'broker_list''  by chrome
8. configuring 'broker_list' only
9. it doesn't work because i can not input 'sals_conf' in this properties 'broker_list'

### Environment

- 3.0.0
- 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- 3.4.5
- 2.13.0
- default
- default

**Comment by spacewander** [comment]
APISIX Dashboard doesn't support APISIX 3.0 yet.

**Comment by lihanghang404** [comment]
AdminAPI is ok.

**Comment by tzssangglass** [comment]
Considered solved, feel free to reopen this if you needed.
