### ISSUE TITLE
docs: suggest to put workflow plugin in "general" category

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#8422]
### Current State

Currently the workflow plugin is in the "serverless" category:
https://github.com/apache/apisix/blob/7926408305c36af1003f76c860a9dd027ab32026/docs/en/latest/config.json#L175-L182

However, the workflow plugin doesn't run user-defined code, and it doesn't integrate with serverless platforms like aws-lambda either.

### Desired State

After discussing with @membphis, we recommend putting the workflow plugin in "general" category, as it is similar to the batch-requests plugin. The workflow plugin allows users to combine multiple actions just like the batch-requests allows users to connect to multiple APIs.

@navendu-pottekkat 
What's your opinion?

**Comment by navendu-pottekkat** [comment]
Currently, the workflow Plugin only does traffic management. But if the "actions" evolve to include other capabilities, then it might be good to add it in the "general" category. Otherwise, a good option is in the "traffic" category.

**Comment by membphis** [comment]
The `workflow` is not only do traffic management things.

So `general` category is better for it.

**Comment by Neilblaze** [comment]
@navendu-pottekkat can you please assign me if this is up for grabs?

**Comment by navendu-pottekkat** [comment]
@Neilblaze Done.
