### ISSUE TITLE
As a user, I want to use my existing cache infrastructure, e.g., Redis

### ISSUE THREAD

**Issue by nfrankel** [apache/apisix#8423]
### Description

Most organizations already manage their own caching infrastructure, e.g., Redis, Hazelcast, etc. They know to operate it and may have (paid) support. With Apache APISIX, they need to use the `proxy-cache` plugin, which only provides disk or memory options.

As a user, I want to use my existing cache infrastructure to reuse all my know-how.

**Comment by tzssangglass** [comment]
Does that mean making proxy-cache support cache base settings like redis?

**Comment by nfrankel** [comment]
@tzssangglass Yes, but not only. Because the next requirement will be to support Hazelcast, etc.

We need to provide an abstraction layer and a sample provider such as Redis. This way, the community can provide their own.

**Comment by tokers** [comment]
Agree +1.

After we have such a layer, it can be used in many places. e.g., used in limit-* plugins, x-logger plugins.

**Comment by nfrankel** [comment]
I think we need an additional abstraction, `Storage` (just like `Consumer`).

We could define different storages, and then plugins could use them, in a many-to-many relationships.

**Comment by tzssangglass** [comment]
> I think we need an additional abstraction, `Storage` (just like `Consumer`).

I think it should be Cache Storage, it can be Redis, memcached and others.

**Comment by nfrankel** [comment]
I stand by `Storage`: I'd like that it can be reused across as many plugins as possible. For example, it could be used in the `limit-count` and replace Redis with any datastore that allows key-value storage.

**Comment by tzssangglass** [comment]
> I'd like that it can be reused across as many plugins as possible.

+1

**Comment by spacewander** [comment]
Look like this feature will turn APISIX into a cache server. I implemented a cache server via Nginx in my previous company, which is not an easy thing to implement. It requires modifying a bundle of Nginx core source, which means it would be a long-term job and need 💰 💰 💰  . Is there any strong demand to support this feature?

**Comment by nfrankel** [comment]
@spacewander I think you misread me: I want Apache APISIX to integrate with storage solutions so we can leverage them.

**Comment by spacewander** [comment]
No. Using Redis or any other Storage to replace the local filesystem in the proxy-cache plugin is in fact making APISIX closer to a cache server.

**Comment by spacewander** [comment]
The main point is not whether it is "cache server" or "integrate with storage solutions". The main point is if it is worth doing this job (💰💰💰 ). If we have an infinite budget, we can provide anything people like. But as we don't have one, we need to consider the ROI.

**Comment by spacewander** [comment]
This is why I seldom say "+1", because I am one of the people who need to think about the budget.

**Comment by spacewander** [comment]
> Look like this feature will turn APISIX into a cache server. I implemented a cache server via Nginx in my previous company, which is not an easy thing to implement. It requires modifying a bundle of Nginx core source, which means it would be a long-term job and need 💰 💰 💰 . Is there any strong demand to support this feature?

To make it clear, a strong demand is something like:
"Several companies want this feature and they are willing to use it in the production once we have implemented it".

**Comment by MilkWangStudio** [comment]
> The main point is not whether it is "cache server" or "integrate with storage solutions". The main point is if it is worth doing this job (💰💰💰 ). If we have an infinite budget, we can provide anything people like. But as we don't have one, we need to consider the ROI.

I think you're right, apisix is a opensource project, it should focus on gateway rather than cache. 

On the other hand, I have a requirement to develop common cache server now. I code a min demo with spring cloud gateway to implement cache server. It has some basic features. like dynamic api config, double cache, cache update strategy etc. 

now the call link is :  client -> apisix(auth) -> cacheServer -> dataApi -> db

I want to develop a apisix-plugin to replace cacheServer. I think the difficulty may be to integrate middleware in apisix.
For example, the memory update is triggered by mq.

Without considering the cost, do you think it's a good idea to implement a better cache-proxy plugin?

**Comment by spacewander** [comment]
> 

APISIX has a memory-based cache-proxy implementation, contributed by the community. This implementation is done in Lua.

However, in our benchmark, the memory-based cache-proxy implementation isn't better than the disk implementation, see https://github.com/apache/apisix/pull/5028#issuecomment-931453714. Even based on the memory, a pure Lua implementation isn't faster than the disk-based C implementation.

So if you think a better cache-proxy plugin should work better than squid server or Apache Traffic server, you need to write it as an Nginx C module. In my previous Job in a CDN company, I wrote a cluster-level cache server based on Nginx, which is almost written in C and only exposes some Lua API for configuration.

**Comment by spacewander** [comment]
On the other hand, if your case is not complex, for example, caching KB-level responses in a Memcache server, a pure Lua implementation may be already enough.

The cache server area is complex. It really depends on the size that you need to cache and where you want to put the cache in.

**Comment by MilkWangStudio** [comment]
> On the other hand, if your case is not complex, for example, caching KB-level responses in a Memcache server, a pure Lua implementation may be already enough.
> 
> The cache server area is complex. It really depends on the size that you need to cache and where you want to put the cache in.

Thanks your suggests, It's very enlightening for me.
