### ISSUE TITLE
Unified apisix/core/vault.lua and apisix/secret/vault.lua

### ISSUE THREAD

**Issue by soulbird** [apache/apisix#8424]
### Description

`apisix/secret/vault.lua` was introduced in https://github.com/apache/apisix/pull/8412.

Functions currently in [apisix/secret/vault.lua](https://github.com/apache/apisix/blob/master/apisix/secret/vault.lua) are copied from [apisix/core/vault.lua](https://github.com/apache/apisix/blob/master/apisix/core/vault.lua).

The functions in `apisix/core/vault.lua` are only used in the `jwt-auth` plugin to save the jwt key, so it is not appropriate to put vault-related functions in the core module. We need to unify them.

The kms component has more comprehensive key management functions and is more versatile, so we should make the following adjustments:

1. Use the vault function provided by the kms component to replace the vault-related functions in the jwt-auth plugin. This will introduce a break change due to changes in configuration.
2. Delete the `apisix/core/vault.lua` file.

**Comment by shreemaan-abhishek** [comment]
To be noted: `apisix/admin/kms.lua` has been renamed to s`apisix/admin/secrets.lua`. Ref: PR #8448
