### ISSUE TITLE
help request: kafka-logger的brokers.sasl_configmechanism.

### ISSUE THREAD

**Issue by lihanghang404** [apache/apisix#8427]
### Description

3.0.0版本源码中，kafka-logger的brokers.sasl_config.mechanism只支持PLAIN一种格式如图：
![image](https://user-images.githubusercontent.com/91579571/204698084-1393d1fd-0058-4f8c-b63f-51a210cc5997.png)
kafka服务端报错信息如下：
![img_v2_ac236e72-9b25-4305-8ff5-58abf703e24g](https://user-images.githubusercontent.com/91579571/204698126-c2624d7d-0a7a-4fba-bcd6-b7a3bfd3d04a.jpg)
现在需要支持SCRAM-SHA-256或者SCRAM-SHA-512格式

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): centos7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): default
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant: 2.13.1
- Plugin runner version, for issues related to plugin runners:default
- LuaRocks version, for installation issues (run `luarocks --version`):default

**Comment by tzssangglass** [comment]
In the kafka plugin dependency `lua-resty-kafka`, `SCRAM-SHA-256` is still in TODO state, ref: https://github.com/doujiang24/lua-resty-kafka/blob/master/lib/resty/kafka/sasl.lua#L4

You can contribute to lua-resty-kafka first to support `SCRAM-SHA-256` if you need to.
