### ISSUE TITLE
more ssl certificate in etcd

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8428]
### Description

in etcd use the ssl certificate to proxy requests, if more ssl certificate in etcd is the same sni, if one certificate is expired,the other is good,then apisix will use the good or random to get ssl certificate?

this is good certificate:
{
    "id": "1",           # id
    "cert": "new cert",      # Certificate
    "key": "new key",        # Private key
    "snis": ["t.com"]    # https SNI
}

this is the expired certificate:
{
    "id": "2",           # id
    "cert": "expired cert",      # Certificate
    "key": "expired key",        # Private key
    "snis": ["t.com"]    # https SNI
}

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@kellyseeme Currently, not.

**Comment by kellyseeme** [comment]
tks
