### ISSUE TITLE
metrics without apisix_http_status 

### ISSUE THREAD

**Issue by wood-zhang** [apache/apisix#8429]
### Description

here is my metrics returned by prometheus, no apisix_bandwidth,apisix_batch_process_entries, apisix_http_status,apisix_http_latency_bucket
![image](https://user-images.githubusercontent.com/62324191/204727980-8ac74337-6ab6-4812-b67c-19138b2e942b.png)

here is my chart configure
![image](https://user-images.githubusercontent.com/62324191/204728504-918e594e-a102-42c1-a760-2f8cd507fb09.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by wood-zhang** [comment]
我发现没有在全局路由里启用prometheus，已解决，谢谢

**Comment by jackk01** [comment]
> 我发现没有在全局路由里启用prometheus，已解决，谢谢

是 dashboard 上的 插件--启动--可观测性--prometheus 吗？我启用了也没用这几个指标

**Comment by tzssangglass** [comment]
> 是 dashboard 上的 插件--启动--可观测性--prometheus 吗？我启用了也没用这几个指标

You need to send some requests and hit the route/service with the prometheus plugin turned on.

**Comment by panhow** [comment]
这个 extra_labels 是自己实现的feature吗？看着原生的没有

**Comment by tzssangglass** [comment]
> 这个 extra_labels 是自己实现的feature吗？看着原生的没有

https://github.com/apache/apisix/blob/8b14c68840a9fd1bae6718a57f158cc117a12acf/docs/en/latest/plugins/prometheus.md#specifying-metrics

support form APISIX v3.0.0

**Comment by panhow** [comment]
> 

thx, i am still using `v2.15`

**Comment by panhow** [comment]
> > 这个 extra_labels 是自己实现的feature吗？看着原生的没有
> 
> https://github.com/apache/apisix/blob/8b14c68840a9fd1bae6718a57f158cc117a12acf/docs/en/latest/plugins/prometheus.md#specifying-metrics
> 
> support form APISIX v3.0.0

thx, i will check it

**Comment by QuanTran91** [comment]
> > > 这个 extra_labels 是自己实现的feature吗？看着原生的没有
> > 
> > 
> > https://github.com/apache/apisix/blob/8b14c68840a9fd1bae6718a57f158cc117a12acf/docs/en/latest/plugins/prometheus.md#specifying-metrics
> > support form APISIX v3.0.0
> 
> thx, i will check it

How is it going? Did it work?
