### ISSUE TITLE
bug: for mac making deps,pcre header file cannot be found

### ISSUE THREAD

**Issue by drgnchan** [apache/apisix#8432]
### Current Behavior

after executing `make deps` on my mac m1 chip version,terminal showed the result below.
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/40224023/204767197-f0fed9be-a73a-43d4-b25c-79d8f76144e1.png">

And I have installed the pcre by homebrew before `make deps`.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/40224023/204767436-caefe7ae-9992-45e7-a4ee-f34995cadd01.png">

### Expected Behavior

luarocks can find the header file `pcre.h`.

### Steps to Reproduce

1. Run `make deps`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`): Darwin raymondMacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
LGTM.

the branch has been tested at a M2 Mac.
