### ISSUE TITLE
feat: Upstream status page

### ISSUE THREAD

**Issue by bhedahra** [apache/apisix#8441]
### Description

Hello 

As a user, I want to see upstream statuses like nginx or tengine, could you please help?

For example, i can see upstreams up or down in nginx like that

Index | Upstream |            Name |          Status | Rise counts | Fall counts | Check type | Check port
0 | upstream-name | upstreamip-port | up | 10 |  0 | tcp | 0

**Comment by membphis** [comment]
Can you post a picture to show the final result? @bhedahra

**Comment by bhedahra** [comment]
Hello, for example; this is tengine upstream status page. This is enough for us. Thanks.

![image](https://user-images.githubusercontent.com/95253933/205057893-734590e8-61dc-4437-ae0e-a1fac63e2fe7.png)

**Comment by tokers** [comment]
APISIX has the health check control API for collecting this health information, see https://apisix.apache.org/docs/apisix/control-api/#get-v1healthcheck for the details and learn if these information is what you need.

**Comment by juzhiyuan** [comment]
This endpoint returns empty, according to @bhedahra's slack chat. @bhedahra Please provide steps and more information on this "issue". Then, the team will try to explore and reproduce it.

**Comment by tzssangglass** [comment]
we can get upstream status by the prometheus plugin, ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md#specifying-metrics

**Comment by tokers** [comment]
> we can get upstream status by the prometheus plugin, ref: https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md#specifying-metrics

The metrics got from the real traffic, and the image provided @bhedahra is gotten from the something like health check. Not sure if this is what @bhedahra needs.

**Comment by cardiyu** [comment]
+1，maybe refer to aliyun slb openapi for healthcheck，ref：
https://next.api.aliyun.com/document/Slb/2014-05-15/DescribeHealthStatus

{
  "RequestId": "365F4154-92F6-4AE4-92F8-7FF34B540710",
  "BackendServers": [
    {
      "ServerHealthStatus": "abnormal",
      "Protocol": "https",
      "ListenerPort": 80,
      "ServerIp": "192.XX.XX.11",
      "Port": 70,
      "ServerId": "i-bp1h5u3fv54ytf***"
    }
  ]
}
