### ISSUE TITLE
bug: The BUG that was created when the response header was modified using the plugin

### ISSUE THREAD

**Issue by rampagecong** [apache/apisix#8463]
### Current Behavior

I mentioned two PR in the first half of the year about customizing and modifying the response header in apisix-go-plugin-runner, but recently I found some problems.

I called 'r.R.header ().Add("Set-Cookie", v)' in a browser with a runner,

But the same key in the corresponding Set-Cookie was found in another traceless browser with the same value.

My idea is that the 'core.response.set_header' in ext-plugin/init.lua in apisix will modify the 'Set-Cookie 'of the entire apisix response header.

The effect I want is to modify the response header only in the current browser, and not in any other browser.

 Code View:
https://github.dev/apache/apisix/blob/edb8edfd42943c1e112b259f1c1c29bd41136512/apisix/plugins/ext-plugin/init.lua#L658-L673

### Expected Behavior

The response header was modified in runner to only apply to the current browser, rather than all browsers being executed.

### Error Logs

runner and apisix execute normally, with no error log and only a problem with the expected effect.

### Steps to Reproduce

1.Making the runner plugin.
2.Configure routes and plugins on the dashboard.
3.Invoke the configured route in the browser
4.Open two unrelated browsers, one browser accesses the configured route, and the Set-Cookie is modified. Refresh another browser Set-Cookie has been changed to the same value.

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):Linux rampagecongtest 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.15
- APISIX Dashboard version, if relevant:2.13.0
- Plugin runner version, for issues related to plugin runners:apisix-go-plugin-runner

**Comment by tzssangglass** [comment]
> I called 'r.R.header ().Add("Set-Cookie", v)' in a browser with a runner,

I think you should be careful with `("Set-Cookie", v)`, here is how to modify the response cookie in APISIX: https://github.com/apache/apisix/blob/master/apisix/plugins/cas-auth.lua#L64-L66

As you can see, only the cookie with a specific name will be modified here.

**Comment by rampagecong** [comment]
> > I called 'r.R.header ().Add("Set-Cookie", v)' in a browser with a runner,
> 
> I think you should be careful with `("Set-Cookie", v)`, here is how to modify the response cookie in APISIX:
> 
> https://github.com/apache/apisix/blob/1da09bf4442e2a2cafd309ecd6297551342a4cb8/apisix/plugins/cas-auth.lua#L64-L66
> 
> As you can see, only the cookie with a specific name will be modified here.

I see.

https://github.dev/apache/apisix/blob/edb8edfd42943c1e112b259f1c1c29bd41136512/apisix/plugins/ext-plugin/init.lua#L658-L673

This is the code that I brought up PR to modify the response header.

The use of set-cookie in core.response.add_header will affect both the current browser and the cookie in the browser accessing the route. I think it should not be so. Should be a cookie that only affects the currently accessed browser.

**Comment by tzssangglass** [comment]
> [github.dev/apache/apisix/blob/edb8edfd42943c1e112b259f1c1c29bd41136512/apisix/plugins/ext-plugin/init.lua#L658-L673](https://github.dev/apache/apisix/blob/edb8edfd42943c1e112b259f1c1c29bd41136512/apisix/plugins/ext-plugin/init.lua#L658-L673)
> 
> This is the code that I brought up PR to modify the response header.

Have you tried `Set-Cookie", name ... "=" ... val ... COOKIE_PARAMS` also cause the phenomenon you describe?

**Comment by tzssangglass** [comment]
> I think it's the same if you use it this way.


Then I think this has nothing to do with ext-plugin, but with the scope of influence caused by setting cookies in APISIX.

**Comment by rampagecong** [comment]
> > I think it's the same if you use it this way.
> 
> Then I think this has nothing to do with ext-plugin, but with the scope of influence caused by setting cookies in APISIX.

Yeah, that's why I brought it up. See if the developers can come up with better suggestions.

**Comment by rampagecong** [comment]
@spacewander Please have a look at the above problems, can you provide a solution?

https://github.dev/apache/apisix/blob/edb8edfd42943c1e112b259f1c1c29bd41136512/apisix/core/response.lua#L100-L132

**Comment by rampagecong** [comment]
I found the problem.There was a BUG in the PR I submitted earlier for 'apisix-go-plugin-runner'.
https://github.dev/apache/apisix-go-plugin-runner/blob/ccd171d45d59ec252e200672145d483f1661abf1/internal/http/request.go#L192-L205
**r.respHdr = nil**
Looks like someone already found it.
