### ISSUE TITLE
How to route to different grpc service by path?

### ISSUE THREAD

**Issue by FlyTOmeLight** [apache/apisix#8464]
### Description

I have a question that about routing to grpc service.
I want to be able to distinguish different grpc services by different path prefixes.
I run failed on ingress-nginx
I wonder if apisix has some solution or maybe it out of reach,I've also seen the grpc-web design, but that's not the way I want it

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1

**Comment by tokers** [comment]
Not so clear for your case. Do you want a grpc proxy or translating http to grpc or vice versa.

If you want a proxy, if you know the way grpc concatenates service and methods to a URI path, then you know how to write apisix routes.

**Comment by zbh0323** [comment]
> Not so clear for your case. Do you want a grpc proxy or translating http to grpc or vice versa.
> 
> If you want a proxy, if you know the way grpc concatenates service and methods to a URI path, then you know how to write apisix routes.

Just like this


grpc:
  - name: grpc
    priority: 3
    match:
      paths:
        - /{{ .Release.Name }}/grpc/*
    backends:
      - serviceName: {{ .Release.Name }}
        servicePort: grpc
    plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/{{ .Release.Name }}/grpc/(.*)", "/$1"]
