### ISSUE TITLE
how to set the client ip to upstream server

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8468]
### Description

when i use the stream_proxy,TLS over TCP connection,the upstream all is the apisix ip address,how to transport the client real ip to upstream server?

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/discussions/8124#discussioncomment-3942200

Try the nginx directive proxy_bind. It may help you.

**Comment by kellyseeme** [comment]
maybe not the same,i want to use the  proxy_protocol,but  can't find to set ,but not affect:
  enable_tcp_pp: true
  enable_tcp_pp_to_upstream: true

**Comment by tzssangglass** [comment]
> enable_tcp_pp: true
> enable_tcp_pp_to_upstream: true

what is the full configuration?

**Comment by tzssangglass** [comment]
from https://github.com/apache/apisix/blob/5822eca9a28ff7b92dc7fc0431281eb62dd60ba8/apisix/cli/ngx_tpl.lua#L208-L210

I think I think the indentation is wrong here https://github.com/apache/apisix/blob/5822eca9a28ff7b92dc7fc0431281eb62dd60ba8/conf/config-default.yaml#L37-L44

it should be:

```yaml
  #proxy_protocol:                  # Proxy Protocol configuration
    #listen_http_port: 9181           # The port with proxy protocol for http, it differs from node_listen and admin_listen.
                                    # This port can only receive http request with proxy protocol, but node_listen & admin_listen
                                    # can only receive http request. If you enable proxy protocol, you must use this port to
                                    # receive http request with proxy protocol
    #listen_https_port: 9182          # The port with proxy protocol for https
    #enable_tcp_pp: true              # Enable the proxy protocol for tcp proxy, it works for stream_proxy.tcp option
    #enable_tcp_pp_to_upstream: true  # Enables the proxy protocol to the upstream server
```

cc @spacewander

**Comment by spacewander** [comment]
This is an indent error in the comment.

@tzssangglass 
Would you submit a PR to fix it? Thanks!

**Comment by tzssangglass** [comment]
> maybe not the same,i want to use the proxy_protocol,but can't find to set ,but not affect:

According to your description, proxy_bind is what you need.

**Comment by shreemaan-abhishek** [comment]
@kellyseeme is your query resolved? Can we close this now?
