### ISSUE TITLE
feat: As a user, I want to use RPM to install apisix

### ISSUE THREAD

**Issue by zhendongcmss** [apache/apisix#8473]
### Description

Before APISIX provider RPM, why doesn't provider it now ?

**Comment by tzssangglass** [comment]
we support rpm, https://apisix.apache.org/docs/apisix/installation-guide/

You can't get the rpm?

**Comment by zhendongcmss** [comment]
Why we doesn't attach the RPM on Github release ?

**Comment by love52** [comment]
If rpm installation is used, dubbo proxy cannot be used？

OR，
If you want to use apisix's http to dubbo protocol in a non-Docker environment,   Do I have to compile openRestry to add dubbo_model and apisix is then compiled from the openRestry again ？

**Comment by juzhiyuan** [comment]
> If i want to use apisix's http to dubbo protocol in a non-Docker environment, Do I have to compile openRestry to add dubbo_model and apisix is then compiled from the openRestry again ？

Hi @bzp2010 👋 Take Dubbo as an example, if we want to use it, I have thought two ways:

1. Use APISIX Base in bare metal, and compile it to APISIX.
2. Use docker

If using RPM, how to use Dubbo then? Can you please give some hints?

**Comment by monkeyDluffy6017** [comment]
considerer resolved
