### ISSUE TITLE
关于apisix双向认证的功能

### ISSUE THREAD

**Issue by feichenxue** [apache/apisix#8474]
### Description

有点类似于配置nginx开启客户端认证的配置
这里只列出server段的关键部分：
ssl_certificate /etc/pki/ca_linvo/server/server.crt;#server公钥
ssl_certificate_key /etc/pki/ca_linvo/server/server.key;#server私钥
ssl_client_certificate /etc/pki/ca_linvo/root/ca.crt;#根级证书公钥，用于验证各个二级client
ssl_verify_client on;

我看了apisix文档好像没有这一方面的配置！

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/blob/master/docs/zh/latest/mtls.md

https://github.com/apache/apisix/blob/master/docs/zh/latest/certificate.md#%E8%AE%BE%E7%BD%AE%E5%A4%9A%E4%B8%AA-ca-%E8%AF%81%E4%B9%A6

**Comment by juzhiyuan** [comment]
Hi @feichenxue, there also has one tutorial: https://apisix.apache.org/docs/apisix/next/tutorials/client-to-apisix-mtls/

Does it meet your needs? If yes, please close this issue :)

**Comment by wangyp0701** [comment]
After configuring the ca certificate, you can access it, but you can't control the required CN. The download is that all the issued ca certificates can be authenticated successfully.

![1675662193240](https://user-images.githubusercontent.com/33682005/216892729-49dcad87-524f-474a-b84c-29c15d0f0d8c.png)
![1675662218650](https://user-images.githubusercontent.com/33682005/216892790-c479fb37-22c2-408c-8d2b-d39f75a86119.png)

Is there any way to realize the release according to CN

**Comment by feichenxue** [comment]
Thanks for everyone's help！
