### ISSUE TITLE
use http to https is not affect

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8483]
### Description

i set two route :
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f134336f236f87ad84b625c9f1' -X PUT -d '{
  "uri": "/*",
  "name": "back",
  "upstream_id": "mybackend",
  "status": 1,
  "host": "*.backend.com"
}'

curl http://127.0.0.1:9180/apisix/admin/routes/httptohttps -H 'X-API-KEY: edd1c9f134336f236f87ad84b625c9f1' -X PUT -d '{
    "uri": "/*",
    "plugins": {
        "redirect": {
            "http_to_https": true
        }
    }
}'

in test,the request of http not redirect to https,the second route is not affected. how can i change the route?

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kellyseeme** [comment]
if i change the routes name,then the https is not affected,error log is :
[error] 19072#19072: *7957 [lua] init.lua:540: http_access_phase(): failed to set upstream: missing upstream configuration in Route or Service, client
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f134336f236f87ad84b625c9f1' -X PUT -d '{
"uri": "/*",
"plugins": {
"redirect": {
"http_to_https": true
}
}
}'

curl http://127.0.0.1:9180/apisix/admin/routes/httptohttps -H 'X-API-KEY: edd1c9f134336f236f87ad84b625c9f1' -X PUT -d '{
"uri": "/",
"name": "back",
"upstream_id": "mybackend",
"status": 1,
"host": ".backend.com"

}'

**Comment by kellyseeme** [comment]
if i use the vars ,http will directly return the result,not redirect to https
"vars": [
        [
            "scheme",
            "==",
            "http"
        ]
    ],
    "plugins": {
        "redirect": {
            "uri": "https://$host$request_uri",
            "ret_code": 301
        }
    }

**Comment by kellyseeme** [comment]
i find this is work ,use one rules:
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034331f236ff7ad84b625c8f1' -X PUT -d '{
    "uri": "/*",
    "host": "*.backend.com",
    "upstream_id": "backend",
    "plugins": {
        "redirect": {
            "http_to_https": true
        }
    }
}'
if the shema is https,this plugin is no effect?

**Comment by tzssangglass** [comment]
I didn't understand what you wanted to do.

> if the shema is https,this plugin is no effect?

yes, we have code like:

```
    local _scheme = proxy_proto or core.request.get_scheme(ctx)
    if conf.http_to_https and _scheme == "http" then
```
