### ISSUE TITLE
bug: can't public control api 

### ISSUE THREAD

**Issue by juzn01** [apache/apisix#8484]
### Current Behavior

i have apisix 3.0 and i want enable control api public to "0.0.0.0" in config.yaml file but it don't work:
enable_control: true
control:
ip: "0.0.0.0"
port: 9090

curl http://127.0.0.1:9090/v1/healthcheck >> OK
curl http://apisix-ip:9090/v1/healthcheck >> not OK
Please help me! Thanks!

### Steps to Reproduce

instal apisix 3.0 on redhat 7.9 by rpm
start apisix:
systemctl start apisix
change conf/config.yaml file:

enable_control: true
control:
ip: "0.0.0.0"
port: 9090

restart apisix:
systemctl restart apisix

### Environment

- APISIX version (run `apisix version`):3.0
- Operating system (run `uname -a`): redhat 7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0

**Comment by mscb402** [comment]
Can you share `netstat -tulpn`?

**Comment by tokers** [comment]
Not sure if this is due to the `0.0.0.0` format, could you try to configure the `ip` field to `*`?

**Comment by mscb402** [comment]
> > Can you share `netstat -tulpn` output for us?
> 
> ![image](https://user-images.githubusercontent.com/28623637/207011805-bc70d556-3c55-4ded-b6a3-a990314051a7.png)
> 
> yes

Look like there don't have 0.0.0.0:9090

**Comment by mscb402** [comment]
can you post all your config.yaml content to us?

**Comment by juzn01** [comment]
> can you post all your config.yaml content to us?

![image](https://user-images.githubusercontent.com/28623637/207014524-ded70d1d-c9c4-4d65-8868-98fe15d2dad1.png)
this is config in config.yaml.

**Comment by mscb402** [comment]
Maby you need put control block to apisix block,like this
```
apisix:
  enable_control: true
  control:
    ip: "127.0.0.1"
    port: 9090
```

**Comment by mscb402** [comment]
please, try is config. And share all your config for us not just fragment

**Comment by juzn01** [comment]
> please, try is config. And share all your config for us not just fragment

It is my all config bro.
![image](https://user-images.githubusercontent.com/28623637/207016947-0f8b74e9-a739-4918-869a-c7598b1d21ea.png)

**Comment by juzn01** [comment]
> Maby you need put control block to apisix block,like this
> 
> ```
> apisix:
>   enable_control: true
>   control:
>     ip: "0.0.0.0"
>     port: 9090
> ```

oki let me try it

**Comment by juzn01** [comment]
> OK, I see it. Please change the config and try it. It is work for you now?

ah oki ,it is work now thanks you.

**Comment by mscb402** [comment]
its glad to help you, you can close this issue now

**Comment by juzn01** [comment]
i open new issue relate to reponse rewrite, please help me.
https://github.com/apache/apisix/issues/8501
