### ISSUE TITLE
The apisix plugin truncates the response BUG

### ISSUE THREAD

**Issue by savingrun** [apache/apisix#8486]
### Description

APISIX: 2.15.1
java-plugin-runner: 0.4.0
When we use the `ext-plugin-post-resp` plug-in, when the request interface is enabled, when the data is relatively large, the response body is truncated and the return is incomplete

log:
```shell
6690#6690: *6385 [lua] ext-plugin-post-resp.lua:164: phase_func(): output response failed: nginx output filter error
```

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`): Linux apisix-debug-10165 5.4.217-1.el7.elrepo.x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners: java-plugin-runner-version v0.4.0
- LuaRocks version, for installation issues (run `luarocks --version`): /usr/local/bin/luarocks 3.8.0

**Comment by tokers** [comment]
I think this is an inherent limitation in APISIX. We lacks the doc to explain it.

**Comment by suhli** [comment]
> I think this is an inherent limitation in APISIX. We lacks the doc to explain it.

limit about what?openresty?

**Comment by spacewander** [comment]
It's usually caused by the Nginx side. Is there any more relative error log?

**Comment by yunduansing** [comment]
Maybe this problem is like `https://github.com/apache/apisix-go-plugin-runner/issues/114`
