### ISSUE TITLE
help request: real-ip plugin enable problem

### ISSUE THREAD

**Issue by ynsdl** [apache/apisix#8488]
### Description

I am trying to enable real-ip plugin to override remote_addr with http_x_forwarded_for to get real client ip.

When ı add to my json from apisix dashboard, it returns to me "invalid plugin data".

![Screen Shot 2022-12-08 at 22 06 33](https://user-images.githubusercontent.com/46422366/206549554-0bd22495-0a23-498f-8875-b5c438204a45.png)

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): Linux apisix01 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
you may use

```json
{
  "source": "arg_realip",
  "trusted_addresses": ["127.0.0.0/24"]
}
```

**Comment by ynsdl** [comment]
same error. 

<img width="1011" alt="Screen Shot 2022-12-09 at 09 53 59" src="https://user-images.githubusercontent.com/46422366/206643239-278b829f-7bea-4aef-8bde-f062b50d7eb1.png">

**Comment by ronething** [comment]
> same error.
> 
> <img alt="Screen Shot 2022-12-09 at 09 53 59" width="1011" src="https://user-images.githubusercontent.com/46422366/206643239-278b829f-7bea-4aef-8bde-f062b50d7eb1.png">

i mean the raw data is

<img width="406" alt="image" src="https://user-images.githubusercontent.com/28869910/206658127-a79add2c-0e88-460c-bed4-4c2ac9c5c9bc.png">

**Comment by ynsdl** [comment]
OK. I added source not only "http_x_forwarded_for" but also "arg_realip" but I can see client ip on my application server

my structure is internet --> nginx ---> apisix ---> jboss

I can see client ip on nginx;

x.x.com | **remoteAddr::8.6.2.2** | upstreamAddr::10.3.1.1:9080 | [09/Dec/2022:12:26:11 +0000] | request:POST  HTTP/2.0 | httpStatus::200 | bytesSent::0| apiKey::- | reqTime::0.001 | upsRespTime::0.001 | upsConnTime::0.000 | upsHeaderTime::0.001

apisix log;  nginx remote addr come apisix with http_x_forwarded_for

x.x.com | **xForweededFor::8.6.2.2** | remoteAddr::10.4.2.16 | upstreamAddr::10.34.167.39:8080 | [09/Dec/2022:12:26:12 +0000] | request:POST  HTTP/1.1 | httpStatus::200 | bytesSent::0 | userAgent::okhttp/4.9.0 | appKey::| apiKey::| reqTime::0.001 | upsRespTime::0.000 | upsConnTime::0.000 | upsHeaderTime::0.000

 I cant see http_X_forwarded_for ip addr (8.6.2.2) at Jboss. it writes 10.4.2.16 on jboss log.

**Comment by tzssangglass** [comment]
> I cant see http_X_forwarded_for ip addr (8.6.2.2) at Jboss. it writes 10.4.2.16 on jboss log.

can you get `x-real-ip` ?

**Comment by ynsdl** [comment]
solved
thanks
