### ISSUE TITLE
bug: 使用k8s服务发现功能，出现偶发pod ip不更新情况导致请求到已关闭的pod ip

### ISSUE THREAD

**Issue by chenjinxuan** [apache/apisix#8489]
### Current Behavior

配置文件：    
discovery:
      kubernetes:
        service:
            schema: https
            host: kubernetes.default.svc.cluster.local
            port: "443"  
            
dashboard upstream配置
 {
  "timeout": {
    "connect": 60,
    "send": 60,
    "read": 60
  },
  "type": "roundrobin",
  "scheme": "grpc",
  "discovery_type": "kubernetes",
  "pass_host": "pass",
  "name": "example-service",
  "service_name": "default/example-service:port-9000",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}           

### Error Logs

未发现异常日志，只是当大量deployment同时滚动时，会出现apisix无法更新pod ip情况，最后导致请求到旧的pod ip上

### Steps to Reproduce

无

### Environment

- APISIX version 2.13.3:
- Operating system k8s 1.21

**Comment by tzssangglass** [comment]
I remember that k8s discovery uses a watch mechanism and should be able to sense the latest pod ip. any error logs?

cc @zhixiongdu027

**Comment by chenjinxuan** [comment]
> > 只是当大量deployment同时滚动时，会出现apisix无法更新pod ip情况，最后导致请求到旧的pod ip上
> 
> kubernetes 从 “endpoinst 摘除旧 pod ip” 和 “删除 旧 pod ” 是并行的. 如果 "删除 旧 pod " 先执行完毕, “endpoinst 摘除旧 pod ip” 后执行完, 那问题就不可避免了. 这里的最佳实践是 定制 pod 的 preStop , 并且在 “preStop” 中 "sleep" 一段时间 .
> 
> 如果你怀疑是延迟导致的, 那么可以考虑三个方面:
> 
> * pod 的变动反应到 endpoints 中的延迟
> * endpoints 的变动 到 kubernetes discovery 接收到 events 的延迟
> * kubernetes discovery 接收到 events 后，修改 nodes 列表的延迟
> 
> 为了验证，可以做如下试验:
> 
> 1. 将 apisix 日志级别改为 debug
> 2. 模拟 滚动 deployment
> 3. 对比 kubernetes discovery 的日志打印时间和日志内容里面的更改时间,两个时间差值可以反应出延迟情况
> 
> @chenjinxuan @tzssangglass

我这边的情况是，当我大批量滚动deployment的时候，会出现apisix一直（长达10分钟以上）不更新pod ip情况

**Comment by zhixiongdu027** [comment]
> 我这边的情况是，当我大批量滚动deployment的时候，会出现apisix一直（长达10分钟以上）不更新pod ip情况

能看在发现故障时，同时看看 endpoints资源情况吗。

另外，这让我联想到另外一个 issue #8313

**Comment by chenjinxuan** [comment]
> > 我这边的情况是，当我大批量滚动deployment的时候，会出现apisix一直（长达10分钟以上）不更新pod ip情况
> 
> 能看在发现故障时，同时看看 endpoints资源情况吗。
> 
> 另外，这让我联想到另外一个 issue #8313

我是直接通过svc地址连接apiserver，没有通过其他代理。
你的意思是当发现故障时，我去看k8s endpoints资源情况？还是说看apisix的upstream情况？

**Comment by zhixiongdu027** [comment]
> 你的意思是当发现故障时，我去看k8s endpoints资源情况？还是说看apisix的upstream情况？


看 enpoints

**Comment by zhixiongdu027** [comment]
请问有什么发现吗 @chenjinxuan
