### ISSUE TITLE
help request: How to implement `apisix.core.json` encode output Unicode characters

### ISSUE THREAD

**Issue by dickens7** [apache/apisix#8498]
### Description

How do I output Unicode characters in Apisix using the encode function of `apisix.core.json`?

```lua
local json = require "apisix.core.json"
local t = {aaa = "aaaa", bbb = "你好，世界"}
local json_str = json.encode(t)
print(json_str)
```

Expected output

```json
{"aaa":"aaaa","message":"\u4f60\u597d，\u4e16\u754c"}
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by pixeldin** [comment]
This looks like an encoding issue you are occured. And from your example, you import with the ```local json = require "apisix.core.json"``` but using the ```cjson.encode(t)```.
You may try this?
```
local json = require "apisix.core.json"
local t = {aaa = "aaaa", bbb = "你好，世界"}
local json_str = json.encode(t)
print(json_str)
```

**Comment by dickens7** [comment]
@pixeldin Thanks, the `cjson` here is wrong when pasting the code

**Comment by spacewander** [comment]
I tried:
```
=== TEST 18: hit
--- ONLY
--- config
    location /t {
        content_by_lua_block {
            local json = require "apisix.core.json"
local t = {aaa = "aaaa", bbb = "你好，世界"}
local json_str = json.encode(t)
ngx.print(json_str)
        }
    }
--- response_body
```
Got: `{"bbb":"你好，世界","aaa":"aaaa"}`.

It works fine for me.

**Comment by tzssangglass** [comment]
what his' expected output is

```json
{"aaa":"aaaa","message":"\u4f60\u597d，\u4e16\u754c"}
```

**Comment by dickens7** [comment]
> what his' expected output is
> 
> ```json
> {"aaa":"aaaa","message":"\u4f60\u597d，\u4e16\u754c"}
> ```

Yes, that's what I expect.
I looked into it and it seems like I can only implement a `utf8_to_unicode` on my own

**Comment by tzssangglass** [comment]
accord to: http://lua-users.org/wiki/LuaUnicode

It seems that the "convert a character to a string in unicode" you want is not possible.
