### ISSUE TITLE
CSS come out to question mark, after apply filter in response-rewrite plugin

### ISSUE THREAD

**Issue by juzn01** [apache/apisix#8501]
### Current Behavior

After i config filter in respone rewrite css file come out to question mark???
![image](https://user-images.githubusercontent.com/28623637/207021645-74970d88-2258-4bc3-bb67-1433a7dd9bb4.png)

Css on browser:
![image](https://user-images.githubusercontent.com/28623637/207025731-068df01f-d2b1-4e68-890c-b80eb92788ff.png)

### Expected Behavior

Css on normal:
![image](https://user-images.githubusercontent.com/28623637/207022475-846481ff-afc7-4876-b1c3-ddc4fd9d05e4.png)

### Steps to Reproduce

instal apisix 3.0 on redhat 7.9 by rpm
start apisix:
systemctl start apisix
![image](https://user-images.githubusercontent.com/28623637/207022732-68c53b4f-10cd-4990-b412-f22bdcc4973f.png)

### Environment

APISIX version (run apisix version):3.0
Operating system (run uname -a): redhat 7.9
OpenResty / Nginx version (run openresty -V or nginx -V):1.21.4.1
etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):3.5.0

**Comment by juzn01** [comment]
i uploaded error css capture:
![image](https://user-images.githubusercontent.com/28623637/207025186-2b8787d7-edf3-4bc2-964c-498f5abff9e7.png)

**Comment by mscb402** [comment]
First, share the header before the plugin is enabled.
And then share the header after the plugin is enabled.

**Comment by juzn01** [comment]
> First, share the header before the plugin is enabled. And then share the header after the plugin is enabled.

dev team has fix link in html and i don't need modify response . thank you.
