### ISSUE TITLE
help request: how to set the response content-type

### ISSUE THREAD

**Issue by yunduansing** [apache/apisix#8505]
### Description

when use ext-plugin-post-resp to wrap the response data,client received the response header["Content-Type"] will be changed ,the origin is application/json,but the received of client is text/plain

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tzssangglass** [comment]
ref: https://github.com/apache/apisix/issues/8388#issuecomment-1345741536

we can tracing in #8388
