### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by ghost** [apache/apisix#8506]
### Description

lua ./apisix/cli/apisix.lua start
lua: error loading module 'ssl.core' from file '/data/tapisix/deps/lib/lua/5.1/ssl.so':
	/data/tapisix/deps/lib/lua/5.1/ssl.so: undefined symbol: luaL_setfuncs
stack traceback:
	[C]: ?
	[C]: in function 'require'
	/data/tapisix/deps/share/lua/5.1/ssl.lua:8: in main chunk
	[C]: in function 'require'
	/data/tapisix/deps/share/lua/5.1/ssl/https.lua:10: in main chunk
	[C]: in function 'require'
	./apisix/cli/etcd.lua:24: in main chunk
	[C]: in function 'require'
	./apisix/cli/ops.lua:18: in main chunk
	[C]: in function 'require'
	./apisix/cli/apisix.lua:32: in main chunk
	[C]: ?
make: *** [run] 错误 1

when I execute apisix.lua,it reports the mistake.

### Environment

The system is centos7, dependecies cmd is:

yum-config-manager --add-repo "https://openresty.org/package/centos/openresty.repo"
sed -i 's/$releasever/7/g' /etc/yum.repos.d/openresty.repo
yum install -y openresty  openresty-openssl111-devel

**Comment by mscb402** [comment]
Why this Lua path is in "/data/tapisix", are you changed the script?

**Comment by tzssangglass** [comment]
> lua ./apisix/cli/apisix.lua start

This is the wrong way to execute it.

We usually execute the following in the APISIX installation directory

```
./bin/apisix start
```
