### ISSUE TITLE
help request: How to set header in apisix ? 

### ISSUE THREAD

**Issue by wavemoroc001** [apache/apisix#8508]
### Description

Hi I have plan to set keycloak behide gateway and I have to set header in order to make keycloak work fine.
How to config following header in apisix gateway via `apisix_dashboard` ? 

```conf
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
``` 

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): Docker env
- APISIX Dashboard version, if relevant: 2.15

**Comment by mscb402** [comment]
You can use proxy-rewrite plugin to change header https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by wavemoroc001** [comment]
@mscb402 It can call variable like in nginx ? eg. `$remote_addr`

**Comment by mscb402** [comment]
Yes. The values in the header can contain Nginx variables like $remote_addr and $client_addr.

**Comment by mscb402** [comment]
If this answer work for you, you can close this issue. :)

**Comment by karl-chanel** [comment]
> why cant i see the proxy-rewrite plugin in the route config dashboard,while i can see the plugin in the global plugin config dashboard@mscb402 

i can do that via the admin api using curl,but i cant do that in the dashboard
