### ISSUE TITLE
help request: 在apisix-dashboard中,同样的插件配置,对路由使用插件生效,对服务使用插件不生效

### ISSUE THREAD

**Issue by Coderyangg** [apache/apisix#8510]
### Description

同一个插件配置，在路由中使用可以正常使用，在服务中配置不生效

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Hello, plugin only enable at ones

**Comment by mscb402** [comment]
If you config plugin at service and router. Only config at the router will be used. In other words, the plugin configuration on the route takes precedence over the service. If both routes exist, the plug-in configuration of the route will overwrite them

**Comment by mscb402** [comment]
Can you tell us what plugin you are using?  And share plugin config detail.

**Comment by mscb402** [comment]
Can you describe in more detail about "not working" for us?

**Comment by Coderyangg** [comment]
> Can you tell us what plugin you are using? And share plugin config detail.

all plugin when i use for route ,it`s working,whlie for service,it`s invalid,now i am using oidc plugin.
this is my config
{
  "bearer_only": true,
  "client_id": "xx",
  "client_secret": "xxxx",
  "disable": true,
  "discovery": "https://keycloak.icos.city/realms/dit/.well-known/openid-configuration",
  "realm": "xx",
  "scope": "openid profile"
}

**Comment by mscb402** [comment]
By the way, Are you config plugin at the router and service at the same time? Or are you forget to add the route to the service?

**Comment by mscb402** [comment]
Are you config router and service at the same time, and setting the router plugin with `disable: true`?

**Comment by mscb402** [comment]
If so, please try to remove the plugin from the router, not just disable it.

> Are you config router and service at the same time, and setting the router plugin with `disable: true`?

**Comment by Coderyangg** [comment]
> Are you config router and service at the same time, and setting the router plugin with `disable: true`?

no,i just display the config,while i use it,it is not config the same time

**Comment by mscb402** [comment]
Please try to remove this plugin from the router, not just disable it.

**Comment by Coderyangg** [comment]
> Please try to remove this plugin from the router, not just disable it.

ok ,thank you ,it it valid now
