### ISSUE TITLE
Using advanced matching conditions does not take effect

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8517]
### Description

when i set the advanced rules ，in the etcd store，the values is 
"vars":[["uri","==","\/api"]]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/535200/207491387-e9f82f1d-2d3a-4486-bdd5-9e40857a3239.png">

but when i request the route ,this is not effect,Is it because there are escape symbols in etcd？

### Environment

- APISIX version (run `apisix version`):2.14.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Can you share more detail?

**Comment by tzssangglass** [comment]
> when i set the advanced rules ，in the etcd store，the values is

Please give the complete reproduction steps

**Comment by kellyseeme** [comment]
this is two rules:
{
	"hosts": ["mes.test.cn"],
	"vars": [
		["uri", "~*", "^.*1234.*$"]
	],
	"name": "mes03",
	"uris": ["\/*"],
	"upstream_id": "15"
}
---
{
	"hosts": ["mes.test.cn"],
	"name": "mes04",
	"uris": ["\/*"],
	"upstream_id": "15"
}

i have two rules,but when i request for this:

curl mes.test.cn/00123400 ,it hit the second rules，in my desirse is hit the first rules have the advanced rules.

**Comment by tzssangglass** [comment]
> curl mes.test.cn/00123400 ,it hit the second rules，in my desirse is hit the first rules have the advanced rules.

the `uri` of first route is `/`, it only match the request `curl http://mes.test.cn/`, which request path is `/`

**Comment by kellyseeme** [comment]
sorry，the page show is wrong,if i edit this is show this :
<img width="876" alt="image" src="https://user-images.githubusercontent.com/535200/207751642-a248149e-1621-4082-977a-0c907921b819.png">

**Comment by mscb402** [comment]
I think you should using `"vars":[["uri","~~","^.*1234.*$"]]` instead.

**Comment by kellyseeme** [comment]
> 

i have try,but also the same result,hit the second rules.

**Comment by mscb402** [comment]
Emm, Mabey you can try setting 'priority' on this router

```
{
"hosts": ["mes.test.cn"],
"vars": [
["uri", "~", "^.1234.$"]
],
"name": "mes03",
"uris": ["/"],
"priority":100,
"upstream_id": "15"
}

----
{
"hosts": ["mes.test.cn"],
"name": "mes04",
"uris": ["/*"],
"priority":0,
"upstream_id": "15"
}
```

**Comment by kellyseeme** [comment]
this rule is first to match the hosts,uris,priority,then use the vars to match rules?

**Comment by mscb402** [comment]
> this rule is first to match the hosts,uris,priority,then use the vars to match rules?

If different Routes match to the same URI, then the Route is matched based on its priority. A higher value corresponds to a higher priority. It is set to 0 by default. So by default, we can't assume the order of match. 
Does this `priority` solve your problem?

**Comment by kellyseeme** [comment]
for this enviroment,it can solve,i see the doc about match rules:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/535200/207824710-99211979-14aa-45bb-ae1c-690ed0b2e92d.png">
if the rules have the same uri,just match the hosts?not match the vars condition??

**Comment by tokers** [comment]
The `vars` is not the "first-class" condition for the route matching. Only when you match the URI (and Host, if you use the `radixtree_host_uri` router), the `vars` will be checked. Thus, if there are two routes with the same Host and URI, one has `vars` while the other hasn't. Then proper priority should be assigned. Or the second one might never have the chance to match API requests.

**Comment by tokers** [comment]
The `vars` is not the "first-class" condition for the route matching. Only when you match the URI (and Host, if you use the `radixtree_host_uri` router), the `vars` will be checked. Thus, if there are two routes with the same Host and URI, one has `vars` while the other hasn't. Then proper priority should be assigned. Or the second one might never have the chance to match API requests.

**Comment by kellyseeme** [comment]
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/535200/208024446-3e8522a2-fa92-421d-8074-65c2fc8ee6c7.png">
the dashboard is use the vars conditions to set the blue-green ,this is wrong?

**Comment by mscb402** [comment]
Why would you think this is wrong?

**Comment by kellyseeme** [comment]
if we use the blue-green,then the uri is same,the priority is the same,the hosts is same,only the vars is not same,but the vars is not checked,so maybe one rules is never hit.

> The `vars` is not the "first-class" condition for the route matching. Only when you match the URI (and Host, if you use the `radixtree_host_uri` router), the `vars` will be checked. Thus, if there are two routes with the same Host and URI, one has `vars` while the other hasn't. Then proper priority should be assigned. Or the second one might never have the chance to match API requests.

**Comment by tzssangglass** [comment]
> if we use the blue-green,then the uri is same,the priority is the same,the hosts is same,only the vars is not same,but the vars is not checked,so maybe one rules is never hit.

Yes, it was as expected.

**Comment by kellyseeme** [comment]
when i use the **radixtree_uri**,set two rules:
{
"hosts": ["test1.cn"],
"name": "mes04",
"uris": ["/*"],
"upstream_id": "15"
}

{
"hosts": ["test2.cn"],
"name": "mes04",
"uris": ["/*"],
"upstream_id": "16"
}
curl 10.189.13.131 -H 'host:test2.cn'
test2.cn

curl 10.189.13.131 -H 'host:test1.cn'
test1.cn

why this is work fine?this is only hosts and upstream is not same..for befor reply ,there must be a rule never mached.



> The `vars` is not the "first-class" condition for the route matching. Only when you match the URI (and Host, if you use the `radixtree_host_uri` router), the `vars` will be checked. Thus, if there are two routes with the same Host and URI, one has `vars` while the other hasn't. Then proper priority should be assigned. Or the second one might never have the chance to match API requests.

**Comment by tzssangglass** [comment]
> why this is work

if your `apisix.router.http` is `radixtree_uri`(defaulte), it's just coincidence that it works.

if you set `apisix.router.http` to `radixtree_host_uri`, it will work as expected.

read more: https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/router.md

**Comment by kellyseeme** [comment]
> > why this is work
> 
> if your `apisix.router.http` is `radixtree_uri`(defaulte), it's just coincidence that it works.
> 
> if you set `apisix.router.http` to `radixtree_host_uri`, it will work as expected.
> 
> read more: https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/router.md

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/535200/209034072-c84ac65e-1da2-4a4c-bd94-829d9623d0ae.png">

if there have two rules of the same uri,then match only once???

in my expect:if there have the same uri of two rules,there will be match two rules,so the hosts,prioryty and vars can affect the result of match.

**Comment by kellyseeme** [comment]
> > why this is work
> 
> if your `apisix.router.http` is `radixtree_uri`(defaulte), it's just coincidence that it works.
> 
> if you set `apisix.router.http` to `radixtree_host_uri`, it will work as expected.
> 
> read more: https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/router.md

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/535200/209034072-c84ac65e-1da2-4a4c-bd94-829d9623d0ae.png">

if there have two rules of the same uri,then match only once???

in my expect:if there have the same uri of two rules,there will be match two rules,so the hosts,prioryty and vars can affect the result of match.

**Comment by tokers** [comment]
Yes, that's a counter-intuitive point. It's not easy to change the router. I propose writing more docs about it.

**Comment by kellyseeme** [comment]
if search in browser ，we can find the example，
<img width="947" alt="image" src="https://user-images.githubusercontent.com/535200/209494805-919e6ed3-bc9f-4b5d-8dcf-5efd4d61735e.png">
 in the config step,there all use the default configuration,if all is coincidental,they business is maybe work wrong，but they can't find it ?

so in apisix,all rules matched must has  a precondition(default configuration): the uri must not the same。

but in some enviroment,we must have the same uri and only the vars is not the same...

> <img alt="image" width="1092" src="https://user-images.githubusercontent.com/535200/208024446-3e8522a2-fa92-421d-8074-65c2fc8ee6c7.png">
> 
> the dashboard is use the vars conditions to set the blue-green ,this is wrong?

in the dashboard,there blue-green,there is only the vars not same.use the priority also not slove the problem.

**Comment by tzssangglass** [comment]
> but in some enviroment,we must have the same uri and only the vars is not the same...

Unfortunately, it is not supported if it is in this form.

One option I've seen is.

Add a recognizable prefix to the client request, like /foo/*, /bar/*, and use proxy-rewrite in APISIX to remove /foo, /bar

**Comment by kellyseeme** [comment]
> <img alt="image" width="825" src="https://user-images.githubusercontent.com/535200/207826721-68b063ff-32c7-49d3-89ee-7f9d8fefe77a.png">
> 
> in my test,this is not same by the doc

if the uri is same，but priority is not same，then this will be match rules twice？
