### ISSUE TITLE
feat: support using upstream as the backend of the proxy-mirror plugin

### ISSUE THREAD

**Issue by lingsamuel** [apache/apisix#8518]
### Description

Using upstream as the backend of proxy-mirror can reduce the cost of route maintenance, as the user only needs to maintain a single upstream instead of a specific value on a huge number of routes.

In addition, in xds, routes and upstreams are configured by different services. All upstreams are managed with the same concept, as is the mirror backend. Therefore, the route will reference an upstream resource instead of using a specific value that will be used.
So in this case, it's difficult, even impossible, to correctly grab the data from the upstream.nodes and patch it to the proxy-mirror plugin of routes due to the timing uncertainty.

**Comment by Revolyssup** [comment]
@Sn0rt Please add this to backlog
