### ISSUE TITLE
bug: proxy-write plugin reset authorization in headers will affect the use of basic auth plugin

### ISSUE THREAD

**Issue by zhuliquan** [apache/apisix#8521]
### Current Behavior

I want to convert Apisix authentication to upstream authentication by proxy rewrite-plugin, but I got error below:
{"message":"Invalid user key in authorization"}
I guess that proxy-rewrite changes authorization in headers before the basic-auth plugin in apisix.

### Steps to Reproduce

I want to convert Apisix authentication to upstream authentication by proxy rewrite-plugin, but I got error below:
{"message":"Invalid user key in authorization"}
I guess that proxy-rewrite changes authorization in headers before the basic-auth plugin in apisix.

### Environment

APISIX version is 2.1
Consumer setting is:
```{
    "plugins": {
        "basic-auth": {
            "username": "zhuliquan",
            "password": "c8cabe9627b258016c373779fb896fa1"
        }
    },
    "username": "zhuliquan"
}```json
route setting is:
```
{
    "plugins": {
        "prometheus": {
            "disable": false
        },
        "basic-auth": {
            "disable": false
        },
        "limit-count": {
            "time_window": 60,
            "disable": false,
            "count": 20,
            "redis_timeout": 1000,
            "rejected_code": 502,
            "key": "consumer_name",
            "policy": "local"
        },
        "consumer-restriction": {
            "whitelist": [
                "zhuliquan"
            ],
            "rejected_code": 403,
            "disable": false,
            "type": "consumer_name"
        },
        "proxy-rewrite": {
            "scheme": "http",
            "disable": false,
            "uri": "/test_index/_search?size=0&from=0&preference=_primary_first",
            "headers": {
                "set": {
                    "Authorization": "Basic ZXNfYWRtaW46cWlhbnhpbkBFUw=="
                }
            }
        }
    },
    "name": "search_full_data",
    "priority": 0,
    "uris": [
        "/v1/files/_search_full_data"
    ],
    "methods": [
        "POST"
    ],
    "service_id": "00008"
}
```

**Comment by tzssangglass** [comment]
```
basic-auth                     # priority: 2520
proxy-rewrite                  # priority: 1008
```

`basic-auth` run before `proxy-rewrite`

**Comment by zhuliquan** [comment]
@tzssangglass waht can I do to exchange the execution order of two plugins

**Comment by zhuliquan** [comment]
>

**Comment by zhuliquan** [comment]
> ```
> basic-auth                     # priority: 2520
> proxy-rewrite                  # priority: 1008
> ```
> 
> `basic-auth` run before `proxy-rewrite`
what can i do?

**Comment by tzssangglass** [comment]
> what can i do?

I mean proxy-rewrite shouldn't affect the results of basic-auth because it runs after the basic-auth plugin runs.

**Comment by zhuliquan** [comment]
> > what can i do?
> 
> I mean proxy-rewrite shouldn't affect the results of basic-auth because it runs after the basic-auth plugin runs.

are your sure it work out on apisix 2.1?

**Comment by tzssangglass** [comment]
> are your sure it work out on apisix 2.1?

from: https://github.com/apache/apisix/blob/9c7e96e608099bcc7a0fa10b1ee4395e7a03d3fa/conf/config-default.yaml#L201-L224

I think it should work on v2.1
