### ISSUE TITLE
help request: in apisix etcd failed to parse domain

### ISSUE THREAD

**Issue by chelintsien** [apache/apisix#8529]
### Description

apisix will probabilistically appear in k8s：
v3.lua:716: request_chunk(): http://etcd.ingress-apisix.svc.cluster.local:2379: failed to parse domain: failed to parse domain. Retrying, context
But pinging the etcd.ingress-apisix.svc.cluster.local in the same pod with the error is fine

### Environment

- APISIX version (run `apisix version`):  2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4, use http connect to etcd
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Fabriceli** [comment]
Can you give the reproduce steps?

**Comment by tzssangglass** [comment]
same as: #7715?

**Comment by Martinprobu** [comment]
i have the same issure

**Comment by Lanhild** [comment]
Same here;
```bash
2022/12/20 02:07:14 [warn] 48#48: *6440513 [lua] v3.lua:733: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
```
>Using the default configuration provided in apache/apisix-docker

**Comment by chelintsien** [comment]
> Can you give the reproduce steps?

probabilistic occurrence, no mandatory steps

**Comment by tokers** [comment]
> > @chelintsien How did you install APISIX? What about the version information?
> 
> use helm install, apisix is v2.15.1

Please add them to the issue description. Thanks.

Also, could you try to login to the APISIX container, and check out the `etc/resolv.conf`, use dig command with the DNS server that is used by APISIX, to see if you can resolve the domain correctly.

**Comment by chelintsien** [comment]
in the APISIX container :
![image](https://user-images.githubusercontent.com/1673155/208635004-a8d29f1b-5407-419e-b36b-5c5a72fb0cf6.png)
![image](https://user-images.githubusercontent.com/1673155/208635293-d4eefaa2-a19f-4b8c-8eff-e5a43e22c673.png)

**Comment by ependi-buzz** [comment]
use ip is ok

**Comment by tokers** [comment]
This is a known issue, we're still trying to troubleshoot it.

**Comment by vtychx** [comment]
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/60866246/211786738-ac52039b-f371-4d06-b77f-ceaa04f894e5.png">
DNS server works fine.I found the problem is function _deepcopy().
table orig have values but can not call line:134  "for pairs(orig) do",and istable print 0. Usually it should print 2.
<img width="1822" alt="image" src="https://user-images.githubusercontent.com/60866246/211790898-819c92fa-cb92-4c2e-be3a-8d1a16ad4ad9.png">

**Comment by vtychx** [comment]
@tokers

**Comment by tokers** [comment]
> <img alt="image" width="1487" src="https://user-images.githubusercontent.com/60866246/211786738-ac52039b-f371-4d06-b77f-ceaa04f894e5.png">
> 
> DNS server works fine.I found the problem is function _deepcopy(). table orig have values but can not call line:134 "for pairs(orig) do",and istable print 0. Usually it should print 2.
> <img alt="image" width="1822" src="https://user-images.githubusercontent.com/60866246/211790898-819c92fa-cb92-4c2e-be3a-8d1a16ad4ad9.png">

Thanks for the clue.

**Comment by tokers** [comment]
@chelintsien I tested this case on my local, but I didn't reproduce it.

**Comment by shreemaan-abhishek** [comment]
@chelintsien please share your Operating System information. `etcd` is not fully supported on M1 mac.

**Comment by hyt05** [comment]
Rolling back the version to apisix:2.14.1-centos solved this problem
https://github.com/apache/apisix/issues/7715#issuecomment-1217959557

**Comment by monkeyDluffy6017** [comment]
It's fixed, please refer to this issue: https://github.com/apache/apisix/issues/8800
The related pr: https://github.com/api7/apisix-build-tools/commit/b3805a0bef56abb1cd0e950437168612272a4681
