### ISSUE TITLE
docs: add consul link to README.md file

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix#8533]
### Current State

> https://github.com/apache/apisix/blob/master/README.md#126
- Works with external service discovery: In addition to the built-in etcd, it also supports [Consul](docs/en/latest/discovery/consul_kv.md), [Nacos](docs/en/latest/discovery/nacos.md), [Eureka](docs/en/latest/discovery/eureka.md) and [Zookeeper (CP)](docs/en/latest/discovery/zookeeper.md).
  

### Desired State

- Works with external service discovery: In addition to the built-in etcd, it also supports [Consul](docs/en/latest/discovery/consul.md), [Consul_kv](docs/en/latest/discovery/consul_kv.md), [Nacos](docs/en/latest/discovery/nacos.md), [Eureka](docs/en/latest/discovery/eureka.md) and [Zookeeper (CP)](docs/en/latest/discovery/zookeeper.md).

**Comment by Amishakumari544** [comment]
[consul_kv](https://github.com/apache/apisix/issues/docs/en/latest/discovery/consul_kv.md) link is giving 404 @Fabriceli
