### ISSUE TITLE
help request: how to lossless update  upsteam service in k8s 

### ISSUE THREAD

**Issue by qlql489** [apache/apisix#8535]
### Description

i config  router  use node type, the value is k8s's service host,  like this:
```
"nodes": [
      {
        "host": "push-api",
        "port": 80,
        "weight": 1
      }
    ]
```
the upstream service deploy at list two pod ,when i update upstream service ,will cause some requsts faill, return code 502
i guess is the upsteam's  keepalive config, the old connection is not close,  i  try to modify the config like this , it works ， but It affects performance and is not elegant，have other solution to solve the problem?
```
 upstream apisix_backend {
        server 0.0.0.1;


        balancer_by_lua_block {
            apisix.http_balancer_phase()
        }
        # keepalive 320;
        # keepalive_requests 1000;
        # keepalive_timeout 60s;
        # we put the static configuration above so that we can override it in the Lua code
    }
```

### Environment

- APISIX version (2.13.1):
- Operating system (linux):
- OpenResty / Nginx version (openresty/1.19.9.1):
- etcd version, if relevant ():
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues ():

**Comment by tzssangglass** [comment]
same as: #8489?

**Comment by tokers** [comment]
@tzssangglass Here seems that he didn't use the service discovery.

@qlql489 This may be due to APISIX doesn't know that your pods are drifting. So it still reuses the connections in the keepalive pool. Try enabling `proxy_socket_keepalive`.

**Comment by shreemaan-abhishek** [comment]
ping @qlql489, do you have any further questions/updates? If not, please close the issue. Thanks.
