### ISSUE TITLE
想让apisix充当正向代理服务器

### ISSUE THREAD

**Issue by yuqiquan** [apache/apisix#8539]
### Description

想让apisix作为正向代理服务器，然后在配置文件中进行配置

![image](https://user-images.githubusercontent.com/44921350/208573384-71db4adb-77cc-4a2b-bd80-edd9cbb5f97c.png)

然后通过apisix代理访问 ，日志中出现错误
![image](https://user-images.githubusercontent.com/44921350/208573495-27b781f7-6c87-41aa-87c8-ad91adbc8c66.png)

访问失败 ，这种情况应该怎么解决？

### Environment

- APISIX version 2.15.0

**Comment by tokers** [comment]
A good reproducible case is good for troubleshooting, including:

1. How did you install APISIX?
2. How did you send a request?
3. Which response is the one you want to see?
4. Which response is the one you saw?

**Comment by kwanhur** [comment]
what's the [proxy-protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt)

what's the [forward-proxy](https://www.jscape.com/blog/forward-proxy-vs-reverse-proxy)

they're totally different.
