### ISSUE TITLE
bug: can't run apifix by offical document

### ISSUE THREAD

**Issue by LoseAccount233** [apache/apisix#8540]
### Current Behavior

I operate according to the official document
When I run  docker-compose -p docker-apisix up -d  after
the main container apisix start failed

logs:
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused
all etcd nodes are unavailable
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused

I have tested this operation on three servers，they all failed

### Expected Behavior

run all container success

### Error Logs

/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init
/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused

### Steps to Reproduce

git clone https://githubfast.com/apache/apisix-docker.git  
cd apisix-docker/example
docker-compose -p docker-apisix up -d

### Environment

- APISIX version (run `apisix version`): lastest
- Operating system (run `uname -a`): centos7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by pixeldin** [comment]
have you checked the running status or connection health of `etcd`?

**Comment by tokers** [comment]
Try to print the content of `docker-compose ps`.

**Comment by LoseAccount233** [comment]
> Try to print the content of `docker-compose ps`.
Nothing returned after running `docker-compose ps`

After running `docker ps`, return to the running container list 
CONTAINER ID   IMAGE                                   COMMAND                  CREATED         STATUS                          PORTS                              NAMES
7c3d5fddaa7c   apache/apisix:latest                    "sh -c '/usr/bin/api…"   5 minutes ago   Restarting (1) 41 seconds ago                                      docker-apisix-apisix-1
d636acf0c3a4   prom/prometheus:v2.25.0                 "/bin/prometheus --c…"   5 minutes ago   Up 5 minutes                    0.0.0.0:9090->9090/tcp             docker-apisix-prometheus-1
4a9592eba40d   nginx:1.19.0-alpine                     "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes                    0.0.0.0:9081->80/tcp               docker-apisix-web1-1
ad9ac7db628c   grafana/grafana:7.3.7                   "/run.sh"                5 minutes ago   Up 5 minutes                    0.0.0.0:3000->3000/tcp             docker-apisix-grafana-1
50573a2f03ce   apache/apisix-dashboard:2.15.0-alpine   "/usr/local/apisix-d…"   5 minutes ago   Up 5 minutes                    0.0.0.0:9000->9000/tcp             docker-apisix-apisix-dashboard-1
d5365f87ac9f   bitnami/etcd:3.4.15                     "/opt/bitnami/script…"   5 minutes ago   Up 5 minutes                    0.0.0.0:2379->2379/tcp, 2380/tcp   docker-apisix-etcd-1
cc329ca3a381   nginx:1.19.0-alpine                     "/docker-entrypoint.…"   5 minutes ago   Up 5 minutes                    0.0.0.0:9082->80/tcp               docker-apisix-web2-1

I also try to use java to control etcd and work common to write and read data;

**Comment by LoseAccount233** [comment]
> have you checked the running status or connection health of `etcd`?

yes, i hava test the etcd by java; I try to use java to control etcd, and it works normally,

**Comment by LoseAccount233** [comment]
> have you checked the running status or connection health of `etcd`?

yes, I try to use java to control etcd, and it works normally,

**Comment by LoseAccount233** [comment]
> have you checked the running status or connection health of `etcd`?

The cause of the bug is my image mirro is aliyun,i change apisix version to `apache/apisix:3.0.0-centos` and it works normaly!

thanks!

**Comment by LoseAccount233** [comment]
> Try to print the content of `docker-compose ps`.

The cause of the bug is my image mirro is aliyun,i change apisix version to `apache/apisix:3.0.0-centos` and it works normaly!

thanks!

**Comment by unsw-luopan** [comment]
save my life......same error, same mirror
