### ISSUE TITLE
bug: apisix3.0启用ext-plugin-post-resp插件后，域名改写异常

### ISSUE THREAD

**Issue by shixiaoge** [apache/apisix#8541]
### 路由配置
```txt
{
  "uri": "/test/*",
  "name": "test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "ext-plugin-post-resp": {
      "conf": [
        {
          "name": "Test",
          "value": "{}"
        }
      ],
      "disable": false
    },
    "proxy-rewrite": {
      "host": "www.test.com",
      "regex_uri": [
        "/test/(.*)",
        "/$1"
      ],
      "scheme": "http"
    }
  },
  "service_id": "438694776414407728",
  "status": 1
}
```
## 问题
`启用 ext-plugin-post-resp 插件后，域名改写 无效`

``

### Steps to Reproduce

1. 配置Service，节点类型 IP + 端口 (nginx服务器)
2. 配置路由，配置域名改写
3. 访问测试，观察上游服务器 nginx 日志，$host 部分 (域名改写正常)
4. 启用 ext-plugin-post-resp 插件
5. 访问测试，观察上游服务器 nginx日志，$host部分 (域名改写不生效)

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): centos7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.9.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Please provide a more detailed reproducible case. What does the request look like? What does the response look like?

**Comment by a11enhuang** [comment]
配置headers也会失效
