### ISSUE TITLE
help request: Errors are reported by different consumers pointing to different published routes 

### ISSUE THREAD

**Issue by bluewaystar** [apache/apisix#8547]
### Description

Two routes R1 and R2 and two consumers C1 and C2 are established respectively

Consumer C1 points to route R1, and consumer C2 points to route R2

Publish a route and offline another route. At this time, the route of request publishing is OK.

However, if two routes are published at the same time, an error is reported when requesting a route:
{"message": "The consumer_name is forbidden."}

-------------- Create R1 and R2 ------------------------

{
    "uri": ["/*"],
    "methods": ["GET","POST"],
    "priority": 0,
    "name": "R1",
    "plugins": {"jwt-auth": {"disable": false},"consumer-restriction": {
            "whitelist": [
                "C1"
            ]
        }, "proxy-rewrite": {
            "regex_uri": ["^/xy/(.*)","/$1"]
        }},
    "desc": "R1 DESC",
    "upstream_id": "00000000000000000430"
}

{
    "uris": ["/*"],
    "methods": ["GET","POST"],
    "priority": 0,
    "name": "R2",
    "plugins": {"jwt-auth": {"disable": false},"consumer-restriction": {
            "whitelist": [
                "C2"
            ]
        }, "proxy-rewrite": {
            "regex_uri": ["^/mn/(.*)","/$1"]
        }},
    "desc": "R2 DESC",
    "upstream_id": "00000000000000000432"
}

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by bluewaystar** [comment]
Create route R1 and R2:
{
    "uri": ["/*"],
    "methods": ["GET","POST"],
    "priority": 0,
    "name": "R1",
    "plugins": {"jwt-auth": {"disable": false},"consumer-restriction": {
            "whitelist": [
                "C1"
            ]
        }, "proxy-rewrite": {
            "regex_uri": ["^/xy/(.*)","/$1"]
        }},
    "desc": "R1 DESC",
    "upstream_id": "00000000000000000430"
}

{
    "uris": ["/*"],
    "methods": ["GET","POST"],
    "priority": 0,
    "name": "R2",
    "plugins": {"jwt-auth": {"disable": false},"consumer-restriction": {
            "whitelist": [
                "C2"
            ]
        }, "proxy-rewrite": {
            "regex_uri": ["^/mn/(.*)","/$1"]
        }},
    "desc": "R2 DESC",
    "upstream_id": "00000000000000000432"
}

**Comment by spacewander** [comment]
How do you create the consumer C1 & C2?

**Comment by bluewaystar** [comment]
> How do you create the consumer C1 & C2?

{
    "username": "C1",
    "plugins": {
        "jwt-auth": {
            "key": "C1-key",
            "secret": "C1-secret"
        }
    }
}

**Comment by spacewander** [comment]
@An-DJ 
Would you help me to look up this issue? Thanks!

**Comment by An-DJ** [comment]
> @An-DJ Would you help me to look up this issue? Thanks!

plz assign to me : )

**Comment by bluewaystar** [comment]
@spacewander @An-DJ  Has this problem been solved？

**Comment by bluewaystar** [comment]
can you help me?

**Comment by An-DJ** [comment]
> can you help me?

@bluewaystar I'm working on it. Plz waitting a few days : )

**Comment by bluewaystar** [comment]
> > can you help me?
> 
> @bluewaystar I'm working on it. Plz waitting a few days : )

thanks.

**Comment by An-DJ** [comment]
@bluewaystar Notice that u use the same uri but different rules with plugin `consumer-restriction`. 

The http requests with 2 different kinds of jwt-token are C1 and C2, but they are corresponding to the same uri "/". 
That is, C2's request might be routed to R2, so that the C2's request may be forbidden because it's not in R2's whitelist.

If you want to restrict the `Consumer` to a specific `Route`, you can add more different rules in it to distinguish the two `Route` with the same uri, such as `host` and `remote_addr`.

**Comment by bluewaystar** [comment]
> @bluewaystar Notice that u use the same uri but different rules with plugin `consumer-restriction`.
> 
> The http requests with 2 different kinds of jwt-token are C1 and C2, but they are corresponding to the same uri "/". That is, C2's request might be routed to R2, so that the C2's request may be forbidden because it's not in R2's whitelist.
> 
> If you want to restrict the `Consumer` to a specific `Route`, you can add more different rules in it to distinguish the two `Route` with the same uri, such as `host` and `remote_addr`.

thanks.i try it,is success.

**Comment by spacewander** [comment]
Consider solved. Feel free to reopen it if needed.
