### ISSUE TITLE
bug: [ info ] WARNING: You're not using LuaRocks 3.x; please remove the luarocks and reinstall it via https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh

### ISSUE THREAD

**Issue by cherishman2005** [apache/apisix#8559]
### Current Behavior

openresty-1.13.6.1

```
make deps
```

```
[ info ] WARNING: You're not using LuaRocks 3.x; please remove the luarocks and reinstall it via https://raw.githubusercontent.com/apache/apisix/master/utils/linux-install-luarocks.sh
```

### Steps to Reproduce

```
make deps
```

### Environment

apisix-release-3.0

Linux ubuntu 4.9.0-141-custom #19 SMP Wed Nov 28 20:32:27 CST 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by spacewander** [comment]
We require at least LuaRocks 3.x and OpenResty 1.19.3.2+ to install APISIX.
Please remove them and install the latest ones instead.
