### ISSUE TITLE
help request: About ssl configuration？

### ISSUE THREAD

**Issue by zhangliweixyz** [apache/apisix#8561]
### Description

What is apisix->ssl->enable for and if I set enable false，what will happen?
![image](https://user-images.githubusercontent.com/70928799/209285784-22bde199-df95-44ad-a49c-2250da559768.png)

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
it wiil not generate ssl server conf, you can check `ngx_tpl.lua` in `apisix/cli/ngx_tpl.lua` or you can exec `./bin/apisix init` to see the nginx.conf

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/28869910/209307762-81790922-e645-4068-8f58-4501a141f422.png">

**Comment by zhangliweixyz** [comment]
OK，I get it, tks
