### ISSUE TITLE
feat: As a user, I want to configure consumer_group_id in consumer-restriction plugin, so that we can limit consumers by group_id

### ISSUE THREAD

**Issue by starsz** [apache/apisix#8563]
### Description

Hello, I found that we don't support configuring `consumer_group_id` in [consumer-restriction](https://apisix.apache.org/docs/apisix/plugins/consumer-restriction/) plugins.

I think we can support configuring `consumer_group_id` in this plugin so that we can limit consumers by group id; it will be easier for users.

refer: 
https://apisix.apache.org/docs/apisix/plugins/consumer-restriction/
https://apisix.apache.org/docs/apisix/admin-api/#consumer-group

**Comment by ronething** [comment]
@starsz Hi, i will try this, please assign to me.

**Comment by starsz** [comment]
> @starsz Hi, i will try this, please assign to me.

Nice. Look forward to this feature.
