### ISSUE TITLE
feat: As a user, I want to refactor the resources under apisix.admin, so that we don't need to repeat

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#8569]
### Description

Currently, all the resources under `apisix.admin` are basically copied and pasted from a template and changed. If you make general changes to the resource, such as fix count or add adapter, you need to change it file by file. And due to historical problems, some resource implementation methods are incomplete.
I hope we can refactor the code to something like `core.config.new`, where we only need to pass a few parameters to create a new resource.

Note: Please read every resource file before jumping into the refactor. Some resources have particular logic. We need a smart way to handle them.

CC @An-DJ

**Comment by An-DJ** [comment]
I think we can refactor the resources one by one:

- [ ] routes #8611 
- [ ] services
- [ ] upstreams
- [ ] consumers
- [ ] ssls
- [ ] plugins
- [ ] protos
- [ ] global_rules
- [ ] stream_routes
- [ ] plugin_metadata
- [ ] plugin_configs
- [ ] consumer_groups
- [ ] secrets

**Comment by spacewander** [comment]
We can use fewer PRs to implement it. The refactor progress can be faster after several PRs as we will have a stable foundation.

What about refactoring 2~3 resources in the upcoming PR?

**Comment by An-DJ** [comment]
The `plugins` is structurally different from other resources. 

Maybe it is NOT need to be refactored. @spacewander Can we remove it from the list?
