### ISSUE TITLE
help request: Is there any way to restrict client access by x-forward-for ?

### ISSUE THREAD

**Issue by lee-x-zh** [apache/apisix#8571]
### Description

For some reasons, we deployed Apisix behind NG.
Now We want to only grant route acesss to a specific group of public IPs。
We tried IP_RESTRICTION plugin, It seemed to only accept the front NG IP。
So, Is there any way to restrict client ip by X-Forward-For head ?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
You can try traffic-split plugin. https://apisix.apache.org/zh/docs/apisix/plugins/traffic-split/

**Comment by mscb402** [comment]
There is a example
```
curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/index.html",
    "plugins": {
        "traffic-split": {
            "rules": [
                {
                    "match": [
                        {
                            "vars": [
                                ["proxy_add_x_forwarded_for",{"127.0.0.1", "192.168.0.0/16"}]
                            ]
                        }
                    ],
                    "weighted_upstreams": [
                        {
                            "upstream": {
                                "name": "upstream_A",
                                "type": "roundrobin",
                                "nodes": {
                                    "127.0.0.1:1981":10
                                }
                            },
                            "weight": 3
                        },
                        {
                            "weight": 2
                        }
                    ]
                }
            ]
        }
    },
    "upstream": {
            "type": "roundrobin",
            "nodes": {
                "127.0.0.1:1980": 1
            }
    }
}'```

**Comment by shreemaan-abhishek** [comment]
@lee-x-zh, do you have any further questions/updates? If not, please close the issue. Thanks.
