### ISSUE TITLE
bug: dashboard操作gzip插件无法禁用功能。

### ISSUE THREAD

**Issue by jeffaryhe** [apache/apisix#8573]
### Current Behavior

apisix3.0 ：当我在dashboard操作gzip插件时，配置启用gzip功能，测试没有问题，当我关闭gzip功能之后，测试发现gzip功能依然是生效状态，查看etcd的key值，发现etcd有残留。
![image](https://user-images.githubusercontent.com/26104831/209618471-8c96acba-bd9e-4c9e-b323-7592f86c9f36.png)

### Steps to Reproduce

apisix3.0

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Do you mean you set `disable: true`, but this plugin still enable?

**Comment by jeffaryhe** [comment]
是的，gzip 插件你可以测试看看。确实是这样。

**Comment by mscb402** [comment]
I think this is a bug, gzip look like not support `disable: true`.The only solution now is for you to manually remove the plugin.

Open "View"
<img width="219" alt="image" src="https://user-images.githubusercontent.com/11229089/209896698-b8ec7912-afe7-49e3-bf03-ec4222e1d36b.png">

Remove this json
<img width="452" alt="image" src="https://user-images.githubusercontent.com/11229089/209896674-61ef49a5-572f-4df3-b894-c0531406e2d0.png">

**Comment by jeffaryhe** [comment]
etcd里面是关闭了这个，但是你要测试访问这个页面可以看到gzip开始开启的状态，你可以测试

**Comment by mscb402** [comment]
Yes, I tried. There has a problem. When you close this plugin in the UI dashboard will write a `disable: true` to ETCD (Which will not delete the plugin config in ETCD). But this plugin looks like not support this config. So you can't disable this plugin in UI. The only solution now is for you to manually remove the plugin.

**Comment by jeffaryhe** [comment]
嗯，我只是测试使用，希望你们后续修复

**Comment by mscb402** [comment]
Ok, we will fix it soon. If you have no further questions, you can close the issue～

**Comment by mscb402** [comment]
In fact, APISIX dashboard only supports version 2.15 of APISIX, which is available in version 2.15. But version 3.0 is not currently supported. And we will fix it soon
