### ISSUE TITLE
help request: How to know which consumer visited which route and upstream at which time

### ISSUE THREAD

**Issue by bluewaystar** [apache/apisix#8579]
### Description

When a third party requests a route, can you record who the third party is?

And can you record which route, service and upstream are requested by which third party?

在第三方请求路由的时候，能记录下第三方是谁吗？
并且能记录下哪个第三方请求的是哪个路由、服务、上游吗？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
How to identify a third party? IP or what others?
Regarding routing, you can use apisix variables in the log to represent different paths, upstreams, services, etc. https://github.com/apache/apisix/blob/master/docs/en/latest/apisix-variable .md

**Comment by bluewaystar** [comment]
> How to identify a third party? IP or what others? Regarding routing, you can use apisix variables in the log to represent different paths, upstreams, services, etc. https://github.com/apache/apisix/blob/master/docs/en/latest/apisix-variable .md

thanks

**Comment by juzhiyuan** [comment]
Hi @bluewaystar,

1. Does APISIX Variables can meet your needs? If yes, then please close this issue :)
2. If you have tried it successfully, can you please take some time to write a blog? Apache APISIX Community has one Blogger Program (https://apisix.apache.org/guest-blog-post), good content will be published on APISIX's Blog. https://apisix.apache.org/blog

If you have interests, please cc @EmilyKeer 🥳
