### ISSUE TITLE
help request: when i use apisix websocket config ,it is invalid

### ISSUE THREAD

**Issue by Coderyangg** [apache/apisix#8585]
### Description

i try to use apisix websocket ,this is my config 
![image](https://user-images.githubusercontent.com/39979426/209923638-6dbaf86e-be02-4c28-b783-3e388a42139a.png)
when i use postman request this,it like this 
![image](https://user-images.githubusercontent.com/39979426/209923728-eb3126c8-5687-4a90-a5e5-30206386b30a.png)

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/11229089/209932485-7c0b8555-2926-4fb3-aab9-a9c727fb75ba.png">
Can you post all `path` in there?

**Comment by Coderyangg** [comment]
> 
/ws/supervision/monitor/historyTravelPush/{twinId}/{startTime}/{endTime}/{multiplier}

**Comment by Coderyangg** [comment]
> <img alt="image" width="371" src="https://user-images.githubusercontent.com/11229089/209932485-7c0b8555-2926-4fb3-aab9-a9c727fb75ba.png">
> 
> Can you post all `path` in there? What is `{twin` at the end? Is misspell?

it is just some param

**Comment by Coderyangg** [comment]
> > <img alt="image" width="371" src="https://user-images.githubusercontent.com/11229089/209932485-7c0b8555-2926-4fb3-aab9-a9c727fb75ba.png">
> > Can you post all `path` in there? What is `{twin` at the end? Is misspell?
> 
> it is just some param

![image](https://user-images.githubusercontent.com/39979426/209933448-80483913-7060-4767-8f69-9d9a3f0b4940.png)

**Comment by mscb402** [comment]
For I know, Apisix does not support param like this one. Can you share some documents that you are read about?

**Comment by Coderyangg** [comment]
> For I know, Apisix does not support param like this one. Can you share some documents that you are read about?

apisix can not support web socket request with param?

**Comment by mscb402** [comment]
> > For I know, Apisix does not support param like this one. Can you share some documents that you are read about?
> 
> apisix can not support web socket request with param?

There is not support param like this way. Not just websocket. I don't very familiar with this. So I want know which document lead you using params in apisix. Can you share about it?

**Comment by tokers** [comment]
Please visit https://github.com/api7/lua-resty-radixtree/#parameters-in-path for more details. The syntax for marking the path parameters is wrong in your case.

**Comment by Coderyangg** [comment]
> share

I just try this way,never have i read document to using like this

**Comment by Coderyangg** [comment]
> > > For I know, Apisix does not support param like this one. Can you share some documents that you are read about?
> > 
> > 
> > apisix can not support web socket request with param?
> 
> There is not support param like this way. Not just websocket. I don't very familiar with this. So I want know which document lead you using params in apisix. Can you share about it?

i have tested param in http,as you say ,it can not support

**Comment by Coderyangg** [comment]
> > > > For I know, Apisix does not support param like this one. Can you share some documents that you are read about?
> > > 
> > > 
> > > apisix can not support web socket request with param?
> > 
> > 
> > There is not support param like this way. Not just websocket. I don't very familiar with this. So I want know which document lead you using params in apisix. Can you share about it?
> 
> i have tested param in http,as you say ,it can not support

so ,should i use this to set param?
![image](https://user-images.githubusercontent.com/39979426/210026698-aceebe0f-5807-40cc-adfc-df08339946e1.png)
