### ISSUE TITLE
help request: TCP proxy

### ISSUE THREAD

**Issue by ffjiang666** [apache/apisix#8591]
### Description

I tried to set TCP proxy followed the document about stream proxy. I setted the conf/config.yaml:
  stream_proxy: # TCP/UDP proxy
    tcp: # TCP proxy address list
      - 9006
      - 9007
and I add a stream_routes to apisix, I can connect mysql by 172.21.128.53:13306, but I can't connect by the stream proxy. I've tried many times, please help me, thanks!
![image](https://user-images.githubusercontent.com/39405427/210040225-d67c7c45-6f00-4909-8f22-792c51aee52c.png)
![tcptest](https://user-images.githubusercontent.com/39405427/210041129-8447cc32-5fa5-44a4-95a4-1b7d20bf3b10.png)

### Environment

- APISIX version (run `apisix version`):3.0.0
- Operating system (run `uname -a`):Linux srp-ims 3.10.0-1160.42.2.el7.x86_64 #1 SMP Tue Sep 7 14:49:57 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.0
- APISIX Dashboard version, if relevant:2.15.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ffjiang666** [comment]
@tokers Thank you, but there's no error log in apisix_log/error.log. Any other advice?

**Comment by tokers** [comment]
Not only APISIX, also for MySQL. If possible, could you try to capture some network packets?

**Comment by monkeyDluffy6017** [comment]
```
curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "server_addr": "192.168.3.73",
    "server_port": 9006,
    "upstream": {
        "nodes": {
            "192.168.3.73:3306": 1
        },
        "type": "roundrobin"
    }
}'

mysql --host=192.168.3.73 --port=9006 -u root -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 12
Server version: 8.0.31 MySQL Community Server - GPL
```
@ffjiang666 I tested with your example, and it worked，could you try to use the mysql in our example 
https://apisix.apache.org/docs/apisix/stream-proxy/#more-route-match-options

```
docker run --name mysql -e MYSQL_ROOT_PASSWORD=toor -p 3306:3306 -d mysql
```

**Comment by flechter** [comment]
Hello,
We try to test the stream proxy, and we have exactly the same problem.
I just try to do the example in :
https://apisix.apache.org/docs/apisix/stream-proxy/#more-route-match-options
But i stil have the same error when I try to connect to the mysql database with stream : 
root@det1authent06:~/apisix/apisix-docker-master/test# mysql --host=127.0.0.10 --port=9101 -u root -p
Enter password: 
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
root@det1authent06:~/apisix/apisix-docker-master/test# mysql --host=127.0.0.10 --port=3306 -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 17
Server version: 8.0.31 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

It is very strange, my route is like in the exemple : 

curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "server_addr": "127.0.0.10",
    "server_port": 9101,
    "upstream": {
        "nodes": {
            "127.0.0.1:3306": 1
        },
        "type": "roundrobin"
    }
}'
and i had the option in the config.yml :
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "0.0.0.0"
    port: 9092

  stream_proxy: # TCP/UDP proxy
    tcp: # TCP proxy address list
      - 9100 # by default uses 0.0.0.0
      - "127.0.0.10:9101"
    udpp: # TCP proxy address list
      - 9100 # by default uses 0.0.0.0
      - "127.0.0.10:9101"
      
     what can be the problem ?

**Comment by tokers** [comment]
> Hello,
> 
> We try to test the stream proxy, and we have exactly the same problem.
> 
> I just try to do the example in :
> 
> https://apisix.apache.org/docs/apisix/stream-proxy/#more-route-match-options
> 
> But i stil have the same error when I try to connect to the mysql database with stream : 
> 
> root@det1authent06:~/apisix/apisix-docker-master/test# mysql --host=127.0.0.10 --port=9101 -u root -p
> 
> Enter password: 
> 
> ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
> 
> root@det1authent06:~/apisix/apisix-docker-master/test# mysql --host=127.0.0.10 --port=3306 -u root -p
> 
> Enter password: 
> 
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> 
> Your MySQL connection id is 17
> 
> Server version: 8.0.31 MySQL Community Server - GPL
> 
> 
> 
> Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.
> 
> 
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> 
> affiliates. Other names may be trademarks of their respective
> 
> owners.
> 
> 
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> 
> 
> mysql> 
> 
> 
> 
> It is very strange, my route is like in the exemple : 
> 
> 
> 
> curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> 
> {
> 
>     "server_addr": "127.0.0.10",
> 
>     "server_port": 9101,
> 
>     "upstream": {
> 
>         "nodes": {
> 
>             "127.0.0.1:3306": 1
> 
>         },
> 
>         "type": "roundrobin"
> 
>     }
> 
> }'
> 
> and i had the option in the config.yml :
> 
> apisix:
> 
>   node_listen: 9080              # APISIX listening port
> 
>   enable_ipv6: false
> 
> 
> 
>   enable_control: true
> 
>   control:
> 
>     ip: "0.0.0.0"
> 
>     port: 9092
> 
> 
> 
>   stream_proxy: # TCP/UDP proxy
> 
>     tcp: # TCP proxy address list
> 
>       - 9100 # by default uses 0.0.0.0
> 
>       - "127.0.0.10:9101"
> 
>     udpp: # TCP proxy address list
> 
>       - 9100 # by default uses 0.0.0.0
> 
>       - "127.0.0.10:9101"
> 
>       
> 
>      what can be the problem ?
> 
> 
> 
> 

Which error occurred in your case? I didn't read related error messages from your reply.

**Comment by flechter** [comment]
My error is this one : 
root@det1authent06:~# mysql --host=127.0.0.10 --port=9101 -u root -p
Enter password: 
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

it's the same error, like the route didn't work

**Comment by monkeyDluffy6017** [comment]
I can not reproduce your problem, could you check if your apisix and mysql works well?  `ps aux | grep nginx` `ps aux | grep mysql` @flechter

**Comment by flechter** [comment]
I use docker both for apisix and mysql (lke in the exemple) the container are runing :
root@det1authent06:~# docker ps|grep apisix
b2a437b146f8        registry-docker.svc.ext.tdc/apache/apisix:latest                    "/docker-entrypoint.â¦"   3 days ago          Up 3 days           0.0.0.0:9080->9080/tcp, 0.0.0.0:9091-9092->9091-9092/tcp, 0.0.0.0:9100-9101->9100-9101/tcp, 0.0.0.0:9180->9180/tcp, 0.0.0.0:9443->9443/tcp   test_apisix_1
3af987724aaf        registry-docker.svc.ext.tdc/apache/apisix-dashboard:2.15.0-alpine   "/usr/local/apisix-dâ¦"   3 days ago          Up 3 days           0.0.0.0:9900->9000/tcp                                                                                                                       test_apisix-dashboard_1
root@det1authent06:~# docker ps|grep mysql
86f43e1442e8        registry-docker.svc.ext.tdc/mysql                                   "docker-entrypoint.sâ¦"   3 days ago          Up 3 days           0.0.0.0:3306->3306/tcp, 33060/tcp

**Comment by monkeyDluffy6017** [comment]
I never use apisix in docker before, could you check if it is possbile to access mysql in apisix container?

**Comment by flechter** [comment]
on the container, yes it's working when I try with the ip adress : 
root@b2a437b146f8:/usr/local/apisix# mysql --host=10.59.6.225 -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 18
Server version: 8.0.31 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> Ctrl-C -- exit!

but not if I try with a localhost adress :
root@b2a437b146f8:/usr/local/apisix# mysql --host=127.0.0.1 -u root -p
Enter password: 
ERROR 2002 (HY000): Can't connect to MySQL server on '127.0.0.1' (115)
root@b2a437b146f8:/usr/local/apisix# 
I have alos try to configure Apisix with the ip adress, but it's also  not working

**Comment by monkeyDluffy6017** [comment]
The nodes configured in route should not be `127.0.0.1:3306`, try `10.59.6.225:3306`
```
curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
"server_addr": "127.0.0.10",
"server_port": 9101,
"upstream": {
"nodes": {
"127.0.0.1:3306": 1
},
"type": "roundrobin"
}
}'
```

**Comment by flechter** [comment]
I tryed this configuration :
```
root@det1authent06:~/apisix/apisix-docker-master/test# curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "server_addr": "127.0.0.10",
>     "server_port": 9101,
>     "upstream": {
>         "nodes": {
>             "10.59.6.225:3306": 1
>         },
>         "type": "roundrobin"
>     }
> }'
{"key":"\/apisix\/stream_routes\/1","value":{"server_port":9101,"update_time":1673258709,"create_time":1672765493,"server_addr":"127.0.0.10","upstream":{"type":"roundrobin","pass_host":"pass","scheme":"http","nodes":{"10.59.6.225:3306":1},"hash_on":"vars"},"id":"1"}}
root@det1authent06:~# mysql --host=127.0.0.10 --port=9101 -u root -p
Enter password: 
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0
```
But still the same error

**Comment by flechter** [comment]
yes it's working if y try instead of the apisix port : 
```
root@det1authent06:~# mysql --host=127.0.0.10 --port=3306 -u root -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 19
Server version: 8.0.31 MySQL Community Server - GPL

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

**Comment by ffjiang666** [comment]
I followed the example before exactly.
https://apisix.apache.org/docs/apisix/stream-proxy/#more-route-match-options
It didn't work. 
![image](https://user-images.githubusercontent.com/39405427/211476834-f5b55d84-c244-4247-b21d-81b1f0fff3f2.png)
![image](https://user-images.githubusercontent.com/39405427/211480527-3bdb528c-bb0a-472c-a162-2f2e878fd71b.png)
![image](https://user-images.githubusercontent.com/39405427/211480542-d700e340-093b-43b0-b40b-d1f41647f5c2.png)
![image](https://user-images.githubusercontent.com/39405427/211480584-0b6fb5ad-fcc1-42bc-b40d-40013318b0b0.png)
![image](https://user-images.githubusercontent.com/39405427/211480626-27766fdb-2c00-4fe1-8840-d54ce1c1db32.png)
I also tried the real IP 172.21.128.53:
![image](https://user-images.githubusercontent.com/39405427/211480788-052c267d-9755-424f-a31c-0898ceacef74.png)
![image](https://user-images.githubusercontent.com/39405427/211480848-3bbf28f0-fbb0-462e-8c83-8666ab61aeea.png)
but it didn't work either.
![image](https://user-images.githubusercontent.com/39405427/211481016-b5caf48b-95d8-411b-9465-0f9181a14f73.png)

**Comment by monkeyDluffy6017** [comment]
@ffjiang666 please check if your apisix works well `ps -aux | grep nginx`

**Comment by ffjiang666** [comment]
@monkeyDluffy6017 yes, my apisix works well in docker.
![image](https://user-images.githubusercontent.com/39405427/211488066-3c52fdce-c21f-4581-89a0-60f85844afd9.png)

**Comment by ffjiang666** [comment]
By the way, I pulled from git, and runned docker by docker-compose. 
And the log is well.
![image](https://user-images.githubusercontent.com/39405427/211493237-7a19030b-32e9-43e4-beb2-353e80e2f08d.png)

**Comment by monkeyDluffy6017** [comment]
I don't find anything wrong, could you just follow the example, use the same port and mysql, like:
```
docker run --name mysql -e MYSQL_ROOT_PASSWORD=toor -p 3306:3306 -d mysql
```

**Comment by flechter** [comment]
I had the same problem, my apisix was running in docker, so I try to install it on a server without Docker and it's working.
So I thing the stream was not workin in docker mode. 
Is it normal ?

**Comment by ffjiang666** [comment]
@flechter Yeah. I think so too.
So, is it a bug in apisix docker version?

**Comment by monkeyDluffy6017** [comment]
I think it's something like network problem, are you interested in locating this problem?

**Comment by ffjiang666** [comment]
@monkeyDluffy6017 Yes, I really want to locate it and resolve it.

**Comment by kayx23** [comment]
@ffjiang666 @flechter we've just released a new how-to guide for L4 proxy and in this guide, both APISIX and MySQL are started in Docker as well.

Link: https://docs.api7.ai/apisix/how-to-guide/traffic-management/proxy-transport-layer-l4-traffic

Hope this helps.

**Comment by monkeyDluffy6017** [comment]
considered resolved
