### ISSUE TITLE
help request: location需要指向tomcat webapps目录下的路由如何配置？用proxy_rewrite插件吗

### ISSUE THREAD

**Issue by wyfaq** [apache/apisix#8594]
### Description

以下是nginx的配置：路由/fxgroup-omg指向tomcat webapps下的fxgroup-omg目录
location /fxgroup-omg {
                proxy_pass   http://prd-fxgroup-omg_upstreams/fxgroup-omg;
        }

如果改为apisix，应该如何配置了？

### Environment

- APISIX version (run `apisix version`): 2.13.3
- Operating system (run `uname -a`): 3.10.0-1127.19.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
You can create a route in APISIX with path `fxgroup-omg` and set upstream `prd-fxgroup-omg_upstreams`

**Comment by mscb402** [comment]
There is a document you can read https://apisix.apache.org/docs/apisix/getting-started/

**Comment by juzhiyuan** [comment]
> webapps

It seems that the `webapps` directory contains static files instead of API? If then, I'm not sure if it works 🤔 You can have a try first.
