### ISSUE TITLE
help request: The best practices for APISIX LB and HA in non-K8s?

### ISSUE THREAD

**Issue by saytesnake** [apache/apisix#8598]
### Description

Before that, I read some issues.

https://github.com/apache/apisix/issues/547
https://github.com/apache/apisix/issues/5612
https://github.com/apache/apisix/discussions/6060
https://github.com/apache/apisix/issues/8537

But unfortunately there's no detailed description, maybe this issue is not common in non-k8s environments, or even this approach may be incorrect and unnecessary?

That's how we currently do it.

```mermaid
graph TD;
    Keepalived-VIP-->Nginx1;
    Keepalived-VIP-->Nginx2;
    Nginx1-->APISIX1;
    Nginx1-->APISIX2;
    Nginx2-->APISIX1;
    Nginx2-->APISIX2;
    APISIX1-->ETCD1;
    APISIX1-->ETCD2;
    APISIX1-->ETCD3;
    APISIX2-->ETCD1;
    APISIX2-->ETCD2;
    APISIX2-->ETCD3;
```

And the `nginx.conf` just like that,

```
upstream APISIX {
        server 192.168.1.100:9080;
        server 192.168.1.101:9080;
        server 192.168.1.102:9080;
}

server {
        listen 9080;
        server_name api.abc.com;

        location / {
            proxy_pass http://APISIX;
        }
}
```
It can work, but to be honest, I'm not sure if this‘s the right thing to do, or if there's a mistake in understanding.

What are the best practices?

Thank you for your attention.

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Anolis OS 7.9
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4
- APISIX Dashboard version, if relevant: 2.13.0
- Plugin runner version, for issues related to plugin runners: -
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by tokers** [comment]
@saytesnake The nginx layer can be removed.

**Comment by kwanhur** [comment]
The critical point is that what's the scenario you face?

1. you should pay attention to which HA mode for the VIP at L4, like [Master/Slave](https://en.wikipedia.org/wiki/Master/slave_(technology))(e.g Keepalived+LVS) and [ECMP](https://en.wikipedia.org/wiki/Equal-cost_multi-path_routing)(e.g GoBGP+LVS).
2. how many layers[L4(e.g LVS)+L7(e.g APISIX)] do you need? Is one layer enough or are two layers better? 

- Does it need to split traffic via the Internet/Intranet with different layers? 
- What's the primary usage of the layer? like multi-entry points or SSL offload or Application Loadbalancer.

3. how many APISIX clusters you should have? Do they share the same ETCD cluster or integrate with different ETCD clusters?
