### ISSUE TITLE
request help: Nginx log management and cutting

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#860]
### Issue description

In a production environment, because access log files grow very fast, too large logs can seriously affect server efficiency. At the same time, in order to facilitate the analysis and calculation of the log, it is necessary to perform timing cutting on the log file. Timing cutting methods, including cutting by month, cutting by day, cutting by hour, etc.

### Environment

* apisix version (cmd: `apisix version`): 0.9 or higher
* OS: tlinux2.2

**Comment by membphis** [comment]
We can enable privilege process to do this.
Welcome PR.

**Comment by moonming** [comment]
It is best to discuss technical solutions on the mailing list.

**Comment by spacewander** [comment]
Solved.

**Comment by qwxingzhe** [comment]
现可通过插件支持：https://apisix.apache.org/docs/apisix/plugins/log-rotate
