### ISSUE TITLE
Java开发的多个external plugin 如何在配置文件中配置

### ISSUE THREAD

**Issue by 15349185792** [apache/apisix#8602]
### Description

Java开发的多个external plugin 如何在配置文件中配置ext-plugin.cmd

### Environment

- APISIX version 3.0
- docker 运行

**Comment by An-DJ** [comment]
You can use `-DAPISIX_LISTEN_ADDRESS=unix:/tmp/runner.sock` to specify different socket type files to different external plugins.

Then the plugins will create their own socket file automatically, so that you can write all of them into `config.yaml`.

Ref: https://apisix.apache.org/docs/java-plugin-runner/how-it-works/

**Comment by An-DJ** [comment]
@15349185792 Do you mean how to configure multiple external plugins to a single route?

**Comment by 15349185792** [comment]
@An-DJ 不是，是在config.yaml中如何配置多个java自定义插件

**Comment by An-DJ** [comment]
@15349185792 
The section `ext-plugin` in config.yaml is used to config the external plugin runner. 

Your custom plugins can be implemented in the java-plugin-runner, so you do not need to configure with `config.yaml`.

**Comment by 15349185792** [comment]
@An-DJ 我在官网看 是需要把自定义java插件在config,yaml中进行配置的
![image](https://user-images.githubusercontent.com/50066683/210937200-e62ea096-a797-4800-8cb8-8c703806c8f6.png)
，不然apisix如何发现java插件呢？

**Comment by An-DJ** [comment]
> @An-DJ 我在官网看 是需要把自定义java插件在config,yaml中进行配置的 ![image](https://user-images.githubusercontent.com/50066683/210937200-e62ea096-a797-4800-8cb8-8c703806c8f6.png) ，不然apisix如何发现java插件呢？

@15349185792 The `plugin runner` handles the RPC call from APISIX, creates a fake request at its side, runs external `plugins` and returns the result back to APISIX.

So if you have implemented multiple external plugins in java-plugin-runner, you only need to configure that runner into the config.yaml, just like you mentioned above. Actually the cmd in `ext-plugins` is the real command of how to start this runner.

Ref: https://apisix.apache.org/docs/apisix/external-plugin/

**Comment by 15349185792** [comment]
下面的图是配置一个java插件，那如果配置多个java插件呢？
![image](https://user-images.githubusercontent.com/50066683/210949492-8738091e-7205-4f62-9248-3c8aea9a53dd.png)

**Comment by An-DJ** [comment]
> 下面的图是配置一个java插件，那如果配置多个java插件呢？ ![image](https://user-images.githubusercontent.com/50066683/210949492-8738091e-7205-4f62-9248-3c8aea9a53dd.png)

This is how to configure a `plugin-runner`, not a external `plugin`.

Do you mean how to configure multiple `plugin-runners`?

**Comment by 15349185792** [comment]
@An-DJ 是的 不好意思，我刚开始描述错了，我实际问的是`plugin-runner`

**Comment by An-DJ** [comment]
Now the `ext-plugin` can configure only one external plugin-runner.

@15349185792 Could you plz explain why you need to use multiple plugin-runners?

**Comment by 15349185792** [comment]
@An-DJ 非常感谢你的耐心回答！我只是猜测可能会有这类使用场景。
