### ISSUE TITLE
bug: kafka old topic repeat to create after I change kafka_topic config

### ISSUE THREAD

**Issue by tanjiancheng** [apache/apisix#8605]
### Current Behavior

![image](https://user-images.githubusercontent.com/7401570/210507938-fd075184-e9d5-4f17-b3e4-bb2bf1aa6235.png)
log3 is on used，after I delete log1,log2,log3,and request the http api the first time，all topic create again
![image](https://user-images.githubusercontent.com/7401570/210508035-933c3bb0-65a3-4128-ac3e-d52329a6e8b5.png)
it still auto create log1，log2 topics that I use before，the right way is just auto create log3

### Expected Behavior

just auto create  topic log3 

### Error Logs

no

### Steps to Reproduce

change kafka_topic repeatedly and save

### Environment

- APISIX version (3.1.0-debian)
- apisix-dashboard (2.15.0-alpine)

**Comment by tokers** [comment]
Did you have a few requests to APISIX before you edited the topic? Since the log sending is async, a batch of log entries might be sent to the old topic.

**Comment by tanjiancheng** [comment]
> Did you have a few requests to APISIX before you edited the topic? Since the log sending is async, a batch of log entries might be sent to the old topic.

no，i stop request long time，and I try to delete the kafka-plugin and create again，still happen this problem

**Comment by tanjiancheng** [comment]
by the way，the other problem is after auto create topic（if the kafka set the config auto.create.topics.enable=true）,it will miss the first message send to kafka

**Comment by tokers** [comment]
Is it possible to provide a minimum reproducible case?

**Comment by tanjiancheng** [comment]
> Is it possible to provide a minimum reproducible case?

easy to show it！
first
![image](https://user-images.githubusercontent.com/7401570/210732058-50ee15e6-1bdd-457e-9410-bdebb68cc393.png)
and request api, it will auto create topic log4,
then back to change and save
![image](https://user-images.githubusercontent.com/7401570/210732303-ba3db5e5-d7fd-488b-98a6-2a0e2aec7381.png)
and request api, it will auto create topic log5,
then i delete the log4 and log5 topic
![image](https://user-images.githubusercontent.com/7401570/210732477-97625719-9789-46ec-bfba-9c0f8c11bc0c.png)
![image](https://user-images.githubusercontent.com/7401570/210732496-58cb8a1c-0839-4b26-8754-4f5eccb648d9.png)
and request api, log4 and log5 happen again
![image](https://user-images.githubusercontent.com/7401570/210732825-2e8525c7-0510-4dc6-a9a9-370c6f948a80.png)
the right result is just happen topic log5
