### ISSUE TITLE
希望能支持从请求体中进行条件过滤来进行灰度转发

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#8621]
### Description

我的接口都是跑了很久的json请求，无法改造请求或增加请求头；所以希望能从请求体的json中判断用户身份或用户账号来进行灰度；不知道traffic-split这种插件是否能支持，或者改造支持呢

**Comment by swtseaman** [comment]
比如：
http body :  {"userId": "u00001"}

希望插件能提取userId，或者哪怕是判断整个body里有没有包含u00001，就进行灰度转发

**Comment by swtseaman** [comment]
请问vars对象如何获取body呢，有没有 filter_func 或者 vars相关的文档呢？ 我还看了api/lua-resty-expr的相关文档，也没有介绍

**Comment by monkeyDluffy6017** [comment]
```
function(vars)
    local core = require ('apisix.core')
    local body, err = core.request.get_body()
    if not body then
        return false
    end
  
    local data, err = core.json.decode(body)
    if not data then
        return false
    end
  
    if data['foo'] == 'bar' then
        return true
    end
  
    return false
  end
```

**Comment by swtseaman** [comment]
感谢，请问有没有关于apisix.core的更详细的文档呢？

我刚刚尝试这样做也可以

` "filter_func": "function(vars) ngx.req.read_body() ngx.log(ngx.ERR, ngx.req.get_body_data()) return string.find(ngx.req.get_body_data(), \"swtseaman\") end"`

**Comment by swtseaman** [comment]
另外我还希望我的判断关键词是通过专门的配置来实现，而不是通过修改filter_func代码的方式，因为这样做风险较高；请问是不是通过插件的形式更为合理呢？

**Comment by monkeyDluffy6017** [comment]
> 请问有没有关于apisix.core的更详细的文档呢
Please check the code directly: https://github.com/apache/apisix/tree/master/apisix/core

**Comment by monkeyDluffy6017** [comment]
Maybe you could try apisix vars: https://apisix.apache.org/docs/apisix/apisix-variable/.
I didn't test, you could have a try

**Comment by swtseaman** [comment]
@monkeyDluffy6017 请问filter_func可以读取到APISIX Dashboard配置的Protocol Buffers内容吗

**Comment by monkeyDluffy6017** [comment]
> 请问filter_func可以读取到APISIX Dashboard配置的Protocol Buffers内容吗

Why need this?

**Comment by swtseaman** [comment]
> 

我希望实现判断内容可配置，所以需要有一个地方可以配置我的filter_func的过滤内容

**Comment by monkeyDluffy6017** [comment]
I think it will work, you could have a test

**Comment by swtseaman** [comment]
> I think it will work, you could have a test

可是我不知道怎么读取，请问有文档或读取代码示例吗？

**Comment by monkeyDluffy6017** [comment]
No different from other calls to pb in apisix

**Comment by monkeyDluffy6017** [comment]
considered resolved
