### ISSUE TITLE
help request: can not get response body in the body_filter on my custom plugin

### ISSUE THREAD

**Issue by showcup** [apache/apisix#8622]
### Description

Can not get response body in the body_filter on my custom plugin，The following code is in body_filter:
```
function _M.body_filter(conf,ctx)
    local final_body = core.response.hold_body_chunk(ctx)
    if not final_body then
        core.log.warn(' response body is nil')
        return
    end
    --final_body = transform(final_body)
    ngx.arg[1] = final_body
end
```
final_body is nil when it runs, I want to transform response , these codes refer to the response-rewrite plugin.  In response-rewrite, response body can be modified through filters, but respone body cannot be obtained in my custom plugin please help me!

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): apisix docker
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Do you have any other plugins use `core.response.hold_body_chunk` before your custom plugin

**Comment by monkeyDluffy6017** [comment]
I think you shoud add a log in `core.response.hold_body_chunk`, and check if the function is called several times.

**Comment by showcup** [comment]
> I think you shoud add a log in `core.response.hold_body_chunk`, and check if the function is called several times.

Thank you. I'll try

**Comment by monkeyDluffy6017** [comment]
@showcup if the log is printed twice, it means that you have called `core.response.hold_body_chunk` twice, that's the reason why you can not get the response body

**Comment by monkeyDluffy6017** [comment]
considered resolved
