### ISSUE TITLE
help request: how to use fixed values as response content

### ISSUE THREAD

**Issue by chenyyyang** [apache/apisix#8626]
### Description

APISIX_VERSION=2.11.0
the method from the below picture seems not work...Could you give more advise
![image](https://user-images.githubusercontent.com/22273370/210939290-5d4c9eed-757b-4645-bafc-51abf124bdab.png)

**Comment by ronething** [comment]
@chenyyyang Hi, where is your pic come from? And if you want to return fixed_value, you can use `response-write` plugin. 

refer: https://apisix.apache.org/docs/apisix/plugins/response-rewrite/

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/hello",
    "plugins": {
        "response-rewrite": {
            "body": "Hello, World!"
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}'
```

**Comment by chenyyyang** [comment]
@ronething  thank you for your response.
The pic is generated via asking ChatGPT from OpenAI's website...

Is there another way due to the priority of response-write (899) is much bigger than my self-devloped plugin?
Since i can not change the priority.

**Comment by ronething** [comment]
Maybe you can try `serverless-post-function` plugin, refer: https://apisix.apache.org/docs/apisix/plugins/serverless/

```
$ curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "plugins": {
        "serverless-post-function": {
            "phase": "rewrite",
            "functions" : ["return function(conf, ctx) return 200, \"Hello, World!\" end"] 
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}'
```

**Comment by chenyyyang** [comment]
@ronething  Good job!many thanks.
