### ISSUE TITLE
feat: As a user, I want to use authentication plugins in conjuction with other plugins, so that user identity would be available as a variable for other plugins

### ISSUE THREAD

**Issue by tellim** [apache/apisix#8629]
### Description

A typical use case would be the oidc plugin to work with the limit-* plugins.

A token field extractor would allow to retrieve desired user information from access token e.g. access_token.email or access_token.username and that information could be used in variables or variable combinations to create configs for these plugins.

Figures could also be retrieved from the access token whith varying oauth2 scopes allowing to setup customed user limitations on the IDP side.

**Comment by spacewander** [comment]
We already include the ID token & userinfo in the request: https://github.com/apache/apisix/blob/37f6f81a1a9c18895db1c61cca62785980fe9d10/apisix/plugins/openid-connect.lua#L353

So now what we need is to have a mechanism to decode them and fetch the sub-field in them.

**Comment by tokers** [comment]
Besides the OIDC, do you have any other scenarios? @tellim

**Comment by tellim** [comment]
@tokers not really though I spoke of authentication plugins as whole, so maybe look into providing a common authenticated identity interface that each auth plugin could implement.

**Comment by tokers** [comment]
> @tokers not really though I spoke of authentication plugins as a whole, so maybe look into providing a common authenticated identity interface that each auth plugin could implement.

Fair enough. A common mechanism is good, and then we can design the passed data for each authentication plugin.
