### ISSUE TITLE
feat: As a user, I want to port APISIX core to RISC-V architecture. So that SiFive Unmatched/VisionFive users can run apisix as web gateway..

### ISSUE THREAD

**Issue by hanf2x** [apache/apisix#8630]
### Description

A typical use case would be the a RISCV ISA based dual socket server running apisix as a load balancer.

RISC-V is no longer a small ISA, as qualcomm and other MCU vendor switching from arm to RISC-V. We speculate that RISC-V can be free and high performance with the potential to become an enterprise server SOC.

The foreseeable challenges are unknown, as little support was provided on the base nginx and openresty. But I hope that the base functions can work as a demo.

**Comment by spacewander** [comment]
> I want to port APISIX core to RISC-V architecture

What's your plan to work on this?

**Comment by spacewander** [comment]
Got it
