### ISSUE TITLE
help request: 如何用skywalking插件记录tag以便于进行相关业务统计

### ISSUE THREAD

**Issue by guochunyang2004** [apache/apisix#8631]
### Description

help request: 如何用skywalking插件记录tag以便于进行相关业务统计

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners: skywalking
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
@guochunyang2004 Do you mean inserting tags into all the traces through APISIX?

**Comment by An-DJ** [comment]
The only attribute that can be configured is `sample_ratio`.

Ref: https://apisix.apache.org/docs/apisix/plugins/skywalking/#attributes

Do you mean add more custom tags to the traces? Or Could you show your use case?

**Comment by guochunyang2004** [comment]
> @guochunyang2004 Do you mean inserting tags into all the traces through APISIX?

Yes,you are right.

**Comment by guochunyang2004** [comment]
> The only attribute that can be configured is `sample_ratio`.
> 
> Ref: https://apisix.apache.org/docs/apisix/plugins/skywalking/#attributes
> 
> Do you mean add more custom tags to the traces? Or Could you show your use case?

yes,I want to add more custom tags.

**Comment by guochunyang2004** [comment]
已找到办法，修改了apisix的skywalking插件源码。
