### ISSUE TITLE
help request: 2.x stable version and 3.x latest version, whether etcd data is compatible

### ISSUE THREAD

**Issue by marchlhw** [apache/apisix#8634]
### Description

1、2.x稳定版和3.x最新版，etcd数据是否兼容，有没有经过验证，我已经发现有些插件的scheme有更新
2、代理缓存插件的Apisix-Cache-Status响应头是否能自定义修改

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): centos7.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
https://github.com/apache/apisix/blob/master/docs/en/latest/upgrade-guide-from-2.15.x-to-3.0.0.md

**Comment by monkeyDluffy6017** [comment]
> 代理缓存插件的Apisix-Cache-Status响应头是否能自定义修改

The response header `Apisix-Cache-Status` is hard coded. Maybe you could modify the plugin and expose the response header

**Comment by qihaiyan** [comment]
The key ```ssl``` in etcd has been changed to ```ssls```

**Comment by shreemaan-abhishek** [comment]
Please refer to the upgrade guide: https://github.com/apache/apisix/blob/master/docs/en/latest/upgrade-guide-from-2.15.x-to-3.0.0.md
