### ISSUE TITLE
关于原生插件开发

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#8636]
### Description

看了很多文档和视频，都是关于依赖plugin runner，使用python、go、java来开发插件的。
不知道使用这种方式对apisix的性能影响有多少？更希望采用原生lua方式开发插件，看了文档 https://apisix.apache.org/zh/docs/apisix/plugin-develop/
这个文档对lua文件具体地址，插件的具体开发方式描述的内容不够具体，请问有没有更具体的开发文档；

比如：
1、插件开发模板（example项目，可以直接参照的）
2、有没有自定义插件的默认存放地址，直接放到具体地址即可（是否必须配置 apisix -> extra_lua_path）
3、如何启用自定义插件，是否需要在 conf/config-default.yaml 的plugins节点添加自定义插件
4、自定义插件如何添加到 apisix dashboard来进行界面化配置

**Comment by tokers** [comment]
> 1、插件开发模板（example项目，可以直接参照的）

Maybe you can checkout some built-in plugins in this repo directly.

> 2、有没有自定义插件的默认存放地址，直接放到具体地址即可（是否必须配置 apisix -> extra_lua_path）
Yes you need to configure the `extra_lua_path` field.

> 3、如何启用自定义插件，是否需要在 conf/config-default.yaml 的plugins节点添加自定义插件

Yes.

> 4、自定义插件如何添加到 apisix dashboard来进行界面化配置

@bzp2010 Could you answer this? Thanks!

**Comment by swtseaman** [comment]
> > 1、插件开发模板（example项目，可以直接参照的）
> 
> Maybe you can checkout some built-in plugins in this repo directly.
> 
> > 2、有没有自定义插件的默认存放地址，直接放到具体地址即可（是否必须配置 apisix -> extra_lua_path）
> > Yes you need to configure the `extra_lua_path` field.
> 
> > 3、如何启用自定义插件，是否需要在 conf/config-default.yaml 的plugins节点添加自定义插件
> 
> Yes.
> 
> > 4、自定义插件如何添加到 apisix dashboard来进行界面化配置
> 
> @bzp2010 Could you answer this? Thanks!

extra_lua_path应该怎么配置，是不是  /data/customer/lua_plugins
然后我把插件文件 body_plugin.lua 放到 /data/customer/lua_plugins
然后再到 conf/config-default.yaml的plugin节点添加 body-plugin 
然后重启apisix
最后用api给路由添加这个插件就可以了？

**Comment by swtseaman** [comment]
另外我还想请教下，添加原生lua插件，和使用plugin-runner开发其他语言的插件，性能损耗大不大，有没有相关测试数据呀

**Comment by swtseaman** [comment]
找到方法了，方法分享一下：

1、按照文档开发插件 xxx.lua
2、将xxx.lua放到apisix容器的/usr/local/apisix/apisix/plugins/
```
docker cp xxx.lua docker-id:/usr/local/apisix/apisix/plugins/
```
3、修改apisix_conf/config.yaml， 新增配置
```
plugins:
  - xxx
```
4、重启apisix 
```
docker  restart docker-id
```
5、导出schema.json
```
curl localhost:9092/v1/schema > schema.json
```
6、将schema.json放到apisix-dashboard的覆盖原配置
```
docker cp schema.json docker-id:/usr/local/apisix-dashboard/conf/
```
7、重启 dashboard
```
docker restart dashboard-id
```
之后就可以在dashboard后台新建或修改路由，选择自定义插件了

**Comment by xk-ai** [comment]
> 找到方法了，方法分享一下：
> 
> 1、按照文档开发插件 xxx.lua 2、将xxx.lua放到apisix容器的/usr/local/apisix/apisix/plugins/
> 
> ```
> docker cp xxx.lua docker-id:/usr/local/apisix/apisix/plugins/
> ```
> 
> 3、修改apisix_conf/config.yaml， 新增配置
> 
> ```
> plugins:
>   - xxx
> ```
> 
> 4、重启apisix
> 
> ```
> docker  restart docker-id
> ```
> 
> 5、导出schema.json
> 
> ```
> curl localhost:9092/v1/schema > schema.json
> ```
> 
> 6、将schema.json放到apisix-dashboard的覆盖原配置
> 
> ```
> docker cp schema.json docker-id:/usr/local/apisix-dashboard/conf/
> ```
> 
> 7、重启 dashboard
> 
> ```
> docker restart dashboard-id
> ```
> 
> 之后就可以在dashboard后台新建或修改路由，选择自定义插件了

您好，我按照你的步骤，从第五步的时候开始出现问题，curl localhost:9092/v1/schema > schema.json，导出的shcema只有我新增的插件，我把原路径下的schema手动添加自定义的插件，把对应shema的json放进去，然后etcd莫名其妙异常崩溃，过一段时间才能正常启动，数据被自动清空。在这我有点几点疑惑，希望能帮忙解答
1.curl localhost:9092/v1/schema > schema.json  这个导出的是谁的数据，是apisix的数据还是dashboard的数据。端口选择
2.我不更新dashboard的schema，直接加完插件后，调用http://xxxx"xx/apisix/admin/routes/88,对外api添加路由，报错"error_msg": "invalid configuration: allOf 1 failed: value should match only one schema, but matches none，可我数据都是对，是我没更新schema的原因吗

**Comment by xk-ai** [comment]
我现在在config-defaul.yml修改后，有全部的信息的了，但现在更新重启后，dashboard还是没有对应插件，路由调用还是报"invalid configuration: allOf 1 failed: value should match only one schema, but matches none
