### ISSUE TITLE
./linux-install-openresty.sh: line 35: OPENRESTY_VERSION: unbound variable

### ISSUE THREAD

**Issue by cherishman2005** [apache/apisix#8650]
### Description

apisix version: apisix-release-3.0

```
apisix-release-3.0/utils# ./linux-install-openresty.sh

Hit:1 https://openresty.org/package/ubuntu focal InRelease
Hit:2 http://hk.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://hk.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://hk.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://hk.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists... Done
./linux-install-openresty.sh: line 35: OPENRESTY_VERSION: unbound variable
```

### Environment

ubuntu20.04
```
Linux ubuntu 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Fabriceli** [comment]
I think this script [linux_openresty_1_19_runner.sh](https://github.com/apache/apisix/blob/master/ci/linux_openresty_1_19_runner.sh) can help you

**Comment by spacewander** [comment]
You need to setup the env, like: https://github.com/apache/apisix/blob/cbf2297c86409fe373c5eb70922f58e6f448e41a/.github/workflows/code-lint.yml#L23

BTW, this script is only used in the CI, and should not be used separately.
