### ISSUE TITLE
bug: http://apisix-etcd:2379: failed to parse domain

### ISSUE THREAD

**Issue by MarkCupitt** [apache/apisix#8652]
### Current Behavior

APiSix, latest Version, installed on Kubernetes 1.26 via Helm Chart.

See this error in logs

```
2023/01/10 09:26:20 [warn] 69#69: *8442376 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:32:45 [warn] 54#54: *9029191 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:34:30 [warn] 67#67: *9098086 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:34:30 [warn] 98#98: *9098236 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
```
same error occurs if we set etcd url as `http://apisix-etcd.apisix.svc.cluster.local:2379` etcd exists and service name is correct. 

### Expected Behavior

Log entry should not appear

### Error Logs

API - 192.168.50.80 - - [10/Jan/2023:09:03:04 +0000] smarterfarm.billrush.work:20000 "GET /grasshopper/1.0/invoice/usage/a738978d-b249-4e27-9e71-0ad5d2afb374/Laboratory-Tests?startDate=2022-12-20&endDate=2023-01-19 HTTP/1.1" 401 0 0.009 "-" "PostmanRuntime/7.30.0" 10.152.183.237:8080 401 0.005 "http://smarterfarm.billrush.work:20000/grasshopper/1.0/invoice/usage/a738978d-b249-4e27-9e71-0ad5d2afb374/Laboratory-Tests?startDate=2022-12-20&endDate=2023-01-19"
2023/01/10 09:07:33 [warn] 69#69: *8038310 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
API - 192.168.50.80 - - [10/Jan/2023:09:08:34 +0000] smarterfarm.billrush.work:20000 "GET / HTTP/1.1" 404 47 0.000 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" - - - "http://smarterfarm.billrush.work:20000"
API - 192.168.50.80 - - [10/Jan/2023:09:08:35 +0000] smarterfarm.billrush.work:20000 "GET /favicon.ico HTTP/1.1" 404 47 0.000 "http://smarterfarm.billrush.work:20000/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" - - - "http://smarterfarm.billrush.work:20000"
API - 192.168.50.80 - - [10/Jan/2023:09:08:36 +0000] smarterfarm.billrush.work:20000 "GET / HTTP/1.1" 404 47 0.000 "https://www.google.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36" - - - "http://smarterfarm.billrush.work:20000"
2023/01/10 09:16:15 [warn] 69#69: *8380444 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:23:20 [warn] 88#88: *8442243 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
API - 192.168.50.80 - - [10/Jan/2023:09:23:32 +0000] - "\x05d\x05\xC9\x00\x00\x00\x006L\x05d\x05\xC9\x01\x00\x00\x00\xDE\x8E\x05d\x05\xC9\x02\x00\x00\x00\x9F\x84\x05d\x05\xC9\x03\x00\x00\x00wF\x05d\x05\xC9\x04\x00\x00\x00\x1D\x90\x05d\x05\xC9\x05\x00\x00\x00\xF5R\x05d\x05\xC9\x06\x00\x00\x00\xB4X\x05d\x05\xC9\x07\x00\x00\x00\x5C\x9A\x05d\x05\xC9\x08\x00\x00\x00\x19\xB9\x05d\x05\xC9\x09\x00\x00\x00\xF1{\x05d\x05\xC9" 400 229 0.163 "-" "-" - - - "://"
2023/01/10 09:26:20 [warn] 69#69: *8442376 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:32:45 [warn] 54#54: *9029191 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:34:30 [warn] 67#67: *9098086 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:34:30 [warn] 98#98: *9098236 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
2023/01/10 09:48:45 [warn] 106#106: *9029212 [lua] v3.lua:829: request_chunk(): http://apisix-etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer

### Steps to Reproduce

install latest apisix via helm

### Environment

- APISIX version apache/apisix:3.1.0-debian
- Operating system (run `uname -a`): Ubuntu 22.04LTS Kubernetes 1.26

Everything else as per helm chart

**Comment by kellyseeme** [comment]
in version 2.15.1,have the same problem.https://github.com/apache/apisix/issues/8713

**Comment by pengchuangchina** [comment]
in version 2.15.1,have the same problem.https://github.com/apache/apisix/issues/8713

**Comment by pengchuangchina** [comment]
Ihave the same problem. https://github.com/apache/apisix/issues/8713

**Comment by monkeyDluffy6017** [comment]
please refer to https://github.com/apache/apisix/issues/8800
