### ISSUE TITLE
bug: encrypt_conf(): failed to get schema for plugin: proxy-rewrite

### ISSUE THREAD

**Issue by MarkCupitt** [apache/apisix#8653]
### Current Behavior

```
API - 192.168.50.80 - - [11/Jan/2023:00:18:30 +0000] ops.billrush.co.nz "PUT /apisix/admin/upstreams/platform-tenant HTTP/1.1" 200 480 0.009 "-" "buckingbronco/1.0.0" - - - "http://ops.billrush.co.nz"
2023/01/11 00:18:32 [warn] 49#49: *43847430 [lua] plugin.lua:929: encrypt_conf(): failed to get schema for plugin: proxy-rewrite, client: 192.168.50.80, server: , request: "PUT /apisix/admin/routes/bounty-bonanza-system-info HTTP/1.1", host: "ops.billrush.co.nz"
```

Possibly related to this feature request

https://github.com/apache/apisix/pull/8403

### Expected Behavior

To not see this Warning

### Error Logs

```
API - 192.168.50.80 - - [11/Jan/2023:00:18:30 +0000] ops.billrush.co.nz "PUT /apisix/admin/upstreams/platform-tenant HTTP/1.1" 200 480 0.009 "-" "buckingbronco/1.0.0" - - - "http://ops.billrush.co.nz"
2023/01/11 00:18:32 [warn] 49#49: *43847430 [lua] plugin.lua:929: encrypt_conf(): failed to get schema for plugin: proxy-rewrite, client: 192.168.50.80, server: , request: "PUT /apisix/admin/routes/bounty-bonanza-system-info HTTP/1.1", host: "ops.billrush.co.nz"
```

### Steps to Reproduce

Install Latest APissix via Helm Chart

### Environment

- APISIX version (run `apisix version`): apache/apisix:3.1.0-debian
- Operating system (run `uname -a`): Ubuntu 22.04 Kubernetes 1.26

installed via Helm Chart

**Comment by tokers** [comment]
@MarkCupitt What does the route object look like?

**Comment by MarkCupitt** [comment]
@tokers her is the upstream and route json

```
{
  "name": "smarterfarm.billrush.work/smarterfarmnz-keycloak",
  "id": "smarterfarmnz-keycloak",
  "status": 1,
  "version": "v1.0.0",
  "desc": "All Routes for smarterfarmnz auth service",
  "labels": {
    "tenant": "smarterfarmnz",
    "route": "auth",
    "pod": "keycloak"
  },
  "uri": "/auth*",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE"
  ],
  "host": "smarterfarm.billrush.work",
  "upstream_id": "platform-keycloak",
  "enable_websocket": false,
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "add": {
          "x-Killbill-ApiKey": "xxxxxxxxx"
        }
      }
    }
  }
}
```

```
{
  "id": "platform-keycloak",
  "name": "platform-keycloak",
  "desc": "Upstream for keycloak-service.platform.svc.cluster.local:8080",
  "type": "roundrobin",
  "nodes": {
    "keycloak-service.platform.svc.cluster.local:8080": 1
  },
  "pass_host": "pass",
  "retries": 0,
  "retry_timeout": 0,
  "timeout": {
    "connect": 3,
    "send": 3,
    "read": 3
  },
  "labels": {
    "service": "platform-keycloak"
  }
}
```

**Comment by tokers** [comment]
@MarkCupitt First of all, this error message is harmless. It occurs since you don't enable the `apisix.data_encryption.enable` in your `config.yaml`.

On the other hand, we don't need to print such a message when users do not enable this feature. This is not an error.

**Comment by MarkCupitt** [comment]
Ok, thanks .. wil ignore it then .. appreciate the feedback

**Comment by spacewander** [comment]
> @MarkCupitt First of all, this error message is harmless. It occurs since you don't enable the `apisix.data_encryption.enable` in your `config.yaml`.
> 
> On the other hand, we don't need to print such a message when users do not enable this feature. This is not an error.

What about adding a wrapper to check the feature before logging?

**Comment by tokers** [comment]
> > @MarkCupitt First of all, this error message is harmless. It occurs since you don't enable the `apisix.data_encryption.enable` in your `config.yaml`.
> > On the other hand, we don't need to print such a message when users do not enable this feature. This is not an error.
> 
> What about adding a wrapper to check the feature before logging?

Agree +1.

**Comment by Hazel6869** [comment]
@tokers can you assign it to me？

**Comment by NivHamisha** [comment]
Hey there, 
Where are we standing with the feature flag wrapper? 
Those logs are spamming us 😢

**Comment by abs007** [comment]
Is the issue still open for contribution? I'd like to have a go at this, thanks.

**Comment by monkeyDluffy6017** [comment]
hi @abs007, this issue is fixed by https://github.com/apache/apisix/pull/9057
