### ISSUE TITLE
help request: apisix dashboard grafana不能选择节点

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#8654]
### Description

apisix dashboard配置好了grafana，也确实有数据；但是无法对service | route | instance | consumer | node 进行筛选，都只显示一个all；请问是不是哪里还需要配置或者同步数据给grafana

<img width="2059" alt="image" src="https://user-images.githubusercontent.com/4599375/211711091-770af349-c163-41d7-aa68-88d80100892f.png">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Fabriceli** [comment]
Make sure you have enable Prometheus plugin in global:
![image](https://user-images.githubusercontent.com/13508022/211763343-830d2ae4-304d-40ef-8e7e-2642fa427619.png)

**Comment by swtseaman** [comment]
> Make sure you have enable Prometheus plugin in global: ![image](https://user-images.githubusercontent.com/13508022/211763343-830d2ae4-304d-40ef-8e7e-2642fa427619.png)

请问开启后还需要其他配置吗？我现在已经开启了，但是grafana里还是只有 all  选项

**Comment by swtseaman** [comment]
产生请求后就有了，谢谢！
