### ISSUE TITLE
help request: Whether there is an image of apisix-base to connect to the etcd with tls

### ISSUE THREAD

**Issue by huweihuang** [apache/apisix#8656]
### Description

Whether there is an image of apisix-base to connect to the etcd with tls

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
@huweihuang Do you mean docker image?

So far the official docker images published on DockerHub are all build with apisix-base.

You can use the features relying on the apisix-base directly. : )
