### ISSUE TITLE
docs: error link about nacos deployment tutorial in apisix-seed page

### ISSUE THREAD

**Issue by ronething** [apache/apisix#8657]
### Current State

https://apisix.apache.org/docs/apisix/discovery/control-plane-service-discovery/#supported-service-registry

If you want to enable control plane Nacos service discovery, please refer to: [Nacos Deployment Tutorial](https://github.com/api7/apisix-seed/blob/main/docs/en/latest/zookeeper.md).

it links to the zookeeper deployment tutorial.

### Desired State

If you want to enable control plane Nacos service discovery, please refer to: [Nacos Deployment Tutorial](https://github.com/api7/apisix-seed/blob/main/docs/en/latest/nacos.md).

**Comment by juzhiyuan** [comment]
Thanks for the report! Would you like to update it?

You can update it here: https://github.com/apache/apisix/edit/release/3.1/docs/en/latest/discovery/control-plane-service-discovery.md

**Comment by e1ijah1** [comment]
I'd like to help with this issue.

**Comment by shreemaan-abhishek** [comment]
This can be closed now.
