### ISSUE TITLE
help request: sourceCode deployment on macOS M1

### ISSUE THREAD

**Issue by bigbug-dachong** [apache/apisix#8664]
### Description

i have a problem when i start apisix-server by sourceCode-deployment

env：
macOS M1

refer to：
https://apisix.apache.org/zh/docs/apisix/building-apisix/

steps：
1、get all deps — ok
2、download sourceCode — ok
3、make deps — ok
4、make install — failed， cause the macOS dirRights。
so i directly run /apisix/bin/apisix start.
but the server doesn’t run succ.

the error-log show:
`2023/01/10 17:09:59 [error] 3666#793558: init_worker_by_lua error: ...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: NYI: cannot call this C function (yet) stack traceback: [C]: in function 'ngx_lua_ffi_shdict_get' ...Cellar/openresty/1.21.4.1_1/lualib/resty/core/shdict.lua:320: in function 'get' ...pisix-2.15.1//deps/share/lua/5.1/resty/worker/events.lua:119: in function 'get_event_id' ...pisix-2.15.1//deps/share/lua/5.1/resty/worker/events.lua:610: in function 'configure' ...ithub/apisix-latest/apache-apisix-2.15.1/apisix/init.lua:113: in function 'http_init_worker' init_worker_by_lua:2: in main chunk`

### Environment

- APISIX version (run `apisix version`): 3.1
- 
- Operating system (run `uname -a`):MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0
- 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
nginx version: openresty/1.21.4.1
built by clang 13.1.6 (clang-1316.0.21.2.5)
built with OpenSSL 1.1.1n  15 Mar 2022

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.5
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):3.9.1

**Comment by soulbird** [comment]
see: #7313
