### ISSUE TITLE
同一个Consumer，如何限制只能访问路由A，而不能访问路由B

### ISSUE THREAD

**Issue by heichong** [apache/apisix#8667]
### Description

# 创建一个Consumer
```
{
  "username": "helloConsumer",
  "desc": "hello消费者",
  "plugins": {
    "key-auth": {
      "disable": false,
      "key": "1234567890"
    }
  }
}
```

# 创建Router A

```
{
  "uri": "/test1/**",
  "name": "hello",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "key-auth": {
      "disable": false,
      "header": "token"
    },
    "proxy-rewrite": {
      "regex_uri": [
        "^/test1/(.*)",
        "/$1"
      ]
    }
  },
  "upstream_id": "442135180308644824",
  "status": 1
}
```

# 创建 Router B

```
{
  "uri": "/test2/*",
  "name": "test2",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "key-auth": {
      "disable": false,
      "header": "token"
    },
    "proxy-rewrite": {
      "regex_uri": [
        "^/test2/(.*)",
        "/$1"
      ]
    }
  },
  "upstream_id": "442135180308644824",
  "status": 1
}
```

# 问题

我应该怎么处理，才能让helloConsumer 只能访问Router A，而不能访问Router B

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jagerzhang** [comment]
可以在路由配置的插件节点插入 consumer-restriction 这个插件配置，示例如下：
```
"plugins": {
    "consumer-restriction": {
      "disable": false,
      "rejected_code": 403,
      "type": "consumer_name",
      "whitelist": [  // 这里指定能访问的白名单，当然这个插件还支持黑名单，具体看下帮助文档 
        "helloConsumer"  
      ]
    }
}
```

**Comment by heichong** [comment]
> 可以在路由配置的插件节点插入 consumer-restriction 这个插件配置，示例如下：
> 
> ```
> "plugins": {
>     "consumer-restriction": {
>       "disable": false,
>       "rejected_code": 403,
>       "type": "consumer_name",
>       "whitelist": [  // 这里指定能访问的白名单，当然这个插件还支持黑名单，具体看下帮助文档 
>         "helloConsumer"  
>       ]
>     }
> }
> ```

好的，明白了，感谢!
