### ISSUE TITLE
feat: For clickhouse logger to support include req and response body option

### ISSUE THREAD

**Issue by gaoxingliang** [apache/apisix#8670]
### Description

I want to track all the api requests and response to the clickhouse database.
And I found the clickhouse logger doesn't support this.
https://apisix.apache.org/docs/apisix/plugins/clickhouse-logger/
I think we only need to add two / three lines at:
https://github.com/apache/apisix/blob/master/apisix/plugins/clickhouse-logger.lua#L36
and adding:
```
        include_req_body = {type = "boolean", default = false},
        include_resp_body = {type = "boolean", default = false},
```
and change related doc stuff. (I don't know the lua script before. Just reading the code.)

**Comment by An-DJ** [comment]
I found that other Loggers (such as [kafka-logger](https://apisix.apache.org/docs/apisix/plugins/kafka-logger/)) contain not only `include_req_body` and `include_resp_body`, but also `include_req_body_expr` and `include_resp_body_expr` for filtering.

It seems like a meaningful use scenario for clickhouse-logger.

CC @spacewander Should the implementation of their expr be added in the meantime?

**Comment by spacewander** [comment]
LGTM

**Comment by pixeldin** [comment]
This seems to be a familiar feature implemented in `file-logger`, maybe I can try it, can you assign it to me?
