### ISSUE TITLE
help request: how to modify skywalking component value

### ISSUE THREAD

**Issue by jujiale** [apache/apisix#8671]
### Description

Hello:

  we use skywalking plugin in apisix 2.12. we config the follwing attr in config.yaml. it works well
`

    plugin_attr:
      skywalking:
        service_name: our own service_name
        service_instance_name: our own Instance Name
        endpoint_addr: http://127.0.0.1:12800

`

and what we get in skywalking is following picture.
![image](https://user-images.githubusercontent.com/48037235/212037019-d293025e-1975-4f5c-8d0d-708adae619d8.png)

**we want to modify "Componet" value to our own identify lable(such as: Component: APISIX  ->  Component: My Own)**. what should I do to achieve this. I read /plugins/skywalking.lua code. but I nerver find how to modify it.

thanks

### Environment

- APISIX version (run `apisix version`):2.12
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
seems you need to set component id, refer: 

- https://github.com/apache/apisix/issues/4059
- https://github.com/apache/skywalking/pull/6757

**Comment by jujiale** [comment]
> seems you need to set component id, refer:
> 
> * [request help: add APISIX plugin component id for skywalking #4059](https://github.com/apache/apisix/issues/4059)
> * [[plugin] add APISIX plugin component id skywalking#6757](https://github.com/apache/skywalking/pull/6757)

get it! thank you very much.
