### ISSUE TITLE
feat: As a user, I want to support send error-log to kafka, so that we can get error logs from kafka

### ISSUE THREAD

**Issue by starsz** [apache/apisix#8678]
### Description

Hi, folks.

Now I found that we only support sending error log to `tcp server` , `skywalking`, `clickhouse ` .
I want to support sending error log to kafka, so that we can collect `access log` and `error log` via kafka.

refer: https://apisix.apache.org/docs/apisix/2.13/plugins/error-log-logger/

**Comment by ronething** [comment]
@starsz i will try this, please assign to me.

**Comment by starsz** [comment]
> @starsz i will try this, please assign to me.

Nice, look forward to this feature.
