### ISSUE TITLE
help request: 是否有文档可以指导实现多环境

### ISSUE THREAD

**Issue by JohnQI8888** [apache/apisix#8680]
### Description

我们有多套环境， 我们希望在入口流量上 打上一个标签，让apisix 可以按照流量标签 分流。

比如 http 请求头里 包含 host: www.a.com 加上  ”env: env-1"   流量进去  192.168.2.1 实例
比如 http 请求头里 包含 host: www.a.com 加上  ”env: env-1"   流量进去  192.168.2.2 实例
比如 http 请求头里 包含 host: www.a.com 没有其他 标签         流量进去  192.168.2.3 实例

这样的功能， 该怎么样利用apisix 实现

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
maybe you need traffic-split plugin?

refer: https://apisix.apache.org/docs/apisix/plugins/traffic-split/

**Comment by JohnQI8888** [comment]
支持  /* 这样的通配符吗？

**Comment by ronething** [comment]
>   支持  /* 这样的通配符吗？

you can have a try

**Comment by JohnQI8888** [comment]
> > 支持  /* 这样的通配符吗？
> 
> you can have a try

Thanks for help, and another problem is we still work in apisix 1.6.x,  I don't think it can work for us.

**Comment by shreemaan-abhishek** [comment]
@JohnQI8888 apisix v1 isn't supported anymore. Please reopen this issue if you have further questions.
