### ISSUE TITLE
bug: apisix 3.x lost config cache values after etcd compacted

### ISSUE THREAD

**Issue by zlhgo** [apache/apisix#8682]
### Current Behavior

https://github.com/apache/apisix/blob/df1cadb27744234f2f9fe6b6bfa5ea18442fb8e6/apisix/core/config_etcd.lua#L370

Perhaps should be 
```lua
local dir_res, headers = res.body.node or {}, res.headers
```

#8675 has the same problem.

### Steps to Reproduce

1.
```bash
etcdctl compact `etcdctl get -w json /apisix/upstreams/ | jq .header.revision`
```
Perhaps this command should be run multiple times.
2. do not update related keys, for example global_rules.
3. wait a moment, the global plugins not working.

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zlhgo** [comment]
@tokers 为啥就没人理我呢。

**Comment by spacewander** [comment]
There are some paths that reloaded data may be in res.body.node
Try to fix it via https://github.com/apache/apisix/pull/8736
