### ISSUE TITLE
Block IP for certain time if it hit error status code limit

### ISSUE THREAD

**Issue by aswarcewicz** [apache/apisix#8683]
### Description

I would like to ask is it possible to block IP address for certain time if it hit configured number of errors from remote service.

For example:
User try to make SQL Injection. 
Service returns response code 500
After 10 attempts to hack my service I would like to globally block User IP Address for 1 hour.

One other requirment - I would like to combine this rule with existing limit-count plugin. 
I already have global limit-count per IP configured

**Comment by tokers** [comment]
Currently not. strategies cannot be tweaked dynamically.

**Comment by aswarcewicz** [comment]
Maybe there are any plans to support this scenario?
It will be helpful in other cases too.
For example when malicious user try to BruteForce password.
With this functionality we can be block this user and prevent attack.

**Comment by tokers** [comment]
@aswarcewicz For your case, it could be implemented out of the APISIX. You may set up a feedback system that checks the access logs and invokes APISIX Admin API to tweak the plugin.

**Comment by aswarcewicz** [comment]
ok, thank you for this workaround.
I hope some day this scenario wil be supported out of the box with APISIX :)
