### ISSUE TITLE
feat: support centOS7 for utils/linux-install-openresty.sh

### ISSUE THREAD

**Issue by uran0sH** [apache/apisix#8685]
### Description

When I run './linux-install-openresty.sh', I find that it doesn't support centOS7. I thought that it should support centOS7.

**Comment by Fabriceli** [comment]
Cloud you give more info? Error stack and version info

**Comment by uran0sH** [comment]
> Cloud you give more info? Error stack and version info

Error: apt-key: command not found
version: Linux localhost 3.10.0-1160.76.1.el7.x86_64

**Comment by ronething** [comment]
if you want to install dependencies for building apisix, you may use command like below.

```shell
$ ./utils/install-dependencies.sh  
```

file `utils/linux-install-openresty.sh` is just for ci which runs on ubuntu.

**Comment by tokers** [comment]
Maybe we can write some comments in `utils/linux-install-openresty.sh`, or just rename this file so that it would be more "dedicated".

**Comment by monkeyDluffy6017** [comment]
https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh

**Comment by spacewander** [comment]
I will rename this file as people keep asking similar question, like https://github.com/apache/apisix/issues/8650#issuecomment-1379669047

**Comment by uran0sH** [comment]
> 

I try this one. And I met a problem on CentOS7. And I also give a pr(https://github.com/api7/apisix-build-tools/pull/273) to fix the problem. So can someone help review it? Thanks

**Comment by uran0sH** [comment]
> https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh @uran0sH Could you try this?

I try this one. And I met a problem on CentOS7. And I also give a pr(https://github.com/api7/apisix-build-tools/pull/273) to fix the problem. So can someone help review it? Thanks
