### ISSUE TITLE
help request: 请问forward-auth插件服务超时状态码默认是403吗, 支持修改吗

### ISSUE THREAD

**Issue by youshaojun** [apache/apisix#8687]
### Description

APISIX_VERSION=3.0.0
配置forward-auth插件后, 认证服务超时APISIX forward-auth响应403状态码, 期望能支持配置为502状态码

### Environment

- APISIX version (run `apisix version`): 3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Yes, when the service times out, it should respond with 502
