### ISSUE TITLE
interface help!

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8690]
### Description

I want to know Whether there is an interface to add apisix users for login apisix-board,not only modify config file of /api/conf/conf.yaml .
（means that add a user to login apisix-board by apisix interface.  You can see what I mean！）

please help me! thanks

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Lanhild** [comment]
As far as I know there isn't.

**Comment by soulbird** [comment]
same as #8677
