### ISSUE TITLE
docs: ssl api wrong path

### ISSUE THREAD

**Issue by awx-tim-zhang** [apache/apisix#8692]
### Current State

The documentation(https://apisix.apache.org/docs/apisix/admin-api/#ssl-api) says ssl api locates in `/apisix/admin/ssls`, but it's actually `/apisix/admin/ssl`.

### Desired State

Update the document

**Comment by ronething** [comment]
maybe it don't need to update. because of apisix 3.x SSL resource prefix is `/apisix/admin/ssls`, which in apisix 2.x is `/apisix/admin/ssl`.

**Comment by juzhiyuan** [comment]
Thanks for update and check! The SSL APIs have been changed since v3.
