### ISSUE TITLE
[docs]: deployment-role.md is not exist

### ISSUE THREAD

**Issue by Fabriceli** [apache/apisix#8698]
### Current State

**Description of the current state/issue**:
1. open [set-up-multiple-ca-certificates](https://apisix.apache.org/docs/apisix/certificate/#set-up-multiple-ca-certificates]
2. click [Deployment Modes](https://apisix.apache.org/docs/apisix/certificate/architecture-design/deployment-role.md/)
**Link to the page**:
- https://apisix.apache.org/docs/apisix/architecture-design/deployment-role
- https://apisix.apache.org/docs/apisix/certificate/architecture-design/deployment-role.md/
**Screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/13508022/212796356-3c83fa8e-4069-4f70-90b3-bcb0e4469d6b.png)

### Desired State

**Description of the change you are proposing**:

### Would you like to fix this issue?

None

**Comment by SkyeYoung** [comment]
@SylviaBABY @yzeng25 Hi, do you have time to fix this?

**Comment by SylviaBABY** [comment]
> @SylviaBABY @yzeng25 Hi, do you have time to fix this?

will fix it this week, thanks for remind

**Comment by SkyeYoung** [comment]
fixed in #8714
