### ISSUE TITLE
if etcd is down,the apisix not affect service?

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8702]
### Description

if etcd cluster is down ,the apisix also can handle the requests?just affect if the apisix is restart or reload?how much time will be ok if etcd cluster down?

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
> if etcd cluster is down ,the apisix also can handle the requests

Yes, Just can't update the data anymore after the etcd cluster is down

**Comment by kellyseeme** [comment]
if etcd clsuter is down,the apisix is cache the configuretion ?if this is ,then apisix will have the cache time,so how much time will be affect if etcd cluster down?

**Comment by tokers** [comment]
> if etcd clsuter is down,the apisix is cache the configuretion ?if this is ,then apisix will have the cache time,so how much time will be affect if etcd cluster down?

Not cache, when ETCD cluster is down, the configuration snapshot would be in APISIX per-worker memory. It can always be used unless the worker process exited.
