### ISSUE TITLE
feat: As a user, I want file-logger plugin support record response body in a custom format, so that make the log format more flexible

### ISSUE THREAD

**Issue by mscb402** [apache/apisix#8705]
### Description

As a user, I would like the file-logger plugin to support logging the response body in a custom format to make the logging format more flexible. 
Currently the file-logger plugin supports logging the response body, but not logging the response in the way the user wants. 
So if the user configures the log format in meta. There will be no way to log the response body. Only clear log format in meta will be enabled.
So I want to add a new var `resp_body` to let the user put it in a log format which let the user use the response in the way there want. 
What do you think about this? If you think this is ok, pls assign me to add this feature.

**Comment by mscb402** [comment]
@tokers

**Comment by mscb402** [comment]
@spacewander

**Comment by spacewander** [comment]
LGTM

**Comment by gaoxingliang** [comment]
Hi @mscb402 Can we make this feature to other plugins? (eg clickhouse-logger, elastic-search logger.)  because this should be a common feature instead of dedicated to file logger plugin?

**Comment by mscb402** [comment]
> Hi @mscb402 Can we make this feature to other plugins? (eg clickhouse-logger, elastic-search logger.) because this should be a common feature instead of dedicated to file logger plugin?

OK， I will create a new pr to support this feature.
