### ISSUE TITLE
apisix 能否支持对管理人员更细粒度的授权

### ISSUE THREAD

**Issue by snail2sky** [apache/apisix#8708]
### Description

1. 目前只要能登陆到apisix的dashboard，那么就能操作dashboard的所有功能，这其实在生产环境中是很危险的，目前是否支持更细粒度的授权？
2. 其次，apisix到底是一个什么样的定位呢？到底是交给运维人员管理，还是交由研发管理？运维将所有的相关域名的流量直接打到研发的apisix中，让研发根据自己的需求做更细粒度的调度？能否给出几个最佳实践
3. 能否对相关的域名做批量替换upstream，主要指的是灾演情况

- 因为我是运维人员，从我的观点来看，apisix有点像网络架构中的接入层的交换机，而不是核心层的，apisix应该离realserver (apiserver) 很近，而且经常操作他的人应该是研发，而不是运维；当然运维也可以用apisix 做汇聚层、甚至是核心层的 nginx，但是不会针对 具体的 api进行转发，而只需要将域名的所有流量转发给研发的 apisix即可

**Comment by juzhiyuan** [comment]
1. APISIX Dashboard only supports admin account by default, it's a GUI to operate RESTful APIs. If you need more permissions, you have to develop your own dashboard IMO.

**Comment by snail2sky** [comment]
好的 感谢，以后有相关的开发计划吗？

**Comment by juzhiyuan** [comment]
https://apisix.apache.org/blog/2023/01/02/accessing_apisix-dashboard_from_everywhere_with_keycloak_authentication/

Here has one blog explaining that how to protect Dashboard via Keycloak :)

**Comment by snail2sky** [comment]
ok, thank you~



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月1日(周三) 上午8:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [apache/apisix] apisix 能否支持对管理人员更细粒度的授权 (Issue #8708)




 
https://apisix.apache.org/blog/2023/01/02/accessing_apisix-dashboard_from_everywhere_with_keycloak_authentication/
 
Here has one blog explaining that how to protect Dashboard via Keycloak :)
