### ISSUE TITLE
前后端跨域问题 CORS policy 

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8710]
### Description

1.新建路由 开启cors 插件
![image](https://user-images.githubusercontent.com/39228009/213349024-f88b54f9-3ba3-4f11-80b6-1638996545c7.png)

2.前后端分离项目,直接调用路由地址，google 浏览器 报跨域错误
![image](https://user-images.githubusercontent.com/39228009/213348858-40190bff-719f-4b95-a294-fe7393e95e3a.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Maybe you can set allow credentials to true.

**Comment by mscb402** [comment]
If still have a problem, you can set `Access-Control-Allow-Origin: http://domain.com`. Change  domain.com to your domain

**Comment by githubxubin** [comment]
> If still have a problem, you can set `Access-Control-Allow-Origin: http://domain.com`. Change domain.com to your domain

okey ~  thanks it is ok

**Comment by mscb402** [comment]
You can close this issue now :)
