### ISSUE TITLE
docs: consolidate deployment modes guides

### ISSUE THREAD

**Issue by navendu-pottekkat** [apache/apisix#8715]
### Current State

The [deployment modes documentation page](https://apisix.apache.org/docs/apisix/deployment-modes/) contains documentation about all the deployment modes. There is also another page for [stand-alone mode](https://apisix.apache.org/docs/apisix/stand-alone/) with just its documentation.

### Desired State

Instead, these two pages should be merged to a single page and moved out of the "Others" section.

**Comment by Neilblaze** [comment]
Taking this up!

**Comment by navendu-pottekkat** [comment]
@Neilblaze Could you please propose what you are planning to do before working on the issue? Let's get the goal clear and make sure they are aligned.

**Comment by Neilblaze** [comment]
Scraping out the entire content from the `stand-alone-mode` page & appending it to the `deployment modes documentation page` in the pre-existing `stand-alone` section at the bottom of the same. Then I'll shift the page outside of the "Others" section. Once done, I'll delete the single page which was initially preserved for `stand-alone` mode, as it's no longer required once merging of both is done!

P.S> There will be no change in the docs, since the file name remains the same. For example, the "Standalone" remains as `../../en/latest/deployment-modes.md#standalone`

**Comment by Neilblaze** [comment]
@navendu-pottekkat please review 🔝😄

**Comment by navendu-pottekkat** [comment]
@Neilblaze Sounds good. Where will we move it outside "Others"? It might be a difficult ask, so probably, we can keep it in  there right now and look at it in the future. // @juzhiyuan who else can provide some input here?

**Comment by Neilblaze** [comment]
> Where will we move it outside "Others"? 

I think a better approach will be keeping it seperate just like the FAQ section, which is outside of "others".

Would you mind having a look at my PR #8724?

**Comment by juzhiyuan** [comment]
> @Neilblaze Sounds good. Where will we move it outside "Others"? It might be a difficult ask, so probably, we can keep it in there right now and look at it in the future. // @juzhiyuan who else can provide some input here?

Hi @navendu-pottekkat and @Neilblaze 👋 I suggest combining the `Standalone` into the `Deployment Mode` page and removing the `standalone` page.

When developers use Google to search this, it may lead to 404 issues, but I can use Google Search Console to remove the history page.

**Comment by Neilblaze** [comment]
> I suggest combining the `Standalone` into the `Deployment Mode` page and removing the `standalone` page.

@juzhiyuan Thanks! I think, I did exactly what you mentioned in — #8724. Can you please have a look? 😄
Do lemme know if I need to change anything else on it!

**Comment by juzhiyuan** [comment]
Thanks for your PR! I will check tomorrow :)
