### ISSUE TITLE
help request: access logs can not delete

### ISSUE THREAD

**Issue by lifeblood** [apache/apisix#8717]
### Description

```
plugin_attr:
  log-rotate:
      interval: 76400    # rotate interval (unit: second)
      max_kept: 24     # max number of log files will be kept
      max_size: -1      # max size of log files will be kept
      enable_compression: false    # enable log file compression(gzip) or not, default false
```
access logs can not delete

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):Linux 172-16-5-11 6.0.1-1.el7.elrepo.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Oct 10 10:32:48 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.2 -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/stream --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../apisix-nginx-module-1.10.0/src/meta --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../wasm-nginx-module-0.6.3 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.ec7pjaeCNo/openresty-1.21.4.1/../grpc-client-nginx-module-v0.2.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"id":"57e1d8ad-d591-467c-b36c-dee53f3c3d67","hostname":"172-16-5-11","etcd_version":"3.5.0","version":"2.15.0","boot_time":1666176869}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by juzhiyuan** [comment]
Hi, thanks for your report, can you please provide your steps to reproduce this case?

**Comment by tokers** [comment]
> access logs can not delete

Could you let me know how you knew this? Do you see extra log files in your file system? In addition, do you see any related APISIX error log entries?

**Comment by shreemaan-abhishek** [comment]
@lifeblood, please resond.
