### ISSUE TITLE
help request: Routes returns timeout in high request

### ISSUE THREAD

**Issue by amyrprv** [apache/apisix#8721]
### Description

I have a scenario in which I have two upstreams and two routes associated with them.
one of the upstreams returns timeout and the other is working perfectly. when the routes are under high request it will corrupt the healthy route and it will return 504 or EADDRINUSE error. but under normal circumstances, both work correctly. and by correctly I mean one route returns timeout and the other returns its response.

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux 94747961c5e2 5.10.16.3-microsoft-standard-WSL2
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.15
- APISIX Dashboard version, if relevant: 2.15.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by abehnamfard** [comment]
same here

**Comment by mscb402** [comment]
I don't get it. Could you provide more detail about your problem? The health check may be what you want. https://apisix.apache.org/docs/apisix/tutorials/health-check/

**Comment by abehnamfard** [comment]
Thank you for your response.
Let me explain my problem with an example.
I have two upstreams A & B.
A response in no time and it is very fast.
But B is kind of slow and on high-load requests, it takes about 60 seconds to respond.
My problem is when I have too many requests for B upstream it affects A requests and makes them slow.
@mscb402

**Comment by mscb402** [comment]
Can you share your JSON config about the upstream/route for us?

**Comment by abehnamfard** [comment]
A upstream: 
`{
  "nodes": [
    {
      "host": "172.18.26.6",
      "port": 3001,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "OK upstream",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}`
A route:
`{
  "uri": "/ok",
  "name": "ok route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "uri": "/"
    }
  },
  "upstream_id": "444634001206936085",
  "status": 1
}`

B upstream: 
`{
  "nodes": [
    {
      "host": "172.18.26.6",
      "port": 3002,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 49,
    "send": 49,
    "read": 49
  },
  "type": "roundrobin",
  "scheme": "http",
  "pass_host": "pass",
  "name": "NOK upstream",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}`
B route:
`{
  "uri": "/nok",
  "name": "Nok route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "uri": "/"
    }
  },
  "upstream_id": "444636767954403861",
  "status": 1
}`

**Comment by mscb402** [comment]
Do you mean if you access `/nok` in high QPS. The route `/ok` will be affected?

**Comment by abehnamfard** [comment]
Yes, that's exactly my problem.

**Comment by monkeyDluffy6017** [comment]
Can you check the total number of connections in the APISIX server? When there are too many connections because of timeout, it may exhaust the server's connection resources

**Comment by mscb402** [comment]
Have you checked the problem with the machine itself? For example, the number of ulimt is too small, or the network load is too large. Or the upstream machine is slow, etc. Logically, these two different routes should not affect each other. 
I think you can do an experiment, without the Apisix instance. Whether the upstream of `172.18.26.6:3001` is affected after accessing the upstream of `172.18.26.6:3002` with high QPS

**Comment by abehnamfard** [comment]
Thank you again.
I will separate A and B servers and test them again, Will share the result with you.

**Comment by abehnamfard** [comment]
My test environment was not set up correctly, based on @mscb402 suggestion I check the scenario without Apisix and the problem still was there.
By separating A and B every thing works fine and there was no effect on upstream A.
