### ISSUE TITLE
help request:  How to make session of plugin openid-connect  longer?

### ISSUE THREAD

**Issue by Lewisyixin** [apache/apisix#8726]
### Description

It seems session created by openid-connect is less than 2min. When using web site with ajax will be embarrassing(Such kibana, dev tools. We have to flush browser if we didn't use it for less than 2min. )
![image](https://user-images.githubusercontent.com/17898688/215234743-e1e52395-2f68-45bc-b70b-59a288688211.png)

### Environment

- APISIX version (run `apisix version`):  2.15.0
- Operating system (run `uname -a`): 5.4.190-1.el7.elrepo.x86_64 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- Plugin runner version, for issues related to plugin runners: Use origin plugin in apisix 2.15.0

**Comment by mscb402** [comment]
Can you share you config?

**Comment by monkeyDluffy6017** [comment]
Configuring the session expiration time is not currently supported, but we can do it by modifying the code.
APISIX use the [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc) library to connect IdP, and the lua-resty-openidc library use the [lus-resty-session](https://github.com/bungle/lua-resty-session) library to maintian the session, so we just need to pass the session argument to the lua-resty-session library.
we need to change the session parameter of the openid-connect plugin, The call stack is as follows
https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua#L350
https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1466
So I think add a configuration `session.cookie.lifetime` would help, you could have a try

**Comment by Lewisyixin** [comment]
@monkeyDluffy6017  
Finally it's my fault. The CORS is caused by access_token expiring which is set by us.
By the way,  I also find session.cookie.lifetime can be set just by adding variables in `nginx.conf`
```
    set $session_cookie_lifetime 86400;
    set $session_cookie_renew 86400;
```
And the default value is 3600.

**Comment by hamlinzheng** [comment]
@Lewisyixin Hello, did you solve this problem by changing `nginx.conf` ? I met the same problem, my visits were often redirected to OIDC Provider to re-authenticate, this is my issue: https://github.com/apache/apisix/issues/9110, Can you please give me some suggestion?

**Comment by zsmlinux** [comment]
> Configuring the session expiration time is not currently supported, but we can do it by modifying the code. APISIX use the [lua-resty-openidc](https://github.com/zmartzone/lua-resty-openidc) library to connect the IdP, and the lua-resty-openidc library use the [lus-resty-session](https://github.com/bungle/lua-resty-session) library to maintian the session, so we just need to pass the session argument to the lua-resty-session library. we need to change the session parameter of the openid-connect plugin, The call stack is as follows https://github.com/apache/apisix/blob/master/apisix/plugins/openid-connect.lua#L350 https://github.com/zmartzone/lua-resty-openidc/blob/master/lib/resty/openidc.lua#L1466 So I think add a configuration `session.cookie.lifetime` would help, you could have a try

@monkeyDluffy6017 Can apisix support this configuration?

**Comment by karl-chanel** [comment]
m

**Comment by monkeyDluffy6017** [comment]
considered resolved

**Comment by monkeyDluffy6017** [comment]
@zsmlinux please refer to this: https://github.com/apache/apisix/issues/8726#issuecomment-1407399108
