### ISSUE TITLE
docs: tutorial expose your service can not work

### ISSUE THREAD

**Issue by ronething** [apache/apisix#8729]
### Current State

https://apisix.apache.org/docs/apisix/tutorials/expose-api/#expose-your-service

after step1 and step2, when execute step3 Test

```
curl -i -X GET "http://127.0.0.1:9080/get?foo1=bar1&foo2=bar2" -H "Host: example.com"
```

will get `{"error_msg":"404 Route Not Found"}`, maybe `http://127.0.0.1:9080/get` should be `http://127.0.0.1:9080/anything/get`

### Desired State

step3 Test successfully.

**Comment by Neilblaze** [comment]
Yep, it's the same for me! I'd like to take this up. 😄 
@navendu-pottekkat can you assign me this?

**Comment by Ajay-singh1** [comment]
Easy Peesy!
