### ISSUE TITLE
how to set the nginx log format

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8732]
### Description

when i use the self definition for accessLogFormat,there is not effect:
<img width="661" alt="image" src="https://user-images.githubusercontent.com/535200/215265561-409caafe-1a33-404a-a16a-66245d09dac5.png">
in k8s cluster ,for helm install ,there is empty
<img width="310" alt="image" src="https://user-images.githubusercontent.com/535200/215265604-90b6d573-003c-497e-a04e-0f2c6cbda524.png">
how can i set this in helm install?

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
maybe the field in pic one should be `accessLogFormat` instead of `access_log_format`?
refer: https://github.com/apache/apisix-helm-chart/blob/2741f102d64ace12aa920d2770c3001524d99728/charts/apisix/values.yaml#L436

**Comment by kellyseeme** [comment]
yes,tks
