### ISSUE TITLE
docs: title about architecture in zh docs is APISIX

### ISSUE THREAD

**Issue by ronething** [apache/apisix#8739]
### Current State

- zh docs: https://apisix.apache.org/zh/docs/apisix/next/architecture-design/apisix/

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/28869910/215384761-622b6a18-8b2f-418d-aa8a-5b5d8633793e.png">

- en docs: https://apisix.apache.org/docs/apisix/next/architecture-design/apisix/

<img width="1118" alt="image" src="https://user-images.githubusercontent.com/28869910/215384788-73fa820d-eef3-4640-9675-f0e369dfeb05.png">

### Desired State

maybe title about architecture in zh docs can be "软件架构" instead of "APISIX"?

**Comment by monkeyDluffy6017** [comment]
I have fixed the doc by #8740
