### ISSUE TITLE
feat: As a user, I want APISIX to support the head HTTP request, so that we can check if the APISIX is available easily

### ISSUE THREAD

**Issue by An-DJ** [apache/apisix#8741]
### Description

As a user, I want APISIX to support the head HTTP request, so that we can check if the APISIX is available easily.

After that, the user can send a head request like below to APISIX and check if it works.
```
$ curl --head localhost:9180

HTTP/1.1 200 OK
Date: ...
...
```

**Comment by An-DJ** [comment]
@spacewander Could you plz assign that issue to me?

**Comment by spacewander** [comment]
APISIX doesn't enable Admin API if it is not deployed as CP.

**Comment by spacewander** [comment]
Reasonable if it  is only used to get starting
