### ISSUE TITLE
feat: As a user, I want to add EDAS registry discovery support, to enable requests redirecting to EDAS hosted micro services directly.

### ISSUE THREAD

**Issue by alickreborn** [apache/apisix#8745]
### Description

# Background

[EDAS](www.aliyun.com/product/edas) is an Alibaba Cloud product used for hosting micro service applications, which supports micro service frameworks such as Dubbo, Spring Cloud, HSF and service Mesh. The registry center it currently using is a multi-tenant [Nacos server](https://nacos.io/zh-cn/) .

Currently, Apisix can redirect requests to a micro service application if the backend registry server is Nacos, but failed inside EDAS, we hope this can work as well, which could save a lot of Ops works.

Thank you.

**Comment by monkeyDluffy6017** [comment]
Are you interested in developing this feature?
