### ISSUE TITLE
docs: Tutorial /tutorials/expose-api routing not working as expected

### ISSUE THREAD

**Issue by schubidos** [apache/apisix#8747]
### Current State

Following the description the test request is forewarded to example.com instead of httpbin.org.
Problem occured with version 3.1 apisix docker on windows 11 running with docker-desktop.

Missing "anything" was already addressed (https://github.com/apache/apisix/issues/8729), this is about missing config attribute for proper working example.

### Desired State

Described behavior and code samples should match.
For routing to httpbin.org the attribute `"pass_host": "node"`  must be set in upstream configuration, otherwise the host (httpbin.org) configured in upstream is not used.

So it should be:

### 1. Create an Upstream.
Create an Upstream service containing httpbin.org that you can use for testing. This is a return service that will return the parameters we passed in the request.

```
curl "http://127.0.0.1:9180/apisix/admin/upstreams/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "pass_host": "node",
  "nodes": {
    "httpbin.org:80": 1
  }
}'
```

...

Adding an upstream object to your route can achieve the above effect.
```
curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream": {
    "type": "roundrobin",
    "pass_host": "node",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}
```

Additional personal opinion: in this example I find `"host": "example.com"` in route config and curl parameter `-H "Host: example.com"` a bit confusing, especially because it did not work without proper "pass_host" attribute. However, I think it does not help to demonstrate the case.

**Comment by monkeyDluffy6017** [comment]
If use the `node` mode, it will failed when there are serveral nodes. It may be confusing too.
https://github.com/apache/apisix/blob/master/t/admin/routes4.t#L603

How about just listing the configuration item `pass_host` ?
```
curl "http://127.0.0.1:9180/apisix/admin/upstreams/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "pass_host": "pass",        <== list the configuration item `pass_host` 
  "nodes": {
    "httpbin.org:80": 1
  }
}'
```

**Comment by schubidos** [comment]
The problem with `"pass_host": "pass"` is, that the request is routed then to example.com instead of httpbin.org.

I tried this:
## Set `"pass_host": "pass"`
Call `curl -i -X GET "http://127.0.0.1:9080/anything/get?foo1=bar1&foo2=bar2" -H "Host: example.com"`
Result (comes from **example.com!!!**):
```
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=UTF-8
Content-Length: 1256
Connection: keep-alive
Accept-Ranges: bytes
Age: 178498
Cache-Control: max-age=604800
Date: Tue, 31 Jan 2023 08:03:09 GMT
Expires: Tue, 07 Feb 2023 08:03:09 GMT
Last-Modified: Sun, 29 Jan 2023 06:28:11 GMT
Vary: Accept-Encoding
X-Cache: 404-HIT
Server: APISIX/3.1.0

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;

    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

## Set `"pass_host": "node"`
Call `curl -i -X GET "http://127.0.0.1:9080/anything/get?foo1=bar1&foo2=bar2" -H "Host: example.com"`
Result as expected (From doc: `APISIX will forward the request to http://httpbin.org:80/anything/foo?arg=10`.):
```
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 462
Connection: keep-alive
Date: Tue, 31 Jan 2023 08:12:01 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/3.1.0

{
  "args": {
    "foo1": "bar1",
    "foo2": "bar2"
  },
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.68.0",
    "X-Amzn-Trace-Id": "Root=1-63d8cd51-704a662e2fe620074111b518",
    "X-Forwarded-Host": "example.com"
  },
  "json": null,
  "method": "GET",
  "origin": "172.18.0.1, 213.225.34.217",
  "url": "http://example.com/anything/get?foo1=bar1&foo2=bar2"
}
```


I'm just exploring APISIX, so I can't say if it is an error in the docs (as I thought), or a bug. The only thing I see is, that the described steps don't deliver the described result.

**Comment by monkeyDluffy6017** [comment]
It's werid, it does work on my workaround without Set "pass_host": "node", but i'm not using docker

**Comment by monkeyDluffy6017** [comment]
`curl -i -X GET http://httpbin.org:80/anything/foo\?arg\=10 -H "Host: example.com"`
The above command will work too, it seems that the `httpbin.org` website does not handle the `Host` header of the request.
Could test the command in your environment?

**Comment by schubidos** [comment]
OK, that's interesting. I started with a new installation of apisix-docker/example:
```
git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example

docker-compose -p docker-apisix up -d
```

And then followed this tutorial step by step - https://apisix.apache.org/docs/apisix/tutorials/expose-api/ - so just copied the commands to my shell.
I tried the same procedure on 2 notebooks with same result, one with windows 11 the other with windows 10 both with docker-desktop.

Call `curl -i -X GET "http://127.0.0.1:9080/anything/get?foo1=bar1&foo2=bar2" -H "Host: example.com"`
returns error 404 and the content of http://example.com

Thats the corresponding access.log entry:
```
172.18.0.1 - - [31/Jan/2023:08:03:09 +0000] example.com "GET /anything/get?foo1=bar1&foo2=bar2 HTTP/1.1" 404 1256 0.932 "-" "curl/7.68.0" 34.224.50.110:80 404 0.933 "http://example.com/anything/get?foo1=bar1&foo2=bar2"
```
And thats the log after setting `"pass_host": "node"`:
```
172.18.0.1 - - [31/Jan/2023:08:12:01 +0000] example.com "GET /anything/get?foo1=bar1&foo2=bar2 HTTP/1.1" 200 462 0.470 "-" "curl/7.68.0" 34.205.150.168:80 200 0.430 "http://httpbin.org/anything/get?foo1=bar1&foo2=bar2"
```

I now tried your suggestion from my **local machine** (via wsl Ubuntu):
`curl -i -X GET http://httpbin.org:80/anything/foo\?arg\=10 -H "Host: example.com"`
this works fine:
```
HTTP/1.1 200 OK
Date: Tue, 31 Jan 2023 16:21:01 GMT
Content-Type: application/json
Content-Length: 373
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true

{
  "args": {
    "arg": "10"
  },
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "example.com",
    "User-Agent": "curl/7.68.0",
    "X-Amzn-Trace-Id": "Root=1-63d93fed-5f582fb17e0a8daa7cd307ef"
  },
  "json": null,
  "method": "GET",
  "origin": "213.225.34.217",
  "url": "http://example.com/anything/foo?arg=10"
}
```

Then I tried the same from the terminal in **docker container "docker-apisix-web1-1 nginx:1.19.0-alpine"**
`curl -i -X GET "http://httpbin.org/anything/foo?arg=10" -H "Host: example.com"`
And here the problem occurs:
```
HTTP/1.1 404 Not Found
Accept-Ranges: bytes
Age: 218528
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Tue, 31 Jan 2023 16:27:43 GMT
Expires: Tue, 07 Feb 2023 16:27:43 GMT
Last-Modified: Sun, 29 Jan 2023 03:45:35 GMT
Server: ECS (dcb/7FA3)
Vary: Accept-Encoding
X-Cache: 404-HIT
Content-Length: 1256

<!doctype html>
<html>
<head>
    <title>Example Domain</title>

    <meta charset="utf-8" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style type="text/css">
    body {
        background-color: #f0f0f2;
        margin: 0;
        padding: 0;
        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
        
    }
    div {
        width: 600px;
        margin: 5em auto;
        padding: 2em;
        background-color: #fdfdff;
        border-radius: 0.5em;
        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);
    }
    a:link, a:visited {
        color: #38488f;
        text-decoration: none;
    }
    @media (max-width: 700px) {
        div {
            margin: 0 auto;
            width: auto;
        }
    }
    </style>    
</head>

<body>
<div>
    <h1>Example Domain</h1>
    <p>This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.</p>
    <p><a href="https://www.iana.org/domains/example">More information...</a></p>
</div>
</body>
</html>
```

**Comment by monkeyDluffy6017** [comment]
I test in my ubuntu18.04, and it worked
![image](https://user-images.githubusercontent.com/9354193/215979065-8339eb66-e33f-407e-ba7d-52e5ae727de8.png)
```
curl "http://127.0.0.1:9180/apisix/admin/upstreams/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "httpbin.org:80": 1
  }
}'

curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["GET"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream_id": "1"
}'

curl -i -X GET "http://127.0.0.1:9080/anything/get?foo1=bar1&foo2=bar2" -H "Host: example.com"
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 462
Connection: keep-alive
Date: Wed, 01 Feb 2023 07:19:08 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/3.0.0
```
So I think it's your windows' problem?

**Comment by schubidos** [comment]
> So I think it's your windows' problem?
OK, I did not recognize that windows is currently not officially supported. Yes, it might be related to docker-desktop on Windows environment. As mentioned before, I tried it on two machines - one Windows 10 and the other Windows 11.

DEB package install failed in my wsl (Ubuntu 20.04.5) with "'http://openresty.org/package/debian bullseye InRelease is not signed" error - doc says only Debian Bullseye is supported, so I won't follow up this.

I don't want to install docker in my wsl, so I'll give it another try when I have a linux machine available.

Thanks for your support!

**Comment by schubidos** [comment]
### Update 

I could run the expose-api tutorial (all steps as described) successfully with the Docker installation on Debian Bullseye.
So doc seems to be OK and my initial problem most likely is related to the not supported Windows environment.

However, I had to change the docker-compose.yml to make it run.
```
git clone https://github.com/apache/apisix-docker.git
cd apisix-docker/example
```

Change apache/apisix container to version 2.99.0-debian in docker-compose.yml solved the problem
```
  apisix:
    #image: apache/apisix:latest
    image: apache/apisix:2.99.0-debian
``` 

With the original configuration (apache/apisix:latest and also apache/apisix:3.1.0-debian) the apisix container failed to start, the error was:
```
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
nginx: [alert] could not open error log file: open() "/usr/local/apisix/logs/error.log" failed (13: Permission denied)
2023/02/03 17:19:16 [emerg] 1#1: open() "/usr/local/apisix/logs/error.log" failed (13: Permission denied)
```

**Comment by monkeyDluffy6017** [comment]
Yeah, the Windows environment have not been fully tested, few users will deploy APISIX on windows.
The latest apisix image works fine for me
@soulbird  have you encountered this problem before?

**Comment by shreemaan-abhishek** [comment]
@schubidos, can we close this?
