### ISSUE TITLE
help request: How does upstream support subset like functionality in apisix's kubernetes service discovery?

### ISSUE THREAD

**Issue by ada012** [apache/apisix#8756]
### Description

Hi, I see that in apisix's kubernetes service discovery, it supports "label_selector".

https://apisix.apache.org/zh/docs/apisix/discovery/kubernetes/

But how to support "label_selector" in upstream，For example:

With multiple versions of Pods deployed for a service, traffic needs to be directed to different Pods through different labels.

I see that "apisix_upstream subsets" in "ingress-controller" support similar functionality, but rely on "ingress-controller"
https://apisix.apache.org/zh/docs/ingress-controller/references/apisix_upstream/

How does upstream support subset like functionality in apisix's kubernetes service discovery?

### Environment

- APISIX version (run `apisix version`): 2.15.0

**Comment by mscb402** [comment]
I think you can create 2 services, ServiceA match label `version=1.0` pods, and ServiceB match label `version=1.1` pods.
And create 2 upstream, UpstreamA using `namespace/ServiceA` as the service name and UpstreamB using `namespace/ServiceA` as the services name.
And then you can use this 2 upstream in your route

**Comment by shreemaan-abhishek** [comment]
@ada012, did you find the solution?

**Comment by ada012** [comment]
@shreemaan-abhishek We originally implemented VirtualServices based on Istio, and planned to use APIS6 instead of VirtualServices, and in the case that APISix does not support it, we are currently ready to reinvent Kubernetes service discovery with custom plugins, if APISIX support is better.

**Comment by shreemaan-abhishek** [comment]
cc: @tao12345666333 @Revolyssup

**Comment by ada012** [comment]
@shreemaan-abhishek @Revolyssup Oh no, I know apisix-ingress-controller supports subsets, but I deployed apisix in my cluster instead of apisix-ingress-controller, and I wonder if apisix has plans to support subsets, and I understand that in the service discovery plugin implementation logic for kubernetes, you can change it to It is implemented according to the label list-watch podIP. Of course, this may require me to implement it myself

**Comment by Revolyssup** [comment]
> and I understand

The Kubernetes related abstraction can only be used with apisix-ingress-controller. Else you'll have to manually configure admin api or have your own controller that automates the logic. Though I wonder, why can't you use apisix-ingress-controller for this?

**Comment by ada012** [comment]
Due to the large size of our cluster, when we started planning to use apisix, we compared apisix with APISIX-ingress-controllers, but in some special scenarios, configuration changes to apisix ingress controllers take some time to take effect, which will increase the downtime to some extent.

**Comment by Revolyssup** [comment]
@ada012 So you cannot directly use Kubernetes constructs with only Apisix deployed, you will need ingress controller. You can close the issue if this answers your doubts.
