### ISSUE TITLE
feature: as a developer, I want a new plugin, so that support using swagger for request verification

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#8767]
# OAS-Validation detail 

## description

Validate HTTP requests and responses against API specifications. Supports Swagger v2 and OpenAPI v3 specification JSON request and response bodies, and supports schema definitions described using JSON Schema draft v4.

Attributes

| name | type | required| default | value | describe |
| --- | --- | --- | --- | --- | --- |
| api_spec | string | yes | empty | swagger body | API specification defined using Swagger or OpenAPI. This can be a JSON or YAML based file. If using a YAML file, the specification needs to be URL-encoded to preserve the YAML format. |
| verbose_response | boolean | yes | true | true/false | If set to true, returns detailed error messages for invalid requests and responses. This is useful when testing. |

The difference with request-validation
1. Using swagger to describe the field format of the api, a set of interfaces can be described and verified.
2. .. TODO

## enable plugin

The following example shows how to enable the `oas-validation` plugin on a given route and set the api_spec field and verbose_response

```json
curl http://127.0.0.1:9180/apisix/admin/routes/5 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
  "uri": "/",
  "plugins": {
    "oas-validation": {
      "api_spec": "json swaggger body",
      "verbose_response": true
    }
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "127.0.0.1:8080": 1
    }
  }
}
'
```

## Example

1. create a upstream

```json
curl "http://127.0.0.1:9180/apisix/admin/upstreams/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "type": "roundrobin",
  "nodes": {
    "httpbin.org:80": 1
  }
}'

{"key":"\/apisix\/upstreams\/1","value":{"id":"1","nodes":{"httpbin.org:80":1},"create_time":1675229644,"update_time":1675229644,"hash_on":"vars","scheme":"http","type":"roundrobin","pass_host":"pass"}}
```

1. create and query the route

```bash
curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["POST"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream_id": "1"
}'

curl -X GET "http://127.0.0.1:9180/apisix/admin/routes/1" -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1"

{"key":"\/apisix\/routes\/1","value":{"id":"1","create_time":1675231122,"status":1,"upstream_id":"1","methods":["POST"],"update_time":1675231820,"host":"example.com","uri":"\/anything\/*","priority":0},"createdIndex":17,"modifiedIndex":20}
```

1. test the route

```bash
curl -i -X POST "http://127.0.0.1:9080/anything/POST" -H "Host: example.com" -d '{"name": "2102312JSWCNJB000312"}' -H 'accept: application/json' -H 'Content-Type: application/json'

HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 554
Connection: keep-alive
Date: Wed, 01 Feb 2023 06:50:41 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Server: APISIX/3.1.0

{
  "args": {},
  "data": "{\"name\": \"2102312JSWCNJB000312\"}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "application/json",
    "Content-Length": "32",
    "Content-Type": "application/json",
    "Host": "example.com",
    "User-Agent": "curl/7.85.0",
    "X-Amzn-Trace-Id": "Root=1-63da0bc1-6494eb36237cca65385c33f8",
    "X-Forwarded-Host": "example.com"
  },
  "json": {
    "name": "2102312JSWCNJB000312"
  },
  "method": "POST",
  "origin": "172.19.0.1, 143.92.118.2",
  "url": "http://example.com/anything/POST"
}
```

1. Update the route to use swagger's validate

```bash
{
  "uri": "/get",
  "plugins": {
    "oas-validation": {
      "api_sepc": {
        "swagger": "2.0",
        "info": {
          "version": "1.0.6",
          "title": "example api"
        },
        "host": "httpbin.org",
        "basePath": "/v2",
        "schemes": [
          "http"
        ],
        "paths": {
          "/post": {
            "post": {
              "consumes": [
                "application/json"
              ],
              "produces": [
                "application/json"
              ],
              "parameters": [
                {
                  "in": "body",
                  "name": "body",
                  "required": true,
                  "schema": {
                    "$ref": "#/definitions/User"
                  }
                }
              ],
              "responses": {
                "200": {
                  "description": "Create user successfully"
                },
                "405": {
                  "description": "Invalid input"
                }
              }
            }
          }
        },
        "definitions": {
          "User": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "example": "doggie"
              }
            }
          }
        }
      },
      "verbose_response": true
    }
  }
}
```

##  test plugin (TODO

After enabling the plugin as configured above, use the `curl` command to request the route:

Verify that swagger validates the body, the expected behavior is to provide an error of incorrect format.

```json
curl -i -X POST "http://127.0.0.1:9080/anything/POST" -H "Host: example.com" -d '{"name": false}' -H 'accept: application/json' -H 'Content-Type: application/json'
```

PASS

```bash
curl -i -X POST "http://127.0.0.1:9080/anything/POST" -H "Host: example.com" -d '{"name": "2102312JSWCNJB000312"}' -H 'accept: application/json' -H 'Content-Type: application/json'
```

## disbale plugin

When you need to disable the plugin, you can delete the corresponding JSON configuration with the following command, and APISIX will automatically reload the relevant configuration without restarting the service:

```json
curl "http://127.0.0.1:9180/apisix/admin/routes/1" \
-H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "methods": ["POST"],
  "host": "example.com",
  "uri": "/anything/*",
  "upstream_id": "1"
}'
```%

**Comment by tokers** [comment]
We already have the `request-validation` plugin, what about enhancing it instead of creating a new one.

**Comment by Sn0rt** [comment]
> We already have the `request-validation` plugin, what about enhancing it instead of creating a new one.

the developer can use a swagger file to set a batch apis for validation.
instead of setting the `body_scheme` by the request-validation plugin one by one.

the swagger file is generic tool for describe api.


reference: 
https://docs.konghq.com/hub/kong-inc/oas-validation/
https://docs.konghq.com/hub/kong-inc/request-validator/

**Comment by githubxubin** [comment]
> > We already have the `request-validation` plugin, what about enhancing it instead of creating a new one.
> 
> the developer can use a swagger file to set a batch apis for validation. instead of setting the `body_scheme` by the request-validation plugin one by one.
> 
> the swagger file is generic tool for describe api.
> 
> BTW: I can handle this feature develop
> 
> reference: https://docs.konghq.com/hub/kong-inc/oas-validation/ https://docs.konghq.com/hub/kong-inc/request-validator/

Hi~  Are you rooting for swagger now？

**Comment by Sn0rt** [comment]
@githubxubin There are currently no plans to implement an open source version of the openai validate plug-in, but you can refer to the APISIX Enterprise Edition provided by api7 company to provide this function.
