### ISSUE TITLE
help request: The DNS resolution error of the upstream service corresponding to the route

### ISSUE THREAD

**Issue by hardme** [apache/apisix#8775]
### Description

My routing uses xxx.service.consul as the upstream address, but when my upstream service is restarted, it often appears that the dns resolution is still the ip before the restart

### Environment

- APISIX version :2.13.1
- etcd version:3.5.0
- APISIX Dashboard version, if relevant:2.13.0

**Comment by An-DJ** [comment]
@hardme Could you plz offer the logs before and after the restart?

**Comment by hardme** [comment]
Sorry, there is no log. We can only say that we observe the apisix log and print out the ip of the requested upstream service, which does not match the actual ip of the service.

**Comment by An-DJ** [comment]
Well, this problem could be due to a number of reasons. Maybe it is caused by the error of APISIX itself, but we should rule out infrastructure issues like network and DNS.

If you have simple steps to reproduce that issue, it will help the community better identify and resolve it.

**Comment by hardme** [comment]
At present, my solution is to just put the problematic route back online and offline again.

**Comment by tokers** [comment]
This may be due to the DNS cache error. You may configure the retry strategy for this upstream.

**Comment by tokers** [comment]
This may be due to the DNS cache error. You can go ahead and configure the retry strategy for this upstream.

**Comment by hardme** [comment]
@tokers I tested it when something went wrong. The IP accessed by apisix is ​​different from the one I resolved in the container where apisix is ​​located. The IP resolved by the container is correct.

**Comment by tokers** [comment]
> @tokers I tested it when something went wrong. The IP accessed by apisix is ​​different from the one I resolved in the container where apisix is ​​located. The IP resolved by the container is correct.

Then you can check the one APISIX resolved, if this one is a historical instance of your upstream.

**Comment by hardme** [comment]
> > @tokers I tested it when something went wrong. The IP accessed by apisix is ​​different from the one I resolved in the container where apisix is ​​located. The IP resolved by the container is correct.
> 
> Then you can check the one APISIX resolved, if this one is a historical instance of your upstream.


By adding logs, we found that the IP of the upstream node is cached in the routing information. I want to know whether the routing information apisix will cache the IP of the upstream service for DNS resolution by itself.

**Comment by tokers** [comment]
> in the routing information

By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.

**Comment by hardme** [comment]
> > in the routing information
> 
> By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.

That is, from the routing information matched by apisix in the cache, we output the matching routing information in the log, and found that when there is an IP of the upstream node in the routing information, it will not query DNS, but will directly use the routing information. IP, even if this IP has expired

**Comment by tokers** [comment]
> > > in the routing information
> > 
> > 
> > By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.
> 
> That is, from the routing information matched by apisix in the cache, we output the matching routing information in the log, and found that when there is an IP of the upstream node in the routing information, it will not query DNS, but will directly use the routing information. IP, even if this IP has expired

APISIX will parse the domain when it matches the route for the current request, and the upstream nodes' information will be inserted into the object  (which is reachable from the route object). But the resolve is executed each time APISIX gets the matched route (if there are domains in the upstream node list).

Whether to use a cached DNS record is decided by the DNS client. So it's essential to see why the DNS client of APISIX still uses an expired result. If I remember correctly, the cache TTL is get from the DNS record.

**Comment by hardme** [comment]
> > > > in the routing information
> > > 
> > > 
> > > By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.
> > 
> > 
> > That is, from the routing information matched by apisix in the cache, we output the matching routing information in the log, and found that when there is an IP of the upstream node in the routing information, it will not query DNS, but will directly use the routing information. IP, even if this IP has expired
> 
> APISIX will parse the domain when it matches the route for the current request, and the upstream nodes' information will be inserted into the object (which is reachable from the route object). But the resolve is executed each time APISIX gets the matched route (if there are domains in the upstream node list).
> 
> Whether to use a cached DNS record is decided by the DNS client. So it's essential to see why the DNS client of APISIX still uses an expired result. If I remember correctly, the cache TTL is get from the DNS record.

We have made the following configuration, canceled the dns cache, and we set the TTL returned by the DNS server to be 5s, I am not sure whether our configuration has an impact on this
```yaml
dns:
  validity: ~
```

**Comment by tokers** [comment]
> > > > > in the routing information
> > > > 
> > > > 
> > > > By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.
> > > 
> > > 
> > > That is, from the routing information matched by apisix in the cache, we output the matching routing information in the log, and found that when there is an IP of the upstream node in the routing information, it will not query DNS, but will directly use the routing information. IP, even if this IP has expired
> > 
> > 
> > APISIX will parse the domain when it matches the route for the current request, and the upstream nodes' information will be inserted into the object (which is reachable from the route object). But the resolve is executed each time APISIX gets the matched route (if there are domains in the upstream node list).
> > Whether to use a cached DNS record is decided by the DNS client. So it's essential to see why the DNS client of APISIX still uses an expired result. If I remember correctly, the cache TTL is get from the DNS record.
> 
> We have made the following configuration, canceled the dns cache, and we set the TTL returned by the DNS server to be 5s, I am not sure whether our configuration has an impact on this
> 
> ```yaml
> dns:
>   validity: ~
> ```

Did you set this configuration after the issue occurred? Or the issue occurs when you have this configuration.

**Comment by hardme** [comment]
> > > > > > in the routing information
> > > > > 
> > > > > 
> > > > > By saying "in the routing information", what did you mean? Cache DNS records is a normal behavior for an API Gateway, for the sake of performance.
> > > > 
> > > > 
> > > > That is, from the routing information matched by apisix in the cache, we output the matching routing information in the log, and found that when there is an IP of the upstream node in the routing information, it will not query DNS, but will directly use the routing information. IP, even if this IP has expired
> > > 
> > > 
> > > APISIX will parse the domain when it matches the route for the current request, and the upstream nodes' information will be inserted into the object (which is reachable from the route object). But the resolve is executed each time APISIX gets the matched route (if there are domains in the upstream node list).
> > > Whether to use a cached DNS record is decided by the DNS client. So it's essential to see why the DNS client of APISIX still uses an expired result. If I remember correctly, the cache TTL is get from the DNS record.
> > 
> > 
> > We have made the following configuration, canceled the dns cache, and we set the TTL returned by the DNS server to be 5s, I am not sure whether our configuration has an impact on this
> > ```yaml
> > dns:
> >   validity: ~
> > ```
> 
> Did you set this configuration after the issue occurred? Or the issue occurs when you have this configuration.

This configuration is to solve the previous dns server parsing host cache exception problem. After using this configuration, the dns server parsing host cache exception is gone. Then we found the above problem
