### ISSUE TITLE
bug: apisix control service is not installed on k8s by helm chart

### ISSUE THREAD

**Issue by winglight** [apache/apisix#8776]
### Current Behavior

I checker the document: https://apisix.apache.org/docs/dashboard/FAQ/#4-after-modifying-the-plugin-schema-or-creating-a-custom-plugin-in-apache-apisix-why-cant-i-find-it-on-the-dashboard, then I tried to visit apisix control api but 9091 port doesn't exist in apisix pod. Facto, I expect that it should be installed as default with apisix installation.

### Expected Behavior

In apisix-admin pod, there should be a control api server listening 9091.

### Steps to Reproduce

Install apisix by the instructions of here: https://apisix.apache.org/docs/helm-chart/apisix/

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): k8s/helm
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Could you post a issue in https://github.com/apache/apisix-helm-chart/issues
