### ISSUE TITLE
How can I get apisix variables in java-plugin-runner?

### ISSUE THREAD

**Issue by 15349185792** [apache/apisix#8779]
### Description

How can I get apisix variables in java-plugin-runner?

### Environment

- APISIX version 3.1.0

**Comment by An-DJ** [comment]
@15349185792 What is meant by apisix variables you mentioned?

**Comment by 15349185792** [comment]
> @15349185792 What is meant by apisix variables you mentioned?

I want to use route_name in my cunstom logic like this:
![image](https://user-images.githubusercontent.com/50066683/216272428-f22826d6-e4e7-4325-a05c-da462c2619fc.png)

**Comment by nic-chen** [comment]
hi @15349185792 
please refer to https://github.com/apache/apisix-java-plugin-runner/blob/main/docs/en/latest/development.md#the-functions-must-be-implemented-of-filter-execution

![image](https://user-images.githubusercontent.com/33000667/216276297-b245feed-7a11-46e1-8dad-d8313685e7b7.png)
