### ISSUE TITLE
bug: Failed to connect to 127.0.0.1 port 9180: Connection refused

### ISSUE THREAD

**Issue by cgriblt** [apache/apisix#8781]
### Current Behavior

![Screenshot_2023-02-02_16-07-19](https://user-images.githubusercontent.com/116111871/216333734-9f58d347-b26d-4eee-8550-f12ee0f97f8e.png)
![Screenshot_2023-02-02_16-06-53](https://user-images.githubusercontent.com/116111871/216333740-bc39efdf-965d-41ec-abdb-a0fee66f15a5.png)
![Screenshot_2023-02-02_16-06-23](https://user-images.githubusercontent.com/116111871/216333748-d813e2e0-f48f-40f2-b43b-0fd2177452c0.png)

When I make a request with curl, I can't get a return. Apache APISIX Dashboard works but apache APISIX does not

### Steps to Reproduce

1. Run APISIX via the docker image.
2. curl "http://127.0.0.1:9180/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'
3. Failed to connect to 127.0.0.1 port 9180: Connection refused

### Environment

- APISIX version (run `apisix version`):
- APISIX Docker
- Operating system (run `uname -a`):
- Linux 127.0.0.1 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ronething** [comment]
the logs show `all etcd nodes are unavailable`, maybe you should check this.

**Comment by tokers** [comment]
1. Did you have an avaiable ETCD cluster?
2. Did you configure the ETCD cluster address for the APISIX container when you run it?
3. For the first screenshot, are you sure your APISIX container is running?

**Comment by WVenus** [comment]
Is your image id f42b705fe47e ？
You can try apache/apisix: 3.1.0-debian.

**Comment by shreemaan-abhishek** [comment]
I am getting the same error in kubernetes-based installation (using helm chart).

<img width="471" alt="image" src="https://user-images.githubusercontent.com/61597896/217160670-064be987-fb46-4b57-bf41-713899b6581e.png">

Got the same error previously when I tried to install via docker.

**Comment by WVenus** [comment]
My analysis is a image problem.Got the same error previously when I tried to install via docker.
The image installed by helm defaults to apache/apisix: 3.1.0-debian

configuration information：
![image](https://user-images.githubusercontent.com/39941928/217191730-ade6103a-d6b9-4af2-b0ab-2b405f02f159.png)

"strace apisix start" log :

open("/usr/local/apisix/conf/config.yaml", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0777, st_size=1874, ...}) = 0
....
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(2379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (
Operation now in progress)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 2999) = 1 ([{fd=3, revents=POLLIN|POLLOUT|POLLERR|POLLHUP}])
recvfrom(3, 0x7ffe6b5c61ec, 0, 0, NULL, NULL) = -1 ECONNREFUSED (Connection refused)
fcntl(3, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(3, F_SETFL, O_RDWR)               = 0
close(3)                                = 0
socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3
fcntl(3, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK)    = 0
connect(3, {sa_family=AF_INET, sin_port=htons(2379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS (
Operation now in progress)
poll([{fd=3, events=POLLIN|POLLOUT}], 1, 2999) = 1 ([{fd=3, revents=POLLIN|POLLOUT|POLLERR|POLLHUP}])
recvfrom(3, 0x7ffe6b5c61ec, 0, 0, NULL, NULL) = -1 ECONNREFUSED (Connection refused)
fcntl(3, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
fcntl(3, F_SETFL, O_RDWR)               = 0
close(3)                                = 0
write(2, "request etcd endpoint 'http://12"..., 80request etcd endpoint 'http://127.0.0.1:2379/version' error
, connection refused
) = 80
write(2, "all etcd nodes are unavailable\n", 31all etcd nodes are unavailable
) = 31
write(1, "Warning! Request etcd endpoint '"..., 206Warning! Request etcd endpoint 'http://127.0.0.1:2379/vers
ion' error, connection refused, retry time=1
Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2
) = 206

**Comment by tokers** [comment]
> My analysis is a image problem.Got the same error previously when I tried to install via docker. The image installed by helm defaults to apache/apisix: 3.1.0-debian
> 
> configuration information： ![image](https://user-images.githubusercontent.com/39941928/217191730-ade6103a-d6b9-4af2-b0ab-2b405f02f159.png)
> 
> "strace apisix start" log :
> 
> open("/usr/local/apisix/conf/config.yaml", O_RDONLY) = 3 fstat(3, {st_mode=S_IFREG|0777, st_size=1874, ...}) = 0 .... socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3 fcntl(3, F_GETFL) = 0x2 (flags O_RDWR) fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0 connect(3, {sa_family=AF_INET, sin_port=htons(2379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS ( Operation now in progress) poll([{fd=3, events=POLLIN|POLLOUT}], 1, 2999) = 1 ([{fd=3, revents=POLLIN|POLLOUT|POLLERR|POLLHUP}]) recvfrom(3, 0x7ffe6b5c61ec, 0, 0, NULL, NULL) = -1 ECONNREFUSED (Connection refused) fcntl(3, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK) fcntl(3, F_SETFL, O_RDWR) = 0 close(3) = 0 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 3 fcntl(3, F_GETFL) = 0x2 (flags O_RDWR) fcntl(3, F_SETFL, O_RDWR|O_NONBLOCK) = 0 connect(3, {sa_family=AF_INET, sin_port=htons(2379), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EINPROGRESS ( Operation now in progress) poll([{fd=3, events=POLLIN|POLLOUT}], 1, 2999) = 1 ([{fd=3, revents=POLLIN|POLLOUT|POLLERR|POLLHUP}]) recvfrom(3, 0x7ffe6b5c61ec, 0, 0, NULL, NULL) = -1 ECONNREFUSED (Connection refused) fcntl(3, F_GETFL) = 0x802 (flags O_RDWR|O_NONBLOCK) fcntl(3, F_SETFL, O_RDWR) = 0 close(3) = 0 write(2, "request etcd endpoint 'http://12"..., 80request etcd endpoint 'http://127.0.0.1:2379/version' error , connection refused ) = 80 write(2, "all etcd nodes are unavailable\n", 31all etcd nodes are unavailable ) = 31 write(1, "Warning! Request etcd endpoint '"..., 206Warning! Request etcd endpoint 'http://127.0.0.1:2379/vers ion' error, connection refused, retry time=1 Warning! Request etcd endpoint 'http://127.0.0.1:2379/version' error, connection refused, retry time=2 ) = 206

I think this is because you use the 3.x image while using the helm chart for 2.x.

**Comment by shreemaan-abhishek** [comment]
Try running curl against the correct port: 9081/9082

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/61597896/217487181-af85a0ac-b717-4f13-98eb-300e4d330e97.png">

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/61597896/217487345-847f34f6-efd0-4d46-a749-28972d8144e3.png">

This should work:

`curl "http://127.0.0.1:9081/apisix/admin/services/" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1'`

**Comment by kayx23** [comment]
@shreemaan-abhishek is correct in that you should bind to the `0.0.0.0` interface if you run APISIX in docker and would like to access Admin API from `127.0.0.1` on host. You can update this in the `config.yaml`.
