### ISSUE TITLE
bug: Version 3.1.0-debian fails to bind

### ISSUE THREAD

**Issue by chris-sanders** [apache/apisix#8789]
### Current Behavior

Upgrading to 3.1.0-debian I'm getting the following error on startup from the apisix. I've tried to use podSecurityContext to allow NET_BIND_SERVICE, NET_ADMIN, and NET_RAW. I get Permission denied regardless. Rolling back to 3.0.0-debian solves this and service is restored.

/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua init_etcd
2023/02/04 22:41:55 [warn] 1#1: low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:285
nginx: [warn] low address bits of 127.0.0.1/24 are meaningless in /usr/local/apisix/conf/nginx.conf:285
2023/02/04 22:41:55 [emerg] 1#1: bind() to 0.0.0.0:53 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:53 failed (13: Permission denied)

### Expected Behavior

3.1.0 can bind ports like 3.0.0 did

### Error Logs

see above

### Steps to Reproduce

1. Install 3.1.0
2. Bind a port < 1024 

### Environment

I'm using HelmChart 1.1.0 which triggers this with no modifications to versions. Whatever it includes is exactly what I'm running.

**Comment by soulbird** [comment]
ref: https://github.com/apache/apisix-docker/issues/326#issuecomment-1372124381
