### ISSUE TITLE
bug: grpc-web plugin doesn't follow the cors spec

### ISSUE THREAD

**Issue by fracek** [apache/apisix#8791]
### Current Behavior

I'm using the grpc-web but it looks like out of the box it doesn't follow [the spec when it comes to cors](https://github.com/grpc/grpc-web/blob/master/doc/browser-features.md#cors-support):

> Should follow the [CORS spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Server-Side_Access_Control) (Mandatory)
> 
> * Access-Control-Allow-Credentials to allow Authorization headers
> * Access-Control-Allow-Methods to allow POST and (preflight) OPTIONS only
> * Access-Control-Allow-Headers to whatever the preflight request carries

The plugin doesn't set the `Access-Control-Allow-Credentials` header and the `Access-Control-Allow-Headers` value is hardcoded, so it won't include all preflight headers.

The spec doesn't mention it, but for the plugin to work it also needs to add the following header:

 * `Access-Control-Expose-Headers` = `grpc-status,grpc-message`

Or the web client won't be able to read the response grpc status or message.

### Expected Behavior

The plugin should set `Access-Control-Allow-Credentials` to `true` and `Access-Control-Allow-Headers` to `http_access_control_request_headers`. It should also return `Access-Control-Expose-Headers`.

### Steps to Reproduce

1. Deploy a grpc application that requires headers to be set (for example, authentication)
2. Create an upstream for it
3. Create a route, enabling the grpc-web plugin
4. Connect to the route using the `@improbable-eng/grpc-web` client. Notice the request is blocked because of cors.

### Environment

* your apisix-ingress-controller version (output of apisix-ingress-controller version --long):
```
Version: 1.6.0
Git SHA: no-git-module
Go Version: go1.19.4
Building OS/Arch: linux/amd64
Running OS/Arch: linux/amd64
```

* your Kubernetes cluster version (output of kubectl version):

```
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:35:11Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by monkeyDluffy6017** [comment]
How about use the `grpc-web` plugin with the `cors` plugin？
https://github.com/apache/apisix/blob/master/t/plugin/grpc-web.t#L178

**Comment by monkeyDluffy6017** [comment]
Would you like to do this?

**Comment by fracek** [comment]
Yep, I have a few things to do in the next week or so but after that I can contribute. I wanted to double check with the team the changes I propose made sense.

**Comment by monkeyDluffy6017** [comment]
@spacewander is it better to implement the default `cors` behavior in grpc-web plugin?

**Comment by spacewander** [comment]
Yes, we can do it in grpc-web plugin.

```
The spec doesn't mention it, but for the plugin to work it also needs to add the following header:

    Access-Control-Expose-Headers = grpc-status,grpc-message

Or the web client won't be able to read the response grpc status or message.
```

We have e2e test for grpc-web at https://github.com/apache/apisix/tree/master/t/plugin/grpc-web.
Why the client requires something that doesn't exist in the spec to work? Is this issue relative to the client?

**Comment by fracek** [comment]
I believe it's a bug in the grpc-web spec. [Cors request can only access safelisted headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) by default, so `Access-Control-Expose-Headers` is needed to access the headers needed by grpc-web.

**Comment by spacewander** [comment]
Is there any issue or bug report in the grpc-web repo? It's valuable to hear the opinion of grpc-web's maintainer.

**Comment by fracek** [comment]
I raised an issue there https://github.com/grpc/grpc-web/issues/1319
