### ISSUE TITLE
help request: limit-count plugin key configuration

### ISSUE THREAD

**Issue by yunfhu** [apache/apisix#8794]
### Description

Hi,we're using the limit-count plugin,the key filed default value is "remote_addr". The code shows apisix extract the key from ctx.var,it should support configured as other value. Any document about the full list configurable value of limit-count key filed?

### Environment

- APISIX version (run `apisix version`):apisxi 2.11
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by yunfhu** [comment]
https://apisix.apache.org/docs/apisix/apisix-variable/
is all the apisix variable can be used as the key filed of limit-count plugin

**Comment by mscb402** [comment]
Yes, you can use all variable in limit-count plugin

**Comment by mscb402** [comment]
You can use all Nginx variables from "http://nginx.org/en/docs/varindex.html".
And APISIX additional variables from "https://apisix.apache.org/docs/apisix/apisix-variable/".
But remember to set `key_type` to `true`.

**Comment by yunfhu** [comment]
> 

According to the limit-count plugin document: https://apisix.apache.org/docs/apisix/plugins/limit-count/,the available value for  key_type is "var", "var_combination" or "constant"

**Comment by mscb402** [comment]
sorry，Is a mistake, you should set `key_type` to `var`

**Comment by yunfhu** [comment]
> sorry，Is a mistake, you should set `key_type` to `var`

thanks
