### ISSUE TITLE
feat: As a user, I want to know which  route is working  In many scenarios with similar rules

### ISSUE THREAD

**Issue by tylitianrui** [apache/apisix#8802]
### Description

In many scenarios with similar rules，how can  i  distinguish the  route  which is working？ I suggest that  add a variable to make it clear

**Comment by monkeyDluffy6017** [comment]
How about use the [file-logger](https://apisix.apache.org/docs/apisix/plugins/file-logger/) plugin to record the [route id](https://apisix.apache.org/docs/apisix/apisix-variable/)

**Comment by tylitianrui** [comment]
> How about use the [file-logger](https://apisix.apache.org/docs/apisix/plugins/file-logger/) plugin to record the [route id](https://apisix.apache.org/docs/apisix/apisix-variable/) ![image](https://user-images.githubusercontent.com/9354193/217208822-3873a555-9c6a-434f-9a6e-685c1fb7b7c8.png)

it is  useful but  cumbersome. I need  judge the accuracy of rules by querying logs  each time.  It’s  not easy for automated test  either.  i want to develop a plugin for testing

**Comment by shreemaan-abhishek** [comment]
@tylitianrui, what do you suggest?
