### ISSUE TITLE
help request: how to rewrite  response header 's location to remove port

### ISSUE THREAD

**Issue by lsy1990** [apache/apisix#8803]
### Description

I use apisix as a gateway ,the upstream is a service.
when a request to service that with path / ,the service will return 302  /index 
but the location contains   gateway port 9080 ,such as   http://domain.com:9080/index
but I want to the location value is http://domain.com/index
If I use nginx to implement it .the reponse is right.
Is there some plugin to enable ?thanks.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
First of all, I don't know what kind of scenario you have. First I need to clarify that if your APISIX Gateway is working on port 9080, then you want to jump to the service "http://domain.com/index" which belongs to port 80, which is not under Gateway control.
If you want to access "http://domain.com" to reach the Gateway, then you should configure APISIX to listen on port 80. If we do not consider the correct way to use it, and you understand the premise of what I said. You do need a 301 bounce to "http://domain.com/index". You need to first create a "/" route and then add a "redirect" plugin with the following configuration:

```
{
  "uri": "/",
  "name": "test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "redirect": {
      "ret_code": 302,
      "uri": "http://domain.com/index"
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.org",
        "port": 80,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```

**Comment by lsy1990** [comment]
@mscb402  thanks ，It is good idea to use redirect plugin.

**Comment by lsy1990** [comment]
@mscb402  Is there redirect plugin ?

**Comment by mscb402** [comment]
Yes, you can see document in here https://apisix.apache.org/en/docs/apisix/plugins/redirect/

**Comment by mscb402** [comment]
But this plugin not show in apisix-dashboard, so you need enable it using JSON

**Comment by lsy1990** [comment]
@mscb402 thanks
