### ISSUE TITLE
chore: Supplement the schema in deployment 

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#8804]
### Description

Apache APISIX v3 adds a decoupled deployment mode. ref: https://apisix.apache.org/docs/apisix/deployment-modes/#decoupled

The current schema is not perfect. 

When the role is `control_plane`, it should contain the configuration of the `admin` field, which is consistent with traditional.

https://github.com/apache/apisix/blob/5984321c34d3cdc90573ebbecfd17ba9082fb3ba/apisix/cli/schema.lua#L375-L412

xref: https://github.com/apache/apisix-helm-chart/issues/459

**Comment by jiangfucheng** [comment]
Hi, could assign it me, i want to try it.

**Comment by rukundob451** [comment]
@tao12345666333 was the issue worked on?

**Comment by tokers** [comment]
@jiangfucheng Did you start it? I can assign it to you.

**Comment by jiangfucheng** [comment]
> @jiangfucheng Did you start it? I can assign it to you.

I was submit a pr https://github.com/apache/apisix/pull/8809, but still has some problem, could you guide me slove it? I can't reproduce it in my local machine.
