### ISSUE TITLE
apisix have error of real ip plugin

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8808]
### Description

when i use apisix 2.15.1,use the real ip plugin and other plugin,there have some error in k8s pod  log:
2023/02/07 19:49:49 [warn] 45#45: *283226 [lua] real-ip.lua:147: phase_func(): missing real address, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost"

2023/02/07 17:54:53 [error] 43#43: *5 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/admin/init.lua:256: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
coroutine 0:
	[C]: in function 'ipairs'
	/usr/local/apisix/apisix/admin/init.lua:256: in function 'sync_local_conf_to_etcd'
	/usr/local/apisix/apisix/admin/init.lua:354: in function </usr/local/apisix/apisix/admin/init.lua:348>, context: ngx.timer
2023/02/07 17:54:52 [warn] 47#47: *2 [lua] plugin.lua:355: load(): failed to read stream plugin list from local file, context: init_worker_by_lua*

### Environment

- APISIX version (run `apisix version`):apisix 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
What is the `real-ip` plugin configurations? The error message hints that your API request might miss the HTTP header where APISIX gets the real IP.

**Comment by kellyseeme** [comment]
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/535200/217407018-84d1b7e7-8a45-4b90-92a6-c5ee2c5bd153.png">
tks,the real ip have resloved,but when i start the apisix pod there have some error in error.log，when i use the yum there is not problem,use the k8s mode have the error.

**Comment by monkeyDluffy6017** [comment]
https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L496
This line should not be deleted.
You coud config like this:
```
stream_plugins: # sorted by priority
  #- prometheus                    # priority: 500
```

**Comment by kellyseeme** [comment]
tks
