### ISSUE TITLE
Is Apache APISIX supports cookies sticky?

### ISSUE THREAD

**Issue by ygm521** [apache/apisix#881]
That is, the same client request is always processed by a fixed APISIX server.

**Comment by membphis** [comment]
目前还没有这个实现，你们需要支持这个场景么？

There is no such implementation yet. Do you need to support this case?

**Comment by ygm521** [comment]
那么同一个用户的后续请求如何保证发给选中的真实服务器呢？只能基于源ip？

**Comment by membphis** [comment]
You can use the existing implementation, based on the source IP consistency hash for your purposes.

可以使用目前已有实现，基于源 ip 的一致性 hash 达到你的目的。

We can also let APISIX support a load balancing algorithm like sticky cookies, welcome PR.
Can refer to: http://nginx.org/en/docs/http/ngx_http_upstream_module.html#sticky

我们也可以让 APISIX 支持 sticky cookie 这种负载均衡算法，欢迎贡献 PR。

可以参考：http://nginx.org/en/docs/http/ngx_http_upstream_module.html#sticky

**Comment by ygm521** [comment]
只需要在openresty上加入sticky的c模块就行了。至于应用池方面得结合相应的配置指令。

**Comment by membphis** [comment]
PR welcome

**Comment by ygm521** [comment]
需要在openresty的源代码基础加c模块，你们代码中没找到openresty相关源码。

**Comment by moonming** [comment]
@ygm521 OpenResty is not part of Apache APISIX, so if you want to implement sticky in the Nginx c module way, then you have to maintain your own OpenResty package.
So I think to implement sticky in the Lua way is better.

**Comment by soulsoul** [comment]
i agree with moonming,  PR is on the way...

**Comment by ygm521** [comment]
@moonming yes,you are right. it easy to do, use shared cache store cookie--rserIPport , it can be solved.

**Comment by membphis** [comment]
@ygm521 @soulsoul do you think we still need this feature?

**Comment by spacewander** [comment]
Consider solved as there is not response.

**Comment by Aaron199** [comment]
i realy need this feature,  that because i created a Prometheus Deployment that replicas is 2 , as you know  two prometheus has different DataSource，when you connect it through ‘service’，you will get different data

**Comment by tzssangglass** [comment]
> i realy need this feature, that because i created a Prometheus Deployment that replicas is 2 , as you know two prometheus has different DataSource，when you connect it through ‘service’，you will get different data

pls submit a new issue. in fact, we can use traffic-split plugin to do this.

**Comment by WeiWANG0118** [comment]
Actually, I really need this feature. I was facing the same problem that I can't save my cookie then session in the request while I'm using a node server. If my project is highly relying on the cookie/session stored in the request,  I can't APISIX as the api gateway which means I can't use this excellent tool. That's sad.

**Comment by tzssangglass** [comment]
> Actually, I really need this feature. I was facing the same problem that I can't save my cookie then session in the request while I'm using a node server. If my project is highly relying on the cookie/session stored in the request, I can't APISIX as the api gateway which means I can't use this excellent tool. That's sad.

hi, maybe you can take a look at:https://github.com/apache/apisix/issues/1975, use chash on cookie could work.
