### ISSUE TITLE
bug: Adding "plugins:" to config.yaml prevents rewriting the request header

### ISSUE THREAD

**Issue by macdoor** [apache/apisix#8812]
### Current Behavior

If the following content is added to config.yaml, the request header cannot be rewritten
```
plugins:
  - log-rotate
```

The route is defined as follows
```
{
  "uri": "/g/gw*",
  "name": "REST API 18083 prod",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "vars": [
    [
      "server_port",
      "==",
      "18083"
    ]
  ],
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "gem_environment": "prod",
        "rest_gw_proxy_port": "$server_port"
      }
    }
  },
  "upstream_id": "446753751294806357",
  "status": 1
}
```

request headers gem_environment, rest_gw_proxy_port will not be added

### Expected Behavior

The plugins defined in config.yaml should not affect the rewriting of headers.

### Steps to Reproduce

1. create route
```
{
  "uri": "/g/gw*",
  "name": "REST API 18083 prod",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "vars": [
    [
      "server_port",
      "==",
      "18083"
    ]
  ],
  "plugins": {
    "proxy-rewrite": {
      "headers": {
        "gem_environment": "prod",
        "rest_gw_proxy_port": "$server_port"
      }
    }
  },
  "upstream_id": "446753751294806357",
  "status": 1
}
```
2. start route 
headers gem_environment, rest_gw_proxy_port are added to the incoming request and sent upstream
3. modify conf/config.yaml, and add the following content
```
plugins:
  - log-rotate
```
4. reload apisix
headers gem_environment, rest_gw_proxy_port disappeared

### Environment

- APISIX version (run apisix version): 3.1.0 or 2.15.1
- Operating system (run uname -a): 3.10.0-1160.25.1.el7.x86_64
- OpenResty / Nginx version (run openresty -V or nginx -V):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info): 3.5.6
- APISIX Dashboard version, if relevant: 3.0.0 or 2.15.0
- Plugin runner version, for issues related to plugin runners: prometheus, log-rotate
- LuaRocks version, for installation issues (run luarocks --version):

**Comment by monkeyDluffy6017** [comment]
Do you add `proxy-rewrite` to the config?
```
plugins:
  - log-rotate
  - proxy-rewrite
```

**Comment by soulbird** [comment]
The plugins configuration in config.yaml will override the configuration in config-fault.yam

**Comment by macdoor** [comment]
@monkeyDluffy6017 @soulbird Thank you, that's the problem. BTW, I didn't find relevant instructions in the docs. So I need to config plugin in config.yaml and route simultaneously, right?

**Comment by monkeyDluffy6017** [comment]
YES, please check [this](https://github.com/apache/apisix/blob/master/docs/en/latest/plugin-develop.md#name-priority-and-the-others)

**Comment by macdoor** [comment]
@monkeyDluffy6017 I found that log-rotate plugin is commented in config-default.yaml. Which way is better to enable the log-rotate plugin? Modify config-default.yml? Or write all plugins in config.yaml?

**Comment by monkeyDluffy6017** [comment]
`write all plugins in config.yaml` is better
