### ISSUE TITLE
How to configure, so that the existing plug-ins are no longer displayed on the page

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8814]
### Description

目前apisix有众多的插件,我应该如何去屏蔽掉一些插件,不在页面上显示出来。

### Environment

- APISIX version 2.15 (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Do you mean on the apisix-dashboard?

**Comment by githubxubin** [comment]
> Do you mean on the apisix-dashboard?

yes

**Comment by githubxubin** [comment]
> Do you mean on the apisix-dashboard?

What should I do？

**Comment by monkeyDluffy6017** [comment]
Maybe you could ask in https://github.com/apache/apisix-dashboard/issues ?
