### ISSUE TITLE
help request: cjson decode big number 

### ISSUE THREAD

**Issue by 281743556** [apache/apisix#8815]
### Description

使用apisix 2.13 中内嵌lua为5.1.5，在使用cjson.encode() 转换 
local body_table = { jsonvalue=12345678901234567890}
log(ngx.INFO, "header body_table:", cjson.encode(body_table));
执行结果为：header body_table:{"jsonvalue":1.2345678901235e+019}
我看网上解释，需要使用lua5.3+，help me!!

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
Currently, lua 5.1 does not support operations on int64. Maybe you could use string instead of int64?

Ref: https://groups.google.com/g/openresty/c/09eW8bVevHQ/m/8Qj9YWoJEgAJ
