### ISSUE TITLE
help request: When I use apisix to proxy a TCP connection, how can I close this TCP connection or prevent subsequent requests?

### ISSUE THREAD

**Issue by sugarScc** [apache/apisix#8817]
### Description

I plan to use apisix to proxy TCP connection between client and database(ex. MySQL), but when the client wants to do some bad thing(ex. hijacking) I want to close the TCP connection, how could I implement this feature? It's better if I could ignore subsequent requests from this TCP connection and returen response like "bad request". Is there any plan?

### Environment
- APISIX version (latest):

**Comment by An-DJ** [comment]
Stream Proxy only supports proxy TCP/UDP requests. It is currently unable to do authentication, traffic restriction, etc.

**Comment by sugarScc** [comment]
> 
if I use a custom plugin, could I address this issue?

**Comment by An-DJ** [comment]
Currently, Stream routes do not support Plugin mechanisms. Perhaps you can do SQL security audits at the application level.

**Comment by sugarScc** [comment]
> Currently, Stream Route does not support Plugin mechanisms. Perhaps you can do SQL security audits at the application level.

**Comment by An-DJ** [comment]
@sugarScc IMHO, auditing and constraints on SQL should be application-level requirements and probably should not be implemented based on TCP/UDP proxies.

**Comment by sugarScc** [comment]
> @sugarScc IMHO, auditing and constraints on SQL should be application-level requirements and probably should not be implemented based on TCP/UDP proxies.

yes, we have another service to check whether the SQL is correct in application-level, the point is, when we find the SQL is malicious, can we break the TCP connection in apisix?

**Comment by An-DJ** [comment]
Maybe you need a blacklist or limit traffic mechanisms based on Stream Route.

Stream Route currently does not have these features, nor can it be extended by custom plugins. It can only proxy TCP/UDP traffic directly.

**Comment by tokers** [comment]
> > @sugarScc IMHO, auditing and constraints on SQL should be application-level requirements and probably should not be implemented based on TCP/UDP proxies.
> 
> yes, we have another service to check whether the SQL is correct in application-level, the point is, when we find the SQL is malicious, can we break the TCP connection in apisix?

We have a lot of things to do on APISIX if we want to intercept bad SQLs.

1. How did we analyze the MySQL protocol? How can we know if we get a complete SQL statement if we don't do this? In other words, how can we detect the protocol boundary?
2. How to communicate with the external service? Which protocols? Retry? Timeout? How to handle these stuff?

Anyway, you can develop such a feature if you want, but it doesn't like a standard feature.

**Comment by sugarScc** [comment]
> > > @sugarScc IMHO, auditing and constraints on SQL should be application-level requirements and probably should not be implemented based on TCP/UDP proxies.
> > 
> > 
> > yes, we have another service to check whether the SQL is correct in application-level, the point is, when we find the SQL is malicious, can we break the TCP connection in apisix?
> 
> We have a lot of things to do on APISIX if we want to intercept bad SQLs.
> 
> 1. How did we analyze the MySQL protocol? How can we know if we get a complete SQL statement if we don't do this? In other words, how can we detect the protocol boundary?
> 2. How to communicate with the external service? Which protocols? Retry? Timeout? How to handle these stuff?
> 
> Anyway, you can develop such a feature if you want, but it doesn't like a standard feature.

Got it, but if I assume that I have addressed those issue, and now I have following abilities:
1. able to find the bad SQLs;
2. able to communicate with external service. 

And now I only need one extra ability to implement this feature:
1. able to disconnect the TCP connection

And I noticed we can delay one TCP connection when using xrpc(redis), does this mean we are able to close the TCP connection?

**Comment by tokers** [comment]
> able to disconnect the TCP connection

Try to use the OpenResty API: `ngx.exit(-1)` in the stream subsystem, it will close the TCP connection established with the client.

**Comment by sugarScc** [comment]
Hi, I notice proxy-mirror plugin can mirror http packet, I wonder is there any easy way for us to mirror tcp packet？

**Comment by sugarScc** [comment]
> > able to disconnect the TCP connection
> 
> Try to use the OpenResty API: `ngx.exit(-1)` in the stream subsystem, it will close the TCP connection established with the client.

Hi, I notice proxy-mirror plugin can mirror http packet, I wonder is there any easy way for us to mirror tcp packet？

**Comment by shreemaan-abhishek** [comment]
@sugarScc please create another issue for this.
