### ISSUE TITLE
help request: How to get route.id in plugin

### ISSUE THREAD

**Issue by guochunyang2004** [apache/apisix#8822]
### Description

如何在插件中获取route.id ？

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
https://apisix.apache.org/docs/apisix/apisix-variable/
![image](https://user-images.githubusercontent.com/9354193/217975044-2bef7d3d-fdac-41e8-9925-7993cdabc124.png)

**Comment by An-DJ** [comment]
@guochunyang2004  APISIX provides this variable.

You can refer to the related implementation of the plugin consumer-restriction about how to use it:
https://github.com/apache/apisix/blob/master/apisix/plugins/consumer-restriction.lua#L73
