### ISSUE TITLE
docs: error link about nacos deployment tutorial in apisix-seed page

### ISSUE THREAD

**Issue by ronething** [apache/apisix#8825]
### Current State

the PR https://github.com/apache/apisix/pull/8662 just push to release/3.1, why not master branch?
issue refer: https://github.com/apache/apisix/issues/8657

### Desired State

maybe the master branch should be modified.

**Comment by shreemaan-abhishek** [comment]
This is probably due to a mistake during raising the PR.

**Comment by Ajay-singh1** [comment]
@ronething Can we close this issue now?
