### ISSUE TITLE
if etcd is use auth

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8833]
### Description

if etcd is use auth,any affect?we use ten more cluster of one etcd,the etcd have 10000 connections,if auth is open,will affect service?and we use domain of etcd,there more error in parse domain in the error log.

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kellyseeme** [comment]
if apisix use auth,then etcd open the auth,in the change time,all the apisix pod is CrashLoopBackOff,the error log is:
got malformed key-put message: "{"error":"etcdserver: user name is empty","code":3,"message":"etcdserver: user name is empty"}" from etcd "http://10.123.12.45:2379/v3/kv/put"
this is not the desired state,if etcd down,is not affect the running pod

**Comment by tokers** [comment]
@kellyseeme https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L632-L633 See this.

**Comment by mscb402** [comment]
This is because you have a configuration problem and you need to configure the username and password for ETCD in the config file. This section of the document is indeed missing, we will add it as soon as possible.

**Comment by kellyseeme** [comment]
tks
