### ISSUE TITLE
help request: use helm install apisix version 3.1.0 ,ApisixRoute tips 404 Route Not Found

### ISSUE THREAD

**Issue by imgolye** [apache/apisix#8835]
### Description

use helm install apisix version 3.1.0 ,ApisixRoute tips 404 Route Not Found.
yaml file:
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: async-service-test-router
  namespace: test
spec:
  http:
    - name: async-service-test-router
      match:
        paths:
        - /async-service/
        methods:
        - GET
      backends:
      - serviceName: async-service-base
        servicePort: 7323

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
@imgolye Please provide the specific environment information, and paste the APISIX Ingress Controller logs.

**Comment by yongxiaodong** [comment]
> @imgolye Please provide the specific environment information, and paste the APISIX Ingress Controller logs.

I encountered the same mistake.  My K8S Cluster Version Is 1.20.11
Installation method: Helm [https://apisix.apache.org/docs/apisix/installation-guide/](url)
After the installation is complete

```
#kubectl get pod -n apisix
NAME                      READY   STATUS    RESTARTS   AGE
apisix-7fdc8945d9-7ndf5   1/1     Running   0          23h
apisix-etcd-0             1/1     Running   0          22h
apisix-etcd-1             1/1     Running   0          22h
apisix-etcd-2             1/1     Running   0          22h
```

Apisix logs: 
`192.168.16.60 - - [28/Feb/2023:02:17:32 +0000] apisix.dataoke.com "GET /dtk_go_app_api/v1/goods-info-nl HTTP/1.1" 404 47 0.000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" - - - "http://apisix.dataoke.com"
`

I confirm that my back end can work normally

**Comment by shreemaan-abhishek** [comment]
ping @imgolye
