### ISSUE TITLE
bug: Healthcheck on Upstream multiple Targets

### ISSUE THREAD

**Issue by synologic** [apache/apisix#8841]
### Current Behavior

An upstream configured with 2 targets:

{
  "nodes": [
    {
      "host": "172.16.1.115",
      "port": 3000,
      "weight": 1
    },
    {
      "host": "172.16.1.115",
      "port": 3001,
      "weight": 1
    }
  ],
  "timeout": {
    "connect": 6,
    "send": 6,
    "read": 6
  },
  "type": "roundrobin",
  "checks": {
    "active": {
      "concurrency": 10,
      "healthy": {
        "http_statuses": [
          200,
          302
        ],
        "interval": 1,
        "successes": 2
      },
      "http_path": "/",
      "timeout": 1,
      "type": "http",
      "unhealthy": {
        "http_failures": 5,
        "http_statuses": [
          429,
          404,
          500,
          501,
          502,
          503,
          504,
          505
        ],
        "interval": 1,
        "tcp_failures": 2,
        "timeouts": 3
      }
    }
  },
  "scheme": "http",
  "pass_host": "pass",
  "name": "Upstream 1 on port 3000",
  "keepalive_pool": {
    "idle_timeout": 60,
    "requests": 1000,
    "size": 320
  }
}

The Route:

{
  "uri": "/*",
  "name": "Default Static Route",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "*.local",
  "plugins": {
    
    "proxy-rewrite": {
      "scheme": "https"
    }
  },
  "upstream_id": "447279289499386665",
  "status": 1
}

Both target nodes are running, very simple express nodejs app for testing.

Requesting / from apisix, works fine and healthcheck returns all ok:

root@apisix1:/usr/local/apisix/logs# curl http://172.16.1.110:9090/v1/healthcheck
[{"healthy_nodes":[{"priority":0,"weight":1,"host":"172.16.1.115","port":3000}],"src_type":"upstreams","name":"upstream#\/apisix\/upstreams\/447279289499386665","src_id":"447279289499386665","nodes":[{"priority":0,"weight":1,"host":"172.16.1.115","port":3000},{"priority":0,"weight":1,"host":"172.16.1.115","port":3001}]}]

If i stop the first node, healthcheck shows only the second node as healthy, and as expected, Apisix logs show:

2023/02/11 17:28:52 [warn] 2876#2876: *22420 [lua] healthcheck.lua:1149: log(): [healthcheck] (upstream#/apisix/upstreams/447279289499386665) unhealthy TCP increment (2/2) for '(172.16.1.115:3000)' while connecting to upstream, client: 192.168.34.171, server: _, request: "GET / HTTP/1.1", upstream: "http://172.16.1.115:3000/", host: "www.local"

However, if I bring the second node online, it is never added back to the load balancing rotation.

It receives health check requests, it is never added back.

If I stop the second node and do an HTTP Request to Apisix, i get a 502 Bad Gateway, and the second requests goes to the first target node, which is then added to the healthcheck correctly.

Bringing back the second node, will automatically add it to healthy nodes and it will receive requests.

### Expected Behavior

A target node that has been brought back up, should be added automatically back into the load balancing RR

### Steps to Reproduce

As described above

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Debian 11
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.7

**Comment by shreemaan-abhishek** [comment]
I tried to reproduce this bug and I can confirm everything is working fine. The target node that was brought back up, was added automatically back into the load-balancing RR

However, did you notice any error logs?

**Comment by kayx23** [comment]
I have a similar setup with two nginx nodes configured on an upstream with active health check, using the default round robin LB option.

Brought one down and added it back. I see the health check indicator becomes `healthy` again, and that when I generate 10 consecutive requests, requests are distributed to the two nodes in the round robin fashion.

![image](https://github.com/apache/apisix/assets/39619599/61ff2acf-a4e4-4c99-922d-efa6a1643a01)

Cannot repro your situation:

> However, if I bring the second node online, it is never added back to the load balancing rotation.
> It receives health check requests, it is never added back.

Closing for now. If needed, feel free to re-open but please format the description better.
