### ISSUE TITLE
help request:  How to rewrite uri in custome format ?

### ISSUE THREAD

**Issue by wavemoroc001** [apache/apisix#8842]
### Description

Hi, I have uri like this '/api/service-a/account/me' then i want to rewrite it in this format `/service-a/account/me`.  
I have look at proxy-rewrite but i still no idea to achieve my goal.

Cloud you give some advice ? 

### Environment

- APISIX version (run `apisix version`): 3.1
- Operating system (run `uname -a`): Docker
- Plugin runner version, for issues related to plugin runners: proxy-rewrite

**Comment by An-DJ** [comment]
From: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

![image](https://user-images.githubusercontent.com/24536972/218350927-35fc6c42-3d11-44be-b677-ff4f7286648f.png)

**Comment by An-DJ** [comment]
@wavemoroc001 Maybe `["^/api/(.*)", "/$1"]` is ur need?

**Comment by wavemoroc001** [comment]
@An-DJ 
Like this ? 

<img width="1306" alt="Screenshot 2566-02-13 at 09 02 10" src="https://user-images.githubusercontent.com/56395197/218354289-9bd76c6a-e12f-4cbf-95b5-0a95bfb76052.png">

**Comment by An-DJ** [comment]
@wavemoroc001 Yes. You can refer to the demo below, which forwards all "/api/ip" requests 
to "http://httpbin.org/ip".

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
      "plugins": {
            "proxy-rewrite": {
                "regex_uri" : ["^/api/(.*)", "/$1"]
            }
       },
      "upstream": {
           "type": "roundrobin",
           "nodes": {
               "httpbin.org": 1
           }
      },
      "uri": "/api/ip"
}'

```

```
curl "http://localhost:9080/api/ip"
{
  "origin": "127.0.0.1, x.x.x.x"
}
```

**Comment by wavemoroc001** [comment]
@An-DJ  Thanks It work!
