### ISSUE TITLE
Can apisix's access.log log level be set? I want to see very detailed log information

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8846]
### Description

apisix 的access.log日志可以设置级别吗 想看非常详细的日志信息

### Environment

- APISIX version 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Try to customize the access log format. See the `access_log_format` in `config-default.yaml`.

**Comment by githubxubin** [comment]
> 

thanks
