### ISSUE TITLE
help request: Can I know which file the error log is printed from?

### ISSUE THREAD

**Issue by syl000** [apache/apisix#8847]
### Description

for some error log,i can find
eg：
```
2023/02/13 06:38:16 [error] 58#58: *2483679 [lua] config_etcd.lua:631: no healthy etcd endpoint available, next retry after 8s, context: ngx.timer
```
config_etcd.lua

bug for some error log,i can't
eg:
```
2023/02/13 04:39:08 [warn] 54#54: *965949 [lua] v3.lua:829: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
```
I can't find v3.lua

### Environment

- APISIX version:3.1.0
- Operating system:Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux
- OpenResty / Nginx version :openresty/1.21.4.1

**Comment by tokers** [comment]
It's not a module in APISIX itself, it's api7/lua-resty-etcd.

**Comment by syl000** [comment]
> It's not a module in APISIX itself, it's api7/lua-resty-etcd.

```
2023/02/13 04:39:08 [warn] 54#54: *965949 [lua] v3.lua:829: request_chunk(): http://etcd:2379: failed to parse domain: failed to parse domain. Retrying, context: ngx.timer
```
都是中国人我就直接中文了：）
其实我是想找下为什么会有上面那个warn，etcd和apisix都是使用docker部署，并且使用同一个bridge类型自定义网络，理论上来说可以通过`服务名:端口`的形式访问到，确实在整个apisix运行期间，也没看到什么异常的情况，

**Comment by hyt05** [comment]
+1

**Comment by tokers** [comment]
@syl000 @hyt05 This is a known issue. We're still trying to figure out it.

**Comment by syl000** [comment]
> This is a known issue. We're still trying to figure out it.

请问下，目前看来会对已知功能带来什么影响吗？或者单纯的只是一个warning？

可以把issue链接贴出来吗？我使用关键字检索没有找到相关信息。

**Comment by hyt05** [comment]
回退到2.14.1-centos 就可以了

**Comment by syl000** [comment]
> 回退到2.14.1-centos 就可以了

好的，我试试，谢谢！

**Comment by shreemaan-abhishek** [comment]
fixed by https://github.com/api7/apisix-build-tools/pull/278
