### ISSUE TITLE
Is there any way to quickly clear the data of apisix? Is there an existing interface that can be used

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8848]
### Description

有什么方法快速清空apisix的数据吗？有现成的接口可以使用吗

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
APISIX doesn't have such an API, but you can list all the resources and delete them one by one. Or you may just clear the data in the ETCD cluster.

**Comment by githubxubin** [comment]
> APISIX doesn't have such an API, but you can list all the resources and delete them one by one. Or you may just clear the data in the ETCD cluster.

How clear the data from teh ETCD？

**Comment by ronething** [comment]
if you want to clear etcd data about apisix, you can exec command like `./etcdctl del --prefix /apisix`, it maybe dangerous, so make sure you know what you are doing.
