### ISSUE TITLE
help request: About active health checks

### ISSUE THREAD

**Issue by liufeiguo** [apache/apisix#8853]
### Description

配置路由时，主动健康检查，配置了主机名、端口、路径之后，在该主机并未接收到apisix 发送的任何请求，主动健康检查功能是否不好使？

### Environment

- APISIX version (run `apisix version`): 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Active health check needs to be triggered before a request occurs

**Comment by liufeiguo** [comment]
但是在请求发生之前，配置的健康检查并未触发，除了在路由配置，还需要在哪里配置么

**Comment by liufeiguo** [comment]
> Active health check needs to be triggered before a request occurs

But before the request occurs, the health check of the configuration is not triggered. In addition to the routing configuration, where do you need to configure it

**Comment by liufeiguo** [comment]
> > Active health check needs to be triggered before a request occurs
> 
> But before the request occurs, the health check of the configuration is not triggered. In addition to the routing configuration, where do you need to configure it

![image](https://user-images.githubusercontent.com/46086269/218905670-842e02d7-cd03-4332-bf33-7f9c2ae597f2.png)
The configured active check did not access the path before the request

**Comment by soulbird** [comment]
Sorry, I expressed something wrong again.
If no request occurs, the health check will not be triggered

**Comment by liufeiguo** [comment]
> Sorry, there is something wrong with my expression. If no request occurs, the health check will not be triggered

However, when accessing through the configured route and the path after the gateway proxy, the corresponding service of the active health check does not receive the request

**Comment by liufeiguo** [comment]
> Sorry, there is something wrong with my expression. If no request occurs, the health check will not be triggered

Passive inspection depends on active inspection. How is this triggered

**Comment by soulbird** [comment]
You can learn about the principles of health checks from this article https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md
If there are any problems in practice, please give configuration and reproduction steps

**Comment by liufeiguo** [comment]
> https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md

from [](https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md ), correctly understand the health examination, thank you for your help

**Comment by liufeiguo** [comment]
> You can learn about the principles of health checks from this article https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md If there are any problems in practice, please give configuration and reproduction steps

from [](https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md) , correctly understand the health examination, thank you for your help

**Comment by liufeiguo** [comment]
> You can learn about the principles of health checks from this article https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md If there are any problems in practice, please give configuration and reproduction steps

from https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/health-check.md , correctly understand the health examination, thank you for your help
