### ISSUE TITLE
feat: As a user, I want to apisix support consul discovery with health API

### ISSUE THREAD

**Issue by dyrnq** [apache/apisix#8856]
### Description

As a user, I want to apisix support consul discovery with health API, because Consul culster has then the optional health checking mechanisms and export API with [Health HTTP Endpoint](https://developer.hashicorp.com/consul/api-docs/health).

So apisix can fetch  a svc`s all health filtered endpoints directly use from Consul discovery from health API.

**Comment by monkeyDluffy6017** [comment]
Would you like to implement this feature?

**Comment by dyrnq** [comment]
I think I can do this, that can study from consul discovery type, can we named this discovery type name  `consul_ heath`?

**Comment by monkeyDluffy6017** [comment]
@spacewander

**Comment by spacewander** [comment]
What's the difference between the new consul discovery and the consul discovery we have now?

**Comment by dyrnq** [comment]
They are all consul discovery, Only the interface is slightly different.

Consul has an agent ability to health check the endpoints that registered. health check is an optional for users.

Consul have two API get registered endpoints, one is [Consul Catalog API](https://developer.hashicorp.com/consul/api-docs/catalog) and another is  [Consul health API](https://developer.hashicorp.com/consul/api-docs/health).

And consul health API can use consul the optional health checking mechanisms. and return health filter upstream endpoint to apisix.


So if consul return health  endpoint to apisix, then apisix no need to health check them, and if consul return all endpoints to apisix ,then apisix need to do healtch check.

**Comment by dyrnq** [comment]
I have noticed that nacos discovery use the query parameter `healthyOnly=true` to filter unhealthy endpoints.

But I haven't verified this, just from the perspective of code analysis in <https://github.com/apache/apisix/blob/master/apisix/discovery/nacos/init.lua#L39>  and the docs of nacos <https://nacos.io/en-us/docs/open-api.html>.



<h3 style="padding: 0px; margin: 24px 0px 16px; font-weight: 600; box-sizing: border-box; font-size: 1.25em; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Request Path</h3><pre style="padding: 16px; margin: 0px 0px 16px; box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; overflow-wrap: normal; overflow: auto; line-height: 1.45; background-color: rgb(246, 248, 250); border-radius: 3px; color: rgb(36, 41, 46); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><code class="language-plain" style="padding: 0.5em; margin: 0px; box-sizing: border-box; font-family: SFMono-Regular, Consolas, &quot;Liberation Mono&quot;, Menlo, Courier, monospace; font-size: 13.6px; background: rgb(30, 30, 30); border-radius: 3px; word-break: normal; white-space: pre; border: 0px; display: block; overflow: auto visible; line-height: inherit; overflow-wrap: normal; color: rgb(220, 220, 220);">/nacos/v1/ns/instance/list
</code></pre><h3 style="padding: 0px; margin: 24px 0px 16px; font-weight: 600; box-sizing: border-box; font-size: 1.25em; line-height: 1.25; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Request Parameters</h3>

Name | Type | Required | Description
-- | -- | -- | --
serviceName | String | yes | Service name
groupName | String | no | group name
namespaceId | String | no | ID of namespace
clusters | String, splited by comma | no | Cluster name
healthyOnly | boolean | no, default value is false | Return healthy instance or not

**Comment by spacewander** [comment]
So the current consul discovery will return an unhealthy node? We assumed that the nodes from the discovery should be healthy if the service discovery has health check support.
I would consider it a bug and fix it in the current consul discovery.

**Comment by dyrnq** [comment]
I have some test here <https://github.com/dyrnq/nomad-vagrant/blob/main/scripts/test-consul-health.sh#L71>

I prepare 4 instance nginx here:

| ip           | port  | check                | states  |
|--------------|-------|----------------------|---------|
| 192.168.33.4 | 18080 | with health check    | running |
| 192.168.33.4 | 28080 | with health check    | running |
| 192.168.33.4 | 38080 | with health check    | Fault   |
| 192.168.33.4 | 48080 | without health check | Fault   |


Then I use different API to check return, give the result as follows

```
(
echo "fetch endpoint from catalog API"
curl -fsSL http://127.0.0.1:8500/v1/catalog/service/nginx | jq -r '.[] | "\(.ServiceAddress):\(.ServicePort)"'
echo "fetch endpoint from health API without health filter"
curl -fsSL http://127.0.0.1:8500/v1/health/service/nginx | jq -r '.[] | "\(.Service.Address):\(.Service.Port)"'
echo "fetch endpoint from health API with health filter"
curl -fsSL http://127.0.0.1:8500/v1/health/service/nginx?passing=true | jq -r '.[] | "\(.Service.Address):\(.Service.Port)"'
# https://developer.hashicorp.com/consul/api-docs/health#passing
)


# fetch endpoint from catalog API
# 192.168.33.4:18080
# 192.168.33.4:28080
# 192.168.33.4:38080
# 192.168.33.4:48080
# fetch endpoint from health API without health filter
# 192.168.33.4:18080
# 192.168.33.4:28080
# 192.168.33.4:38080
# 192.168.33.4:48080
# fetch endpoint from health API with health filter
# 192.168.33.4:18080
# 192.168.33.4:28080
# 192.168.33.4:48080

```

**Comment by monkeyDluffy6017** [comment]
@dyrnq What you tested is just to prove that the consul works as expect, but If the APISIX will return an unhealthy node?

**Comment by dyrnq** [comment]
At this stage，apisix V3.1 (docker.io/apache/apisix:3.1.0-debian) release has another  issues <https://github.com/apache/apisix/issues/8827>, and master have fix 8827.

So I use dev apisix image (docker.io/apache/apisix:dev) verified this


```bash
curl http://127.0.0.1:9180/apisix/admin/routes/1000 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
  "uri": "/",
  "name": "nginx-test",
  "upstream": {
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "discovery_type": "consul",
    "pass_host": "pass",
    "service_name": "nginx",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  }
}'
```
then dump then from apisix
```bash
curl -fsL http://127.0.0.1:9090/v1/discovery/consul/dump | jq -r '.services."nginx"[] | "\(.host):\(.port)"'
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:38080
192.168.33.4:48080
```

**Comment by monkeyDluffy6017** [comment]
So it's a bug, would you like to fix this?

**Comment by dyrnq** [comment]
Indeed, there are some challenge for me. 

I tried to see  the code <https://github.com/apache/apisix/blob/master/apisix/discovery/consul/init.lua#L329>

there are consul_sub_url , consul_watch_sub_url, consul_server_url

I think i can change

## step1

```bash
consul_sub_url = "/catalog/service",  --> consul_sub_url = "/health/service", 
```

## step2

append query string `?passing=true` to `svc_url`

```bash
local svc_url = consul_server.consul_sub_url .. "/" .. service_name
```

## setp3

adjust the data returned json by heath API

`local svc_address, svc_port = node.ServiceAddress, node.ServicePort`

**Comment by dyrnq** [comment]
I lost here.

`if consul_server.index ~= watch_result.headers['X-Consul-Index'] then`

I think this logical judgment should discard, becaus the health status is a dynamic value constantly changing.

**Comment by spacewander** [comment]
@Fabriceli

Would you provide some help? Thanks!

**Comment by Fabriceli** [comment]
> I lost here.
> 
> `if consul_server.index ~= watch_result.headers['X-Consul-Index'] then`
> 
> It also needs to be adjusted accordingly, becaus the health status is a dynamic value constantly changing.
> 
> or maybe watch an associated health API `/health/checks/:service` to check X-Consul-Index`s change

I think you do not need change this `if consul_server.index ~= watch_result.headers['X-Consul-Index'] then`. the value of `X-Consul-Index`, indicating that the client wishes to wait for any changes subsequent to that index, if watch `/health/checks/:service` API, that will make all watch request waiting for any changes. The second reason is, the watch API `/catalog/services` just ONE request; for the watch API `/health/checks/:service` has N (number of services) requests.

**Comment by dyrnq** [comment]
> > I lost here.
> > `if consul_server.index ~= watch_result.headers['X-Consul-Index'] then`
> > It also needs to be adjusted accordingly, becaus the health status is a dynamic value constantly changing.
> > or maybe watch an associated health API `/health/checks/:service` to check X-Consul-Index`s change
> 
> I think you do not need change this `if consul_server.index ~= watch_result.headers['X-Consul-Index'] then`. the value of `X-Consul-Index`, indicating that the client wishes to wait for any changes subsequent to that index, if watch `/health/checks/:service` API, that will make all watch request waiting for any changes. The second reason is, the watch API `/catalog/services` just ONE request; for the watch API `/health/checks/:service` has N (number of services) requests.

when an node from health to unhealth, the `/catalog/services` X-Consul-Index has no change, then will not go to  fetch the new health nodes.

**Comment by dyrnq** [comment]
Or mybey we can wath `/health/state/:state` <https://developer.hashicorp.com/consul/api-docs/health#list-checks-in-state>,

it seems a ONE request.

I found some information ,see <https://github.com/fabiolb/fabio/blob/v1.6.3/registry/consul/service.go#L43>

**Comment by Fabriceli** [comment]
The `/health/state/:state` API will be updated when any endpoint updated or added or deleted?

**Comment by dyrnq** [comment]
OK, Let me modify this and submit a PR according to we discussed above. I will test it after modification.

**Comment by dyrnq** [comment]
> Have to check whether the `/health/state/:state` API will be updated or not when any endpoint updated or added or deleted.

`/health/state/any` meet expectations

>state (string: <required>) - Specifies the state to query. Supported states are any, passing, warning, or critical. The any state is a wildcard that can be used to return all checks.

**Comment by dyrnq** [comment]
@Fabriceli 

I encountered difficulties.

there has a dependency return of watch_result.body from `/catalog/services` , that not have in /health/state/any.

So need watch /health/state/any, then fetch service list from `/catalog/services`, and loop /catalog/services `s result list continue?

```bash
        for service_name, _ in pairs(watch_result.body) do
            -- check if the service_name is 'skip service'
            if skip_service_map[service_name] then
                goto CONTINUE
            end
```

**Comment by Fabriceli** [comment]
@dyrnq, that is the way

**Comment by Fabriceli** [comment]
@dyrnq, that is the way

**Comment by dyrnq** [comment]
In this way, I started to modify and found a problem

When the node health changes from healthy to unhealthy, Consul will find the update faster, while Apisix will finish the update more slowly.

there is a test case

```bash
while true; do 
echo -n "--->$(date)==="; 
curl --connect-timeout 1 --max-time 1 http://127.0.0.1:9080; 
echo "fetch healthy from consul"; 
curl -fsSL http://127.0.0.1:8500/v1/health/service/nginx?passing=true | jq -r '.[] | "\(.Service.Address):\(.Service.Port)"';   
echo "dump from apisix ******" ; 
curl -fsL http://127.0.0.1:9090/v1/discovery/consul/dump | jq -r '.services."nginx"[] | "\(.host):\(.port)"'; 
sleep 1s;
done
```


```bash
--->Thu Feb 23 15:23:19 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:23:21 CST 2023===curl: (28) Operation timed out after 1002 milliseconds with 0 bytes received
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:23:23 CST 2023===curl: (28) Operation timed out after 1004 milliseconds with 0 bytes received
fetch health from consul
192.168.33.4:18080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:23:25 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
```

Although consul also has a little delay, but apisix more obvious.

**Comment by dyrnq** [comment]
More test here, there is a node from unhealthy to healthy,  consul update at 15:35:09 and apisix update at 15:35:28.
```bash
--->Thu Feb 23 15:35:08 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:09 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:10 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:12 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:13 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:14 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:15 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:16 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:18 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:19 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:20 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:21 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:22 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:24 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:25 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:26 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:27 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:48080
--->Thu Feb 23 15:35:28 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:35:30 CST 2023===nginx-2
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:35:31 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:35:32 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:35:33 CST 2023===nginx-4
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
--->Thu Feb 23 15:35:34 CST 2023===nginx-1
fetch health from consul
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
dump from apisix ******
192.168.33.4:18080
192.168.33.4:28080
192.168.33.4:48080
```

**Comment by Fabriceli** [comment]
> 

Maybe you need to print more debug log

**Comment by dyrnq** [comment]
It seems not print log.info info in this init.lua file, how to open debug level? 

I try to config conf/debug.yaml ,it not working fot this

**Comment by dyrnq** [comment]
> > 
> 
> Maybe you need to print more debug log

OK, I config here, it is working, i will try continue test
```bash
nginx_config:
  error_log_level:  info
```

**Comment by dyrnq** [comment]
@spacewander @Fabriceli I have test the modify and PR, pls help check. 

now the consul healthy and apisix dump were updated almost at the same time.

If there is still delay update, it is the consult itself

**Comment by monkeyDluffy6017** [comment]
considered resolved
