### ISSUE TITLE
bug: Disabled basic-auth still need authorazation

### ISSUE THREAD

**Issue by gaoxingliang** [apache/apisix#8857]
### Current Behavior

The problem is when the basic-auth is already disabled for a route, it still needs authorization.
Reproduce steps:
1. create a route route-a without basic-auth plugin.
2. create a consumer with basic-auth plugin.
3. enable basic auth for route-a.
4. do some curl test for route-a and check the auth is working.
5. disable basic auth for route-a in apisix-dashboard.
6. Try step4 again. it shows we still need authorization.

I checked the json conf:
```
"plugins": {
    "basic-auth": {
      "disable": true
    },
```
I worked around by removing whole `basic-auth` in the `plugins` part.

 

### Expected Behavior

The disabled plugin should not be enable.

### Steps to Reproduce

1. See above

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
What's the version of your dashboard? It might be due to the incompatibility between APISIX 3.x and APISIX dashboard 2.x

**Comment by gaoxingliang** [comment]
@tokers I'm using the apisix dashboard 2.15.0.  I will try to upgrade to 3.0.0 and re-check.

**Comment by shreemaan-abhishek** [comment]
@gaoxingliang any updates? Please let us know if the issue does not exist. We will close it.
