### ISSUE TITLE
feat: As a user, I want to api parameter encryption and decryption, so that support plug-in

### ISSUE THREAD

**Issue by wulinghui** [apache/apisix#8858]
### Description

see [Gateway 接口参数加解密](https://blog.csdn.net/qq_17213067/article/details/127859326)

If I need to implement it myself, I don't know whether the encryption library has been included and how to use the encryption api

We look forward to your reply.

**Comment by monkeyDluffy6017** [comment]
Could you describe it more clearly?

**Comment by wulinghui** [comment]
I hope to make a decryption plug-in.

The body content passed by the user is encrypted by the encryption algorithm, and then the decrypted body is reversely proxy to the original upstream in Apisix

**Comment by wulinghui** [comment]
I hope to make a decryption plug-in.

The body content passed by the user is encrypted by the encryption algorithm, and then the decrypted body is reversely proxy to the original upstream in Apisix, so that the back-end services are not required to do the encryption function. Similarly, I want to encrypt the response body.

**Comment by jiangfucheng** [comment]
Maybe we can implement a plugin that can decrypt "query string" or body of request, and encrypt body of response.

**Comment by wulinghui** [comment]
Yes, this function is necessary. If available, support utf-8 encoding as much as possible. 
Get can teach me the key encryption code, and I will tune it.

**Comment by wulinghui** [comment]
Can you tell me about when I can arrange this function to go online？
