### ISSUE TITLE
apisix 路由 匹配条件 路径是否支持path中包含参数

### ISSUE THREAD

**Issue by leekari5548** [apache/apisix#8859]
### Description

apisix 设置 路由 匹配条件 路径是否支持path中包含参数，比如 `/user/{userId}`这样的

### Environment

- APISIX version  3.1.0
- Operating system  centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
See https://github.com/api7/lua-resty-radixtree#parameters-in-path

**Comment by leekari5548** [comment]
thanks
