### ISSUE TITLE
open etcd auth have some problem

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8862]
### Description

when open the etcd auth,use the admin api update route,sometimes happen the error like this:

failed to put route[/routes/220] to etcd: etcdserver: invalid auth token

2023/02/15 14:41:56 [error] 44#44: *6633274 [lua] routes.lua:185: failed to put route[/routes/220] to etcd: etcdserver: invalid auth token, client: 10.1.1.94, server: , request: "PUT /apisix/admin/routes/220 HTTP/1.1", host: "apisix-test-admin.sa:9180"

but the username and password is in the config.yaml and some time retry is ok.

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Could you provide a minimal reproduction use case with detailed steps?

**Comment by kellyseeme** [comment]
etcd open auth：
etcdctl user add root , then input root password
etcdctl auth enable
then config the apisix config.yaml ，below etcd add:
user: root 
password: $(the root password)
then use the admin api to add route , probability have the errors,not one hundred percent，no pattern found。
。

**Comment by kellyseeme** [comment]
use the admin api of get is no problem,post have ten percent happen of {"error_msg":"etcdserver: invalid auth token"}

and there is no requests for the apisix pod.
