### ISSUE TITLE
help request: plugins.proxy-rewrite does not work

### ISSUE THREAD

**Issue by YangChaorix** [apache/apisix#8864]
### Description

route config ：
`
{
  "uri": "/worksheet/*",
  "name": "test1",
  "methods": [
    "GET",
    "POST"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "/worksheet/",
        "/api/v2/open/worksheet/"
      ]
    }
  }
}`

I try to request path : /worksheet/getFilterRows but  does not work, upstream nginx logs path still not being replaced

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/24434787/218965324-626b8bbd-eeac-4d67-bb45-7a6359d0b90e.png">

### Environment

- APISIX version (run `apisix version`): 3.10
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Try to set the `regex_uri` to:

```json
"regex_uri": ["/worksheet/(.*)", "/api/v2/open/worksheet/$1"]
```

**Comment by YangChaorix** [comment]
> 

<img width="367" alt="image" src="https://user-images.githubusercontent.com/24434787/218983438-180f4a89-c98a-464d-8eea-023c73dc0b79.png">

I have tried this one。but still  does not work
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/24434787/218983790-96f41b74-5935-476d-b3b3-24e05ed6ab9a.png">

I feel like this is a bug。。

**Comment by YangChaorix** [comment]
> Try to set the `regex_uri` to:
> 
> ```json
> "regex_uri": ["/worksheet/(.*)", "/api/v2/open/worksheet/$1"]
> ```

hallo， I found the cause of the problem。。。

If I enable the plugin log-rotate， rewrites will not work，for example：

<img width="770" alt="image" src="https://user-images.githubusercontent.com/24434787/219571836-9718c55f-0284-4a8d-9288-7a0b57a6ab5c.png">

Do you know what this is about?

**Comment by YangChaorix** [comment]
@tokers Please help me to see

**Comment by YangChaorix** [comment]
> Try to set the `regex_uri` to:
> 
> ```json
> "regex_uri": ["/worksheet/(.*)", "/api/v2/open/worksheet/$1"]
> ```

I solved it
i have to config all plugins in config.yaml, Because the overwrite operation is executed，for example：
<img width="631" alt="image" src="https://user-images.githubusercontent.com/24434787/219576679-dd786a25-d58b-4c05-8cf0-e7cc728c70b1.png">

**Comment by shreemaan-abhishek** [comment]
> If I enable the plugin log-rotate， rewrites will not work，for example：
Can you share your error log?

**Comment by YangChaorix** [comment]
> > If I enable the plugin log-rotate， rewrites will not work，for example：
> 
> Can you share your error log?

thanks a lot, I solved it, Look at the comments above 👆

**Comment by YangChaorix** [comment]
<img width="638" alt="image" src="https://user-images.githubusercontent.com/24434787/221494886-bf607c60-a7a7-4b5e-a9b5-be732f07ffab.png">


<img width="857" alt="image" src="https://user-images.githubusercontent.com/24434787/221495484-4e4911eb-2215-41e0-aa69-644221335603.png">

I found a new problem，when i use the plugins log-rotate，The process created a new file access.log without write access.

@shreemaan-abhishek
