### ISSUE TITLE
help request:  APISIX Dashboard Configure Active Health Check

### ISSUE THREAD

**Issue by liufeiguo** [apache/apisix#8868]
### Description

I configured an active health check for routing：
![image](https://user-images.githubusercontent.com/46086269/219249900-24cc265f-d945-426d-bf31-31a02243f377.png)
But when I access the route, I can correctly proxy to the upstream service, but the configured active health request path does not receive any requests. Is it a bug?

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: 2.13
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Could you try to use the `curl` command to reproduce the problem?

**Comment by liufeiguo** [comment]
> Could you try to use the `curl` command to reproduce the problem?
`_curl http://127.0.0.1:9080/apisix/admin/routes/1003 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
	"uri": "/testportal/*",
	"name": "testportal",
	"desc": "netauth管理端路由",
	"priority": 1,
	"upstream": {
		"nodes": [{
			"host": "10.210.21.101",
			"port": 80,
			"weight": 1
		}],
		"retries": 2,
		"timeout": {
			"connect": 9,
			"send": 3,
			"read": 3
		},
		"type": "roundrobin",
		"scheme": "http",
		"pass_host": "pass",
		"keepalive_pool": {
			"idle_timeout": 60,
			"requests": 1000,
			"size": 320
		},
		"retry_timeout": 2,
		"checks": {
			"active": {
				"timeout": 5,
				"http_path": "/test/test",
				"host": "10.210.21.113",
				"port": 9077,
				"healthy": {
					"interval": 2,
					"successes": 1
				},
				"unhealthy": {
					"interval": 1,
					"http_failures": 2
				},
				"req_headers": ["User-Agent: curl/7.29.0"]
			},
			"passive": {
				"healthy": {
					"http_statuses": [200, 201],
					"successes": 3
				},
				"unhealthy": {
					"http_statuses": [500],
					"http_failures": 3,
					"tcp_failures": 3
				}
			}
		}
	},
	"labels": {
		"API_VERSION": "v1.0"
	},
	"status": 1
}'_`
When I visit http://127.0.0.1:9080/testportal/ Corresponding active health check

http://10.210.21.113:9077 The service did not receive any requests, and the active health check did not send messages to the specified path

**Comment by liufeiguo** [comment]
> Could you try to use the `curl` command to reproduce the problem?

**curl http://127.0.0.1:9080/apisix/admin/routes/1003 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
	"uri": "/testportal/*",
	"name": "testportal",
	"desc": "netauth管理端路由",
	"priority": 1,
	"upstream": {
		"nodes": [{
			"host": "10.210.21.101",
			"port": 80,
			"weight": 1
		}],
		"retries": 2,
		"timeout": {
			"connect": 9,
			"send": 3,
			"read": 3
		},
		"type": "roundrobin",
		"scheme": "http",
		"pass_host": "pass",
		"keepalive_pool": {
			"idle_timeout": 60,
			"requests": 1000,
			"size": 320
		},
		"retry_timeout": 2,
		"checks": {
			"active": {
				"timeout": 5,
				"http_path": "/test/test",
				"host": "10.210.21.113",
				"port": 9077,
				"healthy": {
					"interval": 2,
					"successes": 1
				},
				"unhealthy": {
					"interval": 1,
					"http_failures": 2
				},
				"req_headers": ["User-Agent: curl/7.29.0"]
			},
			"passive": {
				"healthy": {
					"http_statuses": [200, 201],
					"successes": 3
				},
				"unhealthy": {
					"http_statuses": [500],
					"http_failures": 3,
					"tcp_failures": 3
				}
			}
		}
	},
	"labels": {
		"API_VERSION": "v1.0"
	},
	"status": 1
}'**
When I visit http://127.0.0.1:9080/testportal/ Corresponding active health check

http://10.210.21.113:9077 The service did not receive any requests, and the active health check did not send messages to the specified path

**Comment by liufeiguo** [comment]
> Could you try to use the `curl` command to reproduce the problem?

Today, I tested again that the active health check configuration of upstream.checks.active.host host IP must appear in the upstream service of this routing agent before the active health check will take effect. When the IP configured by upstream.checks.active.host is not in the upstream service of this routing agent, the active health check will not take effect.
Examples of success are as follows:
![image](https://user-images.githubusercontent.com/46086269/220079572-0636e751-e2bf-47d0-880e-a7de53e5de60.png)
![image](https://user-images.githubusercontent.com/46086269/220079607-80a5f597-2a6d-4aa3-94fa-0c611705fccc.png)

**Comment by monkeyDluffy6017** [comment]
Try to use the `curl` command first, there are successful use cases in the doc.

**Comment by liufeiguo** [comment]
> Try to use the `curl` command first, there are successful use cases in the doc.

I have tested that curl and page operation are the same. Now I want to know whether the passive health check will be sent passively when the request is triggered
