### ISSUE TITLE
help request: After creating upstream, if the timeout field is not used, what is the default timeout and where is it configured?

### ISSUE THREAD

**Issue by lanyazhizhou** [apache/apisix#8870]
### Description

在dashbord界面创建一个上游，如下：
```
{
  "nodes": [
    {
      "host": "172.16.10.12",
      "port": 8153,
      "weight": 1
    }
  ],
  "retries": 50,
  "type": "roundrobin",
  "hash_on": "vars",
  "scheme": "http",
  "pass_host": "pass",
  "name": "test"
}
```
没有配置timeout字段，则其默认的timeout是多少？怎么配置默认的timeout？

### Environment

- APISIX version (run `2.6`):
- Operating system (run `linux`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
maybe you can refer links like below:

https://github.com/apache/apisix/blob/e6888819a27c488b0dba6121e5b62bdc92a20a78/apisix/schema_def.lua#L389
https://github.com/apache/apisix/blob/e6888819a27c488b0dba6121e5b62bdc92a20a78/apisix/schema_def.lua#L113-L121

https://apisix.apache.org/docs/apisix/admin-api/#upstream-api

**Comment by lanyazhizhou** [comment]
> maybe you can refer links like below:
> 
> https://github.com/apache/apisix/blob/e6888819a27c488b0dba6121e5b62bdc92a20a78/apisix/schema_def.lua#L389
> 
> 
> https://github.com/apache/apisix/blob/e6888819a27c488b0dba6121e5b62bdc92a20a78/apisix/schema_def.lua#L113-L121
> 
> https://apisix.apache.org/docs/apisix/admin-api/#upstream-api

Thank you，This is really what I want！
