### ISSUE TITLE
how to use ext-plugin-pre-req change apisix request body。 base on apisix-go-plugin-runner

### ISSUE THREAD

**Issue by hongdingyi** [apache/apisix#8875]
### Description

how to use ext-plugin-pre-req change apisix request body。 base on apisix-go-plugin-runner

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Not yet supported

**Comment by hongdingyi** [comment]
> Not yet supported

Can you support me。thank you


func(r *Request) SetBody(body []byte)error{
	builder := util.GetBuilder()
	varName := builder.CreateString(string(body))
	ei.VarStart(builder)
	ei.VarAddName(builder, varName)
	varInfo := ei.VarEnd(builder)
	_, err := r.askExtraInfo(builder, ei.InfoRespBody + 1, varInfo)
	util.PutBuilder(builder)
	return err
}


    if info_type == extra_info.RespBody + 1 then
        local info = req:Info()
        local var_req = extra_info_var.New()
        var_req:Init(info.bytes, info.pos)
        local var_name = var_req:Name()
        core.request.set_body(var_name)
        res = 0


function _M.set_body(new_body_data)
    ngx.req.set_body_data(new_body_data)
    ngx.req.set_header("Content-Length", tostring(#new_body_data))
end

**Comment by hongdingyi** [comment]
I really need your help。I've already implemented the code
