### ISSUE TITLE
help request: upstream rejected request with error 8 while reading response header from upstream

### ISSUE THREAD

**Issue by ganarajtejasvi** [apache/apisix#8883]
### Description

We are trying to use APISIX with grpc and a grpc-web request through apisix is resulting in a 502 response for once in 3-4 request. Ie the response for the below sample request is received sometimes but not always.

Any help/resolution/extra configuration that would be required to route grpc without errors on APISIX would be appreciated. 
Have searched this error and have found one  [(issue on nginx)](https://trac.nginx.org/nginx/ticket/2376) but since the issues is not always found not sure how to handle this.

`curl --location --request POST 'http://apisix-server.amazonaws.com:80/example_grpc.ExampleService/search' \
--header 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'authorization: Bearer token’ \
--header 'content-type: application/grpc-web+proto' \
--header 'origin: https://origin.example.com' \
--header 'referer: https://origin.example.com/' \
--header 'x-grpc-web: 1' \
--header 'x-user-agent: grpc-web-javascript/0.1' \
--header 'Host: api.example.com' \
--data-raw '4*j
ABCD1234
2
20
38'`

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux apisix-567c58f6dc-4dm4k 5.4.228-131.415.amzn2.aarch64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Could you provide a minimal reproduction use case with detailed steps?

**Comment by ganarajtejasvi** [comment]
We managed to fix this by adding the following parameters to our apisix nginx.conf
`  http_configuration_snippet:      |
    client_body_buffer_size 2048k;
    client_header_buffer_size 4k;
    proxy_buffering on;
    proxy_buffers 4 256k;
    proxy_buffer_size 128k;
    proxy_busy_buffers_size 256k;
    proxy_max_temp_file_size 0;
    large_client_header_buffers 4 32k;`

Post this the responses have been successful and we have not seen any errors.
