### ISSUE TITLE
502 Bad Gateway bug issue

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8885]
### Description

When I request to create a consumer, 502 Bad Gateway is displayed;

 curl http://127.0.0.1:9080/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "foo",
    "plugins": {
        "basic-auth": {
            "username": "foo",
            "password": "bar"
        }
    }
}'
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Environment

- APISIX version 2.13
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by githubxubin** [comment]
the error.log is :
*148532 [lua] balancer.lua:382: run(): failed to set server peer [90:1] err: no host allowed while connecting to upstream, client: 172.18.0.1, server: _, request: "PUT /apisix/admin/consumers HTTP/1.1", host: "127.0.0.1:9080"

**Comment by monkeyDluffy6017** [comment]
The port is not right, use `9180` instead of `9080`

**Comment by githubxubin** [comment]
> The port is not right, use `9180` instead of `9080`

you are worry , my apisix version is 2.15 not 3.1 ，the port is 9080,i am true,That's what the official document says

**Comment by tokers** [comment]
> > The port is not right, use `9180` instead of `9080`
> 
> you are worry , my apisix version is 2.15 not 3.1 ，the port is 9080,i am true,That's what the official document says

It depends on how you install and configure APISIX. Please checkout the `config.yaml` to know if the port is `9180`.

**Comment by lchpersonal** [comment]
I got the same issues
