### ISSUE TITLE
The health check is not working properly！！！

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8889]
### Description

I configured the active health check and filled in the request path, but the active health check did not send a request to the address, so it could not be used at all. I configured the dashboard instead. Please help me! 
thanks

### Environment

- APISIX version (run `2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: :2.13-alpine 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Did you try to send a request, we only start the health check when the upstream is hit by a request. There won't be any health check if an upstream is configured but isn't in used.

**Comment by githubxubin** [comment]
thanks
