### ISSUE TITLE
what is client-control unit

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8892]
### Description

<img width="847" alt="image" src="https://user-images.githubusercontent.com/535200/220100721-15d53feb-f951-4e8c-b5e5-4b3fe866dad3.png">

in client-control，what unit of max_body_size.

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
The unit is bytes, and you can get the answer simply by trying

**Comment by kellyseeme** [comment]
> The unit is bytes, and you can get the answer simply by trying

tks，yes，i have try,ask this is to confirm the result,emmm,may be in the docs we can add it , reduce the user time to try it.

**Comment by monkeyDluffy6017** [comment]
@kellyseeme Would you like to update the doc?

**Comment by kellyseeme** [comment]
> @kellyseeme Would you like to update the doc?

maybe i can try ,but i dont have experience for this.
