### ISSUE TITLE
bug: Is there an extra undefined conf parameter here?

### ISSUE THREAD

**Issue by shima-park** [apache/apisix#8893]
### Current Behavior

nothing.

### Steps to Reproduce

1

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shima-park** [comment]
https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/limit-count-local.lua#L58

**Comment by monkeyDluffy6017** [comment]
@mscb402

**Comment by mscb402** [comment]
Yes you are right, conf parameter is no need

**Comment by mscb402** [comment]
I will fix that
