### ISSUE TITLE
system backup and data recovery?

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8895]
### Description

How does apisix do system backup and data recovery?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
ref: https://github.com/apache/apisix/issues/8899#issuecomment-1438376073
