### ISSUE TITLE
How to implement periodic data backup?

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8899]
### Description

I want to implement ETCD data backup regularly, how should I do? Whether there is documentation or solution!!!

### Environment

- APISIX version 2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
This is not related to APISIX. Maybe you can find helps from ETCD community. Articles like https://docs.vmware.com/en/VMware-Application-Catalog/services/tutorials/GUID-backup-restore-data-etcd-kubernetes-index.html may help you.
