### ISSUE TITLE
help request: How to get the matched route(or route uri) in external plugin(Java) ext-plugin-post-req phase?

### ISSUE THREAD

**Issue by hmh-the-one** [apache/apisix#8905]
### Description

Here is one route:  
apisix/admin/routes/routes1  
```json
{
    "methods":["GET","POST"],
    "uri":"/something/*",
    "upstream_id":"auth",
    "plugins":{
        "proxy-rewrite": {
            "uri": "/something/*"
        },
        "ext-plugin-post-req":{
            "conf":[
                {
                    "name":"TestFilter"
                }
            ]
        }
    }
}
```
And I have multiple routes with same TestFilter & config. In Java-implemented external plugin, how can I get the already matched route id or route uri in PluginFilter implementation, the route only, no need for any other plugin config or filter result. As the above example,  that is "routes1" (id value) or "/something/*" (uri value).   
Where can I find the full available config list that the plugin can receive? Is the ext-plugin-post-req conf.value and global environment properties available?
Passing the id through each route's ext-plugin-post-req conf.value is one way, though
Thanks in advanced.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):
version: 3.1.0

**Comment by soulbird** [comment]
You mean route_id？

**Comment by hmh-the-one** [comment]
> You mean route_id？

Yes

**Comment by soulbird** [comment]
Try `request.getVars("route_id")`

**Comment by hmh-the-one** [comment]
> Try `request.getVars("route_id")`

It works, thanks. Where can  I find the full list of "vars" available in Java external plugin?

**Comment by soulbird** [comment]
see: https://github.com/apache/apisix/blob/master/docs/en/latest/apisix-variable.md
