### ISSUE TITLE
route 404 why？？？

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8906]
### Description

I simply call to get the token interface and directly prompt the route 404. Is there a problem with my configuration where I execute apisix 2.15-alpine according to the official documentation;

[root@localhost ~]# curl http://127.0.0.1:9080/apisix/plugin/jwt/sign?key=user-key -i
HTTP/1.1 404 Not Found
Date: Wed, 22 Feb 2023 02:23:34 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX/2.15.0

{"error_msg":"404 Route Not Found"}

### Environment

- APISIX version 2.15-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by githubxubin** [comment]
2023/02/22 03:12:03 [error] 45#45: *21384 [lua] balancer.lua:349: run(): proxy retry timeout, retry count: 0, deadline: 1677035518.898 now: 1677035523.899 while connecting to upstream, client: 172.18.0.1, server: _, request: "GET /apisix/plugin/jwt/sign?key=user-key HTTP/1.1", upstream: "http://12.12.12.12:1/apisix/plugin/jwt/sign?key=user-key", host: "127.0.0.1:9080"

**Comment by githubxubin** [comment]
i want to know the public-api must to config in plugin module ,i set the public-api in route ,but it cant truly work, help me ,please!!!

**Comment by tokers** [comment]
> i want to know the public-api must to config in plugin module ,i set the public-api in route ,but it cant truly work, help me ,please!!!

Sorry, I cannot understand your meaning correctly. You have to expose the jwt sign API via the `public-api` plugin. How did you create this route?

**Comment by githubxubin** [comment]
> > i want to know the public-api must to config in plugin module ,i set the public-api in route ,but it cant truly work, help me ,please!!!
> 
> Sorry, I cannot understand your meaning correctly. You have to expose the jwt sign API via the `public-api` plugin. How did you create this route?

Can't you configure public-api through global plugin config?
