### ISSUE TITLE
public-api cant work in plugin config

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8908]
### Current Behavior

i set public-api in public config,not in route, as a result ,all route request response 400????????
i do not  know  ......

### Expected Behavior

apisix/plugin/jwt/sign can access truly

### Error Logs

2023/02/22 03:42:15 [error] 46#46: *135295 [lua] balancer.lua:349: run(): proxy retry timeout, retry count: 0, deadline: 1677037330.214 now: 1677037335.214 while connecting to upstream, client: 192.168.88.66, server: _, request: "GET /image/finger.png HTTP/1.1", upstream: "http://12.12.12.12:1/image/finger.png", host: "10.210.21.110:9080", referrer: "http://10.210.21.110:9080/test2/"

### Steps to Reproduce

apisix version is 2.15

### Environment

- APISIX version 2.15-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Can you share your config here? Mabe your configuration is wrong.

**Comment by githubxubin** [comment]
> Can you share your config here? Mabe your configuration is wrong.

1.first one: the  plugin config is :
{
  "disable": false,
  "uri": "/apisix/plugin/jwt/sign"
}
2.the route config is :
{
  "uri": "/test1/*",
  "name": "xubin_01",
  "desc": "xubin_01",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "plugins": {
    "proxy-rewrite": {
      "regex_uri": [
        "^/test1(/|$)(.*)",
        "/$2"
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "10.210.21.123",
        "port": 80,
        "weight": 1
      }
    ],
    "retries": 2,
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    },
    "retry_timeout": 2
  },
  "labels": {
    "API_VERSION": "v1.0"
  },
  "status": 1
}

and it return 400 Bad Request;
the error log is：
#48: *1490106 [lua] balancer.lua:349: run(): proxy retry timeout, retry count: 0, deadline: 1677057988.934 now: 1677057993.935 while connecting to upstream, client: 192.168.88.66, server: _, request: "GET /js/login/thirdlogin.js HTTP/1.1", upstream: "http://12.12.12.12:1/js/login/thirdlogin.js", host: "10.210.21.110:9080", referrer: "http://10.210.21.110:9080/test1/"

**Comment by mscb402** [comment]
In your config, I don't see any `public-api` what this issue is related with `public-api`

**Comment by mscb402** [comment]
Why did you set `public-api` in the global plugin config? Can you explain that? The Public-API only exposes some internal API which is registered by some plugin itself.

**Comment by githubxubin** [comment]
> 

i think that if i want to expose the  interface "/apisix/plugin/jwt/sign" , i can config the public-api in global plugin config,Isn't it?
I understand that global is valid for all routes

**Comment by githubxubin** [comment]
> Why did you set `public-api` in the global plugin config? Can you explain that? The Public-API only exposes some internal API which is registered by some plugin itself.

or the scope of the global plug-in list is global and is applicable to all routes. Am I understanding correctly？

**Comment by mscb402** [comment]
If you set public-api plugin in the router. This means this route will be controlled by public-api plugin. If you register it to global config, means all routers will be controlled by public-api. And public-api will not release control even if this URL does not match any public API.
So you can't using public-api in global config.

**Comment by githubxubin** [comment]
> If you set public-api plugin in the router. This means this route will be controlled by public-api plugin. If you register it to global config, means all routers will be controlled by public-api. And public-api will not release control even if this URL does not match any public API. So you can't using public-api in global config.

OK thanks，i find the public-api in global plugin config ,i think it can work in  my mind
