### ISSUE TITLE
 jwt-auth plugins use is failed to verify jwt

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8910]
### Description

i set public-api in public config,not in route, as a result ,all route request response 400????????
i do not know ......

when i delete the public-api in plugin config,the route can access truly! 
help me please!

### Environment

- APISIX version 2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
What is `public config`?

**Comment by githubxubin** [comment]
> What is `public config`?

i have solved! thanks
