### ISSUE TITLE
help request: 使用nginx重写X-Request-Id传递给apisix

### ISSUE THREAD

**Issue by loveyang2012** [apache/apisix#8913]
### Description

在使用nginx重写X-Request-Id传递给apisix时，发现apisix日志中的request-id字段不是nginx传递的。
nginx配置：
location / {
    proxy_pass http://upstream;
    set $req_id  123
    proxy_set_header X-Request-Id $req_id;
}
apisix能获取自定义header么，并打印到日志中？

### Environment

- APISIX version (run `apisix version`): 3.1
- Operating system (run `uname -a`):  centos

**Comment by tokers** [comment]
@loveyang2012 It's tough to help you because information is not enough. How did you configure the `request-id` field in APISIX log?

**Comment by soulbird** [comment]
Which variable are you using to log the request-id

**Comment by loveyang2012** [comment]
> @loveyang2012 It's tough to help you because information is not enough. How did you configure the `request-id` field in APISIX log?
I just set  $request_id in APISIX log ,do not anything else.

**Comment by tokers** [comment]
> request_id

```
$request_id

unique request identifier generated from 16 random bytes, in hexadecimal (1.11.0)
```

It doesn't identical with the `X-Request-ID` header.

**Comment by loveyang2012** [comment]
请求流程：nginx--->apisix--->upstream，需求是 使用X-Request-ID串联 nginx到apisix的请求，通过nginx把X-Request-ID传递到apisix，apisix 应该做什么配置么？

**Comment by wadefelix** [comment]
@loveyang2012  The issue is solved in which version?

I encounterd it in verison 3.2.1
