### ISSUE TITLE
help request:  health check monitoring on apisix dashboard

### ISSUE THREAD

**Issue by sudo-shubh12** [apache/apisix#8918]
### Description

We have created upstream server with health check monitoring. Is there any way to get the health check status on the API dashboard?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Dashboard does not have this function yet, you can check it through the API: https://github.com/apache/apisix/blob/master/docs/en/latest/control-api.md#get-v1healthcheck

**Comment by shreemaan-abhishek** [comment]
@sudo-shubh12 I am closing this issue reopen if you have further questions.
