### ISSUE TITLE
help request: when i use roundrobin on upstream,i got a not balance load

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#8919]
### Description

i have a upstream and this upstream have multi-nodes,these nodes's weight is same(like 100),and i didn't set health-check.But when try to visit the domain which is use this upstream ,i got a not balance load,such as first ip got twice load more than second ip.
but other upstream have no this problem.if this is a bug or i have error config?

### Environment

- APISIX version (run `apisix version`):2.9

**Comment by tokers** [comment]
@Nobilta Did you have the statistics about the request distributions? Balancing is relative, the round-robin cannot make sure the load balancing is even absolutely. What about the samples? What about your API request types (HTTP or WebSocket or others)?

**Comment by Nobilta** [comment]
> @Nobilta Did you have the statistics about the request distributions? Balancing is relative, the round-robin cannot make sure the load balancing is even absolutely. What about the samples? What about your API request types (HTTP or WebSocket or others)?

开启websocket，在测试过程中3个ip的负载大概为1：1：8，且此问题偶发，其他upstream（相同配置）并没有这个问题

**Comment by soulbird** [comment]
Please use the latest version

**Comment by Nobilta** [comment]
> 

@soulbird To see if this is the problem mentioned above, it is a bit expensive to use the latest version😂

**Comment by soulbird** [comment]
Looks like this is the problem, version 2.9 does not contain this fix. If the upgrade is troublesome, you can consider manually modifying the code to verify it

**Comment by Nobilta** [comment]
> Looks like this is the problem, version 2.9 does not contain this fix. If the upgrade is troublesome, you can consider manually modifying the code to verify it

@soulbird thank you so much, i wiil modify the code to verify it
