### ISSUE TITLE
help request: the minimum in healthcheck schema is incorrect

### ISSUE THREAD

**Issue by spacewander** [apache/apisix#8937]
### Description

It's meaningless to use zero as the minimum:
https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L239

We set them to zero because we wanted to use a default healthcheck in https://github.com/apache/apisix/pull/5589.
However, as this PR is surpassed by https://github.com/apache/apisix/pull/7850, there is no need to keep the zero value.

### Environment

- APISIX version (run `apisix version`): master
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Neilblaze** [comment]
@spacewander Can you assign me please if this is up for grabs?

**Comment by navendu-pottekkat** [comment]
Sure @Neilblaze cc: @spacewander

**Comment by Neilblaze** [comment]
@navendu-pottekkat I'm a bit confused about whether I'm going to break the tests by directly removing [`minimum = 0`](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L239) or we need to set the props to a minimum of `1`? 

> Nonetheless, for now I'm going with the former one i.e. I'm removing the `minimum` prop from [`successes`](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L237).

**Comment by navendu-pottekkat** [comment]
@spacewander can chime in here.

**Comment by spacewander** [comment]
> @navendu-pottekkat I'm a bit confused about whether I'm going to break the tests by directly removing [`minimum = 0`](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L239) or we need to set the props to a minimum of `1` or default at `true`?
> 
> > Nonetheless, for now, I'm going with the former one i.e. I'm removing the `minimum` prop from [`successes`](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L237).

What do you mean 'default at `true`'? There is no default value in the healthcheck schema. Can you give some code as an example?

**Comment by spacewander** [comment]
If you mean the default value in
https://github.com/apache/apisix/blob/8d38884a7ac1d08c529e7f8494fa8ea0d01c1872/apisix/schema_def.lua#L263

it is not relative to the topic here.

**Comment by Neilblaze** [comment]
Gotcha! Thanks for the clarity @spacewander 😄 
I'm moving forward with removing `minimum = 0` from [here](https://github.com/apache/apisix/blob/d3ac217cb26ab731d51f1ef8275932df8bf72c7b/apisix/schema_def.lua#L239) instead of assigning `minimum = 1` then.

**Comment by pottekkat** [comment]
Closing this as it is confirmed that this is not an issue: https://github.com/apache/apisix/pull/8949#issuecomment-1759535250
