### ISSUE TITLE
how to use vars to match rule

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#8938]
### Description

<img width="452" alt="image" src="https://user-images.githubusercontent.com/535200/221166155-f6a1c6e8-4bf3-43e5-9dd2-fd7733c6da5f.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/535200/221166343-cc768933-fe3f-4ffe-8bb8-aea08891314d.png">

curl http://10.1.1.1/users/../123
{"error_msg":"404 Route Not Found"}

uris":["\/*"],why this not match the route?how can i set this?

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
`..` is a dangerous symbol in URI, and APISIX will normalize the URI before the route matching. So actually, the URI used for matching is `/123`, not `/users/../123`.

**Comment by kellyseeme** [comment]
yes ,this is dangerous,we want to set some rules to reject the request
