### ISSUE TITLE
help request: how to join slack channel?

### ISSUE THREAD

**Issue by s0l4r** [apache/apisix#8940]
### Description

When trying to join the Slack channel, it says it requires an @apache.org e-mail adress? 

"Don’t have an @apache.org email address?
Contact the workspace administrator at ASF for an invitation."

### Environment

Slack for Mac

**Comment by Preshh0** [comment]
I have the same experience.

**Comment by Neilblaze** [comment]
Duplicate of #8907

**Comment by Ajay-singh1** [comment]
@s0l4r You Can Close this issue.

**Comment by goal31121** [comment]
hello
I want to join the this slack
but I have not a ASF account
How to get the account?
