### ISSUE TITLE
help request: k8s ingress nginx as a upstream in apisix does not work!

### ISSUE THREAD

**Issue by javad2157** [apache/apisix#8944]
### Description

hello everybody. I ran apisix with docker compose official way 
![image](https://user-images.githubusercontent.com/89399278/221378210-0e4a3192-a0b9-45f2-bd60-bff7247bf11d.png)
i have a kubernetes cluster that i use ingress nginx for external traffic to my deployment.
when i create an upstream with ingress nginx address in apisix dashboard i does not get any response for my api call.
but when i use node port instead of ingress nginx for accessing to my deployment api application, everything is fine and work.
![image](https://user-images.githubusercontent.com/89399278/221378626-1a35d690-61d5-4ac2-8447-48cf826c9cbf.png)
I don't have any network problem like resolving dns and access problem, surely.
I can call api with ingress url in apisix server with curl command without any problem.
appreciate for any help.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Is there any error log?

**Comment by shreemaan-abhishek** [comment]
ping @javad2157
