### ISSUE TITLE
help request: 如何在aarch64安装apisix，最好是rpm的

### ISSUE THREAD

**Issue by xinqing123** [apache/apisix#8946]
### Description

apisix如何在aarch64安装，没找到apisix .aarch.rpm文件，现在尝试源码安装，但是源码安装，不知道怎么操作，官网的有点看不懂

### Environment

- APISIX version (run `apisix version`):2.13.1
- Operating system (run `uname -a`): aarch64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
```
yum install -y https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm
yum install apisix
```

**Comment by shreemaan-abhishek** [comment]
@xinqing123 I am closing this issue. Please reopen if you have further questions.
