### ISSUE TITLE
docs: How to login to dashboard on Getting Started

### ISSUE THREAD

**Issue by dashohoxha** [apache/apisix#8957]
### Current State

The dashboard section of the Getting Started does not explain how to login on the dashboard:
https://apisix.apache.org/docs/apisix/getting-started/#using-the-apisix-dashboard

### Desired State

It should explain that you can use username 'admin' and password 'admin' to login. Or that these credentials can be found on the YAML config file for the dashboard.

**Comment by Neilblaze** [comment]
@nfrankel, @juzhiyuan, @navendu-pottekkat thoughts on this?

**Comment by navendu-pottekkat** [comment]
@dashohoxha Thank you for opening the issue. This can be added to the doc.

// @Neilblaze

**Comment by Amishakumari544** [comment]
can I work on this? If suitable?

**Comment by ro4i7** [comment]
@dashohoxha @Neilblaze @navendu-pottekkat @nfrankel please check PR #9069

**Comment by kayx23** [comment]
Please see my comment here https://github.com/apache/apisix/pull/9069#issuecomment-1717131222

**Comment by kayx23** [comment]
> The dashboard section of the Getting Started does not explain how to login on the dashboard:
> https://apisix.apache.org/docs/apisix/getting-started/#using-the-apisix-dashboard

There's no longer a dashboard section and dashboard isn't started with the quickstart script. Closing this issue now as it's outdated.
