### ISSUE TITLE
how to change the priority between global plugins and Router‘s plugins??

### ISSUE THREAD

**Issue by ww530220264** [apache/apisix#8961]
### Description

global plugin A, the priority is 1000

plugin B, the priority is 3000 and binding with Router A

i want to execute plugin B before A? Can you help me~

### Environment

- APISIX version (run `apisix version`): 2.15
- Operating system (run `uname -a`): linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
No. It's not feasible. Plugins on global rules before ones on route.

**Comment by ww530220264** [comment]
> No. It's not feasible. Plugins on global rules before ones on route.

Thanks for letting me know.
