### ISSUE TITLE
pull images faill

### ISSUE THREAD

**Issue by xlgo** [apache/apisix#8968]
### Description

Pulling from apache/apisix
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'

### Environment

[root@master ~]# docker pull apache/apisix
Using default tag: latest
latest: Pulling from apache/apisix
mediaType in manifest should be 'application/vnd.docker.distribution.manifest.v2+json' not 'application/vnd.oci.image.manifest.v1+json'
[root@master ~]# docker version
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
[root@master ~]# uname -a
Linux master 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by An-DJ** [comment]
It is a bug of Docker.

Ref: https://github.com/moby/moby/issues/39727

Maybe you can upgrade ur docker and have a try again.

**Comment by xlgo** [comment]
thanks
