### ISSUE TITLE
docs: Grammatical Error in the Docs

### ISSUE THREAD

**Issue by Ajay-singh1** [apache/apisix#8970]
### Current State

There is a Grammatical Error in the Docs docs/en/latest/external-plugin.md.
The spelling is intested in How it is implemented section.

### Desired State

The grammatical error must be fixed ASAP and the spelling should be corrected.

**Comment by shreemaan-abhishek** [comment]
@Ajay-singh1, you can straightaway raise a PR with a fix. It is okay not to open issues for document fixes. Thanks.

**Comment by Ajay-singh1** [comment]
Maybe for first time contributors.

**Comment by Ajay-singh1** [comment]
Hey @shreemaan-abhishek I think you had a fix for this issue but your PR is not merged yet!
