### ISSUE TITLE
docs: the docs about grpc-transcode

### ISSUE THREAD

**Issue by Brucepower0223** [apache/apisix#8971]
### Current State

when i use proto file includes import Google Struct.

first, i run the cmd "protoc --include_imports --descriptor_set_out=proto.pb proto/helloworld.proto"
and then use the python utils to upload the file.

error occurs:

![image](https://user-images.githubusercontent.com/12574550/222069862-ca14f4d8-1b15-474d-b0f3-ea7cfe931eed.png)

otherwise:
the code:
resp = requests.put("http://127.0.0.1:9180/apisix/admin/protos/" + id, json=reqParam, headers={
    "X-API-KEY": api_key,
})
    
is that true?? the proto admin api seems like. apisix/admin/proto/

    

### Desired State

the python utils can upload import proto

**Comment by Brucepower0223** [comment]
the python utils code is in 
<img width="972" alt="image" src="https://user-images.githubusercontent.com/12574550/222070435-b94daa43-1d76-4aad-b8ad-4bac7def9778.png">

**Comment by Brucepower0223** [comment]
the python utils code is this:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/12574550/222074905-4a70b52d-042e-405e-bc8b-df02657459ae.png">

**Comment by kayx23** [comment]
Hi @Brucepower0223, there had been an update to this doc. Please see https://github.com/apache/apisix/pull/9414

**Comment by navendu-pottekkat** [comment]
Closing this issue as the fix has already been updated in the docs.
