### ISSUE TITLE
Request conversion help

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#8974]
### Description

Does apisix support converting http requests from clients into socket requests, proxy to upstream, and finally convert socket requests returned from upstream into http requests and return them to clients?

client ---'http'---->apisix-------'socket'-------->upstream
client <----'http'----apisix<-------'socket'-------upstream

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
A little confused about ur description.

Could u give the detailed of ur use case, about what is the "converting http requests to socket requests"?
