### ISSUE TITLE
help request: CORS:  When allow_credential is set to true, why can't other attributes be set to * ?

### ISSUE THREAD

**Issue by chenjinfeng0505** [apache/apisix#8977]
### Description

When allow_credential is set to true, why can't other attributes be set to * ? 

please let me know, Thanks.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by An-DJ** [comment]
More detailed can be found there:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#credentialed_requests_and_wildcards

Iit is also discussed in stackoverflow:

https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141

**Comment by Qiuqiu0505** [comment]
Thanks @An-DJ
