### ISSUE TITLE
help request: APISIX Whether HTTP2 protocol is supported？

### ISSUE THREAD

**Issue by chen940227746** [apache/apisix#8989]
### Description

APISIX Whether HTTP2 protocol is supported？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Yes. https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L103
