### ISSUE TITLE
help request: plugins proxy-cache cannot handle post method $request_body ?

### ISSUE THREAD

**Issue by YangChaorix** [apache/apisix#8990]
### Description

The configuration is as follows
<img width="466" alt="image" src="https://user-images.githubusercontent.com/24434787/222369360-5c8a9086-0f11-4001-8556-8b6a1b8dc9fa.png">

<img width="756" alt="image" src="https://user-images.githubusercontent.com/24434787/222369640-0f6909d8-e51f-45c2-b2e8-d5f9b84cb6b3.png">

 cat logs  ctx.var["request_body"] value is "" 

What should I change to make it work? Is this type of configuration supported ？

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
https://apisix.apache.org/docs/apisix/apisix-variable/ 
The `$request_body` is not a valid variable. Currently, we don't expose this variable.

**Comment by mscb402** [comment]
Are you sending the request body? Could you let me know how you can access this route? Please share your `curl` cmd

**Comment by YangChaorix** [comment]
> Are you sending the request body? Could you let me know how you can access this route? Please share your `curl` cmd

This is the curl request。

curl --location --request POST 'http://127.0.0.1:9080/worksheet/getFilterRows' \
--header 'Content-Type: application/json' \
--data-raw '{
  "appKey": "02c71d5f45d3556e",
  "sign": "ZjgyNjA1NDc0OWRkYmRlZGY0NmFmYzc1NWMzNjEzZGEzNmQ3ZDI0ZThiMzZkMmNkYmNjOGY5YTRkMGRmZjZhZA==",
  "worksheetId": "6189f276e2355ced8fe8ed74",
  "pageSize": 10,
  "pageIndex": 1
}'

**Comment by mscb402** [comment]
I produce it on my local environment. Look like proxy-cache can't use the $request_body as the cache key.

**Comment by JustTony97** [comment]
Could you tell me, there is still no support for the **request_body** parameter for the **proxy_cache** plugin?

**Comment by YangChaorix** [comment]
i had solved it

**Comment by JustTony97** [comment]
Could you provide an example of setting up a proxy_cache plugin that would cache not only the uri but also the body in a POST type request? Thank you in advance

**Comment by JustTony97** [comment]
> i had solved it

Could you give an example of setting up a proxy-cache plugin that would cache POST requests not only for uri but also for body? thank you in advance

**Comment by JustTony97** [comment]
@YangChaorix, Can you tell me how to use the $request_body parameter so that the request body is cached in POST requests?

**Comment by YangChaorix** [comment]
> @YangChaorix, Can you tell me how to use the $request_body parameter so that the request body is cached in POST requests?

I tried and failed that use the $request_body, so I gave  up  @JustTony97

**Comment by kjgarza** [comment]
To support it _M.access would need something like:

```
local request_body = core.request.get_body()
 local cache_key_parts = {ctx.var.request_uri, request_body}
local value = util.generate_complex_value(cache_key_parts, ctx)
```

Any chance this gets fixed?
