### ISSUE TITLE
bug: traffic-split plugin can't proxy virtual upstream that schema is https

### ISSUE THREAD

**Issue by TenYearsIn** [apache/apisix#8996]
### Current Behavior

i have two upstream using https protocol, when i configure traffice-splite plugin on one route proxying that two upstream. i find i can not get correct response,  it tells me that require "Bad Request This combination of host and port requires TLS"

### Expected Behavior

i can use this route with traffice-split plugin proxy https upstream

### Error Logs

apisix's response is that 
Bad Request
This combination of host and port requires TLS

### Steps to Reproduce

1. Run Apisix On Centos7
2. start two applications that uses tls 
3. create a route `curl "http://127.0.0.1:9080/apisix/admin/routes/1234567890" -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{"uri":"/health","plugins":{"traffic-split":{"rules":[{"name":"upstream_A","type":"roundrobin","nodes":{"ip:port":10},"timeout":{"connect":15,"send":15,"read":15}}]}},"upstream": {"type": "roundrobin","nodes": {"ip:port": 2}}}'`
4. invoke api `curl -X GET http://127.0.0.1:9080/health` 

### Environment

-  Apisix Version(run `apisix version`): any version
- Operating system (run `uname -a`): Linux 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):3.4.0

**Comment by tokers** [comment]
What's your APISIX version? I cannot grep the key error message.

**Comment by TenYearsIn** [comment]
Apisix. version is 2.9 . But I think my issuse description `traffic-split plugin can't proxy virtual upstream that schema is https` is ambiguous.  Actually,  When I want to create a route with traffic-split pluggin proxying two back-end applications that protocol is https .  I found request has arrived to this two backend applications but the request schema is http. So this issue can description `feat: traffic-split plugin can not support upstream that protocl is https`

**Comment by tokers** [comment]
`2.9` is too old, and the team does not maintain it. Could you try the latest version to see if this issue exists?

**Comment by TenYearsIn** [comment]
yes, The version `3.0` also has the same issue

**Comment by oyiadin** [comment]
traffic-split doesn't support specifying `scheme` of upstream right now

https://github.com/apache/apisix/blob/e4e7c7327a87e1ff8f190e0608c4a0df2dfb2214/apisix/plugins/traffic-split.lua#L167-L176

I need this feature too ;-)

**Comment by TenYearsIn** [comment]
I have completed this feature, Could you assign it to me @tokers @spacewander
