### ISSUE TITLE
help request: rewrite host

### ISSUE THREAD

**Issue by overstarry** [apache/apisix#9004]
### Description

I have a route with a host of *.apps.xx, requesting a.apps.xx, and I want to access a different folder depending on the requested path

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Do you mean you want to change `Host` for a different route? The proxy-rewrite plugin is what you need. https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by overstarry** [comment]
I want to access different paths according to different hosts
example: a.apps.m.com -> /a/prod
b.apps.m.com -> /b/prod

**Comment by overstarry** [comment]
@mscb402

**Comment by mscb402** [comment]
I can't understand what you mean.
Do you mean you create a route with host `*.apps.m.com`. And if someone accesses with `a.apps.m.com`, then you want to get upstream content from the path `http://upstream/a/prod`?
Please give us more detail, Like what input or output you desire. And provide you route configuration you want to change currently.

**Comment by overstarry** [comment]
yes host: *.app.m.com
a.app.m.com -> http://upstream/a/prod
b.app.m.com -> http://upstream/b/prod

**Comment by mscb402** [comment]
I think the best way is to create a multi-route to do this.
First route with the host `a.app.m.com` and set a plugin `proxy-rewrite` with configuration `{'uri':'/a/prod'}`.
Second route with the host `b.app.m.com` and set a plugin `proxy-rewrite` with configuration `{'uri':'/b/prod'}`.

Like this (This is just a example, you need change it)
```json
{
    "methods": ["GET"],
    "uri": "/*",
    "host": "a.app.m.com"
    "plugins": {
        "proxy-rewrite": {
            "uri": "/a/prod",
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}
```

```json
{
    "methods": ["GET"],
    "uri": "/*",
    "host": "b.app.m.com"
    "plugins": {
        "proxy-rewrite": {
            "uri": "/b/prod",
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}
```

**Comment by overstarry** [comment]
There are many such hosts，It is better to have a universal solution

**Comment by mscb402** [comment]
Or you can use `_meta` in plugin https://apisix.apache.org/docs/apisix/terminology/plugin/#plugin-common-configuration
Like 
```
{
    "methods": ["GET"],
    "uri": "/*",
    "host": "a.app.m.com"
    "plugins": {
        "proxy-rewrite": {
            "_meta":{
                    "filter":["host", "==", "a.app.m.com"]
            }
            "uri": "/a/prod",
        },
        "proxy-rewrite": {
            "_meta":{
                    "filter":["host", "==", "b.app.m.com"]
            }
            "uri": "/b/prod",
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:80": 1
        }
    }
}
```

**Comment by overstarry** [comment]
ok,thanks

**Comment by mscb402** [comment]
If you want some program way to do. You can try using a serverless plugin using Lua code. But this may be difficult. https://apisix.apache.org/docs/apisix/plugins/serverless/

**Comment by overstarry** [comment]
I was solved with serverless plugin
