### ISSUE TITLE
feat: filter access logs sent to http/sls etc

### ISSUE THREAD

**Issue by zlzforever** [apache/apisix#9005]
### Description

When i enable http-logger, every access logs are sent to log server, sometimes, i want to exclude some logs for examples:
1. Method: OPTIONS
2. Custom Header:  route-id: '455333323'

**Comment by soulbird** [comment]
APISIX is only a producer of logs and should maintain the integrity of logs. It is more appropriate for log filtering to be handled by the log collection platform.
