### ISSUE TITLE
bug: response-rewrite in v2.15.3 does not remove header when setting to ""

### ISSUE THREAD

**Issue by freemindcore** [apache/apisix#9009]
### Current Behavior
There is a header "server" in one of my services, I want to remove it.

`"server": "istio-envoy"`

I am trying to remove header (server) with response-rewrite plugin but failed.
This is my config:

```
    "response-rewrite": {
      "headers": {
        "server": "",
        "x-server-new": "worked"
      }
    }
```
    
The header x-server-new was added successfully, which means that my config took effect.
But the "server" header should be removed. 
Unfortunately it failed to do so, I think this is a bug.

### Expected Behavior

"server" header should be removed.

### Steps to Reproduce

1. Run APISix
2. Set a route, add the response-rewrite plugin with the above config to it
3. Test 

### Environment

- APISIX version (run `apisix version`): 
_/usr/local/openresty/luajit/bin/luajit ./apisix/cli/apisix.lua version
2.15.1_
- Operating system (run `uname -a`):
_Linux apisix-5d5dfc55d8-558hc XXXX.amzn2.x86_64 SMP Fri Dec 9 12:54:21 UTC 2022 x86_64 GNU/Linux_

- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
_nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1n  15 Mar 2022 (running with OpenSSL 1.1.1s  1 Nov 2022)_

- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
> The header x-server-new will be added successfully though.

This is an expected behavior, isn't it?

**Comment by freemindcore** [comment]
Yes, it is true for x-server-new header which means my config took effect. But server header should be removed, but failed.

> 



> > The header x-server-new will be added successfully though.
> 
> This is an expected behavior, isn't it?

**Comment by tokers** [comment]
@freemindcore So what is the server header you seen from the response?

**Comment by freemindcore** [comment]
@tokers The same as it was -  "server":  "istio-envoy"

**Comment by shreemaan-abhishek** [comment]
@freemindcore do you see the same issue in the latest version?

**Comment by freemindcore** [comment]
> @freemindcore do you see the same issue in the latest version?
Was it fixed?
I am still on 2.15.1, have not tried 2.15.3 yet.

**Comment by freemindcore** [comment]
@shreemaan-abhishek 
Thanks for the followup! 
I did an upgrade to v2.15.3, the bug still exists.

Can someone fix this?

**Comment by shreemaan-abhishek** [comment]
I don't think the team maintains v2, I would suggest upgrading to v3.

**Comment by freemindcore** [comment]
V2.15 is a LTS maintenance version. Why would the team drop the support for v2.15?

**Comment by shreemaan-abhishek** [comment]
> V2.15 is a LTS maintenance version. Why would the team drop the support for v2.15?

My bad.

**Comment by shreemaan-abhishek** [comment]
Btw, I tried to reproduce this bug but I could see that header was removed when setting to "".

Without response rewrite:

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/61597896/236908113-b1a9e5fc-fff4-4f23-ab17-49a00dafb8bc.png">

With response rewrite:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/61597896/236908373-36060343-83d9-4102-8849-897f577fb871.png">

**Comment by freemindcore** [comment]
Thanks for digging into this issue!

Weird. I put the response-rewrite plugin in service config, so I tried the same config in route this time. 

As a conclusion, I tried the  response-rewrite plugin in both route and service config, still failed in our system:
![image](https://user-images.githubusercontent.com/5857025/236978493-87ac6400-e9ae-459e-bca7-8ca424cc3741.png)
![image](https://user-images.githubusercontent.com/5857025/236978563-d1089c48-a212-4dc7-b353-71bc0ac2664f.png)


Without response rewrite (I disabled the plugin):
![image](https://user-images.githubusercontent.com/5857025/236979352-25acb155-a806-4053-b23e-8eeac7c6b17d.png)
![image](https://user-images.githubusercontent.com/5857025/236979519-5ab02297-4d09-4cfe-ad9f-16a8eb7d51dd.png)


Here is my current setup:
<img width="1761" alt="image" src="https://user-images.githubusercontent.com/5857025/236979012-02fe2869-2cc6-4a80-a3a4-02c0bb99257a.png">

**Comment by shreemaan-abhishek** [comment]
Please share your route configuration, let me give it a try on my system.

**Comment by freemindcore** [comment]
Here you are:
```{
  "uri": "/*",
  "name": "STAG-api\t",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "hosts": [
    "test1.xxx.com",
    "test2.xxx.com"
  ],
  "vars": [
    [
      "http_release",
      "!",
      "==",
      "new_release"
    ]
  ],
  "plugins": {
    "response-rewrite": {
      "disable": false,
      "headers": {
        "server": "",
        "x-envoy-decorator-operation": "notworking",
        "x-envoy-upstream-service-time": "notworking",
        "x-server-new": "worked"
      }
    }
  },
  "service_id": "418160269672317467",
  "upstream_id": "418158059005674011",
  "labels": {
    "APP": "API",
    "ENV": "STAG"
  },
  "status": 1
}
```

**Comment by shreemaan-abhishek** [comment]
Do you notice any error logs?

**Comment by freemindcore** [comment]
> 

Nope, I could not find any.

**Comment by shreemaan-abhishek** [comment]
I don't see anything unique in your route configuration. Here's mine, give it a try and lemme know if it works.

```bash
curl -i http://127.0.0.1:9080/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "uri": "/hello",
    "plugins": {
        "limit-count": {
            "count": 2222,
            "time_window": 60,
            "rejected_code": 503,
            "key_type": "var_combination",
            "key": "$consumer_name $remote_addr"
        },
    "response-rewrite": {
      "headers": {
        "server": "",
        "x-server-new": "worked"
      }
    }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "127.0.0.1:1980": 1
        }
    }
}'
```

**Comment by freemindcore** [comment]
Issue was caused by APISIX integration with ISTIO
