### ISSUE TITLE
feat: forward-auth plugin send authorization service's response body to upstream

### ISSUE THREAD

**Issue by flca267** [apache/apisix#9023]
### Description

As a user, I want to use forward-auth plugin to send authorization service's response body to upstream. But the plugin only support response header now.

**Comment by monkeyDluffy6017** [comment]
What authentication server will put the authentication information into the body？

**Comment by flca267** [comment]
Authentication server may not only return the auth result but some data which could be used for upstream(e.g. user info when auth success). If we send it, upstream do not need to request the authentication server again.

**Comment by monkeyDluffy6017** [comment]
@spacewander What‘s’ your opinion?

**Comment by flca267** [comment]
The plugin may need a config called upstream_bodies to let user select which part of response body from authentication server is needed. It may be a complicated task as the plugin need to merge the additional data into the original request body.

**Comment by spacewander** [comment]
What about configuring the authentication server to pass the info via response body?
As you mentioned, selecting and merging the additional data may be a complicated task.

**Comment by flca267** [comment]
I rethink about it. Support this feature but make current logic more complicated isn't what i want. So i will close this issue. THANKS for your opinions! @spacewander @monkeyDluffy6017
