### ISSUE TITLE
bug: util.file_read() function did not trim the LF in the end of the file.

### ISSUE THREAD

**Issue by panhow** [apache/apisix#9029]
### Current Behavior

i was testing k8s discovery .
I met this promblem when i use `discovery.kubernetes.client.token_file` instead `discovery.kubernetes.client.token` .

`util.read_file()` return the string with "LF"(the last character of the file) . as a result, k8s client will get a response with `400 bad request: missing required Host header`, because when http client build a request, "LF" in a http header lines is a line break. As a consequence, invalid http request sent to api server.

### Expected Behavior

`util.read_file` return a string with no "LF" in the end.

here is the minimum reproducable code written by lua:
```lua
local f = io.open("/tmp/t")
local s = f:read("*all")
print(s:byte(1,-1))
```

bash script
```bash
cat <<EOF >> test.lua
local f = io.open("/tmp/t")
local s = f:read("*all")
print(s:byte(1,-1))
EOF

echo "a" >> /tmp/t
resty test.lua
```
this example will get a result:
```
9710
```

### Error Logs

Error Log:
```
2023/03/07 20:00:47 [error] 20047#20047: *480073452 [lua] informer_factory.lua:295: list failed, kind: Endpoints, reason: Bad Request: missing required Host header, message : 400 Bad Request: missing required Host header, context: ngx.timer
```

tcpdump to capture the http request:
![image](https://user-images.githubusercontent.com/34205715/223419074-7c3642a2-a07f-427b-9eb2-faa4ec22ff02.png)

Set token as `abc`. 
Add logs to find what the token is, also print every byte in the token string.
![image](https://user-images.githubusercontent.com/34205715/223419504-372c23dd-c2bb-4de8-a404-179c6b839153.png)

### Steps to Reproduce

1.add k8s discovery to `config.yaml `
```yaml
discovery:
  kubernetes:
    service:
      schema: https
      host: "127.0.0.1"
      port: "6443"
    client:
      token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
```
2. reload apisix
error logs :
```
2023/03/07 20:00:47 [error] 20047#20047: *480073452 [lua] informer_factory.lua:295: list failed, kind: Endpoints, reason: Bad Request: missing required Host header, message : 400 Bad Request: missing required Host header, context: ngx.timer
```

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15

**Comment by panhow** [comment]
@tokers @spacewander  PTAL

**Comment by spacewander** [comment]
We can trim the whitespace before using it in the HTTP request?
As for `util.file_read`, it's a common function so we should let it do what we expect to do - read the whole file. We can add whitespace trimming in the k8s code.

**Comment by panhow** [comment]
trim when k8s code init works.

**Comment by panhow** [comment]
@spacewander is there any unit test for kubernetes discovery?
