### ISSUE TITLE
help request: When the global skywalking plugin is enabled, disabling skywalking configuration at the route level does not take effect

### ISSUE THREAD

**Issue by Hwting** [apache/apisix#9031]
### Description

1.When the global skywalking plugin is enabled, disabling skywalking configuration at the route level does not take effect
![image](https://user-images.githubusercontent.com/16237905/223444555-302beabd-8067-4a37-9f10-197f24dea567.png)
![image](https://user-images.githubusercontent.com/16237905/223444764-636c4325-c1d5-48b6-9352-fdf90ee9c94c.png)

### Environment
```
NAME  	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
apisix	apisix   	1       	2022-08-23 17:07:57.837975504 +0800 CST	deployed	apisix-0.11.0	2.15.0 
```
Purpose:
want to filter interface

**Comment by An-DJ** [comment]
You can try this?

```
{
  "plugins": {
    "skywalking": {
      "_meta": {
        "disable": true
      }
    }
  }
}
```

**Comment by Hwting** [comment]
> 你可以试试这个吗？
> 
> ```
> {
>   "plugins": {
>     "skywalking": {
>       "_meta": {
>         "disable": true
>       }
>     }
>   }
> }
> ```
also did not take effect
![image](https://user-images.githubusercontent.com/16237905/223604934-de29db92-6c06-4ec1-ad91-10ca69d4d822.png)

**Comment by An-DJ** [comment]
@Hwting Could you plz show your global level config and route level config more in detail?

**Comment by Hwting** [comment]
@An-DJ 
route：
/apisix/admin/routes/00000000000000003684
```
{"node":{"key":"\/apisix\/routes\/00000000000000003684","value":{"enable_websocket":true,"labels":{"pro":"xx","type":"whiteList"},"plugins":{"skywalking":{"_meta":{"disable":true}},"proxy-rewrite":{"regex_uri":["^\/xx\/(.*)","\/$1"]}},"update_time":1678241526,"uri":"\/xx\/xx\/xx\/websocket\/**","id":"00000000000000003687","status":1,"hosts":["api.xx.com"],"upstream_id":"50000000000000004","name":"xx-\/xx\/xx\/websocket\/**","create_time":1666354309}},"count":1,"action":"get"}

```
global:
/apisix/admin/global_rules 
```
"skywalking":{"disable":false}
```

**Comment by An-DJ** [comment]
I can't reproduce this issue in my local env based on APISIX 3.2. Maybe you can follow my steps to check:

1. Create a Route with skywalking open:
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
{
  "id": "ip",
  "uri": "/ip",
  "plugins": {
    "skywalking":{}
  },
  "upstream": {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org:80": 1
    }
  }
}'
```
2. Create a global config with skywalking open:
```
curl http://127.0.0.1:9180/apisix/admin/plugin_configs/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "plugins": {
      "skywalking":{}
    }
}'
```
3. Request the uri and there is a record in skywalking.
```
curl "http://localhost:9080/ip"
```
![image](https://user-images.githubusercontent.com/24536972/224228331-cbe85f03-f55b-4d96-a0ee-0dfe17c22fad.png)

4. Close the skywalking in route level, then request again and check, there are **no new records**.
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes/ip" -X PATCH -d '
{
  "plugins": {
    "skywalking": {
        "_meta": {
          "disable": true
        }
      }
  }
}'
```
5. Reopen in route level and request again, there is a new record:
```
curl -i "http://127.0.0.1:9180/apisix/admin/routes/ip" -X PATCH -d '
{
  "plugins": {
    "skywalking": {
        "_meta": {
          "disable": false
        }
      }
  }
}'
```
![image](https://user-images.githubusercontent.com/24536972/224228542-645c7a04-a67d-44cd-bcdb-44b97a31421d.png)

**Comment by Hwting** [comment]
I have no problem with APISIX/3.2.0, so this should be a 2.15.0 bug

> I can't reproduce this issue in my local env based on APISIX 3.2. Maybe you can follow my steps to check:
> 
> 1. Create a Route with skywalking open:
> 
> ```
> curl -i "http://127.0.0.1:9180/apisix/admin/routes" -X PUT -d '
> {
>   "id": "ip",
>   "uri": "/ip",
>   "plugins": {
>     "skywalking":{}
>   },
>   "upstream": {
>     "type": "roundrobin",
>     "nodes": {
>       "httpbin.org:80": 1
>     }
>   }
> }'
> ```
> 
> 2. Create a global config with skywalking open:
> 
> ```
> curl http://127.0.0.1:9180/apisix/admin/plugin_configs/1 \
> -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
> {
>     "plugins": {
>       "skywalking":{}
>     }
> }'
> ```
> 
> 3. Request the uri and there is a record in skywalking.
> 
> ```
> curl "http://localhost:9080/ip"
> ```
> 
> ![image](https://user-images.githubusercontent.com/24536972/224228331-cbe85f03-f55b-4d96-a0ee-0dfe17c22fad.png)
> 
> 4. Close the skywalking in route level, then request again and check, there are **no new records**.
> 
> ```
> curl -i "http://127.0.0.1:9180/apisix/admin/routes/ip" -X PATCH -d '
> {
>   "plugins": {
>     "skywalking": {
>         "_meta": {
>           "disable": true
>         }
>       }
>   }
> }'
> ```
> 
> 5. Reopen in route level and request again, there is a new record:
> 
> ```
> curl -i "http://127.0.0.1:9180/apisix/admin/routes/ip" -X PATCH -d '
> {
>   "plugins": {
>     "skywalking": {
>         "_meta": {
>           "disable": false
>         }
>       }
>   }
> }'
> ```
> 
> ![image](https://user-images.githubusercontent.com/24536972/224228542-645c7a04-a67d-44cd-bcdb-44b97a31421d.png)

@An-DJ  I have no problem with APISIX/3.2.0, so this should be a 2.15.0 bug

**Comment by Hwting** [comment]
#8603
