### ISSUE TITLE
bug: ApisSix 3.2 Consul 1.15 Integration problem

### ISSUE THREAD

**Issue by unreal-asr** [apache/apisix#9032]
### Current Behavior

Apache APISIX  3.2 (installed with helm charts on k8s) report an error during the services discovery configured by consul. 
All the configuration are the same as in this [guide](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/) the only difference is the Consul version. Only with Consul >= 1.15.x the problem arises

Consul version tested:

- consul:1.8   ok (version used in the guide)
- consul:1.10  ok
- consul:1.11  ok
- consul:1.12  ok
- consul:1.13  ok
- consul:1.14  ok
- **consul:1.15  ko**

On apisix pod the reported error is:

2023/03/07 10:15:38 [error] 49#49: *27601 [lua] init.lua:225: connect consul: http://10.0.245.110:30850/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/07 10:15:38 [warn] 49#49: *27601 [lua] init.lua:231: retry connecting consul after 1 seconds, context: ngx.timer

Consequently it is not possible to use the upstream of type consul (from the guide)

```
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "uri": "/consul/web/*",
    "upstream": {
        "service_name": "service_a",
        "type": "roundrobin",
        "discovery_type": "consul"
    }
}
```

```
# the first request fail
curl -s http://127.0.0.1:9080/consul/web/
```

```
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
</html>
```

### Expected Behavior

That the consul discovery works well and then (as in the guide)

the first request
curl -s http://127.0.0.1:9080/consul/web/
Output
hello web2%

the second request
curl -s http://127.0.0.1:9080/consul/web/
Output
hello web1%

### Error Logs

2023/03/07 10:15:38 [error] 49#49: *27601 [lua] init.lua:225: connect consul: http://10.0.245.110:30850/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/07 10:15:38 [warn] 49#49: *27601 [lua] init.lua:231: retry connecting consul after 1 seconds, context: ngx.timer

### Steps to Reproduce

The same step in this [guide](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/) with docker or installation with helm on k8s (same behaviour)

### Environment

APISIX 3.2
Consul 1.15.x

**Comment by Fabriceli** [comment]
Could you provide more information about re-production this scenario, I will check it later

**Comment by Fabriceli** [comment]
Please provide more info about `apisix_conf/config.yaml`, what is your config of the Consul discovery?

**Comment by Fabriceli** [comment]
from the error msg:
```sh
2023/03/07 10:15:38 [error] 49#49: *27601 [lua] init.lua:225: connect consul: http://10.0.245.110:30850/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/07 10:15:38 [warn] 49#49: *27601 [lua] init.lua:231: retry connecting consul after 1 seconds, context: ngx.timer
```
Maybe make a mistake config about the IP:PORT of the Consul server

**Comment by unreal-altran** [comment]
Dear Fabriceli,

I followed exactly the same steps of this [guide ](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/) but with consul v1.15.x. I got exactly your error in the ApiSix logs and obviously the ApiSix services are not forwarding properly.
Considering that I tried all previous versions of consul from 1.8 (the guide version) to 1.15.x and only the latter one doesn't work I think it's either a bug in Consul or a change in the responses of the new Consul 1.15.x API.
If the problem falls in the latter case, perhaps the response management by ApiSix Discovery plugin will be need to reviewed...

**Comment by Fabriceli** [comment]
Checked, neither a bug nor a breaking change in the response of the Consul.
When you restart or update Consul server, the connection between APISIX and Consul will be reset in a few seconds, so it will print fellow error msg:
```sh
[error] 49#49: *78795 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET /consul/web/ HTTP/1.1", upstream: "http://172.20.10.2:9082/consul/web/", host: "127.0.0.1:9080"
```

Just wait a few moment, it will watch successfully.

**Comment by Fabriceli** [comment]
Checked, neither a bug nor a breaking change in the response of the Consul.
When you restart or update Consul server, the connection between APISIX and Consul will be reset in a few seconds, so it will print fellow error msg:
```sh
[error] 49#49: *78795 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: _, request: "GET /consul/web/ HTTP/1.1", upstream: "http://172.20.10.2:9082/consul/web/", host: "127.0.0.1:9080"
```

Just wait a few moment, it will watch successfully.

**Comment by unreal-altran** [comment]
Dear Fabriceli,

I've seen this behavior too but it happens when you leave the same instance of ApiSix and only change the version of Consul for testing, some version of consul works and adds the routes in ApiSix, then you switch to the non-working one and the route remains in ApiSix giving the impression that it works after reconnectins. 
I kindly invite you to try from scratch (the same steps of this [guide ](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/) ) with a clean version of ApiSix and only Consul v1.15.1.

- Register some service to Consul 1.15.1 via Consul HTTP API.
- Check whether the test service is registered successfully on Consul 1.15.1
- Add a Route to ApiSix with discovery type Consul
- Test and Verify the Result

Even waiting for retries, ApiSix always logs something like this:

```
2023/03/15 18:54:28 [error] 49#49: *374 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/15 18:54:28 [warn] 49#49: *374 [lua] init.lua:231: retry connecting consul **after 1 seconds**, context: ngx.timer
2023/03/15 18:55:29 [error] 49#49: *8353 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/15 18:55:29 [warn] 49#49: *8353 [lua] init.lua:231: retry connecting consul **after 4 seconds**, context: ngx.timer
...
...
2023/03/15 18:57:49 [warn] 49#49: *25776 [lua] init.lua:231: retry connecting consul **after 64 seconds**, context: ngx.timer
2023/03/15 18:59:53 [error] 49#49: *41328 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
...
...
2023/03/15 19:05:09 [error] 49#49: *81259 [lua] init.lua:225: connect consul: http://http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
2023/03/15 19:05:09 [warn] 49#49: *81259 [lua] init.lua:231: retry connecting consul **after 1024 seconds**, context: ngx.timer
```
The apsisx-gateway always responds:

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty</center>
<p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
```

**Comment by Fabriceli** [comment]
> Dear Fabriceli,
> 
> I've seen this behavior too but it happens when you leave the same instance of ApiSix and only change the version of Consul for testing, some version of consul works and adds the routes in ApiSix, then you switch to the non-working one and the route remains in ApiSix giving the impression that it works after reconnectins. I kindly invite you to try from scratch (the same steps of this [guide ](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/) ) with a clean version of ApiSix and only Consul v1.15.1.
> 
> * Register some service to Consul 1.15.1 via Consul HTTP API.
> * Check whether the test service is registered successfully on Consul 1.15.1
> * Add a Route to ApiSix with discovery type Consul
> * Test and Verify the Result
> 
> Even waiting for retries, ApiSix always logs something like this:
> 
> ```
> 2023/03/15 18:54:28 [error] 49#49: *374 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
> 2023/03/15 18:54:28 [warn] 49#49: *374 [lua] init.lua:231: retry connecting consul **after 1 seconds**, context: ngx.timer
> 2023/03/15 18:55:29 [error] 49#49: *8353 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
> 2023/03/15 18:55:29 [warn] 49#49: *8353 [lua] init.lua:231: retry connecting consul **after 4 seconds**, context: ngx.timer
> ...
> ...
> 2023/03/15 18:57:49 [warn] 49#49: *25776 [lua] init.lua:231: retry connecting consul **after 64 seconds**, context: ngx.timer
> 2023/03/15 18:59:53 [error] 49#49: *41328 [lua] init.lua:225: connect consul: http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
> ...
> ...
> 2023/03/15 19:05:09 [error] 49#49: *81259 [lua] init.lua:225: connect consul: http://http://<consul_host>:30083/v1 by sub url: /catalog/services, got watch result: null, with error: closed, context: ngx.timer
> 2023/03/15 19:05:09 [warn] 49#49: *81259 [lua] init.lua:231: retry connecting consul **after 1024 seconds**, context: ngx.timer
> ```
> 
> The apsisx-gateway always responds:
> 
> ```
> <html>
> <head><title>404 Not Found</title></head>
> <body>
> <center><h1>404 Not Found</h1></center>
> <hr><center>openresty</center>
> <p><em>Powered by <a href="https://apisix.apache.org/">APISIX</a>.</em></p></body>
> ```
> 
> P.S. I realized that the[ official image](https://hub.docker.com/_/consul/tags?page=1&name=1.15) of Consul 1.15.1 has been updated only 2 days ago with the same version number 1.15.1 & :latest (the digest has changed). I haven't tried this new specific version yet. Maybe they solved the problem on the Consul side. @Fabriceli was your test done after the publication of the latest consul version dating to 2 days ago?

I can not reproduce, though i follow this [guide](https://apisix.apache.org/blog/2023/01/18/consul-with-apisix/). It work fine with the consul 1.15.1 version and also 1.15 version. Can you provide more info about the situation, eg. openresty version, lua version etc.

**Comment by shreemaan-abhishek** [comment]
@unreal-altran, any updates? Does it work now?
