### ISSUE TITLE
bug: The client_secret field of the keycloak plug-in cannot be encrypted

### ISSUE THREAD

**Issue by yongling0625** [apache/apisix#9035]
### Current Behavior

2023/03/08 07:00:29 [warn] 54#54: *95 [lua] plugin.lua:895: decrypt_conf(): failed to decrypt the conf of plugin [authz-keycloak] key [client_secret], err: decrypt ssl key failed, context: ngx.timer

client_secret is not properly encrypted

### Expected Behavior

client_secret is properly encrypted

### Error Logs

2023/03/08 07:00:29 [warn] 54#54: *95 [lua] plugin.lua:895: decrypt_conf(): failed to decrypt the conf of plugin [authz-keycloak] key [client_secret], err: decrypt ssl key failed, context: ngx.timer

### Steps to Reproduce

1.  git  clone  https://github.com/apache/apisix-docker.git
2. cd  apisix-docker/example/apisix_conf
3. vi conf.yaml  
  ```
 apisix:  
     data_encryption:
          enable: true
          keyring:
             - edd1c9f0985e76a2
```
 5. add router and enable authz-keycloak 

### Environment

- APISIX version (run `apisix version`):  3.1.0-centos  or 3.2.0-centos
- Operating system (run `uname -a`):  centos 7 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by monkeyDluffy6017** [comment]
Is the `client_secret` in your etcd unencrypted?

**Comment by yongling0625** [comment]
@monkeyDluffy6017   yes, client_secret is stored in plain text in etcd.

**Comment by monkeyDluffy6017** [comment]
Use the `curl` command instead of dashboard, dashboard won't encrypt the data

**Comment by yongling0625** [comment]
The data is encrypted. Thank you.
