### ISSUE TITLE
help request:  how to kafka-logger get header variables send to kafka

### ISSUE THREAD

**Issue by wolgod** [apache/apisix#9036]
### Description

If I want to modify kafka-logger so that I can get some custom values in the header and send them to kafka, is there any implementation idea?

### Environment

- APISIX version (run `apisix version`):2.15.2
- Operating system (run `uname -a`):centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Do you mean using your custom log format which contains some header value? You can try config your own log format in metadata https://apisix.apache.org/docs/apisix/plugins/kafka-logger/#metadata
