### ISSUE TITLE
docs: usage of profane terms in documentation and apisix codebase.

### ISSUE THREAD

**Issue by shreemaan-abhishek** [apache/apisix#9042]
### Current State

Blacklist and whitelist are profane terms. And the usage of appropriate terms like allowlist and denylist is suggested.

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/61597896/223948692-2dad650d-24b0-4780-8805-738f954b384f.png">

### Desired State

The usage of words like blacklist and whitelist should be replaced with allowlist and denylist respectively.

**Comment by Neilblaze** [comment]
@shreemaan-abhishek I'm taking this up! Assign me please. :)
