### ISSUE TITLE
feat: todo in apisix/cli/schema.lua

### ISSUE THREAD

**Issue by ronething** [apache/apisix#9052]
### Description

i found this TODO, do we need to change it now? @spacewander 

https://github.com/apache/apisix/blob/2d94db124856e9c70592e52dcfc45baa77f9c272/apisix/cli/schema.lua#L67-L68

**Comment by spacewander** [comment]
No. The use_grpc is still experimental. We still need to wait for more time.

**Comment by ronething** [comment]
ok, i will close this issue later.
