### ISSUE TITLE
bug: If `allow_admin` contains 127.0.0.0/24, requests from other ips without adminKey are allowed by default

### ISSUE THREAD

**Issue by An-DJ** [apache/apisix#9055]
### Current Behavior

If `allow_admin` contains 127.0.0.0/24, requests from other ips without the admin key are allowed by default.

https://github.com/apache/apisix/blob/27535e9831b303ef721046bd51e471abb0be9c13/apisix/cli/ops.lua#L190

### Expected Behavior

Only requests from 127.0.0.0/24 without adminKey are allowed. Otherwise, they should be banned if the admin key isn't configured in `config.yaml`.

### Steps to Reproduce

1. use the config below:
```
deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
      - 127.0.0.0/24
    admin_key:
      # empty
```
2. Requests from other ips without adminKey are allowed.

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): Ubuntu 18.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
It looks like it just avoids warnings when using the default configuration. But the judgment is faulty and should see if it is only "127.0.0.0/24".
