### ISSUE TITLE
docs: add a link to the new one in the old stand-alone doc

### ISSUE THREAD

**Issue by monkeyDluffy6017** [apache/apisix#9058]
### Current State

The doc for stand-alone mode is now:
https://apisix.apache.org/docs/apisix/deployment-modes/#standalone
Which is different from the path of the old one:
https://apisix.apache.org/docs/apisix/2.15/stand-alone/

Users may get confused about this:
https://github.com/apache/apisix/issues/9051

### Desired State

add a new link in the old stand-alone doc which point to the new one

**Comment by ro4i7** [comment]
@monkeyDluffy6017 please checkout #9067
