### ISSUE TITLE
feat: The forward-auth plugin discards any pre-existing `X-Forwarded` prefix headers within the request.

### ISSUE THREAD

**Issue by joyyir** [apache/apisix#9060]
### Description

My system utilizes AWS ALB as a front-end for APISIX, and as a result, AWS ALB response includes `X-Forwarded` prefix headers. You can find additional information about this in the documentation.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/x-forwarded-headers.html

Since the forward-auth plugin adds its own `X-Forwarded` prefix headers, any `X-Forwarded` prefix headers that are added by AWS ALB are disregarded. Consequently, the external authentication service is unable to determine the protocol originally used by the client.

I am requesting a feature that would allow for the preservation of specific request headers.
Thank you.

**Comment by yujinchoi-94** [comment]
Same here. I also want to use the original value of`X-Forwarded-Method` not a forward-auth plugin generated one.
