### ISSUE TITLE
feat: As a user, I want to allow external ips in `allow_admin` without adminKey in debug mode, so that users can request containered APISIX Admin API from the host for test

### ISSUE THREAD

**Issue by An-DJ** [apache/apisix#9071]
### Description

As a user, I want to allow external ips in `allow_admin` without adminKey in debug mode, so that users can request containered APISIX Admin API from the host for test.

To simplify the operating steps in the "Getting Started" document, we want to make empty adminKey.

However, the APISIX now does not allow the requests without adminKey to visit Admin API except `127.0.0.0/24`, 
https://github.com/apache/apisix/blob/master/apisix/cli/ops.lua#L191
so that users cannot visit containered APISIX Admin API from the host.

Such a strategy is made for safety, but we can support it in debug mode, so that users can try the APISIX easily with "Getting Started".

What I want to do is allow the external custom ips in `allow_admin` with empty `admin_key` in debug mode, like below:
```
deployment:
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
    # empty
```

**Comment by An-DJ** [comment]
CC @spacewander

**Comment by spacewander** [comment]
> Such a strategy is made for safety, but we can support it in debug mode, so that users can try the APISIX easily with "Getting Started".

It seems this feature is not for debugging, but to make it easy to get started. What about adding an env value to do it, like [bitnami/etcd](https://hub.docker.com/r/bitnami/etcd/)'s `ALLOW_NONE_AUTHENTICATION`?

**Comment by An-DJ** [comment]
> > Such a strategy is made for safety, but we can support it in debug mode, so that users can try the APISIX easily with "Getting Started".
> 
> It seems this feature is not for debugging, but to make it easy to get started. What about adding an env value to do it, like [bitnami/etcd](https://hub.docker.com/r/bitnami/etcd/)'s `ALLOW_NONE_AUTHENTICATION`?

Agree.
