### ISSUE TITLE
HTTP  methods trace and connect return "405 Not Allowed"

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9091]
### Description

apisix returns 405 Not Allowed when I use the http methods trace and connect. How do I solve it?

the route config is :
.....
    "priority": 1,
    "methods": [
        "TRACE",
        "POST",
        "GET",
        "CONNECT"
    ],
.......

the request is :
[root@localhost]# curl -X TRACE "http://10.4.16.105:9080/yangcong/1k.txt"
<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Environment

- APISIX version (run `apisix :2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version IS 2.13-alpine , if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
TRACE and CONNECT will be treated as invalid HTTP method, before the route matching.

**Comment by githubxubin** [comment]
> TRACE and CONNECT will be treated as invalid HTTP method, before the route matching.

What do you mean? How do I check whether these two types of requests are available

**Comment by githubxubin** [comment]
> TRACE and CONNECT

Do you need any additional configuration? I need to use both requests to match the route

**Comment by githubxubin** [comment]
> TRACE and CONNECT will be treated as invalid HTTP method, before the route matching.

Is TRACE and CONNECT supported for these two request methods? Version is apisix-:2.15-alpine

**Comment by tokers** [comment]
Indeed, these two methods are not supported by the Nginx core. Even if you configure them in the Route, they're useless.

**Comment by githubxubin** [comment]
> Indeed, these two methods are not supported by the Nginx core. Even if you configure them in the Route, they're useless.

Could you help me with that？ Sir s

**Comment by githubxubin** [comment]
> Indeed, these two methods are not supported by the Nginx core. Even if you configure them in the Route, they're useless.

Could you help me with that？ Sir  thanks

**Comment by spacewander** [comment]
Look like it's a bug in the schema definition:
https://github.com/apache/apisix/blob/3b76c45543861a0fb4a7924842d3a47c51ae83b2/apisix/schema_def.lua#L530-L536

Trace and connect are valid HTTP methods, but they are not supported by Nginx. Maybe we can remove them.
