### ISSUE TITLE
Apisix的官方安装包能否改成基于apisix-base构建呢？

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9092]
### Description

您好，看apisix的文档上，很多功能上都写着如下一句话“This feature requires APISIX to be run on APISIX-Base.”
请问，是否能将apisix的安装包（比如rpm包）默认就改成基于apisix-base构建的呢？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
That's it now

**Comment by ro4i7** [comment]
> ### Environment
> * APISIX version (run `apisix version`):
> * Operating system (run `uname -a`):
> * OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
> * etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
> * APISIX Dashboard version, if relevant:
> * Plugin runner version, for issues related to plugin runners:
> * LuaRocks version, for installation issues (run `luarocks --version`):

Yeah, you can change the APISIX installation package to be built on APISIX-Base by default. You can use all the features that require APISIX-Base without any additional configuration.

**Comment by zzqCh** [comment]
> > ### Environment
> > 
> > * APISIX version (run `apisix version`):
> > * Operating system (run `uname -a`):
> > * OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
> > * etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
> > * APISIX Dashboard version, if relevant:
> > * Plugin runner version, for issues related to plugin runners:
> > * LuaRocks version, for installation issues (run `luarocks --version`):
> 
> Yeah, you can change the APISIX installation package to be built on APISIX-Base by default. You can use all the features that require APISIX-Base without any additional configuration.


我看二楼说是已经是基于apisix-Base的了，您这个没看懂的呢。是需要自己构建的么？还是说安装的时候给参数么？

**Comment by ro4i7** [comment]
> 我看二楼说是已经是基于apisix-Base的了，您这个没看懂的呢。是需要自己构建的么？还是说安装的时候给参数么？

means, you are already running APISIX on APISIX-Base, then you don't need to build it yourself or give any additional parameters during installation. then by default, APISIX should be able to use all the features that require APISIX-Base without any additional configuration. But, if you encounter any issues or errors related to this, then you need to check if APISIX is properly configured to use APISIX-Base.

You can look for the `--with-etcd` parameter in the output of the `apisix version` command. 
like for example, if the output contains the line:
```
built with: --with-etcd=/usr/local/apisix/etcd
```
then this, means that APISIX is built to use APISIX-Base located at `/usr/local/apisix/etcd`
