### ISSUE TITLE
Hope to support oidc+consumer-restriction whitelist+consumer to implement different system calls

### ISSUE THREAD

**Issue by peterlyz** [apache/apisix#9093]
### Description

1、前提：一个普通restful接口- 获取ldap员工信息

2、场景：目前有20几个系统需要调用这个接口，想通过网关的oidc鉴权插件控制哪些系统能用（因为要申请），每个系统有自己申请的client_id+client_secret

3、当前文档示例中，basic-auth+consumer-restriction的方式，能实现不同consumer的访问控制-不同系统对应不同consumer就能控制访问同一个API；
      希望使用openid-connect鉴权也能实现：不同系统使用不同client_id、client_secret访问同一个route。

**Comment by monkeyDluffy6017** [comment]
Would you like to create a pr to do this feature?
