### ISSUE TITLE
HTTP methods return "405 Not Allowed" #9091

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9095]
### Current Behavior

apisix returns 405 Not Allowed when I use the http methods trace and connect. How do I solve it?

the route config is :
.....
"priority": 1,
"methods": [
"TRACE",
"POST",
"GET",
"CONNECT"
],
.......

the request is :
[root@localhost]# curl -X TRACE "http://10.4.16.105:9080/yangcong/1k.txt"

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Expected Behavior

The route is normally upstream

### Error Logs

10.210.21.105 - - [17/Mar/2023:01:59:12 +0000] 10.210.21.105:9080 "TRACE /page/test HTTP/1.1" 405 154 0.000 "-" "curl/7.29.0" - - - "://"
no have error.log record

### Steps to Reproduce

apisix returns 405 Not Allowed when I use the http methods trace and connect. How do I solve it?

the route config is :
.....
"priority": 1,
"methods": [
"TRACE",
"POST",
"GET",
"CONNECT"
],
.......

the request is :
[root@localhost]# curl -X TRACE "http://10.4.16.105:9080/yangcong/1k.txt"

<html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

### Environment

- APISIX version (run `apisix :2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard :2.13-alpine,
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tokers** [comment]
Please do not create duplicated issues for the same question. I replied with the reason in #9091. So I will close this one.
