### ISSUE TITLE
help request: I need to monitor the health status of routes, not just upstream

### ISSUE THREAD

**Issue by guochunyang2004** [apache/apisix#9096]
### Description

English：
I need to monitor the health status of routes, not just upstream.

1. There is a problem with the officially provided health status monitoring. If the upstream node fails to access and there is no return value, it cannot be detected.

2. If only the upstream node is detected, it cannot be detected.

What schemes are available to detect whether the entire route is alive

中文：
我需要监控路由的健康状态，而不仅是上游的健康状态。
1.官方提供的健康状态监控有个问题，如果上游节点访问失败而且没有任何返回值，无法检测出来。
2. 如果只有上游节点也是无法检测出来。
有什么方案可以检测整个路由是否存活

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
> 1. There is a problem with the officially provided health status monitoring. If the upstream node fails to access and there is no return value, it cannot be detected.

Could you plz show the steps to help reproducing the issue?


> 2. If only the upstream node is detected, it cannot be detected.
> 
> What schemes are available to detect whether the entire route is alive

If you just want to monitor the details of routes, you can use [prometheus plugin](https://apisix.apache.org/docs/apisix/plugins/prometheus/)

**Comment by tokers** [comment]
So how to define the "health" of a route? Do you have any idea?

**Comment by shreemaan-abhishek** [comment]
Fixed by #9057
