### ISSUE TITLE
help request: Can Apisix support IP certificates

### ISSUE THREAD

**Issue by aiyiyi121** [apache/apisix#9109]
### Description

I have a requirement to use an https IP certificate.

I use Alibaba Cloud SLB reverse proxy to connect to my Apisix cluster. This https certificate is issued to the SLB IP address.
I have already added this certificate to Apisix, but when I access through https, I will still be prompted that it is not secure. 
Can the Apisix 2.10 version support certificates in the IP format?

![image](https://user-images.githubusercontent.com/65179185/226112073-1177cf22-0c0f-490a-a1b4-138c96f61162.png)

### Environment

- APISIX version (run `apisix version`): 2.10
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.19.3.1

**Comment by tokers** [comment]
Did you try to add the ip addresses to the SNI list of the SSL object?

**Comment by tokers** [comment]
Also, could you checkout the specific reason that your browser reports the unsafe event.

**Comment by aiyiyi121** [comment]
> Did you try to add the ip addresses to the SNI list of the SSL object?

![image](https://user-images.githubusercontent.com/65179185/226174183-9298acf8-3124-4f52-a25d-9d38f371b204.png)
I'm sure it has been added to the SNI list of the SSL object.

**Comment by aiyiyi121** [comment]
> Did you try to add the ip addresses to the SNI list of the SSL object?

![image](https://user-images.githubusercontent.com/65179185/226174183-9298acf8-3124-4f52-a25d-9d38f371b204.png)
I'm sure it has been added to the SNI list of the SSL object.

**Comment by aiyiyi121** [comment]
> Also, could you checkout the specific reason that your browser reports the unsafe event.

When I access through `https://ip`, its certificate was identified as another domain name certificate that I added. Cleaning up the cache is still the case.
![image](https://user-images.githubusercontent.com/65179185/226175018-0f37048b-a6f4-4d14-9df8-d3caeb2f98d8.png)

**Comment by tokers** [comment]
So what are the SAN sections in the certificate that you want the APISIX to return?

**Comment by aiyiyi121** [comment]
This certificate contains three IPs, and I hope that the authentication information it returns contains the IP address I requested.

For example, when I request nginx, it can return the correct IP certificate information
![image](https://user-images.githubusercontent.com/65179185/226229615-f1c8354c-dda3-48c8-89eb-eadddd2deb99.png)
