### ISSUE TITLE
help request: How to filter the log data by http status code when use the http-logger

### ISSUE THREAD

**Issue by KamenRiderKuuga** [apache/apisix#9118]
### Description

I want to do some log by the http status code, for example: when the response code is 400 or 500, I want to use an HTTP server to receive the log and record the request and response body

Now I use the `http-logger`, but it seems that I still got all the logs. The configuration is:
```json
{
  "uri": "http://log-server:8080",
  "include_req_body": true,
  "include_resp_body": true,
  "include_resp_body_expr": [
    [
      "status",
      ">",
      399
    ]
  ]
}
```

How should I do for doing this, thank you!

**In addition, I originally used serverless-post-function, but found that there is no way to directly do HTTP requests in it**

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux gateway-6d7798b968-gvqs4 5.4.164-1.el7.elrepo.x86_64 #&#8203;1 SMP Mon Dec 6 12:28:33 EST 2021 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by spacewander** [comment]
Maybe you can try https://github.com/apache/apisix/blob/master/docs/en/latest/terminology/plugin.md#dynamically-control-whether-the-plugin-is-executed?

**Comment by KamenRiderKuuga** [comment]
Thanks, this is exactly what I needed!
