### ISSUE TITLE
least conn algorithm is incorrect！！

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9121]
### Current Behavior

I set three servers (12, 14, 15), whose TCP connections are 197, 146, and 176,（with “netstat -ant | grep ^tcp | wc -l”） respectively. I used least conn algorithm, with the same weight. When I access route, I don't hit 14 servers all the time, but randomly.

### Expected Behavior

The server that can hit the minimum number of connections

### Error Logs

![image](https://user-images.githubusercontent.com/39228009/226506934-11df7c61-6fb9-4221-b9ef-20a36a1e51e9.png)

`192.168.88.66 - - [21/Mar/2023:02:39:25 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1096 0.009 "-" "PostmanRuntime/7.29.2" 10.4.16.14:8180 200 0.004 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:39:31 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.010 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.009 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:39:48 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.014 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.014 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:39:53 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.006 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.006 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:39:58 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.009 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.009 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:40:03 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.005 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.005 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:40:07 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.015 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.014 "http://yangcong.com.cn:9080/yangcong/1k.txt"
192.168.88.66 - - [21/Mar/2023:02:40:12 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.006 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.003 "http://yangcong.com.cn:9080/yangcong/1k.txt"
`

### Steps to Reproduce

For details, see Current Behavior

### Environment

- APISIX version (run `apisix :2.15-alpine`):   apisix :2.15-alpine    bitnami/etcd:3.4.15   dashboard:2.13-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Please provide complete steps to reproduce

**Comment by githubxubin** [comment]
> Please provide complete steps to reproduce

1.The first route configuration configures three upstream routes to provide the same service.

2.Second, the least conn algorithm is used to set the same weight to 1, and no plug-ins are configured

3.The third view three upstream server connections Respectively is 169 connection number 116 connection number 201 number of connections (with "netstat - ant | grep ^ TCP | wc -l")

4.The fourth request route discovery does not always hit the service with the minimum number of connections, but rather at random


route config:
`{
    "id": "451165119469060800",
    "create_time": 1678444966,
    "update_time": 1679370326,
    "uri": "/yangcong/*",
    "name": "测试",
    "priority": 1,
    "methods": [
        "TRACE",
        "POST",
        "GET",
        "CONNECT"
    ],
    "plugins": {
        "basic-auth": {
            "disable": true,
            "password": "df",
            "sdf": "sdf",
            "username": "dd"
        },
        "proxy-rewrite": {
            "headers": {
                "1111": "123456",
                "test": "88888"
            },
            "method": "POST",
            "scheme": "http"
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "10.4.16.14",
                "port": 8180,
                "weight": 1
            },
            {
                "host": "10.4.16.15",
                "port": 8180,
                "weight": 1
            },
            {
                "host": "10.4.16.12",
                "port": 8180,
                "weight": 1
            }
        ],
        "retries": 4,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "least_conn",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        },
        "retry_timeout": 1
    },
    "labels": {
        "1": "1"
    },
    "status": 1
}`

**Comment by soulbird** [comment]
How many workers have your apisix started? Note that the least conn algorithm is limited to a single worker

**Comment by githubxubin** [comment]
> How many workers have your apisix started? Note that the least conn algorithm is limited to a single worker

Only one route is used by only one user!!!

**Comment by soulbird** [comment]
I'm talking about the number of nginx workers, https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L140

**Comment by githubxubin** [comment]
> I'm talking about the number of nginx workers, https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L140

Can you give me a definite answer? Is it a bug in the system or my configuration,thanks!

**Comment by githubxubin** [comment]
> I'm talking about the number of nginx workers, https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L140

Is there anything wrong with my procedure? Or is the command to query the number of server connections faulty? Look forward to your reply. Thank you
