### ISSUE TITLE
least conn algorithm is incorrect！

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9126]
### Description

I set three servers (12, 14, 15), whose TCP connections are 197, 146, and 176, respectively. I used least conn algorithm, with the same weight. When I access route, I don't hit 14 servers all the time, but randomly.

image
192.168.88.66 - - [21/Mar/2023:02:39:25 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1096 0.009 "-" "PostmanRuntime/7.29.2" 10.4.16.14:8180 200 0.004 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:39:31 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.010 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.009 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:39:48 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.014 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.014 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:39:53 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.006 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.006 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:39:58 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.009 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.009 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:40:03 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.005 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.005 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:40:07 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1276 0.015 "-" "PostmanRuntime/7.29.2" 10.4.16.15:8180 200 0.014 "http://yangcong.com.cn:9080/yangcong/1k.txt" 192.168.88.66 - - [21/Mar/2023:02:40:12 +0000] yangcong.com.cn:9080 "GET /yangcong/1k.txt HTTP/1.1" 200 1146 0.006 "-" "PostmanRuntime/7.29.2" 10.4.16.12:8180 200 0.003 "http://yangcong.com.cn:9080/yangcong/1k.txt" 

### Environment

APISIX version (run apisix :2.15-alpine): apisix :2.15-alpine bitnami/etcd:3.4.15 dashboard:2.13-alpine
Operating system (run uname -a):
OpenResty / Nginx version (run openresty -V or nginx -V):
etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):
APISIX Dashboard version, if relevant:
Plugin runner version, for issues related to plugin runners:
LuaRocks version, for installation issues (run luarocks --version):

**Comment by soulbird** [comment]
same as #9121
