### ISSUE TITLE
Does retry_timeout have a default value?

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#9128]
### Description

if i open the healthy check, the retry have the default value,and retry_timeout have default value?where can i find it?

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
Hi, about health check you can refer: https://apisix.apache.org/docs/apisix/tutorials/health-check/

> Does retry_timeout have a default value? 

maybe you can refer this: https://apisix.apache.org/docs/apisix/admin-api/#upstream


also, you can check the source code. like: https://github.com/apache/apisix/blob/81149cd31567f6a86e33100fa7d09d7550073157/apisix/schema_def.lua#L385-L388
