### ISSUE TITLE
bug: Unable to start apisix

### ISSUE THREAD

**Issue by PhanPirang** [apache/apisix#9129]
### Current Behavior

I got problems while starting apisix.

### Expected Behavior

APISIX should start successfully based on Documentation.

### Error Logs

/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua start
Warning! Current maximum number of open file descriptors [1024] is not greater than 1024, please increase user limits by execute 'ulimit -n <new user limits>' , otherwise the performance is low.
nginx: [emerg] bind() to unix:/mnt/d/Project/Backend/APISIX/apisix-3.2.0/conf/config_listen.sock failed (22: Invalid argument)

### Steps to Reproduce

1. Clone APISIX and build from source
2. Start ETCD
3. Init apisix
4. Start apisix

### Environment

- APISIX version (3.2.0)
- Operating system (Linux)
- OpenResty / Nginx version (1.21.4.1)
- etcd version, if relevant (3.5.4)

**Comment by kellyseeme** [comment]
change the open file descriptors ,always ulimit -n ,the default value is 1024

**Comment by PhanPirang** [comment]
> change the open file descriptors ,always ulimit -n ,the default value is 1024

How to change it?

**Comment by PhanPirang** [comment]
> > change the open file descriptors ,always ulimit -n ,the default value is 1024
> 
> How to change it?

I've changed it now. The only problems left is that 

nginx: [emerg] bind() to unix:/mnt/d/Project/Backend/APISIX/apisix-3.2.0/conf/config_listen.sock failed (22: Invalid argument)
