### ISSUE TITLE
bug: route / and route /* are the same behavior

### ISSUE THREAD

**Issue by Yullin** [apache/apisix#9133]
### Current Behavior

two route as follow:
1. 
```
{
    "host": "example.com",
    "methods": [
        "GET"
    ],
    "upstream": {
        "nodes": {
            "192.168.1.223:80": 1
        }
    },
    "uri": "/*"
}
```
2.
```
{
    "host": "example.com",
    "methods": [
        "GET"
    ],
    "remote_addrs": ["192.168.2.0/24"],
    "upstream": {
        "nodes": {
            "192.168.1.223:80": 1
        }
    },
    "uri": "/"
}
```
IP 192.168.2.3 both get 200 status when access example.com/ and example.com/a.txt

### Expected Behavior

Expected:
1. 192.168.2.3 get 404 "route not found" response when access example.com/
2. 192.168.2.3 get 200 response when access example.com/a.txt

### Steps to Reproduce

1. add route / with `{remote_addrs: ["192.168.2.0/24"]}`
2. add route /* without "remote_addrs"
3. access these 2 routes

### Environment

- APISIX version (run `apisix version`): 2.12.1 and 2.15.3 and 2.13.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
When your request can match multiple routes at the same time, the matching result is unpredictable, which conforms to the current design.
Can you adjust your routing uri or add more precise conditions to distinguish different routes
