### ISSUE TITLE
Parameter unit   

### ISSUE THREAD

**Issue by githubxubin** [apache/apisix#9137]
### Description

Is the unit of upstream retry timeout seconds?

Is there a connection pool idle timeout in seconds?

Many page configuration does not have a unit, there is a detailed documentation can provide? This is really rough

 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
maybe you can refer admin api page: https://apisix.apache.org/docs/apisix/admin-api

You are also welcome to contribute to the documentation, and we appreciate it greatly.

**Comment by githubxubin** [comment]
Thank you for your reply. Could you please help hander  this issue? #9183 
 and That's a problem I've been having lately! itis strange!!!
