### ISSUE TITLE
help request: k8s discovery return errorlog: `informer_factory.lua:317: watch failed, kind: Endpoints, reason: ReadBodyError, message : closed, context: ngx.timer`

### ISSUE THREAD

**Issue by zsmlinux** [apache/apisix#9138]
### Description

error log: `informer_factory.lua:317: watch failed, kind: Endpoints, reason: ReadBodyError, message : closed, context: ngx.timer`

I found out the log came from :
![image](https://user-images.githubusercontent.com/10682145/226790756-f824fcd3-fbf3-44f1-a3a2-15c07d4d6b06.png)

Print more logs:
![image](https://user-images.githubusercontent.com/10682145/226790926-141bdb89-a271-453a-b154-363f7f2e2c9d.png)

Even though apiserver response_status is `200`, but also have `watch failed`'s error log. 

I think the reason is because the response_body is nil.

No services were being updated at the time, so response_body is nil.

Can we determine and adjust the level of such logs. It should not be error level.

### Environment

- APISIX version (run `apisix version`): 3.0.0
- Operating system (run `uname -a`): 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.3 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../apisix-nginx-module-1.11.0 --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../apisix-nginx-module-1.11.0/src/stream --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../apisix-nginx-module-1.11.0/src/meta --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.BZbTAq0pnL/openresty-1.21.4.1/../grpc-client-nginx-module-v0.3.1 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"id":"3847ad70-19a1-411b-be66-86a0a2014727","version":"3.0.0","etcd_version":"3.4.0","hostname":"logapisixgw-7bff4b8664-rkkvh","boot_time":1678631027}
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zhixiongdu027** [comment]
![image](https://user-images.githubusercontent.com/4032302/229668163-864bd992-cec5-4c61-a824-050d1700a21a.png)

I tend to think that the error in this place is the reason for the cluster or account permissions
Maybe you can try to use kubectl get --raw=''url' to try to read the data.
  The value of url is marked in the figure

Also, as a reminder, your pictures may contain information that should not be made public
