### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by idb-root** [apache/apisix#9139]
### Description

/usr/local/apisix/conf/config.yaml 配置了日志路径，为什么日志还是指向：/usr/local/apisix/logs/error.log -> /dev/stderr
nginx_config:    # config for render the template to genarate nginx.conf
  error_log: '/usr/local/apisix/logs/error.log'

请问应该怎么解决呢？

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):Linux apisix-75d9c66745-kslpf 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
1. Do you reload apisix after modified log path?
2. Make sure that you have write permission for the error.log.

**Comment by shreemaan-abhishek** [comment]
ping @idb-root
