### ISSUE TITLE
help request:  kubernetes service discovery doesn't work

### ISSUE THREAD

**Issue by marksmansj** [apache/apisix#9148]
### Description

Hello All.
  I already install apisix within k8s in namespace sr. I want to enable kubernetes service discovery. but it doesn't work. these are my config down below:
**1、I deployed nginx pod and svc**
**kubectl describe svc/nginxv3 -n sr**
Name:              nginxv3
Namespace:         sr
Labels:            app=nginxv3
                   version=v1
Annotations:       kubesphere.io/creator: admin
                   kubesphere.io/serviceType: statelessservice
Selector:          app=nginxv3
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                172.29.101.130
IPs:               172.29.101.130
Port:              tcp-80  80/TCP
TargetPort:        80/TCP
Endpoints:         172.29.22.180:80,172.29.47.188:80
Session Affinity:  None
Events:            <none>

**kubectl describe endpoints/nginxv3 -n sr**    
Name:         nginxv3
Namespace:    sr
Labels:       app=nginxv3
              version=v1
Annotations:  endpoints.kubernetes.io/last-change-trigger-time: 2023-03-21T14:44:35+08:00
Subsets:
  Addresses:          172.29.22.180,172.29.47.188
  NotReadyAddresses:  <none>
  Ports:
    Name    Port  Protocol
    ----    ----  --------
    tcp-80  80    TCP

Events:  <none>

**2、deployed sa**

kind: ServiceAccount
apiVersion: v1
metadata:
 name: apisix-test
 namespace: sr
---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: apisix-test
rules:
- apiGroups: [ "" ]
  resources: [ endpoints ]
  verbs: [ get,list,watch ]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
 name: apisix-test
roleRef:
 apiGroup: rbac.authorization.k8s.io
 kind: ClusterRole
 name: apisix-test
subjects:
 - kind: ServiceAccount
   name: apisix-test
   namespace: sr

**3、set apisix configmap and restart apisix pod**
      discovery:
        kubernetes:
          service:
            schema: https
            host: 192.168.140.35
            port: 6443
          client:
            token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijh5dDRXRUhha2JETDdzVXgwbENXZEFLQmRpYWRxZkZTWVk2NmozYzcwQjQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1l

**4、apisix route and upstream**
{
  "uri": "/*",
  "name": "nginxv3",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "nginxv3.test.com",
  "upstream": {
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "discovery_type": "kubernetes",
    "pass_host": "pass",
    "service_name": "sr/nginxv3:tcp-80",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}

**5、I set local hosts and access the domain and return 503 from server**
![image](https://user-images.githubusercontent.com/50012913/227071836-2ad58ec6-ea7d-45b5-8668-377b0b7d9f52.png)

**6、apisix log**
*8717918 [lua] init.lua:441: handle_upstream(): failed to set upstream: discovery kubernetes is uninitialized

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

apisix version
/usr/local/openresty//luajit/bin/luajit ./apisix/cli/apisix.lua version
3.1.0

uname -a
Linux k8smaster-01.test.com 5.16.8-1.el7.elrepo.x86_64 #1 SMP PREEMPT Mon Feb 7 18:12:06 EST 2022 x86_64 x86_64 x86_64 GNU/Linux

$ openresty -V
nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.5 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.4LxUDwBgw8/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.0 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

apache/apisix-dashboard:3.0.0-alpine

**Comment by marksmansj** [comment]
..

**Comment by baymaxlan** [comment]
Bro, has it been resolved? How was it resolved?

**Comment by swallretu** [comment]
the same issue i hit at apisix v3.8.0
