### ISSUE TITLE
help request: API is bound to different HTTP ports 

### ISSUE THREAD

**Issue by ccwxl** [apache/apisix#9152]
### Description

将api按照端口进行分类。例如有`api/a`,`api/b`,`api/c`,`api/d`
- 将`api/a`,`api/b`绑定到9801端口
- 将`api/c`,`api/d`绑定到9802端口
将流量分开。 apisix 是否支持，在文档里没看到。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
Is 9801 the port of the backend service? If yes, you can try traffic-split plugin.

**Comment by siaron** [comment]
9801 是apisix的端口

**Comment by soulbird** [comment]
This usage is not currently supported. But I'm curious about your usage scenario, can you describe it?

**Comment by siaron** [comment]
在一个服务里有两类http端口，一种是对外提供服务（南北流量，外网可访问），另一种是内部的服务（东西流量，外网不可访问），想通过apisix统一入口，所以想用不同端口处理，所以要绑定不同的api

**Comment by soulbird** [comment]
You can listen to multiple ports on APISIX to receive traffic at the same time, and then split the traffic to different backend services through the traffic-spilt plugin.
https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L24

**Comment by siaron** [comment]
这种情况下`api/a`,'api/b','api/c','api/d' 还是在两个端口中能访问呢，通过对外开放的9810端口也能访问到`api/c`,'api/d'。

**Comment by soulbird** [comment]
> 这种情况下`api/a`,'api/b','api/c','api/d' 还是在两个端口中能访问呢，通过对外开放的9810端口也能访问到`api/c`,'api/d'。

You can configure conditional routing through vars, binding uri and port (ngx.var.server_port) together
