### ISSUE TITLE
How to pass/add cookie from forward-auth upstream response to the final client

### ISSUE THREAD

**Issue by Trznadel** [apache/apisix#9153]
### Description

Hello,
I've recently started using APISIX and I'm currently struggling with the following issue. When a request is sent to my app, firstly it's forwarded to the authentication service via forward-auth plugin. The service takes a param from the request's header ("Authorization") and responds with a header with JWT token (JWT-AUTH, which is forwarded to the routed services) and also with an access token, that I would like to return to the client but I don't know how. It seems that a response-rewrite could maube solve the problem but I don't know if it's somehow possible to store (in some temp. variable) and pass a value ("test cookie") returned by authentication service. My sample configuration in .yaml config file looks like this and right now retruning a value to the client is hardcoded  ("test cookie"):

plugins:
      cors: {}
      forward-auth: {
        "uri": "http://authentication-service:8080/verifiy",
        "request_method": "POST",
        "request_headers": [ "Authorization" ],
        "upstream_headers": [ "JWT-AUTH" ]
      }
      response-rewrite: {
        headers: {
          set: {
            "Set-Cookie": "test-cookie"
          }
        }
      }
     
Could you please support?
Regards,
Andrzej

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
You can get the jwt token returned by the authentication service through `$http_jwt_auth` in the proxy-rewrite plugin (provided you configured `"upstream_headers": [ "JWT-AUTH" ]` ).
For the value (response body) returned by the authentication service, we currently do not have any method to get it
