### ISSUE TITLE
help request:can't use plugin [soap] 

### ISSUE THREAD

**Issue by coolboywcm** [apache/apisix#9154]
### Description

curl http://127.0.0.1:9180/apisix/admin/routes/1 \
    -H 'X-API-KEY: KEY' -X PUT -d '
{
    "methods": ["POST"],
    "uri": "/ws",
    "plugins": {
        "soap": {
            "wsdl_url": "http://127.0.0.1/xxx?wsdl"
        }
    }
}'

reponse:

{"error_msg":"unknown plugin [soap]"}

### Environment

- APISIX version (3.1.0):
- Operating system (CentOS Linux release 7.6.1810):
- OpenResty / Nginx version (nginx version: openresty/1.21.4.1):
- etcd version, if relevant ("etcd_version":"3.4.0"):
- APISIX Dashboard version, if relevant(3.0.0)

**Comment by woyouyitouchenfeijv** [comment]
Look at your config.yaml ，Is soap not configured

**Comment by coolboywcm** [comment]
How to configure about [soap] plugin in config.yaml ?
Can you give me an example

**Comment by coolboywcm** [comment]
> Look at your config.yaml ，Is soap not configured

How to configure about [soap] plugin in config.yaml ?
Can you give me an example

**Comment by coolboywcm** [comment]
> @coolboywcm SOAP plugin is not available in APISIX open source version currently.

When will it be available in open source version?

**Comment by kingluo** [comment]
> > @coolboywcm SOAP plugin is not available in APISIX open source version currently.
> 
> When will it be available in open source version?

Maybe it's available in the enterprise version only.

@membphis @moonming
