### ISSUE TITLE
bug: X-Forwarded-For logic error in real-ip plugin

### ISSUE THREAD

**Issue by bzp2010** [apache/apisix#9164]
### Current Behavior

When there are multiple IPs in XFF, real-ip will use the last IP as the source IP.

[code](https://github.com/apache/apisix/blob/master/apisix/plugins/real-ip.lua#L91-L100)

### Expected Behavior

According to MDN Web Docs, when XFF has multiple values, the first IP will be the client IP.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax

### Steps to Reproduce

1. Enable the real-ip plugin and try to send an XFF header with multiple IPs, APISIX will get the wrong one.

In fact, according to the code and MDN documentation, it has indeed been proven beyond doubt that there is an error here. And this error has existed for a long time.

### Environment

- APISIX version (run `apisix version`): 3.2.0 on master branch

**Comment by bzp2010** [comment]
This is a misidentification, and with a function like http://nginx.org/en/docs/http/ngx_http_realip_module.html#real_ip_recursive we can correctly handle request headers for multiple IPs.

**Comment by kellyseeme** [comment]
i change it in my docker,and restart it ,why it not affected?also the wrong results?
