### ISSUE TITLE
How can I reuse connections in dubbo-proxy?

### ISSUE THREAD

**Issue by heyaochun** [apache/apisix#9169]
### Description

I've tested to find that, apisix establishes a short connection to dubbo backend service when proxying a http request.

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  1.21.4
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by heyaochun** [comment]
It seems that ngx_stream_multi_upstream_module in Tengine(which is not maintained any more) controls connections.  
Any suggestions or help will be much appreciated. Thanks in advance.

**Comment by monkeyDluffy6017** [comment]
The dubbo feature is powered by `ngx_stream_multi_upstream` which is maintained by APISIX:
https://github.com/api7/ngx_multi_upstream_module
And I see that the connection pool is supported:
https://github.com/apache/apisix/pull/4506/files

**Comment by heyaochun** [comment]
> The dubbo feature is powered by `ngx_stream_multi_upstream` which is maintained by APISIX: https://github.com/api7/ngx_multi_upstream_module And I see that the connection pool is supported: https://github.com/apache/apisix/pull/4506/files

Thank you  from reply.
1. /api7/ngx_multi_upstream_module is actually  exacted from tengine-2.3.2 (https://github.com/alibaba/tengine/tree/master/modules/ngx_multi_upstream_module) , as you can see it in readme.md
2. keepalive doesn't work  with dubbo, mentioned in nginx.conf (or cli/ngx_tpl.lua).

In my current conlusion, dubbo_proxy is not suitable for prod env. since its weakness in：dubbo group not support\short connection\original module not maintained. Any further discussions are welcomed.

**Comment by huntkalio** [comment]
does dubbo_proxy support keepalive or multi ？
