### ISSUE TITLE
bug:global rules is not affectd in apisix 2.15.1

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#9172]
### Current Behavior

set the global_ruels use admin api,use the ip-restriction for whitelist ,when i use the disable true,but the whitelist is not take effect;if i use it in apisix 2.14.1,this is ok
curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c' -X PATCH -d '
{
    
    "plugins": {
        "ip-restriction": {
            "disable": false,
            "whitelist": [
                "127.0.0.2"            ]
        }
    }
}'

curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c' -X PATCH -d '
{
    
    "plugins": {
        "ip-restriction": {
            "disable": true,
            "whitelist": [
                "127.0.0.2"            ]
        }
    }
}'

### Expected Behavior

the same as apsixi 2.14.1
use "disable": false, this is take effect
 use "disable": true, this is not take effect
<img width="667" alt="image" src="https://user-images.githubusercontent.com/535200/227866011-f9c464e1-47cb-4118-83ff-400fd44c5b28.png">

### Steps to Reproduce

1 deploy the 2.15.1 env
2 set globals
curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c' -X PATCH -d '
{
    
    "plugins": {
        "ip-restriction": {
            "disable": true,
            "whitelist": [
                "127.0.0.2"            ]
        }
    }
}'
3 curl localhost:9080
4 
curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c' -X PATCH -d '
{
    
    "plugins": {
        "ip-restriction": {
            "disable": false,
            "whitelist": [
                "127.0.0.2"            ]
        }
    }
}'
5 curl localhost:9080

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
maybe you can try to use `_mata.disable`?

```sh
curl http://127.0.0.1:9080/apisix/admin/global_rules/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PATCH -i -d '{
        "plugins": {
	    "ip-restriction": {
		"_meta": {"disable": true},
            	"whitelist": [
                	"127.0.0.2"
            ]
        }
}}'

```

**Comment by kellyseeme** [comment]
tks,this is ok
