### ISSUE TITLE
docs: incorrect uri in "expose-api" tutorial

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix#9182]
It should be `/anything` and `example.com` here.

_Originally posted by @juzhiyuan in https://github.com/apache/apisix/pull/7952#discussion_r1150118134_

**Comment by woyouyitouchenfeijv** [comment]
Can I do this?

**Comment by Neilblaze** [comment]
I think an already approved PR already exists in #8730 
cc: @juzhiyuan, @leslie-tsang
