### ISSUE TITLE
Duplicate Limit Count For Broader Period

### ISSUE THREAD

**Issue by coffeebe4code** [apache/apisix#9186]
### Description

As an API Developer I would like to limit a consumer based on a short duration (preventing bursts, ddos, etc). AND, I would like to limit a consumer over a broader period.

Ie, this apikey or consumer can call an api X number of times per month according to their payment and billing plan.

In other api gateway terminology. The shorter duration is called a "Spike Arrest". The longer duration is considered a "Quota Limit".

We can do the work ourself and make this a custom plugin. But I thought this was generic enough, and easy enough to duplicate the limit count plugin, that it would be a good suggestion. If you would accept a PR, I would be willing to do so here and follow the contributor/pr guidelines.

**Comment by coffeebe4code** [comment]
@Neilblaze could I get some feedback, triage, routing, or tags? I'm not sure who I should ping

This is not ChatGPT generated :)

**Comment by Neilblaze** [comment]
cc: @juzhiyuan, @monkeyDluffy6017, @spacewander

**Comment by frankkoornstra** [comment]
We're also looking at this and are specifically interested in the quota limit per month since that is the most common billing cycle and doesn't seem to be supported by the [limit-count plugin](https://apisix.apache.org/docs/apisix/plugins/limit-count/).
