### ISSUE TITLE
docs: attributes undocumented for certain logging plugins

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix#9190]
### Current State

Thanks to APISIX's [excellent design](https://github.com/apache/apisix/blob/master/apisix/utils/log-util.lua), I found that many logging plug-ins support features such as `include_req_body`, `include_req_body_expr`,`include_resp_body`,`include_resp_body_expr`, such as `file-logger`,`http-logger`,`loggly`,`tencent-cloud-cls`. However, this feature does not appear in the [plug-in documentation](https://apisix.apache.org/docs/apisix/plugins/file-logger/) or in the [plug-in schema definition](https://github.com/apache/apisix/blob/01f0498498b6cbd90b5d9afc73a34a6931e3c724/apisix/plugins/file-logger.lua#L27). 

### Desired State

Maybe we should add the above.

**Comment by Neilblaze** [comment]
@Gallardot I'm taking this up!

**Comment by navendu-pottekkat** [comment]
@Neilblaze Are you still working on this issue?

**Comment by Neilblaze** [comment]
@navendu-pottekkat Sorry for the delay. I'm working on another issue, so if anyone wants to pick this up, please feel free to assign :)

**Comment by smileby** [comment]
@kayx23 can assignees it to me.  I'll do it

**Comment by pottekkat** [comment]
@smileby Thank you. Assigned.

**Comment by kayx23** [comment]
Going through some logging plugins now and noticed these options are not added to all logging plugins, such as `google-cloud-logging`. Should we open a new issue and track progress of the remaining, if any needs? Open for discussion.
