### ISSUE TITLE
Can limit-req or limit-count use keys from headers like "authorization" or from query parameters like "teant" or whatever?

### ISSUE THREAD

**Issue by 13140983173** [apache/apisix#9193]
### Description

I found documentation that says only ["remote_addr", "server_addr", "http_x_real_ip", "http_x_forwarded_for", "consumer_name"] could be used as key, refers to https://apisix.apache.org/zh/docs/apisix/plugins/limit-req

### Environment

- APISIX version (run `2.15.0`):

**Comment by tokers** [comment]
Set the `key_type` to `vars` and you can use the variables you want, for instance, if you want to use a HTTP header, use variable `http_header_name`, where header_name is the name of the HTTP header.

**Comment by fabrii** [comment]
Is this documented somewhere? I can see in https://apisix.apache.org/docs/apisix/plugins/limit-req/ that the valid values are ["var", "var_combination"]

**Comment by sdvdxl** [comment]
> Set the `key_type` to `vars` and you can use the variables you want, for instance, if you want to use a HTTP header, use variable `http_header_name`, where header_name is the name of the HTTP header.

not `vars` but `var_combination`

**Comment by andresvargasr** [comment]
@tokers just want to say thanks it  also worked for me using this conf:  `"key_type": "var"` and  `"key": "$http_my_header_name"`
