### ISSUE TITLE
bug: prometheus blocked somewhere and cause worker process full CPU usage

### ISSUE THREAD

**Issue by tangzhenhuang** [apache/apisix#9195]
### Current Behavior

prometheus blocked at somewhere(see the gdb bt at error logs)

### Expected Behavior

no blocked

### Error Logs

gdb attach all of the wokers and they block at:
(gdb) bt
#0  ngx_shmtx_lock (mtx=0x7e2ba7242068) at src/core/ngx_shmtx.c:86
#1  0x000000000057321f in ngx_meta_lua_ffi_shdict_get (zone=0xdaa1b8, key=0x7e2b9cdb83a8 "__ngx_prom__delete_count", key_len=24, value_type=0x7e2bb4799b48, str_value_buf=0x7e2bb47a25d0, str_value_len=0x7e2bb476b4b8,
    num_value=0x7e2bb47a2570, user_flags=0x7e2bb4799b98, get_stale=0, is_stale=0x7e2bb47a2590, err=0x7e2bb47c80a0) at /tmp/tmp.PEGq0wUP9q/openresty-1.21.4.1/../apisix-nginx-module-1.9.0/src/meta/ngx_meta_lua_shdict.c:1631
#2  0x00007e2be4f33e4a in ?? ()
#3  0x00007e2bb47a2570 in ?? ()
#4  0x00007e2bb4799b98 in ?? ()
#5  0x0000000000000000 in ?? ()

![image](https://user-images.githubusercontent.com/21658981/228504237-cb626579-a474-4af3-8655-a73d272941a0.png)

And the strace log:
![image](https://user-images.githubusercontent.com/21658981/228706256-525f77fe-3992-4dd8-9cec-28c824978881.png)
Looks like it's stuck in a loop(cyclically FUTEX_WAIT and FUTEX_WAKE)

### Steps to Reproduce

constantly

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux nginx-prd-it-8fd8df996-rzldj 4.19.113-300.el7.x86_64 #1 SMP Mon Mar 30 21:31:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by crazyMonkey1995** [comment]
I looked at it again and it seems that something is different. The problem I encountered is that the worker process has been stuck somewhere and did not return (from the perspective of the gdb stack), but from the the stack, it should also be related to prometheus and share dict
