### ISSUE TITLE
Why APISIX rebuild radixtree every time when i edit router?

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#9196]
### Description

I found that every time I modify the route, the `create_radixtree_uri_router` function  in `radixtree_uri.lua` is triggered.And i found no function about delete radixtree node in `easy_rax.c`.In my opinion,i think it will delete useless node or add new node on the same radixtree when i modify route,instead of present.I'm wondering why radixtree is being edited this way now, or what's wrong with the way I said.
```
//radixtree_uri.lua
function _M.match(api_ctx)
    local user_routes = _M.user_routes
    if not cached_version or cached_version ~= user_routes.conf_version then
        uri_router = base_router.create_radixtree_uri_router(user_routes.values,
                                                             uri_routes, false)
        cached_version = user_routes.conf_version
    end

    if not uri_router then
        core.log.error("failed to fetch valid `uri` router: ")
        return true
    end

    return base_router.match_uri(uri_router, match_opts, api_ctx)
end
```

**Comment by zccabb** [comment]
I think it might be
Radixtree pursues maximum lookup performance, so both building and rebuilding need to be very efficient. Choosing to only support adding new nodes can simplify the implementation and improve performance. 
If deleting old nodes and adding new nodes are used to update the radixtree, the implementation will be more complex and the efficiency will be difficult to reach the level of rebuilding a new radixtree.
As an auxiliary route lookup structure, the radixtree is accessed by a large number of requests. Even if it is rebuilt, it can be quickly rebuilt to meet performance requirements. This complete rebuild approach can achieve the simplest and most efficient implementation.
