### ISSUE TITLE
help request: OIDC loss of session data

### ISSUE THREAD

**Issue by sunerlin** [apache/apisix#9197]
### Description

session中的数据时间很短就会丢失
`2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1202: authenticate(): OIDC Authorization Code Flow completed -> Redirecting to original URL (/)
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1511: authenticate(): session.present=true, session.data.id_token=true, session.data.authenticated=true, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1563: authenticate(): id_token={"aud":["9f3db13007c0d44b5394"],"scope":"openid","name":"0286","owner":"sunshine","jti":"admin\/09df822a-2b4c-419c-b7eb-2bbb4a0a2e53","iat":1680082961,"iss":"http:\/\/192.168.166.247:7003","sub":"ee7b7276-c6fd-49f6-aedb-499c033b84bf","nonce":"71ff898d8b314faad05edba454d952e2","exp":1680090161,"tokenType":"access-token","nbf":1680082961}
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1511: authenticate(): session.present=true, session.data.id_token=true, session.data.authenticated=true, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1563: authenticate(): id_token={"aud":["9f3db13007c0d44b5394"],"scope":"openid","name":"0286","owner":"sunshine","jti":"admin\/09df822a-2b4c-419c-b7eb-2bbb4a0a2e53","iat":1680082961,"iss":"http:\/\/192.168.166.247:7003","sub":"ee7b7276-c6fd-49f6-aedb-499c033b84bf","nonce":"71ff898d8b314faad05edba454d952e2","exp":1680090161,"tokenType":"access-token","nbf":1680082961}
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1511: authenticate(): session.present=true, session.data.id_token=true, session.data.authenticated=true, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1563: authenticate(): id_token={"aud":["9f3db13007c0d44b5394"],"scope":"openid","name":"0286","owner":"sunshine","jti":"admin\/09df822a-2b4c-419c-b7eb-2bbb4a0a2e53","iat":1680082961,"iss":"http:\/\/192.168.166.247:7003","sub":"ee7b7276-c6fd-49f6-aedb-499c033b84bf","nonce":"71ff898d8b314faad05edba454d952e2","exp":1680090161,"tokenType":"access-token","nbf":1680082961}
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1511: authenticate(): session.present=true, session.data.id_token=true, session.data.authenticated=true, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 47#47: *15082 [lua] openidc.lua:1563: authenticate(): id_token={"aud":["9f3db13007c0d44b5394"],"scope":"openid","name":"0286","owner":"sunshine","jti":"admin\/09df822a-2b4c-419c-b7eb-2bbb4a0a2e53","iat":1680082961,"iss":"http:\/\/192.168.166.247:7003","sub":"ee7b7276-c6fd-49f6-aedb-499c033b84bf","nonce":"71ff898d8b314faad05edba454d952e2","exp":1680090161,"tokenType":"access-token","nbf":1680082961}
2023/03/29 09:42:41 [debug] 47#47: *15083 [lua] openidc.lua:1511: authenticate(): session.present=true, session.data.id_token=true, session.data.authenticated=true, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 47#47: *15083 [lua] openidc.lua:1563: authenticate(): id_token={"aud":["9f3db13007c0d44b5394"],"scope":"openid","name":"0286","owner":"sunshine","jti":"admin\/09df822a-2b4c-419c-b7eb-2bbb4a0a2e53","iat":1680082961,"iss":"http:\/\/192.168.166.247:7003","sub":"ee7b7276-c6fd-49f6-aedb-499c033b84bf","nonce":"71ff898d8b314faad05edba454d952e2","exp":1680090161,"tokenType":"access-token","nbf":1680082961}
2023/03/29 09:42:41 [debug] 52#52: *16449 [lua] openidc.lua:1511: authenticate(): session.present=nil, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false
2023/03/29 09:42:41 [debug] 52#52: *16449 [lua] openidc.lua:560: openidc_discover(): openidc_discover: URL is: http://192.168.166.247:7003/.well-known/openid-configuration
2023/03/29 09:42:41 [debug] 52#52: *16449 [lua] openidc.lua:115: openidc_cache_get(): cache hit: type=discovery key=http://192.168.166.247:7003/.well-known/openid-configuration
2023/03/29 09:42:41 [debug] 52#52: *16449 [lua] openidc.lua:695: openidc_get_token_auth_method(): token_endpoint_auth_method result set to client_secret_basic
2023/03/29 09:42:41 [debug] 52#52: *16449 [lua] openidc.lua:1542: authenticate(): Authentication is required - Redirecting to OP Authorization endpoint
2023/03/29 09:42:41 [debug] 53#53: *16452 [lua] openidc.lua:1511: authenticate(): session.present=nil, session.data.id_token=false, session.data.authenticated=nil, opts.force_reauthorize=nil, opts.renew_access_token_on_expiry=nil, try_to_renew=true, token_expired=false`

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
Could you provide reproduction steps?
