### ISSUE TITLE
help request: apisix cluster setup

### ISSUE THREAD

**Issue by balamir1979** [apache/apisix#9199]
### Description

How to create a cluster with 3 apisix gateway? Is it possible clustering the apisix servers?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by fatih-codee** [comment]
I also search creating high avaliability cluster with docker. please add your comment folks

**Comment by Sn0rt** [comment]
yep. the user can deploy the contorl palne and the data palne at different machine.
and the etcd can deployed as a cluster.
