### ISSUE TITLE
help request: Openwhisk doesn't get headers/arguments when making request through APISIX

### ISSUE THREAD

**Issue by crhenrici** [apache/apisix#9200]
### Description

To experiment with certain authentication methods I'm using the Openwhisk plugin which runs before the request to implement some custom authentication. With the request I'm passing some headers which are needed for the authentication. My expectation is that I would could access the header in Openwhisk through the parameters in the main function of the Openwhisk function. However I've come to find out that the paremetes is empty and hence I can't access the information in the header.

How can I access the header or the info passed as header in the request I'm making?

I've tested this with postman and with curl. Following the curl command
`curl http://localhost:9080/somepath/ --header "userid:someuserid" --header "password:somepassword"`

I'm running APISIX as a docker image, using the official docker image from APISIX.

Any help or pointers are greatly appreciated.

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`): Linux f1862785e9d1 5.15.49-linuxkit #1 SMP Tue Sep 13 07:51:46 UTC 2022 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.0
- APISIX Dashboard version, if relevant: 2.15.0
- Plugin runner version, for issues related to plugin runners: Where do I find this? I'm using the Openwhisk plugin.
- LuaRocks version, for installation issues (run `luarocks --version`): 
- Openwhisk version: 1.0.0 (for what it's worth)

**Comment by mscb402** [comment]
I read the code and it look like openwhisk plugin does not send all header to openwhisk.
https://github.com/apache/apisix/blob/809ba09b26ddd62e0efa612f85e90d1aa938ce02/apisix/plugins/openwhisk.lua#L75-L89

**Comment by crhenrici** [comment]
Unfortunate but in the code I can see that it sends a body as part of the POST request. So maybe I can use that as a workaround.
