### ISSUE TITLE
help request: apisix How to directly return the status code through response rewrite;

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix#9203]
### Description

The return operation similar to nginx

```
        location /status/ {
            return 200 ;
        }
```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jinjianming** [comment]
- This is how I fulfilled my needs
- You must configure an upstream or you cannot obtain data

```
    "response-rewrite": {
      "_meta": {
        "disable": false
      },
      "body": "code: ok",
      "headers": {
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Allow-Origin": "*"
      },
      "status_code": 200
    }
  },
  "upstream": {
    "nodes": [{
      "host": "127.0.0.1",
      "port": 80,
      "weight": 100
    }],
```

**Comment by jiangfucheng** [comment]
Maybe you can use `fault-injection pugin`. https://apisix.apache.org/docs/apisix/plugins/fault-injection/

**Comment by shreemaan-abhishek** [comment]
@jinjianming I am closing this issue, you can reopen it if you have more questions.
