### ISSUE TITLE
help request: After enabling the stream agent on the Mac M1 machine, ‘make run’  error

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9206]
### Description

2023/03/30 17:15:44 [error] 41544#11130185: *1605 stream [lua] config_etcd.lua:659: failed to fetch data from etcd: ...Cellar/openresty/1.21.4.1_2/lualib/resty/core/shdict.lua:406: dlsym(RTLD_DEFAULT, ngx_stream_lua_ffi_shdict_get_macos): symbol not found
stack traceback:
 [C]: in function '__index'
 ...Cellar/openresty/1.21.4.1_2/lualib/resty/core/shdict.lua:406: in function 'ngx_lua_ffi_shdict_get'
 ...Cellar/openresty/1.21.4.1_2/lualib/resty/core/shdict.lua:614: in function 'get'
 ...t/apisix//deps/share/lua/5.1/resty/etcd/health_check.lua:38: in function 'get_target_status'
 ...lua_project/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:75: in function 'choose_endpoint'
 ...lua_project/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:737: in function 'http_request_chunk'
 ...lua_project/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:819: in function 'request_chunk'
 ...lua_project/apisix//deps/share/lua/5.1/resty/etcd/v3.lua:1132: in function 'watchdir'
 ...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:165: in function 'http_waitdir'
 ...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:216: in function 'waitdir'
 ...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:388: in function 'sync_data'
 ...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:606: in function <...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:596>
 [C]: in function 'xpcall'
 ...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:596: in function <...qiangzhao/lua_project/apisix/apisix/core/config_etcd.lua:574>,  etcd key: /apisix/ssls, context: ngx.timer

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zzqCh** [comment]
Does anyone answer?

**Comment by Sn0rt** [comment]
maybe you need try this https://github.com/api7/apisix-build-tools/blob/master/build-apisix-base.sh .

this script inclue some patchs for apisix run at arm64 machine.


BTW. I test the APISIX at myself M2 machine.

```
~/w/apisix *master> type openresty
openresty is /usr/local/openresty/bin/openresty
~/w/apisix *master> file /usr/local/openresty/bin/openresty
/usr/local/openresty/bin/openresty: Mach-O 64-bit executable arm64
```
