### ISSUE TITLE
help request: proxy_mirror插件能否配置多个host

### ISSUE THREAD

**Issue by chenwenjun-github** [apache/apisix#9215]
### Description

以下是官网文档对于proxy_mirror的解释，请问其中的host能否配置多个
![image](https://user-images.githubusercontent.com/46237364/229174994-f407dc74-71ee-4e08-9764-a9b09ee881e5.png)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by mscb402** [comment]
Not support for now

**Comment by Sn0rt** [comment]
currenlty. the the proxy_mirror not support multiple host for mirror. 
you can found the implementation from here https://github.com/apache/apisix/blob/809ba09b26ddd62e0efa612f85e90d1aa938ce02/apisix/plugins/proxy-mirror.lua#L30

**Comment by chenwenjun-github** [comment]
thanks, I haved write a custom plugin base on proxy_mirror to support mulit host, close this problem

**Comment by ryan4yin** [comment]
in fact, multi host can be implemented by using nginx's `upstream` with the plugin `proxy-mirror`, more details here:

https://github.com/apache/apisix/issues/9690
