### ISSUE TITLE
bug:  function _M.run_plugin , if a plugin has error, the request will be error

### ISSUE THREAD

**Issue by wonchar** [apache/apisix#9218]
### Current Behavior

                local ok, code, body = pcall(phase_func, conf, api_ctx)
                if not ok then
                    core.log.error(plugins[i].name, " is error ", phase)
                    if api_ctx.plugin_err == nil or api_ctx.plugin_err == "" then
                        api_ctx.plugin_err = plugins[i].name .. "#" .. phase
                    else
                        api_ctx.plugin_err = api_ctx.plugin_err .. "," .. plugins[i].name .. "#" .. phase
                    end
                end

### Steps to Reproduce

source code : plugin.lua

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

apisix 3.2

**Comment by Sn0rt** [comment]
can you share the path of this file or to create a unit test for validation of this issues ?
