### ISSUE TITLE
docs: use bash to configure ssl resource

### ISSUE THREAD

**Issue by kingluo** [apache/apisix#9229]
### Current State

https://apisix.apache.org/docs/apisix/certificate/#single-sni

It uses a python script to upload cert and key files in the ssl configuration.

But this script is not user-friendly, the user needs to install python and `requests` package.

### Desired State

We could use bash builtin syntax to configure the ssl resource.

```bash
curl http://127.0.0.1:9180/apisix/admin/ssls/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "cert": "'"$(<server.crt)"'",
    "key": "'"$(<server.key)"'",
    "snis": [
        "*.apisix.dev"
    ]
}'
```

**Comment by kayx23** [comment]
Here as well https://apisix.apache.org/docs/apisix/mtls/#how-to-configure-2

**Comment by kayx23** [comment]
Another issue opened for consolidating all mTLS docs: https://github.com/apache/apisix/issues/9485

**Comment by smileby** [comment]
@kingluo I think this has been solved

**Comment by kayx23** [comment]
It hasn't. I'm still seeing Python scripts.

**Comment by smileby** [comment]
I saw the Python script in [Mutual TLS Authentication](https://apisix.apache.org/docs/apisix/mtls/), but not in [Certificate](https://apisix.apache.org/docs/apisix/certificate/#single-sni)

**Comment by kayx23** [comment]
> I saw the Python script in [Mutual TLS Authentication](https://apisix.apache.org/docs/apisix/mtls/), but not in [Certificate](https://apisix.apache.org/docs/apisix/certificate/#single-sni)

I see... yeah

**Comment by smileby** [comment]
This issue, if it only deals with [Mutual TLS Authentication](https://apisix.apache.org/docs/apisix/mtls/), then I can try it

**Comment by kayx23** [comment]
Yeah of course, you can give it a go 🙂
