### ISSUE TITLE
As a user, i want new nodes from kubernetes discovery has lower weight with other nodes

### ISSUE THREAD

**Issue by flca267** [apache/apisix#9230]
### Description

As a user, i want new nodes from kubernetes discovery has lower weight with other nodes in several minutes.
Now a new node from kubernetes discovery has the same default weight with other existing nodes. Some service's newly instance may need several minutes to "warmup". If the new node has the same weight with others, it may under low performance during the "warmup" period. 
The kubernetes discovery's nodes() method fetch nodes from a lrucache, so add a timer to set new weight ? Or is there any better way to do this?

**Comment by zhixiongdu027** [comment]
By default, kubernetes records all pod ips in the endpoints resource without discrimination, rather than sorting them by startup time.

       In order to achieve your needs, you should develop a kubernetes operator that identifies the weight for each pod in the endpoint resource, The weights are then read and applied by discovery

       Another way is to use the kubernetes probe function to delay adding pod ip to endpoints, and use sidecar "warmup" during the delay

**Comment by chenwenjun-github** [comment]
> 

I have the same need, now I just use the kubernetes probe function to delay adding pod ip to endpoints, and in sidecar use proxy_mirror plugin to warmup, it work when protocol is http, but my protocol is grpc, proxy_mirror don't support grpc
