### ISSUE TITLE
how to do suffix match

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#9232]
### Description

in nginx this is a settings like :
location ~* .*\.(gif|jpg|jpeg|png|css|js|ico)$ {
        proxy_pass server

how to set this in apisix?

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kingluo** [comment]
@kellyseeme 

You could add uri matching rule in the route cfg.

```bash
curl http://127.0.0.1:9180/apisix/admin/routes/1 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "methods": ["GET"],
    "uri": "/*",
    "vars": [
        ["uri", "~~", "\\.(gif|jpg|jpeg|png|css|js|ico)$"]
    ],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'

-- other rules ...
curl http://127.0.0.1:9180/apisix/admin/routes/2 \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -i -d '
{
    "methods": ["GET"],
    "uri": "/get",
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'
```
