### ISSUE TITLE
feat: As a user, I want forward-auth plugin to allow degradation , so that appropriate for some special scenarios.

### ISSUE THREAD

**Issue by Gallardot** [apache/apisix#9233]
### Description

As a user, I want the `forward-auth` plug-in to allow degradation when authorization service is unavailable, which is suitable for some special scenarios. 

https://github.com/apache/apisix/blob/809ba09b26ddd62e0efa612f85e90d1aa938ce02/apisix/plugins/forward-auth.lua#L122-L126

ps: For example, the [limit-count](https://apisix.apache.org/docs/apisix/plugins/limit-count/) plugin supports degradation when redis is unavailable

**Comment by Sn0rt** [comment]
If a business system is configured with authentication and the authentication module is down, it is expected that the business system will refuse user authentication.

This is different from cache optimization performance such as redis.

**Comment by Gallardot** [comment]
> if the forward-auth support `degradation` config and the `degradation` has been set as `true`. it will pass if the authentication server has no obvious rejection (include auth server down), and only reject the authentication when specifying to return the http status code of 4xx.
> 
> Is this what you mean ?

Yes.🤝

**Comment by Sn0rt** [comment]
@leslie-tsang cc

**Comment by shreemaan-abhishek** [comment]
> in some internal service security is not mandatory.

Then it's better not to use the plugin than to allow to skip authentication using a flag. WDYT?

**Comment by Sn0rt** [comment]
> > in some internal service security is not mandatory.
> 
> Then it's better not to use the plugin than to allow to skip authentication. WDYT?
> 
> I mean, at any cost, if we can afford to allow to skip authentication, then there is no point in authenticating all requests. We can TOTALLY skip authentication and not use the `forward-auth` plugin at all.

the user can enable the `forward-auth` plugin for a specific router (path). if the `path` not needs authentication, the user can skip to configure this plugin. 

and the `degradation` option only work for fault tolerance.

@shreemaan-abhishek

**Comment by shreemaan-abhishek** [comment]
> and the `degradation` option only work for fault tolerance.

IMHO, the correct way to add fault tolerance to an authentication system would be to add more replicas of the authentication server. If the user thinks that it's okay if the authentication is skipped for some requests in the case where authentication server is unavailable, then the user is better off disabling the authentication completely.

Maybe I am missing the author's point, but I don't really think that we should support this feature as it does not serve a bigger purpose.

**Comment by Gallardot** [comment]
@shreemaan-abhishek  

We are applying this plugin to a security detection scenario, which expands the capabilities of this plugin. It's not just for user authentication. In the context of security detection. With this plugin, we can capture requests and also intercept them.

**Comment by shreemaan-abhishek** [comment]
Let me give it a try I'll be back with a PR soon.
