### ISSUE TITLE
help request: Upstream services require different consumers to return different information on how to place their username in the header, and whether this header can be used as the username for casbin

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#9249]
### Description

Upstream services require different consumers to return different information on how to place their username in the header, and whether this header can be used as the username for casbin
### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
can you provider more info about the http body ?

casbin is responsible for authorization, not authentication. maybe you should process authorization by your self by Casbin.

of course , you can set http header by the proxy-rewrite plugin.

reference: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by cverdela** [comment]
I'm not talking about authorization, but how to solve the problem of authorization and authentication at the same time

**Comment by cverdela** [comment]
In addition, identity information is passed to the upstream through the gateway, and the upstream returns different results according to different identities in the same route

**Comment by Sn0rt** [comment]
are you read this https://apisix.apache.org/zh/docs/apisix/plugins/authz-casbin/ ? 
maybe it's useful for you

**Comment by cverdela** [comment]
You didn't understand what I meant

**Comment by Sn0rt** [comment]
Can you give a specific example? I can't imagine your scene in one or two sentences

**Comment by cverdela** [comment]
There are three consumers a, b, and c. A and b have the same organization as 1, and c has the same organization as 2. The authentication of a, b, and c needs to be different. When accessing the same upstream, a and b return 11, and c return 22. Upstream only returns based on the organizational judgment passed in the header, without consumer information

**Comment by cverdela** [comment]
I need to prevent a from obtaining 22 through any means

**Comment by cverdela** [comment]
What is the execution order of the three plugins a, b and c? How to make them execute in the order of a, b, and c

**Comment by cverdela** [comment]
`"key-auth": {},
        "proxy-rewrite": {
            "headers": {
                "add": {
                    "tenant": "$consumer_group_id"
                }
            }
        },
        "authz-casbin": {
            "model": "[request_definition]
            r = sub, obj, act

            [policy_definition]
            p = sub, obj, act

            [role_definition]
            g = _, _

            [policy_effect]
            e = some(where (p.eft == allow))

            [matchers]
            m = (g(r.sub, p.sub) || keyMatch(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)",

            "policy": "p, *, web1, GET
            p, admin, *, *
            g, 1000, admin",

            "username": "tenant"
        }
    },`

**Comment by cverdela** [comment]
I want to use proxy rewrite to write consumer group information to the header, and then use casbin to confirm permissions. Upstream users can also obtain header information

**Comment by cverdela** [comment]
I have 1 consumer group 2080. Jack is a consumer in 2080. I added the header as the ID of the consumer group using proxy rewrite, and verified the header using casbin. Surprisingly, the header. add implemented my idea, but the header. set failed
