### ISSUE TITLE
help request: Can proxy-rewite plugin support multiple path rewrite?

### ISSUE THREAD

**Issue by GloryAndDream** [apache/apisix#9258]
### Description

> 
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: service-route
  namespace: dev
spec:
  http:
    - name: machine-service-app
      match:
        hosts:
          - api-test.xxx.com
        paths:
          - "/machine/*"
          - "/pay/*"
      plugins:
      - name: proxy-rewrite
        enable: true
        config:
          regex_uri: ["^/machine|pay(/|$)(.*)", "/$2"]
      backends:
      - serviceName: machine-service-app
        servicePort: 8001
> 

I want to proxy-rewrite support multiple paths, but even I got regexp correct, it didn't work for both paths:

e.g. regexp is below:

**^/machine|pay(/|$)(.*)**

can match below paths:

**/machine/tests
/machine
/machine/
/pay/testset
/pay/**

However, when I deploy this configurations, it can only match paths begin with **/machine/*** , not the **/pay/xxx**

Is there a solution or not? 

### Environment

- APISIX version (run `apisix version`): 
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kingluo** [comment]
Your regex is wrong.

Example:

```bash
curl http://127.0.0.1:9180/apisix/admin/routes/1  \
-H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "methods": ["GET"],
    "uri": "/*",
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": ["^/(machine|pay)(/.*)", "/$2"]
        }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "httpbin.org": 1
        }
    }
}'
```

**Comment by GloryAndDream** [comment]
> Your regex is wrong.
> 
> Example:
> 
> ```shell
> curl http://127.0.0.1:9180/apisix/admin/routes/1  \
> -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
> {
>     "methods": ["GET"],
>     "uri": "/*",
>     "plugins": {
>         "proxy-rewrite": {
>             "regex_uri": ["^/(machine|pay)(/.*)", "/$2"]
>         }
>     },
>     "upstream": {
>         "type": "roundrobin",
>         "nodes": {
>             "httpbin.org": 1
>         }
>     }
> }'
> ```

I tried you regexp, still not working


**http://api-test.xxx.com/machine/health**

```

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Apr 07 21:56:08 CST 2023
There was an unexpected error (type=Not Found, status=404).
```


**http://api-test.xxx.com/machine**

`{"error_msg":"404 Route Not Found"}`

seems only first part of path goes to controller, by the way, the API is built on springboot

**Comment by GloryAndDream** [comment]
> ```shell
> "^/(machine|pay)(/.*)", "/$2"
> ```

Yes, I need to extract second part, but I tried this regexp "^/machine(/.*)", "/$2" , it worked fine, the url **http://api-test.xxx.com/machine/health** is accessible 

it seems the plugin can't handle with **|**

**Comment by kingluo** [comment]
`|` must be quoted with `(`. That's not a bug, it's regex usage issue.

What's your question? I'm really confused.

> However, when I deploy this configurations, it can only match paths begin with /machine/* , not the /pay/xxx

or 

>http://api-test.xxx.com/machine
>
>{"error_msg":"404 Route Not Found"}`

Anyways, the regex obeys the pcre regex standard, please change your regex to fit your need.

**Comment by GloryAndDream** [comment]
I need to match below urls:
e.g. 
**http://api-test.xxx.com/machine/aaa

http://api-test.xxx.com/pay/bbb**

however, I can't find the correct regexp to get what I need with plugin proxy-rewite

**Comment by GloryAndDream** [comment]
anyone can help me with correct regex string?
