### ISSUE TITLE
bug: datadog plugin failed to send metric when consumer is used with route for authentication

### ISSUE THREAD

**Issue by 0prodigy** [apache/apisix#9269]
### Current Behavior

datadog plugin failed to send metric

### Expected Behavior

plugin should send metric to datadog agent

### Error Logs

lua entry thread aborted: runtime error: /usr/local/apisix/apisix/plugins/datadog.lua:92: attempt to concatenate field 'consumer' (a table value)

### Steps to Reproduce

1. Enable datadog plugin in routes
2. Check log 

### Environment

- APISIX version (run apisix version): 3.0.0
- Operating system (run uname -a): Linux (x86_64 GNU/Linux)
- OpenResty / Nginx version (run openresty -V or nginx -V): openresty/1.21.4.1
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run luarocks --version):

**Comment by Sn0rt** [comment]
can you share your config of the router ?

**Comment by shreemaan-abhishek** [comment]
@0prodigy please share steps to reproduce, I have configured the dd plugin before and it worked.

**Comment by monkeyDluffy6017** [comment]
I will close this due to long period of inactivity, please feel free to reopen it

**Comment by zhuoyang** [comment]
I am facing this issue as well, it only happens when there's authentication enabled on the route

**Comment by kayx23** [comment]
I was able to reproduce the issue with the following steps:

1. configure datadog on a route
2. configure a consumer with `key-auth`
3. patch the route with `key-auth`
4. send a request to the route and check logs

![image](https://github.com/apache/apisix/assets/39619599/4d75ef97-6b60-471b-aaed-aed319036bf8)

cc: @Vacant2333

**Comment by shreemaan-abhishek** [comment]
looks like a good first issue to me

**Comment by Vacant2333** [comment]
> I was able to reproduce the issue with the following steps:
> 
> 1. configure datadog on a route
> 2. configure a consumer with `key-auth`
> 3. patch the route with `key-auth`
> 4. send a request to the route and check logs
> 
> ![image](https://private-user-images.githubusercontent.com/39619599/297947139-4d75ef97-6b60-471b-aaed-aed319036bf8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5OTEwOTMsIm5iZiI6MTcwNTk5MDc5MywicGF0aCI6Ii8zOTYxOTU5OS8yOTc5NDcxMzktNGQ3NWVmOTctNmI2MC00NzFiLWFhZWQtYWVkMzE5MDM2YmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDA2MTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmOWU4OTg4MjM0ZDdiNDQ1Nzk4YzVmMThlNTlhOGMwYzI4ZTdjNDIxMTljMTZhMzAxMjZhYTQ2YmFiNGJhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jEWeysuXIKsgEjZrufgMI_O-EWHxroSGHs0hahPajo)
> 
> cc: @Vacant2333

u can assign me this, i will take a look when im free~~

**Comment by ecoupal-believe** [comment]
https://github.com/apache/apisix/pull/10934
