### ISSUE TITLE
request help: Doc for OAuth 2 Plugin

### ISSUE THREAD

**Issue by sshniro** [apache/apisix#927]
### Issue description
I want to integrate APISIX with Keycloak Identity Provider (OAuth 2). The ReadMe Lists OAuth2 as a feature. Is there any usage document? or should it be created?

**Comment by moonming** [comment]
the document of OAuth 2 is in the todo list.
PR is welcome :)

**Comment by sshniro** [comment]
Okay, I'll try to create a doc, is there any medium (slack/discord) the development channel is active on, for any clarifications regarding the plugin?

**Comment by moonming** [comment]
we have test cases for openid-connect: https://github.com/apache/incubator-apisix/blob/master/t/plugin/openid-connect.t

**Comment by sshniro** [comment]
Closing this issue, as the doc has been created by #987
