### ISSUE TITLE
Ext-plugin phase_func error not found unix:sock file (eg: connect() to unix:/usr/local/apisix/conf/apisix-1.sock failed (2: No such file or directory))

### ISSUE THREAD

**Issue by 15810111831** [apache/apisix#9272]
### Description

**### Expedited!!**
Deploy through the example in github, and use go-runner to compile ext-plugin, but the sock file is not found when using ext-plugin-pre-req to load the plugin.
![image](https://user-images.githubusercontent.com/30543961/230812853-722cdc82-ec73-481d-8b65-c5fd971fcc00.png)

config:
![image](https://user-images.githubusercontent.com/30543961/230813456-36f1a644-84ff-4539-af05-642f9338dc9c.png)

Docker container conf dir:
can't found 
![image](https://user-images.githubusercontent.com/30543961/230813888-b62aeafa-cfbc-4c8e-b37a-74bd72fd37a6.png)

![image](https://user-images.githubusercontent.com/30543961/230813770-3dc40581-8ebf-4ebb-9010-1cf960d6cae1.png)

### Environment

- APISIX version (3.2.0):
- Operating system (aarch64 GNU/Linux):
- OpenResty / Nginx version (nginx version: openresty/1.21.4.1):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kworkbee** [comment]
@15810111831 I'm experiencing the same phenomenon. Have you done anything?

**Comment by kworkbee** [comment]
Hi, @membphis @moonming I'm experiencing the same thing right now, and it's having a significant impact on my business. This is especially noticeable when traffic is on the rise, and it seems to be resolved when the workload is scaled out when the log occurs, or when the pod is restarted when the log occurs. I'd appreciate it if you could take a closer look.
