### ISSUE TITLE
help request: routing based on request body parameters

### ISSUE THREAD

**Issue by gepardi** [apache/apisix#9275]
### Description

Hello
Is there a way to define routing based on request body parameters?

### Environment

- APISIX version: latest 3.2
- Operating system (run `uname -a`): latest
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): latest
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): latest
- APISIX Dashboard version, if relevant: latest
- Plugin runner version, for issues related to plugin runners: latest
- LuaRocks version, for installation issues (run `luarocks --version`): latest

**Comment by Sn0rt** [comment]
> body

can you provider a example of usage ?

**Comment by gepardi** [comment]
> 

Assume that the request body contains a field named username. We intend to route requests with usernames starting with 'apisix__' differently from those with usernames starting with 'other__'. One way to meet this requirement is to write a plugin. Is there another way?

**Comment by Sn0rt** [comment]
> > 
> 
> Assume that the request body contains a field named username. We intend to route requests with usernames starting with 'apisix__' differently from those with usernames starting with 'other__'. One way to meet this requirement is to write a plugin. Is there another way?

not support yet. howevert you can try to write self plugin for this feature . more info you can found from https://apisix.apache.org/zh/docs/apisix/next/plugins/ext-plugin-pre-req/

**Comment by gepardi** [comment]
> > > 
> > 
> > 
> > Assume that the request body contains a field named username. We intend to route requests with usernames starting with 'apisix__' differently from those with usernames starting with 'other__'. One way to meet this requirement is to write a plugin. Is there another way?
> 
> not support yet. howevert you can try to write self plugin for this feature . more info you can found from https://apisix.apache.org/zh/docs/apisix/next/plugins/ext-plugin-pre-req/

Thank you.
