### ISSUE TITLE
bug: not able to join apisix slack channel

### ISSUE THREAD

**Issue by kiranvpawar** [apache/apisix#9281]
### Current Behavior

I tried to join apisix slack channel using link - https://apisix.apache.org/slack

but not able to join, getting error as : "The email address must match one of the domains listed below. Please try another email."

I tried using office and personal email. please help.

![image](https://user-images.githubusercontent.com/5488201/230879289-ab8896dd-e25d-45d5-81e9-32196cfacfa6.png)

### Steps to Reproduce

I tried to join apisix slack channel using link - https://apisix.apache.org/slack

but not able to join, getting error as : "The email address must match one of the domains listed below. Please try another email."

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
please try https://join.slack.com/t/the-asf/shared_invite/zt-1ste27lth-KRjCr~O29U8aINsmEnpnjQ

**Comment by SiddheshKukade** [comment]
@moonming also doesn't works for me ![Screenshot_2023-04-14-15-28-26-149_com.Slack.jpg](https://user-images.githubusercontent.com/65951872/232013906-7a1180df-f261-417e-b757-9e20c4339748.jpg)

Kindly update the readme with the latest link. 👍

**Comment by juzhiyuan** [comment]
@SiddheshKukade Please use this one: https://join.slack.com/t/the-asf/shared_invite/zt-1ugrg37is-mFrbRqBEdpGWZ7_cuvvv0A

**Comment by shilingna** [comment]
I miss the same problem. How can I solve it

**Comment by malanverestack** [comment]
@juzhiyuan 

It still does not work with that link

![image](https://github.com/apache/apisix/assets/124132048/03ea7e2e-a828-4d20-98f6-65daf90d12e5)

**Comment by arjunbhut** [comment]
Hey @moonming , can you please invite me to join, would be a great help, here is my email : arjunbhut1@gmail.com

**Comment by moonming** [comment]
> Hey @moonming , can you please invite me to join, would be a great help, here is my email : [arjunbhut1@gmail.com](mailto:arjunbhut1@gmail.com)

Invitation sent

**Comment by robcxyz** [comment]
Hi @moonming - thank you for your help on this. Can you add me as well?

rob@sudoblock.io

Appreciate your help.

**Comment by moonming** [comment]
> Hi @moonming - thank you for your help on this. Can you add me as well?
> 
> [rob@sudoblock.io](mailto:rob@sudoblock.io)
> 
> Appreciate your help.

Invitation sent

**Comment by allenajd3** [comment]
Hi @moonming, I woluld like to join to slack channel too. Can you add me as well?
allen_ajd3@hotmail.com
Thanks

**Comment by Mehuls90** [comment]
Hi @moonming, I would like to join the slack channel as well. can you add me mehuls90@gmail.com 
Thanks

**Comment by its-akshay** [comment]
Hi @moonming , I want o join the slack channel, can you add me keswani014@gmail.com
Thanks

**Comment by yan-vine** [comment]
@moonming I would like to join slack channel, can you add me yusufeen@gmail.com thank you

**Comment by moonming** [comment]
> [@moonming](https://github.com/moonming) I would like to join slack channel, can you add me [yusufeen@gmail.com](mailto:yusufeen@gmail.com) thank you

Invited

**Comment by swapnil-omni** [comment]
[@moonming](https://github.com/moonming) I would like to join slack channel, can you add me [swapnil.raj@saisonomni.com] thank you

**Comment by moonming** [comment]
> [@moonming](https://github.com/moonming) I would like to join slack channel, can you add me [[swapnil.raj@saisonomni.com](mailto:swapnil.raj@saisonomni.com)] thank you

Invited
