### ISSUE TITLE
[help] Connecting APISIX to Amazon Managed Service for Prometheus

### ISSUE THREAD

**Issue by pthomaz** [apache/apisix#9282]
I'm confused on how I can send APISIX metrics to the remote address of AMP (Amazon Managed Service for Prometheus). Can someone help me?

Sorry if this is not the right place to ask for this help.

**Comment by soulbird** [comment]
Please refer to this article https://github.com/apache/apisix/blob/master/docs/en/latest/plugins/prometheus.md

**Comment by nic-6443** [comment]
Please note that the APISIX Prometheus plugin is based on the Pull model and cannot actively push metrics to remote services. It requires a remote Prometheus server to access its metric endpoint.

**Comment by pthomaz** [comment]
Thanks for the help guys!
