### ISSUE TITLE
help request: plugin [elasticsearch-logger] return error

### ISSUE THREAD

**Issue by coolboywcm** [apache/apisix#9283]
### Description

**route config:**
"plugins": {
    "elasticsearch-logger": {
      "_meta": {
        "disable": false
      },
      "endpoint_addr": "http://xxxx:xxxx",
      "field": {
        "index": "apisixlog"
      }
    }
  }

**tail -f /usr/local/apisix/logs/error.log**

 [error] 4391#4391: *126717034 [lua] batch-processor.lua:95: Batch Processor[elasticsearch-logger] failed to process entries: elasticsearch server returned status: 400, body: {"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: an id must be provided if version type or value are set;"},"status":400}, context: ngx.timer, client: xxx.xxx.xx.xx, server: 0.0.0.0:9080

ES version:**elasticsearch-7.3.0** 

**elasticsearch.yml** content:
action.auto_create_index: true
path.data: /data/elasticsearch
path.logs: /var/log/elasticsearch
cluster.name: docker-cluster
node.name: node-1
cluster.initial_master_nodes: ["node-1"]
network.host: 0.0.0.0
http.port: xxxx
http.cors.allow-origin: "*"
http.cors.enabled: true

### Environment

APISIX version (3.1.0):
Operating system (CentOS Linux release 7.6.1810):
OpenResty / Nginx version (nginx version: openresty/1.21.4.1):
etcd version, if relevant ("etcd_version":"3.4.0"):
APISIX Dashboard version, if relevant(3.0.0)

**Comment by nic-6443** [comment]
I found that version 7.17.1 (the version used in APISIX test cases) of Elasticsearch can work normally, so this problem may come from the difference in Elasticsearch versions. You can try to find the configuration document for version 7.3.0 of Elasticsearch and see if there is any relevant information.

**Comment by shreemaan-abhishek** [comment]
ping @coolboywcm
