### ISSUE TITLE
docs: populate default `log_format` for logging plugins

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9284]
Help Wanted. You should review **all log plugin** docs and update them.

### Current State

No default value:
![image](https://user-images.githubusercontent.com/39619599/231041236-81a1e5c6-806a-49e2-a751-fad1b71bb770.png)

For example: https://apisix.apache.org/docs/apisix/plugins/syslog

### Desired State

Populated the field with
`{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}`

**Comment by kayx23** [comment]
## info that might be useful

In `/apisix/utils/log-util.lua`: 

```
local _M = {}
_M.metadata_schema_log_format = {
    type = "object",
    default = {
        ["host"] = "$host",
        ["@timestamp"] = "$time_iso8601",
        ["client_ip"] = "$remote_addr",
    },
}
```

@soulbird mentioned the default format should be the same as the one available in metadata

**Comment by kayx23** [comment]
> Hey @kayx23 , do I have to put `{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}` in the `Default` field of `log_format`
> 
> Did I get it right?

That's correct. So far a lot of (if not most?) plugin docs with `log_format` do not provide a default value. 

The default value should be `{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}`, as seen in [my comment above](https://github.com/apache/apisix/issues/9284#issuecomment-1502611367)

**Comment by Arghyahub** [comment]
Okay @kayx23 , I'm fixing it🙂

**Comment by Arghyahub** [comment]
Do let me know If I didn't get something right and I will work on it
