### ISSUE TITLE
bug: consumer used wolf-rbac auth, consumer other plugins not used

### ISSUE THREAD

**Issue by lingliy** [apache/apisix#9287]
### Current Behavior

consumer used wolf-rbac auth, consumer other plugins ineffective

### Expected Behavior

consumer used wolf-rbac auth, consumer other plugins effect

Location:  /test_is_redirect

### Steps to Reproduce

1. create route
curl -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" "http://127.0.0.1:9180/apisix/admin/routes/1" -X PUT -d "{\"methods\": [\"GET\"],\"host\": \"example1.com\",\"uri\": \"/*\",\"upstream\": {\"type\": \"roundrobin\",\"nodes\": {\"127.0.0.1:80\": 1}}, \"plugins\":{\"wolf-rbac\":{}} }"

2. create consumer
curl http://127.0.0.1:9180/apisix/admin/consumers -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "username": "foo",
    "plugins": {
        "wolf-rbac":{"server":"http://192.168.216.128:12180","header_prefix":"X-", "appid": "test10"}, "redirect": {"uri": "/test_is_redirect", "ret_code": 301}
    }
}'

3. request
curl -v -H"Authorization: V1#test10#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiZm9vIiwibWFuYWdlciI6IiIsInZlcnNpb24iOjIsImFwcGlkIjoidGVzdDEwIiwiaWF0IjoxNjgxMTk2NjczLCJleHAiOjE2ODM3ODg2NzN9.9wvUFijW3rMRU6bcL9eQDvPpWYRqfswxQ3QCYb1VUY0" -H"Host: example1.com" http://127.0.0.1:9080/

4. Expected 
response header Location:

Location: /test_is_redirect

### Environment

- APISIX version (3.2.0):
- Operating system (Linux centos7-17 3.10.0-1160.45.1.el7.x86_64 #1 SMP Wed Oct 13 17:20:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux):
- OpenResty / Nginx version (nginx version: openresty/1.21.4.1
built by gcc 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) 
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DAPISIX_BASE_VER=1.21.4.1.7 -DNGX_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/usr/local/openresty/libgrpc_engine.so -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.33 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.09 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.21 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.9 --add-module=../ngx_stream_lua-0.0.11 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -Wl,-rpath,/usr/local/openresty/wasmtime-c-api/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../mod_dubbo-1.0.2 --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../ngx_multi_upstream_module-1.1.1 --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../apisix-nginx-module-1.12.0 --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/stream --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../apisix-nginx-module-1.12.0/src/meta --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../wasm-nginx-module-0.6.4 --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../lua-var-nginx-module-v0.5.3 --add-module=/tmp/tmp.xYfSxgSEeh/openresty-1.21.4.1/../grpc-client-nginx-module-v0.4.2 --with-poll_module --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module):
- etcd version, if relevant ({"id":"49f998e4-52dd-40b3-ad8d-0280dec80351","hostname":"centos7-17","boot_time":1681188802,"etcd_version":"3.4.0","version":"3.2.0"}):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (/usr/local/bin/luarocks 3.8.0
LuaRocks main command-line interface):

**Comment by nic-6443** [comment]
I can't understand your description. Why do you expect the returned Location header to be `/godis_route`? Isn't it configured as `/test_is_redirect` in your redirect plugin?

**Comment by lingliy** [comment]
I understand that once it passes wolf-rbac authentication, it will match foo in consumers. Since it is associated with consumer, then the redirect plugin under consumer should be effective, but the actual test will not be effective

**Comment by lingliy** [comment]
incorrect response
```
[root@centos7-17 apisix]# curl -v -H"Authorization: V1#test10#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiZm9vIiwibWFuYWdlciI6IiIsInZlcnNpb24iOjIsImFwcGlkIjoidGVzdDEwIiwiaWF0IjoxNjgxMTk2NjczLCJleHAiOjE2ODM3ODg2NzN9.9wvUFijW3rMRU6bcL9eQDvPpWYRqfswxQ3QCYb1VUY0" -H"Host: example1.com" http://127.0.0.1:9080/
* About to connect() to 127.0.0.1 port 9080 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 9080 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Accept: */*
> Authorization: V1#test10#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAsInVzZXJuYW1lIjoiZm9vIiwibWFuYWdlciI6IiIsInZlcnNpb24iOjIsImFwcGlkIjoidGVzdDEwIiwiaWF0IjoxNjgxMTk2NjczLCJleHAiOjE2ODM3ODg2NzN9.9wvUFijW3rMRU6bcL9eQDvPpWYRqfswxQ3QCYb1VUY0
> Host: example1.com
> 
< HTTP/1.1 200 OK
< Content-Type: text/html; charset=utf-8
< Content-Length: 51
< Connection: keep-alive
< X-UserId: 20
< X-Username: foo
< X-Nickname: testauth
< Date: Tue, 11 Apr 2023 07:21:00 GMT
< Last-Modified: Wed, 29 Mar 2023 03:36:13 GMT
< ETag: "6423b22d-33"
< Accept-Ranges: bytes
< Server: APISIX/3.2.0
< 
<html>
<body>
<h1>hello world</h1>
</body>
</html>
* Connection #0 to host 127.0.0.1 left intact
```

I have looked at the wolf-rbac plugins source code and found that consumer.attach_consumer  function was not used. Other auth type plugins use this function, so it is not actually associated with other plugins under the consumer. But since I am not that familiar with apisix and am not sure if this understanding is correct, I did this test and found that consumer used wolf-rbac auth, consumer other plugins not used

**Comment by nic-6443** [comment]
Thank you, you are right. The wolf-rbac plugin did indeed miss the `consumer.attach_consumer()`. 
Do you have an interest in fixing this bug?

**Comment by lingliy** [comment]
I am very happy to be part of the solution. I have not contributed commit to a well-known project before. many of the steps are unfamiliar,   first version has been submitted, https://github.com/apache/apisix/pull/9298/commits/dc46cb8616cdbb82f2d1d681106b5fb018c03498
