### ISSUE TITLE
bug: accessing introspection endpoint timeout when using openid-connect plugin 

### ISSUE THREAD

**Issue by arrowing** [apache/apisix#9288]
### Current Behavior

1、log in system by apisix (oidc connect plugin) and keycloak (bearea only)
2、request resource first
3、it always return status code 401
4、a moment later, i request resources again and again, there are return code 200 in 99% and a little return code 401 likes step 3.

### Expected Behavior

It always fine after i loged in the system and request resources.

### Error Logs

[lua] openidc.lua:502: call_token_endpoint(): accessing introspection endpoint (http://*/realms/*/protocol/openid-connect/token/introspect) failed: timeout, client: *, server: _, request: "GET / HTTP/1.1", host: "*", referrer: "*"

[lua] openid-connect.lua:275: phase_func(): OIDC introspection failed: accessing introspection endpoint (http://*/realms/*/protocol/openid-connect/token/introspect) failed: timeout, client: *, server: _, request: "GET / HTTP/1.1", host: "*", referrer: "*"

### Steps to Reproduce

as like Current Behavior

### Environment

- APISIX version (run `apisix version`): 2.14.1-alpine In Docker
- Operating system (run `uname -a`): Linux 3.10.0-693.2.2.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by nic-6443** [comment]
The meaning of this log is that when Apisix requested Keycloak, a timeout error occurred. Is it possible that your Keycloak service occasionally experiences request timeouts? You can try using tcpdump to record the network requests between Apisix and Keycloak to see if you can find these timed-out requests. Then look for the reason for the timeout in the Keycloak logs.
