### ISSUE TITLE
How to use the request-id plugin to add multiple headers

### ISSUE THREAD

**Issue by liuwenzhi0318** [apache/apisix#9292]
### Current Behavior

在请求接口时，需要增加多个 header 头。

### Steps to Reproduce

{
  "_meta": {
    "disable": false
  },
  "algorithm": "uuid",
  "header_name": "X-B3-TraceId",
  "include_in_response": true
}

### Environment

![image](https://user-images.githubusercontent.com/37536326/231367729-04ff7314-92fa-4d46-981d-41c390602c44.png)

**Comment by liuwenzhi0318** [comment]
I understand the proxy-rewrite plugin, how to deal with the value of the newly added header as a uuid or request-id plugin like ["uuid", "snowflake", "nanoid", "range_id"]

**Comment by Sn0rt** [comment]
> how to deal with the value of the newly added header as a uuid or request-id plugin like ["uuid", "snowflake", "nanoid", "range_id"]

you try to describe issues in Chinese.  I can't understand this expression.

**Comment by Sn0rt** [comment]
Are want to add a new algorithm for id generation ?

**Comment by liuwenzhi0318** [comment]
proxy-rewrite 插件我有了解，这个插件的怎么处理新增的 header的 value 值为一个 uuid 或者 request-id 插件类似那样的["uuid", "snowflake", "nanoid", "range_id"] 一个变量。 目前官网示例显示的是一个 str
![image](https://user-images.githubusercontent.com/37536326/231417484-d876aae7-257d-4bd3-80b3-9d10c72f6601.png)

**Comment by liuwenzhi0318** [comment]
我想实现 request-id 一样的功能，只是需要增加多个 header

**Comment by leslie-tsang** [comment]
Please use english in public channel.

**Comment by leslie-tsang** [comment]
> 我想实现 request-id 一样的功能，只是需要增加多个 header，并且value 是以类似uuid 随机生成的

It sounds meaningless, the `request id` should be unique.

**Comment by liuwenzhi0318** [comment]
request-id is just a plugin name, and the plugin name can also be a header, I just need a function like this. I just need to automatically add my custom header after the external request or user request access to the apisix gateway

**Comment by liuwenzhi0318** [comment]
similar   nginx  proxy_set_header

**Comment by liuwenzhi0318** [comment]
Nginx is converted to apisix to use the actual operation method of the plug-in. This is just one of the headers, and multiple classes can also be configured in this way
```
location / {
    proxy_pass http://upstream;
    set $req_id $pid.$msec.$remote_addr.$connection.$connection_requests;
    proxy_set_header X-Request-Id $req_id;
}
```

**Comment by leslie-tsang** [comment]
Maybe you could try adding a custom plugin to [register a var](https://apisix.apache.org/docs/apisix/plugin-develop/#register-custom-variable), and then reference that var in other plugins.

**Comment by Sn0rt** [comment]
agree wtih leslie-tsang

to convert the ngx config file as follow.

```lua
location / {
    content_by_lua_block {
        local http = require "resty.http"
        local httpc = http.new()
        local res, err = httpc:request_uri("http://upstream")

        if not res then
            ngx.say("failed to request: ", err)
            return
        end

        local req_id = ngx.var.pid .. "." .. ngx.var.msec .. "." .. ngx.var.remote_addr .. "." .. ngx.var.connection .. "." .. ngx.var.connection_requests
        ngx.req.set_header("X-Request-Id", req_id)

        ngx.say(res.body)
    }
}

```

**Comment by liuwenzhi0318** [comment]
I hope that the official add header plug-in can realize this function. I think this function will be very practical.

Compared with the request-id plugin, the code is similar to this

`"plugins": [
 {
    "_meta": {
      "disable": false
    },
    "algorithm": "uuid",
    "header_name": "X-A-A",
    "include_in_response": true
  },
  {
    "_meta": {
      "disable": false
    },
    "algorithm": "uuid",
    "header_name": "X-B-B",
    "include_in_response": true
  }
]`

**Comment by liuwenzhi0318** [comment]
or   ![image](https://user-images.githubusercontent.com/37536326/231426533-30efd934-f192-4b18-bfa3-d0749a847396.png)

**Comment by Sn0rt** [comment]
> I hope that the official add header plug-in can realize this function. I think this function will be very practical.
> 
> Compared with the request-id plugin, the code is similar to this
> 
> ```
> "plugins": {
> "header":[
>    {
>       "algorithm": "uuid",
>       "header_name": "X-A-A",
>       "include_in_response": true
>     },
>   {
>     "algorithm": "uuid",
>     "header_name": "X-B-B",
>     "include_in_response": true
>   }
> ]
> }
> ```

This is very clear, I can understand it.
You need two custom headers, whose value is automatically generated by the plugin (request-id).
Your scenario may be that different components consume different http headers.

Am I right?

**Comment by liuwenzhi0318** [comment]
no. I need to set 2-3 headers in the same request

**Comment by liuwenzhi0318** [comment]
Yes

**Comment by Sn0rt** [comment]
current the `request-id` not support this usage.
however I think it's useful feature. we welcome you to implement this feature based on request-id plugin.

@leslie-tsang cc

**Comment by jiangfucheng** [comment]
@Sn0rt @leslie-tsang Hi, I want to try implement this feature, could assign it to me?

**Comment by soulbird** [comment]
I disagree, this feature is not generic, you can implement it in your own plugin. Or we can also see if more people want this feature

**Comment by leslie-tsang** [comment]
> @Sn0rt @leslie-tsang Hi, I want to try implement this feature, could assign it to me?

First of All, thanks for your self-recommendation. :)

Unfortunately, there is no such a scenario that would convince me to implement this feature in the open source APISIX.

**Comment by liuwenzhi0318** [comment]
thank you all;
I have this consideration: If the function of this plug-in is used as a general plug-in, it will be a great enhancement to the function of grayscale release. Canary release can't just be done through the official traffic ratio, but more canary release through custom headers.
