### ISSUE TITLE
help request: How use the [http-logger] plugin to retrieve both the 'route_name' and 'rep_body' in the log content

### ISSUE THREAD

**Issue by coolboywcm** [apache/apisix#9295]
### Description

How can I use the [http-logger] plugin to retrieve both the **route_name** and **rep_body** in the log content for a specific route without affecting the logging of other routes? I know that the **$route_name** variable can be used to retrieve the route name from the meta property of the [http-logger[ plugin, but this is a global configuration. Is it possible to retrieve the route_name within the http-logger plugin for a specific route only?

my [http-logger] plugin content:
"http-logger": {
      "_meta": {
        "disable": false
      },
      "concat_method": "new_line",
      "include_req_body": true,
      "include_resp_body": true,
      "uri": "http://xxxxxxx/apisix/addLog"
    }

### Environment

APISIX version (3.1.0):
Operating system (CentOS Linux release 7.6.1810):
OpenResty / Nginx version (nginx version: openresty/1.21.4.1):
etcd version, if relevant ("etcd_version":"3.4.0"):
APISIX Dashboard version, if relevant(3.0.0)

**Comment by nic-6443** [comment]
In the latest version of APISIX, [http-logger](https://apisix.apache.org/docs/apisix/plugins/http-logger/) supports configuring `log-format` at the plugin level. You can give it a try.

**Comment by shreemaan-abhishek** [comment]
you can register a custom variable and store the name of the route using serverless plugin:

https://docs.api7.ai/apisix/reference/built-in-variables#method-2-in-the-serverless-plugins

**Comment by shreemaan-abhishek** [comment]
Do you have any other questions?
