### ISSUE TITLE
help request: apisix + keycloak  using reatfull service 400 – Bad Request

### ISSUE THREAD

**Issue by robertluoxu** [apache/apisix#9297]
### Description

使用使用openid-connect 连接keycloak做认证，使用官方httpbin.org 站点测试一切正常，当切换至自有的restfull 服务时，出现400错误，请帮助我！
如下时apisix 中路由配置
![image](https://user-images.githubusercontent.com/52069259/231640088-5c7236ca-2d28-4cee-8a30-644c8a5f69d3.png)

问题情况：
![image](https://user-images.githubusercontent.com/52069259/231640211-c88e9db4-8135-46cc-9e2b-00b6b29b6d6b.png)

### Environment

- APISIX version (run `apisix version`): 2.15.0-centos
- Operating system (run `uname -a`): root
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by nic-6443** [comment]
This 400 Bad Request is returned by your upstream service (apparently a Tomcat service), you should check your upstream service instead of APISIX.

**Comment by robertluoxu** [comment]
感谢，确实如您所说，发现header太长而后端服务未设置header大小导致
