### ISSUE TITLE
help request: dynamically add management users to apisix-dashboard

### ISSUE THREAD

**Issue by coolboywcm** [apache/apisix#9300]
### Description

How to dynamically add management users to Apisix-dashboard, current management users are configured in /apisix/dashboard/confconf.yaml, I need to synchronize user data with another system. Is there an open API available for user data management?

### Environment

APISIX version (3.1.0):
Operating system (CentOS Linux release 7.6.1810):
OpenResty / Nginx version (nginx version: openresty/1.21.4.1):
etcd version, if relevant ("etcd_version":"3.4.0"):
APISIX Dashboard version, if relevant(3.0.0)

**Comment by nic-6443** [comment]
Please do not create duplicate issues. You have already created:
https://github.com/apache/apisix-dashboard/issues/2787
https://github.com/apache/apisix-dashboard/issues/2788
This is an issue related to the apisix-dashboard project, so you should track it in issues of the apisix-dashboard project.

**Comment by coolboywcm** [comment]
> Please do not create duplicate issues. You have already created: [apache/apisix-dashboard#2787](https://github.com/apache/apisix-dashboard/issues/2787) [apache/apisix-dashboard#2788](https://github.com/apache/apisix-dashboard/issues/2788) This is an issue related to the apisix-dashboard project, so you should track it in issues of the apisix-dashboard project.

Sorry!At the beginning, I was not sure whether the question was related to apisix-dashboard or apisix project. As I was in a hurry, I posted the question in both places. close this issue.

**Comment by nic-6443** [comment]
@coolboywcm No worries, it's okay.
