### ISSUE TITLE
docs: Wrong URL specified on "Expose API" page while testing.

### ISSUE THREAD

**Issue by Revolyssup** [apache/apisix#9304]
### Current State

On this [page](https://github.com/apache/apisix/blob/master/docs/en/latest/tutorials/expose-api.md), the `uri` to match is specified as `/anything/*` but the request is sent on `/get?foo1=bar1&foo2=bar2` which returns `404: route not found` as the route was defined for `/anything/*`

![Screenshot 2023-04-13 at 3 19 20 PM](https://user-images.githubusercontent.com/43276904/231722478-b2c89b9c-198b-4d6a-98cc-47910522a927.png)

### Desired State

According to the last comment `APISIX will forward the request to http://httpbin.org:80/anything/foo?arg=10` and the route config, the command should be changed to:
`curl -i -X GET "http://127.0.0.1:9080/anything/foo?arg=10" -H "Host: example.com"`
![Screenshot 2023-04-13 at 3 21 12 PM](https://user-images.githubusercontent.com/43276904/231722985-f50fa10c-f58a-4540-bc5b-2dcf614df69c.png)

**Comment by Revolyssup** [comment]
Can I take this up? Given that its a small issue and straightforward fix.

**Comment by nic-6443** [comment]
Will be fixed in: https://github.com/apache/apisix/pull/8730
