### ISSUE TITLE
feat: support for the Timing-Allow-Origin header in CORS plugin

### ISSUE THREAD

**Issue by skimdz86** [apache/apisix#9307]
### Description

When using the CORS plugin, I'd like to be able to set also the Timing-Allow-Origin header (https://www.w3.org/TR/resource-timing/#sec-timing-allow-origin).

The plugin configuration for this header should be separate from the one dedicated to the Access-Control-Allow-Origin header (so I should be able to set 2 different allowed values for these headers).
I'm not completely sure about the need of this separation in the real world, but a possible use case could be: 
- I set Access-Control-Allow-Origin: *
- I restrict the domains that can see the timings setting Timing-Allow-Origin: https://my-specific-domain.com

The plugin configuration should have 2 fields to configure the Timing-Allow-Origin header, similarly to Access-Control-Allow-Origin: a field for accepting a single value "timing_allow_origin", and a field "timing_allow_origin_by_regex" to match different possible origins.

I think that the new header should be set in response by the plugin only if the user choose to configure it in the CORS plugin configuration, also given the fact that setting the value * (wildcard) may be considered insecure (see discussion https://github.com/w3c/resource-timing/issues/222) and so we can not set it as default.

If you agree on the issue, I would like to try implementing this feature

**Comment by monkeyDluffy6017** [comment]
Ok, the `Timing-Allow-Origin` is part of the Cross-Origin Resource Sharing (CORS) mechanism

**Comment by skimdz86** [comment]
Hi @monkeyDluffy6017 ,
the Timing-Allow-Origin header is defined in the Resource Timing API, but it seems strictly related to che CORS concepts in my opinion.

In fact, it is a sort of policy about the resource sharing, but in this case information we share is the timing information.
If we see [here](https://developer.mozilla.org/en-US/docs/Web/API/Performance_API/Resource_timing#cross-origin_timing_information) the header allows to return the timing properties on a resource under CORS policies.

Imagine that we have 2 domains, x.com and y.com.
From a page on x.com, we can allow the browser to show the resource timing information about a resource on y.com only if we can invoke URLs on y.com; so we have to set the CORS header first, access the y.com URL (with an XHR), and if we have also set the Timing-Allow-Origin the browser will be able to show the timing info of the resource on y.com.

What do you think?

**Comment by monkeyDluffy6017** [comment]
OK, i get it. It's an enhancement feature. Could you explain it in the doc in more detail? 

```
From a page on x.com, we can allow the browser to show the resource timing information about a resource on y.com only if we can invoke URLs on y.com; so we have to set the CORS header first, access the y.com URL (with an XHR), and if we have also set the Timing-Allow-Origin the browser will be able to show the timing info of the resource on y.com

```

**Comment by skimdz86** [comment]
Ok, I'll update the documentation in the next few days, thanks

**Comment by Sn0rt** [comment]
> Ok, I'll update the documentation in the next few days, thanks

do you have update for document ?

**Comment by skimdz86** [comment]
> > Ok, I'll update the documentation in the next few days, thanks
> 
> do you have update for document ?

Hi, actually I already updated the documentation in this commit https://github.com/apache/apisix/pull/9365/commits/bb98891c6454c8236dfda6fb833feac36df56bc6

Please let me know if everything is ok!

Thank
