### ISSUE TITLE
Health check error

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9308]
### Current Behavior

The active health check continued when I closed a route，On the route is the bound service

### Expected Behavior

The route is closed, and the health check stops

### Error Logs

After the route is disabled, the health check log continues

### Steps to Reproduce

1.Configure upstream

`{
    "id": "455751713836499648",
    "create_time": 1681178790,
    "update_time": 1681438064,
    "nodes": [
        {
            "host": "10.4.16.12",
            "port": 443,
            "weight": 1
        },
        {
            "host": "192.168.39.96",
            "port": 443,
            "weight": 1
        }
    ],
    "retries": 1,
    "timeout": {
        "connect": 6,
        "send": 6,
        "read": 6
    },
    "type": "roundrobin",
    "checks": {
        "active": {
            "concurrency": 10,
            "healthy": {
                "http_statuses": [
                    302
                ],
                "interval": 2,
                "successes": 10
            },
            "host": "10.4.16.12",
            "http_path": "/",
            "https_verify_certificate": false,
            "port": 443,
            "timeout": 1,
            "type": "http",
            "unhealthy": {
                "http_failures": 10,
                "http_statuses": [
                    429
                ],
                "interval": 2,
                "tcp_failures": 10,
                "timeouts": 10
            }
        }
    },
    "scheme": "http",
    "pass_host": "pass",
    "name": "健康检查测试后端",
    "desc": "健康检查测试后端",
    "keepalive_pool": {
        "idle_timeout": 60,
        "requests": 1000,
        "size": 320
    },
    "retry_timeout": 1
}`

2.Configuration service

`{
    "id": "456184583122059968",
    "create_time": 1681436800,
    "update_time": 1681436800,
    "name": "健康检查服务",
    "upstream_id": "455751713836499648"
}`

3.configuration route 
`{
    "id": "456185170559500992",
    "create_time": 1681437150,
    "update_time": 1681438375,
    "uri": "/test456/*",
    "name": "healthtest2",
    "desc": "healthtest1-绑定服务",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS",
        "CONNECT",
        "TRACE"
    ],
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": [
                "^/test456(/|$)(.*)",
                "/$2"
            ]
        }
    },
    "service_id": "456184583122059968",
    "status": 1
}`

ps：When I do not bind the service, but configure the upstream on the route alone, the health check stops normally

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by nic-6443** [comment]
I think this is expected because upstream is referenced by service, not directly by route. Therefore, the status change of route should not affect upstream. 
If there are other routes using this upsream through serverice at this time, you would obviously want the health check of upstream to work normally.

**Comment by thor533** [comment]
> I think this is expected because upstream is referenced by service, not directly by route. Therefore, the status change of route should not affect upstream. If there are other routes using this upsream through serverice at this time, you would obviously want the health check of upstream to work normally.

okey, i got it,thank you reply, which, based on your explanation, makes sense!

**Comment by thor533** [comment]
> I think this is expected because upstream is referenced by service, not directly by route. Therefore, the status change of route should not affect upstream. If there are other routes using this upsream through serverice at this time, you would obviously want the health check of upstream to work normally.

In addition, I have one last question about the health check. I think the interval of the health check of apisix is not accurate. If you have a look at my configuration and this log, it does not correspond at all !
![图片](https://user-images.githubusercontent.com/62246176/231963195-07c2b04f-64c0-446f-9d0a-ab0bdb33907f.png)

my interface log is :
![图片](https://user-images.githubusercontent.com/62246176/231963822-868536a5-484c-4946-8757-3d862ccf2268.png)

**Comment by thor533** [comment]
> I think this is expected because upstream is referenced by service, not directly by route. Therefore, the status change of route should not affect upstream. If there are other routes using this upsream through serverice at this time, you would obviously want the health check of upstream to work normally.

I am studying and investigating whether apisix can replace our internal api gateway,thanks!
