### ISSUE TITLE
request help: jwt体验疑惑，如何与crm关联使用？

### ISSUE THREAD

**Issue by jiezaizone** [apache/apisix#931]
### Issue description
1、jwt使用参数形式访问，url如下，
http://192.168.4.122:8080/\#/message\?jwt\=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJrZXkiOiJpc3V3YW5nIiwiZXhwIjoxNTc1NDY3NzcxfQ.rGhdOPZtvcDpySebT3NxecSTd30gAzqfKu46IpkCSs0zLxv2qcZacplsRx-HT3Yu5hRtxaKGl0nIcsw5J_Y2Kw
地址可以通过授权访问，单刷新后会出现{"message":"Missing JWT token in request"} 情况，重新打开又能访问，再刷新又被拒绝
2、jwt需要手动创建Consumers，如何与自己的crm关联？是否有demo介绍
3、配置jwt，在没有授权情况下直接返回{"message":"Missing JWT token in request"}，如何能够在401返回后进行一些操作，比如跳转到授权页面？

### Environment

* apisix version (cmd: `apisix version`):
* OS:Docker ：tinywan-api-gateway、etcd-server

**Comment by moonming** [comment]
@jiezaizone can you give the reproduce steps by curl, not the browser?
And is there has error msg in Nginx's log file?

**Comment by moonming** [comment]
https://github.com/apache/incubator-apisix/blob/master/doc/plugins/jwt-auth.md#how-to-enable is the document for jwt and consumer

**Comment by spacewander** [comment]
Close as lack of reply from the author
