### ISSUE TITLE
The interval time is not accurate

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9310]
### Description

In addition, I have one last question about the health check. I think the interval of the health check of apisix is not accurate. If you have a look at my configuration and this log, it does not correspond at all !
![图片](https://user-images.githubusercontent.com/62246176/231990205-99535019-4200-4b3e-9282-8a52d10b0f2d.png)

my interface log is :
![图片](https://user-images.githubusercontent.com/62246176/231990296-6ad92d5d-0a6f-4463-a945-3eebdecfa10e.png)

### Environment

- APISIX version (run `apisix :2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
What's wrong? I can see the health check happening every 2 seconds just as configured. Could you please explain what am I missing? Sorry for the hassle.

**Comment by thor533** [comment]
> What's wrong? I can see the health check happening every 2 seconds just as configured. Could you please explain what am I missing? Sorry for the hassle.

The status code of the active health check I set is 302, but my interface returns 200. Normally, according to the configuration, first of all, the active health check should be performed 5 times, each time for 2 seconds. Then, it should start to excute the unhealthy configuration should be performed 5 times, with an interval of 5 seconds. Is that right? I don't know if my understanding is correct, please help me correct, thank you very much for your reply

**Comment by thor533** [comment]
> What's wrong? I can see the health check happening every 2 seconds just as configured. Could you please explain what am I missing? Sorry for the hassle.

Excuse me, could you help me with this？ thanks

**Comment by shreemaan-abhishek** [comment]
@thor533, I could better help you if you could add the screenshot with English text in the issue description. I do not understand Chinese. 😅

**Comment by thor533** [comment]
> @thor533, I could better help you if you could add the screenshot with English text in the issue description. I do not understand Chinese. 😅

sir,thank your reply ,and you can see here:
![图片](https://user-images.githubusercontent.com/62246176/232750243-d816dbc9-15f6-4c80-9df1-5b930d8965a4.png)

This interval really confused me. I don't know what kind of logic it is, which is very different from what I understand.
Looking forward to your reply! thanks

**Comment by shreemaan-abhishek** [comment]
It depends on whether you are talking about [active check](https://apisix.apache.org/zh/docs/apisix/tutorials/health-check/#%E4%B8%BB%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5) or [passive check](https://apisix.apache.org/zh/docs/apisix/tutorials/health-check/#%E8%A2%AB%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5).

The configuration that you currently have means that the health check will be done every 2 seconds, and if there are 5 successes the node will be marked as healthy. Also, if the upstream node returns 302, it will be marked as healthy.

For unhealthy nodes, it will check every the health check will be done every 5 seconds. If the upstream node returns error code: 429, the upstream node will be marked as unhealthy.

**Comment by thor533** [comment]
> It depends on whether you are talking about [active check](https://apisix.apache.org/zh/docs/apisix/tutorials/health-check/#%E4%B8%BB%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5) or [passive check](https://apisix.apache.org/zh/docs/apisix/tutorials/health-check/#%E8%A2%AB%E5%8A%A8%E5%81%A5%E5%BA%B7%E6%A3%80%E6%9F%A5).
> 
> The configuration that you currently have means that the health check will be done every 2 seconds, and if there are 5 successes the node will be marked as healthy. Also, if the upstream node returns 302, it will be marked as healthy.
> 
> For unhealthy nodes, it will check every the health check will be done every 5 seconds. If the upstream node returns error code: 429, the upstream node will be marked as unhealthy.

I'm talking about active checking, my configuration above, first of all, the first time it should  run the health status, it run it every two seconds,and  he need to run  five times, but the interface returns 200, not 302, on the sixth time, should it  run the unhealthy configuration? it run every 5 seconds, and it return the status code 200, not 429, So it should be executed five times, right? But the test results, they don't match my understanding

**Comment by soulbird** [comment]
same as #9327
