### ISSUE TITLE
bug: Can not edit resource and method when soap transforms rest 

### ISSUE THREAD

**Issue by NahidAfzali** [apache/apisix#9315]
### Current Behavior

Hi,
when I transform soap API to rest, a request parameter whose type is base64Binary doesn't add to the parameters. I found the problem and edit the API definition. But the main problem is that the resources do not change and because of this bug, the request doesn't send the base64Binary parameter. Please help me with this bug or mistake.

### Error Logs

the request doesn't send the base64Binary parameter

### Steps to Reproduce

SOAP API
Import WSDL
.
.
.
API configuration/Resources/edit API parameters
test from the devportal

### Environment

WSO2 AM

**Comment by kingluo** [comment]
@NahidAfzali Which apisix version do you test? Could you clarify your question more?

**Comment by Sn0rt** [comment]
@NahidAfzali wait for your update. if I not get you reply  I will close this issue after one week.
