### ISSUE TITLE
bug: something wrong with casbin

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#9317]
**### Current Behavior**

I want to use proxy rewrite to write consumer group information to the header, and then use casbin to confirm permissions. Upstream users can also obtain header information。
I added the header as the ID of the consumer group using proxy rewrite, and verified the header using casbin. Surprisingly, the header. add implemented my idea, but the header. set failed

**### Steps to Reproduce**

**create 1 upstream**

```
{
    "create_time": 1678944046,
    "scheme": "http",
    "name": "web1",
    "pass_host": "pass",
    "update_time": 1678944740,
    "id": "452002436731634371",
    "desc": "web1",
    "type": "roundrobin",
    "timeout": {
        "send": 6,
        "read": 6,
        "connect": 6
    },
    "nodes": {
        "web1:80": 1
    },
    "keepalive_pool": {
        "size": 320,
        "idle_timeout": 60,
        "requests": 1000
    }
}

```

**create 1 consumer_groups :**

```
PUT /apisix/admin/consumer_groups/2080
{
   "plugins": {
    }
}
```
**create 1 consumer:**
```

{
    "username": "jack",
    "plugins": {
        "key-auth": {
            "key": "QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT"
        }
    },
    "group_id":"2080"
}
```
**create 1 router:**

```
{
  "name": "web1-rewrite",
  "status": 1,
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "priority": 0,
  "labels": {},
  "uri": "/web1/*",
  "plugins": {
       
        "proxy-rewrite": {
            "_meta": {
            	"priority": 1
        	},
            "headers": {
                "set": {
                    "tenant": "$consumer_group_id"
                }
            }
        },
         "key-auth": {
            "_meta": {
            	"priority": 2
        	}
        },
        "authz-casbin": {
            "_meta": {
            	"priority": 0
        	},
            "model": "[request_definition]
            r = sub, obj, act

            [policy_definition]
            p = sub, obj, act

            [role_definition]
            g = _, _

            [policy_effect]
            e = some(where (p.eft == allow))

            [matchers]
            m = (g(r.sub, p.sub) || keyMatch(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)",

            "policy": "p, *, web1, GET
            p, admin, *, *
            g, 2080, admin",

            "username": "tenant"
        }
    },
  "upstream_id": "452002436731634371"
}
```

**access :**

```
POST /web1/ HTTP/1.1
HEADER
apikey: QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT

{"message":"Access Denied"}

```

**### Expected Behavior**

```
POST /web1/ HTTP/1.1
HEADER
apikey: QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT

hello web1
```

### Error Logs

no error

### Environment

- APISIX version (run `apisix version`):3.2.0
use https://apisix.apache.org/zh/docs/apisix/installation-guide/
docker-compose -p docker-apisix up -d

system :WIN10 docker desktop

**Comment by tao12345666333** [comment]
Please format your issue contents, thanks.

**Comment by cverdela** [comment]
@tao12345666333  sorry，like this？

**Comment by cverdela** [comment]
Additional instructions：
when I changed like this   set->add
```
"proxy-rewrite": {
            "_meta": {
            	"priority": 1
        	},
            "headers": {
                "add": {
                    "tenant": "$consumer_group_id"
                }
            }
        },
```

It meets expectations

**Comment by tao12345666333** [comment]
hi, @cverdela `headers.add` will append the header, while `headers.set` will overwrite it.

https://github.com/apache/apisix/issues/9317#issuecomment-1514050071 It seems that your problem has already been resolved.

**Comment by cverdela** [comment]
hi, @tao12345666333 ,not resolved
If header is not exist, headers.set will add it.

**Comment by cverdela** [comment]
To avoid consumers adding this header header themselves, I would prefer to use set instead of add

**Comment by cverdela** [comment]
![image](https://user-images.githubusercontent.com/21302251/233288900-b38c99b2-a046-4d06-9d20-e5210f85562b.png)

**Comment by tao12345666333** [comment]
Can you provide its complete request and response headers?

Use `set`, `add`, or don‘t use this method separately.

**Comment by cverdela** [comment]
#set#

POST /web1/ HTTP/1.1
HEADER
apikey: QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT

{"message":"Access Denied"}


POST /web1/ HTTP/1.1
HEADER
apikey: 192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf

{"message":"Access Denied"}

#add#

POST /web1/ HTTP/1.1
HEADER
apikey: QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT

hello web1


POST /web1/ HTTP/1.1
HEADER
apikey: 192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf

{"message":"Access Denied"}

**Comment by tao12345666333** [comment]
Is this your current actual test result? From here, it appears that 'set' and 'add' have the same value. Therefore, they should produce the same outcome.

**Comment by cverdela** [comment]
my current actual test result
All steps can be replicated at the top

**Comment by cverdela** [comment]
### Steps to Reproduce

create two consumer_groups :

PUT /apisix/admin/consumer_groups/1000
{
   "plugins": {
    }
}
PUT /apisix/admin/consumer_groups/2080
{
   "plugins": {
    }
}
create two consumer:

{
    "username": "tom",
    "plugins": {
        "key-auth": {
            "key": "192b9bdd22ab9ed4d12e236c78afcb9a393ec15f71bbf5dc987d54727823bcbf"
        }
    },
    "group_id":"1000"
}

{
    "username": "jack",
    "plugins": {
        "key-auth": {
            "key": "QinPGTd7Ulec03lar0vkI9ojqmXsuw4VOyirnC5NuvEdJSCwLwesmknNygXITunT"
        }
    },
    "group_id":"2080"
}
create 1 router:

{
  "name": "web1-rewrite",
  "status": 1,
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "priority": 0,
  "labels": {},
  "uri": "/web1/*",
  "plugins": {
       
        "proxy-rewrite": {
            "_meta": {
            	"priority": 1
        	},
            "headers": {
                "set": {
                    "tenant": "$consumer_group_id"
                }
            }
        },
         "key-auth": {
            "_meta": {
            	"priority": 2
        	}
        },
        "authz-casbin": {
            "_meta": {
            	"priority": 0
        	},
            "model": "[request_definition]
            r = sub, obj, act

            [policy_definition]
            p = sub, obj, act

            [role_definition]
            g = _, _

            [policy_effect]
            e = some(where (p.eft == allow))

            [matchers]
            m = (g(r.sub, p.sub) || keyMatch(r.sub, p.sub)) && keyMatch(r.obj, p.obj) && keyMatch(r.act, p.act)",

            "policy": "p, *, web1, GET
            p, admin, *, *
            g, 2080, admin",

            "username": "tenant"
        }
    },
  "upstream_id": "452002436731634371"
}

**Comment by tao12345666333** [comment]
Is there any configuration for Casbin?

**Comment by tao12345666333** [comment]
Can you provide the complete steps to reproduce? Thank you.

**Comment by cverdela** [comment]
https://github.com/apache/apisix/issues/9317#issuecomment-1515889396
complete steps

**Comment by cverdela** [comment]
> Is there any configuration for Casbin?

no other configuration

**Comment by cverdela** [comment]
> @cverdela Did you directly use the Casbin server's Docker image? In order to reproduce more efficiently, could you provide a minimal reproduction step including the part of Casbin? Thank you.

I haven't tried yet, I'm currently designing a solution

**Comment by tao12345666333** [comment]
So how did you get your test results now? 
Simply using the information you provided above is not enough to fully reproduce this issue.

**Comment by cverdela** [comment]
> 

？
I use this
![image](https://user-images.githubusercontent.com/21302251/233514106-cfd5000c-7d8e-4c90-8f34-a9d69816e6f1.png)

**Comment by cverdela** [comment]
What information is insufficient to fully reproduce this problem.
that‘s all my steps’

**Comment by cverdela** [comment]
![image](https://user-images.githubusercontent.com/21302251/233514578-6e95c2e4-7070-4759-a0f0-6bf934905232.png)
 the configuration for Casbin is in the configuration of router

**Comment by tao12345666333** [comment]
> > @cverdela Did you directly use the Casbin server's Docker image? In order to reproduce more efficiently, could you provide a minimal reproduction step including the part of Casbin? Thank you.
> 
> 
> 
> I haven't tried yet, I'm currently designing a solution

In the steps you provided only include the configuration in APISIX.  Does not contain Casbin server or application related configuration.

**Comment by cverdela** [comment]
no Casbin server

**Comment by cverdela** [comment]
the configuration for Casbin is in the configuration of router

**Comment by tao12345666333** [comment]
In simple terms, what is your upstream? What configuration does it contain?

**Comment by cverdela** [comment]
https://apisix.apache.org/docs/apisix/installation-guide/
This is the environment you provided, with two upstreams, web1 and web2

**Comment by cverdela** [comment]
sorry 
upsteam
`{"id":"452002436731634371","create_time":1678944046,"update_time":1678944740,"nodes":{"web1:80":1},"timeout":{"connect":6,"send":6,"read":6},"type":"roundrobin","scheme":"http","pass_host":"pass","name":"web1","desc":"web1","keepalive_pool":{"idle_timeout":60,"requests":1000,"size":320}}`

**Comment by cverdela** [comment]
This was created through the management console, I forgot it

**Comment by cverdela** [comment]
now everything is in https://github.com/apache/apisix/issues/9317#issue-1670283656
I deleted the etcd data file and redo it again

**Comment by tao12345666333** [comment]
I can confirm this issue.

**Comment by cverdela** [comment]
thanks

**Comment by tao12345666333** [comment]
I need to dig into the code to do some checks

**Comment by cverdela** [comment]
Where can I see the main code design of Apisix

**Comment by tao12345666333** [comment]
FYI: https://github.com/apache/apisix/blob/1434335041c6e054f7b6afb0401aea0a069b0ad7/apisix/plugins/proxy-rewrite.lua#L232-L259

@cverdela

**Comment by tao12345666333** [comment]
@cverdela  APISIX v3.3. has been released. https://github.com/apache/apisix/releases/tag/3.3.0


I have verified that this issue has been fixed.  I will close this one. Thanks for your report.



If you have any follow-up comments regarding this issue, please continue to add comments.
