### ISSUE TITLE
radixtree.new cost nearly 120s when uri_routes num is 10w 

### ISSUE THREAD

**Issue by xiewenhui** [apache/apisix#9320]
### Description

hi  api7team,
I tested and found radixtree.new()  cost nearly 120s when uri_routes num is 10w   (32core, 32G,  centos Physical Machine server)， 
I use radixtree_uri_with_parameter for http router.
do you have any optimize suggestions?

### Environment

- APISIX version (run `apisix version`):  2.15
- Operating system (run `uname -a`):  centos 6.8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):   1.21.4.1

**Comment by tao12345666333** [comment]
How did you conduct the testing?

**Comment by Revolyssup** [comment]
@xiewenhui Any updates?
