### ISSUE TITLE
request has no response when using a customized openresty

### ISSUE THREAD

**Issue by liugang594** [apache/apisix#9321]
### Description

I built an apisix based on a customized openresty, then when I send a request, request is stuck and no response.

could you give some hints?

Thanks!

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Hey please share some more information. Like error logs, and route configuration. I would also recommend making multiple tries.

**Comment by tao12345666333** [comment]
APISIX uses its own unique apisix-base. If you replace it, it may cause some unexpected situations.
