### ISSUE TITLE
least-conn is incorrect

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9323]
### Description

When I use the least-conn algorithm to select the upstream, if the score is the same, it should use the polling algorithm to select the node, but in my test, this is not the case.
you can see:
I've got five nodes, When I use postman to click continuously, it only poll from three nodes, and the other two nodes are never selected. Is there any problem?
![image](https://user-images.githubusercontent.com/62246176/232679179-5fc4fa3d-1830-49b7-b63b-c048c0d47936.png)

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by thor533** [comment]
When I use postman to click consecutively, this active_conn should always be 0. According to (active_conn +1) /weigth, we know that they should have the same score

**Comment by tao12345666333** [comment]
Let's discuss in #7088, I will close this one. It's a duplicate.
