### ISSUE TITLE
how to export uri in prometheus metrics when there is not matched route (404 route not found)?

### ISSUE THREAD

**Issue by Garry24** [apache/apisix#9324]
### Description

When making a request to apisix, if the requested URI matches a route, the `matched_uri` can be seen in the `apisix_http_status ` metric exposed by Prometheus.  e.g.
>"apisix_http_status{code="200", container="apisix", instance="xxxxx:9091", matched_uri="/foo/bar", namespace="apisix", node="xxxx", pod="apisix-server-smw5t", route="foo-bar-route", service="foo-bar-service"}"

However, when the request does not match any route and results in a 404 error, the requested URI causing the error will not be recorded in the `apisix_http_status` metric.

How can I get 404 uri from prometheus metrics?

### Environment

- APISIX version (run `apisix version`): 2.15.1

**Comment by tao12345666333** [comment]
It's already included.

FYI

https://github.com/apache/apisix/blob/abcb49e019e7bbd5ceb7cba2c71ef4c4119bdc45/t/plugin/prometheus2.t#L285-L289

**Comment by Garry24** [comment]
sorry, I just got empty `matched_uri` value when has 404 eror.


https://github.com/apache/apisix/blob/0b848acd5a10dfabe9227ff555f8578297f29e5d/apisix/plugins/prometheus/exporter.lua#L205
