### ISSUE TITLE
Least-connection algorithm is incorrect

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#9325]
### Description

When I use the least-conn algorithm to select the upstream, if the score is the same, it should use the polling algorithm to select the node, but in my test, this is not the case.
you can see:
![image](https://user-images.githubusercontent.com/131146587/232719348-fa55c282-bd61-41a3-a7be-73de1a11fbfa.png)

I've got five nodes, When I use postman to click continuously, it only poll from three nodes, and the other two nodes are never selected. Is there any problem?
And when i  use postman to click continuously ， this  ‘active_conn ’ should always be 0. According to (active_conn +1) /weigth, we know that they should have the same score。
With the same minimum number of connections, is a normal polling algorithm used or SWRR？
or Is there more detailed documentation on this part? The official documentation is too simple

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
let's discuss #7088, I will close this one, it's a duplicate. Thanks for your report.

**Comment by bin-53** [comment]
> * APISIX version (run `apisix 2.15-alpine`):

i have request in #7088,please help me solve it
