### ISSUE TITLE
The active health check is abnormal

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9335]
### Description

I just turned on the active health check, and when all the nodes were marked unhealthy, I asked again, again randomly selecting the upstream node，
the error log :
![图片](https://user-images.githubusercontent.com/62246176/232961768-a9aa5206-4dde-4a42-a95d-8b7f3ed540d2.png)

the route config:
{
  "uri": "/test/*",
  "name": "test1231231",
  "priority": 1,
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE"
  ],
  "upstream": {
    "nodes": [
      {
        "host": "10.4.16.12",
        "port": 9001,
        "weight": 1
      },
      {
        "host": "192.168.88.66",
        "port": 9001,
        "weight": 1
      }
    ],
    "retries": 1,
    "timeout": {
      "connect": 1,
      "send": 1,
      "read": 9
    },
    "type": "least_conn",
    "checks": {
      "active": {
        "concurrency": 10,
        "healthy": {
          "http_statuses": [
            404
          ],
          "interval": 2,
          "successes": 5
        },
        "http_path": "/test",
        "port": 9001,
        "timeout": 1,
        "type": "http",
        "unhealthy": {
          "http_failures": 5,
          "http_statuses": [
            506,
            200
          ],
          "interval": 5,
          "tcp_failures": 2,
          "timeouts": 3
        }
      }
    },
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    },
    "retry_timeout": 1
  },
  "labels": {
    "1": "1"
  },
  "status": 1
}

### Environment

- APISIX version (run `apisix 2.15`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
Please provide a clearer description, I don't understand your meaning and please format your content.
