### ISSUE TITLE
The performance difference is too large

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9337]
### Description

I use apisix to do proxy forwarding, only to do proxy, without adding any plug-in and business functions, only one upstream node, after apisix,QPS only one-third, may I ask is it normal?
![image](https://user-images.githubusercontent.com/62246176/233013281-1ba8ab1c-d4fd-4bce-84ce-e13843ff95d7.png)

my route config is :
{
    "uri": "/ces/*",
    "name": "ces11",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS",
        "CONNECT",
        "TRACE"
    ],
    "upstream": {
        "nodes": [
            {
                "host": "10.4.16.12",
                "port": 8180,
                "weight": 1
            }
        ],
        "retries": 4,
        "timeout": {
            "connect": 10,
            "send": 10,
            "read": 10
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        },
        "retry_timeout": 4
    },
    "status": 1
}

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by thor533** [comment]
And when i set the worker_processes:1,the QPS only 5000,bad performance
![image](https://user-images.githubusercontent.com/62246176/233038048-d363f164-8ec6-4dba-8622-fdaea8272205.png)
![image](https://user-images.githubusercontent.com/62246176/233038114-b428fd6b-e47a-4220-a3d5-cade6b4cc824.png)

**Comment by tao12345666333** [comment]
Please use wrk2

**Comment by bin-53** [comment]
> Please use wrk2

okey，The result is about the same
![image](https://user-images.githubusercontent.com/131146587/233239785-364067d9-5213-48f6-b3a9-ddeed4521419.png)
![image](https://user-images.githubusercontent.com/131146587/233239867-a86da2d3-04da-470b-bd10-9132937639a3.png)

**Comment by thor533** [comment]
> Please use wrk2
okey,I got the same result

![image](https://user-images.githubusercontent.com/62246176/233244455-56f74500-9c45-4b84-a5f0-c087ecfafc12.png)
![image](https://user-images.githubusercontent.com/62246176/233244509-6bf14845-bd66-41a7-b910-02f121d510d2.png)

**Comment by thor533** [comment]
> Please use wrk2

hi, is there any configuration that needs to be modified?
