### ISSUE TITLE
help request: 

### ISSUE THREAD

**Issue by heiying0810** [apache/apisix#9340]
### Description

If I have many routes, but I don't want to generate accessLog logs for some of them, do I have corresponding switches or have development plans in the future

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
Please do not use GitHub issues for asking questions. The issues in this project are used to track bugs related to the project. If you have any questions, please join our Slack channel for communication.

https://apisix.apache.org/slack
