### ISSUE TITLE
where to find 404 config

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#9342]
### Description

in apisix,where to find the 404 configuration？

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zccabb** [comment]
Do you mean that you want to customize the return of 404?
If so, you can find the information for 404 under apisix/init.lua.Change it to the value you want.
https://github.com/apache/apisix/blob/54159168ee52f9d8614b6706842ddc5e5af2c4fb/apisix/init.lua#L569-L576
### Example
```lua
return core.response.exit(404,
                    {error_msg = "404 Route Not Found TEST TEST"})
```
If a 404 error occurs:
```shell
$ ~ curl 127.0.0.1:9080/
{"error_msg":"404 Route Not Found TEST TEST"}
```

**Comment by kellyseeme** [comment]
tks，and where i can find to change the 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/535200/233772276-91d7a913-f929-424c-8ada-bd80f08fc022.png">

**Comment by soulbird** [comment]
This information is compiled into apisix-base, you cannot modify it in apisix

**Comment by kellyseeme** [comment]
tks
