### ISSUE TITLE
help request: apisix2.15是否可以增加elasticsearch-logger支持？

### ISSUE THREAD

**Issue by zhangyuthink** [apache/apisix#9346]
### Description

我看apisix 3.2版已可以支持elasticsearch-logger，我生产环境部署了2.15版，不太敢升级。请问是否可以支持elasticsearch-logger？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
Version 2.15 will not add new features, only bug fixes and security updates
