### ISSUE TITLE
help request: How to config use_grpc when using Decoupled deployment mode , add use_grpc:true  both on dp and cp side?

### ISSUE THREAD

**Issue by liugang594** [apache/apisix#9347]
### Description

In Decoupled deployment mode, if I want to use gRPC, how can I config it, add **use_grpc:true**  both on dp and cp side, or only on cp side?

Thanks!

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by tao12345666333** [comment]
FYI https://github.com/apache/apisix/blob/master/t/deployment/grpc/mtls.t

**Comment by liugang594** [comment]
> FYI https://github.com/apache/apisix/blob/master/t/deployment/grpc/mtls.t

How about data-plane?

**Comment by leslie-tsang** [comment]
Considered solved. Feel free to reopen it if needed.
