### ISSUE TITLE
failed to use apixis as proxy of kafka

### ISSUE THREAD

**Issue by tangmin823** [apache/apisix#9348]
### Description

2023/04/20 20:55:35 [error] 544#544: *387663 [lua] kafka.lua:58: handle_upstream(): failed to initialize pubsub module, err: bad "upgrade" request header: nil, client: [192.168.100.75](http://192.168.100.75/), server: _, request: "POST /aa HTTP/1.1", host: "[192.168.20.41:9080](http://192.168.20.41:9080/)"

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`): centos
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): etcd Version: 3.4.13
- APISIX Dashboard version, if relevant: 3.2
- Plugin runner version, for issues related to plugin runners:  no use kafka-proxy, because no need to use SASL
- LuaRocks version, for installation issues (run `luarocks --version`):  /usr/bin/luarocks 2.3.0

**Comment by tao12345666333** [comment]
Please provide more details and steps to reproduce
