### ISSUE TITLE
Does apisix support converting websocket protocol to grpc protocol?

### ISSUE THREAD

**Issue by mloves0824** [apache/apisix#9354]
### Description

![image](https://user-images.githubusercontent.com/12976844/233818390-52690e47-49a0-479a-a02d-a77fef7103df.png)
Does apisix support converting websocket protocol to grpc protocol?
Establish a long websocket connection between the web client and apisix, apisix forwards the request to the backend grpc service, and pushes the push data of the backend service to the web client.

**Comment by tao12345666333** [comment]
Can you describe your specific scenario? Why do you need such a feature?

**Comment by mloves0824** [comment]
> Can you describe your specific scenario? Why do you need such a feature?

Our business scenario is a real-time data push scenario.
1. The web page establishes a persistent connection with the websocket gateway.
2. The webpage subscribes to the backend service through this connection, and the websocekt gateway forwards the subscription request to the backend service through grpc or kafka.
3. The backend service generates real-time data, which is pushed to the websocket gateway through grpc or kafka, and the gateway pushes the real-time data to the web page.

**Comment by kingluo** [comment]
@mloves0824 No, it does not support websocket-to-grpc.
Nginx websocket proxying is via HTTP 1.1 upgrade, i.e. the upstream http connection is downgraded to a plain tcp connection for websocket messaging.
If you need transcoding, then you need to implement it in lua code.

**Comment by leslie-tsang** [comment]
Considered solved. Feel free to reopen it if needed.

**Comment by harbourlga** [comment]
> ### Description
> ![image](https://user-images.githubusercontent.com/12976844/233818390-52690e47-49a0-479a-a02d-a77fef7103df.png) Does apisix support converting websocket protocol to grpc protocol? Establish a long websocket connection between the web client and apisix, apisix forwards the request to the backend grpc service, and pushes the push data of the backend service to the web client.

How did you solve it later using apisix? What's the plan?

**Comment by harbourlga** [comment]
> > Can you describe your specific scenario? Why do you need such a feature?
> 
> Our business scenario is a real-time data push scenario.
> 
> 1. The web page establishes a persistent connection with the websocket gateway.
> 2. The webpage subscribes to the backend service through this connection, and the websocekt gateway forwards the subscription request to the backend service through grpc or kafka.
> 3. The backend service generates real-time data, which is pushed to the websocket gateway through grpc or kafka, and the gateway pushes the real-time data to the web page.

How did you solve push scenario later using apisix? What's the plan?
