### ISSUE TITLE
The name of CSRF is error

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9373]
### Current Behavior

When I used the CSRF plugin, I found that there was a big problem with the algorithm that generated the token. When I modified the name parameter, the token could only be used once, and the second time it was used, an error was reported

{"error_msg":"csrf token mismatch"}

### Expected Behavior

The generated token can pass the verification

### Error Logs

{"error_msg":"csrf token mismatch"}

### Steps to Reproduce

1.set the route:
```
{
    "id": "457923292771123904",
    "create_time": 1682473152,
    "update_time": 1682498301,
    "uri": "/test/*",
    "name": "least-conn2",
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS",
        "CONNECT",
        "TRACE"
    ],
    "plugins": {
        "csrf": {
            "disable": false,
            "name":”test“
            "key": "edd1c9f034335f136f87ad84b625c8f1"
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "192.168.88.66",
                "port": 9001,
                "weight": 1
            }
        ],
        "retries": 1,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        },
        "retry_timeout": 2
    },
    "status": 1
}
```
2.request the GET method  get the token:
test=eyJleHBpcmVzIjoxNjgyNTAwNzk1LCJyYW5kb20iOjAuNjU5MzY4MzU4MzUyOTUsInNpZ24iOiI3NDFlZGJiZGNhYmVjZmQzMzBiY2Q2YjY4NTYyNzNiYzI0ZTBhODE0ZjZjNDZjNTU3ZWZmNDlmM2Q0YTNkYTc4In0=;path=/;SameSite=Lax;Expires=Wed, 26-Apr-23 11:19:55 GMT

3.request the post method request:
![image](https://user-images.githubusercontent.com/62246176/234529773-c05bd107-f56e-474b-9058-a43094a9d991.png)

4.When I asked again, apisix couldn't verify it
![image](https://user-images.githubusercontent.com/62246176/234530076-9ba56b23-17d0-4f8d-814c-6ca720d1f295.png)

ps:Using the default name does not have this bug

### Environment

- APISIX version (run `apisix 2.15-alpine`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@thor533 Can you also show the cookies in the subsequent request that was sent?

**Comment by sheharyaar** [comment]
@shreemaan-abhishek , I would like to look into this

**Comment by sheharyaar** [comment]
Hi @thor533 , I tried to reproduce this issue, but for me even the second and subsequent requests pass successfully.
I tried the same `apisix- 2.15-alpine` docker image.

**Comment by sheharyaar** [comment]
Can you please try to reproduce it again and attach apisix logs too ?

**Comment by sheharyaar** [comment]
@thor533 , i tested with the same image `apisix 2.15-alpine`, for me even with the default name, the second request gives "csrf token mismatch". This is because for every request, a new token is generated and sent via `Set-Cookie` header. Hence for every request you must read the token from the cookie. Since you are using the same `test` cookie, it blocks your request.

The docs mention that clearly : https://apisix.apache.org/docs/apisix/plugins/csrf/#enable-plugin

![image](https://github.com/apache/apisix/assets/34273345/ad265feb-98f9-4bb5-8f68-0a0365852413)

Moreover, in the image you attached, the Cookie set by postman is different from the `test` value :

![image](https://github.com/apache/apisix/assets/34273345/eb475ec1-b89a-4c81-b567-c1fb9a13a400)

**Comment by monkeyDluffy6017** [comment]
considered resolved. please feel free to reopen it

**Comment by monkeyDluffy6017** [comment]
@sheharyaar thanks for your contribution
