### ISSUE TITLE
help request: APISIXROUTE can NOT distinct cookie_var null and NOT exist

### ISSUE THREAD

**Issue by newman4cloud** [apache/apisix#9374]
### Description

apisixroute.yaml like here:
    match:
      exprs:
      - op: In
        subject:
          name: hello
          scope: Cookie
        set: 
        - ""

     
\# request will be received
\# curl --cookie "hello="  http://my_apisix  

\# **request can NOT be received**
\# curl  http://my_apisix

In my opinion, if cookie_var does not exist in a request, then its value should be "" as default
if this is NOT a bug but a feature, please tell me how to distinct cookie_var is null and not exist

### Environment

# apisix version
/usr/local/openresty/luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua version
2.15.0

**Comment by Sn0rt** [comment]
don't understand very well
Do you want to distribute routes based on cookies?

**Comment by shreemaan-abhishek** [comment]
@newman4cloud, please elaborate your problem.
