### ISSUE TITLE
help request: curl 9180 port got Connection reset by peer

### ISSUE THREAD

**Issue by Hxhong** [apache/apisix#9377]
### Description

refer to https://github.com/apache/apisix/issues/8171
There is no problem requesting port 9180 on the container host, but the following error suddenly occurred when requesting port 9180 on other virtual machines: 
<img width="965" alt="image" src="https://user-images.githubusercontent.com/42258295/234738216-2c84f994-0c20-4d23-9db5-df3e233f3e89.png">

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Centos-7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.6
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> on other virtual machines

What does it mean?

Also, could you please show your docker-compose file?

P.S: We have some examples you might want to refer: https://github.com/apache/apisix-docker

**Comment by Hxhong** [comment]
> > on other virtual machines
> 
> What does it mean?
> 
> Also, could you please show your docker-compose file?
> 
> P.S: We have some examples you might want to refer: https://github.com/apache/apisix-docker
For example, if the container is on 192.168.0.1 and I request port 9180 on that address, it works correctly. However, if the request is made from another virtual machine, I receive a "connection reset by peer" error message.
Here is my docker run command：
docker run -d \
-p 9080:9080 \
-p 9180:9180 \
-p 9091:9091 \
-v config.yaml:ro \
--restart=always \
--name apisix \
apache/apisix:3.1.0

**Comment by Hxhong** [comment]
> > on other virtual machines
> 
> What does it mean?
> 
> Also, could you please show your docker-compose file?
> 
> P.S: We have some examples you might want to refer: https://github.com/apache/apisix-docker

For example, if the container is on 192.168.0.1 and I request port 9180 on that address, it works correctly. However, if the request is made from another virtual machine, I receive a "connection reset by peer" error message.
Here is my docker run command：
docker run -d
-p 9080:9080
-p 9180:9180
-p 9091:9091
-v config.yaml:ro
--restart=always
--name apisix
apache/apisix:3.1.0

**Comment by LiteSun** [comment]
Can you successfully ping the target machine from another machine, it looks like a network problem

**Comment by Hxhong** [comment]
> Can you successfully ping the target machine from another machine, it looks like a network problem

Yes, I checked the network and there was no problem. Strangely, there is no problem with the GET request, but there is a problem with the PUT request...But the PUT request can run successfully on container host.

**Comment by Sn0rt** [comment]
are you sure the APISIX is running ?
and are you solve this problem ?
