### ISSUE TITLE
help request: Error "lua_ssl_trusted_certificate" directive is duplicate in /usr/local/apisix/conf/nginx.conf:240

### ISSUE THREAD

**Issue by Sachkov-Aleksandr** [apache/apisix#9381]
### Description

Hello. 
I am trying to install APICIS via Helm chart. At the same time, I need to link the control plane and etcd via mtls. 
I have separately installed an etcd cluster of three nodes.  Configured values for the control plane and mtls. And deploy Helm.
But in APISIX, when deploying, I get the error /usr/local/openresty//luajit/bin/luajit ./apisix/cli/api sys.lua init_etcd
2023/04/27 11:05:55 [emerg] 1#1: the directive "lua_ssl_trusted_certificate" is duplicated in /usr/local/apisix/conf/nginx.conf:240
nginx: [emerg] the directive "lua_ssl_trusted_certificate" is duplicated in /usr/local/apisix/conf/nginx.conf:240

Please, help me with this problem?

### Environment

- APISIX version (run `apisix version`): 3.2.0-debian
- Operating system (run `uname -a`): K8s 1.22, node OS is debian
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):  bitnami/etcd 3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant: Not dashboard
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Could you please share the command that you used to install APISIX?

**Comment by shreemaan-abhishek** [comment]
What did you do to enable mTLS with etcd?

Also, there is an unknown field `ssl_verify_depth: 2` in your config map. This field is not present in config-default.yaml. Maybe try removing it.

++ try installing apisix using helm charts by the way defined [here](https://apisix.apache.org/docs/helm-chart/apisix/).

**Comment by Sachkov-Aleksandr** [comment]
> What did you do to enable mTLS with etcd?
> 
> Also, there is an unknown field `ssl_verify_depth: 2` in your config map. This field is not present in config-default.yaml. Maybe try removing it.
> 
> ++ try installing apisix using helm charts by the way defined [here](https://apisix.apache.org/docs/helm-chart/apisix/).

Thanks for the reply. 
I include mtls in etcd via directives in Helm:

`  client:
     secureTransport: true
    useAutoTLS: false
    existingSecret: "etcd-client-secret"
    enableAuthentication: true
    certFilename: "tls.crt"
    certKeyFilename: "tls.key"
    caFilename: "ca.crt"
 `

And than I enabled mtls in APISIX Helm via by specifying certificates:

`etcd:
   enabled: false
  host:
    - https://etcd.apisix.svc.cluster.local:2379
  user: ""
  password: "" 
  prefix: "/apisix"
  timeout: 30
  auth:
    rbac:
      create: false
      rootPassword: *************
    tls:
      enabled: true
      existingSecret: "etcd-cp-secret"
      certFilename: "tls.crt"
      certKeyFilename: "tls.key"
      verify: true
      sni: ""`

I removed the field ssl_verify_depth:2 directive but it didn't give a result.
I will also note that initially I installed the chart via Helm, specifying certificates in values and received the same error except for one moment - I also set etcd separately.

**Comment by Sachkov-Aleksandr** [comment]
Hello. Could you please help me with my problem. I installed via Help and everything works, but the standard Helm works without SSL. How can I use it to correctly configure MTLS?

**Comment by shreemaan-abhishek** [comment]
@Sachkov-Aleksandr, even I tried to implement mTLS between apisix and etcd using helm but was unsuccessful

```bash
helm upgrade --install apisix apisix/apisix --create-namespace  --namespace apisix \
  --set ingress-controller.enabled=true \
  --set ingress-controller.config.apisix.serviceNamespace=apisix \
  --set gateway.stream.enabled=true \
  --set etcd.auth.tls.enabled=true \
  --set etcd.auth.tls.existingSecret="mtls" \
  --set etcd.auth.tls.certFileName="t/certs/mtls_client.crt" \
  --set etcd.auth.tls.certKeyFilename="t/certs/mtls_client.key" \
  --set gateway.tls.enabled=true \
  --set gateway.tls.existingCASecret="ssl" \
  --set gateway.tls.certCAFilename="t/certs/mtls_ca.crt"
```

You can take a look at this blog: https://blog.frankel.ch/mtls-everywhere/. It might help you.

Also, you might as well ask this question in the slack channel. You might get some help there.

**Comment by Sachkov-Aleksandr** [comment]
> @Sachkov-Aleksandr, even I tried to implement mTLS between apisix and etcd using helm but was unsuccessful
> 
> ```shell
> helm upgrade --install apisix apisix/apisix --create-namespace  --namespace apisix \
>   --set ingress-controller.enabled=true \
>   --set ingress-controller.config.apisix.serviceNamespace=apisix \
>   --set gateway.stream.enabled=true \
>   --set etcd.auth.tls.enabled=true \
>   --set etcd.auth.tls.existingSecret="mtls" \
>   --set etcd.auth.tls.certFileName="t/certs/mtls_client.crt" \
>   --set etcd.auth.tls.certKeyFilename="t/certs/mtls_client.key" \
>   --set gateway.tls.enabled=true \
>   --set gateway.tls.existingCASecret="ssl" \
>   --set gateway.tls.certCAFilename="t/certs/mtls_ca.crt"
> ```
> 
> You can take a look at this blog: https://blog.frankel.ch/mtls-everywhere/. It might help you.
> 
> Also, you might as well ask this question in the slack channel. You might get some help there.

Can you give me link on Slack channel?

**Comment by shreemaan-abhishek** [comment]
https://join.slack.com/t/the-asf/shared_invite/zt-1vf0j8c9c-YBzmRKvB0X4Ear0eZG04Rw

**Comment by Sn0rt** [comment]
@shreemaan-abhishek can I close this issue ?

**Comment by shreemaan-abhishek** [comment]
@Sn0rt, I don't know. I am not sure if the user's query is resolved.
