### ISSUE TITLE
help request: I want to control the plug-in according to parameters.

### ISSUE THREAD

**Issue by Cheol-Soon-Choi** [apache/apisix#9393]
### Description

I want to trigger a plugin based on parameters or headers.

When /test?key=a, plugin A works,
When /test?key=b, can plugin B work?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi, Maybe this documetation is helpful. https://apisix.apache.org/docs/apisix/terminology/plugin/#dynamically-control-whether-the-plugin-is-executed

**Comment by Sn0rt** [comment]
@Cheol-Soon-Choi 

Did the last comment solve your problem?
If you don't reply, I will close this issue in a week.
