### ISSUE TITLE
help request: does apisix support ssl_preread_protocol? can we use one port to serve both http and https?

### ISSUE THREAD

**Issue by ZhangShangyu** [apache/apisix#9394]
### Description

**Background**
We want to use one port to serve both http and https due to the firewall rule restrict.
For example: 8081 port can proxy both http and http schema, http://test.com:8081 and https://test.com:8081 can proxy to the same apisix upstream backend

**Nginx solution**
In native nginx can use ssl_preread_protocol to implement this requirement, refer to https://www.nginx.com/blog/running-non-ssl-protocols-over-ssl-port-nginx-1-15-2

```
stream {
    upstream http {
        server unix:/var/run/nginx_http.sock;
    }

    upstream https {
        server unix:/var/run/nginx_https.sock;
    }

    map $ssl_preread_protocol $upstream {
        "" http;
        default https;
    }

    server {
        listen 8081;
        proxy_pass $upstream;
        ssl_preread on;
        proxy_protocol on;
    }
}

http {
    server {
        listen unix:/var/run/nginx_http.sock proxy_protocol;
        listen unix:/var/run/nginx_https.sock ssl proxy_protocol;

        location / {
            proxy_pass http://192.168.1.1:8080;
        }
    }
}
```

**so how can apisix solve this requirement?**

thanks for help

**Comment by xiaolei000129** [comment]
解决了吗？

**Comment by xiaolei000129** [comment]
解决了吗？我也遇到这个问题了，我们的前端是https 但是我的接口是http://xxx:9080/不知道怎么用https 现实

**Comment by xiaolei000129** [comment]
升级最新版本解决了问题
