### ISSUE TITLE
docs: missing `Protos` section in Admin API

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9404]
[Proto](https://github.com/apache/apisix/blob/master/apisix/admin/proto.lua) should be documented to the [Admin API reference](https://apisix.apache.org/docs/apisix/admin-api/).

It is used in creating gRPC communication. 

See the use of `/admin/protos/{id}` with `grpc-transcode` plugin [here](https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/#enabling-the-plugin).

**Comment by navendu-pottekkat** [comment]
This new "Proto" section could be appended to the end of the document. It should follow the same style as the rest of the sections in the Admin API.
