### ISSUE TITLE
docs: use shell instead of Python to configure protos resources

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9405]
This doc issue also has the same motivation: https://github.com/apache/apisix/issues/9229

## Current State

In current [grpc-transcode](https://apisix.apache.org/docs/apisix/plugins/grpc-transcode/#enabling-the-plugin) doc:
![image](https://user-images.githubusercontent.com/39619599/236181934-220ed02d-4088-4020-b274-c380b010312a.png)

Python is used to
1. convert `.pb` file from binary to `base64` format
2. send HTTP PUT request to `/protos` to create a protos resource

## Desired State

Replace Python script with 
* shell `base64` utility, which Linux distros and macOS come with
* shell `curl` for sending HTTP requests

**Comment by jiangfucheng** [comment]
@Gallardot Hi, could assign it to me?
