### ISSUE TITLE
help request: After finding with nacos service, the weights with weights polling, where the weight is to obtain the weight configured on nacos

### ISSUE THREAD

**Issue by caobaorui** [apache/apisix#9416]
### Description

After finding with nacos service, the weights with weights polling, where the weight is to obtain the weight configured on nacos

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):Linux master 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by soulbird** [comment]
It seems that the weight is obtained from nacos, see: https://github.com/apache/apisix/blob/master/apisix/discovery/nacos/init.lua#L317

**Comment by caobaorui** [comment]
> 好像是从nacos中获取权重，参见：[https ://github.com/apache/apisix/blob/master/apisix/discovery/nacos/init.lua#L317](https://github.com/apache/apisix/blob/master/apisix/discovery/nacos/init.lua#L317)

If the load balancing policy uses polling with weights and the service discovery mode is k8s, where is the weight obtained and how do I set the weight

**Comment by shreemaan-abhishek** [comment]
@caobaorui you want to set the weight for nodes discovered using k8s service discovery mode?
