### ISSUE TITLE
apisix-plugin-java  Connection refused

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9418]
### Description

When I used java to develop the java plug-in, I deployed apisix in the native environment with docker, then I started Java-plugin-runner with idea, and when I accessed route, I couldn't connect

```
2023/05/06 07:34:11 [error] 51#51: *1381 connect() to unix:/tmp/runner.sock failed (111: Connection refused), client: 172.20.0.1, server: _, request: "GET /test/ HTTP/1.1", host: "127.0.0.1:9080"
2023/05/06 07:34:11 [error] 51#51: *1381 [lua] init.lua:881: phase_func(): failed to connect to the unix socket unix:/tmp/runner.sock: connection refused, client: 172.20.0.1, server: _, request: "GET /test/ HTTP/1.1", host: "127.0.0.1:9080"
2023/05/06 07:34:11 [warn] 51#51: *1381 [lua] plugin.lua:1098: run_plugin(): ext-plugin-pre-req exits with http status code 503, client: 172.20.0.1, server: _, request: "GET /test/ HTTP/1.1", host: "127.0.0.1:9080"
172.20.0.1 - - [06/May/2023:07:34:11 +0000] 127.0.0.1:9080 "GET /test/ HTTP/1.1" 503 269 0.000 "-" "curl/7.64.1" - - - "http://127.0.0.1:9080"
```
My environment：macOS 11.3
the container is :
![image](https://user-images.githubusercontent.com/62246176/236610299-1c4a7eab-ff02-4245-a49c-3739db97783d.png)

How do I develop locally? I want to debug locally

### Environment

- APISIX version (run `apisix version`):apache/apisix:3.2.0-debian 
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
thank you report. 
can you provier a guide for help us to reproduce ?

**Comment by Sn0rt** [comment]
can't reproduced
