### ISSUE TITLE
install: mkdir /usr/share/lua: Read-only file system

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9421]
### Description

When I installed apisix from the native source, make install encountered an error and I was unable to install it smoothly
![image](https://user-images.githubusercontent.com/62246176/236613138-a8291afb-0b41-4dfa-93b2-9feba5f1f391.png)

I changed docker to install apisix, which can run normally, but I want to develop java plug-in, and cannot debug it locally. Is there a way to solve this problem。（Or, how can I set up apisix locally for normal development, which would be too much of a crash
）

My environment：macOS big sur 11.3

### Environment

- APISIX version (run `apisix version`):apache/apisix:3.2.0-debian
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zccabb** [comment]
This is a problem with the macos security mechanism.
You can refer to these schemes to see if you can solve them.
https://toolbox.easeus.com/ntfs-mac-tips/read-only-file-system-on-mac.html
https://apple.stackexchange.com/questions/430927/terminal-command-ln-generates-error-read-only-file-system
https://support.apple.com/guide/mac-help/change-permissions-for-files-folders-or-disks-mchlp1203/mac
Or search keywords
`macos read-only file system`

**Comment by Sn0rt** [comment]
and does not need install.

```shell
make deps 
make run
```

**Comment by thor533** [comment]
> and does not need install.
> 
> ```shell
> make deps 
> make run
> make reload
> ```

My God, you are right, why does the official document not have the correct procedure.
Big guy, I ran locally, but I didn't enter debug, could you please help me check? You are a good man.
![image](https://user-images.githubusercontent.com/62246176/236618823-ec804406-aad9-4bea-a752-2d670d4c8217.png)


the route:
```
{
  "uri": "/test/*",
  "name": "xx",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "plugins": {
    "ext-plugin-pre-req": {
      "conf": [
        {
          "name": "TokenValidator",
          "value": "{\"validate_header\":\"token\",\"validate_url\":\"https://www.sso.foo.com/token/validate\",\"rejected_code\":\"403\"}"
        }
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "10.210.21.105",
        "port": 9001,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "labels": {
    "API_VERSION": "x"
  },
  "status": 1
}
```

**Comment by shreemaan-abhishek** [comment]
I am closing this issue as it seems that the original issue has been resolved, if you have more questions you can reopen this issue. If you have questions about setting up a debugging environment, please file another issue. Thanks.
