### ISSUE TITLE
docs: apisix/getting-started ##using-the-apisix-dashboard

### ISSUE THREAD

**Issue by zccabb** [apache/apisix#9422]
### Current State

Now I have a question, please kindly answer it at your convenience.
I use https://apisix.apache.org/docs/apisix/getting-started/ install apisix
https://apisix.apache.org/docs/apisix/getting-started/#using-the-apisix-dashboard
![534a0e79-b212-4cc5-8e11-fa2a2ffc07fe](https://user-images.githubusercontent.com/76942195/236614231-38cecc38-c7ce-4cb2-bf9a-329a4eb2bcc7.jpeg)
At this point, can I access apisix-dashboard directly from localhost:9000？

### Desired State

Should I be able to access dashboard at localhost:9000 according to the documentation.
But there is no service for localhost:9000.

**Comment by zccabb** [comment]
If the issue exists，please assign it to me，I can modify this document.

**Comment by Neilblaze** [comment]
@zccabb can you retry with `localhost:9080`? 
> @navendu-pottekkat Seems like the port number needs to be updated.

**Comment by navendu-pottekkat** [comment]
The current getting started guide uses a different install script that does not install the dashboard by default. You can follow an older version of the guide, and it should work out of the box: https://apisix.apache.org/docs/apisix/3.0/getting-started/

cc: @juzhiyuan

**Comment by zccabb** [comment]
thanks
