### ISSUE TITLE
help request: After building openresty on Mac m1 ,make run error

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9424]
### Description

error log is :
2023/05/06 21:18:45 [emerg] 82318#18641762: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82319#18641763: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82320#18641764: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82321#18641765: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82322#18641767: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82323#18641768: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82324#18641769: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82325#18641770: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82326#18641771: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82327#18641772: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
2023/05/06 21:18:45 [emerg] 82328#18641773: failed to init engine: dlopen("", 0x0002): tried: '""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/openresty/1.21.4.1_2/luajit/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache), '""' (no such file), '/usr/local/lib/""' (no such file), '/usr/lib/""' (no such file, not in dyld cache) with ""
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/10181098/236629265-bd0e062c-da18-49ee-9c76-cd94cfb2aa4a.png">

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by leslie-tsang** [comment]
Please provide the reproduce step. :)

**Comment by shreemaan-abhishek** [comment]
You can take a little help from here: https://blog.ronething.cn/20230212-build-apisix-on-m2-pro.html#0x02-%E6%BA%90%E7%A0%81%E6%9E%84%E5%BB%BA

**Comment by Sn0rt** [comment]
recommend https://sn0rt.github.io/build-self-apisix/

**Comment by zzqCh** [comment]
> recommend https://sn0rt.github.io/build-self-apisix/ 

已解决，谢谢
