### ISSUE TITLE
feat: add id to global_rules schema

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#9429]
### Description

xref: https://github.com/apache/apisix/pull/8439

https://github.com/apache/apisix/blob/9ad740234dff97653d057350f3177be18ec7ddd9/apisix/schema_def.lua#L831-L840

the `id` is required.

**Comment by tarunclub** [comment]
Hey, I think I can help you out with this can you assign this issue to me?

**Comment by tarunclub** [comment]
Hey,

Just wanted to let you all know that I've raised a pull request for issue #9432. It includes the changes we discussed earlier to add the 'id' property to the required section of the global_rule schema.

Please take a look and let me know if you have any feedback or concerns. Your review and feedback would be greatly appreciated.

Thanks!

**Comment by tao12345666333** [comment]
thanks

https://github.com/apache/apisix/pull/8439#issuecomment-1334667221

please add test case

**Comment by howiieyu** [comment]
I would like this issue to be assigned to me if possible, thanks. 
@spacewander @tao12345666333

**Comment by tao12345666333** [comment]
@tarunclub has opened a PR for this, but there has been no feedback and no test case added.

If you are willing to work on this, you can open a PR

**Comment by howiieyu** [comment]
@tao12345666333 I opened a PR for this issue, please check it for #9517 .

**Comment by tao12345666333** [comment]
#9517 has been merged, I will close this one, thanks.
