### ISSUE TITLE
Stream Route `remote_addr` Naming Suggestion

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9441]
## Current State
`remote_addr` in a stream route is used to filter requests by client's IP address. The naming of this attribute is confusing. It is difficult to tell if `remote_addr` means upstream service or downstream client's IP. 

## Suggestion
Rename `remote_addr` to `client_addr` or similar

## Relevant Docs
* [Admin API Stream Routes](https://apisix.apache.org/docs/apisix/admin-api/#stream-route-api)
* [Stream Proxy doc](https://apisix.apache.org/docs/apisix/next/stream-proxy/)

APISIX Version: `v3.3.0`

**Comment by fatihbm** [comment]
The `remote_addr` variable is an embedded variable used by Nginx that provides information about the client address. This variable is critical in Nginx's internal workings and is necessary for properly routing HTTP requests. Therefore, renaming this variable to `client_addr` or something similar could cause Nginx to behave unexpectedly or produce errors.
http://nginx.org/en/docs/http/ngx_http_core_module.html

**Comment by kayx23** [comment]
@fatihbm ok I see, thanks for sharing!

**Comment by kayx23** [comment]
ok I see. Thanks for the clarification! Issue closed.

Traky
