### ISSUE TITLE
feat: As a user, I want to add CI based on RedHat UBI, so that users can have a more stable environment.

### ISSUE THREAD

**Issue by tao12345666333** [apache/apisix#9454]
### Description

Due to the approaching EOL of CentOS 7/8 [1], users may choose to use more professional RedHat UBI images[2][3][4]. I suggest that we can add CI based on UBI images and support package building for this platform. I have already tested it and found that APISIX's rpm package can run directly in the UBI image. **We also need to release container images based on RedHat UBI.**

1. https://wiki.centos.org/About/Product
2. https://connect.redhat.com/en/blog/migrating-your-base-image-from-centos-to-ubi
3.  https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image
4. https://hub.docker.com/r/redhat/ubi8

**Comment by Sn0rt** [comment]
@Revolyssup pls take a look

**Comment by Revolyssup** [comment]
@Sn0rt I will take up the issue. Just to confirm - I need to add another dockerfile here https://github.com/api7/apisix-build-tools/tree/master/dockerfiles with UBI as base image.

**Comment by tao12345666333** [comment]
@Revolyssup This issue includes two aspects:

* Building UBI-based images, so you need to add specific build steps in the apisix-build-tools project, including the Dockerfile[1] mentioned above and some GitHub Actions workflows[2]. 
* Using the image built in the previous step to run CI in apache/apisix repository.

1. https://github.com/api7/apisix-build-tools/tree/master/dockerfiles
2. https://github.com/api7/apisix-build-tools/tree/master/.github/workflows
3. https://github.com/apache/apisix/tree/master/.github/workflows

**Comment by Sn0rt** [comment]
@kingluo FYI we will add a new ci for testing whole test cases at UBI.

**Comment by Revolyssup** [comment]
> 3\. https://github.com/apache/apisix/tree/master/.github/workflows

@tao12345666333 For the second part, the CI added would be similar to the existing tests based on centos[1] right? Except we will use the newly created UBI based image.

1. https://github.com/apache/apisix/blob/master/.github/workflows/centos7-ci.yml

**Comment by tao12345666333** [comment]
yes

**Comment by Revolyssup** [comment]
@tao12345666333 Do you think I will need a separate dockerfile for this? Or IMAGE_BASE and IMAGE_TAG here[1] can be overridden during build process to redhat/ubi8. So if I go this way, I won't need any changes in the Dockerfile right? Maybe some changes in the build script here[2] to check for IMAGE_BASE=="ubi8" and change installation steps. 
Please correct me if I'm wrong somewhere.

1. https://github.com/api7/apisix-build-tools/blob/a494c2de90ccc7973ca510b4708704555cdbbf8b/dockerfiles/Dockerfile.apisix-base.rpm#L1

2. https://github.com/api7/apisix-build-tools/blob/a494c2de90ccc7973ca510b4708704555cdbbf8b/utils/install-common.sh#L19

**Comment by Revolyssup** [comment]
@tao12345666333 Another doubt I had was - As you said "We also need to release container images based on RedHat UBI." In the build tools repository[1] I see dockerfiles which are used to create apisix packages(deb/rpm). Where are the dockerfiles for images that are pushed to apache/apisix like this one[2].

1. https://github.com/api7/apisix-build-tools
2. https://hub.docker.com/layers/apache/apisix/3.3.0-centos/images/sha256-9e47afde08933567fd9c447c6dcc66cd02466e337e098eec347e1973d0f24be2?context=explore

**Comment by tao12345666333** [comment]
yes. You can refer to this article https://connect.redhat.com/en/blog/migrating-your-base-image-from-centos-to-ubi

It is possible to do it by modifying the parameters in the build process.

**Comment by tao12345666333** [comment]
please check the Apache/APISIX-docker repository

**Comment by tao12345666333** [comment]
https://hub.docker.com/layers/apache/apisix/3.3.0-redhat/images/sha256-dcef789ef0cc6d7c7e671623e3f0651f882058e450e34970fc3a78aeb6742b12?context=explore

The RedHat UBI based image has been published.
