### ISSUE TITLE
feat: As a user, I want to forward-auth add more forward info, so that can easily obtain related routing information

### ISSUE THREAD

**Issue by sdvdxl** [apache/apisix#9461]
### Description

 I need the route_id to check auth,but now only can check uri path.
forward-auth  plugin need forward more infos, example:
 route_id, route_name.
It is better to be able to specify the parameters you want.

**Comment by flca267** [comment]
I think combine `proxy-rewrite` and `forward-auth` can pass route_id to authorization service.
For example
```
{
  "plugins": {
        "proxy-rewrite": {
            "headers": {
                "add": {
                    "x-rout-id": "$route_id",
                    "x-route-name": "$route_name"
                }
            }
        },
        "forward-auth": {
            "uri":"authorization-service-uri",
            "request_headers": ["x-rout-id", "x-route-name"]
        }
    }
    ...
}
```
I did not test it, check if it works by yourself.

**Comment by sdvdxl** [comment]
it works
