### ISSUE TITLE
help request: How to access the parameter in path while writing plugin

### ISSUE THREAD

**Issue by awx-tim-zhang** [apache/apisix#9462]
### Description

I defined a route with uri like this `user/:user`. How to access the value of the parameter `user` in a custom plugin?

### Environment

- APISIX version 2.15

**Comment by shreemaan-abhishek** [comment]
You can use `ngx.req.get_uri_args()`.

FYI: https://github.com/apache/apisix/blob/4419d0d8eb3daf901a1cf6fd4d2f806e579dced9/apisix/core/request.lua#L43

**Comment by Sn0rt** [comment]
hi @awx-tim-zhang . have you try the last comment ? does it work for your plugin ?

if we not get your reply in one week we will close this issue.
