### ISSUE TITLE
help request: debug by pstack, no symbol table

### ISSUE THREAD

**Issue by math-chao** [apache/apisix#9465]
### Description

debug by pstack, but no symbol table

here is the result 
#0  0x0000000000449bf3 in ngx_shmtx_lock (mtx=0x7fc9d4ded068) at src/core/ngx_shmtx.c:78
#1  0x0000000000572caf in ngx_meta_lua_ffi_shdict_get (zone=0x1281138, key=0x7fc9d1d69080 "__ngx_prom__delete_count", key_len=24, value_type=0x7fc9de85f828, str_value_buf=0x7fc9de844380, str_value_len=0x7fc9de875ef8, num_value=0x7fc9de85f868, user_flags=0x7fc9de85f848, get_stale=0, is_stale=0x7fc9de8636f8, err=0x7fc9de8723a8) at /tmp/tmp.YN7822nAJt/openresty-1.21.4.1/../apisix-nginx-module-1.9.0/src/meta/ngx_meta_lua_shdict.c:1631
#2  0x00007fca19caa8d7 in ?? ()
#3  0x00007fc9de85f868 in ?? ()
#4  0x00007fc9de85f848 in ?? ()
#5  0x0000000000000000 in ?? ()

how to resolve it? help please 

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please give more description about your issue like what you are trying to do.

**Comment by Sn0rt** [comment]
hi @math-chao , how to produce your case help us to solve this issue?
