### ISSUE TITLE
forward-auth Cookies cannot be carried to upstream

### ISSUE THREAD

**Issue by thor533** [apache/apisix#9469]
### Description

When I use forward-auth for authentication, I pass the authentication, I write the cookie into the response header and forward it to the upstream homepage, but the browser cannot write and forward the cookie of the domain. What do I need to do? It is similar to a simple single sign-on function

the route config ：
```
{
  "uri": "/test/*",
  "name": "forwardauth",
  "priority": 1,
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS"
  ],
  "plugins": {
    "forward-auth": {
      "client_headers": [
        "location",
        "set-cookie",
        "Cookie",
        "Host"
      ],
      "disable": false,
      "request_headers": [
        "Location"
      ],
      "upstream_headers": [
        "location",
        "set-cookie",
        "Cookie",
        "Host"
      ],
      "uri": "http://127.0.0.1:8088/ssoserver/get/authentication/forwardauth"
    },
    "proxy-rewrite": {
      "regex_uri": [
        "^/test(/|$)(.*)",
        "/$2"
      ]
    }
  },
  "upstream": {
    "nodes": [
      {
        "host": "10.20.11.29",
        "port": 8180,
        "weight": 1
      }
    ],
    "retries": 1,
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "node",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}
```
I cannot realize this business requirement. I have written the cookie into the response header, but it cannot be written into the browser

### Environment

- APISIX version (run `apisix version`):2.15-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by thor533** [comment]
When the authentication was successful, the set-cookie attribute I set was not brought upstream
![image](https://github.com/apache/apisix/assets/62246176/f1757b1c-bcce-44b2-9f3c-7a4ca82d5eef)

**Comment by Gallardot** [comment]
According to the APISIX documentation and your configuration, the `upstream_headers` header from auth-server will be sent to upstream server by APISIX on successful authentication. Upstream server then provides the header back to the browser if needed. Only if authentication fails will APISIX directly send the header specified by `client_headers` to the browser.

https://apisix.apache.org/docs/apisix/plugins/forward-auth/#attributes

**Comment by Sn0rt** [comment]
@thor533 can you confirm the last comment and close this issue ?
