### ISSUE TITLE
bug(docs): Incorrect redirect link in Getting Started documetation

### ISSUE THREAD

**Issue by jiangfucheng** [apache/apisix#9473]
### Current Behavior

Some links that in the https://apisix.apache.org/docs/apisix/getting-started/rate-limiting/ web page have beed redirected to incorrect pages.
![image](https://github.com/apache/apisix/assets/33349046/06e2ccee-50c2-4d43-ac96-c76d3009d1d7)

1.`Get APISIX` link should redirect to https://apisix.apache.org/docs/apisix/getting-started/README/ , but actual redirected page is current page
2.`Configure routes` link should redirect to https://apisix.apache.org/docs/apisix/getting-started/configure-routes/ , but actual redirected page is :https://apisix.apache.org/docs/apisix/getting-started/rate-limiting/configure-routes/#whats-a-route
![image](https://github.com/apache/apisix/assets/33349046/11249137-0140-4366-a7c3-7e02b284ac2c)

There are same issues on other pages under `Getting Started`.

I'm not familar with Front-End technology, maybe this issues cause by relative path? 
```
## Prerequisite(s)

1. Complete the [Get APISIX](./) step to install APISIX first.
2. Complete the [Configure Routes](./configure-routes#whats-a-route) step.
```
Can we through replace the relative path to absolute path to fix this issue?
Like these codes in https://github.com/apache/apisix/blob/master/docs/en/latest/getting-started/key-authentication.md: 
![image](https://github.com/apache/apisix/assets/33349046/be789821-1f28-4327-a201-4042cad253a1)

### Steps to Reproduce

1.Enter this page: https://apisix.apache.org/docs/apisix/getting-started/rate-limiting/
2.Click `Configure routes` link: 
![image](https://github.com/apache/apisix/assets/33349046/021e5d2c-7b2d-4982-aeeb-5b3c4eb27529)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zccabb** [comment]
Hey, I think I can help you out with this can you assign this issue to me?

**Comment by Arghyahub** [comment]
I have already fixed the issue,
Can anyone help me on how to test the frontend locally? I'm unable to test it

**Comment by Arghyahub** [comment]
I have fixed the issue
