### ISSUE TITLE
apisix response-rewrite when match OPTIONS request

### ISSUE THREAD

**Issue by juzn01** [apache/apisix#9475]
### Description

I need check request match OPTIONS method,please help me config ,when match it,apisix return 200 to client.

### Environment

- APISIX version : 3.2
- Operating system : centos7
- OpenResty / Nginx version : 1.21.4
- etcd version, if relevant : 3.5
- APISIX Dashboard version, if relevant: 2.14

**Comment by shreemaan-abhishek** [comment]
I didn't understand your request. Please elaborate.

**Comment by wangxiaolong100** [comment]
If you want to solve CORS issues, you can use the cors plugin.

**Comment by Sn0rt** [comment]
@juzn01  can you confirm the last comment and close this issue .
