### ISSUE TITLE
help request: does the consul discovery support filtering nodes based on metadata, and does it also support parsing TaggedAddresses

### ISSUE THREAD

**Issue by shenqidebaozi** [apache/apisix#9476]
### Description

Hello, I am currently researching the **apisix gateway** product and Consul is currently serving as our company registration center.

I have noticed that **apisix** supports the **consul service**, but I have not yet found how to filter nodes and how to use the consul `TaggedAddresses` feature. In addition, the service discovery option of the **apisix dashboard** does not include `consul`, so I cannot directly set it in the dashboard. The routing specified through the API can also cause errors when viewed in the interface.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shenqidebaozi** [comment]
![image](https://github.com/apache/apisix/assets/35397691/c752f506-abbe-4424-ad28-571b39b15577)
![image](https://github.com/apache/apisix/assets/35397691/bd14523f-d10c-458c-b5cd-56a69053c3f8)

**Comment by Fabriceli** [comment]
> ![image](https://user-images.githubusercontent.com/35397691/237897770-c752f506-abbe-4424-ad28-571b39b15577.png) ![image](https://user-images.githubusercontent.com/35397691/237897864-bd14523f-d10c-458c-b5cd-56a69053c3f8.png)

apisix-dashboard support consul discovery from [apisix-dashboard#2731](https://github.com/apache/apisix-dashboard/pull/2731)

**Comment by Sn0rt** [comment]
If a user encounters this problem next time, we will reopen this issue
