### ISSUE TITLE
grpc settings

### ISSUE THREAD

**Issue by kellyseeme** [apache/apisix#9480]
### Description

when use dashboard in apisix 2.15,setting for the upstream schema is grpc,but why i can't  access it or how can i access?
the grpc client error is lost connection error,connection closed,but use the grpc client to access the grpc server is ok.

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Hazel6869** [comment]
@kellyseeme Hi can you give me more info about  your operation,  such as your configuration  
screenshot and your  curl  response and log？

**Comment by Sn0rt** [comment]
@kellyseeme  can you provider the reproduce step help us to solve this promble ?

if you not provider the crucial can we close this issus at next week ?
