### ISSUE TITLE
docs: consolidate mTLS docs

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9485]
### Current State

mTLS information are scattered in different places.
* [Tutorials - Configure mTLS for client to APISIX](https://apisix.apache.org/docs/apisix/tutorials/client-to-apisix-mtls/)
* [Others - Mutual TLS Authentication](https://apisix.apache.org/docs/apisix/mtls/), which includes instructions to configure mTLS between
  * APISIX and Admin API
  * APISIX and etcd
  * APISIX and client (repeated)
  * APISIX and Upstream

### Desired State

Discuss how can organize and consolidate docs and action on the plan

**Comment by Arghyahub** [comment]
You want the entire documentation of Mutual TLS Authentication (from others) to be added to Tutorials
Did I get it right?

**Comment by kayx23** [comment]
More of an open discussion of what makes sense for all over "what I want". From a user perspective I find docs on this topic on this site pretty scattered. Feel free to provide your POV.
