### ISSUE TITLE
feat: As a user, I want the test of HEC logger with some real cases, so that

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#9489]
### Description

now the test cases of the HEC logger are mock.  I want to covert those tests with really.

now the vector supports the HEC source already. 

https://vector.dev/docs/reference/configuration/sources/splunk_hec/
https://apisix.apache.org/docs/apisix/plugins/splunk-hec-logging/

**Comment by Revolyssup** [comment]
Can you assign this to me?

**Comment by jiangfucheng** [comment]
Now, Partial test cases use splunk server as the real log server and others use mock server,  Maybe we replace these server address to splunk server is enough? Do we need use vector as the hec logger server?
https://github.com/apache/apisix/blob/35ea74ee8b7af5c4e3040914d5d535c20d7f7b8b/ci/pod/docker-compose.plugin.yml#LL191C10-L191C10

**Comment by Revolyssup** [comment]
> Now, Partial test cases use splunk server as the real log server and others use mock server, Maybe we replace these server address to splunk server is enough? Do we need use vector as the hec logger server? https://github.com/apache/apisix/blob/35ea74ee8b7af5c4e3040914d5d535c20d7f7b8b/ci/pod/docker-compose.plugin.yml#LL191C10-L191C10

I have made changes locally to replace those partial mock tests. Once your fix around splunk logger gets merged, I will create the PR
