### ISSUE TITLE
help request: apisix go-runner rewrite response body max length 16mb problem occurred

### ISSUE THREAD

**Issue by yyl-code** [apache/apisix#9490]
### Description

2023/05/16 10:37:24 [error] 58#58: *1773 lua entry thread aborted: runtime error: ...apisix//deps/share/lua/5.1/flatbuffers/compat_luajit.lua:90: attempt to perform arithmetic on local 'd' (a nil value)
stack traceback:
coroutine 0:
	...apisix//deps/share/lua/5.1/flatbuffers/compat_luajit.lua: in function 'HeadersLength'
	/usr/local/apisix/apisix/plugins/ext-plugin/init.lua:605: in function </usr/local/apisix/apisix/plugins/ext-plugin/init.lua:480>
	/usr/local/apisix/apisix/plugins/ext-plugin/init.lua:841: in function 'rpc_call'
	/usr/local/apisix/apisix/plugins/ext-plugin/init.lua:873: in function 'phase_func'
	/usr/local/apisix/apisix/plugin.lua:1094: in function 'run_plugin'
	/usr/local/apisix/apisix/init.lua:582: in function 'http_access_phase'

apisix golang plugin write data max > 16m 

### Environment

- APISIX version (run apisix version):3.1.0
- Operating system (run uname -a):docker centos
- OpenResty / Nginx version (run openresty -V or nginx -V):openresty/1.21.4.1
- etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):3.4.15
- APISIX Dashboard version, if relevant:3.0.0
- Plugin runner version, for issues related to plugin runners: golang-runner v0.5.0
- LuaRocks version, for installation issues (run luarocks --version):5.1.0

**Comment by Hazel6869** [comment]
@yyl-code Hi, what is your operate, and what is your needs?

**Comment by Sn0rt** [comment]
@yyl-code can you provider the reproduce step help us to solve this promble ?

**Comment by yyl-code** [comment]
@Sn0rt There will be an exception when the rewriting response body is greater than 16mb in the go-plugin.

**Comment by Sn0rt** [comment]
got it . I will move this issue to backlog. and take a look.

**Comment by Sn0rt** [comment]
not support bigger than 16M
