### ISSUE TITLE
Missing space before the appended originating IP with the `real-ip` plugin

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9494]
### Description

There should be a space before the appended originating client IP
![image](https://github.com/apache/apisix/assets/39619599/4b2c1fe9-d1a7-41d9-a8dc-25a8ec37b961)

### Steps to Reproduce

```
curl "http://127.0.0.1:9180/apisix/admin/routes" -H "X-API-KEY: xxx" -X PUT -d '
{
  "id": "getting-started-anything",
  "uri": "/anything",
  "upstream" : {
    "type": "roundrobin",
    "nodes": {
      "httpbin.org": 1
    }
  }
}'
```
```
curl http://127.0.0.1:9180/apisix/admin/global_rules/1 -H "X-API-KEY: xxx" -X PUT  -d '{
   "plugins":{
      "real-ip":{
         "source": "http_x_forwarded_for"
      }
   }
}'
```
```
curl "http://127.0.0.1:9080/anything" -H "x_forwarded_for: 1.2.3.48"
```

### Environment

- APISIX version: 3.3

**Comment by zccabb** [comment]
Can you assign this problem to me？

**Comment by zccabb** [comment]
I think you can use
```shell
curl "http://127.0.0.1:9080/anything" -H "X-Forwarded-For: 1.2.3.48"
```
this is because of

https://github.com/apache/apisix/blob/070f15fe773f4d27df7a51996c5cc1da87951c6d/apisix/plugins/real-ip.lua#L91-L95

You can try it first and let me know if you have any more questions.

**Comment by kayx23** [comment]
Hi @zccabb , your command with `X-Forwarded-For` works as intended. 

I got the idea of `x_forwarded_for` from https://github.com/apache/apisix/issues/9433 and [the doc](https://apisix.apache.org/docs/apisix/plugins/real-ip/)

**Comment by zccabb** [comment]
I think you can use
curl "http://127.0.0.1:9080/anything" -H "X-Forwarded-For: 1.2.3.48"
this is because of

https://github.com/apache/apisix/blob/070f15fe773f4d27df7a51996c5cc1da87951c6d/apisix/plugins/real-ip.lua#L91-L95

You can try it first and let me know if you have any more questions.

This may be a bug, I need to confirm it

**Comment by mscb402** [comment]
I believe this may be a bug with httpbin. Firstly, it seems that you are sending the wrong header - it should be `x-forwarded-for`, not `x_forwarded_for`. However, it appears that httpbin is still able to process the `x_forwarded_for` header for the sake of compatibility. It seems possible that there is a bug related to this compatibility feature. As a solution, you could try the following: 
```
curl http://httpbin.org/anything -H "x-forwarded-for: 1.2.3.111" -v -H 'x_forwarded_for: 1.1.1.1'
```
Send request without to APISIX. And you will get the same result below:
```
*   Trying 54.173.69.67:80...
* Connected to httpbin.org (54.173.69.67) port 80 (#0)
> GET /anything HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.74.0
> Accept: */*
> x-forwarded-for: 1.2.3.111
> x_forwarded_for: 1.1.1.1
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 17 May 2023 09:10:57 GMT
< Content-Type: application/json
< Content-Length: 361
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
<
{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Host": "httpbin.org",
    "User-Agent": "curl/7.74.0",
    "X-Amzn-Trace-Id": "Root=1-64649a1f-23d29ac7700c8fc15eac7054"
  },
  "json": null,
  "method": "GET",
  "origin": "1.2.3.111, 61.232.56.241,1.1.1.1",
  "url": "http://httpbin.org/anything"
}
```

**Comment by mscb402** [comment]
And this is HTTP Standand RFC: https://www.rfc-editor.org/rfc/rfc9110.html#section-16.3.1-6.2
> Field name:
The requested field name. It MUST conform to the field-name syntax defined in [Section 5.1](https://www.rfc-editor.org/rfc/rfc9110.html#fields.names), and it SHOULD be restricted to just letters, digits, and **hyphen ('-') characters**, with the first character being a letter.

**Comment by kayx23** [comment]
I'll leave it for you all to decide if this is a bug or something to improve on.

I noticed this when into an issue for another user [as mentioned earlier](https://github.com/apache/apisix/issues/9494#issuecomment-1550842387)

@mscb402 Thanks for the reference. But sound like we should enforce some sort of format check, rather than trusting users to do the right thing?

**Comment by Revolyssup** [comment]
@kayx23 As mentioned [here](https://github.com/apache/apisix/issues/9494#issuecomment-1551039427), I don't think its a bug with APISIX. What sort of format checking are you proposing here?

**Comment by kayx23** [comment]
I was referring to a check to warn users that they should use a hyphen instead of an underscore in `x_forwarded_for`. If this check is considered unnecessary, feel free to close the issue. Thanks.

**Comment by Revolyssup** [comment]
> I was referring to a check to warn users that they should use a hyphen instead of an underscore in `x_forwarded_for`. If this check is considered unnecessary, feel free to close the issue. Thanks.

Hmm, I think this slash is part of official spec as described here https://github.com/apache/apisix/issues/9494#issuecomment-1551048665 so is common knowledge. Therefore we can close this issue.
