### ISSUE TITLE
help request: 如何修改error.log的日志格式

### ISSUE THREAD

**Issue by Bigwen-1** [apache/apisix#9498]
### Description

在config.yaml有看到access_log_format来修改access.log格式，不清楚如何修改error.log

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by ronething** [comment]
@Bigwen-1 Hi, there is no error log format to modify.

**Comment by tokers** [comment]
The error.log format is fixed and you cannot tweak it.

**Comment by xuchmao** [comment]
try ngx.log

**Comment by lingsamuel** [comment]
Close, as answered. If there are any further questions, feel free to reopen or file a new issue.
