### ISSUE TITLE
docs: invalid md file links

### ISSUE THREAD

**Issue by AnattaGuo** [apache/apisix#9500]
### Current State

1. Click the `Getting Started` link. 

![image](https://github.com/apache/apisix-website/assets/17614321/97576b81-96b1-456f-8d28-b0410dcb64aa)

2. The `404 Page Not Found` appears.

![image](https://github.com/apache/apisix-website/assets/17614321/69316a7c-ee88-4110-807d-ddb4b87c5416)

### Desired State

Click`Getting Started`,  the page should redirect to **Getting Started**.

**Comment by navendu-pottekkat** [comment]
Thanks for opening the issue and fixing it. Approved the PR.
