### ISSUE TITLE
bug: when proxy redis,there is a coroutine leak

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9511]
### Current Behavior

<img width="1307" alt="image" src="https://github.com/apache/apisix/assets/10181098/d6cdd0e1-56bb-4eaf-9fa3-ffe324a35d42">

### Expected Behavior

when client close the connection, the connection  state between client and apisix  should be closed or time-wait , that is the command `netstat -an | grep -E "6379|9100" | grep ESTABLISHED | wc -l`   result is  0

### Error Logs

2023/05/19 09:43:50 [error] 68280#3244386: *2113 stream [lua] init.lua:472: from_upstream(): failed to handle upstream: closed while prereading client data, client: 127.0.0.1, server: 0.0.0.0:9100

<img width="1723" alt="image" src="https://github.com/apache/apisix/assets/10181098/3a231d7f-2991-4a5a-8249-5e635c57d4d5">

### Steps to Reproduce

1.enable the stream proxy and enable the redis xrpc protocol in config.yaml
<img width="326" alt="image" src="https://github.com/apache/apisix/assets/10181098/27e345af-5c23-4129-8b48-b691b2ce3918">

2.create the stream route 
`
curl --location --request PUT 'http://127.0.0.1:9180/apisix/admin/stream_routes/1' \
--header 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' \
--header 'Content-Type: application/json' \
--data '{
    "server_port": 9100,
    "upstream": {
        "nodes": {
            "127.0.0.1:6379": 1
        },
        "type": "roundrobin",
        "name":"redis0000"
    },
    "protocol":{
        "name":"redis"
    }
}'

`
<img width="624" alt="image" src="https://github.com/apache/apisix/assets/10181098/024c387b-7df9-4467-a630-1b6bf31aa897">

3. on the redis client such as 'another Redis Desktop Manager' , open the connection, the connection config like this:
<img width="887" alt="image" src="https://github.com/apache/apisix/assets/10181098/45c65e20-bfce-4032-bbc6-ff3f6e36e2a4">

5.  View the current connection
<img width="1095" alt="image" src="https://github.com/apache/apisix/assets/10181098/4dffc352-e405-4383-a4aa-abe8f540c40c">

7.  on the redis client,close the connection.
<img width="735" alt="image" src="https://github.com/apache/apisix/assets/10181098/8360bab9-9acd-49dd-a6f9-69d82ac8445f">

9. view the current connection
<img width="1248" alt="image" src="https://github.com/apache/apisix/assets/10181098/d3eb2491-59a2-48cc-ae24-911a53d4f49b">

### Environment

- APISIX version (run `apisix version`):  3.2 
- Operating system (run `uname -a`):   Darwin localhost 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  apisix base,openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
let me take a look

**Comment by shreemaan-abhishek** [comment]
I could reproduce this issue. But I was wondering what made you think a coroutine was leaked.

**Comment by zzqCh** [comment]
> I could reproduce this issue. But I was wondering what made you think a coroutine was leaked.

I want to proxy the four layer protocol, so I wan't to  verify the xrpc function, after the client closed the connection, I discovered that network connections still exist. I don't know much about Lua，but in other languages, the proxy function normally  developed using coroutine, so i think the coroutine is leak.

**Comment by shreemaan-abhishek** [comment]
@monkeyDluffy6017 is it really necessary to close the connection between apisix and client when the connection between apisix and redis is lost? 🤔

**Comment by zzqCh** [comment]
> 



> @monkeyDluffy6017 is it really necessary to close the connection between apisix and client when the connection between apisix and redis is lost? 🤔



yeah, please consider the following scenario
If the same client is opened multiple times(means connect multiple times), multiple new connection will be created, but the old connection cannot be released either, finally, resources will be depleted

**Comment by shreemaan-abhishek** [comment]
@zzqCh. No, it does not make sense. Using the stream route, APISIX will proxy requests from some specific origins (according to the stream_route configuration) to a given upstream. This should be regardless of any client using that specified port number and ip address pair. I hope I made sense to you.

**Comment by monkeyDluffy6017** [comment]
Hi @shreemaan-abhishek, I'm not very familiar with xrpc, but i think the connection should be closed too

**Comment by zzqCh** [comment]
> @zzqCh. No, it does not make sense. Using the stream route, APISIX will proxy requests from some specific origins (according to the stream_route configuration) to a given upstream. This should be regardless of any client using that specified port number and ip address pair. I hope I made sense to you.

I think  the behavior of stream proxy and websocket proxy should be consistent. In the scenario of websocket proxy ,when the client or server closed the connection, the other side will close the connection too.

**Comment by moonming** [comment]
@nic-chen please take a look this issue

**Comment by nic-chen** [comment]
If the client has explicitly closed the connection with APISIX, and the connection still exists, it is a bug. I will try to reproduce it in the afternoon and determine whether it is a APISIX bug.

**Comment by nic-chen** [comment]
@zzqCh  By the way, is it convenient to leave an email address or other contact information? Or you can contact me by mail(chenjunxu6@gmail.com). Maybe we could explore this issue in more depth.

**Comment by nic-chen** [comment]
Here is my test process(Same configurations with yours, and APISIX version is 3.2.1):

Connect to redis through APISIX's proxy:
<img width="387" alt="image" src="https://github.com/apache/apisix/assets/33000667/c82d5404-31b2-4d42-9261-ee12dc73fb26">

In the APISIX container, we could see connections on ports 9100 and 2379:
![img_v2_f9120f08-fe0a-4f31-b712-56074761698g](https://github.com/apache/apisix/assets/33000667/2f76a6dd-dcdb-404c-afc5-8f9b550a634e)

Use the `quit` command to close the connection:
<img width="245" alt="image" src="https://github.com/apache/apisix/assets/33000667/9d3c2372-db3e-4f82-98a9-16eb3f8983d2">

We could see that the connection on port 9100 no longer exists:
<img width="615" alt="image" src="https://github.com/apache/apisix/assets/33000667/de1dca87-2e48-48b0-adbe-40e1b8a69526">

After a while, the connection on port 6379 also disappeared:
<img width="586" alt="image" src="https://github.com/apache/apisix/assets/33000667/cf4c9337-4082-43f0-846f-cc4d75627d9f">


Close the connection by `control + c` has the same behavior.


So the bug should not exist, and you need to determine whether your client is really disconnected from APISIX. @zzqCh

**Comment by Sn0rt** [comment]
14 july @Sn0rt
