### ISSUE TITLE
help request: 如何使用https

### ISSUE THREAD

**Issue by xiaolei000129** [apache/apisix#9519]
### Description

我的前端使用了https 但是后端接口还是http://xxx:8090 导致无法使用，看了一些文章，但是还是没有弄明白

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by xiaolei000129** [comment]
解决了吗？我也遇到这个问题了，我们的前端是https 但是我的接口是http://xxx:9080/不知道怎么用https 现实

**Comment by zccabb** [comment]
You can refer to this document
https://apisix.apache.org/zh/docs/apisix/tutorials/client-to-apisix-mtls/
It's a little bit about how to configure mTLS, maybe that helps,

**Comment by An-DJ** [comment]
Hi, a new doc about how to configure HTTPS between client and APISIX is published here:

https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-https-between-client-and-apisix

Maybe it is helpful to you : ) @xiaolei000129

**Comment by xiaolei000129** [comment]
升级版本解决了
