### ISSUE TITLE
help request: how can i get the user from cas-auth

### ISSUE THREAD

**Issue by seominho77** [apache/apisix#9524]
### Description

 my route use cas-auth plugin， my service how get userinfo。

### Environment

- APISIX version (run `apisix version`): 3.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please give some more elaborate explanations. For example, what type of user info do you want?

**Comment by DerekHou** [comment]
I guess the user info which [seominho77](https://github.com/seominho77) needs is in the "<cas:user></cas:user>". The services which are proxied may need this info to get detail user information
