### ISSUE TITLE
bug: in mTLS, clients can establish connection with server by expired cert in session resumption.

### ISSUE THREAD

**Issue by wangkpot** [apache/apisix#9525]
### Current Behavior

In mTLS, clients can establish connection with server by expired cert in session resumption.

### Expected Behavior

In mTLS, clients can't establish connection with server by expired cert in session resumption.

### Steps to Reproduce

1. client with valid cert send request and receive response successfully in mTLS at first time;
2. when the cert is expired,  clients still can establish connection with server in session resumption.

### Environment

- APISIX version (run `apisix version`): 2.13.1
- Operating system (run `uname -a`): Centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1

**Comment by tokers** [comment]
By default, APISIX/Nginx won't verify the client strictly. If that the case you desire, try to enable `ssl_verify_client`.

**Comment by tokers** [comment]
> By default, APISIX/Nginx won't verify the client strictly. If that the case you desire, try to enable `ssl_verify_client`.

PS, we may consider to support a dynamic flag in the `client-control` plugin.

**Comment by wangkpot** [comment]
> By default, APISIX/Nginx won't verify the client strictly. If that the case you desire, try to enable `ssl_verify_client`.

Even if enable `ssl_verify_client`, the above problem still occurs.

**Comment by An-DJ** [comment]
Hi @wangkpot , : )
a new doc about how to configure mTLS between client and APISIX is published there:
https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-mtls-between-client-and-apisix

Could you refer this doc and offer an example which can be easily reproduced? That may help to diagnose if it is a bug.

**Comment by wangkpot** [comment]
> Hi @wangkpot , : ) a new doc about how to configure mTLS between client and APISIX is published there: https://docs.api7.ai/apisix/how-to-guide/traffic-management/tls-and-mtls/configure-mtls-between-client-and-apisix
> 
> Could you refer this doc and offer an example which can be easily reproduced? That may help to diagnose if it is a bug.

ok. there are steps to reproduce：
1. configure mTLS between client and APISIX correctly；
2. client send request with client-cert which expires in five minutes, and client receive response successfully；
3. five minutes later, client send request with **expired** client-cert  still receive response successfully(tls resumption happens here).

**Comment by tokers** [comment]
As per the RFC 5426:

> Sessions cannot be resumed unless both the client and server agree.
   If either party suspects that the session may have been compromised,
   or that certificates may have expired or been revoked, it should
   force a full handshake.

It seems that APISIX should force a full handshake when the session is compromised. Currently, APISIX uses the built-in Nginx way to store and reuse TLS sessions. If we want to fix this behavior, we may need some effort to change the Nginx core.

**Comment by tokers** [comment]
> 

I considered for a while, even we don't change the Nginx core, we may need to tweak the way we set the session timeout, e.g., parsing the certificates (both the client and server), getting the certificate expiration time, and taking the shortest time (of course, also respect the `ssl_session_timeout` directive) as the timeout.

**Comment by wangkpot** [comment]
> > 
> 
> I considered for a while, even we don't change the Nginx core, we may need to tweak the way we set the session timeout, e.g., parsing the certificates (both the client and server), getting the certificate expiration time, and taking the shortest time (of course, also respect the `ssl_session_timeout` directive) as the timeout.

yep, that's what I thought.

**Comment by Sn0rt** [comment]
14 july @Sn0rt

**Comment by Sn0rt** [comment]
will reproduce in 2.13 @sn0rt

**Comment by Sn0rt** [comment]
@wangkpot 

We are now using a fixed ssl_session_timeout:
https://github.com/apache/apisix/blob/455d5bfac93ed1b16bc9d0209bb29143c22a5585/apisix/cli/ngx_tpl.lua#L626

So it is indeed possible that the cert expires but the ssl session can still be reused.

The solution is indeed as what @tokers said before, a measure of cert expiration is needed to dynamically change ssl_session_timeout, which requires a certain amount of work:

https://github.com/apache/apisix/issues/9525#issuecomment-1608851793

Based on the above reasons, it is concluded that:

APISIX will ignore this issues.

In a production environment, certificates are generally replaced 30 days before expiration.

**Comment by wangkpot** [comment]
fine.
