### ISSUE TITLE
request help: Any plan for supporting the SM1/SM2/SM3/SM4 cryptographic algorithm?

### ISSUE THREAD

**Issue by Miss-you** [apache/apisix#953]
### Environment

* apisix version (cmd: `apisix version`):
* OS:

**Comment by totemofwolf** [comment]
As i know, Chinese cryptographic algorithm `SM2 SM3 SM4` are included in official openssl 1.1.1, 
so you should use at least openssl 1.1.1 (when compiled with openresty):
refer:
https://www.openssl.org/blog/blog/2018/09/11/release111/

and you should compile and patch openssl 1.1.1 refered to: 
https://github.com/apache/incubator-apisix-docker/blob/master/alpine/Dockerfile

----

refered to issues from https://github.com/jntass/TASSL-1.1.1b/issues/12

`EC` is stand for `SM2`

```
bash-4.4# bin/openssl
OpenSSL> ciphers
...:ECC-SM4-SM3:ECDHE-SM4-SM3:...
```

After that you could add these ciphers to apisix's config.yaml (not tested),
Welcome PR.

**Comment by moonming** [comment]
OpenResty not support openssl 1.1.1 yet :(

**Comment by totemofwolf** [comment]
It is said that OpenResty 1.17.8.1 RC1 has feature: 
`Updated the ngx_ssl.get_tls1_version_str() API to recognize TLS 1.3 connection.`

refer to :
http://openresty.org/cn/ann-1017008001rc1.html

**Comment by moonming** [comment]
The new version of OpenResty is 1.17, which supports openssl 1.1.1.
How should we support it? I'm not familiar with SM1/SM2/SM3/SM4.
 What do you guys think? @spacewander @totemofwolf @Miss-you

**Comment by spacewander** [comment]
I am not an expert of SMx algorithms. But it seems that @toruneko's https://github.com/toruneko/lua-resty-crypto supports them, though it doesn't detect if the OpenSSL version is high enough.

**Comment by membphis** [comment]
we can get the OpenSSL version in CLI

**Comment by toruneko** [comment]
I'm implement `sm3`, `sm4` algorithms  on pure lua, but `sm2` not yet. So the `lua-resty-crypto` can not runs `sm2` with openssl which version under 1.1.1 
About detect version,  [version.lua](https://github.com/toruneko/lua-resty-crypto/blob/master/lib/resty/crypto/version.lua) can help us get major, minor, and patch version.



Because of I joined a 996 company recently, the project only bugfix now.  : (

**Comment by moonming** [comment]
@spacewander @toruneko do you know how to integrate the sm2 cert in Nginx/OpenResty? I did a search and it looks like a separate Nginx C module is needed.

**Comment by aifeiasdf** [comment]
> I am not an expert of SMx algorithms. But it seems that @toruneko's https://github.com/toruneko/lua-resty-crypto supports them, though it doesn't detect if the OpenSSL version is high enough.

It seem that this project can only do smX compute on L7 application, if I want to do smx handshake on L4 handshake, I have to implement extra C code on Nginx C module

**Comment by spacewander** [comment]
For people who are interested in the GMSSL support feature:
This task is in the TODO list but doesn't have a plan.

It looks like the modification of GMSSL has been merged into OpenSSL. But we have not tested it yet.

If someone is willing to sponsor the development of GMSSL support, please contact us.

**Comment by spacewander** [comment]
Found a new player BabaSSL for this area.

**Comment by moonming** [comment]
fixed by https://github.com/apache/apisix/pull/8389
