### ISSUE TITLE
May I ask how to remove X-Forwarded For X-Forwarded Host and other information to prevent upstream access

### ISSUE THREAD

**Issue by cverdela** [apache/apisix#9530]
### Description

May I ask how to remove X-Forwarded For X-Forwarded Host and other information to prevent upstream access

请问下如何去掉X-Forwarded-For   X-Forwarded-Host 等信息 不让上游获得

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
You can use `proxy-rewrite`'s `headers.remove` option.

<img width="863" alt="image" src="https://github.com/apache/apisix/assets/61597896/cbfc3667-d46c-4379-818b-a24b4c37cbd5">

https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by cverdela** [comment]
I have tried it before

**Comment by shreemaan-abhishek** [comment]
If you were using forward auth or real ip plugins, you can change the plugin execution order and then retry.

**Comment by cverdela** [comment]
router
```
{
    "name": "dgc",
    "uris": ["/*"],
    "upstream": {
        "scheme": "http",
        "type": "roundrobin",
        "nodes": {
            "10.154.97.26": 1
        }
    },
    "plugins": {
       
        "proxy-rewrite": {
            "_meta": {
            	"priority": 1
        	},
        	"host": "10.157.95.18",
            "headers": {
                "remove": [
                    "X-Forwarded-Host"
                ]
            }
        }
    }

}
```


wireshark


`Hypertext Transfer Protocol
    GET /SALE/0200_012_FMHITEM_GET?page_num=1&page_size=1 HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET /SALE/0200_012_FMHITEM_GET?page_num=1&page_size=1 HTTP/1.1\r\n]
            [GET /SALE/0200_012_FMHITEM_GET?page_num=1&page_size=1 HTTP/1.1\r\n]
            [Severity level: Chat]
            [Group: Sequence]
        Request Method: GET
        Request URI: /SALE/0200_012_FMHITEM_GET?page_num=1&page_size=1
            Request URI Path: /SALE/0200_012_FMHITEM_GET
            Request URI Query: page_num=1&page_size=1
                Request URI Query Parameter: page_num=1
                Request URI Query Parameter: page_size=1
        Request Version: HTTP/1.1
    Host: 10.157.95.18\r\n
    X-Real-IP: 172.27.0.1\r\n
    X-Forwarded-For: 172.27.0.1\r\n
    X-Forwarded-Proto: http\r\n
    X-Forwarded-Host: localhost\r\n
    X-Forwarded-Port: 9080\r\n
    cache-control: no-cache\r\n
    Postman-Token: e4db838e-b1c7-4eb9-aff5-6fba38024c09\r\n
    User-Agent: PostmanRuntime/6.4.1\r\n
    Accept: */*\r\n
    cookie: saplb_*=(znbb-piq-01_PIQ_00)2115550; JSESSIONID=nSU_zzPOlkLzdaFeaWyzpu-pmENBiAHeRyAA_SAPXvsAyyytyaJax6W6v32HFdJ1; JSESSIONMARKID=S4KK8ADl8ke3u7R2HtHnBkpR-ppFISB03eA95HIAA\r\n
    accept-encoding: gzip, deflate\r\n
    \r\n
    [Full request URI: http://10.157.95.18/SALE/0200_012_FMHITEM_GET?page_num=1&page_size=1]
    [HTTP request 1/1]
    [Response in frame: 19]
`

**Comment by cverdela** [comment]
so it was a bug?

**Comment by shreemaan-abhishek** [comment]
@cverdela No this is not a bug but by design.

`forward-auth` will always be executed after `proxy-rewrite` because `forward-auth` gets executed in the `access` phase of nginx and `proxy-rewrite` gets executed in the `rewrite` phase.

<img width="851" alt="image" src="https://github.com/apache/apisix/assets/61597896/5cce73da-682e-44a9-9d66-3aca9a1c1e6f">


[Learn more](https://api7.ai/learning-center/openresty/knowledge-of-nginx-used-in-openresty#execution-phase)

**Comment by cverdela** [comment]
I only want to remove  X-Forwarded-Host

**Comment by shreemaan-abhishek** [comment]
Take a look at the dockerfile here: https://github.com/apache/apisix-docker/blob/master/debian/Dockerfile

**Comment by cverdela** [comment]
Sorry, I didn't understand what you meant

**Comment by shreemaan-abhishek** [comment]
sorry wrong window.

**Comment by shreemaan-abhishek** [comment]
@cverdela by the way, you can use the `serverless-post-function` plugin to achieve your goal:

```
        "serverless-post-function": {
            "phase": "access",
            "functions" : ["return function()  return require(\"apisix.core\").request.set_header(ctx, "X-Forwarded-For", ""); end"]
        }
```

**Comment by cverdela** [comment]
I  want to remove X-Forwarded-Host  not set it  null

**Comment by cverdela** [comment]
Some upstream services may determine whether they have been proxied or not based on the X-Forwarded-Host header and respond differently accordingly. I hope that apisix can be agnostic to this when communicating with them

**Comment by cverdela** [comment]
Some upstream services may determine whether they have been proxied or not based on the X-Forwarded-Host header and respond differently accordingly. I hope that apisix can be agnostic to this when communicating with them

**Comment by cverdela** [comment]
For example, some upstream services may have an HMAC-like verification process. They detect the X-Forwarded-Host header and assume that relevant information needs to be included in the signature. For consumers who previously made direct calls, this requires a change in behavior.

**Comment by shreemaan-abhishek** [comment]
> I want to remove X-Forwarded-Host not set it null

In theory, setting the header as an empty string i.e. `""`. should remove the header.

**Comment by cverdela** [comment]
nvalid request body: Expected comma or array end but found invalid token at character 394

**Comment by shreemaan-abhishek** [comment]
@cverdela which plugins are you using?

**Comment by cverdela** [comment]
only this
```
{
    "name": "dgc",
    "uris": ["/*"],
    "upstream": {
        "scheme": "http",
        "type": "roundrobin",
        "nodes": {
            "10.154.97.26": 1
        }
    },
    "plugins": {
       
        "serverless-post-function": {
            "phase": "access",
            "functions" : ["return function()  return require(\"apisix.core\").request.set_header(ctx, \"X-Forwarded-For\", \"\"); end"]
        }
    }

}
```

**Comment by acx-1** [comment]
Hello! you can try this.It works on me. @cverdela

```lua
{
    "plugins": {
        "serverless-post-function": {
            "phase": "access",
            "functions": [
                "return function()  ngx.var.var_x_forwarded_for=''; end"
            ]
        }
    }
}
```

**Comment by kayx23** [comment]
Alternatively you can [rewrite with `proxy-rewrite`](https://github.com/apache/apisix/pull/8200) to something trivial?  cc: @monkeyDluffy6017

**Comment by monkeyDluffy6017** [comment]
@cverdela have you solved your problem?

**Comment by monkeyDluffy6017** [comment]
considered resolved

**Comment by dylanoy** [comment]
I've tried all the suggestions mentioned above, including:
```
ngx.req.proxy_set_header('X-Forwarded-For', '127.0.0.1')`
```
```
ngx.var.var_x_forwarded_for='127.0.0.1'
```
```
require('apisix.core').request.set_header(ctx, 'X-Forwarded-For', '')
```
and using
```json
"proxy-rewrite": {
	"headers": {
		"remove": [
			"X-Forwarded-For",
			"X-Real-IP"
		]
	}
}
```

However, none of these methods were able to remove the X-Forwarded-For header sent to the upstream server or modify its value. I also couldn't change the value of X-Real-IP.

Finally, I found a solution by referring to the realip module. Using the following configuration, I was able to successfully modify the X-Real-IP and X-Forwarded-For headers sent to the upstream server:
```json
"serverless-post-function": {
	"functions": [
		"return function() local _, client = pcall(require, 'resty.apisix.client')\nclient.set_real_ip('127.0.0.1', 80); end"
	],
	"phase": "rewrite"
}
```

I'm sharing this here as a reference for anyone who encounters the same issue or needs to modify these two header values.

Hope everyone has a wonderful day

**Comment by typ431127** [comment]
> 你好！你可以试试这个。它对我有用。@cverdela
> 
> ```lua
> {
>     "plugins": {
>         "serverless-post-function": {
>             "phase": "access",
>             "functions": [
>                 "return function()  ngx.var.var_x_forwarded_for=''; end"
>             ]
>         }
>     }
> }
> ```

有用，我解决了针对x_forwarded_host的校验问题
