### ISSUE TITLE
feat: Check external plugin readiness on APISIX startup

### ISSUE THREAD

**Issue by joyyir** [apache/apisix#9531]
### Description

I got a `503` response when apisix is ready and external plugin is not ready.
The current version of apisix helm chart uses [`tcpSocket` for readiness probe](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/_pod.tpl#L108), but this is not sufficient when using external plugins as it does not check readiness of external plugins.
In my opinion, A mechanism is needed which check the readiness of external plugin on APISIX startup time.

**Comment by jiangfucheng** [comment]
In current logic, APISIX will create `ext-plugin` child process in `init_worker` phase, if the child process start failed, it will print error logs and try to restart the `ext-plugin` process.

Check the child process if alive is easy, but it seems complicated to stop nginx in `init_worker` phase.
Do you have any suggestions?
