### ISSUE TITLE
Cannot build APISIX image 

### ISSUE THREAD

**Issue by trong11** [apache/apisix#9541]
### Description

When trying to build my custom image from source code, i ran the command `make deps` and encounter this error, can someone help me ? 
```
Error: Failed installing dependency: https://luarocks.org/luasec-0.9-1.src.rock - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/share/openssl/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
make: *** [Makefile:152: deps] Error 1

```

**Comment by shreemaan-abhishek** [comment]
Check this out: https://luarocks.org/modules/zhaozg/openssl

You need to install the openssl luarock manually. Btw, which OS are you running on?

**Comment by trong11** [comment]
> Check this out: https://luarocks.org/modules/zhaozg/openssl
> 
> You need to install the openssl luarock manually. Btw, which OS are you running on?

Im running on Ubuntu

**Comment by shreemaan-abhishek** [comment]
Then it should not be much difficult.

**Comment by trong11** [comment]
Can you show me how ?

**Comment by shreemaan-abhishek** [comment]
Take a look at the dockerfile here: https://github.com/apache/apisix-docker/blob/master/debian/Dockerfile

**Comment by trong11** [comment]
> Take a look at the dockerfile here: https://github.com/apache/apisix-docker/blob/master/debian/Dockerfile

Can this help me build the custom version of APISIX or the original one?

**Comment by shreemaan-abhishek** [comment]
> Can this help me build the custom version of APISIX or the original one?

My bad, the given dockerfile can build the original one but a local build is not possible.

I have created a PR for supporting docker image creation from local codebase. #9586

**Comment by leslie-tsang** [comment]
New PR in https://github.com/apache/apisix-docker/pull/476 ?

**Comment by shreemaan-abhishek** [comment]
@lingsamuel, yes.
