### ISSUE TITLE
bug: java plugin runner on postfilter can not get response body

### ISSUE THREAD

**Issue by sjh19950115** [apache/apisix#9542]
### Current Behavior

use java plugin runner to write plugins, use ext-plugin-post-resp plugin to configure filter,  but in postFilter I can not get response body. use lua can get body by ngx.arg[1]. I also see the variable in apisix variable and nginx variable to add the value by requiredVars method , but not find

### Expected Behavior

use java plugin runner , we can get response body by the postFilter method

### Steps to Reproduce

1.write  java plugin runner filter extend PluginFilter
2.Override postFilter method
3.can not get response body

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Vacant2333** [comment]
hello can u provide the plugin content
