### ISSUE TITLE
feat: As a user, I want to mirror some request by route not all, so that I found the proxy mirror plugin, but find it can't mirror by route?

### ISSUE THREAD

**Issue by swcumt** [apache/apisix#9543]
### Description

I want mirror request by route. For example I just want mirror `/foo/*` to test server  while route `/bar/*` not mirror

**Comment by Revolyssup** [comment]
You can add a route for `uri: /foo/* with proxy-mirror plugin configured. https://apisix.apache.org/docs/apisix/plugins/proxy-mirror/#enabling-the-plugin

**Comment by lingsamuel** [comment]
Closing this since
