### ISSUE TITLE
是否可以提供基于国密的docker镜像

### ISSUE THREAD

**Issue by zqge** [apache/apisix#9546]
### Description

能否提供国密tls的docker镜像，教程使用 apisix-base的版本，编译一直报错。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
Feel free to give the compilation error message to the community. : )

A detailed blog may be helpful to you: https://apisix.apache.org/zh/blog/2022/12/08/apisix-support-tongsuo/

**Comment by zqge** [comment]
> Feel free to give the compilation error message to the community. : )
> 
> A detailed blog may be helpful to you: https://apisix.apache.org/zh/blog/2022/12/08/apisix-support-tongsuo/

Can you provide a complete dockerfile file with tongsuo? Currently, it can execute build apisix base. sh normally, but the later documentation is incomplete. If you can provide a complete dockerfile file, I can compile it into an image myself

**Comment by zqge** [comment]
At present, after completing the steps in the tutorial, build apisix base. sh, we can deploy the Tongsuo version of OpenResty. The subsequent steps for installing apisix are to install it in source code, but we have encountered some problems.
![image](https://github.com/apache/apisix/assets/15939444/62e2eb34-6cdd-4d55-918a-d5cfe16fb72f)
