### ISSUE TITLE
ci: gets xds error when running

### ISSUE THREAD

**Issue by monkeyDluffy6017** [apache/apisix#9551]
### Current Behavior

https://github.com/apache/apisix/actions/runs/5084924232/jobs/9143791731?pr=9549
![image](https://github.com/apache/apisix/assets/9354193/e3cb20b7-8dc6-459c-a3d4-eced8c8ff822)

### Expected Behavior

No error when running ci

### Steps to Reproduce

Rerun the ci

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Please assign to me.

**Comment by monkeyDluffy6017** [comment]
Thanks @shreemaan-abhishek

**Comment by lingsamuel** [comment]
Any progress? @shreemaan-abhishek

**Comment by shreemaan-abhishek** [comment]
The fix for the XDS issues in the CI was expected to be solved by #9274. And in turn by #9559. The changes to `t/xds-library/config_xds.t` from #9559 are missing on the master branch.

Raised a PR: #9706
