### ISSUE TITLE
help request: docker 的镜像仓库在哪里。dockerhub 上搜不到了

### ISSUE THREAD

**Issue by EthanKk** [apache/apisix#9553]
### Description

docker 的镜像仓库在哪里。dockerhub 上搜不到了

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
Here: https://hub.docker.com/r/apache/apisix
