### ISSUE TITLE
bug: The "ext-plugin" plugin executes before custom plugins.

### ISSUE THREAD

**Issue by ipanocloud** [apache/apisix#9555]
### Current Behavior

`
  - api-restriction                # priority: 12003
  - ext-plugin-pre-req         # priority: 12000
  - request-id                     # priority: 11010
  - fault-injection                # priority: 11000
`
The "api-restriction " is custom plugin, priority: 12003. however ext-plugin-pre-req priority:12000
but ext-plugin-pre-req plugin before api-restriction executes

### Expected Behavior

The "api-restriction " before ext-plugin-pre-req plugin

### Error Logs

N/A

### Steps to Reproduce

1. apisix dashboard select one route to config.
2. add api-restriction
3. add ext-plugin-pre-req
4. use postman send request
5. but but . The ext-plugin-pre-req is before api-restriction execute.

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`):  3.10.0-1160.76.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> The ext-plugin-pre-req Plugin is for running specific external Plugins in the Plugin Runner before executing the built-in Lua Plugins.

https://apisix.apache.org/docs/apisix/plugins/ext-plugin-pre-req/#description

**Comment by Revolyssup** [comment]
@ipanocloud This is by design. If you want to run external plugin after the other plugins then you can use `ext-plugin-post-req`

**Comment by lingsamuel** [comment]
Close, as answered. If there are any further questions, feel free to reopen or file a new issue.
