### ISSUE TITLE
help request: Ignore the case of the uri

### ISSUE THREAD

**Issue by overstarry** [apache/apisix#9556]
### Description

 i want to ignore the case of the uri，such as： xx.com/A -> xx.com/a

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by overstarry** [comment]
`"serverless-pre-function": {
      "_meta": {
        "disable": false
      },
      "functions": [
        "return function(conf, ctx) ctx.var.uri= string.lower(ctx.var.uri);ngx.log(ngx.ERR, \"match uri \",  ctx.var.uri ); end"
      ],
      "phase": "access"
    }`

**Comment by overstarry** [comment]
@justinmclean

**Comment by shreemaan-abhishek** [comment]
I don't think this is supported yet.

**Comment by Revolyssup** [comment]
@overstarry the code you provided in serverless-pre-function is correct and works as expected. Its just the `ctx.vars` just holds variables for that context and is not updated by calling `set_uri`.

Here I used your configuration to test:
Without your configuration: 
![whennotok](https://github.com/apache/apisix/assets/43276904/0ac30526-14a8-4e2b-bbf6-1208e196bf43)

With your configuration
![whenok](https://github.com/apache/apisix/assets/43276904/6bc95be4-fe53-4fdf-a4ec-3d678c0bf617)

**Comment by overstarry** [comment]
What is the difference between ctx.var.uri = uri and ngx.req.set_uri (uri)? @Revolyssup

**Comment by Revolyssup** [comment]
> What is the difference between ctx.var.uri = uri and ngx.req.set_uri (uri)? @Revolyssup

ctx is just context passed by apisix to plugins to pass data internally among different phases of a request. Setting it does not have any effect on actual URI. You can think of it as just variable holder. So setting ctx.var.uri=uri wil just set that variable for this request whereas ngx.req.set_uri calls into openresty ngx API to actually set the request URI.

**Comment by overstarry** [comment]
ok，thanks
