### ISSUE TITLE
apisix3.3.0 need to support the rust environment

### ISSUE THREAD

**Issue by XW512** [apache/apisix#9558]
### Description

When I was compiling version 3.3.0 with make deps, I noticed the following issues:

apisix master-0 depends on lua-resty-mediador 0.1.2-1 (0.1.2-1 installed)
apisix master-0 depends on lua-resty-ldap 0.2.2-0 (not installed)
Installing https://luarocks.org/lua-resty-ldap-0.2.2-0.src.rock

lua-resty-ldap 0.2.2-0 depends on lua_pack 2.0.0-0 (2.0.0-0 installed)
lua-resty-ldap 0.2.2-0 depends on lpeg 1.0.2-1 (1.0.2-1 installed)
Warning: unmatched variable LUA_LIBDIR
make[1]: Entering directory `/tmp/luarocks_lua-resty-ldap-0.2.2-0-8tRJqa/lua-resty-ldap'
--- Build
CFLAGS: -O2 -fPIC
LIBFLAG: -shared
LUA_LIBDIR:
LUA_BINDIR: /usr/local/bin
LUA_INCDIR: /usr/local/include
--- Check Rust toolchain
The cargo is not installed
This rock contains the Rust code: make sure you have a Rust development environment installed and try again
make[1]: *** [all] Error 1
make[1]: Leaving directory `/tmp/luarocks_lua-resty-ldap-0.2.2-0-8tRJqa/lua-resty-ldap'

Error: Failed installing dependency: https://luarocks.org/lua-resty-ldap-0.2.2-0.src.rock - Build error: Failed building.
make: *** [deps] Error 1

Does the current version 3.3.0 need to rely on the rust environment to compile

### Environment

- APISIX version (run `apisix version`):  3.3.0
- Operating system (run `uname -a`):  centos7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.13
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):  3.8.0

**Comment by XW512** [comment]
I have checked version 3.1, and the version of lua rest ldap is 0.1.0-0, while the version of 3.3.0 is 0.2.2.0, which should be caused by this version of lua rest ldap

**Comment by An-DJ** [comment]
@XW512 You are right. The compilation of APISIX with recent versions relies on the rust toolchain. It is introduced by new version of lua-resty-ldap.

Found a related PR here: https://github.com/apache/apisix/pull/9254

According to the context, it is necessary to upgrade lua-resty-ldap to 0.2.2 to support the m2 chips.

**Comment by XW512** [comment]
> @XW512 You are right. The compilation of APISIX in recent versions relies on the rust toolchain. It is introduced by new version of lua-resty-ldap. (Ref: [api7/lua-resty-ldap#17](https://github.com/api7/lua-resty-ldap/pull/17))
> 
> Found a related PR here about why upgrading lua-resty-ldap to 0.2.2: #9254
> 
> According to the context, it is necessary to upgrade lua-resty-ldap to 0.2.2 to support the m2 chips.

Okay, thank you very much. I would like to ask if it is possible to control the lua-rest-ldap version reduction process through parameters. During compilation, this can reduce the dependency on Apisix

**Comment by Revolyssup** [comment]
This CI has be failing for quite a while due to this https://github.com/apache/apisix-docker/actions/workflows/apisix_dev_push_docker_hub.yaml

**Comment by An-DJ** [comment]
> I would like to ask if it is possible to control the lua-rest-ldap version reduction process through parameters. During compilation, this can reduce the dependency on Apisix

Now temporarily unable to do it, and is not recommended to do so. : )

Modules are introduced and upgraded to solve practical problems, such as `lua-resty-ldap` you mentioned. It just introduces an additional (popular) compilation toolchain.

If you're having trouble installing the build toolchain, feel free to ask the community to help you : )

**Comment by XW512** [comment]
> This CI has be failing for quite a while due to this https://github.com/apache/apisix-docker/actions/workflows/apisix_dev_push_docker_hub.yaml

The error message I compiled is the same, but it lacks a dependency on rust

**Comment by XW512** [comment]
> > I would like to ask if it is possible to control the lua-rest-ldap version reduction process through parameters. During compilation, this can reduce the dependency on Apisix
> 
> Now temporarily unable to do it, and is not recommended to do so. : )
> 
> Modules are introduced and upgraded to solve practical problems, such as `lua-resty-ldap` you mentioned. It just introduces an additional (popular) compilation toolchain.
> 
> If you're having trouble installing the build toolchain, feel free to ask the community to help you : )

I understand, but My idea is whether different operating systems can be packaged differently, which can reduce dependencies between different systems，If there are any issues, I will seek help from the community
