### ISSUE TITLE
bug: response_rewrite body_base64

### ISSUE THREAD

**Issue by jcarrasco-odf** [apache/apisix#9561]
### Current Behavior

I'm triying to configure 
"response-rewrite": {
      "body_base64": true
    }
 
to decode the body content but I always get 

config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer

### Expected Behavior

A response with the body content base64 decoded

### Error Logs

apisix 2023/05/27 21:36:52 [error] 54#54: *15874062 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 53#53: *15874058 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 55#55: *15874066 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 49#49: *15874052 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 52#52: *15874071 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 59#59: *15874056 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 51#51: *15874068 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 50#50: *15874078 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer                                                                                                           
 apisix 2023/05/27 21:36:52 [error] 56#56: *15874083 [lua] config_etcd.lua:634: failed to fetch data from etcd: failed to check item data of [/apisix/routes] err:failed to check the configuration of plu 
 gin response-rewrite err: invalid base64 content,  etcd key: /apisix/routes, context: ngx.timer   

### Steps to Reproduce

1 Run APISIX via Docker image
2 Create a route with

  "plugins": {
    "response-rewrite": {
      "body_base64": true
    }
  }

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
> When set, the body of the request will be decoded before writing to the client.
https://apisix.apache.org/docs/apisix/plugins/response-rewrite/

Hi, you should set `body` field together, maybe you used dashboard to configure the route, the dashboard unable to detect the configuration error.

**Comment by jcarrasco-odf** [comment]
You are right, the dashboard doesn't show any errors. I have checked the code and it does work that way, howerer how can I decode the response body?.

**Comment by Revolyssup** [comment]
> field together,

If you will pass a body then that body will be base64 decoded. Is your use case different? Are you trying to base64 decode the response from upstream server instead?

**Comment by jcarrasco-odf** [comment]
yes, that is my intention, to be able to Base64 decode the upstream response body.

Thanks for the information.

**Comment by Revolyssup** [comment]
@jcarrasco-odf If you want the feature then you can create another issue as a feature request. You can close this issue if your query is answered.

**Comment by jcarrasco-odf** [comment]
Thanks. I close the issue.
