### ISSUE TITLE
help request: in discovery.dns.servers config, how to use local DNS resolver ?

### ISSUE THREAD

**Issue by wilenceyao** [apache/apisix#9565]
### Description

The service discovery of dns type requires us to configure servers like this,

https://github.com/apache/apisix/blob/master/apisix/discovery/dns/schema.lua#L20

discovery:
  dns:
    servers:
      - "10.96.0.10:53"

how to tell apisix use system local resovers instead of manually configure

### Environment

*

**Comment by shreemaan-abhishek** [comment]
I'm curious too.

**Comment by kasini3000** [comment]
Looking forward to the early implementation of this feature.
Look:
Building cross platform dynamic service discovery using coredns and etcd
https://www.cnblogs.com/piapia/p/17503775.html

----

BTW: Generally speaking, at least two DNS IPs and ports should be added.

**Comment by Revolyssup** [comment]
@lingsamuel Please put this to backlog from in-progress as it is a low priority feature and requires discussion first.
