### ISSUE TITLE
bug: helm installation is failing 

### ISSUE THREAD

**Issue by hemakumar-ganumukkala** [apache/apisix#9568]
### Current Behavior

apisix installation is failing with below error on the kubernetes environment :

helm repo add apisix https://charts.apiseven.com/ && helm repo update && helm upgrade --install apisix apisix/apisix --create-namespace --namespace apisix --set dashboard.enabled=true --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --set gateway.type=NodePort
"apisix" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "apisix" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Release "apisix" does not exist. Installing it now.
Error: Chart.yaml file is missing

### Expected Behavior

Should successfully install the components. 

### Error Logs

apisix installation is failing with below error on the kubernetes environment :

helm repo add apisix https://charts.apiseven.com/ && helm repo update && helm upgrade --install apisix apisix/apisix --create-namespace --namespace apisix --set dashboard.enabled=true --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --set gateway.type=NodePort
"apisix" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "apisix" chart repository
...Successfully got an update from the "bitnami" chart repository
Update Complete. ⎈Happy Helming!⎈
Release "apisix" does not exist. Installing it now.
Error: Chart.yaml file is missing

### Steps to Reproduce

Below steps in the kubernetes env:
helm repo add apisix https://charts.apiseven.com/ && helm repo update && helm upgrade --install apisix apisix/apisix --create-namespace --namespace apisix --set dashboard.enabled=true --set ingress-controller.enabled=true --set ingress-controller.config.apisix.serviceNamespace=apisix --set gateway.type=NodePort

### Environment

Initital installation itself failing 
- Operating system (run `uname -a`): max os

**Comment by AlinsRan** [comment]
This is because there is an `apisix/` directory in your current path, but it's not a chart package.
It will attempt to query from the local path, and if it cannot be found, it will be downloaded and installed remotely. 
You only need to change the work directory.
