### ISSUE TITLE
help request: why I have not found message , when i add a grpc proto

### ISSUE THREAD

**Issue by iamacnhero** [apache/apisix#9569]
### Description

refer this: https://apisix.apache.org/blog/2021/12/30/apisix-proxy-grpc-service/

when I add a proto like this below: 
curl http://127.0.0.1:9180/apisix/admin/proto/1 \
-H 'X-API-KEY: someKeky' -X PUT -d '
{
    content = "syntax = \"proto3\";
    package com.company.push.v1;
    option java_package = "com.company.push.grpc.devicetoken";
    option objc_class_prefix = "COMPANY";
    service DeviceTokenService {
           rpc PersistDeviceToken (PersistDeviceTokenRequest) returns (PersistDeviceTokenReply);
    }
    message PersistDeviceTokenRequest {
            string device_id = 1;
            string token = 2;
            string app_id = 3;
    }

     message PersistDeviceTokenReply {
             int32 error_code = 1;
             string error_message = 2;
     }
}'

I got a  {"error_msg":"not found"}, I can't find any error, how should I do ?

### Environment

- APISIX version  3.0.0
- Operating system  Linux 695ddc80fd35 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 GNU/Linux
- OpenResty / Nginx version   nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1n  15 Mar 2022
TLS SNI support enabled

- etcd version   3.4.15
- LuaRocks version   none

**Comment by shreemaan-abhishek** [comment]
> I got a `{"error_msg":"not found"}`, I can't find any error, how should I do ?

What triggers that error?

**Comment by iamacnhero** [comment]
I know,  this document 'https://apisix.apache.org/blog/2021/12/30/apisix-proxy-grpc-service/",  this path [/apisix/admin/proto/1] is not correct，proto should be protos

**Comment by Revolyssup** [comment]
@iamacnhero Did you add the route? If yes, then can you provide the route configuration you added?
