### ISSUE TITLE
help request: how to get route_id

### ISSUE THREAD

**Issue by RangoStack** [apache/apisix#9570]
### Description

自定义插件怎么获取到请求的route_id呢？
ngx.ctx.api_ctx.route_id这种方式获取到的route_id与实际请求的route_id不一致的情况。

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@RangoStack Can you elaborate further? In which plugin are you trying to access the route id?

**Comment by moonming** [comment]
@RangoStack Please use English in the public channel, thx
Back to your question, can you provide reproduction steps? How do check the route id is not the ngx.ctx.api_ctx.route_id?

**Comment by lingsamuel** [comment]
Please give a minimal reproducible example. I can't repro this on my side.

Here is my reproduce way with APISIX  3.2
1. edit request-id plugin
```diff
function _M.header_filter(conf, ctx)
    if not conf.include_in_response then
        return
    end

+   core.log.info("request-id got route_id: ", ngx.ctx.api_ctx.route_id)
    local headers = ngx.resp.get_headers()
    if not headers[conf.header_name] then
        core.response.set_header(conf.header_name, ctx["request-id-" .. conf.header_name])
    end
end
```

2. generate many routes
![image](https://github.com/apache/apisix/assets/14567045/d1ef33c7-21ff-4312-8399-e970343dd8da)

3. create a simple route with request-id plugin
```bash
curl http://127.0.0.1:9180/apisix/admin/routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '{
    "uri": "/*",
    "plugins": {
        "request-id": {
         }
    },
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "baidu.com:80": 1
        }
    }
}'
```

4. query the route multiple times
![image](https://github.com/apache/apisix/assets/14567045/d315ac33-44b7-479b-8bf5-cd7576401784)
