### ISSUE TITLE
bug: admin & control API ip cannot be hot updated if its port is unchanged

### ISSUE THREAD

**Issue by An-DJ** [apache/apisix#9571]
### Current Behavior

Admin & control API ip cannot be updated and reloaded if its port is unchanged.

### Expected Behavior

Admin & control API ip can be changed and hot reloaded successfully if its port is unchanged.

### Steps to Reproduce

Take Admin API as an example:

1. Start APISIX with default configuration (Admin API ip 0.0.0.0, port 9180)
2. Change Admin API ip to `127.0.0.1` in `conf/config.yaml`
```
deployment:
  admin:
    admin_listen:
        ip: 127.0.0.1
```
3. Reload APISIX configure by the command `apisix reload`
4. Failed with error.log
```
2023/05/29 19:41:49 [notice] 10743#10743: signal process started
2023/05/29 19:41:49 [emerg] 10653#10653: bind() to 127.0.0.1:9180 failed (98: Address already in use)
2023/05/29 19:41:49 [emerg] 10653#10653: bind() to 127.0.0.1:9180 failed (98: Address already in use)
2023/05/29 19:41:49 [emerg] 10653#10653: bind() to 127.0.0.1:9180 failed (98: Address already in use)
2023/05/29 19:41:49 [emerg] 10653#10653: bind() to 127.0.0.1:9180 failed (98: Address already in use)
2023/05/29 19:41:49 [emerg] 10653#10653: bind() to 127.0.0.1:9180 failed (98: Address already in use)
2023/05/29 19:41:49 [emerg] 10653#10653: still could not bind()
```

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): Ubuntu 18.04
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):  openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@An-DJ Its not really a bug. 0.0.0.0:9180 means the socket corresponds to all IPs on all interfaces. When you reload, before letting go off the existing nginx process, openresty tries to bind to port 9180 on localhost but that address is already taken by the existing running process so it fails.

**Comment by An-DJ** [comment]
Yes thanks. I have noticed that. I have some deeper thoughts about that issue, and maybe we can discuss it on another one.

**Comment by An-DJ** [comment]
https://trac.nginx.org/nginx/ticket/1457 More details can be found there which can help people who found that issue to understand it.
