### ISSUE TITLE
help request: what topology to deploy to achieve high availability

### ISSUE THREAD

**Issue by yangdatianxia** [apache/apisix#9572]
### Current State

Unspecified deployment node

### Desired State

I would like to ask, if I want to deploy the decoupled mode, how many servers do I need to ensure high availability, and what are the data_plane and control_plane respectively. Should my java client be connected to the data_plane node, or the control_plane？

**Comment by kayx23** [comment]
please update the title to a more descriptive one rather than the URL. Thx.

**Comment by kayx23** [comment]
1. Your java client talks to the data plane.
2. How to achieve high availability for your system is dependent on a variety of factors. For one, separating DP and CP could be a good start, but you'd need to do some learning and architecting yourself.

The docs would not provide a definitive answer for how you should architect for your system. Closing the issue now.
