### ISSUE TITLE
docs: missing doc for `ai` plugin

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9573]
### Current State

Saw the plugin in `conf`:
![image](https://github.com/apache/apisix/assets/39619599/e02fa398-20c2-47e3-afe6-cc22c11ce095)

But the only information I could find was https://apisix.apache.org/blog/2022/11/02/apache-apisix-v3-preview/#2-ai-plane

### Desired State

* Discuss and decide if we should add a doc for this plugin and under what category.
* Write the doc.

**Comment by Revolyssup** [comment]
@kayx23 Was there any decision made here?

**Comment by shreemaan-abhishek** [comment]
ai plane is a performance optimization layer for apisix, this is not a plugin for end usage.
