### ISSUE TITLE
failed to find upstream by id. 

### ISSUE THREAD

**Issue by wentao1994** [apache/apisix#9581]
### Description

error日志里的信息:

2023/05/31 17:16:44 [error] 17450#17450: *525033 [lua] init.lua:591: http_access_phase(): failed to fetch service configuration by id: 459991065718426128, client: 192.168.110.50, server: _, request: "GET / HTTP/1.1", host: "gateway-sit.xiangyunbj.cn"

这是service的配置
/apisix/services/459991065718426128
{"id":"459991065718426128","create_time":1683705640,"update_time":1685527746,"name":"xiangyun-gateway-sit","desc":"xiangyun-gateway-sit","upstream_id":"459993355858741776","plugins":{"basic-auth":{"_meta":{"disable":true}}}}

023/05/31 17:17:56 [error] 17454#17454: *539267 [lua] upstream.lua:584: get_by_id(): failed to find upstream by id: 459993355858741776, client: 192.168.130.175, server: _, request: "GET /xiangyun-iam/api/user/login HTTP/1.1", host: "gateway-sit.xiangyunbj.cn"
2023/05/31 17:17:57 [error] 17454#17454: *539381 [lua] upstream.lua:584: get_by_id(): failed to find upstream by id: 459993355858741776, client: 192.168.130.175, server: _, request: "GET /xiangyun-iam/api/user/login HTTP/1.1", host: "gateway-sit.xiangyunbj.cn"
2023/05/31 17:17:59 [error] 17454#17454: *539811 [lua] upstream.lua:584: get_by_id(): failed to find upstream by id: 459993355858741776, client: 192.168.110.50, server: _, request: "GET /xiangyun-iam/api/user/login HTTP/1.1", host: "gateway-sit.xiangyunbj.cn"

upstream是存在的:
etcdctl --endpoints=http://127.0.0.1:2379 get /apisix/  --prefix|grep 459993355858741776
/apisix/upstreams/459993355858741776
{"id":"459993355858741776","create_time":1683707005,"update_time":1685524822,"nodes":{"192.168.110.72:9000":1},"timeout":{"connect":6,"send":6,"read":6},"type":"roundrobin","scheme":"http","pass_host":"pass","name":"xiangyun-gateway-sit","desc":"xiangyun-gateway-sit","keepalive_pool":{"idle_timeout":60,"requests":1000,"size":320}}

在出现报错的期间,有过下线路由的操作,执行过apisix reload/
apisix在什么情况下会出现这种error,而且会出现路由丢失的情况.看不出来配置的哪里有问题。。。。而且重启之后这个配置还在正常的工作.

### Environment

- APISIX version (run `apisix version`):apiversion:3.2.0
- Operating system (run `uname -a`):3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"boot_time":1685527677,"etcd_version":"3.5.0","version":"3.2.0","hostname":"bj-qingyun-serve04-dev","id":"711bd294-8f47-4de2-84d0-c68ee31e8d90"}
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
From your description, I don't know how to reproduce it.

**Comment by Revolyssup** [comment]
@wentao1994 During the error reporting period, can you confirm that there were no issues between the connectivity of etcd and APISIX?
