### ISSUE TITLE
help request: Apisix3 decoupled mode does not automatically refresh CP data without DP

### ISSUE THREAD

**Issue by XW512** [apache/apisix#9582]
### Description

I have set up the decoupled mode of Apisix3, but found that the DP node will not automatically refresh the modified data of the CP node. If I restart the DP node and the data can be synchronized to the DP node, is there a problem with my configuration

the DP config

apisix:
  ssl:
    ssl_trusted_certificate: /app/apisix-3.3.0/conf/cert/mtls_ca.crt
deployment:
  role: data_plane
  role_data_plane:
    config_provider: control_plane
    control_plane:
      host:
        - "https://gw-cp.intsit.local:9280"
      timeout: 5
      prefix: "/apisix"
  admin:
    admin_key:
      - name: admin
        key: 7b0d04aef23327824710da9ce10c55f0  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin

this CP config

deployment:
  role: control_plane
  role_control_plane:
    config_provider: etcd
    conf_server:
      listen: 0.0.0.0:9280
      cert: /app/apisix-3.3.0/conf/cert/mtls_server.crt
      cert_key: /app/apisix-3.3.0/conf/cert/mtls_server.key
  admin:
    admin_key:
      - name: admin
        key: 7b0d04aef23327824710da9ce10c55f0  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): centos8
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.19.9.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.9
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): 3.8.0

**Comment by XW512** [comment]
I want to ask, is this definitely a bug? If it's a bug, why hasn't anyone else encountered it，Or is there a problem with my configuration？

**Comment by shreemaan-abhishek** [comment]
@XW512 please provide the whole config.yaml file with proper formatting thanks so that I can try to reproduce it, thanks.

**Comment by XW512** [comment]
> @XW512 please provide the whole config.yaml file with proper formatting thanks so that I can try to reproduce it, thanks.

OK，thank you

this is data_plane config：

apisix:
  ssl:
    ssl_trusted_certificate: /app/apisix-3.3.0/t/certs/mtls_ca.crt
deployment:
  role: data_plane
  role_data_plane:
    config_provider: control_plane
    control_plane:
      host:
        - "https://gw-cp.intsit.cloud.local:9280"
      timeout: 30
      prefix: "/apisix"
  admin:
    admin_key:
      - name: admin
        key: 6b0d04aef24327864740da9ce10c55f0
        role: admin

this is control_plane config:

deployment:
  role: control_plane
  role_control_plane:
    config_provider: etcd
    conf_server:
      listen: 0.0.0.0:9280
      cert: /app/apisix-3.3.0/t/certs/mtls_server.crt
      cert_key: /app/apisix-3.3.0/t/certs/mtls_server.key
  admin:
    admin_key:
      - name: admin
        key: 6b0d04aef24327864740da9ce10c55f0
        role: admin

**Comment by shreemaan-abhishek** [comment]
@XW512, please don't send the data plane and the control plane configs separately 🤦🏼. Please paste your whole config.yaml file with proper formatting here. 🤦🏼‍♂️ 🤦🏼‍♂️

**Comment by XW512** [comment]
> @XW512, please paste your config.yaml file with proper formatting here. 🤦🏼‍♂️ 🤦🏼‍♂️

OK
this is  data_plane config.yaml

#
# deployment:
#   role: traditional
#   role_traditional:
#     config_provider: etcd
#   etcd:
#     host:
#       - http://${{ETCD_HOST:=localhost}}:2379
#
# This will find environment variable `ETCD_HOST` first, and if it's not exist it will use `localhost` as default value.
#
apisix:
  ssl:
    ssl_trusted_certificate: /app/apisix-3.3.0/t/certs/mtls_ca.crt
deployment:
  role: data_plane
  role_data_plane:
    config_provider: control_plane
    control_plane:
      host:
        #- "https://gis-gw-cp.intsit.sfcloud.local:9280"
        - "https://admin.apisix.dev:9280"
      timeout: 30
      prefix: "/apisix"
      #certs:
      #cert: /app/apisix-3.3.0/conf/cert/mtls_client.crt
      #cert_key: /app/apisix-3.3.0/conf/cert/mtls_client.key
  admin:
    admin_key:
      - name: admin
        key: 6b0d04aef24327864740da9ce10c55f0 
        role: admin


this is control_plane  config.yaml

#       - http://${{ETCD_HOST}}:2379
# 
# And then run `export ETCD_HOST=$your_host` before `make init`.
#
# If the configured environment variable can't be found, an error will be thrown.
#
# Also, If you want to use default value when the environment variable not set,
# Use `${{VAR:=default_value}}` instead. For instance:
#
# deployment:
#   role: traditional
#   role_traditional:
#     config_provider: etcd
#   etcd:
#     host:
#       - http://${{ETCD_HOST:=localhost}}:2379
#
# This will find environment variable `ETCD_HOST` first, and if it's not exist it will use `localhost` as default value.
#
deployment:
  role: control_plane
  role_control_plane:
    config_provider: etcd
    conf_server:
      listen: 0.0.0.0:9280
      cert: /app/apisix-3.3.0/t/certs/mtls_server.crt
      cert_key: /app/apisix-3.3.0/t/certs/mtls_server.key
  admin:
    admin_key:
      - name: admin
        key: 6b0d04aef24327864740da9ce10c55f0
        role: admin

producer mtls from https://apisix.apache.org/zh/docs/apisix/tutorials/client-to-apisix-mtls/

**Comment by kingluo** [comment]
The conf server is removed, so the etcd communication rolls back to what 2.x versions behave like, i.e. no matter CP or DP, connects to etcd directly. Closed by https://github.com/apache/apisix/pull/10012

**Comment by XW512** [comment]
> The conf server is removed, so the etcd communication rolls back to what 2.x versions behave like, i.e. no matter CP or DP, connects to etcd directly. Closed by #10012

thank you，I would like to ask how to configure the Decoupled mode for DP and CP isolation in version 3.5.0. I see that the configuration method after conf server is removed is not described in the document 3.5.0

**Comment by kingluo** [comment]
> > The conf server is removed, so the etcd communication rolls back to what 2.x versions behave like, i.e. no matter CP or DP, connects to etcd directly. Closed by #10012
> 
> thank you，I would like to ask how to configure the Decoupled mode for DP and CP isolation in version 3.5.0. I see that the configuration method after conf server is removed is not described in the document 3.5.0

No, we have changed the doc:
https://github.com/apache/apisix/blob/c757bafeb94315e03d3cc1ba4c88a0a94c081fd1/docs/en/latest/deployment-modes.md#L68

As well as the conf:
https://github.com/apache/apisix/blob/c757bafeb94315e03d3cc1ba4c88a0a94c081fd1/conf/config-default.yaml#L616-L625

The configuration of etcd, no matter which deployment mode, is configured just like 2.x version, except the role field.

**Comment by XW512** [comment]
> > > The conf server is removed, so the etcd communication rolls back to what 2.x versions behave like, i.e. no matter CP or DP, connects to etcd directly. Closed by #10012
> > 
> > 
> > thank you，I would like to ask how to configure the Decoupled mode for DP and CP isolation in version 3.5.0. I see that the configuration method after conf server is removed is not described in the document 3.5.0
> 
> No, we have changed the doc:
> 
> https://github.com/apache/apisix/blob/c757bafeb94315e03d3cc1ba4c88a0a94c081fd1/docs/en/latest/deployment-modes.md#L68
> 
> As well as the conf:
> 
> https://github.com/apache/apisix/blob/c757bafeb94315e03d3cc1ba4c88a0a94c081fd1/conf/config-default.yaml#L616-L625
> 
> The configuration of etcd, no matter which deployment mode, is configured just like 2.x version, except the role field.



> 

thank you, I tried using the method you mentioned above and found that DP can get up, while CP cannot. The error is as follows:
invalid deployment control_plane configuration: property "role_control_plane" validation failed: property "conf_server" is required

The configuration information of my CP is as follows:

deployment:
  role: control_plane
  role_control_plane:
    config_provider: etcd

**Comment by XW512** [comment]
Is this modification not in version 3.5.0, but in the master branch？When is the next release expected to be released

**Comment by kingluo** [comment]
> Is this modification not in version 3.5.0, but in the master branch？When is the next release expected to be released

Yes, it's only on the master branch. It'll be available in 3.6 or backport to 3.5 if necessary.

**Comment by XW512** [comment]
> > Is this modification not in version 3.5.0, but in the master branch？When is the next release expected to be released
> 
> Yes, it's only on the master branch. It'll be available in 3.6 or backport to 3.5 if necessary.

I would like to try this new mode now. Could you please create a release version first? Thank you very much

**Comment by kingluo** [comment]
You could try it from source code, but yes, it's a bit tough job.
So maybe you could use the release or dev version of the docker image:
https://hub.docker.com/r/apache/apisix/tags
Here is an example:
https://gist.github.com/kingluo/addf27f7dce5f9133043e8f1e5ab3a6a

**Comment by XW512** [comment]
> You could try it from source code, but yes, it's a bit tough job. So maybe you could use the release or dev version of the docker image: https://hub.docker.com/r/apache/apisix/tags Here is an example: https://gist.github.com/kingluo/addf27f7dce5f9133043e8f1e5ab3a6a

Thank you very much. I will give it a try
