### ISSUE TITLE
help request: use etcd ssl cluster,apisix error "upstream SSL certificate does not match ip while SSL handshaking to upstream"

### ISSUE THREAD

**Issue by Mararesliu** [apache/apisix#9592]
### Description

- error.log

2023/06/02 14:45:30 [error] 99763#99763: *3791 upstream SSL certificate does not match "ip" while SSL handshaking to upstream, client: unix:, server: , request: "GET /version HTTP/1.1", upstream: "https://ip:2379/version", host: "127.0.0.1"
2023/06/02 14:45:30 [warn] 99763#99763: *3791 [lua] conf_server.lua:181: report_failure(): report failure, endpoint: 10.7.64.107:2379 count: 2 while connecting to upstream, client: unix:, server: , request: "GET /version HTTP/1.1", upstream: "https://ip:2379/version", host: "127.0.0.1"

- config.yaml

apisix:
  ssl:
    ssl_trusted_certificate: /usr/local/apisix/tls/etcd.pem

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    admin_key:
      - name: admin
        key: edd1c9f034335f136f87ad84b625c8f1  # using fixed API token has security risk, please update it when you deploy to production environment
        role: admin
  etcd:
    host:
      - https://ip1:2379
      - https://ip2:2379
      - https://ip3:2379
    tls:
      cert: "/usr/local/apisix/tls/etcd.pem"
      key: "/usr/local/apisix/tls/etcd-key.pem"

### Environment

- APISIX version (run `apisix version`): 3.2
- Operating system (run `uname -a`):3.10.0-1160.59.1.el7.x86_64
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.4.24
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
I don't quite understand your problem description.

What is the relationship between etcd's ssl and upstream?
