### ISSUE TITLE
help request: How to filter HEAD requests when using file-logger?

### ISSUE THREAD

**Issue by kamly** [apache/apisix#9596]
### Description

many head request ， i want to filter it

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by An-DJ** [comment]
https://apisix.apache.org/docs/apisix/plugins/file-logger/

You may need `include_resp_body_expr`?

**Comment by kamly** [comment]
> https://apisix.apache.org/docs/apisix/plugins/file-logger/
> 
> You may need `include_resp_body_expr`?

i think `include_resp_body_expr` records the conditions of the body

```
"include_resp_body": true,
"include_resp_body_expr": [
    [
      "arg_foo",
      "==",
      "bar"
    ]
]
```
is arg foo is bar , can log the response body

but what I want is that if the method is a head request, the log is not recorded

**Comment by An-DJ** [comment]
> but what I want is that if the method is a head request, the log is not recorded

FYI it is not supported in APISIX yet.

IMHO, filtering, aggregation, count and other analysis operation can be further done based on the raw log data. If we do more restriction conditions on logging, it may lose the control of observability.

Recommend you filter and aggregate logs with other tools and OLAP system. : )

**Comment by kamly** [comment]
in nginx, we can 

```
map $request_method $ignore_head_request {
    HEAD 0;
    default 1;
}
access_log /data/logs/nginx/nginx_access.log json if=$ignore_head_request;
```

**Comment by shreemaan-abhishek** [comment]
I think you will have to patch apisix for this use case.

**Comment by kamly** [comment]
I want to push mr to apisix, but where should I start to solve this problem?  Can you provide some ideas?

**Comment by kamly** [comment]
@spacewander hi ,  can file-logger support `filter_expr` 

example:
```
{
    "file-logger": {
        "filter_expr": [
            [
                "http_method",
                "!=",
                "HEAD"
            ]
        ]
    }
}
```

**Comment by kamly** [comment]
@monkeyDluffy6017 hi,  please look look, thanks~

**Comment by monkeyDluffy6017** [comment]
LGTM
