### ISSUE TITLE
feat: add support for PURGE method in go plugin

### ISSUE THREAD

**Issue by W-sh** [apache/apisix#9597]
### Description

<img width="551" alt="image" src="https://github.com/apache/apisix/assets/33708244/e4fb170f-55f4-4a88-9073-7f3ec27abde6">

apisix和go-plugin交互不支持purge method，希望增加支持。在apisix作为流量网关，go插件自定义插件的场景，所代理的后端服务存在各种method，使用过程中发现purge method无法透传到后端服务，在apisix会处理异常返回501

**Comment by Revolyssup** [comment]
Translation:
The interaction between apisix and go-plugin does not support the purge method, and we hope to add support. In the scene where apisix is ​​used as a traffic gateway and the go plugin is a custom plugin, there are various methods in the proxy backend service. During use, it is found that the purge method cannot be transparently transmitted to the backend service, and apisix will handle the exception and return 501
