### ISSUE TITLE
docs: update Debug Mode doc with reload information

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9598]
### Current State

It's currently not mentioned in this doc whether users should restart APISIX for configs in `debug.yaml` to take effects: https://apisix.apache.org/docs/apisix/debug-mode/

### Desired State

* confirm in the codebase that `debug.yaml` is checked for differences at a given time interval
* add the information to the doc

Similar to how the [Standalone doc](https://apisix.apache.org/docs/apisix/deployment-modes/#standalone) mentions `apisix.yaml` is monitored: 

> The routing rules in the conf/apisix.yaml file are loaded into memory immediately after the APISIX node service starts. And every time interval (default 1 second), will try to detect whether the file content is updated, if there is an update, reload the rule.

**Comment by Revolyssup** [comment]
I can take this issue to update docs.

**Comment by kayx23** [comment]
Feel free to open a PR. Thanks.
