### ISSUE TITLE
13: Permission denied

### ISSUE THREAD

**Issue by l36t** [apache/apisix#9603]
### Description

I want to listen tcp service,port is 465,when I start docker,the error is:
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /usr/local/apisix/conf/nginx.conf:3
2023/06/06 03:52:55 [emerg] 1#1: bind() to 0.0.0.0:465 failed (13: Permission denied)

How can I resolve this problem,thanks

### Environment

- APISIX version (run `apisix version`):3.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Port number<1024 can not be used by unpriviliged processes.If you want to bind 465, then make sure you run the process as super user.

**Comment by l36t** [comment]
> Port number<1024 can not be used by unpriviliged processes.If you want to bind 465, then make sure you run the process as super user.

Thank you,I know the reason，but I install apisix from docker，How can I run the process as super user？

**Comment by Revolyssup** [comment]
@l36t Can you show the full command you are using? Are you trying to port map 465 on host? Or are you using host networking?

**Comment by Revolyssup** [comment]
@l36t Your docker daemon must be running with root privileges. You can do ps aux | grep docker to check

**Comment by lcxmm** [comment]
> > Port number<1024 can not be used by unpriviliged processes.If you want to bind 465, then make sure you run the process as super user.
> 
> Thank you,I know the reason，but I install apisix from docker，How can I run the process as super user？

Please provide the image ID or image version; 
I generally use gosu to raise authority, Or build the image by youself, when building the image, use a super user as running user;

**Comment by Sn0rt** [comment]
@l36t can I close this issue ?
