### ISSUE TITLE
doc(FAQ): how to use regex to match uri. 

### ISSUE THREAD

**Issue by membphis** [apache/apisix#961]
Currently, only the `path` in a route can be indexed. It supports full matching and prefix matching.
If you want to support regular matching, you need to use the `vars` of the route.

For example, to match this request: `/api/module/{code}/{param}`

```lua
local rule = {
    paths = {"/api/module/*"},
    vars = {"uri", "~~", [[/api/module/{\w+}/{\w+}]]},
}
```

----

目前路由中只有 path 字段是可以被索引的，它支持全量匹配和前缀匹配。
如果要支持正则匹配，需要通过路由的 `vars` 实现。

比如要匹配这种请求：`/api/module/{code}/{param}`

在 apisix 中需要这么写：

```lua
local rule = {
    paths = {"/api/module/*"},
    vars = {"uri", "~~", [[/api/module/{\w+}/{\w+}]]},
}
```

**Comment by liuhengloveyou** [comment]
What's the state of now?

**Comment by zhangweidongyyl** [comment]
how to use in apisix route conf?
