### ISSUE TITLE
repos.apiseven.com repomd.xml not found

### ISSUE THREAD

**Issue by zebra-93** [apache/apisix#9612]
### Description

https://repos.apiseven.com/packages/centos/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lingsamuel** [comment]
it's ok now
