### ISSUE TITLE
How to accurately control the daily limit count from 0 to 24 points

### ISSUE THREAD

**Issue by 123libohan** [apache/apisix#9613]
### Description

We want to accurately control the daily limit count from 0 to 24 points.
However, It cannot be accurately controlled by the limit-count plug-in, for an example:
Setting time_window  for 1 day at 9:00 today will control the daily limit count  in the time range of 9:00 tomorrow, but we want to control  in the range of 0 to 24 every day
Whether apisix supports such control of transfer volume?
Look forward to hearing from you. Thank you

**Comment by shreemaan-abhishek** [comment]
> but we want to control in the range of 0 to 24 every day

It isn't easy to understand what you mean. Do you want the limit-count time window to start at 12:00 AM and end at 11:59 PM?

**Comment by 123libohan** [comment]
> 

No,I want limit-count time window start at 00:00 AM and end at 12:00 PM , 24 hours in total.

**Comment by shreemaan-abhishek** [comment]
If you want a `limit-count` time window of 24 hours any start time and end time should work right? 🤔 Why do you want specific starting and ending times? 🤔🤔 🤔
