### ISSUE TITLE
feat: As a user, I want the opentelemetry plugin add support for configuring service_name via an additional attribute in the opentelemetry plugin.

### ISSUE THREAD

**Issue by fleashiro** [apache/apisix#9614]
### Description

Currently, in the `opentelemetry` plugin, the service name can only be set through the `plugin_attr` attribute in the configuration file. However, I would like to propose an enhancement that allows the plugin to prioritize an additional attribute, service_name.

When executing the create_tracer_obj method in the `opentelemetry` plugin:
- If the service_name attribute is present in the plugin attributes, use it as the service name.
- If the service_name attribute is not provided, fallback to using the value defined in the configuration file.

This enhancement will provide users with the flexibility to configure the service_name directly in the plugin attributes, making it more convenient and intuitive to use.

**Comment by Sn0rt** [comment]
@fleashiro sounds reasonable. 

Can you sort out the documentation for the two usage methods?
1. Method 1 uses attr (currently supported).
2. The way you expect, this is the main thing to discuss.

**Comment by fleashiro** [comment]
@Sn0rt Sorry for delayed response.

To enhance this plugin, my main goal is to integrate the collector configuration directly into the plugin's attributes. 
Currently, the collector can only be configured using YAML, as explained in the [opentelemetry documentation](https://apisix.apache.org/docs/apisix/plugins/opentelemetry/#configuring-the-collector).

To implement this feature:
1. Add the collector fields to the plugins's schema
2. Modify the create_tracer_obj (found at [opentelemetry.lua](https://github.com/apache/apisix/blob/master/apisix/plugins/opentelemetry.lua#L232C28-L232C28)) Function:

If the conf.collector fields are available, use the values provided by the user; otherwise, fall back to default yaml values.
```
local function create_tracer_obj(conf)
    -- Set default values
    local default_address = plugin_info.collector.address
    local default_timeout = plugin_info.collector.request_timeout
    local default_headers = plugin_info.collector.request_headers

    -- Override defaults with values from the conf table if available
    local address = conf.collector and conf.collector.address or default_address
    local request_timeout = conf.collector and conf.collector.request_timeout or default_timeout
    local request_headers = conf.collector and conf.collector.request_headers or default_headers

    -- create exporter
    local exporter = otlp_exporter_new(exporter_client_new(address, request_timeout, request_headers))
    -- Rest of the function code
    ...

```
3. Add test cases

**Comment by Sn0rt** [comment]
I'm a little curious, what kind of scenarios need to configure service.name: APISIX repeatedly.

After APISIX is deployed as a direction agent, the service name is configured and does not need to be changed repeatedly.

**Comment by fleashiro** [comment]
@Sn0rt 
I rethink it and you're absolutely right. Changing the `service_name` using the plugin's attributes might not be necessary. My initial motivation for wanting to change it was because I have multiple apisix instances, each with a different service name. I wanted to avoid creating multiple YAML files with only the service.name being different. But I just noticed that I can achieve this using environment variables. As a result, this feature request doesn't require altering the service.name component any more. I will close it soon.

**Comment by Sn0rt** [comment]
Yes. 

Even if k8s is used to deploy APISIX, the properties of its configuration file opentelemetry can also be initialized with variables.
