### ISSUE TITLE
How to  get request header and not differentiate between dashes and underscores

### ISSUE THREAD

**Issue by chenjinfeng0505** [apache/apisix#9615]
### Description

We get the request header by using core.request.header(ctx, name).  But name  contains dashed line  or underscores，such as  name-a and name_a.  We want to get value directly and not differentiate between dashes and underscores. 
If you have any good suggestions, please let me know.
Thanks.

### Environment

- APISIX version (run `apisix version`): 3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Sn0rt** [comment]
If there are a certain number of headers, you can try to use proxy-rewrite to unify these headers into one format.

**Comment by chenjinfeng0505** [comment]
@Sn0rt  Thanks  I know that apisix distinguishes between underscores and underscores, but kong can not distinguish. In order to solve this problem, I added a judgment.
