### ISSUE TITLE
bug: restart etcd admin api  /apisix/admin/routes response is error

### ISSUE THREAD

**Issue by Xusq513** [apache/apisix#9618]
### Current Behavior
```
{
    "createdIndex": 10,
    "value": {

        "uri": "/test/*",
        "name": "test-默认路由",
        "id": "test",
        "priority": 0,
        "labels": {
            "systemCode": "test"
        },
        "upstream_id": "test",
        "create_time": 1686127207,
        "update_time": 1686127207,
        "status": 1
    },
    "key": "/apisix/routes/test",
    "modifiedIndex": 10
}
```

### Expected Behavior
```
{
    "total": 1,
    "list": [
        {
    "createdIndex": 10,
    "value": {

        "uri": "/test/*",
        "name": "test-默认路由",
        "id": "test",
        "priority": 0,
        "labels": {
            "systemCode": "test"
        },
        "upstream_id": "test",
        "create_time": 1686127207,
        "update_time": 1686127207,
        "status": 1
    },
    "key": "/apisix/routes/test",
    "modifiedIndex": 10
}
    ]
}
```

### Steps to Reproduce

1. start apisix and etcd
2. query /apisix/admin/routes ,the result is right
3. stop etcd
4. start etcd
5. query /apisix/admin/routes ,the result is error

### Environment

- APISIX version (run `apisix version`): 3.2.0 (3 nodes)
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.7

**Comment by Xusq513** [comment]
restart apisix , the response become right. when it's error, I view etcd data, it's no problem.

**Comment by shreemaan-abhishek** [comment]
works fine for me.

**Comment by Sn0rt** [comment]
sorry , we can't reproduce this issues . @Xusq513

**Comment by bzp2010** [comment]
This bug has been identified, so I reopened this issue to track progress.

**Comment by AlinsRan** [comment]
@shreemaan-abhishek I have reproduced it, please let me fix this issue.
