### ISSUE TITLE
apisix  fail to start(can't work normally)

### ISSUE THREAD

**Issue by cczchunge** [apache/apisix#9620]
### Description

when i start apisix ,   "apisix start":

the error.log shows:

2023/06/07 17:12:07 [error] 10132#10132: init_worker_by_lua error: ./prometheus.lua:37: attempt to index local 'exporter' (a number value)
stack traceback:
        ./prometheus.lua:37: in main chunk
        [C]: in function 'require'
        ...cal/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:17: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/apisix/plugin.lua:740: in function 'init_worker'
        /usr/local/share/lua/5.1/apisix/init.lua:148: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk
2023/06/07 17:12:07 [error] 10133#10133: init_worker_by_lua error: ./prometheus.lua:37: attempt to index local 'exporter' (a number value)
stack traceback:
        ./prometheus.lua:37: in main chunk
        [C]: in function 'require'
        ...cal/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:17: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/apisix/plugin.lua:740: in function 'init_worker'
        /usr/local/share/lua/5.1/apisix/init.lua:148: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk
2023/06/07 17:12:07 [error] 10134#10134: init_worker_by_lua error: ./prometheus.lua:37: attempt to index local 'exporter' (a number value)
stack traceback:
        ./prometheus.lua:37: in main chunk
        [C]: in function 'require'
        ...cal/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:17: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/apisix/plugin.lua:740: in function 'init_worker'
        /usr/local/share/lua/5.1/apisix/init.lua:148: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk
2023/06/07 17:12:07 [error] 10138#10138: init_worker_by_lua error: ./prometheus.lua:37: attempt to index local 'exporter' (a number value)
stack traceback:
        ./prometheus.lua:37: in main chunk
        [C]: in function 'require'
        ...cal/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:17: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/apisix/plugin.lua:740: in function 'init_worker'
        /usr/local/share/lua/5.1/apisix/init.lua:148: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk
2023/06/07 17:12:07 [error] 10135#10135: init_worker_by_lua error: ./prometheus.lua:37: attempt to index local 'exporter' (a number value)
stack traceback:
        ./prometheus.lua:37: in main chunk
        [C]: in function 'require'
        ...cal/share/lua/5.1/apisix/plugins/prometheus/exporter.lua:17: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/apisix/plugin.lua:740: in function 'init_worker'
        /usr/local/share/lua/5.1/apisix/init.lua:148: in function 'http_init_worker'
        init_worker_by_lua:2: in main chunk

====
please help me!

### Environment

- APISIX version (run `apisix version`):  3.2.0
- Operating system (run `uname -a`):  Linux iZ1pg01g9j9z3qotzmx9xgZ 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):   etcd v3.5.7
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): /usr/local/bin/luarocks 3.9.2

**Comment by kayx23** [comment]
please update the issue title

**Comment by shreemaan-abhishek** [comment]
@cczchunge Which method (docker, helm, local build) are you using for installation? 

If you are building locally, have you made any changes to the local codebase?

**Comment by shreemaan-abhishek** [comment]
@cczchunge any updates?
