### ISSUE TITLE
If the upstream service is an https service（h2 over tls);apisix does not use http/2 by default  to communicate with upstream;

### ISSUE THREAD

**Issue by wzbwzt** [apache/apisix#9630]
### Description

when the upstream has enable h2 https server,apisix has not communicate with upstream by http/2;
env: 3.2.1-debian of docker image used
config: config.yaml has enable http2;
discover: upstream has  print the request protocol

``fmt.Fprintln(ctx.Writer, ctx.Request.Proto)``

**Comment by wzbwzt** [comment]
direct access to upstream  services ,the printed  protocol is http/2; so server is ok

**Comment by shreemaan-abhishek** [comment]
> apisix has not communicate with upstream by http/2

How did you confirm this?

**Comment by wzbwzt** [comment]
output the `Request.Proto`  in upstream to checkout when request via apisix; 
result is `http/1.1` ,but when has not requst via apisix , result is `http/2`

**Comment by Revolyssup** [comment]
@wzbwzt Can you confirm that your configuration yaml has set the enable_http2 as true in ssl config? Reference: https://github.com/apache/apisix/blob/488ace42e978a03a803bfd43d19fbe15d8f435a0/conf/config-default.yaml#L103

**Comment by Sn0rt** [comment]
can I close this issues ? if you not append others msg I will close this issues after one week.

**Comment by Revolyssup** [comment]
@wzbwzt Checking in. Is your query solved? If yes, will you close the issue?

**Comment by kingluo** [comment]
@wzbwzt Upstream only accepts http(s) and grpc protocols. No http/2.
