### ISSUE TITLE
help request: apisix 如何同时支持两个go-ruuner

### ISSUE THREAD

**Issue by zhangyial** [apache/apisix#9636]
### Description

场景：公司有两个团队各自提供了一个go-ruuner插件，请教，如何在同一个apisix中集成两个go-ruuner?

### Environment

- APISIX version (run `apisix version`):
- Operating system (linux):
- OpenResty / Nginx version (OpenResty 1.21.4.1):
- etcd version, if relevant (3.5.4):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
You can have a single main process and use .RegisterPlugin method (in github.com/apache/apisix-go-plugin-runner/pkg/plugin) to register both plugins there. And then you can enable each of those plugins by their name https://apisix.apache.org/docs/apisix/plugins/ext-plugin-pre-req/#enabling-the-plugin

**Comment by Revolyssup** [comment]
@zhangyial  Checking in. Is your use case met? Do you have any further queries? If not, will you close the issue?

**Comment by Revolyssup** [comment]
@zhangyial Closing the issue. Please reopen if you still have query.
