### ISSUE TITLE
bug:  package apisix-base-1.21.4.1.10-0.ubi8.6.x86_64 does not verify

### ISSUE THREAD

**Issue by aliezHub** [apache/apisix#9639]
### Current Behavior

yum install apisix -y 报错

### Error Logs

You can remove cached packages by executing 'yum clean packages'.
Error: Transaction test error:
  package apisix-base-1.21.4.1.10-0.ubi8.6.x86_64 does not verify: Payload SHA256 digest: BAD (Expected 3e208450aee26b44fc2840ccaf39f21b5efe50a25dc3e736e7667618fd9d02ef != c1835d8ca27356934e076c5216adf028605595647c6f0e927770b168829b4b5b)

### Steps to Reproduce

按照https://apisix.apache.org/docs/apisix/installation-guide/中的RPM安装方式，安装报错

### Environment

# cat /etc/os-release
NAME="TencentOS Server"
VERSION="3.1 (Final)"
ID="tencentos"
ID_LIKE="rhel fedora centos"
VERSION_ID="3.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="TencentOS Server 3.1 (Final)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:tencentos:tencentos:3"
HOME_URL="https://cloud.tencent.com/product/ts"

TENCENT_SUPPORT_PRODUCT="tencentos"
TENCENT_SUPPORT_PRODUCT_VERSION="3"
NAME_ORIG="TencentOS Server"

**Comment by moonming** [comment]
This issue was caused by making packages, which were fixed a few days ago.
CI will be added later to ensure the availability of the installation package.
Thanks for the report @aliezHub
