### ISSUE TITLE
How to support both rewrite url and unsafe  transfer last url?

### ISSUE THREAD

**Issue by lsy1990** [apache/apisix#9640]
### Description

I want to use proxy_rewrite to modify url to remove url's prev,and keep the origin url  last part .Is there some way to implement it?

**Comment by shreemaan-abhishek** [comment]
please show us an example of what you want to achieve.

**Comment by shreemaan-abhishek** [comment]
@lsy1990 any updates?

**Comment by Revolyssup** [comment]
@lsy1990 You can use regex uri to achieve this. Refer to `regex_uri` field in the docs here: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/
