### ISSUE TITLE
help request: How to manipulate the response body?

### ISSUE THREAD

**Issue by exsaviour** [apache/apisix#9642]
### Description

Greetings,

I am trying to manipulate a response body but I am not able to understand how to.
I was able to manipulate a request body using the following code:

```
req_template=$(cat <<EOF
{%
cjson = require(\"cjson.safe\")
requestBodyJson = cjson.decode(_ctx.var.request_body)
requestBodyJson.newAttribute = \"New attribute\"
modifiedRequestBody = cjson.encode(requestBodyJson)
%}    
{*modifiedRequestBody*}
EOF
)


echo "Creating Request Transformer Plugin"
plugin_config_payload='{
    "desc": "Request Transformation Plugin",
	"plugins": {
        "body-transformer": {
            "request": {
                "input_format": "json",
		        "template": "'"$req_template"'"
            }
        }
	}
}'
```

But I was unable to alter the response body following the same approach because I cannot find the variable holding the value anywhere. It's not on _ctx, or _ctx.var.response or _ctx.var.rsp, I tried various ideias and combinations, looked everywhere in the documentation and the code but I was not able to find how to do this with a json body, can you please help?

Regards,
Emil 

### Environment

- APISIX version: 3.0.1;
- Operating system: Linux fa074110730d 5.15.0-73-generic #80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023 x86_64 GNU/Linux (docker);
- OpenResty / Nginx version: openresty/1.21.4.1;

**Comment by Revolyssup** [comment]
You can try using ngx.arg[1] and ngx.arg[2] as specified in the docs for ngx.arg:
> When this table is used in the context of [body_filter_by_lua*](https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/#body_filter_by_lua), the first element holds the input data chunk to the output filter code and the second element holds the boolean flag for the "eof" flag indicating the end of the whole output data stream.

**Comment by exsaviour** [comment]
Hello,

It's not working, here's the code:

```
res_template=$(cat <<EOF
{%
%}    
{*ngx.arg[1]*}
{*ngx.arg[2]*}
EOF
)


echo "Creating Response Transformer Plugin"
plugin_config_payload='{
    "desc": "Response Transformation Plugin",
	"plugins": {
        "body-transformer": {
            "response": {
                "input_format": "json",
		"template": "'"$res_template"'"
            }
        }
	}
}'
```

The first ngx argument is showing empty space and the second is showing the true boolean flag. 
It seems as though I am trying to access the body at a point where it is no longer there but at the same time, I am using the body transformer plug-in, so I should be able to get it.
Reference:
https://apisix.apache.org/docs/apisix/plugins/body-transformer/

**Comment by kingluo** [comment]
Try master branch. 
In the previous version before https://github.com/apache/apisix/pull/9446, `_body` is only available when the body is decoded failed.

**Comment by exsaviour** [comment]
Hello,
I applied the fix locally and it worked!
Thank you so much @kingluo

**Comment by zijiwork** [comment]
res_template Where should the variable be defined? I can't seem to find where to put it.
<img width="457" alt="image" src="https://github.com/apache/apisix/assets/24753365/690585de-3f32-4716-9530-174511bb2606">

**Comment by kingluo** [comment]
@zijiwork 
res_template is just a bash variable.
Check here: https://apisix.apache.org/zh/docs/apisix/plugins/body-transformer/#test

**Comment by zijiwork** [comment]
Thank you so much
@kingluo 

```
req_template=$(cat <<EOF | awk '{gsub(/"/,"\\\"");};1' | awk '{$1=$1};1' | tr -d '\r\n'
{
	"envName": "测试环境",
	"envCode": "test",
	"clusterId": 1,
	"envDesc": "",
	"namespace": "default",
	"hosts": [],
	"hosts_id": [],
	"isNotificationEnabled": null,
	"isApprovalEnabled": null,
	"noticeEvent": null,
	"noticeType": "",
	"webhook": "",
	"isContainer": true,
	"hostIds": []
}
EOF
)
```

I expect to use rsp_template to judge the request data and return the corresponding field content, but the following template does not take effect. 

can you help me? Return the envName in the request in the response template
```
rsp_template=$(cat <<EOF | awk '{gsub(/"/,"\\\"");};1' | awk '{$1=$1};1' | tr -d '\r\n'
{% if envName == 测试环境 then %}
{
   "status":"{{_ctx.var.status}}",
   "name": "{{envName}}"
}
{% else %}
{
   "code":"{{envCode}}"
}
{% end %}
EOF
)
```

**Comment by zijiwork** [comment]
> double quote missing? "测试环境"

The double quotes are not missing. If double quotes are added, the judgment will be invalid. No matter I can't get the response content through {{_ctx.var.response}} or _ctx.var.rsp, please tell me what I missed?
