### ISSUE TITLE
help request: Why does the post parameter in the advanced route matching rule only support application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by youzhixiaomutou** [apache/apisix#9643]
### Description

In lines 260 - 272 of the ctx.lua file,  it is hard-coded "Content-Type" == "application/x-www-form-urlencoded":

``` lua
elseif core_str.has_prefix(key, "post_arg_") then
    -- only match default post form
    if request.header(nil, "Content-Type") == "application/x-www-form-urlencoded" then
        local arg_key = sub_str(key, 10)
        local args = request.get_post_args()[arg_key]
        if args then
            if type(args) == "table" then
                val = args[1]
            else
                val = args
            end
        end
    end
```
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type, why not support such as "Content-Type" == "application/x-www-form-urlencoded; charset=utf8" as Content-Type？

### Environment

- APISIX version (run `apisix version`): v3.2.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
(subscribed)

**Comment by Revolyssup** [comment]
This function is just an abstraction over ngx API where the `ngx.req.get_post_args` method specifies[1] that it returns query args for mime type `application/x-www-form-urlencoded`. The code here is just following the ngx API. Moreover there is no charset parameter defined for this mime type. Please refer here[2][3].

1. https://openresty-reference.readthedocs.io/en/latest/Lua_Nginx_API/#ngxreqget_post_args
2. https://stackoverflow.com/questions/16819502/application-x-www-form-urlencoded-and-charset-utf-8#:~:text=The%20application%2Fx%2Dwww%2D,which%20the%20name%20is%20_charset%20.
3. https://url.spec.whatwg.org/#application/x-www-form-urlencoded

**Comment by Revolyssup** [comment]
@youzhixiaomutou Can you close the issue if your query was answered?
