### ISSUE TITLE
docs: Missed documentation about standalone mode

### ISSUE THREAD

**Issue by hamidrezakhosroabadi** [apache/apisix#9647]
### Current State

It seems there is no document for standalone mode since version 3.0 and according to this [change log](https://github.com/apache/apisix/blob/master/CHANGELOG.md) the standalone mode was not removed.
It causes to document conflicts and reduces document cohesion.

### Desired State

 If standalone mode still exists in version 3.3, we can add the correspond documentation.

**Comment by shreemaan-abhishek** [comment]
https://apisix.apache.org/docs/apisix/deployment-modes/#standalone
