### ISSUE TITLE
help request: how can apisix support virtual url and mutiple base path forward like kong?

### ISSUE THREAD

**Issue by somno1ency** [apache/apisix#9651]
### Description

asume I have a two micro service deployed, and the service info is below:
1. http://internal-dns/service-1
2. http://internal-dns/service-2
please pay attention, the domain part of two service is the same, just as tiped: internal-dns, what the different is the path part, and I want config two route to visit them, the first url via gateway is:
https://gateway.xx.com/anything, it can visit service1
the second url via gateway is:
https://gateway.xx.com/anything-other, it can visit service2

by using kong, I can create a service component(kong component) for service 1, the forward host is internal-dns and the base path is service-1, and then I create a service component for service 2, the forward host is internal-dns too and the base path is service-2
then I create a route under each service, and the route path is anything and anything-other, so it's will works as I expected

recently, I want to migrate the gateway to apisix for some reason, but when I want to keep the url as well, I found it's difficult to support it, how can I do this, please help, by using apisix dashboard, thanks very much!

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): Linux 79e4ca0b3b12 6.3.6-orbstack-00155-g0884b5092004 #1 SMP Wed Jun  7 08:31:59 UTC 2023 aarch64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
built with OpenSSL 1.1.1s  1 Nov 2022
TLS SNI support enabled
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
You can create two routes like so:

Create first route with route uri: `anything` that forwards request to the upstream: `http://internal-dns/service-1` and create second route with route uri: `anything-other` that would forward request to the upstream: `http://internal-dns/service-2`

**Comment by somno1ency** [comment]
yeah, I want to do like this, but when I use apisix dashboard, the forwards target setting, as you said, set it to http://internal-dns/service-1, but it's can only contains domain or IP, so I cannot put the service-1 part into the target setting, even I choose the upstream type to Node / Discovery, which like this:
<img width="1296" alt="image" src="https://github.com/apache/apisix/assets/8048737/d06c2253-606b-44d2-9085-6f19a55cf8bb">
as the slash char is not allowed, so I cannot configure it, please help, thank you

**Comment by somno1ency** [comment]
and another thing, in my case, the request url for service-1 is https://gateway.xx.com/anything to forward to http://internal-dns/service-1, please pay attention, the anything is just a virtual part, just used for pretty the url, that said there is no need a api in service-1 which it's route is anything, now with apisix, I found that the request uri (anything) will become a part of the target api, but most scenes, there is no need become a part of the target api, kong have a boolean config call "strip path" to make it to virtual, used it to pretty url, no effected with the target, so how can I do in apisix, I think it's very useful

now in apisix, a route like "anything" forward to http://internal-dns/service-1 required the service-1 have an api named anything, so actually http://gateway.xx.com/anything/aa will forward to http://internal-dns/service-1/anything/aa, what I want is to strip the anything, so I expected http://gateway.xx.com/anything/aa forward to http://internal-dns/service-1/aa, how can I do with apisix dashboard?

**Comment by somno1ency** [comment]
oh, at last, I found the way to configure what I want, thank u very much

**Comment by shreemaan-abhishek** [comment]
> oh, at last, I found the way to configure what I want, thank u very much

Would you mind sharing how you did that?

**Comment by somno1ency** [comment]
sure, when I create a route for service-1, I add "anything" in Request Basic Define part, and then in Request Overrid part, I change the URI Override from "Stay The Same" to "Static", so that will apear a "New Path" form, I put the target service base path to here, so it's works as my expected.

**Comment by somno1ency** [comment]
but I face another problem, could you help me? when I develop a custom plugin and enable it in a route, the apisix will occured etcd cannot fetch data, but enable official plugin is ok, if etcd config is error, I think the official plugin will cause error too, but now only appear on my plugin:
![image](https://github.com/apache/apisix/assets/8048737/a74b02fc-e9f0-47ee-9d25-364e4e13413e)
my plugin is so simple just print some context, but the error occured when call check_schema
<img width="664" alt="image" src="https://github.com/apache/apisix/assets/8048737/05b84e64-e639-41e6-bd6b-b9d9a41609e4">
why check_schema will cause the problem?

**Comment by Revolyssup** [comment]
@somno1ency It looks like the check function returned ok as false but err was nil. I am looking into the issue.

**Comment by shreemaan-abhishek** [comment]
@somno1ency, please share your custom plugin. Probably there is some issue in your code.
