### ISSUE TITLE
help request: can i install apisix 3.x.x  with ubuntu  witout docker ?

### ISSUE THREAD

**Issue by Meguais** [apache/apisix#9668]
### Description

help request: can i install apisix 3.x.x  with ubuntu  witout docker ?

### Environment

- APISIX version (run 3.x.x`):
- Operating system (run `ubuntu`):

**Comment by Revolyssup** [comment]
You can refer here: https://apisix.apache.org/docs/apisix/installation-guide/#installation-via-deb-repository

**Comment by Meguais** [comment]
thank you Does OpenResty support all versions for apisix?

**Comment by Meguais** [comment]
I am new to linux and can I install CentOS packages on ubuntu?

**Comment by Revolyssup** [comment]
> thank you Does OpenResty support all versions for apisix?

 OpenResty 1.19+ + LuaJIT is required for Apache APISIX.

**Comment by Revolyssup** [comment]
> I am new to linux and can I install CentOS packages on ubuntu?

No not directly. Ubuntu supports debian packages. You can convert rpm into deb though.
Although apisix has a deb package which you can install directly.

**Comment by Meguais** [comment]
> 

thank you
I asked chatgpt but I don't trust it very much it told me to sudo apt install alien 
So do I do it with alien?

**Comment by shreemaan-abhishek** [comment]
@Meguais, you can try converting rpm to deb if chatgpt suggests you to use alien, go ahead and give it a shot 😉 

For now, I am closing this issue, please reopen if you have further questions.
