### ISSUE TITLE
IP does not poll when using passive health-check

### ISSUE THREAD

**Issue by DHB-liuhong** [apache/apisix#967]
### Issue description
ip does not pool when using passive health-check

### Environment
![image](https://user-images.githubusercontent.com/26212922/70767597-e1e1d980-1d9c-11ea-91a4-385781b096cc.png)
Send the requests：
![image](https://user-images.githubusercontent.com/26212922/70767778-819f6780-1d9d-11ea-9d76-92e1ef1019eb.png)

All of these requests are processed by this ip of 8080 ,The 8081 IP does not handle any requests

**Comment by DHB-liuhong** [comment]
@moonming can you help to see.

**Comment by moonming** [comment]
@DHB-liuhong can you give reproduce steps? and what's the version of APISIX?

**Comment by DHB-liuhong** [comment]
@moonming apisix version：
[root@node9 ~]# apisix version
0.9-rc1
step：
1. set routes
curl -i -X PUT http://192.168.3.39:9080/apisix/admin/routes/1 -d '
{
    "uri": "/*",
    "methods": ["PUT", "GET", "POST", "DELETE"],
    "upstream": {
        "type": "roundrobin",
        "nodes": {
            "192.168.3.39:8080": 1,
            "192.168.3.39:8081": 1
        },
        "checks": {
            "passive": {
                "healthy": {
                    "http_statuses": [200, 201, 204, 301],
                    "successes": 1
                },
                "unhealthy": {
                    "http_statuses": [500, 504, 403],
                    "http_failures": 1,
                    "tcp_failures": 1
                }
            }
        }
    }
}'
2. use s3cmd create bucket
for i in {1..10};do s3cmd -c test.cfg mb s3://b0$i;done
3. observe apisix access.log

**Comment by DHB-liuhong** [comment]
@moonming can you help to see. thanks

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.
