### ISSUE TITLE
Apisix now needs to configure a whitelist, which does not work according to the document

### ISSUE THREAD

**Issue by val-stu** [apache/apisix#9670]
### Description

1

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Please provide a detailed description of you issue.
