### ISSUE TITLE
Support install APISIX on server Redhat 7

### ISSUE THREAD

**Issue by anhnguyenit2** [apache/apisix#9679]
### Description

- I can install APISIX(**RPM offline package**) on centos 7, but when i try install on redhat, i get error: 
```linux
https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (Apache APISIX Repository for CentOS),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=release ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable release
        or
            subscription-manager repos --disable=release

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=release.skip_if_unavailable=true

failure: repodata/repomd.xml from release: [Errno 256] No more mirrors to try.
https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

```

### Environment

- APISIX version (run `apisix version`): 3.3
- Operating system (run `uname -a`): redhat 7
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant: v3.0.1
- Plugin runner version, for issues related to plugin runners: 
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lingsamuel** [comment]
We don't provide redhat 7 release. If you want to install, you need to change your repo and edit the releasever to 7 or 8

**Comment by anhnguyenit2** [comment]
@lingsamuel you mean i need install apisix with redhat 8 right?

**Comment by moonming** [comment]
> https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml

This is not a correct address. What are your installation steps? @anhnguyenit2

**Comment by anhnguyenit2** [comment]
> We don't provide redhat 7 release. If you want to install, you need to edit your repo releasever to 7 or 8

@lingsamuel this is step: https://apisix.apache.org/docs/apisix/installation-guide/#installation-via-rpm-offline-package

**Comment by anhnguyenit2** [comment]
> > https://repos.apiseven.com/packages/centos/7Server/x86_64/repodata/repomd.xml
> 
> This is not a correct address. What are your installation steps? @anhnguyenit2

@moonming this is step: https://github.com/apache/apisix/issues/9679#issuecomment-1596580860

**Comment by lingsamuel** [comment]
You need to edit your yum repo file.
For example (fedora 38), you need to edit `apache-apisix.repo` and `openresty.repo` under `/etc/yum.repos.d`

**Comment by anhnguyenit2** [comment]
![image](https://github.com/apache/apisix/assets/57515634/4225f651-c98d-4848-90f1-512264815122)


> You need to edit your yum repo file. For example (fedora 38), you need to edit `apache-apisix.repo` and `openresty.repo` under `/etc/yum.repos.d`

@lingsamuel could you provide me correct repo. I change to this repo but it not work

**Comment by anhnguyenit2** [comment]
@lihuibin I can install now, thank you for your support!
