### ISSUE TITLE
help request: image not found on ACK

### ISSUE THREAD

**Issue by zhouzhenhua** [apache/apisix#9686]
### Description

After the capacity expansion of Alibaba Cloud Cloud ACK kubernetes node last Friday (2023.6.16),

Have you encountered a failure in pulling the APISIX image from the APISIX cluster deployed by helm charts?

**The following is a manual test for pulling images：**
```
[root@bastion01 docker]# docker pull apache/apisix:3.2.0-debian
Trying to pull repository docker.io/apache/apisix ...
manifest for docker.io/apache/apisix:3.2.0-debian not found
[root@bastion01 docker]# docker pull apache/apisix:3.3.0-debian
Trying to pull repository docker.io/apache/apisix ...
manifest for docker.io/apache/apisix:3.3.0-debian not found
```

### Environment

- APISIX version (run `apisix version`): apisix-3.2.0
- Operating system (run `uname -a`):   Alibaba Cloud Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by vedantm8** [comment]
I ran the following commands and both worked as intended:

For docker pull apache/apisix:3.2.0-debian
`$ docker pull apache/apisix:3.2.0-debian
3.2.0-debian: Pulling from apache/apisix
3f9582a2cbe7: Pull complete 
81c0df9a0214: Pull complete 
4f4fb700ef54: Pull complete 
7f9595e006f7: Pull complete 
0fd728e90d89: Pull complete 
52e828237f39: Pull complete 
Digest: sha256:1447c22cadd5bcd4a28150c034185e058a6dae659ede3b87525650eba4ce976d
Status: Downloaded newer image for apache/apisix:3.2.0-debian
docker.io/apache/apisix:3.2.0-debian`

For docker pull apache/apisix:3.3.0-debian
`$ docker pull apache/apisix:3.3.0-debian
3.3.0-debian: Pulling from apache/apisix
f03b40093957: Pull complete 
1e680f54b960: Pull complete 
4f4fb700ef54: Pull complete 
74268aad2661: Pull complete 
1a3229b5dddd: Pull complete 
026d4349006e: Pull complete 
Digest: sha256:3fd88c55ce477af810e1571c99325f34126b298050b05150138735faa2cf6598
Status: Downloaded newer image for apache/apisix:3.3.0-debian
docker.io/apache/apisix:3.3.0-debian`

**Comment by shreemaan-abhishek** [comment]
It works on my laptop, did you try to run this command on your laptop to see if it works?

Also, could you try images with other tags/versions to verify if this problem happens only with particular versions of apisix images?

**Comment by lingsamuel** [comment]
Please contact the provider. The images are OK.
