### ISSUE TITLE
[Site]: Getting Started

### ISSUE THREAD

**Issue by codingWombat** [apache/apisix#9699]
### Current State

**Description of the current state/issue**:
Link to getting-started page results in 404 
**Link to the page**:
https://apisix.apache.org/docs/apisix/installation-guide/getting-started.md/

**Screenshots (if relevant)**:
![image](https://github.com/apache/apisix-website/assets/33450945/179250fc-2911-41df-9558-03ca079ef11c)

### Desired State

**Description of the change you are proposing**:
Provide proper content instead object not found.

### Would you like to fix this issue?

None

**Comment by xuruidong** [comment]
This issue is fixed  in master branch , #9501

**Comment by yzeng25** [comment]
Verified on page: https://apisix.apache.org/docs/apisix/installation-guide/ , the broken links were changed to  https://apisix.apache.org/docs/apisix/getting-started/README/ in current version, thus close this issue.
