### ISSUE TITLE
help request: apisix can't find the skywalking plug-in has been configured

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9702]
### Description

![1687244760067](https://github.com/apache/apisix/assets/63503074/9af163a1-0cc0-439f-a3fd-7ac66c4ad207)
![image](https://github.com/apache/apisix/assets/63503074/8a89bbb2-9d7c-4f53-adb9-2e0816e34bb8)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Can you also show the configuration of apisix-dashboard like this one https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml?

**Comment by llp520-jkcs** [comment]
你好感谢你的解答，按照你的配置没有效果
![1687252144919](https://github.com/apache/apisix/assets/63503074/0702428d-b303-40f6-b573-9a2a7f9c2f02)
![1687252155344](https://github.com/apache/apisix/assets/63503074/d77b2789-8dc0-4219-b7a6-e6a692b485b0)
![1687252164697](https://github.com/apache/apisix/assets/63503074/677c06e6-bc3c-4801-9c68-70132f1c4926)
![image](https://github.com/apache/apisix/assets/63503074/1d00867c-78ce-43b4-9250-7ce338dbdc66)

**Comment by lingsamuel** [comment]
apisix and apisix-dashboard have different config. Please make sure your apisix-dashboard have enabled skywalking plugin

**Comment by llp520-jkcs** [comment]
插件里面没有，寻求帮助

**Comment by Revolyssup** [comment]
@llp520-jkcs How did you install apisix-dashboard?

**Comment by llp520-jkcs** [comment]
I tried installing it through Docker Compose

**Comment by shreemaan-abhishek** [comment]
@llp520-jkcs, please try the admin API and let us know if it works.
