### ISSUE TITLE
feat:  opa plugins, add the ability to set headers  

### ISSUE THREAD

**Issue by chusov** [apache/apisix#9704]
### Description

opa plugin can set headers if the policy response is false - https://apisix.apache.org/docs/apisix/plugins/opa/#using-custom-response 
I would like to be able to set headers for a request if the policy response is true. 
Use cases - to send to the backend the status of the policy, the policy name, fields from the JWT token.
The changes are not so big, so I can prepare a MR

**Comment by Revolyssup** [comment]
@lingsamuel Please assign it to me.

**Comment by chusov** [comment]
@Revolyssup 
opa can also return:

`response_headers_to_add (optional)`: an object mapping a string header name to a string header value
`request_headers_to_remove (optional)`: is an array of string header names


https://www.openpolicyagent.org/docs/latest/envoy-primer/#output-document

**Comment by Revolyssup** [comment]
> opa plugin can set headers if the policy response is false

Is this part of your use case?

**Comment by Revolyssup** [comment]
> @Revolyssup opa can also return:
> 
> `response_headers_to_add (optional)`: an object mapping a string header name to a string header value `request_headers_to_remove (optional)`: is an array of string header names
> 
> https://www.openpolicyagent.org/docs/latest/envoy-primer/#output-document

Is this part of your use case?

**Comment by chusov** [comment]
> Is this part of your use case?
not really) sorry

**Comment by Sn0rt** [comment]
@chusov hi, can you provider an HTTP header for the usage?

**Comment by Revolyssup** [comment]
@chusov Will you take a look at this PR to see if it fits your use case? https://github.com/apache/apisix/pull/9710
