### ISSUE TITLE
apisix中找不到skywalking插件

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9705]
### Description

![image](https://github.com/apache/apisix/assets/63503074/ed8c3d33-c073-4332-b447-905f4e708c14)
![image](https://github.com/apache/apisix/assets/63503074/b14652ea-8bd3-4b18-9122-141d4c194428)
![image](https://github.com/apache/apisix/assets/63503074/39d98e7c-33a7-4534-87e9-c594f12958b1)
![image](https://github.com/apache/apisix/assets/63503074/8ce78d4e-bee2-4b40-a49b-e98a37217207)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by lingsamuel** [comment]
do NOT file duplicate issue
