### ISSUE TITLE
Can there be a k8s-specific mode

### ISSUE THREAD

**Issue by zhaomingcheng01** [apache/apisix#9714]
### Description

apisix目前支持全量yaml模式,但是又一个痛点就是devops需要有k8s得权限去操作configmap,我们是cicd分开,devops做ci部分,cd又argocd做,而且实际运行过程中etcd总出问题,一会死一个节点,难以维护
能不能有一种支持以K8S的crd为配置中心的模式,这样不用将所有的东西放在yaml中难以维护,还要授权,也不用在去维护单独的etcd集群

**Comment by zhaomingcheng01** [comment]
能不能通过apisix的ingress controller输出为yaml,然后apisix通过刷新yaml的模式,达到全量crd的模式

**Comment by zhixiongdu027** [comment]
are u interested in this #4388
