### ISSUE TITLE
help request: i want use apisix to proxy "forword-proxy" , I want to implement cascading forward proxy function through apisix

### ISSUE THREAD

**Issue by NJLOVER** [apache/apisix#9719]
### Description

我希望通过apisix来代理访问所有的正向代理服务，这样我只需要配置apisix的地址作为代理服务节点。但是现在apisix 会阻止https协议代理的CONNECT方法，异常为client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT tch686548.tch.poe.com:443 HTTP/1.1"

### Environment

- APISIX version (run `apisix version`): 2.15.1
- Operating system (run `uname -a`): Linux a5a18cbebbe7 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by NJLOVER** [comment]
{
        "createdIndex": 42806168,
        "modifiedIndex": 42806168,
        "key": "\/apisix\/routes\/forward",
        "value": {
          "methods": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "CONNECT"
          ],
          "id": "forward",
          "priority": -2,
          "uri": "*",
          "host": "proxy.xxxxx.com",
          "status": 1,
          "upstream": {
            "scheme": "http",
            "type": "roundrobin",
            "hash_on": "vars",
            "pass_host": "pass",
            "nodes": {
              "httpbin.default.svc:8080": 1
            }
          }
        }

**Comment by shreemaan-abhishek** [comment]
ENGLISH:

I hope to proxy access to all forward proxy services through apisix, so I only need to configure the address of apisix as a proxy service node. But now apisix will prevent the CONNECT method of https protocol proxy, the exception is client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT tch686548.tch.poe.com:443 HTTP/1.1 "

**Comment by shreemaan-abhishek** [comment]
@NJLOVER please share any relevant error logs.

**Comment by NJLOVER** [comment]
2023/06/25 18:20:42 [info] 50#50: *36010305 client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT beacons.gcp.gvt2.com:443 HTTP/1.1"
2023/06/25 18:20:42 [info] 49#49: *36010308 client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT beacons2.gvt2.com:443 HTTP/1.1"
2023/06/25 18:20:42 [info] 50#50: *36010309 client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT beacons4.gvt2.com:443 HTTP/1.1"
2023/06/25 18:20:42 [info] 50#50: *36010311 client sent invalid request while reading client request line, client: 172.30.5.99, server: _, request: "CONNECT beacons5.gvt3.com:443 HTTP/1.1"

**Comment by shreemaan-abhishek** [comment]
This looks like a very generic error from nginx, did you confirm that other methods like GET, PUT, etc work normally?

**Comment by Revolyssup** [comment]
@NJLOVER Can you show the request body or the whole HTTP request that is being sent?
