### ISSUE TITLE
Cannot download source from the website

### ISSUE THREAD

**Issue by lujiajing1126** [apache/apisix#9724]
### Current State

https://apisix.apache.org/downloads/

Both 3.2.1LTS and 3.3.0 are missing from the Apache mirror.

I suppose the release manager should move artifacts from https://dist.apache.org/repos/dist/dev/apisix/ to https://dist.apache.org/repos/dist/release/apisix/. Multiple version are left in the dev SVN.

https://infra.apache.org/release-publishing.html#uploading

### Desired State

Sources can be downloaded

**Comment by tao12345666333** [comment]
Thanks for your feedback, I helped the RM operate SVN.

**Comment by tao12345666333** [comment]
![image](https://github.com/apache/apisix/assets/3264292/028fff07-d026-4d73-bb51-187fc9087bea)

**Comment by tao12345666333** [comment]
![image](https://github.com/apache/apisix/assets/3264292/028fff07-d026-4d73-bb51-187fc9087bea)

**Comment by tao12345666333** [comment]
![image](https://github.com/apache/apisix/assets/3264292/028fff07-d026-4d73-bb51-187fc9087bea)

**Comment by lujiajing1126** [comment]
Thanks. I confirm it works now.
