### ISSUE TITLE
help request: is there any way to disable script 

### ISSUE THREAD

**Issue by ZhangShangyu** [apache/apisix#9725]
### Description

we want to disable or forbid script in route/service to avoid script inject attack, so is there an option to disable run script?

### Environment

apisix: 2.15.3

**Comment by shreemaan-abhishek** [comment]
What does forbid script mean? I tried to search for it on google but found nothing. Could you please re-explain?

**Comment by ZhangShangyu** [comment]
> What does forbid script mean? I tried to search for it on google but found nothing. Could you please re-explain?

here https://apisix.apache.org/docs/apisix/terminology/script/

**Comment by ZhangShangyu** [comment]
hi @lingsamuel can assign this feature to me?

**Comment by lingsamuel** [comment]
Assigned, thanks!

**Comment by shreemaan-abhishek** [comment]
@ZhangShangyu this is now in progress #10154

**Comment by shreemaan-abhishek** [comment]
For now, this feature cannot be removed. Ref: https://lists.apache.org/thread/5tjhy7f4g2znspzkgmfps6yw6lxz3xgv
