### ISSUE TITLE
help request: Request Error Code: 10000 schema validate failed: schema not found, path: plugins.ext-plugin-post-resp

### ISSUE THREAD

**Issue by forget99** [apache/apisix#9729]
### Description

我在apisix dashboard编辑路由时，在路由数据编辑器中添加`ext-plugin-post-resp`，apisix dashboard error reporting：

`Request Error Code: 10000 schema validate failed: schema not found, path: plugins.ext-plugin-post-resp`

请技术老师帮我看下，谢谢！

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Can you confirm that `ext-plugin-post-resp` exists in your dashboard configuration here? https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml

**Comment by forget99** [comment]
> Can you confirm that `ext-plugin-post-resp` exists in your dashboard configuration here? https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml

@Revolyssup I deploy Apisix in Docker，I modified the dashboard configuration file, but it didn't work。
`/apisix-docker/example/dashboard_conf/config.yaml`

`
plugins:         # plugin list (sorted in alphabetical order)
  - api-breaker
  - authz-keycloak
  - basic-auth
  - batch-requests
  - consumer-restriction
  - cors
  # - dubbo-proxy
  - echo
  # - error-log-logger
  # - example-plugin
  - fault-injection
  - grpc-transcode
  - hmac-auth
  - http-logger
  - ip-restriction
  - jwt-auth
  - kafka-logger
  - key-auth
  - limit-conn
  - limit-count
  - limit-req
  # - log-rotate
  # - node-status
  - openid-connect
  - prometheus
  - proxy-cache
  - proxy-mirror
  - proxy-rewrite
  - redirect
  - referer-restriction
  - request-id
  - request-validation
  - response-rewrite
  - serverless-post-function
  - serverless-pre-function
  # - skywalking
  - sls-logger
  - syslog
  - tcp-logger
  - udp-logger
  - uri-blocker
  - wolf-rbac
  - zipkin
  - server-info
  - traffic-split
  - ext-plugin-post-resp
`

**Comment by forget99** [comment]
> Can you confirm that `ext-plugin-post-resp` exists in your dashboard configuration here? https://github.com/apache/apisix-dashboard/blob/master/api/conf/conf.yaml

> @Revolyssup I deploy Apisix in Docker，I modified the dashboard configuration file, but it didn't work。 `/apisix-docker/example/dashboard_conf/config.yaml`

`
plugins:         # plugin list (sorted in alphabetical order)
     - ext-plugin-post-resp
`
