### ISSUE TITLE
如何绑定ssl证书----How to bind SSL certificates

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9731]
### Description

![image](https://github.com/apache/apisix/assets/63503074/c25a869c-586d-401e-9a71-87d389627adf)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by llp520-jkcs** [comment]
How does Apisix bind certificates and redirect to https through domain name

**Comment by llp520-jkcs** [comment]
How to bind SSL certificates

![image](https://github.com/apache/apisix/assets/63503074/54ac40ea-e5da-4aa0-8219-6680be0074c0)
![image](https://github.com/apache/apisix/assets/63503074/ea90c659-6327-4d61-a1fd-32297149fb90)

**Comment by shreemaan-abhishek** [comment]
Please check this out: https://apisix.apache.org/docs/apisix/mtls/

**Comment by Revolyssup** [comment]
@llp520-jkcs To reach APISIX on 443, you can enable ssl from here[1] and for http to https redirection, you can use redirect plugin.[2]. To use mTLS to communicate with Upstream, you can use the tls.client_cert/key in the upstream[3].
Also can you elaborate your use case a little? Whats the flow of request?


1. https://github.com/apache/apisix/blob/acffe99a74818c28da55c15b381a732438dfee9d/conf/config-default.yaml#L99
2. https://apisix.apache.org/docs/apisix/plugins/redirect/
3. https://apisix.apache.org/docs/apisix/admin-api/#request-body-parameters-3

**Comment by llp520-jkcs** [comment]
![1687859375940](https://github.com/apache/apisix/assets/63503074/2b604b4e-fbda-495e-8785-338c45596ff0)

**Comment by llp520-jkcs** [comment]
![image](https://github.com/apache/apisix/assets/63503074/e531a745-f2d0-45cf-ac5b-2aa754bf9ab1)
