### ISSUE TITLE
feat: As a user, I want to openid-connect support post check, so that I can do authz based on token

### ISSUE THREAD

**Issue by wenerme** [apache/apisix#9735]
### Description

As a user, I want to openid-connect support post check, so that I can do authz based on token.

- authz-keycloak is complicated, don't support some features (e.g. check groups).
- openid-connect is easy to setup

I hope I can post check the token to do authz, e.g.

```yaml
post_check: |
  return local function(access_token,id_token,userinfo,conf,ctx)
   // check access_token.groups contains something
   return 401, '{}'
  end
```

**Comment by wenerme** [comment]
xref https://github.com/apache/apisix/issues/8772

**Comment by Revolyssup** [comment]
@wenerme Similar to https://github.com/apache/apisix/issues/8772, You want to further restrict access by matching claims right?

**Comment by Revolyssup** [comment]
@lingsamuel Assign this to me

**Comment by wenerme** [comment]
@Revolyssup yes, but I try to using opa now, opa can work with oidc, can share with other context. If apisix don't want to handle the random script, can tell other user to use opa too. I searched the issues, there are few related to this post check, by allowing passing script is the only way to match all these requests.

**Comment by Revolyssup** [comment]
> @Revolyssup yes, but I try to using opa now, opa can work with oidc, can share with other context. If apisix don't want to handle the random script, can tell other user to use opa too. I searched the issues, there are few related to this post check, by allowing passing script is the only way to match all these requests.

If OPA solved your use case, we can close this issue and continue tracking https://github.com/apache/apisix/issues/8772

**Comment by Revolyssup** [comment]
@wenerme Any updates here?

**Comment by wenerme** [comment]
@Revolyssup ok to close this.
