### ISSUE TITLE
feat: As a user, I want to try loggly logger, so that I not want mock test

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#9739]
### Description

I find this `t/plugin/loggly.t` test case still uses a mock test case.

If possible, it is expected to use the real backend to test this plugin, because I found that several logger plugins passed the test case test using the mock, but could not really work.

this is a mock server.

```lua
add_block_preprocessor(sub {
    my ($block) = @_;

    $block->set_value("stream_conf_enable", 1);

    if (!defined $block->extra_stream_config) {
        my $stream_config = <<_EOC_;
    server {
        listen 8126 udp;
        content_by_lua_block {
            -- mock udp server is just accepts udp connection and log into error.log
            require("lib.mock_layer4").loggly()
        }
    }
...
```

**Comment by Revolyssup** [comment]
Please assign to me

**Comment by Revolyssup** [comment]
@Sn0rt Loggly is cloud based and provided by solar winds. I couldn't find a loggly server either packaged as a docker image or otherwise. I thinks its paid only. How should we proceed here?

**Comment by Sn0rt** [comment]
> @Sn0rt Loggly is cloud based and provided by solar winds. I couldn't find a loggly server either packaged as a docker image or otherwise. I thinks its paid only. How should we proceed here?

can you confirm this with loggly plugin developer ?

**Comment by Revolyssup** [comment]
> @Sn0rt Loggly is cloud based and provided by solar winds. I couldn't find a loggly server either packaged as a docker image or otherwise. I thinks its paid only. How should we proceed here?

@spacewander Can you confirm this?

**Comment by Sn0rt** [comment]
@Revolyssup skip this issues.
