### ISSUE TITLE
How Apisix uses HTTPS access. Urgently request everyone's help

### ISSUE THREAD

**Issue by val-stu** [apache/apisix#9741]
### Description

![image](https://github.com/apache/apisix/assets/63503074/d9f222bb-4abf-4bb9-b68d-6554a081f6b0)
![image](https://github.com/apache/apisix/assets/63503074/89285ec2-b043-40ea-8c23-16a08c06dca8)
![image](https://github.com/apache/apisix/assets/63503074/2504c9d8-ed92-4b4b-bd20-9b0fb3791601)
![image](https://github.com/apache/apisix/assets/63503074/07269fe3-6c2b-4597-bd78-493e46c6d255)
![image](https://github.com/apache/apisix/assets/63503074/e38d87e8-654a-4dab-8a32-643bd097cba6)
![image](https://github.com/apache/apisix/assets/63503074/e43ffd27-d858-403c-9ff3-36fd42e7f81f)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
please add screenshots containing english description so that everyone can help..

**Comment by llp520-jkcs** [comment]
I want to proxy this service through Apisix HTTPS 162.62.115.41:443

But now access through apisix9443 is not possible. You can take a closer look at the screenshot, which is the question I want to express

**Comment by oyiadin** [comment]
I can read Chinese but I still cannot catch up with your question.  Could you please describe your question in more detailed English, and do not use too much screenshot? Because images are hardly indexed by Google and they are not friendly for searching purpose.

By the way, it seems that you haven't finished you DNS configurations for your domain `seekseek.com`. I think it's somewhat unrelated with HTTPS.

**Comment by season886** [comment]
你是不是想跳转到443端口而不是9443？如果这样的话你在配置文件加上这个
plugin_attr:
  redirect:
    https_port: 443

**Comment by shreemaan-abhishek** [comment]
@llp520-jkcs, did you try @season886's suggestion?
