### ISSUE TITLE
Inconsistent Behaviours in APISIX CLI

### ISSUE THREAD

**Issue by kayx23** [apache/apisix#9742]
### Description

Relevant file: https://github.com/apache/apisix/blob/master/apisix/cli/ops.lua

### 1. Command `-h` option

A help menu for `apisix start` is printed if I run `apisix start -h`:
![image](https://github.com/apache/apisix/assets/39619599/c531f265-0943-4b34-a6c3-111c76c781ac)

However, `-h` does not seem to work for the other CLI commands, which is unexpected from a user perspective.

For example, `-h` is ignored in the following examples with other commands:

![image](https://github.com/apache/apisix/assets/39619599/79606e06-af1b-4e41-a548-2dac0482a76b)

### 2. `--verbose` option

https://github.com/apache/apisix/blob/9993bbbbb139cab312e7581836ac35da5fe51500/apisix/cli/ops.lua#L801

* This should accept `-v` as well.
* `apisix init_etcd --verbose` did not print additional debug info for me, compared with the output of `apisix init_etcd`. Is this how it's used? If so, can others share their results?

### Environment

- APISIX version: 3.3.0
- Operating system: CentOS 8

**Comment by Revolyssup** [comment]
@lingsamuel I can take this

**Comment by kayx23** [comment]
any update?

**Comment by Revolyssup** [comment]
@kayx23 This got lost. Thanks for reminder. Putting this into backlog and will process it.

**Comment by Revolyssup** [comment]
@kayx23 For the 2nd point, `--verbose` is to be used with `apisix start` and not `apisix init_etcd`. Example screenshot attached below. 
![Screenshot from 2023-08-29 10-19-49](https://github.com/apache/apisix/assets/43276904/6424b314-931f-4e0c-a526-7456a3913830)

For the 1st point, flag parsing is not consistent right now as it's not done in commands other than `start`. I think it's okay to have these flags local to start command as they are of little use in other commands. Either you can add this in the docs that the flags are not global or if this causes confusion with users then we can make `-h` flag global.

**Comment by kayx23** [comment]
Thanks for the help. One last thing, should there be a `-v` as well, shorthand for `--verbose`? Similar to`-h` to `--help` and `-c` to `--config`.

**Comment by Revolyssup** [comment]
> `-v` a

Yep, this suggestion makes sense to me. I will create a PR for this.
