### ISSUE TITLE
Be able to set route id in Kubernetes resource

### ISSUE THREAD

**Issue by frankkoornstra** [apache/apisix#9743]
### Description

When a route gets created from the [Kubernetes resource](https://apisix.apache.org/docs/ingress-controller/references/apisix_route_v2beta3/) there's no way to create the id deterministically (by providing a `route_id` for example) or to even get the id from the status of the resource; only when I log in to the dashboard, I can get the route id.

I need the route id to be able to programmatically create consumers that I want to restrict to a route with `consumer-restrict` through the Admin API . Also I need it to analyze my reported traffic in a completely different service.

I would be very happy if we could determine the id beforehand with an optional `route_id` in the spec. If that's not possible, could the id be returned in the status of the k8s resource?

**Comment by shreemaan-abhishek** [comment]
@tao12345666333 please transfer this issue to the ingress controller repository.

**Comment by frankkoornstra** [comment]
Apologies, did not realize those were separate repos, I'll recreate it there :)
