### ISSUE TITLE
 apisix kubernetes multi-cluster service discovery？

### ISSUE THREAD

**Issue by Michael754267513** [apache/apisix#9744]
### Description

apisix kubernetes multi-cluster service discovery. Currently, only service_name in a single cluster can be matched. -- For example, if a service is deployed in clusters a and b, how do I configure apisix.sixsixsix.com to access the service in clusters A and b?

### Environment

- APISIX version (run `apisix version`):  v3.3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):   openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): "version":"3.3.0","etcd_version":"3.4.0"
- APISIX Dashboard version, if relevant: 
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by zhixiongdu027** [comment]
In multi-cluster mode, the format of service name contains the cluster id
