### ISSUE TITLE
help request: get upstream body in serverless plugin

### ISSUE THREAD

**Issue by ikatlinsky** [apache/apisix#9747]
### Description

I am trying to use https://apisix.apache.org/docs/apisix/plugins/serverless/ to get the response body of the upstream resource to add additional headers to the response based on body content, however, I cannot find a way to access the body of the upstream and have the ability to set headers. Can someone point me in the right direction?

### Environment

- APISIX version (run `apisix version`): 3.3.0

**Comment by shreemaan-abhishek** [comment]
Did you try `core.response.hold_body_chunk()`? 

https://github.com/shreemaan-abhishek/apisix/blob/6af89d675653ead0b4ce0a241d870fa5a1ed2a19/apisix/core/response.lua#L167-L177

**Comment by ikatlinsky** [comment]
yes, the problem is that it is only available in the body_filter phase, but in this phase, I am not allowed to update the headers of the response, as body_filter is executed after the header_filter phase which closes the window for headers manipulation.

**Comment by shreemaan-abhishek** [comment]
I see, I am not sure if this is possible.

**Comment by jiangfucheng** [comment]
@ikatlinsky  @shreemaan-abhishek  Maybe we can support set multi-phase in `serverless` plugin, what do you think?
example configuration:
```
"serverless-pre-function": {
    "phases": [
    	{
    		"phase": "body_filter",
    		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
    	},
    	{
    		"phase": "header_filter",
    		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
    	}
    ]
}
```

**Comment by ikatlinsky** [comment]
It would be a nice feature, especially if we will have the ability to pass data between phases. Though, it will not help in my case, as the order of the phases is strict and cannot be changed - the header stage is always before the body stage, while described case needs them to be reversed.

**Comment by jiangfucheng** [comment]
You are right, I didn't fully understand your needs before.
