### ISSUE TITLE
bug: Route not found and SSL routines:ssl3_read_bytes:tlsv1 alert internal error (please address it immediately)

### ISSUE THREAD

**Issue by shivraj001** [apache/apisix#9748]
### Current Behavior

I'm getting issues while accessing a route via https to  httpbin service provided in apisix documentation. httpbin service is running in kubernetes.
I tried multiple curl command for http request, some of them succeeds but most of them ends up with below  error:
error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error

Find the attachment below

![Selection_2992](https://github.com/apache/apisix/assets/70901133/c52cf6dd-0381-4aab-b481-acd53c148822)

And with http requet below the response (route not found)

![Selection_303](https://github.com/apache/apisix/assets/70901133/3f1b764b-9d88-4772-91b5-5f54cdadd25b)

### Expected Behavior

success response from httpbin backend service running in kubernetes.

### Error Logs

For https: curl: (35) error:14094438:SSL routines:ssl3_read_bytes:tlsv1 alert internal error
For http: {"error_msg":"404 Route Not Found"}

APISIX Logs (Not sure why is this happening)

2023/06/28 15:00:40 [error] 32875#32875: *4102578 [lua] radixtree_sni.lua:176: match_and_set(): failed to find any SSL certificate by SNI: test-stage.**.com, context: ssl_certificate_by_lua*, client: 192.168.7.213, server: 0.0.0.0:9443

I could see some errors about etcd as well (need help here as well)

2023/06/28 15:02:38 [warn] 33226#33226: *4115258 [lua] plugin.lua:252: load_stream(): new plugins: {"limit-conn":true,"syslog":true,"mqtt-proxy":true,"ip-restriction":true}, context: init_worker_by_lua*
2023/06/28 15:02:41 [alert] 1#1: worker process 33199 exited on signal 9
2023/06/28 15:02:41 [error] 33208#33208: *4115026 [lua] config_etcd.lua:634: failed to fetch data from etcd: closed,  etcd key: /apisix/protos, context: ngx.timer
2023/06/28 15:02:41 [error] 33208#33208: *4115038 [lua] config_etcd.lua:634: failed to fetch data from etcd: closed,  etcd key: /apisix/plugin_configs, context: ngx.timer
2023/06/28 15:02:41 [error] 33217#33217: *4115342 [lua] config_etcd.lua:634: failed to fetch data from etcd: closed,  etcd key: /apisix/ssls, context: ngx.timer
2023/06/28 15:02:41 [error] 33217#33217: *4115341 [lua] config_etcd.lua:634: failed to fetch data from etcd: closed,  etcd key: /apisix/routes, context: ngx.timer
2023/06/28 15:02:41 [error] 33217#33217: *4115350 [lua] config_etcd.lua:634: failed to fetch data from etcd: closed,  etcd key: /apisix/upstreams, context: ngx.timer
2023/06/28 15:02:38 [warn] 33226#33226: *4115547 stream [lua] plugin.lua:252: load_stream(): new plugins: {"ip-restriction":true,"limit-conn":true,"syslog":true,"mqtt-proxy":true}, context: init_worker_by_lua*

Got this for http request in logs

2023/06/28 18:35:01 [warn] 67532#67532: *5230083 [lua] plugin.lua:252: load_stream(): new plugins: {"limit-conn":true,"syslog":true,"mqtt-proxy":true,"ip-restriction":true}, context: init_worker_by_lua*
192.168.7.213 - - [28/Jun/2023:18:35:04 +0000] test-stage.**.com "GET /headers HTTP/1.1" 404 47 0.000 "-" "curl/7.68.0" - - - "http://test-stage.**.com"

### Steps to Reproduce

1. Load ssl certificate for SNI 
2. Run httpbin service in kubernetes
3. Create route for httpbin as upstream 
4. Use curl command and hit multiple request with http and https 

### Environment

- APISIX version (apisix 3.3):
- Operating system (linux):
- APISIX ingress controller (1.6.0):
- etcd version, if relevant (3.5.9):
- APISIX Dashboard version, (3.0.0):

**Comment by shreemaan-abhishek** [comment]
Which method did you use to install APISIX?

**Comment by shivraj001** [comment]
I used APISIX Helm chart @shreemaan-abhishek

**Comment by Revolyssup** [comment]
@shivraj001 How did you create route? Using APISIXRoute? Can you provide the configuration that you used?

**Comment by shivraj001** [comment]
@Revolyssup i have created this route by calling adminapi, this how configuration looks after fetching it with get route request
{
  "uri": "/*",
  "name": "testroute1",
  "desc": "v1",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "host": "test-stage.**.com",
  "upstream": {
    "nodes": [
      {
        "host": "httpbin.default.svc.cluster.local",
        "port": 80,
        "weight": 100
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },

  "status": 1
}

**Comment by Revolyssup** [comment]
@shivraj001 I see that you have passed `host` in your route configuration but you dont set it in your curl commands. Can you try adding proper Host header.

**Comment by shreemaan-abhishek** [comment]
@shivraj001, how did you manage to call the admin API with helm-based installation? 🤔

**Comment by shivraj001** [comment]
@Revolyssup I don't think there should be any issue with host header here as in curl command, I'm passing the host name in url itself so it should use the set host name in header also.

**Comment by shivraj001** [comment]
@shreemaan-abhishek  Since ApisixRoute was also giving the same error which i'm facing right now. I port-forwarded the admin api port in my local to troubleshoot it.

**Comment by shreemaan-abhishek** [comment]
@shivraj001, could you please check if `etcd` contains the route?

You can use the command `etcdctl get /apisix/routes --prefix`

**Comment by shivraj001** [comment]
Hi @shreemaan-abhishek ! I cleaned up the setup and re-installed every thing, now things work fine. I tried to reproduce the issue but not able to do it.
I'm closing this issue for now. If any help required I will reach out here again. Thanks. :)
