### ISSUE TITLE
help request: Apisix delays for a certain period of time before forwarding the request to the upstream service

### ISSUE THREAD

**Issue by hardme** [apache/apisix#9757]
### Description

通过网卡抓包发现apisix收到客户端请求后,经过一段时间延迟后，请求才会发送给上游服务

### Environment

- APISIX version (run `apisix version`):2.13.2

**Comment by Revolyssup** [comment]
Can you elaborate on how much the delay is? On which type of requests? What is the configuration? Please provide some more details.

**Comment by hardme** [comment]
> Can you elaborate on how much the delay is? On which type of requests? What is the configuration? Please provide some more details.

延迟在1-10s都有，不过大部分在1-2s，是正常的http请求，上游配置的是k8s的svc地址

**Comment by woniuxu** [comment]
我们也遇到这个问题，tcpdump抓包，http包的Arrival Time: Jul 20, 2023 21:23:58.495873000 CST；
但是access log里面的timestamp是 2023-07-20 21:23:58.757； delay了200多毫秒。开了debug日志暂时看不出问题，有什么建议吗？

**Comment by woniuxu** [comment]
post请求，版本是2.11.0

**Comment by hardme** [comment]
> post请求，版本是2.11.0

参考：https://apisix.apache.org/zh/blog/2023/03/06/the-mystery-of-prometheus-plugins-and-long-tail-requests/
可以去掉prometheus插件或者升级3.0之后的版本
