### ISSUE TITLE
How Apisix uses TCP to connect to MySQL

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9758]
### Description

I want to connect to MySQL through TCP, but this error occurred and APisix did not start on port 9101. Why

![4EY@59 6 `G% % YON8J$%3](https://github.com/apache/apisix/assets/63503074/b03879d2-f416-457d-a96d-4855f5842e72)
![3~2WF$P~_ T~VOGCC1`)S9N](https://github.com/apache/apisix/assets/63503074/2538877c-334d-4ec1-91a2-4aeb20eafd5f)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by llp520-jkcs** [comment]
![4EY@59 6 `G% % YON8J$%3](https://github.com/apache/apisix/assets/63503074/03ef5a2d-e9a8-48be-82b3-c7c86ed3dfae)

**Comment by shreemaan-abhishek** [comment]
Change the `server_port` in your stream route config to `9501`. And add the following snippet for your `stream_proxy` tcp configuration:

```yaml
  stream_proxy:
    tcp:
      - "<your-ip-that-you-have-hidden-in-the-screenshot>:9501"
```

**Comment by kayx23** [comment]
The [documentation](https://apisix.apache.org/docs/apisix/stream-proxy/#more-stream-route-filtering-options) on this topic includes an example for MySQL that is actually quite clear. As @shreemaan-abhishek pointed out, you have misalignment in your configuration and request. Closing this one now but you may reopen if you still need help. Thanks.
