### ISSUE TITLE
help request: consumer-restriction配置consumer_group_id后api返回"Missing authentication or identity verification."

### ISSUE THREAD

**Issue by gzlboy** [apache/apisix#9761]
### Description

使用consumer-restriction+basic-auth插件，consumer-restriction 配置type为consumer_name时接口返回符合预期，但当把consumer-restriction的type改成consumer_group_id后(设置了blacklist)，不是黑名单内的consumer访问api，就会返回：
{"message":"Missing authentication or identity verification."}
如果使用黑名单内的consumer登录，返回是正常的：
{"message":"The consumer_group_id is forbidden."}

请教是什么原因呀？

`{
    "plugins": {
        "consumer-restriction": {
            "type": "consumer_group_id",
            "blacklist": [
                "web1"
            ]
        }
    }
}`
注：web1为group_id

apisix版本：3.3.0

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Can you set the log level to info and search for the log starting with `consumer: ` when you send request for a non blacklist consumer to confirm which consumer is selected?
Also please provide the consumer configuration as well and the requests you are sending.

**Comment by gzlboy** [comment]
dataPlane logs:
![image](https://github.com/apache/apisix/assets/1492060/8b16295b-e5e6-47d1-a91a-a346b6b94b3b)

consumer jack:
![image](https://github.com/apache/apisix/assets/1492060/29eaeddc-2a9a-4b22-a26d-36edaf62c7e0)

consumer nginxUser1:
![image](https://github.com/apache/apisix/assets/1492060/29196aee-1103-4a69-b926-6581aeb273d9)

router config:
`{
    "createdIndex": 72,
    "value": {
        "methods": [
            "GET",
            "POST",
            "PUT",
            "DELETE",
            "PATCH",
            "HEAD",
            "OPTIONS",
            "CONNECT",
            "TRACE",
            "PURGE"
        ],
        "upstream": {
            "nodes": {
                "nginx-service:80": 1
            },
            "type": "roundrobin",
            "timeout": {
                "send": 6,
                "read": 6,
                "connect": 6
            },
            "hash_on": "vars",
            "scheme": "http",
            "keepalive_pool": {
                "idle_timeout": 60,
                "size": 320,
                "requests": 1000
            },
            "pass_host": "pass"
        },
        "id": "467386148696622209",
        "plugins": {
            "consumer-restriction": {
                "blacklist": [
                    "web1"
                ],
                "_meta": {
                    "disable": false
                },
                "type": "consumer_group_id",
                "rejected_code": 403
            },
            "proxy-rewrite": {
                "use_real_request_uri_unsafe": false,
                "regex_uri": [
                    "/bbb/(.*)",
                    "/$1"
                ]
            },
            "basic-auth": {
                "_meta": {
                    "disable": false
                },
                "hide_credentials": false
            }
        },
        "uri": "/bbb/*",
        "update_time": 1688114202,
        "priority": 0,
        "create_time": 1688113453,
        "name": "nginx",
        "status": 1
    },
    "key": "/apisix/routes/467386148696622209",
    "modifiedIndex": 78
}`

帮看下，多谢！

**Comment by jiangfucheng** [comment]
https://github.com/apache/apisix/blob/f2337f25d4bdbe7291810f36c0fbedd5cea8d29d/apisix/plugins/consumer-restriction.lua#L127C5-L132

It's a bug, the consumer "nginxUser1" not belong any `consumer_group`,  the request should be passed. I'll fix it.

**Comment by Revolyssup** [comment]
@jiangfucheng Hmm I agree with you. Let's get you assigned on this.

**Comment by Revolyssup** [comment]
@gzlboy Meanwhile, you can either wait for the fix or give a consumer group to `nginxUser1` which is not blacklisted

**Comment by gzlboy** [comment]
> @gzlboy Meanwhile, you can either wait for the fix or give a consumer group to `nginxUser1` which is not blacklisted

ok,thanks!
