### ISSUE TITLE
help request: is it possible to modify the upstream in the ext-plugin

### ISSUE THREAD

**Issue by puzhaonan** [apache/apisix#9764]
### Description

我有一个在ext-plugin中修改上游的需求，请问在ext-plugin中可以修改上游么？

I have a requirement to modify the upstream in ext-plugin. Can I modify the upstream in ext-plugin?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Not really. Upstream are bound on Route or a service. The plugins are executes after route matching so the upstream bound on that route will serve the request. What is your exact use case? Maybe if you lay down your use case, we can give a better solution.

**Comment by puzhaonan** [comment]
I want to have a function that can dynamically add gray mark to the request header, and can route to the gray environment according to the gray mark by the percentage of traffic, the percentage requirement can be accurate to less than 5%, the official traffic splitting plug-in does not meet my needs

**Comment by puzhaonan** [comment]
> Not really. Upstream are bound on Route or a service. The plugins are executed after route matching so the upstream bound on that route will be used. What is your exact use case? Maybe if you lay down your use case, we can give a better solution.

I want to have a function that can dynamically add gray mark to the request header, and can route to the gray environment according to the gray mark by the percentage of traffic, the percentage requirement can be accurate to less than 5%, the official traffic splitting plug-in does not meet my needs

**Comment by Revolyssup** [comment]
@puzhaonan How does the weighted upstream field in the traffic-split plugin not helping here?[1] Because it's not allowing header manipulation?

1. https://apisix.apache.org/docs/apisix/plugins/traffic-split/#canary-release

**Comment by puzhaonan** [comment]
> @puzhaonan How does the weighted upstream field in the traffic-split plugin not helping here?[1] Because it's not allowing header manipulation?
> 
> 1. https://apisix.apache.org/docs/apisix/plugins/traffic-split/#canary-release

Whether this plug-in can be divided by 1% traffic

**Comment by Revolyssup** [comment]
@puzhaonan Can you use weight as 99 and 1?

**Comment by puzhaonan** [comment]
> @puzhaonan Can you use weight as 99 and 1?

thanks, I'll have a try

**Comment by puzhaonan** [comment]
> @puzhaonan Can you use weight as 99 and 1?

Our specific requirements are such that there are two states, one state is "check" and the other is "effective", if it is "check" state, 5% of the traffic will be added to the flag, but will not be routed to the grayscale environment. If the status is "valid", 5% of the traffic will be tagged and 5% of the traffic will be routed to the grayscale environment, can it be achieved using the plug-ins provided by the official?

**Comment by shreemaan-abhishek** [comment]
> Our specific requirements are such that there are two states, one state is "check" and the other is "effective"

How is the state to be determined?
