### ISSUE TITLE
help request: How to publish the log format of plugins through declarative publishing

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix#9767]
### Description

```bash
curl http://127.0.0.1:9180/apisix/admin/plugin_metadata/clickhouse-logger -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "log_format": {
        "properties": "$request_body",
        "client_ip": "$remote_addr",
        "@timestamp": "$time_iso8601"
    }
}'```

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi, could you provide a more detailed description?

**Comment by jinjianming** [comment]
For example, I need to define the log log of the clickhouse logger plugin now_ The format needs to be completed through a PUT request, and I hope to publish it declaratively through the apisixroute or ApisixClusterConfig of ingress through a yaml file

**Comment by jiangfucheng** [comment]
`ClickHouse logger` plugin support set `log_format` field to change log format when you define plugin, no need set plugin_metadata use http request. Maybe it's enough.
![image](https://github.com/apache/apisix/assets/33349046/bb2eb8fd-20c1-4359-b86d-28a4b4db9343)

**Comment by shreemaan-abhishek** [comment]
@jinjianming I am closing this issue. Please reopen if you have further questions.
