### ISSUE TITLE
help request: The gzip plugin doesn't work for POST requests with a response code of 201

### ISSUE THREAD

**Issue by dbit-xia** [apache/apisix#9771]
### Description

I noticed that when making a POST request, the gzip compression doesn't work when the response code is 201. The response header doesn't contain 'Content-Encoding: gzip'. Is there any way to enable gzip compression for such responses?

plugin setting:
```
{
  "_meta": {
    "disable": false
  },
  "buffers": {
    "number": 32,
    "size": 4096
  },
  "comp_level": 1,
  "http_version": 1,
  "min_length": 1,
  "types": "*",
  "vary": true
}
```

### Environment

- APISIX version (run `apisix version`): 3.2.1
- Operating system (run `uname -a`): Linux 030316a0d564 5.14.0-1024-oem #26-Ubuntu SMP Thu Feb 17 14:35:50 UTC 2022 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): bitnami/etcd:3.4.15
- APISIX Dashboard version, if relevant: no
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`): same container

**Comment by Revolyssup** [comment]
Do you have any related error logs or access logs?

**Comment by jiangfucheng** [comment]
@dbit-xia Could provide the response infomation(both response_body and response_header)?
I check the code of gzip plugin,  If response headers don't contains `Content-Type` header, it will not enable gzip, could that be the reason?
https://github.com/apache/apisix/blob/ef2a96deafcb419c1a501c6acdd3352ad67f828b/apisix/plugins/gzip.lua#L110-L114

**Comment by dbit-xia** [comment]
[https://mailman.nginx.org/pipermail/nginx/2012-September/035338.html](https://mailman.nginx.org/pipermail/nginx/2012-September/035338.html)
I looked at the gzip package of nginx used by the bottom layer. I found this discussion. It should be that the bottom layer does not support the compression of the 201 response code!
