### ISSUE TITLE
help request:  kafka-proxy，apisix receive websocket frame: failed to receive the first errors

### ISSUE THREAD

**Issue by robertluoxu** [apache/apisix#9774]
### Description

使用kafka-proxy插件连接kafka borker，vue中使用webscoket连接apisix，vue中如何消费kafka中的消息：

![image](https://github.com/apache/apisix/assets/52069259/3bb950b8-35cf-44bf-8226-952f9d305458)

![image](https://github.com/apache/apisix/assets/52069259/00626181-2c77-4e92-8a53-144d04be2410)

![image](https://github.com/apache/apisix/assets/52069259/fae5c5c7-1989-4c35-8911-43ddf694d783)

### Environment

- APISIX version (run `apisix version`):  2.15.0-centos
- Operating system (run `uname -a`):  
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by robertluoxu** [comment]
官方文档中描述：“APISIX 将从 Kafka 中获取数据，并向客户端发送 PubSubReq 响应数据” ， 此过程发生在哪一步？通过何种方式给客户端发送响应数据？客户端ws中 onmessage 方法未收到主动推送的消息？

**Comment by robertluoxu** [comment]
There are a lot of failed to **receive websocket frame: failed to receive the first errors** in apisix
![image](https://github.com/apache/apisix/assets/52069259/ff16c1ed-721a-4ca1-ba7a-3c31e68a7c33)

**Comment by Revolyssup** [comment]
For the error message above, the read timeout is totally normal and unrelated to error as pointed out by the agentzsh here[1] - "It's completely normal to receive read timeout errors when doing
websockets, which simply means there's no new incoming messages on the
current websocket connection. No need to panic on this.
"

1. https://forum.openresty.us/d/4516-ab52a5eafae3c8f8ed463a0c81d6d873/4

**Comment by shreemaan-abhishek** [comment]
@robertluoxu, I am closing this issue. Please reopen if you have further questions.
