### ISSUE TITLE
feat: I want support multi-phase in serverless plugin

### ISSUE THREAD

**Issue by jiangfucheng** [apache/apisix#9783]
### Description

Exapmle configuration:

```
"serverless-pre(post)-function": {
    "phases": [
    	{
    		"phase": "body_filter",
    		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
    	},
    	{
    		"phase": "header_filter",
    		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
    	}
    ]
}
```

**Comment by Revolyssup** [comment]
@jiangfucheng So currenty the serverless plugin is executed in all phases. And your proposal is to run specific functions in specific phases?

**Comment by jiangfucheng** [comment]
@Revolyssup Currenty serverless plugin only can specify one phase, I hope it can specify multiple phase with different functions at the same time.  Exapmle, I can specify "header_filter" phase to process response header, and specify "body_filter" phase to process reponse_body and so on.

**Comment by Sn0rt** [comment]
can you provide real user requirements?  and user case

**Comment by jiangfucheng** [comment]
We need to modify the response body based on the response header's value. So we must save the `response_header` value in `header_filter` phase before using it in `body_filter` phase.

**Comment by Sn0rt** [comment]
ok. can you take a proposal for discuss ?

**Comment by diegozhu** [comment]
> ### Description
> Exapmle configuration:
> 
> ```
> "serverless-pre(post)-function": {
>     "phases": [
>     	{
>     		"phase": "body_filter",
>     		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
>     	},
>     	{
>     		"phase": "header_filter",
>     		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
>     	}
>     ]
> }
> ```

thumb up.
by the way,  consider this configuration ?
plugins: {
"serverless-pre-function" :{
"rewrite": [func1, func2],
"access": [func1, func2],
"body_filter": [func1, func2],
}
}

**Comment by jiangfucheng** [comment]
> > ### Description
> > Exapmle configuration:
> > ```
> > "serverless-pre(post)-function": {
> >     "phases": [
> >     	{
> >     		"phase": "body_filter",
> >     		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
> >     	},
> >     	{
> >     		"phase": "header_filter",
> >     		"functions" : ["return function() ngx.log(ngx.ERR, \"serverless pre function\"); end"]
> >     	}
> >     ]
> > }
> > ```
> 
> thumb up. by the way, consider this configuration ?
> 
> ```
> plugins: {
>     "serverless-pre-function" :{
>         "rewrite": [func1, func2],
>         "access": [func1, func2],
>         "body_filter": [func1, func2],
>     }
> }
> ```
> 
> besides, is there any way to make mult-line func possible ? it's really hard to read once the funcion become big.

I think the schema design is acceptable. 

In addition, this feature will be incompatible with the old version, so we need to discuss whether compatibility with the older version.
