### ISSUE TITLE
help request: The maximum number of routers and the impact of the number on performance

### ISSUE THREAD

**Issue by cdmikechen** [apache/apisix#9790]
### Description

I'm new in apisix.

I would like to know if the performance of apisix degrades significantly as the router grows incrementally? 
I searched some apisix documentation, but didn't find anything about it.

One of my current scenarios is that many routers will correspond to a service or an upstream. if there are many routers registered (e.g. 10 thousands), will the apisix admin api continue to work properly (e.g. list api, too much data returned within a get request doesn't seem very sensible)?

### Environment

- APISIX version (run `apisix version`): 2.15.3
- Operating system (run `uname -a`): centos7 (docker)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): NA
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.0
- APISIX Dashboard version, if relevant: NA
- Plugin runner version, for issues related to plugin runners: NA
- LuaRocks version, for installation issues (run `luarocks --version`): NA

**Comment by moonming** [comment]
Some users have more routes than 10k and have no performance issues

**Comment by leslie-tsang** [comment]
Considered solved. Feel free to reopen it if needed.
