### ISSUE TITLE
APISIX deployed on K8S returning 502

### ISSUE THREAD

**Issue by idb-root** [apache/apisix#9796]
### Current Behavior

Apisix is deployed in the K8S container cluster. When redeploying the container, Apisix reports 502. Is there any solution to avoid 502?
Ps:

a. The backend business is spring boot 2.6.3

b. Tomcat keepalive_ Time=60s

c. Apisix keepalive_ Timeout=30s

### Error Logs

/path/path2/path3/path4?app_version=6.5.0&pid=3000&uuid=22774320 HTTP/1.1-id 192.168.1.10 - - [06/Jul/2023:07:04:09 +0000] x.xxx.com "POST /path/path2/path3/path4?app_version=6.5.0&pid=3000&uuid=22774320 HTTP/1.1" 502 229 0.001 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_361)" 172.23.8.129:8080 502 0.001 "http://x.xxx.com"

### Steps to Reproduce

1. Apisix deployed on k8s

2. K8s ingress upstream apisix (service client ip)

3. Apisix Upstream Application (Service Client IP)

### Environment

- APISIX version (run `apisix version`):3.2.0
<br class="Apple-interchange-newline">
- Operating system (run `uname -a`):centos7.6
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.5.0
- APISIX Dashboard version, if relevant:3.0.0
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> When redeploying the container

How do you redeploy?


> /path/path2/path3/path4?app_version=6.5.0&pid=3000&uuid=22774320 HTTP/1.1-id 192.168.1.10 - - [06/Jul/2023:07:04:09 +0000] x.xxx.com "POST /path/path2/path3/path4?app_version=6.5.0&pid=3000&uuid=22774320 HTTP/1.1" 502 229 0.001 "-" "Apache-HttpClient/4.5.13 (Java/1.8.0_361)" 172.23.8.129:8080 502 0.001 "http://x.xxx.com/"

This does not look like an error log.

**Comment by 0x101011** [comment]
502 `Bad Gateway` or `Gateway timeout` is APISIX feature to HealthCheck API backend Server available

I remember you can chose two healthcheck mode: Passive & Active . which you can self define your Error Code

this page may notice the same problem same as you:
 https://apisix.apache.org/blog/2021/09/24/youpaicloud-usercase/#scenario-2-upstream-health-screening-problem

**Comment by idb-root** [comment]
> pisix is deployed in the K8S container cluster. When redeploying the container, Apisix reports 502. Is there any solution to avoid 502? Ps:

Rolling deployment of containers on the K8S platform

Ps:

The container has a health check, but the upstream service of Apisix does not have a health check

This is the real log returned by Apisix, and the sensitive parts have been replaced with xxx

**Comment by 0x101011** [comment]
> > pisix is deployed in the K8S container cluster. When redeploying the container, Apisix reports 502. Is there any solution to avoid 502? Ps:
> 
> Rolling deployment of containers on the K8S platform
> 
> Ps:
> 
> The container has a health check, but the upstream service of Apisix does not have a health check
> 
> This is the real log returned by Apisix, and the sensitive parts have been replaced with xxx

Yes Bro. I think your cluster maybe just haven On Upstream such as One Pod or other for "http://x.xxx.com/" .
So In Your `redeploying the container` Times , The Backend Server is Unavailable.
If there have any request ,It should be 502 is normal.

you seems need have more Pod and degrade your `Unavailable` server via Active HealthCheck .

Hope tips have some help to you

<img width="1074" alt="截屏2023-07-07 下午3 08 23" src="https://github.com/apache/apisix/assets/29942463/dc36c358-2ff3-4be8-8c9d-8fb2bbba5cf7">

**Comment by idb-root** [comment]
> > > pisix is deployed in the K8S container cluster. When redeploying the container, Apisix reports 502. Is there any solution to avoid 502? Ps:
> > 
> > 
> > Rolling deployment of containers on the K8S platform
> > Ps:
> > The container has a health check, but the upstream service of Apisix does not have a health check
> > This is the real log returned by Apisix, and the sensitive parts have been replaced with xxx
> 
> Yes Bro. I think your cluster maybe just haven On Upstream such as One Pod or other for "http://x.xxx.com/" . So In Your `redeploying the container` Times , The Backend Server is Unavailable. If there have any request ,It should be 502 is normal.
> 
> you seems need have more Pod and degrade your `Unavailable` server via Active HealthCheck .
> 
> Hope tips have some help to you
> 
> <img alt="截屏2023-07-07 下午3 08 23" width="1074" src="https://user-images.githubusercontent.com/29942463/251665119-dc36c358-2ff3-4be8-8c9d-8fb2bbba5cf7.png">


English：
  When redeploying or publishing container groups on the K8S platform, elegant downtime was configured for the containers to avoid the occurrence of states such as 502
  I suspect that the 502 issue that occurred after using Apisix in the middle was caused by the strong disconnection of Apisix, but I am not sure how to configure Apisix to avoid it

中文：
  在k8s平台重新部署或发布容器组的时候，对容器配置了优雅停机，而避免了502等状态的出现
  中间使用了apisix后而出现的502，我怀疑还是apisix出现的强断开导致的，但不清楚怎么配置apisix来避免

["/bin/bash","-c","sleep 60; curl -X POST -H 'Content-Type: application/json' http://localhost:8080/XXX/actuator/shutdown"]

**Comment by idb-root** [comment]
Health check condition: If there is only one node in the upstream, the initiation of health check will not be triggered, and the request will be forwarded to the upstream regardless of whether the unique node is healthy or not

Because there is only one node in the K8S server's vcie client IP, even if health checks are configured on the Apisix Upstream, they will not take effect.

健康检查条件：
如果 upstream 中只有一个节点时不会触发启动健康检查，该唯一节点无论是否健康，请求都将转发给上游

因为k8s的servcie client ip只有这一个节点，即使在apisix upstream配置了健康检查也不会生效。

**Comment by 0x101011** [comment]
好的，兄弟。
我才理解你只是为了尽量消除应用日志中的502服务不可用的记录是吧。
你有装APISIX Dashboard吗？，用那个配置比较方便。

你看看这个插件，开启这个插件。API的降级断路器。如果你只想修改返回码。可以通过这个自定义返回码和返回信息，例如把502 ->  599 : 服务正在部署中不可用。
https://apisix.apache.org/zh/docs/apisix/plugins/api-breaker/

另外上游Upstream的配置，健康检查开启被动检查，也需要开启主动检查，使用TCP。
<img width="1757" alt="截屏2023-07-07 下午4 19 35" src="https://github.com/apache/apisix/assets/29942463/c907ed63-d445-4a39-8f3e-ed07985db1f0">

**Comment by idb-root** [comment]
全局开启了：api-breaker
路由上也开启了：api-breaker
上游同时开启了健康检查
在k8s上部署的时候，还是报502

- [ ]

**Comment by idb-root** [comment]
<img width="1377" alt="image" src="https://github.com/apache/apisix/assets/120011910/21422b1a-d0ef-4062-9729-fd9efa2ef4d8">
<img width="1380" alt="image" src="https://github.com/apache/apisix/assets/120011910/ff5e0496-6c0d-4280-9fff-875df7ef09e5">
<img width="1258" alt="image" src="https://github.com/apache/apisix/assets/120011910/faf70b13-2e43-440b-92b7-75e239fc19da">

**Comment by idb-root** [comment]
![WX20230707-175751@2x](https://github.com/apache/apisix/assets/120011910/ff32f46c-b3cc-4be9-8dd1-265048924fa7)
未使用Apisix和使用了Apisix时的业务图示，502是apisix日志报出的状态码。

**Comment by GreenAppleOne** [comment]
@0x101011 @shreemaan-abhishek  这是一个很典型的场景把  apisix +k8s 部署，部署应用的间隙 出现短暂  502，不走网关反而不会出现 连接中断的情况，有什么好的建议吗？

**Comment by Sn0rt** [comment]
@tao12345666333 pls take a look

**Comment by tao12345666333** [comment]
You can combine APISIX two-mode healthcheck with liveness/readiness in Kubernetes. Adjust the parameters according to your actual situation

**Comment by monkeyDluffy6017** [comment]
@idb-root have you solved your problem now?
