### ISSUE TITLE
help request: how to set http2_max_concurrent_streams in nginx.conf

### ISSUE THREAD

**Issue by FlyTOmeLight** [apache/apisix#9797]
### Description

Hello everyone,
I'm currently using Apisix to proxy my gRPC service, and I'm experiencing the GOAWAY phenomenon when the service is under high concurrency. I came across this issue on GitHub (https://github.com/apache/apisix/issues/7642), but I couldn't find where to modify the `http2_max_concurrent_streams` in Apisix. I'm deploying the Apisix service using Helm Chart, and my Apisix version is 2.15.0. I tried adding the field directly in the `config.yaml` file, but it didn't take effect. Could someone please guide me on how to modify the `http2_max_concurrent_streams` parameter?
Thank you!

### Environment

- APISIX version (run `apisix version`): 2.15.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
https://the-asf.slack.com/archives/CUC5MN17A/p1688705488455659

**Comment by shreemaan-abhishek** [comment]
@FlyTOmeLight you can do that by setting the following in config.yaml:

<img width="424" alt="image" src="https://github.com/apache/apisix/assets/61597896/7897827a-78f3-46e3-b016-b10ffcec0693">

Is this how you set the `http2_max_concurrent_streams` var?
