### ISSUE TITLE
feat: Dubbo-Proxy Plugin Support Multi Type Object Request And Response

### ISSUE THREAD

**Issue by 0x101011** [apache/apisix#9798]
### Description

As a Deep User Of  `Apache Apisix` and `Apache Dubbo` , I find Apisix has Ability to proxy Dubbo service but needed  advanced  feature . which is Strong Typed Parameter Proxy.

Now `Dubbo-Proxy-Plugin` may just support **Map<String,String>** Response or Request.

Java developer need this badly.

> I sincerely want to know APISIX community if there are any plans or Technology roadmap to support this feature, if yes how can i join the feature to achieve this via community guide

**Comment by Sn0rt** [comment]
> ### Description
> As a Deep User Of `Apache Apisix` and `Apache Dubbo` , I find Apisix has Ability to proxy Dubbo service but needed advanced feature . which is Strong Typed Parameter Proxy.
> 
> Now `Dubbo-Proxy-Plugin` may just support **Map<String,String>** Response or Request.
> 
> Java developer need this badly.
> 
> > I sincerely want to know APISIX community if there are any plans or Technology roadmap to support this feature, if yes how can i join the feature to achieve this via community guide

interesting. can you provider a user case ? 

maybe we need a proposal for discuss.

**Comment by 0x101011** [comment]
Yes Bro,

In some java web develop cases, we design api by RPC or ROA pattern. we always try to POST a DTO Object request Parameters. 

In many cases , the param not just contain BASIC Java Types : the Parent Class DTO contains many sub Class DTO. it came to be nested Object.

`controller`:
```java
    @PostMapping("/api/saveOrUpdate")
    public Mono<String> saveOrUpdate(@RequestBody MetaDataDTO metaDataDto) {
            return Mono.just(Constants.SUCCESS);
    }
```
`request param`
```java
public class MetaDataDto {

    private String id;

    private String appName;

    private String contextPath;

    private String path;

   private MetaConfigDTO metaconfig;
```

In Dubbo , the Provider Alway choose to define a Facade/API layer ,which just contain all function interface and param DTO. this layer give to Consumer to dependency .

such as：

`Facade/API layer`
```java
public interface HelloService {
    public UserVerifyResponse verify(UserInfoRequest who);
}
``` 

So . in `Dubbo-Proxy-Plugin` it provide ability to parse HTTP -> Dubbo xrpc . it really helpful for some Developed Online Dubbo Service ,for we can expose dubbo service not to develop a Java Web Parsing Dubbo Layer.

But for many application online which we can not Expose it easy because Parameter Type Problem.

**Comment by Sn0rt** [comment]
Does it seem like a type of requirement? https://github.com/apache/apisix/pull/9660

**Comment by 0x101011** [comment]
> Does it seem like a type of requirement? #9660

Yes sir.
