### ISSUE TITLE
bug: Missing 3.4.0 image on DockerHhub

### ISSUE THREAD

**Issue by vdieulesaint** [apache/apisix#9800]
### Current Behavior

APISIX 3.4.0 was released last week but the image hasn't been published yet on docker hub :
https://hub.docker.com/r/apache/apisix/tags

Please, could you push the corresponding image on dockerhub

### Expected Behavior

When publishing a new release, an image must be pushed on docker hub as well.

### Steps to Reproduce

Not applicable

**Comment by shreemaan-abhishek** [comment]
It's available now, thank you. You may close this issue if you have no issues.

**Comment by vdieulesaint** [comment]
Thanks for your reactivity.
Best.
Vincent
