### ISSUE TITLE
help request: is it ok to add a batch_processor for file-logger? 

### ISSUE THREAD

**Issue by wklken** [apache/apisix#9803]
### Description

we do a benchmark and find out it will take a lot of time in the json encode of `file-logger`. 

and other loggers like `http-logger` are using batch_processor

so, we add a `batch_processor`(batch_max_size 1000 and inactive_timeout  5s) in the `file-logger` and the qps is greatly improved. 5500 to 13000. the log seems ok.

I'm not so familiar with the batch_processor_manager, and no sure is there any risk to use it with the `write_file_data`.

Hence, my concern is whether it is safe to add a batch_processor for the file-logger? 

### Environment

- APISIX version (run `apisix version`): 3.2.1
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> and no sure is there any risk to use it with the `write_file_data`.

I have no knowledge in this field but I wanted to know what makes you think that it could be risky? 🤔

**Comment by wklken** [comment]
> >

like:
- Did all the workers share the same batch processor? While all workers shared the same access log, was there any race condition?
- If the batch_max_size is set to a value like 100000 and we receive a huge content to write, would it create a problem?

**Comment by shreemaan-abhishek** [comment]
Nice catch!

I view all the worker processes as executables carrying the same apisix code (sorry for the poor analogy), the batch processor essentially uses ngx_timer function that invokes the given function later in a background "light thread" after the delay specified. (it does not send the functions to be executed to a separate "centralized" process).

So, coming to your question:

> Did all the workers share the same batch processor?

No.

> If the batch_max_size is set to a value like 100000 and we receive a huge content to write, would it create a problem?

I think this can be only found by testing it out. 🤔

**Comment by wklken** [comment]
thanks @shreemaan-abhishek 
I will take a look at the source code and do some test.
