### ISSUE TITLE
Prometheus integrating Grafana to collect Apisix data shows incorrect number of requests

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9807]
### Description

Inaccurate number of data collection display requests

![1688980637256](https://github.com/apache/apisix/assets/63503074/e3660646-0492-482a-9c8a-1a0ef333ddae)
![image](https://github.com/apache/apisix/assets/63503074/afb2120f-013c-4046-95a6-0203ec47d2ba)
![image](https://github.com/apache/apisix/assets/63503074/56bc3fa3-48e4-4c96-98da-0de2376619e5)
![image](https://github.com/apache/apisix/assets/63503074/1a6891ea-5f1f-4b95-a44c-cbdd0bb49c91)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> Inaccurate number of data collection display requests

What is the evidence that shows that the number of data collected is inaccurate?

**Comment by XXMY** [comment]
I think the data of request per seconds was not correct,  please check below: 
<img width="1349" alt="image" src="https://github.com/apache/apisix/assets/8390566/26817513-01ef-4dfd-9d77-42537720869b">
<img width="1204" alt="image" src="https://github.com/apache/apisix/assets/8390566/fcf2fe7f-c0fe-4f59-8e7f-9ecf27d4cf07">

**Comment by XXMY** [comment]
> I think the data of request per seconds was not correct, please check below: <img alt="image" width="1349" src="https://private-user-images.githubusercontent.com/8390566/299254505-26817513-01ef-4dfd-9d77-42537720869b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc0NzQsIm5iZiI6MTcwNjA4NzE3NCwicGF0aCI6Ii84MzkwNTY2LzI5OTI1NDUwNS0yNjgxNzUxMy0wMWVmLTRkZmQtOWQ3Ny00MjUzNzcyMDg2OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDkwNjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDdkYjJhMDFhYTUyZGUyMTFmODk3MGViMjlhZmRhMjE5Zjg5MjY4OTQyNWM2ZDgzZGZlZjZjMTMyZDIwZTRhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.kpfuFjQtX4_-vYFSIsDD7m__zV-UTkBdXX5EUWb1iHQ"> <img alt="image" width="1204" src="https://private-user-images.githubusercontent.com/8390566/299254932-fcf2fe7f-c0fe-4f59-8e7f-9ecf27d4cf07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwODc0NzQsIm5iZiI6MTcwNjA4NzE3NCwicGF0aCI6Ii84MzkwNTY2LzI5OTI1NDkzMi1mY2YyZmU3Zi1jMGZlLTRmNTktOGU3Zi05ZWNmMjdkNGNmMDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMDkwNjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFlNjA1YjA3ZGE4YzhlMmY1MjIyODRlODU2ZjFiOTZjZTBlYjE5MTUxNjgwM2Y3YmFmMGIwZTcyNzNlNmNmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TCMSElFOOGWXPVTdt91BfuiprQxGruQgZ8UD2N7xbZ0">



> > Inaccurate number of data collection display requests
> 
> What is the evidence that shows that the number of data collected is inaccurate?
> 
> Please help everyone by adding a clear description of the screenshots you posted.
