### ISSUE TITLE
How to configure tls for apisix

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9808]
### Description

How to configure tls for apisix

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
It's literally there in the documentation:

https://apisix.apache.org/docs/apisix/mtls/
