### ISSUE TITLE
bug: healthcheck cannot use specified `Host` header

### ISSUE THREAD

**Issue by chnliyong** [apache/apisix#981]
### Issue description
The healthcheck config schema requires `host` config item placed within the `upstream.checks.active`, which should be referenced by `upstream.checks.active.host`, but when initializing the healthchecker, the code use `upstream.checks.host` show below:
```lua
    ...
    for addr, weight in pairs(upstream.nodes) do
        local ip, port = core.utils.parse_addr(addr)
        local ok, err = checker:add_target(ip, port, upstream.checks.host)
        if not ok then
            core.log.error("failed to add new health check target: ", addr,
                            " err: ", err)
        end
    end
    ...
```
[Link](https://github.com/apache/incubator-apisix/blob/af1a29a38e6c7623fa697ea524832ece76a9cbf6/lua/apisix/balancer.lua#L84)

### Environment

* apisix version (cmd: `apisix version`): master
* OS: Ubuntu 18.04.3

**Comment by moonming** [comment]
welcome PR

**Comment by membphis** [comment]
fixed https://github.com/apache/apisix/pull/1871
