### ISSUE TITLE
help request: apisix How to Implement Implicit Page Jumping

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix#9812]
### Description

Example: Change the request path https://testa.com/home/test Jump to https://testb.com/home/test/test.html Page, but the page URL is still https://testa.com/home/test

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jinjianming** [comment]
This can be achieved in nginx

```
    location = /home/test {
        rewrite /home/test /home/test/test.html break;
        proxy_pass https://def.com;
    }
```

**Comment by jiangfucheng** [comment]
You can use `proxy-rewrite` plugin to rewrite uri.
ref: https://apisix.apache.org/docs/apisix/plugins/proxy-rewrite/

**Comment by leslie-tsang** [comment]
Considered solved. Feel free to reopen it if needed.
