### ISSUE TITLE
help request: Example to convert URL string to base64 and use it as param to call 3rd API

### ISSUE THREAD

**Issue by chilcano** [apache/apisix#9818]
### Description

Hi there!
I have a specific use case to implement on APISIX.

I have a APISIX route `http://local-apisix/myapi/any-string-value` and want to convert `any-string-value` to base64 and immediately use it to call to 3rd party API.
The 3rd party API expects base64 string in the URL (`GET http://3rd-api/otherapi/<base64(any-string-value)>`).

I've used `proxy-rewrite` plugin to manipulate the URL using `regex_uri`, but unfortunately, regex is not enough to convert to base64.

Please, could anybody help me with that? An snipped code can be helpful.
Any hints is welcome.
Regards.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Existing plugins seems not meet you needs.

**Comment by qwzhou89** [comment]
你可以使用
  serverless-post-function:
    functions:
      - |
        return function(conf, ctx)
          ctx.var.upstream_uri = ngx.encode_base64(ctx.var.real_request_uri);
        end
    phase: access

**Comment by qwzhou89** [comment]
> You will see that i get `"path": "/api02/base64/api01/abc123"` and `"path": "/L2FwaTAxL2FiYzEyMw=="` respectively when it should be `"path": "/api02/base64/L2FwaTAxL2FiYzEyMw=="`.
去掉"proxy-rewrite"插件的里面的regex_uri配置，然后在serverless-post-function with "phase": 里面添加/api02/base64/不就可以了吗？
"serverless-post-function": {
"functions": ["return function(conf, ctx)\n ctx.var.upstream_uri = \"/api02/base64/\" .. ngx.encode_base64(ctx.var.real_request_uri);\nend\n"],
"phase": "access"
}

**Comment by qwzhou89** [comment]
> code sample(not test yet):
> 
> ```
> local core = require("apisix.core");
> local b64 = require("ngx.base64");
> local splited_uris = core.utils.split_uri(ctx.var.upstream_uri);
> ctx.var.upstream_uri = table.concat(splited_uris,"", 1, #splited_uris - 1) .. b64.encode_base64url(splited_uris[#splited_uris]);
> ```

这应该是可以的。另外也可以参考
apisix/plugins/proxy-rewrite.lua
的代码，把`proxy-rewrite`的`regex_uri`的逻辑在serverless-pre-function里面实现下也可以。

还有，不知道你使用的apisix版本是多少，2.15.3以上的话，应该可以更改插件的优先级，把serverless-pre-function放在"phase": "rewrite"，并把他的优先级提高，让它先于proxy-rewrite执行，应该也可以

**Comment by jiangfucheng** [comment]
@chilcano A litle hint, you can use `require("ngx.base64"). encode_base64url(data)` directly, it's url safed base64 algorithm.

**Comment by shreemaan-abhishek** [comment]
@chilcano, apisix.core is not documented you can take a look at the code in the apisix repository: https://github.com/apache/apisix/tree/master/apisix/core

To learn about ngx libraries you can check out the openresty documentation: https://github.com/openresty/lua-resty-core

If you do not have further questions, you may close this issue now.
