### ISSUE TITLE
help request: traffic_split来做灰度发布时,nacos服务实例如何在请求头中获取到该请求是否是灰度流量

### ISSUE THREAD

**Issue by wxz1211** [apache/apisix#9824]
### Description

使用traffic_split来做灰度发布时,目前的方案:
1、使用的微服务中间件是:nacos、(生产、灰度使用的nacos是同一套),注册服务的时候会将对应的nacos实例设置为灰度or生产.
2、生产与灰度用的**同一个路由**,生产环境和灰度环境使用**不同的上游**(对上游部分的lua代码及dashboard进行了改动,给上游加了一个属性(生产or灰度),根据该属性,去找对应的nacos实例.比如属性值为灰度,具体逻辑:找不到对应的灰度的nacos实例的话,就会去找生产的实例)
在进行了这样的改动以后:遇到了一个问题:
当请求到达具体的nacos服务后,无法得知该请求是来自生产环境还是灰度环境.
期望:nacos服务实例可以在请求头里获取到该请求是否是灰度流量

### Environment

- APISIX version (run `apisix version`):2.15.1
- Operating system (run `uname -a`): linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Could you provide specific configurations?

**Comment by Revolyssup** [comment]
Translation:
When using traffic_split for grayscale publishing, the current solution:
1. The microservice middleware used is: nacos, (the nacos used by production and grayscale is the same set), when registering the service, the corresponding nacos instance will be set as grayscale or production.
2. The same route is used for production and grayscale. The production environment and grayscale environment use different upstreams (the lua code and dashboard of the upstream part have been changed, and an attribute (production or grayscale) has been added to the upstream. According to this attribute, find the corresponding nacos instance. For example, the attribute value is grayscale, the specific logic: if the corresponding grayscale nacos instance cannot be found, it will find the production instance)
After making such changes: encountered a problem:
When the request reaches the specific nacos service, it is impossible to know whether the request comes from the production environment or the grayscale environment.
Expectation: The nacos service instance can obtain whether the request is grayscale traffic in the request header

**Comment by Revolyssup** [comment]
@wxz1211 Please also provide the snippets of lua code changes you did.

**Comment by wxz1211** [comment]
> @wxz1211 Please also provide the snippets of lua code changes you did.
@Revolyssup 
hi.Here are my changes:
1:dashboard-->upstream page --->. add new balance type(nacos_traffic) 
2:Modified file: balance.lua、discovery/nacos/init.lua
3:A new file named traffic.lua has been added to the balance directory


1、dashboard-->upstream page :
![image](https://github.com/apache/apisix/assets/11730002/73934370-e565-43db-a1d9-f75eb066066f)
Upstream added a new field:nacos_profile
![image](https://github.com/apache/apisix/assets/11730002/66eebd76-984d-4bbd-9c36-1fb019d2372e)
lua:

2、Modified file: balance.lua、discovery/nacos/init.lua
balance.lua:
![image](https://github.com/apache/apisix/assets/11730002/338e01b1-f4bf-4be8-96a8-cb7adf9bfc18)
discovery/nacos/init.lua:
![image](https://github.com/apache/apisix/assets/11730002/3c7e6ea7-9e8b-4981-ad04-b887cf83cbeb)

3、A new file named traffic.lua has been added to the balance directory
```lua
local roundrobin  = require("resty.roundrobin")
local core = require("apisix.core")
local nkeys = core.table.nkeys
local pairs = pairs
local log = core.log

local _M = {}


function _M.new(up_nodes, upstream)
    local safe_limit = 0
    log.info("traffic-up_nodes:", core.json.encode(up_nodes))
    log.info("traffic-upstream:", core.json.encode(upstream))
    log.info("upstream-type:", upstream.type)
    local profile = upstream.profile or 'base'
    local processedData = {}

    for key, value in pairs(up_nodes) do
        local ipPort, profile = key:match("([^:]+:%d+):([^:]+)")
        log.info("ipPort:", core.json.encode(ipPort))
        log.info("profile:", core.json.encode(profile))        
        if not processedData[profile] then
            processedData[profile] = {}
        end
        processedData[profile][ipPort] = value
    end
    up_nodes = processedData[profile] or processedData['base']
    log.info("processed-node:", core.json.encode(up_nodes))
    if not up_nodes then
        return nil, "up_nodes not exist"
    end
    for _, weight in pairs(up_nodes) do
        -- the weight can be zero
        safe_limit = safe_limit + weight + 1
    end

    local picker = roundrobin:new(up_nodes)
    local nodes_count = nkeys(up_nodes)
    return {
        upstream = upstream,
        get = function (ctx)
            if ctx.balancer_tried_servers and ctx.balancer_tried_servers_count == nodes_count then
                return nil, "all upstream servers tried"
            end

            local server, err
            for i = 1, safe_limit do
                server, err = picker:find()
                if not server then
                    return nil, err
                end
                if ctx.balancer_tried_servers then
                    if not ctx.balancer_tried_servers[server] then
                        break
                    end
                else
                    break
                end
            end

            return server
        end,
        after_balance = function (ctx, before_retry)
            if not before_retry then
                if ctx.balancer_tried_servers then
                    core.tablepool.release("balancer_tried_servers", ctx.balancer_tried_servers)
                    ctx.balancer_tried_servers = nil
                end

                return nil
            end

            if not ctx.balancer_tried_servers then
                ctx.balancer_tried_servers = core.tablepool.fetch("balancer_tried_servers", 0, 2)
            end

            ctx.balancer_tried_servers[ctx.balancer_server] = true
            ctx.balancer_tried_servers_count = (ctx.balancer_tried_servers_count or 0) + 1
        end,
        before_retry_next_priority = function (ctx)
            if ctx.balancer_tried_servers then
                core.tablepool.release("balancer_tried_servers", ctx.balancer_tried_servers)
                ctx.balancer_tried_servers = nil
            end

            ctx.balancer_tried_servers_count = 0
        end,
    }
end


return _M

```

**Comment by Revolyssup** [comment]
@wxz1211 Just to confirm your requirement - You want to encode the information about which Nacos instance(Prod or grayscale) served the discovery of this Service into the request header?

**Comment by Revolyssup** [comment]
@wxz1211 You can try adding something like  `ngx.req.set_header("nacos-profile, profile)` in the get function on returned table in the traffic.lua file

**Comment by wxz1211** [comment]
> ngx.req.set_header("nacos-profile, profile)

it works ,thx

**Comment by Revolyssup** [comment]
@wxz1211 You can close this issue.
