### ISSUE TITLE
bug: According to the official installation of skywalking, it does not work and cannot be found in the "visualization plugin" in Apisix

### ISSUE THREAD

**Issue by llp520-jkcs** [apache/apisix#9826]
### Description

bug: According to the official installation of skywalking, it does not work and cannot be found in the "visualization plugin" in Apisix
![image](https://github.com/apache/apisix/assets/63503074/3bf90a82-c63c-4e2b-8859-50686c807361)
Unable to find skywalking
![image](https://github.com/apache/apisix/assets/63503074/cd0bb302-6eb6-4d68-b8d6-2cd0bc444df5)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Please ensure that the skywaking plugin is enabled in you dashboard configuration, defaut is disabled.

**Comment by llp520-jkcs** [comment]
Your answer is not professional, I didn't see this plugin in Apisix. I can't open it

**Comment by llp520-jkcs** [comment]
Unable to search for skywalking in the plugin

**Comment by jiangfucheng** [comment]
Can you provide `APISIX Dashboard` configurations?

**Comment by llp520-jkcs** [comment]
The dashboard configuration did not enable this plugin skywalking

resolved
