### ISSUE TITLE
help request: why one of http_to_https、uri and regex_uri can  be configured to plugin 'redirect'

### ISSUE THREAD

**Issue by chenjinfeng0505** [apache/apisix#9835]
### Description

As I know, http_to_https、uri  and regex_uri  will both change  request to client. 
When I use the following parameter settings route, it will report an error:

    "status": 1,
    "plugins": {
        "redirect": {
            "http_to_https": true,
            "ret_code": 301,
            "encode_uri": false,
            "append_query_string": false,
            "regex_uri": []
        }
    }

error info:
{
    "error_msg": "failed to check the configuration of plugin redirect err: property \"regex_uri\" validation failed: expect array to have at least 2 items"
}

At this time，http_to_https is true and regex_uri is empty. if without this regex_uri filed, it is successful.
I want to know that after setting a field，Why can't other fields be empty and filed name must also be absent.

### Environment

- APISIX version (run `apisix version`): 3.0.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Because these functions are all implemented by `redirect` plugin,  no matter which filed you modified, the `schema checker` will check all configuration of this plugin.

**Comment by jiangfucheng** [comment]
Hi, you question is why `regext_uri` field can't be empty?

**Comment by chenjinfeng0505** [comment]
@jiangfucheng  If http_to_https have value,  why regex_uri and uri can’t be empty and must not exist in the request.

（ps: 官方文档说明： http_to_https、uri 和 regex_uri 只能配置其中一个属性。
     场景一： 如果http_to_https有值，uri 和 regex_uri 不设置任何值，这种也会执行失败；
     场景二：如果http_to_https有值，请求中无uri 和 regex_uri参数 ，可以执行成功）

**Comment by jiangfucheng** [comment]
> Only one of http_to_https, uri and regex_uri can be configured.

**Comment by jiangfucheng** [comment]
> Only one of http_to_https, uri and regex_uri can be configured.
ref: https://apisix.apache.org/docs/apisix/plugins/redirect/

What is the meaning of not setting any values?  If you set `http_to_https`, so that  `uri` and `regex_uri` should not be configured rather than set the "empty" value.

**Comment by shreemaan-abhishek** [comment]
I agree with @jiangfucheng, essentially if you set `http_to_https` other fields like `uri`, and `regex_uri` will not be used anyhow. So what is the need to set an empty value for `regex_uri`? 🤔
