### ISSUE TITLE
help request: Need to join APISIX Slack Channel

### ISSUE THREAD

**Issue by Irfan00001** [apache/apisix#9844]
### Description

Currently I am evaluating APISIX Gateway for my organization to implement the same. Need some more understanding due to which I request to joining the SLACK Channel

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi, you can click the below link to join the Slack channel.

https://join.slack.com/t/the-asf/shared_invite/zt-1z8uch2dx-8KDsDWJeoqM~e1DxZxkweA
