### ISSUE TITLE
help request: how to add @timestamp field to elasticsearch-logger?

### ISSUE THREAD

**Issue by child2d** [apache/apisix#9852]
### Description

hi,

my elasticsearch-logger plugin has been added to the route while i want to add @timestamp to the log.

here is my elasticsearch-logger, it looks good. plenty of useful log field generated from logger.
```json
// elasticsearch-logger-plugin
"elasticsearch-logger": {
    "name": "elasticsearch-logger",
    "ssl_verify": true,
    "retry_delay": 1,
    "max_retry_count": 0,
    "timeout": 10,
    "field": {
        "index": "access_log"
    },
    "batch_max_size": 1000,
    "inactive_timeout": 5,
    "buffer_duration": 60,
    "endpoint_addr": "http://foo:9200"
}
```

question is if i add log_format `{"@timestamp": "$time_iso8601"}` to the plugin metadata, those log field will be lost. 
I don't want to manually configure many configuration items into metadata because it's too cumbersome. 
How can I reuse the original log fields?

from elasticsearch log i found `start_time`, can it be configure to iso datetime format?

### Environment

- APISIX version (run `apisix version`): 3.1.0
- Operating system (run `uname -a`): Linux apisix 4.19.91-26.al7.x86_64 1 SMP x86_64 GNU/Linux which is a k8s pod
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
> question is if i add log_format {"@timestamp": "$time_iso8601"} to the plugin metadata, those log field will be lost.

Why would those log fields be lost? What do you mean? 🤔

**Comment by child2d** [comment]
> > question is if i add log_format {"@timestamp": "$time_iso8601"} to the plugin metadata, those log field will be lost.
> 
> Why would those log fields be lost? What do you mean? 🤔

in my opinion, fields like `request.headers`, `response.xxx` were not recorded since `log_format` contains only `@timestamp`?

**Comment by child2d** [comment]
- this is without log_format
```json
{
  "server": {
    "version": "3.1.0",
    "hostname": "apisix"
  },
  "request": {
    "method": "GET",
    "querystring": {},
    "size": 2333,
    "headers": {
      "connection": "keep-alive",
      "x-api-key": "",
      "sec-fetch-mode": "cors",
      "accept": "*\/*",
      "x-forwarded-for": "",
      "sec-fetch-site": "same-site",
      "origin": "xx",
      "x-scheme": "https",
      "authorization": "xx",
      "x-real-ip": "xx"
    },
    "uri": "xx",
    "url": "xx"
  },
  "route_id": "xx",
  "latency": 388.00001144409,
  "upstream": "xx",
  "service_id": "",
  "upstream_latency": 9,
  "response": {
    "status": 200,
    "headers": {
      "connection": "close",
      "access-control-allow-methods": "GET,POST,PUT,DELETE,PATCH,HEAD,OPTIONS,CONNECT,TRACE",
      "access-control-allow-origin": "",
      "date": "Mon, 17 Jul 2023 10:05:51 GMT",
      "content-type": "application\/json; charset=utf-8",
      "vary": "Origin",
      "access-control-max-age": "5",
      "access-control-expose-headers": "Content-Disposition",
      "access-control-allow-credentials": "true",
      "content-length": "126",
      "server": "APISIX\/3.1.0"
    },
    "body": "xx",
    "size": 571
  },
  "apisix_latency": 379.00001144409,
  "start_time": 1689588351236,
  "client_ip": "xx"
}
```

- this is with log_format
```json
// It just records this few info
{
  "@timestamp": "2023-07-17T03:53:12+00:00"
}
```

**Comment by shreemaan-abhishek** [comment]
This is so strange, I am not sure how you got so many fields in the log by default. As the documentation says, the default log format is:

```json
{"host": "$host", "@timestamp": "$time_iso8601", "client_ip": "$remote_addr"}
```

In theory, you should only be getting 3 fields in the logs. 🤔 

> i want a + b

With that being said, if you want  `a + b` in your logs, you can add an extra `"@timestamp": "$time_iso8601"` field to your plugin metadata log format. Remember, you need to `add` an extra timestamp field. If you just keep the `timestamp` in the log format, you will only see the timestamp in the logs.

**Comment by child2d** [comment]
🤣 thank you for your kindly answer. i will take my logger as something like two negatives make a positive.
anyway we use elasticsearch pipeline to handle our scenario bypass apisix.
so leave it "so many fields".

**Comment by gujiwork** [comment]
The start_time field in Elasticsearch is of type Long, so Kibana cannot select based on time and cannot convert Long to Date.  I think the apisix logs plugin should set the start_time field to Date type when writing to Elasticsearch.
