### ISSUE TITLE
help request: 500 err

### ISSUE THREAD

**Issue by lilililizheng** [apache/apisix#9853]
### Description

I compiled apisix using the source code, and now any URL I visit following the example returns a 500 error. Using the latest version of apisix, the error log displays the following:
![image](https://github.com/apache/apisix/assets/106649263/b245ed82-f671-4ed2-8ec7-35e44f4523c5)

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

![image](https://github.com/apache/apisix/assets/106649263/54f9cfb8-f658-4887-978f-ae8ce6495c95)

**Comment by lilililizheng** [comment]
![image](https://github.com/apache/apisix/assets/106649263/6daa8e21-e6c7-4887-92a9-83ac8e0569a9)

**Comment by jiangfucheng** [comment]
Do you install all dependencies using `make deps`?

**Comment by lilililizheng** [comment]
![image](https://github.com/apache/apisix/assets/106649263/c273e87c-729c-4fc7-a8d3-ee9212976d4b)

**Comment by Sn0rt** [comment]
can you check `deps/share/lua/5.1/resty/worker/events.lua` from your APISIX directory

**Comment by lilililizheng** [comment]
The source code is built in full accordance with the official documentation, and the apisix process can start normally, what environment variables need to be set? The file exists, how do I check it?

**Comment by lilililizheng** [comment]
I just want to run some of its simple features for now, such as the official example.

**Comment by lilililizheng** [comment]
![image](https://github.com/apache/apisix/assets/106649263/fbabf73c-b39f-4a7b-98cf-f1654a09da47)
I downloaded an earlier version of apisix and it's still the same problem, I don't know what went wrong with the build process, it didn't report any errors, it didn't report any errors at startup

**Comment by Sn0rt** [comment]
Can you take a look at this file https://github.com/api7/apisix-build-tools/blob/master/.github/workflows/package-apisix-base-deb-ubuntu20.04.yml

I believe it can help you to compile APISIX on ubuntu.

**Comment by Sn0rt** [comment]
can you share your version info ?

```shell
APISIX version (run apisix version):
Operating system (run uname -a):
OpenResty / Nginx version (run openresty -V or nginx -V):
etcd version, if relevant (run curl http://127.0.0.1:9090/v1/server_info):
APISIX Dashboard version, if relevant:
Plugin runner version, for issues related to plugin runners:
LuaRocks version, for installation issues (run luarocks --version):
```

**Comment by Revolyssup** [comment]
@lilililizheng any updates?
