### ISSUE TITLE
help request: Is there APISIX healthcheck endpoint?

### ISSUE THREAD

**Issue by chilcano** [apache/apisix#9859]
### Description

Hi there,
We are deploying APISIX on GKE and to configure the GKE BackendConfig we require a `/healthcheck` endpoint.
Is there a healthcheck endpoint available on APISIX node? Or enabling `server-info` to be used as healthcheck is the right approach ?
Regards

### Environment

- APISIX version (run `apisix version`): 3.4.0
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by d9705996** [comment]
I faced the same issue and used https://apisix.apache.org/docs/apisix/FAQ/#after-deploying-apache-apisix-how-to-detect-the-survival-of-the-apisix-data-plane to create a healthcheck endpoint and reference in BackendConfig 

Works like a charm.
