### ISSUE TITLE
add ip whitelist/blacklist feature in limit-count plugin or more beaty implement

### ISSUE THREAD

**Issue by imlewc** [apache/apisix#986]
In my work, there is such a scenario, restricting access to IP request count,but ignore some our inner ips, i think we can add ip whitelist/blacklist feature in limit-count plugin!
Or can we support some logic between some funcs in our admin config, such as my scenario,we can operate logic like excel !
But this idea may be more diffcult in admin config validate.

Do others has some helpful ideas??

**Comment by moonming** [comment]
I think there are 2 ways:
1. use the priority routes with `ip-restriction` plugin: https://github.com/iresty/lua-resty-radixtree/issues/31, however, priority route is not implemented yet;
2. add ip whitelist/blacklist feature in `limit-count` plugin.

The second way is faster at this time.

**Comment by imlewc** [comment]
ok, at first i choose implement with the second way .

**Comment by spacewander** [comment]
This issue is marked as stale because it has not had activity for a long time. It will be closed in the next 7 days unless the label "stale" is removed. Thank you for your contributions.

**Comment by spacewander** [comment]
Can be solved with plugin orchestration.

**Comment by Jerome0430** [comment]
> Can be solved with plugin orchestration.

How to achieve

**Comment by jinjianming** [comment]
+1 How to achieve

**Comment by Jerome0430** [comment]
已收到你的重要来信！我会尽快回复的！
