### ISSUE TITLE
use external secret to store apisix tls certificates

### ISSUE THREAD

**Issue by chiliast123** [apache/apisix#9861]
### Description

If I want to use external secret to store apisix tls certificates, how do I write the configuration contents in the values.yaml?

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
This is not supported yet.

**Comment by chiliast123** [comment]
thanks for your reply, but I want to be sure. The situation is storing the apisix tls certificate on Alibaba Cloud KMS connect to external secret,  use externalsecret to create a Kubernetes secret, then the apisix tls turns into a Kubernetes secret, how the configuration contents in the values.yaml looks like? is it supported?

**Comment by shreemaan-abhishek** [comment]
cc: @tao12345666333, do you have any context on this?

**Comment by tao12345666333** [comment]
I don't know about Alibaba Cloud KMS. But we can work together with Vault, AWS ACM, and others. The following articles are available for reference.


* [Using APISIX Ingress Controller With AWS ACM - API7.ai](https://api7.ai/blog/using-apisix-ingress-with-aws-acm)
* [How to Use cert-manager and HashiCorp Vault to Manage Certificates? - API7.ai](https://api7.ai/blog/how-to-use-cert-manager-and-vault-to-manage-certifications)
* [Manage Ingress Certificates With Cert Manager | Apache APISIX® -- Cloud-Native API Gateway](https://apisix.apache.org/docs/ingress-controller/tutorials/manage-ingress-certificates-with-cert-manager/)
* [HashiCorp Vault Secure Storage Backend in Apache APISIX Ecosystem | Apache APISIX® -- Cloud-Native API Gateway](https://apisix.apache.org/blog/2022/01/21/apisix-hashicorp-vault-integration/)
* [How to Use Vault to Manage Certificates in APISIX - API7.ai](https://api7.ai/blog/apisix-integrates-with-vault)

**Comment by tao12345666333** [comment]
please use ``` (code block) to format your contents.
