### ISSUE TITLE
error日志中偶尔出现transaction cleanup，请问是什么原因

### ISSUE THREAD

**Issue by wodingyang** [apache/apisix#9865]
### Description

![image](https://github.com/apache/apisix/assets/75060224/5d675a38-e8ed-4cce-aecb-0565781b8520)
如图，线上机器总是偶尔会在error.log中出现如上error日志，也没影响业务使用，但是error级别又让人觉得担心。谁能解答下什么情况会出现这样的问题，需要关注么

### Environment

- APISIX version (run `apisix version`):2.15.0
- Operating system (run `uname -a`):centos7

**Comment by Sn0rt** [comment]
got. let me take a look

**Comment by wodingyang** [comment]
已确认是我们用的waf将恶意请求重定向时发生的，暂没发现有什么影响。希望后面有大神能解答下疑惑
