### ISSUE TITLE
how to  use  apisix   stream_route connction  mysql  in  k8s 

### ISSUE THREAD

**Issue by joranbo** [apache/apisix#9870]
### Description

k8s  port,  
![image](https://github.com/apache/apisix/assets/29445870/39b7b4fb-2295-44f2-9fc7-150c2e6c26be)

stream_route:
curl http://127.0.0.1:9180/apisix/admin/stream_routes/1 -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
{
    "server_addr": "127.0.0.1",
    "server_port": 3306,
    "upstream": {
        "nodes": {
            "mysql:3306": 1
        },
        "type": "roundrobin"
    }
}'

stream_pproxy:
![image](https://github.com/apache/apisix/assets/29445870/c0dbfce4-c6dd-4cd0-9e47-75a1d6762a87)

use  ip:32333  connect  failed, What's wrong？

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@joranbo What installation steps did you follow?

**Comment by joranbo** [comment]
![image](https://github.com/apache/apisix/assets/29445870/f50bd5ba-430d-400f-908d-e64783a4763c)
Is this where the port is configured？  32333 is not mapped to tcp proxy port.  How is it set up？  Could you please tell me, thank you

**Comment by joranbo** [comment]
> > ![image](https://user-images.githubusercontent.com/29445870/254835218-f50bd5ba-430d-400f-908d-e64783a4763c.png) Is this where the port is configured？ 32333 is not mapped to tcp proxy port. How is it set up？ Could you please tell me, thank you
> 
> Yes this is where its setup. If you have used helm to install. Either you can edit this and pass the new values.yaml file using `-f` flag with helm install. Or With helm install, you can add `--set` flag to overridde these valued. For eg: `helm install ...... --set gateway.stream.enabled=true --set gateway.stream.tcp[0]=<your port> .......`
> 
> After installation like this, doing you should see extra port mappings on your apisix-gateway service.

Okay, I'll give it a try. Thank you

**Comment by joranbo** [comment]
> <your port>

thank you very much!

This method is not effective
![image](https://github.com/apache/apisix/assets/29445870/ed72e750-a7f7-4239-8be8-87d95ee6f10c)
![image](https://github.com/apache/apisix/assets/29445870/c4f569cb-f2c0-41c1-b108-82462c2058f9)

vim values.yml 
This method is effective

![image](https://github.com/apache/apisix/assets/29445870/ed044ca2-3df9-437d-a698-5af3865c0c82)

**Comment by Revolyssup** [comment]
@joranbo You can close the issue, if it satisfies your requirement.
