### ISSUE TITLE
question: plugin limit-count why new the redis_cli in the incoming?

### ISSUE THREAD

**Issue by wklken** [apache/apisix#9872]
### Description

limit-count-redis: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/limit-count-redis.lua#L101

new the redis cli per request? 

while the 

limit-count-redis-cluster: https://github.com/apache/apisix/blob/master/apisix/plugins/limit-count/limit-count-redis-cluster.lua#L77

only new the client once? 

------

the limit-count-redis can change to new the client once in the function `new()`?

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
Here[1] after the first connection, keepalive is set so subsequent calls do not create a new connection and reuse existing one.
