### ISSUE TITLE
Invalid Host header 

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#9874]
### Description

When I used https to proxy a page, I got the Invalid Host header, at that time when I represent an interface was normal, I don't know what happened?
there is my config:
route config: (10.4.16.15:9000 is page ,others is interface)
```
{
    "uris": [
        "/pageApi/*",
        "/static/*"
    ],
    "name": "http",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": [
                "^/pageApi(/|$)(.*)",
                "/$2"
            ]
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "10.4.16.15",
                "port": 9000,
                "weight": 1
            },
            {
                "host": "192.168.88.66",
                "port": 6001,
                "weight": 1
            }
        ],
        "retries": 1,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        },
        "retry_timeout": 1
    },
    "status": 1
}
```
the result:
1:proxy to page:
![image](https://github.com/apache/apisix/assets/131146587/f2bacb65-e669-4e0a-88fb-4889ba41f38d)
2.proxy to interface is normal
![image](https://github.com/apache/apisix/assets/131146587/22e01314-8b87-448d-a2f1-9682f420f572)

### Environment

- APISIX version (run `apisix version`):2.15-alpine
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
I don't understand your problem. What do you mean by _interface_?

**Comment by bin-53** [comment]
名

> I don't understand your problem. What do you mean by _interface_?

Simply put, I go to the agent a page through apisix, can not succeed, but the agent interface is ok (using the https protocol)

**Comment by bin-53** [comment]
> I don't understand your problem. What do you mean by _interface_?

Simply put, I go to the agent a page through apisix, can not succeed, but the agent interface is ok (using the https protocol)

**Comment by shreemaan-abhishek** [comment]
Do you find anything in the error logs?

**Comment by bin-53** [comment]
> Do you find anything in the error logs?

No error log output
there are some access.log
![image](https://github.com/apache/apisix/assets/131146587/b5125de3-798e-464b-8ef7-38db44d9b8b5)

**Comment by shreemaan-abhishek** [comment]
@bin-53, no error log probably means this is not an APISIX problem.

**Comment by shreemaan-abhishek** [comment]
@bin-53, do you know which hostname is the upstream is running on? If yes, then you can configure the `pass_host` parameter in the upstream configuration. Doing so, _might_ fix the issue.

Ref: https://the-asf.slack.com/archives/CUC5MN17A/p1693027455833209?thread_ts=1692291158.391359&cid=CUC5MN17A
