### ISSUE TITLE
help request: The apisix certificate replacement is displayed successfully, but does not take effect

### ISSUE THREAD

**Issue by mark-make** [apache/apisix#9875]
### Description

When the certificate is replaced on the apisix Dashboard certificate page, it is displayed that the certificate is replaced successfully. However, when you view the domain name of the certificate in the browser, you can find that the certificate is old.

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
I would recommend you to use the admin-api: https://apisix.apache.org/docs/apisix/admin-api/#ssl instead of using the dashboard

**Comment by shreemaan-abhishek** [comment]
ping @mark-make
