### ISSUE TITLE
Plug-in execution order

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#9876]
### Description

Excuse me, the same plug-in are the following several places are configured, will be executed? Who else carries it out first?
1.Consumer 
2. Route
3. Service
4. 全局(全局插件列表)

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by kayx23** [comment]
1. global plugins
2. Consumer
3. Route
4. Service

References:
* https://apisix.apache.org/docs/apisix/next/terminology/plugin/#plugins-execution-order
* https://apisix.apache.org/docs/apisix/next/terminology/plugin/#plugins-merging-precedence
* https://docs.api7.ai/apisix/key-concepts/plugins

**Comment by bin-53** [comment]
> It'd be run twice. Once as the global rule plugin and once as the non-global plugin on the Consumer.
> 
> References:
> 
> * https://apisix.apache.org/docs/apisix/next/terminology/plugin/#plugins-execution-order
> * https://apisix.apache.org/docs/apisix/next/terminology/plugin/#plugins-merging-precedence
> * https://docs.api7.ai/apisix/key-concepts/plugins

Thank you for your reply. Does this have anything to do with the apisix version? Mine is the apisix 2.15-alpine. I see that the latest version 3.4 is as you said

**Comment by kayx23** [comment]
I unfortunately don't have any knowledge of v2. Maybe somebody else could help confirm. @leslie-tsang

**Comment by moonming** [comment]
> 

These execution orders are the same for APISX 2.x and 3.x @bin-53
