### ISSUE TITLE
feat: As a user, I want to remove rust dependencies, so that reconsider how to install ldap dependencies

### ISSUE THREAD

**Issue by Sn0rt** [apache/apisix#9891]
### Description

In order to simplify the installation process and improve the efficiency of development and installation.

I want to remove the rust dependency.

curreclty. only LDAP need rust . so we want rollback the package to pure lua version. (need not rust anymore.

**Comment by Revolyssup** [comment]
Assign to me

**Comment by Revolyssup** [comment]
Summarising the discussion so far:
* The version v0.1.0 of lua-resty-ldap is incompatible with apisix master so the master branch would require some code changes as well to interface with the roll backed version(the one without Rust dependency)
* We will lose a lot of feature and bug fixes made between this version and moreover as pointed out by @bzp2010 ,  the ldap support in v0.1.0 is not as good.  
* @moonming Suggested that we can have two version of this plugin, one using v0.1.0 and another using v0.2.0. To that I would like to ask for suggestions as to how we can go about this approach. Should we have two plugins like `ldap` and `ldap-advanced` in APISIX using different versions of lua-resty-ldap. And if that's the case, when ldap-advanced(the one using Rust) make dependencies then it will still require Rust at build time.

**Comment by FOWind** [comment]
> Summarising the discussion so far:
> 
> * The version v0.1.0 of lua-resty-ldap is incompatible with apisix master so the master branch would require some code changes as well to interface with the roll backed version(the one without Rust dependency)
> * We will lose a lot of feature and bug fixes made between this version and moreover as pointed out by @bzp2010 ,  the ldap support in v0.1.0 is not as good.
> * @moonming Suggested that we can have two version of this plugin, one using v0.1.0 and another using v0.2.0. To that I would like to ask for suggestions as to how we can go about this approach. Should we have two plugins like `ldap` and `ldap-advanced` in APISIX using different versions of lua-resty-ldap. And if that's the case, when ldap-advanced(the one using Rust) make dependencies then it will still require Rust at build time.

As downgrade to 0.1.0, the ldap cannot use password to connect ldap server. Is there a plan to add the ldap-advanced plugin ?
