### ISSUE TITLE
The cor plug-in allow_methods method setting does not take effect

### ISSUE THREAD

**Issue by bin-53** [apache/apisix#9899]
### Description

Not effective when I set up the allow_methods for the cor plugin. I set the allow GET method but the POST method for cross-domain request is still accessible!!
the cor cfg:（gogal route config）
```
{
    "allow_credential": false,
    "allow_headers": "test",
    "allow_methods": "GET",
    "allow_origins": "*",
    "disable": false,
    "expose_headers": "*",
    "max_age": 5
}
```
the route is :
```
{
    "id": "470289427420152510",
    "create_time": 1689843942,
    "update_time": 1690282751,
    "uri": "/cor/*",
    "name": "cor_xb",
    "priority": 1,
    "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "PATCH",
        "HEAD",
        "OPTIONS"
    ],
    "plugins": {
        "proxy-rewrite": {
            "regex_uri": [
                "^/cor(/|$)(.*)",
                "/$2"
            ]
        }
    },
    "upstream": {
        "nodes": [
            {
                "host": "10.4.16.100",
                "port": 8001,
                "weight": 1
            }
        ],
        "retries": 1,
        "timeout": {
            "connect": 6,
            "send": 6,
            "read": 6
        },
        "type": "roundrobin",
        "scheme": "http",
        "pass_host": "pass",
        "keepalive_pool": {
            "idle_timeout": 60,
            "requests": 1000,
            "size": 320
        }
    },
    "status": 1
}
```
the package is :
![image](https://github.com/apache/apisix/assets/131146587/bc9abf64-8dd5-4462-9001-68665b1ca763)
Don't know where the problem is

As expected is pass because it is set to allow GET requests

the request ajsx is :
```
var params =  JSON.stringify({"username":"admin","password":"admin"});
	            $.ajax({
	           	type:'POST',
                xhrFields: { withCredentials: false },
	           	dataType: "json",
	           	data:params,
	           	url:"http://10.4.16.10:9080/cor/api/apisix/admin/user/login",  //apisix的地址 从其他的三方网站发起的请求
	           	success:function(apiData){
}
```

### Environment

- APISIX version (run `apisix version`):2.15
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by bin-53** [comment]
> anyone can help please？

**Comment by sumansuhag** [comment]
Okay, so the problem is that the CORS plugin only deals with response headers, not controlling which methods can be used. If you want to block POST requests from other sites but still allow GET, here's what you gotta do:

1.  Set up your backend to only allow certain methods (using APISIX route configs or other security plugins).
2.  Make sure the `allow_methods` in your CORS plugin is set up right (with the methods separated by commas).
3.  Don't just depend on CORS headers to keep things secure.

This two-step method makes sure your CORS is secure and follows standards, while your server handles request filtering.
