### ISSUE TITLE
feat: If matched_sni has multiple snis, loop can jump out right after a matched sni has been found.

### ISSUE THREAD

**Issue by rodman10** [apache/apisix#9901]
### Description
In the following code
https://github.com/apache/apisix/blob/master/apisix/ssl/router/radixtree_sni.lua#L184-L189
The loop won't jumped out if a matched sni has been found. Can we break the iteration right after matched? Thanks for reply :)

**Comment by Revolyssup** [comment]
@rodman10 Yes I think we can break out. You can create a PR if you want to.
