### ISSUE TITLE
bug: ext-plugin-pre-req pluging get request body error

### ISSUE THREAD

**Issue by jslpower** [apache/apisix#9907]
### Current Behavior

when post large data, ext-plugin-pre-req plugin filter execute request.get_body(), the body content  is incomplete

### Expected Behavior

1、add log

I write some log in function __ask_extra_info, to show rpc buf length

apisix-python-plugin-runner/apisix/runner/http/request.py

    def __ask_extra_info(self, builder: flatbuffers.Builder, ty, data) -> str:
        """
        nginx built-in variable and request body rpc calls
        :param builder:
        :param ty:
        :param data:
        :return:
        """
        res_val = []
        EIReq.Start(builder)
        EIReq.AddInfoType(builder, ty)
        EIReq.AddInfo(builder, data)
        res = EIReq.End(builder)
        builder.Finish(res)
        out = builder.Output()

        try:
            protocol = RunnerServerProtocol(out, runner_utils.RPC_EXTRA_INFO)
            protocol.encode()
            self.r.conn.sendall(protocol.buffer)
        except socket.timeout as e:
            self.r.log.info("connection timout: {}", e.args.__str__())
        except socket.error as e:
            self.r.log.error("connection error: {}", e.args.__str__())
        except BaseException as e:
            self.r.log.error("any error: {}", e.args.__str__())
        else:
            buf = self.r.conn.recv(runner_utils.RPC_PROTOCOL_HEADER_LEN)
            protocol = RunnerServerProtocol(buf, 0)
            err = protocol.decode()
            **self.r.log.info("protocol.length: {}", str(protocol.length))**
            if err.code == RESP_STATUS_CODE_OK:
                buf = self.r.conn.recv(protocol.length)
                **self.r.log.info("buf.length: {}", len(buf))**
                resp = EIResp.Resp.GetRootAs(buf)
                try:
                    for i in range(resp.ResultLength()):
                        vector = resp.Result(i)
                        res_val.append(chr(vector))
                except BaseException as e:
                    self.r.log.error("any error: {}", e.args.__str__())
            else:
                self.r.log.error(err.message)

        return "".join(res_val)

2、plugin source code

from typing import Any
from apisix.runner.http.request import Request
from apisix.runner.http.response import Response
from apisix.runner.plugin.core import PluginBase

class Rewrite(PluginBase):

    def name(self) -> str:
        """
        The name of the plugin registered in the runner
        :return:
        """
        return "rewrite"

    def config(self, conf: Any) -> Any:
        """
        Parse plugin configuration
        :param conf:
        :return:
        """
        return conf

    def filter(self, conf: Any, request: Request, response: Response):
        """
        The plugin executes the main function
        :param conf:
            plugin configuration after parsing
        :param request:
            request parameters and information
        :param response:
            response parameters and information
        :return:
        """

        # print plugin configuration
        print(conf)

        # Fetch request nginx variable `host`
        host = request.get_var("host")
        print(host)

        # Fetch request body
        body = request.get_body()
        print(body)

        # Rewrite request headers
        request.set_header("X-Resp-A6-Runner", "Python")

        # Rewrite request args
        request.set_arg("a6_runner", "Python")

        # Rewrite request path
        request.set_uri("/a6/python/runner")

-------------------------------------

### Error Logs

2023-07-26 14:34:12,207 - INFO - protocol.length: 286360
, context: ngx.timer
2023/07/26 14:34:12 [warn] 11899#11899: *113 [lua] init.lua:955: 2023-07-26 14:34:12,207 - INFO - buf.length: 219260
, context: ngx.timer
2023/07/26 14:34:15 [warn] 11899#11899: *113 [lua] init.lua:955: 2023-07-26 14:34:15,026 - ERROR - any error: ('unpack_from requires a buffer of at least 1 bytes',)

### Steps to Reproduce

1、enabled ext-plugin-pre-req 

2、post 286360 byte data to backend api

     content-type: text/plain

3、pluging filter execute request.get_body()  is incomplete

     logger info : protocol.length: 286360，buf.length: 219260

-------------------

1、enabled ext-plugin-pre-req 

2、post 117160 byte data to API

3、content-type: text/plain

4、pluging filter execute  request.get_body  is complete

      logger info : protocol.length: 117160，buf.length: 117160

### Environment

- APISIX version (run `apisix version`):3.1.0
- Operating system (run `uname -a`):Linux localhost.localdomain56 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):{"etcd_version":"3.5.0","hostname":"localhost.localdomain56","version":"3.1.0","id":"11fca3d3-2330-462d-a844-23d9f9ab107a","boot_time":1690353632}
- APISIX Dashboard version, if relevant: 3.0.0
- Plugin runner version, for issues related to plugin runners:  apisix-python-plugin-runner 0.2
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@Sn0rt I think this can be transferred to https://github.com/apache/apisix-python-plugin-runner/issues
