### ISSUE TITLE
bug: build from source on ubuntu, failed to run command: apisix init

### ISSUE THREAD

**Issue by hundanLi** [apache/apisix#9910]
### Current Behavior

following the document: https://apisix.apache.org/docs/apisix/building-apisix/ 
when run the command `apisix init` , error occurs:
/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua test
/usr/local/openresty//luajit/bin/luajit: cannot open /usr/local/apisix/apisix/cli/apisix.lua: No such file or directory 

### Expected Behavior

it should be ok to run `apisix init`

### Error Logs

/usr/local/openresty//luajit/bin/luajit /usr/local/apisix/apisix/cli/apisix.lua test
/usr/local/openresty//luajit/bin/luajit: cannot open /usr/local/apisix/apisix/cli/apisix.lua: No such file or directory 

### Steps to Reproduce

Following doc: https://apisix.apache.org/docs/apisix/building-apisix/ to build from source step by step.

### Environment

- APISIX version (run `apisix version`):3.4.1
- Operating system (run `uname -a`):Ubuntu SMP Wed Jun 24 01:15:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.2
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):/usr/local/bin/luarocks 3.8.0

**Comment by kayx23** [comment]
Does the issue still persist? Did your previous steps (e.g. `make`) all work out without errors?
