### ISSUE TITLE
Feature Request: The service discovery support filtering nodes based on registration center metadata.

### ISSUE THREAD

**Issue by ycachi** [apache/apisix#9912]
### Description

 Take Eureka as an example : old eureka client config **eureka.instance.metadata-map.version:A** ,new deploy service config  **eureka.instance.metadata-map.version:B** . The service discovery  filter nodes based on eureka metadata version=A or  version=B ，Implement traffic distribution to different version nodes.
![eureka](https://github.com/apache/apisix/assets/32326689/ea54ab1e-479a-4d55-95b9-b167e8cb3d05)

**Comment by shenqidebaozi** [comment]
https://github.com/apache/apisix/issues/9476

**Comment by jzhao20230918** [comment]
> #9476

I think this is a different issue? Does Apisix support routing based on metadata get via service discovery?
