### ISSUE TITLE
feat: As a user, I want to expose the static files through API, so that I can fetch a file from a specified URL

### ISSUE THREAD

**Issue by Boburmirzo** [apache/apisix#9914]
### Description

As a user, I want to expose the static files through API, so that I can fetch a file from a specified URL. 

Assume that we want to expose a static file (Yaml, JSON, JavaScript, CSS, or image files) through API. Then your API users can access the file at the specified URL (https://apisix.com/openapi.json).

I tried to create a custom plugin here and it would be great if we can include it officially on APISIX website (maybe it needs some improvements but now it is working well):

https://github.com/Boburmirzo/apisix-file-proxy-plugin-demo

**Comment by nfrankel** [comment]
Several comments mention "don't serve static content" with Apache APISIX, _e.g._, https://github.com/apache/apisix/discussions/6082#discussioncomment-1977367

**Comment by Boburmirzo** [comment]
Good to know.
