### ISSUE TITLE
help request: content-based healthcheck

### ISSUE THREAD

**Issue by qwzhou89** [apache/apisix#9920]
### Description

There is a need to check whether a field in the upstream's return body (in json format) is the specified value, and only the field with the specified value is considered to be a healthy node when doing a healthcheck on a certain route.
Is there a way to customize this to the current healthcheck?

**Comment by theweakgod** [comment]
@qwzhou89 I think it is not necessary to check a certain field in the body. I think it is very simple to make an API specifically for health checks to match the entire content of the body. What you think.
