### ISSUE TITLE
help request: when etcd enable auth, the etcd log will continuously print ‘delete a simple token’

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9925]
### Description

help request: when etcd enable auth, the etcd log will continuously print ‘delete a simple token’
![WechatIMG1](https://github.com/apache/apisix/assets/10181098/e2ec126e-211c-4548-be10-5ad2b59c2def)

### Environment

- APISIX version (run `apisix version`):  3.2
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi, could you provide detailed reproduction steps?

**Comment by zzqCh** [comment]
1.Start ETCD and configure the password. The current ETCD version used is 3.5.9
<img width="614" alt="image-20230801113404745" src="https://github.com/apache/apisix/assets/10181098/60178885-5401-4ecc-ad28-a35370346a50">

2. config the apisix and enable the user and password
<img width="741" alt="image-20230801113313070" src="https://github.com/apache/apisix/assets/10181098/a02eea91-549f-4aeb-875e-af9516efff77">

3. execute 'make run' command
4. stop the server etcd
5. start the etcd server and then will see the etcd logs
   
<img width="1282" alt="image-20230801113519505" src="https://github.com/apache/apisix/assets/10181098/99ad5662-e056-4431-bbb0-f890d6bb809d">

6. If apisix  runs continuously, the logs of etcd will continue to be print 'deleted a simple token'

**Comment by zzqCh** [comment]
> Hi, could you provide detailed reproduction steps?

1.Start ETCD and configure the password. The current ETCD version used is 3.5.9
<img width="614" alt="image-20230801113404745" src="https://github.com/apache/apisix/assets/10181098/60178885-5401-4ecc-ad28-a35370346a50">

2. config the apisix and enable the user and password
<img width="741" alt="image-20230801113313070" src="https://github.com/apache/apisix/assets/10181098/a02eea91-549f-4aeb-875e-af9516efff77">

3. execute 'make run' command
4. stop the server etcd
5. start the etcd server and then will see the etcd logs
   
<img width="1282" alt="image-20230801113519505" src="https://github.com/apache/apisix/assets/10181098/99ad5662-e056-4431-bbb0-f890d6bb809d">

6. If apisix  runs continuously, the logs of etcd will continue to be print 'deleted a simple token'

**Comment by shreemaan-abhishek** [comment]
How did you configure the etcd password and username in etcd? (not asking about apisix config.yaml)

**Comment by zzqCh** [comment]
> How did you configure the etcd password and username in etcd? (not asking about apisix config.yaml)

Yeah，the root password is same with apisix config.yaml

**Comment by shreemaan-abhishek** [comment]
Please share the configuration with me.

**Comment by jiangfucheng** [comment]
@zzqCh I reproduced this issue partly. 
After I stop and start etcd, APISIX will not be able to watch etcd for about 50s, and then it will return to normal.

**Comment by zzqCh** [comment]
> @zzqCh I reproduced this issue partly. After I stop and start etcd, APISIX will not be able to watch etcd for about 50s, and then it will return to normal. Maybe it's harmless?

If apisx runs for a long time, such as five hours, the etcd will print many "deleted a simple token" log。like this
<img width="1324" alt="image" src="https://github.com/apache/apisix/assets/10181098/2b018731-f55e-4672-8b93-ef7db5f8d98d">

**Comment by zzqCh** [comment]
> 
I configured with the environment variable, the env name is 'ETCD_ROOT_PASSWORD'
<img width="400" alt="image" src="https://github.com/apache/apisix/assets/10181098/f1777afb-2f96-411e-993d-b971611602d4">

**Comment by zzqCh** [comment]
> @zzqCh I reproduced this issue partly. After I stop and start etcd, APISIX will not be able to watch etcd for about 50s, and then it will return to normal. Maybe it's harmless?

**Comment by zzqCh** [comment]
> Please share the (etcd) configuration with me.

also, if the configuration is wrong ,the etcd will print the 'invalid auth' not 'delete a simple token'

**Comment by shreemaan-abhishek** [comment]
That is probably an issue with etcd. And they are info logs so I don't think they are problematic.
