### ISSUE TITLE
bug: Method was overrided without configuration

### ISSUE THREAD

**Issue by wavemoroc001** [apache/apisix#9929]
### Current Behavior

I faced with weird behavior that i sent request with `POST` method to my service but my service logged `GET` method. The method should be `POST` on my service.

### Expected Behavior

should not override method without configured.

### Steps to Reproduce

1. Run APISIX image version 3.4.1
2. Deploy some service which can log request method (I use nginx)
3. Create simple route like in this example via APISIX Dashboard and map route to service in number 2
``` json
{
  "uris": [
    "/api/classroom-service/health"
  ],
  "name": "test override method",
  "upstream": {
    "nodes": [
      {
        "host": "classroom",
        "port": 8585,
        "weight": 1
      }
    ],
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "pass_host": "pass"
  },
  "status": 1
}
```
4. Sent some request with different method.

I use nginx and take a look in access.log
```log
172.18.0.8 - - [29/Jul/2023:18:32:32 +0000] "GET /api/classroom-service/health HTTP/1.1" 200 10 "http://host/api/classroom-service/health" "PostmanRuntime/7.32.3" // Should be POST
172.18.0.8 - - [29/Jul/2023:18:34:23 +0000] "GET /api/classroom-service/health HTTP/1.1" 200 10 "http://host/api/classroom-service/health" "PostmanRuntime/7.32.3" //Should be PUT
```

### Environment

- APISIX version (run `apisix version`): 3.4.1
- Operating system (run `uname -a`): Debian image
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):3.4.15
- APISIX Dashboard version, if relevant: 3.0.1
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by jiangfucheng** [comment]
Hi， could you provide specific request command?

**Comment by wavemoroc001** [comment]
Just simple cmd 

```bash
curl --location --request PUT 'host/api/classroom-service/health'
```

**Comment by jiangfucheng** [comment]
![image](https://github.com/apache/apisix/assets/33349046/88be0aea-cfb5-4754-a093-1f198c5a7e88)
![image](https://github.com/apache/apisix/assets/33349046/d2ebc729-1f67-4677-b13f-dee4383a5e7b)
I can't reproduce it.

**Comment by wavemoroc001** [comment]
Sorry, It just misconfiguration on postman. Not related to APISIX
