### ISSUE TITLE
bug: route 404 after upgrade to 3.2.2

### ISSUE THREAD

**Issue by wklken** [apache/apisix#9951]
### Current Behavior

register route and service into etcd, the changes not been watched and got 404

### Expected Behavior

apisix watch the changes in time, the url should not be 404

### Error Logs

I have create route/service 4 times, delete the instance and redo
only 1 time got an error log. another 3 times got no error log(still 404)

```
2023/08/02 08:28:44 [error] 1051#1051: *44434 upstream timed out (110: Connection timed out) while reading upstream, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", upstream: "http://10.1.1.1:2379/v3/watch", host: "127.0.0.1"
```

---

`apisix reload`

```
2023/08/02 08:49:43 [warn] 38#38: *19 [lua] config_etcd.lua:168: main etcd watcher started, revision=437733, context: ngx.timer
2023/08/02 08:49:43 [warn] 41#41: *36 [lua] config_etcd.lua:168: main etcd watcher started, revision=437733, context: ngx.timer

....
# do reload

2023/08/02 09:05:05 [notice] 770#770: signal process started
2023/08/02 09:05:05 [emerg] 773#773: bind() to 0.0.0.0:6008 failed (98: Address already in use)
2023/08/02 09:05:05 [warn] 771#771: *24136 [lua] config_etcd.lua:168: main etcd watcher started, revision=437755, context: ngx.timer
```

### Steps to Reproduce

1. upgrade apisix from 3.2.1 to 3.2.2
2. register the service and route
3. apisix-dashboard can see the route and service
4. apisix admin api can fetch the route and service
5. call the url,  404
7. do `apisix reload`, call the url, 200;
8. downgrade to apisix 3.2.1, do 2-5, call the url, 200;

------

got an error log

maybe this feature cause the error: https://github.com/apache/apisix/pull/9456

### Environment

- APISIX version (run `apisix version`): 3.2.2
- Operating system (run `uname -a`): 
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 2.5.4
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by qihaiyan** [comment]
Same error occurs to me.

**Comment by jiangfucheng** [comment]
@wklken Hi, I can't reproduce this issue, here is my reproduction step, please help me check the difference with your description.
1. checkout code to 3.2.2
`git checkout -b 3.2.2 3.2.2 `
2. update dependency
`make deps`
3. start apisix
`make run`
4. create route (I start a nginx as backend server with 9081 port)
```
 curl 127.0.0.1:9180/apisix/admin/routes/1 -H "X-API-KEY: edd1c9f034335f136f87ad84b625c8f1" -X PUT -d '
{
  "uri": "/*",
  "name": "test",
  "methods": [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "PATCH",
    "HEAD",
    "OPTIONS",
    "CONNECT",
    "TRACE",
    "PURGE"
  ],
  "upstream": {
    "nodes": [
      {
        "host": "127.0.0.1",
        "port": 9081,
        "weight": 1
      }
    ],
    "timeout": {
      "connect": 6,
      "send": 6,
      "read": 6
    },
    "type": "roundrobin",
    "scheme": "http",
    "pass_host": "pass",
    "keepalive_pool": {
      "idle_timeout": 60,
      "requests": 1000,
      "size": 320
    }
  },
  "status": 1
}'
```
5. access apisix
`curl localhost:9080`
6. check the result
`hello web1%`

**Comment by qihaiyan** [comment]
try using a etcd cluster with auth enabled @jiangfucheng

**Comment by jiangfucheng** [comment]
> try using a etcd cluster with auth enabled @jiangfucheng

I follow this project https://github.com/guessi/docker-compose-etcd to start an etcd cluster in my local env, and enable auth, but still can't reproduce this issue.

**Comment by wklken** [comment]
I run the apisix in k8s, the etcd address is a service(bitnami etcd helm chart)
And I set `timeout` to `120`

```yaml
deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  etcd:
    host:
      - "http://apigateway-etcd:2379"
    timeout: 120
    prefix: /gateway-apisix
    user: root
    password: xxxx
```

**Comment by qihaiyan** [comment]
I use route+service too, maybe this is the cause.

**Comment by wklken** [comment]
after register the route+service, got 404

> curl 'http://127.0.0.1:9180/apisix/admin/services/eee.prod.stage-20'  -H 'X-API-KEY: eex3P86cLLSlAOagO1em3FADrRXhMR2c' | jq

```
{
  "key": "/bk-gateway-apisix/services/eee.prod.stage-20",
  "modifiedIndex": 437855,
  "value": {
    "labels": {
      "gateway.bk.tencent.com/stage": "prod",
      "gateway.bk.tencent.com/gateway": "eee"
    },
    "update_time": 1691028294,
```

the modifiedIndex is `437855`

and the log,  `/watch` start_revisions is `437868`, so at that time, the apisix has no newest configdata, and will never know the changes until reload/restart

```
2023/08/03 02:10:04 [info] 37#37: *19 [lua] v3.lua:852: request_chunk(): http request method: POST path: /watch body: {"create_request":{"range_end":"L2JrLWdhdGV3YXktYXBpc2l4MA==","key":"L2JrLWdhdGV3YXktYXBpc2l4Lw==","start_revision":437868}} query: nil, context: ngx.timer
2023/08/03 02:10:04 [info] 37#37: *19 [lua] config_etcd.lua:193: res_func: {
  result = {
    created = true,
    header = {
      cluster_id = "3892788201713343575",
      member_id = "12985827509394625062",
      raft_term = "57",
      revision = "437868"
    }
  }
}, context: ngx.timer
```

and I add another route+service, 404; 


```
2023/08/03 02:22:05 [info] 40#40: *40 [lua] config_etcd.lua:193: res_func: nil, context: ngx.timer
2023/08/03 02:22:05 [info] 40#40: *40 [lua] config_etcd.lua:107: cancel_watch(): cancel watch connection success, context: ngx.timer
2023/08/03 02:22:05 [info] 40#40: *40 [lua] config_etcd.lua:181: restart watchdir: start_revision=437886, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *28877 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while reading upstream, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", upstream: "http://1.1.1.1:2379/v3/watch", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 40#40: *40 [lua] v3.lua:76: choose_endpoint(): choose endpoint: http://127.0.0.1:2379, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *19 [lua] config_etcd.lua:193: res_func: nil, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *19 [lua] config_etcd.lua:107: cancel_watch(): cancel watch connection success, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *19 [lua] config_etcd.lua:181: restart watchdir: start_revision=437886, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *19 [lua] v3.lua:76: choose_endpoint(): choose endpoint: http://127.0.0.1:2379, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *29656 [lua] client.lua:123: dns_parse(): dns resolve bk-apigateway-etcd, result: {"class":1,"address":"1.1.1.1","section":1,"name":"bk-apigateway-etcd.default.svc.cluster.local","ttl":30,"type":1}, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *29656 [lua] resolver.lua:84: parse_domain(): parse addr: {"class":1,"section":1,"address":"1.1.1.1","name":"bk-apigateway-etcd.default.svc.cluster.local","ttl":30,"type":1}, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *29656 [lua] resolver.lua:85: parse_domain(): resolver: ["10.96.0.10"], client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *29656 [lua] resolver.lua:86: parse_domain(): host: bk-apigateway-etcd, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *29656 [lua] resolver.lua:88: parse_domain(): dns resolver domain: bk-apigateway-etcd to 1.1.1.1, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *29589 epoll_wait() reported that client prematurely closed connection, so upstream connection is closed too while reading upstream, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", upstream: "http://1.1.1.1:2379/v3/watch", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *30892 [lua] client.lua:123: dns_parse(): dns resolve bk-apigateway-etcd, result: {"class":1,"address":"1.1.1.1","section":1,"name":"bk-apigateway-etcd.default.svc.cluster.local","ttl":30,"type":1}, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *30892 [lua] resolver.lua:84: parse_domain(): parse addr: {"class":1,"section":1,"address":"1.1.1.1","name":"bk-apigateway-etcd.default.svc.cluster.local","ttl":30,"type":1}, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *30892 [lua] resolver.lua:85: parse_domain(): resolver: ["10.96.0.10"], client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *30892 [lua] resolver.lua:86: parse_domain(): host: bk-apigateway-etcd, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 37#37: *30892 [lua] resolver.lua:88: parse_domain(): dns resolver domain: bk-apigateway-etcd to 1.1.1.1, client: unix:, server: , request: "POST /v3/watch HTTP/1.1", host: "127.0.0.1"
2023/08/03 02:22:05 [info] 40#40: *40 [lua] v3.lua:852: request_chunk(): http request method: POST path: /watch body: {"create_request":{"range_end":"L2JrLWdhdGV3YXktYXBpc2l4MA==","key":"L2JrLWdhdGV3YXktYXBpc2l4Lw==","start_revision":437886}} query: nil, context: ngx.timer
2023/08/03 02:22:05 [info] 37#37: *19 [lua] v3.lua:852: request_chunk(): http request method: POST path: /watch body: {"create_request":{"range_end":"L2JrLWdhdGV3YXktYXBpc2l4MA==","key":"L2JrLWdhdGV3YXktYXBpc2l4Lw==","start_revision":437886}} query: nil, context: ngx.timer
2023/08/03 02:22:05 [info] 40#40: *40 [lua] config_etcd.lua:193: res_func: {
  result = {
    created = true,
    header = {
      cluster_id = "3892788201713343575",
      member_id = "12985827509394625062",
      raft_term = "57",
      revision = "437886"
    }
  }
}, context: ngx.timer

```

----

How the apisix know the `start_reversion` after it cancel and start a new connection?

**Comment by wklken** [comment]
@jiangfucheng can you please raise the level of this bug? Version 3.2.2/3.4.0/3.4.1 may all be affected(if it's related to #9456), especially if deploy or upgrade in a production environment.

**Comment by jiangfucheng** [comment]
@monkeyDluffy6017 @kingluo Hi, could you help take a look at this issue, I don't have enough time to process this issue in a timely manner.

**Comment by monkeyDluffy6017** [comment]
@Sn0rt Could you help to check?

**Comment by Sn0rt** [comment]
got. I will try to reproduce this .

**Comment by wklken** [comment]
@Sn0rt create the route and service on the version 3.2.2

- the first sync after `start` is right
- the sync after `reload` is right too
- only the changes after `start` would be 404

**Comment by Sn0rt** [comment]
> `upgrade apisix from 3.2.1 to 3.2.2`

the original  3.2.1 upgrade to 3.2.2.

the original 3.2.2 downgrade to 3.2.1.

which one is your case ?

**Comment by Sn0rt** [comment]
# check the etcd

```bash
~/w/apisix> etcdctl get /apisix/routes/100
/apisix/routes/100
{"uri":"/anything","service_id":"200","priority":0,"id":"100","create_time":1691050439,"methods":["GET"],"update_time":1691050439,"status":1}
~/w/apisix> etcdctl get /apisix/services/200
/apisix/services/200
{"create_time":1691050434,"upstream":{"nodes":{"httpbin.org:80":1},"type":"roundrobin","hash_on":"vars","scheme":"http","pass_host":"pass"},"update_time":1691050434,"id":"200"}
```

format the result `/apisix/routes/100`

```bash
{
  "uri": "/anything",
  "service_id": "200",
  "priority": 0,
  "id": "100",
  "create_time": 1691050439,
  "methods": [
    "GET"
  ],
  "update_time": 1691050439,
  "status": 1
}
```

the `/apisix/services/200`

```bash
{
  "create_time": 1691050434,
  "upstream": {
    "nodes": {
      "httpbin.org:80": 1
    },
    "type": "roundrobin",
    "hash_on": "vars",
    "scheme": "http",
    "pass_host": "pass"
  },
  "update_time": 1691050434,
  "id": "200"
}
```

**Comment by wklken** [comment]
@Sn0rt I am not sure your reproduce step is correct

------

my step is:
1. use 3.2.1, crate route/service, 200
2. upgrade to 3.2.2, create route/service, 404, `apisix reload`, 200, create another route/service, 404; (and in the error.log got not error, it seems the apisix did not watched the changes)

------

the 3.2.1 is ok(we deployed on production for a long time), only the 3.2.2 has the `404` issue;

**Comment by Sn0rt** [comment]
> * use 3.2.1, crate route/service, 200

So can you simplify the environment to reproduce? I'm checking my steps to reproduce.

I don't quite understand what you describe, it is best to provide certain steps to reproduce.

**Comment by wklken** [comment]
@Sn0rt  I have reproduce it via docker-compose;  the key is change the `deployment.etcd.prefix`!

------

the steps:
1. `git clone https://github.com/apache/apisix-docker.git`
2. `cd apisix-docker/compose`
3. edit the docker-compose-master.yaml
```yaml
version: "3"

services:
  apisix:
    # image: "apache/apisix:${APISIX_DOCKER_TAG}"
    image: "apache/apisix:3.2.2-centos"
    restart: always
    volumes:
      - ./apisix_conf/master/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.5.7
    # user: root
    # restart: always
    volumes:
      - ../example/etcd_data:/bitnami/etcd_data
        # volumes:
        #   - etcd_data:/bitnami/etcd
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379/tcp"
    networks:
      - apisix

networks:
  apisix:
    driver: bridge
```
4. edit the `apisix_conf/master/config.yaml`
```
apisix:
  node_listen: 9080              # APISIX listening port
  enable_ipv6: false

  router:
    http: radixtree_uri_with_parameter

nginx_config:
  http:
    enable_access_log: false
    client_max_body_size: "40m"

  error_log_level: "info"
  worker_processes: 1

deployment:
  admin:
    allow_admin:               # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0              # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1
        role: admin                 # admin: manage all configuration data

  etcd:
    host:                           # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379"          # multiple etcd address
    prefix: "/test-apisix"               # apisix configurations prefix
    timeout: 120                    # 30 seconds
```
6. `rm -rf ../example/etcd_data/*` 
7. `docker-compose -p docker-apisix -f docker-compose-master.yaml up`
8. open another terminal, `docker ps -a` get the running container id of apisix
9. `docker exec -it {the id} /bin/bash`
10. register the route and service
```
curl http://127.0.0.1:9180/apisix/admin/services/200 \
                                                                -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
                                                {
                                                    "upstream": {
                                                        "type": "roundrobin",
                                                        "nodes": {
                                                      "etcd:2379": 1
                                                        }
                                                    }
                                                }'
curl http://127.0.0.1:9180/apisix/admin/routes/100 \
                                                -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
                                    {
                                        "methods": ["GET"],
                                        "uri": "/metrics",
                                        "service_id": "200"
                                    }'
```
11. there got no watch logs for the route and resource (if you change the `prefix` back, you can see the logs)
12. curl, got 404 `curl http://localhost:9080/metrics -v`


-----

if we change the `prefix` back to `/apisix`, the step 12 will got 200

**Comment by kingluo** [comment]
@wklken It's not supposed to change prefix at the runtime, even if followed by `apisix reload`.
In the current implementation, the keys layout of etcd `prefix` is required to be initiated either by `apisix init`, `apistx start`, or `apisix restart`, but not by `apisix reload`.

**Comment by wklken** [comment]
@kingluo when we change the prefix in `config.yaml` then start the apisix, the execution order is `apisix start`(`prefix=/apisix`) then `apisix reload`(`prefix=/custom-prefix`)?  

------

change the prefix in config.yaml, then docker-compose up, put a route and service, the `config_etcd.lua` got the events, but still 404

```
apisix_1  | 2023/08/03 14:14:50 [info] 51#51: *16 [lua] config_etcd.lua:117: produce_res(): append res: {
apisix_1  |   result = {
apisix_1  |     events = { {
apisix_1  |         kv = {
apisix_1  |           create_revision = "45",
apisix_1  |           key = "/test-apisix/routes/100",
apisix_1  |           mod_revision = "45",
apisix_1  |           value = {
apisix_1  |             create_time = 1691072090,
apisix_1  |             id = "100",
apisix_1  |             methods = { "GET",
apisix_1  |               <metatable> = <1>{}
apisix_1  |             },
apisix_1  |             priority = 0,
apisix_1  |             service_id = "200",
apisix_1  |             status = 1,
apisix_1  |             update_time = 1691072090,
apisix_1  |             uri = "/metrics"
apisix_1  |           },
apisix_1  |           version = "1"
apisix_1  |         }
apisix_1  |       },
apisix_1  |       <metatable> = <table 1>
apisix_1  |     },
apisix_1  |     header = {
apisix_1  |       cluster_id = "14841639068965178418",
apisix_1  |       member_id = "10276657743932975437",
apisix_1  |       raft_term = "5",
apisix_1  |       revision = "45"
apisix_1  |     }
apisix_1  |   }
apisix_1  | }, err: nil, context: ngx.timer
```

**Comment by kingluo** [comment]
@wklken 
`apisix start` has nothing to do with `apisix reload`, the previous one implies etcd layout initialization under the prefix.
**To simplify the scenario, please keep the prefix unchanged and try to reproduce the issue.**
It's better to keep those steps stable. It seems you talked about multiple scenarios with only a little of differences, which confused me a bit.
Tell me the final version of the full and detailed steps and I'll try to check it sooner or later. Thanks.

**Comment by jiangfucheng** [comment]
https://github.com/apache/apisix/blob/f99cf546d4a514f73870073cf3e3bfeb598a5777/apisix/core/config_etcd.lua#L395C30-L395C30 
It cause by this code, `string.find()` method default is pattern matching. 

ref: https://www.lua.org/manual/5.1/manual.html#pdf-string.find

**Comment by wklken** [comment]
> @wklken `apisix start` has nothing to do with `apisix reload`, the previous one implies etcd layout initialization under the prefix. **To simplify the scenario, please keep the prefix unchanged and try to reproduce the issue.** It's better to keep those steps stable. It seems you talked about multiple scenarios with only a little of differences, which confused me a bit. Tell me the final version of the full and detailed steps and I'll try to check it sooner or later. Thanks.

@kingluo 

sorry for the confusing words in the reproduce steps, I have changed it to `if you start from the beginning, change the `prefix` back to `/apisix` in the step 4 , then step 12 will got 200`, the steps is correct.

**Comment by wklken** [comment]
@jiangfucheng I have checked, if we remove the `-` from prefix, the 404 disappeared.

**Comment by monkeyDluffy6017** [comment]
@jiangfucheng Excellent work!

**Comment by kingluo** [comment]
> https://github.com/apache/apisix/blob/f99cf546d4a514f73870073cf3e3bfeb598a5777/apisix/core/config_etcd.lua#L395C30-L395C30 I reproduced this bug, It seems causes by this code, `string.find()` method default is pattern matching， “-” is a special character.
> 
> ref: https://www.lua.org/manual/5.1/manual.html#pdf-string.find

Yes, it's a bug. Thanks for your bugfix.
