### ISSUE TITLE
bug: stringx.strip using wrong index if # > 200

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#9959]
### Current Behavior

String won't be striped correctly with stringx.strip funcion if length > 200.
the penlight version 1.9.2-1 used by apisix has this bug, and was fixed in 1.10.0 with commit: https://github.com/lunarmodules/Penlight/commit/19c863ed5a28fc25b6031fef46fc83add51a7169
so maybe we should update penlight to the latest version in rockspec.

### Steps to Reproduce

use stringx.strip in any plugin's code.

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`): ubuntu
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`): 1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): 3.5.7
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
Welcome PR to upgrade penlight @qihaiyan
