### ISSUE TITLE
websocket connect error：'matched_ssl' (a nil value)  

### ISSUE THREAD

**Issue by wwwsky86** [apache/apisix#9962]
### Description

**Using the macOS chrome browser, the following error may occur**

2023/08/03 15:26:33 [error] 49#49: *263477 lua entry thread aborted: runtime error: /usr/local/apisix/apisix/init.lua:332: attempt to index local 'matched_ssl' (a nil value)
stack traceback:
coroutine 0:
	/usr/local/apisix/apisix/init.lua: in function 'verify_https_client'
	/usr/local/apisix/apisix/init.lua:560: in function 'http_access_phase'
	access_by_lua(nginx.conf:408):2: in main chunk, client: 172.20.30.121, server: _, request: "GET /96d2d3a4caafa1fc41c66833ab95ed4d/18090/ HTTP/1.1", host: "abc.*.cn"

**Use safari browser or linux curl command or window  chrome , the return of apisix is OK** （http code 200）

**Comment by Sn0rt** [comment]
I can't help you with your description.

he key information is as follows

1. Your router, upstram configuration information, etc.
2. How does your client trigger this issue?
3. APISIX version number
4. Simplify the scene where the problem occurs as much as possible, and do not rely on non-essential components.

**Comment by wwwsky86** [comment]
**Rollback to Apisix 3.3.0 solve the problem**
![image](https://github.com/apache/apisix/assets/10069198/67b93098-ee07-480c-b559-5841e53852a4)

**Comment by Revolyssup** [comment]
@wwwsky86 you can close the issue then
