### ISSUE TITLE
help request: how to configure rate limiting per consumer per route

### ISSUE THREAD

**Issue by DGolubets** [apache/apisix#9965]
### Description

I want to enable rate limiting for a particular consumer for a particular route.

So far I didn't find how can that be enabled. 

### Environment

APISIX install with Helm in k8s.
Chart version: apisix-2.1.0
App version: 3.4.0

**Comment by shreemaan-abhishek** [comment]
Is this similar to your requirement: https://the-asf.slack.com/archives/CUC5MN17A/p1690449611274429?

**Comment by DGolubets** [comment]
> Is this similar to your requirement: https://the-asf.slack.com/archives/CUC5MN17A/p1690449611274429?

I don't have ASF account to check.

**Comment by shreemaan-abhishek** [comment]
Please join #apisix channel after joining the ASF slack workspace: https://join.slack.com/t/the-asf/shared_invite/zt-1z1cth9wx-2CMIattLWRW5R5ytuNHIgA

**Comment by Sn0rt** [comment]
hi @DGolubets have you try this feature in req-limit plugin ?

![image](https://github.com/apache/apisix/assets/2706161/e9a3e289-def6-4d40-90d3-50ab44c880d1)


https://apisix.apache.org/docs/apisix/plugins/limit-req/

**Comment by DGolubets** [comment]
Hey,

> Please join #apisix channel after joining the ASF slack workspace: https://join.slack.com/t/the-asf/shared_invite/zt-1z1cth9wx-2CMIattLWRW5R5ytuNHIgA

Thanks for the invite

No, my requirement is different, it's more like what I found a bit down the thread there: https://the-asf.slack.com/archives/CUC5MN17A/p1676970398154249

> hi @DGolubets have you try this feature in req-limit plugin ?
> 
> ![image](https://user-images.githubusercontent.com/2706161/258307631-e9a3e289-def6-4d40-90d3-50ab44c880d1.png)
> 
> https://apisix.apache.org/docs/apisix/plugins/limit-req/

The problem with keys is that you can only specify the variable name, not the value.

Essentialy what I want is: 
```
ConsumerA -> Route1 -> 10 rps
ConsumerA -> Route2 -> 20 rps
ConsumerB -> Route1 -> 5 rps
ConsumerB -> Route1 -> 5 rps
ConsumerB -> Route2 -> unlimited
ConsumerC -> unlimited
```

**Comment by Revolyssup** [comment]
> Hey,
> 
> > Please join #apisix channel after joining the ASF slack workspace: https://join.slack.com/t/the-asf/shared_invite/zt-1z1cth9wx-2CMIattLWRW5R5ytuNHIgA
> 
> Thanks for the invite
> 
> No, my requirement is different, it's more like what I found a bit down the thread there: https://the-asf.slack.com/archives/CUC5MN17A/p1676970398154249
> 
> > hi @DGolubets have you try this feature in req-limit plugin ?
> > ![image](https://user-images.githubusercontent.com/2706161/258307631-e9a3e289-def6-4d40-90d3-50ab44c880d1.png)
> > https://apisix.apache.org/docs/apisix/plugins/limit-req/
> 
> The problem with keys is that you can only specify the variable name, not the value.
> 
> Essentialy what I want is:
> 
> ```
> ConsumerA -> Route1 -> 10 rps
> ConsumerA -> Route2 -> 20 rps
> ConsumerB -> Route1 -> 5 rps
> ConsumerB -> Route1 -> 5 rps
> ConsumerB -> Route2 -> unlimited
> ConsumerC -> unlimited
> ```

Currently rate limit plugin doesn't support per consumer per route, this can be a feature request.

**Comment by DGolubets** [comment]
I've found the Workflow plugin, which seems to allow me to do what I want, though it only supports `limit-count`. I think it would be really cool if it supported all the plugins, allowing for complex logic.

**Comment by shreemaan-abhishek** [comment]
@DGolubets would you mind sharing how you did that?

**Comment by shreemaan-abhishek** [comment]
I see, thanks for the share. You can close this issue if your problem is resolved.
