### ISSUE TITLE
docs: 所有文档

### ISSUE THREAD

**Issue by gjing1st** [apache/apisix#9968]
### Current State

目前文档基本都是英文编写。即使切换为中文，仍然有大量的英文。而且文档写的实在是不敢恭维。即难以找到想要的文档，而且就算找到了也是简单的一笔代过。好比说我要看https部分，1.5版本还有个文档，3版本后根本找不到。找个ip如何配置https更是找不到。如果要看国密https，那完犊子，全网都找不到方法或者插件要怎么搞。

再牛逼的产品，如果文档是一坨屎，别人不会用也白瞎。APISIX功能搞那么多完全没必要，先把主要的搞好。然后把文档写清楚，别人才会来用。
之前温老师说一个月发一版，我觉着完全没必要非得一个月一版本，追求多少位贡献值。一个月一版，现在这么多人，都不知道增加了哪些功能，文档完全跟不上。
现在APISIX已经那么多功能了，先把文档写好，国内用户原本可以很多的，看论坛就知道了，很多人都放弃了APISIX，说它是个半成品。做好核心，维护好核心功能生态，再发展其他的。
建议看看人家KubeShpere产品版本和文档说明。别说什么apache顶级项目，最快孵化，没什么用，文档就是一坨屎。现在人家Kong都进化的这么好了，你文档都写不好，让别人咋用，为什么要用你APISIX。

### Desired State

希望好好完善文档，别在那追求一个月一版本了！！！

**Comment by shreemaan-abhishek** [comment]
Please use English while communicating so everyone can help you better.

**Comment by saytesnake** [comment]
APISIX 跟同为 Apache 系的 SkyWalking，私以为均比其对应的竞品 Kong 与 Pinpoint 都要好，但文档也确实一言难尽，主要是，看似也没人关心这文档。

伸手党、沉默自研党，还是出门右拐 Kong，be to or not to be，但是，就国内的开源产品来说，KubeShpere、快猫星云、飞致云的产品文档确实足够优秀；

@shreemaan-abhishek 

APISIX or SkyWalking, in my opinion, all are better than their corresponding competitors Kong and Pinpoint. But the docs, it's truly quite poor and not friendly. More importantly, it seems that no one cares about how to write good documentation.

Of course, we don't wanna be a freeloader, but the truth is that we might not know APISIX as well as APISIX's contributors do.

**Comment by moonming** [comment]
@gjing1st @saytesnake Thank you for your feedback. The documentation of APISIX is mainly contributed by hundreds of developers in the community, so it has not been sorted out systematically, and it is not friendly for users.

We are refactoring the documentation of APISIX, the new documentation website is here: https://docs.api7.ai/apisix/documentation
