### ISSUE TITLE
doc(FAQ): Why is the ID displayed on the dashboard not the original value of etcd?

### ISSUE THREAD

**Issue by membphis** [apache/apisix#997]
为什么仪表板上显示的ID不是etcd的原始值？

Why is the ID displayed on the dashboard not the original value of etcd?

**Comment by juzhiyuan** [comment]
The original ID is too long to display, so we shorten the ID for the beauty of our dashboard. For example, we assume the original id is `00000000000000034831`, we will shorten it to `34831` in this way: `originalId.replace(/^(0+)/, '')`

**Comment by ShiningRush** [comment]
This is not a good way, my team member usually confuse the id between dashboard and admin api.I think id should keep same as it was, no tricks.

Maybe We should discuss whether it is a FAQ or fix.

**Comment by juzhiyuan** [comment]
> This is not a good way, my team member usually confuse the id between dashboard and admin api.I think id should keep same as it was, no tricks.
> 
> Maybe We should discuss whether it is a FAQ or fix.

🤔ok, I will Pin this issue. Also, the new dashboard is under development on Next branch! Welcome to contribute!
