### ISSUE TITLE
help request: How to solve "accept4() failed (24: Too many open files)"

### ISSUE THREAD

**Issue by cyrnicolase** [apache/apisix#9970]
### Description

I got lots of nginx error log. "accept4() failed (24: Too many open files)" . i don't know what's wrong.

### Environment

- APISIX version : 3.3.0
- Operating system : Linux apisix-197 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version : openresty/1.21.4.1
- etcd version: 3.5.0

**Comment by Revolyssup** [comment]
@cyrnicolase Can you provide some more information about your environment?
You might have to adjust resource limit on your environment? 
Make sure to run `ulimit -n 1024`  in your environment.
You can check the limit by running
`su - <user> -c "ulimit -a"` where `<user>` is the user of the openresty process on which APISIX is running.

**Comment by cyrnicolase** [comment]
> @cyrnicolase Can you provide some more information about your environment? You might have to adjust resource limit on your environment? Make sure to run `ulimit -n 1024` in your environment. You can check the limit by running `su - <user> -c "ulimit -a"` where `<user>` is the user of the openresty process on which APISIX is running.

Thanks fo reply. my openresty is running on root. 

![apsix-show](https://github.com/apache/apisix/assets/2086960/cafd512f-f54a-4f5c-92cc-00167021af72)

**Comment by Revolyssup** [comment]
@cyrnicolase This is the master process, can you confirm that the nginx worker process has enough open files limit set?

**Comment by cyrnicolase** [comment]
@Revolyssup Thanks, I have found the answer. The plugin `request-id` may be have some bugs in `nanoid`.
