### ISSUE TITLE
help request: error starting etcd pods

### ISSUE THREAD

**Issue by foohub** [apache/apisix#9972]
### Description

I Installed Kubernetes 1.27.4 on ubuntu 20.04.6. K8s work problem-free but when I tried to install apisix using helm or even with yaml I recieved this error on running etcd pods:

Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  BackOff    10m (x1906 over 15h)   kubelet  Back-off restarting failed container etcd in pod apisix-etcd-0_apisix(28c29c3e-e52b-41e8-a09a-c537c2a365c4)
  Warning  Unhealthy  5m14s (x796 over 15h)  kubelet  Liveness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out
  Warning  Unhealthy  14s (x2684 over 15h)   kubelet  Readiness probe failed: command "/opt/bitnami/scripts/etcd/healthcheck.sh" timed out

Does anyone installed apisix on kuber 1.27.4 sucessfully?

### Environment

- APISIX version (run `apisix:3.4.1-debian-11-r5`):
- Operating system (5.4.0-144-generic #161-Ubuntu SMP Fri Feb 3 14:49:04 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux):
:

**Comment by Revolyssup** [comment]
@foohub Can you show the output of kubectl describe for the failing etcd pod?
