### ISSUE TITLE
Implementing a /health Endpoint for APISIX Deployment on GCP

### ISSUE THREAD

**Issue by michelgokan** [apache/apisix#9974]
### Description

I am encountering an issue while deploying APISIX on Google Cloud Platform (GCP). To set up a subdomain pointing to the APISIX ingress controller, such as `gateway.example.com`, GCP demands the existence of a `/health` endpoint to validate that the service is live; otherwise, it returns an error page.

However, I understand that APISIX does not inherently support a `/health` endpoint (or is it?). Whenever I attempt to access the `/health` endpoint, I receive a `404` error message generated by APISIX.

Can someone guide me on how to resolve this problem and enable GCP to successfully perform health checks on APISIX? Any suggestions or resources would be greatly appreciated.

### Environment

- APISIX version (run `apisix version`): apache/apisix:3.4.0-debian
- Operating system (run `uname -a`): Kubernetes Engine on top of GCP (Docker)
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): docker.io/bitnami/etcd:3.5.7-debian-11-r14
- APISIX Dashboard version, if relevant: apache/apisix-dashboard:3.0.0-alpine
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by moonming** [comment]
You can create a router `/health` refers to https://docs.api7.ai/apisix/getting-started/configure-routes
