### ISSUE TITLE
help request: 服务器etcd异常导致流量nginx等待突增

### ISSUE THREAD

**Issue by swtseaman** [apache/apisix#9976]
### Description

apisix运行很久基本稳定，3个节点上均部署的 etcd + apisix + java应用

最近连续2天出现NG等待数突增的情况，情况发生时间点，Etcd reachable异常，内存被打满，不知道如何排查；烦请各位大牛指导下；

grafana截图如下：
![image](https://github.com/apache/apisix/assets/4599375/2b810caf-d7b0-41f2-9a58-45a0c8d8b689)

![image](https://github.com/apache/apisix/assets/4599375/df90d10b-8fab-4300-8d1e-0e40e0cb4a6f)

### Environment

- APISIX version (run `apisix version`): 3.2.0
- Operating system (run `uname -a`): Linux localhost 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):nginx version: openresty/1.21.4.1
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`): {"version":"3.2.0","boot_time":1682039497,"etcd_version":"3.5.0","hostname":"localhost","id":"a74d7cad-b87e-49ae-82c7-1d35235f5b83"}

**Comment by shreemaan-abhishek** [comment]
Please use English while communicating your issues so that everyone can help you better.
