### ISSUE TITLE
bug: core.response.set_header("Content-Type", "text/html") will add default charset 

### ISSUE THREAD

**Issue by diegozhu** [apache/apisix#9977]
### Current Behavior

core.response.set_header("Content-Type", "text/html")  shows unexpected content-type: text/html; charset=utf-8;

### Expected Behavior

core.response.set_header("Content-Type", "text/html;")   shows expected content-type: text/html;

### Environment

- APISIX version 3.2:
- Operating system centos 7.9:
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by Revolyssup** [comment]
@diegozhu Please provide the apisix route configuration and the path on which request was sent for reproduction.

**Comment by diegozhu** [comment]
> @diegozhu Please provide the apisix route configuration and the path on which request was sent for reproduction.

thanks for your reply

1.   first :
![image](https://github.com/apache/apisix/assets/1610612/9b2eccfc-8883-4004-bab9-2ca9f45f053b)

2.  second:
add a html file with gbk encoding in that path

3. add a route proxy to 127.0.0.1 7758 
4. visit , you will see 'text/html; utf-8' in reponse header

**Comment by diegozhu** [comment]
@Revolyssup   any thoughts ?

**Comment by Revolyssup** [comment]
@diegozhu  In the config, you can set http.charset to `off`.

**Comment by diegozhu** [comment]
@Revolyssup   thanks a lot.
