### ISSUE TITLE
feat: radixtree supports radixtree_host_uri_with_parameter

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#9980]
### Description

Only 3 types of radixtree are supported now. I think radixtree_host_uri_with_parameter should be supported also.
1. radixtree_uri: match route by uri(base on radixtree)
2. radixtree_host_uri: match route by host + uri(base on radixtree)
3. radixtree_uri_with_parameter: like radixtree_uri but match uri with parameters

**Comment by shreemaan-abhishek** [comment]
This looks like a big feature and probably it will require making changes to https://github.com/api7/lua-resty-radixtree.

Would you like to contribute this feature?

**Comment by qihaiyan** [comment]
> This looks like a big feature and probably it will require making changes to https://github.com/api7/lua-resty-radixtree.
> 
> Would you like to contribute this feature?

I can have a try, but maybe it will take a long time.

**Comment by nilimaomni** [comment]
Any update on the proposed support of radixtree_host_uri_with_parameter or any other alternative to consider both host and parameter?
