### ISSUE TITLE
help request: apisix how implement the try_files feature

### ISSUE THREAD

**Issue by zzqCh** [apache/apisix#9989]
### Description

the nginx document  is :
https://nginx.org/en/docs/http/ngx_http_core_module.html#try_files

### Environment

- APISIX version (run `apisix version`):
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
Whar do you want it for? Please describe your use case.

**Comment by zzqCh** [comment]
> Whar do you want it for? Please describe your use case.

I think the advantage of APISIX is that it can replace nginx and supports dynamic features, but I don't see any replacement for try-files at the moment, so I would like to know how to implement the try-files functionality.

**Comment by shreemaan-abhishek** [comment]
Do you have a use case? I do not fully understand the `try-flies` feature, your use case scenario might help me understand.

**Comment by zzqCh** [comment]
> Do you have a use case? I do not fully understand the `try-flies` feature, your use case scenario might help me understand.

Now there is a route，the path is /a, when  a client access /a, the apisix needs to access /a/b and /a/c of the backend service in orderly(if /a/b returns 200 then end the request, otherwise continue with the request /a/b), and /b and /c are actually configured in the try-files plugin of the /a route

**Comment by shreemaan-abhishek** [comment]
This feature isn't yet supported, would you like to submit a PR for this feature?

**Comment by zzqCh** [comment]
> This feature isn't yet supported, would you like to submit a PR for this feature?

I don't know how to implement it, I considered intercept the request (such as before_proxy phase) before forwarding to the upstream, then send requests using resty library, but this approach will cause the upstream_status and other information to be empty, do you have a good solution?
