### ISSUE TITLE
help request: how to read the plugins list opened on a route in my customized plugin?

### ISSUE THREAD

**Issue by qihaiyan** [apache/apisix#9991]
### Description

I'am developing my customized plugin, i want to read all plugins opened on a route, or read a specified plugin opened on a route with plugin's conf data.

### Environment

- APISIX version (run `apisix version`): 3.3.0
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
You can use the Admin API to GET the specific route and parse the response to find the plugins it uses.

**Comment by qihaiyan** [comment]
> You can use the Admin API to GET the specific route and parse the response to find the plugins it uses.

I think it's not a high performance way

**Comment by shreemaan-abhishek** [comment]
There is no other way.

**Comment by Revolyssup** [comment]
@qihaiyan Dataplane and control plane can be deployed separately, the plugins are executed in data plane and admin api is control plane so they don't share any such direct way of in-code communication
