### ISSUE TITLE
help request: Is there any way I can run serverless function multi times in different phases ?

### ISSUE THREAD

**Issue by diegozhu** [apache/apisix#9994]
### Description

 Is there any way I can run serverless function multi times in different phases. something like:

plugins: {
     "serverless-pre-function" :{
            "rewrite": [func1, func2],
            "access": [func1, func2],
            "body_filter": [func1, func2],
     }
}

### Environment

- APISIX version (run `apisix version`):  apisix 3.2
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
No this isn't supported.

**Comment by jiangfucheng** [comment]
it seems duplicate with https://github.com/apache/apisix/issues/9783, I will implement this feature.

**Comment by diegozhu** [comment]
close issue since @jiangfucheng  will implement this feature.
