### ISSUE TITLE
bug: traffic-split plugin does not verify the UpstreamID is valid

### ISSUE THREAD

**Issue by Nobilta** [apache/apisix#9996]
### Current Behavior

when i use traffic-split on a route,if i use a not exist upstream id,it will not verify this upstream id is valid.
`{
    "uri": "/index.html",
    "plugins": {
        "traffic-split": {
            "rules": [
                {
                    "weighted_upstreams": [
                        {
                            "upstream_id": "abcdefg",//this upstreamid is not exist,but this request will success
                            "weight": 1
                        },
                        {
                            "weight": 1
                        }
                    ]
                }
            ]
        }
    },
    "upstream_id": "abcdefg",//this upstreamid is not exist,but this request will failed
}` 

### Steps to Reproduce

set traffic-split plugin on route,and set a not exist upstreamid

### Environment

- APISIX version (run `apisix version`):3.3
- Operating system (run `uname -a`):
- OpenResty / Nginx version (run `openresty -V` or `nginx -V`):
- etcd version, if relevant (run `curl http://127.0.0.1:9090/v1/server_info`):
- APISIX Dashboard version, if relevant:
- Plugin runner version, for issues related to plugin runners:
- LuaRocks version, for installation issues (run `luarocks --version`):

**Comment by shreemaan-abhishek** [comment]
I could reproduce this, let me bring a fix.
